### ISSUE TITLE
feature request for promtool: find out which metric weighs most when encountering "sample limit exceeds"

### ISSUE THREAD

**Issue by chenlujjj** [prometheus/prometheus#10000]
## Proposal
**Use case. Why is this important?**

*“Nice to have” is not a good use case. :)*

Sometimes we encounter the scraping failure problem caused by  "sample limit exceeds", and we want to know which metric makes up the biggest part of sample amout. I have written a go script for this: https://github.com/chenlujjj/samplelimit.
Maybe this feature can be added to promtool ?

**Comment by LeviHarrison** [comment]
I think this is a cool idea, maybe under the name of `check weight` or something.

cc @JessicaGreben @dgl

**Comment by LeviHarrison** [comment]
Actually, this fits better under the `debug metrics` command, possibly part of the output it writes.

**Comment by chenlujjj** [comment]
I will check the code related to `debug metrics` command, and may implement this feature this weekend.

**Comment by LeviHarrison** [comment]
Great! Thanks.

**Comment by JessicaGreben** [comment]
@chenlujjj sounds like a good idea to me. thanks!

**Comment by JessicaGreben** [comment]
@LeviHarrison why call it `weight`? I would call it `check cardinality`.Thoughts?

**Comment by LeviHarrison** [comment]
I think having it as a subcommand of `check metrics` is good. 

My issue is with calling it "cardinality". I see cardinality as the number of unique variants of a given metric there are (as partitioned by labels). But, this command doesn't take just one metric into consideration, it evaluates all the metrics from a target. Therefore, I think it's more appropriate to call it "weight", as it ranks a collection of metrics by how much of the scrape they take up.

Just my thoughts, feel free to take it any direction.

**Comment by juliusv** [comment]
@chenlujjj Off-topic, but someone should say it: congrats on creating Prometheus issue 10000! :partying_face:
