### ISSUE TITLE
labelmap is not working well for node label start with number

### ISSUE THREAD

**Issue by ejianlv** [prometheus/prometheus#10010]
1, In K8s environment, if we define a node label "**5gc-abc-se/vnf=xyz**", it is a valid node label according to https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/

2, due to we have pm job relabel_configs as below:
        relabel_configs:
          - action: labelmap
            regex: __meta_kubernetes_node_label_(.+)

3, the node label will be convert to "5gc_abc_se_vnf": "xyz"
        "metric": {
          "5gc_abc_se_vnf": "xyz",
          "__name__": "kubelet_volume_stats_used_bytes",
          "beta_kubernetes_io_arch": "amd64",

4, but "**5gc_abc_se_vnf**" is not a valid metrics label according to 
https://prometheus.io/docs/concepts/data_model/#metric-names-and-labels
Label names may contain ASCII letters, numbers, as well as underscores. They must match the regex [a-zA-Z_][a-zA-Z0-9_]*. Label names beginning with __ are reserved for internal use.

5, if we have a federation job defined in another Prometheus, and the the target is the one of this Prometheus service. we will find error "lastError": "expected label name, got \"INVALID\"", as below:
      {
        "discoveredLabels": {
          "__address__": "prometheus.monitoring:9090",
          "__metrics_path__": "/federate",
          "__param_match[]": "{namespace=\"test\"}",
          "__scheme__": "http",
          "job": "federate"
        },
        "labels": {
          "instance": "prometheus.monitoring:9090",
          "job": "federate"
        },
        "scrapePool": "federate",
        "scrapeUrl": http://prometheus.monitoring:9090/federate?match%5B%5D=%7Bnamespace%3D%22test%22%7D,
        "globalUrl": http://prometheus.monitoring:9090/federate?match%5B%5D=%7Bnamespace%3D%22test%22%7D,
        "lastError": "expected label name, got \"INVALID\"",
        "lastScrape": "2021-12-06T06:10:47.716774956Z",
        "lastScrapeDuration": 1.159234488,
        "health": "down"
      },

I think labelmap should be improved, if the node label start with number, it should add "_" automatically to avoid the issue above.

for example node label "**5gc-abc-se/vnf=xyz**" should be convert to metrics label "**_5gc_abc_se_vnf**": "xyz", I think "_5gc_abc_se_vnf" is valid metric label.

**Comment by roidelapluie** [comment]
Unfortunately, we can not do this, it could break people:
- That could collision with existing labels
- That could be fixed in another way by subsequent relabeling rules.
 - Last but not least, we can not decide for users how to sanitize labels. There could be other things than this making invalid labels, and sanitizing can depend on the language and other things.

I such, I propose you two workaround and close this issue.

Workaround 1, your proposal: 

```
- action: labelmap
  regex: _meta_kubernetes_node_label_(.+)
- action: labelmap
  regex: [0-9](.+)
  replacement:  _$1
```

Workaround 2, avoid the labels in the first place:

```
- action: labelmap
  regex: _meta_kubernetes_node_label_([a-z].+)
```

Thank you for your report!

**Comment by ejianlv** [comment]
Got it and thanks a lot.

**Comment by ejianlv** [comment]
My proposal:

from:

```
- action: labelmap
  regex: _meta_kubernetes_node_label_(.+)
```

change to:

```
- action: labelmap
  regex: __meta_kubernetes_node_label_([0-9].+)
  replacement: _${1}
- action: labelmap
  regex: __meta_kubernetes_node_label_([a-zA-Z].+)
```

BRs/Jian
