### ISSUE TITLE
relabel_config regex with underscore not working

### ISSUE THREAD

**Issue by mccricardo** [prometheus/prometheus#10019]
**What did you do?**
Example config:

```yaml
- action: labeldrop
  regex: 'c(.*)'
```

**What did you expect to see?**
Drop labels **container**  and **connection_security_policy**.

**What did you see instead? Under which circumstances?**
Only label **container** was dropped. Happens with every action.

**Environment**

* System information:
Kubernetes. Image: quay.io/prometheus/prometheus.

* Prometheus version:
```sh
prometheus, version 2.32.0 (branch: HEAD, revision: 52c693a63be1096158667557f934d2d0d207c4d9)
  build user:       root@03a85e24f43f
  build date:       20211214-15:58:16
  go version:       go1.17.5
  platform:         linux/amd64
  ```

**Comment by roidelapluie** [comment]
Can we please see your prometheus configuration?

I think the reason might be that `container` comes from service discovery, therefore it should be dropped with `relabel_configs`. `connection_security_policy`, could come from the scraped metrics, and should be dropped with `metric_relabel_configs`.

**Comment by mccricardo** [comment]
Thank you for the reply @roidelapluie. Let me check on that and I'll get back to you.

**Comment by mccricardo** [comment]
Spot on @roidelapluie. Thank you so much. I'll be closing the issue.
