### ISSUE TITLE
Log error

### ISSUE THREAD

**Issue by EnicZhang** [prometheus/prometheus#10024]
**What did you do?**

**What did you expect to see?**

**What did you see instead? Under which circumstances?**

**Environment**

* System information:

	insert output of `uname -srm` here

* Prometheus version:

	insert output of `prometheus --version` here

* Alertmanager version:

	insert output of `alertmanager --version` here (if relevant to the issue)

* Prometheus configuration file:
```
insert configuration here
```

* Alertmanager configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```

**Comment by LeviHarrison** [comment]
Could you please add some more details about this error? It's hard to figure out what's going on just based on the title of the issue.

**Comment by EnicZhang** [comment]
https://github.com/prometheus/prometheus/blob/main/documentation/examples/remote_storage/remote_storage_adapter/main.go
At line 217 of this file ,"Read Error " should be changed to "Write Error".

**Comment by LeviHarrison** [comment]
"Read Error" is correct. The first step in the handler code for the `/write` endpoint which you're referring to is to read the body of the write request. Therefore, if there is an error, it's an error _reading_ the body.

**Comment by gf-zhangdd** [comment]
Indeed, thanks @LeviHarrison

**Comment by EnicZhang** [comment]
Indeed, thanks. @LeviHarrison

**Comment by LeviHarrison** [comment]
No problem.
