### ISSUE TITLE
Panic in TestChunkDiskMapper_WriteChunk_Chunk_IterateChunks

### ISSUE THREAD

**Issue by charlesxsh** [prometheus/prometheus#10039]
**What did you do?**
Trigger TestChunkDiskMapper_WriteChunk_Chunk_IterateChunks
**What did you expect to see?**
PASS
**What did you see instead? Under which circumstances?**
panic as follows:

```
panic: runtime error: slice bounds out of range [:104326] with capacity 104293 [recovered]
	panic: runtime error: slice bounds out of range [:104326] with capacity 104293

goroutine 6 [running]:
testing.tRunner.func1.2(0x6451c0, 0xc000014108)
	/usr/local/go/src/testing/testing.go:1143 +0x335
testing.tRunner.func1(0xc00024db80)
	/usr/local/go/src/testing/testing.go:1146 +0x4c2
panic(0x6451c0, 0xc000014108)
	/usr/local/go/src/runtime/panic.go:965 +0x1b9
github.com/prometheus/prometheus/tsdb/chunks.TestChunkDiskMapper_WriteChunk_Chunk_IterateChunks(0xc00024db80)
	/repos/prometheus/tsdb/chunks/head_chunks_test.go:125 +0xcf2
testing.tRunner(0xc00024db80, 0x671d80)
	/usr/local/go/src/testing/testing.go:1193 +0xef
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1238 +0x2b5
```
**Environment**

* System information:

	insert output of `uname -srm` here

* Prometheus version:

	insert output of `prometheus --version` here

* Alertmanager version:

	insert output of `alertmanager --version` here (if relevant to the issue)

* Prometheus configuration file:
```
insert configuration here
```

* Alertmanager configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```

**Comment by codesome** [comment]
@charlesxsh what Prometheus version/commit are you testing this on?

**Comment by charlesxsh** [comment]
@codesome e0f1506254688cec85276cc939aeb536a4e029d1

**Comment by beorn7** [comment]
Hello from the bug scrub!

This doesn't seem to have happened in years. Closing.
