### ISSUE TITLE
nil deference in TestWriteStorageLifecycle

### ISSUE THREAD

**Issue by charlesxsh** [prometheus/prometheus#10033]
**What did you do?**
Trigger test TestWriteStorageLifecycle
**What did you expect to see?**
PASS
**What did you see instead? Under which circumstances?**

```
invalid memory address or nil pointer dereference [signal SIGSEGV: segmentation violation]
Unable to propagate EXC_BAD_ACCESS signal to target process and panic (see https://github.com/go-delve/delve/issues/852)
Stack:
	0  0x0000000001c8d345 in github.com/prometheus/prometheus/storage/remote.(*WriteStorage).ApplyConfig
	    at /Users/xsh/code/prometheus-fork/storage/remote/write.go:172
	1  0x0000000001cb9707 in github.com/prometheus/prometheus/storage/remote.TestWriteStorageLifecycle
	    at /Users/xsh/code/prometheus-fork/storage/remote/write_test.go:208
	2  0x00000000011845c3 in testing.tRunner
	    at /usr/local/go/src/testing/testing.go:1193
```

The reason is because 
```
conf := &config.Config{
		GlobalConfig: config.DefaultGlobalConfig,
		RemoteWriteConfigs: []*config.RemoteWriteConfig{
			&config.DefaultRemoteWriteConfig,
                         // missing assignment for URL
		},
	}
```

so when the code executed to ApplyConfig's 
```
endpoint := rwConf.URL.Redacted()   <---- rwConf.URL is nil
```

**Environment**

* System information:

	insert output of `uname -srm` here

* Prometheus version:

	insert output of `prometheus --version` here

* Alertmanager version:

	insert output of `alertmanager --version` here (if relevant to the issue)

* Prometheus configuration file:
```
insert configuration here
```

* Alertmanager configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```

**Comment by zamariola** [comment]
I've followed the guidelines proposed here (https://github.com/prometheus/prometheus/pull/10037) to create a PR with those helper functions. it's supposed to remove all nil pointer dereference exceptions in the remote package.
