### ISSUE TITLE
HashMod sum64 foobar

### ISSUE THREAD

**Issue by miekg** [prometheus/prometheus#1004]
This `shift` that I added is wrong :(
https://github.com/prometheus/prometheus/blob/master/retrieval/relabel.go#L88

It shifts too much, discarding much of the glorious hash input. If have a PR almost ready to just do a simple xor of all the hash bytes, which looks simpler and works better. Finishing the last bit in the tests.

**Comment by juliusv** [comment]
Wouldn't a XOR have bad distribution properties as well? If you just switch the position of some of the input bytes, the output hash will be the same. Basically, any permutation of the input bytes will produce the same output :)

**Comment by juliusv** [comment]
Ah I read you wrong. You want to XOR the hash, not the input.

**Comment by miekg** [comment]
yes, xor that hashed bytes.
