### ISSUE TITLE
Persistent data problem of Prometheus

### ISSUE THREAD

**Issue by wizard2318** [prometheus/prometheus#10094]
**What did you do?**
The persistent data of Prometheus only lasts for one day. Prometheus Prometheus The configuration of yaml file is retention: 7d, which is still useless

**What did you expect to see?**
You can see the data of Prometheus for 7 days

**What did you see instead? Under which circumstances?**

**Environment**

* System information:

	centos 7.6

* Prometheus version:

	v2.20.0

* Alertmanager version:

	insert output of `alertmanager --version` here (if relevant to the issue)

* Prometheus configuration file:
```
/root/kube-prometheus/manifests/prometheus-prometheus.yaml
```

* Alertmanager configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
The persistent data of Prometheus only lasts for one day. Prometheus Prometheus The configuration of yaml file is retention: 7d, which is still useless

**Comment by jeyrce** [comment]
@wizard2318 Have you check the datetime on your system?

**Comment by codesome** [comment]
@wizard2318 the retention can only be set via command line flags at the moment and cannot be done by the yaml config. Are you missing that flag? `--storage.tsdb.retention.time=7d`. And do you have size retention enabled by any chance?

**Comment by beorn7** [comment]
Hello from the bug scrub!

No follow up in 2.5y, closing.
