### ISSUE TITLE
Tag docker builds on dockerhub with version information

### ISSUE THREAD

**Issue by keegancsmith** [prometheus/prometheus#1009]
Just relying on `master` and `latest` is living dangerously. Would be great if I could pin the version of Prometheus I use when I use it through docker. This is similiar to all the other tools under `prom` in dockerhub (pushgateway, promdash, alertmanager)

**Comment by juliusv** [comment]
Agreed in general, someone just needs to get to it. See also https://github.com/prometheus/prometheus/issues/926

**Comment by fabxc** [comment]
Should be closed: https://hub.docker.com/r/prom/prometheus/tags/
