### ISSUE TITLE
kubernetes_sd_config namespace configuration for "current namespace"

### ISSUE THREAD

**Issue by edeandrea** [prometheus/prometheus#10118]
## Proposal
The current [kubernetes_sd_config](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#kubernetes_sd_config) allows someone to configure a set of namespaces to watch and monitor. If omitted, all namespaces are used.

Several times now I've run into an issue where I only wanted to monitor things in the current namespace where prometheus is deployed. The problem with that, though, is that my prometheus configuration is re-used and I can't statically define the name of a namespace ahead of time. I'd like prometheus to just monitor the current namespace.

As a workaround I've had to switch away from using `kubernetes_sd_config` and manually configure all my services as separate `static_config`s.

In many instances monitoring all namespaces won't work because the users/service accounts assigned to a workload don't have cluster-wide view/list permissions. They only have permissions on the current namespace.

This would be a great enhancement and would simplify lots of things.

**Comment by roidelapluie** [comment]
This has been implemented recently but not released yet.

**Comment by edeandrea** [comment]
Thank you! Do you happen to know the issue/PR # for that?

**Comment by fpetkovski** [comment]
This is the PR implementing the feature: https://github.com/prometheus/prometheus/pull/9881

**Comment by edeandrea** [comment]
Thanks!
