### ISSUE TITLE
PromQL: Define and document behavior of `quantile` and `histogram_quantile` with φ=NaN

### ISSUE THREAD

**Issue by beorn7** [prometheus/prometheus#10117]
**What did you do?**

`quantile(NaN, some_metric)`

`histogram_quantile(NaN, som_histogram_bucket)`

**What did you expect to see?**

Good question. I think it would be most reasonable to let those queries return `NaN`. Those queries are “obviously” nonsensical. But they are valid PromQL, and it would be good if they had a defined and documented behavior.

**What did you see instead? Under which circumstances?**

`quantile(NaN, some_metric)` weirdly returns an error:

```
Error executing query: unexpected error: runtime error: index out of range [-9223372036854775808]
```

Even more weirdly, `histogram_quantile(NaN, som_histogram_bucket)` returns `1000000000`. :exploding_head: 

**Environment**

* Prometheus version:

	2.31.1

**Comment by 123vivekr** [comment]
I'd like to take this up if its free

**Comment by LeviHarrison** [comment]
Looks like no one else is working on it so you're free to go ahead!

**Comment by 123vivekr** [comment]
Hi, I'd like to clarify my assumptions before starting work. 

The proposed changes:
- `quantile(NaN, some_metric)` and `histogram_quantile(NaN, som_histogram_bucket)` should return `NaN`
- document the above behaviour for `quantile` [here](https://prometheus.io/docs/prometheus/latest/querying/operators/#aggregation-operators) and `historgram_quantile` [here](https://prometheus.io/docs/prometheus/latest/querying/functions/#histogram_quantile)

**Comment by beorn7** [comment]
Yes, I think that's the right course of action.

**Comment by jyz0309** [comment]
I have tried to resolve this issue in #10295 .
