### ISSUE TITLE
Add proxy support for AWS EC2 Service Discovery

### ISSUE THREAD

**Issue by zrc210** [prometheus/prometheus#10125]
## Proposal
**Use case. Why is this important?**

The AWS EC2 Service Discovery Configuration does not allow users to specify an http(s) proxy for the underlying AWS EC2 API calls. In environments where VPC egress is controlled, either VPC-Endpoints have to be used to allow egress to AWS Services, or, an explicit proxy (like squid or envoy) can be configured to allow egress to the AWS API's.

Similar features are enabled for[ azure_sd_config](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#azure_sd_config)

I see https://github.com/prometheus/prometheus/issues/2026 is closed, as is https://github.com/prometheus/prometheus/pull/2027.

I don't think setting `HTTP_PROXY` or `HTTPS_PROXY` environment variables is desirable, as we only want the AWS SDK instance used for EC2 Service Discovery to use the proxy. Additionally, the proxy shouldn't affect the Credential Chain (using the Task or Instance Metadata to use the IAM Role).

[AWS has documentation regarding configuring a proxy with the golang sdk](https://aws.github.io/aws-sdk-go-v2/docs/configuring-sdk/custom-http/#configuring-a-proxy).

**Comment by LeviHarrison** [comment]
We ended up adding the entire standard HTTP client to the Azure Discovery in https://github.com/prometheus/prometheus/pull/9267, and I think that's probably what we'll want to do here as well. This should work: https://aws.github.io/aws-sdk-go-v2/docs/configuring-sdk/custom-http/#overriding-during-configuration-loading.
