### ISSUE TITLE
config: Need escaping to avoid environment variable expansion in external labels

### ISSUE THREAD

**Issue by beorn7** [prometheus/prometheus#10122]
If I set the feature flag `--enable-feature=expand-external-labels`, I get the nice and sweet expansion of environment variables in configured `external_labels`.

Should I require a literal `$` in one of my label values, I can simply not set the feature flag.

But what if I want the expansion in some label values but require a literal `$` in others?

Also, we would like to promote the feature to stable and get rid of the feature flag eventually (which we can only do with v3 because it is a breaking change). Once we have done so, we definitely need a way to specify a literal `$`.

I propose to use the same escaping as in Bash, i.e. a literal `$` can be created via `\$`.

(I'm actually surprised that https://pkg.go.dev/os#Expand doesn't provide any escaping out of the box.)

**Comment by fpetkovski** [comment]
The `\$` sequence definitely looks more familiar and consistent with other tools, but using it in go would require replacing the `\$` sequence with a reserved environment variable (e.g. `PROMETHEUS_DOLLAR`), and setting the value of that environment variable value to `$`. The os.Expand function would then work as desired.

A cleaner approach might be to use `$$` to escape the `$` character, and explicitly match the `$` value in os.Expand: https://github.com/prometheus/prometheus/pull/10129/files.

This is just my assessment, I am open to any sort of feedback.

**Comment by LeviHarrison** [comment]
Although `$$` is suitable, as you pointed out `\$` is what would be expected and for a function as simple as `os.Expand` I think it could be worth incorporating a modified copy into our codebase to support it, like this: https://go.dev/play/p/LPNSoyThK4P. All I needed to do was add `&& (j == 0 || s[j-1] != '\\')` on line 17 and there's escaping with `\` now.

> (I'm actually surprised that pkg.go.dev/os#Expand doesn't provide any escaping out of the box.)

Doesn't seem like it will be added either: https://github.com/golang/go/issues/43482

**Comment by roidelapluie** [comment]
I disagree that `\$`is what would be expected. $$ is a common form of escaping as well, and is easier to type.

**Comment by beorn7** [comment]
Hmmm…

```bash
$ echo $USER
beorn
$ echo $$USER
2095USER
$ echo \$USER
$USER
```

Given that environment variable expansion is in "shell territory", I think we should follow shell conventions. `$$` in bash expands to the PID. `\$` expands to a literal `$`. Even if we don't support expansion of `$$` to the PID, I would not give it a completely different meaning.

**Comment by roidelapluie** [comment]
Escaping is very complex and if we really want it, we would need to make `\\` escape as `\`. I would be in favour of not escaping anything or just allowing $$ because it avoids the complex `\\` issues and possibly others. I disagree that this is a shell territory, and in e g.  Makefiles, $ is escaped by $$.

**Comment by LeviHarrison** [comment]
I will point out that the Docker Compose config, which is probably the closest to our config, does use `$$` for escaping: https://docs.docker.com/compose/compose-file/compose-file-v2/#variable-substitution.

**Comment by fpetkovski** [comment]
It also looks like the playground example does not really escape properly. The modified function returns `\$hi`, but I expected it to return `$hi`. So if the intent is to use `\$`, there will be a bit more work to be done.

**Comment by LeviHarrison** [comment]
Yeah, that was a quick pass so it's not fully correct.

**Comment by beorn7** [comment]
I wouldn't really use Makefiles as a role model. They have a bunch of quite unique syntactical features, mostly due to ancient history. But I take the point for Docker Compose. Also, requiring only one escaping rule has its merits, too. So yeah, I would be fine with the `$$` solution, too.

Again, it's a pity that the Go library function missed to settle this point.

**Comment by LeviHarrison** [comment]
`$$` sounds good to me as well.
