### ISSUE TITLE
Is it possible to add http client configure to disable HTTP2 in Remote_Write Configure?

### ISSUE THREAD

**Issue by siyyang-ms** [prometheus/prometheus#10155]
## Proposal
**Use case. Why is this important?**
*“Nice to have” is not a good use case. :)*

 Currently, if the remote write receives Stream Error HTTP1.1_Required, it would retry with HTTP2, and it would never work.

**Comment by testn** [comment]
Can you try setting the following environment variable to see if it works?

`GODEBUG=http2client=0`

**Comment by siyyang-ms** [comment]
> 

It does not work whether I only set GODEBUG=http2client=0 or GODEBUG=http2client=0;http2server=0.

I can see the runtime info GODEBUG from PromethuesURL/status to verify that those environment variables are set successfully.

**Comment by testn** [comment]
Can you try to turn on the debugging?

`GODEBUG=http2debug=2 `

**Comment by siyyang-ms** [comment]
Hi, I have added GODEBUG as follows
<html>
<body>


GODEBUG | http2client=0;http2debug=2
-- | --



</body>
</html>

But the promethues still keeps retry with **http2**!

2022/01/12 09:20:13 **http2**: Transport encoding header ":authority" = "my remote write endpoint"
2022/01/12 09:20:13 http2: Transport encoding header ":method" = "POST"
2022/01/12 09:20:13 http2: Transport encoding header ":path" = "my remote write endpoint suffix"
2022/01/12 09:20:13 http2: Transport encoding header ":scheme" = "https"
2022/01/12 09:20:13 http2: Transport encoding header "user-agent" = "Prometheus/2.32.1"
2022/01/12 09:20:13 http2: Transport encoding header "x-prometheus-remote-write-version" = "0.1.0"
2022/01/12 09:20:13 http2: Transport encoding header "content-encoding" = "snappy"
2022/01/12 09:20:13 http2: Transport encoding header "content-type" = "application/x-protobuf"
2022/01/12 09:20:13 http2: Transport encoding header "content-length" = "8019"
2022/01/12 09:20:13 http2: Framer 0xc0012822a0: wrote HEADERS flags=END_HEADERS stream=25 len=9
2022/01/12 09:20:13 http2: Framer 0xc0012822a0: wrote DATA flags=END_STREAM stream=25 len=8019 data="\x89\xc7\x03\xf0q\nk\n\"\n\b__name__\x12\x16go_gc_duration_seconds\n\x1a\n\binstance\x12\x0elocalhost:9090\n\x11\n\x03job\x12\nprometheus\n\r\n\bquantile\x12\x010\x12\a\x10\x91\xf4\xd7\xec\xe4/\nn\n\"\n\xfem\x00Bm\x00\b\x10\n\b\x15m\x18\x040.25\x12\a\x11p\x00m\xfe\xdd\x00N\xdd\x00\x00\x0f\x1dp\b\x030.\x1do\x00w\xfeo\x00No\x00:\xdf\x00075\x12\x10\t6\x8fh\xa7\x8b\xb9@?\x11\xe8\x00t\xfey\x00Ny\x002\xc5\x01(1\x12\x10\tK\xf5\xae\x8b\xec\x94x\x15v\bi\n&];\x00\x1aV;\x02\x10_sum\n\xb6?\x02$\x12\x10\t2\a\x9c\x00\x1e\xacz\x15k\bk\n(\x1dk\x00\x1cZk\x00\x10" (7763 bytes omitted)
2022/01/12 09:20:13 http2: Framer 0xc0012822a0: read WINDOW_UPDATE stream=25 len=4 incr=2039
2022/01/12 09:20:13 http2: Transport received WINDOW_UPDATE stream=25 len=4 incr=2039
2022/01/12 09:20:13 http2: Framer 0xc0012822a0: read WINDOW_UPDATE len=4 (conn) incr=2039
2022/01/12 09:20:13 http2: Transport received WINDOW_UPDATE len=4 (conn) incr=2039
2022/01/12 09:20:13 http2: Framer 0xc0012822a0: read WINDOW_UPDATE stream=25 len=4 incr=2048
2022/01/12 09:20:13 http2: Transport received WINDOW_UPDATE stream=25 len=4 incr=2048
2022/01/12 09:20:13 http2: Framer 0xc0012822a0: read WINDOW_UPDATE len=4 (conn) incr=2048
2022/01/12 09:20:13 http2: Transport received WINDOW_UPDATE len=4 (conn) incr=2048
2022/01/12 09:20:13 http2: Framer 0xc0012822a0: read WINDOW_UPDATE stream=25 len=4 incr=2048
2022/01/12 09:20:13 http2: Transport received WINDOW_UPDATE stream=25 len=4 incr=2048
2022/01/12 09:20:13 http2: Framer 0xc0012822a0: read WINDOW_UPDATE len=4 (conn) incr=2048
2022/01/12 09:20:13 http2: Transport received WINDOW_UPDATE len=4 (conn) incr=2048
2022/01/12 09:20:13 http2: Framer 0xc0012822a0: read WINDOW_UPDATE len=4 (conn) incr=1884
2022/01/12 09:20:13 http2: Transport received WINDOW_UPDATE len=4 (conn) incr=1884
2022/01/12 09:20:13 http2: Framer 0xc0012822a0: read RST_STREAM stream=25 len=4 ErrCode=HTTP_1_1_REQUIRED
2022/01/12 09:20:13 http2: Transport received RST_STREAM stream=25 len=4 ErrCode=HTTP_1_1_REQUIRED
2022/01/12 09:20:13 RoundTrip failure: stream error: stream ID 25; HTTP_1_1_REQUIRED; received from peer

**Comment by LeviHarrison** [comment]
Setting the environment variable `PROMETHEUS_COMMON_DISABLE_HTTP2=1` disables HTTP2 from our side. Maybe that will help.

**Comment by roidelapluie** [comment]
This might be a bug in our HTTP client, do you have a way to reproduce it?

**Comment by siyyang-ms** [comment]
> Setting the environment variable `PROMETHEUS_COMMON_DISABLE_HTTP2=1` disables HTTP2 from our side. Maybe that will help.

It does not solve my case. When I set this environment variable, the error changes to "local error: tls: no renegotiation"

**Comment by siyyang-ms** [comment]
> This might be a bug in our HTTP client, do you have a way to reproduce it?

@roidelapluie You might try set GODEBUG and verify the log whether the remote write http client is using http2 or http1.
<html>
<body>


GODEBUG | http2client=0;http2debug=2
-- | --



</body>
</html>

**Comment by testn** [comment]
What do you use for the server side? If you cannot resolve it, fronting the server side with nginx or haproxy might help

**Comment by siyyang-ms** [comment]
> What do you use for the server side? If you cannot resolve it, fronting the server side with nginx or haproxy might help

Yes. I solved this problem by adding an nginx proxy. The server side is IIS server.

**Comment by roidelapluie** [comment]
Tt is now possible to disable http2. use enable_http2: false.
