### ISSUE TITLE
Tracking issue for promotion/demotion of experimental features

### ISSUE THREAD

**Issue by beorn7** [prometheus/prometheus#10167]
_The idea of this issue is to assign it to the upcoming release shepherd and use it to hand over state from one release shepherd to the next, updating this original post (rather than adding comments). If you know a better way of doing this, feel free to implement it and port the information here over to the better way._

### `--scrape.adjust-timestamps` and `--scrape.timestamp-tolerance`

__State:__ Blocked on decision for default value.

These are not feature flags, but regular, albeit hidden, flags, marked as "Experimental. This flag will be removed in a future release.". However, as per the dev-summit, the plan is to remove only `--scrape.adjust-timestamps`, as `--scrape.timestamp-tolerance` alone is enough to control the feature (`--scrape.timestamp-tolerance=0` will disable timestamp adjustment). Before we can do so, we want to find out a good default value (as the feature should be "on by default"). From the dev-summit notes:

> CONSENSUS: We will promote `-scrape.timestamp-tolerance` to stable and remove `-scrape.adjust-timestamps`. Before we do so, we will try to find a reasonable default value and reach out to users about donating real-world data.

### Feature flag `remote-write-receiver`

__State:__ Deprecated.

This feature flag should be removed in v2.34. In v2.33, it creates a warning to use `--web.enable-remote-write-receiver` instead, but it still takes effect. In v2.34, it should be a no-op (i.e. the remote write receiver will be inactive if the feature flag is set but _not_ `--web.enable-remote-write-receiver`), and a corresponding warning should be issued.

### Feature flag `memory-snapshot-on-shutdown`

__State:__ To be vetted.

Talk to @codesome . It was still too new to promote in v2.33. Also, it looks this should not just be promoted to "always on", but it might be useful to still give the user a choice (via a regular flag).

### Feature flag `expand-external-labels`

__State:__ To be vetted. 

No longer blocked on #10122/#10129. Probably should be deprecated in v2.35.

Once the issue above is resolved, this can be promoted to stable. However, as the behavior with the feature enabled can break existing setups, it still needs to be opted in explicitly (via a regular flag -- which can only be removed in v3.0.0).

### Feature flag `new-service-discovery-manager`

__State:__ To be vetted.

This feels fairly new still. We have to find out if it is stable enough. Once it is, we can probably promote this to "always on".

_(Note that there are more experimental features, but for those, there is not state to hand over.)_

**Comment by LeviHarrison** [comment]
> If you know a better way of doing this, feel free to implement it and port the information here over to the better way.

We could do it as a project with different columns for "To be vetted," "Blocked," "Deprecated," but this is probably fine.

**Comment by roidelapluie** [comment]
> ### Feature flag `remote-write-receiver`
> **State:** Deprecated.
> 
> This feature flag should be removed in v2.34. In v2.33, it creates a warning to use `--web.enable-remote-write-receiver` instead, but it still takes effect. In v2.34, it should be a no-op (i.e. the remote write receiver will be inactive if the feature flag is set but _not_ `--web.enable-remote-write-receiver`), and a corresponding warning should be issued.

This seems too soon to me, we should wait a couple of releases before removing the feature flag.

**Comment by LeviHarrison** [comment]
> ### Feature flag `new-service-discovery-manager`
> **State**: To be vetted.
>
> This feels fairly new still. We have to find out if it is stable enough. Once it is, we can probably promote this to "always on".

My impression of this flag was that it was more of a minor protection for a mechanism we didn't consider was too prone to failure, and given that we've only seen one bug (https://github.com/prometheus/prometheus/issues/9654) a day after the release, I think we should consider promoting this to stable sooner rather than later. Of course, I don't know how extensively it's been tested.

**Comment by beorn7** [comment]
WRT using a GH project: Good idea. We can see how convoluted things get here.

WRT deprecation timing (in this case remote-write-receiver): Given that feature flags are inherently volatile, I don't think we need to wait for longer than one minor release. IMHO it just increases the management overhead for us, while it won't really significantly reduce the number of users hit by surprise. Perhaps others could chime in on this so that we get an idea what practice to follow.

**Comment by csmarchbanks** [comment]
Since there was concern expressed around removing the remote-write-receiver flag in v2.34 I will leave it for another release. Does removing it in v2.35 sound ok to everyone? If so I will update this issue.

I believe the bug @codesome needs to fix is related to memory-snapshot-on-shutdown so that should be left for at least another release as well.

**Comment by beorn7** [comment]
Hello from the bug scrub!

With no movement here in 2.5y, my (meta) experiment of tracking experimental features in this way clearly failed. Closing.
