### ISSUE TITLE
Link to pre-filtered alert-overview

### ISSUE THREAD

**Issue by chlunde** [prometheus/prometheus#10171]
## Proposal

To allow good a good UX for developers and integration between different webapps, we would like to link to a pre-filtered alert view.

### Use case
A concrete use case is to have one application link to a the alert list pre-filtered with the name of a specific microservice. This will show the developer what kind of alerts are currently defined for their service.

I think this should show:
* Are there any specific alerts defined for this microservice (the pattern is part of the expression, labels or annotations)
* _Probably:_ Are there generic alerts firing for that microservice now (one of the firing alerts has this service name as part of a label value)

In #10142, the alert page is reworked to allow for filtering. After that is merged, or as a part of that PR, it would be nice to include this option.

cc @Nexucis

**Comment by Nexucis** [comment]
Yeah I think it's ok do it (@juliusv yell you have something against it ;) )

For consistency, we should be able to pre-filtered the Target and Service Discovery page that have the same search bar.

**Comment by juliusv** [comment]
@Nexucis I think generally it's a good idea. Just take into account that we already sync the URL parameters + page content on the /graph page in both directions, so it's probably a good idea to use a similar approach on the other pages and / or generalize the existing code for that in Prometheus.

**Comment by Nexucis** [comment]
totally agree @juliusv, the behavior should be exactly the same than in the graph page !

**Comment by AndreSPy1** [comment]
Hello, good morning, is it possible to work on this issue? to separate it, thanks

**Comment by Nexucis** [comment]
yes of course @AndreSPy1 so far nobody is working on it, so you can totally do it.

**Comment by AndreSPy1** [comment]
> sí, por supuesto, @AndreSPy1 hasta ahora nadie está trabajando en eso, así que puedes hacerlo por completo.

thaks :)

**Comment by MasonLegere** [comment]
Should this issue be closed out following the merge of PR 10613? https://github.com/prometheus/prometheus/pull/10613

**Comment by Nexucis** [comment]
Yes indeed. This issue can be closed now.
