### ISSUE TITLE
TestTemplateExpansion is failing on non-amd64 architectures

### ISSUE THREAD

**Issue by sergiodj** [prometheus/prometheus#10185]
**What did you do?**

I'm building prometheus on an Ubuntu GNU/Linux distro (Focal).  I'm actually building a snap for prometheus, but that shouldn't matter for the problem at hand.

**What did you expect to see?**

As usual, I expected to see successful builds for all architectures that we're supporting (amd64, arm64, s390x and ppc64le).

**What did you see instead? Under which circumstances?**

On non-amd64 builds, I see the following testcase failure:

```
--- FAIL: TestTemplateExpansion (0.01s)
    template_test.go:485: 
                Error Trace:    template_test.go:485
                Error:          Not equal: 
                                expected: "0s:-1s:1s:14d 6h 56m 7s:-106751991167300d -15h -30m -8s:"
                                actual  : "0s:-1s:1s:14d 6h 56m 7s:106751991167300d 15h 30m 7s:"
                            
                                Diff:
                                --- Expected
                                +++ Actual
                                @@ -1 +1 @@
                                -0s:-1s:1s:14d 6h 56m 7s:-106751991167300d -15h -30m -8s:
                                +0s:-1s:1s:14d 6h 56m 7s:106751991167300d 15h 30m 7s:
                Test:           TestTemplateExpansion
FAIL
FAIL    github.com/prometheus/prometheus/template       0.200s
```

The build succeeds on amd64.

**Environment**

* System information:

Ubuntu Focal (20.04), with Go 1.17, NodeJS 16.13.2.

* Prometheus version:

I'm trying to build the latest upstream version, 2.32.1.

I'm happy to provide more logs or info if needed.

**Comment by sergiodj** [comment]
I think this is related to https://github.com/golang/go/issues/43047.

It seems to me that you have two ways forward here: either adjust the test and accept either negative or positive results, or get rid of the test given that it is relying on undefined behaviour.

Thanks.

**Comment by sergiodj** [comment]
Thanks for the reply, @LeviHarrison.  Yeah, your suggestion makes sense to me.  I'd be OK with having these specific tests split into an amd64-specific file.

**Comment by LeviHarrison** [comment]
Although actually, I wonder if the output itself is unexpected and should be fixed. It seems that the conversions were introduced in #9680.

**Comment by LeviHarrison** [comment]
If anything, it looks to me that the amd64 output could be wrong (converting a massive positive number of seconds into a negative duration), not the other architectures, so I opened #10196 to fix this.
