### ISSUE TITLE
Proposal: report sample and series statistics to help analyze and monitor query complexity

### ISSUE THREAD

**Issue by aughr** [prometheus/prometheus#10181]
Hey Prometheus community, @alanprot and I work on Amazon Managed Service for Prometheus. We're trying to improve our own and customer visibility into how expensive queries are to execute.

Prometheus already returns timing statistics about the query execution when the `stats=true` parameter is provided. When running many queries in parallel, especially in a multi-tenant environment on Cortex or Thanos, that timing can vary a lot for the same query. We're interested in metrics that should be the same across query runs for the same underlying data.

## Proposal

Record and add two new fields to the statistics response to help understand the query complexity and the amount of work done by the Prometheus engine to run a query.

* **Series Processed:** the number of series processed by the engine
* **Samples Processed:** the number of samples processed by the engine

These new fields are stable - not affected by any external factor other than the query and samples ingested - and can be used to better explain the cost of distinct queries.

We'd also like to understand these stats over time in a range query, so we propose adding a new `stats=detailed` option that returns stats by step. This is especially helpful in a context like Cortex where a subset of steps of a cached query can contribute to a query result.

What are your thoughts?

## Examples

Let's assume SerieA and SerieB has 5 labels and one sample per minute:

    * q=SerieA
        * InstantQuery: SeriesProcessed 5, SamplesProcessed=5
        * Range Query with 10 steps: SeriesProcessed 50, SamplesProcessed=50
    * q=max_over_time(SerieA[10m])
        * SeriesProcessed 5, SamplesProcessed=50
        * Range Query with 10 steps: SeriesProcessed 50, SamplesProcessed=500
    * q=sum by (label) (max_over_time(SerieA}[10m]))
        * SeriesProcessed 5, SamplesProcessed=50
        * Range Query with 10 steps: SeriesProcessed 50, SamplesProcessed=500
    * q=max_over_time(SerieA{label="unique"}[10m])
        * SeriesProcessed 1, SamplesProcessed=10
        * Range Query with 10 steps: SeriesProcessed 10, SamplesProcessed=100
    * q=sum(max_over_time(SerieA[10m])) + sum(max_over_time(SerieA[10m]))
        * SeriesProcessed 10, SamplesProcessed=100
        * Range Query with 10 steps: SeriesProcessed 100, SamplesProcessed=1000

### range queries

For range queries with `stats=detailed` with the following underlying data:

MetricA
* Number of Series: 1 at 1642118820 and 4 after that
* 2 samples per minute (scrape_interval=30s)

Output:
```
q=sum(serieA)&start=1642119240&end=1642119360&step=60

{
  "status": "success",
  "data": {
    "resultType": "matrix",
    "result": [
      {
        "metric": {},
        "values": [
          [
            1642118820,
            "6"
          ],
          [
            1642118880,
            "7"
          ],
          [
            1642118940,
            "6"
          ]
        ]
      }
    ],
    "stats": {
      "timings": {
        "evalTotalTime": 0.00502032,
        "resultSortTime": 7.56e-7,
        "queryPreparationTime": 0.000021759,
        "innerEvalTime": 0.004988867,
        "execQueueTime": 0.000044814,
        "execTotalTime": 0.005070935
      },
      "query": {
        "steps": {
          "1642118820": {
            "samples": 2,
            "series": 1
          },
          "1642118880": {
            "samples": 8,
            "series": 4
          },
          "1642118940": {
            "samples": 8,
            "series": 4
          }
        },
        "total": {
          "samples": 18,
          "series": 9
        }
      }
    }
  }
}
```

Note that there's a bit of subtlety to work out in the total semantics if we move forward here: should series be the number of unique series or the total for each bucket?

**Comment by aughr** [comment]
It looks like there are some past efforts in this space as well:

https://github.com/prometheus/prometheus/issues/6668
https://github.com/prometheus/prometheus/pull/6890

**Comment by bboreham** [comment]
I'm always a fan of having more data. The step-level stats look a bit too much on the face of it, but as you say it would be optional.

Related: working with a different back-end as I do (Cortex), I also want to bring stats out which would not be known to Prometheus - e.g. how much data came from Cortex' cache.  So I would like the mechanism to be extensible and not tied to one struct as it is today.

**Comment by aughr** [comment]
@bboreham Yeah, agreed, extensibility seems important here. I'm planning on writing up a Cortex-side issue for this work as well (since of course we use Cortex too) and will have further thoughts there.

**Comment by alanprot** [comment]
Hi, 

I just pushed a draft PR with the samples processed changes.

**Comment by GiedriusS** [comment]
cc @moadz as you were working on a similar thing in Thanos

**Comment by moadz** [comment]
Hey @aughr, I've written a proposal for introducing a partitioned histogram metric that represents this exactly:
https://github.com/thanos-io/thanos/pull/4932 
https://github.com/thanos-io/thanos/issues/4895

Where my proposal differs is the need to record these stats as a metric for the purpose of measuring and enforcing response time SLO's on the `/query_range` and `/query` endpoints.  One key thing is accounting for the Proxy Store API's fan out of series selects across targets. Thanos will dedup timeseries post-select before promql eval, so it's important these stats reflect the true reach of a query.

**Comment by aughr** [comment]
Interesting, thank you for pointing me to that, @moadz! Beyond the per-query / metric distinction, I think our goals for sample stats differ, but they can both co-exist. For our own operations at AWS, we might be interested in the true reach sample count. For our customers, though, we want to provide a consistent sample count for a given query whether an ingester in Cortex is down, compaction has happened, etc. That's the focus of this proposal.

That said, do you think it would be valuable for your use case to have both kinds of sample stats (true reach and de-duped) be in query stats if this proposal were to move forward? Would that make recording the metrics you want easier?

**Comment by codesome** [comment]
Without any opinion on the json payload format, having this stat makes sense.

Although, I am not sure about the `Range Query with 10 steps: SeriesProcessed 50, SamplesProcessed=50` in the issue description. Intuitively feels like `SeriesProcessed` should be number of unique series touched overall during the range query. And not a sum of series touched across steps. Because the range query is internally optimised to only fetch the series once per range query. So here I would expect `SeriesProcessed` to be 5 if there were 5 distinct series.

cc @roidelapluie

**Comment by moadz** [comment]
@aughr 
> That said, do you think it would be valuable for your use case to have both kinds of sample stats (true reach and de-duped) be in query stats if this proposal were to move forward? Would that make recording the metrics you want easier?
Not quite as these would be changes to the Query API, not the Store API (Cortex & Thanos make use of direct selects on the TSDB as opposed to via the query path) 

That being said, I do want to look into exposing these query stats via the Thanos query API as well. So any standard set here should be followed upstream in Cortex/Thanos. 

I would also like to hear more about how you intend to use these additional stats. Will they be parsed/persisted for analysis? Or is it simply for additional transparency to the user wrt query performance?

**Comment by bboreham** [comment]
What is left to do after #10369 ?

**Comment by alanprot** [comment]
We still don't have the series processed, but also i don't see demand for it.

So i think we can or close or if we think Series Processed is a good info to add in the stats we can try to add it as well.
