### ISSUE TITLE
Backfilling recording rules via API

### ISSUE THREAD

**Issue by metalmatze** [prometheus/prometheus#10202]
## Use case. Why is this important?

For the Service Level Objective project [Pyrra](https://github.com/pyrra-dev/pyrra) we are adding [support for availability recording rules](https://github.com/pyrra-dev/pyrra/pull/56) that pre-aggregate the number of failed and total requests over the objective's window (often like 4w).

Now, if the Prometheus server is running for more than 4w and there's plenty of data available for the objective the displayed graph will only have the recording rule's data since it was created. This leaves users with a seemingly broken graph. 

![errorbudget](https://user-images.githubusercontent.com/872251/150957667-d11c80fe-fe8a-4cc2-81d7-7bbfcd247327.png)

_Note: This Prometheus has all the data available, it's just that the recording rule was created less than 2 days ago._ 

This experiences gets worse if users were to chance the objective's window from 4w to something else like 2w, since the underlying recording rules changes from `increase(http_requests_total[4w])` to `increase(http_requests_total[2w])` and it's name from `http_requests:increase4w` to `http_requests:increase2w`.

## Proposal

Rather than creating some extra tooling as part of Pyrra to call the existing `promtool tsdb create-blocks-from rules` I want to propose adding a API to Prometheus itself to create these back filling blocks. 
In my particular use case the back filling doesn't need to be instantly either and is fine to take a couple of minutes (depending on the amount of data). 

As for the API I can imagine a RESTful admin API call containing such payload:
```
> GET /api/v1/admin/tsdb/blocks/rules HTTP/1.1
> Host: localhost:9090
> User-Agent: curl/7.81.0
> Accept: */*
> {"start": 1643106335, "rules": ["http_requests:increase4w"]}
```
The response wouldn't be blocking until the blocks are created but could return `201 CREATED` and thus signal that the request was successfully queued.
Obviously the actual implementation is up for discussion and I don't have a strong opinion.

cc @JessicaGreben @GayathriVenkatesh @roidelapluie

**Comment by sobelek** [comment]
Hey 👋 
Are there any ongoing plans of implementing this backfill API?

**Comment by bboreham** [comment]
Hello from the bug-scrub! Nobody has stepped up to implement this in two years, so we will close the issue.
It still seems like a valid idea; we can re-open if someone has concrete plans to deliver it.
