### ISSUE TITLE
Azure SD: Add a Prometheus User Agent on HTTP requests

### ISSUE THREAD

**Issue by jrauschenbusch** [prometheus/prometheus#10201]
It would be really good to be able to distinguish HTTP calls made from Prometheus server to the Azure ARM API.

Reason: ARM API requests are rate-limited and it's nearly impossible to distinguish calls made from Prometheus or from other components (except the version of azure-sdk-for-go present in the user agent header).

Current userAgent:
```
Go/go1.15.6 (amd64-linux) go-autorest/v14.2.1 Azure-SDK-For-Go/v49.2.0 compute/2018-10-01
```

Suggested userAgent:
```
Go/go1.15.6 (amd64-linux) go-autorest/v14.2.1 prometheus-server/v2.24.1
```

**Comment by roidelapluie** [comment]
Thanks for your request. Are you able to try out #10209 ?

**Comment by jrauschenbusch** [comment]
Hi @roidelapluie,

thanks for your efforts. I'll try to test.

**Comment by jrauschenbusch** [comment]
@roidelapluie LGTM

User Agent is recorded as `Prometheus/2.33.0-rc.1` by using your branch
