### ISSUE TITLE
No datapoints found.

### ISSUE THREAD

**Issue by nickvth** [prometheus/prometheus#1022]
When using the getting started guide i get no data or No datapoints found when using the expression browser.

using version: 0.15.1 / 2015-07-27
![screen shot 2015-08-22 at 11 14 56](https://cloud.githubusercontent.com/assets/7606465/9423312/17f74f30-48bf-11e5-8a55-54c5a23c305b.png)
![screen shot 2015-08-22 at 11 14 36](https://cloud.githubusercontent.com/assets/7606465/9423313/1814a4f4-48bf-11e5-9326-d0b6bd91a718.png)

**Comment by fabxc** [comment]
Thanks for reporting, likely broken in master.
Please checkout tag 0.15.1 and go from there, master is our development branch and thus not a good starting point.

**Comment by nickvth** [comment]
it's not broken :-), maybe you can at to the documentation that ntp service must be configured or your system has the correct date and time. After fixing date and time on my virtual machine it works. I will close this issue.

**Comment by matthiasr** [comment]
Still an interesting point though. Maybe the web interface should say something if the host and browser clocks are too far apart?

**Comment by yanhongwang** [comment]
Hello Nickvth,

I also meet the same issue (**No datapoints found.**). And I found that seem also the ntp problem.
Is that the same to you? Could I ask how you fix it?

ntpd[1220]: error resolving pool ntp.ubuntu.com: Temporary failure in name resolution (-3)
ntpd[1220]: error resolving pool 1.ubuntu.pool.ntp.org: Temporary failure in name resolution (-3)
ntpd[1220]: error resolving pool 2.ubuntu.pool.ntp.org: Temporary failure in name resolution (-3)
ntpd[1220]: error resolving pool 3.ubuntu.pool.ntp.org: Temporary failure in name resolution (-3)

Thanks very much.

Hong

**Comment by nickvth** [comment]
@yanhongwang  it looks like you have also a dns issue with resolving ntp.ubuntu.com or ntp.ubuntu.com host or ntp service is not available anymore, but i think it's still available.  

1. First check your dns settings
can you ping google.com or ntp.ubuntu.com etc.. 
2 .You can configure your ntp daemon and here are some good tutorials you can use for ubuntu:
- https://www.digitalocean.com/community/tutorials/how-to-set-up-timezone-and-ntp-synchronization-on-ubuntu-14-04-quickstart
- https://www.digitalocean.com/community/tutorials/how-to-set-up-time-synchronization-on-ubuntu-16-04
- https://www.digitalocean.com/community/tutorials/how-to-configure-ntp-for-use-in-the-ntp-pool-project-on-ubuntu-16-04 

Good Luck!

Regards,

Nick

**Comment by yanhongwang** [comment]
Hi @nickvth 

Thanks for your hint and reply.
I think that probably is proxy issue because I can't neither ping ntp.ubuntu.com nor google in my network environment. I need to figure out that first.

Thanks anymore.

Hong
