### ISSUE TITLE
Move remote_storage_adapter example out of repo

### ISSUE THREAD

**Issue by brancz** [prometheus/prometheus#10221]
## Proposal
**Use case. Why is this important?**

Move remote_storage_adapter example out of repo into a separate repo. This has on several occasions made importing Prometheus unnecessarily difficult because this example imports enormous dependencies such as influxdb. There's really no good reason for this to be in the Prometheus repository, it can be in another repository and be linked to from the same places.

## Alternatives considered

Because of how go mods work, unfortunately, we can't just have another `go.mod` within that directory, which I would have preferred for simplicity.

**Comment by roidelapluie** [comment]
> Because of how go mods work, unfortunately, we can't just have another go.mod within that directory, which I would have preferred for simplicity.

I am surprised by this claim. What's blocking this? We already have repos with multiple go.mods, like common.

**Comment by brancz** [comment]
I should have elaborated. Generally, it can work to have nested modules, but with this exact situation, it cannot. The problem is that in this case, the nested module tries to access the "upper" one. The error is:

```
○ go mod tidy
github.com/prometheus/prometheus/documentation/examples/remote_storage/remote_storage_adapter: ambiguous import: found package github.com/prometheus/prometheus/documentation/examples/remote_storage/remote_storage_adapter in multiple modules:
        github.com/prometheus/prometheus v1.8.2-0.20211119115433-692a54649ed7 (/home/brancz/pkg/mod/github.com/prometheus/prometheus@v1.8.2-0.20211119115433-692a54649ed7/documentation/examples/remote_storage/remote_storage_adapter)
        github.com/prometheus/prometheus/documentation/examples/remote_storage/remote_storage_adapter (/home/brancz/src/github.com/prometheus/prometheus/documentation/examples/remote_storage/remote_storage_adapter)
github.com/prometheus/prometheus/documentation/examples/remote_storage/remote_storage_adapter/graphite: ambiguous import: found package github.com/prometheus/prometheus/documentation/examples/remote_storage/remote_storage_adapter/graphite in multiple modules:
        github.com/prometheus/prometheus v1.8.2-0.20211119115433-692a54649ed7 (/home/brancz/pkg/mod/github.com/prometheus/prometheus@v1.8.2-0.20211119115433-692a54649ed7/documentation/examples/remote_storage/remote_storage_adapter/graphite)
        github.com/prometheus/prometheus/documentation/examples/remote_storage/remote_storage_adapter (/home/brancz/src/github.com/prometheus/prometheus/documentation/examples/remote_storage/remote_storage_adapter/graphite)
github.com/prometheus/prometheus/documentation/examples/remote_storage/remote_storage_adapter/influxdb: ambiguous import: found package github.com/prometheus/prometheus/documentation/examples/remote_storage/remote_storage_adapter/influxdb in multiple modules:
        github.com/prometheus/prometheus v1.8.2-0.20211119115433-692a54649ed7 (/home/brancz/pkg/mod/github.com/prometheus/prometheus@v1.8.2-0.20211119115433-692a54649ed7/documentation/examples/remote_storage/remote_storage_adapter/influxdb)
        github.com/prometheus/prometheus/documentation/examples/remote_storage/remote_storage_adapter (/home/brancz/src/github.com/prometheus/prometheus/documentation/examples/remote_storage/remote_storage_adapter/influxdb)
github.com/prometheus/prometheus/documentation/examples/remote_storage/remote_storage_adapter/opentsdb: ambiguous import: found package github.com/prometheus/prometheus/documentation/examples/remote_storage/remote_storage_adapter/opentsdb in multiple modules:
        github.com/prometheus/prometheus v1.8.2-0.20211119115433-692a54649ed7 (/home/brancz/pkg/mod/github.com/prometheus/prometheus@v1.8.2-0.20211119115433-692a54649ed7/documentation/examples/remote_storage/remote_storage_adapter/opentsdb)
        github.com/prometheus/prometheus/documentation/examples/remote_storage/remote_storage_adapter (/home/brancz/src/github.com/prometheus/prometheus/documentation/examples/remote_storage/remote_storage_adapter/opentsdb)
```

**Comment by roidelapluie** [comment]
We could keep it in this repo if we rename or move the packages at the same time we add the go.mod

**Comment by brancz** [comment]
It depends on two main sub-packages from prometheus/prometheus, the first one, `prompb` wouldn't be a problem, as it's quite self contained, but the second one `storage/remote` transitively depends on practically everything in the Prometheus repository, I don't believe this is possible without drastically changing the layout and refactoring a lot of the repository.

**Comment by roidelapluie** [comment]
> It depends on two main sub-packages from prometheus/prometheus, the first one, `prompb` wouldn't be a problem, as it's quite self contained, but the second one `storage/remote` transitively depends on practically everything in the Prometheus repository, I don't believe this is possible without drastically changing the layout and refactoring a lot of the repository.

https://github.com/prometheus/prometheus/commit/bb4fd13d3da6be9570424308fc91e05d7af81ae9

**Comment by brancz** [comment]
Wow nice!!! I apologize, I think I straight out do not understand go mods. Do you want to create a PR? :)

**Comment by roidelapluie** [comment]
Yes, but it will involved a few extra work to see what to do with CI etc.

**Comment by brancz** [comment]
I feel a bit out of my depth since everything I've done here so far was entirely wrong, if you tell what I can do to help, then I'm happy to do that, but if it's faster for you to just do, then I totally understand and will just stand on the sidelines cheering for you :D
