### ISSUE TITLE
Native Service Discovery for Oracle Cloud Infrastructure

### ISSUE THREAD

**Issue by mayurOciSA** [prometheus/prometheus#10226]
Hello Prometheus Community,
I am with OCI(Oracle Cloud Infrastructure). 

Use Case: I am reaching out to you on behalf of joint OCI and Prometheus customers. These joint customers are asking for support for native Service Discovery(SD) in Prometheus for their OCI resources(similar to the ones listed [here](https://github.com/prometheus/prometheus/tree/main/discovery)). Since Prometheus is widely used as a one-stop-shop for monitoring resources across different environments(cloud providers and on-prem), native SD for OCI will really be useful for many OCI and Prometheus joint users.

My team is planning to develop this new SD for OCI, following all the guidelines and processes set by the community. We will maintain it on an ongoing basis as well. I think we meet the criteria for new native SD, as laid down in the documentation [here](https://github.com/prometheus/prometheus/tree/main/discovery). 

Before my team embarks on building SD for OCI,  I wanted to know if Prometheus Community is open to accepting new SD for OCI, given the information above.

**Comment by roidelapluie** [comment]
Can we get more details about OCI, mainly:
- Which services would be implemented?
- Is there any rate limits that users might hit?

**Comment by mayurOciSA** [comment]
Hi @roidelapluie 

1. We are starting with Compute Service...discovering compute nodes on OCI. These nodes will have Prometheus NodeExporter running on them. Other services might come in the future.

2. we have a rate limit of 1 TPS/api/Region/CustomerAccount for most of the OCI SDK APIs which are for fetching metadata info(for nodes, vcn etc). In order to avoid hitting limits, we can leverage retries and exponential backoff built into OCI SDK.

Thanks
Mayur

**Comment by roidelapluie** [comment]
Even if vendors commit to support for their SD, it's critical as Prometheus maintainer to have access to the infrastructure. Would it be possible to get a test account to validate and maintain the SD over the long term? We have a few SD's where I use personal account to develop/maintain and I like to avoid it for new SD's.

Also  the fact that the second message already speaks about hitting limits seems to be a red flag to me. Do you have an idea of the number of api call's needed/allowed for this SD to work?

**Comment by mayurOciSA** [comment]
Hi @roidelapluie 
Definitely. What are your requirements for the test account in terms of what services/service limits are required?

I would love to understand more about the red flag you mentioned. For context, each discovery job starts at a region and a compartment in a tenancy. Each of the calls has its own rate limits per region. We will have recommendations in service discovery documentation to mitigate issues around throttling, for example, recommended values for refresh interval and right defaults, etc.
I will get back to you with API calls calculations, to make crystal the number of calls to different APIs we will make in SD.

**Comment by mayurOciSA** [comment]
@roidelapluie gentle reminder

**Comment by roidelapluie** [comment]
Yes, I would like to know how many targets you aim at supporting with default values, without throttling.

**Comment by roidelapluie** [comment]
Friendly ping.

**Comment by mayurOciSA** [comment]
@roidelapluie I plan to support ~300 targets in 1 sd job, without throttling and with a default refresh_interval of 5minutes. 
I will be done with coding the functionality in 1 or 2 days and will perform testing and see how it performs. Will soon get back to you with results in 2/3 days.  Does this help?
Also, can you please share your requirements for the test account on OCI in terms of what services/service limits are required?

**Comment by roidelapluie** [comment]
We need to be able to power small vms', to test the SD. This is only debugging and ad-hoc, when we have users requests.

**Comment by mayurOciSA** [comment]
Hi @roidelapluie 
I have got pulled into some other work but will get back to OCI-SD development and testing in a week.

For the OCI Cloud account for testing, I think Oracle Cloud "Always Free" tier might do the job. Here are the relevant links for the specifics.
https://docs.oracle.com/en-us/iaas/Content/FreeTier/freetier_topic-Always_Free_Resources.htm#freetier_topic_Always_Free_Resources_Infrastructure

https://www.oracle.com/cloud/free/#always-free

![image](https://user-images.githubusercontent.com/93163855/159537488-68e2a8f4-b3df-4811-8254-51593771d043.png)

**Comment by roidelapluie** [comment]
Okay. One last think would be to see how much bigger the prometheus binary gets with that extra SD.

**Comment by mayurOciSA** [comment]
for Prometheus binary: it is 116.5 MB after building locally with new OCI SD on mac vs 104.7MB I downloaded from https://prometheus.io/download/

**Comment by mayurOciSA** [comment]
Hi @roidelapluie 
I am code complete and have done testing with 1000 targets on OCI across 3 jobs. The results look good. I will create PR after completing some internal processes.

**Comment by mayurOciSA** [comment]
Hi @roidelapluie 

While working through some internal processes, a question came up with regards to the copyright notice format. Our standard when contributing code to a third-party open-source project is to just include "Copyright 2022 Oracle and/or its affiliates” (with the applicable year(s)) in the file headers.
However, since we’d be contributing Oracle code under the Apache 2.0 license, it may make more sense and be easier for you in the long run for Oracle to include in the file headers of Oracle code the notice. 
This is as per the recommendation of Apache under the How To Apply The Apache License To Your Work section at https://www.apache.org/licenses/LICENSE-2.0 ("Copyright 2022 Oracle and/or its affiliates. Licensed under the Apache License, Version 2.0 . . .").
Do you have a preference as to which form of the header we include in the Oracle-authored files? Do you also want us to include a NOTICE.txt file for the Oracle folder (in keeping with Apache 2.0 application guidance)? Since the same license (Apache 2.0) that applies to the Prometheus project would also apply to Oracle’s contribution, a LICENSE.txt file in the Oracle folder is not necessary, but, if you would prefer a more built-out folder, we can accommodate. Please advise.

**Comment by caniszczyk** [comment]
re: copyright headers, we prefer what is here:
https://github.com/cncf/foundation/blob/main/copyright-notices.md#copyright-notices

re: NOTICE.txt, it's fine to include

We also prefer a LICENSE file at the root of the project

**Comment by roidelapluie** [comment]
In other cases i had added original copyright to files, like here:
https://github.com/prometheus/exporter-toolkit/blob/9f7b277231e81a5529f560c0389d764cc0ac7de3/web/handler.go#L1-L3

Maybe a double-copyright attribution on the files would be the simplest option here?

**Comment by munger1985** [comment]
dear guys, i have written oci_exporter which is capable of exporting all metrics to prometheus, i am trying to contribute to exporters  https://github.com/munger1985/OCI-Auto-Scripts/tree/main/oci_exporter

**Comment by bboreham** [comment]
Hello from the bug-scrub! The linked PR was closed in the bug-scrub in January; we will close this issue.
We would prefer that integration of new service discovery go via [HTTP](https://prometheus.io/docs/prometheus/latest/http_sd/) which avoids the need to modify Prometheus.
