### ISSUE TITLE
Proposal: Clean up leftover checkpoint tmp directories during startup

### ISSUE THREAD

**Issue by tpaschalis** [prometheus/prometheus#10245]
## Proposal
Hey team! 👋  I'm here to ask whether you think it's a good idea to make Prometheus clean up leftover checkpoint.*.tmp directories during startup.

We're currently [defering their cleanup](https://github.com/prometheus/prometheus/blob/cda025b5b50328ccd129c141e09dd77b3b1b034e/tsdb/wal/checkpoint.go#L140-L144) in cases where Checkpoint() may exit early due to an error, but this block won't get called if Prometheus OOMs while reading a segment.

While looking at the way we handle block tmp dirs, it has already been suggested in a comment by @bwplotka.
https://github.com/prometheus/prometheus/blob/0df3489275ed4357b12d98e737290992e19915ce/tsdb/db.go#L54-L58

**Use case. Why is this important?**
This would be useful in preventing users' disk usage from blowing up and also enable us to be a good citizen in a shared system by cleaning up useless leftover data.

**Comment by codesome** [comment]
Yes. Cleaning them up on startup makes sense, there wont be any problems.
