### ISSUE TITLE
Proposal: Add resource groups filter to azure service discovery

### ISSUE THREAD

**Issue by jrauschenbusch** [prometheus/prometheus#10253]
## Proposal

Since ARM API requests are rate-limited in Azure, it would be good to be able to reduce the load posed by Prometheus Azure Service Discovery. Especially when running multiple AKS clusters on a single subscription, running Prometheus servers on each, this problem is multiplied. So an additional reduction by resource group would be really good.

Use case: Non-AKS related VMSS residing in a specific resource group which should be discovered by a single prometheus server instance.

Filter could reduce the amount of getScaleSetVMs calls by filtering by resource group:
https://github.com/prometheus/prometheus/blob/5851557a288eb695c7fa450be3c8884ae446bee3/discovery/azure/azure.go#L302-L308

Filter could reduce the amount of getNetworkInterfaceByID by reducing the machines set:
https://github.com/prometheus/prometheus/blob/5851557a288eb695c7fa450be3c8884ae446bee3/discovery/azure/azure.go#L320
https://github.com/prometheus/prometheus/blob/5851557a288eb695c7fa450be3c8884ae446bee3/discovery/azure/azure.go#L351

**Comment by roidelapluie** [comment]
Thanks for your input. Yes, this would be a great feature.

**Comment by David-N-Perkins** [comment]
I'm looking at implementing this, but not sure how to get the current resource group a Prometheus instance is in. Would this be an additional config value, or is there a way to look it up?

**Comment by David-N-Perkins** [comment]
@jrauschenbusch I implemented this feature, but don't have access to Azure resources to test my [changes](https://github.com/prometheus/prometheus/pull/10365). Are you able to test this or know someone who can?

**Comment by jrauschenbusch** [comment]
Will close this ticket as it's now implemented and merged.
