### ISSUE TITLE
/prometheus/chunks_head filling up entire disk

### ISSUE THREAD

**Issue by AndrewNiven1** [prometheus/prometheus#10256]
**What did you do?**

Ran Prometheus v2.32.0 on an Azure Kubernetes cluster, Kubernetes version 1.21.2. Limits of 500m CPU and 3Gi memory were set. A 50GiB persistent volume claim was allocated to Prometheus.

A scale test was run in which the number of metrics scraped by the Prometheus approached 500k.

**What did you expect to see?**

The Prometheus would either:
- handle all metrics as normal
- get killed by Kubernetes due to exceeding its memory allocation. It would attempt to recover. When the scale test ended, and the number of metrics decreased, it would return to normal behaviour. 

**What did you see instead? Under which circumstances?**

Prometheus crashed permanently, and was unable to restart, because it could not write metrics to /prometheus/wal due to the disk being full. We investigated and saw that the size of the directory /prometheus/chunks_head was around 48GiB - almost the entire size of the persistent volume claim allocated to Prometheus. 

When we deleted some of the files in /prometheus/chunks_head, Prometheus was able to restart. It then cleared out the entire /prometheus/chunks_head directory, as it would be expected to do, and continued to work normally.

It appears that the standard behaviour (creating blocks out of chunks and then deleting the chunks from chunks_head) got interrupted in some way, and was not able to recover without manual intervention.

**Environment**

* System information:

	Kubernetes v1.21.2

* Prometheus version:

	v2.32.0

* Prometheus configuration file:

Prometheus container spec in Kubernetes:

    Port:          9090/TCP
    Host Port:     0/TCP
    Args:
      --web.console.templates=/etc/prometheus/consoles
      --web.console.libraries=/etc/prometheus/console_libraries
      --config.file=/etc/prometheus/config_out/prometheus.env.yaml
      --storage.tsdb.path=/prometheus
      --storage.tsdb.retention.time=1d
      --web.enable-lifecycle
      --web.external-url=http://simon-metrics-kube-prometh-prometheus.simon:9090
      --web.route-prefix=/
      --log.level=debug
      --web.config.file=/etc/prometheus/web_config/web-config.yaml
      --storage.tsdb.max-block-duration=2h
      --storage.tsdb.min-block-duration=2h
    State:          Running
      Started:      Wed, 02 Feb 2022 17:36:16 +0000
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     500m
      memory:  3Gi
    Requests:
      cpu:        500m
      memory:     3Gi
    Readiness:    http-get http://:http-web/-/ready delay=0s timeout=3s period=5s #success=1 #failure=120
    Environment:  <none>
    Mounts:
      /etc/prometheus/certs from tls-assets (ro)
      /etc/prometheus/config_out from config-out (ro)
      /etc/prometheus/rules/prometheus-simon-metrics-kube-prometh-prometheus-rulefiles-0 from prometheus-simon-metrics-kube-prometh-prometheus-rulefiles-0 (rw)
      /etc/prometheus/web_config/web-config.yaml from web-config (ro,path="web-config.yaml")
      /prometheus from prometheus-simon-metrics-kube-prometh-prometheus-db (rw,path="prometheus-db")
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-wmphv (ro)

* Logs:

We have not been able to recover logs from the time of the issue.

**Comment by AndrewNiven1** [comment]
Hi Ganesh, thanks for your response. 

I'm not sure I agree that the issue here was an under-provisioned disk. In normal operation, the size of the /prometheus/chunks_head directory is on the order of 100-200MiB. In the case that we observed, the size of /prometheus/chunks_head had grown to 48GiB. This is clearly abnormal and indicates that something had gone wrong (i.e. the routine responsible for tidying the chunks_head directory was not called for some reason). Hitting the disk size limit was the most obvious symptom of the problem, but not the root cause - increasing the disk size would merely have delayed the problem, not prevented it.

In any case I've not been able to reproduce the problem, so I'm happy for this issue to stay closed until it's observed again.

Thanks,

Andrew

**Comment by codesome** [comment]
If compaction fails because of not enough disk space, then chunks_head is not going to be cleared up, because that is a data loss. Hence chunks_head would keep on taking more space until disk is full. This is just a speculation. It is however weird that big % was chunks_head and not the WAL, so there _might_ be some actual issue.

It would have been interesting to know more details around it. But since nothing is actionable because of lack of data, we can keep this issue closed. In case you are running the scale test again, please keep the logs and the data directory :)

**Comment by disambiguationuk** [comment]
We have retention_time set to six hours but our oldest blocks end up being much older than this during this behaviour, they never get cleaned up.

**Comment by mgerdts** [comment]
I've seen this also, accompanied by log entries that match #10043.

**Comment by xvzf** [comment]
@codesome we just had this happening with 80Gi of disk available and a 2hr retention (as we're writing to a remote cluster). We have ~400k time series on this prometheus instance and the HA-pair is using ~3Gi disk size. Despite this, the disk was running full with the log entries that match #10043 as @mgerdts also observed.

Do you think this is a duplicate of #10043 ? Otherwise I'd suggest to open the issue again

**Comment by codesome** [comment]
@xvzf can you please share the size of all directories inside the tsdb data directory? And does the disk fill up during the replay or after the replay?

**Comment by xvzf** [comment]
@codesome I cannot anymore unfortunately, we destroyed the PVC as we wanted to get our HA-pair up again. In case it happens again I'll gather more insights

Based on our monitoring, the disk filled up after the replay, there have been no restarts, prometheus was running healthy and the disk size just kept growing and growing
