### ISSUE TITLE
Missing docs for `__meta_kubernetes_endpoints_label*` labels

### ISSUE THREAD

**Issue by valyala** [prometheus/prometheus#10284]
The commit https://github.com/prometheus/prometheus/commit/617c56f55a14b7f6ed4f0f4402c1e18aaf3b396c adds new labels for `role: endpoints`: `__meta_kubernetes_endpoints_label_*` and `__meta_kubernetes_endpoints_labelpresent_*`. But these labels aren't documented at https://prometheus.io/docs/prometheus/latest/configuration/configuration/#kubernetes_sd_config . This may prevent from the usage of these labels.

Side notes:
1) Why these labels weren't added to `role: endpointslice`?
2) Why `__meta_kubernetes_endpoints_annotation*` labels weren't added to `role: endpoints` and `role: endpointslice` to be consistent with other `role`s in `kubernetes_sd_config`?

**Comment by juanrh** [comment]
@roidelapluie I see #10911 was merged and `__meta_kubernetes_endpoints_label_<labelname>` and `__meta_kubernetes_endpoints_labelpresent_<labelname>` are documented in https://prometheus.io/docs/prometheus/latest/configuration/configuration/#endpoints, so this issue should be ok to close, right? Or am I missing something?

**Comment by sonali-rajput** [comment]
any updates?

**Comment by simonpasquier** [comment]
The documentation looks up-to-date to me. Feel free to reopen if it's not the case.
