### ISSUE TITLE
Add more detailed metrics to http_sd_config

### ISSUE THREAD

**Issue by mst-ableton** [prometheus/prometheus#10309]
## Proposal

It would be nice to get metrics from within Prometheus as to whether an `http_sd_config` refresh succeeded or failed.  It would also be nice to have the timestamp of the last time an `http_sd_config` succeeded. Right now, the only metric I can find is `prometheus_sd_refresh_failures` which only notifies of global service discovery failures. Examples of other service discovery metrics are:

* [`prometheus_sd_dns_lookups_total`](https://github.com/prometheus/prometheus/blob/9a2e93228e63a3fbac950ef0a639f754c3598c5d/discovery/dns/dns.go#L52) / [`prometheus_sd_dns_lookup_failures_total`](https://github.com/prometheus/prometheus/blob/9a2e93228e63a3fbac950ef0a639f754c3598c5d/discovery/dns/dns.go#L58)
* [`prometheus_sd_file_mtime_seconds`](https://github.com/prometheus/prometheus/blob/9a2e93228e63a3fbac950ef0a639f754c3598c5d/discovery/file/file.go#L161) / [`prometheus_sd_file_read_errors_total`](https://github.com/prometheus/prometheus/blob/9a2e93228e63a3fbac950ef0a639f754c3598c5d/discovery/file/file.go#L50)

**Use case. Why is this important?**

If service discovery is not operating, it's possible that critical hosts are not being monitored. Therefore it's important to monitor each SD refresh and alert if a failure happened -- this requires metrics to alert on. The best available metric I can find, `prometheus_sd_refresh_failures`, does not break down by SD provider or config name, making it difficult to diagnose what is going on. 

It's possible that this information is available in a different metric that I wasn't able to find -- maybe some kind of HTTP scraping metric? If so, then feel free to close this issue! Regardless, it might be helpful to update https://prometheus.io/docs/prometheus/latest/http_sd/ with a list of metrics applicable to `http_sd`.

Thanks for taking the time to read this, and thanks for making such an awesome monitoring platform!

**Comment by roidelapluie** [comment]
This makes sense. I am not sure that last successful timestamp is userful. it is useful with file_sd as the value will generally not change. But we could definitively have a failures counter.

**Comment by David-N-Perkins** [comment]
@mst-ableton I put up a PR that adds the `prometheus_sd_http_failures_total` counter metric, with a `url` label set to the value in the config. Let me know if you want anything additional.

**Comment by mst-ableton** [comment]
@David-N-Perkins that PR looks great, thanks for taking the time to work on it!

**Comment by David-N-Perkins** [comment]
@mst-ableton I need to remove the `url` label from the metric, because multiple `http_sd_config`'s with the same value would cause a panic. So there will be a single `prometheus_sd_http_failures_total` counter metric for all `http_sd_config`'s. I wanted to make sure that still works for you.

**Comment by David-N-Perkins** [comment]
The PR is merged. I think this can be closed now.

**Comment by roidelapluie** [comment]
Thanks!
