### ISSUE TITLE
Handle saves/deletes on /api/v1/rules

### ISSUE THREAD

**Issue by gillg** [prometheus/prometheus#10314]
### Is your proposal related to a problem?

Grafana since v8 introduced a very useful alerting UI for end users.
They rely in background on an internal alertmanager not able to receive alerts from outside, native Alertmanager APIs to manage a remote instance, and some Cortex metrics APIs to manage all alerting from 1 place.

**Using Grafana to evaluate alerting rules is a SPOF and late in alerting stack**, so you can also use this API natively https://cortexmetrics.io/docs/api/#set-rule-group
Is there any plans to implement this endpoint ?

### Describe the solution you'd like

The best would be to handle POST and DELETE verbs on the existing rules API `/api/v1/rules`.
We should be able to configure prometheus config file to check rules in a folder like `/etc/prometheus/remote-rules.d/*.yml`
At command-line args we could have `--rules.remote-management.store-path=/etc/prometheus/remote-rules.d/` then one yaml file is created by "namespace" (see cortexmetrics API doc)

### Describe alternatives you've considered

The only homemade alternative is a reverse proxy with handles POST / DELETEs on `/api/v1/rules` and a tool in charge to create files in a `/etc/prometheus/remote-rules.d/*.yml` folder

This proposal partialy duplicates https://github.com/thanos-io/thanos/issues/5168 but both are usefull if you want to dispatch alerts at different levels.

**Comment by roidelapluie** [comment]
I'd like to avoid mangling files on disk. If we were to support something like this, it would be hard to remove it later.

I think it makes more sense to go directly to a database rather than letting the users access the local filesystem.

**Comment by DrAuYueng** [comment]
Sounds good.

**Comment by BlueBlue-Lee** [comment]
Is there any plan to support post/put/get/delete api for rules in Prometheus natively? Managing rule files is kind of hard and inconvenient.

**Comment by bboreham** [comment]
Hello from the bug-scrub! No update in over two years, so we will close this.
Julien's idea of a config database was discussed [at the dev summit](https://docs.google.com/document/d/11LC3wJcVk00l8w5P3oLQ-m3Y37iom6INAMEu2ZAGIIE/edit#bookmark=id.77pv82789akw).
Next step for that would be a design document in https://github.com/prometheus/proposals.
