### ISSUE TITLE
ECR Public Gallery

### ISSUE THREAD

**Issue by mike-stewart** [prometheus/prometheus#10343]
Would you consider also hosting your container image on ECR Public? This would be beneficial to AWS customers who are constrained by Dockerhub rate limiting.

**Comment by SuperQ** [comment]
For reference, this is about adding Prometheus to https://gallery.ecr.aws/

**Comment by SuperQ** [comment]
Another way we could handle this is to setup something like https://github.com/xelalexv/dregsy.

**Comment by matthiasr** [comment]
As a workaround, we also publish (most?) images to quay.io, which AFAIK does not have rate limits for pulling.

**Comment by mike-stewart** [comment]
This is an example of one of the projects that's only on dockerhub: https://github.com/prometheus/statsd_exporter

I can log an issue for that repo specifically if that makes more sense. I wasn't sure if this was a repo-specific policy or not.

**Comment by SuperQ** [comment]
@mike-stewart That project is on quay.io.

https://quay.io/repository/prometheus/statsd-exporter

**Comment by jacobwoffenden** [comment]
Publishing to ECR Public Gallery would also help for when Quay.io goes down like it did earlier today

**Comment by bboreham** [comment]
Hello from the bug-scrub! Prometheus is hosted on two repositories, and there was not much interest in adding more, so closing.
