### ISSUE TITLE
Is it possible that alert carry ActiveAt field?

### ISSUE THREAD

**Issue by YukkiKaze** [prometheus/prometheus#10342]
## Proposal
When prometheus send alert to alertmanager,  alertmanager will get `StartsAt` `EndsAt` fileld, 
https://github.com/prometheus/prometheus/blob/main/cmd/prometheus/main.go#L1238
when alert source host and target host time synchronized, there is nothing to worry about.
But if alert source host's time is falling behind target host for several hours, this alert will never be sent out by alertmanager, for alertmanager think it's an already ended alert.
If alert carry `ActiveAt` timestamp, which [keep updating with source time](https://github.com/prometheus/prometheus/blob/main/rules/alerting.go#L381), alertmanager can compare it with `EndsAt` field, and no need to warry about messing source time with target time.

**Comment by roidelapluie** [comment]
In general, out of sync clocks are hard to deal with. @simonpasquier what do you think about this issue?

**Comment by YukkiKaze** [comment]
In my opinion, if time differs in several hosts, alert manager can decide whether to trigger alert based on the origin side. in origin side, prometheus discard `ActiveAt` field which can help alert manager to decide if this alert should be triggered, now we only have `StartAt` and `EndsAt`  field, therefore cannot determine the alert state if clock out of sync @simonpasquier

**Comment by YukkiKaze** [comment]
Found a solution of time disorder,  add a timestamp field in alerting_rules annotation, like this: 
`timestamp: {{ with query "time()" }}{{ . | first | value | humanizeTimestamp }}{{ end }}`
alert receiver can judge alert state by compare this timestamp with alert's endtime, no need to use its local time.
@roidelapluie this issue can be closed, thanks for reply~
