### ISSUE TITLE
Expression evaluation time is proportional to chunk descs

### ISSUE THREAD

**Issue by brian-brazil** [prometheus/prometheus#1035]
I noticed that demo.robustperception.io is pegged for CPU. It's scraping a handful of targets and running the Conway's life demo.

If you run
```
go tool pprof http://demo.robustperception.io:9090/debug/pprof/profile
```
you'll see that the problem is in the analyze phase, in particular in `github.com/prometheus/prometheus/storage/local.(*memorySeries).newIterator` which copies all the chunkdescs for each series referenced. Evaluation time should be proportional to the amount of a time series that is accessed, not the total amount of data stored. Accordingly I think we need to rework this, as 9k timeseries being referenced a second is enough to eat an entire core.

**Comment by fabxc** [comment]
Could you provide the data rather than your conclusion of it so we don't all have replicate the whole process?

**Comment by juliusv** [comment]
The SVG graph would be nice :)

**Comment by brian-brazil** [comment]
The command to retrieve it is above, and it's monitoring itself too if you need anything else. It's running at head.

**Comment by beorn7** [comment]
OK, finally found time to look into this.

The code in question does not copy all the chunkDescs. It creates a slice of chunk pointers and let's them point to the chunks currently loaded. The series iterator then acts directly on chunks and not on chunkDescs at all.

I'm trying to remember why we did it that way. It kind of makes the pinning not needed...

I'll continue to think about it.

**Comment by beorn7** [comment]
OK, wrapped me head around the multiple layers of indirection here. It makes sense after all.

I see a number of possible optimizations, but I cannot really believe the copying of pointers to chunks would be a bottle neck. I'm looking at the profiling data right now, assuming it still runs with the same parameters.

**Comment by beorn7** [comment]
The issue is mostly the mutex that has to be acquired to get to the chunk reference. So while the problem is not copying chunkDesc, the fundamental cause is similar: Even for accessing a single sample, we go through all chunks. I think it will help a lot even in less special use-cases than the game-of-life setup to fix that. Working on it...
