### ISSUE TITLE
Support for elliptic curve cryptography

### ISSUE THREAD

**Issue by tumbl3w33d** [prometheus/prometheus#10378]
A while ago I [asked about](https://discuss.prometheus.io/t/tls-between-prometheus-and-node-exporters-with-ec-pki/433) whether anyone was able to let prometheus scrape node exporter TLS endpoints with ECC certificates. Unfortunately, there was no answer. Thus, my assumption still is, that prometheus lacks support for curve crypto.

## Proposal
I guess I don't need to explain the importance of modern cryptography and ECC is not even that new anymore. The underlying TLS lib in use by prometheus probably supports this with some adjustments. Prometheus is the only software in my infrastructure that forces me to use RSA yet for these endpoints.

I'd be glad to be told that I'm just holding it wrong.

**Comment by roidelapluie** [comment]
the following cert I have created works for me:

```
$ cat example.com.crt 
-----BEGIN CERTIFICATE-----
MIIBCDCBuwIUXY67fm5zNZIII3Uv0SZOZkURdwQwBQYDK2VwMCcxCzAJBgNVBAYT
AkRFMRgwFgYDVQQDDA93d3cuZXhhbXBsZS5jb20wHhcNMjIwMzAyMTYzMDAzWhcN
MjQwMTMxMTYzMDAzWjAnMQswCQYDVQQGEwJERTEYMBYGA1UEAwwPd3d3LmV4YW1w
bGUuY29tMCowBQYDK2VwAyEAYWl4d8WvzQledmpjH37I5Vtbuli5zJh7G9YByOBX
v7UwBQYDK2VwA0EA90RH/m+7gIwldcLx04zON472zhcNXbrgDuY1q6BjnFhEQCix
6TiXzfG/EEW2ZkzEhUWoVd0VHrdufJ6xVBpnDQ==
-----END CERTIFICATE-----
$ openssl x509 -in example.com.crt -text
Certificate:
    Data:
        Version: 1 (0x0)
        Serial Number:
            5d:8e:bb:7e:6e:73:35:92:08:23:75:2f:d1:26:4e:66:45:11:77:04
        Signature Algorithm: ED25519
        Issuer: C = DE, CN = www.example.com
        Validity
            Not Before: Mar  2 16:30:03 2022 GMT
            Not After : Jan 31 16:30:03 2024 GMT
        Subject: C = DE, CN = www.example.com
        Subject Public Key Info:
            Public Key Algorithm: ED25519
                ED25519 Public-Key:
                pub:
                    61:69:78:77:c5:af:cd:09:5e:76:6a:63:1f:7e:c8:
                    e5:5b:5b:ba:58:b9:cc:98:7b:1b:d6:01:c8:e0:57:
                    bf:b5
    Signature Algorithm: ED25519
         f7:44:47:fe:6f:bb:80:8c:25:75:c2:f1:d3:8c:ce:37:8e:f6:
         ce:17:0d:5d:ba:e0:0e:e6:35:ab:a0:63:9c:58:44:40:28:b1:
         e9:38:97:cd:f1:bf:10:45:b6:66:4c:c4:85:45:a8:55:dd:15:
         1e:b7:6e:7c:9e:b1:54:1a:67:0d
-----BEGIN CERTIFICATE-----
MIIBCDCBuwIUXY67fm5zNZIII3Uv0SZOZkURdwQwBQYDK2VwMCcxCzAJBgNVBAYT
AkRFMRgwFgYDVQQDDA93d3cuZXhhbXBsZS5jb20wHhcNMjIwMzAyMTYzMDAzWhcN
MjQwMTMxMTYzMDAzWjAnMQswCQYDVQQGEwJERTEYMBYGA1UEAwwPd3d3LmV4YW1w
bGUuY29tMCowBQYDK2VwAyEAYWl4d8WvzQledmpjH37I5Vtbuli5zJh7G9YByOBX
v7UwBQYDK2VwA0EA90RH/m+7gIwldcLx04zON472zhcNXbrgDuY1q6BjnFhEQCix
6TiXzfG/EEW2ZkzEhUWoVd0VHrdufJ6xVBpnDQ==
-----END CERTIFICATE-----
```

**Comment by tumbl3w33d** [comment]
Thank you for your feedback! I realized I need to make a minimal reproducible example and while doing it I almost thought I cannot reproduce it because what I did at first was directly mounting the certificate (one like you showed) and it indeed worked. The config attribute of prometheus is named `ca_file` though and when I use it for that, i.e. passing a CA that has issued the curve certificate, I run into the problem I described. Please have a look: https://github.com/tumbl3w33d/prometheus-ecc

**Comment by roidelapluie** [comment]
Please see: https://go.dev/play/p/OPD6rxnJGPo

It seems that your certificate is rejected by the golang library we are using:

```
x509: unsupported elliptic curve
```

**Comment by roidelapluie** [comment]
We don't receive the info as we use high-level functions, that do not return such errors.

**Comment by tumbl3w33d** [comment]
I see. I guess this can be closed then and in case anyone encounters a similar problem they will get your hint as well. I'll go evaluate curves. `secp384r1` works, for example.

**Comment by roidelapluie** [comment]
Thank you !
