### ISSUE TITLE
RFC: Change start page

### ISSUE THREAD

**Issue by matthiasr** [prometheus/prometheus#1038]
When I visit a Prometheus, 90% of the time I want to query something. However, what I see is

![prometheus_time_series_collection_and_processing_server](https://cloud.githubusercontent.com/assets/131590/9542268/ddfdec4a-4d5e-11e5-9730-56c9b99b62f0.png)

This information is interesting approximately once whenever the configuration changes, if even that. I would propose to move the status page to `/status` and make `/` redirect to or be equivalent to `/graph`.

Another candidate would be the Alerts page, but if there is anything interesting there, I have already been notified.

**Comment by fabxc** [comment]
Strong +1

**Comment by jimmidyson** [comment]
How about a mashup of graph & alert? Totally agree the status page is not the most useful root page.

**Comment by matthiasr** [comment]
Hmm a completely new root page would of course be even better. Something like one query box (but when you submit it takes you to `/graph`) and a grid of alerts (and when you click, it takes you to `/alerts` with that alert expanded)?

**Comment by fabxc** [comment]
#1039 

Any larger redesigns would be nice – I can think of dozens of possible improvements.
But probably a UI-savvy person would be needed to do this effectively.

**Comment by brian-brazil** [comment]
I think that / should be the status of the prometheus server, so things like how many chunks, series, targets it has and things like build and eval information,

I don't believe it should be either /graph or /alert as that's not relevant for all users.

**Comment by fabxc** [comment]
On IRC I suggested having an input box on the status page that takes your input to `/graph`.
It's just a fact that people running a Prometheus in many cases go there to do querying and not to check the enabled flags and such.

**Comment by brian-brazil** [comment]
@fabxc That sounds like a good idea

**Comment by brian-brazil** [comment]
This was done.
