### ISSUE TITLE
kubelet_volume_stats_capacity_bytes metric not updating when disk is resized in Kubernetes

### ISSUE THREAD

**Issue by AndrewFarley** [prometheus/prometheus#10404]
**What did you do?**
I resized an volume natively in Kubernetes, and the metric `kubelet_volume_stats_capacity_bytes` (which is labelled to and associated with the PVC) is not being updated.  However, it does look like the metric `kube_persistentvolume_capacity_bytes` (which is associated to the PV) is.  I've attached a screenshow below showing both metrics highlighting this issue, along with a kubectl screenshot as well showing the new/actual size and the naming of the PVC to confirm this.

**What did you expect to see?**
That both metrics were updated when Kubernetes resizes a volume.  See screenshots...

<img width="921" alt="Screen Shot 2022-03-07 at 9 35 09 AM" src="https://user-images.githubusercontent.com/470163/156941142-1eb7e4fc-3324-434c-ada0-ec873271789b.png">

<img width="1420" alt="Screen Shot 2022-03-07 at 9 33 09 AM" src="https://user-images.githubusercontent.com/470163/156941137-1bdd32b0-8f3c-41b3-aaf1-c9c6271b9fb5.png">

**What did you see instead? Under which circumstances?**
Instead Prometheus just shows the original "max-size" of the PVC as the `kubelet_volume_stats_capacity_bytes` value.  Restarting the pod does not seem to fix the issue, the metric still shows the original value.

**Environment**
Kubernetes: AWS EKS v1.21
Prometheus: Via helm chart `15.5.1`, running prom/prometheus:v2.30.4

**Comment by AndrewFarley** [comment]
Related To / Reference: https://github.com/DevOps-Nirvana/Kubernetes-Volume-Autoscaler/issues/1

**Comment by AndrewFarley** [comment]
FYI, team after further investigation this appears to be something happening at this version of Prometheus, and it does not appear to have happened in the past.  This customer was updated to `v2.30.4` a few months ago when it was released and we have scaled this disk in the past successfully.

Because of that, I can confirm this issue does NOT happen with an older version of Prometheus... eg this issue does not happen with Helm Chart `13.2.1`, running `prom/prometheus:v2.24.0`  See screenshots for proof/examples...

This is an example of the older version of Prometheus where this worked.  Note the "disk used" percentage in the top graph goes down when we scale up the disk, and both the middle row graphs update at the same time as they should.

<img width="1373" alt="Screen Shot 2022-03-07 at 9 56 23 AM" src="https://user-images.githubusercontent.com/470163/156941882-cfc8cf22-def3-40d2-84a7-ac7af8be2b3f.png">

This is an example of the more recent version of Prometheus where this is failing.  Note the "disk used" percentage in the top does NOT go down when we scale up the disk, and note the middle row graphs are NOT the same.

<img width="1393" alt="Screen Shot 2022-03-07 at 9 50 42 AM" src="https://user-images.githubusercontent.com/470163/156941935-496f9474-72f7-4164-8c0c-75690e9ee51d.png">

**Comment by AndrewFarley** [comment]
One more screenshot, showing the entire timeline with updates and with it working and not working

<img width="1382" alt="Screen Shot 2022-03-07 at 10 00 37 AM" src="https://user-images.githubusercontent.com/470163/156942253-0b607758-0df2-4df0-9287-af0fcc62b849.png">

Any help or a fix is appreciated!  Thanks team.

**Comment by AndrewFarley** [comment]
Ping, anyone?

**Comment by AndrewFarley** [comment]
Ping?

**Comment by lsowen** [comment]
Seeing the same thing for a PVC that I resized.  `kubelet_volume_stats_capacity_bytes` is still showing the original (smaller) size.

**Comment by peterbourgon** [comment]
I guess this isn't a Prometheus issue, but rather whatever exporter provides the `kubelet_volume_stats_capacity_bytes` metric.

**Comment by AndrewFarley** [comment]
@peterbourgon I mean, if it's not Prometheus (core) then perhaps it would be the node_exporter then eh?  Hmm, let me cross-post over there and see if anything comes of that

**Comment by peterbourgon** [comment]
I suspect it's a bug in kubelet.

**Comment by AndrewFarley** [comment]
> I suspect it's a bug in kubelet.

Where... would be that code?  :\

**Comment by discordianfish** [comment]
Not here, not in the node_exporter either. It's in kubernetes..

Also, for questions/help/support please use our [community](https://prometheus.io/community/) channels. There are more people available to potentially respond to your request and the whole community can benefit from the answers provided.
