### ISSUE TITLE
Deployment Time of an Application

### ISSUE THREAD

**Issue by caatclaudia** [prometheus/prometheus#10428]
## Proposal

In a Cluster with more than one application, the deployment time of all the applications is an important metric:

- To calculate the time that is necessary if the deployment of an application needs to be restarted;
-  To find out if the time is acceptable (e.g.: in certain Clusters, it may be necessary that the deployment time is less than 1min).

So, the Deployment time of the pods on a specific namespace should be available in Prometheus metrics.

**Comment by roidelapluie** [comment]
thanks for your github issue.

I feel like this could be an issue for https://github.com/kubernetes/kube-state-metrics.

In the meantime, prometheus client libraries expose a process_start_time_seconds metric that can be used for this.

Regards,
