### ISSUE TITLE
Proposal: add query sharding support to TSDB

### ISSUE THREAD

**Issue by pracucci** [prometheus/prometheus#10420]
## Proposal
In November 2021, Grafana Labs [announced query sharding](https://grafana.com/blog/2021/11/09/observabilitycon-announcements/) for Grafana Enterprise Metrics (GEM).

The query sharding implementation leverages some changes we did in TSDB to be able to selectively query a given shard, so that multiple processes (running on different machines) can query different shards from the same copy of a TSDB block.

A shard is a consistent set of series. The same series belongs to the same shard across different blocks. To do it, we use a simple hash mod algorithm to find out which shard each series belongs to.

We propose to upstream to Prometheus TSDB the changes we did to support query sharding. 

The proposed changes target TSDB as a library. They can be used by other OSS projects as a foundation to build query sharding capabilities.

**Use case. Why is this important?**

Query sharding can significantly reduce the time required to execute high cardinality and/or CPU intensive queries. Running GEM at Grafana Labs, we’ve seen a 10x reduction in query latency for high cardinality queries (up to 30x for some special cases).

### How query sharding works in GEM

Let’s start with an example. Consider this simple query:

```
sum(rate(metric[1m]))
```

Query sharding splits the query into N partial queries, where N is the number of shards (3 in the example) and each partial query runs the `sum(rate())` on a different set of series (a shard). Each partial query is executed by a different process (typically running on different machines) and the result of each partial query is then concatenated and a final `sum()` aggregation is run on top of it:

```
sum(
  concat(
    sum(rate(metric{__query_shard__="1_of_3"}[1m]))
    sum(rate(metric{__query_shard__="2_of_3"}[1m]))
    sum(rate(metric{__query_shard__="3_of_3"}[1m]))
  )
)
```

> Note: the `concat()` function doesn’t exist in PromQL and is not a real function. I’ve used it to give an idea of the series concatenation process.

### How GEM queries different shards from the same TSDB block

For a given block (containing all series for a time period, eg. 2h), a partial query needs to fetch chunks only from a subset of the series, which are the series matching the given shard. To do it, we added a couple of options to `storage.SelectHints`:

- ShardIndex: the ID of the shard to query from the block (ranges between 0 and ShardCount-1). Only series whose hash mod matches the ShardIndex will be considered when running the `Select()`.
- ShardCount: Total number of shards.

### Proposed changes in Prometheus TSDB

To add sharding capability to TSDB querier’s `Select()`, we propose the following changes.

Add `ShardIndex` and `ShardCount` to `storage.SelectHints`:

```golang
type SelectHints struct {
	// …

	ShardIndex uint64 // Current shard index (starts from 0 and up to ShardCount-1).
	ShardCount uint64 // Total number of shards (0 means sharding is disabled).
}
```

Add `ShardedPostings()` to `tsdb.IndexReader`. `ShardedPostings()` works similar to `SortedPostings()` but, instead of sorting postings, it filters postings by the given shard index and count:

```golang
type IndexReader interface {
	// …

	// ShardedPostings returns a postings list filtered by the provided shardIndex
	// out of shardCount. For a given posting, its shard MUST be computed hashing
	// the series labels mod shardCount (eg. `labels.Hash() % shardCount == shardIndex`).
	ShardedPostings(p index.Postings, shardIndex, shardCount uint64) index.Postings
}
```

Finally, call `ShardedPostings()` from `blockQuerier.Select()` and `blockChunkQuerier.Select()`.

To give a you a better understanding of this proposal, I’ve opened a PR showing a **reference implementation**: https://github.com/prometheus/prometheus/pull/10421

### Follow up work

In case this proposal is accepted, there’s some follow up work we commit to upstream too, in particular:

#### Series hash caching

When querying the TSDB head, the series hash is already in memory, but when querying a TSDB block the series hash needs to be computed each time. Computing the series hash is an expensive operation.

To overcome this, we’ve built an optional, configurable and fast in-memory cache for the series hashes, which we’ll propose as a follow up PR.

**Comment by bwplotka** [comment]
Love this idea!

This is something we are discussing to leverage in Thanos too cc @moadz @fpetkovski 

Details make sense, except for one thing that might matter for Thanos systems only: We don't do write deduplication of remote writes, so we can have Prometheus/agent replicas in the receiver/block TSDB code. This means that we might want to ensure that all replicas are in the same shard. The way we could it is to hash labels all but configured `replica` labels. Still I think we could implement the design proposed by @pracucci and then allow swapping `hash` function with some special hash that ignores `replica` label.

To sum, I don't see any objections to this design - maybe I would propose adding sharded method as separate interface to not overcrowd main one? 

Anyway, we can discuss this on PR

**Comment by pracucci** [comment]
Thanks Bartek for the feedback!

> Still I think we could implement the design proposed by @pracucci and then allow swapping hash function with some special hash that ignores replica label.

Agree. I think being able to customise the hashing function could allow a good degree of customisation.

> maybe I would propose adding sharded method as separate interface to not overcrowd main one?

I'm totally up for that if helps to simplify downstream projects vendor/ upgrades or TSDB maintenance. I just have a question to better understand the feedback: the `ShardedPostings()` function is directly used by the queriers `Select()`. Are there significant uses cases of the index that don't hit `Select()`? Maybe labels querying?

**Comment by roidelapluie** [comment]
Who would be responsible to error when a user has the same label set in rate({}) output?

Wrong query example: sum(rate({__name__=~"foo|bar"}[5m])). If you have foo and bar metrics (e.g. with no labels), it will fail in prometheus but not in your example.

**Comment by krajorama** [comment]
Hello from the bug scrub.

Keeping the issue open as it seems to be in progress (#10421). @pracucci is there more left to implement or is this issue done?

**Comment by pracucci** [comment]
> @pracucci is there more left to implement or is this issue done?

From my perspective it's done. I don't plan further development on this.

**Comment by beorn7** [comment]
Hello from the bug scrub!

We close this based on @pracucci 's response. If anyone is missing anything, please follow up.
