### ISSUE TITLE
TSDB DB.Delete does not work

### ISSUE THREAD

**Issue by ydayagi** [prometheus/prometheus#10430]
**What did you do?**
I am using the TSDB package for storing metrics. Later the metrics are read from TSDB and written to a remote server.
I tried using the function [DB.Delete](https://github.com/prometheus/prometheus/blob/fdb6916baff47c7d07c05bfc588c063e1cb9903f/tsdb/db.go#L1640) for deleting range.
I even tested deleting everything from 'DB.StartTime()' to 'DB.Head().MaxTime()'.
I even waited for the retention and compaction goroutine to operate.
However, the range I deleted is still there.

**What did you expect to see?**
The deleted range not appearing in queries nor on disk

**What did you see instead? Under which circumstances?**
Metrics in range are still there.

**Environment**

* System information:

	`Linux 5.14.10-300.fc35.x86_64 x86_64`

* Prometheus version:

	from go.mod: `github.com/prometheus/prometheus v1.8.2-0.20211217191541-41f1a8125e66`

**Comment by ydayagi** [comment]
@bwplotka would appreciate your thoughts on this

**Comment by bwplotka** [comment]
Hi, 

1. What matchers you provide?
2. Can you share how you are using the code? How you are creating DB etc? There might some wrong usage etc - it should work as you expect if you create DB correctly and if `func (db *DB) Delete(mint, maxt int64, ms ...*labels.Matcher) error {` does not return any errors.

**Comment by ydayagi** [comment]
> Hi,
> 
> 1. What matchers you provide?
> 2. Can you share how you are using the code? How you are creating DB etc? There might some wrong usage etc - it should work as you expect if you create DB correctly and if `func (db *DB) Delete(mint, maxt int64, ms ...*labels.Matcher) error {` does not return any errors.

1. I do not use matches. Just range. I want to delete the entire time range.
2. [Here](https://github.com/project-flotta/flotta-device-worker/blob/8b3cf5a8dd5cf4f38e3a704d62db7ed0bb2cc20f/internal/metrics/metrics.go#L65) you can see how we open the DB.
The last piece of code was this:
```go
minTime, err := db.StartTime()
if err != nil {
    log.Error(err)
    return
}
log.Info("TSDB min max", minTime, db.Head().MaxTime())
err = db.Delete(minTime, db.Head().MaxTime())
if err != nil {
    log.Error(err)
}

err = db.CleanTombstones()
if err != nil {
    log.Error(err)
}
```
db is an instance of 'tsdb.DB'.

**Comment by bwplotka** [comment]
> I do not use matches. Just range. I want to delete the entire time range.

I think that is the reason there - you have to provide matches. Even if it is `__name__ != ""` (not sure if that will work, we block this in some places)

**Comment by ydayagi** [comment]
> > I do not use matches. Just range. I want to delete the entire time range.
> 
> I think that is the reason there - you have to provide matches. Even if it is `__name__ != ""` (not sure if that will work, we block this in some places)

@bwplotka it is not working. I used `db.Delete(tMin, tMax, &labels.Matcher{
		Type: labels.MatchNotEqual,
	})`
it seems that it should match any non-empty label.
Even if adding matchers will work it will still be a bug. Because, when querying a range I do not have to provide a matcher.

**Comment by bwplotka** [comment]
Then we need to look closer, PRs welcome too! (:

**Comment by krajorama** [comment]
Hello from the bug scrub.

After two and a half years without further development , we suspect a usage problem and we're closing the issue. Please provide further information if the issue persists.
