### ISSUE TITLE
Make azure_sd_config resilient to one bad VM/NIC

### ISSUE THREAD

**Issue by gburton1** [prometheus/prometheus#10455]
## Proposal
**Use case. Why is this important?**
The azure_sd_config logic currently queries all VMs in the given subscription, and then plucks out the network interface from each VM and queries Azure for the network interface. If the network interface is not found, the whole discovery process bails out.
```
			// Get the IP address information via separate call to the network provider.
			for _, nicID := range vm.NetworkInterfaces {
				networkInterface, err := client.getNetworkInterfaceByID(ctx, nicID)
				if err != nil {
					level.Error(d.logger).Log("msg", "Unable to get network interface", "name", nicID, "err", err)
					ch <- target{labelSet: nil, err: err}
					// Get out of this routine because we cannot continue without a network interface.
					return
				}
```
This means that a large subscription with hundreds of VMs can take a complete metric outage if any random VM in the subscription gets into a bad state. This happened to us when an unimportant, offline VM failed to de-provision properly, and the VM still referred to a network interface that no longer existed. That caused a total outage of metric collection on hundreds of VMs until we could track down and clean up that VM. Here is an example showing how it bails out:
```
ts=2022-03-15T21:27:32.693Z caller=refresh.go:98 level=error component="discovery manager scrape" discovery=azure msg="Unable to refresh target groups" err="unable to complete Azure service discovery: network.InterfacesClient#Get: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code=\"ResourceNotFound\" Message=\"The Resource 'Microsoft.Network/networkInterfaces/<redacted>' under resource group <redacted> was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix
```

It would be better behavior to simply exclude the offending VM from the final list of discovered targets, and continue processing.

**Comment by David-N-Perkins** [comment]
The `return` isn't the problem. This method is run in parallel go routines, one for each VM. It's because when an error is written to the `ch` channel (two lines above the return) and the refresh method reads it, just the error is returned on line [403](https://github.com/prometheus/prometheus/blob/main/discovery/azure/azure.go#L403).

My question is what should be done with errors? Just log them and skip the VMs? Another option would be to create a metric that tracks the number of VMs that encountered errors. Open to other ideas.

**Comment by gburton1** [comment]
Skipping the VM is the main recommendation. Adding WARN-level logging would be the simplest additional step to add  visibility. Adding a metric for it would be even better because then it could be alerted on more easily. In fact, you could argue that the metric is the most important part of this feature request because it would have value even if the skip functionality were not added. The reason is that you have some grace period after an error is introduced...service discovery fails going forward, but existing targets continue getting collected. Over time, targets will get stale, and whenever Prometheus restarts you will lose all targets and take an outage until service discovery is fixed. But at least with a reliable way of being alerted, you might be able to jump in and fix it before a restart happens.

**Comment by David-N-Perkins** [comment]
OK. I'll work on adding a metric to count failures and continuing checks. @roidelapluie, any additional comments or concerns?

**Comment by roidelapluie** [comment]
What was Prometheus behaviour?

I expect that Prometheus keeps the old list of targets until the VM is decomissionned. I don't think we should drop a target because that call fails. This seems like a bug to fix by the azure teams, not prometheus.

**Comment by gburton1** [comment]
@David-N-Perkins thanks!

@roidelapluie you are correct that Prometheus keeps the old list of targets if service discovery starts failing to process one VM. But if Prometheus gets restarted/redeployed, then you lose the old list of targets, and the service discovery process never succeeds at building a new list of targets because it chokes on the single bad VM. The malconfigured VM needs to be fixed on the Azure side of course, but increased visibility and resiliency in this situation would be desirable on the Prometheus side.

**Comment by roidelapluie** [comment]
It seems wrong to ignore all failures. Can we only ignore "404" errors?

**Comment by gburton1** [comment]
@roidelapluie good idea. Ignoring only 404s would be a well-constrained way to make a big improvement to resiliency of service discovery. 

@David-N-Perkins adding the metric for these errors is my top request. But I also think that ignoring 404s and continuing the service discovery processing, whether its the initial refresh or later ones, would be a great improvement to the robustness/resiliency of this service discovery process.

**Comment by David-N-Perkins** [comment]
@gburton1 I put up a PR. Would you be able to test the changes?

**Comment by gburton1** [comment]
Sure. Do PR builds generate a docker image artifact? We run Prometheus in Kubernetes.

**Comment by David-N-Perkins** [comment]
I don't think so. The CircleCI build just produces [executables](https://app.circleci.com/pipelines/github/prometheus/prometheus/16361/workflows/702ba023-2d93-49ce-935a-d3548a11d049/jobs/78183/artifacts). There are [instructions](https://github.com/David-N-Perkins/prometheus/tree/azure-sd-failure-counter#building-the-docker-image) for building it manually. If that's too difficult, I could build an image, but I'm not sure where to post it for you to access.

**Comment by gburton1** [comment]
@David-N-Perkins I saw the PR merged this morning; thanks a lot for taking this on and making it more resilient, and making service discovery failure more visible via a metric.

**Comment by roidelapluie** [comment]
Indeed. Since it is merged, I will close this issue. Thanks all!
