### ISSUE TITLE
[Question] Why counters starts from NO_DATA rather than 0

### ISSUE THREAD

**Issue by ihsancemil** [prometheus/prometheus#10466]
# Question
https://github.com/prometheus/prometheus/blob/8b5eb562b12f4ea0e0f9126e7b25f5a450687970/promql/functions.go#L70
In above code if there is only one point exist it does not calculate the rate(or increase) of the samples. For example, VictoriaMetrics assumes that counters starts from 0 which looks natural to me. Why prometheus ignores these samples.

# Behind the story
I create a counter for my method calls. I use method parameters as my labels. I want to count all the distinct method calls. Some of the parameters only one time used in my method. Thus, when I call the my method increase(query_selector[5m]) if the data is not exist at 5m before  it return 0 as a result (You can imagine query_selector[5m] result [1, 1, 1, 1] with respective timestamps).

# Further investigation
`query_selector - query_selector offset d` is also fails because the right side of the minus returns NO_DATA. Even if left side returns a valid value. This query result with NO_DATA rather than left side value. This problem can be related.

**Comment by roidelapluie** [comment]
because many counters do *not* start at zero. e.g. if you have traffic disruption, or you add a target that was never monitored before.

Assuming that a counter starts from zero would be inventing data and returning incorrect values.

**Comment by roidelapluie** [comment]
If you really have the use case for this, you could do: `query_selector - query_selector offset d or query_selector`
