### ISSUE TITLE
scrape: introduce two new metrics: `scrape_error_count` and `scrape_total_count`

### ISSUE THREAD

**Issue by Dentrax** [prometheus/prometheus#10468]
## Proposal
**Use case. Why is this important?**

`scrape_error_count`: simply we should increase this gauge in case either `err != nil` or `non-ok` response. https://github.com/prometheus/prometheus/blob/9ed56c6065f2602090553cc3ced90baa4e14e1f9/scrape/scrape.go#L784-L795

It would be better for observation if there are some _failed_ scrapes.

`scrape_total_count`: we should increase this just before run the `scrape` function. https://github.com/prometheus/prometheus/blob/9ed56c6065f2602090553cc3ced90baa4e14e1f9/scrape/scrape.go#L770  

By doing so, we can calculate _scrape success rate_ by dividing the failed count by the total number of scrapes to find fail rate.: `(scrape_total_count / scrape_error_count)`

*“Nice to have” is not a good use case. :)*
`-`

**Comment by roidelapluie** [comment]
What would be the point of (scrape_total_count / scrape_error_count)? That sounds like `avg(up)` ?

**Comment by Dentrax** [comment]
Correct, actually dropped that as an example. We can get more _scraping_ details about target applications by adding these two metrics. It would be nice to have to create some dashboards that show scrape healthy _per application_.

**Comment by roidelapluie** [comment]
Why not using avg(up) by(job) ?

**Comment by Dentrax** [comment]
Hmmm, by using this query actually we are able to calculate uptime percent. And `count(up) == 0` means that Prometheus couldn't scrape it? In this case, we don't need smth like `scrape_error_count`, right?

**Comment by roidelapluie** [comment]
uptime percent is avg_over_time(up[1h]).

**Comment by roidelapluie** [comment]
I will close this based on y previous answers.
