### ISSUE TITLE
Is that possible to query for the “raw” data within a time range with exact ingested time stamps without considering arbitrary step for range queries

### ISSUE THREAD

**Issue by venkatchinmay** [prometheus/prometheus#10502]
Hi, I would like to retrieve data **AS it was collected and recorded by Prometheus.**
I do not want to use an arbitrary step for range queries.

Is that possible to query for the “raw” data within a time range with exact ingested time stamps ?
**If it is possible to get, so how ?** 
**if it is not possible why ? and suggest any alternative**

@codesome

**Comment by codesome** [comment]
Closing in favour of https://github.com/prometheus/prometheus/discussions/10503
