### ISSUE TITLE
Sudden unexplained drop in scrape_samples_scraped within every 24 hours

### ISSUE THREAD

**Issue by subject-of-ymir** [prometheus/prometheus#10512]
What did you do?

--> I have 4 services running in my docker stack, namely, Prometheus, Promscale, Postgres/Timescaledb and Grafana to monitor my django application. Currently I am working on testing APIs RPM and latency metrics, and accordingly I have a "api_latency_bucket" histogram and "api_hit_rate" counter metrics. Both metrics have a label called "apis" and values are the api name in my code. (Example: api_hit_rate.label(func_name).inc())

What did you expect to see?

--> I expected too see my API RPM and compare it with my elastic apm that I previously have been using. And if they show different metrics trend, I shall use logger info to resolve who shows the truth.

What did you see instead? Under which circumstances?

-->  I noticed that API RPM get sudden dips and it deviates from what my elastic apm shows. So I decided to check the samples scraped at the time of dip and it matched. Whenever there is a sudden drop in samples scraped, there is drop in my metrics too.

Environment

Docker-compose:

version: “3.3”

services:

postgres-db:
image: [Package dev_promscale_extension · GitHub](http://ghcr.io/timescale/dev_promscale_extension:develop-ts2-pg14)
ports:
- 5432:5432/tcp
networks:
- rexnet
environment:
- POSTGRES_PASSWORD=***
- POSTGRES_USER=***
- POSTGRES_DB=***
deploy:
placement:
constraints: [node.labels.trex.type ==mon]

promscale:
image: timescale/promscale:latest
ports:
- 9201:9201/tcp
- 9202:9202/tcp
depends_on:
- postgres-db
- prometheus
networks:
- rexnet
environment:
- PROMSCALE_DB_CONNECT_RETRIES=10
- PROMSCALE_DB_HOST=postgres-db
- PROMSCALE_DB_PORT=5432
- PROMSCALE_DB_NAME=***
- PROMSCALE_DB_SSL_MODE=allow
- PROMSCALE_DB_USER=***
- PROMSCALE_DB_PASSWORD=***

deploy:
  placement:
    constraints: [node.labels.trex.type ==mon]
prometheus:
image: prom/prometheus:main
user: ***
ports:
- 9090:9090
networks:
- rexnet
command: --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yml
volumes:
- ./prometheus:/etc/prometheus
- prometheus-data:/prometheus
- /var/run/docker.sock:/var/run/docker.sock:ro
deploy:
placement:
constraints: [node.labels.trex.type ==mon]

grafana:
image: grafana/grafana:7.5.7
ports:
- 3000:3000
networks:
- rexnet
restart: unless-stopped
volumes:
- ./grafana:/etc/grafana/provisioning/datasources
- grafana-data:/var/lib/grafana
deploy:
placement:
constraints: [node.labels.trex.type == mon]

networks:
rexnet:
driver: overlay
attachable: true
external:
name: rexnet

volumes:
prometheus-data:
grafana-data:

Prometheus.yml:

-->
global:
  scrape_interval: 10s
  scrape_timeout: 10s
  evaluation_interval: 1m
scrape_configs:
- job_name: **
  honor_timestamps: true
  scrape_interval: 10s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  static_configs:
  - targets:
    - **:***
- job_name: ***
  honor_timestamps: true
  scrape_interval: 10s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  static_configs:
  - targets:
    - lobby-***:***
- job_name: ***
  honor_timestamps: true
  scrape_interval: 10s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  static_configs:
  - targets:
    - ***:***
- job_name: ***
  honor_timestamps: true
  scrape_interval: 10s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  static_configs:
  - targets:
    - ***
- job_name: ***
  honor_timestamps: true
  scrape_interval: 10s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  static_configs:
  - targets:
    - ***
- job_name: ***
  honor_timestamps: true
  scrape_interval: 10s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  static_configs:
  - targets:
    - ***
- job_name: ***
  honor_timestamps: true
  scrape_interval: 10s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  static_configs:
  - targets:
    - ***
- job_name: ***
  honor_timestamps: true
  scrape_interval: 10s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  static_configs:
  - targets:
    - ***
- job_name: ***
  honor_timestamps: true
  scrape_interval: 10s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  static_configs:
  - targets:
    - ***
- job_name: ***
  honor_timestamps: true
  scrape_interval: 10s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  relabel_configs:
  - source_labels: [__meta_dockerswarm_network_name]
    separator: ;
    regex: rexnet
    replacement: $1
    action: keep
  - source_labels: [__meta_dockerswarm_service_label_prometheus_cashtable_job]
    separator: ;
    regex: .+
    replacement: $1
    action: keep
  dockerswarm_sd_configs:
  - follow_redirects: true
    host: unix:///var/run/docker.sock
    role: tasks
    port: ***
    filters: []
    refresh_interval: 1m
- job_name: ***
  honor_timestamps: true
  scrape_interval: 10s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  relabel_configs:
  - source_labels: [__meta_dockerswarm_network_name]
    separator: ;
    regex: rexnet
    replacement: $1
    action: keep
  - source_labels: [***]
    separator: ;
    regex: .+
    replacement: $1
    action: keep
  dockerswarm_sd_configs:
  - follow_redirects: true
    host: unix:///var/run/docker.sock
    role: tasks
    port: ***
    filters: []
    refresh_interval: 1m
- job_name: ***
  honor_timestamps: true
  scrape_interval: 10s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  relabel_configs:
  - source_labels: [__meta_dockerswarm_network_name]
    separator: ;
    regex: rexnet
    replacement: $1
    action: keep
  - source_labels: [****]
    separator: ;
    regex: .+
    replacement: $1
    action: keep
  dockerswarm_sd_configs:
  - follow_redirects: true
    host: unix:///var/run/docker.sock
    role: tasks
    port: ***
    filters: []
    refresh_interval: 1m
- job_name: ***
  honor_timestamps: true
  scrape_interval: 10s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  relabel_configs:
  - source_labels: [__meta_dockerswarm_network_name]
    separator: ;
    regex: rexnet
    replacement: $1
    action: keep
  - source_labels: [***]
    separator: ;
    regex: .+
    replacement: $1
    action: keep
  dockerswarm_sd_configs:
  - follow_redirects: true
    host: unix:///var/run/docker.sock
    role: tasks
    port: ***
    filters: []
    refresh_interval: 1m
**_- job_name: monitor-django
  honor_timestamps: true
  scrape_interval: 10s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  authorization:
    type: HTTP_X_METRICS_AUTH
    credentials: <secret>
  follow_redirects: true
  static_configs:
  - targets:
    - ***_**
remote_write:
- url: http://promscale:9201/write
  remote_timeout: 30s
  follow_redirects: true
  queue_config:
    capacity: 2500
    max_shards: 200
    min_shards: 1
    max_samples_per_send: 500
    batch_send_deadline: 5s
    min_backoff: 30ms
    max_backoff: 5s
  metadata_config:
    send: true
    send_interval: 1m
    max_samples_per_send: 500

The last job named "monitor-django" is the one that I am having problem in.

Here is the image of samples scraped graph:

![](https://aws1.discourse-cdn.com/standard20/uploads/prometheus/original/1X/450e0c8a7aeb098c884d61b52af607b739be581a.jpeg)

I am unable to figure out where the problem lies in prometheus server.

**Comment by roidelapluie** [comment]
You could look at the missing metrics at that time. is your application restarting?

**Comment by beorn7** [comment]
Hello from the bug scrub!

With no feedback on this in more than two years, we are closing the issue.
