### ISSUE TITLE
Http endpoint to change scrape_interval and scrape_timeout.

### ISSUE THREAD

**Issue by VenkateswaranJ** [prometheus/prometheus#10513]
Currently, there is no Http endpoint for changing scrape_interval and scrape_timeout. One has to edit the config file manually and reload the config every time. Also in [<http_sd_config>](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#http_sd_config) it is only possible to add target URLs and labels but it's not possible to add scrape_interval for each target.

**Comment by roidelapluie** [comment]
With http_sd_config you can set scrape interval for each target:
```
[
    {
        "targets": ["10.0.40.3:9100"],
        "labels": {
            "__meta_datacenter": "london",
            "__scrape_interval__": "1m",
            "__scrape_timeout__": "5m"
        }
    },
    {
        "targets": ["10.0.40.1:9100"],
        "labels": {
            "__meta_datacenter": "london",
            "__scrape_interval__": "1m",
            "__scrape_timeout__": "5m"
        }
    }
]

```

You can also do this with relabel_configs. Without knowing more about your usecase, it is difficult to help you more.
