### ISSUE TITLE
Support for Kafka and/or gnatsd remote storage

### ISSUE THREAD

**Issue by jimmidyson** [prometheus/prometheus#1052]
Or other pub-sub or queuing systems.

This would allow for a more flexible architecture for storage & also alerting, without the need to add more options directly into Prometheus codebase.

**Comment by mdlayher** [comment]
Seems to me that this issue has been obsoleted with the addition of the generic remote storage write path.  Am I correct?

**Comment by brian-brazil** [comment]
That's correct.
