### ISSUE TITLE
Structured Remote Write Protocol

### ISSUE THREAD

**Issue by andysim3d** [prometheus/prometheus#10539]
## Proposal

**Use case. Why is this important?**
Structured remote write, make each remote write self-contained. So that ingestors could be stateless. 

### OVERVIEW

Prometheus as de facto monitoring infrastructure is being widely used in industry. It scrapes data following OpenMetrics protocol and stores data in a storage - remote or local TSDB. 

In current implementation of prometheus remote write, it leverages a straightforward [data model](https://github.com/prometheus/prometheus/blob/main/prompb/remote.proto#L22-L28): one write request contains a list of [timeseries](https://github.com/prometheus/prometheus/blob/main/prompb/types.proto#L58-L64), or a list of metadata. In particular, per timeseries contains a list of samples. Those samples are [time sorted double values](https://github.com/prometheus/prometheus/blob/main/prompb/types.proto#L41-L46). 

For Gauge and Counter, that simple data model is sufficient. But when it comes to Histogram and Summary, things start to become complicated. For Histogram, Prometheus treats per configured buckets as one time series(one time series per configured quantile for Summary). That means if a histogram has 10 configured buckets, it might end up split into 12 different write requests.

[this proposal](https://docs.google.com/document/d/1i880vXorPec1ls91bnuoKR3-Hl3-D9XA1q1w734rZnU/edit#) is the design doc, contains the background and discussions around the topic.

**Comment by roidelapluie** [comment]
Thanks for this. Could you submit your design doc here: https://github.com/prometheus/docs/blob/main/content/docs/introduction/design-doc.md

**Comment by andysim3d** [comment]
Hi @roidelapluie , it is about 2 months since I opened pr to add proposal to prometheus doc. is there any concerns/thoughts that blocks the review?

**Comment by roidelapluie** [comment]
Hello, I think we should point this at @cstyan @csmarchbanks @bwplotka which are maintainers of remote storage.

**Comment by krajorama** [comment]
Hello from the bug scrub,

For histograms this issue is being solved long term by https://github.com/prometheus/proposals/blob/main/proposals/2024-01-26_classic-histograms-stored-as-native-histograms.md That doesn't include Summary type though.

@cstyan @csmarchbanks @bwplotka in view of PRW 2.0 is this issue still needed to be solved?

**Comment by bwplotka** [comment]
Ah, did not notice this. Indeed this can be closed, solved mostly by nhcb. Summaries are still not technically structured but this is generally less of an issue - much easier to detect and the consequences are not that big.

Let's close this one. We can reopen/or can create an issue for full scrape transactionally one day, but currently it's not planned.

Note that remote write protocol, especially 2.0 allows structured write, the majority of work would be to extend current TSDB and WAL with transaction ID, so remote write WAL watching with sharding can leverage that.

Thanks!
