### ISSUE TITLE
web.enable-lifecycle  flag   false status  

### ISSUE THREAD

**Issue by freemankevin** [prometheus/prometheus#10541]
This flag value shows that it is not in line with reality, it is obviously enabled and the test has passed, and then the false state is also displayed here.

![image](https://user-images.githubusercontent.com/71524776/161888169-cb60e156-2a60-4208-a66e-b34741d77af3.png)

![image](https://user-images.githubusercontent.com/71524776/161888203-262368a8-a165-4998-ae74-56f8d955df3a.png)

**Comment by roidelapluie** [comment]
I can not reproduce it. Are you sure that you are pointing to the same release?

**Comment by freemankevin** [comment]
I found the reason. My docker-compose mounts prometheus.yaml as a file, so even if the interface is dropped, the effect cannot be seen, because docker needs to mount a directory to do file synchronization, and the directory permission is 775.
![388e71d31fd92a2843ae63c704d9f3a](https://user-images.githubusercontent.com/71524776/162382469-d71f7501-8d20-4ebc-acce-e68c8b904b05.png)

I truly appreciate your timely help.

**Comment by roidelapluie** [comment]
Thanks!
