### ISSUE TITLE
OTLP input API alongside remote write ingest

### ISSUE THREAD

**Issue by gouthamve** [prometheus/prometheus#10547]
OpenTelemetry is gaining more and more popularity and I think we should add an endpoint to Prometheus to ingest OTLP metrics.

I've done similar work here: https://github.com/grafana/mimir/pull/695

I am working on the PR right now, but before I send it, I want to make sure we want to OTLP directly. And there is also the caveat that if a request fails and is retried, it will result in a Out of Order ingest error and will be dropped. This is obviously not a great scenario, but I think its still better than not ingesting OTLP at all.

**Comment by gouthamve** [comment]
https://github.com/prometheus/prometheus/issues/8535#issuecomment-1084299444 looks like it might fix the OOO writes, but it is a little bit far away I think.

**Comment by gouthamve** [comment]
I'm going to think about the TSDB stuff for a bit, but answering the other bit:

> I also think we should not create a double dependency between prometheus and opentelemetry-contrib

That is fair. I think we can also move the conversion code to Prometheus and let it become the source of truth which otel-contrib imports. I _think_ that the community would be open to that.

**Comment by roidelapluie** [comment]
> I'm going to think about the TSDB stuff for a bit, but answering the other bit:


cumulative is what delta encoding is doing, the challenge is to get the correct value at the beginning of the chunk

**Comment by roidelapluie** [comment]
As per Valencia dev summit discussion, let's close this for now. We can reconsider this later.
