### ISSUE TITLE
Pagination support required for Prometheus API or Query to List down the metrics.

### ISSUE THREAD

**Issue by d14mittal** [prometheus/prometheus#10563]
GET /api/v1/query API gives a list of all metrics for `query={__name__!=""}`
If I want to get only first 100, then next 100-200, then 200-300 so on.... how can I do that???
How to achieve pagination either in query or the API?

**Comment by roidelapluie** [comment]
This is in general a bad idea to extract all metrics. Pagination has the issue that we can not properly isolate every request, resulting in mixed output.

If you just want query names, you can also use `/api/v1/label/__name__/values`

**Comment by alanprot** [comment]
Hi..

What about pagination on the `/series` api? It returns a sorted list so it would be easier to implement a pagination there?

WDYT @roidelapluie
