### ISSUE TITLE
RemoteWrite client / prompb moved into prometheus/common

### ISSUE THREAD

**Issue by jzelinskie** [prometheus/prometheus#10565]
## Proposal

Lots of projects want access the protobufs for the remote write protocol and the boilerplate to make a request.
Right now that requires pulling in all of Prometheus, when really doesn't doesn't seem necessary.
I'm proposing moving some of this code into the github.com/prometheus/common repository.

**Comment by roidelapluie** [comment]
Thanks for your interest. We have not made a lot of noise about it yet, but we are experiencing with [buf.build](https://buf.build/prometheus/prometheus/assets).

Could you try:

```
go get go.buf.build/protocolbuffers/go/prometheus/prometheus
```

**Comment by roidelapluie** [comment]
Since there has been no further feedback, i will close this issue.

**Comment by jzelinskie** [comment]
Yep! This solved our problem!
