### ISSUE TITLE
Dataraces in package `tsdb`

### ISSUE THREAD

**Issue by chavacava** [prometheus/prometheus#10570]
While testing a new linting rule for [revive](https://github.com/mgechev/revive) I found subtle potential dataraces in the package `tsdb`.
Both dataraces are caused by capturing the named function result `err` in anonymous functions that are executed as goroutines.
First occurrence:
https://github.com/prometheus/prometheus/blob/6555cc68caf8d8f323056e497ae7bb1e32a81667/tsdb/head_wal.go#L134-L141
and following references to `err` in the function literal 

Second:
https://github.com/prometheus/prometheus/blob/6555cc68caf8d8f323056e497ae7bb1e32a81667/tsdb/agent/db.go#L411-L418
and following references to `err` in the function literal

**Comment by Kanika637** [comment]
I am new to this project and I want to work on this issue, Could you please guide me?

**Comment by chavacava** [comment]
> I am new to this project and I want to work on this issue, Could you please guide me?

Well I'm also new to this project.
I think there is not to much to do on this issue, it is a tiny bug, and I've already made a PR #10571
If you are looking for GO open source projects to collaborate on, you can check [revive](https://github.com/mgechev/revive/) a GO static analysis framework. I'll be glad to guide you working on some of the issues

**Comment by Kanika637** [comment]
Ohh ok then, will surely check https://github.com/mgechev/revive/  @chavacava
