### ISSUE TITLE
Allow specifying metrics to skip in promtool lint

### ISSUE THREAD

**Issue by chancez** [prometheus/prometheus#10574]
## Proposal
**Use case. Why is this important?**

An application may be exposing metrics that are defined by third party libraries, which the developer has no control over, so it would be useful to be able to configure promtool to skip these metrics when linting.

One example is the GoCollector metrics from `prometheus/client_golang` fails linting:

```
go_gc_heap_allocs_by_size_bytes_total non-counter metrics should not have "_total" suffix
go_gc_heap_frees_by_size_bytes_total non-counter metrics should not have "_total" suffix
go_gc_pauses_seconds_total non-counter metrics should not have "_total" suffix
```

**Comment by chancez** [comment]
Also it seems like the metrics that don't conform are new in 1.12.x. So I think it may have been part of https://github.com/prometheus/client_golang/pull/955

**Comment by bwplotka** [comment]
Yea, let's fix it on client_golang side, thanks for reporting!

**Comment by roidelapluie** [comment]
@bwplotka what is the status here?

**Comment by bwplotka** [comment]
It is fixed in latest version, plus we disabled those new metrics by default. 

I believe this means we can close this issue for now. We can reopen when there will be more arguments for such feature. Thanks!
