### ISSUE TITLE
Implement Links between Graph and Expression Browser Pages

### ISSUE THREAD

**Issue by matttproud** [prometheus/prometheus#106]
# In the Graph Page
- "View this Graph in the Expression Browser"

# In the Expression Browser
- "View this Expression as a Graph" link.  @juliusv can offer some insights into runtime checks to ensure that the right kind of expressions are only allowed this.
- Use heuristics from the AST to create node-level links of expressions such that these sub expressions can be graphed.

**Comment by juliusv** [comment]
The only reason this was left open was the last point "Use heuristics from the AST to create node-level links of expressions such that these sub expressions can be graphed.".

I opened https://github.com/prometheus/prometheus/issues/436 for that and will close this one.
