### ISSUE TITLE
Prometheus Compaction Issue

### ISSUE THREAD

**Issue by halfcipher** [prometheus/prometheus#10611]
We are facing an issue with the Prometheus due to compaction in an OKD cluster 3.11. We have observed that Prometheus is not able to delete the .tmp files.

The Prometheus data is persisted using persistent volume as NFS.

Following are the errors:

`level=error ts=2022-04-20T11:59:54.933890812Z caller=compact.go:432 component=tsdb msg="removed tmp folder after failed compaction" err="remove /prometheus/01G13DER2DGHDAQE70SXGQEQKA.tmp/chunks: directory not empty"`

`level=error ts=2022-04-20T11:59:54.934016435Z caller=db.go:272 component=tsdb msg="compaction failed" err="persist head block: write compaction: add series: out-of-order series added with label set \"{__name__=\\\"ALERTS\\\",alertname=\\\"ClusterMonitoringOperatorDown\\\",alertstate=\\\"pending\\\",severity=\\\"critical\\\"}\""`

Pleas help me resolve this issue.

**Comment by britcey** [comment]
NFS is explicitly called out as not supported in the docs:

https://prometheus.io/docs/prometheus/latest/storage/#operational-aspects

CAUTION: Non-POSIX compliant filesystems are not supported for Prometheus' local storage as unrecoverable corruptions may happen. NFS filesystems (including AWS's EFS) are not supported. NFS could be POSIX-compliant, but most implementations are not. It is strongly recommended to use a local filesystem for reliability.

**Comment by roidelapluie** [comment]
Indeed, your issue is very likely linked with NFS. Please try with another filesystem.
