### ISSUE TITLE
Unable to build Prometheus 2.35.0

### ISSUE THREAD

**Issue by ddevault** [prometheus/prometheus#10619]
```
web/ui/assets_embed.go:25:33: undefined: EmbedFS
```

**Comment by roidelapluie** [comment]
please run `make build` which will generate the correct files.

**Comment by ddevault** [comment]
Works. Thanks!

**Comment by mingqibee** [comment]
@ddevault Hi How do you operate it，I have the same problem now。tks

**Comment by mingqibee** [comment]
@roidelapluie  @ddevault The error is as follows after I run make build, please help to check, is there something wrong with my operation
![image](https://user-images.githubusercontent.com/38835550/177491614-81c504aa-674e-4b21-b9e9-6174c50144a7.png)

**Comment by mingqibee** [comment]
I encountered the same problem because it was the main branch. Later I re-downloaded the code that specified the tag and make build , Works. Thanks!
