### ISSUE TITLE
Incorrect parsing of OpenTSDB failures

### ISSUE THREAD

**Issue by swsnider** [prometheus/prometheus#1061]
When OpenTSDB 2.1.0 fails to record timeseries, it seems to always return the errors array, even if summary output is specifically requested. Since this is not an `int`, prometheus returns a json error spuriously, from https://github.com/prometheus/prometheus/blob/master/storage/remote/opentsdb/client.go#L131

**Comment by juliusv** [comment]
Thanks for reporting! We currnetly don't have an OpenTSDB around for testing, but happy to accept fixes!

**Comment by brian-brazil** [comment]
This code is about to be removed, so this is obsolete.
