### ISSUE TITLE
Add feature flag to control /api/v1/metadata 

### ISSUE THREAD

**Issue by SuperQ** [prometheus/prometheus#10618]
## Proposal

The current `/api/v1/metadata` includes every instance of the metric definition. There are [cases where application bugs introduce high cardinality HELP text](https://github.com/prometheus/jmx_exporter/issues/703).

It would be useful to have a flag to squash this and only return one (fist?) instance of the definitions in order to avoid expensive (many megabytes) of metadata being returned by this API endpoint.

**Comment by juanrh** [comment]
@roidelapluie I'm interested on working on this issue

**Comment by juanrh** [comment]
Keeping one arbitrary definition seems like a simple change, that could be enabled with a query for additional flexibility. 

```
diff --git a/web/api/v1/api.go b/web/api/v1/api.go
index 3c4a34291..f4fe932b0 100644
--- a/web/api/v1/api.go
+++ b/web/api/v1/api.go
@@ -1165,6 +1165,7 @@ func (api *API) metricMetadata(r *http.Request) apiFuncResult {
                }
        }
 
+       firstMetaOnly := r.FormValue("firstMetaOnly") == "true" // FIXME better name for var and param
        // Put the elements from the pseudo-set into a slice for marshaling.
        res := map[string][]metadata{}
        for name, set := range metrics {
@@ -1175,6 +1176,9 @@ func (api *API) metricMetadata(r *http.Request) apiFuncResult {
                s := []metadata{}
                for metadata := range set {
                        s = append(s, metadata)
+                       if firstMetaOnly {
+                               break
+                       }
                }
                res[name] = s
        }
```

What do you think?

**Comment by bwplotka** [comment]
cc @ArthurSens 

Should we instead have some API parameter for this? What it could be called? `limit-per-metric`? Might be more sensible than feature flag?

**Comment by ArthurSens** [comment]
The change would be a lot simpler indeed, almost the same as suggested by @juanrh 

For adoption it would be a lot easier with a parameter too, there's no need to reconfigure the prometheus container with an extra feature flag

**Comment by ArthurSens** [comment]
> Maybe `limit-help-per-metric`?

Feels a bit strange saying that we're limiting help text, but we return the whole metadata

**Comment by bwplotka** [comment]
Yea, same problem might happen for other metadata, so I think I would vote for just per metric for now?

**Comment by ArthurSens** [comment]
should be ready for review now!
