### ISSUE TITLE
OpenTSDB has a hard-coded limit of 8 tags per datapoint

### ISSUE THREAD

**Issue by swsnider** [prometheus/prometheus#1062]
If you attempt to submit a datapoint with more than 8 tags, OpenTSDB will return an error.

See OpenTSDB/opentsdb#437

We should handle this like we do NaN, and avoid sending these points.

**Comment by fabxc** [comment]
Tough one. Makes OpenTSDB pretty useless as a Prometheus remote storage in my opinion – this also gives people reasons to design their metrics around limitations of down stream components.

**Comment by beorn7** [comment]
Yes, known issue.

We definitely need to document that and think about a fallback mechanism once OpenTSDB support is not purely experimental.

**Comment by beorn7** [comment]
Fallback might not be reasonably possible. Probably just not write the affected time series out to OpenTSDB and issue warnings about it.

**Comment by fabxc** [comment]
From recent discussion this is no longer the case: https://github.com/prometheus/prometheus/issues/10#issuecomment-203414217

**Comment by grobie** [comment]
For reference, the limit is controlled by `tsd.storage.max_tags` and still defaults to 8.
