### ISSUE TITLE
storage.tsdb.path to s3fs storage?

### ISSUE THREAD

**Issue by tooptoop4** [prometheus/prometheus#10628]
has anyone used prometheus against s3fs mount instead of local storage? my prometheus runs on k8s and i want to avoid having a persistent EBS

**Comment by roidelapluie** [comment]
s3fs is not supported. Prometheus uses posix mechanisms that require actual filesystems.

https://prometheus.io/docs/prometheus/latest/storage/

**Comment by tooptoop4** [comment]
@roidelapluie juicefs claims posix support
