### ISSUE TITLE
New `bool` modifier not working in recording rules

### ISSUE THREAD

**Issue by juliusv** [prometheus/prometheus#1065]
For example, try the expression `up > bool 0` with some up and down targets. It works fine in the expression browser, but in a recorded rule it acts like the `bool` isn't there.

**Comment by juliusv** [comment]
@brian-brazil @fabxc

**Comment by juliusv** [comment]
The status page also shows `newup{} = up > 0` instead of `newup{} = up > bool 0`.

**Comment by juliusv** [comment]
So for the printed text, I guess we just need new printing logic in https://github.com/prometheus/prometheus/blob/master/promql/printer.go. Still doesn't explain the different evaluation behavior between rules and interactive queries though.

**Comment by juliusv** [comment]
Argh. The printer is indeed the culprit, it seems. Look at this line in recording.go:

https://github.com/prometheus/prometheus/blob/master/rules/recording.go#L47

IMO having to go through serializing and deserializing an expression again internally to evaluate it for a recording rule is quite a wart. Would it be possible to keep it in symbolic form instead and only use the printer-generated serializations for user-targeted output?

**Comment by fabxc** [comment]
This was a 'good for now' solution. We can certainly keep the AST node directly in rules.
