### ISSUE TITLE
Can't CPU pprof prometheus >0.15

### ISSUE THREAD

**Issue by mwitkow-io** [prometheus/prometheus#1067]
It seems that since 0.15, I am no longer able to grab a CPU profile of our prometheus. This is sad, because it was useful to see where our CPU actually goes (whether it's rules or scraping, or metric archiving). Right now I get:

```
michal:~/Private/i (master) $ go tool pprof http://leafmon:9090/debug/pprof/profile
Fetching profile from http://leafmon:9090/debug/pprof/profile
Please wait... (30s)
Saved profile in /home/michal/pprof/pprof.eu1-prod-simleaf-2.simleaf.eu1-prod.internal.improbable.io:9090.samples.cpu.001.pb.gz
Entering interactive mode (type "help" for commands)
(pprof) top10
1.77mins of 1.77mins total (  100%)
      flat  flat%   sum%        cum   cum%
  1.77mins   100%   100%   1.77mins   100%  
```
Similarly `web` is empty. Has something changed for 0.15? Or am I just missing something?

**Comment by brian-brazil** [comment]
On Thu, Sep 10, 2015 at 10:01 AM, Michal Witkowski <notifications@github.com
> wrote:

> It seems that since 0.15, I am no longer able to grab a CPU profile of our
> prometheus. This is sad, because it was useful to see where our CPU
> actually goes (whether it's rules or scraping, or metric archiving). Right
> now I get:
>
> michal:~/Private/i (master) $ go tool pprof http://leafmon:9090/debug/pprof/profile
> Fetching profile from http://leafmon:9090/debug/pprof/profile
> Please wait... (30s)
> Saved profile in /home/michal/pprof/pprof.eu1-prod-simleaf-2.simleaf.eu1-prod.internal.improbable.io:9090.samples.cpu.001.pb.gz
> Entering interactive mode (type "help" for commands)
> (pprof) top10
> 1.77mins of 1.77mins total (  100%)
>       flat  flat%   sum%        cum   cum%
>   1.77mins   100%   100%   1.77mins   100%
>
> Similarly web is empty. Has something changed for 0.15? Or am I just
> missing something?
>

This was always broken until recently.
https://github.com/prometheus/prometheus/commit/da2499d5a5de661292de129832aef67dfbc42385
fixes it. There hasn't been a release since, so you'll need to build from
head to get the fix.

-- 
Brian Brazil
www.robustperception.io

**Comment by juliusv** [comment]
Yep, the fix will be rolled out with the next release (RC expected this week). Sorry about that! Closing the issue here, as it's fixed in HEAD.
