### ISSUE TITLE
Build error in master "Failed to parse source map from @nexucis/src/index.ts"

### ISSUE THREAD

**Issue by oshyshkov2010** [prometheus/prometheus#10674]
### What did you do?

Cloned the latest version and executing 
make build

### What did you expect to see?

Successful build

### What did you see instead? Under which circumstances?

Darwin X64, nvm version v16.15.0, node v16.15.0, npm version '8.5.5', go version go1.18.1 darwin/amd64
git clone https://github.com/prometheus/prometheus.git
cd prometheus
make build
...
Creating an optimized production build...
Compiled with warnings.

Failed to parse source map from '/Users/oleksiishyshkov/tools/prometheus_src/prometheus/web/ui/node_modules/@nexucis/src/index.ts' file: Error: ENOENT: no such file or directory, open '/Users/oleksiishyshkov/tools/prometheus_src/prometheus/web/ui/node_modules/@nexucis/src/index.ts'

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.

File sizes after gzip:

  454.65 kB  build/static/js/main.7fd31b42.js
  52.38 kB   build/static/css/main.faad45b4.css

The project was built assuming it is hosted at ./.
You can control this with the homepage field in your package.json.

The build folder is ready to be deployed.

Find out more about deployment here:

  https://cra.link/deployment

>> bundling npm licenses
rm -f "npm_licenses.tar.bz2"
find web/ui/node_modules -iname "license*" | tar cfj "npm_licenses.tar.bz2" --transform 's/^/npm_licenses\//' --files-from=-
tar: Option --transform is not supported
Usage:
  List:    tar -tf <archive-filename>
  Extract: tar -xf <archive-filename>
  Create:  tar -cf <archive-filename> [filenames...]
  Help:    tar --help
make: *** [npm_licenses] Error 1

### System information

Darwin X64, nvm version v16.15.0, node v16.15.0, npm version '8.5.5', go version go1.18.1 darwin/amd64

### Prometheus version

```text
Master branch
```

**Comment by Nexucis** [comment]
thanks for reporting this issue.

Even if it looks super bad it's actually more a warning than an error. So the build of the UI still work as expected.
That doesn't mean we shouldn't fix it, it's just less urgent

**Comment by fatelei** [comment]
hmm, the @nexucis directory has no src/index.ts

<img width="545" alt="image" src="https://user-images.githubusercontent.com/961094/169066944-4c6982fc-8f80-4bce-9e62-50209d5c03c3.png">

maybe forget to ship it

**Comment by Nexucis** [comment]
Thanks @fatelei for the link. That was helpful :)

I read the different comments there and I think I will just remove the source map. That actually makes sense to remove it as I don't have the wish to put the source code in the package.
