### ISSUE TITLE
Adding __type__ hidden label to leverage it in metric_relabel_configs

### ISSUE THREAD

**Issue by paologallinaharbur** [prometheus/prometheus#10684]
## Proposal
I would like to add as hidden label `__type__` in addition to `__name__` to be able to leverage it with `metric_relabel_configs`.

**Use case. Why is this important?**

 - It would be possible to take decisions based on the metric type

 -  I am currently sending metrics to a Newrelic endpoint. 
  Since `Remote Write` doe not include the metric type Newrelic asks to add the addition label "newrelic_metric_type" as a workaround . (this is needed if the metric type cannot be inferred from the metric name)
  I would like to add such label to all metrics leveraging `metric_relabel_configs`, however right now I think it is not possible since we do not have access to metadata at that point

---

Is there a different way to attach the metric type as a label to metrics? (I know it is a workaround while waiting for a proper solution)

**Comment by roidelapluie** [comment]
about type, very often you should be able to tell by the name:

_count _sum should be histogram / summary
if there is a le label it's histogram / summary

counters should end with _total

other should be gauge

**Comment by paologallinaharbur** [comment]
Yes, that is the point, Newrelic tries to infer that from the name, but from time to time the "guessed" one is different from the one specified by the metric. Sadly the metric name, most of the times, cannot be changed since it belongs to a third party exporter.


The currently workaround works, but the label is added manually 😢 

Having the type available as an hidden label would allow us to automatically add the type as a label to the metric

**Comment by roidelapluie** [comment]
Prometheus  also sends the full metadata to remote write endpoints, which rewrelic could use.

https://prometheus.io/docs/prometheus/latest/configuration/configuration/#remote_write

**Comment by paologallinaharbur** [comment]
Checking the code I think it would be enough something like:
```
	*l = append(*l, labels.Label{
		Name:  labels.MetricName,
		Value: s[:p.offsets[0]-p.start],
	},
		labels.Label{
			Name:  labels.MetricType,
			Value: string(p.mtype),
		},
	)
```

in the PromParser and the OpenMetricsParser. (adding as well some tests and fixing existing ones 😄 )

**Comment by brian-brazil** [comment]
That's not sufficient, the parser accepts Prometheus text format in any order plus the OM ingestion parser isn't smart enough to know what metric family it is in (and thus what type it might be). The parser is designed for speed, not to be fully featured.

It's also semantically inappropriate to have type as a label, as it is not a dimension, so it only adds clutter and would break downstream usage by adding an unexpected instrumentation label.

If you need this information, you need a fully-featured parser. There's one in Go for the Prometheus text format, and in Python for OpenMetrics.

**Comment by roidelapluie** [comment]
Metadata is not always included in the payload but it's literally designed at usecases like yours.

cc @cstyan any opinion here?

**Comment by paologallinaharbur** [comment]
Thanks for the feedback I really appreciate the responsiveness 😃 

> That's not sufficient, the parser accepts Prometheus text format in any order plus the OM ingestion parser isn't smart enough to know what metric family it is in (and thus what type it might be). The parser is designed for speed, not to be fully featured.

I thought that the type was parsed (if available) into the `mtype` attribute: 
- [here](https://github.com/prometheus/prometheus/blob/78f264578722493dcd8bf25c43bde7865a18792f/model/textparse/openmetricsparse.go#L260) for the OpenMetricsParser
- [here](https://github.com/prometheus/prometheus/blob/78f264578722493dcd8bf25c43bde7865a18792f/model/textparse/promparse.go#L295-L295) for the PromParser. 

That it why I was thinking I could use `mtype   MetricType` to populate the temporary type label in the `Metric(l *labels.Labels) string` method of the two parsers.

In case the type is not available I was thinking to avoid adding such temporary label.

> It's also semantically inappropriate to have type as a label, as it is not a dimension, so it only adds clutter and would break downstream usage by adding an unexpected instrumentation label.

If specified as `__type__ ` it would be discarded automatically after the relabelling similarly to `__name__ `?

**Comment by roidelapluie** [comment]
`__name__` is not discarded, it's the name of the metric.

**Comment by brian-brazil** [comment]
> That it why I was thinking I could use mtype MetricType to populate the temporary type label in the Metric(l *labels.Labels) string method of the two parsers. 

That's only when parsing the TYPE line self, it doesn't apply when parsing any other line.

> Is it way more complex to add it?

For OM it shouldn't be too hard to do it efficiently, as the spec is locked down to make that practical. The problem is as the decision was made that the Prometheus text format can take in lines in a random order, supposedly to make things easier. However that also prevents one-pass constant-ish memory linear time algorithms that we'd need to do it efficiently impossible for parsers. So that kinda scuppers us, as we could see the sample before we see the TYPE line.

> Regarding the "fully-featured parser" did you mean the https://github.com/prometheus/common/expfmt?

Yes, that's the official parser for the Prometheus text format.

**Comment by paologallinaharbur** [comment]
> __name__ is not discarded, it's the name of the metric, which is a regular label.

My bad, I read in the docs "Labels starting with __ will be removed from the label set after target relabeling is completed." and I thought it was applying to all labels and therefore also to `__type__ `. I imagine that it is not enough if I add it at that point 😕 

> The problem is as the decision was made that the Prometheus text format can take in lines in a random order, supposedly to make things easier. [...] as we could see the sample before we see the TYPE line.

I was not aware of this and it looks like a stopper 🤯 We are going to check the code again to see if we come up with some ideas to do that efficiently without assuming that the "type line" is parsed before the sample ones.

**Comment by brian-brazil** [comment]
> I was not aware of this and it looks like a stopper 

What I'd suggest looking at is seeing if you can leverage the various caches in the scrape code to do something smart. Having a more correct parser would be great, if it can be done efficiently. Particularly for checking that OM input is meeting the spec, as there's a common misconception that if Prometheus accepts input that it is valid. In reality Prometheus will currently accept all valid OM/Prometheus text format input, but also some invalid inputs.

**Comment by cstyan** [comment]
> Metadata is not always included in the payload but it's literally designed at usecases like yours.
> 
> cc @cstyan any opinion here?

I would prefer to avoid hacking yet another thing into remote write and just to move forward with the metadata in WAL PR. I will take a more active hand in moving that forward starting this coming week.

**Comment by cstyan** [comment]
@paologallinaharbur let me know if you think the metadata WAL pr and including the metadata alongside each sample rather than as separate messages would not solve your use case. Otherwise I think we can close this in favour of that work.

**Comment by paologallinaharbur** [comment]
Hello, @cstyan yes it would likely solve our usecase. Thanks for the help! 😄
