### ISSUE TITLE
Prometheus returns HTTP 500 "seeker can't seek" error on /favicon.ico

### ISSUE THREAD

**Issue by ricardbejarano** [prometheus/prometheus#10697]
### What did you do?

1. Run Prometheus (I did `docker run -it -p 9090:9090 quay.io/prometheus/prometheus:latest`)
2. Go to http://localhost:9090/favicon.ico

### What did you expect to see?

Prometheus' favicon.

### What did you see instead? Under which circumstances?

A HTTP 500 response with Go's `seeker can't seek` error message.

### System information

Darwin 21.4.0 x86_64

### Prometheus version

```text
prometheus, version 2.35.0 (branch: HEAD, revision: 6656cd29fe6ac92bab91ecec0fe162ef0f187654)
  build user:       root@cf6852b14d68
  build date:       20220421-09:53:42
  go version:       go1.18.1
  platform:         linux/amd64
```

### Logs

_None relevant to the issue (not even with `--log.level=debug`)._

**Comment by fpapadamis** [comment]
This `HTTP 500` on `/favicon.ico` seems to appear only when running Prometheus using docker. I have a `2.35.0` version running as a service and I get `HTTP 200` and the actual image when I'm browsing `/favicon.ico`.

**Comment by mmuth** [comment]
Same issue here

**Comment by Nexucis** [comment]
issue wasn't there in 2.34. I'm looking about what changed between 2.34 and 2.35

**Comment by roidelapluie** [comment]
It's not only in docker, it's when building with promu crossbuild.

**Comment by Nexucis** [comment]
that's weird @roidelapluie. I downloaded the last archive and run the binary and I don't see the issue like @fpapadamis said it too.

**Comment by roidelapluie** [comment]
```
tar xvf prometheus-2.36.1.linux-amd64.tar.gz
cd prometheus-2.36.1.linux-amd64/
./prometheus 
```

then

```
curl 127.0.0.1:9090/favicon.ico
seeker can't seek
```

**Comment by Nexucis** [comment]
```bash
tar xvf prometheus-2.36.1.darwin-amd64.tar.gz
cd prometheus-2.36.1.darwin-amd64/
./prometheus
```

```
curl 127.0.0.1:9090/favicon.ico --output favicon.ico
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 15086  100 15086    0     0   983k      0 --:--:-- --:--:-- --:--:-- 4910k
```

no issue in darwin arch.

Perhaps the issue is more on linux actually

**Comment by roidelapluie** [comment]
My initial thinking: https://github.com/prometheus/common/blob/627089d3a7af73be778847aa577192b937b8d89a/server/static_file_server.go#L21

We need more extensions here. If the extension is not known, go http will seek the file to know the mimetype, which is not possible.

**Comment by roidelapluie** [comment]
https://github.com/prometheus/common/pull/385

**Comment by roidelapluie** [comment]
After some testing, I confirm that prometheus/common#385 fixes the issue.

**Comment by Nexucis** [comment]
cool, thank you @roidelapluie. I commented the PR in order to add more mimeTypes support.

**Comment by ricardbejarano** [comment]
Thank you, folks!

**Comment by DesireWithin** [comment]
Hello everyone, do you notice that alertmanager `0.24.0` have the same issue?
