### ISSUE TITLE
PromQL function day_of_year

### ISSUE THREAD

**Issue by roidelapluie** [prometheus/prometheus#10718]
## Proposal
**Use case. Why is this important?**

We have day of month, day of week, but day_of_year would be handy as well, to complete our date functions.

**Comment by roidelapluie** [comment]
cc @juliusv

**Comment by juliusv** [comment]
Sure, sounds good to me.

**Comment by IvoGoman** [comment]
I would like to take this one.

**Comment by roidelapluie** [comment]
> I would like to take this one.

Sure, have fun :-) :+1+

**Comment by Nexucis** [comment]
Fix with #10720
