### ISSUE TITLE
Query examples page contains outdated metric name

### ISSUE THREAD

**Issue by NorbertHauriel** [prometheus/prometheus#10726]
### What did you do?

Opened the documentation at https://prometheus.io/docs/prometheus/latest/querying/examples/

### What did you expect to see?

Examples using the metric **http_requests_total**  to be valid for the newest Prometheus.

### What did you see instead? Under which circumstances?

It is a non-existing metric because it was renamed to prometheus_http_requests_total, therefore half of the page is outdated for newcomers.

### Prometheus version

```text
Prometheus version 2.35.0
```

**Comment by roidelapluie** [comment]
I am closing this issue as the examples in the page are generic and not tied to Prometheus server itself.
