### ISSUE TITLE
License missing copyright

### ISSUE THREAD

**Issue by USSX-Hares** [prometheus/prometheus#10732]
### What did you do?

The [license file](https://github.com/prometheus/prometheus/blob/main/LICENSE) is missing the copyright notice, there is a template instead:

```
   APPENDIX: How to apply the Apache License to your work.

      To apply the Apache License to your work, attach the following
      boilerplate notice, with the fields enclosed by brackets "[]"
      replaced with your own identifying information. (Don't include
      the brackets!)  The text should be enclosed in the appropriate
      comment syntax for the file format. We also recommend that a
      file or class name and description of purpose be included on the
      same "printed page" as the copyright notice for easier
      identification within third-party archives.

   Copyright [yyyy] [name of copyright owner]
```

### What did you expect to see?

Something like `Copyright 2012-2022 Prometheus Team.`

### What did you see instead? Under which circumstances?

> `Copyright [yyyy] [name of copyright owner]`

### Prometheus version

```text
Branch: `main`
Version: `2.35.0`
```

### Prometheus configuration file

```yaml
N/A
```

### Alertmanager version

```text
N/A
```

### Alertmanager configuration file

```yaml
N/A
```

### Logs

```text
N/A
```

**Comment by dgl** [comment]
The template you see is part of the license text, as an example of how to apply it.

The copyright notices for Prometheus itself can be found at top of source files, for example: https://github.com/prometheus/prometheus/blob/main/cmd/prometheus/main.go in addition per 4(d) of the license there is a NOTICE file: https://github.com/prometheus/prometheus/blob/main/NOTICE
