### ISSUE TITLE
Prepare and cut Prometheus 0.16.0rc1

### ISSUE THREAD

**Issue by juliusv** [prometheus/prometheus#1074]
Follow https://github.com/prometheus/prometheus/wiki/Release-Checklist to prepare a 0.16.0rc1 release.

Currently open PRs that still should go in before the release:
* https://github.com/prometheus/prometheus/pull/1069
* https://github.com/prometheus/prometheus/pull/1073
* https://github.com/prometheus/prometheus/pull/1064 (tentative)
* https://github.com/prometheus/prometheus/pull/1039
* https://github.com/prometheus/prometheus/pull/907 (would be cool, but probably won't happen before the release unless someone feels strongly and takes the time)
* https://github.com/prometheus/prometheus/pull/802 (we should really fix this)

**Comment by beorn7** [comment]
https://github.com/prometheus/prometheus/pull/1075 should definitely go in. Has caused trouble already.

**Comment by fabxc** [comment]
For future reference, there are milestones greatly simplifying this. Created some for 0.16 and 0.17.
