### ISSUE TITLE
Creating remote.Storage twice results in duplicate metrics collector registration

### ISSUE THREAD

**Issue by kvrhdn** [prometheus/prometheus#10779]
### What did you do?

We vendor the `remote.Storage` implementation in Grafana Tempo. If we receive data for a tenant, we create a new `remote.Storage` for that tenant and apply its remote write config. If this fails (because the config happens to be invalid), we will retry creating the `remote.Storage` later resulting in the process panicking.

In this specific case, applying the config failed because `tls_config.ca_file` was invalid.

### What did you expect to see?

The process should not panic when `remote.Storage` is created a second time with the same `prometheus.Registerer`.

If it's not possible to guarantee this, a validate function would also be really nice, this would allows us to fail while the process is still starting.

### What did you see instead? Under which circumstances?

The process panicked with

```
panic: duplicate metrics collector registration attempted

goroutine 270 [running]:
github.com/prometheus/client_golang/prometheus.(*wrappingRegisterer).MustRegister(0xc00108c2a0, {0xc000a15eb0, 0x1, 0x1dc9cb4})
	/drone/src/vendor/github.com/prometheus/client_golang/prometheus/wrap.go:104 +0x151
github.com/prometheus/prometheus/tsdb/wal.NewWatcherMetrics({0x2259ca8, 0xc00108c2a0})
	/drone/src/vendor/github.com/prometheus/prometheus/tsdb/wal/watcher.go:139 +0x374
github.com/prometheus/prometheus/storage/remote.NewWriteStorage({0x223be60, 0xc00043d040}, {0x2259ca8, 0xc00108c2a0}, {0xc000acfb20, 0x1c}, 0xdf8475800, {0x223af00, 0x32cf470})
	/drone/src/vendor/github.com/prometheus/prometheus/storage/remote/write.go:77 +0xa5
github.com/prometheus/prometheus/storage/remote.NewStorage({0x223a940, 0xc0006a4230}, {0x2259ca8, 0xc00108c2a0}, 0x1e6b688, {0xc000acfb20, 0x1c}, 0x0, {0x223af00, 0x32cf470})
	/drone/src/vendor/github.com/prometheus/prometheus/storage/remote/storage.go:75 +0x116
github.com/grafana/tempo/modules/generator/storage.New(0xc000b5cfa0, {0x1dce4fd, 0xd}, {0x2259c78, 0xc0000bca50}, {0x223a940, 0xc0002f7360})
	/drone/src/modules/generator/storage/instance.go:60 +0x4b6
...
```

A minimal test case to reproduce the error:

```go
package modules

import (
	"testing"
	"time"

	"github.com/go-kit/log"
	"github.com/pkg/errors"
	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/common/model"
	"github.com/prometheus/prometheus/scrape"
	"github.com/prometheus/prometheus/storage/remote"
	"github.com/stretchr/testify/assert"
)

func Test(t *testing.T) {
	reg := prometheus.NewRegistry()
	startTimeCallback := func() (int64, error) {
		return int64(model.Latest), nil
	}
	remoteStorage := remote.NewStorage(log.NewNopLogger(), reg, startTimeCallback, "/var/wal", time.Minute, &noopScrapeManager{})
	assert.NoError(t, remoteStorage.Close())

	remoteStorage = remote.NewStorage(log.NewNopLogger(), reg, startTimeCallback, "/var/wal", time.Minute, &noopScrapeManager{})
	assert.NoError(t, remoteStorage.Close())
}

type noopScrapeManager struct{}

func (noop *noopScrapeManager) Get() (*scrape.Manager, error) {
	return nil, errors.New("scrape manager not implemented")
}
```

### Prometheus version

```text
2.34.0-rc.0 (v1.8.2-0.20220228151929-e25a59925555)
```

**Comment by kvrhdn** [comment]
I don't mind contributing a PR to ensure we can create `remote.Storage` twice by calling `Close` in between. Just want to check first if this would be accepted 🙂

**Comment by roidelapluie** [comment]
You could create a new registry each time and register it to the main registry after successful creation.

**Comment by roidelapluie** [comment]
To clarify, this would be accepted.

**Comment by roidelapluie** [comment]
We could look into my solution or yours, I think however it is reasonable to expect a new registerer each time.

**Comment by thoernle** [comment]
Is there any progress? This happens also in [https://github.com/grafana/grafana/issues/68213](https://github.com/grafana/grafana/issues/68213)

**Comment by bboreham** [comment]
Hello from the bug-scrub! Is this still an issue in Tempo?  It looks like Grafana worked round it.

The extra effort involved to change the API is only worth it if there are still cases hitting the problem.

**Comment by kvrhdn** [comment]
We have a workaround in Tempo which entails passing in a temporary registry and only registering the metrics from that registry once creation has been successful. This way we don't register metrics twice if setup failed due to an error later.

I'll link our code in case someone else stumbles on this issue: https://github.com/grafana/tempo/blob/6afedd95e5b94d7f4dcac0175116d305ce4c619e/modules/generator/generator.go#L253-L265

So this isn't causing any issues for Tempo anymore, I'll close the issue.
