### ISSUE TITLE
Add max_retries to remote write queue config

### ISSUE THREAD

**Issue by PhilipGough** [prometheus/prometheus#10785]
## Proposal

Looking at the [docs](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#remote_write) and code for the `queue_config` for `remote_write`, appears the intended behaviour is to retry a recoverable error forever.

Would it be useful to allow the `queue_config` to configure `max_retries` in order to allow the client to give up?
Or is it by design that we want to continue retrying to allow the client to catch up eventually?

**Comment by csmarchbanks** [comment]
Thank you for opening this issue, there is some discussion around this and similar ideas in various issues, for example in https://github.com/prometheus/prometheus/issues/7912. There is also a rather old PR now in https://github.com/prometheus/prometheus/pull/8549 which would add this feature. There was some disagreement at that time as to if we should do this, I think it is worth a topic at the next dev-summit to see if there is still disagreement or not.

**Comment by PhilipGough** [comment]
@csmarchbanks thanks for those links. Even as I was writing the issues I realise that there are tradeoffs to consider here and the answer is non-trivial.

I'm going to go ahead and close this because I don't think it adds any value on top of the info and discussion already in #7912
