### ISSUE TITLE
Build from source command doesn't work

### ISSUE THREAD

**Issue by douglascamata** [prometheus/prometheus#10816]
### What did you do?

Followed the README to install Prometheus from source using: `GO111MODULE=on go install github.com/prometheus/prometheus/cmd/prometheus`

### What did you expect to see?

Prometheus being installed.

### What did you see instead? Under which circumstances?

The following compilation error:

```sh
$ GO111MODULE=on go install github.com/prometheus/prometheus/cmd/prometheus/...
/go/pkg/mod/github.com/prometheus/prometheus@v1.8.2-0.20220308163432-03831554a519/web/ui/doc.go:19:2: missing go.sum entry for module providing package github.com/shurcooL/httpfs/filter (imported by github.com/prometheus/prometheus/web/ui); to add:
        go get github.com/prometheus/prometheus/web/ui@v1.8.2-0.20220308163432-03831554a519
/go/pkg/mod/github.com/prometheus/prometheus@v1.8.2-0.20220308163432-03831554a519/web/ui/doc.go:20:2: missing go.sum entry for module providing package github.com/shurcooL/httpfs/union (imported by github.com/prometheus/prometheus/web/ui); to add:
        go get github.com/prometheus/prometheus/web/ui@v1.8.2-0.20220308163432-03831554a519
/go/pkg/mod/github.com/prometheus/prometheus@v1.8.2-0.20220308163432-03831554a519/web/ui/doc.go:21:2: missing go.sum entry for module providing package github.com/shurcooL/vfsgen (imported by github.com/prometheus/prometheus/web/ui); to add:
        go get github.com/prometheus/prometheus/web/ui@v1.8.2-0.20220308163432-03831554a519
```

### System information

Linux codespaces-787b6c 5.4.0-1074-azure #77~18.04.1-Ubuntu SMP Wed Mar 30 15:36:02 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by fpapadamis** [comment]
Tried to reproduce this behavior in a containerized docker environment.

### What did you do?
1. Used **ubuntu:18.04** image.
2. Installed **Go**.
3. Installed **Nodejs**.
4. Installed **npm**.
5. Executed `GO111MODULE=on /usr/local/go/bin/go install github.com/prometheus/prometheus/cmd/prometheus@latest`.

Same steps were followed using **ubuntu:20.04** image, too.

### What did you expect to see?
Prometheus being installed.

### What did you see instead? Under which circumstances?

> go: downloading github.com/prometheus/prometheus v0.36.0
go: github.com/prometheus/prometheus/cmd/prometheus@latest (in github.com/prometheus/prometheus@v0.36.0):
	The go.mod file for the module providing named packages contains one or
	more replace directives. It must not contain directives that would cause
	it to be interpreted differently than if it were the main module.

**Comment by LeviHarrison** [comment]
Hi there! I was able to get `GO111MODULE=on go install github.com/prometheus/prometheus/cmd/...` to work, but only when executed from the root of the cloned repository. Looking through the history of that bit of the documentation, I found [this conversation](https://github.com/prometheus/prometheus/pull/9098#discussion_r680405199), which confirms the issue. As was pointed [later in that PR](https://github.com/prometheus/prometheus/pull/9098#issuecomment-905336834) by @fhemberger, `make build` is basically the exact same thing, so I think it would make sense to just remove `GO111MODULE=on go install github.com/prometheus/prometheus/cmd/...` as whole, or at least clarify where it has to be run.

cc @juliusv

**Comment by juliusv** [comment]
Yeah, my understanding of Go modules is not current or deep enough to understand this case exactly, but just stating in the README.md right above that `go install` line that it needs to be executed from the checked-out repo's root is probably a decent way to go?

**Comment by LeviHarrison** [comment]
Yeah, sounds good to me.
