### ISSUE TITLE
Document that WAL can still be written after memory-snapshot-on-shutdown

### ISSUE THREAD

**Issue by like-inspur** [prometheus/prometheus#10824]
### What did you do?

I install prometheus with docker and config memory-snapshot-on-shutdown

### What did you expect to see?

The prometheus docs tell me with this config prometheus will reduce the startup time since the memory state can be restored with this snapshot and m-mapped chunks without the need of WAL replay.

https://prometheus.io/docs/prometheus/2.34/feature_flags/#memory-snapshot-on-shutdown

### What did you see instead? Under which circumstances?

I reboot prometheus and found from the log that  prometheus start still need wal relay, and this is not the same as prometheus docs

### System information

Linux 5.10.83 x86_64

### Prometheus version

```text
prometheus, version 2.34.0 (branch: HEAD, revision: 881111fec4332c33094a6fb2680c71fffc427275)
  build user:       root@121ad7ea5487
  build date:       20220315-15:18:00
  go version:       go1.17.8
  platform:         linux/amd64
```

### Prometheus configuration file

```yaml
--enable-feature=memory-snapshot-on-shutdown 
--log.level=debug
```

### Logs

```text
ts=2022-06-08T06:11:26.188Z caller=head.go:493 level=info component=tsdb msg="Replaying on-disk memory mappable chunks if any"
ts=2022-06-08T06:11:26.188Z caller=head.go:500 level=info component=tsdb msg="Chunk snapshot is enabled, replaying from the snapshot"
ts=2022-06-08T06:11:27.222Z caller=head_wal.go:1044 level=info component=tsdb msg="chunk snapshot loaded" dir=/prometheus/chunk_snapshot.004003.0031424512 num_series=136898 duration=1.033069595s
ts=2022-06-08T06:11:27.222Z caller=head.go:514 level=info component=tsdb msg="Chunk snapshot loading time" duration=1.034020665s
ts=2022-06-08T06:11:27.371Z caller=head.go:536 level=info component=tsdb msg="On-disk memory mappable chunks replay completed" duration=148.755762ms
ts=2022-06-08T06:11:27.371Z caller=head.go:542 level=info component=tsdb msg="Replaying WAL, this may take a while"
ts=2022-06-08T06:11:27.400Z caller=head.go:613 level=info component=tsdb msg="WAL segment loaded" segment=4003 maxSegment=4004
ts=2022-06-08T06:11:27.401Z caller=head.go:613 level=info component=tsdb msg="WAL segment loaded" segment=4004 maxSegment=4004
ts=2022-06-08T06:11:27.401Z caller=head.go:619 level=info component=tsdb msg="WAL replay completed" checkpoint_replay_duration=163.422µs wal_replay_duration=29.367864ms total_replay_duration=1.212414046s
ts=2022-06-08T06:11:27.548Z caller=main.go:958 level=info fs_type=EXT4_SUPER_MAGIC
ts=2022-06-08T06:11:27.548Z caller=main.go:961 level=info msg="TSDB started"
```
```

**Comment by bboreham** [comment]
Your complaint is about 29.36 milliseconds?

**Comment by like-inspur** [comment]
yes, there are two questions about this
1.  On large producion environment, wal files are large and wal replay takes a long time
2.  I found without memory-snapshot-on-shutdown config checkpoint and wal replay duration all need long time. is that this config reduce the time of this two phases?

**Comment by mdschmitt** [comment]
Yes, the function of `--enable-feature=memory-snapshot-on-shutdown` is to snapshot the active memory Prometheus had when you shut it down.  It dumps this snapshot to disk as an m-mapped structure.  It still does a WAL replay, but does so by reading in this m-map file instead of fetching up to 2h of metrics by scanning through the disk.  So, the debug output you listed is correct.  Prometheus did a WAL replay and the replay took just under 30 milliseconds because it came from the m-map.

I think this issue can be closed; it seems to be a slight misunderstanding of wording in the docs.

**Comment by roidelapluie** [comment]
The WAL replay takes 30 milliseconds, which means that indeed it is not really "done". Maybe we can indeed clarify the docs or the logs @codesome

**Comment by codesome** [comment]
Somehow I missed this issue. Yes the snapshot does not mean it won't touch the WAL. There could be many reasons why new WAL files came in later without a new snapshot. A docs thing yes.

**Comment by bhanu8824** [comment]
can any one provide the prometheus  values files. or where should i mention this value --enable-feature=memory-snapshot-on-shutdown

**Comment by bboreham** [comment]
@bhanu8824 existing docs are [here](https://github.com/prometheus/prometheus/blob/76775d58f87693b4566c1f0deae8e64c55a0481d/docs/feature_flags.md?plain=1#L41).

**Comment by beorn7** [comment]
Yes, this still needs help. Assigning you. Thank you.

**Comment by bhanu8824** [comment]
Hi team,
I am facing an issue where the Prometheus server pod is consuming high
memory during startup. I found a suggestion in the documentation to use the
--enable-feature=memory-snapshot-on-shutdown flag to help reduce memory
usage. After adding this flag and redeploying, the memory usage initially
decreased as expected. However, after two months, I am again seeing high
memory consumption during startup, with the pod using almost 4GB of memory.
Even after the pod starts successfully, this 4GB of memory is not being
released. Could you help me understand why this is happening?

  server:
    extraFlags:
    - enable-feature=memory-snapshot-on-shutdown


[image: image.png]

**Comment by beorn7** [comment]
Please use the [community channels](https://prometheus.io/community/) to seek support. GH issues are not a good way to ask for support, in particular if they are already closed.
