### ISSUE TITLE
Add various warnings (and maybe even other info) to PromQL evaluation results

### ISSUE THREAD

**Issue by beorn7** [prometheus/prometheus#10839]
_This is meant as an umbrella issues for adding warnings (and possibly non-warning just-informational annotations) to PromQL results. (I failed to find an existing issue.) If parts of this turn out to be more involved, separate issues might be filed for it._

This topic was discussed at the dev summit, as can be seen in [the meeting notes](https://docs.google.com/document/d/11LC3wJcVk00l8w5P3oLQ-m3Y37iom6INAMEu2ZAGIIE/edit?pli=1#heading=h.9dxdqy30r96p). Very generally, there is a long-standing desire to “explain” the results of a PromQL query better. Most commonly, this would affect things that went wrong in a way that isn't an outright error. That's where the term “warning” is coming from. But there are also cases where the explanation isn't even a warning, e.g. performance stats about the evaluation or (relevant with the new histograms) information about the accuracy of a result (based on the resolution of the histograms involved).

The effort has two parts: (1) Providing the plumbing to deliver the warnings (or “annotations” or whatever we call them). (2) Actually issuing warnings/annotations.

### Plumbing

The query API already has a warnings field (only used for remote-read issues so far) and returns stats. What's missing is support in the UI to display warnings and stats, and maybe a notion of “annotations” for valuable information that isn't supposed to flag anything “wrong” so that framing it as a warning would be confusing.

A concern is that the [`promql.Result` type](https://github.com/prometheus/prometheus/blob/e4a09f2b4b4772a886a694eb29a90712d41d63df/promql/value.go#L195-L201) contains the warnings as `storage.Warnings`, presumably because the warnings are currently only used for issues coming from remote-read. With more warnings (or even “annotations”), they will also come from other sources, like the PromQL engine itself, and the `storage.Warnings` type would be misleading.

### Actual warnings/annotations to add

Reasons for warnings expressed in the past include:
- Explain a failed label match (or any label match).
- Warn about technically correct but nonsensical usage (e.g. `quantile(10, foo)`).
- Warn about applying gauge functions to counters or counter function to gauges (based on the naming (`..._total`) or even based on what's stored in the metadata buffer, it would of course be better to have a proper persistent metadata storage).
- Warn about `rate` and similar calculations that fail for a lack of samples covered by the used range.

Some of those are not trivial. E.g. the last point about not enough samples to calculate a rate shouldn't warn if it happens for a “legitimate” reason (e.g. the series ends or starts within the range or even outright before or after the range), but if “simply” extending the range a bit would allow the calculation to succeed, a warning would be helpful. Finding out about that might be costly, so the we might not want those warnings to be “on by default”… (Again, a fully-fledged metadata storage would help, which could know when a series starts or ends and what intended scrape interval it has.)

The new sparse histograms add a whole lot of more opportunities to warn:
- New histogram samples are mixed up with conventional samples.
- Incompatible bucket layouts prevent an aggregation (over time or between different histograms).
- …

**Comment by beorn7** [comment]
#12152 is merged now and a huge leap forward.

We still need to figure out how to warn about `rate` and similar calculations that fail for a lack of samples covered by the used range. (We don't want a huge number of false positives here.)

Also note that rule evaluations have ignored warnings so far, which was probably fine as they only came from remote read. Now that warnings AKA annotations are much more useful for recording rules, we need to log and count the annotations (and maybe even display them in the rules page of the web UI). The starting point is probably the [EngineQueryFunc](https://github.com/prometheus/prometheus/blob/156222cc509d2f234589ba0aac6ae8f673f54a85/rules/manager.go#L196), where we need to extract the annotations from the `res` and return it as an additional return argument.

**Comment by WillSewell** [comment]
Is there any plan to allow users to configure the set of warnings that will be returned?

Our counter metrics do not follow the standard naming conventions (don't end in _total/_sum/_count/_bucket), so we'd ideally like to disable this warning.

**Comment by beorn7** [comment]
The current plan is to keep things simple and therefore to not add knobs to switch individual annotations off and on.

The concept we have followed is to give annotations the "warning" level if they are for sure legitimate. For annotations that might happen for things that are intended, we use the "info" level. The latter is true for the warning about the missing suffix. Those "info" annotations always start with "PromQL info". So you could filter them out based on that.

If that's not satisfying enough, we currently consider to move the "info" annotations under a separate key in the JSON response of the query API. Currently, it's all under "warnings", which is not very intuitive as some of the "warnings" are not "warning" level but "info" level. With that separate key, it would be even easier to display those annotations differently depending on level, and maybe ignore info-level by default and only display them on request.

**Comment by beorn7** [comment]
In different news: Note that OpenMetrics enforces the suffixes. And future versions of Prometheus might be stricter with the metric types (e.g. they could simply disallow applying a `rate` to a non-counter metric), so mid- to long-term, it is recommended to fix your metric names anyway.

**Comment by bboreham** [comment]
Closing as largely implemented.  One part extracted to #14818.

* @WillSewell your point may be addressed by https://github.com/prometheus/prometheus/pull/14327
