### ISSUE TITLE
when resend-delay==evaluation_interval then delay is actually double

### ISSUE THREAD

**Issue by dishonono** [prometheus/prometheus#10844]
### What did you do?

I created a rule group with evaluated every 1m and left the resend-delay as 1m (default)
i added a an alert rule that is firing to the group

### What did you expect to see?

I expected the alerts to be sent to alert manager every minute

### What did you see instead? Under which circumstances?

In practice the alerts are send to alert manager every 2 minutes:
![image](https://user-images.githubusercontent.com/30979046/172839081-5d90851f-7f89-4ccd-9efd-a29ce515a550.png)
(these are the times that notifictions were sent to the alert manager )

I debugged this a bit and found that the issue in function needsSending in alerting.go :
![image](https://user-images.githubusercontent.com/30979046/172839948-38b874cc-d22e-41d1-9df1-6a48ffb3ec47.png)

a.LastSentAt and ts are exacly 60s apart, so the condition is not met, bcause it's not Before
![image](https://user-images.githubusercontent.com/30979046/172840084-8735e61a-1587-4068-b27b-e00a09070cec.png)
If the condtion was !After , it would work as I expected.

My question is if this is a bug or an intended behiviour? personally I think it's a bug.
I found the PR where resend-delay was added: https://github.com/prometheus/prometheus/pull/4538/files
I can open a PR to fix this if you agree it's a bug ....

### System information

Linux 5.10.102.1-microsoft-standard-WSL2 x86_64

### Prometheus version

```text
version=2.36.0, branch=HEAD, revision=d48f381d9a4e68c83283ce5233844807dfdc5ba5
```

### Prometheus configuration file

```yaml
# my global config
global:
  scrape_interval:     5s 
  evaluation_interval: 60s
```

### Alertmanager version

```text
N/A
```

**Comment by dishonono** [comment]
it depends how you interpate this:
# Minimum amount of time to wait before resending an alert to Alertmanager.
# CLI flag: -ruler.resend-delay
[resend_delay: <duration> | default = 1m]

I interpated it as : if an alert was already sent to Alert Manager, dont send another one for a minute
Which in the case of 1 minute evaluation interval, should yield an alert every minute.

**Comment by roidelapluie** [comment]
This is the minimum amount of time, not the maximum. This should not cause any problem to send every 2 minutes as alertmanager will keep the alert firing anyway. Therefore I will close this issue.
