### ISSUE TITLE
Clarify Compatible TLS Ciphers in Documentation

### ISSUE THREAD

**Issue by a-gavin** [prometheus/prometheus#10852]
## Proposal
Clarify the specific ciphers supported by Prometheus in relevant web configuration documentation.

In the following three Prometheus Web config YAML files, the documentation mentions that the compatible Prometheus TLS ciphers come from the available Go TLS package ciphers (which are linked in a comment in each):

- [Prometheus HTTPS and authentication doc](https://github.com/prometheus/prometheus/blob/df1bae051482edd8815b4367ff87e23fab719771/docs/configuration/https.md)
- [Alert Manager HTTPS and authentication doc](https://github.com/prometheus/alertmanager/blob/f958b8be84b870e363f7dafcbeb807b463269a75/docs/https.md)
- [Exporter toolkit Web configuration doc](https://github.com/prometheus/exporter-toolkit/blob/19e732caf179e5deb553a9cb2bb2da983dd0d830/docs/web-configuration.md)

Unfortunately, not all the listed ciphers in the [linked webpage](https://golang.org/pkg/crypto/tls/#pkg-constants) in the documentation are secure or supported by Prometheus. As I found in [this function call](https://github.com/prometheus/exporter-toolkit/blob/b94b2d647d1efe979a909e38914d348189a706ae/web/tls_config.go#L280), only the secure Go ciphers are supported. Thus, if a user were to specify the cipher ``TLS_RSA_WITH_RC4_128_SHA`` it would not be supported in Prometheus given the call to ``tls.CipherSuites()``.

I propose adding clarifying in all three markdown documentation files that only the TLS ciphers returned from ``CipherSuites()`` are supported and not all the ciphers in the Go TLS cipher constants list. I will submit a PR for this shortly.

**Comment by roidelapluie** [comment]
#10903 is merged
