### ISSUE TITLE
Optional remote-storage RPC protocol

### ISSUE THREAD

**Issue by ethe** [prometheus/prometheus#10883]
## Proposal
In current, remote storage hard-coding uses PB over HTTP as protocol, it is the most convenient situation in kinds of usage case. However, I think it does not the most efficient situation, if we consider using it in a good enough network environment. Is it able to support various of transport or protocol, such as Flatbuffers over TCP, allow users to have more choices and select the best way to serialize and transport the data? Is it a good feature to be considered? Hope for you reply, thanks.

**Comment by ethe** [comment]
> This is a complex topic. HTTP has well known mechanisms for authentication, encryption, loadbalancing, routing, etc. Introducing flatbuffers sounds like we wound need to re-invent a lot by ourselves, and it might prevent users to run the remote write targets in many situations as it would need TCP access.
> 
> AFAIK there are some discussions about what the future of remote write will be, but I am not aware of a proposal that would involve flatbuffers.
> 
> Are you hitting any limits with the current remote write solution?

Yes I am, I think we can separate transport and protocol and discuss it alone. In protocol part, PB deserialization is a heavy overhead to lots of remote storage service (including our implementation). For a example, victoria metrics uses costumized PB unmarshal approach a lot rather than import `prompb`, some protocols which support zero copy are able to extremly avoid deserialization overhead. Maybe I can do some code work to show an example that how to integrate an optional flatbuffers serialization, measure how many works we need to do and benchmark it. Do you think it is a good idea to try?

In transport part, I do not have much more complaining, I just think if it also supports pluggable just like thrift, it would be better.

**Comment by roidelapluie** [comment]
cc @bwplotka @tomwilkie WDYT here?

**Comment by beorn7** [comment]
Hello from the bug scrub.

Sorry for the lag in responding. A lot has happened in remote-write land in the meantime.

@bwplotka and @alexgreenbank will craft a response here soon.

**Comment by bwplotka** [comment]
👋🏽 Thanks for this issue. Let's unpack.

Thanks to the [PRW 2.0](https://prometheus.io/docs/specs/remote_write_spec_2_0/) basic [content negotiation](https://prometheus.io/docs/specs/remote_write_spec_2_0/#content-type), there is definitely a room to innovate on different payloads within the same protocol e.g. having flatbuffer or [Arrow](https://github.com/prometheus/prometheus/issues/14342) formats and negotiate that within `Content-Type`.

Anyone is welcome to propose format and benchmark it with the current data-model and clients/receivers to help us make a pragmatic decision for the next minor version of Remote Write. Note that  2.0 introduces interning which [improves resources needed to encode and decode messages (on top of compression ratio)](https://docs.google.com/presentation/d/132Pk1dDXh0LazigEGoY9AYHmWzh4-ntZvPWJ7twV3Oc/edit#slide=id.g2fe2a676c3e_0_2), so I would encourage everyone to test and adopt new version before experimenting with more exotic serialization format.

I'm going to close this issue for now. Feel free to open another discussion / issue for a specific format (e.g. we have [an arrow](https://github.com/prometheus/prometheus/issues/14342)), but ideally only if you want to help us prove that this is worth doing. At this point team does not plan to expand and experiment on protocol changes as we have large portion work to ensure its adoption, storage compatibility for new features like created timestamps and nhcb as well as efficiency of the whole pipeline.
