### ISSUE TITLE
Evaluation rules order of evaluation undefined

### ISSUE THREAD

**Issue by aecolley** [prometheus/prometheus#1088]
It is impossible to use a recorded value in another recorded rule, because the evaluation order is unpredictable. Sometimes, you get the value from the current evaluation, and sometimes you get the result of the previous evaluation. This leads to oddities like dividing this minute's sum1m by last minute's count1m, giving wrong values and the occasional +Inf.

Suggested fix: add a command-line flag to enforce sequential evaluation of rules in the same order as their appearance in the rules file.

This is related to issue 17, but that is about adopting some sophisticated automatic sorting, whereas this bug is about the lack of any basic consistency. I would be unhappy if this wasn't going to be fixed until issue 17 was ready.

**Comment by brian-brazil** [comment]
The agreed solution is to be able to have groups of rules, and that they will be ordered within the group. This still allows use of multiple cores for calculations.

I suspect that #17 will never happen.

**Comment by beorn7** [comment]
Should we create a new issue that describes the preferred approach, and close this and #17 ?
@juliusv What do you think?

**Comment by fabxc** [comment]
:+1:

**Comment by juliusv** [comment]
:+1: Will do.

**Comment by juliusv** [comment]
Superseded by https://github.com/prometheus/prometheus/issues/1095. Closing.
