### ISSUE TITLE
Before relabeling Grid keep flicker

### ISSUE THREAD

**Issue by DesireWithin** [prometheus/prometheus#10894]
### What did you do?

I notice that `before relabeling` grid of the `target` tab keep flicker. 

### What did you expect to see?

When I move mouse on the lables, `before relabeling` grid  should show up

### What did you see instead? Under which circumstances?

Now when I move mouse on the lables, `before relabeling` grid keep flicker.
it's hard to describe,  my browers horizontal and vertical scroll bars keep flicker too. But when I zoom out the web page, the issue maybe gone.

I deploy prometheus in the K8S as a `statefulset`, and the target is discover by `kubernetes_sd_configs endpoint`

I test on firefox, chrome and edge, and on the different computers, same thing happend
I test some prometheus version, here is the result :

- v2.20       good
- v2.34       not good
- v2.36.1    not good
- v2.36.2    not good

Perhaps there are too many `before relabeling` items cause this issue.

### System information

Linux 4.15.0-158-generic x86_64

### Prometheus version

```text
See above
```

### Logs

```text
There are no error logs of prometheus pods
```

**Comment by roidelapluie** [comment]
Thanks for your report. I can reproduce it on  http://prombench.prometheus.io/prometheus-meta/targets

**Comment by Nexucis** [comment]
ah yes, I thought I had fixed this issue, but it seems not. It happens when the `tooltip` is displayed between the cursor and the Grid. The cursor is not on the grid anymore, so the tooltip disappear. And so on ...

**Comment by kaffarell** [comment]
Can we close this one in favor of #11158 ?

**Comment by beorn7** [comment]
Hello from the bug scrub.

Note that Prometheus v3 comes with a new UI. We are pretty sure that this particular issue will not happen there in the same way. Therefore, we are closing this, but if you see the same thing with the new UI, please follow up. /cc @juliusv
