### ISSUE TITLE
UI: Target order not sorted

### ISSUE THREAD

**Issue by josefzahner** [prometheus/prometheus#10896]
### What did you do?

I've just upgraded to 2.36.2. In the Classic UI the order of the targets on the "Status -> Targets" page was sorted, probably based on the Endpoint URL. With the "new" UI, it's not sorted at all in my case. We have groups with over 100 targets, and you find nothing without sorting. Is this a bug or expected behaviour? It was always an issue for me with the new UI and now the classic UI is gone....

### What did you expect to see?

Best option would be to have the header where you can click to sort (asc/desc) one or multiple specific columns. Because if one of the 100 targets is down, you have to scroll and search manually without an option to sort.
However it would be fine for me to just get the sorted output based on endpoint again.

### What did you see instead? Under which circumstances?

Target Output isn't sorted at all.

### Prometheus version

```text
2.36.2
```

### Alertmanager version

```text
0.24.0
```

**Comment by Nexucis** [comment]
> and you find nothing without sorting.

And using the search bar doesn't help you to find your targets ?

**Comment by Nexucis** [comment]
I'm not against the sorting feature, I was just wondering if the search bar could help you while waiting for the fix. Because if you are searching for a specific target and you know a partial name, then the search bar should help you to find it quickly.

**Comment by josefzahner** [comment]
I agree, searching helps a lot, but as human its sometimes easier to scan the list with your eyes. But today it's even with a few targets complicated to find it without using the search bar.

**Comment by srungta** [comment]
Isn't the list of targets already sorted alphabetically by `scrapPool` name? @josefzahner

**Comment by lushaorong** [comment]
Hi,I want to try this work

**Comment by Nexucis** [comment]
sure @lushaorong go ahead :)

**Comment by lushaorong** [comment]
> sure @lushaorong go ahead :)

Shall I refer to Classic UI or add a sort button

**Comment by Nexucis** [comment]
perhaps like suggested in the issue, we could have a sort per column header. So likely you have the sort arrow per column.

**Comment by hazzadous** [comment]
@lushaorong I may have stepped on your toes here, sorry! Happy to collaborate on this as needed.

**Comment by josefzahner** [comment]
@hazzadous I see you made some commits but they are not in the main branch yet. Any ideas why?

**Comment by hazzadous** [comment]
@josefzahner not sure, I saw some reviewer assignments on the PR, but I guess not a high priority. Please feel free to pick up, I don't really have any skin in the game as I don't use prom UI so much.

**Comment by beorn7** [comment]
Hello from the bug scrub.

Note that Prometheus v3 comes with a new UI. Not sure if the new UI has the sorting feature, or if it is even still relevant to ask for. We'll close this, but if a similar need still exists, please file a new issue referring to the new UI. /cc @juliusv
