### ISSUE TITLE
Consider specifying and standardize on a change log tag for Security Bugfixes

### ISSUE THREAD

**Issue by rilehudd** [prometheus/prometheus#10905]
I've seen tags utilize `[Bugfix/Security]` or `[Security/Bugfix]`. But explicitly specifying the tag used would help users more quickly understand the release notes. Maybe this is already being done (based upon the tags I've seen), but without specifying it, its hard to tell if it is always followed and what tags are used or if it just depends on the particular maintainer that is making the release.

Also, if considered, the [release documentation](https://github.com/prometheus/prometheus/blob/main/RELEASE.md) should be updated.

**Comment by rilehudd** [comment]
Seems like this could apply to Node Exporter too (though I don't see any examples of existing security tags like I do in Prometheus).

**Comment by roidelapluie** [comment]
#10988 is merged
