### ISSUE TITLE
Consider warning users that label-propagation optimisations that seem 'trivial' are not done

### ISSUE THREAD

**Issue by ashleydavies** [prometheus/prometheus#10909]
## Proposal

I think it's fair to say developers tend to expect things to be automatically optimised - see any modern compiler or DBMS, and there's generally an assumption that they will spot obvious inefficiencies and fix them for you at 'build' time (whether that's building code or preparing queries for execution) before consuming computational time.

I noticed today that Prometheus doesn't optimise queries along the lines of: `a{b="c"} + d` into the form `a{b="c"} + d{b="c"}`, which can produce very significant (15x for my query, though this presumably differs wildly) performance improvements, and I searched around looking for the rationale for not optimising this, and stumbled upon an old issue (#8053) suggesting this exact optimisation. There's very good reasons enumerated there why this optimisation can't be taken, but I would wager that most users of Prometheus don't realise these use cases exist and would assume the same way I did that there is no need to manually optimise these queries.

As a consequence, I wonder whether it might be worth adding "hints" to the UI warning users that Prometheus doesn't optimise these things? I imagine, for example, if you input a query in the graph view along the lines of:

`a{b="c"} <bin-op> d`

and assuming the query takes more than some fixed time - say, 1s - to execute, then there could be a one-time dismissible warning that you may benefit from including your label selectors on both sides of the query string if you are querying "normal" metrics stored in the TSDB, and not a dynamic remote endpoint that might do something particularly clever with `d`.

**To be clear** -- I totally understand the rationale why this isn't optimised, and I'm not criticising or suggesting that changes! Just suggesting there might be a large volume of users who don't realise this and get bitten by this issue unknowingly on the regular. Perhaps a dynamic detection for these things in the UI isn't the correct path, and emphasising it in the documentation might be better? Very open to discussion here of course and I'm happy to help the implementation if others agree with this!

**Comment by beorn7** [comment]
Hello from the bug scrub.

This kind of optimization wasn't possible in the past for a weird reason, but we want to remove that reason with Prometheus v3, see https://github.com/prometheus/prometheus/issues/13586 . 

We should certainly just do the optimization instead of documenting that it is not done. The former is tracked in https://github.com/prometheus/prometheus/issues/8053 . Closing this one.

**Comment by ashleydavies** [comment]
😄
