### ISSUE TITLE
windows_iis_current_application_pool_up time is incorrect?

### ISSUE THREAD

**Issue by RedEyezCuckoo** [prometheus/prometheus#10920]
### What did you do?

we use windows_exporter-0.18.1-amd64.exe for check iis informations.
when we check
windows_iis_current_application_pool_up / windows_iis_total_application_pool_start_time
in prometheus, we find out metric count in incorrect.

### What did you expect to see?

in performance manager,
Current Application Pool Uptime is 9,147,932.108
( total = Current Application Pool Uptime * app count )
we expect those numbers in prometheus.

### What did you see instead? Under which circumstances?

in promehteus,
fixed number were shown.(like pic below.)
![image](https://user-images.githubusercontent.com/39359964/175902858-aa67f084-0805-4f77-86e4-6e7c75fa5482.png)

### System information

window 2012 R2 Standard

### Prometheus version

```text
prometheus, version 2.36.0 (branch: HEAD, revision: d48f381d9a4e68c83283ce5233844807dfdc5ba5)
  build user:       root@b3126bd1c115
  build date:       20220530-13:56:56
  go version:       go1.18.2
  platform:         linux/amd64
```

**Comment by LeviHarrison** [comment]
I think this issue is with [windows_exporter](https://github.com/prometheus-community/windows_exporter), not Prometheus itself, and I suggest you open an issue over there. Thanks!
