### ISSUE TITLE
Move away from deprecated Azure packages.

### ISSUE THREAD

**Issue by roidelapluie** [prometheus/prometheus#10942]
Azure packages have depreciation notices:

**github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute**
> Please note, this package has been deprecated. A replacement package is available [github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/compute/armcompute](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/compute/armcompute). We strongly encourage you to upgrade to continue receiving updates. See [Migration Guide](https://aka.ms/azsdk/golang/t2/migration) for guidance on upgrading. Refer to our [deprecation policy](https://azure.github.io/azure-sdk/policies_support.html) for more details.

**github.com/Azure/azure-sdk-for-go/services/network/mgmt/2018-10-01/network**
> Please note, this package has been deprecated. A replacement package is available [github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/network/armnetwork](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/network/armnetwork). We strongly encourage you to upgrade to continue receiving updates. See [Migration Guide](https://aka.ms/azsdk/golang/t2/migration) for guidance on upgrading. Refer to our [deprecation policy](https://azure.github.io/azure-sdk/policies_support.html) for more detail

**Comment by asw101** [comment]
+@sandeep-sen for visibility.

**Comment by sandeep-sen** [comment]
@roidelapluie I am part of Azure SDK for Go team, I can help you with the migration to our newer sdks, what is the best way to reach you.

**Comment by sandeep-sen** [comment]
+ @xboxeer for getting onboarding instructions for "track 2" go sdk

**Comment by xboxeer** [comment]
@roidelapluie Thanks for reaching out, the method you mentioned `NewVirtualMachinesClientWithBaseURI` is an old way of using SDK, that requires you provide a resource endpoint to tell SDK what is the current Azure cloud you are working with, in our new SDK, this is can be achieved by the below code
```golang
import {
   "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/compute/armcompute"
}

options := arm.ClientOptions {
    ClientOptions: azcore.ClientOptions {
        Cloud: cloud.AzureChina,
    },
}
client, err := armcompute.NewVirtualMachinesClient("", cred, &options)
```
By using the above code, you don't need to specify the resource endpoint every time when you are creating new resource client

You can refer to this sample for more details of how to operate azure resource using our new sdk: [Create VM using new Azure SDK for golang](https://github.com/Azure-Samples/azure-sdk-for-go-samples/blob/main/sdk/resourcemanager/compute/create_vm/main.go)

**Comment by xboxeer** [comment]
Issue https://github.com/Azure/azure-sdk-for-go/issues/18780 raised to optimize migration guidance to include general pattern difference of using SDK
