### ISSUE TITLE
Add `__meta_kubernetes_service_port_number` in kubernetes_sd_config

### ISSUE THREAD

**Issue by yngwiewang** [prometheus/prometheus#10945]
When using the pod role type, we have `__meta_kubernetes_pod_container_port_name` and `__meta_kubernetes_pod_container_port_number`, but in service role there is only `__meta_kubernetes_service_port_name` and no `__meta_kubernetes_service_port_number`. If the port name is not set or it's difficult to remember the port name, port number will be very convenient. Could I open a PR to add `__meta_kubernetes_service_port_number`？

**Comment by yngwiewang** [comment]
Thanks, @brancz , I will open a PR in a couple of days.
Should I add `__meta_kubernetes_endpoint_port_number` together?
I notice that in endpointslice role, it has `__meta_kubernetes_endpointslice_port` label, maybe we should use a unified label name, `_port` or `port_number`, which one is better?

**Comment by yngwiewang** [comment]
Thanks, @brancz , I'm working on it.

**Comment by roidelapluie** [comment]
#11002 is merged.
