### ISSUE TITLE
Support grouping rules such that rules within a group are executed sequentially

### ISSUE THREAD

**Issue by juliusv** [prometheus/prometheus#1095]
Introduce a mechanism to wrap a set of rules into a group in such a way that all rules within that group are executed sequentially (vs. in parallel). This allows dependent rules to work deterministically.

Historical note: See also discussions on https://github.com/prometheus/prometheus/issues/1088 and https://github.com/prometheus/prometheus/issues/17.

**Comment by brian-brazil** [comment]
As an additional note, we'll also likely want to use such groups to indicate which rules are allowed to access remote storage. Generally remote storage should be avoided for reliability reasons, and only be used for human trending.

**Comment by zxwing** [comment]
Is there any timeline for this feature?

**Comment by fabxc** [comment]
It's not a super-trivial one so it will take a bit. But it's high up on the list of next features to work on.

**Comment by aecolley** [comment]
Are there any thoughts on how these groupings will be expressed syntactically? It occurred to me that it can be inferred automatically by comparing (lhs) rule names+labelsets with (rhs) metric selectors, and grouping all possibly-matching rules together. However, this is a bit automagic, so it's not necessarily the obvious solution.

I'm considering making an unpublished patch to implement this, just to stay on top of mounting technical debt. I would prefer not to diverge too far from whatever plans you have without good reason, so I'm asking what those plans are.

**Comment by juliusv** [comment]
@aecolley That was my initial idea early on, but that isn't as unproblematic as it sounds: https://github.com/prometheus/prometheus/issues/17

**Comment by Gouthamve** [comment]
A proposal for fixing this with backward compatibility is here: https://docs.google.com/document/d/1AgRT1sJyvxwVx6ZLffUKFZ3yYFt01LSz_ohLQbA2yc4/edit

**Comment by brian-brazil** [comment]
Added in 2.0.
