### ISSUE TITLE
High CPU usage when add some metrics

### ISSUE THREAD

**Issue by pytimer** [prometheus/prometheus#10969]
### What did you do?

Use Prometheus monitor a Kubernetes cluster that have 10 nodes, it cpu usage is 2. But when i add some applications and metrics, Prometheus cpu usage increase to 6 cpu. I don't know why. 

Judging by the CPU profiling graph, it looks like most of the CPU is used to tsdb querier select.
[pprof.prometheus.samples.cpu.001.pb.gz](https://github.com/prometheus/prometheus/files/9034050/pprof.prometheus.samples.cpu.001.pb.gz)

![image](https://user-images.githubusercontent.com/17105586/177024144-c45acf18-5059-46d1-88a5-ae47875a7891.png)

### What did you expect to see?

I'm not sure that the CPU usage is expected, i want to  reduce CPU usage via some ways.

### What did you see instead? Under which circumstances?

I see the Prometheus CPU usage increase too much when add some applications and metrics.

### System information

Linux 3.10.0-1062.12.1.el7.x86_64 x86_64

### Prometheus version

```text
prometheus, version 2.12.0 (branch: HEAD, revision: 43acd0e2e93f9f70c49b2267efa0124f1e759e86)
  build user:       root@7a9dbdbe0cc7
  build date:       20190818-13:53:16
  go version:       go1.12.8
```

### Prometheus configuration file

```yaml
Use `prometheus-operator`
```

**Comment by roidelapluie** [comment]
your Prometheus version is from 2019. Please reopen if you can reproduce with a recent version and it's causing issues.
