### ISSUE TITLE
Why we 'CutNewFile' when truncate head chunks?

### ISSUE THREAD

**Issue by t00350320** [prometheus/prometheus#10980]
Here is the case:
1、suppose a head chunk compaction by default 2h range from 12:00-14:00. And we know the real time may reach 15:10, because the compaction need 1.5*range time.
2、If the series comes slowly , let's say from 12:00-15:10, the first head chunk file '001' has not reach 128M( the head chunk default size), so a compaction reads 12:00-14:00 chunks from  file '001' . Concurrently,file '001''s maxtime(~15:10) bigger than 14:00,so it shouldn't be removed  in Truncate().

So, what happens if there is no 'cdm.CutNewFile()'  in above case?  

prometheus\tsdb\chunks\head_chunks.go
func (cdm *ChunkDiskMapper) Truncate(mint int64) error {
xxx
	// Cut a new file only if the current file has some chunks.
	if cdm.curFileSize() > HeadChunkFileHeaderSize {
		// There is a known race condition here because between the check of curFileSize() and the call to CutNewFile()
		// a new file could already be cut, this is acceptable because it will simply result in an empty file which
		// won't do any harm.
		cdm.CutNewFile()
		fmt.Println("CutNewFile####")
	}

**Comment by beorn7** [comment]
Hello from the bug scrub.

Sorry for not responding here earlier.

We are not quite sure what you are shooting for here. Maybe this needs a more interactive conversation between you and a TSDB expert. Would you like to jump onto the  #prometheus-dev channel on CNCF Slack to start a conversation?
