### ISSUE TITLE
Under what circumstances value of 'prometheus_tsdb_head_series' keep growing all the time ?

### ISSUE THREAD

**Issue by iamyeka** [prometheus/prometheus#10982]
I don’t know about remote write but scraped series are all appended to in memory chunks, those are written out to a block file every two hours, then, later, head gc will run and that will prune in memory chunks that don’t receive any updates. So any churn related memory buildup should be reduced after 2 hours. tsdb_head_series should show a drop every two hours as gc runs.

_Originally posted by @prymitive in https://github.com/prometheus/prometheus/issues/10925#issuecomment-1168764298_

**Comment by iamyeka** [comment]
In theory, prometheus_tsdb_head_series would go down every two hours by the flag storage.tsdb.min-block-duration set to 2h by default.
But in my environment, the value keeps growing and the memory usage keeps increasing the same time utils an oom happens.

Prometheus version: v2.21.1
Retention time: 20d

Could somebody help me solve this problem? Any tips will be really appreciated.

**Comment by bwplotka** [comment]
Hi

* Make sure to get latest version of Prometheus, otherwise it's hard for us to help.
* Check if compaction ever happens. It should happen after every 2-3h. 
* Have you waited 2h? It might happen you have so many series that you don't have enough memory (or CPU resource) to survive until next head blockcompaction

**Comment by iamyeka** [comment]
Hi @bwplotka Thanks for reply.

The compaction happened only once when prometheus started.
And the metric prometheus_tsdb_compactions_triggered_total's value is 1 all the time just like the picture shows below.
![image](https://user-images.githubusercontent.com/22488212/177466400-e7fca92a-65fe-4e77-97b5-90cf6c765a05.png)

I try to visit the path /debug/pprof of prometheus. Looks like the goroutine got stuck in the first compaction process.
![image](https://user-images.githubusercontent.com/22488212/177466702-c1cd207e-a519-4b26-b675-3aa2b92abb63.png)

When i attach to the pod, i find the wal dir got a huge size which is not common as well as the chunks_head dir.
![image](https://user-images.githubusercontent.com/22488212/177466897-d6c4304d-b2e5-4f2a-a92e-856dc2db7a08.png)

**Comment by iamyeka** [comment]
In theory, prometheus would print a log like below every two hours after writing a new block.
```
level=info ts=2022-06-16T09:01:41.440Z caller=compact.go:495 component=tsdb msg="write block" mint=1655359200000 maxt=1655366400000 ulid=01G5NVV9Q83B5T86AVFVB2GMA1 duration=1m41.336678503s
```
In fact, the log never printed.

After reading related code, i guess somehow we came across a situation where the condition `if meta.Stats.NumSamples == 0 {` always returns true.
```
func (c *LeveledCompactor) Write(dest string, b BlockReader, mint, maxt int64, parent *BlockMeta) (ulid.ULID, error) {
	start := time.Now()

	uid := ulid.MustNew(ulid.Now(), rand.Reader)

	meta := &BlockMeta{
		ULID:    uid,
		MinTime: mint,
		MaxTime: maxt,
	}
	meta.Compaction.Level = 1
	meta.Compaction.Sources = []ulid.ULID{uid}

	if parent != nil {
		meta.Compaction.Parents = []BlockDesc{
			{ULID: parent.ULID, MinTime: parent.MinTime, MaxTime: parent.MaxTime},
		}
	}

	err := c.write(dest, meta, b)
	if err != nil {
		return uid, err
	}

	if meta.Stats.NumSamples == 0 {
		return ulid.ULID{}, nil
	}

	level.Info(c.logger).Log(
		"msg", "write block",
		"mint", meta.MinTime,
		"maxt", meta.MaxTime,
		"ulid", meta.ULID,
		"duration", time.Since(start),
	)
	return uid, nil
}
```

**Comment by alexgreenbank** [comment]
Hello from the bug scrub.

Closing as the original poster mentions that this is solved. Feel free to re-open if this is not the case.
