### ISSUE TITLE
@prometheus-io/codemirror-promql: When can we give an example of Vue？

### ISSUE THREAD

**Issue by Keep-working-enthusiasm** [prometheus/prometheus#11004]

**Comment by stenwolf** [comment]
this is how i'm using codemirror-promql with vue composition
`<template>
    <div id="editor" class="editor page-panel" />
</template>

<script>

import { PromQLExtension } from 'codemirror-promql';
import { basicSetup } from '@codemirror/basic-setup';
import { EditorState } from '@codemirror/state';
import { EditorView, keymap } from '@codemirror/view';
import { reactive, onMounted } from '@vue/composition-api';

export default {
    name: 'PromQLEditor',
    setup() {
        function enterKey() {
            return keymap.of([{
                key: 'Enter',
                run() { console.log('this is to prevent a new line, and trigger search'); return true; },
            }]);
        }

        onMounted(() => {
            const data = reactive({
                editorState: null,
                editorView: null,
            });
            const promQL = new PromQLExtension();

            data.editorState = EditorState.create({
                extensions: [
                    enterKey(),
                    basicSetup,
                    promQL.asExtension()
                ]
            });

            data.editorView = new EditorView({
                state: data.editorState,
                parent: document.getElementById('editor'),
            });
        });

        return {};
    },
};
</script>

<style lang="scss" scoped>
.editor {
    height: 40px;
    width: 100%;
    margin: 0 25 10;
}
</style>
`

**Comment by a-yuex** [comment]
Expect vue

**Comment by bboreham** [comment]
Hello from the bug-scrub!  Not much context and nothing happened for 2 years, so we'll close this.
Please open a new feature request with full details if required.

**Comment by thislyc** [comment]
@bboreham Hello, I can provide a PR, but where should I put my sample code?

**Comment by bboreham** [comment]
I have no idea what this is about. 
Click on “new issue” and provide full details.
