### ISSUE TITLE
Add username_file in prometheus.yaml configuration

### ISSUE THREAD

**Issue by Mak0tin** [prometheus/prometheus#11007]
When using basic auth, we have password_file to load password credentials, but in username field there is only string option and no “username_file”. 

```bash
# Sets the `Authorization` header on every scrape request with the
# configured username and password.
# password and password_file are mutually exclusive.
basic_auth:
  [ username: <string> ]
  [ password: <secret> ]
  [ password_file: <string> ]
```

Having the option to load the username via file would be very helpful.

If you find it suitable I can work in the PR

**Comment by lushaorong** [comment]
hi,I want to try this work

**Comment by lushaorong** [comment]
plz assign it to me

**Comment by roidelapluie** [comment]
I don't think we should do this. Prometheus only reads secrets from files. Username is not considered a secret.

I am also concerned by the inability to read username and password files atomically.

**Comment by roidelapluie** [comment]
I will close this issue for now based on my previous reply.
