### ISSUE TITLE
codemirror-promql is missing dependency: lezer-promql

### ISSUE THREAD

**Issue by MrDeerly** [prometheus/prometheus#11017]
### What did you do?

Installed `@prometheus-io/codemirror-promql@0.37.0-rc.1` via yarn. Tried to use it and ran into issues.

### What did you expect to see?
It should work without an error.

### What did you see instead? Under which circumstances?

`    Cannot find module '@prometheus-io/lezer-promql' from 'node_modules/@prometheus-io/codemirror-promql/dist/cjs/complete/hybrid.js'
`

While checking the dependencies of `@prometheus-io/codemirror-promql` i noticed that only `lru-cache` is installed.

The issue i see is that in the new publish action / script where `codemirror-promql `is build and published before `lezer-promql` is. Causing `lezer-promql` missing in `codemirror-promql`. You can verify that be checking one of the recent action runs. For example: https://github.com/prometheus/prometheus/runs/7330658186?check_suite_focus=true

Shortened github action output:
```
Run ./scripts/ui_release.sh --publish dry-run
...
...
+ @prometheus-io/codemirror-promql@0.37.0-rc.0
...
...
+ @prometheus-io/lezer-promql@0.37.0-rc.0
```

### Prometheus version

```text
0.37.0-rc.1
```

**Comment by Nexucis** [comment]
mmm I don't think it's because the dependency `@prometheus-io/lezer-promql` isn't installed. Pretty sure if you check in `node_modules/prometheus-io` you should find it.

I bet it's because you are using the commonJS module of codemirror-promql, so you have to tell to use the cjs module of `lezer-promql` because it is not able to do it by itself.
This issue usually happens when you are using `Jest` for example as a test runner.

If you are using Jest, then this config should help you: 

```json
    "moduleNameMapper": {
      "lezer-promql": "<rootDir>/../node_modules/@prometheus-io/lezer-promql/dist/index.cjs"
    }
```

**Comment by MrDeerly** [comment]
> mmm I don't think it's because the dependency `@prometheus-io/lezer-promql` isn't installed. Pretty sure if you check in `node_modules/prometheus-io` you should find it.
> 
> I bet it's because you are using the commonJS module of codemirror-promql, so you have to tell to use the cjs module of `lezer-promql` because it is not able to do it by itself. This issue usually happens when you are using `Jest` for example as a test runner.
> 
> If you are using Jest, then this config should help you:
> 
> ```json
>     "moduleNameMapper": {
>       "lezer-promql": "<rootDir>/../node_modules/@prometheus-io/lezer-promql/dist/index.cjs"
>     }
> ```

Ofc you're right. I totally missed to check the parent folder of the module. Indeed I'm using Jest with cjs which is causing the issue. Thanks for you quick answer, and sorry for the unneeded noise!
