### ISSUE TITLE
Prometheus Mixin Dashboard: add cluster filter variable

### ISSUE THREAD

**Issue by ulikl** [prometheus/prometheus#11027]
## Proposal
**Use case. Why is this important?**

I would like to use the Prometheus Dashboards  from https://github.com/prometheus/prometheus/blob/main/documentation/prometheus-mixin/dashboards.libsonnet against a datasource with metrics from multiple Kubernetes clusters where Prometheus-Operator is deployed.
Here the current filter (job and instance) are not very helpful:

- The jobname is identical over all cluster
- the IPs from instance can also overlap between the cluster, as they are internal pod IPs. And it hard to find out which IP is currently from which cluster.

The kubernetes-mixins Dashboards all have a cluster filters included, which can be hidden for single instance use.

If this too Kubernetes specific, could a generic filter variable be added?

**Comment by alexgreenbank** [comment]
Hello from the bug scrub.

We believe this has been resolved by https://github.com/prometheus/prometheus/pull/13180. Please follow up if this is not the case.
