### ISSUE TITLE
History in expression browser

### ISSUE THREAD

**Issue by fabxc** [prometheus/prometheus#1103]
As suggested by @grobie it would be immensely helpful to go back through previous expressions.

**Comment by grobie** [comment]
Implementation in #1188.

**Comment by applegrain** [comment]
I'll give this one a try! Based on the implementation and discussion in #1188, my plan is to:
- navigate history with shift+j (up), shift+k (down) when the cursor is in the textbox
- store history in localStorage
- add `Clear history` button
- add `Store history in localStorage` check box - If unchecked the history will be stored in session storage

Would be interesting to be able to search your history as well, but I'll have that as a stretch goal for now.
