### ISSUE TITLE
Improve large number readability

### ISSUE THREAD

**Issue by MarkSRobinson** [prometheus/prometheus#11049]
## Proposal

Often I have queries like `foo > 1000000`.  This is hard to read and very easy to make a mistake between 100k, 1M, and 10M.  I would love to have some way formatting large numbers for increased clarity.

Option 1 - digit grouping - eg `1_000_000` or `1.000.000`
Option 2 - engineering SI notation  - eg `1M` or `900k` or `2Ti`

**Comment by shooqie** [comment]
You can do `foo > 10^6` or `foo > 1000 * 1000`

**Comment by MarkSRobinson** [comment]
Absolutely there are some work around but one you move off easy powers of 10.  Let's say I wanted to alert on 90% of 2TiB,  2TiB != 2TB and there is a huge difference between the two.  

My big concern is the readability and maintenance rather than strict compactness.  `0.90 * 2TiB` is clearer than `0.9 * 2 * 1_099_511_627_776` is clearer than `1.979 * 1000 * 1000 * 1000 * 1000` even though they're all equivalent.

A built in function like `pow` would also be pretty good and wouldn't require changing the parsing engine.  So something like `0.9 * parse_number("2Ti")`

**Comment by roidelapluie** [comment]
Indeed this can be done with `0.9*2*2^40`. My concern with introducing a specific function for bytes would be where to draw the line: should we also parse centimeters, milliliters, tons, .. ? I think we can still push this to the user. Note that PromQL expression also support comments with `#` which could help reading queries.

**Comment by francescor** [comment]
yes, please 
several AI tools even already suggest (allucinated suggestions :) to use M, G, Gi... as with https://docs.victoriametrics.com/metricsql/ 
 `K, Ki, M, Mi, G, Gi, T and Ti`....

**Comment by beorn7** [comment]
Grouping with `_` already works (e.g. 1_000_000 is accepted as an input).

WRT prefixes, I'm torn. I would expect many, if not a majority of users, to read `process_resident_memory_bytes > 1G` as "more RSS than 1GiB", but that would be written as `process_resident_memory_bytes > 1Gi`. In contrast `process_resident_memory_bytes > 10^9` vs. `process_resident_memory_bytes > 2^30` or  `process_resident_memory_bytes > 1024 * 1024 * 1024` leaves no doubt.

**Comment by beorn7** [comment]
> several AI tools even already suggest (allucinated suggestions :) to use M, G, Gi... as with https://docs.victoriametrics.com/metricsql/ `K, Ki, M, Mi, G, Gi, T and Ti`....

With all due respect, but this should never be a reason to introduce bad ideas into PromQL.

**Comment by alexgreenbank** [comment]
Hello from the bug scrub.

Discussed during the bug scrub and agreement that we should not add support for `K, Ki, M, Mi, G, Gi, T and Ti` style prefixes/suffixes.

Closing this issue as `_` style grouping already works.
