### ISSUE TITLE
Build fails due to invalid gzip option -k

### ISSUE THREAD

**Issue by mttradebyte** [prometheus/prometheus#11047]
### What did you do?

Attempt to build Prometheus on a CentOS 7 platform

### What did you expect to see?

A successful build. It last worked on version 2.30.3 that I've tested.

### What did you see instead? Under which circumstances?

```
gzip: invalid option -- 'k'
Try `gzip --help' for more information.
>> building binaries
/home/kitchen/recipes/prometheus/tmp-build/bin/promu build --prefix /home/kitchen/recipes/prometheus/tmp-build/src/github.com/prometheus/prometheus
 >   prometheus
# github.com/prometheus/prometheus/web/ui
web/ui/embed.go:21:3: usage: //go:embed pattern...
!! command failed: build -o /home/kitchen/recipes/prometheus/tmp-build/src/github.com/prometheus/prometheus/prometheus -ldflags -X github.com/prometheus/common/version.Version=2.37.0 -X github.com/prometheus/common/version.Revision=b41e0750abf5cc18d8233161560731de05199330 -X github.com/prometheus/common/version.Branch=HEAD -X github.com/prometheus/common/version.BuildUser=kitchen@3460a3706333 -X github.com/prometheus/common/version.BuildDate=20220721-14:47:40  -extldflags '-static' -a -tags netgo,builtinassets github.com/prometheus/prometheus/cmd/prometheus: exit status 2
make: *** [common-build] Error 1
```

This comes from:
```
scripts/compress_assets.sh:find static -type f -exec gzip -fk '{}' \; -print0 | xargs -0 -I % echo %.gz | xargs echo //go:embed >> embed.go
```

It seems when building on CentOS 7, the available gzip version does not include the `-k` option, which causes the build to fail. Builds should not be host dependent, outside of the Go / Node versions.

### System information

CentOS 7

### Prometheus version

```text
2.37.0
```

### Prometheus configuration file

```yaml
N/A
```

### Alertmanager version

```text
N/A
```

### Alertmanager configuration file

```yaml
N/A
```

### Logs

```text
N/A
```

**Comment by mttradebyte** [comment]
Looks like this commit did it https://github.com/prometheus/prometheus/commit/c901ebaf8dd1273de415f8a32617d708c4256683

**Comment by roidelapluie** [comment]
gzip -k is necessary to speedup subsequent build. You could use our own docker image golang-builder to build prometheus or remove it during our build. However, this is a useful feature to have upstream.

**Comment by mttradebyte** [comment]
It may be useful for subsequent builds but for those of us that aren't building these on repeat and are still using a still-supported OS, it makes no sense to force us to move to an entirely new build platform because of an option which isn't available everywhere. It's just as easy to add a check to make it compatible with RHEL 7 based build platforms.

**Comment by roidelapluie** [comment]
Sure, if you want to send a pull request, I'd gladly merge it.

**Comment by mttradebyte** [comment]
Submitted a PR.
