### ISSUE TITLE
Grafana shows wrong values when alerts triggered.

### ISSUE THREAD

**Issue by 605adi** [prometheus/prometheus#11043]
### What did you do?

**Versions:-**
1. Prometheus:v2.26.0
2. Grafana:8.2.4
3. Node-Exporter:v1.1.2

I have created alerts using node-exporter, prometheus and grafana.

Grafana Query used for Disk usage, CPU Usage and Memory Usage :-
1. 
min((node_filesystem_size_bytes{device="/dev/sda1",fstype="ext4",instance="ip",job="node-exporter",mountpoint="/"} - node_filesystem_avail_bytes{device="/dev/sda1",fstype="ext4",instance="ip",job="node-exporter",mountpoint="/"})/ node_filesystem_size_bytes{device="/dev/sda1",fstype="ext4",instance="ip",job="node-exporter",mountpoint="/"})

2.  100 * (1 - avg(rate(node_cpu_seconds_total{mode=“idle”, instance=“custom:port” , job=“node-exporter”}[1m])))

3.  ((node_memory_MemTotal_bytes{instance="ip",job="node-exporter"} - node_memory_MemAvailable_bytes{instance="ip",job="node-exporter"}) / node_memory_MemTotal_bytes{instance="ip",job="node-exporter"}) * 100

when the alerts triggered it sends an alerts but the actual problem is when i compare alerts with GCP or the machine, alerts its shows different values. like in GCP its 45% then in Grafana its 80%.

How to solve this problem Grafana alerts showing wrong values how to get the exact values.

Steps tried:-

Changed scrape_interval to 5s.
changed CPU query
checked prometheus collecting the same data as it shows in Grafana.

### What did you expect to see?

Only issue is with the values .
The value what grafana displays is not accurate .
I want to monitor my system disk, cpu and memory usage and wants to receive alerts on threshold above 70, 80 and 90.
Using node-exporter , prometheus and Grafana . Grafana for creating alerts.

want to receive the exact values from the system. want 100% accuracy.

### What did you see instead? Under which circumstances?

1. Disk usage of my system is 70 then prometheus shows 72.
2. Memory usage of my system is 70 then prometheus shows 75
3. CPU usage of my system is 50 then prometheus shows 60.

Sometimes there is sudden hike reaches upto 90% in Prometheus but actually it didn't went upto 90% in my system

### System information

ubuntu :- 18.04

### Prometheus version

```text
Prometheus:v2.26.0
```

### Prometheus configuration file

```yaml
global:

scrape_interval: 15s

evaluation_interval: 15s

alerting:

alertmanagers:

static_configs:

targets:
rule_files:
scrape_configs:

job_name: "prometheus"static_configs:
targets: [“customip:port”]
```

**Comment by nabillarahmanizhafira** [comment]
Up! Is there anyone who's actually looking for this issue? This is also happened to me
