### ISSUE TITLE
Scrape duration longer than Head Compaction can cause Overlapping Blocks Error

### ISSUE THREAD

**Issue by richardjennings** [prometheus/prometheus#11050]
### What did you do?

Configured a Scrape target that takes several minutes to respond. The metrics include timestamps from the start of the scrape running.

### What did you see instead? Under which circumstances?

If a Head compaction runs and completes whilst the scrape is in progress - when finished the scrape appends data to HEAD that includes a mint that overlaps with the newly created block from Head Compaction. This results in a failure state in which head compaction no longer works failing with the error message ```"compaction failed", "compact head: reloadBlocks blocks: invalid block sequence: block time ranges overlap: [....```

### Prometheus version

```text
2.36.1
```

**Comment by roidelapluie** [comment]
cc @codesome

**Comment by codesome** [comment]
@richardjennings does your scrape target specify timestamps for the metric? If not, several minutes of scrape should not create this issue. Is your scrape scraping samples of nearly 1 hour old?

But what you said is indeed possible. If Prometheus was trying to scrape something that is nearly 1 hour old, it could face this issue. At this point I wonder if we should enable handling of overlapping blocks by default, it is not experimental anymore.

**Comment by richardjennings** [comment]
@codesome yes, the scrape target specified timestamps and those timestamps could be quite old. We changed the way this particular scrape job worked and have not seen the issue since. 

> But what you said is indeed possible. If Prometheus was trying to scrape something that is nearly 1 hour old, it could face this issue. At this point I wonder if we should enable handling of overlapping blocks by default, it is not experimental anymore.

Thank you.

**Comment by alexgreenbank** [comment]
Hello from the bug scrub. Apologies for the delay.

Closing. This should be resolved as Prometheus' default behaviour is by now to accept overlapping blocks. Please follow up if this is not true.
