### ISSUE TITLE
Unable to use a constant record expression in a query comparison

### ISSUE THREAD

**Issue by amccague** [prometheus/prometheus#11059]
### What did you do?

I have a defined record which is a constant like:
```yaml
  - expr: (1-0.99)
    record: error_budget
```

When I query `error_budget` I can see its constant value. Equally if I query `(6 * error_budget)` I see the expected value.

### What did you expect to see?

Records to be returned as if the right hand side of the comparison is resolved.

### What did you see instead? Under which circumstances?

When I query like:
```
errors_per_actions:ratio_rate30m > (6 * error_budget)
```
I get "Empty query result"

However if I replace in line the error_budget value like
```
errors_per_actions:ratio_rate30m > (6 * (1-0.99))
```
Then I get results as I expect.

I'm probably missing something obvious but this looks like something I should be able to do.

### System information

Linux 5.4.156-83.273.amzn2.x86_64 x86_64

### Prometheus version

```text
prometheus, version 2.36.1 (branch: HEAD, revision: 3c0a100dec2950f23e91f7efbf8867750960807d)
  build user:       root@e59c79158868
  build date:       20220609-15:25:21
  go version:       go1.18.3
  platform:         linux/amd64
```

**Comment by prymitive** [comment]
https://prometheus.io/docs/prometheus/latest/querying/operators/#vector-matching

Matching `metric > number` works differently than `metric > metric`.
`metric > metric` only works if both sides had same set of labels.

In your case, since you seem to have a single global `error_budget` metric, you can use empty `on` clause (`on ()`) to force comparison, something like `errors_per_actions:ratio_rate30m > on() (6 * error_budget)`

**Comment by amccague** [comment]
> https://prometheus.io/docs/prometheus/latest/querying/operators/#vector-matching
> 
> Matching `metric > number` works differently than `metric > metric`. `metric > metric` only works if both sides had same set of labels.
> 
> In your case, since you seem to have a single global `error_budget` metric, you can use empty `on` clause (`on ()`) to force comparison, something like `errors_per_actions:ratio_rate30m > on() (6 * error_budget)`

Ah of course, I was missing something obvious.
Also a good hint to use a more scoped name or seek to lookup by labels. Thanks!
