### ISSUE TITLE
monitor on prem database - where prometheus is on K8 cluster

### ISSUE THREAD

**Issue by varunmuthu30** [prometheus/prometheus#11055]
## Proposal
**Use case. Why is this important?**

*“Nice to have” is not a good use case. :)*

**Comment by varunmuthu30** [comment]
We are configuring it to have a central repository for monitoring, as we have different flavors of databases

**Comment by alexgreenbank** [comment]
Hello from the bug scrub.

Closing as this is an old issue with no specifics.
