### ISSUE TITLE
Error: read series: invalid size

### ISSUE THREAD

**Issue by mccricardo** [prometheus/prometheus#11063]
### What did you do?

Upgrade Prometheus from 2.33.5 to 2.36.1 in our AKS cluster using the kube-prometheus-stack chart 38.0.0, persisting using Azure File Shares (azurefile-csi PVC).

### What did you expect to see?

No errors.

### What did you see instead? Under which circumstances?

After some time, we started receiving several errors like the following.

<img width="1761" alt="Screenshot 2022-07-25 at 14 19 15" src="https://user-images.githubusercontent.com/1016505/181039732-c052e13a-3bd1-4f38-9057-867fe11645f3.png">

### System information

Linux 5.4.0-1069-azure x86_64

### Prometheus version

```text
prometheus, version 2.37.0 (branch: HEAD, revision: b41e0750abf5cc18d8233161560731de05199330)
  build user:       root@0ebb6827e27f
  build date:       20220714-15:13:18
  go version:       go1.18.4
  platform:         linux/amd64
```

### Logs

```text
ts=2022-07-26T14:58:40.749Z caller=manager.go:636 level=warn component="rule manager" file=/etc/prometheus/rules/prometheus-kube-prometheus-stack-prometheus-rulefiles-0/monitoring-prometheus-uptime-slo-ee26c4f1-ad5d-401f-9275-ca9763117fb5.yaml group=sloth-slo-sli-recordings-prometheus-99_uptime name=slo:sli_error:ratio_rate3d index=6 msg="Evaluating rule failed" rule="record: slo:sli_error:ratio_rate3d\nexpr: (sum(avg_over_time(prometheus:slo:downtime[3d]))) / (sum(avg_over_time(prometheus:slo:all[3d])))\nlabels:\n  sloth_id: prometheus-99_uptime\n  sloth_service: prometheus\n  sloth_slo: 99_uptime\n  sloth_window: 3d\n  team: monitoring\n" err="expanding series: get series 9356433: block: 01G8X9FG8KJX96B9CZY6936ETN: read series: invalid size"
```

**Comment by mccricardo** [comment]
Could be related to #10679.

**Comment by LeviHarrison** [comment]
Yup, it looks like the same issue, and the same conclusion:

> We document explicitly that NFS is not supported, even if posix compliant. This is the current state, and I don't think we have people involved to make this work at the moment.
