### ISSUE TITLE
[Broken Link in Documentation] tsdb README external link.

### ISSUE THREAD

**Issue by alpaylan** [prometheus/prometheus#11069]
### What did you do?

In the tsdb [README](https://github.com/prometheus/prometheus/tree/v0.37.0/tsdb), I tried to check the external resources.

### What did you see instead? Under which circumstances?

`A writeup of the original design can be found [here](https://fabxc.org/blog/2017-04-10-writing-a-tsdb/).`

The link in this line is broken.

**Comment by LeviHarrison** [comment]
Nice catch, thanks for reporting. I guess the site is either down or doesn't exist anymore?

**Comment by juliusv** [comment]
@fabxc will know why :)

**Comment by RichiH** [comment]
I poked him by email to see if he has time, nerves, and motivation to fix his site.

If not, we can point to https://web.archive.org/web/20210803115658/https://fabxc.org/tsdb/ instead.
