### ISSUE TITLE
prometheus container_network_transmit_bytes_total != aws monitoring "network out (bytes)"

### ISSUE THREAD

**Issue by Ben-Mark** [prometheus/prometheus#11076]
### What did you do?

I'm trying to get a basic result of how many bytes were sent from a single machine (AWS EC2)
I have an eks with a single ec2 node, with prometheus installed via helm (official release chart..)

I ran the below promQL
`sum(rate(container_network_transmit_bytes_total[1h]))`

and tried to see if I get the same result in aws ec2 monitoring metrics
network out (bytes)   sum of every 1 second  in 1 hour interval

I see completely different numbers

### What did you expect to see?

I expected to see the same numbers

### What did you see instead? Under which circumstances?

I have 1 single VM in my aws region 
I am trying to validate prometheus metrics with AWS monitoring metrics

prometheus is giving me x2 of what ec2 monitoring metrics are showing
For example:
AWS ec2 monitoring says, sum of 1 second in a 1 hour interval == 1mb sent
prometheus sum of 1 second in a 1 hour interval == 2mb sent 
 given by this query `sum(rate(container_network_transmit_bytes_total[1h]))`

I also tried to subtract and combine the result of `sum(rate(node_network_transmit_bytes_total[1h]))`

What am I doing wrong?
Is this a bug?

this also applies for Average , completely different numbers

Need help guys

### System information

Amazon linux 2  t3.xlarge

### Prometheus version

```text
15.10.5
```

### Prometheus configuration file

```yaml
the official prometheus helm chart
deployed in my eks cluster
```

### Alertmanager version

```text
not relevant
```

### Alertmanager configuration file

```yaml
not relevant
```

### Logs

```text
not relevant
```

**Comment by mozai** [comment]
I'm seeing the same thing, only 10x the pods on a machine means 30x the sum of network traffic.  I think the problem isn't in Prometheus but something odd/misunderstood in cadvisor.

`sum by (instance, pod) (rate(container_network_transmit_bytes_total{instance=~"ip-10-179-73-87.ec2.internal", pod=""}[5m]))` shows a graph between 19MB/s and 25MB/s

`sum by(kubernetes_node) (rate(node_network_transmit_bytes_total{kubernetes_node=~"ip-10-179-73-87.ec2.internal"}[5m]))`  shows a graph between 19MB/s and 25MB/s, with an acceptable margin-of-error difference -- I'd accept they're the same.

Notice the first query I asked for `pod=""` so cadvisor metrics assocated with NO pod and thus NO container!  When I ask for the per-pod metrics, I'd expect to see something that would sum-up to node_network_transmit_bytes but instead

`sum by (instance, pod) (rate(container_network_transmit_bytes_total{instance=~"ip-10-179-73-87.ec2.internal", pod!=""}[5m]))` shows me almost every (but not every) pod on the machine is using between 1MB/s and 25MB/s .  If I were to `sum by (instance)` that number would be 30x what the node_network_transmit_bytes reports is sent out by that instance.

I don't know the answer but after two hours this is the first mention I've seen of the trouble I'm having, so I'm leaving a comment.
