### ISSUE TITLE
Ability to disable remote write retries

### ISSUE THREAD

**Issue by jakubgs** [prometheus/prometheus#11089]
## Proposal

According to discussion in this issue for Cortex storage backend:

>This(`out of order sample` errors) happens when Prometheus sends old samples for series, for which Cortex already has newer samples. __Cortex can only ingest samples for the series in order.__ On restart, Prometheus tries to push all data from its WAL to remote write. __It doesn't remember how much it has pushed before the restart.__

* https://github.com/cortexproject/cortex/issues/3411

Based on that information it would make sense to entirely disable retries for remote write when using Cortex as a storage backend.

I tried setting `min_backoff` to a very low value, but that means that it still attempts to send old samples at least once, generating lots of unnecessary failed push requests to Cortex distributors:
```
ts=2022-08-02T12:21:24.110Z
caller=dedupe.go:112
component=remote
level=error
remote_name=dist-01
url=http://10.10.10.10:9092/api/v1/push
msg="non-recoverable error"
count=1000
exemplarCount=0 
err="server returned HTTP status 400 Bad Request: user=fake: err: out of order sample.
```
My understanding is that these retries are pointless if Cortex just ignores them, and they just generate unnecessary churn.

**Comment by jakubgs** [comment]
I see there was once a `max_retries` option which I guess could have done this if set to 0, but not sure:

* https://github.com/prometheus/prometheus/pull/5649

But anyway, I do think this would be a useful feature, as in case of Cortex storage backend the retries just cause rejections:

![image](https://user-images.githubusercontent.com/2212681/182577102-7c6e5a07-fe79-467b-a546-2bad1940a410.png)

Which just generates pointless bandwidth, CPU, and memory usage.

**Comment by earthgecko** [comment]
It would be handy to have something like this in the `remote_write`
```
# Configure whether HTTP status codes are retried
# [ do_not_retry_on_http: [<stutus_code>, ..., <stutus_code>]]
do_not_retry_on_http: [401, 403]
```

**Comment by bboreham** [comment]
If the context is replay of WAL after a restart of Prometheus, then these are not "retries" as the word is used in the remote-write code.

You may find the `sample_age_limit` config added in #13002 is helpful to reduce the amount of noise from a restart after a long outage.

If you don't agree, please provide more context.

> do_not_retry_on_http: [401, 403]

These are already not retried.

**Comment by jakubgs** [comment]
Oh, I wasn't aware of this pr.
```yaml
  # If set, any sample that is older than sample_age_limit
  # will not be sent to the remote storage. The default value is 0s,
  # which means that all samples are sent.
  [ sample_age_limit: <duration> | default = 0s ]
```
>This useful when recovering from network outages in the case of the used remote write storage rejects samples that are too old.

That's a very good addition, thank you for pointing it out. I'm closing this.
