### ISSUE TITLE
failed to compile the file web/ui/asssets_embed.go

### ISSUE THREAD

**Issue by baoguangya** [prometheus/prometheus#11113]
### What did you do?

run make common-build

### What did you expect to see?

the building should success

### What did you see instead? Under which circumstances?

the building failed

### System information

linux 3.10
go version go1.18.4 linux/amd64

### Prometheus version

```text
prometheus, version 2.37.0 (branch: non-git, revision: non-git)
  build user:       root@localhost.localdomain
  build date:       20220804-18:06:43
  go version:       go1.18.4
  platform:         linux/amd64
```

### Logs

[root@localhost prometheus-2.37.0]# make common-build
\>\> building binaries
/root/go/bin/promu build --prefix /root/prometheus-2.37.0 
 \>   prometheus
\# github.com/prometheus/prometheus/web/ui
web/ui/assets_embed.go:25:33: undefined: EmbedFS
!! command failed: build -o /root/prometheus-2.37.0/prometheus -ldflags -X github.com/prometheus/common/version.Version=2.37.0 -X github.com/prometheus/common/version.Revision=non-git -X github.com/prometheus/common/version.Branch=non-git -X github.com/prometheus/common/version.BuildUser=root@localhost.localdomain -X github.com/prometheus/common/version.BuildDate=20220804-19:41:10  -extldflags '-static' -a -tags netgo,builtinassets github.com/prometheus/prometheus/cmd/prometheus: exit status 2
make: *** [common-build] Error 1

**Comment by baoguangya** [comment]
The variable EmbedFS ought to be assets.EmbedFS

**Comment by roidelapluie** [comment]
Please provide your full build log and go version.

**Comment by baoguangya** [comment]
Sorry, it's because I skipped make assets-compress.
