### ISSUE TITLE
Unclear what is the order of rules for write_relabel_configs

### ISSUE THREAD

**Issue by nosalan** [prometheus/prometheus#11120]
### What did you do?

I tried limit number of metrics sent via remote_write. As per documentation of [remote_write](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#remote_write) pointing to [relabel_config](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#relabel_config) one can define multiple rules e.g. `drop` and `keep`. Unfortunately it is unclear in which order the rules are executed. Given `drop` and `keep` rules that affect the same label it is unclear which rule wins. For example in the case below I would expect that first rule drops everything and next rules allow specific labels but it is not working and I don't know if this is due to the fact that that `drop` rule wins or due to the wrong order of rules.

      write_relabel_configs:
        - source_labels: ['__name__']
          regex: '.+'
          action: 'drop'
        - source_labels: ['__name__']
          regex: 'container_cpu_usage_seconds_total'
          action: 'keep'

### What did you expect to see?

The documentation should be clear about what happens when there are multiple rules with different kinds and which wins. Additionally, I think the most common use case is that everything is blocked and then specific metrics are allowed and it would be nice to have such example in the documentation.

### What did you see instead? Under which circumstances?

It is unclear what is the Prometheus behavior in case of multiple relabel rules affecting same target.

### Prometheus version

```text
version=2.31.1, branch=HEAD, revision=411021ada9ab41095923
```

**Comment by roidelapluie** [comment]
The rules are a list, I think it is clear that they are executed sequentially, from top to bottom. The kind of rule is not important and does not affect order. Only the position in the list matters.

**Comment by nosalan** [comment]
@roidelapluie Thanks for clarification. Then, all metrics except `container_cpu_usage_seconds_total` should be dropped in my case, but the actual behavior is that everything is dropped anyway.

**Comment by roidelapluie** [comment]
```
    - source_labels: ['__name__']
      regex: '.+'
      action: 'drop'
```
After this rule, everything is dropped.


You just need the second rule:

```
    - source_labels: ['__name__']
      regex: 'container_cpu_usage_seconds_total'
      action: 'keep'
```

**Comment by nosalan** [comment]
Yeah, that's correct. Only the second rule is sufficient. Thanks.
