### ISSUE TITLE
Support non-cardinal labels (a.k.a. metric baggage, non-dimensional labels)

### ISSUE THREAD

**Issue by ringerc** [prometheus/prometheus#11132]
## Proposal

Management of cardinality is a constant issue in Prometheus.

Since [prometheus has decided never to support non-string metric values](https://github.com/prometheus/prometheus/issues/2227), **users routinely attempt to associate non-numeric data with a specific time-series by (ab)using time-series labels**. This results in difficult-to-analyse disjoint time-series, unexpected cardinality explosions, excessive memory consumption, etc.

I propose that Prometheus **define a way to mark a given label as *non-cardinal*,** such that

* The label name and value will be stored in the tsdb; but
* The label will be *not be included* in tsdb indexes for the metric;
* Only the cardinal labels will be considered for determining metric time-series uniqueness, the label and value are ignored are not considered to define new dimensions of a metric;
* The label will not be included when querying Prometheus to enumerate distinct time-series via the REST APIs;
* The labels *will* be included in payloads when fetching values for a time-series

Relational database "covering indexes" provide a long-standing precedent for this functionality; see e.g. [postgres's `INCLUDE (y)` clause for `CREATE INDEX`](https://www.postgresql.org/docs/current/indexes-index-only-scans.html).

For backwards-compatibility with existing tools, this should probably be implemented by defining a well-known label prefix, much like prom does for the virtual labels it exposes in recording rules, remote write label rewrite rules, etc.

### Use case: side-band message on health checks

Extremely common case. You have a health check endpoint with an associated message. You want to be able to see the message in your metrics platform, which uses Prometheus and the Prometheus metrics format.

E.g. the series

```
t=15 health[svc=foo,message="healthy"]                        0
t=16 health[svc=foo,message="warning: something is wrong"]    1
t=17 health[svc=foo,message="error: service on fire"]         2
```

The user typically expects this to mean one time-series "health[svc=foo]" with a metric-value and a side-band payload or baggage value "message". But Prometheus and tools actually see

```
t=15 health[svc=foo,message="healthy"]                        0

t=15 health[svc=foo,message="healthy"]                        [NO DATA FOR TIMESERIES]
t=16 health[svc=foo,message="warning: something is wrong"]    1

t=15 health[svc=foo,message="healthy"]                        [NO DATA FOR TIMESERIES]
t=16 health[svc=foo,message="warning: something is wrong"]    [NO DATA FOR TIMESERIES]
t=17 health[svc=foo,message="error: service on fire"]         2

```

If the `message` varies a lot, including identifiers or timestamps, etc, this can cause a cardinality explosion, massive memory consumption etc.

Tools that query for `health` metrics will be confused unless specifically configured to ignore the `message` label.

With my proposal, we would instead use something like:

```
t=15 health[svc=foo,__include_message="healthy"]                        0
t=16 health[svc=foo,__include_message="warning: something is wrong"]    1
t=17 health[svc=foo,__include_message="error: service on fire"]         2
```

Prom and TSDB would store these as in the timeseries `health[svc=foo]` *ignoring the value of `__include_message` for the purpose of identifying timeseries uniqueness in a scrape, indexing, etc, limiting memory use and search costs.

### Use case: string payloads

While Prometheus is designed to only carry numeric metrics, the reality is that not everything can be represented as a single float64.

It's common for users to abuse labels to try to create string-valued "metrics" to propagate desired information for access via Prometheus federation, Prometheus-consuming tools like Grafana, etc. For example:

* An application status field is a series of well-defined strings and user doesn't want to hardcode a string-to-int enumeration in their metrics endpoint then maintain a matching int-to-string mapping in their metrics dashboards/consumers etc (there are hacks that carry the mapping in the metric description, but, ick);
* Attempts to bypass high-numbers-of-labels cardinality issues by using labels with json blobs or key/value pair strings
* ... you name it, you've probably seen it in the wild

A common antipattern is using a label to carry the real data, with a dummy unused value, e.g.

```
my_service_readiness=[readiness="starting"] 0
my_service_readiness=[readiness="initializing buttons"] 0
my_service_readiness=[readiness="loading whatsits"] 0
my_service_readiness=[readiness="rounding cubes"] 0
my_service_readiness=[readiness="adding k to every word"] 0
my_service_readiness=[readiness="ready I hope"] 0
```

This is again a pain to work with in common tooling and causes storage and memory issues in prom.

Since [prom won't support string-valued metrics](https://github.com/prometheus/prometheus/issues/2227), being able to tell prom that these are non-cardinal labels would be a huge help for such use cases.

## Alternative spelling

In the above I used a label prefix `__include_` to mean "include, but do not index", akin to postgres's `INCLUDE (cols)` for covering indexes.

An alternative spelling would be a separate comma-separated list of metrics keys to treat as non-cardinal (or possibly a negated set for "only treat these labels as cardinal, everything else is non-cardinal"). This might be friendlier to tooling, since it would not impose constraints on metrics naming.

E.g.

```

t=15 health[svc=foo,__non_cardinal="message",message="healthy"]                        0
t=16 health[svc=foo,__non_cardinal="message",message="warning: something is wrong"]    1
t=17 health[svc=foo,__non_cardinal="message",message="error: service on fire"]         2
```

**Comment by ringerc** [comment]
### **Not** a use case: top-N sampling

Prometheus struggles with use cases where the number of distinct values for a label are very high but only the top-N for some value are of interest.

Consider monitoring of some table health metric for a relational database system. Users may have 1 table or 100,000 tables. You are not interested in all tables. But a single "max(x)" for the worst value for the health metric across all tables is generally inadequate and unhelpful. What you want is to capture and forward some top-N set of health metrics for a subset of tables.

Prometheus presently struggles with this because each time entries enter or leave the top-N set between scrapes that adds new cardinal values. If there is a lot of churn the usual performance and memory problems arise.

This is true whether the application metrics endpoint generates top-N style metrics with a varying set of labels or whether the whole dataset is scraped then reduced with recording rules before forwarding to a federated endpoint etc.

Non-cardinal labels won't help here, because you want to keep track of distinct values for different table names. You just want Prometheus to gracefully handle these sparse time-series that come and go over time.

There doesn't seem to be a good way to do this in Prometheus; there would need to be a way to efficiently represent "top-N" buckets for a metric **with associated labels** in TSDB directly.

So I'm explicitly excluding this use case from the non-cardinal labels proposal.

**Comment by beorn7** [comment]
Hello from the bug scrub!

This is certainly a bigger effort to tackle. It is pretty much one of the use cases discussed in the whole metadata effort currently ongoing. See https://docs.google.com/document/d/1epBslSSwRO2do4armx40fruStJy_PS6thROnPeDifz8/edit#heading=h.5sybau7waq2q for a recent design doc draft. @aknuds1 @codesome maybe you could verify that the use case in this issues is included in your considerations? And respectively, @ringerc , feel free to comment on the design doc if you don't see your use case modeled.

In any case, due to the scope of this, we eventually want a proper proposal in https://github.com/prometheus/proposals  .  

As these aspects will be tracked in the above mentioned design doc draft and later in the "proper" design doc in the proposals repo, we are closing this issue.

**Comment by ringerc** [comment]
The pick-the-newest-sample conflict-resolution logic proposed in https://github.com/prometheus/prometheus/pull/14495 would partially solve the issue described here, if it was possible to extract it for use outside the proposed `info()` function.

Consider the example in in this issue's description. If we had some function `latest_by(series, "key_labels")` that returned the datapoint and full set of associated labels for the series with the newest datapoint in `series` when grouped by comma-separated label list `key_labels`, then consuming enumeration metrics would look like this:

```
latest_by(health, "svc")
```

and for the input given in this issue's description would produce the desired output at each of the time points by:

* finding all series satisfying `{__name__="health"}`
* grouping by cardinal label(s) `svc`
* for each group, finding the series with the newest datapoint timestamp and returning that series
