### ISSUE TITLE
Added http_sd_config support for rules

### ISSUE THREAD

**Issue by shenzgang** [prometheus/prometheus#11137]
The application program and Prometheus are decoupled. The application program can dynamically modify the alarm rule configuration. Otherwise, I have to manually modify the local file to update the alarm rule information.

**Comment by roidelapluie** [comment]
Rules configuration should ideally be present all the time, even if targets are not available. Having them so dynamic would produce a lot of reloads for which the code is not optimized for at the moment.

We have an agreement to try out some API's on top of the rules to load/unload rules, but not much work as been done at this point. However, this would be better tracked in a dedicated github issue.
