### ISSUE TITLE
AWS EC2 Service Discovery with regional endpoints fails

### ISSUE THREAD

**Issue by Kardi5** [prometheus/prometheus#11139]
### What did you do?

We are running prometheus in an AWS EKS cluster via the prometheus-community Helm chart for prometheus.
From https://github.com/prometheus-community/helm-charts/releases/tag/prometheus-15.12.0
with Prometheus Version: v2.37.0 (patched)

Configure Service Account in Helm chart config:
```
serviceAccounts:
  server:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::ACC_NR:role/ROLE_NAME
```
which is correctly reflected by environment variables

Configure prometheus.yml scrape config (see below)

Use AWS with regional endpoints (EC2, STS, etc): https://docs.aws.amazon.com/general/latest/gr/rande.html

### What did you expect to see?

See all running EC2 instances in the current account

### What did you see instead? Under which circumstances?

Error from debug log of prometheus:

```
ts=2022-08-10T09:41:22.740Z caller=ec2.go:229 level=debug component="discovery manager scrape" discovery=ec2 msg="Unable to describe availability zones" err="WebIdentityErr: failed to retrieve credentials
caused by: SerializationError: failed to unmarshal error message
status code: 400, request id: xxxxxxxxxxxx
caused by: UnmarshalError: failed to unmarshal error message
-- I removed the HEX dump and formatted the output
<?xml version="1.0" encoding="UTF-8"?>
  <Response>
    <Errors>
      <Error>
        <Code>NoSuchVersion</Code>
        <Message>The requested version (2011-06-15) of service AmazonEC2 does not exist</Message>
      </Error>
    </Errors>
    <RequestID>xxxxxxxxxxxx</RequestID>
</Response>

caused by: unknown error response tag, {{ Response} []}"
```

I read somewhere that regional endpoints might have a reduced API version spectrum. So maybe this is it? 

If I remove the `endpoint: "ec2.eu-central-1.amazonaws.com"` from the Prometheus config no messages are logged but also no EC2 servers appear in Prometheus.

### System information

Linux 5.4.129-63.229.amzn2.x86_64

### Prometheus version

```text
version=2.37.0, branch=HEAD, revision=b41e0750abf5cc18d8233161560731de05199330
go=go1.18.4, user=root@0ebb6827e27f, date=20220714-15:13:18
```

### Prometheus configuration file

```yaml
[...]
  - job_name: "node-exporter"
    tls_config:
      insecure_skip_verify: True
    metrics_path: /node-exporter/metrics
    scheme: https
    ec2_sd_configs:
      - region: eu-central-1
        port: 8443
        endpoint: "ec2.eu-central-1.amazonaws.com"
    relabel_configs:
      - source_labels: ['__meta_ec2_tag_Fqdn']
        target_label: 'instance'
[...]
```
```


### Alertmanager version

_No response_

### Alertmanager configuration file

_No response_

### Logs

_No response_

**Comment by beorn7** [comment]
Hello from the bug scrub!

As nothing has been moving here in the last two years, we assume this isn't an issue anymore. If it still is an issue with the current Prometheus release, please follow up and we'll reopen.
