### ISSUE TITLE
Reuse string on TSDB labels set

### ISSUE THREAD

**Issue by alanprot** [prometheus/prometheus#11133]
## Proposal
Hi All,

Have we already though about "string interning" on the TSDB labels ([lset](https://github.com/prometheus/prometheus/blob/fba20567c0301d48361959a87aefa7d2e0c72815/tsdb/head.go#L1518))?
Looking at the memory profile on cortex seems that most of the memory is being used to keep these labels in memory and,  in most of the cases, they have lots os duplicates strings (in particularly on labels names).

I just did a small change to "reuse strings" during wall replay and it seems to improve quite a bit the memory footprint not only during wall replay but after as well - as the series are kept in memory after that.  

I was thinking if we could do something like this (remove duplicate strings references) during normal operation - perhaps during head compaction?

PS: TSDB already dedups strings on the block index (symbols table)

![Screen Shot 2022-08-05 at 10 21 51 AM](https://user-images.githubusercontent.com/4027760/183469581-3be555ef-9d75-465c-8b96-9ba51a615dfa.png)

**Comment by beorn7** [comment]
Note there is #10991 in the works.

**Comment by alanprot** [comment]
Oh ok...

Seems that https://github.com/prometheus/prometheus/pull/10991 is proposing a different way to store the lset in memory.. but it would not prevent the duplicate strings in memory, right?

I think what im trying to propose to not keep the duplicated strings at all in memory (maybe using the same reference during head compaction). Ex: if i have 1M series with a labelName = "instance", i would store the string "instance" only once, not 1M times.

I know that there is many locks to do this dedup during head compaction but we can minimize them with the stripeSeries.

**Comment by beorn7** [comment]
Then there is also #10231 with a lot of precursor PRs behind it.

**Comment by beorn7** [comment]
Hello from the bug scrub!

There's now also https://github.com/prometheus/prometheus/pull/12304 

We believe that this approach has been tackled from multiple angles by now. Therefore, we are closing this issue. If you feel that there is still an aspect of it that has not been considered, please follow up. /cc @bboreham
