### ISSUE TITLE
Prometheus GUI (the Targets view) is not usable.

### ISSUE THREAD

**Issue by hawran** [prometheus/prometheus#11158]
### What did you do?

1. Open a Prometheus GUI web.
2. Go to the `Status / Targets` view.
3. Expand a group with more than 10 items (?, just a guess, don't know the real threshold for showing the group within its own view).
4. Move the mouse to the `Label` block to see the `Before relabeling` hint (showing the labels before relabeling).

### What did you expect to see?

A `Before relabeling` hint showing the labels (for the selected row).

### What did you see instead? Under which circumstances?

Nothing.
Both the selected row and the mouse are just blinking.

### System information

Ubuntu 22.04.1 LTS, Linux 5.15.0-46-generic x86_64

### Prometheus version

```text
2.37.0
```

**Comment by hawran** [comment]
`Firefox 103.0.2 (64-bit)`

See the screencast for more info:
[220815-113843.prometheus-gui.targets..webm](https://user-images.githubusercontent.com/25924718/184616014-ca5e4143-115b-4eeb-8a05-cde87529f199.webm)

**Comment by gouthamve** [comment]
Facing the same issue in Chrome. Was trying to copy the labels and it just wasn't working.


https://user-images.githubusercontent.com/7354143/185085936-2a4380b6-893b-45db-8d6e-db148c09dc3e.mov

**Comment by roidelapluie** [comment]
2 issues here:

https://github.com/prometheus/prometheus/issues/10894

And the fact that labels can't be selected

**Comment by UntestedEngineer** [comment]
I did a little bit backwards testing.  I can confirm:

2.32.1: Works
2.33.0: Does not work

**Comment by hawran** [comment]
`2.39.1` - not working
Any chance to fix it?

**Comment by beorn7** [comment]
Hello from the bug scrub.

Note that Prometheus v3 comes with a new UI. We are pretty sure that this particular issue will not happen there in the same way. Therefore, we are closing this, but if you see the same thing with the new UI, please follow up. /cc @juliusv
