### ISSUE TITLE
Y-axis values partially hidden on OS X in expression browser

### ISSUE THREAD

**Issue by io41** [prometheus/prometheus#1115]
The following y-axis values all start with `5.` but this is not visible. See screenshot:

<img width="882" alt="screenshot 2015-09-25 09 32 45" src="https://cloud.githubusercontent.com/assets/121624/10096427/4c3dd7a4-6369-11e5-9375-d597d6ca60c7.png">

Possible solution is to either the y-axis needs more space, or the font-size for `.rickshaw_graph .y_ticks text, .rickshaw_graph .x_ticks_d3 text` needs to be reduced to 8px.

**Comment by beorn7** [comment]
Seems to be a problem not only on OSX. Chrome on Linux looks the same.
