### ISSUE TITLE
Expose subquery resolution via Select() via interval or new hint

### ISSUE THREAD

**Issue by GiedriusS** [prometheus/prometheus#11162]
## Proposal

Currently, Thanos does push-down in some instances e.g. when the user's query has a function like `max()`. This means that the query itself is pushed down to the leaf node i.e. Prometheus itself executes that query. This helps speed up queries because all samples don't need to be sent to a central location for evaluation.

`step` parameter is used to detect whether there is a range query or not: https://github.com/thanos-io/thanos/blob/main/pkg/store/prometheus.go#L249-L256. However, right now even subqueries set the `step` parameter to zero. I believe this is because the original `EvalStmt` has `Interval` set as zero https://github.com/prometheus/prometheus/blob/main/promql/engine.go#L630-L638 (take a look at `populateSeries` and `s.Interval == 0`). 

All of this means that Thanos right now incorrectly evaluates pushed-down queries with subqueries in them because it evaluates an instant query at the leaf node.

I suggest changing `Interval` in `populateSeries` accordingly if we are populating series for a subquery. Or perhaps there could be a separate SelectHint for this use case?

**Comment by GiedriusS** [comment]
Potential fix: https://github.com/prometheus/prometheus/pull/11163.

**Comment by bwplotka** [comment]
I would invest in Prometheus hints to help us more. They are designed to provide information for more efficient results from underlying selects (:
