### ISSUE TITLE
Browse Metrics Explorer appends metric names in Expression search input

### ISSUE THREAD

**Issue by LupoOnGitHub** [prometheus/prometheus#11164]
### What did you do?

- Browser: Firefox 103.0.1 (64-bit)
- open metrics browser (localhost:9090)
- open metrics explorer
- select a metric
- execute or not (does not make a difference)
- open metrics explorer again
- select a metric (same or another)
![metrics-explorer-1](https://user-images.githubusercontent.com/43185718/184855819-de5c52ea-567a-49ab-a280-ccd5364ce319.png)
![metrics-explorer-2](https://user-images.githubusercontent.com/43185718/184855841-d5c536d5-fe45-470d-a288-a4f4e7cf4b2d.png)

### What did you expect to see?

Expected only the latest selected metric in the search input

### What did you see instead? Under which circumstances?

name of the latest selected metric is added in front of the previous selected 
![metrics-explorer-result](https://user-images.githubusercontent.com/43185718/184855759-fcb6dfc9-ba8e-44e3-ab3c-5efebdfc1ebc.png)

### System information

Linux 5.15.0-46-generic x86_x64

### Prometheus version

```text
prometheus, version 2.37.0 (branch: HEAD, revision: b41e0750abf5cc18d8233161560731de05199330)
  build user:       root@ebb6827e27f
  build date:       20220714-15:13:18
  go version:       go1.18.4
  platform:         linux/amd64
```

**Comment by roidelapluie** [comment]
it seems complex to me, you might want to introduce a metric in an already existing expression

**Comment by LupoOnGitHub** [comment]
when I browse a metric, and then browse another one, currently the search expression is not overwritten by the newly selected metric, but the name is appended, which results in an unexpected metric expression.
E.g. first browse "go_gc_duration_seconds" and then browse "go_info". The current situation is a metric name in the search bar "go_infogo_gc_duration_seconds". What I expect is only the name of the latest selected metric, so in this case "go_info"

**Comment by LeviHarrison** [comment]
Not everyone would necessarily expect that though, right? There's a perfectly valid use case for wanting to include multiple metric names in a query (ex `<metric> + <metric>`), and I imagine the metric explorer deleting said queries before they're finished would be pretty annoying.

**Comment by LupoOnGitHub** [comment]
OK, if `<metric> + <metric>` is a use case than the browsed metric names should be concanated by a "+" sign instead of putting the names together.

**Comment by LeviHarrison** [comment]
It's not the only use case though, all the other binary operators (`-`, `*`, `/`, etc.) could be what a user is looking for as well. So it wouldn't make sense to assume they wanted addition.

**Comment by LupoOnGitHub** [comment]
Thanks for the explanation, I was not aware of these use cases, so I close this issue.
