### ISSUE TITLE
Prometheus Github Wiki has a a strange single link

### ISSUE THREAD

**Issue by bluepuma77** [prometheus/prometheus#11178]
### What did you do?

Go to https://github.com/prometheus/prometheus/wiki

Click on displayed link https://prometheus.io

### What did you expect to see?

https://prometheus.io

### What did you see instead? Under which circumstances?

https://bit.ly/350amvh forwarding to non-existing
http://www.bitly-bot.com/thirdparty/e107b0e9dba01798ed13f4c433f0e17b

### System information

n.a.

### Prometheus version

```text
n.a.
```

### Prometheus configuration file

```yaml
n.a.
```

### Alertmanager version

```text
n.a.
```

### Alertmanager configuration file

```yaml
n.a.
```

### Logs

```text
n.a.
```

**Comment by dgl** [comment]
I've removed it.

Looks like it was added in March:

```
commit f918966992359b61bea1730cdeeb203dc0a5ab18
Author: brlbr <100172117+brlbr@users.noreply.github.com>
Date:   Tue Mar 22 12:18:39 2022 +0200

    Updated Home (markdown)
```

The user doesn't appear to exist anymore. I don't think it possible to lock down pages in Git Hub wikis, we want to let people edit the ports allocations, but there's not really anything interesting on the main page.
