### ISSUE TITLE
promql (histograms): Extend PromQL testing framework to include native histograms

### ISSUE THREAD

**Issue by beorn7** [prometheus/prometheus#11170]
And then write a bunch of tests dealing with native histograms.

The main obstacle here is to find a good way of spelling out a native histograms in the syntax of the testing framework.

**Comment by hdost** [comment]
So I've been thinking a bit about the Syntax at first you were mentioning JSON but as I looked through the grammar I wasn't so sure about that because we'd be adding a full JSON grammar to PromQL. My next thought was that we add something to the effect of

`{{ format; offset; bucket, bucket, ... }}`

The reason for the double brackets is that we need a way to differentiate the histogram series from other gauge/counter series.

**Comment by beorn7** [comment]
Yeah, as said, that's probably the hardest nut to crack here…

I'm not an expert for the PromQL test framework, but I would tend to not see the syntax of specifying a time series to test against as part of the PromQL grammar. It's kind of its own thing, so we are fairly free to pick the way that makes writing tests easiest. (And I agree that it shouldn't be JSON. If I mentioned that, it was probably in relation to https://github.com/OpenObservability/OpenMetrics/issues/247 , which has nothing to do with the PromQL test framework.)

But what would that be? Naively, one might want to go for an "inverse String method", so that the test writer specifies a histogram in the same "human readable" syntax is the `String` method renders it now. But at a closer look, that seems like a bad idea to me. First of all, this "human readable" form is very verbose (just render a histogram in the Table view of the web UI to get an idea). And second, it's very easy to accidentally describe a histogram that doesn't fit any of the bucketing schemas we support right now.

So I guess it should be something closer to the internal representation, but perhaps not quite. What you suggested above (`{{ format; offset; bucket, bucket, ... }}`) might be very close to the sweet spot. I would probably use "schema" instead of "format" as that's what we use internally in the Go types. The format used here doesn't have to support sparseness. We probably won't create test cases with hundreds of empty buckets between spans. So just providing the first `offset` and then write down the absolute count in each bucket is maybe the best way. The only real difference to your suggestion is that you still need to add the `count` and the `sum` field somewhere. Maybe use "named" fields for clarity? E.g. `{{ sum: 23.34 count: 34 schema: 3 offset: -3 buckets: [ 1.2 2.34 5 6 ] }}`. Each missing field would default to 0. And maybe let every numerical field support the `100+30x1000` syntax to easily define longer series of histograms.

WRT the double curly braces: If the existing format requires the line-break between series, we should get away with single braces, right? But perhaps it's not. Not an expert, as said… It would just be great to find a good trade-off between verbosity and clarity. Perhaps there is a shorter way than double braces…

**Comment by beorn7** [comment]
Demoting to P2 because we decided in the sync meeting we are confident that things work correctly for now, so it's not a blocker for the merge into main (still as an experimental feature with a feature flag). Of course, we still really want this as soon as possible.

**Comment by hdost** [comment]
https://github.com/hdost/prometheus/tree/parser-v2 Also started this experiment just to make sure I know what lexer is really trying to do. Makes it a bit easier to see where issues might be

**Comment by hdost** [comment]
Latest attempt started, began a bit fresh, borrowing some changes from my previous attempts. Restarted just from the lexer, maintaining lexing and parsing of existing tests.
https://github.com/prometheus/prometheus/pull/12080
