### ISSUE TITLE
openstack_sd return wrong number of targets when openstack has multiple projects and all_tenants is configured to true

### ISSUE THREAD

**Issue by zhang-sec** [prometheus/prometheus#11182]
### What did you do?

I set up openstack_sd to obtain all instance targets of all openstack projects.

### What did you expect to see?

When openstack has multiple projects and all_tenants is configured to true, openstack_sd should discover correct number of instance targets.

### What did you see instead? Under which circumstances?

**openstack_sd return wrong number of targets.**

I have 4 projects on my openstack with 75 total instances across all projects(some of them have no floating IPs), but when all_tenants is configured to true, openstack_sd ended up returning 118 targets.

instance target metadata in **_admin_** project, this is correct:

__address__="172.16.0.x:80"
__meta_openstack_address_pool="private_admin_vlan30"
__meta_openstack_instance_flavor="e2874b8a-7d9b-4de3-8c82-e1da2d58610f"
__meta_openstack_instance_id="185165a5-5923-4d48-afd9-f30421cd5e6f"
__meta_openstack_instance_name="xxx"
__meta_openstack_instance_status="ACTIVE"
__meta_openstack_private_ip="172.16.0.x"
__meta_openstack_project_id="f2eafd169de24c41a2d02b3647fba6e4"
__meta_openstack_user_id="8a61d0eee2384be1963b8ed11e7270b0"
__meta_openstack_public_ip="192.168.30.x"
__metrics_path__="/metrics"
__scheme__="http"
job="openstack"

instance target metadata in **_test_** project, the same instance generated 2 targets, and mistakenly used the public IP(192.168.30.x) as the private IP:

**Target1:**
__address__="172.30.0.x:80"
__meta_openstack_address_pool="private_test_vlan30"
__meta_openstack_instance_flavor="e2874b8a-7d9b-4de3-8c82-e1da2d58610f"
__meta_openstack_instance_id="f78ca89e-191b-4f94-86ef-e7d4eb9d5ec1"
__meta_openstack_instance_name="xxx"
__meta_openstack_instance_status="ACTIVE"
__meta_openstack_private_ip="172.30.0.x"
__meta_openstack_project_id="684dee66643b42e29eda9a6f4da7f592"
__meta_openstack_user_id="8a61d0eee2384be1963b8ed11e7270b0"
__metrics_path__="/metrics"
__scheme__="http"
job="openstack"

**Target2:**
__address__="172.30.0.x:80"
__meta_openstack_address_pool="private_test_vlan30"
__meta_openstack_instance_flavor="e2874b8a-7d9b-4de3-8c82-e1da2d58610f"
__meta_openstack_instance_id="f78ca89e-191b-4f94-86ef-e7d4eb9d5ec1"
__meta_openstack_instance_name="xxx"
__meta_openstack_instance_status="ACTIVE"
__meta_openstack_private_ip="192.168.30.x"
__meta_openstack_project_id="684dee66643b42e29eda9a6f4da7f592"
__meta_openstack_user_id="8a61d0eee2384be1963b8ed11e7270b0"
__metrics_path__="/metrics"
__scheme__="http"
job="openstack"

### System information

Linux 3.10.0-1160.el7.x86_64 x86_64

### Prometheus version

```text
prometheus, version 2.29.2 (branch: HEAD, revision: 752c4f11ae86effa9a46f017f2feb66730c67ed8)
  build user:       root@61bcc9848ade
  build date:       20210827-09:44:22
  go version:       go1.16.7
  platform:         linux/amd64

prometheus, version 2.38.0 (branch: HEAD, revision: 818d6e60888b2a3ea363aee8a9828c7bafd73699)
  build user:       root@e6b781f65453
  build date:       20220816-13:23:14
  go version:       go1.18.5
  platform:         linux/amd64
```

### Prometheus configuration file

```yaml
- job_name: 'openstack'
    openstack_sd_configs:
      - role: 'instance'
        region: 'RegionOne'
        identity_endpoint: 'http://xxxx:5000/v3'
        domain_name: 'Default'
        project_name: 'admin'
        username: 'xxx'
        password: 'xxx'
        all_tenants: true
```

**Comment by beorn7** [comment]
Hello from the bug scrub!

It's hard for us to vet this issue as the openstack_sd is heavily undermaintained.

This is now more than two years old, and a few things have changed there. We close this issue now as stale, but if the issue is still happening with recent Prometheus versions, please follow up here so that we can re-open.

Very generally, we would welcome active maintainers by people who are using openstack_sd in their day-to-day work.
