### ISSUE TITLE
Increase in memory usage between TSDB v2.33.5 and v2.35.0

### ISSUE THREAD

**Issue by PhilipGough** [prometheus/prometheus#11185]
### What did you do?

I ran a load test with two different version of Thanos receive leveraging TSDB and pinned to the following commits:

1. [v0.25.2 Thanos](https://github.com/thanos-io/thanos/releases/tag/v0.25.2) -> [692a54649ed7](https://github.com/prometheus/prometheus/search?q=692a54649ed7)
2. [v0.27.0 Thanos](https://github.com/thanos-io/thanos/releases/tag/v0.27.0) -> [03831554a519](https://github.com/prometheus/prometheus/commit/03831554a51946f28c7cdc6be7282c687092327b)

The test is pushing twenty million active series over 3h. The configuration for both runs was exactly the same. Six 
Thanos receive replicas with exactly the same args and resources etc. The tests were run on an OpenShift cluster.

### What did you expect to see?

I expected to see no significant difference between the memory consumption across both runs.

### What did you see instead? Under which circumstances?

The tests were run at different times so the v0.27.0 graph is offset by 3hrs.

After summing by version, we can see a significant difference in memory usage on the newer TSDB after some time:

<img width="1557" alt="Screenshot 2022-08-18 at 14 41 37" src="https://user-images.githubusercontent.com/5781491/185409665-4a10b60e-008e-4fe1-8f73-d0afc2536f9b.png">

We can see across the two runs that we are remote writing the same number of series:

<img width="1879" alt="Screenshot 2022-08-18 at 14 45 10" src="https://user-images.githubusercontent.com/5781491/185410390-530810b8-453c-4c40-bf12-a31c17dba459.png">

Side by side view:

<img width="1769" alt="Screenshot 2022-08-18 at 14 49 26" src="https://user-images.githubusercontent.com/5781491/185411400-4aa9802d-0426-4c86-8964-ffbeb4236253.png">

View per Pod overlayed:

<img width="1587" alt="Screenshot 2022-08-18 at 14 51 21" src="https://user-images.githubusercontent.com/5781491/185411783-8480ef0d-d361-4c0d-9e3b-feb7c9ea504f.png">

**Comment by bwplotka** [comment]
cc @codesome @fpetkovski 🤗

**Comment by fpetkovski** [comment]
I wonder if we can run the same test on Thanos 0.27 with an older Prometheus version. This way we can tell whether the memory increase is caused by TSDB or Thanos.

**Comment by PhilipGough** [comment]
> I wonder if we can run the same test on Thanos 0.27 with the Prometheus version from 0.25.2. This way we can tell whether the memory increase is caused by TSDB or Thanos.

Yes, let me follow up with that

**Comment by PhilipGough** [comment]
Following up as promised to @fpetkovski suggestion around building Thanos v0.27.0 with the 0.25.2 TSDB

I made the required changes and pushed to [my branch](https://github.com/thanos-io/thanos/compare/release-0.27...PhilipGough:thanos:custom) and docker image `docker.io/philipgough/thanos:custom`

```bash
 docker cp  $(docker create --name thanos-custom-tsdb docker.io/philipgough/thanos:custom):/bin/thanos /tmp/thanos-custom && go version -m /tmp/thanos-custom | grep github.com/prometheus/prometheus
        dep     github.com/prometheus/prometheus        v1.8.2-0.20211119115433-692a54649ed7
        =>      github.com/prometheus/prometheus        v1.8.2-0.20211119115433-692a54649ed7    h1:8rwRA5BKEAWtawaP4ozroDm3xMDrp9POAoT3HkQ3ZHw=
```

We can see that the dependencies align with whats in [v0.25.2](https://github.com/thanos-io/thanos/blob/v0.25.2/go.mod#L220)

<img width="1498" alt="Screenshot 2022-08-22 at 09 27 55" src="https://user-images.githubusercontent.com/5781491/185875759-88112ceb-c6d0-4f52-9010-1e76fbe19b71.png">

Interestingly enough the custom build track almost identically with v0.27.0 while v0.25.2 still outperforms.

For interests sake, I then ran the same test with thanos `main`, which uses a newer TSDB and which shows an improvement over v0.27.0 but is also outperformed by the older version.

Perhaps this highlights an issue in Thanos directly or is intermittent? 

I will try to reproduce locally and investigate further.

**Comment by roidelapluie** [comment]
pprof might help as well.

**Comment by PhilipGough** [comment]
<img width="1920" alt="Screenshot 2022-09-07 at 16 05 14" src="https://user-images.githubusercontent.com/5781491/188912781-12dc4fd9-f239-43ea-9795-a06548c61f27.png">

I set up a proxy to mirror requests which enabled me to avoid offsetting the graphs. The results tracked almost identically between the two versions that were originally reported.

I am going to close the issue based on that result since it seems like there were other factors involved when tracking the run at different times!
