### ISSUE TITLE
tsdb (histograms): Scrape float histograms and store them in the TSDB

### ISSUE THREAD

**Issue by beorn7** [prometheus/prometheus#11199]
Scraping is the easy part, WIP see #11149 .

Storing in TSDB is the hard part: We cannot do the triple-delta integer trick (unless all floats in the histogram are in fact integers, in which case we might consider falling back to an integer histogram internally). We should probably start with the usual XOR encoding as we use them for the normal Prometheus float samples and encode the absolute count in each bucket with it (in relation to the previous values from corresponding buckets). So we need yet another chunk encoding.

**Comment by beorn7** [comment]
@marctc this should be assigned to you, but we haven't you added as a collaborator to the Prometheus org yet…

**Comment by beorn7** [comment]
For bonus points, also add scraping of conventional float histograms. This is already implicitly supported for the traditional Prometheus text format because everything is a float there anyway. However, it is not yet supported for the resurrected protobuf format because the protobuf format used actual integers for conventional histograms and just got floats added recently. The change for conventional float histograms is easy, though, because we already store them with floats everywhere.

(Ironically, float histograms won't work with OpenMetrics because OpenMetrics explicitly only uses integers for histograms. I would expect OpenMetrics to add float histograms in the future, though.)

**Comment by codesome** [comment]
This has been done
