### ISSUE TITLE
histograms: clean up metrics

### ISSUE THREAD

**Issue by beorn7** [prometheus/prometheus#11196]
We have metrics just added for experimenting (e.g. `histogramSamplesTotal` in tsdb/head.go), but we might also add “real” production metrics or work Histogram stuff into existing metrics.

https://github.com/prometheus/prometheus/blob/7feea8aa894da5f16d41935538d2bf6ffb55050f/tsdb/head_append.go#L581 is a case where we add histograms and floats in the same way to `samplesAppended` but might want to partition.

_Technically, we are allowed to change metrics even for a released stable feature, but in this case, we already know we have to rework these metrics. Therefore this is marked P1, i.e. we should get this done before merging the sparsehistogram branch into main._

**Comment by codesome** [comment]
We can either partition existing metrics or adding new metrics. I don't know if suddenly partitioning will create problems in usage, but I am in favour of partitioning.

**Comment by codesome** [comment]
At the moment I am thinking of these 3 `samplesAppended outOfBoundSamples outOfOrderSamples` and remove `histogramSamplesTotal`

**Comment by codesome** [comment]
An attempt https://github.com/prometheus/prometheus/pull/11395

**Comment by beorn7** [comment]
I think that's enough for now. We can still iterate on it later, but the metric change we wanted to do for sure is done now.
