### ISSUE TITLE
tsdb (histograms): Support or remove `BufferedSeriesIterator`

### ISSUE THREAD

**Issue by beorn7** [prometheus/prometheus#11198]
`BufferedSeriesIterator` seems unused. Either verify that and remove it. Or otherwise, we have to add Histogram support.

If we go for removal, we should do it directly in main rather than in the sparsehistogram branch.

**Comment by codesome** [comment]
I find it is being used in PromQL engine (https://github.com/prometheus/prometheus/blob/main/promql/engine.go#L1370, https://github.com/prometheus/prometheus/blob/main/promql/engine.go#L1813). However, we seem to be duplicating it here https://github.com/prometheus/prometheus/blob/main/tsdb/tsdbutil/buffer.go which can be removed. I can do both, implement histograms in the storage package and remove this extra file.

**Comment by codesome** [comment]
Looks like BufferedSeriesIterator already supports histograms in the storage package (else queries would not have worked in the first place). The one from tsdbutil has been removed from main branch. Hence closing this issue.
