### ISSUE TITLE
tsdb (histograms): Handle duplicate histograms properly

### ISSUE THREAD

**Issue by beorn7** [prometheus/prometheus#11197]
We are currently allowing ingesting two different Histograms with the same timestamp. See https://github.com/prometheus/prometheus/blob/7feea8aa894da5f16d41935538d2bf6ffb55050f/tsdb/head_append.go#L355-L360 . Only exact duplicates should be allowed.

**Comment by codesome** [comment]
What does exact duplicate mean? The spans can change with additional empty buckets while the filled buckets match? Or should the entire thing exactly match, the spans and the buckets and rest of the field?

**Comment by beorn7** [comment]
Hmm, what do we actually do with exact duplicates in the conventional float case? IIRC ingesting them is a no-op (no error message but no state change in the TSDB either). 

If that's the case, I think a histogram with just empty buckets added or removed should still count as the same histogram.
Essentially, if you run the `Compact` method on both, and the returned histograms are equal, then we should consider the original histograms equal (and not ingest the duplicate).

(This is just a random thought. I might be wrong, as usual…)

**Comment by codesome** [comment]
It would be weird to get empty buckets out of nowhere, and helps keep the code simple if we do not try and take care of empty buckets. Running compact on 2 histograms for every histogram append might be very CPU consuming at ingestion time. So I am thinking of just compacting spans and checking (in-flight check, wont actually call the compact function) while expecting same content for buckets for a start. Based on what we see in practice we can improve the logic I think.

**Comment by beorn7** [comment]
Maybe we should run Compact on all histograms upon ingestion? In that way, we would unify their layout, no matter what targets expose… (In most cases, the Compact call wouldn't do anything, so it shouldn't be too expensive.)

**Comment by codesome** [comment]
Opened https://github.com/prometheus/prometheus/issues/11321 to track Compact() before appending histogram.
