### ISSUE TITLE
histograms: allow recording rules to emit native histograms

### ISSUE THREAD

**Issue by beorn7** [prometheus/prometheus#11201]
With #11199 and #11200 completed, we can finally store native histograms emitted by recording rules (and by alerting rules, FWIW).

Recording rules will always emit float histograms (that's why we need #11199). A more interesting question is if they will always emit gauge histograms or if there are rare cases where they could also emit counter histograms. For the first iteration here it's probably OK to assume all histograms emitted by recording rules are gauge histograms. (The usual use case will be pre-aggregation of rate'd histograms or maybe just a rate'd histogram.) However, for the final implementation, we have to think about the counter histogram case. It might require some type tracking in the PromQL engine, which foreshadows future, more invasive improvements to PromQL, where we could finally prevent (or at least warn against) rate'ing a gauge of a normal float metric etc.

**Comment by codesome** [comment]
Done in https://github.com/prometheus/prometheus/pull/11838
