### ISSUE TITLE
remote write: Handle float histogram and gauge histograms (and float gauge histograms ;)

### ISSUE THREAD

**Issue by beorn7** [prometheus/prometheus#11203]
Once #11199 and #11200 are done, we also have to propagate float histograms and gauge histogram (and the combination of both) via remote write. Since this is all prepared in the protobuf already, it should be a fairly trivial change. (Maybe the code is even written in a way that it will "just work" once TSDB supports both properties. Still need to make sure, therefore this issue.)

**Comment by leizor** [comment]
Looks like support for float histograms was added in https://github.com/prometheus/prometheus/pull/11817 so it's just support for gauge histogram needed now

**Comment by beorn7** [comment]
Yes, I believe this is all done. @codesome if you find the time, please verify. But I'm confident enough to close this as done.
