### ISSUE TITLE
tsdb: Investigate zstandard WAL compression

### ISSUE THREAD

**Issue by SuperQ** [prometheus/prometheus#11223]
## Proposal

There is now a [pure Go zstd compression library](https://github.com/klauspost/compress/tree/master/zstd#zstd) that seems to be fast enough to improve on the WAL compression.

It may be worth experimenting with to reduce the storage footprint of WAL files.

**Comment by beorn7** [comment]
Hello from the bug scrub!

This has been implemented in #11666. Use `--storage.tsdb.wal-compression-type=zstd` to select it. (It's hidden, but it's also more of an experiment for now.)
