### ISSUE TITLE
Support out of order ingestion for native histograms

### ISSUE THREAD

**Issue by beorn7** [prometheus/prometheus#11220]
This feature will be released soon for normal float samples, and it would be really weird if we did not support it for histogram samples.

Update 14th June 2023: @krajorama and @jesusvazquez are starting to work on this issue.

**Comment by krajorama** [comment]
Overall task list from discussion:
Scope: everything is in the tsdb package: db.go, head_append.go, ooo_*.

Write path: start from headAppender.Append function
Need ooo_head.go OOOChunk.InsertHistogram, OOOChunk.ToHistogramChunk, modify writing ooo head to disk to account for different encodings.
Need head.go insertHistogram - keep it simple for now, no handling of counter reset, just use the 32 sample OOOchunks.

@jesusvazquez notes:
ooo_head.go
 - Creeate new InsertHistogram() method
 - Create new ToHistogramFloatHistogram() ToHistogram()

head_append.go
 - Modify AppendHistogram() with ooo logic
 - Modify appendableHistogram() with ooo logic
 - Create insertHistogram()
 - Modify mmapCurrentOOOHeadChunk() with new chunk encoding logic. The method currently works with ooo chunks as if they always were XOR chunks.

**Comment by beorn7** [comment]
Also assigning to @zenador and @krajorama to mark all the collaborators on this issue.

**Comment by zenador** [comment]
Testing to see if this grants permission to assign

**Comment by krajorama** [comment]
From IRL discussion:  we've decided that we do **not need** to support the of mixing different sample types (float/integer histogram/float histogram) in the OOO headchunk. This should make testing a bit simpler.

**Comment by krajorama** [comment]
From IRL discussion:
@carrieedwards @fionaliao @jesusvazquez (cc @zenador )

Immediate goals in priority order for the code:
* add native histograms to existing unit test happy paths
* add tests around counter reset/multiple chunk handling
* tests for float <-> native histogram series transitions

**Comment by beorn7** [comment]
The PromQL engine simply looks at the `CounterResetHint` as returned from the query to TSDB. If you want the PromQL engine to do the (expensive) traditional counter reset detection, just set the `CounterResetHint` in the returned histogram to `UnknownCounterReset`.

**Comment by beorn7** [comment]
Closing this as the code is merged, but note that this is a huge undertaking and it is quite likely that we will find bugs in the implementation. But those should be tracked in specific issues.

Thanks everyone for all the work here.
