### ISSUE TITLE
remote read / performance: reuse buffer for marshaling

### ISSUE THREAD

**Issue by GiedriusS** [prometheus/prometheus#11232]
Currently, remote read handler allocates a new buffer for each response: https://github.com/prometheus/prometheus/blob/314aa45c2ced676d6a76d5ce9333a60faa331570/storage/remote/codec.go#L235-L240. We can re-use the buffers with a `sync.Pool` instead of allocating a new one each time.

**Comment by roidelapluie** [comment]
cc @bwplotka

**Comment by bwplotka** [comment]
Ideally, we start simpler with static buffers/types first before we move to sync.Pool, but can definitely improve a lot here.

Help wanted!

**Comment by fatsheep9146** [comment]
Could I work on with this? @bwplotka
