### ISSUE TITLE
Metrics for defined rules of type Alert

### ISSUE THREAD

**Issue by druanoor** [prometheus/prometheus#11234]
Currently, the `ALERTS` metric is only showing metrics for metrics in `Pending` or `Firing` states.

We want to use this metrics for checking the adoption of self-service alerts from our end-users. I've seen that the `/api/v1/rules` endpoint provides this info, but would be great having it directly exposed on prometheus metrics.

**Comment by roidelapluie** [comment]
Which kind of metrics are you looking for? Do you have examples?

**Comment by druanoor** [comment]
I mean metrics for the defined alerts as Rules, pretty much this: 
![image](https://user-images.githubusercontent.com/51286702/188473728-7e68c388-3820-4a66-a802-de1fa139330b.png)


Similiar to the output of calling the `/api/v1/rules?type=alerts` endpoint but on metrics format exposing alertname & labels even if they have values like `$labels.namespace`

**Comment by beorn7** [comment]
Hello from the bug scrub!

We are trying to understand this feature request. It seems this requires a _new_ metric (not an extension of the `ALERTS` metric), just counting _defined rules_ (not _alerts_), labeled by their state (inactive, pending, firing) what you see in the UI.

As you already noted, the https://prometheus.io/docs/prometheus/latest/querying/api/#rules endpoint can be used, so there is some kind of work-around present

As there was nothing moving on this in the last two years, we are closing it, but if anyone has concrete plans to work on this, please follow-up and we'll re-open.
