### ISSUE TITLE
Enable handling of overlapping blocks by default

### ISSUE THREAD

**Issue by codesome** [prometheus/prometheus#11255]
Prometheus has had the support for handling overlapping blocks (both during compaction and querying) for a very long time, and it has been used by Thanos, Cortex, Mimir at large scale.

I propose we enable them by default now and not hard fail on finding overlapping blocks. I also propose we still have the switch to disable compaction of overlapping blocks because it is useful and required by downstream consumers with out-of-order feature (what that I mean Mimir, but will also be required by Cortex when they support out-of-order ingestion).

cc @bwplotka

**Comment by bwplotka** [comment]
Yes, I like it. It proven to work pretty well for us too.

**Comment by roidelapluie** [comment]
In which case are overlapping blocks not a bug in regular Prometheus?

**Comment by codesome** [comment]
Also I think it helps in ease of use when working with out of order and backfilling, you don't have to do an extra step of enabling overlapping blocks (while also having to remember that overlapping blocks need to be enabled).

**Comment by jesusvazquez** [comment]
> We log a warning when overlapping blocks are found, so if we come across it, we can see what was the reason then instead of stopping Prometheus from functioning.

If its that much rare and the codebase can already handle querying from multiple overlapping blocks I think thats another reason to simply enable overlapping blocks by default :+1:
