### ISSUE TITLE
ui (histograms): Prettify rendering of Native Histograms in Table view

### ISSUE THREAD

**Issue by beorn7** [prometheus/prometheus#11269]
The text rendering of Native Histograms in the Table view is quite verbose, but it's currently the only way of displaying Native Histograms in the built-in UI.

Maybe a small graphical representation of each Histogram would be much more consumable for humans, with some way of retrieving the exact text representation of all the numbers (maybe via a tool tip, but that might have accessibility problems).

**Comment by juliusv** [comment]
Thanks for bringing this to my attention, I'm working on this right now!


https://user-images.githubusercontent.com/538008/215611917-24d4b689-dfde-4bc0-bb42-977584d8605c.mp4

**Comment by leeoniya** [comment]
different width bars are even more :exploding_head: when you have a dynamic/adaptive x axis.

in one table a 30px wide bar can be 0.1-0.2 and the same width bar, in the same hz position position in the next table can be 500-1000 :). i'm still entirely unconvinced by the utility of different bar widths here :sweat_smile:

**Comment by juliusv** [comment]
Hmm yeah, it's definitely a mind-altering experience 🤔🤣

Synching the X-axis up is an interesting idea, I could try that. Of course it would mean that if only one out of many histograms has one super high-ranged bucket, all other histogram displays will be squeezed together as well.

**Comment by leeoniya** [comment]
> Of course it would mean that if only one out of many histograms has one super high-ranged bucket, all other histogram displays will be squeezed together as well.

https://getyarn.io/yarn-clip/b1c103b1-9629-48b4-aa03-4318ce00422d

**Comment by beorn7** [comment]
Maybe I'm missing something, but shouldn't the x axis just be exponential as the bucket size is also exponential?

**Comment by leeoniya** [comment]
> Maybe I'm missing something, but shouldn't the x axis just be exponential as the bucket width is also exponential?

that's essentially what i'm suggesting. when the axis scale matches the bucket progression, you get uniform widths and spacing. wheb the axis scale is linear but the bucket progression is exponential, you get the varying widths as in the screen rec above.

**Comment by juliusv** [comment]
Yeah, for interaction the log scale definitely is better. OTOH human brains are bad at grokking exponentials or logarithms, so I think having an option to also display buckets on a linear axis would be good too. Just viewing things linearly made me appreciate much more just how tiny the initial buckets are, and how large the last ones are – that's something that gets way harder to picture mentally with a log-scale axis. So I could implement both as well.

**Comment by beorn7** [comment]
A switch would certainly make sense.

BTW, for the funny PNG renderings in native histograms, I used an exponential y axis. But a heatmap is essentially a series of color-coded histograms rotated by 90°, so the exponential y axis in the heatmap corresponds to an exponential x axis in the table view.

**Comment by beorn7** [comment]
@juliusv have you made any progress on this recently?
There might be a new contributor interested in this (@Maniktherana). If you don't plan to work on this any time soon, perhaps you could share your work so far?

**Comment by Maniktherana** [comment]
hey @juliusv I'm looking to work on this
How did you achieve the histogram renders? was it using heatmaps or did you make a custom flot chart?

**Comment by juliusv** [comment]
@Maniktherana Oh, I actually didn't use any library at all and drew everything with pure HTML, which ended up being only a few lines actually :) And yes, since I have been shamefully neglecting this and mostly working on the new UI now, feel free to take this over. I just pushed what I had back then to this branch: https://github.com/prometheus/prometheus/tree/native-histogram-charts (with this latest commit containing all the relevant changes: https://github.com/prometheus/prometheus/commit/662fa3871b538541ec7651c1cc61789831c75e80)

I had some other work on top of that to start adding optionality for exponential / non-exponential display as requested here, but it was still so broken that I removed it for now and just pushed the latest working state before that.

Feel free to either base your work on that branch or build something better :)

**Comment by Maniktherana** [comment]
> Modulo the double tooltip and the "BRUH" at the top of course :)
Fixed the double tooltip issue, it was caused by clashing `id={`bucket-${index}-${bIdx}`}.
And yeah I'll remember to remove that 😅 

> Do you think it's worth making the X axis configurable between exponential vs. linear (what I had previously)?

As long its meaningful to users I don't see an issue. Can make it a toggle like how it is between line chart/stacked chart. Might have to remove x-axis ticks/labels for every quarter in exponential mode tho as it doesn't seem to make much sense. It can be saved for the linear scale.

> Another consideration is whether we will always want to display that much for each histogram sample. Makes the table quite long and the DOM will probably get expensive at some point as well. So at least at some point we may want to add an option to cut down on the level of detail, but I think we can add that later too.

Yes that's also a concern I share. I'm looking into strategies for this, ig we can simply not render bars with a count <1% as they can refer to the table for granular data. It's more apparent on linear scales as bars start having a width of 1px

**Comment by Maniktherana** [comment]
@beorn7 ig we can close this under #13658

**Comment by beorn7** [comment]
Thanks for working on this. It looks great.
However, the current solution doesn't seem to render the zero bucket and negative buckets.

Here you can see a histogram with a populated zero bucket and many negative buckets, they simply don't show up:

![image](https://github.com/prometheus/prometheus/assets/5609886/93c2a776-f036-42d2-b10d-cf579155b8a5)

**Comment by beorn7** [comment]
Also, it would be nice to improve the sorting of the negative buckets and the zero buckets. The negative buckets that are "most negative" should come first, and the zero bucket should be in between the negative and positive buckets.

**Comment by Maniktherana** [comment]
> Thanks for working on this. It looks great. However, the current solution doesn't seem to render the zero bucket and negative buckets.
> 
> Here you can see a histogram with a populated zero bucket and many negative buckets, they simply don't show up:
> 
> ![image](https://private-user-images.githubusercontent.com/5609886/309007513-93c2a776-f036-42d2-b10d-cf579155b8a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyMjYwNDksIm5iZiI6MTcwOTIyNTc0OSwicGF0aCI6Ii81NjA5ODg2LzMwOTAwNzUxMy05M2MyYTc3Ni1mMDM2LTQyZDItYjEwZC1jZjU3OTE1NWI4YTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjlUMTY1NTQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGE4YzUxYTgxODBjNjhhMWQ1NWRlZjVlM2ZiNThiMzU2ZjhjMDYwYWY0ODdlYTkyZmEwNDFmMWVkOWIzODI0NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.v_obH0wegaJGfkDXEYecKnqRO-ya8q7FK_81SCQ7SYA)

What should behavior look like for negative buckets? with current implementation, they overflow behind y axis (of course they do) but it would lead to a rather cramped graph in table view

**Comment by beorn7** [comment]
Yeah, the negative buckets have to be "left of zero". But the X axis can start at negative values.
More of a challenge is how to render the zero at all because you'll never reach it on a truly exponential scale. I guess you just start rendering at the first populated bucket closest to zero and render the zero bucket at the same width as all the other buckets, and then just label the x axis accordingly.

**Comment by beorn7** [comment]
Maybe leave one standard bucket width empty if the zero bucket isn't directly touching the first populated negative or positive bucket. (In most practical cases, there will be very many empty buckets between the zero bucket and the first populated bucket. There is even the case where the zero bucket has a width of zero, i.e. it only takes observations of exactly zero. That's a valid use case and has to be rendered somehow.)

**Comment by Maniktherana** [comment]
I'm trying to keep up here, but can you please explain the zero bucket?
Is it just a bucket where the range has zero in it?

**Comment by beorn7** [comment]
From the [design doc](https://docs.google.com/document/d/1cLNv3aufPZb3fNfaJgdaRBZsInZKKIHo9E6HinJVbpM/edit) (which is quite outdated by now, so take things there with a grain of salt): "The zero-bucket-width defines a special bucket around zero. All observations with an absolute value below or equal the zero-bucket-width are counted in this special bucket. This avoids an explosion of the bucket counts for observations very close to zero and allows observations of the value zero in the first place. The precise value for the zero-bucket-width is arbitrary (and in particular not related to the resolution). In practice, it doesn’t even matter that much. It should be large enough to not let noisy observations very close to zero create a lot of buckets, and small enough to not count observations into the zero bucket that are meant to be seen as non-zero."

**Comment by beorn7** [comment]
I'll try to draw a few sketches once I find the time.

**Comment by Maniktherana** [comment]
> There is another aspect of histogram rendering: The population in a bucket should be represented by the _area_, not by the _height_ of the bar. This works just fine with the exponential rendering because all bars have the same width. But for the linear rendering, we needed to adjust the height (or we decide to not render a "real" histogram).
> 
> But let's first get the exponential rendering right, that will be most common anyway.

Rough draft, but I came up with this for exponential scales:
`width: 100 / numBuckets + '%';`
`height: ((count / range) / (countMax / rangeOfCountMax)) * 100 + '%'`
The y-axis ticks are just quartiles of `countMax / rangeOfCountMax`
<img width="877" alt="Screenshot 2024-03-01 at 12 13 09 AM" src="https://github.com/prometheus/prometheus/assets/14011425/30e3786e-3715-4a13-a91f-2c7dd501332d">

This would, at the very least, look somewhat consistent and you could calculate to get the area equal to the count

for example in the tallest bar, the 
range is  `[-0.000003814697265625 -> -0.0000019073486328125)`
and count is `0.0666681481810707`

On multiplying we get our height of ~35k

Now to figure out linear scales

**Comment by Maniktherana** [comment]
@beorn7 Let me know if this is on the right path. I think the zero bucket bit may not have been addressed yet

**Comment by beorn7** [comment]
It looks very promising. Could you put your current code state into a WIP PR? Then I can play with it. (But I won't get there before Tuesday.)

**Comment by beorn7** [comment]
Finally this works properly.
