### ISSUE TITLE
tsdb (histograms): Support native histograms in snapshot on shutdown

### ISSUE THREAD

**Issue by beorn7** [prometheus/prometheus#11262]
See http://ganeshvernekar.com/blog/prometheus-tsdb-snapshot-on-shutdown/ for context on the in-memory snapshot on shutdown.

The snapshot-on-shutdown feature itself is experimental and has to be activated with a feature flag. Therefore, this is only P2 because not having the support only means that you cannot switch on both feature flags at the same time.

Tentatively assigning to @codesome as he is the expert for the snapshot-on-shutdown feature.

**Comment by codesome** [comment]
@marctc will be working on this.
