### ISSUE TITLE
TSDB (histograms): Possible BufferedSeriesIterator performance issue

### ISSUE THREAD

**Issue by beorn7** [prometheus/prometheus#11273]
Is this TODO by @codesome  just a small performance improvement (or something more serious that might be more relevant than P3)? https://github.com/prometheus/prometheus/blob/7feea8aa894da5f16d41935538d2bf6ffb55050f/storage/buffer.go#L44

**Comment by codesome** [comment]
Maybe related in coming up with an overall improvement: https://github.com/prometheus/prometheus/blob/7feea8aa894da5f16d41935538d2bf6ffb55050f/storage/buffer.go#L167

**Comment by fatsheep9146** [comment]
Is this pr still valid? Does #11687 already solve this pr ?
@beorn7

**Comment by beorn7** [comment]
Yes, you are right. Please review #12839. :)
