### ISSUE TITLE
histograms: custom bucket layouts

### ISSUE THREAD

**Issue by beorn7** [prometheus/prometheus#11277]
Implement one or more custom bucket layouts, including all the implications (mostly to detect when merging/aggregation is possible if different layouts collide). Examples:
* Explicitly configured bucket boundaries (which could be used to perfectly emulate the conventional histograms).
* Linear buckets (good for observations that are naturally distributed evenly or that are inherently logarithmic already, like sound pressure in dB, star brightness, …).
* Log-linear buckets (e.g. 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 20, 30, …)
* Anything to support another metrics system’s histograms.
* Maybe a simple offset of the current exponential layout for distributions where high accuracy is needed around a value that is not zero (further discussion needed if this is a good idea).

Note that the implementation has to go along with corresponding feature in the instrumentation libraries and the exposition format.

**Comment by baryluk** [comment]
Note, I frequently use multi-scale histograms. I call it `HistogramHybrid3`

i.e. 0, 1, 2, 3, 4, 5, 6, 7, 9, ..., 20, 30, 40, 50, ..., 190, 200, 400, 800, 1600, 3200, ...  (linear, linear, exponential).

These are frequently tuned for specific application, and code updating buckets knows exactly where to find buckets, by doing bounded amount of checks very quickly (<10, use first set of buckets via simple indexing, <=200 use second set of buckets via simple division, offset and indexing, >200 use third bucket, by offsetting, dividing, and doing an optimized log2).

Way faster than doing binary search.

**Comment by beorn7** [comment]
To avoid misunderstandings, I should mention that custom bucket layouts are a niche feature that is expected to be used very rarely for very specific use cases. Guaranteed mergeability across time and (label) space is one of the key features of the new Native Histograms, and custom bucket layouts go directly against that.

**Comment by jmcarp** [comment]
I see why you all would consider this a niche feature, but I would like to voice support for implementing it at some point. Exponential buckets work well most of the time, but sometimes my team wants to collect a metric that follows a linear or log-linear distribution, and it would be simpler to be able to use native histograms in those cases as well.

**Comment by bwplotka** [comment]
I was thinking about this feature n the context of migration [use case](https://github.com/prometheus/prometheus/issues/13304#issuecomment-1866248406). We could already replace all classic histograms with native histograms if we had custom bucketing feature for efficiency of storage and atomicity of remote export. 

Do you have any existing ideas around this @beorn7? My understanding is that proposal has to follow and the initial high level implementation could be as follows:

1. Add appropriate bucketing and values to separate fields (float buckets, int counts, float counts) and decide on priority/semantics

```
message Histogram {
   oneof count { // Count of observations in the histogram.
    uint64 count_int   = 1;
    double count_float = 2;
  }
  double sum = 3; // Sum of observations in the histogram.

  // timestamp is in ms format, see model/timestamp/timestamp.go for
  // conversion from time.Time to Prometheus timestamp.
  int64 timestamp = 15;

  // custom_buckets specify custom, explicit buckets for this histogram.
  // If empty, sparse (exponential) int or float histogram is assumed.
  // If more than one custom bucket is set, explicit buckets are assumed
  // and all other fields (e.g. positive/negative spans, deltas, counts, resets etc) 
  // are ignored.
  repeated double custom_buckets =  15;
  // Use either "custom_buckets_counts" or "custom_buckets_float_counts", 
  // the former for regular histograms with integer counts, the latter for float
  // histograms.
  repeated sint64 custom_buckets_counts    = 16;
  repeated double custom_buckets_float_counts    = 17;

  // ---- All below not used when custom layout is chosen?

  // Negative Buckets.
  repeated BucketSpan negative_spans =  8 [(gogoproto.nullable) = false];
  
  // Use either "negative_deltas" or "negative_counts", the former for
  // regular histograms with integer counts, the latter for float
  // histograms.
  repeated sint64 negative_deltas    =  9; // Count delta of each bucket compared to previous one (or to zero for 1st bucket).
  repeated double negative_counts    = 10; // Absolute count of each bucket.

  // Positive Buckets.
  repeated BucketSpan positive_spans = 11 [(gogoproto.nullable) = false];
  // Use either "positive_deltas" or "positive_counts", the former for
  // regular histograms with integer counts, the latter for float
  // histograms.
  repeated sint64 positive_deltas    = 12; // Count delta of each bucket compared to previous one (or to zero for 1st bucket).
  repeated double positive_counts    = 13; // Absolute count of each bucket.

  enum ResetHint { ... }
  sint32 schema             = 4; 
  double zero_threshold     = 5;
  oneof zero_count { ... }
  ResetHint reset_hint               = 14;
}
```

2. Decide and propose conversion flows e.g. what if new bucket appears across samples. Do we attempt to convert and if yes, with what err tolerance? Do we simply take latest and ignore non matching buckets in single query/query_range? If only one bucket is added/removed, do we attempt to converge to lower resolution?
3. Semantics around mixing / migrating one histogram metric from custom layout to sparse one

Does it make sense? 🤔 @beorn7

**Comment by beorn7** [comment]
I think the conversion from custom buckets to exponential ones will be very problematic. That's why I wouldn't frame the whole effort as a migration tool, but really just as a way to handle the current classic histogram case in a more efficient way. (And of course enabling entirely new use cases that don't match the exponential schema, e.g. importing histograms form 3rd party systems not following the exponential schema or just custom use cases requiring a specific bucket layout.)

The protobuf looks good so far (but there might be a lot of devils in the details, we have to adjust the approach on the go.

On the PromQL side, I think we should just handle cases where a direct conversion is possible (by merging buckets). If you ever run into non-matching buckets, we should better err out than doing something that might give you error margins that are hard to reason about. Maybe we could introduce explicit conversion functions in the future. But the main message should be that you better migrate to the current exponential schema set if you are interested in proper mergeablity.

**Comment by beorn7** [comment]
We now have #13485 , which supersedes this one. Closing.
