### ISSUE TITLE
Open to exposing Status (firing, resolved) in AlertTemplateData?

### ISSUE THREAD

**Issue by callumj** [prometheus/prometheus#11300]
## Proposal
We use an annotation called `Description` that allows engineers to provide guidance on what to do when an alert fires (or resolves). We'd like to allow our engineers to customize the instructions provided in message depending on the state of alert (if resolved, then do something else) which would require access to the state of the rule.

Would this be something accepted by the community and I suspect it might not be immediately straightforward in `Eval()` given alert state is determined elsewhere.

**Comment by roidelapluie** [comment]
Once the alert is resolved, the annotations should no longer be evaluated, so it seems impossible for me.

**Comment by callumj** [comment]
> Once the alert is resolved, the annotations should no longer be evaluated, so it seems impossible for me.

Oh duh, that makes sense. Thanks for the quick reply!
