### ISSUE TITLE
Docker image latest tag switch from 2.38.0 to 2.37.1 after 2.37.1 release

### ISSUE THREAD

**Issue by netsandbox** [prometheus/prometheus#11310]
### What did you do?

When 2.37.1 was released on 2022-09-12, the `latest` tag switched from 2.38.0 to 2.37.1, see https://hub.docker.com/r/prom/prometheus/tags and https://quay.io/repository/prometheus/prometheus?tab=tags.

### What did you expect to see?

The `latest` tag should be 2.38.0.

### What did you see instead? Under which circumstances?

The `latest` tag is 2.37.1.

**Comment by Nexucis** [comment]
yeah I saw that too. There is the same issue for the npm packages.
That never happens before, but now we have LTS version this issue will be there each time. I'm not sure there is an easy solution to fix it excepting checking if the tag is the latest one (in term of version) and if yes, then the image latest should be pushed.
Perhaps there is an easier solution than this one 🤞

**Comment by roidelapluie** [comment]
This has been resolved, the LTS does not push to the latest tag anymore.
