### ISSUE TITLE
Out-of-order post merge cleanup

### ISSUE THREAD

**Issue by codesome** [prometheus/prometheus#11329]
A few TODOs coming out of https://github.com/prometheus/prometheus/pull/11075

- [x] Add documentation for out of order feature and the config (before v2.39)
- [x] Rename the `type WAL` to `type WL` (but the usage retains wal and wbl naming).
- [x] Revisit Head.Appender.Commit() code and try to simplify it.
- [x] Simplify `loadWAL` and `loadWBL` in head_wal.go as much as possible (not directly related to the OOO work, since this structure of code existed before)
- [x] make processWBLSamples and processWALSamples look similar
- [x] Add a fast path for write path by checking the last sample https://github.com/prometheus/prometheus/issues/11329#issuecomment-1305698507
- [x] Some refactor https://github.com/prometheus/prometheus/issues/11329#issuecomment-1305707786

Few having their own issues:
* https://github.com/prometheus/prometheus/issues/11835
* https://github.com/prometheus/prometheus/issues/11836
* https://github.com/prometheus/prometheus/issues/11837

cc @jesusvazquez @bwplotka

**Comment by jesusvazquez** [comment]
> Simplify loadWAL and loadWBL in head_wal.go as much as possible (not directly related to the OOO work, since this structure of code existed before)

As part of this item lets see if we can make processWBLSamples and processWALSamples look similar

**Comment by codesome** [comment]
> > Simplify loadWAL and loadWBL in head_wal.go as much as possible (not directly related to the OOO work, since this structure of code existed before)
> 
> As part of this item lets see if we can make processWBLSamples and processWALSamples look similar

Added it in the issue description

**Comment by codesome** [comment]
I think we have a bug in a metric
https://github.com/prometheus/prometheus/blob/73d805cf6c67cadf8e56d6fb8958d1408be869dc/tsdb/head_append.go#L317-L319
The histogram buckets assume seconds, but here most of the timestamps are going to be milliseconds. So we should be doing `/1000` to satisfy for most cases/

**Comment by jesusvazquez** [comment]
` Rename the type WAL to type WL (but the usage trains wal and wbl naming).` can be marked as completed :+1:

**Comment by jesusvazquez** [comment]
We could optmize the write path by changing the logic here https://github.com/prometheus/prometheus/blob/c1b669bf9b0b1286ece53c977262089119783105/tsdb/ooo_head.go#L42-L46

We could optimistically try to append at the end first unless the last sample timestamp is bigger than the sample we want to insert, in which case we would do what the method does (sort, then append).

**Comment by jesusvazquez** [comment]
Move https://github.com/prometheus/prometheus/blob/3330d85ba8cd6c53e74af23ab96e9e2c134bec39/tsdb/head_read.go#L472-L478 to the ooo_head_read.go file.

**Comment by roidelapluie** [comment]
What happens when Prometheus itself writes OOO?


This is the case in two scenarios:

When a rule is moved from one file to another and the configuration is reloaded. The new rule writes its metric but several evaluation interval later, the first rule writes a staleness marker. In the past, that second happen was rejected and the staleness marker was not written.

https://github.com/prometheus/prometheus/blob/30b31cae93b2fe66486f188c07e215b80ebc93f8/rules/manager.go#L392-L399

The second scenario is when a target is stopped. We also wait a bit and try to insert a staleness marker that is rejected e.g. if the metrics are inserted with a target that has been restarted (e.g. because of a config change).

https://github.com/prometheus/prometheus/blob/30b31cae93b2fe66486f188c07e215b80ebc93f8/scrape/scrape.go#L1409-L1447

**Comment by codesome** [comment]
> What happens when Prometheus itself writes OOO?

TSDB is agnostic to this. If a sample is OOO and within the out_of_order_time_window, it will be added to the TSDB. Regarding the stale sample, if it is added to the TSDB, and then there is another sample later for the series, does that still work fine or the stale sample causes any problems?

**Comment by roidelapluie** [comment]
ideally in that case we should not apply OOO logic. Instead of commit, could we have a special function that bypasses the OOO logic for those 2 cases?

In the case of a target, it would mean that we could "override" a float64 by a stalenan NaN, therefore losing datapoints on some reloads.

**Comment by codesome** [comment]
Yes TSDB could have some interface to allow appending samples without OOO logic. Could you please open an issue for that one so that we can track its progress?

**Comment by fionaliao** [comment]
>  make processWBLSamples and processWALSamples look similar

I'm planning to take this task. I've been working on out or order support for native histograms. Making `processWBLSamples` and `processWALSamples` more similar means that when we extend the WBL with histogram handling, that can be more consistent with the WAL histogram handling.

A few differences between WBL vs WAL that should be updated:

1. A change was made to replay the WAL concurrently without sleeps in https://github.com/prometheus/prometheus/pull/10973. The change wasn't applied to the WBL, so it's still using the old implementation: https://github.com/prometheus/prometheus/blob/db816ce9dbf2768ed2db1619fb2a8b9f9addeae8/tsdb/head_wal.go#L925-L938 
2. A small optimisation was done to the WAL to not send empty buffers to be processed in https://github.com/prometheus/prometheus/pull/11319. This change hasn't been applied to the WBL: https://github.com/prometheus/prometheus/blob/db816ce9dbf2768ed2db1619fb2a8b9f9addeae8/tsdb/head_wal.go#L764-L766
3. For the WBL, we try and reuse sample buffers: https://github.com/prometheus/prometheus/blob/db816ce9dbf2768ed2db1619fb2a8b9f9addeae8/tsdb/head_wal.go#L875-L883. I think buffers are supposed to be sent to `wp.output` after use. As far as I can tell, nothing is ever sent to `wp.output`. As a comparison, for the WAL, buffers are written to `wp.output` here: https://github.com/prometheus/prometheus/blob/db816ce9dbf2768ed2db1619fb2a8b9f9addeae8/tsdb/head_wal.go#L607-L610, and then reused here: https://github.com/prometheus/prometheus/blob/db816ce9dbf2768ed2db1619fb2a8b9f9addeae8/tsdb/head_wal.go#L538-L546.

**Comment by nicolastakashi** [comment]
> Move
> 
> https://github.com/prometheus/prometheus/blob/3330d85ba8cd6c53e74af23ab96e9e2c134bec39/tsdb/head_read.go#L472-L478
> 
> to the ooo_head_read.go file.

It's done

**Comment by alexgreenbank** [comment]
Hello from the bug scrub.

cc: @codesome @jesusvazquez 

Is this issue up to date, are all of the TODOs unchecked still outstanding?

**Comment by jesusvazquez** [comment]
👋 @alexgreenbank I've gone through the code and the issues and I think many have changed since I first listed the TODO actions. I have ticked the pending items since i think they now look very similar.

loadWal and loadWbl were refactord 1 year ago to improve performance and processWALSamples and processWBLSamples now look very similar.
