### ISSUE TITLE
Add the OpenSSF Scorecard GitHub Action

### ISSUE THREAD

**Issue by gabibguti** [prometheus/prometheus#11325]
## Proposal

Hello, I'm working on behalf of Google and the [Open Source Security Foundation][ossf] to help essential open source projects improve their supply-chain security. Given prometheus’ importance to monitoring and alerting, we'd like to recommend an improvement to the projects security posture.

Would you consider adopting an OpenSSF tool called Scorecards? [Scorecards][sc] runs dozens of automated security checks to help maintainers better understand their project's supply-chain security posture. It is developed by the OpenSSF, [in partnership with GitHub][sc-blog].

I see prometheus’ already follows security best practices, such as cryptographic release signing and CI/CD through CircleCI. Adding Scorecards could help ensure other best practices, such as the usage of Token Permissions mentioned in https://github.com/prometheus/prometheus/pull/11285.

The [Scorecard GitHub Action][sc-gha] is very lightweight and runs on each change to the repository. The results of its checks are available on to the project's [security dashboard](https://github.com/<<<USERNAME>>>/<<<REPO_NAME>>>/security), and include suggestions on how to solve any issues (see examples below). Over 1600 projects have added the action already. 

Would you be interested in a PR which adds this Action? Optionally, it can also publish your results to the OpenSSF REST API, which allows a [badge][badge] with the project's score to be added to its README.

-------------------

#### Examples

![Code scanning dashboard with multiple alerts, including Code-Review and Token-Permissions][img-security]

![Detail of a Token-Permissions alert, indicating the specific file and remediation steps][img-detail]

[badge]: https://openssf.org/blog/2022/09/08/show-off-your-security-score-announcing-scorecards-badges/
[ossf]: https://openssf.org/
[ossf-membership]: https://openssf.org/about/members/
[sc]: https://github.com/ossf/scorecard
[sc-blog]: https://github.blog/2022-01-19-reducing-security-risk-oss-actions-opensff-scorecards-v4/
[sc-gha]: https://github.com/ossf/scorecard-action
[img-security]: https://user-images.githubusercontent.com/15221358/190184391-84ca1844-259a-4b3b-9c86-74adadbea7f1.png
[img-detail]: https://user-images.githubusercontent.com/15221358/190184600-ee8d3b39-077e-416a-8711-1b5fb01cf0b3.png

**Comment by roidelapluie** [comment]
It is interesting, feel free to open in a pr.
