### ISSUE TITLE
`GetLabels` and `GetSeries` APIs should return 5xx on internal server error and 4xx for invalid requests

### ISSUE THREAD

**Issue by alanprot** [prometheus/prometheus#11355]
Currently those APIS returns 4xx on all cases.

See for example:

https://github.com/prometheus/prometheus/blob/734772f82824db11344ea3c39a166449d0e7e468/web/api/v1/api.go#L614-L617

https://github.com/prometheus/prometheus/blob/734772f82824db11344ea3c39a166449d0e7e468/web/api/v1/api.go#L1568-L1569

I think this seems a bit weird as 422 is supposed to indicate a problem on a request and that the request should be changed in order to be processed. From the [RFC 9110, 15.5.21](https://www.rfc-editor.org/rfc/rfc9110.html#name-422-unprocessable-content):

> The 422 (Unprocessable Content) status code indicates that the server understands the content type of the request content (hence a [415 (Unsupported Media Type)](https://www.rfc-editor.org/rfc/rfc9110.html#status.415) status code is inappropriate), and the syntax of the request content is correct, but it was unable to process the contained instructions. For example, this status code can be sent if an XML request content contains well-formed (i.e., syntactically correct), but semantically erroneous XML instructions.

This not seems to be the case here.

## Proposal
I believe that the API should return 5xx on cases where the error was not caused by a customer request but most probably by some internal server error.

**Use case. Why is this important?**

Status code should be reliable and indicate the nature of the error. The callers use status code to decided things like retry strategy, etc.

**Comment by bboreham** [comment]
I checked back through the history, and this code seems to have been there since the `labelNames()` function was added in #4835.
https://github.com/prometheus/prometheus/pull/4835/files#diff-315f251cdd7e93fcec1e7e9505744da1d1828f30d2b61d1f4ce963fa26bf1909R398

Did you miss out some part of your issue report?  It seems to me that some errors are the fault of the caller and some are internal to the service.  You seem to be saying only the second kind can happen, which is just as wrong as the code saying only the first kind.

**Comment by alanprot** [comment]
Hi Bryan .. thanks for looking into this..

actually the pr is just wrapping the error with the “returnAPIError” function as it is done on the query apis .. this gives the possibility to return different status codes based on the error type returned by the storage.

**Comment by alanprot** [comment]
@bboreham WDYT?

**Comment by bboreham** [comment]
I think this issue should say something more like "the API should return 5xx when the error was caused by internal server error, and 4xx only when the error was caused by a problem in the request".

**Comment by alanprot** [comment]
@bboreham updated! :D
