### ISSUE TITLE
Text format parser ignoring EOF format error

### ISSUE THREAD

**Issue by zeroware** [prometheus/prometheus#1135]
I wrote a custom exporter and forgot to add a line return `\n` at the end of the file.
Prometheus displayed that my target was healthy but my metrics were not parsed.

This is low priority but we should have some kind of error message.

Note : previous versions of prometheus returned an `EOF` error.

**Comment by fabxc** [comment]
That is probably caused by the new decoder, which in theory supports
streaming. EOF is a signal that the stream is done.
If it happens while parsing a metric, I think the underlying parser should
explicitly state that it is a premature EOF.

**Comment by beorn7** [comment]
Needs updated vendoring to take effect in head.
