### ISSUE TITLE
Enable out of order sample feature via command line flag or --enable-feature

### ISSUE THREAD

**Issue by samkim** [prometheus/prometheus#11354]
## Proposal
**Use case. Why is this important?**
To be able to enable the out of order sample feature on a prometheus instance managed by the prometheus operator.

Currently it looks like the feature is only enabled if the out of order time window value is set in a config file. However, this would require using [custom config](https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/custom-configuration.md#custom-configuration) instead of an operator managed config file.

With either feature specific CLI flags or support for adding via --enable-feature with a default window value, we could enable the functionality while letting the operator continue generating the config file secret.

**Comment by bboreham** [comment]
Hi, I'm not sure I fully understand the problem (I've never used the Prometheus Operator).
Are you saying that Prometheus Operator will never add support for the out-of-order time window in the config?

**Comment by ArthurSens** [comment]
Hey 👋  - Prometheus-Operator maintainer here

It is possible to configure `out_of_order_time_window` using Prometheus-Operator, you can take a look at the [API reference](https://prometheus-operator.dev/docs/operator/api/#monitoring.coreos.com/v1.TSDBSpec) to understand how it looks like :)

With that said, when opening issues related to prometheus-operator, the repository https://github.com/prometheus-operator/prometheus-operator is a better place!
