### ISSUE TITLE
make build | MacOS > 12.6  tar --transform

### ISSUE THREAD

**Issue by MB175** [prometheus/prometheus#11363]
### What did you do?

`make build`

### What did you expect to see?

Binary build process of prometheus with embedded web ui

### What did you see instead? Under which circumstances?

The --transform option is not natively supported on the Mac version of tar

```
find web/ui/node_modules -iname "license*" | tar cfj "npm_licenses.tar.bz2" --transform 's/^/npm_licenses\//' --files-from=-
tar: Option --transform is not supported
Usage:
  List:    tar -tf <archive-filename>
  Extract: tar -xf <archive-filename>
  Create:  tar -cf <archive-filename> [filenames...]
  Help:    tar --help
make: *** [npm_licenses] Error 1
```

### System information

MacOS 12.6

**Comment by MB175** [comment]
Possible workaround could be to require [Gnu-Tar](https://formulae.brew.sh/formula/gnu-tar), no convenient though because the command still would have to be gtar instead of tar

**Comment by Nexucis** [comment]
yeah you will have to use this workaround.
But we could document it somewhere that you need to install it when using MacOS, so people don't loose time to find how to fix it.

**Comment by MB175** [comment]
@Nexucis a OS specific modification to the make file could be made, calling the gtar command. The issue than would be gtar not found, this would somewhat lead users to install gtar.

**Comment by roidelapluie** [comment]
NB if you are on a Mac, you will need gnu-tar.

**Comment by MB175** [comment]
@roidelapluie nice, thanks for pointing out, keep in mind that the make file needs to be modified so it uses gtar

**Comment by roidelapluie** [comment]
Our mac OS users never reported that the commands needs to be changed

**Comment by MB175** [comment]
@roidelapluie okay now I'm confused, I will give it a try again. At least after I installed gtar with brew it did not replace the tar command only add the gtar command. There might be a setting to overload tar with gtar though.

**Comment by Nexucis** [comment]
yeah indeed. I'm not an expert in mac, so I can't assure it won't be an issue. 
But so far replacing the tar mac version by the GNU one doesn't cause me any issue, it's quite the opposite actually I have less issue than before.

**Comment by MB175** [comment]
Would u guys say it's boilerplate if we would just check in the Makefile for example with `ifeq ($(UNAME_S),Darwin)` to check rather to use tar or gtar

**Comment by roidelapluie** [comment]
I think we fixed this https://github.com/prometheus/prometheus/pull/11721 , could you give the solution a try?

**Comment by LeviHarrison** [comment]
Works for me now 👍🏻

**Comment by MB175** [comment]
```
--transform

```
has been removed now, makefile works on macOS 👍🏻
