### ISSUE TITLE
Prometheus should continue to bootstrap go

### ISSUE THREAD

**Issue by StephanErb** [prometheus/prometheus#1136]
Prometheus 15.x used to download go when one was calling `make`, if go was not installed. The latest rc does no longer do that. For me as an end user, this feels like a regression.

**Comment by fabxc** [comment]
What we have done before does no longer work with the official vendoring proposal coming with Go 1.5, which ultimately has features we will need.
The Go tool was actively working against what we have done before – it was merely a hole our approached slipped through and made it work. The Go tool is simply not meant to be used that way. It strongly expects a proper setup of a `$GOPATH`.
The alternative would have been for `make` to move heavily alter your folder structure underneath itself, which is not what a user wants it to do either.

@brian-brazil will agree with you, though.
Personally, I strongly think that setting up a compile environment should never be part of an application's build process. Especially for Go which is as trivial to setup as any interpreter.
Nobody would expect a python or npm package to download and install an interpreter. Everyone is perfectly fine with doing `brew install npm` before (or equivalent). For Go it is `brew install go`.

There is hope though. The `scripts/goenv.sh` script downloads and installs a Go environment for you.
You have to care about setting up a correct folder structure the compiler can work with, though.

It should go something like this. As you can see, just doing a proper Go installation might turn out to be easier.

```
export dir=$HOME/gopath/src/github.com/prometheus/prometheus
mkdir -p $HOME/go $dir
source ./scripts/goenv.sh $HOME/go $dir
cp -r ./* $dir/
cd $dir
make
```

We also provide pre-built binaries.

**Comment by StephanErb** [comment]
I have totally missed that you provide pre-built binaries. They solve the hurdles for me as a enduser. Thanks for your quick reaction!

**Comment by fabxc** [comment]
They admittedly lack visibility on our site and in the repo's README.

**Comment by beorn7** [comment]
We definitely need very visible pointers to binaries and Debian packages everywhere. Official deb's are in Stretch testing. And then there is Brian's stuff.

**Comment by juliusv** [comment]
Not sure I understand, binaries are pointed out under http://prometheus.io/docs/introduction/install/ and https://github.com/prometheus/prometheus/#precompiled-binaries already? Also in http://prometheus.io/docs/introduction/getting_started/.

The debs could be pointed out more, but we don't have ones yet that belong to the project itself, but maybe point to the official Debian and/or Brian ones?

**Comment by fabxc** [comment]
Yes, but it is hidden in text. I guess some big download buttons would be helpful.
That's the first thing I look for when visiting the website of a project I want to try out.

**Comment by juliusv** [comment]
Ah ok - yeah, all for putting it on the frontpage somewhere :)

**Comment by barkerd427** [comment]
Big buttons definitely help. I didn't find them right away either. Chef has
a nice layout for downloads.

**Comment by juliusv** [comment]
Working on a "Download" frontpage button. The question is, we already list different download options on http://prometheus.io/docs/introduction/install/, but I think it might make sense to have a dedicated page just for downloading, similar to http://grafana.org/download/. Maybe even link it like that from the top nav as a button like in Grafana? I'm generally against overloading the top nav, but that might be worth it, and stylistically, it stands out enough from the rest of the menu in the right way, IMO.

**Comment by barkerd427** [comment]
That would be helpful. Thank you.

**Comment by juliusv** [comment]
Heh - of course Prometheus is a bit more complicated in the respect that it has a many components we offer downloads for (and in different ways), so will have to think a bit how to structure that.

**Comment by barkerd427** [comment]
Just getting a dedicated download page with a button on the front page will
be a huge improvement. Set the Prometheus binaries at the top with download
buttons or a selector of some type. The other components could just be
links to the current docs for the first iteration. I'm more likely to
upgrade Prometheus than the other pieces.
