### ISSUE TITLE
RemoteWrite to aws with just role_arn doesn't work

### ISSUE THREAD

**Issue by KavyaShree25** [prometheus/prometheus#11360]
### What did you do?

Configured a remote write to aws 

remote_write:
   url: "https://aps-workspaces.us-east-1.amazonaws.com/workspaces/wsID/api/v1/remote_write"
   sigv4:
       region: us-east-1
       role_arn: <assumed role>

This doesn't seem to work

### What did you see instead? Under which circumstances?

caller=main.go:1203 level=error msg="Failed to apply configuration" err="could not get SigV4 credentials: NoCredentialProviders: no valid providers in chain. Deprecated.\n\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors"

**Comment by alazets** [comment]
hey, any chance to get the answer?
