### ISSUE TITLE
Reduce default overhead of out-of-order feature when not enabled

### ISSUE THREAD

**Issue by codesome** [prometheus/prometheus#11399]
Currently we are allocating space for these 3 variables for all series even if out-of-order ingestion is not enabled.

https://github.com/prometheus/prometheus/blob/04dd6be1a0f14b77c78199f4ab502d70207fdee8/tsdb/head.go#L1798-L1800

We can improve this situation by putting it inside a struct and replacing these 3 variables by a pointer. (We can re-use the new struct for [this](https://github.com/prometheus/prometheus/blob/04dd6be1a0f14b77c78199f4ab502d70207fdee8/tsdb/head.go#L1794-L1796) as well)

**Comment by bboreham** [comment]
This was done in #11779
