### ISSUE TITLE
missing labels on alerts

### ISSUE THREAD

**Issue by roastiek** [prometheus/prometheus#11424]
### What did you do?

upgrade form 2.38.0 to 2.39.0

### What did you see instead? Under which circumstances?

Alerts are missing n last labels after second firing evaluation. Probably happens only on instances with external labels.

I did some debuging and found out the breaking commit #11147.

The cause lies here https://github.com/prometheus/prometheus/blob/8ed39fdab1ead382a354e45ded999eb3610f8d5f/notifier/notifier.go#L364

It reuse labels that are shared with `AlertingRule.active` alerts.

### System information

Linux

### Prometheus version

```text
prometheus, version 2.39.0
```

**Comment by roidelapluie** [comment]
cc @codesome @bboreham

**Comment by codesome** [comment]
I am trying to reproduce it by having external labels on the notifier and sending the alert from the AlertingRule but I am not able reproduce it yet. @roastiek do you have any examples of labels on alerts and external labels that is causing this bug?

**Comment by codesome** [comment]
With reproducing of error aside, would you be willing to try a patch with changing `a.Labels = lb.Labels(a.Labels)` to `a.Labels = lb.Labels(nil)` at the line that you pointed out?

**Comment by codesome** [comment]
On another look, I am suspecting it is some bug in `model/relabel/relabel.go` file. Checking.

**Comment by roastiek** [comment]
Ii happens to alerts with 8 or more labels.

On https://github.com/prometheus/prometheus/blob/8ed39fdab1ead382a354e45ded999eb3610f8d5f/cmd/prometheus/main.go#L1285 is the shared reference created.

And yes `a.Labels = lb.Labels(nil)` is one way of fixing it.

**Comment by douglascamata** [comment]
Related: #11426

**Comment by douglascamata** [comment]
> On another look, I am suspecting it is some bug in model/relabel/relabel.go file. Checking.

@codesome check my PR at #11426. I have a passing test showing that `rebabel.Process` effectively modifies the input label slice when the optimizations of #11147 are triggered.

**Comment by douglascamata** [comment]
Oh, actually my test doesn't test what I want, but I see the issue 😂

**Comment by douglascamata** [comment]
Ugh, seems like target label is mandatory. So my bad. 🤔

**Comment by codesome** [comment]
Fixed in https://github.com/prometheus/prometheus/pull/11427. Fix is available in v2.39.1.

**Comment by bboreham** [comment]
Thanks Ganesh.
