### ISSUE TITLE
PromQL: at midnight, day_of_month() returns wrong date

### ISSUE THREAD

**Issue by fschlich** [prometheus/prometheus#11432]
### What did you do?

I'm trying to tag my metrics with a date in the form YYYY-MM-DD. For this I use the year(), month() and day_of_month() functions like so:
```
up{instance="130.73.242.147:6443"}
+ ignoring(year, month, day) group_right
    count_values without() ("year", year(timestamp(
        count_values without() ("month", month(timestamp(
            count_values without() ("day", day_of_month(timestamp(
                up{instance="130.73.242.147:6443"}
            )))
        )))
    )))
 *0
```

### What did you expect to see?

For October 1 at midnight, I expect to see `2022-10-1`

### What did you see instead? Under which circumstances?

what I actually get is `2022-10-30` - the day_of_month() value is from a second earlier:

![prometheus-day_of_month-error](https://user-images.githubusercontent.com/1262986/194612846-d8e54f04-90d3-48ef-8f30-080fbb39d5ce.png)

### System information

Linux 5.10.0-18-amd64 x86_64

### Prometheus version

```text
Version	2.39.0
Revision	6d7f26c46ff70286944991f95d791dff03174eea
Branch	HEAD
BuildUser	root@bc053716806f
BuildDate	20221005-05:09:43
GoVersion	go1.19.1

(kube-prometheus-stack helm chart version 40.5.0, but I can see this on 2.37.0 as well)
```

**Comment by fschlich** [comment]
I just notice that this is a more general issue, only that it's not so apparent when it's not the turn of the month (where the entire expression creates dates far in the future).

It seems that the old day's date is returned for every day at midnight, and for a few seconds after that as well. In my limited testing, in the opinion of `day_of_month()` the new day seems to start at 00:00:13

**Comment by roidelapluie** [comment]
It looks like you are attempting to use the `timestamp()` function multiple times in a row, chaining it with various date-related functions such as `year()`, `month()`, and `day_of_month()`.

It's important to note that the `timestamp()` function should only be used directly with a metric selector, such as `up{instance="130.73.242.147:6443"}`. When used in this way, it will return the timestamp of the metric. However, when it is chained with other functions as in your query, it will instead use the current step timestamp, which probably is not what you want.

You could try:

```
count_values("year",year(timestamp(up))) + ignoring(day,year) group_right(year) count_values("day",day_of_month(timestamp(up))) + ignoring(day,year,month) group_right(day,year) count_values("month",month(timestamp(up)))
```

*Note: Generated with the help of chatgpt*

**Comment by roidelapluie** [comment]
Feel free to reopen if you have further questions.

**Comment by fschlich** [comment]
Hi @roidelapluie, 
thanks for looking at this issue. What you suggest to try is in fact a solution to my problem, although it took me a while to understand why. The discussion in #8966 was especially helpful.

I must say it's surprising to learn that a PromQL function can change the timestamp of a sample, if only by one scrape_interval or so. This needs to be documented! Some mention at https://prometheus.io/docs/prometheus/latest/querying/functions/#timestamp would probably be useful, given that the Internet is full of people using the chained approach, e.g. when searching 'prometheus aggregate monthly':
* (https://sysrant.com/posts/monthly-reports-with-grafana-and-prometheus/
* https://stackoverflow.com/questions/52175218/group-data-by-year-month-day-in-prometheus
* https://groups.google.com/g/prometheus-developers/c/pul4HF4OS0E
