### ISSUE TITLE
Bring CLOMonitor Score to 100%

### ISSUE THREAD

**Issue by eddie-knight** [prometheus/prometheus#11462]
Prometheus is signed up as part of the KubeCon [Security Slam](https://events.linuxfoundation.org/kubecon-cloudnativecon-north-america/attend/experiences/#security-slam), so I just grabbed the checklist for this repo from the official [CLOMonitor page for Prometheus](https://clomonitor.io/projects/cncf/prometheus) and put it here to track the work required. It refreshes every hour, so this should be up-to-date.

The only checks that immediately matter as part of the Security Slam are the ones in the security category below.

### Summary

**Repository**: prometheus
**URL**: https://github.com/prometheus/prometheus
**Checks sets**:  `COMMUNITY` + `CODE`
**Score**: 80

### Checks passed per category

| Category  |  Score  |
| :----------------- | --------: |
|  Documentation  |  83%  |
|  License  |  75%  |
|  Best Practices  |  80%  |
|  Security  |  75%  |
|  Legal  |  100%  |

### Documentation [83%]

  - [ ] Adopters ([_docs_](https://clomonitor.io/docs/topics/checks/#adopters))
  - [x] [Changelog](https://github.com/prometheus/prometheus/blob/main/CHANGELOG.md) ([_docs_](https://clomonitor.io/docs/topics/checks/#changelog))
  - [x] [Code of conduct](https://github.com/prometheus/prometheus/blob/main/CODE_OF_CONDUCT.md) ([_docs_](https://clomonitor.io/docs/topics/checks/#code_of_conduct))
  - [x] [Contributing](https://github.com/prometheus/prometheus/blob/main/CONTRIBUTING.md) ([_docs_](https://clomonitor.io/docs/topics/checks/#contributing))
  - [ ] Governance ([_docs_](https://clomonitor.io/docs/topics/checks/#governance))
  - [x] [Maintainers](https://github.com/prometheus/prometheus/blob/main/MAINTAINERS.md) ([_docs_](https://clomonitor.io/docs/topics/checks/#maintainers))
  - [x] [Readme](https://github.com/prometheus/prometheus/blob/main/README.md) ([_docs_](https://clomonitor.io/docs/topics/checks/#readme))
  - [ ] Roadmap ([_docs_](https://clomonitor.io/docs/topics/checks/#roadmap))
  - [x] [Website](https://prometheus.io/) ([_docs_](https://clomonitor.io/docs/topics/checks/#website))
  
### License [75%]

  - [x] Apache-2.0 ([_docs_](https://clomonitor.io/docs/topics/checks/#license_spdx_id))
  - [x] Approved license ([_docs_](https://clomonitor.io/docs/topics/checks/#license_approved))
  - [ ] License scanning ([_docs_](https://clomonitor.io/docs/topics/checks/#license_scanning))
  
### Best Practices [80%]

  - [x] Analytics ([_docs_](https://clomonitor.io/docs/topics/checks/#analytics))
  - [ ] Artifact Hub badge ([_docs_](https://clomonitor.io/docs/topics/checks/#artifacthub_badge))
  - [x] Contributor License Agreement ([_docs_](https://clomonitor.io/docs/topics/checks/#cla)) `EXEMPT`
  - [ ] Community meeting ([_docs_](https://clomonitor.io/docs/topics/checks/#community_meeting))
  - [x] Developer Certificate of Origin ([_docs_](https://clomonitor.io/docs/topics/checks/#dco))
  - [x] [Github discussions](https://github.com/prometheus/prometheus/discussions/11443) ([_docs_](https://clomonitor.io/docs/topics/checks/#github_discussions))
  - [x] [OpenSSF badge](https://bestpractices.coreinfrastructure.org/projects/486) ([_docs_](https://clomonitor.io/docs/topics/checks/#openssf_badge))
  - [x] [Recent release](https://github.com/prometheus/prometheus/releases/tag/v2.36.2) ([_docs_](https://clomonitor.io/docs/topics/checks/#recent_release))
  - [x] Slack precense ([_docs_](https://clomonitor.io/docs/topics/checks/#slack_presence)) `EXEMPT`
  
### Security [75%]

  - [x] Binary artifacts ([_docs_](https://clomonitor.io/docs/topics/checks/#binary_artifacts))
  - [x] Code review ([_docs_](https://clomonitor.io/docs/topics/checks/#code_review))
  - [x] Dangerous workflow ([_docs_](https://clomonitor.io/docs/topics/checks/#dangerous_workflow))
  - [x] Dependency update tool ([_docs_](https://clomonitor.io/docs/topics/checks/#dependency_update_tool))
  - [x] Maintained ([_docs_](https://clomonitor.io/docs/topics/checks/#maintained))
  - [ ] Software bill of materials (SBOM) ([_docs_](https://clomonitor.io/docs/topics/checks/#sbom))
  - [x] [Security policy](https://github.com/prometheus/prometheus/blob/main/SECURITY.md) ([_docs_](https://clomonitor.io/docs/topics/checks/#security_policy))
  - [ ] Signed releases ([_docs_](https://clomonitor.io/docs/topics/checks/#signed_releases))
  - [ ] Token permissions ([_docs_](https://clomonitor.io/docs/topics/checks/#token_permissions))
  
### Legal [100%]

  - [x] Trademark disclaimer ([_docs_](https://clomonitor.io/docs/topics/checks/#trademark_disclaimer))
  
For more information about the checks sets available and how each of the checks work, please see the [CLOMonitor's documentation](https://clomonitor.io/docs/topics/checks/).

**Comment by sandipanpanda** [comment]
Hi @LeviHarrison can you let me know if anyone is currently working on `Signed releases` ([docs](https://clomonitor.io/docs/topics/checks/#signed_releases)) and `Software bill of materials (SBOM)` ([docs](https://clomonitor.io/docs/topics/checks/#sbom))? If not, I would like to help in implementing `signing Prometheus container images` and `SBOM generation`.

**Comment by udf2457** [comment]
Very keen to see SLSA releases from Prometheus !

Useful links:
https://docs.sigstore.dev/signing/overview/
https://github.com/slsa-framework/slsa-github-generator/blob/main/internal/builders/generic/README.md#provenance-for-goreleaser
https://goreleaser.com/blog/slsa-generation-for-your-artifacts/#slsa-github-generator

**Comment by beorn7** [comment]
Hello from the bug scrub!

Increasing the CLOMonitor Score sounds like a good thing to have. We will appreciate PRs addressing issues exposed by the score. However, having an additional issue to track what is already tracked on the scoring site isn't making much of a difference. Thus, we are closing this issue, but explicitly not to discourage contributions aimed at improving the score.
