### ISSUE TITLE
Metrics for head_chunks and wal folders

### ISSUE THREAD

**Issue by whitepiratebaku** [prometheus/prometheus#11478]
### Proposal

Prometheus has 3 main storage consumers, blocks, head_chunks and wal. We have metric to show the size of blocks on disk but not for head_chunks, wal. I wonder is there possibility to add? or maybe it can be calculated with existing metrics?

**Comment by roidelapluie** [comment]
cc @codesome

**Comment by codesome** [comment]
If they are helpful, we can add them :) PRs are welcome.

**Comment by Kaushal28** [comment]
@codesome  I would like to contribute here, can you please provide me with some more details if you have or any entry point from where I can start? Thanks.

**Comment by fbegyn** [comment]
I'll take a shot at this over the weekend.
