### ISSUE TITLE
Graph and query result mismatch

### ISSUE THREAD

**Issue by devatkc** [prometheus/prometheus#11495]
### What did you do?

Query data on Prometheus expression browser.

Result:
![image](https://user-images.githubusercontent.com/70131156/198175875-42ca5719-d322-4522-b2c8-6a9d246a3175.png)

Graph:
![image](https://user-images.githubusercontent.com/70131156/198176035-7c491177-2228-44ac-a9ba-f54d8d221a07.png)

### What did you expect to see?

Graph should match query result data.

### What did you see instead? Under which circumstances?

Query result shows the timestamp of last data point is "1666836820" (which is 2022-10-27 2:13:40 +00:00, in a readable format), but on graph, the last data point has timestamp "2022-10-27 02:18:38 +00:00", why graph has more data than query result? 

### System information

Windows 11 Pro 22000.1098 | Docker Desktop 4.12.0 (85629)

### Prometheus version

```text
prometheus, version 2.39.1 (branch: HEAD, revision: dcd6af9e0d56165c6f5c64ebbc1fae798d24933a)
  build user:       root@273d60c69592
  build date:       20221007-15:57:09
  go version:       go1.19.2
  platform:         linux/amd64
```

### Prometheus configuration file

```yaml
scrape_configs:
  - job_name: telegraf
    static_configs:
      - targets: ['telegraf.local:9273']
```

### Alertmanager version

```text
N/A
```

### Alertmanager configuration file

```yaml
N/A
```

### Logs

```text
N/A
```

**Comment by roidelapluie** [comment]
The graph view does not show you the data points. It shows you the value at every step.

**Comment by roidelapluie** [comment]
The data points in the graph is the step 2022-10-27 02:18:38. At that moment, pormetheus looks 5 minutes in the past and find the 2022-10-27 2:13:40 datapoint.
