### ISSUE TITLE
Proposal: add the equivalent of "relabel_configs" *after* the scraping

### ISSUE THREAD

**Issue by jaepetto** [prometheus/prometheus#11499]
### Proposal

As per your [documentation](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#relabel_config) and some questions on [StackOverflow](https://stackoverflow.com/questions/66500444/apply-prometheus-metric-relabelling-after-rules), it appears that the "relabel_configs" is evaluated before the scraping actually takes place.

It is really useful in cases like the use of the blackbox exporter.

However, it would be equally useful to re-write labels after the scraping actually takes place. I know at least 2 two use cases where it would be useful:

- when using the blackbox exporter, the name of the endpoint becomes the address of the blackbox exporter (e.g. `http://<blackbox>:9115`). It would be nice to be able to put the `__param_target` back as instance
- when using blackbox exporter into a docker container. The blackbox exporter may be named `anything` (the name of the service) in a docker-compose, while this `<anything>` is not available from the host. Again, it would be nice to be able to compose a new instance name that is accessible from the host.

Would it be possible to have another set of `relabel_configs` that runs after the actual scrape?

**Comment by britcey** [comment]
I believe you're describing metric_relabel_configs

https://prometheus.io/docs/prometheus/latest/configuration/configuration/#metric_relabel_configs

"Metric relabeling is applied to samples as the last step before ingestion. It has the same configuration format and actions as target relabeling. Metric relabeling does not apply to automatically generated timeseries such as up."

**Comment by dominicmarino** [comment]
I think that this is covered by `metric_relabel_configs`

**Comment by jaepetto** [comment]
@britcey @dominicmarino : Thanks for your really quick reply. You are absolutely right. I was describing `metric_label_configs`. I missed it in the documentation.
