### ISSUE TITLE
Allow discovery of terminating condition for kubernetes-sd endpointslice

### ISSUE THREAD

**Issue by hanikesn** [prometheus/prometheus#11507]
### Proposal

Currently the endpoints and endpointslice role differ in behavior when a pod is in terminating state: For endpoint objects pods are removed as soon as the pod enters the terminating state [1], while for endpointslice these will be marked as condition: terminating.

Currently there's no way to discover the terminating condition, which means it's unavoidable to scrape pods in terminating condition. Quite some service don't respond to the metrics endpoint at that point anymore making scrape failures unavoidable.

I suggest to always expose the terminating condition with a separate label so people can restore the old behavior.

[1] https://cloud.google.com/blog/products/containers-kubernetes/kubernetes-best-practices-terminating-with-grace
[2] https://kubernetes.io/docs/concepts/services-networking/endpoint-slices/#conditions

**Comment by roidelapluie** [comment]
Looking at the doc we would need to add extra meta labels, it sounds good to me. Probably we want to match the yaml and have different labels for each condition.

**Comment by hanikesn** [comment]
I think #10257 might be related as well. At least it can cause similar issues of scraping pods mistakenly.

**Comment by Bhargavram3468** [comment]
Hi, 

I have similar issue, when we are migrating from one version of own nodeexporter to another version, we have observed in endpoints ---> the pod ip of old version is tagged to new version of port number in kubectl get endpoints, and after some time the new pod ip is updated successfully. So do you have any idea of resolving the issue. 

For clear understanding: 
old pod ip starts with 10.xx.xx.xx:9690
new pod Ip starts with 192.XX.XX.XX:9100
but Iam getting 10.XX.XX.XX:9100 for some time.

**Comment by petergood** [comment]
I would like to claim this issue - I am working on a solution.
