### ISSUE TITLE
docs: Make it clearer that regexps are always fully anchored

### ISSUE THREAD

**Issue by aSemy** [prometheus/prometheus#11526]
### What did you do?

I have a metric with a label. The label name is long, and I want to replace it with a shorter one.

```
feign_Client_seconds_max{application="my-backend", client="my.application.has.a.long.package.name.FeignClient", method="getInfo", uri="/rest/{blah}/something/{else}"}
```

I have written a regex that correctly matches `FeignClient` from the 'client' label: `([^\.]+)$`

I have tested this regex online, and it works correctly: https://regex101.com/r/E5rpSs/1

However, when I try entering this regex into Prometheus, I do not get any message at all. Prometheus just ignores the [label_replace](https://prometheus.io/docs/prometheus/latest/querying/functions/#label_replace) function and returns the data as if I hadn't done anything.

```
label_replace(feign_Client_seconds_max, "client_name", "$1", "client", "([^\\.]+)$")
```

```
feign_Client_seconds_max{application="my-backend", client="my.application.has.a.long.package.name.FeignClient", method="getInfo", uri="/rest/{blah}/something/{else}"}
```

### What did you expect to see?

```
feign_Client_seconds_max{application="my-backend", client_name="FeignClient", method="getInfo", uri="/rest/{blah}/something/{else}"}
```

### What did you see instead? Under which circumstances?

```
feign_Client_seconds_max{application="my-backend", client="my.application.has.a.long.package.name.FeignClient", method="getInfo", uri="/rest/{blah}/something/{else}"}
```

### System information

n/a

### Prometheus version

```text
Docker Prometheus v2.39.1
```

### Prometheus configuration file

```yaml
n/a
```

### Alertmanager version

```text
n/a
```

### Alertmanager configuration file

```yaml
n/a
```

### Logs

```text
n/a
```

**Comment by prymitive** [comment]
From https://prometheus.io/docs/prometheus/latest/querying/basics/:

`Regex matches are fully anchored. A match of env=~"foo" is treated as env=~"^foo$".`

So when you write `"([^\\.]+)$"` prometheus will actually use `"^([^\\.]+)$$"`.

**Comment by aSemy** [comment]
> From https://prometheus.io/docs/prometheus/latest/querying/basics/:
> 
> `Regex matches are fully anchored. A match of env=~"foo" is treated as env=~"^foo$".`
> 
> So when you write `"([^\\.]+)$"` prometheus will actually use `"^([^\\.]+)$$"`.

Thanks, I'll try that. But those docs only look like they're for label matching, not for functions like `label_replace()`.

It would be helpful to have a specific section in the docs, with a header that can be linked to. It would be more visible if there's a specific 'regex' section in the TOC, and also where regexes are mentioned in other docs, they contain a link directly to the relevant section.

**Comment by rynkat** [comment]
I'd like to work on this
