### ISSUE TITLE
/etc/defaults/prometheus is being ignored

### ISSUE THREAD

**Issue by yacoob** [prometheus/prometheus#1153]
As far as I can tell, the startup script doesn't seem to use variables defined in `/etc/defaults/prometheus`. FWIW, this is as observed in deb package made by @brian-brazil, ver `0.16.0rc2-nightly20151008-051722`.

**Comment by brian-brazil** [comment]
That's a 3rd party script maintained by my company, and not a part of the Prometheus project. I'll talk to you offline, but it definitely works for me:

https://github.com/RobustPerception/demo_prometheus_ansible/blob/master/roles/prometheus/tasks/main.yml#L14
