### ISSUE TITLE
"Top 10 label names with high memory usage" is misleading

### ISSUE THREAD

**Issue by bboreham** [prometheus/prometheus#11530]
### What did you do?

Looked at "Top 10 label names with high memory usage" in a Prometheus with 28GB of Go heap, where a profile shows me that 31% of the memory (8.7GB) is in labels.

### What did you expect to see?

Numbers showing several GB of usage.

### What did you see instead? Under which circumstances?

Numbers totalling 11MB.

Name | Bytes
-- | --
id | 2866166
name | 2497605
path | 1481937
container_id | 1076845
filename | 919418
instance | 627711
exported_pod | 565466
device_name | 546763
mountpoint | 511269
uid | 500512

The problem is that, per the docs, "Memory usage is calculated by adding the length of all values for a given label name", which means each unique value is added once, but internally Prometheus stores the name and the value independently for each series.

### Prometheus version

```text
2.39.1
```

**Comment by roidelapluie** [comment]
There is no limit on label values. There are users who pass the entirety of `ps -ef` as label values. In those cases, this is useful.

**Comment by bboreham** [comment]
Wouldn’t it be more useful if it calculated the actual memory usage?

Alternatively, we could have different text for the heading, to match the current calculation. 
“Bytes used by unique values for labels”?
“Top 10 labels in index”?

**Comment by roidelapluie** [comment]
Yes if there is an easy fix to correct the calculation it would be great
