### ISSUE TITLE
Panic during WAL replay after downgrading from 0.39.1 to 0.38.0

### ISSUE THREAD

**Issue by npordash** [prometheus/prometheus#11538]
### What did you do?

We downgraded a tsdb from version 0.39.1 to 0.38.0. It's important to note that the memory-snapshot-on-shutdown feature is enabled.

_For some additional context: we import tsdb as a library similar to projects like Thanos, Cortex, and Mimir._

### What did you expect to see?

TSDB should restart successfully after downgrading.

### What did you see instead? Under which circumstances?

We encounter this panic during WAL replay:
```
panic: runtime error: integer divide by zero

goroutine 299 [running]:
github.com/prometheus/prometheus/tsdb.rangeForTimestamp(...)
	/go/pkg/mod/github.com/prometheus/prometheus@v0.38.0/tsdb/db.go:1643
github.com/prometheus/prometheus/tsdb.(*memSeries).cutNewHeadChunk(0xc181294a20, 0x18444cb5382, 0xc0541d0710?)
	/go/pkg/mod/github.com/prometheus/prometheus@v0.38.0/tsdb/head_append.go:644 +0x1b2
github.com/prometheus/prometheus/tsdb.(*memSeries).append(0xc181294a20, 0x18444cb5382, 0x3ff0000000000000, 0x0, 0xc1953c3bc0?)
	/go/pkg/mod/github.com/prometheus/prometheus@v0.38.0/tsdb/head_append.go:601 +0x1c5
github.com/prometheus/prometheus/tsdb.(*walSubsetProcessor).processWALSamples(0xc00111e9a8, 0xc00014ae00)
	/go/pkg/mod/github.com/prometheus/prometheus@v0.38.0/tsdb/head_wal.go:449 +0x357
github.com/prometheus/prometheus/tsdb.(*Head).loadWAL.func7(0xc1a4bd7fa0?)
	/go/pkg/mod/github.com/prometheus/prometheus@v0.38.0/tsdb/head_wal.go:110 +0x2f
created by github.com/prometheus/prometheus/tsdb.(*Head).loadWAL
	/go/pkg/mod/github.com/prometheus/prometheus@v0.38.0/tsdb/head_wal.go:109 +0x405
```

I did some digging and I believe the cause for this is due to [this change](https://github.com/prometheus/prometheus/commit/d0607435a29b542a03d5c83f89cf17f0447ecacf#diff-e55e448a1ce649167194e1ced19ab2009f422ad678011e333414b8de8e62d311R790), since versions prior to `0.39.0` are assuming that `chunkRange` can never be `0`, which makes sense.

I'm not sure if this is worth fixing or not considering the memory snapshot stuff is still considered experimental. If there is actually a use-case where a downgrade is needed all you have to do is disable the feature or delete the chunk snapshot directory.

**Comment by roidelapluie** [comment]
Since memory snapshot is experimental, and we promise that you can upgrade prometheus without breakage, not downgrade, we should not fix this.

But, we would need to add a note to the 2.39 release that users using that features will not be able to downgrade.

**Comment by alexgreenbank** [comment]
Hello from the bug scrub.

Apologies for the time to look at this.

Closing this as too much time has passed and the moment for adding a note has gone.
