### ISSUE TITLE
Host metrics 

### ISSUE THREAD

**Issue by woot3d** [prometheus/prometheus#11541]
### What did you do?

I collected all host metrics via the node exporter and did not found custom networking metrics for the host especially routes ones

### What did you expect to see?

Routes metrics for the available routes on the host as well as the type of those routes

### What did you see instead? Under which circumstances?

Missing routes metrics

### System information

Linux 4.15.0-166-generic x86_64

**Comment by roidelapluie** [comment]
You have to enable that with the flag `--collector.network_route`.
