### ISSUE TITLE
Latest Docker container for armv7 breaks with 64-bit related error

### ISSUE THREAD

**Issue by Pierric82** [prometheus/prometheus#11554]
### What did you do?

I did nothing but WatchTower pulled the latest image for prom/prometheus for my system and recreated my prometheus container with that image. This was during the early hours of the 7th of November.

### What did you expect to see?

Everything working as previously.

### What did you see instead? Under which circumstances?

Prometheus was down.

I apologise for not having the detailed logs at hand anymore, as I have reverted to the previous version of the image without saving them. However, the logs were showing an error that started with:
`panic: unaligned 64-bit atomic operation`

This rings an alarm bell for me, as my system is armv7, it's a raspberry pi 4, however the OS is not running as 64bit. The image for this architecture should therefore be 32-bit exclusively.

After reverting to the previous version, it's working again, however I've lost all the historical data from the previous months.

### System information

Linux 5.10.103-v7l+ armv7l

### Prometheus version

```text
Since I've reverted to the previous version, I'll enter the details about the Docker image that was failing:

sha256:011839df910c756d2c002b96747b16b0f7a5224c4f3956ee54988aa9e0faea17
205.9 MB
2022-11-07 19:45:35
Docker 20.10.20+azure-1 on linux, arm
```

**Comment by roidelapluie** [comment]
Fix is ready in #11547
