### ISSUE TITLE
Request to have #11317 added to v2.37.X LTS version

### ISSUE THREAD

**Issue by mkoreneff** [prometheus/prometheus#11563]
### Proposal

The fixes in #11317 released in v2.39.0-rc.0 are super useful; is it possible to backport this bugfix into a LTS release?

**Comment by roidelapluie** [comment]
It is planned but I want to take the time to review and give more airtime to this fix before backporting it. It is very likely that this is an issue since Prometheus 2.17.

**Comment by mkoreneff** [comment]
Great, thanks!

**Comment by roidelapluie** [comment]
This has been backported in 2.37.3
