### ISSUE TITLE
 sha256sums.txt is missing hashes for source files

### ISSUE THREAD

**Issue by mq2195** [prometheus/prometheus#11567]
### What did you do?

1. open file sha256sums.txt
2. look for hash for source files
![image](https://user-images.githubusercontent.com/54117541/201177162-dc5f9eb4-a538-408b-8982-39f5a2b61b35.png)

I want to compile prometheus from source (in automated way) and without hash there is no way to verify integrity of the file with sources.

### What did you expect to see?

(with correct hash ofcourse)
![image](https://user-images.githubusercontent.com/54117541/201177779-1f60b86a-6cb5-4e54-8ad2-7522d41bc967.png)

### What did you see instead? Under which circumstances?

-

### System information

n/a

### Prometheus version

```text
2.40.1 / 2022-11-09
```

**Comment by roidelapluie** [comment]
The source file is generated by GitHub, not by our CI. We can not generate a hash if we do not generate the file.
