### ISSUE TITLE
Improve staleness handling for series with explicit timestamps

### ISSUE THREAD

**Issue by jan--f** [prometheus/prometheus#11565]
### Proposal

When staleness was improved for 2.0, any series that are ingested with explicit timestamps are explicitly excluded from the functionality.
From what I understand this was done because:

- The improved staleness handling is implemented by appending a magic value to any series, that has not been seen in 4 scrape intervals (it either vanished from the endpoint or the scrape failed).
- With explicit timestamps the following situation can happen:
  - A sample `metric 1 1` is ingested at time 2.
  - The scrape fails for 4 scrape intervals, so a stale marker would be added with timestamp 6.
  - At time 7 a sample `metric 2 5` is scraped.
- This requires out-of-order ingestion, which was not possible until recently.

Since out-of-order samples can now be ingested I'd like to propose to extend the improved staleness handling to series with explicit timestamps.

This would improve use cases where explicit timestamps can cause issues, e.g. cAdvisor. See also https://github.com/prometheus-operator/kube-prometheus/pull/695 and https://github.com/google/cadvisor/issues/2526.

I"m sure I'm missing some explicit timestamps use cases, but I think the time is right to at least discuss this.

**Comment by roidelapluie** [comment]
Your assumption is wrong. It was removed. We ingest the staleness marker as soon as a metric disappear.

**Comment by roidelapluie** [comment]
> The improved staleness handling is implemented by appending a magic value to any series, that has not been seen in 4 scrape intervals (it either vanished from the endpoint or the scrape failed).


This is not the case. We do not do this anymore. Therefore I can't see how we could do staleness markers on timestamped metrics.

**Comment by jan--f** [comment]
> This is not the case. We do not do this anymore. Therefore I can't see how we could do staleness markers on timestamped metrics.

I have admittedly only looked at `scrape/scrape.go` but there are a few places where stale markers are handled, e.g. in 
https://github.com/prometheus/prometheus/blob/42633bd05ca4d718d52503c1f334c299cdb6fe37/scrape/scrape.go#L1387

I'll look a bit close, but would appreciate any pointers.

**Comment by roidelapluie** [comment]
What happens in scrape.go is that we set the staleness when we do not see some metrics. Or, when we stop scraping a target, we retroactively add staleness markers, but we wait 2 scrape interval, in case the missing metrics are appended in the meantime by another target. In which case the staleness marker is rejected because it is ooo.

**Comment by roidelapluie** [comment]
This is it

Le lun. 22 mai 2023, 14:52, Bryan Boreham ***@***.***> a
écrit :

**Comment by roidelapluie** [comment]
https://github.com/prometheus/prometheus/pull/13060

**Comment by SuperQ** [comment]
Cherry-pick into 2.48: https://github.com/prometheus/prometheus/pull/13066

**Comment by bboreham** [comment]
Someone asked me about this: 

> > The improved staleness handling is implemented by appending a magic value to any series, that has not been seen in 4 scrape intervals (it either vanished from the endpoint or the scrape failed).

> This is not the case. We do not do this anymore. 

I could not find any evidence that staleness ever waited 4 scrape intervals.  The current code contains a comment from 2017 where 2 scrapes are cited, and as far as I can see that was from the first implementation of staleness.
https://github.com/prometheus/prometheus/blame/bfaa0a319cec/scrape/scrape.go#L1375
