### ISSUE TITLE
Dark Background with Black text in dark mode - Graph

### ISSUE THREAD

**Issue by grimz-ly** [prometheus/prometheus#11568]
### What did you do?

updated container image to version 40.1 and hit web interface to test

### What did you expect to see?

basically what I've seen all along. construct a promql query, execute it, and see results

### What did you see instead? Under which circumstances?

all appears OK, but the text color of any metric in the query is black against the dark background in the text box. search boxes in other views have change text to white so only Graph appears affected. The text is still white in v39.2

### System information

Linux 4.15.0-194-generic x86_64

### Prometheus version

```text
prometheus, version 2.40.1 (branch: HEAD, revision: 965274259f993801d63f553639d248588287120b)
  build user:       root@d020f7085e1e
  build date:       20221109-14:30:50
  go version:       go1.19.3
  platform:         linux/amd64
```

**Comment by roidelapluie** [comment]
Can you share a screenshot?

**Comment by grimz-ly** [comment]
<img width="1128" alt="prom_dark" src="https://user-images.githubusercontent.com/74379877/201358128-895b5dcf-fc08-4644-9e78-879341223236.png">

**Comment by roidelapluie** [comment]
Cc @juliusv @Nexucis

**Comment by juliusv** [comment]
Tried 2.39.2, it's working fine there, so this must have happened as part of the latest dependencies update for 2.40. Taking a closer look...

**Comment by juliusv** [comment]
Actually it was broken in https://github.com/prometheus/prometheus/pull/11068 - the `name` tag text color for the dark mode is set to `#000` (black) there. Gonna fix...

**Comment by juliusv** [comment]
@codesome FYI in case you deem it worth a 2.40.2 bugfix release.

**Comment by codesome** [comment]
Hmmm, I would like to wait a bit and see if we get more complains. If not, fix goes into 2.41, since I don't see this as a critical bug impacting the functioning of Prometheus and has a workaround (switch to light mode temporarily).

**Comment by juliusv** [comment]
@codesome Staunch dark mode aficionados would probably not see light mode as a valid workaround, but I don't mind either way :)

**Comment by Christoph-Raab** [comment]
Having encountered same issue while updating to 2.40.1 I would be glad about a bug fix release.

**Comment by codesome** [comment]
Ack. I will get on it sometime this week for 2.40.2.
