### ISSUE TITLE
Add VM size label to azure_sd_config service discovery

### ISSUE THREAD

**Issue by bociankruk** [prometheus/prometheus#11575]
### Proposal
It would be great to gather a meta label for VM size in Azure service discovery (docs: https://learn.microsoft.com/en-us/azure/virtual-machines/sizes).
Similar service discovery for AWS have this functionality as well (label name: __meta_ec2_instance_type).

There are multiple use cases for using this. For example:
- monitoring for using the same VM sizes to ensure that Reserved Instances are properly used.
- monitoring the CPU quota from subscription level.

**Comment by LeviHarrison** [comment]
Sounds like a good idea, thanks!

**Comment by LeviHarrison** [comment]
We can get the VM size from [`HardwareProfile.VMSize`](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute#HardwareProfile) in `mapFromVM()`:

https://github.com/prometheus/prometheus/blob/8b48e36933a89c7abf44e4baa41317d509e1506b/discovery/azure/azure.go#L512-L545

**Comment by thinh2** [comment]
Hi @LeviHarrison, I would like to work on this issue. Is it still available ?

**Comment by LeviHarrison** [comment]
Sure, go for it!

**Comment by davidifr** [comment]
Hi @LeviHarrison I see no action was made here for a week so I took the liberty to work on this issue.
https://github.com/prometheus/prometheus/issues/11575
Your review would be much appreciated.

**Comment by LeviHarrison** [comment]
Sure, that's fine. Reviewing it right now.

**Comment by davidifr** [comment]
Hi @LeviHarrison,
Thank you so much for the review and your insightful comments!
I believe you can close this one (Sorry for forgetting to connect the PR with the issue).

**Comment by LeviHarrison** [comment]
Oh yes, meant to do that. Thanks for reminding me.
