### ISSUE TITLE
provide metrics for kubernetes_sd discovery failures

### ISSUE THREAD

**Issue by juliantaylor** [prometheus/prometheus#11574]
### Proposal

There appears to be no way to monitor the state of the kubernetes service discovery.
https://prometheus.io/docs/prometheus/latest/configuration/configuration/#kubernetes_sd_config

The only metrics I could find in discovery/kubernetes/kubernetes.go are event counts which are not really suitable.
So as is the service discovery can fail silently and as the previously found targets remain configured it will only hard fail on changes or prometheus restart.

It would be good if there would be a metric on discovery failure which one could use to for alerting.
Currently we only seem to ahve log output, e.g.:
```
ts=2022-11-14T09:10:32.982Z caller=kubernetes.go:590 level=error component="discovery manager scrape" discovery=kubernetes msg="Failed to check networking.k8s.io/v1 availability" err="the server has asked for the client to provide credentials"
or
 Failed to list *v1beta1.Ingress: ingresses.extensions is forbidden: User \"system:serviceaccount:g..." cannot list resource \"ingresses\" in API group \"extensions\" in the namespace \"...\""
```

Possible failure cases are expired/missing credentials or unsupported API objects due to kubernetes deprecations.

**Comment by machine424** [comment]
I think we could make use of informers' `WatchErrorHandler` https://github.com/kubernetes/kubernetes/blob/862ff187baad9373d59d19e5d736dcda1e25e90d/staging/src/k8s.io/client-go/tools/cache/shared_informer.go#L185-L198 to surface some errors via a metric.

I'll give it a try.
