### ISSUE TITLE
Add a configurable stabilisation delay before resolving alerts

### ISSUE THREAD

**Issue by clux** [prometheus/prometheus#11570]
### Proposal

Currently, there is the `for` attribute in alerts to avoid spurious/flappy expressions triggering on a too small time period, but there is nothing to guard against the parallel problem of an alert resolving too quickly.

This can be a problem when you have data loss for a minute (so that a typical `sum(rate(metric[1m])) > 0` query returns nothing), or you have some other retrigger issues on HA alertmanagers (maybe https://github.com/prometheus/alertmanager/issues/1546), or just in general use alerts on expressions that take some time to truly settle down.

All these cases could benefit from a **grace period**  / **stabilisation delay** such that alerts that momentarily seem fine from the `expr` POV, are not immediately resolved during active incidents, but given at least some configurable time to settle. 

This would avoid confusing resolved messages being propagated through alertmanager and confusing oncallers.

Prior art; `stabilizationWindowSeconds` in [Kubernetes HPAs](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#stabilization-window).

**Comment by roidelapluie** [comment]
We would move to have this.

**Comment by pawadski** [comment]
Yes please. It was quite a surprise to see that I could define how long a rule needs to return true to alert, but not be able to define how long it needs to return false to be resolved.

**Comment by bboreham** [comment]
What's left to do here?

**Comment by rapphil** [comment]
keep_firing_for is not mentioned in the documentation at all.

**Comment by bboreham** [comment]
At https://prometheus.io/docs/prometheus/latest/configuration/recording_rules/#rule I see it under "The syntax for alerting rules is:"

Maybe you mean it should be on https://prometheus.io/docs/prometheus/latest/configuration/alerting_rules/.  (Which I would agree with).  Would you like to make a PR ?

**Comment by alexgreenbank** [comment]
Hello from the bug scrub.

@alexgreenbank to make the docs PR to add this.
