### ISSUE TITLE
Prometheus TSDB compactions failed 

### ISSUE THREAD

**Issue by knutov** [prometheus/prometheus#11585]
### What did you do?

I have alert on `increase(prometheus_tsdb_compactions_failed_total[1m]) > 0` (with 1.3333 value)

In prometheus logs:

```
prometheus[3247006]: ts=2022-11-16T02:48:26.172Z caller=db.go:908 level=error component=tsdb msg="compaction failed" err="compact head: persist head block: populate block: chunk iter: populateWithDelChunkSeriesIterator: unexpected empty chunk found while rewriting chunk"
```

I assume this can be bug because of comment: 

```go
// Empty chunk, this should not happen, as we assume full
// deletions being filtered before this iterator.
p.err = errors.New("populateWithDelChunkSeriesIterator: unexpected empty chunk found while rewriting chunk")
```

from https://github.com/prometheus/prometheus/blob/fa6e05903fd3ce52e374a6e1bf4eb98c9f1f45a7/tsdb/querier.go#L711 

May be it is related - before it is started I deleted some old data after configure relabeling with

```bash
curl -X POST -g 'http://localhost:9090/api/v1/admin/tsdb/delete_series?match[]={instance="some.server:1234"}'
```

### What did you expect to see?

no errors

### What did you see instead? Under which circumstances?

errors as described

### System information

Debian 11 with 5.10.0-10-amd64 #1 SMP Debian 5.10.84-1 (2021-12-08) x86_64 GNU/Linux

### Prometheus version

```text
prometheus, version 2.40.1 (branch: HEAD, revision: 965274259f993801d63f553639d248588287120b)
  build user:       root@d020f7085e1e
  build date:       20221109-14:30:50
  go version:       go1.19.3
  platform:         linux/amd64
```

### Logs

```text
prometheus[3247006]: ts=2022-11-16T02:48:26.172Z caller=db.go:908 level=error component=tsdb msg="compaction failed" err="compact head: persist head block: populate block: chunk iter: populateWithDelChunkSeriesIterator: unexpected empty chunk found while rewriting chunk"
```

**Comment by roidelapluie** [comment]
cc @codesome

**Comment by wanghsingmin** [comment]
I have the same error!
**System information**

Centos 7 Linux 3.10.0-1160.66.1.el7.x86_64 #1 SMP Wed May 18 16:02:34 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Prometheus version**
Version	2.40.1
Revision	965274259f993801d63f553639d248588287120b
Branch	HEAD
BuildUser	root@d020f7085e1e
BuildDate	20221109-14:30:50
GoVersion	go1.19.3

**Comment by wanghsingmin** [comment]
This issue causes our WALs logs to keep growing (> 200G) and when we restart the server, the replay WALs cause OOM, and the system kills the Prometheus process.  Finally, to recover the system, I removed all WALs logs, and then the error is gone. Now I keep watching the status.

**Comment by codesome** [comment]
Looks like this should have happened pre 2.40.x as well (the error existed before). Testing out what changed in between. We should not be erroring out here ideally.

**Comment by codesome** [comment]
Good to know that this existed before as well, and we don't need to error here. Earlier it didn't give a problem because of a bug, which 2.40.x fixed.

See https://github.com/prometheus/prometheus/blob/release-2.39/tsdb/querier.go#L694

It uses `errors.Wrap` on a `nil` error, which resulted in a nil error at the end. Tt actually had to create a new error, which 2.40.x fixes. Will cut a 2.40.3 with the fix.

**Comment by codesome** [comment]
This was fixed by https://github.com/prometheus/prometheus/pull/11623
