### ISSUE TITLE
No prometheus metric to find all unique label names, unique label counts or unique label value pairs

### ISSUE THREAD

**Issue by jagyas** [prometheus/prometheus#11584]
### Proposal

I was trying to create a high cardinality management dashboard as Grafana cloud has. See URL below:
https://grafana.com/docs/grafana-cloud/billing-and-usage/control-prometheus-metrics-usage/cardinality-management/

But I have found that there is no metric which can give me unique label names or count of unique labels or unique values for each label. 

Is there any feasibility if prometheus can export metrics to publish all these label details?

**Comment by kaffarell** [comment]
To get the count of unique labels / values for each label technically you can use this metric (Prometheus  creates a different time-series for every metric-label-value combination):
```
# HELP prometheus_tsdb_head_series_created_total Total number of series created in the head
# TYPE prometheus_tsdb_head_series_created_total counter
prometheus_tsdb_head_series_created_total 60566
```

For other metrics like those on the TSDB Status page on the prometheus interface, you can check the api:
```
GET http://localhost:9090/api/v1/status/tsdb
```
The response will include informations about (in json format):
* Head Stats
* Top 10 label names with value count
* Top 10 series count by metric names
* Top 10 label names with high memory usage
* Top 10 series count by label value pairs



Also check this guide on how to feed the response into prometheus:   
https://grafana.com/docs/grafana-cloud/billing-and-usage/control-prometheus-metrics-usage/usage-analysis-api/  
or this plugin:  
https://grafana.com/grafana/plugins/grafana-simple-json-datasource/

**Comment by jagyas** [comment]
Thanks a lot for your reply.

It is good to have these cardinality related data in the form of metrics so that we can take advantage of PromQL but anyway after your suggestion we have found below two useful plugins which helped us to access Prometheus TSDB REST endpoint and showing data on dashboard.

https://grafana.com/grafana/plugins/marcusolsson-json-datasource/  
https://grafana.com/grafana/plugins/yesoreyeram-infinity-datasource/

Grafana cloud is having this cardinality related data as a paid functionality. But I believe that understanding cardinality better will help everyone. If possible you can try to add these native metrics in future releases. But this is resolved for me, for now.

**Comment by k24dizzle** [comment]
Hi, are you willing to share how you got the `api/v1/status/tsdb` data in a grafana dashboard?

**Comment by jagyas** [comment]
Hello @k24dizzle ,
As I mentioned above, I am using Grafana plugins which can call prometheus REST endpoint and convert response data to Grafana visualization. As we were having multiple prometheus urls to hit to fetch and collect data, **yesoreyeram-infinity-datasource** plugin was most suitable for us. It helped to add different different endpoints in panel only without changing anything in datasource configuration.

**Comment by kaffarell** [comment]
Hey @jagyas can you please close this issue as it is resolved?

**Comment by alexgreenbank** [comment]
Hello from the bug scrub.

Closing as this issue looks to be resolved.
