### ISSUE TITLE
Speed up federation

### ISSUE THREAD

**Issue by zhangnaifan** [prometheus/prometheus#11594]
### Proposal

Can we speed up federation by running concurrent tasks instead of iterating one by one?
[Code](https://github.com/prometheus/prometheus/blob/main/web/federate.go#L105)

**Comment by roidelapluie** [comment]
Can you please tell us more about your use case and what you are using federation for?

**Comment by alexgreenbank** [comment]
Hello from the bug scrub.

Closing due to lack of follow up.
