### ISSUE TITLE
Enable bulk query fetching in `read` from storage remote client

### ISSUE THREAD

**Issue by dudmz** [prometheus/prometheus#11597]
### Proposal

Looking at the TODO's of the project (specifically at `storage/remote/client.go`), I found a case where we could implement bulk reading multiple queries. Since protobuf enables this, most of the refactor would come by calling `[]*prompb.Query{query}` instead of `query`. This way, upcoming features that uses read for multiple queries should benefit from this.

This is my first contribution to the project, so if possible, I'd like some feedback on my work from the maintainers or seasoned contributors. Thanks! :)

**Comment by roidelapluie** [comment]
cc @bwplotka

**Comment by bwplotka** [comment]
Thanks! It generally is easy to implement, as you showed, but I don't think we need that. Essentially, this is no easy use in current Prometheus, so adding that complexity can be simply avoided. I guess we might want to go through TODOs to ensure they are worth doing/ have enough context. In this case, we can do that, but we don't have clear ideas why we would use it (: 

Does it make sense?

Anyway, great contribution, thanks. However, I am sure some things need your attention than this in the Prometheus ecosystem 🤗

**Comment by alexgreenbank** [comment]
Hello from the bug scrub.

Closing as corresponding PR closed without merging.
