### ISSUE TITLE
`Appender.Append` should return the appended labelset 

### ISSUE THREAD

**Issue by colega** [prometheus/prometheus#11598]
### Proposal

`Appender.Append` returns the reference of the appended series, however there's no way to know which label set ended up being appended. 

Since `headAppender.Append` modifies the labelset (removing the empty labels) it would be great to have that result back instead of having to rely on having the same label-cleanup logic on the caller side. 

Without having this, we can call `Append()` and then call `GetRef()` with the same label set and get an empty result, which feels wrong.

This also will become especially important if we do strings interning or other kind of modifications on `labels.Labels` before actually creating the series. (cc @bboreham).

I would be happy to perform the change in the code, to be clear, I'm talking about doing:

```diff
diff --git storage/interface.go storage/interface.go
index 22d3b4186..bd8b92af2 100644
--- storage/interface.go
+++ storage/interface.go
@@ -225,7 +225,7 @@ type Appender interface {
        // to Append() at any point. Adding the sample via Append() returns a new
        // reference number.
        // If the reference is 0 it must not be used for caching.
-       Append(ref SeriesRef, l labels.Labels, t int64, v float64) (SeriesRef, error)
+       Append(ref SeriesRef, l labels.Labels, t int64, v float64) (SeriesRef, labels.Labels, error)

        // Commit submits the collected samples and purges the batch. If Commit
        // returns a non-nil error, it also rolls back all modifications made in
```

However, I'd just like to confirm whether there are any concerns on adding yet another return param on the most heavily called method in the codebase.

**Comment by roidelapluie** [comment]
cc @bboreham

**Comment by codesome** [comment]
Does doing the label cleanup step before calling `GetRef` work? Or does the extention of interface have other benefits as well? (I am not considering any modifications in labels.Labels right now)

**Comment by bboreham** [comment]
I think this proposed change exposes an implementation detail in TSDB that the `Appender` interface was designed to hide.

How about a function similar to [`GetRef`](https://github.com/prometheus/prometheus/blob/30b31cae93b2fe66486f188c07e215b80ebc93f8/storage/interface.go#L245-L253) which adds the reference and returns the labels, similarly in a separate interface so we can be clear it is not part of the main interface.

**Comment by colega** [comment]
> Does doing the label cleanup step before calling GetRef work?

It does, but it creates an implicit contract of having to do that in exactly the same way as TSDB does. Maybe we need a `tsdb.CleanupLabels(labels.Labels) (labels.Labels, error)` function then?

> How about a function similar to [GetRef](https://github.com/prometheus/prometheus/blob/30b31cae93b2fe66486f188c07e215b80ebc93f8/storage/interface.go#L245-L253) which adds the reference and returns the labels

Sorry what you mean by "adds the reference" here?

**Comment by colega** [comment]
Since this isn't clear yet (read: we have different opinions), I'll close the issue in the meantime.
We can always re-open if we find a need for this in the future.
