### ISSUE TITLE
exemplars scrapping openmetrics error

### ISSUE THREAD

**Issue by toxish666** [prometheus/prometheus#11601]
### What did you do?

1) Run server on 8080 port, that write on /metrics following body, that is constructed by [https://github.com/prometheus/client_java](java client). Here is the example body:
> \# HELP rpc_durations_histogram_seconds RPC latency distributions.
> \# TYPE rpc_durations_histogram_seconds histogram
> rpc_durations_histogram_seconds_bucket{le="-0.00099"} 0
> rpc_durations_histogram_seconds_bucket{le="-0.00089"} 0
> rpc_durations_histogram_seconds_bucket{le="-0.0007899999999999999"} 0
> rpc_durations_histogram_seconds_bucket{le="-0.0006899999999999999"} 0
> rpc_durations_histogram_seconds_bucket{le="-0.0005899999999999998"} 6 # {dummyID="6876"} -0.0006266745065283909 1.6688084762944589e+09

2) Run docker compose with docker compose file content:
>  services:
>  prometheus:
>   image: prom/prometheus:v2.40.2
>    command:
>     - --config.file=/etc/prometheus/prometheus.yaml
>      - --log.level=debug
>      - --web.console.libraries=/usr/share/prometheus/console_libraries
>      - --web.console.templates=/usr/share/prometheus/consoles
>      - --enable-feature=native-histograms
>      - --enable-feature=exemplar-storage
>    volumes:
>      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
>    ports:
>      - 9090:9090

### What did you expect to see?

Nothing in logs, prometheus should be able to parse metrics in application/openmetrics-text format.

### What did you see instead? Under which circumstances?

Prometheus is not able to scrape opentrace 1.0.0 metrics
`prometheus-prometheus-1  | ts=2022-11-18T22:05:26.759Z caller=scrape.go:1358 level=debug component="scrape manager" scrape_pool=aaa target=http://host.docker.internal:8080/metrics/stepName msg="Append failed" err="expected timestamp or new record, got \"MNAME\""
`

### Prometheus version

```text
2.40.2
```

### Prometheus configuration file

```yaml
scrape_configs:
  - job_name: aaa
    metrics_path: /metrics
    scrape_interval: 20s
    scheme: http
    static_configs:
      - targets: [host.docker.internal:8080]
```

### Logs

```text
prometheus-prometheus-1  | ts=2022-11-18T22:03:46.756Z caller=scrape.go:1358 level=debug component="scrape manager" scrape_pool=aaa target=http://host.docker.internal:8080/metrics/stepName msg="Append failed" err="expected timestamp or new record, got \"MNAME\""
prometheus-prometheus-1  | ts=2022-11-18T22:04:06.759Z caller=scrape.go:1358 level=debug component="scrape manager" scrape_pool=aaa target=http://host.docker.internal:8080/metrics/stepName msg="Append failed" err="expected timestamp or new record, got \"MNAME\""
prometheus-prometheus-1  | ts=2022-11-18T22:04:26.754Z caller=scrape.go:1358 level=debug component="scrape manager" scrape_pool=aaa target=http://host.docker.internal:8080/metrics/stepName msg="Append failed" err="expected timestamp or new record, got \"MNAME\""
prometheus-prometheus-1  | ts=2022-11-18T22:04:46.758Z caller=scrape.go:1358 level=debug component="scrape manager" scrape_pool=aaa target=http://host.docker.internal:8080/metrics/stepName msg="Append failed" err="expected timestamp or new record, got \"MNAME\""
prometheus-prometheus-1  | ts=2022-11-18T22:05:06.768Z caller=scrape.go:1358 level=debug component="scrape manager" scrape_pool=aaa target=http://host.docker.internal:8080/metrics/stepName msg="Append failed" err="expected timestamp or new record, got \"MNAME\""
```

**Comment by roidelapluie** [comment]
How are you exposing the metrics? Using client_java natively? it might be that either our parser does not support negative examplars or you are not sending the openmetrics header
