### ISSUE TITLE
Docs: Apdex score never goes below 0.5

### ISSUE THREAD

**Issue by aSemy** [prometheus/prometheus#11607]
### What did you do?

I followed the docs and tried to create an Apdex score

https://prometheus.io/docs/practices/histograms/#apdex-score

```
(
  sum(rate(feign_Client_seconds_bucket{le="0.3"}[5m])) by (client)
+
  sum(rate(feign_Client_seconds_bucket{le="1.2"}[5m])) by (client)
) / 2 / sum(rate(feign_Client_seconds_count[5m])) by (client)
```

### What did you expect to see?

An Apdex score ranging from 0 to 1

### What did you see instead? Under which circumstances?

The Apdex score never went below 0.5

<img width="800" alt="image" src="https://user-images.githubusercontent.com/897017/203120300-ba6d8a85-8faa-474b-ab43-f8265cda7a73.png">

### Prometheus version

```text
Build Information
* Version	2.40.2
* Revision	a07a94a5abb8a979d8aa87297f77f3979148b2da
* Branch	HEAD
* BuildUser	root@1b4b53e3f125
* BuildDate	20221117-13:40:12
* GoVersion	go1.19.3
```

**Comment by aSemy** [comment]
```
(
  sum(rate(feign_Client_seconds_bucket{le="0.3"}[5m])) by
 (client)  +
  sum(
rate(feign_Client_seconds_bucket{le="1.2"}
[5m])) by (client)
)/ sum
(rate(feign_Client_seconds_count[5m])) by (client)
) - 1
```

Removing the `/ 2` and instead  `-1` at the end looks like it produces a better result.

<img width="857" alt="image" src="https://user-images.githubusercontent.com/897017/203126799-bc478aa7-46c9-45d5-8e96-a715a18c2560.png">


btw it would be nice if Prometheus had an auto formatter, or some way to nicely format queries. It makes it really difficult that everything has to be all mushed together into one query.  And because Gradle and Prometheus have complete opposite enter/shift-enter shortcuts I keep making mistakes. It's very annoying.

**Comment by roidelapluie** [comment]
There is a way to format queries in recent prometheus releases. It is a button next to the query input.

cc @beorn7 can you assess this for correctness to see if we need to update the docs?

**Comment by beorn7** [comment]
The documented formula is correct (as in: it yields the Apdex score). The weirdness bust be in the values of your metrics.

 If all your requests are slower than 1.2s, then both `sum(rate(feign_Client_seconds_bucket{le="0.3"}[5m]))` as well as `sum(rate(feign_Client_seconds_bucket{le="1.2"}[5m]))` are zero. Your version of the formula would yield -1 in that case (which proves that your formula doesn't calculate an Apdex score because an Apdex score cannot be smaller than 0).

**Comment by aSemy** [comment]
Thanks for checking! I've run the PromQL again and it seems to be calculating as expected. I must have accidentally copy and pasted the wrong filter (which is why I think allowing for defining filters as variable would help #11609)
