### ISSUE TITLE
Create additional `scratch`-based docker image

### ISSUE THREAD

**Issue by liam-verta** [prometheus/prometheus#11608]
### Proposal

Create `scratch`-based docker image in addition to the existing `busybox`-based image.

The current docker image is based on https://github.com/prometheus/busybox which has [unpatched vulnerabilities](https://github.com/prometheus/busybox/issues/50). Having an image based on `scratch` would give consumers at least one secure production image they could use without creating a custom image.

However, switching to only have a `scratch`-based image would likely be a breaking change for a number of consumers of the current image.  So, adding a new image would give users a secure option without breaking existing users.

**Comment by LeviHarrison** [comment]
Hi there! This is actually already planned, as detailed in https://github.com/prometheus/prometheus/issues/8657. As far as I know though no one has starting working on it.

**Comment by roidelapluie** [comment]
Close as duplicate of #8657
