### ISSUE TITLE
Promtool documentation

### ISSUE THREAD

**Issue by LeviHarrison** [prometheus/prometheus#11612]
### Proposal

I don't believe we have any complete documentation of Promtool and its subcommands anywhere besides the help flag of the binary itself, save for a few snippets in various places. I think it might be useful to put together a full page in the docs both to help with the use of the tool and also the discovery of its features.

**Comment by dgl** [comment]
+1.

A quick list of things we do have:
- https://prometheus.io/docs/prometheus/latest/configuration/unit_testing_rules/
- https://prometheus.io/docs/prometheus/latest/configuration/recording_rules/#syntax-checking-rules
- https://prometheus.io/docs/prometheus/latest/storage/#backfilling-from-openmetrics-format
- https://prometheus.io/docs/prometheus/latest/migration/#recording-rules-and-alerts "update rules" -- which has been removed now...
- https://prometheus.io/docs/guides/basic-auth/#creating-web-yml

I think it makes sense to keep the main docs for some of those where they are, but maybe link from an index / other commands page.

**Comment by LeviHarrison** [comment]
Agreed, sounds good.

**Comment by machine424** [comment]
Thanks to @roidelapluie, we have https://prometheus.io/docs/prometheus/latest/command-line/promtool/ (generated) now.

We can enrich it and add links to relevant materials you shared. I think we can reword this issue.

**Comment by machine424** [comment]
Let's close this.
