### ISSUE TITLE
Support query raw samples with restful api or promtool

### ISSUE THREAD

**Issue by zhaojinxin409** [prometheus/prometheus#11620]
### Proposal

This feature is mainly for debugging promql.
When the promql's result is not behaving as we expect, the raw samples is usesful to debug promql.

**Comment by roidelapluie** [comment]
This is possible by running an instant query and my_metric[1h]. Then you get the raw samples.

**Comment by zhaojinxin409** [comment]
Thanks, it's really helpful to me
