### ISSUE TITLE
prometheus State Error

### ISSUE THREAD

**Issue by cchwasd** [prometheus/prometheus#11630]
### What did you do?

use prometheus-2.40.3.windows-amd64.zip
display interface:
  Targets -> prometheus->State is keeping Down

### What did you expect to see?

Targets -> prometheus->State is  Up

### What did you see instead? Under which circumstances?

use prometheus-2.40.3.windows-amd64.zip
display interface:
  Targets -> prometheus->State is keeping Down

### System information

Windows10

### Prometheus version

```text
prometheus-2.40.3.windows-amd64.zip
```

**Comment by roidelapluie** [comment]
Does using the env variable

GODEBUG=netdns=cgo

Help here?

**Comment by roidelapluie** [comment]
It sounds like the issue you were experiencing has been resolved in Prometheus versions 2.40.7 and 2.41.0. If you are not already using one of these versions, upgrading to the latest version may resolve the issue you were experiencing.
