### ISSUE TITLE
Is it possible to only generate alerts in the working hours

### ISSUE THREAD

**Issue by brunoqc** [prometheus/prometheus#1164]
I have the following rule to get alerts if my program didn't do its job at least once in the last 15 minutes.

I would like to be only notified in the working hours (like 9:00AM to 5:00PM).

Limiting alerts depending of the current time may not make sense for online services but in my case, it's for a polling program that only run in the working hour and if a problem happens, it's important enough (in the day) that I get paged.

```
ALERT TestLastOk
  IF absent(last_ok ) or on (name) (time() - last_ok > 900)
  WITH {}
  SUMMARY "problem"
  DESCRIPTION "the thing didn't run in the last 15 minutes"
```

**Comment by brian-brazil** [comment]
Presuming you're in UTC, `(vector(time()) % 86400 / 3600 > 5 < 17)`  will return a timeseries in that time. `and` could be used to restrict based on that.

**Comment by brunoqc** [comment]
Thanks.

Is there also a way to restrict based on the weekday (like monday to friday)?

**Comment by barkerd427** [comment]
I've asked previously, and I think this is a matter for the AlertManager.
The new version is currently under construction. I'm hoping it will include
this functionality.

**Comment by brian-brazil** [comment]
@brunoqc not currently. You could have an exporter that reported the current day.

**Comment by brian-brazil** [comment]
This question was answered.
