### ISSUE TITLE
Allow agents with no remote_writes configured

### ISSUE THREAD

**Issue by jlevesy** [prometheus/prometheus#11665]
### Proposal

Hello 👋 !

I would like to reopen the discussion https://github.com/prometheus/prometheus/issues/9611 regarding allowing the agents to run without any `remote_write` configured because I think I have an interesting use case for it.

We're currently experimenting with [Mimir HA deduplication](https://grafana.com/docs/mimir/latest/operators-guide/configure/configuring-high-availability-deduplication/) and while it seems to be the only way to go, it significantly increases the complexity of the setup because it requires an external KV store to be set up. 

So, I took the opportunity to experiment with another approach: making sure that only one agent in a replicated workload has `remote_write` enabled by using Kubernetes leader election on a group of agents. In other words: have an active-passive setup over a group of agents. This would remove the need for an external KV store on Mimir side, while allowing to get decent fail-over time when a leading agent pod goes down.

Of course this use case is valid if only the agents are running in a k8s cluster.

I wrote [prometheus-elector](https://github.com/jlevesy/prometheus-elector) which implements this idea by rewriting the Prometheus config according to the current leader election status.
 
The problem is that, for followers we still want to scrape but not necessarily push metrics so it would be nice to let them run without any`remote_write` targets. My test setup runs [a patched version](https://github.com/prometheus/prometheus/compare/main...jlevesy:prometheus:allow-agent-no-remote-write) that does that.

Does this use case makes any kind of sense?

Thanks!

**Comment by roidelapluie** [comment]
cc @rfratto

**Comment by rfratto** [comment]
Grafana Agent still permits no remote_writes (though it's not a very conscious decision), so I'm personally open to Prometheus Agent doing the same.

@bwplotka Do you have any input on this?

**Comment by bwplotka** [comment]
Happy with that. Solid use case and very interesting! Worth for Prometheus blog post even! @jlevesy 

I would welcome such change 👍🏽

**Comment by jlevesy** [comment]
I'll be working on it asap then. Thanks for your feedback folks!

**Comment by jlevesy** [comment]
Hello again 👋 

I just opened a PR to remove the if statement that prevents prometheus to start in agent mode without `remote_writes`.

I also run in one of our test environments [a setup](https://github.com/jlevesy/prometheus-elector/tree/main/helm)  with `prometheus-elector` enabled, and I'm curious regarding how the Prometheus agent behaves in that case.

I was under the assumption that when the agent get a `remote_write` config it will attempt to send the entirety of its WAL content to the remote (aka all the metrics that it has scrapped since started, capped by a limit ofc) , meaning that I shouldn't see any gap in the metrics when a fail-over between two replicas, but I still one (duration of ~30s, with a lease duration of 15s for the election), so now I'm starting to think that it only sends its metrics as soon as it gets one remote_write config, but there are many moving parts here 😅. 

Anyway, Could you clarify what is the expected behavior of the agent when a fail-over happens (ie: config goes from no `remote_write` to at east one)?

Thanks!

**Comment by jlevesy** [comment]
Well thanks for accepting this contribution! 

I would be definitely interested into writing down a blog both if you feel it makes sense. How should I proceed?

**Comment by jlevesy** [comment]
Hi again, I've pushed [prometheus-elector](https://github.com/jlevesy/prometheus-elector) to the point where I would be happy to get feedbacks on it!

Let me know what you think about it! Thanks!

**Comment by roidelapluie** [comment]
The PR #11709 has been merged. Thanks!
