### ISSUE TITLE
AlertmanagerFromGroup does not use port added to address

### ISSUE THREAD

**Issue by bboreham** [prometheus/prometheus#11671]
### What did you do?

The code creates a `LabelBuilder` here:
https://github.com/prometheus/prometheus/blob/72a48321dabed43f2cd9e510dda96c50d4a48a58/notifier/notifier.go#L730

then does various steps which might add a port number, and delete labels beginning `__meta_`, but none of this work has any effect.
At the end of processing it uses `lset` which was the result of relabelling 40 lines earlier:
https://github.com/prometheus/prometheus/blob/72a48321dabed43f2cd9e510dda96c50d4a48a58/notifier/notifier.go#L771

### What did you expect to see?

I guess, since this code has no effect and hasn't changed in 5 years, we don't need it.

### What did you see instead? Under which circumstances?

-

### Prometheus version

```text
Commit 72a48321dabed43f2cd9e510dda96c50d4a48a58
```

**Comment by roidelapluie** [comment]
Interestingly while the port should not be added I think, we should probably still go over HTTPS if __scheme__ is https.

**Comment by bboreham** [comment]
Do you think that changes with this PR?
