### ISSUE TITLE
For alerting usages, allow UTF-8 labels

### ISSUE THREAD

**Issue by bo-er** [prometheus/prometheus#11700]
### Proposal

Currently, prometheus treats alerts.yaml's "labels" and prometheus labels(that are appended to a metric) equally, therefore labels defined in alerts.yaml are also checked before they are used by an alert message, UTF-8 encoded labels fail to pass this checking and validation. We want to enable UTF-8 encoded labels and send alerts containing UTF-8 encoded labels therefore kindly request checking and validations for these alerting-related labels be removed.

**Comment by simonpasquier** [comment]
Just to be sure I understand correctly, you want Prometheus to support UTF-8 label names?
The topic was discussed during the [2022 Prometheus dev summit 10](https://docs.google.com/document/d/11LC3wJcVk00l8w5P3oLQ-m3Y37iom6INAMEu2ZAGIIE/edit) and the consensus was

> We will explore both "dots and slashes" and "everything in a backwards compatible way" in a design document

**Comment by bo-er** [comment]
https://github.com/prometheus/common/issues/182
from @brian-brazil:
> expanding them would cause breakage across the ecosystem

> You're confusing label names and label values. Label values is already as big as possible, any valid UTF-8. Label names are limited, and expanding them would cause breakage across the ecosystem.

This answer is quite confusing, how come allowing UTF-8 label names used by alertmanager would cause breakage across the ecosystem? If we had differentiated labels used by metrics and labels used by alertmanager, would this still be a problem?

**Comment by simonpasquier** [comment]
> it would be nice to have UTF-8 labels in alerts sent by alertmanager.

Prometheus sends alerts to Alertmanager. If we want to support UTF-8 label names, it should happen for all components.

**Comment by bo-er** [comment]
> > it would be nice to have UTF-8 labels in alerts sent by alertmanager.
> 
> Prometheus sends alerts to Alertmanager. If we want to support UTF-8 label names, it should happen for all components.

Thank you, I figured it out: There is no need to put the user-defined labels in "labels", we can just put them into "annotations" with key-value pairs as values of annotation. I was thinking about putting them into the labels(which seems reasonable, after all they are "labels"), and referencing them in alert message via "{{$external.名字}}". 
Again, thank you for your time and I will close these issues.
