### ISSUE TITLE
Failed to compile lezer-promql

### ISSUE THREAD

**Issue by lazy-wangxl** [prometheus/prometheus#11724]
### What did you do?

branch : release-2.37
execute "make build" and loop through the error message:

`[root@localhost prometheus]# make build
which: no yamllint in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/usr/local/go/bin:/usr/local/node/bin:/root/bin)
cd web/ui && npm install
npm WARN @jest/core@27.5.1 requires a peer of node-notifier@^8.0.1 || ^9.0.0 || ^10.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @jest/reporters@27.5.1 requires a peer of node-notifier@^8.0.1 || ^9.0.0 || ^10.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @pmmmwh/react-refresh-webpack-plugin@0.5.7 requires a peer of @types/webpack@4.x || 5.x but none is installed. You must install peer dependencies yourself.
npm WARN @pmmmwh/react-refresh-webpack-plugin@0.5.7 requires a peer of sockjs-client@^1.4.0 but none is installed. You must install peer dependencies yourself.
npm WARN @pmmmwh/react-refresh-webpack-plugin@0.5.7 requires a peer of webpack-hot-middleware@2.x but none is installed. You must install peer dependencies yourself.
npm WARN @pmmmwh/react-refresh-webpack-plugin@0.5.7 requires a peer of webpack-plugin-serve@0.x || 1.x but none is installed. You must install peer dependencies yourself.
npm WARN ajv-formats@2.1.1 requires a peer of ajv@^8.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN fork-ts-checker-webpack-plugin@6.5.2 requires a peer of vue-template-compiler@* but none is installed. You must install peer dependencies yourself.
npm WARN jest@27.5.1 requires a peer of node-notifier@^8.0.1 || ^9.0.0 || ^10.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN jest-cli@27.5.1 requires a peer of node-notifier@^8.0.1 || ^9.0.0 || ^10.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN jest-config@27.5.1 requires a peer of ts-node@>=9.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN jsdom@16.7.0 requires a peer of canvas@^2.5.0 but none is installed. You must install peer dependencies yourself.
npm WARN node-fetch@2.6.7 requires a peer of encoding@^0.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN postcss-load-config@3.1.4 requires a peer of ts-node@>=9.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-scripts@5.0.1 requires a peer of react@>= 16 but none is installed. You must install peer dependencies yourself.
npm WARN resolve-url-loader@4.0.0 requires a peer of rework@1.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN resolve-url-loader@4.0.0 requires a peer of rework-visit@1.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN sass-loader@12.6.0 requires a peer of fibers@>= 3.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN sass-loader@12.6.0 requires a peer of node-sass@^4.0.0 || ^5.0.0 || ^6.0.0 || ^7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN sass-loader@12.6.0 requires a peer of sass@^1.3.0 but none is installed. You must install peer dependencies yourself.
npm WARN sass-loader@12.6.0 requires a peer of sass-embedded@* but none is installed. You must install peer dependencies yourself.
npm WARN ws@8.8.0 requires a peer of bufferutil@^4.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN ws@8.8.0 requires a peer of utf-8-validate@^5.0.2 but none is installed. You must install peer dependencies yourself.
npm WARN ws@7.5.8 requires a peer of bufferutil@^4.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN ws@7.5.8 requires a peer of utf-8-validate@^5.0.2 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

audited 1257 packages in 12.145s
found 13 vulnerabilities (11 high, 2 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
cd web/ui && CI="" npm run build

> prometheus-io@ build /home/wangxl/WorkSpace/TMT/src/prometheus/web/ui
> bash build_ui.sh --all

build lezer-promql

> prometheus-io@ build /home/wangxl/WorkSpace/TMT/src/prometheus/web/ui
> bash build_ui.sh --all "@prometheus-io/lezer-promql"

build lezer-promql

> prometheus-io@ build /home/wangxl/WorkSpace/TMT/src/prometheus/web/ui
> bash build_ui.sh --all "@prometheus-io/lezer-promql"

build lezer-promql

> prometheus-io@ build /home/wangxl/WorkSpace/TMT/src/prometheus/web/ui
> bash build_ui.sh --all "@prometheus-io/lezer-promql"

build lezer-promql

> prometheus-io@ build /home/wangxl/WorkSpace/TMT/src/prometheus/web/ui
> bash build_ui.sh --all "@prometheus-io/lezer-promql"

build lezer-promql

> prometheus-io@ build /home/wangxl/WorkSpace/TMT/src/prometheus/web/ui
> bash build_ui.sh --all "@prometheus-io/lezer-promql"

build lezer-promql

> prometheus-io@ build /home/wangxl/WorkSpace/TMT/src/prometheus/web/ui
> bash build_ui.sh --all "@prometheus-io/lezer-promql"

build lezer-promql

> prometheus-io@ build /home/wangxl/WorkSpace/TMT/src/prometheus/web/ui
> bash build_ui.sh --all "@prometheus-io/lezer-promql"

build lezer-promql

> prometheus-io@ build /home/wangxl/WorkSpace/TMT/src/prometheus/web/ui
> bash build_ui.sh --all "@prometheus-io/lezer-promql"

build lezer-promql

> prometheus-io@ build /home/wangxl/WorkSpace/TMT/src/prometheus/web/ui
> bash build_ui.sh --all "@prometheus-io/lezer-promql"

build lezer-promql

> prometheus-io@ build /home/wangxl/WorkSpace/TMT/src/prometheus/web/ui
> bash build_ui.sh --all "@prometheus-io/lezer-promql"

build lezer-promql

> prometheus-io@ build /home/wangxl/WorkSpace/TMT/src/prometheus/web/ui
> bash build_ui.sh --all "@prometheus-io/lezer-promql"

build lezer-promql

> prometheus-io@ build /home/wangxl/WorkSpace/TMT/src/prometheus/web/ui
> bash build_ui.sh --all "@prometheus-io/lezer-promql"

build lezer-promql

> prometheus-io@ build /home/wangxl/WorkSpace/TMT/src/prometheus/web/ui
> bash build_ui.sh --all "@prometheus-io/lezer-promql"

build lezer-promql

> prometheus-io@ build /home/wangxl/WorkSpace/TMT/src/prometheus/web/ui
> bash build_ui.sh --all "@prometheus-io/lezer-promql"

build lezer-promql

> prometheus-io@ build /home/wangxl/WorkSpace/TMT/src/prometheus/web/ui
> bash build_ui.sh --all "@prometheus-io/lezer-promql"

build lezer-promql

> prometheus-io@ build /home/wangxl/WorkSpace/TMT/src/prometheus/web/ui
> bash build_ui.sh --all "@prometheus-io/lezer-promql"

build lezer-promql

> prometheus-io@ build /home/wangxl/WorkSpace/TMT/src/prometheus/web/ui
> bash build_ui.sh --all "@prometheus-io/lezer-promql"

build lezer-promql

> prometheus-io@ build /home/wangxl/WorkSpace/TMT/src/prometheus/web/ui
> bash build_ui.sh --all "@prometheus-io/lezer-promql"

build lezer-promql

> prometheus-io@ build /home/wangxl/WorkSpace/TMT/src/prometheus/web/ui
> bash build_ui.sh --all "@prometheus-io/lezer-promql"

build lezer-promql

> prometheus-io@ build /home/wangxl/WorkSpace/TMT/src/prometheus/web/ui
> bash build_ui.sh --all "@prometheus-io/lezer-promql"

build lezer-promql

> prometheus-io@ build /home/wangxl/WorkSpace/TMT/src/prometheus/web/ui
> bash build_ui.sh --all "@prometheus-io/lezer-promql"

build lezer-promql

> prometheus-io@ build /home/wangxl/WorkSpace/TMT/src/prometheus/web/ui
> bash build_ui.sh --all "@prometheus-io/lezer-promql"

build lezer-promql

> prometheus-io@ build /home/wangxl/WorkSpace/TMT/src/prometheus/web/ui
> bash build_ui.sh --all "@prometheus-io/lezer-promql"

build lezer-promql

> prometheus-io@ build /home/wangxl/WorkSpace/TMT/src/prometheus/web/ui
> bash build_ui.sh --all "@prometheus-io/lezer-promql"

build lezer-promql

> prometheus-io@ build /home/wangxl/WorkSpace/TMT/src/prometheus/web/ui
> bash build_ui.sh --all "@prometheus-io/lezer-promql"

build lezer-promql

> prometheus-io@ build /home/wangxl/WorkSpace/TMT/src/prometheus/web/ui
> bash build_ui.sh --all "@prometheus-io/lezer-promql"

build lezer-promql

> prometheus-io@ build /home/wangxl/WorkSpace/TMT/src/prometheus/web/ui
> bash build_ui.sh --all "@prometheus-io/lezer-promql"

build lezer-promql

> prometheus-io@ build /home/wangxl/WorkSpace/TMT/src/prometheus/web/ui
> bash build_ui.sh --all "@prometheus-io/lezer-promql"

build lezer-promql

> prometheus-io@ build /home/wangxl/WorkSpace/TMT/src/prometheus/web/ui
> bash build_ui.sh --all "@prometheus-io/lezer-promql"

build lezer-promql`

### What did you see instead? Under which circumstances?

now，High memory usage (command: top)

top - 10:03:45 up 2 days, 23:36,  6 users,  load average: 2.60, 1.25, 0.73
Tasks: 232 total,   7 running, 225 sleeping,   0 stopped,   0 zombie
%Cpu(s): 11.1 us, 88.9 sy,  0.0 ni,  0.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem :  2044260 total,    22480 free,  1002944 used,  1018836 buff/cache
KiB Swap:  2097148 total,  1949572 free,   147576 used.   982500 avail Mem

   PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND
 30237 gdm       20   0 2929400  58112  19796 S  0.0  2.8   2:14.97 gnome-shell
 44981 root      20   0 1051444  48348  20344 S  0.0  2.4   0:55.44 prometheus
 62245 root      20   0  797552  29928  13740 S  0.0  1.5   0:00.44 npm
 62173 root      20   0  797536  29896  13740 S  0.0  1.5   0:00.47 npm
 62137 root      20   0  797568  29884  13744 S  0.0  1.5   0:00.36 npm
 62269 root      20   0  797564  29868  13740 S  0.0  1.5   0:00.34 npm
 62293 root      20   0  797536  29860  13728 S  0.0  1.5   0:00.36 npm
 62197 root      20   0  797520  29852  13740 S  0.0  1.5   0:00.36 npm
 62257 root      20   0  797512  29804  13728 S  0.0  1.5   0:00.37 npm
 62281 root      20   0  797660  29804  13728 S  0.0  1.5   0:00.38 npm
 62185 root      20   0  797556  29768  13732 S  0.0  1.5   0:00.37 npm
 62233 root      20   0  797516  29760  13744 S  0.0  1.5   0:00.39 npm
 62305 root      20   0  797672  29740  13728 S  0.0  1.5   0:00.39 npm
 62209 root      20   0  797516  29732  13732 S  0.0  1.5   0:00.40 npm
 62161 root      20   0  797572  29728  13732 S  0.0  1.5   0:00.37 npm
 62317 root      20   0  797540  29696  13728 S  0.0  1.5   0:08.19 npm
 62101 root      20   0  797576  29692  13740 S  0.0  1.5   0:00.30 npm
 62089 root      20   0  797664  29676  13728 S  0.0  1.5   0:00.31 npm
 62077 root      20   0  797512  29660  13728 S  0.0  1.5   0:00.29 npm
 62065 root      20   0  797672  29644  13728 S  0.0  1.5   0:00.28 npm
 62113 root      20   0  797528  29632  13728 S  0.0  1.4   0:00.33 npm
 62029 root      20   0  797564  29628  13728 S  0.0  1.4   0:00.29 npm
 62125 root      20   0  797536  29612  13728 S  0.0  1.4   0:00.47 npm
 62149 root      20   0  797672  29612  13740 S  0.0  1.4   0:00.34 npm
 62221 root      20   0  797528  29608  13732 S  0.0  1.4   0:00.39 npm
 61993 root      20   0  797668  29596  13728 S  0.0  1.4   0:00.30 npm
 62005 root      20   0  797544  29596  13728 S  0.0  1.4   0:00.32 npm
 62017 root      20   0  797672  29584  13728 S  0.0  1.4   0:00.29 npm
 61981 root      20   0  797508  29568  13728 S  0.0  1.4   0:00.30 npm
 62041 root      20   0  797544  29552  13728 S  0.0  1.4   0:00.31 npm

![image](https://user-images.githubusercontent.com/17446031/207755196-16fb64f6-da83-4bf9-9557-ef132a4e75e1.png)

### System information

CentOS Linux release 7.8.2003 (Core) / Linux 3.10.0-1127.el7.x86_64 x86_64

### Prometheus version

```text
release-2.37
```

### Prometheus configuration file

```yaml
[root@localhost prometheus]# cat plugins.yml
- github.com/prometheus/prometheus/discovery/aws
- github.com/prometheus/prometheus/discovery/azure
- github.com/prometheus/prometheus/discovery/consul
- github.com/prometheus/prometheus/discovery/digitalocean
- github.com/prometheus/prometheus/discovery/dns
- github.com/prometheus/prometheus/discovery/eureka
- github.com/prometheus/prometheus/discovery/gce
- github.com/prometheus/prometheus/discovery/hetzner
- github.com/prometheus/prometheus/discovery/ionos
- github.com/prometheus/prometheus/discovery/kubernetes
- github.com/prometheus/prometheus/discovery/linode
- github.com/prometheus/prometheus/discovery/marathon
- github.com/prometheus/prometheus/discovery/moby
- github.com/prometheus/prometheus/discovery/nomad
- github.com/prometheus/prometheus/discovery/openstack
- github.com/prometheus/prometheus/discovery/puppetdb
- github.com/prometheus/prometheus/discovery/scaleway
- github.com/prometheus/prometheus/discovery/triton
- github.com/prometheus/prometheus/discovery/uyuni
- github.com/prometheus/prometheus/discovery/xds
- github.com/prometheus/prometheus/discovery/zookeeper
```

**Comment by lazy-wangxl** [comment]
I upgrade npm vertion to 8.19.2， but also error like this:

`[root@localhost prometheus]# make build
which: no yamllint in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/usr/local/go/bin:/root/bin)
cd web/ui && npm install

up to date, audited 1410 packages in 7s

217 packages are looking for funding
  run `npm fund` for details

10 vulnerabilities (9 high, 1 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
cd web/ui && CI="" npm run build

> build
> bash build_ui.sh --all

build lezer-promql

> @prometheus-io/lezer-promql@0.37.5 build
> bash ./build.sh

+ npx lezer-generator src/promql.grammar -o src/parser
Wrote src/parser.js and src/parser.terms.js
+ cat src/parser.terms.js
+ bash ./generate-types.sh
+ mkdir -p ./dist
+ indexFile=./dist/index.d.ts
+ [[ -f ./dist/index.d.ts ]]
+ rm ./dist/index.d.ts
+ cat
++ sed -E 's/ = [0-9]+/: number/' src/parser.terms.js
+ rollup -c

./src/parser.js → ./dist/index.cjs, ./dist/index.es.js...
created ./dist/index.cjs, ./dist/index.es.js in 86ms
build codemirror-promql

> @prometheus-io/codemirror-promql@0.37.5 build
> npm run build:lib


> @prometheus-io/codemirror-promql@0.37.5 build:lib
> bash ./build.sh

+ tsc --module esnext --target es2018 --outDir dist/esm
+ tsc --module commonjs --target es5 --outDir dist/cjs --downlevelIteration
build react-app

> @prometheus-io/app@0.37.5 build
> react-scripts build

Creating an optimized production build...
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
Compiled with warnings.

Failed to parse source map from '/home/prometheus/web/ui/node_modules/domutils/lib/https:/raw.git                              hubusercontent.com/fb55/domutils/f7e357b5c210b6731c2a60e0b7b3cfaa1f96b706/src/feeds.ts' file: Error: ENOENT: no such file                               or directory, open '/home/prometheus/web/ui/node_modules/domutils/lib/https:/raw.githubuserconten                              t.com/fb55/domutils/f7e357b5c210b6731c2a60e0b7b3cfaa1f96b706/src/feeds.ts'

Failed to parse source map from '/home/prometheus/web/ui/node_modules/domutils/lib/https:/raw.git                              hubusercontent.com/fb55/domutils/f7e357b5c210b6731c2a60e0b7b3cfaa1f96b706/src/helpers.ts' file: Error: ENOENT: no such fil                              e or directory, open '/home/prometheus/web/ui/node_modules/domutils/lib/https:/raw.githubusercont                              ent.com/fb55/domutils/f7e357b5c210b6731c2a60e0b7b3cfaa1f96b706/src/helpers.ts'

Failed to parse source map from '/home/prometheus/web/ui/node_modules/domutils/lib/https:/raw.git                              hubusercontent.com/fb55/domutils/f7e357b5c210b6731c2a60e0b7b3cfaa1f96b706/src/index.ts' file: Error: ENOENT: no such file                               or directory, open '/home/prometheus/web/ui/node_modules/domutils/lib/https:/raw.githubuserconten                              t.com/fb55/domutils/f7e357b5c210b6731c2a60e0b7b3cfaa1f96b706/src/index.ts'

Failed to parse source map from '/home/prometheus/web/ui/node_modules/domutils/lib/https:/raw.git                              hubusercontent.com/fb55/domutils/f7e357b5c210b6731c2a60e0b7b3cfaa1f96b706/src/legacy.ts' file: Error: ENOENT: no such file                               or directory, open '/home/prometheus/web/ui/node_modules/domutils/lib/https:/raw.githubuserconte                              nt.com/fb55/domutils/f7e357b5c210b6731c2a60e0b7b3cfaa1f96b706/src/legacy.ts'

Failed to parse source map from '/home/prometheus/web/ui/node_modules/domutils/lib/https:/raw.git                              hubusercontent.com/fb55/domutils/f7e357b5c210b6731c2a60e0b7b3cfaa1f96b706/src/manipulation.ts' file: Error: ENOENT: no suc                              h file or directory, open '/home/prometheus/web/ui/node_modules/domutils/lib/https:/raw.githubuse                              rcontent.com/fb55/domutils/f7e357b5c210b6731c2a60e0b7b3cfaa1f96b706/src/manipulation.ts'

Failed to parse source map from '/home/prometheus/web/ui/node_modules/domutils/lib/https:/raw.git                              hubusercontent.com/fb55/domutils/f7e357b5c210b6731c2a60e0b7b3cfaa1f96b706/src/querying.ts' file: Error: ENOENT: no such fi                              le or directory, open '/home/prometheus/web/ui/node_modules/domutils/lib/https:/raw.githubusercon                              tent.com/fb55/domutils/f7e357b5c210b6731c2a60e0b7b3cfaa1f96b706/src/querying.ts'

Failed to parse source map from '/home/prometheus/web/ui/node_modules/domutils/lib/https:/raw.git                              hubusercontent.com/fb55/domutils/f7e357b5c210b6731c2a60e0b7b3cfaa1f96b706/src/stringify.ts' file: Error: ENOENT: no such f                              ile or directory, open '/home/prometheus/web/ui/node_modules/domutils/lib/https:/raw.githubuserco                              ntent.com/fb55/domutils/f7e357b5c210b6731c2a60e0b7b3cfaa1f96b706/src/stringify.ts'

Failed to parse source map from '/home/prometheus/web/ui/node_modules/domutils/lib/https:/raw.git                              hubusercontent.com/fb55/domutils/f7e357b5c210b6731c2a60e0b7b3cfaa1f96b706/src/traversal.ts' file: Error: ENOENT: no such f                              ile or directory, open '/home/prometheus/web/ui/node_modules/domutils/lib/https:/raw.githubuserco                              ntent.com/fb55/domutils/f7e357b5c210b6731c2a60e0b7b3cfaa1f96b706/src/traversal.ts'

Failed to parse source map from '/home/prometheus/web/ui/node_modules/entities/lib/https:/raw.git                              hubusercontent.com/fb55/entities/867ac709ba482a56a98b7c35f49ca833c74dc193/src/decode.ts' file: Error: ENOENT: no such file                               or directory, open '/home/prometheus/web/ui/node_modules/entities/lib/https:/raw.githubuserconte                              nt.com/fb55/entities/867ac709ba482a56a98b7c35f49ca833c74dc193/src/decode.ts'

Failed to parse source map from '/home/prometheus/web/ui/node_modules/entities/lib/https:/raw.git                              hubusercontent.com/fb55/entities/867ac709ba482a56a98b7c35f49ca833c74dc193/src/decode_codepoint.ts' file: Error: ENOENT: no                               such file or directory, open '/home/prometheus/web/ui/node_modules/entities/lib/https:/raw.githu                              busercontent.com/fb55/entities/867ac709ba482a56a98b7c35f49ca833c74dc193/src/decode_codepoint.ts'

Failed to parse source map from '/home/prometheus/web/ui/node_modules/entities/lib/https:/raw.git                              hubusercontent.com/fb55/entities/867ac709ba482a56a98b7c35f49ca833c74dc193/src/encode.ts' file: Error: ENOENT: no such file                               or directory, open '/home/prometheus/web/ui/node_modules/entities/lib/https:/raw.githubuserconte                              nt.com/fb55/entities/867ac709ba482a56a98b7c35f49ca833c74dc193/src/encode.ts'

Failed to parse source map from '/home/prometheus/web/ui/node_modules/entities/lib/https:/raw.git                              hubusercontent.com/fb55/entities/867ac709ba482a56a98b7c35f49ca833c74dc193/src/escape.ts' file: Error: ENOENT: no such file                               or directory, open '/home/prometheus/web/ui/node_modules/entities/lib/https:/raw.githubuserconte                              nt.com/fb55/entities/867ac709ba482a56a98b7c35f49ca833c74dc193/src/escape.ts'

Failed to parse source map from '/home/prometheus/web/ui/node_modules/entities/lib/generated/http                              s:/raw.githubusercontent.com/fb55/entities/867ac709ba482a56a98b7c35f49ca833c74dc193/src/generated/decode-data-html.ts' fil                              e: Error: ENOENT: no such file or directory, open '/home/prometheus/web/ui/node_modules/entities/                              lib/generated/https:/raw.githubusercontent.com/fb55/entities/867ac709ba482a56a98b7c35f49ca833c74dc193/src/generated/decode                              -data-html.ts'

Failed to parse source map from '/home/prometheus/web/ui/node_modules/entities/lib/generated/http                              s:/raw.githubusercontent.com/fb55/entities/867ac709ba482a56a98b7c35f49ca833c74dc193/src/generated/decode-data-xml.ts' file                              : Error: ENOENT: no such file or directory, open '/home/prometheus/web/ui/node_modules/entities/l                              ib/generated/https:/raw.githubusercontent.com/fb55/entities/867ac709ba482a56a98b7c35f49ca833c74dc193/src/generated/decode-                              data-xml.ts'

Failed to parse source map from '/home/prometheus/web/ui/node_modules/entities/lib/generated/http                              s:/raw.githubusercontent.com/fb55/entities/867ac709ba482a56a98b7c35f49ca833c74dc193/src/generated/encode-html.ts' file: Er                              ror: ENOENT: no such file or directory, open '/home/prometheus/web/ui/node_modules/entities/lib/g                              enerated/https:/raw.githubusercontent.com/fb55/entities/867ac709ba482a56a98b7c35f49ca833c74dc193/src/generated/encode-html                              .ts'

Failed to parse source map from '/home/prometheus/web/ui/node_modules/entities/lib/https:/raw.git                              hubusercontent.com/fb55/entities/867ac709ba482a56a98b7c35f49ca833c74dc193/src/index.ts' file: Error: ENOENT: no such file                               or directory, open '/home/prometheus/web/ui/node_modules/entities/lib/https:/raw.githubuserconten                              t.com/fb55/entities/867ac709ba482a56a98b7c35f49ca833c74dc193/src/index.ts'

Failed to parse source map from '/home/prometheus/web/ui/node_modules/sanitize-html/node_modules/                              htmlparser2/lib/https:/raw.githubusercontent.com/fb55/htmlparser2/4763205746cd80120b5d2b69041197a394d24ba9/src/Parser.ts'                               file: Error: ENOENT: no such file or directory, open '/home/prometheus/web/ui/node_modules/saniti                              ze-html/node_modules/htmlparser2/lib/https:/raw.githubusercontent.com/fb55/htmlparser2/4763205746cd80120b5d2b69041197a394d                              24ba9/src/Parser.ts'

Failed to parse source map from '/home/prometheus/web/ui/node_modules/sanitize-html/node_modules/                              htmlparser2/lib/https:/raw.githubusercontent.com/fb55/htmlparser2/4763205746cd80120b5d2b69041197a394d24ba9/src/Tokenizer.t                              s' file: Error: ENOENT: no such file or directory, open '/home/prometheus/web/ui/node_modules/san                              itize-html/node_modules/htmlparser2/lib/https:/raw.githubusercontent.com/fb55/htmlparser2/4763205746cd80120b5d2b69041197a3                              94d24ba9/src/Tokenizer.ts'

Failed to parse source map from '/home/prometheus/web/ui/node_modules/sanitize-html/node_modules/                              htmlparser2/lib/https:/raw.githubusercontent.com/fb55/htmlparser2/4763205746cd80120b5d2b69041197a394d24ba9/src/index.ts' f                              ile: Error: ENOENT: no such file or directory, open '/home/prometheus/web/ui/node_modules/sanitiz                              e-html/node_modules/htmlparser2/lib/https:/raw.githubusercontent.com/fb55/htmlparser2/4763205746cd80120b5d2b69041197a394d2                              4ba9/src/index.ts'

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.

File sizes after gzip:

  470.48 kB  build/static/js/main.16fcfdee.js
  52.46 kB   build/static/css/main.99eb7085.css

The project was built assuming it is hosted at ./.
You can control this with the homepage field in your package.json.

The build folder is ready to be deployed.

Find out more about deployment here:

  https://cra.link/deployment

>> bundling npm licenses
rm -f "npm_licenses.tar.bz2"
find web/ui/node_modules -iname "license*" | tar cfj "npm_licenses.tar.bz2" --transform 's/^/npm_licenses\//' --files-from                              =-
>> compressing assets
scripts/compress_assets.sh
gzip: invalid option -- 'k'
Try `gzip --help' for more information.
gzip: invalid option -- 'k'
Try `gzip --help' for more information.
gzip: invalid option -- 'k'
Try `gzip --help' for more information.
gzip: invalid option -- 'k'
Try `gzip --help' for more information.
gzip: invalid option -- 'k'
Try `gzip --help' for more information.
gzip: invalid option -- 'k'
Try `gzip --help' for more information.
gzip: invalid option -- 'k'
Try `gzip --help' for more information.
gzip: invalid option -- 'k'
Try `gzip --help' for more information.
gzip: invalid option -- 'k'
Try `gzip --help' for more information.
gzip: invalid option -- 'k'
Try `gzip --help' for more information.
gzip: invalid option -- 'k'
Try `gzip --help' for more information.
gzip: invalid option -- 'k'
Try `gzip --help' for more information.
gzip: invalid option -- 'k'
Try `gzip --help' for more information.
gzip: invalid option -- 'k'
Try `gzip --help' for more information.
gzip: invalid option -- 'k'
Try `gzip --help' for more information.
gzip: invalid option -- 'k'
Try `gzip --help' for more information.
gzip: invalid option -- 'k'
Try `gzip --help' for more information.
gzip: invalid option -- 'k'
Try `gzip --help' for more information.
gzip: invalid option -- 'k'
Try `gzip --help' for more information.
gzip: invalid option -- 'k'
Try `gzip --help' for more information.
gzip: invalid option -- 'k'
Try `gzip --help' for more information.
gzip: invalid option -- 'k'
Try `gzip --help' for more information.
gzip: invalid option -- 'k'
Try `gzip --help' for more information.
gzip: invalid option -- 'k'
Try `gzip --help' for more information.
gzip: invalid option -- 'k'
Try `gzip --help' for more information.
gzip: invalid option -- 'k'
Try `gzip --help' for more information.
gzip: invalid option -- 'k'
Try `gzip --help' for more information.
gzip: invalid option -- 'k'
Try `gzip --help' for more information.
gzip: invalid option -- 'k'
Try `gzip --help' for more information.
gzip: invalid option -- 'k'
Try `gzip --help' for more information.
gzip: invalid option -- 'k'
Try `gzip --help' for more information.
gzip: invalid option -- 'k'
Try `gzip --help' for more information.
gzip: invalid option -- 'k'
Try `gzip --help' for more information.
gzip: invalid option -- 'k'
Try `gzip --help' for more information.
gzip: invalid option -- 'k'
Try `gzip --help' for more information.
gzip: invalid option -- 'k'
Try `gzip --help' for more information.
gzip: invalid option -- 'k'
Try `gzip --help' for more information.
gzip: invalid option -- 'k'
Try `gzip --help' for more information.
gzip: invalid option -- 'k'
Try `gzip --help' for more information.
gzip: invalid option -- 'k'
Try `gzip --help' for more information.
gzip: invalid option -- 'k'
Try `gzip --help' for more information.
gzip: invalid option -- 'k'
Try `gzip --help' for more information.
gzip: invalid option -- 'k'
Try `gzip --help' for more information.
gzip: invalid option -- 'k'
Try `gzip --help' for more information.
gzip: invalid option -- 'k'
Try `gzip --help' for more information.
gzip: invalid option -- 'k'
Try `gzip --help' for more information.
gzip: invalid option -- 'k'
Try `gzip --help' for more information.
gzip: invalid option -- 'k'
Try `gzip --help' for more information.
gzip: invalid option -- 'k'
Try `gzip --help' for more information.
gzip: invalid option -- 'k'
Try `gzip --help' for more information.
gzip: invalid option -- 'k'
Try `gzip --help' for more information.
gzip: invalid option -- 'k'
Try `gzip --help' for more information.
gzip: invalid option -- 'k'
Try `gzip --help' for more information.
gzip: invalid option -- 'k'
Try `gzip --help' for more information.
gzip: invalid option -- 'k'
Try `gzip --help' for more information.
gzip: invalid option -- 'k'
Try `gzip --help' for more information.
gzip: invalid option -- 'k'
Try `gzip --help' for more information.
gzip: invalid option -- 'k'
Try `gzip --help' for more information.
gzip: invalid option -- 'k'
Try `gzip --help' for more information.
gzip: invalid option -- 'k'
Try `gzip --help' for more information.
gzip: invalid option -- 'k'
Try `gzip --help' for more information.
gzip: invalid option -- 'k'
Try `gzip --help' for more information.
gzip: invalid option -- 'k'
Try `gzip --help' for more information.
gzip: invalid option -- 'k'
Try `gzip --help' for more information.
gzip: invalid option -- 'k'
Try `gzip --help' for more information.
gzip: invalid option -- 'k'
Try `gzip --help' for more information.
gzip: invalid option -- 'k'
Try `gzip --help' for more information.
>> building binaries
/root/go/bin/promu build --prefix /home/prometheus
 >   prometheus
# github.com/prometheus/prometheus/web/ui
web/ui/embed.go:21:3: usage: //go:embed pattern...
!! command failed: build -o /home/prometheus/prometheus -ldflags -X github.com/prometheus/common/version.Version=2.37.5 -X github.com/prometheus/common/version.Revision=8d25a0867918173e501b417e7acd85861df8fb0e -X github.com/prometheus/common/version.Branch=release-2.37 -X github.com/prometheus/common/version.BuildUser=root@localhost.localdomain -X github.com/prometheus/common/version.BuildDate=20221216-02:36:08  -extldflags '-static' -a -tags netgo,builtinassets github.com/prometheus/prometheus/cmd/prometheus: exit status 2
make: *** [common-build] Error 1
`

**Comment by erikbaranowski** [comment]
I ran into similar to your first error with `build lezer-promql` looping and I wanted to add some information. I do believe an older version of npm was the cause of this. What was happening:

In `./web/ui/package.json` there is a script setup for the build keyword 

```
"scripts": {
    "build": "bash build_ui.sh --all",
    "build:module": "bash build_ui.sh --build-module",
    "start": "npm run start -w react-app",
    "test": "npm run test --workspaces",
    "lint": "npm run lint --workspaces"
 }
```

In build_ui.sh, an npm run build command is executed `npm run build -w "@prometheus-io/${module}"`

- In the older version of npm this was recognizing the build keyword to then call its own build command in an infinite loop `bash build_ui.sh --all`
- In the newer version of npm, it will in fact call the build script of the target module defined in `./web/ui/module/*/package.json`

npm version 6.14.17 is the last documented version I can spot on their website for the npm build command so it is probably any version here or before with the issue you had https://docs.npmjs.com/cli/v6/commands/npm-build

As a reference point, I was able to `make build` from the root of the project on linux using 

WSL2 Debian running on Windows 11 Professional 

node --version
v19.3.0

npm --version
9.2.0

cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

**Comment by alexgreenbank** [comment]
Hello from the bug scrub.

Apologies for the time this has taken to look at.

We believe that this was fixed by using the latest tools and some tooling has been added to ensure the tools are up to date. Closing this issue.

If there are still problems we recommend troubleshooting via the resources linked at https://prometheus.io/community/
