### ISSUE TITLE
Proposal: Concurrent evaluation of alert rules in an alert group

### ISSUE THREAD

**Issue by gillesdemey** [prometheus/prometheus#11737]
### Context

According to [the documentation](https://prometheus.io/docs/prometheus/latest/configuration/recording_rules/#recording-rules) all rules within an alert group are evaluated sequentially. This makes sense since an alert group could contain one or more recording rules that have to be evaluated before other alert rules can subsequently refer to the recording.

This feels like an artificial restriction on the concurrent evaluation of rules within an alert group. 

Currently, if we'd want alert rules to be evaluated concurrently they must exist in different alert groups, leading to the creation of _many_ different alert groups at scale.

It becomes tricky to find the rule group you need since "grouping" implies the rules belong together, but we've placed them in _different_ groups because having too many rules in a single group has adverse effects on evaluation.

### Proposal

In order not to introduce any breaking changes to the existing evaluation behavior I'd like to propose a `concurrent: <true|false>` property that can be configured for a `<rule_group>` to opt-in to concurrent evaluation mode.

With concurrent alert rule evaluation all recording rules would be "hoisted" automatically to be evaluated first (and also concurrently) so other alert rules can still use the recorded series and all subsequently alert rules can be evaluated concurrently.

This means alert groups can group a large amount of rules without having adverse effects on the evaluation duration for the entire group.

```
      ┌─────────────┐
┌─────┤ Alert Group ├───────────────────────────────────┐
│     └─────────────┘         ┌ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ┐ │
│ ┌ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─         ┌───────────────────┐   │
│  ┌──────────────────┐│      │ │   Alert Rule #1   │ │ │
│ ││Recording Rule #1 │         └───────────────────┘   │
│  └──────────────────┘│      │ ┌───────────────────┐ │ │
│ │┌──────────────────┐ ─────▶  │   Alert Rule #2   │   │
│  │Recording Rule #2 ││      │ └───────────────────┘ │ │
│ │└──────────────────┘         ┌───────────────────┐   │
│  ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ┘      │ │   Alert Rule #3   │ │ │
│                               └───────────────────┘   │
│                             └ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ┘ │
└───────────────────────────────────────────────────────┘
╔══════════════════════════════════════════╗
║ Dashed line means evaluated concurrently ║
╚══════════════════════════════════════════╝
```

Lastly, I think hoisting recording rules automatically would be a nice quality-of-life improvement for the existing (sequential) alert group behavior so alert group authors don't have to think about or manually specify the order of alert rules within a group. 

If this would be a breaking change perhaps another property like `hoist_recording_rules: <true|false>` could be an option.

**Comment by TheCodeYoda** [comment]
is this ticket actively being worked on?

**Comment by darshanime** [comment]
related https://github.com/prometheus/prometheus/pull/12946

**Comment by gotjosh** [comment]
I'm going to close this the version of concurrent evaluation of rules for Prometheus has been designed and implemented as part of https://github.com/prometheus/prometheus/pull/12946
