### ISSUE TITLE
TSDB: Provide an commit interface that does not write OOO samples

### ISSUE THREAD

**Issue by roidelapluie** [prometheus/prometheus#11730]
In two scenarions Prometheus will rely on the rejection of OOO samples:

When a rule is moved from one file to another and the configuration is reloaded. The new rule writes its metric but several evaluation interval later, the first rule writes a staleness marker. In the past, that second happen was rejected and the staleness marker was not written.

https://github.com/prometheus/prometheus/blob/30b31cae93b2fe66486f188c07e215b80ebc93f8/rules/manager.go#L392-L399

The second scenario is when a target is stopped. We also wait a bit and try to insert a staleness marker that is rejected e.g. if the metrics are inserted with a target that has been restarted (e.g. because of a config change).

https://github.com/prometheus/prometheus/blob/30b31cae93b2fe66486f188c07e215b80ebc93f8/scrape/scrape.go#L1409-L1447

Therefore we should have an interface to that these samples should be rejected if they are OOO.

**Comment by codesome** [comment]
With the native histogram work that is happening, we will soon require a way to communicate to the appender whether the histogram is a counter histogram or a gauge histogram, and that will require some modification in the interface. I will keep this one in mind so that we could have a generic way of communicating such things. Hints for append maybe, just like queries.

**Comment by codesome** [comment]
A proposal for this https://github.com/prometheus/prometheus/issues/11765

**Comment by colega** [comment]
As mentioned in https://github.com/prometheus/prometheus/issues/11765#issuecomment-1707960383 we would also love to be able to increase the OOO window per-appender. Changing the OOO window is a general case of this request.

**Comment by Vanshikav123** [comment]
Hello everyone! I'm  working on resolving this issue as part of my LFX Mentorship. I'll keep you updated on my progress and any findings along the way.

**Comment by jesusvazquez** [comment]
Native histograms are getting OOO support soon, so we probably want to cover the native histograms appenders as well.

**Comment by jesusvazquez** [comment]
@roidelapluie it is my understanding that the new code added here https://github.com/prometheus/prometheus/pull/14710 solves both issues above (unit tests added as well).

So I'm going to go ahead and close this issue. Please reopen if you spot anything missing :+1:
