### ISSUE TITLE
Omitting a label matcher in PromQL inconsistent behaviour: Sometimes a syntax error, sometimes fine

### ISSUE THREAD

**Issue by samjewell** [prometheus/prometheus#11742]
### What did you do?

Downloaded and ran the Prometheus binary to scrape itself.

Then ran the query:
`{, job="prometheus"}` and got a syntax error.

After this I ran:
`{job="prometheus", }` and found it to be a valid query.

For me this is a bug, as it's inconsistent behaviour. The position of the missing label shouldn't matter to the validity of the query from a syntactic point of view. 

### What did you expect to see?

Either both queries should be valid syntax, or neither. At the moment the behaviour is inconsistent.

### What did you see instead? Under which circumstances?

One was invalid, the other not.

My preferred fix would be that it's ok to omit labels, both before and after the comma.
I'm templating PromQL queries from jsonnet into Grafana JSON dashboard files, and it's easier to template the version where the label-matcher is omitted but the comma remains, than it is to also omit the comma. Easier because of the following:

The queries on the dashboard I was templating looked like this in one case (one branch of an `if` statement):
```json
…
grafanacloud_org_metrics_overage{org_id="$org_id"}
…
grafanacloud_org_metrics_overage{org_id="$org_id", cluster="$cluster"}
…
```

And like this in the other case (other branch of the `if`):
```json
…
grafanacloud_org_metrics_overage{}
…
grafanacloud_org_metrics_overage{, cluster="$cluster"}
…
```

The latter case had a syntax error, but was easier to template out (as the `if` logic was simply to switch between `'org_id="$org_id"'` and `''` when doing string-interpolation. Obviously the workaround is to change the order of the label-matchers, but it took me literally ~6 months I think to discover that this workaround existed!

### System information

Darwin 21.6.0 arm64

### Prometheus version

```text
prometheus, version 2.40.4 (branch: HEAD, revision: 414d31aee6586a5f29e755ae059b7d7131f1c6c8)
  build user:       root@45956a3006ca
  build date:       20221129-11:04:07
  go version:       go1.19.3
  platform:         darwin/arm64
```

### Prometheus configuration file

```yaml
Just the default one that comes with the binary download
```

**Comment by roidelapluie** [comment]
I disagree that this is inconsistent. It is quite common to enable trailing comma without enabling comma everywhere.

One example is yaml, where `[a,b,]` is valid but `[,a,b]` is not.

I think being more relaxed here would probably lead to un-noticed errors.

**Comment by roidelapluie** [comment]
I also don't think that is correct to say `the label-matcher is omitted but the comma remains`; there is no label matcher omitted, it is just that you add a comma after a label matcher. e.g. I do not think that `my_metric{a="a",,b="b"}` should be a valid matcher.

**Comment by samjewell** [comment]
@roidelapluie thanks so much for your response. I'll close the issue in that case - it's not what I would choose, but at least I understand it now. Thanks again.
