### ISSUE TITLE
Add 'hints' to TSDB Append interface

### ISSUE THREAD

**Issue by codesome** [prometheus/prometheus#11765]
### Proposal

A follow-up of #11764.

There are a couple of use cases right now that could benefit with having hints on TSDB Append.

1. #11730 - a way to tell storage to ignore out-of-order samples even if they are enabled.
2. ~As a follow up of #11522, which appends 'FloatHistogram' as counter histograms, we need to add support for gauge histograms (required to add native histogram support to recording rules). This is already supported in TSDB (i.e. to indicate a histogram chunk to be either counter or gauge), but we cannot communicate during append if the sample is gauge or counter histogram.~ we decided to do it a different way

I am confident we will have more use cases that way while we are extending the TSDB. So, similar to queries, I propose we introduce hints to Appender.

Example proposal, combining #11764:

```go
type AppendSample struct { // See https://github.com/prometheus/prometheus/issues/11764
	// Checked in the order as present here. If h, fh, and e are nil, f is used.
	h  *histogram.Histogram
	fh *histogram.FloatHistogram
	e *exemplar.Exemplar // If this is present, t is ignored.
	f  float64
	t  int64
}

type AppendHints struct {
	DiscardOutOfOrder bool
}

type Appender interface {

	Append(ref SeriesRef, l labels.Labels, s AppendSample, hints *AppendHints) (SeriesRef, error)

	// ...
}
```

cc @bwplotka

**Comment by colega** [comment]
Should `ref SeriesRef` also be moved into `AppendHints` then?

**Comment by codesome** [comment]
We could. But for some reason, I prefer `ref` outside. Reason: `ref` is used widely, almost everywhere. `hint` I would assume to be not used in many places, so it would be simple to just pass `nil` everywhere instead of creating a `&storage.AppendHints` object while saving on allocations as well.

**Comment by roidelapluie** [comment]
The proposal LGTM.

**Comment by colega** [comment]
I would like to propose a custom OOO window (that could be 0) instead of completely disabling it. Just like there are use cases where we'd like to disable OOO, we might (we do have in Grafana Mimir for example) have use cases where we'd like to increase the OOO window allowance for some series/requets. Would that be possible?

**Comment by bboreham** [comment]
Can we update the proposed design in view of deciding to do histograms a different way?

I see that `AppendCTZeroSample` was added in a different pattern.   Can we make things consistent?
@ArthurSens

**Comment by ArthurSens** [comment]
> Can we update the proposed design in view of deciding to do histograms a different way?
> 
> I see that `AppendCTZeroSample` was added in a different pattern. Can we make things consistent? @ArthurSens

Do you mean different from the pattern proposed in this issue? I guess it could be something like:

```go
type AppendSample struct { // See https://github.com/prometheus/prometheus/issues/11764
	// Checked in the order as present here. If h, fh, and e are nil, f is used.
	h  *histogram.Histogram
	fh *histogram.FloatHistogram
	e *exemplar.Exemplar // If this is present, t is ignored.
	f  float64
	t  int64
	ct int64
}

type AppendHints struct {
	DiscardOutOfOrder bool
	DiscardCTZeroIngestion bool
}
```

We just need to make sure we do the same ordering checks before committing the CT, just like we do today.

**Comment by jesusvazquez** [comment]
@ArthurSens that would look consistent to me. Not sure if @bboreham agrees as well?

**Comment by colega** [comment]
Should we consider accepting a struct `AppendHints` value (assuming that zero-value will be no hints) instead of a pointer?

This is on the hot path (even hotter for remote-writers) and we could save an allocation here (because it's an interface it's going to escape).

**Comment by jesusvazquez** [comment]
@ArthurSens regarding Oleg's question, I think with remote write 2.0 we are expecting to use append hints more often in the remote write path right? If thats the case I think we should do what Oleg is suggesting.

**Comment by ArthurSens** [comment]
> @ArthurSens regarding Oleg's question, I think with remote write 2.0 we are expecting to use append hints more often in the remote write path right? If thats the case I think we should do what Oleg is suggesting.

Sorry but I don't have the context to answer this one 😬, maybe @bwplotka or @cstyan ?

**Comment by krajorama** [comment]
Be ware that native histograms can have multiple exemplars.

**Comment by cstyan** [comment]
> > @ArthurSens regarding Oleg's question, I think with remote write 2.0 we are expecting to use append hints more often in the remote write path right? If thats the case I think we should do what Oleg is suggesting.
> 
> Sorry but I don't have the context to answer this one 😬, maybe @bwplotka or @cstyan ?

For RW2.0 receivers are [required](https://prometheus.io/docs/specs/remote_write_spec_2_0/#required-written-response-headers) to respond to write requests with headers that indicate how many datapoints of each sample type were accepted. I suppose internally to Prometheus this could be done by hooking into append hints, but that's up to you guys/TSDB maintainers :shrug: 

The current v2 http handler is [here](https://github.com/prometheus/prometheus/blob/main/storage/remote/write_handler.go#L334) and [here](https://github.com/prometheus/prometheus/blob/main/storage/remote/write_handler.go#L371).
