### ISSUE TITLE
Hopes to increase `etcd` discovery 

### ISSUE THREAD

**Issue by JellyZero** [prometheus/prometheus#11788]
### Proposal

Hopes to increase `etcd` discovery

**Comment by LeviHarrison** [comment]
Hi there. I'm going to assume you mean you wish for there to be an etcd service discovery mechanism. Although I'm not too familiar with etcd, my impression is that as merely a key-value store, it would require custom logic to turn it into a service discovery system, logic that is not generic enough for it to be an official Prometheus SD. That being said, there is a [blog post](https://prometheus.io/blog/2015/08/17/service-discovery-with-etcd/) describing how to create a custom SD using etcd.

**Comment by alexgreenbank** [comment]
Hello from the bug scrub.

Closing as there is not enough detail to move this forward.

If this is still relevant then please consider creating a detailed proposal at https://github.com/prometheus/proposals where it can be discussed.
