### ISSUE TITLE
Option to delay rule evaluations

### ISSUE THREAD

**Issue by codesome** [prometheus/prometheus#11807]
### Proposal

With out-of-order ingestion, now time series can get old data anytime. There could be recording rules that need to be re-calculated for a timestamp because they got new samples. But it is also possible that you can identify a set of rule groups that tend to get delayed samples (especially when coupled with the remote-write receiver). In this case, having the ability to delay the evaluation of rule groups can keep the recording rule results more accurate.

The proposal is to add a new field `evaluation_delay` to the rule group. And let's say the delay is `d`, whenever the rule has to evaluate for time `now()`, it would just evaluate for time `now()-d` and produce samples for that time.

This is something done in Mimir and works well there. A reference implementation of how it will look in Prometheus is here https://github.com/grafana/mimir-prometheus/pull/155/.

cc @roidelapluie @beorn7 @juliusv

**Comment by codesome** [comment]
We could wait for some time and see if the community asks for it.

**Comment by juliusv** [comment]
Yup, either is ok with me.

**Comment by beorn7** [comment]
This also could help with the [ingestion delay issue discussed at the dev summit last April](https://docs.google.com/document/d/11LC3wJcVk00l8w5P3oLQ-m3Y37iom6INAMEu2ZAGIIE/edit?pli=1#heading=h.pnxuet28ppx3) (search for "ingestion delay" to find the relevant section).

It's not a perfect solution (and the discussion at the dev-summit suggested there might not be one), but depending on your realtime requirements, it might actually be a good practice to add a bit of delay to most rule groups.

**Comment by roidelapluie** [comment]
That makes sense. I used offset in PromQL queries in the past to simulate this. I propose we validate that OOO window is larger than the delay.

**Comment by codesome** [comment]
> I propose we validate that OOO window is larger than the delay.

I think we should not validate it, because it gets complicated quickly. For example, even without OOO window set, you can still get samples up to 1hr old that is not out-of-order. And some backfilling could be going on behind the scenes. So I would not add restrictions.

**Comment by roidelapluie** [comment]
The restriction is to make sure that we can ingest the result in the tsdb.

**Comment by codesome** [comment]
> The restriction is to make sure that we can ingest the result in the tsdb.

Oh yeah, did not think about that. max_delay=max(1h, OOO window).

**Comment by alexgreenbank** [comment]
Hello from the bug scrub.

We believe this has been implemented by https://github.com/prometheus/prometheus/pull/14061.

Closing this issue, please follow up if the PR linked above has not fully resolved the issue.
