### ISSUE TITLE
Support JSON marshalling interface

### ISSUE THREAD

**Issue by jaronoff97** [prometheus/prometheus#11816]
### Proposal

Right now, Prometheus only supports marshaling via YAML through the following interfaces:

* `yaml.Unmarshaler`
* `yaml.Marshaler`

This causes an issue for a user trying to serialize a scrape config to JSON as we try to do in the OpenTelemetry world [here](https://github.com/open-telemetry/opentelemetry-operator/blob/49de005991bd6864ccbf637c022da9e0ae925405/cmd/otel-allocator/server/server.go#L90-L122). Right now we have to serialize to YAML first, and then serialize that to JSON. Would it be welcome to add methods to prometheus scrape config fields (and their sub-fields) to adhere to the following interface

* `json.Marshaler`
* `json.Unmarshaler`

**Comment by roidelapluie** [comment]
Thank you for your suggestion to add support for marshaling via JSON in Prometheus. I understand the need for this feature, and I agree that it would be useful for you to have the option to serialize configs to JSON.

However, I have to consider the complexity and maintenance burden of adding this feature. Currently, we only support marshaling via YAML, and adding support for JSON marshaling would require significant changes to the codebase. In addition, we do not support full marshaling even in YAML - secrets are not marshallable. Furthermore, the basic JSON marshaling in the common package has proven to be more complex than expected, as demonstrated in this pull request: https://github.com/prometheus/common/pull/394

Given these considerations, as well as our general preference to avoid adding dead code, I don't think we should support full marshaling to JSON at this time.

**Comment by alexgreenbank** [comment]
Hello from the bug scrub.

Closing as this is almost 2 years old and there was no follow up to the response.
