### ISSUE TITLE
Flaky fuzzing failures in CI

### ISSUE THREAD

**Issue by bboreham** [prometheus/prometheus#11810]
Sometimes I see a report that the fuzzing CI job failed, e.g.: https://github.com/prometheus/prometheus/actions/runs/3840368422/jobs/6539337120

It says:
```
2023-01-04 18:04:26,855 - root - INFO - Fuzzer: fuzzParseMetricSelector. Detected bug.
2023-01-04 18:04:26,856 - root - INFO - Trying to reproduce crash using: /tmp/tmpdw5piina/tmplxscns1i.
2023-01-04 18:04:29,[52](https://github.com/prometheus/prometheus/actions/runs/3840368422/jobs/6539337120#step:5:53)9 - root - INFO - Reproduce command returned: 1. Reproducible on /github/workspace/build-out/fuzzParseMetricSelector.
2023-01-04 18:04:29,[53](https://github.com/prometheus/prometheus/actions/runs/3840368422/jobs/6539337120#step:5:54)0 - root - INFO - Crash is reproducible.
```

However it does not say what the crash was.  This does not seem very useful.

It also says:
```
Container for artifact "artifacts" successfully created. Starting upload of file(s)
Total size of all the files uploaded is 195 bytes
```

I cannot see where this file went.

The same job for the same PR passed on retry, hence I describe it as flaky.

**Comment by codesome** [comment]
I faced flaky test for `FuzzParseMetric` before. I checked few inputs of the failing tests, and they seem to be for an empty input `""`. I see that `FuzzParseMetric` [here](https://github.com/prometheus/prometheus/blob/fa0f04bbc6f41708782d4e259fd1fb38896bb904/promql/fuzz.go#L90) returns 1 if the parsing did not error out. And an empty input does not error out, failing the fuzzing test.

**Comment by bboreham** [comment]
Just so I can do better next time, where do you see `””` was the failure?

**Comment by codesome** [comment]
In the `Summary` section of the CI run (button on top left), I saw attachments for the failed tests. Those attachments had the failure case. I checked the link that you provided and it seems to be missing from there.

**Comment by codesome** [comment]
https://github.com/prometheus/prometheus/actions/runs/3840368422 seems to have some artifact below for fuzzParseMetricSelector (the 257B artifact).

**Comment by bboreham** [comment]
I see what you're saying about returning 1, `fuzzInteresting`, but I don't see that this is what the tool was reporting as a "crash".
From https://github.com/dvyukov/go-fuzz:
> To communicate application-level bugs Fuzz function should panic (os.Exit(1) will work too, but panic message contains more info).

**Comment by codesome** [comment]
I see. Also, in the log message for the fuzz failure, there are some links in there that let you download the test inputs, which has a regression directory with an input. Not sure if that is the one causing panic.

**Comment by jonathanmetzman** [comment]
Is this still occurring?

**Comment by roidelapluie** [comment]
Closing this issue as it seems like the problem was identified and fixed by the team responsible for the fuzzing infrastructure. Thank you all for your contributions and help in resolving this issue.
