### ISSUE TITLE
Native histograms support for text based prometheus exporter

### ISSUE THREAD

**Issue by amouhadi** [prometheus/prometheus#11811]
### Proposal

sparse/exponential histograms support in Prometheus only exists for the prometheus remote write protobuf representation and there is not a way to represent them in the text based exposition format used by prometheus exporter.
https://github.com/prometheus/prometheus/blob/main/model/textparse/promparse.go#L171-L175
Is it possible to add support for sparse histogram in textparse model?

**Comment by codesome** [comment]
Native histograms also exist for scraping, but with protobuf again. client_golang already supports exposing native histograms. client_java also has native histogram support, but that version is in `sparsehistogram` branch of the repo.

We do plan to add a text format. There has been some discussion going on about adding a text format and support it in other clients.
See https://groups.google.com/g/prometheus-developers/c/1uRXTAOD9-Y and https://docs.google.com/document/d/1w6GhLmDYKkkNLsyPWkC3TGhW3Rs1G73j7E_nG7bhlw0/edit

May I ask how text format helps you? Is using protobuf a blocker? (given you can expose native histograms via clients that support it)

**Comment by amouhadi** [comment]
thanks for the response, we're using a flow of java client,  Opentelemetry Collector, prometheus, cortex and grafana. tried to use the Exponential Histogram, had no issue with java client and opentelemetry receiver, although the PrometheusRemoteWrite in OTEL Collector does not support native histogram. There is an open issue in [opentelemetry-collector-contrib](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/16207)  to support for converting OTLP exponential histogram to Prometheus Native Histograms.
Also cortex still doesn't support the native histogram, there is this open issue for that too
https://github.com/cortexproject/cortex/issues/5060

**Comment by beorn7** [comment]
We do have an issue in prometheus/prometheus to add native histograms to the OM text format, see #11265.

OTel work is tracked over there.

I think, with that, the request in this issue is fully covered by other issues. Therefore, I'm closing this issue.
