### ISSUE TITLE
No error message within logs, just 'expected equal, got "INVALID"' on the Status / Targets view.

### ISSUE THREAD

**Issue by hawran** [prometheus/prometheus#11828]
### What did you do?

Trying to find out why are we missing metrics from some pods.

### What did you expect to see?

An error message within the logs explaining what is going on.

### What did you see instead? Under which circumstances?

Just 'expected equal, got "INVALID"' message within the Error column on the Status / Targets view.

### System information

Kernel Version: 5.4.0-126-generic, OS Image: Ubuntu 18.04.6 LTS

### Prometheus version

```text
2.40.5
```

**Comment by hawran** [comment]
I have finally found a culprit, I hope - an incorrect label name `topic-name`.

**Comment by hawran** [comment]
> I have finally found a culprit, I hope - an incorrect label name `topic-name`.

Meaning I've found the reason for missing metrics, however I'd like to see an error message more explanatory.

**Comment by roidelapluie** [comment]
Fixed by #11682.
