### ISSUE TITLE
Simplify `chunks.Meta` by removing the OOO fields

### ISSUE THREAD

**Issue by codesome** [prometheus/prometheus#11837]
### Proposal

With OOO support, we introduced 3 new fields to the chunk meta:
https://github.com/prometheus/prometheus/blob/f88a0a7d83bb9ef4387ff158d43f5a0c580fffdf/tsdb/chunks/chunks.go#L125-L132

This unnecessarily bloats the chunk meta because these fields are only required by the Head block's OOO Head reader (the part that reads the OOO data from the Head), and are not required everywhere else. We can likely find a way that does not require these fields to be inside the meta. For example, store that information with the Head block's OOO reader wrapper.

How to do this is still TBD. Ideas are welcome :)

---

This issue is broken down from https://github.com/prometheus/prometheus/issues/11329

**Comment by divaspathak** [comment]
I want to work on this issue. Can you please assign it to me?

**Comment by ansalamdaniel** [comment]
Hi @codesome , I'm currently working on this issue.
I need a clarification on the example solution you've mentioned.
Do we have to move the markers in `OOORangeHead` struct?

Alternate solution:
After going through the code, for a `Series()` call we are storing the same markers data for the overlapping chunks.
As these markers is mainly used in `oooMergedChunk` method, we can move these markers in the `memSeriesOOOFields` struct.

Please do let me know your thoughts on this.

**Comment by bboreham** [comment]
I started looking at this.
