### ISSUE TITLE
Pushdown more aggregator 'group/by' info through SelectHint

### ISSUE THREAD

**Issue by wanghaao** [prometheus/prometheus#11841]
### Proposal

```go
type SelectHints struct {
	Start int64 // Start time in milliseconds for this select.
	End   int64 // End time in milliseconds for this select.

	Step         int64 // Query step size in milliseconds.
	SubQueryStep int64 // SubQuery step size in milliseconds.

	Func string // String representation of surrounding function or aggregation.

	Grouping []string // List of label names used in aggregation.
	By       bool     // Indicate whether it is without or by.
	Range    int64    // Range vector selector range in milliseconds.

	DisableTrimming bool
}
```

On the master branch, the ``SelectHint`` struct only contains the info of the last node on the AST path. If the last node is ``AggregationExpr``, ``SelectHint`` would contain the ``Grouping`` and ``By``, for example, the ``Grouping`` of ``max(metric) by (a,  b)`` is ``[a,b]``, and the ``By`` is ``true``. We have already pushdown the ``Grouping`` and ``By`` to the remote storage, i.e., for the  VectorSelector ``metric``, the remote storage just needs to return the label ``a, b``. It is an optimizable point.

However, the ``Grouping`` and ``By`` of ``max(irate(metric)) by (a, b)`` should also be pushdown, and we can't get  ``Grouping`` and ``By`` following the logic of the master branch.

Can we directly pass the entire ``path []parser.Node`` on ``AST`` to the ``SelectHint``? We can implement more pushdown optimization according to the ``path``.

```go
func (ng *Engine) populateSeries(querier storage.Querier, s *parser.EvalStmt) {
	var evalRange time.Duration
	parser.Inspect(s.Expr, func(node parser.Node, path []parser.Node) error {
		switch n := node.(type) {
		case *parser.VectorSelector:
			start, end := ng.getTimeRangesForSelector(s, n, path, evalRange)
			subqInterval := ng.getLastSubqueryInterval(path)
......................
```

**Comment by fpetkovski** [comment]
Linking related issues:
* https://github.com/prometheus/prometheus/issues/11703
* https://github.com/prometheus/prometheus/issues/9979

**Comment by wanghaao** [comment]
> Linking related issues:
> 
> * [Extend select hints to have both the temporal and spatial function #11703](https://github.com/prometheus/prometheus/issues/11703)
> * [SelectHints should contain function parameters in addition to the function name #9979](https://github.com/prometheus/prometheus/issues/9979)

Passing the entire ``path []parser.Node on`` AST is a better selection, we can do more optimization.

**Comment by alexgreenbank** [comment]
Hello from the bug scrub.

Is there an update on this issue?
