### ISSUE TITLE
Add container ID as a meta label when utilizing Pod service discovery

### ISSUE THREAD

**Issue by bawhetst** [prometheus/prometheus#11843]
### Proposal

Our particular use case requires that we know the container ID associated with Pod targets. Currently, we utilize a separate process to lookup the container ID using the `__meta_kubernetes_pod_uid` and `__meta_kubernetes_pod_container_name` meta labels from Pod targets.

For simplicity's sake, we'd prefer if the container ID were already included in the meta labels so that we don't have to do the extra lookup. Frankly, I don't know if access to the container ID would be useful for other use cases. I don't think this should have an effect on the number of timeseries unless the new meta label is used i.e. relabeled.

The container ID already exists in the `Status->(Init)ContainerStatuses[]->ContainerID` field of the Pod object retrieved via the informer so there's no extra querying needed.

**Comment by bawhetst** [comment]
I opened a PR for this at https://github.com/prometheus/prometheus/pull/11844.

**Comment by bboreham** [comment]
What should happen when a pod has more than one container?

**Comment by bawhetst** [comment]
> What should happen when a pod has more than one container?

The same thing that happens today, a target is created for each container in the pod. If ports are defined for the container, then a target is created for each port per container.

**Comment by roidelapluie** [comment]
PR has been merged, thanks!
