### ISSUE TITLE
Graph UI zero-filling potentially confusing

### ISSUE THREAD

**Issue by fabxc** [prometheus/prometheus#1184]
Currently our Graphs are filled with [zero data](https://github.com/prometheus/prometheus/blob/master/web/blob/static/js/graph.js#L542) up to the point where the first time series starts.

This can cause confusion as it suggests that there was data being scraped for certain time series even though there is none.
Consequentially it is confusing when functions such as `increase()` do not return the expected data.

**Comment by brian-brazil** [comment]
Related to #345?

**Comment by fabxc** [comment]
Yes, adding comment there, closing here.
