### ISSUE TITLE
Auto-completion getting in the way of BY clause

### ISSUE THREAD

**Issue by fabxc** [prometheus/prometheus#1185]
When adding a label to a by-clause and hitting enter to execute the query the first auto-completion entry is added.
Either labels should be suggested or nothing.

**Comment by fabxc** [comment]
Extending this – we should block auto-completion for anything with leading digits, also known as numbers.

As pointed out by @grobie there is no longer away to see a list of all metric names since we removed the respective dropdown menu. I suggest those be shown when hitting the down button without any preceeding non-whitespace input.

This leads to the point of multiline input. Currently navigating through multiple lines is blocked by the auto-suggest dropdown. We should provide some reasonably intuitive way around this, e.g. disabling auto-completion while holding CTRL.

**Comment by fabxc** [comment]
`CTRL+Z` does ignore metric names inserted via auto-completion.

**Comment by grobie** [comment]
Auto complete was reverted for now in #1303.
