### ISSUE TITLE
Strange TSDB block storage behaviour

### ISSUE THREAD

**Issue by rsommer** [prometheus/prometheus#11873]
### What did you do?

We are running prometheus in multiple HA setups, using HA pairs with replica-label to be used in thanos long term storage. After doing an operating system upgrade last week, we encounter a strange block storage behaviour on one node in our staging environment. Both prometheus nodes are running with v2.41.0, they scrape the same targets, show nearly identical numbers in chunks, samples and series but despite all that, the resulting 2 hour blocks are around 600M on the one node and 1.2G on the other. There are always more segments per block on the second node.

From the last 2 hour blocks:

Node 1:
```
{
	"ulid": "01GQ6ZM9DGMF13S8FTD3V4EWA2",
	"minTime": 1674187200004,
	"maxTime": 1674194400000,
	"stats": {
		"numSamples": 591247933,
		"numSeries": 855723,
		"numChunks": 4950400
	},
	"compaction": {
		"level": 1,
		"sources": [
			"01GQ6ZM9DGMF13S8FTD3V4EWA2"
		]
	},
	"version": 1
}

$ du -sch chunks/*
504M	chunks/000001
504M	total
```

Node 2:
```
 {
	"ulid": "01GQ6ZM9BG0TYENXRCRYFNC4BK",
	"minTime": 1674187200000,
	"maxTime": 1674194400000,
	"stats": {
		"numSamples": 591261385,
		"numSeries": 855080,
		"numChunks": 4949858
	},
	"compaction": {
		"level": 1,
		"sources": [
			"01GQ6ZM9BG0TYENXRCRYFNC4BK"
		]
	},
	"version": 1
}

$ du -sch chunks/*
512M	chunks/000001
512M	chunks/000002
46M	chunks/000003
1.1G	total
```

Both nodes are currently scrapping 690 targets, all with status `up`.

I headed to the community forum first, but after I found a post describing nearly the same problem (but unfortunatly without any answer), this _might_ be more suitable for the issue tracker.

### What did you expect to see?

I expected the disk usage to be the same on bit nodes, as they are using the same config and that was the case up until the switch to a new distribution release (in this case from debian buster to bullseye). As the disk usage differs but the underlying system is the same, that should not be the problem.

### What did you see instead? Under which circumstances?

Block size between the nodes differ, for example the last blocks:

Node 1:
```
577M	01GQ645CX3VFVYGHSNFJ5MGG53
579M	01GQ6B145NRKE8HRFNKS156VGT
582M	01GQ6HWVD8HW73Y0BDX7H8ZRXC
588M	01GQ6RRK4TJY0AT9JE2CXTX27X
591M	01GQ6ZM9DGMF13S8FTD3V4EWA2
```

Node 2:
```
1.2G	01GQ645CVYRTWJE03616VTBAFC
1.2G	01GQ6B143ZS92RBA0VG5SR6AH7
1.2G	01GQ6HWVVR6EPFGAB8FKM7T8ZE
1.2G	01GQ6RRJKWSF5VS1YQDWE8DRZE
1.2G	01GQ6ZM9BG0TYENXRCRYFNC4BK
```

### System information

Linux 5.10.0-20-amd64 x86_64

### Prometheus version

```text
On both nodes:

prometheus, version 2.41.0 (branch: HEAD, revision: c0d8a56c69014279464c0e15d8bfb0e153af0dab)
  build user:       root@d20a03e77067
  build date:       20221220-10:40:45
  go version:       go1.19.4
  platform:         linux/amd64
```

### Prometheus configuration file

```yaml
# Scrape intervals identical on both nodes

global:
  scrape_interval:     10s
  evaluation_interval: 10s

# The rest is just labels and file service discovery
```

**Comment by rsommer** [comment]
After restarting prometheus on the misbehaving node (which was not done until now in order to investigate whats going on), the behaviour suddenly stopped - this leaves me wondering what was happening here?

**Comment by roidelapluie** [comment]
You probably experienced timestamp jitter issue: https://o11y.eu/blog/announcing-o11y-toolkit/

**Comment by rsommer** [comment]
Thanks for clarification, seems like that is indeed what we experienced - closing.
