### ISSUE TITLE
Prometheus UI is down 

### ISSUE THREAD

**Issue by naggirk** [prometheus/prometheus#11906]
### What did you do?

2.40.* TO 2.41.* Prometheus UI is failing to start

### What did you see instead? Under which circumstances?

Port forward command succeeded but when opening localhost:9090 on the browser displays 
Error opening React index.html: open web/ui/static/react/index.html: no such file or directory

### Prometheus version

```text
2.40.* TO 2.41.*  ----> Failing
2.39.2 ----> running
```

**Comment by dgl** [comment]
Please can you provide build details as the bug template mentions: `prometheus --version`.

If you're not using an official release build or image, then you need to make sure you compile it with `make`, rather than something like go build, as the web UI assets need building as well.

**Comment by naggirk** [comment]
prometheus, version 2.41.0

Following this wiki https://github.com/prometheus/prometheus/blob/main/web/ui/README.md
I see the following errors

ERROR in src/pages/graph/ExpressionInput.tsx:26:37
Module not found: Error: Can't resolve '@prometheus-io/codemirror-promql'
Module not found: Error: Can't resolve '@prometheus-io/codemirror-promql/dist/esm/complete'

We're currently deploying prometheus with this helm chart https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack

see version tag 2.41.0
Chart version 44.3.0
https://github.com/prometheus-community/helm-charts/blob/48f08281b29c78a3cd372a11800b6d18484a6e52/charts/kube-prometheus-stack/values.yaml#L2666

If I deploy the same chart with a version less than or equal to 2.39.2 the Prometheus UI works fine but in the 2.40 and up versions the UI is failing with 
Error opening React index.html: open web/ui/static/react/index.html: no such file or directory

**Comment by lilinvictorms** [comment]
We see same issue: the UI works until version 2.39.2, then is broken with version 2.40+. Is any way to vote this issue to get higher priority for investigation?

**Comment by roidelapluie** [comment]
Can you confirm you did not build prometheus yourself? Can this be reproduced with official docker images?

**Comment by lilinvictorms** [comment]
Oh yes, I was using prometheus docker image from MCR (Microsoft Container Registry) which is a private built version. Tried official image from "prom/prometheus:v2.42.0" and it works. So this seems a build issue with new versions.

**Comment by naggirk** [comment]
I can verify the same thing,
MCR images results in an UI failure but pulling from quay.io works fine

**Comment by toralf** [comment]
We are facing in Gentoo this bug too: https://bugs.gentoo.org/905408

**Comment by naggirk** [comment]
if you use MCR Prometheus version 2.43.0 the UI is working again

**Comment by toralf** [comment]
HHm, we do use this:

[I] app-metrics/prometheus
     Available versions:  2.40.4^st 2.43.0-r2^st
     Installed versions:  2.43.0-r2^st(05:18:19 PM 04/13/2023)
     Homepage:            https://github.com/prometheus/prometheus
     Description:         Prometheus monitoring system and time series database

**Comment by rostislaved** [comment]
Faced this issue on manjaro.

prometheus was installed via pacman

Helped: cd to "cd /usr/share/prometheus" and start prometheus from there:

cd /usr/share/prometheus
prometheus
