### ISSUE TITLE
Create Exporter for Spring Boot Metrics

### ISSUE THREAD

**Issue by mingfang** [prometheus/prometheus#1190]
Spring Boot applications by default supports the /metrics endpoint exposing JVM and application metrics, http://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-metrics.html

However the response is not compatible with Prometheus.
I know about the JMX Exporter but it would be great to have an official SpringBootExporter that works out of the box.

**Comment by jimmidyson** [comment]
:+1: I've made a start but it's stalled a bit due to other things. See https://github.com/jimmidyson/spring-boot-prometheus - really happy for contributions to get it working nicely.

**Comment by brian-brazil** [comment]
The general idea would be to write a simpleclient collector that'd proxy the metrics, giving them good labels where possible.

I note that Spring counters are not compatible with Prometheus counters, as they have a decrement method.

**Comment by jimmidyson** [comment]
I had to use a Prometheus gauge in place of spring counters. Was going to do the same as dropwizard spring metrics implementation & use metrics prefixes to create counters & summaries as required.

**Comment by brian-brazil** [comment]
There's nothing to be done here on the Prometheus side, if there's anything on the client_java side please open up an issue there.
