### ISSUE TITLE
That's how regular expression work. See https://www.robustperception.io/extracting-full-labels-from-consul-tags/

### ISSUE THREAD

**Issue by suikast42** [prometheus/prometheus#11903]
That's how regular expression work. See https://www.robustperception.io/extracting-full-labels-from-consul-tags/

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

_Originally posted by @brian-brazil in https://github.com/prometheus/prometheus/issues/3472#issuecomment-344269517_

**Comment by suikast42** [comment]
I see this dicussion here. 

Correct me if I am wrong. 

The regex: prometheus:([^=]+)=([^,]+) for example captures all labeles starts with prometheus.

Example Data:
```
prometheus_minio,frontend,minio,server=minio.minio[0],prometheus:server=minio.minio[0],prometheus:test2=1117a0ed-de14-25cc-0787-0d21dfa9d96e,prometheus:foo=worker-01,prometheus:version=RELEASE.2023-01-20T02-05-44Z,traefik.enable=true,traefik.consulcatalog.connect=false,traefik.http.routers.minio.tls=true,traefik.http.routers.minio.rule=Host(`minio.cloud.private`),prometheus:bar=worker-02
```

as you can see in https://regex101.com/ all groups captured by this regex. 

Could be marvellous to have this in standard pf prometheus.

**Comment by roidelapluie** [comment]
I need more context to be able to understand what you're trying to achieve. Specifically, I'd like to know how you're using Prometheus and what service discovery mechanism you're using, if any.

**Comment by bboreham** [comment]
Reviewed at the bug-scrub: we don't understand the question here, but since more context was asked for >1 year ago and silence since then, we will close.
