### ISSUE TITLE
Return more values on HTTP API /api/v1/status/tsdb

### ISSUE THREAD

**Issue by DanielCastronovo** [prometheus/prometheus#11945]
### Proposal

Adding a parameter on HTTP API /api/v1/status/tsdb for list more values (currently that describe only top 10) for :
- seriesCountByMetricName
- labelValueCountByLabelName
- memoryInBytesByLabelName
- seriesCountByLabelPair

Like other Tools, adding a parameter topN = integer on the request could be a good ways and a minimal change

**Comment by roidelapluie** [comment]
cc @bboreham

**Comment by bboreham** [comment]
No issue with this idea, but would like to see useful numbers returned first - see #11530

> Like other Tools

Such as?

**Comment by yeya24** [comment]
It also works if we can have a new API for getting Series cardinality. `/api/v1/status/tsdb` has some other information like headStats so having a dedicated cardinality API seems better.

**Comment by bboreham** [comment]
Sure, if you would like to put some more details into your suggestion, that’d be great. 
Sometimes people write a design doc. 

Note that Prometheus is an Open Source project run by volunteers; it relies on somebody showing up to implement any particular feature.

**Comment by bboreham** [comment]
Happy to see a PR.
If you didn't already see it, take a look at https://github.com/prometheus/prometheus/blob/main/CONTRIBUTING.md

**Comment by ArthurSens** [comment]
👋 Just checking... anything else to be done here? Or was it all done already? :)

**Comment by codebasky** [comment]
Now /api/v1/status/tsdb endpoint support limit query parameter as proposed by Daniel.

curl http://localhost:9090/api/v1/status/tsdb?limit=5

**Comment by bwplotka** [comment]
Amazing, thanks, seems this issue can be closed then!
