### ISSUE TITLE
Build error when execute 'make build'

### ISSUE THREAD

**Issue by LeosDing** [prometheus/prometheus#11957]
### What did you do?

Execute command 'make build'

### What did you expect to see?

'make build' execute success and no error.

### What did you see instead? Under which circumstances?

[root@localhost prometheus]# make build
which: no yamllint in (/usr/share/Modules/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin)
cd web/ui && npm install

up to date in 6s

252 packages are looking for funding
  run `npm fund` for details
cd web/ui && CI="" npm run build

> build
> bash build_ui.sh --all

+ set -e
+ [[ -w /root ]]
+ buildOrder=(lezer-promql codemirror-promql)
+ for i in "$@"
+ case ${i} in
+ buildModule
+ for module in "${buildOrder[@]}"
+ echo 'build lezer-promql'
build lezer-promql
+ npm run build -w @prometheus-io/lezer-promql

> @prometheus-io/lezer-promql@0.37.1 build
> bash ./build.sh

+ npx lezer-generator src/promql.grammar -o src/parser
Wrote src/parser.js and src/parser.terms.js
+ cat src/parser.terms.js
+ bash ./generate-types.sh
+ mkdir -p ./dist
+ indexFile=./dist/index.d.ts
+ [[ -f ./dist/index.d.ts ]]
+ rm ./dist/index.d.ts
+ cat
++ sed -E 's/ = [0-9]+/: number/' src/parser.terms.js
+ rollup -c

./src/parser.js → ./dist/index.cjs, ./dist/index.es.js...
created ./dist/index.cjs, ./dist/index.es.js in 121ms
+ for module in "${buildOrder[@]}"
+ echo 'build codemirror-promql'
build codemirror-promql
+ npm run build -w @prometheus-io/codemirror-promql

> @prometheus-io/codemirror-promql@0.37.1 build
> npm run build:lib

> @prometheus-io/codemirror-promql@0.37.1 build:lib
> bash ./build.sh

+ tsc --module esnext --target es2018 --outDir dist/esm
+ tsc --module commonjs --target es5 --outDir dist/cjs --downlevelIteration
+ buildReactApp
+ echo 'build react-app'
build react-app
+ npm run build -w @prometheus-io/app

> @prometheus-io/app@0.37.1 build
> react-scripts build

Creating an optimized production build...
Failed to compile.

TS2769: No overload matches this call.
  Overload 1 of 2, '(o: { [s: string]: unknown; } | ArrayLike<unknown>): [string, unknown][]', gave the following error.
    Argument of type 'T' is not assignable to parameter of type '{ [s: string]: unknown; } | ArrayLike<unknown>'.
      Type 'T' is not assignable to type 'ArrayLike<unknown>'.
  Overload 2 of 2, '(o: {}): [string, any][]', gave the following error.
    Argument of type 'T' is not assignable to parameter of type '{}'.
    262 |   o: T,
    263 |   cb: ([k, v]: [string, T[key]], i: number, arr: [string, T[key]][]) => Z
  > 264 | ): Z[] => Object.entries(o).map(cb);
        |                          ^
    265 |
    266 | export const callAll =
    267 |   (

npm ERR! Lifecycle script `build` failed with error: 
npm ERR! Error: command failed 
npm ERR!   in workspace: @prometheus-io/app@0.37.1 
npm ERR!   at location: /home/liu/prometheus/web/ui/react-app 
make: *** [Makefile:54: ui-build] Error 1

### System information

Linux 4.19.190-6.2.4.lns8.loongarch64 loongarch64

### Prometheus version

```text
prometheus-2.37.1
go version go1.18.9 linux/loong64
npm version 9.4.0
nodejs version v19.6.0
```

**Comment by roidelapluie** [comment]
We only support building with our docker image. Maybe @Nexucis can help you.

**Comment by Nexucis** [comment]
yeah I heard about this issue already. I think it's coming with nodeJS v19. Try to downgrade it. At least with NodeJS v16 it's working fine. Probably also with NodeJS v18

**Comment by roidelapluie** [comment]
I will close this based on @Nexucis 's answer.
