### ISSUE TITLE
Include information on tsdb status api to help estimate memory usage.

### ISSUE THREAD

**Issue by nicolastakashi** [prometheus/prometheus#11963]
### Proposal

Probably everyone working with Prometheus already cross [this amazing post from robust perception](https://www.robustperception.io/how-much-ram-does-prometheus-2-x-need-for-cardinality-and-ingestion/).

It is useful to at least give us one idea of how much memory a prometheus instance may require to ingest data based on their cardinality.

Based on this I would like to suggest the addition of the following information to the TSDB Status API.

- Average Labels Per Time Series
- Number of Unique Label Pairs
- Average Bytes per Label Pair

**Comment by roidelapluie** [comment]
cc @bboreham WDYT?

**Comment by bboreham** [comment]
Generally more information is good, but I’m afraid Brian’s post is misleading. Unique labels are all stored as separate copies per series, and label pairs are never treated as a unit. 

I spoke about memory consumption at the last PromCon: https://promcon.io/2022-munich/talks/why-is-it-so-big-analysing-the-m/

See also https://github.com/prometheus/prometheus/issues/11530

**Comment by bboreham** [comment]
Hello from the bug-scrub!
The TSDB Status page now gives more information, and the specific items requested in this issue are not high-value, so we will close this.
Personally I think a broader view of memory - how much is used by scraping, service discovery, queries, tsdb, etc. - would be very useful, but that would be a different issue.
