### ISSUE TITLE
Two vulnerabilities found in prometheus 2.42.0 image

### ISSUE THREAD

**Issue by nityavyas** [prometheus/prometheus#11974]
### What did you do?

Twistlock scanner for the image of version 2.42.0 found these vulnerabilities. One of them High. 

PRISMA-2022-0227
PRISMA-2022-0270

### What did you expect to see?

No vulnerabilities found.

### What did you see instead? Under which circumstances?

Saw these vulnerabilities when we download latest image and run twistlock scanner for it.

PRISMA-2022-0227
PRISMA-2022-0270

Can I please ask to have a fix for this released? Also it would be great to know the timeline for them. Thank you!

### Prometheus version

```text
2.42.0
```

**Comment by roidelapluie** [comment]
We appreciate our users' efforts to help make Prometheus more secure. However, please note that automated security scanners can generate many false positives. As we receive many reports, it can take time to review them in more detail, which could impact our response to genuine security issues.

We kindly urge you to take a closer look at the vulnerabilities found by Twistlock before you report them to us. Furthermore, we ask that you read our security policy (https://prometheus.io/docs/operating/security/) and submit a curated report with specific details about the security issues that impact our codebase. It will assist us in prioritizing and addressing actual security concerns more quickly.
