### ISSUE TITLE
Exemplars support for all time series

### ISSUE THREAD

**Issue by jonatan-ivanov** [prometheus/prometheus#11982]
### Proposal

Right now Exemplars are only supported on counters and histogram buckets. They are not supported for `Summary` (it has a `_count`) and `Histogram` (it also has a `_count`).

Having Exemplars support for at least `_count` (`Summary` and `Histogram`) would make it possible for the users to use Exemplars for things like request rates and error rates.

There were some discussions about this on the mailing list, this issue is basically for tracking that effort: https://groups.google.com/g/prometheus-developers/c/zgu5hwV_2oo/m/5VfUiOfmAgAJ

**Comment by roidelapluie** [comment]
I think we should keep the existing tests and add one or two extra example tests to test all code paths. Adding exemplars to all metrics in tests could potentially hide bugs in the future.

**Comment by jonatan-ivanov** [comment]
I guess you wanted to add this comment to the PR but this is essentially what I did.

**Comment by bobrik** [comment]
See also: https://github.com/OpenObservability/OpenMetrics/issues/241.
