### ISSUE TITLE
Select datadir for snapshots using API

### ISSUE THREAD

**Issue by alberto-trujillo-almagro** [prometheus/prometheus#11990]
### Proposal

When prometheus generate snapshots using API, we cant select data directory.
Snapshosts stores into "prometheus/snapshots" directory (in the same folder that prometheus files). 
When we deploy this stack into Kubernetes cluster, we cant create a Persistent Volumen inside default Prometheus Persistent Volumen to separate the storage.

Possible Solution:
  - Enable a new feature that permit select a diferent directory path for snapshots, using API:
https://github.com/prometheus/prometheus/blob/6dcfb717403e4a58c770dad796a09e9570a7a684/web/api/v1/api.go#L1536

**Comment by roidelapluie** [comment]
This is not possible because Snapshots use hard links. You have to move the snapshot on your own.

**Comment by roidelapluie** [comment]
I'd like to provide some additional information about hard links and how they relate to the issue at hand.

In Unix-based file systems, a hard link is a reference to an existing file. When a hard link is created, it creates a new entry in the file system's directory with the same inode number as the original file. This means that both the original file and the hard link have the same location on disk and refer to the same data.

In the context of Prometheus snapshots, this approach offers two main benefits: speed and disk space efficiency.

Firstly, when Prometheus generates a snapshot, it could be a costly operation in terms of time and resources. By using hard links, we avoid copying the entirety of the data to a new location, which saves significant amounts of time when creating a snapshot. Instead, the hard links point to the existing files on disk, which allows us to quickly generate the snapshot without the need for a full copy.

Secondly, disk space efficiency is important. By using hard links, we can avoid the necessity of duplicating the data that would be associated with each snapshot. Instead, the hard links enable snapshots to share the same physical data files as TSDB, reducing the disk space requirements and resulting in a more efficient use of resources.
