### ISSUE TITLE
Update tsdb/docs/… for native histograms and out-of-order ingestion

### ISSUE THREAD

**Issue by beorn7** [prometheus/prometheus#12005]
### Proposal

Both native histograms and out-of-order ingestion added various things to TSDB. Those update still needs to be reflected in https://github.com/prometheus/prometheus/tree/main/tsdb/docs/format

**Comment by fionaliao** [comment]
I think these are the updates that need to be made:

- chunks.md
	- add float histogram chunk format
- head_chunks.md
	- ooo mask for encoding
- wal.md
	- add histogram records
- wbl.md
	- doesn't exist yet, needs to be added 
	- most record types the same as wal.md, but need to add mmapmarker

**Comment by beorn7** [comment]
Sounds promising. (Not that I would know a lot about this documentation.)

**Comment by beorn7** [comment]
NHCB stuff needs to be added, too (working on it already).

**Comment by beorn7** [comment]
https://github.com/prometheus/prometheus/pull/15554 has added the WAL/WBL part.
