### ISSUE TITLE
Add a healthcheck command to the CLI (or at least the Docker image)

### ISSUE THREAD

**Issue by trajano** [prometheus/prometheus#12000]
### Proposal

Similar to https://github.com/prometheus/prometheus/pull/10366 but I am thinking more like traefik's approach which is to add a `healthcheck` command to the CLI that tests if the local server is up.  It does not need to do it via a public API and may have more robust checks that can only be done internally.

**Comment by roidelapluie** [comment]
I suggest implementing `promtool` subcommands for checking the health and readiness status of local Prometheus servers. These subcommands would call the existing `/-/healthy` and `/-/ready` endpoints on the local server, respectively. 

Please let me know if this approach is aligned with what you had in mind.

If more robust checks were needed, it could be done by having promtool query Prometheus directly, much like the existing promtool query command, does it satisfy your needs?

**Comment by trajano** [comment]
that should be fine `traefik` just adds a subcommand anyway.

**Comment by roidelapluie** [comment]
I noticed that both #12112 and #12096 seem to address the same issue. It looks like #12096 wasn't linked to the original issue before the second PR was submitted :(

**Comment by tjhop** [comment]
@roidelapluie that's my bad, I didn't realize there was existing work started in a PR already. It seems that #12096 already has some review work started, so I wouldn't mind closing my PR to prevent further duplication of effort, if that's preferred

**Comment by roidelapluie** [comment]
Maybe you can cooperate with the review of the other pull request?

**Comment by tjhop** [comment]
Sure, I can do that :+1:
