### ISSUE TITLE
Error "out of bounds" may disable all jobs when invalid metrics are received by remote-write

### ISSUE THREAD

**Issue by nemobis** [prometheus/prometheus#12006]
### What did you do?

Prometheus 2.39 running with `--web.enable-remote-write-receiver` to receive remote-written metrics from some other Prometheus instances and OpenTelemetry collectors in the same network.

### What did you expect to see?

If a remote machine sends invalid metrics (perhaps with grossly incorrect timestamps?), these samples should just be dropped, in the same way out of order samples are (normally) dropped by the scraper. Other jobs and sources should be unaffected.

### What did you see instead? Under which circumstances?

In some circumstances it may happen that the logs are flooded with errors like:

```
ts=2023-02-20T08:53:21.719Z caller=scrape.go:1294 level=warn component="scrape manager" scrape_pool=blackbox target=<redacted> msg="Appending scrape report failed" err="out of bounds"
ts=2023-02-20T08:53:22.795Z caller=manager.go:683 level=warn component="rule manager" <redacted> msg="Rule evaluation result discarded" err="out of bounds" sample=<redacted> => 1 @[1676883202753]"
```

At the same time,
* the `/targets` page shows most targets across all jobs down with "out of bounds" error;
* a `count(up) by (job)` query will show that most targets have completely vanished.

This is different from https://github.com/prometheus/prometheus/issues/10900 in various ways:
1) there isn't any log line containing both "Out of order sample from remote write" and "out of bounds";
2) the local clock was in sync;
3) deleting the database didn't help;
4) the error vanishes the moment the `--web.enable-remote-write-receiver` option is removed.

### System information

```
$ uname -a
Linux <redacted> 4.18.0-425.10.1.el8_7.x86_64 #1 SMP Wed Dec 14 16:00:01 EST 2022 x86_64 x86_64 x86_64 GNU/Linux
$ cat /etc/*release* | head -n5
NAME="Red Hat Enterprise Linux"
VERSION="8.7 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.7"
```

### Prometheus version

```text
$ prometheus --version
prometheus, version 2.39.1 (branch: HEAD, revision: dcd6af9e0d56165c6f5c64ebbc1fae798d24933a)
  build user:       root@273d60c69592
  build date:       20221007-15:57:09
  go version:       go1.19.2
  platform:         linux/amd64
```

### Prometheus configuration file

`/etc/systemd/system/prometheus.service` includes

```
ExecStart=/usr/local/bin/prometheus \
<redacted>
  --web.enable-lifecycle \
  --web.enable-admin-api \
  --web.enable-remote-write-receiver
```

**Comment by jcortejoso** [comment]
We have also experienced this.

**Comment by roidelapluie** [comment]
I think we should indeed review our policy for ingesting samples in the future

**Comment by Setheck** [comment]
> I think we should indeed review our policy for ingesting samples in the future

Yes!
I experienced a similar issue, where i have 2 prometheus instances pushing via remote write to another instance.
One of the downstream instances started up on a host with a system clock set to 10 years in the future. It scraped a future sample, pushed to the upstream prometheus, which pushed the current time to 10 years in the future, breaking all metric ingestion. I had to delete blocks fix it =(

**Comment by chzhuo** [comment]
I think we should add a `timeLimitAppender` to writer_handler.go like scrape.go to prevent invalid timestamp
https://github.com/prometheus/prometheus/blob/1ea477f4bcd04c580e51711dca346a06421b311c/scrape/scrape.go#L752-L755

**Comment by fatpat** [comment]
I encounter the very same problem. A date command mistake on a prometheus agent change the date a week or so in the future. This prometheus agent pushed remote write data to several prom servers and those are broken with ` msg="Appending scrape report failed" err="out of bounds"`.

Date and Time have since been synchronized back on the faulty prometheus agent but the problem remains.

how would it be possible to fix the issue ? By deleting some blocks but which ?

**Comment by fatpat** [comment]
> I encounter the very same problem. A date command mistake on a prometheus agent change the date a week or so in the future. This prometheus agent pushed remote write data to several prom servers and those are broken with ` msg="Appending scrape report failed" err="out of bounds"`.
> 
> Date and Time have since been synchronized back on the faulty prometheus agent but the problem remains.
> 
> how would it be possible to fix the issue ? By deleting some blocks but which ?

I manage to recover prometheus by:
1- stop prometheus
2- backup prometheus data directory
3- remove wal and chunks_head directories
4- start prom

**Comment by dgarcdu** [comment]
Hello.

Same issue here, a badly configured date in a device pushing metrics with OpenTelemetry collector via remote-write causes the out of bounds error and moves the head block times to the future. We solved it by temporarily disabling that device and deleting wal and chunks_head.

Is there an available fix for this case? I'm currently looking for a way to avoid this happening again in the future, but it would be nice if "too far ahead" samples were discarded under remote-write the same way they are in pull mode.

**Comment by bboreham** [comment]
Ref #13573

**Comment by jkroepke** [comment]
## Indicate invalid metric

After I saw the logs on my instances, I saw that under Prometheus Web UI Status -> TSBD Status that the date is fate in the future (today, we have 10 June)

![image](https://github.com/prometheus/prometheus/assets/1560587/bd2632b4-ecf5-4d3a-aba1-8d7d718eefe3)

Then I do a hand-crafted Query

http://prometheus/api/v1/query_range?query=%7B__name__%3D~%22.%2B%22%7D&start=1726735890.207&end=1726739490.207&step=1

where `start` and `end` parameter match the numbers from TSDB Status page. The Current Time Timestamp need to be divided by 1000.

## recovery

I followed the step (https://github.com/prometheus/prometheus/issues/12006#issuecomment-1611410650) to recover from state, but it didn't help.

I head to remove blocks (one-by-one) coming from newest. **DATA WILL BE LOST HERE**, but it's necessary to identity and remove the invalid metric.

**Comment by Starefossen** [comment]
We had our entire Prometheus server go down due to a metric with what appears to be future timestamp corrupt the entire TSDB.

**Comment by bboreham** [comment]
Using remote-write?

**Comment by Starefossen** [comment]
Yes, using Prometheus' remote-write from OpenTelemetry Collector.

**Comment by jkroepke** [comment]
https://github.com/prometheus/prometheus/pull/14304 should deny such metrics in future.
