### ISSUE TITLE
failure on CircleCI: test_windows

### ISSUE THREAD

**Issue by ianwoolf** [prometheus/prometheus#12018]
### Proposal

Two PRs submitted last year failed at CircleCI step: test_windows.

https://github.com/prometheus/prometheus/pull/10367
https://github.com/prometheus/prometheus/pull/10321

want some help...

**Comment by roidelapluie** [comment]
Thanks for bringing this up. We have moved from CircleCI to GitHub Actions for our testing, which is more reliable and efficient compared to CircleCI. We recommend that you rebase your changes on top of the `main` branch and give it a try with GitHub Actions. This should resolve the issue.
