### ISSUE TITLE
Prometheus remote write data lost

### ISSUE THREAD

**Issue by Panplumousse** [prometheus/prometheus#12016]
### What did you do?

I use Checkpoint skyline with open telemetry to send data into prometheus datasources with **remote-write-receiver** :
https://supportcenter.checkpoint.com/supportcenter/portal?eventSubmit_doGoviewsolutiondetails=&solutionid=sk178566

My prometheus configuration:

- --storage.tsdb.retention.time=15d
    - --config.file=/etc/config/prometheus.yml
    - --storage.tsdb.path=/data
    - --web.console.libraries=/etc/prometheus/console_libraries
    - --web.console.templates=/etc/prometheus/consoles
    **- --web.enable-remote-write-receiver**
    - --log.level=debug
    - --web.enable-lifecycle

In checkpoint side (firewall) i have many server with the skyline monitoring plugin install.

### What did you expect to see?

i did expect to have metric in prometheus for all my checkpoint server.

### What did you see instead? Under which circumstances?

At the first few minute it is working fine but after a few minutes we don't see any new data for some off server.
And on an other hand , when i keep juste one sending server active , we keep received all data without any lost

### System information

kubernetes

### Prometheus version

```text
2.41.0
```

### Logs

```text
evel=error component=web msg="Out of order sample from remote write" err="out of bounds" series="{__name__=\"system_network_errors_receive\", device=\" \", environment=\"Default\", host_name=\"XXXXXXXXXXX\", interface=\"TOTAL\", job=\"vs_id_0/CPviewExporter\", service_name=\"CPviewExporter\", service_namespace=\"vs_id_0\", service_version=\"CPviewExporter-0.1.0\"}""
```

**Comment by liguozhong** [comment]
Samples from the future move forward the retention period, and could cause problems.

Initially hardcode a 10m limit on how far in the future we accept samples.

you should check metrics timestamp.

https://github.com/prometheus/prometheus/issues/2893
https://github.com/prometheus/prometheus/pull/2897

`const maxAheadTime = 10 * time.Minute
`

```
func appender(app storage.Appender, sampleLimit, bucketLimit int) storage.Appender {
	app = &timeLimitAppender{
		Appender: app,
		maxTime:  timestamp.FromTime(time.Now().Add(maxAheadTime)),
	}
```


```
 func (app *timeLimitAppender) Append(ref uint64, lset labels.Labels, t int64, v float64) (uint64, error) {
	if t > app.maxTime {
		return 0, storage.ErrOutOfBounds
	}

	ref, err := app.Appender.Append(ref, lset, t, v)
	if err != nil {
		return 0, err
	}
	return ref, nil
}
```
 

```

	// ErrOutOfBounds is when out of order support is disabled and the sample is older than the min valid time for the append.
	ErrOutOfBounds = errors.New("out of bounds")
```

**Comment by bboreham** [comment]
Hello from the bug-scrub!
There is no way we can debug this issue from 18 months ago, and handling of errors has improved, so we will close this.
Please open a new issue with up-to-date logs if you are still experiencing this problem.
