### ISSUE TITLE
I don't get a summary values when using protobuf

### ISSUE THREAD

**Issue by amnonh** [prometheus/prometheus#12028]
### What did you do?

I've used the ```--enable-feature=native-histograms``` which supports protobuf.
I get all metrics but the summaries, I've decode the message and saw that the values are there.

Maybe there's some non-compatibility of summaries with the old protobuf representations?
I didn't see any errors in the log.

I'm using Promethues 2.42.0 in a container.

### What did you expect to see?

To see the summaries

### What did you see instead? Under which circumstances?

I see the metric but it's empty (i.e. no quantil and values)

### System information

docker

### Prometheus version

```text
$ prometheus --version
prometheus, version 2.42.0 (branch: HEAD, revision: 225c61122d88b01d1f0eaaee0e05b6f3e0567ac0)
  build user:       root@c67d48967507
  build date:       20230201-07:53:32
  go version:       go1.19.5
  platform:         linux/amd64
```

**Comment by amnonh** [comment]
I wrote the Prometheus supprot for the [seastar](https://seastar.io/) framework. With the retutn of protobuf, I would like to resurrect the protobuf support in Seastar.
Can someone take a look at this issue?

**Comment by beorn7** [comment]
Thanks for reporting. There is entirely a possibility that the new protobuf parser has hiccups like this (although I thought I had covered summaries by tests). Will have a look ASAP. And of course, any further evidence or even PRs to fix are highly welcome in the meantime.

**Comment by beorn7** [comment]
It must be in here: https://github.com/prometheus/prometheus/blob/main/model/textparse/protobufparse.go

**Comment by beorn7** [comment]
I checked the unit tests, and they cover summaries.

I then created a minimal setup with https://github.com/prometheus/client_golang/blob/main/examples/random/main.go . Everything seems to work fine. I get the summaries with all their "fields":

![image](https://user-images.githubusercontent.com/5609886/230160836-ca683778-c818-4cb7-93b2-6bae659f25e2.png)

The Prometheus server is definitely using protobuf to scrape the example binary because it also sees the native histograms:

![image](https://user-images.githubusercontent.com/5609886/230160987-dba7e0bf-cf25-4daf-b9e3-fe6390a0f4b7.png)

Something else must go wrong in your case. Could you investigate further to find out what?

**Comment by amnonh** [comment]
I've compiled main locally and it works, with 2.43.0 running in a container it doesn't work. so it gives me enough confident in my library implementation, I'll test again with the next release.
Let's keep this issue open, untill we see that it's closed in the next release

**Comment by amnonh** [comment]
After some more digging I found the issue, closing as not a problem

**Comment by amnonh** [comment]
@beorn7 I'm still working on Adding native-histogram support for [Seastar](https://github.com/scylladb/seastar) I don't get the values in Prometheus.

Do you have an example of what is needed for Prometheus to parse Native Histograms?
I mean an all the required fields, as far as I can validate the histgorams I'm sending looks fine buy maybe a field is missing.

**Comment by beorn7** [comment]
Both sides need to use protobuf (the classic format, see https://github.com/prometheus/client_model (or https://github.com/prometheus/prometheus/blob/main/prompb/io/prometheus/client/metrics.proto for the proto3 version used by Prometheus itself)).

As an instrumented example, you could run https://github.com/prometheus/client_golang/blob/main/examples/random/main.go . Then you can use `curl` to see the text encoding of the protobuf in the following way:
```
curl -H 'Accept: application/vnd.google.protobuf;proto=io.prometheus.client.MetricFamily;encoding=text' localhost:8080/metrics
```

The histogram therein is called `rpc_durations_histogram_seconds`. It is a combined histogram with classic and native buckets. the `bucket` proto messages are the classic buckets. You can ignore them for native histogram purposes. See the proto definition file (linked above) for details.

**Comment by beorn7** [comment]
More generally, I would suggest to discuss this in the #prometheus-histograms-dev channel on the CNCF Slack.
