### ISSUE TITLE
Command line option --web.console.libraries still exists in --help but isn't actually supported in 

### ISSUE THREAD

**Issue by kestess** [prometheus/prometheus#12059]
### What did you do?

prometheus, version 2.42.0 (branch: HEAD, revision: 225c61122d88b01d1f0eaaee0e05b6f3e0567ac0)

Tried to start with this service file:

[Unit]
Description=Prometheus
Wants=network-online.target
After=network-online.target

[Service]
User=prometheus
Group=prometheus
Type=simple

ExecStart=/usr/local/bin/prometheus \
 --config.file /etc/prometheus/prometheus.yml \
 --storage.tsdb.path /prom_data \
 --web.console.templates="/etc/prometheus/consoles" \
 --web.console.libaries="/etc/prometheus/consoles_libraries" \
 --web.enable-lifecycle

[Install]
WantedBy=multi-user.target

### What did you expect to see?

I don't expect to see an error (see below) or see the option in the --help output
--web.console.libraries="console_libraries"  Path to the console library directory.

### What did you see instead? Under which circumstances?

Mar 05 20:13:19 prometheus prometheus[12320]: Error parsing commandline arguments: unknown long flag '--web.console.libaries'
Mar 05 20:13:19 prometheus prometheus[12320]: prometheus: error: unknown long flag '--web.console.libaries'

### Prometheus version

```text
ivy@prometheus:~/prometheus-2.42.0.linux-amd64$ prometheus --version
prometheus, version 2.42.0 (branch: HEAD, revision: 225c61122d88b01d1f0eaaee0e05b6f3e0567ac0)
  build user:       root@c67d48967507
  build date:       20230201-07:53:32
  go version:       go1.19.5
  platform:         linux/amd64
```

### Prometheus configuration file

```yaml
no relevant config
```

**Comment by roidelapluie** [comment]
It appears that there is a typo in your service file. Instead of --web.console.libaries, it should be --web.console.libraries. You are missing an "r" in 'libaries'. Kindly update that in your service file and restart the service.
