### ISSUE TITLE
add new functions 'consecutive_gt' and 'consecutive_lt'

### ISSUE THREAD

**Issue by uglycow** [prometheus/prometheus#12062]
### Proposal

We set an alert for the latency of our system (something like max(job:latency_quantile95) > 100 ). 
We soon found it was too sensitive because our system would experience inherent latency spikes periodically, I can't explain the details about the spike here, we just can't get ride of it for now. 

![img_2](https://user-images.githubusercontent.com/7302803/223084582-6b1912f3-198f-432c-ba89-93b84cc68a0c.png)

We don't wanna be bothered by those spikes and we decide only to alert if the spike persists for a period of time, say 5 min.
We try to do it like: `(sum_over_time(((sum_over_time((max(job:lantency_quantile95) > bool 100 ) [3m:1m])) >= bool 5)[1d:5m])`. It worked but we found that we are not alarmed when the spike persists 5min and spanned across two 5-min-window. 

We actually want a function to check whether the series satisfies a certain condition consecutively for a range of points.
I checked the code and it turns out that it's quite convenient to add these new functions.
```golang
	"consecutive_gt": {
		Name:       "consecutive_gt",
		ArgTypes:   []ValueType{ValueTypeMatrix, ValueTypeScalar, ValueTypeScalar},
		ReturnType: ValueTypeVector,
	},
	"consecutive_lt": {
		Name:       "consecutive_lt",
		ArgTypes:   []ValueType{ValueTypeMatrix, ValueTypeScalar, ValueTypeScalar},
		ReturnType: ValueTypeVector,
	},
```
We don't wanna maintain our own repo, @roidelapluie plz kindly help review whether it's worth adding these functions to the official repo.
If so, plz help review my pr:

**Comment by roidelapluie** [comment]
Let's continue the discussion in the pull request and figure out the best way to move forward.

**Comment by beorn7** [comment]
Hello from the bug scrub!

As per the discussion on the PR, we are also closing this. As said over there, this should not be a final rejection, but it would need further discussion at the dev-summit, for which you could propose [an agenda item](https://docs.google.com/document/d/1uurQCi5iVufhYHGlBZ8mJMK_freDFKPG0iYBQqJ9fvA/edit?usp=sharing) if you so desire.
