### ISSUE TITLE
Default to now if time paramater not specified in HTTP API

### ISSUE THREAD

**Issue by qed-** [prometheus/prometheus#1207]
As discussed here: https://groups.google.com/forum/#!topic/prometheus-developers/JrU8l0-IKt8 it would be convenient if the GET /api/v1/query endpoint defaulted to 'now' if the time paramater is not specified.

Use case is to allow a client to get the current state of metrics without worrying about clock sync, staleness handling.

**Comment by grobie** [comment]
If people are worried about this being used incorrectly by accident, we could also use something like `last` as special value.

:+1: in general

**Comment by brian-brazil** [comment]
I think making it optional would make sense.

**Comment by fabxc** [comment]
Or `now`? `last` would not describe the semantics quite correctly, as we do not go back to the last visible samples for the query.

Making it optional is very implicit. If I say `?...&timestamp=now`, at least there's little doubt what's happening internally.

**Comment by brian-brazil** [comment]
I'd expect that most users are doing quick lookups the same as in the expression browser and would like things to just work. In that context I'm not seeing much benefit to having them specify an additional magic parameter.

**Comment by fabxc** [comment]
Inserting it without any indicator is more magic. It's almost zero effort to do.
A query is only complete with a timestamp.

**Comment by grobie** [comment]
I don't consider default parameters to be magic. It's a common approach in both HTTP parameters as well as programming functions. The used timestamp will be visible in the result and how to set a timestamp explicitly can be seen in the documentation.

**Comment by jimmidyson** [comment]
:+1: implicit default to now

**Comment by fabxc** [comment]
So be it then :)

**Comment by qed-** [comment]
Thanks all.
