### ISSUE TITLE
Question regarding MQTT

### ISSUE THREAD

**Issue by markfink** [prometheus/prometheus#1210]
hope you do not mind me asking a question in here.

I am looking at time series db solutions / monitoring / visualization tools in the open source space. I must say I like prometheus - awesome job so far! What I would like to learn about is the preferred solution to collect data from mosquitto (e.g. mqtt is used to collect temperature data from many hundreds or maybe thousands of tiny sensors).

As far as I understand you are not into push protocols. So is there a way to add an mqtt subscriber to prometheus maybe as a plugin? For example I know that InfluxDB has this feature built into telegraf. This approach probably scales better but also leads to long data chains …sensor -> mosquitto -> importer -> database. Do you think it would be possible to subscribe prometheus directly to mosquitto maybe as a plugin - without running an importer as a separate process?

For the purpose of learning this stuff... Is there a fork or some other information what it would mean to have a more push oriented prometheus? (I hope this question does not hurt any feelings)!

Best,
Mark

**Comment by brian-brazil** [comment]
From a quick look, I think you'd be looking at a similar approach to the graphite/statsd/collectd exporters and creating an exporter that takes in mqtt and produces appropriate prometheus metrics on the other end.

**Comment by brian-brazil** [comment]
Looks like this is answered.
