### ISSUE TITLE
Add  insecure_skip_verify config into prometheus.yml

### ISSUE THREAD

**Issue by realhuseyn** [prometheus/prometheus#12130]
### Proposal

Hello, everyone. I have a little problem related to the default prometheus.yml config file. Our microservices are running with HTTPS on the Kubernetes cluster. When I deploy prometheus-server with Helm, "prometheus-server" configmap is generated automatically. But...Every time I must add the following config to "job_name: kubernetes-pods" section in ConfigMap:
      tls_config:
        insecure_skip_verify: true
If I don't add this config, prometheus-server can't retrieve the metrics of HTTPS microservices. In this case, I can overwrite all default prometheus.yml configs on values.yml when releasing Helm. But I don't want to overwrite all configs on prometheus.yml. I just need to add "insecure_skip_verify". Could you please help with this issue?

**Comment by machine424** [comment]
Hello,

I don't think it's a good idea, security wise, to make `insecure_skip_verify` a global config field in Prometheus.

You should be able to customize `insecure_skip_verify` for that specific job via the values file, if not you'll need to directly check with the Helm chart's maintainers (on the chart's repo).

To avoid setting `insecure_skip_verify: false` you can provide a CA to prometheus so it case validate the target's certificate against it.
See https://prometheus.io/docs/prometheus/latest/configuration/configuration/#tls_config

For such usage queries, I recommend using slack, for more efficient and prompt interaction.

**Comment by machine424** [comment]
Let's close this, see reasons above.
