### ISSUE TITLE
metric name X does not support exemplars

### ISSUE THREAD

**Issue by rootdarkarchon** [prometheus/prometheus#12136]
### What did you do?

Restarted one of my servers running AspNetCore/Kestrel that exposes a prometheus-net.AspNetCore endpoint.

Prometheus is running in a Docker environment in the same Docker network as this application. Prior to the update there have been no issues.

### What did you expect to see?

Scraping my /metrics should be no issue

### What did you see instead? Under which circumstances?

Prometheus shows `metric name mare_auth_requests_success does not support exemplars`

I attempted to telnet to the metrics endpoint and do a `GET /metrics` with following result, which indicates nothing out of the ordinary for me.

![image](https://user-images.githubusercontent.com/21534284/225124259-78c61bb9-77de-42b6-b65d-0368679f710c.png)

Log also shows:
`caller=scrape.go:1366 level=debug component="scrape manager" scrape_pool=mare target=http://mare:4980/metrics msg="Append failed" err="metric name mare_auth_requests_success does not support exemplars"`

### System information

Linux 5.10.0-21-amd64 x86_64

### Prometheus version

```text
prometheus, version 2.42.0 (branch: HEAD, revision: 225c61122d88b01d1f0eaaee0e05b6f3e0567ac0)
  build user:       root@c67d48967507
  build date:       20230201-07:53:32
  go version:       go1.19.5
  platform:         linux/amd64
```

**Comment by rootdarkarchon** [comment]
Seems like it was an issue with prometheus-net AspNetCore 8.0.0.0

**Comment by 64J0** [comment]
I'm getting this error as well!
