### ISSUE TITLE
Searching in Metrics Explorer is extremely slow

### ISSUE THREAD

**Issue by 414owen** [prometheus/prometheus#12143]
### What did you do?

Opened metrics explorer and searched for a 12-char string.

### What did you expect to see?

Results (pretty quickly)

### What did you see instead? Under which circumstances?

It clearly ran the search for every keystroke, and over our 4565 metrics, this took a few seconds

### Likely cause

~It seems the `nexucis/fuzzy` package is slow~ (or we just have too many metrics)

### Potential solutions

* Find a much faster fuzzy search implementation
* Debounce keypresses in the search field
* Only search on `enter` or button press
* When a search finishes, skip intermediate keystrokes and search only the most up-to-date input value

**Comment by 414owen** [comment]
Actually, when there aren't many results, it's fast (almost instantaneous).  
It's when I search for something very common that the latency is really noticeable.  
Maybe that means it's the actual rendering that's slow?

**Comment by andrzejgorski** [comment]
I Have the same problem

**Comment by beorn7** [comment]
Hello from the bug scrub!

This might all be very different with the new UI. We are closing this and would like to ask you to file a new issue if the new UI has a similar problem.
