### ISSUE TITLE
Expression browser graphs don't deal well with constant timeseries

### ISSUE THREAD

**Issue by bbigras** [prometheus/prometheus#1214]
I'm not sure if this is a bug. It's very probable that I did something wrong.

The metric is the number of requests to nginx. The number of requests is very low. The frequents "bumps" are requests made by nagios (once per 5 minutes I think).

I asked on IRC first and someone said that I should get zeros if all my values are the same.

![image](https://cloud.githubusercontent.com/assets/24027/11127326/d5c56c6e-8941-11e5-8e11-84d4a8fd7149.png)

![image](https://cloud.githubusercontent.com/assets/24027/11127352/f67d0c32-8941-11e5-93fb-f8cdac251d82.png)

**Comment by brian-brazil** [comment]
Can you show us the result in the "Console" view of the expression browser?

**Comment by brunoqc** [comment]
![image](https://cloud.githubusercontent.com/assets/24027/11127850/599e14e4-8944-11e5-9bd1-20363b0fd7ae.png)

----

![image](https://cloud.githubusercontent.com/assets/24027/11127860/65a1b1ce-8944-11e5-9167-19acb2a081c0.png)

**Comment by brian-brazil** [comment]
That's not zero, this is a UI problem.

**Comment by brunoqc** [comment]
I was thinking it was zeros because of the grafana graph :

![image](https://cloud.githubusercontent.com/assets/24027/11128063/709d3de0-8945-11e5-8d33-036ac0216549.png)

**Comment by brian-brazil** [comment]
It's probably worth filing a bug against grafana for better selection of min/max.

**Comment by jimmidyson** [comment]
You can set the min in the graph options.
