### ISSUE TITLE
Docker sunset of free Teams

### ISSUE THREAD

**Issue by DaspawnW** [prometheus/prometheus#12153]
### Proposal

As you are maybe already aware docker/hub-feedback#2314 GitHub will sunset free Teams. This change will lead to frozen public images if the owner doesn't apply to the OpenSource Program or buys the Team. (That's at least my interpretation, but as it's currently a manner of hours until this changes it's also not put into stones).

Is there any plan how prometheus will handle this? Alternatives could be for example github, google, quay or ecr.

Thank you in advance,
Best regards,
Björn

**Comment by roidelapluie** [comment]
Prometheus is available on quai and has applied to the open source tier.
