### ISSUE TITLE
Feature request: Filter queries on metric value

### ISSUE THREAD

**Issue by alexissavin** [prometheus/prometheus#1216]
Starting using Prometheus I'm looking for a way to filter some of my queries on the metric value.
Filter already allow us to select a set of metrics according to labels, but in some case, it would be useful to filter on the metric value.

The easiest example that I have in mind would be to filter "up" query to only retrieve down instances.

http://localhost:9090/api/v1/query?query=up{job="node"}&time=2015-11-13T11:30:00.0Z

Maybe this could be done with a specific function to look like the following ?

http://localhost:9090/api/v1/query?query=filter(<operator>,<compared value>,up{job="node"})&time=2015-11-13T11:30:00.0Z

So that the request would look like this :
http://localhost:9090/api/v1/query?query=filter(gt,0,up{job="node"})&time=2015-11-13T11:30:00.0Z

Thanks for your feedback.

**Comment by fabxc** [comment]
Sounds like you simply want `up{job="node"} == 1`.
Comparison operations do filter by default.

**Comment by alexissavin** [comment]
Oh, great :-)

I did not understood this from "http://prometheus.io/docs/querying/operators/".

Thank you very much for your quick reply.
