### ISSUE TITLE
how to calculate the value of container_fs_usage_bytes

### ISSUE THREAD

**Issue by yikai116** [prometheus/prometheus#12160]
### What did you do?

I get the value of container_fs_usage_bytes of one pod, but the value don't match any value I got in pod using 'df -h'

### What did you expect to see?

I want to know the calculate rule of container_fs_usage_bytes

### What did you see instead? Under which circumstances?

xx

### System information

xx

### Prometheus version

```text
xx
```

### Prometheus configuration file

```yaml
xx
```

### Alertmanager version

```text
xx
```

### Alertmanager configuration file

```yaml
xx
```

### Logs

```text
xx
```

**Comment by beorn7** [comment]
Hello from the bug scrub!

This metrics comes from cadvisor. You could use the support channels of that project. Alternatively, it might work to use Prometheus community channels listed on https://prometheus.io/community/ . Generally, asking usage questions in GH issues isn't a good way to get answers.
