### ISSUE TITLE
include_scrape_configs

### ISSUE THREAD

**Issue by datamuc** [prometheus/prometheus#12177]
### What did you do?

Well, none of the templates really apply to this kind of thing.

`include_scrape_configs` here does not exist anywhere. In the documentation it is referred to as `scrape_config_files`.

You might also fix the release notes and the blog article.

### What did you see instead? Under which circumstances?

yada

**Comment by roidelapluie** [comment]
https://github.com/prometheus/prometheus/pull/12178

**Comment by roidelapluie** [comment]
Sorry about this! I based the changelog on the pull request name, which was a temporary name

**Comment by roidelapluie** [comment]
We have fixed this.
