### ISSUE TITLE
out of bound fix

### ISSUE THREAD

**Issue by chris-fengtian-guo** [prometheus/prometheus#12183]
### Proposal

A) A16 Conclusion For the fix out of bound problem - this problem has two triggers - the experiment also illustrates the principle of prometheus -
1) When prometheus is running - the data will be stored in the /data/prome_db directory - wal is the temporary storage record file of the data collected by the tsdb head from the exporter - (the situation that triggers the bug - such as modifying the system time from 2023-03-22 To the future time 2024-03-22, the timestamp of these new indicator data will start from 2024-03-22 and be recorded in the wal or checkpoint file under wal)
2) When prometheus runs longer than 2 hours, it will write the tsdb head memory data to the permanent disk block block file - for example, the timestamp of the indicator data in the block is the time in the next 1 year - 2024-03-21 20:00: 00 Therefore - when prometheus starts - the memory database tsdb head requires that the newly added timestamp must be greater than this - otherwise, an out of bound error will be reported
-/data/prome_db/01HSHD0NXQKH1Y4V0AZ8J2V69P 2024-03-21 18:00:01 +0000 UTC 2024-03-21 20:00:00 +0000 UTC 1h59m58.514s
3) Solution - it is a tool - stop promehteus service - delete /data/prome_db/wal, /data/prome_db/ disk block block if the timestamp is newer than the current now() time, delete it - for example 01HSHD0NXQKH1Y4V0AZ8J2V69P - restart promethes

B) of course you can provide patch and it's complex solution 
to drop the head wal of series and samples in future.  and patch for remove tsdb block which in future tine  

C) simple solution and script to fix out of bound
```
import os
import re
import shutil
import subprocess
import time
import os
import subprocess
import time
import shutil
from datetime import datetime
import argparse
import re

def delete_newer_blocks(prometheus_data_path):
    # promtool 命令和数据目录
    promtool_cmd = "promtool"
    blocks_path = prometheus_data_path

    # 获取当前时间戳 (毫秒)
    current_timestamp = int(time.time() * 1000)

    # 执行 promtool 命令，获取 block 列表
    cmd = [promtool_cmd, "tsdb", "list", prometheus_data_path]
    print(f"Executing command: {' '.join(cmd)}")
    cmd_output = subprocess.check_output(cmd).decode('utf-8')

    # 解析命令输出，逐行处理
    for line in cmd_output.splitlines():
        # 跳过标题行
        if line.startswith("BLOCK") or line.startswith("====="):
            continue

        # 分割行数据
        fields = line.split()

        # 获取 block 目录、min 时间戳和 max 时间戳
        block_dir = fields[0]
        min_timestamp = int(fields[1])
        max_timestamp = int(fields[2])

        # 将时间戳转换为可读格式
        min_time_readable = datetime.fromtimestamp(min_timestamp / 1000).strftime('%Y-%m-%d %H:%M:%S')
        max_time_readable = datetime.fromtimestamp(max_timestamp / 1000).strftime('%Y-%m-%d %H:%M:%S')

        # 输出 block 目录、时间戳信息和可读时间格式
        print(f"Block directory: {block_dir}, Min time: {min_timestamp} ({min_time_readable}), Max time: {max_timestamp} ({max_time_readable})")

        # 如果 max 时间戳比当前时间新，删除 block 目录
        if max_timestamp > current_timestamp:
            block_path = os.path.join(blocks_path, block_dir)
            print(f"Removed newer block: {block_path}")
            shutil.rmtree(block_path)
        else:
            print(f"Keeping block: {block_dir}")


parser = argparse.ArgumentParser()
parser.add_argument('--storage_path', default=None, help='Prometheus database storage directory.')
args = parser.parse_args()

if args.storage_path:
    storage_path = args.storage_path
else:
    with open('/etc/default/prometheus', 'r') as f:
        contents = f.read()

    pattern = r'storage\.tsdb\.path=(\S+)'
    match = re.search(pattern, contents)
    if match:
        storage_path = match.group(1)
        print(storage_path)  # 输出 /data/prome_db
    else:
        print('未找到 storage.tsdb.path')


# 停止 prometheus 服务
print("停止 prometheus 服务")
subprocess.run(["systemctl", "stop", "prometheus"])

WAIT_TIME = 5
print(f"sleep {WAIT_TIME} seconds")
time.sleep(WAIT_TIME)

# 删除 wal 目录
print("删除 wal 目录")
wal_path = os.path.join(storage_path, "wal")
if os.path.exists(wal_path):
    shutil.rmtree(wal_path)

# 删除 chunks_head 目录
print("删除 chunks_head 目录")
chunks_head_path = os.path.join(storage_path, "chunks_head")
if os.path.exists(chunks_head_path):
    shutil.rmtree(chunks_head_path)

# 删除 lock 文件
print("删除 lock 文件")
lock_file = os.path.join(storage_path, "lock")
if os.path.isfile(lock_file):
    os.remove(lock_file)

# 删除 queries.active 文件
print("删除 queries.active 文件")
queries_active_file = os.path.join(storage_path, "queries.active")
if os.path.isfile(queries_active_file):
    os.remove(queries_active_file)

print("删除 未来时间戳的tsdb block")
delete_newer_blocks(storage_path)

#启动 prometheus 服务
print("启动 prometheus 服务")
subprocess.run(["systemctl", "start", "prometheus"])
```

**Comment by bboreham** [comment]
This appears to be a suggestion to fix some problem.
I'm sorry but I did not understand it.

Prometheus has recently added "out-of-order" support, which also allows you to write data that previously would have errored as "out of bounds".

**Comment by chris-fengtian-guo** [comment]
Following is example of out of bound and the script fix it

1）for example the time of system where prometheus run is not current time 
[root@hs32 ~]# date
Tue Apr 25 00:48:42 CST 2023
2) change system time to current time and prometheus will out of bound error
[root@hs32 ~]# date -s '2023-04-24 16:44:00'
Mon Apr 24 16:44:00 CST 2023
[root@hs32 ~]# 
3) the script fix the out of bound
[root@hs32 ~]# python3 ./prometheus_out_of_bound_fix.py 
/data/prome_db
停止 prometheus 服务
sleep 5 seconds
删除 wal 目录
删除 chunks_head 目录
删除 lock 文件
删除 queries.active 文件
删除 未来时间戳的tsdb block
Executing command: promtool tsdb list /data/prome_db
Block directory: 01GS0PR2RBBFBQHHTAVFVZZ7ZV, Min time: 1675323599985 (2023-02-02 15:39:59), Max time: 1676116800000 (202
Keeping block: 01GS0PR2RBBFBQHHTAVFVZZ7ZV
Block directory: 01GTMV9ACZAXG9VZSYV866HS8R, Min time: 1676116801486 (2023-02-11 20:00:01), Max time: 1677866400000 (202
Keeping block: 01GTMV9ACZAXG9VZSYV866HS8R
Block directory: 01GW8ZTGFEY4YZX9HXMAQEEK0R, Min time: 1677866401486 (2023-03-04 02:00:01), Max time: 1679616000000 (202
Keeping block: 01GW8ZTGFEY4YZX9HXMAQEEK0R
Block directory: 01GXX4BNKTY30HR3QVAFJ5XGGN, Min time: 1679616001486 (2023-03-24 08:00:01), Max time: 1681365600000 (202
Keeping block: 01GXX4BNKTY30HR3QVAFJ5XGGN
Block directory: 01GYEGHDZ97H1QSJ69AK58RC8P, Min time: 1681365601486 (2023-04-13 14:00:01), Max time: 1681948800000 (202
Keeping block: 01GYEGHDZ97H1QSJ69AK58RC8P
Block directory: 01GYM9YQB1MWMF9QG3S27FE2J1, Min time: 1681948801486 (2023-04-20 08:00:01), Max time: 1682143200000 (202
Keeping block: 01GYM9YQB1MWMF9QG3S27FE2J1
Block directory: 01GYP7QJ6E1KCE0PTBS5ZM089Q, Min time: 1682143201486 (2023-04-22 14:00:01), Max time: 1682208000000 (202
Keeping block: 01GYP7QJ6E1KCE0PTBS5ZM089Q
Block directory: 01GYR5H2SGV5SKB9QA452P3XWY, Min time: 1682208001486 (2023-04-23 08:00:01), Max time: 1682272800000 (202
Keeping block: 01GYR5H2SGV5SKB9QA452P3XWY
Block directory: 01GYRT486FQ0KDMP64B09RGNVA, Min time: 1682272801486 (2023-04-24 02:00:01), Max time: 1682294400000 (202
Keeping block: 01GYRT486FQ0KDMP64B09RGNVA
Block directory: 01GYSX3NR3WRE9VW90GNG7XBDV, Min time: 1682294400000 (2023-04-24 08:00:00), Max time: 1682316000000 (202
Keeping block: 01GYSX3NR3WRE9VW90GNG7XBDV
Block directory: 01GYSX3NEDQ31WH28NZNY9X88C, Min time: 1682316001486 (2023-04-24 14:00:01), Max time: 1682323200000 (202
Keeping block: 01GYSX3NEDQ31WH28NZNY9X88C
启动 prometheus 服务

**Comment by chris-fengtian-guo** [comment]
1) to explain you dont't understand and I add english comment for the code and maybe chinese comment is confused  
import os
import re
import shutil
import subprocess
import time
import os
import subprocess
import time
import shutil
from datetime import datetime
import argparse
import re

def delete_newer_blocks(prometheus_data_path):
    # promtool command and data directory
    # promtool 命令和数据目录
    promtool_cmd = "promtool"
    blocks_path = prometheus_data_path

    # Get the current timestamp (milliseconds)
    # 获取当前时间戳 (毫秒)
    current_timestamp = int(time.time() * 1000)

    # Execute the promtool command to get the block list
    # 执行 promtool 命令，获取 block 列表
    cmd = [promtool_cmd, "tsdb", "list", prometheus_data_path]
    print(f"Executing command: {' '.join(cmd)}")
    cmd_output = subprocess.check_output(cmd).decode('utf-8')

    # Parse the command output and process it line by line
    # 解析命令输出，逐行处理
    for line in cmd_output.splitlines():
        # Skip the header line
        # 跳过标题行
        if line.startswith("BLOCK") or line.startswith("====="):
            continue

        # Split the line data
        # 分割行数据
        fields = line.split()

        # Get the block directory, min timestamp, and max timestamp
        # 获取 block 目录、min 时间戳和 max 时间戳
        block_dir = fields[0]
        min_timestamp = int(fields[1])
        max_timestamp = int(fields[2])

        # Convert timestamps to readable format
        # 将时间戳转换为可读格式
        min_time_readable = datetime.fromtimestamp(min_timestamp / 1000).strftime('%Y-%m-%d %H:%M:%S')
        max_time_readable = datetime.fromtimestamp(max_timestamp / 1000).strftime('%Y-%m-%d %H:%M:%S')

        # Print the block directory, timestamp information, and readable time format
        # 输出 block 目录、时间戳信息和可读时间格式
        print(f"Block directory: {block_dir}, Min time: {min_timestamp} ({min_time_readable}), Max time: {max_timestamp} ({max_time_readable})")

        # If the max timestamp is newer than the current time, delete the block directory
        # 如果 max 时间戳比当前时间新，删除 block 目录
        if max_timestamp > current_timestamp:
            block_path = os.path.join(blocks_path, block_dir)
            print(f"Removed newer block: {block_path}")
            shutil.rmtree(block_path)
        else:
            print(f"Keeping block: {block_dir}")


parser = argparse.ArgumentParser()
parser.add_argument('--storage_path', default=None, help='Prometheus database storage directory.')
args = parser.parse_args()

if args.storage_path:
    storage_path = args.storage_path
else:
    with open('/etc/default/prometheus', 'r') as f:
        contents = f.read()

    pattern = r'storage\.tsdb\.path=(\S+)'
    match = re.search(pattern, contents)
    if match:
        storage_path = match.group(1)
        print(storage_path)  # Output /data/prome_db
        print("输出 /data/prome_db")
    else:
        print('Storage.tsdb.path not found')
        print('未找到 storage.tsdb.path')


# Stop the prometheus service
#

# 停止 prometheus 服务
print("Stopping prometheus service")
print("停止 prometheus 服务")
subprocess.run(["systemctl", "stop", "prometheus"])

WAIT_TIME = 5
print(f"Sleeping {WAIT_TIME} seconds")
print(f"sleep {WAIT_TIME} seconds")
time.sleep(WAIT_TIME)

# Delete the wal directory
# 删除 wal 目录
print("Deleting wal directory")
print("删除 wal 目录")
wal_path = os.path.join(storage_path, "wal")
if os.path.exists(wal_path):
    shutil.rmtree(wal_path)

# Delete the chunks_head directory
# 删除 chunks_head 目录
print("Deleting chunks_head directory")
print("删除 chunks_head 目录")
chunks_head_path = os.path.join(storage_path, "chunks_head")
if os.path.exists(chunks_head_path):
    shutil.rmtree(chunks_head_path)

# Delete the lock file
# 删除 lock 文件
print("Deleting lock file")
print("删除 lock 文件")
lock_file = os.path.join(storage_path, "lock")
if os.path.isfile(lock_file):
    os.remove(lock_file)

# Delete the queries.active file
# 删除 queries.active 文件
print("Deleting queries.active file")
print("删除 queries.active 文件")
queries_active_file = os.path.join(storage_path, "queries.active")
if os.path.isfile(queries_active_file):
    os.remove(queries_active_file)

print("Deleting TSDB blocks with future timestamps")
print("删除 未来时间戳的tsdb block")
delete_newer_blocks(storage_path)

# Start the prometheus service
# 启动 prometheus 服务
print("Starting prometheus service")
print("启动 prometheus 服务")
subprocess.run(["systemctl", "start", "prometheus"])

**Comment by chris-fengtian-guo** [comment]
> This appears to be a suggestion to fix some problem. I'm sorry but I did not understand it.
> 
> Prometheus has recently added "out-of-order" support, which also allows you to write data that previously would have errored as "out of bounds".

1) so I don't know my script for fix out of bound is valuable ? 
and if it's useful and I don't know where to put the script ?
2) I don't if you have similar patch or script solution for out of bound ?

**Comment by bboreham** [comment]
OK I think I get a better idea where your problem arises - somehow you got future timestamps into TSDB, and then it won't accept data older than that.

> the future time 2024-03-22

Do you know how this happened?  Typically Prometheus is used to ingest data "now".

**Comment by chris-fengtian-guo** [comment]
> 
1) This happen typically , ntp change the system time or manual change system time to future time (for example one day in future)
and prometheus tsdb begin ingest data of future timestame from scrape of exporter and run for more than 2 hours , for examples run few days
2) change system time back to now and out of bound happen

**Comment by chris-fengtian-guo** [comment]
10 Experiment - I modified the system time to one year later - 2024 - performed a night of prometheus data writing - found that the disk database file 01HSHD0NXQKH1Y4V0AZ8J2V69P has been generated - then I need to dump the timestamps of indicators in these files - and then set the system time The modification will be in the normal time of 2023 - then it should trigger an out of bound error - then it is expected that 01HSHD0NXQKH1Y4V0AZ8J2V69P will not affect the tsdb head, and you only need to delete wal and chunks_head to restart prometheus and then import the time stamp into the tsdb head without the timestamp will not trigger out of bound errors
[root@hs25 prometheus_related]# promtool tsdb list -r /data/prome_db
BLOCK ULID                  MIN TIME                       MAX TIME                       DURATION       NUM SAMPLES  NUM CHUNKS   NUM SERIES   SIZE
01HSHKWG3KEGMM6QYVZH8SGZBA  2024-03-21 07:03:34 +0000 UTC  2024-03-21 18:00:00 +0000 UTC  10h56m25.094s  4448473      34754        3788         10MiB503KiB218B
01HSHD0NXQKH1Y4V0AZ8J2V69P  2024-03-21 18:00:01 +0000 UTC  2024-03-21 20:00:00 +0000 UTC  1h59m58.514s   911520       7596         3788         2MiB385KiB543B
01HSHKWD5QS2V5579H2CTPX4CR  2024-03-21 20:00:01 +0000 UTC  2024-03-21 22:00:00 +0000 UTC  1h59m58.514s   911520       7596         3788         2MiB438KiB914B
01HSHTR4DQ5C10CY8K32G9WJT8  2024-03-21 22:00:01 +0000 UTC  2024-03-22 00:00:00 +0000 UTC  1h59m58.514s   911520       7596         3788         2MiB323KiB702B
2 Then modify the system time to the correct time - date -s '2023-03-22 09:54:00' - produce an out of bound error

**Comment by chris-fengtian-guo** [comment]
> 

my above expirement comment is chinese and I just translate with google to english and maybe comment not accureate

**Comment by bboreham** [comment]
OK, I think I understand, once you get some data with timestamps way off the current time, you can't get Prometheus to accept more data at the current time.

We could document this better, and add a possible recovery procedure to delete the head and WAL data as you suggest.

However, [the new "out-of-order sample" feature](https://github.com/prometheus/prometheus/pull/11075) will allow you to continue working without deleting data.

**Comment by bboreham** [comment]
No further updates; closing.
