### ISSUE TITLE
Prometheus pod is not coming up with error "runutil.go:101 msg="function failed. Retrying in next tick" err="trigger reload"

### ISSUE THREAD

**Issue by rajani-konreddy** [prometheus/prometheus#12181]
### What did you do?

1. Deployed prometheus
![image](https://user-images.githubusercontent.com/104550831/227485957-0615d63a-ff63-4136-975b-5d40244dceb2.png)

3. Prometheus pod is not coming up with below error. found in config-reloader container logs

# kubectl logs pod/prometheus-eccs-central-prometheus-0 -n eccs-monitoring -c config-reloader
level=info ts=2023-03-24T09:34:48.083513445Z caller=main.go:111 msg="Starting prometheus-config-reloader" version="(version=0.55.0, branch=refs/tags/v0.55.0, revision=fd0fe0aed99a6a178197f302c06982ad7473a900)"
level=info ts=2023-03-24T09:34:48.083564113Z caller=main.go:112 build_context="(go=go1.17.7, user=Action-Run-ID-1963576315, date=20220310-14:16:37)"
level=info ts=2023-03-24T09:34:48.083905875Z caller=main.go:149 msg="Starting web server for metrics" listen=:8080
level=error ts=2023-03-24T09:35:18.089876736Z caller=runutil.go:101 msg="function failed. Retrying in next tick" err="trigger reload: reload request failed: Post \"https://127.0.0.1:9090/-/reload\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
level=error ts=2023-03-24T09:35:48.090565685Z caller=runutil.go:101 msg="function failed. Retrying in next tick" err="trigger reload: reload request failed: Post \"https://127.0.0.1:9090/-/reload\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
level=error ts=2023-03-24T09:36:18.091634537Z caller=runutil.go:101 msg="function failed. Retrying in next tick" err="trigger reload: reload request failed: Post \"https://127.0.0.1:9090/-/reload\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
level=error ts=2023-03-24T09:36:18.795917042Z caller=runutil.go:101 msg="function failed. Retrying in next tick" err="trigger reload: reload request failed: Post \"https://127.0.0.1:9090/-/reload\": unexpected EOF"
level=error ts=2023-03-24T09:36:53.089553868Z caller=runutil.go:101 msg="function failed. Retrying in next tick" err="trigger reload: reload request failed: Post \"https://127.0.0.1:9090/-/reload\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
level=error ts=2023-03-24T09:37:23.090635769Z caller=runutil.go:101 msg="function failed. Retrying in next tick" err="trigger reload: reload request failed: Post \"https://127.0.0.1:9090/-/reload\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
level=error ts=2023-03-24T09:37:52.211857721Z caller=runutil.go:101 msg="function failed. Retrying in next tick" err="trigger reload: reload request failed: Post \"https://127.0.0.1:9090/-/reload\": unexpected EOF"

### What did you expect to see?

Expected: Prometheus pod should be up and running

### What did you see instead? Under which circumstances?

# kubectl logs pod/prometheus-eccs-central-prometheus-0 -n eccs-monitoring -c config-reloader
level=info ts=2023-03-24T09:34:48.083513445Z caller=main.go:111 msg="Starting prometheus-config-reloader" version="(version=0.55.0, branch=refs/tags/v0.55.0, revision=fd0fe0aed99a6a178197f302c06982ad7473a900)"
level=info ts=2023-03-24T09:34:48.083564113Z caller=main.go:112 build_context="(go=go1.17.7, user=Action-Run-ID-1963576315, date=20220310-14:16:37)"
level=info ts=2023-03-24T09:34:48.083905875Z caller=main.go:149 msg="Starting web server for metrics" listen=:8080
level=error ts=2023-03-24T09:35:18.089876736Z caller=runutil.go:101 msg="function failed. Retrying in next tick" err="trigger reload: reload request failed: Post \"https://127.0.0.1:9090/-/reload\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
level=error ts=2023-03-24T09:35:48.090565685Z caller=runutil.go:101 msg="function failed. Retrying in next tick" err="trigger reload: reload request failed: Post \"https://127.0.0.1:9090/-/reload\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
level=error ts=2023-03-24T09:36:18.091634537Z caller=runutil.go:101 msg="function failed. Retrying in next tick" err="trigger reload: reload request failed: Post \"https://127.0.0.1:9090/-/reload\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
level=error ts=2023-03-24T09:36:18.795917042Z caller=runutil.go:101 msg="function failed. Retrying in next tick" err="trigger reload: reload request failed: Post \"https://127.0.0.1:9090/-/reload\": unexpected EOF"
level=error ts=2023-03-24T09:36:53.089553868Z caller=runutil.go:101 msg="function failed. Retrying in next tick" err="trigger reload: reload request failed: Post \"https://127.0.0.1:9090/-/reload\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
level=error ts=2023-03-24T09:37:23.090635769Z caller=runutil.go:101 msg="function failed. Retrying in next tick" err="trigger reload: reload request failed: Post \"https://127.0.0.1:9090/-/reload\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
level=error ts=2023-03-24T09:37:52.211857721Z caller=runutil.go:101 msg="function failed. Retrying in next tick" err="trigger reload: reload request failed: Post \"https://127.0.0.1:9090/-/reload\": unexpected EOF"

**Comment by afokin52** [comment]
Faced the same problem. Having deployed Prometheus with the help of Helm in Kubernetes.

**Comment by beorn7** [comment]
Hello from the bug scrub!

Sorry for no response here in 1½ years. We suspect this is not a bug in Prometheus but some configuration issue, so we close this issue now. We hope that you could solve it in the meantime.
