### ISSUE TITLE
Allow setting (web-config) TLS parameters via command line parameters

### ISSUE THREAD

**Issue by frittentheke** [prometheus/prometheus#12195]
### Proposal

To get this out of the way: I know support for ENV parameters has come up time and again and I do not want to ask for this feature again.

I just discovered the recently added capability of systemd to provide credentials to a service at runtime. See https://systemd.io/CREDENTIALS/ for how this works.

In short a credential `foobar` can be read from a file `/etc/myfoobarcredential.txt` by adding `LoadCredential=foobar:/etc/myfoobarcredential.txt` to the unit. On the consuming end an environment variable `$CREDENTIALS_DIRECTORY` is provided which then contains files named with the credential name that was loaded. So in essence the path for a secret is dynamic.

When using this feature to give TLS certificate and key to Prometheus the path in the `web-config.yml` pointing to those files would need to be dynamic. While this would yet be another use-case for env variable replacement in config files, I am more wondering about the reasoning behind config options available as command line options. Having read https://prometheus.io/docs/prometheus/latest/configuration/https/ I know the TLS feature is experimental and also that the `web-config.yml` file is read on every HTTP request. 

Since systemd also has the `%d` specifier which can be used for e.g. command line arguments to set the `$CREDENTIALS_DIRECTORY`, this cannot be used as Prometheus only takes TLS parameters via config file.
The usual recommendation to use `envsubst` or `sed` (https://www.robustperception.io/environment-substitution-with-docker/) does work but in non containerized environment the generated config file will then remain on disk (compared to a container only having an ephemeral FS), makes this all look rather ugly and hacky.

In essence I am asking about adding the tls settings to the list of `web.*` command line parameters  like ...
```
[...]
--web.listen-address="0.0.0.0:9090"   
--web.max-connections=512
--web.console.templates="consoles"
--web.console.libraries="console_libraries"
--web.page-title="Prometheus Time Series Collection and Processing Server"             
--web.cors.origin=".*"
[...]
```

I am also wondering about plans on removing the experimental label from the TLS feature?

**Comment by frittentheke** [comment]
> Hello, we are discussion a new way to manage secrets with providers. Systemd could be one of those providers. I will keep this in my name.

@roidelapluie may I gently nag you for an update on this matter?

**Comment by beorn7** [comment]
Hello from the bug scrub!

Note that there has been a proposal a while ago that might help with this:  https://docs.google.com/document/d/1EqHd2EwQxf9SYD8-gl3sgkwaU6A10GhiN7aw-2kx7NU/edit?usp=sharing 

Sadly, this proposal fell stale somehow. We'll add a dev-summit item to find out how we can revive it.

We'll close this issue for now. If you feel the above proposal is not what you need, please follow up.
