### ISSUE TITLE
scrape_config_files missing in configuration schema @ json.schemastore.org

### ISSUE THREAD

**Issue by mbelangergit** [prometheus/prometheus#12194]
### What did you do?

I'm using the new `scrape_config_files` configuration parameter in my `prometheus.yml`.

### What did you expect to see?

Not getting errors form my tool chain.

### What did you see instead? Under which circumstances?

The VSCode [YAML extension][yaml] is flagging it as problem: `Property scrape_config_files is not allowed.`

[yaml]: https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml

Same on the linter side. I'm using [Mega-Linter][mega-linter] and it calls [v8r][v8r], a tool that checks the validity of JSON/YAML files if they have a matching schema defined on [schemastore.org][schemastore]. `prometheus.yml is invalid, must NOT have additional properties`

[mega-linter]: https://megalinter.io/latest
[v8r]: https://github.com/chris48s/v8r
[schemastore]: https://www.schemastore.org/json

### System information

VSCode on Windows 10

### Prometheus version

```text
prometheus, version 2.43.0 (branch: HEAD, revision: edfc3bcd025dd6fe296c167a14a216cab1e552ee)
  build user:       root@8a0ee342e522
  build date:       20230321-12:56:07
  go version:       go1.19.7
  platform:         linux/amd64
  tags:             netgo,builtinassets
```

### Prometheus configuration file

```yaml
---
global:
  scrape_interval: 15s

scrape_config_files:
  - external-scrape-configs.yml
```

### Alertmanager version

```text
N/A
```

### Alertmanager configuration file

```yaml
N/A
```

### Logs

```text
N/A
```

**Comment by jkuester** [comment]
We should be able to close this issue now that https://github.com/SchemaStore/schemastore/pull/2904 has been merged. (I am seeing the new schema correctly in WebStorm.)  @mbelangergit can you confirm?

**Comment by mbelangergit** [comment]
Yes, both the VSCode YAML extension and v8r are now accepting the `scrape_config_files` tag.

The issue can be closed.

Thanks!
