### ISSUE TITLE
Can we just ignore the invalid series and retain the remaining valid series when encounter an error during parsing the metrics document?

### ISSUE THREAD

**Issue by arvonh** [prometheus/prometheus#12201]
### What did you do?

I wrote a prometheus client with lua, and I had some label whose name is invalid for prometheus. this can result that prometheus saves nothing from my metrics document.

### What did you expect to see?

 just ignore the invalid series and retain the remaining valid series 

### What did you see instead? Under which circumstances?

all series are skipped.

### System information

Linux

### Prometheus version

```text
v2.29.1
```

**Comment by arvonh** [comment]
When a scraper scrapes a metrics document from a certain target, it will parse this doc. when encounter an error(sth like an illegal label name) , it will skip parsing and rollback the entire document. so we wont save any series. my question is : can we just ignore the invalid series, and keep other valid series?

**Comment by roidelapluie** [comment]
We have intentionally chosen not to allow for the retention of invalid series when encountered during parsing. It is recommended that you remove any incorrect metrics at the source to avoid the hard failures that can result from such errors. This decision was made with the belief that hard failures are easier to reason about than partially accurate data that could be rendered useless without any knowledge of its accuracy.
