### ISSUE TITLE
Default relabelling to (.*) and $1 ?

### ISSUE THREAD

**Issue by brian-brazil** [prometheus/prometheus#1222]
Relabelling has a lot of irreducible complexity due to the abundance of different configurations we must allow for, however I think there's some scope for making the syntax a little easier.

I propose that we default the regex to `(.*)` and the replacement to `$1`. The effect of this is that copies and setting static labels will both be much easier, both of which are very common uses.

```
- regex: .*
  replacement: staticvalue
  target_label: myLabel
- source_labels: [src]
  regex: (.*)
  replacement: $1
  target_label: myLabel
```
would become

```
- replacement: staticvalue
  target_label: myLabel
- source_labels: [src]
  target_label: myLabel
```

This is a small bit magic which may cause confusion, but overall I think it'd be a benefit.

@fabxc @beorn7 @juliusv

**Comment by fabxc** [comment]
That's a good idea :+1:

**Comment by juliusv** [comment]
:+1:

**Comment by beorn7** [comment]
:+1:

**Comment by jimmidyson** [comment]
Should the default regex actually be `(.+)` so at least something should be present?

**Comment by fabxc** [comment]
Then the case for assigning a static value wouldn't work. No source labels are present, so the concatenated value is the empty string, `.+` wouldn't mach, and the replacement would be skipped.

Did you see an issue with `.*` for any particular case?

**Comment by jimmidyson** [comment]
Good point.

The problem was actually with Kubernetes discovery (of course ;)) where we relabel the metrics path from the service annotation, but this was setting empty path if there was no annotation. I'll update the config there instead.

Closing.
