### ISSUE TITLE
prometheus Historical Data is not loading in grafana UI.

### ISSUE THREAD

**Issue by sarikagupta1206** [prometheus/prometheus#12226]
### What did you do?

I am using grafana, prometheus and thanos with helm chart as below versions::

**NAME NAMESPACE REVISION UPDATED STATUS CHART APP VERSION

grafana metrics-monitoring 7 2023-02-20 21:09:04.114125 +0530 IST deployed grafana-6.40.2 9.1.7

kube-prometheus metrics-monitoring 13 2023-04-04 15:25:22.056237 +0530 IST deployed kube-prometheus-8.1.11 0.60.1

thanos metrics-monitoring 28 2023-04-04 19:37:22.2219 +0530 IST deployed thanos-12.3.2 0.31.0 **:

**Thanos sidecar is giving below error:

kubectl logs prometheus-kube-prometheus-prometheus-0 -c thanos-sidecar -n metrics-monitoring | grep -i err
level=warn ts=2023-04-04T13:56:10.602322752Z caller=shipper.go:239 msg="reading meta file failed, will override it" err="failed to read /prometheus/thanos.shipper.json: open /prometheus/thanos.shipper.json: no such file or directory"**:

**prometheus is giving :

kubectl logs prometheus-kube-prometheus-prometheus-0 -c prometheus -n metrics-monitoring | grep -i err
ts=2023-04-04T13:58:16.736Z caller=scrape.go:1328 level=debug component="scrape manager" scrape_pool=serviceMonitor/metrics-monitoring/kube-prometheus-kubelet/0 target=https://192.168.99.36:10250/metrics msg="Scrape failed" err="Get "https://...:10250/metrics": context deadline exceeded"**:

**Thanos qurier is giving:

kubectl logs thanos-compactor-6bb55c5b9c-tt7s7 -n metrics-monitoring | grep -i err
level=error ts=2023-04-04T14:08:06.085358495Z caller=compact.go:593 msg="retriable error" err="BaseFetcher: iter bucket: The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint."**:

Kubectl logs thanos-bucketweb-7c5548c7c-fv55f -n metrics-monitoring | grep -i err
level=error ts=2023-04-04T14:07:57.252342655Z caller=runutil.go:100 msg="function failed. Retrying in next tick" err="BaseFetcher: iter bucket: The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.":

**Comment by alexgreenbank** [comment]
Hello from the bug scrub.

Apologies for the delay. We hope you have found a resolution for this, closing as there was no follow up.

For troubleshooting it is best to go to the various community resources via https://prometheus.io/community/
