### ISSUE TITLE
Getting duplicate alerts if we remove the Thanos Ruler

### ISSUE THREAD

**Issue by SanthoshiMekala** [prometheus/prometheus#12221]
### What did you do?

Hi All,

In production we have around 25000 targets and because of huge load we opted for Prometheus shards instead of single Prometheus server and implemented Thanos components for the aggregation. Our thanos architecture comprises three components,
Prometheus shards - For scraping and storing the metrics in local storage.
Thanos query - For viewing the TSDB data globally from all the prometheus shards.
Thanos ruler - For storing the output of processed rules and Alerting system will get data from this and alerts based on the condition.

As per the Thanos documentation (https://thanos.io/tip/components/rule.md/#rule-aka-ruler), it is not recommended to use Thanos Ruler except in some specific cases. So, we tried migrating all the recording and alerting rules to Prometheus shards and removed Thanos ruler. We have 7 replicas for Prometheus shards, due to the above change, we are getting duplicate alerts (7 alerts) for each rule. Multiple shards will scrape the targets of single namespace and the rules execution is being done locally in Prometheus shards and as a result, we are getting duplicate results.

Is it the expected behaviour? Is it the recommended approach when we have multiple replicas for Prometheus shards, we need to use Thanos Ruler? Or Thanos ruler is not needed for our scenario?

Thank you!

### What did you expect to see?

We expected single alert for single rule

### What did you see instead? Under which circumstances?

We are getting as many number of alerts as the number of prometheus shards.

### Prometheus version

```text
Recently we have upgraded our Thanos and Prometheus versions to the below ones.
Thanos: from 0.23.0 to 0.29.0
Prometheus: from 2.34.0 to 2.40.0.
```

**Comment by roidelapluie** [comment]
Hi, thank you for reaching out. Can you please provide more details about the alerts and how they differ? Specifically, do the alerts contain the same information or are they different in some way? Do they have the same labels or are some labels different? Any additional details you can provide will be helpful in understanding the behavior you are seeing.

**Comment by SanthoshiMekala** [comment]
Hi @roidelapluie the labels and the content of the alerts are same. For each Prometheus shard, it is triggerring single alert. So, only the shard is different for all the alerts.

**Comment by SanthoshiMekala** [comment]
We have configured the relabel configurations. But after removing the thanos-ruler, we kept all the recording rules in all the Prometheus shards. So, the rules are getting executed locally in all the shards and firing the alerts in all the shards. As a result, we are getting the duplicate alerts. Is it the expected behaviour? We expected that even though we kept the rules in Prometheus shards, the evaluation and alert firing would be global.

**Comment by roidelapluie** [comment]
It would be helpful to know how the alerts differ. Do you have a screenshot of 2 alerts that you think should be 1?

**Comment by SanthoshiMekala** [comment]
In the attached screenshot, the alerts are getting fired two times, one from prometheus-shard-0 and one from prometheus-shard-1. But both the alerts are same.
<img width="725" alt="DuplicateAlertsPerShard" src="https://user-images.githubusercontent.com/39329333/231369317-e9684280-446f-4229-8fe9-8f0e25098f9a.PNG">

**Comment by roidelapluie** [comment]
Okay, I better understand now. The issue is with Thanos, I would therefore recommend you to open an issue / discussion in the thanos repository.

Thanks!

**Comment by SanthoshiMekala** [comment]
Thank you @roidelapluie I will create an issue and check with the Thanos team.
