### ISSUE TITLE
I hope to be able to see the number of all series and the total number of samples.

### ISSUE THREAD

**Issue by luzejia** [prometheus/prometheus#12238]
### Proposal

The values ​​of series and chunk in the tsdb status seen in prometheus ui are only the active data in the last few hours, not all the data summary.

Is there any way to see the total number of series and samples in the entire prometheus tsdb, as well as the write rate of samples？

**Comment by luzejia** [comment]
> Without having tried it:
> 
> Number of samples: `count_over_time({__name__=".+"}[my_retention_period])` Number of series: `count(max_over_time({__name__=".+"}[my_retention_period]))`
> 
> (replace `my_retention_period` with `14d` or however your Prometheus is configured).
> 
> May be resource-intensive to execute these queries.
> 
> Write rate is simpler: `rate(prometheus_tsdb_head_samples_appended_total[1m])`

Thank you for your answer, I have tried to count {__name__=".+"}, but in the case of a large amount of data, the execution will hang and consume a lot of resources.

**Comment by alexgreenbank** [comment]
Hello from the bug scrub. Apologies for the delay in replying.

Individual blocks can be analysed with a command line tool such as `promtool tsdb list`. The stats here can be aggregated to provide a total number of samples.

A total number of unqiue series requires deduplicating series names across blocks which, as you have pointed out, is expensive and consumes a lot of resources.

Closing as there are no plans to implement this kind of functionality and out-of-band solutions (command line tools) exist.
