### ISSUE TITLE
A way to force flush Prometheus data to TSDB block manually

### ISSUE THREAD

**Issue by abhijitchaudhari1** [prometheus/prometheus#12261]
### Proposal

We are planning to use Promethus with local PV and thanos with objectstore to persistent the monitoring data. This setup creates TSDB block every 2 hours and it gets uploaded to objectstore via thanos sidecar. 

When we do a node rotation, i.e prometheus pod moves from one node to other , it uses a empty volume running on the new node,  we loose some data. This data was not flushed to TSDB block and hence thanos sidecar did not upload it. 

I want to understand if it is possible to force flush the Prometheus data to TSDB block , such that the recent data is persisted to objecstore  before moving the pod from one node to other node.

**Comment by bboreham** [comment]
There is no API for this at the moment.
