### ISSUE TITLE
ExternalLabels can be support overwrite targets'labels when remote_write?

### ISSUE THREAD

**Issue by AugensternMin** [prometheus/prometheus#12265]
### What did you do?

I am using Thanos for remote_write of prometheus, each prometheus data provides a `cluster` label for differentiation,
so I set `external_labels` in each prometheus config like follows:
```
global:
   external_labels:
       cluster: clusterA   
```

### What did you expect to see?

In Thanos, the `cluster` label for each prometheus data is as configured from the external_labels.

### What did you see instead? Under which circumstances?

But when the target metrics also has a custom `cluster` label, It's going to override my external_labels.

Is there a configuration item like `honorLabels`, to specify the priority of `external_labels`?

I found the relevant code in [processExternalLabels](https://github.com/prometheus/prometheus/blob/7309ac272195cb856b879306d6a27af7641d3346/storage/remote/queue_manager.go#L894)

It's comments: `processExternalLabels merges externalLabels into ls. If ls contains a label in externalLabels, the value in ls wins.`

### Prometheus version

```text
version v2.33.5
```

### Prometheus configuration file

```yaml
global:
   external_labels:
       cluster: clusterA   
```
```


### Alertmanager version

_No response_

### Alertmanager configuration file

_No response_

### Logs

_No response_

**Comment by bboreham** [comment]
I don't think you can configure this.
You could add a `metric_relabel_configs` to rename `cluster` when the data is scraped, then a `write_relabel_configs` to rename it back to `cluster`. 

I looked back at the history; apparently it worked this way for the last 6 years.  
https://github.com/prometheus/prometheus/blame/8e3a39f7259fc306e790be546444c031e7e0c531/storage/remote/queue_manager.go#L209-L213

**Comment by alexgreenbank** [comment]
Hello from the bug scrub.

Closing issue as this is the expected behaviour and a workaround provided.
