### ISSUE TITLE
alert condition using: time() not fired

### ISSUE THREAD

**Issue by lethe3000** [prometheus/prometheus#1228]
Hi, I want to alert if a container which is disappear more than 5s，but I cannot make condition `time() - container_last_seen > 5` fired.
```
ALERT ContainerDown
  IF time() - container_last_seen{name="nginx"} > 5
  FOR 1s
  SUMMARY "container{{$lables.name}} is down on {{$labels.instance}}"
  DESCRIPTION "container{{$labels.name}} down on {{$labels.instance}}"
  RUNBOOK ""
```

I stopped nginx container, and I executed below query,  found that the value is greater than 5.
```
time() - container_last_seen{name="nginx"}
```
So I wonder that cannot use time() in alert conditions?

**Comment by matthiasr** [comment]
No, this should work fine. However, your label values differ – `=` wants an exact match, and I presume there is no container called "nginx" and thus there is nothing to return.

**Comment by lethe3000** [comment]
thanks I think I shoud use `=~` to match container name.
