### ISSUE TITLE
add unit tests for quantile.go

### ISSUE THREAD

**Issue by khareyash05** [prometheus/prometheus#12291]
### Proposal

I would like to add unit tests for `promql/quantile.go` to check if all the functions are working correctly or not

**Comment by machine424** [comment]
Some tests were added via https://github.com/prometheus/prometheus/pull/13153
If you think other cases should be covered as well, please, don't hesitate.

**Comment by beorn7** [comment]
Also note that the tests via the PromQL testing framework in https://github.com/prometheus/prometheus/blob/main/promql/testdata/histograms.test and https://github.com/prometheus/prometheus/blob/main/promql/testdata/native_histograms.test exercise the code in promql/quantile.go a lot. I think the test coverage is pretty good overall.

I'll close this, but if you spot any gaps, please follow up and I'll re-open.
