### ISSUE TITLE
nomad_sd_config: server expects url not host

### ISSUE THREAD

**Issue by michael-strigo** [prometheus/prometheus#12306]
### What did you do?

Following the latest documentation for [nomad_sd_config](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#nomad_sd_config) I've configured my prometheus to scrape nomad like this:

```yaml
nomad_sd_configs:
  - server: 172.30.29.23:4646
```

### What did you expect to see?

I expected this to work as per documentation where the server key expects a `<host>` to be:

> a valid string consisting of a hostname or IP followed by an optional port number

### What did you see instead? Under which circumstances?

the following error:

```
level=error component="discovery manager scrape" msg="Cannot create service discovery" err="invalid address '172.30.29.23:4646': parse \"172.30.29.23:4646\": first path segment in URL cannot contain colon" type=nomad config=pushgateway
```

I don't know if this is a documentation bug (change <host> to <string>) or the actual API needs a bit of tweaking.
Although `server: http://1.2.3.4:4646` is a bit weird... would be nicer if it was an `address` or something more descriptive.

### Prometheus version

```text
Starting Prometheus Server mode=server version="(version=2.43.0, branch=HEAD, revision=edfc3bcd025dd6fe296c167a14a216cab1e552ee)
```

**Comment by beorn7** [comment]
Hello from the bug scrub!

Unfortunately, the Nomad SD is mostly unmaintained. Any help here is very welcome. Nevertheless, @machine424 promised to have a look here if it is easy to resolve even without detailed Nomad SD knowledge.

**Comment by machine424** [comment]
Thanks for reporting this, I opened https://github.com/prometheus/prometheus/pull/15532 to address the doc.

`server` should be a valid URL.

And the nomad client is making sure of that here https://github.com/hashicorp/nomad/blob/4563165196d48c4c1f8cf54882de68d68bcd30fe/api/api.go#L502-L518

`172.30.29.23:4646`not being a valid (relative) URL.
