### ISSUE TITLE
The console (auto-)reload (button) doesn't reload sidebar metrics

### ISSUE THREAD

**Issue by Baughn** [prometheus/prometheus#1230]
For example, as in https://status.brage.info/consoles/minecraft.html

You have to fully reload the page to update (e.g.) the load percentage.

**Comment by brian-brazil** [comment]
The graph control only covers the graph, we might be able to do something with JS but it's not going to cover all cases. Have you considered Grafana?

**Comment by Baughn** [comment]
Considered, yet. I haven't tried it yet; it's next on the list. I got a lot of use from Promdash, earlier, but right now I'm doing something slightly weird and wanted to inject arbitrary HTML.

**Comment by gklepach** [comment]
Hi, did you fix this problem?
Data in "prom_right_table_head", is not auto update?

**Comment by brian-brazil** [comment]
The example console templates are intended to be simple. I'd suggest using Grafana or adding your own Javascript if you're like to do something more sophisticated.
