### ISSUE TITLE
Allow disabling HTTP response compression for scrape requests

### ISSUE THREAD

**Issue by prymitive** [prometheus/prometheus#12319]
### Proposal

Currently Prometheus will always request **gzip** compression from the target when sending scrape requests: https://github.com/prometheus/prometheus/blob/main/scrape/scrape.go#L788.

HTTP compression does reduce the amount of bytes sent over the wire and so is often desirable. 
The downside of compression is that it requires extra resources - cpu & memory.

In my tests forcing Prometheus to disable HTTP compression resulted in 3GB memory savings thanks to shaving off 2GB from memory allocated by `compress/flate` & not storing response body twice in memory (once compressed and once uncompressed).
Most our scrape jobs use local network, so we don't **need** compression and we would happily trade some extra network bandwidth in exchange for extra memory.
We would still want to use compression for scrapes that run over the internet, like federation requests. So ideally this should be configurable per scrape job.

I would like to add ability to configure what Prometheus puts in `Accept-Encoding` request header per scrape job. Which means:

- Adding extra configuration options for each `scrape_job` entry in the config file.
- It would also be great if there was a `global` section option to set the default behaviour, so  that one could set default behaviour without the need to add a field to every single scrape job config block.

Looking at the code there are a few ways to achieve this:

1) Add a field to `ScrapeConfig` [struct](https://github.com/prometheus/prometheus/blob/main/config/config.go#L457) specifically for compression.
2) Add a new field to `HTTPClientConfig` [struct](https://github.com/prometheus/common/blob/main/config/http_config.go#L287) specifically for compression
3) Add a new field to `HTTPClientConfig` [struct](https://github.com/prometheus/common/blob/main/config/http_config.go#L287) for setting arbitrary headers.

I'm not convinced that setting arbitrary headers is the best thing to do here. For starters it's the least obvious and most indirect way of doing this. Secondly it would allow people to request any encoding, not just "gzip" or "off", while Prometheus scrape code only supports gzip. This could lead to confusion.

I'm not 100% sure that `HTTPClientConfig` is the right place to have this knob. Given that it's mostly used for passing values that are set on Go HTTP transport. But it is more or less client side configuration, so perhaps it would be a good fit there.

On the other hand compression handling is very explicit in Prometheus code, so perhaps it would be the best to add a new knob directly on `ScrapeConfig` and tie it more closely inside Prometheus code, and so maybe that's the right approach here.

Happy to make the PR, it's just that I'm not sure what's the preferred way of passing this setting down to scrape code.

**Comment by wjordan** [comment]
Note that VictoriaMetrics [`vmagent`](https://docs.victoriametrics.com/vmagent.html) has implemented a custom `scrape_configs` option `disable_compression` (as well as a global `-promscrape.disableCompression` command-line flag) for this purpose.

**Comment by dswarbrick** [comment]
Has anybody considered exploring more efficient compression algorithms, such as Zstd ([RFC 8878](https://www.rfc-editor.org/rfc/rfc8878.html))? Zstd is significantly faster than zlib (which should translate to less CPU time for a given amount of data), whilst offering about the same compression ratio.

**Comment by prymitive** [comment]
Raised #13166 for this
