### ISSUE TITLE
tsdb.Open() should take an io/fs instead of a dir string

### ISSUE THREAD

**Issue by jzelinskie** [prometheus/prometheus#12321]
### Proposal

By adopting the io/fs abstraction, it'd be possible for other programs or tests to use in-memory filesystems for tsdb without creating a tempdir/tempfs.

EDIT: I realized this might not be the only thing since the tsdb works using mmap, right?

**Comment by roidelapluie** [comment]
Yes mmap is going to be an issue.

**Comment by roidelapluie** [comment]
But the storage itself is an interface. You could swap the TSDB by another package when using PromQL: https://github.com/prometheus/prometheus/blob/main/storage/interface.go

**Comment by beorn7** [comment]
Hello from the bug scrub!

As per the explanations above, we are closing this.
