### ISSUE TITLE
no docker image tagged for v2.44.0-rc.1

### ISSUE THREAD

**Issue by christian-heusel** [prometheus/prometheus#12335]
### What did you do?

I wanted to test the new rc release v2.44.0-rc.1 with my ususal setup in docker and didnt find a tag for v2.44.0-rc.1.

### What did you expect to see?

There is a tag for v2.44.0-rc.1 as there is for [v2.44.0-rc.0](https://hub.docker.com/layers/prom/prometheus/v2.44.0-rc.0/images/sha256-ee22e3e4fbc98f6d3ae420d6f23de327e8b4a06ce91534a03b9717e73578eb78?context=explore)

### What did you see instead? Under which circumstances?

```
$ docker compose up
[+] Running 1/1
 ✘ prometheus Error                                                                                                                                                                                          1.8s
Error response from daemon: manifest for prom/prometheus:v2.44.0-rc.1 not found: manifest unknown: manifest unknown
```

### System information

Linux scotty-the-fifth 6.1.27-1-lts #1 SMP PREEMPT_DYNAMIC Mon, 01 May 2023 18:18:27 +0000 x86_64 GNU/Linux

**Comment by roidelapluie** [comment]
I have relaunched the job.

**Comment by kaffarell** [comment]
Exists now (https://hub.docker.com/layers/prom/prometheus/v2.44.0-rc.1/images/sha256-ce2a8095b9a0536ac4d4382500ee9b29ca55ea40a9c017475eb66a825be17450?context=explore) we can close the issue.
