### ISSUE TITLE
Consider length limit for label values on ingestion

### ISSUE THREAD

**Issue by brian-brazil** [prometheus/prometheus#1235]
We could end up with such a long labelvalue that it causes performance issues (e.g. if a metric was split out by a user-provided customer name). It might be an idea to have a limit on how long a label value can be, defaulting to something like 1KiB.

**Comment by beorn7** [comment]
I'm against an arbitrary limit. While label values could become too long accidentally, I'm sure somebody will be able to come up with a legitimate use-case for _any_ label value length eventually.

Obviously, we are “vulnerable” to abusive clients, but we are that anyway. E.g. it's very easy to create millions of time series in a very short time and bring down the server. The responsibility of not overloading the server lies with the client.

**Comment by juliusv** [comment]
I think I'm with @beorn7 on this one. Should we close it?
