### ISSUE TITLE
Cannot create Kubernetes discovery: open : no such file or directory

### ISSUE THREAD

**Issue by calvinmorrow** [prometheus/prometheus#1236]
Prometheus 0.16.1, tested with linux-amd64 release as well as docker image:

Receiving the following error on startup:  ERRO[0000] Cannot create Kubernetes discovery: open : no such file or directory  source=targetmanager.go:424

I've tried multiple variations of configuration with no success.  Strangely, changing the master address doesn't seem to affect the error at all.  It doesn't seem like any tcp communication is happening;  My perception is that the error is occurring due to absence of some configuration item and not from any actual Kubernetes API communication.

```
bash-4.2# ./prometheus -log.level debug -config.file=/etc/prometheus/prometheus.yml
prometheus, version 0.16.1 (branch: release-0.16.1, revision: 968ee35)
  build user:       fabianreinartz@macpro
  build date:       20151016-13:19:57
  go version:       1.5
INFO[0000] Loading configuration file /etc/prometheus/prometheus.yml  source=main.go:196
ERRO[0000] Cannot create Kubernetes discovery: open : no such file or directory  source=targetmanager.go:424
INFO[0000] Loading series map and head chunks...         source=storage.go:262
INFO[0000] 0 series loaded.                              source=storage.go:267
INFO[0000] Starting target manager...                    source=targetmanager.go:114
INFO[0000] Listening on :9090                            source=web.go:223
```

prometheus.yml:
```
global:
  scrape_interval:     60s # By default, scrape targets every 15 seconds.
  evaluation_interval: 60s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

scrape_configs:
- job_name: kubernetes

  bearer_token: <snip>

  kubernetes_sd_configs:
  - masters:
    - 'https://kubernetes.mydomain.com:6443'
```

**Comment by jimmidyson** [comment]
So we need to improve that error message...

Think I've spotted the error (logic in https://github.com/prometheus/prometheus/blob/master/retrieval/discovery/kubernetes/discovery.go#L615-L618) - will fix tomorrow if noone else gets there first.
