### ISSUE TITLE
Expression graphs: Allow time selection with mouse drag

### ISSUE THREAD

**Issue by RichiH** [prometheus/prometheus#1237]
When displaying an expression's result as a graph, I would like to be able to drag select a time slice to zoom in on. This would allow quicker drill-down into interesting events.

**Comment by roidelapluie** [comment]
I also think that double clicking on the graph could zoom out.

**Comment by roidelapluie** [comment]
In the react UI the moise pointer is clearly visible so it makes you think that you can zoom, but you can't currently :)

**Comment by beorn7** [comment]
Just to be clear: This should only be added to the new React UI.

**Comment by LeviHarrison** [comment]
I'm working on this
