### ISSUE TITLE
Getting wrong metrics from a simple name query

### ISSUE THREAD

**Issue by zuzzas** [prometheus/prometheus#12394]
### What did you do?

I've queried a metrics by name.

### What did you expect to see?

Only metrics matching the name.

### What did you see instead? Under which circumstances?

Wrong metrics are returned for a given name. With an entirely different name. I've never seen such a thing before version 2.44.0.

![image](https://github.com/prometheus/prometheus/assets/950313/bd45a94e-f56a-4d44-a4e0-0ad0f6a80818)

### Prometheus version

```text
prometheus, version 2.44.0 (branch: HEAD, revision: 1ac5131f698ebc60f13fe2727f89b115a41f6558)
  build user:       root@781b98cea375
  build date:       20230518-11:37:52
  go version:       go1.19.3
  platform:         linux/amd64
  tags:             netgo,builtinassets,stringlabels
```

**Comment by npordash** [comment]
I've seen this behavior a few times due to this scenario: https://github.com/prometheus/prometheus/pull/9381#issuecomment-1517116467

**Comment by codesome** [comment]
@zuzzas did you see `Overlapping m-map chunks on duplicate series records` when Prometheus restarted (the restart right before this query error)?

**Comment by zuzzas** [comment]
I am not certain, the logs are already rotated, unfortunately. And I have not been able to reproduce this issue ever since.
