### ISSUE TITLE
Automated Preview Environments at Pull Request

### ISSUE THREAD

**Issue by dakar91** [prometheus/prometheus#12392]
### Proposal

Bunnyshell is providing free Kubernetes infrastructure for previews at PRs to open source projects.

Would you be interested in having preview environments on future pull requests?

Our team @bunnyshell and @bunnyshellosi are ready to help implement the initial pipeline to get you started!

Example workflow - https://github.com/aris-bunnyshell/demo-books-php/tree/main/.github/workflows
Example configuration - https://github.com/aris-bunnyshell/demo-books-php/blob/main/.bunnyshell/templates/docker-compose/bunnyshell.yaml

We really think some of the issues and PRs can benefit from preview environments, like the 46 open issues which are UI related: https://github.com/prometheus/prometheus/labels/component%2Fui

**Comment by dakar91** [comment]
Hey @Nexucis & @juliusv I noticed you've been working with Gitpod in the Prometheus repo, maybe you can have a look at this initiative? Thank you.

**Comment by beorn7** [comment]
Hello from the bug scrub!

Since @Nexucis and @juliusv , as the domain experts, haven't responded in the last 1½ years, we are closing this. (However,  @Nexucis and @juliusv, you are of course still welcome to follow up here with your thoughts.)
