### ISSUE TITLE
Send alert notifications even if limit is reached

### ISSUE THREAD

**Issue by sdufel** [prometheus/prometheus#12415]
### Proposal

The per-rule limit is great for protecting an alertmanager deployment from an excessive amount of alert instances.  Unfortunately, it also prevents any active alerts from notifying once it is reached.  This is not ideal, as we would prefer to be notified when our alerts start firing.

Proposed solution:
- Add a new optional field to the rule group struct controlling the limit behavior
- The default would continue with the current behavior
- With the new field configured, firing and pending alert instances would be persisted up to the limit.
- Notifications would be sent for all firing alerts as normal

From a user's perspective - in most cases, if an alert rule exceeds a certain number of instances, it's an example of a systemic problem.  The exact list of alert instances is not that important.  In cases where something catastrophic is happening, or if it's a matter of an alert rule that was misconfigured, I would want both a stable alerting system and a notification.  The current limit feature only provides one of those.

**Comment by sdufel** [comment]
If this sounds reasonable, I don't mind contributing an PR for this.

**Comment by roidelapluie** [comment]
Which alertmanager receiver are you using?

The webhook receiver has a `[ max_alerts: <int> | default = 0 ]` setting too so you can deal with the bottleneck here.

in general in Prometheus we tend to drop complete things at once, but you should have an alert in place to detect when that's happening.

**Comment by sdufel** [comment]
We're using a combination of webhook, slack, and pagerduty. 

I'm hoping to limit alert volume before they actually reach the alertmanager, though.  If someone creates a poorly-crafted alert, it can create 50-100k alert instances, which degrades the system for everyone else.

**Comment by qinxx108** [comment]
For my opinion it is a better user experience to truncate the alerts rather than drop the whole thing when the limit got hit.  Image when i hit the limit on number of alerts can generate per rule, i would like to see the alerts in my destination to troubleshoot(for example i have cardinality issue on a label can generate too many alerts)

**Comment by machine424** [comment]
Adding another limiting parameter would also add more complication and confusion (https://github.com/prometheus/prometheus/issues/12646 is suggesting different limits for alerts and recording rules...).
How about grouping the alerts/rules per group? Separate the poorly-crafted alerts from the battle-tested ones?

**Comment by beorn7** [comment]
Hello from the bug scrub!

As no further discussion happened in over a year, we would like to close this. You can set limits per group, which should get you a long way, see @machine424's comment above.
