### ISSUE TITLE
/api/v1/query_range & /api/v1/query interface does not support addition syntax

### ISSUE THREAD

**Issue by bugmenoway** [prometheus/prometheus#12448]
### What did you do?

I try to calculate the sum of multiple indicators, such as up+up, and I get an error prompt 
'invalid parameter \"query\": 1:6: parse error: unexpected identifier \"up\"'.

I tried using "up - - up" instead of "up+up",it worked.

### What did you expect to see?

I hope the addition syntax of the query interface can also be used normally.
In fact, I can perform addition normally in the graph section of Prometheus' web page,but the query interface cannot.

### What did you see instead? Under which circumstances?

GET http://host:9090/api/v1/query?query=up+up
and I get an error prompt 
'invalid parameter \"query\": 1:6: parse error: unexpected identifier \"up\"'.

### System information

Linux 4.19.90-23.15.v2101.ky10.x86_64 x86_64

### Prometheus version

```text
version 2.43.0
go version: go1.19.7
tags: netgo,bulitinasssets
```

**Comment by sdufel** [comment]
The `+` character needs to be encoded when used in a query string - otherwise, it will be interpreted as a space character.

Try `/api/v1/query?up%2Bup`

**Comment by bugmenoway** [comment]
> 在查询字符串中使用时，需要对字符进行编码 - 否则，它将被解释为空格字符。`+`
> 
> 尝试`/api/v1/query?up%2Bup`

it worked! thank thank  thank.
