### ISSUE TITLE
Feature Request: UI option to specify time for evaluation

### ISSUE THREAD

**Issue by bluecmd** [prometheus/prometheus#1246]
When I want to look at past data in Prometheus I usually use PromDash's "Until" UI option. That said, I prefer using Prometheus for experimentation. I usually end up just doing "X offset 1w", but when I want to look at a certain date that's quite painful as this is not static, while the time window I want to examine is.

The API already has a time= option, so this should just be a UI feature unless I'm missing something.

It would be nice if both relative and absolute times were supported ("2015-06-01 11:00:00" and "2 days ago").

**Comment by grobie** [comment]
:+1: This would help a lot, as range queries can be very expensive for certain data sets.

**Comment by yamatoya** [comment]
I want to work.
I am thinking of two solutions. Which is better? or is there a more better solution ?

1. change ui from `until` field to `from` field.
![image](https://user-images.githubusercontent.com/2118539/31319691-f488cb60-aca2-11e7-8591-1341e0cb39e3.png)
2. change ui like grafana
![image](https://user-images.githubusercontent.com/2118539/31319627-fe5a372e-aca1-11e7-93da-1863a17baac9.png)

**Comment by grobie** [comment]
Cool, thank you!

We should keep the option to specify a relative time range, as that's easier when you want to take a quick look. I find Grafana a bit too much and I don't find the order of the quick ranges intuitive. Hiding some of the options in a drop down like grafana does it could be helpful. I guess we should separate the "stacked" button from the time options, at least with a vertical break line or some space. I don't have a good suggestion on the design besides that.

Regarding my older comment, I think I misunderstood the request back then to add a time option to the console view as well. Would be great though.

**Comment by SuperQ** [comment]
Similar, it would be nice to have a time picker in the "Console" view.

<img width="600" alt="time-picker" src="https://user-images.githubusercontent.com/1320667/42880125-76ec150c-8a93-11e8-94ea-b0db51b0fe0b.png">

**Comment by kdada** [comment]
Anything updated?

I think a time picker for console is useful. It is not only for querying in ui, but also support alerting callback.

If we received an alert from prometheus/alertmanager, we click `generatorURL` to redirect to prometheus ui. But sometimes we find nothing in `Console` because the alert has been resolved.

So if prometheus ui supports `g0.time=xxxx` and a time picker, it will be more friendly to users.

**Comment by grobie** [comment]
@kdada We all agree. Feel free to open a pull request :-)

**Comment by kdada** [comment]
@grobie I'm working on it.

**Comment by vn-ki** [comment]
I think this can be closed as #4764 is merged.
