### ISSUE TITLE
Support `etcd_sd_configs` in `scrape_configs`?

### ISSUE THREAD

**Issue by jmjoy** [prometheus/prometheus#12461]
### Proposal

Because `etcd` is also a relatively general foundation for service discovery.

**Comment by roidelapluie** [comment]
Do you have a link to what you mean? I have never seen etcd used for this.

**Comment by jmjoy** [comment]
> Do you have a link to what you mean? I have never seen etcd used for this.

There is a blog about using `etcd` as service discovery via `file_sd_configs`: <https://prometheus.io/blog/2015/08/17/service-discovery-with-etcd/>

Prometheus supports many `*_sd_configs`, but not `etcd_sd_configs`.
https://prometheus.io/docs/prometheus/latest/configuration/configuration/#scrape_config

**Comment by beorn7** [comment]
Hello from the bug scrub!

Generally, we have a problem with maintaining the many SDs already. A new SD needed to come with committed maintainers to not add to the pile of essentially unmaintained SDs.

As this has been sitting without much attention for 1.5y, and you can already use the file-based SD, we'll close this.
If anyone feels the need for a native etcd SD _and_ has the resources to maintain it, please follow up.
