### ISSUE TITLE
Make Help Link in UI customizable

### ISSUE THREAD

**Issue by mrueg** [prometheus/prometheus#12473]
### Proposal

Currently the help link in the navbar `./web/ui/react-app/src/Navbar.tsx`  points to https://prometheus.io/docs/prometheus/latest/getting_started/

It would be nice to make it configurable, so we can point it to a specific version, an internal documentation or another page.

My current idea is adding a new endpoint to prometheus' API `/help`  which by default redirects to ` https://prometheus.io/docs/prometheus/latest/getting_started/` and can be customized by the operator.

Ideally it would nice to have it embedded / "iframed", so users don't loose context (so the navbar is still visible).

**Comment by roidelapluie** [comment]
Iframes are something from the past. I think we could have the link customizable with a cli flag, like we have for the title

**Comment by beorn7** [comment]
Hello from the bug scrub!

This idea hasn't got much attention over the last 1.5y. We currently don't think the help link should be customizable. We'll close this, but whoever has strong opinions that it should, please follow up here with your line of argument, and we will reconsider.
