### ISSUE TITLE
Tooltip shows null y value when multiple series are stacked

### ISSUE THREAD

**Issue by kokes** [prometheus/prometheus#12474]
### What did you do?

I have multiple series and I stack them. To reproduce the issue, I wrote this churning exporter that I run alongside my Prometheus build:

```go
package main

import (
	"fmt"
	"log"
	"math/rand"
	"net/http"
	"time"
)

func main() {
	log.Printf("exposing metrics on localhost:1234/metrics")
	http.HandleFunc("/metrics", func(w http.ResponseWriter, r *http.Request) {
		label := time.Now().Unix() / 15
		value := rand.Intn(10)
		fmt.Fprintf(w, "my_custom_metric{label=\"%v\"} %v\n", label, value)
	})
	http.ListenAndServe("localhost:1234", nil)
}
```

It ensures a new label for a given series every 15 seconds.

### What did you expect to see?

I was expecting to see the actual value in the tooltip when I hover over the series.

### What did you see instead? Under which circumstances?

The "older" series is shown properly as a chart, but the tooltip shows `null`.

I tried bisecting the hell out of this, but I don't quite understand flot and the various helpers that come into play. I was able to find a case where it's not an issue anymore - by exiting in all cases [in flot.stack](https://github.com/prometheus/prometheus/blob/86a7064dcfc0828a10520888a188c46731986b3c/web/ui/react-app/src/vendor/flot/jquery.flot.stack.js#L75). This obviously disables its functionality, so it was just a test to see where the problem arises.

I was under the impression this was a known issue and it was fixed in https://github.com/prometheus/prometheus/commit/e12e5ecc8fe18c643860ca5a45feaa38cab6f8f1, but apparently not. I see it in both the main branch as well as 2.43/2.44

```
// TODO: Flot has problems displaying intermittent "null" values when stacked,
// resort to 0 now. In Grafana this works for some reason, figure out how they
// do it.
```

I also looked at the upstream flot code, but there seem to be no recent updates https://github.com/grafana/grafana/tree/main/public/vendor/flot

![Screenshot 2023-06-20 at 10 14 26](https://github.com/prometheus/prometheus/assets/8451755/4d2b9695-5df0-4bce-8b60-e4e09d61fc08)

### System information

Darwin 22.5.0 x86_64

### Prometheus version

```text
$ ./prometheus --version
prometheus, version 2.45.0-rc.0 (branch: main, revision: 86a7064dcfc0828a10520888a188c46731986b3c)
  build user:       okokes@prg-mp84w
  build date:       20230620-09:24:28
  go version:       go1.20.4
  platform:         darwin/amd64
  tags:             unknown
```
```


### Prometheus configuration file

```yaml
global:
  scrape_interval: 3s

scrape_configs:
  - job_name: "prometheus"

    static_configs:
      - targets: ["localhost:9090", "localhost:1234"]
```
```


### Alertmanager version

_No response_

### Alertmanager configuration file

_No response_

### Logs

_No response_

**Comment by rgroothuijsen** [comment]
Tried this myself with the above code, and interestingly stacked mode also causes all data points to have the same timestamp label when hovered over. The labels were properly represented when switching back to unstacked mode.

**Comment by beorn7** [comment]
Hello from the bug scrub!

We have a completely new UI by now. If this problem still persists in the new UI, please file a new issue.

**Comment by kokes** [comment]
Tested this in the new UI and the issue is not reproduced there.
