### ISSUE TITLE
Add ``zscore_over_time`` function

### ISSUE THREAD

**Issue by tuguri8** [prometheus/prometheus#12496]
### Proposal

Many developers use ``stddev_over_time`` and ``avg_over_time`` to implement z-score.
This function  can help detecting anomalies over time series.

**Comment by beorn7** [comment]
More discussion in the PR #12497 .

**Comment by beorn7** [comment]
As per further the discussion on #12497 (triggered by overarching discussions at the dev summit), I'll close this for now.

(tl;dr: It is relatively easy to calculate a z-score over time with the existing PromQL primitives.)
