### ISSUE TITLE
promtool tsdb create-blocks-from openmetrics uses a lot of disk, but the generated blocks are small.

### ISSUE THREAD

**Issue by Wtango** [prometheus/prometheus#12490]
### What did you do?

I prepare an openmetric format file(321MB) with 122512 series and 1470144 samples, 1 sample every hour for a series, and then I use below command to generate the blocks:
```
# promtool tsdb create-blocks-from --max-block-duration=240h openmetrics metrics.txt data
```

I repeat above operation to generate the the block into 10 different folders data, data1,... data9, every data folder takes 29MB disk:
```
# du -sh data*
29M     data
29M     data1
29M     data2
29M     data3
29M     data4
29M     data5
29M     data6
29M     data7
29M     data8
29M     data9
```

After checking the output from `df -h`, I saw **5GB** available disk reduction after genearting 10 folders, but the total size of these 10 folders is only 290MB. Even I reboot my host, the disk hadn't been free up, only after I removing all of the data folders, **5GB** disk comes back.

Below is the blocks info for the `data/` folder:
```
BLOCK ULID                  MIN TIME       MAX TIME       DURATION     NUM SAMPLES  NUM CHUNKS   NUM SERIES   SIZE
01H3RRHEHYP5Q0Y8FR5PSFJFJZ  1687172637147  1687194237148  6h0m0.001s   857584       122512       122512       14883923
01H3RRHJZN24HBJ1AZCK8JR1K3  1687197837147  1687212237148  4h0m0.001s   612560       122512       122512       14761059
```

Below is the files info for the generated `data/` folder:
```
data # ls -la
total 16
drwxr-x--- 1 root    root     104 Jun 25 00:50 .
drwxr-x--- 1 miepusr miepgrp 1250 Jun 25 01:20 ..
drwxr-x--- 1 root    root      60 Jun 25 00:53 01H3RRHEHYP5Q0Y8FR5PSFJFJZ
drwxr-x--- 1 root    root      60 Jun 25 00:50 01H3RRHJZN24HBJ1AZCK8JR1K3

data # du -sh *
15M     01H3RRHEHYP5Q0Y8FR5PSFJFJZ
15M     01H3RRHJZN24HBJ1AZCK8JR1K3

data/01H3RRHEHYP5Q0Y8FR5PSFJFJZ # ls -la
total 11208
drwxr-x--- 1 root root       60 Jun 25 00:53 .
drwxr-x--- 1 root root      104 Jun 25 00:50 ..
drwxr-x--- 1 root root       12 Jun 25 00:50 chunks
-rw-r----- 1 root root 11453289 Jun 25 00:50 index
-rw-r----- 1 root root      281 Jun 25 00:50 meta.json
-rw-r----- 1 root root        9 Jun 25 00:50 tombstones

data/01H3RRHEHYP5Q0Y8FR5PSFJFJZ # du -sh *
3.3M    chunks
11M     index
4.0K    meta.json
4.0K    tombstones

# cd chunks/

chunks # ls -la
total 3360
drwxr-x--- 1 root root      12 Jun 25 00:50 .
drwxr-x--- 1 root root      60 Jun 25 00:53 ..
-rw-r----- 1 root root 3430344 Jun 25 00:50 000001

chunks # du -sh *
3.3M    000001
```

### What did you expect to see?

The disk reduction should be around 290MB from the output of `df -h`

### What did you see instead? Under which circumstances?

The disk reduction is **5GB** after generating 10 folders, these folders have 290MB disk usage in total.

### System information

Linux 5.14.21-150400.24.63-default x86_64

### Prometheus version

```text
prometheus, version 2.31.1 (branch: HEAD, revision: 411021ada9ab41095923b8d2df9365b632fd40c3)
  build user:       root@9419c9c2d4e0
  build date:       20211105-20:35:02
  go version:       go1.17.3
  platform:         linux/amd64
```

**Comment by machine424** [comment]
@Wtango 

(you talked about running `df -h`, `df` returns "free" space.)
There is no magic solution, you will need to run `du -h -d 1` on the directory that "consumes 5GB" to track down these greedy files (if they exist).
As long as you haven't identified them, I don't see how we can help (ah, maybe you're cloning the repo 10 times, I know that it becomes heavy after the UI build)

**Comment by Wtango** [comment]
cannot find the reason, close it.
