### ISSUE TITLE
add tests to web UI

### ISSUE THREAD

**Issue by discordianfish** [prometheus/prometheus#125]
Let's figure out what we can use.

ie.:
- https://github.com/soundcloud/tyrtle
- http://docs.seleniumhq.org/

**Comment by mattbostock** [comment]
I'd recommend Agouti, a webdriver client for Go:
http://agouti.org/#using-agouti-by-itself

Here are some examples tests I've written using Agouti:
https://github.com/mattbostock/leavediary/blob/a8eaf858c2b941773a471e7fc76b2f43aaa9e26c/acceptance_test.go#L74

**Comment by grobie** [comment]
Actually, I think we should separate the UI from the server (depends on #2467) and do the testing solely in javascript. There are proposals to rewrite the UI in Elm following the current alertmanager rewrite.

**Comment by mattbostock** [comment]
@grobie: Can you expand on what you mean by separating the UI from the server? Do you mean the UI will be entirely rendered using javascript, which connects to the API backend?

I think I mistook the intent of this issue to be 'acceptance tests', i.e. blackbox verification of common user journeys. Completely agree on testing the javascript side in isolation. Perhaps those might be covered as part of the work on integration testing: #1106

**Comment by grobie** [comment]
On Mon, Apr 17, 2017, 16:50 Matt Bostock <notifications@github.com> wrote:

> @grobie <https://github.com/grobie>: Can you expand on what you mean by
> separating the UI from the server? Do you mean the UI will be entirely
> rendered using javascript, which connects to the API backend?
>

Yes, I think this makes most sense.

**Comment by discordianfish** [comment]
Agreed, and I've actually gained some experience recently with this. So if someone needs help setting up the frontend tests, let me know.

**Comment by simonpasquier** [comment]
This has been auto-closed erroneously.

**Comment by gouthamve** [comment]
The new React UI has tests
