### ISSUE TITLE
Dynamic Alert Rules

### ISSUE THREAD

**Issue by changwuf31** [prometheus/prometheus#1251]
So we can allow something like
```
IF node_load1 > 2 * count(node_cpu{mode="idle"}) by (instance) FOR 5m
```

**Comment by brian-brazil** [comment]
That's a valid rule, though load average isn't a particularly useful metric for alerting these days. We'd generally encourage alerting on something that directly affects users such as latency or error rates.

**Comment by changwuf31** [comment]
It runs without failure, yes.. but it does not return the expected result.
And yes, we'd love to use latency and error rates as alert trigger, still trying to figure how best to implement that.

**Comment by brian-brazil** [comment]
Try:

`node_load1 > on (instance) 2 * count by (instance)(node_cpu{mode="idle"})`

**Comment by changwuf31** [comment]
@brian-brazil It works, thank you :+1:
