### ISSUE TITLE
file_sd_config must be file_sd_configs

### ISSUE THREAD

**Issue by cronolio** [prometheus/prometheus#12523]
### What did you do?

https://prometheus.io/docs/prometheus/latest/configuration/configuration/#file_sd_config
`file_sd_config` must be `file_sd_configs`

in docker image v2.45.0 (latest for now) it is file_sd_configs

### What did you expect to see?

please update documentation

### What did you see instead? Under which circumstances?

caller=main.go:482 level=error msg="Error loading config (--config.file=/etc/prometheus/prometheus.yml)" file=/etc/prometheus/prometheus.yml err="parsing YAML file /etc/prometheus/prometheus.yml: yaml: unmarshal errors:\n  line 15: field file_sd_config not found in type config.ScrapeConfig"

**Comment by FOWind** [comment]
I think there is no matter with the doc

refer to https://prometheus.io/docs/prometheus/latest/configuration/configuration/#scrape_config

`file_sd_configs` is the one of the`scrap_config` keys name, and `<file_sd_config>` is a item of file_sd_configs, used to describe the file_sd_config pattern.

**Comment by bwplotka** [comment]
Hello from the Bug Scrub!

Thanks for reporting, but indeed this is documented as intended (the doc piece is about one item).
