### ISSUE TITLE
Promethus service keeps on restarting with fatal error: runtime: out of memory.

### ISSUE THREAD

**Issue by venkatakarthikbandaru** [prometheus/prometheus#12520]
### What did you do?

Prometheus service has been running fine but we are observing restarts of the service and after restart its trying to load the data and WAL segments after reaching end of loading segments point its again restarts and observer high memory usage.

Is there a way that we can limit Prometheus memory usage.

observed logs:

--/var/log/messages -- "Prometheus: fatal error: runtime: out of memory "

Journal logs are as below

systemd[1]: Started Prometheus Server.
systemd[1]: Stopped Prometheus Server.
systemd[1]: prometheus.service has no holdoff time, scheduling restart.
systemd[1]: prometheus.service failed.
systemd[1]: Unit prometheus.service entered failed state.
systemd[1]: prometheus.service: main process exited, code=killed, status=9/KILL
prometheus[3506]: level=info ts=2023-07-04T09:27:53.997Z caller=head.go:577 component=tsdb msg="WAL segment loaded" segment=91025 maxSegment=93088
prometheus[3506]: level=info ts=2023-07-04T09:27:50.126Z caller=head.go:577 component=tsdb msg="WAL segment loaded" segment=91024 maxSegment=93088
prometheus[3506]: level=info ts=2023-07-04T09:27:50.126Z caller=head.go:577 component=tsdb msg="WAL segment loaded" segment=91023 maxSegment=93088
prometheus[3506]: level=info ts=2023-07-04T09:27:50.125Z caller=head.go:577 component=tsdb msg="WAL segment loaded" segment=91022 maxSegment=93088
prometheus[3506]: level=info ts=2023-07-04T09:27:50.125Z caller=head.go:577 component=tsdb msg="WAL segment loaded" segment=91021 maxSegment=93088
prometheus[3506]: level=info ts=2023-07-04T09:27:50.123Z caller=head.go:577 component=tsdb msg="WAL segment loaded" segment=91020 maxSegment=93088
prometheus[3506]: level=info ts=2023-07-04T09:27:50.123Z caller=head.go:577 component=tsdb msg="WAL segment loaded" segment=91019 maxSegment=93088
prometheus[3506]: level=info ts=2023-07-04T09:27:50.123Z caller=head.go:577 component=tsdb msg="WAL segment loaded" segment=91018 maxSegment=93088
prometheus[3506]: level=info ts=2023-07-04T09:27:50.121Z caller=head.go:577 component=tsdb msg="WAL segment loaded" segment=91017 maxSegment=93088
prometheus[3506]: level=info ts=2023-07-04T09:27:50.120Z caller=head.go:577 component=tsdb msg="WAL segment loaded" segment=91016 maxSegment=93088

### What did you expect to see?

prometheus start and running

### What did you see instead? Under which circumstances?

prometheus keeps on restarting

### System information

RHEL 7.9

### Prometheus version

```text
2.30.0
```

**Comment by bwplotka** [comment]
Hello from the Bug Scrub!

This is unfortunately expected if you scrape too many/too cardinal samples by Prometheus and it OOMs. With the persistent storage it will keep OOM-ing. Some ideas of auto-recovery were discussed [here](https://github.com/prometheus/prometheus/issues/13939). Marking as a duplicate.
