### ISSUE TITLE
Sigv4 support for alertmanager_config

### ISSUE THREAD

**Issue by alvinlin123** [prometheus/prometheus#12536]
### Proposal

One use case for sigv4 support in alertmanager_config is so that Grafana can use AWS Managed Service for Prometheus as external Alertmanager. It is currently not working as noted in https://github.com/grafana/grafana/issues/64064. Grafana uses Prometheus alert notifier code under the hood.

A more generic use case is for people using on-prem Prometheus to send alerts to AWS Managed Service for Prometheus, which can be useful to "migrate to the cloud" in phases.

**Comment by roidelapluie** [comment]
Let's do this!

**Comment by tjhop** [comment]
Is there anyone working on this yet? I believe I have a functional patch and would be happy to PR it if I'm not stepping on any toes

**Comment by tjhop** [comment]
#12774 has been merged, I believe this can be closed now

**Comment by alvinlin123** [comment]
thanks @tjhop! this is my bad, but I just realized you addressed my issue! Thanks!

**Comment by antonbezr** [comment]
Can anyone please share how they have configured their `alertmanager_config`?

Getting this error: `field sigv4 not found in type config.AlertmanagerConfig` using `additionalAlertManagerConfigs` in Helm chart.

**Comment by antonbezr** [comment]
Anyone using kube-prometheus-stack Helm chart?

Anyone know how to setup the path for AMP Alertmanager?

```
      additionalAlertManagerConfigs:
        - scheme: https
          api_version: v2
          path_prefix: /
          static_configs:
            - targets:
                - "https://aps-workspaces.us-west-2.amazonaws.com/workspaces/ws-2a113fca-685d-41d3-9fe2-f7883f09dc84/alertmanager/api/v2/alerts"
          sigv4:
            region: us-west-2
            role_arn: >-
              {{`{{(get (dict
              "dev" "arn:aws:iam::211125483143:role/AmazonManagedPrometheusIngestionRole"
              "beta" "arn:aws:iam::950236693197:role/AmazonManagedPrometheusIngestionRole"
              "prod" "arn:aws:iam::780888491465:role/AmazonManagedPrometheusIngestionRole")
              (index .metadata.labels "leviathan.agi.amazon.dev/cluster-stage"))}}`}}
```

ts=2024-03-02T01:05:35.342Z caller=main.go:512 level=error msg="Error loading config (--config.file=/etc/prometheus/config_out/prometheus.env.yaml)" file=/etc/prometheus/config_out/prometheus.env.yaml err="parsing YAML file /etc/prometheus/config_out/prometheus.env.yaml: \"https://aps-workspaces.us-west-2.amazonaws.com/workspaces/ws-2a113fca-685d-41d3-9fe2-f7883f09dc84/api/v1/remote_write\" is not a valid hostname"
