### ISSUE TITLE
Creating a Primitive Cluster

### ISSUE THREAD

**Issue by Larenim** [prometheus/prometheus#12544]
### Proposal

_Good afternoon._

I would like to clarify whether there are at least some kind of clustering of prometneus in the plans?

I know that for high availability there are solutions using kubernetes or simply branching out many active nodes, but this will not save fault tolerance at the data center level.
- kubernetes is not recommended to be created between several data centers, so the option is no longer necessary.
- Creation of many nodes leads either to redundancy, if the data store is single, or to possible discrepancies in the data, as well as an additional burden on exporters.
Some exporters cannot be run often, for example, scripted ones, or if the exporter is for a database, the same postgress with the addition of custom queries, so only 1 node would be good to remain an active node.

**Closer to the point.**
I would like to have a fairly simple functional configured in the config and having only a few parameters.

`cluster:`
` - members`
`     - node-01`
`     - node-02`
 The parameter points to the list of nodes included in the cluster, including the node where the config is located.

`cluster:`
`  priority: 1` # number
The parameter indicating the priority of the node, the less, the more priority it is as the main node of the cluster, that is, the active

`cluster:`
`   running_different_tasks: false` # bool
a parameter indicating to check configs and in case of discrepancies between jobs between nodes, if set to true, then excellent jobs will be launched even on inactive servers.
For example, there is a server 1 and 2, on 1 there are A and B jobs, on 2 B and C. If there is 1 master, then A and B will be launched on it, and on 2 only C.
If false, but jobs are only run on the active node.

`cluster:`
`  check_config_interval: 60s` # time
A parameter indicating the frequency of checking configs, comparing them.

`cluster:`
`  livenessProbe:`
`               failureThreshold: 3`
`               periodSeconds: 20`
Parameter indicating to check the life of cluster members
For example, if there are 3 unsuccessful checks that occur every 20 seconds, then the node is considered inactive and the active one moves to another node.

Note.
Cluster configs, except for the priority on all nodes, must be the same, otherwise there should be a config mismatch error in the cluster status.

In addition, I would like a separate tab in the interface in which a minimum of information is indicated.
- Status
- cluster members
- number of running jobs in nodes (for parameter running_different_tasks)

What gives this solution:
- removes data redundancy, since 1 job works only once.
- Creates high availability that will work across multiple data centers.
- removes unnecessary load that exporters or scripts under them can create.

**Comment by bwplotka** [comment]
Hello from the Bug Scrub!

Thanks for this idea!

> I would like to clarify whether there are at least some kind of clustering of prometneus in the plans?

There are no plans. Prometheus explicitly does not solve clustering. Instead we allow downstream projects like Cortex, Thanos, Mimir or [Prometheus Operator](https://prometheus-operator.dev/) to scale. Specifically your idea sounds like relate to Prometheus Operator, or even OpenTelemetry Target Allocator feature.
