### ISSUE TITLE
Increase with rollover

### ISSUE THREAD

**Issue by ChevronTango** [prometheus/prometheus#12547]
### Proposal

Right now using `increase` for counter Metrics is very useful, however more often than not special care has to be taken when these Metrics rollover back to zero. This normally causes the increase function to return a huge negative value. Instead it would be much more useful to have a stricter function (maybe strict_increase or increase_with_rollover) that behaves the same way but whenever the value is negative, just returns the underlying value. Ie.

```
result = x2-x1
If result < 0
return x2
else
return result
```

I know that this could probably be achieved with some complex query but it's such a common use case I'm surprised there's not a function for it already.

Right now either our queries are unwieldy or our graphs are useless whenever a rollover occurs, which may or may not be frequent depending on your query. A function like this would simplify things drastically.

**Comment by roidelapluie** [comment]
What is your usecase?

increase should not be used with sub-zero metrics, as it is meant for counters, which start at zero.

**Comment by ChevronTango** [comment]
> What is your usecase?
> 
> increase should not be used with sub-zero metrics, as it is meant for counters, which start at zero.

The issues isn't subzero, but counters which reset to zero, which causes increase to return a negative value. It's still a counter, just one that rolls over. An example would be monthly finances,  or number of alerts per day. Any strictly increasing counter which periodically resets to zero, or an above zero value. Ie. A sawtooth graph.

**Comment by roidelapluie** [comment]
Increase should never return a negative value. Do you have an example with some data to back this up? This would be a serious bug.

**Comment by bwplotka** [comment]
Hello from the Bug Scrub!

As @roidelapluie said, `increase` already should not return any negative values. Let us know if you have found otherwise and how we can repro. Closing for now, thanks!
