### ISSUE TITLE
Prefer to not register metrics globally

### ISSUE THREAD

**Issue by ptodev** [prometheus/prometheus#12549]
### Proposal

A lot of packages register metrics with the default Prometheus registry. This is a problem for applications such as Grafana Agent, where there could be multiple instances of the same [service discovery component](https://github.com/grafana/agent/tree/main/component/discovery), or multiple [scrape components](https://github.com/grafana/agent/blob/main/component/prometheus/scrape/scrape.go). Different instances of these components should have different series, so that we can differentiate them. At a minimum, we will need this for metrics prefixed with:
* `prometheus_target_`
* `prometheus_sd_`

One way to achieve this would be via passing a Registerer to constructors such as:
* [scrape.NewManager](https://github.com/prometheus/prometheus/blob/main/scrape/manager.go#L104)
* SD constructors such as [dns.NewDiscovery](https://github.com/prometheus/prometheus/blob/main/discovery/dns/dns.go#L128)

This is similar to how we currently pass custom loggers. Since a metrics registerer is also a type of telemetry settings, it makes sense to pass them in the same way as logging settings.

I believe we should only register with the global registry if a custom one is not provided:
* If someone is supplying a custom registry, the chances are that they don't need the global one and using it would just add unnecessary series to it.
* This would make this a breaking change, because currently metrics are registered during `init()`. This means that metrics are registered even if some components are not used. If we use constructors for registering, then if a component is never used its metrics will never be registered (even with the global registry).

**Comment by beorn7** [comment]
Hello from the bug scrub!

Some work has been done on this. Thank you very much @ptodev! Is there anything left to do?

**Comment by ptodev** [comment]
Hi @beorn7, thank you too for your help with this 😊 We can close this issue, because it's referring to packages imported by other repositories. However, the default registry is still used in `main.go` so I opened #15725 to rectify this. I won't be able to to pick this up in the near future, but maybe someone else would be willing to take a look.

**Comment by beorn7** [comment]
Makes sense, thank you very much.
