### ISSUE TITLE
Histograms: not all examplars are ingested

### ISSUE THREAD

**Issue by beorn7** [prometheus/prometheus#12553]
### What did you do?

Exposed exemplars alongside classic buckets, but also exposed a native histogram.

### What did you expect to see?

The native histogram should be ingested together with all the exemplars assigned to the classic buckets.

### What did you see instead? Under which circumstances?

Only the first exemplar is ingested.

### Notes

See https://cloud-native.slack.com/archives/C02KR205UMU/p1688414381799849 for the findings.

It's unclear if that happened with `scrape_classic_histograms` set or not, but that has to be checked in any case.

**Comment by beorn7** [comment]
The protobuf parser seems to do the right thing. Multiple exemplars per histogram is covered by tests. So we have to assume that the exemplars are thrown away later in the process. Investigating…

**Comment by beorn7** [comment]
Fixed in 2.46.0. :tada:

**Comment by bboreham** [comment]
Can you clarify whether this was a problem when using solely classic histograms?

**Comment by beorn7** [comment]
It's not a problem with classic histograms because there will be at most one exemplar per bucket, which translates into one exemplar per ingested sample, which works fine.
