### ISSUE TITLE
Ability to enable admin API on a separate listener

### ISSUE THREAD

**Issue by matzarah** [prometheus/prometheus#12567]
### Proposal

To enable the the admin API, it requires Prometheus to be started with a command line arg and the API is available through the standard HTTP listener. 

This makes it challenging to turn on and off when required, especially when working with a large Prometheus instance that takes a long time to start due due to WAL replay. 

It would be helpful if the admin API could optionally be exposed through a separate listener, then administrators could choose to leave it enabled at all times but only available on localhost and thus not exposed to externally with other features of the HTTP listener.

**Comment by beorn7** [comment]
Hello from the bug scrub!

This could be implemented as part of https://github.com/prometheus/exporter-toolkit/issues/260 .
We feel that we shouldn't solve this for the admin endpoint specifically, but have a solution that allows users to route endpoints differently (e.g. /pprof is an often discussed topic).

Closing this as it is covered by https://github.com/prometheus/exporter-toolkit/issues/260 .
