### ISSUE TITLE
Alertmanager Prometheus, I can't see mail alert?

### ISSUE THREAD

**Issue by ThuyNT2916** [prometheus/prometheus#1258]
Hi,
I'm beginer with Prometheus, I have some trouble and need help.
I config alertmanager.conf:
```
notification_config {
    name: "alert_email"
    email_config {
        email: "abc@gmail.com"
    }
}
aggregation_rule {
  repeat_rate_seconds: 3600
  notification_config_name: "alertmanager_email"
}
```
And I config alertmanager.url, when I restart prometheus, I see notice:

"Error sending notification: Post http://localhost:9093/api/alerts: dial tcp localhost:9093: connection refused  file=notification.go line=198" and I can't access to http://localhost:9093

Can you help me!
Thanks!

**Comment by fabxc** [comment]
Are you running Alertmanager on your local machine? What does Alertmanager log on startup and does it actually keep running or terminate right away?

**Comment by beorn7** [comment]
Since there was no follow-up in a while, I'm closing this. Please re-open with more information if applicable.

**Comment by deveshmehta** [comment]
Hi both,

I am facing the same issue. I am running the AlertManager and Prometheous on the same local machine.

Below is my alert manager logs and it keeps running and doesn't terminate right away.
[root@itsp2prom01 alertmanager-0.4.2.linux-amd64]# ./alertmanager -config.file=simple.yml
INFO[0000] Starting alertmanager (version=0.4.2, branch=master, revision=9a5ab2fa63dd7951f4f202b0846d4f4d8e9615b0)  source=main.go:84
INFO[0000] Build context (go=go1.6.3, user=root@2811d2f42616, date=20160902-15:33:13)  source=main.go:85
INFO[0000] Loading configuration file                    file=simple.yml source=main.go:156
INFO[0000] Listening on :9093                            source=main.go:206

grep -v '#' simple.yml
global:
  smtp_smarthost: 'mailserver:25'
  smtp_from: 'root@localhost.itsprod.net'

templates:
- '/etc/alertmanager/template/*.tmpl'

route:
  group_by: ['alertname', 'cluster', 'service']

  group_wait: 30s

  group_interval: 5m

  repeat_interval: 3h

  receiver: team-X-mails


receivers:
- name: 'team-X-mails'
  email_configs:
  - to: 'devesh251@gmail.com'

Please let me know if you need more details

Thanks
Devesh
