### ISSUE TITLE
incompatible with latest go/x/exp package

### ISSUE THREAD

**Issue by diurnalist** [prometheus/prometheus#12602]
### What did you do?

I have integrated the prometheus library into a project as a dependency and it fails to build if using the latest x/exp package. The issue seems to be that the slices package has been updated to use a different call signature.

https://cs.opensource.google/go/x/exp/+/302865e7556b4ae5de27248ce625d443ef4ad3ed

It seems that the stdlib implementation of this uses the `int` comparable, so prometheus should probably follow that.

### What did you see instead? Under which circumstances?

Would expect it to build in supported Go versions.

**Comment by diurnalist** [comment]
To be clear this isn't really a bug, but it was surprising to me as a user of the package. I am able to work around it by explicitly depending on an earlier version of the exp package.

**Comment by lufia** [comment]
Maybe this was fixed by #12650

**Comment by beorn7** [comment]
Hello from the bug scrub!

This indeed appears to be fixed long ago.
