### ISSUE TITLE
Performance: when ingesting Otel metrics, use a cache for metric and labels normalization

### ISSUE THREAD

**Issue by bertysentry** [prometheus/prometheus#12627]
### Proposal

Now that https://github.com/prometheus/prometheus/pull/12571 has been merged, we can ingest Otel metrics directly.

Otel metric names and labels are normalized with some code from the translator of OpenTelemetry Prometheus exporters. The normalization involves a lot of string operations (matching, replacing, concatenations, etc.) and is performed on-the-fly during the ingestion. This consumes significant processor cycles.

As the function that translates (metricName, metricType, metricUnit) always result with the same Prometheus metric name, we could use a cache mechanism to avoid running the normalization again and again.

A thread-safe dictionary should do the trick.

Potential problem: the cache could grow in size infinitely. Should it have a limit?

**Comment by aknuds1** [comment]
By normalizing OTel metric names, do you mean `prometheustranslator.BuildCompliantName`? Since this issue was opened, I have [optimized](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/29686) the translation code by generating the Prometheus metric name _per metric_, instead of per sample as it used to be. Therefore, it's less of a bottleneck than it used to be :)

**Comment by aknuds1** [comment]
On the topic of OTLP performance; I noticed from profiling that building metric identifiers is a bottleneck, and have [prototyped](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/31385) a version of the `prometheusremotewrite` package that instead hashes label sets in the way that Prometheus does. It gives a nice performance bump.

**Comment by jesusvazquez** [comment]
@aknuds1 did work on multiple performance improvements for the OTLP ingestion endpoint so I'm closing this issue for now.

@bertysentry please feel free to reopen or open a new one with some specifics about what you would like to do in case its different to what Arve did. Thank you!

**Comment by bertysentry** [comment]
That's great, thank you!
