### ISSUE TITLE
Mark out-of-order as stable

### ISSUE THREAD

**Issue by jesusvazquez** [prometheus/prometheus#12631]
### Proposal

Out-of-order has been out for a year now, and we've gained enough production experience to consider it as a stable feature.

Also out-of-order is a downstream dependency of OTEL Support because of how OTEL clients interact with Prometheus so as part of the initiative to have a better OTEL Support we need to mark this feature as stable.

### Related issues

- https://github.com/prometheus/prometheus/issues/11329
- https://github.com/prometheus/prometheus/issues/11628
- https://github.com/prometheus/prometheus/pull/11644
- https://github.com/prometheus/prometheus/issues/11837
- https://github.com/prometheus/prometheus/pull/12133
- https://github.com/prometheus/prometheus/issues/11730
- Nice to have:
  - https://github.com/prometheus/prometheus/issues/11834
    - https://github.com/prometheus/prometheus/pull/11847

### Other actions

- Write documentation on how to enable out-of-order. (Done)
- Write a Prometheus blogpost announcing out-of-order as stable.
- Highlight this on the next release when it happens. (Done)

**Comment by roidelapluie** [comment]
Requires #11730

**Comment by ArthurSens** [comment]
A good place to start might be reading the original Out-of-order proposal and understanding how it works :) 

https://docs.google.com/document/d/1Kppm7qL9C-BJB1j6yb6-9ObG3AbdZnFUBYPNNWwDBYM/edit#heading=h.unv3m5m27vuc

**Comment by Atharva-Kanherkar** [comment]
Hi @ArthurSens!

Are there any pre-requisites for the application of LFX mentorship in this issue? (Other than an open mind and some existing skills :) )

**Comment by ArthurSens** [comment]
I'm not the mentor for this project, so I'm not the best person to ask that. I'd say that this project is somewhat complex, so understanding Prometheus internals might be a requirement.

But again, it would be better to ask the official mentors, as they might have different opinions and it's them who are going to make the selection :)

**Comment by Atharva-Kanherkar** [comment]
@ArthurSens Where can I contact them?

**Comment by jesusvazquez** [comment]
I'm working on https://github.com/prometheus/prometheus/issues/11730 and https://github.com/prometheus/prometheus/issues/11765 and then we will be able to mark OOO as stable.

**Comment by jesusvazquez** [comment]
I'll close the issue when this is merged https://github.com/prometheus/prometheus/pull/15215

**Comment by jesusvazquez** [comment]
Closing as done 🎉
