### ISSUE TITLE
Setting different limit for alerting And recording rule in a rule group

### ISSUE THREAD

**Issue by vardhaman-surana** [prometheus/prometheus#12646]
### Proposal

currently there is just one field to limit the number of active alerts and series produced by a recording rule per rule group. 
Having two fields like **limitSeriesProduced** and **limitActiveAlerts** would help in setting different limit for alerting rules and recording rules.

**Comment by machine424** [comment]
FYI https://github.com/prometheus/prometheus/issues/12415 is asking for another kind of limiting.

**Comment by beorn7** [comment]
Hello from the bug scrub!

As the discussion didn't really go anywhere in more than a year, let's close this.
Limits per group can still get you a long way. We don't want to add more and more limits, which is ultimately really confusing.
