### ISSUE TITLE
Upgrade golang.org/x/exp

### ISSUE THREAD

**Issue by dmitryax** [prometheus/prometheus#12649]
### Proposal

The project uses `golang.org/x/exp/slices.SortFunc` extensively. Recently `golang.org/x/exp` got a backward incompatible change to the callback function signature to match the upcoming go1.21 standard library API: https://github.com/golang/exp/commit/302865e7556b4ae5de27248ce625d443ef4ad3ed#diff-ec22fd7f0aec27f1c6dc503e7dd3960c8f5ab781684218aa59b404ada0d48231R29.

In order to upgrade `golang.org/x/exp`, all the function usages have to be updated or replaced

**Comment by bboreham** [comment]
I looked up where it was decided to change `SortFunc`: https://github.com/golang/go/issues/60091#issuecomment-1553850782
