### ISSUE TITLE
`promtool check rules <file>` is broken

### ISSUE THREAD

**Issue by kfdm** [prometheus/prometheus#12663]
### What did you do?

I have written a rule with a known bad annotation

```
groups:
  - name: example-rule
    rules:
      - alert: example-rule
        annotations:
          summary: "{{$label.foo}}"
        expr: up==1
        for: 1s
        labels:
          severity: high
```

When I run with 2.46 it shows no error

```
~/Downloads/prometheus-2.46.0.darwin-arm64/promtool check rules tmp.rule.yml
Checking tmp.rule.yml
```

When I run with 2.45 it shows the error

```
~/Downloads/prometheus-2.45.0.darwin-arm64/promtool check rules tmp.rule.yml
Checking tmp.rule.yml
  FAILED:
tmp.rule.yml: group "example-rule", rule 1, "example-rule": annotation "summary": template: __alert_example-rule:1: undefined variable "$label"
```

I suspect the changes in https://github.com/prometheus/prometheus/pull/12225 are the source of the issue.

https://github.com/prometheus/prometheus/blob/f676d4a756f6833ba2694b2c6600259ff3c62533/cmd/promtool/main.go#L729-L733

`ParseFile` already validates the rules and detects the answer, but because the error check here immediately sets `failed = true` and then `continue`, there is no opportunity for the error messages to be printed out.

### What did you expect to see?

```
~/Downloads/prometheus-2.45.0.darwin-arm64/promtool check rules tmp.rule.yml
Checking tmp.rule.yml
  FAILED:
tmp.rule.yml: group "example-rule", rule 1, "example-rule": annotation "summary": template: __alert_example-rule:1: undefined variable "$label"
```

### What did you see instead? Under which circumstances?

```
~/Downloads/prometheus-2.46.0.darwin-arm64/promtool check rules tmp.rule.yml
Checking tmp.rule.yml
```

### System information

Darwin 22.5.0 arm64

### Prometheus version

```text
~/Downloads/prometheus-2.46.0.darwin-arm64/promtool --version
promtool, version 2.46.0 (branch: HEAD, revision: cbb69e51423565ec40f46e74f4ff2dbb3b7fb4f0)
  build user:       root@a12703ef1de3
  build date:       20230725-12:36:56
  go version:       go1.20.6
  platform:         darwin/arm64
  tags:             netgo,builtinassets,stringlabels
```

**Comment by kfdm** [comment]
Doing an additional test, it appears the exit code is also incorrect.

```
❯ ~/Downloads/prometheus-2.46.0.darwin-arm64/promtool check rules < tmp.rule.yml
Checking standard input
group "example-group", rule 1, "example-rule": annotation "summary": template: __alert_example-rule:1: undefined variable "$label"

❯ echo $?
1

❯ ~/Downloads/prometheus-2.46.0.darwin-arm64/promtool check rules  tmp.rule.yml 
Checking tmp.rule.yml

❯ echo $?
0
```

**Comment by roidelapluie** [comment]
Thanks! Are you willing to send a PR?

**Comment by kfdm** [comment]
I can give it a shot though Go isn't my primary language, so it often takes me a bit longer to figure out a clean solution.

**Comment by DrAuYueng** [comment]
I submitted a PR(#12715 ) to fix this and added some test cases.
This is the result of the unit test:
<img width="1057" alt="image" src="https://github.com/prometheus/prometheus/assets/1527849/8315c7ff-5744-468c-9163-521e1f7c0cf1">

<img width="864" alt="image" src="https://github.com/prometheus/prometheus/assets/1527849/6ab7a07c-18c8-4f43-a2dd-dd0b2dee3aaa">
