### ISSUE TITLE
uri=root 

### ISSUE THREAD

**Issue by houzhao666** [prometheus/prometheus#12683]
### What did you do?

1.Access interface actuator/prometheus

![MicrosoftTeams-image (81)](https://github.com/prometheus/prometheus/assets/45731570/f73b6c4f-96e1-44ca-b785-aeb6df2c3341)

The system does not have a root interface, and the interface returns root information.

### What did you see instead? Under which circumstances?

![MicrosoftTeams-image (82)](https://github.com/prometheus/prometheus/assets/45731570/957d2393-980b-432e-82ec-118331179619)

**Comment by roidelapluie** [comment]
Thanks for this pull request. This does not seem to be related to Prometheus.Please check with your library provider (actuator?).

**Comment by houzhao666** [comment]
Okay, thank you very much.
