### ISSUE TITLE
Recording rule discarding samples for histograms

### ISSUE THREAD

**Issue by jmcarp** [prometheus/prometheus#12713]
### What did you do?

I'm testing switching from classic to native histograms, and my use case includes calculating rates and histogram quantiles over histograms using recording rules.

### What did you expect to see?

Rates and histogram quantiles should be calculated as for classic histograms, with no errors or gaps in metrics.

### What did you see instead? Under which circumstances?

I noticed that a recording rule that calculates a rate over a histogram metric now has occasional gaps in the resulting series, with corresponding log messages like `0.180000 observations found in buckets, but the Count field is 0.180000`.

<img width="913" alt="Screenshot 2023-08-16 at 8 27 08 PM" src="https://github.com/prometheus/prometheus/assets/1633460/3e851287-28f1-4f5f-8b26-6324cbdfc1fb">

A complete log line:

```
ts=2023-08-16T22:57:24.182Z caller=manager.go:735 level=warn component="rule manager" file=/etc/prometheus/rules/aggregation.rules.yml group=rules/aggregation.rules name=sqlprober_dedicated_latency_ns:rate1m index=60 msg="Rule evaluation result discarded" err="0.180000 observations found in buckets, but the Count field is 0.180000: histogram's observation count should be at least the number of observations found in the buckets" sample="{__name__=\"sqlprober_dedicated_latency_ns:rate1m\"} => {count:0.18, sum:154043.88, (623487.0199105466,679917.4164288685]:0.02, (679917.4164288685,741455.2001894652]:0.02, (741455.2001894652,808562.6292314784]:0.04, (808562.6292314784,881743.7995210788]:0.06, (1.048576e+06,1.1434802362872052e+06]:0.04} @[1692226643986]"
```

I wonder if this is some kind of floating point comparison bug, because 0.180000 >= 0.180000.

Note that if I run the same query used in the recording rule in the prometheus web interface, the result has no gaps, so this appears to be specific to recording rules.

### System information

Linux 5.4.238-148.347.amzn2.x86_64 x86_64

### Prometheus version

```text
prometheus, version 2.46.0 (branch: HEAD, revision: cbb69e51423565ec40f46e74f4ff2dbb3b7fb4f0)
  build user:       root@42454fc0f41e
  build date:       20230725-12:31:24
  go version:       go1.20.6
  platform:         linux/amd64
  tags:             netgo,builtinassets,stringlabels
```

**Comment by beorn7** [comment]
Thanks for reporting. This seems to be a precision issue during the validation.
