### ISSUE TITLE
Flaky TestScrapeLoopCache

### ISSUE THREAD

**Issue by bboreham** [prometheus/prometheus#12727]
### What did you do?

Failed at https://github.com/prometheus/prometheus/actions/runs/5878305514/job/15940103209?pr=12710

### What did you see instead? Under which circumstances?

```
=== RUN   TestScrapeLoopCache
    scrape_test.go:1346: 
        	Error Trace:	D:/a/prometheus/prometheus/scrape/scrape_test.go:1346
        	Error:      	Not equal: 
        	            	expected: 26
        	            	actual  : 25
        	Test:       	TestScrapeLoopCache
        	Messages:   	Appended samples not as expected:
        	            	committed: {__name__="metric_a"} 42.000000 1692188133189
        	            	committed: {__name__="metric_b"} 43.000000 1692188133189
        	            	committed: {__name__="up"} 1.000000 1692188133189
        	            	committed: {__name__="scrape_duration_seconds"} 0.000000 1692188133189
        	            	committed: {__name__="scrape_samples_scraped"} 2.000000 1692188133189
        	            	committed: {__name__="scrape_samples_post_metric_relabeling"} 2.000000 1692188133189
        	            	committed: {__name__="scrape_series_added"} 2.000000 1692188133189
        	            	committed: {__name__="metric_a"} NaN 1692188133209
        	            	committed: {__name__="metric_b"} NaN 1692188133209
        	            	committed: {__name__="up"} 0.000000 1692188133209
        	            	committed: {__name__="scrape_duration_seconds"} 0.000145 1692188133209
        	            	committed: {__name__="scrape_samples_scraped"} 0.000000 1692188133209
        	            	committed: {__name__="scrape_samples_post_metric_relabeling"} 0.000000 1692188133209
        	            	committed: {__name__="scrape_series_added"} 0.000000 1692188133209
        	            	committed: {__name__="metric_a"} 44.000000 1692188133209
        	            	committed: {__name__="up"} 1.000000 1692188133209
        	            	committed: {__name__="scrape_duration_seconds"} 0.000000 1692188133209
        	            	committed: {__name__="scrape_samples_scraped"} 1.000000 1692188133209
        	            	committed: {__name__="scrape_samples_post_metric_relabeling"} 1.000000 1692188133209
        	            	committed: {__name__="scrape_series_added"} 0.000000 1692188133209
        	            	committed: {__name__="up"} 0.000000 1692188133225
        	            	committed: {__name__="scrape_duration_seconds"} 0.000000 1692188133225
        	            	committed: {__name__="scrape_samples_scraped"} 0.000000 1692188133225
        	            	committed: {__name__="scrape_samples_post_metric_relabeling"} 0.000000 1692188133225
        	            	committed: {__name__="scrape_series_added"} 0.000000 1692188133225
--- FAIL: TestScrapeLoopCache (0.06s)
```

**Comment by bboreham** [comment]
The line that is missing is 
```
                                committed: {__name__="metric_a"} NaN 1692539639135
```

That metric should be marked as stale after the last scrape.

**Comment by machine424** [comment]
I took a look at this as I saw it twice recently, after burning some CPU cycles using (`main` with `go 1.21.5`):
`go test -v -count=1000000 ./scrape/ -run "^TestScrapeLoopCache$" -timeout 999999999s`
I think the problem is with the scrapeLoop ticker:
https://github.com/prometheus/prometheus/blob/6b8e9453881bffe5fe3aec99a6f3462676a95489/scrape/scrape.go#L1160-L1201
After adding a log, I can see:
```
=== RUN   TestScrapeLoopCache
2023-12-26 21:36:32.26559 +0100 CET m=+426.091768168 scrapeLoop.run ticker.C
2023-12-26 21:36:32.287033 +0100 CET m=+426.113210918 scrapeLoop.run ticker.C
2023-12-26 21:36:32.295742 +0100 CET m=+426.121920293 scrapeLoop.run ticker.C
--- PASS: TestScrapeLoopCache (0.07s)
=== RUN   TestScrapeLoopCache
2023-12-26 21:36:32.330122 +0100 CET m=+426.156300210 scrapeLoop.run ticker.C
2023-12-26 21:36:32.330856 +0100 CET m=+426.157034376 scrapeLoop.run ticker.C
2023-12-26 21:36:32.341542 +0100 CET m=+426.167720710 scrapeLoop.run ticker.C
    scrape_test.go:1246: 
        	Error Trace:	/Users/machine424/personal-projects/github/prometheus/scrape/scrape_test.go:1246
        	Error:      	"[{[{__name__ metric_a}] %!s(int64=1703622992310) %!s(float64=42)} {[{__name__ metric_b}] %!s(int64=1703622992310) %!s(float64=43)} {[{__name__ up}] %!s(int64=1703622992310) %!s(float64=1)} {[{__name__ scrape_duration_seconds}] %!s(int64=1703622992310) %!s(float64=9.8834e-05)} {[{__name__ scrape_samples_scraped}] %!s(int64=1703622992310) %!s(float64=2)} {[{__name__ scrape_samples_post_metric_relabeling}] %!s(int64=1703622992310) %!s(float64=2)} {[{__name__ scrape_series_added}] %!s(int64=1703622992310) %!s(float64=2)} {[{__name__ metric_b}] %!s(int64=1703622992330) %!s(float64=NaN)} {[{__name__ metric_a}] %!s(int64=1703622992330) %!s(float64=NaN)} {[{__name__ up}] %!s(int64=1703622992330) %!s(float64=0)} {[{__name__ scrape_duration_seconds}] %!s(int64=1703622992330) %!s(float64=0.000218042)} {[{__name__ scrape_samples_scraped}] %!s(int64=1703622992330) %!s(float64=0)} {[{__name__ scrape_samples_post_metric_relabeling}] %!s(int64=1703622992330) %!s(float64=0)} {[{__name__ scrape_series_added}] %!s(int64=1703622992330) %!s(float64=0)} {[{__name__ metric_a}] %!s(int64=1703622992330) %!s(float64=44)} {[{__name__ up}] %!s(int64=1703622992330) %!s(float64=1)} {[{__name__ scrape_duration_seconds}] %!s(int64=1703622992330) %!s(float64=8.4709e-05)} {[{__name__ scrape_samples_scraped}] %!s(int64=1703622992330) %!s(float64=1)} {[{__name__ scrape_samples_post_metric_relabeling}] %!s(int64=1703622992330) %!s(float64=1)} {[{__name__ scrape_series_added}] %!s(int64=1703622992330) %!s(float64=0)} {[{__name__ up}] %!s(int64=1703622992341) %!s(float64=0)} {[{__name__ scrape_duration_seconds}] %!s(int64=1703622992341) %!s(float64=9.6084e-05)} {[{__name__ scrape_samples_scraped}] %!s(int64=1703622992341) %!s(float64=0)} {[{__name__ scrape_samples_post_metric_relabeling}] %!s(int64=1703622992341) %!s(float64=0)} {[{__name__ scrape_series_added}] %!s(int64=1703622992341) %!s(float64=0)}]" should have 26 item(s), but has 25
        	Test:       	TestScrapeLoopCache
        	Messages:   	Appended samples not as expected:
        	            	committed: {__name__="metric_a"} 42.000000 1703622992310
        	            	committed: {__name__="metric_b"} 43.000000 1703622992310
        	            	committed: {__name__="up"} 1.000000 1703622992310
        	            	committed: {__name__="scrape_duration_seconds"} 0.000099 1703622992310
        	            	committed: {__name__="scrape_samples_scraped"} 2.000000 1703622992310
        	            	committed: {__name__="scrape_samples_post_metric_relabeling"} 2.000000 1703622992310
        	            	committed: {__name__="scrape_series_added"} 2.000000 1703622992310
        	            	committed: {__name__="metric_b"} NaN 1703622992330
        	            	committed: {__name__="metric_a"} NaN 1703622992330
        	            	committed: {__name__="up"} 0.000000 1703622992330
        	            	committed: {__name__="scrape_duration_seconds"} 0.000218 1703622992330
        	            	committed: {__name__="scrape_samples_scraped"} 0.000000 1703622992330
        	            	committed: {__name__="scrape_samples_post_metric_relabeling"} 0.000000 1703622992330
        	            	committed: {__name__="scrape_series_added"} 0.000000 1703622992330
        	            	committed: {__name__="metric_a"} 44.000000 1703622992330
        	            	committed: {__name__="up"} 1.000000 1703622992330
        	            	committed: {__name__="scrape_duration_seconds"} 0.000085 1703622992330
        	            	committed: {__name__="scrape_samples_scraped"} 1.000000 1703622992330
        	            	committed: {__name__="scrape_samples_post_metric_relabeling"} 1.000000 1703622992330
        	            	committed: {__name__="scrape_series_added"} 0.000000 1703622992330
        	            	committed: {__name__="up"} 0.000000 1703622992341
        	            	committed: {__name__="scrape_duration_seconds"} 0.000096 1703622992341
        	            	committed: {__name__="scrape_samples_scraped"} 0.000000 1703622992341
        	            	committed: {__name__="scrape_samples_post_metric_relabeling"} 0.000000 1703622992341
        	            	committed: {__name__="scrape_series_added"} 0.000000 1703622992341
--- FAIL: TestScrapeLoopCache (0.04s)
```
Sometimes it ticks at the same `ms` timestamp
https://github.com/prometheus/prometheus/blob/6b8e9453881bffe5fe3aec99a6f3462676a95489/scrape/scrape_test.go#L1197

And the third scrape ends up being made at the same millisecond timestamp than the second one.
And because of:
https://github.com/prometheus/prometheus/blob/6b8e9453881bffe5fe3aec99a6f3462676a95489/tsdb/head_append.go#L465-L472
`{__name__="metric_a"} 44` is never appended and this the metric isn't marked as stale at the end.

Expanding the interval should decrease the likelihood of it ticking at the same millisecond timestamp: https://github.com/prometheus/prometheus/pull/13336

But I still have some questions:
- Isn't it confusing to mark it as committed? `committed: {__name__="metric_a"} 44.000000 1703622992330`
- Shouldn't we allow overriding a `NaN` with a known value with the same timestamp instead of ErrDuplicateSampleForTimestamp?
- Maybe we should make it more explicit that `XXms` scrape intervals are not recommended.

---

What do you think about adding the possibility to enable the debug log level when running tests, the following debug log could have been helpful to debug this:

https://github.com/prometheus/prometheus/blob/6b8e9453881bffe5fe3aec99a6f3462676a95489/scrape/scrape.go#L1719-L1723

**Comment by bboreham** [comment]
Thanks, great work!

Let me check I got this right: Prometheus asks Go to fire a timer every 10 ms, but you observed ticks at 295ms, 330ms, 330ms and 345ms. It averages out quite close, but two ticks at 330ms breaks assumptions in the code.
This issue https://github.com/golang/go/issues/44343 seems to explain the symptom, and why we see it more on Windows.

> Isn't it confusing to mark it as committed? committed: {__name__="metric_a"} 44.000000 1703622992330

I think the intention is to say that `Commit()` was called on the appender, i.e. the scrape finished without error.

> Shouldn't we allow overriding a NaN with a known value with the same timestamp instead of ErrDuplicateSampleForTimestamp?

That is an interesting idea.  If we narrow to "`StaleNaN`, the specific NaN used for stale values" I definitely agree.
I'm not sure if other NaNs can get into TSDB; perhaps via protobuf?

> Maybe we should make it more explicit that XXms scrape intervals are not recommended.

Yes, the Prometheus documentation could explain this issue in Go, particularly on Windows.

Alternatively, we could use `TimeBeginPeriod`, new in Go 1.22, to make timers more accurate when scrape jobs have such small intervals.  Ref https://github.com/golang/go/issues/61723

**Comment by machine424** [comment]
Thanks for your input Bryan!

> Let me check I got this right: Prometheus asks Go to fire a timer every 10 ms, but you observed ticks at 295ms, 330ms, 330ms and 345ms. It averages out quite close, but two ticks at 330ms breaks assumptions in the code.
You're correct!

> This issue https://github.com/golang/go/issues/44343 seems to explain the symptom, and why we see it more on Windows.
I came across that one but I thought it only related to durations being exceeded, here it sometimes ticks after 0.5ms instead of the desired 10ms...

> That is an interesting idea. If we narrow to "StaleNaN, the specific NaN used for stale values" I definitely agree.
I'm not sure if other NaNs can get into TSDB; perhaps via protobuf?

Yep, I was talking about `StaleNaN`, I'll run some tests and maybe start a discussion about that.

> Yes, the Prometheus documentation could explain this issue in Go, particularly on Windows.

> Alternatively, we could use TimeBeginPeriod, new in Go 1.22, to make timers more accurate when scrape jobs have such small intervals. Ref https://github.com/golang/go/issues/61723

I'm seeing that on mac as well, I'll see how we can mention that in the doc and +1 to test those new APIs for windows.
