### ISSUE TITLE
Prometheus false positive alerts "KubeClientCertificateExpiration"

### ISSUE THREAD

**Issue by Karthik6615** [prometheus/prometheus#12735]
### What did you do?

This is query which is getting executed on Prometheus alert manager for KubeClientCertificateExpiration: "histogram_quantile(0.01, sum by (job, le) (rate(apiserver_client_certificate_expiration_seconds_bucket{job="apiserver"}[5m]))) < 604800"

After investigation in our Kubernetes cluster we couldn't find any client certificate which is getting expired within 7 days range. Still above query is triggering alerts.

### What did you expect to see?

No alert should be triggered for  KubeClientCertificateExpiration

### What did you see instead? Under which circumstances?

we are seeing KubeClientCertificateExpiration prometheus alert.

:fire: [FIRING:1] KubeClientCertificateExpiration
Cluster: production-<location>-aks
Description: A client certificate used to authenticate to kubernetes apiserver is expiring in less than 24.0 hours.Details:
• endpoint: https
• instance: <server-ip>
• job: apiserver
• namespace: default
• prometheus: service/prometheus-prometheus
• service: kubernetes
• severity: critical```

Which is not excepted.

### System information

Ubuntu 22.04.2 LTS

**Comment by roidelapluie** [comment]
Thanks for your issue.

This seems related to the Prometheus Operator, you could open an issue here: https://github.com/prometheus-operator/prometheus-operator/issues
