### ISSUE TITLE
kubernetes_sd_config __metas for namespaces

### ISSUE THREAD

**Issue by genofire** [prometheus/prometheus#12745]
### Proposal

i would like to have from namespace the metas like label.

there is just the name:
`__meta_kubernetes_namespace`

my proposal would be:
 * `__meta_kubernetes_namespace`: keep name there for backport, or move to `__meta_kubernetes_namespace_name`
 * `__meta_kubernetes_namespace_uid`: The UID of the namespace object.
 * `__meta_kubernetes_namespace_label_<labelname>`: Each label from the namespace object.
 * `__meta_kubernetes_namespace_labelpresent_<labelname>`: true for each label from the namespace object.
 * `__meta_kubernetes_namespace_annotation_<annotationname>`: Each annotation from the namespace object.
 * `__meta_kubernetes_namespace_annotationpresent_<annotationname>`: true for each annotation from the namespace object.

**Comment by bboreham** [comment]
How would you use this?

Why is this important for the project?

**Comment by simonpasquier** [comment]
IIUC the request is related to the PR #13798.

**Comment by machine424** [comment]
Apart from the namespace UUID, I think this request is the same as https://github.com/prometheus/prometheus/issues/9510. Maybe we should close this and continue the discussion there.

**Comment by simonpasquier** [comment]
Let's close this one as a duplicate then.
