### ISSUE TITLE
prom query again..

### ISSUE THREAD

**Issue by mysterytree** [prometheus/prometheus#1274]
Hi @juliusv 
I want to monitor the container memory used rate.
I write  this query
```
sum(container_memory_usage_bytes{name!=""})by(name)/machine_memory_bytes 
```
And respones no date.
Maybe  both
```
sum(container_memory_usage_bytes{name!=""})by(name)
```
and 
```
machine_memory_bytes 
```
return a list.
So I have to write  
```
sum(container_memory_usage_bytes{name!=""})by(name)/16829906944*100
```
I have two vm with same the memory
So it can works.
But if they are different ,what should I do ?

**Comment by roman-vynar** [comment]
```sum(container_memory_usage_bytes{name!=""})by(name)/ on (LABEL) machine_memory_bytes```
where LABEL is common label between those metrics, i.e. jobname or some host definition.

**Comment by cemo** [comment]
@roman-vynar where `container_memory_usage_bytes` metrics is coming from? I would like to have this metric too but could not find where I should scrape to get this metric.

**Comment by roman-vynar** [comment]
@cemo cadvisor

**Comment by cemo** [comment]
@roman-vynar I am using https://github.com/prometheus/prometheus/blob/master/documentation/examples/prometheus-kubernetes.yml this configuration but I could not be sure that this configuration contains scraping kubelets as well. Is there a part for kubelet inside it?

**Comment by roman-vynar** [comment]
@cemo We are not using Kubernetes, we run cadvisor standalon on each docker host.

**Comment by juliusv** [comment]
@cemo This part should be the one that scrapes the kubelets: https://github.com/prometheus/prometheus/blob/master/documentation/examples/prometheus-kubernetes.yml#L50-L78
