### ISSUE TITLE
Proposal: optionally support underscore in big numbers

### ISSUE THREAD

**Issue by freeseacher** [prometheus/prometheus#12769]
### Proposal

Recently i found a merge request to internal monitoring with scientific notation in right side of expression. That is how currently users trying to cope with big numbers to make it "simple" to read.
Go and many languages now support input numbers with underscore in it.
Please make it possible in promql too. 

support information
https://go.dev/ref/spec#Letters_and_digits
https://peps.python.org/pep-0515/
https://www.javascripttutorial.net/es-next/javascript-numeric-separator/

**Comment by roidelapluie** [comment]
Where exactly would you like to support them?

**Comment by freeseacher** [comment]
in promql query language 
expression like 
`expr: metric_name > 10_000_000_000_000` 
simpler to read then
`expr: metric_name > 10e12`

**Comment by roidelapluie** [comment]
This is quite a change, I will gather the team's opinion about it.

**Comment by freeseacher** [comment]
Any updates on this ?

**Comment by beorn7** [comment]
Did we ever collect the team's opinion about it?

I like it. It the same as in Go.
