### ISSUE TITLE
Standard internal error counter for all exporters?

### ISSUE THREAD

**Issue by RichiH** [prometheus/prometheus#1278]
I think it would make sense to have a canonical metric for internal error counting of all exporters. This would allow easy monitoring when scrape happens upon a partially misconfigured or otherwise non-ideal target.

This is partially motivated by https://github.com/prometheus/snmp_exporter/issues/16

**Comment by brian-brazil** [comment]
There's so many ways that an exporter can fail that this isn't practical. For example that issue is a user configuration error, which is different from the target having an error which is different from a failure.

At most we can offer only general guidance.

**Comment by RichiH** [comment]
While I readily agree that there is a myriad of reasons, the point is that this would allow me to look at antyhing that is not zero.

**Comment by RichiH** [comment]
https://github.com/prometheus/prometheus/issues/1169 is somewhat related to this.

**Comment by brian-brazil** [comment]
#1169 is to cover a failure of the exporter itself to handle a failure.

**Comment by RichiH** [comment]
Correct. One is for failures that could be handled/ignored, one is for the ones which could not.
