### ISSUE TITLE
Cleanup container layout

### ISSUE THREAD

**Issue by SuperQ** [prometheus/prometheus#12793]
### Proposal

The current Dockerfile configuration is such that if you override the default `command` args, the paths to various files are incorrect compared to the default config flags.

It should be possible to pass flags like `--storage.tsdb.retention.time` to the container command without having to also specify the TSDB path or the config path.

This is a breaking change and would have to happen in Prometheus 3.0.

**Comment by walker-tom** [comment]
@SuperQ, @jan--f, I'm happy to have a look at this, did you have any ideas of how it should be done?

**Comment by SuperQ** [comment]
I think this is no longer necessary.
