### ISSUE TITLE
Add a Terraform template

### ISSUE THREAD

**Issue by SuperQ** [prometheus/prometheus#1280]
It would be handy for people using Terraform[0](https://www.terraform.io) to have a config template in the Prometheus code/docs.

**Comment by joeblew99** [comment]
+1 
We are running on AWS, and would like to be able to bring up Prom easily.

Backing up to bacup and restore off S3 would alos be required i guess. I dont know how well Prom handles upgrading and data migration you see,

**Comment by SuperQ** [comment]
@joeblew99 Backups of Prometheus is being tracked in other issues.

**Comment by joeblew99** [comment]
Ok cool

**Comment by joeblew99** [comment]
Anyway. I also use Terraform.
If your looking for an example look at what the cockroachdb guys have. Their Terraform setup is pretty good

**Comment by jcmartins** [comment]
:+1:

**Comment by discordianfish** [comment]
@SuperQ Unfortunately TF doesn't abstract the cloud provider, so we need to create separate terraform templates for various providers.
It's also unclear to me what the specific use case would be. If it should be something people can actually use in prod, it IMO should use static machine images instead some hackish cloud-init install script which would make things even more complicated.

**Comment by brian-brazil** [comment]
I think this is outside the scope of the project, but we can add a link to it from the prometheus.io docs as we do for other config mgmt systems.
