### ISSUE TITLE
Specify InfluxDB password

### ISSUE THREAD

**Issue by simonszu** [prometheus/prometheus#1281]
Hi,

i am trying to achieve a setup where prometheus stores long-term data in an InfluxDB or something. I know about the CLI flags `-storage.remote.influxdb-url`, `-storage.remote.influxdb.database` and `-storage.remote.influxdb.username`, since they show up in the `-h` output. But where should one specify the password of the influxdb user?
Either it isn't implemented, or the -h output is incomplete, so i'm opening this issue. 

Thanks.

**Comment by brian-brazil** [comment]
It's the `INFLUXDB_PW` environment variable.

**Comment by juliusv** [comment]
This issue has a great point - this env variable is not documented anywhere. Since the other InfluxDB settings are currently flags, I think it'd be best to document this in the `storage.remote.influxdb.username` flag` - I'll send a fix.
