### ISSUE TITLE
Ensure Validate() Function is Called for All Service Discoveries Using HTTPClientConfig

### ISSUE THREAD

**Issue by roidelapluie** [prometheus/prometheus#12810]
We would like to make sure that all service discoveries using `HTTPClientConfig` call the `Validate()` function at the end of the `UnmarshalYAML()` method. This is crucial to ensure that the configuration is valid before it is used by the service discoveries.

See #12785 for an example.

Pull requests should preferably only touch one service discovery to make the review and merge process easier and quicker.

Each SD should include at least one test to avoid regressions.

**Comment by slashpai** [comment]
I would like to work on this one :)

**Comment by slashpai** [comment]
Remaining ones to add Validate():
- PuppetDB
- Uyuni

For Kubernetes this is already called but not at the end https://github.com/prometheus/prometheus/blob/b2c5de2e65aeb5c3faba24538bf0290f3ed75f57/discovery/kubernetes/kubernetes.go#L186

**Comment by roidelapluie** [comment]
I think we still miss discovery/aws/lightsail.go

**Comment by slashpai** [comment]
> I think we still miss discovery/aws/lightsail.go

done

**Comment by tonisanta** [comment]
Hello! I can work on some of the missing ones like zookeeper

**Comment by slashpai** [comment]
@roidelapluie Is there anything else remaining on this? I think all are covered.

**Comment by roidelapluie** [comment]
Thanks!
