### ISSUE TITLE
Proposal: Support canceling of queries

### ISSUE THREAD

**Issue by aknuds1** [prometheus/prometheus#12836]
### Proposal

I propose adding a context argument to query processing functions in Prometheus, especially `tsdb.PostingsForMatchers`, so they may respect cancellation. Running Mimir at scale at Grafana Labs, the need to be able to cancel queries in Prometheus has become evident over time.

There is already an open [PR](https://github.com/prometheus/prometheus/pull/12359) for adding a context argument to `tsdb.PostingsForMatchers`, which contains additional rationale.

TODO:

- [ ] See how Prometheus cancels queries via the HTTP `timeout` [query parameter](https://prometheus.io/docs/prometheus/latest/querying/api/#instant-queries), and add a test verifying that cancellation via context is carried out

**Comment by jesusvazquez** [comment]
@aknuds1 thanks for this proposal. If you think that makes sense, lets grow a bit the scope of this and try to produce a unit test where you start a query and it gets successfully cancelled.

**Comment by aknuds1** [comment]
Sounds good @jesusvazquez.

**Comment by yeya24** [comment]
Anything else left for this proposal? I see all prs got merged.

**Comment by aknuds1** [comment]
You're right @yeya24 ,I forgot about this issue :man_facepalming: 

Closing the issue.

**Comment by jesusvazquez** [comment]
@aknuds1 Did you add an unit test testing query cancellation in Prometheus?

**Comment by aknuds1** [comment]
@jesusvazquez I haven't got that far yet, it's on my TODO list. Do you think this issue should stay open until I've done that?

**Comment by jesusvazquez** [comment]
Yep lets do that.
