### ISSUE TITLE
Display total number of returned elements

### ISSUE THREAD

**Issue by RichiH** [prometheus/prometheus#1284]
In the expression browser, I see `Load time:` and `Resolution:`. Displaying the total number of returned element would be quite useful as well.

**Comment by juliusv** [comment]
Internally we also gather quite a lot of timing information about the various stages of a query (https://github.com/prometheus/prometheus/blob/master/util/stats/query_stats.go#L43-L74). It might be useful to return that too, even if we don't always display everything.

**Comment by RichiH** [comment]
Can't hurt. You can hide it behind a plus sign that expands on click.

Richard

Sent by mobile; excuse my brevity.

**Comment by Gouthamve** [comment]
@brian-brazil Can this be closed now?

**Comment by juliusv** [comment]
It would seem so! Closing...

**Comment by RichiH** [comment]
@Gouthamve Thanks! FYI, you can also close issues via your commit message; once the PR is merged, the issue closes.
