### ISSUE TITLE
Synthetic metrics inaccessible in agent mode

### ISSUE THREAD

**Issue by holograph** [prometheus/prometheus#12860]
### What did you do?

Prometheus collects a number of synthetic metrics, notably `scrape_samples_scraped`, with some subtleties:

* These metrics aren't exposed through the `/metrics` endpoint;
* These metrics aren't available on the `/api/v1/metadata` endpoint;
* Other endpoints like `/api/v1/series` do seem to query these metrics successfully, however these endpoints are not available in agent mode.

In effect this means the only way to get at synthetic metrics in agent mode is via remote write. Are these metrics not included in `/metrics` intentionally? Is there another way to get at them?

For more context, although this might be a niche use case, we want a separate mechanism to alert on Prometheus Agent failures (such as `scrape_samples_scraped>scrape_sample_limit`); these alerts still have value even if our remote store (Mimir) is down.

### What did you expect to see?

HTTP calls to `/metrics` ("self scrapes") should include synthetic metrics as well.

### What did you see instead? Under which circumstances?

In agent mode, synthetic metrics aren't exposed through any public API, and are only available through remote_write (and possibly remote_read as well).

### System information

Linux 6.1.29-0-virt x86_64

### Prometheus version

```text
prometheus, version 2.45.0 (branch: HEAD, revision: 8ef767e396bf8445f009f945b0162fd71827f445)
  build user:       root@920118f645b7
  build date:       20230623-15:09:49
  go version:       go1.20.5
  platform:         linux/amd64
  tags:             netgo,builtinassets,stringlabels
```

**Comment by roidelapluie** [comment]
Yes they are not included in /metrics intentionally. They are exposed in /federate but this is not available on the agent. If you want local alerting on prometheus you would need to use the server mode for now.

**Comment by holograph** [comment]
Thanks, that is what I had assumed. But why are these metrics not included? I'm not familiar with /federate (new endpoint?) but I would think any Prometheus instance should be able to expose those, or at least have it configurable?

**Comment by roidelapluie** [comment]
Because /metrics is for performance metrics of prometheus itself. The syntetic metrics are attached to the metrics of the targets we scrape, and so they are directly written in the local TSDB. Also, because prometheus scrapes itself, it comes to my mind that this would lead to many duplicate metrics. I also note that syntetic metrics are written with the exact same timestamp as the scrapes, which would be impossible if exposed with /metrics.

**Comment by holograph** [comment]
I guess this could be documented better (I may take a stab at it, no promises), but that makes a lot of sense, thanks for explaining it!
