### ISSUE TITLE
Ensure maximum native histogram buckets per sample via downscaling

### ISSUE THREAD

**Issue by krajorama** [prometheus/prometheus#12863]
## Problem

In theory a native histogram sample can contain a huge number of buckets. The model allows for
```
        // Observation counts in buckets. The first element is an absolute
	// count. All following ones are deltas relative to the previous
	// element.
	PositiveBuckets, NegativeBuckets []int64
```
A sample can be introduced to Prometheus TSDB by a) scraping b) remote write receiver.

Since there's no limit, it would be fairly easy to intentionally or non intentionally abuse this fact.

## Proposed requirement

Allow the configuration of a bucket count limit.
If limit is set (!=0), any native histogram sample which is above the bucket count limit must be scaled down (the schema decreased) to reduce the number of bucket bellow the limit.

Scrape configuration can be global or on job level. Proposed parameter name: `native_histogram_bucket_limit`.
Remote write receiver is configured currently on the command line. How I would propose to add a configuration section `remove_write_receiver` and have the same parameter as above for consistency.

**Comment by beorn7** [comment]
Scrape config already has `native_histogram_bucket_limit`.

But remote write receiver hasn't.

**Comment by beorn7** [comment]
I guess the concurrently filed https://github.com/prometheus/prometheus/issues/12864 has a bit more context. I'm closing this one.
