### ISSUE TITLE
TestQuerierIndexQueriesRace timed out in CI

### ISSUE THREAD

**Issue by bboreham** [prometheus/prometheus#12867]
Test added in #12558 cc @dimitarvdimitrov.

Failed in #12865:
https://github.com/prometheus/prometheus/actions/runs/6237753012/job/16932051487?pr=12865

Same PR passed on re-run; that test run took only 1m30s.
https://github.com/prometheus/prometheus/actions/runs/6237753012/job/16934382851?pr=12865

Failed in #12851:
https://github.com/prometheus/prometheus/actions/runs/6189131757/job/16802589892?pr=12851

Failed in #12874:
https://github.com/prometheus/prometheus/actions/runs/6249608442/job/16966649393?pr=12874

```
panic: test timed out after 10m0s
running tests:
	TestQuerierIndexQueriesRace (8m42s)
	TestQuerierIndexQueriesRace/[__name__!="metric"] (8m42s)
```

~Since it seems to consistently succeed on retry, I might guess the Action is running multiple things in parallel first time around, and there isn't enough CPU to do this one inside 10 minutes.~ guessed wrong - see real explanation below.

**Comment by dimitarvdimitrov** [comment]
running this locally takes no more than 2s (tried on arm64 M1 mac and on an Intel x86). 

Interestingly it's not the actual test that takes long - it's the cleanup steps that are blocking. From CI logs:


```
goroutine 19185 [semacquire, 8 minutes]:
sync.runtime_Semacquire(0x5302a5?)
	/usr/local/go/src/runtime/sema.go:62 +0x27
sync.(*WaitGroup).Wait(0xc0006afec0?)
	/usr/local/go/src/sync/waitgroup.go:116 +0x4b
testing.(*common).Cleanup.func1()
	/usr/local/go/src/testing/testing.go:1150 +0x11f
testing.(*common).runCleanup(0xc0026bc1a0, 0xc00019cc80?)
	/usr/local/go/src/testing/testing.go:1328 +0xe2
testing.tRunner.func2()
	/usr/local/go/src/testing/testing.go:1570 +0x29
testing.tRunner(0xc0026bc1a0, 0xc0026b45a0)
	/usr/local/go/src/testing/testing.go:1582 +0x135
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1629 +0x3ea
```

**Comment by bboreham** [comment]
Can you say a little more about what went wrong?  It looks from your proposed fix that `appendSeries` should exit immediately because the context isn't cancelled, but it's still running in the goroutine dump.

**Comment by dimitarvdimitrov** [comment]
my understanding is that there is a race condition between a) starting the goroutine and b) finishing the 1000 iterations of LabelValues calls and proceeding to the test cleanup. I was able to trigger it on the main branch (69edd8709ba7d4b2152eab5fb208a3d74b4a81e1) with this diff

```diff
diff --git a/tsdb/querier_test.go b/tsdb/querier_test.go
index 2fcdbf7c4..a615c5fd1 100644
--- a/tsdb/querier_test.go
+++ b/tsdb/querier_test.go
@@ -2249,7 +2249,9 @@ func TestQuerierIndexQueriesRace(t *testing.T) {

 func appendSeries(t *testing.T, ctx context.Context, wg *sync.WaitGroup, h *Head) {
        defer wg.Done()
-
+       if ctx.Err() != nil {
+               t.Fatal("context canceled before appendSeries can start")
+       }
        for i := 0; ctx.Err() != nil; i++ {
                app := h.Appender(context.Background())
                _, err := app.Append(0, labels.FromStrings(labels.MetricName, "metric", "seq", strconv.Itoa(i), "always_0", "0"), 0, 0)
```

And just run the test a lot of times. I suppose the resources in CI are more constrained, so this race condition is more prone to happening.

```shell
go test -count=1000 -run=TestQuerierIndexQueriesRace ./...
```
```
?   	github.com/prometheus/prometheus/tsdb/encoding	[no test files]
?   	github.com/prometheus/prometheus/tsdb/errors	[no test files]
--- FAIL: TestQuerierIndexQueriesRace (0.03s)
    --- FAIL: TestQuerierIndexQueriesRace/[always_0!="0"___name__="metric"] (0.02s)
        querier_test.go:2253: context canceled before appendSeries can start
FAIL
FAIL	github.com/prometheus/prometheus/tsdb	37.772s
ok  	github.com/prometheus/prometheus/tsdb/agent	0.041s [no tests to run]
ok  	github.com/prometheus/prometheus/tsdb/chunkenc	0.005s [no tests to run]
ok  	github.com/prometheus/prometheus/tsdb/chunks	0.012s [no tests to run]
ok  	github.com/prometheus/prometheus/tsdb/fileutil	0.010s [no tests to run]
ok  	github.com/prometheus/prometheus/tsdb/goversion	0.005s [no tests to run]
ok  	github.com/prometheus/prometheus/tsdb/index	0.017s [no tests to run]
ok  	github.com/prometheus/prometheus/tsdb/record	0.008s [no tests to run]
ok  	github.com/prometheus/prometheus/tsdb/tombstones	0.014s [no tests to run]
ok  	github.com/prometheus/prometheus/tsdb/tsdbutil	0.007s [no tests to run]
ok  	github.com/prometheus/prometheus/tsdb/wlog	0.011s [no tests to run]
FAIL
``` 


This also implies that the test itself is also a noop sometimes, but I'm not sure how solvable that is, since we will always have delay in synchronising two goroutines.

**Comment by bboreham** [comment]
OK, that makes sense, so in the one case where it's supposed to exit immediately it actually hangs forever.

The fact that this happened on lots of CI runs suggests the test is mostly a no-op.
Is it worth putting another 1ms sleep inbetween the queries so there is more chance both goroutines run?

**Comment by dimitarvdimitrov** [comment]
> Is it worth putting another 1ms sleep inbetween the queries so there is more chance both goroutines run?

I opened https://github.com/prometheus/prometheus/pull/12881 to make the test more sensitive
