### ISSUE TITLE
negative values with irate

### ISSUE THREAD

**Issue by f0** [prometheus/prometheus#1287]
Hi,

i use  this query to get the cpu utilisation  (from http://www.robustperception.io/understanding-machine-cpu-usage/ )
```
100 - (avg by (instance) (irate(node_cpu{cluster="test",mode="idle"}[5m])) * 100)
```
with this query i got negative values in my graphs  
![negative_values](https://cloud.githubusercontent.com/assets/1117435/12139333/15d6f054-b460-11e5-8503-97f334d609d9.png)

if i change irate to rate , the negative values are gone

the metric source is a node_exporter

i think negative values should never happen with cpu usage....

**Comment by brian-brazil** [comment]
You've got a subtraction in there, so it's not the irate that's going negative. Can you share the raw values and timestamps around the artifact?

**Comment by f0** [comment]
@brian-brazil  sure, whats the best way to do this?

**Comment by brian-brazil** [comment]
`node_cpu{cluster="test",mode="idle"}[5m]` for the time period in question.

**Comment by f0** [comment]
@brian-brazil 
![negative-values-1](https://cloud.githubusercontent.com/assets/1117435/12139753/cdf4754c-b462-11e5-94d7-0727d138ecb0.png)

i also try to get the values from the api

**Comment by f0** [comment]
@brian-brazil  here are the api responce for the specific time frame

**Comment by brian-brazil** [comment]
There's something very odd in the data (all values exactly 10s apart):
```
5595210.02
5595224.21  + 1.4/s
5595238.4    + 1.4/s
5595238.4    + 0/s
```

Somehow every 3rd scrape is getting the same value, and it's increase is in the first two of the triplet.

Are you using a node exporter that includes https://github.com/prometheus/node_exporter/pull/177 ?

Why do some of the results not have an instance label?

**Comment by f0** [comment]
@brian-brazil  i removed the instance label (policy...), no this commit is not included i use the last released version 0.12.0rc1

**Comment by brian-brazil** [comment]
> I removed the instance label

That's bad practice, a given metric should all have the same label and may be causing some of your problems.

> i used step=10s in the api call

Ah, please use the `query` endpoint as we want the raw data.

**Comment by f0** [comment]
i only removed the instance label in the provided data.

hm if i do a query against the query endpoint, how can i specify a timeframe?

**Comment by f0** [comment]
ok here are the values with the query endpoint for the specific time, this time i do not removed any labels
[raw_data2.zip](https://github.com/prometheus/prometheus/files/79702/raw_data2.zip)

**Comment by brian-brazil** [comment]
I need `node_cpu{cluster="test",mode="idle"}[5m]`, you seem to have given me `node_cpu{cluster="test",mode="idle"}`

**Comment by f0** [comment]
[raw_data3.zip](https://github.com/prometheus/prometheus/files/79715/raw_data3.zip)
sorry, here is with [5m]

**Comment by brian-brazil** [comment]
Can you give me the same, but a minute later? I want to get some data points after the problem.

`scrape_duration_seconds` for the node exporters around that time would also help.

**Comment by f0** [comment]
[raw_data3+1m.zip](https://github.com/prometheus/prometheus/files/79727/raw_data3.1m.zip)

[raw_data_scrape.zip](https://github.com/prometheus/prometheus/files/79733/raw_data_scrape.zip)

**Comment by brian-brazil** [comment]
I think what happened was that your Prometheus server got paused or overloaded for ~5s, and that messed up the timestamps.

**Comment by f0** [comment]
@brian-brazil ok if this happend , is the impact correct? I mean are negative values the correct answer for this?

**Comment by brian-brazil** [comment]
The data that we ended up with was that there was 19s of idle time in 15s, so a negative answer is what comes out. There's always race conditions that can cause oddness (there's a few smaller ones in your data too), when things get overloaded there's not much we can do I'm afraid.

**Comment by f0** [comment]
hm i do not thin the prometheus system (rkt container) was overloaded,  the cpu usage was 10%  and more than 50GB Memory are free, not much disk activity in this timeframe

**Comment by grobie** [comment]
Can you check the prometheus server logs? Also what were the results of the `up` timeseries for that job? Maybe prometheus wasn't able to scrape the targets?

**Comment by brian-brazil** [comment]
The timestamp consistency indicates that there were no scrape failures.
