### ISSUE TITLE
Consider removing support for deprecated k8s APIs in service discovery

### ISSUE THREAD

**Issue by mickael-carl** [prometheus/prometheus#12884]
### Proposal

Prometheus currently supports discovering the following roles with deprecated APIs:
* `discovery.k8s.io/v1beta1` of EndpointSlice, [no longer served as of k8s 1.25](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#endpointslice-v125)
* `networking.k8s.io/v1beta1` of Ingress, [no longer served as of k8s 1.22](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#ingress-v122)

Considering that k8s 1.22 is End of Life since 2022-12-08 and k8s 1.25 will be on 2023-10-28, it might be worth considering removing support for those, which will simplify the maintenance of the discovery code.
I haven't been able to find a policy that describes the supported k8s versions in Prometheus, would that also be something worth clarifying in the process?

**Comment by roidelapluie** [comment]
I do not think it costs us a lot to maintain the code, and when new deprecations will come we might to rewite the code to handle them again. for me it's a no-cost to keep them as far as I see it.

**Comment by mickael-carl** [comment]
It's actually making contributions in that area trickier. Take for example #12338: it took me some time to figure out why the code is the way it is in the first place (I hadn't looked at the SD bits ever before), and then fix each test twice. Similarly, any change to ingress/endpointslices data lookup will need to be duplicated.
Worth noting that the API is not just deprecated though: it's just gone from supported versions of k8s.

Re: deprecations: the ones that this issues refers to were not GA and as such the stability guarantees around them weren't very strong. `networking.k8s.io/v1` Ingresses are GA for instance, and so them going away anytime soon is extremely unlikely. From the [deprecation policy](https://kubernetes.io/docs/reference/using-api/deprecation-policy/):
> There are no current plans for a major version revision of Kubernetes that removes GA APIs.

**Comment by roidelapluie** [comment]
Okay, I understand better your feedback and it's important to us. I will
carry this issue to the proper maintainer.

Le mar. 26 sept. 2023, 19:15, Mickaël Carl ***@***.***> a
écrit :

**Comment by brancz** [comment]
Even though I wholeheartedly agree with you @mickael-carl, I unfortunately know lots of companies that are using versions as old as 1.20 fully supported by the respective provider, so if we break that compatibility we'll force them to be stranded on old Prometheus versions. I don't like it myself either, but I think for Prometheus it would be best to keep this support for another year or two.

**Comment by mickael-carl** [comment]
Well, the nice thing is that this wouldn't break 1.20 compatibility, only some APIs that were already marked as deprecated at that time. The only thing that would be broken would be folks still using the v1beta1 version of ingresses and that's a pretty easy thing to fix right?

**Comment by brancz** [comment]
I see what you mean. What would the actual compatibility be then? As in the first version that serves the v1 APIs?

**Comment by mickael-carl** [comment]
Ingress v1 has been available since k8s 1.19, which has deprecated the v1beta1 API as well, from the changelog:
> `Ingress` and `IngressClass` resources have graduated to `networking.k8s.io/v1`. Ingress and IngressClass types in the `extensions/v1beta1` and `networking.k8s.io/v1beta1` API versions are deprecated and will no longer be served in 1.22+. Persisted objects can be accessed via the `networking.k8s.io/v1` API.

**Comment by brancz** [comment]
hmm .. I'm inclined to agree with you, but what do you think of running a Twitter and Mastodon poll to gauge an indication of versions used?

**Comment by mickael-carl** [comment]
@brancz while I wouldn't mind sending out such a survey, I actually wouldn't be able to, not having an account on any of those platforms 🙂 Additionally and fwiw (just to try and make my case a bit further), 1.29 just came out marking 10+ versions in a row for the availability of ingress v1, and the deprecation of ingress v1beta1. Similarly, it's now been 9 releases that EndpointSlice v1beta1 is deprecated.

**Comment by simonpasquier** [comment]
Adding the "Prometheus 3.0" milestone since it could make sense for a new major version to drop deprecated APIs?

**Comment by beorn7** [comment]
We discussed this at the dev summit today. There weren't many attendees, so take this with a grain of salt, but the general consensus was to drop the deprecated API with v3.

If anyone has issues with that, please comment here.

**Comment by simonpasquier** [comment]
The change has been merged in the release-3.0 branch.
