### ISSUE TITLE
Expose --storage.tsdb.retention.time in a metric

### ISSUE THREAD

**Issue by nemobis** [prometheus/prometheus#12925]
### Proposal

As I have many Prometheus instances with different retention settings defined different repositories, I'd love to have a dashboard where to combine them all with a Prometheus query.

I can find the metrics `prometheus_tsdb_retention_limit_bytes` for `--storage.tsdb.retention.size` (clear enough) as well as `prometheus_tsdb_size_retentions_total` and `prometheus_tsdb_time_retentions_total` (no idea what these are) but I don't find a metric reflecting the `--storage.tsdb.retention.time` setting (I've not tried `--storage.tsdb.retention` as I don't use it and I understand it's [deprecated](https://prometheus.io/docs/prometheus/latest/command-line/prometheus/) since [a while ago](https://www.robustperception.io/configuring-prometheus-storage-retention/)).

So, would it be possible to add a metric like `prometheus_tsdb_retention_time_limit_days` or something, with an appropriate conversion from `--storage.tsdb.retention.time` units?

**Comment by msscaroso** [comment]
Hey! 👋 Is it something the project/community would be interested in? If so, I can open a PR and hash out the details there.

I believe it should be something in this direction. https://github.com/prometheus/prometheus/commit/89449ce5e7fba6a37448e82c58918f72adaec694
(just a draft. still need to think of which unit & metric name to use) I'd love to give a try!

**Comment by msscaroso** [comment]
Hi there @beorn7  :wave: (hopefully I'm tagging the right person, but lmk if not)

Is this issue something the project/community would be interested in?
If yes, I'll continue & work in a PR :runner:

**Comment by bwplotka** [comment]
Thanks for this idea! I think it's worth accepting, contributions are welcome 🤗 

Perhaps `prometheus_tsdb_retention_seconds` - concise and in base units as our [metric name style guide](prometheus_tsdb_retention_time_limit_days) recommends.

(Triaged during Prometheus bug scrub meeting)

**Comment by machine424** [comment]
Maybe we can close this as implemented

**Comment by nemobis** [comment]
Indeed. Thanks everyone!
