### ISSUE TITLE
Failed reloads are not exposed through web API

### ISSUE THREAD

**Issue by RichiH** [prometheus/prometheus#1292]
I reloaded via the web API and got:

    foo@bar ~ % curl -X POST http://localhost:9090/-/reload
    Reloading configuration file...%
    foo@bar ~ %

While I saw an actual error on CLI:

        INFO[842745] Loading configuration file prometheus.yml     source=main.go:196
        ERRO[842745] Couldn't load configuration (-config.file=prometheus.yml): yaml: unmarshal errors:
      line 362: cannot unmarshal !!map into string  source=main.go:208

Exposing the error via the web API would help quite a bit.

**Comment by brian-brazil** [comment]
Dupe of #1425
