### ISSUE TITLE
promql: numerical comparison of label values

### ISSUE THREAD

**Issue by beorn7** [prometheus/prometheus#12934]
### Proposal

I'm not sure if the following is a good idea, but since we (inconclusively) discussed it at the dev summit, I thought I put it in here so that at least we don't forget and can come to an informed decision later.

I also have a vague feeling that this was proposed earlier, but I couldn't find any reference to it.

## Problem

Sometimes label values (which are always strings in Prometheus) happen to contain numbers. That's generally not a good idea, but sometimes it just happens. And most prominently, this case features in classic histograms (with the values of the `le` labels) and in summaries (with the values of the `quantile` labels).

Now there are many ways of writing the same number, for example `.1`, `0.1`, `0.10`, `+0.1', `1e-1` are all representing the same number while not passing as equal when doing label matching in PromQL. OpenMetrics took a stab at unifying the formatting, but there are still two problems left:
1. In practice, there will always be non-compliant metrics producers, because – depending on your tool chain – generating the “right” formatting might be quite cumbersome and not-obvious (e.g. in Go).
1. There are numbers where the common formatting algorithms just don't come up with a reproducible answer. A formatting algorithm is mostly concerned with creating the shortest sequence of digits that recreates the exact same IEEE 754 float representation when parsed. There can be up to nine different sequences all fulfilling this requirement, and while I can imagine an algorithm that reproducibly picks one out of those, it would probably be quite expensive, and more importantly, most languages won't have an implementation ready.

Furthermore, once you have to deal with numbers in label values, you might want to do comparisons like "greater than".

## Proposal

We could introduce new label matching operators that act based on parsed float values. They could look like:
* `{foo=="1.234"}`: numerical equality
* `{foo!=="1.234"}`: numerical inequality
* `{foo<="1.234"}`: numerically less than or equal
* `{foo>="1.234"}`: numerically greater than or equal
* `{foo<"1.234"}`: numerically less than
* `{foo>"1.234"}`: numerically greater than

If a label value doesn't parse as a float number, the matcher would not match (and maybe we can issue a warning via the new warning framework in PromQL).

## Concerns

- This is a lot of new syntax for a niche use case.
- And it won't even end there because one might argue we should then also be able to do aggregation based on the numerical label value (do a `sum by (le)` where all numerically equal `le` labels end up in one resulting entry).

### Normalization on ingestion

Prometheus 1.x normalized the values of the `le` and `quantile` labels of (classic) histograms and summaries, respectively, i.e. it parsed them as floats and then reformatted them into strings before storing them into the TSDB.

This is happening again in Prometheus 2.x if you activate native histograms because then you will also resurrect protobuf  scraping, which represents those values as actual float values anyway.

At the recent dev-summit, we reached the consensus that we want to let Prometheus normalize those two label values always (again), which would then implement [an earlier proposal of mine](https://github.com/OpenObservability/OpenMetrics/issues/129) that got rejected by OpenMetrics.

This however doesn't fully solve the problem because it would not affect labels beyond the `le` and `quantile` labels. Plus there is still a small chance that some numbers could be formatted differently (if you change the Go version or the hardware platform or something).

### First class numerical label value

We could introduce a type dimension to label values, allowing label values that are actually numbers. This would be the cleanest approach, but also a very involved one. It would work against the pragmatic simplicity of Prometheus and PromQL (all sample values are floats, all label values are strings).

**Comment by shwethabm** [comment]
Can I work on this issue?

**Comment by beorn7** [comment]
We should first make a call if we want this feature. I'm torn myself, and I would love feedback from others.

**Comment by roidelapluie** [comment]
I would rather have a relabeling action to normalize numbers in labels than touching PromQL. I think this is also how we should do 'Normalization on ingestion'.

**Comment by beorn7** [comment]
A normalization relabel action sounds good to me. It would help normalize labels that are not `le` or `quantile` in a histogram or summary, respectively. However, it would still not solve the case which certain (non-round) numbers where normalization could still lead to varying results, and it would not allow "greater than" comparison etc. (I'm not saying that we _have_ to support those cases, just wanted to clarify what part of the problem space are solved by a normalization relabeling action.)

**Comment by krajorama** [comment]
A practical use case and unit test suggestion for the bucket "le" labels:

When we turn on native histograms feature, every classic histogram "le" label changes value where the number was a whole number. So if `le="10"` before, now it's `le="10.0"`.  This is a problem for alerts, especially on RED metrics, since the `increase/rate/irate` functions don't produce correct values anymore. 

Case in point, you can add this test:
```
# Text to OpenMetrics transition test
# Test histogram where half the samples are bellow 2.0 the other half is over.
# Thus quantile of 0.5 should be 2.0.
load 5m
	text2om_bucket{le="2"}	  0+1x5 _x5
	text2om_bucket{le="2.0"}  _ _x5 6+1x5
	text2om_bucket{le="4"}    0+2x5 _x5
	text2om_bucket{le="4.0"}  _ _x5 12+2x5
	text2om_bucket{le="+Inf"} 0+2x10

eval instant at 32m histogram_quantile(0.5, sum by (le) (increase(text2om_bucket[10m])))
	{} 2
```
But it fails:
```
error in eval histogram_quantile(0.5, sum by (le) (increase(text2om_bucket[10m]))) (line 262): expected 2 for {} but got NaN
```

Since increase will not see two samples for the buckets in the given time range. It's even worse if it does see values, because the old buckets will be seen to decrease (to 0).

The overall effect is that the user might get some false positive alerts or possible miss some alerts.

**Comment by beorn7** [comment]
The new label matchers proposed here are actually not really helping with @krajorama 's use case. If you `rate` a range vector, the differently formatted `le` labels will really bite you, and the new label matchers don't help with that. That goes into the direction of the aggregation issue already mentioned above. 

It amplifies the concerns I'm having anyway. So maybe we should focus indeed on making normalization configurable on scrape, which goes more into the direction of the relabel action @roidelapluie proposed. I'll try to write something up soon.

**Comment by beorn7** [comment]
OK, see #12984 .

**Comment by beorn7** [comment]
Thanks for all your feedback.

To come to some kind of preliminary conclusion:

The equality use case isn't really covered completely with the proposed "numerical equality label matcher" (`{foo=="1.234"}`). Series identity is wired much more deeply into PromQL, applying to the following aspects (and possibly more):
* Aggregation: Something like `sum by (foo)` would also need a mode where it aggregates numerically equal labels into the same resulting time series. We could even come up with a syntax for this (`sum by (foo==)` or something), but we are getting deeper down the rabbit hole here.
* Range selectors: `{foo=="1.234"}[5m]` would select by numerical equality, but functions consuming this range selector needed to be made aware of that, because the selected series would still look differently. Or the range selector needed to rewrite the different label values into one canonical form. While I could imagine this is a solvable problem, it is quite involved.

In sum, I think the equality issue is better solved with normalization upon ingestion, as proposed above. See also #12984 for more thoughts about it. It is essentially one know to turn, instead of a whole bunch of relatively complex additions and changes of PromQL as proposed in this issue. It should be noted, however, that the normalization upon ingestion might still run into the possible ambiguity in the case of many decimal places. The doesn't happen in practice with `quantile` labels because they are usually set manually with a limited number of decimal places (e.g. `0.5`, `0.999`) where the issue doesn't happen. With `le`, it could most plausibly happen with automatically set exponential bucket boundaries. But those are prime use cases for native histograms, where we don't have `le` labels anymore. Which leaves us with the niche case of numerical label values used for other (user-specific) reasons beyond `le` and `quantile` in histograms/summaries.

This proposal also contains a solution for "greater than"/"less than" comparison. The question is how often this is needed in practice.

Overall, this proposal is possibly an appropriate solution for rarely occurring niche cases (numerical label values with many decimal places on the one hand, and comparisons beyond simple equality on the other hand). My conclusion for now is that the limited scope of those niche use cases cannot justify the amount of complexity that comes with this proposal. Therefore, I close the issue, but we have it "on file" now and can revisit if we change our mind.
