### ISSUE TITLE
Error if target-group is empty

### ISSUE THREAD

**Issue by macetw** [prometheus/prometheus#12948]
### Proposal

I am trying to diagnose at what level my problem is, my ServiceMonitor is not finding any of the target endpoints I have defined to it. But there's no error in the logs. In the list of scrape pools, I can find my service monitor, but when I select it, I can't see any targets.

Why that is happening, I can't tell. But I'd like more diagnostic data from Prometheus, that there were no endpoints found (or some other problem).

In this code somewhere, it's missing a check for if a scrape-pool is empty.
https://github.com/prometheus/prometheus/blob/a5a4eab679ccf2d432ab34b5143ef9e1c6482839/scrape/manager.go#L211
The code should notice it and print a helpful diagnostic (however helpful it can be) for the problem pool.

**Comment by macetw** [comment]
... Or here. If all targets are dropped, give us helpful information.
https://github.com/prometheus/prometheus/blob/a5a4eab679ccf2d432ab34b5143ef9e1c6482839/scrape/scrape.go#L535C1-L536C1

**Comment by roidelapluie** [comment]
What story does the service discovery page tell?

**Comment by machine424** [comment]
`promtool check service-discovery` to manually re-trigger the discovery, can be helpful.
Also you can check metrics like `prometheus_sd_discovered_targets` or per SD mechanism metrics to see where the targets are disappearing, if any.

Unfortunately, with more details, we cannot help.

**Comment by beorn7** [comment]
Hello from the bug scrub!

With no more info provided, we are closing this. However, more info is still welcome. Just follow up here and we'll re-open.
