### ISSUE TITLE
use Go standard errors package

### ISSUE THREAD

**Issue by mmorel-35** [prometheus/prometheus#12960]
### Proposal

* Since Dec 1, 2021, `github.com/pkg/errors` is an archived project.
* Since go 1.13, there is a standard `errors` and `fmt` modules that provides equivalent ways to handle errors.

The subtlety I have yet identified is that  `github.com/pkg/errors`.Wrap or Wrapf are returning nil when the provided argument error is nil while fmt.Errorf doesn't. So the error needs to be checked for nullity first.
As it can be a huge merge request if we do it on the whole project, I have created several merge request to fix it by package.

I started by just applying errorlint. When this is done, then the gomodguard can be used to ensure that `github.com/pkg/errors` is not used and replaced by  `errors` and `fmt`.

Closes #12615

**Comment by mmorel-35** [comment]
Hi @bboreham ,

I have created this issue to gather the different merge requests I created and detail the intention of them.
What kind of title would be more appropriate ?

**Comment by bwplotka** [comment]
Thanks! Looks fair to me.

**Comment by bboreham** [comment]
> What kind of title would be more appropriate ?

For example, for #12923 I would suggest "scrape: use Go standard errors package".
For me the change to linting is subordinate to the change in behaviour.

**Comment by mmorel-35** [comment]
Once those 5 last pr are merged It shall be possible to entirely remove github.com/pkg/errors as direct dependency.
