### ISSUE TITLE
Index symbols lookup spent too much CPU on ctx check

### ISSUE THREAD

**Issue by yeya24** [prometheus/prometheus#12983]
### What did you do?

<img width="663" alt="image" src="https://github.com/prometheus/prometheus/assets/25150124/9e42bda3-264c-478c-8526-93dac349a602">

I am running Cortex with latest version of Prometheus. `index.Symbols.Lookup` function took 7% CPU time on profile but about 4% CPU time was spent on checking context. The check seems too fine grained.

### What did you expect to see?

I expect context check should take a very small portion of CPU time.

### What did you see instead? Under which circumstances?

.

**Comment by bboreham** [comment]
@aknuds1 I think you added this at https://github.com/prometheus/prometheus/pull/12666/files#diff-fb0f63e7d2d24fa7aa1c18b2619b10a07c821b38f45c2351458b00edef63f995R1310

**Comment by aknuds1** [comment]
Thanks for the heads up @bboreham - I guess evidence points towards dropping that check?
