### ISSUE TITLE
Parse Created timestamps from OpenMetrics text format

### ISSUE THREAD

**Issue by ArthurSens** [prometheus/prometheus#12980]
### Proposal

In #12936, we added created timestamps to Prometheus proto inspired by the semantics used by OpenMetrics proto; in #12973, we added the ability to parse this same information. Just like OpenMetrics proto, OpenMetrics text already exposes Created Timestamps, but the way Prometheus interprets it is very different from how we wanted it to.

Following our recently accepted proposal (https://github.com/prometheus/proposals/pull/29), we want to change how Prometheus parses created timestamps from OpenMetrics text. 

This task is about implementing the `CreatedTimestamp()` function in openmetricsparse that was added in #12973 following what was [proposed](https://github.com/prometheus/proposals/blob/main/proposals/2023-06-13_created-timestamp.md#openmetrics-text).

It should also be implemented behind the [feature flag `created-timestamp-ingestion`](https://github.com/prometheus/proposals/blob/main/proposals/2023-06-13_created-timestamp.md#feature-flag)

**Comment by bboreham** [comment]
Part of #6541

**Comment by bwplotka** [comment]
Fixed in https://github.com/prometheus/prometheus/pull/14356
