### ISSUE TITLE
Add template function for converting string to PromQL string literal.

### ISSUE THREAD

**Issue by manueljacob** [prometheus/prometheus#13013]
### Proposal

Within templates, it is possible to run PromQL queries with the `query` template function. In some cases, it is useful to insert a string literal representing a string known at template evaluation time.

### Example

So far I’ve used the template `'{{ printf "kubelet_volume_stats_available_bytes{namespace=\"%s\",persistentvolumeclaim=\"%s\"}" $labels.namespace $labels.persistentvolumeclaim | query | first | value | humanize1024 }}B'`, which is unsafe. Instead, I’d like to write something like `'{{ printf "kubelet_volume_stats_available_bytes{namespace=%s,persistentvolumeclaim=%s}" (promQlStringLiteral $labels.namespace) (promQlStringLiteral $labels.persistentvolumeclaim) | query | first | value | humanize1024 }}B'`.

**Comment by AniketNS** [comment]
Hey @manueljacob, I'd like to work on this issue. Can you help me doing that?

**Comment by roidelapluie** [comment]
I think using %q instead of %s would be safe and simpler.

**Comment by manueljacob** [comment]
> I think using %q instead of %s would be safe and simpler.

Good point. Since PromQL uses the same rules for string literals as Go, it should work perfectly unless I missed something.
