### ISSUE TITLE
Uptime Prometheus

### ISSUE THREAD

**Issue by Ncarel** [prometheus/prometheus#1309]
Hello!
When I start Prometheus, the Uptime value is equal to my system date - 1H.
Prometheus save date with a date that not the same with my system.
Please a solution?

**Comment by brian-brazil** [comment]
Prometheus uses UTC, I'm guessing your in a timezone that's UTC+1 or UTC-1?

**Comment by Ncarel** [comment]
UTC+1
Thanks!
