### ISSUE TITLE
Memory growth after restart for 1-2 days, then flattens out

### ISSUE THREAD

**Issue by wiardvanrij** [prometheus/prometheus#13154]
### What did you do?

On our sandbox/playground, we are testing and tuning Prometheus. 
See our memory stats over the last 30 days:
<img width="1716" alt="image" src="https://github.com/prometheus/prometheus/assets/5786097/541606e0-457b-4439-b6a0-62545ab6153f">

As you can see, we had some restarts. Either manually or due to a heavy memory spike (which is somewhat irrelevant to this issue). What I find interesting is that it takes about 1-2 days before the memory becomes "stable". 

I personally cannot relate this to either our retention or whatsoever. We use a PVC so it's not that after a reload, there is fewer data. 

### What did you expect to see?

I would expect memory to be 'stable' or at the very least not keep increasing for a day or two before eventually sort of flattening out. This is especially hard to deal with since we are tuning/tweaking Prometheus and basically it now requires a longer time to see the actual 'real' impact of our changes. 

### What did you see instead? Under which circumstances?

As already described.

I did gather profiles and this is a diff over time: https://flamegraph.com/share/d1bbae2a-847c-11ee-b135-0a855ce7b751

### System information

K8s

### Prometheus version

```text
v2.47.1
```

**Comment by eero-t** [comment]
Is metrics database cleared between restarts, so that there's less data at the beginning?

**Comment by wiardvanrij** [comment]
No, I'm using PVCs and also memory snapshot

**Comment by wiardvanrij** [comment]
Unable to reproduce anymore and isn't happening as well.
