### ISSUE TITLE
Add label to every metric in cluster, while using serviceMonitors. 

### ISSUE THREAD

**Issue by BenCoughlan15** [prometheus/prometheus#13165]
### Proposal

Hey, I'm currently using the prometheus operator, and kube-prometheus-stack chart. 

I currently have about 120 serviceMonitors in each cluster, and 12 clusters. 

I then port all the metrics from those clusters to a central _global_ mimir cluster. 

I currently use the **externalLabel** parameter to add the **cluster-id** label to all the metrics, and this works fine. 

However, in Grafana I now have "global" dashboards, that are aware of the **cluster-id** label, and regional ones that don't carry the **cluster-id** label. 

I'd rather just have one dashboard for both Global, and Regional, as it's a lot less to maintain. 
 
So my choices are: 

1: Update every serviceMonitor, across the whole estate, which means bumping a lot of helm charts, which is a lot of work. 
2: Maintain two types of dashboard. 

I guess, my question is:
Is there any way to have a global setting to add a label to all metrics? I've searched everywhere, and can't seem to find it. 

If not, then would it make sense to have that added as a feature?

**Comment by machine424** [comment]
Have you tried taking advantage of `metric{foo="bar", doesnotexist=~".*"}≡metric{foo="bar"}`?

Make the default value of `cluster-id` equal to `.*`

**Comment by ArthurSens** [comment]
This feature has been merged(https://github.com/prometheus-operator/prometheus-operator/pull/6379) and it's being released tomorrow. Try it out and let us know if it solves your problem!

For prometheus-operator related issues, please open in our repository :)
https://github.com/prometheus-operator/prometheus-operator/issues/new/choose
