### ISSUE TITLE
Improve efficiency of histogram decoding

### ISSUE THREAD

**Issue by fpetkovski** [prometheus/prometheus#13161]
### Proposal

The histogram decoder allocates a new object each time `AtHistogram` or `AtFloatHistogram` is called, and this takes a significant amount of CPU when executing queries. Furthermore, calling `ToFloat` on a regular histogram also creates a new object and there is no good way to reuse memory during the execution of a query.

I've put together a quick benchmark to illustrate this problem: https://github.com/prometheus/prometheus/pull/13160. Note that even though the tooltip says 4.6% of all, that also includes the time required to set up the benchmark. The `ToFloat` call actually takes around 30-40% of the query execution time.

<img width="1044" alt="image" src="https://github.com/prometheus/prometheus/assets/1286231/42f46347-88ae-4e73-804c-cbab0cacb73d">

I think this optimization is worth pursuing because it would lead to significant performance improvements for queries on native histograms. One solution could be to apply the same pattern that is used in `SampleIterable` where the caller can provide an existing histogram object that can be reused. If `nil` is provided, the decoder would allocate a new object.

**Comment by beorn7** [comment]
As per direct communication, @fpetkovski will work on this.

**Comment by yeya24** [comment]
Is it fixed by https://github.com/prometheus/prometheus/pull/13340 and https://github.com/prometheus/prometheus/pull/13215?

**Comment by fpetkovski** [comment]
Most of the improvements are covered by those two PRs and I don't see other low effort work for now.

**Comment by beorn7** [comment]
OK, I'll close this then.

More optimizations can always be done, even if no issue prompts for it. :smile:
