### ISSUE TITLE
Native Histograms doesn't work with 'Info' type

### ISSUE THREAD

**Issue by defenestration** [prometheus/prometheus#13172]
### What did you do?

native-histograms breaks targets with info metric types from being scraped.

It seems prometheus will process 'info' types as a gauge without this flag, though promtool will report errors on it. 

i noticed this working with flux2, kube-prometheus-stack and kube-state-metrics in this issue. https://github.com/fluxcd/flux2-monitoring-example/issues/14 

Flux uses kube-state-metrics' custom resource definitions now but in their reference spec use 'info' types for those metrics. 
  This works, until native-histograms is enabled on prometheus. 

### What did you expect to see?

Matching behavior when the `native-histograms` feature is not used.

### What did you see instead? Under which circumstances?

This is the error i saw on teh promehteus targets page for kube-state-metrics. it prevents the kube-state-metrics target from being scraped.

`err="invalid metric type \"info\"`

### Prometheus version

```text
image used: quay.io/prometheus/prometheus:v2.47.2
```

### Logs

```text
ts=2023-11-21T18:29:00.017Z caller=scrape.go:1399 level=debug component="scrape manager" scrape_pool=serviceMonitor/monitoring/kube-prometheus-stack-kube-state-metrics/0 target=http://10.42.0.118:8080/metrics msg="Append failed" err="invalid metric type \"info\""
```
```

**Comment by defenestration** [comment]
Seems to be a similar problem with the 'stateSet' type in kube-state-metrics.  Wondering if this should be an issue on the kube-state-metrics end possibly?

**Comment by dgrisonnet** [comment]
OpenMetrics doesn't support native histograms yet: https://github.com/prometheus/prometheus/issues/11265

**Comment by dgrisonnet** [comment]
That said, I don't know how kube-state-metrics ended up negotiating probutuf since it is the only format we don't support and it should've negociated for OpenMetrics instead which shouldn't have caused the issue you are faicing: https://github.com/kubernetes/kube-state-metrics/blob/240cffd908220854a27f7e92d8157eaee4dc8d42/pkg/metricshandler/metrics_handler.go#L189-L225.

**Comment by beorn7** [comment]
Interesting… :)

so yeah, I guess that's what happened: KSM negotiated protobuf, although it doesn't support it. Then it still sent OM. Prometheus, expecting protobuf, got confused and fell back to classic prometheus text format, which looks similar to OM, but doesn't have an "info" type (plus some more subtle differences).

This makes me wonder if it is a good behavior to fall back to the classic text format if the sent data looks invalid… But changing that now would be a breaking change. Maybe something to consider for 3.x...
