### ISSUE TITLE
Build fails due to ui.AssetInfo

### ISSUE THREAD

**Issue by samdroid-apps** [prometheus/prometheus#1317]
When running `make` (on fedora 24 rawhide) or `make docker` the build appears to fails.

Output from `make docker`:

```
>> building binaries
 >   prometheus
# github.com/prometheus/prometheus/web       
web/web.go:204: undefined: ui.AssetInfo
Makefile:41: recipe for target 'build' failed 
```

Or similar output from `make`:

```
>> writing assets
>> formatting code
web/ui/bindata.go
>> building binaries
 >   prometheus
# github.com/prometheus/prometheus/web
web/web.go:204: undefined: ui.AssetInfo
Makefile:41: recipe for target 'build' failed
make: *** [build] Error 2
```

Setting `DEBUG=1` does not affect anything either.

**Comment by beorn7** [comment]
Can't comment on the Docker part, but with a clean checkout in an otherwise completely empty GOPATH, I cannot reproduce the problem.

Are you building from head?
Which Go version?

**Comment by samdroid-apps** [comment]
Yes, I am building from HEAD.

I am running `go version go1.5.3 linux/amd64` (from the package `golang-1.5.3-1.fc24.x86_64`).  Maybe it is an issue with a package on my system.  I will wait and check later after updating.

**Comment by beorn7** [comment]
All dependencies should be vendored, and the Makefile sets GO15VENDOREXPERIMENT=1.

Could you do a new clean clone from git and retry?

**Comment by samdroid-apps** [comment]
Hum, I tested in a Ubuntu-15.something VM, and it worked fine.  But I did something differently - I didn't ran "make build" instead of "make assets"

Testing back on fc24 with a clean gopath, the same could be repoduced.  Running "make build" works.  However, running "make" (which includes format and assets) did not

**Comment by beorn7** [comment]
So pretty clearly, you asset build doesn't work. It uses a tool not vendored, github.com/jteeuwen/go-bindata. so `make assets` go-get's `go-bindata` from the source and compiles it, to then create `web/ui/bindata.go`. Something in that chain fails for you, and then `bindata.go` is somehow malformed (possibly empty), which then makes the compile fail.

Luckily, you only have to generate `wob/ui/bindata.go` if any of the assets have changed, so if you only ever run `make build`, everything should be OK. (Which is probably the rationale why we didn't bundle the `go-bindata` tool). We might also remove it from the default make target, cf. https://github.com/prometheus/prometheus/issues/1326 ). @fabxc knows more about it (as he did things differently for `prometheus/alertmanager`).

Which leaves as an exercise for the reader why the `go-bindata` part fails for you. For me, it runs completely smoothly. Perhaps, you have no access to the internet, and therefore the `go get` fails?
