### ISSUE TITLE
Prometheus server not stopped by closing the terminal session

### ISSUE THREAD

**Issue by Ricky-Tigg** [prometheus/prometheus#13183]
### What did you do?

While the present repository is the source of acquisition of the _Prometheus_ and _node_exporter_ program codes, related documentation's instructions at prometheus.io for starting them exist. However the documentation lacks instructions that cover the practises for stopping them.

By experience, I learned that closing each terminal session in which these applications were started does end up the process that is attached to _node_exporter_ but not the one that is attached to _Prometheus_, which is as sub-process of `/usr/lib/systemd/systemd --user`.

### What did you expect to see?

- Closing the terminal session in which the _Prometheus_ server was started to end up the process that is attached to it.
-  Documentation that includes the instruction for stopping at least the _Prometheus_ server.

### System information

Linux 6.6.2-201.fc39.x86_64

### Prometheus version

```text
prometheus, version 2.48.0 (branch: HEAD, revision: 6d80b30990bc297d95b5c844e118c4011fad8054)
  build user: root@26117804242c
  build date: 20231116-04:35:21
  go version: go1.21.4
  platform:   linux/amd64
  tags:       netgo,builtinassets,stringlabels
```

**Comment by machine424** [comment]
I'd assume the signal sent by closing your terminal session is SIGHUP?

Prometheus uses that signal to allow reloading the configuration, see https://github.com/prometheus/prometheus/blob/ecc37588b00c5ec1d4f2349266a23b01f6c91743/cmd/prometheus/main.go#L970-L1000

Which is documented at https://prometheus.io/docs/prometheus/latest/configuration/configuration/#configuration

If you think we can improve the doc, contributions are welcome.

**Comment by beorn7** [comment]
You can shutdown Prometheus by sending a SIGTERM (which could be triggered by hitting Ctrl-C in a terminal session). That's just normal behavior of almost any program.

You could also use an API endpoint, which is less common behavior and documented here: https://prometheus.io/docs/prometheus/latest/management_api/#quit

WRT closing when the terminal session ends: To my knowledge, closing a terminal session is indeed (only) signaled by SIGHUP, which _some_ programs react to by terminating themselves (presumably programs that only make sense to run in a terminal session). SIGHUP is often used as a signal to reload the config, as it is by Prometheus. In that case, there is just no way of terminating upon closing the terminal session.

**Comment by beorn7** [comment]
Yes, sorry, Ctrl-C sends SIGINT. Prometheus catches both, SIGINT and SIGTERM, and treats them the same (graceful shutdown). Confusingly, the log says "Received SIGTERM, exiting gracefully..." even if SIGINT was received… (and I guess, on MS Windows, the signals are named differently anyway.

So yeah, let's add to https://prometheus.io/docs/prometheus/latest/getting_started/#shutting-down-your-instance-gracefully that SIGINT (and thus Ctrl-C in the terminal) will also shut down the server. And maybe make the wording [here](https://github.com/prometheus/prometheus/blob/a6d4b8d97baa3d73c0d33817b0a3a1213ba57497/cmd/prometheus/main.go#L874) more precise…

**Comment by beorn7** [comment]
Still considering updating the docs to mention SIGINT / Ctrl-C as options for a cleas shutdown.
