### ISSUE TITLE
remove the `remote-write-receiver` flag from `enable-feature`

### ISSUE THREAD

**Issue by jan--f** [prometheus/prometheus#13206]
### Proposal

This flag has been deprecated and user should use `--web.enable-remote-write-receiver` to enable this feature.

_edit_
This issue needs no work at this point. https://github.com/prometheus/prometheus/pull/13435 is the proposed fix. We can only merge this when we have a prometheus 3 branch, so this issue is done but will stay open for a bit.

**Comment by cstyan** [comment]
modified the title a little, it was a bit unclear before what the point of this issue was :+1:

**Comment by rahulrocksn** [comment]
Hey is anyone working on this? If not, I would like to work on it

**Comment by jan--f** [comment]
Yes there is a PR linked against this issue already.

**Comment by beorn7** [comment]
And we can only merge that one once we actually release v3 (or have a release branch for v3, in which we can merge it).

**Comment by yuvarajrece** [comment]
May I participate in working on this?

**Comment by cstyan** [comment]
There's already relevant PRs open for this, we just have to wait until we're releasing v3 to merge them

**Comment by bwplotka** [comment]
Yup, https://github.com/prometheus/prometheus/pull/14526#pullrequestreview-2209290018 solves it.
