### ISSUE TITLE
--enable-feature: remove "promql-at-modifier" and "promql-negative-offset"

### ISSUE THREAD

**Issue by jan--f** [prometheus/prometheus#13207]
### Proposal

Both features are enabled by default and thus should be dropped from the feature flag list for a major version bump.

_edit_
This issue needs no work at this point. https://github.com/prometheus/prometheus/pull/13456 is the proposed fix. We can only merge this when we have a prometheus 3 branch, so this issue is done but will stay open for a bit.

**Comment by asimrehman92** [comment]
@carrieedwards @jan--f 
Hi Gophers, 
Is this issue still open?

**Comment by beorn7** [comment]
Yes, and it will (only) be closed once v3.0.0 has been released with those feature flags removed.

**Comment by beorn7** [comment]
Sorry, I guess you wanted to know if this is still free to work on… I guess it is, and it is indeed an easy one. I guess we will keep the PR unmerged until we have a prometheus-3 release branch (and merge it into that one).

**Comment by asimrehman92** [comment]
Yup, Thank you For understanding,
and for further details please assist me more because this will be my first contribution.

**Comment by beorn7** [comment]
Then take your time and explore the code a bit. You could first search the code base to find where the feature flag mentioned in this issue are processed. From there, it should be easy to see how to remove these flags.

**Comment by beorn7** [comment]
Ummm, now that I look at this issue more closely, there is already a PR doing the thing, see #13456 linked above.
So I guess that means this issue is already "solved", we just need to delay merging the PR and closing the issue up to the point where we have a v3 release branch.

**Comment by asimrehman92** [comment]
@beorn7 thank you for your collaboration.

**Comment by kushalShukla-web** [comment]
is this pr still open ?

**Comment by beorn7** [comment]
The PR #13456 is not merged yet because that can only happen once we have a v3 release branch.

Not sure if it would be better to close this issue already because a "fix" already exists, just intentionally not yet merged.
Prom 3 release coordinators should decide.

**Comment by jan--f** [comment]
I removed the inviting tags and added a quick updated in the description. Maybe that'll help.
