### ISSUE TITLE
All group rules in PrometheusRule are not taken into account if one of the expression a rule of of a group is wrong

### ISSUE THREAD

**Issue by kaiyuanlim** [prometheus/prometheus#13226]
### What did you do?

Created a PrometheusRule with multiple groups.

I have group A, B and C.

Group C has a faulty expression in on its rule which is aws_ebs_volume_idle_time_sum > 100d
It should be aws_ebs_volume_idle_time_sum > 100

This however, caused all of the other groups in the PrometheusRule manifest to be ignored.
Hence, i lost records for a period of 1 month.
No error was thrown in the logs.

### What did you expect to see?

If a rule in group C is problematic, it should not ignore rules group A and B 

### What did you see instead? Under which circumstances?

All rules groups A,B and C are ignored and not processed by prometheus.

There is then a gap in my metrics now.
<img width="1590" alt="image" src="https://github.com/prometheus/prometheus/assets/78371459/8abe8709-a187-4157-a473-91090eb2a843">

### System information

Ubuntu 20.04

### Prometheus version

```text
Prometheus version v2.46.0
```

**Comment by machine424** [comment]
Sorry to here about that, normally groups execute concurrently, maybe the groups do depend on each other?
It'd be helpful if you can share how to reproduce this (if you could provide the final prometheus config, it'd be great)

(In the meanwhile, if there is indeed a bug, enabling the admission webhook may help https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/user-guides/webhook.md)

**Comment by kaiyuanlim** [comment]
Okay, i will enable the admission webhook.

The groups involved are as follows:

`
groups:
- name: resource-consumption
        interval: 1m
        rules:
          - record: sum:cpuusagetotal:30d
            expr: sum_over_time(sum by (namespace) (sum by (namespace, pod) (irate(container_cpu_usage_seconds_total{namespace!=""}[5m])) and on(pod) kube_pod_status_phase{phase="Running"}==1 )[30d:1h])
          - record: sum:allocatablecore:30d
            expr: sum_over_time(max (sum by (namespace) (kube_node_status_allocatable{resource="cpu", unit="core", namespace!=""}))[30d:1h])
          - record: sum:capacitycore:30d
            expr: sum_over_time(max (sum by (namespace) (kube_node_status_capacity{resource="cpu", unit="core", namespace!=""}))[30d:1h])
          - record: sum:cpurequests:30d
            expr: sum_over_time(sum by (namespace) (sum by (namespace, pod) (kube_pod_container_resource_requests{resource="cpu", unit="core", namespace!=""}) and on(pod) kube_pod_status_phase{phase="Running"}==1 )[30d:1h])
          - record: sum:memusage:30d
            expr: sum_over_time(sum by (namespace) (sum by (namespace, pod) (container_memory_usage_bytes{namespace!=""}) and on(pod) kube_pod_status_phase{phase="Running"}==1 )[30d:1h])
          - record: sum:memrequests:30d
            expr: sum_over_time(sum by (namespace) (sum by (namespace, pod) (kube_pod_container_resource_requests{resource="memory", unit="byte", namespace!=""}) and on(pod) kube_pod_status_phase{phase="Running"}==1 )[30d:1h])
          - record: sum:allocatablememory:30d
            expr: sum_over_time(max (sum by (namespace) (kube_node_status_allocatable{resource="memory", unit="byte", namespace!=""}))[30d:1h])
          - record: sum:capacitymemory:30d
            expr: sum_over_time(max (sum by (namespace) (kube_node_status_capacity{resource="memory", unit="byte", namespace!=""}))[30d:1h])
- name: cloudwatch
        rules:
          - alert: EBSVolumeIdleTime
            expr: aws_ebs_volume_idle_time_sum > 100d
            labels:
              severity: warning
            annotations:
              description: "Volume with volumeId {{$labels.volume_id}} is idle for more than 100 days"
              summary: EBS Volume idle for more than 100 days
`

The one that has the wrong expression is EBSVolumeIdleTime and all of the rules in the group resource-consumption were no longer taken into consideration by Prometheus.

**Comment by machine424** [comment]
Well, now that I'm thinking about the webhook admission, I think prometheus-operator should have a built in mechanism to filter out PrometheusRules with faulty groups before applying them. I think your malformed PrometheusRule was never applied to Prometheus, so Prometheus didn't know about the other group.

There has been some recent work in the operator concerning that https://github.com/prometheus-operator/prometheus-operator/pull/5221/files (A metric was added for rejected PrometheusRule, you can add an alert for that, but make sure that alert isn't part of a malformed PrometheusRule ;))

Because there is nothing to do from Prometheus side, I suggest you check with prometheus-operator folks if it makes sense to only ignore malformed groups from a PrometheusRule, for me it isn't worth the complexity given the admission webhook + the new metric, but you can give it a try if you want.

**Comment by kaiyuanlim** [comment]
Got it. I will mark this as closed
