### ISSUE TITLE
prometheus_local_storage_chunks_to_persist includes 

### ISSUE THREAD

**Issue by beorn7** [prometheus/prometheus#1323]
chunksToPersist in function loadSeriesMapAndHeads is incremented for every chunk read from the snapshot. even if it is a still open head chunk. That overestimates the number of chunks to persist

**Comment by beorn7** [comment]
Once this is fixed, we probably want to change the heuristics for going into "graceful degradation mode". If the number of memory chunks exceeds the configured amount and there is a reasonable (but not necessarily large) number of chunks waiting for persistence, we should also go into "speedy" mode.

**Comment by fabxc** [comment]
How soon can we fix these related issues?
Once that's done and #1318 merged we should be mostly ready for a RC of v0.17.0.

**Comment by beorn7** [comment]
This is pretty low hanging fruit. I'll fix it ~this week.
