### ISSUE TITLE
web/ui/bindata.go changes during runtime

### ISSUE THREAD

**Issue by RichiH** [prometheus/prometheus#1326]
If I want to `git pull` in a repo I also build & run from, I always get

````
error: Your local changes to the following files would be overwritten by checkout:
        web/ui/bindata.go
Please, commit your changes or stash them before you can switch branches.
Aborting
````

I am unsure if said file should not be tracked at all or if local state should be put elsewhere, but either way, this is annoying.

**Comment by fabxc** [comment]
It doesn't change at runtime – at least there's would be no logical cause for that.

It most likely happens when you run `make` and the `assets` target is executed. It always wants to update all the timestamps. Best to remove that from the default execution.

**Comment by RichiH** [comment]
Sorry, didn't verify that.

That sounds fine a well.

Richard

Sent by mobile; excuse my brevity.

**Comment by fabxc** [comment]
I agree that it's truly annoying. We removed it from Alertmanager for that reason but didn't do for Prometheus yet.
