### ISSUE TITLE
Feature request: `sort_metric()` or similar

### ISSUE THREAD

**Issue by RichiH** [prometheus/prometheus#1328]
For active debugging when going through a list of targets, having a consistent order for the metrics and label sets would be useful.

Ideally, this should sort alphabetically and numerically, i.e.

````
bar{quux="1"}
foo1{quux="1"}
foo1{quux="2"}
foo1{quux="10"}
foo2{quux="1"}
foo10{quux="1"}
````

@cron2

**Comment by brian-brazil** [comment]
Dupe of #414
