### ISSUE TITLE
Probably wrong release notes?

### ISSUE THREAD

**Issue by datamuc** [prometheus/prometheus#13290]
### What did you do?

Two BUGFIXES in the release notes https://github.com/prometheus/prometheus/releases/tag/v2.45.1 refer to #12644. But this task is open and seems to have nothing to do with the mentioned bugs.

### What did you expect to see?

the correct links

### What did you see instead? Under which circumstances?

n/a

### System information

n/a

### Prometheus version

```text
n/a
```

### Prometheus configuration file

```yaml
n/a
```

**Comment by machine424** [comment]
Nice catch @datamuc 

I think the right links are:

- [BUGFIX] Linode SD: Cast InstanceSpec values to int64 to avoid overflows on
386 architecture. https://github.com/prometheus/prometheus/pull/12568
- [BUGFIX] TSDB: Handle TOC parsing failures. https://github.com/prometheus/prometheus/pull/10623

cc @roidelapluie

**Comment by codesome** [comment]
Thanks, I have updated it now
