### ISSUE TITLE
time() function with error

### ISSUE THREAD

**Issue by songjiayang** [prometheus/prometheus#13292]
### What did you do?

Run `time()` function in prometheus web console.

### What did you expect to see?

work well

### What did you see instead? Under which circumstances?

Got errors:

```
Error executing query: Cannot convert undefined or null to object
```

### Prometheus version

```text
Version	2.49.0-rc.0
Revision	c4c8d59c14ea558a4878fb014cc954347c317978
Branch	HEAD
BuildUser	root@e59256874f10
BuildDate	20231212-11:17:29
GoVersion	go1.21.5
```

**Comment by rgroothuijsen** [comment]
This is caused by a missing type check [here](https://github.com/prometheus/prometheus/blob/main/web/ui/react-app/src/pages/graph/Panel.tsx#L196), since it doesn't expect a scalar input. If you wrap the query result in a vector, i.e. `vector(time())`, it does produce an output.

**Comment by machine424** [comment]
You're right @rgroothuijsen 

`isHeatmapData` assumes the input to be of `GraphProps['data']` which is not always true.

I have a reproduction test in here https://github.com/prometheus/prometheus/compare/main...machine424:prometheus:dont-heat-ui (I think this part needs more tests) is someone would like to work on a fix.

**Comment by Loori-R** [comment]
Yes, my oversight. I can take care of it next week.

**Comment by bwplotka** [comment]
Sounds like v2.49.0 is blocked by this then (:

**Comment by bwplotka** [comment]
Friendly ping @Loori-R

**Comment by kevinmingtarja** [comment]
If there's no cycles for this internally, I'd be more than happy to contribute!

**Comment by bwplotka** [comment]
Go for it @kevinmingtarja

**Comment by kevinmingtarja** [comment]
Okay, I'm on it!
