### ISSUE TITLE
Docs for the --web.cors.origin flag are broken

### ISSUE THREAD

**Issue by paketb0te** [prometheus/prometheus#13309]
### What did you do?

Looking at the docs for the [`--web.cors.origin` flag](https://prometheus.io/docs/prometheus/latest/command-line/prometheus/#flags), it appears that the example regex (containing a pipe character `|`) breaks the markdown table that it is included in.

### What did you expect to see?

| Flag | Description | Default |
| --- | --- | --- |
| <code class="text-nowrap">--web.cors.origin</code> | Regex for CORS origin. It is fully anchored. Example: `https?://(domain1\|domain2)\.com` | `.*` |

### What did you see instead? Under which circumstances?

| Flag | Description | Default |
| --- | --- | --- |
| <code class="text-nowrap">--web.cors.origin</code> | Regex for CORS origin. It is fully anchored. Example: 'https?://(domain1|domain2)\.com' | `.*` |

### Prometheus version

```text
latest public docs at https://prometheus.io/docs/prometheus/latest/command-line/prometheus/#flags
```

**Comment by bboreham** [comment]
Fixed by #14420.
