### ISSUE TITLE
Many vendored packages miss license files

### ISSUE THREAD

**Issue by grobie** [prometheus/prometheus#1331]
govendor doesn't copy license related files and prometheus is now violating the license of several projects.

Upstream issue tracked here https://github.com/kardianos/govendor/issues/77

**Comment by fabxc** [comment]
I explained the reasons in the other PR but agree that it's not great (I think everyone who vendors just rolls with it for now). Thanks for filing the upstream bug – sounds promising.

**Comment by grobie** [comment]
Well, when it comes to legal I'd be wary of "just rolling with it". I'll open a PR.
