### ISSUE TITLE
SD: failed to register metric: duplicate metrics collector registration attempted consul.go:349

### ISSUE THREAD

**Issue by bwplotka** [prometheus/prometheus#13312]
### Proposal

From @roman-vynar https://github.com/prometheus/prometheus/issues/13245#issuecomment-1863001187:

> looks like I have discovered another bug while testing this, not in v2.48.0 but it is in the main.
> Looks like the following commit https://github.com/prometheus/prometheus/commit/6de80d7fb03f7cd5ed44b85559886e73d89e720d
> It throws errors like this

> ts=2023-12-19T15:35:28.274Z caller=consul.go:349 level=error component="discovery manager scrape"
 discovery=consul config=xxx msg="Unable to register metrics" 
err="failed to register metric: duplicate metrics collector registration attempted"
> if you have 1+ jobs with the same type of SD, e.g. 2 jobs with consul_sd_config or azure_sd_config etc.

cc @ptodev do you mind double checking this?

**Comment by ptodev** [comment]
Hello, apologies for this. I will take a look into fixing it today.

**Comment by ahsanashraf918** [comment]
i faced same
{"caller":"file.go:258","component":"discovery manager scrape","config":"app metrics","discovery":"file","err":"failed to register metric: duplicate metrics collector registration attempted","level":"error","msg":"Unable to register metrics","ts":"2023-12-26T12:31:58.934Z"}

**Comment by machine424** [comment]
Had the same error using the kube SD config in https://github.com/prometheus/prometheus/issues/11305

Some targets are not taken into account.
