### ISSUE TITLE
No targets in Prometheus

### ISSUE THREAD

**Issue by Flaco0898** [prometheus/prometheus#13323]
### What did you do?

Added 21 targets on my prometheus.yml file

### What did you expect to see?

All of my pre-configured targets

### What did you see instead? Under which circumstances?

I can add 20 targets and everything is ok, but once i add one more and all of them but one dissapear. If i go to Service Discovery i can find all of them, but not in "Targets" and every metric on grafana gets lost untill deleting that last one on prometheus.yml file, i tried to change the scrape time interval thinking it was not enough but remains the same.

### System information

Rocky Linux 9.3 Blue Onyx

### Prometheus version

<html>
<body>

Version | 2.48.0
-- | --
6d80b30990bc297d95b5c844e118c4011fad8054
HEAD
root@26117804242c
20231116-04:35:21
go1.21.4

</body>
</html>

### Prometheus configuration file

global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 1m
  external_labels:
    monitor: codelab-monitor
scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  enable_http2: true
  static_configs:
  - targets:
    - prometheus:9090
- job_name: node_exporter
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  enable_http2: true
  static_configs:
  - targets:
    - node_exporter:9100
- job_name: SRV-Insurgentes
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  enable_http2: true
  static_configs:
  - targets:
    - 192.168.2.1:9182
- job_name: SRV-Diaz_Ordaz
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  enable_http2: true
  static_configs:
  - targets:
    - 192.168.76.1:9182
- job_name: SRV-Hipodromo
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  enable_http2: true
  static_configs:
  - targets:
    - 192.168.4.1:9182
- job_name: SRV-Baja_Mil
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  enable_http2: true
  static_configs:
  - targets:
    - 192.168.35.1:9182
- job_name: SRV-ENS-AV.Juárez
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  enable_http2: true
  static_configs:
  - targets:
    - 192.168.160.1:9182
- job_name: SRV-ENS-AV.Guadalupe
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  enable_http2: true
  static_configs:
  - targets:
    - 192.168.161.1:9182
- job_name: SRV-ENS-AV.Mision
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  enable_http2: true
  static_configs:
  - targets:
    - 192.168.163.1:9182
- job_name: SRV-ENS-AV.Coral
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  enable_http2: true
  static_configs:
  - targets:
    - 192.168.164.1:9182
- job_name: SRV-Brazil
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  enable_http2: true
  static_configs:
  - targets:
    - 192.168.19.1:9182
- job_name: SRV-Madero
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  enable_http2: true
  static_configs:
  - targets:
    - 192.168.44.1:9182
- job_name: SRV-Zaragoza
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  enable_http2: true
  static_configs:
  - targets:
    - 192.168.47.1:9182
- job_name: SRV-Calle_Esmeralda
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  enable_http2: true
  static_configs:
  - targets:
    - 192.168.165.1:9182
- job_name: SRV-Pedro_Loyola
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  enable_http2: true
  static_configs:
  - targets:
    - 192.168.166.1:9182
- job_name: SRV-ENS-Reforma_9na
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  enable_http2: true
  static_configs:
  - targets:
    - 192.168.96.1:9182
- job_name: SRV-Vista_Hermosa
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  enable_http2: true
  static_configs:
  - targets:
    - 192.168.116.1:9182
- job_name: SRV-Rio_Fuerte
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  enable_http2: true
  static_configs:
  - targets:
    - 192.168.123.1:9182
- job_name: SRV-Lazaro_Cardenas
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  enable_http2: true
  static_configs:
  - targets:
    - 192.168.170.1:9182
- job_name: SRV-Gonzalez
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  enable_http2: true
  static_configs:
  - targets:
    - 192.168.5.1:9182

###Logs

**Comment by machine424** [comment]
Prometheus version
Prometheus configuration file
and Logs

would be helpful.

**Comment by Flaco0898** [comment]
Here are the Logs. i don really know if this is enough, but this part of them took my attention

ts=2023-12-18T23:00:03.263Z caller=db.go:1619 level=info component=tsdb msg="Deleting obsolete block" block=01HHYQ1VYP6SGW9RYSCV7ZS609
ts=2023-12-18T23:00:03.266Z caller=db.go:1619 level=info component=tsdb msg="Deleting obsolete block" block=01HHZ4SAF4NFW6GS3R221F24P6
ts=2023-12-18T23:00:03.270Z caller=db.go:1619 level=info component=tsdb msg="Deleting obsolete block" block=01HHYXXK6QS560GHWPSVJTYCJ2
ts=2023-12-18T23:37:52.735Z caller=main.go:859 level=warn msg="Received SIGTERM, exiting gracefully..."
ts=2023-12-18T23:37:52.735Z caller=main.go:883 level=info msg="Stopping scrape discovery manager..."
ts=2023-12-18T23:37:52.735Z caller=main.go:897 level=info msg="Stopping notify discovery manager..."
ts=2023-12-18T23:37:52.735Z caller=manager.go:1026 level=info component="rule manager" msg="Stopping rule manager..."
ts=2023-12-18T23:37:52.735Z caller=manager.go:1036 level=info component="rule manager" msg="Rule manager stopped"
ts=2023-12-18T23:37:52.735Z caller=main.go:934 level=info msg="Stopping scrape manager..."
ts=2023-12-18T23:37:52.735Z caller=main.go:893 level=info msg="Notify discovery manager stopped"
ts=2023-12-18T23:37:52.736Z caller=main.go:879 level=info msg="Scrape discovery manager stopped"
ts=2023-12-18T23:37:52.737Z caller=main.go:926 level=info msg="Scrape manager stopped"
ts=2023-12-18T23:37:52.802Z caller=notifier.go:604 level=info component=notifier msg="Stopping notification manager..."
ts=2023-12-18T23:37:52.802Z caller=main.go:1155 level=info msg="Notifier manager stopped"
ts=2023-12-18T23:37:52.802Z caller=main.go:1167 level=info msg="See you next time!"
ts=2023-12-18T23:37:59.095Z caller=main.go:539 level=info msg="No time or size retention was set so using the default time retention" duration=15d
ts=2023-12-18T23:37:59.095Z caller=main.go:583 level=info msg="Starting Prometheus Server" mode=server version="(version=2.48.0, branch=HEAD, revision=6d80b30990bc297d95b5c844e118c4011fad8054)"
ts=2023-12-18T23:37:59.095Z caller=main.go:588 level=info build_context="(go=go1.21.4, platform=linux/amd64, user=root@26117804242c, date=20231116-04:35:21, tags=netgo,builtinassets,stringlabels)"
ts=2023-12-18T23:37:59.095Z caller=main.go:589 level=info host_details="(Linux 5.14.0-284.11.1.el9_2.x86_64 #1 SMP PREEMPT_DYNAMIC Tue May 9 17:09:15 UTC 2023 x86_64 56be1daa1720 (none))"
ts=2023-12-18T23:37:59.095Z caller=main.go:590 level=info fd_limits="(soft=1073741816, hard=1073741816)"
ts=2023-12-18T23:37:59.095Z caller=main.go:591 level=info vm_limits="(soft=unlimited, hard=unlimited)"
ts=2023-12-18T23:37:59.097Z caller=web.go:566 level=info component=web msg="Start listening for connections" address=0.0.0.0:9090
ts=2023-12-18T23:37:59.097Z caller=main.go:1024 level=info msg="Starting TSDB ..."
ts=2023-12-18T23:37:59.098Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1701814554112 maxt=1701842400000 ulid=01HGZCJ0CMSE9NCSGZ6DWGF8B5
ts=2023-12-18T23:37:59.098Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1701842403342 maxt=1701907200000 ulid=01HH1ABHD5EY6N6Y2YDMTQX67Y
ts=2023-12-18T23:37:59.098Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1701907203340 maxt=1701972000000 ulid=01HH3852VFQYH9P9NSE8QTFXFZ
ts=2023-12-18T23:37:59.098Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1701972003340 maxt=1702036800000 ulid=01HH55YM5W3S9470QYKF1M7GRK
ts=2023-12-18T23:37:59.098Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1702036803342 maxt=1702101600000 ulid=01HH73R563FWS1PKH2EHNQXB70
ts=2023-12-18T23:37:59.098Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1702101603342 maxt=1702166400000 ulid=01HH91HPEENFRQ60HVQP4FT98N
ts=2023-12-18T23:37:59.099Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1702166403342 maxt=1702231200000 ulid=01HHAZB7SZFC41M0FHM4HPWETH
ts=2023-12-18T23:37:59.099Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1702231203342 maxt=1702296000000 ulid=01HHCX4KJ0VE734YN639XQTTXX
ts=2023-12-18T23:37:59.099Z caller=tls_config.go:274 level=info component=web msg="Listening on" address=[::]:9090

**Comment by sakaspar** [comment]
It seems like there might be an issue with your Prometheus configuration. One thing that stands out is that you have repeated configurations for each job, specifically the static_configs block. Each job definition should have a single static_configs block with a list of targets.

For example, instead of having separate static_configs for each job, you should organize your configuration like this:

`scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - prometheus:9090

  - job_name: node_exporter
    static_configs:
      - targets:
          - node_exporter:9100

  - job_name: SRV-Insurgentes
    static_configs:
      - targets:
          - 192.168.2.1:9182

  # ... Same for other jobs`

Make sure to correct the structure for all jobs. Having multiple static_configs blocks at the same level.

**Comment by machine424** [comment]
I don't think there's any problem with the config.
I think it's a UI issue, adding that 21th target strangely triggers some sticky scrapePool filtering on the page like in https://github.com/prometheus/prometheus/issues/13413
I think we can close the issue in favor of the other one that contains more details. And maybe add your config there as a simpler way to reproduce the issue.

**Comment by machine424** [comment]
I added your config as a way to reproduce the issue https://github.com/prometheus/prometheus/issues/13413#issuecomment-2042091658
I'll close the issue, don't hesitate if there is sth else we should know about.
