### ISSUE TITLE
RW - wrong status code for storage.ErrTooOldSample (out of order time window feature)

### ISSUE THREAD

**Issue by nmdanny** [prometheus/prometheus#13334]
### What did you do?

The remote write [spec](https://prometheus.io/docs/concepts/remote_write_spec/#retries-backoff) specifies that a RW sender must perform retries when encountering a 5xx status code

When using the experimental out of order window feature, and attempting to ingest a sample older than the window,
I receive `500 Internal Server Error: too old sample`

Assuming there's no server mis-configuration or time sync issues, this error is truly non-recoverable and thus it makes no sense to retry it. Such scenario is likely when there can be significant lag between the RW sender and the receiver, e.g, when using a message queue.

The following lines (and perhaps others) seem like they should be adjusted to handle `storage.ErrTooOldSample` as well

https://github.com/prometheus/prometheus/blob/6b8e9453881bffe5fe3aec99a6f3462676a95489/storage/remote/write_handler.go#L71C1-L74C9

### What did you see instead? Under which circumstances?

Sending RW requests (from a go service) with old samples, beyond the out of order window, yields a status code of 500 (should probably be 400) 
Prometheus 2.45.1

**Comment by bboreham** [comment]
Why 404?  I think 403 is more appropriate:
> 403 Forbidden
> The server understood the request, but is refusing to fulfill it. Authorization will not help and the request SHOULD NOT be repeated. If the request method was not HEAD and the server wishes to make public why the request has not been fulfilled, it SHOULD describe the reason for the refusal in the entity. If the server does not wish to make this information available to the client, the status code 404 (Not Found) can be used instead.

**Comment by nmdanny** [comment]
You're right, 404 is not appropriate - I meant to use 400 - Bad Request

> The HyperText Transfer Protocol (HTTP) 400 Bad Request response status code indicates that the server cannot or will not process the request due to something that is perceived to be a client error (for example, malformed request syntax, invalid request message framing, or deceptive request routing).


From my understanding, 403 is usually used in the context of security/RBAC - which isn't the case here, since this is a business logic restriction. Seeing 403 in logs would usually imply some auth issue which would be misleading.

**Comment by cykl** [comment]
Thanks. 

I just handled an incident triggered by this behavior. The Prometheus server returned `500: too old sample` one time to an agent configured to remote write its data. Agent then endlessly retried the same call again and again block all samples until I killed / cleaned it. 

Returning 400 seems like the right to do.

**Comment by bboreham** [comment]
Looks like `ErrOutOfOrderExemplar` and a few others would have the same problem.
