### ISSUE TITLE
promql (histograms): Issue warning if `histogramRate` is applied to the wrong kind of histogram

### ISSUE THREAD

**Issue by beorn7** [prometheus/prometheus#13345]
### Proposal

In short: The [`histogramRate`](https://github.com/prometheus/prometheus/blob/756202aa4fc09c4fdc756a8c5b1976d709cd3939/promql/functions.go#L178) function can be applied to gauge histograms and to counter histograms. Ideally, the `isCounter` argument is `true` if applied to counter histograms, and it is `false` if applied to gauge histograms. Otherwise, we should issue a warning via the new annotation system.

See relevant TODOs in the code:
- https://github.com/prometheus/prometheus/blob/756202aa4fc09c4fdc756a8c5b1976d709cd3939/promql/functions.go#L199
- https://github.com/prometheus/prometheus/blob/756202aa4fc09c4fdc756a8c5b1976d709cd3939/model/histogram/float_histogram.go#L473

The broad plan would be to issue the warning in the following two cases:
- `isCounter` is `false` but the first or the last histogram in the range is not a gauge histogram.
- `isCounter` is `true` but at least one histogram in the range is a gauge histogram.

The good thing here is that we know precisely if a histogram is a gauge histogram or a counter histogram. It's not just a naming convention we have to rely on like for float samples.

**Comment by EmadMokhtar** [comment]
Is this good ticket for new contributor? if yes, I'm interested to work on it.

**Comment by beorn7** [comment]
It's not super complex, but probably not a good first issue, either. I already ping'd @zenador on it. She has implemented similar warnings before and is probably most qualified to do this.
