### ISSUE TITLE
Implement an integral() function

### ISSUE THREAD

**Issue by gtopper** [prometheus/prometheus#1335]
Similar to Graphite's [integral()](http://graphite.readthedocs.org/en/latest/functions.html#graphite.render.functions.integral), and InfluxDB's planned [INTEGRAL()](https://influxdb.com/docs/v0.9/query_language/functions.html#integral).

This would be useful as a workaround for #1334, and would have the added benefit of always starting at 0, as opposed to the arbitrary value the counter happens to have reached at the beginning of the displayed time frame.

**Comment by beorn7** [comment]
This function already exists: `sum_over_time` or (depending on your exact use case) `average_over_time` http://prometheus.io/docs/querying/functions/#aggregation-_over_time

**Comment by beorn7** [comment]
Doesn't account for counter resets, though.

**Comment by gtopper** [comment]
As partly mentioned in #1334, integral() differs from sum_over_time() in that integral() results in a graph where all time series start at zero, whereas the starting value of sum_over_time() is arbitrary (whatever counters happened to be set to at that time). Is there a workaround for that?

I guess there's a significant difference in approach between Prometheus and Graphite: Prometheus doesn't seem to have any functionality that recognizes the concept of an "observed timeframe" - everything is time windowed, probably to suit the alerting functionality, where only time windows have meaning. However, when graphing, the timeframe observed can be very meaningly, e.g. if you're trying to see the increase of things over that timeframe.

**Comment by beorn7** [comment]
I think the fundamental problem is the same as in #1334 . Let's dup this one and have the discussion only in that other issue.

**Comment by cberner** [comment]
@beorn7, `sum_over_time` is quite different because it treats all data points as equally spaced. There's no way to recover the area under curve, like a proper `integral` function would return

**Comment by beorn7** [comment]
Yes, I think you are right. A different question is if such an integral function should be in PromQL.

For such discussions, the  [prometheus-developers mailing list](https://groups.google.com/forum/#!forum/prometheus-developers) is much better suited than a GitHub issue. Ideally, you would present a few good use cases there and create a consensus that the feature is useful. Then, we can file a feature request issue here.
