### ISSUE TITLE
remote write 2.0: Add support for created timestamp propagation [spec]

### ISSUE THREAD

**Issue by cstyan** [prometheus/prometheus#13368]
@ArthurSens and @bwplotka have been working on support for created timestamps in Prometheus. These can be considered metadata, and should be propagated in remote write 2.0.

**Comment by bwplotka** [comment]
This is done in spec see https://github.com/prometheus/docs/pull/2462

However Prometheus supporting this field is still to do. Keeping this issue open to reflect this.
