### ISSUE TITLE
adding scrape rule for subdomain.subdomain.example.com does not get scraped

### ISSUE THREAD

**Issue by riaanp78** [prometheus/prometheus#13374]
### What did you do?

I added a new scrape rule for a sub domain of a sub domain 

` 
     - job_name: "example"
        scheme: "https"
        scrape_timeout: 20s
        metrics_path: "/metrics"
        static_configs:
          - targets: ["subdomain.subdomain.example.com:443"]
            tls_config:
              insecure_skip_verify: true
`

### What did you expect to see?

The data appearing under service discovery or  targets

### What did you see instead? Under which circumstances?

Nothing, no error messages. Also rule is not showing in in the config section. appears to be entirely ignored, 

### System information

Kubernetes 

### Prometheus version

```text
Latest Helm chart
```

**Comment by machine424** [comment]
I bet it won't work with any domain, did you try with `example.com`?
my though is that your config is malformed, thus blocked by the config-reloader and prometheus never knows about it.

That being said, if you could provide exact steps to reproduce this, I could take a look.

**Comment by riaanp78** [comment]
@machine424 I just obfuscated my real domain. I also found my problem. There was a setting that prometheus didn't like where I attempted to disable TLS on a scrape job. Which was weird since I saw it on the examples (are the examples maintained?)
But this can be ignored and closed. Not a prometheus problem.

**Comment by machine424** [comment]
Good news.
If the examples are not up to date, don't hesitate to raise a PR ;)
I think this could be closed then?

**Comment by riaanp78** [comment]
@machine424 yes you may close. In hind site i was a bit quick on logging a ticket - apologies.
