### ISSUE TITLE
tsdb: need histogram support for created-timestamp handling

### ISSUE THREAD

**Issue by beorn7** [prometheus/prometheus#13384]
### Proposal

OM introduced created timestamps, but doesn't support native histograms yet. However, we have backported created-timestamps to the classic protobuf format, which also supports native histograms. (And of course, OM is supposed to support native histograms soon.)

Combining both features, we run into the problem that [AppendCTZeroSample](https://github.com/prometheus/prometheus/blob/6cd24d87b0d4e3acd4503b061d32c5aa6d8883a9/tsdb/head_append.go#L389) will always insert a float zero sample, even into a series of histograms. Which will make rate calculation impossible whenever the zero float sample and any histogram sample is in the range at the same time.

So we need to find a way to insert a zero histogram in case the created timestamp comes with a histogram sample.

**Comment by beorn7** [comment]
@ArthurSens would you be interested in working on this?

@bwplotka @krajorama FYI.

**Comment by ArthurSens** [comment]
Yes, that sounds fun :) Finally an excuse for me to dig deeper into native histograms :P

Is this something that you folks need ASAP? I have an accepted talk at kubecon around something that I haven't finished the implementation, I can work on this after a few weeks 😬

**Comment by beorn7** [comment]
Given that's only happening if you activate both feature flags at the same time, I doubt it's super urgent. But user reports will tell. :)

**Comment by ArthurSens** [comment]
I'm just making sure I understand the problem here.

We currently have 2 sample types, `float` and `histogram`. The problem is that `AppendCTZeroSample` appends a float type and we don't check if we're appending a float or a histogram before calling it. Is that correct?

If yes, what do we want to do here? Just ensure we don't call `AppendCTZeroSample` when iterating over a histogram? Or implement AppendCTZeroSample to HistogramAppender?

I'm asking because I haven't fully understood how native histograms work under the hood... does created timestamps matter in their context?

**Comment by beorn7** [comment]
If a histogram is a counter-like histogram, CT applies in the same way as for float counters.

The same way as a zero float sample is inserted into a series of float counters, we need to insert a zero histogram sample into a series of histogram counters.

In the exposition format, we can see if a CT is part of a float sample or a histogram sample, so it should be easy to do the right thing.

Implementation details have to be researched, but the above describes the desired outcome.

**Comment by ArthurSens** [comment]
Awesome, thanks for the info!

Another question, what is the histogram equivalent to a zero sample?

Does this look correct?
```go
histogram.Histogram{Count: 0, Sum: 0, Schema: 3, ZeroThreshold: 0.0, ZeroCount: 0}
```

**Comment by beorn7** [comment]
yes. just use the Go zero value.

We might need to check that a schema change or a change of the zero bucket doesn't trigger a new chunk if it is only for an empty histogram. Once we have made sure of that, even the Schema doesn't matter anymore.

**Comment by beorn7** [comment]
@ArthurSens is this still on your radar? I think we need this to declare native histograms a stable feature (which, in turn, we would really like for v3 of Prometheus).

**Comment by ArthurSens** [comment]
Yes, I had a branch almost ready actually, but I've got some feedback in #13506 saying that we want to refactor the scrapeloop code a little bit before advancing here.

This will definitely come out before 3.0 though :)

**Comment by bwplotka** [comment]
Just reviewing the current WIP PR and I wonder... should do anything with ResetHint? Or it simply will be less useful field if we have CT attached to some samples in future with e.g. metadata store

**Comment by beorn7** [comment]
I think the ResetHint and the CT should be consistent with each other. We cannot enforce that all targets will consistently and correctly add CTs, so we still need the ResetHint. Or in other words: CT should just feed into ResetHint as yet another source of information for a counter reset.

Maybe one day we can promote CT to be _the_ counter reset source of truth (implying we have to "fix" a CT that comes in incorrectly from a target or add a CT if a target doesn't expose one). But even then, we still need a marker for gauge histograms.

**Comment by krajorama** [comment]
Agree with Beorn, I did add this comment in otel collector to say pretty much the same: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/624b3682b96067aca40a0b70beb844e94f561a50/pkg/translator/prometheusremotewrite/histograms.go#L67

**Comment by ArthurSens** [comment]
While working on https://github.com/prometheus/prometheus/pull/14694, I've noticed that our strategy of ingesting a "Zero" histogram, i.e. `histogram.Histogram{}`, already plays nicely with counterResetHints.

You'll notice in the new test `TestHeadAppender_AppendHistogramCTZeroSample`, "zero" histograms are appended and the appender correctly adds CounterResetHints to them.
