### ISSUE TITLE
Range vector incorrectly accepts embedded offset modifier

### ISSUE THREAD

**Issue by PeterZaitsev** [prometheus/prometheus#1338]
Hi,

rate(mysql_global_status_questions{alias="$host"} offset 1d[$interval])

is allowed and it returns data without any offset. 

rate(mysql_global_status_questions{alias="$host"}[$interval] offset 1d)

is correct syntax which returns proper data

Is there any reason 1st variant does not return and error ?

**Comment by grobie** [comment]
According to the documentation of [range selector](http://prometheus.io/docs/querying/basics/#range-vector-selectors) and [offsets](http://prometheus.io/docs/querying/basics/#offset-modifier), the behavior of the first expression is undefined. I believe it's an oversight that it parses the range vector expression ignoring the offset.
