### ISSUE TITLE
PromQL: Make durations and number literals the same

### ISSUE THREAD

**Issue by beorn7** [prometheus/prometheus#13412]
### Proposal

This has been agreed upon a long time ago. Also see [this design doc by @darshanime](https://docs.google.com/document/d/1LaZfknXuuRWGtQSbULoMtclQhuLUMrdwg15wMvoBvCQ/edit#) and [this brain dump of mine](https://docs.google.com/document/d/1jMeDsLvDfO92Qnry_JLAXalvMRzMSB1sBr9V7LolpYM/edit).

@darshanime gave it a try in https://github.com/prometheus/prometheus/pull/9138 , but the PR fell stale without follow-up to comments.

v3 would be a great timing to finish this up (either as a new PR or by building on top of #9138), because this changes the syntax of PromQL (in a backwards-compatible way, but still).

**Comment by darshanime** [comment]
hello! i've resurrected https://github.com/prometheus/prometheus/pull/9138, we can continue the discussion there...

**Comment by beorn7** [comment]
Great, thank you very much.

**Comment by Maniktherana** [comment]
@beorn7 I'll try this out.

**Comment by Maniktherana** [comment]
@beorn7 I'll try this out

**Comment by NeerajGartia21** [comment]
@beorn7 I'll also try this and see what happens.

**Comment by NeerajGartia21** [comment]
No problem, I'll be happy to help @Maniktherana if he needs any.

**Comment by Nexucis** [comment]
yeah that shouldn't be too complicated to update that @beorn7.

**Comment by Maniktherana** [comment]
@beorn7 @Nexucis Just to confirm, the issue of the red squiggles is coming from the parser in `@prometheus-io/codemirror-promql` right? Doesn't look like it has anything to do with the react app itself

**Comment by beorn7** [comment]
I guess so (but this is just to prove that I don't even know the differences between "the react app" and "the parser").

**Comment by Maniktherana** [comment]
> I guess so (but this is just to prove that I don't even know the differences between "the react app" and "the parser").
> 
> 

By react app I'm referring to web/ui/react-app. The parser would be in web/ui/module/codemirror-promql

**Comment by Nexucis** [comment]
yeah the packages that need to be updated are 
* `@prometheus-io/lezer-promql` for the grammar 
* and `@prometheus-io/codemirror-promql` for the autocompletion and parser.

Both needs to be updated and there is nothing to update in the `react-app`

**Comment by Maniktherana** [comment]
> yeah the packages that need to be updated are
> 
> * `@prometheus-io/lezer-promql` for the grammar
> * and `@prometheus-io/codemirror-promql` for the autocompletion and parser.
> 
> Both needs to be updated and there is nothing to update in the `react-app`

Do I update the modules in this repo? As the individual repos under prometheus are archived

**Comment by Nexucis** [comment]
yes it has to updated in this repo. They are located under the path `web/ui/module`

**Comment by beorn7** [comment]
https://github.com/prometheus/prometheus/pull/14417 updating the UI has been merged. We can finally close this issue.
