### ISSUE TITLE
Add Host Binding Feature to Prometheus Emitter

### ISSUE THREAD

**Issue by diosvo** [prometheus/prometheus#13429]
## Summary
The Prometheus emitter cannot currently bind to a specific host. This feature is crucial for environments where binding to all interfaces (default behaviour) is not desired or poses security concerns. This ticket aims to enhance the Prometheus emitter by introducing a configurable host binding option.

### Problem Statement: 
Currently, the Prometheus emitter binds to all available network interfaces. This behaviour might not be ideal in certain deployment scenarios, especially in multi-homed environments or where strict network security policies are enforced.

### Proposed Solution:
- Implement a configuration option specifying a particular host/IP address to which the Prometheus emitter should bind. This option should be flexible enough to support different deployment needs (e.g., binding to localhost for local monitoring, binding to a specific interface in multi-homed setups).
- Expected Outcome: Once implemented, users can configure the Prometheus emitter to bind to a specific host/IP. This enhancement will provide better security and more control over network traffic management.

### Use Cases:
Bind to `localhost` for scenarios where Prometheus metrics are only consumed locally.
Specify a particular network interface in environments with multiple network interfaces to control network exposure.

###  Implementation Notes:
A new configuration parameter (e.g., `hostBindAddress`) should be introduced.
The emitter's network binding logic should be updated to respect this new parameter, defaulting to the current behaviour (binding to all interfaces) when not specified.

### Security: 
Reduced attack surface by preventing the Prometheus emitter from exposing metrics on all network interfaces.

### Flexibility: 
Users gain more control over their Prometheus emitter deployments, tailoring them to specific network requirements.

**Comment by roidelapluie** [comment]
We have never got that request in the past. Do you have a real use case or requirement? This sounds very specific and very niche. I prefer to rely on the operating system.

**Comment by darshanime** [comment]
Can you clarify what you mean by "prometheus emitter"? If you are talking about prometheus proper, we already have the `--web.listen-address` flag you can use?
