### ISSUE TITLE
stacked graphs are not deep linked anymore

### ISSUE THREAD

**Issue by peterhoneder** [prometheus/prometheus#13445]
### What did you do?

If you create a query with multiple results and switch to the stacked graph, it will reset to the unstacked lines every time you:
- click refresh
- open a link
- click the execute button

in the previously deployed version (v2.48.1), it still worked correctly (as it did the last years). Could this PR be responsible for the regression? https://github.com/prometheus/prometheus/pull/13096

### What did you expect to see?

stacked lines to be remembered, like in the previous version of prometheus

### What did you see instead? Under which circumstances?

unstacked lines

### Prometheus version

```text
Build Information
Version	2.49.1
Revision	43e14844a33b65e2a396e3944272af8b3a494071
Branch	HEAD
BuildUser	root@6d5f4c649d25
BuildDate	20240115-16:58:43
GoVersion	go1.21.6
```

**Comment by raoulbhatia** [comment]
CC @Loori-R @juliusv @beorn7 as you were involved in #13096

**Comment by Nexucis** [comment]
closed with https://github.com/prometheus/prometheus/pull/13460
