### ISSUE TITLE
Error opening React index.html: open web/ui/static/react/index.html: no such file or directory

### ISSUE THREAD

**Issue by chenpfeisoo** [prometheus/prometheus#13459]
### What did you do?

vist url http://localhost:9090  after run  main  funciton   , web/ui/static/react/index.html: no such file or directory

### What did you see instead? Under which circumstances?

Error opening React index.html: open web/ui/static/react/index.html: no such file or directory
<img width="1444" alt="image" src="https://github.com/prometheus/prometheus/assets/18147157/8c89b670-995f-454f-816b-52d0646ec2c7">
![image](https://github.com/prometheus/prometheus/assets/18147157/39076f8f-57d3-4bef-a816-c633b2cd793c)

**Comment by roidelapluie** [comment]
Thank you for your pull request. You should follow the instructions ln the readme to build Prometheus from source, or get our pre-built builds. You can download them from the website.
