### ISSUE TITLE
WAL watcher unable to catch up when backlogged

### ISSUE THREAD

**Issue by djudd** [prometheus/prometheus#13471]
### What did you do?

I reported this in Slack, and while I don't have a simple reproduction, @cstyan confirmed that this looks like a bug: https://cloud-native.slack.com/archives/C167KFM6C/p1706219700271849

There's a scenario where, if the WAL watcher falls behind after startup, it becomes unable to catch up.

Specifically, the `lastSegment` variable in Run in watcher.go is never updated after the watcher starts, so if we've ever been caught up to the latest WAL segment in a Prometheus process lifetime, even if we subsequently fell behind again, the `tail` parameter will be set to true: https://github.com/prometheus/prometheus/blob/998fafe679b7e02b6a786672ade256aa714e5616/tsdb/wlog/watcher.go#L301-L303
If `tail` is true, we'll only actually perform a read from the current WAL segment when we get a Notify event for a write, or when the every-15-second read timeout fires: https://github.com/prometheus/prometheus/blob/998fafe679b7e02b6a786672ade256aa714e5616/tsdb/wlog/watcher.go#L478-L487

If Notify events are infrequent, e.g. if they occur approximately once per new WAL segment, and the rate of new samples & new segments is roughly constant, this will mean our rate of reading old records will be roughly capped at the rate of new WAL segments being written, and so we'll gradually keep falling behind. We appear to have seen this behavior in production repeatedly--specifically the symptom where, when the WAL watcher falls behind, it gets stuck well below the throughput that it's able to achieve at startup.

This is similar to https://github.com/prometheus/prometheus/issues/13111 but isn't limited to the use of `agent` mode (although it does require a more specific load pattern).

I suspect a fix might be as simple as setting `lastSegment = max(lastSegment, currentSegment)` here: https://github.com/prometheus/prometheus/blob/998fafe679b7e02b6a786672ade256aa714e5616/tsdb/wlog/watcher.go#L308-L309
... but that might have wider implications of which I'm not aware.

### What did you expect to see?

I expected that the WAL watcher used by remote write would be able to catch up from a backlog that occurs between restarts (e.g. due to a blip on the receiver side) as quickly as it is able to catch up from a backlog at startup.

### What did you see instead? Under which circumstances?

The WAL watcher throughput becomes a bottleneck on remote write and the backlog grows indefinitely.

### System information

Linux 5.15.109+ x86_64

### Prometheus version

```text
prometheus, version 2.48.0 (branch: HEAD, revision: 6d80b30990bc297d95b5c844e118c4011fad8054)
  build user:       root@26117804242c
  build date:       20231116-04:35:21
  go version:       go1.21.4
  platform:         linux/amd64
  tags:             netgo,builtinassets,stringlabels
```

**Comment by bboreham** [comment]
There is some debate at https://github.com/prometheus/prometheus/pull/13583#discussion_r1668166164 over how this symptom could have been observed.

> this will mean our rate of reading old records will be roughly capped at the rate of new WAL segments being written, and so we'll gradually keep falling behind

Any time a whole new segment is available, the current segment will be read to the end by this code:

https://github.com/prometheus/prometheus/blob/814b920e8a6345d35712b5857ebd4cb5e90fc107/tsdb/wlog/watcher.go#L447-L457

which fires every 100ms.

I can believe that the reader remains an entire segment behind, i.e. "rate of reading old _segments_ will be capped at the rate of new WAL segments being written", but this wouldn't make the backlog grow.
Is it possible that is what you observed?

**Comment by djudd** [comment]
> rate of reading old segments will be capped at the rate of new WAL segments being written

Yes, I think that's right. I think "rate of reading old records" wasn't intended to be that precise.

> this wouldn't make the backlog grow

It's been a while, but IIRC, in steady-state we were mostly just keeping a constant lag, rather than falling further behind. However, periodically we'd get unlucky and we'd fall behind by an extra segment due to a load spike or something, so over a period of hours the lag would keep getting slowly worse in a series of small step changes. Does that make sense?

**Comment by cstyan** [comment]
> It's been a while, but IIRC, in steady-state we were mostly just keeping a constant lag, rather than falling further behind. However, periodically we'd get unlucky and we'd fall behind by an extra segment due to a load spike or something, so over a period of hours the lag would keep getting slowly worse in a series of small step changes. Does that make sense?

:thinking: I can see how this would happen, without the change from https://github.com/prometheus/prometheus/pull/13583 we'd be waiting for the new segment to be created, at which point we'd try to read and send the whole segment. IIRC the max size for a segment is 128MB. That would explain the consistent state of always being a segment or so behind. If there was sufficient latency for a period during which we're trying to read and send that whole segment, and your scrape throughput is also sufficiently high enough to also mean a new full segment was written to disk during that time, you could potentially fall multiple segments behind over a long period of time.

@djudd have you not noticed any large chunks of missing data since upgrading post https://github.com/prometheus/prometheus/pull/13583 ? That essentially introduced a bug where Prometheus would "catch up" by actually dropping all samples between `current segment RW is reading` and `newest segment` when it notices it's behind.

**Comment by djudd** [comment]
> you could potentially fall multiple segments behind over a long period of time

@cstyan yes, but just to make sure we're on the same page, this is something we saw after an initial one-off event (e.g. a crash) saw us initially fall several segments behind. I'm not sure we ever saw this problem in isolation.

> have you not noticed any large chunks of missing data

We have seen some missing data actually at least once, and I'm not sure we ever tracked down what happened-seems like it could be this.

**Comment by cstyan** [comment]
> @cstyan yes, but just to make sure we're on the same page, this is something we saw after an initial one-off event (e.g. a crash) saw us initially fall several segments behind. I'm not sure we ever saw this problem in isolation.

Yes, a crash/OOM kill is one of the most common ways to start falling behind.


> We have seen some missing data actually at least once, and I'm not sure we ever tracked down what happened-seems like it could be this.

If you look at the `prometheus_wal_watcher_current_segment` metrics you'd likely see it increase by more than 1 in a short period of time right before the period you have missing data in your remote storage.

> (FWIW, for our most critical use cases I think we'd generally prefer to lose a chunk of historical data than to stay behind for a prolonged period of time, because the latter breaks all Prom-based alerts. But obviously we'd prefer not to make that tradeoff.)

This is technically still an option via the `sample_age_limit` in remote write queue [config](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#remote_write).

**Comment by bboreham** [comment]
> This is technically still an option via the sample_age_limit in remote write queue [config](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#remote_write).

Interested why you say "technically" - that strikes me as a very good suggestion. Am I missing some nuance?

`sample_age_limit` was introduced in Prometheus 2.50.
