### ISSUE TITLE
nhcb: add optional field to prometheus remote write protobuf definition for custom bucket specification

### ISSUE THREAD

**Issue by krajorama** [prometheus/prometheus#13475]
### Proposal

Related to https://github.com/prometheus/proposals/pull/31

The histogram message type should have a new optional field that is a list of float64 values. These are to describe the custom bucket upper boundaries (excl. +Inf which is implicit). So basically encode what we currently put in the `le` label.

- [ ] Add `custom_bounds` field to remote write specification 2.0 : [types.proto](https://github.com/prometheus/prometheus/blob/remote-write-2.0/prompb/write/v2/types.proto).
   ```
     // custom_bounds specify upper bounds for the buckets
     // with arbitrary widths for this histogram. The upper bounds are inclusive (following `le` label semantics),
     // however, the previous bound specifies the lower bound (exclusive), making the bucket count
     // non-cumulative (as opposed to `le` semantics in the past).
     // Bounds have to be monotonically increasing.
     // The last element is also a lower bound for the implicit +Inf bucket (overflow buckets).
     // The first element is the upper inclusive boundary for the first bucket,
     // which implicitly has a lower inclusive bound of -Inf.
     repeated double custom_bounds =  16;
   ```
- [ ] Update the note of the field `schema` to allow schema number 127. And also explain that in that case `custom_bounds` is taken into account for interpreting the custom buckets (stored in `positive_spans`, `positive_deltas`, `positive_counts`). Furthermore `negative_spans`, `negative_deltas`, `negative_counts`, `zero_count` and `zero_threshold` should be ignored.
- [ ] Test what happens to Prometheus if we send a remote write request with custom bucket definition and schema value of 127 - Prometheus should gracefully reject the sample currently (regardless of native histogram feature toggle!)
- [ ] Test the the field is truly optional and if not set, causes no problem.

This issue should target remote write 2.0.

**Comment by bwplotka** [comment]
We can do that for Prometheus Remote Write 2.0 only. He is a feature branch with proto: https://github.com/prometheus/prometheus/blob/remote-write-2.0/prompb/write/v2/types.proto#L84

**Comment by krajorama** [comment]
Technically we can as native histograms are an experimental feature still. But I'm ok with rebasing on top of remote-write-2.0 branch as well

**Comment by linasm** [comment]
What will be the semantics of `Histogram.reset_hint` protobuf field in this new use case?

**Comment by beorn7** [comment]
> What will be the semantics of `Histogram.reset_hint` protobuf field in this new use case?

There should be no change in semantics. What makes you think there would be one?

**Comment by linasm** [comment]
> > What will be the semantics of `Histogram.reset_hint` protobuf field in this new use case?
> 
> There should be no change in semantics. What makes you think there would be one?

Just wanted to know, without any opinions on my own.

I guess in this case, for this new internal representation of classic histogram, a change in behaviour (vs. old school bucket storage in individual series) would be that reset detection would be done at a level of histogram as a whole (and not on the individual buckets like before)? Which I think would make sense and not be a significant behaviour change in practice (but is probably worth a mention in the docs).

**Comment by beorn7** [comment]
> I guess in this case, for this new internal representation of classic histogram, a change in behaviour (vs. old school bucket storage in individual series) would be that reset detection would be done at a level of histogram as a whole (and not on the individual buckets like before)? Which I think would make sense and not be a significant behaviour change in practice (but is probably worth a mention in the docs).

I see. Yes, in the (pathological) case that a counter reset is only visible in some buckets, the NHCB approach would "fix" the previously "wrong" behavior.  So you could say that's a change of semantics. You could also say that it reduced the error rate of unidentified counter resets.

**Comment by krajorama** [comment]
Agreed as discussed in CNCF slack: https://cloud-native.slack.com/archives/C02KR205UMU/p1707301006347199

**Comment by krajorama** [comment]
Added in remote write 2.0.
