### ISSUE TITLE
nhcb: unit test framework to automatically generate custom histogram series from classic histogram series

### ISSUE THREAD

**Issue by krajorama** [prometheus/prometheus#13508]
### Proposal

Depends on:
#13486 
#13487 

If the unit test has this kind of definition:
```
load 5m
	testhistogram2_bucket{le="0"}	 0+0x10
	testhistogram2_bucket{le="2"}	 0+1x10
	testhistogram2_bucket{le="4"}    0+2x10
	testhistogram2_bucket{le="6"}	 0+3x10
	testhistogram2_bucket{le="+Inf"} 0+3x10
	testhistogram2_count{} 0+3x10
        testhistogram2_sum{} 0+3x50
```

Then automatically create and store a custom histogram series called `testhistogram2`.

**Comment by beorn7** [comment]
Yes, that is a good idea. Maybe there should be some parameter to (de-)activate the behavior, but we can try without it and see if any problems are happening.

A scenario could be if somebody wants to create a normal native histogram called `testhistogram2` in the same test as the classic histogram above. Maybe we only create the NHCB implicitly if there is no series with the corresponding name already?

**Comment by krajorama** [comment]
completed
