### ISSUE TITLE
what is the storage model for prometheus

### ISSUE THREAD

**Issue by andyxning** [prometheus/prometheus#1353]
I come into `prometheus` from a ppt about Golang. 
After reading some introduction info about it,  i am now wondering the storage model for `prometheus`.
I know that:
*  `Graphite` uses `whisper` 
* `Cacti` uses `RRD`
* ` OpenTSDB` uses `HBase`   
How does the storage model for `prometheus` and any doc or code for it?

**Comment by fabxc** [comment]
We are using our own storage layer, which has a very high throughput but is not intended for long-term storage.
Prometheus supports streaming metrics into InfluxDB or Graphite upon ingestion. This is just experimental though and without read-back support.

There's currently no white-paper documentation on our storage model.
Here are some slides that might help a bit but are lacking text for a good understanding without the surrounding talk: http://www.slideshare.net/FabianReinartz/prometheus-storage-57557499

I would be interested in that Go presentation that referenced Prometheus. Do you have a link?

**Comment by andyxning** [comment]
sorry for the actual pdf that reference Prometheus. Here is a [blog](http://peter.bourgon.org/go-in-production) that deeply present the corresponding pdf. And the reference section is [here](http://peter.bourgon.org/go-in-production/#logging-and-telemetry)
