### ISSUE TITLE
UTF-8: Update typescript parser to support new syntax

### ISSUE THREAD

**Issue by ywwg** [prometheus/prometheus#13564]
### Proposal

https://github.com/prometheus/prometheus/blob/main/web/ui/module/codemirror-promql/src/parser/parser.ts

Part of https://github.com/prometheus/prometheus/issues/13095, we will need to update the typescript parser so that it understands the new query syntax. This would be a great issue for an outside contributor!

**Comment by NeerajGartia21** [comment]
@ywwg I would like to work on this. Can you please assign it to me?

**Comment by ywwg** [comment]
Are you in the CNCF slack? https://communityinviter.com/apps/cloud-native/cncf
We can discuss the work in the #prometheus-utf8-dev channel there

**Comment by NeerajGartia21** [comment]
Cool, I'll ask there !!

**Comment by ywwg** [comment]
fixed in https://github.com/prometheus/prometheus/pull/13590
