### ISSUE TITLE
Variant of `increase` function that assumes uninitialized counters start at zero 0, like VictoriaMetric's increase_pure

### ISSUE THREAD

**Issue by swar8080** [prometheus/prometheus#13570]
### Proposal

Hello, would a function like VictoriaMetric's [increase_pure](https://docs.victoriametrics.com/metricsql/#increase_pure) make sense to implement for PromQL?

It seems to solve the problem discussed in https://github.com/prometheus/prometheus/issues/1673 and would be easier to adopt than the upcoming [created timestamp feature](https://github.com/prometheus/proposals/pull/29) 

Put another way, our use-case is we want to fire an alert in grafana anytime a prometheus counter is increased. The counter has many dynamic labels so pre-initializing the counter to zero is not an option. Additionally, we would like to sum the counter by labels, and calculate the increase for each of those sums. For example, a counter tracking when an error occurs, summed by the `customer` label, which would fire a separate alert per customer if their error count increases. Using `rate` and `increase` would miss firing the alert on the first increment of the counter after the application instance starts.

I'm guessing there's some edge cases where `increase_pure` understates the counter and causes an alert to misfire, but that's much better than missing a legitimate reason to alert.

I've found some partial workarounds, but they don't allow aggregating by label and are complex for people new to promql. My company is used to delta temporality metric systems like statsd where setting-up these types of alerts is trivial. Unless I missed some easier workaround, this could be a painful part of our migration to prometheus

**Comment by beorn7** [comment]
With the current work on created-at timestamps (/cc @ArthurSens ), I believe this problem will be addressed in a much superior way than adding yet another confusing PromQL function to a set of functions that are already confusing.

**Comment by ArthurSens** [comment]
The 2.50.0 should come pretty soon with initial support for created timestamps. Although support is only coming for the protobuf format, I'm already working on other formats, e.g. OpenMetrics text https://github.com/prometheus/prometheus/pull/13506.

You mention that adoption of created timestamps might be difficult, do you mind elaborating on that? Happy to make things easier, we just need feedback :)

**Comment by beorn7** [comment]
As this is a problem that we have discussed literally from the very early days of Prometheus, and we have deliberately avoided assuming a zero point that isn't really in the data all the time, I'm very confident that we won't change course now, when a suitable solution (in the form of taking the created-at timestamp into account) is very close.

Therefore, I close this issue. But feel free to continue the conversation, here or on other community channels.
