### ISSUE TITLE
Prometheus built from source in directory not called "prometheus" doesn't work

### ISSUE THREAD

**Issue by aknuds1** [prometheus/prometheus#13572]
### What did you do?

Apparently, Prometheus built from source in a directory called something else than "prometheus", has the wrong assets path built in. How to reproduce:

```console
$ git clone https://github.com/prometheus/prometheus.git something-prometheus
$ cd something-prometheus
$ make build
$ touch prometheus.yml
$ ./prometheus &
$ curl -L http://localhost:9090
Error opening React index.html: open static/react/index.html: no such file or directory
```

### What did you expect to see?

I expected to get a functioning Prometheus home page.

### What did you see instead? Under which circumstances?

I instead saw the following error:

```
Error opening React index.html: open static/react/index.html: no such file or directory
```

### System information

Linux 6.7.4-arch1-1 x86_64

### Prometheus version

```text
prometheus, version 2.49.1 (branch: feat/info-function, revision: 358d54a904804ea77b9f06995acf320da110db92)
  build user:       arve@archlinux
  build date:       20240212-11:13:04
  go version:       go1.22.0
  platform:         linux/amd64
  tags:             unknown
```

**Comment by beorn7** [comment]
This seems to be in the React part. @Nexucis could you have a look?

**Comment by Nexucis** [comment]
Hello,

I have tried to reproduce the issue but unfortunately I wasn't able to...

Here my setup:

```bash
$>  go version
go version go1.21.6 darwin/arm64
```

```bash
$> npm version
{
  npm: '10.2.4',
  node: '21.5.0',
  acorn: '8.11.2',
  ada: '2.7.4',
  ares: '1.24.0',
  base64: '0.5.1',
  brotli: '1.1.0',
  cjs_module_lexer: '1.2.2',
  cldr: '43.1',
  icu: '73.2',
  llhttp: '9.1.3',
  modules: '120',
  napi: '9',
  nghttp2: '1.58.0',
  openssl: '3.2.0',
  simdjson: '3.6.2',
  simdutf: '4.0.4',
  tz: '2023c',
  undici: '5.28.2',
  unicode: '15.0',
  uv: '1.47.0',
  uvwasi: '0.0.19',
  v8: '11.8.172.17-node.18',
  zlib: '1.2.11'
}
```

I'm wondering if the issue is go v1.22 but I wouldn't see why it has this effect

**Comment by Nexucis** [comment]
what is your nodejs and npm version @aknuds1 ?

**Comment by aknuds1** [comment]
@Nexucis thanks for trying to reproduce. I have Node v20.10.0 and NPM v10.2.3. I found I couldn't reproduce the problem on my MacBook (Go v1.22.0, Node v21.6.2, NPM v10.2.4), so it's not straightforward apparently.

**Comment by Nexucis** [comment]
ah that's interesting, weird but interesting. Thank you for trying on another OS.

Is it possible on your archilinux to upgrade nodejs ? Just to evict the possibility it's coming from that

**Comment by aknuds1** [comment]
> Is it possible on your archilinux to upgrade nodejs?

I will try.

**Comment by aknuds1** [comment]
@Nexucis I installed Node v21.6.2, it doesn't fix the problem.

**Comment by Nexucis** [comment]
meeh it would been so simpler if it was nodejs :/

**Comment by Nexucis** [comment]
thanks for trying @aknuds1 !

**Comment by sababa976** [comment]
is there any solution to this problem?
i also ran into the same error message

**Comment by aknuds1** [comment]
I'm not aware of any solution yet :(

**Comment by aknuds1** [comment]
The bug appears to have been fixed! I'm guessing through the new React UI that was merged in the meantime <3
