### ISSUE TITLE
Promote new-service-discovery-manager

### ISSUE THREAD

**Issue by machine424** [prometheus/prometheus#13609]
### Proposal

`new-service-discovery-manager` has been introduced in https://github.com/prometheus/prometheus/pull/9349 and https://github.com/prometheus/prometheus/pull/9537, it's hidden behind `--enable-feature=new-service-discovery-manager`.

I expect this new manager to be widely adopted by third parties (consumers that use prometheus as a library), as the default manager has been relocated to `github.com/prometheus/prometheus/discovery/legacymanager`.  I don't think they transitioned or have been using a "legacy" dependency without raising any concerns :)

**The default legacy manager has known limitations/bugs:**

- It recreates/discovers targets from scratch on each config apply (/-/reload). In some setups, this "causes unnecessary scrape disruptions": https://github.com/prometheus/prometheus/issues/9321. This limitation was the driving force behind the changes that resulted in the new manager.
- With file SD, targets from a deleted file are not dropped if a reload is triggered just after the deletion https://github.com/prometheus/prometheus/issues/12007.

**Bugs that affect both managers:**

- Receivers are not notified about dropped targets: https://github.com/prometheus/prometheus/issues/12858 - https://github.com/prometheus/prometheus/pull/13147 suggests a fix for the new manager only.
- The `targets` map is leaking: https://github.com/prometheus/prometheus/issues/12436 - @machine424 has an idea for a fix for the new manager that needs https://github.com/prometheus/prometheus/pull/13147

Considering all these factors, let's discuss the `new-service-discovery-manager` promotion.

**Comment by machine424** [comment]
Fare enough, Should we add the known bugs https://github.com/prometheus/prometheus/issues/12858 and https://github.com/prometheus/prometheus/issues/12436 to the milestone as well for better visibility?

**Comment by bboreham** [comment]
Hello from the bug-scrub! 
@jan--f please can you clarify whether this is or is not expected to happen as part of Prometheus 3 ?

**Comment by jan--f** [comment]
yes this would be great to have in 3.0. Ideally along with the fixes @machine424 has proposed for #12858 and #12436.

**Comment by jan--f** [comment]
@machine424 Is there anything else to do here? Iiuc this issue can be closed, right?

**Comment by machine424** [comment]
You're right, don't know why this wasn't done by gh, maybe bcz of the force push.
