### ISSUE TITLE
confuse of function quantile

### ISSUE THREAD

**Issue by wuyueandrew** [prometheus/prometheus#13618]
### What did you do?

Function `quantile` defined in promql/quantile.go
`rank := q * (n - 1)` this line of code, is there any reason of n - 1, why not q * n -1 .

### What did you see instead? Under which circumstances?

no

**Comment by roidelapluie** [comment]
In the `quantile` function within `promql/quantile.go`, the `rank := q * (n - 1)` calculation adjusts for the way slices are indexed in go, starting from zero. Subtracting 1 after the multiplication (`q * n - 1`) would incorrectly shift the rank.
