### ISSUE TITLE
Publish exposition format as an IETF standard

### ISSUE THREAD

**Issue by SuperQ** [prometheus/prometheus#1361]
It would be interesting/good to write up the exposition format as an IETF RFC standard. This would allow more adoption by "traditional" companies since they can reference a standard for both implementation and marketing "We support metrics via RFC XXXX".

**Comment by beorn7** [comment]
We have a number of issues around the exposition format by now. How about moving them all into the docs repo, with a dedicated label? We should have clarity on the spec before starting any work, and the spec lives in the docs repo. So it might be the best point to track those issues.

**Comment by RichiH** [comment]
Sounds good to me; as soon as they are done, I can start pouring it all into the ID. Maybe the specs could even be replaced with a link to the RFC after it's been published. Just keep in mind that this sets the exposition format in stone for a certain time.

**Comment by beorn7** [comment]
Even more a reason to get clarity about changes we might want to get in.

I'll go ahead and start creating issues about topics we discussed before.

**Comment by beorn7** [comment]
Moved to https://github.com/prometheus/docs/issues/541
