### ISSUE TITLE
Ignore kubernetes services

### ISSUE THREAD

**Issue by vic3lord** [prometheus/prometheus#1364]
Hello team,

There are lots of services on kubernetes cluster that don't support prometheus metrics,
Is there any option to make a list of services I don't need prometheus to query?

Thanks for this awesome project.

**Comment by jimmidyson** [comment]
You can do this via relabelling. See https://github.com/prometheus/prometheus/blob/master/documentation/examples/prometheus-kubernetes.yml#L53-L56 for an example. What this is doing is only `keep`ing Kubernetes services that are annotated with `prometheus.io/scrape=true`. I find it works best to whitelist services in this way.

**Comment by vic3lord** [comment]
Thanks, it sure seems to solve my problem...
