### ISSUE TITLE
Hyper-Threading off causes CPU statistics err

### ISSUE THREAD

**Issue by Patrick08T** [prometheus/prometheus#13700]
### What did you do?

**Environment:**
Linux Version: 3.10.0-1160.31.1.el7.x86_64
Prometheus: 2.28.1
Query Log: `(1 - avg(rate(node_cpu_seconds_total{hostName=~"xxx",mode="idle"}[30s])) by (hostName))*100`

**Problem:**
When the promethus was running all the time, I turned off the Hyper-Threading and saw the cpu go from 0 to 44. 

### What did you expect to see?

I don't think anything's gonna change.

**Comment by machine424** [comment]
Prometheus doesn’t expose node_cpu_seconds_total it only scrapes it.

**Comment by beorn7** [comment]
Yeah, that would be a question for https://github.com/prometheus/node_exporter . Although I suspect that node_exporter just passes through the kernel metrics, so maybe the explanation is deep down somewhere there in the kernel.
