### ISSUE TITLE
CI: flaky TestOpenstackSDInstanceRefresh

### ISSUE THREAD

**Issue by bboreham** [prometheus/prometheus#13723]
### What did you do?

Failed at https://github.com/prometheus/prometheus/actions/runs/8177383653/job/22358925757?pr=13716

### Logs

```text
--- FAIL: TestOpenstackSDInstanceRefresh (0.01s)
    instance_test.go:63: 
        	Error Trace:	/__w/prometheus/prometheus/discovery/openstack/instance_test.go:63
        	Error:      	Received unexpected error:
        	            	context canceled
        	Test:       	TestOpenstackSDInstanceRefresh
FAIL
FAIL	github.com/prometheus/prometheus/discovery/openstack	0.034s
```

**Comment by bboreham** [comment]
`TestOpenstackSDInstanceRefresh` passes `context.Background` which cannot be cancelled, so I'm a little unclear how this error can arise.

@simonpasquier apparently you added Context to this function; can you see what is wrong?

**Comment by machine424** [comment]
I see your PR also updates the OS client => `github.com/gophercloud/gophercloud v1.10.0`, I think it's the same problem than https://github.com/gophercloud/gophercloud/issues/2969 that was fixed, we should try upgrading to the latest.

> TestOpenstackSDInstanceRefresh passes context.Background which cannot be cancelled, so I'm a little unclear how this error can arise.

It doesn't mean the receiving functions will use the passed context throughout, if they create their own cancellable context and if they forward its error and we don't wrap it, we can end up with a plain `context canceled`

**Comment by bboreham** [comment]
For #13716 I wound back the `gophercloud` update.

**Comment by machine424** [comment]
The issue was fixed in `github.com/gophercloud/gophercloud v1.11.0` https://github.com/gophercloud/gophercloud/releases/tag/v1.11.0
