### ISSUE TITLE
Support inline `tls_config` files

### ISSUE THREAD

**Issue by matthiasr** [prometheus/prometheus#1377]
Currently, `tls_config` only accepts files. It is sometimes easier to have a single, self-contained configuration file (or have it composed by config management, if you have that) than littering auxiliary files somewhere.

I would propose a syntax like

``` yaml
tls_config:
  ca: |
    -----BEGIN CERTIFICATE-----
    …
    -----END CERTIFICATE-----
```

and so on. Defining both file and literal should be an error (or warning, and just pick one or the other).

**Comment by gouthamve** [comment]
We want to be consistent everywhere and the new node_exporter TLS config file also accepts just file paths. Closing this as we would like to have one way to do things and we haven't had a request for it after this issue.
