### ISSUE TITLE
Prometheus skipping scrapes every 2 hours

### ISSUE THREAD

**Issue by anubshar1** [prometheus/prometheus#13784]
### What did you do?

We have a reasonably big instance of Prometheus that scrapes around 26K targets (all node exporter), and roughly contains 22.5M timeseries in its head. These targets are discovered via service discovery and the scrape interval is set to 30s.

We are seeing that every 2 hours, the prometheus instance totally skips scraping a subset of the targets it was supposed to scrape every 30s and for such targets the duration between two subsequent scrapes goes as high as > 100s. This behaviour is evident when we plot the 99th percentile of the `prometheus_target_interval_length_seconds` metric over a period of time.

![Screenshot 2024-03-18 at 12 04 24](https://github.com/prometheus/prometheus/assets/163815582/44d5ea4b-6b20-43ea-8040-6bc4c2d76e25)

Interestingly, it then seems like prometheus is trying to make up for these lost scrapes by scraping them at an interval of much less than 30s (sometimes two scrapes are only 5s apart).

![Screenshot 2024-03-18 at 12 04 45](https://github.com/prometheus/prometheus/assets/163815582/88684bcc-c749-4115-9a64-eb0f8ce8a605)

Just to avoid any confusions, there are no scrape timeouts happening here. It's that prometheus is not even trying to scrape some set of targets for a brief period of time, and then trying to makeup for that by having two scrapes very close to each other.

<img width="1672" alt="Screenshot 2024-03-18 at 14 30 13" src="https://github.com/prometheus/prometheus/assets/163815582/05419c17-cf6e-483e-94db-bccadda98d17">

Also, this seems to be happening to most of our Prometheus instances (shards). These instances are deployed across two datacenters and since the behavior is reproducible in multiple instances in both the datacenters, we think its unlikely to be an infrastructure issue. The machines that run these Prometheus instances are physical machines with 40 cores, 512G RAM and local SSD disks and we do not see any kind of resource crunch on these machines. We discovered this issue recently but we are seeing this pattern for the last 3 months (don't have data before that).

Please let us know if we should provide more info to help debug this issue. Thank you!

### What did you expect to see?

The time interval between two scrapes should remain consistent as per the configuration settings, without any unexpected spikes.

### What did you see instead? Under which circumstances?

Every 2 hours, there is an unexpected and significant increase in the time interval between two scrapes, as evidenced by the spike in the `prometheus_target_interval_length_seconds` metric. 

### System information

Linux 3.10.0-1160.105.1.el7.x86_64 x86_64

### Prometheus version

```text
prometheus, version 2.46.0 (branch: HEAD, revision: cbb69e51423565ec40f46e74f4ff2dbb3b7fb4f0)
  build user:       root@42454fc0f41e
  build date:       20230725-12:31:24
  go version:       go1.20.6
  platform:         linux/amd64
  tags:             netgo,builtinassets,stringlabels
```

**Comment by prymitive** [comment]
Sounds similar to #10377. You might want to try upgrading to at least [v2.47.0](https://github.com/prometheus/prometheus/releases/tag/v2.47.0) as it contains a fix for that issue.

**Comment by anubshar1** [comment]
Upgrading to v2.47.0 indeed fixed the issue. Thank you @prymitive!
