### ISSUE TITLE
Remove `init()` from discovery/metrics.go

### ISSUE THREAD

**Issue by bjschafer** [prometheus/prometheus#13788]
### What did you do?

Imported `github.com/prometheus/prometheus/model/rulefmt` to perform rule validation, in a project that's also using `k8s.io/client-go` and expects to register its own workqueue metrics.

Instead, because of a dependency chain, `github.com/prometheus/prometheus/discovery` ends up imported, and because it has an `init()` function which registers these metrics, it overwrites the metrics I'm using.

### What did you expect to see?

Valid e.g. `workqueue_depth` metrics from my controller.

### What did you see instead? Under which circumstances?

No e.g. `workqueue_depth` metrics from my controller, as they get stomped on by the discovery package.

**Comment by bboreham** [comment]
Prometheus is not designed for use as a library. Any difficulties you have using it as such are not an issue for Prometheus.

You are welcome to propose a PR which makes things easier for you, but I will close this.
