### ISSUE TITLE
Proposal: Add support `Nacos` SD config

### ISSUE THREAD

**Issue by dongjiang1989** [prometheus/prometheus#13801]
### Proposal

Add support [Nacos](https://nacos.io/en/) SD config.

Prometheus will periodically check the REST endpoint and create a target for every app instance.

The following meta labels are available on targets during relabeling:

- `__meta_nacos_app_name`: the name of the app
- `__meta_nacos_app_instance_id`: the ID of the app instance
- `__meta_nacos_app_instance_hostname`: the hostname of the instance
- `__meta_nacos_app_instance_homepage_url`: the homepage url of the app instance
- `__meta_nacos_app_instance_statuspage_url`: the status page url of the app instance
- `__meta_nacos_app_instance_healthcheck_url`: the health check url of the app instance
- `__meta_nacos_app_instance_ip_addr`: the IP address of the app instance
- `__meta_nacos_app_instance_vip_address`: the VIP address of the app instance
- `__meta_nacos_app_instance_secure_vip_address`: the secure VIP address of the app instance
- `__meta_nacos_app_instance_status`: the status of the app instance
- `__meta_nacos_app_instance_port`: the port of the app instance
- `__meta_nacos_app_instance_port_enabled`: the port enabled of the app instance
- `__meta_nacos_app_instance_secure_port:` the secure port address of the app instance
- `__meta_nacos_app_instance_secure_port_enabled`: the secure port of the app instance
- `__meta_nacos_app_instance_country_id`: the country ID of the app instance
- `__meta_nacos_app_instance_metadata_<metadataname>`: app instance metadata
- `__meta_nacos_app_instance_datacenterinfo_name`: the datacenter name of the app instance
- `__meta_nacos_app_instance_datacenterinfo_<metadataname>`: the datacenter metadata

**Comment by roidelapluie** [comment]
HTTP SD support was added in version 2.2.0 of Nacos: https://nacos.io/zh-cn/blog/2.2.0-release.html
