### ISSUE TITLE
Filter not working

### ISSUE THREAD

**Issue by jzielke84** [prometheus/prometheus#13829]
### What did you do?

I have the following metric showing in prometheus by using the bird exporter:
```
bird_protocol_up{env="prd", export_filter="(unnamed)", import_filter="(unnamed)", instance="vmffkbuen01.ffkbu.lan:9399", ip_version="4", job="node", name="ffwiel", proto="BGP", server="vmffkbusv01", state="Active Socket: No route to host"}
```
However, then I copy the exact line into into the query box, no results are shown.

### What did you expect to see?

The line prometheus shows among all other metrics.

### What did you see instead? Under which circumstances?

No results

### System information

Linux 6.1.0-18-amd64 x86_64

### Prometheus version

```text
prometheus, version 2.50.1 (branch: HEAD, revision: 8c9b0285360a0b6288d76214a75ce3025bce4050)
  build user:       root@6213bb3ee580
  build date:       20240226-11:36:26
  go version:       go1.21.7
  platform:         linux/amd64
  tags:             netgo,builtinassets,stringlabels
```

**Comment by bboreham** [comment]
> instance="vmffkbuen01.ffkbu.lan:9399", ip_version="4", job="node"

Prometheus adds the `instance` and `job` labels itself, and may not come up with the exact same spelling.
The values from your exporter will be stored as `exported_instance` and `exported_job`.
Try removing these parts from your query, and see if it works.

You ignored many requests in the issue template, which makes it harder to help you.
I will close this as the information supplied does not indicate a bug.

**Comment by jzielke84** [comment]
@bboreham  The values I showed you are from within prometheus. They are the actual data which prometheus shows me. What do you mean by "may not come up with the exact same spelling"?

**Comment by bboreham** [comment]
OK I misunderstood what your first line showed.

Prometheus is fine with spaces in label values.

Are you doing range queries or instant queries?  Maybe the data varies from time to time?

Perhaps some screen grabs would make the situation clearer.

**Comment by jzielke84** [comment]
<img width="1800" alt="Screenshot 2024-03-31 at 17 42 02" src="https://github.com/prometheus/prometheus/assets/13448042/fc84b534-30ab-4b89-822a-d3c653852480">
<img width="1774" alt="Screenshot 2024-03-31 at 17 42 58" src="https://github.com/prometheus/prometheus/assets/13448042/8f46a28f-53a0-49cf-9182-41181d36dd94">

**Comment by bboreham** [comment]
Thanks for that. To rule out the "data varies from time to time" explanation, can you please try again with a value in the "Evaluation time" box, e.g. "2024-04-01 06:00:00".

As a check, I found a series in a publicly-accessible Prometheus that has a space in a label:
http://prombench.prometheus.io/prometheus-meta/graph?g0.expr=kubernetes_build_info%7Bgo_version%3D%22go1.20.10%20X%3Aboringcrypto%22%7D&g0.tab=1&g0.stacked=0&g0.show_exemplars=0&g0.range_input=1h&g0.end_input=2024-04-01%2009%3A00%3A00&g0.moment_input=2024-04-01%2009%3A00%3A00

It is possible that what looks like a space in your data is not actually a space.  You'd need to examine the data at a lower level to detect that, e.g. using `curl` to hit the API directly like this:
```
curl 'http://prombench.prometheus.io/prometheus-meta/api/v1/query?query=kubernetes_build_info%7Bgo_version%3D%22go1.20.10+X%3Aboringcrypto%22%7D&time=1711962000' | od -c
```
