### ISSUE TITLE
Prom stops updating subset of metrics after dovecot server is restarted

### ISSUE THREAD

**Issue by matejzero** [prometheus/prometheus#13821]
### What did you do?

We are running dovecot server and it's exposing native [OpenMetrics metrics ](https://doc.dovecot.org/configuration_manual/stats/openmetrics/). We have noticed that we can collect metrics without a problem, until dovecot server is restarted. After that, some metrics stops updating (we just get a flatline). Metric in question is named `dovecot_mail_delivery_count` and is a part of histogram metric (though it's type is counter).

### What did you expect to see?

I expected my metrics to be scraped after dovecot restart.

### What did you see instead? Under which circumstances?

The only way to get prom back to scraping all metrics is to restart prometheus server. After that, everything works until dovecot is restarted again.

If I curl dovecot directly from my prom server, I can see metric increasing:
```
[root@prom01 ~]# curl  -s http://dovecot.mail.int:9119/metrics  |grep dovecot_mail_delivery_count
dovecot_mail_delivery_count 5898
[root@prom01 ~]# curl  -s http://dovecot.mail.int:9119/metrics  |grep dovecot_mail_delivery_count
dovecot_mail_delivery_count 5901
[root@prom01 ~]# curl  -s http://dovecot.mail.int:9119/metrics  |grep dovecot_mail_delivery_count
dovecot_mail_delivery_count 5949
```

If I check directly, I get 501 metrics:
```
$ curl -s http://dovecot.mail.int:9119/metrics  | grep -v "#" | wc -l
501
```

When running `scrape_samples_scraped{instance="dovecot.mail.int:9119"}` on 2 prom servers (one working (fresh restart) and one not working), I get the following metrocs:
```
- working prom: scrape_samples_scraped{instance="dovecot.mail.int:9119"} 501
- non-working prom: scrape_samples_scraped{instance="dovecot.mail.int:9119"} 457
```

I have enabled debug log in prometheus and I get no errors or anything that would explain that is happening.

Any ideas what's happening here and how to debug?

### System information

Linux 4.18.0-477.27.2.el8_8.x86_64 x86_64

### Prometheus version

```text
prometheus, version 2.49.1 (branch: HEAD, revision: 43e14844a33b65e2a396e3944272af8b3a494071)
  build user:       root@6d5f4c649d25
  build date:       20240115-16:58:43
  go version:       go1.21.6
  platform:         linux/amd64
  tags:             netgo,builtinassets,stringlabels
```

**Comment by dgl** [comment]
We discussed this on slack a bit, curl -v shows it is sending an openmetrics content type:

```
< HTTP/1.1 200 OK
< Date: Thu, 21 Mar 2024 08:37:24 GMT
< Transfer-Encoding: chunked
< Content-Type: application/openmetrics-text; version=0.0.1; charset=utf-8
```

Could you confirm which version of dovecot this is? There is a mentioned change in 2.3.14 for histogram metrics.

**Comment by matejzero** [comment]
Version we are using is dovecot-2.3.19.1-2.x86_64

**Comment by bboreham** [comment]
I'm struggling to think how we can debug this without access to a Dovecot server.  Is it something that one can run up for a quick test, e.g. in a container, and still reproduce the issue?

Could you supply the complete result of `curl /metrics` for working and non-working cases?

**Comment by matejzero** [comment]
For unknown reason, this started to work again. I did not had time to debug further, but for now, all is OK.
