### ISSUE TITLE
Prometheus's remote_write closes the impact of metadata sending

### ISSUE THREAD

**Issue by hexiang1219** [prometheus/prometheus#13840]
### Proposal

When the remote_write configuration of prometheus is as follows:

`remote_write: - url: http://127.0.0.1:3700/prometheus/api/v1/push metadata_config: send: false`

Will it have any impact on subsequent storage and querying of Prometheus? Is it generally better to turn it on or off?

**Comment by cstyan** [comment]
@hexiang1219 if you're using remote write to send to prometheus via enabling the remote write handler, that handler isn't written to accept metadata currently anyways. Not having metadata just means that in your query UI, prometheus's or something like grafana, you wouldn't get nice hints/annotations for the metric type/help text/etc.
