### ISSUE TITLE
Configurabe scrape interval / scrape timeout via relabeling still marked as experimental

### ISSUE THREAD

**Issue by schustersv** [prometheus/prometheus#13849]
### Proposal

Hello,
the possibility of configuring scrape_interval/scrape_timeout via relabeling has been implemented in #8911 which was merged in Aug, 2021, roughly 2.5 years ago. Still the feature is marked as "experimental". This seems to be the case only in the documentation, I did not find anything in the code that marks the feature as experimental, it isn't hidden behind a feature flag either.
I haven't been able to find any issues caused by this feature (and I'm currently using it myself successfully), so I'd propose to remove the hint in the docs telling users that it is experimental. Or are there any objections to that which I'm not aware of?

Thanks in advance,
Sven

**Comment by roidelapluie** [comment]
Hello Sven,

Yes, this feature can be marked as stable.
