### ISSUE TITLE
quay.io lists v2.51.2 but i see no 2.51.2 release (with tarballs) on github

### ISSUE THREAD

**Issue by till** [prometheus/prometheus#13927]
### What did you do?

Just got a dependabot PR to update to v2.51.2, but when I checked github, I see no release and no artifacts.

There is a tag though:
https://github.com/prometheus/prometheus/releases/tag/v2.51.2

### What did you expect to see?

I expected to find a release with all the tarballs for different architectures.

### What did you see instead? Under which circumstances?

No release.

### System information

Github

**Comment by machine424** [comment]
Thanks, I see the release being marked as a draft and I don't know if it's intentional.
cc @bboreham

**Comment by bboreham** [comment]
Sorry, I forgot to push the “Publish release” button.
