### ISSUE TITLE
Feature Flag "Created Timestamps Zero Injection" requires enabled "Native Histograms"

### ISSUE THREAD

**Issue by dbluxo** [prometheus/prometheus#13920]
### What did you do?

If you activate the feature flag `--enable-feature=created-timestamp-zero-ingestion` in Prometheus, you must also activate the feature flag `--enable-feature=native-histograms`, otherwise the following error message will appear when you scrape your own Prometheus metrics (`:9090/metrics`):

<img width="477" alt="Bildschirmfoto 2024-04-11 um 10 57 39" src="https://github.com/prometheus/prometheus/assets/20679842/148a4191-b266-4c09-ac7b-2e72ef0e7d97">

I don't know if this is intentional, but otherwise it should be documented as a dependency in the documentation?

### What did you see instead? Under which circumstances?

Error: `native histograms are disabled`

### Prometheus version

```text
prometheus, version 2.51.2 (branch: HEAD, revision: b4c0ab52c3e9b940ab803581ddae9b3d9a452337)
  build user:       root@b63f02a423d9
  build date:       20240410-14:05:54
  go version:       go1.22.2
  platform:         linux/amd64
  tags:             netgo,builtinassets,stringlabels
```

**Comment by machine424** [comment]
Thanks for the report.
Yes, IIUC, that shouldn't be required.
This looks like a regression for https://github.com/prometheus/prometheus/pull/12733 (I tested with the PR's code and the error wasn't there)

**Comment by machine424** [comment]
Running a binary search:

```
git bisect start 4a6f8704efcabfe9ee0f74eab58d4c11579547be 5082655392fe2eb036f24da51b54ca050496368a
git bisect run bash -c '
make common-build 
./prometheus --enable-feature=created-timestamp-zero-ingestion > /dev/null 2>&1 &
PPPID="$!"
sleep 15
last_error=$(curl -s "http://localhost:9090/api/v1/targets" | jq -er ".data.activeTargets[0].lastError")
if [ -z "$last_error" ]; then
    echo "lastError is empty."
else
    echo "lastError contains: $last_error"
    kill -9 $PPPID
    exit 13
fi
kill -9 $PPPID
'
```
returns https://github.com/prometheus/prometheus/pull/13681/commits/4d4d822c36b7fdda555aec124eb7b031ed0daa6b as the first bad commit.
But that commit only adds come native histograms metrics into prometheus'. I think https://github.com/prometheus/prometheus/pull/12733 was already broken for native histograms metrics.

**Comment by bwplotka** [comment]
Thanks for reporting! 

Yea, it seems proto parsing with native histograms assumes native histograms being enabled in the Prometheus storage, otherwise error is returned.

Skipping native histograms (dropping them), might not be a desired option either. 

I think I would be supporting on keeping this and documenting better cc @ArthurSens @beorn7 @krajorama as we want to have native histogram by default going forward, so that won't be a problem.

**Comment by machine424** [comment]
In that case I think `created-timestamp-zero-ingestion` should itself make all the needed changes so native histograms are accepted, because when `--enable-feature=created-timestamp-zero-ingestion` is omitted, prometheus is able to scrape native histograms without having to set `--enable-feature=native-histograms`.

**Comment by beorn7** [comment]
I think it's also OK to modify protobuf parsing to ignore native histograms if the feature flag is disabled.

**Comment by krajorama** [comment]
> I think it's also OK to modify protobuf parsing to ignore native histograms if the feature flag is disabled.

Yes, just have to make sure to not ignore classic histograms as well :)

**Comment by ArthurSens** [comment]
> > I think it's also OK to modify protobuf parsing to ignore native histograms if the feature flag is disabled.
> 
> Yes, just have to make sure to not ignore classic histograms as well :)

I'm looking at the scrape.go code now... do I understand correctly that float histograms represent the classic histograms? and histogram represent native histograms? I.e, the change is simply checking if the native histogram feature flag is enabled here?

https://github.com/prometheus/prometheus/blob/f36915b6b14e3b54132a9cd701835d0255741f96/scrape/scrape.go#L1630-L1635

**Comment by beorn7** [comment]
Both classic and native histograms have a float histogram version.
Or in other words: "classic" vs. "native" on the one hand and "integer" vs "float" on the other hand are orthogonal properties.

So no, the `if` statement you have quoted is not about switching between classic and native histograms, but about switching between integer native histograms and float native histograms.

But it _should_ be a quite easy switch.
