### ISSUE TITLE
improve --rules.max-concurrent-evals description.

### ISSUE THREAD

**Issue by machine424** [prometheus/prometheus#13931]
### Proposal

Suggest to adjust `–query.max-concurrency` when changing `--rules.max-concurrent-evals` as the rules manager uses the same query engine than the API: https://github.com/prometheus/prometheus/blob/4a6f8704efcabfe9ee0f74eab58d4c11579547be/cmd/prometheus/main.go#L743-L772
Add that to `--rules.max-concurrent-evals`'s description: https://github.com/prometheus/prometheus/blob/633224886a1c975dd3a8a8308a0b1d630048a21c/cmd/prometheus/main.go#L420

Was discussed here: https://cloud-native.slack.com/archives/C167KFM6C/p1712665137550239

**Comment by kushalShukla-web** [comment]
is this pr solves the issue @machine424

**Comment by kushalShukla-web** [comment]
I think this issue is solved
