### ISSUE TITLE
Need urgent help!!! Want to modify tags "keys" to lowercase dynamically scraping from Cloudwatch-Exporter in Prometheus before sending to Mimir

### ISSUE THREAD

**Issue by Vaibhav-1995** [prometheus/prometheus#13930]
### Proposal

We are using **Cloudwatch-exporter** to scrape cloudwatch metrics and adding exporter job in **Prometheus** to scrape those metrics from exporter and then forwarding those metrics from prometheus to mimir **to enable alerting on metrics.**

There is no consistency in **keys** of tags at aws side, due to which we are facing issue of getting **blank values of tags in alert email** as many of them **are not matching keys in alert template code** as we can add **only one pattern (Uppercase or lowercase)** in template code.

So we are trying to **standardise** the incoming tags from all aws services **to one fix pattern as lowercase** and then forward them to mimir so this issue will be overcome and will able to print all tags in alert email.

Please suggest how we can achieve this with prometheus job scrapinng config that we have added as below - 
- job_name: 'cloudwatch-exporter'     
  kubernetes_sd_configs:
  - role: service
        scrape_interval: 1m
        metrics_path: /metrics
        relabel_configs:
        - target_label: _address_
           replacement: XXX-prom-cloudwatch-exp-XXX.XXX.svc.cluster.local:9106

tags we are getting through below metrics - 
**aws_resource_info**{job="aws_ec2",instance="",**tag_Name**="XXX",**tag_Owner**="XXX",tag_businessunit="XXX",**tag_environment**="dev"} 1.0
So, here we want to modify **tag_Name** to *tag_name*, **tag_Owner** to *tag_owner*  all all such tags staring with word **tag_**tagname dynamically that will be present in metric **"aws_resource_info"**

Please suggest.

**Comment by machine424** [comment]
This is not an emergency service and no life seems to be at stake, please adjust the title ;)
I'll close this in favor of the already existing discussion: https://github.com/prometheus/prometheus/discussions/13912

**Comment by Vaibhav-1995** [comment]
Sure @machine424 

It will be appreciated if someone starts looking into it in https://github.com/prometheus/prometheus/discussions/13912 so that can have solution on it

**Comment by Vaibhav-1995** [comment]
Yes @machine424 

I have just requested on the added issue I am facing so far and I don't think I have used any improper or out of good wording for the same.
Also I am not here firstly addressing something.
Anyway waiting for someone to reply on the mentioned findings on the support of configuration.

Thanks for your reply!
