### ISSUE TITLE
--enable-feature: Consider removing no-default-scrape-port

### ISSUE THREAD

**Issue by beorn7** [prometheus/prometheus#13959]
### Proposal

Please consider if the behavior enabled with `--enable-feature=no-default-scrape-port` should become the default behavior in Prometheus 3.x /cc @roidelapluie @LeviHarrison

**Comment by jan--f** [comment]
Adding the `help wanted` and `good first issue` labels, as this doesn't seem contentious and not very complicated.

**Comment by alex-kattathra-johnson** [comment]
@jan--f: I'd be interested in picking this up as a first bug!

**Comment by jan--f** [comment]
Thanks for the PR, we'll have to wait for the prometheus 3 dev branch to open before this can be merged.

**Comment by jackma-00** [comment]
Hi, @arejula27 and I would like to pick this issue and contribute as co-authors. 
Can we please be assigned to it?
Thanks.

**Comment by jan--f** [comment]
Hey @jackma-00 and @arejula27 feel free to propose a PR. Please note that there is already an open PR https://github.com/prometheus/prometheus/pull/14160. It seems to be orphaned but there is some context in the PR that should help you.

**Comment by arejula27** [comment]
Perfect!!

Is there any way to set up everything? I read the Contribute.md but I do not find how to set up all dependencies and I would prefer to work locally (not on gitpod), any tips?

If I build from  source as it indicates I find this output
![image](https://github.com/user-attachments/assets/606b5d49-fdcb-4e4f-a5bb-7d2847c0b789)
something similar with `make test`
![image](https://github.com/user-attachments/assets/0178a3d9-eac2-41d7-b71f-9f87406671cd)

**Comment by beorn7** [comment]
Yeah, we definitely need better guidelines how to set up a dev environment. (Contributions welcome, by the way. Documentation is as important as code. So if you could keep notes of what you are doing and will be able to write it down for an updated CONTRIBUTING.md or an outright contributor's guide, that would be awesome.)

Having said that, I think the way to go is to make `make` work. It does everything else, but it needs some things installed. One if it is `goyacc`, as you have just seen. It is in the https://pkg.go.dev/golang.org/x/tools package.

Run something like `go install golang.org/x/tools/cmd/goyacc@latest` to install it.

(There might be more tools to install. You have to approach this incrementally.)

**Comment by arejula27** [comment]
Thanks so much, for sure we can take notes and improve the doc

**Comment by arejula27** [comment]
We have created a new PR #14958 
We hope it is correct, waiting for review :D

**Comment by arejula27** [comment]
We have made the #14958 pr, after finding more time we will update the contributing.md file in another one with better-defined guidelines

**Comment by beorn7** [comment]
The discussion went a bit astray with two concurrent PRs on this.

In summary: The implementation in #14160 is deliberate, trying to implement the actually desired behavior, which is a bit different from both previous states. To summarize:

- old state without feature flag: add default port (80 or 443) if no port specified by the user
- old state with feature flag: don't add the default port if not specified by the user but _remove_ it if specified by the user
- new state: take exactly what the user specified (which is presumable the behavior of every normal HTTP library)
