### ISSUE TITLE
Default --storage.tsdb.retention.time

### ISSUE THREAD

**Issue by jonathan-dev** [prometheus/prometheus#13967]
### What did you do?

I was running prom/prometheus:v2.37.6

### What did you expect to see?

--storage.tsdb.retention.time is said to default to 15 documented here : https://prometheus.io/docs/prometheus/latest/storage/#operational-aspects

### What did you see instead? Under which circumstances?

The flags I see at `/flags` show `--storage.tsdb.retention.time` to be 0s

**Comment by jonathan-dev** [comment]
Thanks a lot for the quick and detailed answer. The reason I noticed this behavior was because the [cloudflare pint](https://github.com/cloudflare/pint) tool was complaining about my retention time being 0s and thus being shorter than some of the ranges that I was querying (like 2m). After that I was a bit confused whats going on because when I was running a query it seemed like that there was a history kept but I was not able to validate that it was the 15days claimed or just the cleanup running infrequently. After checking I just noticed that the `/status` endpoint shows me the 15d retention time when I do not use the flags which is kind of what I was looking for. Noting it under the operational aspects probably would also helpful I think.

**Comment by machine424** [comment]
Let's start by making https://prometheus.io/docs/prometheus/latest/storage/#operational-aspects as clera as https://github.com/prometheus/prometheus/blob/76b0318ed52e655e96a3a4734e3678bf55801616/cmd/prometheus/main.go#L345-L346 then.

**Comment by tesla59** [comment]
Hi @machine424 
How should this issue be further proceeded?

**Comment by jonathan-dev** [comment]
I think it would have also helped me to document the strange behavior that the `/status` page is showing 0 as default although it is the 15 days somewhere like https://prometheus.io/docs/prometheus/latest/storage/#operational-aspects or the `/status` page itself. What are your thoughts on that?

**Comment by Pushpendra100** [comment]
The default value for the flag `storage.tsdb.retention.time` is **0s**

As it is done here that if neither `storage.tsdb.retention.time` is set nor `storage.tsdb.retention.size` is set, then we are doing `cfg.tsdb.RetentionDuration = defaultRetentionDuration` which is **15d**
https://github.com/prometheus/prometheus/blob/2d2b440304d0ec599bf19b102724aab67650b91e/cmd/prometheus/main.go#L572C1-L575C4

Thus, after filling up values in cfg.web.Flags by the for loop. We can keep a check same as above.
https://github.com/prometheus/prometheus/blob/2d2b440304d0ec599bf19b102724aab67650b91e/cmd/prometheus/main.go#L804C1-L814C3

```
        if newFlagRetentionDuration == 0 && cfg.tsdb.MaxBytes == 0 {
		cfg.web.Flags["storage.tsdb.retetion.time"] = defaultRetentionDuration.String()
	}
```
