### ISSUE TITLE
docs: Remove the section about remote read JSON responses - it only supports proto response or errors

### ISSUE THREAD

**Issue by bwplotka** [prometheus/prometheus#13975]
### Proposal

AC:
* Remove the wrong section: https://prometheus.io/docs/prometheus/latest/querying/remote_read_api/#format-overview

**Comment by kushalShukla-web** [comment]
https://github.com/prometheus/prometheus/pull/13989/files pr for this issue

**Comment by kushalShukla-web** [comment]
@bwplotka is this fine ?

**Comment by kushalShukla-web** [comment]
i have created another Pr from new branch
