### ISSUE TITLE
Custom timeouts per query

### ISSUE THREAD

**Issue by RichiH** [prometheus/prometheus#1399]
As per IRC with @juliusv 

Initial context was my desire to run `count({job=~".+"}) / count(up{job=~".+"}) by (job)` which ran into a timeout for obvious reasons.

**Comment by RichiH** [comment]
Sorry, I meant @juliusv

**Comment by brian-brazil** [comment]
I can see this being useful to have lower timeouts when delegating parts of queries to slave Prometheus servers.
