### ISSUE TITLE
Range-vector functions double-count samples if their timestamps align with query step

### ISSUE THREAD

**Issue by vpranckaitis** [prometheus/prometheus#14007]
### What did you do?

See [these tests](https://github.com/vpranckaitis/prometheus/commit/3df6bb7484bab3e76468ffb2d08e5f8f3a8452e2) for an example. It seems that range-vector functions treat both ends of the range as inclusive. Thus if a timestamp of a sample matches the location of one of the steps of the query, the sample will be included in calculations both in the left side window and in the right side window of range function.

### What did you expect to see?

I would expect the range functions to treat one of the edges of the range as exclusive. This would mean that a query like `sum_over_time(foo[$__interval])`, where `$__interval` is the query step size, would guarantee that the samples are sorted into separate windows/buckets, and no two windows/buckets share a sample.

It could be argued that the current behavior is beneficial for `rate()`-family functions, since they need at least two samples in the window to produce a result. However, the conditions for this makes it difficult to rely upon (you need to make sure that the samples, step size, and the query range is correctly aligned), and there's already a best-practice to use a range that is at least 2x or 3x of the scrape interval.

### What did you see instead? Under which circumstances?

See [these example tests](https://github.com/vpranckaitis/prometheus/commit/3df6bb7484bab3e76468ffb2d08e5f8f3a8452e2)

### Prometheus version

```text
`main` branch
```

**Comment by vpranckaitis** [comment]
If the proposed change seems good, I could also submit a PR.

**Comment by bboreham** [comment]
Thanks for your interest in the Prometheus project.

We could not make such an impactful change without a major version bump.

I'm pretty sure it has been discussed, but it's not an easy thing to search for.

**Comment by vpranckaitis** [comment]
Accidentally found [an earlier issue for this](https://github.com/prometheus/prometheus/issues/13213), which seems to be already being worked on for Prometheus 3.0. I guess this one could be closed.

**Comment by bboreham** [comment]
Excellent! Your searching powers are greater than mine.
Let's link the proposed PR too https://github.com/prometheus/prometheus/pull/13904
