### ISSUE TITLE
`predict_linear` could be more predictive.

### ISSUE THREAD

**Issue by beorn7** [prometheus/prometheus#1401]
See attached image. Essentially, we are calculating the slope with sophisticated regression analysis, and then we are not starting at the value predicted for the end of the range but at the last sample value within the range.
![img_20160217_162506](https://cloud.githubusercontent.com/assets/5609886/13114541/3755ae8c-d594-11e5-83a2-2eb1c17163ae.jpg)

**Comment by juliusv** [comment]
Every issue should now contain whiteboard snapshots. <3
