### ISSUE TITLE
Remote-write: threshold to skip resharding should be higher

### ISSUE THREAD

**Issue by bboreham** [prometheus/prometheus#14044]
I saw a lot of log lines like this:

```
ts=2024-05-02T14:02:48.270112953Z level=warn msg="Skipping resharding, last successful send was beyond threshold" [...] lastSendTimestamp=1714658566 minSendTimestamp=1714658568
```

Context was that we wanted to feed data in a timely manner, so `BatchSendDeadline` had been reduced to 100ms.

The code that generates the message: 
https://github.com/prometheus/prometheus/blob/94c81bba419b6c8ad993a182f357d722c78cd9c1/storage/remote/queue_manager.go#L1021-L1026

is called every 10s (hard-coded), so if `BatchSendDeadline` is any less than 5s we stand some chance that we didn't even try to send within that interval.

### Proposal

I suggest the check should be within `2 * time.Duration(t.cfg.BatchSendDeadline) + shardUpdateDuration`.

**Comment by bboreham** [comment]
I notice in a similar previous issue @csmarchbanks said https://github.com/prometheus/prometheus/issues/7124#issuecomment-613634182

> At very low remote write volumes it is very easy to go through multiple batch send durations without new samples coming in

Which matches the situation in this case (volume was about 500 series, scraped every 5s).
Anyway this judgement seems highly dependent on the value of `BatchSendDeadline`; is it unreasonable to set it to 100ms?

> low volumes are unlikely to ever reshard above the minimum anyway

More context: the machine was occasionally under heavy CPU load; I believe this generated a backlog on the send queue.
(Sadly I don't have metrics to confirm this)

**Comment by kushalShukla-web** [comment]
is this good @bboreham or do we need to wait for others review .

**Comment by bboreham** [comment]
Best to comment on the PR within the PR itself.

**Comment by kushalShukla-web** [comment]
okay @bboreham .

**Comment by cstyan** [comment]
> Which matches the situation in this case (volume was about 500 series, scraped every 5s).
> Anyway this judgement seems highly dependent on the value of `BatchSendDeadline`; is it unreasonable to set it to 100ms?

I would have suggested/assumed people would drop the batch size `max_samples_per_send` a lot lower before dropping the `BatchSendDeadline` that low.

**Comment by bboreham** [comment]
I don't think that helps.  In my example, Prometheus scraped 509 series every 5 seconds; I wanted it to send those 509 series without waiting 5 seconds.
If I reduce `max_samples_per_send` from 2000 default to 100, say, it will send 500 of them, but I still want it to send all 509 series.

**Comment by cstyan** [comment]
Personally  I would still lower the batch size before the send deadline timeout, but even so I think guarding against excessive resharding checks is a valid change. Reviewing the PR again today.

**Comment by bboreham** [comment]
I don't think I am understanding your point.  What would you lower `max_samples_per_send` to, given my example?

**Comment by cstyan** [comment]
> I don't think I am understanding your point. What would you lower `max_samples_per_send` to, given my example?

Something below `509`? Or even just `1000` or so and lower the send deadline to ~1s. I don't know exactly what your use case is but scraping a small amount of samples and then always sending _all_ of them via remote write ASAP isn't really a situation we've designed for. Setting the send deadline to 100ms is just a workaround that's worked in your case.

This is separate from the issue of the the resharding check happening too often when the send deadline is < 5s, which  I don't have any issue with merging a fix for.

**Comment by bboreham** [comment]
> lower the send deadline to ~1s

OK, that case still shows the issue I am talking about, because two times 1 second is way less than the 10s interval it checks at.

> always sending all of them via remote write ASAP

That isn't what I asked for; I asked for:

> > in a timely manner

and

> > without waiting 5 seconds

> Setting the send deadline to 100ms is just a workaround that's worked in your case.

I disagree, it matches what I wanted.

Bryan

**Comment by cstyan** [comment]
Bryan and I discussed on Slack; over text we'd misunderstood each other. His config changes were definitely valid given the low scrape load he had. Remote write has some gaps when it comes to handling timely sending of data in that kind of a scenario, the hard coding of the reshard check ticker is just one of those gaps.

I'll be opening a few issues soon for some things we can try out, there are a number of people interested in taking on some smaller tasks in RW and those could be good first issues for them.

**Comment by kushalShukla-web** [comment]
yeah after seeing and understanding code @bboreham  assumption here is valid as we dont need to wait for 5 seconds , and yeah as @bboreham  also asked for feeding data timely manner  .  and also we need to remove that hard coding of the resharding check ticker .

**Comment by kushalShukla-web** [comment]
i have some issues in my mind , shall i create those issues @cstyan ?

**Comment by CodexRaunak** [comment]
Hey, I want to contribute to cloud native projects, I am quite starting my open source joruney,
Can anyone tell how to understand all this? Where to start from? It would be a lot of help if someone could point out in the right direction or point to a resource @bboreham

**Comment by bboreham** [comment]
Hi @CodexRaunak and thanks for your interest.
Prometheus is written in Go and TypeScript, no Java.

A great first step would be to get Prometheus running, and have it monitor something of interest to you.
This will be useful even if you find a different project to contribute to.
There are lots of blog posts and videos how to get started.

On the coding side, get enough of a dev environment working to run the unit tests.
See if you can make one of them break by editing the code described in this issue.
