### ISSUE TITLE
Revisit target provider implementations

### ISSUE THREAD

**Issue by fabxc** [prometheus/prometheus#1406]
Various SD integrations are not using the given channels correctly. Most commonly they send on the update channel without listening on the done channel to abort in case the consumer is gone. This can cause deadlocking of single goroutines or the entire server.

Generally, the pattern of starting background processing before `Run()` is called should be reconsidered as well.

**Comment by cstyan** [comment]
@fabxc I'm considering taking a shot at this, I think it would be a good task for improving my understanding of how the SD component works.

I could use some pointers as to where to start, and what the desired outcome is. Just to confirm I understand your first point, the done channel refers `ctx.Done()`?

**Comment by fabxc** [comment]
I think I did a pass over the SDs some time ago and fixed some of the issues. But we added more SDs since so it's possible we do have some issues again.
There are certainly other general issues across various implementations like #3001

It's certainly a good idea to just read through them and try to validate their behavior! If you have any questions along the way, just ask here or on IRC.

The done channel refers to `ctx.Done()` as you said.

#3014 and #3013 are relevant cleanups that should how a low entry barrier as well. Those are probably best done against the dev-2.0 branch.

**Comment by cstyan** [comment]
I'll look into the three issues you've linked,thanks!

**Comment by krasi-georgiev** [comment]
@fabxc , @brancz , @Gouthamve I think this can be closed now?

**Comment by brancz** [comment]
I would think so as well if anyone thinks otherwise feel free to re open.

**Comment by krasi-georgiev** [comment]
@brancz i think you missed the close button :)

**Comment by brancz** [comment]
:facepalm:
