### ISSUE TITLE
Case insensitive FastRegexMatcher doesn't check all folds

### ISSUE THREAD

**Issue by colega** [prometheus/prometheus#14066]
### What did you do?

I ran the `mimir-prometheus` [FuzzFastRegexMatcher_WithStaticallyDefinedRegularExpressions](https://github.com/grafana/mimir-prometheus/blob/6dc8786f458cefec360e12f696c4e025db749322/model/labels/regexp_test.go#L751-L751) for a while, and found a bug.

The input string `"ſſs"` is not matched by the case-insensitive regular expression `"(?i:(foo1|foo2|aaa|bbb|ccc|ddd|eee|fff|ggg|hhh|iii|lll|mmm|nnn|ooo|ppp|qqq|rrr|sss|ttt|uuu|vvv|www|xxx|yyy|zzz))",`. 

### What did you expect to see?

I expected that string to be matched, as the golang's regexp package matches it.

### What did you see instead? Under which circumstances?

It wasn't matched.

**Comment by colega** [comment]
A very quick diff that fixes the problem in the least performant way:
```diff
diff --git model/labels/regexp.go model/labels/regexp.go
index 79e340984..7681483e7 100644
--- model/labels/regexp.go
+++ model/labels/regexp.go
@@ -791,7 +791,15 @@ func (m *equalMultiStringMapMatcher) Matches(s string) bool {
        }

        _, ok := m.values[s]
-       return ok
+       if ok {
+               return true
+       }
+       for k := range m.values {
+               if strings.EqualFold(s, k) {
+                       return true
+               }
+       }
+       return false
 }
```

**Comment by colega** [comment]
I'd also consider just going through the standard regular expression engine if the matcher is case insensitive and the string contains unicode runes.

**Comment by kushalShukla-web** [comment]
hey @colega  i did not get it like "ſſs" this string should be present on the given regular expression , something like that ?

**Comment by colega** [comment]
The case-insensitive regular expression `"(?i:(sss))"` should match the string `"ſſs"` but it does not.

**Comment by kushalShukla-web** [comment]
you mean this matches function is incomplete right and it should have a check for a string to be matched .

**Comment by kushalShukla-web** [comment]
i think here we should use "regexp" package instead of string package .

**Comment by kushalShukla-web** [comment]
> A very quick diff that fixes the problem in the least performant way:
> 
> ```diff
> diff --git model/labels/regexp.go model/labels/regexp.go
> index 79e340984..7681483e7 100644
> --- model/labels/regexp.go
> +++ model/labels/regexp.go
> @@ -791,7 +791,15 @@ func (m *equalMultiStringMapMatcher) Matches(s string) bool {
>         }
> 
>         _, ok := m.values[s]
> -       return ok
> +       if ok || m.caseSensitive {
> +               return ok
> +       }
> +       for k := range m.values {
> +               if strings.EqualFold(s, k) {  

> i think here we should use regexp package instead of string package as we need to match for a certain pattern . 

> +                       return true
> +               }
> +       }
> +       return false
>  }
> ```

**Comment by kushalShukla-web** [comment]
will create pr for this today .

**Comment by bboreham** [comment]
I observe it fails because `ToLower("ſſs")` is `"ſſs"`.
However if we flip all the `ToLower`s to `ToUpper`, this case does work.

Maybe we can use `unicode.SimpleFold`?  (which I found used inside Go's regexp package)

**Comment by Ranveer777** [comment]
@colega @bboreham
I'm interested in picking up this initiative.
