### ISSUE TITLE
Histogram reuse bug in query evaluation

### ISSUE THREAD

**Issue by faustuzas** [prometheus/prometheus#14072]
### What did you do?

I have noticed a bug in histogram memory reuse when `(chunkenc.Iterator).AtFloatHistogram` returns multiple histograms with the same address and does not use the newly added destination histogram functionality.

Exemplary way to reproduce the bug:
1. The Iterator returns two consecutive histograms that point to the same address X. 
2. The `histograms` slice now looks like this: `[X, X (.....)]`, `()` denotes part of the slice where `len <= i < cap`.
3. The iterator returns another histogram with the address Y where Y != X.
4. The first slot in `histograms` slice which is pointing to X gets pivoted to the unused back of the slice in:
https://github.com/prometheus/prometheus/blob/312e3fd728d522028285000a63157cadf0666f65/promql/engine.go#L2134-L2138
5. Now the `histograms` slice is `[X, Y (X, .....)]`.
6. On arrival of another histogram, slice length is increased and the new histogram is copied to the address X, mutating histograms at i=0 and i=2:
https://github.com/prometheus/prometheus/blob/312e3fd728d522028285000a63157cadf0666f65/promql/engine.go#L2169-L2175

Demo unit test reproducing the bug: https://github.com/faustuzas/prometheus/pull/1

Debug logs from the test above printing the inputs to the rate function inside the PromQL engine:
```
Input into function:
 => [2024-05-09 12:00:00 +0300 EEST] 300000.00 (0x14000130240)
Input into function:
 => [2024-05-09 12:00:00 +0300 EEST] 300000.00 (0x14000130240)
Input into function:
 => [2024-05-09 12:00:00 +0300 EEST] 300000.00 (0x14000130240)
 => [2024-05-09 12:02:00 +0300 EEST] 300000.00 (0x14000130240)
Input into function:
 => [2024-05-09 12:00:00 +0300 EEST] 300000.00 (0x14000130240)
 => [2024-05-09 12:02:00 +0300 EEST] 300000.00 (0x14000130240)
Input into function:
 => [2024-05-09 12:00:00 +0300 EEST] 300000.00 (0x14000130240)
 => [2024-05-09 12:02:00 +0300 EEST] 300000.00 (0x14000130240)
Input into function:
 => [2024-05-09 12:00:00 +0300 EEST] 300000.00 (0x14000130240)
 => [2024-05-09 12:02:00 +0300 EEST] 300000.00 (0x14000130240)
 => [2024-05-09 12:05:00 +0300 EEST] 600000.00 (0x140001302d0)
Input into function:
 => [2024-05-09 12:02:00 +0300 EEST] 750000.00 (0x14000130240) <-- bug happens and rate function detects a reset
 => [2024-05-09 12:05:00 +0300 EEST] 600000.00 (0x140001302d0)
 => [2024-05-09 12:05:30 +0300 EEST] 750000.00 (0x14000130240)
Input into function:
 => [2024-05-09 12:02:00 +0300 EEST] 750000.00 (0x14000130240)
 => [2024-05-09 12:05:00 +0300 EEST] 600000.00 (0x140001302d0)
 => [2024-05-09 12:05:30 +0300 EEST] 750000.00 (0x14000130240)
Input into function:
 => [2024-05-09 12:05:00 +0300 EEST] 600000.00 (0x140001302d0)
 => [2024-05-09 12:05:30 +0300 EEST] 750000.00 (0x14000130240)
```
--- 
The problem is absent when line https://github.com/prometheus/prometheus/blob/312e3fd728d522028285000a63157cadf0666f65/promql/engine.go#L2218 is changed to:
```go
t, fh := it.AtFloatHistogram(histograms[n].H)
histograms[n].T, histograms[n].H = t, fh.Copy()
```
However, this defeats the whole purpose of having a destination histogram in the iterator. 

### What did you see instead? Under which circumstances?

---

### Prometheus version

`main` branch

**Comment by faustuzas** [comment]
Hey @fpetkovski @krajorama, I've seen you working on optimisations around histograms in PromQL engine recently. Perhaps you could take a look at this bug?

I've tried to come up with a fix, however, promql engine code is very complex and this bug requires deep knowledge about reusing histograms in the iterators to fix it properly.

**Comment by fpetkovski** [comment]
I will take a look!

**Comment by fpetkovski** [comment]
@faustuzas I took at look at the bug and I don't think that the iterator stub used in tests is implemented correctly. I've made a suggestion for the correct implementation: https://github.com/faustuzas/prometheus/pull/1/files#r1597967140.

I am curious how you discovered the bug. Did you see it inside Prometheus or are you using the engine or some other Prometheus package in a different project?

**Comment by faustuzas** [comment]
Hey, @fpetkovski, thank you for taking a look. Yes, this bug was discovered outside the Prometheus. 

Your suggested change to the stub iterator makes sense, the semantics of the engine have changed a little with the addition of histogram re-use and the reduction of allocations. 

I will close the issue, thanks for the help again!
