### ISSUE TITLE
remote write lose sample when target is unavailable

### ISSUE THREAD

**Issue by roastiek** [prometheus/prometheus#14087]
### What did you do?

I'm using remote write to a receiver, which can be temporary down when updating. 

### What did you expect to see?

All samples should be evantualy written back when a receiver is running again.

### What did you see instead? Under which circumstances?

After upgrading to 2.51.2 from 2.50.1 I started missing samples on a receiver in time when it was not running. I cheked this by quering some metrics samples in both prometheus and receiver. I can see drop in `prometheus_remote_storage_samples_total` but nothing in `prometheus_remote_storage_samples_dropped_total` or `prometheus_remote_storage_samples_failed_total` metrics. So the samples were probraly never tried to send and just skipped.

I'm suspecting changes made in #13583 and shared parameter `tail bool` between https://github.com/prometheus/prometheus/blob/3b8b57700c469c7cde84e1d8f9d383cb8fe11ab0/tsdb/wlog/watcher.go#L393 and https://github.com/prometheus/prometheus/blob/3b8b57700c469c7cde84e1d8f9d383cb8fe11ab0/tsdb/wlog/watcher.go#L533 First time is used to to tail the wal and second time to skip reading samples of checkpoint. Prior the change it stayed `true` once set. However now it can revert back to `false` when processing of samples is paused for some time and then resumed.

Reverting back to 2.50.1 fixed this.

### Prometheus version

```text
2.51.2
```

**Comment by koly23** [comment]
Is there any logs in prometheus? When use debug log level, is there any debug logs?

**Comment by machine424** [comment]
Thanks for the report,

That code also troubled me when I was looking at `watcher.go` lately, I agree with you.
I left the following comment:

> I don't know if this was intentional (I cannot see it explicitly stated)
> 
> But I think that in order to help the watcher catch up, we started making it skip samples records now (`tail=false` here passed to `readSegment` makes it skip/ignore the samples records)
> 
> When this issue was discussed, the `case <-segmentTicker.C` block https://github.com/prometheus/prometheus/blob/8849b7dcadc2960c70467734efce35d737be25f5/tsdb/wlog/watcher.go#L451-L461 was ignored, even though it seems to be there for this same reason: "read the current segment until the end if a new one is there" and it checks that every `segmentCheckPeriod = 100 * time.Millisecond` which should be sufficient.

on that PR https://github.com/prometheus/prometheus/pull/13583/files#r1668166164 to check if this was intentional.

And opened https://github.com/prometheus/prometheus/pull/14434 to highlight the issue.

**Comment by bboreham** [comment]
Closed by #14446
