### ISSUE TITLE
[prometheus] Secure Prometheus with enabling Ldap authentication 

### ISSUE THREAD

**Issue by kksaha** [prometheus/prometheus#14137]
### Proposal

To secure Prometheus need to enable ldap authentication. At present, there is no option in Prometheus to allow LDAp authentication. How can we configure that .

**Comment by roidelapluie** [comment]
This request is out of scope, but you can secure Prometheus using a reverse proxy like Nginx with LDAP authentication. Alternatively, Prometheus supports enterprise-grade OAuth for authentication.
