### ISSUE TITLE
EC2 service discovery: show scrape pool in targets page when configured but no targets found yet

### ISSUE THREAD

**Issue by hackery** [prometheus/prometheus#14138]
### Proposal

When a new discovery config is deployed, but no actual targets exist yet, the scrape pool does not appear in the Targets status page.

This can be confusing and waste diagnosis time - especially when working via automation, to multiple environments, for multiple customers, with governance-restricted access to Prometheus hosts, etc.

Proposal: new discovery pools should appear in the list, empty and showing `(0/0 up)` or `(pending)` for count of targets scraped.

![image](https://github.com/prometheus/prometheus/assets/308470/73f490ba-d349-4bfe-9f9d-55f2fecf87db)

**Comment by machine424** [comment]
This makes sense to me (I was under the impression that this was already the case actually). However, I believe that those empty jobs should only be listed on the `/service-discovery` page to indicate that a job_name is defined, but no target has been discovered. The `/targets` page should maintain its focus on displaying only the scrape pools with active or discovered targets.

**Comment by beorn7** [comment]
This is more or less a special case of the more general https://github.com/prometheus/prometheus/issues/8528 . Closing this one. Let's continue the discussion over in the older issue.
