### ISSUE TITLE
time shifts, prometheus memory go high and no gc 

### ISSUE THREAD

**Issue by rockerzhao** [prometheus/prometheus#14147]
### What did you do?

deploy prometheus in k8s with prometheus operator
when i change time to before and after, my prometheus memory will be hign and not fall, not gc

my log:
ts=2024-05-27T07:24:10.499Z caller=manager.go:683 level=warn component="rule manager" file=/etc/prometheus/rules/prometheus-kube-prometheus-stack-prometheus-rulefiles-0/monitor-kube-prometheus-stack-kube-apiserver-availability.rules-b21132ee-39cc-4254-83a0-b65c3cb132b4.yaml group=kube-apiserver-availability.rules name=cluster_verb_scope_le:apiserver_request_slo_duration_seconds_bucket:increase30d index=6 msg="Rule evaluation result discarded" err="out of bounds" sample="{__name__=\"clus^Cts=2024-05-27T07:24:12.736Z caller=scrape.go:1349 level=warn component="scrape manager" scrape_pool=serviceMonitor/rabbitmq-service/rabbitmq-exporter-prometheus-rabbitmq-exporter/0 target=http://192.168.241.84:9419/metrics msg="Append failed" err="out of bounds"
ts=2024-05-27T07:24:13.085Z caller=manager.go:683 level=warn component="rule manager" file=/etc/prometheus/rules/prometheus-kube-prometheus-stack-prometheus-rulefiles-0/monitor-kube-prometheus-stack-kubernetes-system-apiserver-f04fbdb4-8f10-4aee-91d0-24eaba02a26a.yaml group=kubernetes-system-apiserver name=KubeAPIDown index=4 msg="Rule evaluation result discarded" err="out of bounds" sample="{__name__=\"ALERTS\", alertname=\"KubeAPIDown\", alertstate=\"firing\", severity=\"critical\"} => 1 @[1716794646967]"
ts=2024-05-27T07:24:13.085Z caller=manager.go:683 level=warn component="rule manager" file=/etc/prometheus/rules/prometheus-kube-prometheus-stack-prometheus-rulefiles-0/monitor-kube-prometheus-stack-kubernetes-system-apiserver-f04fbdb4-8f10-4aee-91d0-24eaba02a26a.yaml group=kubernetes-system-apiserver name=KubeAPIDown index=4 msg="Rule evaluation result discarded" err="out of bounds" sample="{__name__=\"ALERTS_FOR_STATE\", alertname=\"KubeAPIDown\", severity=\"critical\"} => 1716776796 @[1716794646967]"
ts=2024-05-27T07:24:13.455Z caller=scrape.go:1655 level=warn component="scrape manager" scrape_pool=serviceMonitor/default/zookeeper/0 target=http://192.168.59.196:9141/metrics msg="Error on ingesting samples that are too old or are too far into the future" num_dropped=451
ts=2024-05-27T07:24:13.497Z caller=scrape.go:1349 level=warn component="scrape manager" scrape_pool=serviceMonitor/monitor/kube-prometheus-stack-prometheus/0 target=http://192.168.59.200:9090/metrics msg="Append failed" err="out of bounds"
ts=2024-05-27T07:24:15.113Z caller=scrape.go:1655 level=warn component="scrape manager" scrape_pool=serviceMonitor/monitor/kube-prometheus-stack-kube-controller-manager/0 target=https://20.20.20.16:10257/metrics msg="Error on ingesting samples that are too old or are too far into the future" num_dropped=356
ts=2024-05-27T07:24:15.118Z caller=scrape.go:1655 level=warn component="scrape manager" scrape_pool=serviceMonitor/monitor/om-exporter/0 target=http://20.20.20.16:9395/metrics msg="Error on ingesting samples that are too old or are too far into the future" num_dropped=10
ts=2024-05-27T07:24:15.161Z caller=scrape.go:1655 level=warn component="scrape manager" scrape_pool=serviceMonitor/monitor/kube-prometheus-stack-kubelet/0 target=https://20.20.20.15:10250/metrics msg="Error on ingesting samples that are too old or are too far into the future" num_dropped=1289
ts=2024-05-27T07:24:15.161Z caller=scrape.go:1349 level=warn component="scrape manager" scrape_pool=serviceMonitor/monitor/kube-prometheus-stack-kubelet/0 target=https://20.20.20.15:10250/metrics msg="Append failed" err="out of bounds"
![1111](https://github.com/prometheus/prometheus/assets/20817783/06c61534-e7ab-4f8d-bb94-41fd53437260)

### What did you expect to see?

i want konw how to resolve it . or why no gc, because of change time?

### What did you see instead? Under which circumstances?

i see memory go hign and not fall , no gc
![1111](https://github.com/prometheus/prometheus/assets/20817783/6b269ec4-7e44-4ca0-82ab-5fcc5c573817)

### System information

centos

### Prometheus version

```text
v2.39.1
```

### Prometheus configuration file

```yaml
prometheus operator default config
```

### Alertmanager version

```text
no
```

### Alertmanager configuration file

```yaml
no
```

### Logs

```text
ts=2024-05-27T07:52:09.624Z caller=scrape.go:1655 level=warn component="scrape manager" scrape_pool=serviceMonitor/monitor/kube-prometheus-stack-kube-scheduler/0 target=https://20.20.20.16:10259/metrics msg="Error on ingesting samples that are too old or are too far into the future" num_dropped=389
ts=2024-05-27T07:52:09.681Z caller=scrape.go:1655 level=warn component="scrape manager" scrape_pool=serviceMonitor/monitor/kube-prometheus-stack-kube-scheduler/0 target=https://20.20.20.15:10259/metrics msg="Error on ingesting samples that are too old or are too far into the future" num_dropped=354
ts=2024-05-27T07:52:09.953Z caller=scrape.go:1655 level=warn component="scrape manager" scrape_pool=serviceMonitor/default/mariadb-galera/0 target=http://192.168.241.80:9104/metrics msg="Error on ingesting samples that are too old or are too far into the future" num_dropped=1244
ts=2024-05-27T07:52:10.499Z caller=scrape.go:1655 level=warn component="scrape manager" scrape_pool=serviceMonitor/monitor/kube-prometheus-stack-apiserver/0 target=https://20.20.20.14:6443/metrics msg="Error on ingesting samples that are too old or are too far into the future" num_dropped=25716
ts=2024-05-27T07:52:10.499Z caller=scrape.go:1349 level=warn component="scrape manager" scrape_pool=serviceMonitor/monitor/kube-prometheus-stack-apiserver/0 target=https://20.20.20.14:6443/metrics msg="Append failed" err="out of bounds"
ts=2024-05-27T07:52:10.662Z caller=scrape.go:1655 level=warn component="scrape manager" scrape_pool=serviceMonitor/monitor/kube-prometheus-stack-alertmanager/0 target=http://192.168.59.197:9093/metrics msg="Error on ingesting samples that are too old or are too far into the future" num_dropped=493
ts=2024-05-27T07:52:11.181Z caller=scrape.go:1655 level=warn component="scrape manager" scrape_pool=serviceMonitor/monitor/om-exporter/0 target=http://172.29.123.14:9283/metrics msg="Error on ingesting samples that are too old or are too far into the future" num_dropped=165
ts=2024-05-27T07:52:11.181Z caller=scrape.go:1349 level=warn component="scrape manager" scrape_pool=serviceMonitor/monitor/om-exporter/0 target=http://172.29.123.14:9283/metrics msg="Append failed" err="out of bounds"
ts=2024-05-27T07:52:11.502Z caller=scrape.go:1655 level=warn component="scrape manager" scrape_pool=serviceMonitor/monitor/kube-prometheus-stack-kube-proxy/0 target=http://20.20.20.14:10249/metrics msg="Error on ingesting samples that are too old or are too far into the future" num_dropped=260
ts=2024-05-27T07:52:11.738Z caller=scrape.go:1655 level=warn component="scrape manager" scrape_pool=serviceMonitor/monitor/pd-service/0 target=http://172.28.123.15:12381/metrics msg="Error on ingesting samples that are too old or are too far into the future" num_dropped=4503
ts=2024-05-27T07:52:11.739Z caller=scrape.go:1349 level=warn component="scrape manager" scrape_pool=serviceMonitor/monitor/pd-service/0 target=http://172.28.123.15:12381/metrics msg="Append failed" err="out of bounds"
```

**Comment by rockerzhao** [comment]
Flame diagram
![222](https://github.com/prometheus/prometheus/assets/20817783/b30680b5-07dc-4d23-9b36-112e66be64e6)

**Comment by rockerzhao** [comment]
and my prometheus_tsdb_head_series metric like:

I understand i set 2 hours to write to disk, it will fall observably,but it not happend
![333](https://github.com/prometheus/prometheus/assets/20817783/963310aa-2127-4bc8-99c3-39cce2aa8e64)

**Comment by rockerzhao** [comment]
anyone can help me? i just want to konw why it dont gc, is it caused by time shifts ?

**Comment by roidelapluie** [comment]
Time shifting is not supported by Prometheus, which expects the correct time.

It is possible that you have metrics from far in the pas or the future. We have other tickets open to tackle this but as I see it, except with the fact that Prometheus could tackle this better, the timestamps in your server is corrupt so the data is meaningless and there is nothing we can do about it.

**Comment by rockerzhao** [comment]
> Time shifting is not supported by Prometheus, which expects the correct time.
> 
> It is possible that you have metrics from far in the pas or the future. We have other tickets open to tackle this but as I see it, except with the fact that Prometheus could tackle this better, the timestamps in your server is corrupt so the data is meaningless and there is nothing we can do about it.

thank you for you reply,  i know this kind of data is invalid, i just want konw why memory so high in this situation, if my time incorrect, is the memory always so hgh?
