### ISSUE TITLE
Why Does Prometheus Kubernetes Discovery Use a Single Informer 'process' Function and Queue?

### ISSUE THREAD

**Issue by MengXiangyu0624** [prometheus/prometheus#14204]
### Proposal

I'm currently delving into the implementation details of Prometheus's Kubernetes service discovery, and I noticed that the design uses a **single informer processing function alongside a single queue mechanism**. I'm curious about the rationale behind this choice, particularly considering the potential benefits of multiple queues for handling huge Kubernetes events (e.g., Pods, Nodes) concurrently in large k8s cluster.

Thank you for the answer and help in advance 🙏 😊 

<img width="1189" alt="image" src="https://github.com/prometheus/prometheus/assets/52183517/4175228a-017e-4da7-be10-da7386bf6a4f">

**Comment by roidelapluie** [comment]
cc @brancz

**Comment by machine424** [comment]
Just to be clear, it's one queue and worker per `kubernetes_sd_config`.
All of what a worker does is retrieve the resource manifest from the cache, construct the target, and push it into a channel.
This is why it seems to have worked fine so far (performance/used resources tradeoff seems to be accepted), given the number of events that a "normal" cluster generates. 
If you could provide more insights and details about the limitations of this implementation, we'll be happy to challenge it.

**Comment by MengXiangyu0624** [comment]
thanks for the answer!

**Comment by machine424** [comment]
Sure, I'll close this.
