### ISSUE TITLE
ARM binaries for Raspberry Pi

### ISSUE THREAD

**Issue by vielmetti** [prometheus/prometheus#1423]
I'm hoping to put Prometheus on a Raspberry Pi 2. I checked the mailing list and the Github for any mention of ARM support and came up blank.

**Comment by brian-brazil** [comment]
ARM should work fine if you cross-compile, and Prometheus has previously been run on a Raspberry Pi: https://5pi.de/2015/02/10/prometheus-on-raspberry-pi/

If you don't want to cross-compile yourself, there's some nightlies up at http://www.robustperception.io/prometheus-nightly-binaries/

**Comment by brian-brazil** [comment]
I'm presuming this is answered, if not let us know.

**Comment by alexellis** [comment]
@brian-brazil we need to move up to Prometheus 2.0 for OpenFaaS on ARMHF. Do you have any thoughts on whether the project will provide a multi-arch image? The Docker team provide a free CI service where they can build Docker images for multiple architectures. The result is that a single image name would redirect to the appropriate architecture.
