### ISSUE TITLE
Config reload via HTTP API should return status code

### ISSUE THREAD

**Issue by RichiH** [prometheus/prometheus#1425]
As of right now, `prometheus_config_last_reload_success_timestamp_seconds` provides information from within Prometheus on if a reload was successful or not, but a simple return to the caller would allow me to see if everything was fine from CLI.

**Comment by RichiH** [comment]
`curl 'http://localhost:9090/api/v1/query?query=prometheus_config_last_reload_success_timestamp_seconds'` is a crude workaround, but kinda icky.

**Comment by brian-brazil** [comment]
Related to #1149

**Comment by brian-brazil** [comment]
Per #1292, having the error message would be good too.
