### ISSUE TITLE
"No datapoints found." using rate on node_cpu

### ISSUE THREAD

**Issue by pwaller** [prometheus/prometheus#1428]
```
prometheus, version 0.16.2 (branch: stable, revision: 287d9b2)
  build user:       @ee15eaddc546
  build date:       20160223-19:12:50
  go version:       1.5.3
```

I'm pretty convinced everything is working, except that I can't get the `rate()` function to work. Here I pick a specific `node_cpu` and try and try and compute the rate:

![screenshot from 2016-02-26 10 40 47](https://cloud.githubusercontent.com/assets/438648/13350028/7d9f2a7a-dc75-11e5-88b2-f50e65eec9fa.png)

And the rate:

![screenshot from 2016-02-26 10 41 10](https://cloud.githubusercontent.com/assets/438648/13350073/a9d7176a-dc75-11e5-9885-1e4ea41e1d04.png)

Am I doing something obviously wrong? I found #1022 but checking the clocks from the host running prometheus, the prometheus container and my browser and they all agree to within a second.

`rate(node_cpu[1m])` also returns no data, whereas `node_cpu` by itself returns lots of data.

**Comment by brian-brazil** [comment]
Eyeballing that data, you have a scrape interval of 1m so `rate(node_cpu[1m])` will often not have two data points to work with. I'd suggest using `rate(node_cpu[5m])` instead.

**Comment by pwaller** [comment]
I think I'm coming to understand the problem. I thought I had a 1s scrape interval, but my scrape interval was only applying to the first scrape config and not the later ones.

How is the default scrape interval determined? I thought it was 10s, [judging from the docs](http://prometheus.io/docs/operating/configuration/)?

**Comment by pwaller** [comment]
Sorry. PEBKAC. I was reading the default scrape timeout, not the scrape interval. All solved!

The only slightly unfortunate thing was just how mysterious it was when I got no data back.

**Comment by brian-brazil** [comment]
Glad you're sorted out.

**Comment by pwaller** [comment]
Thanks for the exceptional response time :+1:  :clap:

**Comment by davidlwillson** [comment]
I'll suggest that it would be cool if Prometheus could detect the problem and say something like: You're trying for every 30s, but your samples seem to be every 60s. Decrease the granularity of your report, or increase the granularity of your samples.
