### ISSUE TITLE
There is a tag v2.52.1 with no release or Docker images

### ISSUE THREAD

**Issue by remram44** [prometheus/prometheus#14291]
### What did you do?

Noticed tag 2.52.1, tried to install it

### What did you expect to see?

Prometheus running

### What did you see instead? Under which circumstances?

ImagePullBackOff

**Comment by beorn7** [comment]
This was tagged for a planned release, but then we never cut a release. Mostly because 2.53 is already underway.

@ArthurSens maybe you want to delete the tag, as we probably will never cut that release?

**Comment by ArthurSens** [comment]
Can this be done safely though? Should I add a [retract](https://go.dev/ref/mod#go-mod-file-retract) directive to go mod before that?

**Comment by beorn7** [comment]
I think you can safely delete the 2.52.1 tag because Go will only see the 0.52.1 tag, which you could leave in place.

**Comment by ArthurSens** [comment]
Yeah ok, I was trying to add the retract directive to v2.52.1 and the compiler was complaining about that... I'll just remove the tag then :)

**Comment by ArthurSens** [comment]
Done, sorry for the inconvenience @remram44!

**Comment by oseiberts11** [comment]
> For extra context, there's an extensive [slack thread](https://cloud-native.slack.com/archives/C01AUBA4PFE/p1717081750932189) with all the problems we faced in that release 😕

Referring to a place where you need to login to read anything isn't very helpful, I'm afraid. Apart from the fact that a chat system simply isn't documentation.

**Comment by beorn7** [comment]
To clarify in case others feel like missing out: What @ArthurSens linked to, isn't documentation. Just informational context and (literally) chat.

Having said that, I agree that even for "mere" chat, Slack is really a bad fit for an open source project. But everyone knows that already. It's a problem we cannot solve in the scope of this issue.
