### ISSUE TITLE
Use tls config code in common

### ISSUE THREAD

**Issue by brian-brazil** [prometheus/prometheus#1430]
https://github.com/prometheus/common/pull/31 copied the tls config code over to common so it could be shared with the blackbox exporter. We should switch prometheus over to use this too for consistency. It's likely the alertmanager will also end up using this for webhook and/or HA.

**Comment by fabxc** [comment]
I'm not 100% confident yet that this is something where shared code is the
best solution.

This will spread out into sharing code for a lot a similar small things up
to a point where things become unnecessarily static.

**Comment by brian-brazil** [comment]
I'm planning on sharing all the auth&ssl code for http as I'm expecting an identical need across 3 repos. Having separate copies would lead to divergence.

I'm not seeing anything else that could be shared currently.

**Comment by fabxc** [comment]
Factoring out code to common packages can make sense of course but should
happen more carefully.

The referenced PR factors out code from two packages with significant
design issues into a single shared one.

It's easy to say that we can always change it - but that's not reality with
these things.

**Comment by fabxc** [comment]
And not seeing anything currently is not the issue - with the next thing
remotely similar that's used more than once it will be "this is a perfect
fit for that common package".

**Comment by skebo** [comment]
+1 for use of common code for auth&ssl for http.  my specific use case is marathon with basic authentication.

**Comment by brian-brazil** [comment]
This was done.
