### ISSUE TITLE
Crash bug: Seems to happen when swapping with wait time around 20-40%

### ISSUE THREAD

**Issue by RichiH** [prometheus/prometheus#1431]
Crash log see https://gist.github.com/RichiH/aefd6350a90ae1561b21

**Comment by brian-brazil** [comment]
Are you sure you didn't OOM?

**Comment by RichiH** [comment]
I am not.

**Comment by RichiH** [comment]
Seems to be cut off at the top, so I am closing it. Sorry for the noise.

**Comment by RichiH** [comment]
Jftr, it was not OOM.
