### ISSUE TITLE
Changing one of gauge metric labels creates two overlapping time series

### ISSUE THREAD

**Issue by bvasiliev** [prometheus/prometheus#14320]
### What did you do?

I collect NVMe device metrics using the standard node-exporter. The `nvme_device_info` metric , with type `gauge`, has some labels, including `device` and `serial`.

Label `device` may be changed in time for the same `serial` and the same physical device during host reboot e. g. 

### What did you expect to see?

I expect all the labels for the same metric to remain consistent over time and source, even if one of them is updated.

### What did you see instead? Under which circumstances?

After the source host reboot and the `device` label change, Prometheus returns two overlapping time series for each with new and old `device` label values for 3 times:

![nvme_device_info afrer device label change](https://github.com/prometheus/prometheus/assets/2996932/e263b531-6455-49e7-a6d0-d8492b03cd80)

One of the overlapping time series has wrong label pairs that do not correspond to the data source.
Metrics in the source text file during label change are consistent and do not contain duplicate values:
```
$ grep -e nvme_device_info -e nvme_data_units_written_total /var/lib/prometheus/node-exporter/nvme.prom

# HELP nvme_data_units_written_total Number of 512-byte data units written by host, reported in thousands
# TYPE nvme_data_units_written_total counter
nvme_data_units_written_total{device="nvme1n1"} 6.1718292e+07
nvme_data_units_written_total{device="nvme0n1"} 4.0432075e+07
# HELP nvme_device_info Device information
# TYPE nvme_device_info gauge
nvme_device_info{device="nvme1n1",firmware="3B7QCXE7",model="Samsung SSD 960 EVO 250GB",serial="S3ESNX0J913905P"} 1.0
nvme_device_info{device="nvme0n1",firmware="3B7QCXE7",model="Samsung SSD 960 EVO 250GB",serial="S3ESNX0K464894P"} 1.0
```

This behavior breaks many-to-one group with other metrics and the overall monotonicity. For example, request
`nvme_data_units_written_total{} * on(device) group_left(serial,model) nvme_device_info{serial="S3ESNX0K464894P"}
`
return broken time series which are impossible to aggregate and rate():

![nvme_data_units_written_total group_left after device label change](https://github.com/prometheus/prometheus/assets/2996932/5609a12d-b84c-47e8-8866-c4ecc1e1aded)

### System information

Linux 6.8.0-35-generic x86_64

### Prometheus version

```text
prometheus, version 2.45.3+ds (branch: debian/sid, revision: 2.45.3+ds-2build1)
  build user:       team+pkg-go@tracker.debian.org
  build date:       20240401-07:14:21
  go version:       go1.22.1
  platform:         linux/amd64
  tags:             unknown
```

### Prometheus configuration file

```yaml
global:
  scrape_interval:     60s
  evaluation_interval: 60s
```

**Comment by beorn7** [comment]
First of all: If a label value changes, it creates a new series, also called a metric. So to get the terminology right, you _are_ creating a new metric (and remove an old one).

Staleness handling in Prometheus should handle exactly this case, i.e. you should not see the overlap.
However, as you can see the overlap, my assumption is that your node_exporter instance actually exposes both metrics at the same time for a few minutes. You could check that by manually looking at the `/metrics` endpoint of your node_exporter during the time of a change. If you see the duplication there, you need to troubleshoot your node exporter next.

**Comment by bvasiliev** [comment]
@beorn7 thank you for attention!

I've checked node_exporter's `/metric` by running every minute script `curl http://localhost:9100/metrics -o - 2>1 | grep -e ^nvme_device_info -e ^node_textfile_scrape_error | ts "[%Y-%m-%d %H:%M:%S]" >> node-exporter-test.txt` including the time of the change and didn't find any duplications at all.

![prometheus-overlap2](https://github.com/prometheus/prometheus/assets/2996932/37922567-9da2-4852-bed3-7a5e692d28ef)
 ![metrics-log](https://github.com/prometheus/prometheus/assets/2996932/346b5130-51d2-4575-b0fe-eea5b97ca692)


But in this attempt, I made requests in real-time and noticed that, from the moment of the change (reboot) at 18:29:00 until the moment at 18:32:00, on the graph above there was only one series labeled {device="nvme0n1"}. The new series {device="nvme1n1"} appeared in the database's results at 18:33:00 with three retrospective values.

**Comment by beorn7** [comment]
Are you using normal scrapes to collect the date, or are you doing something special? It looks like staleness isn't working in your case, and you seem to have delayed ingestion. Are you maybe using the OTel collector in between?

**Comment by beorn7** [comment]
Are you using timestamps in your nvme.prom files?

**Comment by bvasiliev** [comment]
No, I don't use timestamps.

nvme.prom is generated by the [prometheus-community/node-exporter-textfile-collector-scripts/nvme_metrics.py](https://github.com/prometheus-community/node-exporter-textfile-collector-scripts/blob/master/nvme_metrics.py) without timestamps.

Sample: [nvme.prom.gz](https://github.com/user-attachments/files/16028481/nvme.prom.gz)

**Comment by beorn7** [comment]
I have run out of explanations. I cannot imagine that the staleness handling doesn't work as expected in such a vanilla situation (or in other words: I don't think this is a bug in Prometheus).

I strongly suspect something subtle is off in your setup. Feel free to further troubleshoot and provide more evidence here. Maybe somebody else is seeing the same.

**Comment by beorn7** [comment]
Maybe we are back at the assumption that your node exporter is indeed exposing all those series at the same time for a short period, and your Prometheus happens to scrape in exactly that moment (while your `curl` wasn't so "lucky"). Just another wild guess.

**Comment by bvasiliev** [comment]
> exposing all those series at the same time for a short period, and your Prometheus happens to scrape in exactly that moment (while your `curl` wasn't so "lucky")

nvme.prom is written through sponge 
`/usr/share/prometheus-node-exporter-collectors/nvme_metrics.py | sponge /var/lib/prometheus/node-exporter/nvme.prom`
and I think we can rely on its integrity in time.

An overlaps every time lasts for three intervals/minutes but `curl` shows a changes immediately. Values did not flap in time not in `/metrics` curl, not in tsdb. Labels change only once and an interval between changes is constant. I think we can also exclude stochastic processes.

**Comment by machine424** [comment]
Perhaps the node_exporter is being scraped twice during that time period. The target from before the reboot is still being scraped at the same time as the new one. Do node-exporters run in containers?

You might want to examine the `prometheus_sd_discovered_targets`, `prometheus_target_scrape_pool_targets`, and `node_textfile_mtime_seconds` metrics.

I notice that curl is scraping `localhost:9100`, but Prometheus is pointed to `chronos:9100`. Perhaps curl doesn’t accurately reflect the scraping. Maybe the target scraped by prometheus exposes the old+new series during that time period.

You can take a look at the `scrape_series_added` and `scrape_samples_scraped` metrics.

**Comment by bvasiliev** [comment]
I've created synthetic metrics that swap labels every 1m, 5m, 15m intervals [    bvasiliev/prometheus-overlap-test](https://github.com/bvasiliev/prometheus-overlap-test) to localize the issue. 

I found that, with uninterrupted operation of Prometheus, labels changes are handled as expected.

But the issue occurs when a label is changed while Prometheus is off, and a downtime is shorter than a `scrape_interval`. So yes, under these conditions the node_exporter is being scraped twice.

Below are the charts showing the Prometheus restart at 09:45 and the shutdown for one minute at 09:55:

![1m](https://github.com/prometheus/prometheus/assets/2996932/438c1e26-690b-438b-8d11-f5d8279658d5)
![5m](https://github.com/prometheus/prometheus/assets/2996932/855e4460-b0b5-4ba2-9ad3-059c1dbdd56a)

**Comment by machine424** [comment]
I hadn’t realized that Prometheus itself was restarted. In such a case, because Prometheus cannot write the staleness markers, I believe it will fall back to the old behavior of "keeping the series for X intervals before dropping it." This behavior seems to be what you’re observing.

By the way, good debugging effort!

**Comment by bvasiliev** [comment]
> I hadn’t realized that Prometheus itself was restarted

Oh, that little detail I didn't highlight :-) 

I temporarily masked this with a start delay in the prometheus-node-exporter.service unit: 
```
[Service]
ExecStartPre=/usr/bin/sleep 60
```

I'm not sure if this staleness behavior is a bug, but I think it may not be uncommon in scenarios where Prometheus is in agent mode.

**Comment by beorn7** [comment]
For staleness handling to work across restarts, we needed to reconstruct a lot of state from the scraping… not sure if it is worth the effort.

I'll close this issue as we know now what happens.

A "restart-resilient staleness handling" feature would be quite involved and require a design doc. If somebody wants to work on it, please let us know.
