### ISSUE TITLE
remote_write client metrics: a partially failed batch is counted as all samples failed

### ISSUE THREAD

**Issue by thampiotr** [prometheus/prometheus#14323]
### What did you do?

1. Using a remote_write pipeline to send samples and exemplars to a remote backend
2. A batch of samples and exemplars is sent, for example 2000 samples and 1 exemplar. 
3. The one exemplar is rejected, for example, [due to this issue](https://github.com/prometheus/prometheus/issues/13577).
4. remote_write receives an HTTP status 400, logs a "non-recoverable" error log message and drops the batch
5. The [failure metrics are incremented](https://github.com/prometheus/prometheus/blob/5a218708f1f755a67b3d9b68549ccbbb6463d850/storage/remote/queue_manager.go#L1541-L1543) with number of samples/exemplars/histograms in the entire batch. Even if all samples were ingested, but only one exemplar failed.

### What did you expect to see?

1. The [failure metrics](https://github.com/prometheus/prometheus/blob/5a218708f1f755a67b3d9b68549ccbbb6463d850/storage/remote/queue_manager.go#L1541-L1543) would ideally reflect how many data points have failed in the batch. Otherwise we don't have accurate success rate metrics.
2. Exemplars / native histograms are experimental. It may be desirable to retry the batch without exemplars and native histograms to not drop the samples?

### What did you see instead? Under which circumstances?

The [failure metrics](https://github.com/prometheus/prometheus/blob/5a218708f1f755a67b3d9b68549ccbbb6463d850/storage/remote/queue_manager.go#L1541-L1543) counted the entire batch as failed, even when the samples were ingested correctly.

### Logs

```text
ts=2024-06-19T17:38:16.946175Z level=error msg="non-recoverable error" ... url=(...) count=5 exemplarCount=1 err="server returned HTTP status 400 Bad Request: send data to ingesters: failed pushing to ingester ...: user=...: err: out of order exemplar. timestamp=2024-06-19T17:35:15Z, series=a_test_total{...}, exemplar={...}"
```

**Comment by bwplotka** [comment]
Quick question - can you instead rely on server side metrics?

**Comment by thampiotr** [comment]
> Quick question - can you instead rely on server side metrics?

If we have clients remote_write-ing from multiple sites with different failure rates, it may not be always possible to distinguish which client is having SR issues (depends on labels that the backend sets). The server-side metrics can help in some cases, but more accurate client-side metrics I think would be better.

**Comment by cstyan** [comment]
Remote Write Sender users are not always also operators of the Receiver side as well, such as SaaS users.

**Comment by bwplotka** [comment]
Thanks!

> operators of the Receiver side as well, such as SaaS users

Yea, but every SaaS should be expected to give you this metric, no? If we expect them to give you this number in PRW response one day, they have to have it anyway in some "system" metrics. (:  If they don't have such metric, likely they don't implement this feature either. 

To me one argument could be "but those system SaaS metrics" are on different endpoint etc for some providers. Perhaps another argument is to have consistent or more precise alerting on client side for different providers too, but one would challenge this one too e.g. let's say you have structured PRW response with number of samples rejected (or I guess rejected exemplars in separation?). In this case indeed if you have exemplars rejected but sample written could make this alert in lower prio. But if you have like 0.1% samples rejected, would you set alert with lower priority too? Is it worth to have this precision (batches are usually only 200 samples wide).

> The one exemplar is rejected, for example, https://github.com/prometheus/prometheus/issues/13577.

Hm, this is for OTLP ingestion though, are we sure this can happen for PRW too?

**Comment by bwplotka** [comment]
Nevertheless, there might be a valid reasons to experiment on some Receiver response format structure, similar to [OTLP](https://github.com/open-telemetry/opentelemetry-proto/blob/v1.3.1/opentelemetry/proto/collector/metrics/v1/metrics_service.proto#L64) approach. 

We could totally add it in 2.x Remote Write as "SHOULD" or/and start with Prometheus experimental implementation first. I think it would epic to innovate and play with different formats (proto/JSON, number of samples or also exemplars, adding reasons, establishing versioning and negotiation of this). Help wanted 🤗 

It's unlikely we change 2.0 as we are just [announcing experimental state](https://github.com/prometheus/docs/pull/2462) and ideally we don't add more adoption friction. This was [discussed at on Slack public channel a bit](https://cloud-native.slack.com/archives/C06B8KJUU2Y/p1718895205682679) and [mentioned](https://github.com/prometheus/proposals/blob/3d85921828eeee033fd71f8730a1638bc5307f4a/proposals/2024-04-09_remote-write-20.md#partial-writes:~:text=One%20idea%20came%20from%20the%20Grafana%20Agent/Alloy%20maintainer%2C) in our [proposal](https://github.com/prometheus/proposals/pull/35). Hope that makes sense, but feel free to challenge anything here.

Cheers!

**Comment by bwplotka** [comment]
Added this issue to https://github.com/prometheus/prometheus/issues/13105#issue-1982617705

**Comment by thampiotr** [comment]
> Hm, this is for OTLP ingestion though, are we sure this can happen for PRW too?

I believe yes. For example, if you shard the targets among multiple clients that scrape & remote_write with a Receiver that has OOO window enabled, you won't face issues when targets move between instances and occasionally send OOO samples. However, when you enable exemplars or native histograms, which do not support OOO ingestion currently, you will start to see entire batches failing on the client side. We see this with Alloy clustering.

So I'm not sure if the missing support for OOO exemplars should be treated as OTEL-specific, it's useful for other use cases too.

**Comment by bwplotka** [comment]
FYI: We might actually fix this in 2.0 spec as there is even stronger reason to do similar, feel free to give feedback https://github.com/prometheus/prometheus/issues/14359

**Comment by bwplotka** [comment]
This is now fixed when PRW 2.0 is used https://github.com/prometheus/prometheus/pull/14444

Fixing this in 1.0 spec is not in scope as it's now deprecated.

**Comment by bboreham** [comment]
RW1 is deprecated?  Where?

**Comment by cstyan** [comment]
> RW1 is deprecated? Where?

Not yet deprecated, but we're not making a 1.1 so the changes made for 2.0 in the referenced PR do not need to also be made tot the 1.0 code.
