### ISSUE TITLE
remote write: infinite retry of "recoverable" issues

### ISSUE THREAD

**Issue by machine424** [prometheus/prometheus#14350]
### Proposal

The DNS lookup issues, for example, are considered "recoverable" issues. https://github.com/prometheus/prometheus/blob/6572b1fe631e00440a2c682f8f966232f697d358/storage/remote/client.go#L223-L227 and are endlessly retried https://github.com/prometheus/prometheus/blob/c5040c5ea9e70b6525cd6942fb26a1bdb32510d6/storage/remote/queue_manager.go#L1673-L1677

Logs like the following are emitted:

```
ts=2024-06-14T01:28:01.804Z caller=dedupe.go:112 component=remote level=warn remote_name=5ca657 url=http://invalid-remote-storage.example.com:9090/api/v1/write msg="Failed to send batch, retrying" err="Post \"http://invalid-remote-storage.example.com:9090/api/v1/write\": dial tcp: lookup invalid-remote-storage.example.com on 172.30.0.10:53: no such host"
```
However, logs can easily be missed and are not regularly checked.

The DNS lookup issue could be due to a mistake in the endpoint URL.

While I understand that not retrying the samples means dropping them, perhaps having a metric and alert for such long retries could be helpful.

The DNS lookup is just one example, the same can apply for other "recoverable" issues.

Or maybe the remote write endpoint should warn about this: Prometheus hasn't sent me anything? But it means it should support alerting...

**Comment by machine424** [comment]
@simonpasquier pointed out to me that the`PrometheusRemoteWriteBehind` alert https://github.com/prometheus/prometheus/blob/3d54bcc018df3e081758db3e13a49f9a2566c49b/documentation/prometheus-mixin/alerts.libsonnet#L210-L219 should trigger in such cases.

It turns out that one of the metrics, `prometheus_remote_storage_queue_highest_sent_timestamp_seconds`, used in that alert is no longer initialized, resulting in the alert never firing. 

We’ll see whether we can reinitialize the metric again https://github.com/prometheus/prometheus/pull/8060/files#r1664064996.

**Comment by bboreham** [comment]
I want to point out the reason this was changed was in #8046, that the chart is hard to read when the initial "behind" value is 50+ years.

**Comment by machine424** [comment]
> I want to point out the reason this was changed was in #8046, that the chart is hard to read when the initial "behind" value is 50+ years.

Yep, https://github.com/prometheus/prometheus/pull/8046 fixes the dashboards, that's why I opened https://github.com/prometheus/prometheus/pull/14437 to revert #8060 as I don't think it's a must-have

**Comment by dimitarvdimitrov** [comment]
@machine424 you mentioned misconfiguration. Doesn't `PrometheusRemoteStorageFailures` cover these cases? 

We just hit an issue with 2.54.0 (with https://github.com/prometheus/prometheus/pull/14437) where there is a remote-write endpoint, but there are no series to send to it. So `PrometheusRemoteWriteBehind` is falsely firing.

**Comment by replay** [comment]
I agree with @dimitarvdimitrov that the correct alert to catch write errors is `PrometheusRemoteStorageFailures`, not `PrometheusRemoteWriteBehind`. With the current definition of the `PrometheusRemoteWriteBehind` alert it will trigger if there is no data to send and if `prometheus_remote_storage_highest_timestamp_in_seconds` has been initialized to a non-0 value.

**Comment by machine424** [comment]
The `PrometheusRemoteStorageFailures` metric only catches unrecoverable errors: https://github.com/prometheus/prometheus/blob/c5040c5ea9e70b6525cd6942fb26a1bdb32510d6/storage/remote/queue_manager.go#L1673-L1677.

Since network-related issues are considered recoverable https://github.com/prometheus/prometheus/blob/6572b1fe631e00440a2c682f8f966232f697d358/storage/remote/client.go#L223-L227), if a new new remote-write endpoint is added and Prometheus can’t reach it (like if the URL is wrong), no alert would trigger before https://github.com/prometheus/prometheus/issues/14350. Now, you can catch that with `PrometheusRemoteWriteBehind`.

Also, it’s a good practice to initialize series https://prometheus.io/docs/practices/instrumentation/#avoid-missing-metrics.

> We just hit an issue with 2.54.0 (with https://github.com/prometheus/prometheus/pull/14437) where there is a remote-write endpoint, but there are no series to send to it. So PrometheusRemoteWriteBehind is falsely firing.

If you’re sure the endpoint won’t be used, it’s probably better to just remove it from the config.
But if the endpoint is only going to be used occasionally (like it’s only interested in certain series that show up from time to time), then it might be best to disable `PrometheusRemoteWriteBehind` for that endpoint since the alert, and the logic behind it, assume continuous data flow.
