### ISSUE TITLE
Replace go-kit/log with log/slog

### ISSUE THREAD

**Issue by jan--f** [prometheus/prometheus#14355]
### Proposal

As @SuperQ proposed on Slack, the 3.0 release would be a good opportunity to replace `go-kit/log` with `log/slog`.

Afaiu the goal is to keep the log output format close to what is logged today with changes where needed.
Some cli flag behavior will probably have to change.

**Comment by roidelapluie** [comment]
This is a good idea.

**Comment by ansh-devs** [comment]
@jan--f  Hi, is it possible for me pick this one up?

**Comment by jan--f** [comment]
@ansh-devs yeah I think you can contribute to this. Please reach out to @SuperQ, he might be working on this already. Join us on slack for a quicker discussion.

**Comment by tjhop** [comment]
Hey all, prometheus/common#677 is ready for review. Once that's done with review and merged, I'll get started converting prometheus to use slog :+1:

**Comment by tjhop** [comment]
I'm nearly finished converting prometheus to use slog via the new promslog package in prometheus/common. I'll open it as a draft PR when ready so we can tear it apart 👍

**Comment by tjhop** [comment]
#14906 has been merged!
