### ISSUE TITLE
data point not found 

### ISSUE THREAD

**Issue by ringtail** [prometheus/prometheus#1436]
Here is my metrics api  
```
# HELP etcd_rafthttp_message_sent_failed_total The total number of failed messages sent. 
# TYPE etcd_rafthttp_message_sent_failed_total counter
etcd_rafthttp_message_sent_failed_total{msgType="MsgVote",remoteID="d4a60b0448bfed3e",sendingType="pipeline"} 1
```
but I got No datapoints found in prometheus.    

```
version:prometheus-0.16.1.linux-amd64
```

**Comment by ringtail** [comment]
I try to check ntp service and it is still not work.

**Comment by beorn7** [comment]
Can you describe in more detail what you have done to get that error message? Also, can you describe what kind of investigation/troubleshooting you have already applied? What do you mean by "I try to check ntp service"?

**Comment by juliusv** [comment]
@ringtail Have you verified that both machines have the same time configured (is that what you mean by "check ntp service"?)? Otherwise the sample times might be off and you'd have to change the end time in your graph to see anything.

**Comment by ringtail** [comment]
yes I have checked the ntp service and the result is like this.    
<img src="http://moyuan.oss-cn-beijing.aliyuncs.com/github/f67ca4d8140aa2757ee88ed958e5feb3.png"/>

**Comment by ringtail** [comment]
here is my code without sdk
```
/*
 * jenkinsNodeBase
 * https://github.com//jenkinsnodebase
 *
 * Copyright (c) 2016
 * Licensed under the MIT license.
 */

'use strict';
var express = require('express');
var app = express();

// respond with "hello world" when a GET request is made to the homepage
app.get('/metrics', function(req, res) {
  res.format({
    'text/plain': function(){
      res.send(
      '# HELP suminfo_proxytimes The total number of failed messages sent. \n'+
      '# TYPE suminfo_proxytimes counter\n' +
      'suminfo_proxytimes{msgType="MsgVote",remoteID="d4a60b0448bfed3e",sendingType="pipeline"} 1');
    }
  })
});

app.listen(3000, function () {
	  console.log('Example app listening on port 3000!');
});
```

**Comment by grobie** [comment]
Is prometheus able to scrape your server? Is your instance listed on the `/status` as healthy?

**Comment by ringtail** [comment]
yes. prometheus can scrape my server.the node is listed and healthy. all metrics can list.

**Comment by grobie** [comment]
Can you paste the query you were executing and expecting to return data?

**Comment by ringtail** [comment]
simply set the key and try to test data point 
<img src="http://moyuan.oss-cn-beijing.aliyuncs.com/github/f67ca4d8140aa2757ee88ed958e5feb3.png"/>

**Comment by grobie** [comment]
Ah, now I see your first image as well. In your code example, you use a lower case i `suminfo_proxytime`, but that's probably not it.

Can you select the metric from the drop-down list next to the execute button?

**Comment by ringtail** [comment]
this is no item named suminfo_proxytime

**Comment by beorn7** [comment]
How does the Status tab on your Prometheus server look like? You should see which targets it scrapes, and you can click on the endpoints to see what is being scraped.

**Comment by ringtail** [comment]
here is the status tab and data sources
<img src="http://moyuan.oss-cn-beijing.aliyuncs.com/github/b2ea53a8ed16e60b6b81795f5bf46409.png"/>
<img src="http://moyuan.oss-cn-beijing.aliyuncs.com/github/b2ea53a8ed16e60b6b81795f5bf46409.png"/>

**Comment by beorn7** [comment]
That looks good.

Completely different idea: Looking at your node.js code, it looks like you are missing a "\n" at the end of your input. That would explain it (but should also create a log message).

**Comment by ringtail** [comment]
@beorn7 awesome!!!!!!!  thank you very much!!!!!

**Comment by beorn7** [comment]
So I assume it helped? :-)

Please re-open if not.
