### ISSUE TITLE
[Feature] Add new labels to time series

### ISSUE THREAD

**Issue by patilsuraj767** [prometheus/prometheus#14402]
### Proposal

While using `promtool tsdb create-blocks-from openmetrics` to create a tsdb blocks there should be a way to add custom labels to time series.

**Comment by tjhop** [comment]
While not as straightforward as doing it all in one command, it is at least possible to relabel a local tsdb block using the `thanos tools bucket rewrite` command with the local filesystem:

https://thanos.io/tip/components/tools.md/#bucket-rewrite
