### ISSUE TITLE
@ modifier with future return inconsistent value for sum_over_time

### ISSUE THREAD

**Issue by Jzeemo** [prometheus/prometheus#14418]
### What did you do?

I have a gauge metric that tracks device_status (ON/OFF). I would like to determine how many seconds a device was ON for a given period (e.g., yesterday, the current week, or the current month).

For example, to calculate the ON time for the current week number, I am using the following Prometheus query:

`sum_over_time((device_status{device_id="10000001"})[604800s:1s] @EndofRequestedWeek)`

Technically, the return value should be greater than or equal to the total seconds in the given period since it sums the value over time.

However, I am encountering inconsistencies in the results. Sometimes I receive a value of, for example, 6000 seconds, but other times it is 5200 seconds.

It only happens when I set the @ modifier with future. If I test with time From NOW to the past, this issue won't happen.

### What did you expect to see?

I expect to see the result keep increasing for sum_over_time with future modifiers as long as the range over the current time.

### What did you see instead? Under which circumstances?

I saw some timestamp values are missing.

First Query | Second Query
-- | --
1 @1720163018 | 1 @1720163018
1 @1720163019 | 1 @1720163019
1 @1720163020 | 1 @1720163020
1 @1720163021 | 1 @1720163021
1 @1720163022 | 1 @1720163022
1 @1720163023 | 1 @1720163023
1 @1720163024 | 1 @1720163024
1 @1720163025 | 1 @1720163035
1 @1720163026 | 1 @1720163036
1 @1720163027 | 1 @1720163037
1 @1720163028 | 1 @1720163038
1 @1720163029 | 1 @1720163039
1 @1720163030 | 1 @1720163040
1 @1720163031 | 1 @1720163041
1 @1720163032 | 1 @1720163042
1 @1720163033 | 1 @1720163043
1 @1720163034 | 1 @1720163044
1 @1720163035 | 1 @1720163045
1 @1720163036 | 1 @1720163046
1 @1720163037 | 1 @1720163047
1 @1720163038 | 1 @1720163048
1 @1720163039 | 1 @1720163049
1 @1720163040 | 1 @1720163055
1 @1720163041 | 1 @1720163056
1 @1720163042 | 1 @1720163057
1 @1720163043 | 1 @1720163058
1 @1720163044 | 1 @1720163059

### System information

Ubuntu 22.04.4 LTS

### Prometheus version

```text
Build Information
version	2.53.0
revision	4c35b9250afefede41c5f5acd76191f90f625898
branch	HEAD
buildUser	root@7f8d89cbbd64
buildDate	20240619-07:39:12
goVersion	go1.22.4
```

### Prometheus configuration file

```yaml
global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:4000']
```

**Comment by beorn7** [comment]
Using `@` with future values is prone to be used in the wrong way. Note that the the value in the future is (most likely) just not there rather than 1 or 0. However, since the series (in most cases) doesn't have a staleness marker if it ist still actively scraped, you'll get 5m of repeating the most recent value in your sub-query.

From your description, I cannot say if Prometheus is doing anything wrong, but I'm pretty sure that the query you are using won't really give you what you want for @-values in the future.

**Comment by Jzeemo** [comment]
@beorn7 , thank you. I understand that the value in the future is not just 1 or 0, so I expected it to return nothing.

Regarding the time sequence:

Past- - - - - - Current Time ---------@ modifier

I expected the data from the past up to the current time, with no data from the current time to @ modifier. I am not predicting any future values either. If my expectation is wrong for @ modifier, Could you please correct me?

Regarding the statement:

**"However, since the series (in most cases) doesn't have a staleness marker if it is still actively scraped, you'll get 5m of repeating the most recent value in your sub-query."**

I couldn't find any related documentation about receiving 5 minutes of repeating the most recent value in my sub-query. Could you please point me to where I can find it?

**Comment by beorn7** [comment]
https://prometheus.io/docs/prometheus/latest/querying/basics/#staleness
