### ISSUE TITLE
Consider passing through escaped non-escape sequences

### ISSUE THREAD

**Issue by grobie** [prometheus/prometheus#1443]
Prometheus is currently [very strict about escaped characters if these are not an escape sequence](https://github.com/prometheus/prometheus/blob/master/promql/lex.go#L643).

This requires characters in regular expressions to [be double escaped](http://demo.robustperception.io:9090/graph#%5B%7B%22range_input%22%3A%221h%22%2C%22end_input%22%3A%22%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3A%22%22%2C%22expr%22%3A%22node_uname_info%7Binstance%3D~%5C%22demo%5C%5C.robustperception%5C%5C.io%5C%5C%3A9100%5C%22%7D%22%2C%22tab%22%3A1%7D%2C%7B%22range_input%22%3A%221h%22%2C%22end_input%22%3A%22%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3A%22%22%2C%22expr%22%3A%22node_uname_info%7Binstance%3D~%5C%22demo%5C%5C%5C%5C.robustperception%5C%5C%5C%5C.io%5C%5C%5C%5C%3A9100%5C%22%7D%22%2C%22tab%22%3A1%7D%5D).

This makes it bit more inconvenient to escape meta characters in regular expressions. More problematic though, it is an issue with Grafana among others, which escapes all kinds of characters by default https://github.com/grafana/grafana/issues/2918.

If we just ignore such cases, we should make it easier for people to escape meta characters in regular expressions. It should be backwards compatible, as a currently escaped backslash will continue to work.

**Comment by brian-brazil** [comment]
Trying to do magic with escaping is risky, as it makes it unclear exactly which layer is interpreting which escape sequences. It gets to be even more fun if a layer changes the escape sequences it knows about.

I'm for keeping a strict definition of escaping. Letting our users be lax in how many backslashes they must provide is likely to cause more problems than it solves in the long run.

> This makes it bit more inconvenient to escape meta characters in regular expressions.

That's completely normal. If we want to avoid that in a sane way we'd have to look at something like Python's `r` string literal modifier - which we already pretty much have via backticks.

**Comment by grobie** [comment]
Oh, to be honest, I didn't know about the backtick behavior. So instead of changing the behavior of the backslash, we'd need to ask users to use backticks in such situations? This sounds reasonable to me.

**Comment by brian-brazil** [comment]
Backticks can't handle backticks inside them, so to be fully generic a client would have to support our escaping.
