### ISSUE TITLE
`navigator.clipboard` may not be available

### ISSUE THREAD

**Issue by vitoyucepi** [prometheus/prometheus#14432]
### What did you do?

1. Start Prometheus locally.
   `docker run -it -p 9090:9090 prom/prometheus`.
1. Start a clean chromium profile.
   `chromium --user-data-dir="/tmp/test/data" --disk-cache-dir="/tmp/test/cache"`.
1. Access local ip from chromium.
   Use network ip, for example *192.168.0.1:9090*, not *localhost* or *127.0.0.1*.
1. Type an expression, for example `up`.
1. Press *Execute*.
1. Open browser development tools. Press *F12* or *Ctrl-Shift-i*.
1. Try to copy the label.
   For example, try to copy `instance="localhost:9090"`.
1. See error in dev tools.

Ref: #11229

### What did you expect to see?

No error in dev tools.

### What did you see instead? Under which circumstances?

```
main.b9e603c4.js:2 Uncaught TypeError: Cannot read properties of undefined (reading 'writeText')
    at r (main.b9e603c4.js:2:582187)
    at Object.Ie (main.b9e603c4.js:2:1056216)
    at $e (main.b9e603c4.js:2:1056370)
    at main.b9e603c4.js:2:1074595
    at wo (main.b9e603c4.js:2:1074689)
    at ko (main.b9e603c4.js:2:1075104)
    at main.b9e603c4.js:2:1080752
    at Ce (main.b9e603c4.js:2:1156473)
    at main.b9e603c4.js:2:1076572
    at Co (main.b9e603c4.js:2:1076602)
```

### System information

Linux 6.9.6 x86_64

### Prometheus version

```text
prometheus, version 2.53.0 (branch: HEAD, revision: 4c35b9250afefede41c5f5acd76191f90f625898)
  build user:       root@7f8d89cbbd64
  build date:       20240619-07:39:12
  go version:       go1.22.4
  platform:         linux/amd64
  tags:             netgo,builtinassets,stringlabels
```

### Prometheus configuration file

```yaml
No
```

### Alertmanager version

```text
No
```

### Alertmanager configuration file

```yaml
No
```

### Logs

```text
No
```

**Comment by stavros-tsioulis** [comment]
navigator.clipboard is only available in secure contexts: which are https sites or localhost / 127.0.0.1.
https://developer.mozilla.org/en-US/docs/Web/API/Navigator/clipboard

**Comment by juliusv** [comment]
Thanks for the detailed report! We're building a new Prometheus UI at the moment (available in the `mantine-ui` branch and testable by setting the `--enable-feature=new-ui` command-line flag). At least with that UI (which uses Mantine's `useClipboard()` hook), it seems to be working even from non-localhost + HTTP.

Since I hope we can make the new UI more widely available sometime in the next few months, I'll close this issue for now as will-be-fixed-in-new-ui.
