### ISSUE TITLE
Prometheus Staleness Issue on Fedora 39

### ISSUE THREAD

**Issue by nikteliy** [prometheus/prometheus#14441]
### What did you do?

I am currently using Fedora 39 and have both Prometheus (version 2.32) and Prometheus Node Exporter (version 1.6.1) installed. I have encountered an issue with Prometheus where it continues to write the last value for an additional 5 minutes after I stop the prometheus-node-exporter service.
But when I use any aggregated function, those 5 minutes disappear.
![charts](https://github.com/prometheus/prometheus/assets/52915342/15b6a0e4-cfd8-4817-8e44-f36c86434e1f)

It seems similar to the [staleness behavior](https://prometheus.io/docs/prometheus/latest/querying/basics/#staleness) for metrics with their own timestamps, but that does not appear to be the case here.

### What did you expect to see?

I expected that the last point on my graph would be at the same time as when I stopped the prometheus-node-exporter service.

### What did you see instead? Under which circumstances?

Instead, I observed that Prometheus continued to write the last value for an additional 5 minutes after I stopped the prometheus-node-exporter service. This behavior occurred every time I stopped the service.

### System information

Linux 6.8.11-200.fc39.x86_64 x86_64

### Prometheus version

```text
prometheus, version  (branch: , revision: )
  build user:       
  build date:       
  go version:       go1.21.6
  platform:         linux/amd64
```

**Comment by roidelapluie** [comment]
It seems like you're familiar with Prometheus's staleness handling, where it shows the last metric value for up to 5 minutes if no new data is received. However, if you're also stopping Prometheus at the same time as the `prometheus-node-exporter`, it might prevent the insertion of the invisible staleness marker. This marker indicates when data is considered stale after the 5-minute window. Without it, aggregation functions might not recognize the data as stale, resulting in the last data point being absent from your charts. It’s important to keep Prometheus running continuously to ensure proper handling of staleness markers.

**Comment by nikteliy** [comment]
Hi @roidelapluie 
Thank you for the response. The reason was that to pause metric collection, targets are removed from the Prometheus configuration. Unfortunately, I don't know of a better way to pause Prometheus. Anyway, I believe the issue can be closed.
