### ISSUE TITLE
Metrics in "/actuator/prometheus" are not consistent in a multi nodes environment (kubernetes)

### ISSUE THREAD

**Issue by ZakariaAitErrami** [prometheus/prometheus#14449]
### What did you do?

My application is built using Spring Boot and is deployed with multiple replicas in a Kubernetes cluster. I am using the /actuator/prometheus endpoint to expose metrics. However, I've noticed that the metrics returned by this endpoint are different and inconsistent depending on which server instance is accessed. When I refresh the /actuator/prometheus page, the values change based on the server I hit.

Is there a way to make the metric values consistent across all nodes?

### What did you expect to see?

I expect to see metrics are consistent across all nodes and not each node track its own metrics

### What did you see instead? Under which circumstances?

each node track its own metrics (If I aggregate metrics using a promql query I will then have duplicate)

**Comment by beorn7** [comment]
This seems to be a question about Spring Boot usage, not an issue in the Prometheus server.

Note that https://github.com/prometheus/prometheus/ is the repository for the Prometheus Server (and not "all of Prometheus"). I recommend to use our [community channels](https://prometheus.io/community/) to ask usage questions. In your particular case, you might also want to consider Spring Boot community channels.
