### ISSUE TITLE
Recommendation for PGO with Prometheus

### ISSUE THREAD

**Issue by Adib234** [prometheus/prometheus#14457]
### Proposal

Building Go programs with PGO [(profile guided optimization)](https://go.dev/doc/pgo) improves performance by 2-14% so I've been interested in doing this with Prometheus, what would be the recommended way of bringing this over to Prometheus?

I already have a system in place for continuous profiling which generates profiles that can be specified in the `-pgo` flag in `go build`, so what would be the ideal place to store these profiles? I plan on manually uploading the profiles and every time Prometheus is built, specify `-pgo` with the location of the manually uploaded profile

**Comment by bboreham** [comment]
See previous attempts at #12777 and #12889.
