### ISSUE TITLE
config: remove `expand-external-labels` feature flag in v3

### ISSUE THREAD

**Issue by beorn7** [prometheus/prometheus#14486]
### Proposal

I believe we should make use of the v3 release to finally remove the `expand-external-labels` feature flag and make the behavior "always on". The impact was anyway very low in practice, but it could have broken users in rare cases. The v3 release is the perfect opportunity to get this technically breaking change out of the feature flag limbo.

**Comment by jyz0309** [comment]
I would like to try this issue if not anybody is working on this. :-)

**Comment by beorn7** [comment]
Please go ahead, @jyz0309 . But be aware that this is just my proposal at this point. While I do believe it will end up as the consensus, there could still be objections. The code change should be easy, though, so no big risk.

**Comment by beorn7** [comment]
Note that the PR should be created against the [v3 release branch](https://github.com/prometheus/prometheus/tree/release-3.0).

**Comment by roidelapluie** [comment]
I agree

**Comment by ywwg** [comment]
[this is a copy-paste message on all unfinished breaking change items]
What is the status of this item?  We are beginning to reach the point where breaking changes may have to miss 3.0 unless they are wrapped up soon.

**Comment by ywwg** [comment]
updated the metadata on the PR so it's linked to the project board
