### ISSUE TITLE
scrape: Normalize `le` and `quantile` labels upon ingestion in v3

### ISSUE THREAD

**Issue by beorn7** [prometheus/prometheus#14485]
### Proposal

See https://github.com/prometheus/prometheus/issues/12984#issuecomment-1766592549 .

As far as I remember, we agreed to normalize the values of `le` labels of classic histograms and `quantile` labels of summaries to the OpenMetrics formatting rules in v3. I couldn't find any issue for that, and I don't think that has been implemented. See the comprehensive comment above for all the context.

**Comment by beorn7** [comment]
Just discovered that this issues hasn't got the "breaking" label. It would be very welcome to have this in v3 before we cut the final release.

**Comment by ywwg** [comment]
@machine424 are you still working on this? If not please let us know ASAP. If there is no update we will have to reassign or drop this from v3
