### ISSUE TITLE
v2.53.1 prometheus/promtool have CRITICAL loophole

### ISSUE THREAD

**Issue by xiaoyuan2019** [prometheus/prometheus#14547]
### What did you do?

check command：trivy image --db-repository m.daocloud.io/ghcr.io/aquasecurity/trivy-db --java-db-repository m.daocloud.io/ghcr.io/aquasecurity/trivy-java-db prometheus:v2.53.1

![image](https://github.com/user-attachments/assets/d34ff8a6-ed83-4de1-a2e0-0e24190b9396)
![image](https://github.com/user-attachments/assets/eac9b3ab-37d1-4473-8fd9-a4a4835a3889)

### What did you expect to see?

prometheus/promtool do not have HIGH and CRITICAL loophole，please hury up fixed，thanks！！！

### What did you see instead? Under which circumstances?

v2.53.1 prometheus/promtool have CRITICAL loophole

### Prometheus version

```text
Version	2.53.1
Revision	14cfec3f6048b735e08c1e9c64c8d4211d32bab4
Branch	HEAD
BuildUser	root@9f8e5b6970da
BuildDate	20240710-10:16:27
GoVersion	go1.22.5
```

**Comment by beorn7** [comment]
Please report security issues privately as described in https://prometheus.io/docs/operating/security/ . While doing so, please pay attention to the [section about automated security scanners](https://prometheus.io/docs/operating/security/#automated-security-scanners). Thank you very much.

**Comment by xiaoyuan2019** [comment]
@beorn7 send email？who is MAINTAINERS ？
![image](https://github.com/user-attachments/assets/084f69c1-9749-41ea-856c-71a0255ccd90)

**Comment by beorn7** [comment]
https://github.com/prometheus/prometheus/blob/main/MAINTAINERS.md
