### ISSUE TITLE
/api/v1/query requires time

### ISSUE THREAD

**Issue by AlekSi** [prometheus/prometheus#1460]
http://prometheus.io/docs/querying/api/#instant-queries says
> The current server time is used if the time parameter is omitted.

However, it is in fact required: `{"status":"error","errorType":"bad_data","error":"cannot parse \"\" to a valid timestamp"}`

https://github.com/prometheus/prometheus/blob/master/web/api/v1/api.go#L311 – no check for absent query argument.

**Comment by fabxc** [comment]
Which version are you running?

The defaulting to `now` is a bit further up before entering the parsing function: https://github.com/prometheus/prometheus/blob/master/web/api/v1/api.go#L132-L140

**Comment by grobie** [comment]
Please re-open if you have more questions.

**Comment by AlekSi** [comment]
Sorry, you are right, I used 0.16.1, where `time` is mandatory argument. Thanks.
