### ISSUE TITLE
prometheus store data into influxDB

### ISSUE THREAD

**Issue by ringtail** [prometheus/prometheus#1461]
can prometheus store data into influxdb

**Comment by guanglinlv** [comment]
see `prometheus --help`

```
...
   -storage.remote.influxdb-url 
      The URL of the remote InfluxDB server to send samples to. None, if 
      empty.
  
   -storage.remote.influxdb.database "prometheus"
      The name of the database to use for storing samples in InfluxDB.
  
   -storage.remote.influxdb.retention-policy "default"
      The InfluxDB retention policy to use.
  
   -storage.remote.influxdb.username 
      The username to use when sending samples to InfluxDB. The 
      corresponding password must be provided via the INFLUXDB_PW environment 
      variable.
...
```

**Comment by grobie** [comment]
https://prometheus.io/docs/introduction/roadmap/#long-term-storage

**Comment by jeunii** [comment]
`./prometheus -config.file=prometheus.yml -storage.remote.influxdb-url=http://127.0.0.1:8086 -storage.remote.influxdb.database=prometheus -storage.remote.influxdb.retention-policy=default -storage.remote.influxdb.username=admin`

I am using this command to write data into Influx DB. But seems like the InfluxDB for database Prometheus is empty. Something I am missing ?

**Comment by juliusv** [comment]
@jeunii Please ask usage questions on the users mailing list or the IRC channel: https://prometheus.io/community/
