### ISSUE TITLE
arm builds ?

### ISSUE THREAD

**Issue by joeblew99** [prometheus/prometheus#1464]
Some of my infrastructure is moving to arm and so i was wondering if its possible to build for arm ?

armv7 and arm64

**Comment by brian-brazil** [comment]
There's 3rd party nightlies at http://www.robustperception.io/prometheus-nightly-binaries/

**Comment by joeblew99** [comment]
Thanks Brian. Looks good

**Comment by brian-brazil** [comment]
Those aren't official builds, so we should leave this hanging around as a feature request to get arm builds as part of our releases. @sdurrheimer

**Comment by joeblew99** [comment]
Ah. Got it.

**Comment by sdurrheimer** [comment]
We are working on a new release process that's involves cross-building project for different platforms. `linux/arm ` and `linux/arm64` will be part of those platforms.

We can't give a ETA yet.
@see https://github.com/prometheus/alertmanager/pull/223

**Comment by joeblew99** [comment]
Awesome. Thanks

**Comment by grobie** [comment]
Arm builds are available starting with [018.0rc1](https://github.com/prometheus/prometheus/releases/tag/0.18.0rc1) thanks to @sdurrheimer and https://github.com/prometheus/promu.

**Comment by joeblew99** [comment]
Thankyou all .

**Comment by ryanhartje** [comment]
Did this slip through the cracks or something? Prometheus still doesn't have an official arm64 image on dockerhub 3 years later.

**Comment by simonpasquier** [comment]
@ryanhartje this issue was only about binary builds, not container images which is in progress (see https://github.com/prometheus/prometheus/pull/5031).

**Comment by ryanhartje** [comment]
Thanks @simonpasquier and Prometheus team!
