### ISSUE TITLE
CVE of  prometheus/prometheus:v2.54.0

### ISSUE THREAD

**Issue by weiZhenkun** [prometheus/prometheus#14659]
### What did you do?

![image](https://github.com/user-attachments/assets/1f0309a2-b21a-4841-b6ae-031d53c853cc)

### What did you expect to see?

CVEs should be fixed

### What did you see instead? Under which circumstances?

CVEs should be fixed.

**Comment by beorn7** [comment]
Please report security issues privately as described in https://prometheus.io/docs/operating/security/ . While doing so, please pay attention to the [section about automated security scanners](https://prometheus.io/docs/operating/security/#automated-security-scanners). Thank you very much.
