### ISSUE TITLE
Unable to set route on prometheus container

### ISSUE THREAD

**Issue by zmbcgn** [prometheus/prometheus#14678]
### What did you do?

I try to add a route with "ip route add" command, but i'm getting this error:

prometheus $ ip route add
ip: RTNETLINK answers: Operation not permitted
/prometheus $ 

I run prometheus within a compose file along with the prom/snmp-exporter . both have the cap "net_admin" set, but where as I can set a route in the snmp-exporter container, within the prometheus container i cannot.

I guess there is something wrong/missing inside the prometheus image.

### What did you expect to see?

the route is added.

### What did you see instead? Under which circumstances?

prometheus $ ip route add
ip: RTNETLINK answers: Operation not permitted
/prometheus $ 

### System information

Linux b482f2fd9a7f 5.15.0-117-generic #127-Ubuntu SMP Fri Jul 5 20:13:28 UTC 2024 x86_64 GNU/Linux

### Prometheus version

```text
prometheus, version 2.53.2 (branch: HEAD, revision: 6e971a7dc905696d4bc4ffa150bf282fcfac5fa9)
  build user:       root@363b0aa99939
  build date:       20240809-14:55:04
  go version:       go1.22.6
  platform:         linux/amd64
  tags:             netgo,builtinassets,stringlabels
```

### Prometheus configuration file

```yaml
ommited - not neccessary.
```

**Comment by tjhop** [comment]
Prometheus runs as the `nobody` user in the [container](https://github.com/prometheus/prometheus/blob/main/Dockerfile#L21), which is why the command fails. The snmp exporter doesn't set a user and so runs as root by default. 

For security reasons, it's generally recommended to not run things as root inside containers. I don't imagine this is a stance the project is going to change

**Comment by zmbcgn** [comment]
OK. I understand. I need to route traffic to a wireguard container, to reach my NAS at home. I don't want to expose my NAS to the internet, that's why I use wireguard to connect to it. I also tried the network_type: container:wireguard trick, but then Prometheus will lose its connectivity to the snmp_exporter. So, currently I am limited to monitor my NAS with SNMP. Maybe my setup can be optimized, but that's what I have right now.

**Comment by zmbcgn** [comment]
Found myself a workaround with the prometheus proxy found under https://github.com/pambrose/prometheus-proxy . So we can close this issue
