### ISSUE TITLE
text format parsing error in line 3: expected integer as timestamp, got ""

### ISSUE THREAD

**Issue by ringtail** [prometheus/prometheus#1469]
here is my metrics
```
# HELP suminfo_oss_sum The total number of failed messages sent. 
# TYPE suminfo_oss_sum counter
suminfo_oss_sum 4424 
# HELP suminfo_osssize_sum The total number of failed messages sent. 
# TYPE suminfo_osssize_sum counter
suminfo_osssize_sum 0 1
```

**Comment by grobie** [comment]
What are you trying to do in line 6? You're exporting two values there, 0 and 1. Assuming you're not trying to set a manual timestamp, you should remove one of the two.

You can find the documentation about the text format here: http://prometheus.io/docs/instrumenting/exposition_formats/#text-format-details

**Comment by ringtail** [comment]
sorry but I can't still pass 
```
# HELP suminfo_oss_sum The total number of failed messages sent. 
# TYPE suminfo_oss_sum counter
suminfo_oss_sum 4424 
# HELP suminfo_osssize_sum The total number of failed messages sent. 
# TYPE suminfo_osssize_sum counter
suminfo_osssize_sum 0 
```

**Comment by beorn7** [comment]
@ringtail You have trailing whitespace in line 3.

I guess the parser should tolerate that. I'll open an issue in the appropriate package.
For now, just remove the trailing whitespace.

**Comment by beorn7** [comment]
https://github.com/prometheus/common/issues/33 for the separate issue.

@ringtail Please re-open if removing the trailing whitespace doesn't fix your issue.

**Comment by ringtail** [comment]
Thank you !!!
