### ISSUE TITLE
Investigate supporting arrays as label values

### ISSUE THREAD

**Issue by juliusv** [prometheus/prometheus#147]
This would be useful for things like e.g. the list of roles attached to a host and then querying only by a single role. Not sure if supporting this is worth the time and complexity though.

**Comment by brian-brazil** [comment]
This would be better done as multiple timeseries each with the label value you wanted, and fits the data model generally.

**Comment by matthiasr** [comment]
I disagree. Consider a service participating in A/B testing with several experiments going on at the same time. Some requests will end up participating in more than one experiment; when reporting these separately they would be over-reported for the total request rate.

**Comment by brian-brazil** [comment]
In a case like that where timeseries aren't independent, you'd have to have a separate metric for total request rate.

**Comment by juliusv** [comment]
This is simply not realistic to do in Prometheus anytime soon - closing.
