### ISSUE TITLE
How to use anchored regular expressions?

### ISSUE THREAD

**Issue by grobie** [prometheus/prometheus#1470]
@guanglinlv asked about the new anchored expressions in #1459:

> node_cpu{instance=~"xx|yy",mode="user"} help me getting the point both xx and yy instance. it's very useful to make a comparing among different instance. how can i get that if regular expression is anchored ?

**Comment by grobie** [comment]
In order to use anchored regular expressions, it's important to always match the full value from start to beginning.

```
# `xx` or `yy` are at the beginning of the instance label
node_cpu{instance=~"(xx|yy).*", mode="user"}

# `xx` or `yy` are at the end of a the instance label
node_cpu{instance=~".*(xx|yy)", mode="user"}

# `xx` or `yy` are somewhere in the instance label
node_cpu{instance=~".*(xx|yy).*", mode="user"}
```

It is recommended to be as specific as possible in order to not match other values.

**Comment by guanglinlv** [comment]
@grobie , aha, got it, regular expression must be match the full value. even if i want to match with substring. i will try it again. thanks a lot.

**Comment by beorn7** [comment]
Closing as the question is answered (thanks @grobie ). @guanglinlv please re-open if any issue remains.
