### ISSUE TITLE
Commit d15adfc917b3d417980c6259c0c8f072f1f82082 increases system load from ~9 to ~16

### ISSUE THREAD

**Issue by RichiH** [prometheus/prometheus#1473]
As per https://github.com/prometheus/prometheus/issues/1472

d15adfc917b3d417980c6259c0c8f072f1f82082 is the next one

````
git bisect start
# good: [5b30bdb610a8fe7019edbf23bfc10412309ca5b8] Change TargetProvider interface.
git bisect good 5b30bdb610a8fe7019edbf23bfc10412309ca5b8
# bad: [fbe251c2df399b89bf87a11352ab26aff676d8d0] Fix scrape interval length calculation
git bisect bad fbe251c2df399b89bf87a11352ab26aff676d8d0
# skip: [05de8b7f8d43bc37b7198cad16e9b4760ba255ff] Extract target scraping into scrape loop.
git bisect skip 05de8b7f8d43bc37b7198cad16e9b4760ba255ff
# bad: [da99366f85bb9acc758ecc4ff0eeec43ac0310c7] Consolidate Target.Update into constructor.
git bisect bad da99366f85bb9acc758ecc4ff0eeec43ac0310c7
# bad: [d15adfc917b3d417980c6259c0c8f072f1f82082] Preserve target state across reloads.
git bisect bad d15adfc917b3d417980c6259c0c8f072f1f82082
# first bad commit: [d15adfc917b3d417980c6259c0c8f072f1f82082] Preserve target state across reloads.
````

**Comment by fabxc** [comment]
Could you elaborate?
Next on for what? If the issue started in the commit you bisected in #1472, it will likely be there for all subsequent ones.

**Comment by RichiH** [comment]
The last one went from load ~3 to ~9. This one went from ~9 to ~16.

**Comment by fabxc** [comment]
I understand. Generally it's super helpful to get the profiling SVG that nicely shows where time is spent.

Basically, run this:

```
go tool pprof --svg http://<prometheus>/debug/pprof/profile > prof.svg
```

**Comment by RichiH** [comment]
Good to know. Do you need that for those two issues?

**Comment by fabxc** [comment]
Got one for the first one, which is hopefully fixed via #1474.
Would be great for this one.

**Comment by RichiH** [comment]
Minor nitpick: GitHub does not allow SVG, only PNG, GIF, and JPG.

As they all look different, I made ten and had a `sleep 10` in between.
![prof_1](https://cloud.githubusercontent.com/assets/754723/13632129/7ddd2790-e5e8-11e5-8c50-c1a4508cbb48.png)
![prof_2](https://cloud.githubusercontent.com/assets/754723/13632124/7ddace1e-e5e8-11e5-9887-75be4359f4d5.png)
![prof_3](https://cloud.githubusercontent.com/assets/754723/13632127/7ddc0a5e-e5e8-11e5-9bd3-9dd90cdee70c.png)
![prof_4](https://cloud.githubusercontent.com/assets/754723/13632125/7ddb1e64-e5e8-11e5-9d8e-3732a8ab4097.png)
![prof_5](https://cloud.githubusercontent.com/assets/754723/13632126/7ddb9db2-e5e8-11e5-8f10-637d17c82ecc.png)
![prof_6](https://cloud.githubusercontent.com/assets/754723/13632128/7ddcc340-e5e8-11e5-950c-653937d7b1a2.png)
![prof_7](https://cloud.githubusercontent.com/assets/754723/13632131/7ded4d82-e5e8-11e5-8c23-7cf7a2d82d66.png)
![prof_8](https://cloud.githubusercontent.com/assets/754723/13632132/7deda750-e5e8-11e5-84ea-4f735380ed0f.png)
![prof_9](https://cloud.githubusercontent.com/assets/754723/13632130/7ded415c-e5e8-11e5-96ac-20b095fcb3e6.png)
![prof_10](https://cloud.githubusercontent.com/assets/754723/13632133/7dee9908-e5e8-11e5-8c24-37dfe207ec8d.png)

**Comment by RichiH** [comment]
System load with different builds: https://snapshot.raintank.io/dashboard/snapshot/fN9YwxGe8X9lxmQOwiK42pi6D6XQIo7L

**Comment by RichiH** [comment]
Longer term data, with added ingestion rates: https://snapshot.raintank.io/dashboard/snapshot/3szO1U2vYxxDrYlwq26V1Dq844xw4J6L

**Comment by brian-brazil** [comment]
Is this resolved?
