### ISSUE TITLE
Promote Agent mode as stable

### ISSUE THREAD

**Issue by ArthurSens** [prometheus/prometheus#14744]
### Proposal

I recently realized that to run Prometheus in agent mode we still need to toogle the feature-flag `agent`. The feature is out for a few years already and is widely adopted.

It might be too close to PromCon, and therefore to 3.0 release date, but should we discuss removing the feature flag and replacing it with other configuration options?

**Comment by jan--f** [comment]
I'm adding it to Prometheus 3 for now. Iiuc this would be a breaking change and getting it into Prometheus 3 would be ideal.

**Comment by ArthurSens** [comment]
> Maybe this could be bundled up with the idea of one binary for both prometheus and promtool. The "mode" of the binary could be selected with a command line flag (e.g. `--server`, `--tool`, `--agent`), but the default mode would depend on the name of the binary (or the linkname), e.g. `prometheus`, `promtool`, `promagent`.

I kept this in mind when implementing #14747, my idea over there was that in the future we could have `--runtime.mode=tool`. That's why I created an Enum instead of a boolean

**Comment by beorn7** [comment]
Yeah, I would generally agree. But `prometheus --tool` is just much shorter to type than `prometheus --runtime.mode=tool`.

Or in other words: This is a flag that people might actually type manually quite regularly, which might (or might not) justify this kind of top-level flag.

**Comment by ArthurSens** [comment]
Not sure why this wasn't closed by #14747 🤔, closing now
