### ISSUE TITLE
Prometheus agent 2.54.1, delayed metrics

### ISSUE THREAD

**Issue by mmosbaek** [prometheus/prometheus#14761]
### What did you do?

Hi,

We have Prometheus running in agent mode as part of our Thanos setup. The agents ship metrics to Thanos receiver (v0.36.1). 

We tried to upgrade Prometheus from 2.53.0 to 2.54.1.

After the upgrade, when querying metrics in the Thanos query (v0.36.1), the metrics seem to be delayed, and it keeps drifting over time. Before the upgrade the metrics where available almost instantly. 

I tried disabling the remote-write v2 feature, but it didn't help.

I don't see any hints in either Prometheus or Thanos logs.

I can't really find any hints on the issue, so let me know if you need anything else. 

Thanks in advance

### What did you expect to see?

I expected the metrics to be available as quickly as before.

### What did you see instead? Under which circumstances?

Metrics seems to be delayed and it gets worse over time.

### System information

Kuberntes v1.28.12 - Flatcar 3815.2.5

### Prometheus version

```text
Prometheus v. 2.54.1 running in agent-mode
```

**Comment by machine424** [comment]
Thanks for reporting this.

It seems https://github.com/prometheus/prometheus/issues/13471 hit again, which is timely as we wanted to investigate it further.

I'm suspecting the revert in https://github.com/prometheus/prometheus/releases/tag/v2.53.1 (that is shipped in `v2.54` as well), could you try `v.2.53.1`?

Could you elaborate on what you mean by `delayed` and `keeps drifting`? Could you quantify that? Could you share some relevant metrics from the thanos receive, perhaps https://github.com/thanos-io/thanos/blob/3270568f6b23fb81a58695d64fbc5c5716dcc449/pkg/receive/handler.go#L192-L208?

Could you check if the issue persists after disabling the agent mode? If it does, there will be some relevant metrics we can retrieve. In the meantime, the output of the following command would tell us a little bit about the wal:

```
for i in {1..32}
do
   echo $(date); ls -1qU data-agent/wal/ | wc -l; du -sh data-agent/wal/; sleep 5
done
```
(adapt `data-agent/wal` to point to the correct wal dir)

**Comment by patrickdung** [comment]
I had setup kube-thanos. It uses prometheus.

The default alert manager has rule and it also detected delayed metrics or metrics with timestamp problem recently. Seems to related to Promethues 2.54.1.

**Comment by mmosbaek** [comment]
Sorry for the late reply. 

I tried with version 2.53.1 as well, and I see the same pattern. 

What I mean by `drifting` and `delayed` metrics is that the metrics seems to be shipped to Thanos, but it seems to be delayed. And it seems to be more delayed over time. See below screenshots.

V2.53.0. The metrics are available almost immediately, as expected:   
![2531](https://github.com/user-attachments/assets/2ec46bf3-0908-4c5f-add4-c706d26590d4)

Here v2.54.1 have been deployed for about 35 mins and the drift is now around 7-8 min. This gap slowly increases over time. 
![2541](https://github.com/user-attachments/assets/1201c84a-0228-4e80-bf37-8353f3848cfd)

I tried with another non-agent prometheus v2.54.1 as well, running in same cluster, scraping the same metrics, but with local storage not shipping to Thanos, and here **I do not** see the same issue.

**Comment by machine424** [comment]
(Wrote a rely but never clicked `Comment`)

Thanks for the details.

> I tried with another non-agent prometheus v2.54.1 as well, running in same cluster, scraping the same metrics, but with local storage not shipping to Thanos, and here I do not see the same issue.

IIUUC, you made a test with Prometheus in server/non-agent mode without making it ship metrics through remote-write? I'd be great to have remote-write enabled there as well to see if the metrics are "delayed" as well.

If you could share`--log.level=debug` logs for some minutes from that Prometheus agent with the issue, it could be helpful.

Also, if we could get the output of the script I shared in https://github.com/prometheus/prometheus/issues/14761#issuecomment-2324071811 it'd be great.
