### ISSUE TITLE
Print `uname -a` as part of startup

### ISSUE THREAD

**Issue by RichiH** [prometheus/prometheus#1480]
This would better fit into prometheus/common, but it seems every part of prometheus does this on its own.

To prevent questions about OS, architecture, etc, it would be nice if the output of `uname -a`, or the relevant subset, could just be printed along with build info during startup.

**Comment by CrazyByDefault** [comment]
Looks like this could be addded to either [prometheus/cmd/prometheus/main.go](https://github.com/prometheus/prometheus/blob/master/cmd/prometheus/main.go) or to [common/version/info.go](https://github.com/prometheus/common/blob/master/version/info.go).

But the question of _what_ to put is kinda tricky. Not all OSes are compatible with `uname -a` (especially Windows).

Also, I'm new to Golang (not to mention Open Source contrib in general), and I'd like to contribute to Prometheus.
