### ISSUE TITLE
OpenMetrics using gigabytes more memory

### ISSUE THREAD

**Issue by bboreham** [prometheus/prometheus#14808]
### What did you do?

Ran Prometheus at commit a77f5007f9debcc1fc5b7133ac422e2b164a8c99

### What did you expect to see?

Heap memory around 15-20GB

### What did you see instead? Under which circumstances?

OOM at 32GB limit; also CPU usage went way up.

<img width="1121" alt="image" src="https://github.com/user-attachments/assets/5a4a8ffc-88ba-4cc2-855a-3554242f8dd1">

<img width="838" alt="image" src="https://github.com/user-attachments/assets/3b74a69e-2e66-4e5f-a035-3fcd6d9baaa0">

[prom-oom-heap.pprof.gz](https://github.com/user-attachments/files/16837367/prom-oom-heap.pprof.gz)

Going back to commit b7a58dcf3d2347ade21ce946007efb0bcb5e22a2 resolved the problem (before #14356)

### System information

Linux 6.1.85+ #1 SMP PREEMPT_DYNAMIC Thu Jun 27 21:05:47 UTC 2024 x86_64 

### Prometheus version

```text
prometheus, version 2.54.1 (branch: main, revision: a77f5007f9debcc1fc5b7133ac422e2b164a8c99)
  build user:       bryan@study-pc
  build date:       20240902-11:24:22
  go version:       go1.22.5
  platform:         linux/amd64
  tags:             netgo,builtinassets,stringlabels
```

### Prometheus configuration file

Command-line args:
```
      - args:
        - --config.file=/etc/prometheus/$(POD_NAME).yml
        - --web.listen-address=:9090
        - --web.external-url=https://admin-dev-us-central-0.grafana-dev.net/bryan-prometheus/
        - --web.enable-admin-api
        - --web.enable-lifecycle
        - --web.route-prefix=/bryan-prometheus/
        - --storage.tsdb.path=/prometheus/data
        - --storage.tsdb.wal-compression
        - --storage.tsdb.retention.size=40GB
        - --enable-feature=promql-at-modifier,exemplar-storage
```

### Logs

```text
ts=2024-09-02T12:10:47.610Z caller=main.go:252 level=warn msg="This option for --enable-feature is now permanently enabled and therefore a no-op." option=promql-at-modifier
ts=2024-09-02T12:10:47.610Z caller=main.go:193 level=info msg="Experimental in-memory exemplar storage enabled"
ts=2024-09-02T12:10:47.614Z caller=main.go:671 level=info msg="Starting Prometheus Server" mode=server version="(version=2.54.1, branch=main, revision=a77f5007f9debcc1fc5b7133ac422e2b164a8c99)"
ts=2024-09-02T12:10:47.614Z caller=main.go:676 level=info build_context="(go=go1.22.5, platform=linux/amd64, user=bryan@study-pc, date=20240902-11:24:22, tags=netgo,builtinassets,stringlabels)"
ts=2024-09-02T12:10:47.614Z caller=main.go:677 level=info host_details="(Linux 6.1.85+ #1 SMP PREEMPT_DYNAMIC Thu Jun 27 21:05:47 UTC 2024 x86_64 bryan-prometheus-0 (none))"
ts=2024-09-02T12:10:47.614Z caller=main.go:678 level=info fd_limits="(soft=1048576, hard=1048576)"
ts=2024-09-02T12:10:47.614Z caller=main.go:679 level=info vm_limits="(soft=unlimited, hard=unlimited)"
```
```

**Comment by bwplotka** [comment]
ack, we are on it cc @Maniktherana

**Comment by ArthurSens** [comment]
Interesting! We're calling CreatedTimestamp() as the first part of the conditional

https://github.com/prometheus/prometheus/blob/7dd74ca6b7b34fe5724f3796fd64660ce6104272/scrape/scrape.go#L1658

We might want to switch this if to check `sl.enableCTZeroIngestion` first

**Comment by bwplotka** [comment]
Fixed on `main`, but the same performance regression exists behind [the `created-timestamp-zero-ingestion` flag](https://prometheus.io/docs/prometheus/latest/feature_flags/#created-timestamps-zero-injection), which we were aware of. Added. https://github.com/prometheus/prometheus/issues/14823 to track the improvements, we (@Maniktherana @ArthurSens) are on it!

Thanks!
