### ISSUE TITLE
Flaky `TestDelayedCompactionDoesNotBlockUnrelatedOps` test

### ISSUE THREAD

**Issue by juliusv** [prometheus/prometheus#14857]
In the CI step for `Run make GOOPTS=--tags=stringlabels GO_ONLY=1 SKIP_GOLANGCI_LINT=1`, I just got this test failure where it runs out of disk space:

```
--- FAIL: TestDelayedCompactionDoesNotBlockUnrelatedOps (0.00s)
    --- FAIL: TestDelayedCompactionDoesNotBlockUnrelatedOps/Head_is_compactable (0.95s)
        block_test.go:597: 
            	Error Trace:	/__w/prometheus/prometheus/tsdb/block_test.go:597
            	            				/__w/prometheus/prometheus/tsdb/compact_test.go:2118
            	Error:      	Received unexpected error:
            	            	compactor write: preallocate: no space left on device
            	Test:       	TestDelayedCompactionDoesNotBlockUnrelatedOps/Head_is_compactable
```

**Comment by juliusv** [comment]
@machine424

**Comment by machine424** [comment]
Yes, I haven't seen any of those fail on `main` lately, maybe it's related to changes on your branch.

**Comment by juliusv** [comment]
I think in the end, it was not really related to my branch, but just could've happened with any other branch as well that somehow introduced even just a little more storage or memory usage, pushing the race detector tests over the edge where they fail. But it seems that @SuperQ has fixed that now by properly setting env vars in the CI pipeline to tell the Go runtime to limit its memory usage, and now things are stable so far. So will close this.
