### ISSUE TITLE
how to handle aggregated sums from federated prometheus

### ISSUE THREAD

**Issue by filippog** [prometheus/prometheus#1490]
hi,
I'm testing prometheus federation and aggregation, namely I have a "global" prometheus at https://prometheus.wmflabs.org pulling all metrics matching '^project:' from several per-project prometheus servers, e.g. https://graphite-prometheus.wmflabs.org/status. In this context a "project" is a simply collection of VMs, following the `job:` example in the federation documentation. Currently `project:` metrics are generated via rules on the federated servers e.g. `project:node_network_receive_bytes{} = sum(node_network_receive_bytes{device!="lo"}) BY (device)` and the idea being to pull only aggregated metrics from federated servers.

Normally this works but with some caveats e.g. `rate(project:node_network_receive_bytes[5m])` on the global prometheus will artificially jump when a new target is added to the federated servers since that's now rate of sums instead of sum of rates. [Jump on the global server](https://prometheus.wmflabs.org/graph#%5B%7B%22range_input%22%3A%2230m%22%2C%22end_input%22%3A%222016-03-15%2015%3A00%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3A%22%22%2C%22expr%22%3A%22rate(project%3Anode_network_transmit_bytes%5B5m%5D)%22%2C%22tab%22%3A0%7D%5D) at the same time a [new target came up](https://prometheus.wmflabs.org/graph#%5B%7B%22range_input%22%3A%2230m%22%2C%22end_input%22%3A%222016-03-15%2015%3A00%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3A%22%22%2C%22expr%22%3A%22project%3Aup%22%2C%22tab%22%3A0%7D%5D)

What's the recommendation in this case? Having the 5m rate as a recording rule would achieve that I think? thanks!

**Comment by brian-brazil** [comment]
You should be aggregating up on the project prometheus servers:

```
project_device:node_network_receive_bytes:rate5m = sum by (project, device) rate(node_network_receive_bytes{job="node"}[5m]))
```

Never take the rate of a sum, as it causes the problem you've encountered.

**Comment by filippog** [comment]
thanks @brian-brazil ! btw I'm happy to turn this issue into a documentation improvement, e.g. linking "best practices -> recording rules" from "federation", I'm fine to close it too
