### ISSUE TITLE
SIGHUP causes exit during startup

### ISSUE THREAD

**Issue by nosnilmot** [prometheus/prometheus#14917]
### What did you do?

Sending HUP signal to prometheus soon after (re)starting causes prometheus to exit instead of continuing to start. Suspect signal handler is not registered early enough to handle signals received during startup.

### What did you expect to see?

prometheus should complete startup and ignore SIGHUP

### What did you see instead? Under which circumstances?

prometheus exits if HUP sent early enough during startup

### System information

Darwin 23.6.0 arm64 (also seen on Linux 6.2.0-1018-aws x86_64)

### Prometheus version

```text
prometheus, version 2.54.1 (branch: non-git, revision: non-git)
  build user:       reproducible@reproducible
  build date:       20240827-10:44:00
  go version:       go1.23.0
  platform:         darwin/arm64
  tags:             netgo,builtinassets,stringlabels


prometheus, version 2.54.1 (branch: HEAD, revision: e6cfa720fbe6280153fab13090a483dbd40bece3)
  build user:       root@812ffd741951
  build date:       20240827-10:56:41
  go version:       go1.22.6
  platform:         linux/amd64
  tags:             netgo,builtinassets,stringlabels
```

### Prometheus configuration file

```yaml
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
    - targets: ["localhost:9090"]
```

### Logs

```text
If HUP sent ~10ms after launch, prometheus exits (bad):

$ prometheus & pid=$! && sleep 0.01 && kill -HUP $pid && fg
[1] 39311
prometheus
Hangup: 1


If HUP sent ~50ms after launch, promethues continues (and reloads config) (good):

$ prometheus & pid=$! && sleep 0.05 && kill -HUP $pid && fg
[1] 39344
ts=2024-09-17T06:55:37.385Z caller=main.go:601 level=info msg="No time or size retention was set so using the default time retention" duration=15d
ts=2024-09-17T06:55:37.385Z caller=main.go:645 level=info msg="Starting Prometheus Server" mode=server version="(version=2.54.1, branch=non-git, revision=non-git)"
ts=2024-09-17T06:55:37.385Z caller=main.go:650 level=info build_context="(go=go1.23.0, platform=darwin/arm64, user=reproducible@reproducible, date=20240827-10:44:00, tags=netgo,builtinassets,stringlabels)"
ts=2024-09-17T06:55:37.385Z caller=main.go:651 level=info host_details=(darwin)
ts=2024-09-17T06:55:37.385Z caller=main.go:652 level=info fd_limits="(soft=245760, hard=unlimited)"
ts=2024-09-17T06:55:37.385Z caller=main.go:653 level=info vm_limits="(soft=unlimited, hard=unlimited)"
ts=2024-09-17T06:55:37.387Z caller=web.go:571 level=info component=web msg="Start listening for connections" address=0.0.0.0:9090
ts=2024-09-17T06:55:37.388Z caller=main.go:1160 level=info msg="Starting TSDB ..."
ts=2024-09-17T06:55:37.389Z caller=tls_config.go:313 level=info component=web msg="Listening on" address=[::]:9090
ts=2024-09-17T06:55:37.389Z caller=tls_config.go:316 level=info component=web msg="TLS is disabled." http2=false address=[::]:9090
ts=2024-09-17T06:55:37.391Z caller=head.go:626 level=info component=tsdb msg="Replaying on-disk memory mappable chunks if any"
ts=2024-09-17T06:55:37.391Z caller=head.go:713 level=info component=tsdb msg="On-disk memory mappable chunks replay completed" duration=3.5µs
ts=2024-09-17T06:55:37.391Z caller=head.go:721 level=info component=tsdb msg="Replaying WAL, this may take a while"
ts=2024-09-17T06:55:37.391Z caller=head.go:793 level=info component=tsdb msg="WAL segment loaded" segment=0 maxSegment=5
ts=2024-09-17T06:55:37.392Z caller=head.go:793 level=info component=tsdb msg="WAL segment loaded" segment=1 maxSegment=5
ts=2024-09-17T06:55:37.393Z caller=head.go:793 level=info component=tsdb msg="WAL segment loaded" segment=2 maxSegment=5
ts=2024-09-17T06:55:37.393Z caller=head.go:793 level=info component=tsdb msg="WAL segment loaded" segment=3 maxSegment=5
ts=2024-09-17T06:55:37.393Z caller=head.go:793 level=info component=tsdb msg="WAL segment loaded" segment=4 maxSegment=5
ts=2024-09-17T06:55:37.394Z caller=head.go:793 level=info component=tsdb msg="WAL segment loaded" segment=5 maxSegment=5
ts=2024-09-17T06:55:37.394Z caller=head.go:830 level=info component=tsdb msg="WAL replay completed" checkpoint_replay_duration=47.458µs wal_replay_duration=2.88525ms wbl_replay_duration=83ns chunk_snapshot_load_duration=0s mmap_chunk_replay_duration=3.5µs total_replay_duration=2.95075ms
ts=2024-09-17T06:55:37.395Z caller=main.go:1181 level=info fs_type=1a
ts=2024-09-17T06:55:37.395Z caller=main.go:1184 level=info msg="TSDB started"
ts=2024-09-17T06:55:37.395Z caller=main.go:1367 level=info msg="Loading configuration file" filename=prometheus.yml
prometheus
ts=2024-09-17T06:55:37.671Z caller=main.go:1404 level=info msg="updated GOGC" old=100 new=75
ts=2024-09-17T06:55:37.671Z caller=main.go:1415 level=info msg="Completed loading of configuration file" filename=prometheus.yml totalDuration=276.475166ms db_storage=750ns remote_storage=917ns web_handler=291ns query_engine=541ns scrape=276.090833ms scrape_sd=89.542µs notify=2.708µs notify_sd=2.208µs rules=3.542µs tracing=45.875µs
ts=2024-09-17T06:55:37.671Z caller=main.go:1145 level=info msg="Server is ready to receive web requests."
ts=2024-09-17T06:55:37.671Z caller=main.go:1367 level=info msg="Loading configuration file" filename=prometheus.yml
ts=2024-09-17T06:55:37.671Z caller=manager.go:164 level=info component="rule manager" msg="Starting rule manager..."
ts=2024-09-17T06:55:37.937Z caller=main.go:1415 level=info msg="Completed loading of configuration file" filename=prometheus.yml totalDuration=265.414416ms db_storage=2.5µs remote_storage=2.708µs web_handler=500ns query_engine=2.167µs scrape=264.815042ms scrape_sd=90.917µs notify=3.833µs notify_sd=2.75µs rules=4.25µs tracing=20.375µs
```

**Comment by juliusv** [comment]
Yeah, this is where the handler is defined: https://github.com/prometheus/prometheus/blob/b8d1336d42f1f560b02e45ae1d8979a2e4b3b83f/cmd/prometheus/main.go#L1068-L1145 - and then it's started as part of https://github.com/prometheus/prometheus/blob/b8d1336d42f1f560b02e45ae1d8979a2e4b3b83f/cmd/prometheus/main.go#L1322.

We do a bunch of config and flag setup before that, but all of that should only take a couple of milliseconds in the normal case. However, as you report, it's also only ~50ms in your case, which still sounds realistic. I guess we could set up the signal handling even earlier, although at some point you may even run into issues with the Go runtime starting up before that or something like that.

**Comment by juliusv** [comment]
Do you want to try if building Prometheus from https://github.com/prometheus/prometheus/tree/catch-sighup-early (commit https://github.com/prometheus/prometheus/commit/6b01b7a3f0bfeb2a061e9ccc5c8e01405d3347f2) improves things for you? I've basically just moved the catching of the signal to the beginning of `main`, even though we still only do the actual handling of the caught signal later on.

**Comment by juliusv** [comment]
Turned it into a PR: https://github.com/prometheus/prometheus/pull/14924

**Comment by nosnilmot** [comment]
Thanks for trying, this improves things slightly, but only by ~10ms, so SIGHUP received within the first ~40ms still results in exit.

> you may even run into issues with the Go runtime starting up before that or something like that.

I think this is exactly the problem - I've since learned that Go runtime by explicitly installs a SIGHUP handler that causes the program to exit 😮  https://pkg.go.dev/os/signal#hdr-Default_behavior_of_signals_in_Go_programs

It would need prometheus to be started by a native program that ignores SIGHUP to address that ("_If the Go program is started with either SIGHUP or SIGINT ignored (signal handler set to SIG_IGN), they will remain ignored._") - `nohup` looks like it would work here:
>  _If the program was started with SIGHUP or SIGINT ignored, and [Notify](https://pkg.go.dev/os/signal#Notify) is called for either signal, a signal handler will be installed for that signal and it will no longer be ignored._

that has the disadvantage that `journalctl` log entries then show as coming from `nohup` instead of `prometheus` (also I don't really want the stdout redirection of `nohup`, but that won't apply in normal use when stdout is not a terminal)

**Comment by juliusv** [comment]
Ah drat, then I guess there's nothing more we can do and it's whatever other process startup overhead happens before `main()`.

What you could do: check if the Prometheus server is ready (see https://prometheus.io/docs/prometheus/latest/management_api/#readiness-check) or reachable at all over HTTP before sending and HUP signals.

**Comment by nosnilmot** [comment]
> What you could do:


yes, thanks, I also came up with a few other alternatives, which may be helpful to anyone else who comes across this:
1. Add small sleep to reload just in case it has just started: `sleep 1 && kill -HUP $pid`
2. Switch to REST API for reload `curl -fs -m 5 -X POST 127.0.0.1:9090/-/reload`
3. Check prometheus is accepting connections before reload `nc -z 127.0.0.1 9090 && kill -HUP $pid`
