### ISSUE TITLE
Docs for feature flags is broken

### ISSUE THREAD

**Issue by data-dude** [prometheus/prometheus#14952]
### What did you do?

Tried to read about feature flags and links are broken

https://prometheus.io/docs/prometheus/latest/command-line/prometheus/

https://prometheus.io/docs/prometheus/latest/feature_flags/

### What did you expect to see?

feature links docs

### What did you see instead? Under which circumstances?

404 error

**Comment by spencerwilson** [comment]
These links do not 404:

- https://prometheus.io/docs/prometheus/2.55/command-line/prometheus/
- https://prometheus.io/docs/prometheus/2.55/feature_flags/

I suspect this issue may be a consequence of https://github.com/prometheus/prometheus/issues/14955

**Comment by juliusv** [comment]
Yes, I bet that was because the docs were broken for a few days until they got fixed on the weekend, see https://github.com/prometheus/prometheus/issues/14955#issuecomment-2367422301

Thanks for reporting though!
