### ISSUE TITLE
Docs consider 1.x stable, 2.x prerelease

### ISSUE THREAD

**Issue by spencerwilson** [prometheus/prometheus#14955]
### What did you do?

1. Visit https://prometheus.io/docs/prometheus/latest/getting_started/
2. Look at the version selector on the left nav

### What did you expect to see?

(Tweaking the DOM, something like the following)

<img width="259" alt="image" src="https://github.com/user-attachments/assets/c9a0b144-8e0f-4994-b25b-40b9489b0492">

### What did you see instead? Under which circumstances?

<img width="287" alt="image" src="https://github.com/user-attachments/assets/d469cf65-2ee7-4a72-8ef8-7c1447663f47">

And when selecting 2.55:

<img width="877" alt="image" src="https://github.com/user-attachments/assets/84b703dc-64a2-434e-b515-d2940ff2a070">

I read in https://prometheus.io/blog/2024/09/11/prometheus-3-beta/ that 2.0 was released in 2017, so I take it 2.x is latest, 1.x is legacy, 3.x is prerelease.

### System information

n/a

### Prometheus version

```text
n/a
```

### Prometheus configuration file

```yaml
n/a
```

### Alertmanager version

```text
n/a
```

### Alertmanager configuration file

```yaml
n/a
```

### Logs

```text
n/a
```

**Comment by juliusv** [comment]
Thanks for reporting! This was also reported in https://github.com/prometheus/docs/issues/2514 and I fixed it on the weekend in https://github.com/prometheus/docs/pull/2516. Basically the website build process ran into a weird edge case where there were already both `release-3.0` and `release-2.55` branches, both without a tagged stable release on them (one is still a beta tag, the other still an RC), and it didn't deal with that correctly.
