### ISSUE TITLE
Website Documentation Error: Incorrect Flag Usage in Prometheus Configuration Command

### ISSUE THREAD

**Issue by yenslife** [prometheus/prometheus#14954]
### What did you do?

While following the tutorial on the Prometheus website, I encountered an issue with the command provided in the documentation. Specifically, I noticed that the flag `-config.file` should actually be `--config.file`. This discrepancy suggests that the website documentation is not synchronized with the GitHub source code. I have attached a screenshot for reference.

website link: https://prometheus.io/docs/prometheus/latest/getting_started/#starting-prometheus
![image](https://github.com/user-attachments/assets/2895141c-3c00-4c0a-8f12-928eade79b4b)

### What did you expect to see?

I expected the documentation to accurately reflect the correct command-line syntax for starting Prometheus, specifically using the long flag `--config.file`.

### What did you see instead? Under which circumstances?

Instead of seeing the correct flag usage, I found that the website incorrectly listed it as -config.file. This error could lead to confusion and potential issues for users trying to start Prometheus based on the provided instructions. The issue occurred while accessing the tutorial section of the Prometheus website.

**Comment by spencerwilson** [comment]
The docs at https://prometheus.io/docs/prometheus/2.55/configuration/configuration/ . I suspect this issue is a consequence of https://github.com/prometheus/prometheus/issues/14955

**Comment by juliusv** [comment]
Thanks for reporting! Yes, see my comment in https://github.com/prometheus/prometheus/issues/14955#issuecomment-2367422301, the website build has been fixed to show the proper latest docs again.
