### ISSUE TITLE
Rate function returns incorrect results

### ISSUE THREAD

**Issue by fpetkovski** [prometheus/prometheus#14961]
### What did you do?

We are trying to our prometheus dependency to 3.x-beta and a lot of our promql tests break. The breakage seems to be related to https://github.com/prometheus/prometheus/pull/13904 which changes the behavior of the lookback window and matrix selector. 

I am trying to understand the new behavior and I wonder if there is a bug in PromQL now where the `rate` result (and possibly other windowing functions) are incorrect. 

### What did you expect to see?

I created a new test case in [this](https://github.com/prometheus/prometheus/pull/14960) PR where the rate is calculated over 1m window window and 90s step. The series has a sample each 30s, which means that with the new logic the rate should always have 1 sample in its window. 

Instead, the rate seems to return a result for both the 90s and 180s step.

### What did you see instead? Under which circumstances?

I would expect to see no data returned for this query.

### Prometheus version

v0.300.0-beta.0.0.20240919161259-e480cf21eb1d

**Comment by juliusv** [comment]
> The breakage seems to be related to https://github.com/prometheus/prometheus/pull/13904 which changes the behavior of the lookback window and matrix selector.

CC-ing @beorn7 because he knows both topics (change of lookback window) and the `rate()` function subtleties best.

**Comment by beorn7** [comment]
Will have a look ASAP. Thanks for reporting.

**Comment by beorn7** [comment]
I think the implemented behavior is correct.

Copying the test here for commenting:

```
# rate with counter reset and step larger than window
load 30s
  http_requests_total{pod="nginx-1", series="1"} 1 2 3 4 5 6

eval range from 0 to 180s step 90s rate(http_requests_total[1m])
  {pod="nginx-1", series="1"}
```

So this creates a series with a sample every 30s.

The range evaluation will happen at 0s, 90s, and 180s:
- At 0s, there is indeed only one sample in the 1m window. 
- At 90s, the window contains 4@90s and 3@60s, but not 2@30s (which _would_ have been included with the old behavior). So it sees the increase of 1 over 30s, which is extrapolated to 2 over 1m, which is normalized to 0.03333/s.
- At 180s, the window contains 6@150s (but _not_ 5@120s, as it would have with the old behavior). So only one sample and no point.

Thus, the outcome of the test seems right to me:
```
                                error in eval rate(http_requests_total[1m]) (line 79): expected 0 float points and 0 histogram points for {pod="nginx-1", series="1"}, but got 1 float point [0.03333333333333333 @[90000]] and 0 histogram points []
```

**Comment by fpetkovski** [comment]
Got it, thanks for the explanation. I miscalculated that at step 180s we should have two points in the buffer as well, but there is no sample for that timestamp. 

We can close this one.
