### ISSUE TITLE
deamon doesn't start after crash - leveldb manifest corrupted

### ISSUE THREAD

**Issue by jojo05** [prometheus/prometheus#1496]
I am running 0.17.0 on Fedora rawhide. After a crash, the deamon fails to start (see message below).
What is the recommended procedure to recover from this ? 
Thanks

level=error msg="Error opening memory series storage: leveldb: manifest corrupted (field 'comparer'): missing [file=MANIFEST-000445]" source="main.go:139"

**Comment by beorn7** [comment]
Unless you know how to fix a corrupted leveldb, there is nothing you can do, unfortunately.

LevelDB corruptions upon crashes are rare but if they happen, they essentially mean you have to nuke your storage and start from scratch.

See #651 to track efforts of allowing hot backups.

**Comment by linuxtim** [comment]
> Unless you know how to fix a corrupted leveldb
