### ISSUE TITLE
Suggest: prometheus-config use json format instead of yaml

### ISSUE THREAD

**Issue by guozheng-shen** [prometheus/prometheus#14991]
### Proposal

when I want to modify the config, I got it. I don't know how to convert this string to yaml, yaml has the advantage of readability, but this string doesn't. If the data is json format, I can easily modify it 
`kubectl get configMap  prometheus-config -o yaml`
`apiVersion: v1`
`data:`
  `   prometheus.yml: "global:\n  scrape_interval: 30s\n  evaluation_interval: 30s\nscrape_configs:\n
    \ - job_name: kubelet\n    scheme: https\n    tls_config:\n      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt\n
    \   bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token\n    kubernetes_sd_configs:\n
    \     - role: node\n    relabel_configs:\n      - action: labelmap\n        regex:
    __meta_kubernetes_node_label_(.+)\n      - target_label: __address__\n        replacement:
    'kubernetes.default.svc:443'\n      - source_labels:\n          - __meta_kubernetes_node_name\n
    \       regex: (.+)\n        target_label: __metrics_path__\n        replacement:
    '/api/v1/nodes/${1}/proxy/metrics'\n  - job_name: apiserver\n    metrics_path:
    /metrics\n    kubernetes_sd_configs:\n      - role: endpoints\n    scheme: https\n
    \   tls_config:\n      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.cr ....
`

**Comment by gillg** [comment]
Yaml is a json subset by design. That's why you see offer documentations mixing [] (from json notation) or - (from yaml notation) to create a list of elements.
Saying that, that means you can paste a whole json inside a yaml file, and it will be valid (but a bit confusing for users) 😃 

Only limit, json says you can't have multiple "root" node in a file.
With yaml and the triple dash separator (---) you can put multiple documents in a single file (case of kubernetes manifests as an example)

**Comment by guozheng-shen** [comment]
> Yaml is a json subset by design. That's why you see offen documentations mixing [] (from json notation) or - (from yaml notation) to create a list of elements. Saying that, that means you can paste a whole json inside a yaml file, and it will be valid (but a bit confusing for users) 😃
> 
> Only limit, json says you can't have multiple "root" node in a file. With yaml and the triple dash separator (---) you can put multiple documents in a single file (case of kubernetes manifests as an example)

but when I want to update my config, the yaml strings leave me at a loss. It contains too many spaces and \n 😭
