### ISSUE TITLE
Eureka discovery

### ISSUE THREAD

**Issue by drax68** [prometheus/prometheus#1506]
Hi. Could you please add [Eureka](https://github.com/Netflix/eureka) to discovery backends?
It has quite [straightforward api](https://github.com/Netflix/eureka/wiki/Eureka-REST-operations) and existing [client in go](https://github.com/ArthurHlt/go-eureka-client)

**Comment by juliusv** [comment]
If that is a widely-enough used SD mechanism, then I can imagine it could get added to Prometheus itself. However, SD mechanisms are usually added (via PRs) and maintained by people who actually use a specific type of service discovery, since they are in the best position to test it and know the practical design and implementation considerations. So I guess, feel free to send a PR - and it would help if there was some interest in maintaining it, as well :)

**Comment by pparth** [comment]
+1

**Comment by fabMrc** [comment]
+1

**Comment by manuelpolacek** [comment]
+1

**Comment by hakamairi** [comment]
+1

**Comment by ankurbhakta** [comment]
+1

**Comment by jtlisi** [comment]
+1

**Comment by ipalbeniz** [comment]
+1

**Comment by fedy2** [comment]
+1

**Comment by olafgeibig** [comment]
+1

**Comment by chenapan** [comment]
+1

**Comment by itshanney** [comment]
+1

**Comment by joaovicente** [comment]
+1

**Comment by ankurbhakta** [comment]
+1

**Comment by fabxc** [comment]
Friendly reminder that commenting +1 is mostly noise for maintainers and alone does not incentivise us to work on any particular feature. As an open source project, we welcome productive discussion and contributions.
If you just want to express that you agree with the feature request, GitHub has reaction emojis, which do not flood our inboxes.

**Comment by zzp8164** [comment]
+1

**Comment by pojozhang** [comment]
+1

**Comment by yarix** [comment]
+1

**Comment by fabxc** [comment]
Locking this issue now.

**Comment by tine2k** [comment]
I have written an adapter that you can deploy with your Eureka instance. This adapter provides several HTTP endpoints that return information of the registered services and are **compatible with the Prometheus' Consul discovery client** (consul_sd_config). It is available as a Spring Boot starter on Github: https://github.com/twinformatics/eureka-consul-adapter

**Comment by davidkarlsen** [comment]
Very interesting - I looked at it yesterday - and it is just what I need (as I want to avoid the consul full-mesh stuff for agents). Does eureka have a label concept like consul? And are these mapped over?

**Comment by tine2k** [comment]
No, eureka does not support labels. However, there is something called node metdata that clients can send along with their registration. By overriding InstanceInfoMapper of the adapter you return this metadata as service tags, which you can use as labels in Prometheus.

**Comment by simonpasquier** [comment]
Closing the issue as unfortunately, we are currently not accepting new integrations. See https://github.com/prometheus/prometheus/issues/1506#issuecomment-374864183 for an alternative.

We can only provide the stability and performance we want to provide if we can properly maintain the codebase. This includes, amongst others, test integrations in an automated and scalable fashion. For this reason, we are suggesting people integrate with the help of our generic interfaces. We have an integrations page on which integrations using our generic interfaces are listed.

Even if existing integrations can not be tested in an automated fashion, we will not remove them for reasons of compatibility. This also means that any additions we take on, or any changes to existing integrations we make or accept, will mean maintaining and testing these until at least the next major version, realistically even beyond that.

Feel free to question this answer on our [developer mailing list](https://groups.google.com/forum/#!forum/prometheus-developers), but be aware it's unlikely that you will get a different answer.

**Comment by roidelapluie** [comment]
Being worked on in #3369

**Comment by roidelapluie** [comment]
Closed by  #3369
