### ISSUE TITLE
Please consider disabling fsnotify in certain architectures

### ISSUE THREAD

**Issue by TheTincho** [prometheus/prometheus#1507]
Hi,

As noted in bug fsnotify/fsnotify#130, fsnotify fails to work correctly (or at all) in arm64, ppc64 and ppc64el.

This was preventing prometheus to be accepted in Debian testing, so while this is solved upstream, I hacked together a [patch](http://anonscm.debian.org/cgit/pkg-go/packages/prometheus.git/tree/debian/patches/07-Disable_fsnotify.patch) to disable fsnotify and rely only on refresh intervals in those architectures. You might want to consider applying something similar, so prom keeps working.

**Comment by fabxc** [comment]
That seems sane :+1:

**Comment by TheTincho** [comment]
As a data point, the new Debian release with this patch applies compiles and passes tests in all arches: https://buildd.debian.org/status/package.php?p=prometheus

**Comment by brian-brazil** [comment]
Do you want to send on a PR with that patch?

**Comment by TheTincho** [comment]
Sure, will do.

I see the fsnotify people are moving to fix this issue, but it might take a while, as it might involve getting fixes into golang itself.

**Comment by TheTincho** [comment]
Done.
