### ISSUE TITLE
Prometheus not building on 386 with 1.5.3

### ISSUE THREAD

**Issue by brian-brazil** [prometheus/prometheus#1509]
Prometheus isn't building on 386 for any OS when using go 1.5.3 (other 32 bit archs are fine), for example: 

```
$ GOOS=linux GO15VENDEXPERIMENT=1 GOARCH=386 go build github.com/prometheus/prometheus/cmd/prometheus
# github.com/prometheus/prometheus/storage/local
run compiler with -v for register allocation sites
storage/local/varbit.go:660: internal compiler error: out of fixed register
```

This is from #1491. https://github.com/golang/go/issues/13277, https://github.com/golang/go/issues/11352 and https://github.com/golang/go/issues/12840 seem relevant.

**Comment by beorn7** [comment]
The same happens with go1.6.
