### ISSUE TITLE
Question about push of data

### ISSUE THREAD

**Issue by joeblew99** [prometheus/prometheus#1512]
I have some golang code running on ios and android.
As I understand it, there is a way for them to push to a Prometheus gateway thingy, which then allows promethius to pull from the gateway server.

Can anyone confirm this approach.

Once I get it working I can push the code to a git repo if you want for others to see how to do it :)

**Comment by brian-brazil** [comment]
That should be possible, but you may also be the first user trying to do pushes from mobile phones and I suspect that this is not sane unless you're doing something like getting stats from a mobile phone testing lab.

What exactly are you looking to push, and from how many devices?

**Comment by joeblew99** [comment]
1000 of mobiles. It's enterprise network behind a NAT etc. So push out from
mobiles to gateway is easiest too.

The data is a mixture of rollups counted up on the phone and 30 kHz data.
The 30 kHz sampling data is damn high number of time series style of data.

But as I said it's on a fat pipe so its just a matter of maybe using 10
gateway servers and assigning 20% of devices to each gateway server.

On prim, it's going to be fun to see if she keeps up.
I could do the same sharding trick. And do rollups on each prom, and then
have the rollups go to a final prom server.

The above description / architecture I hope is doable. If you see any crazy
stuff would love to know.

Joe

**Comment by brian-brazil** [comment]
> The 30 kHz sampling data is damn high number of time series style of data.

Prometheus only has 1 kHz time resolution, and the pushgateway will remember only the latest data point. I don't think Prometheus is the type of timeseries database you're looking for, as we're focused on systems monitoring rather than arbitrary timeseries.

**Comment by joeblew99** [comment]
Good to know. I will find a way to get the high frequency data out.
