### ISSUE TITLE
race in tsdb.headAppender.AppendHistogram

### ISSUE THREAD

**Issue by krajorama** [prometheus/prometheus#15139]
### What did you do?

Run Mimir with race detection enabled.

### What did you expect to see?

No race condition.

### What did you see instead? Under which circumstances?

WARNING: DATA RACE
Write at 0x00c08329f350 by goroutine 148443:
  github.com/prometheus/prometheus/tsdb.(*headAppender).AppendHistogram()
     .../vendor/github.com/prometheus/prometheus/tsdb/head_append.go:668 +0x6ed
  github.com/prometheus/prometheus/tsdb.(*dbAppender).AppendHistogram()
      <autogenerated>:1 +0xa1
  ...

Previous write at 0x00c08329f350 by goroutine 236366:
  github.com/prometheus/prometheus/tsdb.(*memSeries).appendHistogram()
      .../vendor/github.com/prometheus/prometheus/tsdb/head_append.go:1403 +0x1c9
  github.com/prometheus/prometheus/tsdb.(*headAppender).Commit()
      .../vendor/github.com/prometheus/prometheus/tsdb/head_append.go:1168 +0x2d48
  github.com/prometheus/prometheus/tsdb.dbAppender.Commit()
      .../vendor/github.com/prometheus/prometheus/tsdb/db.go:1278 +0x49
  github.com/prometheus/prometheus/tsdb.(*dbAppender).Commit()
      <autogenerated>:1 +0x4e
 ...

**Comment by krajorama** [comment]
Seems like we modify `memSeries` here https://github.com/prometheus/prometheus/blob/720a2599a6093f3416477bcc355c1aaf3c2df1da/tsdb/head_append.go#L676  without lock. The conflict is with https://github.com/prometheus/prometheus/blob/720a2599a6093f3416477bcc355c1aaf3c2df1da/tsdb/head_append.go#L1512 which is in fact under lock.

**Comment by krajorama** [comment]
Use case when it happens: two different goroutines happen to create the same native histogram series as the same time . The two appenders race and conflict on the common memSeries.

**Comment by Benz1993com** [comment]
Ok
