### ISSUE TITLE
Fingerprint collision handling is O(n^2) in the number of mappings

### ISSUE THREAD

**Issue by brian-brazil** [prometheus/prometheus#1513]
The fingerprint mappings write out a checkpoint at each mapping, syncing it to disk (https://github.com/prometheus/prometheus/blob/e83f05fe93c32c9e808b2a6a907337b442a540dc/storage/local/persistence.go#L1352). This is O(n^2).

This is done while the raw fingerprint is locked (https://github.com/prometheus/prometheus/blob/e83f05fe93c32c9e808b2a6a907337b442a540dc/storage/local/storage.go#L589), so a scrape of an existing timeseries which is now colliding is now blocked waiting for the checkpoint to be written. Each sample from a scrape is processed sequentially, so this can block many scrapes.

If you've many new collisions, this can block scraping for quite a while. The example I'm looking at seems to have tens of thousands of collisions which took an hour to work through before scraping worked again.

I recommend switching to appending new mappings rather than writing out a whole new file. We should also look at coalescing the write() and syncs() together, otherwise we'll be bottlenecked there too.

**Comment by beorn7** [comment]
oops
the code is definitely designed assuming collisions are rare.

**Comment by brian-brazil** [comment]
This case was with synthetic data for a loadtest, so more collisions and at a higher rate than usual.

We might away with just the coalescing, which'd also avoid a data format change.

**Comment by brian-brazil** [comment]
Ah, I'd missed how the fingerprintlocker is implemented. This will hold up all scraping as that works with locks for 1024 buckets rather than one per timeseries.
