### ISSUE TITLE
Gauges get expired

### ISSUE THREAD

**Issue by hryamzik** [prometheus/prometheus#1514]
I have a set of constants per host and would like to not to update them as often as other metrics. So I've tried to add timestamp to them:

```
# TYPE node_cpu_facts gauge
node_cpu_facts { fact="cores" } 8 1459466225000
node_cpu_facts { fact="count" } 2 1459466225000
node_cpu_facts { fact="threads_per_core" } 2 1459466225000
```

The problem is that they expire. It does look like a bug for me.

**Comment by brian-brazil** [comment]
This is working as expected, timestamps should be avoided for all bar expert users.

What you want here is to expose without timestamps via the textfile collector. I'd also suggest using a metrics per fact, rather than having one metric with many labels.

**Comment by hryamzik** [comment]
Indeed, had to move to:

```
# cat /var/lib/node_exporter/ansible_info.prom 
# Ansible managed: file modified on 2016-04-01 02:27:07 by hryamzik on hryamziks-mac
# TYPE node_cpu_facts gauge

node_cpu_cores 8
node_cpu_count 2
node_cpu_threads_per_core 2
```

Thanks for the fast replay, I think we can close this. I would say documentation update could be very helpful for this scenario.

**Comment by brian-brazil** [comment]
Can you point me at what docs lead you astray? I'm not aware of any official project docs in this area, only my own company blogs at http://www.robustperception.io/tag/textfile-collector/

**Comment by hryamzik** [comment]
I would expect to find these recommendations [here](https://prometheus.io/docs/practices/instrumentation/#use-labels)

**Comment by brian-brazil** [comment]
It's covered more at https://prometheus.io/docs/practices/naming/, there's an existing issue around cleaning up this split.

**Comment by hryamzik** [comment]
Good, thank you very much for your detailed and fast answers!
