### ISSUE TITLE
Can't run prometheus tests

### ISSUE THREAD

**Issue by Tusenka** [prometheus/prometheus#15153]
### What did you do?

go test cmd/prometheus/main_test.go 

### What did you expect to see?

run prometheus tests

### What did you see instead? Under which circumstances?

promql/parser/ast.go:22:2: found packages storage (buffer.go) and main (hello.go) in /home/cas12/prometheus/storage
FAIL    command-line-arguments [setup failed]
What is the best way to run tests in vs code?

### System information

Linux 6.8.0-45-generic x86_64

### Prometheus version

```text
prometheus, version 2.43.0 (branch: HEAD, revision: edfc3bcd025dd6fe296c167a14a216cab1e552ee)
  build user:       root@8a0ee342e522
  build date:       20230321-12:56:07
  go version:       go1.19.7
  platform:         linux/amd64
  tags:             netgo,builtinassets
```

**Comment by beorn7** [comment]
You have to run `go test ./cmd/prometheus`.

BTW, this is not a bug in Prometheus, nor is it a feature request. GH is not a very good way to get help here.

To get support, I recommend to use the various [community channels](https://prometheus.io/community/). This particular question doesn't even seem to be Prometheus specific. It's more about running tests in Go in general or how to run Go tests in VS Code in particular. Go and VS Code surely have community channels on their own.
