### ISSUE TITLE
Queue on different labels of the same metric fails

### ISSUE THREAD

**Issue by hryamzik** [prometheus/prometheus#1515]
Here're my metrics:

```
# TYPE node_cpu_facts gauge
node_cpu_facts { fact="cores" } 8
node_cpu_facts { fact="count" } 2
node_cpu_facts { fact="threads_per_core" } 2
```

And I can do some maths on it with a single label:

```
node_cpu_facts { fact="cores" } + node_cpu_facts
```

This looks wired but the result is actually ```node_cpu_facts { fact="cores" } * 2```.

And this queue simply fails:

```
node_cpu_facts{fact="cores"} * node_cpu_facts{fact="count"} * node_cpu_facts{fact="threads_per_core"}
```

I didn't find any special queue syntax for this case. The only workaround seem to be using 3 metrics instead of one labeled.

**Comment by brian-brazil** [comment]
Your labels don't match, you'd have to use `on` clauses here. As I indicated in #1514 you should be using 3 metrics for this as a label doesn't make sense here and makes things like this harder.

**Comment by hryamzik** [comment]
Can I ask you to show me the correct syntax if queuing in this scenario? I did switch to separate metrics but still a bit frustrated about this behaviour.

**Comment by brian-brazil** [comment]
In this case it's probably `node_cpu_facts{fact="cores"} * on (instance )node_cpu_facts{fact="count"}`

You could also expose the number of threads directly.

**Comment by hryamzik** [comment]
Thanks! Closing.
