### ISSUE TITLE
What time is expected to support influxdb?

### ISSUE THREAD

**Issue by xiaoqge** [prometheus/prometheus#1517]
What time can be expected to officially support influxdb database? I'm going to small-scale production environment

**Comment by brian-brazil** [comment]
Given https://influxdata.com/blog/update-on-influxdb-clustering-high-availability-and-monetization/ it looks like we will never be adding full support for InfluxDB into Prometheus itself.

**Comment by xiaoqge** [comment]
very thank you

**Comment by xiaoqge** [comment]
thank you
