### ISSUE TITLE
subtle change in regex parsing?

### ISSUE THREAD

**Issue by harmw** [prometheus/prometheus#1518]
We just upgraded from `0.16` to `0.17` and are observing the following change in behavior.

Our Grafana dashboards are sending queries like this:
```
service_http_server{job="blaze-gateway",status=~"^2"}
```
This used to work just fine, but now returns _no data_.
The same is true for this variation of the same query:
```
service_http_server{job="blaze-gateway",status=~"^20"}
```
However, the following all do work and return data points:
```
service_http_server{job="blaze-gateway",status=~"^2.*"}
service_http_server{job="blaze-gateway",status=~"^2.+"}
service_http_server{job="blaze-gateway",status=~"^200"}
```
Did something subtle change in this area?

**Comment by grobie** [comment]
Yes, check `Regular expression matchers in PromQL are anchored` in the changelog. This behavior changed in 0.17.0.

There used to be an example for that in the changelog: https://github.com/prometheus/prometheus/commit/7a0c0c3ca2d987689c0daf3eb0c7c78d624d4f56

**Comment by harmw** [comment]
Thats `diff` shows exactly what is going on, thanks! Looks like we'll have to change some of our queries :smile:

**Comment by grobie** [comment]
Well, as the author of that "noise" I totally agree. @brian-brazil and @fabxc had different opinions about this. There have been many questions about this regex change already.
