### ISSUE TITLE
Regexes are silently anchored

### ISSUE THREAD

**Issue by pete0emerson** [prometheus/prometheus#1519]
I'm seeing this in version 0.17.0.

Suppose `__meta_consul_tags` value is `,environment:stage,application:webapp,`.

In `relabel_configs`:

```
    - source_labels: ['__meta_consul_tags']
      regex:         ',application:(.*),'
      target_label:  'application'
      replacement:   '$1'
```

I would expect this to succeed. However, it fails, and my suspicion is that the regular expressions are anchored silently, because this succeeds:

```
    - source_labels: ['__meta_consul_tags']
      regex:         '.*,application:(.*),'
      target_label:  'application'
      replacement:   '$1'
```

If my assumption is correct, my suggestion would be that anchoring be not silently added, so if I truly wanted to anchor it, I'd use the regex anchor `^` to anchor it to the beginning of the string.

**Comment by juliusv** [comment]
This behavior has been changed intentionally in 0.17.0 to the one you are seeing because wanting anchored regexes was seen as the more frequently desired use case.

See also: https://github.com/prometheus/prometheus/issues/1518 and the linked changelog entry.

**Comment by brian-brazil** [comment]
This was a change we made on purpose, as not everyone is fully aware of how regexes work and we'd seen a lot of patterns in use that could unintentionally overmatch (consul tags being a common one).

**Comment by pete0emerson** [comment]
That makes sense. I'd suggest that it's worth documenting well in the `relabel_configs` section to make that clear to the people who are more proficient at regular expressions. If you'd like me to submit a patch, I would be glad to create one.

**Comment by grobie** [comment]
It's already documented? https://prometheus.io/docs/operating/configuration/#relabel_config

**Comment by juliusv** [comment]
It'd make sense to briefly mention it in the code block comment above the `regex` field too.

**Comment by grobie** [comment]
https://github.com/prometheus/docs/issues/370
