### ISSUE TITLE
Non-greedy regex in relabel_configs fails

### ISSUE THREAD

**Issue by pete0emerson** [prometheus/prometheus#1520]
Suppose `__meta_consul_tags` value is `,environment:stage,application:webapp,`.

With a config of: 

```
    - source_labels: ['__meta_consul_tags']
      regex:         ',environment:(.*),'
      target_label:  'environment'
      replacement:   '$1'
```

I get: `environment="stage,application:webapp"`.

That makes sense, because my regular expression is greedy and blowing past the first comma.

If I change it to be non-greedy:

```
    - source_labels: ['__meta_consul_tags']
      regex:         ',environment:(.*?),'
      target_label:  'environment'
      replacement:   '$1'
```

The results are unchanged: `environment="stage,application:webapp"`.

Interestingly enough, if I change my regex to:

```
    - source_labels: ['__meta_consul_tags']
      regex:         ',environment:([a-z]*),'
      target_label:  'environment'
      replacement:   '$1'
```

The results come back empty, i.e. no new labels are created.

**Comment by brian-brazil** [comment]
This is a consequence of the regex being anchored and you not having `(.*)` on either end.

**Comment by pete0emerson** [comment]
Ah, anchoring on both ends, yes, got it. (ref #1519 #1518)

Worth better documentation.

**Comment by grobie** [comment]
https://github.com/prometheus/prometheus/issues/1520
