### ISSUE TITLE
ratio with histogram_count results in values over 100%

### ISSUE THREAD

**Issue by ryswm** [prometheus/prometheus#15203]
### What did you do?

1. Query native histogram with the following format:
  ```
  histogram_count(sum(rate(example_metric_name{success="true"}[5m]))) / histogram_count(sum(rate(example_metric_name{}[5m])))
  ```
2. notice the percentage returned is greater than 100%
3. Queried again to confirm the values match a the time we see the percentage greater than 100%
```
   histogram_count(sum(rate(example_metric_name{success="true"}[5m]))) == 
   histogram_count(sum(rate(example_metric_name{}[5m])))
```

### What did you expect to see?

Expected the percentage to be 100% when the count from both timeseries matches

### What did you see instead? Under which circumstances?

percentage greater than 100% at certain evaluation points

### Prometheus version

```text
2.54.1
```

**Comment by akulabs8** [comment]
hey @ryswm do you need any help with this? Is there any way I can contribute as a begineer to this Repo to this issue?

**Comment by beorn7** [comment]
How much are the results above 100%? Can it still be explained by float inaccuracies?

We need more data to debug this. Ideally enough to reproduce it locally on a developer's machine.

**Comment by ryswm** [comment]
Thank you both for taking a look

we have done some additional testing on our side and found the issue to be caused by sources other than prometheus, so we can close this issue
