### ISSUE TITLE
An indicator of the accident push, Push Gateway How can the police?

### ISSUE THREAD

**Issue by xiaoqge** [prometheus/prometheus#1524]
I use a metric Push Gateway When I stopped, I realized how to police it? For example, a statistical service requests when this accident DOWN business machine, but pushgateway becomes 0, 0 but may be normal, so I can not judge whether this target is outside stopped

**Comment by juliusv** [comment]
I'm sorry, I'm not sure I understand your question. Could you try formulating it again?

**Comment by xiaoqge** [comment]
The Pushgateway is explicitly not an aggregator, but rather a metrics cache. It does not have a statsd-like semantics. The metrics pushed are exactly the same as you would present for scraping in a permanently running program.


Because the index is cached, when a stop push abnormalities, and how the alarm.

**Comment by xiaoqge** [comment]
@juliusv The Pushgateway is explicitly not an aggregator, but rather a metrics cache. It does not have a statsd-like semantics. The metrics pushed are exactly the same as you would present for scraping in a permanently running program.

Because the index is cached, when a stop push abnormalities, and how the alarm.

**Comment by juliusv** [comment]
Ok, that all makes sense, except that I still don't understand what you mean with "when a stop push abnormalities, and how the alarm."

I guess you want to alert on something - but on what? When the pushgateway is down? Or when a job stops pushing to the pushgateway? Or when a job pushes certain data to the pushgateway? What do you mean with "abnormalities"?

**Comment by xiaoqge** [comment]
@juliusv  thank you ,I mean, when a job pushes certain data to the pushgateway

**Comment by juliusv** [comment]
As long as your job is pushing data correctly to the pushgateway, you can alert on the resulting time series just like if it they were scraped directly from a target.

Do you have a concrete example? What metric do you want to alert on?

**Comment by xiaoqge** [comment]
thank you @juliusv I being the first to use other alternative methods
