### ISSUE TITLE
TSDB(histograms): possibility of counter reset overdetection

### ISSUE THREAD

**Issue by beorn7** [prometheus/prometheus#15247]
While discussing all the counter reset detection issues with overlapping chunks and out-of-order ingestion, I realized there is a rare edge case where a counter reset overdetection can happen even without any overlapping chunks or out-of-order ingestion. It just needs the later addition of an non-overlapping block to the TSDB:

The minimal case is a series ABCD where the counter reset happens in between B and C. However, only A and D are recorded first, with the counter reset detected between A and D. A and D happen to land in different blocks (not just different chunks). Later, B and C are backfilled and copied into the TSDB's data directory as a separate block, with a counter reset detected between B and C.

This results in the following: Each sample went into its own chunk (but of course, there might be real life cases with many samples in each of those chunks). The chunk containing C and D is each marked with a counter reset hint of `CounterReset` (i.e. "for sure there was a counter reset happening with this sample"). If the series is queried later, both of those counter reset hints will be propagated, so PromQL sees a counter reset for _both_ C and D, although it should only see it for C.

So far, we concluded that whenever any overlapping blocks or overlapping chunks get into the game, we need to return `UnknownCounterReset` whenever we switch from "one stream of samples to another". In this case, however, we have no way of noticing that the block containing B and C was inserted later, because there is just no overlap in blocks or chunks.

I think the easiest way out is to make sure that the 1st chunk in a block always gets a counter reset hint of `UnknownCounterReset`. I believe this has to be persisted in the chunk itself, not just set during querying, because blocks can get compacted, and then we will "forget" that a chunk was once the 1st in a block. (In the example above, the two old blocks and the newly inserted one might all got compacted into one block.)

**Comment by beorn7** [comment]
If we settle on always setting the counter reset information of the first chunk of a block to `UnknownCounterReset`, maybe we don't need to intercept the counter reset information during querying to set it to `UnknownCounterReset` when returning the first histogram of a chunk? Is it possible to delete chunks from within a block? (And even if it is, then we are mutating a block, and then we can as well change the counter reset information of the chunk after the deleted chunk…)

**Comment by krajorama** [comment]
I'm proposing an algorithm in #15346 to deal with this issue.

**Comment by beorn7** [comment]
> Is it possible to delete chunks from within a block?

The answer is (in my current understanding): Yes! If there are tombstones that affect a chunk completely, this chunk will be left out on block compaction. (I hope I got that right, @codesome has to correct me if not.)

In short: Without any additional measures (will look at #15346 in a minute), we can never be sure that consecutive chunks were consecutive at the time those chunks were created. So we either have to make sure that chunks get edited when they lose their immediate predecessor (which is probably hard or even infeasible), or we need some other means to find out if the current preceding chunk is still the same as the one during creation time of the chunk.

**Comment by beorn7** [comment]
With #15343 merged, let's close this. See #15346 for better counter reset detection, but with #15343, we aren't doing anything wrong anymore.
