### ISSUE TITLE
How to monitor TCP port is normal?

### ISSUE THREAD

**Issue by xiaoqge** [prometheus/prometheus#1525]
How to monitor TCP port is normal? For example I want to monitor the TCP port 1103 port is normal, we enable TCP socket is to build one at a time to determine the State of the port is UP. If Prometheus is used to solve this problem?

**Comment by brian-brazil** [comment]
The blackbox exporter with the TCP module should do this for you.

**Comment by xiaoqge** [comment]
thank you
