### ISSUE TITLE
UTF-8: scrape fails with quoted "utf8" key in exemplar

### ISSUE THREAD

**Issue by tcolgate** [prometheus/prometheus#15259]
### What did you do?

Expose an a metric with exemplar from client_go (via opentelemetry), where one of the labels features a non-traditional character in the label (e.g. `http.scheme`),

### What did you expect to see?

This is exported in sccraping as:
```
metric_total{n="1"} 0 # {"net.http"="abc"} 1.0
```
Prometheus then fails to scrape this due to the presence of the quote:
```
 expected label name, got "\"" ("INVALID") while parsing: "metric_total{n=\"1\"} 0 # {\""
```

### What did you see instead? Under which circumstances?

Prometheus should successfully scrape the quote label name.

### System information

Linux 6.11.5-arch1-1 x86_64

### Prometheus version

```text
tested on 
commit: dd4eb4590dc7f4163afb452fd3f2f189caf2d20f

discovered via opentelemetry collector using 

github.com/prometheus/prometheus v0.54.1
```
```


### Prometheus configuration file

_No response_

### Alertmanager version

_No response_

### Alertmanager configuration file

_No response_

### Logs

_No response_

**Comment by dashpole** [comment]
cc @ywwg 
This is from someone trying out https://github.com/open-telemetry/opentelemetry-go/pull/5755.

**Comment by ywwg** [comment]
ah yeah I bet we missed exemplar parsing
