### ISSUE TITLE
Apply selectors to entire expressions, with or without per-query predicate push-down

### ISSUE THREAD

**Issue by ringerc** [prometheus/prometheus#15368]
### Proposal

I frequently find myself wanting to execute a composite PromQL expression over a subset of the target data available, by applying common label filters to all query terms within a grouped expression such as a chain of operators with label matching.

This must usually be expressed by adding each label to each individual query within the expression, which is verbose, cumbersome and hard to maintain.

Think

```
kube_pod_info{namespace=~"$something"}   <-- namespace selector
* on (kube_cluster, uid)
  group_left(some_labels)
  group by (kube_cluster, uid, some_labels) (
    kube_pod_labels{namespace=~"$something"}  <-- namespace selector repeated
  )
* on (kube_cluster, uid)
  group_left(some_annotations)
  group by (kube_cluster, uid, some_annotations) (
    kube_pod_annotations{namespace=~"$something"}   <-- namespace selector repeated
  )
...
```

The selector repetition ensure that Prometheus doesn't execute some queries against _all_ available data, then discard the majority of it while doing unnecessarily-expensive label matching processing.

Because the `on(...)` expression doesn't mention the filter predicate `namespace` label, Prometheus cannot infer that the filter on `kube_pod_info{namespace=~"$namespace"}` can be implicitly applied to the subsequent queries in the label-matching expression chain. In this case it'd be possible to add `namespace` to all the `on(...)` and `group by (...)` expressions, but it's unclear if Prometheus will actually infer the constraint and execute the other queries in the label-matching chain with it even if it's an explicit label matching term.

So I propose the language extension `(expression) pushdown {selector}`, which would apply `{selector}` to all queries within `expression` before they are executed, such that the following would execute with the same results as the query above:

```
(
  kube_pod_info{}
  * on (kube_cluster, uid)
    group_left(some_labels)
    group by (kube_cluster, uid, some_labels) (
      kube_pod_labels{}
    )
  * on (kube_cluster, uid)
    group_left(some_annotations)
    group by (kube_cluster, uid, some_annotations) (
      kube_pod_annotations{}
    )
) pushdown {namespace=~"$namespace"}  <-- Selector will be applied to all queries in the group
```

This is syntatic sugar, since the execution is the same, but would be very helpful when authoring larger or more complex queries.

There's a reason for the `pushdown` keyword, rather than just writing `(expression){selector}`: ideally, PromQL would also have a way to filter the _results_ of an expression after execution, like `FROM (SELECT ...) AS q WHERE ...` table-subqueries in SQL. And `(expression){selector}` to me is how I would expect to "spell" that most naturally. So it would be a shame to "claim" the `(expression){selector}` syntax for selector push-down, when it'd be better applied to a powerful and functional query language enhancement. Presently this post-filtering of an expression can be emulated with `(some_expression_here) * on (label1) group_left() (label_replace(vector(1),"label1","foo","","")`, but only for exact label equality, not for regex selectors.

---

Ideally Prometheus would be able to selectively push the filter down only to those metrics for which the label was defined, producing the best-of-both-worlds results like SQL databases can with query predicate pushdown into joins and scans. But this isn't possible with the schemaless free-form nature of TSDB, and would have problems with label name conflicts in any case. Prometheus just doesn't know if the `uid` in `kube_pod_labels` means the same thing as the `uid` in `kube_pod_annotations` so it can't do "smart" pushdown.

While I'm on about syntactic enhancements, a way to express `* on (join_labels) group_left(info_labels) group by (join_labels,info_labels) (some_vector)` without repeating the labels in the `group by` clause would also be awesome, but I'm not raising a feature request for that since I can't see myself or anyone else having time to implement it, and hopefully the `info` helper will eventually make the need go away for the most common info-metrics join case.

**Comment by beorn7** [comment]
This is pretty much a duplicate of https://github.com/prometheus/prometheus/issues/11609 , isn't it?

Long ago, we decided that we want some kind of `with {namespace=~"some_reg_exp"}` syntax. Somebody just needs to implement it.

**Comment by ringerc** [comment]
@beorn7 I agree. I think I misunderstood that ticket. It's fair to describe the syntactic-sugar suggestion here as a dup of that ticket, and the other part is not a realistic feature suggestion for Prometheus at this time anyway.

**Comment by ringerc** [comment]
Duplicates https://github.com/prometheus/prometheus/issues/11609
