### ISSUE TITLE
HTTP targets for blackbox-exporter became invalid since 0.18.0rc1

### ISSUE THREAD

**Issue by Bregor** [prometheus/prometheus#1536]
Hello!

Sorry in advance if this really isn't an issue.

After update to `0.18.0rc1` previously valid targets for `blackbox-exporter` became invalid.

Related config fragment:

	metrics_path: /probe
	params:
	  module: [http_2xx]

	target_groups:
	  - targets:
		- https://somewebsite.ru/health
		- https://api.somewebsite.ru/global/health
		- https://m.somewebsite.ru/health

After update there are log records like:

	ERRO[0002] Target update failed: "https://somewebsite.ru/health" is not a valid hostname  source=targetmanager.go:293 target_group=0

**Comment by brian-brazil** [comment]
That is an invalid configuration, try it with the `relabel_config`.

**Comment by Bregor** [comment]
`relabel_configs` section:

    relabel_configs:
      - source_labels: [__address__]
        regex: (.*)(:80)?
        target_label: __param_target
        replacement: ${1}
      - source_labels: [__param_target]
        regex: ^https?://([^/]+).*$
        target_label: instance
        replacement: ${1}
      - source_labels: [__meta_consul_node]
        regex: (.+)
        target_label: __address__
        replacement: ${1}

Is it wrong?

**Comment by brian-brazil** [comment]
Yes, you're not overriding the `__address__` label. Look at the example on https://github.com/prometheus/blackbox_exporter#prometheus-configuration

**Comment by Bregor** [comment]
`__address__` label always should be equal to address of `blackbox-exporter`?

**Comment by brian-brazil** [comment]
Yes, `__address__` is what Prometheus actually talks to.

**Comment by Bregor** [comment]
Thank you so much!
Works like a charm.
