### ISSUE TITLE
open consoles/node.html: no such file or directory

### ISSUE THREAD

**Issue by hryamzik** [prometheus/prometheus#1540]
After updating to the latest version consoles stopped working. I do have them on the file system, like ```/opt/prometheus/consoles/node.html```. There's nothing in logs about this. Do I miss some configuration option at this point?

**Comment by juliusv** [comment]
Hmm, it still works for me - what is your exact Prometheus command line?

**Comment by hryamzik** [comment]
```
exec chpst -u prometheus "//opt/prometheus/prometheus" -config.file=/etc/prometheus/prometheus.yml -storage.local.path=/var/lib/prometheus -alertmanager.url=http://127.0.0.1:9093 -storage.local.retention=4464h0m0s -web.external-url=https://mycompany.org
```

Might be a tailing slash missing....

**Comment by juliusv** [comment]
By default, Prometheus looks for your console files in the `consoles` directory, relative to the current working directory:

If it worked for you before, maybe it is because you still also had a `consoles` directory in the directory you were running Prometheus from?

For your path, you'll need to set `-web.console.templates= opt/prometheus/consoles`. You probably also need to adjust the `-web.console.libraries` flag, which defaults to `console_libraries` relative to the current working directory.

**Comment by hryamzik** [comment]
> maybe it is because you still also had a consoles directory in the directory you were running Prometheus from?

Nope, I've been running it with [runit](https://github.com/gitinsky/ansible-role-prometheus) so nothing really changed except the prometheus version. Will try templates options now, thank you!

**Comment by juliusv** [comment]
@hryamzik That's odd - I can't really explain why it worked before then, unless the current working directory contained those dirs. Do runit-started services perhaps inherit the current working dir from the user who starts them (a common problem with some supervisor systems is also that env vars leak in from the user who starts/stops services, etc. - something which systemd fixes)?

**Comment by hryamzik** [comment]
In fact I've also had to move from sudo to chpst on runit and that may be the cause. As we still run a lot of 14.04 I'm not going to change runit to systemd for now...

**Comment by kaihendry** [comment]
I think I have the same issue

    error executing template __console_/node.html: html/template:__console_/node.html:34:12: no such template "tail"

Upon https://prom.dabase.com/consoles/node.html

I'm launching prom/prometheus like so: https://github.com/kaihendry/pingprom/blob/master/prometheus%40.service

**Comment by gdmello** [comment]
Had the same issue as @kaihendry above, but was resolved by setting `web.console.libraries` to the full path to `console_libraries` folder as @juliusv suggested above.

**Comment by kaihendry** [comment]
Oh I forgot to mention I fixed it like so https://github.com/kaihendry/pingprom/commit/395a4c60d129a2ecc45b526bc57929a29048e1a7, i.e. not mounting like so ` -v /home/%i/pingprom/prometheus:/etc/prometheus/`

**Comment by pajtai** [comment]
If anyone else runs into this with 2.0.0. The config flag is now, `--web.console.templates=`. The config flags can be seen by running `prometheus -h`

**Comment by mperezco** [comment]
I have a running RPM deployment that works for Prometheus 2.1.0 ... in case it helps:
https://github.com/mperezco/prometheus-rpm
