### ISSUE TITLE
Subquery ranges are left-closed and right-closed when returning the subquery result directly

### ISSUE THREAD

**Issue by charleskorn** [prometheus/prometheus#15412]
### What did you do?

I performed a query like `metric[20s:5s]` at T=30s.

### What did you expect to see?

Following https://github.com/prometheus/prometheus/issues/13213 and https://github.com/prometheus/prometheus/pull/13904, I expected the result to include 4 points: T=15s, T=20s, T=25s and T=30s, ie. the point on the left boundary (at T=10s) is excluded.

This mirrors the behaviour of range selectors. 

### What did you see instead? Under which circumstances?

The point on the left boundary (T=10s in the example above) was included.

This is visible in tests like this one, where the point at T=10000 is included in the result, but should be excluded if the range is left-open: https://github.com/prometheus/prometheus/blob/101b1c307f2b80b142c38f7cebcc3db50084ed8f/promql/engine_test.go#L1830-L1842

**Comment by beorn7** [comment]
Interestingly, #13904 did change a lot of the subquery tests, and the changes seem consistent with a left-open behavior, see https://github.com/prometheus/prometheus/pull/13904/files#diff-b1b1097ed667a65058420400e50e96853141ff29f6f46758f4abb6691778e18d

**Comment by beorn7** [comment]
Maybe this is an artifact of how the test above is performed? The regular framework tests seem to work as expected, as does a user-driven end-to-end test. See this screenshot:
![image](https://github.com/user-attachments/assets/da0e3a2c-6f06-4222-b127-f721430bffb5)

Note that I did manually align the query timestamp above (to get the "perfect alignment", which is the usual way of triggering the "one more sample than expected" case.

**Comment by beorn7** [comment]
This is super weird. Now I managed to trigger the 5-sample case with the exact same setup as above in the screen shot.

**Comment by beorn7** [comment]
OK, clarified by inspecting the actual HTTP requests. The UI sometimes still adds some milliseconds to the query time even if a fixed time is set. If it actually sends a perfectly aligned timestamp, I see the five samples.
Still trying to explore why the framework tests work as expected.

**Comment by beorn7** [comment]
I think I have found something, but still have to work out the details.

**Comment by beorn7** [comment]
Fix to be released in v3.0.1

**Comment by charleskorn** [comment]
Thanks for addressing this so quickly @beorn7!
