### ISSUE TITLE
Provide start+end parameters in /api/v1/series

### ISSUE THREAD

**Issue by grobie** [prometheus/prometheus#1542]
When using dashbords with template variables, e.g. in Grafana, it makes sense to only list labels available in the selected dashboard time range. At the moment `/api/v1/series` will always return all possible values over the lifetime of a metric: https://github.com/prometheus/prometheus/blob/322ad49b01a11d925d9fe326cef223344f6b91f2/web/api/v1/api.go#L230

I suggest to offer optional `start` and `end` parameters similar to the interface of `/api/v1/query_range` to specify the time range.

@mtanda

**Comment by gfliker** [comment]
+1 for this feature.

**Comment by mtanda** [comment]
I want this feature too.
With Grafana templated dashboard, we can make dashboard for the hosts which alive in the time period.

**Comment by jimmidyson** [comment]
Fantastic! Thanks @juliusv!
