### ISSUE TITLE
What open source server asset management system can be used with prometheus?

### ISSUE THREAD

**Issue by xiaoqge** [prometheus/prometheus#1544]
What open source server asset management system can be used with prometheus?

**Comment by matthiasr** [comment]
There are no integrations with specific asset management solutions. How these would work strongly depends on your environment anyway. You can use [file based service discovery](http://prometheus.io/docs/operating/configuration/#<file_sd_config>) to integrate with anything.

**Comment by xiaoqge** [comment]
thank you @matthiasr
