### ISSUE TITLE
Bug: `avg_over_time` should ignore NaN values, like for `min_over_time` and `max_over_time`

### ISSUE THREAD

**Issue by atsu85** [prometheus/prometheus#15450]
### What did you do?

Having following series with 3 values, just one of them `NaN`:
> [data{type="some_nan3"} NaN 0 1](https://github.com/prometheus/prometheus/blob/main/promql/promqltest/testdata/functions.test#L1001)

(taken from [test data](https://github.com/prometheus/prometheus/blob/main/promql/promqltest/testdata/functions.test#L997-L1002) used by [other *_over_time functions tests](https://github.com/prometheus/prometheus/blob/main/promql/promqltest/testdata/functions.test#L1004-L1023))

currently produces `NaN`, unlike for `min_over_time` and `max_over_time` functions, where it produces expected results, that ignore `NaN` values:
* [0 for min_over_time result](https://github.com/prometheus/prometheus/blob/main/promql/promqltest/testdata/functions.test#L1008)
* [1 for max_over_time](https://github.com/prometheus/prometheus/blob/main/promql/promqltest/testdata/functions.test#L1015)

### What did you expect to see?

avg_over_time for `[NaN, 0, 1]` should provide the same result as when ignoring all `NaN`s (like `min_over_time` and `max_over_time` functions), so expected result of avg_over_time for `[0, 1]` would be 0.5 instead of `NaN`. 

Based on Prometheus documentation, [avg-, min- and max- over time functions](https://prometheus.io/docs/prometheus/latest/querying/functions/#aggregation_over_time) should behave similarly (it doesn't mention `NaN` values):
> The following functions allow aggregating each series of a given range vector over time and return an instant vector with per-series aggregation results:
> * avg_over_time(range-vector): the average value of all points in the specified interval.
> * min_over_time(range-vector): the minimum value of all points in the specified interval.
> * max_over_time(range-vector): the maximum value of all points in the specified interval.
> 
> Note that all values in the specified interval have the same weight in the aggregation even if the values are not equally spaced throughout the interval.

### What did you see instead? Under which circumstances?

`avg_over_time` produces `NaN` when at least one of the values in range is `NaN` (unlike min_over_time and max_over_time that just ignore `NaN` values)

### Prometheus version

```text
prometheus, version 2.49.1 (branch: HEAD, revision: 43e14844a33b65e2a396e3944272af8b3a494071)
  build user:       root@6d5f4c649d25
  build date:       20240115-16:58:43
  go version:       go1.21.6
  platform:         linux/amd64
  tags:             netgo,builtinassets,stringlabels
```

**Comment by atsu85** [comment]
[this test failure](https://github.com/prometheus/prometheus/actions/runs/12008490726/job/33471236452?pr=15451) proves that `avg_over_time` over [[NaN, 0, 1]](https://github.com/prometheus/prometheus/pull/15451/commits/33757c84ce0aabf47f82a37e415e37223012e5f4#diff-f277c3549a17549dbc047c4f13cdeebd450a0a69b2a568f7dde50935583b3540R1001) produces `NaN` instead of [expected 0.5](https://github.com/prometheus/prometheus/pull/15451/commits/33757c84ce0aabf47f82a37e415e37223012e5f4#diff-f277c3549a17549dbc047c4f13cdeebd450a0a69b2a568f7dde50935583b3540R1029)

**Comment by bboreham** [comment]
@beorn7 has probably thought about what it should do.

**Comment by beorn7** [comment]
The current behavior is correct and intended.

First of all, the `..._over_time` functions are (in most cases) just over-time version of "real" aggregation operators. So their behavior should be consistent with the corresponding aggregation operator (i.e. if you want to change `avg_over_time`, you also have to change `avg`).

About the actual point: `min`, `max`, and their corresponding `..._over_time` versions do _not_ ignore `NaN` values. For example, if there are only `NaN` values in the input, they _do_ return `NaN`. However, since `NaN` is never greater or less than any other value, they are not returned if there is at least one non-`NaN` value in the input.

`avg` (and `avg_over_time`) should therefore not ignore `NaN` either. It is mathematically correct and important that the average of a number of values is `NaN` if at least one of them is `NaN`.

In very general `NaN` is a meaningful value in Prometheus, not a placeholder for "missing data" or something (see also the [OpenMetrics spec](https://github.com/prometheus/OpenMetrics/blob/main/specification/OpenMetrics.md#values), where this is called out explicitly). If you want to filter out `NaN` from the input, you can use the usual PromQL tricks (like `<= +Inf`, which is only false for `NaN` values).

**Comment by atsu85** [comment]
@beorn7, thanks for explaining!

> since NaN is never greater or less than any other value, they are not returned if there is at least one non-NaN value in the input.

ok, thats fair but unexpected reasoning why `min_over_time` and `max_over_time` don't get screwed up by `NaN` values unlike `avg_over_time`.

However 
1) if current behavior of `NaN` handling is considered correct, then doesn't `avg_over_time` deserve tests with `NaN` values, like `min_over_time` and `max_over_time`? Currently [avg_over_time tests](https://github.com/prometheus/prometheus/blob/5e124cf4f2b9467e4ae1c679840005e727efd599/promql/promqltest/testdata/functions.test#L699-L818) don't cover any scenarios related to `NaN`, unlike for example [min_over_time and max_over_time tests](https://github.com/prometheus/prometheus/blob/5e124cf4f2b9467e4ae1c679840005e727efd599/promql/promqltest/testdata/functions.test#L1004-L1016)

2) wouldn't the `NaN` handling deserve documentation also on the website? It wasted a lot of my time, and I'd bet I'm not the only one.

**Comment by atsu85** [comment]
> If you want to filter out NaN from the input, you can use the usual PromQL tricks (like <= +Inf, which is only false for NaN values).

@beorn7, cool trick! Is that also documented somewhere? I tried searching for that, but failed, like i previously failed while searching for excluding `NaN` values for `avg_over_time`

**Comment by atsu85** [comment]
> Adding those tests would indeed by preferred. Would you like to create a PR?

@beorn7, personally I really don't want to be the one that adds the tests for current behavior to carve it into the stone for future generations that might also have doubts/questions about its correctness
(as it didn't make sense to me initially before your reply and intuitively it still doesn't make much more sense, although i understand it is desired).
But feel free to modify the expected values in [the code of my draft PR that i used to show current behavior](https://github.com/prometheus/prometheus/pull/15451/files).

**Comment by beorn7** [comment]
The behavior is already carved into stone. But anyway, I have created #15475 .
