### ISSUE TITLE
where are prom.lib and menu.lib in console_libraries?

### ISSUE THREAD

**Issue by DannyRavi** [prometheus/prometheus#15524]
### What did you do?

I was running example [CONSOLE TEMPLATES](https://prometheus.io/docs/visualization/consoles/#example-console) and saw links to [prom.lib](https://github.com/prometheus/prometheus/blob/main/console_libraries/prom.lib) and menu.lib  files in the example description, but it seems these files don't exist in newer versions.

### What did you expect to see?

access to prom.lib and menu.lib for run the CONSOLE TEMPLATES example

### What did you see instead? Under which circumstances?

broken links for prom.lib and menu.lib in documents of [CONSOLE TEMPLATES](https://prometheus.io/docs/visualization/consoles/#example-console)

**Comment by beorn7** [comment]
Yeah, the console_libraries directory got removed. Console templates are still offered as a feature, but not any longer with any libraries or examples (for various reasons).

https://prometheus.io/docs/visualization/consoles/ needs an update. I have filed https://github.com/prometheus/docs/issues/2554 for it and will close this one. (The relevant documentation is hosted in the docs repository, not here in the prometheus repo.)
