### ISSUE TITLE
`go test ./...` failures on linux 386/i686

### ISSUE THREAD

**Issue by TinfoilSubmarine** [prometheus/prometheus#15547]
### What did you do?

Build prometheus for linux-i686 then run tests.

### What did you expect to see?

Tests passing as they pass for all other architectures.

### What did you see instead? Under which circumstances?

Tests failing, looks like it may be related to 64-bit vs 32-bit types. [Logs](https://github.com/user-attachments/files/18040904/prometheus-test-i686.txt.zip)

### System information

Linux 6.6.63_1 i686

**Comment by beorn7** [comment]
Relevant dev-summit topic: https://docs.google.com/document/d/1uurQCi5iVufhYHGlBZ8mJMK_freDFKPG0iYBQqJ9fvA/edit?pli=1&tab=t.0#bookmark=id.5ds2naruydu0
