### ISSUE TITLE
how to support logic operators in promql

### ISSUE THREAD

**Issue by freshmanGDUT** [prometheus/prometheus#15544]
### Proposal

logicExpression like  "a > bool  5 && b < bool 10 || c > bool 19"，i find its hard to desc in promql. Any Idea that I can desc this logicExpression in promql. And I also have a question, why doesnt promql support logic operations between time point?

**Comment by beorn7** [comment]
Github issues aren't really a good place for this kind of questions. For a feature request, we need something more tangible. May I recommend to discuss this via our [community channels](https://prometheus.io/community)?

If a concrete feature request materializes, you can file that as an issue here (or use https://github.com/prometheus/proposals for more involved changes).
