### ISSUE TITLE
Add timestamp function

### ISSUE THREAD

**Issue by brian-brazil** [prometheus/prometheus#1557]
We should add a function that returns the timestamp of a point in unixtime. `timestamp` seems like a good name.

**Comment by juliusv** [comment]
Isn't that automatically always the same as just `time()`, given that we set the timestamp of sample points to aligned time steps?

**Comment by brian-brazil** [comment]
The timestamp of the sample may be up to 5 minutes earlier though.

**Comment by juliusv** [comment]
Right, but we already set the timestamp of any sample to the evaluation timestamp before any function would be even able to look at the raw underlying timestamp. So this would imply changing that.

https://github.com/prometheus/prometheus/blob/master/promql/engine.go#L692

What'd be the use case for this?

**Comment by brian-brazil** [comment]
It's a bit more relevant after #398, but for now it'd help for example detect stale series.
