### ISSUE TITLE
Add pods name in kubernetes discovery

### ISSUE THREAD

**Issue by rvrignaud** [prometheus/prometheus#1562]
Hello,

I'm new to prometheus, so I may have missed some information.
When I use the kubernetes discovery with the configuration given in the documentation, I only have the pod ip in the instance tag. This is not really easy to use, most of the time we need to get the pod name associated.
Would that be possible to add the pod name in the labels ?

**Comment by matthiasr** [comment]
I think #1449 will add this naturally.

**Comment by fabxc** [comment]
I would like to have Kubernetes SD stable for 1.0.0 so I added it to that milestone.

**Comment by fabxc** [comment]
Fixed via #1449
