### ISSUE TITLE
Hover bug in /status

### ISSUE THREAD

**Issue by rvrignaud** [prometheus/prometheus#1563]
Hello,

There is a small interface bug in /status. In my deployment the hover is too small and the informations are not readable.
I'm using prometheus 0.18.0. I have the same problem on both chrome and firefox.

<img width="380" alt="screen shot 2016-04-18 at 15 30 29" src="https://cloud.githubusercontent.com/assets/525763/14608692/0c559396-0587-11e6-9d44-37a3f16eb7c8.png">

**Comment by brian-brazil** [comment]
This was initially added so that we could have something for debugging relabelling, it needs to be done properly.
