### ISSUE TITLE
Wish: Repo of grafana dashboards

### ISSUE THREAD

**Issue by tarjei** [prometheus/prometheus#1565]
Hi, I know this might be asking a lot, but it would be super super useful if you published a set of grafana starter dashboards for each of the exporters. This would reduce the rampuptime for getting value out of prometheus _a lot_ and be a great way for users to share tips.

**Comment by jimmidyson** [comment]
I started something like this for what I needed at the time at https://github.com/jimmidyson/prometheus-grafana-dashboards - happy to push somewhere else if something more "official" comes along.

**Comment by grobie** [comment]
I've talked about this with the grafana/raintank guys. https://grafana.net/ will soon allow to share dashboards (in addition to datasources, panels, etc.). There will be organization support and we'll get the prometheus organization to share all our dashboards under.

There will also be prometheus examples on http://play.grafana.org/ soon.

In the meantime, You can find my node_exporter example here: https://gist.github.com/grobie/eea8f9d6967debb29f405d4d4503cef5 Here is a screenshot of it: https://twitter.com/dagrobie/status/718941740112158721

**Comment by juliusv** [comment]
Thanks @grobie. Closing the issue here, as it's not about the Prometheus server.

**Comment by tarjei** [comment]
Kudos!
20. apr. 2016 4.41 p.m. skrev "Julius Volz" <notifications@github.com>:
