### ISSUE TITLE
docs: "Writing HTTP Service Discovery" nit: r/complimentary/complementary

### ISSUE THREAD

**Issue by DazWilkin** [prometheus/prometheus#15685]
https://github.com/prometheus/prometheus/blame/c8359fcd6bedbcd49bc9515d4bd789788ea4eadb/docs/http_sd.md#L11

A nit but please revise to use "complementary" (as in "work well with") rather than "complimentary" (as in "otherwise the document is good").

**Comment by beorn7** [comment]
Sound about right. Would you like to create a PR?
