### ISSUE TITLE
point detail shows on top of date pane

### ISSUE THREAD

**Issue by raliste** [prometheus/prometheus#1569]
![image](https://cloud.githubusercontent.com/assets/388935/14718221/c6e4cf9c-07cb-11e6-88f7-fcbb2639e328.png)

Making it really difficult to tell which date you are supposed to be seeing.

**Comment by juliusv** [comment]
:+1: In PromDash we solved this by including the date+time in the hover detail itself:

https://github.com/prometheus/promdash/pull/72/files

We should do the same here.

**Comment by juliusv** [comment]
Giving this a try now.
