### ISSUE TITLE
High availability Settings for Bitnami Prometheus

### ISSUE THREAD

**Issue by vitaaaaa1** [prometheus/prometheus#15714]
### What did you do?

I am using the Helm Chart (Prometheus + Thanos) provided by Bitnami to deploy in my cluster. If I want to set Prometheus to high availability (adjusting the replica count to 2), this means that there will be two Thanos sidecars storing tsdb data to S3. And since the two Prometheus instances actually use the same set of configuration files, it is also impossible to use "external labels" to distinguish between the two Prometheus instances. Will such an architecture cause any problems?
![image](https://github.com/user-attachments/assets/f85b34c5-725c-4775-a63a-6ca24d6f7071)

This is the architecture diagram I envisioned.
![image](https://github.com/user-attachments/assets/6afbe672-4324-42aa-90e7-65f72c49b1b2)

### What did you expect to see?

1

### What did you see instead? Under which circumstances?

1

### System information

1

### Prometheus version

```text
1
```

### Prometheus configuration file

```yaml
1
```

### Alertmanager version

```text
1
```

### Alertmanager configuration file

```yaml
1
```

**Comment by bwplotka** [comment]
Please file the bug on that helm chart repository.

BTW: The solution is simple here -- chart should configure Prometheus instances with the external label that will use the proper unique instance ID from the environment variable using env expansion: https://prometheus.io/docs/prometheus/latest/configuration/configuration/

![image](https://github.com/user-attachments/assets/38e71996-bc4d-425a-ad68-7738db5fd7a4)

**Comment by vitaaaaa1** [comment]
> Please file the bug on that helm chart repository.请在那个 Helm 图表仓库中提交该错误报告。
> 
> BTW: The solution is simple here -- chart should configure Prometheus instances with the external label that will use the proper unique instance ID from the environment variable using env expansion: https://prometheus.io/docs/prometheus/latest/configuration/configuration/顺便说一下，这里的解决方案很简单——图表应使用环境变量中的适当唯一实例 ID 通过环境变量扩展来配置 Prometheus 实例的外部标签：https://prometheus.io/docs/prometheus/latest/configuration/configuration/
> 
> ![image](https://private-user-images.githubusercontent.com/6950331/398937733-38e71996-bc4d-425a-ad68-7738db5fd7a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUzMDU0MTQsIm5iZiI6MTczNTMwNTExNCwicGF0aCI6Ii82OTUwMzMxLzM5ODkzNzczMy0zOGU3MTk5Ni1iYzRkLTQyNWEtYWQ2OC03NzM4ZGI1ZmQ3YTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMjdUMTMxMTU0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzA3ZmQwNzRmNzhlOTMyOGFhNDkyODRjYjQwMmJhYmM2YjQ1OWIyYjc1MmVhNTIxNDcwZDUzMTM3ZTUzMDRmOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.gDUnyrN2bQ7GKWfut3AcI9D26rfRS_RIEirXAM1NIfc)

Although thanos query keeps reporting errors in the log
` ` `
data in the same bucket" address=192.168.31.50:10902 extLset="{replica=\"A\"}" duplicates=2
` ` `
However, there is no duplicate data in either the query or the alarm, does this mean that there will be no problem if the label is consistent

**Comment by vitaaaaa1** [comment]
> Please file the bug on that helm chart repository.
> 
> BTW: The solution is simple here -- chart should configure Prometheus instances with the external label that will use the proper unique instance ID from the environment variable using env expansion: https://prometheus.io/docs/prometheus/latest/configuration/configuration/
> 
> ![image](https://private-user-images.githubusercontent.com/6950331/398937733-38e71996-bc4d-425a-ad68-7738db5fd7a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUzMTI5MDcsIm5iZiI6MTczNTMxMjYwNywicGF0aCI6Ii82OTUwMzMxLzM5ODkzNzczMy0zOGU3MTk5Ni1iYzRkLTQyNWEtYWQ2OC03NzM4ZGI1ZmQ3YTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMjdUMTUxNjQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWEzYmIyMGJhMmE1MDQ5MGM4M2FjN2U3NTIzYjVkYTdiZjYwMjg5ZjdlNjJjMDJiMmY4ZDAxZTRhNzExNzkyYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.mBGyR9CLTXuXScY9P05TxpRuWEDjbcNOoYSd3pzNuOY)

Thank you for your reply. I have another question: Why did I set the environment variable as a label, but it did not actually take effect
![image](https://github.com/user-attachments/assets/2f608b19-896a-4f59-a5ac-9686f1191001)
```
I have no name!@prometheus-server-8484d7f8ff-tjds4:/opt/bitnami/prometheus$ env | grep HOSTNAME
HOSTNAME=prometheus-server-8484d7f8ff-tjds4

```
