### ISSUE TITLE
How to reload Prometheus's configuration?

### ISSUE THREAD

**Issue by guxia** [prometheus/prometheus#1572]
I want to reload Prometheus's configuration,but i don't know how to sending SIGHUP to the Prometheus process on ubuntu?

**Comment by barkerd427** [comment]
kill -HUP <process ID>

**Comment by juliusv** [comment]
Or `killall -HUP prometheus`.

**Comment by guanglinlv** [comment]
Or `curl -s -XPOST localhost:9090/-/reload`

**Comment by guxia** [comment]
Thank everyone!

**Comment by vivipolli** [comment]
> Or `curl -s -XPOST localhost:9090/-/reload`
Lifecycle APIs are not enabled

**Comment by juliusv** [comment]
@vivipolli For the web reload endpoint to work, you'll need to set the `--web.enable-lifecycle` command-line flag, see https://prometheus.io/docs/prometheus/latest/configuration/configuration/#configuration.
