### ISSUE TITLE
make: promu: Command not found

### ISSUE THREAD

**Issue by aristide** [prometheus/prometheus#1574]
I just downloaded source code from github and i'ma having the error **make: promu: Command not found** when i tried to compile prometheus. 

I just followed instructions from README.md
help !!!

**Comment by sdurrheimer** [comment]
The build process didn't change, it's stil `make build` to build it from source.

@aristide Do you have a working Golang envrionement ?

**Comment by juliusv** [comment]
@sdurrheimer From a clean Prometheus checkout in the right GOPATH, I get:

```
make
>> formatting code
# cd /home/julius/gosrc/src/github.com/prometheus/promu; git pull --ff-only
error: Your local changes to the following files would be overwritten by merge:
	cmd/build.go
Please, commit your changes or stash them before you can merge.
Aborting
Updating e068833..53425d6
package github.com/prometheus/promu: exit status 1
make: *** [promu] Error 1
```

Go version 1.6, but I guess that's not related?

**Comment by juliusv** [comment]
Ah duh, should have read the whole error message, my fault.

**Comment by aristide** [comment]
yes!! my golang environement his working i event compile 0.18.0.tar.gz  without any trouble. But when i clone src from github it'does not work at all. 
 
I just open Makefile from v.0.18 and the one from Github. Both are different.

**Comment by juliusv** [comment]
(ok, works for me at least, but requires proper Go setup obviously)

**Comment by juliusv** [comment]
@aristide Do you have `$GOPATH/bin` in your `$PATH`?

**Comment by juliusv** [comment]
(that's where the `promu` tool is installed)

**Comment by aristide** [comment]
thanks!!  it's working now !!

**Comment by juliusv** [comment]
Awesome! Closing then...
