### ISSUE TITLE
Context deadline exceeded

### ISSUE THREAD

**Issue by harneksidhu** [prometheus/prometheus#1582]
I am experiencing a context deadline exceeded error for all node_exporters that are not running on the same server as Prometheus.

My Prometheus status page can be accessed here: http://es.mystorybook.com:9090/status

http://jenkins.mystorybook.com:9100/metrics seems to be working only because it is on the same machine as where Prometheus is hosted.

http://app.mystorybook.com:9100/metrics and http://db.mystorybook.com:9100/metrics are not working according to Prometheus but I can still see the metrics being provided when you hit those links. The username is 'admin' and password is '1234'.

**Comment by fabxc** [comment]
Do the logs provide anything meaningful?

**Comment by juliusv** [comment]
And can you `curl` the node exporters from the Prometheus machine? If the exporters that are not on the Prometheus machine are the only ones that are unreachable, then it sounds like a network problem between your Prometheus host and the other ones.

**Comment by harneksidhu** [comment]
@juliusv It looks like that was exactly it... Should've done more debugging before creating an issue. Thanks.
