### ISSUE TITLE
How to use the Prometheus to monitor existing projects?

### ISSUE THREAD

**Issue by guxia** [prometheus/prometheus#1584]
If I want to monitor some of the errors 、page views、
access errors、the amount online users、the amount of access failure or some other on an existing project  of java。Need i to add the corresponding code in an existing project line by line？Or how else?

**Comment by fabxc** [comment]
Essentially yes.

If the project already exports those statistics in other ways you can also write an exporter if you don't want to touch the code.

https://prometheus.io/docs/instrumenting/exporters/

**Comment by grobie** [comment]
Depending on your existing project, the https://github.com/prometheus/jmx_exporter might also be interesting here.
