### ISSUE TITLE
Metric for warnings

### ISSUE THREAD

**Issue by RichiH** [prometheus/prometheus#1586]
To catch https://github.com/prometheus/prometheus/issues/1585 and others, there should be counters for every warning and error. Optionally, having a timestamp for when a certain warning or error last happened might be useful.

**Comment by beorn7** [comment]
For the case of #1585 , there is `prometheus_local_storage_out_of_order_samples_total`. A timestamp is not really needed as you can see where the last counter increment happened.

**Comment by beorn7** [comment]
This is meant to be included for other warnings and errors in #1479 . I have updated that issue and hereby declare this one a dupe.
