### ISSUE TITLE
Prometheus stops scraping some targets

### ISSUE THREAD

**Issue by hudashot** [prometheus/prometheus#1587]
Every once in a while my Prometheus server stops scraping some targets. `/status` page still lists those, but their "Last Scrape" time is N hours ago. 

What I noticed is:
- usually a number of targets stop getting scraped around the same time;
- most targets in this state don't have any errors on `/status`, but some say "context deadline exceeded";
- it's not limited to a specific target type: some are `node_exporter`s, some are `elasticsearch_exporter`s, some are custom apps that expose metrics using text exposition format;
- I am now using 0.18.0 binaries from the Releases page, but I've seen the same behavior with 0.17 that I compiled myself.

Here's a [goroutine dump](https://gist.github.com/hudashot/74f59ead02504dc1b7a42fe591812acd). 1857 minutes ago is when some targets stopped getting scraped. It looks as if Prometheus stopped reading from a number of established connections (which I can still see open using `lsof`).

I assume this might have been caused by intermittent loss of network connectivity. I have not read the code too closely, but I would have expected `scrape_timeout` to kick in (default value is 10 seconds, right?) and abort those scrapes instead of hanging like this.

**Comment by brian-brazil** [comment]
That sounds like it could be a deadlock in the target management code. Which service discovery methods are you using?

**Comment by hudashot** [comment]
I am using `file_sd_configs` with a list of targets generated by another system as a JSON file.
Here's my [config](https://gist.github.com/hudashot/0d2c555280666bc55bbafcb30f0042e0).

**Comment by fabxc** [comment]
Target manager code was essentially 95% rewritten. If 0.17.0 shows the same behavior it must be in the small intersection.

**Comment by hudashot** [comment]
I probably need to clarify that by 0.17 I meant pre-0.18 build of `master`.
It might have already had the new code in question.

**Comment by fabxc** [comment]
@beorn7 for confirmation, that was the issue fixed via upgrade of the `ctxhttp` package?

**Comment by beorn7** [comment]
That's pretty likely.

**Comment by fabxc** [comment]
@beorn7, @hudashot did you encounter this again or can we close this?

**Comment by beorn7** [comment]
0.19.2 has been running everywhere at SoundCloud without any issues.
Since there were no further complaints from the community, I'll close this.
Please re-open if mistaken.
