### ISSUE TITLE
How does it work- storage.local.retention?

### ISSUE THREAD

**Issue by mokshpooja** [prometheus/prometheus#1589]
Hi Guys, Was looking into the code of storage.go. Wanting to understand what chain of actions happen after storage-local.retention time frame is met.
Overview would help. Thanks.

**Comment by beorn7** [comment]
On 25 April 2016 at 15:22, mokshpooja <notifications@github.com> wrote:
>
> Was looking into the code of storage.go. Wanting to understand
> what chain of actions happen after storage-local.retention time frame is met.
> Overview would help. Thanks.

Starting point is the `loop` method:
https://github.com/prometheus/prometheus/blob/master/storage/local/storage.go#L993

It goes through all series and performs a "maintenance" on them, which
includes truncating old chunks. You have to take it from there and
explore the code.

-- 
Björn Rabenstein, Engineer
http://soundcloud.com/brabenstein

SoundCloud Ltd. | Rheinsberger Str. 76/77, 10115 Berlin, Germany
Managing Director: Alexander Ljung | Incorporated in England & Wales
with Company No. 6343600 | Local Branch Office | AG Charlottenburg  |
HRB 110657B
