### ISSUE TITLE
Drop legacy API

### ISSUE THREAD

**Issue by fabxc** [prometheus/prometheus#1593]

**Comment by juliusv** [comment]
Just double-checked: PromDash does still use the legacy API, unfortunately :(

So we can fix PromDash, keep the legacy API, or remove it and say it's ok to break PromDash (probably not so nice)...

**Comment by fabxc** [comment]
Upgrading PromDash should be straightforward – mostly prefixing `v1/`.
Any Ruby volunteers?

**Comment by stuartnelson3** [comment]
Can one of you point me to an updated API doc? I'll do this ASAP and open a PR for your verification.

**Comment by fabxc** [comment]
Great!

The API v1 docs are [here](https://prometheus.io/docs/querying/api/).

**Comment by juliusv** [comment]
Note that the URL change is the least part - the request/response has completely changed. But you should be able to copy the relevant bits from the Prometheus server's JS.

**Comment by stuartnelson3** [comment]
Who was the lazy person that updated the prometheus JS but not promdash..

**Comment by fabxc** [comment]
So we can drop it? @stuartnelson3

**Comment by stuartnelson3** [comment]
Hey sitting in HBF, but promdash has been using the new API for a while. It
should be fine, but I haven't confirmed.

Am Donnerstag, 23. Juni 2016 schrieb Fabian Reinartz :

**Comment by juliusv** [comment]
Confirmed: https://github.com/prometheus/promdash/pull/484

Old API begone!

**Comment by beorn7** [comment]
See comment on https://github.com/prometheus/prometheus/pull/1761 and see the PR https://github.com/prometheus/prometheus/pull/1601

**Comment by fabxc** [comment]
Saw the PR – just wanted to be sure.
Seems we don't have versioned PromDash releases so it's fixed as soon as
it's in master?
