### ISSUE TITLE
Drop all non-generic write paths

### ISSUE THREAD

**Issue by fabxc** [prometheus/prometheus#1594]

**Comment by brian-brazil** [comment]
We might want to block this on having a generic write path. There were a small handful of users experimenting with this, I don't know if any of them made it as far as production though.

**Comment by fabxc** [comment]
Realistically generic write won't happen for 1.0.0.

Let's mark OpenTSDB and InfluxDB both as unstable/experimental/scheduled
for removal then?

**Comment by brian-brazil** [comment]
Marking them all as deprecated sounds good for 1.0.0.

**Comment by juliusv** [comment]
:+1: for marking deprecated until generic write.

**Comment by rvrignaud** [comment]
Will there be any alternative for influxdb as durable storage on 1.0 ?

**Comment by Gouthamve** [comment]
Can this be closed now?

**Comment by juliusv** [comment]
Yes, thanks!
