### ISSUE TITLE
promql: separate expression language and rule parsing

### ISSUE THREAD

**Issue by fabxc** [prometheus/prometheus#1595]
The current parser handles both as one which makes #1095 nearly impossible to implement.
They should be considered separate language. This will require newlines becoming part of the rules syntax to be handled in a sane way.

Even though everyone should be doing that, this will be breaking.

Should we consider adding newline semantics before 1.0 to not have to cut 2.0 for that?
My hunch is we won't get to it too soon and will cut 2.0 for other reaosons.

**Comment by brian-brazil** [comment]
I hear semicolons are not completely out of fashion.

If we're going to break rules files, we should probably force all rules to be in a group while we're at it.

**Comment by fabxc** [comment]
Not in favor of semicolons – but we should just vote on that.

Please react to this comment:

👍 – newline (Python/Go style)
👎 – semicolon (C style)

**Comment by juliusv** [comment]
I'd have to understand this better before trying to comment either way.

So with newlines, obviously it should still be allowed to have newlines in general in expressions (including rule RHS expressions), just not in certain positions, right? What would be exactly the rule for when a newline means the end of an expression? To get an idea of how much it would break and how confusing it would be...

**Comment by grobie** [comment]
I do have an alternative proposal. I'll prepare an overview.

**Comment by brian-brazil** [comment]
Yeah, I'd like to see what a newline proposal looks like. We don't want to end up with the oddness JS has for newlines for example.

**Comment by fabxc** [comment]
@grobie so, about that alternate proposal... :) I'm curious

**Comment by grobie** [comment]
@fabxc Oops, long time. I'll need to check my notes, but I think it's better to ignore that comment for now.

**Comment by Gouthamve** [comment]
When this happens we also need to look at #1695 Especially fabxc's points:
* easy to define PromQL tests
* easy to define PromQL benchmarks
* alerting rule unit testing for users

**Comment by brian-brazil** [comment]
Is this done now with 2.0?

**Comment by Gouthamve** [comment]
Yes, I think so.
