### ISSUE TITLE
Add command line parameters to the configuration file

### ISSUE THREAD

**Issue by jgillis01** [prometheus/prometheus#1599]
It would be nice to have the prometheus command line parameters added as options in configuration file so that these options could go into effect when the service is reloaded. For example if the alert manager comes online at a later time (or changes endpoint location), an outside process could rewrite the configuration file and HUP the service so that alerts could be pushed to the new endpoint.

**Comment by brian-brazil** [comment]
There's significant effort to making a command line option a reloadable config option, and it also ties us down quite a bit in terms of backwards compatibility in addition to making the config more complex.

The AM will likely ultimately end up in the config file, but I wouldn't expect many other flags to migrate there.

**Comment by grobie** [comment]
As mentioned a few times, retention policy would be very helpful. One of the most commonly adjusted values in order to react to a change in number of time series. Changing that value currently means a downtime of 5-10m to restart the server.

**Comment by brian-brazil** [comment]
Retention time is one of the ones I expect to stay as a flag forever, as that's touching quite a few internals and I can imagine the subsystem substantially changing in the future.

**Comment by grobie** [comment]
It'll be inevitable with per series/rule group retention times.

**Comment by brian-brazil** [comment]
I don't think we'll ever be moving all flags to the config file, so closing this off. A few things will be moved to the config file over time.

**Comment by Perlovka** [comment]
Is it possible to implement this without re-apply upon reloading?
Because configuring application options with init system isn't so handy.
