### ISSUE TITLE
Promtool: Add querying functionality

### ISSUE THREAD

**Issue by beorn7** [prometheus/prometheus#1605]
We want to replace prometheus_cli with promtool.

See also https://github.com/prometheus/prometheus_cli/issues/9

**Comment by alileza** [comment]
Does anyone working on this?

**Comment by beorn7** [comment]
I don't think so. @fabxc might know more about the current state about the API client library. See prometheus/prometheus_cli#9

**Comment by fabxc** [comment]
No one is currently working on this.
I'm happy to provide guidance to anyone willing to tackle this.

**Comment by alileza** [comment]
Nice, i guess i'll try to start working on this.

**Comment by fabxc** [comment]
Sounds great!
Be aware of the API client package:
https://godoc.org/github.com/prometheus/client_golang/api/prometheus

I've recently been thinking about kicking out the dependency on the `model`
package. But with vendoring those potential changes are not blocking.

**Comment by alileza** [comment]
Ok, so  basically we want to move `prometheus_cli` features into `promtool` using [client_golang api](https://godoc.org/github.com/prometheus/client_golang/api/prometheus)?

**Comment by alileza** [comment]
is this changes is what we expect on promtool? if it is, i'll continue to work on query_range etc and submit at PR.
https://github.com/alileza/prometheus/commit/36da400c342eb7a2ebcf6f39c5f44bed39f4ab17

**Comment by beorn7** [comment]
Sorry, dropped the ball here. Yes, this all sounds good to me. What @fabxc tried to say about the prometheus/common/model dependency is essentially "don't worry". @fabxc Please shout if there is anything else to say at this point.

**Comment by xmudrii** [comment]
What's the status of this issue?
I saw Hacktoberfest label and I want to contribute to Prometheus project for the first time.

If this is still needed things I would love to try working on it. Also if there are some instructions/guidelines I would appreciate them.

**Comment by brancz** [comment]
Not sure how far we want to go with this, but for a quickstart I threw this together a while ago, and just queried further with jq. It's not much, but it's a start https://gist.github.com/brancz/1c252d4c87a48c80df7c6b046823c466

Questions we may want to ask ourselves is, which format(s) do we want to output? Interactive? One-off?

Personally I don't think this needs any dependency on common/model, but that also somewhat depends on what we want to build here.

**Comment by si74** [comment]
Hey! I'd be interested working on this.

**Comment by krasi-georgiev** [comment]
based on the original issue this is now fixed
