### ISSUE TITLE
Switch remaining metrics to seconds

### ISSUE THREAD

**Issue by brian-brazil** [prometheus/prometheus#1606]
There's still a handful of metrics in Prometheus not using seconds, mostly around storage. We should switch them to seconds for consistency.

While it's proposed that it's okay to change this sort of thing post 1.0, it'd be best to get it in before that.

**Comment by grobie** [comment]
Some of the quantile summaries should also be histograms for aggregations.

**Comment by brian-brazil** [comment]
Most of those summaries should be just changed not to have quantiles imho.

**Comment by fabxc** [comment]
What's the benefit of removing them? They are not exactly expensive in the
Prometheus case.

**Comment by brian-brazil** [comment]
I think they're of low value and potentially confusing given the disproportionate importance that is attached to quantiles compared to their actual utility. Histhograms are also favoured, so if we really need this data (I think we can live without) we should use those.

**Comment by beorn7** [comment]
+1 for changing everything to seconds.

I find some of the quantiles extremely useful. In general, if the latency of a single host matters, no aggregation is needed, and precomputed quantiles are very handy. A Prometheus server is a good example where you are interested in the latency of a single server.

At SC, we use a number of quantiles exposed by the Prometheus server quite regularly. We can go through all the summaries and decide for each one which of the following is the right course of action:  (a) remove, (b) turn into histogram, or (c) leave it as is is.

**Comment by beorn7** [comment]
Reopening to not lose track.

**Comment by fabxc** [comment]
Metrics are not part of our stability guarantees. Holding of 1.0 for just that doesn't seem appropriate.

**Comment by beorn7** [comment]
Fine with me. So consensus is (2) then? @brian-brazil ?

**Comment by brian-brazil** [comment]
2 is what I was thinking.

**Comment by beorn7** [comment]
Cool. I'll close this again, then, because the metric change will happen implicitly with the move to the new client library.
