### ISSUE TITLE
Prometheus Basic Authentication

### ISSUE THREAD

**Issue by harneksidhu** [prometheus/prometheus#1607]
Hello,

I am trying to find some documentation on how to setup basic authentication for the Prometheus database. I was not able to find anything on Prometheus' documentation. However, I notice Grafana mentions that basic auth is possible for Prometheus  http://docs.grafana.org/datasources/prometheus/.

Is basic authentication possible and if so, where can I find the appropriate instructions in the documentation?

Thanks!

**Comment by barkerd427** [comment]
I believe this is done by putting something line nginx in front of it. I
know of no authentication within Prometheus.

**Comment by beorn7** [comment]
Answer is here: http://www.robustperception.io/adding-basic-auth-to-prometheus-with-nginx/
