### ISSUE TITLE
DNS SD: Old targets do not disappear

### ISSUE THREAD

**Issue by beorn7** [prometheus/prometheus#1610]
I have just run into an issue where targets disappear from the DNS SRV record but stick around in Prometheus. The new targets have been added, but the old ones don't disappear. I couldn't detect any hung goroutine are something, but perhaps I didn't look carefully enough.

I have the full goroutine dump if needed.

I'll report here if I see the issue happening more often. (So far this was the only incident.)

This has happened with the stock 0.18.0 binary.

@fabxc Perhaps this is related to the occasional K8s SD hiccups reported elsewhere, i.e. something in the retrieval layer might get stuck that is not specific to K8s.

**Comment by fabxc** [comment]
Goroutine dump would help, yes.

**Comment by beorn7** [comment]
Sent via personal mail.

**Comment by beorn7** [comment]
Just FTR: This happened again now. But it's definitely a rare event. Targets at SC are coming and going all the time. (Perhaps it's triggered by a special pattern, e.g. all targets are replaced in one go?)

@mweiden This is the issue I was talking about. And to be fair, we never considered it fixed.

**Comment by beorn7** [comment]
Happened again, on v0.20... Is there any difference between 1.0 and 0.20 that could affect this?

(We should release 1.1 so that I can upgrade all of SC, and then I can create goroutine dumps for the current version for easier troubleshooting.)

**Comment by matthiasr** [comment]
Replacing all the addresses in a job, without renaming the job, does the trick. [Here](https://gist.github.com/matthiasr/141e9754b7c0072c432b7fa3ae487b1a) is a script to reproduce this reliably.

**Comment by beorn7** [comment]
This sounds pretty relevant for normal operations.
@fabxc do you think you'll find time to fix this soonish? Otherwise, I'll give it a spin (distracting me from client_golang work. ;)

**Comment by beorn7** [comment]
OK, I'm working on this one now. Dropping `client_golang` work in the meantime.

**Comment by fabxc** [comment]
Thanks, lacking bandwidth for this right now.

**Comment by espenkm** [comment]
This may or may not be useful information on this: What I also see is that the scraping gets confused as it now scrape some other pod that has gotten the recycled ip from the deleted pod(s). This (also?) leads to the new pod gets scraped with the wrong labels as prometheus thinks it is the old pod.

Were on 1.0.1

**Comment by beorn7** [comment]
Bug is understood. Now I have to figure out a solution…

**Comment by fabxc** [comment]
What is the bug?

**Comment by beorn7** [comment]
See PR.
