### ISSUE TITLE
How to configure alertmanager.url into prometheus.yml

### ISSUE THREAD

**Issue by wkshare** [prometheus/prometheus#1615]
-alertmanager.url 
      The URL of the alert manager to send notifications to.

Command line to use trouble, need to restart

**Comment by brian-brazil** [comment]
The only way to do this currently is as a command line argument to Prometheus. It'll move into the config at some point in the future.

**Comment by wkshare** [comment]
thks：）@brian-brazil

**Comment by dimh** [comment]
Hi, some news about it??

**Comment by brancz** [comment]
This is available as an alpha feature: https://prometheus.io/docs/operating/configuration/#alertmanager_config

**Comment by dimh** [comment]
thank you @brancz

**Comment by gvenka008c** [comment]
@brancz Any example on how to configure alert manager within prometheus.yml instead of passing it thorugh command line flag?

```
# Alert manager configuration
alerting:
  alertmanagers:

```

**Comment by juliusv** [comment]
@gvenka008c Please ask usage questions at https://groups.google.com/forum/#!forum/prometheus-users

Also, example: https://github.com/prometheus/prometheus/blob/master/config/testdata/conf.good.yml#L213-L220
