### ISSUE TITLE
AWS: support the ~/.aws/credentials files

### ISSUE THREAD

**Issue by acdha** [prometheus/prometheus#1618]
It would be handy if Prometheus supported the shared credentials file discussed in 
https://blogs.aws.amazon.com/security/post/Tx3D6U6WSFGOK2H/A-New-and-Standardized-Way-to-Manage-Credentials-in-the-AWS-SDKs so it would be compatible with existing configs for awscli or the CloudWatch exporter.

**Comment by brian-brazil** [comment]
Is this something the AWS libraries provide? If not, it's unlikely we'll add support for it ourselves.

**Comment by grobie** [comment]
Yes, this has been added to aws-sdk-go in v1.3.0 according to their README. Our vendored client seems to be v0.9.1rc1.

**Comment by brian-brazil** [comment]
We're on v1.23.12 now.
