### ISSUE TITLE
handle remote storage openTSDB error response correctly.

### ISSUE THREAD

**Issue by guanglinlv** [prometheus/prometheus#1621]
Hi folks,

when then openTSDB return a error response with `400` status code. it looks like the following with different request:
-  `/api/put`

```
{
   "error" : {
         "code": 400,
         "details": "Please seen the TSD logs or append \"details\" to the put request",
         "message": "one or more data points had errors",
         "trace": ".........."
    }
}
```
-  `/api/put?summary`

```
{
    "failed": 1,
    "success": 1
}
```

i think the second output is what we need.  otherwise the [client.go#L127](https://github.com/prometheus/prometheus/blob/master/storage/remote/opentsdb/client.go#L127) will report a error. we should change the `putEndpoint` const to `/api/put?summary`.

more details on `/api/put`, see http://opentsdb.net/docs/build/html/api_http/put.html

thanks.

**Comment by guanglinlv** [comment]
aha, it is not need to change the `putEndpoint`, i can set the prometheus `-storage.remote.opentsdb-url=http://opentsdb-host:4242/?summary` , then opentsdb's response is 

```
HTTP/1.1 200 OK
.
{
    "failed": 0,
    "success": 100
}
```

however, [client.go#L115](https://github.com/prometheus/prometheus/blob/master/storage/remote/opentsdb/client.go#L115) compare the status code with 204.  

then, a incorrect error will report at [queue_manager.go#L194-L198](https://github.com/prometheus/prometheus/blob/master/storage/remote/queue_manager.go#L194-L198)

![incorrect](https://cloud.githubusercontent.com/assets/10666676/15169209/819f2cde-176b-11e6-9b61-e4db36073887.png)

**Comment by brian-brazil** [comment]
See also #1061

**Comment by grobie** [comment]
OpenTSDB support has been removed. Use a remote storage adapter.
