### ISSUE TITLE
fuzzer: Have it re-encode successfully parsed data

### ISSUE THREAD

**Issue by msiebuhr** [prometheus/prometheus#1626]
Dmitry suggests (in https://github.com/dvyukov/go-fuzz/issues/127#issuecomment-218102963) to expand the fuzzing by having it re-encode/stringify the decoded datastructure.

I'm not familiar with the different parses, but I imagine several of them have some re-encodable output.

Possibly check that it matches the parsed input and/or re-parse it and verify it matches the originally parsed out data structure.

**Comment by shwethabm** [comment]
Can I work on this?

**Comment by bboreham** [comment]
Discussed at bug-scrub.  The linked comment is not about re-encoding, but the comment after says it is fixed.
I'm going to close this as done; if there is work left please re-open and be specific about what it is.
