### ISSUE TITLE
"Access is denied" while dropping persistent chunks on Windows

### ISSUE THREAD

**Issue by Bounz** [prometheus/prometheus#1628]
Hi, everyone.
I have prometheus 0.18.0 installed on Windows Server 2008 R2.
After some time a lot of error messages began to appear in log file:
```time="2016-05-11T14:35:09+03:00" level=error msg="Error dropping persisted chunks: rename data\\9f\\109282fa3f2607.db.tmp data\\9f\\109282fa3f2607.db: Access is denied." source="storage.go:1258" ```

While trying to investigate what's happens I found out that it is connected with ```SetRenameInformationFile``` system call, as it can be seen on the screenshot:
![aid](https://cloud.githubusercontent.com/assets/3062744/15218049/c8faf8aa-1866-11e6-9dc4-805babdb826e.png)

Prometheus is running under local SYSTEM account and this account has full access to prometheus directory.
Has anybody faced with problem like this?

**Comment by brian-brazil** [comment]
From my vague recollections of Windows, it doesn't like deleting files that are open. I'd guess something similar is happening here.

We'll need a Windows expert here I suspect.

**Comment by beorn7** [comment]
I'll check if deletion of files happens when they are still open. Preliminarily assigning to myself for that (although I'm not a Windows expert at all...)

**Comment by Bounz** [comment]
Is it possible that prometheus doesn't close files before renaming them?

**Comment by beorn7** [comment]
Fixed by https://github.com/prometheus/prometheus/pull/1754
