### ISSUE TITLE
Improve notifier metrics

### ISSUE THREAD

**Issue by brian-brazil** [prometheus/prometheus#1630]
Per our standard guidelines `prometheus_notifications_latency_seconds` should include failed notifications and `prometheus_notifications_sent_total` should include failures.

**Comment by fabxc** [comment]
Am I missing something or is this actually fixed?
Thought it was via #1699 but was already this way before.

**Comment by brian-brazil** [comment]
Doesn't seem to be fixed.

**Comment by fabxc** [comment]
Well...  could you please point to where you think it is not?

I'm looking at this piece of code: https://github.com/prometheus/prometheus/blob/master/notifier/notifier.go#L291-L297

**Comment by brian-brazil** [comment]
Looks like I misread the code, all good.
