### ISSUE TITLE
"no data" when dividing metrics in browser

### ISSUE THREAD

**Issue by rihardsf** [prometheus/prometheus#1632]
Both metrics are scraped from cAdvisor. I am trying to calculate percentage of memory available by dividing these metrics. 

<img width="1344" alt="screen shot 2016-05-13 at 21 17 42" src="https://cloud.githubusercontent.com/assets/2463210/15257772/9850af8e-1950-11e6-93cf-f9dd0a38bd0c.png">

Is this a bug?

**Comment by brian-brazil** [comment]
This is the correct behaviour as the `id` label differs between the two sets of time series. http://www.robustperception.io/using-group_left-to-calculate-label-proportions/ should help you.

**Comment by rihardsf** [comment]
Many thanks. It makes sense. 

Just in case if anybody care, here is what gives correct result ceil(container_memory_usage_bytes{id="/"} / on (instance) machine_memory_bytes *100)
