### ISSUE TITLE
irate() cuts out metric name

### ISSUE THREAD

**Issue by RichiH** [prometheus/prometheus#1635]
Running the query below, the name of the metric is dropped from the result set:

![prom_irate_1](https://cloud.githubusercontent.com/assets/754723/15321018/31bced00-1c34-11e6-8e68-df4887e19f40.png)

So even while I have plenty of results:
![prom_irate_2](https://cloud.githubusercontent.com/assets/754723/15321017/31bbb3b8-1c34-11e6-8b7c-0ec2b5d2b048.png)

They are all accumulated into one graph:

![prom_irate_3](https://cloud.githubusercontent.com/assets/754723/15321019/31bd6d84-1c34-11e6-9671-f9977aa83a4a.png)

Which is not what I want here.

Playing with `__name__` does not help.

As an aside, selecting on `__name__` should arguably put that into my result's label set.

**Comment by RichiH** [comment]
@cron2: FYI

**Comment by brian-brazil** [comment]
This behaviour is correct, as the output of `irate()` is no longer the same metric. Almost all functions and operators remove the `__name__` for this reason.

In this case what you need to do is explicitly select the metric names you want. Using selectors without a name should only be used for debugging and development.

**Comment by RichiH** [comment]
Even if it's only for debugging and development, an option to pass `__name__` would still be useful in this context.

**Comment by RichiH** [comment]
The easy way out seems to be to add `__name__` to the label set when I run `{__name__=~".+",instance=~"foo.*"}`.

**Comment by beorn7** [comment]
Adding `__name__` is identical to adding a metric name.

Using `__name__` is really considered open heart surgery with a lot of problematic side effects. We cannot introduce features to cater for its use.

Work-around for the given case: You could create a recording rule to create a new time series where the former metric name (or parts thereof) are now in a label, and then perform your original operation on that new time series.

**Comment by RichiH** [comment]
@beorn7 Agreed, that would work. It seems quite cumbersome to do that to drill down into "that's funny, let's look at all metrics related to this", though.

To phrase it differently: Is it certain that no better workaround exists/will be implemented?

**Comment by brian-brazil** [comment]
You can use `label_replace`, but I don't see us implementing anything in this area. It's presumed that you know your metric names when writing a query.

**Comment by beorn7** [comment]
`label_replace` only works on instant vectors.

I could imagine we colud make it work on range expressions, too, which would solve the problem in this particular case.

**Comment by RichiH** [comment]
@brian-brazil While this is usually a valid assumption, diving into the data to see what's there is open-ended by its very nature. And the amount of data prometheus can ingest means that people can't be expected to know everything every other team threw in there.

@beorn7 That would be appreciated. Would this realistically happen in near time or would that be longer term?

**Comment by brian-brazil** [comment]
I don't think we'd be changing `label_replace` in that fashion, functions only take one type of argument. You can workaround via recording rules.
