### ISSUE TITLE
docker: don’t run prometheus as root

### ISSUE THREAD

**Issue by stapelberg** [prometheus/prometheus#1637]
Similar to https://github.com/prometheus/alertmanager/issues/39, I didn’t realize that prometheus itself was also running as root. Can we change that please to limit the attack surface?

**Comment by Gouthamve** [comment]
I see that #2092 takes a stab at this. Should we run it as user `prometheus` or as user `nobody`?

**Comment by Gouthamve** [comment]
Fixed in #2859
