### ISSUE TITLE
Drop legacy JSON format support

### ISSUE THREAD

**Issue by fabxc** [prometheus/prometheus#1640]
This would mostly affect the `common/expfmt` library but the feature would be visible in Prometheus.
@beorn7, so the last status was that this really only affects SC internals,  no?

In that case we should drop that baggage for 1.0.
I might recall incorrectly though and there were other uses that justified keeping it again and again.

**Comment by brian-brazil** [comment]
> I might recall incorrectly though and there were other uses that justified keeping it again and again.

I was under the impression it was only SC.

**Comment by beorn7** [comment]
Somebody was still using the old JMX exporter, but that should be gone now. Perhaps there are remnants in Ruby clients, but I don't think any of those justify blocking it. Deprecation announcement is ages ago.

**Comment by grobie** [comment]
Support for JSON format in ruby client was dropped in release 0.5.0 / 2016-01-02.

**Comment by beorn7** [comment]
So let's drop this for 0.19?

(But then we should do it really soon to not delay 0.19 any further.)

**Comment by beorn7** [comment]
Or perhaps let's make 0.19 the last release that still supports the old format, as a last deprecation warning. (Also, it allows us to release 0.19 ~now. I really want to see the recent bug fixes released as we are running into those bugs pretty frequently.)

**Comment by brian-brazil** [comment]
I'd prefer to avoid breaking changes in 1.0, but I don't feel too strongly on this one.

**Comment by grobie** [comment]
We have kept json around for so long, I don't see a need to remove it before 1.0 either.
