### ISSUE TITLE
Limit EC2 SD by tag

### ISSUE THREAD

**Issue by chbatey** [prometheus/prometheus#1642]
From what I can tell from the docs/code the EC2 service discovery finds all EC2 instances for a region. In the typical EC2 deployments I work with I only want a subset of the instances to be monitored by prometheus so I'd like to tag these instances with something like Prometheus: True or Monitored: True.

I am happy to contribute the change is it is something you'll accept.

**Comment by brian-brazil** [comment]
See https://prometheus.io/docs/operating/configuration/#ec2_sd_config

`__meta_ec2_tag_<tagkey>` contain the tags, and you can use a `keep` or `drop` action to limit based on them.

**Comment by chbatey** [comment]
thanks @brian-brazil what do you mean by a keep or limit? I don't see that in the docs.

**Comment by brian-brazil** [comment]
See http://www.robustperception.io/automatically-monitoring-ec2-instances/ for an example, and https://prometheus.io/docs/operating/configuration/#<relabel_config> for the docs.

**Comment by chbatey** [comment]
Thanks @brian-brazil

**Comment by apandey2017** [comment]
Hi @brian-brazil - how do we specify aws:cloudformation:stack-name in <tagkey>? I could overcome : by _ but not having any luck with a - replacement in stack-name.
