### ISSUE TITLE
Feature request: allow .d-style configuration files

### ISSUE THREAD

**Issue by matevarga** [prometheus/prometheus#1648]
Currently, Prometheus' configuration is stored in one single file. However, maintaining a single file is inconvenient if there are multiple, logically separate, individually deployed or maintained monitored targets.

Example: we try to use one single Prometheus instance to monitor a set of hosts and services. Let's say we have service set A and B. Set A and B consist of multiple services, all of them should be monitored by Prometheus. Now the deployment both set of services is automated, the actual host names, ports can change over time. What I want to be able to do: whenever A is deployed, a file called `A.yml` describing the monitored resources of A is placed into a directory checked by Prometheus, then the deployment script sends a SIGHUP to Prometheus. Same in case of B.

This means that Prometheus' scrape config can be updated on a per-target(-set) basis, and there is no direct coupling between monitored services.

**Comment by grobie** [comment]
This is already possible using the file service discovery: https://prometheus.io/docs/operating/configuration/#<file_sd_config>. There are some blog posts about that as well, for example https://prometheus.io/blog/2015/06/01/advanced-service-discovery/. Using file sd even removes the need to reload the config as prometheus will watch for changes to the files on its own.

**Comment by fabxc** [comment]
Please check file-based service discovery:
https://prometheus.io/docs/operating/configuration/#file_sd_config

**Comment by matevarga** [comment]
Thanks guys, this works -- I'll close the issue and sorry for the hassle.
