### ISSUE TITLE
Log HTTP server errors using common/log

### ISSUE THREAD

**Issue by grobie** [prometheus/prometheus#1651]
We currently don't set `ErrorLog` on the HTTP server, which means that critical errors are being logged using the standard logger instead of the user configurable common/log. See https://golang.org/pkg/net/http/#Server

@mrwacky42

**Comment by juliusv** [comment]
@alileza Want to give this a try as a beginner issue?

**Comment by grobie** [comment]
The only tricky part is that log.Logger isn't an interface but a struct (grrr golang). Possible implementation could use a buffer as output of the ErrorLog logger, and then read from that logger and call our log function. Given the critical context, we'll need to be sure that this doesn't introduce (too many) new failure cases.

**Comment by alileza** [comment]
@juliusv ah sure i'll working on it
