### ISSUE TITLE
Navbar is broken in Safari

### ISSUE THREAD

**Issue by hynek** [prometheus/prometheus#1659]
Since 0.19.0, both in regular Safari of OS X 10.11.5 and Safari Tech Preview, the navbar breaks as if the windows were too narrow:

![2016-05-25 at 10 00](https://cloud.githubusercontent.com/assets/41240/15532356/9f22dee6-225f-11e6-885d-8d3436f1d30d.png)

Relatedly, such a broken navbar (which I assume is intended on mobile) overlaps top content of the page.  In this case the title “Runtime Information”.

Works fine on Chrome 51.0.2704.54 beta and Firefox 45.0b6.

**Comment by guanglinlv** [comment]
+1, chrome/35

**Comment by beorn7** [comment]
Ugh… Somehow, a spurious “w” made it into `_base.html`. See https://github.com/prometheus/prometheus/pull/1661

@hynek Can you verify it fixes the problem?

If yes, we need to cut 0.19.1 ;(

Perhaps wait until tomorrow to see if other snafus like this show up...

**Comment by beorn7** [comment]
Got hold of a Mac. Verified that this is fixed indeed.

So, when to cut 0.19.1? :-/

**Comment by brian-brazil** [comment]
I'd give it a day or two. This isn't a critical issue so we can wait in case something else comes up.

**Comment by beorn7** [comment]
Funny enough, it only shows up in Safari and not in Chrome on the Mac I tried. @guanglinlv seems to have a different Chrome version.

**Comment by hynek** [comment]
Great, thanks for fixing!  Right now I’m in a whirlwind of conf&travel preparations & can’t do much to help you.

**Comment by guanglinlv** [comment]
@beorn7   :+1: :+1:  yes,my chrome version is 35 in my lab , it's a little lower.  it work fine with your fix.

thanks.

**Comment by fabxc** [comment]
FTR 0.19.1 is already cut due to another critical bug – binary and container builds in progress.
