### ISSUE TITLE
Binaries missing in the latest release

### ISSUE THREAD

**Issue by hryamzik** [prometheus/prometheus#1663]
Are you going to upload them? Do you have any ETA for this?

**Comment by grobie** [comment]
We're working on it. ETA is today.

**Comment by fabxc** [comment]
Sorry, there are numerous issues with our CircleCI since yesterday.

**Comment by hryamzik** [comment]
Never mind, I'm not in a rush with an update, just got my deployments broken as they fail to find archives in the latest release. Already updated them to work with fixed version if it's set.

**Comment by fabxc** [comment]
It eventually worked. Tarballs and Docker images are up.
