### ISSUE TITLE
[Question]How to understand prometheus_remote_storage_sedn_latency_seconds?

### ISSUE THREAD

**Issue by guanglinlv** [prometheus/prometheus#1666]
hi, i'm a little poor on the histogram and quantile slot, what's the graph means ?

![sedn_latency](https://cloud.githubusercontent.com/assets/10666676/15561323/1dbb26c4-2327-11e6-9bde-830017a930bf.png)

thanks a lot.

**Comment by grobie** [comment]
In Prometheus we usually use 100-quantiles also called percentiles. They represent the range of values in 100 equally sized groups.

In the example above the latency of all calls to the OpenTSDB remote storage is recorded in seconds. The 0.5 quantile means 50% of all calls took at most $value seconds, 0.9 means 90% of all calls took at most $value seconds, etc. So at the end of the time range you can see that 90% of all calls to OpenTSDB were not slower than 1s.

**Comment by guanglinlv** [comment]
oh, percentiles is fit for me. is it means that we don't need the statistic of sends in various time region [0.1,0.5,1,2,5]s? named like `prometheus_remote_storage_send_latency_seconds_bucket`. prometheus will do the statistic internal and calculate it to the percentiles. 

thanks @grobie .

**Comment by grobie** [comment]
The difference are summaries (quantile labels) vs. histograms (_bucket metrics). Read more about the differences here: https://prometheus.io/docs/practices/histograms/

**Comment by guanglinlv** [comment]
thanks. closing it.
