### ISSUE TITLE
Web UI: navigation bar partly hides page content

### ISSUE THREAD

**Issue by hryamzik** [prometheus/prometheus#1667]
See the screenshot:

![image](https://cloud.githubusercontent.com/assets/1643962/15571344/db95ab40-2342-11e6-82fe-aed588971e3b.png)

Safari, Mac OS. Chrome is fine.

**Comment by brian-brazil** [comment]
Dupe of #1659. Fixed in 0.19.1.

**Comment by hryamzik** [comment]
Oops, I didn't search for closed issue, my bad, sorry.
