### ISSUE TITLE
unable to access cloudformation tags using ec2_sd_config

### ISSUE THREAD

**Issue by awesomescot** [prometheus/prometheus#1671]
There are many cloudformation tags that have colons such as, aws:cloudformation:stack-name.  If I try to access that tag in prometheus with something like __meta_ec2_tag_aws:cloudformation:stack-name, I get a bad label syntax error.  It appears you don't allow colons.  Is there any way to get around this?  Do the colons get replaced with something else?

Thanks.

**Comment by brian-brazil** [comment]
The should be getting replaced with underscores.
