### ISSUE TITLE
A http based discovery service

### ISSUE THREAD

**Issue by Gouthamve** [prometheus/prometheus#1675]
Hi,

Would you like to include a http based discovery service where we send straightforward requests to a external service at regular intervals to get the targets info. 

This would make it easier to implement custom SD mechanism (my feeling) and would be decoupling the prometheus instance from the SD mechanism allowing for all prometheus servers to use only one service for SD. It will be trivial to deploy this service in a HA configuration compared to a daemon on the same server as prometheus.

**Comment by brian-brazil** [comment]
The `file_sd` mechanism covers this via files on disk. In such a setup running one per Prometheus server would be preferable to some form of HA setup, as it has similar failure characteristics but is much simpler.

**Comment by Gouthamve** [comment]
Hmm.

But then again, take the case of the EC2 tags API. We need to access a throttled resource. We are going to run module based monitoring system with each team more or less having a prometheus server monitoring it.

We will have too many requests to the API, so we cache the tags at one service and then the `file_sd` based service will be requesting from the service and updating the files. I was hoping to write a generic `http_sd` service which would make the daemon redundant. I also think its easier to write http endpoints than managing files :). 

But any general reservations against the `http_sd` idea (architecture wise)?

**Comment by brian-brazil** [comment]
It requires a daemon, whereas files don't. We already support this functionality so I don't see a need for another one of these, especially as curl in a cronjob converts from one to the other.

**Comment by Gouthamve** [comment]
+1 to curl in a cronjob!

Thanks
