### ISSUE TITLE
Empty `group_left`/`group_right` isn't working in rules

### ISSUE THREAD

**Issue by beorn7** [prometheus/prometheus#1676]
I still have to understand why, but a `group_left` or `group_right` clause without any labels creates an evaluation error if in a rule:

```
WARN[0173] Error while evaluating rule "fake_rule{} = (chef_client_errors_count > 0) * ON(instance) GROUP_RIGHT() alerting_contact\n": parse error at char 59: unexpected ")" in grouping opts, expected identifier  source=manager.go:265
```

It appears the parser is adding an empty `()` at some point, which is then invalid syntax.

(In different news, `group_right()` should probably be legal and equivalent to `group_right`.)

@brian-brazil @fabxc

**Comment by brian-brazil** [comment]
This is another outcome of alert rules parsing the string version of the rules.

I plan on making an empty list of labels valid, but there's a new feature I want to go with it (see #1597).

**Comment by beorn7** [comment]
So we need to fix the stringification of a PromQL expression.

Work around for now is to use `group_left(dummy)`...
