### ISSUE TITLE
Prometheus text parser barfs on UTF-8 BOMs

### ISSUE THREAD

**Issue by christianlavoie** [prometheus/prometheus#1679]
UTF-8 BOMs at the beginning of a text format string confuse the text parser (prometheus will complain about an invalid metric name). Tested with 1.9.1.

**Comment by beorn7** [comment]
Yeah, that's kind of expected. The text format is fully specified and doesn't include BOMs.
Understanding BOMs would imply Prometheus could act according to whatever the BOM specifies. But it can only understand the one text format specified in https://prometheus.io/docs/instrumenting/exposition_formats/ .

What would be the rationale for supporting BOMs?

(BTW: The code that handles this is in prometheus/common, so we should arguable move this issue over there. But let's see what comes out of it...)

**Comment by juliusv** [comment]
To be honest, I didn't know about BOMs yet, but research turned up:

"A protocol SHOULD forbid use of U+FEFF as a signature for those textual protocol elements that the protocol mandates to be always UTF-8, the signature function being totally useless in those cases."

(https://tools.ietf.org/html/rfc3629)

**Comment by grobie** [comment]
Lucky you @juliusv. I can remember dark times with PHP, Windows and UTF-8
... I didn't know they're still being used.

**Comment by christianlavoie** [comment]
As far as I can tell, most "modern" Windows tools require them.

**Comment by beorn7** [comment]
We have a number of issues around the exposition format by now. How about moving them all into the docs repo, with a dedicated label? We should have clarity on the spec before starting any work, and the spec lives in the docs repo. So it might be the best point to track those issues.

**Comment by beorn7** [comment]
Moved to https://github.com/prometheus/docs/issues/542
