### ISSUE TITLE
Develop suite of standard Prometheus benchmarks

### ISSUE THREAD

**Issue by juliusv** [prometheus/prometheus#168]
We should develop and maintain a suite of easy-to-run Prometheus benchmarks that make it easy for us to compare the performance of different Prometheus versions and configurations.

Possible variables to vary in the benchmark:
- value of GOMAXPROCS
- general fulness of metrics database
- number of timeseries
- number of samples per timeseries
- ratio of samples in memory vs. disk
- query resolutions
- parallelism of queries
- Prometheus version

What to benchmark:
- point / range query times
- scraping / decoding / appending samples times

**Comment by brian-brazil** [comment]
http://prometheus.io/docs/introduction/faq/#why-does-prometheus-use-a-custom-storage-backend-rather-than-%5Bsome-other-storage-method%5D?-isn't-the-%22one-file-per-time-series%22-approach-killing-performance? answers this I'd say

**Comment by beorn7** [comment]
Not quite. Those benchmarks were executed "manually", by running a Prometheus server hotter and hotter until it broke. It hardly qualifies as "easy-to-run". There is https://github.com/prometheus/prometheus/blob/master/storage/local/storage_test.go#L711-L721 , which covers quite a lot in the storage layer, but has no knobs to turn and is not very specific.

**Comment by brian-brazil** [comment]
Can we close this now with prombench?

**Comment by fabxc** [comment]
Well, it could be better but all future issues should probably filed there.

**Comment by Gouthamve** [comment]
Hmm, I don't think so. We still don't have something to evaluate against. I mean, do we have a clear system to recognise regressions?

**Comment by fabxc** [comment]
Yes, there's stuff missing. But I think we should close here and file them in prombench.

**Comment by brian-brazil** [comment]
I agree with Fabian.

**Comment by juliusv** [comment]
+1
