### ISSUE TITLE
[v0.19.1]K8S SD failing if the cluster is in OpenStack

### ISSUE THREAD

**Issue by Krylon360** [prometheus/prometheus#1680]
OpenStack utilizes 2 IP Addresses. A Private (Management IP) and a Public (Floating) IP.
with 0.19.1; Prometheus is only detecting the Private IP; thus it fails it's probe when hitting the Node Port and cAdvisor port.

![screen shot 2016-05-27 at 11 47 20 am](https://cloud.githubusercontent.com/assets/320206/15618031/199916f4-2409-11e6-88b2-4f07e5d41bfe.png)

If I hit that same path using the Public (FloatingIP) that's tied to that endpoint; the /metrics page pulls up just fine.

So; is this a Prometheus issue? or a Kubernetes issue?
I'm going through both repos to see where the problem might be coming from.
This worked fine using the 0.19.0 container; started failing with 0.19.1.

**Comment by fabxc** [comment]
Can you paste your configuration. In general for service-endpoint discovery in k8s nothing should have changed from 0.18.0. Even less so from 0.19.0 – see the diff between 0.19.0 and 0.19.1 [here](https://github.com/prometheus/prometheus/compare/0.19.0...0.19.1)

**Comment by matthiasr** [comment]
In general, I would expect Prometheus to be on the management place and not
use public IPs. Are you running Prometheus inside the cluster or outside?
What is the case for accessing public IPs?

I'm also curious about the "no route to host" message – since Prometheus
doesn't control the routing I don't see how this can have changed.

Finally, in 0.19.0 we added pod discovery and the SD puts out everything,
are you possibly not filtering on the `_ _meta_kubernetes_role` in the
relabelling configuration?

**Comment by Krylon360** [comment]
With OpenStack Networking; the IP isn't public perse ex: `8.8.8.8`.
the Private IP is the management Network (Intercluster Communication).
a separate network is configured for External/Public addressing (Intra-Cluster Networking). 
A Port bind is then created that maps the Private IP to the Public IP.
SSH / all other services the use the network use the public ip.

I'm pretty sure our config could use an update... I'll snip just the kubernetes section. We are running Prometheus, Blackbox-Exporter, Node-Exporter, Stats-D Exporter, AlertManager, and Grafana outside of the Kubernetes Cluster on a dedicated server; hence the BearerToken setting being flagged.

if the Git-Markdown jacks the formatting on the config below; here is a gist of the same config.
[prometheus.yaml] (https://gist.github.com/Krylon360/0a23649bb3a08375e5c664762a77f2c1)

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'service-kubernetes'

    tls_config:
      insecure_skip_verify: true
    bearer_token_file: /bearer_token

    kubernetes_sd_configs:
    - api_servers:
      - ${API_SERVER}
      in_cluster: false
      tls_config:
        insecure_skip_verify: true
      bearer_token_file: /bearer_token

    relabel_configs:
    - source_labels: [__meta_kubernetes_role]
      action: keep
      regex: (?:apiserver|node)
    - action: labelmap
      regex: __meta_kubernetes_node_label_(.+)
      replacement: '$1'
    - source_labels: [__meta_kubernetes_role]
      regex: '(.*)'
      target_label: kubernetes_role
      replacement: '$1'

  - job_name: 'node'

    tls_config:
      insecure_skip_verify: true
    bearer_token_file: /bearer_token

    kubernetes_sd_configs:
    - api_servers:
      - ${API_SERVER}
      in_cluster: false
      tls_config:
        insecure_skip_verify: true
      bearer_token_file: /bearer_token

    relabel_configs:
    - source_labels: [__meta_kubernetes_role, __meta_kubernetes_service_name]
      action: keep
      regex: endpoint;nodeexporter

  - job_name: 'kubernetes-service-endpoints'

    tls_config:
      insecure_skip_verify: true
    bearer_token_file: /bearer_token

    kubernetes_sd_configs:
    - api_servers:
      - ${API_SERVER}
      in_cluster: false
      tls_config:
        insecure_skip_verify: true
      bearer_token_file: /bearer_token

    # TODO add additional relabeling
    relabel_configs:
    - source_labels: [__meta_kubernetes_role, __meta_kubernetes_service_annotation_prometheus_io_scrape]
      action: keep
      regex: endpoint;true
    - source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_port]
      target_label: __address__
      regex: (.+)(?::\d+);(\d+)
      replacement: $1:$2

**Comment by jimmidyson** [comment]
[Here](https://github.com/prometheus/prometheus/blob/master/retrieval/discovery/kubernetes/discovery.go#L781-L803) is where I think this is having the problem. This currently uses the internal node IP if available, which shows that it expects Prometheus to be run in-cluster. Not sure of the best fix for this: make it configurable in SD or emit a target for each node IP & filter by relabelling?

**Comment by brian-brazil** [comment]
The additional IPs should be available as labels for relabelling.

**Comment by jimmidyson** [comment]
Ah OK so single target with labels for each node IP - great idea.

**Comment by jimmidyson** [comment]
#1712 makes all node IPs available from Kubernetes API server available for relabelling from meta labels `__meta_kubernetes_node_address_<type>` so you should be able to use `__meta_kubernetes_node_address_external_ip` in your relabel config. It still defaults to using internal IP.

**Comment by jimmidyson** [comment]
Just an update: after review meta label will be `meta_kubernetes_node_address_ExternalIP` rather than what I said above.

**Comment by Krylon360** [comment]
Awesome! Thanks everyone for the quick turnaround!

Bryce Walter
