### ISSUE TITLE
DNS resolution happens only on startup

### ISSUE THREAD

**Issue by alon-argus** [prometheus/prometheus#1683]
Hi again everyone.

I use a DNS service for my services (specifically Mesos-DNS, but it can be Consul or any other), therefore I use Prometheus' `dns_sd_configs` configuration option to give my services addresses 

The problem is:  
Prometheus resolves the SRV DNS addresses only on its startup ,so if Prometheus starts before the DNS server, it won't show all of these Targets. They won't even appear as "Down", but they'll just never appear until I'll restart Prometheus.

Version: 0.18.0

**Comment by matthiasr** [comment]
Can you try starting DNS first? We use DNS SD a lot and don't hit this. The
only difference I see is DNS being unavailable at startup, so the bug might
be triggered by that condition. What I would expect in that case is that
subsequent updates properly reflected.

**Comment by alon-argus** [comment]
It happens only when I start DNS after Prometheus. 
Anyway, I'm trying to reproduce now with the latest version 0.19.1

**Comment by alon-argus** [comment]
OK, it seems like it doesn't reproduce with 0.19.1. Please close the issue and I'll report if it happens again. Thanks a lot!

**Comment by alon-argus** [comment]
OK, it seems like it doesn't reproduce with 0.19.1. I'm closing the issue and I'll report if it happens again. Thanks!
