### ISSUE TITLE
Labels Query

### ISSUE THREAD

**Issue by Rucknar** [prometheus/prometheus#1689]
*Aim* - I wish to be able to query for host metrics based upon a server's role easily.

*Challenge* - I’m doing this within a container orchestration platform that supports DNS service discovery. I’m using this platform to schedule the running of our node-exporter globally. Prometheus then retrieves the list of node-exporters through DNS service discovery. This works well and our results are filterable on ‘instance’ (IP/Port). 

*What i’ve tried*
I’ve tried Adding a textile collector to node-exporter, can now see ‘role’ metric returned, i figured once my data is all in the same place, it should be easy... But I couldn’t see a way of manipulating this returned data into something i could use in other metrics. I attempted relabel configs to try map the values but i don’t think it's possible to re-map a metric result to a label like that?

I think the usual way here is to split up the jobs so that each group has a label, that’s not something i can easily do here, there isn't a config management platform behind this deployment. I guess fundamentally i shouldn't need one as all the data is there, I can obtain the servers role within a container, how can i easily either replace an existing label with this data, or add a new label from it?

Think i’ve just gotten confused with labels in general, apologies if this is covered, i have searched around a lot. 

Any help appreciated,

Thanks

Ed

**Comment by brian-brazil** [comment]
It sounds like you're looking for http://www.robustperception.io/how-to-have-labels-for-machine-roles/

**Comment by Rucknar** [comment]
I do indeed, thanks for the heads up @brian-brazil
