### ISSUE TITLE
Could not use kubernetes-pods job

### ISSUE THREAD

**Issue by rvrignaud** [prometheus/prometheus#1693]
I'm using prometheus 0.19.2 in a Google Container Cluster (GKE) (Kubernetes 1.2.4).
'kubernetes-service-endpoints' discovery is working fine.
I'm trying to use 'kubernetes-pods' job but I don't get any target discovered.

My prometheus job definition is a copy/paste of 'kubernetes-pods' as defined in https://github.com/prometheus/prometheus/blob/master/documentation/examples/prometheus-kubernetes.yml 

I have a deployment object defined with:
```
{
  "apiVersion": "extensions/v1beta1",
  "kind": "Deployment",
  "metadata": {
    "name": "telegraf",
    "namespace": "prd"
  },
  "spec": {
    "replicas": 1,
    "template": {
      "metadata": {
        "labels": {
          "name": "telegraf"
        },
        "annotations": {
          "prometheus.io/scrape": "true",
          "prometheus.io/port": "9126"
        }
      },
      "spec": {
        "containers": [
          {
            "name": "telegraf",
            "image": "xxx",
            "resources": {
              "limits": {
                "memory": "100Mi",
                "cpu": "10m"
              }
            },
            "livenessProbe": {
              "httpGet": {
                "path": "/metrics",
                "port": 9126
              },
              "initialDelaySeconds": 30
            },
            "readinessProbe": {
              "httpGet": {
                "path": "/metrics",
                "port": 9126
              }
            },
            "env": [
             ....
            ]
          }
        ]
      }
    }
  }
}
```

I have pods scheduled and running. But no target is discovered. I'm not sure how to debug this.
I see nothing in prometheus logs relevant. 

Am I doing anything wrong ?

**Comment by matthiasr** [comment]
I'm not 100% sure but I _think_ you need to declare named ports in your pod spec. At least port 9126 – so just adding `"ports: { "name": "telemetry", "containerPort": 9126 }` should do.

**Comment by rvrignaud** [comment]
@matthiasr : thanks that fixed the problem. this may need to be specified in documentation ?
(ports must be an array not a map though)

**Comment by matthiasr** [comment]
Indeed! I filed prometheus/docs#455 for that.

**Comment by pdbogen** [comment]
FWIW, the issue here is not the name aspect, but that the port appears to not be declared at all.
