### ISSUE TITLE
Transient, one-off labels?

### ISSUE THREAD

**Issue by atombender** [prometheus/prometheus#1696]
I’d like to generate alerts for PostgreSQL statements that have been running for more than N minutes and are probably stuck due to locking or some I/O issue. The only way to report _specific_ queries would be if the entire SQL statement was a label (e.g. `postgres_query_time_total{sql="select * from foo"} 9204881`), otherwise an alert would be completely opaque until the developer or person on duty can consult the table of running statements.

Does Prometheus handle this use case well, or is it a bad idea to generate so many transient labels?

**Comment by matthiasr** [comment]
The MySQL exporter kind of does this based on MySQLs summary tables. It uses a _sanitized_ query as label value, so the set of queries remains bounded.

If you generate a new label for every query with every parameter, Prometheus will blow up very fast.

**Comment by brian-brazil** [comment]
Prometheus could alert that a query has been running too long, but it's not going to be able to tell you which one. Combining with a logging tool is the best approach.
