### ISSUE TITLE
web.console.templates is not overridden by passed argument

### ISSUE THREAD

**Issue by anioool** [prometheus/prometheus#1700]
Hi,

I planed to add node extractor and use the default templates for that. I tried to call the template but  I am receiving the same error - files don't exist. I checked the command line flags and I found that flag web.console.templates contains default value instead of value which i passed in command line.

I am executing prometheus by using following commad:
`          /bin/prometheus -config.file=/etc/prometheus/prometheus.yml \
                 -storage.local.path=/prometheus \
                 -alertmanager.url=http://localhost:9093 \
                 -web.console.libraries=/etc/prometheus/console_libraries \
                 -web.console.templates=/etc/prometheus/consoles \
                 -logtostderr 
`
Tested with versions : 0.18.0 and 0.19.2

**Comment by brian-brazil** [comment]
This is working correctly for me on 0.18.0 and 0.19.2. Are you sure you're talking to the Prometheus you think you're talking to?

**Comment by anioool** [comment]
Strange... I am using the docker and deployments scripts for kubernetes cluster. For web.console.libraries flag I do not have any problems.

Dockerfile
`FROM prom/prometheus

COPY prometheus.yaml /etc/prometheus/prometheus.yml
COPY alerts_config /etc/prometheus/alerts_config

VOLUME [ "/prometheus" ]
WORKDIR /prometheus


EXPOSE 9090
CMD ["/bin/prometheus", "-config.file=/etc/prometheus/prometheus.yml", "-storage.local.path=/prometheus", "-logtostderr", "-web.console.libraries=/etc/prometheus/console_libraries", "-web.console.templates=/etc/prometheus/consoles"  ]
`

Container 
`      - name: prometheus-init
        image: registry.xxx/prometheus:1.2.0
        command:
          - /bin/sh
          - -c
          - |
            while [ ! -f /data/lock/alertmanager.lock ]
            do
                echo 'Alertmanager is still not up and running. Sleep 10 seconds...'
                sleep 10
            done
            echo 'Trying to launch prometheus app...' &&
            /bin/prometheus -config.file=/etc/prometheus/prometheus.yml \
                 -storage.local.path=/prometheus \
                 -alertmanager.url=http://localhost:9093 \
                 -web.console.libraries=/etc/prometheus/console_libraries \
                 -web.console.templates=/etc/prometheus/consoles \
                 -logtostderr
        volumeMounts:
          - name: prometheus-data
            mountPath: /data/lock
      imagePullSecrets:
      - name: registry.xxx.com
`

**Comment by anioool** [comment]
Hi,

Maybe it will sound stupid by changed the order of passed parameters and after that web.console.templates flag has been overridden.

Sorry for raising not necessary ticket.
