### ISSUE TITLE
Rename `target_groups` to `static_configs`

### ISSUE THREAD

**Issue by fabxc** [prometheus/prometheus#1706]
Our SD configurations are consistently suffixed with `_configs` and descriptive of what they do. `target_groups` seems out of order.
I'd suggest renaming it to `static_configs` as we have a break to configuration with the recent changes in file SD configs anyway.

**Comment by brian-brazil** [comment]
That's going to be a painful one, but I think it makes sense. We might want to do it gracefully.

**Comment by grobie** [comment]
+1 for the consolidation. Following our discussion of the alert syntax
changes, I think this should be done in 3 release steps.

1. Introduce new naming, still accept old naming, print a descriptive
warning.
2. Remove old naming, print a descriptive error message explaining what to
change.
3. Remove error handling of old naming.

**Comment by fabxc** [comment]
Fixed via #1716
