### ISSUE TITLE
rule_type: recording and alerting examples

### ISSUE THREAD

**Issue by hryamzik** [prometheus/prometheus#1709]
I've found a label called ```rule_type``` in the [test data](https://github.com/prometheus/common/blob/master/expfmt/testdata/text#L288). It seems to be related to some label-based recording and alerting configuration but I can't figure out how could it look. Can you give me an example, please?

**Comment by brian-brazil** [comment]
That about normal recording rules vs alerting rules.

**Comment by hryamzik** [comment]
But metrics is the same, what's the reason for this?

**Comment by brian-brazil** [comment]
Recording rules and alerting rules are pretty similar, one results in time series the other in alerts.

**Comment by hryamzik** [comment]
I don't get it, if result is similar why do you use two metrics?

**Comment by brian-brazil** [comment]
The extra dimension helps you determine what is causing the problem you're looking into.

**Comment by hryamzik** [comment]
Good, thanks!
