### ISSUE TITLE
Marathon SD assumes all applications have a port.

### ISSUE THREAD

**Issue by bellmounte** [prometheus/prometheus#1711]
The following line is throwing a panic:
https://github.com/prometheus/prometheus/blob/b5bfb502df63e97d421264898d0417fb31287bef/retrieval/discovery/marathon/marathon.go#L229

This is because `task.Ports[0]` assumes a length greater than 0,  but the marathon configuration for the app is as follows:
```
  "portDefinitions": [
  ],
```

There appears to be a bad assumption that all apps will have ports.

The app that is causing this error is marathon-lb.

The work around is to add a random port definition, but this isn't ideal.

**Comment by fabxc** [comment]
This is fixed in https://github.com/prometheus/prometheus/releases/tag/0.19.3
