### ISSUE TITLE
Support scientific notation for numeric values in expression language

### ISSUE THREAD

**Issue by juliusv** [prometheus/prometheus#173]
This would make expressing certain values easier.

**Comment by juliusv** [comment]
This should probably also support `NaN`, `+Inf`, `-Inf`.

Probably we can just use http://golang.org/pkg/strconv/#ParseFloat

**Comment by beorn7** [comment]
Is this fixed with the new parser? @fabxc

**Comment by fabxc** [comment]
Yes.
