### ISSUE TITLE
Alerts should be relabelable

### ISSUE THREAD

**Issue by brian-brazil** [prometheus/prometheus#1744]
Before sending alerts out you should have a chance to relabel them. Use cases include having a different external label on a HA pair that you want to strip so that the alertmanager will de-dupe them, and having alerts that are only used as part of `ALERTS` for other alerts and shouldn't be sent to the alertmanager.

Only labels would be relabelable, not annotations. `ALERTS` is not affected.

**Comment by aecolley** [comment]
What labels can prevent an alert from being sent to alertmanagers? I traced the path back from notifier's POST to sendAlerts in rules/manager.go but didn't find any label-related filtering.

**Comment by brian-brazil** [comment]
This issue is about implementing such support.

**Comment by brancz** [comment]
@brian-brazil is this not fixed with #1878 ? If not can you elaborate?

**Comment by brian-brazil** [comment]
Relabelling should be after external labels, not before.

**Comment by brancz** [comment]
Ok that makes sense. If I understand correctly, we just need to move [this](https://github.com/prometheus/prometheus/blob/42c05dd3a2e847b5329470a6a0d380b09cf3ca13/notifier/notifier.go#L270-L277) before [relabelling](https://github.com/prometheus/prometheus/blob/42c05dd3a2e847b5329470a6a0d380b09cf3ca13/notifier/notifier.go#L214)?

**Comment by brian-brazil** [comment]
Yes

**Comment by brancz** [comment]
PR on it's way
