### ISSUE TITLE
[Feature Request] Put full Git commit id in prometheus_build_info's revision label

### ISSUE THREAD

**Issue by RichiH** [prometheus/prometheus#1748]
As per subject; the extra storage is neglible and as humans don't need to type the string, it's better to use longform.

**Comment by juliusv** [comment]
Does this have any real advantages? I can only see how it would make things like dashboards showing this information require more space.

**Comment by RichiH** [comment]
Arguably, the UI should take care of UI considerations.

The backend should be as explicit as possible.

**Comment by juliusv** [comment]
Fine with me.

**Comment by vic3lord** [comment]
This is something that needs to be changed on prometheus/promu and not here, am I wrong?

**Comment by sdurrheimer** [comment]
`promu` is involved in this change yes, but we also might need to do changes in `prometheus/common/version` depending of the way of implementing it.

**Comment by vic3lord** [comment]
Let me know if I can do anything to help, really love this project I'd love to spend sometime on it even though it's a small thing

**Comment by sdurrheimer** [comment]
We can change the `Revision` prop [here](https://github.com/prometheus/promu/blob/master/cmd/info.go#L61) to store the full git revision.
But then we might need to change commandline outputs of the `prometheus/common/version` package [here](https://github.com/prometheus/common/blob/master/version/info.go#L55) and [here](https://github.com/prometheus/common/blob/master/version/info.go#L83) to display only the short version. I don't how the commandline output would look like with a full git revision.

**Comment by vic3lord** [comment]
We can add short-revision property and use both each when its needed

**Comment by sdurrheimer** [comment]
I don't think we need to add a prop to store a semi-duplicated data. We can computes it, since a short-revision corresponds to the first seven characters.

**Comment by vic3lord** [comment]
Great so just [:8] is enough

**Comment by grobie** [comment]
Nitpick, but `git rev-parse --short HEAD` is not guaranteed to return seven characters. That's the default minimum value of the --short flag, but in general git will return the shortest unambigious sha1 prefix. In theory these could also be more than 7 characters at some point.

**Comment by RichiH** [comment]
And if it prints seven today, it might print ten tomorrow. That is part of
why I would use longform for all the things.

Richard

Sent by mobile; excuse my brevity.

**Comment by fabxc** [comment]
:+1: on using the full one. When selecting along that dimension we are still free to do `=~abcdef12.*`.

**Comment by sdurrheimer** [comment]
PR open on Promu's repo to make the change.
