### ISSUE TITLE
Import historical metrics

### ISSUE THREAD

**Issue by Stef3478** [prometheus/prometheus#1750]
Hi,

I would like to import historical metrics in a bulk. 
I configured a new exporter which stores run-times of certain batches. And I would like to store (back load) these metrics from the past few years as well to see the trends (in Grafana).
I read that in the past this was possible with the import api but not anymore (there's an open issue for this I think: issue 535). Is there another way to do this, like the "hacky" way of doing this as mentioned in issue 535?

Thanks,
Stef

**Comment by beorn7** [comment]
The issue is https://github.com/prometheus/prometheus/issues/535

And no, there never was an import API.
