### ISSUE TITLE
Disk throughput in node console

### ISSUE THREAD

**Issue by hryamzik** [prometheus/prometheus#1751]
Shows speed in bytes [counted as](https://github.com/prometheus/prometheus/blob/master/consoles/node-disk.html#L14) ```node_disk_sectors_read * 512``` but sector size could be different. Looks like  ```node_disk_bytes_read``` should be used instead.

**Comment by brian-brazil** [comment]
The sector size is always 512 for that variable, and that's how node_disk_bytes_read is calculated.

**Comment by hryamzik** [comment]
So if I have 4 KB  sectors I'll have to multiply by 8?

**Comment by brian-brazil** [comment]
It'll multiply by 512, and produce the correct value.

**Comment by hryamzik** [comment]
So does this mean that for a 4 KB blocks device node_exporter will report each block as 8 ones?

**Comment by brian-brazil** [comment]
Yes, that's what the kernel does.

**Comment by hryamzik** [comment]
Got it, thank you!
