### ISSUE TITLE
Introduce metric for per-exporter pressure on prometheus itself

### ISSUE THREAD

**Issue by harmw** [prometheus/prometheus#1755]
Is it possible to expose some kind of metric to point out the amount of _stress_ a certain metrics endpoint poses on the prometheus machine itself? We have several exporters in our platform, just no simple way of figuring out which one of those is stressing prometheus the most. Some more insights in this process would be great.

**Comment by brian-brazil** [comment]
What you're mostly looking for is the number of samples that an exporter is producing. Usually it's just a handful of metrics in one exporter. http://www.robustperception.io/which-are-my-biggest-metrics/

**Comment by fabxc** [comment]
You can also do something along the lines of:

`count by(instance) ({__name__=~".+"})`

That can be expensive though.

**Comment by harmw** [comment]
Thanks, that looks useful.

However:
```
Error executing query: query timed out in expression evaluation
```

I'll see if I can do _something_ to get the information out of prom.

**Comment by brian-brazil** [comment]
`scrape_samples_scraped` does this now.
