### ISSUE TITLE
Uninstall Prometheus

### ISSUE THREAD

**Issue by dwalst** [prometheus/prometheus#1756]
**What did you do?**
Hello, I installed and configured Prometheus and want to uninstall and reinstall it.  Can you tell me how to completely uninstall Prometheus?
I have it installed on RHEL 7

**Comment by Gouthamve** [comment]
Hi,
It would help if you told how you installed it. In most cases it would be deleting a couple of files (binaries/config).

**Comment by dwalst** [comment]
tar xvfz prometheus-*.tar.gz
cd prometheus-*
./prometheus -config.file=prometheus.yml

**Comment by Gouthamve** [comment]
Uninstalling is as simple as  `rm -rf prometheus-*`   :)

Its a single binary so there are no dependencies that are installed anywhere.

**Comment by dwalst** [comment]
Wonderful, awesome, and sweet!!!  Thank you very much and have a great day/evening :)

**Comment by dwalst** [comment]
Ok, I was a little premature, as that didn't work, see below:


prometheus-0.19.2.linux-amd64]# rm -rf prometheus-*

prometheus-0.19.2.linux-amd64]# ./prometheus -config.file=prometheus.yml

INFO[0000] Starting prometheus (version=0.19.2, branch=master, revision=23ca13c)  source=main.go:73
INFO[0000] Build context (go=go1.6.2, user=root@134dc6bbc274, date=20160529-18:58:00)  source=main.go:74
INFO[0000] Loading configuration file prometheus.yml     source=main.go:206
INFO[0000] Loading series map and head chunks...         source=storage.go:340
INFO[0000] 438 series loaded.                            source=storage.go:345
INFO[0000] Starting target manager...                    source=targetmanager.go:74
WARN[0000] No AlertManager configured, not dispatching any alerts  source=notifier.go:165
INFO[0000] Listening on :9090                            source=web.go:241

I CAN STILL FETCH AND VIEW THE CONSOLE AND GRAPH STATISTICES AS WELL.
Do I also need to delete all Prometheus filesystems and related files?

**Comment by Gouthamve** [comment]
`prometheus-0.19.2.linux-amd64]# rm -rf prometheus-*`

You were trying to delete the folder from inside. `cd ..` and then do it.

If you only want to clear the data stored, do `rm -rf data/` from the current folder (from where you ran ./prometheus) and rerun it.
