### ISSUE TITLE
promtool: print file/line locations for warnings/errors

### ISSUE THREAD

**Issue by juergenhoetzel** [prometheus/prometheus#1758]
Checking my config I get warnings, but not the file-name + line-number which cause the warnings/errors:

```
→ ./promtool  check-config /srv/prometheus/prometheus.yml
Checking /srv/prometheus/prometheus.yml
WARN[0000] The 'target_groups' option for scrape configurations is deprecated, use 'static_configs' instead  source=config.go:468
WARN[0000] The 'target_groups' option for scrape configurations is deprecated, use 'static_configs' instead  source=config.go:468
WARN[0000] The 'target_groups' option for scrape configurations is deprecated, use 'static_configs' instead  source=config.go:468
  SUCCESS: 1 rule files found
```

These additional info could also improve editor support. I use Emacs and implementing a 
[Flycheck](https://github.com/flycheck/flycheck) checker should be easy when this info is provided.

**Comment by fabxc** [comment]
I agree that it would be handy but with the YAML parsing package we are using this is hardly doable.

**Comment by serathius** [comment]
I created issue for yaml package https://github.com/go-yaml/yaml/issues/343
