### ISSUE TITLE
vendor: Update vendored goleveldb, and check if other dependencies should be updated, too

### ISSUE THREAD

**Issue by beorn7** [prometheus/prometheus#1768]
Before we release 1.0.0, we should get our vendored dependencies up-to-date and give them a test run.
In particular, goleveldb has some fixes and performance improvements upstream.

**Comment by fabxc** [comment]
Any particular reason why?
I don't see too much urgency here. We should check whether there are security or bug fixes affecting our code path but in general this is always has potential for regressions.

**Comment by beorn7** [comment]
I did check. That made me file this issue. And that's what I tried to express by "goleveldb has some fixes and performance improvements upstream".
Obviously, we should canary the changes, but given that we have performance problems with the indexes, I think it's worth it. I cannot really judge the actual impact of the bug fixes, as we had very few incidents reported that might have been triggered by goleveldb bugs. But the commit descriptions sounded pretty relevant to me, so I wouldn't like to release a 1.0.0 software with know bugs that are even known to be fixed upstream.

**Comment by beorn7** [comment]
I see. Then I have to apologize for my lack of clarity. It really sounds in the OP as if I want to do a blanket update of everything. What I should have said: Let's do goleveldb in any case, and while we are on it, let's check the other dependencies if there is a reason to update. I'll change the title accordingly.

**Comment by fabxc** [comment]
Closed via #1785
