### ISSUE TITLE
Refactor `aggregation` in engine.go

### ISSUE THREAD

**Issue by brian-brazil** [prometheus/prometheus#1789]
This function is getting complicated, some cleanup would be good.

**Comment by serathius** [comment]
Is it ok for me to take it?
I will prepare some tests before refactoring.

**Comment by brian-brazil** [comment]
I'm in the middle of redoing large portions of PromQL, so I'd hold off. We already have pretty good tests for PromQL.

**Comment by krasi-georgiev** [comment]
@brian-brazil was this done in the promql refactoring?

**Comment by brian-brazil** [comment]
No, I didn't change this.

**Comment by brian-brazil** [comment]
It's not obvious to me that we can really improve this, so closing off for now.
