### ISSUE TITLE
`target_group` should be called `static_config` in error messages

### ISSUE THREAD

**Issue by cherti** [prometheus/prometheus#1801]
if you provide:

```
static_configs:
  - files:
    - /path/to/files*.json
```

in prometheus.yml (which is wrong, it should be `file_sd_configs` instead of `static_configs`) at least promtool complains about:
`FAILED: unknown fields in target_group: files`

This error is quite misleading and makes it harder to locate the actual problem.

My short digging into the topic revealed that something might be [calling checkOverflow with a wrongly labeled context](https://github.com/prometheus/prometheus/blob/master/config/config.go#L226), but I haven't digged too far, I must admit.

**Comment by brian-brazil** [comment]
This error is correct, and I'm not sure we can do much about it. Knowing that you meant a difference SD mechanism one level up in the config would require quite a bit of sophistication, which I'm not sure is possible.

**Comment by cherti** [comment]
although I think I see how the error comes into place technically, could you line out how you mean "correct" here with regard of promtool complaining about an error in a field that is not specified?

To be more specific: I do not see yet how this is correctly labeled as an unknown field *in* `target_group`, as the latter is not specified there.
Maybe a change in formulation could already clarify things.

**Comment by brian-brazil** [comment]
`static_configs` is a list of `target_group`s, `files` is not a field of `target_group`.

**Comment by cherti** [comment]
so the error reads as `files` not being of *type* `target_group`, correct?

**Comment by brian-brazil** [comment]
No, that files is not a field of the type target_group.

**Comment by cherti** [comment]
ok, that's what I meant.

For my reading/understanding of the message, the error is wrong then. At least the colon has to go imo, because to me it looks like a separator with `files` being the unknown field *in* a `target_group` somewhere in the config file.

**Comment by brian-brazil** [comment]
That is what the message means.

**Comment by beorn7** [comment]
In different news:

`target_group` is outdated, it should read `static_config`.
Perhaps that clears a bit of the misunderstanding.

**Comment by beorn7** [comment]
Changed issue title accordingly.

**Comment by rprakashg** [comment]
Can we get the documentation fixed -> https://prometheus.io/docs/operating/configuration/#<static_config>
