### ISSUE TITLE
The way to pull metrics from nsq channel

### ISSUE THREAD

**Issue by freeseacher** [prometheus/prometheus#1803]
Hi!  
I am looking for ways to migrate from influxdb to prometheus. 
Currently i have several custom collectors that push metrics to nsqd in influxdb line protocol and custom writer to influxdb. 
Is there i way to teach prometeus got that metrics from nsq ?
At present moment i found only one - telegef nsq consumer, but that approach looks ugly. 
Maybe there is a better way ?

**Comment by brian-brazil** [comment]
There's a influxdb exporter that can take in the line procotol and produce Prometheus metrics.

https://github.com/prometheus/influxdb_exporter/
