### ISSUE TITLE
evaluation_interval per rule

### ISSUE THREAD

**Issue by zxwing** [prometheus/prometheus#1806]
Is there any way to specify evaluation_interval per each recording rule?
I have the requirement to execute an ad-hoc expression rule per hour and another expression  per 15s, which cannot be achieved by current global evaluation_interval.

To be clear, I plan to have a rule to record the host CPU usage every hour so my application won't get destroyed when I pull the CPU usage during the past six months, given the scrape_interval is 10s. However, I need another rule to record the usage every 15s for a better resolution.

**Comment by brian-brazil** [comment]
This is #1095 

I'd suggest for now just running it every 15s. The extra samples don't cost much more to store.
