### ISSUE TITLE
How can I do sampling on metrics?

### ISSUE THREAD

**Issue by zxwing** [prometheus/prometheus#1808]
My application needs to show the monitoring history spanning six months with the scrape_interval = 10s, which says the range vector will have ~1.5M records. We originally plan to use a recording rule to average data with the interval 15m. However, because of the bug https://github.com/prometheus/prometheus/issues/1095 we cannot have other rules averaging data with different intervals(e.g. 30m, 1h). 

I'd like to ask your suggestions for this situation. Is there any way we can specify the sampling interval when doing avg()? That says the avg() can return a range vector instead of an instant vector. This feature is available on Kairosdb, below is a screenshot.

![image](https://cloud.githubusercontent.com/assets/1362214/16792762/2699aff2-48fe-11e6-9d0a-a98b0c737557.png)

**Comment by brian-brazil** [comment]
We don't and won't offer downsampling in Prometheus, however you can call query_range with whatever interval you like.

**Comment by zxwing** [comment]
So the recording rule is the only way for my situation? Hope we can have the feature that sets evaluation_interval per rule soon

**Comment by brian-brazil** [comment]
The question here is what are you trying to do?

**Comment by zxwing** [comment]
I have a time series with 1.5 million samples collected during the past six months. How can I display them without downsampling?

**Comment by brian-brazil** [comment]
For that you'll need to put `my_series[26w]` into the `query` endpoint and then render them yourself. This can't be done with a single request to `query_range`, as we've safeties against returning too many point.

**Comment by zxwing** [comment]
Processing the raw data in my application is always doable. However, as prometheus already have a bunch of functions and operators, I hope there would be a way doing such post-processing work in prometheus before returning samples to API callers. For me the recording rule is designed for this, but the global evaluation_interval restricts its usage.

**Comment by zxwing** [comment]
BTW, what is the "query endpoint" you mean here? My understanding is the application can only call retrieve samples from prometheus thru the HTTP APIs. Does the "query endpoint" here stand for applications?

**Comment by brian-brazil** [comment]
The HTTP API offers several endpoints, `query_range` is the one usually used for graphing and there's also `query`.

**Comment by brian-brazil** [comment]
It sounds like with you should make multiple query_range calls, or handle the processing inside your application.

**Comment by zxwing** [comment]
"It sounds like with you should make multiple query_range calls" we can't do this as the cost is too expensive, my dashboard will access those samples frequently. 

Now my solution is to create my exporter to create new time series with post-processed samples. The workflow is:
1. Promethues pull my exporter
2. My exporter queries promethues using functions like avg_over_time()
3. My exporter returns processed samples to Promethues 
4 .Promethues saves the samples in a new series

Then my application can just query and render the new series.

**Comment by brian-brazil** [comment]
I think you're greatly over-complicating the problem. Why not just make a normal graph using avg_over_time?

**Comment by zxwing** [comment]
avg_over_time returns an instant vector but not a range vector, I don't want to make lots of query_range calls(tens of thousands for 1.5M samples).

**Comment by zxwing** [comment]
I paste the avg_over_time() below to make sure I don't misunderstand something.
For example I have samples for the last one hour, the avg_over_time() only returns me two samples while I may want it to return 60 samples with 1 minute interval, which is downsampling that you said won't be supported. 

![image](https://cloud.githubusercontent.com/assets/1362214/16797451/397e328e-491a-11e6-918e-87fd3b5a42d5.png)

![image](https://cloud.githubusercontent.com/assets/1362214/16797481/557db7ca-491a-11e6-83e5-d8b603818aa5.png)

**Comment by brian-brazil** [comment]
The console view uses `query`, the graph view uses `query_range`. You can ask query_range to request evaluation at a 1 minute interval.

**Comment by zxwing** [comment]
Awesome! I wasn't aware the query_range has a `step` parameter which is exactly what I want! Thanks for your patient answer! Now Prometheus solves all of my problems, I love  this project!
