### ISSUE TITLE
supporting multi-tenancy

### ISSUE THREAD

**Issue by zxwing** [prometheus/prometheus#1813]
Is there any plan to support multi-tenancy in Prometheus? Making users in a public cloud only see monitoring data belonging to them. Frankly speaking, I don't know how a multi-tenancy monitoring system looks like or if there is anything existing. Now we retrieve all data users ask and do a post-process filtering out data users not supposed to see, it works but inefficient.

**Comment by fabxc** [comment]
Different companies are interested in that and there's some ongoing explorative work: https://docs.google.com/document/d/1C7yhMnb1x2sfeoe45f4mnnKConvroWhJ8KQZwIHJOuw/edit#

The current working approach seems to be to attach a `user` label to the metrics and pre-process incoming queries to always have a `user="x"` selection in each retrieved metric. Some companies are doing that but there's no open source version of it.
It shouldn't be too complex to re-implement though using the `promql` package in this repository.

**Comment by zxwing** [comment]
Good to see there is something on-going! However, labeling user="x" is not working in a sophisticated system where resources can be shared to other tenancies. This is why we do filtering instead of labeling metrics.

**Comment by fabxc** [comment]
I see that it can get more complex but cannot immediately see for which cases filtering the result provides something that cannot be implemented with a similar rule set on pre-processing queries.
Calculating results and throwing them away is always unideal.

**Comment by zxwing** [comment]
Let's say the user A has a service with metrics labeled with user='A'; after a while, he transfers the service to user B, how should I re-label the service's metric from user='A' to user='B'?

**Comment by fabxc** [comment]
Ah, got it. I suppose you could check the query selections beforehand anyway. But filtering the result might be easier, especially as regex queries along the `__name__` label get involved.

**Comment by zxwing** [comment]
I planned to check query selections originally but found it's not easy with Prometheus's query DSL. 
The DSL is great for operating but not friendly for API integration. A DSL parser is required so I can know what labels users select. Another way is to create my APIs that wrap Promeheus's DSL, but then I have to write tons of documents to explain how my APIs map to Prometheus's DSL, and users will definitely get confused.  So for now the filtering is an easier way.

**Comment by zxwing** [comment]
Is there any DSL spec for Prometheus?

**Comment by fabxc** [comment]
Not really. It was changing a fair bit in the past but now we could
actually have one.
But the `promql` package in the prometheus source tree provides a parser
that gives you an AST, which is easy to work with. It's used by other
organizations to solve similar problems.

**Comment by zxwing** [comment]
Got it! Thanks a lot!

**Comment by zxwing** [comment]
it's answered, close it

**Comment by yasongxu** [comment]
some project is open  [cortex](https://github.com/cortexproject/cortex)
