### ISSUE TITLE
[feature] Ability to filter relevant scraper port with marathon_sd

### ISSUE THREAD

**Issue by czervenyvlk** [prometheus/prometheus#1814]
Hi,
With meta label **__meta_marathon_app_label_<labelname>** I can only filter all application tasks with help of an application label.
I run docker container and in this case application task expose multiple generated host ports to which only few application scrapers are bind to from the container.
Is it possible to filter/identify these relevant services providing Prometheus metrics?

**Comment by grobie** [comment]
Do you want to give it a try?

**Comment by czervenyvlk** [comment]
Hi @grobie I played with file_sd_configs and manually query marathon api for list of the ports for marathon task and then ensure that prometheus metrics is exposed on that port - it works, but I think it's not really clear way how to do it.
