### ISSUE TITLE
Kubernetes SD example does not include required 'role'

### ISSUE THREAD

**Issue by karora** [prometheus/prometheus#1823]
From the 1.0 release notes, as well as from reading the documentation here:
https://github.com/prometheus/docs/blob/master/content/docs/operating/configuration.md#kubernetes_sd_config

it appears that a `role` of `endpoint`, `service`, `node`, `pod`, `container` or `apiserver` must be present in each kubernetes_sd_config, however the example does not yet seem to be updated to include these.

https://github.com/prometheus/prometheus/blob/master/documentation/examples/prometheus-kubernetes.yml

**Comment by jimmidyson** [comment]
Good catch. Fancy sending in a PR to fix?

**Comment by karora** [comment]
Heh - there was a reason I was looking for the example - might take me a week or two before I have the time to read and understand the manual - it's pretty dense prose ... :-)

**Comment by SleepyBrett** [comment]
Yeah this broke my install as well.

**Comment by SleepyBrett** [comment]
Well I was just about to build a pull request around my first stab at a config and it looks like you guys have a new config example on master.

thanks @zoidbergwill

**Comment by zoidbergwill** [comment]
Whoops, didn't even see this issue, or I would've referenced it in my PR.

Fortunately the great people that reviewed my PR managed to help me figure out what exactly needed to be updated.

**Comment by jimmidyson** [comment]
Fixed by #1840
