### ISSUE TITLE
PromQL question

### ISSUE THREAD

**Issue by svenmueller** [prometheus/prometheus#1824]
Hi,

Is there a way in PromQL to query/calculate the CPU usage value for each available instance/target (something like in the console node template) and show it as result when executing the query?

```
# this would be the query for a single instance
100 * (1 - avg by(instance)(irate(node_cpu{job='node',mode='idle',instance='instance'}[5m])))
```

Thx in Advance,
Sven

**Comment by brian-brazil** [comment]
Remove the `instance='instance'` from that expression. See http://www.robustperception.io/understanding-machine-cpu-usage/

**Comment by svenmueller** [comment]
Thx, i completly missed that.
