### ISSUE TITLE
Issue with count_values()?

### ISSUE THREAD

**Issue by Hetkoekje** [prometheus/prometheus#1849]
Hi,

I've been using Prometheus with Cadvisor and node_exporter to monitor some dockers, currently i'm attempting to write a query to detect when a docker container goes down.
So far I've found this query that almost does the job to my liking:
`count(container_last_seen{image!=""}) `

This detects the amount of running containers nicely, but if prometheus is running and a docker goes down after prometheus is already running, the metric isn't removed.
This is cadvisor's part and maybe it is designed this way, because what i do notice is that the value of metric changes if the docker goes down!
Then I found the count_values() operator instead of the count() in the documentation of your website and was thinking, that's it!

Unfortunately, when I replaced count() with count_values() I received the following error:
`count_values(container_last_seen{image!=""})`
> Error executing query: parse error at char 44: unexpected ")" in aggregation, expected ","

Is this working as intended? If so, could you please clarify this a bit in your documentation and maybe put it in another category as count() or something? Because at this time, it seems like they can both be used in the same way  (syntax wise).
If not, a bug is hereby reported :smile:

**Comment by grobie** [comment]
Check the documentation of the count_values(), there is a required parameter for specifying the label name which will hold the unique value. In you case, something like `count_values("timestamp", container_last_seen{image!=""})`.

**Comment by Hetkoekje** [comment]
Thank you! That did the job!
Seeing the result of the query, it also actually makes sense that you need to add a label parameter.

It still isn't very clear to me though where exactly this is documented, but that probably is a fault on my part. I was looking at [this page](https://prometheus.io/docs/querying/operators/#aggregation-operators) and following the logic here, to me it seemed that it could be used the same way as count()

But again, this is probably a fault on my part.
Thank you again for your quick response and making this awesome tool!
