### ISSUE TITLE
 container_fs_io_current always 0

### ISSUE THREAD

**Issue by ZhenyangZhao** [prometheus/prometheus#1854]
Hi all:
My prometheus "container_fs_io_current" always 0,but in cadvisor diskio not 0.Is that correct?

prometheus version: 0.20.0

deploy: prometheus running on docker.

pic1: prometheus

![image](https://cloud.githubusercontent.com/assets/7477708/17207247/3e1550a2-54e6-11e6-9418-cd9118405358.png)

pic2: cadvisor

![image](https://cloud.githubusercontent.com/assets/7477708/17274673/bf9ec0aa-571f-11e6-8dd0-1015a2b78d53.png)

Thanks

**Comment by fabxc** [comment]
That value is retrieved from cAdvisor. If you think it might be wrong, you
have to check with the cAdvisor maintainers.

**Comment by ZhenyangZhao** [comment]
@fabxc 
Thanks for your reply.
I really wonder in my environment.
port:9104 is my cadvisor. when i check the cadvisor. container diskio is not 0. i use docker command line "docker ps -a | docker stats" block io is not 0. but i use prometheus query expression like "container_fs_io_current" all response 0.

prometheus version: 1.0.1

**Comment by Chentongxuedefanhua** [comment]
+1

**Comment by ZhenyangZhao** [comment]
@fabxc  thanks alot. my mistake
