### ISSUE TITLE
level=error msg="Storage needs throttling. Scrapes and rule evaluations will be skipped."

### ISSUE THREAD

**Issue by wkshare** [prometheus/prometheus#1857]
So we for how to deal with this problem?

**Environment**

* System information:

	Linux 3.19.0-25-generic x86_64

* Prometheus version: 

	prometheus, version 0.20.0 (branch: master, revision: aeab25c)
  	build user:       root@77050118f904
  	build date:       20160616-08:38:14
  	go version:       go1.6.2

* Prometheus configuration file:
```
insert configuration here
```

* Alertmanager configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
time="2016-07-29T12:13:49+08:00" level=error msg="Storage needs throttling. Scrapes and rule evaluations will be skipped." chunksToPersist=526447 maxChunksToPersist=524288 maxToleratedMemChunks=57671680 memoryChunks=52595672 source="storage.go:707" 
time="2016-07-29T12:18:35+08:00" level=error msg="Storage needs throttling. Scrapes and rule evaluations will be skipped." chunksToPersist=524376 maxChunksToPersist=524288 maxToleratedMemChunks=57671680 memoryChunks=52525249 source="storage.go:707"
```

**Comment by beorn7** [comment]
Your Prometheus server cannot keep up with the load of samples to persist. You'll find relevant information here: https://prometheus.io/docs/operating/storage/

**Comment by fabxc** [comment]
Closing here as this is a configuration issue. Let us know if you have any further trouble.
