### ISSUE TITLE
Inconsistent encoding of units in metric names

### ISSUE THREAD

**Issue by streadway** [prometheus/prometheus#186]
The lack of units for the counter scalars has lead to encoding them in the docstring, or metric name itself.  Does it make sense to use a label for units?  It seems we have a metric level special meaning for the "name" label, does this extend also to "units"?

Examples of confusing names with the units encoded in different locations in the names, and in the docstring.

`namespace_metric_units` vs. `namespace_units_metric`

  * "http_request_durations_microseconds", "The amounts of time the default multiplexor has spent answering HTTP requests (microseconds)."
  * "http_request_bytes_total", "The total volume of content body sizes received (bytes)."

**Comment by juliusv** [comment]
This got resolved a while ago, closing.
