### ISSUE TITLE
Alert rule configuration file cannot be automatically loaded

### ISSUE THREAD

**Issue by barnettZQG** [prometheus/prometheus#1866]
in prometheus config.yml file ,i can see this:
 **# Load and evaluate rules in this file every 'evaluation_interval' seconds.**
but I practice shows that it is not effective。
I use latest version image from docker-hub "prom/prometheus"

Other:
the targets configuration file could be automatically loaded

**Comment by matthiasr** [comment]
The comment is technically correct but ambiguous. The rules are loaded
once, then evaluated regularly. To reload them, send a SIGHUP to the
Prometheus process.
-- 
Matthias Rampke
Engineer

SoundCloud Ltd. | Rheinsberger Str. 76/77, 10115 Berlin, Germany | +49 173
6395215

Managing Director: Alexander Ljung | Incorporated in England & Wales with
Company No. 6343600 | Local Branch Office | AG Charlottenburg  | HRB 110657B

**Comment by barnettZQG** [comment]
thank you for you answer.
but i think that rule cloud be automatic loading is very useful.

**Comment by fabxc** [comment]
This was a deliberate decision as it was with not reloading the configuration automatically.
Files watches don't show super consistent behavior cross-platform and we don't want to run into issues of loading partial, yet valid, configurations or rule files.

If one is able to deploy a new file, it is equally easy to follow this up with a SIGHUP in general.

**Comment by barnettZQG** [comment]
I restart the prometheus container after modify the rules file,but now prometheus data size over 60GB,so it very slow.  Don't know whether normal or not.

**Comment by barnettZQG** [comment]
So now I can use the following two ways:
(1)kill -HUP  pid 
(2)curl -X POST http://localhost:9090/-/reload

**Comment by fabxc** [comment]
Yes, after a certain size restarts tend to become slower as data has to be checkpointed & loaded.
The reloading is the very fast alternative.
