### ISSUE TITLE
[Question] How to give a alarm when prometheus is down?

### ISSUE THREAD

**Issue by liuguoming** [prometheus/prometheus#1879]
Hi! I have three question and need your suggestion.
1. How to give an alarm hen prometheus is down?
2. Does prometheus pull metrics concurrently if there are many jobs?

**Comment by fabxc** [comment]
Yes, metrics are pulled concurrently, potentially thousands may happen in
parallel.

You would alert about a Prometheus server being down by having a designated
Prometheus server, which monitors your other Prometheus servers.
You would have two of these. So they in turn can monitor each other. We
call this "meta-monitoring".
