### ISSUE TITLE
How to build docker from the git source 

### ISSUE THREAD

**Issue by sakthivel1988** [prometheus/prometheus#1891]
Hi ,

How can i build the docker from the dockerfile for Prometheus , I have the issue for building  the file 

[root@kube-master prometheus]# docker build -t prometheus .
Sending build context to Docker daemon 25.55 MB
Step 1 : FROM quay.io/prometheus/busybox:latest
 ---> 372dfc85dcbc
Step 2 : MAINTAINER The Prometheus Authors <prometheus-developers@googlegroups.com>
 ---> Using cache
 ---> ea2bdba0c610
Step 3 : COPY prometheus /bin/prometheus
lstat prometheus: no such file or directory

Says the binary file prometheus  missing , But how to generate the binary . Please let me know how to get  it 

Regards,
Sakthi

**Comment by fabxc** [comment]
You have to run `make build` first to build the binaries.

**Comment by sakthivel1988** [comment]
Thanks a ton !!!


I had a issue in setting my gopath .. Now fixed and build the docker .


Regards,
Sakthi
