### ISSUE TITLE
Make rule evaluation and federation consistent in time

### ISSUE THREAD

**Issue by beorn7** [prometheus/prometheus#1893]
Currently, if samples get ingested _during_ a rule is evaluated or a federation request is processed, only a subset of samples with the same timestamp may be taken into account during the evaluation.

Making ingestion of all the samples from a single scrape atomic would solve the problem, but the problem might be solved in an easier way by "simply" ignoring samples that came in after a certain watermark.

For reference: discussion started in https://github.com/prometheus/docs/issues/514 and already referenced #398 as a possible part of the solution.

**Comment by beorn7** [comment]
Also #1887 for the reported incident that caused the discussion in the first place.

**Comment by lmb** [comment]
I reported #2598, which was closed as a duplicate of this issue. I think this issue should mention that this behaviour breaks aggregating histograms using histogram_quantile in the currently released version. That should prevent more dupes.

**Comment by Gouthamve** [comment]
AFAICS, this is fixed 2.0. Can this be closed @fabxc @brian-brazil

**Comment by brian-brazil** [comment]
This is not fixed in 2.0 (yet).

**Comment by brian-brazil** [comment]
I've got a basic version of this working over in the tsdb repo, it needs cleanup and performance work.

**Comment by krasi-georgiev** [comment]
@beorn7 , @brian-brazil , @gouthamve  is this issue still unsolved?

**Comment by brian-brazil** [comment]
Yes, there's an old PR over in TSDB for this. I believe @gouthamve was planning on working on it soon.

**Comment by krasi-georgiev** [comment]
aah that must be the isolation PR https://github.com/prometheus/tsdb/pull/306

**Comment by beorn7** [comment]
Based on some recent discussions I had, this seems to hurt quite a few people, especially for rules calculating histogram quantiles aggregating many targets.

The “almost done” [PR](https://github.com/prometheus/tsdb/pull/306) somehow became stale. @gouthamve doesn't have time right now to work on it. The PR is for the archived TSDB repo, so it has to be lifted over into prometheus/prometheus and then made ready for a final review. If anybody wants to do that, please speak up here in the issue. Otherwise, I'll add it to my long list of urgent things to do.

For reference: @gouthamve created [slides](https://docs.google.com/presentation/d/1-ICg7PEmDHYcITykD2SR2xwg56Tzf4gr8zfz1OerY5Y/edit?usp=sharing) to explain the design. Slides 14, 15, 16 have most of the process.

**Comment by beorn7** [comment]
Adding it to my list by assigning this issue to me. I'll still appreciate others beating me to it. Just assign to yourself or let me know.

**Comment by beorn7** [comment]
The one left TODO: Make the actual scrape and the creation of the synthetic metrics use the same appender, so that they all appear at the same time.

**Comment by beorn7** [comment]
After some thinking and discussion, I have now filed a separate issue #6950 for the remaining task. It's easier than the main part that has been done now, and it's lower priority. Might be a good issue for somebody who wants to get into TSDB development.

Closing this now.
