### ISSUE TITLE
Build and distribute prometheus as snap package

### ISSUE THREAD

**Issue by jacekn** [prometheus/prometheus#1897]
Latest Ubuntu LTS (16.04) ships with prometheus version 0.16.2 which is over 6 months old. There is no native way to get newer version.

It would be good to have prometheus available in snap format which is better suited for fast moving projects.

I did some work on it and snap builds and runs fine: https://github.com/jacekn/prometheus/tree/snap

but it would need to be integrated with promu

**Comment by brian-brazil** [comment]
What is snap and why should we dedicate ongoing maintenance effort to support it?

**Comment by jacekn** [comment]
It's recent cross-distro packaging format, more info is here: http://snapcraft.io/

It's very simple and maintenance burden is minimal. Prometheus snap packages would allow users to easily install and keep it up to date.

**Comment by brian-brazil** [comment]
Per previous discussion, closing this.
