### ISSUE TITLE
Forbid invalid relabel configurations

### ISSUE THREAD

**Issue by grobie** [prometheus/prometheus#1900]
This produces an empty label name

```
# config
relabel_configs:
- source_labels: [__address__]

# result
node_boot_time{="localhost:9100",instance="localhost:9100",job="node"}
```

I guess a configuration with either just `source_labels` or just `target_label` or any other config not having the minimum set of attributes set should be rejected.

**Comment by hashmap** [comment]
@grobie I'm not an expert in relabeling, all my knowledge comes from @brian-brazil PromCon talk. I've implemented a draft of this fix based on https://prometheus.io/docs/operating/configuration/#<relabel_config>:
* `source_labels` must be defined
* `target_label` must be defined if `action` is `replace` or `hashmod`

However I found some counterexamples in `conf.good.yml` which is good by definition, right?
* https://github.com/prometheus/prometheus/blob/master/config/testdata/conf.good.yml#L49
* https://github.com/prometheus/prometheus/blob/master/config/testdata/conf.good.yml#L87

Am I missing something?

**Comment by brian-brazil** [comment]
It is valid to not have source labels.

**Comment by hashmap** [comment]
@brian-brazil in any case or in some particular? In https://prometheus.io/docs/operating/configuration/#<relabel_config> only `labelmap` looks unclear to me, the rest should require source labels

**Comment by brian-brazil** [comment]
Replace doesn't require `source_labels` either.

**Comment by brian-brazil** [comment]
That's useful for target relabelling, as you might want to add something static that's not from SD.
