### ISSUE TITLE
Add check metrics functionality to promtool

### ISSUE THREAD

**Issue by grobie** [prometheus/prometheus#1902]
Promtool can check configs and rule files, it'd be great if it also could test the output of a /metrics endpoint and check it for errors to guide developers during the creation of custom exporters.

**Comment by beorn7** [comment]
Or to guide developers of client libraries… (Ideally, developers of exporters use a client library that protects them from exporting invalid metrics.)

**Comment by grobie** [comment]
While it existed before #1953, this issue has less information and qualifies as the duplicate.
