### ISSUE TITLE
Alert rules with "constans"

### ISSUE THREAD

**Issue by freeseacher** [prometheus/prometheus#1905]
Hi i want to separate constants with threshold from rules. and made such configuration. 
```
rule_files:
  - "init.rules"
  - "rules/*.rules"
```
init.rules
```
prod:disk_used_percent:warning = 80
prod:disk_used_percent:critical = 95
```
I want to use it in such rule
```
cat rules/prod.rules 
ALERT disk_usage_percent_warning
  IF disk_used_percent > prod:disk_used_percent:warning
  LABELS {....}
  ANNOTATIONS { .....}
```
but when i do t manually  
```
disk_used_percent{env="prod",host="wrk01"} > prod:disk_used_percent:warning
```
return empty result
but 
```
disk_used_percent{dc="BAL",env="prod",fstype="xfs",host="wrk01",job="wrk01",path="/"}	82.29296049154334
```
and 
```
prod:disk_used_percent:warning{}	80
```
According to https://prometheus.io/docs/querying/operators/#comparison-binary-operators that seems to be "Between two scalars" and should be fine. 
Am i'am doing something wrong?

**Comment by brian-brazil** [comment]
`prod:disk_used_percent:warning` is a vector.

It's easiest to use hardcoded values when you can, it's simpler to understand. The more general solution is complicated.

**Comment by grobie** [comment]
We use threshold metrics in a few places where we want to allow users to configure different thresholds. It gets indeed a lot more complicated though.

@freeseacher Both sides are vectors. You'll either need to the right hand side to a scalar or specify the labels the vector matching should work on.
