### ISSUE TITLE
graph not showing any data

### ISSUE THREAD

**Issue by LuboVarga** [prometheus/prometheus#1909]
**What did you do?**
I have selected metrics and use exact label values to select only one.

**What did you expect to see?**
I expect to see 1 day of given metrics, where first half of day there was some value (constant value of 18171) and other part there (probably) were not reported any value for given metrics. (I know that best practice talks about providing all values at app startup, but this is now WIP in our app)

**What did you see instead? Under which circumstances?**
In graph I do not see nothing. When I hover by mouse, I see that at first part of graph, there are datapoints (tooltip will show me) and in second part I do not see any datapoint. I neither see any value on axis, so I am able to see, that there is something other than null/0.

When I do not limit query to single metric (by exact label values), I can see given metric "normally". I see that it is constant (18171) for some time (there is green line) and than it drops to 0 (again green line :). Why this behaviour is not same for that particular single metrics being selected?

PS: I think that visualization needs some other metrics to have logged 0 value, to show also unlogged values as 0. Am I right? Can this behaviour be fixed?

* Prometheus version:
1.0.1

**Comment by brian-brazil** [comment]
This sounds like you ran into #1214 

Grafana would be one way to handle this.

**Comment by LuboVarga** [comment]
Yes, it seems that referenced issue is exactly what I have hit. Grafana is not a best solution, as I very often use prometheus for ad-hoc queries hitting this bug. I would prefer, if prometheus simple graph start acting as grafana's graph. I will wait :-)
