### ISSUE TITLE
Metric tracking crash recoveries?

### ISSUE THREAD

**Issue by mattbostock** [prometheus/prometheus#1918]
There's a metric to track inconsistencies in the local storage:

```
prometheus_local_storage_inconsistencies_total
```

https://github.com/prometheus/prometheus/blob/70490fe5685277a7ff5bf09aaa96843a379a6e25/storage/local/persistence.go#L242-L247

...but it's not incremented (as far as I can tell) when the storage is found dirty during startup (and crash recovery is invoked):

https://github.com/prometheus/prometheus/blob/70490fe5685277a7ff5bf09aaa96843a379a6e25/storage/local/persistence.go#L700-L708

The help for the above metric says:

> A counter incremented each time an inconsistency in the local storage is detected. If this is greater zero, restart the server as soon as possible.

So it probably doesn't make sense to use it to indicate that crash recovery took place when Prometheus started.

Should we have a separate metric dedicated to this purpose?

**Comment by beorn7** [comment]
As discussed in person, I think a metric like that would make sense. It's usually obvious from the logs that it happened, but you have to check the logs to find out. So the fact that you should check the logs would be something for a ticketing alert. Could be `prometheus_local_storage_started_dirty` or something.

**Comment by mattbostock** [comment]
Thanks, I'll raise a PR soon.
