### ISSUE TITLE
Could you make newHttpClient in ""github.com/prometheus/prometheus/retrieval/target.go" public?

### ISSUE THREAD

**Issue by allanliu** [prometheus/prometheus#1919]
Hi,

Was wondering if you could make the "[newHttpClient](https://github.com/prometheus/prometheus/blob/master/retrieval/target.go#L69)" function public.  Would import it for [vulcan](https://github.com/digitalocean/vulcan) :)

Thanks,

Allan

**Comment by beorn7** [comment]
I'll leave this to @fabxc to decide.

**Comment by fabxc** [comment]
@allanliu This is now exported in master.

**Comment by allanliu** [comment]
thanks!

**Comment by fabxc** [comment]
With the v1.1.1 release from today, it's also in the latest released version.
