### ISSUE TITLE
Support for specifying HTTP headers in scrape configs

### ISSUE THREAD

**Issue by neuroid** [prometheus/prometheus#1921]
Hi,

I think it would be useful to expose a `scrape_config.headers` setting, which would allow to set arbitrary HTTP headers for scrape requests, similar to `scrape_config.params` What's your take on this?

**Comment by fabxc** [comment]
This was discussed before in https://github.com/prometheus/prometheus/issues/1724
Hence, I've to close here as well for the reasons given there.
