### ISSUE TITLE
New generic write path needs authentication support

### ISSUE THREAD

**Issue by tomwilkie** [prometheus/prometheus#1934]
See #1930 

SSL/TLS certs and tokens are both an option, see http://www.grpc.io/docs/guides/auth.html

**Comment by brian-brazil** [comment]
Will we be able to reuse our existing config format, or does this have to be a new format?

**Comment by tomwilkie** [comment]
TBD - I'm hoping for tls we can reuse the existing format, but it'll need
new code, as afaict you don't get to config the http client yourself. Only
looked briefly though.

**Comment by brian-brazil** [comment]
This was implemented
