### ISSUE TITLE
Remote storage in kafka or HBase

### ISSUE THREAD

**Issue by zouyee** [prometheus/prometheus#1935]
**What did you expect to see?**
could prometheus supported remote storage in kafka or HBase?
thank you for your response!

**Comment by fabxc** [comment]
We decided to not further support any specific remote storage implementations as they are way more complex than service discovery integrations for example.
Instead, we just started adding a remote API based on gRPC, which will allow you to integrate Prometheus with any long-term storage you want and also read back from it.

Some of the discussion was captured [here](https://docs.google.com/document/d/1Qj_m-lbatySAU0vsVfAPG7mduN1-nevrpD85uQhi4sY/edit#heading=h.6xcexetcoa4g).
The first bit of implementation was merged yesterday in [this PR](https://github.com/prometheus/prometheus/pull/1930).
