### ISSUE TITLE
get range vector from a function return.

### ISSUE THREAD

**Issue by atoy40** [prometheus/prometheus#1939]
Hello,

i'd like to know if you can generate a range-vector from a function returned instant-vector ?
The idea is to compute the delta() of an averaged-over-time serie. Something like :
delta( avg_over_time(mymetric[10m])[2h] )
but this syntax won't work.

More commonly, is it possible to "mix" functions

Thanks
Anthony.

**Comment by beorn7** [comment]
This is not possible right now, see #1227 .

**Comment by brian-brazil** [comment]
For that use case, you're best off using `deriv`.
