### ISSUE TITLE
ipv6 addresses not automatically wrapped

### ISSUE THREAD

**Issue by w0mbat** [prometheus/prometheus#1944]
**What did you do?**
We installed Kubernetes and Prometheus on top of Rackspace and seeing sometimes ipv4, sometimes ipv6 addresses for nodes, service and pod ips.

**What did you expect to see?**
All endpoints either declared explicitly or via autodiscovery should be in state `UP`

**What did you see instead? Under which circumstances?**
Endpoints with a ipv6 addresses have a state `DOWN` and the error says `Get http://xxxx:xxxx:xxxx:xxx:xxxx:xxxx:xxxx:xxx:9100/metrics: dial tcp: too many colons in address xxxx:xxxx:xxxx:xxx:xxxx:xxxx:xxxx:xxx:9100`

**Environment**

* System information:
Linux 4.7.0-coreos x86_64

* Prometheus version: 
prometheus, version 1.1.0 (branch: master, revision: a60378c77765080a781e313ece0d0ab47c2e54e2)
  build user:       root@583368332c21
  build date:       20160903-19:35:49
  go version:       go1.6.3

* Alertmanager version:

none

* Prometheus configuration file:

https://raw.githubusercontent.com/prometheus/prometheus/v1.1.0/documentation/examples/prometheus-kubernetes.yml

* Alertmanager configuration file:
none

* Logs:
none

* Screens:
<img width="1891" alt="bildschirmfoto 2016-09-05 um 12 18 47" src="https://cloud.githubusercontent.com/assets/571379/18244973/031bf988-7363-11e6-89fc-8ad8e1e605fb.png">

**Comment by fabxc** [comment]
I see where we are rendering them wrong in the UI. However, for scraping we are using `URL.String()`, which handles ipv6 addresses correctly.

**Comment by jimmidyson** [comment]
@fabxc It appears it doesn't... https://play.golang.org/p/Q8ikNMh4aF

**Comment by jimmidyson** [comment]
e.g. https://github.com/prometheus/prometheus/blob/master/retrieval/discovery/kubernetes/node.go#L95

**Comment by fabxc** [comment]
Ah, yes. Just walked to the Prometheus code. Quite a few places where unexpected things could happen with ipv6. Will work on a fix.
