### ISSUE TITLE
prom/prometheus Docker Image misses ssl_helper

### ISSUE THREAD

**Issue by lloesche** [prometheus/prometheus#1947]
Trying to `wget https://...` in the prom/prometheus Docker container results in
```
wget: can't execute 'ssl_helper': No such file or directory
wget: error getting response: Connection reset by peer
```

My use case is, I need to add a helper binary from https://github.com to generate files for file_sd based service discovery. I'd like to use the prom/prometheus image as base for my own image instead of building one from scratch.

I thought prom/prometheus was (used to be?) based off of Alpine but apk doesn't seem to be available.

**Comment by lloesche** [comment]
I just found out I can use ADD in the Dockerfile in place of the wget. This solves my use case. Keeping the issue open in case you want to fix it anyways. After all why have a wget at all if it can't handle https URLs.

**Comment by sdurrheimer** [comment]
We can't fix it, the `wget` from `busybox` doesn't support SSL.

**Comment by lloesche** [comment]
I could have sworn that I did wget a https url using an older version of the prom/prometheus Docker image in the past. Anyways, closing this issue as it's resolved for me.
