### ISSUE TITLE
conf

### ISSUE THREAD

**Issue by fly891583770** [prometheus/prometheus#1949]
**What did you do?**

**What did you expect to see?**

**What did you see instead? Under which circumstances?**

**Environment**
Hello zookeeper configuration file can not be loaded? For example: loading config: couldn't load configuration Error yaml: (-config.file=prometheus.yml): line 5: did not find expected key source=main.go:126
- System information:
  
  insert output of `uname -srm` here
- Prometheus version: 
  
  insert output of `prometheus -version` here
- Alertmanager version:
  
  insert output of `alertmanager -version` here (if relevant to the issue)
- Prometheus configuration file:

```
insert configuration here
```
- Alertmanager configuration file:

```
insert configuration here (if relevant to the issue)
```
- Logs:

```
insert Prometheus and Alertmanager logs relevant to the issue here
```

**Comment by fly891583770** [comment]
Hello zookeeper configuration file can not be loaded? For example: loading config: couldn't load configuration Error yaml: (-config.file=prometheus.yml): line 5: did not find expected key source=main.go:126

System information:
Linux 3.10.0-327.el7.x86_64 x86_64
Prometheus configuration file:


global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
       external_labels:
           monitor: 'codelab-monitor'

  # A scrape configuration containing exactly one endpoint to scrape:
  # Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.        - job_name: 'prometheus'

        # Override the global default and scrape targets from this job every 5 seconds.
           scrape_interval: 5s

        static_configs:
        - targets: ['localhost:9090']

**Comment by Rucknar** [comment]
@fly891583770 The yaml isn't valid. 

```
--- 
global: 
  external_labels: 
    monitor: codelab-monitor
  scrape_interval: 15s
scrape_configs: 
  scrape_interval: 5s
  static_configs: 
    - 
      targets: 
        - "localhost:9090"
```

Should work, the indentation was all wrong in the above. Check out http://www.yamllint.com/ if you want to check this stuff out in the future.
