### ISSUE TITLE
Add relabelling to generic write path

### ISSUE THREAD

**Issue by brian-brazil** [prometheus/prometheus#1955]
As with alerting, this goes after external labels are applied. Where should we put this in the config?

**Comment by fabxc** [comment]
Probably it's own section for all related config. We probably also want to
have SD in there to discover write targets?

**Comment by brian-brazil** [comment]
Yeah, we'll probably ultimately want that. We're still on "target" right now :)

**Comment by fabxc** [comment]
Yes, just another reason to have a new top-level section for `remote` as
there'll be more coming.
That might be best divided in `read` and `write` again.

**Comment by brian-brazil** [comment]
I've have separate top-level write and read sections.

**Comment by tomwilkie** [comment]
Will also want to include remote auth in the config, see #1957.
