### ISSUE TITLE
how to make the event of no datapoint found to triggerring alarm 

### ISSUE THREAD

**Issue by zouyee** [prometheus/prometheus#1956]
**What did you do?**
ALERT ea
  IF sum(rate(container_cpu_usage_seconds_total{marathon_app_id="/nginx"}[5m])) BY (mesos_task_id, instance) / count(container_cpu_usage_seconds_total{marathon_app_id="/nginx"}) BY (mesos_task_id, instance) == nil
  FOR 5m
  LABELS {severity="warning"}
  ANNOTATIONS {description="ea:app:cpus:sum:<0.8:5m:warning:/nginx", summary="ea:app:cpus:sum:<0.8:5m:warning:/nginx"}
**What did you expect to see?**
how to make the event of no datapoint found to triggerring alarm 
![qw](https://cloud.githubusercontent.com/assets/5785605/18316372/e9302026-754c-11e6-8407-341bc3d598a0.png)
@fabxc  could you help me? thanks u for your response!

**Comment by fabxc** [comment]
In general the `absent()` function allows you to generate a result from something that has no result.
I'm not sure I understand what you want to do in this context. Do you want to alert if there are no instances for a Marathon task? In this case you should probably not try to embed this into calculations of CPU usage but have a separate alert.
