### ISSUE TITLE
Range query doesn't support 10s resolution if the time range spanning 2 days?

### ISSUE THREAD

**Issue by zxwing** [prometheus/prometheus#1968]
The following queries data for 2 days with the resolution 10s:
```
[root@172-20-11-202 ~]# wget 'http://172.20.11.202:9090/api/v1/query_range?query=collectd%3Acollectd_virt_memory&start=1473220095&end=1473392838&step=10s' -O stdout
--2016-09-09 11:54:47--  http://172.20.11.202:9090/api/v1/query_range?query=collectd%3Acollectd_virt_memory&start=1473220095&end=1473392838&step=10s
Connecting to 172.20.11.202:9090... connected.
HTTP request sent, awaiting response... 400 Bad Request
2016-09-09 11:54:47 ERROR 400: Bad Request.
```
the `start` *1473220095 = 9/7/2016, 11:48:15 AM GMT+8:00* and the `end` *1473392838 = 9/9/2016, 11:47:18 AM GMT+8:00*, which are two days.

However, if I change the `step` to 1m, the same query works:

```
[root@172-20-11-202 ~]# wget 'http://172.20.11.202:9090/api/v1/query_range?query=collectd%3Acollectd_virt_memory&start=1473220095&end=1473392838&step=1m' -O stdout
--2016-09-09 12:01:27--  http://172.20.11.202:9090/api/v1/query_range?query=collectd%3Acollectd_virt_memory&start=1473220095&end=1473392838&step=1m
Connecting to 172.20.11.202:9090... connected.
HTTP request sent, awaiting response... 200 OK
```

So how should I determine what resolution to use? I think there is a caveat. 

**BTW: can we give out a clear error message in HTTP body? The 400 error is horrible for debug**

**Comment by grobie** [comment]
We set a hard-limit of 11k data points per single query.

> BTW: can we give out a clear error message in HTTP body? The 400 error is horrible for debug

I think the error output is very clear.

```bash
curl http://localhost:9090/api/v1/query_range\?query\=foo\&start\=1473220095\&end\=1473392838\&step\=10s
```

With `wget` it's a bit more laborious as it usually doesn't bother saving the output on error response codes.

```bash
wget -qO - --content-on-error http://localhost:9090/api/v1/query_range\?query\=foo\&start\=1473220095\&end\=1473392838\&step\=10s
```

**Comment by zxwing** [comment]
Thanks @grobie, it's clear now
