### ISSUE TITLE
Adding configuration APIs

### ISSUE THREAD

**Issue by zxwing** [prometheus/prometheus#1972]
Prometheus is great, however, like many other Linux software, it only has APIs for core business but leaves configurations to old-style text files. 

As the current trend for software is *APIs define everything*, I suggest Prometheus adding support for configuration APIs so people don't have to reload configuration by modifying a text file and calling `kill -1`.

**Comment by beorn7** [comment]
This is a very deliberate decision. The discussion happened in various forms. We plan to document non-goals with a bit of justification in the docs to spare people the time to look it up, see https://github.com/prometheus/docs/issues/149#issuecomment-231055809 .

tl;dr: There will be no config API. Those that need it can build a wrapper that provides an API, creates a config file on the other end and sends a SIGHUP.
