### ISSUE TITLE
Question : Setting up Prometheus (dockerized) to monitor OpenVPN clients

### ISSUE THREAD

**Issue by ddewaele** [prometheus/prometheus#1978]
**What did you do?**

Setup prometheus / alertmanager in their docker containers on a user defined bridged network.
Works fine to monitor assets that are running on the hosts / reachable via the internet.

I'm hoping for some guidance on how such a setup could work to monitor OpenVPN clients connected via a tun+ interface (either directly on the host, or via another docker container on the same network).

![](https://dl.dropboxusercontent.com/u/13246619/Docker/docker-prometheus-openvpn.png)

The idea is to monitor external devices (that expose prometheus metrics) that connect to the OpenVPN.

I've asked a more generic question (not involving Prometheus, as I assume this has nothing to do with Prometheus itself) on [superuser](http://serverfault.com/questions/802458/allow-docker-containers-to-connect-to-openvpn-clients-on-the-host-tunnel-interfa).

If somebody has some pointers on how to get this up and running I'd be happy to write up a blog post on how such a setup could work.

**Comment by Rucknar** [comment]
Are you wondering how best to discover the service, route traffic to it, or perhaps how you might get metrics from it @grobie?

**Comment by grobie** [comment]
Please send questions to the prometheus-users usergroup https://groups.google.com/forum/#!forum/prometheus-users instead.
