### ISSUE TITLE
Prometheus Startup Error

### ISSUE THREAD

**Issue by tesla747** [prometheus/prometheus#1981]
**Trying to start Prometheus?**

**What did you expect to see?**

**I'm trying to start prometheus, im getting the below error**

INFO[0000] Starting prometheus (version=1.1.2, branch=master, revision=36fbdcc30fd13ad796381dc934742c559feeb1b5)  source=main.go:73
    INFO[0000] Build context (go=go1.6.3, user=root@a74d279a0d22, date=20160908-13:12:43)  source=main.go:74
    INFO[0000] Loading configuration file prometheus.yml     source=main.go:221
    ERRO[0000] Error loading config: couldn't load configuration (-config.file=prometheus.yml): yaml: line 6: found character that cannot start any token  source=main.go:126

**RHEL 6**

* System information:

Linux 2.6.32-573.12.1.el6.x86_64 x86_64

* Prometheus version: 

prometheus, version 1.1.2 (branch: master, revision: 36fbdcc30fd13ad796381dc934742c559feeb1b5)
  build user:       root@a74d279a0d22
  build date:       20160908-13:12:43
  go version:       go1.6.3

* Alertmanager version:

NA

* Prometheus configuration file:
```
global:
  scrape_interval:     5s
  evaluation_interval: 5s
scrape_configs:
- job_name: linux
target_groups:
        -targets: ['192.17.36.189:3306']
          labels:
            alias: db1
```

* Alertmanager configuration file:
```
NA
```

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```

**Comment by fabxc** [comment]
You have to put a space after the `-` in `-targets`. Please use a YAML linter for future YAML syntax errors: http://www.yamllint.com/

**Comment by tesla747** [comment]
Thanks fabxc. I have started it, but i'm unable to open the prometheus link in my browser. It says site can't be reached. I know these doubts are silly. Would be glad if you could help me. Does it have to do with proxy or anything?
