### ISSUE TITLE
Add minute() function

### ISSUE THREAD

**Issue by mattbostock** [prometheus/prometheus#1983]
**What did you do?**

Tried to add an alert that triggers at a specified time, e.g.:

```
hour() % 8 == 0 and minute() > 30 and minute() < 40
```

The idea is to trigger an alert at the start of each on-call shift to test the escalation path, i.e. are the on-call people's phones working, do we have the correct phone numbers, is the rota configured correctly.

**What did you expect to see?**

The current UTC minutes returned.

**What did you see instead? Under which circumstances?**

> Error executing query: parse error at char 8: unknown function with name "minutes"

**Environment**

* Prometheus version: 

	matt➜github.com/prometheus/prometheus(master✗)» ./prometheus -version
prometheus, version 1.1.2 (branch: master, revision: 3fd992d2d1450e9153f27e0061bd92743499286a)
  build user:       matt@matt
  build date:       20160912-17:09:55
  go version:       go1.7
matt➜github.com/prometheus/prometheus(master✗)»

**Comment by grobie** [comment]
@mattbostock Makes sense. Do you want to give this a try? It should be pretty straightforward. Here is the commit which introduced hour()/month()/etc. https://github.com/prometheus/prometheus/commit/4680daf2370391a4fd22d92eec4c043b949d7679

**Comment by mattbostock** [comment]
Sure, will do.
