### ISSUE TITLE
Problem with building Prometheus in Windows environment.

### ISSUE THREAD

**Issue by vipetrul** [prometheus/prometheus#1992]
Trying to build Prometheus using golang v 1.7
Issued following command:
C:\GoWorkspace\src\Prometheus>go build -o prometheus ./cmd/prometheus

Received exceptions along these lines:
cmd\prometheus\main.go:29:2: cannot find package "github.com/prometheus/prometheus/config" in any of:
        C:\GoWorkspace\src\Prometheus\vendor\github.com\prometheus\prometheus\config (vendor tree)
        C:\Go\src\github.com\prometheus\prometheus\config (from $GOROOT)
        C:\GoWorkspace\src\github.com\prometheus\prometheus\config (from $GOPATH)

**Environment**
Windows environment. GOPATH is set (see below)

C:\GoWorkspace\src\Prometheus>SET go
GOPATH=C:\GoWorkspace
GOROOT=C:\Go\

* Prometheus version: 
	Current master branch.

**Comment by sdurrheimer** [comment]
Hi there, you shouldclone the project as `C:\GoWorkspace\src\github.com\prometheus\prometheus` not `C:\GoWorkspace\src\Prometheus`.
