### ISSUE TITLE
Malformed HTTP status code Error

### ISSUE THREAD

**Issue by tesla747** [prometheus/prometheus#2007]
**What did you do?**

I have started Prometheus and while I opening the page I get the error in the Targets page. 

**What did you expect to see?**

I'm trying to setup a monitoring for MySQL as mentioned in [this link by Percona](https://www.percona.com/blog/2016/02/29/graphing-mysql-performance-with-prometheus-and-grafana/)

I'm setting this up for the first time.

**What did you see instead? Under which circumstances?**

I'm getting the following error in Targets page of Prometheus:

Get http://172.19.36.189:3306/metrics: malformed HTTP status code "'172.19.36.189'"

![image](https://cloud.githubusercontent.com/assets/20291387/18623564/81c9a9c0-7e5c-11e6-9f5a-7172887fcf57.png)

I need this to run to monitor my MySQL instances.

**Environment**

RHEL

* System information:

Linux 2.6.32-573.12.1.el6.x86_64 x86_64

* Prometheus version: 

prometheus, version 1.1.2 (branch: master, revision: 36fbdcc30fd13ad796381dc934742c559feeb1b5)
  build user:       root@a74d279a0d22
  build date:       20160908-13:12:43
  go version:       go1.6.3

* Alertmanager version:

NA

* Prometheus configuration file:
```
global:
  scrape_interval:     5s
  evaluation_interval: 5s
scrape_configs:
- job_name: linux
  static_configs:
  - targets:
    - '172.19.36.189:3306'
    labels:
      alias: db1

```

* Alertmanager configuration file:
```
NA
```

* Logs:
```
No errors reported in logs:

time="2016-09-19T11:24:07+05:30" level=info msg="Checkpointing in-memory metrics and chunks..." source="persistence.go:548"
time="2016-09-19T11:24:07+05:30" level=info msg="Done checkpointing in-memory metrics and chunks in 3.150607ms." source="persistence.go:572"
time="2016-09-19T11:24:07+05:30" level=info msg="Completed maintenance sweep through 2 in-memory fingerprints in 20.000345545s." source="storage.go:1086"
time="2016-09-19T11:24:37+05:30" level=info msg="Completed maintenance sweep through 2 in-memory fingerprints in 20.000348375s." source="storage.go:1086"
time="2016-09-19T11:25:07+05:30" level=info msg="Completed maintenance sweep through 2 in-memory fingerprints in 20.000335103s." source="storage.go:1086"
time="2016-09-19T11:25:37+05:30" level=info msg="Completed maintenance sweep through 2 in-memory fingerprints in 20.000307011s." source="storage.go:1086"
time="2016-09-19T11:26:07+05:30" level=info msg="Completed maintenance sweep through 2 in-memory fingerprints in 20.000357629s." source="storage.go:1086"
time="2016-09-19T11:26:37+05:30" level=info msg="Completed maintenance sweep through 2 in-memory fingerprints in 20.000357269s." source="storage.go:1086"
time="2016-09-19T11:27:07+05:30" level=info msg="Completed maintenance sweep through 2 in-memory fingerprints in 20.000381751s." source="storage.go:1086"
time="2016-09-19T11:27:37+05:30" level=info msg="Completed maintenance sweep through 2 in-memory fingerprints in 20.000385896s." source="storage.go:1086"
time="2016-09-19T11:28:07+05:30" level=info msg="Completed maintenance sweep through 2 in-memory fingerprints in 20.000319199s." source="storage.go:1086"

```

**Comment by fabxc** [comment]
Do you see correct metrics when visiting
http://172.19.36.189:3306/metrics manually
in your browser?

**Comment by tesla747** [comment]
No, the page is not opening. While I try to do telnet to the server 172.19.36.189 @3306 it says:

D♦Host '10.224.16.8' is not allowed to connect to this MySQL server
Connection to host lost.

**Comment by fabxc** [comment]
That looks like the port of the MySQL database. This is not how you monitor
MySQL with Prometheus.
The blog post you linked above goes into quite a bit of detail about the
usage of exporters. Please verify that you followed the instructions there
correctly.

**Comment by tesla747** [comment]
I have added necessary parameters in exporters. Yet the metrics page is not opening.

**Comment by tesla747** [comment]
The target state is showing only down
