### ISSUE TITLE
Getsockopt: connection refused

### ISSUE THREAD

**Issue by tesla747** [prometheus/prometheus#2008]
**What did you do?**

Started Prometheus to monitor linux host.

**What did you expect to see?**

I was expecting the target status to be in UP Status.

**What did you see instead? Under which circumstances?**

I'm getting the below error:

![image](https://cloud.githubusercontent.com/assets/20291387/18628421/c68bb00a-7e7d-11e6-9086-57af7ebefd5c.png)

**Environment**

Linux

* System information:

Linux 2.6.32-573.12.1.el6.x86_64 x86_64

* Prometheus version: 
prometheus, version 1.1.2 (branch: master, revision: 36fbdcc30fd13ad796381dc934742c559feeb1b5)
  build user:       root@a74d279a0d22
  build date:       20160908-13:12:43
  go version:       go1.6.3

* Alertmanager version:

NA

* Prometheus configuration file:
```
global:
  scrape_interval:     5s
  evaluation_interval: 5s
scrape_configs:
- job_name: linux
  static_configs:
  - targets:
    - '172.19.36.189:9104'
    labels:
      alias: db1

```

* Alertmanager configuration file:
```
NA
```

* Logs:
```
time="2016-09-19T15:26:27+05:30" level=info msg="Completed maintenance sweep through 3 in-memory fingerprints in 30.000431023s." source="storage.go:1086"
time="2016-09-19T15:26:57+05:30" level=info msg="Completed maintenance sweep through 2 in-memory fingerprints in 20.000186292s." source="storage.go:1086"
time="2016-09-19T15:27:27+05:30" level=info msg="Completed maintenance sweep through 2 in-memory fingerprints in 20.000233901s." source="storage.go:1086"
time="2016-09-19T15:27:57+05:30" level=info msg="Completed maintenance sweep through 2 in-memory fingerprints in 20.00023597s." source="storage.go:1086"
time="2016-09-19T15:28:27+05:30" level=info msg="Completed maintenance sweep through 2 in-memory fingerprints in 20.000197688s." source="storage.go:1086"
time="2016-09-19T15:28:57+05:30" level=info msg="Completed maintenance sweep through 2 in-memory fingerprints in 20.000228615s." source="storage.go:1086"
time="2016-09-19T15:29:27+05:30" level=info msg="Completed maintenance sweep through 2 in-memory fingerprints in 20.0002949s." source="storage.go:1086"
time="2016-09-19T15:29:57+05:30" level=info msg="Completed maintenance sweep through 2 in-memory fingerprints in 20.000235757s." source="storage.go:1086"
time="2016-09-19T15:30:27+05:30" level=info msg="Completed maintenance sweep through 2 in-memory fingerprints in 20.000243498s." source="storage.go:1086"
time="2016-09-19T15:30:47+05:30" level=info msg="Checkpointing in-memory metrics and chunks..." source="persistence.go:548"
time="2016-09-19T15:30:47+05:30" level=info msg="Done checkpointing in-memory metrics and chunks in 3.36598ms." source="persistence.go:572"
time="2016-09-19T15:30:57+05:30" level=info msg="Completed maintenance sweep through 2 in-memory fingerprints in 20.000284943s." source="storage.go:1086"
time="2016-09-19T15:31:27+05:30" level=info msg="Completed maintenance sweep through 2 in-memory fingerprints in 20.000241069s." source="storage.go:1086"

```

**Comment by brancz** [comment]
Have you started the node_exporter on that particular host? Can you `curl` the `/metrics` endpoint?

**Comment by tesla747** [comment]
Yes, node exporter and prometheus server is running on the same server. The page **http://172.19.36.189:9104/metrics** is not opening. It says Unable to connect. Curl gives the same error "couldn't connect to host"

**Comment by brancz** [comment]
Can you `curl localhost:9104/metrics` from the server? If you only have one Prometheus and one `node_exporter` then configuring it with localhost would suffice, other than that there seems to be an issue non-related to Prometheus.

**Comment by tesla747** [comment]
[root@NOVABANK189 prometheus_exporters]# curl localhost:9104/metrics
curl: (7) couldn't connect to host

It isn't connecting. Any idea where I should look at to narrow down the issue?

**Comment by tesla747** [comment]
Once I had mysql exporter started, it seems to show as UP. Thanks for the help!!

**Comment by kaarthikeyan1987** [comment]
I am getting the below error after creating deployment

![image](https://user-images.githubusercontent.com/33221055/32370405-e94913ee-c0b2-11e7-8306-d0d5270ec688.png)
But when I do curl localhost:2379/metrics it is working fine as it loads inside.

Below is my configuration
![image](https://user-images.githubusercontent.com/33221055/32370440-0e4a5b08-c0b3-11e7-87de-672982fd31a0.png)

please help

**Comment by stefano-pogliani** [comment]
@kaarthikeyan1987: Since the `curl`command works with localhost is `etcd` listening only on the localhost interface?
If so you can configure Prometheus to scrape `http://localhost:2379/metrics` and it should work.
