### ISSUE TITLE
Only allow single K8S API server in SD config

### ISSUE THREAD

**Issue by fabxc** [prometheus/prometheus#2013]
The Kubernetes upstream client library does not support multiple API server URLs but instead expects DNS load balancing or using a proxy:

https://godoc.org/k8s.io/client-go/1.4/rest#Config

We should consider making the K8S SD config argument just a single API server URL. If we want to use the official client library there's no way to use multiple ones. With cluster federation and all, there's a fair bit of proxying involved behind the scenes anyway.

@brian-brazil @jimmidyson

**Comment by brian-brazil** [comment]
If that's the way the upstream API works, then that's the way it works.

**Comment by jimmidyson** [comment]
OK let's go with that. Needs to be noted that as we move to static configuration for API servers to scrape metrics from (not k8s SD) that users will have to configure all the API servers, not just the RR DNS or proxy address, but that's a separate issue.

**Comment by brian-brazil** [comment]
The new k8 SD does this.
