### ISSUE TITLE
Ability to scrape pods exposing https endpoints

### ISSUE THREAD

**Issue by vjsamuel** [prometheus/prometheus#2017]
Hi,

Thank you for the amzing product that is prometheus. Is it possible for me to use prometheus to scrape pods running on kubernetes that expose HTTPS endpoints? I dont see a `prometheus.io/scheme` as part of the sample yaml file for Pods but I see it in the example for Services.

Thanks in advance.

**Comment by fabxc** [comment]
The annotations are nothing fixed that's built into Kubernetes. It's merely
a way to provide a value in Kubernetes, that is then available in the
relabeling step.
If you check the Kubernetes example config, you can apply similar
relabeling rules to write 'https' into the Prometheus `__scheme__` label
from a Kubernetes annotation.

**Comment by vjsamuel** [comment]
Thank you very much. It helped.
