### ISSUE TITLE
JS library for graph building

### ISSUE THREAD

**Issue by bernerdschaefer** [prometheus/prometheus#202]
The goal is to have a JS library which provides an API for building graphs from the prometheus rest endpoints. The idea is that this can be used along with #159 to provide a straightforward way of building custom dashboards. Ideally, it can also be used to power prometheus' own graph pane.

**Comment by thachmai** [comment]
@brian-brazil @juliusv 
Did this graph library idea materialize?

I have some experience in data viz and can potentially contribute if there is a need.

**Comment by brian-brazil** [comment]
The graphing library that the console templates use would be a good base (API wise anyway), but it probably needs to be rewritten as frontend dev really isn't my area and it's a little bit buggy. https://github.com/prometheus/prometheus/blob/master/web/blob/static/js/prom_console.js

I was thinking the tricky bit would be bringing promdash in line with whatever we end up using (either factor what it has out, or switch it to the new core graph library) but as it looks like we're hoping to move in the direction of Grafana which means we can skip this.

That's leave the main work then as rewriting the expression browser, such as to support multiple expressions etc.

One wrinkle is that rickshaw which we're using for visualisation currently appears to be a dead project, so we need to switch to something else.

We'd love help with anything around this, as none of us are really frontend developers.

**Comment by thachmai** [comment]
Alright. I'll take a look at the current graph + promdash and the Grafana API to get a general idea. I will get back in touch with you guys in a couple of days with my findings.

**Comment by brian-brazil** [comment]
To be clear, we're only at Grafana as a potential replacement for Promdash. We'd still need a library to allow users embed graphs, including for console templates.

**Comment by thachmai** [comment]
OK. Would it make sense then to see how Grafana implements its graphs and see if there is something we can extract and reuse?

**Comment by fabxc** [comment]
If they are based on open source libraries (which I assume), it absolutely
makes sense.

We would be very happy to see someone giving our frontends a shot.

**Comment by jordan-wright** [comment]
It looks like [they likely use flot](https://github.com/grafana/grafana/tree/master/public/vendor/flot)[1]

[1] [http://www.flotcharts.org/](http://www.flotcharts.org/)

**Comment by gouthamve** [comment]
Closing this because its out of scope for Prometheus now.
