### ISSUE TITLE
Cannot use IPv6 address in Alertmanager URL

### ISSUE THREAD

**Issue by thedirtycolumbia** [prometheus/prometheus#2025]
**What did you do?**
Tried to set -alertmanager.url=http://[IPV6ADDRESS]:PORT/

**What did you expect to see?**
Prometheus able to send alerts to an IPv6 Alertmanager.

**What did you see instead? Under which circumstances?**
It appears that `govalidator.IsURL` does not properly handle IPv6 address (w/ or w/o brackets).

**Environment**

* System information:

	Linux 3.14.33-4.el6.pharos.x86_64 x86_64

* Prometheus version: 

	prometheus, version 0.18.0 (branch: release-0.18, revision: f12ebd6)
  build user:       root@ebaf628123aa
  build date:       20160418-08:20:43
  go version:       go1.5.4

* Alertmanager version:

	alertmanager, version 0.4.2 (branch: master, revision: 9a5ab2fa63dd7951f4f202b0846d4f4d8e9615b0)
  build user:       root@2811d2f42616
  build date:       20160902-15:33:13
  go version:       go1.6.3

* Prometheus configuration file:
https://gist.github.com/shore/8761b976a0f2a68e366772c4033b62b3

* Alertmanager configuration file:
https://gist.github.com/shore/bfa3def3beb8b83f86e48b8a72b86d3c

* Logs:
```
time="2016-09-23T00:08:32Z" level=error msg="invalid Alertmanager URL: http://[::1]:9093" source="main.go:65"
```

**Comment by juliusv** [comment]
@thedirtycolumbia Thanks! Hmm, govalidator has bitten us a number of times already now. I wonder if we should keep using it or just let the occasional wrong URL through.

For now I filed a bug there: https://github.com/asaskevich/govalidator/issues/150

The fix doesn't seem totally trivial if one wanted to fix the `rxURL` regex there. Regexing IPv6 correctly apparently gets quite long. Maybe the correct solution there is to restructure the code and move away from a URL regex altogether.

**Comment by thedirtycolumbia** [comment]
@juliusv Thanks for the quick response and the bug filed upstream! I have subscribed to that issue as well. It may be that moving away from the URL regex is a good solution if it is a recurring problem. We'll keep an eye on how things go in https://github.com/asaskevich/govalidator/issues/150.

**Comment by juliusv** [comment]
@thedirtycolumbia Yeah, sorry about that. The workaround for now would be to use a DNS name (or even just an /etc/hosts entry) that resolves only to a v6 address. Still, we should fix this soon ourselves if govalidator doesn't do so.

**Comment by brian-brazil** [comment]
Looks like we just need to update our vendoring now.

**Comment by thedirtycolumbia** [comment]
@brian-brazil Thanks! We're looking forward to this fix.
