### ISSUE TITLE
Remote write relabelling

### ISSUE THREAD

**Issue by brian-brazil** [prometheus/prometheus#2033]
We should support relabelling on the remote write path. This goes after external labels.

**Comment by juliusv** [comment]
@brian-brazil Could you add the rationale for why this goes after external labels, especially since it's the other way around with alerts? Naively I would have thought that one wouldn't want to let the user shoot down the external labels, but who knows...

**Comment by brian-brazil** [comment]
The external labels logic is just a default, it needs to be overrideable (especially for alerts). If alert relabelling is the wrong way, around that's a bug.

**Comment by juliusv** [comment]
@brian-brazil Ok, then maybe we should change the alert relabeling order before documenting it - can we get around calling it a breaking change then? :)

**Comment by juliusv** [comment]
Of course, technically you can achieve the same either way by just not using external labels for any labels that you may want to override (and just use relabeling to set them everywhere). It's just not as convenient. But it gives external people a guarantee that anything outgoing from a given Prometheus server will *always* have the configured external labels.

**Comment by brian-brazil** [comment]
If external labels is 2nd, you can't set an external label to empty. External labels are also defaults, not overrides - if you want to make them overrides use relabelling.

**Comment by juliusv** [comment]
Don't care much either way - question is whether we consider it breaking to "fix" the way it's done in alerting currently.

**Comment by brian-brazil** [comment]
The alert relabelling feature as implemented doesn't meet the spec of the issue requesting it, so that's a bug.

**Comment by juliusv** [comment]
Phew :sweat_smile: 

For reference: https://github.com/prometheus/prometheus/issues/1744

**Comment by brian-brazil** [comment]
Also dupe of #1955
