### ISSUE TITLE
Implement HTTP API for getting all label names

### ISSUE THREAD

**Issue by juliusv** [prometheus/prometheus#2038]
Would be relevant for https://github.com/grafana/grafana/issues/6038 (cc @bergquist).

Endpoint would be:

`GET /api/v1/labels`

Output would be:

``` json
{
   "status" : "success",
   "data" : [
      "__name__",
      "job",
      "instance",
      "method",
      "status",
      "path"
   ]
}
```

This isn't a trivial change, as it requires plumbing all the way down to the storage layer and the LevelDB index accessor functions.

**Comment by opsnull** [comment]
any updating ?

**Comment by brancz** [comment]
I don't think we'll tackle this before 2.0 as LevelDB is going away completely for that and this feature would have to be rewritten entirely. @fabxc what is your stance on getting something like this into the 2.0 dev branch? However I wouldn't expect this to be too difficult with the 2.0 storage given that we are already keeping indices of labels and their values, right @fabxc ?

**Comment by fabxc** [comment]
Yea, that should be reasonably easy to do. I also want to investigate composite indices against metric names then, i.e. "what are all possible values of label `instance` for metric `requests_total`".

**Comment by juliusv** [comment]
@fabxc @Gouthamve This just came up again in a discussion with @davkal (it could be useful for the UIs he's building). Do you have any more insight into how to do this efficiently on top of the new storage? To do it properly with minimal overhead, it'd probably need a new TSDB interface function?

**Comment by Gouthamve** [comment]
So the `tsdb.Querier` already exposes it: https://github.com/prometheus/tsdb/blob/master/querier.go#L34-L35

We need to add it to the `Storage` interface I guess.

**Comment by shubheksha** [comment]
@Gouthamve, that returns all the values, not names. A new function will be needed. See https://github.com/prometheus/tsdb/issues/279

**Comment by krasi-georgiev** [comment]
the work on tsdb side is done so removed the `local storage` label.

**Comment by deeTEEcee** [comment]
Is there a way to get the list of unique label names based on the metric?
