### ISSUE TITLE
Allow exporting graphed data (as CSV?)

### ISSUE THREAD

**Issue by juliusv** [prometheus/prometheus#2039]
I've talked to people introducing Prometheus in a more traditional big company - when trying to convince deciders there that Prometheus is the right tool for them, the more Excel-type of people have been asking for simple ways to export graph data as CSV. Grafana supports some kind of graph export, but it's not ideal for their needs.

We could think about adding a query/graph data export button to the Prometheus web UI. Questions are:
- do we want that?
- what formats should it support? (I can imagine JSON and CSV being the obvious ones)
- if we do support CSV, do we want to drag in some JS dependency to be sure to get all the quoting right?

**Comment by brian-brazil** [comment]
My thoughts on this have been that there should be a tool that can run a query and output in csv. I'm not sure about it being part of the core.

**Comment by beorn7** [comment]
Yeah, I would also see this in some tool.

Put it into promtool? There is still https://github.com/prometheus/prometheus/pull/1753 . Once that is in, adding a CSV output would be straight forward.

**Comment by juliusv** [comment]
Makes sense, but wouldn't really help with the original goal: to help the Excel-type people in a more traditional company who want to have a simple UI and probably don't even know how to use the command line. Maybe that's a somewhat isolated use case though, as that's the first time I've heard about it like that too. So if we decide we don't deem that important enough to the UI, we could close this issue (or change it to add that to promtool).

**Comment by beorn7** [comment]
So you are more thinking about a "download as ..." menu on the /graph page, so that you can retrieve the result of a query you have crafted in the UI in a format of your choice?

This might be useful even for other purposes.

**Comment by juliusv** [comment]
@beorn7 Precisely.

**Comment by beorn7** [comment]
Random concern: Prometheus queries are not necessarily reproducible. To generally get _exactly_ the data displayed, you needed to export from the data already in the browser instead of re-run the query. So this might be a concern of the JS code running in the browser.

**Comment by juliusv** [comment]
@beorn7 That shouldn't be a problem, as we're already remembering the exact graph JSON for every graph in the JS and would have access to it.

**Comment by juliusv** [comment]
So just in case someone built such a button - would people be ok with having it in Prometheus?

**Comment by beorn7** [comment]
I'm pretty easy with it if it is really just something living in the UI.

**Comment by brian-brazil** [comment]
Yeah, I'm fine with it being just JS (and I can see it being handy for support). We'd probably also want to request it in Grafana.

**Comment by fabxc** [comment]
Same, as a pure UI feature, totally fine.

Generally, @grobie brought up the point, that it would be cool to have UI
as a separately developed tool, that can point to any Prometheus server. It
would just get resynced into the prometheus repo for each release as we
still want each instance to have a UI in case of emergency. This requires
full REST API coverage of course so the UI can entirely rely on it rather
than server-side generation.
This would provide clearer separation when questions come up whether we
want X to be a feature of Prometheus. We ultimately will need it anyway to
allow users/vendors to fully integrate Prometheus into their own management
panels.

**Comment by juliusv** [comment]
@fabxc Agreed to that as a mostly orthogonal thing. The REST API features are already all there, or are you talking about not just the graphing/querying interface, but all the other metadata pages as well? Anyways, probably off-topic here.

**Comment by fabxc** [comment]
Yes, we need it for status, targets, and alerts as well.

**Comment by roidelapluie** [comment]
Hi,

I have made a console template:

```
{{ $t := query "time()" | first | value }}{{ $i := 0 }}{{ range query .Params.query -}}
{{ if eq $i 0 }}time{{ range $v, $x := .Labels}}{{ if not (eq $v "__name__") }},{{$v}}{{ end }}{{ end }},value{{$i = 1}}{{ end }}
{{$t|humanizeTimestamp|safeHtml}}{{ range $v, $x := .Labels}}{{ if not (eq $v "__name__") }},{{$x}}{{ end }}{{ end }},{{.Value}}
{{- end }
```

Maybe we can add it as an example console template?

usage:

curl http://127.0.0.1:9090/consoles/query.csv?query=up

**Comment by roidelapluie** [comment]
v2 (error handling)

```
{{ $error := false }}{{ $t := query "time()" | first | value }}{{ $i := 0 }}{{ $samples := query .Params.query -}}                        
{{ $labels := ($samples | first).Labels -}}
{{ $ln := $labels | len -}}
{{ range $samples -}}
{{ $samplelabels := .Labels -}}
{{ if not (eq $ln ($samplelabels | len)) -}}{{$error = true}}# ERROR: different number of labels {{ $ln }} vs {{$samplelabels | len}}
{{end -}}
{{ range $lname, $lvalue := $labels -}}
{{ if not (index $samplelabels $lname) }}{{$error = true}}# ERROR: Extra label {{ $lname}} ({{$labels}} vs {{$samplelabels}})
{{ end -}}
{{ end -}}
{{ range $lname, $lvalue := $samplelabels -}}
{{ if not (index $labels $lname) }}{{$error = true}}# ERROR: Extra label {{ $lname}} ({{$samplelabels}} vs {{$labels}})
{{end -}}
{{ end -}}
{{ end -}}
{{ if not $error -}}
time{{ range $k, $v := $labels}}{{ if not (eq $k "__name__") }},{{$k}}{{ end }}{{ end }},value
{{- range $sample := $samples}}
{{$t|humanizeTimestamp|safeHtml}}{{ range $k, $v := $labels}}{{ if not (eq $k "__name__") }},{{index $sample.Labels $k}}{{ end }}{{ end }},{{.Value}}
{{- end }}
{{- end }}
```

**Comment by noamtamim** [comment]
@roidelapluie how is this template used? Do I install it somewhere?

**Comment by juliusv** [comment]
You can drop it as a file into your console template directory
(flag --web.console.templates="consoles").

See https://prometheus.io/docs/visualization/consoles/ - it's a bit of a
little known feature that enables you to drop in an arbitrary HTML file
with Go templating that the Prometheus server then expands and serves to
you.

**Comment by RichiH** [comment]
Decided in team triage: Will close as we have JSON now. Please poke if you disagree strongly.
