### ISSUE TITLE
compile the code left some error

### ISSUE THREAD

**Issue by jinhang** [prometheus/prometheus#2043]
**compile source code**

**to have binary file**

---
- System information:

Linux 3.11.0-12-generic i686
- Prometheus version: 

```

    GOARCH="386"
GOBIN="/usr/local/go/bin"
GOEXE=""
GOHOSTARCH="386"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/usr/local/go_workspace"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_386"
CC="gcc"
GOGCCFLAGS="-fPIC -m32 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build798007709=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
```
- Logs:

```
root@ubuntu:/usr/local/go_workspace/src/github.com/prometheus/prometheus# make all
>> formatting code
>> fetching promu
>> building binaries
make: /usr/local/go_workspace/bin/promu: Command not found
make: *** [build] Error 127
```

**Comment by jinhang** [comment]
please modify the reademe
```
$go get -u github.com/prometheus
$ mkdir -p $GOPATH/src/github.com/prometheus
$ cd $GOPATH/src/github.com/prometheus
$ git clone https://github.com/prometheus/prometheus.git
$ cd prometheus
$ make build
$ ./prometheus -config.file=your_config.yml
```

**Comment by grobie** [comment]
@jinhang `go get` should not be necessary, the "fetching promu" state should have installed promu correctly. Can you report the output of `uname -m` please.

**Comment by jinhang** [comment]
`Linux 3.11.0-12-generic i686 ` I have compiled successed

**Comment by juliusv** [comment]
@jinhang All good then? Can this issue be closed?

**Comment by jinhang** [comment]
hi,morning, when I want to modify the `https://github.com/prometheus/prometheus/blob/master/web/ui/templates/_base.html` file, then try to compile, some error leave to me
![image](https://cloud.githubusercontent.com/assets/4497831/19592883/5ce3139a-97b0-11e6-9ea7-9f6907759a5b.png)

**Comment by jinhang** [comment]
could you give me some advice how to solve this question, I only want to modify the prometheus web UI ,thanks a lot, brother
