### ISSUE TITLE
avg() doesn't work with range selector []

### ISSUE THREAD

**Issue by zxwing** [prometheus/prometheus#2048]
I use avg() as below expression:

```
avg(collectd:collectd_virt_memory{virt="ca9718fac1014adeb605c9d72ae81617",type="rss",hostUuid="a456ba03d5944397b76fd8f2dbf9fceb"}[1h])
```

but get the error:
```
Error executing query: parse error at char 135: expected type vector in aggregation expression, got matrix
```

what is the right way to use it? The document doesn't give any example. From my understanding `[]` is the only range selector

**Comment by brian-brazil** [comment]
You want `avg_over_time`

**Comment by zxwing** [comment]
@brian-brazil I see, thanks !

**Comment by redbaron** [comment]
@zxwing, just a note - AFAIK you'll have bad time if you let metrics cardinality grow uncapped. random container names as metrics value is essentially uncapped growth
