### ISSUE TITLE
Don't filter the instance label in the targets page

### ISSUE THREAD

**Issue by grobie** [prometheus/prometheus#2061]
At least when relabeling is used to set the `instance` label (see http://www.robustperception.io/controlling-the-instance-label/) we should not filter the `instance` label from the targets page overview. Any objections to just always show it?

https://github.com/prometheus/prometheus/blob/05d3d6d9f72ad02ec27077f2686b4b17d76b9f76/web/ui/templates/targets.html#L36

**Comment by brian-brazil** [comment]
Agreed, lets always show it.
