### ISSUE TITLE
about "prometheus/web/ui/"?

### ISSUE THREAD

**Issue by jinhang** [prometheus/prometheus#2067]
**I want to have alert name to display.**

**how to display alert name**

**Comment by juliusv** [comment]
An alert name may be displayed in a variety of contexts. For example, you can see the alert names on the `/alerts` page of a Prometheus server.

Coud you be more specific about what you want?

**Comment by jinhang** [comment]
I want to display alertname to user,and user can eidt send email path

**Comment by juliusv** [comment]
Sorry, from those few words I'm having trouble understanding what it is exactly that you want... we would need a longer, clearer description of the problem to be able to respond in a meaningful way.
