### ISSUE TITLE
Fetch etcd members list using only one etcd endpoint/proxy address

### ISSUE THREAD

**Issue by kayrus** [prometheus/prometheus#2076]
My goal is to configure only one or two etcd proxy/endpoints and Prometheus will get the whole cluster information from "https://172.16.0.1:2379/v2/members"

This will allow dynamically monitor etcd cluster independently on etcd members IP addresses.

**Comment by brian-brazil** [comment]
I don't think this is something we'd add to Prometheus, as like in #2036 you're proposing an SD mechanism that only discovers the cluster itself.

In reality you should have some other service/machine database with this information which would make a better SD choice.
