### ISSUE TITLE
Graphite remote-storage in Prometheus

### ISSUE THREAD

**Issue by zybjcdl** [prometheus/prometheus#2083]
Hi all:

Our current monitoring system is using collectd+graphite+seyren+pagerduty structure.

Now the service will be changed to delivered in kubernetes. So we want to use prometheus as the monitoring system.

But we still want to use graphite + seyren+ pagerduty system to keep the monitoring system consistent as before.

So I wondered instead of using prometheus + alertmanager

Could we get the data from prometheus ,and put it to graphite? That will be prometheus + graphite + seyren+ pagerduty.

I see from here
https://github.com/prometheus/prometheus/blob/b66ce9c5cd4a0cc624d9d29da9c6733d1236f382/CHANGELOG.md

There is one feature in 2016-01-18:

0.16.2 / 2016-01-18

- [FEATURE] Add Graphite remote-storage integration

Does that mean we could store prometheus data into graphite?

If so, how could we use this feature?

Please help! Thank you so much!

**Comment by dominikschulz** [comment]
Looking at the [code](https://github.com/prometheus/prometheus/blob/master/cmd/prometheus/config.go) I'd say it should be as easy as running Prometheus with these options:
`-storage.local.engine=none -storage.remote.graphite-address=graphiteHost:graphitePort`.

This will completely disable local prometheus storage. If you still want local storage for e.g. queries you can omit the storage.loal.engine option.

**Comment by zybjcdl** [comment]
Thanks dominikschulz. it works.

**Comment by zybjcdl** [comment]
@dominikschulz One more question. Is there any limitation on this option? 
I find when the graphite is in the same cluster as prometheus, this option works.
But if the graphite is in another cluster, this option doesn't work.

**Comment by brian-brazil** [comment]
There shouldn't be any such limit.

**Comment by infa-ddeore** [comment]
`-storage.local.engine=none` is removed in 2.x versions, seems there is no alternate option in 2.x
