### ISSUE TITLE
Remote write config not guarded by experimental section

### ISSUE THREAD

**Issue by fabxc** [prometheus/prometheus#2086]
Did I miss a discussion where we agreed that it is stable now? Especially with the ongoing discussion around wire format.

@juliusv @brian-brazil

**Comment by brian-brazil** [comment]
This was discussed, and as with everything else it's clearly mentioned in the docs.

**Comment by fabxc** [comment]
Generally fine with me as its documented. Just started post-vacation catchup and only found: https://github.com/prometheus/docs/pull/599

Was there any other discussion around this?

**Comment by brian-brazil** [comment]
Julius and I had a discussion when the config was added.
