### ISSUE TITLE
Wrong storage engine flag value

### ISSUE THREAD

**Issue by fabxc** [prometheus/prometheus#2087]
When we discussed a boolean enable/disable flag for local storage, we decided to have an `engine` string flag instead, which allows `disabled` as well as any custom engine people want.
However, the default value for the current local storage engine ended up being `persistet`, which is equivalent to a boolean flag again.

Anyway, changing it would be breaking, so we have to live with it.
Issue just helps tracking for >1.0.

@juliusv

**Comment by fabxc** [comment]
I suggest moving everything to `-storage.tsdb.*`. That's mostly done aside from `-storage.local.path` I think.

Do we really need a persistence-disabled mode for tsdb?
It came up before and I just suggested to point Prometheus to tmpdir and set retention == block size. We can even optimize that to drop in-memory blocks before their initial compaction if they are already behind the retention.

**Comment by brian-brazil** [comment]
I've never seen much use for persistence disabled, the use case always really seems to be for a very short retention period.

**Comment by Gouthamve** [comment]
So, I saw that with none, we have a `noopStorage` which doesn't ingest anything and returns empty values.

Implementing the noopStorage is straight-forward but I think it should ideally be done after #2850 We could remove the flag now and add it when noopStorage is added.

**Comment by fabxc** [comment]
This is gone for now. Pointing TSDB at tmpfs should work just fine. Truly preventing any file from being written has no strong enough performance benefit that'd be worth the effort right now.

**Comment by grobie** [comment]
I guess the argument would be more ease of use, but I agree that there are
more important things.

**Comment by juliusv** [comment]
Would still be nice to be able to use Prometheus as a pure remote reader/writer. Otherwise one has to think how large a block on disk can get and how much memory it will consume... although all one wants to do is forward / read back samples. I mean, I'm not actively working on Cortex anymore, but think the idea is nice in general.

**Comment by fabxc** [comment]
@juliusv yea, I see no problem adding it back once someone comes claims a need for it. But since we stirred up all the flags anyway, I don't see it as a hard 2.0 requirement. 

One might even argue that this is more of a use case for the component disaggregation you started a discussion on a while ago. A forward-only mode should possibly rather be a sub-command that's explicit about the remaining functionality rather than just disabling the storage and being left with all query and rule APIs still enabled but non-functional.
Then you can just assemble your necessary components together in another `main.go` instead of accommodating different use cases into a single one.

**Comment by fabxc** [comment]
Though for the user it would be a straightforward thing to do. Instead of:

```
prometheus --storage.tsdb.disabled --config.file=abc.yml
```

you just say

```
prometheus forward --config.file=abc.yml
```

**Comment by juliusv** [comment]
@fabxc That sounds good in general, though I wonder what that approach would look like if you still do want the querying (like when you use it for remote write *and* read). For that kind of thing, it'd be easier to specifically just turn the local storage off. But I also think it's ok to start 2.x without this and add it later. Better than adding something half-thought-out now that we can't break later.

**Comment by fabxc** [comment]
Right, good point. Let's look into this again later then. Will remove it from the milestone for now.
