### ISSUE TITLE
Node_exporter can not be curled by "curl" command.

### ISSUE THREAD

**Issue by tacit-boy** [prometheus/prometheus#2089]
**What did you do?**
I want to see metrics.
**What did you expect to see?**
A lot of metrics
**What did you see instead? Under which circumstances?**
When i used "curl http://<My ip>:9881/metrics" , there is a error.

An error has occurred:
expected summary in metric go_gc_duration_seconds label:<name:"quantile" value:"0" > untyped:<value:0.000275082 > 

**Environment**
ubuntu 14.04
- System information:

Linux 4.2.0-27-generic x86_64

Node_exporter's logs is normal.
I do not know what to do.

**Comment by brian-brazil** [comment]
If this is still happening, please file as a bug against the node exporter.
