### ISSUE TITLE
All the k8s related metrics

### ISSUE THREAD

**Issue by zybjcdl** [prometheus/prometheus#2114]
Hi.
I want to find the document about all the k8s metrics and the instruction of the metrics , which prometheus could collect.

Is there a document about that?

**Comment by dominikschulz** [comment]
I'm not sure if I understand your question correctly, but maybe this link helps you: http://stackoverflow.com/questions/39366111/how-to-alert-on-the-kubernetes-cluster-health

**Comment by matthiasr** [comment]
There is not a good comprehensive overview (at least as far as I know) and there is still a lot of movement happening in this space.

As a starting point, take a look at [cAdvisor](https://github.com/google/cadvisor), these are the container metrics exported by the kubelet.

For metrics about the state of Kubernetes objects, there is [kube-state-metrics](https://github.com/kubernetes/kube-state-metrics) (warning: metrics there are still changing a lot).

I'm not sure if there is any detailed documentation on the metrics from the Kubernetes components themselves, but generally I just open their metrics page and look at what's there and the help strings; most of them are pretty self explanatory.

**Comment by zybjcdl** [comment]
Thanks @dominikschulz @matthiasr for your help.
To summary, there are following kind of metrics for k8s.
1)Kubelet metrics:
https://godoc.org/k8s.io/kubernetes/pkg/kubelet/metrics
2)container metrics:
https://github.com/google/cadvisor/blob/master/metrics/testdata/prometheus_metrics
3)API servers: Not sure where the detailed instruction is.
4)kube-state-metrics
https://github.com/kubernetes/kube-state-metrics

If there are anything more, please let me know. Thanks!

**Comment by fabxc** [comment]
You can also take a look at: 

https://github.com/coreos/kube-prometheus
https://github.com/coreos/prometheus-operator

I gave a talk on both. Slides are here but missing explanation of course. Videos from the KubeCon talk should be available eventually:

https://speakerdeck.com/fabxc/monitoring-kubernetes-clusters-with-prometheus

I think with the previous answers, this sums up all the resources there are.
