### ISSUE TITLE
Have a drop_common_labels() in the graph UI

### ISSUE THREAD

**Issue by EdSchouten** [prometheus/prometheus#2118]
While experimenting with queries, root-causing problems, etc. etc. etc. I often find myself adding `drop_common_labels()` around an existing query, because the key shown below the graph is too cluttered.

Would it be possible to have some short-hand feature for this? For example, having a checkbox next to the graph. When clicked, the query doesn't need to be re-executed, but the key below the graph is updated to no longer include common labels. The common labels may still be showed once below the graph, so the information is not lost.

**Comment by juliusv** [comment]
We (Prometheus team) just had a bug scrub call and decided to close this, as this hasn't come up regularly and is likely not something we want to support in the built-in UI at this point.
