### ISSUE TITLE
OpenShift Pod Service Discovery for restricted serviceaccount

### ISSUE THREAD

**Issue by nsams** [prometheus/prometheus#2127]
Kubernetes SD uses the /api/v1/pods API to get a list of all pods in the cluster.

When using OpenShift with a restricted serviceaccount that can only access configured namespaces this API isn't allowed, instead you can:

- get a list of projects `/oapi/v1/projects`
- get pods for a every project (=namespace in k8s) `/api/v1/namespaces/example/pods`

This would allow using prometheus in such a environment where you don't have access to the whole cluster.

**Comment by brian-brazil** [comment]
Dupe of #1951
