### ISSUE TITLE
Support calculating max rate over time

### ISSUE THREAD

**Issue by bobrik** [prometheus/prometheus#2129]
**What did you do?**

I have a metric that is a counter (cpu time). I want to calculate max 5m rate over the last 1d to get the estimate max sustained cpu usage for my thing for capacity planning reasons. Turns out, I can't construct such expression. I can only construct "5m rate over the last 1d" part with:

```
rate(cadvisor_container_cpu_user_seconds_total{marathon_app_id="/foo/bar"}[5m])
```

* Prometheus version: 

```
prometheus, version 1.2.1 (branch: master, revision: 05b140e6b2da83e1315518eadd9be7f185adb998)
  build user:       vagrant@53206eae2e4e
  build date:       20161013-14:14:23
  go version:       go1.7.1
```

**Comment by brian-brazil** [comment]
You need to create a recording rule for the rate, and then use max_over_time on that.

**Comment by bobrik** [comment]
@brian-brazil I am probably doing it wrong, but it doesn't make any difference.

### Without any rules

Query:

```
max_over_time(rate(cadvisor_container_cpu_user_seconds_total{marathon_app_id=~"/foo/.+"}[5m]))
```

Gives:

```
Error executing query: parse error at char 95: expected type matrix in call to function "max_over_time", got vector
```

### With rule

Used rule:

```
cadvisor:cpu_user:rate = rate(cadvisor_container_cpu_user_seconds_total{marathon_app_id=~".+"}[3m])
```

Query with that rule:

```
max_over_time(cadvisor:cpu_user:rate{marathon_app_id=~"/foo/.+"})
```

Gives:

```
Error executing query: parse error at char 66: expected type matrix in call to function "max_over_time", got vector
```

Even if it should only work with the rule, I think it's worth mentioning that in docs with explanation. It doesn't seem obvious, at least for me.

**Comment by mattbostock** [comment]
Does the following work?
      max_over_time(cadvisor:cpu_user:rate{marathon_app_id=~"/foo/.+"}[5m])

**Comment by bobrik** [comment]
@mattbostock that did the trick.

**Comment by donghwicha** [comment]
Is this still valid? I tried but it fails to gather values 
max_over_time(cadvisor:cpu_user:rate{my_cont_id=~"/foo/.+"})
