### ISSUE TITLE
How can I retrieve a set of metrics

### ISSUE THREAD

**Issue by mqliang** [prometheus/prometheus#2161]
I use prometheus to collect monitoring information for kubernetes. And my profiling tool need to retrieve metrics for a set of pod, for example: all "container_cpu_usage_seconds_total" metrics with labels "kubernetes_pod_name=foo" or "kubernetes_pod_name=bar".

Is there anyway I can retrieve all the metrics I need with only one request?

**Comment by tlex** [comment]
You could use regex:
```
container_cpu_usage_seconds_total{kubernetes_pod_name=~"(foo|bar).*"}
```
the [=~](https://prometheus.io/docs/querying/basics/#instant-vector-selectors) selector announces that a regex follows

The second option would be the [or](https://prometheus.io/docs/querying/operators/#logical-set-binary-operators) operator (allows to get not only the same metric with different labels, but also different metrics all together):
```
container_cpu_usage_seconds_total{kubernetes_pod_name="foo"} or container_cpu_usage_seconds_total{kubernetes_pod_name="bar"}
```
