### ISSUE TITLE
Why can't {} be used to match every metric?

### ISSUE THREAD

**Issue by EdSchouten** [prometheus/prometheus#2162]
I've noticed that Prometheus contains some smartness that prevents you from running queries that match every metric. For example, running the query `{}` prints the following error:

```
Error executing query: parse error at char 2: vector selector must contain label matchers or metric name
```

Let's add some smartness to work around this by running `{__name__=~".*"}`:

```
Error executing query: parse error at char 16: vector selector must contain at least one non-empty matcher
```

You could ask yourself: why would you want to run a query that matches every metric? Well, I just want to get a rough idea of the number of metrics our Prometheus setup stores by job. Ideally I'd just want to run `count({}) by (job)`, but now I'm forced to use workarounds like `count({__name__=~"..*"}) by (job)` (notice the `..*`).

**Comment by brian-brazil** [comment]
This is on purpose to reduce the chances of users accidentally hosing their Prometheus, as it's very easy to end up with such an expression while playing around.

**Comment by mprasil** [comment]
@EdSchouten use "`.+`" if you find "`..*`" too hack-ish.
