### ISSUE TITLE
Feature request: Load rule files from directory

### ISSUE THREAD

**Issue by maratkalibek** [prometheus/prometheus#2176]
Hello!
can you consider option of loading alert rule files from directory, not specifying them one by one in configuration.

This can help:
1. if there is a lot of alert rules. storing them in big files can be tricky.
1. if rule files automatically generated.

**Comment by brancz** [comment]
That feature is already supported 🙂 you can [load rule files via a file glob](https://prometheus.io/docs/operating/configuration/#configuration-file).

**Comment by maratkalibek** [comment]
thanks for info!
