### ISSUE TITLE
Auto set memory-chunk base on the available free memory detected

### ISSUE THREAD

**Issue by netroby** [prometheus/prometheus#2188]
We know we can using golang runtime package to get memstats information. so we know the free memory available.
```
https://golang.org/pkg/runtime/
```
Now the default ```storage.local.memory-chunks``` be 1024*1024. It not good if the installed target machine have not enough memory. like a VM with only 512MB memory.

https://github.com/prometheus/prometheus/blob/6703404cb431f57ca4c5097bc2762438d3c1968e/cmd/prometheus/config.go#L117

So would we please add the auto detected memory? 
We should not using more then 85% availble free memory. or we will got OOM .

**Comment by songjiayang** [comment]
👍

**Comment by beorn7** [comment]
This is less trivial than suggested here.
In any case, what you want will be implemented as a solution of #455 .
