### ISSUE TITLE
Make "range vector" and "matrix" terminology consistent

### ISSUE THREAD

**Issue by tcolgate** [prometheus/prometheus#2196]
**What did you do?**

make an error in a query where a function expects a range vector, but you just give it an instant vector

**What did you expect to see?**

An error that refers to requiring a range vector

**What did you see instead? Under which circumstances?**

An error that refers to a "matrix"

The documentation doesn't really ever refer to Prometheus supporting a "matrix" type, but the errors do. Equally, some errors state that a "vector" has been required where a "matrix" is expected, yet the docs refer to instant vectors and range vectors (so both are vectors, by the wording in the docs).

It would be nice if the terminology was consistent between the two.

**Comment by tcolgate** [comment]
I can look at updating some error messages. I think replacing "vector" with "instant vector", and "matrix" with "range vector", would be OK?

**Comment by beorn7** [comment]
That touches ancient Prometheus history, so I'd say @juliusv should comment on it.

**Comment by brian-brazil** [comment]
Renaming as you suggest makes sense. The older terminology is a holdover from Borgmon.

**Comment by juliusv** [comment]
We also call it matrix / vector in the API though: https://prometheus.io/docs/querying/api/#expression-query-result-formats

So the inconsistency there would have to remain unfortunately.

**Comment by tcolgate** [comment]
Initial attempt in #2197 
I don't think the type names in  common/model  can realistically be changed, so this attempt to translate it purely for the purposes of messages reported to the users.
I could use  a type, with a String() method, but that seemed like overkill
Some tests still failing, just wanted to see if this was sane.

**Comment by tcolgate** [comment]
#2197 was merged
