### ISSUE TITLE
Newbie Question: count

### ISSUE THREAD

**Issue by hardcoar** [prometheus/prometheus#2198]
quick question: what's the difference between histogram's ```<basename_count>``` vs ```count``` metric?

i would really like to use prometheus in k8s and i want to start small. if it's the same i would use histograms instead (to conserve resources) or if it's negligible i'll use both for specifics. please help me and thanks in advance!

**Comment by juliusv** [comment]
I'm not sure what you mean with `count` metric, but I assume you mean a metric of type Counter (vs. type Histogram). The `<basename>_count` series that is outputted as part of a histogram in fact is a counter, so you don't need to define an extra counter metric to just count the observed events as well, you get it for free with the histogram. So yes, if you mean that, you can omit the extra counter metric.

**Comment by juliusv** [comment]
Hoping that answered the question and closing here - please reopen if not (but better to use the users mailing list for questions like this, as it's not an issue). See https://prometheus.io/community/.

**Comment by hardcoar** [comment]
@juliusv awesome. thanks! i will next time.
