### ISSUE TITLE
Support port for "node" role under "kubernetes_sd_config"

### ISSUE THREAD

**Issue by aerokite** [prometheus/prometheus#2199]
*The node role discovers one target per cluster node with the address defaulting to the Kubelet's HTTP port.*

If I have another service running on each node directly and exposes metrics on a particular port, what should I do?

If *node* role supports port, I can create another job to collect metrics with that port. 

    - job_name: 'kubernetes-node-metrics'
      kubernetes_sd_configs:
      - role: node
      port: 10240

Suppose, I have a service running on each node exposing metrics on port 10240. I can collect using your existing *node* role if you support port for **kubernetes_sd_config**.

**Comment by fabxc** [comment]
Generally, you would discover this with the `endpoints` discovery, which
doesn't care about on which node the endpoints run. The underlying
DaemonSet just makes it that way.
