### ISSUE TITLE
Reserve ports for GitLab CE/EE and GitLab runner exporters

### ISSUE THREAD

**Issue by maratkalibek** [prometheus/prometheus#2211]
Hello, please can you add to [port allocation page](https://github.com/prometheus/prometheus/wiki/Default-port-allocations) in wiki following two ports:

* 9401 - GitLab CE/EE
* 9402 - GitLab runner

Thanks in advance

**Comment by brian-brazil** [comment]
The wiki is world writable, you should be able to do this yourself. 9173 and 9174 are the next free consecutive ports.
