### ISSUE TITLE
prometheus server crash problem

### ISSUE THREAD

**Issue by jinhang** [prometheus/prometheus#2216]
* System information:

	window7

* Prometheus version: 

1.2.3

* Prometheus configuration file:
```

```

![image](https://cloud.githubusercontent.com/assets/4497831/20587754/fdc818be-b24a-11e6-92bf-9c03f5b82aca.png)

**Comment by brian-brazil** [comment]
Can you please provide the full crash log? We can't tell anything from this.

**Comment by jinhang** [comment]
![image](https://cloud.githubusercontent.com/assets/4497831/20588567/1c8437fa-b251-11e6-856f-111c242e71a9.png)
![image](https://cloud.githubusercontent.com/assets/4497831/20588572/2c8bdc3e-b251-11e6-8c8b-484ad994fa3f.png)

**Comment by brian-brazil** [comment]
That does not show any evidence of a crash. Please post the full text dump.

**Comment by jinhang** [comment]
when I restart:
`
time="2016-11-24T14:24:02+08:00" level=info msg="Loading series map and head chunks..." source="storage.go:354" 
time="2016-11-24T14:24:02+08:00" level=warning msg="Persistence layer appears dirty." source="persistence.go:712" 
time="2016-11-24T14:24:02+08:00" level=warning msg="Starting crash recovery. Prometheus is inoperational until complete." source="crashrecovery.go:40" 
time="2016-11-24T14:24:02+08:00" level=warning msg="To avoid crash recovery in the future, shut down Prometheus with SIGTERM or a HTTP POST to /-/quit." source="crashrecovery.go:41" 
time="2016-11-24T14:24:02+08:00" level=info msg="Scanning files." source="crashrecovery.go:55" 
`

**Comment by jinhang** [comment]
time="2016-11-24T14:29:06+08:00" level=info msg="Done checkpointing in-memory metrics and chunks in 2.847s." source="persistence.go:573"

**Comment by jinhang** [comment]
this problem full log is miss .only see
![image](https://cloud.githubusercontent.com/assets/4497831/20588791/e465c602-b252-11e6-9bea-e2bff8dc45ea.png)

**Comment by grobie** [comment]
Closing as crash log is still missing. If you have a complete crash log, paste it here (no images) and feel free to open again.
