### ISSUE TITLE
Why not to use shared memory for in RAM DB

### ISSUE THREAD

**Issue by onorua** [prometheus/prometheus#2225]
#### The problem
As soon as we increased memory to around 32GB+, we noticed quite a big startup time due to journals restoration, even we have sent TERM signal properly and waited for normal shutdown. Startup takes couple of minutes (up to 10 actually), which is noticeable on graphs. 
That is because prometheus is trying to get all the data are to be in RAM into memory.

#### shared memory proposal
it is possible to attach shared memory from another process, which will speedup the startup time, because you will not need to load journals from disk to RAM, but rather attach already available memory. 
This will require checks for data consistency on startup of course and fallback to the current restoration from journals.

What do you think about this functionality?

**Comment by beorn7** [comment]
I'd expect this to require a lot of effort to get right, and then additional operational effort to run. And it only covers a relatively rare corner case (i.e. where a SIGHUP is not enough but it's not a complete restart of the machine/container running Prometheus).
