### ISSUE TITLE
Is there any plan for prometheus to support string type metrics?

### ISSUE THREAD

**Issue by aaskey** [prometheus/prometheus#2227]
Currently prometheus metrics types include counter, gauge, histogram, and summary. They are all numeric types. I would like to see if prometheus can support string type metrics. For example, to report system state in "start", "running", "pause", "bypass", "stop", or sometimes, arbitrary string message, then apply aggregation functions to the values.  Is there any way to do it now? If not, is there plan to support it?

**Comment by brian-brazil** [comment]
There's no plans to support non-numeric values. However you can put strings into labels.

Arbitrary string messages are usually bad idea, as each value will be a new time series which will run you into performance issues.

**Comment by aaskey** [comment]
Hi Brian, you mean it is a bad idea to use arbitrary string message as labels? That's also one of the reasons I am hesitate using that way.

**Comment by brian-brazil** [comment]
Yes. If you're looking for that you probably want an event logging solution, such as ELK.

**Comment by aaskey** [comment]
ELK is a very capable logging solution. I am trying to see if I can use one stack to satisfy my application requirements. Is there any specific reason not supporting string metrics type?

**Comment by brian-brazil** [comment]
Strings aren't metrics.

**Comment by matthiasr** [comment]
Storing strings would require a complete new storage schema and is
fundamentally different from storing time series of numbers. Prometheus'
storage efficiency heavily relies on this uniformity.

As for your original use case, there are a few ways to represent this as
metrics provided the number of states is bounded (not arbitrary!). The
simplest one would be to just map states to some integer values. You can
for example count_by_value or alert on that pretty easily.

**Comment by aaskey** [comment]
Got it. Thank Brian and Matthias.
