### ISSUE TITLE
prometheus_local_storage_memory_series increasing too fast 

### ISSUE THREAD

**Issue by ton31337** [prometheus/prometheus#2231]
As you can see in this graph, this is increasing too fast..

![screen shot 2016-11-28 at 17 51 41](https://cloud.githubusercontent.com/assets/3352707/20675162/0407f7fc-b594-11e6-9e05-412b938addca.png)

Are there any ways to figure out which exporter is exposing too much metrics?

**Comment by brian-brazil** [comment]
If you're running a recent build `scrape_samples_scraped` will help you.
