### ISSUE TITLE
[RFC] metric relabelling support for dropping labels

### ISSUE THREAD

**Issue by tcolgate** [prometheus/prometheus#2233]
I'm working with cadvisor, and importing some environment variables in from containers (to get mesos task ID and marathon app id, but it could be anything). These result in rather unpleasant labels (container_env_mesos_task_id).
  Later I need to make this against a mesos_task_id label coming from elsewhere, so have elected to rename this label in metric relabeling.
  Ideally there would be an easy way to bulk remove all container_env_ labels. Currently the only option is to explicitly replace the labels by name.
  Possible solutions could be:

- Support stripping out of `__label_name` labels, as it done in target relabelling (then I can teach cadvisor to expose them with the `__` prefix
- Provide additional actions that drop labels matching a pattern (labeldrop/labelkeep) 

My personal preference would be for the former, since it matches the target relabelling behaviour. Though that behaviour could actually be implemented with a labeldrop action anyway.

**Comment by beorn7** [comment]
Just for anecdotal evidence: We have a very similar need (and solved it, as so often, on the level of config management, i.e. a Ruby loop in a Chef recipe creates all the individual label replacement rules).

**Comment by tcolgate** [comment]
One more thought.
Stripping __ would imply checking every label name on every scraped metric.
labeldrop/labelkeep would only be invoked if they are included in a set of relabelling rules.
The latter seems preferable.

**Comment by tcolgate** [comment]
Attempted in #2279

**Comment by tcolgate** [comment]
Closed by #2279
