### ISSUE TITLE
If I want to change the Prometheus Command-Line Flags.

### ISSUE THREAD

**Issue by barnettZQG** [prometheus/prometheus#2236]
If I want to change the Prometheus Command-Line Flags when prometheus is running.
Example: -storage.local.memory-chunks  or alertmanager.url ...
Now,I only restart the running prometheus. But it is a time-consuming operation.I have to wait for Prometheus program to a full stop to start a new.
Do not know to have a better way to let me complete the need to modify the prometheus flags.
```
func KillPrometheus() error {
	if prometheusCMD.Process != nil {
		err := prometheusCMD.Process.Signal(os.Interrupt)
		if err != nil {
			yiyun.Error("Kill Prometheus Process Error.", err.Error())
			return err
		}
		yiyun.Info("Killed old prometheus server")
	} else {
		yiyun.Info("prometheus process is nil")
	}
	return nil
}
```

**Comment by fabxc** [comment]
All configuration options provided through flags are fixed and can only be changed by restarting Prometheus.

To configure Alertmanagers, we added a section to the config file in our 1.4 release. You can now use the same service discovery mechanisms you can use for targets: https://prometheus.io/docs/operating/configuration/#<alertmanager_config>
Changes to the configuration file can be applied at runtime by hitting the `/-/reload` endpoint or sending a `SIGHUP` to the process.

The `-alertmanager.url` flag is only around for backwards compatibility.  
That said, currently the file based configuration is still flagged as alpha but is unlikely to change.

**Comment by barnettZQG** [comment]
I see.
