### ISSUE TITLE
Find a bug and can not build the prometheus code.

### ISSUE THREAD

**Issue by barnettZQG** [prometheus/prometheus#2239]
error message:
```
github.com/prometheus/prometheus/storage/local/mapper.go:70: m.mappingsCounter.Set undefined (type prometheus.Counter has no field or method Set)
```
error code:
```
m.mappingsCounter.Set(float64(len(m.mappings)))
```
reasons：

https://github.com/prometheus/client_golang/commit/2fee50beaa152342e8347c41edf2202c3bd5f858

This commit delete the `Set` method.may be the correct code is:
```
m.mappingsCounter.Add(float64(len(m.mappings)))
```

**Comment by beorn7** [comment]
You are building Prometheus against the head of https://github.com/prometheus/client_golang . However, Prometheus is supposed to be built against the vendored dependencies.

It's on my TODO list to adjust the current code to the head of https://github.com/prometheus/client_golang , but this will also go along with an update of the vendoring. So _always_ build with the vendored dependencies (which is automatic with Go 1.7, you really have to delete the `vendor` directory to avoid it.
