### ISSUE TITLE
SIGPIPE killed prometheus and alertmanager (journald restart)

### ISSUE THREAD

**Issue by joker234** [prometheus/prometheus#2241]
**What did you do?**
restarted systemd-journald.service

**What did you expect to see?**
prometheus should not bei killed

**What did you see instead? Under which circumstances?**
prometheus was killed, after I restarted the above service. Only prometheus, alertmanager, grafana and the [prometheus mailexporter](https://github.com/cherti/mailexporter) were killed on different servers.

**Environment**

* System information:

Linux 3.16.0-4-amd64 x86_64

* Prometheus version: 

prometheus, version 0.20.0 (branch: master, revision: f8bb0ee)
  build user:       johannes@local
  build date:       20160710-00:19:46
  go version:       go1.6.2

* Alertmanager version:

alertmanager, version 0.3.0 (branch: master, revision: d263b7ab9aa8ae6213b45ba3c959d02c9600955c)
  build user:       johannes@local
  build date:       20160905-16:00:39
  go version:       go1.7

* Prometheus configuration file:
I think this is not relevant.

* Alertmanager configuration file:
I think this is not relevant.

* Logs:
```
Dec 01 17:54:40 hostname systemd[1]: prometheus.service holdoff time over, scheduling restart.
Dec 01 17:54:40 hostname systemd[1]: Stopping Prometheus Server Instance...
Dec 01 17:54:40 hostname systemd[1]: Starting Prometheus Server Instance...
Dec 01 17:54:40 hostname systemd[1]: Started Prometheus Server Instance.
```
```
Dec 01 18:03:35 hostname systemd[1]: Starting Prometheus Alertmanager Server Instance...
Dec 01 18:03:35 hostname systemd[1]: Started Prometheus Alertmanager Server Instance.
```

The difference between prometheus.service and prometheus-alertmanager.service is, that the following option is set in the prometheus config file:
```
Restart=always
```

**Comment by grobie** [comment]
Can't reproduce. Please reopen if you have evidence this is a bug in Prometheus.
