### ISSUE TITLE
ec2_sd_config IAM roles support

### ISSUE THREAD

**Issue by loky9000** [prometheus/prometheus#2244]
Is there are possibility to use AWS IAM roles in ec2_sd_config?
I test prometheus stack in docker (prom/prometheus:latest)
My aws user has no direct access to resources only through switch to correct  IAM role so 
i got 
UnauthorizedOperation: You are not authorized to perform this operation.\n\tstatus code: 403
when access_key and  secret_key params is set

i try set profile property (profile configured on docker host in ~/.aws/config so unclear how it can be used from inside prometheus container, if it should be mounted is unclear the target for this mount)
- job_name: 'aws_test'
     tls_config:
      insecure_skip_verify: true
     ec2_sd_configs:
      - region: 'eu-east-1'
         profile: "test-profile"
    relabel_configs:
      - source_labels: [__meta_ec2_tag_Name]
         regex: dmz-haproxy*
         action: keep
        # Use the instance ID as the instance label
      - source_labels: [__meta_ec2_instance_id]
         target_label: instance
but got the error
"Error loading config: couldn't load configuration (-config.file=/etc/prometheus/prometheus.yml): unknown fields in ec2_sd_config: profile" source="main.go:149"

**Comment by brian-brazil** [comment]
It should just work out of the box.

**Comment by loky9000** [comment]
Run successfully with profile: parameter after pull fresh prom/prometheus:latest
but there are couple issues after update:
- AWS nodes doesn't show in Targets(Unclear is prometheus able to get nodes from AWS or not, nothing in logs about it)
- Expression browser doesn't show on /graph path anymore 
https://www.dropbox.com/s/2kf7q92rfqrfini/Screenshot%202016-12-03%2011.50.19.png?dl=0
- Prometheus container run with '-log.level=debug' property but  show log level info on /flags 
https://www.dropbox.com/s/anse9qrsva7r80j/Screenshot%202016-12-03%2011.55.45.png?dl=0

**Comment by loky9000** [comment]
So where is role_arn should be set?

**Comment by loky9000** [comment]
Looks like 'profile' parameter for ec2_sd_config not works or ignored for some reason

**Comment by rlees85** [comment]
I also cannot get prometheus to work with an IAM role. This is the error I get from trying to do so on an ec2 instance with the correct IAM role attached to it:

```
time="2017-01-31T16:49:48Z" level=error msg="could not describe instances: EnvAccessKeyNotFound: AWS_ACCESS_KEY_ID or AWS_ACCESS_KEY not found in environment" source="ec2.go:81" 
```

It seems like it is not even trying because the access key value is not set.

**Comment by vacri** [comment]
@rlees what version is it working for you on? I'm using 1.5.0 from the debian/sid apt repo (built 20170126) and getting the EnvAccessKeyNotFound error, despite having a valid role on the instance. Just wondering if I need to build my own even newer version, or if it's something else.

**Comment by rlees85** [comment]
@vacri it was 1.5.2 from the Prometheus homepage: https://prometheus.io/download/

It was a case of manually extracting the file and finding a suitable systemd unit. I think I used this one:

https://askubuntu.com/questions/818514/how-do-i-install-the-latest-version-of-prometheus-on-16-04

(Last post in the thread, NOT the unit for node-exporter)

Make sure you change the path in `ExecStart` to match the version and path you extracted.

**Comment by vacri** [comment]
thanks @rlees85, I'll check it out!
