### ISSUE TITLE
Question: Prometheus has no api of alert configration ?

### ISSUE THREAD

**Issue by xiaoping378** [prometheus/prometheus#2250]
Hi,
Now, this project has no alert api of configration, right?
I want to integrate it into another system, using a customed graph to config the alert.
any idea about to implement this ?

**Comment by brian-brazil** [comment]
Alerts are configured via rules files, you can build a system on top of that. See https://prometheus.io/docs/alerting/rules/

**Comment by xiaoping378** [comment]
Thanks, Got it.
I will build a restful server which handle my custom url, then convert the request to alert-rules.
