### ISSUE TITLE
suggested feature: mobile client

### ISSUE THREAD

**Issue by joeblew99** [prometheus/prometheus#2251]
I am needing to be metrics (and logging) from Mobiles into Prom.
SO, i am raising it here to get feedback. to i am not repeating others work.

Here is a good example, that logs to a third party system
https://github.com/logpacker/mobile-sdk

1. Is there already something in PROM to do this ?

2. Is anyone interested in this, and would you be open to a PR ?
It will be written in golang and use the existing Prom API, and so will be easy to support due to compile time checks.

3. Are there any gotcha's anyone can see with doing this ?

**Comment by brian-brazil** [comment]
Prometheus is a metrics system, it sounds like you're looking for an event logging solution so Prometheus isn't appropriate here.

**Comment by joeblew99** [comment]
I want to send the metrics back to Prom.

Logging i know is something else.

**Comment by brian-brazil** [comment]
Sending metrics to Prometheus from mobile clients is more an event logging use case than it is a metrics use case due to the number of clients and their likely lifetime.

**Comment by joeblew99** [comment]
so then ?
I plan in storage on the client if that helps ?
Prom is a push based system if i recall and so with storage it can push up to server.
Helps ?

Right now, the main thing is if you want a PR for this ? I have done a fair bit of gomobile.

**Comment by brian-brazil** [comment]
Prometheus is pull based, and we don't accept changes that change that. I don't think Prometheus is what you're looking for.

**Comment by joeblew99** [comment]
i am sure that PROM is what we want to us, because its nicely integrated with GRPC and GRPC-gateway and GOA v2. We use all these in many mobile, server and clients.

All we want is to take a stab at Prom agent on mobile basically.

Pull is no problem. It just requires a IOT style gateway relay pattern.  Already have that stuff i can plug in.

**Comment by grobie** [comment]
This has been discussed a few discussions on the developers mailing list: for example https://groups.google.com/d/msg/prometheus-developers/_svg4sn5w4c/CXDCjEVfDAAJ. The mailing list is the best place to discuss such developments.
