### ISSUE TITLE
version flags

### ISSUE THREAD

**Issue by joker234** [prometheus/prometheus#2252]
prometheus and promtool should have the same version flag for showing the version number:
```
prometheus -version
promtool version
```

Maybe one can add `promtool -version` as additional possibility.

**Comment by Gouthamve** [comment]
With the move to kingpin, promtool now uses a version flag:
```
➜  prometheus git:(integ-play) ✗ ./promtool --version
promtool, version  (branch: , revision: )
  build user:
  build date:
  go version:       go1.8.3
```

**Comment by joker234** [comment]
This doesn't really resolve the issue. Now we still have different version flags for prometheus and promtool. `-version` and `--version`.

**Comment by Gouthamve** [comment]
Oh no, so even prometheus moved to `--` in 2.0. See: https://prometheus.io/blog/2017/06/21/prometheus-20-alpha3-new-rule-format/

**Comment by joker234** [comment]
ah I see. Thx.
