### ISSUE TITLE
Cannot use non-ascii characters in alert name

### ISSUE THREAD

**Issue by bsd04** [prometheus/prometheus#2255]
**What did you do?**

Created alert rule with following name: ALERT LiigaLühike ...

**What did you expect to see?**

Checking test.rules
  SUCCESS: 1 rules found

**What did you see instead? Under which circumstances?**

Checking test.rules
  FAILED: parse error at line 1, char 13: unexpected character: 'ü'

**Environment**

Linux localhost.localdomain 3.10.0-514.el7.x86_64

* System information:

Linux 3.10.0-514.el7.x86_64 x86_64

* Prometheus version: 

prometheus, version 1.3.1 (branch: master, revision: be476954e80349cb7ec3ba6a3247cd712189dfcb)
  build user:       root@37f0aa346b26
  build date:       20161104-20:24:03
  go version:       go1.7.3

* Alertmanager version:

alertmanager, version 0.5.1 (branch: master, revision: 0ea1cac51e6a620ec09d053f0484b97932b5c902)
  build user:       root@fb407787b8bf
  build date:       20161125-08:14:40
  go version:       go1.7.3

* Prometheus configuration file:

not  relevant

* Alertmanager configuration file:

not relevant

* Logs:

not relevant

**Comment by beorn7** [comment]
That's the intended behavior. An alert name is treated the same as a metric name in PromQL, see https://prometheus.io/docs/concepts/data_model/#metric-names-and-labels for restrictions.

We should document that more clearly. I have filed https://github.com/prometheus/docs/issues/636 for that.
