### ISSUE TITLE
Unable to probe https sites.Please provide required config file

### ISSUE THREAD

**Issue by lalithasoundarya** [prometheus/prometheus#2261]
**What did you do?**
I installed prometheus on my pc and tried to scrape an url but the probe status is 0 and status is up

**What did you expect to see?**
I expect to see probe status as probe_success=1.

**What did you see instead? Under which circumstances?**
Iam seeing probe success = 0 message for given url

**Environment**

System information:

    insert output of uname -srm here
    Microsoft Windows [Version 6.1.7601]

    Prometheus version:

    insert output of prometheus -1.3.1 windows amd64

    Alertmanager version:

    insert output of alertmanager -version here (if relevant to the issue)

* Prometheus configuration file:
 global:
external_labels:
monitor: 'hostname'

rule_files:
- 'C:\Users\prasanta1.sahoo\go\bin\alert.rules'

scrape_configs:

    job_name: 'bb'
    scrape_interval: 30s
    scrape_timeout: 10s
    metrics_path: /probe
    params:
    module: [http_2xx] # Look for a HTTP 200 response.
    static_configs:
        targets: [ '10.129.65.22:10000/Services/AccountInquiry_v1_0/OperationsEndpoint.com']

    relabel_configs:
        source_labels: [address]
        regex: (.*)(:80)?
        target_label: __param_target
        replacement: ${1}
        source_labels: [__param_target]
        regex: (.*)
        target_label: instance
        replacement: ${1}
        source_labels: []
        regex: .*
        target_label: address
        replacement: 10.50.90.1:9115 # Blackbox exporter
```
insert configuration here
```

* Alertmanager configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```

**Comment by brian-brazil** [comment]
Usage questions are best asked at https://groups.google.com/forum/#!forum/prometheus-users
