### ISSUE TITLE
A web UI bug when use Chrom and Firefox browser 

### ISSUE THREAD

**Issue by barnettZQG** [prometheus/prometheus#2265]
```
Uncaught ReferenceError: Handlebars is not defined(…)(anonymous function) @ graph.js?v=1:6
```
This is a browser compatibility issues, so that the Graph can't display.
Safari browser no problem.

**Comment by tattsun** [comment]
@barnettZQG
Could you tell me what versions of browser and prometheus did you use?

**Comment by samis** [comment]
I'm experiencing this issue too and want to provide more detail.
My client browser is Gentoo's stable Firefox 45.
As for the server Prometheus version, I am using 1.2.3+ds2-4 from the Debian repository

**Comment by arthur-c** [comment]
Same problem with Chrome Version 55.0.2883.75 (64-bit) : the graph page only display "add graph" and the click is ineffective. 
Ok with FF 50.0.2 and Konqueror 4.14.24

With Konqueror, I can reproduce the problem if I try to load a graph from an alert query (the URL after the IF statement) : I have an "empty" graph page.

The issue started with 1.4.0 (I rollbacked) and still present with 1.4.1

**Comment by barnettZQG** [comment]
@arthur-c That's right.

**Comment by arthur-c** [comment]
Humm, I am able to display the graph page on chrome after several page reloads without cache (ctrl + F5), on konqueror with simple multiple reloads

**Comment by beorn7** [comment]
We definitely saw a number of issues that could be resolved with a "hard reload" (Ctrl+Shift+R).

**Comment by brancz** [comment]
Some systems like the rails assets pipeline add hashes to the assets and avoids caching problems with that. Maybe we can do something similar, in fact I would be surprised if we're the first ones doing that.

**Comment by brian-brazil** [comment]
Sounds like this was a transient caching issue.
