### ISSUE TITLE
Assessment sheet to monitor application by Prometheus

### ISSUE THREAD

**Issue by prasanata** [prometheus/prometheus#2267]
**What did you do?**
We are trying to use Prometheus for Monitoring our application.

**What did you expect to see?**
We are trying to understand what the tool and config file parameter setting are required for monitoring our application by Prometheus.
Please let me know if anybody have any Assessment sheet to assess any application for Prometheus monitoring.

**What did you see instead? Under which circumstances?**

Installed Prometheus and Balckbox exporter

**Environment**

* System information:

	insert output of `uname -srm` here
Microsoft Windows [Version 6.1.7601]
* Prometheus version: 

	insert output of `prometheus -version` here
prometheus, version 1.3.1 (branch: master, revision: be476954e80349cb7ec3ba6a324
7cd712189dfcb)
  build user:       root@37f0aa346b26
  build date:       20161104-20:31:07
  go version:       go1.7.3
* Alertmanager version:

	insert output of `alertmanager -version` here (if relevant to the issue)

* Prometheus configuration file:
```
insert configuration here
```

* Alertmanager configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```

**Comment by Gouthamve** [comment]
Hi, Usage questions are best asked at https://groups.google.com/forum/#!aboutgroup/prometheus-users

@brian-brazil Can this be closed?
