### ISSUE TITLE
Invalid metric name

### ISSUE THREAD

**Issue by talhakabakus** [prometheus/prometheus#2281]
**What did you do?**
Just configured a scrape to monitor my web app located at http://localhost:8080/testapp.

**What did you expect to see?**
The various analysis of my web server

**What did you see instead? Under which circumstances?**
No result is displayed

**Environment**
Ubuntu 16.04 LTS

* System information:
Linux 4.4.0-31-generic x86_64

* Prometheus version: 

prometheus, version 1.4.1 (branch: master, revision: 2a89e8733f240d3cd57a6520b52c36ac4744ce12)
  build user:       root@e685d23d8809
  build date:       20161128-09:59:22
  go version:       go1.7.3

* Prometheus configuration file:
global:
  scrape_interval:     5s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 5s # Evaluate rules every 15 seconds. The default is every 1 minute.

  external_labels:
      monitor: 'codelab-monitor'

rule_files:

scrape_configs:
  - job_name: 'payara'
    metrics_path: '/testapp'

    static_configs:
      - targets: ['localhost:8080']

**Comment by talhakabakus** [comment]
That's all the configuration I did @brian-brazil, when I enter `Prometheus -> Status -> Targets`, I see the error I shared in the previous post.

**Comment by brian-brazil** [comment]
You application is producing an invalid metric name. This is a bug in the application, can you indicate which client library you're using?

**Comment by talhakabakus** [comment]
I use **Payara** application server that runs a **Java EE web app**.

**Comment by brian-brazil** [comment]
So you're using https://github.com/prometheus/client_java ?

**Comment by talhakabakus** [comment]
Ok @brian-brazil, just figured out the reason of the error - something related with my security restrictions. Thanks for your guidance.

**Comment by srikanthdixit** [comment]
This is my prometheus configuration file.
# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'codelab-monitor'

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
   - "first.rules"
   - "second.rules"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.


    static_configs:
      - targets:
          - "10.93.1.134:9100"
          - "10.9.64.47:9100"

Issue: In prometheus dashboard i can see the target servers are showing DOWN not sure what would be the issue. I might be doing something wrong. Any help would be greatly appreciated. Please find attached screeen shot is what i'm facing
<img width="1418" alt="screen shot 2017-06-08 at 11 07 53 am" src="https://user-images.githubusercontent.com/26823541/26943599-ff693272-4c3a-11e7-8ba5-91b1d3aeb660.png">
