### ISSUE TITLE
Question: n:m target probing

### ISSUE THREAD

**Issue by kim** [prometheus/prometheus#2284]
I have a cluster of services which are not themselves aware of the fact that they form a cluster, yet must be able to communicate with each other over TCP. The service instances are discovered using DNS SRV.

I am wondering if I could utilise prometheus in conjunction with blackbox exporters deployed alongside service instances to monitor inter-service connectivity. For this to work, I'd need to be able to apply relabelling on the _set_ of targets returned by SD, for each target. However, it is my understanding that relabelling is applied pointwise.

An alternative approach would be to perform SD and probing of peers on each service instance separately and expose the results as a regular scrape endpoint to prometheus. This seems to violate  a philosophical stance taken by prometheus maintainers, though (cf. eg. prometheus/blackbox_exporter#82).

Hence, I'd like to know if similar use cases exist for others and whether there is another solution apart from what I outlined above.

_(apologies if this kind of inquiries are better served by some mailing list; I am not subscribed there)_

**Comment by brian-brazil** [comment]
This is not possible. I'd suggest looking at file-based service discovery.

**Comment by kim** [comment]
I don't think file-based service discovery helps in any way here. But thanks anyways for your insightful response.

**Comment by brian-brazil** [comment]
You could generate all the n:m targets and then used file_sd to provide that to prometheus.

**Comment by kim** [comment]
Thanks. I actually interpolated that from your first answer, yet I can't find this operationally preferable to the second approach I gave. Perhaps I was just looking for a _convenient_ solution, but it's clear that it doesn't fit the prometheus model very well in the general case. So thanks again, and nevermind.
