### ISSUE TITLE
Also use consul tags as filter for service discovery

### ISSUE THREAD

**Issue by flypenguin** [prometheus/prometheus#2285]
Currently you can either scrape all services, or a list of certain services given by _service name_.

It would be really nice if you could also specify a tag filter, e.g. "prometheus_target", to use. 

**Current situation:**

[See Docs](https://prometheus.io/docs/operating/configuration/#%3Cconsul_sd_config%3E). Only consul service _name_ is available for filtering.

**Proposal for configuration:**

    # STATUS QUO
    services:
      [ - <string> ]
    # The string by which Consul tags are joined into the tag label.
    [ tag_separator: <string> | default = , ]

    # NEW ADDITION
    tags:
      [ - <string> ]

**Effect:**

Should either scrape all services, or ...

* if service name given: only services with the given names
* if service tag list given: only services with the given tags attached
* if both given: any combination of given service names and tag names

**Rationale:**

We have much more services registered in consul than we want to scrape (most of them don't even have scraping endpoints for prometheus available). So prometheus should not try to scrape them, and possibly list them as failed if it can't reach the scraping endpoint.

**Comment by brian-brazil** [comment]
You can do this via relabelling, see https://www.robustperception.io/finding-consul-services-to-monitor-with-prometheus/

**Comment by flypenguin** [comment]
oh cool :) . in that case - close it if you want. (although it would be way more convenient that way ;) )
