### ISSUE TITLE
result of a count() on a query that returns nothing should be 0 ?

### ISSUE THREAD

**Issue by zerthimon** [prometheus/prometheus#2286]
**What did you do?**
count(container_last_seen{name="container_that_doesn't_exist"})

**What did you expect to see?**
0

**What did you see instead? Under which circumstances?**
"no data"

**Comment by brian-brazil** [comment]
This is correct. You're probably looking for the `absent` function.

**Comment by zerthimon** [comment]
@brian-brazil I'm trying to make prometheus to alert when count of the containers that match a specific pattern in a geo region drops below some number:
```
IF count(container_last_seen{environment="prod",name=~"notification_sender.*",roles=~".*application-server.*"}) by (geo_region) < 4
```
So this works until there is no containers of this name in the region ... then the value becomes "no data" and that's not < 4 ... so there is no alert ...

I can see how absent() may help me here...

**Comment by juliusv** [comment]
Yeah, absent() is probably the way to go. There's also count_scalar(),
which outputs 0 for an empty input vector, but that outputs a scalar
without any dimensional information.

**Comment by zerthimon** [comment]
@juliusv yeah, I tried count_scalar() but I can't use aggregation with it. As for absent() ... I'm still out of ideas here.

How would you address this use case:
1. an EC2 region with application servers running docker containers.
2. Cadvisors on every server provide container names
3. The containers are named with a specific pattern: 
* notification_checker[0-9]
* notification_sender[0-9]
4 I need an alert when the number of container of the same pattern (eg. notification_sender-.*) in region drops below 4
5 alert also has to fire if there are no containers match the pattern

The best query I could come up with is this:
```
count(container_last_seen{environment="prod",name=~"notification_sender.*",roles=~".*application-server.*"}) by (geo_region) < 4
```
The result of the query is:
```
{geo_region="tokyo"}	4
{geo_region="sydney"}	4
{geo_region="singapore"}	4
{geo_region="saopaulo"}	4
{geo_region="virginia"}	4
{geo_region="dublin"}	4
```
Which is great... but... It can't get me a region where there are no containers (0), cause for some reason count() doesn't work for 0 elements in vector ...
I'd expect to have also:
```
{geo_region="california"}   0
```

**Comment by grobie** [comment]
Please use the [prometheus-users mailing list](https://groups.google.com/d/msg/prometheus-users) for questions.

**Comment by fortman** [comment]
@zerthimon You might want to use 'bool' with your comparator
count(container_last_seen{environment="prod",name=~"notification_sender.*",roles=~".*application-server.*"}) by (geo_region) < bool 4
or something like that.  Play with bool
Also the link to the mailing list doesn't work for me.

**Comment by baifeg** [comment]
@zerthimon The following expr works for me
count(ALERTS) or (1-absent(ALERTS))

**Comment by lilred** [comment]
Alternatively, `count(ALERTS) or vector(0)`

**Comment by r0fls** [comment]
Neither of these solutions seem to retain the other dimensional information, they simply produce a scaler 0.
