### ISSUE TITLE
the param of web.console.libraries is unavailable

### ISSUE THREAD

**Issue by ljohnny** [prometheus/prometheus#2294]
i run this command :  prometheus.exe -config.file=./prometheus.yml -web.console.libraries=./console_libraries and modify the menu.lib file's content .But the page of '/graph' was any change.Even i remove this file and it was not any influence. what's wrong with?my version is prometheus-1.3.1.windows-amd64

**Comment by brian-brazil** [comment]
/graph is not part of the console templates or the included examples, it's embedded in Prometheus.

**Comment by ljohnny** [comment]
it's part of grafana?

**Comment by ljohnny** [comment]
it's /consoles,it's my comprehension errors.
