### ISSUE TITLE
Build Automated Complete End to End Test

### ISSUE THREAD

**Issue by matttproud** [prometheus/prometheus#230]
1. Builds binary running requisite whitebox tests.
2. Starts up Prometheus.
3. Tries issuing web queries to evaluate known expressions against the database.
4. Validates results.

/CC: @juliusv — You may have some ideas of some things you'd like to see captured here.

**Comment by ncabatoff** [comment]
I took a stab at this (minus step 1), see https://github.com/ncabatoff/prombench.  I wasn't thinking in terms of incorporating it into the Prometheus project itself, but if desired I could create a PR.  I'd need some guidance in terms of where it should go and so forth.

**Comment by grobie** [comment]
Thank you, this is awesome!

I don't think it's necessary to merge the project itself into the prometheus repository. I'm fine if people actually prefer that, but it should be totally fine to just embed it. I could imagine we add a `make benchmark` target, which install prombench if not available and runs the benchmark. Similar to what we do with promu.

**Comment by ncabatoff** [comment]
That was my thinking.

**Comment by brian-brazil** [comment]
Prombench covers this.
