### ISSUE TITLE
Is prometheus Support Remote storage in Warp 10 Platform  database

### ISSUE THREAD

**Issue by abhilash07** [prometheus/prometheus#2302]
Dear Sir/Madam, i have been using Prometheus for past 4 months and using influx-db as remote storage. But the problem in the influx-db opensource version doesn't support clustering so we planned to store our metrics in Warp 10 Platform  database remotely. This opensource db will support clustering is there any way to send Prometheus metrics data to Warp 10 Platform  database (http://www.warp10.io/introduction/platform/). Thanks in advance.

Regrads
Abhilash S

**Comment by brian-brazil** [comment]
You can use remote write to send data to 3rd party systems, See https://www.robustperception.io/using-the-remote-write-path/
