### ISSUE TITLE
prometheus can not bind ip v4 address

### ISSUE THREAD

**Issue by pc10201** [prometheus/prometheus#2310]
**What did you do?**

./prometheus -web.listen-address "0.0.0.0:9091"
./prometheus -web.listen-address ":9091"

**What did you expect to see?**

I want bind 0.0.0.0 let everyone can see the web.

**What did you see instead? Under which circumstances?**

```
 ss -lntup
Netid  State      Recv-Q Send-Q Local Address:Port               Peer Address:Port            
tcp    LISTEN     0      128              *:22                           *:*                   users:(("sshd",pid=1165,fd=3))
tcp    LISTEN     0      128             :::22                          :::*                   users:(("sshd",pid=1165,fd=4))
tcp    LISTEN     0      128             :::9091                        :::*                   users:(("prometheus",pid=9266,fd=21))
```

**Environment**

* System information:
CentOS 7 x64
Linux 3.10.0-327.36.3.el7.x86_64 x86_64

* Prometheus version: 

```
./prometheus -version
prometheus, version 1.4.1 (branch: master, revision: 2a89e8733f240d3cd57a6520b52c36ac4744ce12)
  build user:       root@e685d23d8809
  build date:       20161128-09:59:22
  go version:       go1.7.3
```

**Comment by juliusv** [comment]
The `ss` output doesn't indicate that Prometheus is not listening on v4, even if it just shows a v6 entry. When I run Prometheus in the same way, I get the same `ss` output, but I can still reach Prometheus on the v4 address. Does that not work for you?

**Comment by pc10201** [comment]
I am sorry.It is OK now.
Because centos firewalld  service is active.So I stop it.
