### ISSUE TITLE
promtool check-rules should alert on duplicates

### ISSUE THREAD

**Issue by momorientes** [prometheus/prometheus#2314]
**What did you do?**
Duplicate Recording Rules(out of stupidity):
```
ifInRate{} = (rate(ifInOctets[1m])*8) / ifSpeed
ifInRate{} = (rate(ifOutOctets[1m])*8) / ifSpeed
```
**What did you expect to see?**
a warning of some kind when running `promtool check-rules`

**What did you see instead? Under which circumstances?**
```
WARN[8657] Error on ingesting results from rule evaluation with different value but same timestamp  numDropped=77 source=manager.go:299
```

**Comment by brian-brazil** [comment]
This is potentially a valid setup, there's no general way to detect this sort of thing.

**Comment by fabxc** [comment]
Indeed nothing that indicates an actual issue. We don't want to get into the business of warnings as that will be quite a rabbit hole.
