### ISSUE TITLE
prometheus data loss problem

### ISSUE THREAD

**Issue by coffeehc** [prometheus/prometheus#2320]
Recently our prometheus data loss problem occurs, every 5 minutes to lose part of the data
View code is mainly due to the data storage time has been more than 15d, at this time call func (s * MemorySeriesStorage) maintainArchivedSeries (fp model.Fingerprint, beforeTime model.Time) method, triggered the delete expired data, but I found deleted When the current collection of data has not been stored.
Next, I set the storage.local.retention 18d, there is no current data loss problem
I would like to ask what is the distribution of the problem?

* System information:

Linux 3.10.0-229.el7.x86_64 x86_64 800G SSD

* Prometheus version: 

prometheus, version 1.4.1 (branch: master, revision: 2a89e8733f240d3cd57a6520b52c36ac4744ce12)
  build user:       root@e685d23d8809
  build date:       20161128-09:59:22
  go version:       go1.7.3

**Comment by Gouthamve** [comment]
Hi, I am not able to understand the issue here correctly. Are you telling that even if you increase the retention to 18d you are losing data that we persisted before the restart?

**Comment by Gouthamve** [comment]
@brian-brazil This can be closed as it looks like a usage question and is quite old.
