### ISSUE TITLE
Docker image should accept optional flags as ENV variables

### ISSUE THREAD

**Issue by mstump** [prometheus/prometheus#2324]
With the current docker image there is no way to pass additional command line flags such as ```-web.external-url```. Instead of invoking prometheus directly the image should invoke a shell script, optionally passing command line variables if they're specified in the environment.

**Comment by andrestc** [comment]
Couldn't you just pass this cmd line flags directly to `docker run`? Those would override the `CMD` entry of the Dockerfile and will be fed directly to the `ENTRYPOINT` (prometheus binary).

**Comment by mstump** [comment]
you are correct.
