### ISSUE TITLE
Short hostname results in "context deadline exceeded"

### ISSUE THREAD

**Issue by stuart-c** [prometheus/prometheus#2332]
**What did you do?**

Added a target with a very short (4 char) hostname and port number combo

**What did you expect to see?**

Successful polling of the new hostname

**What did you see instead? Under which circumstances?**

No stats - error of "context deadline exceeded". Still didn't work even if the timeout was increased significantly.

**Environment**

Official Docker container of Prometheus (:latest)

The following config snippet didn't work:

  - job_name: 'jira'
    static_configs:
      - targets: ['jira:8080']

But the following does:

  - job_name: 'jira'
    static_configs:
      - targets: ['jirax:8080']

**Comment by brian-brazil** [comment]
This sounds like a name resolution issue on your end. Have you verified this name resolves and is accessible from within the container?

**Comment by stuart-c** [comment]
Yep. I used "docker exec" to get into the prometheus container and then could both ping "jira" and telnet to the correct port sending a manual HTTP request and getting the metric data back.

**Comment by brian-brazil** [comment]
Deadline exceeded implies that DNS worked. Can you access jira via IP address?

Incidentally ping uses non-standard resolution. I wouldn't fully trust it for testing something like this.

**Comment by stuart-c** [comment]
Yep accessing via IP address works. If I just change the container/link name in Docker to have an extra char it works, so it is just the 4 char hostname/port (jira:8080) which doesn't work. I don't see the callback on the jira exporter side being called at all (this is a Python script using the client library)

**Comment by brian-brazil** [comment]
Something weird is going on here anyway. Several of my home systems happen to be 4 chars, so I don't think it's on the Prometheus side.

**Comment by stuart-c** [comment]
Could it be something about being 9 total chars (i.e. host:port = 4:4 chars)?

It was a very odd thing and as I say just changing the hostname fixed it

**Comment by brian-brazil** [comment]
This is likely something odd with resolution on your end. If this is still occurring, it's best to discuss on https://groups.google.com/forum/#!forum/prometheus-users
