### ISSUE TITLE
Deploy prometheus with k8s, execute cmd get no data

### ISSUE THREAD

**Issue by JackTiger** [prometheus/prometheus#2337]
I deploy prometheus  in k8s, and execute cmd that the result is no data, and I execute restful api in k8s master node like below:

curl -X GET "http://127.0.0.1:30900/api/v1/query?query=container_spec_cpu_shares&time=1484218546.737&_=1484218527110"
{"status":"success","data":{"resultType":"vector","result":[]}}

I think my prometheus  config is right, because I deploy in other k8s cluster, so Is there limit to prometheus  , like k8s version or prometheus   version?

**Comment by matthiasr** [comment]
Check the target page of Prometheus – can it scrape its targets? Did it find any?

**Comment by JackTiger** [comment]
@matthiasr  Thanks for your help, I have resolved my problem because the time in cluster of k8s is set in the future, so prometheus can not get any data.

By the way, Does the prometheus support to monitor the data that I increase service node dynamic. For example now prometheus monitor 5 vm, and I want to add vm to be monitored, Whether I must rewrite the config file of prometheus and restart prometheus server?
