### ISSUE TITLE
Feature request: label_drop(v instant-vector, label) method

### ISSUE THREAD

**Issue by nvartolomei** [prometheus/prometheus#2343]
The use case for this one is to drop metric labels at query time. Currently I'm using `label_replace` with empty `replacement`, but it's too verbose.

> `label_drop(v instant-vector, label string)` removes label `label` from each timeseries in `v`.

**Comment by brian-brazil** [comment]
That falls under #959. I think we'd go with label_set with an empty value first.

Have you tried using `without`?
