### ISSUE TITLE
Support for HTTP Headers when performing metrics scraping

### ISSUE THREAD

**Issue by ihr** [prometheus/prometheus#2346]
Hi guys,

I am facing a scenario in which I need to scrap the metrics from microserices deployed on a PaaS (Cloud Foundry). In order to get the metrics from individual instances of a microservice, I need to send a header `X-CF-APP-INSTANCE: APP_GUID:APP_INDEX`where APP_GUID change at runtime APP_INDEX. Here is [a link to the docs](https://docs.cloudfoundry.org/devguide/deploy-apps/routes-domains.html#surgical-routing). I haven't found anything that could help me in the current version of Prometheus. Would you consider this feature important and would you accept a pull request? Or am I missing something, is this already possible somehow?

**Comment by brian-brazil** [comment]
A small proxy server would be the best way to handle this.

Offering headers to users would likely see them used in cases where other solutions would be more appropriate, and make debugging a lot more difficult.

**Comment by ihr** [comment]
Hi Brian,

I see your point. Do you have in mind any proxy in particular? Thanks!

**Comment by brian-brazil** [comment]
Probably easiest to write something quickly yourself, though something like HAProxy is probably configurable to do this by taking it from a url parameter and making it into a label.

**Comment by fabxc** [comment]
This has been requested several times in the past and was rejected. So closing here.

Please see #1724 for past discussion.

**Comment by eaglerainbow** [comment]
@ihr You might find https://github.com/promregator/promregator interesting (still in experimental stage, though).
