### ISSUE TITLE
Lookup Metric via Fingerprint in Graph and Console

### ISSUE THREAD

**Issue by matttproud** [prometheus/prometheus#235]
Not sure exactly how this would appear from a user perspective, but would be nice ``01289381983818192451-c-1-s``?

**Comment by brian-brazil** [comment]
This is more a promtool thing I think.

**Comment by beorn7** [comment]
Given that we want to bury fingerprints under more layers of abstraction anyway, it's arguably totally wrong to put it into the web ui in any form.

It could be put into `storagetool` to act on a cold storage.

**Comment by juliusv** [comment]
Closing this for now.
