### ISSUE TITLE
[Question]: Delete metrics for a specific target

### ISSUE THREAD

**Issue by DigitalMarc** [prometheus/prometheus#2356]
Hi,
**Prom version: 1.2.1**

It seems that we can't use the delete API to remove a set of metrics such as:
`{__name__=~".*",cluster="Test Cluster"}`
The API reply with `400 Bad Request`

full request made: `curl -X DELETE -g 'http://localhost:9090/api/v1/series?match[]={__name__=~".*",cluster="Test Cluster"}'`

How can we remove all the metrics that matches a specific field or, put differently, all metrics from a target?

Many thanks

**Comment by brian-brazil** [comment]
That looks to be correct. Does that expression work in the expression browser?

**Comment by DigitalMarc** [comment]
Yes it does.

**Comment by brian-brazil** [comment]
The space needs to be encoded as %20

**Comment by DigitalMarc** [comment]
Wonderful!

**Comment by piotrkochan** [comment]
```
curl -X DELETE -g 'localhost:9090/prometheus/api/v1/series?match[]={instance="localhost:9100"}' | jq
```

```
{
  "status": "error",
  "errorType": "internal",
  "error": "not implemented"
}
```

**Comment by mzupan** [comment]
@piotrkochan 

```
curl -X POST http://localhost:9090/api/v1/series?match[]={instance="localhost:9100"}
```
