### ISSUE TITLE
how to read the result of goroutine of the prometheus debug tool

### ISSUE THREAD

**Issue by xixikaikai** [prometheus/prometheus#2362]
curl -s http://172.19.0.176:31090/debug/pprof/goroutine?debug=2

goroutine 12557387 [running]:
runtime/pprof.writeGoroutineStacks(0x2654400, 0xc521d2c1a0, 0x26ec830, 0x30)
	/usr/local/go/src/runtime/pprof/pprof.go:585 +0x79
runtime/pprof.writeGoroutine(0x2654400, 0xc521d2c1a0, 0x2, 0x0, 0xc420212400)
	/usr/local/go/src/runtime/pprof/pprof.go:574 +0x44
runtime/pprof.(*Profile).WriteTo(0x26eff00, 0x2654400, 0xc521d2c1a0, 0x2, 0xc521d2c1a0, 0xc57201c1e4)
	/usr/local/go/src/runtime/pprof/pprof.go:298 +0x341
net/http/pprof.handler.ServeHTTP(0xc57201c1f1, 0x9, 0x2662940, 0xc521d2c1a0, 0xc5553e2000)
	/usr/local/go/src/net/http/pprof/pprof.go:209 +0x1a6
net/http/pprof.Index(0x2662940, 0xc521d2c1a0, 0xc5553e2000)
	/usr/local/go/src/net/http/pprof/pprof.go:221 +0x205
net/http.HandlerFunc.ServeHTTP(0x1bbd3b8, 0x2662940, 0xc521d2c1a0, 0xc5553e2000)
	/usr/local/go/src/net/http/server.go:1726 +0x44
net/http.(*ServeMux).ServeHTTP(0x26ffe60, 0x2662940, 0xc521d2c1a0, 0xc5553e2000)
	/usr/local/go/src/net/http/server.go:2022 +0x7f
net/http.(*ServeMux).ServeHTTP-fm(0x2662940, 0xc521d2c1a0, 0xc5553e2000)
	/go/src/github.com/prometheus/prometheus/web/web.go:203 +0x48
github.com/prometheus/prometheus/vendor/github.com/prometheus/common/route.(*Router).handle.func1(0x2662940, 0xc521d2c1a0, 0xc5553e2000, 0xc572764200, 0x1, 0x1)
	/go/src/github.com/prometheus/prometheus/vendor/github.com/prometheus/common/route/route.go:83 +0x2ba
github.com/prometheus/prometheus/vendor/github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc4201c1380, 0x2662940, 0xc521d2c1a0, 0xc5553e2000)
	/go/src/github.com/prometheus/prometheus/vendor/github.com/julienschmidt/httprouter/router.go:299 +0x7ec
github.com/prometheus/prometheus/vendor/github.com/prometheus/common/route.(*Router).ServeHTTP(0xc4204d0100, 0x2662940, 0xc521d2c1a0, 0xc5553e2000)
	/go/src/github.com/prometheus/prometheus/vendor/github.com/prometheus/common/route/route.go:125 +0x4c
net/http.serverHandler.ServeHTTP(0xc42019c080, 0x2662940, 0xc521d2c1a0, 0xc5553e2000)
	/usr/local/go/src/net/http/server.go:2202 +0x7d
net/http.(*conn).serve(0xc4bf2d8000, 0x2664040, 0xc57253e100)
	/usr/local/go/src/net/http/server.go:1579 +0x4b7
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2293 +0x44d

goroutine 1 [select, 6786 minutes]:
main.Main(0x0)
	/go/src/github.com/prometheus/prometheus/cmd/prometheus/main.go:230 +0x1c22
main.main()
	/go/src/github.com/prometheus/prometheus/cmd/prometheus/main.go:45 +0x22

goroutine 26 [chan receive, 2 minutes]:
github.com/prometheus/prometheus/vendor/github.com/golang/glog.(*loggingT).flushDaemon(0x27005e0)
	/go/src/github.com/prometheus/prometheus/vendor/github.com/golang/glog/glog.go:879 +0x7a
created by github.com/prometheus/prometheus/vendor/github.com/golang/glog.init.1
	/go/src/github.com/prometheus/prometheus/vendor/github.com/golang/glog/glog.go:410 +0x21d

goroutine 52 [select]:
github.com/prometheus/prometheus/retrieval.(*scrapeLoop).run(0xc424c6e460, 0x12a05f200, 0x12a05f200, 0x0)
	/go/src/github.com/prometheus/prometheus/retrieval/scrape.go:436 +0x3cc
created by github.com/prometheus/prometheus/retrieval.(*scrapePool).sync
	/go/src/github.com/prometheus/prometheus/retrieval/scrape.go:240 +0x3e5

goroutine 68 [syscall, 6786 minutes]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:116 +0x157
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 70 [select, 14 minutes]:
github.com/prometheus/prometheus/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).compactionError(0xc4204aa300)
	/go/src/github.com/prometheus/prometheus/vendor/github.com/syndtr/goleveldb/leveldb/db_compaction.go:90 +0x5e1
created by github.com/prometheus/prometheus/vendor/github.com/syndtr/goleveldb/leveldb.openDB
	/go/src/github.com/prometheus/prometheus/vendor/github.com/syndtr/goleveldb/leveldb/db.go:139 +0x592

goroutine 159 [select, 6786 minutes, locked to thread]:
runtime.gopark(0x1bbd848, 0x0, 0x1acb970, 0x6, 0x18, 0x2)
	/usr/local/go/src/runtime/proc.go:259 +0x13a
runtime.selectgoImpl(0xc420477730, 0x0, 0x18)
	/usr/local/go/src/runtime/select.go:423 +0x11d9
runtime.selectgo(0xc420477730)
	/usr/local/go/src/runtime/select.go:238 +0x1c
runtime.ensureSigM.func1()
	/usr/local/go/src/runtime/signal1_unix.go:304 +0x2f3
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2086 +0x1

goroutine 158 [select, 2 minutes]:
github.com/prometheus/prometheus/rules.(*Group).run(0xc4204b54f0)
	/go/src/github.com/prometheus/prometheus/rules/manager.go:171 +0x282
github.com/prometheus/prometheus/rules.(*Manager).ApplyConfig.func1.1(0xc42042e060, 0xc4204b54f0)
	/go/src/github.com/prometheus/prometheus/rules/manager.go:426 +0x52
created by github.com/prometheus/prometheus/rules.(*Manager).ApplyConfig.func1
	/go/src/github.com/prometheus/prometheus/rules/manager.go:427 +0xa7

goroutine 160 [select, 6786 minutes]:
main.Main.func2(0xc420263c80, 0xc420263c20, 0xc4204b53b0, 0x5, 0x5, 0xc420201860)
	/go/src/github.com/prometheus/prometheus/cmd/prometheus/main.go:165 +0x358
created by main.Main
	/go/src/github.com/prometheus/prometheus/cmd/prometheus/main.go:179 +0x1211

goroutine 161 [select]:
github.com/prometheus/prometheus/vendor/github.com/syndtr/goleveldb/leveldb/util.(*BufferPool).drain(0xc42037c620)
	/go/src/github.com/prometheus/prometheus/vendor/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:206 +0x247
created by github.com/prometheus/prometheus/vendor/github.com/syndtr/goleveldb/leveldb/util.NewBufferPool
	/go/src/github.com/prometheus/prometheus/vendor/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:237 +0x1bc

goroutine 162 [select, 6671 minutes]:
github.com/prometheus/prometheus/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).compactionError(0xc4204aa000)
	/go/src/github.com/prometheus/prometheus/vendor/github.com/syndtr/goleveldb/leveldb/db_compaction.go:90 +0x5e1
created by github.com/prometheus/prometheus/vendor/github.com/syndtr/goleveldb/leveldb.openDB
	/go/src/github.com/prometheus/prometheus/vendor/github.com/syndtr/goleveldb/leveldb/db.go:139 +0x592

goroutine 163 [select, 2 minutes]:
github.com/prometheus/prometheus/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0xc4204aa000)
	/go/src/github.com/prometheus/prometheus/vendor/github.com/syndtr/goleveldb/leveldb/db_state.go:96 +0x249
created by github.com/prometheus/prometheus/vendor/github.com/syndtr/goleveldb/leveldb.openDB
	/go/src/github.com/prometheus/prometheus/vendor/github.com/syndtr/goleveldb/leveldb/db.go:140 +0x5b4

goroutine 164 [select, 6671 minutes]:
github.com/prometheus/prometheus/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).tCompaction(0xc4204aa000)
	/go/src/github.com/prometheus/prometheus/vendor/github.com/syndtr/goleveldb/leveldb/db_compaction.go:804 +0x83c
created by github.com/prometheus/prometheus/vendor/github.com/syndtr/goleveldb/leveldb.openDB
	/go/src/github.com/prometheus/prometheus/vendor/github.com/syndtr/goleveldb/leveldb/db.go:146 +0x73a

goroutine 165 [select, 6786 minutes]:
github.com/prometheus/prometheus/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).mCompaction(0xc4204aa000)
	/go/src/github.com/prometheus/prometheus/vendor/github.com/syndtr/goleveldb/leveldb/db_compaction.go:751 +0x263
created by github.com/prometheus/prometheus/vendor/github.com/syndtr/goleveldb/leveldb.openDB
	/go/src/github.com/prometheus/prometheus/vendor/github.com/syndtr/goleveldb/leveldb/db.go:147 +0x75c

goroutine 166 [select]:
github.com/prometheus/prometheus/vendor/github.com/syndtr/goleveldb/leveldb/util.(*BufferPool).drain(0xc42037c8c0)
	/go/src/github.com/prometheus/prometheus/vendor/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:206 +0x247
created by github.com/prometheus/prometheus/vendor/github.com/syndtr/goleveldb/leveldb/util.NewBufferPool
	/go/src/github.com/prometheus/prometheus/vendor/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:237 +0x1bc

goroutine 14 [select, 5953 minutes]:
github.com/prometheus/prometheus/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).compactionError(0xc4204aa180)
	/go/src/github.com/prometheus/prometheus/vendor/github.com/syndtr/goleveldb/leveldb/db_compaction.go:90 +0x5e1
created by github.com/prometheus/prometheus/vendor/github.com/syndtr/goleveldb/leveldb.openDB
	/go/src/github.com/prometheus/prometheus/vendor/github.com/syndtr/goleveldb/leveldb/db.go:139 +0x592

goroutine 15 [select, 2 minutes]:
github.com/prometheus/prometheus/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0xc4204aa180)
	/go/src/github.com/prometheus/prometheus/vendor/github.com/syndtr/goleveldb/leveldb/db_state.go:96 +0x249
created by github.com/prometheus/prometheus/vendor/github.com/syndtr/goleveldb/leveldb.openDB
	/go/src/github.com/prometheus/prometheus/vendor/github.com/syndtr/goleveldb/leveldb/db.go:140 +0x5b4

goroutine 16 [select, 5953 minutes]:
github.com/prometheus/prometheus/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).tCompaction(0xc4204aa180)
	/go/src/github.com/prometheus/prometheus/vendor/github.com/syndtr/goleveldb/leveldb/db_compaction.go:804 +0x83c
created by github.com/prometheus/prometheus/vendor/github.com/syndtr/goleveldb/leveldb.openDB
	/go/src/github.com/prometheus/prometheus/vendor/github.com/syndtr/goleveldb/leveldb/db.go:146 +0x73a

goroutine 177 [select, 6786 minutes]:
github.com/prometheus/prometheus/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).mCompaction(0xc4204aa180)
	/go/src/github.com/prometheus/prometheus/vendor/github.com/syndtr/goleveldb/leveldb/db_compaction.go:751 +0x263
created by github.com/prometheus/prometheus/vendor/github.com/syndtr/goleveldb/leveldb.openDB
	/go/src/github.com/prometheus/prometheus/vendor/github.com/syndtr/goleveldb/leveldb/db.go:147 +0x75c

goroutine 178 [select]:
github.com/prometheus/prometheus/vendor/github.com/syndtr/goleveldb/leveldb/util.(*BufferPool).drain(0xc42037ca80)
	/go/src/github.com/prometheus/prometheus/vendor/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:206 +0x247
created by github.com/prometheus/prometheus/vendor/github.com/syndtr/goleveldb/leveldb/util.NewBufferPool
	/go/src/github.com/prometheus/prometheus/vendor/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:237 +0x1bc

goroutine 71 [select, 2 minutes]:
github.com/prometheus/prometheus/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0xc4204aa300)
	/go/src/github.com/prometheus/prometheus/vendor/github.com/syndtr/goleveldb/leveldb/db_state.go:96 +0x249
created by github.com/prometheus/prometheus/vendor/github.com/syndtr/goleveldb/leveldb.openDB
	/go/src/github.com/prometheus/prometheus/vendor/github.com/syndtr/goleveldb/leveldb/db.go:140 +0x5b4

goroutine 72 [select, 14 minutes]:
github.com/prometheus/prometheus/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).tCompaction(0xc4204aa300)
	/go/src/github.com/prometheus/prometheus/vendor/github.com/syndtr/goleveldb/leveldb/db_compaction.go:804 +0x83c
created by github.com/prometheus/prometheus/vendor/github.com/syndtr/goleveldb/leveldb.openDB
	/go/src/github.com/prometheus/prometheus/vendor/github.com/syndtr/goleveldb/leveldb/db.go:146 +0x73a

goroutine 73 [select, 14 minutes]:
github.com/prometheus/prometheus/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).mCompaction(0xc4204aa300)
	/go/src/github.com/prometheus/prometheus/vendor/github.com/syndtr/goleveldb/leveldb/db_compaction.go:751 +0x263
created by github.com/prometheus/prometheus/vendor/github.com/syndtr/goleveldb/leveldb.openDB
	/go/src/github.com/prometheus/prometheus/vendor/github.com/syndtr/goleveldb/leveldb/db.go:147 +0x75c

goroutine 74 [select]:
github.com/prometheus/prometheus/vendor/github.com/syndtr/goleveldb/leveldb/util.(*BufferPool).drain(0xc4202742a0)
	/go/src/github.com/prometheus/prometheus/vendor/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:206 +0x247
created by github.com/prometheus/prometheus/vendor/github.com/syndtr/goleveldb/leveldb/util.NewBufferPool
	/go/src/github.com/prometheus/prometheus/vendor/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:237 +0x1bc

goroutine 75 [select, 58 minutes]:
github.com/prometheus/prometheus/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).compactionError(0xc4204aa480)
	/go/src/github.com/prometheus/prometheus/vendor/github.com/syndtr/goleveldb/leveldb/db_compaction.go:90 +0x5e1
created by github.com/prometheus/prometheus/vendor/github.com/syndtr/goleveldb/leveldb.openDB
	/go/src/github.com/prometheus/prometheus/vendor/github.com/syndtr/goleveldb/leveldb/db.go:139 +0x592

goroutine 76 [select, 2 minutes]:
github.com/prometheus/prometheus/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0xc4204aa480)
	/go/src/github.com/prometheus/prometheus/vendor/github.com/syndtr/goleveldb/leveldb/db_state.go:96 +0x249
created by github.com/prometheus/prometheus/vendor/github.com/syndtr/goleveldb/leveldb.openDB
	/go/src/github.com/prometheus/prometheus/vendor/github.com/syndtr/goleveldb/leveldb/db.go:140 +0x5b4

goroutine 77 [select, 58 minutes]:
github.com/prometheus/prometheus/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).tCompaction(0xc4204aa480)
	/go/src/github.com/prometheus/prometheus/vendor/github.com/syndtr/goleveldb/leveldb/db_compaction.go:804 +0x83c
created by github.com/prometheus/prometheus/vendor/github.com/syndtr/goleveldb/leveldb.openDB
	/go/src/github.com/prometheus/prometheus/vendor/github.com/syndtr/goleveldb/leveldb/db.go:146 +0x73a

goroutine 78 [select, 58 minutes]:
github.com/prometheus/prometheus/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).mCompaction(0xc4204aa480)
	/go/src/github.com/prometheus/prometheus/vendor/github.com/syndtr/goleveldb/leveldb/db_compaction.go:751 +0x263
created by github.com/prometheus/prometheus/vendor/github.com/syndtr/goleveldb/leveldb.openDB
	/go/src/github.com/prometheus/prometheus/vendor/github.com/syndtr/goleveldb/leveldb/db.go:147 +0x75c

goroutine 79 [select]:
github.com/prometheus/prometheus/storage/local.(*persistence).processIndexingQueue(0xc42019bd40)
	/go/src/github.com/prometheus/prometheus/storage/local/persistence.go:1278 +0xb96
github.com/prometheus/prometheus/storage/local.(*persistence).run(0xc42019bd40)
	/go/src/github.com/prometheus/prometheus/storage/local/persistence.go:291 +0x2b
created by github.com/prometheus/prometheus/storage/local.(*MemorySeriesStorage).Start
	/go/src/github.com/prometheus/prometheus/storage/local/storage.go:344 +0x12f

goroutine 179 [select]:
github.com/prometheus/prometheus/storage/local.(*MemorySeriesStorage).handleEvictList(0xc4200e52c0)
	/go/src/github.com/prometheus/prometheus/storage/local/storage.go:1029 +0x465
created by github.com/prometheus/prometheus/storage/local.(*MemorySeriesStorage).Start
	/go/src/github.com/prometheus/prometheus/storage/local/storage.go:367 +0x3da

goroutine 180 [select, 6786 minutes]:
github.com/prometheus/prometheus/storage/local.(*MemorySeriesStorage).handleQuarantine(0xc4200e52c0)
	/go/src/github.com/prometheus/prometheus/storage/local/storage.go:1639 +0x45f
created by github.com/prometheus/prometheus/storage/local.(*MemorySeriesStorage).Start
	/go/src/github.com/prometheus/prometheus/storage/local/storage.go:368 +0x3ff

goroutine 181 [select, 6786 minutes]:
github.com/prometheus/prometheus/storage/local.(*MemorySeriesStorage).logThrottling(0xc4200e52c0)
	/go/src/github.com/prometheus/prometheus/storage/local/storage.go:900 +0x838
created by github.com/prometheus/prometheus/storage/local.(*MemorySeriesStorage).Start
	/go/src/github.com/prometheus/prometheus/storage/local/storage.go:369 +0x424

goroutine 182 [select]:
github.com/prometheus/prometheus/storage/local.(*MemorySeriesStorage).loop(0xc4200e52c0)
	/go/src/github.com/prometheus/prometheus/storage/local/storage.go:1246 +0x4fe
created by github.com/prometheus/prometheus/storage/local.(*MemorySeriesStorage).Start
	/go/src/github.com/prometheus/prometheus/storage/local/storage.go:370 +0x449

goroutine 187 [select, 6786 minutes]:
github.com/prometheus/prometheus/notifier.(*Notifier).Run(0xc42009ab40)
	/go/src/github.com/prometheus/prometheus/notifier/notifier.go:205 +0x1b8
created by main.Main
	/go/src/github.com/prometheus/prometheus/cmd/prometheus/main.go:210 +0x15d9

goroutine 80 [select]:
github.com/prometheus/prometheus/storage/local.(*MemorySeriesStorage).waitForNextFP(0xc4200e52c0, 0x531d, 0x3fef2e034308a930, 0x1)
	/go/src/github.com/prometheus/prometheus/storage/local/storage.go:1133 +0x198
github.com/prometheus/prometheus/storage/local.(*MemorySeriesStorage).cycleThroughMemoryFingerprints.func1(0xc42c526120, 0xc4200e52c0)
	/go/src/github.com/prometheus/prometheus/storage/local/storage.go:1173 +0x245
created by github.com/prometheus/prometheus/storage/local.(*MemorySeriesStorage).cycleThroughMemoryFingerprints
	/go/src/github.com/prometheus/prometheus/storage/local/storage.go:1183 +0x67

goroutine 189 [semacquire, 6786 minutes]:
sync.runtime_Semacquire(0xc4204e9954)
	/usr/local/go/src/runtime/sema.go:47 +0x30
sync.(*WaitGroup).Wait(0xc4204e9948)
	/usr/local/go/src/sync/waitgroup.go:131 +0x97
github.com/prometheus/prometheus/retrieval.(*TargetManager).Run(0xc4204e98f0)
	/go/src/github.com/prometheus/prometheus/retrieval/targetmanager.go:72 +0x15e
created by main.Main
	/go/src/github.com/prometheus/prometheus/cmd/prometheus/main.go:216 +0x167d

goroutine 190 [IO wait]:
net.runtime_pollWait(0x7f2437273380, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:160 +0x59
net.(*pollDesc).wait(0xc42c532140, 0x72, 0xc42c523d10, 0xc420014180)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x38
net.(*pollDesc).waitRead(0xc42c532140, 0x2657440, 0xc420014180)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x34
net.(*netFD).accept(0xc42c5320e0, 0x0, 0x2654700, 0xc572764180)
	/usr/local/go/src/net/fd_unix.go:419 +0x238
net.(*TCPListener).accept(0xc4203520e8, 0x29e8d60800, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:132 +0x2e
net.(*TCPListener).AcceptTCP(0xc4203520e8, 0xc42c523e38, 0xc42c523e40, 0xc42c523e30)
	/usr/local/go/src/net/tcpsock.go:209 +0x49
net/http.tcpKeepAliveListener.Accept(0xc4203520e8, 0x1bbd1d8, 0xc4bf2d8000, 0x2664100, 0xc424c50150)
	/usr/local/go/src/net/http/server.go:2608 +0x2f
net/http.(*Server).Serve(0xc42019c080, 0x26638c0, 0xc4203520e8, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:2273 +0x1ce
net/http.(*Server).ListenAndServe(0xc42019c080, 0xc42019c080, 0xc42c523f78)
	/usr/local/go/src/net/http/server.go:2219 +0xb4
github.com/prometheus/prometheus/web.(*Handler).Run(0xc420201860)
	/go/src/github.com/prometheus/prometheus/web/web.go:254 +0x1f0
created by main.Main
	/go/src/github.com/prometheus/prometheus/cmd/prometheus/main.go:223 +0x16f0

goroutine 193 [select]:
github.com/prometheus/prometheus/storage/local.(*MemorySeriesStorage).waitForNextFP(0xc4200e52c0, 0x0, 0x3ff0000000000000, 0x0)
	/go/src/github.com/prometheus/prometheus/storage/local/storage.go:1133 +0x198
github.com/prometheus/prometheus/storage/local.(*MemorySeriesStorage).cycleThroughArchivedFingerprints.func1(0xc42c526180, 0xc4200e52c0)
	/go/src/github.com/prometheus/prometheus/storage/local/storage.go:1206 +0x22f
created by github.com/prometheus/prometheus/storage/local.(*MemorySeriesStorage).cycleThroughArchivedFingerprints
	/go/src/github.com/prometheus/prometheus/storage/local/storage.go:1226 +0x67

goroutine 191 [select, 6786 minutes]:
github.com/prometheus/prometheus/discovery.(*TargetSet).Run(0xc424cbf9f0, 0x7f24372a53a0, 0xc42c4f07c0)
	/go/src/github.com/prometheus/prometheus/discovery/discovery.go:183 +0x2e4
github.com/prometheus/prometheus/retrieval.(*TargetManager).reload.func1(0x7f24372a53a0, 0xc42c4f07c0, 0xc4204e98f0, 0xc424cceb10)
	/go/src/github.com/prometheus/prometheus/retrieval/targetmanager.go:116 +0x43
created by github.com/prometheus/prometheus/retrieval.(*TargetManager).reload
	/go/src/github.com/prometheus/prometheus/retrieval/targetmanager.go:119 +0x632

goroutine 213 [select]:
github.com/prometheus/prometheus/retrieval.(*scrapeLoop).run(0xc424cbfe00, 0x12a05f200, 0x12a05f200, 0x0)
	/go/src/github.com/prometheus/prometheus/retrieval/scrape.go:436 +0x3cc
created by github.com/prometheus/prometheus/retrieval.(*scrapePool).sync
	/go/src/github.com/prometheus/prometheus/retrieval/scrape.go:240 +0x3e5

goroutine 210 [select, 6786 minutes]:
github.com/prometheus/prometheus/discovery.(*TargetSet).Run(0xc424cbfbd0, 0x7f24372a53a0, 0xc42c4f08c0)
	/go/src/github.com/prometheus/prometheus/discovery/discovery.go:183 +0x2e4
github.com/prometheus/prometheus/retrieval.(*TargetManager).reload.func1(0x7f24372a53a0, 0xc42c4f08c0, 0xc4204e98f0, 0xc424cced20)
	/go/src/github.com/prometheus/prometheus/retrieval/targetmanager.go:116 +0x43
created by github.com/prometheus/prometheus/retrieval.(*TargetManager).reload
	/go/src/github.com/prometheus/prometheus/retrieval/targetmanager.go:119 +0x632

goroutine 51 [select]:
github.com/prometheus/prometheus/retrieval.(*scrapeLoop).run(0xc424c6e3c0, 0x12a05f200, 0x12a05f200, 0x0)
	/go/src/github.com/prometheus/prometheus/retrieval/scrape.go:436 +0x3cc
created by github.com/prometheus/prometheus/retrieval.(*scrapePool).sync
	/go/src/github.com/prometheus/prometheus/retrieval/scrape.go:240 +0x3e5

goroutine 50 [select]:
github.com/prometheus/prometheus/retrieval.(*scrapeLoop).run(0xc424c6e320, 0x12a05f200, 0x12a05f200, 0x0)
	/go/src/github.com/prometheus/prometheus/retrieval/scrape.go:436 +0x3cc
created by github.com/prometheus/prometheus/retrieval.(*scrapePool).sync
	/go/src/github.com/prometheus/prometheus/retrieval/scrape.go:240 +0x3e5

goroutine 53 [select]:
github.com/prometheus/prometheus/retrieval.(*scrapeLoop).run(0xc424c6e500, 0x12a05f200, 0x12a05f200, 0x0)
	/go/src/github.com/prometheus/prometheus/retrieval/scrape.go:436 +0x3cc
created by github.com/prometheus/prometheus/retrieval.(*scrapePool).sync
	/go/src/github.com/prometheus/prometheus/retrieval/scrape.go:240 +0x3e5

goroutine 54 [select, 2 minutes]:
github.com/prometheus/prometheus/retrieval.(*scrapeLoop).run(0xc424c6e5a0, 0x12a05f200, 0x12a05f200, 0x0)
	/go/src/github.com/prometheus/prometheus/retrieval/scrape.go:436 +0x3cc
created by github.com/prometheus/prometheus/retrieval.(*scrapePool).sync
	/go/src/github.com/prometheus/prometheus/retrieval/scrape.go:240 +0x3e5

goroutine 12500656 [chan send]:
github.com/prometheus/prometheus/storage/local.(*seriesMap).fpIter.func1(0xc42038d220, 0xc55cd91d40)
	/go/src/github.com/prometheus/prometheus/storage/local/series.go:133 +0xe0
created by github.com/prometheus/prometheus/storage/local.(*seriesMap).fpIter
	/go/src/github.com/prometheus/prometheus/storage/local/series.go:138 +0x67

**Comment by brian-brazil** [comment]
This is the standard dump Go produces. Is there some particular problem you#re trying to debug?
