### ISSUE TITLE
labeldrop does not work as expected

### ISSUE THREAD

**Issue by roman-vynar** [prometheus/prometheus#2367]
Prometheus 1.5.0 introduced `labeldrop` relabeling action. However, it does not work as expected.

The following config results in dropping all time series containing that label `container_label_com_amazonaws_ecs_task_arn` instead of just a single label:
```
    metric_relabel_configs
      - source_labels: [container_label_com_amazonaws_ecs_task_arn]
        action: labeldrop
```

This config does nothing to the time series and label when using something on matching regex:
```
    metric_relabel_configs
      - source_labels: [container_label_com_amazonaws_ecs_task_arn]
        regex: 'arn:.*'
        action: labeldrop
```

The same story when placing the above into `relabel_configs`.
How does it suppose to work?

Thanks.

**Comment by brian-brazil** [comment]
Source labels aren't relevant for label drop, it's applying to the label names.

It looks like you want a normal replace in this case.

**Comment by roman-vynar** [comment]
@brian-brazil thanks!

Nevermind, the syntax is:
```
      - regex: 'container_label_com_amazonaws_ecs_task_arn'
        action: labeldrop
```

**Comment by tcolgate** [comment]
To drop an individual label you can use replace with a replacement value of "". labeldrop is for bulk dropping of labels.
