### ISSUE TITLE
Error out if labeldrop/labelkeep are used with source_labels

### ISSUE THREAD

**Issue by brian-brazil** [prometheus/prometheus#2368]
This is non-nonsensical, so catch it when we parse the relabelling config.

**Comment by juliusv** [comment]
Same for target labels, regex, modulus, separator, right?

**Comment by brian-brazil** [comment]
We require the regex, nothing else should be non-default.

**Comment by roman-vynar** [comment]
I agree as this is a bit confusing [ref](https://github.com/prometheus/prometheus/issues/2367)
Usually, you have label names under `source_labels` and compare their values in `regex`.
With labeldrop, you put label names into `regex`.

**Comment by juliusv** [comment]
Right, don't know how "regex" made it into my list :)

But yeah, the many conditionally used fields in relabeling are getting a bit confusing.
