### ISSUE TITLE
I think the release I'm using is missing it's version

### ISSUE THREAD

**Issue by ds0nt** [prometheus/prometheus#2370]
**What did you do?**
prometheus -version

**What did you expect to see?**
version 1.5

**What did you see instead? Under which circumstances?**
prometheus, version  (branch: , revision: )
  build user:       
  build date:       
  go version:       go1.7.4

**Environment**
arch linux (manjaro)

* System information:
Linux 4.4.39-1-MANJARO x86_64

* Prometheus version: 
if only...

**Comment by beorn7** [comment]
Where did you get the release from?

**Comment by brancz** [comment]
Yeah I just tried this as well on linux and darwin amd64 and it seems fine from github releases of `v1.5.0`.
