### ISSUE TITLE
UI: Date/time picker in the expression browser uses local time of the browser.

### ISSUE THREAD

**Issue by beorn7** [prometheus/prometheus#2371]
While the display is in UTC as intended.

Broadly related: #1616 #500

**Comment by jjneely** [comment]
Visually this looks like the following.  (Local time was US Pacific Daylight Savings: UTC -0700)

![prometheus-time-picker 2017-09-08 12 05 00](https://user-images.githubusercontent.com/10540/30279030-04c5bc9c-96da-11e7-9c8f-fb00afbb7bd0.png)

**Comment by jjneely** [comment]
I spent some time looking at this today, but I'm not a front end developer.  I've seen conflicting google results if setting the correct timezone is just an option to the datetimepicker or not.  Is there any additional background here?

How can I help move this forward or get up to speed to build a patch?

**Comment by beorn7** [comment]
I can just say it's very annoying to not have the picker it UTC as the display. I would like to believe it should be a super easy fix but I'm not a frontend dev either.

**Comment by mattbostock** [comment]
Seems there's an undocumented timezone option:
https://github.com/Eonasdan/bootstrap-datetimepicker/issues/2118

**Comment by beorn7** [comment]
Fixed by #3182, many thanks, @yamatoya
