### ISSUE TITLE
avoiding html in console templates - markdown?

### ISSUE THREAD

**Issue by automaticgiant** [prometheus/prometheus#2372]
either at runtime or as a separate step.
i tried adding blackfriday to the web package before returning the html, but the html from the base templates/libs aren't compatible with the way markdown can include html.
i tried rendering the markdown first before handing it to prometheus, but i can't find a renderer that will ignore the template codes (`{{ blah }}`).
any suggestions for avoiding as much html as possible when doing console templates?

**Comment by brian-brazil** [comment]
The console templates are designed with html in mind, if you're running a custom fork of Prometheus then there's not much we can do on our end.
