### ISSUE TITLE
UI does not display correctly after upgrade until browser cache is cleared.

### ISSUE THREAD

**Issue by msde** [prometheus/prometheus#2379]
I recommend adding prometheus version or some other cachebuster to the names of static files such as prometheus.css

**What did you do?**

* Opened http://prometheus:9090/graph in browser
* Upgraded from 1.0.0 to 1.5.0
* Opened http://prometheus:9090/graph in browser

**What did you expect to see?**

The UI

**What did you see instead? Under which circumstances?**

Just a title bar and an "Add Graph" button.

**Environment**

MacOS Chrome 55

* System information:

	Linux 3.10.0-327.36.3.el7.x86_64 x86_64

* Prometheus version: 

prometheus, version 1.5.0 (branch: master, revision: d840f2c400629a846b210cf58d65b9fbae0f1d5c)
  build user:       root@a04ed5b536e3
  build date:       20170123-13:56:24
  go version:       go1.7.4

* Prometheus configuration file:
N/A

**Comment by sourcecube** [comment]
Hey guys.. this issue can be closed since it has been merged. ( : 
Wanted to work on it, until I realized that it was already fixed.

**Comment by grobie** [comment]
Thanks!
