### ISSUE TITLE
Prometheus 1.4.1 leaves (a lot of) sockets on scraped node in CLOSE_WAIT state

### ISSUE THREAD

**Issue by iggyzap** [prometheus/prometheus#2388]
Hi,
* Issue at hand
We are running prometheus in production and recently we've started to see situation when it kill servers under pressure by leaving scraped nodes with a lot of connections in CLOSE_WAIT state.

* Expected behaviour:
0 Connection in CLOSE_WAIT state, since prometheus should follow http and underlying protocols for correctly closing connections after scrape.

* Observations
We are observing a lot of opened sockets left in CLOSE_WAIT mode.
That's happening in AWS ap-south-1 region.

* System information:

	Linux 4.4.19-29.55.amzn1.x86_64 x86_64

* Prometheus version: 

/usr/local/prometheus/prometheus -version
prometheus, version 1.4.1 (branch: master, revision: 2a89e8733f240d3cd57a6520b52c36ac4744ce12)
  build user:       root@e685d23d8809
  build date:       20161128-09:59:22
  go version:       go1.7.3

**Comment by brian-brazil** [comment]
Further debugging indicates this is some form of bug on the exporter side causing an overload, Prometheus appears to be behaving correctly.
