### ISSUE TITLE
Data lost after restart prometheus

### ISSUE THREAD

**Issue by jofm** [prometheus/prometheus#2390]
Hi,

I'm starting using prometheus and I cannot evaluate if this is a issue or something that i'm missing. Also I can't find info about this.

I'm using Prometheus v1.5.0 with Pushgateway v0.3.1 both on linux Red Hat. 
When injecting metrics on the pushgateway I need to specify a timestamp. Everything runs well until I restart prometheus service.  After restart I notice that all values for each time period are just wrong, they simple don't match with the data before the restart.

Metric sample that go into pushgateway: 
```metric_one{metric_type="Modify",metric_sub_type="Synch"} 15 1485820800000
metric_two{metric_type="Modify",metric_sub_type="Synch"} 4 1485820800000
metric_one{metric_type="Hybrid2Pre",metric_sub_type="Hybrid2Pre"} 6 1485820800000
metric_two{metric_type="Hybrid2Pre",metric_sub_type="Hybrid2Pre"} 0 148582080000
```

I'm putting new metrics in pushgateway every hour and pushing with prometheus every 30 minutes (sync reasons with data collectors). Here's my config file:

```# my global config
global:
  scrape_interval:     30m 
  evaluation_interval: 30m 

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'codelab-monitor'

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: 'orders_stats'
    static_configs:
      - targets: ['localhost:9091']
```
 

Don't know if this has anything to do with some kind of prometheus data aggregation that just go rogue because of the "forced" timestamp or some missing configuration.

Thanks in advance.

**Comment by brian-brazil** [comment]
A 30m scrape interval is going to run you into staleness issues. 2m is the practical maximum.

**Comment by jofm** [comment]
Thanks for the reply @brian-brazil 

Does staleness issues affect the already collected data?

Below is a sample of my dashboard before and after restart prometheus for a better understanding.

The chart on the left uses influxdb as datasource and the one on the right is using prometheus. Both are sync.

Before restart (data between both graph are sync):
![before restart](https://cloud.githubusercontent.com/assets/25510815/22589711/937c4f7a-ea03-11e6-8021-f0f088b05352.png)

After restart (prometheus data went rogue):
![after_restart](https://cloud.githubusercontent.com/assets/25510815/22589737/a9aea784-ea03-11e6-8247-a160b7b4957d.png)

KPI metric is calculated using the other two, under_5 and above_5 -  under_5/(under_5+above_5) * 100
Metics values just change completely after restart.

Regards

**Comment by brian-brazil** [comment]
No, the data is still there but queries may have unexpected issues such as gaps.

**Comment by jofm** [comment]
Ok, but shouldn´t I experience that without a restart also?

**Comment by brian-brazil** [comment]
I'm presuming the restart is unrelated.

**Comment by rathohit311356** [comment]
How can we keep data file persistent ? 
When we start Prometheus data gets deleted and new service start pulling data from scratch,
How can I configure to have my data persistent, I know about storage local path flag but no clue how to make my Prometheus data file persistent, please help advising

**Comment by krasi-georgiev** [comment]
@rathohit311356 sound like you have a lot of reading to do :rabbit:  , 
I would advise starting from the docs.
https://prometheus.io/docs/introduction/overview/
