### ISSUE TITLE
Join two metrics as label to some other metric [HELP/DIRECTIONS needed]

### ISSUE THREAD

**Issue by mohanprasaths** [prometheus/prometheus#2393]
Hi,
      I would like to make a join operation between two metrics and expect the metric values to be in single response.

Consider this situation :
**ifOutOctets** - which gives number of packets transmitted 
(Response is << _****`_ifOutOctets{ifAlias="bond1v4@bond1",ifDescr="bond1v4",ifIndex="8",ifName="bond1v4",instance="169.53.135.170",job="Vyatta"}	value :	75392868_`****_ >>)

**ifInOctets** - which gives number of packets received
(Response is << _**`ifInOctets{ifAlias="bond1v4@bond1",ifDescr="bond1v4",ifIndex="8",ifName="bond1v4",instance="169.53.135.170",job="Vyatta"}  value: 8996220`**_>>)

**ifSpeed** - gives speed of interface
(Response is << _**`_ifSpeed{ifAlias="bond1v4@bond1",ifDescr="bond1v4",ifIndex="8",ifName="bond1v4",instance="169.53.135.170",job="Vyatta"}	value :	100000000_ `**_>>)

I would like to join all these metrics to be queried using a single query and expected response be like 
_**` (ifSpeed{ifAlias="bond1v4@bond1",ifDescr="bond1v4",ifIndex="8",ifName="bond1v4",instance="169.53.135.170",job="Vyatta",ifInOctets:"8996220",ifOutOctets="75392868"}	value :	100000000`**_)

I can add ifInOctets and ifOutOctets as lookups in ifSpeed but that would create new time series data for each and every change in ifInOctets and ifOutOctets . 
Please let me know if there is any other way to join these queries . Thanks in advance.

**Comment by brian-brazil** [comment]
This is not possible, values can't become labels. It sounds like whatever you're using to process this data needs to be able to handle multiple queries.

**Comment by mohanprasaths** [comment]
Thanks a lot @brian-brazil  .
