### ISSUE TITLE
 sum_over_time on range queries. 

### ISSUE THREAD

**Issue by kiranalii** [prometheus/prometheus#2394]
Hi,

I want to use sum_over_time on range queries. But it's not working.

I tried these queries

`http://localhost:9093/api/v1/query_range?query=sum_over_time(go_gc_duration_seconds&start=2017-02-01T19:03:40.0Z&end=2017-02-02T09:03:04.0Z&step=15s)`

Error Message:

`{
  "status": "error",
  "errorType": "bad_data",
  "error": "cannot parse \"15s)\" to a valid duration"
}`

`http://localhost:9093/api/v1/query_range?query=sum_over_time(go_gc_duration_seconds)&start=2017-02-01T19:03:40.0Z&end=2017-02-02T09:03:04.0Z&step=15s`

`{
  "status": "error",
  "errorType": "bad_data",
  "error": "parse error at char 39: expected type range vector in call to function \"sum_over_time\", got instant vector"
}`

Help would be appreciated 
Thanks

**Comment by kiranalii** [comment]
This query is working 

`http://localhost:9093/api/v1/query_range?query=sum_over_time(go_gc_duration_seconds[1s])&start=2017-02-01T19:03:40.0Z&end=2017-02-02T09:03:04.0Z&step=15s`

But i don't know what is difference between [1s] and step size.
Help would be appreciated. Thanks

**Comment by beorn7** [comment]
Disclaimer: I don't think your query makes any sense semantically.

Purely syntactically: `sum_over_time(...[1s])` sums up all sample values between "now" and "now - 1s", where "now" is the evaluation time of the query. (Note that a typical scrape interval is ~1m, so most likely, there will be no sample in the 1s interval you are summing over.)

The `step` parameter in the API query tells Prometheus for which times the PromQL query should be evaluated, or in other words, what value "now" should have.

**Comment by kiranalii** [comment]
Thanks @beorn7, thakns for explaining [1s] and step size difference. Got it thanks
