### ISSUE TITLE
Add graph button throws Handlebar Exeception

### ISSUE THREAD

**Issue by medyagh** [prometheus/prometheus#2399]
**What did you do?**

Click on Add Graph

**What did you expect to see?**
Anything to happen (a graph to be added or aything)

**What did you see instead? Under which circumstances?**
Nothing.  and I get these exceptions in chrome inspect:

in chrome's inspect I see

```
Uncaught ReferenceError: Handlebars is not defined
    at graph.js:6
```
that line is

`Handlebars.registerHelper('pathPrefix', function() { return PATH_PREFIX; });`

**Environment**
Mac OS, Chrome, and I used prometheus-1.5.0.darwin-amd64 version.

* System information:

	Darwin 15.6.0 x86_64

* Prometheus version: 
```
	prometheus, version 1.5.0 (branch: master, revision: d840f2c400629a846b210cf58d65b9fbae0f1d5c)
  build user:       root@a04ed5b536e3
  build date:       20170123-13:59:53
  go version:       go1.7.4
```

screenshots 
<img width="296" alt="screen shot 2017-02-06 at 10 21 17 am" src="https://cloud.githubusercontent.com/assets/4564227/22655915/51d90242-ec57-11e6-8bc1-579157bfba01.png">
<img width="974" alt="screen shot 2017-02-06 at 10 14 39 am" src="https://cloud.githubusercontent.com/assets/4564227/22655918/54a5e9e0-ec57-11e6-907f-d0b0a70290f9.png">

**Comment by bvis** [comment]
I've found this same issue when Prometheus is deployed under a path. For example:

- https://prometheus.domain.com/ <- OK
- https://my.domain.com/prometheus <- KO

It could be related with this line: https://github.com/prometheus/prometheus/blob/7daa21eeb6ccbe628839c5c07704e0f1d7801992/web/ui/static/js/graph.js#L823

Where `PATH_PREFIX` wouldn't have any value.

**Comment by h0tbird** [comment]
Same thing exposing via Kubernetes API server + `kubectl proxy`:
```
[0] ~ >> kubectl cluster-info --namespace monitoring | grep Prometheus
Prometheus is running at https://104.155.8.87/api/v1/proxy/namespaces/monitoring/services/prometheus
```

![add_graph](https://cloud.githubusercontent.com/assets/417440/22973471/0f23d1f6-f37e-11e6-9efc-dcb7b76d480b.png)

**Comment by h0tbird** [comment]
Setting `-web.external-url` to the value below makes the _WebUI_ unreachable.
```
-web.external-url=http://127.0.0.1:8001/api/v1/proxy/namespaces/monitoring/services/prometheus
```

However, I managed to reach the `/graph` endpoint by setting `PATH_PREFIX='http://127.0.0.1:8001/api/v1/proxy/namespaces/monitoring/services/prometheus'`

![debug](https://cloud.githubusercontent.com/assets/417440/23019702/0042c9aa-f444-11e6-96be-ddd494a9e254.png)

**Comment by brian-brazil** [comment]
This might be a bug, this might be the kubeproxy doing something that's fundamentally unsupportable. Requires investigation.

**Comment by brian-brazil** [comment]
This sounds like it was an issue with external url/route configuration for Prometheus rather than a bug, so closing. If that wasn't the case, please let us know.
