### ISSUE TITLE
[Config] Switch whitelist of Consul services to blacklist

### ISSUE THREAD

**Issue by yannispanousis** [prometheus/prometheus#2402]
**What did you expect to see?**

I'm integrating Prometheus with Consul for service discovery and following [this config](https://prometheus.io/docs/operating/configuration/#consul_sd_config)

**What did you see instead? Under which circumstances?**

I expected to be able to rule out services I don't care to discover. Instead the configuration file only allows a whitelist. That effectively neutralises the usefulness of the service discovery, because now I have to keep the Prometheus scrape list up-to-date, whereas if it was a blacklist then I would only have to change that list for services I don't care about.

**Comment by brian-brazil** [comment]
You can use a drop relabel action to do this.

**Comment by yannispanousis** [comment]
Nice! That looks like some powerful stuff. (Just setting up the stack now so wasn't aware of this). Thanks man.

**Comment by brian-brazil** [comment]
You're welcome.
