### ISSUE TITLE
Prometheus kubernetes object statistics are not collected with coreOS

### ISSUE THREAD

**Issue by sugun999** [prometheus/prometheus#2405]
Hi,

I am trying to collect statistics of kubernetes objects with prometheus. I have setup kubernetes with coreOS.
Used this file https://github.com/coreos/blog-examples/blob/master/monitoring-kubernetes-with-prometheus/prometheus.yml to run prometheus as pod.

My pods are running under "fast-local" namespace(where as prometheus pod is running under default namespace) and I specified below annotations with each of my pods and I am able to access these pods with services that I created with kubernetes.

annotations:
prometheus.io/scrape: "true"
prometheus.io/port: "1111"

I would expect to see successful statistics of my custom pods with prometheus UI. But it shows below error.

![error](https://cloud.githubusercontent.com/assets/24804615/22697573/82979d0e-ed5a-11e6-8a6c-6ee8a379f260.PNG)

Am I missing anything? Do I need to run cAdvisor/heapster to collect statistics?

**Comment by brian-brazil** [comment]
Are you sure the /metrics is in the Prometheus format?

**Comment by sugun999** [comment]
Hi,

How I can check this? Is there any guide?

**Comment by gianrubio** [comment]
@sugun999 in the first job you're not scrapping a prometheus endpoint, to verify just click in the first link http://10.2.36... and check

the second error is related a network problem, check if prometheus can reach the hosts.

**Comment by fabxc** [comment]
Assuming this is resolved.
