### ISSUE TITLE
Frendly alert names?

### ISSUE THREAD

**Issue by danisabad** [prometheus/prometheus#2407]
Hello.

Is it possible to give more human readable names to alerts? It would be nice to have spaces and other symbols like (,),[,],",'. Now all these gives `parse error at line X, char X: unexpected string X`.

Now best I can think of is, for example, 'File_system_space_available_percentage' or 'FileSystemSpaceAvailablePercentage' - which obviously isn't that convenient.

* Prometheus version: 

```
prometheus, version 1.5.0 (branch: master, revision: d840f2c400629a846b210cf58d65b9fbae0f1d5c)
  build user:       root@a04ed5b536e3
  build date:       20170123-13:56:24
  go version:       go1.7.4
```

* Logs:
```
time="2017-02-08T11:45:17+01:00" level=error msg="Failed to apply configuration: error loading rules, previous rule set restored: error parsing sample.rule: parse error at line 18, char 8: unexpected string \"\\\"Filesystem Space\"... in alert statement, expected identifier" source="main.go:275"
```

**Comment by brian-brazil** [comment]
There's no plans to change the limitations on alert names. Longer names would be harder to read on devices such as pagers where space is limited.

You can add more information using annotations.

**Comment by juliusv** [comment]
Closing as there are no plans to change this.
