### ISSUE TITLE
Issues when creating docker image from source code

### ISSUE THREAD

**Issue by xbblq7n** [prometheus/prometheus#2428]
Hi,

I am trying to convert the source code of the prometheus in to the docker image. when i try to build it with the
**Step1: docker build -t (name) . command, i am getting the below error**
Stp3 : COPY prometheus /bin/prometheus
lstat prometheus: no such file or directory

**Step 2: In order to overcome this issue, i am placing the docker file outside prometheus directory.
/root/prometheus**
Now i am getting this below error
Stp4 : COPY promtool /bin/promtool
lstat promtool: no such file or directory

Please advise

-Regards,
Vivek

**Comment by sdurrheimer** [comment]
The docker image doesn't self-compile the project, you need to compile it before building the docker image.

**Comment by brian-brazil** [comment]
Usage questions should be asked at https://groups.google.com/forum/#!forum/prometheus-users
