### ISSUE TITLE
image for s390x platform

### ISSUE THREAD

**Issue by XiLongZheng** [prometheus/prometheus#2437]
**What did you do?**
I am trying to build quay.io/prometheus/prometheus:v1.4.1 image for s390x platform, but I didn't have busybox:uclibc image for s390x, what I had is busybox:glibc, is it OK to use busybox:glibc to replace busybox:uclibc as base image?

**Environment**
s390x
* System information:
Ubuntu 16.04 running on s390x (IBM LinuxONE)
	insert output of `uname -srm` here
Linux 4.4.0-59-generic s390x
* Prometheus version: 
v1.4.1

**Comment by brian-brazil** [comment]
I'm afraid that none of the prometheus developers work with this platform. If there's a PR with a small tweak to allow for this we'd be happy to review it, but realistically we're unlikely to be able to help with this directly.
