### ISSUE TITLE
jquery 1.11.2 should be updated

### ISSUE THREAD

**Issue by samueletonon** [prometheus/prometheus#2439]
Description:  while running require.js chrome addon i went on my prometheus 1.5.0 and got a warning for /static/vendor/js/jquery.min.js  pointing to 

Info: https://github.com/jquery/jquery/issues/2432 
http://blog.jquery.com/2016/01/08/jquery-2-2-and-1-12-released/

* Prometheus version: 
prometheus, version 1.5.0 (branch: master, revision: d840f2c400629a846b210cf58d65b9fbae0f1d5c)
  build user:       root@a04ed5b536e3
  build date:       20170123-13:56:24
  go version:       go1.7.4

**Comment by Gouthamve** [comment]
The relevant files that need updating are here: https://github.com/prometheus/prometheus/tree/master/web/ui/static/vendor/js

Update those and run `make assets` to get the new version.

@samueletonon Do you want to give this a try?

**Comment by Gouthamve** [comment]
Closed in #3183
