### ISSUE TITLE
Use custom user agent

### ISSUE THREAD

**Issue by grobie** [prometheus/prometheus#2440]
Prometheus currently uses the default golang HTTP user agent `Go-http-client/1.1`. In order to unambiguously identify scrape requests, it'd be helpful to see a custom Prometheus user agent.

**Comment by matthiasr** [comment]
How does that relate to the Accept header that it sends?

**Comment by brian-brazil** [comment]
It wouldn't. This helps users debugging issues by making it easier to identify requests from Prometheus servers.

**Comment by matthiasr** [comment]
:+1:

**Comment by agaoglu** [comment]
PR sets a custom user agent, though i'm not sure about the name. Default was `Go-http-client/1.1` proposed is `Prometheus-scraper/1.0`. Is that any good?

**Comment by grobie** [comment]
I had something like "Prometheus v1.5.2" in mind. I'm open to more specific
agent identifiers like including "-scraper" of people think that removes
confusion.

**Comment by agaoglu** [comment]
Updated PR to make use of build version.
