### ISSUE TITLE
sum by, irate and __name__ question

### ISSUE THREAD

**Issue by matejkramny** [prometheus/prometheus#2441]
**What did you do?**

I have data like:

```
system_cpu_system
system_cpu_user
system_cpu_steal
...
```

```
sum by(__name__)(irate({__name__=~"system_cpu_(system|user|steal|softirq|nice|iowait)"}[10s]))
```

<img width="1088" alt="screen shot 2017-02-21 at 22 53 25" src="https://cloud.githubusercontent.com/assets/797608/23200451/42034178-f889-11e6-86b8-be722c95b258.png">

**What did you expect to see?**

```
sum by(__name__)({__name__=~"system_cpu_(system|user|steal|softirq|nice|iowait)"})
```

<img width="1089" alt="screen shot 2017-02-21 at 22 52 49" src="https://cloud.githubusercontent.com/assets/797608/23200411/061e7e84-f889-11e6-890d-737ed03e1c0a.png">

**What did you see instead? Under which circumstances?**

The `__name__` label (?) gets lost when using the `irate` function. There is ingestable data by `irate` as you can see:

<img width="1096" alt="screen shot 2017-02-21 at 22 56 16" src="https://cloud.githubusercontent.com/assets/797608/23200546/bffa8c4e-f889-11e6-921e-719659322d18.png">

I think I might not be doing this right, or this might be a bug.. I don't know how better to ask. I looked through numerous docs and tried many variations. Please help!

**Comment by matejkramny** [comment]
I can do this manually, but I'd like to know how it's possible using `sum by`

<img width="766" alt="screen shot 2017-02-21 at 23 16 47" src="https://cloud.githubusercontent.com/assets/797608/23200930/f2cd771a-f88b-11e6-8726-bc87eba6eea0.png">

**Comment by brian-brazil** [comment]
When you apply a function to a metric, it's no longer that metric. Thus the name is removed. You need to do this by hand as you've figured out.

I'd suggest using the node exporter to get these metrics, as it has labels which make the processing easier.

**Comment by matejkramny** [comment]
Ok I see. My targets are `firehol/netdata`.

Thanks for responding & making this awesome project!
