### ISSUE TITLE
Query: Is Prometheus accepting GSoC proposals?

### ISSUE THREAD

**Issue by Gouthamve** [prometheus/prometheus#2451]
I am a student and I just saw CNCF on the GSoC org's list. I was wondering if Prometheus is a part too and if you were open for proposals.

https://summerofcode.withgoogle.com/organizations/6540924424290304/

**Comment by caniszczyk** [comment]
@Gouthamve we are tracking CNCF project related ideas here:

https://github.com/cncf/soc#prometheus

**Comment by Gouthamve** [comment]
Sorry, the official site listed some other list. Thanks. I will leave this open incase someone else has the same question.
