### ISSUE TITLE
a question about prometheus example.rules 

### ISSUE THREAD

**Issue by xuxiali13** [prometheus/prometheus#2456]
_The problems of scene description:_
the prometheus collect the bandwidth from nginx, and it will send alert message to alertmanager when bandwidth reached the threshold seted, also, alertmanager send alert to nginx meanwhile. 
I make http requests to nginx, and the bandwidth prometheus collected is display: 
       _job="prometheus",servername="www.at.com"}      611005
       job="prometheus",servername="www.bt.com"}      400732_

If I config "example.rules" as follows:

prometheus:ngx_bandwidth:sum = sum(ngx_bandwidth) by (job,servername)
ALERT APINGXBANDWIDTH
  **IF prometheus:ngx_bandwidth:sum{servername="www.at.com"} > 100**
  FOR 2s
  LABELS { service = "bandwidth" }
  ANNOTATIONS {
    summary = "{{ $labels.job }} {{$labels.value}}",
    description = "{{ $value }}",
  }
the alertmanager will receive the alert message from prometheus. 

But, ,If I config "example.rules" as follows:
prometheus:ngx_bandwidth:sum = sum(ngx_bandwidth) by (job,servername)
ALERT APINGXBANDWIDTH
  **IF prometheus:ngx_bandwidth:sum{servername="www.at.com"} + prometheus:ngx_bandwidth:sum{servername="www.bt.com"}> 100**
  FOR 2s
  LABELS { service = "bandwidth" }
  ANNOTATIONS {
    summary = "{{ $labels.job }} {{$labels.value}}",
    description = "{{ $value }}",
  }
the alertmanager cann't receive the alert message from prometheus .
why? help me, thanks.

**Comment by beorn7** [comment]
> prometheus:ngx_bandwidth:sum{servername="www.at.com"} + prometheus:ngx_bandwidth:sum{servername="www.bt.com"}

This expression is an addition of matching vector elements. Since there are no matching vector elements, the result is empty, and the alert doesn't fire.

What you want is an aggregation:

```sum(prometheus:ngx_bandwidth:sum{servername=~"www\\.(at|bt)\\.com"}) without (servername)```

In different news, it makes more sense to ask quastions like this on the [prometheus-users mailinglist](https://groups.google.com/forum/#!forum/prometheus-users") rather than filing a GitHub issue.
