### ISSUE TITLE
Displayed graphs not mapped reliably to URL

### ISSUE THREAD

**Issue by fabxc** [prometheus/prometheus#2463]
The writing of open query graphs to the URL seems to randomly drop some of them. This mostly happens when 6+ graphs are open and I copy&paste the URL to a new tab.

All graphs boxes are shown but some are randomly missing the query string. Not sure whether we are hitting URL length limits or the JS code is just wrong.

**Comment by brian-brazil** [comment]
That sounds like the URL length limit to me.

**Comment by grobie** [comment]
Can't reproduce, URLs with 7 shorter expressions work fine. @fabxc do you have an example.

**Comment by brian-brazil** [comment]
I'm presuming this is the url length, which we can't do much about.
