### ISSUE TITLE
Why UP service returns 0 even if the service is active

### ISSUE THREAD

**Issue by bogdanb07** [prometheus/prometheus#2464]
Hi guys,

UP service return 0 even if the service is active.

In the yaml file i have multiple k8s clusters configured (over 500 targets in prometheus). Each cluster had scrape_interval: 15s.

Is this interval too small for all targets to scan them and this is the reason why sometimes the UP returns 0 ?

[log.txt](https://github.com/prometheus/prometheus/files/813383/log.txt)

**Comment by beorn7** [comment]
15s is not too fast. Your server might still have trouble of some kind.

There are a lot of possible reasons why scrapes are occasionally failing.

Please discuss this on the [prometheus-users](https://groups.google.com/forum/#!forum/prometheus-users) mailing list. It's easier to find people that could help you there.
