### ISSUE TITLE
Data accessible via API

### ISSUE THREAD

**Issue by brancz** [prometheus/prometheus#2467]
Most of the data that is displayed via the web UI is also accessible via the API, however, some information is still missing. I would like to use this issue to collect the missing parts.

A possibly non exhaustive list I've been able to come up with that is still missing:

* runtime information shown on `/status`
* flags on `/flags` :heavy_check_mark: 
* currently pending/firing alerts :heavy_check_mark: 
* loaded config :heavy_check_mark: 
* loaded rules :heavy_check_mark: 

Anything I'm missing?

@beorn7 @brian-brazil @fabxc @juliusv

**Comment by beorn7** [comment]
It's basically everything under the _Status_ tab, i.e. not only `/status` but also `/flags`, `/config`, `/rules`, `/targets`. Not sure if any of those can already be queried via the API.

**Comment by brian-brazil** [comment]
We have to be a little careful with some of those, as things like rule groups will likely change the formats even if the feature itself was backwards compatible.

**Comment by brancz** [comment]
@brian-brazil Agreed. For rules and config I was thinking for a start to really just expose the loaded string source.

@beorn7 `/targets` and `/alertmanagers` already exists on the API and was released in `v1.5.0`, but the others I agree with.

**Comment by mxinden** [comment]
I will start working on the `/status/config` endpoint exposing the currently loaded config as displayed in the UI.

**Comment by brian-brazil** [comment]
How much is left here?

**Comment by mxinden** [comment]
@brian-brazil In regards to exposing the status: Still working on https://github.com/prometheus/prometheus/pull/2711.

**Comment by mxinden** [comment]
> How much is left here?

With https://github.com/prometheus/prometheus/pull/2711 merged, the loaded config can be retrieved via the API.

I will update the initial issue description. @brancz hope you don't mind.

I will see what I can do in regards to "currently pending/firing alerts" following up on https://github.com/prometheus/prometheus/pull/4012 and https://github.com/prometheus/prometheus/pull/3656.

**Comment by brancz** [comment]
@mxinden Go for it.

**Comment by mxinden** [comment]
> How much is left here?

With https://github.com/prometheus/prometheus/pull/4318 merged, I updated the top level issue:

> * currently pending/firing alerts :heavy_check_mark: 
> * loaded rules :heavy_check_mark:

**Comment by vn-ki** [comment]
Hi, I would like to work on this issue.

**Comment by vn-ki** [comment]
> flags on `/flags`

If I'm not wrong, #3864 added this (`v1/status/flags`). This means only runtime stats are remaining.

**Comment by brancz** [comment]
Correct. Will mark as done.

**Comment by roidelapluie** [comment]
I think this can be closed.

**Comment by codesome** [comment]
I can see runtime information at `/status` but I also see an open PR for this https://github.com/prometheus/prometheus/pull/5165 which tries to add some stuff which is already present. Not sure what else is left to be added. Closing this for now and can be reopened if needed.
