### ISSUE TITLE
High CPU Usage with Recording Rules and ZK Patch

### ISSUE THREAD

**Issue by jjneely** [prometheus/prometheus#2481]
**What did you do?**

I grabbed Prometheus 1.5.2 and applied the ZK patch from PR #2470, built and tested it.  Next I had a team use the new version who monitors a pretty healthy list of Aurora (ZooKeeper discovery) jobs, and healthy usage of recording rules.  We saw an immediate jump in CPU compared to the prior Prometheus version (1.2.1).  It started taking all CPU resources we granted to the Aurora job running it.

<img width="1440" alt="prometheus-zk-cpu-bug" src="https://cloud.githubusercontent.com/assets/10540/23671944/0dfb044e-033b-11e7-9e48-bc1bece5dd9b.png">

**What did you expect to see?**

As the configuration was unchanged, we expected to see similar CPU usage from prior versions.

**What did you see instead? Under which circumstances?**

CPU usage appears normal when I attempted to reproduce with just the `prometheus.yml` config file copied over to my test environment.  CPU usage was under 2 cores.  However, when I added the recording rules to my test environment the CPU usage spiked up to 17 cores on my test hardware.  This bare metal server now runs at a load of 17+.

I got out the profiling tools to take a look and produced the following SVG:

![p-test pprof](https://cloud.githubusercontent.com/assets/10540/23672212/ef114bbe-033b-11e7-88c6-f91f2047057f.png)

Why would recording rules cause more time to be spent in ZookeeperDiscovery?

**Environment**

My test hardware is Ubuntu Trusty running kernel 3.13.0-85-generic.  64G RAM and 24 cores.

Prometheus was compiled with Go 1.7.4.

* System information:

	Linux 3.13.0-85-generic x86_64

* Prometheus version: 

	prometheus, version 1.5.2 (branch: foo, revision: 1.5.2-1+JENKINS~trusty.20170306212211)
          build user:       jjneely@42lines.net
          build date:       2017-03-06T21:22:40Z
          go version:       go1.7.4

* Prometheus configuration file:

[prometheus-test.txt](https://github.com/prometheus/prometheus/files/825436/prometheus-test.txt)

* Prometheus Rules:

[prometheus-test.rules.txt](https://github.com/prometheus/prometheus/files/825461/prometheus-test.rules.txt)

**Comment by jjneely** [comment]
Testing with this a bit more, this condition happens not with the addition of recording rules, but when I SIGHUP Prometheus to reload its rules.

**Comment by StephanErb** [comment]
Where you even doing a SIGHUP for the Prometheus 1.2.1 setup? If I am not mistaken it was not even working there. At least for us it always ended up in crashes when combining ZK service discovery and reloads.

In addition, happened this after a single reload or only after multiple ones? Maybe we are missing a necessary cleanup of old watcher or something like this.

**Comment by jjneely** [comment]
Yeah, later resting reveals that this affects 1.2.1 as well.  Maybe not as badly, as reloads are not uncommon.  But yeah, there's some cleanup that's not working here.

**Comment by StephanErb** [comment]
I am able to reproduce the issue with Prometheus 1.6.0. 

Observations after a SIGHUP:

* CPU utilisation jumps significantly, maxing out the host.
* Discovered targets drop out of `/targets`.
* While it was constant before, the `prometheus_treecache_watcher_goroutines` is now increasing steadily. 
* After a while, CPU utilisation drops, targets show up, and `prometheus_treecache_watcher_goroutines` stays constant again, until we send the next SIGHUP

**Comment by StephanErb** [comment]
@jjneely I have filed the pull request #2669 with a fix. Would be great if you could give it a test run as well.
