### ISSUE TITLE
Prometheus quit via url

### ISSUE THREAD

**Issue by mg03** [prometheus/prometheus#2482]
**What did you do?**

curl -X POST localhost:9090/-/quit

**What did you expect to see?**

Prometheus to stop

**What did you see instead? Under which circumstances?**

Prometheus keeps running and I get 404 page not found for ```/-/quit```

**Environment**

ubuntu 14.04

* System information:

	insert output of `uname -srm` here

Linux 4.4.0-64-generic x86_64

* Prometheus version: 

	insert output of `prometheus -version` here

prometheus -version
prometheus, version 1.5.2 (branch: master, revision: bd1182d29f462c39544f94cc822830e1c64cf55b)
  build user:       root@a8af9200f95d
  build date:       20170210-14:41:22
  go version:       go1.7.5

* Alertmanager version:

	insert output of `alertmanager -version` here (if relevant to the issue)

* Prometheus configuration file:
```
insert configuration here
```

* Alertmanager configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
curl -X POST localhost:9090/-/quit
404 page not found
```

**Comment by beorn7** [comment]
Could you elaborate your use case? Why do you need this?

**Comment by juliusv** [comment]
Since allowing remote shutdown is a bit risky, you need to start Prometheus with the `-web.enable-remote-shutdown` flag to enable this. It works for me with that flag, so closing.
