### ISSUE TITLE
Filter and Drop Metric in Prometheus

### ISSUE THREAD

**Issue by jroshanfdo** [prometheus/prometheus#2484]
Hi,

I am trying to filter and drop a set of metrics in prometheus.

Existing Metrics List:
test_metrics{name="a"}
test_metrics{name="b"}
test_metrics{name="c"}
test_metrics{name="d"}
test_metrics{name="e"}

I would like to drop b , c & d then have
Expected solution - 
test_metrics{name="a"}
test_metrics{name="e"}

Please let me know if it is feasible

**Comment by brian-brazil** [comment]
Usage questions will get the best responses on the mailing list: https://groups.google.com/forum/#!forum/prometheus-users
