### ISSUE TITLE
Dynamic retention - data gets less granular with time

### ISSUE THREAD

**Issue by waqark3389** [prometheus/prometheus#2485]
I have an interesting question. If I keep 6 months worth of metrics, e.g. cpu usage. This fills up disk unnecessary disk space as I dont really want to see what the cpu usage was like 5 months ago at a particular minute. Would it be possible to consolidate or roll up all points in a series past a certain time period, roll them up by averaging daily and store just one value for that day instead of every scrape result. 

Essentially data is deleted (for disk space and performance) but an average for a day is kept in. 

I want to keep 6 months worth of data but dont really want to see a very granular view of what happened 6 months ago

**Comment by beorn7** [comment]
There is no downsampling implemented right now, and it's not really planned either.

You can emulate the setup by having a long-term Prometheus federating at larger intervals from your short-term Prometheus.

Note that larger scrape intervals lead to worse compression, so the returns of downsampling are somewhat diminished.

Finally, I recommend to discuss questions like this on the [prometheus-users](https://groups.google.com/forum/#!forum/prometheus-users) mailing list.
