### ISSUE TITLE
Strange behavior of 'count'

### ISSUE THREAD

**Issue by kehao95** [prometheus/prometheus#2489]
I have totally no idea what was going on here. So I will just describe how I tried this and what did I see.
I was trying to calculate the cpu_load pre-CPU using the metrics exported by the node_expoter.
So I calculated as this:
```
{pre_cpu_load by instance}
= A/B
=  {load1 by instance}/{number of CPU by instance}
=  {load1 by instance}/{count of {all cpu} by instance}
# So the query is: 
node_load1 / (count by(instance)(count by(instance, cpu)(node_cpu)))
```
**What did I do?**
In the prometheus web interface, exec
```node_load1 / (count by(instance)(count by(instance, cpu)(node_cpu)))``` 
'no data'
for debug I specific the instance id and tear this apart:
Here is some experiments:

|label|query|expect|result|
|---|---|---|--|
|A|node_load1{instance="xxxxx"}|0.3|0.3|
|A'|node_load1|[0.3,0.3,0.3]|[0.3,0.3,0.3]|
|A+1|~|1.3|1.3|
|B|count by(instance)(count by(instance, cpu)(node_cpu{instance="xxxx"}))|4|4|
|B'|count by(instance)(count by(instance, cpu)(node_cpu))|[2,2,4]|[2,2,4]|
|B+1|~|5|5|
|A/B|node_load1{instance="xxxxx"}/(count by(instance)(count by(instance, cpu)(node_cpu{instance="xxxx"})))|0.075|**no data**|
|A'/B'|node_load1 / (count by(instance)(count by(instance, cpu)(node_cpu)))|[2,2,2,4]|**no data**|

**Environment**

* System information:
`Linux 4.4.35-33.55.amzn1.x86_64 x86_64`
* Prometheus version: 
```
prometheus, version 1.5.2 (branch: master, revision: bd1182d29f462c39544f94cc822830e1c64cf55b)
  build user:       root@a8af9200f95d
  build date:       20170210-14:41:22
  go version:       go1.7.5
```

**Comment by kehao95** [comment]
Two more instersting things here may be helpful.
The incident of the result column is also 'broken'
<img width="953" alt="screen shot 2017-03-10 at 11 36 37 am" src="https://cloud.githubusercontent.com/assets/6213976/23781363/c1000c08-0587-11e7-9b82-489a2fd13e4a.png">

There is a result of '4' in Query B but the graph did show it correctly. The line seemed to dorped off the graph.
<img width="665" alt="screen shot 2017-03-10 at 11 54 10 am" src="https://cloud.githubusercontent.com/assets/6213976/23781443/5a156c62-0588-11e7-86ff-c8d63b9f29be.png">

**Comment by brian-brazil** [comment]
For usage questions, https://groups.google.com/forum/#!aboutgroup/prometheus-users is the best place to get answers.

**Comment by kehao95** [comment]
Well, I think this may be a bug. So I report it. Could you plz take another look?
In brief, I came across a situation where I got a query 'A' with result of a. And query 'B' with result of b.
But when I query 'A/B' I got no data

**Comment by beorn7** [comment]
It is not a bug.

You need to understand label matching, see https://prometheus.io/docs/querying/operators/#vector-matching .

If you discuss this questions on the mailing list, other users can benefit from the answers.

**Comment by kehao95** [comment]
Oh sorry, thank you for your reply.
