### ISSUE TITLE
Scrape fails with connection reset by peer

### ISSUE THREAD

**Issue by iobestar** [prometheus/prometheus#2495]
I have targets migrated from Jetty 9.2 to 9.3 and scraping start failing with exception: connection reset by peer.

If Jetty 9.2 is used on target then scraping doesn't fail.

It seems that Go http client in Prometheus Server doesn't work well with Jetty 9.3 "half-closed" connections.

This is probably related to https://github.com/eclipse/jetty.project/issues/359

Can anyone else confirm this issue?

**Comment by brian-brazil** [comment]
Do you have reason to believe that Prometheus is acting incorrectly here?

**Comment by iobestar** [comment]
Problem solved on server side. Go HTTP client handle connection closing correctly.
