### ISSUE TITLE
[Question] is it possible to transfer data via HTTPS ?

### ISSUE THREAD

**Issue by JeromeVi** [prometheus/prometheus#2505]
Hi,
It's not an issue but a question, I use a Grafana application that read data from multiple Prometheus datasources. The thing is that the data are send via HTTP and I want to secure this transfert.

Is it a way to do it in HTTPS ? Or an other method ?

Thank you for your inputs

**Comment by brian-brazil** [comment]
Usage questions are best asked at https://groups.google.com/forum/#!aboutgroup/prometheus-users
