### ISSUE TITLE
Consider passing down scrape timeout as header

### ISSUE THREAD

**Issue by brian-brazil** [prometheus/prometheus#2508]
I'd like to propose passing the scrape timeout down as a header when scraping. For exporters like snmp and blackbox it'd be good if the user didn't have to set timeouts in two places. More generally for expensive exporters, it'd be good to stop querying when the other side has given up. Whether this would ever be exposed to client libraries is a separate question.

This would be something like:

```
Scrape-Timeout-Seconds: 10.0 
```

**Comment by fabxc** [comment]
Why a header?
We should decide for either headers or query params. Given that we also discussed things like label selectors already, query params make the most sense.

**Comment by brian-brazil** [comment]
Headers could be automatic, whereas url parameters are currently explicitly configured by the user.

**Comment by fabxc** [comment]
Anything in the way of us adding default url params?

**Comment by brian-brazil** [comment]
It doesn't seem quite as clean to me. It'd be exposing a minor internal detail on places like the /status page.

**Comment by grobie** [comment]
Closing the connection has signaled such timeout so far and most services
at SoundCloud react to such event by aborting the processing of a request.

Though, with the discussion around keep-alive this sounds like a useful
hint. Intuitively a header also sounds like the better option to me to
transport such meta information.

**Comment by juliusv** [comment]
Agreed on header in this case.
