### ISSUE TITLE
Query for HAPROXY ONLY for "be_http"

### ISSUE THREAD

**Issue by prasenforu** [prometheus/prometheus#2516]
**What did you do?**
I am executing below query 
`haproxy_backend_connections_total{backend!="",job="haproxy"}`

**What did you expect to see?**

What I expecting that is also OK (below) as per query.
![image](https://cloud.githubusercontent.com/assets/19322497/24235046/6147471a-0fc1-11e7-99e3-19022589c5ba.png)

**What did you see instead? Under which circumstances?**
But I Want to capture backend connection which is starts with ONLY "**be_http**_*"

Not able to do such query.

PLEASE HELP.

**Comment by zouyee** [comment]
haproxy_backend_connections_total{backend=～"^be_http_.*",job="haproxy"}
About other use case, you could find from [operators](https://prometheus.io/docs/querying/operators/)

**Comment by prasenforu** [comment]
Perfect :)
Thanks Zouyee

**Comment by grobie** [comment]
Please ask questions on the prometheus-users@ mailing list the next time.
