### ISSUE TITLE
Return error on duplicate label matchers in PromQL query

### ISSUE THREAD

**Issue by stuartnelson3** [prometheus/prometheus#2517]
**What did you do?**

I executed the following query:

```
http_request_duration_milliseconds{quantile="0.99", quantile="0.5"}
```

(Actual metric name was different)

**What did you expect to see?**

An error saying that I can't specify the same label matcher key twice.

**What did you see instead? Under which circumstances?**

No error, empty returned data set.

**Environment**

* System information:

```
Linux 3.16.7-ckt11+soundcloud x86_64
```

* Prometheus version: 

```
prometheus, version 1.5.2 (branch: master, revision: bd1182d29f462c39544f94cc822830e1c64cf55b)
  build user:       root@a8af9200f95d
  build date:       20170210-14:41:22
  go version:       go1.7.5
```

* Prometheus configuration file:
Not relevant

I'm assuming the code is working correctly -- PromQL filters the metrics according to the two label matchers supplied. Because they're logically excluding the other, the returned set is empty. Seems like a pretty obvious incorrect use-case and returning "Hey, label matchers must be unique, but `key` was specified more than once" would be a nice-to-have.

**Comment by fabxc** [comment]
This seems generally like expected behavior. Label matchers are connected by AND, irrespective of label name. 
For equality obviously the result will be empty, but not sure whether it should be an error.

For example, would this seem wrong?

`requests_total{status!="404",status!="300"}`

**Comment by stuartnelson3** [comment]
That's a good point. While I would be surprised to see this instead of a regex, there's no reason it shouldn't be allowed.
