### ISSUE TITLE
Need to integarted Prometheus with influx db: 

### ISSUE THREAD

**Issue by Rishabhjain123456** [prometheus/prometheus#2521]
I am able to see all storage metrics by Prometheus --help but i don't know how to edit these parameters.
I want to edit below parameters and want to get data in my influx so i can store for longer period.
 -storage.remote.influxdb-url.influxdb-url
      The URL of the remote InfluxDB server to send samples to. None, if
      empty.

   -storage.remote.influxdb.database "prometheus"
      The name of the database to use for storing samples in InfluxDB.

   -storage.remote.influxdb.retention-policy "default"
      The InfluxDB retention policy to use.

   -storage.remote.influxdb.username
      The username to use when sending samples to InfluxDB. The
      corresponding password must be provided via the INFLUXDB_PW environment
      variable.

Also how to add my http://locallost:8086(influx db) to -storage.remote.influxdb-url.influxdb-url.

Thanks 
Rishabh

**Comment by brian-brazil** [comment]
Please ask support questions on https://groups.google.com/forum/#!aboutgroup/prometheus-users
