### ISSUE TITLE
Send Content-Type On Remote Write

### ISSUE THREAD

**Issue by danielshiplett** [prometheus/prometheus#2522]
The remote_write message sent has content-encoding headers but does not have content-type headers.  Please add.  Presumably it would be 'application/x-protobuf'.

Prometheus version:  v1.5.2

**Comment by juliusv** [comment]
Will do, thanks.

**Comment by tomwilkie** [comment]
@juliusv this can be closed now I think.

**Comment by juliusv** [comment]
Indeed, thanks.
