### ISSUE TITLE
what's the difference between deltaEncodedChunk and doubleDeltaEncodedChunk

### ISSUE THREAD

**Issue by timchenxiaoyu** [prometheus/prometheus#2524]
what's the difference between deltaEncodedChunk and doubleDeltaEncodedChunk?

**Comment by juliusv** [comment]
See https://prometheus.io/docs/operating/storage/#chunk-encoding

Please direct questions to our mailing lists instead of using GitHub issues: https://prometheus.io/community/

**Comment by timchenxiaoyu** [comment]
ths
