### ISSUE TITLE
How to dynamic service discovery [ target scrapes]  with marathon/mesos 

### ISSUE THREAD

**Issue by shamimgeek** [prometheus/prometheus#2533]
Hello all,

I am new to prometheus and trying to setup monitoring for mesos/marathon. could you please provide some example configuration for dynamic service discovery in mesos environment. 

Thanks in advance.

**Comment by brian-brazil** [comment]
Usage questions are best asked at https://groups.google.com/forum/#!aboutgroup/prometheus-users
