### ISSUE TITLE
Query data for max-min decimation plotting

### ISSUE THREAD

**Issue by moof2k** [prometheus/prometheus#2534]
Pulling timeseries in a max-min decimated form is useful for plotting waveforms or other data where the min and max values are important. This is a common use case in audio wave editors and plotting data captured from analog sources. Here's a nice explanation: [Link](http://digital.ni.com/public.nsf/allkb/F694FFEEA0ACF282862576020075F784)

From my brief testing it appears Prometheus only supports [down/sub]sampling.

For example, say I want to plot node_cpu first at 1s intervals and later at 30s intervals (zoomed out). If the data is recorded at 5s intervals, I would expect the 1s plot to show all the datapoints and the 30s plot to decimate the data to show me the min and max over each 30s sampling interval.

It's not clear to me how to accomplish this. Am I correct Prometheus doesn't support this use case? If so, please consider this a feature request. :)

![image](https://cloud.githubusercontent.com/assets/5669125/24381345/c55271da-1304-11e7-9c51-d8c5c3a1b633.png)

**Comment by brian-brazil** [comment]
Usage questions are best asked at https://groups.google.com/forum/#!forum/prometheus-users

Look at the *_over_time functions.
