### ISSUE TITLE
can not use count() to determine whether there is a machine actived 

### ISSUE THREAD

**Issue by ckeyer** [prometheus/prometheus#2535]
**What did you do?**
`time() - container_last_seen=""} <=10`  no data
 `count(time() - container_last_seen <=10)`  return  `no data`

**What did you expect to see?**

 `count(time() - container_last_seen <=10)`  return  `no data`

**What did you see instead? Under which circumstances?**
 
`count(time() - container_last_seen <=10)`  return  `0`

**Environment**

latest

* System information:

	insert output of `uname -srm` here

* Prometheus version: 

	insert output of `prometheus -version` here

* Alertmanager version:

	insert output of `alertmanager -version` here (if relevant to the issue)

* Prometheus configuration file:
```
insert configuration here
```

* Alertmanager configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```

**Comment by brian-brazil** [comment]
Usage questions are best asked at https://groups.google.com/forum/#!forum/prometheus-users
