### ISSUE TITLE
Relabel consul node to instance not working

### ISSUE THREAD

**Issue by perbly** [prometheus/prometheus#2539]
As you see in the picture, instance-label isn't the __meta_consul_node. But when i do a mouseover the nodename is correct. 
And it seems like reconfiguring/restarting prometheus gives the correct nodename for a while and then it just disappear and becomes the address:post again.

I tried to relabel __meta_consul_node to a new label called "hostname" and that worked perfect for a while also until it just disappeared.

**What did you do?**
Configured prometheus to scrape consul and relabel _consul_node to instance
**What did you expect to see?**
the nodename (hostname)
**What did you see instead? Under which circumstances?**
address+port
**Environment**
Consul 0.7.3
* System information:
Ubuntu 16.10

* Prometheus version: 
1.5.0

* Alertmanager version:

	insert output of `alertmanager -version` here (if relevant to the issue)

* Prometheus configuration file:
```
  - job_name: consul
    consul_sd_configs:
    - server:   'consul.gotham.city:8500'

    relabel_configs:
    - source_labels: ['__meta_consul_service']
      regex:         '(.*)'
      target_label:  'job'
      replacement:   '$1'
    - source_labels: ['__meta_consul_tags']
      regex:         ',(prod|uat),'
      target_label:  'group'
      replacement:   '$1'
    - source_labels: ['__meta_consul_node']
      regex:         '(.*)'
      target_label:  'instance'
      replacement:   '$1'
    - source_labels: ['__meta_consul_dc']
      regex:         '(.*)'
      target_label:  'datacenter'
      replacement:   '$1'
insert configuration here
```

* Alertmanager configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
nothing in logs regarding this
```

![image](https://cloud.githubusercontent.com/assets/5936850/24408484/1c08221c-13ce-11e7-8432-5a26ee311ad3.png)

**Comment by brian-brazil** [comment]
This isa known bug in 1.5.0, please upgrade to 1.5.2.
