### ISSUE TITLE
Time Series Annotations

### ISSUE THREAD

**Issue by matttproud** [prometheus/prometheus#255]
We had talked about providing the graph interface with the means to add annotations.  That would be nice.  Let's also provide programmatic means for this that can be bound to an (expression, time) double.

**Comment by juliusv** [comment]
We won't be adding annotation support to Prometheus itself for the time being. PromDash has annotation support. Closing this.

**Comment by nordicdyno** [comment]
Maybe it's time to reopen proposal, because: «NOTE: PromDash is deprecated. We recommend Grafana for visualization of Prometheus metrics nowadays, as it has native Prometheus support and is widely adopted and powerful.»?

**Comment by brian-brazil** [comment]
This is a feature that'll never be added to Prometheus itself, as it belongs at a different layer. I believe the latest version of Grafana has a similar feature.

**Comment by nordicdyno** [comment]
It has, but for other backends (Graphana, Influx): http://docs.grafana.org/reference/annotations/
Unfortunately Prometheus is not in list :(

**Comment by grobie** [comment]
It definitely has prometheus annotations support in Grafana 3.0. We're displaying the results of our `ALERTS` timeseries in multiple dashboards.

**Comment by grobie** [comment]
https://github.com/grafana/grafana/pull/2883 is available in >=3.0.0-beta1.

**Comment by nordicdyno** [comment]
Cool, thanks!
