### ISSUE TITLE
Rename prometheus_build_info metric to build_info

### ISSUE THREAD

**Issue by mattbostock** [prometheus/prometheus#2566]
The `prometheus_build_info` metric is a useful way to confirm the running version of Prometheus, as is `alertmanager_build_info` for Alertmanager.

Since both metrics have a `job` label that allows them to be distinguished, I propose that we rename them to `build_info`.

**Comment by brian-brazil** [comment]
Fixed title to match description.

I think the current way with the application name is probably the better way, as revisions are comparable between versions of a given binary but not across binaries.

**Comment by juliusv** [comment]
@brian-brazil Yeah, kind of an edge case. You could still count the total number of Go versions you have in production across binaries though. But maybe that is not important enough.

**Comment by brian-brazil** [comment]
That'd be an argument for a separate metrics for the go version I think.

**Comment by brian-brazil** [comment]
Thinking a little more, we probably the Go version to be a default metric that comes with client_golang.

**Comment by juliusv** [comment]
@brian-brazil That totally makes sense.

**Comment by juliusv** [comment]
Closing in favor of https://github.com/prometheus/client_golang/issues/328
