### ISSUE TITLE
Remote read ReadResponse should allow for multiple queries

### ISSUE THREAD

**Issue by brian-brazil** [prometheus/prometheus#2574]
The remote read proto currently allows for multiple queries to be made, in line with future expectations to bundle queries together.

However the response only allows for a single vector. We should add another level of list on top of what we have.

It'd be best to do this before 1.6.

**Comment by juliusv** [comment]
But multiple queries are fine to end up in the same range vector, no? The multiple queries is there so that we can request multiple label selector sets with different time ranges and all, but all we need as a result in the end is a list of all the time series with all their data points (which we have now).

**Comment by brian-brazil** [comment]
> But multiple queries are fine to end up in the same range vector, no? 

Consider the query `a + b`. We need the a's and the b's separately unless you want to separate them out on the Prometheus end. Downsampling optimisations/tweaks may also require offering different data for the same metric depending on context.

**Comment by juliusv** [comment]
So I guess you mean that in the end at https://sourcegraph.com/github.com/prometheus/prometheus@5f3327f620e3fd29bfc3770acd68d679d165d49c/-/blob/promql/engine.go#L584:1-591:1, it should only get the iterators for that (sub)query and not all the others. Ok yeah.

**Comment by brian-brazil** [comment]
For now we just need to adjust the proto, so this is possible in the future.

**Comment by juliusv** [comment]
:+1:
