### ISSUE TITLE
Add query hints to remote read

### ISSUE THREAD

**Issue by brian-brazil** [prometheus/prometheus#2580]
As discussed back at promcon, we should add a map[string]string with hints like the function wrapping the selector, the range and the step. This is unstructured and experimental as we don't know yet what if any of this will prove useful for things like downsampling optimisations on the other end.

At some point (likely after the rest of remote read is considered non-experimental), this should be changed to proper structured data when we have a good idea from multiple implementations what information is needed.

**Comment by fabxc** [comment]
I don't see an immediate benefit to making it unstructured initially. If you change something, the other end won't work anymore either way. Just that you won't notice it at compile time with `map[string]string`.

None is more or less work than the other really.

**Comment by fabxc** [comment]
This would be another argument to `Select` I assume, like `Select(*Params, ...labels.Matcher)`?

What I can see immediately would be:

```go
type Aggregation int

const (
    AggrNone Aggregation = iota
    AggrAvg
    AggrMin
    AggrMax
    AggrCounter
    AggrCount
)

type Param struct {
    Step int64
    Aggr Aggregation
}
```

The aggregation would make some assumptions already about what a given PromQL function needs. We could just make it a function name of course. But I'd believe that every implementation making use of these would just end up mapping our dozens of functions theirselves, which introduces lots of room for error.

**Comment by brian-brazil** [comment]
I don't think we should make any assumptions about how downsampling works and what information it finds useful for a first version. Thus why I propose passing it down and only finalising this API after there's more experience.

**Comment by fabxc** [comment]
Then just the raw info

```
type Params struct {
    Step int64
    Func string
}
```

Strictly speaking `sum/avg/...` are not functions. Should this go into an extra `Aggr string` field?

**Comment by brian-brazil** [comment]
There's no overlap between function names and operator names, so for a first pass I'd suggest putting them all in one field.

**Comment by henridf** [comment]
I'd like to work on this - I've started taking a look and I'll report back here if I run into anything, otherwise will hopefully have a PR soon.
