### ISSUE TITLE
Rename scrape timeout header for consistency

### ISSUE THREAD

**Issue by mdlayher** [prometheus/prometheus#2581]
> ...shouldn't we use X-Prometheus-Scrape-Timeout-Seconds instead? We prefix all our other headers with X-Prometheus-

Created from discussion in #2565.

**Comment by juliusv** [comment]
Yes, I think we should! But you knew that ;)

**Comment by mdlayher** [comment]
Yep, just making a GitHub issue to make sure it gets done.
