### ISSUE TITLE
Throttle resends of alerts

### ISSUE THREAD

**Issue by brian-brazil** [prometheus/prometheus#2585]
We currently send alerts at every eval interval. With a 1s eval interval, this would produce a lot of traffic to the AM.

I propose we continue to send new alerts instantly, but throttle the resends to say 60s by default.

**Comment by brancz** [comment]
Generally I think that's ok, we just need to make it explicit in the documentation and make sure that the resolve timeout in the Alertmanager needs to be higher than this value.

**Comment by brian-brazil** [comment]
The resolve timeout is just a default, we can adjust the end time as required inside Prometheus.

**Comment by brancz** [comment]
Yes I realize that I just meant we need to document properly what the relationship between the two is.

**Comment by reymont** [comment]
Any idea for the maximum alarm times? Reaching the "Throttle"(maximum alarm times), do not send alert message any more?

**Comment by brian-brazil** [comment]
Please don't clutter the issue tracker with unrelated questions, use https://groups.google.com/forum/#!aboutgroup/prometheus-users for support.

**Comment by stuartnelson3** [comment]
The current ingest path in AM for alerts has pretty high lock contention, throttling resends would be 👍
