### ISSUE TITLE
Option to disable alert sending for x seconds after startup.

### ISSUE THREAD

**Issue by liquidgecka** [prometheus/prometheus#2592]
When prometheus is configured with alerts in the form: `up{job="example"} > 5` a restart can cause prometheus to actually sent alerts because it doesn't have recent data from those metrics, even though the next collection will actually report them up and resolve the alert. What I would love is a configuration option to either allow alerting to be delayed until each source has been queried x times, or to delay alert sending for x seconds on startup. This would allow the state to become stable before sending me a dozen pages that get immediately cleared.

**Comment by Gouthamve** [comment]
Related: https://github.com/prometheus/prometheus/issues/422#issuecomment-290103449

**Comment by brian-brazil** [comment]
This is one of the things a FOR clause protects against which ~all alerts should have, other considerations are already in #422.
