### ISSUE TITLE
Series lastSampleValue{,Set} is not set upon checkpoint recovery

### ISSUE THREAD

**Issue by juliusv** [prometheus/prometheus#2602]
We do not set the series' lastSampleValue and lastSampleValueSet when recovering a series from the checkpoint upon startup: https://sourcegraph.com/github.com/prometheus/prometheus@acd72ae1a7bf62ef37f69830531666548ce40907/-/blob/storage/local/heads.go#L211:1-221:1

But we only do duplicate sample value detection correctly if this field is set: https://github.com/prometheus/prometheus/blob/master/storage/local/storage.go#L919-L920

Thus, when one restarts a Prometheus, a duplicate sample (that would normally be a noop) is now counted as a sample with equal timestamp, but different value.

/cc @beorn7

**Comment by beorn7** [comment]
Yes, that was deliberate back then, as we didn't want to change the checkpoint format just to enable this check. Explicitly retrieving the last sample from the last chunk of each series would be quite expensive and increase startup time. (At least that was the rationale back then.)

**Comment by juliusv** [comment]
Ah, good to know. I bet we're not aiming to fix this before the new storage then, so closing.
