### ISSUE TITLE
File-based service discovery doesn't accept relative paths to files

### ISSUE THREAD

**Issue by it-praktyk** [prometheus/prometheus#2603]
I tried configure the file-based service discovery with file pattern relatative to the main Prometheus configuration catalog (usually /etc/prometheus).

I've found that only full path is accepted - not relative path.

In my opinion issue is related to the line https://github.com/prometheus/prometheus/blob/master/discovery/file/file.go#L85 what currently is
`
	paths = append(paths, files...)
`

In opposite rule files can be provided with a relative path because the line https://github.com/prometheus/prometheus/blob/master/config/config.go#L63 contains the additional command
`
	resolveFilepaths(filepath.Dir(filename), cfg)
`

Confirmed with Prometheus 1.5.2.

**Comment by brian-brazil** [comment]
#2247 covers this.
