### ISSUE TITLE
PromQL logging and meta-metrics?

### ISSUE THREAD

**Issue by RichiH** [prometheus/prometheus#2604]
As a general discussion item:

Would it make sense to log PromQL queries and expose meta-metrics about how often every timeseries/metric has been accessed? "Last accessed" information might be even cheaper.

The intention behind this is to dig out timeseries/metrics which are never touched and thus can be dropped completely in the future. This could also help decide which timeseries/metrics to export to long-term storage.

**Comment by tomwilkie** [comment]
@RichiH there been some discussion about this on #1315, and I'm currently working on opentracing instrumentation to expose this kind of information.

I could quite quickly add the labels sets for the timeseries that are touched to this?

**Comment by brian-brazil** [comment]
Closing in favour of #1315
