### ISSUE TITLE
promtool check-metrics: bits vs bytes

### ISSUE THREAD

**Issue by mdlayher** [prometheus/prometheus#2617]
Creating a new issue from the discussion in: https://github.com/prometheus/prometheus/pull/2605.

Some of the current open questions:
- Should this tool provide both "errors" and "warnings"?
- Do warnings vs. errors make the tool less useful for CI purposes?
- Does it make for network metrics or metrics such as "available bits of entropy" to remain as bits instead of bytes?
- Can the conversion for humans just be handled by a tool like Grafana, or multiplying/dividing by 8 where needed?

Feel free to continue the discussion here.

**Comment by grobie** [comment]
From @brian-brazil:

> If the choice is between allowing a mix of bit and bytes, and having an exception for entropy I say we switch entropy to bytes.

**Comment by brian-brazil** [comment]
This was done.
