### ISSUE TITLE
Add other annotations for Kubernetes

### ISSUE THREAD

**Issue by cemo** [prometheus/prometheus#2622]
I am new to prometheus land and sorry If this issues is already discussed. The current way of accessing different scrap path is using annotations like `prometheus.io/path`. This is nice because I can access our endpoints from the exact configuration of prometheus. [some annotations] such as `path`, `scheme`, `scrap` are already existing for configuration. Please provide other annotations as well such as:
```
basic_auth:
  [ username: <string> ]
  [ password: <string> ]

[ bearer_token: <string> ]
```

What do you think?

[some annotations]: https://github.com/prometheus/prometheus/blob/master/documentation/examples/prometheus-kubernetes.yml#L80-L90

**Comment by brian-brazil** [comment]
This is not possible, see #1176
