### ISSUE TITLE
Cleanup flags prior to 2.0 release

### ISSUE THREAD

**Issue by brian-brazil** [prometheus/prometheus#2634]
There's various old/deprecated flags we should get rid of (e.g. old alertmanagers flag). This issue is to remind us to do it.

**Comment by fabxc** [comment]
```
   -version false
   -config.file "prometheus.yml"
   -alertmanager.notification-queue-capacity 10000
   -alertmanager.timeout 10s
   -log.format "\"logger:stderr\""
   -log.level "\"info\""
   -query.max-concurrency 20
   -query.staleness-delta 5m0s
   -query.timeout 2m0s
   -storage.local.engine "persisted"     <<< remove?
   -storage.local.path "data"                 <<< mv storage.tsdb.path
   -storage.tsdb.max-block-duration 0s
   -storage.tsdb.min-block-duration 2h0m0s
   -storage.tsdb.no-lockfile false
   -storage.tsdb.retention 360h0m0s
   -web.console.libraries "console_libraries"
   -web.console.templates "consoles"
   -web.enable-remote-shutdown false
   -web.external-url
   -web.listen-address ":9090"
   -web.max-connections 512
   -web.read-timeout 30s
   -web.route-prefix
   -web.telemetry-path "/metrics"         <<< drop this? 
   -web.user-assets
```

overwriting the /metrics path seems pointless. We don't allow randomly rewriting anything else, so what's the reason to do it here? The route prefix allows for all practical cases I assume.

**Comment by brian-brazil** [comment]
> overwriting the /metrics path seems pointless.

Many of our exporters permit it, for reasons that aren't really clear to me.

> -query.staleness-delta 5m0s

Pretty sure this isn't used in 2.0.

**Comment by fabxc** [comment]
So should we ditch /metrics flag for 2.0?

Staleness delta is still used in plenty of cases as our window for how far we look back for instant queries mostly. Even with staleness solved, this needs to be specified somehow. But is the name still apropriate.

**Comment by brian-brazil** [comment]
> So should we ditch /metrics flag for 2.0?

I'd be in favour, however we'd need to get consensus on removing it from all the other components too.

> Staleness delta is still used in plenty of cases as our window for how far we look back for instant queries mostly. 

We don't use the flag value in 2.0, we use the constant `StalenessDelta`.

**Comment by Gouthamve** [comment]
We do have a constant value of 5mins, but it can be updated via the flag
here
<https://github.com/prometheus/prometheus/blob/dev-2.0/cmd/prometheus/config.go#L159-L163>

Should we keep it configurable?

**Comment by fabxc** [comment]
> I'd be in favour, however we'd need to get consensus on removing it from all the other components too.

@SuperQ @grobie @discordianfish you are dealing a lot with exporters doing this. Opinions?

**Comment by SuperQ** [comment]
Yes, we should remove `/metrics` flag from our components.  I don't see a need to provide an override for this in our own code.  The only use case is for reverse proxies, but these can be adjusted by users.

**Comment by grobie** [comment]
I've never changed the metrics path of an exporter. To be honest it's
mostly cargo cult that I included the flag in all exporters I wrote. I
wonder if we should reach out to prometheus-users and check whether anyone
has a good argument to keep them.

**Comment by brian-brazil** [comment]
From the requests I've seen it seems to be users trying to be consistent with some of their applications that use a (single) non-standard path.

**Comment by fabxc** [comment]
This is done.
