### ISSUE TITLE
Increase/Delta/Rate functions 

### ISSUE THREAD

**Issue by cemo** [prometheus/prometheus#2637]
I am using prometheus 1.5.1 and having some issues regarding some functions and their documentation. First of all, It would be really nice to demonstrate some examples in the documentation. It is really hard to understand root cause of a problem. 

I am experimenting prometheus and came across a case where numbers does not make sense.

```
Scrape Interval: 30s
Range duration: 60s (Every range vector contains 2 points for per serie)
```

When I use increase function, I have results doubled. I mean actual difference is 5 but result is 10. I think that it has a computation like ` diff / interval_count * data_point_count`. I verified this behaviour for larger range duration as well. 

I quickly glimpsed functions implementation but could not understand some parts.

**Comment by brian-brazil** [comment]
Questions around usage are best asked at https://groups.google.com/forum/#!forum/prometheus-users

I'd also suggest https://www.youtube.com/watch?v=67Ulrq6DxwA

**Comment by cemo** [comment]
Thank you so much @brian-brazil. I had really tried hard to find a reference. I will watch it.

**Comment by alex88** [comment]
@cemo same issue here, have you found a solution?
