### ISSUE TITLE
Allow Modification of Metric Names During Federation

### ISSUE THREAD

**Issue by civik** [prometheus/prometheus#2647]
It would be useful to have the ability to 'prepend' / 'modify' / 'insert from label' the metric names upon federation.  

Take the use case of pulling metrics from tenant environments where user metrics are scraped and given tags widget_metric{job="userdata", namespace="bobsnamespace"} . To avoid polluting the 'root' metrics and enforce some sort of namespacing onto users in a multi-tenant environment, I would federate and insert values from tags into the metric name and end up with a metric: `userdata_bobsnamespace_widgit_metric`

```
- job_name: 'federate-user'
  scrape_interval: 15s

  honor_labels: true
  metrics_path: '/federate'
  
 --> transform_metric: 
        prepend:
        - '{{job}}_{{namespace}}'  <--

  params:
    'match[]':
      - '{job="userdata"}'
   
```

**Comment by brian-brazil** [comment]
This is already possible via metric relabelling, however adding a label instead would be recommended instead of changing the metric name as labels are how you namespace such things.

Usage questions are best asked on https://groups.google.com/forum/#!aboutgroup/prometheus-users
