### ISSUE TITLE
Gaps with `histogram_quantile` if no count change

### ISSUE THREAD

**Issue by Dominik-K** [prometheus/prometheus#2662]
**What did you do?**
Our service gets only sometimes some requests via gRPC. To check the request counts, I run this query:
`histogram_quantile(0.99, sum(rate(grpc_server_handling_seconds_bucket[5m])) by (le))`

**What did you expect to see?**
A solid line at 0 were there are gaps now.

**What did you see instead? Under which circumstances?**
Gaps between the request. There are no 0 values pointing with the mouse over it.
![screen shot 2017-04-27 at 19 03 08](https://cloud.githubusercontent.com/assets/5795847/25495065/313f947e-2b7c-11e7-86f2-1d5b2310c28f.png)

I checked that the service was scraped and the counter `grpc_server_handling_seconds_bucket` is in the metrics (manually "scraped"). The service was up the whole time.

I got the gaps at the same timeframes by doing a division by zero:
![screen shot 2017-04-27 at 19 18 32](https://cloud.githubusercontent.com/assets/5795847/25495682/58d900a4-2b7e-11e7-87a4-a8598c349b6f.png)
 

**Environment**

* System information:
Official latest `prom/prometheus` Docker image.

* Prometheus version: 
prometheus, version 1.6.1 (branch: master, revision: 4666df502c0e239ed4aa1d80abbbfb54f61b23c3)

**Comment by juliusv** [comment]
When all rate buckets are 0, `histogram_quantile()` returns `NaN` (can you check in the returned AJAX data that this is the case?). The graph will not show 0 values for `NaN`, but should just show a gap, as you mention. This makes sense to me, as there were not any requests at all in the considered time window, so no quantiles can be calculated.

**Comment by juliusv** [comment]
> How can I check the Ajax return data?

In Chrome: open Chrome inspector -> "Network" tab -> (refresh a graph) -> click on one of the `query_range` requests -> "Response"

**Comment by juliusv** [comment]
Cool, closing here then.

**Comment by Dominik-K** [comment]
They are `NaN`. Thanks for your answer.
