### ISSUE TITLE
Improvement: Ignore beginning comma in query selectors

### ISSUE THREAD

**Issue by JensRantil** [prometheus/prometheus#2676]
**Background:** When I (in the Prometheus web GUI) query metrics, I generally first query for a list of all metrics and then copy-paste some selectors to refine my query.

**Problem:** Copy-pasting many times mistakenly includes a beginning comma (`,`). `my_metric{instance="my-instance",}` is gracefully handled by Prometheus but `my_metric{,instance="my-instance"}` is not and yields `Error executing query: parse error at char 11: unexpected "," in label matching, expected identifier`.

**Proposed solution:** That `my_metric{,instance="my-instance"}` is interpreted as `my_metric{instance="my-instance"}` and Prometheus is a bit more forgiving :-)

**Comment by brian-brazil** [comment]
Trailing commas is something that many languages offer, but I've never seen leading commas. This is also the only request for this so I think it's safe to not include it.
