### ISSUE TITLE
How can I get the highest memory usage for a given period of time for container?

### ISSUE THREAD

**Issue by CarlosDGQ** [prometheus/prometheus#2679]
I used the
      max_over_time(container_memory_usage_bytes{container_name="kibana-logging"}[1h]) like this; 
but "[1h]" mean  an hour before the current time and I get the highest container_memory_usage_bytes for last one hour; 

I want to specifiy time period,such as 2017-05-03T12:42:00.781Z to 2017-05-03T23:42:00.781Z or other time period like this,I just want to get the data at the time period I have specified.

   Is there any method can sovle my problem?

Thanks a lot!

**Comment by juliusv** [comment]
Please ask usage questions on the mailing list, as I see you already did at https://groups.google.com/forum/#!topic/prometheus-users/8D32g1mTmv4.

Closing.
