### ISSUE TITLE
storage: prometheus_local_storage_open_head_chunks undercounts

### ISSUE THREAD

**Issue by beorn7** [prometheus/prometheus#2687]
prometheus_local_storage_open_head_chunks is decremented too often or not incremented when it should be. We have observed negative values, which would be a great way to create memory from nothing, but will unfortunately not work in practice.

**Comment by brian-brazil** [comment]
The RP demo is reporting -54 and that has basically no label churn.

**Comment by fabxc** [comment]
Will get into the patch release with #2704
