### ISSUE TITLE
Invalid Prometheus URL, really is valid

### ISSUE THREAD

**Issue by jswitzer** [prometheus/prometheus#2691]
ERRO[0000] invalid Prometheus URL: http://mon0.kira.np.:9090/  source=main.go:75

The problem appears to be that the version of govalidator currently within this repository doesn't include an upstream fix for fully qualified urls. 

This particular issue was fixed here:
https://github.com/asaskevich/govalidator/issues/193

Should I try to put together a PR with a govalidator version update?

**Comment by brian-brazil** [comment]
Yes please.
