### ISSUE TITLE
Update README for minumum go version requirement

### ISSUE THREAD

**Issue by siavashs** [prometheus/prometheus#2698]
Trying to build `promtool` with golang < 1.8 produces this error message:
```
/path/to/gopath/src/github.com/prometheus/prometheus/util/promlint/promlint.go:86: undefined: sort.SliceStable
```
 As I checked [`sort.SliceStable` was added in golang-1.8](https://golang.org/doc/go1.8#sort_slice)

**Comment by Colstuwjx** [comment]
+1,  I also met a build issue:

```
vendor/k8s.io/client-go/rest/request.go:21:2: cannot find package "context" in any of:
```

We should add go version requirement since `context` is part of go 1.7+

**Comment by juliusv** [comment]
Done in https://github.com/prometheus/prometheus/pull/2750
