### ISSUE TITLE
Prometheus container keep only 15 days datas

### ISSUE THREAD

**Issue by ouraios** [prometheus/prometheus#2723]
Hello,

I have a problem with prometheus using docker.

It seems like prometheus keep only the last 15days of datas, but i havnt specified option to force it to keep only the last 15 days of data, how that's possible ??

**Comment by fabxc** [comment]
That is the default. You can change it by adapting the `-storage.local.retention` flag.

**Comment by ouraios** [comment]
What are the differents values i can use ?

**Comment by fabxc** [comment]
You can provide the time in hours with the `h` suffix, e.g. `200h`,
`1000h`, ...

**Comment by ouraios** [comment]
and mon with 6m for example ?

**Comment by fabxc** [comment]
No, just hours.

**Comment by ouraios** [comment]
Oh okay thanks, i think it does not appear clearly in the doc, maybe specifiying it more could be a nice improvement 😃 
Thanks for your help ! 👍
