### ISSUE TITLE
Update vendored github.com/Sirupsen/logrus

### ISSUE THREAD

**Issue by fazalmajid** [prometheus/prometheus#2732]
prometheus won't build in Solaris because the vendored version of logrus is ancient and doesn't include the file terminal_solaris.go that provides IsTerminal():
https://github.com/sirupsen/logrus/commits/master/terminal_solaris.go

Removing the vendored logrus and building it from HEAD (currently master = 5e5dc898656f695e2a086b8e12559febbfc01562) lets Prometheus build successfully.

**Comment by brian-brazil** [comment]
Would you like to send a PR?

**Comment by grobie** [comment]
Have a look at the govendor update command:
https://github.com/kardianos/govendor

**Comment by fazalmajid** [comment]
Sure, I was just unclear about the project's policy on updating dependencies. I just submitted the PR #2733
