### ISSUE TITLE
Prometheus still monitoring itself even after i have removed it from the config.

### ISSUE THREAD

**Issue by adityatalks** [prometheus/prometheus#2737]
I wanted to stop prometheus from monitoring itself. I removed it from the config file and restarted the service. But it still shows metrics about itself rather than just from the service i want it to monitor.

![image](https://cloud.githubusercontent.com/assets/1214214/26200294/1473a22a-3beb-11e7-8116-84a8a140fab8.png)

![image](https://cloud.githubusercontent.com/assets/1214214/26200296/1805d494-3beb-11e7-9262-34df25cd987e.png)

![image](https://cloud.githubusercontent.com/assets/1214214/26200307/1b2e1e74-3beb-11e7-9865-86ab777118ea.png)

**Comment by brian-brazil** [comment]
I see nothing unusual here, the metric list in 1.x is across the entire retention period.

https://groups.google.com/forum/#!forum/prometheus-users is generally the best place for usage questions.
