### ISSUE TITLE
All the query shows "No datapoints found"

### ISSUE THREAD

**Issue by dearluo133** [prometheus/prometheus#2740]
<img width="653" alt="no data" src="https://cloud.githubusercontent.com/assets/28785192/26208394/8594a554-3c1c-11e7-8324-345dabe10f9f.PNG">
<img width="464" alt="targets" src="https://cloud.githubusercontent.com/assets/28785192/26208402/8c794dc0-3c1c-11e7-9ad2-892f30f31670.PNG">

I use snmp_exporter and i can see the data through the targets but when i use query the pertinent data it shows no datapoints found , even if when i queried "up"

**Comment by brian-brazil** [comment]
Usage questions are best asked at https://groups.google.com/forum/#!forum/prometheus-users
