### ISSUE TITLE
Store metrics docstrings and allow to query them

### ISSUE THREAD

**Issue by AlekSi** [prometheus/prometheus#2747]
Prometheus doesn't currently store metrics docstrings (`#HELP` lines in text format). They could be useful for a user in various UIs and dashboards.

I think they can be stored as simple non-versioned metainformation. If some metric has different docstrings in various jobs, then log a warning and overwrite it (the last write wins).

Obviously, they also should be exposed via API.

**Comment by aweiteka** [comment]
+1. Here's a specific use case:

As a query developer creating queries for dashboards and alerts, I would like to enable "help mode" in the prometheus web UI so I can understand exactly what data is being returned so I have confidence the data I am getting is what I want. This might be implemented as a mouseover tooltip in the query bar or as a function, e.g. `help(<metric_name>)`

**Comment by Gouthamve** [comment]
Related: https://github.com/prometheus/prometheus/issues/376

**Comment by brian-brazil** [comment]
#4183 added this.
