### ISSUE TITLE
Prom2: weird interplay of rate and recording rules on P2

### ISSUE THREAD

**Issue by mwitkow** [prometheus/prometheus#2754]
**What did you do?**
Ran a stack of P1 and P2 side by side. Pointed it at the same service that generates a steady 80 qps on a rate counter. There's also a `::rate1m` recording rule assigned to it. The data is scraped every `15s`. 

This screen shows the raw data calculated with a query, and the output of the recording rule

![simlea1_weird_timing](https://cloud.githubusercontent.com/assets/9655971/26307752/1023d5cc-3eee-11e7-9bde-1155772576b7.png)

**What did you expect to see?**

The same graph on P2.

**What did you see instead? Under which circumstances?**
![simleaf2_weird_timing](https://cloud.githubusercontent.com/assets/9655971/26307803/58082942-3eee-11e7-8c49-8c207f7d30c9.png)

Instead, the P2 behaviour seems weird, as the query data seems very similar to the one from P1, but the recording rule is different.

**Environment**

`dev-2.0` latest head.

@fabxc

**Comment by mwitkow** [comment]
@fabxc is this an artifact of the new TSDB or did any other changes to rule evaluation happen?

**Comment by mwitkow** [comment]
@fabxc do you think this may be related to #2776 ?

**Comment by fabxc** [comment]
Hard to guess. Possible for sure. Easiest way to find out is whether it disappears with the next alpha.

**Comment by brian-brazil** [comment]
This looks like aliasing, nothing to see here I think.

**Comment by Gouthamve** [comment]
Hmm, setting the resolution to 1sec should probably show if its aliasing or not.

**Comment by mwitkow** [comment]
@brian-brazil can you elaborate please? 

It's still there, sadly :(

**Comment by brian-brazil** [comment]
If every time you refresh the page (and thus have slightly different start/end times), then it's aliasing. This is a standard signal processing problem, and not something we can solve in Prometheus.
