### ISSUE TITLE
file_sd should have a metric for the timestamps of the files it's using

### ISSUE THREAD

**Issue by brian-brazil** [prometheus/prometheus#2757]
This should work the same way as for the textfile collector.

**Comment by Gouthamve** [comment]
Some pointers:

The text file collector does it by having [a map](https://github.com/prometheus/node_exporter/blob/master/collector/textfile.go#L76) and updating it on [every read](https://github.com/prometheus/node_exporter/blob/master/collector/textfile.go#L105).

We could have the same translated to file_sd here: https://github.com/prometheus/prometheus/blob/master/discovery/file/file.go#L195-L211

**Comment by KalivarapuReshma** [comment]
I am working on this and will be opening a pull request in 2-3 days.

**Comment by cstyan** [comment]
I think we can close this now, and close #3063
