### ISSUE TITLE
Is there a way to monitor individual port using node exporter in prometheus?

### ISSUE THREAD

**Issue by nikhilgoenka** [prometheus/prometheus#2762]
[NOTICE]: <> (If your question is around usage and not a bug in Prometheus please use: https://groups.google.com/forum/#!forum/prometheus-users)

**What did you do?**

**What did you expect to see?**
I have a couple of processes which I wish to monitor (like if the process is running/CPU-usage, etc)

**What did you see instead? Under which circumstances?**

**Environment**

* System information:

	insert output of `uname -srm` here

* Prometheus version: 

	insert output of `prometheus -version` here

* Alertmanager version:

	insert output of `alertmanager -version` here (if relevant to the issue)

* Prometheus configuration file:
```
insert configuration here
```

* Alertmanager configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```

**Comment by brian-brazil** [comment]
Usage questions should be asked on https://groups.google.com/forum/#!forum/prometheus-users

You want the blackbox exporter.
