### ISSUE TITLE
Alpha.2 Missing metrics on scrape when a sample limit is set (even when sample limit is not being actually hit)

### ISSUE THREAD

**Issue by checketts** [prometheus/prometheus#2769]
**What did you do?**
Running the `v2.0.0-alpha.2` and comparing the results against my existing `v1.6.2` deployment

**What did you expect to see?**
Using `v1.6.2` I can see the scrape samples coming in regularly with the query `scrape_samples_scraped{app="drydock"}`
![image](https://cloud.githubusercontent.com/assets/416063/26456463/5ece9854-412a-11e7-87fd-713b23e91d09.png)

**What did you see instead? Under which circumstances?**
With `alpha.2`, scraping the same targets I see metrics being missed
![image](https://cloud.githubusercontent.com/assets/416063/26456441/4cbb4c48-412a-11e7-9b91-316c4ffea6d2.png)

**Environment**
Running in Docker container in Kubernetes 1.4.1

**Comment by brian-brazil** [comment]
Do you know which metrics are missing? Is it always the same ones?

**Comment by brian-brazil** [comment]
Does the problem go away if you remove the limit? I see some issues with this code in 2.0, but nothing that'd cause this.

**Comment by brian-brazil** [comment]
Ah, we're passing along the wrong error message.

**Comment by checketts** [comment]
Removing the sample limit completely made the problem go away. Increasing the limit didn't work (though I had only tried tripling the value)

**Comment by fabxc** [comment]
Is this fixed with #2772 @brian-brazil

**Comment by brian-brazil** [comment]
No, I've got the code to fix just need to write the unittests.

**Comment by fabxc** [comment]
Fixed in #2787
