### ISSUE TITLE
Unknown reason prometheus's data genedated graphs having spikes dips

### ISSUE THREAD

**Issue by sutest** [prometheus/prometheus#2772]
![image](https://cloud.githubusercontent.com/assets/14442253/26482819/11930b7c-421c-11e7-9202-f7074493dcd1.png)

As seen from the screenshot , it's a graph showing nginx QPS which collected from prometheus_nginx_exporter (this exporter fetch data by tail log file function)

Normally this QPS graph should be consistent, somehow recently we have been seeing this issue that the QPS graph suddenly got so bad spikes or dips (value suddenly go down sharply and recovered) 

FYI, the graph are generated via grafana which fetching data from prometheus

The strange thing is , when the prometheus service reboot, this situation will recover at once, however after 1~2days , these spikes appears again.

We did some test to prove that the actual QPS never has this kind of sharply drop at anytime, so we consider this should be either a prometheus hidden bug or metrics issue.

We looking for some help

thanks in advance

**Comment by brian-brazil** [comment]
This is probably an oddness in your enviroment, looking into it is best done on https://groups.google.com/forum/#!forum/prometheus-users
