### ISSUE TITLE
If throttled, don't `rate`, etc. with 0 values

### ISSUE THREAD

**Issue by Dominik-K** [prometheus/prometheus#2793]
We've run into the "throttling mode" ° today. It seems that Prometheus (1.6.3) uses zero values for the throttled time and calculates wrong `rate`s resulting in **false alerts** afterwards.

A threshold-underrun alert was thrown 60 minutes later because we used a `rate(...[60m])` function:

![screen shot 2017-06-01 at 18 03 06](https://cloud.githubusercontent.com/assets/5795847/26689189/247d8324-46f5-11e7-8a57-180546b9a535.png)

* Throttling started at 16:27 and left "rushed mode" short before 16:42.
* Both graphs are based on the same `sum(rate(METRIC))` with different rate intervals.

**What did you expect to see?**

* A gap between 16:27 and 16:42 as Prometheus didn't scrape any values at this time.
* A near-to-flat, small changing `rate(...[60m])` graph (as seen before 16:27 and after 17:45). 
=> No false alerts like threshold was underrun.

I propose that Prometheus skips the throttled timeframe. I.e. uses the last value before throttling for `rates` calculated after it left "rushed mode", e.g. has real data values again.

° "Storage needs throttling. Scrapes and rule evaluations will be skipped." (urgencyScore=1)

**Comment by brian-brazil** [comment]
Nothing is ingested when throttling.

You're not showing us everything here. Is there a single time series which shows the supposed problem?

**Comment by Dominik-K** [comment]
The graphs shown above (and below) are based on the same `counter` timeseries. Only the rate interval is different. Here's also the raw counter value shown in the same graph (times are UTC+1 with summer time => +2h offset to UTC+0):

![screen shot 2017-06-06 at 17 00 37](https://cloud.githubusercontent.com/assets/5795847/26835975/da752032-4ad9-11e7-9d22-da6f42308da8.png)

The raw counter value in Prometheus (times are UTC+0):
![screen shot 2017-06-06 at 17 01 27](https://cloud.githubusercontent.com/assets/5795847/26835980/dcfd14cc-4ad9-11e7-974a-e3561e9d19be.png)


While throttling at the first 5 minutes, the counter value is set with the same value as the last scrape. Then there are NaN's until throttling is over. That's a second problem, though.

**Comment by brian-brazil** [comment]
Can you share the raw data for that counter?

**Comment by Dominik-K** [comment]
Sure. Here are the [raw values](https://gist.github.com/Dominik-K/d65b46246d59f8d28d0e00bb600dd846), retrieved with the [`query_range`](https://prometheus.io/docs/querying/api/#range-queries) API call.

**Comment by brian-brazil** [comment]
Can you get the values using the `query` api please.

**Comment by Dominik-K** [comment]
Where's the difference? I just checked the first and last value with the `query` call and they are the same. E.g. the last value in the timeframe:

    {
        "status": "success",
        "data": {
            "resultType": "vector",
            "result": [
                {
                    "metric": {
                        "__name__": "REDACTED",
                        "instance": "REDACTED",
                        "job": "REDACTED"
                    },
                    "value": [
                        1496332800,
                        "266768234"
                    ]
                }
            ]
        }
    }

**Comment by brian-brazil** [comment]
query_range does not return the raw data.

**Comment by brian-brazil** [comment]
I'm presuming this is a misunderstanding of how rate() works. If you've evidence that rate() is broken, please share the raw data.
