### ISSUE TITLE
UP status incorrectly given to anything in 2.0-alpha.2

### ISSUE THREAD

**Issue by johrstrom** [prometheus/prometheus#2796]
[NOTICE]: <> (If your question is around usage and not a bug in Prometheus please use: https://groups.google.com/forum/#!forum/prometheus-users)

**What did you do?**
Misconfigured Prometheus 2.0-aplha.2 such that it attempts to scrape a host does not exist. It was then marked as UP even though it should not have been. 

**What did you expect to see?**
Items marked appropriately in the /status page (UP iff they're up and DOWN iff they're down)

**What did you see instead? Under which circumstances?**
Everything is marked as UP regardless of whether that's actually true or not.  You can replicate easily by using a host name that isn't reachable. You can use the config below.

* Prometheus version: 

prometheus, version 2.0.0-alpha.2 (branch: HEAD, revision: ab0ce4a8d9858956b37b545cfb84bb4edb5d7776)
  build user:       jeff@localhost.localdomain
  build date:       20170525-21:21:28
  go version:       go1.8

* Prometheus configuration file:
```
scrape_configs:
- job_name: "up-test"
  static_configs:
  - targets: ['does.not.exist']

```

**Comment by brian-brazil** [comment]
This was fixed.

**Comment by jinlongplus** [comment]
How to build dev 2.0 . I just build a 1.7 version.
