### ISSUE TITLE
Drop global default timings

### ISSUE THREAD

**Issue by fabxc** [prometheus/prometheus#2810]
sWe have global defaults for rule evaluation and scraping. With rule groups coming up, those will also be configurable directly per group.

As it stands, any sufficiently advanced setup wraps the configuration in some sort of templating, be that through Chef and friends or more dynamic things like prometheus-operator. From that perspective, our global defaulting just adds complexity to our code and the final config and rule files are just more complex to read.

We should consider dropping those in Prometheus 2.0 to be explicit that our configs are just the format people should compile down to.

One concern is how this plays into Alertmanager, where we should apply the same rules. It has even more of those global defaults for all the different integrations and is getting really out of hand there. OTOH, it is also a lot more painful there to remove it. ([those](https://github.com/prometheus/alertmanager/blob/master/config/config.go#L300-L312))

**Comment by brian-brazil** [comment]
I'm against this. For the vast majority of users they should only be setting the global options.

By making the per group/scrape_config option the only option we'll see more users shooting themselves in the foot by having more than one interval in a Prometheus.

**Comment by fabxc** [comment]
Mh, I'm somewhat okay leaving it I guess. I think it's getting out of hand and increasingly awkward in Alertmanager though.

**Comment by brian-brazil** [comment]
Yeah, I'm getting a bit concerned about the AM in this regard.
