### ISSUE TITLE
Port remote APIs to 2.0

### ISSUE THREAD

**Issue by fabxc** [prometheus/prometheus#2811]
Tracking issue for adding the remote APIs back to dev-2.0. They were removed as the storage interface changed.

**Comment by fabxc** [comment]
@juliusv you looked into this already. Any progress/blockers so far?

**Comment by juliusv** [comment]
@fabxc Well, the new storage append interface (using refs) combined with the new staleness handling wrapped around it has made it more complicated and left me confused, so I didn't write any code yet. I might make an attempt this week, but I'll be gone for two weeks (June 11 - 25) afterwards, so it'd be up for grabs during that time if I didn't get to anything yet.

**Comment by fabxc** [comment]
Are we fine with shipping an initial 2.0 with remote APIs disabled? Seems fine to me TBH, given that they are experimental. Breaking stuff we should get done before is just piling up... so I want to cut down what we can.

**Comment by grobie** [comment]
I don't think this is a good idea and would not be in favor of that. Having
to look at some feature matrix to understand which release supports which
feature is very user unfriendly and confusing.

**Comment by brian-brazil** [comment]
I think we need the remote APIs for a 2.0.

**Comment by fabxc** [comment]
So who is committing to adding these? We are currently committed to:

- /api/v2
- CLI changes
- rule group changes and migration tooling
- Backup support
- Deletion support

We only have so much capacity and someone has to handle
- Storage migration (docs and/or tooling)
- Remote APIs

**Comment by juliusv** [comment]
> Remote APIs

Let me have another look at that and I will give you more of detail about commitment or not by tomorrow.

**Comment by tomwilkie** [comment]
I'll commit to handling this is @juliusv doesn't have time.  Remote APIs have been super popular, I think it would be a mistake to not include them in v2.

**Comment by juliusv** [comment]
@tomwilkie That'd be brilliant. I don't think I'm able to commit to full PRs on those before sometime in July, as I'm unavailable during the next two weeks and have plenty of unrelated stuff to take care of. So if you want to go ahead, please do so!
