### ISSUE TITLE
Add context to 2.0 storage interfaces

### ISSUE THREAD

**Issue by AlekSi** [prometheus/prometheus#2823]
Having `context.Context` in `Storage`, `Querier`, `Appender` and probably few other types would be helpful for remote storages. Even if Prometheus will use `context.TODO()` in the first 2.0 release, having at least somewhat stable interface is a good thing.

I can implement it if you agree.

**Comment by Gouthamve** [comment]
@AlekSi Thanks for the interest. Yes, the plan is to add `context.Context` to those types. The bigger issue is how you will plumb into the storage and its presented here: https://github.com/prometheus/tsdb/issues/84

I think it makes sense to tackle the issue in tsdb first before we implement it in Prometheus as the wrapper is pretty thin.

**Comment by AlekSi** [comment]
Yepp, I saw that tsdb issue. This issue is about adding context to generic storage interfaces which, eventually, will be used for cancellation signals. How they will be handled depends on specific implementations, including tsdb. In the simplest case, they can just ignore them.
I'm prototyping remote storage implementation now, that's why I'm interested in adding contexts now rather then when/if tsdb support them.

**Comment by fabxc** [comment]
Yes, as you said it makes sense to add them to the shim layer now. We can
than use it in tsdb later after figuring out our desired semantics.
If you want to file a PR adding those, that would be great.

**Comment by tomwilkie** [comment]
+1 I just came across the need for this working on the remote APIs for 2.0.

**Comment by AlekSi** [comment]
> I can implement it if you agree.

We postponed that work. Feel free to work on it if you need it _right now_. I expect to return to it later.

**Comment by AlekSi** [comment]
Actively working on it again.

**Comment by krasi-georgiev** [comment]
@AlekSi can we close this one since there is an open issue for the same in the tsdb repo
https://github.com/prometheus/tsdb/issues/84

**Comment by AlekSi** [comment]
Please see discussion above why those are separate issues.

**Comment by krasi-georgiev** [comment]
yep , sorry. I missed some important bits on the first read.
