### ISSUE TITLE
Redirect fix breaks redirect

### ISSUE THREAD

**Issue by m-stolle** [prometheus/prometheus#2825]
**What did you do?**

Update 1.6.3 to 1.7.0

**What did you expect to see?**

https://server/prometheus opens prometheus

**What did you see instead?**

https://server/prometheus redirects to https://server/prometheus/prometheus/graph

**Environment**

* System information:

> Linux 3.10.0-514.16.1.el7.x86_64 x86_64

* Prometheus version: 

```
prometheus, version 1.7.0 (branch: master, revision: bfa37c8ee39d11078662dce16c162a61dccf616c)
  build user:       root@7a6329cc02bb
  build date:       20170607-09:43:48
  go version:       go1.8.3
```

* Prometheus call:
```
-config.file=/etc/prometheus/prometheus.yml -web.listen-address=127.0.0.1:9090 -web.external-url=https://server/prometheus -alertmanager.url=http://127.0.0.1:9093/alertmanager -storage.local.path=/var/lib/prometheus/
```

* httpd.conf:
```
ProxyPass         /prometheus  http://localhost:9090/prometheus nocanon
ProxyPassReverse  /prometheus  http://localhost:9090/prometheus
```

I think #2755 is responsible for the new behaviour. I already set the option `web.route-prefix=/` but it does not help.

**Comment by grobie** [comment]
@brancz second report about this.

**Comment by brancz** [comment]
I didn't see the first one. Thanks for tagging, I'll prepare a fix asap.

**Comment by andrewhowdencom** [comment]
The other one is heree https://github.com/prometheus/prometheus/issues/2817
