### ISSUE TITLE
Bug: Unable to modify resolution in graph view

### ISSUE THREAD

**Issue by andrewhowdencom** [prometheus/prometheus#2827]
[NOTICE]: <> (If your question is around usage and not a bug in Prometheus please use: https://groups.google.com/forum/#!forum/prometheus-users)

**What did you do?**

Was showing a colleague how to use Prometheus. We have small blips in the data which are normal, but which you can't see unless you bump the resolution to something like 60s. However in doing this Chrome crashes outright, and firefox complains about a script dying.

**What did you expect to see?**

Finer data in the graph

**What did you see instead? Under which circumstances?**

He's dead, jim

**Environment**

https://hub.docker.com/r/prom/prometheus/

1.7 tag

* System information:

```
Linux 4.4.35+ x86_64
```

* Prometheus version: 
```
prometheus -version
prometheus, version 1.7.0 (branch: master, revision: bfa37c8ee39d11078662dce16c162a61dccf616c)
  build user:       root@7a6329cc02bb
  build date:       20170607-09:43:48
  go version:       go1.8.3
```

Some information not included as I don't think it's relevant. Can post anything else you neeed here also.

**Comment by AlekSi** [comment]
I believe this is due to #2766. 😞

**Comment by AlekSi** [comment]
That's due to `self.params.step` being a string at this point. This hack works:
```js
self.params.step = parseInt(self.params.step);
```

Feel free to work on a better solution if there is no PR from me in a couple of days.

**Comment by brian-brazil** [comment]
A PR would be greatly appreciated.

**Comment by AlekSi** [comment]
Would like to see it in 1.7.2.

**Comment by AlekSi** [comment]
@brian-brazil Should I send a PR for `release-1.7`? I use that feature in my current work all the time. We upgraded to 1.7 and now it is broken.

**Comment by andrewhowdencom** [comment]
If you do @AlekSi can you cc me <3 I also use this regularly. Cool to see that it'd been fixed on main though!

**Comment by matthiasr** [comment]
Please do!
