### ISSUE TITLE
Prometheus consoles should support Telegraf properties

### ISSUE THREAD

**Issue by e271828-** [prometheus/prometheus#2838]
The combination works well, except for the fact that none of the Prometheus consoles or Grafana dashboards support Telegraf's default naming scheme.

I've added support in this repo:

https://github.com/e271828-/prometheus-telegraf-consoles

**Comment by brian-brazil** [comment]
We'd generally recommend using the node exporter for such properties, and Grafana for dashboards.

The example console templates are there so there's something to look at in simple cases.

**Comment by e271828-** [comment]
The node exporter has weak log parsing support, which we need for long-running batch jobs. 

Telegraf is in general 5x more popular, more featureful, etc. It would make sense to have better support.

**Comment by brian-brazil** [comment]
For logs you want mtail or the grok_exporter. See also https://www.robustperception.io/one-agent-to-rule-them-all/

**Comment by brian-brazil** [comment]
I don't think it's likely we'll ever add more to the included console examples, Grafana is the way to go.
