### ISSUE TITLE
Graph legends have irrational behavior when monitoring thousands of hosts

### ISSUE THREAD

**Issue by e271828-** [prometheus/prometheus#2839]
Prometheus graphs are largely unusable when looking at properties across many thousands of hosts. 

The graph itself has reasonable behavior, but the legend extends infinitely instead of enforcing a maximum visible length and hiding the rest behind a folded div.

**Comment by brian-brazil** [comment]
The expression browser is only intended for ad-hoc debugging and exploration, for general dashboarding use we recommend Grafana.

Also, it's generally unwise to have thousands of plots on a single graph. It's extremely difficult for a human to pick anything useful out of that much noise.

**Comment by e271828-** [comment]
Ad-hoc debugging and exploration is less than convenient when you can't stack two graphs on top of each other due to the size of the legends :) 

From practical experience I must say I disagree strongly with your second point.

![screen shot 2017-06-12 at 2 17 38 pm](https://user-images.githubusercontent.com/7109823/27055677-01872bda-4f7a-11e7-97b2-7fd350c830f5.png)

**Comment by brian-brazil** [comment]
I'm afraid I don't think it's practical to fix this on our end.
