### ISSUE TITLE
[Question] Application metrics monitoring of Kubernetes Pods

### ISSUE THREAD

**Issue by boeboe** [prometheus/prometheus#2841]
Hi all,

We are already using node-exporters to pull/collect docker/container metrics within our kubernetes environment. Next we would also like to be able to collect application metrics (provided by spring-actuator in our case, eg. http://pod-name:8080/prometheus). How is this typically done, keeping in mind we cannot use Kubernetes services as fixed DNS names (they are load balanced over the pods behind the service) and the fact that pods disappear and appear all the time, changing their name and hence addressability?

Our initial naive approach was the following (but this will not be sufficient since it is load-balanced by the service):

    - job_name: 'example-service'
      scheme: http
      metrics_path: '/prometheus'
      static_configs:
       - targets: ['example-service:8080']

Any advice or examples would be really great.

Thanks a lot in advance,
Bart

**Comment by brian-brazil** [comment]
Usage questions are best asked at https://groups.google.com/forum/#!forum/prometheus-users

Look at kubernetes service discovery.

**Comment by boeboe** [comment]
Thanks @brian-brazil , I'll have a look.

**Comment by bibinwilson** [comment]
Hi @boeboe ,
I am stuck at the similar situation. I tried the config above but it didnt work. Were you able yo scrape the metrics from using the above config.
