### ISSUE TITLE
Move remote.proto into its own directory

### ISSUE THREAD

**Issue by brian-brazil** [prometheus/prometheus#2845]
Currently remote.proto is sitting in with the remote read/write code, which means any adapters using it end up pulling in some Prometheus code which they really shouldn't.

This was done initially to get things going, but we should find a better place to put our public protos long term.

**Comment by tomwilkie** [comment]
+1, also see https://github.com/prometheus/prometheus/pull/2821#issuecomment-308791455

**Comment by fabxc** [comment]
@brian-brazil In #2821 you proposed a single directory listing our protos. The general trend in Go seems to be to have `pkg/remote/remotepb` for example to address the problem or unnecessary imports. That's how AM does it.
I can see how a single dir makes it easier to find. But it kind of messes with hierarchical package structure.

I'm open to either but would like to hear more arguments/opinions.

Can we agree to avoid sharing partial proto types across repositories, i.e. not have AMs silence matcher import its `LabelMatcher` proto from prometheus/prometheus or share mundane stuff like the `LabelPair` tuple?

**Comment by brian-brazil** [comment]
I'm not too pushed either way on sharing.

**Comment by brian-brazil** [comment]
The dev-2.0 branch has a prompb directory for these.

**Comment by tomwilkie** [comment]
Closed by #2850
