### ISSUE TITLE
Remote storage resharding from 1 to -1 shards

### ISSUE THREAD

**Issue by tomwilkie** [prometheus/prometheus#2847]
@brian-brazil reported seeing `INFO[0390] Remote storage resharding from 1 to -1 shards. source="queue_manager.go:351"` in his logs.

@brian-brazil do you have any extra context?

**Comment by brian-brazil** [comment]
The remote write generally doesn't seem to like the other end having issues, such as being down for 5+ minutes. In this scenario, it also blocks shutdown.

**Comment by tomwilkie** [comment]
Going to close as a dupe of #2969, as there is a stack trace there.
