### ISSUE TITLE
Expose direct TSDB querying in v2 API

### ISSUE THREAD

**Issue by fabxc** [prometheus/prometheus#2849]
I would like the v2 API to expose a minimal layer to query the TSDB directly on top of the admin actions we expose. Any objections or concerns around this?

@brian-brazil @Gouthamve

**Comment by brian-brazil** [comment]
Wouldn't that basically be the remote read endpoint?

**Comment by fabxc** [comment]
To a degree, sure. But I want to have it focused and extensible on TSDBs primitives, which are lower level than the remote-read path. I want to provide access to the on-disk/in-mem chunks as they are for example.
There's interesting tooling to be built on top of that. 

I'm also a bit confused why remote read is not exposed under a versioned endpoint. Proto being extensible is one thing, but it doesn't help with fundamental method changes or moving to gRPC at some point. By now we all know those remote APIs aren't going away anymore.

**Comment by brian-brazil** [comment]
I'm not sure we should be offering that level of detail via the API that can be used by the average user, it sounds like something that belongs more in promtool.

**Comment by Gouthamve** [comment]
Yep, but promtool would be needing the APIs. Also, given this is an admin API, I think it is fine.

**Comment by fabxc** [comment]
As it's get only, I wouldn't necessarily put it under admin/ – but would if not otherwise acceptable.
I wasn't looking at promtool use cases per se. The reason why this couldn't go into external tooling is because that doesn't give us access to in-memory blocks.

**Comment by brian-brazil** [comment]
The v2 api isn't being developed, and remote read has been extended to have more chunk-level access so I think it's safe to say this is obsolete.
