### ISSUE TITLE
Error on ingesting samples with different value and the prometheus log does not show

### ISSUE THREAD

**Issue by xixikaikai** [prometheus/prometheus#2858]
Just like the issue on this page :
https://github.com/prometheus/prometheus/issues/2493

But I did not see the log that indicate the error metric?
I've noticed the log in prometheus should be like this?
![image](https://user-images.githubusercontent.com/10403433/27276974-624534a4-550f-11e7-8d59-71ee14deebdd.png)

**Comment by xixikaikai** [comment]
This is the part of prometheus logs 
`time="2017-06-16T08:47:51Z" level=info msg="Indexing metrics in memory." source="crashrecovery.go:502" 
time="2017-06-16T08:47:51Z" level=info msg="10000 metrics queued for indexing." source="crashrecovery.go:507" 
time="2017-06-16T08:47:51Z" level=info msg="20000 metrics queued for indexing." source="crashrecovery.go:507" 
time="2017-06-16T08:47:51Z" level=info msg="30000 metrics queued for indexing." source="crashrecovery.go:507" 
time="2017-06-16T08:47:51Z" level=info msg="Indexing archived metrics." source="crashrecovery.go:510" 
time="2017-06-16T08:47:51Z" level=info msg="40000 metrics queued for indexing." source="crashrecovery.go:523" 
time="2017-06-16T08:47:51Z" level=info msg="50000 metrics queued for indexing." source="crashrecovery.go:523" 
time="2017-06-16T08:47:51Z" level=info msg="60000 metrics queued for indexing." source="crashrecovery.go:523" 
time="2017-06-16T08:47:51Z" level=info msg="70000 metrics queued for indexing." source="crashrecovery.go:523" 
time="2017-06-16T08:47:52Z" level=info msg="80000 metrics queued for indexing." source="crashrecovery.go:523" 
time="2017-06-16T08:47:52Z" level=info msg="90000 metrics queued for indexing." source="crashrecovery.go:523" 
time="2017-06-16T08:47:52Z" level=info msg="100000 metrics queued for indexing." source="crashrecovery.go:523" 
time="2017-06-16T08:47:52Z" level=info msg="110000 metrics queued for indexing." source="crashrecovery.go:523" 
time="2017-06-16T08:47:52Z" level=info msg="120000 metrics queued for indexing." source="crashrecovery.go:523" 
time="2017-06-16T08:47:52Z" level=info msg="All requests for rebuilding the label indexes queued. (Actual processing may lag behind.)" source="crashrecovery.go:529" 
time="2017-06-16T08:47:52Z" level=info msg="Checkpointing fingerprint mappings..." source="persistence.go:1480" 
time="2017-06-16T08:47:52Z" level=info msg="Done checkpointing fingerprint mappings in 1.537957ms." source="persistence.go:1503" 
time="2017-06-16T08:47:52Z" level=warning msg="Crash recovery complete." source="crashrecovery.go:152" 
time="2017-06-16T08:47:52Z" level=info msg="30673 series loaded." source="storage.go:378" 
time="2017-06-16T08:47:52Z" level=info msg="Starting target manager..." source="targetmanager.go:61" 
time="2017-06-16T08:47:52Z" level=info msg="Listening on :9090" source="web.go:259" 
time="2017-06-16T08:47:53Z" level=warning msg="Error on ingesting samples with different value but same timestamp" numDropped=8 source="scrape.go:520" 
time="2017-06-16T08:47:53Z" level=warning msg="Error on ingesting samples with different value but same timestamp" numDropped=7 source="scrape.go:520" 
time="2017-06-16T08:47:55Z" level=warning msg="Error on ingesting samples with different value but same timestamp" numDropped=6 source="scrape.go:520" 
time="2017-06-16T08:48:05Z" level=warning msg="Error on ingesting samples with different value but same timestamp" numDropped=7 source="scrape.go:520" 
time="2017-06-16T08:48:06Z" level=warning msg="Error on ingesting samples with different value but same timestamp" numDropped=8 source="scrape.go:520" 
time="2017-06-16T08:48:07Z" level=warning msg="Error on ingesting samples with different value but same timestamp" numDropped=8 source="scrape.go:520" 
time="2017-06-16T08:48:08Z" level=warning msg="Error on ingesting samples with different value but same timestamp" numDropped=8 source="scrape.go:520" 
time="2017-06-16T08:48:08Z" level=warning msg="Error on ingesting samples with different value but same timestamp" numDropped=7 source="scrape.go:520" 
time="2017-06-16T08:48:10Z" level=warning msg="Error on ingesting samples with different value but same timestamp" numDropped=6 source="scrape.go:520" 
time="2017-06-16T08:48:20Z" level=warning msg="Error on ingesting samples with different value but same timestamp" numDropped=7 source="scrape.go:520" 
time="2017-06-16T08:48:21Z" level=warning msg="Error on ingesting samples with different value but same timestamp" numDropped=8 source="scrape.go:520" 
time="2017-06-16T08:48:22Z" level=warning msg="Error on ingesting samples with different value but same timestamp" numDropped=8 source="scrape.go:520" 
time="2017-06-16T08:48:23Z" level=warning msg="Error on ingesting samples with different value but same timestamp" numDropped=8 source="scrape.go:520" 
time="2017-06-16T08:48:23Z" level=warning msg="Error on ingesting samples with different value but same timestamp" numDropped=7 source="scrape.go:520" 
time="2017-06-16T08:48:25Z" level=warning msg="Error on ingesting samples with different value but same timestamp" numDropped=6 `

**Comment by beorn7** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
