### ISSUE TITLE
Is the alert a continuous event in the graph or just some alert point to trigger a alert email?

### ISSUE THREAD

**Issue by xixikaikai** [prometheus/prometheus#2860]
* Prometheus version: 

	1.5.2

* Alertmanager version:

	latest

my prometheus config is as below:
global:
  scrape_interval: 40s # By default, scrape targets every 15 seconds.
  scrape_timeout: 30s

and my graph is like this:
![image](https://user-images.githubusercontent.com/10403433/27279884-9a8752b2-5518-11e7-9428-56927f174034.png)

I have a FOR 3-minute alert rule in my alert.rules file,
and in this picture, we have zero value, but it is not continuously all zero, it is partial.

**Comment by brian-brazil** [comment]
It's best to ask usage questions on https://groups.google.com/forum/#!aboutgroup/prometheus-users

**Comment by xixikaikai** [comment]
I've also some other rules in my alert.rules file that have the same situation.
And I checked the code in prometheus
![image](https://user-images.githubusercontent.com/10403433/27280017-0a5570e2-5519-11e7-9eb4-ba73ae0c9907.png)

In alerting.go
I do not know if the delete process is triggered under what intervals?
