### ISSUE TITLE
Support Persistent Rule Generation through Web Interface

### ISSUE THREAD

**Issue by matttproud** [prometheus/prometheus#287]
After a user prototypes in the expression browser, he or she may want to persist the rule to a configuration.  A user may optionally want to rescind or modify an existing rule as well.

Reporter's Note: This could be easily achieved in a oneoff configuration file that only Prometheus is allowed to mutate.

/CC: @peterbourgon

**Comment by juliusv** [comment]
Closing, as we decided that we won't be doing this.

**Comment by peterbourgon** [comment]
Aww.

**Comment by juliusv** [comment]
@peterbourgon Sorry ;)
