### ISSUE TITLE
Add AssumeRole to EC2 discovery

### ISSUE THREAD

**Issue by jubagarie** [prometheus/prometheus#2877]
It would be nice to add the "AssumeRole" feature to the EC2 discovery. It would allow a Prometheus node to target instances in several AWS accounts easily.

It may not be always relevant to have one Prometheus instance per account as some of them are containing very few nodes or are preproduction environments.

I expected the "profile" key in the EC2 discovery configuration to allow this, but it doesn't seem to be working as expected. Using any valid or invalid value (e.g. existing profile or not in ~/.aws/config) behaves the same way : only the EC2 instances running in the same AWS account as the Prometheus instance are targeted.

**Environment**

* System information:
Linux 3.16.0-4-amd64 x86_64

* Prometheus version: 
prometheus, version 1.7.1 (branch: master, revision: 3afb3fffa3a29c3de865e1172fb740442e9d0133)
  build user:       root@0aa1b7fc430d
  build date:       20170612-11:44:05
  go version:       go1.8.3

**Comment by jamiemoore** [comment]
I have created a pull request for this #2895

**Comment by diurnalist** [comment]
This can be closed now, I think?
