### ISSUE TITLE
Prometheus start up error:

### ISSUE THREAD

**Issue by srivimal** [prometheus/prometheus#2879]
Could someone help me with the below error:
------------------------------------------

vimal@vimal-vm:~/Prometheus/server$ ./prometheus -config.file=./vimal.yml
prometheus, version 0.15.1 (branch: master, revision: 64349aa)
  build user:       julius@julius-thinkpad
  build date:       20150727-17:56:51
  go version:       1.4.2
INFO[0000] Loading configuration file ./vimal.yml        file=main.go line=173
ERRO[0000] Couldn't load configuration (-config.file=./vimal.yml): unknown fields in scrape_config: static_configs  file=main.go line=177
ERRO[0000] Note: The configuration format has changed with version 0.14. Please see the documentation (http://prometheus.io/docs/operating/configuration/) and the provided configuration migration tool (https://github.com/prometheus/migrate).  file=main.go line=178
vimal@vimal-vm:~/Prometheus/server$ 
vimal@vimal-vm:~/Prometheus/server$ 
vimal@vimal-vm:~/Prometheus/server$ 
vimal@vimal-vm:~/Prometheus/server$ prometheus -version
prometheus, version 0.15.1 (branch: master, revision: 64349aa)
  build user:       julius@julius-thinkpad
  build date:       20150727-17:56:51
  go version:       1.4.2
vimal@vimal-vm:~/Prometheus/server$ cat vimal.yml 
global:
  scrape_interval:     5s
  evaluation_interval: 5s
scrape_configs:
- job_name: linux
  static_configs:
  - targets: 
    - '127.0.0.1:9090'
    labels:
      alias: db1

**Comment by grobie** [comment]
Please ask questions on the mailing list.
