### ISSUE TITLE
How to check if an alert is inactive? 

### ISSUE THREAD

**Issue by zxwing** [prometheus/prometheus#2880]
The document says:

        For pending and firing alerts, Prometheus also stores synthetic time series of the form 
        ALERTS{alertname="<alert name>", alertstate="pending|firing", <additional alert labels>}. The 
        sample value is set to 1 as long as the alert is in the indicated active (pending or firing) state, and a 
        single 0 value gets written out when an alert transitions from active to inactive state. Once inactive, 
        the time series does not get further updates.

but I am confused by what I observed. After an alert turns to inactive (the Alerts page becomes green and shows 0 active), querying ALERTS metric still returns data with state pending/firing, value 0/1 for a while, and finally returns no data which means the alert becomes inactive.

What is the reliable programming way to judge if an alert is inactive?

**Comment by brian-brazil** [comment]
Usage questions are best asked at https://groups.google.com/forum/#!forum/prometheus-users
