### ISSUE TITLE
Pass context to SeriesIterator.ValueAtOrBeforeTime/RangeValues

### ISSUE THREAD

**Issue by aaron7** [prometheus/prometheus#2886]
It would be useful to have the context accessible from the `ValueAtOrBeforeTime/RangeValues` methods for alternate storage backends.

With cortex we are creating a lazy iterator where `ValueAtOrBeforeTime/RangeValues` will trigger network IO. https://github.com/weaveworks/cortex/pull/442

**Comment by brian-brazil** [comment]
Covered by #2823
