### ISSUE TITLE
Calculating percentile with snmp entries

### ISSUE THREAD

**Issue by cchance27** [prometheus/prometheus#2890]
Not sure if i'm missing something but i'm trying to calculate bandwidth i have my graphs working for interface bandwidth stored from snmp into prometheus, but i can't seem to figure out a way to grab the 95th percentile value for an interface. 

Regardless of what i use i seem to keep getting thrown the error 

expected type range vector in call to function "rate", got instant vector

**Comment by brian-brazil** [comment]
Usage questions are best asked at https://groups.google.com/forum/#!aboutgroup/prometheus-users
