### ISSUE TITLE
ec2_sd_configs - context deadline exceeded

### ISSUE THREAD

**Issue by heestory** [prometheus/prometheus#2898]
Hi 
I face the issue(context deadline exceeded) when I configure ec2_sd_configs.

I try to access [public ip]9100/metrics, is okay, but! prometheuse give me a [private ip]9100/metrics! so I get a context deadline exceeded after set up a ec2_sd_configs

what should I do? plz give me some advice

**Comment by johrstrom** [comment]
I get this a lot when I have security groups misconfigured. So you have to be sure that your prometheus server has outbound and that the target has inbound set correctly.

**Comment by brian-brazil** [comment]
Usage questions are best asked at https://groups.google.com/forum/#!forum/prometheus-users
