### ISSUE TITLE
Scrape errors are not logged

### ISSUE THREAD

**Issue by AlekSi** [prometheus/prometheus#2903]
**What did you do?**
I run Prometheus with debug level logging. I stopped some exporter.

**What did you expect to see?**
Scrape error in the log.

**What did you see instead? Under which circumstances?**
Nothing about scrape error in the log. It's still present in `/target` page, but that's only current status, I would like to be able to find it in logs with timestamps.

prometheus-users thread: https://groups.google.com/d/topic/prometheus-users/Ut5gqYqGTgg/discussion

**Comment by brian-brazil** [comment]
Dupe of #2820
