### ISSUE TITLE
Rules fail to load with yaml unmarshal error in 2.00 alpha.3 release

### ISSUE THREAD

**Issue by hajzso** [prometheus/prometheus#2913]
**What did you do?**
I tried to load my alert ruleset using the 'rule_files:' directive. (see config below) I also tried with the [] notation, and indenting the path.

**What did you expect to see?**
Proemtheus starting up and rules loading succesfully. (When I start it without including the rule file, it starts)

**What did you see instead? Under which circumstances?**
Prometheus fails to start. See error message in the log section below. I don't get any errors when using the 1.7.1 release, same config loads any ruleset.

**Environment**

* System information:

Linux 4.4.0-1020-aws x86_64

* Prometheus version: 

prometheus, version 2.0.0-alpha.3 (branch: master, revision: 70f96b0ffb6567100ffc91f7c3fe4e57c8d9dedb)
  build user:       root@5630fb1ab539
  build date:       20170622-10:04:46
  go version:       go1.8.3

* Alertmanager version:

alertmanager, version 0.7.1 (branch: master, revision: ab4138299b94c78dc554ea96e2ab28d04b048059)
  build user:       root@97e9539a4c3f
  build date:       20170609-15:31:09
  go version:       go1.8.3

* Prometheus configuration file:
```
global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
- "alert.rules"

scrape_configs:
# Node exporter
  - job_name: 'node'
    scrape_interval: "15s"
    file_sd_configs:
      - files:
        - '/home/hajzso/prometheus/targets/node/*.json'
        - '/home/hajzso/prometheus/discovery/node/*.json'
# Blackbox exporter
  - job_name: 'blackbox_http'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - https:/example.com
        
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9115  # Blackbox exporter
```

* Rules file:
```
ALERT website_down
  IF probe_success == 0
  FOR 3m
  LABELS { severity = "hipchat" }
  ANNOTATIONS {
    summary = "Instance {{ $labels.instance }} down",
    description = "{{ $labels.instance }} has been down for more than 3 minutes.",
}

ALERT downage
  IF up == 0
FOR 1h
```
* Alertmanager configuration file:
```
route:
 group_by: [cluster]
 # If an alert isn't caught by a route, send it to hipchat.
 receiver: team-hipchat
 routes:
  # Send severity=hipchat alerts to hipchat.
  - match:
      severity: hipchat
    receiver: team-hipchat

receivers:
- name: team-hipchat
  hipchat_configs:
  - room_id: 12345
    auth_token: 12345
    notify: true
```

* Logs:
```
● prometheus.service - Prometheus server
   Loaded: loaded (/etc/systemd/system/prometheus.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2017-07-07 07:09:36 UTC; 2s ago
  Process: 31904 ExecStart=/home/hajzso/prometheus/prometheus/prometheus --config.file=/home/hajzso/prometheus/prometheus/prometheus.yml (code=exited, status=1/FAILURE)
 Main PID: 31904 (code=exited, status=1/FAILURE)

Jul 07 07:09:36 ip-10-0-0-157 prometheus[31904]: time="2017-07-07T07:09:36Z" level=info msg="Starting tsdb" source="main.go:210"
Jul 07 07:09:36 ip-10-0-0-157 prometheus[31904]: time="2017-07-07T07:09:36Z" level=info msg="tsdb started" source="main.go:216"
Jul 07 07:09:36 ip-10-0-0-157 prometheus[31904]: time="2017-07-07T07:09:36Z" level=info msg="Loading configuration file /home/hajzso/prometheus/prometheus/prometheus.yml" source="main.go:344"
Jul 07 07:09:36 ip-10-0-0-157 prometheus[31904]: time="2017-07-07T07:09:36Z" level=error msg="yaml: unmarshal errors:
Jul 07 07:09:36 ip-10-0-0-157 prometheus[31904]:   line 1: cannot unmarshal !!str `ALERT w...` into rulefmt.RuleGroups" source="manager.go:484"
Jul 07 07:09:36 ip-10-0-0-157 prometheus[31904]: time="2017-07-07T07:09:36Z" level=error msg="Failed to apply configuration: error loading rules, previous rule set restored" source="main.go:362"
Jul 07 07:09:36 ip-10-0-0-157 prometheus[31904]: time="2017-07-07T07:09:36Z" level=error msg="Error loading config: one or more errors occurred while applying the new configuration (-config.file=/home/hajzso/prometheus/prometheus/prometheus.yml)" source="main.go:265"
Jul 07 07:09:36 ip-10-0-0-157 systemd[1]: prometheus.service: Main process exited, code=exited, status=1/FAILURE
Jul 07 07:09:36 ip-10-0-0-157 systemd[1]: prometheus.service: Unit entered failed state.
Jul 07 07:09:36 ip-10-0-0-157 systemd[1]: prometheus.service: Failed with result 'exit-code'.
e
```

**Comment by tinytub** [comment]
Try use `promtool update rules your.rules` command,
it will generate a new rules file called `your.rules.yml`

**Comment by Gouthamve** [comment]
Yes, for more info read: https://prometheus.io/blog/2017/06/21/prometheus-20-alpha3-new-rule-format/

Closing as there is nothing here to do. Please re-open if you think otherwise.

**Comment by wangybelle** [comment]
serverFiles:
  rules.yml: |
    groups:
    - name: example
      rules:
      - alert: InstanceDown
        expr: up == 0
        for: 5m
        labels:
          severity: page
        annotations:
          summary: "Instance {{ $labels.instance }} down"
          description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 5 minutes."

      - alert: APIHighRequestLatency
        expr: api_http_request_latencies_second{quantile="0.5"} > 1
        for: 10m
        annotations:
          summary: "High request latency on {{ $labels.instance }}"
          description: "{{ $labels.instance }} has a median request latency above 1s (current value: {{ $value }}s)"

  prometheus.yml:
    rule_files:
      - "/etc/config/rules.yml"

**Hello, I got following error on the above configurations in prometheus. Please help me**

level=info ts=2018-01-25T07:25:34.887714618Z caller=kubernetes.go:100 component="target manager" discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2018-01-25T07:25:34.888985459Z caller=kubernetes.go:100 component="target manager" discovery=k8s msg="Using pod service account via in-cluster config"
level=error ts=2018-01-25T07:25:34.890128487Z caller=manager.go:485 component="rule manager" 
msg="loading groups failed" err="yaml: unmarshal errors:\n  line 1: cannot unmarshal !!str `groups:...` into rulefmt.RuleGroups"
level=error ts=2018-01-25T07:25:34.890175318Z caller=main.go:413 msg="Failed to apply configuration" err="error loading rules, previous rule set restored"
level=info ts=2018-01-25T07:25:34.890570093Z caller=kubernetes.go:100 component=notifier discovery=k8s msg="Using pod service account via in-cluster config"

**Comment by vdice** [comment]
@wangybelle I assume this is from using the [prometheus helm chart](https://github.com/kubernetes/charts/tree/master/stable/prometheus)?  I ran into this as well.

Try:

```
rules.yml:
  groups:
  - name: example
    rules:
...
```
(Basically, remove the `|` or `|-`, etc. after `rules.yaml:`)
