### ISSUE TITLE
Switch to curator-go treecache

### ISSUE THREAD

**Issue by brian-brazil** [prometheus/prometheus#2914]
The treecache implementation used in our zookeeper service discovery was something I wrote as none existed in Go at the time. I attempted to get it upstreamed into a more appropriate library, but it appears that https://github.com/curator-go/curator/ is now the standard.

I think we should switch to that library rather than continuing to maintain our own version.

**Comment by StephanErb** [comment]
This sounds like a good idea. The current implementation is collapsing regularly due to shortcomings of the used ZK go library (https://github.com/samuel/go-zookeeper/issues/121, https://github.com/samuel/go-zookeeper/issues/133)

**Comment by brian-brazil** [comment]
curator-go relies on the same ZK library as what we have - there's only one of them in Go as far as I'm aware.

**Comment by StephanErb** [comment]
I have filed https://github.com/samuel/go-zookeeper/issues/165 as a desperate attempt. Let's see what comes out of it.

**Comment by cstyan** [comment]
@brian-brazil I'll give this a shot. Should I branch from master or 2.0?

**Comment by brian-brazil** [comment]
Master.

**Comment by elifkus** [comment]
@brian-brazil 

I looked into the go-curator TreeCache implementation here. https://github.com/curator-go/curator/blob/master/recipes/cache/tree_cache.go

You’d like to remove this code https://github.com/prometheus/prometheus/blob/master/util/treecache/treecache.go and use the code above. Am I right?

The curator tree_cache implementation has a dependency on the curator client. Do you want to use curator itself as well? 

(I couldn't find an implementation of tree_cache in go-curator that doesn’t have a dependency on the curator client.)

**Comment by brian-brazil** [comment]
> Am I right?

Yes.

**Comment by elifkus** [comment]
go-curator seems to be unmaintained. Also [this issue (Fix various race conditions #4)](https://github.com/curator-go/curator/issues/4#issuecomment-313345850) and especially [this comment](https://github.com/curator-go/curator/issues/4#issuecomment-313345850) makes me think that using go-curator is not a good idea.

**Comment by elifkus** [comment]
curator-go looks unmaintained. [This issue Fix various race conditions #4](https://github.com/curator-go/curator/issues/4) especially [this comment](https://github.com/curator-go/curator/issues/4#issuecomment-313345850) makes me think that using curator-go is not a good idea.

**Comment by Gustavo2008** [comment]
Manter o padrão é sempre bom!
Parabéns pelo código, ficou muito bom.

**Comment by roidelapluie** [comment]
@nemith Are you interested by our treecache implementation for https://github.com/go-zookeeper ? https://github.com/prometheus/prometheus/tree/master/util/treecache

**Comment by nemith** [comment]
Add "recipes" to go-zookeeper has always been the plan.  I think a pull request would be welcomed and help on support would be nice as well.

**Comment by gaurangkudale** [comment]
Hi @roidelapluie ,
It looks like `curator-go` not has been maintained from long time

> Add "recipes" to go-zookeeper has always been the plan. I think a pull request would be welcomed and help on support would be nice as well.

How can I help here?

**Comment by krajorama** [comment]
Hello from the bug scrub: this doesn't seem like a current problem, please reopen if there's a need.
