### ISSUE TITLE
After restart Prometheus, it try to dump all tsdb data to memory - prometheus-2.0

### ISSUE THREAD

**Issue by tinytub** [prometheus/prometheus#2917]
[NOTICE]: <> (If your question is around usage and not a bug in Prometheus please use: https://groups.google.com/forum/#!forum/prometheus-users)

**What did you do?**
Try to benchmark prometheus 2.0.0-alpha-3
and set prometheus scrape-interval to 1s , then scrape 6 test host and they have tatal 50w samples .
After one hour, prometheus still scrape, but memory use is about 12g and still raise.
I killed prometheus and try to restart it, the main process is start,
log stop at "INFO[0000] Starting tsdb                                 source="main.go:210""
it looks like prometheus try to dump all tsdb data to memory, after 30 minutes, prometheus memory res usage is about 33g, and my prometheus data dir is same size. 
![image](https://user-images.githubusercontent.com/1871460/27956440-6ef71dca-634c-11e7-9abb-6f286d2b2cbb.png)
![image](https://user-images.githubusercontent.com/1871460/27956453-7e4379cc-634c-11e7-8a44-9abd64de76cb.png)

finally after another 10 minutes I got "tsdb started" log ,but the memory usage not go down

**Environment**

* System information:

Linux 2.6.32-642.15.1.el6.x86_64 x86_64
* Prometheus version: 

prometheus, version 2.0.0-alpha.3 (branch: master, revision: 70f96b0ffb6567100ffc91f7c3fe4e57c8d9dedb)
  build user:       root@5630fb1ab539
  build date:       20170622-10:04:46
  go version:       go1.8.3

**Comment by fabxc** [comment]
> they have tatal 50w samples

What does that mean?

What are you scraping from these host in general. By default we keep the last 4h in memory. At 1s scrape intervals that naturally has implications for the memory consumed in total.

**Comment by tinytub** [comment]
total 500000 metrics,
I edit the example in https://github.com/prometheus/client_golang
Then I can get about 80000 metrics from every host.

Thanks for the help, I'll try it
