### ISSUE TITLE
bench.go imports "testing", pollutes global flag namespace

### ISSUE THREAD

**Issue by tomwilkie** [prometheus/prometheus#2920]
promql/bench.go imports testing for a non-test module, which means anyone who imports the promql package (cortex) gets all the test flags in non-test binaries.

**Comment by fabxc** [comment]
I think I took a stab at this a couple of times and it's just hard to get out.
The answer is ultimately to not use the global flag set for your applications – which you should never be doing anyway ;)

**Comment by tomwilkie** [comment]
Rgr.  I think this simple fix might do the trick, if people don't find it to distasteful.
