### ISSUE TITLE
Prometheus 2.0 dynamically linked on Linux

### ISSUE THREAD

**Issue by brian-brazil** [prometheus/prometheus#2922]
When I build the dev-2.0 branch via `make`, I'm getting a dynamically linked binary. This should be static.

We should figure out what's going wrong.

**Comment by Gouthamve** [comment]
Heres why: https://github.com/prometheus/promu/issues/60

I tried to hack this in: https://github.com/prometheus/prometheus/pull/2460 but closed it.

From @mxinden's comment on the linked issue, I think to build static binaries, we need to have write access to $GOROOT. Alternatively we could use docker, but that looks like a harder requirement.

The same happens to 1.0 also, btw.

**Comment by brian-brazil** [comment]
We've already got a bug for that, so no need to keep this one open. Sounds like it'll be fixed in Go 1.10.
