### ISSUE TITLE
Make sure SD mechanisms are resilient to failure

### ISSUE THREAD

**Issue by brian-brazil** [prometheus/prometheus#2924]
There have been a few reports of all/many targets being removed when a SD failed in some way.

We should keep using the old target information when a SD fails. Confirm this is what we're doing inside Prometheus, and within each SD mechanism (i.e. SD mechanisms should hard fail rather than returning partial results).

**Comment by brian-brazil** [comment]
#2924 is an example of this.

**Comment by krajorama** [comment]
Hello from the bug scrub: we're closing this as it doesn't seem to be a pain-point. Please reopen if there's a need.
