### ISSUE TITLE
invalid metric name "collectd_docker_cpu.percent &  invalid metric name "collectd_mesos-slave_bytes"

### ISSUE THREAD

**Issue by vishksaj** [prometheus/prometheus#2929]
**What did you see instead? Under which circumstances?**

Configured prometheus for dev environment could see that prometheus is not accepting metrics with '-' and '.' is there any way to fix this issue using collectd exporter (https://github.com/signalfx/docker-collectd-plugin) in target ( Write Http : JSON )

**Environment** --Dev

* System information:

Linux 3.10.0-514.10.2.el7.x86_64 x86_64

* Prometheus version: 

1.7.1

* Prometheus configuration file:
```
lobal:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
rule_files:
- /etc/prometheus/cpu.rules
scrape_configs:
- job_name: collectd
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - 192.168.3.16:9103

**Comment by brian-brazil** [comment]
These are invalid metric names, I'd suggest filing a bug with the metric provider to sanitise them to underscores.
