### ISSUE TITLE
Local building prometheus binary files.

### ISSUE THREAD

**Issue by psyelephant** [prometheus/prometheus#2933]
Hello! How can I build Prometheus locally without internet access? 
I have changed several things across javascript files, ex. prom_console.js.
But when I building binaries my changes keeps excluded, and I see standard prom_console.js.

Little notice - I really newbie in go and so one.

May I ask for some advice?

Thank you!

**Comment by brian-brazil** [comment]
Questions relating to developing Prometheus should be asked at https://groups.google.com/forum/#!aboutgroup/prometheus-developers
