### ISSUE TITLE
Remote Read for 2.0

### ISSUE THREAD

**Issue by Gouthamve** [prometheus/prometheus#2945]
This is the issue to track for 2.x:

- [x] Remote reading from external sources
- [ ] Remote read endpoint in Prometheus to allow it to act as an LTS

**Comment by brian-brazil** [comment]
> Remote read endpoint in Prometheus to allow it to act as an LTS

With my proposal for transition, this needs to happen in 1.x.

**Comment by brian-brazil** [comment]
See also #2811

**Comment by tomwilkie** [comment]
I have "Remote read endpoint in Prometheus to allow it to act as an LTS" almost working in a branch here, will push preliminary PR tomorrow morn.
