### ISSUE TITLE
prometheus cannot find all k8s resouces, such as pod/services etc. 

### ISSUE THREAD

**Issue by iloayuil** [prometheus/prometheus#2947]
Prometheus reported the error information below after I deployed EFK:
"
time="2017-07-14T06:43:21Z" level=error msg="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:180: Failed to list *v1.Service: User "system:serviceaccount:monitoring:default" cannot list all services in the cluster" component="kube_client_runtime" source="kubernetes.go:75" 
time="2017-07-14T06:43:21Z" level=error msg="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:245: Failed to list *v1.Node: User "system:serviceaccount:monitoring:default" cannot list all nodes in the cluster" component="kube_client_runtime" source="kubernetes.go:75" 
time="2017-07-14T06:43:21Z" level=error msg="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:179: Failed to list *v1.Endpoints: User "system:serviceaccount:monitoring:default" cannot list all endpoints in the cluster" component="kube_client_runtime" source="kubernetes.go:75" 
time="2017-07-14T06:43:21Z" level=error msg="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:207: Failed to list *v1.Pod: User "system:serviceaccount:monitoring:default" cannot list all pods in the cluster" component="kube_client_runtime" source="kubernetes.go:75" 
time="2017-07-14T06:43:21Z" level=error msg="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:227: Failed to list *v1.Service: User "system:serviceaccount:monitoring:default" cannot list all services in the cluster" component="kube_client_runtime" source="kubernetes.go:75" 
time="2017-07-14T06:43:22Z" level=error msg="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:180: Failed to list *v1.Service: User "system:serviceaccount:monitoring:default" cannot list all services in the cluster" component="kube_client_runtime" source="kubernetes.go:75" 
time="2017-07-14T06:43:22Z" level=error msg="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:181: Failed to list *v1.Pod: User "system:serviceaccount:monitoring:default" cannot list all pods in the cluster" component="kube_client_runtime" source="kubernetes.go:75" 
time="2017-07-14T06:43:22Z" level=error msg="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:207: Failed to list *v1.Pod: User "system:serviceaccount:monitoring:default" cannot list all pods in the cluster" component="kube_client_runtime" source="kubernetes.go:75" 
time="2017-07-14T06:43:22Z" level=error msg="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:227: Failed to list *v1.Service: User "system:serviceaccount:monitoring:default" cannot list all services in the cluster" component="kube_client_runtime" source="kubernetes.go:75" 
time="2017-07-14T06:43:22Z" level=error msg="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:179: Failed to list *v1.Endpoints: User "system:serviceaccount:monitoring:default" cannot list all endpoints in the cluster" component="kube_client_runtime" source="kubernetes.go:75"
"

What shoud I do now? @Conorbro

**Comment by matthiasr** [comment]
this looks like a permissions / RBAC issue – Kubernetes is denying the Prometheus service account the access it needs. Check the roles and role bindings.

Please post usage questions to the prometheus-users mailing list, not issues.
