### ISSUE TITLE
Prometheus 2: no token found for scraping target

### ISSUE THREAD

**Issue by iobestar** [prometheus/prometheus#2959]
**What did you do?**
Set up monitoring side-by side Prometheus 1.x and Prometheus 2.x

**What did you expect to see?**
Identical set of active scraping targets.

**What did you see instead? Under which circumstances?**
Some scraping targets are down on Prometheus 2.x with exception "no token found".

* Prometheus version: 
prometheus, version 2.0.0-beta.0 (branch: master, revision: 2b5d9159537cbd123219296121e05244e26c0940)
  build user:       root@fc24486243df
  build date:       20170712-12:24:53
  go version:       go1.8.3

After troubleshooting I discover that a problem is in label name. When metric has label which starts with underscore scraping fails. For example:
FAILS: DatabaseInvoker_MaxWorkers{_name="Main",} 10.0
OK: DatabaseInvoker_MaxWorkers{name="Main",} 10.0

**Comment by brian-brazil** [comment]
A leading underscore on a labelname is discouraged, however it is supported.

**Comment by juliusv** [comment]
Fixing.

**Comment by juliusv** [comment]
Fix in https://github.com/prometheus/prometheus/pull/2961

**Comment by Gouthamve** [comment]
Can this be closed?

**Comment by juliusv** [comment]
@Gouthamve Thanks, yes, closing.

I don't understand why this issue wasn't auto-closed, since https://github.com/prometheus/prometheus/pull/2961 contained a "Fixes ..." mention for this issue in the commit and PR description.

**Comment by Gouthamve** [comment]
That is because issues are closed only when merges happen into the default branch of the repo. I was also surprised and had to look the exact rules up.
