### ISSUE TITLE
Incorrect target endpoint link

### ISSUE THREAD

**Issue by rvgate** [prometheus/prometheus#2964]
**What did you do?**
wget https://github.com/prometheus/prometheus/releases/download/v1.7.1/prometheus-1.7.1.linux-amd64.tar.gz
tar xvfz prometheus-1.7.1.linux-amd64.tar.gz
cd prometheus-1.7.1.linux-amd64/
./prometheus
Then navigate to http://localhost:9090/targets

Tried both with:
prometheus-2.0.0-beta.0.linux-amd64.tar.gz
prometheus-1.7.1.linux-amd64.tar.gz

**What did you expect to see?**
I expected the Endpoint target link to be matching the link description. Clicking it should get me to that location. For example, the default target "http://localhost:9090/metrics" should bring me to "http://localhost:9090/metrics" when you click it.

**What did you see instead? Under which circumstances?**
The target "http://localhost:9090/metrics" brings me to "http://myhostname:9090/metrics"

* System information:

	Linux 4.4.0-83-generic x86_64

* Prometheus version: 

	prometheus, version 1.7.1 (branch: master, revision: 3afb3fffa3a29c3de865e1172fb740442e9d0133)
	build user:       root@0aa1b7fc430d
	build date:       20170612-11:44:05
	go version:       go1.8.3

* Prometheus configuration file:
unchanged

* Alertmanager configuration file:
unchanged

* Logs:
nothing relevant

* Screenshot:
![prometheus-targets](https://user-images.githubusercontent.com/1440528/28322167-b679c864-6bd5-11e7-9e4a-cf9216bf5ed0.png)

**Comment by brian-brazil** [comment]
This is by design, it's an old feature so that if you are on another machine and Prometheus is scraping "localhost" you'll still go to the right place.
