### ISSUE TITLE
Chunk encoding affects query results

### ISSUE THREAD

**Issue by AlekSi** [prometheus/prometheus#2965]
Please see this test: https://github.com/AlekSi/prometheus/blob/ec68e9722a8b740ee9631dc4ae58398f0f42f3a4/promql/range_test.go I expect it to return 21 values independent of chunk encoding. @SuperQ confirmed at IRC that query results should not be affected by storage. But they are: https://travis-ci.org/AlekSi/prometheus/builds/254887870

This test fails with both current master and v1.7.1.

**Comment by brian-brazil** [comment]
@beorn7

**Comment by beorn7** [comment]
Thanks @AlekSi for the perfect bug report including test.

This is intriguing, if the timestamp is off by 1ms, everything works as expected. I guess the chunk iterator in encoding v2 gets a hiccup if you hit a sample's timestamp precisely and then skips the next data point.

I'll try to nail this down in a unit test in the storage layer itself.
