### ISSUE TITLE
Matching escaped double quotes

### ISSUE THREAD

**Issue by iobestar** [prometheus/prometheus#2974]
**What did you do?**
PromQL: `metric_foo_bar{name="\"bar\""}`

**What did you expect to see?**
Data endpoints for metric metric_foo_bar with where label 'name' have value `'"bar"'`

**What did you see instead? Under which circumstances?**
No data endpoints.

* Prometheus version: 
prometheus, version 2.0.0-beta.0 (branch: master, revision: 2b5d9159537cbd123219296121e05244e26c0940)
  build user:       root@fc24486243df
  build date:       20170712-12:24:53
  go version:       go1.8.3

This query works on Prometheus 1.7.1 but on Prometheus 2.0 I had to replace it with regex matcher:
`metric_foo_bar{name=~".+bar.+"}`

**Comment by Gouthamve** [comment]
@iobestar Can you try: `metric_foo_bar{name="\"bar\""}` ?

In any case, @brian-brazil WDYT?

**Comment by brian-brazil** [comment]
That query does not work on 1.x, it should be escaped as you suggest.

**Comment by iobestar** [comment]
Correction of my initial post I am using escaped double quotes (escape disappear in presentation):
PromQL: `metric_foo_bar{name="\"bar\""}`

Escaped double quotes works on Prometheus 1.x but it doesn't work on Prometheus 2.0

**Comment by juliusv** [comment]
Confirmed, this is a bug in the new text protocol parser, which just extracts slices of the underlying input bytes into label values verbatim, without doing any interpretation of escape sequences `\n`, `\"`, or `\\`. So it stores the wrong label value, and then of course it can't be selected.

Problematic place in the code: https://github.com/prometheus/prometheus/blob/dev-2.0/pkg/textparse/parse.go#L108-L132

**Comment by Gouthamve** [comment]
Fixed in #2995
