### ISSUE TITLE
Feature Request: Allow registering multiple times (with flag)

### ISSUE THREAD

**Issue by DrewDennison** [prometheus/prometheus#2981]
Hello,

I'm using Prometheus with Scala and the Play Framework 2.5. Play will hot-reload every time there is a code change which means `.register()` is called multiple times. This causes errors saying there is already a collector with that name registered. I would like to disable the exception at registration if there is something with the same name. Perhaps it could print a warning?

**Comment by brian-brazil** [comment]
This is a feature request for the Java client, you should file it there. This behaviour is intended though, as it is a mistake to register multiple collectors with the same name.
