### ISSUE TITLE
alertmanager flag unknown in v2.0-beta

### ISSUE THREAD

**Issue by lcouto** [prometheus/prometheus#2984]
When passing the "-alertmanger.url" flag (v2.0-beta), I'm receiving the following message:
"prometheus: error: unknown long flag '--alertmanager.url'"

I tried it without the double "--" and received the following message:
"prometheus: error: unknown short flag '-a'"

**Comment by juliusv** [comment]
Yeah, the flag (which was previously deprecated) has been removed in 2.x and Alertmanagers can only be configured in the config file now. See https://prometheus.io/blog/2017/06/21/prometheus-20-alpha3-new-rule-format/

That'll be more properly documented soon.
