### ISSUE TITLE
Support for GZIP compression on federation endpoint

### ISSUE THREAD

**Issue by boeboe** [prometheus/prometheus#2986]
Hi,

I'd like to know if there is support to enable GZIP compression on the federation endpoint? I noticed that right now "text/plain" is used without compression. I'm looking for something like:

    Content-Type: text/plain
    Content-Encoding: gzip 

Currently I am confronted with 55k line of metrics, resulting in 23.1MB of plain text data to be send every scrape interval. When there would be support for GZIP compression, the wire transfer amount would be 1.7MB, resulting in 92% of bandwidth saviour.

Example metrics attached as file.
[metrics.log.gz](https://github.com/prometheus/prometheus/files/1172471/metrics.log.gz)

**Comment by grobie** [comment]
We already support gzip compression. You need to set the `Accept-Encoding: gzip` HTTP header.

```
curl -v -s -H 'Accept-Encoding: gzip' 'http://demo.robustperception.io:9090/federate?match\[\]=up%7Bjob%3D%22prometheus%22%7D' >/dev/null 2>&1 | grep Content-        
< Content-Encoding: gzip
< Content-Type: text/plain; version=0.0.4
< Content-Length: 124
```

**Comment by brian-brazil** [comment]
You should also take a look at https://www.robustperception.io/federation-what-is-it-good-for/

**Comment by boeboe** [comment]
Thanks for your quick response @brian-brazil .

Exactly how is this configured on the configuration side (https://prometheus.io/docs/operating/federation) or is this done out of the box?

BR,
Bart
