### ISSUE TITLE
https://prometheus.io is down

### ISSUE THREAD

**Issue by mza97** [prometheus/prometheus#2987]
https://prometheus.io is down, any solution to download it ?

**Comment by grobie** [comment]
I can't confirm, it's up form 3 different locations I just checked. We use cloudflare as CDN, it's highly unlikely that CloudFlare is down.

http://downforeveryoneorjustme.com/prometheus.io

**Comment by mza97** [comment]
Since friday it was not working, but now I check the downforeveryoneorjustme website it's working again lol I don't know why

**Comment by Gouthamve** [comment]
Thanks for letting us know! But I think it could have been a very short hiccup in your or Cloudflare's network.

As this is not a bug anymore, I am closing it. Please feel free to reopen if anything changes.
