### ISSUE TITLE
/flags has pointers instead of values (v2 beta 0)

### ISSUE THREAD

**Issue by aecolley** [prometheus/prometheus#2993]
**What did you do?**
Visited /flags on a running prom/prometheus:v2.0.0-beta.0 Docker container

**What did you expect to see?**
"alertmanager.notification-queue-capacity | 10000"

**What did you see instead? Under which circumstances?**
"alertmanager.notification-queue-capacity | {0xc4204183e8}"

**Environment**

* System information:

	Docker 1.11.1 on linux 4.9.13 (minikube 0.20.0, virtualbox)

**Comment by Gouthamve** [comment]
Fixed in #2998
