### ISSUE TITLE
azure_sd_configs api change

### ISSUE THREAD

**Issue by yosefy** [prometheus/prometheus#2994]
on site in documentation says
azure_sd_configs:

__meta_azure_tag_<tagname>
while it is:
__meta_azure_machine_tag_<tagname>

![image](https://user-images.githubusercontent.com/12940013/28616837-e16ed46a-7206-11e7-927d-4fc34db837e5.png)

**Comment by grobie** [comment]
Thanks! Want to file a PR against https://github.com/prometheus/docs/blob/master/content/docs/operating/configuration.md ?

**Comment by yosefy** [comment]
done

thanks
