### ISSUE TITLE
[2.0 beta] addrConn.resetTransport failed to create client transport

### ISSUE THREAD

**Issue by hiscal2015** [prometheus/prometheus#3004]
Hi, all

When I'm testing 2.0 beta version, everything looks fine but one error repeats in logs:

```
prometheus[3766]: 2017/07/30 07:44:58 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp [::]:9090: connect: cannot assign requested address"; Reconnecting to {[::]:9090 <nil>}

```

What does this mean, do I need to fix this? Thanks.

**Comment by Gouthamve** [comment]
This looks like an error from the new GRPC API. Not sure what the issue is.

/cc @fabxc

**Comment by vinihi83** [comment]
I get the same thing. I am using 'prometheus-2.0.0-beta.0.windows-amd64.tar.gz'

> prometheus-2.0.0-beta.0.windows-amd64.tar.gz

`D:\tools\prometheus-2.0.0>prometheus.exe --config.file=./prometheus.yml
INFO[0000] Starting prometheus (version=2.0.0-beta.0, branch=master, revision=2b5d9159537cbd123219296121e05244e26c0940)  source="main.go:202"
INFO[0000] Build context (go=go1.8.3, user=root@fc24486243df, date=20170712-12:28:38)  source="main.go:203"
INFO[0000] Host details (windows)                        source="main.go:204"
INFO[0000] Starting tsdb                                 source="main.go:216"
INFO[0000] tsdb started                                  source="main.go:222"
INFO[0000] Loading configuration file ./prometheus.yml   source="main.go:351"
INFO[0000] Starting target manager...                    source="targetmanager.go:67"
INFO[0000] Listening on 0.0.0.0:9090                     source="web.go:286"
2017/08/08 20:03:43 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: failed to do connect handshake, response: \"HTTP/1.1 503 Service Unavailable\\r\\nConnection: close\\r\\nContent-Length: 768\\r\\nCache-Control: no-cache\\r\\nContent-Type: text/html; charset=utf-8\\r\\nPragma: no-cache\\r\\nProxy-Connection: close\\r\\n\\r\\n<HTML><HEAD>\\r\\n<TITLE>Network Error</TITLE>\\r\\n</HEAD>\\r\\n<BODY>\\r\\n<FONT face=\\\"Helvetica\\\">\\r\\n<big><strong></strong></big><BR>\\r\\n</FONT>\\r\\n<blockquote>\\r\\n<TABLE border=0 cellPadding=1 width=\\\"80%\\\">\\r\\n<TR><TD>\\r\\n<FONT face=\\\"Helvetica\\\">\\r\\n<big>Network Error (tcp_error)</big>\\r\\n<BR>\\r\\n<BR>\\r\\n</FONT>\\r\\n</TD></TR>\\r\\n<TR><TD>\\r\\n<FONT face=\\\"Helvetica\\\">\\r\\nA communication error occurred: \\\"\\\"\\r\\n</FONT>\\r\\n</TD></TR>\\r\\n<TR><TD>\\r\\n<FONT face=\\\"Helvetica\\\">\\r\\nThe Web Server may be down, too busy, or experiencing other problems preventing it from responding to requests. You may wish to try again at a later time.\\r\\n</FONT>\\r\\n</TD></TR>\\r\\n<TR><TD>\\r\\n<FONT face=\\\"Helvetica\\\" SIZE=2>\\r\\n<BR>\\r\\nFor assistance, contact your network support team.\\r\\n</FONT>\\r\\n</TD></TR>\\r\\n</TABLE>\\r\\n</blockquote>\\r\\n</FONT>\\r\\n</BODY></HTML>\\r\\n\""; Reconnecting to {[::]:9090 <nil>}
2017/08/08 20:03:44 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: failed to do connect handshake, response: \"HTTP/1.1 503 Service Unavailable\\r\\nConnection: close\\r\\nContent-Length: 768\\r\\nCache-Control: no-cache\\r\\nContent-Type: text/html; charset=utf-8\\r\\nPragma: no-cache\\r\\nProxy-Connection: close\\r\\n\\r\\n<HTML><HEAD>\\r\\n<TITLE>Network Error</TITLE>\\r\\n</HEAD>\\r\\n<BODY>\\r\\n<FONT face=\\\"Helvetica\\\">\\r\\n<big><strong></strong></big><BR>\\r\\n</FONT>\\r\\n<blockquote>\\r\\n<TABLE border=0 cellPadding=1 width=\\\"80%\\\">\\r\\n<TR><TD>\\r\\n<FONT face=\\\"Helvetica\\\">\\r\\n<big>Network Error (tcp_error)</big>\\r\\n<BR>\\r\\n<BR>\\r\\n</FONT>\\r\\n</TD></TR>\\r\\n<TR><TD>\\r\\n<FONT face=\\\"Helvetica\\\">\\r\\nA communication error occurred: \\\"\\\"\\r\\n</FONT>\\r\\n</TD></TR>\\r\\n<TR><TD>\\r\\n<FONT face=\\\"Helvetica\\\">\\r\\nThe Web Server may be down, too busy, or experiencing other problems preventing it from responding to requests. You may wish to try again at a later time.\\r\\n</FONT>\\r\\n</TD></TR>\\r\\n<TR><TD>\\r\\n<FONT face=\\\"Helvetica\\\" SIZE=2>\\r\\n<BR>\\r\\nFor assistance, contact your network support team.\\r\\n</FONT>\\r\\n</TD></TR>\\r\\n</TABLE>\\r\\n</blockquote>\\r\\n</FONT>\\r\\n</BODY></HTML>\\r\\n\""; Reconnecting to {[::]:9090 <nil>}
2017/08/08 20:03:46 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: failed to do connect handshake, response: \"HTTP/1.1 503 Service Unavailable\\r\\nConnection: close\\r\\nContent-Length: 768\\r\\nCache-Control: no-cache\\r\\nContent-Type: text/html; charset=utf-8\\r\\nPragma: no-cache\\r\\nProxy-Connection: close\\r\\n\\r\\n<HTML><HEAD>\\r\\n<TITLE>Network Error</TITLE>\\r\\n</HEAD>\\r\\n<BODY>\\r\\n<FONT face=\\\"Helvetica\\\">\\r\\n<big><strong></strong></big><BR>\\r\\n</FONT>\\r\\n<blockquote>\\r\\n<TABLE border=0 cellPadding=1 width=\\\"80%\\\">\\r\\n<TR><TD>\\r\\n<FONT face=\\\"Helvetica\\\">\\r\\n<big>Network Error (tcp_error)</big>\\r\\n<BR>\\r\\n<BR>\\r\\n</FONT>\\r\\n</TD></TR>\\r\\n<TR><TD>\\r\\n<FONT face=\\\"Helvetica\\\">\\r\\nA communication error occurred: \\\"\\\"\\r\\n</FONT>\\r\\n</TD></TR>\\r\\n<TR><TD>\\r\\n<FONT face=\\\"Helvetica\\\">\\r\\nThe Web Server may be down, too busy, or experiencing other problems preventing it from responding to requests. You may wish to try again at a later time.\\r\\n</FONT>\\r\\n</TD></TR>\\r\\n<TR><TD>\\r\\n<FONT face=\\\"Helvetica\\\" SIZE=2>\\r\\n<BR>\\r\\nFor assistance, contact your network support team.\\r\\n</FONT>\\r\\n</TD></TR>\\r\\n</TABLE>\\r\\n</blockquote>\\r\\n</FONT>\\r\\n</BODY></HTML>\\r\\n\""; Reconnecting to {[::]:9090 <nil>}
WARN[0003] Received SIGTERM, exiting gracefully...       source="main.go:334"
INFO[0003] See you next time!                            source="main.go:341"
INFO[0003] Stopping target manager...                    source="targetmanager.go:81"
INFO[0003] Target manager stopped.                       source="targetmanager.go:93"
INFO[0003] Stopping rule manager...                      source="manager.go:454"
INFO[0003] Rule manager stopped.                         source="manager.go:460"
INFO[0003] Stopping notification handler...              source="notifier.go:471"
`

**Comment by Rucknar** [comment]
Just built and ran the `dev-2.0` branch and no longer see this error, where as i do when running the `beta0` build from dockerhub. Suspect it was fixed shortly after the beta was cut.

**Comment by hiscal2015** [comment]
Upgraded to 2.0.0-beta.1, still have this issue.

**Comment by mkjaer** [comment]
I have this issue with 2.0.0-beta.2

Ubuntu 17.04 / docker 17.06.1-ce

**Comment by haosdent** [comment]
Have this issue with 2.0.0-beta.2

**Comment by gjflsl** [comment]
@hiscal2015 When you runing with web.listen-address="0.0.0.0:9090" and you system disable ipv6,you will get this waring message.

**Comment by aliasmee** [comment]
I also encountered the same error message, but did not affect the normal use.
Follow-up can be detected at boot time ipv6 have wood enabled, if not enabled, no longer try to bind ipv6.

**Comment by htdvisser** [comment]
I created Pull Request #3174 that fixes this issue (at least, for me)
