### ISSUE TITLE
Error executing query: parse error at char 31: unknown escape sequence U+0020 ' '

### ISSUE THREAD

**Issue by Keleir** [prometheus/prometheus#3010]
**What did you do?**

I have gathered some window system metrics via [**snmp_exporter**](https://github.com/prometheus/snmp_exporter), and got these value as following:
```
# HELP hrStorageUsed The amount of the storage represented by this entry that is allocated, in units of hrStorageAllocationUnits. - 1.3.6.1.2.1.25.2.3.1.6
# TYPE hrStorageUsed gauge
hrStorageUsed{hrStorageDescr="C:\\ Label:  Serial Number 40663d48"} 5.399618e+06
hrStorageUsed{hrStorageDescr="D:\\ Label:  Serial Number 54e7a6b6"} 650729
hrStorageUsed{hrStorageDescr="Physical Memory"} 18596
hrStorageUsed{hrStorageDescr="Virtual Memory"} 19331

# HELP hrStorageSize The size of the storage represented by this entry, in units of hrStorageAllocationUnits - 1.3.6.1.2.1.25.2.3.1.5
# TYPE hrStorageSize gauge
hrStorageSize{hrStorageDescr="C:\\ Label:  Serial Number 40663d48"} 7.838207e+06
hrStorageSize{hrStorageDescr="D:\\ Label:  Serial Number 54e7a6b6"} 2.6213887e+07
hrStorageSize{hrStorageDescr="Physical Memory"} 262135
hrStorageSize{hrStorageDescr="Virtual Memory"} 384577
```
But when I use this metric to present a `Singlestat` of disk usage with grafana, it occurs problem:

![singlestat_error](https://user-images.githubusercontent.com/7112075/28808086-157b3f06-76ac-11e7-800e-b35904935929.png)
The error info is:
```
{
  "status": "error",
  "errorType": "bad_data",
  "error": "parse error at char 31: unknown escape sequence U+0020 ' '",
  "message": "parse error at char 31: unknown escape sequence U+0020 ' '"
}
```
My opinion is that the label value `hrStorageDescr` contains some special characters just like `C:\\ Label:  Serial Number 40663d48` which makes the promsql query crash.

So I paste the query exprssion into prometheus's own query box, It also the same promble:

![prom_error](https://user-images.githubusercontent.com/7112075/28808309-70fc5a94-76ad-11e7-82b1-a7c9b91f4253.png)

**Environment**
* Prometheus version: `1.7.1`

**Comment by Gouthamve** [comment]
Hi I think you need escape the `\` in the query. Could you try: `{hrStorageDescr="C:\\ Label: SerialNumber...}`?

Also if its erroring at `:`, try escaping that too.

**Comment by Keleir** [comment]
@Gouthamve  I create a grafana `Templating` of hrStorageDescr with name `device` and refering it in query statment by `$device`:
```
Query: query_result(hrStorageSize{job="snmp_windows", instance="$server"})

Regex: .*hrStorageDescr="(.*?)",.*
```

![templating](https://user-images.githubusercontent.com/7112075/28863515-dbfecd1a-779b-11e7-9030-d61f1b73ecf9.png)


This will mathch the label values of hrStorageDescr:
```
C:\\ Label:  Serial Number 40663d48
D:\\ Label:  Serial Number 54e7a6b6
Physical Memory
Virtual Memory
```
With this templating, My query on grafana is:
```
( hrStorageUsed{hrStorageDescr="$device",instance=~"$server"} / hrStorageSize{hrStorageDescr="$device",instance=~"$server"}) * 100
```
But this occurs error as above.

**Comment by grobie** [comment]
Backslash needs to be escaped by another backslash. If grafana doesn't handle this correctly, open a bug report there.
