### ISSUE TITLE
[experimental] Ab-initio metrics delta monitoring for feature-extraction of important monitoring sets for specific applications.

### ISSUE THREAD

**Issue by jayunit100** [prometheus/prometheus#3012]
The universality of the prometheus metrics format and the large number of exporters gives us a good starting point for finding key reporting and system metrics for any running system, with our without custom metrics.

With legacy systems moving to prometheus, it would be great to be able to monitor delta's and changes as compared with a baseline of a healthy system, and one way to do this would be using metrics as feature vectors along with finger prints.

We've been experimenting with this approach and would be interested in contributing this to the prometheus community in some way as an optional module that was able to 'discover' important metrics in a running system, based on a starting / stopping time.

**Comment by brian-brazil** [comment]
Closed in favour of -dev email.
