### ISSUE TITLE
Remove uber-constructor in discovery package

### ISSUE THREAD

**Issue by fabxc** [prometheus/prometheus#3014]
Currently the discovery package has [one gigantic constructor](https://github.com/prometheus/prometheus/blob/master/discovery/discovery.go#L53-L133) for all known SD mechanism. This causes a huge dependency graph with all the SD's client libraries.
This should be refactored in a way the packages using `discovery` are responsible for importing SD packages directly instead.

**Comment by cstyan** [comment]
> This should be refactored in a way the packages using discovery are responsible for importing SD packages directly instead.
Those packages being notifier and targetmanager? And importing each SD mechanism in addition to `discovery` but just not calling `discovery.ProvidersFromConfig`

Can you confirm if the end goal is just to have those packages initialize all the SD mechanisms in the given config themselves? If so, I don't understand how that would fix the dependency issue.

**Comment by khalibartan** [comment]
@fabxc If this is not fixed I'd like to work on this.

**Comment by simonpasquier** [comment]
@khalibartan I've already opened https://github.com/prometheus/prometheus/pull/4913 to address this.

**Comment by roidelapluie** [comment]
Fixed by #7701 I think .. cc @brian-brazil

**Comment by brian-brazil** [comment]
Yeah, this can be closed.
