### ISSUE TITLE
Question: RPM source files for RHEL7?

### ISSUE THREAD

**Issue by fmunteanu** [prometheus/prometheus#3015]
Can you please provide a link to RPM source files for RHEL7?
https://packagecloud.io/prometheus-rpm/release/packages/el/7/prometheus-1.7.1-1.el7.centos.x86_64.rpm
This directory does not contain any visible files:
https://packagecloud.io/prometheus-rpm/release/el/7/SRPMS/

Regards,

Floren

**Comment by brian-brazil** [comment]
Those are not official rpms, I'd suggest looking at https://github.com/lest/prometheus-rpm
