### ISSUE TITLE
The memory Prometheus uses is going up and up, crashed my machine

### ISSUE THREAD

**Issue by krisoul** [prometheus/prometheus#3027]
prometheus, version 1.7.1

I  run Prometheus with default configuration, but its memory is going up and up, my machine's mem is 32G, and Prometheus crashed my machine.

Even though I configured Prometheus with specified mem-chunks, like this:
```
nohup ./prometheus -config.file=prometheus.yml \
-storage.local.retention=2160h \
-storage.local.memory-chunks=5242880 \
-storage.local.max-chunks-to-persist=3097152 \
-storage.local.num-fingerprint-mutexes=10240 \
-storage.local.series-file-shrink-ratio=0.2 \
-storage.local.checkpoint-interval=5m \
&> prometheus.log &
```
but the memory problem still happens.

Why?

**Comment by krisoul** [comment]
By the way, after my machine crashed, I restart my machine and Prometheus, then the crashrecovery starts, what drive me crazy is that **crashRecovery spent quite a long time, more than one hour, and still not finish**

```
time="2017-08-07T17:47:01+08:00" level=info msg="37900000 metrics queued for indexing." source="crashrecovery.go:534" 
time="2017-08-07T17:47:01+08:00" level=info msg="37910000 metrics queued for indexing." source="crashrecovery.go:534" 
time="2017-08-07T17:47:01+08:00" level=info msg="37920000 metrics queued for indexing." source="crashrecovery.go:534" 
time="2017-08-07T17:47:01+08:00" level=info msg="37930000 metrics queued for indexing." source="crashrecovery.go:534" 
time="2017-08-07T17:47:01+08:00" level=info msg="37940000 metrics queued for indexing." source="crashrecovery.go:534" 
time="2017-08-07T17:47:01+08:00" level=info msg="37950000 metrics queued for indexing." source="crashrecovery.go:534" 
time="2017-08-07T17:47:01+08:00" level=info msg="37960000 metrics queued for indexing." source="crashrecovery.go:534" 
time="2017-08-07T17:47:01+08:00" level=info msg="37970000 metrics queued for indexing." source="crashrecovery.go:534" 
time="2017-08-07T17:47:01+08:00" level=info msg="37980000 metrics queued for indexing." source="crashrecovery.go:534" 
time="2017-08-07T17:47:02+08:00" level=info msg="37990000 metrics queued for indexing." source="crashrecovery.go:534" 
time="2017-08-07T17:47:02+08:00" level=info msg="38000000 metrics queued for indexing." source="crashrecovery.go:534" 
time="2017-08-07T17:47:02+08:00" level=info msg="38010000 metrics queued for indexing." source="crashrecovery.go:534"
```

WTF?

**Comment by fabxc** [comment]
Please direct usage questions to the Prometheus users mail list.

**Comment by beorn7** [comment]
You have a lot of metrics in your database. Depending on how many are active at the same time, 32GiB of RAM is probably way too small.

What you describe is the expected behavior. You need to tweak flags and/or your setup and/or move to a bigger machine. Discussing those things makes more sense if it happens on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your questions, and the whole community can benefit from the answers provided.

**Comment by krisoul** [comment]
@beorn7 
thx to your attention, but why the memory exceed what configured very much,
![_20170807195553](https://user-images.githubusercontent.com/3422759/29025672-7da0b662-7baa-11e7-8b48-ec946ebd1438.png)

See, I just use the default configuration.

**Comment by beorn7** [comment]
As said, please bring your questions to the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users).

**Comment by krisoul** [comment]
@beorn7 okok,
can I ask two questions else?

**Comment by krisoul** [comment]
@beorn7 

Does Prometheus support dynamic granularity storage like rrdtool? 

For example:
If I set `scrape-interval=30s`,
in last 1st month, data's granularity is 30s;
in last 2nd month, data's granularity is 60s;
in last 3rd month, data's granularity is 90s;
...

just like the granularity  can be adjusted dynamicly by the peroid in storage.

----------

If not, will Prometheus support this function in the near future?

**Comment by krisoul** [comment]
@beorn7 

Q2: I want to store nearly 2000 machines' metrics and there are 70 metrics of each machine, so what kind of configuration or performance of my Prometheus server need at least?

Looking forward to your suggestion.

Best regard!
