### ISSUE TITLE
vendor.json in dev-2.0 is broken

### ISSUE THREAD

**Issue by AlekSi** [prometheus/prometheus#3030]
Please look there: https://github.com/prometheus/prometheus/blob/dev-2.0/vendor/vendor.json Search for `84bc9597164f671c0130543778228928d6865c5c`. You will see it for too many import paths. This commit exists in cockroachdb repository (https://github.com/cockroachdb/cockroach/commit/84bc9597164f671c0130543778228928d6865c5c), but in https://github.com/petermattis/goid, for example. Notice also that those origin paths contain `/vendor/`. I can only guess that old version of Go or old version of govendor was used to update vendor.json.

The end result is that `govendor sync` fails with Go 1.8.3 and govendor 1.0.8.

Refs #3022.

**Comment by grobie** [comment]
Fixed in #3400.
