### ISSUE TITLE
Unexplained recording rule syntax example provided in docs

### ISSUE THREAD

**Issue by cmcginty** [prometheus/prometheus#3040]
I'm raising this issue because the current Recording Rule documentation is woefully lacking with respect to non-expert user such as myself.

I'm trying to implement a recording rule but the first example is using syntax that is not defined nor explained to the reader.

On the https://prometheus.io/docs/querying/rules/#configuring-rules page, the example is:

```
# Saving the per-job HTTP in-progress request count as a new set of time series:
job:http_inprogress_requests:sum = sum(http_inprogress_requests) by (job)
```
First, the left-hand value does not match the syntax defined immediately above it. Assuming the example is valid, could you please document the `<X>:<Y>:<Z>`values with respect to the right-hand query in the example?

Does the colon in this example have some special meaning?

**Comment by brian-brazil** [comment]
That's a convention defined in https://prometheus.io/docs/practices/rules/, and it does match the docs prior to it.
