### ISSUE TITLE
Windows binaries only available in tar.gz format !?!

### ISSUE THREAD

**Issue by NicolaiPetri** [prometheus/prometheus#3045]
Topic says it all. It doesn't make any sense to only provide binaries in tar.gz format, a .zip option should be available for windows users.

**Comment by matthiasr** [comment]
Could you please explain specifically why it "doesn't make any sense"?

**Comment by redbaron** [comment]
AFAIK bundled utilities cannot unpack tar.gz

**Comment by beorn7** [comment]
> AFAIK bundled utilities cannot unpack tar.gz

Is that really still the case? *facepalm*

Just as a data point: https://golang.org/dl/ offers the Windows archives as zip, so apparently that's still a thing. I guess it's easy enough to package the Windows download as zip.

**Comment by guhuajun** [comment]
Please try http://cmder.net/ with git for windows.

**Comment by NicolaiPetri** [comment]
To explain a bit further, windows does not have built-in support for tar.gz format. So installing prometheus on Windows then requires installation of 7zip or similar tools first. 
I can live with that for prototyping, but for doing automated installs and moving this to the "enterprise" world there is just problems for every piece of software you must add to get something working.
I was trying to make a script for an "instant prometheus" windows image, but this is my first hurdle.

**Comment by brian-brazil** [comment]
I'd suggest continuing this conversation on https://github.com/prometheus/promu/issues/46 as promu is where this change needs to be made.
