### ISSUE TITLE
Prometheus external_labels not available in Grafana

### ISSUE THREAD

**Issue by bkupidura** [prometheus/prometheus#3049]
Probably this is intentional behavior, but prometheus dosen't add external_labels to queries send by Grafana.

This can be useful for ex. exposing information about region name.

Can we treat that as feature requests? ;)

**Comment by brian-brazil** [comment]
Yes, that's intended currently. The presumption is you already know that due to the data source. If that not sufficient for you use case?

**Comment by bkupidura** [comment]
Right now we are thinking how we can support multi-region deployments. So we are researching about what options do we have, but we dont have ready architecture yet. 

But you have a point, in case we choose to federate "side-prometheuses" to "global-prometheus" external_labels will be there.

Region name available in "side-prometheuses" would be useful for us because we have already region_name in our logging solution. From user perspective it would be nice to be 100% sure that you are watching metrics from right environment. (in case federation would not be used)

**Comment by brian-brazil** [comment]
Grafana should generally talk directly to the Prometheus that has the data you want. Likely via data source templating in your case.
