### ISSUE TITLE
Migrate `/targets` to use `/api/v1/targets` as the backend

### ISSUE THREAD

**Issue by RichiH** [prometheus/prometheus#3069]
Very low prio, but `targets` should use `/api/v1/targets` instead of dumping HTML at the user.

**Comment by fabxc** [comment]
I'm against doing this partially.
We started implementing API endpoints for things visible in the UI a while
ago to support building UIs purely against the API. But we shouldn't
attempt migrating single pages to fetch data via JS while others remain
being rendered at the server.
That would just make our JS code more messy than it already is. Probably
needs a new UI like Alertmanager.

**Comment by grobie** [comment]
Same. Stuart, Andrey and I talked about a new UI already. Plans for this
have been around for a long time.

**Comment by RichiH** [comment]
Valid point; "migrate everything under /status once the new status APIs are done" sounds saner.

**Comment by brian-brazil** [comment]
New UI does this.
