### ISSUE TITLE
Prometheus 2.0: remote storage configuration is ignored

### ISSUE THREAD

**Issue by AlekSi** [prometheus/prometheus#3095]
[`github.com/prometheus/prometheus/config.QueueConfig`](https://github.com/prometheus/prometheus/blob/v2.0.0-beta.2/config/config.go#L1449) values are ignored in `dev-2.0` branch. This structure is duplicated by [`github.com/prometheus/prometheus/storage/remote.QueueManagerConfig`](https://github.com/prometheus/prometheus/blob/v2.0.0-beta.2/storage/remote/queue_manager.go#L126) which is not configurable.

In #2552 @brian-brazil wrote
> I'd suggest hardcoding to reasonable sane values, and seeing when someone wants it changed what their use case is.

I want to increase `max_samples_per_send` because 100 samples per insert is too small value for [PromHouse](https://github.com/Percona-Lab/PromHouse) and [ClickHouse](https://clickhouse.yandex).

Also, I would like to see `QueueManagerConfig` removed – that's one of the places where Prometheus duplicates the same code in different packages.

I can work on it if you are ok with it.

/cc @tomwilkie

**Comment by tomwilkie** [comment]
Yes, this change has been ported to v2 yet.  The remote code in master is ahead in many ways, once we get 1.8 out I'll sync them up.
