### ISSUE TITLE
Add "v1 latest" tag to Docker images

### ISSUE THREAD

**Issue by sandersaares** [prometheus/prometheus#3098]
The Docker image at https://hub.docker.com/r/prom/prometheus/tags/ currently has version-specific tags and latest/master tags but nothing that means "latest from the v1 branch".

This is desirable for automation scenarios that will pull a new Docker image on deploy. As there are breaking changes between v1 and v2, if one day "latest" points to v2 then those automated deploys will fail for no too-obvious reason.

If switching to v2 requires an explicit change in the Docker tag, the reason for any breakage after such an action is obvious. Therefore I request a "latest-v1" style tag, in addition to the existing ones.

**Comment by grobie** [comment]
@sdurrheimer

**Comment by sandersaares** [comment]
Aaaaand my "latest" targeting deployments are now broken with v2 being published.

**Comment by brian-brazil** [comment]
It seems unlikely at this stage that there will be further 1.x releases, so this is obsolete. In general if you use "latest" and things break, you get to keep both pieces.
