### ISSUE TITLE
Extract console templates from Prometheus itself

### ISSUE THREAD

**Issue by grobie** [prometheus/prometheus#3101]
We usually argue against features by using the argument of additional complexity and development resources spent. I see console templates falling clearly into that category and propose to extract them into a standalone repository. They are less used than PromDash was. Grafana is our answer to dashboarding and they show their clear interest in improving the Prometheus experience.

This would be a breaking change to be done in a major version release.

@brian-brazil

**Comment by brian-brazil** [comment]
Console templates use the same code as alert templates, so the main cost isn't going anywhere. They also require close to no maintenance and support, as alert templates are where we're seeing that.

I don't think we'd save anything by kicking them out to a separate repo, in fact I'd expect it to make whatever maintenance is required worse. As long as this feature exists, I think it belongs inside the Prometheus repo.

Console templates were always meant for more advanced use cases, and I wouldn't be so sure that they're less used than Promdash was.

**Comment by civik** [comment]
Personally I think console templates are the best/easiest way to embed Prometheus content into arbitrary web pages. For example, embedding some simple live metrics into a status page.   There is no way I'd want to be handcuffed to Grafana for any and all external visualizations.  I'm also starting to mess with consul templates as a API compatibility shim to tools like Cachet.  I'd hate to see that flexibility vanish from Prometheus.

**Comment by roidelapluie** [comment]
just dropping a line there to say that we are using console templates to expose a status page for our end users. So there are thousands of (end) users of that feature :)

**Comment by brian-brazil** [comment]
Yeah, splitting them out doesn't make sense.
