### ISSUE TITLE
Recording rule is different  from the recorded expression

### ISSUE THREAD

**Issue by Cplo** [prometheus/prometheus#3104]
[NOTICE]: <> (                                                                 )
[NOTICE]: <> (  Please do *NOT* ask usage questions in Github issues.          )
[NOTICE]: <> (                                                                 )
[NOTICE]: <> (  If your issue is not a feature request or bug report use:      )
[NOTICE]: <> (  https://groups.google.com/forum/#!forum/prometheus-users. If   )
[NOTICE]: <> (  you are unsure whether you hit a bug, search and ask in the    )
[NOTICE]: <> (  mailing list first.                                            )
[NOTICE]: <> (                                                                 )
[NOTICE]: <> (  You can read more at: https://prometheus.io/community/         )
[NOTICE]: <> (                                                                 )

**What did you do?**
I define the following recording rules:
```
node_exporter:node_cpu_use:percent{} = 100 * (1 - avg(rate(node_cpu{mode="idle"}[2m])) BY (instance, job))
node_exporter:node_cpu_mode_use:percent{} = 100 * avg(rate(node_cpu[2m])) BY (instance, mode)
node_exporter:node_mem_use:percent{} = 100 * (1 - (node_memory_MemFree + node_memory_Cached + node_memory_Buffers) / (1 + node_memory_MemTotal))
node_exporter:node_disk_use:percent{} = 100 * (1 - node_filesystem_free{device=~"/dev.*",mountpoint!~"/etc.*|/run.*"} / (1 + node_filesystem_size))
node_exporter:node_swapmem_use:percent{} = 100 * (node_memory_SwapTotal - node_memory_SwapFree) / (node_memory_SwapTotal + 1)
node_exporter:node_disk_util:percent{} = irate(node_disk_io_time_ms[2m]) / 10
node_exporter:node_disk_bytes_read{} = irate(node_disk_bytes_read[2m])
node_exporter:node_disk_bytes_write{} = irate(node_disk_bytes_written[2m])
node_exporter:node_disk_iops_read{} = irate(node_disk_reads_completed[2m])
node_exporter:node_disk_iops_write{} = irate(node_disk_writes_completed[2m])
node_exporter:node_disk_context_switches{} = irate(node_context_switches[2m])
node_exporter:node_network_receive_bytes{} = irate(node_network_receive_bytes[2m])
node_exporter:node_network_transmit_bytes{} = irate(node_network_transmit_bytes[2m])
node_exporter:node_time_diff{} = node_time - scalar(node_time{instance="tosqatest1"})
```
the metric **node_exporter:node_time_diff** value never changed，but the expression node_time - scalar(node_time{instance="tosqatest1"}) value normally changed by per job scrape interval (1 minute).

![2017-08-22 12-56-55](https://user-images.githubusercontent.com/9261394/29553667-bb23a882-874e-11e7-8140-afa731bcc0b7.png)
![2017-08-22 12-56-48](https://user-images.githubusercontent.com/9261394/29553677-cb889bba-874e-11e7-814d-ef08f9f74922.png)

**What did you expect to see?**
recording rule also change normally.
**What did you see instead? Under which circumstances?**

**Environment**

* System information:

	Linux 4.4.73-1.el7.elrepo.x86_64 x86_64

* Prometheus version:
  prometheus, version 1.7.1 (branch: master, revision: 3afb3fffa3a29c3de865e1172fb740442e9d0133)
  build user:       root@0aa1b7fc430d
  build date:       20170612-11:44:05
  go version:       go1.8.3

* Prometheus configuration file:
```
N/A
```

**Comment by brian-brazil** [comment]
I don't see anything odd here, query_range executes every 3s here while I presume your recording rule has a 1 minute interval. These are normal artifacts.
