### ISSUE TITLE
make docker results in broken image

### ISSUE THREAD

**Issue by discordianfish** [prometheus/prometheus#3109]
`make docker` runs `promu build` which creates a binary with cgo enabled for which the base image doesn't include the necessary shared libs.

**Comment by discordianfish** [comment]
Root cause: https://github.com/prometheus/promu/issues/60
We should probably just convert the makefile to use promu crossbuild which results in a statically linked binary.

**Comment by taion809** [comment]
I was able to fix this with a multi-stage docker build.  If that is acceptable I can push up my changes for review.

**Comment by discordianfish** [comment]
@taion809 Oh cool, in general yes! We should just make sure to not diverge too much from how Prometheus is built and it needs to work for cross compilation etc.

**Comment by taion809** [comment]
In that case I’ll push a branch up for review.  The change made doesn’t
change the makefile or the Use of promu so it should be ok :)

**Comment by simonpasquier** [comment]
@fish IIUC this issue isn't relevant anymore. Do you think it can be closed?

**Comment by discordianfish** [comment]
@simonpasquier Ah, yah I think this can be closed. Thanks for the ping!
