### ISSUE TITLE
Reloading Prometheus 2.0 has significant memory spikes

### ISSUE THREAD

**Issue by fabxc** [prometheus/prometheus#3112]
Since every scraper has a rather large cache now for all staleness handling and usage of `AddFast` a reload causes severe memory spikes of up to 2x.

On reload we terminate all scrapers as the configuration might have changed. In 2.0, each scraper carries a rather large cache around for staleness handling and usage of `AddFast`. Those caches are dropped and get re-created for all the "new" targets. The same happens with the known buffer sizes for each scraper.

We could investigate not purging all scrapers and instead try to hot-reload them as well where necessary. This needs some very careful consideration though.

@brian-brazil

**Comment by siavashs** [comment]
I noticed that the number of open files are doubled during reload (kept open ~5 minutes)
<img width="606" alt="start_-_reload" src="https://user-images.githubusercontent.com/113189/32500310-4b2d57a8-c3d5-11e7-8ebd-ed2c7613a007.png">
^ markers: start, reload

**Comment by roidelapluie** [comment]
It looks like 910c22418c9a94e6ccfbc46dd760f5f392a25775 fixed the initial issue.

**Comment by roidelapluie** [comment]
I have taken this approach over at #6670.

There are only a few fields changes that won't trigger a new cache:
- honor_timestamp
- scrape_interval
- scrape_timeout
- sample_limit
- http_config
