### ISSUE TITLE
Rounding problem with Y axis labels

### ISSUE THREAD

**Issue by candlerb** [prometheus/prometheus#3118]
(Relates to #3084)

**What did you do?**

Collect data from [apcupsd-exporter](https://github.com/damomurf/apcupsd-exporter)

In the console, entered `apcups_time_left_seconds/60` as the metric expression to graph

**What did you expect to see?**

A graph with battery remaining time in minutes rather than seconds

**What did you see instead? Under which circumstances?**

The graph is OK but the Y axis labels are broken.

![image](https://user-images.githubusercontent.com/44789/29744388-e00b8dc2-8a9b-11e7-8477-aebef3e271a0.png)

The data points are 20.5, 21, 21.5 (the raw data points are 1230, 1260, 1290)

Labels should be:

* 21.6
* 21.4
* 21.2
* 21.0
* 20.8
* 20.6
* 20.4

However the actual labels displayed are:

* 21.6
* 00000000002
* 00000000003
* 00000000004
* 00000000004
* 20.6
* 00000000002

**Environment**

* System information:

	Linux 4.4.0-87-generic x86_64

* Prometheus version:

    ~~~
    prometheus, version 2.0.0-beta.2 (branch: HEAD, revision: a52f082939a566d5269671e98be06fc6bdf61d09)
      build user:       root@41a0740ea598
      build date:       20170818-08:16:50
      go version:       go1.8.3
    ~~~

* Alertmanager version:

	N/A

* Prometheus configuration file:

default plus:

```
  - job_name: apcupsd
    scrape_interval: 60s
    static_configs:
      - targets: ['nuc2.example.com:8080']
```

* Alertmanager configuration file:

	N/A

* Logs:

	N/A

**Comment by brian-brazil** [comment]
Is this still happening with 1.7.2?

**Comment by candlerb** [comment]
I have only been using 2.0.0 train - the report was for 2.0.0 beta 2, and I am now on 2.0.0 beta 5.  If the fix is in beta 5 I can try to reproduce.

**Comment by brian-brazil** [comment]
It hasn't made it to the 2.0 branches yet.

**Comment by grobie** [comment]
Should be fixed, please re-open otherwise.
