### ISSUE TITLE
auto-repair attempt for LevelDB on corruption?

### ISSUE THREAD

**Issue by joernhees** [prometheus/prometheus#3120]
I'm using prometheus as part of a GitLab CE Omnibus installation... every now and then the leveldb behind it seems to go corrupt ( https://gitlab.com/gitlab-org/gitlab-ce/issues/37092 ).

While i think that the problem probably lies on gitlab's side by swallowing a TERM signal or the likes, i wonder: why doesn't prometheus (in production) try to auto-repair the DB?

In the current state i loose way more info by prometheus being down and not logging than i'd loose by minor DB inconsistencies, no?

**Comment by beorn7** [comment]
LevelDB will not be used anymore in v2.0 of Prometheus. There is very little incentive to invest significant work in improving LevelDB handling at this point.

**Comment by beorn7** [comment]
If anybody want's to take this, please let me know. Otherwise, I'll close as "won't fix".
