### ISSUE TITLE
2.0 question

### ISSUE THREAD

**Issue by Jaware** [prometheus/prometheus#3121]
i saw your blog about 2.0,you talked about the performance,but not very explicite.the 2.0release is master worker based cluster? or it is  still the same patern like version 1.0? and when will the release vesion be published?

**Comment by grobie** [comment]
As requested in the issue template, please do not open issues for questions, but use our mailing list https://groups.google.com/forum/#!forum/prometheus-users.

**Comment by Jaware** [comment]
。。。。。。。。。。。。。。。。。。。。。
