### ISSUE TITLE
make: makefile: line 15:  Error -- Badly specified macro for windows

### ISSUE THREAD

**Issue by atulsnapdeal** [prometheus/prometheus#3126]
Hi,

I tried to build this project via windows and when i ran the make build command. I got this error. Please help:

make: makefile: line 15:  Error -- Badly specified macro

I think, i tried to replace $ with % and some how it skipped this line error but followed by line 21. Is there any window compatible Makefile which can solve this problem or i need to do this in some other way.

Thanks,
Atul

**Comment by brian-brazil** [comment]
Which version and variant of make are you using?

**Comment by grobie** [comment]
Closing due to lack of response.
