### ISSUE TITLE
Prom 2.0: Not able to Query older data properly

### ISSUE THREAD

**Issue by KalivarapuReshma** [prometheus/prometheus#3128]
When we point prometheus 2.0 to a data directory that is 5 days old, the expression browser should show series from older blocks too, but it only shows series from head block. 

Further, this query fails: `{__name__=~".+"} ` over the 2y period  with no datapoints found.

**Comment by fabxc** [comment]
Was all your data written by Prometheus 2.0 or are those still files from
Prometheus 1.x?

**Comment by KalivarapuReshma** [comment]
Sorry, so I was creating blocks via TSDB and then checking. The blocks I created were for a short period and the step function just crosses over.

Lots of debugging into the querier and tsdb codebase revealed this to me (:
