### ISSUE TITLE
Dockerfile for Windows images

### ISSUE THREAD

**Issue by sixeyed** [prometheus/prometheus#3148]
** This is a feature request **

It would be great to have Windows versions of the official image.

I have a sample [Windows Dockerfile here](https://github.com/dockersamples/aspnet-monitoring/blob/master/prometheus/Dockerfile) which works well, but it takes a different approach from the Linux image. The Windows version deploys the published release rather than building from source.

Looking for feedback - I'm happy to maintain the Windows variants, and I can also set up CI (it would need to be AppVeyor at this stage, as they're the only service to provide Windows agents).

**Comment by grobie** [comment]
Soo, we have another request for a custom Docker image following #2693. I'm not sure a generic approach via promu will work in all cases. How do people feel about just adding new Dockerfiles everytime someone contributes one?

@juliusv @brian-brazil @fabxc

**Comment by brian-brazil** [comment]
I think we need to support this in a standard way everywhere, or nowhere. We've had a few of these requests, how many different archs are we going to be asked for?

For Windows in particular, given that none of us are Windows people will we be able to maintain this?

**Comment by sixeyed** [comment]
Fair point @brian-brazil  - but Windows has quite a large user base :) I'm happy to maintain the Windows variants. I do the same with the [NATS](https://hub.docker.com/_/nats/) image, I did the original Dockerfile and when they're prepping a release I help with the Windows testing.

**Comment by brian-brazil** [comment]
This falls under https://github.com/prometheus/promu/issues/89
