### ISSUE TITLE
Implement mechanism to use proxy header as base for http links

### ISSUE THREAD

**Issue by sylr** [prometheus/prometheus#3156]
Hi,

I'm trying to **proxy several prometheus instances** from internet through a single **nginx reverse proxy** using the **same host** but under **different base path**, e.g. :

 - prometheus.company.com/k8s1-euw-dev/
 - prometheus.company.com/k8s1-euw-prod/
 - etc ...

Here is the flow I'd like to implement:

User request:

```
GET /k8s1-euw-dev/graph HTTP/1.0
Host: prometheus.company.com
```

Proxy forwarded request :

```
GET /graph HTTP/1.0
Host: prometheus.company.com
X-Forwarded-BasePath: /k8s1-euw-dev
```

Prometheus generated html :

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>Prometheus Time Series Collection and Processing Server</title>
    <link rel="shortcut icon" href="/k8s1-euw-dev/static/img/favicon.ico?v=3afb3fffa3a29c3de865e1172fb740442e9d0133">
    <script src="/k8s1-euw-dev/static/vendor/js/jquery.min.js?v=3afb3fffa3a29c3de865e1172fb740442e9d0133"></script>
    <script src="/k8s1-euw-dev/static/vendor/bootstrap-3.3.1/js/bootstrap.min.js?v=3afb3fffa3a29c3de865e1172fb740442e9d0133"></script>
...
```

I tried using `web.external-url` & `web.route-prefix` but it rewrites the endpoints globally and I don't want to do that, I'd like to keep internal endpoints like if those confs weren't set.

Regards.

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
