### ISSUE TITLE
Support socks5 proxy in proxy_url

### ISSUE THREAD

**Issue by thomasf** [prometheus/prometheus#3164]
since go1.9 supports socks5 by default the first prometheus release compiled w. 1.9 will support this..

related issue: https://github.com/QubitProducts/exporter_exporter/issues/9

**Comment by thomasf** [comment]
prometheus 1.8 is compiled with go 1.9, right? If so this is fixed now.

**Comment by grobie** [comment]
@thomasf 1.9.1 even. Cool, can you confirm?

**Comment by thomasf** [comment]
I tested the linux/amd64 binary download and `proxy_url: "socks5://localhost:3000"` worked fine.

**Comment by grobie** [comment]
Thanks!
