### ISSUE TITLE
Prometheus: Search pattern for metrics in query box, doesnt search whole word rather it search for each letter of the word

### ISSUE THREAD

**Issue by kavyakul** [prometheus/prometheus#3187]
**What did you do?**
Search metrics in Prometheus

**What did you expect to see?**
name of the metric matching the pattern

**What did you see instead? Under which circumstances?**
the word was not matched as a whole, rather each letter was searched.

**Environment**

* System information:
Docker container running on Linux 3.10.0-514.26.2.el7.x86_64 x86_64
	
* Prometheus version:
Prometheus docker image version: v1.7.1
	
![image](https://user-images.githubusercontent.com/15211290/30540031-f8eaceda-9c92-11e7-8705-857c3d535b9c.png)

Regards,
Kavya K

**Comment by grobie** [comment]
I'd not restrict the input to whole word matches, but assuming `org_graylog2_memory` is an existing metrics name/prefix, it should surely show up at the top.

Maybe @stuartnelson3 can port his weight algorithm from alertmanager over?

**Comment by stuartnelson3** [comment]
Can try to take a look if I have time this weekend.

Relevant code is here: https://github.com/prometheus/prometheus/blob/master/web/ui/static/js/graph.js#L234-L240

Docs are here: 
https://github.com/bassjobsen/Bootstrap-3-Typeahead#options

**Comment by krajorama** [comment]
Hello from the bug scrub: closing as obsolete, refers to an older UI.
