### ISSUE TITLE
DNS discovery should not trim final dot

### ISSUE THREAD

**Issue by bboreham** [prometheus/prometheus#3196]
I wish to question [this line](https://github.com/prometheus/prometheus/blob/master/discovery/dns/dns.go#L185). It is commented:

> // Remove the final dot from rooted DNS names to make them look more usual.

but why do we care how it _looks_?  A rooted name has a different meaning from a non-rooted name.

More practically, in a typical Kubernetes installation it causes 4-5 pointless DNS lookups as the search path is traversed.

**Comment by simonpasquier** [comment]
The code has been there since the inception of the DNS SD [1] but I agree that it should be removed. Maybe @juliusv has some opinion?

[1] https://github.com/prometheus/prometheus/pull/297/files#diff-de6c481fa836cf8897a7b6d1ae60e5d5R74

**Comment by bboreham** [comment]
Can we start by agreeing on the nature of the problem, which I think is something like:

“Prometheus alters the SD results it gets from a DNS SRV lookup by removing any final dot, transforming fully-qualified names into relative names. Removing this artefact proved to inconvenience some users, so we choose to retain it”

If we agree on this, I think my suggestion would be to add another Prometheus SD type which uses the unaltered DNS response.

**Comment by juliusv** [comment]
@bboreham Fully agreed on the problem description. We probably wouldn't need a completely new SD type, but just add an option to the DNS SD?

**Comment by codesome** [comment]
During the discussions in the bug scrub we decided that it is better to provide the original value as a metadata.
