### ISSUE TITLE
Circular (repository) dependency with tsdb

### ISSUE THREAD

**Issue by TheTincho** [prometheus/prometheus#3197]
Hi,

I am starting to prepare the Debian packages for 2.0, including packaging new dependencies like `prometheus/tsdb`. While doing that I notice that it depends on `prometheus/prometheus/pkg`, thus making packaging an order of magnitude more complex.

Wouldn't it make sense to move this to common?

**Comment by fabxc** [comment]
This is just a testing dependency so we can conveniently read an input file of test data.
I'd rather not move `pkg/textparse` to the common repository (or anything anymore really). 

Do you have to include testing deps? I suppose I'd then rather just make those use the common parser, even though it's a bit more hassle to use.

**Comment by TheTincho** [comment]
I had not noticed it was only for tests. But since we run all tests during build, I need to either disable the tests or include the dep...

**Comment by Gouthamve** [comment]
Closed in https://github.com/prometheus/tsdb/pull/226
