### ISSUE TITLE
[QA]  PromQL subtraction operator  is not right?

### ISSUE THREAD

**Issue by songjiayang** [prometheus/prometheus#3204]
**What did you do?**

I use PromQL to check my service code,  I just want to known whether there is 4xx expect 400 / 419 case.

Query like screenshot:

![screen shot 2017-09-21 at 10 14 58 pm](https://user-images.githubusercontent.com/1459834/30703747-250328e4-9eb6-11e7-85d6-912c5040319a.png)

**What did you expect to see?**

- no  value smaller than 0.

**What did you see instead? Under which circumstances?**
- some value smaller than 0

**Environment**
  
* System information:
 - Ubuntu 14.04

* Prometheus version:
 -  v 1.4.1

I known there is a better query for my case , but I want to known  what's the problem for my current query.

**Comment by brian-brazil** [comment]
That looks like floating point inaccuracy.
