### ISSUE TITLE
Upgrading Prometheus 2.0 from beta2 to beta5 fails to start.

### ISSUE THREAD

**Issue by laverite** [prometheus/prometheus#3213]
**What did you do?**
Updated from v2.0.0-beta.2 -> v2.0.0-beta.5

**What did you expect to see?**
I expected prometheus beta5 to start properly.

**What did you see instead? Under which circumstances?**
beta5 failed to start complaining about missing lock file.  tried to touch a lockfile and then it complained about a missing chunks dir.  removed my touched lock file and reverted back to beta2 and things look fine again.

**Environment**
k8s 1.7.4 on bare-metal

* System information:

	Linux 4.9.13-1 x86_64

* Prometheus version:

> prometheus, version 2.0.0-beta.5 (branch: HEAD, revision: 64c7932e851f3276391fc3e216cd30f447d4924e)
  build user:       root@df40cc0bd79b
  build date:       20170921-16:23:04
  go version:       go1.8.3

>prometheus, version 2.0.0-beta.2 (branch: HEAD, revision: a52f082939a566d5269671e98be06fc6bdf61d09)
  build user:       root@41a0740ea598
  build date:       20170818-08:16:50
  go version:       go1.8.3

* Logs:
```
level=error ts=2017-09-24T23:40:02.426894698Z caller=main.go:317 msg="Opening storage failed" err="open block /prometheus/data/01BTTYEYSJJFT86B8X7286ETW9: try lock file: open /prometheus/data/01BTTYEYSJJFT86B8X7286ETW9/index: no such file or directory"

level=error ts=2017-09-24T23:38:06.766703158Z caller=main.go:317 msg="Opening storage failed" err="open block /prometheus/data/01BTTYEYSJJFT86B8X7286ETW9: open /prometheus/data/01BTTYEYSJJFT86B8X7286ETW9/chunks: no such file or directory"`
```

**Comment by grobie** [comment]
It's recommended to read the release notes before attempting an upgrade. The beta.4 release is incompatible with previous versions. https://github.com/prometheus/prometheus/releases
