### ISSUE TITLE
Histogram startTimer() fails when applying labelNames

### ISSUE THREAD

**Issue by acarlstein** [prometheus/prometheus#3225]
#How you doing? 
I apologize to bother you but I think I may have encounter a possible bug.
I tried to find any solution or explanation to the problem unsuccessfully, else I would not be bothering you.

In Java or Groovy, this works:
```
Histogram requestLatency = Histogram.build().name("xrequests_latency_seconds").help("Request latency in seconds.").register();
Histogram.Timer requestTimer = requestLatency.startTimer();
try {
	TimeUnit.SECONDS.sleep(1);
} finally {
	requestTimer.observeDuration();
}
```

While this fails:
```
Histogram requestLatency = Histogram.build().name("xrequests_latency_seconds").help("Request latency in seconds.").labelNames("Feeling").register();
Histogram.Child histogramChild = requestLatency.labels("sleepy");									
Histogram.Timer requestTimer = requestLatency.startTimer();
try {
	TimeUnit.SECONDS.sleep(1);
} finally {
	requestTimer.observeDuration();
}
```

Producing this Exception:
> java.lang.NullPointerException at io.prometheus.client.Histogram.startTimer(Histogram.java:282)

I have apply similar approach using labels with Counter and Gauge, no problems there.

**Comment by brian-brazil** [comment]
This is correct, for a labelled metric you must specify the labels.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by acarlstein** [comment]
Brian,

Since English is my second language, I may have explained myself wrong or failed to understand correctly. For that I apologize.

Histogram is failing when I am applying the labels. 
The second code example I provide ends in NullPointerException.
Is this supposed to happen?
