### ISSUE TITLE
A stable list of Prometheus versions and exporters

### ISSUE THREAD

**Issue by k-s-dean** [prometheus/prometheus#3249]
Hi, 
would it be possible to get a list of stable releases for prometheus and its various components that include exporter versions that correlate to a working Prometheus environment.

The fragmentation of exporters while providing process isolation has caused big issues in regards to getting a working Prometheus setup.

I'm jumping through different exporters finding memory leaks and inconsistent metrics and range of different issues which is frustrating me to no end, it would be nice to know what works and what doesn't.

A list of the last known working versions, of various prometheus releases and exporters is all that is required. 

This will mitigate issues when newly released versions do not work as expected allowing for a roll back to a previous version, a page on prometheus.io would be nice with a table of working versions that are currently considered stable by the community.

I'm currently trying to implement Prometheus in a production environment but due to all the various issues with prometheus and its exporters its proving very difficult.  

Looking forward to the release of 2.0, keep up the good work. 

Regards K

**Comment by brian-brazil** [comment]
This is something more for discussion on the Prometheus developers list.

Note that the vast majority of exporters are not maintained by the Prometheus team, and it has been a long long time since there was a backward incompatible change that'd affect exporters.
