### ISSUE TITLE
DropwizardExports throws NPE if gauge's value is null 

### ISSUE THREAD

**Issue by DmitryLipiev** [prometheus/prometheus#3272]
**What did you do?**

Tried to export Dropwizard metrics

**What did you expect to see?**

A list of Prometheus metrics in my browser

**What did you see instead? Under which circumstances?**

Internal server error. Some of our gauge metrics are initialized to null, when DropwizardExports comes across them it throws NPE at line 54:
LOGGER.log(Level.FINE, String.format("Invalid type for Gauge %s: %s", name, obj.getClass().getName()));  

**Environment**

Ubuntu 16.04, Java8

* System information:

Linux 4.4.0-96-generic x86_64

**Comment by brian-brazil** [comment]
This is the wrong repository, could you file this in client_java?

**Comment by DmitryLipiev** [comment]
Yes, filed https://github.com/prometheus/client_java/issues/301
