### ISSUE TITLE
recording rules show different data from raw PromQL 

### ISSUE THREAD

**Issue by i19** [prometheus/prometheus#3279]
**What did you do?**
I scrape metrics every 10 seconds, and run rules every 10 seconds too. 
The raw data is an counter, which is used to counter the request counts, aka QPS
I use grafana to graph the data points for the last 1 hour, with step as 10 seconds
below is my graph
![image](https://user-images.githubusercontent.com/5731240/31421675-3ca8985a-ae0e-11e7-9199-7f2e752793fb.png)

**What did you expect to see?**
The two lines should be the same at most times. 

**What did you see instead? Under which circumstances?**
The graph generated by recording rules had a lot square, lost some details

**Environment**

* System information:

	Linux 3.10.0-327.28.3.el7.ttm.x86_64 x86_64

* Prometheus version:

	prometheus, version 1.7.1 (branch: release-1.7, revision: dd381356a50cd1f95c7ca65e6c4d36c0bfac2f41)
  build user:       i19@Mac
  build date:       20170922-09:42:16
  go version:       go1.8.3

* Prometheus configuration file:
```
global:
  scrape_interval:     10s
  evaluation_interval: 10s
  scrape_timeout:      5s

rule_files:
  - "recording.rules"

scrape_configs:
  - job_name: ucs_raw
    metrics_path: '/raw'
    honor_labels: true
```

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
