### ISSUE TITLE
PromQL tests fail to run on a system with 4gb /tmp space

### ISSUE THREAD

**Issue by grobie** [prometheus/prometheus#3299]
**What did you do?**

    go test github.com/prometheus/prometheus/promql

**What did you expect to see?**

Tests to succeed. 

**What did you see instead? Under which circumstances?**

```
...
--- FAIL: TestEvaluations (7.40s)
        promql_test.go:33: error running test testdata/functions.test: log series: no space left on device
        promql_test.go:33: error running test testdata/histograms.test: log series: no space left on device
        promql_test.go:33: error running test testdata/legacy.test: log series: no space left on device
        promql_test.go:33: error running test testdata/operators.test: log series: no space left on device
        promql_test.go:33: error running test testdata/selectors.test: log series: no space left on device
        promql_test.go:33: error running test testdata/staleness.test: log series: no space left on device
FAIL
FAIL    github.com/prometheus/prometheus/promql 7.861s
```

**Environment**

* System information:

	Linux 4.13.6-1-ARCH x86_64

tmpfs is 4GB: `tmpfs on /tmp type tmpfs (rw,nosuid,nodev)`

* Prometheus version:

	master + updated tsdb (commit: 721050c6)

**Comment by Gouthamve** [comment]
This has happened with me too but I think I had `/tmp` with 2G (away from my machine). I think the issue is not that a test can produce 4G but the artifacts from the older tests are not being cleaned. Needs to be investigated, but I think a `defer os.RemoveAll()` can fix this.

**Comment by grobie** [comment]
I actually deleted everything in /tmp and started with 99% free space and still couldn't run the tests.
