### ISSUE TITLE
If the frequency update the prometheus.yml is faster than scrape, it will never to scrape data

### ISSUE THREAD

**Issue by shanquanqiang** [prometheus/prometheus#3315]
If the frequency update the prometheus.yml is faster than scrape, it will never to scrape data.

it will return in case <-sl.scrapeCtx.Done():

func (sl *scrapeLoop) run(interval, timeout time.Duration, errc chan<- error) {
	select {
	case <-time.After(sl.scraper.offset(interval)):
		// Continue after a scraping offset.
	case <-sl.scrapeCtx.Done():
		close(sl.stopped)
		return
	}

**Comment by fabxc** [comment]
Is this something you are interpreting from the code or something you observed in a running instance. The called `offest()` method does not make us wait for `interval` here. Instead it divides time into consistent slots and returns the time until the next one. Thus reloading frequently does not always reset the wait timer to `interval` and should not result in scrapes never happening.

Note that you should generally not have a need to reload Prometheus frequently regardless.

**Comment by brian-brazil** [comment]
If this was a problem, it should no longer be the case with the latest versions.
