### ISSUE TITLE
drop_common_labels reported as unknown function

### ISSUE THREAD

**Issue by smarterclayton** [prometheus/prometheus#3320]
Got an error on query `drop_common_labels(openshift_sdn_pod_setup_errors) > 0` on v2.0.0-rc.1.  I had just upgraded, but I did force refresh the page (in case something was cached).

```
Error executing query: parse error at char 19: unknown function with name "drop_common_labels"
```

**Comment by grobie** [comment]
drop_common_labels has been removed and is not longer available, see #3060.

@brian-brazil We need a better answer for this then "it's gone".

**Comment by smarterclayton** [comment]
Ok, expected the docs to be updated.  Also use it extremely often for very dense labels generated by kubernetes clusters (where there are several layers of labels being added which are mostly the same)

**Comment by brian-brazil** [comment]
You should be using by/without in your aggregations to select exactly which labels you want. drop_common_labels and keep_common are unsafe, as they don't always return the same labels.

**Comment by smarterclayton** [comment]
It's more useful in the cases where I'm zeroing in on the labels I do want, by removing all the ones that don't change and thus cannot be useful in further refining.  Not disagreeing it is redundant to other more focused tools, just identifying that it's a regular part of iterative flow of working through large metric sets to refine what I might need to search on, especially in the absence of knowing what the important labels are in an ad-hoc search.

**Comment by brian-brazil** [comment]
That's something that's best done in an exploration tool, it doesn't belong in the core language.

If you have lots of labels that are unchanging, it's possible that you have redundant target labels that should be trimmed.

**Comment by brian-brazil** [comment]
We already have bugs tracking 2.0 doc updates, there's nothing to be done here on the Prometheus side.
