### ISSUE TITLE
prometheus telemetry metrics missing

### ISSUE THREAD

**Issue by jan--f** [prometheus/prometheus#3323]
It seems like prometheus 2 itself does no longer export local_storage metrics. These were quite useful. If this change has been anouced somewhere I must have missed this. Changelog, mailing list or github issues search didn't turn up anything for me. 

**What did you do?**
Update prometheus from  version 1.5.2 to version 2.0.0-rc.0

**What did you expect to see?**
Getting prometheus_local_storage_* metrics when scraping prometheus with ```curl localhost:9090/metrics``` on the prometheus host.

**What did you see instead? Under which circumstances?**
No prometheus_local_storage_* metrics.

**Environment**

* System information:

	Linux 4.4.82-6.9-default x86_64

* Prometheus version:

	prometheus, version 2.0.0-rc.0 (branch: , revision: )
        build user:       abuild@sheep11
        build date:       20171017-12:38:42
        go version:       go1.8.3

* Prometheus configuration file:
```
global:

rule_files: []

scrape_configs:

```

**Comment by jan--f** [comment]
Just learned about the rename of the ```prometheus_local_storage_``` metrics to ```tsdb_*```

**Comment by fabxc** [comment]
We will move those to `prometheus_tsdb_*` for the next release to make them discoverable more easily.
