### ISSUE TITLE
rule error

### ISSUE THREAD

**Issue by timchenxiaoyu** [prometheus/prometheus#3342]
caller=manager.go:485 component="rule manager" msg="loading groups failed" err="yaml: unmarshal errors:\n  line 1: cannot unmarshal !!str `ALERT c...` into rulefmt.RuleGroups

```
kubectl get configmap prometheus-rules  -oyaml -n kube-system


apiVersion: v1
data:
  admin.rule: "ALERT container_cpu_usage_seconds_total_gt_1000_6f520219a26dc3a4cd66d439e9dced83\n\tIF
    (ceil(avg(rate(container_cpu_usage_seconds_total{id=\"/\",instance=\"test-slave-111\",job=\"kubernetes-nodes\",kubernetes_io_hostname=\"test-slave-111\"}[5m]))
    * 100 * 100) / 100) > 10\n\tLABELS {tenxClusterID=\"CID-ca4135da3326\", tenxNamespace=\"admin\",
    tenxStrategyID=\"STRAID-ggDYwFzTYWpS\", tenxStrategyName=\"ttt\", tenxTargetName=\"test-slave-111\",
    tenxTargetType=\"node\"}\n\tANNOTATIONS {condition=\"CPU利用率 > 10%\", createTime=\"2017-10-24T16:56:36+08:00\",
    currentValue=\"CPU利用率 {{ $value }}%\", tenxMetricType=\"cpu/usage_rate\", tokenMD5=\"9f834d0df08163e97b1ebb8423003292\"}\n"
kind: ConfigMap
metadata:
  creationTimestamp: 2017-10-24T08:56:22Z
  name: prometheus-rules
  namespace: kube-system
  resourceVersion: "54328149"
  selfLink: /api/v1/namespaces/kube-system/configmaps/prometheus-rules
  uid: 3547006c-b899-11e7-89e0-5254eec04736
```
prometheus version is 2.0

**Comment by Gouthamve** [comment]
Hi, the rule format changed from 1.x. See: https://prometheus.io/blog/2017/06/21/prometheus-20-alpha3-new-rule-format/ 

You can use promtool to automatically convert the rules: `promtool update rules <filenames>`

**Comment by timchenxiaoyu** [comment]
promtool check rules /tmp/admin.rule 
Checking /tmp/admin.rule
  FAILED:
yaml: unmarshal errors:
  line 1: cannot unmarshal !!str `instanc...` into rulefmt.RuleGroups

/bin $ cat /tmp/admin.rule 
instance:network_bytes:rate1m = sum by(instance) (rate(network_bytes_total[1m]))

ALERT HighNetworkTraffic
  IF instance:network_bytes:rate1m > 10e6

**Comment by timchenxiaoyu** [comment]
line 1: cannot unmarshal !!str `ALERT c...` into rulefmt.RuleGroups
