### ISSUE TITLE
Some rate calculations on rc1 are incorrect

### ISSUE THREAD

**Issue by smarterclayton** [prometheus/prometheus#3345]
In 2.0.0-rc1 some queries for rate over counters seem to be wildly overstated / incorrectly calculated.  This is very large kubernetes cluster that is receiving ~0.1 requests per second on average for a specific request error code, but the rate calculation is reporting 28 req/s.

Here's the samples from the three masters for a particular metric `apiserver_request_count` sampled from the server directly for one server:

```
apiserver_request_count{client="openshift/v1.7.0+80709908fd (linux/amd64) kubernetes/b0608fa",code="404",contentType="application/vnd.kubernetes.protobuf",resource="secrets",scope="resource",subresource="",verb="GET"} 7584

... wait 5-10s

apiserver_request_count{client="openshift/v1.7.0+80709908fd (linux/amd64) kubernetes/b0608fa",code="404",contentType="application/vnd.kubernetes.protobuf",resource="secrets",scope="resource",subresource="",verb="GET"} 7584

... wait 5-10s

apiserver_request_count{client="openshift/v1.7.0+80709908fd (linux/amd64) kubernetes/b0608fa",code="404",contentType="application/vnd.kubernetes.protobuf",resource="secrets",scope="resource",subresource="",verb="GET"} 7587

```

Prometheus console reports the correct instantaneous value:

```
Query:
apiserver_request_count{client="openshift/v1.7.0+80709908fd (linux/amd64) kubernetes/b0608fa",code="404",contentType="application/vnd.kubernetes.protobuf",resource="secrets",scope="resource",subresource="",verb="GET"}

Result:
{client="openshift/v1.7.0+80709908fd (linux/amd64) kubernetes/b0608fa",code="404",contentType="application/vnd.kubernetes.protobuf",instance="172.31.21.249:443",job="kubernetes-apiservers",resource="secrets",scope="resource",subresource="",verb="GET"} | 7587
```

![graph](https://www.dropbox.com/s/hej7mip4qnkyfpl/Screenshot%202017-10-24%2011.52.14.png?raw=1)

Over the last six hours the total has only increased by about 3k which should be a rate of about 0.15 sec.

But the query for rate is reporting a 5m rate of 28/sec which is impossible:

```
Query:
rate(apiserver_request_count{client="openshift/v1.7.0+80709908fd (linux/amd64) kubernetes/b0608fa",code="404",contentType="application/vnd.kubernetes.protobuf",instance="172.31.21.249:443",job="kubernetes-apiservers",resource="secrets",scope="resource",subresource="",verb="GET"}[5m])

Result:
{client="openshift/v1.7.0+80709908fd (linux/amd64) kubernetes/b0608fa",code="404",contentType="application/vnd.kubernetes.protobuf",instance="172.31.21.249:443",job="kubernetes-apiservers",resource="secrets",scope="resource",subresource="",verb="GET"} | 27.712352499999998
```

![Graph](https://www.dropbox.com/s/klc9ptmgyspiz1t/Screenshot%202017-10-24%2011.51.26.png?raw=1)

**Comment by smarterclayton** [comment]
The prometheus instance has been running for about 20 hours since it was last cleared and reset due to #3283 and #3316

**Comment by smarterclayton** [comment]
Other rates on other series are also broken by two or three orders of magnitude

**Comment by fabxc** [comment]
Thanks, does this sound like https://github.com/prometheus/prometheus/issues/3337?

**Comment by smarterclayton** [comment]
Yes, will check the samples reported in the morning

**Comment by smarterclayton** [comment]
Looks like this was fixed with rc2:

![graph](https://www.dropbox.com/s/35hnde02ntp3d2s/Screenshot%202017-10-25%2016.18.08.png?raw=1)

**Comment by smarterclayton** [comment]
There's a tiny tail of correct rate on the right edge.

**Comment by fabxc** [comment]
Awesome, thanks for the quick response!

**Comment by paultiplady** [comment]
@fabxc any idea when this regression was introduced? I seem to be hitting this on 1.7.0, is that possible? Thanks!

**Comment by fabxc** [comment]
It was caused purely by an issue in the new storage issue which has since
then be fixed. If you seeing anything like this in 1.x code, please open a
separate issue since it's most definitely another problem.

**Comment by paultiplady** [comment]
Thanks for the quick response -- I'll do some more digging on my side and try upgrading to see if that clears things.
