### ISSUE TITLE
Issue configuring service end points for prometheus.yml

### ISSUE THREAD

**Issue by kaarthikeyan1987** [prometheus/prometheus#3371]
I am having hard time figuring out on how to structure code for service end points as I completely new to coding.
My goal is to get pod and container metrics from my kubernetes-cluster.
I have deployed kube-state-metrics agent post which I am trying to configure the service endpoints in the Prometheus configuration file and I am getting error. Please need you guys help. Thank you so much in advance.

I have attached my configuration file.
[prometheus.txt](https://github.com/prometheus/prometheus/files/1426910/prometheus.txt)

Also find the error when executing the yaml file.

 prometheus.service - Prometheus
   Loaded: loaded (/etc/systemd/system/prometheus.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2017-10-30 10:22:37 UTC; 27min ago
  Process: 26346 ExecStart=/usr/local/bin/prometheus -config.file /etc/prometheus/prometheus.yml -storage.local.path /var/lib/prometheus/ (code=exited, status=1/FAILURE
 Main PID: 26346 (code=exited, status=1/FAILURE)

Oct 30 10:22:37 ip-172-31-21-51 systemd[1]: Stopped Prometheus.
Oct 30 10:22:37 ip-172-31-21-51 systemd[1]: Started Prometheus.
Oct 30 10:22:37 ip-172-31-21-51 prometheus[26346]: time="2017-10-30T10:22:37Z" level=info msg="Starting prometheus (version=1.7.1, branch=master, revision=3afb3fffa3a29
Oct 30 10:22:37 ip-172-31-21-51 prometheus[26346]: time="2017-10-30T10:22:37Z" level=info msg="Build context (go=go1.8.3, user=root@0aa1b7fc430d, date=20170612-11:44:05
Oct 30 10:22:37 ip-172-31-21-51 prometheus[26346]: time="2017-10-30T10:22:37Z" level=info msg="Host details (Linux 4.4.0-1038-aws #47-Ubuntu SMP Thu Sep 28 20:05:35 UTC
Oct 30 10:22:37 ip-172-31-21-51 prometheus[26346]: time="2017-10-30T10:22:37Z" level=info msg="Loading configuration file /etc/prometheus/prometheus.yml" source="main.g
Oct 30 10:22:37 ip-172-31-21-51 systemd[1]: prometheus.service: Main process exited, code=exited, status=1/FAILURE
Oct 30 10:22:37 ip-172-31-21-51 systemd[1]: prometheus.service: Unit entered failed state.
Oct 30 10:22:37 ip-172-31-21-51 systemd[1]: prometheus.service: Failed with result 'exit-code'.

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
