### ISSUE TITLE
align columns in targets view

### ISSUE THREAD

**Issue by caarlos0** [prometheus/prometheus#3373]
it's a minor, but the tables are not aligned (each column has a different width in each table)... it would look better if they all have the same size.

Image:

![image](https://user-images.githubusercontent.com/245435/32173637-d300c8e2-bd66-11e7-8735-a503cc2d83a0.png)

**Comment by applegrain** [comment]
I'll take a look at this, shouldn't be too much work to fix.

**Comment by Bplotka** [comment]
Are we sure this is really better than what it was? I would rather have readable labels than aligned columns ):

Labels are wrapped terribly. The same is when label value/name is long enough to exceed fixed width.

![image](https://user-images.githubusercontent.com/6950331/37457405-d31f9040-2839-11e8-8bea-51a1a6d6b343.png)

**Comment by juliusv** [comment]
@Bplotka I tend to agree with you. Also a job that has errors needs vastly more space in the errors column than a job that doesn't have an error, and it would be nice to be able to use that unused space better in the error-free jobs (e.g. to have more space for labels and such).

**Comment by juliusv** [comment]
I see that ironically I was the person merging this change, but I didn't see that label wrapping problem back then. It'd be nice to at least improve that.

**Comment by Bplotka** [comment]
Yea, could see that there was no test against these cases (e.g in given animation in PR)

**Comment by Bplotka** [comment]
Moved to new issue: https://github.com/prometheus/prometheus/issues/3972
