### ISSUE TITLE
Reload resets alert state

### ISSUE THREAD

**Issue by brian-brazil** [prometheus/prometheus#3376]
I've confirmed @discordianfish's report that a config reload will reset alert state, meaning the FOR clauses start from scratch again.

**Comment by discordianfish** [comment]
Oh sorry, I thought I've opened an issue for that. Thanks for confirming.

**Comment by krasi-georgiev** [comment]
I haven't worked on the alerting but this one sound simple so will have a look now.

**Comment by Gouthamve** [comment]
Closed via #3382
