### ISSUE TITLE
Change --log.level=info to --log.level=warn in Dockerfile

### ISSUE THREAD

**Issue by dsvensson** [prometheus/prometheus#3386]
**What did you do?**

Started prometheus under docker-compose.

**What did you expect to see?**

Nothing.

**What did you see instead? Under which circumstances?**

Lots of log INFO's that I want to hide.

**Environment**

prom/prometheus docker container.

* System information:

	docker

* Prometheus version:

	2.0.0-rc2

* Logs:
```
prometheus_1  | level=info ts=2017-11-01T09:39:34.401732653Z caller=main.go:215 msg="Starting Prometheus" version="(version=2.0.0-rc.2, branch=master, revision=3701a827cf5da595bd2366dad6e1b3c979a1009c)"
prometheus_1  | level=info ts=2017-11-01T09:39:34.40179053Z caller=main.go:216 build_context="(go=go1.9.2, user=root@78a874392a56, date=20171031-19:21:13)"
prometheus_1  | level=info ts=2017-11-01T09:39:34.401811123Z caller=main.go:217 host_details="(Linux 4.9.49-moby #1 SMP Wed Sep 27 23:17:17 UTC 2017 x86_64 47b7422941a8 (none))"
prometheus_1  | level=info ts=2017-11-01T09:39:34.404592868Z caller=web.go:380 component=web msg="Start listening for connections" address=0.0.0.0:9090
prometheus_1  | level=info ts=2017-11-01T09:39:34.404612563Z caller=targetmanager.go:69 component="target manager" msg="Starting target manager..."
prometheus_1  | level=info ts=2017-11-01T09:39:34.404599197Z caller=main.go:314 msg="Starting TSDB"
prometheus_1  | level=info ts=2017-11-01T09:39:34.613745929Z caller=main.go:326 msg="TSDB started"
prometheus_1  | level=info ts=2017-11-01T09:39:34.613846488Z caller=main.go:394 msg="Loading configuration file" filename=/etc/prometheus/prometheus.yml
prometheus_1  | level=info ts=2017-11-01T09:39:34.617933193Z caller=main.go:371 msg="Server is ready to receive requests."
```

Final attempt. As there are good arguments for not controlling log level via configuration (#3384), and opinionated reasons for not giving docker-compose control over the command line arguments in the upstream prom/prometheus container (#3385), then perhaps the Dockerfile log level can be changed to `warn` under the flag of [_Basics of the Unix Philosophy_](http://www.faqs.org/docs/artu/ch01s06.html):

> 11. Rule of Silence: When a program has nothing surprising to say, it should say nothing.

**Comment by brian-brazil** [comment]
It's good for applications to be verbose at startup, as it's a great aid with debugging issues then. The startup information is all quite important for us when dealing with user support requests and thus info should remain the default.

The logs here are extremely light as startup logs go, though there's some work in progress to expand them a bit.

**Comment by dsvensson** [comment]
But don't they fall under 'surprising'? If the intention is that things should start, what is the value of having the lines say that everything went as intended? I expect an error would be printed otherwise?

Having Prometheus version logged is ofc interesting, and it might also be valiable to list host details. But it does seem fairly verbose.

**Comment by brian-brazil** [comment]
> If the intention is that things should start, what is the value of having the lines say that everything went as intended?

So we can tell where things got stuck.

**Comment by dsvensson** [comment]
So the main reason for these INFO logs being the default everywhere is to be able to debug Prometheus when it hangs, in situations where it does not get stuck if restarting with `--log.level=debug`? Not saying it's bad, just want to understand the reason.

**Comment by brian-brazil** [comment]
Info is generally the default for logging. These log lines are info so we can debug hangs, as getting users to change log levels (especially for rarely occurring issues) can be difficult.

**Comment by dsvensson** [comment]
Yeah, I know, changing log levels does lack some usability ;)
