### ISSUE TITLE
Grafana dashboard for 2.0

### ISSUE THREAD

**Issue by Gouthamve** [prometheus/prometheus#3388]
We would need to replace the default dashboard in Grafana with one that supports 2.0. I personally remember using the dashboard to figure out operational issues long back when I first deployed Prometheus. 

I plan to hash out one soon so that we have a base to iterate on. Also we need to figure out how to (if we need to?) support both 1.x and 2.x dashboards in Grafana.

Not sure this is the right place to track this, but an issue somewhere would be good.

**Comment by brancz** [comment]
Does anyone of us actually support the one for 1.x? If not I don't think we need to worry about it, and if so, then it's only something to worry about for the next half a year or so and then we can drop support.

Regarding a 2.0 one, I think it's very useful to have one, but would encourage to start off from what's still applicable from the 1.x one and drop the things that are not, and that gradually add what we discover to be actually useful metrics to watch over time.

**Comment by brian-brazil** [comment]
> Does anyone of us actually support the one for 1.x? 

As far as I'm aware, this is something the Grafana people created on their own. @bergquist

**Comment by bergquist** [comment]
Yea that's something we built our self and bundle within Grafana. But we could certainly use some help. Moving the discussion to https://github.com/grafana/grafana/issues/9759
