### ISSUE TITLE
Export LastScrape as metric

### ISSUE THREAD

**Issue by jan--f** [prometheus/prometheus#3397]
LastScrape is accessible through prometheus' http api. It would be useful if prometheus would expose this as a telemtry metric as well.

**Comment by brian-brazil** [comment]
This is a metric about a target, and thus doesn't belong on /metrics as per-target information is not about Prometheus's performance as a whole. Try using the `timestamp` function on `up`.

**Comment by jan--f** [comment]
Ahh thx that is very helpful.
