### ISSUE TITLE
prometheus expression browser: problem with float rounding of the scale tick labels

### ISSUE THREAD

**Issue by marcindulak** [prometheus/prometheus#3411]
**What did you do?**

Visualizing simple queries in the expression browser

**What did you expect to see?**

The scale tick labels use reasonably rounded floats

**What did you see instead? Under which circumstances?**

The scale ticks labels include too many digits. This changes depending on the selected time range.

![screenshot from 2017-11-04 19-13-06](https://user-images.githubusercontent.com/3178318/32408382-235b1020-c197-11e7-81cd-ce466ffdba27.png)

**Environment**

* System information:

$ cat /etc/redhat-release 
CentOS Linux release 7.4.1708 (Core)

$ uname -srm
Linux 3.10.0-693.5.2.el7.x86_64 x86_64

* Prometheus version:

$ prometheus --version
prometheus, version 1.8.1 (branch: HEAD, revision: 3a7c51ab70fc7615cd318204d3aa7c078b7c5b20)
  build user:       root@ab78fb101775
  build date:       20171023-15:50:57
  go version:       go1.9.1
	
Installed from https://github.com/lest/prometheus-rpm

google-chrome Version 62.0.3202.75 (Official Build) (64-bit)

**Comment by simonpasquier** [comment]
Closing in favor of #3595
