### ISSUE TITLE
Refactor the API to use go-kit

### ISSUE THREAD

**Issue by krasi-georgiev** [prometheus/prometheus#3416]
Started looking at the api code and I think it can be improved by using the go-kit package.
https://github.com/go-kit/kit
https://youtu.be/JXEjAwNWays?t=1451
https://www.youtube.com/watch?v=NX0sHF8ZZgw

**Comment by krasi-georgiev** [comment]
@tomwilkie what do you have against go-kit? 
I haven't used it, but it looks like a good fit.

**Comment by gauravsitlani** [comment]
@krasi-georgiev Can I take the initiative to help out .   
This is the code right ?  
https://github.com/prometheus/prometheus/blob/master/web/api/v2/api.go

**Comment by krasi-georgiev** [comment]
that would be great!
I started a topic in the groups, but hasn't been discusses yet so a bit more input from the other maintainers.
https://groups.google.com/forum/#!topic/prometheus-developers/IebVSsE2_Gk

I am leaning towards gokit + swagger spec generation via annotations.
https://goswagger.io/generate/spec.html

**Comment by gauravsitlani** [comment]
Have you looked at Gilmour : https://www.youtube.com/watch?v=rDQTBpIWa7M
https://github.com/gilmour-libs/gilmour

**Comment by gauravsitlani** [comment]
@krasi-georgiev I'll go through the api code and check out go-kit + swagger and follow the thread.

**Comment by krasi-georgiev** [comment]
Thanks.  
post your findings or questions in the Google groups thread.

**Comment by Bo0km4n** [comment]
Hi I’m Katsuya, 
I’m thinking to participate GSoC’18,  and I’d like to work on Prometheus.
I found this issue Prometheus’s ideas page,
It’s sounds very interesting.
Could you tell me more detail of this issue?
If there is anything I can do, I want to help.

**Comment by krasi-georgiev** [comment]
I did a quick research and started a dicsussion in the Prometheus mailing list.
https://groups.google.com/forum/#!topic/prometheus-developers/IebVSsE2_Gk

also started a doc to take some notes
https://docs.google.com/spreadsheets/d/1juaYH-unAYIp1-rlmYRNojxxwRswK4w7lDPHtUQj398/edit#gid=0

overall I am leaning towards go-kit with some code annotations to auto generate the code based on the code annotations/comments next to each endpoint.

if you have an opinion can post it in the mailing list to get some more comment and can also ping me on irc #prometheus-dev if you have any questions.

**Comment by krasi-georgiev** [comment]
@Bo0km4n should hang around a bit longer in the IRC. Saw your question, but you were not in the irc anymore. if you put @krasi in front of the question I will get a notification and better chance to get a quick reply.

**Comment by Bo0km4n** [comment]
Oh, I’m sorry,,, I’m the first time to use IRC.
Even if you skipped a private chat with the “/privmsg command”, I got an error.

If you do not bother you, I’d like to contact you by email or github issue.

**Comment by krasi-georgiev** [comment]
it might be a bit difficult of you have more than one question , but lets try , fire away.

**Comment by Bo0km4n** [comment]
Fmm... Ok, I think I will try a conversation on irc.

Could you tell me about private chat command?

I tried command “/privmsg krasi hello, nice to meet you”
But actually, I couldn’t send message to you.
What command when you send private message to other user?
Sorry to hear persistently.

**Comment by krasi-georgiev** [comment]
send me a message in the main room

**Comment by Bo0km4n** [comment]
Sorry I don't know how to enter main room.
Do not you just enter the #prometheus-dev channel?

2018-03-15 5:02 GMT+09:00 Krasi Georgiev <notifications@github.com>:

**Comment by brian-brazil** [comment]
What's the actual problem we're trying to solve here?

**Comment by krasi-georgiev** [comment]
AFAIR the code is not well organised  , v1,v2, admin are all separate and difficult to follow. 
versioning is difficult and non DRY , API documentation is all manual so easy to drift.

**Comment by brian-brazil** [comment]
I don't see how using a framework would resolve any of that, it'd just add an extra layer of abstraction and complicate the code. That versioning was never properly designed wouldn't be fixed either, and I personally think we should be considering deleting v2 rather than fixing it.

**Comment by krasi-georgiev** [comment]
can't be sure on a 100% , but I would like at least to try and refactor it. 
If it ends up the same or more complicated than we don't have to merge it.

I am against using frameworks as well so will try to avoid it at all cost unless it brings some real time and maintaining savings.

**Comment by brian-brazil** [comment]
As is stands there's very little maintenance required on the APIs, and adding new endpoints isn't that hard.

**Comment by krasi-georgiev** [comment]
It was long ago so will check again and will close the proposal if that is the case.

**Comment by krasi-georgiev** [comment]
I had a look at the code again as part of troubleshooting a race condition and must say it is extremely unorganised , difficult to  follow and difficult to troubleshoot.
It uses 2 different routers with some rules defined in the New function and others in the Run function. 
Overall adding more things to the api . versioning etc. would make it really difficult to maintain in its current state.

Now I am even more convinced than before that this can get a lot better.

**Comment by krasi-georgiev** [comment]
the last dev summit it was decided to try open api for the alertmanager and it all good will consider it for Prometheus as well.
