### ISSUE TITLE
Flaky test in github.com/prometheus/prometheus/discovery/file.go

### ISSUE THREAD

**Issue by elifkus** [prometheus/prometheus#3419]
I ran make test and the tests for file service discovery failed. But sometimes they don't. 

--- FAIL: TestFileSD (0.03s)
	file_test.go:105: Unexpected target groups [], we expected a failure here.

I looked into it and found out what makes the tests fail. But I'm not able to fix it (as I'm new to the codebase and to the language) so I'm writing here in the hope someone who knows better might help out. I'll continue in the comments. 

System information: MacOs 10.13.1 
                                  Darwin 17.2.0 x86_64
Prometheus version: 
prometheus, version 2.0.0-rc.3 (branch: master, revision: 09be10a553e8f63f86938c682533013ed8f899dd)
  build user:       mine@my-MacBook.local
  build date:       20171107-08:54:35
  go version:       go1.8

**Comment by elifkus** [comment]
The test that fails is  testFileSD(t, "invalid_nil", ".yml", false)

I found out that the test fails when the content of fixtures/_test_invalid_nil.yml in is empty instead of 

> - targets: ['localhost:9090', 'example.org:443']
>   labels:
>     foo: bar
> 
> - null

Sometimes the content is read before the content is written over to the file (which is done in the test testFileSD). 

I guess 

> go fsd.Run(ctx, ch) 

at line 53 starts the read before line 74 writes the file content to fixtures/_test_invalid_nil.yml

> _, err = io.Copy(newf, f)

**Comment by grobie** [comment]
Thanks for the report @elifkus! I guess we need some goroutine synchronization here. @krasi-georgiev you were looking into our sd tests already, right?

**Comment by krasi-georgiev** [comment]
@grobie  no I haven't, but It happens almost every time on my local tests and quite annoyed by these so will get it fixed.

@elifkus thanks for the pointers.
