### ISSUE TITLE
curl -XPOST http://127.0.0.1:9090/api/v2/admin/tsdb/snapshot {"error":"grpc: the connection is unavailable","code":14}

### ISSUE THREAD

**Issue by kubebc** [prometheus/prometheus#3449]
Hi, Team,

Version: prometheus-2.0.0.linux-amd64.tar.gz
$ ./prometheus --config.file=prometheus.yml --web.enable-lifecycle --web.enable-admin-api
$ curl -XPOST http://127.0.0.1:9090/api/v2/admin/tsdb/snapshot
{"error":"grpc: the connection is unavailable","code":14}

Any idea about this? Thanks!

**Comment by Gouthamve** [comment]
I just tried it on a clean run and it worked for me. Can you give us more
information regarding your OS/Setup?

**Comment by kubebc** [comment]
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 17.04
Release:	17.04
Codename:	zesty

$ uname -a
Linux VirtualBox 4.10.0-35-generic #39-Ubuntu SMP Wed Sep 13 07:46:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by brian-brazil** [comment]
Can you tell us more about your network setup and anything that's unusual?

For now I'm going to presume that it's a problem on your end, but let is know if you have more information.
