### ISSUE TITLE
Show gaps in graph when data has long gaps

### ISSUE THREAD

**Issue by juliusv** [prometheus/prometheus#345]
See:

https://github.com/shutterstock/rickshaw/issues/121
https://github.com/shutterstock/rickshaw/issues/155

http://code.shutterstock.com/rickshaw/examples/gaps.html
http://code.shutterstock.com/rickshaw/examples/inconsistent.html

**Comment by grobie** [comment]
Solved in the meantime.

**Comment by fabxc** [comment]
This is especially confusing when zero-filling time series at the beginning up the the timestamp of the first displayed time series. It suggests false existence of false data, which only becomes apparent if calculations over this non-existent data fails.

**Comment by jeromegn** [comment]
Since this doesn't seem to be resolving itself, my workaround is to manually rebuild the series data client-side.

For this, you have to know the `start`, `end` and `step` for the query.

```javascript
function buildSeriesData(data, from, to, step){
  let seriesData = [];
  for (let i = from; i < to; i += step) {
    let y = data.find((d)=> d[0] == i)
    seriesData.push([i, y && y[1] || null])
  }
  return seriesData;
}
```

That returns an array of the appropriate size, with the gaps filled as `[<timestamp>, null]`
