### ISSUE TITLE
Prometheus autostart after installing

### ISSUE THREAD

**Issue by neuroxdnb** [prometheus/prometheus#3463]
Usual behavior of packages containing services upon installation is to register the service being installed and start it.  However this is not true for prometheus packages.
RPM POSTIN spec does not contain ```systemctl enable prometheus.service```.

**What did you do?**
yum install prometheus
**What did you expect to see?**
systemctl enable prometheus.service
**What did you see instead? Under which circumstances?**
none
**Environment**
CentOS Linux release 7.4.1708 (Core) 
* System information:
Linux 3.10.0-514.16.1.el7.x86_64 x86_64
* Prometheus version:
prometheus, version 1.8.2 (branch: HEAD, revision: 5211b96d4d1291c3dd1a569f711d3b301b635ecb)
  build user:       root@1412e937e4ad
  build date:       20171104-16:09:14
  go version:       go1.9.2
* Alertmanager version:
alertmanager, version 0.10.0 (branch: HEAD, revision: 133c888ef3644b47a52acbaeffb09f4cc637df1b)
  build user:       root@01302b7cd08a
  build date:       20171109-15:34:53
  go version:       go1.9.2
* Prometheus configuration file:
not applicable
* Alertmanager configuration file:
not applicable
* Logs:
not applicable

**Comment by grobie** [comment]
We don't provide yum packages. Please take this to the package provider
repository.

**Comment by neuroxdnb** [comment]
Thank you!
