### ISSUE TITLE
Dynamic relabelling only sets one last target_label

### ISSUE THREAD

**Issue by bookwar** [prometheus/prometheus#3472]
**What did you do?**
Following example in https://github.com/prometheus/prometheus/pull/2078 I have a Nomad service which is scraped from Consul with 
`__meta_consul_tags = ,label-env-dev,label-project-myproject,label-team-myteam,`

Then the following relabeling rules are applied:
```
      - source_labels: [__meta_consul_tags]
        regex: '.*,label-([[:alnum:]]+)-([^,]+),.*'
        replacement: '${2}'
        target_label: '${1}'
```

**What did you expect to see?**

Labels `env=dev`, `project=myproject` and `team=myteam`

**What did you see instead?**

Only the last label is applied: `team=myteam`

**Environment**

* Prometheus version:
  latest image from docker hub docker.io/prom/prometheus
  `version="(version=2.0.0, branch=HEAD, revision=0a74f98628a0463dddc90528220c94de5032d1a0)"`

**Comment by brian-brazil** [comment]
That's how regular expression work. See https://www.robustperception.io/extracting-full-labels-from-consul-tags/

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by bookwar** [comment]
I misread the #2078 then, and expected different result from it.

Thanks for the link, it works indeed.

```
- source_labels: [__meta_consul_tags]
        regex: ',(?:[^,]+,){0}label-([[:alnum:]]+)-([^,]+),.*'
        replacement: '${2}'
        target_label: '${1}'
      - source_labels: [__meta_consul_tags]
        regex: ',(?:[^,]+,){1}label-([[:alnum:]]+)-([^,]+),.*'
        replacement: '${2}'
        target_label: '${1}'
      - source_labels: [__meta_consul_tags]
        regex: ',(?:[^,]+,){2}label-([[:alnum:]]+)-([^,]+),.*'
        replacement: '${2}'
        target_label: '${1}'
      - source_labels: [__meta_consul_tags]
        regex: ',(?:^,]+,){3}-(label-[[:alnum:]]+)-([^,]+),.*'
        replacement: '${2}'
        target_label: '${1}'
```
