### ISSUE TITLE
Show flag default for boolean flags in help output

### ISSUE THREAD

**Issue by juliusv** [prometheus/prometheus#3476]
`./prometheus -h` shows boolean flags like this:

```
      --web.enable-lifecycle     Enable shutdown and reload via HTTP request.
      --web.enable-admin-api     Enables API endpoints for admin control actions.
```

Without looking at the code, it wasn't clear to me what the default value for those was. It should be clear from the help output.

**Comment by supra08** [comment]
@juliusv is this issue still open? I would like to work on this.

**Comment by juliusv** [comment]
Yes, it's still open. It seems like the flag library we use doesn't have a built-in way of showing this, so maybe the best we can do is add the default to the help text of the boolean flags.

**Comment by brian-brazil** [comment]
Or we could improve the upstream library.

**Comment by juliusv** [comment]
Yep, or that. There's already a slightly related issue for that library for boolean flags: https://github.com/alecthomas/kingpin/issues/243

**Comment by supra08** [comment]
In that case, I guess the faster option would be to fix it by using the default to the help text. Or else we would have to wait for the patch to be merged first. @juliusv what do you say?

**Comment by juliusv** [comment]
@supra08 Yeah, obviously fixing the upstream library would be the best solution, but until someone wants to do that, just extending our help texts would already help.

**Comment by geekodour** [comment]
From the documentation,
> Boolean values are uniquely managed by Kingpin. Each boolean flag will have a negative complement: --<name> and --no-<name>.

https://github.com/alecthomas/kingpin/blob/master/README.md#boolean-values

so `--web.enable-lifecycle` has implicit `--no-web.enable-lifecycle`, so the command line parser makes `--name` equivalent to `--name=true`. The default value is the zero value for a type. Therefore it'll always be `false` by default.

So the name of the boolean flag should be self explanatory on whether to enable of disable the feature which I think in Prometheus's case is. Except `storage.tsdb.no-lockfile` and `storage.tsdb.wal-compression` which probably can be `storage.tsdb.no-create-lockfile` and `storage.tsdb.enable-wal-compression` respectively. But I think that'll be a breaking change?

I made a still made a PR to kingpin: https://github.com/alecthomas/kingpin/pull/317 but I think it's no longer actively maintained.

**Comment by beorn7** [comment]
Hello from the bug scrub.

We discussed this, and for better or worse, we are using the usual Kingpin semantics here. All those boolean flags are "by default false", and the naive user doesn't even have to know they are boolean flags. They just use the flag to activate the documented feature. Maybe the `[no-]` part is confusing then, but that's the way Kingpin shows it.

As this issue hasn't seen any updates in 4y, we are closing it now. If anyone is ever confused about a boolean flag, please update the doc string to clarify.
