### ISSUE TITLE
Use of outdated bootstrap library

### ISSUE THREAD

**Issue by swestcott** [prometheus/prometheus#3494]
During a routine security test it was found that Prometheus is using Bootstrap 3.3.1 which has a known XSS issue (https://github.com/twbs/bootstrap/issues/20184). Further to this Bootstrap 3 is [no longer maintained](https://github.com/twbs/bootstrap/issues/20184#issuecomment-244818062).

**Environment**

* Prometheus version: 1.7.2, but confirmed in `master` also (https://github.com/prometheus/prometheus/blob/master/web/ui/templates/_base.html#L8)

**Comment by brian-brazil** [comment]
From a look at our code, we're not using this anywhere. All the places where we've untrusted data we're handling with Go templating's escaping.

**Comment by simonpasquier** [comment]
Closed by https://github.com/prometheus/prometheus/pull/5226
