### ISSUE TITLE
rule http api

### ISSUE THREAD

**Issue by Jaware** [prometheus/prometheus#3501]
it seems like there is no rule http api,i have to add rules throw rule files? is there any other ways to register rules like  reading from db or api?.it will be very awesome if we can add rules from api.

**Comment by Gouthamve** [comment]
Hi, I think the consensus is that the configuration on disk to be the source of truth for Prometheus. See the discussion here: https://github.com/prometheus/prometheus/issues/1623

You could always write your tooling on top to do this. Please feel free to re-open if you have strong reasons against the same.
