### ISSUE TITLE
Errors when proxy is defined

### ISSUE THREAD

**Issue by abrrco** [prometheus/prometheus#3516]
**What did you do?**
Download and start Prometheus 2.0

**What did you expect to see?**
Prometheus running

**What did you see instead? Under which circumstances?**

If HTTP_PROXY and/or HTTPS_PROXY is set in environment, on
Ubuntu 16.04:
transport: http2Client.notifyError got notified that the client transport was broken unexpected EOF.
Ubuntu 14.04:
2017/11/27 13:18:51 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: failed to do connect handshake, response: \"HTTP/1.1 407 Proxy Authentication Required\\r\\nConnection: close\\r\\nContent-Length: 849\\r\\nCache-Control: no-cache\\r\\nContent-Type: text/html; charset=utf-8\\r\\nPragma: no-cache\\r\\nProxy-Authenticate: NTLM\\r\\nProxy-Authenticate: BASIC realm=\\\"IWA_Almbrand\\\"\\r\\nProxy-Connection: close\\r\\n\\r\\n<HTML><HEAD>\\r\\n<TITLE>Access Denied</TITLE>\\r\\n</HEAD>\\r\\n<BODY>\\r\\n<FONT face=\\\"Helvetica\\\">\\r\\n<big><strong></strong></big><BR>\\r\\n</FONT>\\r\\n<blockquote>\\r\\n<TABLE border=0 cellPadding=1 width=\\\"80%\\\">\\r\\n<TR><TD>\\r\\n<FONT face=\\\"Helvetica\\\">\\r\\n<big>Access Denied (authentication_failed)</big>\\r\\n<BR>\\r\\n<BR>\\r\\n</FONT>\\r\\n</TD></TR>\\r\\n<TR><TD>\\r\\n<FONT face=\\\"Helvetica\\\">\\r\\nYour credentials could not be authenticated: \\\"Credentials are missing.\\\". You will not be permitted access until your credentials can be verified.\\r\\n</FONT>\\r\\n</TD></TR>\\r\\n<TR><TD>\\r\\n<FONT face=\\\"Helvetica\\\">\\r\\nThis is typically caused by an incorrect username and/or password, but could also be caused by network problems.\\r\\n</FONT>\\r\\n</TD></TR>\\r\\n<TR><TD>\\r\\n<FONT face=\\\"Helvetica\\\" SIZE=2>\\r\\n<BR>\\r\\nFor assistance, contact your network support team.\\r\\n</FONT>\\r\\n</TD></TR>\\r\\n</TABLE>\\r\\n</blockquote>\\r\\n</FONT>\\r\\n</BODY></HTML>\\r\\n\""; Reconnecting to {[::]:9090 <nil>}

Keeps repeating in output

**Comment by abrrco** [comment]
uname -srm
Linux 4.4.0-97-generic x86_64 and
Linux 4.4.0-70-generic x86_64 

prometheus, version 2.0.0 (branch: HEAD, revision: 0a74f98628a0463dddc90528220c94de5032d1a0)
  build user:       root@615b82cb36b6
  build date:       20171108-07:11:59
  go version:       go1.9.2

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by brilliantmichael** [comment]
Setting `NO_PROXY=...,0.0.0.0:9090,...` resolves this. Prometheus is probably scraping your prometheus metrics endpoint and going through your proxy to do it.
