### ISSUE TITLE
[Feature request] ServiceComb Service Discovery

### ISSUE THREAD

**Issue by tianxiaoliang** [prometheus/prometheus#3522]
That is a Service Discovery https://github.com/ServiceComb/service-center, M hoping to contribute code to https://github.com/prometheus/prometheus/tree/master/discovery to support this service.
What u think

**Comment by tianxiaoliang** [comment]
We r a now in Apache incubator
http://incubator.apache.org/projects/servicecomb.html

**Comment by simonpasquier** [comment]
Thanks for suggesting this change. Unfortunately, we are currently not accepting new integrations.

We can only provide the stability and performance we want to provide if we can properly maintain the codebase. This includes, amongst others, test integrations in an automated and scalable fashion. For this reason, we are suggesting people integrate with the help of our generic interfaces. We have an integrations page on which integrations using our generic interfaces are listed.

Even if existing integrations can not be tested in an automated fashion, we will not remove them for reasons of compatibility. This also means that any additions we take on, or any changes to existing integrations we make or accept, will mean maintaining and testing these until at least the next major version, realistically even beyond that.

Feel free to question this answer on our [developer mailing list](https://groups.google.com/forum/#!forum/prometheus-developers), but be aware it's unlikely that you will get a different answer.
