### ISSUE TITLE
Add alert template expansion time to rule group evaluation time

### ISSUE THREAD

**Issue by conr** [prometheus/prometheus#3540]
We should add in alert template expansion time to the rule group evaluation time introduced in #3491 as this contributes the time taken to evaluate a given rule group.

**Comment by Harkishen-Singh** [comment]
I think we are already adding the expansion time in the group evaluation time.
Related code: [link](https://github.com/prometheus/prometheus/blob/f7a322fa6d4736e9bb96a9c4a230c11bafc0a7dd/rules/manager.go#L314)
@brian-brazil @conr

**Comment by brian-brazil** [comment]
Yeah, this must have gotten fixed at some point.
