### ISSUE TITLE
[Feature request] Group alerts by group name on /alerts

### ISSUE THREAD

**Issue by zemek** [prometheus/prometheus#3579]
It would be nice to have the `/alerts` page on Prometheus which shows all of the defined alerts to be grouped by the group name. Sort of like how `/targets` is grouped by job.

**Comment by beorn7** [comment]
I don't quite understand. Alerts are already grouped by alert name. But what is the group name? Alerts are only grouped in the Alertmanager. (And displaying the configured groups is indeed a problem right now, see https://github.com/prometheus/alertmanager/issues/868 .)

**Comment by brian-brazil** [comment]
I believe they mean the name of the rule group.

**Comment by aditya-konarde** [comment]
Came here looking for the same. 

The reasoning I think behind this feature request is: 

Lets say I have an app named `foo` and I define 100 rules for the app named `foo`.

As a user, I want to be able to see all the rules for that app grouped by the group I have defined the rules in. 

Can one of the maintainers please take a look?

**Comment by pbhudiaBAE** [comment]
Can this issue be closed now since #5448 has been merged

**Comment by simonpasquier** [comment]
Sure, thanks!

**Comment by kormotodor** [comment]
Oh my god why did you made it.. It looks so bad now without that alerts sorting fancy method (firing to top from all bunch of rules)

**Comment by pbhudiaBAE** [comment]
The grouping of alerts was a requested feature in multiple issues. There has already been some changes #5664 #5655 to make it more friendly. If you feel that this is still an issue you might want to consider opening a new issue.
