### ISSUE TITLE
DNS SRV fixed in upstream Go, switch to native LookupSRV in Prometheus now?

### ISSUE THREAD

**Issue by juliusv** [prometheus/prometheus#360]
https://code.google.com/p/go/source/detail?r=77ceb1db4a1e

**Comment by beorn7** [comment]
@fabxc Is that still valid? We use github.com/miekg/dns in retrieval/discovery/dns.go . Is that still needed/intended?

**Comment by juliusv** [comment]
We would have to re-try with the standard library. The fix back then didn't solve all problems IIRC, but it might be all good nowadays.

**Comment by grobie** [comment]
What are the reasons to switch?

**Comment by juliusv** [comment]
@grobie All things being equal, it's always nicer to use the standard library for something (if it works). Less dependencies, often simpler and almost guaranteed to be well-maintained.

**Comment by juliusv** [comment]
That said, there's no pressure here at all to change this.

**Comment by fabxc** [comment]
Having this in the back of my head for some time. Once this area is a bit
more stable I'll give it another shot.

**Comment by grobie** [comment]
The golang stdlib DNS resolver still doesn't support EDNS0 and there are no signs they're going to implement it anytime soon. There are DNS recursors which assume EDNS0 to be always supported. I'm in favor of closing this issue.

**Comment by brian-brazil** [comment]
Makes sense to me, this has been lying around a while with no sign of the Go library being ready for our use yet.

> There are DNS recursors which assume EDNS0 to be always supported.

Such recursors are broken.

**Comment by discordianfish** [comment]
:+1:

**Comment by matthiasr** [comment]
👍 to closing.

> Such recursors are broken.

True, but not helpful.

**Comment by beorn7** [comment]
Reopening because the head of `github.com/miekg/dns` apparently cannot deal with long DNS SRV requests. 

Typical error message:
`WARN[0684] resolving srv.eample.net failed: dns: failed to unpack truncated message source=dns.go:187`

We are just staying with the vendored version we have, but looking at the commit log of `github.com/miekg/dns`, there seem to be some worrying bugs including race conditions.

We have to revisit the issue in that light: Investigate standard library capabilities once more on the one hand, and finding out what's wrong with newer versions of `github.com/miekg/dns` on the other hand.

**Comment by discordianfish** [comment]
I assume nobody reported the bug to miekg/dns yet?
@beorn7 Does this happen with all larger SRV queries or only under special circumstances?

This looks like ErrTruncated: https://godoc.org/github.com/miekg/dns#pkg-variables
And according to the miekg/dns examples, you are suppose to check for that error. So I think that the older version of the code returned err = nil when a message is truncated, now it returns err = ErrTruncated. If that's the case, this should fix it: https://github.com/prometheus/prometheus/compare/master...discordianfish:fish/fix-dns-sd?expand=1
@beorn7 Can you test this? If it works, I can also look into adding some unit tests.

**Comment by beorn7** [comment]
@discordianfish Thanks. That could very well be it. I just had no time to look into details here.

I'll have a look as soon as I'm done with all those higher-priority tasks.

**Comment by beorn7** [comment]
Addressed in https://github.com/prometheus/prometheus/pull/2153
