### ISSUE TITLE
Move shared config types to the common repo

### ISSUE THREAD

**Issue by shubheksha** [prometheus/prometheus#3643]
In PR #3629, we moved shared types to `util/config` but since they're used across the project we should move `Secret`, `TLSConfig`, `HTTPClientConfig`, etc., to [common](https://github.com/prometheus/common).

**Comment by simonpasquier** [comment]
IIUC everything's already present in common (see [common/config/http_config.go](https://github.com/prometheus/common/blob/master/config/http_config.go)). Or am I missing something?

**Comment by brian-brazil** [comment]
That has drifted a bit, so need to be all brought up to date. Note that the blackbox exporter requires non-persistent connections.

**Comment by simonpasquier** [comment]
@shubheksha unless you plan to do it, I can give it a try.

**Comment by krasi-georgiev** [comment]
I would like to discuss an idea for the config handling in general. 
will ping you when the WIP PR  is ready

**Comment by shubheksha** [comment]
@simonpasquier Picking this up!

**Comment by shubheksha** [comment]
@brian-brazil, @simonpasquier is right. I compared  the two files, everything is already present in `common`. Only this repo needs to be switched over to use `common`.
