### ISSUE TITLE
Refactor `TargetGroup` struct

### ISSUE THREAD

**Issue by shubheksha** [prometheus/prometheus#3644]
In PR #3629, we moved `TargetGroup` into its own package from `config`. However, we need to split this into two structs:  one of them will resemble the YAML config and the other will be used for internal exchange between `retrieval` and `discovery`.

**Comment by beorn7** [comment]
Hello from the bug scrub.

This seems to be stale. Is this really needed, given that nobody complained about it in many years? @roidelapluie you might have context on this but didn't provide any when we asked you 2½ years ago. Closing this, but re-open if anyone find this is still relevant.
