### ISSUE TITLE
Remove `config` dependency from `discovery`

### ISSUE THREAD

**Issue by shubheksha** [prometheus/prometheus#3645]
This is a follow-up to #3013. In #3629, we removed `config ` dependency from the `discovery` package partially. We need to decouple these packages completely.

**Comment by shubheksha** [comment]
@krasi-georgiev, I believe you're working on something along these lines?

**Comment by krasi-georgiev** [comment]
yep , here is the first draft , but it is a WIP
https://github.com/prometheus/prometheus/pull/3605

**Comment by krasi-georgiev** [comment]
I was thinking of a global Config manager which is responsible for loading/parsing/providing the configs (thorugh `Read() struct{.....}` interface)

Each package will use the Read interface and converts the input to the package internal config types so neither  the config nor any other packages have to import shared structs types.

**Comment by shubheksha** [comment]
Sounds good! /cc @juliusv

**Comment by brian-brazil** [comment]
#3629 did this.
