### ISSUE TITLE
Why do we need 2 packages relabel packages? /pkg/relabel, /relabel 

### ISSUE THREAD

**Issue by krasi-georgiev** [prometheus/prometheus#3647]
Wondering what is the reason to have 2 almost identical relabel packages and if we can combine it into one.
/pkg/relabel
/relabel

or rename to avoid the confusion if they serve different purpose.

**Comment by brian-brazil** [comment]
Only the pkg one is meant to be there in 2.0

**Comment by krasi-georgiev** [comment]
https://github.com/prometheus/prometheus/pull/3648
once this is merged will double check and cleanup

**Comment by vn-ki** [comment]
Is this issue done?

**Comment by codesome** [comment]
No, it is being done in this PR https://github.com/prometheus/prometheus/pull/4083

**Comment by vaibhavk** [comment]
Can I work on this Issue if no one is assigned?
