### ISSUE TITLE
iincrease

### ISSUE THREAD

**Issue by roidelapluie** [prometheus/prometheus#3649]
I would like to have a iincrease function; that would be like idelta, but for counters.

**Comment by brian-brazil** [comment]
Can you explain your use case for this? `idelta` exists to allow implementation of custom rate&friends via recording rules, and the features to make that possible don't all exist yet. It's not meant to be used for anything currently.

**Comment by roidelapluie** [comment]
I want to see the Volume of data going on a SNMP interface ; All I can do is irate ; which is only the rate ; not the total volume. And idelta by purpose will not handle counters resets correctly.

**Comment by brian-brazil** [comment]
> not the total volume

Nothing in Prometheus can calculate the total volume, as history is limited. Are you sure that's what you're looking for?

**Comment by roidelapluie** [comment]
Yes idelta will do. Thanks.
