### ISSUE TITLE
The list of dropped targets grows forever

### ISSUE THREAD

**Issue by simonpasquier** [prometheus/prometheus#3652]
**What did you do?**

Setup Prometheus with kubernetes_sd scrape configuration. Then go to the Status > Service discovery page in the Prometheus UI.

**What did you expect to see?**

The list of targets including those which have been dropped.

**What did you see instead? Under which circumstances?**

The list of dropped targets is larger than what it should be and continues to grow over time.

**Environment**

* System information:

Linux 4.4.0-104-generic x86_64

* Prometheus version:

prometheus, version 2.0.0 (branch: master, revision: ec94df49d45baa8e680d81e732294eb04fff00de)
  build user:       pasquier-s@simon-trusty
  build date:       20180104-09:35:39
  go version:       go1.9.2

**Comment by simonpasquier** [comment]
IIUC we're accumulating dropped targets and the list is never reset.

See https://github.com/prometheus/prometheus/blob/ec94df49d45baa8e680d81e732294eb04fff00de/retrieval/scrape.go#L263

**Comment by simonpasquier** [comment]
cc @Conorbro

**Comment by Conorbro** [comment]
Thanks, I'll take a look now.
