### ISSUE TITLE
Binary Operators not working as expected in Prometheus 2.0

### ISSUE THREAD

**Issue by pslobo** [prometheus/prometheus#3683]
I've got the following simple query that is working in older versions of Prometheus:

`node_load1{instance=~"$instance.*"} / count by(job, instance)(count by(job, instance, cpu)(node_cpu{instance=~"$instance.*"}))` 

For some odd reason, this isn't working. When I test it out in Prometheus dashboard, it returns `no_data`. However, when I try each individual section of the query, it works just fine.

Example:

- `node_load1{instance=~"db_server.*"}` => 0.54
- `count by(job, instance)(count by(job, instance, cpu)(node_cpu{instance=~"db_server.*"}))` => 2

If I try any of these queries:

`0.54 / count by(job, instance)(count by(job, instance, cpu)(node_cpu{instance=~"db_server.*"}))` or `node_load1{instance=~"db_server.*"} / 2` I get the expected results, but join the two and I get `no_data`

**Environment**
CentOS 7 server
Linux 3.10.0-693.11.1.el7.x86_64 x86_64
Prometheus, Grafana, Alertmanager all running on Docker 

docker version
Client:
 Version:       17.12.0-ce
 API version:   1.35
 Go version:    go1.9.2
 Git commit:    c97c6d6
 Built: Wed Dec 27 20:10:14 2017
 OS/Arch:       linux/amd64

Server:
 Engine:
  Version:      17.12.0-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.2
  Git commit:   c97c6d6
  Built:        Wed Dec 27 20:12:46 2017
  OS/Arch:      linux/amd64
  Experimental: false

**Comment by pslobo** [comment]
Ok, so got this working. Changing the equation and surrounding the second part of the equation with `scalar()` did the trick. Odd that this wasn't needed in v1. Something change in that regard?

**Comment by Gouthamve** [comment]
@brian-brazil Did we break anything here?

**Comment by brian-brazil** [comment]
Looks like a typical misunderstanding of binary operator vector matching.

**Comment by pslobo** [comment]
@brian-brazil totally possible given I'm rather new to all this. What puzzles me though is that the same query (without `scalar()` seems to be working in others instances of Prometheus (v1) and this was in fact taken from published Grafana Dashboards.

**Comment by brian-brazil** [comment]
I see no indications of a bug in PromQL here.
