### ISSUE TITLE
Kubernetes namespace filtering with regex

### ISSUE THREAD

**Issue by johscheuer** [prometheus/prometheus#3692]
**Feature Request**
In this PR: https://github.com/prometheus/prometheus/pull/2642 + according issue: https://github.com/prometheus/prometheus/issues/2280 a namespace selection by name was introduced (for Kubernetes). Currently we have the requirement to filter the namespaces in a dynamic way (instead of defining some static names). If this is still an open topic I would like to implement this feature.

Best regards!

**Comment by brian-brazil** [comment]
The whole point of that feature is that the user doesn't always have permission to request a list of namespaces.

If that's not the case, you can use relabelling to restrict targets by namespace.

**Comment by johscheuer** [comment]
Thanks, will using the relabel_configs for filtering the namespaces!
