### ISSUE TITLE
file_sd sends all target groups down updates channel

### ISSUE THREAD

**Issue by cstyan** [prometheus/prometheus#3699]
SD implementations are only supposed to send changed target groups down the channel when sending updates, but file_sd sends all target groups when only one has changed.

relates to #1406

**Comment by brian-brazil** [comment]
I don't see this a bug, it's a design decision by file_sd and the SD code should be able to handle it.

**Comment by cstyan** [comment]
Did I misunderstand your SD documentation? I seem to remember that SD
mechanisms should send all target groups at the start and then only send
target groups that are updated after that.

**Comment by brian-brazil** [comment]
There's nothing saying an SD can't send everything subsequently, and for some SDs that's easier.

**Comment by cstyan** [comment]
Hmm. I must be misremembering then! My bad, feel free to close this.
