### ISSUE TITLE
consul: more efficient tag and service filtering

### ISSUE THREAD

**Issue by iksaif** [prometheus/prometheus#3711]
This is related to:
* https://github.com/hashicorp/consul/pull/2549
* https://github.com/prometheus/prometheus/pull/2028
* https://github.com/prometheus/prometheus/issues/2285
* https://github.com/prometheus/prometheus/pull/2066
* https://github.com/prometheus/prometheus/issues/3452
* https://github.com/prometheus/prometheus/issues/771
* And some others

The official answer so far as been "use relabeling", but doing that ends up opening one TCP connection per service (it looks like all the services are being watched). This happens because if you don't specify a service name, and drop using relabeling `shouldWatch()`  will always return True and all services will be watched (which is currently very inefficient with consul, and clearly non-necessary).

According to https://www.consul.io/api/catalog.html#list-services, we still can only filter on `dc` and `node-service`. As discussed in https://github.com/hashicorp/consul/pull/2549 they would like to also add `service-meta` here, but that hasn't been done (and that was almost a year ago).

Currently the discovery/consul/consul.go simply watches the Catalog without any restrictions, *but* `Services()` returns both the service names and tags, so we can start to do some filtering here based on the tags (example in https://github.com/hashicorp/consul/blob/b3292d13fb8bbc8b14b2a1e2bbae29c6e105b8f4/command/catalog/list/services/catalog_list_services.go#L85)

`catalog.Service()` can take an also optional `tag` argument that could be used to do some filtering server-side, so we can use that too to get notified only when necessary.

I (or somebody else from my team) will try to get a PR ready next week as it is quite annoying to have thousands of connections for nothing, and relabeling isn't that obvious to do this.

**Comment by iksaif** [comment]
cc: @vguerci, @Thib17, @karthimohan, @mchataigner

**Comment by brian-brazil** [comment]
I understand where you are coming from however as noted on several of those issues, Prometheus uses service discovery that exists - we don't invent new one or variants thereof. If there are filtering options that Consul supports natively then they can be considered for addition.

Service-meta as is discussed on https://github.com/hashicorp/consul/pull/2549 sounds like a better way to handle this (as would more efficient watching), and I am against adding short-term hacks to Prometheus which will ultimately lead to impedance mismatches. The place to tackle this problem is at its source.

Put another way, we already have one custom way of doing filtering in Prometheus (relabelling) I don't think we should be adding more.

**Comment by iksaif** [comment]
My point is that `Services()` returns both names and tags, and that `Service()` accepts both name and tag, but currently prometheus only uses name.

The mechanism is already here, we just do not use it.

**Comment by brian-brazil** [comment]
A config option to pass a the tag to the `Service` call would be fine by me.

**Comment by iksaif** [comment]
Great ! :) Will do that.

**Comment by brian-brazil** [comment]
You might also want to check if https://github.com/prometheus/prometheus/pull/3592 should also be applied to the Consul SD code.

**Comment by iksaif** [comment]
Ok, I will experiment with that too but I expect it to be beneficial only when the services in the catalog are disapearing. What we see are not idle connections, but [blocking queries](https://www.consul.io/api/index.html#blocking-queries) to every defined service in the catalog.

**Comment by iksaif** [comment]
We just found out that the blocking query to the catalog (one per job) could also get very expensive both in term of CPU and bandwidth (mostly because if you are big enough, the catalog is refresh all the time). There are also issues with non-stale reads to other datacenters.

I'll come up with number of graphs this week and next. Then propose ways to make that less of an issue for big users. For example I think that we could get rid of the catalog call if we already have the service names.

**Comment by iksaif** [comment]
I agree that the current (user-facing) behavior is the correct one. I'm trying to find a more resource efficient implementation of the same behavior. Currently I know that we do ~1000qps per dc on consul, and some of these queries are non-stale queries to leaders.

**Comment by iksaif** [comment]
For future reference, since one of my patch will include the ability to do stale reads, here is the impact on our cluster of **not using** stale reads (prometheus being one of the top issuer of non-stale read queries): 

![graph](https://snapshot.raintank.io/render/dashboard-solo/snapshot/Ao1duPrS1iLsJmkIARUIdbEdYFDX2q6w?refresh=15m&orgId=2&panelId=54&from=1517840644313&to=1517846093069&var-datacenter=par&var-period=10m&width=1000&height=500&tz=UTC%2B01%3A00)

[link](https://snapshot.raintank.io/dashboard/snapshot/Ao1duPrS1iLsJmkIARUIdbEdYFDX2q6w?refresh=15m&orgId=2&panelId=54&fullscreen&from=1517840644313&to=1517846093069&var-datacenter=par&var-period=10m)
