### ISSUE TITLE
Regex match unable to match missing labels

### ISSUE THREAD

**Issue by SharpEdgeMarshall** [prometheus/prometheus#3712]
### Issue
- `my_metric{my_label=""}` matches when `my_label` is empty or missing
- `my_metric{my_label=~".*"}` matches only when `my_label` is empty

This difference in behaviour is misleading and actually there is no workaround.

### Use case
Need to match a label `my_label` with a Grafana template variable `$Myvar`, it should be possible to match also all values of `my_label` so regex matching must be used with `.*` but there is no way to match metrics where `my_label` is missing.

`my_metric{my_label=~"^$Myvar$"}`

**Comment by brian-brazil** [comment]
Is this on Prometheus 2.0.0? It should be fixed in 2.1.0.

**Comment by SharpEdgeMarshall** [comment]
yes prometheus 2.0.0, i'll try with 2.1.0

**Comment by brian-brazil** [comment]
I presume this is all working now.
