### ISSUE TITLE
After Prometheus 2.0 upgrade, df -h command hangs. 

### ISSUE THREAD

**Issue by gbvikas** [prometheus/prometheus#3717]
we upgraded the dev environment(running in AWS) from prometheus 1.8 to 2.0. 
The "df -h" used to work with prometheus 1.8 version. Note that there is separate disk attached for prometheus storage. 
But after the upgrade, the command just hangs. If we stop Prometheus instance, then the command works. 
Does Prometheus 2.0 hold any lock? 
I am able to navigate through the folders.

**Comment by brian-brazil** [comment]
This is very unlikely to be a Prometheus issue. This sounds like overload or some other issues on your machine.
