### ISSUE TITLE
Better syntax mistake errors

### ISSUE THREAD

**Issue by typingduck** [prometheus/prometheus#372]
Currently syntax errors in the UI are of the form "Error parsing rules at line 1, char 6: syntax error" when the 5th character is incorrect.
The off-by-one error plus not reporting which character is the problem makes it difficult to diagnose.
(As a side not the problem character here was the '.' char. Not sure if this is explicitly disallowed or not. If disallowed then perhaps it should be filtered out at an earlier stage)

**Comment by fabxc** [comment]
Fixed by #676
