### ISSUE TITLE
After 2.1.0 upgrade tsdb reloads block dat from disk all the time

### ISSUE THREAD

**Issue by roidelapluie** [prometheus/prometheus#3725]
The metric is tsdb_reloads_total Number of times the database reloaded block data from disk.

Upgrade happened at 8.33

![upgrade](https://user-images.githubusercontent.com/291750/35241025-73858ce0-ffb5-11e7-91f4-1c618d3a7432.png)

Also SOME queries take a lot more time.

Please note that this prometheus server is not the server from where we graph so dashboards have no influence on that data (it is just recording rules):

![qd](https://user-images.githubusercontent.com/291750/35241104-b6d223b4-ffb5-11e7-9afc-0fe5b62c4a96.png)
(0.5 quantile is the same before and after upgrade so only some queries are impacted)

**Comment by FUSAKLA** [comment]
I can confirm this problem 
![screenshot from 2018-01-26 01-15-16](https://user-images.githubusercontent.com/6112562/35419096-6e573542-0236-11e8-91be-7fcb510a3db7.png)

**Comment by roidelapluie** [comment]
tsdb https://github.com/prometheus/tsdb/commit/b7bea04e62fda5eccd8f3999a6e2fb50117d46f4 by @Gouthamve is the fix for this

**Comment by Gouthamve** [comment]
Closed in #3747
