### ISSUE TITLE
NullPointerException crash in Java API

### ISSUE THREAD

**Issue by njbartlett** [prometheus/prometheus#3729]
In the Java API, the following code works:

```java
private final Gauge fillLevelGauge = Gauge.build()
        .name("fill_level")
        .help("Fill level")
        .register();

    // ...

    fillLevelGauge.set(1d);
```

... but the following code crashes with a `NullPointerException`:

```java
private final Gauge fillLevelGauge = Gauge.build()
        .name("fill_level")
        .labelNames("mylabel")
        .help("Fill level")
        .register();

    // ...

    fillLevelGauge.set(1d);
```

I found the following [issue](https://github.com/prometheus/prometheus/issues/3225) which states "for a labelled metric you must specify the labels". However I cannot believe that you actually intend for the program to **crash** when a programmer makes this mistake? And not even with any explanation of the reason for the crash?

At the very least I believe this should be an `IllegalArgumentException` with a message attached, e.g. "for a labelled metric you must specify the labels".

**Comment by krasi-georgiev** [comment]
@njbartlett shouldn't this be in the java client issues?
https://github.com/prometheus/client_java

**Comment by njbartlett** [comment]
@krasi-georgiev  Sorry yes, I will move it.
