### ISSUE TITLE
Error sending samples to remote storage 

### ISSUE THREAD

**Issue by gangsta** [prometheus/prometheus#3732]
Hi , 

Getting 

```go
Jan 24 15:15:51 prometheus prometheus: level=warn ts=2018-01-24T14:15:51.973934966Z caller=queue_manager.go:485 component=remote msg="Error sending samples to remote storage" count=100 err="server returned HTTP status 400 Bad Request: proto: wrong wireType = 2 for field StartTimestampMs"
```
* prometheus.yaml
```
remote_read:
- url: http://localhost:9201/write
remote_write:
- url: http://localhost:9201/read
```

* remote_stroage_adapter 

```
/usr/sbin/remote_storage_adapter \
  -influxdb-url=http://domain.com:8086/ \
  -influxdb.database=db \
  -influxdb.retention-policy=autogen \
  -influxdb.username=user \
  -send-timeout=30s
```

* influxdb 

```
version: influxdb-1.4.2

# Influxdb 
influx 
auth  
CREATE DATABASE db; 
CREATE USER "user" with password 'psswd'; 
GRANT ALL ON db TO user; 
ALTER RETENTION POLICY "autogen" ON "db" DURATION 1d REPLICATION 1 SHARD DURATION 1d DEFAULT;
SHOW RETENTION POLICIES ON db;
#shown above retention

SHOW MEASUREMENTS;
# nothings is shown
```

* Prometheus

```
version: 
[root@prometheus ~]# prometheus --version
prometheus, version 2.1.0 (branch: HEAD, revision: 85f23d82a045d103ea7f3c89a91fba4a93e6367a)
  build user:       root@6e784304d3ff
  build date:       20180119-12:01:23
  go version:       go1.9.2
```

**Comment by tomwilkie** [comment]
Thanks for the report @kalinux.  I think the remote storage adapters have rotted a little.  As of influx v1.4.0 you don't need the remote storage adapter IIRC, influx supports our remote read/write APIs natively.

**Comment by kalinux** [comment]
Hi @tomwilkie 
Can you give me prometheus.yaml example (or point to some documentation) how to configure Prometheus with Influxdb ?
as far as I can find documentation it touches `remote_storage_adapter`

Regards
Karen

**Comment by kalinux** [comment]
Or you meant
remote_read:
```yaml
- url: http://domain.com:8086/
remote_write:
- url: http://domain.com:8086/
```

**Comment by tomwilkie** [comment]
I've not used it before, but this blog post has some details: https://www.influxdata.com/blog/influxdb-now-supports-prometheus-remote-read-write-natively/

**Comment by fmoessbauer** [comment]
By now there is also official documentation on how to use the native API: https://docs.influxdata.com/influxdb/v1.4/supported_protocols/prometheus#prometheus-remote-read-and-write-api-support

However until https://github.com/influxdata/influxdb/issues/9244 is not resolved, the native backend is not backwards compatible with the remote_storage_adapter.

**Comment by kalinux** [comment]
Hi @tomwilkie @fmoessbauer , so that means we can close this issue until InfluxDB fixes issue/adds feature ?

**Comment by fmoessbauer** [comment]
@kalinux this depends on how the prometheus team is going to proceed with the remote_storage_adapter. If support is going to be dropped in favor of the influxdb native one, this issue should be at least documented as a known error.

**Comment by tomwilkie** [comment]
I chatted to @brian-brazil this weekend at FOSDEM and remote_storage_adapter is going to hang around a little longer, as it serves as a good example.  I'm going to update it, add it to our CI etc.  I'll chat to influx and see if we should remove the influx path from the adapter or not.

**Comment by kalinux** [comment]
@tomwilkie the same from me , chatted with @brian-brazil at FOSDEM about how to solve this Influxdb and remote_storage_adapter story , seems only way so far is just to use `url: influxdburl+credentials` cause Influxdb is not providing basic http authentication . so to me its more in Influxdb side ?

**Comment by brian-brazil** [comment]
@kalinux  That's a different problem you're thinking of.

I note that our influx adpater is the only example of a read adapter we have, though others (such as the CrateDB adapter) also exist out there.

**Comment by kalinux** [comment]
so what is solution ? use remote_storage_adapter or not ? use `url: influxdb+credentials` or not ?

**Comment by simonszu** [comment]
When referring to the original issue in the first post, i now have the same problem as well. I won't drop `remote_storage_adapter` from my setup until InfluxDB fixes the bug @fmoessbauer mentioned - although it seems that for now i have to live without influxdb integration at all.

**Comment by kalinux** [comment]
@simonszu you can use as temporary solution putting all in URL, that's works for as well, but again - as temporary solution.

**Comment by kalinux** [comment]
copied from Docs.
```
# Remote write configuration (for Graphite, OpenTSDB, or InfluxDB).
remote_write:
* url: "http://localhost:8086/api/v1/prom/write?u=paul&p=foo&db=prometheus"
# Remote read configuration (for InfluxDB only at the moment).
remote_read:
* url: "http://localhost:8086/api/v1/prom/read?u=paul&p=foo&db=prometheus"
```
Insecure I know , but there is no other solution so far ,

**Comment by simonszu** [comment]
Yeah, ok, this is for InfluxDBs new native Prometheus API. Unfortunately there's https://github.com/influxdata/influxdb/issues/9244 which causes the data sent by Prometheus not properly written into InfluxDBs storage.

**Comment by adityanmishra** [comment]
But it works fine with 2.1.0

**Comment by weih1214** [comment]
> seems only way so far is just to use url: influxdburl+credentials cause Influxdb is not providing basic http authentication . so to me its more in Influxdb side ?
Does this mean that basic_auth config doesn't work at all?

**Comment by weih1214** [comment]
Hi all, I am trying to config adapter for prometheus. I want to use basic_auth for the authentication, but I got error from adapter "err="{\"error\":\"unable to parse authentication credentials\"}", which I guess is something wrong in the authentication. How can I use adapter to communicate with influxdb using certain credentials?

**Comment by gangsta** [comment]
@weih1214 I`m using influxdburl+credentials as remote storage url, as far I get, basic_auth works from Prometheus side, but Influxdb is not supporting it , probably thats why you get this error.

**Comment by appleboy** [comment]
Hi I have the same problem with [Splunk storage adapter](https://github.com/kebe7jun/ropee)

Prometheus version: 2.14.0

See the following log

```
Nov 12 05:36:04 prometheus[1144]: ts=2019-11-12T05:36:04.222Z caller=dedupe.go:111 component=remote level=warn queue=0:http://127.0.0.1:9970/read msg="Skipping resharding, last successful send was beyond threshold" lastSendTimestamp=0 minSendTimestamp=1573536954
Nov 12 05:36:10 prometheus[1144]: ts=2019-11-12T05:36:10.761Z caller=dedupe.go:111 component=remote level=error queue=0:http://127.0.0.1:9970/read msg="non-recoverable error" count=100 err="server returned HTTP status 400 Bad Request: proto: wrong wireType = 2 for field StartTimestampMs"
```

any hints to debug?

**Comment by gouthamve** [comment]
We went through this issue in our bugscrub and have decided to close this as the upstream issue from Influx is fixed. Please feel free to reopen this if you're still seeing problems!
