### ISSUE TITLE
Long label values hard to read on service discovery status page

### ISSUE THREAD

**Issue by brian-brazil** [prometheus/prometheus#3739]
Some k8 SD labels like `__meta_kubernetes_pod_annotation_kubernetes_io_created_by` can be very long, making the service discovery status page scroll horizontally.

We should really wrap these, such as by removing the `whitespace: nowrap` and adding `display: inline`.

**Comment by vaibhavsingh97** [comment]
@brian-brazil I want to claim this issue 👍
