### ISSUE TITLE
Provide Metrics and Endpoints Dashboard in Prometheus Server

### ISSUE THREAD

**Issue by matttproud** [prometheus/prometheus#376]
@juliusv and I spoke a while ago about the desire to have a standardized metrics and endpoints metadata dashboard in the Prometheus server itself to provide the following information:
# Targets/Endpoints
- Metrics Exposed Drilldown (including time when metric {first,last} seen, documentation, type information)
- Time {First,Last} Seen
- Time {First,Last} Responded

**Comment by LeviHarrison** [comment]
Is this still valid?

**Comment by juliusv** [comment]
I guess something along those lines could still make sense, but maybe as part of a more general better metrics exploration interface story than just something geared around targets.
