### ISSUE TITLE
histogram_quantile error result

### ISSUE THREAD

**Issue by Jaware** [prometheus/prometheus#3769]
prometheus 1.7.1
my query is:histogram_quantile(**0.95**, rate(http_server_requests_bucket{app="puhui-decision-server"}[30m]))
the result is:
![image](https://user-images.githubusercontent.com/3970304/35602087-4d5c1120-0671-11e8-9cfc-e131898ca8d8.png)
it is obvious that "/prometheus" can not be 0.95
when i use 0.90  query :histogram_quantile(**0.90**, rate(http_server_requests_bucket{app="puhui-decision-server"}[30m]))
![image](https://user-images.githubusercontent.com/3970304/35602162-b8f4ae6a-0671-11e8-9a3e-17accbb32758.png)

the result is 0.90 ,why is that the result is decided by φ-quantile? so weird

**Comment by brian-brazil** [comment]
Can you share the result of the rate()?

**Comment by Jaware** [comment]
sorry ,little busy
![image](https://user-images.githubusercontent.com/3970304/35721021-2eb680e6-082b-11e8-8284-e93daf5da17c.png)

**Comment by brian-brazil** [comment]
Those are different queries for different jobs and instances, different results are to be expected.

**Comment by Jaware** [comment]
they are not different jobs,job is all the same("all"),i can not find out why

**Comment by Jaware** [comment]
can you show me how to use histogram_quantile correctly? it seems as if my query is wrong @brian-brazil
