### ISSUE TITLE
Prometheus not monitoring Rancher Server

### ISSUE THREAD

**Issue by pkaramol** [prometheus/prometheus#3775]
**What did you do?**
Deployed Prometheus/Grafana stak on a Rancher environment, on AWS.

**What did you expect to see?**
Prometheus collecting metrics from the Rancher Server as well (container and Rancher host metrics seem to work)

**What did you see instead? Under which circumstances?**
No data points collected in *Rancher Stats* dashboard.

**Environment**

*Rancher Server*:
```
$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

```
"CATTLE_RANCHER_SERVER_VERSION=v1.6.14",
```

*Rancher Host*:
```
[rancher@rancher-node01 ~]$ cat /etc/os-release 
NAME="RancherOS"
VERSION=v1.1.3
ID=rancheros
ID_LIKE=
VERSION_ID=v1.1.3
PRETTY_NAME="RancherOS v1.1.3"
HOME_URL="http://rancher.com/rancher-os/"
SUPPORT_URL="https://forums.rancher.com/c/rancher-os"
BUG_REPORT_URL="https://github.com/rancher/os/issues"
BUILD_ID=
```

```
[rancher@rancher-node01 ~]$ docker ps | grep -i rancher | awk '{print $2}'
rancher/scheduler:v0.8.3
infinityworks/prometheus-rancher-exporter:v0.22.52
rancher/lb-service-haproxy:v0.7.15
rancher/external-lb:v0.3.3
rancher/rancher-ecr-credentials:v2.0.1
rancher/net:v0.13.7
rancher/net:v0.13.7
rancher/net:v0.13.7
rancher/dns:v0.15.3
rancher/network-manager:v0.7.19
rancher/net:holder
rancher/healthcheck:v0.3.3
rancher/metadata:v0.9.5
rancher/agent:v1.2.9
```

* System information:

*Rancher Server*:
```
$ uname -srm
Linux 4.4.0-1049-aws x86_64
```

*Rancher Host*:
```
[rancher@rancher-node01 ~]$ uname -srm
Linux 4.9.75-rancher x86_64
```

* Prometheus version:

	insert output of `prometheus --version` here

* Alertmanager version:

	insert output of `alertmanager --version` here (if relevant to the issue)

* Prometheus configuration file:
```
insert configuration here
```

* Alertmanager configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
