### ISSUE TITLE
Restart time increase gradually for each restart on Prometheus 2.0

### ISSUE THREAD

**Issue by tejaswiniVadlamudi** [prometheus/prometheus#3777]
When I try to check the restart time of Prometheus, it increases gradually each time, I reboot.

For 5 iterations: I got the below values: 7, 21, 35, 57, 97

Process followed:

1. Login to Prometheus container, run:
     date; reboot
2. Check if Prometheus container is UP and check uptime
3. Measure restart time as difference between uptime and time you get on running in bullet 1 

Running Prometheus 2.0 on Kubernetes 1.6.10

**Comment by brian-brazil** [comment]
Over what time period is this? The WAL is expected to require more work over time, but that should reset every 2h.

Does this also happen with 2.1.0?

**Comment by brian-brazil** [comment]
Can you also indicate if there's any indications of data corruption? I have another report of this which went away when a corrupted block was removed.

**Comment by tejaswiniVadlamudi** [comment]
Prometheus is not corrupted, I haven't verified this with 2.1 yet.
I can check and confirm.

**Comment by brian-brazil** [comment]
This was probably the 4GB index issue preventing compaction, if this is still happening with 2.2.1 please reopen.
