### ISSUE TITLE
Fix kubernetes charts

### ISSUE THREAD

**Issue by felixPG** [prometheus/prometheus#3787]
Hi:

I dont know if this is the same team that make the kubernetes charts, but please, could you take a look to https://github.com/kubernetes/charts/issues/3519

Regards

**Comment by brian-brazil** [comment]
This is not a problem in Prometheus itself, I believe you have already filed a bug in the right place.

**Comment by felixPG** [comment]
ok thanks, Only asking if is the same team that develop the prometheus helm chart.
