### ISSUE TITLE
Storing/loading multiple graphs from URL doesn't work anymore

### ISSUE THREAD

**Issue by juliusv** [prometheus/prometheus#3789]
When adding more than one graph on the `/graph` page, only the first one is stored in the URL. Also, when trying to open a URL like [http://localhost:9090/graph?g0.range_input=1h&g0.expr=rate(node_cpu%5B1m%5D)&g0.tab=0&g1.range_input=1h&g1.expr=rate(http_request_duration_microseconds_count%5B1m%5D)&g1.tab=0](http://localhost:9090/graph?g0.range_input=1h&g0.expr=rate(node_cpu%5B1m%5D)&g0.tab=0&g1.range_input=1h&g1.expr=rate(http_request_duration_microseconds_count%5B1m%5D)&g1.tab=0), the second entry is halfway rendered, but not executed (and disappears from the URL).

According to `git bisect` this regression was introduced by https://github.com/prometheus/prometheus/commit/a8ff643464ee5f3cf97f1c55c0aab44796f09167. @lovisas would you be able to take a look?

**Comment by juliusv** [comment]
The bug (at least trying to open the link above) only seems to happen when "Search query history" is enabled.

**Comment by lovisas** [comment]
Yes will do!
