### ISSUE TITLE
provide median() operator or note how to get it with quantile(0.5)

### ISSUE THREAD

**Issue by tzz** [prometheus/prometheus#3791]
Currently, the `quantile` operator is provided, but there's no `median`. The `median` according to https://prometheus.io/docs/practices/histograms/ is trivially `quantile(0.5, ...)`. Can you please consider either adding a new `median` operator to do this, or adding a note to `quantile` in the docs https://prometheus.io/docs/prometheus/latest/querying/operators/ for users that don't know this?

Thank you.

**Comment by matthiasr** [comment]
Since it's so easy to do with the existing quantile function, I don't think
we need a new one.

For mentioning this, can you please make a PR in <
https://github.com/prometheus/docs>?

**Comment by tzz** [comment]
The operators.md reference was not in the docs repo so I created https://github.com/prometheus/prometheus/pull/3792 which should resolve it trivially.

Thanks.

**Comment by beorn7** [comment]
With #3792 closed, I'll try to craft a docs PR that might find more acceptance.
