### ISSUE TITLE
Add CII Badge

### ISSUE THREAD

**Issue by caniszczyk** [prometheus/prometheus#3795]
One of the CNCF graduation requirements is getting a CII Badge:
https://bestpractices.coreinfrastructure.org/

It would be great to see this happen :)

**Comment by brian-brazil** [comment]
I did this many months ago.

**Comment by caniszczyk** [comment]
@brian-brazil can you add the badge to the README?

**Comment by azmelanar** [comment]
@brian-brazil @caniszczyk created pull request.
