### ISSUE TITLE
Wrong log and data timestamp showing for the wrong timezone

### ISSUE THREAD

**Issue by tdy218** [prometheus/prometheus#3803]
$ sw_vers
> ProductName:	Mac OS X
> ProductVersion:	10.13.3
> BuildVersion:	17D47

$ uname -srm
> Darwin 17.4.0 x86_64

$ ./prometheus --version
> prometheus, version 2.1.0 (branch: HEAD, revision: 85f23d82a045d103ea7f3c89a91fba4a93e6367a)
>  build user:       root@6e784304d3ff
>  build date:       20180119-12:07:34
>  go version:       go1.9.2

When the prometheus was started, it showed wrong log timestamp.
<img width="968" alt="prometheus_wrong_timestamp" src="https://user-images.githubusercontent.com/4214030/35847147-56e9c0ec-0b54-11e8-8429-8fed52e8290e.png">

When i opened the prometheus graph webpage, it showed wrong time also.
![wechatimg7](https://user-images.githubusercontent.com/4214030/35847501-99fe4546-0b55-11e8-81ba-ec8d12ab925e.jpeg)

**Comment by tdy218** [comment]
I noticed the following words in the prometheus FAQ webpage.
> To avoid any kind of timezone confusion, especially when the so-called daylight saving time is involved, we decided to exclusively use Unix time internally and UTC for display purposes in all components of Prometheus. A carefully done timezone selection could be introduced into the UI. Contributions are welcome. See issue #500 for the current state of this effort.
from https://prometheus.io/docs/introduction/faq/#can-i-change-the-timezone?-why-is-everything-in-utc?

No matter how can i change the timezone on my laptop, the log and the data timestamp is wrong still, is there something else setting about timezone for prometheus ?

**Comment by brian-brazil** [comment]
As those docs say, Prometheus uses UTC and has no notion of timezones.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
