### ISSUE TITLE
Parametrised rules

### ISSUE THREAD

**Issue by jsuchenia** [prometheus/prometheus#3804]
## Enhancement request
It could be nice that rule files can be loaded with some parameters attached. Those parameters could be useful as a context to 'for' or some default labels assignments
Currently all rules are loaded as they are so it's hard to maintain rules with different settings or threshold levels

## How to implement that
We can evaluate rule file before YAML parser as a template. I know that inside Alert rules we use templating, so initial params can be included using other notation like `[[` and `]]` instead of typical mustaches (looks like in go templating  you can define Delims)

Example usage:
```
rules:
 - file: /path/to/file.yml
   params:
      a: b
      c: d
```
Then we can skip groups, change thresholds, conditionally load/skip alerts based on cofiguration

* Prometheus version:
Currently in 2.1.0 there are no such solution

**Comment by brian-brazil** [comment]
This sort of thing is something that we expect users to handle using the templating feature of your configuration management system. In this case it sounds like you may be looking for the existing external_labels setting combined with alert notification templates in the Alertmanager.

**Comment by jsuchenia** [comment]
@brian-brazil When you have a configuration management then you can use it - and that's fine. However often we have only scheduler (like kubernetes, or others) to run a container and pre-defined configuration that can use service discovery. Currently I'm using a bunch of sed/awk scripts to tune main config file + concatenate only needed alerts

Of course using scheduler we can deliver a whole configuration and all needed alerts. In our case we deliver an application with profiled prometheus to monitor it (rules, console templates) - in this case you have to adjust configuration in a scheduler (prometheus params, new rules) - we can't deliver a template of that.

As long as I'm thinking about that it could be useful to have an ability to override parameters from a command line or env variable - maybe we can template config and alerts based from env variables, cmd line or hardcoded as proposed above?

**Comment by brian-brazil** [comment]
Prometheus intends to be a monitoring system, not to duplicate the functionality of configuration management. There's no plans to add any such features to Prometheus. You should look into something like ksonnet.
