### ISSUE TITLE
Add ability to clear history for individual metrics

### ISSUE THREAD

**Issue by juliusv** [prometheus/prometheus#382]
From @mweiden:

"Adding the ability to clear the history for one metric instead of removing all storage via 'sudo rm -rf /srv/prometheus/storage/*' would make debugging metric design much less painful and leave other crucial data intact."

**Comment by beorn7** [comment]
https://github.com/prometheus/prometheus/pull/743 has added the required method to the storage. Now we need an API...

**Comment by fabxc** [comment]
We wanted to document an official `v1` HTTP-API.
So we first will want to define a consistent one. Not sure whether the current endpoints fulfill that - especially in terms of the response format.

**Comment by juliusv** [comment]
At least there's nothing obvious I'd want to change about the response formats for now. We made some adjustments to the response format (https://github.com/prometheus/prometheus/issues/389) before the January announcement, so that we wouldn't have to change it so much anymore afterwards.

We can think if we want to amend/adjust the query parameters. Currently you provide `end` and `range` for range queries, instead of `start` and `end`. We could allow optionally specifying `start` instead of `end`, but that could be added later in a non-breaking way.

**Comment by fabxc** [comment]
Yes, was not so much about changing but about verifying that everything is consistent.
I actually started a design doc this morning - let's see.

If there's something we can do better, we shouldn't be hold back by a semi-official announcement in a buried issue.

**Comment by juliusv** [comment]
Keep in mind that PromDash, Grafana, and other tools already use the query API as it stands today, so even without an official API announcement there's already tons of things we'd break if we changed something in a backwards-incompatible way. Hoping for v1 of the API to be compatible with today's API in the best case...

**Comment by fabxc** [comment]
That's why I think we should just define a public API and provide the old one in parallel. We will want to do API-versioning, so the endpoint paths break anyway.

**Comment by juliusv** [comment]
This just got fixed in https://github.com/prometheus/prometheus/pull/783
