### ISSUE TITLE
Empty labels being returned from PromQL

### ISSUE THREAD

**Issue by brian-brazil** [prometheus/prometheus#3841]
https://github.com/prometheus/alertmanager/issues/1240 shows empty labels somehow coming out of storage and into alerts. I've seen this previously myself also, but haven't narrowed it down. I suspect an issue on the ingestion path somewhere.

**Comment by brian-brazil** [comment]
This is an issue in retreival by the looks of it, and `honor_labels` is not honoring empty strings.

**Comment by krasi-georgiev** [comment]
any easy way to replicate it?

**Comment by brian-brazil** [comment]
Pushgateway example shows it, as you end up with an instance label. Working on a fix, but this all needs unittests too.
