### ISSUE TITLE
Switch from InstrumentHandler to InstrumentHandlerDuration

### ISSUE THREAD

**Issue by brian-brazil** [prometheus/prometheus#3844]
The current InstrumentHandler we are using in web.go is deprecated, we should replace it with InstrumentRoundTripperDuration.

**Comment by beorn7** [comment]
`InstrumentRoundTripper…` is for client-side instrumentation. To replace `InstrumentHandler` from the `prometheus` package, you want to use the `InstrumentHandler…` family of middlewares from the `promhttp` package.

**Comment by brian-brazil** [comment]
Thanks, summary updated.

**Comment by brian-brazil** [comment]
The duration will include the request count. I'm not sure if we want size, probably doesn't hurt.
