### ISSUE TITLE
Invalid target labelnames?

### ISSUE THREAD

**Issue by brian-brazil** [prometheus/prometheus#3850]
Per https://groups.google.com/forum/#!topic/prometheus-users/4JIBSa1zyDA it appears that a user on 2.0.0 has managed to have target labels containing hyphens in the label name. This indicates a lack of validation somewhere.

**Comment by krasi-georgiev** [comment]
DIBS

should this be checked in the `parser` or somewhere in the ingestion path?

**Comment by brian-brazil** [comment]
It's probably that the sanitization I added around service discovery was lost.

**Comment by krasi-georgiev** [comment]
that would mean I broke it :flushed:  , do you remember where was this piece to save me some digging?

**Comment by maximilianvw** [comment]
Sorry guys I was offline for the weekend. I reported this bug via the mailing list. My scrape config was as follows:

`scrape_configs:
- job_name: prometheus
  scrape_interval: 10s
  scrape_timeout: 10s
  static_configs:
  - targets:
    - localhost:9090
- job_name: openstack
  openstack_sd_configs:
  - identity_endpoint: xxx
    password: xxx
    project_name: xxx
    role: instance
    username: xxx
  relabel_configs:
  - action: keep
    regex: ACTIVE
    source_labels:
    - __meta_openstack_instance_status
  - action: keep
    regex: 'true'
    source_labels:
    - __meta_openstack_tag_service_nodeexporter
  - regex: ([^:]+)(?::\d+)?
    replacement: $1:9100
    source_labels:
    - __address__
    target_label: __address__
  - source_labels:
    - __meta_openstack_private_ip
    target_label: private_ip
  - source_labels:
    - __meta_openstack_public_ip
    target_label: floating_ip
  - source_labels:
    - __meta_openstack_instance_name
    target_label: instance
  - action: labelmap
    regex: __meta_openstack_tag_service_(.+)
    replacement: service-$1`

Let me know if you need more details.

**Comment by brian-brazil** [comment]
So the issue here is around that last labelmap.

**Comment by simonpasquier** [comment]
thanks @maximilianvw I think I've spotted the place. Will send a PR.
