### ISSUE TITLE
2.2.0-rc.0 is not downgradeable to 2.1.0

### ISSUE THREAD

**Issue by zegl** [prometheus/prometheus#3859]
**What did you do?**

Upgrade to 2.2.0-rc.0, and then downgrade the same server to 2.1.0 again.

**What did you expect to see?**

No issues. Upgrading and downgrading should be supported between minor versions.

**What did you see instead? Under which circumstances?**

Data related errors.

* Logs:

```
level=error ts=2018-02-19T08:34:22.401620054Z caller=engine.go:533 component="query engine" msg="error expanding series set" err="block: 01C6N2WWGAQW2JJTKKY0T2A9WB: invalid checksum"
level=error ts=2018-02-19T08:34:22.401686966Z caller=engine.go:544 component="query engine" msg="error selecting series set" err="symbol lookup: unknown symbol offset 0"
```

**Comment by fabxc** [comment]
Yes, this is intended unfortunately as 2.1.0 introduced a bug where storage files were written in an invalid way. 2.2 repairs this automatically on the first startup but naturally 2.1 does no longer understand the correct version.

Sorry if this was not clarified in the changelog of the RC.

Did you encounter any particular issue that made you want to downgrade again?

**Comment by zegl** [comment]
Ok, I understand. This didn't cause any large problems, I just had to remove all persisted data on this node and restart it.

I've been debugging a recent issue with prometheus running out of memory (I'll open another issue if I find anything), and as a part of my debugging I tried to upgrade one node to 2.2. The downgrade was triggered by "accident" by a deployment job.
