### ISSUE TITLE
Strange behaviour of Counter

### ISSUE THREAD

**Issue by sigma420** [prometheus/prometheus#3860]
**What did you do?**
Use client_java to model a Counter

**What did you expect to see?**
The Counter value should always increase over time

**What did you see instead? Under which circumstances?**
The Counter value flip flopped increasing and decreasing continuously. When viewed over a day,overall the counter value increased.

**Environment**
linux prometheus 2.0

* System information:

	insert output of `uname -srm` here
[ec2-user@ip-10-11-37-190 ~]$ uname -srm
Linux 3.10.0-514.6.1.el7.x86_64 x86_64

* Prometheus version:

	insert output of `prometheus --version` here
prometheus, version 2.0.0 (branch: HEAD, revision: 0a74f98628a0463dddc90528220c94de5032d1a0)
  build user:       root@615b82cb36b6
  build date:       20171108-07:11:59

  go version:       go1.9.2

![image](https://user-images.githubusercontent.com/1855753/36376845-d36fbf3a-15c8-11e8-976b-cf483cba0e7e.png)

![image](https://user-images.githubusercontent.com/1855753/36376883-f6d3ff7c-15c8-11e8-9e7f-07b7c2988433.png)

**Comment by brian-brazil** [comment]
Are you scraping through any form of load balancer? This is usually due to scraping multiple instances as one target, which doesn't work.

**Comment by sigma420** [comment]
hi Brian,

Thanks for the quick response. The targets are individual hosts where the Java app is running.  In the graphic attached in the issue, I am trying to plot the metric from a single host svtnd0000002pr.nbndc.local:80. This is listed as a separate target in the config file. Please see the list of targets below.

![image](https://user-images.githubusercontent.com/1855753/36377215-72f543f8-15ca-11e8-8609-c04abca815a6.png)

**Comment by brian-brazil** [comment]
If there is indeed only one JVM backing that target, then the issue is likely incorrect usage of the client library. What does this metric look like in your code?

**Comment by sigma420** [comment]
Hi Brian,

It is defined as follows

public final class Metrics {
    /**
     static {
     DefaultExports.initialize();
     } **/

    public static final Counter executeAutomatedWorkflowAsyncTotal = Counter
            .build()
            .name("tnd_nbi_executeAutomatedWorkflowAsync_total")
            .help("Total number of nbi executeAutomatedWorkflow request ")
            .labelNames("workflow","testname","usergroup","userid","channel").register();

And used as follows

if (null != params.get("testIdentifier")) {	
			 Metrics.executeAutomatedWorkflowAsyncFailureTotal.labels(wfname,params.get("testIdentifier"),params.get("userDescriptor"),params.get("requestorID"),params.get("channelID")).inc();
			 }

**Comment by brian-brazil** [comment]
Aside from having all your metrics abstracted away in a different class being discouraged (keep them in the same file they are used), that looks okay. You've got a loadbalancer or similar in here somewhere.

**Comment by sigma420** [comment]
Hi Brian,

Thanks so much for the feedback. It was a load balancing issue.
