### ISSUE TITLE
Can't add GZ zone discovery end points

### ISSUE THREAD

**Issue by Adel-Magebinary** [prometheus/prometheus#3871]
Hello @richardkiene 

Since the endpoint is consist of Endpoint, Port, Version.

Could you please add a Zone as a config as well?

`var endpoint = fmt.Sprintf("https://%s:%d/v%d/discover", d.sdConfig.Endpoint, d.sdConfig.Port, d.sdConfig.Version)`

becomes

`var endpoint = fmt.Sprintf("https://%s:%d/v%d/%s/discover", d.sdConfig.Endpoint, d.sdConfig.Port, d.sdConfig.Version,d.sdConfig.Zone)`

where d.sdConfig.Zone can be 'gz'
eg:
"https://cmon.cns.x.com:9163/v1/gz/discover"

Related code:
https://github.com/prometheus/prometheus/blob/675ce533c97bf3b0d952ac346339b4cad17d5588/discovery/triton/triton.go#L193

**Comment by Adel-Magebinary** [comment]
Another dirty fix can be changing the version type to string :) but it's a bad idea.

**Comment by RichiH** [comment]
We're currently triaging. Is this still relevant for you? Any useful updates?

**Comment by Adel-Magebinary** [comment]
Yes. It would be more important to know the status of each server than individual containers.  Happy to test this if it is required.
