### ISSUE TITLE
Use standard json naming convention

### ISSUE THREAD

**Issue by stuartnelson3** [prometheus/prometheus#389]
This would probably require changes to every project, but I think it'd be nice to use standard JSON naming for the api, so instead of 

```javascript
{Type: "matrix",
 Value: [
  Metric: {},
  Values: [{Value: 1, Timestamp:1234428}]
}
```

it would be

```javascript
{type: "matrix",
 value: [
  metric: {},
  values: [{values: 1, timestamp:1234428}]
}
```

thoughts?

**Comment by juliusv** [comment]
:+1: - though I think compressed encodings should take care pretty well of maps per sample? Anyways, I'm for two-item arrays.

If we want to change this, we'd need to do it kind of now-ish. But from our side, it would require quite some careful change management to not break things in production.

**Comment by brian-brazil** [comment]
I'd suggest adding a url parameter that selects the output format, defaulting to the old format. At some point we can flip the default, and ultimately delete the old format.

**Comment by juliusv** [comment]
Actually it might be easier to change the query clients to support both formats for a while. Putting conditional switches into the nested JSON-marshaled types in the server would get complicated/inefficient.

This is a change which updates the format that the server produces:

https://github.com/prometheus/prometheus/compare/change-json?expand=1

For vectors, it looks like this:

```json
{
   "type" : "vector",
   "value" : [
      {
         "timestamp" : 1421765411.045,
         "value" : "65.475000",
         "metric" : {
            "quantile" : "0.5",
            "instance" : "http://localhost:9090/metrics",
            "job" : "prometheus",
            "__name__" : "http_request_duration_microseconds",
            "handler" : "/static/",
            "method" : "get",
            "code" : "304"
         }
      },
      {
         "timestamp" : 1421765411.045,
         "value" : "5826.339000",
         "metric" : {
            "quantile" : "0.9",
            "instance" : "http://localhost:9090/metrics",
            "job" : "prometheus",
            "__name__" : "http_request_duration_microseconds",
            "handler" : "prometheus",
            "method" : "get",
            "code" : "200"
         }
      },
      /* ... */
   ]
}
```

For matrices, it looks like this:

```json
{
   "type" : "matrix",
   "value" : [
      {
         "metric" : {
            "quantile" : "0.99",
            "instance" : "http://localhost:9090/metrics",
            "job" : "prometheus",
            "__name__" : "http_request_duration_microseconds",
            "handler" : "/static/",
            "method" : "get",
            "code" : "200"
         },
         "values" : [
            [
               1421765547.659,
               "29162.953000"
            ],
            [
               1421765548.659,
               "29162.953000"
            ],
            [
               1421765549.659,
               "29162.953000"
            ],
            /* ... */
         ]
      }
   ]
}
```

Does that look sane? I'll let it sit there in any case for a while because it needs some changes in the other components to be compatible with it.

**Comment by brian-brazil** [comment]
That looks sane to me.

**Comment by juliusv** [comment]
Updated to have a version number.
