### ISSUE TITLE
integrate annotations in ALERTS metric

### ISSUE THREAD

**Issue by MorphBonehunter** [prometheus/prometheus#3898]
For using the (templated) annotations from the alert rules in external Tools like Grafana it would be nice if the annotations are exporter not only to the alertmanager but are also accessible in the ALERTS Metric.

**Comment by brian-brazil** [comment]
This wouldn't work out, as annotations can vary from evaluation to evaluation so it'd cause cardinality issues. Annotations can only exist for long enough to send them to the alertmanager.

**Comment by MorphBonehunter** [comment]
Ok, i understand that. Maybe it make sense to still think about it for using the annotations outside the alertmanager. So at the moment the annotations are only usable outside prometheus and i would think it should be possible to use all "output" that prometheus produces als use inside prometheus (could be an wrong sight).
So maybe the ALERS Metric could be split to some smaler parts (maybe alert Group, or if this makes sense to per Rule) and include then the annotations?

**Comment by brian-brazil** [comment]
It doesn't make sense to have the annotations inside the tsdb at all, as they are event logging rather than metrics.

**Comment by MorphBonehunter** [comment]
But labels do? :smile: 
Whats the difference in this case? Don't get me wrong, but the annotations are something like the labels in this case.
So if this makes no sense, you can close this issue. I just thougt it might be an good idea...maybe i'm wrong :grin:

**Comment by brian-brazil** [comment]
Labels are the identify of an alert, if they're varying from evaluation to evaluation you have a problem.
