### ISSUE TITLE
promql needlessly imports "testing" which adds a bunch of needless flags

### ISSUE THREAD

**Issue by Dieterbe** [prometheus/prometheus#3915]
github.com/prometheus/prometheus/promql imports github.com/prometheus/prometheus/util/testutil which imports "testing".

the result is that any tool (3rd party) which imports github.com/prometheus/prometheus/promql imports testing, which if said tool uses flags, then a bunch of flags are added automatically by the testing package:
```
  -test.bench regexp
    	run only benchmarks matching regexp
  -test.benchmem
    	print memory allocations for benchmarks
  -test.benchtime d
    	run each benchmark for duration d (default 1s)
  -test.blockprofile file
    	write a goroutine blocking profile to file
  -test.blockprofilerate rate
    	set blocking profile rate (see runtime.SetBlockProfileRate) (default 1)
  -test.count n
    	run tests and benchmarks n times (default 1)
  -test.coverprofile file
    	write a coverage profile to file
  -test.cpu list
    	comma-separated list of cpu counts to run each test with
  -test.cpuprofile file
    	write a cpu profile to file
  -test.failfast
    	do not start new tests after the first test failure
  -test.list regexp
    	list tests, examples, and benchmarks matching regexp then exit
  -test.memprofile file
    	write a memory profile to file
  -test.memprofilerate rate
    	set memory profiling rate (see runtime.MemProfileRate)
  -test.mutexprofile string
    	write a mutex contention profile to the named file after execution
  -test.mutexprofilefraction int
    	if >= 0, calls runtime.SetMutexProfileFraction() (default 1)
  -test.outputdir dir
    	write profiles to dir
  -test.parallel n
    	run at most n tests in parallel (default 8)
  -test.run regexp
    	run only tests and examples matching regexp
  -test.short
    	run smaller test suite to save time
  -test.testlogfile file
    	write test action log to file (for use only by cmd/go)
  -test.timeout d
    	panic test binary after duration d (default 0, timeout disabled)
  -test.trace file
    	write an execution trace to file
  -test.v
    	verbose: print additional output
```

these flags are irrelevant and thus confusing.  they pollute help/usage messages for tools that don't invoke any testing logic.
as far as I know, only test code should actually import "testing"; not regular application code or libraries.

**Comment by fabxc** [comment]
This came up in the past. Remvoing the dependency was tricky for various reasons. 
We concluded that the right answer is to not use the global flag set.

**Comment by Dieterbe** [comment]
so, if the testing flags are not desired, apps should not define any global flags then?
That would be a bit painful for me, maybe i'll try to remove the testing flags out of the global flagset instead.

**Comment by fabxc** [comment]
> so, if the testing flags are not desired, apps should not define any global flags then?


Yes

**Comment by brian-brazil** [comment]
Do you have a proposal for disentangling this?

**Comment by Dieterbe** [comment]
me? no. realistically i won't have time to work on this. (if no one has, feel free to close this)

**Comment by brian-brazil** [comment]
We can put it down as something to consider as we develop a promql testing tool for users, but beyond that I don't think anyone is prioritising this.
