### ISSUE TITLE
Monitor the "ssl" and "ssl 2 way" with prometheus

### ISSUE THREAD

**Issue by fchiorascu** [prometheus/prometheus#3916]
**What did you do?**
Took a look on blackbox_exporter to observer the "ssl" possibility to obtain certificate information, but in my opinion are not so detailed.

**What did you expect to see?**
The possibility to onitor the "ssl 2 way" the certificate details per expiration, self-signed or not, security, if they have an intermediate certificate if the communication is permitted between to project componets communication between them based on 2 certificates in "ssl 2 way" approach.
Will you try to improve or to have something in the future?

<<**Feature request**>>

**Environment**
Dev/ Pre-Production / Production

* System information:
CentOS Linux release 7.3.1611 (Core)
Linux 3.10.0-514.6.2.el7.x86_64 x86_64

* Prometheus version:
2.0

* Alertmanager version:
-
* Prometheus configuration file:
-

* Alertmanager configuration file:
-
* Logs:
-

**Comment by brian-brazil** [comment]
This would be a feature request against the blackbox exporter, but I think you're really looking for a cert auditing tool which is not a goal of the blackbox exporter.

**Comment by fchiorascu** [comment]
I was looking on the internet and based on experience I m trying to have on prometheus something to really help on this matter doesn’t matter if is blackbox_exporter or not. In Centreon or Nagios I could check the certificate or some particularities in a nice view. What I consider and look here is to have in Prometheus something more complex based on the fact that I don’t want to use 3 tools to monitor a server. I want to have it all in prometheus. I don’t need an auditing tool only to know if this will be developed or not in Peometheus “detailed ssl”, “detailed ssl 2 way”, otherwise based in the needs I will choose another solution that covers this needs instead of Prometheus.

Kind regards,
