### ISSUE TITLE
Collect detailed metrics about Jenkins server itself and his activity with prometheus

### ISSUE THREAD

**Issue by fchiorascu** [prometheus/prometheus#3917]
**What did you do?**
I was searching for a proper way to collect the Jenkins "Global Build Stats" or some metrics in order to have a detailed Dashboard in Grfava that will cover all Jenkins activity.

**What did you expect to see?**
Jenkins itself: master node, slave node status/ health, version, cluster statistics, load statistics as: online executors/ busy executors/ available executors/ queue length, throughput, any other relevant info.
Builds: build time, status, health, build number, project, built on, last success, last duration, robot result, weather report, parallel builds, any other relevant info.
Pipeline: build time, status, health, build number, project, built on, last success, last duration, robot result, weather report, full stage view, parallel pipelines, any other relevant info.

<< **Feature request** >>

**What did you see instead? Under which circumstances?**

**Environment**

* System information:
CentOS Linux release 7.3.1611 (Core)
Linux 3.10.0-514.6.2.el7.x86_64 x86_64

* Prometheus version:
2.0

* Alertmanager version:
-
* Prometheus configuration file:
-

* Alertmanager configuration file:
-
insert configuration here (if relevant to the issue)
-

* Logs:
-
insert Prometheus and Alertmanager logs relevant to the issue here
-

**Comment by krasi-georgiev** [comment]
shouldn't this be against with the Jenkins exported that you are using?

**Comment by fchiorascu** [comment]
Hi,

There are few metrics there put in place based on what I've found on internet related to "Prometheus exporter for jenkins".
I need some guidance in order to cover all Jenkins KPIs needs related to what I've put on the top of the post.

**Jenkins -> monitor itself
Jenkins activity -> to monitor**
Jenkins itself: master node, slave node status/ health, version, cluster statistics, load statistics as: online executors/ busy executors/ available executors/ queue length, throughput, any other relevant info.
Builds: build time, status, health, build number, project, built on, last success, last duration, robot result, weather report, parallel builds, any other relevant info.
Pipeline: build time, status, health, build number, project, built on, last success, last duration, robot result, weather report, full stage view, parallel pipelines, any other relevant info.

Kind Regards,

**Comment by krasi-georgiev** [comment]
still all of this is related to the Jenkins exporter itself.

**Comment by fchiorascu** [comment]
Ok, I’ll test it and come back with a feedback.

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by fchiorascu** [comment]
I was entering there but is not so easy or intuitive also I was asking a question on the Community with no feedback. I think prometheus needs a really nice Community page where to track and interact in the true sense with people like Grafana, Elasticsearch or Influxdata pages.
