### ISSUE TITLE
DNS SD : target doesn't appears in Prometheus

### ISSUE THREAD

**Issue by Whiteire** [prometheus/prometheus#3925]
**What did you do?**
I configured a job with dns_sd_configs. When I use dig command with the domain name, I got some results :

`$ dig my.domain`

`;; ANSWER SECTION:`
`my.domain.             600     IN      A       XXX.XXX.XXX.XXX`
`my.domainc.             600     IN      A       XXX.XXX.XXX.XXX`
`my.domain.             600     IN      A       XXX.XXX.XXX.XXX`
`my.domain.             600     IN      A       XXX.XXX.XXX.XXX`
`my.domain.             600     IN      A       XXX.XXX.XXX.XXX`
`my.domain.             600     IN      A       XXX.XXX.XXX.XXX`
`my.domain.             600     IN      A       XXX.XXX.XXX.XXX`
`my.domain.             600     IN      A       XXX.XXX.XXX.XXX`
`my.domain.             600     IN      A       XXX.XXX.XXX.XXX`
`my.domain.             600     IN      A       XXX.XXX.XXX.XXX`

But when I put the same domain name in my job prometheus, I got no result in the prometheus interface. I'm not sure to understand well how it works.

**What did you expect to see?**
The targets should appear in Prometheus.

**What did you see instead? Under which circumstances?**
I can see my job but with no results.

**Environment**

* System information:

` $ uname -srm`
`Linux 2.6.32-642.13.1.el6.x86_64 x86_64`

* Prometheus version:
`prometheus-2.2.0`

* Prometheus configuration file:
`[...]`
`- job_name: xxx`
`  dns_sd_configs:`
`  - names:`
`    - my.domain`
`[...]`

Thanks for your help.

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
