### ISSUE TITLE
Migrate CircleCI to V2

### ISSUE THREAD

**Issue by tylerauerbeck** [prometheus/prometheus#3932]
The current version of config that Prometheus uses for CircleCI (V1) is being deprecated.

https://circleci.com/blog/sunsetting-1-0/

We should migrate this to use the V2 config prior to the deprecation date.

**Comment by krasi-georgiev** [comment]
yep , that is a good idea. Can you open a PR?

here is the commit that was done for the node_exporter , probably can do a lot of copy and paste form there.
https://github.com/prometheus/node_exporter/commit/65e485c4e926083c8cb4baf36a8d80d16a963421

**Comment by tylerauerbeck** [comment]
Yepp, no problem. I should have some time over the day or so to get something pulled together.

**Comment by sdurrheimer** [comment]
Some work are being done on CircleCI v2 on the node_exporter project. When they will be stabilized, we will do the move on all Prometheus projects.

**Comment by krasi-georgiev** [comment]
@sdurrheimer are you saying that it is best to wait until the one done in node_exporter is stable?

**Comment by sdurrheimer** [comment]
@krasi-georgiev It's probably better yes.

**Comment by simonpasquier** [comment]
Fixed by #4106
