### ISSUE TITLE
federation endpoint should include HELP/TYPE metadata

### ISSUE THREAD

**Issue by fche** [prometheus/prometheus#3935]
**What did you do?**

Started consuming /federate?match[]=  data by other tools, as though it were a normal prometheus-exporter format.

**What did you expect to see?**

HELP and TYPE metadata passed through from the upstream exporters.

**What did you see instead? Under which circumstances?**

Always
\# TYPE .... untyped

This makes the federation facility lossy in terms of information, especially with respect to summary/histogram types.

This was with prometheus 2.0.0

**Comment by brian-brazil** [comment]
This is as expected, and has always worked this way.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by fche** [comment]
Sorry - it did not seem like a "how to use" question but a problem.  I understand it's always worked this way.  Is the opinion that this is good and should stay that way?

**Comment by brian-brazil** [comment]
That is a complicated question. This is not what federation is for in any case, if you need this use the the text format parser directly on the targets.

**Comment by fche** [comment]
Federation could be useful if it federates (centralizes/abstracts) the targets.  Often one does not even have access to the individual targets (because they're on an isolated network vlan as in kubernetes).  To what extent would a higher-tier prometheus server be able to do all the same calculations on a federated data stream (sans metadata) as it could if it did reach the targets directly?

**Comment by brian-brazil** [comment]
https://www.robustperception.io/federation-what-is-it-good-for/
