### ISSUE TITLE
Show 'params' in Discovery UI

### ISSUE THREAD

**Issue by Jean-Daniel** [prometheus/prometheus#3945]
**Feature request**
I have a couple of prometheus scrape_configs that use relabeling to create target param (blackbox exporter, …)

While the new Discovery UI is invaluable to see the result of relabeling for target label, it would also be very helpful to get the value of other value generated by the relabeling like final __address__ value and also __param_xxx values.

**Comment by brian-brazil** [comment]
Params are clearly shown with other information like address in the Endpoint column.
