### ISSUE TITLE
Adopt DCO

### ISSUE THREAD

**Issue by caniszczyk** [prometheus/prometheus#3947]
To graduate a project from CNCF, they must adhere to the CNCF IP Policy which involves adopting a DCO: https://github.com/apps/dco

I suggest Prometheus slowly adopt this over the next month or so, experiment first with node_exporter

**Comment by caniszczyk** [comment]
cc: @juliusv @brian-brazil

**Comment by krasi-georgiev** [comment]
@caniszczyk  the DCO app is now enabled across the entire organisation. 
Is there anything else we need to do or can close this as resolved?

**Comment by brian-brazil** [comment]
This is done.

**Comment by grobie** [comment]
@brian-brazil I believe we actually need to mention the DCO and at least link to https://developercertificate.org/ from all of our CONTRIBUTING.md files, otherwise the signed-off tag is meaningless.

**Comment by simonpasquier** [comment]
Closed by #4211 regarding the Contributing guide.
