### ISSUE TITLE
Magic number in the code

### ISSUE THREAD

**Issue by zjwzte** [prometheus/prometheus#3955]
I find a magic number `163` here:

https://github.com/prometheus/prometheus/blob/ef567ceb7dfab609dda4328ff6eeddb58d90493d/scrape/scrape.go#L151

@fabxc I notice that you wrote the original code. Could you please explain a bit about this number? I guess `163` might be a typo and it should be `1e3`. If so, I'd like to sent a patch to fix it :)

**Comment by fabxc** [comment]
Yea, that's a typo and was supposed to be `1e3` similar to the second argument.

**Comment by zjwzte** [comment]
@fabxc thanks for confirmation! PR https://github.com/prometheus/prometheus/pull/3968 sent :)
