### ISSUE TITLE
scraping node-exporter: "proto: can't skip unknown wire type 6 for io_prometheus_client.MetricFamily"

### ISSUE THREAD

**Issue by discordianfish** [prometheus/prometheus#397]
Hi,

I'm running prometheus with those dependencies/versions:
- prometheus: 034f6bb2be8c047e1685e14c5d9e5a722ed3d392
- client_golang: 23e5e5fefd61ab1fce08080eb640956a70786856
- client_model: 775af9440e07a658e13f699448c745367bc12115

And 6 node exporters with those:
- node-exporter: 053db591224505c18b5b3cd996bb90ed40eaee4c
- client_golang: 457bc47eacdc954882e72bc81968061b5ca750a3
- client_model: 775af9440e07a658e13f699448c745367bc12115

For one node-exporter I get this error in prometheus after node-exporter runs some time: `proto: can't skip unknown wire type 6 for io_prometheus_client.MetricFamily' from node-exporter`.
This happens on only this one so far, even though they are docker containers and therefor the environment is the same for all of them. I'll update node-exporter so they all run the same client_golang version but if there is something relevent different I would expect all exporters to fail.

**Comment by garbamoussa** [comment]
Hi all,

I have integrated an ARIMA forecast into kapacitor by udf.

It starts and works fine, calculates forecast for each batch and writes back to influx. But always after 6 batches it stops writing, throwing error:

read error: proto: can’t skip unknown wire type 7 for agent.Response

Looking at the series that it should write, its not any different in batch 7. So i really have no idea.

Has anyone seen a similar error? Any idea how to start debugging?

Thanks a lot
