### ISSUE TITLE
Improve staleness handling

### ISSUE THREAD

**Issue by brian-brazil** [prometheus/prometheus#398]
Currently prometheus considers a timeseries stale when it's got no data points more recent than 5m (configurable).

This causes dead instances' data to hang around for longer than it should, makes less often scrape intervals difficult, makes advanced self-referential use cases more difficult and   prevents the timestamp propagating from the push gateway.

I propose that we consider a timeseries stale if it wasn't present in the most recent scrape of the target we get it from.

**Comment by brian-brazil** [comment]
I was just thinking there from the rate discussion, and have a sketch of a solution.

The two basic cases we want to solve are:

1.  If a pushgateway exports a sample with a timestamp, it should be considered fresh for as long as it exported.
2. If a target scrape fails or a target is removed, we no longer want to consider it's time series fresh. This is the `sum(some_gauge)` case.

In addition we want something that'll produce the same results now as back in time, and across Prometheus restarts.

My idea is to add two new values that a sample can have: "fresh" and "stale". These would be persisted like normal samples, but not directly exposed to users.

When we get a scrape with timestamps set on sample we don't have, we'd add a sample for the exported value, and a 2nd one with the "fresh" value and the scrape time. If we get a sample we already have, then we add a new sample with the "fresh" value and scrape time. When querying for a given time with an instant selector, if we get a "fresh" then we walk back until we get the actual sample. For a range selector we'd ignore that sample.

When a scrape fails, a evaluation no longer produces certain timeseries or a target is removed we'd add in a "stale" on all affected time-series. For an instant selector if the first sample we hit is stale, we stop and return nothing. For a range selector we'd ignore the stale samples, and return the other samples as usual (irate needs special handling here as it's more instant in semantics - could we change it to an instant selector?, and we'll need to be careful with SD blips).


There's various corner cases and details to be worked out, but this seems practical and has the right semantics.

**Comment by beorn7** [comment]
> When a scrape fails, a evaluation no longer produces certain timeseries or a target is removed we'd add in a "stale" on all affected time-series.

I believe the actual challenge in staleness handling is to identify which time-series are "affected" in the above sense. To do that, we needed to track which target exported which time-series in their respective last scrape. All the updates and lookups required are not trivial to get right and fast, especially in a highly concurrent, high throughput scenario.

**Comment by brian-brazil** [comment]
> My idea is to add two new values that a sample can have: "fresh" and "stale". These would be persisted like normal samples, but not directly exposed to users.

As an implementation idea, it appears that there are `2^52 - 1` ways to represent NaN in float64, so with some trickery we could encode this information plus an actual NaN using that fact. This would avoid the need to add metadata of some form to the chunk. This cloud also presumably be propagated to long term storage.

There is of course the question of if float64 implementations are "NaN-clean", or if we'd have to handle that ourselves in some cases.

**Comment by DanyC97** [comment]
@brian-brazil is any traction on this issue? Asking as i'm in process of evaluating/ moving from influxDb but this issue is a bit of a blocker

Thanks and great job!

**Comment by brian-brazil** [comment]
There's a hint that we'll do some of the plumbing for this for other reasons, but as this is a major breaking change it'll be at least 2.0 before this happens.

**Comment by octo** [comment]
Sorry for an uninformed question: have you considered storing the scrape interval in `type Sample`, just like the timestamp? That allows you do easily determine if a given Sample is stale and you don't have to track which target used to provide which metric.

**Comment by brian-brazil** [comment]
I don't think that would help, as it doesn't tell you about scrapes that didn't happen or targets appearing/disappearing.

**Comment by redbaron** [comment]
just a thought, is it possible to invert problem and let target being scraped to optionally report difference since last scrape?

**Comment by brian-brazil** [comment]
That brings with it all sorts of problems (http://www.robustperception.io/how-does-a-prometheus-counter-work/), and I don't see a way it helps with the issue at hand.

**Comment by redbaron** [comment]
@brian-brazil I meant not a difference in values, but difference in metrics set, so that central server doesn't need to track which metrics are gone

**Comment by brian-brazil** [comment]
That has similar issues to the difference in values, as the client needs to track scrapes.

**Comment by szxnyc** [comment]
@brian-brazil 

Where is the "staleness configuration" for a timeseries? You mention that it's 5m by default and configurable. I have a system that, currently, can only be scrapped every 4 hours and I want my graphs to have valid data-points for up to that time without gaps.

**Comment by beorn7** [comment]
@szxnyc The flag is `--query.staleness-delta``.

**Comment by brian-brazil** [comment]
https://docs.google.com/document/u/1/d/1ordTPfUSaGvaBolUGeLChATwgc1xUhUxfUhudYoOeMw/edit is a proposal for how to handle this.

**Comment by brian-brazil** [comment]
The base form of this is in place for scrapes in the dev-2.0 branch if ye'd like to try it out.

**Comment by AndreaGiardini** [comment]
@brian-brazil Can you build a new alpha release in order to test it?

**Comment by fabxc** [comment]
@AndreaGiardini sync'd with @brian-brazil again and we concluded the amount of fixes and new experimental features justifies another alpha.
Release is already in progress.

**Comment by WIZARD-CXY** [comment]
looking forward to the new release

**Comment by brian-brazil** [comment]
Remaining core staleness work is now all out for review.

**Comment by brian-brazil** [comment]
This is all implemented in 2.0 with the pgw changes just awaiting a release. Still need docs, but that'll happen with the rest of 2.0 docs.

**Comment by alok87** [comment]
@brian-brazil I used prometheus/cloudwatch_exporter with below config to collect data for `SQS` metric. This data takes more than 10mins to refresh (`localhost:9106/metrics`). Please suggest how can i avoid this.

**Comment by alok87** [comment]
The above was because of the cloudwatch gets updated with latest data every 5mins. Also i changed the delay_seconds to 10seconds in cloudwatch_exporter. Now the data gets refreshed in max 5mins.
