### ISSUE TITLE
Add function to support replacing label values like regexp.ReplaceAllString

### ISSUE THREAD

**Issue by Wing924** [prometheus/prometheus#3997]
have a metrics like `resp_time_sum{vip="www_example_com"}`.
I want to replace `_` with `.` in vip label: `resp_time_sum{vip="www.example.com"}`

Currently, `label_replace` function can't do this because we can't know how many `_` the value contains.
I asked this question in [prometheus-users](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/prometheus-users/6aOUfyRoSb4/UC1PiASvBQAJ), but the suggest rename label in exporters.

Because we can't always change the exporters, I think add a new function `label_gsub` may be useful.

```
# dst_label = regex.ReplaceAllString(src_label, replacement)
label_gsub(v instant-vector, dst_label string, replacement string, src_label string, regex string)
```
*gsub come from ruby's [gsub](https://apidock.com/ruby/String/gsub)*

**Comment by brian-brazil** [comment]
This sort of thing is best fixed in your source data. Regexes in PromQL are anchored, which are not compatible with global replacements.
