### ISSUE TITLE
--web.route-prefix doesn't work as expected

### ISSUE THREAD

**Issue by beorn7** [prometheus/prometheus#4004]
**What did you do?**

Ran prometheus with `--web.route-prefix=/prefix`

**What did you expect to see?**

All paths prefixed with `/prefix`

**What did you see instead? Under which circumstances?**

- `http://localhost:9090/prefix` redirects to `http://localhost:9090/graph`, which obviously doesn't work.
- Typing `http://localhost:9090/prefix/graph` explicitly still has little success because all the `/static/` resources are not prefixed.

* Prometheus version:

prometheus, version 2.2.0 (branch: master, revision: 60dafd425cdc96f7df3019cf756998b42209cf1d)
  build user:       bjoern@reasonableresolution
  build date:       20180323-15:46:34
  go version:       go1.10

**Comment by brian-brazil** [comment]
#4025 was not the right fix for this. Can you indicate what the external URL was in this case?

**Comment by abh** [comment]
It seems like the original problem here would have been fixed by using external-url instead of route-prefix.

**Comment by juliusv** [comment]
Has this been fixed in https://github.com/prometheus/prometheus/pull/4256 now?

**Comment by roidelapluie** [comment]
I think this can be closed @juliusv @beorn7

**Comment by beorn7** [comment]
I'd assume so. But I got repeatedly confused by the behavior in the past, so it would be good if somebody else could confirm.

**Comment by roidelapluie** [comment]
I confirm that it works as expected and that in most cases you want external.url.

This behavious was even revisited recently for the new UI: https://github.com/prometheus/prometheus/issues/6163

**Comment by beorn7** [comment]
OK, closing then…
