### ISSUE TITLE
Service Discovery for Kubernetes API Server

### ISSUE THREAD

**Issue by nsauro** [prometheus/prometheus#4016]
As per the [documentation](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#%3Ckubernetes_sd_config%3E) on `kubernetes_sd_configs`

```
# The API server addresses. If left empty, Prometheus is assumed to run inside
# of the cluster and will discover API servers automatically and use the pod's
# CA certificate and bearer token file at /var/run/secrets/kubernetes.io/serviceaccount/.
```
My use case is that I'm running Prometheus outside of the Kubernetes Cluster that it is monitoring(for fear that if the cluster goes haywire, it doesn't bring down our eye and ears with it).  It would be nice to be able to use some kind of SD mechanism to find the API servers vs hardcoding in a list of servers.

Thanks!

**Comment by brian-brazil** [comment]
I don't think that multiple layers of SD would be sane to support. In such a setup you should have DNS which you can use for this.

**Comment by nsauro** [comment]
Yea..we are using that currently, but was hoping to use ec2 or some other sd to help reduce the amount of differences in configurations between environments.  

Right now, our dns entries are different due to the different environments(and I cannot get dns search suffixing to work for whatever reason), which causes us to have to do some config management to generate configs for each env.  


Thanks anyway.

**Comment by brian-brazil** [comment]
You need configuration management to generate different configs for each Prometheus anyway as they all should have different external labels.
