### ISSUE TITLE
Use UnmarshalStrict for yaml Unmarshalling

### ISSUE THREAD

**Issue by krasi-georgiev** [prometheus/prometheus#4017]
The yaml library we are using now support `UnmarshalStrict` which will return an error for for unknowns, or double definitions
https://godoc.org/gopkg.in/yaml.v2#UnmarshalStrict

After start using `UnmarshalStrict` `CheckOverflow` will be no longer needer
https://github.com/prometheus/prometheus/blob/dfd6709a44eb4a809c41b6676500b8b4ccfd9af1/util/yaml/yaml.go#L22-L31

**Comment by RichiH** [comment]
Related to https://github.com/prometheus/prometheus/issues/1275 and as per IRC< @fabx said: "I still think we should be using https://github.com/ghodss/yaml "

**Comment by krasi-georgiev** [comment]
so basically if the other devs agree, replace `gopkg.in/yaml` with `ghodss/yaml` or just add PR to use `UnmarshalStrict`

**Comment by grobie** [comment]
Does ghodss/yaml handle YAML anchors?

**Comment by fabxc** [comment]
It uses the same YAML library but just performs a conversion to JSON, which
is then parsed through the much saner encoding/json.

**Comment by brian-brazil** [comment]
I still fail to see the benefits of switching the data to a format that's not the one we're trying to parse.
