### ISSUE TITLE
Use only one CI tool rather than two 

### ISSUE THREAD

**Issue by sichvoge** [prometheus/prometheus#4022]
Currently, the Prometheus project is using two different CI tools (CircleCI and Travis). I understand that there were reasons to do that such as Travis is much faster running tests but it did not support Docker in the past. Hence, CircleCI was introduced.

But as Travis added support for Docker, shouldn't we only one? I know that there is probably no harm on running two, but managing a single CI process is probably easier. If that makes sense, I'd be happy to help migrating.

cc/ @brancz

**Comment by krasi-georgiev** [comment]
I have a proposal coming in 1-2 days for  https://github.com/drone/drone 
As part of the new prombench and e2e CI tests that we are working on Drone can also be used to combine all steps in circle and travis so will post a link here if you want to join the discussion.

**Comment by krasi-georgiev** [comment]
yes, I am aware, thanks. 
I have looked through all build steps.

**Comment by krasi-georgiev** [comment]
lets continue the discussion in
https://groups.google.com/forum/#!topic/prometheus-developers/8Qs5H_aQDX4
