### ISSUE TITLE
query api

### ISSUE THREAD

**Issue by lurenjia528** [prometheus/prometheus#4024]
@fabxc
@brian-brazil
why I use java to search prometheus (send two requests continuously),it return me the same result,my queryUrl's parameter "time" is not     

http://192.168.17.55:8082/api/v1/query?query=net_bytes_recv{host="master1"}&time=1522290775
{responseData={"status":"success","data":{"resultType":"vector","result":[{"metric":{"__name__":"net_bytes_recv","exported_host":"master1","host":"master1","instance":"192.168.17.55:9126","job":"telegraf@55"},"value":**[1522290775,"1705132704882"]**}]}}, responseCode=200}
http://192.168.17.55:8082/api/v1/query?query=net_bytes_recv{host="master1"}&time=1522290770
{responseData={"status":"success","data":{"resultType":"vector","result":[{"metric":{"__name__":"net_bytes_recv","exported_host":"master1","host":"master1","instance":"192.168.17.55:9126","job":"telegraf@55"},"value":**[1522290770,"1705132704882"]**}]}}, responseCode=200}
http://192.168.17.55:8082/api/v1/query?query=net_bytes_sent{host="master1"}&time=1522290775
{responseData={"status":"success","data":{"resultType":"vector","result":[{"metric":{"__name__":"net_bytes_sent","exported_host":"master1","host":"master1","instance":"192.168.17.55:9126","job":"telegraf@55"},"value":**[1522290775,"504077178478"]**}]}}, responseCode=200}
http://192.168.17.55:8082/api/v1/query?query=net_bytes_sent{host="master1"}&time=1522290770
{responseData={"status":"success","data":{"resultType":"vector","result":[{"metric":{"__name__":"net_bytes_sent","exported_host":"master1","host":"master1","instance":"192.168.17.55:9126","job":"telegraf@55"},"value":**[1522290770,"504077178478"]**}]}}, responseCode=200}

I use python ,the result is  same
import urllib.request
import time
tt = time.time()
tt1 = tt-5
url = 'http://192.168.17.55:8082/api/v1/query?query=net_bytes_recv{host="master1"}&time=' +str(tt)
get = urllib.request.urlopen(url).read()
print(get.decode('utf-8'))
url = 'http://192.168.17.55:8082/api/v1/query?query=net_bytes_recv{host="master1"}&time=' + str(tt1)
get = urllib.request.urlopen(url).read()
print(get.decode('utf-8'))

the result:
{"status":"success","data":{"resultType":"vector","result":[{"metric":{"__name__":"net_bytes_recv","exported_host":"master1","host":"master1","instance":"192.168.17.55:9126","job":"telegraf@55"},"value":**[1522298340.57,"1706462520784"**]}]}}
{"status":"success","data":{"resultType":"vector","result":[{"metric":{"__name__":"net_bytes_recv","exported_host":"master1","host":"master1","instance":"192.168.17.55:9126","job":"telegraf@55"},"value":[**1522298335.57,"1706462520784"**]}]}}

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
