### ISSUE TITLE
Allow basic authentication credentials to reside inline with target URL

### ISSUE THREAD

**Issue by asaf400** [prometheus/prometheus#4026]
**What did you do?**

I attempted to use relabel_config to modify a kubenetes service discovery targets ('kubernetes-service-endpoints'),
so that a basic auth protected target could be read, while the credentials are dynamic and are part of the source labels.. 

For my point of view (after reading all the docs I could find),
there are only two options:

1.
Given the following source labels (before labels):
[__address__, __meta_some_port, meta_username, meta_password]
where values are [192.168.1.104:80;1936;admin;PasSw0rd;]
this regex '(.+)(?::\d+);(\d+);(\w+);(\w+)'
this replacement: '$3:$4@$1:$2'
would produce a valid http url:
http://admin:PasSw0rd@192.168.1.104:1936/metrics
with __address__ as:
admin:PasSw0rd@192.168.1.104:1936
and __scheme__ as the default 'http', as well as __metrics_path__ as the default '/metrics'

the complete address works perfect in curl, but not in prometheus..

**What did you expect to see?**

For method 1, I expected prometheus to scrape the targets with the provided inline basic auth credentials..

**What did you see instead? Under which circumstances?**

Target Error Column shows:
' parse http://admin:PasSw0rd**%40**192.168.1.104:1936/metrics: invalid URL escape "%40"'

%40 is the @ in Hex on the Ascii table..

Seems prometheus is unable (not ready \ not implemented) to parse basic authentication credentials inline with the __address__, and with that conclusion I want to suggest a feature:

Either enable method 1 to work, by correctly parsing both regular addresses and basic auth inline addresses..

or enable method 2 which is:
respect a new 'meta label', where there are currently '__address__ ', '__scheme__', '__metricspath__'
I suggest adding '__username__' and '__password__', which would be used as credentials

**Environment**
prometheus 2.2.1 on RHEL7 - pod ontop openshift 3.6 (k8s 1.6)

* Prometheus version:

prometheus 2.2.1 HEAD rev=bc6058c8127a..........

**Comment by brian-brazil** [comment]
This is explicitly not supported, you need to put it in the scrape_config.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by asaf400** [comment]
@brian-brazil Thanks, I though so too that this is more of a question then an issue, however i posted here anyways in light of the fact that this a limitation of prometheus, and should be considered as a feature request..

However I just found out that my mentioned 2nd method is actually implemented?
https://github.com/mrsiano/openshift-grafana/blob/master/prometheus-high-performance.yaml#L292

Will attempt that...

**Comment by nickle-ye** [comment]
hi, I have encountered the save issue.

 Is there any chance that I can dynamic set up the auth info from the label info of target instead of hard code on the scrape_config?

As different target would need individual basic account, the common one won't be worked.
