### ISSUE TITLE
Listening on wrong addresses

### ISSUE THREAD

**Issue by lgierth** [prometheus/prometheus#4036]
**What did you do?**
Start prometheus with `--web.listen-address=127.0.0.1:9090`
```sh
> ps aux | grep prom
prometh+ 27719  339  1.0 5369168 700096 ?      Ssl  06:22   0:47 /usr/bin/prometheus --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/var/lib/prometheus --web.console.libraries=/etc/prometheus/console_libraries --web.console.templates=/etc/prometheus/consoles   --web.listen-address=127.0.0.1:9090
```

**What did you expect to see?**
Expected to see it listen on IPv4 localhost. I also semi-expected it to generally listen on localhost only by default.

**What did you see instead? Under which circumstances?**
It listens on IPv6 all-hosts (`::`), and prints IPv4 all-hosts.
```sh
> netstat -nlp | grep 9090
tcp6       0      0 :::9090                 :::*                    LISTEN      26163/prometheus
> journalctl -xe | grep prom | grep -i listening
Apr 02 05:55:47 myhost.net prometheus[26163]: level=info ts=2018-04-02T03:55:47.963398278Z caller=web.go:382 component=web msg="Start listening for connections" address=0.0.0.0:9090
```

With `--web.listen-address=localhost:9090` and `--web.listen-address=[::1]:9090` it also reports listening on 0.0.0.0, and listens on the same IPv6 all-hosts (instead of localhost), ~~but only responds with 503~~ (I think the 503 might be unrelated).

**Environment**

* System information:

	Linux 4.13.0-36-generic x86_64

* Prometheus version:

```
prometheus, version 2.2.1 (branch: master, revision: bc6058c81272a8d938c05e75607371284236aadc)
  build user:       root@myhost.net
  build date:       20180326-06:31:27
  go version:       go1.10
```

* Alertmanager version:

	n/a

* Prometheus configuration file:
```
---
global:
  scrape_interval:     15s
  scrape_timeout:      10s
  evaluation_interval: 60s

```

* Alertmanager configuration file:
```
n/a
```

* Logs:
```
Apr 02 05:55:47 myhost.net prometheus[26163]: level=info ts=2018-04-02T03:55:47.963398278Z caller=web.go:382 component=web msg="Start listening for connections" address=0.0.0.0:9090
```

**Comment by brian-brazil** [comment]
This is a Linux internal thing, nothing to do with Prometheus.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by lgierth** [comment]
For the record, I moved `--web.listen-address` to the front and it now correctly binds to localhost only, i.e.

```
> /usr/bin/prometheus --web.listen-address=127.0.0.1:9090 --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/var/lib/prometheus --web.console.libraries=/etc/prometheus/console_libraries --web.console.templates=/etc/prometheus/consoles   --web.route-prefix=/prometheus
```
instead of
```
> /usr/bin/prometheus --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/var/lib/prometheus --web.console.libraries=/etc/prometheus/console_libraries --web.console.templates=/etc/prometheus/consoles   --web.listen-address=127.0.0.1:9090
```

**Comment by brian-brazil** [comment]
That shouldn't make the slightest difference.

**Comment by lgierth** [comment]
Yes, *actually* it turned out it was an orphaned doublequote somewhere in the systemd unit file, which apparantly made the arguments *look* correct, but actually get cut off.
