### ISSUE TITLE
Feature request: gRPC scraping

### ISSUE THREAD

**Issue by sdotz** [prometheus/prometheus#4039]
We have a lot of gRPC services at The New York Times. It would be great to be able to scrape gRPC endpoints that provide a standard protocol buffer format. Our services are just gRPC and thus we prefer not to have an extra http/1 service running on each app.

Has any work or proposal been done on this? Anyone else interested in this?

**Comment by brian-brazil** [comment]
We offer only HTTP scraping, as we only want to have to support one way to do a particular thing. If you need gRPC you are free to implement it via proxy_url.
