### ISSUE TITLE
Add "Open Graph in new tab" option

### ISSUE THREAD

**Issue by RichiH** [prometheus/prometheus#4045]
During exploratory analysis, we often open several windows to compare side-by-side. Instead of copy & pasting queries, and re-executing potentially expensive queries, it would be simpler to be able to open the same graph in a new tab.

Ideally, this link would be sitting next to `Remove Graph` in the lower right.

I am torn on if it would be better to duplicate or move the graph into a new tab; I would tend towards copying.

**Comment by brian-brazil** [comment]
I'm not sure it's worth cluttering the UI with a button just for this. Personally I duplicate the tab when I want to do this.

**Comment by beorn7** [comment]
Hello from the bug scrub.

Given that nobody has commented on this in six years, and nobody has started to work on this, we'll close this.
