### ISSUE TITLE
Config mismatch

### ISSUE THREAD

**Issue by dbluxo** [prometheus/prometheus#4051]
**What did you do?**

Compare prometheus.yml config with the loaded prometheus config in ui `https://prometheus-url/config`

**What did you expect to see?**

Config in prometheus.yml is the same as the shown config in prometheus ui

**What did you see instead? Under which circumstances?**

Config mismatch, example:

In prometheus.yml:

```      
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
```

Loaded config shown in prometheus ui:

```
  - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
    separator: ;
    regex: (.+)
    target_label: __metrics_path__
    replacement: $1
    action: replace
```

**Environment**

We are using prometheus 2.2.1 inside kubernetes.

* System information:

  Linux 4.9.75-rancher x86_64

* Prometheus version:

  prometheus, version 2.2.1 (branch: HEAD, revision: bc6058c81272a8d938c05e75607371284236aadc)
  build user:       root@149e5b3f0829
  build date:       20180314-14:15:45
  go version:       go1.10

**Comment by brian-brazil** [comment]
This is expected, to hide secrets we need to marshall and unmarshall the config so you end up seeing all the defaults.
