### ISSUE TITLE
Debounce timerange setting changes

### ISSUE THREAD

**Issue by juliusv** [prometheus/prometheus#406]
After pressing any of the buttons that cause timerange changes, we should wait a short amount of time before updating the graph. That way, if the user presses the button multiple times, we don't load every intermediate result immediately.

**Comment by juliusv** [comment]
> The way I did this on a different UI was only to allow one request to be in progress at a time, and wait for the result to come back (and discarded) before sending of the newest request.

This isn't ideal here, because we want users to be able to rapidly select a time range, while skipping over intermediary values which shouldn't immediately trigger a query and block results for the finally settled-on range. So I'd just do a normal debounce here (like 250ms or so) on the value from the input field, before triggering a query.

**Comment by adrijshikhar** [comment]
I would like to work on this issue. I am new to the open-source world.

**Comment by juliusv** [comment]
@adrijshikhar Sounds good to me! Let me know if you need any pointers. Generally the file in question will be https://github.com/prometheus/prometheus/blob/master/web/ui/react-app/src/pages/graph/TimeInput.tsx.

**Comment by adrijshikhar** [comment]
> @adrijshikhar Sounds good to me! Let me know if you need any pointers. Generally the file in question will be https://github.com/prometheus/prometheus/blob/master/web/ui/react-app/src/pages/graph/TimeInput.tsx.

Thanks for this. I will get right on it.

**Comment by Marvin9** [comment]
@juliusv Since it was inactive for so long, I made a PR without notifying here. I hope it is fine
