### ISSUE TITLE
Build UI for displaying and exploring timeseries dimensionality

### ISSUE THREAD

**Issue by juliusv** [prometheus/prometheus#407]
There should be UI support for dimensional exploration of data. When providing an expression / metric name, the UI could show the user a summary of the selected data in terms of label names and their possible values, then allow the user to further narrow down results based on that. This could either be completely client-side and based on returned query data, or with some more fancy server-side support which can figure out dimensionality of metrics without actually loading all the data for them. What exactly this should look like needs to be defined.

**Comment by Gouthamve** [comment]
Would something like this work: https://github.com/kausalco/public/tree/master/promvt

/cc @davkal

**Comment by brian-brazil** [comment]
I don't think it needs to be a full UI, even a page with tables for the biggest metrics and jobs would be handy.

**Comment by brian-brazil** [comment]
We've the basics now in the UI, and there's the tsdb analyze tool too.
