### ISSUE TITLE
Consul service discovery across all datacenters

### ISSUE THREAD

**Issue by sev3ryn** [prometheus/prometheus#4070]
**Feature request:**

Right now you have to add multiple scrappers with consul service discovery if you have more than one Consul datacenters(one scrapper per one DC).  
I suggest to add ability to autodiscover Consul datacenters and aferwards to discover services to be scrapped for each DC.

I'm happy to implement this but first I want to know your opinion on following questions:

1. Does this feature request not contradict Prometheus philosophy?
2. Right now if consul_sd_configs.datacenter field is omitted - it uses local Consul DC. I suggest not to conflict with this functionality and add additional field dc_discovery:(true|false). Your thoughts?
@brian-brazil @iksaif

**Comment by brian-brazil** [comment]
The Prometheus design is that you would have one Prometheus per failure domain/datacenter, so it doesn't make sense to scrape all services in all datacenters. If you need this you can always list your datacenters in the config file.
