### ISSUE TITLE
support marathon basic auth (Bearer) 

### ISSUE THREAD

**Issue by adamdecaf** [prometheus/prometheus#4074]
Following from https://github.com/prometheus/prometheus/issues/3090 there's no support for `Authorization: Basic ...` with marathon, which is what non DC/OS installs use. 

Part of the `auth_token` changes mention this: https://github.com/prometheus/prometheus/commit/2aba238f3145ec80348fa4288af607f728b08dd1

> Existing configuration files that use the bearer token will no longer work. More work is required to make this backwards compatible.

Even before the `auth_token[_file]` changes this wouldn't have worked. 

https://github.com/prometheus/prometheus/blob/v2.2.1/discovery/marathon/marathon.go#L300-L305

**Comment by brian-brazil** [comment]
This was added in #4009.

**Comment by adamdecaf** [comment]
In specific the code here didn't seem to work for me. I need an auth header like `Authorization: Basic ...`. 

> `request.Header.Set("Authorization", "token="+string(rt.authToken))`

**Comment by adamdecaf** [comment]
What I'm seeing is that the auth plugin we use needs `Basic ...`, which prometheus doesn't seem to allow.

```java
    public static AuthKey authKeyFromHeaders(HttpRequest request) throws Exception {
        Option<String> header = request.header("Authorization").headOption();
        if (header.isDefined() && header.get().startsWith("Basic ")) {
            String encoded = header.get().replaceFirst("Basic ", "");
            String decoded = new String(Base64.getDecoder().decode(encoded), "UTF-8");
            String[] userPass = decoded.split(":", 2);

            return AuthKey.with(userPass[0], userPass[1]);
        }
        return null;
    }
```

https://github.com/ContainX/marathon-ldap/blob/master/src/main/java/io/containx/marathon/plugin/auth/util/HTTPHelper.java#L19

**Comment by plaflamme** [comment]
Ah, ok. That's because you need your config to use a `basic_auth` block as described in the updated documentation https://github.com/prometheus/prometheus/blob/master/docs/configuration/configuration.md#marathon_sd_config

**Comment by adamdecaf** [comment]
Oh ok. The commits made it seem like basic/bearer auth were removed. Are they going to be around for a while? We're not going to use DC/OS. 

Thanks. I'll try building a docker image from master locally with `bearer_token_file`.

**Comment by plaflamme** [comment]
@adamdecaf basic auth was not supported before #4009. Supporting it is what motivated the change.

All authentication methods should be supported in the long run. I suspect the `auth_token` method will be dropped if / when `DC/OS` moves to the more standard `bearer_token` authentication.

**Comment by adamdecaf** [comment]
Perfect, thanks!

**Comment by adamdecaf** [comment]
@brian-brazil @plaflamme Would y'all accept a `basic_auth_file` PR? I want to keep the basic auth params in a kubernetes `Secret`.

**Comment by brian-brazil** [comment]
I wouldn't accept a file that contains basic auth details as that'd make debugging harder be making the username not available in the UI, if we were to accept it it would have to contain no more than the raw password.

**Comment by adamdecaf** [comment]
@brian-brazil Sounds good to me. `basic_auth_password_file`?
