### ISSUE TITLE
Automatically choose graphing resolution based on number of timeseries

### ISSUE THREAD

**Issue by juliusv** [prometheus/prometheus#409]
Implement the ability in the Prometheus server to automatically limit the total number of data points returned for a range query by autoscaling the number of data points per timeseries based on how many timeseries are involved in total.

**Comment by brian-brazil** [comment]
I don't think this is likely to happen, and it would likely cause confusion by trying to 2nd guess the user. If a query is too expensive to run, we should hard-fail.
