### ISSUE TITLE
Have the last configuration reload time in Status tab 

### ISSUE THREAD

**Issue by lparet-yseop** [prometheus/prometheus#4099]
Hi everyone,

I think it can be usefull for people using Prometheus and AlertManager reload to have the information of the last configuration reload. 
In my case, I use reload after pushing a new configuration. So it will be interesting to verify directly in the Prometheus (and AlertManager) UI the last reload. I know we can see the configuration content but if my file has a lot of lines it's difficult to find what I want...

For example:
In Status > Runtime Information for Prometheus
In Status > Status for AlertManager

Let me know what you think about that

**Comment by krasi-georgiev** [comment]
prometheus provides this via the 
`prometheus_config_last_reload_successful` metrics
that should work for you?

**Comment by brian-brazil** [comment]
Already added in #3921

**Comment by krasi-georgiev** [comment]
Nice!, I missed that one.
