### ISSUE TITLE
Error scraping kubernetes apiserver endpoints  in minikube with example prometheus configuration

### ISSUE THREAD

**Issue by yunlzheng** [prometheus/prometheus#4120]
## Proposal
**Use case. Why is this important?**

*Nice to have' is not a good use case :)*

## Bug Report
**What did you do?**

```
# From Example
kubectl create -f prometheus-rbac-setup.yml 

# From Example
kubectl create configmap prometheus --from-file=prometheus.yml=kubernetes-prometheus.yml 

# This is my custom file
kubectl create -f prometheus-deployments.yml 
```

**What did you expect to see?**

Prometheus can discovery the kubernetes-apiservers，kubernetes-cadvisor and kubernetes-nodes targets and success scraping metrics data

**What did you see instead? Under which circumstances?**

![](http://7pn5d3.com1.z0.glb.clouddn.com/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202018-04-28%20%E4%B8%8B%E5%8D%883.57.21.png)

The target kubernetes-apiservers scraping error with messahe:

```
Get https://10.0.2.15:8443/metrics: x509: certificate is valid for 192.168.99.100, 10.96.0.1, 10.0.0.1, not 10.0.2.15
```

**Environment**

* System information:

	$ uname -srm
        Linux 4.9.13 x86_64

* Prometheus version:

	/prometheus $ prometheus --version
        prometheus, version 2.2.1 (branch: HEAD, revision: 
        bc6058c81272a8d938c05e75607371284236aadc)
        build user:       root@149e5b3f0829
        build date:       20180314-14:15:45
        go version:       go1.10

* Prometheus configuration file:

https://github.com/prometheus/prometheus/blob/master/documentation/examples/prometheus-kubernetes.yml

* Logs:
```
level=info ts=2018-04-28T07:47:07.604327895Z caller=web.go:382 component=web msg="Start listening for connections" address=0.0.0.0:9090
level=info ts=2018-04-28T07:47:07.668295285Z caller=main.go:514 msg="TSDB started"
level=info ts=2018-04-28T07:47:07.668350545Z caller=main.go:588 msg="Loading configuration file" filename=/etc/prometheus/prometheus.yml
level=info ts=2018-04-28T07:47:07.669727547Z caller=kubernetes.go:191 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2018-04-28T07:47:07.670966244Z caller=kubernetes.go:191 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2018-04-28T07:47:07.673711432Z caller=kubernetes.go:191 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2018-04-28T07:47:07.674561758Z caller=kubernetes.go:191 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2018-04-28T07:47:07.675461852Z caller=kubernetes.go:191 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2018-04-28T07:47:07.676243663Z caller=kubernetes.go:191 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2018-04-28T07:47:07.677061016Z caller=kubernetes.go:191 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2018-04-28T07:47:07.677799305Z caller=main.go:491 msg="Server is ready to receive web requests.
```

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
