### ISSUE TITLE
Add linters to golangci lint.

### ISSUE THREAD

**Issue by SuperQ** [prometheus/prometheus#4125]
## Proposal

Enable additional linters in `golangci-lint`
```yaml
linters:
  enable:
  - golint
```

**Comment by brian-brazil** [comment]
Do we know what level of false positives we can expect?

**Comment by SuperQ** [comment]
Good question, Maybe @mjtrangoni has some more experience with that.

**Comment by mjtrangoni** [comment]
@brian-brazil you are right, there are going to be **many** false positives. 
IMHO, the best and simplest way I found was using [gometalinter](https://github.com/alecthomas/gometalinter) plus a JSON configuration file, like [this](https://github.com/mjtrangoni/flexlm_exporter/blob/master/.gometalinter.json). This configuration file should be also project-specific.
Another interesting thing I found was that gometalinter introduces some specific flags for some linters. I mean, It is not only running the linter itself.
OTOH, I think this will be adding some great value to the projects.

**Comment by juliusv** [comment]
Yeah, careful with linting, at least https://github.com/golang/lint's README.md says "In short, this tool is not, and will never be, trustworthy enough for its suggestions to be enforced automatically, for example as part of a build process.", and we've known that for a while :)

We can still have targets for it of course, just not have them be part of CI checks.
