### ISSUE TITLE
Expose GCE labels during service discovery

### ISSUE THREAD

**Issue by woolite64** [prometheus/prometheus#4137]
## Proposal
Expose GCE [instance labels](https://cloud.google.com/compute/docs/labeling-resources) as \__meta_gce_label\_<name> so that values can be passed to Target Labels.

It's currently possible to filter by GCE labels using Prometheus, but the values aren't available once the host is found. Tags and metadata are exposed ([here](https://github.com/prometheus/prometheus/blob/c207920500d1d55c21d7b7dbb27ba213394ce369/discovery/gce/gce.go#L222-L240)) with __meta prefixes.

**Comment by brian-brazil** [comment]
It sounds like you'll need to update the vendoring. We use govendor for this,

**Comment by woolite64** [comment]
Opened a PR for this. First time using Go, any feedback is appreciated.

I was able to compile, run tests, and confirm that labels were working on my end.
