### ISSUE TITLE
Consider supporting sorting by label value

### ISSUE THREAD

**Issue by juliusv** [prometheus/prometheus#414]
Mainly for display reasons (tabular view), it would be sometimes useful to not sort by the value of timeseries, but by a given label value.

Example: list all apps in a PaaS and their memory usage. It would be nice to be able to sort by application name ("app" label).

/cc @grobie

**Comment by RichiH** [comment]
Sorry, I looked for dups, but didn't see this one.

I agree with the discussion in https://github.com/prometheus/prometheus/pull/432 that this should be in one layer only. As you don't know where further consumption of the results happens, e.g. Grafana, via HTTP API, etc, I do think that this should be done in PromQL itself as that opens one canonical way of sorting for all further processing methods.

**Comment by brian-brazil** [comment]
#1533

**Comment by Gouthamve** [comment]
This is the default in 2.0. I think this issue can be closed @brian-brazil
