### ISSUE TITLE
Proposal: pushing metrics directly to Prometheus

### ISSUE THREAD

**Issue by rollcat** [prometheus/prometheus#4140]
I think push vs pull has been mentioned a long time ago, on numerous occasions, and in numerous sources already, but after briefly reviewing open (and closed) issues I haven't found anything of a decisive "yes" / "no" / "maybe" / "send a patch".

From what I gathered, pushgateway, due to its design, is only ever recommended for [certain, specialized use cases](https://prometheus.io/docs/practices/pushing/).

The high-level proposal is to expose an endpoint, where clients could push metrics directly, ideally via HTTP POST. Basically integrate (parts of) pushgateway into "core" Prometheus, and make push-based metric collection a first-class citizen.

Clients that only expose metrics via the scrape/GET endpoint, could be bridged by a local scraper that later pushes the metrics via POST.

**Comment by krasi-georgiev** [comment]
https://groups.google.com/forum/#!forum/prometheus-developers
Proposals are best discussed in the google group as more people are subscribed there and will be a better place for such discussion.

it might be worth doing some search as I suspect this topic has already been discussed.
Don't forget to describe your use case and why it  can't be solved with the pull model or via the push gateway.

**Comment by brian-brazil** [comment]
This has been discussed extensively, and this is an explicit non-goal of the project.
