### ISSUE TITLE
Feature request: IRC alertmanager integration

### ISSUE THREAD

**Issue by io7m** [prometheus/prometheus#4141]
## Proposal

It would be good if Prometheus could send alert messages to IRC.  It already supports sending messages to other chat protocols (some of which are proprietary), and IRC being a widely implemented, widely used open standard constitutes quite an omission!

**Comment by SuperQ** [comment]
IRC requires a persistent connection, which is not possible in an alertmanager cluster, as each one would require an independent connection.

Googling for "alertmanager irc bot" returns several bots that implement webhook receivers.

https://github.com/multimfi/bot
https://github.com/metalmatze/alertmanager-bot

In addition, I believe Matrix (Riot?) implement enough Slack API to pass messages to IRC.

Also, the prometheus repo is not an appropriate place for an alertmanager feature request.

**Comment by io7m** [comment]
Sorry, I was actually asked to report this one by `bhenc` on the IRC channel. Clearly I got the wrong repos.

**Comment by SuperQ** [comment]
No worries, I think it would be good to have some links to various webhook implementations somewhere.  We could put this in our docs repo under the alertmanager docs, similar to how we list exporters.

**Comment by brian-brazil** [comment]
They're already on https://prometheus.io/docs/operating/integrations/#alertmanager-webhook-receiver

The AM repo would have the disadvantage that it'd only get updated on release.
