### ISSUE TITLE
lose data (last 15 days)

### ISSUE THREAD

**Issue by toanpt3** [prometheus/prometheus#4142]
Hi everybody.

I'm having a data loss situation. Specifically, one day after the previous 15 days data will be deleted. For example, today, 05/05/2018, the date 20/04/2018 will be deleted.
I do not think this is a bug or feature.
please advice ?
1. Cannot get lost data
2. The configuration is not lost data (last 15 days)

- **System information**:
 CentOS Linux release 7.3.1611 (Core)  x86_64 x86_64 x86_64 GNU/Linux
- **Prometheus version**:
Version | 1.7.1

**Comment by krasi-georgiev** [comment]
by default Prometheus deletes any data older than 15days

https://prometheus.io/docs/prometheus/latest/storage/#operational-aspects
