### ISSUE TITLE
a issue about prometheus metrics timestamp  and for great response ! thank u very much !

### ISSUE THREAD

**Issue by annan211** [prometheus/prometheus#4152]
#Hi , everybody ，I have a big problem about Prometheus when I send some metrics data to pushgateway 
With simpleclient_pushgateway java API 0.3.0 

The problem is I can not send metrics data with  timestamp , but I need it so much .

I have coverd   DropwizardExports  class with  PromDropwizardExports and override fromCounter / fromGauge / fromHistogram  / fromTimers and 
Add timestamp to Sample

Ex :

List<MetricFamilySamples> fromCounter(String dropwizardName, Counter counter) {
    String name = sanitizeMetricName(dropwizardName);
    Sample sample = new Sample(name, new ArrayList(), new ArrayList(),
            (new Long(counter.getCount())).doubleValue(),System.currentTimeMillis());
    LOGGER.info("Counter Sample is : " + sample);
    return Arrays.asList(new MetricFamilySamples(name, Type.GAUGE, getHelpMessage(dropwizardName, counter),
            Arrays.asList(sample)));
}

, but it don not work , ti is very important ,I wait for your great response !

**Comment by FUSAKLA** [comment]
I think pushing with timestamp is rejected since pushgateway version `0.4.0` ([see changelog](https://github.com/prometheus/pushgateway/blob/master/CHANGELOG.md))

More info can be found here in this issue https://github.com/prometheus/pushgateway/issues/109
