### ISSUE TITLE
No new Docker builds for master branch

### ISSUE THREAD

**Issue by AlekSi** [prometheus/prometheus#4156]
Currently, both Docker Hub and quay.io show that latest `master` image is 14 days old. Latest commit to that branch was 2 days ago.

https://hub.docker.com/r/prom/prometheus/tags/
https://quay.io/repository/prometheus/prometheus?tag=master&tab=tags

Reason for that: https://circleci.com/gh/prometheus/prometheus/6085
Seems to be a side-effect of #4132.

/cc @simonpasquier @SuperQ

**Comment by SuperQ** [comment]
The docker hub master build is failing with this:

```
Step 3/15 : COPY prometheus /bin/prometheus
 ---> 25b23cd39f2e
Step 4/15 : COPY promtool /bin/promtool
COPY failed: stat /var/lib/docker/tmp/docker-builder143748466/promtool: no such file or directory
Makefile.common:89: recipe for target 'docker' failed
make: *** [docker] Error 1
Exited with code 2
```

**Comment by SuperQ** [comment]
Confirmed, the `promtool` fix worked, we now have updated docker images published on both `hub.docker.com` and `quay.io`.

**Comment by krasi-georgiev** [comment]
broke it - fix it :smile:
