### ISSUE TITLE
digitalocean service discovery

### ISSUE THREAD

**Issue by caarlos0** [prometheus/prometheus#4166]
## Proposal
**Use case. Why is this important?**

I want to use prometheus on DigitalOcean. My previous experience was on aws, using ec2_sd and all that.

I noticed, though, that there isn't a digitalocean_sd or something like that for digitalocean.

I could in theory use SD from files, etcd or whatever... but I think it would be useful for more people.

Is that from the interest of you guys? If it is, I can work on a PR.

Thanks!

**Comment by brian-brazil** [comment]
Per https://github.com/prometheus/prometheus/tree/master/discovery#service-discovery we are not currently accepting new SD mechanisms, so would recommend that you use file_sd.

**Comment by krasi-georgiev** [comment]
maybe we should update this to say

 > There is currently a moratorium on new service discovery mechanisms being added to Prometheus due to a lack of developer capacity  <b>for long term support and maintenance</b>. In the meantime file_sd remains available.`

**Comment by krasi-georgiev** [comment]
@caarlos0 there is a PR with a very good example how to implement a custom SD that generates a json in the file_sd format.
https://github.com/prometheus/prometheus/pull/3720

**Comment by krasi-georgiev** [comment]
btw a while ago I started a [discussion](https://groups.google.com/forum/#!searchin/prometheus-developers/file$20sd%7Csort:date/prometheus-developers/JcE5nSbCe4k/Z0ChZaR7AgAJ) about `file_sd` vs `http_sd` so if  `file_sd` doesn't solve your use case you might give some feedback in the discussion.

**Comment by brian-brazil** [comment]
> If I compromise to maintain it, still not a thing you want to do?

Part of the reason the moratorium is all the previous sd creators who said the same thing, and did not follow through.

**Comment by caarlos0** [comment]
> Part of the reason the moratorium is all the previous sd creators who said the same thing, and did not follow through.

hm, OK, I can understand that. As much as I want to say I'll not be one of those, you have no reason to believe me, so it doesn't matter heh 

Anyway, thanks for the replies, will try to make an external thing that generates the file in the right format, so other people may still use it anyway :) 

Oh, and thanks for this great tool! Prometheus is awesome! 🤘

Cheers!

**Comment by caarlos0** [comment]
In case anyone else needs this -> https://github.com/TOTVS/prometheus-digitalocean-sd

**Comment by roidelapluie** [comment]
Happening in #7407
