### ISSUE TITLE
compact error leading to disk entire in a hour in 2.2.1

### ISSUE THREAD

**Issue by zhouyuanchao** [prometheus/prometheus#4168]
https://github.com/prometheus/prometheus/issues/3714 
this issue shows this bug is fix in 2.2.1, but when I use 2.2.1, disk was entire in a hour.

level=error ts=2018-05-16T06:11:11.282000739Z caller=db.go:281 component=tsdb msg="compaction failed" err="compact [/opt/huawei/prometheus/data/01CDFJQJA3BKVWCJD0YKZ0XABV /opt/huawei/prometheus/data/01CDHGH6P0AQY2KK36B93WM54W /opt/huawei/prometheus/data/01CDKEB3S50X0DKHBJXAFP46B0]: mmap files: mmap: cannot allocate memory"
level=error ts=2018-05-16T06:14:11.283045419Z caller=db.go:281 component=tsdb msg="compaction failed" err="compact [/opt/huawei/prometheus/data/01CDFJQJA3BKVWCJD0YKZ0XABV /opt/huawei/prometheus/data/01CDHGH6P0AQY2KK36B93WM54W /opt/huawei/prometheus/data/01CDKEB3S50X0DKHBJXAFP46B0]: mmap files: mmap: cannot allocate memory"

level=info ts=2018-05-16T10:34:51.201694208Z caller=compact.go:393 component=tsdb msg="compact blocks" count=1 mint=1526443200000 maxt=1526450400000
level=error ts=2018-05-16T10:35:21.361394055Z caller=db.go:281 component=tsdb msg="compaction failed" err="reload blocks: open block /opt/huawei/prometheus/data/01CDKVZHD33HJQKXWV3DS955M5: mmap files: mmap: cannot allocate memory"

when i try to restart 
level=info ts=2018-05-16T11:34:39.020138102Z caller=main.go:407 msg="Notify discovery manager stopped"
level=error ts=2018-05-16T11:34:39.020250764Z caller=main.go:582 err="Opening storage failed open block /opt/huawei/prometheus/data/01CDM66MBXFR2KS3X63Z4REXMH: mmap files: mmap: cannot allocate memory"
level=info ts=2018-05-16T11:34:39.020290097Z caller=main.go:584 msg="See you next time!"

**Comment by krasi-georgiev** [comment]
`mmap: cannot allocate memory`  you need more memory :)

**Comment by zhouyuanchao** [comment]
I still have 30G free memory

**Comment by krasi-georgiev** [comment]
this error comes from the OS , maybe some limit on what Prometheus can use, but in any way this doesn't look like a bug.

**Comment by krasi-georgiev** [comment]
if you run a search all issues with `cannot allocate memory` you will see that every report was due to insufficient  system memory.

**Comment by zhouyuanchao** [comment]
The meta.json in all dir is same, why write to disk repeatly?

![image](https://user-images.githubusercontent.com/38806828/40164635-afda6436-59ec-11e8-851b-0c7dfb20b8f5.png)
![image](https://user-images.githubusercontent.com/38806828/40164713-de075274-59ec-11e8-9ed5-8761985fd8e5.png)
![image](https://user-images.githubusercontent.com/38806828/40164723-e3deacb0-59ec-11e8-8181-285b3ac808c2.png)

**Comment by krasi-georgiev** [comment]
find the culprit for the insufficient memory(not enough phisical memory or some memory restrictions)  and open a new issue if you still find that there is a problem.
