### ISSUE TITLE
connect alertmanager connection refused

### ISSUE THREAD

**Issue by like-inspur** [prometheus/prometheus#4170]
I run prometheus and alertmanager in docker swarm environment with latest image. In prometheus.yml I config alerting targets, but there is no target under prometheus web. The output of prometheus log is like this:
level=info ts=2018-05-17T07:13:59.669899464Z caller=main.go:220 msg="Starting Prometheus" version="(version=2.2.1, branch=HEAD, revision=bc6058c81272a8d938c05e75607371284236aadc)"
level=info ts=2018-05-17T07:13:59.669980404Z caller=main.go:221 build_context="(go=go1.10, user=root@149e5b3f0829, date=20180314-14:15:45)"
level=info ts=2018-05-17T07:13:59.6700267Z caller=main.go:222 host_details="(Linux 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64 swarm-213 (none))"
level=info ts=2018-05-17T07:13:59.67005277Z caller=main.go:223 fd_limits="(soft=1048576, hard=1048576)"
level=info ts=2018-05-17T07:13:59.674284268Z caller=web.go:382 component=web msg="Start listening for connections" address=0.0.0.0:9090
level=info ts=2018-05-17T07:13:59.674202619Z caller=main.go:504 msg="Starting TSDB ..."
level=info ts=2018-05-17T07:13:59.699334072Z caller=main.go:514 msg="TSDB started"
level=info ts=2018-05-17T07:13:59.699466488Z caller=main.go:588 msg="Loading configuration file" filename=/etc/prometheus/prometheus.yml
level=info ts=2018-05-17T07:13:59.7018075Z caller=main.go:491 msg="Server is ready to receive web requests."
level=error ts=2018-05-17T07:14:04.817294851Z caller=notifier.go:473 component=notifier alertmanager=http://swarm-214:9093/api/v1/alerts count=0 msg="Error sending alert" err="Post http://swarm-214:9093/api/v1/alerts: dial tcp 10.110.25.214:9093: connect: connection refused"

**Comment by simonpasquier** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by zstyblik** [comment]
I have a bit different setup, but the same issue. However, connection seems to be just fine when tested from Prometheus container.

Running prom/prometheus:v2.1.0 and prom/alertmanager:v0.14.0.

**Comment by krasi-georgiev** [comment]
@zstyblik thanks for the update. 

Closing now but feel free to continue the discussion in the mailing list or IRC.

[user mailing list](https://groups.google.com/forum/#!forum/prometheus-users)
[IRC channel](https://webchat.freenode.org/?channels=prometheus), #prometheus on irc.freenode.net.
