### ISSUE TITLE
Regression: `basic_auth` should not require a `username`

### ISSUE THREAD

**Issue by juliusv** [prometheus/prometheus#4173]
After https://github.com/prometheus/prometheus/pull/4077, `basic_auth` in HTTP configs now requires setting a username, otherwise you get an error:

```
[...] err="Error loading config couldn't load configuration (--config.file=prometheus.yml): parsing YAML file prometheus.yml: basic_auth requires a username"
```

Using basic auth without a username has been standard practice, for example in the suggested `remote_write` configs for Cortex. So this is a breaking change and needs to be fixed.

**Comment by adamdecaf** [comment]
Whoops, https://github.com/prometheus/common/pull/135 fixes that.

**Comment by juliusv** [comment]
@adamdecaf Awesome, thanks :)

**Comment by adamdecaf** [comment]
https://github.com/prometheus/prometheus/pull/4174 Should fix it in promtheus itself.
