### ISSUE TITLE
Prometheus not able to fetch kubernetes node matrics 

### ISSUE THREAD

**Issue by jsjuber** [prometheus/prometheus#4181]
I have deployed Prometheus on my kubernetes cluster and expose Prometheus service from the outside using Nodeport. I have access the consul of Prometheus but after the checked status target portion is blank Prometheus not able to fetch k8 cluster data from the node. I think I have missed something plz help.
For deployment, I have used below git repo.
https://github.com/bibinwilson/kubernetes-prometheus
![pro](https://user-images.githubusercontent.com/28477054/40361118-e6afb572-5de5-11e8-9ad7-4fa0b440fd01.png)

**Comment by krasi-georgiev** [comment]
This is a good question , but for the users group :+1:  
https://groups.google.com/forum/#!forum/prometheus-users
The developers here are busy solving nasty bugs :beetle: 

I would recommend looking through the official docs and examples as well as searching in the google groups as there is a good chance that you will find the answer immediately.
https://prometheus.io/docs/introduction/overview/
