### ISSUE TITLE
Pass LookbackDelta as query hint to remote read

### ISSUE THREAD

**Issue by mtanda** [prometheus/prometheus#4192]
## Proposal
Related to https://github.com/prometheus/prometheus/pull/4122 .

I'm implementing read adapter.
The read adapter response size could be big, so I reduce size by calculating expected step, and response each datapoints correspond to the step.

Prometheus only accept datapoints in `refTime - lookbackDelta`.
https://github.com/prometheus/prometheus/blob/v2.2.1/promql/engine.go#L796

refTime is calculated like `refTime = startTime x n x interval`.
https://github.com/prometheus/prometheus/blob/v2.2.1/promql/engine.go#L402

read adapter need response datapoitns which fit in each time bucket.

But, the start time of query range is affected by lookbackDelta.
https://github.com/prometheus/prometheus/blob/v2.2.1/promql/engine.go#L492
https://github.com/prometheus/prometheus/blob/v2.2.1/promql/engine.go#L476

It is difficult to align data.

If I may misunderstand something, please tell me how I can align the data.

**Comment by brian-brazil** [comment]
It's fine to add this, however you don't need to.

For instant vector evaluation all you need to do is return the first sample at or before each interval. Watch out for 'offset' though.

**Comment by mtanda** [comment]
Now I understand more detail.
My read adapter inject staleNan to datapoint, so I confuse the behavior related to staleness.
Don't need to pass LookbackDelta, it seems to work without it.
So I close this issue.

Thanks for your help!
