### ISSUE TITLE
prometheus 2.2.1 Getting Error in query_range 

### ISSUE THREAD

**Issue by abhi11** [prometheus/prometheus#4197]
I get error when I run the following.
```
curl -i http://10.182.11.105:9090/api/v1/query_range?query=up&start=1527199200&end=1527199500&step=15s
```

I am running this on a linux machine.
I get the following error. I have also used the rfc3339 format but that shows the same error.
```
{"status":"error","errorType":"bad_data","error":"cannot parse \"\" to a valid timestamp"}
```

**Comment by hoffie** [comment]
This seems to be the error message which is printed when no start or end parameters are seen by Prometheus at all. Can you confirm that curl sends the proper request by adding `-v`?

When running your example verbatim in bash, the shell will interpret the `&` signs and will fork the call.
When escaping the URL, your example works for me in bash:
```
curl -i 'http://10.182.11.105:9090/api/v1/query_range?query=up&start=1527199200&end=1527199500&step=15s'
```

**Comment by krasi-georgiev** [comment]
This is a  question for the users group :+1: 
https://groups.google.com/forum/#!forum/prometheus-users
The developers here are busy solving bugs :beetle: 

I would recommend looking through the official docs and examples as well as searching in the google groups as there is a good chance that you will find the answer immediately.
https://prometheus.io/docs/introduction/overview/
