### ISSUE TITLE
Document internal pieces of the Prometheus server and how they fit together

### ISSUE THREAD

**Issue by juliusv** [prometheus/prometheus#4219]
The Prometheus server is a big beast with many subcomponents, which can be hard for new contributors to get into. I would like to see documentation that zooms in to the Prometheus piece of https://prometheus.io/assets/architecture.svg and explains for developers how all the different pieces fit together:

- config
- SD
- scraping
- TSDB
- rules
- alert notifications
- etc.

This should include a diagram of how the pieces interconnect, what information they exchange, and then a natural language explanation of each piece and its assumptions. Where necessary, it could link to more detailed documentation about a specific piece, like https://github.com/prometheus/prometheus/blob/master/discovery/README.md.

**Comment by krasi-georgiev** [comment]
:+1: 
Is this going to dive in actual code or just  more detailed view about each piece in the architecture?

I am asking as I have noticed that any code references and components get outdated very quickly.

**Comment by juliusv** [comment]
@krasi-georgiev I was thinking it might link to actual code and maybe mention some of the used types or interfaces where appropriate, but it shouldn't go into too much detail itself. Still, it might get outdated, so links should go to a particular Prometheus revision and the doc should state that the explanations are based on that, so that people can also see how updated or outdated the doc is.

**Comment by krasi-georgiev** [comment]
yep that should work! 
ping me when you have the google doc so I can follow and nag you with questions :stuck_out_tongue_winking_eye: 
Maybe I can also help with some parts.

Here is a deep dive in the TSDB , started by @gouthamve and than I also started adding different bits to it.
https://docs.google.com/document/d/1t5eSLlH36oK1Ex3PWwuc4R58kx4PC7Ago90TRR_7nmo/edit#heading=h.9fse7yo9k0j6

**Comment by juliusv** [comment]
@krasi-georgiev Thanks! Oh yeah, if you could help flesh out / finalize / website-ize the TSDB documentation, that would be great. That probably makes sense as a separate item with a lot of detail, that this main overview can then link to.

**Comment by RichiH** [comment]
Sounds sane; if you need to point at docs that would be good to have, I think we should simply create placeholders for that to flesh out later. If that means the official docs are interspersed with a few TODO for a short time, I think that's OK. We should have a link in there to point out how people can help, but else...

**Comment by juliusv** [comment]
@lucperkins My plan so far was to write this one myself, or do you think it's better if someone new to the project does it? Of course it'd be great to get a review in any case.

**Comment by lucperkins** [comment]
@juliusv @RichiH I've got this on my TODO list.

@krasi-georgiev One possibility might be something like this ["Code Organization"](https://apache.github.io/incubator-heron/docs/contributors/codebase/) doc that I put together for the Apache Heron documentation. Basically a high-level intro to the repo that points out important subdirectories and places in the code. Since it's mostly Go, links to the GoDoc could be applied liberally as well. Would you find that useful?

**Comment by juliusv** [comment]
@lucperkins Oh ok! So currently I have a work item open with the CNCF for me to do this and with much more detail planned than in https://apache.github.io/incubator-heron/docs/contributors/codebase/. It would dive into more detail about how each component works, how it connects to other components, and what assumptions there are (which might be difficult to derive from just reading code). Do you feel strongly on taking this on though?

**Comment by lucperkins** [comment]
@juliusv I'm happy to leave that up to you, of course. One possibility could be that you give me a rough "braindump"-style Google doc and I can spin that into a more full-fledged doc plus the "drilldown" diagram that you mention.

**Comment by juliusv** [comment]
@lucperkins Sounds good to me, let's collaborate on it! I hope to start working on this by next week, maybe even before. What do you usually use for diagrams? We have been using https://www.draw.io/ so far, which maybe isn't as shiny as some desktop tools, but has the advantage that everyone can update diagrams no matter what their Desktop OS is, and without needing to install expensive software.

**Comment by lucperkins** [comment]
@krasi-georgiev Agreed re: linking directly to code. GoDoc links are more sustainable, as the names for important structs/interfaces/constants/etc seem to be largely unchanging in the Prometheus code.

**Comment by juliusv** [comment]
Good idea, will keep that in mind for the public interfaces. Sometimes you can't avoid linking to code (a specific revision then) when it's about unexported internals that are important for devs.

@lucperkins It'd be great to get your help to get the TSDB doc that @krasi-georgiev linked into shape!

**Comment by lucperkins** [comment]
@juliusv @krasi-georgiev Let’s get it done 👍🏻

**Comment by krasi-georgiev** [comment]
please ping me next week for the TSDB

**Comment by henridf** [comment]
@juliusv if you need more cycles i'd be happy to contribute, whether it's reading/editing, or writing portions relative to the pieces i'm more familiar with (which would currently be remote storage and `promql/`). 

(It sounds like you already have a couple cooks, so totally ok if you'd rather not spoil the broth!)

**Comment by juliusv** [comment]
@henridf Yep thanks! Let me get the initial version out first, and then everyone is free to add their broth ingredients to it :)

**Comment by juliusv** [comment]
@lucperkins @brian-brazil @RichiH here's a WIP for this: https://github.com/prometheus/prometheus/pull/4295

Interested in general feedback for now, I will still add more details to the doc and polish it later.

**Comment by juliusv** [comment]
This was merged.
