### ISSUE TITLE
Metric Relabeling and Values

### ISSUE THREAD

**Issue by muralikanagala** [prometheus/prometheus#4225]
Hello Everyone,

I am using Prometheus to monitor a RabbitMQ cluster and currently working on relabeling on some dynamic queues. I am grouping a bunch of queues into one generic queue label. 

My question here is what happens to the values of those metrics that are getting relabeled?
Are there any options like average/sum for the values in the metrics while relabeling them?

Thank you!

**Comment by krasi-georgiev** [comment]
The github issues are focused on bug reports :beetle: and this looks like more like a support request :+1: 

I would recommend looking through the official docs and examples as well as searching in the google groups or asking in the irc channel and I am sure there will be someone to help you out.

irc: #prometheus 
group: https://groups.google.com/forum/#!forum/prometheus-users
docs: https://prometheus.io/docs/introduction/overview/

Feel free to reopen if you are 100% convinced that is not a support request and a bug in Prometheus.
