### ISSUE TITLE
Add REST API for SD.

### ISSUE THREAD

**Issue by shunliz** [prometheus/prometheus#4228]
## Proposal
**Use case. Why is this important?**
As a third-party system, i need register/deregister my endpoint to prometheus by REST API and be scraped. I don't like existing SDs as they are not flexible.

Not sure if it's a good idea, any suggestion?

*Nice to have' is not a good use case :)*

**Comment by jojohappy** [comment]
You can look this document
https://github.com/prometheus/prometheus/tree/master/documentation/examples/custom-sd

It use `file_sd` for SD

**Comment by krasi-georgiev** [comment]
one big disadvantage in your proposal is that all your targets need to know the ip of the Prometheus server which might work in a small setup,but a big disadvantage at scale.

Can you share more details about your setup?

**Comment by shunliz** [comment]
Thanks jojohappy, brian-brazil. Using the custom-sd is way to solve my problem, but I have many vms or docker created dynamically, and each time a vm or docker created, need to restart prometheus. I'm not sure if it will lose some metrics and if there is any problems that restart prometheus frequently.

Thanks krasi-georgiev. I just have a hybrid cloud controller which will need to monitor the vms or dockers created by the  hybrid cloud controller in different cloud resource provider.

**Comment by jojohappy** [comment]
Prometheus has provide api to reload configuration, It will not need to restart Prometheus and impact on scrape process.

**Comment by shunliz** [comment]
Thansk all for the comments and replys.
I think i can close this question.
