### ISSUE TITLE
rule_files does not seem to detect file changes

### ISSUE THREAD

**Issue by avonwyss** [prometheus/prometheus#4235]
## Proposal
**Use case. Why is this important?**
Changes to rule files specified in `rule_files` should ideally take effect automatically, without the need to trigger a configuration reload manually. This would allow external tools/scripts to generate of modify these files without requiring direct interaction with Prometheus.

I would expect it to behave the same as `scrape_configs.*.file_sd_configs.files` which detects file changes as well as new files when using a wildcard.

**Comment by brian-brazil** [comment]
You need to reload Prometheus's configuration for changes to rules to take effect, just as for prometheus.yml changes.

**Comment by avonwyss** [comment]
I'm aware of that, which is why I have made a proposal to add file change detection.

**Comment by brian-brazil** [comment]
Yes, that'd also prevent users from doing a multi-file atomic change as the first file changed would trigger a reload before the rest were done.

**Comment by brian-brazil** [comment]
It is a problem, say I want to replace file a.rules with b.rules. That's not possible atomically with your suggestion.

> Also, usually file monitors triggers use some debouncing/quiet wait time which also mitigates this kind of issues.

That makes it into a race condition, which isn't much better. In addition you'd be breaking all the users who depend on the current documented behaviour.

**Comment by avonwyss** [comment]
@krasi-georgiev Of course I can create some mechanism to trigger the reload externally, but I try to keep the tools and systems as decoupled as possible. Since file monitoring actually exists in other places of the configuration it did not seem to be such a far-fetched idea.

**Comment by krasi-georgiev** [comment]
> try to keep the tools and systems as decoupled

To me it seems logical that the same tool that  generates the config should be responsible for actually enabling the new config.

And @brian-brazil's argument about the race condition is a rather big blocker against changing the current behaviour.

**Comment by roidelapluie** [comment]
PSA: We need that atomic change thing. To us changing that would cause troubles.

**Comment by avonwyss** [comment]
Since this proposal has apparently significant problem potential I'm closing it.
I have now added the `--web.enable-lifecycle` flag and trigger the reload externally via web request.
