### ISSUE TITLE
Asked remote read write

### ISSUE THREAD

**Issue by MoSunDay** [prometheus/prometheus#4243]
I wonder why some remote storage only provides a write operation, not a read, so how can the data written to the database be used?

From other if using remote read and wirte InfluxDB, every time a large number of queries memory is required for a double, because InfluxDB need memory cache results, and then give P8S results to vomit, P8S also need to save data memory, and then execute PromQL.

This is just my guess. Why not set a time period for the InfluxDB data to exist locally after it has been fetched? Future queries will only use P8S 'own memory overhead.

**Comment by krasi-georgiev** [comment]
I think you will get a better answer for that in the devs Malling list

**Comment by MoSunDay** [comment]
@krasi-georgiev thanks
