### ISSUE TITLE
2.3.0 returns wrong content-type for built-in javascript libraries

### ISSUE THREAD

**Issue by veksh** [prometheus/prometheus#4246]
## Bug Report

I've installed 2.3.0 in a VM with port 9090 forwarded to localhost, and
web interface does not work as expected: no javascript libraries are loaded (2.2.1 is OK).
On closer inspection, error console has 14 errors like

```
Refused to execute script from 'http://localhost:9090/static/vendor/js/jquery.min.js?v=290d71791a507a5057b9a099c9d48703d86dc941' because its MIME type ('text/x-js') is not executable, and strict MIME type checking is enabled.
```

so most probably `Content-Type` header for built-in javascript libraries is wrong.

Command-line is

```
/usr/local/bin/prometheus --config.file=/usr/local/etc/prometheus.yml --storage.tsdb.path=/var/lib/prometheus/data/ --web.console.templates=/usr/local/share/prometheus/console --web.console.libraries=/usr/local/share/prometheus/console_libraries --log.level=debug
```

**Environment**

* System information:

	Linux 3.0.101-108.38-default x86_64

* Prometheus version:

	prometheus, version 2.3.0 (branch: HEAD, revision: 290d71791a507a5057b9a099c9d48703d86dc941)
           build user:       root@d539e167976a
           build date:       20180607-08:46:54
           go version:       go1.10.2

* Prometheus configuration file:
```
global:
  scrape_interval:     15s
  evaluation_interval: 15s
  scrape_timeout:      10s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']
```

**Comment by krasi-georgiev** [comment]
that is probably because of this commit
https://github.com/prometheus/prometheus/commit/c207920500d1d55c21d7b7dbb27ba213394ce369

**Comment by fabxc** [comment]
@krasi-georgiev any further info how that commit causes this?

**Comment by brian-brazil** [comment]
It's likely the nosniff.

**Comment by fabxc** [comment]
Okay, what was the motivation for adding those security headers? Were we exposed to any security risk?

**Comment by brian-brazil** [comment]
General security hardening was the motivation.

**Comment by fabxc** [comment]
Yes, but what are the risks those headers are fixing? I personally haven't seen them before and don't know what they do and how they are causing this issue. I'm all for hardening, but would be good to understand what we are hardening against and how.

**Comment by hasso** [comment]
While reverting security headers commit temporarily is OK as hotfix, the real problem is the Content-Type. text/x-js and similar ones are obsolete for more than 10 years and application/javascript must be used.

https://tools.ietf.org/html/rfc4329

**Comment by veksh** [comment]
With current 2.3.1 release (default config, just unpacked and started) I'm seeing different results on different platforms:

1) centos 7: `application/javascript`

```
[alex@v-centos7 ~]$ curl -si 'localhost:9090/static/vendor/js/jquery.min.js?v=290d71791a507a5057b9a099c9d48703d86dc941'|head -7
HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Length: 86671
Content-Type: application/x-javascript
Last-Modified: Fri, 11 May 2018 16:21:47 GMT
Date: Tue, 26 Jun 2018 10:03:27 GMT
[alex@v-centos7 ~]$ grep PRETTY_NAME /etc/os-release
PRETTY_NAME="CentOS Linux 7 (Core)"
[alex@v-centos7 ~]$ uname -a
Linux v-centos7.m1.maxidom.ru 3.10.0-862.2.3.el7.x86_64 #1 SMP Wed May 9 18:05:47 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

2) suse linux enterprise 11.4: `text/x-js`

```
alex@v-test:~$ curl -si 'localhost:9090/static/vendor/js/jquery.min.js?v=290d71791a507a5057b9a099c9d48703d86dc941'|head -7
HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Length: 86671
Content-Type: text/x-js; charset=utf-8
Last-Modified: Fri, 11 May 2018 16:21:47 GMT
Date: Tue, 26 Jun 2018 10:04:38 GMT
alex@v-test:~$ grep PRETTY_NAME /etc/os-release
PRETTY_NAME="SUSE Linux Enterprise Server 11 SP4"
alex@v-test:~$ uname -a
Linux v-test 3.0.101-108.38-default #1 SMP Mon Apr 16 12:16:19 UTC 2018 (3dac46e) x86_64 x86_64 x86_64 GNU/Linux
```

W/o security headers Google Chrome is OK with both.

**Comment by veksh** [comment]
On SLES `/etc/mime.types` correctly maps `js` to `application/javascript`:

```
alex@v-test:~$ grep javascript /etc/mime.types 
application/javascript js
```

**Comment by amorken** [comment]
@veksh I suspect that if you grep for "text/x-js" instead of "javascript" you may find that the /etc/mime.types contains a mapping for that type to "js" later in the file.

Go's mime type loader simply scans the input files in order and adds things to a map, so later entries win. See https://golang.org/src/mime/type_unix.go and https://golang.org/src/mime/type.go for specifics

If you comment out the "text/x-js" entry you may get the behavior you expect.

**Comment by veksh** [comment]
@amorken you are absolutely right -- there are 2 entries for "js" in `/etc/mime.types`, second one is wrong and after editing it out Content-Type for js became `application/javascript`. Thanks!

**Comment by brian-brazil** [comment]
I'm not sure we should be depending on external (and apparently outdated) resources for something like this. Is there a better way to do this?

**Comment by amorken** [comment]
Well, we can "simply" provide the MIME types ourselves: https://github.com/amorken/prometheus/commit/fc6b6bfe842e0500c4e43c882478277f7d84d5ee

It's not beautiful, but it should be functional. I can send a PR over and include the now-reverted c207920 commit too if there's interest.

-@M

**Comment by brian-brazil** [comment]
Is it just the static endpoint that's affected, or is this something we need to set more broadly?

**Comment by amorken** [comment]
Just the static endpoint. It is the only usage of `http.ServeContent` in the Prometheus tree, and that's where the automatic selection of Content-Type based on file extension happens.

**Comment by mrasu** [comment]
Hello, I made a PR for this issue.
It changes prometheus' web to return consistent Content-Type.

Can I ask you to look?

**Comment by krasi-georgiev** [comment]
I believe this is closed in https://github.com/prometheus/prometheus/pull/5551
