### ISSUE TITLE
http2Client.notifyError

### ISSUE THREAD

**Issue by njouve** [prometheus/prometheus#4281]
## Bug Report
I 've just followed the Getting Started Guide and launched the Windows binary ( prometheus-2.3.0.windows-amd64 ) on a command line.
I have neither proxy setup nor fancy network setup.

**What did you expect to see?**

A nice welcome message

**What did you see instead? Under which circumstances?**

A continous flow of  **http2Client.notifyError got notified that the client transport was broken unexpected EOF.** messages.

**Environment**

* System information:

Windows 10 64

* Prometheus version:

prometheus, version 2.3.0 (branch: HEAD, revision: 290d71791a507a5057b9a099c9d48703d86dc941)
  build user:       root@d539e167976a
  build date:       20180607-08:56:37
  go version:       go1.10.2

* Prometheus configuration file:
The pristine factory version

* Logs:
```
2018/06/18 16:05:49 transport: http2Client.notifyError got notified that the client transport was broken unexpected EOF.
2018/06/18 16:05:49 transport: http2Client.notifyError got notified that the client transport was broken unexpected EOF.
2018/06/18 16:05:49 transport: http2Client.notifyError got notified that the client transport was broken unexpected EOF.
2018/06/18 16:05:50 transport: http2Client.notifyError got notified that the client transport was broken unexpected EOF.
2018/06/18 16:05:50 transport: http2Client.notifyError got notified that the client transport was broken unexpected EOF.
2018/06/18 16:05:50 transport: http2Client.notifyError got notified that the client transport was broken unexpected EOF.
2018/06/18 16:05:50 transport: http2Client.notifyError got notified that the client transport was broken unexpected EOF.
2018/06/18 16:05:50 transport: http2Client.notifyError got notified that the client transport was broken unexpected EOF.
2018/06/18 16:05:50 transport: http2Client.notifyError got notified that the client transport was broken unexpected EOF.
2018/06/18 16:05:50 transport: http2Client.notifyError got notified that the client transport was broken unexpected EOF.
2018/06/18 16:05:50 transport: http2Client.notifyError got notified that the client transport was broken unexpected EOF.
2018/06/18 16:05:50 transport: http2Client.notifyError got notified that the client transport was broken unexpected EOF.
2018/06/18 16:05:50 transport: http2Client.notifyError got notified that the client transport was broken unexpected EOF.
2018/06/18 16:05:50 transport: http2Client.notifyError got notified that the client transport was broken unexpected EOF.
2018/06/18 16:05:51 transport: http2Client.notifyError got notified that the client transport was broken unexpected EOF.
2018/06/18 16:05:51 transport: http2Client.notifyError got notified that the client transport was broken unexpected EOF.
2018/06/18 16:05:51 transport: http2Client.notifyError got notified that the client transport was broken unexpected EOF.
2018/06/18 16:05:51 transport: http2Client.notifyError got notified that the client transport was broken unexpected EOF.
```

**Comment by simonpasquier** [comment]
Do you have any proxy setup? If so, you can check https://github.com/prometheus/prometheus/issues/3496

**Comment by njouve** [comment]
No as I said in the report, no proxy setup...

**Comment by simonpasquier** [comment]
Sorry I missed that information. Can you start the server with the `--log.level=debug` option and share the full logs? Am I correct that for now you start prometheus without any flag?

**Comment by njouve** [comment]
This morning it works like a charm... In the meantime yesterday I had switched to a Dockerized prometheus, then this morning after a reboot it all went good. I don't know what to think, maybe a transient networking problem...

**Comment by simonpasquier** [comment]
Thanks for following up!
