### ISSUE TITLE
Promql won't time-out queries in matrixSelector

### ISSUE THREAD

**Issue by jacksontj** [prometheus/prometheus#4288]
## Bug Report
**What did you do?**
Someone sent a large query such as `{__name__=~".+"}[5d]` to our prometheus host.

**What did you expect to see?**
I expect the query to timeout before completing, while consuming some memory and CPU along the way.

**What did you see instead? Under which circumstances?**
The query runs until it exhausts all available memory on the host and OOM killer get is. I have set it up in a repro env locally and the query has been running for ~60m (its still going) even though I have the timeout set to the default 2m.

**Environment**

* Prometheus version:

2.2

**Comment by brian-brazil** [comment]
Thanks for the report. I'm aware of this, and it's something I intend to cleanup now that the big PromQL change is in.

**Comment by juliusv** [comment]
@brian-brazil Something like https://github.com/prometheus/prometheus/commit/29294b2048f121c3596755c5b539d18973a8cc3d? Or probably you were already thinking of something more holistic?

**Comment by jacksontj** [comment]
@juliusv that would cover #4289 but not this PR. This matrixSelector is *after* the expandSeriesSet is called.

**Comment by juliusv** [comment]
@jacksontj Have you verified somehow that the bulk of the time (and memory) here is spent *after* the expansion of the series set for the matrix selector (https://github.com/prometheus/prometheus/blob/404abe0f1c19053581ba890cb40d2a2f7c6b758e/promql/engine.go#L511), in the actual evaluation?

**Comment by juliusv** [comment]
(of course there should still be timeout handling in the other pieces of the engine)

**Comment by jacksontj** [comment]
In the example I have both spots are very time intensive (at least on 2.2). Meaning it doesn't time out in either place (I can see it spend lots of time in both). I'm verifying master right now on my test host -- should have an answer in ~5-10m (prom takes FOREVER to start/stop)

**Comment by juliusv** [comment]
Yup, makes sense.

> (prom takes FOREVER to start/stop)

Whoa, how come?

**Comment by jacksontj** [comment]
From the *little* looking I've done its TSDB-- we have ~5TB of data on this box. I'll probably spend some time looking into that in the future, but for another issue/pr :)

**Comment by juliusv** [comment]
Oh yeah, I would assume it's the TSDB, but which part would be interesting. Anyway, let's leave that one for another issue :)

**Comment by brian-brazil** [comment]
> Something like 29294b2? 

No, it should be in the range vector function evaluation. There's math to be done to see how often we're required to do this, and it turns out due to edge cases (really long durations) to be at every time series.
