### ISSUE TITLE
Promql won't time-out queries in expandSeriesSet

### ISSUE THREAD

**Issue by jacksontj** [prometheus/prometheus#4289]
## Bug Report
**What did you do?**
Someone sent a large query such as `{__name__=~".+"}[5d]` to our prometheus host.

**What did you expect to see?**
I expect the query to timeout before completing, while consuming some memory and CPU along the way.

**What did you see instead? Under which circumstances?**
The query runs until it exhausts all available memory on the host and OOM killer get is. I have set it up in a repro env locally and the query has been running for ~60m (its still going) even though I have the timeout set to the default 2m.

**Environment**

* Prometheus version:

2.2

Same symptoms as #4288

**Comment by brian-brazil** [comment]
This doesn't sound right, it shouldn't take 2m just to lookup the index. How many time series do you have? Can you share your config?

**Comment by jacksontj** [comment]
My prod hosts have >10MM timeseries per box (don't see a metric for it besides a count in head, which is the lower bound). I'm not sure how many this test host has, as itI'm not the only reporter of this issue (#4290) FWIW.

cc @juliusv

**Comment by brian-brazil** [comment]
Can you try this on Prometheus 2.3?

**Comment by jacksontj** [comment]
I was able to reproduce this on master as well

**Comment by juliusv** [comment]
So let's say you had 10MM series, with 2h blocks you'd then be doing 10MM*(24/2)*5 = 600MM series lookups, and using a regex matcher. Doesn't sound too surprising to me that that could take >2m. Unless each series lookup is <.2 microseconds.

**Comment by brian-brazil** [comment]
I can see that (though there's more time than that due to compaction).
