### ISSUE TITLE
unexpected end of JSON input

### ISSUE THREAD

**Issue by pc10201** [prometheus/prometheus#4297]
Prometheu version=2.3.1

```
level=error ts=2018-06-21T08:20:01.914472896Z caller=file.go:321 component="discovery manager scrape" discovery=file msg="Error reading file" path=/etc/prometheus/jobs/node.json err="unexpected end of JSON input"
```

But /etc/prometheus/jobs/node.json file is a valid json file.I use 
```
python -m json.tool /etc/prometheus/jobs/node.json
```

to check it

**Comment by brian-brazil** [comment]
Is the file being created atomically via `rename`?

**Comment by pc10201** [comment]
I know the reason.

I write a program to update `/etc/prometheus/jobs/node.json` file every minute

And I set refresh_interval to 15s in prometheus.yml

**Comment by simonpasquier** [comment]
@pc10201 can you close the issue in that case?

**Comment by simonpasquier** [comment]
@pc10201 I'm closing the issue as it looks like you got things sorted out. If this isn't the case, I recommend that you ask for help on our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users).

**Comment by sorx00** [comment]
@pc10201 How you fixed this problem? I have discovery service for Rancher, which rewrite job file every 30 seconds. So every time Prom try to read this file, it's putting error into log.

**Comment by currycan** [comment]
I met the same problem,the prometheus version is 2.4.3.

**Comment by pc10201** [comment]
> @pc10201 How you fixed this problem? I have discovery service for Rancher, which rewrite job file every 30 seconds. So every time Prom try to read this file, it's putting error into log.

I do not fix it.But I change my program to create a tmp file,if the file is same as before and will not override it.

**Comment by snarlysodboxer** [comment]
> Is the file being created atomically via `rename`?

Which is best for this situation, writing to a temporary file and then using `os.Rename`, or overwriting the existing file with `ioutil.WriteFile` or similar?

**Comment by zhangxb1987** [comment]
> I know the reason.
> 
> I write a program to update `/etc/prometheus/jobs/node.json` file every minute
> 
> And I set refresh_interval to 15s in prometheus.yml

how you solve the issue?

**Comment by zhangxb1987** [comment]
@pc10201 how you override ? which api do you use?
