### ISSUE TITLE
Memory usage: Observing paging and swapping 

### ISSUE THREAD

**Issue by dhbarman** [prometheus/prometheus#4311]
## Proposal
**Use case. Why is this important?**

Better system performance. 

*Nice to have' is not a good use case :)*

## Bug Report
**What did you do?**

Nothing 

**What did you expect to see?**

No paging and swapping as memory available is high. 

**What did you see instead? Under which circumstances?**

Paging and swapping are observed on Prometheus nodes while memory is still available. 

**Environment**

* System information:

	Linux 4.1.12-124.15.2.el7uek.x86_64 x86_64

* Prometheus version:

   prometheus --version
   prometheus, version 2.2.1 (branch: HEAD, revision: bc6058c81272a8d938c05e75607371284236aadc)
  build user:       root@149e5b3f0829
  build date:       20180314-14:15:45
  go version:       go1.10

<img width="1440" alt="screen shot 2018-05-31 at 3 44 55 pm" src="https://user-images.githubusercontent.com/16171028/41877373-de5e5152-7885-11e8-9548-f3ccac4006b2.png">

**Comment by krasi-georgiev** [comment]
why do you think Prometheus is causing this?  AFAIK It is the OS that controls Paging and swapping.

At compaction or rules evaluation it might use more RAM so maybe this is when the OS decides to SWAP.

**Comment by dhbarman** [comment]
If OS controls the behavior, shouldn't we see consistent or uniform behavior ? We see occasional high swapping and paging. I am collecting more data which I will upload here.

**Comment by krasi-georgiev** [comment]
I imagine this happens at compaction when Prometheus needs more memory to expand and merge the blocks.

**Comment by krasi-georgiev** [comment]
> Is there anything we can do to avoid such spikes ? Or is it expected ?

It is to be expected. 

>  Does it have any correlation with incoming queries ?

yes any heavy queries will greatly increase memory usage.

**Comment by dhbarman** [comment]
Is there no mitigation step? Do you suggest that we should increase swap memory allocation? Do you have any code change in prometheus which will improve its memory footprint?

**Comment by krasi-georgiev** [comment]
@dhbarman did you get this resolved so I can close the issue?

**Comment by dhbarman** [comment]
@krasi-georgiev Have not resolved it completely. We will keep monitoring our servers. We plan to upgrade to a newer version of Prometheus too. You may close the ticket for now.

**Comment by krasi-georgiev** [comment]
ok, thanks. Feel free to add more updates.
