### ISSUE TITLE
Unhealthy targets filter not work 

### ISSUE THREAD

**Issue by songjiayang** [prometheus/prometheus#4319]
## what I see?
when I select unhealthy filter in page http://localhost:9090/targets, it doesn't hide the healthy targets.

![screen shot 2018-06-27 at 11 15 23 pm](https://user-images.githubusercontent.com/1459834/41983288-38b83664-7a60-11e8-9af2-bcea8ef7be4e.png)

### Prometheus version?
prometheus, version 2.3.1 (branch: HEAD, revision: 188ca45bd85ce843071e768d855722a9d9dabe03)
  build user:       root@82ef94f1b8f7
  build date:       20180619-16:01:25
  go version:       go1.10.3

**Comment by simonpasquier** [comment]
I can't reproduce it with Firefox. What's your browser? Can you check in the Javascript console if you have any error?

**Comment by songjiayang** [comment]
No error in Javascript console, I have tried Firefox, Chrome and Safari, but not work for me.

**Comment by simonpasquier** [comment]
Have you tried clearing the cache and reloading the page?

**Comment by simonpasquier** [comment]
Ah I get the confusion now. Currently the "Unhealthy" filter hides the jobs that have all targets healthy . If a job has only one down/unreachable target, it will be displayed as well as all its targets.

**Comment by songjiayang** [comment]
Got it, thanks for your description.
