### ISSUE TITLE
Service discovery Azure [Error discovery manager]

### ISSUE THREAD

**Issue by cosson-florent** [prometheus/prometheus#4325]
## Bug Report
**What did you do?**
I configured Service discover Azure and it worked during 1 months without problems but I got a strange error last night. See logs below.

**What did you expect to see?**
Should discovery VM without problems. I just restarted Prometheus to solve the problem but it appears again last night.

**What did you see instead? Under which circumstances?**
Logs error from discovery manager

**Environment**

* System information:

	Linux 4.15.0-1013-azure x86_64

* Prometheus version:

	version 2.2.0 

* Logs:
```
level=error ts=2018-06-29T07:08:44.372259Z caller=azure.go:275 component="discovery manager scrape" discovery=azure msg="Unable to get network interface" name=XXXXXerr="network.InterfacesClient#Get: Failure sending request: StatusCode=0 -- Original Error: Get https://management.azure.com/subscriptions/XXX-XXX-XXXXX/resourceGroups/osi/providers/Microsoft.Network/networkInterfaces/XXXX?api-version=2016-09-01: dial tcp: lookup management.azure.com on XXX.XXX.XX.XX:53: dial udp XXX.XX.XX: socket: too many open files"
```

**Comment by simonpasquier** [comment]
I'd say that your Prometheus service has hit the file descriptor limits. See https://github.com/prometheus/prometheus/wiki/FAQ#error-too-many-files-open for more details.

I'm going to close your request. If you need more help, please use the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users).
