### ISSUE TITLE
Failing gofmt tests

### ISSUE THREAD

**Issue by krasi-georgiev** [prometheus/prometheus#4332]
@brancz , @SuperQ do you remember why we run `make test` against .1.10 and 1.x? 

It seems that we always update the second target (currently 1.10.x) to latest stable anyway so we are running against the same versions on both targets most of the time.

There are some gofmt changes in 1.13 and Travis has some bug in travis that returns 1.13 for 1.x where it should return latest stable, but my question is should we just run 1.10 or at least run `make style` only for the laster golang stable.?

**Comment by krasi-georgiev** [comment]
some initial discussions in https://github.com/prometheus/prometheus/pull/4329#issuecomment-401806566

**Comment by SuperQ** [comment]
I don't really know the whole history.

**Comment by simonpasquier** [comment]
At least it isn't uniform across projects since AlertManager (at least) tests only against 1.10.x (which is pulling the correct version).

**Comment by brancz** [comment]
Not sure how to ensure this as our setup is quite entangled regarding this, but it sounds like we should run everything with the same version as we’re compiling the target binary with promu.

**Comment by krasi-georgiev** [comment]
ok , thanks

@simonpasquier do you want to update your PR https://github.com/prometheus/prometheus/pull/4331 to remove the 1.x alltogether so we can fix the tests and will revisit if needed.

**Comment by simonpasquier** [comment]
@krasi-georgiev this is done.
