### ISSUE TITLE
Add counter for prometheus query engine queries

### ISSUE THREAD

**Issue by d-shi** [prometheus/prometheus#4334]
## Proposal

Similar to https://github.com/prometheus/prometheus/issues/2325, but add one additional metric that is a counter for number of queries coming in to prometheus query engine. Right now there is a metric called `prometheus_engine_queries`, which is a gauge. We see that most of the time this gauge has a value of 0 (sometimes one data point will be 1).

We are trying to debug why `prometheus_engine_query_duration_seconds` latencies spike up to >10 seconds sometimes, and would like to know if it correlates to a massive number of queries coming in, but do not have this metric currently since the gauge is mostly 0 (so at least no real queuing of queries is happening).

**Comment by brian-brazil** [comment]
prometheus_engine_query_duration_seconds_count already covers this.

**Comment by d-shi** [comment]
Ah, thank you. Sorry didn't see that before.
