### ISSUE TITLE
Prometheus Server Logs to Fluentd

### ISSUE THREAD

**Issue by mumarniaz** [prometheus/prometheus#4337]
## Proposal
Currently, Prometheus server logs all logging information on `std::out` to console. Is there any configuration or feature in prometheus server to send these logs to fluentd directly? I have found this plugin:  [Fluentd logging driver](https://docs.docker.com/config/containers/logging/fluentd/ ) which run as a daemon set and send all pods logs to fluentd instead of only Prometheus server log.

**Use case. Why is this important?**
It will be important in scenarios where someone want to place these logs on some centralize location and analyze those logs instead of getting it directly from Prometheus pod.

**Comment by simonpasquier** [comment]
I don't feel that Prometheus needs to be modified to handle your use case. AFAIU it's up to you to setup your logging infrastructure to get the container logs and push them to your central location.

**Comment by krasi-georgiev** [comment]
yeah logging is displayed to stdout/stderr be default and it is up to the systemd or the container orchestrator  to redirect the logs to wherever you decide.

@mumarniaz this isn't something for us so I advise continuing on google search or other more relevant groups :+1:
