### ISSUE TITLE
retention not working in version 2.3.1

### ISSUE THREAD

**Issue by shirpx** [prometheus/prometheus#4348]
Hey,
i set prometheus retention to be 1h with flag
 --storage.tsdb.retention="1h"
can see it in the ui but still can query data longer than 1h.

i am using the latest version

ui shows 1h:
https://screenshot.net/3dk9riq

more than 1h data:
https://screenshot.net/20plrad

i have been asked to open a bug when asked in prometheus-users

**Comment by eladamitpxi** [comment]
anything we can do to expedite / triage this issue?

**Comment by krasi-georgiev** [comment]
as per the discussion in https://github.com/prometheus/tsdb/pull/357 it works as expected.
