### ISSUE TITLE
Prometheus fails to recover after getting KILLed 

### ISSUE THREAD

**Issue by discordianfish** [prometheus/prometheus#435]
Hi,

I KILLed prometheus accidentally. After restarting, apparently recovered a bunch of samples but then panic'ed due a index being ot of range: https://gist.github.com/discordianfish/18b5c2eaea2e2d66858f

- Affected: prometheus, version 0.9.0rc2 (branch: master, revision: 401decc)

**Comment by juliusv** [comment]
@brian-brazil  encountered the same issue in #437 -  see there for additional info.

**Comment by beorn7** [comment]
If the file length of a series file is consistent with the information in the checkpoint, the file should only be stat'd during crash recovery, not open'd. When you see "Cecovered metric [...]: head chunk found among the [...] recovered chunks in series file.", then the file size was inconsistent and the file had to be inspected. That happens if a chunk was written to the file after the last checkpoint was taken. Series with a high ingestion rate will more often be in that state.

What was your ingestion rate? What was your checkpointing interval?

**Comment by brian-brazil** [comment]
We're using the defaults, and have about 23k series scraped once a minute.

**Comment by beorn7** [comment]
My question was related to the slowness, which (in my current theory) can happen if you have relatively few series but write chunks quite frequently (more often than checkpoints being written). @brian-brazil You had no trouble with slowness of crash recovery, but @discordianfish had, so I was particularly interested in his numbers of samples per series.

**Comment by discordianfish** [comment]
@beorn7 My scrape interval is 60s, except when scraping itself (still 15s)

**Comment by beorn7** [comment]
@discordianfish Thanks. So there goes my theory.

I tried several scenarios now, and the crash recovery behaved as expected. In your case, it had to seek to many series files, and that can only happen if most series have a head chunk that is different from the one in the most recent checkpoint. I plan to implement a mechanism that will trigger a snapshot early if that happens.

Perhaps something delayed the checkpointing in your case.

All of that is still only about the slowness, not about the panic.

Still investigating...

**Comment by beorn7** [comment]
Modified version of my theory: If many metrics have the same collection pattern (i.e. they are scraped with the same interval, and scraping similarly structured data, which has a similar compression behavior), then all those metrics will start a new chunk at approx. the same time. Just after that has happened, all the corresponding time series are "dirty", i.e. the head chunk in the last checkpoint is not the current head chunk. If a crash happens at that time, all those series have to be checked during recovery, requiring a disk seek each.

Three fixes related to this issue went into the code now:
- Fix of the post-recovery crash reported by Brian, too.
- Fix of a deadlock during shutdown (which might have created the unclean shutdown in your case in the first place).
- Introduced a new heuristics to checkpoint earlier if many series are "dirty".

I assume that addresses all the issues, but in general, the whole crash recovery desperately needs proper automated testing, for which I'll open a separate issue.
