### ISSUE TITLE
get Max  function report bug

### ISSUE THREAD

**Issue by hellojukay** [prometheus/prometheus#4353]
## Proposal
query expression is prometheus ui:
```txt
 max((100-ssCpuIdle{instance="10.95.135.202"}))
```
## Bug Report
this query call api 
```txt
/api/v1/query?query=%20max((100-ssCpuIdle%7Binstance%3D%2210.95.135.202%22%7D))&time=1530795419.956&_=1530795412900
```
so it return error result , i use grafana , the same expression return right result, grafana call api 
```txt
/query_range?query=max((sum(dskUsed%7Binstance%3D%2210.95.135.202%22%7D)%2Fsum(dskTotal%7Binstance%3D%2210.95.135.202%22%7D))*100)&start=1528200000&end=1530813600&step=21600"
```
**What did you expect to see?**
i think prometheus ui should also call api
```txt
GET /api/v1/query_range
```

**Comment by simonpasquier** [comment]
The Console tab of the Prometheus UI is doing an instant query (which is hitting `/api/v1/query`). If you want a range query, you need to click the Graph tab (see below).

![image](https://user-images.githubusercontent.com/2587585/42382894-e7740710-8135-11e8-8014-fb8095d2eea5.png)

It looks as if this is actually a question about usage and not development so I'm going to close this issue.

To make your question, and all replies, easier to find, we suggest you move this over to our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search. If you prefer more interactive help, join or our [IRC channel](https://webchat.freenode.net/?randomnick=1&channels=prometheus), #prometheus on irc.freenode.net. Please be aware that our IRC channel has no logs, is not searchable, and that people might not answer quickly if they are busy or asleep. If in doubt, you should choose the mailing list.
