### ISSUE TITLE
Make subexpressions of rules/alerts/expressions links to their tabular view

### ISSUE THREAD

**Issue by juliusv** [prometheus/prometheus#436]
Whenever showing rules, alerts, or single expressions on the web interface, split up expressions into subexpressions and make each a link to a suitable graph/tabular view for the subexpression.

**Comment by Gouthamve** [comment]
Closing based on the convo with @juliusv on IRC (summarising):

>  "foo / bar", the "/" would be a link to the total expression, the "foo" and the "bar" links to just those
>  which makes it hard to click on the whole expression.

> This makes sense for borgmon with huge alerting rules but not prometheus.
