### ISSUE TITLE
spring boot project server returned HTTP status 401 Unauthorized

### ISSUE THREAD

**Issue by zhangxin2016** [prometheus/prometheus#4361]
## Proposal
**Use case. Why is this important?**

*Nice to have' is not a good use case :)*

## Bug Report
**What did you do?**

**What did you expect to see?**

**What did you see instead? Under which circumstances?**

**Environment**

* System information:

	insert output of `uname -srm` here

* Prometheus version:

	insert output of `prometheus --version` here

* Alertmanager version:

	insert output of `alertmanager --version` here (if relevant to the issue)

* Prometheus configuration file:
```
insert configuration here
```

* Alertmanager configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```

**Comment by krasi-georgiev** [comment]
Thanks for your report. It looks as if this is actually a question about usage and not development.

no crash, no panic = support question :wink: 


To make support question, and all replies, easier to find, I suggest you move this to our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users). 

If you haven't looked already you might find your answer in the [official docs and examples](https://prometheus.io/docs/introduction/overview/) or by searching in the [users](https://groups.google.com/forum/#!forum/prometheus-users) or [devs](https://groups.google.com/forum/#!forum/prometheus-developers) groups.
The [  #prometheus IRC channel ](https://webchat.freenode.net/?channels=prometheus) is also a great place to mix up with the community and ask questions (don't be afraid to answers few while waiting).

If you think this is not purely a support question, feel free to comment in here or in the [dev mailing list](https://groups.google.com/forum/#!forum/prometheus-developers).

Once your questions have been answered, please add a link to the solution to help other Prometheans in trouble reaching this from a search :+1:
