### ISSUE TITLE
Unused point slices are not added back to the pool by the matrix selector

### ISSUE THREAD

**Issue by roganartu** [prometheus/prometheus#4362]
A recent change to promql/engine.go moved the call to `putPointSlice` from the evaluator finalizers in the `matrixSelector` method to elsewhere:

https://github.com/prometheus/prometheus/commit/dd6781add2390eb2f2251e108f2ef835eba44b05#diff-83539908220a826e39b7ba3a4f27d5d6L862

However, now only the used point slices are returned to the pool:
https://github.com/prometheus/prometheus/blob/dd6781add2390eb2f2251e108f2ef835eba44b05/promql/engine.go#L732

I may be missing something here, but afaict unused (ie: empty) point slices should be returned to the pool immediately, since no reference to them is held after the current iteration in `matrixSelector` anyway.

**Comment by juliusv** [comment]
@brian-brazil
