### ISSUE TITLE
metrics with same metric name cannot use binary arithmetic operators to calculate.

### ISSUE THREAD

**Issue by cauwulixuan** [prometheus/prometheus#4365]
## Proposal
**Use case. Why is this important?**

*Nice to have' is not a good use case :)*

## Bug Report
**What did you do?**
I have defined a metric name "hadoop_namenode_fsname_system_capacity_bytes" with different labels.
And metrics can be scraped like:
```
# HELP hadoop_namenode_fsname_system_capacity_bytes Current DataNodes capacity in each mode in bytes
# TYPE hadoop_namenode_fsname_system_capacity_bytes gauge
hadoop_namenode_fsname_system_capacity_bytes{mode="UsedNonDFS"} 203908392012.0
hadoop_namenode_fsname_system_capacity_bytes{mode="Total"} 422567952384.0
hadoop_namenode_fsname_system_capacity_bytes{mode="Used"} 156852491239.0
hadoop_namenode_fsname_system_capacity_bytes{mode="Remaining"} 144899711054.0
```
Now I want to calculate `capacity_used_ratio` using:
```
hadoop_namenode_fsname_system_capacity_bytes{mode="Used"} / hadoop_namenode_fsname_system_capacity_bytes{mode="Total"}
```

**What did you expect to see?**
The result of the calculation.

**What did you see instead? Under which circumstances?**
no data

**Environment**

* System information:

	insert output of `uname -srm` here

* Prometheus version:

	insert output of `prometheus --version` here

* Alertmanager version:

	insert output of `alertmanager --version` here (if relevant to the issue)

* Prometheus configuration file:
```
insert configuration here
```

* Alertmanager configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```

**Comment by cauwulixuan** [comment]
Any ideas? Many thanks.

**Comment by krasi-georgiev** [comment]
Thanks for your report. It looks as if this is actually a question about usage and not development.

no crash, no panic = support question :wink: 


To make support question, and all replies, easier to find, I suggest you move this to our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users). 

If you haven't looked already you might find your answer in the [official docs and examples](https://prometheus.io/docs/introduction/overview/) or by searching in the [users](https://groups.google.com/forum/#!forum/prometheus-users) or [devs](https://groups.google.com/forum/#!forum/prometheus-developers) groups.
The [  #prometheus IRC channel ](https://webchat.freenode.net/?channels=prometheus) is also a great place to mix up with the community and ask questions (don't be afraid to answers few while waiting).

If you think this is not purely a support question, feel free to comment in here or in the [dev mailing list](https://groups.google.com/forum/#!forum/prometheus-developers).

Once your questions have been answered, please add a link to the solution to help other Prometheans in trouble reaching this from a search :+1:

**Comment by cauwulixuan** [comment]
It works by ignore "mode" label, because by default Prometheus wants to match all labels on both sides:
```
hadoop_namenode_fsname_system_capacity_bytes{mode="Used"} / ignoring(mode) hadoop_namenode_fsname_system_capacity_bytes{mode="Total"}
```
Wish could help others.

**Comment by krasi-georgiev** [comment]
Thanks!
