### ISSUE TITLE
consul_sd_configs bug

### ISSUE THREAD

**Issue by zhangjianweibj** [prometheus/prometheus#4366]
prometheus version:last
source code:  discovery/consul/consul.go
issue:consule service has supported meta property for some time.

![image](https://user-images.githubusercontent.com/18585129/42507570-35cb42e4-8478-11e8-80cb-b80dd94b4749.png)

but prometheus has not updated the corresponding entity.i register a service in consul with some metadata info.but prometheus  shows some information without the metadata info.

**Comment by zhangjianweibj** [comment]
![image](https://user-images.githubusercontent.com/18585129/42509081-5db5a74a-847d-11e8-88e6-483c37ac8913.png)

 CatalogService type also support serviceMeta

**Comment by simonpasquier** [comment]
@zhangjianweibj IIUC your request matches with #4280 so please comment there. Note that it isn't going to be merged right now because there's a feature moratorium.

**Comment by zhangjianweibj** [comment]
@simonpasquier yeah,it is a very useful and necessary feature.wish the PR can be merged as soon as possbile.very thanks.
