### ISSUE TITLE
metrics metadata can inherit from job

### ISSUE THREAD

**Issue by zhangjianweibj** [prometheus/prometheus#4368]
prometheus verison:last

issue: metrics get from prometheus should inherit metadata from scrape job.or users can config the feature.in this situation，prometheus pull meric from client can reduce additional label and reduce network burden.what is more,users can use prometheus more flexibly and effectively.

for example,i want every metric samples get from prometheus hava lables service_id and service_port,how to achieve this goal?
![image](https://user-images.githubusercontent.com/18585129/42558528-1ba8caa6-8524-11e8-86af-30ef0fb7006c.png)

![image](https://user-images.githubusercontent.com/18585129/42558617-65859334-8524-11e8-84b8-c628177dc4f3.png)

**Comment by jojohappy** [comment]
You can use the `relabel_config` to replace the `__meta_` label as a normal label.

example
```
relabel_configs:
- source_labels: [__meta_consul_node]
  separator: ;
  regex: (.*)
  target_label: node
  replacement: $1
  action: replace
- source_labels: [__meta_consul_service]
  separator: ;
  regex: (.*)
  target_label: consul_service
  replacement: $1
  action: replace
- source_labels: [__meta_consul_tag]
  separator: ;
  regex: (.*)
  target_label: consul_tag
  replacement: $1
  action: replace
- source_labels: [__meta_consul_dc]
  separator: ;
  regex: (.*)
  target_label: consul_dc
  replacement: $1
  action: replace
- source_labels: [__meta_consul_service_port]
  separator: ;
  regex: (.*)
  target_label: consul_service_port
  replacement: $1
  action: replace
```

**Comment by simonpasquier** [comment]
Thanks for your report and @jojohappy for the answer. I'm closing the issue for now.

For future questions, we suggest you use our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search. If you prefer more interactive help, join or our [IRC channel](https://webchat.freenode.net/?randomnick=1&channels=prometheus), #prometheus on irc.freenode.net. Please be aware that our IRC channel has no logs, is not searchable, and that people might not answer quickly if they are busy or asleep. If in doubt, you should choose the mailing list.
