### ISSUE TITLE
Derivative of a constant counter is _close_ to zero, instead of zero

### ISSUE THREAD

**Issue by maurorappa** [prometheus/prometheus#4373]
**What did you do?**
I have a simple constant counter:
![counter](https://user-images.githubusercontent.com/4287381/42623920-04bdbd90-85bc-11e8-93ef-a7d7c0018769.JPG)

I want its derivative, being a constant it should be zero, but it looks like some calculation is done and rounding is appening.
![deriv-counter](https://user-images.githubusercontent.com/4287381/42623921-04e9656c-85bc-11e8-8a60-aef3bb9c6eb2.JPG)

**What did you expect to see?**

By definition, its derivative should be zero

**What did you see instead? Under which circumstances?**

a value close to zero, which of course could be rounded to it :)
Being a special case (constant value) is could return zero immediately without calculations (performance saving)

* System information:

Linux 3.10.0-693.11.6.el7.x86_64 x86_64insert output of `uname -srm` here

* Prometheus version:

prometheus, version 2.3.0 (branch: HEAD, revision: 290d71791a507a5057b9a099c9d48703d86dc941)
  build user:       root@d539e167976a
  build date:       20180607-08:46:54
  go version:       go1.10.2

**Comment by brian-brazil** [comment]
This smells like floating point inaccuracy, which there are limited options for dealing with as it'd likely just pop up in another form. I'm not sure we should special case, do you have a proposed tweak to the order of operations?

**Comment by maurorappa** [comment]
I understand we don't want to complicate the code for edge cases, one approach could be using the function 'funcChanges'  in 'funcDeriv' before calling 'linearRegression'. 
Of course it needs to be benchmarked to see any saving (time,cpu), I could give a go if you think it's useful.

**Comment by brian-brazil** [comment]
I'd classify that as special casing. I'm not sure there's much we can sanely do here.

**Comment by maurorappa** [comment]
your call ;)
feel free to close it

**Comment by brian-brazil** [comment]
I don't see anything obvious we can do.

Also, that's a counter. You should only use deriv on gauges. You want rate.
