### ISSUE TITLE
max_over_time treats NaN as the max

### ISSUE THREAD

**Issue by jacksontj** [prometheus/prometheus#4385]
## Bug Report
**What did you do?**
a simple query like `max_over_time(foo[30m])`

**What did you expect to see?**
I expected to see the largest value

**What did you see instead? Under which circumstances?**
If there was a single `NaN` in the time range then the value returned is NaN. I made an example test case (which fails) to showcase the issue: https://github.com/jacksontj/prometheus/commit/a36f35153d4c230847bbfe992992b1f78f492f37

**Environment**

* Prometheus version:

	verified on 2.2, 2.3, and master

**Comment by brian-brazil** [comment]
Thanks for the report. We must have not fixed this for min/max while we were doing the others.

**Comment by jacksontj** [comment]
I can submit a PR with the test+fix. What is the desired behavior? Should NaNs be treated as the smallest thing? Or excluded from comparison? Personally seems like they should be excluded, but either way works for me.

**Comment by brian-brazil** [comment]
We should do the same as `max` does, and only return a NaN if there's only NaNs.

**Comment by jacksontj** [comment]
#4386 with the fix and some tests. I noticed that `clamp_min` and `clamp_max` still use the math.Max/Min functions, so presumably have similar issues.

**Comment by juliusv** [comment]
@jacksontj It's not clear to me what the right behavior of `clamp_{min,max}` would be in the face of `NaN`s, whether it should simply preserve `NaN`s or take the clamp value. Probably the current behavior is ok?

**Comment by brian-brazil** [comment]
I'm not sure what the right behaviour is there either, I'd say we wait until a use case comes up.
