### ISSUE TITLE
TimeOut in Histogram and Summaries

### ISSUE THREAD

**Issue by atulverma1997** [prometheus/prometheus#4387]
Proposal: 
Sometimes a user start timer, but don't want to stop it. In such cases, the duration is not logged in any bucket. So, there should be a timeout settings in Histogram/Summary, so that user can configure after how much time, the timer should be automatically stopped, and logged in the appropriate bucket. 

Use Case: 
In my case, I send an HTTP request to an API, which could give a TimeOutException. In this case, I start the timer before sending the request. Here, I catch a TimeOutException in which I log the exception using Counter metric, but don't stop the Histogram.Timer. That is why, the timer starts, but it dont stop and is not logged in any of the bucket. There can be timeout setting in Histogram in which I can configure that after this much time, the duration should be logged in infinity bucket

**Comment by brian-brazil** [comment]
You should file this against the client library you are using, as this repository is for the Prometheus server itself.
I would say in this case that it's your responsibility to stop the timer.

**Comment by atulverma1997** [comment]
Thank you @brian-brazil ,

Filing against the appropriate client library.
