### ISSUE TITLE
prometheus process excessive memory usage

### ISSUE THREAD

**Issue by wlibo666** [prometheus/prometheus#4394]
I deployed prometheus 2.3.0 on the kubernetes cluster，when I collect application monitoring data，I found that the prometheus process has been increasing memory usage.
I want to limit the memory usage of the prometheus process to 1G, what should I do?

**Comment by krasi-georgiev** [comment]
Thanks for your report. It looks as if this is actually a question about usage and not development.

no crash, no panic = usage question :wink: 


To make support question, and all replies, easier to find, I suggest you move this to our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users). 

If you haven't looked already you might find your answer in the [Common errors](https://github.com/prometheus/prometheus/wiki/FAQ) or the  [official docs and examples](https://prometheus.io/docs/introduction/overview/) or by searching in the [users](https://groups.google.com/forum/#!forum/prometheus-users) or [devs](https://groups.google.com/forum/#!forum/prometheus-developers) groups.
The [  #prometheus IRC channel ](https://webchat.freenode.net/?channels=prometheus) is also a great place to mix up with the community and ask questions (don't be afraid to answers few while waiting).

If you think this is not purely a support question, feel free to comment in here or in the [dev mailing list](https://groups.google.com/forum/#!forum/prometheus-developers).

Once your questions have been answered, please add a link to the solution to help other Prometheans in trouble reaching this from a search :+1:
