### ISSUE TITLE
 feature request -reretain and compression

### ISSUE THREAD

**Issue by Jerryhax** [prometheus/prometheus#4401]
## Proposal
**Use case. Why is this important?**
I want to save more and longer data, such as monitoring data for one thousand servers a year. In order to save storage, the data in one month is fully retained (15 seconds to scrape the data), and data that is only retained for 30 seconds or once per minute for more than one month.
what should I do？Can u add  flags to set these?

**Comment by krasi-georgiev** [comment]
It looks as if this is actually a question about usage and not development.

no crash, no panic = usage question :wink: 


To make support question, and all replies, easier to find, I suggest you move this to our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users). 

If you haven't looked already you might find your answer in the [Common errors](https://github.com/prometheus/prometheus/wiki/FAQ) or the  [official docs and examples](https://prometheus.io/docs/introduction/overview/) or by searching in the [users](https://groups.google.com/forum/#!forum/prometheus-users) or [devs](https://groups.google.com/forum/#!forum/prometheus-developers) groups.
The [  #prometheus IRC channel ](https://webchat.freenode.net/?channels=prometheus) is also a great place to mix up with the community and ask questions (don't be afraid to answers few while waiting).

If you think this is not purely a support question, feel free to comment in here or in the [dev mailing list](https://groups.google.com/forum/#!forum/prometheus-developers).

Once your questions have been answered, please add a link to the solution to help other Prometheans in trouble reaching this from a search :+1:
