### ISSUE TITLE
Rules page returns error in V2.3.2

### ISSUE THREAD

**Issue by BartVerc** [prometheus/prometheus#4407]
## Bug Report
**What did you do?**
Opening prometheus in a browser on `/rules`.
**What did you expect to see?**
A page with all rules defined in the configuration.
**What did you see instead? Under which circumstances?**
I got the response: `error executing template rules.html: template: rules.html:79:57: executing "content" at <.GetEvaluationTime.S...>: can't evaluate field GetEvaluationTime in type *rules.Group`
**Environment**
Dockerhub: prom/prometheus:v2.3.2 
version 2.3.2 
go1.10.3
* System information:
Linux 4.13.0-41-generic x86_64
* Prometheus version:
version 2.3.2

**Comment by simonpasquier** [comment]
Hmm, that is weird. Can you share your Prometheus logs and full configuration (including rules)?

**Comment by BartVerc** [comment]
Logs:
[logs_prom_v232](https://github.com/prometheus/prometheus/files/2227019/logs_prom_232.txt)
Config:
[prometheus.yml](https://github.com/prometheus/prometheus/files/2227015/prometheus.yml.txt)
[rules.yml](https://github.com/prometheus/prometheus/files/2227016/rules.yml.txt)

**Comment by juliusv** [comment]
Confirmed broken in master, working in 2.3.2. `git bisect`-ing now.

**Comment by juliusv** [comment]
Badumm-tssss: I broke this in https://github.com/prometheus/prometheus/commit/9e3171f6e3ff36c820b2c987194dd1baf17e401a

Renamed some functions in there, but wasn't aware they were being called from a template!

**Comment by juliusv** [comment]
(gonna work on a fix)

**Comment by BartVerc** [comment]
Thanks guys!
