### ISSUE TITLE
Configurable limit to scrape concurrency

### ISSUE THREAD

**Issue by hawkw** [prometheus/prometheus#4408]
## Proposal

When Prometheus is configured with more than one scrape target, it sends requests to all those targets concurrently. In some cases, a very high number of concurrent requests can cause issues.

I propose adding a configuration option that limits the number of concurrent requests when scraping. When Prometheus issues a request to a scrape target, it should track the number of requests that are currently in-flight, and test to see whether it has reached the concurrency limit, if one has been configured. If the limit has been reached, Prometheus should wait until some in-flight requests complete before making more requests.

**Use case. Why is this important?**

Linkerd 2 deploys a Prometheus instance behind a proxy. This proxy places a limit on the number of routes (in this case, HTTP authorities) which can concurrently have requests in flight to them. When the limit is reached, the proxy will return errors. When the Prometheus instance attempts to scrape more targets than the proxy's route limit concurrently, the route cache bound is reached and subsequent scrape requests result in errors. Thus, the scrape is incomplete. If scrape concurrency could be limited, then routes whose requests have finished would be considered "inactive" by the proxy and could be evicted from the route cache, allowing new requests to succeed.

See linkerd/linkerd2#1234 and linkerd/linkerd2#1322 for more information on this specific use-case.

**Comment by briansmith** [comment]
Let's not fixate on the specific issue of a proxy imposing some limit on Prometheus's scraper. It sounds like Prometheus is probably doing something close to what we're asking for anyway.

> scrapes are already splayed over time to avoid spikes.

That sounds like what we ultimately would want anyway, however we're not seeing the splaying done in the way we expected. Could you please point us to where we can understand how this splaying is done?  Are there any tuning parameters to control it?

**Comment by brian-brazil** [comment]
It's based on a hash of the target labels, and with 100+ targets it should
be reasonably uniform. It is not configurable.

**Comment by simonpasquier** [comment]
> Could you please point us to where we can understand how this splaying is done?

https://github.com/prometheus/prometheus/blob/6a464ae174f74808cbcc7fe0dec97dbbec3b2847/scrape/target.go#L125-L139

**Comment by RichiH** [comment]
Currently doing a bug scrub. It's near-certain that this will not be implemented.
