### ISSUE TITLE
Test correct rendering of template-based web endpoints

### ISSUE THREAD

**Issue by juliusv** [prometheus/prometheus#4417]
See https://github.com/prometheus/prometheus/pull/4416

The template-based web endpoints such as `/alerts`, `/rules`, etc., refer to Go variable and method names that the compiler cannot statically verify. When the Go names get renamed, it breaks the templates without anyone noticing. It would be good to have some kind of e2e test that at least checks whether those pages render without an error.

**Comment by minhlongdo** [comment]
@juliusv would it be ok for me to pick up this issue?

**Comment by brian-brazil** [comment]
Please go ahead.

**Comment by minhlongdo** [comment]
@brian-brazil do you have any advice on how I should test endpoints that have `defer h.mtx.RUnlock()` in the handler? Like the `/config` endpoint

**Comment by brian-brazil** [comment]
I don't see why those would be any different to test.

**Comment by minhlongdo** [comment]
@brian-brazil I guess this issue can be closed?
