### ISSUE TITLE
prometheus could not log to syslog

### ISSUE THREAD

**Issue by veksh** [prometheus/prometheus#4420]
Prometheus 2.3.2 lost an option for syslog logging (it was looking like
`--log.format=logger:syslog?appname=prometheus&local=5`), and now has only `--log.level`
and stderr logging.

**Comment by krasi-georgiev** [comment]
Which was the last version this worked on? 
Prometheus switched logging packages few versions back.

**Comment by veksh** [comment]
Cannot remember exact version (`log.format=logger.syslog` is still OK with e.g. node_exporter). So this change is intentional? It is a pity then, having syslog was great for general troubleshooting. Some operational and configuration errors are hard to catch w/o logs (e.g. rule evaluation errors).

**Comment by simonpasquier** [comment]
The flag has been dropped since 2.0.0 (see #3219). There's https://github.com/prometheus/common/pull/136 to add JSON logging to the common log library and eventually to Prometheus. Once that's in, it _might_ be possible to enable back Syslog (no commitment though).

**Comment by veksh** [comment]
JSON would be nice too, but it is syslog that I miss. For systemd-based Linux that is less of an issue, but for other platforms there is no options to catch Prometheus messages except redirecting stdout to a file, which is a bit less flexible than standard syslog.

**Comment by simonpasquier** [comment]
> redirecting stdout to a file, which is a bit less flexible than standard syslog.

Agreed. What I wanted to say is that adding JSON logging will bring back the `log.format` flag. Since the underlying log library already supports Syslog, it shouldn't be too complicated to put it back. Again just my thoughts.

**Comment by brian-brazil** [comment]
The decision thus far is that supporting stdout is sufficient, as the user can then hook that in however they like whether that be syslog or something else.

**Comment by ramato-procon** [comment]
currently logs are written to a log file in /tmp folder additionally. Writing logs to /tmp in a docker container is an antipattern IMHO. Therefore there should be an option to disable file logging at all.
Additonally JSON logging is a must for ELK stack.

**Comment by brian-brazil** [comment]
Prometheus does not write logs to a file, only to stdout. It is something in your setup that is doing that.

**Comment by ramato-procon** [comment]
Yes, you're right. The logs where created by OpenShift. Excuse me.

**Comment by ntindall** [comment]
I wrote this to convert logfmt to json .... https://github.com/ntindall/logfmt2json
but can we just merge  prometheus/common#136 to bring back the json support?

**Comment by dlazerka** [comment]
@brian-brazil 
> Prometheus does not write logs to a file, only to stdout.
Actually, prometheus 2.2.1 writes to STDERR, not STDOUT. How to make it write to stdout when I don't have shell access? E.g. I'm running official vanilla `prom/prometheus` docker image on k8s. And by default, my logging collectors mark all the normal logs as errors because STDERR.

**Comment by RichiH** [comment]
Currently doing a bug scrub. Consensus was this will not be implemented, but feel free to re-open if you feel strongly.

**Comment by dohnuts** [comment]
How can people ignore the fact STDOUT et STDERR is only two level and that parsing 'info' or whatever is printed to manage log level is outrageously inefficient, prone to problem , and ignore massive existing infrastructure to collect/analyze/store logs , those infrastructure may not want to use systemd like launcher, most of them not even managing the issue.
Moreover Logging to hard drive is not always an option .
Facility are ignored to.

**Comment by dohnuts** [comment]
Parsing stdout to recover  log level  and then send to syslog is inefficient, please bring back syslog for logging.
