### ISSUE TITLE
Could not find scrap data  of prometheus in postgresql database 

### ISSUE THREAD

**Issue by skmurali** [prometheus/prometheus#4422]
I have Prometheus , postgresql 10 and prometheus Postgresql adapter installed and configured sucessfully.  I could see from localhost:9201 of adapter message saying that it pushed metrics into remote postgresql. Further I have small piece of code keep pushing scrap data for testing purpose. 
# my global config. When I go to psql and query. metrics table from Postgres database it did not have anything. prometheus metric collectors running successfully. Environment Mac OS. 
-------prometheus.yml
global:
  scrape_interval:     2s
  evaluation_interval: 2s

  external_labels:
    monitor: 'ATL-monitor'

scrape_configs:
  - job_name: 'GBIATLEngneering'
    honor_labels: true
    static_configs:
      - targets: ['localhost:8000']

  - job_name: 'production'
    honor_labels: true
    static_configs:
      - targets: ['localhost:8080', 'localhost:8081']
        labels:
          group: 'production'

  - job_name: 'pushmetrics'
    honor_labels: true
    static_configs:
      - targets: ['localhost:8082']
        labels:
          group: 'canary'

remote_write:
  - url: "http://localhost:9201/write"
remote_read:
  - url: "http://localhost:9201/read"

**Comment by simonpasquier** [comment]
Thanks for your report. It looks as if this is actually a question about usage.

To make your question, and all replies, easier to find, we suggest you move this over to our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search. If you prefer more interactive help, join or our [IRC channel](https://webchat.freenode.net/?randomnick=1&channels=prometheus), #prometheus on irc.freenode.net. Please be aware that our IRC channel has no logs, is not searchable, and that people might not answer quickly if they are busy or asleep. If in doubt, you should choose the mailing list.

Once your questions have been answered, please add a short line pointing to relevant replies in case anyone stumbles here via a search engine in the future.
