### ISSUE TITLE
Consul SD Config connection leak

### ISSUE THREAD

**Issue by ashepelev** [prometheus/prometheus#4425]
## Proposal
**Use case. Why is this important?**
Consul SD Target Discovery

## Bug Report
**What did you do?**
Using consul_sd_config
**What did you expect to see?**
Discovering targets with stable work without restarts
**What did you see instead? Under which circumstances?**
Host is running out of FDs. The FDs are used for established connections with consul
**Environment**
Ubuntu 16.04
* System information:
Linux 4.4.0-83-generic x86_64

* Prometheus version:
prometheus, version 2.3.2 (branch: HEAD, revision: 71af5e29e815795e9dd14742ee7725682fa14b7b)
  build user:       root@5258e0bd9cc1
  build date:       20180712-14:02:52
  go version:       go1.10.3

* Alertmanager version:
alertmanager, version 0.15.1 (branch: HEAD, revision: 8397de1830f154535a31150f9262da0072d8725d)
  build user:       root@efde7f9485ae
  build date:       20180712-18:25:27
  go version:       go1.10.3

* Prometheus configuration file:
  - job_name: consul-services
    consul_sd_configs:
     - server: consul-server
       token: token-token-token
       datacenter: dc
    relabel_configs:
      - source_labels: [__meta_consul_tags]
        regex: ^.*prometheus_exporter.*$
        action: keep

* Alertmanager configuration file:

* Logs:
Logs don't provide relevant information.

FD Usage:
`lsof -u prometheus | grep consul | wc -l`
`4518`

process_open_fds on the host: 
![image](https://user-images.githubusercontent.com/6569080/43271540-7507d15e-9100-11e8-8e76-386e668e62d4.png)

On the July 12 we've upgraded from 2.0.0 to 2.3.2 release
Dropdowns are service restarts.

There was already closed issue: [https://github.com/prometheus/prometheus/issues/3096](url)

**Comment by brian-brazil** [comment]
Do the net_conntrack_dialer metrics also indicate it's consul?

@iksaif

**Comment by ashepelev** [comment]
@brian-brazil 
Thank you for your answer and correct metric to investigate. We've run this query on our Prom infra.
![image](https://user-images.githubusercontent.com/6569080/43316704-ca00d6fe-91a2-11e8-9fbd-f97516dcbe87.png)
As we can see only one node started to ignore connection utilization. Unfortunately we don't know the reasons. Our infra consists of two prometheus nodes, each has similar configuration, collecting similar targets. They are deployed from the similar configuration role. The only difference, that the second one is backup and we disable alerting on it so we won't have alert duplicates. The alerting is enabled back if we detect that there are less than two prometheus servers are healthy. Something like this:
`      {{ if lt (len ( service "exporter_prometheus_server|passing" )) 2 }}
alerting:
  alertmanagers:
    - timeout: 1s
      static_configs:
        - targets: {{ key "prometheus/alertmanager_targets" }}
      {{ end }}
`

**Comment by iksaif** [comment]
FYI: I won't have a stable internet connection in the next two weeks but I'll look at this issue as soon as I'm back.

Looking at your configuration, you use metric relabeling to filter services. If you have a lot of services this is likely to watch all of them, then drop the ones that don't have the tag. Check https://prometheus.io/docs/prometheus/latest/configuration/configuration/#%3Cconsul_sd_config%3E, you can use the `tag` option to directly look only at services with a given tag.

**Comment by surmehta** [comment]
We are using prometheus version 2.3.1 and facing same issue. We also changed from metric relabeling option to use the tag for filtering services and still seeing connection leaks. 

`- job_name: consul-nodes 
  sample_limit: 100000
  consul_sd_configs:
    - server: 'consul.service.vci:8500'
      tag: 'prometheus_enabled'
  relabel_configs:
    - source_labels: [__meta_consul_service]
      target_label: job
    - action: labelmap
      regex: __meta_consul_metadata_prometheus_(.*)`

Here is the graph with net_conntrack_dialer_conn_established_total metrics

![image](https://user-images.githubusercontent.com/17069554/43407230-238f2e78-93ec-11e8-8100-5c42ec7676e9.png)

There seems to be a correlation between connection leaks and configuration reloads  [http://localhost:9090/-/reload](http://localhost:9090/-/reload). With each reload there is an increase in connection count and the total connections count never goes down.

**Comment by brian-brazil** [comment]
net_conntrack_dialer_conn_established_total is a counter so will always go up, if it's increasing faster than net_conntrack_dialer_conn_closed_total you have a problem.

**Comment by surmehta** [comment]
net_conntrack_dialer_conn_closed_total{dialer_name="consul_sd",instance="localhost:9090",job="scrape-targets"} metrics count is zero.

![image](https://user-images.githubusercontent.com/17069554/43411067-1ce3512a-93f7-11e8-8681-8100585dc8c1.png)

**Comment by brian-brazil** [comment]
That sounds like a leak then, but not in Consul.

This is something we encountered before but never fully resolved. Are you using HTTPS?

**Comment by surmehta** [comment]
No. we are using http

**Comment by surmehta** [comment]
@ashepelev We are using client-go library to watch for changes in specific kubernetes resources and call reload API

**Comment by simonpasquier** [comment]
I confirm that Consul SD is leaking connections on reloads. Working on a fix.
