### ISSUE TITLE
Feat Req: Remote read hint for /api/v1/series

### ISSUE THREAD

**Issue by mtanda** [prometheus/prometheus#4428]
## Proposal
**Use case. Why is this important?**
Currently, `GET /api/v1/series` will read datapoints from remote read endpoint.
If remote read endpoint has "label" index, the endpoint don't need actual datapoints, just return matched label pair is enough to work the API.

**Comment by juliusv** [comment]
Related: https://github.com/prometheus/prometheus/issues/4057

**Comment by gouthamve** [comment]
This is very similar in scope to #4057, closing this in our bug scrub as duplicate.
