### ISSUE TITLE
Extract Specific Data

### ISSUE THREAD

**Issue by rlinux57** [prometheus/prometheus#4435]
Hi,

How can i extract and show specific data metrics in the graphs, In below mentioned screenshot i wanted to extract `pxc-back/pxc1, pxc-back/pxc2, pxc-back/pxc3` and show only that nodes graphs.

![haproxy](https://user-images.githubusercontent.com/40686169/43382865-9cfaf868-93f2-11e8-9f00-a74ea6419fd3.png)

Regards,
rlinux57

**Comment by simonpasquier** [comment]
Thanks for your report. It looks as if this is actually a question about usage and not development.

To make your question, and all replies, easier to find, we suggest you move this over to our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search. If you prefer more interactive help, join or our [IRC channel](https://webchat.freenode.net/?randomnick=1&channels=prometheus), #prometheus on irc.freenode.net. Please be aware that our IRC channel has no logs, is not searchable, and that people might not answer quickly if they are busy or asleep. If in doubt, you should choose the mailing list.

Once your questions have been answered, please add a short line pointing to relevant replies in case anyone stumbles here via a search engine in the future.
