### ISSUE TITLE
discovery.Manager.runUpdater() only needs to run once

### ISSUE THREAD

**Issue by rainpavilion** [prometheus/prometheus#4470]
A provider runs runUpdater()，but they do same things, it maybe a bug.

**Comment by simonpasquier** [comment]
Ah, you might have spotted "interesting"... I agree that a new `runUpdater()` goroutine is spawned for every SD provider while only one instance is needed AFAICT. This could explain SD issues like #4124.  

https://github.com/prometheus/prometheus/blob/46fb4078a6bbf98732a9c9016a0104829b33ed99/discovery/manager.go#L127-L136

@krasi-georgiev?
