### ISSUE TITLE
Removal of "prometheus.io/scrape", etc. from kubernetes example

### ISSUE THREAD

**Issue by schweikert** [prometheus/prometheus#4484]
I am a bit puzzled by this commit:
https://github.com/prometheus/prometheus/commit/03a9e7f72e072c6d29f422425d8acd91a957836b

Is there a reference where this was discussed? Even though this is a convention and not something that needs to be done that way, I fail to see how completely removing this and replacing it with pseudo code is helping users. Even though it wasn't formalized, having a sort-of-agreed-upon way of doing annotations for prometheus in kubernetes is valuable, in my opinion.

**Comment by schweikert** [comment]
@Bplotka : maybe you could comment?

**Comment by Bplotka** [comment]
@schweikert sure, can comment. (: 

Here is the reference for the discussion and *ALL* the reasons and pros & cons of that change in examples: https://github.com/prometheus/prometheus/pull/4131

Let us know if something needs to be explained in further details.

**Comment by Bplotka** [comment]
I don't know why commit does not reference the PR ):

**Comment by schweikert** [comment]
Thanks for the link to that github issue. That's what I was looking for. I searched for it, but failed to find it :)

Anyway, personally I think that this is a bit of a shame. I think the old suggested way has the advantage of being very simple and I find it to be very useful for most of my use cases. I don't have often the problem of having two containers that need scraping in the same pod. Even for that use case, I was thinking that you could spin up a low-resource consumption sidecar that proxies the request and merges metrics from all the containers that you want scraped. This would have the advantage of keeping the simple use case simple, and making the complex use case possible.

**Comment by Bplotka** [comment]
I agree that you can still use annotation if your use case is simple. In fact, what we did in this PR we just tried to make it clear and explain more how to use simple annotations and how it works. We did not remove any example. We just made it clear that this is only an example and not "recommended" and "golden" way for doing this.

The main reason of the change is the fact that people were referencing those annotations as the perfect "way" and that Prometheus recommends it etc etc, while it does not recommend anything in this field - it just gives different ways to handle different use cases.

Do you think that adding more explanation as we did in this change was a wrong idea?

**Comment by schweikert** [comment]
The change removed for example prometheus.io/scrape and replaced with example.io/should_be_scraped. I think that's a bit too drastic and means that all users that want to configure this, need also to think about how to name that annotation. Having a sort-of-standard for that simple use case was useful.

**Comment by schweikert** [comment]
I have added a reply to this google groups thread:
https://groups.google.com/forum/#!topic/prometheus-users/ihMUWtX477Q

**Comment by schweikert** [comment]
This issue probably can be closed, considering that the change was reviewed and agreed on. Move the discussion to prometheus-users. Thanks again Bplotka for your answer. Also, I learned today about how to find a pull request related to a certain github commit (there is actually a link to #4131 when looking at the commit: https://github.com/prometheus/prometheus/commit/03a9e7f72e072c6d29f422425d8acd91a957836b)
