### ISSUE TITLE
Proposal: more flexible token configure  in scrape_config

### ISSUE THREAD

**Issue by zjwzte** [prometheus/prometheus#4491]
## Proposal
**Use case. **
in our exist system, we'd like to provide  restful api for prometheus to scripe metrics;
however,in our system we use self-define http head "Access-Token" to take token info, to use prometheus
we have to resolve http head "Authorization" used in prometheus scripe http request;

Can more flexible token configure  in scrape_config be provided to specify use which http head key to take
token info;

thanks 

* Prometheus configuration file:
```
insert configuration here
```

**Comment by brian-brazil** [comment]
Thanks for your suggestion. We purposefully avoid supporting non-standard auth mechanisms, as that would be challenging to maintain and be a rabbit hole feature wise. In addition allowing arbitrary headers to be passed would make debugging for users quite a bit more difficult, as it wouldn't be possible to look at a /metrics in a browser.

If you have a system that doesn't support basic auth, bearer tokens or ssl mutual auth I would suggest using proxy_url to have a proxy that can alter the request as needed.

**Comment by zjwzte** [comment]
Thanks for your reply；
maybe proxy_url is a better way;

thanks

**Comment by brian-brazil** [comment]
Something else to consider is if you really need to tie into your existing rest setup. Metrics is more an admin/debug endpoint, so you may wish to handle it however you usually handle those.
