### ISSUE TITLE
Breaking files of the main package makes it difficult to test using `go run` 

### ISSUE THREAD

**Issue by krasi-georgiev** [prometheus/prometheus#4493]
## Proposal
**Use case. Why is this important?**
Run and debug Prometheus locally. 
It is important so that we can debug quickly :)

I wish we could organise the files so that the `cmd/prometheus/` contains only `main.go` and `main_test.go` so that I can run and debug only using `go run main.go`.

currently we have so many files in there so that it  is no easy to follow which files need to be passed to the `go run` command.

I guess that mean putting all the other files in their dedicated packages which seems the idiomatic go way anyway.

**Comment by roidelapluie** [comment]
is `go run *.go` such a big deal?

**Comment by krasi-georgiev** [comment]
I wish it was that easy :)
 this picks up the `main_test.go` and fails. I tried many different combinations and nothing worked. 

opening a PR in a sec as this was very easy to fix by moving these in a dedicated package.
