### ISSUE TITLE
Compatible Versions. Prometheus DB will not be removed.

### ISSUE THREAD

**Issue by anumercian** [prometheus/prometheus#4502]
Hello, I was using the 1.8 version of Prometheus, I used to encounter the issue of corrupted data and I used storage.local.dirty=true flag to resolve this problem. After upgrading to version 2.3, this flag is no more supported, but I sometimes still get the corrupt data issue. What could I do in version 2.3 to avoid this problem? Attached are the logs. Could this be happening because of failed upgrade?
**Use case. Why is this important?**
Prometheus fails to start

* Logs:
journalctl -u prometheus -af
```
-- Logs begin at Mon 2018-07-30 22:27:28 UTC. --
Jul 30 22:28:13 8320 systemd[1]: prometheus.service: Start request repeated too quickly.
Jul 30 22:28:13 8320 systemd[1]: Failed to start Prometheus.
Jul 31 17:28:14 8320 systemd[1]: Stopped Prometheus.
Jul 31 17:28:14 8320 systemd[1]: Starting Prometheus...
Jul 31 17:28:14 8320 sh[12915]: Tue Jul 31 17:28:14 UTC 2018    Removing Alert Files from: /var/run/prometheus/alerts
Jul 31 17:28:14 8320 sh[12915]: Tue Jul 31 17:28:14 UTC 2018    Current Version: 2
Jul 31 17:28:14 8320 sh[12915]: Tue Jul 31 17:28:14 UTC 2018    Compatible Versions. Prometheus DB will not be removed
Jul 31 17:28:14 8320 sh[12915]: Tue Jul 31 17:28:14 UTC 2018    Removing Prometheus Lock file from: /fs/nos/var/lib/prometheus-data
Jul 31 17:28:14 8320 systemd[1]: Started Prometheus.
Jul 31 17:28:19 8320 prometheus[12943]: level=error ts=2018-07-31T17:28:19.878266962Z caller=notifier.go:473 component=notifier alertmanager=http://127.0.0.1:9091/api/v1/alerts count=0 msg="Error sending alert" err="Post http://127.0.0.1:9091/api/v1/alerts: dial tcp 127.0.0.1:9091: connect: connection refused"
 ```

**Comment by simonpasquier** [comment]
Thanks for your report. It looks as if this is actually a question about usage and not development. 

To make your question, and all replies, easier to find, we suggest you move this over to our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search. If you prefer more interactive help, join or our [IRC channel](https://webchat.freenode.net/?randomnick=1&channels=prometheus), #prometheus on irc.freenode.net. Please be aware that our IRC channel has no logs, is not searchable, and that people might not answer quickly if they are busy or asleep. If in doubt, you should choose the mailing list.

Once your questions have been answered, please add a short line pointing to relevant replies in case anyone stumbles here via a search engine in the future.
