### ISSUE TITLE
PROPOSAL: add official docker image for remote storage adapter

### ISSUE THREAD

**Issue by rainoko** [prometheus/prometheus#4505]
## Proposal
**Use case. Why is this important?**

In enterprise we cant use non official images. Yes we can build our own but it is useful for other also to have official image in docker hub.

**Comment by simonpasquier** [comment]
The [remote storage adapter](https://github.com/prometheus/prometheus/tree/master/documentation/examples/remote_storage/remote_storage_adapter) is provided as an example and the Prometheus team can't really commit maintaining it. If you're using InfluxDB, the latest versions have built-in support for the remote read/write APIs.

I'm closing the issue for now. If you have further questions, please use the [dev mailing list](https://groups.google.com/forum/#!forum/prometheus-developers) but it is likely that the answer will remain the same.
