### ISSUE TITLE
Notify user if configuration contains duplicated scrape targets

### ISSUE THREAD

**Issue by grobie** [prometheus/prometheus#451]
Given a configuration which contains the same target under several job names, there should be some kind of feedback to the user.

Example:

```json
"jobs" => [
  {
    "name": "foo",
    "address": "qux.address.example"
  },
  {
    "name": "bar",
    "address": "qux.address.example"
  }
]
```

Idea:
As a simple idea, we could add a warning banner (e.g. [bootstrap](http://getbootstrap.com/components/#alerts)) to the top of all prometheus server pages in that case. Alternatively such a config could be simply rejected on bootstrap, pending whether there are valid use cases for the quoted config.

**Comment by brian-brazil** [comment]
This is a valid configuration, for example a server might have multiple roles that require different labels or different scrape parameters.

**Comment by fabxc** [comment]
Closable?
