### ISSUE TITLE
Instant vector selectors regular expressions bug

### ISSUE THREAD

**Issue by zhangjianweibj** [prometheus/prometheus#4511]
version:2.2.1

Instant vector selectors regular expressions use '{__name__=~".+"}' get nothing
![image](https://user-images.githubusercontent.com/18585129/44200957-96082b80-a17a-11e8-8397-1fbd2a6b3f47.png)

use rexpression '{__name__=~"c.*"}' get results.
![image](https://user-images.githubusercontent.com/18585129/44201036-c2bc4300-a17a-11e8-9d54-1061f95812b8.png)

**Comment by brian-brazil** [comment]
That's not right. Does the same happen with 2.3.2?

**Comment by zhangjianweibj** [comment]
![image](https://user-images.githubusercontent.com/18585129/44206787-79c1ba00-a18d-11e8-9fc3-438b12ee8033.png)

![image](https://user-images.githubusercontent.com/18585129/44206817-9eb62d00-a18d-11e8-9f99-7688d068536a.png)


same problem with 2.3.2.i prepare to use prometheus federate function,but get no metrics

![image](https://user-images.githubusercontent.com/18585129/44206880-cf966200-a18d-11e8-8801-716a0038f453.png)

**Comment by brian-brazil** [comment]
`%2b` is not the same as `+`, try `.+`.

**Comment by zhangjianweibj** [comment]
![image](https://user-images.githubusercontent.com/18585129/44207347-716a7e80-a18f-11e8-8289-17faa7192ed8.png)


no metrics as well.....

**Comment by zhangjianweibj** [comment]
![image](https://user-images.githubusercontent.com/18585129/44207416-bf7f8200-a18f-11e8-9da5-14937e6cedf0.png)


with expression '.%2b' in postman works well,but in prometheus not works neither '.+' nor '.%2b'

**Comment by brian-brazil** [comment]
`+` in a URL is parsed as a space. You need to use `+` in your prometheus.yml.

Also, https://www.robustperception.io/federation-what-is-it-good-for
