### ISSUE TITLE
Feature Request: Web API Endpoint for Rules

### ISSUE THREAD

**Issue by corey-hammerton** [prometheus/prometheus#4515]
## Proposal
**Use case. Why is this important?**
Our enterprise monitoring system needs to be connected to Prometheus by querying a Rules or Alerting Rules API in order to make it possible for alerts in Prometheus to trigger or reset in a remote monitoring system simultaneously.

There is currently no good API to fulfill this requirement.

**Comment by gouthamve** [comment]
This has been implemented here: https://github.com/prometheus/prometheus/pull/4318 and will be out in the next release :)

**Comment by gouthamve** [comment]
https://github.com/prometheus/prometheus/blob/master/docs/querying/api.md#rules and https://github.com/prometheus/prometheus/blob/master/docs/querying/api.md#alerts

I'm closing this issue as I think the existing feature set covers your requirements, but if there is anything missing, please feel free to reopen the issue.
