### ISSUE TITLE
Extending support for creating binaries for s390x (IBM Z)

### ISSUE THREAD

**Issue by duane-ibm** [prometheus/prometheus#4521]
We are able to build Prometheus 2.3.2 from source on s390x (IBM Z) using `make build`.

We are planning to add s390x (IBM Z) support to build binaries for Prometheus. We see multi-arch support for Prometheus building binaries for IBM ppcle64.

We had also started a discussion [here](https://groups.google.com/forum/#!topic/prometheus-developers/ZjWZR1kVMbg)
According to the response received we need to modify the `promu.yml` file.
We would need to make additional changes for s390x in `promu` as well as `golang-builder`.

Could you provide your opinion/suggestions on the same?

**Comment by simonpasquier** [comment]
I'm not sure what is your question exactly but the discussion should really happen on the developer mailing list. I suggest that you follow up on the existing thread.

**Comment by duane-ibm** [comment]
@simonpasquier my question is how do we go about adding support for s390x to make prometheus binaries available, as available for other architectures/platforms on [https://prometheus.io/download](https://prometheus.io/download)?

**Comment by simonpasquier** [comment]
@duane-ibm since the discussion is happening at https://groups.google.com/d/msg/prometheus-developers/ZjWZR1kVMbg/_WqEdVkMCwAJ, I'm closing your issue for now.
