### ISSUE TITLE
any way to support external user defined functions

### ISSUE THREAD

**Issue by alburthoffman** [prometheus/prometheus#4522]
## Proposal
**Use case. Why is this important?**
We has to support some validation functions, which are limited to our company only. 
like the metrics will be ignored if the host is in maintenance mode, and will be used when host is back.
We also have other private requirements.

it's not a good idea to add those functions to functions.go. communicate does-not need them and we will have to maintain our own prometheus version.

the ideal solution would be we can do something like:
`apply_external("plugin.function", metrics)`
then it can check functions defined in plugin.so, which can be preload or loaded dynamically.

**Comment by brian-brazil** [comment]
Thank you for your suggestion. I don't think it's wise to allow any external code inside the Prometheus process, as that'll lead to bug reports caused by code in a non-standard setup which we have little to know ability to debug.

The use case you describe is already possible within PromQL.

**Comment by brian-brazil** [comment]
> you mean ignoring metrics from maintenance mode hosts?

Yes, expose a metric indicating it's in maintenance. Then whatever in PromQL to use that.

> it's very limited to only support functions

That doesn't make a difference, it's still arbitrary code outside our control.

> it would be great to have plugins, then plugins can be maintained by users themself. they can also share them out if wanted.

Go plugins don't help for the above reasons. We already have a number of integration points.

**Comment by RalphSu** [comment]
Hmm, probably related, i had some function want it available to my user in PromQL, since i'm exposing the PromQL to them. 
It's something like do calculation similiar https://en.wikipedia.org/wiki/Bollinger_Bands which sound like https://prometheus.io/docs/prometheus/latest/querying/functions/#holt_winters(), expecting syntax like bolling_band() that user can use.

Currently, it looks i had to fork the code, do the code change, compile and deploy, which looks invasive one. @brian-brazil  any suggestion on this kind of extension?

**Comment by brian-brazil** [comment]
That's already possible within PromQL.

**Comment by RalphSu** [comment]
> That's already possible within PromQL.
Do you mean extension is already possible? That would be cool, can you point me a bit of reference? Not find in site docs if i don't miss anything

**Comment by pzou1974** [comment]
This is a very useful feature.   
Influxdb supports custom-functions.
https://docs.influxdata.com/flux/v0.24/functions/custom-functions/

**Comment by inossidabile** [comment]
How about allowing people write things in LUA? This way it's properly isolated and can be controlled well. The language is promoted by Redis so we are in good company.

E.g. for aggregate function we could inject LUA math into `aggrFn` of https://github.com/prometheus/prometheus/blob/master/promql/functions.go#L357. That should already improve situation. Same goes to basic function really just slightly different contract.

I'm ready to take on this and make a PR. Would that be interesting to maintainers?

**Comment by brian-brazil** [comment]
I don't believe there's any appetite for adding a whole new user-exposed language inside Prometheus. If you've more complex statistical needs then a tool like R is a good place to do that processing.

**Comment by brian-brazil** [comment]
The function maps in the PromQL implementation are public, as if someone wants to add functions within their own implementation/build they can.

**Comment by vjsamuel** [comment]
@brian-brazil thank you for the clarity on publicly available maps to add in our own implementations. however `EvalNodeHelper` is largely unexported. is there scope to make few of the members like `ts` `out` `dmn` and `dropMetricName()` to be exported so that external implementations can use them?

**Comment by brian-brazil** [comment]
The general policy is to accept PRs to make things public.
