### ISSUE TITLE
I can`t  add  label (inorder to aggregate the data by this label ) when node_exporter 's role is endpoints

### ISSUE THREAD

**Issue by jiananjiang** [prometheus/prometheus#4530]
I want add label  like  kubernet-nodes's  type  to "kubernet-service-endpoints",inorder to aggregate the data by this label ,As shown below:

![a](https://user-images.githubusercontent.com/30279340/44504731-f0037680-a6cf-11e8-85fd-5fff75967a7c.png)

but I according this  configuration file, I can not  accomplish.

![ee](https://user-images.githubusercontent.com/30279340/44505143-45d91e00-a6d2-11e8-8d13-62b85ccab769.png)

prometheus version 
  prometheus:v2.0.0

kubectl  version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:55:54Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

please tell me what should I do ?

**Comment by jiananjiang** [comment]
this label of "type" is kubernet set for each node's  label, like mark this node belongs which group。

**Comment by simonpasquier** [comment]
`__meta_kubernetes_node_label_type` is only present for `role: node`. For the list of labels associated to `role: endpoint`, see https://prometheus.io/docs/prometheus/latest/configuration/configuration/#endpoints.

I'm closing it for now. If you have further questions, please use our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search.
