### ISSUE TITLE
[PromQL] Percentile parsing

### ISSUE THREAD

**Issue by aurrelhebert** [prometheus/prometheus#4543]
## Proposal
**Use case. Why is this important?**
When add an incorrect parameter for quantile function, a result is loaded

*Nice to have' is not a good use case :)*
You can test it with: "percentile(2.0, metric...)

## Bug Report
**What did you do?**
Just execute command below on Prometheus

**What did you expect to see?**
An error message

**What did you see instead? Under which circumstances?**
A result (+inf)

**Environment**

* Prometheus version: 2.3.1

**Comment by brian-brazil** [comment]
May I ask why this makes a difference to you? Changing this would be a breaking change, as it is the documented behaviour of our quantile functions.

**Comment by brian-brazil** [comment]
This is valid, though not particularly sane, PromQL.

**Comment by gouthamve** [comment]
In our bugscrub we've decided that this is expected behaviour and we will document this case.

**Comment by roidelapluie** [comment]
Should it really be +Inf or NaN?

**Comment by brian-brazil** [comment]
+Inf, this is the documented behaviour in the code.

**Comment by suyashtava** [comment]
Just checking, if this Issue is open to pick?

Or if it is the expected +inf behavior, we are good to close this issue as well.

**Comment by beorn7** [comment]
It's the expected behavior, but the idea is to document the behavior in case nonsensical parameter values are picked.

The documentation change probably has to happen here: https://prometheus.io/docs/prometheus/latest/querying/operators/#aggregation-operators

- φ<0: -Inf
- φ>1: +Inf
- φ is NaN: NaN ← and this actually doesn't work, results in `index out of range [-9223372036854775808]`

**Comment by beorn7** [comment]
I filed #10117 for the latter.

**Comment by juanrh** [comment]
@beorn7 I see #10117 was closed as completed, so this issue should ok to close, right? Or am I missing something?

**Comment by beorn7** [comment]
Yes, bug fixed and documentation added. Thank you very much. Closing this.
