### ISSUE TITLE
Are these MetaLablels like service_name all hardcoded?

### ISSUE THREAD

**Issue by etsangsplk** [prometheus/prometheus#4548]
Are metalabels like "service_name", " "service_port_name" etc, all hard coded as conventions?
Found at https://github.com/prometheus/prometheus/blob/2236bb6c59b98f74dd84688815f2154b1cdf1dc0/discovery/kubernetes/service.go#L138
        serviceNameLabel         = metaLabelPrefix + "service_name"
	serviceLabelPrefix       = metaLabelPrefix + "service_label_"
	serviceAnnotationPrefix  = metaLabelPrefix + "service_annotation_"
	servicePortNameLabel     = metaLabelPrefix + "service_port_name"
	servicePortProtocolLabel = metaLabelPrefix + "service_port_protocol"

**Comment by gouthamve** [comment]
Hi, yes. These correspond to kubernetes service abstraction. This doesn't look like a bug report or feature request, but more like a question.

To make your question, and all replies, easier to find, we suggest you move this over to our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search. If you prefer more interactive help, join or our [IRC channel](https://webchat.freenode.net/?randomnick=1&channels=prometheus), #prometheus on irc.freenode.net. Please be aware that our IRC channel has no logs, is not searchable, and that people might not answer quickly if they are busy or asleep. If in doubt, you should choose the mailing list.

Once your questions have been answered, please add a short line pointing to relevant replies in case anyone stumbles here via a search engine in the future.
