### ISSUE TITLE
Proposal: scalar functions similar to vector

### ISSUE THREAD

**Issue by Armatorix** [prometheus/prometheus#4558]
## Proposal
Now when you want to make some functions like `floor`, `round`, `ceil`, etc. on scalar you've got to firstly change it to vector than make some functions on it and change it back to scalar. IMO it would be better to have also functions directly on scalars.
Example:
 - now: `scalar(round(vector(time())))`
 - request: `round(time())`
Or I'm missing some feature or concept?

**Comment by brian-brazil** [comment]
This was something I specifically avoided when considering PromQL changes, as overloading functions makes them harder to understand - particularly if the output type varies too as you seem to be proposing. Instead if you've a different type of input, you get a different function (e.g. avg_over_time vs avg). Once you do that any benefits are quite a bit smaller.

**Comment by Armatorix** [comment]
You're probably right with overloading. 
Maybe referring to existing functions, prometheus could have `floor_scalar`, `round_scalar`, etc. ? Then there will be no overloading, also  in some cases sytax should be less complex and ofc performance benefits.

**Comment by brian-brazil** [comment]
That seems like it'd be a bit much clutter in the language for something that's already possible. The performance differences here are negligible, we're only talking doing math on a single value.

**Comment by gouthamve** [comment]
Hi @Armatorix, we've gone through this issue in our bugscrub and decided that this is wont-fix. PromQL is strongly typed and we need to make significant changes to the language to make this happen.
