### ISSUE TITLE
increase() not return back correct value

### ISSUE THREAD

**Issue by dophinlife** [prometheus/prometheus#4570]
## Bug Report
**What did you do?**
 Calculates the increase in the time series in the range vector
**What did you expect to see?**
The increase in the time series in the range vector
**What did you see instead? Under which circumstances?**
As shown in the figure below, the increase curve has a jump
![image](https://user-images.githubusercontent.com/8785975/44965674-62464780-af69-11e8-89a9-78cecbfe0629.png)

**Environment**

* Prometheus version:
	v2.2.0-rc.0

**Comment by simonpasquier** [comment]
You'd need to provide the [raw data](https://www.robustperception.io/extracting-raw-samples-from-prometheus) for better understanding.

> v2.2.0-rc.0

You might want to test with v2.3.2 (the latest stable).

**Comment by dophinlife** [comment]
After careful debugging, I found out that it was my problem. Sorry, I'll close this issue.
