### ISSUE TITLE
Please update the maintainers file

### ISSUE THREAD

**Issue by dankohn** [prometheus/prometheus#4574]
https://github.com/prometheus/prometheus/blob/master/MAINTAINERS.md only lists 3 people, but there are 17 listed at https://github.com/cncf/toc/blob/master/reviews/graduation-prometheus.md#have-committers-from-at-least-two-organizations

CNCF would appreciate if the MAINTAINERS.md can be the canonical source of currently active maintainers/committers.

If you want to have categories (or focuses), that's fine.

Cc @caniszczyk @taylorwaggoner

**Comment by beorn7** [comment]
We have one MAINTAINERS.md file per repo, and each lists at least one maintainer for that repo.

I'm not sure what's a good place for the union of all those files. There is a list of "team members" in https://prometheus.io/governance/#team-members , BTW.

**Comment by dankohn** [comment]
We're not trying to impost a process on you. We're happy to use https://prometheus.io/governance/#team-members as CNCF's canonical list of Prometheus maintainers if there are no objections.

**Comment by juliusv** [comment]
@dankohn Yes, please use https://prometheus.io/governance/#team-members for that. Those are the overall project maintainers, and they are all owners on GitHub.

**Comment by dankohn** [comment]
Great, thanks.
