### ISSUE TITLE
Backward vs forward compatibility

### ISSUE THREAD

**Issue by AlekSi** [prometheus/prometheus#4597]
[CHANGELOG.md](https://github.com/prometheus/prometheus/blob/v2.4.0/CHANGELOG.md#240--2018-09-11) currently says:

> Further, the WAL implementation has been re-written so the storage is not backward compatible. Prometheus 2.3 storage will work on 2.4 but not vice-versa.

The first sentence there contradicts the second one. Wikipedia explains [Backward compatibility](https://en.wikipedia.org/wiki/Backward_compatibility#Software) as
> A data format is said to be backward compatible with its predecessor if every message or file that is valid under the old format is still valid, retaining its meaning under the new format.

So storage _is_ backward compatible.

**Comment by gouthamve** [comment]
Ooops, will fix. I updated the releases page, now will open a PR to the changelog.

**Comment by gouthamve** [comment]
Closed in #4600
