### ISSUE TITLE
Show offending labels in many-to-many error

### ISSUE THREAD

**Issue by matthiasr** [prometheus/prometheus#4608]
## Proposal

When showing the error message

```
Error executing query: many-to-many matching not allowed: matching labels must be unique on one side
```

include the labels, and potentially even the whole metric, that caused it.

**Use case. Why is this important?**

I just spent half an hour staring at a query trying to fix this issue; sometimes a very large set of time series has duplication in only a handful of them. Knowing more about the reason for the many-to-many error would have helped a lot.

This message is generated here: https://github.com/prometheus/prometheus/blob/576ee4d3099131e12aa56f7562de416393ad86f4/promql/engine.go#L1222

**Comment by trajano** [comment]
While we're waiting for a fix. how did you debug your query to find out?

**Comment by matthiasr** [comment]
I aggregated away different labels on both sides until I found which one is causing the issue, then thought about how many-to-many matches could arise based on how the metrics were generated and collected. As I wrote, there's no clever way but to think about it really hard.

**Comment by dnwe** [comment]
I hit the same issue. I just manually patched engine.go to print out details of the label collision and ran my queries through that to see which were the cause

**Comment by matthiasr** [comment]
Could you submit that patch?

**Comment by tariq1890** [comment]
I can take this issue up.

**Comment by juliusv** [comment]
@tariq1890 Please do!
