### ISSUE TITLE
Prometheus Crash Recovery Consumes Excessive Amount of Memory

### ISSUE THREAD

**Issue by PeterZaitsev** [prometheus/prometheus#4609]
As Of Prometheus 2.3.2  Crash recovery can be excessively memory important leading to the case when normally running system is unable to ever recover after abnormal reboot. 

How to repeat:

Run prometheus with high ingest rate, consuming  60% of memory 
Kill -9  prometheus 

If auto-restart is configured Prometheus may enter crash loop running out of memory during crash recovery and restarting again

The only way I found to recover from such situation is to restart prometheus disabling all targets;  wait for recovery to complete and perform normal restart with all targets.     This also confirms issue is crash recovery related.

Sorry not having exact repeatable example.

**Comment by violenti** [comment]
Hi, I have the same problem with prometheus 2.3.2 but in kubernetes. Create a cluster federate and the principal nodo consumed 5 gb of memory ram. Is normal is performance?

The configure of the scrape federate is :
  - job_name: 'federate'
        scrape_interval: 60s
        honor_labels: true
        metrics_path: '/federate'

        params:
          'match[]':
             - '{__name__=~"job:.*"}'
             - '{job="prometheus"}'
             - '{job="kubernetes-nodes"}'
             - '{job="kubernetes-cadvisor"}'
             - '{name=~".+"}'
             - '{job="kubernetes-service-endpoints"}'
             - '{job="kubernetes-pods"}'
             - '{job="kubernetes-apiservers"}'
             - '{release="prometheus-production"}'
             - '{release="prometheus-development"}'
             - '{release="prometheus-sandbox"}'
             - '{pod_name=".+"}'
        static_configs:
          - targets:
            - 'prometheus.1'
            - 'prometheus2'
            - 'prometheus3'

**Comment by dswarbrick** [comment]
I'm also running into this problem quite frequently, with Prometheus 2.4.3. We have some moderately large instances, with about 2.8 M series and about 45k samples / sec. They are VMs, so it's relatively easy to add more memory to them, but one is already spec'd with 24 GB, and I'm getting a little nervous how much higher it's going to go.

The RAM usage settles down after about 20 minutes, but you have to get over that (very steep) hill first.

**Comment by brian-brazil** [comment]
Can you try out 2.6.0 and see if it's better? There's been a number of performance improvements made.

**Comment by viberan** [comment]
Same issue with 2.6.0

**Comment by hectorhuertas** [comment]
We are seeing the same issue in 2.7.1. We got two prometheus replicas in kubernetes with the same configuration and around 1M series. Replica 1 using around 8Gi, and replica 2 getting killed by kube when reaching it's 20Gi limit. 2 hours after raising the limit and letting it start, memory is down to 10 Gi.

**Comment by violenti** [comment]
> Can you try out 2.6.0 and see if it's better? There's been a number of performance improvements made.

Yes,  I now run 2.6.1 and the performace is best.

**Comment by fliphess** [comment]
I'm having the same issues running `2.13.1`: Memory usage goes up from 4GB to 16GB and is then OOM killed by the operating system.

**Comment by gamer22026** [comment]
Same here on 2.14 on k8s. During the WAL recovery memory usage shoots up until OOM kill. No memory resource constraints are used on the prometheus server pod. The OOM kill occurs at the kubernetes node level. I've had to manually clear the WAL files which lost all the historical metrics to get prometheus to restart again successfully.

**Comment by christianbeland** [comment]
Same on 2.14 here. Any solution yet?

**Comment by brian-brazil** [comment]
Is there any evidence to indicate that the recovery uses significantly more RAM than Prometheus would once it has recovered? All the cases I've seen are where the Prometheus itself first OOMed due to cardinality issues.

**Comment by christianbeland** [comment]
I don't know. My wal folder has 67 gig and the pod keeps trying to put it in RAM every time it starts. Since most of my node have 16/32gigs, the pod gets evicted then bounce to another node... 

Any way to limit the wal size?

**Comment by PeterZaitsev** [comment]
In my tests it is very problematic.     I think whenever it uses more memory before crash is irrelevant from practical user experience  -  my main use case for this problem is  user placing more load on Prometheus Server than it is able to handle either with too frequent scraping, or scraping too many time series.

The problem with current setup is even when user recognized the problem and rolled back configuration (after Prometheus OOM) he is left with unrecoverable system, which just OOMs in the loop upon crash recovery

This may be current design, but in this case it is problematic design.

**Comment by brian-brazil** [comment]
> I think whenever it uses more memory before crash is irrelevant from practical user experience

It is relevant, as even if we were to get recovery RAM down to zero Prometheus would instead OOM immediately after recovery rather than during recovery.

**Comment by fliphess** [comment]
Since I upgraded to `v2.15.2` a few days ago and added 4 times the amount of CPU and memory limit the pod didn't crash on recovery anymore. 

But I guess this is mainly because we're now using rather 64GB instead of 16GB, which is a ridiculous amount of memory for scraping 10 ingress controllers and the node-exporters of less than 100 servers.

**Comment by roidelapluie** [comment]
> But I guess this is mainly because we're now using rather 64GB instead of 16GB, which is a ridiculous amount of memory for scraping 10 ingress controllers and the node-exporters of less than 100 servers.

What is your retention period?

**Comment by fliphess** [comment]
Currently our retention is on 24 hours, otherwise it would crash.... But preferably we bring it up to 3 months so we can find some trends over a longer period.

**Comment by PeterZaitsev** [comment]
@brian-brazil   The use case I'm looking for is user correcting mistake by reducing ingest load by adjusting configuration.  In this case Prometheus will NOT crash IF it is able to recover

I have validated this numerous time - overload Prometheus it goes in Crash OOM loop.   Reduce the load - no change still crashing in the loop.    Add swap file - Prometheus can complete recovery through with excessive swapping.      Now you can restart  Prometheus and Remove Swap file and it will be able to operate in initial conditions

**Comment by brian-brazil** [comment]
> Now you can restart Prometheus and Remove Swap file and it will be able to operate in initial conditions

That doesn't make sense, compaction which could remove the high-cardinality series happens after recovery is complete. If it OOMed before, it'll OOM after.

**Comment by gouthamve** [comment]
We've gone through this issue in our bugscrub and are closing this as wont-fix. The idea is that the Prometheus will crash with OOM after starting up anyways so it doesn't make sense to optimise the recovery. We consider the overhead of crash recovery low enough.
