### ISSUE TITLE
Support for IPv6 in EC2 service discovery

### ISSUE THREAD

**Issue by mdyring** [prometheus/prometheus#4611]
## Proposal
EC2 instances might not be reachable via private IPv4 addresses (if scraping is done remotely), and might not have public IPv4 addresses.

It would be a very nice addition to expand service discovery to include IPv6 addresses, if possible.

Thank you for your consideration.

**Comment by AdaephonBen** [comment]
@brian-brazil Although the PR seems to have resolved this issue, I noticed that it had not been merged, so I was curious about whether there's anything left to do here. Maybe some documentation? I'd like to pick up this issue, so please tell me there's more work to be done on it

**Comment by brian-brazil** [comment]
See https://github.com/prometheus/prometheus/pull/7086#discussion_r403448643
