### ISSUE TITLE
[Proposal] Allow UTF8 string to be metric and label name

### ISSUE THREAD

**Issue by viciss** [prometheus/prometheus#4615]
## Proposal
For now, the metric and label name meets the regex expression `[a-zA-Z_:][a-zA-Z0-9_:]*`,
but sometimes it is not enough for some cases, like:

* 5xx_http_response to indicate a metric for all http response with 5xx error,
* Some non ASCII letters to be a metric name will be more meaningful for localization

So, would it be possible to extend the metric and label name to support UTF8 string?
Thanks!

**Comment by simonpasquier** [comment]
I'm closing this request as in the near future, Prometheus aims at being compliant with [OpenMetrics](https://openmetrics.io/) which will be the source of truth for the exposition format.
