### ISSUE TITLE
Run tests on Windows

### ISSUE THREAD

**Issue by gouthamve** [prometheus/prometheus#4622]
So, we had windows break a bunch of times before and while we could add tests to check that, we never really run the tests on Windows. Like this test proposed here: https://github.com/prometheus/prometheus/pull/4616#issuecomment-421932402 would never catch itself breaking because Travis and Circle run on Linux and while the test breaks on windows.

**Comment by simonpasquier** [comment]
At the minimum, we need to check that the current tests are passing on Windows and fix them if not.

**Comment by roidelapluie** [comment]
@brian-brazil I think you closed the alertmanager instead of this one, and wanted the labels to be added on the alertmanager one.

**Comment by brian-brazil** [comment]
Currently we're running only the tsdb tests on Windows in CircleCI, fix the rest and run them too.

**Comment by krajorama** [comment]
Hello from the bug scrub! We have some windows tests now . Closing. Please follow up with more specific requirements as needed.
