### ISSUE TITLE
Page Not Found on prometheus.io

### ISSUE THREAD

**Issue by kiefersmith** [prometheus/prometheus#4627]
## Proposal
This is important because documentation is missing.

## Bug Report
I clicked this link titled TSDB format:
https://prometheus.io/docs/prometheus/latest/https://github.com/prometheus/tsdb/blob/master/docs/format/README/

On this page:
https://prometheus.io/docs/prometheus/latest/storage/

**Environment**
NA

* Logs:
NA

**Comment by zicklam** [comment]
#4402
