### ISSUE TITLE
All errors come back as internal errors from api.query()

### ISSUE THREAD

**Issue by bboreham** [prometheus/prometheus#4629]
[This type assertion](https://github.com/prometheus/prometheus/blob/3e87c04/web/api/v1/api.go#L265-L271) matches `ErrorStorage` for all types of error, because `ErrorStorage` is an alias to the error interface.

https://golang.org/ref/spec#Type_assertions

~~I believe this is the cause of https://github.com/weaveworks/cortex/issues/780~~, though I actually found it while chasing something else.

**Comment by bboreham** [comment]
While I'm here, why does `query` make a storage error into an internal error while [`queryRange` does not?](https://github.com/prometheus/prometheus/blob/3e87c04/web/api/v1/api.go#L339-L345)

**Comment by krasi-georgiev** [comment]
@simonpasquier I think this is related to the promql so updated the labels.
