### ISSUE TITLE
Upgrade to 2.4.1 on Windows Failed from 2.3.2

### ISSUE THREAD

**Issue by timlharrison** [prometheus/prometheus#4635]
I started at 2.3.2 and have about a weeks' worth of data.  Trying to upgrade to 2.4.1, I get the following error:

level=error ts=2018-09-19T15:50:57.3030419Z caller=main.go:617 err="opening storage failed: open e:\\prometheus-data\\wal\\00000146: The system cannot find the file specified."

This is strange because while it is right, the file isn't there, there is a "E:\prometheus-data\wal\000146" file... so it seems like maybe its looking for too many zeros?

For fun, I did try just naming the 000146 file to 00000146 and got this error:

level=error ts=2018-09-19T15:52:34.7769161Z caller=main.go:617 err="opening storage failed: read WAL: repair corrupted WAL: cannot handle error"

I am able to revert everything back to 2.3.2 and everything seems to work fine.

EDIT: I also just quickly tried to do the same upgrade on a new storage target to make sure I didn't have some weird corruption... I ran 2.3.2 for a few minutes to get some data, stopped it, replaced all the 2.3.2 files with 2.4.1 files and got the same result.

EDIT2: I just tested the same as above but instead of starting at 2.3.2, I started at 2.4.0 and the upgrade to 2.4.1 worked fine.  I noticed that new WAL files created by 2.4.x are 8 digits instead of 6...

**Comment by timlharrison** [comment]
I also just quickly tried to do the same upgrade on a new storage target to make sure I didn't have some weird corruption... I ran 2.3.2 for a few minutes to get some data, stopped it, replaced all the 2.3.2 files with 2.4.1 files and got the same result.

**Comment by timlharrison** [comment]
FYI, this is resolved for me with 2.4.2

**Comment by gouthamve** [comment]
Thanks! Closing!
