### ISSUE TITLE
alert rule can use defined value?

### ISSUE THREAD

**Issue by fumanne** [prometheus/prometheus#4658]
My one metrics looks like this:
```
ceph_osd_up{ceph_daemon="osd.0",cluster="aaaaa",endpoint="http-metrics",instance="172.20.198.250:9283",job="rook-ceph-mgr",namespace="rook",pod="rook-ceph-mgr0-79f59b566-2lqvd",service="rook-ceph-mgr"}

ceph_osd_up{ceph_daemon="osd.1",endpoint="http-metrics",instance="172.20.164.17:9283",job="rook-ceph-mgr",namespace="rook",pod="rook-ceph-mgr0-79f59b566-snzx5",service="rook-ceph-mgr"}
```

first metrics have cluster label, second have not cluster label
When I configure alert rule. I want to show cluster in every metrics (but the second rule have not cluster label). 
Whether alert rule can support the default label value which I can defined (if metrics have no this label).
I mean alert rule looks like this:
`description: {{ $labels.ceph_daemon }} In {{  $labels.cluster | default bbbb }}  is Down'`

**Comment by SuperQ** [comment]
You can fix this in your query with `label_replace()`.

```
label_replace(ceph_osd_up, "cluster", "bbbb", "cluster", "")
```

**Comment by SuperQ** [comment]
For usage questions/help, please use our [community](https://prometheus.io/community/). On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by brancz** [comment]
This would be an issue for the upstream project. You want to set external labels on your prometheus server then alerts always have that label.

**Comment by fumanne** [comment]
@SuperQ 
Wow..... wonderful!!!.... thanks you very much
