### ISSUE TITLE
bad compile

### ISSUE THREAD

**Issue by gitchander** [prometheus/prometheus#4660]
$ make build

GOOS= GOARCH= go get -u github.com/prometheus/promu
>> building binaries
/home/chander/work/langs/golang/path/bin/promu build --prefix /home/chander/work/langs/golang/path/src/github.com/prometheus/prometheus
 >   prometheus
# github.com/prometheus/prometheus/discovery/targetgroup
discovery/targetgroup/targetgroup.go:81:5: dec.DisallowUnknownFields undefined (type *json.Decoder has no field or method DisallowUnknownFields)
!! command failed: build -o /home/chander/work/langs/golang/path/src/github.com/prometheus/prometheus/prometheus -ldflags -X github.com/prometheus/prometheus/vendor/github.com/prometheus/common/version.Version=2.4.2 -X github.com/prometheus/prometheus/vendor/github.com/prometheus/common/version.Revision=4c524007087ef50f02a396e1f4529340ee81783f -X github.com/prometheus/prometheus/vendor/github.com/prometheus/common/version.Branch=master -X github.com/prometheus/prometheus/vendor/github.com/prometheus/common/version.BuildUser=chander@chander-desktop -X github.com/prometheus/prometheus/vendor/github.com/prometheus/common/version.BuildDate=20180926-08:35:12  -extldflags '-static' -a -tags netgo github.com/prometheus/prometheus/cmd/prometheus: exit status 2
Makefile.common:102: ошибка выполнения рецепта для цели «common-build»
make: *** [common-build] Ошибка 1

**Comment by gouthamve** [comment]
To build Prometheus from the source code yourself you need to have a working Go environment with version 1.10 or greater installed.

Looks like the go version being used is not the latest. Please upgrade and try again.

**Comment by gitchander** [comment]
Bingo! It is has already compiled.
But there is no default config file here.
