### ISSUE TITLE
Metric for number of remote_read queries in-flight

### ISSUE THREAD

**Issue by gouthamve** [prometheus/prometheus#4661]
We have a metric that shows the number in-flight queries on the promql engine: `prometheus_engine_queries`, with the introduction of the concurrency limits #4656, a similar metric should be added for in-flight remote-read queries.

**Comment by tariq1890** [comment]
I can take this up

**Comment by tariq1890** [comment]
Hi @gouthamve . To continue the discussion, I had created the other PR based on how other metrics were tracked in prometheus.

If I understand correctly, We want a remote read metric at the api module level regardless of the underlying remote storage implementation used. Please correct me If I am wrong.

**Comment by simonpasquier** [comment]
@tariq1890 this metric applies to the `/api/v1/read` endpoint which can be used by external systems to read samples from Prometheus. One use case is described here: https://www.robustperception.io/accessing-data-from-prometheus-1-x-in-prometheus-2-0
