### ISSUE TITLE
Snapshot API no longer works without a `skip_head` parameter

### ISSUE THREAD

**Issue by chester89** [prometheus/prometheus#4671]
## Bug Report
**What did you do?**
Run `curl -XPOST http://localhost:9090/api/v1/admin/tsdb/snapshot`
**What did you expect to see?**
No errors, this worked ok in 2.3.2. Adding `?skip_head=false` to the query fixed the problem
**What did you see instead? Under which circumstances?**
`{"status":"error","errorType":"unavailable","error":"unable to parse boolean 'skip_head' argument: strconv.ParseBool: parsing \"\": invalid syntax"}`
**Environment**

* System information:
Windows 7 SP 1

* Prometheus version:
2.4.2 revision c305ffaa092e94e9d2dbbddf8226c4813b1190a0

**Comment by chester89** [comment]
I think it'd be best to add a default value for `skip_head` parameter

**Comment by gouthamve** [comment]
Closed in #4674 and out in `2.4.3`
