### ISSUE TITLE
Write only record rules to remote write backend

### ISSUE THREAD

**Issue by bcochofel** [prometheus/prometheus#4680]
Hi,

Is there a way to only send to remote write (like Inluxdb) some metrics? I want to only send the record rules I've created, is this possible?

Thanks,
Bruno

**Comment by simonpasquier** [comment]
You can probably use [`write_relabel_configs`](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#remote_write) for this use case.

I'm closing it for now. If you have further questions, please use our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search.
