### ISSUE TITLE
Allow customizing the server name

### ISSUE THREAD

**Issue by austin987** [prometheus/prometheus#4683]
Currently, it's hardcoded:
https://github.com/prometheus/prometheus/blob/9ee4b05d16de0b1ecd8bdaa644c2d72cdb8e41ee/web/ui/templates/_base.html#L6

as `Prometheus Time Series Collection and Processing Server`

I'd like the ability to customize it with my own title. In particular, I'd like to show the current environment, so I can distinguish between different instances.

So for example:
`'Dev Prometheus Server`
`Prod Prometheus Server`

Noticed while running app-metrics/prometheus-2.3.2, but the relevant code is unchanged in 2.4.2.

**Comment by achiuBAE** [comment]
Hi, is anyone working on this one? If not, could I work on it?

**Comment by achiuBAE** [comment]
What would be the optimal way to implement this? Through the config file, or through the flag? I see the flags are purely for configuring immutable system parameters, so i'm guessing the flag wouldn't be the way?
Or even through the front end?

Thanks

**Comment by austin987** [comment]
IMO config file or flag is fine. Front end would not be preferred, as that's harder to automate ;)

**Comment by austin987** [comment]
Fixed by https://github.com/prometheus/prometheus/commit/a9050c45f68f00cd9907df9bab96afd1908db934
