### ISSUE TITLE
EC2 service discovery panics when OwnerID is nil

### ISSUE THREAD

**Issue by simonpasquier** [prometheus/prometheus#4684]
_This only affects installations specifying the `endpoint` parameter in the EC2 SD configuration which means it doesn't concern users on AWS EC2._

https://github.com/prometheus/prometheus/blob/1c89984778fa78eda1b89d7fc2d30e025c7d3b9a/discovery/ec2/ec2.go#L243-L246

When `r.OwnerId` is `nil`, the server will crash.

**Comment by simonpasquier** [comment]
Associated PR https://github.com/prometheus/prometheus/pull/4672

**Comment by gouthamve** [comment]
Closed in #4672
