### ISSUE TITLE
Support OpenTSDB remote read 

### ISSUE THREAD

**Issue by Betula-L** [prometheus/prometheus#4707]
## Proposal

There have been several back-end storage supported remote read, such as InfluxDB, as described in https://prometheus.io/docs/operating/integrations.

But why is there no remote read adaptor for OpenTSDB now? 

Is it due to the limitation of  OpenTSDB read API or just because no one implement it?

I wanna implement it if possible.

**Comment by henridf** [comment]
I don't know why there isn't an OpenTSDB remote read adapter, you might get better feedback by asking on the relevant OpenTSDB channels. 

(But in any case, the implementation would live outside of this repo and org).
