### ISSUE TITLE
Not able to run promtool tests without cloning the repo

### ISSUE THREAD

**Issue by kentsanggds** [prometheus/prometheus#4711]
## Bug Report
**What did you do?**

I tried to use homebrew to install the latest version of the promtool, but although I managed to upgrade to 2.4.2 promtool test would fail. I eventually got it working by cloning the repo and building it on my machine.

However I would also like to run the alert tests on Travis using wget to download the release - 

https://github.com/prometheus/prometheus/releases/download/v2.4.2/prometheus-2.4.2.linux-amd64.tar.gz

It doesn't appear to work and without it, I can't introduce the promtool tests as part of the CI workflow

Tried to build in travis using this travis yml - https://github.com/alphagov/prometheus-aws-configuration-beta/blob/cd99a07d691692179397f417adbdb045dffb95d4/.travis.yml

**What did you expect to see?**

promtool running the tests successfully

**What did you see instead? Under which circumstances?**

Promtool failing with - `promtool: error: expected command but got "test", try --help`

* System information:

Ubuntu trusty

* Prometheus version:

2.4.2

**Comment by simonpasquier** [comment]
The `promtool test` command isn't part of any official release yet. You have to compile the binary from the `master` branch.

**Comment by kentsanggds** [comment]
Thanks, any timescale on when it will be released?

**Comment by simonpasquier** [comment]
Sure. The project has recently opted for a 6 weeks release cadence. Since 2.4.0 has been released 4 weeks ago, 2.5.0 should be there in 2 weeks.
