### ISSUE TITLE
Update MAINTAINERS.md

### ISSUE THREAD

**Issue by beorn7** [prometheus/prometheus#4714]
@fabxc 's email address (fabian.reinartz@coreos.com) seems outdated.

Beyond that formally required update, does the current state of MAINTAINERS.md still represent reality?

Local storage is still just missing here (which is worse in combination with https://github.com/prometheus/tsdb/issues/403 ).

Do the other focus areas still make sense? Both their layout as well as the maintainers assigned.

As an example, SD was seriously broken for a long time (rendering 2.1, 2.2, and 2.3 useless in larger production scenarios). My vague memory tells me that things got rectified mostly by @krasi-georgiev with no noticeable shepherding or mentoring by the maintainers.

And then there are rather trivial formalities like #3399 that might still have nasty consequences, given the visibility and importance of this project. It would be great if somebody felt responsible for those.

**Comment by juliusv** [comment]
@fabxc Could you provide an updated email address (and confirm whether you area of maintainership is still ok)?

**Comment by fabxc** [comment]
That should be freinartz@google.com.

Realistically, there are people who are more involved with most areas assigned to me right now. Happy to transfer those.
Retrieval is very performance sensitive and thus easy to regress in. There I'd like to stay on top of things.

**Comment by beorn7** [comment]
Bumping this up as we have a prometheus dev-summit consensus to give the MAINTAINERS.md file a serious makeover. See [notes](https://docs.google.com/document/d/1VVxx9DzpJPDgOZpZ5TtSHBRPuG5Fr3Vr6EFh8XuUpgs/edit), search for "rejig prometheus/prometheus".

The notes suggests @brian-brazil owns this. @brian-brazil : I'll assign this to you. Please unassign if you don't plan to work on it anytime soon.

**Comment by brian-brazil** [comment]
It's on my todo list for today as it happens.
