### ISSUE TITLE
bugs with timezone

### ISSUE THREAD

**Issue by xiyanxiyan10** [prometheus/prometheus#4716]
There is no parameter to set the timezone and not use the computer’s timezone, so alert with wrong timestamp will send to the alertmanager.

**Comment by simonpasquier** [comment]
All times are in UTC. See https://prometheus.io/docs/introduction/faq/#can-i-change-the-timezone?-why-is-everything-in-utc?

See https://github.com/prometheus/prometheus/issues/500 which is about adding timezone awareness to the UI part.
