### ISSUE TITLE
kubernetes prometheus.io/path is not changing metric path in service endpoint.

### ISSUE THREAD

**Issue by vishksaj** [prometheus/prometheus#4717]
What did you do?

Annotations configured for my service

      "prometheus.io/path": "/exporter",
      "prometheus.io/port": "9913",
      "prometheus.io/scrape": "true"

What did you expect to see?

As per relabel config the service endpoint should be /exporter

    - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_metric_path]
      action: replace
      target_label: __metrics_path__
      regex: (.+)

What did you see instead? 

__metrics_path__ is still /metrics (default)

Environment
Prometheus 2.4.2
c305ffaa092e94e9d2dbbddf8226c4813b1190a0 inside kubernetes.

I can  see my cutom path in __meta_kubernetes_service_annotation_prometheus_io_path

![capture](https://user-images.githubusercontent.com/26294710/46753040-62f69a00-ccdc-11e8-9f21-303b2cb5b985.JPG)

Prometheus.yml

#my global config
global:
  external_labels:
    monitor: k8s-incluster

scrape_configs:

  - job_name: 'kubernetes-service-endpoints'
    scrape_interval: 30s
    scrape_timeout: 30s
    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    kubernetes_sd_configs:
    - role: endpoints
    relabel_configs:
    - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
      action: keep
      regex: true
    - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_metric_path]
      action: replace
      target_label: __metrics_path__
      regex: (.+)
    - source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_scrape_port]
      action: replace
      regex: ([^:]+)(?::\d+)?;(\d+)
      replacement: $1:$2
      target_label: __address__
    - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape_scheme]
      action: replace
      target_label: __scheme__
      regex: (https?)
    - action: labelmap
      regex: __meta_kubernetes_service_label_(.+)
    - source_labels: [__meta_kubernetes_namespace]
      action: replace
      target_label: kubernetes_namespace
    - source_labels: [__meta_kubernetes_service_name]
      action: replace
      target_label: kubernetes_name
    metric_relabel_configs:
    - source_labels: [container]
      replacement: '$1'
      action: replace
      target_label: container_name
    - source_labels: [pod]
      replacement: '$1'
      action: replace
      target_label: pod_name
    - source_labels: [namespace]
      regex: '([^-]+)-([^-]+)-(.*)'
      replacement: '$1'
      target_label: app
    - source_labels: [namespace]
      regex: '([^-]+)-([^-]+)-(.*)'
      replacement: '$2'
      target_label: app_env
    - source_labels: [namespace]
      regex: '([^-]+)-([^-]+)-(.*)'
      replacement: '$3'
      target_label: cluster_id

**Comment by gouthamve** [comment]
Hi, it should be `__meta_kubernetes_service_annotation_prometheus_io_path` not `__meta_kubernetes_service_annotation_prometheus_io_metric_path`.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by vishksaj** [comment]
Thanks @gouthamve
