### ISSUE TITLE
silencer "recreate" does not remember matching with "regex"

### ISSUE THREAD

**Issue by liuzhen** [prometheus/prometheus#4725]
## Bug Report
**What did you do?**

receate an expired "silencer" with matching of 'regex'

**What did you expect to see?**
the to be created new silencer have all the properties derived from the old one, including the checked 'regex'

**What did you see instead? Under which circumstances?**

the 'regex' checkbox is cleared within the matching rule

**Environment**

* System information:

	Linux 3.10.0-514.el7.x86_64 x86_64

* Prometheus version:

	2.3.2

* Alertmanager version:

	not relevant

* Prometheus configuration file:
```
insert configuration here
```

* Alertmanager configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```

**Comment by simonpasquier** [comment]
Thanks for filling the issue! Can you copy the information to https://github.com/prometheus/alertmanager/issues/new instead?

**Comment by liuzhen** [comment]
sure, my bad.
