### ISSUE TITLE
Unsafe rm -rf example in documentation

### ISSUE THREAD

**Issue by opensourcegrrrl** [prometheus/prometheus#473]
At http://prometheus.github.io/docs/operating/storage/, the `rm -rf $STORAGE_PATH/*` example is unsafe.

Alternative:
`rm -r ${STORAGE_PATH}`

**Comment by juliusv** [comment]
I was thinking about this when writing it, but the problem is that we don't want to remove the directory itself, just its contents. Hmm...

**Comment by opensourcegrrrl** [comment]
What happens when you test this on someone else's box:
rm -r ${STORAGE_PATH}/

**Comment by grobie** [comment]
As this is just an example, there is no need to use an environment variable. The fact that storage path is supposed to be replaced by the actual content can be shown in a safer way as well, although not as elegant as with a bash variable. For example:

```bash
rm -rf /path/to/storage/*
```

**Comment by opensourcegrrrl** [comment]
Note: The syntax within carrots (<>) is consistent with replaceable syntax on page http://prometheus.github.io/docs/concepts/data_model/#notation. That said, <storage path> is the most consistent because it does not contain a hyphen.

**Comment by juliusv** [comment]
How about `rm -rf <storage path>/*`, because it's a single line and doesn't destroy anything, in contrast to the other suggestion where `rm -r *` will still destroy your current working directory if you accidentally execute it after the first one fails.

**Comment by juliusv** [comment]
(and most importantly, if someone just copies the line without replacing anything, it will result in a syntax error)

**Comment by juliusv** [comment]
Done.

**Comment by opensourcegrrrl** [comment]
+1
