### ISSUE TITLE
Is there a way Prometheus can pass cookie in each scrape request  to Spring Boot

### ISSUE THREAD

**Issue by Aracki** [prometheus/prometheus#4748]
I'm trying to scrape Spring Boot service running in production. We are using micrometer with prometheus registry:

```
compile 'io.micrometer:micrometer-spring-legacy:1.0.6'
compile 'io.micrometer:micrometer-registry-prometheus:1.0.6'
```

**Environment**

* Prometheus version:

	I am running Prometheus in docker. Image: ***prom/prometheus:v2.4.2***

* Prometheus configuration file:
```
global:
  scrape_interval:     5s # Set the scrape interval to every 5 seconds.
  evaluation_interval: 5s # Evaluate rules every 5 seconds.
scrape_configs:
  - job_name: 'global'
    metrics_path: '/management/prometheus'
    static_configs:
      - targets: ['global:8081']
```

* Logs:
```
server returned HTTP status 403
```

What is the proper way to pass through Spring Security? Is there a way for a Prometheus to send cookie with session id? What is the best practices here?

I have asked this on [SO](https://stackoverflow.com/questions/52795684/how-prometheus-scrape-spring-boot-metrics-with-authentication) too.

**Comment by simonpasquier** [comment]
Prometheus supports basic HTTP, X509 client and bearer token authentications.

**Comment by simonpasquier** [comment]
Also to make your question, and all replies, easier to find, we suggest you move this over to our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search. If you prefer more interactive help, join or our [IRC channel](https://webchat.freenode.net/?randomnick=1&channels=prometheus), #prometheus on irc.freenode.net. Please be aware that our IRC channel has no logs, is not searchable, and that people might not answer quickly if they are busy or asleep. If in doubt, you should choose the mailing list.

Once your questions have been answered, please add a short line pointing to relevant replies in case anyone stumbles here via a search engine in the future.

**Comment by Aracki** [comment]
After further research I have found out that there's no current way to set cookies via the scrape config.

Prometheus supports only HTTP Authorization headers like **_Basic_** and **_Bearer tokens_**.
