### ISSUE TITLE
Deleted scrape target is always recreated

### ISSUE THREAD

**Issue by piotrkochan** [prometheus/prometheus#4755]
**Use case. Why is this important?**

There is no really a way to stop prometheus from scraping previously defined target. 

## Bug Report
**What did you do?**

1. I removed scrape config from prometheus.yml
2. I ran:

```
curl -I -X POST -g 'localhost:9090/prometheus/api/v1/admin/tsdb/delete_series?match[]=up{instance="localhost:9100"}'
curl -I -X POST -g 'localhost:9090/prometheus/api/v1/admin/tsdb/clean_tombstones'
```

**What did you expect to see?**
I expect that if there is no config for this target and data then prometheus forget about that target, and do not try to scrape it in the future.

**What did you see instead? Under which circumstances?**

Prometheus still try to scrape this target. Even in the UI it is still visible:
![sdf](https://i.imgur.com/LKZr89i.png)

**Environment**

* System information:

	Linux 4.4.0-130-generic x86_64

* Prometheus version:

```
prometheus, version 2.3.0 (branch: HEAD, revision: 290d71791a507a5057b9a099c9d48703d86dc941)
build user:       root@d539e167976a
build date:       20180607-08:46:54
go version:       go1.10.2
```

* Prometheus configuration file:

Just regular configuration without previously defined scrape_config entry.

**Comment by simonpasquier** [comment]
You need to reload the configuration using `kill -SIGHUP <pid>` for instance.

I'm closing it for now. If you have further questions, please use our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search.

**Comment by piotrkochan** [comment]
@simonpasquier please reopen, because `kill -SIGHUP` does not work, as full prometheus restart.

**Comment by piotrkochan** [comment]
On the mailing list there is same issue and it is no resolved so I assume it is a bug.

https://groups.google.com/forum/#!searchin/prometheus-users/sighup%7Csort:date/prometheus-users/K4Q1ToxhwYw/EBNRvLKPBgAJ

**Comment by simonpasquier** [comment]
`kill -SIGHUP ...` works for me and I would be surprised if it was broken for everybody. Double check that you don't have a mismatch between the file used by Prometheus and the file you're modifying.

**Comment by marksugar** [comment]
Hello @piotrkochan , I don't know if you have solved this problem, because now I have encountered this problem and have not solved it.

**Comment by juliusv** [comment]
@piotrkochan 

> restart, service is still present...

If a full Prometheus restart does not remove the target, then it's certain that Prometheus is loading the wrong configuration file. Prometheus does not store a list of targets on disk by itself, so it would have no other source from which to re-create this target after restart.
