### ISSUE TITLE
scrape: configurable startTimeMargin 

### ISSUE THREAD

**Issue by thomschke** [prometheus/prometheus#4759]
## Proposal
**Use case. Why is this important?**

Sometimes I'm using Prom/Grafana to persist/visualize historical timeseries data 
with the help of a stateful metric-exporter that provide data step-by-step (include timestamp)

For this use case I have to increase "maxAheadTime" 
but in the moment it's a fixed value of 10s.

https://github.com/prometheus/prometheus/blob/105ed5c1125b125d80ed4671165e62fa1df6d2ef/scrape/scrape.go#L136

**Comment by brian-brazil** [comment]
maxAheadTime is from now, not the TSDB's last ingested timestamp. It only prevents you ingesting data from the future, as a safeguard.

**Comment by thomschke** [comment]
Sure, the lower bound of TSDB (startTimeMargin) is the problem - sorry :-)

https://github.com/prometheus/prometheus/blob/3241c527d05dc2a370dbe3a903f8ef8de1d62a04/cmd/prometheus/main.go#L574-L575

**Comment by thomschke** [comment]
A workaround is by increasing `storage.tsdb.min-block-duration` (but this has sideeffects)

**Comment by thomschke** [comment]
Hi @brian-brazil, can you explain a little bit the drawbacks of increasing `storage.tsdb.min-block-duration` in production?

https://github.com/prometheus/prometheus/blob/f34b2602e1208b75dfa9ab17c81dd086fc92f54a/cmd/prometheus/main.go#L156-L157

**Comment by brian-brazil** [comment]
We've looked at this as part of our bug scrub, this use case is better covered under #535
