### ISSUE TITLE
Improve Makefile contraption.

### ISSUE THREAD

**Issue by beorn7** [prometheus/prometheus#476]
If you want to build with your own Go environment, you still have to trigger code-generation in certain cases. That's most comfortable with the Makefiles. But if you run make on top-level, it will download and install its own Go environment. If you run 'make' in a subdirectory with code generation, it will fail...

**Comment by beorn7** [comment]
Various people working on this right now. Unassigning myself for now.

**Comment by discordianfish** [comment]
Who is working on this? We now have the Makefile.COMMON but it's not used in prometheus itself.
I just opened https://github.com/prometheus/alertmanager/pull/55 which has a similar issue.

#548 is a alternative to the Makefile triggered code-generation I assume.

**Comment by brian-brazil** [comment]
@fabxc I think we can close this now?

**Comment by fabxc** [comment]
Yes, syncing an included upstream Makefile did not turn out to be a scalable system.
We should work on a proper centralized system building and packaging releases for all our different components.
