### ISSUE TITLE
Set up a way to distribute binaries.

### ISSUE THREAD

**Issue by beorn7** [prometheus/prometheus#477]
Just the static binaries (Go rules!), or even deb, rpm, ...

And not only for the Prometheus server, but all relevant repos (pushgateway, promdash...)

**Comment by beorn7** [comment]
Fedora and Debian people are already working on RPMs and DEBs, respectively.

We might still want to provide the statically compiled binaries for a number of architectures Go supports.

**Comment by danieldreier** [comment]
Any progress on this? I can't find Debian packages anywhere, and puppetizing the install is needlessly awkward without system packages. I can help build packages if necessary but don't want to duplicate the work of others.

**Comment by beorn7** [comment]
We went into the habit of attaching binaries to GitHub releases.

Debian packages are still in the work by @TheTincho . Not sure how close he is to officially release them.

**Comment by TheTincho** [comment]
On 18/06/15 11:34, Björn Rabenstein wrote:
> We went into the habit of attaching binaries to GitHub releases.
> 
> Debian packages are still in the work by @TheTincho
> <https://github.com/TheTincho> . Not sure how close he is to officially
> release them.

Sorry about this guys, I have had very little spare time to dedicate to
this in the last few months. And to make things worse, every time I can
go back to work into this, I notice there is one (or a few) new
versions, with some new dependencies.. I am actually farther from
finishing now than a month ago :-)

-- 
Martín Ferrari (Tincho)

**Comment by fabxc** [comment]
To be honest, I don't think Prometheus's current speed of development aligns well with Debian's slow moving packages. Having proper custom packages for our releases would be nice, but official ones are probably only feasible in a few months.
By then the whole situation might be easier as well since Go 1.5 will allow shared libraries.

**Comment by brian-brazil** [comment]
I'm working on debs now, I should have something in the next few days,

**Comment by danieldreier** [comment]
@brian-brazil that's awesome! Looking forward to it.

**Comment by brian-brazil** [comment]
I've got working node_exporter debs for x86_64 and i386. They need some cleanup, but should make it easy to do the rest.

**Comment by msiebuhr** [comment]
Is the packaging-work available on a branch somewhere.

I've hacked a bit on init-files &c, but if someone have it around, it would be nice just to copy.

**Comment by brian-brazil** [comment]
Don't we have this now for our Go releases?

**Comment by TheTincho** [comment]
FWIW, prometheus, prometheus_cli, node_exporter, and push_gateway are all present in Debian at their current versions.

**Comment by SuperQ** [comment]
I was wondering what I can do to help add a few more of the common exporters like msyqld, haproxy, blackbox, etc.

I also think we should setup a PPA[0] so we can make backported packages for current releases, given the main release cycle for Debian and Ubuntu LTS releases (commonly used for servers) is 2 years.
[0]: https://en.wikipedia.org/wiki/Personal_Package_Archive

**Comment by fabxc** [comment]
We now have a download page. Thanks @grobie.
