### ISSUE TITLE
Use Docker ENTRYPOINT

### ISSUE THREAD

**Issue by SuperQ** [prometheus/prometheus#4776]
## Proposal

Use Docker `ENTRYPOINT`[0] rather than `CMD` for setting the default command line flag values.

When CMD is used, any additional flags cause the default flags to be dropped.

This makes starting up Prometheus with a simple additional flag like `--storage.tsdb.retention=15d` to need the full list of flags added.

**Environment**

Docker

[0]: https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#entrypoint

**Comment by DrakeW** [comment]
@simonpasquier I would like to help with this issue :)

**Comment by DrakeW** [comment]
@simonpasquier PR submitted, let me know if there's anything else that you would like me to add

**Comment by AndorCS** [comment]
Guys, this change brokes deployment which was works for years:
```
Error parsing commandline arguments: flag 'config.file' cannot be repeated
```
and
```
Error parsing commandline arguments: flag 'storage.tsdb.path' cannot be repeated
```

I have this in my deployment manifest:
```
          args: # copy-pasted from official Dockerfile and adjusted to current flags
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--storage.tsdb.path=/prometheus'
            - '--storage.tsdb.retention=21d'
            - '--web.console.libraries=/etc/prometheus/console_libraries'
            - '--web.console.templates=/etc/prometheus/consoles'
            - '--web.external-url=http://{prometheus.hostname}'
            - '--web.enable-lifecycle'
```

**Comment by SuperQ** [comment]
@AndorCS You will have to update your configuration.

**Comment by AndorCS** [comment]
@SuperQ sure I can do it, but I really don't see any real reason for breaking what works for years.

**Comment by SuperQ** [comment]
This was done to make deployment easier for everyone. You don't have to copy-and-paste all flags to add one additional flag change.

**Comment by AndorCS** [comment]
In this case, it's better for me to override `entrypoint` in case you will break something else in the future releases.

I'm not against this change, but I don't like you kinda breaking what works for a long time even it was not the best way to run the application.
