### ISSUE TITLE
Server metric for scrape interval exceeded

### ISSUE THREAD

**Issue by jpds** [prometheus/prometheus#4777]
## Proposal
**Use case. Why is this important?**

I'm looking for a metric in Prometheus for when a "context deadline exceeded" is encountered for a target.

I'm monitoring SNMP devices, some of which live on the other side of an unreliable connection and on occasion it takes longer than my `scrape_timeout` to query these devices and I would like to graph this out to spot them.

**Comment by brian-brazil** [comment]
You can use `up` and `scrape_duration_seconds` for this.

**Comment by brian-brazil** [comment]
We've looked at this as part of our bug scrub, and this appears to have been answered.
