### ISSUE TITLE
Inconsistency in the configuration documentation

### ISSUE THREAD

**Issue by AmandaHassoun** [prometheus/prometheus#4778]
## Proposal
**Use case. Why is this important?**

Could save potential users a lot of time!

## Bug Report
**What did you do?**

Added `gce_sd_config` to the configuration file

**What did you expect to see?**

No configuration errors!

**What did you see instead? Under which circumstances?**

Prometheus was not able to load the configuration file because it couldn't recognize `gce_sd_config` as a scraping job. Turns out, it's actually supposed to be `gce_sd_configs` but this is not what is documented here: https://prometheus.io/docs/prometheus/latest/configuration/configuration/ 

* Logs:
```
level=error ts=2018-10-23T14:04:02.01456704Z caller=main.go:617 err="error loading config from \"/etc/prometheus/prometheus.yml\": couldn't load configuration (--config.file=\"/etc/prometheus/prometheus.yml\"): parsing YAML file /etc/prometheus/prometheus.yml: yaml: unmarshal errors:\n  line 13: field gce_sd_config not found in type config.plain\n  line 19: field gce_sd_config not found in type config.plain\n  line 25: field gce_sd_config not found in type config.plain\n  line 31: field gce_sd_config not found in type config.plain"
```

**Comment by simonpasquier** [comment]
`gce_sd_configs` is correctly documented in [`scrape_config`](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#scrape_config).

I'm closing it for now. If you have further questions, please use our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search.
