### ISSUE TITLE
Implement double-delta chunk encoding

### ISSUE THREAD

**Issue by beorn7** [prometheus/prometheus#478]
Idea mostly in @beorn7's head. Should improve timestamp compression by a lot. Thus for fewer chunks. Thus fewer chunks to persist. Thus fewer disk seeks. Thus improved performance on spinning disks. And moar samples in RAM. So much goodness...

**Comment by timchenxiaoyu** [comment]
what's the difference  between double-delta and delta encoding ,more detail ,please

**Comment by beorn7** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue (which has been closed over two years ago!). On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by timchenxiaoyu** [comment]
ths
