### ISSUE TITLE
Uninstall Prometheus completely from CentOS

### ISSUE THREAD

**Issue by ajinkyagit** [prometheus/prometheus#4784]
## Proposal
**Use case. Why is this important?**

Uninstall Prometheus completely from CentOS

## Bug Report
**What did you do?**
I have Installed Prometheus using Puppet and now I can't find a way to uninstall it So that I can upgrade it to the latest version

**What did you expect to see?**
Prometheus Completely removed from CentOS
**What did you see instead? Under which circumstances?**

**Environment**

* System information:

Linux 3.10.0-862.14.4.el7.x86_64 x86_64

* Prometheus version:

1.5

**Note**
I have Manually deleted all the prometheus folders but still I am not able to find a way to remove it completely 

**Logs**
service prometheus status
Redirecting to /bin/systemctl status prometheus.service
● prometheus.service
   Loaded: not-found (Reason: No such file or directory)
   Active: failed (Result: start-limit) since Thu 2018-10-25 18:04:25 IST; 8min ago
 Main PID: 6793 (code=exited, status=203/EXEC)

Oct 25 18:04:25 server.puppet.local systemd[1]: prometheus.service: main process exited, code=exited, status=203/EXEC
Oct 25 18:04:25 server.puppet.local systemd[1]: Unit prometheus.service entered failed state.
Oct 25 18:04:25 server.puppet.local systemd[1]: prometheus.service failed.
Oct 25 18:04:25 server.puppet.local systemd[1]: prometheus.service holdoff time over, scheduling restart.
Oct 25 18:04:25 server.puppet.local systemd[1]: start request repeated too quickly for prometheus.service
Oct 25 18:04:25 server.puppet.local systemd[1]: Failed to start Prometheus Monitoring framework.
Oct 25 18:04:25 server.puppet.local systemd[1]: Unit prometheus.service entered failed state.
Oct 25 18:04:25 server.puppet.local systemd[1]: prometheus.service failed.

**Comment by simonpasquier** [comment]
You should ask the question to the project maintaining the Puppet module.

I'm closing it for now. If you have further questions, please use our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search.
