### ISSUE TITLE
Several tags for filtering targets in consul_sd_config

### ISSUE THREAD

**Issue by ashepelev** [prometheus/prometheus#4786]
## Proposal
According to documentation,
```
# An optional tag used to filter nodes for a given service.
[ tag: <string> ]
```
it is not possible to specify several tags to filter targets in consul_sd_config. One can use relabel_configs with action keep or drop but anyway it causes metrics to be pulled.

According to consul documentation it is possible to specify multiple tags in request:
```
tag (string: "") - Specifies the tag to filter on. This is specified as part of the URL as a query parameter. Can be used multiple times for additional filtering, returning only the results that include all of the tag values provided.
```

**Comment by cstyan** [comment]
This will require updating the vendored Consul api, `catalog.ServiceMultipleTags` was only added ~4 months ago: https://github.com/hashicorp/consul/commit/34e551683478e4c454b923d43700335ce082401d
