### ISSUE TITLE
Move all recording rules to be in a subdirectory in Prometheus

### ISSUE THREAD

**Issue by lagunabeach** [prometheus/prometheus#4787]
Hi All, 

I have been assigned a task in Prometheus to move all recording rules to be in a subdirectory rather than directly in /etc/prometheus. How can this be done. Any help on this would be greatly appreciate it. 

Thank you!

**Comment by simonpasquier** [comment]
You want to use the `rule_files:` parameter in the Prometheus configuraiton (eg `rule_files: [ "/some/directory/with/rules/*.yml", "/another/directory/*.yml"]`, see https://prometheus.io/docs/prometheus/latest/configuration/configuration/#configuration-file

I'm closing it for now. If you have further questions, please use our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search.
