### ISSUE TITLE
Can prometheus configuration be updated remotely

### ISSUE THREAD

**Issue by yaminisridaran** [prometheus/prometheus#4789]
Environment: k8s clusters
I have a remote prometheus which I will not have access to configure it. Can I create configuration and push the configuration to the remote prometheus.

**Comment by simonpasquier** [comment]
There's no HTTP API to update the configuration if this is what you're asking for. Prometheus takes its configuration from the file system (this is the `--config.file` CLI flag). You can also use service discovery mechanisms to let Prometheus discover targets from external services (eg Kubernetes API).

I'm closing it for now. If you have further questions, please use our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search.
