### ISSUE TITLE
Metric with 1h scrape_interval do not shown on graphs

### ISSUE THREAD

**Issue by dmitriy-lukyanchikov** [prometheus/prometheus#4801]
## Bug Report
**What did you do?**
Hello i configure scraping with long scrape_interval=1h
Run query over metric that scraped every 1 hour. 
**What did you expect to see?**
i expected to see graphs with small resolution on 24 hour prometheus graph
**What did you see instead? Under which circumstances?**
i see only couple of dots other is empty, if i set custom resolution to 100s than all dots appear. but i need to use this metric on grafana where period and resolution will be very different and its impossible to manually change it every time.

![screen shot 2018-10-29 at 6 42 16 pm](https://user-images.githubusercontent.com/31628587/47665736-7645a880-dbaa-11e8-9d7f-6475f46db56a.png)
![screen shot 2018-10-29 at 6 42 33 pm](https://user-images.githubusercontent.com/31628587/47665737-7645a880-dbaa-11e8-8d0c-59e1e4eaf6e7.png)

Please help with this, or help to understand how it can be fixed
**Environment**

* System information:

Linux 4.4.0-137-generic x86_64

* Prometheus version:

2.4.2

**Comment by simonpasquier** [comment]
You've been hit by staleness handling. See https://prometheus.io/docs/prometheus/latest/querying/basics/#staleness
In practice you need to scrape your targets every 2 minutes at most to deal with potentially failed scrapes.

I'm closing it for now. If you have further questions, please use our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search.
