### ISSUE TITLE
Enforce timestamp monotonicity

### ISSUE THREAD

**Issue by beorn7** [prometheus/prometheus#481]
The storage requires that samples are sorted by timestamp, i.e. a timestamp that is saved to the storage layer must have a timestamp at least as high as the previous sample. This constraint is just by contract so far. It is not checked or enforced.

Unfortunately, that's not trivial as a time series might already be archived when a sample for it comes in again. It's pretty expensive to unarchive a series just to check the latest timestamp.

Ideas:

- Never accept timestamps from the future (+/- a certain tolerated skew).
- Then the mtime of a time series file is an upper bound for the last timestamp.
- Save the last timestamp in the series object.

**Comment by juliusv** [comment]
When we append a new sample to an archived series, we unarchive the series anyways and get the last timestamp of the series from the unarchiving. So even that case seems to be easy to check.

Implementation: https://github.com/prometheus/prometheus/pull/889
