### ISSUE TITLE
Better error reporting for missing query string parameters

### ISSUE THREAD

**Issue by candlerb** [prometheus/prometheus#4811]
## Proposal
**Use case. Why is this important?**

Currently a missing query parameter is reported as if the query parameter was present with empty string.  Furthermore, the error message does not include the *name* of the faulty parameter.  This makes it hard to identify the problem with the query.

This affects people experimenting with the API for the first time.

## Bug Report
**What did you do?**

```
curl -s 'http://localhost:9090/api/v1/query_range?query=ifHCInOctets%7bifDescr%3d"pppoe-out1"%7d' | python3 -mjson.tool
```

**What did you expect to see?**

Something like:

```
"error": "missing parameter 'start'"
```

**What did you see instead? Under which circumstances?**

```
{
    "status": "error",
    "errorType": "bad_data",
    "error": "cannot parse \"\" to a valid timestamp"
}
```

**Environment**

* System information:

        Linux 4.4.0-138-generic x86_64

* Prometheus version:

    ```
    prometheus, version 2.4.3 (branch: HEAD, revision: 167a4b4e73a8eca8df648d2d2043e21bdb9a7449)
      build user:       root@1e42b46043e9
      build date:       20181004-08:42:02
      go version:       go1.11.1
    ```

**Comment by BrianHa94** [comment]
@brian-brazil I would like to take this one up

**Comment by codwu** [comment]
@BrianHa94  Are you still working on it?  I would like to open a PR for this issue.

**Comment by BrianHa94** [comment]
@codwu Yes, I have a fix. I just need to test before opening a PR.

**Comment by gouthamve** [comment]
Hi @BrianHa94 could you submit the patch? This is still an issue on 2.7.1

**Comment by palash25** [comment]
Hi @gouthamve I would like to work on this

Just to be sure this change would require using `errors.New` with appropriate messages and adding it to the `apiError` struct wherever params are checked like in this snippet `start, err := parseTime(r.FormValue("start"))` right? and ofcourse changing the error response in these [test cases](https://github.com/prometheus/prometheus/blob/master/web/api/v1/api_test.go#L498-L525)

**Comment by geekodour** [comment]
@gouthamve @palash25 Would it be useful if we set `start` to `minTime` and `end` to `time.Now` or something because otherwise I think the error message is helpful only?

**Comment by codesome** [comment]
@palash25 you can go ahead if @BrianHa94 is not [working on it](https://github.com/prometheus/prometheus/issues/4811#issuecomment-436789351). @BrianHa94 are you still on it?

**Comment by BrianHa94** [comment]
@palash25 please go ahead.
