### ISSUE TITLE
different results: kube_pod_container_status_waiting_reason VS kube_pod_container_status_waiting

### ISSUE THREAD

**Issue by naseemkullah** [prometheus/prometheus#4815]
## Proposal
**Use case. Why is this important?**

*Set up alerts when pod is not starting due to **CreateContainerConfigError**, generally alert is set based off **kube_pod_container_status_waiting_reason** metric

## Bug Report
**What did you do?**

Had a pod with **CreateContainerConfigError**, setup an alert for  **kube_pod_container_status_waiting_reason > 0** for 10m, but it did not catch it.

Hwoever *kube_pod_container_status_waiting* does catch it (but does not state the reason)

**What did you expect to see?**
I wanted **kube_pod_container_status_waiting_reason** metric to encompass pods that wont start due to **CreateContainerConfigError**
  
**What did you see instead? Under which circumstances?**
please see above
**Environment**
not important
* System information:
latest prometheus helm chart on latest gke

* Prometheus version:

	latest
* Alertmanager version:
latest

**Comment by simonpasquier** [comment]
Thanks for your report. It looks as if this is actually a question about kube-state-metrics and Prometheus usage.

To make your question, and all replies, easier to find, we suggest you move this over to our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search. If you prefer more interactive help, join or our [IRC channel](https://webchat.freenode.net/?randomnick=1&channels=prometheus), #prometheus on irc.freenode.net. Please be aware that our IRC channel has no logs, is not searchable, and that people might not answer quickly if they are busy or asleep. If in doubt, you should choose the mailing list.

Once your questions have been answered, please add a short line pointing to relevant replies in case anyone stumbles here via a search engine in the future.

**Comment by naseemkullah** [comment]
Thank you!
https://groups.google.com/forum/#!topic/prometheus-users/Y5W-rckh-Jo created

**Comment by naseemkullah** [comment]
https://github.com/kubernetes/kube-state-metrics/pull/578 created!

**Comment by brancz** [comment]
I think this can be closed here, as it's not an issue with Prometheus but needs a small patch in kube-state-metrics itself. Closing.
