### ISSUE TITLE
Please add __meta_kubernetes_pod_status so 'completed' pods can be dropped from scrape

### ISSUE THREAD

**Issue by bboreham** [prometheus/prometheus#4823]
## Proposal
**Use case. Why is this important?**

Pods that are created by Kubernetes Job objects will go to `Completed` state if they finish without error.
Without a way to stop scraping, the Prometheus `up` state goes to 0 and (in my current environment) this triggers an alert.

The Kubernetes SD inserts various labels such as `__meta_kubernetes_pod_annotation...` which allow relabel config to drop some targets.  I would like to extend this to a meta label which would hold the `Completed` status, so I can drop those pods from the targets.

**Comment by brian-brazil** [comment]
We'll generally accept any metadata that's available, so feel free to send a PR.

**Comment by bboreham** [comment]
Looking more closely, I find `"Completed"` comes from the (multiple) `container.State.Terminated.Reason` field, and requires gymnastics to obtain.
There is a simpler [`PodPhase`](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-phase) field which will say `Running`, `Succeeded`, etc., and I propose to implement that.
