### ISSUE TITLE
probe prometheus server failed

### ISSUE THREAD

**Issue by obeyler** [prometheus/prometheus#4830]
## Bug Report
**What did you do?**
I install prometheus with helm chart and with an ingress rule with path.

helm install --name prometheus stable/prometheus --namespace prometheus -f values.yaml 

I set inside default values.yaml:
server: 
  prefixURL: "/"
  baseURL: "https://ingress-ops.nd-int-opmydomain/prometheus"
  extraArgs : {"web.route-prefix: "/"}

**What did you expect to see?**
prometheus server running 
**What did you see instead? 

![image](https://user-images.githubusercontent.com/23224162/48076367-56833580-e1e5-11e8-9b29-2047302eaed9.png)

On pod view : 

![image](https://user-images.githubusercontent.com/23224162/48078013-f3939d80-e1e8-11e8-837f-2a05ae6c5de3.png)

**Environment**
Kubernetes 1.12

* Prometheus version:
	prometheus 2.4.3
        prometheus helm chart: 7.3.4

* Logs:
2018/11/06 15:42:15 Watching directory: "/etc/config"

**Comment by obeyler** [comment]
please note that if server.prefixURL="" and server.baseURL="" the pod run well

![image](https://user-images.githubusercontent.com/23224162/48082205-3c038900-e1f2-11e8-91c3-7f8f29beb160.png)

But in our case we need to be under a ingress rule with path

**Comment by simonpasquier** [comment]
Can you try not setting `extraArgs` to `{"web.route-prefix: "/"}`?

**Comment by obeyler** [comment]
Same result :-(

**Comment by simonpasquier** [comment]
Have you tried with `prefixURL: "/prometheus"`? Also please share the actual CLI flags and the Prometheus deployment configuration.

For future questions, please use our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search.

**Comment by obeyler** [comment]
It works thanks
