### ISSUE TITLE
why the alert always pending but not firing

### ISSUE THREAD

**Issue by pulord** [prometheus/prometheus#4836]
![image](https://user-images.githubusercontent.com/15811706/48184981-a6d9cf00-e36e-11e8-8f4b-b4f3806e0bc0.png)
**Query**
`sum by(errCode) (sum_over_time(weixin_biz_errs[5m])) > 60`
**Alert Rules**

![image](https://user-images.githubusercontent.com/15811706/48185302-89593500-e36f-11e8-8bd7-212ae3c4e42b.png)

![image](https://user-images.githubusercontent.com/15811706/48185166-2ebfd900-e36f-11e8-9a89-f2b6a2231cd3.png)

> Runtime Info

![image](https://user-images.githubusercontent.com/15811706/48185899-69c30c00-e371-11e8-9332-815e0b67cb58.png)

**Comment by pulord** [comment]
delete currnet_value from labels， its works！

**Comment by simonpasquier** [comment]
Yes, label values shouldn't change between evaluations otherwise it is equivalent to new alerts.

I'm closing it for now. If you have further questions, please use our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search.
