### ISSUE TITLE
YAML configuration output is not correctly indented

### ISSUE THREAD

**Issue by kaihendry** [prometheus/prometheus#4846]
## Proposal
I'm often terrorised by incorrect YAML indentation and I noticed what Prometheus outputs in /config isn't perfect strictly speaking.

## Bug Report

* What I did: Copy the configuration shown on /config
* Expected: A valid YAML document
* What happened instead: yamllint 1.12.1 strictly complain about the document

* Prometheus version: 2.5

https://s.natalian.org/2018-11-09/yaml-indentation.mp4

**Comment by brian-brazil** [comment]
Is it invalid YAML, or is the linter being over-sensitive?

**Comment by simonpasquier** [comment]
Though not complying with the linter's rules, the YAML exposed by Prometheus is perfectly valid. There isn't much we can do here as we rely on an [external library](https://gopkg.in/yaml.v2) for YAML serialization/deserialization.
