### ISSUE TITLE
Consul job rename/relabel not working with 2.5.0

### ISSUE THREAD

**Issue by raypettersen** [prometheus/prometheus#4853]
## Proposal
**Use case. Why is this important?**
Grouping of exporters when using consul is broken for job rename.

## Bug Report
**What did you do?**
Upgraded to latest 2.5 version. All exporters discovered with consul ended up with a single job name instead of rename for each exporter which was working flawlessly with 1.8.0

**What did you expect to see?**
Continued renaming of job name, so all discovered exporters are sorted correctly in the prometheus view. Downgrading to 2.4.3 resolved the issue.

* Prometheus version:

2.5.0

**Comment by raypettersen** [comment]
```      - source_labels: ['__meta_consul_service']
        regex: '(.*)'
        target_label: 'job'
        replacement: '$1'
```

**Comment by hoffie** [comment]
Do you see any actual problems (i.e. unexpected changes in the database) or could this be just explained by the [announced](https://github.com/prometheus/prometheus/blob/master/CHANGELOG.md), changed UI grouping in 2.5.0?

**Comment by raypettersen** [comment]
It's just the gui as far as I can see. Likely related to the announcement. What's the fix for getting proper grouping when using consul/sd? Right now everything is grouped under "consul". I'd like to get the old behavior which lets me get exporters grouped by name.

**Comment by simonpasquier** [comment]
Indeed the UI layout for targets has changed in 2.5.0. To be honest, it wasn't really intentional but positively welcomed by users that noticed the new layout. On the other hand, I see how the change can be annoying for you. What if targets inside a scrape configuration were grouped by `job`?

**Comment by MustaphaB1** [comment]
Also having this same issue.. will this be fixed or is downgrading to 2.4.3 the only option.

**Comment by simonpasquier** [comment]
I've sent https://github.com/prometheus/prometheus/pull/4898 that will at least sort targets by job then instance labels.

**Comment by zbindenren** [comment]
> Also having this same issue.. will this be fixed or is downgrading to 2.4.3 the only option.

Downgrading to 2.4 is the only option to get the same behavior.

**Comment by raypettersen** [comment]
Problem persists with 2.5, with "standard" consul config.

**Comment by zbindenren** [comment]
@raypettersen the problem also persists with 2.6. And there are no plans to go back to the 
 <= 2.4 behavior. See #4898 for more information.

**Comment by raypettersen** [comment]
Yes, we're staying on 2.4.3 until we find a workaround. I thought #4898 would resolve the problem, but it didn't.
