### ISSUE TITLE
reload promethues config

### ISSUE THREAD

**Issue by 249510573** [prometheus/prometheus#4854]
What about the impact of   reloading the promethues config?  without any interruption of service?

**Comment by simonpasquier** [comment]
Thanks for your report. It looks as if this is actually a question about usage and not development. When reloading itself, Prometheus minimizes the interruption but depending on the concrete setup, we cannot guarantee that a few scrapes won't be missed.

To make your question, and all replies, easier to find, we suggest you move this over to our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search. If you prefer more interactive help, join or our [IRC channel](https://webchat.freenode.net/?randomnick=1&channels=prometheus), #prometheus on irc.freenode.net. Please be aware that our IRC channel has no logs, is not searchable, and that people might not answer quickly if they are busy or asleep. If in doubt, you should choose the mailing list.

Once your questions have been answered, please add a short line pointing to relevant replies in case anyone stumbles here via a search engine in the future.
