### ISSUE TITLE
Read Azure credentials from environment variable

### ISSUE THREAD

**Issue by yanivroz** [prometheus/prometheus#4857]
## Proposal
I saw in the documentation that you can obtain AWS credentials from environment varaibles:
```
# The AWS API keys. If blank, the environment variables `AWS_ACCESS_KEY_ID`
# and `AWS_SECRET_ACCESS_KEY` are used.
[ access_key: <string> ]
[ secret_key: <secret> ]
```
Any plan to support the same for Azure?
something like this:
```
# The Azure API keys. If blank, the environment variables `AZURE_SUBSCRIPTION_ID`,
# `AZURE_CLIENT_ID`, `AZURE_TENANT_ID`, and `AZURE_CLIENT_SECRET` are used.
[ subscription_id: <string> ]
[ tenant_id: <string> ]
[ client_id: <string> ]
[ client_secret: <secret> ]
```

**Comment by brian-brazil** [comment]
We recommend against using environment variables for secrets as they aren't designed for it. We also want to have just one place that configuration comes from. If the client we're using happens to this under the covers that's it's own business though.

**Comment by yanivroz** [comment]
@brian-brazil I understand your point but isn't this kind of inconsistent to have it for one type of service discovery and not for another?
Also, I believe the security issues should be left for the user to decide. After all, putting the secret in the prometheus.yml file as plain text is just as bad as keeping it as an environment variable in clear text, no? (or am I missing something?)

**Comment by yanivroz** [comment]
Azure does have these official environment variables used for similar use cases:
https://simple-azure.readthedocs.io/en/latest/arm.html
https://github.com/banzaicloud/azure-aks-client/blob/master/README.md

I just think it’s inconsistent that Prometheus supports this for AWS and not for Azure…

**Comment by brian-brazil** [comment]
> Azure does have these official environment variables used for similar use cases:

So why isn't it working out of the box today? Are we using the wrong API?

> I just think it’s inconsistent that Prometheus supports this for AWS and not for Azure…

Inconsistency between the official AWS and official Azure libraries is something to take up with Amazon/Microsoft

**Comment by brian-brazil** [comment]
We've looked at this as part of our bug scrub, and per the above we believe the current behaviour is okay. If there's something we're mis-using from the existing Azure APIs please let us know, but we don't take config from envvars per #2357.
