### ISSUE TITLE
Add a meta metric about the scrape format

### ISSUE THREAD

**Issue by roidelapluie** [prometheus/prometheus#4862]
With the same labels as up, I'd like to have a metric called:

scrape_format{name="openmetrics",transport="http",job="node",instance="srv01"} 1

That could ease the migration to openmetrics

**Comment by juliusv** [comment]
Hmm this would mix target labels and format labels on the same time series, with potential collision resolution required. Maybe a sample value enum instead? Another metric could then define the enum values, if needed.

Or we just add counters for how many endpoints in total were scraped in either format.

**Comment by roidelapluie** [comment]
actually I would like to see more metrics related to scrape in general, e.g. return code.. it would be metrics like "up"

**Comment by brian-brazil** [comment]
That's getting a bit into event logging. Keep in mind that any new time
series will be added to every single target that exists, which is not free.
