### ISSUE TITLE
Add non-cumulative distribution type

### ISSUE THREAD

**Issue by mml** [prometheus/prometheus#4863]
## Proposal

Sometimes it's valuable to report a distribution that's not cumulative.  Typical cumulative distributions aggregate approximately all observations since start time, and provide ways for us to examine rates and deltas to figure out things like QPS or "99th percentile latency in the last 30m".

Non-cumulative distribution types are like gauges.  Example usages/observations:  heap characteristics in a malloc implementation (i.e. "what are the counts and sizes of free objects"), or for a work queue, the amount of time each item has been in the queue.

**Comment by cheftako** [comment]
+1

**Comment by logicalhan** [comment]
+1

**Comment by lavalamp** [comment]
Additional color: you can *almost* do this with the existing summary in two different ways:
1. Use the MaxAge feature
2. Use a vector, with a fresh index each time (deleting the prior one)

Unfortunately neither of these (afaict) allow for concurrency guarantees around making observations, so the monitoring software could well take a reading while you're halfway through adding observations.

**Comment by brian-brazil** [comment]
PromQL already supports this via the `histogram` function. You will need to write a custom collector to expose data for this (which you'd need to do anyway). OpenMetrics has a GaugeHistogram type, which you can already use in custom collectors in client_python.

**Comment by juliusv** [comment]
Closing this as this is not an issue about the Prometheus server, but about how to expose this via client libraries (which is already possible).
