### ISSUE TITLE
How much memory does Prometheus need at least?

### ISSUE THREAD

**Issue by UnicornSymbol** [prometheus/prometheus#4877]
When I use 4G memory to run, prometheus2.0 memory usage has been increasing until it dies.

`- "--config.file=/etc/prometheus/prometheus.yml"
- "--storage.tsdb.path=/prometheus"
- "--storage.tsdb.retention=6h"
- "--storage.tsdb.max-block-duration=1h"
- "--web.enable-lifecycle"`

**Comment by kdada** [comment]
In our case, a prometheus instance with about 200 targets and 5 seconds scrape interval, uses 4G ~ 5G memory. 

What's scale of your prometheus?

**Comment by kdada** [comment]
Do you have some queries/alerts/rules which fetch two many metrics?

**Comment by UnicornSymbol** [comment]
I use Prometheus to collect data and grafana to display.I'm not sure is grafana showing too many queries.Do you use grafana?

**Comment by kdada** [comment]
We use grafana too. Our dashboards shows metrics about 30min~6h.

**Comment by simonpasquier** [comment]
Thanks for your report. It looks as if this is actually a question about usage and not development. BTW You shouldn't need to tweak the `storage.tsdb.max-block-duration` flag, it is only required for testing and benchmarking.

To make your question, and all replies, easier to find, we suggest you move this over to our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search. If you prefer more interactive help, join or our [IRC channel](https://webchat.freenode.net/?randomnick=1&channels=prometheus), #prometheus on irc.freenode.net. Please be aware that our IRC channel has no logs, is not searchable, and that people might not answer quickly if they are busy or asleep. If in doubt, you should choose the mailing list.

Once your questions have been answered, please add a short line pointing to relevant replies in case anyone stumbles here via a search engine in the future.
