### ISSUE TITLE
Binary operators should support by clauses

### ISSUE THREAD

**Issue by brian-brazil** [prometheus/prometheus#488]
Sometimes the LHS and RHS don't quite have the same labels, but are still matchable 1-to-1. Allowing by clauses on binary operators would allow for this use case.

#393 is a more advanced case where you want to do a 1-to-many match.

**Comment by brian-brazil** [comment]
More particularly if I have

```
a{label=foo,otherlabel=z} 1
b{label=foo} 2
```

then `a +  by (label) b` should produce:
```
{label=foo} 3
```

and if I have

```
a{label=foo,otherlabel=z} 1
a{label=foo,otherlabel=x} 1
b{label=foo} 2
```

the I'd get an error of some form as this usually indicates an error in the expression (#393 covers the case where you explicitly want this to work).

**Comment by beorn7** [comment]
Thanks for the explanation.

Since you are planning a similar thing for unary operators AKA functions, how would things work there?

**Comment by juliusv** [comment]
Done by @fabxc in https://github.com/prometheus/prometheus/pull/554.
