### ISSUE TITLE
Panic when using empty relabel config

### ISSUE THREAD

**Issue by xocasdashdash** [prometheus/prometheus#4889]
## Bug Report
**What did you do?**
I added an empty relabel config like so:
```
relabel_configs:
            -   source_labels: [ '__meta_dns_name' ]
                regex: 'node-exporter\.(.+?).+'
                target_label: 'az'
                replacement: '$1'
            -
```
**What did you expect to see?**
Prometheus not to panic.
**What did you see instead? Under which circumstances?**
It panics. ie: https://imgur.com/a/aFSiz5V
**Environment**

* System information:

Linux 3.10.0-862.el7.x86_64 x86_64

* Prometheus version:

	prometheus, version 2.5.0 (branch: HEAD, revision: 67dc912ac8b24f94a1fc478f352d25179c94ab9b)
  build user:       root@578ab108d0b9
  build date:       20181106-11:40:44
  go version:       go1.11.1

I also found this bug on 2.4.3

**Comment by juliusv** [comment]
Thanks for the report, looking into it!

**Comment by juliusv** [comment]
https://github.com/prometheus/prometheus/blob/master/relabel/relabel.go#L41 accesses `cfg.SourceLabels`, but `cfg` is a pointer that can actually become `nil` when initialized from an empty YAML object (an empty relabeling rule in this case). Either the list elements should not be pointers or we should check for `nil` values.

**Comment by simonpasquier** [comment]
I would lean towards rejecting any empty relabeling rule at load time since it isn't a useful configuration AFAICT.

**Comment by juliusv** [comment]
@simonpasquier Good point, that would be even better :)

**Comment by infoverload** [comment]
I am interested in working on this!

**Comment by juliusv** [comment]
Heads-up: I'm fixing all the slice-of-pointers config `nil` pointer crashes in one go, so this will be covered by that.
