### ISSUE TITLE
prometheus_sd_configs_failed_total is not actionable, gauge would be better

### ISSUE THREAD

**Issue by juliusv** [prometheus/prometheus#4890]
The metric `prometheus_sd_configs_failed_total` (https://github.com/prometheus/prometheus/blob/a9050c45f68f00cd9907df9bab96afd1908db934/discovery/manager.go#L44-L49) currently tracks the total number of SD configurations that were not able to be applied during configuration (re)load. However, the actual rate of that counter depends highly on the configuration reload rate, so a bad SD config might stick around forever without actually causing any counter increments. This means that this metric is not very useful for alerts. We should introduce a gauge metric that tells us how many SD configurations are currently invalid / were not able to be instantiated.

**Comment by infoverload** [comment]
I would like to work on this

**Comment by geekodour** [comment]
@infoverload , are you working on this?

**Comment by infoverload** [comment]
@geekodour hey, yes I am!

**Comment by palash25** [comment]
@juliusv I don't see any referenced PR by the original claimer on this issue, would it be okay if I take a crack at this?

**Comment by juliusv** [comment]
@palash25 Yes, please go ahead, I haven't heard anything in a while either from @infoverload about this.

**Comment by nevill** [comment]
@beorn7 This one can be closed since my PR got merged.
