### ISSUE TITLE
how to configure data compaction in prometheus server. i want to compact per second data to 1 min after 1 month then to 1h after 3 months and so on 

### ISSUE THREAD

**Issue by deep7710** [prometheus/prometheus#4893]
## Proposal
**Use case. Why is this important?**

*“Nice to have” is not a good use case. :)*

## Bug Report
**What did you do?**

**What did you expect to see?**

**What did you see instead? Under which circumstances?**

**Environment**

* System information:

	insert output of `uname -srm` here

* Prometheus version:

	insert output of `prometheus --version` here

* Alertmanager version:

	insert output of `alertmanager --version` here (if relevant to the issue)

* Prometheus configuration file:
```
insert configuration here
```

* Alertmanager configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```

**Comment by simonpasquier** [comment]
Downsampling isn't currently supported by Prometheus. You might want to look at [Thanos](https://github.com/improbable-eng/thanos#features) that already supports it.

I'm closing it for now. If you have further questions, please use our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search.

**Comment by deep7710** [comment]
1)is there any setup or configuration guide available for thanos?
2)how stable is thanos?
