### ISSUE TITLE
Buggy Discovery behavior

### ISSUE THREAD

**Issue by johnskopis** [prometheus/prometheus#4914]
Sorry for the terrible bug report. I don't have more time to spend on this and it's not incredibly critical.

1. Seems the Discovery instance (at least for marathon) does not close response so underlying transport leaks sockets. This was observed on a server trying to scrape an endpoint returning 5xx errors. After some period of time you can observe many sockets in CLOSE_WAIT state

2. After removing the faulty Discoverer from config and reloading the leaked sockets are not cleaned up (why?)

**Comment by simonpasquier** [comment]
Which version of Prometheus is it?

**Comment by xjewer** [comment]
prometheus 2.4.3, but it's actual in master

https://github.com/prometheus/prometheus/blob/master/discovery/marathon/marathon.go#L352

**Comment by simonpasquier** [comment]
Yep I see the bug now.
