### ISSUE TITLE
custom labels and up timeseries

### ISSUE THREAD

**Issue by nfrush** [prometheus/prometheus#4917]
## Bug Report
**What did you do?**
Added a metric_relabel_config to take values out of my instance name corresponding to the relative location and though it into a "rack" and "server" tag. When I queries the up timeseries, there is no such label on the series (on any sampling series provided by Prometheus). Not sure if this is intended behavior.  Note ona ny other collected metrics, these labels appear.

**What did you expect to see?**

The presence of the label on the up timeseries so that I could issue up({rack="some-rack"}) and get a report on how many machines within a rack we're up (or down). This also provides an ease for alerting if a rack goes down later on

**What did you see instead? Under which circumstances?**
The series up does not contain the custom labels as expected.

**Environment**

* System information:

	Centos 6.6

* Prometheus version:

	2.3.2

* Alertmanager version:

	0.15.1

**Comment by simonpasquier** [comment]
Please share your configuration.

**Comment by nfrush** [comment]
@simonpasquier That's not exactly possible. I can provide you a configuration that is "like" what I'm using in the codebase.

**Comment by simonpasquier** [comment]
@nfrush sure

**Comment by learon** [comment]
Same issue here:

Prometheus version: 2.5.0

Config:

    - job_name: node_exporter
    metric_relabel_configs:
    - source_labels: ['instance']
      action: replace
      regex: '([^:]+):\d+'
      replacement: $1
      target_label: 'instance'
    scrape_interval: 10s
    static_configs:
    - targets: ['server-1:2100']
      labels: {location: 'xx', type: 'xx', endpoint: 'xx'}
    - targets: ['server-2:2100']
      labels: {location: 'xx', type: 'xx', endpoint: 'xx'}


Result 
![screenshot_2](https://user-images.githubusercontent.com/8572255/50342886-3dc8a800-0525-11e9-801c-8563a87a8f3c.png)

**Comment by brian-brazil** [comment]
This is working as expected, metric_relabel_configs only applies to scraped metrics. You want relabel_configs.

**Comment by roidelapluie** [comment]
relabel_configs instead of metric_relabel_configs should indeed work, this issue can be closed.
