### ISSUE TITLE
Export value of sample_limit

### ISSUE THREAD

**Issue by svend** [prometheus/prometheus#4933]
## Proposal

This is a feature request.

Export value of `sample_limit` so that alerts can be set for scrapes that are approaching the limit without hard-coding the limit in the alert.

I checked the exported metrics on Prometheus 2.3.2 and didn't see this currently exported.

**Comment by brian-brazil** [comment]
This would be a new additional sample for every single target, which is not something to add lightly from a resource usage standpoint. It's expected that you'd know the values you're using, and not have many of them, so this could be handled fairly sanely via configuration management.

**Comment by svend** [comment]
That's a good point. I had forgotten that the limit was set per scape config, not globally.
