### ISSUE TITLE
Feature request: Filter queries on metric value in a time interval

### ISSUE THREAD

**Issue by wjwinner** [prometheus/prometheus#4934]
Starting using Prometheus I'm looking for a way to filter some of my queries on the metric value  in a time interval.

for example:

http_duration==200[5m]

Error executing query: parse error at char 24: range specification must be preceded by a metric selector, but follows a *promql.NumberLiteral instead

**Comment by simonpasquier** [comment]
I presume that you want to filter `http_series` series for . The expression should be something like `http_duration{code="200"}`. See https://prometheus.io/docs/prometheus/latest/querying/basics/

I'm closing it for now. If you have further questions, please use our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search.
