### ISSUE TITLE
Issue "divide by zero" on Prometheus 1.x during migration to Prometheus 2.x after file system full 

### ISSUE THREAD

**Issue by craph** [prometheus/prometheus#4936]
Hello,

I post this issue because I have a major issue with Prometheus 1.x after a file system full.

I am using GitLab-ce docker image in production and on monday morning we had a file system full and the GitLab instance including Prometheus inside break down.

After adding some space  I tried to do the migration to Prometheus 2.x.

I have open an issue here : https://gitlab.com/gitlab-org/gitlab-ce/issues/54470

But may be the tsdb is corrupted.

So my question is : 
Is it possible to repair the Prometheus data ?

Thank you very much for your help.

Best regards

**Comment by simonpasquier** [comment]
Thanks for your report. It looks as if this is actually a question about usage and not development.

To make your question, and all replies, easier to find, we suggest you move this over to our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search. If you prefer more interactive help, join or our [IRC channel](https://webchat.freenode.net/?randomnick=1&channels=prometheus), #prometheus on irc.freenode.net. Please be aware that our IRC channel has no logs, is not searchable, and that people might not answer quickly if they are busy or asleep. If in doubt, you should choose the mailing list.

Once your questions have been answered, please add a short line pointing to relevant replies in case anyone stumbles here via a search engine in the future.
