### ISSUE TITLE
Offer Prometheus DB as stand-alone TSDB

### ISSUE THREAD

**Issue by pachico** [prometheus/prometheus#4943]
## Proposal
Sorry in advance if this is not the proper forum to submit this to but I'm wondering if I'm the only one wishing to use Prometheus purely as a stand-alone TSDB and not as monitoring platform.
You might argue that I can do that at anytime simply disregarding jobs, alerts, etc., but I don't find it as elegant as a pure stand-alone DB would be, which is why I am now using InfluxDB.

I haven't found any use case for InfluxDB that couldn't be achieved with Prometheus DB.

Cheers

**Comment by brian-brazil** [comment]
The TSDB is at https://github.com/prometheus/tsdb if you wish to use it.

**Comment by pachico** [comment]
Thanks, @brian-brazil  for your reply. I am aware of the repository.
I was, however, thinking of a product itself, promoted and documented as such, with the possibility to write data points and recording rules via HTTP API, etc.
It might be out of strategic roadmap; I'm simply stating that I'd use it if it existed.

Cheers

**Comment by brian-brazil** [comment]
This is not something we plan, but there's nothing stopping you from creating such a thing yourself.

**Comment by pachico** [comment]
Fair enough, cheers!
