### ISSUE TITLE
No dec.DisallowUnknownFields() function

### ISSUE THREAD

**Issue by aixeshunter** [prometheus/prometheus#4948]
In prometheus/discovery/targetgroup/targetgroup.go file that line 81:
```
	dec := json.NewDecoder(bytes.NewReader(b))
	dec.DisallowUnknownFields()
	if err := dec.Decode(&g); err != nil {
		return err
	}
```
the `dec.DisallowUnknownFields()` functon call is error in my IDE.
Is that a BUG?

**Comment by simonpasquier** [comment]
`DisallowUnknownFields()` has been added to the `encoding/json` package in Go 1.10. You need preferably Go 1.11.2 to build Prometheus.

**Comment by aixeshunter** [comment]
it works, thanks
