### ISSUE TITLE
PromQL: Allow label append to groups of metrics

### ISSUE THREAD

**Issue by SuperQ** [prometheus/prometheus#4949]
## Proposal

From an IRC conversation with @ecraven, we had an idea to simplify some expressions by allowing labels to be applied to groups of metrics surrounded by `()`.

For example:
```
foo{env="prod"} / bar{label="prod"}
```

Becomes:
```
(foo / bar){env="prod"}
```

The effect for other labels applied to `foo` and `bar` would be to append the list of label filters to any interior ones.

For example:
```
(foo{blah="blah"} / bar{blah="blah"}){env="prod"}
```

Would translate to:
```
foo{blah="blah",env="prod"} / bar{blah="blah",env="prod"}
```

**Comment by aixeshunter** [comment]
Good idea :+1:

**Comment by brian-brazil** [comment]
I'm not sure about this. Given how the rest of the language works, I'd expect this to evaluate all of `foo{blah="blah"} / bar{blah="blah"}` and then restrict it down. I'm also generally against features that are merely another way of writing something that we already support.

**Comment by ecraven** [comment]
The reason I tried this was a form like
((foo - bar - baaz) / foo) where I'd have to repeat the labels four times :-/

**Comment by RichiH** [comment]
@SuperQ we're doing our weekly bug scrub ATM; I suspect you're still interesting in this?

**Comment by SuperQ** [comment]
I still think it might be a nice way to simplify queries.

**Comment by roidelapluie** [comment]
At some point I was thinking that we could do that automatically in the promql engine itself but apparently remore read prevents that. In which case the parser is the place to do it. But how do you see that?

Does (foo / bar){env="prod"}
 become foo{env="prod"} / bar{label="prod"}

or does  (foo / bar){env="prod"} do
foo / bar then selects {env="prod"}, which means that we can use that on functions too?

**Comment by slrtbtfs** [comment]
We could recursively add the outer selector to every selector inside the respective subtree. That should be possible to do in the engine and would be similar to how we already treat subqueries.

The interesting part would be how to deal with functions like `label_replace`.

**Comment by brian-brazil** [comment]
This is a form of templating, which can always be done by configuration management. We shouldn't ever be making PromQL more complex to substitute for a lack of templating on the part of the user or merely to reduce apparent duplication.

The semantics here are also unclear, as there's two different things that this syntax could mean as seen above. Things like label_replace only make it more complicated.

**Comment by codesome** [comment]
> Does (foo / bar){env="prod"}
become foo{env="prod"} / bar{label="prod"}

This should be the one if we are going ahead with it. The other one would have a lot of unnecessary calculations.

**Comment by brian-brazil** [comment]
Just had a better example of how this is very unclear semantically come to mind. What would `sum(foo){a="b"}` do?

I don't think we should be adding confusing new syntax and non-obvious semantics to cover things that are already possible.

**Comment by slrtbtfs** [comment]
What would `sum(foo){a="b"}` do?

`sum(foo{a="b"})`?

**Comment by brian-brazil** [comment]
That's not what it looks like though, I'd expect it to return nothing as the output of `sum(foo)` won't have an `a` label. This would get even more fun when vector matching is involved.

**Comment by roidelapluie** [comment]
yeah this does not look sane

**Comment by RichiH** [comment]
Anything in curlies would only apply to the scope of the parentheses directly in front of them. If users try to select on non-existing labels, they would receive an empty return set no matter which foot-gun they would be using.

**Comment by juliusv** [comment]
Yeah, this seems both confusing to read, and a concept that doesn't really fit to the rest of the language, where parent nodes do not affect the evaluation of child nodes, only the other way around.

**Comment by slrtbtfs** [comment]
> where parent nodes do not affect the evaluation of child nodes, only the other way around.

Don't subqueries affect their child nodes?

**Comment by brian-brazil** [comment]
> Don't subqueries affect their child nodes?

They don't, it's an independent evaluation.

**Comment by Harkishen-Singh** [comment]
@brian-brazil are we going ahead with this? else we can close the issue since it seems less likely as per the discussions.

**Comment by brian-brazil** [comment]
While there's a definite strong feeling here that this should not be implemented, there's not a consensus.

**Comment by krajorama** [comment]
Hello from the bug scrub! Closing as this is a somewhat controversial feature request and also there was no discussion in the last four years. Please follow up with new proposal if you want to work on this issue.
