### ISSUE TITLE
Application log monitoring

### ISSUE THREAD

**Issue by deep7710** [prometheus/prometheus#4950]
I have my application generating 10 types of log files and I have it running on 100s of servers. I want to monitor these log files. at the same time, i want to find "ERRORS/EXCEPTIONS etc." which gets printed in these log files and raise alert. Is there a exporter which can handle this?? Infact handle multiple log files!!! I have tries grok_exporter but it can handle only 1 at a time and I do not want to start so many exporters!!!

**Comment by simonpasquier** [comment]
You can look at https://github.com/google/mtail too.

I'm closing it for now. If you have further questions, please use our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search.
