### ISSUE TITLE
Querier.Select now returns a third thing 'warnings' - can't pass golint...

### ISSUE THREAD

**Issue by tomwilkie** [prometheus/prometheus#4956]
As of #4832 we've added a third parameter to `Querier.Select`, but this makes it impossible to implement this interface in a golint clean way:

```
./pkg/querier/querier.go:114:1: error should be the last type when returning multiple items
```

We'd like to stay golint clean in Cortex; anyone object to me making error last in that interface?  And perhaps adding golint to our CI...

**Comment by brian-brazil** [comment]
Sure, go ahead. You'll need to touch it in quite a few places.
