### ISSUE TITLE
Consider reducing label cardinality for persist error exporting

### ISSUE THREAD

**Issue by juliusv** [prometheus/prometheus#496]
Currently we export the label `error="<entire error string>"` for persist errors on the metric `prometheus_local_storage_persist_errors_total`:

https://github.com/prometheus/prometheus/blob/f541390dfbd504fde9acbd7c684a3e889e19c2f3/storage/local/storage.go#L539

In a Prometheus whose disk just ran full, this already produced two different error strings:

    offset 262144 is not a multiple of on-disk chunk length 1041
    offset 131072 is not a multiple of on-disk chunk length 1041

Conceivably there could be many more different offsets affected, so we should probably clamp down the label cardinality on this one.

/cc @beorn7

**Comment by brian-brazil** [comment]
From quick look this should be a no-label counter, it's already in the logs.
