### ISSUE TITLE
Shoud OpenMetrics be compatible with or consider dropwizard metrics?

### ISSUE THREAD

**Issue by TsingLiang** [prometheus/prometheus#4963]
Dropwizard metrics format is diffrent from prometheus metrics. And now, dropwizard metrics is widely used in in the field of big data, like Hadoop，Kafka，Spark，JStorm.Shoud OpenMetrics be compatible with or consider dropwizard metrics?

**Comment by brian-brazil** [comment]
Wrong repo, answered elsewhere.
