### ISSUE TITLE
question about use prometheus to measure each user access if user more than 100k?

### ISSUE THREAD

**Issue by aximo** [prometheus/prometheus#4965]
it not a bug,but an use question, sorry for submitting it here as google group is not acess in china.

Eg, I want to use metrics user acess via http_acess_count{uid="001"} =1

So if the user count is 100k and all access our system, that means  there will be 100k line(at least) in each scrape. the response body will so big.

maybe we can compress the response, but any supported in prometheus server?

and , I don't think this solution is real effective?

So, any comments about this case. how can i measure each user access by it?

**Comment by simonpasquier** [comment]
That's not really what Prometheus is meant for. See https://prometheus.io/docs/practices/instrumentation/#do-not-overuse-labels

**Comment by aximo** [comment]
@simonpasquier get it ,thanks!
