### ISSUE TITLE
Proposal, change default tsdb retention to be much bigger (or smaller)

### ISSUE THREAD

**Issue by baryluk** [prometheus/prometheus#4981]
Hi,

I had my prometheus running for few months, but I just noticed that (after upgrading to 2.6~rc0), that I can't see any data older than few days. I have few small instances of prometheus that were configured quickly without much rules or configs, other than simply adding few static targets (monitoring single target, or just few small servers / network appliances for getting some data in).

Reading https://prometheus.io/docs/prometheus/latest/storage/ , it appears that default retention (`--storage.tsdb.retention` is just 15 days.

Obviously for serious production I would configure it manually, but in many cases where I just startup prometheus for a one server, or run it for development, I would prefer to have default retention be much longer out of the box, to minimize configuration.

I can't fine any reasoning behind setting default of `15d`.

I would prefer much more running out of disk space, and getting some alert, than loosing data so early by default.

I would propose to change default to either significantly less (to force custom retention, and be easy to spot quickly), or to something usable by most without any tweaks. That is either `1d`, or `1y`.

**Comment by brian-brazil** [comment]
We had discussed and agreed on this for 2.0 but noone made the change. As
this is a breaking change (some users may not have the disk for this) we
have to wait for 3.0, whenever that is.

**Comment by krajorama** [comment]
Hello from the bug scrub! Closing due to the fact that there are multiple solutions leveraging Prometheus to provide long term storage.  Also changing the default after many years would be disruptive and nobody else requested this.
