### ISSUE TITLE
Break out all discovery metrics by name

### ISSUE THREAD

**Issue by brian-brazil** [prometheus/prometheus#4993]
It'd be useful if all the metrics in https://github.com/prometheus/prometheus/blob/master/discovery/manager.go were broken out by name, as that's help debug which discovery manager is having an issue.

**Comment by qoops-1** [comment]
Hi, I'm interested in working on this one. Just to clarify: do you want to add labels to all these metrics, so that it would be possible to filter them by the type of service discovery?

**Comment by brian-brazil** [comment]
Yes, like discoveredTargets is done now but only with a name label.
