### ISSUE TITLE
Missing a data point as adjusting query step

### ISSUE THREAD

**Issue by yhkim713** [prometheus/prometheus#4995]
## Bug Report
**What did you do?**
Adjusting step param(required from query_range API) to make my graph more pretty but some points are missing unexpectedly.
A data scrape interval is 10sec

a first query is 
```
increase(exception[1m] with a step 59s
--- it's json output is 
values:Array[7]
0:Array[1544668439,0]
1:Array[1544668498,0]
2:Array[1544668557,1.2]
3:Array[1544668616,0]
4:Array[1544668675,0]
5:Array[1544668734,0]
6:Array[1544668793,0]
```
and second query is
```
increase(exception[1m]) with a step 60s
--- it's json output is
values:Array[6]
0:Array[1544668440,0]
1:Array[1544668500,0]
2:Array[1544668560,0] // here, I expected that it should have a value
3:Array[1544668620,0]
4:Array[1544668680,0]
5:Array[1544668740,0]
```

**Environment**

* Prometheus version:
prometheus, version 2.1.0 (branch: HEAD, revision: 85f23d82a045d103ea7f3c89a91fba4a93e6367a)
  build user:       root@6e784304d3ff
  build date:       20180119-12:01:23
  go version:       go1.9.2

**Comment by simonpasquier** [comment]
As stated in the [documentation](https://prometheus.io/docs/introduction/overview/#when-does-it-not-fit), Prometheus doesn't aim for 100% accuracy. This is why `rate()`/`increase()`, especially applied to slowly increasing counters, don't always yield the same results depending on the step interval. See https://github.com/prometheus/prometheus/issues/3746 for a (much) longer discussion and the current take from the Prometheus team. 

I'm closing it for now. If you have further questions, please use our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search.

**Comment by yhkim713** [comment]
thank you for your detailed answer and the link

**Comment by brian-brazil** [comment]
The issue here is more that your step and range are about the same, you want a range that's larger than your step to avoid things like this.
