### ISSUE TITLE
Actual timestamp() for max_over_time (and other agg functions)

### ISSUE THREAD

**Issue by ali-sattari** [prometheus/prometheus#5003]
## Proposal
**Use case. Why is this important?**
Knowing when a min or max happened in defined window of time is useful. Imagine monitoring a gauge like metric over a week, you want to know the max value in that period (easy) and the time it happened (currently impossible using PromQL)

Something like:
```
max_over_time(shop_online_users{dimension="frontpage"}[1w])
```
Would give the value, but we don't know when the `max` point happened in `1w`.

**Suggestion**
If only the `timestamp()` (or a new function) would return the actual timestamp of evaluated point in time, the problem would be solved:
```
timestamp(max_over_time(shop_concurrent_users{dimension="frontpage"}[1w]))
```
It returns `now` or actually same value as `time()` at the moment.

I can see the `timestamp()` can return the actual timestamp of a metric (only last value) when used without aggregate functions, as discussed in #1557

**Comment by ali-sattari** [comment]
Yes, I figured, so if in any case it should be a new function.

I think any aggregate function that ultimately points to one record in timeline (min, max most notable) can be easily (in theory) be accompanied with the actual timestamp. The case for other aggregate functions such as avg or quantile gets complicated and perhaps not very useful.

I have the external solution (saving each new max or min in a separate metric) as an alternative in mind, but having this built in would be nice too. 

This is rather the default mode in InfluxDB (although kind of comparing apples and oranges): https://docs.influxdata.com/influxdb/v1.7/query_language/functions/#max

**Comment by roidelapluie** [comment]
what if there are multiple ??

**Comment by diegoroccia** [comment]
the following function would return only the points where the metric matches the max_over time

`shop_online_users{dimension="frontpage"} == max_over_time(shop_online_users{dimension="frontpage"}[1w]))`

would this help? We are looking to do something similar

**Comment by ali-sattari** [comment]
@diegoroccia How is the output of that expression different than `max_over_time` alone?

@roidelapluie I guess along with current behavior of `timestamp` the new function could only return timestamp for the last point.

**Comment by diegoroccia** [comment]
have you tried it? it **only** gives you the data points (with timestamp) where the metric matched the max_over_time value, thus giving you the point in time when the peak happened

**Comment by ali-sattari** [comment]
@diegoroccia It doesn't work very well as an instant query, unless the data point in question lies within past 5 minutes or so (due to staleness and max lookback?). I tried it with a `query_range` call that had start and end parameters matching range vector of `max_over_time` and I got all of the data points in that range that matched, with their respective timestamps.

Can you make a more specific example if you have got it working with your metrics? I.e in a dashboard.

**Comment by everispvaquezm** [comment]
> have you tried it? it **only** gives you the data points (with timestamp) where the metric matched the max_over_time value, thus giving you the point in time when the peak happened

Have you tried, because what you suggested is absolutely useless

**Comment by everispvaquezm** [comment]
> have you tried it? it **only** gives you the data points (with timestamp) where the metric matched the max_over_time value, thus giving you the point in time when the peak happened

You should be the one having tried this before suggesting such an useless solution

**Comment by onlyacat** [comment]
Would like to know if there is a workaround or not. Thanks in advance!

**Comment by beorn7** [comment]
Hello from the bug scrub,

As the discussion has shown, implementing this particular feature is difficult or even impossible (mostly arguing around the lines that there can be multiple samples that all match the maximum). The attempt to implement a separate function #7613 lead nowhere.

However, the handling of timestamps could be modified more fundamentally, and that's being discussed in #8966. It needs deep thought, but maybe we can still pick it up for v3.

We'll close this in lieu of #8966.

**Comment by BrivinTech** [comment]
What is the status of this issue? Is it fixed? Or any workaround found?

**Comment by IsQiao** [comment]
**PromQL no solution, it is a workaround solution:**

``` promql
# step 1, find max value in over time
max_over_time(your_expression{a="111"})[1d:5m])
# now, get the max value is 888(for example)

# step 2, find all timestamps that metric value is the max value
 (your_expression{a="111"}== 888)[1d:5m]
```

**MetricQL solution, it's easy:**

``` metricql
tmax_over_time(your_expression{a="111"})[1d:5m])
```
