### ISSUE TITLE
tsdb.retention use problem

### ISSUE THREAD

**Issue by timchenxiaoyu** [prometheus/prometheus#5005]
version=2.5.0, branch=HEAD, revision=67dc912ac8b24f94a1fc478f352d25179c94ab9bset   
set   --storage.tsdb.retention=4h 

![image](https://user-images.githubusercontent.com/9782796/50072820-81fc3580-0211-11e9-991a-a90a13b2373d.png)
get more than 4h  monitor data ,why

**Comment by codesome** [comment]
Blocks are deleted as a whole when it goes beyond retention period. 

In your case, assuming block range was `2h`, and prometheus started at `2h20m`, then the blocks would be `2h20m->4h20m`,`4h20m->6h20m`,`6h20m->8h20m`. So when the block `2h20m-4h20m` goes beyond retention period (`8h20m - 4h = 4h20m`), that block will be deleted. In your graph you have not touched that time yet.

**Comment by timchenxiaoyu** [comment]
![image](https://user-images.githubusercontent.com/9782796/50123597-54100300-029c-11e9-8b87-b5c698531f69.png)
more than two blocks.

**Comment by aixeshunter** [comment]
I have same issuse, could someone tell me where is the code about tsdb retention?

**Comment by codesome** [comment]
https://github.com/prometheus/tsdb/blob/79869d9a4d3d29c494d626aa626724688bbcbe3d/db.go#L515-L518

**Comment by aixeshunter** [comment]
> https://github.com/prometheus/tsdb/blob/79869d9a4d3d29c494d626aa626724688bbcbe3d/db.go#L515-L518

@codesome thanks!

**Comment by simonpasquier** [comment]
IIUC here what happens. When the retention kicks in, we have:

0. The WAL range is [t-2h, t]
0. The last (most recent) block is [t-4h, t-2h]
0. The (last - 1) block is [t-6h, t-4h]
0. The (last - 2) block is [t-8h, t-6h]
0. The (last - 3) block is [t-10h, t-8h]

TSDB doesn't account for data in the WAL for retention adn uses maxTime of the latest block (eg `t-2h`) as the reference time so if you have a retention period of 4h, it will delete all blocks that have their upper bound less than `t - 2h - 4h = t - 6h` which would only be the block at index 4 in the above example. Conclusion: you can have up to 10h of data.

https://github.com/prometheus/prometheus/blob/68f0787c37d530394328171a1e9e86d336f2cfb3/vendor/github.com/prometheus/tsdb/db.go#L339-L356

**Comment by timchenxiaoyu** [comment]
![image](https://user-images.githubusercontent.com/9782796/50191865-acadd180-036a-11e9-9a84-8cef830f2991.png)

as you say  will delete index4[t-10h, t-8h]   ,but i can get [t-12h, t-10h] mostly

**Comment by timchenxiaoyu** [comment]
![image](https://user-images.githubusercontent.com/9782796/50193440-9ce5bb80-0371-11e9-8d86-1369b99b4298.png)
after hour later ,I only get [t-10h, t-8h]. strange!

**Comment by timchenxiaoyu** [comment]
I Know   .  now is  Wed Dec 19 10:50:02 CST 2018
but recent block is  "maxTime": 1545177600000,  2018/12/19 8:0:0  not  2018/12/19 10:0:0 
wal log  contain more than two hour
