### ISSUE TITLE
CORS: Leave user configure CORS in prometheus.yml

### ISSUE THREAD

**Issue by aloababa** [prometheus/prometheus#5010]
According to prometheus code Allowed Origin is always set to '*'.

`
var corsHeaders = map[string]string{
	"Access-Control-Allow-Headers":  "Accept, Authorization, Content-Type, Origin",
	"Access-Control-Allow-Methods":  "GET, OPTIONS",
	"Access-Control-Allow-Origin":   "*",
	"Access-Control-Expose-Headers": "Date",
}
`

So what if i want a single allowed origin ?

It would be nice to allow user configure allowed origins or disable cors in prometheus.yml

**Comment by brian-brazil** [comment]
Per previous discussions, this would make more sense as a flag.

**Comment by geekodour** [comment]
I'll try to send a PR for this one today.

**Comment by cstyan** [comment]
looks like the two PR's fix this, can we close?
