### ISSUE TITLE
Stacked graphs in /graph have increasingly incorrect max values

### ISSUE THREAD

**Issue by smarterclayton** [prometheus/prometheus#5017]
## Bug Report

Generated a stacked graph that was many small aggregates over a long window (a week).  As I increased the window size from 1 hour to 1 week, the max Y value of the graph was increasingly inaccurate, and the stacked data went from filling 90% of the min -> max Y value to filling only 5-10% of the vertical area of the graph.  There were no outlier values that I am aware of above that limit.  If I disable stacking on the long window, the series occupy most of the range of the vertical area.

I expected as I increased the window that stacked would continue to take up most of the Y range.

![Unstacked at 2w](https://www.dropbox.com/s/qj5x1l7vjibtl6z/Screenshot%202018-12-19%2014.31.20.png?raw=1)

![Stacked at 2w](https://www.dropbox.com/s/6gn5n1z4mbntasn/Screenshot%202018-12-19%2014.32.35.png?raw=1)

![Stacked at 1d](https://www.dropbox.com/s/uptou9uo0g2f44l/Screenshot%202018-12-19%2014.32.57.png?raw=1)

![Stacked at 2h](https://www.dropbox.com/s/ds1cxtnlw41cx5d/Screenshot%202018-12-19%2014.33.18.png?raw=1)

It looks as if it is estimating the max Y incorrectly the larger the range.

**Environment**

* Prometheus version:

```
2.3.2
71af5e29e815795e9dd14742ee7725682fa14b7b
20180712-14:02:52
go1.10.3
```

**Comment by brian-brazil** [comment]
It'd be good to see if this is still happening with the new UI.

**Comment by beorn7** [comment]
Hello from the bug scrub, 

Nobody has complained about this in the last four years, so we assume this is not an issue anymore with the new UI. If you have evidence that it is still an issue, please follow up here so that we can re-open.
