### ISSUE TITLE
The Makefile magic that assembles the Go download address does not work on all architectures.

### ISSUE THREAD

**Issue by rkubik** [prometheus/prometheus#503]
Makefile.INCLUDE has:
ARCH=$(shell uname -m)

It uses this architecture string to pull from https://golang.org/dl/. Since go1.4.1.linux-i686.tar.gz does not exist the build will fail. It should pull go1.4.1.linux-386.tar.gz instead.

**Comment by beorn7** [comment]
Oops... we need to fix that in other makefiles, too.

**Comment by beorn7** [comment]
Apparently, the same issue happens if you run on Windows... We should check the ARCH magic for all platforms supported by Go. I'll change the title of this issue accordingly.

**Comment by juliusv** [comment]
@rkubik Could you try if https://github.com/prometheus/prometheus/pull/507 fixes this? We don't have any i686 around...

**Comment by gkoz** [comment]
While there, you might want to fix `GOOS` to do `s/FreeBSD/freebsd/` too.

**Comment by juliusv** [comment]
@gkoz Thanks for pointing that out. Added the `GOOS` fix to the PR. Not sure what you mean with `s/386/i386/`? The links I see on https://golang.org/dl/ contain `386`?

**Comment by gkoz** [comment]
@juliusv I think the `i%86` pattern in you PR should work for freebsd too.

**Comment by rkubik** [comment]
@juliusv Your #507 patch works on i686. Thank you.

**Comment by juliusv** [comment]
@rkubik @gkoz Thanks! Merged.
