### ISSUE TITLE
Server does not shut down cleanly when rules file has syntax errors.

### ISSUE THREAD

**Issue by beorn7** [prometheus/prometheus#504]
Should be easy to fix... either load rules before starting the storage, or shut down storage cleanly if rules don't parse.

**Comment by beorn7** [comment]
Other errors (e.g. if the web.listen address cannot be bound to) may have the same effect.

**Comment by fabxc** [comment]
The rule issue should be fixed by #694 as we no longer shutdown if rules don't parse.

**Comment by juliusv** [comment]
@fabxc But this previously only affected startups - and we still want to die when the configs/rules can't be parsed upon startup, no?

**Comment by fabxc** [comment]
Yes, that's what I was talking about with @beorn7 before. We won't get around restructuring the storage startup.

You can find an attempt [in this branch.](https://github.com/prometheus/prometheus/compare/fabxc/servdisc...fabxc/cfg_check)

No background goroutines are started until after `Storage.Start()` knows that it can return without an error.
Chances are I missed something essential, so the general approach has to be verified by @beorn7 :)

**Comment by fabxc** [comment]
Fixed by #704
