### ISSUE TITLE
which metric is the pod actual metric  

### ISSUE THREAD

**Issue by dengceltics** [prometheus/prometheus#5041]
I get three metrics when i check container_memory_max_usage_bytes{pod_name="prometheus-core-6b5dc8dd4d-z4dvl"}.

![image](https://user-images.githubusercontent.com/42082255/50440950-68569e80-0933-11e9-904a-9357719ab779.png)

Here is the details of the picture:

metric1:
container_memory_max_usage_bytes{beta_kubernetes_io_arch="amd64",beta_kubernetes_io_os="linux",cluster="prod-kubernetes",id="/kubepods/podff7725bf-08da-11e9-a53f-066788000017",instance="node-rwc3apul",job="kubernetes-cadvisor",kubernetes_io_hostname="node-rwc3apul",namespace="monitoring",pod_name="prometheus-core-6b5dc8dd4d-z4dvl"}

metric2:
container_memory_max_usage_bytes{beta_kubernetes_io_arch="amd64",beta_kubernetes_io_os="linux",cluster="prod-kubernetes",container_name="prometheus",id="/kubepods/podff7725bf-08da-11e9-a53f-066788000017/babf8a744fb4f9297dc1d095d89a6444fcce655753396dc66e770ec835241539",image="sha256:42e450d926a80488ea5166225a197da923fd085efed20b811c324842e8352ecc",instance="node-rwc3apul",job="kubernetes-cadvisor",kubernetes_io_hostname="node-rwc3apul",name="k8s_prometheus_prometheus-core-6b5dc8dd4d-z4dvl_monitoring_ff7725bf-08da-11e9-a53f-066788000017_0",namespace="monitoring",pod_name="prometheus-core-6b5dc8dd4d-z4dvl"}
metric3:
container_memory_max_usage_bytes{beta_kubernetes_io_arch="amd64",beta_kubernetes_io_os="linux",cluster="prod-kubernetes",container_name="POD",id="/kubepods/podff7725bf-08da-11e9-a53f-066788000017/17c3cafe254d195027db61143ddfb247c3b0a8a845efebf3bdb3973fa214db70",image="10.4.79.28:5000/gcr.io/google_containers/pause-amd64:3.1",instance="node-rwc3apul",job="kubernetes-cadvisor",kubernetes_io_hostname="node-rwc3apul",name="k8s_POD_prometheus-core-6b5dc8dd4d-z4dvl_monitoring_ff7725bf-08da-11e9-a53f-066788000017_0",namespace="monitoring",pod_name="prometheus-core-6b5dc8dd4d-z4dvl"}

So,which is the pod "prometheus-core-6b5dc8dd4d-z4dvl"  "container_memory_max_usage_bytes" metric .

**Comment by dengceltics** [comment]
![image](https://user-images.githubusercontent.com/42082255/50440795-bb7c2180-0932-11e9-9352-aef2d37d61f2.png)

**Comment by codesome** [comment]
@dengceltics `container_memory_max_usage_bytes{pod_name="prometheus-core-6b5dc8dd4d-z4dvl"}` would select all those metrics which have `__name__="container_memory_max_usage_bytes"` and `pod_name="prometheus-core-6b5dc8dd4d-z4dvl"`. The other labels in the metrics should give you more insight (like `id`).

This question seems to be more on a usage side, please use [prometheus-users](https://groups.google.com/forum/#!forum/prometheus-users) mailing list for such queries.

**Comment by dengceltics** [comment]
> @dengceltics `container_memory_max_usage_bytes{pod_name="prometheus-core-6b5dc8dd4d-z4dvl"}` would select all those metrics which have `__name__="container_memory_max_usage_bytes"` and `pod_name="prometheus-core-6b5dc8dd4d-z4dvl"`. The other labels in the metrics should give you more insight (like `id`).
> 
> This question seems to be more on a usage side, I suggest you to use [prometheus-users](https://groups.google.com/forum/#!forum/prometheus-users) mailing list or `#prometheus` channel on IRC for that.
> https://prometheus.io/community/

Thanks. But the question confused me is that the pod named `prometheus-core-6b5dc8dd4d-z4dvl` must have just one metric named `container_memory_max_usage_bytes` .Such as one linux host's os is either 64-bit or 32-bit. So  `prometheus-core-6b5dc8dd4d-z4dvl`  `container_memory_max_usage_bytes ` value is can't be three numeric valuse.

Sorry,i'll go  #prometheus channel  after i solve this problem.

**Comment by aixeshunter** [comment]
Maybe `sum by(instance, pod_name, namespace) (container_memory_max_usage_bytes{pod_name="prometheus-core-6b5dc8dd4d-z4dvl"}) / 2` is work?

**Comment by simonpasquier** [comment]
Closing it for now. As @codesome already wrote, it is a usage question, not an issue.
