### ISSUE TITLE
In "Service discorvey" page , some object's "Target Labels" is Dropped  

### ISSUE THREAD

**Issue by dengceltics** [prometheus/prometheus#5042]
The main reference of my yaml file is "https://github.com/giantswarm/kubernetes-prometheus/blob/master/manifests-all.yaml" 

The Issue picture :

![image](https://user-images.githubusercontent.com/42082255/50441646-ad300480-0936-11e9-89ff-29cd2da5e9ac.png)
![image](https://user-images.githubusercontent.com/42082255/50441651-b325e580-0936-11e9-8d38-75659dea6f2f.png)
![image](https://user-images.githubusercontent.com/42082255/50441665-b91bc680-0936-11e9-97a7-0e5574a35500.png)

Thanks!

**Comment by simonpasquier** [comment]
Thanks for your report. It looks as if this is actually a question about usage and not development.

To make your question, and all replies, easier to find, we suggest you move this over to our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search. If you prefer more interactive help, join or our [IRC channel](https://webchat.freenode.net/?randomnick=1&channels=prometheus), #prometheus on irc.freenode.net. Please be aware that our IRC channel has no logs, is not searchable, and that people might not answer quickly if they are busy or asleep. If in doubt, you should choose the mailing list.

Once your questions have been answered, please add a short line pointing to relevant replies in case anyone stumbles here via a search engine in the future.
