### ISSUE TITLE
Support left/right_elementwise for operators

### ISSUE THREAD

**Issue by mwitkow-io** [prometheus/prometheus#506]
When operating on vectors:
 `my_stuff_started - my_stuff_stopped`, where both have a `type` label, the entries in `my_stuff_started` that don't have a matching `my_stuff_stopped` entry are removed from results. That's understandable, operators do a full join.

However, it should be possible to say  that I want to retain stuff from `my_stuff_started` even if it is not present in `my_stuff_stopped`. 

I understand that best practices are to prepopulate all your labels with default values, but sometimes it's impossible.

Are there any plans to implement left/right_elementwise

**Comment by brian-brazil** [comment]
This is covered by #393.

For that particular use case I'm not sure that's the best way to model it, missing time series are difficult to deal with at the best of times (http://prometheus.io/docs/practices/instrumentation/#avoid-missing-metrics). I'd suggest for determining the duration of batch jobs to export the duration as a separate gauge, see http://prometheus.io/client_java/io/prometheus/client/exporter/PushGateway.html for a Java example.
