### ISSUE TITLE
Proposal: CoreDNS port 9153 should be explicitly reserved

### ISSUE THREAD

**Issue by mjtrangoni** [prometheus/prometheus#5062]
## Proposal
Regarding [#955](https://github.com/kubernetes/kubeadm/issues/955) and [#65589](https://github.com/kubernetes/kubernetes/pull/65589), IMHO, I think [CoreDNS](https://coredns.io/) port **9153** should be  *explicitly* reserved for CoreDNS. 

Port 9153 is currently reserved [here](https://github.com/prometheus/prometheus/wiki/Default-port-allocations) for [mandrill-prometheus-exporter](https://github.com/hypoport/mandrill-prometheus-exporter).

**Comment by brian-brazil** [comment]
The port numbers are suggestions to avoid clashes with other exporters, and we can't avoid every existing port that some application uses. If you've a clash, you can always change the default when running it.

**Comment by simonpasquier** [comment]
Closing it as there's nothing to be done here.
