### ISSUE TITLE
Support AWS Timestream as remote storage

### ISSUE THREAD

**Issue by peimanja** [prometheus/prometheus#5086]
## Proposal
**Use case. Why is this important?**
AWS announced [Amazon Timestream](https://aws.amazon.com/timestream/) as a fast, scalable, fully managed time series database. It would be great if Prometheus add support to this database as remote storage.

**Comment by simonpasquier** [comment]
There's nothing needed from Prometheus to support Timestream. Either AWS provides API endpoints compatible with the remote storage interfaces or someone has to write an adapter for it (see https://prometheus.io/docs/prometheus/latest/storage/#remote-storage-integrations for more details).

**Comment by fromz** [comment]
Does anyone know it there are any projects out there to write an adaptor for Prometheus?
