### ISSUE TITLE
Make hash collisions less likely.

### ISSUE THREAD

**Issue by beorn7** [prometheus/prometheus#509]
The 64bit hashes we use currently have an uncomfortably high probability to cause a hash collision on very large servers. Investigate remedies (either in hash generation or size...).

**Comment by brian-brazil** [comment]
Long term I think we should be looking at solutions that don't depend on a lack of hash collisions.

**Comment by beorn7** [comment]
FIxed by https://github.com/prometheus/prometheus/pull/682

**Comment by sanga** [comment]
Seems like the text at the bottom of this page requires some updating btw: http://prometheus.io/docs/operating/storage/

**Comment by fabxc** [comment]
The docs are already updated, just has to go live. Which is temporarily
blocked, which is my fault.

**Comment by sanga** [comment]
Cool. Cheers
