### ISSUE TITLE
Mechanism Search based on new label created through label_join function

### ISSUE THREAD

**Issue by xenthik** [prometheus/prometheus#5097]
## Proposal

As you already know using  label_join() and label_replace() function can be used to add new label dynamically. But there is way by to do matching/search on top of this newly added label. So this new label is useless if it can't be used as other label. 

**What did you do?**

for example, A new label "full_name" is created by using existing two labels first_name and last_name in the following query. 

label_join(sum(app:healthcheck:gauge{application="collectHealthies"} != bool 200) by (first_name, last_name), "full_name", " ", "first_name", "last_name")

let's say the output is:

{first_name="Jack",full_name="Jack daniels",last_name="daniels"}	10
{first_name="Glen",full_name="Glen fiddich",last_name="fiddich"}       0
{first_name="Royal",full_name="Royal stag",last_name="stag"}             3

There is no mechanism to search based on new label i.e. full_name.

label_join(sum(app:healthcheck:gauge{application="collectHealthies", full_name="Glen fiddich"} != bool 200) by (first_name, last_name), "full_name", " ", "first_name", "last_name") 

returns nothing.

**What did you expect to see?**

{first_name="Glen",full_name="Glen fiddich",last_name="fiddich"}       0

**Use case. here full_name is use less kind of label, for instance: In Grafana this new variable can be used to create template variable, and this template variable can be used with repeat panel functionality to populate single stat graph. but this is possible if this new label can be use to match the template variable**

* Prometheus version:
Version  2.2.1

**Comment by brian-brazil** [comment]
You can do that on the first_name and last_name independently.

**Comment by xenthik** [comment]
> You can do that on the first_name and last_name independently.

No, When I am using it independently, it is giving me Cartesian product.

let me explain:

I am trying plot a single stat graph using repeat functionality based on "full name" name as template variable. So in this case there should be 3 panel will be created. 1. Jack daniels 2. Glen fiddich and 3. Royal stag.

but if use  first_name and last_name independently as template variable and supply these into like: 
sum(app:healthcheck:gauge{application="collectHealthies",first_name=~"$first_name",last_name=~"$las_name"}

it will give Error: Multiple Series Error" because 

for first_name ="Jack" the output becomes 

1. Jack daniels=10 2. Jack fiddich=null 3. Jack stag=null

for first_name ="Glen " the output becomes

4. Glen daniels=null 5. Glen fiddich=0 6. Glen stag=null

and for first_name ="Royal" the output becomes

7. Royaldaniels=null 8. Royal fiddich=null 9. Royal stag=3


 
I hope I have clarified, Why I want to match on combine label created through label_join.

**Comment by brian-brazil** [comment]
This sounds more like a Grafana usage question than a PromQL feature request. Keep in mind that template variables in Grafana don't have to be a single label value.

**Comment by xenthik** [comment]
I don't feel so, The above criteria is just any example.

it as basic expected functionality, In other RDBMS databases , if you project data by creating custom col, or by using inline query or group by operator there is provision either by where clause or having clause to filter the output.

What is benefit  of having label_join, if you can't use or manipulate it's outcome.

**Comment by brian-brazil** [comment]
You usually don't manipulate labels, you treat them as opaque strings that are used for matching. The canonical use case for label_join is when a hostname and port number are in separate labels.

**Comment by Moulick** [comment]
@brian-brazil  can you please gimme how I can use label_join when a hostname and port number are in separate label ?? Thanks

**Comment by terinjokes** [comment]
I've merged hostname and port using `label_join`, and now wish to filter on the newly created label. It seems like this is the canonical use case.

**Comment by brian-brazil** [comment]
node_ipvs_backend_connections_active{addr="198.51.100.5",port="80"} covers that, though relabelling is likely a better choice here.

**Comment by terinjokes** [comment]
Is there a function to split the string so I can add those label filters? How would relabeling work any different?

**Comment by tomklino** [comment]
Here is my usecase, for which I see no other way than to filter by the new label:

I am following data for kubernetes nodes. For some data sources there are labels that represent the nodes like so: `10.10.10.10:9100` and for others like so: `ip-10-10-10-10.ec2.internal`

Using lable_replace, I've done the following:
```
label_replace(node_cpu_seconds_total{mode="user"}, "node", "ip-$1-$2-$3-$4.ec2.internal", "instance", "([0-9]+).([0-9]+).([0-9]+).([0-9]+).*")
```

What the query above does, is create a new label node, for the data source that doesn't have it, based on the label instance, that represents the node in a `10.10.10.10:9100` fashion.

Now, in my grafana dashboard, I have a variable named node, in the form of "ip-10-10-10-10.ec2.internal", and I would like to filter by that variable for all data sources I'm graphing.

If I could use the above label_replace along with a filter, that would solve my issue. Something like so:

```
label_replace(node_cpu_seconds_total{mode="user"}, "node", "ip-$1-$2-$3-$4.ec2.internal", "instance", "([0-9]+).([0-9]+).([0-9]+).([0-9]+).*") {node="$node"}
```

**Comment by brian-brazil** [comment]
We've looked at this as part of our bug scrub, and adding this doesn't make sense overall. If you really need it it may be possible via sophisticated use of label_replace and label matching.

**Comment by blackwood821** [comment]
@xenthik this is exactly what I'm looking for as well. Did you ever figure out a workaround?

**Comment by bhiravabhatla** [comment]
Any traction on this, we are also having a similar usecase

**Comment by roidelapluie** [comment]
Thank you for taking the time to explain your usecase, @grandich . Prometheus provides a better way to deal with your issue than the blog post you have linked:
https://prometheus.io/blog/2021/02/18/introducing-the-@-modifier/

```
rate(process_cpu_seconds_total[5m]) and topk(5,rate(process_cpu_seconds_total[5m] @ end() )) 
```

See in action: https://prometheus.demo.do.prometheus.io/graph?g0.expr=rate(process_cpu_seconds_total%5B5m%5D)%20and%20topk(5%2Crate(process_cpu_seconds_total%5B5m%5D%20%40%20end()%20))%20&g0.tab=0&g0.stacked=0&g0.range_input=1h

**Comment by grandich** [comment]
Thanks @roidelapluie 

The conceptual misstep for a PromQL newbie like me, which made me stumble upon this issue is:

Can a function output be filtered with an instant vector selector? i.e.

   <function>(){<selector>} 

As in https://github.com/prometheus/prometheus/issues/5097#issuecomment-554097299, I was also assuming that every intermediate result that "has labels" was "filterable" through an instant vector selector. It's not clear to me in the documentation that these selectors apply only to "metrics"

**Comment by grandich** [comment]
@roidelapluie regarding the top N query, in cases of high cardinality, the approach of Grafana templating is more performant. The regex match is better in that case than the "and", and avoids "too many samples into memory in query execution".

**Comment by MartinEmrich** [comment]
I have a similar request for this. My use case: Find all machines with "too old" kernels.

```` 
    label_replace(node_uname_info{job="node-exporter-autodiscovery"}, "kernelversion", "$1", "release", "[0-9.]+-([0-9]+)..+")
````
This transforms the (CentOS 7) kernel release string reported by node_exporter from 3.10.0-957.21.3.el7.x86_64 to just 957.

I then attempted to filter for 

````
label_replace(node_uname_info{job="node-exporter-autodiscovery"}, "kernelversion", "$1", "release", "[0-9.]+-([0-9]+)..+"){kernelversion < 1127}
````

for an alert rule to quickly identify hosts with "too old" running kernels.

Note that a grafana-based approach would not help, as I primarily want it in an alert `expr:`

(A real "bonus" or an alternative for numeric label values would be a function that returns an specified label's value as the result value instead of the original metric value instead of "1" returned by node_uname_info)

**Comment by justinTM** [comment]
over two years :/ any status update on the development for this? so much more has been built in less time; this one's a no-brainer.

@beorn7 @brancz @bwplotka @codesome @csmarchbanks @cstyan @dgl

**Comment by RichardoC** [comment]
This feature would be very helpful. Here's a workaround I've been using

Example source metric

`kube_deployment_status_condition{app="kube-state-metrics", condition="Available",  kubernetes_namespace="important", status="false"}
`

What I expected to work
`label_join(kube_deployment_status_condition{kubernetes_namespace="important"}, "conditionstatus", "-", "condition", "status" ) conditionstatus != "Progressing-true" `

Instead I had to do
`(kube_deployment_status_condition{kubernetes_namespace="important"} unless kube_deployment_status_condition{kubernetes_namespace="important" status="true", condition="Progressing"} )`

Hope this helps someone

**Comment by RichardoC** [comment]
This feature would be very helpful. Here's a workaround I've been using

Example source metric

`kube_deployment_status_condition{app="kube-state-metrics", condition="Available",  kubernetes_namespace="important", status="false"}
`

What I expected to work
`label_join(kube_deployment_status_condition{kubernetes_namespace="important"}, "conditionstatus", "-", "condition", "status" ) conditionstatus != "Progressing-true" `

Instead I had to do
`(kube_deployment_status_condition{kubernetes_namespace="important"} unless kube_deployment_status_condition{kubernetes_namespace="important", status="true", condition="Progressing"} )`

Hope this helps someone

**Comment by piotrkowalczuk** [comment]
I have to admit that lack of this functionality is a bit troublesome. I'm trying to keep labels fairly normalized, therefore I'm having two separate labels `grpc_service` and `grpc_method`. Both create `grpc_endpoint` that looks like `{grpc_service}/{grpc_method}`. In my usecase I would like to create a templated Grafana dashboard where I dynamically generate row for each `grpc_endpoint`. I believe I have two options here:

- create two hidden variables `service` and `method` by filtering query result by `grpc_endpoint` and use those precomputed values for filtering
- use `labels_join` in each and every query and filter by original `endpoint` variable

Since I'm not able to filter out result of `labels_join` I'm efffectively forced to change collector definition so it emits `grpc_endpoint` label as well. As much as it can be done for privately owned instrumentation it is problematic when it comes to third party libraries/exporters.

**Comment by PrestonTaylor** [comment]
I have queries that are hundreds of lines with my filters pre-label_replace in dozens of places, putting a gigantic regex a dozen times in my query makes absolutely no sense. Yes, what I want is throwing away work that's been done already by filtering out after the fact but I'd rather my CPU do the work than me. Assuming one applies the same values to good code as they do queries this makes the query difficult to maintain.

I don't see how this type of request is any different than merely having a mechanism that creates new labels at all, that can be done by consuming services. Some things are for ease of use and that's fine. Perhaps abstraction of the curly brace filter mechanism is needed to give it a more position-agnostic use.

@brian-brazil Please reconsider.

**Comment by dingus9** [comment]
I'm currently working with a monitoring system that has a predefined hist IP formatted (changeably as 10.x.x.x) not the  My current query is like this
```
label_replace({__name__=~'kube_node_status_condition'}, "node_ip", "$1.$2.$3.$4", "node", "ip-([0-9]+)-([0-9]+)-([0-9]+)-([0-9]+).+")==1
```
yielding node_ip: 10.x.x.x in the format of my monitoring system... I have limited result set processing capabilities(don't have access in the post processing to the host ip value) in the monitoring system. I would be really helpful to be able to do a query like this to further pair down the results before the system.

Keep in mind 

```
label_replace({__name__=~'kube_node_status_condition'}, "node_ip", "$1.$2.$3.$4", "node", "ip-([0-9]+)-([0-9]+)-([0-9]+)-([0-9]+).+")==1 {node_ip="10.0.1.2" }
```

**Comment by btlk** [comment]
> We've looked at this as part of our bug scrub, and adding this doesn't make sense overall. If you really need it it may be possible via sophisticated use of label_replace and label matching.

As others here noted, this is valid usecase which will help many people (me included). Could you please reconsider
