### ISSUE TITLE
Token Authentication -- Manipulate Header

### ISSUE THREAD

**Issue by npaschos** [prometheus/prometheus#5107]
## Proposal

I am using **django-rest framework** along with **django-prometheus** in order to export metrics from my app. I have exposed an endopoint and created a Token in order to authenticate the prometheus server. The token works as expected when using _Postman_ or _curl_, but the issue occurs when I try to include it in the `prometheus.yaml` config. The header that _django-rest_ requires in order to authenticate with a token is of the following format:

`Authorization: 'Token XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'`

but the one created by Prometheus is:

`Authorization: 'Bearer XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'`

Note that the former has the _Token_ keyword included, whereas the latter one the _Bearer_ keyword.

As expected, the authentication fails. I tried changing the header but I could not find any way in the documentation, so I assume that it is not possible.

Am I missing a config parameter? If not, I propose that this change is implemented.

---

**Note:** this is my first issue/proposal, I tried following the guidelines. Let me know if anything else is required.

**Comment by brian-brazil** [comment]
We only support standard authentication mechanisms, which your system is not. I'd suggest switching your authentication to use Bearer tokens.

**Comment by roidelapluie** [comment]
From the Django Rest Framework docs: https://www.django-rest-framework.org/api-guide/authentication/

> Note: If you want to use a different keyword in the header, such as Bearer, simply subclass TokenAuthentication and set the keyword class variable.

It looks like you could work at the DRF level instead.

**Comment by roidelapluie** [comment]
This has been implemented in #8512.

```
authorization:
  credentials: mysecrettoken
  type: Token
```
