### ISSUE TITLE
remote_read from prometheus1.8.2 doesn't work

### ISSUE THREAD

**Issue by zerthimon** [prometheus/prometheus#5129]
## Bug Report
**What did you do?**
I'm in the process of migration from 1.8.2 to 2.6.1

Old container 1.8.2:
started with `--web.listen-address=:9090`

```
global:
  external_labels:
    monitor: prometheus-old
```

New container 2.6.1:
```
remote_read:
  - url: http://prometheus-server-old:9090/api/v1/read
```

Both docker containers are on the same host, the new container links the old one on the name `prometheus-server-old`

**What did you expect to see?**
Metrics from the old container.

**What did you see instead? Under which circumstances?**
Only metrics from the the new container.
I'm able to get metrics inside the new container from the old container using `curl http://prometheus-server-old:9090/api/v1/query?query= ...`

**Comment by cstyan** [comment]
Can you show us logs from the 2.6.1 server? When you say you only see metrics from the 2.6.1 container, you mean when you run a query? To be clear, remote read would run queries against your other container, it doesn't mean the 2.6.1 instance is actively reading the data from your old prometheus instance and storing it locally.

**Comment by zerthimon** [comment]
@cstyan yeah I'm querying 2.6.1 for metrics that exist on 1.8.2 and get any.
I'm using the same queries (grafana dashboards) i used with 1.8.2. The backend is now 2.6.1 with remote read pointing to 1.8.2 container.
I don't see any logs relevant to remote reads, just the TSDB operations.

**Comment by roidelapluie** [comment]
Did you enable read_recent: true ?

**Comment by RichiH** [comment]
We are doing a bug scrub; we think this issue can be closed. If you have new data/can reproduce, please let us know.
