### ISSUE TITLE
Add function for standard deviation

### ISSUE THREAD

**Issue by grobie** [prometheus/prometheus#515]
> In statistics, the standard deviation (SD) (represented by the Greek letter sigma, σ) is a measure that is used to quantify the amount of variation or dispersion of a set of data values.
-- http://en.wikipedia.org/wiki/Standard_deviation

Graphite calls it `stdev`. Influxdb `stddev`.

**Comment by brian-brazil** [comment]
I'd go for `stddev`, and add `stdvar` while we're at it.

Should we have over_time versions too?

**Comment by grobie** [comment]
Solved with #641.

**Comment by beorn7** [comment]
So no `over_time` version?

**Comment by brian-brazil** [comment]
I'd say wait for a use case to appear.
