### ISSUE TITLE
Reporting Security Issues

### ISSUE THREAD

**Issue by Dor-Tumarkin** [prometheus/prometheus#5156]
Hi,
There is currently no e-mail address to send security related issues to.
Can you please provide a means for disclosing such issues?
Thanks.

**Comment by brian-brazil** [comment]
Per our security doc, you can send them to people in https://github.com/prometheus/prometheus/blob/master/MAINTAINERS.md

**Comment by brian-brazil** [comment]
Fixed by #5163
