### ISSUE TITLE
min and max as binary operators

### ISSUE THREAD

**Issue by xinau** [prometheus/prometheus#5177]
## Proposal
Adding min and max as binary operators to promql.

**Use case. Why is this important?**
I've got two different timeseries and want to join them by using the maximum value of the two.
For example
```
timeseries_a{foo="bar"} 4
timeseries_b{foo="bar"} 7
```
I would like to do the following promql 
```
timeseries_a bin_op_max timeseries_b
```
instead off doing something like this
https://www.maa.org/programs/faculty-and-departments/classroom-capsules-and-notes/the-maximum-and-minimum-of-two-numbers-using-the-quadratic-formula
```
# for maximum
(timeseries_a + timeseries_b + abs(timeseries_a - timeseries_b)) / 2
(vector(4) + vector(7) + abs(vector(4) - vector(7))) / 2
# for minimum
(timeseries_a + timeseries_b - abs(timeseries_a - timeseries_b)) / 2
(vector(4) + vector(7) - abs(vector(4) - vector(7))) / 2
```
, as this can get difficult with (`on, group_left ...`)

**Comment by brian-brazil** [comment]
You can do `a > b or b`

**Comment by xinau** [comment]
Thank you @brian-brazil.
