### ISSUE TITLE
Add flag/config option to set root directory for UI

### ISSUE THREAD

**Issue by yorik** [prometheus/prometheus#519]
Right now it's impossible to hide prometheus under nginx in some directory because all the links and JS are referenced to /... It would be very good if it would be possible to add some common directory via config or flag so it would be accessible via `http://<host>/<dir>/`

**Comment by beorn7** [comment]
@juliusv You are more familiar with the web part. Is that doable?

**Comment by juliusv** [comment]
@yorik Would your suggestion simply require making paths relative in the frontend (in links, AJAX calls, etc.), or would you actually require the Prometheus server to respond on `/mycustomroot/api/query_range`, etc.?

**Comment by yorik** [comment]
Any way would work for me, but probably adding /mycustomroot will be easier
to implement.
Thank you!

On 11 February 2015 at 13:07, juliusv <notifications@github.com> wrote:

> @yorik <https://github.com/yorik> Would your suggestion simply require
> making paths relative in the frontend (in links, AJAX calls, etc.), or
> would you actually require the Prometheus server to respond on
> /mycustomroot/api/query_range, etc.?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/prometheus/prometheus/issues/519#issuecomment-73871330>
> .
>



-- 
With best regards,
Yury Akudovich

**Comment by juliusv** [comment]
@yorik See https://github.com/prometheus/prometheus/pull/528 - this works for me behind an nginx with a custom root. The one caveat for you would be that the Prometheus itself would have no idea that it's behind a proxy, so when it sends alerts to alertmanager (if you're using that at all), it would send its normal local URL to alertmanager for any rule introspection backlinks. That means that in Alertmanager, the "Generated By" column would not contain the URL through your proxy, but the one that Prometheus thinks it has. This could be made configurable in the future too, I guess...

**Comment by yorik** [comment]
@juliusv, thank you so much! It works for me now. I haven't try
alertmanager yet but it's not the problem for now.

On 14 February 2015 at 18:00, juliusv <notifications@github.com> wrote:

> @yorik <https://github.com/yorik> See #528
> <https://github.com/prometheus/prometheus/pull/528> - this works for me
> behind an nginx with a custom root. The one caveat for you would be that
> the Prometheus itself would have no idea that it's behind a proxy, so when
> it sends alerts to alertmanager (if you're using that at all), it would
> send its normal local URL to alertmanager for any rule introspection
> backlinks. That means that in Alertmanager, the "Generated By" column would
> not contain the URL through your proxy, but the one that Prometheus thinks
> it has. This could be made configurable in the future too, I guess...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/prometheus/prometheus/issues/519#issuecomment-74382726>
> .
>



-- 
With best regards,
Yury Akudovich

**Comment by juliusv** [comment]
@yorik Cool! As you might have read in https://github.com/prometheus/prometheus/pull/528, this can't be immediately merged due to the console paths problem, so I'll let it sit here for a while (you could rebase it ontop of newer masters at times, if desired) until someone decides to fix the remaining problems.

**Comment by brian-brazil** [comment]
This is resolved with #614 and `-web.path-prefix`
