### ISSUE TITLE
Test_readCheckpointis is flaky

### ISSUE THREAD

**Issue by krasi-georgiev** [prometheus/prometheus#5217]
https://travis-ci.org/prometheus/prometheus/builds/493119053?utm_source=github_status&utm_medium=notification

it happened few times locally as well.

cc @cstyan . @tomwilkie

**Comment by cstyan** [comment]
@krasi-georgiev yep, some of the tests need longer timeouts. We're fixing that in #5214 but I can split that out into it's own PR that we could merge right away.

**Comment by krasi-georgiev** [comment]
Thanks , I updated the comment that it closes this issues.

**Comment by simonpasquier** [comment]
I think it should be fixed sooner than later as it blocks basically all PRs right now.

**Comment by tomwilkie** [comment]
@simonpasquier we're on it.  Sorry about that.

**Comment by simonpasquier** [comment]
I didn't see your PR so I had worked on https://github.com/prometheus/prometheus/pull/5224
