### ISSUE TITLE
Load balance / run multiple instances?

### ISSUE THREAD

**Issue by sammcj** [prometheus/prometheus#522]
Since the DB can't handle two connections at once - how can you run multiple instances of the application with access to the same data (for reliability / failover)?

**Comment by brian-brazil** [comment]
See http://prometheus.io/docs/introduction/faq/#can-prometheus-be-made-highly-available?

**Comment by sammcj** [comment]
Oh wow that simple! I didn't realise! Sorry for wasting your time.

**Comment by brian-brazil** [comment]
No problem, happy to help.

**Comment by hermII** [comment]
I'm running multiple instances of the snmp_exporter and I want to configure prometheus.yml to allow prometheus to run and recognize both instances of snmp_exporters running on different ports. Can you give me a sample prometheus.yml file that would work in this scenario...the config that I'm using causes prometheus to crash upon start up with this message: ERRO[0000] Error loading config: couldn't load configuration (-config.file=Prometheus.yml): yaml: line 46 did not find expected key source=main.go:149

**Comment by brian-brazil** [comment]
Please don't comment on old closed issues, this question is better suited to https://groups.google.com/forum/#!aboutgroup/prometheus-users
