### ISSUE TITLE
Make promtool better for CI with syntax-only config check

### ISSUE THREAD

**Issue by glightfoot** [prometheus/prometheus#5222]
## Proposal
**Use case. Why is this important?**

*We validate our rules with promtool in CI before deploying, it would be nice to be able to check for config file syntax validity without having to deploy all secrets, certs, etc.*

## Bug Report
**What did you do?**
```promtool check config prometheus.yaml```

**What did you expect to see?**
```
./promtool check config --syntax-only prometheus.yaml                                                                                                                                                                                
Checking prometheus.yaml
  SUCCESS: prometheus.yaml is valid prometheus config file syntax
  SUCCESS: 0 rule files found
```
**What did you see instead? Under which circumstances?**
```
promtool check config prometheus.yaml
Checking prometheus.yaml
  FAILED: error checking bearer token file "/var/run/secrets/kubernetes.io/serviceaccount/token": stat /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory
```

**Environment**
CI (explicitly does not have the token and certs present in the deployment)

* System information:

	Linux 3.10.0-514.26.2.el7.x86_64 x86_64

* Prometheus version:

	2.7.1

**Comment by roidelapluie** [comment]
I do not agree with this. Those files are part of the configuration and I want promtool to check that it can actually read them.

**Comment by glightfoot** [comment]
@roidelapluie - this will not change that behavior. I agree that that is an important check to have available. This will only add the ability to do the tests without those files as a new feature.

`promtool check config prometheus.yaml` - still works as it does now
`promtool check config --syntax-only prometheus.yaml` - only checks syntax

**Comment by geekodour** [comment]
@codesome can I add this with https://github.com/prometheus/prometheus/issues/21 ?

**Comment by glightfoot** [comment]
Is there any way we can move this along? I had syntax bug get checked in that we could have prevented with this...

**Comment by andbuitra** [comment]
I just had this when doing CI on GitLab but it was related to the alertmanager rules using an absolute path on the monitoring server that throws off promtool on the GitLab server. Syntax only checking would be greatly appreciated!

**Comment by glightfoot** [comment]
I opened a new PR (#6488 ) that mirrors what I built locally to fix this. On the last PR, there was concern that not all files were being checked, so if that is still a problem, then I am more than happy to open another issue and fix there.

**Comment by dt-rush** [comment]
Until something is merged to handle this, `promtool check config` is hardly usable unless you only run it in the same environment you deploy to. The tool itself describes `check config` as:

> Check if the config files are valid or not.

Emphasis on the files, not any API endpoint integrations dependent on envrionment, etc. If we are going to go that direction (and the naming would be misleading), then we should at least provide the `--synstax-only` option.

**Comment by dacox** [comment]
> I do not agree with this. Those files are part of the configuration and I want promtool to check that it can actually read them.

I'm having trouble understanding how the current behaviour is even useful. We don't run `promtool check config` in production, we run it locally and on CI. I'm certainly not putting those files in CI

**Comment by roidelapluie** [comment]
Hello, yes, I understand the use case now. We would like to have this in Prometheus.

**Comment by psalaberria002** [comment]
As an ugly workaround we are running `sed -i.bak '/bearer_token_file/d' config.yaml` in CI. It works.

**Comment by zzehring** [comment]
We're looking for this syntax-only type config check as well for our CI pipeline. I'd like to pick up the work done by @glightfoot, however there looks to be a couple options for implementing this:
- add a `--syntax-only` flag to the existing `promtool check config` command. this has been implemented in #5223
- add another `syntax` check entirely (e.g. `promtool check syntax`). this has been implemented in #6488

I'd like to get input from the promtool maintainers (@dgl, @JessicaGreben) for their preference on how to implement this functionality. 

Seeing as @glightfoot's branches are quite old, I can submit a fresh PR with the chosen implementation.

**Comment by dgl** [comment]
@zzehring thanks for offering! `--syntax-only` gets my vote, I think the larger issues with that before are now addressed, except the one mentioned in https://github.com/prometheus/prometheus/pull/6488#issuecomment-679176356.

For example currently in config/config.go there are calls to `c.HTTPClientConfig.Validate` within UnmarshalYAML. Some refactoring may be needed to make this behave correctly with `bearer_token_file` as well as SD configs.

**Comment by zzehring** [comment]
Thanks for the input! I'll start work on the feature.

**Comment by JessicaGreben** [comment]
@zzehring Thanks for helping with this! I second @dgl vote.

**Comment by glightfoot** [comment]
Thanks for getting this done @zzehring !!!
