### ISSUE TITLE
Support series selector for label/names and label/:name/values API

### ISSUE THREAD

**Issue by jobrs** [prometheus/prometheus#5248]
## Proposal

Add support for series selectors (i.e. match[]) to the `label/names` resp. `label/:name/values` APIs, so that the list of label names and values can be constrained to a subset of series.

This is useful to build
* Multi-tenancy using on labels for separating tenants (similar to https://github.com/prometheus/prometheus/issues/1813#issuecomment-232571410_): To constrain a API call to a tenant you need to add a filter like `tenant=xyz`.
* Sophisticated UIs supporting multiple filter conditions:  To narrow down possible values iteratively (see also https://github.com/prometheus/prometheus/issues/407)

You could use the `/series` API for that purpose but that's quite a complex operation ([example](https://github.com/sapcc/maia/blob/597b0b655ea4aa27e7345a812168a9c44bfd863f/pkg/api/v1api.go#L112)). I am hoping that this could be implemented in a much more efficient way on a lower layer.

**Comment by codesome** [comment]
This discussion had come up during the implementation of `/label/names`, but there was no efficient way to do it as of now. The best way now is equivalent to querying the tsdb for series and filter the required information - which is inefficient.

**Comment by jobrs** [comment]
@codesome Agreed, see my last sentence. Still I would find the API addition useful, since future versions of the TSDB might (wishful thinking) allow for an optimised implementation and the addition would be consistent with the rest of the API.

**Comment by codesome** [comment]
Quoting https://github.com/prometheus/tsdb/issues/530#issuecomment-465959964 from @brian-brazil 
> That's the only way to do it and the most efficient, I don't see the need to extend the API.

**Comment by krasi-georgiev** [comment]
@jobrs is there anything else we need to add the the issue? 
Otherwise I agree that we should extend the API only when we have a more efficient way that the current implementation.

**Comment by jobrs** [comment]
@krasi-georgiev no, these are the points I wanted to raise

**Comment by krasi-georgiev** [comment]
In that case I hope you don't mind closing the issue and can revisit at a later point when we can have a better answer for that.

**Comment by jobrs** [comment]
closing this one, since the requested API addition is not needed from functional/performance perspective
