### ISSUE TITLE
Targets All/Unhealthy buttons to be used as a refresh button

### ISSUE THREAD

**Issue by pbhudiaBAE** [prometheus/prometheus#5259]
## Proposal
To have the All and Unhealthy buttons on the Targets page act as a refresh button. I was looking at the #4599 issue that recently closed and thought that this could be a nice little feature. I have coded a fix that adds this feature, if this feature is desirable I can make a pull request.

**Comment by brian-brazil** [comment]
That could be unexpected for users, as for example if I've a snapshot of a bad state I don't want it disappearing under me.

**Comment by pbhudiaBAE** [comment]
Understood, that's good point. I'll go ahead and close the issue.
