### ISSUE TITLE
Really bad (or no) instructions to install

### ISSUE THREAD

**Issue by ozn0417** [prometheus/prometheus#5261]
Can you guys do a better job of having steps to install Prometheus.  I think the instructions are pretty bad off your main website.  I see a tar.gz file, what do I with it?

## Proposal
**Use case. Why is this important?**

*“Nice to have” is not a good use case. :)*

## Bug Report
**What did you do?**

**What did you expect to see?**

**What did you see instead? Under which circumstances?**

**Environment**

* System information:

	insert output of `uname -srm` here

* Prometheus version:

	insert output of `prometheus --version` here

* Alertmanager version:

	insert output of `alertmanager --version` here (if relevant to the issue)

* Prometheus configuration file:
```
insert configuration here
```

* Alertmanager configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```

**Comment by ozn0417** [comment]
Found something here: https://prometheus.io/docs/introduction/first_steps/

**Comment by juliusv** [comment]
There's also https://prometheus.io/docs/prometheus/latest/getting_started/ and https://prometheus.io/docs/prometheus/latest/installation/.
