### ISSUE TITLE
curl: (52) Empty reply from server when I curl prometheus

### ISSUE THREAD

**Issue by szediktam** [prometheus/prometheus#5262]
## Proposal
**Use case. **

## Bug Report
**What did you do?**
I curl prometheus with a error sometimes.
# curl http://x.x.x.x:9090/api/v1/query?query=node_cpu
curl: (52) Empty reply from server

sometime it is ok.

**What did you expect to see?**
normal output of metric

**What did you see instead? Under which circumstances?**
# curl http://x.x.x.x:9090/api/v1/query?query=node_cpu
curl: (52) Empty reply from server

**Environment**

* System information:

Linux node-1 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

* Prometheus version:

prometheus, version 2.2.1 (branch: HEAD, revision: bc6058c81272a8d938c05e75607371284236aadc)
  build user:       root@149e5b3f0829
  build date:       20180314-14:15:45
  go version:       go1.10

**Comment by szediktam** [comment]
I also use prometheus/client_golang to get query by QueryRange in client_golang/api/v1/api.
It still a error:
`http://x.x.x.x:9090/api/v1/query_range?end=2019-02-22T11%3A51%3A09Z&query=node_cpu&start=2019-02-22T11%3A43%3A09Z&step=120.000: EOF`

**Comment by simonpasquier** [comment]
Check with `wireshark` or `tcpdump` but it looks like the connection gets dropped at the TCP level either from the client or from the server. But it doesn't seem to be a problem specific to Prometheus.

I'm closing it for now. If you have further questions, please use our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search.
