### ISSUE TITLE
Upgrade github.com/miekg/dns

### ISSUE THREAD

**Issue by sylr** [prometheus/prometheus#5263]
Latest version of `github.com/miekg/dns` does not have the ErrTruncated anymore, see: https://github.com/miekg/dns/pull/815

The commit message says:

```
Any program using ErrTruncated will fail to compile when they update to
this version: this is by design: you're doing it wrong. For checking if
a message was truncated you should checked the msg.Truncated boolean;
assuming the unpack didn't fail.
```

Thanos use a recent version of `github.com/miekg/dns` and it is not an issue now but it might become (for Thanos) if https://github.com/prometheus/prometheus/pull/5009 makes it to master as the dependency tree of prometheus within thanos will become bigger as Thanos imports `github.com/prometheus/rules` (indirectly I guess) which will import `github.com/prometheus/config` which itself imports a lot of libs needed for discovery like `github.com/miekg/dns`.

cc @bwplotka

**Comment by simonpasquier** [comment]
Closed by #5020
