### ISSUE TITLE
Upgraded from 2.0 to 2.7

### ISSUE THREAD

**Issue by hariravella** [prometheus/prometheus#5268]
## Bug Report
**What did you do?**
Upgraded from 2.0 to 2.7
**What did you expect to see?**
yml configuration file should be compatible with 2.7
**What did you see instead? Under which circumstances?**

./promtool check config prometheus.yml
Checking prometheus.yml
  FAILED: parsing YAML file prometheus.yml: yaml: unmarshal errors:
  line 48: field collect[] not found in type config.plain

**Environment**

* System information:

	Linux 3.10.0-957.1.3.el7.x86_64 x86_64

* Prometheus version:

	iprometheus, version 2.7.1 (branch: HEAD, revision: 62e591f928ddf6b3468308b7ac1de1c63aa7fcf3)
  build user:       root@f9f82868fc43
  build date:       20190131-11:16:59
  go version:       go1.11.5

* Alertmanager version:

	alertmanager, version 0.16.1 (branch: HEAD, revision: 571caec278be1f0dbadfdf5effd0bbea16562cfc)
  build user:       root@3000aa3a06c5
  build date:       20190131-15:05:40
  go version:       go1.11.5

* Prometheus configuration file:

  - job_name: ravella test
    params:
    collect[]:
        - cpu
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
       - targets: ['ravella_test:9100']

* Alertmanager configuration file:

NA

* Logs:
NA

**Comment by simonpasquier** [comment]
The YAML data isn't valid:

```yaml
    params:
      collect:
      - cpu
```

I'm closing it for now. If you have further questions, please use our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search.
