### ISSUE TITLE
Example Kubernetes port annotation does not use port number

### ISSUE THREAD

**Issue by bboreham** [prometheus/prometheus#5281]
In [this line](https://github.com/prometheus/prometheus/pull/4131/files#diff-416ffe38e4360ad5f27d8a034963c260R159) which is given as an example of annotation usage,

    - source_labels: [__address__, __meta_kubernetes_service_annotation_example_io_scrape_port]
      action: replace
      regex: ([^:]+)(?::\d+)?;(\d+)
      replacement: $1:$2
      target_label: __address__

I am puzzled that the replacement is `$1:$2`; I expect it to be `$1:$3` so that the port number specified in the annotation is used.

For instance I see a similar line matching my expectation [here](https://github.com/grafana/jsonnet-libs/blob/5d7e5391010c768a6ddd39163c35662f379e20ca/prometheus-ksonnet/lib/prometheus-config.libsonnet#L97).

**Comment by simonpasquier** [comment]
This is because the second group (`(?::\d+)`) isn't captured (eg it starts with `(?:`).

**Comment by bboreham** [comment]
Ooh.   TIL.
