### ISSUE TITLE
Allow setting a time offset for individual metrics in a query

### ISSUE THREAD

**Issue by juliusv** [prometheus/prometheus#529]
This would help use cases like https://github.com/prometheus/promdash/issues/201.

Suggestions so far:

* extending existing range syntax: `mymetric[range,offset]`, where `range` is optional. Downside: would be confusing if `[]` could return both instant vectors and range vectors.

* adding a modifier keyword: `mymetric offset 1h`.

* adding a special operator that can only take literals: `offset(mymetric, 1h)`

* ...maybe an even better solution that combines the benefits of the above with fewer drawbacks.

**Comment by juliusv** [comment]
(potentially we could also decide that we don't want to have this as a server-side feature at all and instead leave it up to the presentation layer to do multiple queries for different ranges - this depends on whether we have many use cases for actually combining different offsets in the same query)

**Comment by brian-brazil** [comment]
This is useful for alerts when comparing against the past, so it needs to be in the rule language.

I think the modifier is the cleanest, the others introduce semantic special cases.
