### ISSUE TITLE
High CPU and memory in Prometheus 2.3.2

### ISSUE THREAD

**Issue by anumercian** [prometheus/prometheus#5301]
## Proposal
**Use case. Why is this important?**
Facing high CPU and memory usage of Prometheus at Scale. 

## Bug Report
**What did you do?**
Created 126-130 time series and ran it for 2-3 days. 

**What did you expect to see?**
Prometheus running at normal CPU and memory. 

**What did you see instead? Under which circumstances?**
Prometheus is having CPU spikes every 1 minute for about 5sec to 100%. 
![image](https://user-images.githubusercontent.com/1896420/53755426-60ebce00-3e6b-11e9-9309-a3b247aa46b7.png)

On an average it seems like CPU is having high CPU throughout:
![image](https://user-images.githubusercontent.com/1896420/53755507-837de700-3e6b-11e9-8bbe-9eaeb6902ebe.png)

The memory via pprof is about 120Mb but via OS (/proc) its about 450Mb

**Environment**

* System information:

	insert output of `uname -srm` here

* Prometheus version:

	insert output of `prometheus --version` here
Prometheus 2.3.2

* Alertmanager version:

	insert output of `alertmanager --version` here (if relevant to the issue)

* Prometheus configuration file:
```
insert configuration here
```
global:
  scrape_interval:     15s
  evaluation_interval: 5s
  external_labels:
      monitor: 'codelab-monitor'

rule_files:
  - '/var/run/prometheus/alerts/*.yml'

scrape_configs:
  - job_name: 'prometheus'

    scrape_interval: 5s

    static_configs:
      - targets: ['127.0.0.1:9091']

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - 127.0.0.1:9091

* Alertmanager configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```

**Comment by anumercian** [comment]
file:///users/mercian/crCPU/cpu3.svg

file:///users/mercian/crCPU/cpu2.svg

**Comment by anumercian** [comment]
![image](https://user-images.githubusercontent.com/1896420/53757676-166d5000-3e71-11e9-9229-d7680a59202c.png)


![image](https://user-images.githubusercontent.com/1896420/53757696-22591200-3e71-11e9-9037-f1403ffca145.png)

**Comment by SuperQ** [comment]
I would recommend upgrading to a more current release. There has been a lot of performance and bug fixes since 2.3.2.

I'm not sure where you're getting this data, but you might want to look at `rate(process_cpu_seconds_total[1m])`.

Also, please include the queries used for included graphs. Without the query we have no idea what the graphs mean.

**Comment by anumercian** [comment]
Query: rate(process_cpu_seconds_total[1m])


![image](https://user-images.githubusercontent.com/1896420/53772334-ec308800-3e9a-11e9-82ac-ba711a79903a.png)

![image](https://user-images.githubusercontent.com/1896420/53772345-f2beff80-3e9a-11e9-86ec-4c85c285b234.png)

**Comment by SuperQ** [comment]
Based on the graph, it looks like whatever is producing the other metric data is reporting false information.

**Comment by anumercian** [comment]
@SuperQ What do you mean by other metric data? The difference between OS memory of 450MB and prom heap pprof of 120Mb?

**Comment by SuperQ** [comment]
No, the CPU spikes seem non-existent in the Prometheus direct instrumentation. I'm not sure where `Daemon_resource_utilization` comes from, but it appears inaccurate.

**Comment by anumercian** [comment]
The daemon_resource_utilization is similar to the output of "top" on Linux shell, done for each daemon running and I am seeing Prometheus spiking to above 100% every 1-3minutes.

**Comment by SuperQ** [comment]
Prometheus CPU depends on what queries are being performed. The average CPU use seems to be about 10% of 1 core.

I don't see an actual issue here, other than "it's using resources".

**Comment by SuperQ** [comment]
As for the memory issue, can you please share the results of the query for `process_resident_memory_bytes`? This is the correct metric for memory use.

**Comment by anumercian** [comment]
Okay, could the CPU spike that we see in "top" be the Go Garbage collector?

**Comment by anumercian** [comment]
Will post the result of query "process_resident_memory_bytes" shortly

**Comment by anumercian** [comment]
This is Heap Profile

![image](https://user-images.githubusercontent.com/1896420/53829788-c86e5000-3f35-11e9-98cb-43ed8240c18c.png)

**Comment by simonpasquier** [comment]
Closing since the discussion also happens on the mailing list ([here](https://groups.google.com/d/msg/prometheus-users/KuLfGUlJG1M/wUqnKPevCAAJ)) and there's no evidence of a problem.
