### ISSUE TITLE
example_write_adapter "go build" fail, anyone hit the issue?

### ISSUE THREAD

**Issue by kaihua1987** [prometheus/prometheus#5306]
[root@kaihua-master example_write_adapter]# go build
go: finding github.com/gogo/protobuf v1.1.1
go: finding github.com/matttproud/golang_protobuf_extensions v1.0.1
go: finding github.com/dgryski/go-sip13 v0.0.0-20181026042036-e10d5fee7954
go: k8s.io/apimachinery@v0.0.0-20181127025237-2b1284ed4c93: unrecognized import path "k8s.io/apimachinery" (https fetch: Get https://k8s.io/apimachinery?go-get=1: proxyconnect tcp: EOF)
go: k8s.io/client-go@v2.0.0-alpha.0.0.20181121191925-a47917edff34+incompatible: unrecognized import path "k8s.io/client-go" (https fetch: Get https://k8s.io/client-go?go-get=1: proxyconnect tcp: EOF)
go: labix.org/v2/mgo@v0.0.0-20140701140051-000000000287: unrecognized import path "labix.org/v2/mgo" (https fetch: Get https://labix.org/v2/mgo?go-get=1: proxyconnect tcp: EOF)
go: k8s.io/kube-openapi@v0.0.0-20180629012420-d83b052f768a: unrecognized import path "k8s.io/kube-openapi" (https fetch: Get https://k8s.io/kube-openapi?go-get=1: proxyconnect tcp: EOF)
go: k8s.io/api@v0.0.0-20181213150558-05914d821849: unrecognized import path "k8s.io/api" (https fetch: Get https://k8s.io/api?go-get=1: proxyconnect tcp: EOF)
go: google.golang.org/genproto@v0.0.0-20180831171423-11092d34479b: unrecognized import path "google.golang.org/genproto" (https fetch: Get https://google.golang.org/genproto?go-get=1: proxyconnect tcp: EOF)
go: golang.org/x/sync@v0.0.0-20181108010431-42b317875d0f: unrecognized import path "golang.org/x/sync" (https fetch: Get https://golang.org/x/sync?go-get=1: proxyconnect tcp: EOF)
go: finding github.com/alecthomas/template v0.0.0-20160405071501-a0175ee3bccc
go: golang.org/x/time@v0.0.0-20170424234030-8be79e1e0910: unrecognized import path "golang.org/x/time" (https fetch: Get https://golang.org/x/time?go-get=1: proxyconnect tcp: EOF)
go: gopkg.in/yaml.v2@v2.2.1: unrecognized import path "gopkg.in/yaml.v2" (https fetch: Get https://gopkg.in/yaml.v2?go-get=1: proxyconnect tcp: EOF)
go: gopkg.in/fsnotify.v1@v1.4.7: unrecognized import path "gopkg.in/fsnotify.v1" (https fetch: Get https://gopkg.in/fsnotify.v1?go-get=1: proxyconnect tcp: EOF)
go: gopkg.in/inf.v0@v0.9.0: unrecognized import path "gopkg.in/inf.v0" (https fetch: Get https://gopkg.in/inf.v0?go-get=1: proxyconnect tcp: EOF)
go: sigs.k8s.io/yaml@v1.1.0: unrecognized import path "sigs.k8s.io/yaml" (https fetch: Get https://sigs.k8s.io/yaml?go-get=1: proxyconnect tcp: EOF)
go: finding github.com/go-logfmt/logfmt v0.3.0
go: launchpad.net/gocheck@v0.0.0-20140225173054-000000000087: bzr branch --use-existing-dir https://launchpad.net/gocheck . in /tmp/tmp.fZUO10aKAd/pkg/mod/cache/vcs/777eb00f2dda8f7e87f31562b0b620382271e62af69a4c10e3bbbf4ca80aee18: exec: "bzr": executable file not found in $PATH
go: finding github.com/golang/protobuf v1.2.0
go: finding github.com/oklog/ulid v1.3.1
go: finding github.com/prometheus/procfs v0.0.0-20181005140218-185b4288413d
go: golang.org/x/tools@v0.0.0-20181023010539-40a48ad93fbe: unrecognized import path "golang.org/x/tools" (https fetch: Get https://golang.org/x/tools?go-get=1: proxyconnect tcp: EOF)
go: golang.org/x/crypto@v0.0.0-20180621125126-a49355c7e3f8: unrecognized import path "golang.org/x/crypto" (https fetch: Get https://golang.org/x/crypto?go-get=1: proxyconnect tcp: EOF)
go: finding github.com/aws/aws-sdk-go v0.0.0-20180507225419-00862f899353
go: google.golang.org/grpc@v1.17.0: unrecognized import path "google.golang.org/grpc" (https fetch: Get https://google.golang.org/grpc?go-get=1: proxyconnect tcp: EOF)
go: contrib.go.opencensus.io/exporter/ocagent@v0.4.1: unrecognized import path "contrib.go.opencensus.io/exporter/ocagent" (https fetch: Get https://contrib.go.opencensus.io/exporter/ocagent?go-get=1: proxyconnect tcp: EOF)
go: golang.org/x/sys@v0.0.0-20181107165924-66b7b1311ac8: unrecognized import path "golang.org/x/sys" (https fetch: Get https://golang.org/x/sys?go-get=1: proxyconnect tcp: EOF)
go: gopkg.in/fsnotify/fsnotify.v1@v1.3.0: unrecognized import path "gopkg.in/fsnotify/fsnotify.v1" (https fetch: Get https://gopkg.in/fsnotify/fsnotify.v1?go-get=1: proxyconnect tcp: EOF)
go: golang.org/x/net@v0.0.0-20180906233101-161cd47e91fd: unrecognized import path "golang.org/x/net" (https fetch: Get https://golang.org/x/net?go-get=1: proxyconnect tcp: EOF)
go: gopkg.in/tomb.v1@v1.0.0-20141024135613-dd632973f1e7: unrecognized import path "gopkg.in/tomb.v1" (https fetch: Get https://gopkg.in/tomb.v1?go-get=1: proxyconnect tcp: EOF)
go: gopkg.in/vmihailenco/msgpack.v2@v2.9.1: unrecognized import path "gopkg.in/vmihailenco/msgpack.v2" (https fetch: Get https://gopkg.in/vmihailenco/msgpack.v2?go-get=1: proxyconnect tcp: EOF)
go: finding github.com/cockroachdb/cockroach v0.0.0-20170608034007-84bc9597164f
go: finding github.com/prometheus/common v0.0.0-20181113130724-41aa239b4cce
go: finding github.com/hashicorp/consul v0.0.0-20180615161029-bed22a81e9fd
go: finding github.com/influxdata/influxdb v0.0.0-20170331210902-15e594fc09f1
go: golang.org/x/oauth2@v0.0.0-20180821212333-d2e6202438be: unrecognized import path "golang.org/x/oauth2" (https fetch: Get https://golang.org/x/oauth2?go-get=1: proxyconnect tcp: EOF)
go: finding github.com/beorn7/perks v0.0.0-20180321164747-3a771d992973
go: google.golang.org/api@v0.0.0-20180910000450-7ca32eb868bf: unrecognized import path "google.golang.org/api" (https fetch: Get https://google.golang.org/api?go-get=1: proxyconnect tcp: EOF)
go: gopkg.in/alecthomas/kingpin.v2@v2.2.6: unrecognized import path "gopkg.in/alecthomas/kingpin.v2" (https fetch: Get https://gopkg.in/alecthomas/kingpin.v2?go-get=1: proxyconnect tcp: EOF)
^C
[root@kaihua-master example_write_adapter]# 
[root@kaihua-master example_write_adapter]# 
[root@kaihua-master example_write_adapter]# ping google.golang.org
PING golang.org (64.233.177.141) 56(84) bytes of data.
64 bytes from yx-in-f141.1e100.net (64.233.177.141): icmp_seq=1 ttl=30 time=223 ms
64 bytes from yx-in-f141.1e100.net (64.233.177.141): icmp_seq=2 ttl=30 time=221 ms
64 bytes from yx-in-f141.1e100.net (64.233.177.141): icmp_seq=3 ttl=30 time=221 ms
^C
--- golang.org ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 1999ms
rtt min/avg/max/mdev = 221.524/222.365/223.994/1.152 ms
[root@kaihua-master example_write_adapter]# ping contrib.go.opencensus.io
PING contrib.go.opencensus.io (216.239.36.21) 56(84) bytes of data.
64 bytes from any-in-2415.1e100.net (216.239.36.21): icmp_seq=1 ttl=44 time=36.4 ms
64 bytes from any-in-2415.1e100.net (216.239.36.21): icmp_seq=2 ttl=44 time=35.5 ms
64 bytes from any-in-2415.1e100.net (216.239.36.21): icmp_seq=3 ttl=44 time=35.7 ms
^C
--- contrib.go.opencensus.io ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2002ms
rtt min/avg/max/mdev = 35.573/35.932/36.495/0.458 ms
[root@kaihua-master example_write_adapter]# 
[root@kaihua-master example_write_adapter]#

**Comment by simonpasquier** [comment]
This works for me:

`GO111MODULE=on go build -mod=vendor ./documentation/examples/remote_storage/example_write_adapter/`

#
I'm closing it for now. If you have further questions, please use our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search.
