### ISSUE TITLE
Master UI is unusably slow

### ISSUE THREAD

**Issue by tomwilkie** [prometheus/prometheus#5308]
Running a very recent build (from yesterday), editing text in the query/graph UI is unusably slow.

Try putting this query in:
```
  sum by (pod_name, namespace) (container_memory_rss) 
/ 
  sum by (pod_name, namespace) (
    label_replace(
      kube_pod_container_resource_requests_memory_bytes, 
      "pod_name", "$1", "pod", "(.*)"
    )
  ) 
```
And adding some text after `"(.*)"`.

Heres a profile:

<img width="1523" alt="screenshot 2019-03-05 at 14 10 01" src="https://user-images.githubusercontent.com/444037/53811175-a8985580-3f50-11e9-83ec-a995a9ed875e.png">

Took ~2s to handle the keypress.  I don't know whats going on though.  @davkal ?

**Comment by davkal** [comment]
Taking a look...
