### ISSUE TITLE
util/promlint: consider making it easier for 3rd parties to import

### ISSUE THREAD

**Issue by mdlayher** [prometheus/prometheus#5317]
## Proposal

I originally added `promlint` for use in `promtool check metrics`. It is very useful for that purpose, however, it would also be nice to allow the package to be easily vendored and used in other applications for unit tests and such.

Because this main Prometheus repository is fairly large and also contains a great deal of unrelated code, I propose moving `util/promlint` to `github.com/prometheus/common/promlint` or similar. This way, library code lives with a library instead of an entire application, and is much easier to vendor.

At that point, we can vendor in the updated copy of `common` and switch the import statements used within `promtool`.

**Comment by mdlayher** [comment]
Talked with @SuperQ on IRC and it appears I was wrong about needing to vendor the entire repo. `dep` at least appears to pick out the package by itself if I `dep ensure -add github.com/prometheus/prometheus/util/promlint`.

I do still think it'd be reasonable to move this to common, though.

**Comment by brian-brazil** [comment]
It's only used in one of our repos, so I see no need to move it to common. Common is for stuff shared across our repos.

**Comment by RainbowMango** [comment]
If `github.com/prometheus/common
` isn't the proper place, then how about `github.com/prometheus/client_golang`? 

Maybe we can move it to `client_golang/prometheus/testutil`.

Involve @brancz here.

**Comment by mcristina422** [comment]
@brian-brazil @mdlayher Thoughts on moving promlint into http://github.com/prometheus/client_golang like @RainbowMango suggested? 

Or maybe even http://github.com/prometheus/promlint ? Moving it out of `github.com/prometheus/prometheus` would be extremely helpful

**Comment by brian-brazil** [comment]
As indicated in https://github.com/kubernetes/kubernetes/pull/86477 you'd probably be best using it is a library. As-is the code appropriately located from a Prometheus standpoint, as it is only used in promtool.

**Comment by RichiH** [comment]
We are currently doing a bug scrub.

@beorn is considering to move this to client_golang. @brancz would you be interested in doing that?

**Comment by beorn7** [comment]
To be precise: `client_golang/prometheus/testutil` could make sense as a location.

**Comment by beorn7** [comment]
In particular, client_golang would not be a good place for a stand-alone linter binary, but `promtool` can stay where it is and just import `client_golang/prometheus/testutil` to get the code.

**Comment by RainbowMango** [comment]
I'm interested in this, can I join or take this?
@RichiH @beorn7 @brancz

**Comment by brancz** [comment]
Go for it @RainbowMango :)

**Comment by beorn7** [comment]
I'll brace for impact then. (o:

**Comment by RainbowMango** [comment]
Working on it. Thanks.

**Comment by RainbowMango** [comment]
@beorn7 Can you assign this issue to me? It can help me find this issue quickly in the future. :)

**Comment by beorn7** [comment]
Sure, done.
