### ISSUE TITLE
retention shown in runtime page set to 0s

### ISSUE THREAD

**Issue by roidelapluie** [prometheus/prometheus#5321]
In Prometheus 2.8-rc0 the runtime page shows '0s' retention.

2.7.1:
![retention](https://user-images.githubusercontent.com/291750/54060292-7579ee80-41fc-11e9-9c74-d00667ba333d.png)

2.8-rc0:
![retention2](https://user-images.githubusercontent.com/291750/54060359-b6720300-41fc-11e9-83bc-fa316efd143f.png)

Bisect:
a3c41f425699565c880fb529af6d58cf0cb254d5 is the first bad commit
commit a3c41f425699565c880fb529af6d58cf0cb254d5
Author: Krasi Georgiev <krasi-georgiev@users.noreply.github.com>
Date:   Tue Feb 19 13:53:43 2019 +0200

    use the default time retention value only when no size retention is set (#5216)

    fixes https://github.com/prometheus/prometheus/issues/5213

    Now that we have time and size base retention time bases should not have a default value. A default is set only when both - time and size flags are not set.

    This change will not affect current installations that rely on the default time based value, and will avoid confusions when only the size retention is set and it is expected that the default time based setting would be no longer in place.

    Signed-off-by: Krasi Georgiev <kgeorgie@redhat.com>

:040000 040000 e9acc051e5fd1bfc7262fbd60e675f59976ffa3e 35e8966e63113b7bfc3a61432bbdab27d5a006f6 M      cmd

**Comment by roidelapluie** [comment]
Not sure if that is a bug or not but it is definitively confusing. Maybe we should add to the "Runtime" page the actual retention values.

**Comment by roidelapluie** [comment]
cc @krasi-georgiev

**Comment by krasi-georgiev** [comment]
what flags did you use when starting Prometheus?

**Comment by krasi-georgiev** [comment]
just replicated it, the retention is set to 15d as before,but the GUI shows incorrect info. Will fix soon. Thanks.

**Comment by roidelapluie** [comment]
Since now the flag is optional, I think maybe we could have in runtime page: "TSDB retention: 15d"

**Comment by roidelapluie** [comment]
The values printed out could be:

- 15d
- 15d or 12 GB
- 12GB

**Comment by krasi-georgiev** [comment]
I opened a PR with the fix.

> Since now the flag is optional, I think maybe we could have in runtime page: "TSDB retention: 15d"

not sure what you mean by this comment.

**Comment by roidelapluie** [comment]
Oh nevermind I had a more complex fix in mind
