### ISSUE TITLE
staticcheck tried to download a broken URL

### ISSUE THREAD

**Issue by alevchuk** [prometheus/prometheus#5325]
### Host operating system: output of `uname -a`

Linux base 4.19.25-v7+ #1205 SMP Mon Feb 25 18:19:20 GMT 2019 armv7l GNU/Linux

### node_exporter version: output of `node_exporter --version`
 latest checkout of node_exporter 19e5bb6abdfbc69e9f2039485842eb3c0cf87d08

### node_exporter command line flags
can't build

### Are you running node_exporter in Docker?
no

### What did you do that produced an error?
make

### What did you expect to see?
make should succeed

### What did you see instead?
```
prometheus@base:~/gocode/src/github.com/prometheus/node_exporter $ make
>> checking code style
mkdir -p /home/prometheus/gocode/bin
curl -s -L https://github.com/dominikh/go-tools/releases/download/2019.1/staticcheck_linux_arm > /home/prometheus/gocode/bin/staticcheck
>> running staticcheck
```

seems to be there is no ARM for 2019.1 static check https://github.com/dominikh/go-tools/releases/tag/2019.1

**Comment by dominikh** [comment]
I'd be happy to add ARM targets. Should we build for ARMv5 (which is supported by v6 and v7 platforms, too), or have one version per possible GOARM? You'd have to change the format of the URL in the latter case.

**Comment by SuperQ** [comment]
@dominikh This users is on armv7, but we build quite a lot of platforms for Prometheus. You might want to look at [`promu`](https://github.com/prometheus/promu), which we use for crossbuild publishing.

**Comment by SuperQ** [comment]
@dominikh What do you think about adding a CircleCI build/publish to go-tools?

**Comment by alevchuk** [comment]
Hey thanks for quick plan for the fix!

I was gonna say "pulling in binaries of the internet during `make` makes is hard to review what's being built" yet possibly the opposite is true. Not sure.

Github release builds seem reviewable. E.g. https://github.com/dominikh/go-tools/releases/tag/2019.1 yet there seems to be no view of the commits since last review.

**Comment by dominikh** [comment]
> @dominikh What do you think about adding a CircleCI build/publish to go-tools?

I want people to run fixed releases, not master (unless they want to find issues in staticcheck), and I think I can build the odd release manually just fine ;)

> I was gonna say "pulling in binaries of the internet during make makes is hard to review what's being built" yet possibly the opposite is true. Not sure.

There could be any code in the binary, it doesn't have to match at all what the tag says, so that requires trust. Then again, nobody reads the code of the tools they `go get`, so the effect is the same.

**Comment by alevchuk** [comment]
Still seems to be broken.

Re-ran make with the latest checkouts:
https://github.com/prometheus/node_exporter/commit/19e5bb6abdfbc69e9f2039485842eb3c0cf87d08
https://github.com/prometheus/prometheus/commit/8155cc49924cd48ec552506b4e5519ebafa8b722
https://github.com/prometheus/promu/commit/cdcd4358d7bf0abf3dcab7acf3b7ae2816544021
```
prometheus@base:~/gocode/src/github.com/prometheus/node_exporter $ make
>> checking code style
mkdir -p /home/prometheus/gocode/bin
curl -s -L https://github.com/dominikh/go-tools/releases/download/2019.1/staticcheck_linux_arm > /home/prometheus/gocode/bin/staticcheck
>> running staticcheck
chmod +x /home/prometheus/gocode/bin/staticcheck
GO111MODULE=on go list -e -compiled -test=true -export=false -deps=true -find=false -tags= -- ./... > /dev/null
go: downloading github.com/sirupsen/logrus v1.3.0
go: downloading github.com/prometheus/client_model v0.0.0-20190129233127-fd36f4220a90
go: downloading github.com/soundcloud/go-runit v0.0.0-20150630195641-06ad41a06c4a
go: downloading golang.org/x/net v0.0.0-20190206173232-65e2d4e15006
go: downloading github.com/golang/protobuf v1.2.0
go: downloading github.com/godbus/dbus v0.0.0-20181101234600-2ff6f7ffd60f
go: downloading github.com/alecthomas/units v0.0.0-20151022065526-2efee857e7cf
go: verifying github.com/soundcloud/go-runit@v0.0.0-20150630195641-06ad41a06c4a: checksum mismatch
        downloaded: h1:TGsOnmXp0mo82KbjaDcsTibGxWIdZNXbKJB18gFn1RM=
        go.sum:     h1:os5OBNhwOwybXZMNLqT96XqtjdTtwRFw2w08uluvNeI=
Makefile.common:141: recipe for target 'common-staticcheck' failed
make: *** [common-staticcheck] Error 1


prometheus@base:~/gocode/src/github.com/prometheus/node_exporter $ cat /home/prometheus/gocode/bin/staticcheck
Not Found
```

**Comment by simonpasquier** [comment]
@alevchuk the change to `Makefile.common` has to be propagated to the various repositories but it should work for github.com/prometheus/prometheus using the master branch. Can you check again for this one?

**Comment by alevchuk** [comment]
@simonpasquier i'll check prometheus as well (will need to try before and after your fix, because it never saw a break in prometheus). The delay between git push and pull is usually sub-second. Can you tell me what introduces the propagation delay here?

**Comment by alevchuk** [comment]
I found a workaround for my node_exporter build problem.

```
prometheus@base:~/gocode/src/github.com/prometheus/node_exporter $ cp  ../prometheus/Makefile.common Makefile.common
```


>> checking code style                                                                                                                  make: *** No rule to make target 'check_license', needed by 'common-all'.  Stop.

and remove "check_license" and "unused" from common-all line in `Makefile.common`
```
- common-all: precheck style check_license staticcheck unused build test
+ common-all: precheck style staticcheck build test
```

btw, I tried building prometheus, as requested, yet dropped it because it required "bzr" which pulls in a ton of dependencies

To be honest this build was stressful.  Yet, I appreciate the fast root-cause.

**Comment by SuperQ** [comment]
Yes, I think someone introduced a dependency for one package that uses `bzr` rather than `git` to pull source.

**Comment by simonpasquier** [comment]
Re bzr being needed to build Prometheus, it is commented in the Makefile:

https://github.com/prometheus/prometheus/blob/10ec2552af1be4a421b89afd4a1f8eb17948a187/Makefile#L22-L24

**Comment by simonpasquier** [comment]
> The delay between git push and pull is usually sub-second. Can you tell me what introduces the propagation delay here?

To be precise, the canonical version of `Makefile.common` is maintained on https://github.com/prometheus/prometheus then _someone_ has to open PRs on the other repositories to sync the local version with the canonical one. It is a bit tedious but we haven't spent more time to streamline the process yet...

**Comment by SuperQ** [comment]
@simonpasquier It seems like launchpad.net/gocheck is abandoned. There is now http://labix.org/gocheck located at `gopkg.in/check.v1`.

**Comment by simonpasquier** [comment]
Unfortunately we don't control this dependency as it is pulled indirectly from `github.com/hashicorp/consul`...

```
simon@simon-laptop:~/workspace/src/github.com/prometheus/prometheus ✔ $ GO111MODULE=on go mod why  launchpad.net/gocheck                                                                     
go: finding google.golang.org/grpc/transport latest
# launchpad.net/gocheck
github.com/prometheus/prometheus/discovery/consul
github.com/hashicorp/consul/api
github.com/hashicorp/consul/api.test
github.com/hashicorp/serf/serf
github.com/hashicorp/go-msgpack/codec
github.com/hashicorp/go-msgpack/codec.test
labix.org/v2/mgo/bson
labix.org/v2/mgo/bson.test
launchpad.net/gocheck
```

**Comment by SuperQ** [comment]
Yea, I was looking at that stack of dependencies. It looks like the latest version of `github.com/hashicorp/go-msgpack/codec` has eliminated the test that depends on `labix.org/v2/mgo/bson`, which eliminates the need for `launchpad.net/gocheck`.

**Comment by simonpasquier** [comment]
Yes, sending a PR right away.
