### ISSUE TITLE
Exponentation (`^`) operator does not drop metric name

### ISSUE THREAD

**Issue by juliusv** [prometheus/prometheus#5327]
See http://demo.robustperception.io:9090/graph?g0.range_input=1h&g0.expr=up%20%5E%202&g0.tab=1

Like any other binary arithmetic operator, `^` should drop the metric name.

Reason is this line: https://github.com/prometheus/prometheus/blob/d390497280d61918aa8792f87a2f458e5e231ec2/promql/engine.go#L1896

**Comment by infoverload** [comment]
I'll take a crack at this!
