### ISSUE TITLE
Allow reloading with non POST methods

### ISSUE THREAD

**Issue by eirc** [prometheus/prometheus#5343]
The `/-/reload` endpoint only works with the `POST` method. It would possibly make more sense to allow other methods too like `PUT`.

https://github.com/prometheus/prometheus/blob/7c8f0b08647f1ac5f9608069678b4a01c6e79866/web/web.go#L313

The reasoning is that `POST` by definition produces different side effects each time it is run (like create new resources under `REST`) compared to `PUT` which you can supposedly safely fire multiple times.

Technically my problem is when trying to reload prometheus with a python program and `urllib3` refuses to retry `POST` requests when there's a read error (specifically) since resending a `POST` when the server _may_ have already received is a no no although it's not really a problem in config reloading.

https://github.com/urllib3/urllib3/blob/2a0957ea27e966166f81f88693af8e2f87d19fb6/src/urllib3/util/retry.py#L97-L104

PS: I'm also suggesting to just add the `PUT` instead of replacing the `POST` just for compatibility reasons, I'm sure many would take issue with such an API change.

**Comment by brian-brazil** [comment]
Longer term we plan on switching this to PUT for XSRF reasons, so supporting both now would make sense.

> Technically my problem is when trying to reload prometheus with a python program and urllib3 refuses to retry POST requests when there's a read error

Is that supported by the RFCs?

**Comment by eirc** [comment]
TBH I have no idea what RFCs say about this but it does make sense IMHO.

**Comment by bharaththiruveedula** [comment]
@brian-brazil can I work on this?

**Comment by brian-brazil** [comment]
Sure

**Comment by Danielv123** [comment]
With the PR merged, this issue should be considered for closing.
