### ISSUE TITLE
Auto-publish README to Dockerhub

### ISSUE THREAD

**Issue by SuperQ** [prometheus/prometheus#5348]
The README on docker hub is very stale as pointed out on -developers.

We can add https://github.com/SISheogorath/readme-to-dockerhub to CircleCI to auto-publish the README.

https://hub.docker.com/r/sheogorath/readme-to-dockerhub

**Comment by brian-brazil** [comment]
We could also one-off replace it by just a link to the actual readme. Keeping that working for every repo could be a bit of work.

**Comment by beorn7** [comment]
Hello from the bug scrub.

@SuperQ is this still an issue?

**Comment by SuperQ** [comment]
Yes, we still do not automatically update the docs on hub.docker.com or quay.io.

**Comment by SuperQ** [comment]
It looks like we could use https://github.com/marketplace/actions/update-container-description-action.
