### ISSUE TITLE
Metric type in prompb

### ISSUE THREAD

**Issue by Pryz** [prometheus/prometheus#5351]
Would it be possible to add the type of the metrics in the prompb proto ? Right now there is no way for a remote service to know if the forwarded metrics are counters or gauges for instance.

I was looking at implementing a remote storage (write only currently but will consider a read handler if the write one is working as expected) to forward Prometheus metrics to statsd-like systems. However, since the prompb proto is not exposing the type of the metrics, it makes the translating job quite complicated.

The best would be the have the TYPE and HELP in prompb (https://godoc.org/github.com/prometheus/client_model/go#MetricFamily).

Thanks !

**Comment by Pryz** [comment]
After chatting on #prometheus, seems like the current way is to call the target metadata api (https://github.com/prometheus/prometheus/blob/master/docs/querying/api.md#querying-target-metadata) to get the information about the metric.

**Comment by brian-brazil** [comment]
That'd be quite involved, as we'd need to store it in the TSDB first and this isn't time series data. I'd suggest working with the Prometheus text format directly.

**Comment by Harkishen-Singh** [comment]
@brian-brazil should this be closed as I think it is implemented in #6815

**Comment by brian-brazil** [comment]
No, #6815 does not allow this. The information it provides is not sufficient, timely, or sent to the shard where it would be needed.

**Comment by beorn7** [comment]
Hello from the bug scrub.

This should be fixed by https://github.com/prometheus/prometheus/pull/13394 . Closing.
