### ISSUE TITLE
module directive in go.mod is missing version number

### ISSUE THREAD

**Issue by exklamationmark** [prometheus/prometheus#5356]
## Proposal

Hi,

I was trying to import some packages from the repos at `v2.8.0` and noticed that Go module didn't resolve to the tagged version. Instead, it resolved to a pseudo-version number
(`v0.0.0-20190312040920-59369491cfdf`).

While the hash is still correct (`59369491cfdf` is tagged with `v2.8.0`), it took a while to understand and verify when working with Go module.

The cause was the `module` directive in `go.mod`, which didn't match strategies
[for release > v2 in Go module](https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher).

This is probably not that important if we just want to build the binary. However, it can be annoying when importing packages from Prometheus.

A proper fix would probably need to have the correct major version number in `go.mod`.
For now, it could simply mean having

```
module github.com/prometheus/prometheus/v2
```

## Bug Report
**What did you do?**

Import `github.com/prometheus/prometheus/promql` and `github.com/prometheus/prometheus/storage` at version `v2.8.0`

**What did you expect to see?**

```bash
$ GO111MODULE=on go get -v -x github.com/prometheus/prometheus@v2.8.0
$ cat go.mod | grep 'prometheus/prometheus'
        github.com/prometheus/prometheus v2.8.0 // indirect
```

**What did you see instead? Under which circumstances?**

```bash
$ GO111MODULE=on go get -v -x github.com/prometheus/prometheus@v2.8.0
$ cat go.mod | grep 'prometheus/prometheus'
        github.com/prometheus/prometheus v0.0.0-20190312040920-59369491cfdf
```

**Environment**

* System information:

	Linux 4.15.0-46-generic x86_64

* Prometheus version:

	prometheus, version 2.8.0 (branch: HEAD, revision: 59369491cfdfe8dcb325723d6d28a837887a07b9)

* Alertmanager version:

	N/A

* Prometheus configuration file:

	N/A

* Alertmanager configuration file:

	N/A

* Logs:

	N/A

**Comment by simonpasquier** [comment]
We can't (don't want to) guarantee any API stability on the `github.com/prometheus/prometheus/*` packages so `github.com/prometheus/prometheus/pkg/foo@v2.9.0` could break its API compared to v2.8.0 if we need it. Following SemVer and the Go modules conventions would be misleading and worth than the current situation IMHO.

**Comment by exklamationmark** [comment]
I see. Indeed it would be misleading to follow SemVer in that case.
Should we add some notes to about this, or just leave it as is?

**Comment by simonpasquier** [comment]
I'd leave as it is now since the note would probably be hard to find for people anyway.

**Comment by bcmills** [comment]
See also golang/go#25898.
