### ISSUE TITLE
v2.8.0 OOM with remote write

### ISSUE THREAD

**Issue by HarveyJie** [prometheus/prometheus#5364]
2.8.0 version OOM always， update from 2.7.2

**Comment by codesome** [comment]
@HarveyJie are you using remote_write?

**Comment by HarveyJie** [comment]
@codesome yes!, I use remote_write  by timesale

**Comment by codesome** [comment]
remote_write uses WAL in 2.8.0 which apparently takes more memory than before. Work is in progress here https://github.com/prometheus/prometheus/pull/5316 to reduce the memory usage.
