### ISSUE TITLE
Display rules as defined in configuration

### ISSUE THREAD

**Issue by sylr** [prometheus/prometheus#5370]
## Proposal
**Use case. Why is this important?**

Prometheus rules can be quite complex thus the use of comments, new lines, uppercased keywords ... etc can help make it easier to understand.

E.G:

```
(
    # Pod is down and rename label "kubernetes_pod_name" to "pod"
    label_replace(up{job="kubernetes-pods"}, "pod", "$1", "kubernetes_pod_name", "(.*)")
    *
    # Add node label to up{}
    on (pod) group_left(node) avg(kube_pod_info) by (pod, node)
) == 0
AND
# Node is ready
on (node) kube_node_status_condition{condition="Ready",status="true"} == 1
```

Unfortunately the Prometheus UI does not display the rules as they were written but like if a "sanitizer" have been applied, i.e.:

```
(label_replace(up{job="kubernetes-pods"},
  "pod", "$1", "kubernetes_pod_name", "(.*)") * on(pod)
  group_left(node) avg by(pod, node) (kube_pod_info)) == 0 and on(node) kube_node_status_condition{condition="Ready",status="true"}
  == 1
)
```
The latter is really quite indigest so it would be nice if you could keep the formatting as it.

**Comment by brian-brazil** [comment]
This is a limitation of the YAML parser we use, once it's better we can do better.

**Comment by sylr** [comment]
The YAML parser seems capable to handle comments and multiline strings quite all right:

```go
package main

import (
	"fmt"

	yaml "gopkg.in/yaml.v2"
)

type T struct {
	A string `yaml:"a"`
}

var (
	conf = `a: |
  (
    # Pod is down and rename label "kubernetes_pod_name" to "pod"
    label_replace(up{job="kubernetes-pods"}, "pod", "$1", "kubernetes_pod_name", "(.*)")
    *
    # Add node label to up{}
    on (pod) group_left(node) avg(kube_pod_info) by (pod, node)
  ) == 0
  AND  # Node is ready
  on (node) kube_node_status_condition{condition="Ready",status="true"} == 1`
)

func main() {
	t := T{}
	yaml.UnmarshalStrict([]byte(conf), &t)
	fmt.Printf("%s\n-----------\n", conf)
	fmt.Printf("%s\n", t.A)
}
```

**Comment by brian-brazil** [comment]
Ah, you're looking at the rules page. Those are what the PromQL printer produces. On a page like that it's best to have the actual AST, rather than what may be a confusingly written expression.

> The YAML parser seems capable to handle comments and multiline strings quite all right:

Actually that's all multi-line strings. PromQLs supports # comments.

**Comment by sylr** [comment]
I'm talking at the alerts page really but it's the same problem.

> On a page like that it's best to have the actual AST, rather than what may be a confusingly written expression.

I beg to differ, when you write a rule with indentation, comments and such to make it understandable and easily editable, having it reduced to it's simplest form is what is confusing.

**Comment by brian-brazil** [comment]
That's presuming you get the indentation etc. right. When debugging knowing how it's actually parsed is important.

**Comment by sylr** [comment]
> That's presuming you get the indentation etc. right.

That's not a valid concern, a simple `<pre>` block would be enough.

> When debugging knowing how it's actually parsed is important.

Maybe a few developpers are actually debugging prometheus query parser, users are concerned  to understand the sens of query that have been written by their colleagues.

**Comment by brian-brazil** [comment]
> That's not a valid concern, a simple <pre> block would be enough.

I don't see how that helps. If someone's has misleading indentation, it'll still be misleading.

> Maybe a few prometheus developpers are actually debugging prometheus query parser, users are concerned to understand the sens of query that have been written by their colleagues.

I meant debugging queries, not Prometheus.

**Comment by brian-brazil** [comment]
> And so much for those who get it right ?

This is from experience, it's not the ones that get it right that I have to spend time on.

The rules are on disk if you wish to view them.

**Comment by brian-brazil** [comment]
Which isn't to say the current printer couldn't be improved with some indentation and newlines.

**Comment by sylr** [comment]
![Prometheus_Time_Series_Collection_and_Processing_Server](https://user-images.githubusercontent.com/153052/54475326-419c5b80-47f0-11e9-9eee-71462a5699c3.png)

**Comment by brian-brazil** [comment]
That's non-standard indentation, anything on this page should be in a canonical form.

**Comment by sylr** [comment]
No, it should be as written in configuration.

**Comment by roidelapluie** [comment]
I agree with @brian-brazil (did you change your github username?)

We have lots of complex PromQL and it helps to see how Prometheus "compiles" that. I do not want to see my "garbage" in the console. I have the files for it.

**Comment by sylr** [comment]
That's the problem here, you only think of yourselves and don't think about how other people might need to understand your rules in the middle of the night.

**Comment by roidelapluie** [comment]
That is not true. We are making high usage of annotations for on call people.

**Comment by roidelapluie** [comment]
(And on call also has access to the rule files + ansible repos.. with the original queries)

**Comment by beorn7** [comment]
I think the general idea is to have some kind of `promfmt`, similar to `gofmt`. Prometheus would format the parsed rules with `promfmt` to show the canonical indentation and formatting. In turn, humans writing rules can also use `promfmt` (similar to writing Go code, for example upon saving a rules file), so that everywhere the same canonical formatting would be used and nobody is confused.

Note that `gofmt` preserves comments and (certain) line breaks. `promfmt` (and the parsing in general) should do the same, both for comments in YAML as well as within PromQL expressions.

**Comment by beorn7** [comment]
Aaand this idea is actually ancient – which I knew, but I forgot we have an issue for it: #21. It is, in fact, the second oldest still open issue…

**Comment by beorn7** [comment]
I amended #21 with some observations from the discussion here.

Would it be OK to close this issue in lieu of #21?

**Comment by sylr** [comment]
All right.
