### ISSUE TITLE
no data for a UP target

### ISSUE THREAD

**Issue by lcgogo** [prometheus/prometheus#5380]
## Proposal
**Use case. Why is this important?**
I can see one target in prometheus target website, however, I can not get anything of it from prometheus database.

*“Nice to have” is not a good use case. :)*

## Bug Report
**What did you do?**
I have config a target in the prometheus.yml and the target website is UP. However, in console, there is no target information. The other tragets are OK except that one

**What did you expect to see?**

**What did you see instead? Under which circumstances?**

**Environment**
ubuntu 18.04 docker 18.09.0 latest prometheus image

* System information:
root@aws-elkprom-01:/data/prometheus# uname -srm
Linux 4.15.0-1029-aws x86_64
	insert output of `uname -srm` here

* Prometheus version:
root@aws-elkprom-01:/data/prometheus# docker exec -it prometheus /bin/sh
/prometheus $ prometheus --version
prometheus, version 2.5.0 (branch: HEAD, revision: 67dc912ac8b24f94a1fc478f352d25179c94ab9b)
  build user:       root@578ab108d0b9
  build date:       20181106-11:40:44
  go version:       go1.11.1

	insert output of `prometheus --version` here

* Alertmanager version:

	insert output of `alertmanager --version` here (if relevant to the issue)

* Prometheus configuration file:
```
insert configuration here
```

* Alertmanager configuration file:
```
insert configuration here (if relevant to the issue)
```

  - job_name: 'wallet'
  # List of labeled statically configured targets for this job.
    static_configs:
    - targets:
      ## SANDBOX
      # aws-wallet-sandbox-backend1-AZ2c
      - 172.31.5.236:20200
      - 172.31.5.236:20201
      - 172.31.5.236:20202   # process exportor
      # aws-wallet-sandbox-iface1-AZ2c
      - 172.31.6.117:20200
      - 172.31.6.117:20201
      - 172.31.6.117:20202   # process exportor
      # aws-wallet-sandbox-influxdb
      - 172.31.252.28:20200
      - 172.31.252.28:20201
      # aws-wallet-sandbox-sync1-AZ2c
      - 172.31.5.172:20200
      - 172.31.5.172:20201
      - 172.31.5.172:20202   # process exportor
      ## PRODUCT
      # aws-wallet-influxdb
      - 172.31.252.21:20200
      - 172.31.252.21:20201
      # aws-wallet-sync1-AZ2b
      - 172.31.5.30:20200
      - 172.31.5.30:20201
      - 172.31.5.30:20202   # process exportor
      # aws-wallet-sync2-AZ2c
      - 172.31.5.41:20200
      - 172.31.5.41:20201
      - 172.31.5.41:20202   # process exportor
      # aws-wallet-backend1-AZ2b
      - 172.31.5.68:20200
      - 172.31.5.68:20201
      - 172.31.5.68:20202   # process exportor
      # aws-wallet-backend2-AZ2c
      - 172.31.5.105:20200
      - 172.31.5.105:20201
      - 172.31.5.105:20202   # process exportor

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by zhulongcheng** [comment]
Maybe add the `prometheus-users mailing list` to `README.md`?
