### ISSUE TITLE
support stddev for matrix with group bys

### ISSUE THREAD

**Issue by alburthoffman** [prometheus/prometheus#5385]
## Proposal
**Use case. Why is this important?**
stddev is quite useful function. and sometimes we want to caculate it for a given time window with group bys. But it turns out that prometheus could support it easily.

## Bug Report
**What did you do?**
simply speaking, I want to do something like this
`stddev_over_time(metric[10m]) by (pool, colo)`

**What did you expect to see?**
it will group by metrics with pool and colo, then caculate stddev for last 10m for each group.

**What did you see instead? Under which circumstances?**
an error which means prometheus doesnot support it.

**Environment**
lastest prometheus version

any other ideas like `avg(metric) by (pool, colo)` first, wont get the correct stddev value.
the only solution here for now is to create a new metric which is as same as the old one but only has pool and colo dimensions, and the running `stddev_over_time(metric_with_pool_colo_dimensions_only[10m]) `

so is there a better way to support this? or we can enhance stddev to aggregate matrix?

**Comment by brian-brazil** [comment]
We don't mix cross-sectional and longitudinal aggregations. What you probably want here is a recording rule with the cross-sectional, and then do the over_time on that.

**Comment by gouthamve** [comment]
We've gone through this during our bug scrub, and this requires major changes in the language and we are marking it wont-fix. If you'd still like to see this, could you re-open with a use-case for us to consider?
