### ISSUE TITLE
how many metrics can i pull from pushgateway?

### ISSUE THREAD

**Issue by DemoLiang** [prometheus/prometheus#5396]
## Proposal
**Use case. Why is this important?**
1. i want to now prometheus performance, How many metrics can i pull from pushgateway at once?

I configured scrape_interval 1m pull once, scrape_timedout 10s,evaluation_interval 5s, and timeout occurred from pushgateway pull 500000 metric.

*“Nice to have” is not a good use case. :)*

**Comment by roidelapluie** [comment]
Thanks for your report. It looks as if this is actually a question about usage and not development.

To make your question, and all replies, easier to find, we suggest you move this over to our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search. If you prefer more interactive help, join or our [IRC channel](https://webchat.freenode.org/?channels=prometheus), #prometheus on irc.freenode.net. Please be aware that our IRC channel has no logs, is not searchable, and that people might not answer quickly if they are busy or asleep. If in doubt, you should choose the mailing list.

If you think this is not purely a support question, feel free to comment in here or take the underlying issues to our [developer mailing list](https://groups.google.com/forum/#!forum/prometheus-developers).

Once your questions have been answered, please add a short line pointing to relevant replies in case anyone stumbles here via a search engine in the future.
