### ISSUE TITLE
Consider using the Kahan summation algorithm to reduce accumulation of errors in floating point arithmetic.

### ISSUE THREAD

**Issue by tomwilkie** [prometheus/prometheus#5400]
(Just read this on hacker new: https://hypothesis.works/articles/calculating-the-mean/ and https://news.ycombinator.com/item?id=19470945)

This should be relatively easy for us to implement, and should precision of our sums.

https://en.wikipedia.org/wiki/Kahan_summation_algorithm

**Comment by tomwilkie** [comment]
This could be considered related to #4533.

**Comment by smarch2** [comment]
Hi @tomwilkie, has any progress been made on this? 

I'd be happy to take a look into it if the community see this worth pursuing.

**Comment by beorn7** [comment]
Hello from the bug scrub.
This was fixed by #9588. Closing.
