### ISSUE TITLE
Node labels not seen on the grafana dashboard when prometheus is deployed without pv enabled

### ISSUE THREAD

**Issue by spoorti22** [prometheus/prometheus#5401]
## Proposal
**Label values for a variable defined in Grafana dashvboard doesn't seem to capture the data.**
 
## Bug Report
**The label values which is created as a variable, is not getting the data**
 This api should give the node/pod values /api/v1/label/kubernetes_io_hostname/values
{"status":"success","data":[]}

**What did you expect to see?**
The node/pod values should have been seen

**What did you see instead? Under which circumstances?**
{"status":"success","data":[]}
Not able to get the label values.

****

* System information:

	Linux 3.10.0-862.2.3.el7.x86_64 x86_64

* Prometheus version:

  prometheus, version 2.3.2 (branch: HEAD, revision: 71af5e29e815795e9dd14742ee7725682fa14b7b)
  build user:       root@5258e0bd9cc1
  build date:       20180712-14:02:52
  go version:       go1.10.3

* Alertmanager version:

  alertmanager, version 0.15.2 (branch: HEAD, revision: 
  d19fae3bae451940b8470abb680cfdd59bfa7cfa)
  build user:       root@3101e5b68a55
  build date:       20180814-10:53:39
  go version:       go1.10.3

* Prometheus configuration file:
```
The config is same as below: 
https://github.com/prometheus/prometheus/blob/master/documentation/examples/prometheus-kubernetes.yml
```
Have deployed prometheus with no PV enabled, after redeploying it is able to fetch the label values. But what could be the main issue?

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
