### ISSUE TITLE
Do we have a way to get host names in metrics scrapped in Docker swarm 

### ISSUE THREAD

**Issue by saiharshitachava** [prometheus/prometheus#5410]
I am running node exporter as a global service in Docker swarm and I would like to get the hostnames in metrics scrapped using prometheus.

I'm currently using the A protocol in prometheus.yml which is giving me the container IP's .But I would need the hostnames of the instances as I have many hosts to monitor

I currently see them as below.

up{instance="10.0.33.243:8080",job="cadvisor_eng",monitor="codelab-monitor"} | 1
-- | --
up{instance="10.0.33.244:9100",job="node-exporter_eng",monitor="codelab-monitor"}

 I would need hostnames instead of 10.0.33.243,10.0.33.244

Any help?

**Comment by simonpasquier** [comment]
I suppose that you're using the DNS service discovery. You could use relabeling with `__meta_dns_name` provided that every target identifies uniquely by hostname + job.

```yaml
relabel_configs:
- source_labels: [__meta_dns_name]
  action: replace
  target_label: instance
```

See also https://www.robustperception.io/controlling-the-instance-label

I'm closing it for now. If you have further questions, please use our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search.
