### ISSUE TITLE
Freeze on graph page when working with a large amount of metrics due to no upper limit on insertable metric dropdown.

### ISSUE THREAD

**Issue by SpencerMalone** [prometheus/prometheus#5421]
## Bug Report

**What did you do?**
~After upgrading from 2.6.1 -> 2.8.0, we start seeing large page freezes just after page load. It's like... Page load, click around for a moment, interact with the expression bar, then there's a heavy loading pause (10 seconds?), then it goes to normal with some brief pauses afterwards. We have seen this across all of our instances of 2.8.0, but be aware that we do have pretty beefy deployments.~

~Once it finishes loading, it's often OK, but that into chug is painful.~

Read below, but this turned out to be a coincidence, the problem was a large increase in metric labels that caused the DOM node population on the insertable metric dropdown to cause heavy slowdowns. We should have an upper limit on the amount of DOM nodes we create in https://github.com/prometheus/prometheus/blob/master/web/ui/static/js/graph/index.js#L276

**What did you expect to see?**
Not the spinning loading wheel.

**What did you see instead? Under which circumstances?**
An inability to interact with the GUI

**Environment**

* System information:
`Linux 4.4.161-1.el7.elrepo.x86_64 x86_64`

* Prometheus version:
```
prometheus --version
prometheus, version 2.8.0 (branch: HEAD, revision: 59369491cfdfe8dcb325723d6d28a837887a07b9)
  build user:       root@4c4d5c29b71f
  build date:       20190312-07:46:58
  go version:       go1.11.5
```

* Logs:
There's no JS errors logging, but here is a gif of the behavior. What are you are looking at is the lengthy freeze where the text cursor stops blinking, and the expression bar stays highlighted.

![Screen Recording 2019-03-29 at 03 48 PM](https://user-images.githubusercontent.com/8786752/55258834-6229d400-523a-11e9-88db-cdfaa3b1a4eb.gif)

**Comment by SpencerMalone** [comment]
I'm thinking this has something to do with https://github.com/prometheus/prometheus/blob/master/web/ui/static/js/graph/index.js#L262 or the typeahead, but am having trouble reliably profiling exactly what is causing the pain. I found a small improvement in using a doc fragment for creating options, but nothing huge yet.

**Comment by SpencerMalone** [comment]
OK, I am pretty confident that this is the insertable metric selector. I'm gonna update the title.

Note that we fixed this for our instance, the tl;dr is that we had a cardinality explosion involving someone putting templated data into a metric name with a high cardinality, after fixing the problem and deleting the data, we were unaware that tombstone cleaning was required to remove the entries from the API method being called by the UI. Cleaning those fixed us up, BUT, I still think it's worth having an upper limit on the "insert metrics" dropdown selection.

**Comment by brian-brazil** [comment]
We already have a 10k limit as of 2.8, are you sure you're running at least that?

**Comment by SpencerMalone** [comment]
My understanding is that 2.8 limit was for the lookahead stuff, correct? These heavy pauses lined up with the amount of dom nodes inserted in the code block...
```
        pageConfig.allMetrics = json.data; // todo: do we need self.allMetrics? Or can it just live on the page
        for (var i = 0; i < pageConfig.allMetrics.length; i++) {
          self.insertMetric[0].options.add(new Option(pageConfig.allMetrics[i], pageConfig.allMetrics[i]));
        }
```
at https://github.com/prometheus/prometheus/blob/master/web/ui/static/js/graph/index.js#L274 for the `insert metric at cursor` dropdown population

When I used the chrome debugger to artificially limit the amount of data allowed in that loop, the pause decreased dramatically. The hardest thing is communicating that the amount of metrics populated into that dropdown has been limited. I was looking at something like...

```
        pageConfig.allMetrics = json.data; // todo: do we need self.allMetrics? Or can it just live on the page
        insertMetric = self.insertMetric[0]
        var length = json.data.length;
        if (length > 50000) {
          length = 0
          insertMetric.options[0].text = "- disabled due to volume (too many metric names)"
        }

  
        var fragment = document.createDocumentFragment();
  
        for (var i = 0; i < length; i++) {
          var el = document.createElement('option');
          el.value = json.data[i]
          el.text = json.data[i]
          fragment.appendChild(el);
        }

        insertMetric.appendChild(fragment)
```

But that totally disables that functionality when this occurs. Is that OK?

It ends up looking like so:
<img width="660" alt="Screen Shot 2019-04-10 at 8 37 37 PM" src="https://user-images.githubusercontent.com/8786752/55922733-86899700-5bd0-11e9-9dbf-a440d5f3ea7d.png">
<img width="484" alt="Screen Shot 2019-04-10 at 8 37 40 PM" src="https://user-images.githubusercontent.com/8786752/55922737-8a1d1e00-5bd0-11e9-9bec-562c6c08397e.png">

**Comment by ahurtaud** [comment]
Hello, we "need" this feature for thanos which aggregate even more metrics names. :) 
@SpencerMalone Can you go with a PR with your change in order to have a review / discussion on it ? I think you can go with 10k limit to sync with the metric query view.
Thank you,

**Comment by dgl** [comment]
I didn't find this earlier, there's a bit more related discussion on #5919 (and a related pull request).

**Comment by gouthamve** [comment]
Hi, can you reproduce this with the latest version? And with the new UI / old UI? If yes, could you update the latest state here so we can take a look?

**Comment by bwplotka** [comment]
Idea from Bug scrub: We might want to look on API limits as well

**Comment by hartfordfive** [comment]
Any updates on this issue?   My Prometheus graph UI is essentially unusable due to the number of metrics we have.  I've noticed a gradual increase of latency over time in the interface when attempting to graph metrics.  It's now to the point where if I add more than one graph,  chrome constantly pops up a "Page Unresponsive" notice because of this tab.   It's quite discouraging most of our users attempting to graph data, so they have no choice but to explore queries in Grafana.

**Comment by brian-brazil** [comment]
What version of Prometheus are you using, and how many metric names do you have?

**Comment by hartfordfive** [comment]
@brian-brazil, we're running v2.20.1.  Based on the `/status` page, this Prometheus instance has approx. 29400 metric names (unique values of `__name__`).   In case this extra information is of any value, we current have our min/max block duration set to 2h and we have the tsdb retention time set to 12h as we use GCS via Thanos to store anything older than that.

**Comment by brian-brazil** [comment]
30k shouldn't be making things unusable, but it can you expand on what you mean by "adding one more graph"?

**Comment by hartfordfive** [comment]
Most of the time, when I:
1. Load the `/graph` page on the Prometheus UI
2. Attempt to click in the  "Expression" query bar to enter an expression

it can often take 5+ seconds for the UI to respond or in other words, allow you to actual type in the promql expression.  In any case, if I attempt to click on the "Add Graph" button to add a second expression below, the UI becomes unresponsive again until the "Page Unresponsive" popup appears with the Prometheus tab in question.  At this point, I have to select "Exit Pages" as it's just no longer responsive.  

Another thing I've realized, in case this has any value, in the status section under "Label Names With Highest Cumulative Label Value Length", the top label is `__name__` with a "**Length**" value of **3584388**.

**Comment by hartfordfive** [comment]
Any updates on this?

**Comment by hartfordfive** [comment]
Any updates on this?  The UI is unusable most of the time, which is unfortunate.   In the situation where I can use it, the instant I attempt to add a second query, the UI is completely unresponsive and I eventually get a notice from Chrome to kill the tab.
