### ISSUE TITLE
Prometheus bad graph scale numbers

### ISSUE THREAD

**Issue by danielmotaleite** [prometheus/prometheus#5427]
## Bug Report
**What did you do?**
A graph with this query:

            system_load5{host=~".*kafka-.*"} / system_n_cpus{host=~".*kafka-.*"} > 1.7

**What did you expect to see?**
a graph with small, integer or similar scale numbers

**What did you see instead? Under which circumstances?**
sometimes i get this graph

![image](https://user-images.githubusercontent.com/11890049/55419693-dfb85180-5564-11e9-80a5-956c4ce1dd03.png)

Notice the scale, not very useful. So please add something to round that to more friendly scale

prometheus version:
Version 	2.7.0
Revision 	410ee9e04acb8f59f400858752ca82b4ef88035e
Branch 	HEAD
BuildUser 	root@3bc81b516055
BuildDate 	20190128-10:09:51
GoVersion 	go1.11.5

**Comment by simonpasquier** [comment]
Looks like a duplicate of https://github.com/prometheus/prometheus/issues/3595. Could you try with v2.8.1 as some UI components have been updated?

**Comment by danielmotaleite** [comment]
looks like it's fixed, thanks!
