### ISSUE TITLE
Consider using "go generate" to make Prometheus go-gettable

### ISSUE THREAD

**Issue by juliusv** [prometheus/prometheus#548]
See http://blog.golang.org/generate and https://github.com/prometheus/prometheus/issues/547#issuecomment-75430242.

This could obviate the need for Makefiles and make Prometheus go-gettable.

**Comment by beorn7** [comment]
But take into account that `go generate` is supposed to be run by developers and not by users, i.e. we have to check in the generated blob.go after all.

**Comment by juliusv** [comment]
Oh. Right, we could check in `files.go` (which you meant by `blob.go`), as we already check in protobufs and lexer/parser files.

So the only things really standing in the way of `go get` without any subsequent manual build steps are now:

- build.go (it should be user-generated by design, as otherwise it won't contain the correct build information)
- ensuring an up-to-date Go version

I think the latter is probably fine to ignore, because we already use the new range syntax which will at least fail for people still on Go <1.4. But what about build.go? Weighing the useful information it provides against go-gettability. Hmm...

**Comment by matthiasr** [comment]
Maybe include a generated `build.go` with some bogus (empty?) revision, but use a release process for official binaries that updates it?

**Comment by vtolstov** [comment]
usually software have step make dist, that pregenerates all needed files, so i think in release build.go can have released version...

**Comment by grobie** [comment]
So, reading the `go generate` documentation, I understand the concept that any program can be called. You could just call make, no? :D

```
//go:generate make generate build.go
```

**Comment by beorn7** [comment]
On Fri, Feb 27, 2015 at 5:48 AM, Tobias Schmidt
<notifications@github.com> wrote:
> So, reading the go generate documentation, I understand the concept that any
> program can be called. You could just call make, no? :D
>
> //go:generate make generate build.go

Yes, that's called the 'toilet paper principle'. :)

-- 
Björn Rabenstein, Engineer
http://soundcloud.com/brabenstein

SoundCloud Ltd. | Rheinsberger Str. 76/77, 10115 Berlin, Germany
Managing Director: Alexander Ljung | Incorporated in England & Wales
with Company No. 6343600 | Local Branch Office | AG Charlottenburg  |
HRB 110657B

**Comment by discordianfish** [comment]
It would be great to consent around how we do this, so we can make sure other prometheus projects do the same? The only concern with commiting the files.go is that it blows up the git history. Since we commit the protobuf generated code and Godeps anyways, I think it's fine to commit the files.go as well.

**Comment by brian-brazil** [comment]
Our binary data is checked in now, so this is resolved.
