### ISSUE TITLE
Does PromQL support automated reporting of designated sections?

### ISSUE THREAD

**Issue by wangchaoyu1992** [prometheus/prometheus#5490]
## Proposal
**Use case. Why is this important?**

*“Nice to have” is not a good use case. :)*

## Bug Report
**What did you do?**
 http_requests_total > 100 && 1=<day_of_week() <=5
This is not supported
**What did you expect to see?**
    from Monday to Friday, the number of HTTP requests is greater than 100.
    Alarm for HTTP requests greater than 50 from Saturday to Sunday
    Can PromQL do this? If you can write an example，Thanks.
**What did you see instead? Under which circumstances?**

**Environment**

* System information:

	insert output of `uname -srm` here

* Prometheus version:

	insert output of `prometheus --version` here

* Alertmanager version:

	insert output of `alertmanager --version` here (if relevant to the issue)

* Prometheus configuration file:
```
insert configuration here
```

* Alertmanager configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```

**Comment by simonpasquier** [comment]
You want: `http_requests_total > 100 and on() day_of_week(vector(time())) >= 1 and on() day_of_week(vector(time())) <= 5`.

I'm closing it for now. If you have further questions, please use our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search.
