### ISSUE TITLE
Collect metrics / scrape endpoints during WAL replay (startup before ready for querying)

### ISSUE THREAD

**Issue by JorritSalverda** [prometheus/prometheus#5495]
## Proposal

Collecting metrics by scraping endpoints during startup before Prometheus is ready to be queried reduces the gap in data that arises out of a restart possibly followed by repair, WAL replay and other actions happening during startup. Very likely to be hard to implement, but seems like a very good improvement.

**Use case. Why is this important?**

To shorten the gap in data and visibility of our platform. Startup can easily take 10 to 20 minutes for which time there's no data collection and even when Prometheus is queryable again after startup this gap remains.

**Comment by brian-brazil** [comment]
We can't ingest into the TSDB when the TSDB isn't ready, and that'd likely also cause weirdness with rules. Are you sure it's a repair, and not a WAL replay?

**Comment by JorritSalverda** [comment]
I already assumed it would be very complex.

What I see often is that the last logged repair.go line takes lone, see the difference in timestamps for the first 2 lines:

```
prometheus-1 prometheus level=info ts=2019-04-23T07:52:31.388Z caller=repair.go:47 component=tsdb msg="found healthy block" mint=1555992000000 maxt=1555999200000 ulid=01D94FX0C5S7WJ0M54AQ4JFPBQ
prometheus-1 prometheus level=warn ts=2019-04-23T07:58:03.864Z caller=head.go:454 component=tsdb msg="unknown series references" count=3389
prometheus-1 prometheus level=info ts=2019-04-23T07:58:09.145Z caller=main.go:655 msg="TSDB started"
prometheus-1 prometheus level=info ts=2019-04-23T07:58:09.145Z caller=main.go:724 msg="Loading configuration file" filename=/prometheus-config/prometheus.yml
```

I just upgraded from 2.8.0 to 2.9.1, so I hope we see less repairs in the future. The instances run on 14 cores, 50GB of ram and 2000GB pd-ssd disks on GKE. We've set retention to 7 days.

**Comment by brian-brazil** [comment]
That's WAL replay, repairs are only a one-off if you're on an older version.

**Comment by JorritSalverda** [comment]
Ah okay, I'll rephrase the issue to _during WAL replay_ then. Probably equally complex :)

**Comment by brian-brazil** [comment]
Yes, where would you put the metrics?

**Comment by JorritSalverda** [comment]
Some temporary WAL that can be merged into the actual WAL once it's ready? If it doesn't run alerting rules or querying (except for aggregation rules possibly) this might be feasible? If I start Prometheus with a clean slate it's up and running in seconds, writing data to the WAL, so thought this might be an option.

Once the WAL replay (and other startup actions) are done I can imagine that merging the temporary WAL into the actual WAL runs in the background while querying gets it information from an implementation that retrieves it from either place, a bit like this LongAdder class allows concurrent increments to trade memory for improved performance (just in spirit, not anything like this code):

https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/atomic/LongAdder.html

I do want to state that I don't know anything about how the WAL works, but nothing is impossible right? It's just a question of whether it's feasible.

**Comment by gouthamve** [comment]
We've looked into this during our bugscrub and we decided to close this as a wont-fix. Having said that we're looking into speeding up the WAL replay time (we've recently improved it a lot already) which should partially fix this already.

You should ideally look into HA.
