### ISSUE TITLE
Lifecycle API docs missing

### ISSUE THREAD

**Issue by SuperQ** [prometheus/prometheus#5497]
It seems like the docs for using the lifecycle admin API are missing from the `querying/api` section.

**Comment by brian-brazil** [comment]
Lifecycle isn't part of the /v1/api, so isn't on that page. https://prometheus.io/docs/prometheus/latest/configuration/configuration/ covers reloads.

**Comment by SuperQ** [comment]
The `quit` endpoint is missing documentation, so we should probably pick a better canonical place for the lifecycle API and reference that from configuration.

**Comment by pavansai1** [comment]
Hey, I'm interested in working on this issue :)

**Comment by brian-brazil** [comment]
They're on https://prometheus.io/docs/prometheus/latest/management_api/ these days, so this is already done afaics.
