### ISSUE TITLE
Data disk free space have a big decrease,then release in 12 minutes

### ISSUE THREAD

**Issue by jwongz** [prometheus/prometheus#5500]
## Bug Report
**What did you do?**
I have two physical servers, one of them have prometheus server in docker, the other have node_exporter , pushgateway , remote adapter and influxdb as remote storage in docker.

And the one which have node_exporter,data disk free space have a big decrease,then release in 12 minutes

* Prometheus version:

	v2.2.1

this will happened one time a week:
![image](https://user-images.githubusercontent.com/3717815/56637742-f6068880-669e-11e9-8739-920769b935a7.png)

In most of time:
![image](https://user-images.githubusercontent.com/3717815/56637777-0d457600-669f-11e9-8e87-1b712e61c5c4.png)

**Comment by simonpasquier** [comment]
I see nothing here that would indicate a problem with Prometheus or node_exporter. It seems legit that the disk's free space varies over time.

I'm closing it for now. If you have further questions, please use our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search.
