### ISSUE TITLE
Add access secret key auth in openstack discovery

### ISSUE THREAD

**Issue by zhongjun2** [prometheus/prometheus#5501]
## Proposal
The openstack discovery only support user/password to connect to cloud to get instance info. 
It could be insecure for cloud administrator. They have change the configuration in prometheus
if the password has been changed.
 
It would be good to add IAM(Identity and Access Management) in openstack discovery. You can
create an IAM user(new secret access key) that can do nearly anything that a root account can, then we only have to set secret access key in prometheus, not need to set user/password in prometheus.
The benefit of IAM is that you can control the permissions of an IAM user, or delete the user
altogether at any time.

**Comment by simonpasquier** [comment]
How is this be different from [application credentials](https://docs.openstack.org/keystone/queens/user/application_credentials.html) that are already supported both by Prometheus and the Keystone API?

**Comment by zhongjun2** [comment]
oh, the openstack already support application credentials in keystone and Prometheus. It also
support not need to set user/password in prometheus. 

The truly problem is huaweicloud cannot support access/secret key feature when we use openstack service discovery. 
Huaweicloud[1] is compatible with OpenStack API, so the user can just use openstack service discovery to connent
to huaweicloud when they want to use prometheus. But huaweicloud access/secret key feature is not compatible with
openstack application credentials feature, they have different encryption and decryption algorithm.

Cloud I just added a new discovery or added new access/secret key feature in openstack discovery?

Added a new huaweicloud discovery:
The only different between huaweicloud discovery and openstack discovery is Identity and Access Management feature.
Since the other new huaweicloud discovery APIs is compatible with openstack discovery, so we don't have to change current
Prometheus format, we don't have to do many tests. Is this easier to be accepted by the community?
 
Added new access/secret key feature in openstack discovery：
This way could be a little wired because the new feature is not belong to openstack.
 
[1]https://intl.huaweicloud.com/?locale=en-us

Hi @simonpasquier  What's your opinion?  Thank you!

**Comment by simonpasquier** [comment]
I'd be personally reluctant to add support for access & secret keys into the OpenStack service discovery givent that it isn't supported by the upstream community AFAICT. Which means that it should live as an external service discovery mechanism leveraging the file service discovery since we don't accept new integrations for now.

**Comment by gouthamve** [comment]
We've gone through this in our bugscrub and decided to close this issue as we only support official OpenStack APIs and this seems like a custom modification of the API. If this is supported upstream, we'd love to add it, please reopen the issue in that case.
