### ISSUE TITLE
Allow specifying maximum memory usage

### ISSUE THREAD

**Issue by matthiasr** [prometheus/prometheus#551]
The actual memory usage can not really be set predictably through `storage.local.memory-chunks` alone. To operate a Prometheus reliably, it would me much nicer to just say "you can use this much memory". It should be able to figure out by itself what that means in terms of chunks or allocations.

It would be good if this is a hard limit (including all other memory uses) but a best effort would already help a lot (together with rules of thumb on overhead).

The default should be a sensible fraction of available system memory, or some fixed number, whichever is lower.

**Comment by beorn7** [comment]
See 
https://github.com/prometheus/prometheus/issues/455
