### ISSUE TITLE
Backport tsdb v0.7.1 to prometheus release-2.2

### ISSUE THREAD

**Issue by liuliqiang** [prometheus/prometheus#5511]
## Proposal

We are using a nfs file system to storage prometheus data. However, this nfs system not support all nfs feature and we can't upgrade our prometheus from v2.2.1 -> v2.3.0，for v2.3.0 we would get a error like this:

```
level=info ts=2019-04-25T07:26:42.163002142Z caller=main.go:412 msg="Notify discovery manager stopped"
level=info ts=2019-04-25T07:26:42.163011785Z caller=main.go:588 msg="Notifier manager stopped"
level=info ts=2019-04-25T07:26:42.163023391Z caller=main.go:398 msg="Scrape discovery manager stopped"
level=error ts=2019-04-25T07:26:42.163111118Z caller=main.go:597 err="Opening storage failed lock DB directory: permission denied"
```

So, we are still using prometheus v2.2.1。But as the time go，we find a bug approved along with [Unknown series references in WAL after crash](https://github.com/prometheus/tsdb/issues/21)，so we hope whether prometheus branch release-2.2 can backport this patch and fix the problem。

## Bug Report
**What did you do?**

Running prometheus v2.2.1 with a nfs file system for storing data.

**What did you expect to see?**

when exists unknown series references in WAL samples, keep the series references。
And backport tsdb v0.7.1 to prometheus **release-2.2** branch。

**What did you see instead? Under which circumstances?**

the logs show following

```
level=info ts=2019-04-25T07:48:43.196185867Z caller=web.go:382 component=web msg="Start listening for connections" address=0.0.0.0:9090
level=info ts=2019-04-25T07:48:43.196192061Z caller=main.go:504 msg="Starting TSDB ..."
level=warn ts=2019-04-25T07:48:44.098411172Z caller=head.go:320 component=tsdb msg="unknown series references in WAL samples" count=609875
```

and it would cause：

```
level=error ts=2019-04-25T07:56:13.695858467Z caller=db.go:281 component=tsdb msg="compaction failed" err="persist head block: write compaction: add series: out-of-order series added with label set \"{__name__=\\\"node_bmc_compatibility:avg1h\\\",_firmware_revision=\\\"3.19\\\",_host=\\\"9cdb2928-85a8-11e8-9396-52540075da0d\\\",_manufacturer_name=\\\"supermicro\\\",_product_id=\\\"1588\\\",hostname=\\\"vm19\\\",role=\\\"master\\\"}\""
```

**Environment**

* System information:

```
# uname -srm
Linux 3.10.0-693.11.6.el7.smartx.1.x86_64 x86_64
```

* Prometheus version:

```
prometheus --version
prometheus, version 2.2.1 (branch: HEAD, revision: bc6058c81272a8d938c05e75607371284236aadc)
  build user:       root@149e5b3f0829
  build date:       20180314-14:15:45
  go version:       go1.10
```

**Comment by simonpasquier** [comment]
We usually only support the current stable release (2.9 as of now) so I don't see that we'll update the `release-2.2` branch.

I'm closing it for now. If you have further questions, please use our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search.
