### ISSUE TITLE
Adding `text/plain` as the final accept header fallback

### ISSUE THREAD

**Issue by rdohms** [prometheus/prometheus#5521]
## Add `text/plain` fallback
Currently the prometheus accept header lists, the open metrics standard, plain/text v.0.0.4 and "anything". 

In content negotiation a match of `plain/text;version=0.0.4` on a server that offers `plain/text` does not match and fallsback to the server default, which most APIs have as `application/json`.

This is usually not a problem, but it means that if Prometheus does change v0.0.4 to v0.0.5 and we do not add that specific header, we would fallback to json, not plain/text.

### Option 1
My suggestion would be to add a `plain/text` fallback before the `*/*` match, so that at the very least we get a readable output and not a json encoded string.

`application/openmetrics-text; version=0.0.1,text/plain;version=0.0.4;q=0.5,text/plain;q=0.2,*/*;q=0.1`

### Option 2
Remove the `*/*` match so at least we get a hard 406 fail we can track easier over logs and such.

`application/openmetrics-text; version=0.0.1,text/plain;version=0.0.4;q=0.5`

What do you think of this?

**Comment by brian-brazil** [comment]
This would be a breaking change for many users, and `text/plain;version=0.0.4` is the correct content type that clients exposing Prometheus-formatted metrics should be using.

**Comment by rdohms** [comment]
@brian-brazil I do agree with that statement, but you cannot handle `*/*` and it can lead to silent failures, would it not be better to have a more controlled fallback path?

I'm curious why you consider it a breaking change, as it would only change if the APIs were serving `plain/text` and thus would continue serving the same. Would love to explore the conditions that could break a bit more, i think i may be missing something you are seeing.

**Comment by brian-brazil** [comment]
The thing is that readable output doesn't help us, we need the Prometheus text format.

**Comment by rdohms** [comment]
@brian-brazil I understand that, but `*/*` is also not guaranteeing that for you.

**Comment by brian-brazil** [comment]
No, but if you give us something we'll try to parse it. Which particular server are you having problems doing correct content negotiation on?

**Comment by roidelapluie** [comment]
> This is usually not a problem, but it means that if Prometheus does change v0.0.4 to v0.0.5 and we do not add that specific header, we would fallback to json, not plain/text.

If we switch we would accept both:

`plain/text;version=0.0.5,plain/text;version=0.0.4`

I think we can close this issue.

**Comment by brian-brazil** [comment]
Agreed, there's nothing to change here.
