### ISSUE TITLE
storage.remote.Storage appender no longer usable without local tsdb+WAL

### ISSUE THREAD

**Issue by jacksontj** [prometheus/prometheus#5523]
## Proposal
**Use case. Why is this important?**
The remote clients (read/write) in the prometheus repo are the primary clients that others use to integrate with prometheus as it stands today. With the recent change to remote_write (https://github.com/prometheus/prometheus/pull/4588) the remote.Storage struct now no-longer is standalone, it now requires that you run a local tsdb for the appender to function. This now means if I want to continue using remote_write in my other applications I need to either (1) fork an old version of the client to maintain or (2) re-implement the queuing+client myself. Both seem less than ideal.

Regardless of the specific for this client package, this definitely seems like a break in isolation of packages, since this remote storage client now only knows how to tail from a WAL file (instead of getting the data through the appender interface as it did before).

**Comment by cstyan** [comment]
I don't think we give any guarantee for stability of the remote read or write interfaces, as far as I remember it's all still marked beta but maybe @tomwilkie or @gouthamve can chime in.

Without some more refactoring there isn't really a nice way to have remote write continue to get samples via the appender interface and have those samples come from the WAL watcher. The appender interface is tied in to metrics scrapping.

That being said, we're still planning to do more work on the new remote write code. As part of that I can look into restoring the old behaviour but still have Prometheus get samples for remote write from the WAL.

**Comment by brian-brazil** [comment]
There's none for remote read/write, though there's no plans to break it currently as far as I know.

However this bug is not about that, it's about our internal APIs which we have no guarantees for at all in order to enable us to make changes like this, and avoid ossifying.

**Comment by cstyan** [comment]
Agreed. AFAIK we just a have a loose guarantee that the actual format of the remote write/read data won't change so that we don't break those who have written integrations, such as Influx.

**Comment by brian-brazil** [comment]
The consensus was that we'd change it (once) to something better, though I think we're now looking at sticking with what we have protocol-wise.

My personal expectation is that anyone who needs something more efficient would implement their own wal-reading sidecar, as there's actual protocol stuff there which is going to vary based on backend.

**Comment by jacksontj** [comment]
> However this bug is not about that, it's about our internal APIs which we have no guarantees for at all in order to enable us to make changes like this, and avoid ossifying.

So to clarify here, the remote storage client in the prometheus repo is not meant as a client for anything outside of prometheus to use? The main problem here is that this was the *only* remote read/write client in existence, so people (including myself) started using it. This change effectively breaks it -- not because of a protocol change (which I'd be okay with, since there'd be a potential benefit) -- but instead because the writer *assumes* we have a local TSDB to read from. So what this has done is taken the only remote read/write client in go and made it *only* useful for prometheus.

IMO a better solution to this would have been more inline with:

> My personal expectation is that anyone who needs something more efficient would implement their own wal-reading sidecar, as there's actual protocol stuff there which is going to vary based on backend.

meaning that the remote client should have remained the same, and if prometheus needed a different way of *getting* data -- it should have a separate package for getting it.

**Comment by brian-brazil** [comment]
> So to clarify here, the remote storage client in the prometheus repo is not meant as a client for anything outside of prometheus to use?

Yes, it's an internal library.

**Comment by jacksontj** [comment]
So the next question is when will there be a client for this? Since
apparently the one in the Prometheus repo is not meant for others to use

**Comment by cstyan** [comment]
You're referring to a reusable client that functions the same as Prometheus' remote read/write clients but has stability guarantees and is meant to be used outside Prometheus itself?

I don't think we have any plans to write something like that.

Remote read and write are built to be used from Prometheus. They're meant to allow Prometheus to gain access to information in another data store and to write it's own data somewhere else as well. They're not general purpose libraries.

**Comment by bboreham** [comment]
For testing purposes I created this `remote_write` client: https://github.com/open-fresh/avalanche/blob/master/metrics/write.go

No stability guarantees there either, but the whole file is only 185 lines, which may encourage you.

**Comment by brian-brazil** [comment]
#5624 may be of interest
