### ISSUE TITLE
Documentation link for Remote write integration to ElasticSearch is not correct

### ISSUE THREAD

**Issue by tejaswiniVadlamudi** [prometheus/prometheus#5528]
Documentation(v2.9) bug in [remote-endpoints-and-storage](https://prometheus.io/docs/operating/integrations/#remote-endpoints-and-storage) section not pointing to correct integration for Elasticsearch.

As now it is pointing to [metricbeat](https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-module-prometheus.html) which scrapes Prometheus instead of remote-write feature.

Please correct me if I am wrong.

Thanks in Advance.

**Comment by brian-brazil** [comment]
Would you like to send a PR for the right location?

**Comment by tejaswiniVadlamudi** [comment]
I just tried to check remote write feature with elasticsearch backend, but current link points to usage /federate endpoint using metricbeat. It might be good if the owner of such adapter comments here.
I guess Prometheus beat to be linked here. Is it so?

**Comment by brian-brazil** [comment]
If there isn't actually a remote write integration, then we should remove the entry. I see a few out there from a quick search though.

**Comment by tejaswiniVadlamudi** [comment]
Do we have any update here? If elastic-search is not recommended/applicable to use, maybe we can remove it from the documentation.
