### ISSUE TITLE
Alarm based on (prometheus_notifications_dropped_total) is fired after config reload

### ISSUE THREAD

**Issue by dhbarman** [prometheus/prometheus#5530]
## Proposal
We generate a metric - prometheus_notifications_dropped_delta1m - every minute as follows:
delta(prometheus_notifications_dropped_total{{instance=~"{hostname}.*"}}[1m])

Based on this metric, if the value is > 0 in 60 seconds, we create an alarm.
We observe that - every time we do config re-load, this alarm gets fired. 

## Bug Report
**What did you do?**

Reloaded a new config 

**What did you expect to see?**

Did not expect to see any alarm based on prometheus_notifications_dropped_total after config reload. 

**What did you see instead? Under which circumstances?**

Alarm got fired. 

**Environment**

* System information:

	Linux 4.1.12-124.26.7.el7uek.x86_64 x86_64

* Prometheus version:

bash-4.2# ./prometheus --version
  prometheus, version 2.4.3 (branch: heads/v2.4.3, revision: e22cd181776b7d10907d7776b0e8f0e66ddbaf37)
  build user:       teamcity@tca-hv08-agent044-default
  build date:       20190417-22:33:28
  go version:       go1.11.5

* Alertmanager version:

	alertmanager --version
alertmanager, version 0.15.3 (branch: 0.15.3, revision: 5d75a50792d2e6615ed5045386509b03bc11992a)
  build user:       teamcity@tca-hv05-agent052-default
  build date:       20190424-02:24:16
  go version:       go1.12.4

* Logs:
```
level=info ts=2019-05-02T20:40:01.90019621Z caller=main.go:624 msg="Loading configuration file" filename=/config/sea-unstable/prometheus.yml
level=info ts=2019-05-02T20:40:01.903205383Z caller=queue_manager.go:258 component=remote queue=0:http://localhost:8185/timeseries/write msg="Stopping remote storage..."
level=info ts=2019-05-02T20:40:01.903259618Z caller=queue_manager.go:266 component=remote queue=0:http://localhost:8185/timeseries/write msg="Remote storage stopped."
level=info ts=2019-05-02T20:40:01.921821598Z caller=main.go:650 msg="Completed loading of configuration file" filename=/config/sea-unstable/prometheus.yml
level=info ts=2019-05-02T21:00:16.281365329Z caller=compact.go:398 component=tsdb msg="write block" mint=1556820000000 maxt=1556827200000 ulid=01D9X5HJAAKZK4XN6XWVAWF82C
level=info ts=2019-05-02T21:00:18.487084118Z caller=head.go:446 component=tsdb msg="head GC completed" duration=925.680397ms
level=info ts=2019-05-02T21:00:26.541605487Z caller=head.go:477 component=tsdb msg="WAL checkpoint complete" low=7890 high=7900 duration=8.054419426s
level=info ts=2019-05-02T21:00:41.676816393Z caller=compact.go:352 component=tsdb msg="compact blocks" count=3 mint=1556798400000 maxt=1556820000000 ulid=01D9X5JDCCSQ432FRDTWPX3WP8 sources="[01D9WGYCJ7HEGQ1VNKYRWETP2G 01D9WQT3T7T495ABCET746X855 01D9WYNV27M9MR47WF3YHFW54D]"

```

**Comment by simonpasquier** [comment]
Closing for now as the discussion happens on the mailing list: https://groups.google.com/d/msg/prometheus-developers/vfRS3D_b_v8/2UdMotJdAwAJ
