### ISSUE TITLE
Allow targets to be grouped by arbitrary labels in the UI

### ISSUE THREAD

**Issue by simonpasquier** [prometheus/prometheus#5532]
Since https://github.com/prometheus/prometheus/pull/4898, targets are grouped by their scrape configuration. Before that, they were grouped by `job` label. It has come up a couple of times that having more flexibility would be useful:
* https://github.com/prometheus/prometheus/pull/4898#issuecomment-443229804
* https://groups.google.com/d/msg/prometheus-users/ySU-X6KuAHM/h2OVIOwXAAAJ

**Comment by pbhudiaBAE** [comment]
I can have a look into this

**Comment by pbhudiaBAE** [comment]
Correct me if I'm wrong but is the proposal to have label based filtering per target so that endpoints within a target get filtered based on labels that users can choose.

**Comment by Yagyansh** [comment]
Has any progress been made on this?

**Comment by anuraagbarde** [comment]
Can I work on this? New contributor here :)

**Comment by krajorama** [comment]
Hello from the bug scrub: the current target page looks completely different by now. Please open a new issue on the latest target page if this is still an issue to be solved.
