### ISSUE TITLE
AND operator precedence is too high

### ISSUE THREAD

**Issue by aecolley** [prometheus/prometheus#555]
The expression:
`time() - start_time{job="x"} > 86400`
&nbsp;&nbsp;&nbsp;&nbsp;`and`
`start_time{job="x"} > end_time{job="x"}`

should be parsed as:
`(time() - start_time{job="x"} > 86400)`
&nbsp;&nbsp;&nbsp;&nbsp;`and`
`(start_time{job="x"} > end_time{job="x"})`

but it is actually parsed as:
`((time() - start_time{job="x"} > 86400)`
&nbsp;&nbsp;&nbsp;&nbsp;`and`
`start_time{job="x"}) > end_time{job="x"}`

**rules/lexer.l** classifies `AND` and `OR` as CMP_OP just like `==` and `>`. They should be a different level of operation.

**Comment by juliusv** [comment]
Thanks for reporting! I agree, this should be changed.

**Comment by atombender** [comment]
+1. This bit me today. At the very least the current precedence should be documented.

**Comment by juliusv** [comment]
This will be fixed along with the parser / query engine refactoring that is likely to be done in the next couple of weeks.

**Comment by juliusv** [comment]
Just merged the new query engine + parser feature branch into master: https://github.com/prometheus/prometheus/pull/676

This should be fixed now.
