### ISSUE TITLE
Alert templates type conflict: SampleValue v. float64

### ISSUE THREAD

**Issue by aecolley** [prometheus/prometheus#556]
Attempts to interpolate `{{humanizeDuration $value}}` fail with a type error:

> wrong type for value; expected float64; got model.SampleValue

There's no way to work around this.

**Comment by brian-brazil** [comment]
Hmm, try `{{value $value | humanizeDuration}}`

**Comment by brian-brazil** [comment]
Ah, it's a casting problem. We need to cast to float64 in https://github.com/prometheus/prometheus/blob/5f27629985520bc4dce469d66308db7c922e080c/rules/manager/manager.go#L177

**Comment by juliusv** [comment]
One thing to watch out for when changing this: we currently have a nice `String()` method for serializing `clientmodel.SampleValue`:

https://github.com/prometheus/client_golang/blob/master/model/samplevalue.go#L35-L37

If we cast everything to `float64`, then the default string representation will look less nice for many use cases. For example, timestamps will by default be printed in scientific notation (`1.413989023e+09`) and shenanigans like that.
