### ISSUE TITLE
Kubernetes service discovery for initContainers

### ISSUE THREAD

**Issue by Kuqd** [prometheus/prometheus#5563]
## Proposal

The current Kubernetes service discovery implementation totally disregard initContainers.

https://github.com/prometheus/prometheus/blob/master/discovery/kubernetes/pod.go#L216

This would be useful to have them scrape because:
- they may contain troubleshooting information.
- We could detect problems.
- We might want to observe how long initialization took.

Originally the problem appeared from https://github.com/grafana/loki/issues/575  while for metrics it is arguable that you might need this, for logs there is no question.

Alternatives could be to create a custom service discovery. /cc @gouthamve

**Comment by gouthamve** [comment]
If we do scrape them, how to deal with them if they die? Is that target going to be down forever? /cc @brancz?

**Comment by brancz** [comment]
Yes, init containers must complete before the "normal" containers are started. And yes they will be down forever once they complete, if not removed from discovery once they complete (which should be possible with discovery information from its status). Generally speaking though from the Prometheus perspective init containers can run for some time, and monitoring team would still be useful.
