### ISSUE TITLE
Support for mips64 builds ？

### ISSUE THREAD

**Issue by ysicing** [prometheus/prometheus#5566]
I try to build Prometheus 2.2.1 or master from source on mips64 (NeoKylin Military Server 7.0).
I tried two ways to build binaries, but in the end I couldn't execute the binaries.

1.  use [golang-builder](https://github.com/prometheus/golang-builder)

```
docker run --rm -ti -v $(pwd):/app quay.io/prometheus/golang-builder:mips     -i "github.com/prometheus/prometheus"     -p "linux/mips64"
```
2. use make build
```
# go version go1.12.5 linux/mips64le
GOOS="linux" GOARCH="mips64" make PREFIX=".build/linux-mips64" build
```

Run the binary, as shown below

```
[root@localhost linux-mips64]# ls
prometheus  promtool
[root@localhost linux-mips64]# ./prometheus
-bash: ./prometheus: unable to execute binary
```

Could you provide your opinion/suggestions on the same?

**Comment by ysicing** [comment]
I tried the following, and found that the built binary works. There seems to be no other problem 

```
GOOS="linux" GOARCH="mips64le" make PREFIX=".build/linux-mips64le" build
```

**Comment by qiyongxiao** [comment]
Could it run on mips64le with the second way build?
```
GOOS="linux" GOARCH="mips64le" make PREFIX=".build/linux-mips64le" build
```

**Comment by ysicing** [comment]
@qiyongxiao  Of course it works.

**Comment by qiyongxiao** [comment]
> @qiyongxiao Of course it works.

Oh, thanks!!!! I have build it for mips64 and run normally
