### ISSUE TITLE
Prometheus Hardware Requirements 

### ISSUE THREAD

**Issue by gammohamed** [prometheus/prometheus#5579]
Prometheus Hardware Requirements

In order to design scalable & reliable Prometheus Monitoring Solution, what is the recommended Hardware Requirements  " CPU,Storage,RAM"  and how it is scaled according to the solution.

Please provide your Opinion and if you have any docs, books, references..

**Comment by simonpasquier** [comment]
Storage is already discussed in the [documentation](https://prometheus.io/docs/prometheus/latest/storage/). To avoid duplicates, I'm closing this issue in favor of https://github.com/prometheus/prometheus/issues/5469.
