### ISSUE TITLE
Prometheus stops scraping when insufficient memory 

### ISSUE THREAD

**Issue by woodsaj** [prometheus/prometheus#5585]
**What did you do?**
The node that the Prometheus pod was running on ran out of memory (due to another job consuming it all).  

**What did you expect to see?**
An error (not warning) log message when memory could not be allocated.
Instead of silently failing, Prometheus should either try and recover or crash.

**What did you see instead? Under which circumstances?**
When the memory exhaustion was encountered prometheus stopped scraping metrics, but was otherwise online and responding.

**Environment**
Running as a pod in Kubernetes

* Prometheus version:

|   |   |
|-------|--------|
| Version     | 2.9.2 |
| Revision   | d3245f15022551c6fc8281766ea62db4d71e2747 |
| Branch      | HEAD   |
| BuildUser  | root@1d43b6951e8f |
| BuildDate  | 20190424-15:32:31 |
| GoVersion | go1.12.4 |

* Logs:
```
level=warn ts=2019-05-21T05:08:22.701Z caller=scrape.go:937 component="scrape manager" scrape_pool=kubernetes-pods target=http://10.40.1.20:80/metrics msg="append failed" err="write to WAL: log samples: write /prometheus/data/wal/00002922: cannot allocate memory"
```

**Comment by gouthamve** [comment]
We decided to close this as a wont-fix. You should use meta-monitoring to catch this (alerting on scrapes failing for ex.) This is ideally done by having another Prometheus monitoring it.
