### ISSUE TITLE
irate() strange behavior when values stepping is not the default scrap interval

### ISSUE THREAD

**Issue by hekmon** [prometheus/prometheus#5591]
Considering the following PromQL request:
`base_cpu_times{hostname="$hostname", mode="idle"}`

Yielding the following values:
```
values:Array[8]
0:Array[1558252710,10633786.735]
1:Array[1558252740,10633816.69]
2:Array[1558252770,10633846.635]
3:Array[1558252800,10633876.575]
4:Array[1558252830,10633906.524999999]
5:Array[1558252860,10633936.47]
6:Array[1558252890,10633966.42]
7:Array[1558252920,10633996.365]
```

And now the same query, with irate:
`irate(base_cpu_times{hostname="$hostname", mode="idle"}[$__interval])`

Yielding:
```
0:Array[1558252710,0.9976666666567325]
1:Array[1558252740,0.9985000000024835]
2:Array[1558252770,0.9981666666766008]
3:Array[1558252800,0.9979999999826153]
4:Array[1558252830,3.195135826765516]
5:Array[1558252860,3.194424690782829]
6:Array[1558252890,3.19442469051791]
7:Array[1558252920,3.193713554270304]
```

Starting with the 4th sample, irate is going postal. The only thing I can think of is the difference of the scrapping interval (15s) and the actual distance between samples (30s). Does it influence extrapolation or reset detection of the irate function ?

Anyway the 4th sample should not it be:
(10633906.524999999 - 10633876.575) / (1558252830 - 1558252800) = 0,9983333333 ?

**Comment by beorn7** [comment]
The timestamps you are seeing here are the timestamps for which samples are queried. Those are _not_ the timestamps of the individual samples in the TSDB. You have to look at those to check the irate calculation for correctness.

What do you get with `rate` instead of `irate`? If you work with `$__interval` (which is a Grafana feature rather than a Prometheus one), that should in general be the better choice.

In general, it's unlikely that you have hit a bug. This looks more like a support request, which are much better handled on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by hekmon** [comment]
These timestamps are outside the prometheus TSDB retention and come from an InfluxDB remote read so they actually are the real values (confirmed with an InfluxDB query).

Because influxdb downsamples our metrics, we need to use `irate` which will only take the first 2 values no matter if we use [60s] or [1h]. Using `rate` would change the behavior: this could use more than 2 points. We want the instant rate of the last two points, no matter if they have 15s, 30s or 1min between them so `rate` is not the right function for this case.

Just to be clear, results are exactly the same with [60s] instead of `[$__interval]` (which you are right, I should have test & post without it from the beginning).

But this is not a support request: I extracted the raw data, I computed the irate myself and `irate` just does not yield the right values. Even if it does 99% of the times we are still seeing from time to time these weird results. Actually in my example `irate` got the right values from 0 to 3 even if the stepping was 30s and not the original 15s.

Each values has a 30s stepping, `irate` compute the right values most of the time but in some cases (like this one) it yields something far too big: here 3.195135826765516 instead of 0.9983333333. This is a bug to me: with an instant rate of 3.195135826765516 at sample 4, its raw value would actually have to be 10633972.4291 not 10633906.524999999.

If you think this is not a bug, feel free to close this issue.

**Comment by beorn7** [comment]
Hmm, this sounds weird. It would be great if we could somehow reproduce the behavior in a simple setup. Then we could play with it and find out if it is really a bug or not.

If the timestamps are really all aligned (which is a rather artificial situation), I could wildly guess that it has to do with float equality, i.e. the query might sometimes query something a tad before the timestamp of the sample you want to include, and then it includes two samples further from the past.

But really hard to say, just looking at it from the distance.

**Comment by beorn7** [comment]
Perhaps it's some weird interaction with the remote read interface. I'm not very familiar with that.

**Comment by brian-brazil** [comment]
An instant query can't return a range vector result, so the initial data
must be query_range. See
https://www.robustperception.io/extracting-raw-samples-from-prometheus

**Comment by hekmon** [comment]
We found a workaround for now: instead of doing `1-irate({...mode="idle"}[60s])`, which results in negative %, we do the inverse `sum by (instance, cpu_id) (irate({...mode!="idle}[60s])"` which does not trigger the weird `irate` values.

Unfortunately the retention policies holding these values just dropped them and I only have our grafana query inspector dumps. We will monitor for this bug to appear again and I will update this issue with the raw values the prometheus API returns directly using the technique to extract raw values Brian linked.

With these data I hope you will have enough to reopen this issue.

Thank you for your answers.

**Comment by hekmon** [comment]
Just got a new one:

```
# Query range
POST https://<prometheus>:9091/api/v1/query_range
## BODY
query=1-irate(base_cpu_times%7Bjob%3D%22sys%22%2C%20hostname%3D%22<hostname>%22%2C%20mode%3D%22idle%22%7D%5B1m%5D)&start=1558489740&end=1558519920&step=60
## ANSWER
query_range.json
```

Irate wrong values start at 1558497660 and goes back to normal at 1558512060.
Here the raw values using Brain's technique:

```
# Query
https://<prometheus>:9091/api/v1/query?query=base_cpu_times{job=%22sys%22,hostname=%22<hostname>%22,mode=%22idle%22}[72h]
## ANSWER
query_raw.json
```

Answers & graf in the attached [prombug.zip](https://github.com/prometheus/prometheus/files/3216100/prombug.zip)

**Comment by mozai** [comment]
May be related to something weird I'm seeing, where the rate() produces some bizarre numbers, and not just with a cpu counter (node_cpu_seconds_total) but I see it with a network packets counter (node_network_transmit_bytes_total) too.  I'm using the same scrape interval for all jobs though.

Using curl to get raw numbers, I can see two measurements 5 minutes apart are [1558713540,"45196691.74"] and [1558713735,"45196930.72"]
I'd expect the rate() over that time to be (45196930.72 - 45196691.74) / (1558713735 - 1558713540) = 1.2 or thereabouts.
Instead I'm seeing [1558713735,"163471.25667385952"] for the rate() query.

![sshot 2019-05-24 png](https://user-images.githubusercontent.com/2396738/58345804-42bcbb00-7e27-11e9-84e3-e479f328251a.png)

**Comment by beorn7** [comment]
@mozai You haven't posted your curl query, but I assume you are _not_ looking at raw numbers. See https://www.robustperception.io/extracting-raw-samples-from-prometheus , what @brian-brazil said above.

As written on the mailing list: “I vaguely remember that some kernel versions had a bug reporting the
idle CPU seconds. You could try to avoid `{mode="idle"}` and instead
sum up all the metrics where `{mode!="idle"}`. If that creates a
different result, it's probably the idle cpu counter to blame. (For
example, if it drops slightly, Prometheus will see that as a counter
reset.)”

**Comment by beorn7** [comment]
@hekmon Your query_range query looks at different metrics (`mode!="idle"`) than the raw query (`mode="idle"`). To debug the `irate` calculation, we need the data for exactly the same underlying metric

**Comment by beorn7** [comment]
@mozai Do you have remote read as part of your setup, too?

**Comment by hekmon** [comment]
@beorn7 I'm not sure which query range your are referring to. I just double checked the `query_range` and the `raw_query` from my last msg and both use `mode="idle"` whether in the message or the zip archive. What am I missing ?

**Comment by beorn7** [comment]
Sorry, my bad. My brain unescaped wrongly. :o)

Then, indeed, the result you are seeing cannot be explained from the data queried. I still don't think that `irate` is implemented wrongly. That bug would have shown up a million times over the last five years. My best guess is that it has to do with remote read. Perhaps the data queried from the remote read backend is slightly different from within the `irate` evaluation compared to retrieving the raw counter directly. However, I'm not very familiar with the internals of the remote read interface. Perhaps @juliusv can guess in a more educated fashion?

**Comment by beorn7** [comment]
Still guessing: When querying the raw counter, remote read is probably requesting exactly the stepping required to respond for the query. However, when evaluating the `irate`, it will request the actual last and 2nd to last sample, which might be of a higher resolution. Guessing 2nd order: In that time range where you see the crazy values for the `irate`, you might have two different series under the same label set in your storage backend with a slight shift in timestamp. The `irate` evaluation sees a sample from the one and the other series, and they are wildly different. For the direct counter retrieval, the stepping happens to pick only the samples of the one series.

**Comment by hekmon** [comment]
Here is all I can add:
* I extracted raw values from InfluxDB they are identical to the one extracted found with brian's technique ([influx_github.zip](https://github.com/prometheus/prometheus/files/3219396/influx_github.zip))
* prometheus is using 15s scraping
* this remote read is on a different RP (retention policy) than the default (used by the remote write)
* this RP is using 30s downsampled values
* we are using InfluxDB officials [remote read/write connectors](https://docs.influxdata.com/influxdb/v1.7/supported_protocols/prometheus/)

**Comment by brian-brazil** [comment]
Hmm, what does resets() on this series show?

**Comment by hekmon** [comment]
Mmmm. I went back to grafana to try the `resets()` fx on the exact same timerange but:
![image](https://user-images.githubusercontent.com/3418467/58371366-f5b51380-7f10-11e9-8582-d879fba79025.png)

Everything looks normal now. I checked, we are still on the same retention policy, no change of data from remote read. I just don't get it. (still tried `resets()` but as expected, flat line of 0s)

I guess I will have to wait for another occurrence and this time get:
* query_range
* query_raw
* resets() results

Anything else I should do next time this bug manifests to provide more debug material ?

**Comment by beorn7** [comment]
Next thing I would do is probably checking out what Prometheus and InfluxDB are talking to each other, if need be tcpdump what's on the wire.

**Comment by hekmon** [comment]
New one (see [prombug_v2.zip](https://github.com/prometheus/prometheus/files/3224347/prombug_v2.zip)). I also have the pcap between prom & influx but as it is not sanitized I won't publish it here (will send it privately).

I made the extraction few hours ago and by going back to grafana before posting all the data here, I spotted something interesting: the bug is still present but not on the same time range. Extraction had the bug between 12h & 16h 2 days ago and now the bug is between 14h & 18h (still 2 days ago) (it is 17h40 here).

And because prometheus retention is set to 2 days... I'm guessing: overlap between the last data of prometheus and the data from influxdb ?

**Comment by mozai** [comment]
> You haven't posted your curl query, but I assume you are not looking at raw numbers.
I did double-check with raw numbers, I felt the screenshot would be easier to digest than 50kB of JSON objects.  Easy enough to fetch more data.
[prometheus_rate_function_weird.txt](https://github.com/prometheus/prometheus/files/3224510/prometheus_rate_function_weird.txt)

I see similar results if I use rate(), irate() or increase().  Starting to think I should be filing my own bug report not ridin on someone else's.

**Comment by beorn7** [comment]
It really sounds like an interaction between remote and local data. I'm really not an expert in this area. I'd appreciate if those more deeply involved with the remote read/write interfaces would get to the bottom of this. (@juliusv is the maintainer for this code part.)

**Comment by juliusv** [comment]
I think @tomwilkie would be the right person here (and I think he also wanted to become the maintainer for remote read/write?).

**Comment by krajorama** [comment]
Hello from the bug scrub: since this issue has been stale for a number of years we're closing it. Please reopen if there is new evidence.
