### ISSUE TITLE
Multiple Prometheus in one cluster

### ISSUE THREAD

**Issue by rks1212** [prometheus/prometheus#5600]
Hi Experts,

**Requirement:**

I am working on a request to configure two different sets of Prometheus / Alert Managers and Grafana Dashboards (one for application level metrics and second one for platform level, since there are different parties managing the alerts and resolutions)

**Current Situation:**

Prometheus for Application Metrics has already been provisioned which need not be modified at all as requested by the application owners. 
When I try to deploy second set of Prometheus / Alert Managers and Grafana Dashboards (with different NS, SA, Secrets etc), I am able to deploy but it impacts first deployment by removing prometheus pods and alert manager stateful set. 

**Issue:**

- Please suggest if there is a best practice / tested way to configure multiple parallel instances on a same K8s Cluster (hosting prometheus outside K8s cluster is not feasible)

- Is it an expected behaviour to have only one alert manager working on one K8s cluster ?

- Any reference links / yamls ?

**Environment:**

Ravis-MacBook-Pro-2:kube-prometheus ravi$ kubectl get pods -n  mngmt-monitoring
NAME                                       READY   STATUS    RESTARTS   AGE
grafana-cd485c98c-mpd87                    1/1     Running   0          58m
kube-state-metrics-66f4b77ddc-szww6        4/4     Running   0          58m
node-exporter-7hx9c                        2/2     Running   0          58m
node-exporter-chhsr                        2/2     Running   0          58m
node-exporter-g2blb                        2/2     Running   0          58m
node-exporter-hjjj8                        2/2     Running   0          58m
node-exporter-rzq5f                        2/2     Running   0          58m
node-exporter-trwnn                        2/2     Running   0          58m
prometheus-adapter-iscp-56fdcd895c-zpx8q   1/1     Running   0          58m
prometheus-operator-575987ffdf-wdgnk       1/1     Running   0          58m
Ravis-MacBook-Pro-2:kube-prometheus ravi$ kubectl get pods -n monitoring
NAME                                   READY   STATUS    RESTARTS   AGE
alertmanager-main-0                    2/2     Running   0          28s
alertmanager-main-1                    2/2     Running   0          23s
alertmanager-main-2                    2/2     Running   0          15s
grafana-fc6fc6f58-tc8jn                1/1     Running   0          68s
kube-state-metrics-6d8474895b-rtjkf    4/4     Running   0          22s
node-exporter-4fwbv                    2/2     Running   0          67s
node-exporter-7jp97                    2/2     Running   0          67s
node-exporter-krm8b                    2/2     Running   0          67s
node-exporter-rx9p5                    2/2     Running   0          67s
node-exporter-skcwj                    2/2     Running   0          67s
node-exporter-zzjw4                    2/2     Running   0          67s
prometheus-adapter-66fc7797fd-xkdkv    1/1     Running   0          67s
prometheus-k8s-0                       3/3     Running   1          21s
prometheus-k8s-1                       3/3     Running   1          21s
prometheus-operator-7cb68545c6-66778   1/1     Running   2          69s

## Proposal
**Use case. Why is this important?**

*“Nice to have” is not a good use case. :)*

## Bug Report
**What did you do?**

**What did you expect to see?**

**What did you see instead? Under which circumstances?**

**Environment**

* System information:

	insert output of `uname -srm` here

* Prometheus version:

	insert output of `prometheus --version` here

* Alertmanager version:

	insert output of `alertmanager --version` here (if relevant to the issue)

* Prometheus configuration file:
```
insert configuration here
```

* Alertmanager configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```

**Comment by simonpasquier** [comment]
It looks like you're using [prometheus-operator](https://github.com/coreos/prometheus-operator) to deploy your Prometheus setup but the operator isn't supported by the Prometheus community. Hence I'm closing the issue.
I encourage you to ask the question on our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users) where you'll be able to get more answers.
