### ISSUE TITLE
not read from remote InfluxDB

### ISSUE THREAD

**Issue by cool-firer** [prometheus/prometheus#5610]
with remote read and write configured
```
remote_write:
  - url: "http://localhost:8086/api/v1/prom/write?db=prom_test"

remote_read:
  - url: "http://localhost:8086/api/v1/prom/read?db=prom_test"
```
configure prometheus as data source in grafana, but prometheus only writes to InfluxDB, not read from InfluxDB, seems read from local storage, is this a bug?

**Comment by shidoh** [comment]
we have the same problem

**Comment by yeya24** [comment]
Can you provide your configuration of influxdb?

**Comment by shidoh** [comment]
`reporting-disabled = false
bind-address = "127.0.0.1:8088"

[meta]
  dir = "/var/lib/influxdb/meta"
  retention-autocreate = true
  logging-enabled = true

[data]
  dir = "/var/lib/influxdb/data"
  index-version = "inmem"
  wal-dir = "/var/lib/influxdb/wal"
  wal-fsync-delay = "0s"
  validate-keys = false
  query-log-enabled = true
  cache-max-memory-size = 1073741824
  cache-snapshot-memory-size = 26214400
  cache-snapshot-write-cold-duration = "10m0s"
  compact-full-write-cold-duration = "4h0m0s"
  compact-throughput = 50331648
  compact-throughput-burst = 50331648
  max-series-per-database = 1000000
  max-values-per-tag = 100000
  max-concurrent-compactions = 0
  max-index-log-file-size = 1048576
  series-id-set-cache-size = 100
  trace-logging-enabled = false
  tsm-use-madv-willneed = false

[coordinator]
  write-timeout = "10s"
  max-concurrent-queries = 0
  query-timeout = "0s"
  log-queries-after = "0s"
  max-select-point = 0
  max-select-series = 0
  max-select-buckets = 0

[retention]
  enabled = true
  check-interval = "30m0s"

[shard-precreation]
  enabled = true
  check-interval = "10m0s"
  advance-period = "30m0s"

[monitor]
  store-enabled = true
  store-database = "_internal"
  store-interval = "10s"

[subscriber]
  enabled = true
  http-timeout = "30s"
  insecure-skip-verify = false
  ca-certs = ""
  write-concurrency = 40
  write-buffer-size = 1000

[http]
  enabled = true
  bind-address = ":8086"
  auth-enabled = true
  log-enabled = true
  suppress-write-log = false
  write-tracing = false
  flux-enabled = false
  flux-log-enabled = false
  pprof-enabled = true
  debug-pprof-enabled = false
  https-enabled = false
  https-certificate = "/etc/ssl/influxdb.pem"
  https-private-key = ""
  max-row-limit = 0
  max-connection-limit = 0
  shared-secret = ""
  realm = "InfluxDB"
  unix-socket-enabled = false
  unix-socket-permissions = "0777"
  bind-socket = "/var/run/influxdb.sock"
  max-body-size = 25000000
  access-log-path = ""
  max-concurrent-write-limit = 0
  max-enqueued-write-limit = 0
  enqueued-write-timeout = 30000000000

[logging]
  format = "auto"
  level = "debug"
  suppress-logo = false

[[graphite]]
  enabled = false
  bind-address = ":2003"
  database = "graphite"
  retention-policy = ""
  protocol = "tcp"
  batch-size = 5000
  batch-pending = 10
  batch-timeout = "1s"
  consistency-level = "one"
  separator = "."
  udp-read-buffer = 0

[[collectd]]
  enabled = false
  bind-address = ":25826"
  database = "collectd"
  retention-policy = ""
  batch-size = 5000
  batch-pending = 10
  batch-timeout = "10s"
  read-buffer = 0
  typesdb = "/usr/share/collectd/types.db"
  security-level = "none"
  auth-file = "/etc/collectd/auth_file"
  parse-multivalue-plugin = "split"

[[opentsdb]]
  enabled = false
  bind-address = ":4242"
  database = "opentsdb"
  retention-policy = ""
  consistency-level = "one"
  tls-enabled = false
  certificate = "/etc/ssl/influxdb.pem"
  batch-size = 1000
  batch-pending = 5
  batch-timeout = "1s"
  log-point-errors = true

[[udp]]
  enabled = false
  bind-address = ":8089"
  database = "udp"
  retention-policy = ""
  batch-size = 5000
  batch-pending = 10
  read-buffer = 0
  batch-timeout = "1s"
  precision = ""

[continuous_queries]
  log-enabled = true
  enabled = true
  query-stats-enabled = false
  run-interval = "1s"

[tls]
  min-version = ""
  max-version = ""

`

**Comment by nikosn** [comment]
hi,

I do experience the same with influx 1.7.9 and prometheus 2.14
The strange thing is, I get not no queries logged when prometheus fires a remote_read. In influx 1.5.x a query is logged. How can I debug this further?

THX

**Comment by roygbip** [comment]
same problem with me

prometheus 2.14  +  influxdb 1.7.9

prometheus.yaml :

```yaml
global:
  scrape_interval: 15s
  scrape_timeout: 10s
  external_labels:
    cluster: dev-vm
rule_files:
  - "/etc/prometheus/rules/*.yaml"
scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - 0.0.0.0:9090
remote_write:
- url: "http://xxxx/api/v1/prom/write?db=prometheus"
remote_read:
- url: "http://xxxx/api/v1/prom/read?db=prometheus"
```

influxdb.conf 

```shell
[meta]
  dir = "/var/lib/influxdb/meta"
  retention-autocreate = true
  logging-enabled = true

[data]
  dir = "/var/lib/influxdb/data"
  engine = "tsm1"
  wal-dir = "/var/lib/influxdb/wal"
  cache-max-memory-size = "4g"

[http]
  enabled = true
  bind-address = ":8086"
  auth-enabled = false
  log-enabled = true
  write-tracing = false
  pprof-enabled = false
  https-enabled = false
  max-row-limit = 10000
  realm = "InfluxDB"

[retention]
  enabled = true
  check-interval = "30m"

[subsciber]
  enabled = true
  http-timeout = "30s"

[continuous_queries]
  log-enabled = true
  enabled = true
```


wirte data successful (data can read through chronograf and grafana),  but can't read through prometheus. and there are no logs in prometheus.

**Comment by roygbip** [comment]
> same problem with me
> 
> prometheus 2.14 + influxdb 1.7.9
> 
> prometheus.yaml :
> 
> ```yaml
> global:
>   scrape_interval: 15s
>   scrape_timeout: 10s
>   external_labels:
>     cluster: dev-vm
> rule_files:
>   - "/etc/prometheus/rules/*.yaml"
> scrape_configs:
> - job_name: prometheus
>   honor_timestamps: true
>   scrape_interval: 15s
>   scrape_timeout: 10s
>   metrics_path: /metrics
>   scheme: http
>   static_configs:
>   - targets:
>     - 0.0.0.0:9090
> remote_write:
> - url: "http://xxxx/api/v1/prom/write?db=prometheus"
> remote_read:
> - url: "http://xxxx/api/v1/prom/read?db=prometheus"
> ```
> 
> influxdb.conf
> 
> ```shell
> [meta]
>   dir = "/var/lib/influxdb/meta"
>   retention-autocreate = true
>   logging-enabled = true
> 
> [data]
>   dir = "/var/lib/influxdb/data"
>   engine = "tsm1"
>   wal-dir = "/var/lib/influxdb/wal"
>   cache-max-memory-size = "4g"
> 
> [http]
>   enabled = true
>   bind-address = ":8086"
>   auth-enabled = false
>   log-enabled = true
>   write-tracing = false
>   pprof-enabled = false
>   https-enabled = false
>   max-row-limit = 10000
>   realm = "InfluxDB"
> 
> [retention]
>   enabled = true
>   check-interval = "30m"
> 
> [subsciber]
>   enabled = true
>   http-timeout = "30s"
> 
> [continuous_queries]
>   log-enabled = true
>   enabled = true
> ```
> 
> wirte data successful (data can read through chronograf and grafana), but can't read through prometheus. and there are no logs in prometheus.

solved. 
it not work running prometheus in k8s , but when run in a physical machine, it works!

why ? ?

**Comment by roygbip** [comment]
> > same problem with me
> > prometheus 2.14 + influxdb 1.7.9
> > prometheus.yaml :
> > ```yaml
> > global:
> >   scrape_interval: 15s
> >   scrape_timeout: 10s
> >   external_labels:
> >     cluster: dev-vm
> > rule_files:
> >   - "/etc/prometheus/rules/*.yaml"
> > scrape_configs:
> > - job_name: prometheus
> >   honor_timestamps: true
> >   scrape_interval: 15s
> >   scrape_timeout: 10s
> >   metrics_path: /metrics
> >   scheme: http
> >   static_configs:
> >   - targets:
> >     - 0.0.0.0:9090
> > remote_write:
> > - url: "http://xxxx/api/v1/prom/write?db=prometheus"
> > remote_read:
> > - url: "http://xxxx/api/v1/prom/read?db=prometheus"
> > ```
> > 
> > 
> > influxdb.conf
> > ```shell
> > [meta]
> >   dir = "/var/lib/influxdb/meta"
> >   retention-autocreate = true
> >   logging-enabled = true
> > 
> > [data]
> >   dir = "/var/lib/influxdb/data"
> >   engine = "tsm1"
> >   wal-dir = "/var/lib/influxdb/wal"
> >   cache-max-memory-size = "4g"
> > 
> > [http]
> >   enabled = true
> >   bind-address = ":8086"
> >   auth-enabled = false
> >   log-enabled = true
> >   write-tracing = false
> >   pprof-enabled = false
> >   https-enabled = false
> >   max-row-limit = 10000
> >   realm = "InfluxDB"
> > 
> > [retention]
> >   enabled = true
> >   check-interval = "30m"
> > 
> > [subsciber]
> >   enabled = true
> >   http-timeout = "30s"
> > 
> > [continuous_queries]
> >   log-enabled = true
> >   enabled = true
> > ```
> > 
> > 
> > wirte data successful (data can read through chronograf and grafana), but can't read through prometheus. and there are no logs in prometheus.
> 
> solved.
> it not work running prometheus in k8s , but when run in a physical machine, it works!
> 


i know,
```yaml
global:
  scrape_interval: 15s
  scrape_timeout: 10s
  external_labels:
    cluster: dev-vm
```
`external_labels` not support  ？？

**Comment by ctmuthu** [comment]
> > same problem with me
> > prometheus 2.14 + influxdb 1.7.9
> > prometheus.yaml :
> > ```yaml
> > global:
> >   scrape_interval: 15s
> >   scrape_timeout: 10s
> >   external_labels:
> >     cluster: dev-vm
> > rule_files:
> >   - "/etc/prometheus/rules/*.yaml"
> > scrape_configs:
> > - job_name: prometheus
> >   honor_timestamps: true
> >   scrape_interval: 15s
> >   scrape_timeout: 10s
> >   metrics_path: /metrics
> >   scheme: http
> >   static_configs:
> >   - targets:
> >     - 0.0.0.0:9090
> > remote_write:
> > - url: "http://xxxx/api/v1/prom/write?db=prometheus"
> > remote_read:
> > - url: "http://xxxx/api/v1/prom/read?db=prometheus"
> > ```
> > 
> > 
> > influxdb.conf
> > ```shell
> > [meta]
> >   dir = "/var/lib/influxdb/meta"
> >   retention-autocreate = true
> >   logging-enabled = true
> > 
> > [data]
> >   dir = "/var/lib/influxdb/data"
> >   engine = "tsm1"
> >   wal-dir = "/var/lib/influxdb/wal"
> >   cache-max-memory-size = "4g"
> > 
> > [http]
> >   enabled = true
> >   bind-address = ":8086"
> >   auth-enabled = false
> >   log-enabled = true
> >   write-tracing = false
> >   pprof-enabled = false
> >   https-enabled = false
> >   max-row-limit = 10000
> >   realm = "InfluxDB"
> > 
> > [retention]
> >   enabled = true
> >   check-interval = "30m"
> > 
> > [subsciber]
> >   enabled = true
> >   http-timeout = "30s"
> > 
> > [continuous_queries]
> >   log-enabled = true
> >   enabled = true
> > ```
> > 
> > 
> > wirte data successful (data can read through chronograf and grafana), but can't read through prometheus. and there are no logs in prometheus.
> 
> solved.
> it not work running prometheus in k8s , but when run in a physical machine, it works!
> 
> why ? ?

Dear @roygbip, I'm running on a physical machine. I do face the same issue. How did you solve it?
<img width="840" alt="Screenshot 2020-04-30 at 12 41 54 PM" src="https://user-images.githubusercontent.com/5523763/80701636-fde1df80-8adf-11ea-9b6e-7b2c4eba86d0.png">

**Comment by beorn7** [comment]
We are currently running a bug scrub with the team. This looks like different configuration issues and not likely to be a bug within Prometheus. We are closing this here and encourage you to bring any remaning problems to the  [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users).

**Comment by dheerajkr126** [comment]
@ctmuthu @roygbip 
It seems external_labels creating issue here.  
Without external_labels field into Prometheus, remote read is working fine and able to see influx data with Prometheus remote read.

**Comment by gnodli** [comment]
> @ctmuthu @roygbip
> It seems external_labels creating an issue here along with read_recent: true.
> 
>     1. Remove external label
> 
>     2. Add read_recent true.
> 
> 
> global:
> scrape_interval: 15s
> scrape_timeout: 10s
> rule_files:
> 
>     * "/etc/prometheus/rules/*.yaml"
>       scrape_configs:
> 
>     * job_name: prometheus
>       honor_timestamps: true
>       scrape_interval: 15s
>       scrape_timeout: 10s
>       metrics_path: /metrics
>       scheme: http
>       static_configs:
>       
>       * targets:
>         
>         * 0.0.0.0:9090
>           remote_write:
>       * url: "http://xxxx/api/v1/prom/write?db=prometheus"
>         remote_read:
>       * url: "http://xxxx/api/v1/prom/read?db=prometheus"
>         read_recent: true

it works for me, Thx

**Comment by tabnul** [comment]
same issue here, unfortunately unable to remove external labels because i use kube-prometheus-stack (which adds some labels by default). source is effectively influxdb 1.8.* with prometheus external read endpoint.
Did add read_recent: true and it is applied to config, see below.
Any ideas? I assume it should work with external labels (why wouldnt it?). Is it a bug?

```
global:
  scrape_interval: 30s
  scrape_timeout: 10s
  evaluation_interval: 30s
  external_labels:
    prometheus: monitoring/kube-prometheus-stack-prometheus
    prometheus_replica: prometheus-kube-prometheus-stack-prometheus-0
.........
.........
remote_read:
- url: http://influxdb1.XXXX:8086/api/v1/prom/read?db=proxmox
  remote_timeout: 30s
  read_recent: true
  name: proxmox

```

**Comment by tabnul** [comment]
> same issue here, unfortunately unable to remove external labels because i use kube-prometheus-stack (which adds some labels by default). source is effectively influxdb 1.8.* with prometheus external read endpoint.
> Did add read_recent: true and it is applied to config, see below.
> Any ideas? I assume it should work with external labels (why wouldnt it?). Is it a bug?
> 
> ```
> global:
>   scrape_interval: 30s
>   scrape_timeout: 10s
>   evaluation_interval: 30s
>   external_labels:
>     prometheus: monitoring/kube-prometheus-stack-prometheus
>     prometheus_replica: prometheus-kube-prometheus-stack-prometheus-0
> .........
> .........
> remote_read:
> - url: http://influxdb1.XXXX:8086/api/v1/prom/read?db=proxmox
>   remote_timeout: 30s
>   read_recent: true
>   name: proxmox
> ```

looking at the following issues, i guess it is actually related to external labels.
guess ill start doing alerting from grafana for influxdb datasources. Or maybe as alternative i can get influxdb to push data to prometheus.

https://github.com/prometheus/prometheus/issues/7192
https://github.com/prometheus/prometheus/issues/3359
