### ISSUE TITLE
Queries not showing the correct data?

### ISSUE THREAD

**Issue by gengwg** [prometheus/prometheus#5623]
We got some alerts for Blocked Session  with value 4. However, when we look at the Grafana, it only shows 1. I also queried directly from Prometheus GUI, still not seeing 4. This is really confusing.

![image](https://user-images.githubusercontent.com/3356786/58739375-c09c3b80-83be-11e9-87db-5b77424ee390.png)

**Comment by gengwg** [comment]
More strange. I queried on the GUI in past 3 days. It's all 0 now.
![image](https://user-images.githubusercontent.com/3356786/58739632-31902300-83c0-11e9-8d63-0c4dc68c9eb3.png)

Grafana still showing  value 1.
![image](https://user-images.githubusercontent.com/3356786/58739655-54bad280-83c0-11e9-80b7-6d2c6aeb54c6.png)

Why the GUI disappeared?

**Comment by gengwg** [comment]
Confuse me more. After some time, I tried the query again. It shows up. The last spike was still missing though.

![image](https://user-images.githubusercontent.com/3356786/58739766-ecb8bc00-83c0-11e9-8e6e-63813e4cd9a4.png)

**Comment by gengwg** [comment]
I'm using prometheus version: 2.9.2

**Comment by alileza** [comment]
what is the alert rule? what's is the query?

**Comment by alileza** [comment]
if you think it's a bug, please follow bug report templates on issue creation to give more context

## Bug Report
**What did you do?**

**What did you expect to see?**

**What did you see instead? Under which circumstances?**

**Environment**

* System information:

	insert output of `uname -srm` here

* Prometheus version:

	insert output of `prometheus --version` here

* Alertmanager version:

	insert output of `alertmanager --version` here (if relevant to the issue)

* Prometheus configuration file:
```
insert configuration here
```

* Alertmanager configuration file:
```
insert configuration here (if relevant to the issue)
```




* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```

**Comment by simonpasquier** [comment]
Grafana and the Prometheus graph panel use the [query_range](https://prometheus.io/docs/prometheus/latest/querying/api/#range-queries) API which is evaluating the query at different intervals so it is perfectly possible that the spikes are intermittently visible depending on the time of evaluation and the interval duration.

I'm closing it for now. If you have further questions, please use our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search.

**Comment by gengwg** [comment]
Thanks All. Just confirmed spikes are intermittently visible was a `Resolution` issue. I did a query by every 2 hours. This way the resolution is high enough, and the spike is consistently showing up there. I will take a look at the query_range API. It seems automatically lower the resolution when I increase the time span.

The alert value at `4`, dashboard showing `1` is another story. We have 2 prometheus servers, both scraping at `1` minute interval. Due to slight difference in the scraping time, one scraped value `4`, the other scraped `1`. The alert came from the prom that scraped `4`. However we are using the other prom for dashboarding.
