### ISSUE TITLE
remote read from multiple influxdb but after some days, only part of metrics return then restart influxdb read, it's ok again.

### ISSUE THREAD

**Issue by yzsfly** [prometheus/prometheus#5626]

**Comment by simonpasquier** [comment]
You'd need to provide more details about your issue (configuration, versions, logs).

**Comment by beorn7** [comment]
We are currently running a bug scrub with the team. 

Closing for lack of followup. If that's a configuration issue, the  [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) might be a good place to discusse.
