### ISSUE TITLE
Remote Write Shard Flapping

### ISSUE THREAD

**Issue by BertHartm** [prometheus/prometheus#5627]
## Proposal
Since upgrading to 2.8 / 2.9, it's become very hard to tune the number of shards, and the shards seem to flap between min and max shards if there's any sort of issue.

I'm currently mitigating by trying to set all of my prometheus instances to have enough shards to not need to scale up in normal circumstances, and leaving a low max_shards so as to not go crazy if there's an issue (flapping to 1000 was not fun).

This additionally causes issues because resharding causes http connection churn and smaller than normal batches, both of which lead to higher latency / more flapping on other boxes with the same remote write target.

## Bug Report
**What did you do?**
Set up remote write, in this case with the following settings 
```
- url: redacted
  remote_timeout: 30s
  queue_config:
    capacity: 10000
    max_shards: 10
    min_shards: 6
    max_samples_per_send: 5000
    batch_send_deadline: 5m
    max_retries: 3
    min_backoff: 50ms
    max_backoff: 1s
```

**What did you expect to see?**
Smooth movement between 6 and 10 shards as needed to send the data.

**What did you see instead? Under which circumstances?**
Sharp jumps between 6 and 10 shards whenever there's any sort of network latency.
Graph, 15s resolution, # shards in green, remote write network time in yellow `(rate(prometheus_remote_storage_sent_batch_duration_seconds_sum{instance=~"$instance"}[$__interval])`
![image](https://user-images.githubusercontent.com/508811/58824718-bc645e00-860a-11e9-9105-fa6840d176ea.png)

**Environment**

* System information: Linux 4.15.0-1045-azure x86_64

* Prometheus version:
```
prometheus, version 2.9.2 (branch: HEAD, revision: d3245f15022551c6fc8281766ea62db4d71e2747)
  build user:       root@1d43b6951e8f
  build date:       20190424-15:32:31
  go version:       go1.12.4
```

* Alertmanager version: N/A

* Prometheus configuration file:

```
remote_write:
- url: redacted
  remote_timeout: 30s
  queue_config:
    capacity: 10000
    max_shards: 10
    min_shards: 6
    max_samples_per_send: 5000
    batch_send_deadline: 5m
    max_retries: 3
    min_backoff: 50ms
    max_backoff: 1s
```

* Alertmanager configuration file:
N/A

* Logs:
```
Jun  3 15:02:24 hostname prometheus[3325]: ts=2019-06-03T15:02:24.776Z caller=dedupe.go:111 component=remote level=info queue=0:http://redacted/api/v1/prom/remote/write msg="Remote storage resharding" from=6 to=10
Jun  3 15:04:34 hostname prometheus[3325]: ts=2019-06-03T15:04:34.776Z caller=dedupe.go:111 component=remote level=info queue=0:http://redacted/api/v1/prom/remote/write msg="Remote storage resharding" from=10 to=6
Jun  3 15:04:44 hostname prometheus[3325]: ts=2019-06-03T15:04:44.776Z caller=dedupe.go:111 component=remote level=info queue=0:http://redacted/api/v1/prom/remote/write msg="Remote storage resharding" from=6 to=10
Jun  3 15:05:44 hostname prometheus[3325]: ts=2019-06-03T15:05:44.776Z caller=dedupe.go:111 component=remote level=info queue=0:http://redacted/api/v1/prom/remote/write msg="Remote storage resharding" from=10 to=6
Jun  3 15:05:54 hostname prometheus[3325]: ts=2019-06-03T15:05:54.776Z caller=dedupe.go:111 component=remote level=info queue=0:http://redacted/api/v1/prom/remote/write msg="Remote storage resharding" from=6 to=10
Jun  3 15:06:34 hostname prometheus[3325]: ts=2019-06-03T15:06:34.776Z caller=dedupe.go:111 component=remote level=info queue=0:http://redacted/api/v1/prom/remote/write msg="Remote storage resharding" from=10 to=7
Jun  3 15:06:44 hostname prometheus[3325]: ts=2019-06-03T15:06:44.776Z caller=dedupe.go:111 component=remote level=info queue=0:http://redacted/api/v1/prom/remote/write msg="Remote storage resharding" from=7 to=10
Jun  3 15:07:14 hostname prometheus[3325]: ts=2019-06-03T15:07:14.776Z caller=dedupe.go:111 component=remote level=info queue=0:http://redacted/api/v1/prom/remote/write msg="Remote storage resharding" from=10 to=6
Jun  3 15:07:24 hostname prometheus[3325]: ts=2019-06-03T15:07:24.776Z caller=dedupe.go:111 component=remote level=info queue=0:http://redacted/api/v1/prom/remote/write msg="Remote storage resharding" from=6 to=10
Jun  3 15:08:24 hostname prometheus[3325]: ts=2019-06-03T15:08:24.776Z caller=dedupe.go:111 component=remote level=info queue=0:http://redacted/api/v1/prom/remote/write msg="Remote storage resharding" from=10 to=6
Jun  3 15:08:34 hostname prometheus[3325]: ts=2019-06-03T15:08:34.776Z caller=dedupe.go:111 component=remote level=info queue=0:http://redacted/api/v1/prom/remote/write msg="Remote storage resharding" from=6 to=10
Jun  3 15:09:24 hostname prometheus[3325]: ts=2019-06-03T15:09:24.776Z caller=dedupe.go:111 component=remote level=info queue=0:http://redacted/api/v1/prom/remote/write msg="Remote storage resharding" from=10 to=7
Jun  3 15:09:34 hostname prometheus[3325]: ts=2019-06-03T15:09:34.776Z caller=dedupe.go:111 component=remote level=info queue=0:http://redacted/api/v1/prom/remote/write msg="Remote storage resharding" from=7 to=10
Jun  3 15:09:44 hostname prometheus[3325]: ts=2019-06-03T15:09:44.776Z caller=dedupe.go:111 component=remote level=info queue=0:http://redacted/api/v1/prom/remote/write msg="Remote storage resharding" from=10 to=6
Jun  3 15:09:54 hostname prometheus[3325]: ts=2019-06-03T15:09:54.776Z caller=dedupe.go:111 component=remote level=info queue=0:http://redacted/api/v1/prom/remote/write msg="Remote storage resharding" from=6 to=10
Jun  3 15:10:44 hostname prometheus[3325]: ts=2019-06-03T15:10:44.776Z caller=dedupe.go:111 component=remote level=info queue=0:http://redacted/api/v1/prom/remote/write msg="Remote storage resharding" from=10 to=7
Jun  3 15:10:54 hostname prometheus[3325]: ts=2019-06-03T15:10:54.776Z caller=dedupe.go:111 component=remote level=info queue=0:http://redacted/api/v1/prom/remote/write msg="Remote storage resharding" from=7 to=10
Jun  3 15:11:04 hostname prometheus[3325]: ts=2019-06-03T15:11:04.776Z caller=dedupe.go:111 component=remote level=info queue=0:http://redacted/api/v1/prom/remote/write msg="Remote storage resharding" from=10 to=6
Jun  3 15:11:14 hostname prometheus[3325]: ts=2019-06-03T15:11:14.776Z caller=dedupe.go:111 component=remote level=info queue=0:http://redacted/api/v1/prom/remote/write msg="Remote storage resharding" from=6 to=10
Jun  3 15:12:14 hostname prometheus[3325]: ts=2019-06-03T15:12:14.776Z caller=dedupe.go:111 component=remote level=info queue=0:http://redacted/api/v1/prom/remote/write msg="Remote storage resharding" from=10 to=6
Jun  3 15:12:24 hostname prometheus[3325]: ts=2019-06-03T15:12:24.776Z caller=dedupe.go:111 component=remote level=info queue=0:http://redacted/api/v1/prom/remote/write msg="Remote storage resharding" from=6 to=10
Jun  3 15:13:14 hostname prometheus[3325]: ts=2019-06-03T15:13:14.776Z caller=dedupe.go:111 component=remote level=info queue=0:http://redacted/api/v1/prom/remote/write msg="Remote storage resharding" from=10 to=7
Jun  3 15:13:44 hostname prometheus[3325]: ts=2019-06-03T15:13:44.776Z caller=dedupe.go:111 component=remote level=info queue=0:http://redacted/api/v1/prom/remote/write msg="Remote storage resharding" from=7 to=6
Jun  3 15:13:54 hostname prometheus[3325]: ts=2019-06-03T15:13:54.776Z caller=dedupe.go:111 component=remote level=info queue=0:http://redacted/api/v1/prom/remote/write msg="Remote storage resharding" from=6 to=10
Jun  3 15:14:04 hostname prometheus[3325]: ts=2019-06-03T15:14:04.776Z caller=dedupe.go:111 component=remote level=info queue=0:http://redacted/api/v1/prom/remote/write msg="Remote storage resharding" from=10 to=6
Jun  3 15:14:54 hostname prometheus[3325]: ts=2019-06-03T15:14:54.776Z caller=dedupe.go:111 component=remote level=info queue=0:http://redacted/api/v1/prom/remote/write msg="Remote storage resharding" from=6 to=10
Jun  3 15:15:04 hostname prometheus[3325]: ts=2019-06-03T15:15:04.776Z caller=dedupe.go:111 component=remote level=info queue=0:http://redacted/api/v1/prom/remote/write msg="Remote storage resharding" from=10 to=6
Jun  3 15:15:24 hostname prometheus[3325]: ts=2019-06-03T15:15:24.776Z caller=dedupe.go:111 component=remote level=info queue=0:http://redacted/api/v1/prom/remote/write msg="Remote storage resharding" from=10 to=7
Jun  3 15:15:54 hostname prometheus[3325]: ts=2019-06-03T15:15:54.776Z caller=dedupe.go:111 component=remote level=info queue=0:http://redacted/api/v1/prom/remote/write msg="Remote storage resharding" from=7 to=10
Jun  3 15:16:14 hostname prometheus[3325]: ts=2019-06-03T15:16:14.776Z caller=dedupe.go:111 component=remote level=info queue=0:http://redacted/api/v1/prom/remote/write msg="Remote storage resharding" from=6 to=10
Jun  3 15:16:24 hostname prometheus[3325]: ts=2019-06-03T15:16:24.776Z caller=dedupe.go:111 component=remote level=info queue=0:http://redacted/api/v1/prom/remote/write msg="Remote storage resharding" from=10 to=6
Jun  3 15:17:24 hostname prometheus[3325]: ts=2019-06-03T15:17:24.776Z caller=dedupe.go:111 component=remote level=info queue=0:http://redacted/api/v1/prom/remote/write msg="Remote storage resharding" from=10 to=7
Jun  3 15:17:44 hostname prometheus[3325]: ts=2019-06-03T15:17:44.776Z caller=dedupe.go:111 component=remote level=info queue=0:http://redacted/api/v1/prom/remote/write msg="Remote storage resharding" from=7 to=6
Jun  3 15:18:04 hostname prometheus[3325]: ts=2019-06-03T15:18:04.776Z caller=dedupe.go:111 component=remote level=info queue=0:http://redacted/api/v1/prom/remote/write msg="Remote storage resharding" from=6 to=10
Jun  3 15:18:14 hostname prometheus[3325]: ts=2019-06-03T15:18:14.776Z caller=dedupe.go:111 component=remote level=info queue=0:http://redacted/api/v1/prom/remote/write msg="Remote storage resharding" from=10 to=6
...etc...
```

**Comment by cstyan** [comment]
We're seeing this internally as well, and it's on my list of things to look into. 

However, I'd recommend playing with your config more in the mean time, I think some of it is still there from when you were using versions prior to 2.8? I wouldn't set `capacity: 10000` anymore, the whole point of the new remote write implementation is to not drop samples but also to not OOM your Prometheus by buffering too many samples at once.

The default capacity is now 10, and default `max_samples_per_send` is 100. So your config of `6-10` shards and `capacity: 10000` could be changed to just allow for more shards overall with a lower capacity, giving the shards calculation more wiggle room.

**Comment by BertHartm** [comment]
Our settings could definitely be tuned better, but the large `max_samples_per_send` is very intentional because we need better compression, and fewer network connections, and so that's helped. The capacity = 2x max_samples_per_send was from an older ticket, and so that may be less relevant, but we haven't been seeing issues with OOM, so I've been less concerned.

We've seen this issue with the default settings as well though, where a small instance can go quickly from 3 to 1000 shards if there's any network disruption and small samples_per_send, so giving more wiggle room hasn't helped.

I've been approaching configuring min/max shards as effectively connection pool settings, which has worked fairly well, except for the flapping issue, which is hurting throughput anytime it needs to go above the min.

**Comment by cstyan** [comment]
The resharding calculation still needs some work, but even with improvement the system is always going to shard up in the event that the throughput of the current number of shards is below the rate of incoming samples. Though there is a minimum amount it has to want to increase shards by before that would actually happen.

**Comment by ddongchen** [comment]
hi, @cstyan , I find the memory is increasing quickly when remote write shard flapping. Because when resharding,  it will stop the current shards, and start new shards, which will allocate channel struct, while the old struct may be not GC.  The resharding is changed every 10 seconds, and memory is increasing quickly(the capacity of shard is 1000000). So shall we put the "shardUpdateDuration" into the config? then user could changed the duration based the their own scenarios, such as the scraping interval is 60seconds.

**Comment by cstyan** [comment]
I don't think `shardUpdateDuration` is something we want configurable. I still have this issue on my list of things to look into in the near future. Until then you should remove this `the capacity of shard is 1000000` from your config, the default is now 10. Unless your remote write has difficulties keeping up with the amount of samples it needs to send with the default config I wouldn't change it.

**Comment by YaoZengzeng** [comment]
@cstyan I encoutner the same issue with @ddongchen 

The memory usage of my prometheus as follow:

![image](https://user-images.githubusercontent.com/8636562/61217785-0d578e00-a743-11e9-9d2b-ca9b533774e9.png)

when the remote write shard begin to flap, the memory usage of prometheus almost doubled.

Then the shard return to calm, but the memory usage will not be as low as begining.

And almost all my config is default: shard capacity = 10,  min shard = 1 and max shard = 1000...

**Comment by cstyan** [comment]
Yeah I suspect this is due to the behaviour of pending samples. I'll have a look.

**Comment by YaoZengzeng** [comment]
@cstyan totally agree with you.

I'll upgrade my prometheus to v2.11 to see if it works well.

**Comment by csmarchbanks** [comment]
I am working on fixing the shard flapping here: https://github.com/prometheus/prometheus/issues/5763

It looks like your Prometheus is not under much memory pressure, so it is very possible that the garbage from the extra shards that have been created was not released to the kernel yet, causing the permanent increase in memory. What does the heap used by Prometheus look like?

**Comment by YaoZengzeng** [comment]
@csmarchbanks I've lose the environment, but I think the reason of memory burst is just like what you said, Go alloc the memory from OS however not return back immediately even after GC.
