### ISSUE TITLE
Rate() is too high

### ISSUE THREAD

**Issue by xiecaoyq** [prometheus/prometheus#5631]
What did you do?
I have two new mysql instance, no business.
What did you expect to see?
One of the mysql instances：
![image](https://user-images.githubusercontent.com/33243084/58943126-b2309400-87b1-11e9-89d0-62cb72697011.png)
What did you see instead?
And another mysql instance：
![image](https://user-images.githubusercontent.com/33243084/58943294-02a7f180-87b2-11e9-83e0-b0713da59e80.png)

Environment
System information:
suse12sp2         Linux 4.4.21-69-default x86_64 
Prometheus version:
prometheus, version 2.3.2 (branch: v2.3.2, revision: 71af5e29e815795e9dd14742ee7725682fa14b7b)
  build user:       Jenkins
  build date:       20181109-11:58:23OURCE
  go version:       go1.10.1

Supplementary information:
I took 20s of sample data.
![image](https://user-images.githubusercontent.com/33243084/58946551-b7dda800-87b8-11e9-9796-9f165aedaa26.png)

 rate() Calculate sample data for 20s               
![image](https://user-images.githubusercontent.com/33243084/58946172-e73fe500-87b7-11e9-86d2-f0591045cba0.png)

Why is the value after rate() calculated so high?

**Comment by simonpasquier** [comment]
This kind of question is best answered on our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search.

You would need to provide the raw data when the spike happens. It is most likely that the counter value resets in a transient fashion.

**Comment by beorn7** [comment]
We are currently running a bug scrub with the team. @simonpasquier has directed the poster to the  [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) already, closing this one.
