### ISSUE TITLE
Remote write not honoring max_retries setting

### ISSUE THREAD

**Issue by murphyzlaw** [prometheus/prometheus#5636]
## Bug Report
**What did you do?**
Set up Prometheus to scrape some external metrics (e.g., Avalanche).
Configured remote write with max_retries explicitly as 2.
Set up a remote write test server based on documentation/examples/remote_storage/example_write_adapter but with an HTTP 500 response being returned. Following are the source changes to server.go

```
diff --git a/documentation/examples/remote_storage/example_write_adapter/server.go b/documentation/examples/remote_storage/example_write_adapter/server.go
index b94ef8fc..a737ea13 100644
--- a/documentation/examples/remote_storage/example_write_adapter/server.go
+++ b/documentation/examples/remote_storage/example_write_adapter/server.go
@@ -18,15 +18,26 @@ import (
        "io/ioutil"
        "log"
        "net/http"
+  "time"
 
        "github.com/gogo/protobuf/proto"
        "github.com/golang/snappy"
        "github.com/prometheus/common/model"
 
        "github.com/prometheus/prometheus/prompb"
+       kingpin "gopkg.in/alecthomas/kingpin.v2"
+)
+
+var (
+  allMetrics = kingpin.Flag("all", "Show all metrics.").Short('a').Bool()
 )
 
 func main() {
+       kingpin.Version("0.1-rad")
+       kingpin.CommandLine.Help = "Example Prometheus remote write metrics server"
+
+       kingpin.Parse()
+
        http.HandleFunc("/receive", func(w http.ResponseWriter, r *http.Request) {
                compressed, err := ioutil.ReadAll(r.Body)
                if err != nil {
@@ -51,10 +62,26 @@ func main() {
                        for _, l := range ts.Labels {
                                m[model.LabelName(l.Name)] = model.LabelValue(l.Value)
                        }
-                       fmt.Println(m)
-
+      
                        for _, s := range ts.Samples {
-                               fmt.Printf("  %f %d\n", s.Value, s.Timestamp)
+        unixsec := s.Timestamp / 1000
+        unixnsec := (s.Timestamp % 1000) * 1000000
+        timestamp := time.Unix(unixsec, unixnsec)
+        now := time.Now()
+        bufferPastDuration := 5 * time.Minute
+        pastLimit := now.Add(-1*bufferPastDuration)
+        if !pastLimit.Before(timestamp) {
+          msg := "ERROR too far in the past"
+          fmt.Println(msg)
+          fmt.Println(m)
+          fmt.Printf("  %f %s\n", s.Value, timestamp.Format(time.RFC822Z))
+          http.Error(w, msg, http.StatusInternalServerError)
+          return
+        }
+        if *allMetrics {
+          fmt.Println(m)
+          fmt.Printf("  %f %s\n", s.Value, timestamp.Format(time.RFC822Z))
+        }
                        }
                }
        })
```

**What did you expect to see?**
HTTP 500 errors should be retried by the remote write, but only max_retries times (so max_retries + 1 total sends if they are all errors).

**What did you see instead? Under which circumstances?**
The error condition is set up by connecting to the remote write server, then terminating the connection (e.g. stop the server) for more than 5 minutes. You can see good metrics flowing prior to that, if you run the server with -a.

Once the 500 condition occurs (data older than 5 minutes), the sample triggering HTTP 500 error is retried apparently without any direct limit, over and over. Test program output below.

```
ERROR too far in the past
avalanche_metric_mmmmm_0_0{cluster_id="wus-store120", cycle_id="0", endpoint="metrics", instance="11.16.18.179:9001", job="avalanche-service", label_key_kkkkk_0="label_val_vvvvv_0", label_key_kkkkk_1="label_val_vvvvv_1", label_key_kkkkk_2="label_val_vvvvv_2", label_key_kkkkk_3="label_val_vvvvv_3", label_key_kkkkk_4="label_val_vvvvv_4", label_key_kkkkk_5="label_val_vvvvv_5", label_key_kkkkk_6="label_val_vvvvv_6", label_key_kkkkk_7="label_val_vvvvv_7", label_key_kkkkk_8="label_val_vvvvv_8", label_key_kkkkk_9="label_val_vvvvv_9", namespace="wus-store120", pod="avalanche-84b97845dd-gfg27", prometheus="infrastructure", prometheus_replica="prometheus-prom-op-prometheus-operato-prometheus-1", series_id="0", service="avalanche-service"}
  40.000000 31 May 19 22:19 +0000
ERROR too far in the past
avalanche_metric_mmmmm_0_0{cluster_id="wus-store120", cycle_id="0", endpoint="metrics", instance="11.16.18.179:9001", job="avalanche-service", label_key_kkkkk_0="label_val_vvvvv_0", label_key_kkkkk_1="label_val_vvvvv_1", label_key_kkkkk_2="label_val_vvvvv_2", label_key_kkkkk_3="label_val_vvvvv_3", label_key_kkkkk_4="label_val_vvvvv_4", label_key_kkkkk_5="label_val_vvvvv_5", label_key_kkkkk_6="label_val_vvvvv_6", label_key_kkkkk_7="label_val_vvvvv_7", label_key_kkkkk_8="label_val_vvvvv_8", label_key_kkkkk_9="label_val_vvvvv_9", namespace="wus-store120", pod="avalanche-84b97845dd-gfg27", prometheus="infrastructure", prometheus_replica="prometheus-prom-op-prometheus-operato-prometheus-1", series_id="0", service="avalanche-service"}
  40.000000 31 May 19 22:19 +0000
ERROR too far in the past
avalanche_metric_mmmmm_0_0{cluster_id="wus-store120", cycle_id="0", endpoint="metrics", instance="11.16.18.179:9001", job="avalanche-service", label_key_kkkkk_0="label_val_vvvvv_0", label_key_kkkkk_1="label_val_vvvvv_1", label_key_kkkkk_2="label_val_vvvvv_2", label_key_kkkkk_3="label_val_vvvvv_3", label_key_kkkkk_4="label_val_vvvvv_4", label_key_kkkkk_5="label_val_vvvvv_5", label_key_kkkkk_6="label_val_vvvvv_6", label_key_kkkkk_7="label_val_vvvvv_7", label_key_kkkkk_8="label_val_vvvvv_8", label_key_kkkkk_9="label_val_vvvvv_9", namespace="wus-store120", pod="avalanche-84b97845dd-gfg27", prometheus="infrastructure", prometheus_replica="prometheus-prom-op-prometheus-operato-prometheus-1", series_id="0", service="avalanche-service"}
  40.000000 31 May 19 22:19 +0000
ERROR too far in the past
avalanche_metric_mmmmm_0_0{cluster_id="wus-store120", cycle_id="0", endpoint="metrics", instance="11.16.18.179:9001", job="avalanche-service", label_key_kkkkk_0="label_val_vvvvv_0", label_key_kkkkk_1="label_val_vvvvv_1", label_key_kkkkk_2="label_val_vvvvv_2", label_key_kkkkk_3="label_val_vvvvv_3", label_key_kkkkk_4="label_val_vvvvv_4", label_key_kkkkk_5="label_val_vvvvv_5", label_key_kkkkk_6="label_val_vvvvv_6", label_key_kkkkk_7="label_val_vvvvv_7", label_key_kkkkk_8="label_val_vvvvv_8", label_key_kkkkk_9="label_val_vvvvv_9", namespace="wus-store120", pod="avalanche-84b97845dd-gfg27", prometheus="infrastructure", prometheus_replica="prometheus-prom-op-prometheus-operato-prometheus-1", series_id="0", service="avalanche-service"}
```

**Environment**
Running Prometheus in Kubernetes on Azure

* System information:

Linux 4.15.0-1045-azure x86_64

* Prometheus version:

prometheus, version 2.9.2 (branch: HEAD, revision: d3245f15022551c6fc8281766ea62db4d71e2747)
  build user:       root@1d43b6951e8f
  build date:       20190424-15:32:31
  go version:       go1.12.4

* Alertmanager version:

N/A

* Prometheus configuration file:
```
insert configuration here
```

* Alertmanager configuration file:
```
insert configuration here (if relevant to the issue)
```

global:
  scrape_interval: 30s
  scrape_timeout: 10s
  external_labels:
    prometheus: infrastructure
    prometheus_replica: prometheus-prom-op-prometheus-operato-prometheus-1
    cluster_id: wus-store1
scrape_configs:
  - job_name: 'prometheus-stats'
    scrape_interval: 5s
    static_configs:
      - targets:
        - localhost:9090
  - job_name: avalanche
    kubernetes_sd_configs:
    - role: endpoints
      namespaces:
        names:
        - wus-store1
    relabel_configs:
    - source_labels: [__meta_kubernetes_endpoint_port_name]
      separator: ;
      regex: metrics
      replacement: $1
      action: keep
    - source_labels: [__meta_kubernetes_endpoint_address_target_kind, __meta_kubernetes_endpoint_address_target_name]
      separator: ;
      regex: Node;(.*)
      target_label: node
      replacement: ${1}
      action: replace
    - source_labels: [__meta_kubernetes_endpoint_address_target_kind, __meta_kubernetes_endpoint_address_target_name]
      separator: ;
      regex: Pod;(.*)
      target_label: pod
      replacement: ${1}
      action: replace
    - source_labels: [__meta_kubernetes_namespace]
      separator: ;
      regex: (.*)
      target_label: namespace
      replacement: $1
      action: replace
    - source_labels: [__meta_kubernetes_service_name]
      separator: ;
      regex: (.*)
      target_label: service
      replacement: $1
      action: replace
    - source_labels: [__meta_kubernetes_pod_name]
      separator: ;
      regex: (.*)
      target_label: pod
      replacement: $1
      action: replace
    - source_labels: [__meta_kubernetes_service_name]
      separator: ;
      regex: (.*)
      target_label: job
      replacement: ${1}
      action: replace
    - separator: ;
      regex: (.*)
      target_label: endpoint
      replacement: metrics
      action: replace

remote_write:
  - url: http://10.12.190.216:7201/api/v1/prom/remote/write
    remote_timeout: 10s
    queue_config:
      capacity: 5000
      max_shards: 1
      min_shards: 1
      max_samples_per_send: 100
      batch_send_deadline: 5s
      max_retries: 2
      min_backoff: 30ms
      max_backoff: 100ms

* Logs:
Logs do not seem to provide any relevant material. When errors are considered non-retryable (400), I do see information in the log about it. But this test case is for retryable errors. Presumably we do not want to flood the logs for what could be routine retries.

**Comment by murphyzlaw** [comment]
Note: There seems to be independent comment on this as well. See reference to max_retries at https://www.promlts.com/resources/prometheus-remote-storage

**Comment by simonpasquier** [comment]
It seems that [`MaxRetries`](https://github.com/prometheus/prometheus/blob/819205ed0315069dfa4236925b3f2ec4615a8fb9/config/config.go#L120) isn't used anymore in the remote write code though it is still exposed in the configuration. @cstyan is this intentional?

**Comment by cstyan** [comment]
@simonpasquier  @murphyzlaw Yes, the new remote write is intended to never drop samples. So there is no max retries, it retries until it succeeds or the queue manager is shut down for some reason. The config option is still there to not break parsing of people config files I believe.

**Comment by brian-brazil** [comment]
We should remove it then, these configs are not covered by the stability guarantees so there's no point leaving cruft lying about.

**Comment by murphyzlaw** [comment]
Thanks for your response. I'm not following the reasoning though. Was there anything mis-designed about the previous retry limiting? 
Understood that you can accumulate retryable samples in the WAL now and that it's normally desirable to avoid dropping data. However in a use case of persistent 500 e.g. due to problem on the server side, this can cause retry storms, in fact I've observed this in large scale testing. If sharding is set fairly high and all samples are failing, the effect is aggravated and can cause connection storming as well. I brought down our QA gateway that way. I think max_retries is needed as a circuit breaker.

**Comment by cstyan** [comment]
@brian-brazil I'll open a PR to remove it.

@murphyzlaw in that case you might want to up the `max_backoff` time. We can have a look at other options going forward though.

**Comment by tomwilkie** [comment]
Yup, pls remove @cstyan.

We will only retry on 500s (or non-http errors).  If you have a persistent 500 on your server, you should fix it and then let Prometheus replay its WAL into your server.  As Callum said, use max_backoff to protect your severs - and let us know if you think that needs increasing.

The ongoing aim for remote write is for reliability and to not drop samples.

**Comment by robskillington** [comment]
@tomwilkie @brian-brazil this is interesting, do you know what happens someone has been experimenting with remote write and say their backend is down for a day or two since it was a test environment or some similar situation, does Prometheus eventually garbage collect some of the write ahead log and eventually drop some samples?  

If not, is there some mechanism other than just stopping Prometheus and deleting files on disk to instead just fast forward and only start replaying most recent samples?  If not, that makes sense, it would just be good to have guidance on if that's the recommended course of action or not for some kind of test environment where the WAL reader is behind by many hours/days.

**Comment by brian-brazil** [comment]
The WAL files will typically get deleted after a few hours, as that's all independent of the remote write logic.

**Comment by robskillington** [comment]
Ah ok great, as long as the remote write WAL reader does the right thing and doesn't get stuck  that's a good UX IMO (I assume it doesn't get stuck, just considering that could be a possibility, although I assume that the component handles that edge case).

**Comment by cstyan** [comment]
@robskillington The remote write code is actually written to not read more of the WAL into each remote write queue if there's a problem with sending. In addition, there's no state of any kind for the remote write as of right now. When you start Prometheus it's set up to only send samples with a timestamp greater than the start time of that Prometheus instance.

**Comment by murphyzlaw** [comment]
This seems workable then. What is the mechanism / code for "The WAL files will typically get deleted after a few hours" ?

**Comment by cstyan** [comment]
@murphyzlaw this is handled by the internals of the TSDB. It will periodically take some data stored in memory (~2h worth) and write it to disk as a Block. TSDB then truncates that in memory data, which includes creating a Checkpoint of the WAL files. The oldest 1/3 of segment files are considered for deletion, and any data from those segment files and the previous Checkpoint that are still needed in memory will be written to a new checkpoint file.

**Comment by codesome** [comment]
`max_retries` will be removed in the next release, see https://github.com/prometheus/prometheus/pull/5649
