### ISSUE TITLE
Exceptions occurred at Prometheus startup: netpoll failed

### ISSUE THREAD

**Issue by huangqinghe** [prometheus/prometheus#5638]
Exceptions occurred at Prometheus startup:
![image](https://user-images.githubusercontent.com/8857314/59023892-55051300-8883-11e9-97ea-8d974c9e68bf.png)

Running system information and version:
![image](https://user-images.githubusercontent.com/8857314/59023954-6c440080-8883-11e9-813c-53d1e52ea00c.png)

How can I solve this problem?

**Comment by simonpasquier** [comment]
Your kernel is probably too old, see https://github.com/golang/go/wiki/MinimumRequirements#linux

I'm closing it for now. If you have further questions, please use our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search.
