### ISSUE TITLE
Metrics reset to default values after sometime

### ISSUE THREAD

**Issue by vinayakshettar** [prometheus/prometheus#5645]
Hi ..
I am using Prometheus-net.aspnetcore 2.1.3 wit my webapi version.I have deployed my application in IIS server. Everything works fine when i submit reuqests to webapi and i can see all metrics in browser using url /metrics.
But after some time when i refresh the browser .all values goes to default like below

HELP process_start_time_seconds Start time of the process since unix epoch in seconds.
TYPE process_start_time_seconds gauge
process_start_time_seconds 1559879336.1195

HELP process_windows_num_threads Total number of threads
TYPE process_windows_num_threads gauge
process_windows_num_threads 17

HELP process_windows_virtual_bytes Process virtual memory size
TYPE process_windows_virtual_bytes gauge
process_windows_virtual_bytes 2208377839616

HELP process_windows_open_handles Number of open handles
TYPE process_windows_open_handles gauge
process_windows_open_handles 455

HELP dotnet_collection_count_total GC collection count
TYPE dotnet_collection_count_total counter
dotnet_collection_count_total{generation="1"} 0
dotnet_collection_count_total{generation="0"} 0
dotnet_collection_count_total{generation="2"} 0

HELP process_windows_processid Process ID
TYPE process_windows_processid gauge
process_windows_processid 7352

HELP dotnet_totalmemory Total known allocated memory
TYPE dotnet_totalmemory gauge
dotnet_totalmemory 4124032

HELP process_windows_working_set Process working set
TYPE process_windows_working_set gauge
process_windows_working_set 45293568

HELP process_cpu_seconds_total Total user and system CPU time spent in seconds.
TYPE process_cpu_seconds_total counter
process_cpu_seconds_total 1.453125

HELP dotnet_collection_errors_total Total number of errors that occured during collections
TYPE dotnet_collection_errors_total counter
dotnet_collection_errors_total 0

HELP process_windows_private_bytes Process private memory size
TYPE process_windows_private_bytes gauge
process_windows_private_bytes 55476224

**Comment by brian-brazil** [comment]
This sounds like an issue with your client library rather than Prometheus itself.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
