### ISSUE TITLE
Support text/plain responses on /config

### ISSUE THREAD

**Issue by saj** [prometheus/prometheus#5651]
## Proposal

Currently, it seems all requests to `/config` are unconditionally met with `text/html` type responses:

```
> GET /config HTTP/1.1
> Accept: text/plain

< HTTP/1.1 200 OK
< Content-Type: text/html; charset=utf-8
```

This page is dominated by a single `<div>` element that contains the current Prometheus configuration.

`text/plain` output of the configuration itself, without any of the UI gubbins, would make it  easier for users to inspect or validate their loaded configurations using conventional text processing tools, or a simple script that wraps a YAML parser.

Examples:

```
curl -H 'Accept: text/plain' http://prom.test/config | grep job_name
```

```
curl -H 'Accept: text/plain' http://prom.test/config >before-some-change
# ...
curl -H 'Accept: text/plain' http://prom.test/config >after-some-change
diff -u {before,after}-some-change
```

While it is possible to inspect the configuration as it appears on disk, the configuration on disk may not necessarily match that which was last loaded by Prometheus, and the `/config` path is sometimes more convenient to query.  Presumably, configuration sourced from [file-based service discovery](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#file_sd_config) would be displayed here, too, which would provide a single convenient inspection point.

**Comment by brian-brazil** [comment]
This page is part of the UI, so it's always going to be HTML. If you want to something programmatic you can use the UI: https://prometheus.io/docs/prometheus/latest/querying/api/#config

**Comment by beorn7** [comment]
I guess the 2nd UI above was meant to be “API”.

**Comment by brian-brazil** [comment]
Uh, yes.
