### ISSUE TITLE
prometheus not support influxdb v2.0.0 remote_write and remote_read

### ISSUE THREAD

**Issue by DemoLiang** [prometheus/prometheus#5657]
## Proposal
**Use case. Why is this important?**

*“Nice to have” is not a good use case. :)*

## Bug Report
**What did you do?**
I'm used influxdb v2.0.0 and org=prometheus; bucket=prometheus; token=XXXXX
prometheus v2.7.0
I'm config the prometheus remote_write and remote_read:
remote_write:
- url: "http://30.23.4.174:9999/api/v2/write?org=prometheus&bucket=prometheus&precision=s"
  bearer_token: "XXXXX"

remote_read:
- url: "http://30.23.4.174:9999/api/v2/read?org=prometheus&bucket=prometheus&precision=s"
  bearer_token: "XXXXX"

but prometheus log is :
err="server returned HTTP status 401 Unauthorized:{"code":"unauthorized","message":"unauthorized access"}"

I'm try it by curl ,that token is ok

curl "http://30.23.4.174:9999/api/v2/write?org=prometheus&bucket=prometheus&precision=s" --header "Authorization: Token XXXXX" --data "mem,host=host1 used_percent=23 1560324751"

**What did you expect to see?**
remote write and remote read OK.

**What did you see instead? Under which circumstances?**

**Environment**
linux amd64

* System information:

	insert output of `uname -srm` here

* Prometheus version:

	insert output of `prometheus --version` here

* Alertmanager version:

	insert output of `alertmanager --version` here (if relevant to the issue)

* Prometheus configuration file:
```
insert configuration here
```

* Alertmanager configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```

**Comment by brian-brazil** [comment]
> "Authorization: Token XXXXX" 

That's not a bearer token, it'd say `Bearer`. This is something to talk to influx about, @pauldix

**Comment by DemoLiang** [comment]
> > "Authorization: Token XXXXX"
> 
> That's not a bearer token, it'd say `Bearer`. This is something to talk to influx about, @pauldix

thanks reply.
yes, influxdb v2.0.0 require token,not bearer token。 
now prometheus can no longer use influxdb2.0

**Comment by DemoLiang** [comment]
Associate issue  https://github.com/influxdata/influxdb/issues/14127
