### ISSUE TITLE
LabelValues and LabelNames missing storage.Warnings

### ISSUE THREAD

**Issue by jacksontj** [prometheus/prometheus#5661]
**Use case. Why is this important?**

I've been working on adding the Warnings responses to the go client, in doing so I have noticed that the `LabelValues` and `LabelNames` API calls do not return warnings -- but seem like they should. The `Warnings` are currently returning any time there is an error doing some remote read (and presumably for other non-fatal errors)-- which IMO means that this field should exist for *any* API call that requires coordinating with remote read endpoints -- and `LabelValues` and `LabelNames` both do.

**Comment by jacksontj** [comment]
@brian-brazil so I'm assuming from the labels added that this would be an acceptable feature?

**Comment by brian-brazil** [comment]
Yes, it makes sense.
