### ISSUE TITLE
Prometheus runs fine. metrics list showing up as well but no data in elements section

### ISSUE THREAD

**Issue by tanimraja1** [prometheus/prometheus#5663]
Everything works fine with targets are up but no data or grap is shown after query. Any help would be appreciating.
![Screenshot from 2019-06-14 16-06-24](https://user-images.githubusercontent.com/46931401/59503698-b13ce800-8ebe-11e9-81bb-1e07fc1decdb.png)
#1977 I can even find the mertices but no data or graps is displayed

**Comment by simonpasquier** [comment]
Thanks for your report. It looks as if this is actually a question about usage and not development.

To make your question, and all replies, easier to find, we suggest you move this over to our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search. If you prefer more interactive help, join or our [IRC channel](https://webchat.freenode.net/?randomnick=1&channels=prometheus), #prometheus on irc.freenode.net. Please be aware that our IRC channel has no logs, is not searchable, and that people might not answer quickly if they are busy or asleep. If in doubt, you should choose the mailing list.

Once your questions have been answered, please add a short line pointing to relevant replies in case anyone stumbles here via a search engine in the future.
