### ISSUE TITLE
When you pick "unhealthy" in targets the service discovery page is empty

### ISSUE THREAD

**Issue by roidelapluie** [prometheus/prometheus#5677]
## Proposal
**Use case. Why is this important?**

we want to see SD even when on the other page we pick unhealty

## Bug Report
**What did you do?**

Pick unhealthy in targets
Go to service discovery page

**What did you expect to see?**

The service discovery details

**What did you see instead? Under which circumstances?**

Empty page

**Environment**

* Prometheus version:

2.9.2

**Comment by simonpasquier** [comment]
Confirmed. It was probably introduced by #5201 because the service discovery page also includes `/static/js/targets.js`.

**Comment by praveensastry** [comment]
@simonpasquier I would like to contribute to this

**Comment by simonpasquier** [comment]
@praveensastry go ahead!
