### ISSUE TITLE
Prometheus operator 2.7.1  consuming higher ram

### ISSUE THREAD

**Issue by gouravsw** [prometheus/prometheus#5680]
Prometheus version : 2.7.1 (mage:         quay.io/prometheus/prometheus:v2.7.1)
K8S cluster with 29 nodes.

Prometheus pod count : 2
Memory request : 1G
Memory limit: 6G

Prometheus pods are reaching 6G memory in a very short span of time and they start restarting. Same issue seen in older version as well. Below is the memory utilisation for prometheus pod.

a) Is there any fix for the memory issue? We are planning to move into production but hesitating because of memory issue even though there is no impact on live traffic.
b) Is there any metrics available for use of prometheus, like for 10 node cluster prometheus pods should have 2G of memory for limits, 1CPU etc?

Mon Jun 17 16:13:10 IST 2019
prometheus-test-prometheus-0                                   644m         1741Mi
prometheus-test-prometheus-1                                   352m         2228Mi
prometheus-test-prometheus-0                                   3/4     Running     0          1m
prometheus-test-prometheus-1                                   4/4     Running     1          2m
Mon Jun 17 16:13:21 IST 2019
prometheus-test-prometheus-0                                   942m         2240Mi
prometheus-test-prometheus-1                                   123m         2264Mi
prometheus-test-prometheus-0                                   3/4     Running     0          1m
prometheus-test-prometheus-1                                   4/4     Running     1          2m
Mon Jun 17 16:13:39 IST 2019
prometheus-test-prometheus-0                                   942m         2240Mi
prometheus-test-prometheus-1                                   123m         2264Mi
prometheus-test-prometheus-0                                   3/4     Running     0          2m
prometheus-test-prometheus-1                                   4/4     Running     1          2m
Mon Jun 17 16:13:56 IST 2019
prometheus-test-prometheus-0                                   1002m        2384Mi
prometheus-test-prometheus-1                                   383m         2474Mi
prometheus-test-prometheus-0                                   3/4     Running     0          2m
prometheus-test-prometheus-1                                   4/4     Running     1          2m
Mon Jun 17 16:14:12 IST 2019
prometheus-test-prometheus-0                                   1002m        2384Mi
prometheus-test-prometheus-1                                   383m         2474Mi
prometheus-test-prometheus-0                                   3/4     Running     0          2m
prometheus-test-prometheus-1                                   4/4     Running     1          3m
Mon Jun 17 16:14:19 IST 2019
prometheus-test-prometheus-0                                   998m         2902Mi
prometheus-test-prometheus-1                                   171m         2495Mi
prometheus-test-prometheus-0                                   4/4     Running     0          2m
prometheus-test-prometheus-1                                   4/4     Running     1          3m
Mon Jun 17 16:14:45 IST 2019
prometheus-test-prometheus-0                                   598m         3528Mi
prometheus-test-prometheus-1                                   175m         2616Mi
prometheus-test-prometheus-0                                   4/4     Running     0          3m
prometheus-test-prometheus-1                                   4/4     Running     1          3m
Mon Jun 17 16:14:53 IST 2019
prometheus-test-prometheus-0                                   598m         3528Mi
prometheus-test-prometheus-1                                   175m         2616Mi
prometheus-test-prometheus-0                                   4/4     Running     0          3m
prometheus-test-prometheus-1                                   4/4     Running     1          3m
Mon Jun 17 16:15:00 IST 2019
prometheus-test-prometheus-0                                   598m         3528Mi
prometheus-test-prometheus-1                                   175m         2616Mi
prometheus-test-prometheus-0                                   4/4     Running     0          3m
prometheus-test-prometheus-1                                   4/4     Running     1          3m
Mon Jun 17 16:15:16 IST 2019
prometheus-test-prometheus-0                                   839m         5297Mi
prometheus-test-prometheus-1                                   98m          2617Mi
prometheus-test-prometheus-0                                   4/4     Running     0          3m
prometheus-test-prometheus-1                                   4/4     Running     1          4m
Mon Jun 17 16:15:32 IST 2019
prometheus-test-prometheus-0                                   839m         5297Mi
prometheus-test-prometheus-1                                   98m          2617Mi
prometheus-test-prometheus-0                                   4/4     Running     0          3m
prometheus-test-prometheus-1                                   4/4     Running     1          4m
Mon Jun 17 16:15:49 IST 2019
prometheus-test-prometheus-0                                   222m         5371Mi
prometheus-test-prometheus-1                                   90m          2619Mi
prometheus-test-prometheus-0                                   4/4     Running     0          4m
prometheus-test-prometheus-1                                   4/4     Running     1          4m
Mon Jun 17 16:15:55 IST 2019
prometheus-test-prometheus-0                                   222m         5371Mi
prometheus-test-prometheus-1                                   90m          2619Mi

**Comment by codesome** [comment]
Can you provide your Prometheus config and also the output of `{__name__=~"prometheus_tsdb_head_series.*"}` query?

**Comment by gouravsw** [comment]
Output of query

`

prometheus_tsdb_head_series{cluster="pre2-usea1",endpoint="web",instance="10.2.214.179:9090",job="test-prometheus",namespace="test-ops",pod="prometheus-test-prometheus-1",service="test-prometheus"} | 773452
-- | --
prometheus_tsdb_head_series{cluster="pre2-usea1",endpoint="web",instance="10.2.74.11:9090",job="test-prometheus",namespace="test-ops",pod="prometheus-test-prometheus-0",service="test-prometheus"} | 794404
prometheus_tsdb_head_series_created_total{cluster="pre2-usea1",endpoint="web",instance="10.2.214.179:9090",job="test-prometheus",namespace="test-ops",pod="prometheus-test-prometheus-1",service="test-prometheus"} | 773452
prometheus_tsdb_head_series_created_total{cluster="pre2-usea1",endpoint="web",instance="10.2.74.11:9090",job="test-prometheus",namespace="test-ops",pod="prometheus-test-prometheus-0",service="test-prometheus"} | 942126
prometheus_tsdb_head_series_not_found_total{cluster="pre2-usea1",endpoint="web",instance="10.2.214.179:9090",job="test-prometheus",namespace="test-ops",pod="prometheus-test-prometheus-1",service="test-prometheus"} | 0
prometheus_tsdb_head_series_not_found_total{cluster="pre2-usea1",endpoint="web",instance="10.2.74.11:9090",job="test-prometheus",namespace="test-ops",pod="prometheus-test-prometheus-0",service="test-prometheus"} | 0
prometheus_tsdb_head_series_removed_total{cluster="pre2-usea1",endpoint="web",instance="10.2.214.179:9090",job="test-prometheus",namespace="test-ops",pod="prometheus-test-prometheus-1",service="test-prometheus"} | 0
prometheus_tsdb_head_series_removed_total{cluster="pre2-usea1",endpoint="web",instance="10.2.74.11:9090",job="test-prometheus",namespace="test-ops",pod="prometheus-test-prometheus-0",service="test-prometheus"} | 147722

`

Prometheus-config file

`
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: prometheus-operator-prometheus
    chart: prometheus-operator-5.0.1
    heritage: Tiller
    release: test-ops
  name: prometheus-test-prometheus
  namespace: test-ops
  ownerReferences:
  - apiVersion: monitoring.coreos.com/v1
    blockOwnerDeletion: true
    controller: true
    kind: Prometheus
    name: test-prometheus
spec:
  podManagementPolicy: Parallel
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: prometheus
      prometheus: test-prometheus
  serviceName: prometheus-operated
  template:
    metadata:
      annotations:
        iam.amazonaws.com/role: test-ops/pre2-usea1-thanos-role
      creationTimestamp: null
      labels:
        app: prometheus
        prometheus: test-prometheus
    spec:
      containers:
      - args:
        - --web.console.templates=/etc/prometheus/consoles
        - --web.console.libraries=/etc/prometheus/console_libraries
        - --config.file=/etc/prometheus/config_out/prometheus.env.yaml
        - --storage.tsdb.path=/prometheus
        - --storage.tsdb.retention=14d
        - --web.enable-lifecycle
        - --storage.tsdb.no-lockfile
        - --web.external-url=http://test-prometheus.test-ops:9090
        - --web.route-prefix=/
        - --storage.tsdb.min-block-duration=2h
        - --storage.tsdb.max-block-duration=2h
        - --log.level=debug
        image: quay.io/prometheus/prometheus:v2.7.1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 6
          httpGet:
            path: /-/healthy
            port: web
            scheme: HTTP
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 3
        name: prometheus
        ports:
        - containerPort: 9090
          name: web
          protocol: TCP
        readinessProbe:
          failureThreshold: 120
          httpGet:
            path: /-/ready
            port: web
            scheme: HTTP
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 3
        resources:
          limits:
            cpu: "1"
            memory: 6Gi
          requests:
            cpu: 500m
            memory: 1Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/prometheus/config_out
          name: config-out
          readOnly: true
        - mountPath: /prometheus
          name: prometheus-test-prometheus-db
          subPath: prometheus-db
        - mountPath: /etc/prometheus/rules/prometheus-test-prometheus-rulefiles-0
          name: prometheus-test-prometheus-rulefiles-0
        - mountPath: /etc/prometheus/secrets/etcd-client-secret
          name: secret-etcd-client-secret
          readOnly: true
      - args:
        - --log-format=logfmt
        - --reload-url=http://127.0.0.1:9090/-/reload
        - --config-file=/etc/prometheus/config/prometheus.yaml.gz
        - --config-envsubst-file=/etc/prometheus/config_out/prometheus.env.yaml
        command:
        - /bin/prometheus-config-reloader
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        image: quay.io/coreos/prometheus-config-reloader:v0.29.0
        imagePullPolicy: IfNotPresent
        name: prometheus-config-reloader
        resources:
          limits:
            cpu: 50m
            memory: 50Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/prometheus/config
          name: config
        - mountPath: /etc/prometheus/config_out
          name: config-out
      - args:
        - --webhook-url=http://127.0.0.1:9090/-/reload
        - --volume-dir=/etc/prometheus/rules/prometheus-test-prometheus-rulefiles-0
        image: quay.io/coreos/configmap-reload:v0.0.1
        imagePullPolicy: IfNotPresent
        name: rules-configmap-reloader
        resources:
          limits:
            cpu: 100m
            memory: 25Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/prometheus/rules/prometheus-test-prometheus-rulefiles-0
          name: prometheus-test-prometheus-rulefiles-0
      - args:
        - sidecar
        - --prometheus.url=http://127.0.0.1:9090/
        - --tsdb.path=/prometheus
        - --cluster.address=[$(POD_IP)]:10900
        - --grpc-address=[$(POD_IP)]:10901
        - --objstore.config=$(OBJSTORE_CONFIG)
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: HOST_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        - name: OBJSTORE_CONFIG
          valueFrom:
            secretKeyRef:
              key: thanos.yaml
              name: thanos-objstore-config
        image: improbable/thanos:v0.3.1
        imagePullPolicy: IfNotPresent
        name: thanos-sidecar
        ports:
        - containerPort: 10902
          name: http
          protocol: TCP
        - containerPort: 10901
          name: grpc
          protocol: TCP
        - containerPort: 10900
          name: cluster
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /prometheus
          name: prometheus-test-prometheus-db
          subPath: prometheus-db
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 2000
        runAsNonRoot: true
        runAsUser: 1000
      serviceAccount: test-prometheus
      serviceAccountName: test-prometheus
      terminationGracePeriodSeconds: 600
      volumes:
      - name: config
        secret:
          defaultMode: 420
          secretName: prometheus-test-prometheus
      - emptyDir: {}
        name: config-out
      - configMap:
          defaultMode: 420
          name: prometheus-test-prometheus-rulefiles-0
        name: prometheus-test-prometheus-rulefiles-0
      - name: secret-etcd-client-secret
        secret:
          defaultMode: 420
          secretName: etcd-client-secret
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      creationTimestamp: null
      name: prometheus-test-prometheus-db
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 100Gi
      storageClassName: ebs-general-gp2
    status:
      phase: Pending
status:
  collisionCount: 0
  currentReplicas: 2
  currentRevision: prometheus-test-prometheus-686c5b5b8f
  observedGeneration: 13
  readyReplicas: 2
  replicas: 2
  updateRevision: prometheus-test-prometheus-686c5b5b8f
  updatedReplicas: 2`

**Comment by codesome** [comment]
That config is not of Prometheus, maybe Kubernetes or Prometheus operator (I am not familiar with those configs).

**Comment by gouravsw** [comment]
ok..

**Comment by gouravsw** [comment]
Do you mean to say the prometheus.yaml inside the pod at location /etc/prometheus?

**Comment by gouravsw** [comment]
`# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['localhost:9090']`

**Comment by codesome** [comment]
@gouravsw Yes, I meant this config. I was just collecting the info and would like someone to comment if this memory is usage is normal as I am unaware of it myself.

**Comment by beorn7** [comment]
We are currently running a bug scrub with the team. 

This seems stale, and it is also better to be ask those questions on the  [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users).
