### ISSUE TITLE
how to stop and restart scrapemanager

### ISSUE THREAD

**Issue by lm123** [prometheus/prometheus#5684]
## Proposal
**Use case. Why is this important?**

*“Nice to have” is not a good use case. :)*

## Bug Report
**What did you do?**

Can scrapemanager be stopped and restarted without restarting prometheus server?

**What did you expect to see?**

**What did you see instead? Under which circumstances?**

**Environment**

* System information:

centos 7

* Prometheus version:
2.9.1
* Alertmanager version:

	insert output of `alertmanager --version` here (if relevant to the issue)

* Prometheus configuration file:
```
insert configuration here
```

* Alertmanager configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```

**Comment by simonpasquier** [comment]
Prometheus reloads its configuration when it receives a `SIGHUP` signal. Or you can enable the lifecycle endpoint and hit the `/-/reload` endpoint. Either way it will recreate the targets using the current configuration.

I'm closing it for now. If you have further questions, please use our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search.
