### ISSUE TITLE
Prometheus metrics not working where the metrics page loads fine

### ISSUE THREAD

**Issue by saiharshitachava** [prometheus/prometheus#5687]
We installed prometheus using helm chart in kubernetes and the instance looks good and all the targets look fine..

But a weird issue we are seeing right now is we are seeing no data when we hit prometheus related metrics such as prometheus_engine_queries,prometheus_buildinfo etc..

I cross checked the browser timings by  setting them to UTC and my container has UTC time frame..

not sure what could be the issue here..can someone please guide on this

**Comment by simonpasquier** [comment]
Thanks for your report. It looks as if this is actually a question about usage and not development.

To make your question, and all replies, easier to find, we suggest you move this over to our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search. If you prefer more interactive help, join or our [IRC channel](https://webchat.freenode.net/?randomnick=1&channels=prometheus), #prometheus on irc.freenode.net. Please be aware that our IRC channel has no logs, is not searchable, and that people might not answer quickly if they are busy or asleep. If in doubt, you should choose the mailing list.

Once your questions have been answered, please add a short line pointing to relevant replies in case anyone stumbles here via a search engine in the future.
