### ISSUE TITLE
Look forward to get the mips64le tar

### ISSUE THREAD

**Issue by LizZzxx** [prometheus/prometheus#5689]
## Proposal
**Use case. Why is this important?**

*“Nice to have” is not a good use case. :)*

## Bug Report
**What did you do?**

**What did you expect to see?**

**What did you see instead? Under which circumstances?**

**Environment**

* System information:

	insert output of `uname -srm` here

* Prometheus version:

	insert output of `prometheus --version` here

* Alertmanager version:

	insert output of `alertmanager --version` here (if relevant to the issue)

* Prometheus configuration file:
```
insert configuration here
```

* Alertmanager configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```

**Comment by simonpasquier** [comment]
I tried to enable mips builds but there are bits missing in `golang.org/x/sys/unix`. Especially we rely on `gopkg.in/fsnotify/fsnotify.v1` which calls [`unix.InotifyInit()`](https://godoc.org/golang.org/x/sys/unix#InotifyInit) and it isn't available on mips platforms.

**Comment by LizZzxx** [comment]
So, there is not a good way to build mips package?




| |
张学霞
邮箱：15562592336@163.com
|

签名由 网易邮箱大师 定制

On 06/20/2019 21:00, Simon Pasquier wrote:

I tried to enable mips builds but there are bits missing in golang.org/x/sys/unix. Especially we rely on gopkg.in/fsnotify/fsnotify.v1 which calls unix.InotifyInit() and it isn't available on mips platforms.

**Comment by LizZzxx** [comment]
I need a mips package in my work. It will help me a lot if there is one!Thanks for your help!!




| |
张学霞
邮箱：15562592336@163.com
|

签名由 网易邮箱大师 定制

On 06/20/2019 21:02, LizZzxx wrote:
So, there is not a good way to build mips package?




| |
张学霞
邮箱：15562592336@163.com
|

签名由 网易邮箱大师 定制

On 06/20/2019 21:00, Simon Pasquier wrote:

I tried to enable mips builds but there are bits missing in golang.org/x/sys/unix. Especially we rely on gopkg.in/fsnotify/fsnotify.v1 which calls unix.InotifyInit() and it isn't available on mips platforms.

**Comment by simonpasquier** [comment]
You should probably file an issue against https://github.com/golang/go to support ` unix.Inotify*()` on mips architecture.
Meanwhile and if you really need to build on mips, you _could_ fork the Prometheus project, remove the `github.com/prometheus/prometheus/discovery/file` package and all references to it in the rest of the code. The end result would be a Prometheus binary without file service discovery.

**Comment by LizZzxx** [comment]
Thanks for your reply. What is the affect if I remove the file package?




| |
张学霞
邮箱：15562592336@163.com
|

签名由 网易邮箱大师 定制

On 06/20/2019 21:35, Simon Pasquier wrote:

You should probably file an issue against https://github.com/golang/go to support unix.Inotify*() on mips architecture.
Meanwhile and if you really need to build on mips, you could fork the Prometheus project, remove the github.com/prometheus/prometheus/discovery/file package and all references to it in the rest of the code. The end result would be a Prometheus binary without file service discovery.

**Comment by hoffie** [comment]
> Thanks for your reply. What is the affect if I remove the file package?What Simon said:

>> The end result would be a Prometheus binary without file service discovery.

Basically this feature:
https://prometheus.io/docs/prometheus/latest/configuration/configuration/#file_sd_config

**Comment by LizZzxx** [comment]
Thanks a lot! Your reply helps me lot!




| |
张学霞
邮箱：15562592336@163.com
|

签名由 网易邮箱大师 定制

On 06/21/2019 13:22, Christian Hoffmann wrote:

Thanks for your reply. What is the affect if I remove the file package?What Simon said:

The end result would be a Prometheus binary without file service discovery.

Basically this feature:
https://prometheus.io/docs/prometheus/latest/configuration/configuration/#file_sd_config

**Comment by jefferyto** [comment]
I've been looking into a similar issue (building Prometheus for mips64) for OpenWrt (openwrt/packages#9494).

I found that fsnotify switched from `unix.InotifyInit()` to `unix.InotifyInit1()` in [v1.4.2](https://github.com/fsnotify/fsnotify/blob/master/CHANGELOG.md#v142--2016-10-10), and `unix.InotifyInit1()` [should be defined](https://github.com/golang/sys/blob/fae7ac547cb717d141c433a2a173315e216b64c4/unix/syscall_linux.go#L1511) for all Linux systems.

So if you update fsnotify to v1.4.2 or later, then it should work for mips64le (and mips64).

**Comment by LizZzxx** [comment]
Thanks a lot! I have done this issue via comment out the code relating to the file system!




| |
张学霞
邮箱：15562592336@163.com
|

签名由 网易邮箱大师 定制

On 07/23/2019 04:30, Jeffery To wrote:

I've been looking into a similar issue (building Prometheus for mips64) for OpenWrt (openwrt/packages#9494).

I found that fsnotify switched from unix.InotifyInit() to unix.InotifyInit1() in v1.4.2, and unix.InotifyInit1()should be defined for all Linux systems.

So if you update fsnotify to v1.4.2 or later, then it should work for mips64le (and mips64).

**Comment by beorn7** [comment]
We support mips64le now with prebuilt binaries. Closing.
