### ISSUE TITLE
Allow reserved words as label names

### ISSUE THREAD

**Issue by juliusv** [prometheus/prometheus#569]
Currently, `foo{nan="bar"}` and `foo{sum="bar"}` would be syntax errors because `nan` and `sum` are reserved words. Same for all our other reserved words.

Fix: Keep enough state in the parser/lexer to distinguish contexts in which "sum", "NaN", etc. should be parsed as a number vs. parsed as a label name.

**Comment by fabxc** [comment]
Fixed by #676.
