### ISSUE TITLE
Prometheus is not compatible on ARM Machine

### ISSUE THREAD

**Issue by click2cloud-apurva** [prometheus/prometheus#5691]
## Bug Report
**What did you do?**
I tried to build the dockerfile on ARM Processor but the dockerfile throws an error that 
 `exec user process caused "exec format error"`

**What did you expect to see?**
The prometheus should be up and running on ARM Machine also.

**What did you see instead? Under which circumstances?**
When I run Dockerfile on ARM it gives an error as 
`standard_init_linux.go:207: exec user process caused "exec format error"`

**Environment**
ARM Machine (c1.large.arm) on Packet

**Comment by simonpasquier** [comment]
You know that we've got ARM container images already?

**Comment by c2c-engg-20170100** [comment]
The command `docker run --name prometheus -d -p 127.0.0.1:9090:9090 prom/prometheus` does not work on ARM. And the dockerfile is also not available for ARM on github for Prometheus.

**Comment by simonpasquier** [comment]
It _should_ work. What errors do you get? Can you try with the `quay.io/prometheus/prometheus` image?
You could also try `docker.io/prom/prometheus-linux-arm64` or `docker.io/prom/prometheus-linux-armv7`.

As I said, the project's CI already builds ARM images. You can see CI logs [here](https://circleci.com/gh/prometheus/prometheus/13568). You can also look at `Makefile.common` and `.circleci/config.yml`

**Comment by paulfantom** [comment]
If you want to **build** it, you need to set build-arg ARCH to proper CPU architecture (https://github.com/prometheus/prometheus/blob/master/Dockerfile#L1).

I just verified image from docker hub and didn't see any problems on arm7l:
```
paulfantom@unipi:~ $ uname -a
Linux unipi 4.14.98-v7+ #1200 SMP Tue Feb 12 20:27:48 GMT 2019 armv7l GNU/Linux
docker run --name prometheus -d -p 127.0.0.1:9090:9090 prom/prometheus
Unable to find image 'prom/prometheus:latest' locally
latest: Pulling from prom/prometheus
4f49904eebef: Pull complete 
271143bbc3da: Pull complete 
5d2f7c10b936: Pull complete 
9e6d42751493: Pull complete 
38d3cb0eadc6: Pull complete 
2c8464bad8ef: Pull complete 
fbc33041629c: Pull complete 
e13d57ff5625: Pull complete 
8ea097ca7c07: Pull complete 
Digest: sha256:b89e9c7ffbfbc8efebd6d8ff89b33175625bb2c7ae2751fbcd89f0884cfbdcab
Status: Downloaded newer image for prom/prometheus:latest
68ae8d8876b9d4d1361a21e73c2cfbfa1333076eac15243c53345e4c10a46d11
paulfantom@unipi:~ $ docker logs prometheus
level=info ts=2019-06-20T09:30:51.689Z caller=main.go:286 msg="no time or size retention was set so using the default time retention" duration=15d
level=info ts=2019-06-20T09:30:51.689Z caller=main.go:322 msg="Starting Prometheus" version="(version=2.10.0, branch=HEAD, revision=d20e84d0fb64aff2f62a977adc8cfb656da4e286)"
level=info ts=2019-06-20T09:30:51.690Z caller=main.go:323 build_context="(go=go1.12.5, user=root@a49185acd9b0, date=20190525-13:18:30)"
level=info ts=2019-06-20T09:30:51.690Z caller=main.go:324 host_details="(Linux 4.14.98-v7+ #1200 SMP Tue Feb 12 20:27:48 GMT 2019 armv7l 68ae8d8876b9 (none))"
level=info ts=2019-06-20T09:30:51.690Z caller=main.go:325 fd_limits="(soft=1048576, hard=1048576)"
level=info ts=2019-06-20T09:30:51.690Z caller=main.go:326 vm_limits="(soft=unlimited, hard=unlimited)"
level=info ts=2019-06-20T09:30:51.699Z caller=main.go:645 msg="Starting TSDB ..."
level=info ts=2019-06-20T09:30:51.699Z caller=web.go:417 component=web msg="Start listening for connections" address=0.0.0.0:9090
level=info ts=2019-06-20T09:30:51.737Z caller=main.go:660 fs_type=EXT4_SUPER_MAGIC
level=info ts=2019-06-20T09:30:51.737Z caller=main.go:661 msg="TSDB started"
level=info ts=2019-06-20T09:30:51.737Z caller=main.go:730 msg="Loading configuration file" filename=/etc/prometheus/prometheus.yml
level=info ts=2019-06-20T09:30:51.743Z caller=main.go:758 msg="Completed loading of configuration file" filename=/etc/prometheus/prometheus.yml
level=info ts=2019-06-20T09:30:51.743Z caller=main.go:614 msg="Server is ready to receive web requests."
```

**Comment by c2c-engg-20170100** [comment]
If I run the same dockerfile with your given  image `docker.io/prom/prometheus-linux-arm64` it gives error while building dockerfile
![image](https://user-images.githubusercontent.com/50102846/59841959-1424f800-9373-11e9-9bae-819d26635bff.png)

**Comment by simonpasquier** [comment]
This is because it can't find the binary in `.build/linux-arm64`, presumably you haven't used `promu crossbuild` to build the binaries. It would be better to use our [developer mailing list](https://groups.google.com/forum/#!forum/prometheus-developers) to continue the discussion as I don't think this is an issue with the project.

**Comment by beorn7** [comment]
We are currently running a bug scrub with the team. @simonpasquier pointer to the dev mailing list is appropriate, we are closing this now.
