### ISSUE TITLE
Best practice for replaying historical prometheus data?

### ISSUE THREAD

**Issue by WJerry0227** [prometheus/prometheus#5697]
## Proposal
**Use case. Why is this important?**

I am trying to use prometheus for testing and when a test ends, I captured all the data and store it somewhere. Is there a feature that prometheus can read historical data? Instead of keep receiving streaming data, is there a mode to read some data and only play around within that certain time?

This could be helpful for monitoring.

Or what's some best practice to view historical data given a historical data file?

**Comment by simonpasquier** [comment]
I'm not sure exactly about what you're looking for. I've seen people running integration/functional tests,  snapshotting the Prometheus data when the tests stop and saving the data (share filesystem or object storage). After that they can destroy the running environment and restore the saved data to a fresh Prometheus server if needed. 

I'm closing it for now. If you have further questions, please use our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search.
