### ISSUE TITLE
Interpolation of integers (in UI and storage) should be optional

### ISSUE THREAD

**Issue by niko** [prometheus/prometheus#570]
It feels weird when integers get interpolated. In our case we're monitoring listeners on a streaming server and "5203.167466666667 listeners" just feels plain wrong. IMHO either the interpolation should be somewhat clever and round floats to ints if the input is always ints or it should be optional in the js consoles library and the backend storage.

**Comment by brian-brazil** [comment]
This interpolation is in the /query_range endpoint, and we've discussed having an endpoint that doesn't do interpolation (though it can't evaluate expressions then either).

If you're using the console templates and associated graph library, you can configure how you want to values rendered such as the `humanize` function.

**Comment by juliusv** [comment]
Yeah, what's important to understand is that values are stored exactly as they are exposed, and only interpolated when doing a query. The historical reason for this was that to support aggregations like `sum`, `avg`, etc., we *have* to pick predetermined timestamps at which to sample all the existing time series, so that they're all aligned for aggregation. That naturally requires some form of interpolation. But for the special case of not doing any aggregations, it could be possible to not do any interpolation in the queries. It's just that this code is not there yet.

**Comment by beorn7** [comment]
Should we file an issue about the non-interpolation endpoint?

I'd be strongly opposed to "interpolation of integers only to integers". That would mathematically make no sense. The expectation value has nothing to do with the most likely value. (The expectation value of rolling a die is 3.5, although a die will never ever actual give you 3.5 as a result. That doesn't make 4 the better expectation value.)

**Comment by juliusv** [comment]
There's even a problem for non-aggregated time series though: the graphing libraries expect series to be time-aligned, especially for features such as stacking a graph. We'd have to experiment with that.

I filed https://github.com/prometheus/prometheus/issues/571

**Comment by juliusv** [comment]
Closing this in favor of https://github.com/prometheus/prometheus/issues/571

**Comment by juliusv** [comment]
@niko I think we neglected the part of your suggestion though: offering controls over rounding PromDash or the query language. Perhaps file another ticket in https://github.com/prometheus/promdash if you feel that's still missing?

Just in case it already helps, you can round values via the `round()`, `floor()`, and `ceil()` functions. E.g. http://prometheus.io/docs/querying/functions/#round(). If you wrap that around an entire expression, you should get only integers out.

**Comment by niko** [comment]
Thanks for the fast reply. Makes completely sense when I think about it. Will try round() et.all.

Thanks for the great project in general. I love it! :)

**Comment by juliusv** [comment]
Excellent, thanks! :)
