### ISSUE TITLE
Prometheus tsdb admin api is not returning any data

### ISSUE THREAD

**Issue by yaminisridaran** [prometheus/prometheus#5712]
I am using prometheus version 2.9.0. 
Enabled web-enable-admin-api.
curl -X POST -g 'http://10.15.10.31:9090/api/v1/admin/tsdb/delete_series?match[]=up

I don't see any logs in prometheus.
Please help me with this issue

**Comment by roidelapluie** [comment]
Thanks for your report. It looks as if this is actually a question about usage and not development.

To make your question, and all replies, easier to find, we suggest you move this over to our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search. If you prefer more interactive help, join or our [IRC channel](https://webchat.freenode.org/?channels=prometheus), #prometheus on irc.freenode.net. Please be aware that our IRC channel has no logs, is not searchable, and that people might not answer quickly if they are busy or asleep. If in doubt, you should choose the mailing list.

If you think this is not purely a support question, feel free to comment in here or take the underlying issues to our [developer mailing list](https://groups.google.com/forum/#!forum/prometheus-developers).

Once your questions have been answered, please add a short line pointing to relevant replies in case anyone stumbles here via a search engine in the future.
