### ISSUE TITLE
Make pattern of rule_files more flexible

### ISSUE THREAD

**Issue by YaoZengzeng** [prometheus/prometheus#5714]
## Proposal
**Use case. Why is this important?**

If I configure the rule path with "/etc/prometheus/rules/\*/\*.yaml" and Prometheus will report it is invalid.

Actually If I package the rules in configmap, but the configmap has size limit. So more rules I have, more configmaps I need. 

And I have to mount them to the Pod of Prometheus, with the rule path like `/etc/prometheus/rules/prometheus-prometheus-rulefiles-0/*.yaml`. 

Every time I have a new configmap, I need to update the `prometheus.yaml` with a new rule path.

If I could configure the rule path like "/etc/prometheus/rules/\*/\*.yaml", no update of `prometheus.yaml` is needed as well as reload of Prometheus.

If this enhancement make sense, I'd like to make PR for it :)

**Comment by brian-brazil** [comment]
We only allow a glob in the last part for consistency with file_sd, as we've inotify-related limitations there.

Any time you add a rule file you need to reload Prometheus anyway.

**Comment by YaoZengzeng** [comment]
@brian-brazil  get it! 

Thanks!
