### ISSUE TITLE
Global External Labels for Remote Write should respect honor_labels

### ISSUE THREAD

**Issue by cstyan** [prometheus/prometheus#5726]
## Proposal

Remote storage options such as Cortex and Thanos deduplicate samples from HA Prometheus via configuration of labels. The most common way to set these labels from Prometheus' end is via `external_labels`. However, it's not reasonable to expect users to always set unique label names for these labels that may not, at some point, also be used as labels within series. 

This can result in confusion on the end of the operator(s), where for example they may see multiple cluster values when they only expect one because certain pieces of infrastructure might export the same `cluster` label that they've configured via `external_labels`. We've seen this happen with Kafka clusters, as an example.

I'm proposing that remote write's application of `external_label`s should respect the `honor_labels` configuration option, or have it's own similar option. Having a separate configuration option for remote write makes the most sense, where if the option is true then label values from `external_labels` would have precedence

@beorn7 @brian-brazil 
cc @tomwilkie

**Comment by brian-brazil** [comment]
external_labels is intended to cover the majority use case. If you want to do something more complicated, you can do so with write_relabel_configs. It's one of the reasons it exists.

**Comment by beorn7** [comment]
@cstyan Perhaps I misunderstand something in the described use case, but I also think that `write_relabel_configs` should be perfect for it.

BTW: While reading up about `honor_labels`, I found a confusing wording in the docs. See https://github.com/prometheus/prometheus/pull/5728 for a fix.

**Comment by beorn7** [comment]
After some direct discussion with @cstyan , I think we can close this.

To phrase the problem in other words (@cstyan please correct me if I misunderstood):

This is about guaranteeing that a certain label (e.g. `cluster`) can be used for deduplication by preventing targets from using the same label for other purposes. Thus, if a label is provided by a target, it has to be renamed. That could happen in the `write_relabel_configs`. But @cstyan wanted the same relabeling to happen already in the local Prometheus TSDB. Thus, it boiled down to changing those labels upon ingestion, which means the label in question (e.g. `cluster`) simply has to be set as a target label. That will rename any labels of the same name as exposed by the target itself (e.g. `exported_cluster`). And I believe that's what @cstyan wanted in the first place.

Closing this, assuming I got that right. Please follow up if not.
