### ISSUE TITLE
use rate() get different results in multiple request

### ISSUE THREAD

**Issue by posufo** [prometheus/prometheus#5732]
## Bug Report
**What did you do?**
we have a counter type metric:"balarm_bagent_send_alertevent", draw it in prometheus Graph web.   Use rate() on it , but get different result in multiple requests when we adjust "starttime" to 2d , then adjust it to 1d repeat multiple times.  
our query is : 
"rate(balarm_bagent_send_alertevent{status="success",job="balarm-bagent-cn",host="10.6.24.219"}[1m])"
timerange is from 1d to now,   resolution is 60s.   

first result , resolution is 60s.
![image](https://user-images.githubusercontent.com/2792499/60560681-5858c500-9d83-11e9-9064-ce56ea96e543.png)

second result, , resolution is 60s.
![image](https://user-images.githubusercontent.com/2792499/60560701-6c9cc200-9d83-11e9-875b-d9c0ba7d83e8.png)

without assign resolution 
![image](https://user-images.githubusercontent.com/2792499/60561145-23e60880-9d85-11e9-9bd2-e7b4a3587af1.png)

I think second result maybe right?

**What did you expect to see?**
in multiple request , get the same result.

**Environment**

* System information:

	Linux 3.16.0-7-amd64 x86_64

* Prometheus version:

        prometheus, version 2.7.0 (branch: HEAD, revision: 
        410ee9e04acb8f59f400858752ca82b4ef88035e)
        build user:       root@3bc81b516055
        build date:       20190128-10:09:51
        go version:       go1.11.5

       prometheus, version 2.6.0 (branch: HEAD, revision: 
      dbd1d58c894775c0788470944b818cc724f550fb)
      build user:       root@bf5760470f13
      build date:       20181217-15:14:46
      go version:       go1.11.3

* Prometheus configuration file:
```
global:
  scrape_interval: 10s
scrape_configs:  
  - job_name: balarm-bagent-cn
    scrape_interval: 30s
    static_configs:
    - targets: ['10.6.24.219:2112']
```

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
