### ISSUE TITLE
ec2_sd_configs with role_arn does not scrape targets from AWS EC2 instances

### ISSUE THREAD

**Issue by evgmoskalenko** [prometheus/prometheus#5738]
EC2 SD configurations "ec2_sd_configs" with "role_arn" does not scrape targets from AWS EC2 instances

## Bug Report
I create for Prometheus EC2 Instances role with policy:

     arn:aws:iam::aws:policy/AmazonEC2ReadOnlyAccess

**Environment**

* System information:

     amzn-ami-2018.03.u-amazon-ecs-optimized (ami-0c0c01a7a42f41c0c)

* Prometheus version:

     v2.10.0

* Alertmanager version:

     v0.17.0

* Prometheus configuration file:
```
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'ec2_aws_node_exporter_discovery'
    ec2_sd_configs:
      - region: eu-central-1
        role_arn: arn:aws:iam::my_account_id:role/PrometheusRole-klfm4z5r67tyr
        port: 9100
    relabel_configs:
      - source_labels: ['__meta_ec2_tag_monitoring']
        separator: ;
        regex:         'monitoring'
        replacement:   '$1'
        action:        'keep'
      - source_labels: ['__meta_ec2_public_ip']
        regex:         '^(.*)$'
        target_label:  'instance'
        replacement:   '$1'
        action:        'replace'
      - source_labels: ['__meta_ec2_public_ip']
        regex:         '^(.*)$'
        target_label:  '__address__'
        replacement:   '${1}:9100'
      - source_labels: ['__meta_ec2_instance_id']
        target_label: instance
      - source_labels: ['__meta_ec2_tag_Name']
        target_label: name
```

* Logs:
```
prometheus_1      | level=error ts=2019-07-04T18:00:31.689Z caller=refresh.go:77
component="discovery manager scrape" 
discovery=ec2 
msg="Unable to refresh target groups" 
err="could not describe instances: NoCredentialProviders: no valid providers in chain. Deprecated. For verbose messaging see aws.Config.CredentialsChainVerboseErrors"
```

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by evgmoskalenko** [comment]
This is not a configuration issue. This is a bug. I create a role, attach it to the instance with the Prometheus and specify the role in the config of the Prometheus.

**Comment by evgmoskalenko** [comment]
If this does not work, then remove from the documentation.

**Comment by evgmoskalenko** [comment]
This is workaround is works, with <Key=profile, Value=role>

```
profile: arn:aws:iam::my_account_id:role/PrometheusRole-klfm4z5r67tyr
```
Please. Fix the documentation or fix the bug. Do not confuse.

**Comment by ekoca** [comment]
@evgmoskalenko your solution did not work for me! `ec2_sd_configs` with `role_arn` does not scrape targets from AWS EC2 instances. Here is the error:
```
my-prometheus    | level=error ts=2019-08-02T18:48:20.389Z caller=refresh.go:95 component="discovery manager scrape" discovery=ec2 msg="Unable to refresh target groups" err="could not describe instances: NoCredentialProviders: no valid providers in chain. 
Deprecated.\n\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors"
```

@brian-brazil I don't know why this is closed without proper explanation to solution! :/

**Comment by ejpir** [comment]
can confirm `profile: <arn>` has worked for us

**Comment by athom** [comment]
> This is workaround is works, with <Key=profile, Value=role_arn>
> 
> ```
>   - job_name: 'ec2_aws_node_exporter_discovery'
>     ec2_sd_configs:
>       - region: eu-central-1
>         profile: arn:aws:iam::my_account_id:role/PrometheusRole-klfm4z5r67tyr
>         port: 9100
>     relabel_configs:
> ```
> 
> Fix bug or fix the documentation.

hi, @evgmoskalenko,  you save my day!

**Comment by keiransteele** [comment]
For anyone coming here from Google, role_arn does work, see this article for setting up cross account discovery https://jarodw.com/posts/prometheus-ec2-sd-multiple-aws-accounts/

You need a role in the target account with AmazonEC2ReadOnlyAccess or similar and a trust relationship with the account your Prometheus instance is in. On the Prometheus instance role, you need a policy that allows it to assume the role in the target account.

**Comment by uvaisibrahimatourslate** [comment]
The `role_arn` didn't work for me! :( anyone else facing the same issue with role_arn or role_name ?

**Comment by vrathore18** [comment]
I am facing the same issue

**Comment by jodihum** [comment]
I am having problems with service discovery if I use version 2.26 or above.  If I go back to 2.25.2 it is fine.  I believe it is related to role_arn, since the only services I am having problems discovering are the ones with role_arn in the ec2_sd_configs.  Does anyone know what would be causing this or how I can fix it?

**Comment by jodihum** [comment]
So it turns out our problem was that we needed to have https_proxy set, not just http_proxy as previously
