### ISSUE TITLE
SD for Tencent Cloud CVM instances

### ISSUE THREAD

**Issue by camelus0211** [prometheus/prometheus#5739]
We are using prometheus in tencent cloud. But now, prometheus is not support for scraping CVM instances. We already have done that, we will add PR later.

**Comment by simonpasquier** [comment]
Thanks for suggesting this change. Unfortunately, we are currently not accepting new integrations.

We can only provide the stability and performance we want to provide if we can properly maintain the codebase. This includes, amongst others, test integrations in an automated and scalable fashion. For this reason, we are suggesting people integrate with the help of our generic interfaces. We have an integrations page on which integrations using our generic interfaces are listed.

Even if existing integrations can not be tested in an automated fashion, we will not remove them for reasons of compatibility. This also means that any additions we take on, or any changes to existing integrations we make or accept, will mean maintaining and testing these until at least the next major version, realistically even beyond that.

Feel free to question this answer on our [developer mailing list](https://groups.google.com/forum/#!forum/prometheus-developers), but be aware it's unlikely that you will get a different answer.

**Comment by liguozhong** [comment]
@camelusluo  。We use prometheus in Alibaba and also encountered problems with service discovery. We follow the instructions in the following article. Completed the custom service discovery in Alibaba.

https://prometheus.io/blog/2018/07/05/implementing-custom-sd/

![image](https://user-images.githubusercontent.com/9583245/63639264-bb037880-c6c3-11e9-8268-71383b5ff331.png)

**Comment by cstyan** [comment]
Note that the previous moratorium on SD implementations has been lifted: https://github.com/prometheus/prometheus/tree/master/discovery#does-this-make-sense-as-an-sd

> Note: As part of lifting the past moratorium on new SD implementations it was agreed that, in addition to the existing requirements, new service discovery implementations will be required to have a committed maintainer with push access (i.e., on -team).

**Comment by roidelapluie** [comment]
Note: this has been proposed in #6671

**Comment by krajorama** [comment]
Hello from the bug scrub: closing as we don't have access to test environment. Please consider following up in this issue or open a new issue if you can donate test resources. Alternatively consider implementation via file SD or HTTP SD to keep the integration separate from Prometheus.
