### ISSUE TITLE
cannot find module providing package ....

### ISSUE THREAD

**Issue by Aquarian-Age** [prometheus/prometheus#5747]
Project directory created with go mod After importing this package, it is found that it cannot be compiled.

go run Swarm/swarm_upload.go 
```
go: finding github.com/prometheus/prometheus/util/flock latest
go: finding github.com/prometheus/prometheus/util latest
build command-line-arguments: cannot load github.com/prometheus/prometheus/util/flock: cannot find module providing package github.com/prometheus/prometheus/util/flock
```
Edit the go mod file to delete the library and recompile it will automatically download this library
How to disable automatic go mod download this library?

**Comment by simonpasquier** [comment]
Without further information, it is a bit difficult to help you but the Go code you intend to compile uses a package that has been removed (see https://github.com/prometheus/prometheus/pull/3853) so you need to tell Go modules to use an older version.

I'm closing it for now. If you have further questions, please use our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search.
