### ISSUE TITLE
remote_write with down host consumes all available memory on node

### ISSUE THREAD

**Issue by llamahunter** [prometheus/prometheus#5750]
## Bug Report
**What did you do?**

Deployed prometheus with remote_write url configured for a server with valid DNS that happened to be down.

**What did you expect to see?**

Prometheus to continue to operate with normal memory usage, but perhaps with lots of error messages in the logs.

**What did you see instead? Under which circumstances?**

Prometheus consumed all available RAM on the node, eventually causing the kubelet to get wedged.  Note that url hostname needs to resolve in DNS for memory leak to occur.  If the hostname is invalid, or if the remote host is up, the leak doesn't seem to happen.

I suspect that there is some sort of ever growing queue in prometheus for sending events onward to the remote server.  If it's able to resolve the address, it assumes it might come up "someday" and so caches all events for that hopeful day when the remote server starts responding.  Some sort of limit possibly ought to be placed on this queuing so that it doesn't take down the whole node.

**Environment**

* System information:

Linux 4.14.106-97.85.amzn2.x86_64 x86_64

* Prometheus version:

prometheus, version 2.7.2 (branch: HEAD, revision: 82f98c825a1437c0a24056eb4dc986d9a3fc7fae)
  build user:       root@ab86c672c33a
  build date:       20190302-14:57:04
  go version:       go1.11.5

* Alertmanager version:

N/A

* Prometheus configuration file:

relevant bit dealing with remote_write

```
remote_write:
- url: http://enpfkvdbha1.tivo.com:8098
  remote_timeout: 30s
  write_relabel_configs:
  - source_labels:
    - _name_
    regex: expensive.*
    action: drop
  bearer_token: ABC123
```

Note that `enpfkvdbha1.tivo.com` is a resolveable DNS name, but the server is down.

* Logs:

Relevant bits of prometheus log spewage about send errors.

```
level=warn ts=2019-07-09T21:07:41.193417995Z caller=queue_manager.go:527 component=remote queue=0:http://enpfkvdbha1.tivo.com:8098 msg="Error sending samples to remote storage" count=100 err="Post http://enpfkvdbha1.tivo.com:8098: dial tcp 192.168.63.83:8098: i/o timeout"
level=warn ts=2019-07-09T21:07:41.22135852Z caller=queue_manager.go:527 component=remote queue=0:http://enpfkvdbha1.tivo.com:8098 msg="Error sending samples to remote storage" count=100 err="Post http://enpfkvdbha1.tivo.com:8098: context deadline exceeded"
level=warn ts=2019-07-09T21:07:41.231925947Z caller=queue_manager.go:527 component=remote queue=0:http://enpfkvdbha1.tivo.com:8098 msg="Error sending samples to remote storage" count=100 err="Post http://enpfkvdbha1.tivo.com:8098: dial tcp 192.168.63.83:8098: i/o timeout"
level=warn ts=2019-07-09T21:07:41.232942688Z caller=queue_manager.go:527 component=remote queue=0:http://enpfkvdbha1.tivo.com:8098 msg="Error sending samples to remote storage" count=100 err="Post http://enpfkvdbha1.tivo.com:8098: context deadline exceeded"
level=warn ts=2019-07-09T21:07:41.275507121Z caller=queue_manager.go:527 component=remote queue=0:http://enpfkvdbha1.tivo.com:8098 msg="Error sending samples to remote storage" count=100 err="Post http://enpfkvdbha1.tivo.com:8098: dial tcp 192.168.63.83:8098: i/o timeout"
level=warn ts=2019-07-09T21:07:41.276022237Z caller=queue_manager.go:527 component=remote queue=0:http://enpfkvdbha1.tivo.com:8098 msg="Error sending samples to remote storage" count=100 err="Post http://enpfkvdbha1.tivo.com:8098: context deadline exceeded"
level=warn ts=2019-07-09T21:07:41.276324789Z caller=queue_manager.go:527 component=remote queue=0:http://enpfkvdbha1.tivo.com:8098 msg="Error sending samples to remote storage" count=100 err="Post http://enpfkvdbha1.tivo.com:8098: context deadline exceeded"
level=warn ts=2019-07-09T21:07:41.277722274Z caller=queue_manager.go:527 component=remote queue=0:http://enpfkvdbha1.tivo.com:8098 msg="Error sending samples to remote storage" count=100 err="Post http://enpfkvdbha1.tivo.com:8098: context deadline exceeded"
level=warn ts=2019-07-09T21:07:41.29702191Z caller=queue_manager.go:527 component=remote queue=0:http://enpfkvdbha1.tivo.com:8098 msg="Error sending samples to remote storage" count=100 err="Post http://enpfkvdbha1.tivo.com:8098: context deadline exceeded"
level=warn ts=2019-07-09T21:07:41.298535746Z caller=queue_manager.go:527 component=remote queue=0:http://enpfkvdbha1.tivo.com:8098 msg="Error sending samples to remote storage" count=100 err="Post http://enpfkvdbha1.tivo.com:8098: context deadline exceeded"
level=warn ts=2019-07-09T21:07:41.298787389Z caller=queue_manager.go:527 component=remote queue=0:http://enpfkvdbha1.tivo.com:8098 msg="Error sending samples to remote storage" count=100 err="Post http://enpfkvdbha1.tivo.com:8098: context deadline exceeded"
level=warn ts=2019-07-09T21:07:41.455535275Z caller=queue_manager.go:231 component=remote queue=0:http://enpfkvdbha1.tivo.com:8098 msg="Remote storage queue full, discarding sample. Multiple subsequent messages of this kind may be suppressed."
```

**Comment by csmarchbanks** [comment]
Hello,

Prometheus v2.8.0 and above have a new implementation of remote write that reads from the write-ahead log rather than keeping all samples in memory in order to help prevent OOMs like this. Are you able to reproduce the issue using a more recent version of Prometheus? Preferably >= v2.9.2 for better memory performance.

If you keep using v2.7.2, you can tune the memory requirements of your remote write queue configuration. The most useful properties to tune are:
* `capacity`, which can be lowered from the default 10,000 per shard in order to start discarding samples sooner.
* `max_shards`, which can be lowered so that there will be fewer overall queues.

Note that prior to v2.8.0, once you overrun the capacity of a remote write shard Prometheus will start to discard samples, as you see in the last line of your posted logs.

**Comment by cstyan** [comment]
As @csmarchbanks mentioned:
> Note that prior to v2.8.0, once you overrun the capacity of a remote write shard Prometheus will start to discard samples, as you see in the last line of your posted logs.

Either this, or remote write hasn't reached the configured max enqueued samples (based on number of shards, capactiy, etc.) and would eventually OOM.

Please do let us know if you have the same problems with newer versions.

**Comment by llamahunter** [comment]
Not sure I buy the 'max capacity discard' argument, as it would continue to consume memory for hours until the prometheus process was many, many gigabytes in size.  

Will try with a later version of prometheus, but this problem has persisted for many versions (since we first started testing with 2.3).  Not sure that kube-prometheus, which we use for deployment, has updated to 2.8.0 yet.

**Comment by llamahunter** [comment]
Appears they updated on June 12th to 2.10, and on July 9th to 2.11.  Will give it a try.

**Comment by llamahunter** [comment]
Ah, they have not yet released a version with prometheus v2.8.0 or later.  The current release of kube-prometheus is still using v2.7.2.

**Comment by csmarchbanks** [comment]
How are you deploying kube-prometheus?

I believe kube-prometheus deploys the prometheus operator, at which point you will just have to override the `version` field on the `Prometheus` type that is created.

**Comment by llamahunter** [comment]
Yeah, I could certainly override the version for a test.  I would sort of prefer to run a 'supported configuration' of kube-prometheus to avoid any weird versioning issues between prometheus and the other config files in kube-prometheus.  I can give it a try, tho.

**Comment by llamahunter** [comment]
Ok, so, tried v2.10.0, and it no longer fills up all memory.  But, also, oddly, it doesn't seem to complain in the prometheus logs anymore about the nonexistent server for the remote_write endpoint, either.

**Comment by brancz** [comment]
You can do arbitrary configuration in kube-prometheus, it's meant to be consumed as a library.

**Comment by llamahunter** [comment]
yes, using it as a library, and modifying the existing config files w/in the features of the supported version, but assuming you can run any version of prometheus with all those config files seems naive.

**Comment by brancz** [comment]
I hate to disappoint, but there is no such thing as "support" for kube-prometheus. If there is a real problem we'll try to troubleshoot on a best effort basis. FWIW we bump the Prometheus version independently in OpenShift (which uses kube-prometheus as a library), and we're already using v2.11.0.

**Comment by beorn7** [comment]
The original issue here is resolved. Therefore, I'm closing this.
