### ISSUE TITLE
Documentation - PromQL queries timeout / PromQL queries optimization

### ISSUE THREAD

**Issue by PedroMSantosD** [prometheus/prometheus#5754]
## Proposal
as a user, I need to be able to configure the timeout for promql queries.
This can help prevent crashing prometheus on graph queries (OOM when data is quite large/has high cardinality)
https://github.com/prometheus/prometheus/issues/4414 -> indicates some limits are in place, but no mention on how can the user control them.

as a user, I need to know the best practises for optimising PromQL queries (that either take too long, or get killed by the default OOM for prometheus queries)
- how do I limit the metrics that have high cardinality, so that only matching labels are used (?)
- how do I best operate on several metrics on a single query? is there a way to first extract  the subset of metrics using the exactly-matched-by-label ones (single point) and then operate between them?

As a user, I need to find out the implications of remote read/writes on a prometheus server:
- Does this mean that the server will have "current" in memory metrics, and use the "remote storage" for persisting to disk and reading times older than the ones allocated in memory?
- How is a complex query for old data handled? Will prometheus wait for a response from the remote storage raw-data and then start processing -in-memory- or will the remote-storage provide the resulting vectors/points from the query so prometheus only adds this results to its in-memory data?

**Comment by beorn7** [comment]
Hello from the bug scrub.

Timeouts per query have been implemented a while ago, see https://prometheus.io/docs/prometheus/latest/querying/api/#instant-queries (`timeout` query parameter).

The other questions are more subtle to answer. We would like to defer to discussions on the internet.
