### ISSUE TITLE
Updating information through recording rules

### ISSUE THREAD

**Issue by cmusik** [prometheus/prometheus#5755]
## Bug Report
**What did you do?**
We use recording rules to create metrics with information about system. Something like location and status to be able to pass this information to alertmanager. This information is updated through an automated process and it reloads prometheus.
After the update to version 2.10 we see the metric with old and new labels.

e.g.
```
asset_info{instance="test1",status="a",location="a"}
asset_info{instance="test1",status="b",location="a"}
```

In version 2.8.0 there was only one metric after the prometheus reload.

The query we use to trigger this looks like this.
```
up{exported_instance="i"} * on(exported_instance) group_left(status, location) asset_info
```

**What did you expect to see?**
After reload the asset information is updated and not reported twice.

**What did you see instead? Under which circumstances?**
The asset metric is shown twice instead of one after an update of a value.

**Environment**

* Prometheus version:
```
# prometheus --version
prometheus, version 2.10.0 (branch: HEAD, revision: d20e84d0fb64aff2f62a977adc8cfb656da4e286)
  build user:       root@a49185acd9b0
  build date:       20190525-12:28:13
  go version:       go1.12.5
```

* Testcase
```
#!/bin/bash

function cleanup() {
    kill $WEB
    kill $PROMETHEUS
}

trap cleanup SIGINT SIGTERM

TMP=$(mktemp -d)

echo "changing to $TMP"

cd $TMP
echo 'up{instance="i"} 1' > metrics


cat > prometheus.yml <<EOF
global:
  scrape_interval: 10s
  scrape_timeout: 5s
  evaluation_interval: 10s
  external_labels:
    prometheus_scraper: test

rule_files:
  - rules.yml

scrape_configs:
  - job_name: 'example1'
    metrics_path: '/metrics'
    static_configs:
      - targets: [127.0.0.1:8000]
EOF

cat > rules.yml <<EOF
groups:
  - name: asset_info
    interval: 10s
    rules:
      - record: asset_info
        expr: 1
        labels:
          exported_instance: "i"
          asset_status: "test"
          asset_location: "test"
          testlabel: "a"

  - name: linux
    interval: 10s
    rules:
      - alert: TestAlert
        expr: up{exported_instance="i"} * on(exported_instance) group_left(asset_status, asset_location) asset_info
        for: 2m
EOF

python -m SimpleHTTPServer &
WEB=$!
prometheus &
PROMETHEUS=$!

sleep 15

sed -e 's/testlabel: ".*"/testlabel: "'$RANDOM'"/' -i rules.yml
kill -SIGHUP $PROMETHEUS

wait
```

If you run this, you will see evaluation errors after some seconds.

**Affected version**
I have bisected it and found that change e15d8c5802f98b6a508022500acf44e91adc7d87 is the culprit here. It is also the case in master branch.

**Comment by brian-brazil** [comment]
Did this happen for more than 5 minutes after the reload?

**Comment by cmusik** [comment]
Oh, I forgot that important information. This error vanishes after 5 minutes after the second (and old) metric gets removed.

**Comment by brian-brazil** [comment]
#5759 should handle this, and passes your useful testcase.

**Comment by cmusik** [comment]
Just tried your fix and it looks really good. Thank you!
