### ISSUE TITLE
Query range Error executing query: vector cannot contain metrics with the same labelset

### ISSUE THREAD

**Issue by xigang** [prometheus/prometheus#5757]
## Bug Report
**What did you do?**
- Configuring prometheus to read data from influxdb
- Use the following promeQL to query data from prometheus:
```
sum (rate(container_cpu_usage_seconds_total{image!="",container_name!="POD",pod_name="xdadmin-test-2-ae72dc-5b494dcc9b-wmv5d",namespace="xapi", container_name="php-swoole-base"}[1m])) by (container_name) * 100
```
**What did you expect to see?**
a constant result

**What did you see instead? Under which circumstances?**
use prometheus version 2.10.0:
error: Error executing query: vector cannot contain metrics with the same labelset

![image](https://user-images.githubusercontent.com/3377677/61102009-b762bc00-a49e-11e9-9cdb-42e9c0d4a972.png)
Last 5 hour
![image](https://user-images.githubusercontent.com/3377677/61103917-a453ea00-a4a6-11e9-808d-2bf83ef0348b.png)

Last 6hour
![image](https://user-images.githubusercontent.com/3377677/61103797-1f68d080-a4a6-11e9-85eb-2d886688cbf4.png)

Using prometheus version 2.0.0 does not have this problem above.
![image](https://user-images.githubusercontent.com/3377677/61106258-26481100-a4af-11e9-9f1b-392c5faa6cbd.png)

**Environment**

* System information:

	3.10.0-327.36.3.el7.x86_64

* Prometheus version:

       prometheus, version 2.10.0 (branch: HEAD, revision: d20e84d0fb64aff2f62a977adc8cfb656da4e286)
       build user:       root@a49185acd9b0
       build date:       20190525-12:28:13
       go version:       go1.12.5

* Alertmanager version:
NONE
* Prometheus configuration file:
```
global:
  scrape_interval:     15s
  evaluation_interval: 15s

  remote_read:
  - url: "http://xx.xx.xx.xx:28006/api/v1/prom/read?p=30421d571288d95b&u=prometheusA&db=prometheusA"
    remote_timeout: 1m
  - url: "http://xx.xx.xx.xx:28003/api/v1/prom/read?p=3d03ec241f747891&u=promethuesB&db=promethuesB"
    remote_timeout: 1m
```

* Alertmanager configuration file:
NONE

* Logs:
```
Jul 10 10:34:47 node systemd[1]: Started Prometheus server.
Jul 10 10:34:47 node systemd[1]: Starting Prometheus server...
Jul 10 10:34:47 node prometheus[11559]: level=warn ts=2019-07-10T02:34:47.294Z caller=main.go:275 deprecation_notice="'storage.tsdb.retention' flag is deprecated use 'storage.tsdb.retention.time' instead."
Jul 10 10:34:47 node prometheus[11559]: level=info ts=2019-07-10T02:34:47.294Z caller=main.go:322 msg="Starting Prometheus" version="(version=2.10.0, branch=HEAD, revision=d20e84d0fb64aff2f62a977adc8cfb656da4e286)"
Jul 10 10:34:47 node prometheus[11559]: level=info ts=2019-07-10T02:34:47.294Z caller=main.go:323 build_context="(go=go1.12.5, user=root@a49185acd9b0, date=20190525-12:28:13)"
Jul 10 10:34:47 node prometheus[11559]: level=info ts=2019-07-10T02:34:47.294Z caller=main.go:324 host_details="(Linux 3.10.0-327.36.3.el7.x86_64 #1 SMP Mon Oct 24 16:09:20 UTC 2016 x86_64 node (n
Jul 10 10:34:47 node prometheus[11559]: level=info ts=2019-07-10T02:34:47.294Z caller=main.go:325 fd_limits="(soft=1048576, hard=1048576)"
Jul 10 10:34:47 node prometheus[11559]: level=info ts=2019-07-10T02:34:47.294Z caller=main.go:326 vm_limits="(soft=unlimited, hard=unlimited)"
Jul 10 10:34:47 node prometheus[11559]: level=info ts=2019-07-10T02:34:47.296Z caller=main.go:645 msg="Starting TSDB ..."
Jul 10 10:34:47 node prometheus[11559]: level=info ts=2019-07-10T02:34:47.296Z caller=web.go:417 component=web msg="Start listening for connections" address=0.0.0.0:9090
Jul 10 10:34:47 node prometheus[11559]: level=info ts=2019-07-10T02:34:47.305Z caller=main.go:660 fs_type=XFS_SUPER_MAGIC
Jul 10 10:34:47 node prometheus[11559]: level=info ts=2019-07-10T02:34:47.305Z caller=main.go:661 msg="TSDB started"
Jul 10 10:34:47 node prometheus[11559]: level=info ts=2019-07-10T02:34:47.305Z caller=main.go:730 msg="Loading configuration file" filename=/usr/local/prometheus/prometheus.yml
Jul 10 10:34:47 node prometheus[11559]: level=info ts=2019-07-10T02:34:47.311Z caller=main.go:758 msg="Completed loading of configuration file" filename=/usr/local/prometheus/prometheus.yml
Jul 10 10:34:47 node prometheus[11559]: level=info ts=2019-07-10T02:34:47.311Z caller=main.go:614 msg="Server is ready to receive web requests."
Jul 10 10:35:59 node prometheus[11559]: level=error ts=2019-07-10T02:35:59.928Z caller=api.go:1115 component=web msg="error writing response" bytesWritten=0 err="write tcp xx.xx.xx.xx:9090->xx.xx.xx.xx:57561: writ
Jul 10 10:47:08 node prometheus[11559]: level=error ts=2019-07-10T02:47:08.905Z caller=api.go:1115 component=web msg="error writing response" bytesWritten=0 err="write tcp xx.xx.xx.xx:9090->xx.xx.xx.xx:60194: writ
Jul 12 10:58:55 node prometheus[11559]: level=info ts=2019-07-12T02:58:55.057Z caller=main.go:730 msg="Loading configuration file" filename=/usr/local/prometheus/prometheus.yml
Jul 12 10:58:55 node systemd[1]: Reloaded Prometheus server.
Jul 12 10:58:55 node prometheus[11559]: level=info ts=2019-07-12T02:58:55.117Z caller=main.go:758 msg="Completed loading of configuration file" filename=/usr/local/prometheus/prometheus.yml
Jul 12 11:11:17 node prometheus[11559]: level=error ts=2019-07-12T03:11:17.525Z caller=api.go:1115 component=web msg="error writing response" bytesWritten=0 err="write tcp xx.xx.xx.xx:9090->xx.xx.xx.xx:50216: wri
lines 12714-12779/12779 (END)
```

**Comment by juliusv** [comment]
@xigang Any result (or sub-result) of a PromQL query may not contain the same labelset twice (you can only have one sample value for a given series at a given time), but probably Prometheus 2.0.0 simply did not have a check for this condition yet.

I suspect that InfluxDB contains (or at least is returning) the same series twice at the same timestamp. Can you check this on the InfluxDB side?

**Comment by xigang** [comment]
@juliusv Thank you for your reply.

FIrst:
Yes, prometheus 2.0.0 did not check for this condition, but promethues 2.10.0 checked this.

Check logic in prometheus 2.10.0:
https://github.com/prometheus/prometheus/blob/ead0933dd9065602e234ae907eee17a6dd208601/promql/engine.go#L1062

The logic in prometheus 2.0.0:
https://github.com/prometheus/prometheus/blob/v2.0.0/promql/engine.go#L672

Second:
For influxdb, we have a secondary development of the open source influxdb, which may be related. We check out the influxdb

**Comment by brian-brazil** [comment]
Sounds like Influx is sending us bad data somehow, if this turns out to actually be an issue on our end please let us know.
