### ISSUE TITLE
Prometheus 2.2.1 WAL files wouldn't be deleted automatically when met some error

### ISSUE THREAD

**Issue by benamazing** [prometheus/prometheus#5764]
Hi, i deployed a prometheus with version 2.2.1, and got below error several times.

<pre>
Jul  8 09:51:17 172-16-8-161 prometheus: level=error ts=2019-07-08T01:51:17.050093825Z caller=engine.go:516 component="query engine" msg="error expanding series set" err="invalid encoding \"<unknown>\""
Jul  8 09:51:17 172-16-8-161 prometheus: level=error ts=2019-07-08T01:51:17.050261468Z caller=engine.go:516 component="query engine" msg="error expanding series set" err="invalid encoding \"<unknown>\""
Jul  8 09:51:17 172-16-8-161 prometheus: level=error ts=2019-07-08T01:51:17.050291679Z caller=engine.go:516 component="query engine" msg="error expanding series set" err="invalid encoding \"<unknown>\""
Jul  8 09:51:17 172-16-8-161 prometheus: level=error ts=2019-07-08T01:51:17.050367252Z caller=engine.go:516 component="query engine" msg="error expanding series set" err="invalid encoding \"<unknown>\""
Jul  8 09:51:17 172-16-8-161 prometheus: level=error ts=2019-07-08T01:51:17.05040113Z caller=engine.go:516 component="query engine" msg="error expanding series set" err="invalid encoding \"<unknown>\""
</pre>

When encountering such error, i found below scenarios afterwards.

1. The WAL(write ahead log) files wouldn't be deleted automatically, and keep increasing.
2. The memory usage kept increasing until oom and got killed by system oom killler.
3. When restarted it, it failed to restart (or took a quite a long time to restart) due to too many WAL files to be replayed, and consumed too much memory.
4. Therefore, could only manually remove some WAL files to restore it again.
5. However, when the prometheus process was resumed, it could lead to:
    (1), data loss, due to manually remove WAL files
    (2). some duplicated samples with same timestamp and same values. According to the log, i suspect that was caused by the some data were already compacted to block, but the WAL hasn't been removed, so when restarting prometheus, it replayed the WAL again, and therefore duplicate data occurred, as i saw msg="compact blocks" but no msg="WAL truncation completed" in the end.

Is this a bug of version 2.2.1?

**Comment by simonpasquier** [comment]
2.2.1 isn't supported anymore and many improvements have been made to the WAL code as well as TSDB in general. I suggest that you update Prometheus to the latest version and try again. As for deletion, the current policy is not to delete anything automatically as it would hide the problems and may not be appropriate for some users.

I'm closing it for now. If you have further questions, please use our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search.
