### ISSUE TITLE
Promtool doesn't work with PrometheusRules for prometheus-operator

### ISSUE THREAD

**Issue by jowparks** [prometheus/prometheus#5767]
Currently the `promtool` only works with raw rule definition yaml. Would be nice (and simple to implement) ability to use promtool on PrometheusRule definitions for the prometheus-operator
[related issue](https://github.com/coreos/prometheus-operator/issues/2273)
## Proposal
Allows usage of standard `promtool test rules` with kubernetes PrometheusRules

Current workaround I am using a small simple wrapper (note `yq` I am using is from brew not pip)
```
cat $1 | yq r - spec > temprule
echo "rule_files:\n  - temprule\n\n" | cat - $1.promtest > temptest
promtool test rules temptest
rm temprule
rm temptest
```

**Comment by brian-brazil** [comment]
I don't think it's the role of promtool to handle formats not defined by Prometheus itself, this is something that'd better live in the operator.

**Comment by brancz** [comment]
agreed

**Comment by jowparks** [comment]
I agree formats not defined for prometheus directly should not be handled here (ie the entire PrometheusRule), but what I was suggesting was for the `promtool` unittest field we provide the option of specifying a field directive
ie 
```
rule_files:
  - rule.yaml:spec
```
This would allow a rule to exist in any yaml and still be tested with the standard promtool.

**Comment by brancz** [comment]
I think it'd be better if it was either possible that "rule_files" come from stdin or you just use something like [faq](https://github.com/jzelinskie/faq) to extract the `.spec` content and write it to where the unit test file expects.

**Comment by juliusv** [comment]
Agreed, allowing reading from stdin would be nice to not require a temporary FS storage location.

**Comment by brian-brazil** [comment]
Does using /dev/stdin not work?

**Comment by brancz** [comment]
You're right, it should probably work.

**Comment by juliusv** [comment]
Yes, that works, great. Will close this then, as it can be written in a single command-line using an external tool which is better suited for supporting various non-Prometheus-native formats than promtool itself.
