### ISSUE TITLE
change Job Name,the data is not consistence,how synchronize data?

### ISSUE THREAD

**Issue by NaturAlex** [prometheus/prometheus#5777]
## Proposal
**Use case. Why is this important?**
change Job Name,the data is not consistence,how synchronize data?
*“Nice to have” is not a good use case. :)*

## Bug Report
**What did you do?**
i change job name
**What did you expect to see?**
i want old data and new data synchronize,connect together
**What did you see instead? Under which circumstances?**

**Environment**

* System information:

	centOS7

* Prometheus version:

	2.11

* Alertmanager version:

	0.18
* Prometheus configuration file:
```
insert configuration here
```

* Alertmanager configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```

**Comment by simonpasquier** [comment]
You can't modify the data that's written on disk but you could probably use `label_replace()`.

I'm closing it for now. If you have further questions, please use our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search.
