### ISSUE TITLE
Licenses not opensource in prometheus 2.9.2 

### ISSUE THREAD

**Issue by luisapace** [prometheus/prometheus#5783]
Hi, my team would use prometheus 2.9.2 and to approve that I've to verify that all its licenses are acceptable.

Now I've seen that prometheus 2.9.2 contains the following: 

1. https://github.com/prometheus/prometheus/blob/v2.9.2/vendor/github.com/cockroachdb/cockroach/LICENSE
2. reference to https://glyphicons.com/license/ at https://github.com/prometheus/prometheus/blob/v2.9.2/vendor/github.com/influxdata/influxdb/LICENSE_OF_DEPENDENCIES.md 

Both of them are not opensource licenses.

So my question is: 
Is there any code in prometheus 2.9.2 under those licenses? and if so, what is that code?

If - instead - there is no code in prometheus 2.9.2 under those licenses, could you please clarify why prometheus 2.9.2 lists those licences?

Thanks for your help.

**Comment by simonpasquier** [comment]
The LICENSE files are added by `go mod vendor` whenever we add/update a dependency to the repository.

Irrespective of whether those licenses apply:
* All code from cockroachdb has been removed very recently (see #5743) so the next release of Prometheus (v2.12.0) won't be dependent on it anymore.
* The influxdb dependency comes from the [remote adapter](https://github.com/prometheus/prometheus/tree/master/documentation/examples/remote_storage/remote_storage_adapter) example program so it isn't compiled in the Prometheus binary. In addition Influxdb removed the dependency to glyphicons a while ago but [forgot](https://github.com/influxdata/influxdb/pull/8860) to update its documentation.

**Comment by brancz** [comment]
> The influxdb dependency comes from the remote adapter example program so it isn't compiled in the Prometheus binary. In addition Influxdb removed the dependency to glyphicons a while ago but forgot to update its documentation.

Being an example, maybe we should rather move it to a separate repo (maybe in prometheus-community?) and link to it?

**Comment by simonpasquier** [comment]
@brancz I was thinking the same thing after writing it. I think the examples would be better served in their own repository (it is also the case with the SD adapter code).

**Comment by luisapace** [comment]
Thanks to all of you for your fast foll-up.

**Comment by cstyan** [comment]
> Being an example, maybe we should rather move it to a separate repo (maybe in prometheus-community?) and link to it?

> (it is also the case with the SD adapter code).

Sounds good to me
