### ISSUE TITLE
Remote_write unexpected resource usage

### ISSUE THREAD

**Issue by hagen1778** [prometheus/prometheus#5786]
# Bug Report
**What did you do?**
I'm running pretty busy Prometheus 2.11.1 for federation. It usually consumes ~100GB of RAM(total is 128), ingestion rate is ~40MB/s. Some metrics:
* sum(prometheus_tsdb_head_series) - 3584581791
* sum(rate(prometheus_tsdb_head_samples_appended_total[5m])) - 52202271

**What did you expect to see?**
I expected to see Prometheus writing into remote storage, CPU increase and egress traffic equal to ingress or lower.

**What did you see instead? Under which circumstances?**

CPU usage increased as expected. But egress traffic to remote storage hit 60MB/s (ingress is 40) which is quite unexpected).
Moreover, every 2h or 4h Prometheus were killed by OOM killer.
Remote storage was working fine, metric `prometheus_remote_storage_enqueue_retries_total` was equal to 0.

**Environment**

* System information:

	Linux 4.14.86-generic x86_64

* Prometheus version:

	Prometheus 2.11.1

* Alertmanager version:

       n/a

* Prometheus configuration file:
```
remote_write:
- url: http://remote-storage
  remote_timeout: 30s
  queue_config:
    capacity: 10
    max_shards: 100
    min_shards: 1
    max_samples_per_send: 10000
    batch_send_deadline: 5s
    min_backoff: 30ms
    max_backoff: 100ms
```

* Logs:
```
 journalctl -u prometheus | grep 'remote'
prometheus: ts=2019-07-18T10:10:02.622Z caller=dedupe.go:111 component=remote level=info queue=0:http://remote-storage msg="starting WAL watcher" queue=0:http://remote-storage
prometheus: ts=2019-07-18T10:10:02.808Z caller=dedupe.go:111 component=remote level=info queue=0:http://remote-storage msg="Stopping remote storage..."
prometheus: ts=2019-07-18T10:10:02.831Z caller=dedupe.go:111 component=remote level=error queue=0:http://remote-storage msg="error tailing WAL" err="readCheckpoint: readCheckpoint wasn't able to read all data from the checkpoint /state/prometheus/data/wal/checkpoint.405041/00000000, size: 133660672, totalRead: 8596156"
prometheus: ts=2019-07-18T10:10:02.831Z caller=dedupe.go:111 component=remote level=info queue=0:http://remote-storage msg="WAL watcher stopped" queue=0:http://remote-storage
prometheus: ts=2019-07-18T10:10:02.882Z caller=dedupe.go:111 component=remote level=info queue=0:http://remote-storage msg="Remote storage stopped."
prometheus: level=info ts=2019-07-18T10:39:26.377Z caller=wal_watcher.go:149 component=remote queue=0:http://remote-storage msg="starting WAL watcher" queue=0:http://remote-storage
prometheus: level=info ts=2019-07-18T10:46:16.377Z caller=queue_manager.go:499 component=remote queue=0:http://remote-storage msg="Remote storage resharding" from=1 to=100```

**Comment by YaoZengzeng** [comment]
Actually in Prometheus 2.11, it read from WAL and write to remote storage instead of forwarding ingress directly to egress. So the ingress traffice may not be equal to engress.

And if prometheus restarts and it already have wal, the egress traffic may reach its max speed which related to `max_shards` and `max_samples_per_send` in queue_config.

As for OOM, I don't know the size of memory of your machine. But in my cluster, 500k series may consume 7~8G. The series in your case is such huge, maybe more memory is needed :joy:

**Comment by cstyan** [comment]
If your Prometheus instance is near it's memory limit before adding in remote write it's definitely going to OOM when you add in remote write if you don't give it more memory. From what I remember we saw about a 20% increase in memory used during normal operations with the new WAL based remote write. The goal was that the new remote write doesn't OOM your prometheus instance.

I'm assuming it's OOM'ing every 2 hours or so when truncation/checkpointing happens, which will increase memory usage while those processes occur.

To reduce the memory usage of remote write, you could reduce the max # of shards or max samples per send, or add relabel rules to drop some metrics from remote write.

Are you using federation to grab all metrics from all your other Prometheus instances?

**Comment by hagen1778** [comment]
Hi @cstyan 

> To reduce the memory usage of remote write, you could reduce the max # of shards or max samples per send, or add relabel rules to drop some metrics from remote write.

It turns out that 60MB/s is not the limit. When I increased number of shards to 2k egress increased to 150mb/s, so reducing number of shards is not the option.
The way I solved it is to set GOGC to 50, which increases CPU usage but helps Prometheus to survive during checkpoints.

> Are you using federation to grab all metrics from all your other Prometheus instances?

No, but still a lot - it is non-trivial task to control churn in large teams)

**Comment by cstyan** [comment]
> so reducing number of shards is not the option

Just a suggestion if you weren't able to increase memory.

If you're using remote write anyways you could simply remote write from the lower level Prometheus instances and reduce your usage of or do away with federation.

Let me know if you have other questions or concerns and we can dig into them.

**Comment by beorn7** [comment]
This seems to be more a configuration tuning problem than an actual bug. I'm therefore closing this issue. For more discussions around configuring and tweaking remote write, you could also use the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users).
