### ISSUE TITLE
Bogus incomplete scrape failures on restart

### ISSUE THREAD

**Issue by tbregolin** [prometheus/prometheus#5788]
## Bug Report
**What did you do?**
Restarted the Prometheus instance doing the scrapes.
**What did you expect to see?**
I expected the incomplete scrape to not be written to TSDB as a failure, since it was caused by Prometheus itself being shut down gracefully.
**What did you see instead? Under which circumstances?**
Prometheus considered the scrape failed, and triggered an alert when it came back up.
**Environment**

* System information:

	Linux 4.14.102 x86_64

* Prometheus version:

	prometheus, version 2.11.1 (branch: master, revision: 9856b12928dbcc9f69abc863ac0dd4bfd3673781)
	  build user:       builder@localhost
	  build date:       20190717-13:22:20
	  go version:       go1.12.7

* Logs:
Prometheus logs showing the restart:
```
Jul 20 15:45:07 prom0 systemd[1]: Stopping prometheus monitoring system...
Jul 20 15:45:07 prom0 prometheus[130410]: level=warn ts=2019-07-20T15:45:07.701Z caller=main.go:496 msg="Received SIGTERM, exiting gracefully..."
Jul 20 15:45:07 prom0 prometheus[130410]: level=info ts=2019-07-20T15:45:07.701Z caller=main.go:521 msg="Stopping scrape discovery manager..."
Jul 20 15:45:07 prom0 prometheus[130410]: level=info ts=2019-07-20T15:45:07.701Z caller=main.go:535 msg="Stopping notify discovery manager..."
Jul 20 15:45:07 prom0 prometheus[130410]: level=info ts=2019-07-20T15:45:07.701Z caller=main.go:557 msg="Stopping scrape manager..."
Jul 20 15:45:07 prom0 prometheus[130410]: level=info ts=2019-07-20T15:45:07.701Z caller=main.go:517 msg="Scrape discovery manager stopped"
Jul 20 15:45:07 prom0 prometheus[130410]: level=info ts=2019-07-20T15:45:07.701Z caller=main.go:531 msg="Notify discovery manager stopped"
Jul 20 15:45:07 prom0 prometheus[130410]: level=info ts=2019-07-20T15:45:07.935Z caller=manager.go:776 component="rule manager" msg="Stopping rule manager..."
Jul 20 15:45:07 prom0 prometheus[130410]: level=info ts=2019-07-20T15:45:07.935Z caller=main.go:551 msg="Scrape manager stopped"
Jul 20 15:45:07 prom0 prometheus[130410]: level=info ts=2019-07-20T15:45:07.935Z caller=manager.go:782 component="rule manager" msg="Rule manager stopped"
Jul 20 15:45:07 prom0 prometheus[130410]: level=info ts=2019-07-20T15:45:07.957Z caller=notifier.go:602 component=notifier msg="Stopping notification manager..."
Jul 20 15:45:07 prom0 prometheus[130410]: level=info ts=2019-07-20T15:45:07.957Z caller=main.go:722 msg="Notifier manager stopped"
Jul 20 15:45:07 prom0 prometheus[130410]: level=info ts=2019-07-20T15:45:07.957Z caller=main.go:734 msg="See you next time!"
Jul 20 15:45:07 prom0 systemd[1]: Stopped prometheus monitoring system.
Jul 20 15:45:07 prom0 systemd[1]: prometheus.service: Consumed 4.295s CPU time
Jul 20 15:45:07 prom0 systemd[1]: Started prometheus monitoring system.
Jul 20 15:45:08 prom0 prometheus[131376]: level=info ts=2019-07-20T15:45:08.013Z caller=main.go:329 msg="Starting Prometheus" version="(version=2.11.1, branch=master,
```
Logs from the other Prometheus instance being scraped by the first one, showing the scrape failure:
```
Jul 20 15:45:10 prom1 prometheus[63212]: level=error ts=2019-07-20T15:45:10.131434661Z caller=federate.go:184 component=web msg="federation failed" err="write tcp 10.0.0.16:3000->10.0.0.16:16446: write: broken pipe"
```
Nginx logs for the other Prometheus instance being scraped by the first one, showing the request failed because the client closed the connection:
```
[20/Jul/2019:15:45:07 +0000] "GET /federate?match%5B%5D=%7B__name__%3D%22up%22%7D HTTP/1.1" 499 0 "-" "Prometheus/2.11.1"
[20/Jul/2019:15:45:40 +0000] "GET /federate?match%5B%5D=%7B__name__%3D%22up%22%7D HTTP/1.1" 200 1083199 "-" "Prometheus/2.11.1"
```

Image showing the metric value was 0 until the next scrape ran, 30 seconds later: https://i.ibb.co/V3xsyB0/failure.png

Does it make sense to write an incomplete scrape down as a failure when the only reason it failed is because Prometheus itself was being restarted? I think it would be best to either wait for all the scrapes to return before shutting down, or discard them and not update the metric as a failure.

This might be related to https://github.com/prometheus/prometheus/issues/1169.

**Comment by brian-brazil** [comment]
Can you share the alerting rule?

**Comment by tbregolin** [comment]
Thank you for looking into this.

Here is the alerting rule:
```
- alert: Colo_Prometheus_Unreachable
  expr: sum(up{job="federate"}) without (instance) == 0
  # Wait 3m to avoid alerting on transient network issues
  for: 3m
  labels:
    notify: ops
    priority: "1"
  annotations:
    summary: Failed to scrape Prometheus in {{ $labels.colo_name }}
```

These are the scrape configs:
```
- file_sd_configs:
  - files:
    - /etc/prometheus/targets/nodes.json
  honor_labels: true
  job_name: federate
  metrics_path: /federate
  params:
    match[]:
    - '{__name__="up"}'
  scheme: https
  scrape_interval: 30s
```

Also, for what it's worth, I had an issue with disk space, which corrupted some things, so I had just erased the data dir right before this happened, but neglected to stop Prometheus first:
```
Jul 20 15:44:58: cd /var/lib/prometheus/data && rm -rf 01DFEVRXT0FHKX9FRX5HJ7HMPE 01DFGSK1WKCCQ846ME79AC167S 01DFJQFRFNDMPFP4VA7F98NKR7 01DFMNA9CT3NQYJ68MZV3BVCW5 01DFPK3HKCJM9QCZB1HER094W0 01DFRGWZ0ZBJF9XXQQB73HCHKE 01DFTEQAT8TTQJJDN1BTK4765F 01DFWCFRPJ7V03ZS059GN3VAZ1 01DFXMR0XH7VHDWTVF3NT2EEDW.tmp 01DFYA9DPRJ9WMQ0E2MVHGKY24 01DG082Z9VEY0DP0TGAZBDW3E1 01DG25W8MET6B96HQ33YXR5QQ8 01DG43N9551H41X51XNQ7KH88J 01DG61FBPME5VPDWNTS8Q5G8SM 01DG6NR5XCW79TY7485T50PZ3W 01DG79QZMDY8TCXE590MEPJXY9 01DG7ABCAQDZFWHZWWGEWA28M9 01DG7GKPWF0E0EXK67QVY7YQCQ 01DG7QFE4EFX3XG1KET6GDNDE9 lock wal
Jul 20 15:45:07: systemctl restart prometheus
```
Not sure if this accounts for the unwanted alert or not.

**Comment by brian-brazil** [comment]
That's probably it rather than the restart itself, the alerting across
restarts logic doesn't apply with a for that short.

**Comment by tbregolin** [comment]
That's fair enough. Given that this wasn't the best way to erase the data and restart, and that this is somewhat of an edge case, I think we can close it. Please feel free to re-open if you think there's something worth fixing related to this.
