### ISSUE TITLE
Add new metric: retention size bytes

### ISSUE THREAD

**Issue by smoerboegen** [prometheus/prometheus#5790]
## Proposal
Adding a metric that exposes the currently configured retention size for tsdb storage could be useful for monitoring storage needs.

I would like to be able to use this metric to determine when we need a larger storage volume or otherwise move our data somewhere else.

Of course I could use the size of that actual filesystem but Prometheus is not always the only application storing data in the same filesystem, I just wan't to know how close we are to hitting our storage retention limit.

**Comment by YaoZengzeng** [comment]
I'd like to make PR for this :)

**Comment by krasi-georgiev** [comment]
@smoerboegen What would an example workflow, promql query would look like ?
Just trying to understand how would you use that.

**Comment by krasi-georgiev** [comment]
btw, not sure it helps but there is an api to get the flags
https://prometheus.io/docs/prometheus/latest/querying/api/#flags

**Comment by smoerboegen** [comment]
@krasi-georgiev I'm thinking somethin along the lines of a new exposed metric: "prometheus_tsdb_size_retention_bytes" that returns the currently configured size retention in bytes.

It could be used in this manner to return your current usage in percent:
`prometheus_tsdb_storage_blocks_bytes / prometheus_tsdb_size_retention_bytes * 100`

This way I could easily see if I'm close to my size limit before hitting it. This can be solved with just static values of course, but this would make this case a bit more dynamic.
