### ISSUE TITLE
Reverse proxy - external URL hostname ignored

### ISSUE THREAD

**Issue by janotav** [prometheus/prometheus#5791]
My apologies for using github for asking question. I tried the prometheus users group, but the question went unnoticed: https://groups.google.com/forum/#!topic/prometheus-users/AkE9YujMxV8

I'm trying to run prometheus behind reverse proxy with:

      --web.external-url=http://hostthatdoesnotexist:9090/prometheus
      --web.route-prefix=/prometheus

And I'm still able to access it without noticing any incorrect behaviour due to invalid host being used.

When inspecting the HTML, I can see that all resources are referenced using relative path, which makes prometheus correctly retrieve all HTML elements.

I wonder if there is something weird with my setup or only the path portion of the external url is being used by prometheus when referencing resources.

**Comment by simonpasquier** [comment]
I've replied to the email thread. Closing it for now.
