### ISSUE TITLE
command line param --query.lookback-delta is no use

### ISSUE THREAD

**Issue by jigetage** [prometheus/prometheus#5798]
HELP!
I use docker-compose to deploy prometheus and set config like down below:

`command: --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yml --query.lookback-delta='2m' --storage.tsdb.retention.time='365d'`

In the end, --web.enable-lifecycle, --web.enable-lifecycle, and --web.enable-lifecycle work, but --query.lookback-delta doesn't. 

Perhaps you may ask why do you use --query.lookback-delta? 
Because i just want data scraped in the last 2 minutes. 
For example, there is a metric named job_info. The last scrape of job_info came 5 minutes ago.
Now, I query job_info using http api. The expected result is I get nothing. But, unfortunately, I still get job_info data. It seems --query.lookback-delta doesn't work.
So, could you tell me why? Did I use it in the wrong way? Or it's a bug?

Thank you in advance and any reply would be highly appreciated!

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by jigetage** [comment]
> It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

ok, ok, you are right
