### ISSUE TITLE
Unable to delete metrics although getting a 204 response

### ISSUE THREAD

**Issue by schybbkoh** [prometheus/prometheus#5799]
Creating the ticket here after some basic StackOverflow triage was unsuccessful: https://stackoverflow.com/questions/57160635/prometheus-metrics-do-not-disapper-after-being-deleted

**What did you do?**
I have a two-VM Prometheus cluster running version `2.6.1`. There are some metrics that I need to delete and seem to be unable to do so. 

`admin-api` is enabled:
` └─28557 /opt/prometheus/prometheus-server/prometheus --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/data/prometheus/databases --storage.tsdb.retention=15d --web.enable-admin-api --web.external-url=http://redacted --log.level=debug`

I run `curl -X POST -g 'http://localhost:9090/api/v1/admin/tsdb/delete_series?match[]={instance="my-hostname"}' -v` on both VMs.

**What did you expect to see?**
Expected for all metrics containing `instance="my-hostname"` label (ie. `metricName{label="xxx",label="yyy",instance="my-hostname"}` to not be searchable / graphable etc - so to efectively disappear.

**What did you see instead? Under which circumstances?**

Got `204` as expected
```
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 9090 (#0)
> POST /api/v1/admin/tsdb/delete_series?match[]={instance="my-hostname"} HTTP/1.1
> Host: localhost:9090
> User-Agent: curl/7.47.0
> Accept: */*
>
< HTTP/1.1 204 No Content
< Access-Control-Allow-Headers: Accept, Authorization, Content-Type, Origin
< Access-Control-Allow-Methods: GET, OPTIONS
< Access-Control-Allow-Origin: *
< Access-Control-Expose-Headers: Date
< Date: Tue, 23 Jul 2019 07:54:30 GMT
<
* Connection #0 to host localhost left intact
```

The metrics containing the label are still visible in the "graph" and "alerts" web-interface tabs.
The metric is also available when curling directly the API `curl -g 'http://localhost:9090/api/v1/series?match[]=metricName{instance="my-hostname"}'`

Cleaning tombstones (`curl -X POST -g 'http://localhost:9090/api/v1/admin/tsdb/clean_tombstones' -v`), reloading Prometheus processes, restarting the VMs, waiting 48 hours didn't change a thing.

Also tried deleting some more narrow set of metrics (`curl -X POST -g 'http://localhost:9090/api/v1/admin/tsdb/delete_series?match[]={label="xxx",label="yyy",instance="my-hostname"}'`) with no effect.

**System information:**

`Linux 4.15.0-1041-azure x86_64`

**Prometheus version:**

```
prometheus, version 2.6.1 (branch: HEAD, revision: b639fe140c1f71b2cbad3fc322b17efe60839e7e)
build user:       root@4c0e286fe2b3
build date:       20190115-19:12:04
go version:       go1.11.4
```

**Comment by brian-brazil** [comment]
Can you please provide your config, and the exact commands and queries you're using without any placeholders?

**Comment by schybbkoh** [comment]
Sadly I am not able to provide you with the full config with no edits as it contains sensitive data (ie. host discovery secrets). Are there parts of it you need the most?

**Comment by brian-brazil** [comment]
I basically need to know if you're ingesting data with these labels, and if your PromQL query matches up with your delete command. This is more likely a typo than a bug.

**Comment by schybbkoh** [comment]
Upon further inspection it turned out that there was an unexpected node-exporter file in `/var/spool/prometheus` directory on the source host causing node-exporter to re-scrap ancient metrics over and over again. After deleting the file and re-running the delete command the metrics are gone.
Apologies for the fuss.
