### ISSUE TITLE
Dynamically update the configuration in container-based environment

### ISSUE THREAD

**Issue by rahafrouz** [prometheus/prometheus#5800]
## Proposal
**Use case. Why is this important?**
We are using prometheus for monitoring a cluster of containers that do processing over Edge of the network. [FogFlow](https://github.com/smartfog/fogflow). In a distributed system of Fog Computing, nodes come and go dynamically, and hence our components would have to add the targets dynamically. (And use APIs of prometheus dynamically according to current nodes). 

Currently, we have a hacky go program that listens to an entry point `/manual-config`. This program takes new configuration (list of targets) and updates the prometheus config file. (e.g. `etc/prometheus/tgroups/target_groups.json `).  

The feature requested is similar to [this](https://github.com/prometheus/prometheus/issues/1714). Such feature seems to be more responsibility of the docker engine like [this](https://github.com/docker/compose/issues/1809#issuecomment-488732116), however, until now, there doesn't seem to be any easy and maintainable solution. Any thoughts?

**Comment by brian-brazil** [comment]
The answer is the same, this is something that belongs outside of Prometheus itself.

**Comment by cstyan** [comment]
> In a distributed system of Fog Computing, nodes come and go dynamically, and hence our components would have to add the targets dynamically.

This is solvable via service discovery.

I wouldn't say a sidecar program that updates the prometheus config is hacky. The thanos sidecar (https://github.com/thanos-io/thanos/blob/master/docs/components/sidecar.md#reloader-configuration) and Watch (https://github.com/weaveworks/Watch) do.

**Comment by juliusv** [comment]
If only the targets are dynamic, then a custom SD sidecar using https://prometheus.io/docs/prometheus/latest/configuration/configuration/#file_sd_config seems like the right way to go (which doesn't even require a reloader in the container, as Prometheus watches the target files for changes).

Closing this for now, as it's unclear what else we would want to do here in Prometheus itself.
