### ISSUE TITLE
Improve documentation of remote-write queue_config options

### ISSUE THREAD

**Issue by hagen1778** [prometheus/prometheus#5803]
## Bug Report
**What did you do?**
I'm running pretty busy Prometheus 2.11.1 for federation and configured remote-storage.

**What did you expect to see?**
I expected to have metrics scraped by Prometheus available in remote storage. 

**What did you see instead? Under which circumstances?**
I observer "corrupted" data in remote storage(graph queried directly from remote-storage, no remote-read):
![image](https://user-images.githubusercontent.com/2902918/61993744-30017500-b068-11e9-89b2-955e9e4a8313.png)
It is unclear what is exact reason of gaps in metrics, but it strongly correlates with errors from Prometheus logs:
```
Jul 25 15:12:17 prometheus-host prometheus[32148]: level=error ts=2019-07-25T15:12:17.408Z caller=wal_watcher.go:176 component=remote queue=0:http://remote-storage-host/api/v1/write msg="error tailing WAL" err="open /state/prometheus/data/wal/00000399: no such file or directory"
Jul 25 21:13:36 prometheus-host prometheus[32148]: level=error ts=2019-07-25T21:13:36.886Z caller=wal_watcher.go:176 component=remote queue=0:http://remote-storage-host/api/v1/write msg="error tailing WAL" err="open /state/prometheus/data/wal/00001467: no such file or directory"
Jul 26 05:14:14 prometheus-host prometheus[32148]: level=error ts=2019-07-26T05:14:14.664Z caller=wal_watcher.go:176 component=remote queue=0:http://remote-storage-host/api/v1/write msg="error tailing WAL" err="open /state/prometheus/data/wal/00002934: no such file or directory"
Jul 26 13:14:49 prometheus-host prometheus[32148]: level=error ts=2019-07-26T13:14:49.295Z caller=wal_watcher.go:176 component=remote queue=0:http://remote-storage-host/api/v1/write msg="error tailing WAL" err="open /state/prometheus/data/wal/00004674: no such file or directory"
Jul 26 21:14:57 prometheus-host prometheus[32148]: level=error ts=2019-07-26T21:14:57.796Z caller=wal_watcher.go:176 component=remote queue=0:http://remote-storage-host/api/v1/write msg="error tailing WAL" err="open /state/prometheus/data/wal/00006421: no such file or directory" 
```
Every time this error happens - gap in remote storage disappears for 3 hours and then occurs again.
I can't find any anomalies in `prometheus_remote_storage_*` metrics. Writes are successful, no retries and rate is stable(except of every 2h block merges, when remote write stops for short period). 

Meanwhile I have one more Prometheus under much lower pressure which writes into the same remote storage. It has no similar errors in logs and there are no any gaps in it's metrics, which makes me think it is not the remote_storage fault.

**Environment**

* System information:

	Linux 4.14.86-generic x86_64

* Prometheus version:

	Prometheus 2.11.1

* Alertmanager version:

       n/a

* Prometheus configuration file:
```
remote_write:
- url: http://remote-storage
  remote_timeout: 30s
  queue_config:
    capacity: 10
    max_shards: 1000
    min_shards: 1
    max_samples_per_send: 2000
    batch_send_deadline: 5s
    min_backoff: 30ms
    max_backoff: 100ms
```

* Logs:
```
Jul 25 15:12:17 prometheus-host prometheus[32148]: level=error ts=2019-07-25T15:12:17.408Z caller=wal_watcher.go:176 component=remote queue=0:http://remote-storage-host/api/v1/write msg="error tailing WAL" err="open /state/prometheus/data/wal/00000399: no such file or directory"
Jul 25 21:13:36 prometheus-host prometheus[32148]: level=error ts=2019-07-25T21:13:36.886Z caller=wal_watcher.go:176 component=remote queue=0:http://remote-storage-host/api/v1/write msg="error tailing WAL" err="open /state/prometheus/data/wal/00001467: no such file or directory"
Jul 26 05:14:14 prometheus-host prometheus[32148]: level=error ts=2019-07-26T05:14:14.664Z caller=wal_watcher.go:176 component=remote queue=0:http://remote-storage-host/api/v1/write msg="error tailing WAL" err="open /state/prometheus/data/wal/00002934: no such file or directory"
Jul 26 13:14:49 prometheus-host prometheus[32148]: level=error ts=2019-07-26T13:14:49.295Z caller=wal_watcher.go:176 component=remote queue=0:http://remote-storage-host/api/v1/write msg="error tailing WAL" err="open /state/prometheus/data/wal/00004674: no such file or directory"
Jul 26 21:14:57 prometheus-host prometheus[32148]: level=error ts=2019-07-26T21:14:57.796Z caller=wal_watcher.go:176 component=remote queue=0:http://remote-storage-host/api/v1/write msg="error tailing WAL" err="open /state/prometheus/data/wal/00006421: no such file or directory" 
```

@valyala @cstyan

**Comment by hagen1778** [comment]
#5347

**Comment by cstyan** [comment]
@hagen1778 is there nothing else in your prometheus logs? I'd expect to see messages like `head GC` and `WAL checkpoint complete`. As I mentioned in the other issue, my suspicion is that the WAL is being truncated/checkpoints are being created and remote write is far enough behind that it hasn't read some WAL segments yet.

Can you have a look at what your WAL dir looks like around the time you see the `no such file or directory` error next? I imagine we'll see a new checkpoint with an index # greater than the WAL segment we were supposed to start reading.

Have you changed your retention period  or any other storage related options? Can you also post screenshots of graphs of these queries:

- ```rate(prometheus_remote_storage_highest_timestamp_in_seconds[5m])  - ignoring (queue) rate(prometheus_remote_storage_queue_highest_sent_timestamp_seconds[5m])```
- ```rate(prometheus_remote_storage_samples_in_total[5m])- ignoring(queue) rate(prometheus_remote_storage_succeeded_samples_total[5m]) - rate(prometheus_remote_storage_dropped_samples_total[5m])```
- ```prometheus_tsdb_checkpoint_creations_total```

**Comment by hagen1778** [comment]
Hi @cstyan 

Sorry for the late response. I was playing with remote_write settings trying to increase `capacity` or `shards` even more. Unfortunately this led to OOM's, so now I have only 16h of Prometheus running without restarts. 

>  is there nothing else in your prometheus logs?

There are! This is | grep "remote" output. Sorry that I forgot to mention this.

> Can you have a look at what your WAL dir looks like around the time you see the no such file or directory error next?

Wasn't able to catch this yet.

> Have you changed your retention period or any other storage related options?

Retention is `15d or 250GB` and second condition happens ever 1-2 days.

The graphs are following
![image](https://user-images.githubusercontent.com/2902918/62191965-9fc77680-b36c-11e9-8737-06aa36c52b46.png)
![image](https://user-images.githubusercontent.com/2902918/62192325-4e6bb700-b36d-11e9-9620-1b9408ca1e94.png)
![image](https://user-images.githubusercontent.com/2902918/62192398-74915700-b36d-11e9-920f-99f01a93dd01.png)

**Comment by cstyan** [comment]
The second graph is the real problem. Your prometheus instance is scraping 200k metrics more than it can successfully send over remote write every 5 minutes. It's going to keep falling further behind. So, it's eventually guaranteed that when a checkpoint occurs it's going to include a WAL segment that remote write hasn't read yet. That's the missing data you're seeing in your remote storage. To confirm this you can look for checkpoints created in the logs around the next time you see the `no such file or directory` error.

My only suggestions right now are to, if you can, increase max shards. Sounds like you don't have memory to do this though. And to use relabel rules to drop some metrics. Or alternatively, remote write from each of your Prometheus instances instead of this one large federated instance.

**Comment by csmarchbanks** [comment]
In order to increase throughput I would suggest increasing capacity, and decreasing max shards to avoid running out of memory. Having a capacity of 10 means that many of your shards will end up being blocked because of a slow request on a different shard. Increasing the capacity allows much more throughput across all of the shards. See my explanation here: https://github.com/prometheus/prometheus/pull/5763#issuecomment-514872885

With a max samples per send of 2,000, I recommend a capacity of around 10,000, but it depends on the latency distribution of your remote storage.

**Comment by beorn7** [comment]
This seems to be more a configuration tuning problem than an actual bug. I'm therefore closing this issue. For more discussions around configuring and tweaking remote write, you could also use the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users).

**Comment by valyala** [comment]
> This seems to be more a configuration tuning problem than an actual bug

It would be great to have this information in Prometheus docs, so others don't trap into the same issue.

**Comment by beorn7** [comment]
Definitely. 

If this can be expressed concisely enough, it can go into https://prometheus.io/docs/prometheus/latest/configuration/configuration/#remote_write .

If it is more involved, an article in the "best practices" section might be more appropriate.

Would anybody of the remote-write experts be able to do this?

**Comment by beorn7** [comment]
I have re-opened this after renaming to track the documentation task.
@csmarchbanks @cstyan perhaps one of you could tackle this.

**Comment by csmarchbanks** [comment]
I am happy to write up a doc or best practices section on tuning remote-write. Will plan to do that in the next few days.

**Comment by valyala** [comment]
Just FYI, the original issue has been resolved by reducing `max_shards` from 1000 to 20. High number of shards resulted in high mutex contention in Prometheus remote_write code. This prevented from sending all the scraped samples to remote storage in timely fashion.

**Comment by csmarchbanks** [comment]
@valyala, where are you seeing mutex contention between shards? AFAIK there are no shared mutexes between shards during regular operation (only during startup/resharding/shutdown), and if so I would like to look into fixing that.

Is it possible you were running into the issue described above where too small of a capacity can lead to reduced throughput when one shard is processing a long request?

**Comment by hagen1778** [comment]
@csmarchbanks, I don't have collected profile - just an image I used in report:
![image2019-8-13_17-49-24](https://user-images.githubusercontent.com/2902918/63046007-76a8f900-bec9-11e9-8f8e-2192b299077f.png)

That contention gone once I reduced amount of shards to 20. 
Shard capacity is 20k

**Comment by csmarchbanks** [comment]
Thanks! I will take a look. Any chance you can provide me the raw profile?

**Comment by beorn7** [comment]
Doc is out.
