### ISSUE TITLE
Admin API documentation is out of date

### ISSUE THREAD

**Issue by gucki** [prometheus/prometheus#5808]
Running prometheus 2.11.0. The documentation of the admin api (https://prometheus.io/docs/prometheus/latest/querying/api/) seems to be outdated. The curl commands to delete time series are not working. 

This does *not* work (nothing gets deleted):

`curl -X POST -g 'http://prometheus:9090/api/v1/admin/tsdb/delete_series?match[]={__name__=~".+"}'
`

This works (everything gets deleted, as expected):
`curl -X POST -g 'http://prometheus:9090/api/v2/admin/tsdb/delete_series' -d '{"matchers": [{"name": "__name__", "type": 2, "value": ".+"}]}'`

**Comment by cstyan** [comment]
Hmm strange, I see the same behaviour. The docs do mention that deletes are not immediate but that they should happen at compaction time. 

Is the difference in behaviour intentional or is this a bug? @brian-brazil @juliusv @gouthamve

**Comment by brian-brazil** [comment]
Those are different matchers.

**Comment by juliusv** [comment]
The `+` characters probably needs to be escaped as `%2B` to not be turned into a space in a URL.

**Comment by gucki** [comment]
@brian-brazil Sorry, was a copy/ paste mistake. The regexp I used was the same, updated the description.

**Comment by juliusv** [comment]
@gucki Did you try with escaped `+` characters?

**Comment by juliusv** [comment]
Closing this for now, please reopen if it doesn't work after applying my escaping comment above.
