### ISSUE TITLE
Prometheus dashboard UI Bug: Shows the path to the alerting rules on top of each alerting rule

### ISSUE THREAD

**Issue by bluechips23** [prometheus/prometheus#5809]
## Bug Report
**What did you do?**
Upgraded Prometheus to v2.11.1 and I saw a strange "/etc/prometheus/prometheus.rules > [rule_name]" on top of each of the rules. Not sure if this is a bug or if this is a new feature. I have deleted the deployment and redeployed it again and I still see this. I don't remember seeing this in older version of Prometheus.

**What did you expect to see?**
Did not expect to see "/etc/prometheus/prometheus.rules > [rule name]" on top of each of the alerting rules.

**What did you see instead? Under which circumstances?**
[Alerting Rule Name]  in the status bar

**Environment**

* System information:

	Linux 3.10.0-957.21.3.el7.x86_64 x86_64

* Prometheus version:

    prometheus, version 2.11.1 (branch: HEAD, revision: 
    e5b22494857deca4b806f74f6e3a6ee30c251763)
    build user:       root@d94406f2bb6f
    build date:       20190710-13:51:17
    go version:       go1.12.7

<img width="659" alt="Screen Shot 2019-07-29 at 3 23 38 PM" src="https://user-images.githubusercontent.com/1458117/62076464-bad3a280-b215-11e9-812d-bd070be8ea10.png">

**Comment by simonpasquier** [comment]
Yes it is the new design since 2.10.0. See https://github.com/prometheus/prometheus/pull/5448.
