### ISSUE TITLE
Command "go mod vendor" does not include files tagged as "ignored" on 1.13

### ISSUE THREAD

**Issue by carlosedp** [prometheus/prometheus#5811]
I'd like to bring to attention that beginning with Go 1.13, the command `go mod vendor` will not include files tagged with `// +build ignore` so Prometheus CI script will fail with vendor dirs created with this version.

More info on https://github.com/golang/go/issues/33353 and https://github.com/golang/go/issues/31088.

**Comment by simonpasquier** [comment]
Thanks for the heads-up! I'm keeping the issue to remember that CONTRIBUTING.md would need an update when switching to Go 1.13.

**Comment by carlosedp** [comment]
Yes, I've been fighting this over last days (as you've been following too) where my Go 1.13 (the version that works on Risc-V) generates the vendor dir with some files that are ignored and was failing the CI.

**Comment by brian-brazil** [comment]
@simonpasquier Is this still relevant?
