### ISSUE TITLE
Consider not importing api/v2/model from Alertmanager?

### ISSUE THREAD

**Issue by tomwilkie** [prometheus/prometheus#5813]
By importing `api/v2/model` from alertmanager (in the notifier pkg), we couple the Prometheus codebase to a specific version of the Alertmanager codebase.  This stops projects which import Prometheus and Alertmanager (ie Cortex) from choose independent versions.

Note Cortex is still on a very old version of Alertmanager, one that includes mesh.

I'd like to consider decoupling (perhaps having a separate repo for the model, or just copying it in) so we can update Prometheus and Alertmanager independently in Cortex.

WDYT?

**Comment by tomwilkie** [comment]
Related: cortexproject/cortex#1510

**Comment by beorn7** [comment]
This seems related to the bigger picture discussed in https://groups.google.com/forum/#!topic/prometheus-developers/F1Vp0rLk3TQ .

**Comment by brian-brazil** [comment]
The whole point of the models is that they should be imported elsewhere as a public API, so this should probably be a Go module on the alertmanager side.

**Comment by simonpasquier** [comment]
I agree with @brian-brazil. Reported at https://github.com/prometheus/alertmanager/issues/1983.

**Comment by beorn7** [comment]
Hello from the bug scrub.

While the points raised here are valid, it apparently didn't cause a lot of pain over the last 5y. Thus, we are closing this, but this shouldn't discourage people from improving the situation if they find the time and energy.
