### ISSUE TITLE
How can I setup multi target_label by regex ?

### ISSUE THREAD

**Issue by pmghong1991** [prometheus/prometheus#5815]
In my case , prometheus cluster discovers coredns services from consul . We need to setup some customizable target label  to for grafana .
I setup some k:v labels into  consul tags and try to setdup prometheus relabel_configs with regex ，it looks like 

- job_name: 'consul-prometheus'
        consul_sd_configs:
          - server: '127.0.0.1:8500'
            services: ['coredns']
            datacenter: 'dc1'
        relabel_configs:
        - source_labels: [__meta_consul_service_address]
          action: replace
          target_label: host_ip
        - source_labels: [__meta_consul_tags]
          regex: ',room:(.+),alertId:(.+),'
          replacement: '${1}'
          target_label: room
          action: replace
        - source_labels: [__meta_consul_tags]
          regex: ',room:(.+),alertId:(.+),'
          replacement: '${2}'
          target_label: alertId
          action: replace 

the config above is works. But I have to setup every labels one by one .Once I add another lables, I have to add a pair of source_lable and target label.

Could I setup multi target labels from one source_lables , likes
- source_labels: [__meta_consul_tags]
          regex: ',room:(.+),alertId:(.+),'
          replacement: '${1},${2}'
          target_label: room,alertId
          action: replace

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
