### ISSUE TITLE
Distributed target pulling solution for multiple prometheus nodes

### ISSUE THREAD

**Issue by yangyshdan** [prometheus/prometheus#5817]
## Proposal
**Use case. Why is this important?**

Prometheus has a shared storage solution for TSDB which solves the storage HA problem. Based on the solution, is there a plan to build a corresponding DYNAMICS application HA solution, which allows target pulling work to be dynamically distributed among Prometheus application nodes? Eg, the target configuration can be stored in ETCD, and the application nodes can automatically get the exclusive tasks for metrics pulling. In such a way, there will be several benefits

1. Prometheus's target pulling workload can be distributed within a prometheus application cluster effectively and automatically. The Prometheus application can scale out in an easy way.
2. Each node's task is exclusive, so that no duplicated work will be taken, so the computing resources can be saved.
3. When node fails, other nodes can be take over the corresponding pulling work automatically by detecting the failure information from ETCD.

**Comment by brian-brazil** [comment]
> Prometheus has a shared storage solution for TSDB which solves the storage HA problem. 

No it doesn't, each Prometheus server is independent.

This is probably something better taken to the mailing list, there's no plans for any form of clustering in Prometheus itself.
