### ISSUE TITLE
Suggestion for new PromQL function: label_rename(instant-vector, old-label, new-label)

### ISSUE THREAD

**Issue by paddynewman** [prometheus/prometheus#5831]
I'd like to suggest a new function to be added to PromQL. The new function would be called "label_rename" and would be a simplified version of "label_replace".

Instead of this:
```
label_replace(
  sum by (region, node) (time_series_with_region_and_node_labels),
  "country", "$1",
  "region", "(.+)"
)
```

You could do this:
```
label_rename(
  sum by (region, node) (time_series_with_region_and_node_labels),
  "region", "country"
)
```

The "label_rename" function would rename the "region" label to "country". Unlike "label_replace", the "region" label would NOT be present after the function finished. The label value would remain unchanged.

I think "label_rename(instant-vector, old-label, new-label)" makes more sense to me but if you follow the convention for "label_replace" it should probably be "label_rename(instant-vector, new-label, old-label)". I'd struggle with that but obvisouly consistency is important.

Another thing that might be useful would be to rename multiple labels in one call, perhaps like this:
```
label_rename(
  sum by (region, node) (time_series_with_region_and_node_labels),
  "region", "country",
  "node", "host"
)
```

Please feel free to ignore this request if you don't like it. I can use relabelling instead if I really need to. And thanks for making Prometheus, it's a great piece of software.

**Comment by brian-brazil** [comment]
It's recommended to make your labels consistent at the source, rather than working around it late at the PromQL stage.

**Comment by paddynewman** [comment]
In this case, I'm dealing with inconsistencies that are the result of different naming standards in the cAdviser and kube-state-metrics.

I don't think I can control those label names at source so I think my best bet is to deal with these via relabelling. I will do that.

**Comment by brian-brazil** [comment]
I believe work is already in progress to fix that issue, it just takes a while due to deprecation cycles.

**Comment by paddynewman** [comment]
Thanks for the information. Feel free to close this if you like.
