### ISSUE TITLE
Proposal: Add query - client-IP pairs to prometheus logs

### ISSUE THREAD

**Issue by You-NeverKnow** [prometheus/prometheus#5846]
## Proposal
Add client IP / query pairs to logs similar to mysql logs.

```
# User@Host: abc[abc] @  [<IP address>]  Id: 930295
...
select * from contracts where modified <= 20380116000000  order by modified;
```

**Why is this important?**
We have multiple clients that make queries to Prometheus, so it would be nice to know what client made what queries for debugging purposes in case something goes wrong.

**Comment by roidelapluie** [comment]
Closed by #6520
