### ISSUE TITLE
Data / Metrics cleanup and maintenance?

### ISSUE THREAD

**Issue by ashmere** [prometheus/prometheus#585]
Is it possible to groom or cleanup old data from prometheus?

at the minute it seems to be an infinitely growing data store with no way to clean old data

**Comment by juliusv** [comment]
@ashmere Data is kept for 15 days by default and deleted afterwards. This can be adjusted via the `-storage.local.retention` flag. Does that answer your question?

**Comment by ashmere** [comment]
partially that is useful to know but can we cleanup data more selectively like all metric for this source rather than all?

**Comment by juliusv** [comment]
Not yet unfortunately, but it's tracked in https://github.com/prometheus/prometheus/issues/382 and shouldn't be too hard to add (just not a priority for us at the moment). I guess this issue can be closed then?

**Comment by ashmere** [comment]
yes thanks for the help

**Comment by juliusv** [comment]
Sure! Cool, closing...
