### ISSUE TITLE
Proposal: Add Azure Data Explorer as new remote storage in the documentation

### ISSUE THREAD

**Issue by cosh** [prometheus/prometheus#5858]
The default way of storing data is on the local storage of the Prometheus server. Because of various reasons like high availability and scalability the project provides an interface for the integration of remote storages. Azure Data Explorer is a perfect fit for Azure User that want to continue using Prometheus on Azure with a scalable remote storage.
This article explains the integration: https://www.linkedin.com/pulse/prometheusio-azure-data-explorer-henning-rauch/

I would like to propose to add Azure Data Explorer as a remote storage to this section in the documentation: https://prometheus.io/docs/operating/integrations/#remote-endpoints-and-storage

**Comment by brian-brazil** [comment]
You can send a PR to add it, it's over in the docs repo.

**Comment by cosh** [comment]
cool, will do

**Comment by brian-brazil** [comment]
This is listed now.
