### ISSUE TITLE
Incorrect go.mod replace path

### ISSUE THREAD

**Issue by krasi-georgiev** [prometheus/prometheus#5859]
https://github.com/prometheus/prometheus/blob/master/go.mod#L70

this looks like a mistake.

**Comment by beorn7** [comment]
Was introduced in #4972 , and skimming the discussion there, it looks legit. @simonpasquier @tariq1890 WDYT?

**Comment by tariq1890** [comment]
I don't remember the reason for overriding `klog`.

 But at this point, I'd definitely lean towards either using upstream `klog` or not use `klog` at all and prefer another prometheus-approved logging solution.

@beorn7 The issue you have linked points to something else.

**Comment by beorn7** [comment]
I have fixed the link to the PR. Sorry for the confusion.

**Comment by tariq1890** [comment]
Thoughts @simonpasquier ?

**Comment by krasi-georgiev** [comment]
He will be back on the 19th

**Comment by tariq1890** [comment]
@krasi-georgiev Thanks. Could you elaborate on the concerns you have with this, in the meantime?

As far as I understand, prometheus uses `"github.com/go-kit/kit/log"` as the logger. Simon's fork of klog is merely a wrapper for it.

**Comment by krasi-georgiev** [comment]
I don't have any concern, just thought it might be a mistake.

**Comment by tariq1890** [comment]
@krasi-georgiev We don't have to close this just yet. We can wait on Simon's opinion. It is possible that we may want to change things up a bit as opposed to remaining with the status-quo.

**Comment by krasi-georgiev** [comment]
He will see it in his notification and can reopen if anything should be done now.

**Comment by simonpasquier** [comment]
:wave: I'm back. As @tariq1890 said, the `replace` directive overrides the default klog logger (which is used by the k8s client library) with our [go-kit logger](https://godoc.org/github.com/go-kit/kit/log). The details are explained [here](https://github.com/simonpasquier/klog-gokit#usage).
