### ISSUE TITLE
tsdb: Avoid chunks with >120 samples in MergeOverlappingChunks

### ISSUE THREAD

**Issue by codesome** [prometheus/prometheus#5862]
Currently, during vertical compaction, we directly merge the overlapping chunks and the samples can exceed the limit of 120 in a chunk. Chunk needs to be broken down into smaller chunks if it crosses 120 samples.

The piece of code where the fix goes: https://github.com/prometheus/tsdb/blob/d5b3f0704379a9eaca33b711aa0097f001817fc2/chunks/chunks.go#L208-L240

**Comment by nidhidhamnani** [comment]
I would like to work on this issue

**Comment by codesome** [comment]
@nidhidhamnani go ahead!

**Comment by Sudhar287** [comment]
Can you please elaborate on why this modification is necessary?

**Comment by bwplotka** [comment]
Sure. @Sudhar287 the reason is that our compression algorithm at the moment is designed to have the best compression ration statistically with 120 samples. Anything more than that is introducing high latency (and memory used) for querying because of decoding (time, cpu and mem) without really improving stored size. 

That's why stick to max 120.

**Comment by Sudhar287** [comment]
Okay understood. Thanks @bwplotka

**Comment by brancz** [comment]
I think max 120 alone might not really reflect the entirety of what we want. At the same time we want to avoid chunks that have a low amount of samples as they extrapolated in the long run cause larger disk space and thus space that needs to be mapped into memory. I think we need heuristics for both lower and upper bound merge decisions.

**Comment by codesome** [comment]
@brancz yes, there is another issue tracking the merging of small chunks https://github.com/prometheus/prometheus/issues/6332

**Comment by bboreham** [comment]
Is there a paper somewhere that details how 120 was obtained as the right figure?

**Comment by brancz** [comment]
That would be the gorilla paper: https://www.vldb.org/pvldb/vol8/p1816-teller.pdf

That said while we know the compression statistically gets optimal there, I’m not sure 120 samples exactly the right heuristic here. As I prefer to have a buffer than slip into likely not optimal space.

**Comment by hdost** [comment]
So it looks like this is some sort of cursed issue. There have been multiple PRs all of which have been closed. Is the consensus still that the samples should be split into separate chunks?

**Comment by codesome** [comment]
@hdost Consensus, yes. They were closed because of different reasons :). More than splitting, it's more about avoiding bigger chunks when merging (we can leave alone the already bigger chunks, not worth breaking them down now for the additional complexity that adds).

Now with some refactoring that @bwplotka did, it should be easier to do it now. I think the relevant code is in `storage/merge.go` now (look for `NewCompactingChunkSeriesMerger`).

**Comment by hdost** [comment]
So essentially at this point we just want to make sure we don't compact chunks such that they end up over 120 samples :heavy_check_mark:

**Comment by yeya24** [comment]
Closed by #8582
