### ISSUE TITLE
tsdb: Tests with injected file system errors.

### ISSUE THREAD

**Issue by krasi-georgiev** [prometheus/prometheus#5866]
One case it to catch bugs like:
https://github.com/prometheus/tsdb/pull/575
https://github.com/prometheus/tsdb/issues/565 - A test for this would look like. Inject an error at some point for these funcs and check that no tmp files is left behind.

https://github.com/prometheus/tsdb/pull/582 - a test would look like - create WAL records until we inject FS full fault, check that the `appender.Add` fails, add more space to the FS, check that `appender.Add` succeeds.

An example for a similiar test:
https://github.com/prometheus/tsdb/pull/576

This article is a good start.
https://medium.com/@siddontang/use-fuse-to-inject-failure-to-i-o-deb5f2e7800a

**Comment by qiffang** [comment]
@krasi-georgiev 
Is (the PR)[https://github.com/prometheus/tsdb/pull/583] still needed?

**Comment by krasi-georgiev** [comment]
I would say so, but wondering what the other maintainers would say about it as well.

**Comment by qiffang** [comment]
> I would say so, but wondering what the other maintainers would say about it as well.

So how do we know other maintainers's idea, they never responded

**Comment by krasi-georgiev** [comment]
yes you are right, this is not a high priority and everyone is busy with other more pressing issues and features, but I will try to get someone's attention to look at this one.

**Comment by krasi-georgiev** [comment]
so I asked for an opinion in the slack channel and only @brian-brazil 	responded that if this is really optional and run only with a specific test target than it will be ok to have so feel free to add and will do one more review.

**Comment by krasi-georgiev** [comment]
quite outdated now, closing
