### ISSUE TITLE
tsdb: fsync only called on segment closing

### ISSUE THREAD

**Issue by brancz** [prometheus/prometheus#5869]
I was reading the ingestion path of tsdb and was talking to @gouthamve as I think `fsync` is only called on [closing a segment](https://github.com/prometheus/tsdb/blob/0b72f9af4c7a7953f89c993e69bbf81b12af49c3/wal/wal.go#L605) (which happens on shutdown) or when [rotating to a new segment](https://github.com/prometheus/tsdb/blob/0b72f9af4c7a7953f89c993e69bbf81b12af49c3/wal/wal.go#L390) (which happens when a segment is "[full](https://github.com/prometheus/tsdb/blob/3929359302170bd79567f9808bafcb7fdf116acf/wal/wal.go#L482-L486)"). A segment is [128MB](https://github.com/prometheus/tsdb/blob/3929359302170bd79567f9808bafcb7fdf116acf/wal/wal.go#L38) by default, so on unclean shutdown, I believe we may loose up to the most recent 128MB of data.

It looks like https://github.com/prometheus/tsdb/pull/332 added the new WAL, which is not being flushed at an interval, being part of the strategy to make:

> It is safe for concurrent reads across different processes.

@gouthamve and I were thinking that instead of fsync'ing at an interval, we fsync in [`flushPage`](https://github.com/prometheus/tsdb/blob/3929359302170bd79567f9808bafcb7fdf116acf/wal/wal.go#L403) or directly at the end of [`log`](https://github.com/prometheus/tsdb/blob/3929359302170bd79567f9808bafcb7fdf116acf/wal/wal.go#L481).

First of all, let's validate this and make sure we didn't miss something :slightly_smiling_face: . Otherwise let's make sure we fix this. (I'm actually on vacation, just happened to be reading the code for work unrelated reasons, so it's unlikely I will work on it this week, I'll be back next week)

@gouthamve @brian-brazil @codesome @cstyan @fabxc

**Comment by brian-brazil** [comment]
As part of the bugscrub, it is proposed that we close this as at best it'd be a tunable that'd make no practical difference in terms of dataloss on power failure - you could have lost the same data if the power had been lost a few seconds before.

**Comment by brancz** [comment]
Agreed.
