### ISSUE TITLE
Auto build the tsdb cli tool with every release.

### ISSUE THREAD

**Issue by krasi-georgiev** [prometheus/prometheus#5870]
the tsdb tool would be useful for troubleshooting tsdb problems and now with the new analyze command from https://github.com/prometheus/tsdb/pull/478 it would be helpful to auto build and executable with travis for every new tsdb release.
Than we can ask users to just download and run different commands for troubleshooting an issue.
don't think we need a docker image for this so a simple executable for linux64 would be fine to start with.

@simonpasquier , @SuperQ 	maybe you can help with this one?

**Comment by simonpasquier** [comment]
We should either a) add the `tsdb` binary to `.promu.yml` and container image or b) extend `promtool` with tsdb commands.

**Comment by krasi-georgiev** [comment]
I vote for b)

**Comment by brian-brazil** [comment]
b) makes more sense I think in user terms, and it'd still work for other uses.

**Comment by simonpasquier** [comment]
I agree for b) too.

**Comment by SuperQ** [comment]
For now, can we go with option A so that we provide the tool as a stop-gap until the promtool integration is done?

**Comment by krasi-georgiev** [comment]
yep that is fine too and just open another issue so that someone can pick it up.
