### ISSUE TITLE
Reuse tsdb in Jaeger project

### ISSUE THREAD

**Issue by pavolloffay** [prometheus/prometheus#5872]
Hi,

I am investigating whether this storage could be reused in [Jaeger project](https://github.com/jaegertracing/jaeger). We are looking for a local storage and this could be a nice opportunity to reuse the same component between CNCF projects.

Jaeger stores data called spans, a simple but complete example is here:
```json
{
   "traceID":"23a770f4011fb988",
   "spanID":"6861ad40555fcda7",
   "parentSpanID":"9aec4016b0d5c64b",
   "flags":1,
   "operationName":"Execute",
   "references":[

   ],
   "startTime":1516758686833000,
   "duration":6971,
   "tags":[
      {
         "key":"component",
         "type":"string",
         "value":"java-jdbc"
      }
   ],
   "logs":[
           {
              "timestamp" : 1516759006922000,
              "fields" : [
                {
                  "key" : "event",
                  "type" : "string",
                  "value" : "formatString1"
                }
              ]
            }
   ],
   "processID":"",
   "process":{
      "serviceName":"spring-boot",
      "tags":[
         {
            "key":"hostname",
            "type":"string",
            "value":"DongVinkdeMacBook-Pro.local"
         }
      ]
   }
}
```

We need to query by:
* Time range
* Labels - key value pair
* Service name - similar to label
* Operation name - similar to label
* Duration - min, max

Example Index:
`http.url=http://myservice.com/login` -> [traceid1, traceid2, traceid3];

If a data point (span) with a label is found it is retrieved - but also all data points with the same `traceid` (field stored in a span) have to be retrieved. List of spans with the same `traceid` is called a trace. Each span has a unique id called `spanid`. Spans of the same trace might be stored at different times - in different blocks.

`traceid` could be considered as time series ID but there will be more unique traces than time series because one trace represents logs collected across nodes in a distributed system for one request.
Spans could be stored in chunks in a data field.

**Comment by roidelapluie** [comment]
Maybe you could also look at cortex/loki storage.

**Comment by pavolloffay** [comment]
Yeah, I had some discussion with Loki team. There is also the problem with high cardinality but there might be solutions to that.

**Comment by brian-brazil** [comment]
We discussed this during the bugscrub and this seems more like a support request, and @gouthamve also indicates that you've moved on to looking to other approaches so we're closing this.
