### ISSUE TITLE
tsdb: Isolation for writes

### ISSUE THREAD

**Issue by gouthamve** [prometheus/prometheus#5873]
Currently, when we call `app.Commit()`, we go ahead and start adding samples to the database. But now if there is a concurrent reader that is reading data, it might read some samples from the commit but not all.

This causes issues in Prometheus and has been known to make histograms falter: https://github.com/prometheus/prometheus/issues/1169

This PR is an attempt to fix it: https://github.com/prometheus/tsdb/pull/105

**Comment by roidelapluie** [comment]
@beorn7 @brian-brazil this can be closed, right?
