### ISSUE TITLE
tsdb: Reduce index file size caused by symbol references

### ISSUE THREAD

**Issue by fabxc** [prometheus/prometheus#5874]
As blocks get compacted, index files currently converge towards a size 5-8% compared to a block's chunk files.
This mostly true for relatively low series churn levels. As churn increaeses, there will be fewer chunks per series and per-series overheads for postings lists and series entries become more pronounced.

Postings compression is a known topic, but improving compression of series entries has not been looked into so far. A few strategies I've thought about:

Series entries hold label pairs in the form of offsets into the symbol table. The offsets are stored as varints. This was deemed important when we still accessed the symbol table through mmap on demand. Today however, we load all symbols into memory when loading a block for other reasons.

1. We could not store offsets but just incremental IDs for strings, which makes the numbers we reference a string with significantly shorter and they will therefore compress better. This requires storing. On startup we read the symbol table and just store a `<index>: <string>` mapping in memory rather than an `<offset>: <string>` mapping.
2. Currently the symbol table is sorted lexicographically. I believe there's no strict requirement for that. Instead it would be more efficient to order the table by frequency, i.e. how often a string appears in series. This way more frequent strings have a smaller index and references to them take up less space.
3. Lastly, we could think about having an additional table for label pairs, i.e. name/value combinations that make up a label. This would allow us in series to just store one reference per label instead of two. The extra table for label pairs should have roughly the same amount of entries like the symbol table, as each label value mostly is tied to a particular pair. It could generally be stored as a pair of references into the string table of course and therefore be pretty cheap.

Those are all possible to implement independently but probably roughly in this order. The first two should be very straightforward. 3 is a bit more involved.

**Comment by brian-brazil** [comment]
We looked at this as part of the bug scrub, and this seems to be obsolete given changes to the tsdb since so we're closing it. A new tsdb index format would be the place to consider ideas like these.
