### ISSUE TITLE
tsdb: Query and other benchmarks

### ISSUE THREAD

**Issue by gouthamve** [prometheus/prometheus#5875]
We don't have proper benchmarks yet and that means we cannot see the potential impact of the changes we are introducing.

**Comment by rajibmitra** [comment]
@krasi-georgiev  I would like to work on this issue as part of community bridge program if no one is actively working on it.

**Comment by krasi-georgiev** [comment]
We did this one as part of the last GSOC program. There are still some things to finish, but another contributor has taken the initiative and don't think there is much left to do here to make it an antyre project. I think it landed in the communiyt bridge program by mistake.

**Comment by rajibmitra** [comment]
okay , thanks for the update @krasi-georgiev

**Comment by brian-brazil** [comment]
We have plenty of benchmarks, where do you think there are gaps?

**Comment by roidelapluie** [comment]
@brian-brazil I think that #6512 highlights that we probably don't stress enough the tsdb reads.

**Comment by rajdas98** [comment]
Hi @krasi-georgiev . I would like to take this as my GSOC project. Can you help me with it?

**Comment by brian-brazil** [comment]
We've looked at this as part of the bug scrub, and we currently have benchmarks in the tsdb for the querier so this is being closed. If there's specific cases not covered, an issue/PR should be created for them.
