### ISSUE TITLE
tsdb: GC does not respect pending readers

### ISSUE THREAD

**Issue by fabxc** [prometheus/prometheus#5877]
After a successful compaction of a head's history, we advance its minimum timestamp `mint`. This allows to new readers to not actually access any data before that time (this should probably be validated again).  
Long running readers may have been instantiated before the minimum timestamp was advanced. They may have retrieved references to series and their chunks that later get garbage collected. The reader still holding the reference, may still try to access the data afterwards, effectively holding dangling pointers.

This manifested before in "series not found" errors during garbage collections, causing queries to abort, and was now also observed with chunk references, which caused actual panics.

A straightforward approach is tracking all pending readers and the minimum timestamp they were created with. Garbage collection can then be delayed until all readers have a high enough timestamp.

The general approach should probably be re-thought a bit overall.

**Comment by brian-brazil** [comment]
@beorn7 Do you know if this was this fixed as part of isolation? I'm not sure it was.

**Comment by beorn7** [comment]
Neither am I. Perhaps it was. Or perhaps isolation provides some plumbing to fix this issue. More investigation needed…

**Comment by brian-brazil** [comment]
That's what I suspect is the case, just plumbing that'll help.

**Comment by beorn7** [comment]
Yes, after some digging, I'm fairly sure it isn't addressed yet.

**Comment by roidelapluie** [comment]
This is even more complex as we can have appenders who append in the past.

What we could do is to register in isolation the current segment, and not truncate below that new "low segment" watermark.
