### ISSUE TITLE
tsdb: Use context.Context for transaction lifecycle

### ISSUE THREAD

**Issue by fabxc** [prometheus/prometheus#5878]
Currently `Appender` and `Querier` both have `Commit/Rollback` and `Close`respectively.
Especially Rollback/Close are easy to forget to do properly, causing deadlocks.

One solution would be to replace the explicit aborts with contexts cancelation. 

The interfaces would change as follows:

```go
type Queryable interface {
    Querier(context.Context, mint, maxt int64)
}

type Appednable interface {
    Appender(context.Context, mint, maxt int64)
}
```

On context cancelation `Rollback` and `Close` behaviour would be called. A `Commit` would error if the context is already canceled.

This would make sense to pass to `Delete` as well @Gouthamve (after the main work is in).
It's the only operation that is actually executing a long-running work in a blocking manner and particularly because it may be stuck waiting for the compaction lock. That may take longer than a related HTTP request remains open.

Problem: 
Querying returns iterators over storage memory, which must only be accessed while the transaction is still ongoing.
We cannot really guarantee that client code receives the context's cancelation signal before the storage. For example, the passed context may have a parent context with a timeout. So the storage might return locks before we stop accessing memory. 
Strictly speaking, all data in memory and persisted blocks should be append-only. But that would need some careful checking again.

The problem here really is the high-frequency of our operations. We cannot check `<-ctx.Done` after every sample we added or iterated over as `select` is rather expensive. 

So this is more of an issue for feature consideration and shouldn't be added lightly.

**Comment by brian-brazil** [comment]
We look at this as part of the bug scrub, and currently queries are fast enough in the tsdb that a lack of contexts is not an issue so closing.
