### ISSUE TITLE
tsdb: Improve instrumentation

### ISSUE THREAD

**Issue by fabxc** [prometheus/prometheus#5879]
Instrumentation so far is pretty sparse:

* Make compaction duration metric a summary (no generally applicable histogram buckets possible)
* Fsync duration of the WAL
* WAL corruptions detected
 
There's probably a lot more. Though a lot of performance metrics around querying aren't really possible due to lazy evaluation.

**Comment by simonpasquier** [comment]
As @krasi mentioned, this can be closed IMO.
