### ISSUE TITLE
tsdb: Document that labels.Labels should always be sorted

### ISSUE THREAD

**Issue by gouthamve** [prometheus/prometheus#5880]
Currently we {1="2",2="1"} and {2="1",1="2"} are being treated as different series. This is true for `headBlock` and I could not find if we are sorting and merging series while persisting.

If this is true, it spreads the same series across different locations. Now while this may look like we are increasing our write throughput, we are never appending to the same series concurrently. This is a definite hit to the query performance as we need to hit different places for the same series.

I am pretty sure this is intentional but not able to understand the rationale behind this.

**Comment by cstyan** [comment]
@gouthamve is this still relevant? did you want to document it somewhere in a markdown file or this enough: https://github.com/prometheus/prometheus/blob/master/tsdb/labels/labels.go#L35-L37
