### ISSUE TITLE
tsdb: Implement way to return soft-errors on partial data

### ISSUE THREAD

**Issue by fabxc** [prometheus/prometheus#5881]
Blocks are independent and some blocks may be missing indices or other data for one reason or another for another (e.g. prometheus/tsdb#2 or data that's skipped due to detected corruption).
We can often still serve a large part of the requested data and should be able to do so without the using application having to fail hard on the first error.
We need a way to indicate to the application that some data may be missing.

**Comment by krajorama** [comment]
Hello from the bug scrub: since we have warnings now, this could be enhanced by saying that we return the partial data AND a warning along side it. However we're closing now for lack of activity.
