### ISSUE TITLE
promtool: show warnings for label value queries

### ISSUE THREAD

**Issue by juliusv** [prometheus/prometheus#5885]
An update of the Go client library dependency done in https://github.com/prometheus/prometheus/pull/5883#pullrequestreview-274297321 now provides warnings for label value queries. Figure out if / how to display those in promtool.

**Comment by sayanchowdhury** [comment]
Can pick this issue? I'll do some digging to see how this can be implement. I might take sometime as I'm not familiar with promtool

**Comment by juliusv** [comment]
Sure, go ahead! :)

**Comment by juliusv** [comment]
It's probably a very local change, right next to here: https://github.com/prometheus/prometheus/blob/master/cmd/promtool/main.go#L505

Maybe even just an additional `fmt.Println(...)` or something to output the warnings. Maybe we'd want to output them to stderr instead of stdout though... that would keep the stdout stream clean and parseable.
