### ISSUE TITLE
Query for histogramm returns le in wrong order

### ISSUE THREAD

**Issue by jendrikjoe** [prometheus/prometheus#5898]
## Bug Report
**What did you do?**
I logged a histogram for request times using the python client and:
```python

BUCKETS = (.1, .2, .3, .35, .4, .45, .5, .6, .75, 1, 2.5, 10000, float("inf"))
predict_time = Histogram('request_processing_seconds', 'Time spent processing request', buckets=BUCKETS)

@api.route('/process')
class Process(Resource):

    @predict_time.time()
    def post(self):
        doing stuff here that takes some hundred ms
```

**What did you expect to see?**

Looking at the metrics port of the pod I get the proper histogram:
```
# HELP predict_request_processing_seconds Time spent processing predict request
# TYPE predict_request_processing_seconds histogram
request_processing_seconds_bucket{le="0.1"} 0.0
request_processing_seconds_bucket{le="0.2"} 4.0
request_processing_seconds_bucket{le="0.3"} 4.0
request_processing_seconds_bucket{le="0.35"} 4.0
request_processing_seconds_bucket{le="0.4"} 4.0
request_processing_seconds_bucket{le="0.45"} 4.0
request_processing_seconds_bucket{le="0.5"} 4.0
request_processing_seconds_bucket{le="0.6"} 4.0
request_processing_seconds_bucket{le="0.75"} 4.0
request_processing_seconds_bucket{le="1.0"} 4.0
request_processing_seconds_bucket{le="2.5"} 5.0
request_processing_seconds_bucket{le="10000.0"} 5.0
request_processing_seconds_bucket{le="+Inf"} 5.0
request_processing_seconds_count 5.0
request_processing_seconds_sum 2.44609494402539
```

**What did you see instead? Under which circumstances?**

However, querying it in prometheus with `request_processing_seconds_bucket` shuffles the order of the buckets and returns:

Element  | Value
-- | --
request_processing_seconds_bucket{endpoint="metrics",instance="----",job="rest-prometheus",le="+Inf",namespace="default",pod="rest-59b89fbb9f-27tfv",service="rest-prometheus"} | 5
request_processing_seconds_bucket{endpoint="metrics",instance="----",job="rest-prometheus",le="0.1",namespace="default",pod="rest-59b89fbb9f-27tfv",service="rest-prometheus"} | 0
request_processing_seconds_bucket{endpoint="metrics",instance="----",job="rest-prometheus",le="0.2",namespace="default",pod="rest-59b89fbb9f-27tfv",service="rest-prometheus"} | 4
request_processing_seconds_bucket{endpoint="metrics",instance="----",job="rest-prometheus",le="0.3",namespace="default",pod="rest-59b89fbb9f-27tfv",service="rest-prometheus"} | 4
request_processing_seconds_bucket{endpoint="metrics",instance="----",job="rest-prometheus",le="0.35",namespace="default",pod="rest-59b89fbb9f-27tfv",service="rest-prometheus"} | 4
request_processing_seconds_bucket{endpoint="metrics",instance="----",job="rest-prometheus",le="0.4",namespace="default",pod="rest-59b89fbb9f-27tfv",service="rest-prometheus"} | 4
request_processing_seconds_bucket{endpoint="metrics",instance="----",job="rest-prometheus",le="0.45",namespace="default",pod="rest-59b89fbb9f-27tfv",service="rest-prometheus"} | 4
request_processing_seconds_bucket{endpoint="metrics",instance="----",job="rest-prometheus",le="0.5",namespace="default",pod="rest-59b89fbb9f-27tfv",service="rest-prometheus"} | 4
request_processing_seconds_bucket{endpoint="metrics",instance="----",job="rest-prometheus",le="0.6",namespace="default",pod="rest-59b89fbb9f-27tfv",service="rest-prometheus"} | 4
request_processing_seconds_bucket{endpoint="metrics",instance="----",job="rest-prometheus",le="0.75",namespace="default",pod="rest-59b89fbb9f-27tfv",service="rest-prometheus"} | 4
request_processing_seconds_bucket{endpoint="metrics",instance="----",job="rest-prometheus",le="1.0",namespace="default",pod="rest-59b89fbb9f-27tfv",service="rest-prometheus"} | 4
request_processing_seconds_bucket{endpoint="metrics",instance="----",job="rest-prometheus",le="10000.0",namespace="default",pod="rest-59b89fbb9f-27tfv",service="rest-prometheus"} | 5
request_processing_seconds_bucket{endpoint="metrics",instance="----",job="rest-prometheus",le="2.5",namespace="default",pod="rest-59b89fbb9f-27tfv",service="rest-prometheus"} | 5

This leads to issues plotting the histogram as it is not cumulative anymore.

**Environment**

* System information:

	Linux 4.14.128-112.105.amzn2.x86_64 x86_64

* Prometheus version:

	prometheus, version 2.9.1 (branch: HEAD, revision:  ad71f2785fc321092948e33706b04f3150eee44f)
  build user:       root@09f919068df4
  build date:       20190416-17:50:04
  go version:       go1.12.4

* Prometheus configuration file:
This should be populated by the prometheus operator (not certain, am happy to update it)

**Comment by brian-brazil** [comment]
In general we don't make any promises on the order of query results, and these are just random time series to Prometheus. If you need it sorted in a specific order then you'll need to do it on your end.

**Comment by beorn7** [comment]
Since the buckets are cumulative, you could even use `sort(...)` to get them in the order you want. However, whatever you use to plot the histogram should inspect the `le` label anyway. Otherwise, you will get into trouble if the monitored target has a different idea about the bucket layout compared to the code that plots the histogram.

**Comment by jendrikjoe** [comment]
Thank you very much for the speedy replies. From what it seems it should have been a stackoverflow question, so first of all sorry for raising a bug on this one.
I actually realized (after rebuilding my Grafana dashboard this morning) that I shouldn't add anything to the legend apart from only {{le}}. 
Adding anything else seems to break the Grafana sorting and it defaults to the sorting it gets from prometheus. I mistakingly interpreted this as an issue in prometheus.
