### ISSUE TITLE
grafana版本大于5.1，挂载权限问题

### ISSUE THREAD

**Issue by wu-andrew** [prometheus/prometheus#5906]
报错：
GF_PATHS_DATA='/var/lib/grafana' is not writable.
You may have issues with file permissions, more information here: http://docs.grafana.org/installation/docker/#migration-from-a-previous-version-of-the-docker-container-to-5-1-or-later
mkdir: cannot create directory '/var/lib/grafana/plugins': No such file or directory

**Comment by wu-andrew** [comment]
我参考的https://segmentfault.com/a/1190000018335241解决此问题
      initContainers:
      - name: "init-chown-data"
        image: "busybox:latest"
        imagePullPolicy: "IfNotPresent"
        command: ["chown", "-R", "472:472", "/var/lib/grafana/"]
        volumeMounts:
        - name: grafana-persistent-storage
          mountPath: /var/lib/grafana/
          subPath: ""

这是新加的。
我的配置文件
![image](https://user-images.githubusercontent.com/21164437/63148605-4762cb00-c034-11e9-9c32-12605b29795b.png)

**Comment by codesome** [comment]
This question seems to be related to Grafana usage and not Prometheus. Please post this question in Grafana community https://community.grafana.com/.
