### ISSUE TITLE
building with PIE prduces broken binary

### ISSUE THREAD

**Issue by jan--f** [prometheus/prometheus#5907]
I added `-buildmode=pie` to `flags` and `ldflags` in .promu.yml, since distros sometimes prefer position independent binaries.

The binary of prometheus produced by such a build immediately crashes with `Program terminated with signal SIGTRAP, Trace/breakpoint trap.`

I'd expect to get a runnable binary.

**Comment by simonpasquier** [comment]
It looks more like a Go question than being Prometheus specific.

**Comment by brian-brazil** [comment]
We looked at this as part of the bug scrub and this appears to be a support request without followup. If you're still having issues I'd suggest asking on the [prometheus-developers mailing list](https://groups.google.com/forum/#!forum/prometheus-developers).
