### ISSUE TITLE
Feature request: make `scrape` code independent and shareable in `pkg/scrape` (or its own repo)

### ISSUE THREAD

**Issue by crquan** [prometheus/prometheus#5923]
## Proposal
**Use case. Why is this important?**
I am in a team effort making a proxying layer of scraping some targets which requires a dynamically reading list of targets (from a DB to read address, TLS client certs, extra labels and other configs for each one), and do something extra like results interpolations and attaching labels; so far designed as a independent deployment entity, realized need to re-use a lot of scraping code from prometheus codebase, but a simple `import "github.com/prometheus/prometheus/scrape"` failed for many reasons, including too many unnecessary dependencies and others; I have reached a solution by only copying necessary code from `scrape` and make it working, however this has a maintenance issue going forward when upstream improves; So wonder from upstream if anyone like to make the `scrape` code independently shareable?

**Comment by brian-brazil** [comment]
That sounds a fair bit outside what the core of Prometheus scraping does in design terms, and would require quite a bit of refactoring to allow this use case sanely. This is fundamentally an internal library so using it for inspiration rather than as a dependency probably makes more sense.

**Comment by brian-brazil** [comment]
We looked at this as part of the bug scrub and this sounds out of scope for Prometheus, so we've closing it.
