### ISSUE TITLE
Add docs for remote read streaming

### ISSUE THREAD

**Issue by bwplotka** [prometheus/prometheus#5925]
https://github.com/prometheus/prometheus/pull/5703 extended remote read protocol. We probably want to introduce some documentation piece on website and/or blog post about this.

AC:
* Streaming remote read is documented.

**Comment by brian-brazil** [comment]
https://github.com/prometheus/prometheus/tree/master/documentation/examples/remote_storage is where we usually put that

**Comment by Transwert** [comment]
@brian-brazil @bwplotka  i would like to work upon this one, can you guys state resources, an direction in which i should proceed.

**Comment by bwplotka** [comment]
Thanks @Transwert!

We published a blog post which in details presents remote read streaming: https://prometheus.io/blog/2019/10/10/remote-read-meets-streaming/

With this, I believe this issue is actually done. As @brian-brazil mentioned there is indeed an optional example code we could add here: https://github.com/prometheus/prometheus/tree/master/documentation/examples/remote_storage

In terms of website docs, I did not really find any place to add much. Protocol was never documented, as it might be not really needed - `proto` file is very descriptive already.

I would say blog post (which is done) and optional example code would satisfy this ticket. You are more than welcome to create such example code (e.g remote read client) inside https://github.com/prometheus/prometheus/tree/master/documentation/examples/remote_storage

**Comment by Transwert** [comment]
ok @bwplotka i will surely start working on it, thanks for briefing :)

**Comment by bboreham** [comment]
Came here to say it was quite hard for me to figure out how exactly the request changed from the first version to the streaming version.
Now I read through all the code, I see it is explained at https://prometheus.io/blog/2019/10/10/remote-read-meets-streaming/#usage, but I was looking for some statement about the URL endpoint or http accept-encoding. Maybe adding "the URL is unchanged" to that section would have let me find it quicker.

**Comment by beorn7** [comment]
Hello from the bug scrub.

An example in https://github.com/prometheus/prometheus/tree/master/documentation/examples/remote_storage and an update of the blog post (along the lines sketched out by @bboreham above) would still be welcome. We'll still close this as nothing happened in 3y, and we won't keep issues open that aren't super urgent and nobody is going to work on. Still, improvements of the documentation will be welcome (not only in this area ;).
