### ISSUE TITLE
needs lock protection

### ISSUE THREAD

**Issue by johncming** [prometheus/prometheus#5929]
https://github.com/prometheus/prometheus/blob/302148fd69a852aa8a25c37032349852038beeb1/discovery/manager.go#L168-L176

Function `cancelDiscoverers ` itself has no lock.

https://github.com/prometheus/prometheus/blob/302148fd69a852aa8a25c37032349852038beeb1/discovery/manager.go#L283-L285

**Comment by simonpasquier** [comment]
The analysis is correct. I would probably modify  `cancelDiscoverers` to only call the cancel() functions and move the [rest](https://github.com/prometheus/prometheus/blob/302148fd69a852aa8a25c37032349852038beeb1/discovery/manager.go#L283-L285) to `ApplyConfig` as when the manager's context is cancelled, we don't need to reset the fields anyway.

**Comment by irajdeep** [comment]
@simonpasquier I can work on this if no else is currently working on it
