### ISSUE TITLE
discovery/file: maybe it's bug

### ISSUE THREAD

**Issue by johncming** [prometheus/prometheus#5931]
## Bug Report
**What did you do?**

Submitt a PR, CI prompt with an error

https://circleci.com/gh/prometheus/prometheus/14830?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**What did you expect to see?**

Same, both, or neither

**What did you see instead? Under which circumstances?**

It was verified locally and there were no errors

**Environment**

* System information:

Darwin 18.6.0 x86_64

* Prometheus version:

	master branch

**Comment by codesome** [comment]
Duplicate of https://github.com/prometheus/prometheus/issues/5901
