### ISSUE TITLE
Two different "errors" packages coexist

### ISSUE THREAD

**Issue by johncming** [prometheus/prometheus#5933]
## Proposal

**Use case. Why is this important?**

First of all, this is not a bug, just the usage of `errors`. But sometimes it causes a little confusion.

There are two `errors` packages:

1. `errors` Standard library
2. `github.com/pkg/errors`  Common third-party packages and used a lot in the project.

Examples of mixed use:

1. `github.com/pkg/errors`

https://github.com/prometheus/prometheus/blob/48b2c9c8eae2d4a286d8e9384c2918aefd41d8de/cmd/prometheus/main.go#L660

2.  `errors`

https://github.com/prometheus/prometheus/blob/2184b79763c722ef2584f0b07e43b2380bd87456/rules/manager.go#L183

**Proposal**

In terms of functionality, use `github.com/pkg/errors`. Because `github.com/pkg/errors`  is compatible with the standard error interface

Again, not a bug, just a suggestion. I can provide pr if needed

**Comment by codesome** [comment]
I don't see this being a problem. `github.com/pkg/errors` gives some additional functionality which is useful at places. For example, the file that you pointed used `errors.Wrapf`. And places where we don't need additional those additional functionality, it would be natural to just import `errors`. Just my 2 cents.

**Comment by johncming** [comment]
> I don't see this being a problem. `github.com/pkg/errors` gives some additional functionality which is useful at places. For example, the file that you pointed used `errors.Wrapf`. And places where we don't need additional those additional functionality, it would be natural to just import `errors`. Just my 2 cents.

It's really hard to distinct, for example:

https://github.com/prometheus/prometheus/blob/8fdfa8abeaaaf021d3ca614e4b50af317b1f4145/discovery/config/config.go#L17

**Comment by simonpasquier** [comment]
I don't think we need a general policy: things will drift away eventually as the code base evolves. But there may be places where `github.com/pkg/errors` would be more appropriate (eg `errors.Wrap(err, "...")` instead of `fmt.Errorf("...: %v", err)`). Just my 2c.

**Comment by bwplotka** [comment]
Yea, I would be happy with the strict rule of **having `github.com/pkg/errors` instead of `fmt.Errorf("...: %v", err)`**

However, if the file uses just `errors.New` I don't mind if it's `error` or `pkg/error` - we depend on both anyway (:

**Comment by johncming** [comment]
Thank you for your reply. Yes, use different packages as needed.
