### ISSUE TITLE
bug: count_values

### ISSUE THREAD

**Issue by OPSTime** [prometheus/prometheus#5934]
**Build Information**

> Version	2.11.1
> Revision	e5b22494857deca4b806f74f6e3a6ee30c251763
> Branch	HEAD
> BuildUser	root@d94406f2bb6f
> BuildDate	20190710-13:51:17
> GoVersion	go1.12.7

**go_info:**

Element | Value
-- | --
go_info{group="canary",instance="localhost:8082",job="example_random",version="go1.12.7"} | 1
go_info{group="production",instance="localhost:8080",job="example_random",version="go1.12.7"} | 1
go_info{group="production",instance="localhost:8081",job="example_random",version="go1.12.7"} | 1
go_info{instance="172.17.48.220:9105",job="nodes",version="go1.12.5"} | 1
go_info{instance="172.17.48.221:9100",job="nodes",version="go1.12.5"} | 1
go_info{instance="localhost:9090",job="prometheus",version="go1.12.7"} | 1

**count_values('version', go_info)**

Element | Value
-- | --
{version="1"} | 6

**Comment by brian-brazil** [comment]
This is working as expected. There are 6 1 values.

**Comment by OPSTime** [comment]
> To count the number of binaries running each build version we could write:
> count_values("version", build_version)

**What I understand is wrong?**

> {version="go1.12.7"} 4
> {version="go1.12.5"} 2

**Comment by simonpasquier** [comment]
You want `count by(version) (go_info)`.

**Comment by OPSTime** [comment]
Thank you!
