### ISSUE TITLE
enable HTTP2 on prometheus

### ISSUE THREAD

**Issue by valdemarpavesi** [prometheus/prometheus#5938]
Is it possible to implement HTTP2 on Prometheus ?

Grafana got it implemented.

we do need:

Prometheus as server 9090 with HTTP2 and as client scrap function to exporters.

HTTP2 will bring super power to Prometheus.

example to enable on Server:

```
package main

import (
    "log"
    "net/http"
    "os"

    "golang.org/x/net/http2"
)

func main() {
    cwd, err := os.Getwd()
    if err != nil {
        log.Fatal(err)
    }

    srv := &http.Server{
        Addr:    ":8000", // Normally ":443"
        Handler: http.FileServer(http.Dir(cwd)),
    }
    http2.ConfigureServer(srv, &http2.Server{})
    log.Fatal(srv.ListenAndServeTLS("server.crt", "server.key"))
}

```

**Comment by valdemarpavesi** [comment]
browsers --> http2/https h2 -->  grafana -->  h2c  --> prometheus --> h2c -->  exporter.

**Comment by roidelapluie** [comment]
My opinion:

This project will in general use whatever is supported by the golang http library. The number of potential targets that will support unencrypted h2c is too low to justify making that a prometheus feature.

Should you need that feature, you can deploy a small sidecar next to your prometheus server and use it as http_proxy.

**Comment by brian-brazil** [comment]
Yeah, this isn't something we should be going out of our way to make happen. Given that we're mainly an API, HTTP/2 won't help much anyway.

**Comment by dswarbrick** [comment]
Although they're probably not in short supply, multiplexed requests over HTTP/2 could dramatically reduce socket descriptor usage to blackbox_exporter and similar.

**Comment by budarin** [comment]
> h2 is http2 type that require https ( cert/key), all browsers require http2/https.
> 
> but, in this case , grafana-prometheus or prometheus-exporter is not necessary to use h2.
> 
> we can use h2c. clear text.
> 
> example:
> 
> "golang.org/x/net/http2"
> "golang.org/x/net/http2/h2c"
> 
> client:
> 
> ```
> 
> 
> 
> 		Http2Client = http.Client{
> 			// Skip TLS dial
> 			Transport: &http2.Transport{
> 				AllowHTTP: true,
> 				DialTLS: func(network, addr string, cfg *tls.Config) (net.Conn, error) {
> 					return net.Dial(network, addr)
> 				},
> 			},
> 		}
> ```
> 
> server:
> 
> ```
> 
> func http2Server() {
> 
>     
> 	handler := http.HandlerFunc(http2_index_main)
> 
> 	http2.VerboseLogs = LogVerbose
> 
> 	h2s := &http2.Server{}
> 
> 	h1s := &http.Server{
> 		Addr:    http2ServerlocalAddr,
> 		Handler: h2c.NewHandler(handler, h2s),
> 	   }
> 
> 	h1s.ListenAndServe()
> 
> }
> ```
> 
> https://http2.github.io
> https://http2.akamai.com
> https://http2.akamai.com/demo
> https://en.wikipedia.org/wiki/HTTP/2
> https://github.com/http2/http2-spec/wiki/Tools
> https://http2.github.io/http2-spec/
> https://curl.haxx.se/docs/http2.html

http2 does not require https ( cert/key) - it works well without certs

**Comment by roidelapluie** [comment]
http2 **in golang** requires https

**Comment by budarin** [comment]
> My opinion:
> 
> This project will in general use whatever is supported by the golang http library. The number of potential targets that will support unencrypted h2c is too low to justify making that a prometheus feature.
> 
> Should you need that feature, you can deploy a small sidecar next to your prometheus server and use it as http_proxy.

a binary header Protocol that supports compression and multiplexed requests over HTTP/2 can significantly reduce the number of socket descriptors - isn't this the incentive to enable http2 without encryption????

**Comment by roidelapluie** [comment]
Not really, as Prometheus most of the time will use just one connection per target, and is already using compression.

**Comment by valdemarpavesi** [comment]
thanks @roidelapluie 
![image](https://user-images.githubusercontent.com/10376101/115059282-f6ac1100-9eab-11eb-992c-5b3f319f30de.png)

**Comment by valdemarpavesi** [comment]
now, golang have default http2 into  "net/http"

not required:

"golang.org/x/net/http2"
"golang.org/x/net/http2/h2c"

**Comment by valdemarpavesi** [comment]
Hello @roidelapluie 

testing http2

not http2 enable:

`
level=info ts=2021-04-19T18:03:48.071Z caller=tls_config.go:191 component=web msg="TLS is disabled." http2=false
`


testing with curl, trying http2 and establish with to http/1.1

`
$ curl -kvso /dev/null --http2 http://localhost:9091/federate?match%5B%5D=%7B__name__%3D~%22.%2A%22%7D
*   Trying ::1:9091...
* TCP_NODELAY set
* Connected to localhost (::1) port 9091 (#0)
> GET /federate?match%5B%5D=%7B__name__%3D~%22.%2A%22%7D HTTP/1.1
> Host: localhost:9091
> User-Agent: curl/7.68.0
> Accept: */*
> Connection: Upgrade, HTTP2-Settings
> Upgrade: h2c
> HTTP2-Settings: AAMAAABkAARAAAAAAAIAAAAA
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Content-Type: text/plain; version=0.0.4; charset=utf-8
< Date: Mon, 19 Apr 2021 18:25:20 GMT
< Transfer-Encoding: chunked
< 
{ [73588 bytes data]
* Connection #0 to host localhost left intact
$ 
`



http2 enable:

`
tls_server_config:
  # Certificate and key files for server to use to authenticate to client.
  cert_file: /certs/localhost/tls.crt
  key_file: /certs/localhost/tls.key

http_server_config:
  # Enable HTTP/2 support. Note that HTTP/2 is only supported with TLS.
  # This can not be changed on the fly.
  http2: true
`

results:
`
level=info ts=2021-04-19T19:21:44.326Z caller=main.go:795 msg="Starting TSDB ..."
level=info ts=2021-04-19T19:21:44.328Z caller=tls_config.go:224 component=web msg="TLS is enabled." http2=true
`

testing with curl

`
curl -vso /dev/null --http2-prior-knowledge --http2 --cacert /root/certs/prometheus.crt  https://localhost:9091/federate?match%5B%5D=%7B__name__%3D~%22.%2A%22%7D
`

`
$ curl -vso /dev/null --http2-prior-knowledge --http2 --cacert /root/certs/prometheus.crt  https://localhost:9091/federate?match%5B%5D=%7B__name__%3D~%22.%2A%22%7D
*   Trying ::1:9091...
* TCP_NODELAY set
* Connected to localhost (::1) port 9091 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /root/certs/prometheus.crt
  CApath: /etc/ssl/certs
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.3 (IN), TLS handshake, Server hello (2):
{ [122 bytes data]
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
{ [6 bytes data]
* TLSv1.3 (IN), TLS handshake, Certificate (11):
{ [954 bytes data]
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
{ [264 bytes data]
* TLSv1.3 (IN), TLS handshake, Finished (20):
{ [36 bytes data]
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
} [1 bytes data]
* TLSv1.3 (OUT), TLS handshake, Finished (20):
} [36 bytes data]
* SSL connection using TLSv1.3 / TLS_AES_128_GCM_SHA256
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: C=BE; ST=Antwerp; L=Brasschaat; O=Inuits; CN=localhost
*  start date: Apr 19 19:31:06 2021 GMT
*  expire date: Apr 19 19:31:06 2022 GMT
*  subjectAltName: host "localhost" matched cert's "localhost"
*  issuer: C=BE; ST=Antwerp; L=Brasschaat; O=Inuits; CN=localhost
*  SSL certificate verify ok.
} [5 bytes data]
> GET /federate?match%5B%5D=%7B__name__%3D~%22.%2A%22%7D HTTP/1.1
> Host: localhost:9091
> User-Agent: curl/7.68.0
> Accept: */*
> 
{ [5 bytes data]
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
{ [130 bytes data]
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Content-Type: text/plain; version=0.0.4; charset=utf-8
< Date: Mon, 19 Apr 2021 19:50:36 GMT
< Transfer-Encoding: chunked
< 
{ [1046 bytes data]
* Connection #0 to host localhost left intact
$ 
`

fallback to  HTTP/1.1 200 OK

problem is:  ALPN, server did not agree to a protocol

The default on go  "net/http"  for https  is http2.
To disable http2 have to use:   Server.TLSNextProto to a non-nil, empty map


`
package main

import (
    "log"
    "net/http"
    "crypto/tls"
)

func main() {

    m := http.NewServeMux()

    srv := &http.Server{
        Handler:      m,
        Addr:         "127.0.0.1:8080",
        TLSNextProto: make(map[string]func(*http.Server, *tls.Conn, http.Handler)),
    }

    log.Fatal(srv.ListenAndServe())

}
`


on Prometheus what is the function for 


`

http_server_config:
  # Enable HTTP/2 support. Note that HTTP/2 is only supported with TLS.
  # This can not be changed on the fly.
  http2: true
`

https://www.katacoda.com/va/scenarios/prometheus

regards!
Valdemar
