### ISSUE TITLE
A single NaN breaks a graph plot line

### ISSUE THREAD

**Issue by leonerd** [prometheus/prometheus#594]
I'm plotting a graph of cache hit ratio. Normally the number is 1, or rather close to it; but for caches that are rarely used there may be entire time slices with no attempts at all, so the "hit ratio" becomes NaN. A single NaN will entirely break the graph plot, causing the line not to be drawn for later times even though the data series itself has defined numbers there. Furthermore, hovering the mouse in the right area of the graph still shows the on-hover popup to tell me the exact number, series labels, etc...; just the line is invisble.

Almost certainly just a float variable that retains a "NaN" value somewhere in the client-side JS that needs resetting.

**Comment by juliusv** [comment]
@leonerd Could you take a look if https://github.com/prometheus/prometheus/pull/595 fixes your problem?

**Comment by juliusv** [comment]
@leonerd any luck with https://github.com/prometheus/prometheus/pull/600 now?

**Comment by juliusv** [comment]
Heard out of band that this is fixed.
