### ISSUE TITLE
"$value", Is it the current value?

### ISSUE THREAD

**Issue by OPSTime** [prometheus/prometheus#5955]
**alert rules:**

>   - alert: UnusualNetworkThroughputIn
>     expr: instance:node_network_receive_mbits_excluding_lo:rate1m > 100
>     for: 10s
>     labels:
>       severity: warning
>     annotations:
>       summary: "Incoming network bandwidth > 100 Mb/s ({{ $labels.instance }})"
>       description: "Current value: {{ printf \"%.2f\" $value }}"
> 
>   - alert: UnusualNetworkThroughputOut
>     expr: instance:node_network_transmit_mbits_excluding_lo:rate1m > 100
>     for: 10s
>     labels:
>       severity: warning
>     annotations:
>       summary: "Outgoing network bandwidth > 100 Mb/s ({{ $labels.instance }})"
>       description: "Current value: {{ printf \"%.2f\" $value }}"

**alerts:**
**FIRING:**

>  [FIRING:2] 
> [0]: Outgoing network bandwidth > 100 Mb/s (172.17.48.220:9105)
> 
> Current value: 177.83
> [1]: Incoming network bandwidth > 100 Mb/s (172.17.48.221:9100)
> 
> Current value: 184.07

**RESOLVED:**
**value > 100 Mb/s**
> [RESOLVED] 
> [0]: Outgoing network bandwidth > 100 Mb/s (172.17.48.220:9105)
> 
> Current value: **183.01**
> [1]: Incoming network bandwidth > 100 Mb/s (172.17.48.221:9100)
> 
> Current value: **189.47**

**Comment by simonpasquier** [comment]
`$value` is the value of the last firing alert. I'm closing it for now. If you have further questions, please use our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search.

**Comment by lddlww** [comment]
How to get the current value？@simonpasquier

**Comment by simonpasquier** [comment]
you can't get any value when the alert resolves because by definition there's no data anymore.

**Comment by lddlww** [comment]
@simonpasquier thanks
