### ISSUE TITLE
Add some methods to wal page

### ISSUE THREAD

**Issue by johncming** [prometheus/prometheus#5956]
## Proposal

**Why**

Better encapsulation.

**Action**

`page.buf` abstracts three methods

1. `func (*page) alloc() []byte`

Include the following codes

https://github.com/prometheus/prometheus/blob/7d43feb03ffca86276bf6dd47b618b6986c6583a/tsdb/wal/wal.go#L489

2. `func (*page) remaining() []byte`

Include the following codes

https://github.com/prometheus/prometheus/blob/7d43feb03ffca86276bf6dd47b618b6986c6583a/tsdb/wal/wal.go#L611

3. `func (*page) reset()`

Include the following codes

https://github.com/prometheus/prometheus/blob/7d43feb03ffca86276bf6dd47b618b6986c6583a/tsdb/wal/wal.go#L497-L501

**Comment by beorn7** [comment]
Based on the outcome of the discussion in #5967, I'm closing this. Please speak up if you disagree.
