### ISSUE TITLE
Metric data may be inaccurate

### ISSUE THREAD

**Issue by johncming** [prometheus/prometheus#5959]
definition:

https://github.com/prometheus/prometheus/blob/b5c833ca2194db5581b8979048b3450cc869b88a/notifier/notifier.go#L174-L179

update value:

https://github.com/prometheus/prometheus/blob/b5c833ca2194db5581b8979048b3450cc869b88a/notifier/notifier.go#L325-L326

**case**

There were 10 alerts and only one failed to send.  `dropped` should increase by 1, but increase by 10 at last.

**Comment by simonpasquier** [comment]
Prometheus will send `alerts` in one HTTP request so it is all or nothing.

**Comment by johncming** [comment]
Whether this mechanism causes confusion, especially when most succeed and few fail

**Comment by simonpasquier** [comment]
Sorry I'm not following...

**Comment by johncming** [comment]
> Sorry I'm not following...

Not clearly described. 

There were 10 alarms, 10 alertmanagers, 9 alertmanagers successfully received the alarm, and only 1 alertmanager failed. Based on this metric, there are currently 10 drops, and it looks like all the alerts failed to be sent, but in fact most of them succeeded (9 alertmanagers received alerts).

**Comment by simonpasquier** [comment]
> There were 10 alarms, 10 alertmanagers, 9 alertmanagers successfully received the alarms, and only 1 alertmanager failed. Based on this metric, there are currently 10 drops, and it looks like all the alerts failed to be sent, but in fact most of them succeeded (9 alertmanagers received alerts).

If alerts have been sent to at least one AlertManager instance then `sendAll()` returns `true` and `prometheus_notifications_dropped_total` isn't incremented.

If you want to look at the error rate per AlertManager instance, you need to look at `prometheus_notifications_errors_total` and `prometheus_notifications_latency_seconds_count`:

```
rate(prometheus_notifications_errors_total[5m])
  /
rate(prometheus_notifications_latency_seconds_count[5m])
```

**Comment by brian-brazil** [comment]
We looked at this as part of the bug scrub and this seems to be a handled support request, so we're closing it.
