### ISSUE TITLE
Allow providing robots.txt or security.txt details so that open prometheus installs are less easy to find and can be reported

### ISSUE THREAD

**Issue by gerricchaplin** [prometheus/prometheus#5962]
## Proposal
**Proposal and Issue description:**
I have managed to find numerous open Prometheus and Alert Manager installations on the internet while performing mundane searches for specific alert keywords which are part of generally available and suggested alert rules.

Some of these belonged to some big companies and they are simply unaware that their ingress whitelists or security groups are misconfigured. I have reached out whenever possible to inform them.

As you may be aware Prometheus can expose a good deal of information about internal architecture, network topology, teams, contacts, software versions and in some cases third part API details - which could be used for nefarious reasons.

It would be helpful to make these sort of installations with open API access less visible to public search and be able to know who to contact in such situations. I managed to guess some domains, companies and contact details from Runbook links in the alerts - but those are not always provided or appropriately named. I know security through obscurity is not a thing but every little helps and having some appropriate contact details goes a long way to help get them fixed.

Separately I think the default configuration should not expose `/status` at all. You should need to enable this in configuration.

*Use cases:*
- robots.txt with a block all default can at least attempt to shield open installations from being crawled by default and their content becoming part of general search results.
- security.txt can go some way to providing details of who to contact should someone find an open server.
- I would like to provide this via configuration whenever possible instead of having to inject files as it is not always the case that Prometheus is run in k8s.

_robots.txt_
```
User-agent: *
Disallow: /
```

_security.txt_
```
Contact: mailto:security@example.com
Contact: https://example.com/security-contact.html
```

**Comment by brian-brazil** [comment]
We already specify noindex and nofollow on the various status pages, so a robots.txt shouldn't be needed.

Disabling the status page would make debugging quite hard, so I don't think that's viable. If you want a security.txt that sounds like a case for a reverse proxy, if they aren't aware that their server is open they likely haven't setup such a special file either.

**Comment by gerricchaplin** [comment]
Hi Brian,

Thanks for the quick reply.

I do see it was added as part of https://github.com/prometheus/prometheus/commit/d0f11a3cc61919a752fa0111e9d15661b4dcf8c0 which is great. Sorry I missed that. I have found that most of these are older installations which is part of the problem I guess.

re:/status I was aiming to disable by default - users are then able to allow status if they so choose in order to troubleshoot issues. Even within organisations providing least privilege and the least amount of information is preferable. Perhaps it can fall under a flag like `enable-admin-api`?

re:security.txt is helpful to raise awareness - at least if it's mentioned somewhere as an option end users may be more security conscious. I am not sure I can guess if someone would ignore the file. If someone makes a mistake and exposes their installation through no fault of their own. For example some other team makes changes or misconfigures something there is at least a chance someone can be contacted. I don't really have the context of the creation of the installations I have seen.

I know the general Prom approach is to push the ownership of security towards the user so perhaps  there is not much appetite or time for this type of improvement. Reading https://prometheus.io/assets/downloads/2018-06-11--cure53_security_audit.pdf is seems there are some recommendations in there which suggest that prometheus should at least try to do a little more to help users in these areas.

Thanks again!

**Comment by brian-brazil** [comment]
> Perhaps it can fall under a flag like enable-admin-api?

That's for mutating changes, not read-only information.

> re:/status I was aiming to disable by default - users are then able to allow status if they so choose in order to troubleshoot issues.

That doesn't work in user support terms, or general user friendliness I'm afraid.

> If someone makes a mistake and exposes their installation through no fault of their own. For example some other team makes changes or misconfigures something there is at least a chance someone can be contacted. 

There's a chain of assumptions there, overall I don't think it'd help the type of person you think it'd help as any such organisation either wouldn't use the feature or would have existing controls that'd catch this.

**Comment by gerricchaplin** [comment]
Ok, fair enough.
Thanks again.
