### ISSUE TITLE
0/0 evaluates to +Inf but should be NaN

### ISSUE THREAD

**Issue by aecolley** [prometheus/prometheus#597]
This is inconsistent with float arithmetic in Go. It's not a theoretical-only concern either: I had an alert spuriously fire because the (summary-based) average was too high. You see, sum and count were both zero, so the mean ratio was +Inf which was larger than the threshold; NaN would not have alerted in that case.

Workaround: AND your alert rules with tests like foo_count != 0.

**Comment by juliusv** [comment]
Ah, thanks for pointing this out! Will fix this. Sorry in case this paged you at night :)

**Comment by juliusv** [comment]
Fix out in https://github.com/prometheus/prometheus/pull/598
