### ISSUE TITLE
Can't Scrape with Node Exporter. "append failed" err="\"INVALID\"

### ISSUE THREAD

**Issue by kaizen1** [prometheus/prometheus#5981]
Installed Prometheus behind HAProxy, which would be a common deployment in production.

Two simple scrapers enabled see config below. Both Targets are down in web ui Graph screen. 

Getting the following error in journalctl:

caller=scrape.go:930 component="scrape manager" scrape_pool=prom-exporter target=http://localhost:9100/prometheus/metr
ics2 msg="append failed" err="\"INVALID\" is not a valid start token"

Version | 2.12.0
-- | --
43acd0e |  
HEAD |  
root@7a9dbdbe0cc7 |  
20190818-13:53:16 |  
go1.12.8

<img width="510" alt="config" src="https://user-images.githubusercontent.com/16579459/64210182-91d7aa80-ce70-11e9-971d-7ccb62e298d4.png">

**Comment by kaizen1** [comment]
`
CONFIG FILE

global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  # - "first.rules"
  # - "second.rules"

# this is a self-scrape of prometheus server

scrape_configs:
  - job_name: 'prom-server'
    scrape_interval: 5s
    metrics_path: /prometheus/metrics1
    static_configs:
      - targets: ['localhost:9090']

# this is a scrape of the node exporter running on prometheus server

  - job_name: 'prom-exporter'
    scrape_interval: 5s
    metrics_path: /prometheus/metrics2
    static_configs:
      - targets: ['localhost:9100']

 `

**Comment by csmarchbanks** [comment]
It makes more sense to ask questions like this on the [prometheus-users](https://groups.google.com/forum/#!forum/prometheus-users) mailing list rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
