### ISSUE TITLE
Require  plug-in  or generate API

### ISSUE THREAD

**Issue by johncming** [prometheus/prometheus#5982]
## Proposal

Plug-in functionality or generate API is required， especially service discovery. 

Use cases:

1. different public cloud providers. There are many different cloud providers that want to provide sd services.
2. the existing CMDB. Existing CMDB of the enterprise is compatible with Prometheus sd services under lower cost

**Comment by brian-brazil** [comment]
file_sd is the the API for this already, and there's a partial list of implementations on the website: https://prometheus.io/docs/operating/integrations/#file-service-discovery

**Comment by johncming** [comment]
> https://prometheus.io/docs/operating/integrations/#file-service-discovery

thanks.
