### ISSUE TITLE
Stop Scraping SSH Keys into Prometheus   

### ISSUE THREAD

**Issue by kaizen1** [prometheus/prometheus#5987]
1. I'm using gce_sd_configs on Google cloud for discovery of targets. Target discovery is working well. 
2. But when I go to the Status >> Targets in the web ui and the hover over the instance label, I see all metadata "Before Relabeling". Most of that meta data is ok to display and is not be a problem except for the fact that the Target's SSH keys are getting scraped, so on hovering over instance label in the web ui, the SSH key for the machine is displayed. Not good is an understatement.
3. Relabeling with action: droplabel does not help. I can still see the SSH key on hover.
4. There is no reason that I can think of to scrape SSH keys into Prometheus. It's extremely undesirable to have __meta_gce_metadata_ssh_keys in the Prometheus system. It's also not mentioned anywhere in the documentation.

I hope this is not a feature request and just a misunderstanding because it looks like a security hole.

**Comment by brian-brazil** [comment]
We expose all metadata that we can for service discovery, which there's a list of https://cloud.google.com/compute/docs/storing-retrieving-metadata

I don't see a security issue here, as these are public keys.

**Comment by kaizen1** [comment]
That's not true. Most people generate public keys without a -C flag. That means the USER and HOST of the machine holding the PRIVATE key are published in the Prometheus web ui. 

The Prometheus server has all of the permissions it needs via compute@developer.gserviceaccount.com -- account on GCP instance. So there is no need to publish SSH keys in a web ui.

**Comment by brian-brazil** [comment]
That still doesn't make them private keys. If you believe this is a problem I'd suggest asking Google not to mix this in with information like the CPU platform and zone.

**Comment by kaizen1** [comment]
Google is like City Hall. Not gonna happen.

**Comment by brian-brazil** [comment]
We looked at this as part of the bug scrub, and this is an opaque metadata to Prometheus which does not contain secrets so is not considered a security issue per our security policy so we're closing this.
