### ISSUE TITLE
potential problem with pkg/gate package

### ISSUE THREAD

**Issue by johncming** [prometheus/prometheus#5988]
There's a potential problem with pkg/gate package.

https://github.com/prometheus/prometheus/blob/ead0933dd9065602e234ae907eee17a6dd208601/promql/engine.go#L387-L390

The current gate implementation can easily panic if length is 0.

https://github.com/prometheus/prometheus/blob/4c524007087ef50f02a396e1f4529340ee81783f/pkg/gate/gate.go#L44

If capacity 0, Start return because timeout.

**Two proposals**:

1)	Close channel when Start timeout returns
2)	Create a Gate interface, channelGate is just an implementation. Add other implementations later

**Comment by roidelapluie** [comment]
Do you have a way to reproduce this?

**Comment by roidelapluie** [comment]
Friendly ping @johncming

**Comment by johncming** [comment]
> Friendly ping @johncming

I try it but not find a way to reproduce. I find this issue when reading code.

**Comment by beorn7** [comment]
Hello from the bug scrub.

We assume that the case raised in this issue can never happen. Closing, but please feel free to follow up with more evidence.
