### ISSUE TITLE
use lable_replace to remove the lable, but vector cannot contain metrics with the same labelset

### ISSUE THREAD

**Issue by wu0407** [prometheus/prometheus#5989]
## Proposal
**Use case. Why is this important?**
Promql not have lable_remove function to remove the lable, so use `lable_replace` to complete it.    flow this [link](https://github.com/kubernetes/kube-state-metrics/tree/master/docs#join-metrics)  to join metric from `container_cpu_usage_seconds_total` and `kube_pod_labels`.
but `kube_pod_labels` has "instance" lable that is mutil value, so  lead  to "many to many" error.
```
"found duplicate series for the match group {namespace="kube-system", pod="prometheus-operator-grafana-5bdf985c67-bvdlj"} 
on the right hand-side of the operation: [{name="kube_pod_labels", endpoint="http", instance="10.1.105.233:8080", job="kube-state-metrics", label_app="grafana", label_pod_template_hash="5bdf985c67", label_release="prometheus-operator", namespace="kube-system", pod="prometheus-operator-grafana-5bdf985c67-bvdlj", service="prometheus-operator-kube-state-metrics"}, 
{name="kube_pod_labels", endpoint="http", instance="10.1.105.203:8080", job="kube-state-metrics", label_app="grafana", label_pod_template_hash="5bdf985c67", label_release="prometheus-operator", namespace="kube-system", pod="prometheus-operator-grafana-5bdf985c67-bvdlj", service="prometheus-operator-kube-state-metrics"}];
many-to-many matching not allowed: matching labels must be unique on one side"
```

*“Nice to have” is not a good use case. :)*
promql has some lable_remove functhion
## Bug Report
**What did you do?**
lable is delete by query in graph, is ok.
```
label_replace(kube_pod_labels{namespace="kube-system", label_app="gas"}, "instance", "",  "instance", ".*")
``` 
but in the grafana 
```
Object
xhrStatus:"complete"
request:Object
method:"GET"
url:"api/datasources/proxy/1/api/v1/query_range?query=label_replace(kube_pod_labels%7Blabel_app%3D%22grafana%22%2C%20namespace%3D%22kube-system%22%7D%2C%20%22instance%22%2C%20%22%22%2C%20%22instance%22%2C%20%22.*%22)&start=1567662435&end=1567673235&step=15"
response:Object
status:"error"
errorType:"execution"
error:"vector cannot contain metrics with the same labelset"
message:"vector cannot contain metrics with the same labelset"
```
**What did you expect to see?**
lable remove success
**What did you see instead? Under which circumstances?**
use  metric_relabel_configs to remove the lable
**Environment**

* System information:
```
Linux 4.15.0-33-generic x86_64
```
* Prometheus version:
```
prometheus, version 2.12.0 (branch: HEAD, revision: 43acd0e2e93f9f70c49b2267efa0124f1e759e86)
  build user:       root@7a9dbdbe0cc7
  build date:       20190818-13:53:16
  go version:       go1.12.8
```

* Prometheus configuration file:
```
insert configuration here
```

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by wu0407** [comment]
it is has two kube-state-metrics instance  in   same time, so replace label  general uniquely metrics
