### ISSUE TITLE
prometheus pull data failed after update node_exporter from v0.15.2 to v0.18.1 

### ISSUE THREAD

**Issue by XSHui** [prometheus/prometheus#5992]
## Proposal
**Use case. Why is this important?**

*“Nice to have” is not a good use case. :)*

## Bug Report
**What did you do?**
Linux 3.10.0-229.el7.x86_64 x86_64

prometheus- v2.2.1

old: node_exporter-v0.15.2

new: node_exporter-v0.18.1

1. prometheus- v2.2.1, node_exporter-v0.15.2, we got a lot of errors in node_exporter'log
```
`{"log":"time=\"2019-09-05T09:23:55Z\" level=error msg=\"Error on statfs() system call for \\\"net:[4026532821]\\\": no such file or directory\" source=\"filesystem_linux.go:57\"\n","stream":"stderr","time":"2019-09-05T09:23:55.325227724Z"}`
```

We had config node_exporter as below 
```
`--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|rootfs/var/lib/docker|rootfs/run/docker/netns)($$|/)"`
```

2. I tried to upgrade node_exporter from v0.15.2 to v0.18.1 to fix the problem, but when node_exporter:v0.18.1 online, node data can't be pulled by prometheus.

node_exporter start.sh
```
#!/bin/bash
set -e
ulimit -n 1000000

exec docker run -d --name node_exporter \
    --restart=always \
    --cpu-shares=256 \
    --memory=512MB \
    --memory-reservation=256MB \
    --memory-swappiness=0  \
    --memory-swap=512MB  \
    -v "/:/rootfs:ro" \
    -v "/data:/data" \
    -v /etc/localtime:/etc/localtime:ro \
    --net="host" \
    --pid="host" \
    node-exporter:v0.18.1
```

**What did you expect to see?**

node_exporter:v0.18.0 works well. 

**What did you see instead? Under which circumstances?**
1. node_exporter's state is up in prometheus's targets list

2. curl http://127.0.0.1:9100, works well

3. grafana no data from the node_exporter

4. prometheus expression no result 

eg:
```
(ceil(node_filesystem_size{mountpoint=~"/rootfs/data.*"} )) > 0
```

**Environment**

* System information:

	insert output of `uname -srm` here

* Prometheus version:

	insert output of `prometheus --version` here

* Alertmanager version:

	insert output of `alertmanager --version` here (if relevant to the issue)

* Prometheus configuration file:
```
insert configuration here
```

* Alertmanager configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```

**Comment by XSHui** [comment]
@SuperQ

**Comment by SuperQ** [comment]
For usage questions/help, please use our [community](https://prometheus.io/community/). On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
