### ISSUE TITLE
The reload event may leak

### ISSUE THREAD

**Issue by johncming** [prometheus/prometheus#5993]
The reload event may leak

https://github.com/prometheus/prometheus/blob/b7bb278e955d624f26d99b92dc5e29e477b92b08/scrape/manager.go#L81-L84

`default` may cause a leak of event if channel block.

Read channel operation didn't perform.  Write channel operation will skip because of default statement.

https://github.com/prometheus/prometheus/blob/b7bb278e955d624f26d99b92dc5e29e477b92b08/scrape/manager.go#L98-L103

**Comment by codesome** [comment]
That looks fine. A single reload is enough for multiple updates.

**Comment by simonpasquier** [comment]
Exactly, it works as intended.

**Comment by johncming** [comment]
https://github.com/prometheus/prometheus/blob/b7bb278e955d624f26d99b92dc5e29e477b92b08/scrape/manager.go#L83

If select `default` path is used, event will leak.

**Comment by roidelapluie** [comment]
hello,

We looked at this issue during our bug scrub and I was tasked to look at the code.

> Read channel operation didn't perform. Write channel operation will skip because of default statement.

We queue one reload at the time that we execute at ticker.C. That is why we need the non-blocking write.

Like @simonpasquier and @codesome I do not see any issue here.

In general, it is preferable to discuss code over PR than issues.
