### ISSUE TITLE
Eliminate YML Dependency 

### ISSUE THREAD

**Issue by kaizen1** [prometheus/prometheus#5997]
I manage clusters of MariaDB, HAProxy, Redis, and Node.js, none of which require me to pay attention to white space, indentation, and seemingly random use of leading hyphens, and/or no hyphens.

These YML validation errors from such triviality are a huge waste of time. 

Feature request: use a config format that is not whitespace or indentation sensitive, and remove the hyphens. See any of the above best of breed systems for reference.

**Comment by simonpasquier** [comment]
Hmm, I can understand your griefs against YAML but I'm not seeing the configuration format moving away from YAML anytime soon.

**Comment by csmarchbanks** [comment]
If you do not want to use a whitespace sensitive configuration format, you can specify all of your configuration in JSON since YAML is a superset of JSON.

**Comment by simonpasquier** [comment]
Closing as what @csmarchbanks suggested is the most appropriate answer.
