### ISSUE TITLE
Feature Idea: Weighted Histograms

### ISSUE THREAD

**Issue by falschparker82** [prometheus/prometheus#6001]
## Proposal

Feature Idea: Weighted Histograms

For quantiles, there are two primitives within Prometheus: Summaries and Histograms, both of which are documented to have complementary disadvantages — with a documented tendency toward histograms, as they are aggregatable (we're mainly using them too for this reason).

Histograms have a few more (semi-)documented drawbacks:
- They exhibit clipping behavior if the buckets are not well configured in advance, leaving behind an inexact (clipped) status of a metric that is not retroactively observable.
- Even if working with a metric that has a more or less gaussian distribution, histograms usually exhibit a "staircase" behavior that revolves around the center points of the buckets when metrics slowly change
- Due to the rough nature of the step sizes involved, it's impossible to get an exact average over the whole histogram, even when including all events

Therefore, I propose the following new primitive: Weighted Histograms.

Weighted histograms would not only store the number of events per bucket, but also the *sum* of events content *per bucket*. 

That way, the mentioned behaviors would be counter-acted:

- Clipping behavior towards the edges of a histogram would disappear, _even if misconfigured_, it would be possible to get the extent of a metric over-/underperformance retroactively, since the average of the clipping bucket could still be easily calculated
- Staircase behavior would be reduced, as every bucket would track its own average. A slowly descending metric would take a bucket's average slowly down.
- Last but not least, since the sum and the count of all buckets can be summed at runtime, it's possible again to get an *exact* average, as well as more exact quantiles.

Obviously, there is a tradeoff, as this would need about 50% more storage. Furthermore, the implementation is probably pretty much non-trivial and goes through the whole stack, so I'm not sure it's worth it.

I'm very sorry as I know exactly nothing about the code base, I'm just an advanced end user, feel free to shoot this down — I just thought this idea had enough merit to run by you people. Thanks for all your hard work!

**Comment by brian-brazil** [comment]
> Due to the rough nature of the step sizes involved, it's impossible to get an exact average over the whole histogram, even when including all events

The _sum and _count give you this.


I don't think we're likely to add new types for this, however there's nothing stopping you from playing with this yourself. It shouldn't require any changes to the Prometheus binary to do so.

**Comment by beorn7** [comment]
@falschparker82 Definitely have a look at the existing `_sum` and `_count` metrics, which allows you to calculate the overall average, as @brian-brazil said.

What your suggestion would add is a `_sum` per bucket. I can imagine it would indeed be an improvement over the current interpolation heuristic (which assumes an equal distribution within a bucket), but it will still have the same general problems of averages vs. quantiles, just limited to the bounds of the bucket.

There is a whole lot of whitepapers about the topic of representing histograms in some condensed "digested" way. I have been collecting them for a while, and I'm finally getting to study them in more details. My [upcoming PromCon talk](https://promcon.io/2019-munich/talks/prometheus-histograms-past-present-and-future/) will summarize my preliminary results. This might or might not lead to smaller are more invasive improvements of histograms in the near or far future…

**Comment by beorn7** [comment]
To wrap this up: The talk has happened last week. Recording will soon be linked here: https://promcon.io/2019-munich/talks/prometheus-histograms-past-present-and-future/

As the ideas described here are unlikely to be part of the solution we'll go for, I'll close this issue. That should not imply that nothing will be done in the general direction of improving histograms. I'll report back on my experiments on the developer mailing list. Once things are concrete enough to write a design doc, I'll do so. Eventually, we'll reach a state where we can meaningful file GH issues to track concrete implementation.
