### ISSUE TITLE
Remote write backs up during compaction

### ISSUE THREAD

**Issue by csmarchbanks** [prometheus/prometheus#6007]
## Bug Report
**What did you do?**
Ran remote_write code.

**What did you expect to see?**
Continuous sending of samples to remote storage.

**What did you see instead? Under which circumstances?**
During a compaction samples will backup causing a several minute delay in some cases.

![CompactionRWLag](https://user-images.githubusercontent.com/3280472/64627253-858da900-d3ac-11e9-8672-fde629ea4a64.png)

**Environment**

* System information: Docker/Kubernetes
* Prometheus version: v2.12.0

**Comment by brian-brazil** [comment]
Did you have enough cores for all of it?

**Comment by csmarchbanks** [comment]
> Did you have enough cores for all of it?

Yes, that Prometheus has a large amount of CPU allocated to it and is not significantly CPU throttled during compaction. Also, if it was throttled I would expect some requests to still make it out, it looks like in my case no requests are being sent for a significant amount of time.

![NoRemoteSends](https://user-images.githubusercontent.com/3280472/64637105-597c2300-d3c0-11e9-8da2-b55f13381019.png)

Hoping to dig in a bit more soon.
