### ISSUE TITLE
Unify labels packages

### ISSUE THREAD

**Issue by bwplotka** [prometheus/prometheus#6029]
Currently, we host three `labels` packages exposing really similar logic:

* https://github.com/prometheus/prometheus/tree/master/pkg/labels
* https://github.com/prometheus/prometheus/tree/master/tsdb/labels

Plus proto generated ones: https://github.com/prometheus/prometheus/blob/master/prompb/types.pb.go#L251

This generates massive amount of boilerplate conversions that also allocate extra memory for no reason. Since we moved TSDB into Prometheus we might be able to have only one - so limit con

AC:
* Have only one `labels` package in Prometheus project.

I would propose something brave: 
* Remove all but prompb labels: https://github.com/prometheus/prometheus/blob/master/prompb/types.pb.go#L251
* Move all those helpers from `pkg/labels` and `tsdb/labels` for sorting/comparing/extra matching to some `custom.go` in `prompb` that will add more methods to proto generated `Label` struct.

Any blockers for that? :thinking:

**Comment by brian-brazil** [comment]
What are the performance implications of using proto for this? It looks like more memory at least, and labels are a not-insignificant part of our memory usage.

I think we should unify on to one of the pure-Go packages.

> This generates massive amount of boilerplate conversions that also allocate extra memory for no reason. 

The conversions don't allocate memory.

**Comment by bwplotka** [comment]
> What are the performance implications of using proto for this? It looks like more memory at least, and labels are a not-insignificant part of our memory usage.

Good question, worth to check it before deciding. 
```
type Label struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}
```
You are right that it might use more memory. Wonder if there is any proto generator the does not add those. :/ My point in using proto labels is that there is literally NO way of *not using them*. So if we would operate only on proto Labels it would be quite ideal. 

If we cannot avoid extra fields I guess pure Go might make sense more, let's discuss. (: 

> The conversions don't allocate memory.

Depends on how you do them (: 
I am quite confident that something like this allocates a lot if in the critical path:
```
func labelsTSDBToProm(lset labels.Labels) (res promlabels.Labels) {
	for _, l := range lset {
		res = append(res, promlabels.Label{
			Name:  l.Name,
			Value: l.Value,
		})
	}
	return res
}
```
Am I wrong? 

I guess the better approach would be that unsafe conversion from one struct to second struct. However still you allocate a new slice, plus it sounds a bit wrong to recommend unsafe conversion. Not sure.

**Comment by brian-brazil** [comment]
That's the inefficient way to do the conversion, we use unsafe.

**Comment by bwplotka** [comment]
Can you pont to some example helpers that do such conversion in an unsafe safe way? (: Would be nice to recommend those then.

**Comment by brian-brazil** [comment]
https://github.com/prometheus/prometheus/blob/76769d4b617989c6c60f61a3ba16261f812538c2/storage/tsdb/tsdb.go#L349

**Comment by bwplotka** [comment]
What about proto -> pure Go labels? Would that work seamlessly as well? (despite different struct?)

**Comment by brian-brazil** [comment]
I don't believe so.

**Comment by bwplotka** [comment]
Exactly, so avoiding having both proto + pure Go would be nice. We have to have proto ones, due to our APIs, so ideally using proto would be neat.

Ok let me investigate those options:

A) using JUST proto generated labels. To have that we need to get rid of those custom fields (different protobuf generator? gogo proto upstream issue?)
B) Allow casting proto labels to pure Go ones without allocs. This will allow us to just have both without issues.
If A, B fails we will do C) so just remove `pkg/labels` (I guess?) and keep TSDB and proto ones (: 

Does this sound fair?

**Comment by brian-brazil** [comment]
I'm not sure I'd be a fan of a proto dependency in our core libs. B) sounds like leaking memory contents.

**Comment by ppanyukov** [comment]
What do people think about not generating XXX fields in proto structs? This will make both proto and lib structs same in-memory layout opening ways for efficient unsafe casts and whatnot.

As per https://github.com/thanos-io/thanos/pull/1725

**Comment by bwplotka** [comment]
Fixed in https://github.com/prometheus/prometheus/pull/6326

I think we can investigate unsafe casting to protobuf as separate issue with the thing we did on https://github.com/thanos-io/thanos/pull/1725
