### ISSUE TITLE
tsdb: add block chunks repair cmd tool

### ISSUE THREAD

**Issue by zhulongcheng** [prometheus/prometheus#6031]
## Proposal

we can scan the chunks file and find the first corrupted chunk,
then truncate the chunks file to first corrupted chunk.
Rebuild the index and mete.json by ignoring series those have no chunks.

so that we no need to remove the whole block (lose the whole block data) in order to startup/compact/query.

**Comment by zhulongcheng** [comment]
cc @krasi-georgiev @bwplotka

**Comment by brian-brazil** [comment]
This would be unsafe, partial data is virtually impossible to reason about.

**Comment by krasi-georgiev** [comment]
even if there is a way to delete by a time range? I mean if can delete everything after the corruption this should work ok, right?

**Comment by zhulongcheng** [comment]
> delete everything after the corruption

Yes.

**Comment by krasi-georgiev** [comment]
that was a question for @brian-brazil 
He is more involved in real production uses or Prometheus.

Should it be ok to deleted all data after the corrupted chunk?

**Comment by brian-brazil** [comment]
We looked at this as part of the bug scrub, and a promtool command to drop entire blocks based on them containing corrupt data somewhere is considered reasonable.

**Comment by beorn7** [comment]
Hello from the bug scrub.

We still think this is a useful feature we would accept. But since nobody worked on it in 4y, we assume the need is not urgent enough to justify keeping this issue open.
