### ISSUE TITLE
Prometheus doesn't delete metrics with delete_series

### ISSUE THREAD

**Issue by mslga** [prometheus/prometheus#6046]
## Bug Report
**What did you do?**

Trying to delete metrics from 2 Prometheus pods deployed in k8s cluster. Metrics contain information about old failed jobs which are no longer exits. But since metrics exist, I get alerts for these metrics.

Steps:
1. Check `kube_job_failed` graph in Prometheus UI. Compare list of failed jobs with real list of completed jobs in k8s cluster.

2. Delete not existing jobs:
for first pod:
curl -X POST -g 'http://10.253.96.166:9090/api/v1/admin/tsdb/delete_series?match[]=kube_job_failed{job_name="elasticsearch-backup-curator-1568570100"}' -v

output:
```
*   Trying 10.253.96.166...
* TCP_NODELAY set
* Connected to 10.253.96.166 (10.253.96.166) port 9090 (#0)
> POST /api/v1/admin/tsdb/delete_series?match[]=kube_job_failed{job_name="elasticsearch-backup-curator-1568570100"} HTTP/1.1
> Host: 10.253.96.166:9090
> User-Agent: curl/7.59.0
> Accept: */*
> 
< HTTP/1.1 204 No Content
< Date: Mon, 23 Sep 2019 08:47:04 GMT
< 
* Connection #0 to host 10.253.96.166 left intact

```

for second pod:
curl -X POST -g 'http://10.253.91.60:9090/api/v1/admin/tsdb/delete_series?match[]=kube_job_failed{job_name="elasticsearch-backup-curator-1568570100"}' -v

output:
```
*   Trying 10.253.91.60...
* TCP_NODELAY set
* Connected to 10.253.91.60 (10.253.91.60) port 9090 (#0)
> POST /api/v1/admin/tsdb/delete_series?match[]=kube_job_failed{job_name="elasticsearch-backup-curator-1568570100"} HTTP/1.1
> Host: 10.253.91.60:9090
> User-Agent: curl/7.59.0
> Accept: */*
> 
< HTTP/1.1 204 No Content
< Date: Mon, 23 Sep 2019 08:49:12 GMT
< 
* Connection #0 to host 10.253.91.60 left intact
```

3. Clean old records from disks:
curl -X POST -g 'http://10.253.96.166:9090/api/v1/admin/tsdb/clean_tombstones' -v

output:
```
*   Trying 10.253.96.166...
* TCP_NODELAY set
* Connected to 10.253.96.166 (10.253.96.166) port 9090 (#0)
> POST /api/v1/admin/tsdb/clean_tombstones HTTP/1.1
> Host: 10.253.96.166:9090
> User-Agent: curl/7.59.0
> Accept: */*
> 

< HTTP/1.1 204 No Content
< Date: Mon, 23 Sep 2019 08:48:42 GMT
< 
* Connection #0 to host 10.253.96.166 left intact
```

curl -X POST -g 'http://10.253.91.60:9090/api/v1/admin/tsdb/clean_tombstones' -v
output:
```
*   Trying 10.253.91.60...
* TCP_NODELAY set
* Connected to 10.253.91.60 (10.253.91.60) port 9090 (#0)
> POST /api/v1/admin/tsdb/clean_tombstones HTTP/1.1
> Host: 10.253.91.60:9090
> User-Agent: curl/7.59.0
> Accept: */*
> 

< HTTP/1.1 204 No Content
< Date: Mon, 23 Sep 2019 08:50:43 GMT
< 
* Connection #0 to host 10.253.91.60 left intact
```
4. Restart Prometheus pods

**What did you expect to see?**

I expected that all records with label `elasticsearch-backup-curator-1568570100` will be deleted. And I will not see them in Prometheus UI. 

**What did you see instead? Under which circumstances?**

I still see records with label `elasticsearch-backup-curator-1568570100` in `kube_job_failed` metric in Prometheus UI. 

**Environment**

k8s version: v1.11.5
os-kernel-container-engine: Ubuntu 18.04.2 LTS   4.15.0-46-generic   docker://18.6.1

helm version --tls
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}

Prometheus deployed with Prometheus-operator
chart version: Prometheus-operator-5.0.10
app version: Prometheus-operator  0.29.0

* System information:

	Linux 4.15.0-46-generic x86_64

* Prometheus version:

prometheus, version 2.7.1 (branch: HEAD, revision: 62e591f928ddf6b3468308b7ac1de1c63aa7fcf3)
  build user:       root@f9f82868fc43
  build date:       20190131-11:16:59
  go version:       go1.11.5

* Prometheus configuration file:
```
# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['localhost:9090']

```

**Comment by juliusv** [comment]
Hmm, I can't reproduce this yet. Using Prometheus 2.7.1, I scraped a couple of metrics for the job `node`, then removed that job from the scrape config, then ran:

```
curl -X POST -g 'http://localhost:9090/api/v1/admin/tsdb/delete_series?match[]={job="node"}' -v
```

...and all the series with `job="node"` were gone. Same with just deleting the corresponding `up` metric first.

In case you can make this more reproducible, that would be helpful. And of course, I guess you double-checked everything on your end?

Is the data that is still being returned only recent data, only historic (more than a couple of hours old) data, or both?

**Comment by mslga** [comment]
It's my fail.

I missed first step - I didn't stop scrape metrics for appropriate job.

---
I've repeated all steps including following:
First step. Delete Servicemonitor `prometheus-operator-kube-state-metrics`
...
Last step. Apply Servicemonitor `prometheus-operator-kube-state-metrics`

And it works.

Thank You.
