### ISSUE TITLE
Go get failing with go1.13

### ISSUE THREAD

**Issue by creack** [prometheus/prometheus#6048]
Hello,

It seems like `go get` with prometheus is broken on 1.13, which breaks [opencensus](https://github.com/census-instrumentation/opencensus-service/tree/0.1.1) service (and I suspect anything else depending on prometheus)

prometheus v2.5.0 seems to be working with go1.13, the issue starts at v2.6.0.

Dockerfile to reproduce:

```
FROM golang:1.13

RUN apt-get update && apt-get install -y bzr

ENV GO111MODULE=on

RUN go get -d github.com/prometheus/prometheus@v2.12.0
RUN go get -d github.com/census-instrumentation/opencensus-service@0.1.11
```

When using `golang:1.12`, it works fine.

Error when trying to get promethus directly:

```
go: finding github.com/prometheus/prometheus v2.12.0
go: finding github.com v2.12.0
go: finding github.com/prometheus v2.12.0
go: finding github.com/prometheus/prometheus v2.12.0
go get github.com/prometheus/prometheus@v2.12.0: github.com/prometheus/prometheus@v2.12.0: invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v2
```

Error when trying to get opencensus:

```
go: finding github.com 0.1.11
go: finding github.com/census-instrumentation/opencensus-service 0.1.11
go: finding github.com/census-instrumentation 0.1.11
go: downloading github.com/census-instrumentation/opencensus-service v0.1.1-0.20190905224837-f37ba81b2506
go: extracting github.com/census-instrumentation/opencensus-service v0.1.1-0.20190905224837-f37ba81b2506
go get: github.com/census-instrumentation/opencensus-service@v0.1.1-0.20190905224837-f37ba81b2506 requires
        github.com/prometheus/prometheus@v0.0.0-20190131111325-62e591f928dd requires
        k8s.io/client-go@v2.0.0-alpha.0.0.20181121191925-a47917edff34+incompatible: invalid pseudo-version: preceding tag (v2.0.0-alpha.0) not found
```

**Comment by brian-brazil** [comment]
Hmm, why does census depend on prometheus internals?

This sounds like an issue in the go.mod file of census.

**Comment by creack** [comment]
That's the great thing with go mod, when it fails, you can't know why ^^

```
go mod why github.com/prometheus/prometheus
go: github.com/prometheus/prometheus@v0.0.0-20190131111325-62e591f928dd requires
        k8s.io/client-go@v2.0.0-alpha.0.0.20181121191925-a47917edff34+incompatible: invalid pseudo-version: preceding tag (v2.0.0-alpha.0) not found
```

But even if we remove opencensus from the issue, imho, prometheus should still be go gettable.

**Comment by brian-brazil** [comment]
Yes, all of `prometheus/prometheus` are internals. There's various Prometheus-related projects out there that import bits of it (e.g. Cortex/Thanos), but general software shouldn't be.

The public bits are in the `client_golang` repo.

**Comment by brian-brazil** [comment]
https://github.com/census-instrumentation/opencensus-service/blob/7b57179e7a2a0a9999ff7dcd331d65dec8747b8a/receiver/prometheusreceiver/metrics_receiver.go looks to be it, which is an okay dependency similar to the Cortex/Thanos use cases. It's also a you break it you bought it case, as these are technically unsupported internals that you depend on at your own risk.

Searching around, this looks like a thing that Go modules has yet to figure out. 2.6 was where we added Go modules.

**Comment by creack** [comment]
Thanks you, i'll move it there then. Still sad that bumping go version breaks the build.. I wish the go1compat contract would extend to the toochain

**Comment by simonpasquier** [comment]
FTR `go get github.com/prometheus/prometheus@v2.12.0` with Go 1.13 fails because Prometheus doesn't respect the Go modules rules: the module name should have been `github.com/prometheus/prometheus/v2`. Unfortunately we can't change it now and in any case Prometheus wouldn't respect SemVer either since its versioning doesn't care about (Go) API stability. The workaround is to `go get` the commit ID corresponding to the tag you're interested in: `go get github.com/prometheus/prometheus@43acd0e2e93f9f70c49b2267efa0124f1e759e86`.

**Comment by brian-brazil** [comment]
We looked at this in the bug scrub, and these are internals which we don't support dependencies on. However https://github.com/modularise/prometheus-tsdb and friends should let you resolve this, so closing.

**Comment by base698** [comment]
@brian-brazil I'm importing "github.com/prometheus/prometheus/discovery/targetgroup" for use in a service discovery.  Is that moved elsewhere so not to be considered internal?
