### ISSUE TITLE
Querying raw datapoints

### ISSUE THREAD

**Issue by stapelberg** [prometheus/prometheus#605]
I have a boolean value that I’m scraping (i.e. it can be either 0 or 1, nothing else), and I’m having trouble figuring out how to query prometheus so that it will give me the raw data points. In promdash, I always get interpolated points, and even hitting the API end point directly, I get interpolated data points:

```
curl -s 'http://localhost:9090/api/query_range?end=1426873307&expr=raft_isleader&step=30&range=60'         
{"type":"matrix","value":[
{"metric":{"__name__":"raft_isleader","instance":"alp","job":"robustirc"},"values":[[1426873230,"0"],[1426873260,"0"],[1426873290,"0.17326666666666668"]]},
{"metric":{"__name__":"raft_isleader","instance":"dock0","job":"robustirc"},"values":[[1426873230,"0"],[1426873260,"0"],[1426873290,"0"]]},
{"metric":{"__name__":"raft_isleader","instance":"ridcully","job":"robustirc"},"values":[[1426873230,"0"],[1426873260,"0"],[1426873290,"0"]]}],"version":1}
```

Note how values contains 0.1732…

How can I get just the raw, scraped data points for debugging/understanding my time series better?

**Comment by juliusv** [comment]
@stapelberg We want to have better support for getting raw data out, but there's already a way:

There's a `query` (vs. `query_range`) endpoint for instant queries - that is also what the tabular view uses. If you query it for an instant vector, you will get the raw latest value (but with a time of "now" vs. of the actual sample timestamp). But if you query it for a range vector (`foo[1h]`), you will get the completely raw versions of all data points within that time window, stretching back into the past from now.

For example:

    http:/localhost:9090/api/query?expr=up[10m]

That also works (giving completely raw samples) when doing the same in the tabular view of the expression browser.

**Comment by stapelberg** [comment]
Thanks for explaining, this is what I’ve been looking for :).

**Comment by brian-brazil** [comment]
Looks like this was answered.

**Comment by jf** [comment]
It looks like this isn't possible now? (getting a 404 now, just with `http://localhost:9090/api/query?expr=node_disk_bytes_written`; Prometheus 1.4.1 here)

**Comment by juliusv** [comment]
The unversioned legacy API was removed. Try: http://localhost:9090/api/v1/query?query=node_disk_bytes_written

See also https://prometheus.io/docs/querying/api/

**Comment by rohitChaware** [comment]
Is this endpoint "GET /api/query?expr=<prometheus_query_expression>" documented? Also, are there any POST endpoints? I didn't find them on [](https://prometheus.io/docs/querying/api/) .

**Comment by juliusv** [comment]
@rohitChaware No, that's the old legacy endpoint which doesn't exist anymore in recent Prometheus versions. If with a POST endpoint you mean an endpoint for pushing data, that doesn't exist.

All current API methods are documented at https://prometheus.io/docs/querying/api/

**Comment by rohitChaware** [comment]
Thanks @juliusv for the quick response! Is there any other similar way to pass directly a Prometheus query expression to Prometheus without passing separate query parameters in URL? This "GET /api/query?expr=<prometheus_query_expression>" is really helpful.

**Comment by juliusv** [comment]
@rohitChaware No, they expression query is always sent via a query parameter. What would you have imagined?

**Comment by rohitChaware** [comment]
The APIs documented send individual Prometheus expression query parameters(like start, end, step) separately in URL parameters. But in this "GET /api/query?expr=<prometheus_query_expression>", we are sending the complete Prometheus expression as a URL parameter. And I am looking for the latter type of API. Please correct me if my understanding is not right.
