### ISSUE TITLE
support   golang.org/x/sys/windows  GetCurrentProcess  function error ?

### ISSUE THREAD

**Issue by sixinyiyu** [prometheus/prometheus#6060]
..\..\..\src\github.com\prometheus\client_golang\prometheus\process_collector_windows.go:78:9: assignment mismatch: 2 variables but "golang.org/x/sys/windows".GetCurrentProcess returns 1 values

**Comment by brian-brazil** [comment]
We're aware, this is a breaking change in Go 1.13 for which a fix is currently in progress over in client_golang.
