### ISSUE TITLE
promql: Parser bug: Prometheus does not accept spaces after opening brace in subquery.

### ISSUE THREAD

**Issue by slrtbtfs** [prometheus/prometheus#6065]
## Bug Report
**What did you do?**
 
Gave Prometheus a query like `some_query[ 5s]`. Note the space after the bracket.

**What did you expect to see?**
The query get's parsed to the same as  `some_query[5s]` (without space).

**What did you see instead? Under which circumstances?**

` Error executing query: invalid parameter 'query': parse error at char 12: missing unit character in duration`

**Environment**

* System information:

	`Linux 5.2.16-200.fc30.x86_64 x86_64`

* Prometheus version:
`prometheus, version 2.12.0 (branch: master, revision: 8d3083e2563812da1c1125fafb20b9fe2469f4ba)`

**Comment by slrtbtfs** [comment]
Shouldn't be hard to fix. Can do a PR for that after #6061 is merged.

**Comment by brian-brazil** [comment]
That's a range vector selector, not a subquery. Did we ever say that we support this?

**Comment by brian-brazil** [comment]
Looking through our docs, we never say that spaces are supported here. Thus this behaviour is correct, though the error could be a bit more useful.

**Comment by slrtbtfs** [comment]
> That's a range vector selector, not a subquery. 

Oops, my fault. But it fails for both range vector and subquery selectors.

>  Looking through our docs, we never say that spaces are supported here. Thus this behaviour is correct, though the error could be a bit more useful.

We ignore redundant spaces basically everywhere else, without mentioning it in the docs. It's inconsistent to not ignore them here.

If we keep it like this, we'd rather have to document that we don't support spaces in that specific edge case. 

Queries that do not fail:

`some_query[5s    ]`

`some_query    [5s]`

Queries that fail:

`some_query[   5s]`

Having that in the docs would look kinda ridiculous.

**Comment by brian-brazil** [comment]
This is true.
