### ISSUE TITLE
My Prometheus server doesn't return all custom metrics

### ISSUE THREAD

**Issue by debashish-github** [prometheus/prometheus#6066]
Hi,
   I have this weird problem . I have created some generated as well as custom metric using springs Actuator/Micorometer framework targeted for Prometheus 2.0.0. 
The metric shows up correctly in all environments except Production .

In Production out of about 10 custom metric only couple of them show the values correct consistently. Rest all show the values correctly for a while and then are all set to 0.
When I query the same scrape url from browser all the values are returned .

scrape_interval for my job is 2m and scrape timeout is 90s .

Can you please point out what could be the issue here ?

Thanks

## Proposal
**Use case. Why is this important?**

*“Nice to have” is not a good use case. :)*

## Bug Report
**What did you do?**

**What did you expect to see?**

**What did you see instead? Under which circumstances?**

**Environment**

* System information:

	insert output of `uname -srm` here

* Prometheus version:

	insert output of `prometheus --version` here

* Alertmanager version:

	insert output of `alertmanager --version` here (if relevant to the issue)

* Prometheus configuration file:
```
insert configuration here
```

* Alertmanager configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
