### ISSUE TITLE
Consul SD should account for agent health

### ISSUE THREAD

**Issue by alkalinecoffee** [prometheus/prometheus#6067]
## Bug Report/Proposal

**Summary**

One of our alertmanager instances was terminated due to EC2 health check failure.  Since the node was not properly removed from the Consul cluster, Consul continued to return this dead node when the service catalog is queried.  Because of this, Prometheus attempted to send alerts to the terminated instance.

**What did you do?**

We have the following in our prometheus config to use consul service discovery to find nodes with the `alertmanager` service:

```
alerting:
  alertmanagers:
  - consul_sd_configs:
    - server: localhost:8500
      datacenter: us-east-1
      tag_separator: ','
      scheme: http
      allow_stale: false
      refresh_interval: 30s
      services:
      - alertmanager
```

**What did you expect to see?**

We expect Prometheus to only utilize Consul nodes that are passing the Consul agent health check.

**What did you see instead? Under which circumstances?**

Prometheus was using a terminated EC2 instance as an alertmanager endpoint.  This instance was still registered in Consul, but its Consul agent health check was failing.

Also seeing the IP of the dead node repeatedly in the logs:

```
level=error ts=2019-09-27T14:31:17.174Z caller=notifier.go:482
  component=notifier alertmanager=http://xxx.xxx.xxx.xxx:443/api/v1/alerts
  count=0 msg="Error sending alert"
  err="Post http://xxx.xxx.xxx.xxx:443/api/v1/alerts: context deadline exceeded"
```

**Proposal**

We believe that, if available, the basic consul agent health check should be taken into account when determining whether an alertmanager instance should be used in the Prometheus configuration.

Additionally, it would be a plus if we could, via the consul SD configuration, configure specific health checks Prometheus should look for when querying Consul.  For example, we have an HTTP consul health check to ensure the alertmanager service is ready.  It would be great if that custom health check is considered before adding that instance to the alertmanager pool.

**Environment**

* System information:

```
Linux 4.14.109-80.92.amzn1.x86_64 x86_64
```

* Prometheus version:

```
  build user:       root@4d7ed54ba6d9
  build date:       20190415-09:06:49
  go version:       go1.12.3
```

* Alertmanager version:

```
  build user:       root@868685ed3ed0
  build date:       20190708-14:31:49
  go version:       go1.12.6
```

**Comment by brian-brazil** [comment]
This is by design, you don't want to stop scraping a target just because its failing healthchecks - in fact scrapes are important there.

For the alertmanager, it's fairly harmless to attempt to send alerts to a dead one.

If you want to control this, it is possible via relabelling but not recommended.

**Comment by liozN** [comment]
What about making sure that their serf service is passing successfully?
If an agent is dead, its services keeps their last known state (which might be "passed") and when prometheus tries to scrape them it will get timeout.
If there was a check for serf status - it wouldn't happen.
