### ISSUE TITLE
strip trailing slashes for -alertmanager.url, complain about errors

### ISSUE THREAD

**Issue by stapelberg** [prometheus/prometheus#607]
When ending -alertmanager.url in a trailing slash (you’re saying it’s a URL!), alertmanager replies with an HTTP redirect, and the alert that prometheus sent is just lost. Prometheus won’t even realize that and will not print a message to the log. I think both should be fixed :).

**Comment by juliusv** [comment]
For Prometheus, see https://github.com/prometheus/prometheus/pull/612

**Comment by juliusv** [comment]
And for alertmanager, see https://github.com/prometheus/alertmanager/pull/42
