### ISSUE TITLE
Remote_write unable to send due to `segments are not sequential` error

### ISSUE THREAD

**Issue by jacksontj** [prometheus/prometheus#6080]
## Bug Report
**What did you do?**
Restarted prometheus after a crash

**What did you expect to see?**
Prometheus start and continue to send metrics to remote_write endpoint

**What did you see instead? Under which circumstances?**
Prometheus starts and scrapes metrics, but the logs are littered with:
```
prometheus[19563]: level=error ts=2019-10-01T02:43:23.492Z caller=wal_watcher.go:176 component=remote queue=1:<REMOTE_WRITE_ENDPOINT> msg="error tailing WAL" err="wal.Segments: segments are not sequential"
```

When I look at the wal directory I can see that I have `00000007.repair` in the wal directory.  This means in the [listSegments](https://github.com/prometheus/prometheus/blob/master/tsdb/wal/wal.go#L762) call it is skipped, meaning it reads 6 then 8 and then complains about this error. I then attempted to restart prometheus (thinking it would re-write the WAL or finish the repair) -- but unfortunately it now won't start -- with the same error (`segments are not sequential`). So this means that now I can't do anything with prometheus until I manually clear the WAL file -- which seems not-so-good :)

So with that in mind, it seems that we should probably add some option (env var, cli flag) to allow for partial WAL files -- otherwise if *any* file is corrupt the only way to get prometheus to start is to delete them all or manually rename all the files.

**Environment**

* Prometheus version: 2.12.0

**Comment by brian-brazil** [comment]
Were there any previous log messages relating to the repair?

**Comment by jacksontj** [comment]
Just an error renaming the file (not sure what it meant since it obviously
renamed it). My concern is less about how it got corrupt and more that it
seems to get you into this error mode that requires blots of undocumented
manual intervention.

**Comment by geekhead** [comment]
We've just run into this exact same issue today with the exact same error. However, I didn't see a ####.repair file in the wal directory but still had to stop prometheus, remove all wal files, start back up prometheus to get remote_write to start sending metrics again.

**Comment by Harkishen-Singh** [comment]
@jacksontj @geekhead could you please tell the probable situation before getting `segments not sequential` error.

**Comment by krasi-georgiev** [comment]
@jacksontj can you confirm if this is using local storage, ceph or different?

**Comment by jacksontj** [comment]
This was using local storage (nothing fancy)

**Comment by cstyan** [comment]
Is missing WAL segments we would want to handle during a start up, with a note that all segments after the last sequential segment will be removed and data may be lost?

**Comment by brian-brazil** [comment]
Yes, the same way we handle any other wal corruption.

**Comment by beorn7** [comment]
Hello from the bug scrub.

With more than 4y of silence, we are wondering if working in this still makes sense. @cstyan could you make a call here?

**Comment by cstyan** [comment]
@beorn7 I'm not sure, but I suspect there's something we can still do here to handle things more gracefully. It's been a long time since I looked, but IIRC the TSDB/WAL code should do a repair on restart. I would expect that repair to leave the WAL in a state that is usable by remote write. In this issue, either that was not happening, or remote write was trying to restart while the repair was still unfinished.

**Comment by beorn7** [comment]
OK, thank you. I think we close this now and re-open if this incident is reported again.
