### ISSUE TITLE
JSON Schema for prometheus.yml

### ISSUE THREAD

**Issue by dhruvin2910** [prometheus/prometheus#6082]
## Proposal
**Use case. Why is this important?**
It'd be great if we can have a json schema for prometheus.yml (and other configuration files, if there are any). It'll help developers using IDEs or editors, by providing autocompletion and inline documentation (maybe with typing). I see a swagger file in documentation/dev/api, this proposal is along those lines.

I am interested in contributing schema file; to this repo or to SchemaStore. Let me know if this can add value to the project. Thanks.

**Comment by simonpasquier** [comment]
FWIW the swagger documentation is for the v2 API of Prometheus which is experimental (and likely to be removed at some point). I'm not sure how we can ensure that the JSON schema is kept in sync with the Prometheus code.

**Comment by dhruvin2910** [comment]
> FWIW the swagger documentation is for the v2 API of Prometheus which is experimental (and likely to be removed at some point).

Okay.
> I'm not sure how we can ensure that the JSON schema is kept in sync with the Prometheus code.

I am almost done with the spec (currently faithful to the [documentation](https://prometheus.io/docs/prometheus/latest/configuration/configuration) only, with some issues).

I think there are three options.
1. We update the spec manually just like we update the documentation. But I don't know how often does the schema change, but I understand that doing so is error-prone.
2. We generate schema from the documentation, if the docs are generated by code. See [ansible-schema-generator](https://github.com/shaded-enmity/ansible-schema-generator). I think [godoc](https://godoc.org/github.com/prometheus/prometheus/config#Config) will help there.
3. We generate schema from the code directly (parsing the source file, mainly the structs and tags), but I think it'll be a fair amount of work. (I might be wrong here, I'm relatively new to the language).

Can you give me any ideas (or your opinions on it)?

**Comment by dhruvin2910** [comment]
I have created a PR to SchemaStore/schemastore#821 with the configuration and rules schema (as of v2.13). 

The schema does not include service discovery configs, as I was not sure about how frequently will they change, and they're labeled not stable for 2.x.

It'd be great if someone can try it out and let me know.

The schema will (hopefully) be available from the schemastore. It is not generated from code/docs, hence it may be a bit outdated (or even stale), as new versions with changes in config files come. And I (or someone else) will be updating the schema manually.

I'm closing this issue assuming we are fine with the delays.
