### ISSUE TITLE
Feature request: shutdown options

### ISSUE THREAD

**Issue by fritchie** [prometheus/prometheus#6086]
This is a feature request.

Having the ability to choose whether a full flush takes place during shutdown can be very useful in certain situations. One such case is draining Kubernetes nodes where some of the pods run Prometheus. Having a slow startup would be preferred to a slow shutdown. 

I am thinking of something like innodb_fast_shutdown:

dev.mysql.com/doc/refman/8.0/en/innodb-parameters.html#sysvar_innodb_fast_shutdown

**Comment by bwplotka** [comment]
Thanks for this!

Overall, I found flush to WAL very efficient right now, unless you use some slow disk or (:scream:) NFS... 

 I am afraid Prometheus (actually TSDB) does not have any intermitted transactions like InnoDB, but also ingestion is usually way faster than casual DB writes. 

Just curious, are you experiencing a slow shutdown with Prometheus 2.x? Can you share numbers, how long exactly, how large your Prometheus is? What disk do you sue? Maybe it's stuck on something else then flushing?

**Comment by fritchie** [comment]
thx, the issue is definitely slow storage in this case. I will close this.
