### ISSUE TITLE
Extend promtool with all commands from the tsdb tool and remove the tsdb tool

### ISSUE THREAD

**Issue by krasi-georgiev** [prometheus/prometheus#6087]

**Comment by yeya24** [comment]
I' d like to work on it. But what about #6085? Is it still necessary?

**Comment by codesome** [comment]
@yeya24 #6085 would be a temporary solution till we merge tsdb tool with promtool. Please go ahead with it if you are interested!

**Comment by codesome** [comment]
Oh, I see you already opened a PR, thanks!
