### ISSUE TITLE
Building from .zip should be possible

### ISSUE THREAD

**Issue by quinox** [prometheus/prometheus#609]
Currently you cannot build Prometheus using the zip-files mentioned in fe. https://github.com/prometheus/prometheus/releases/tag/0.12.0.

When you try you get a bunch of warnings such as `fatal: Not a git repository (or any parent up to mount point /tmp)` eventually followed by the usage output of 6l and the failure `Makefile:30: recipe for target 'build' failed`.

Relevant chat on IRC:
> jrv | ah, the zip file doesn't work because the Makefile expects the source directory to still be a git repository.
> jrv | GitHub creates those zip files automatically, so we never tried that.
> jrv | "-X main.buildRevision" isn't followed by an argument for that reason, which is why ld6 crashes
> jrv | cause that's built via a git command
> jrv | VERSION=$(shell cat `git rev-parse --show-toplevel`/VERSION)

**Comment by abraithwaite** [comment]
Is there any reason this version can't be in the Makefile?

It'd be nice to build it from an archive which have predictable stable urls.

**Comment by matthiasr** [comment]
Reopening, as discussed in #707 this is not really _fixed_ yet.

As a workaround, set the `VERSION` variable either as `VERSION=something make` or `make VERSION=something`. After #707, both do the same.
