### ISSUE TITLE
remote_write unreliable (stops writing) after prolonged connection issue to remote, during resharding

### ISSUE THREAD

**Issue by zytek** [prometheus/prometheus#6095]
## Bug Report
**What did you do?**

Set up remote_write to Victoria Metrics. Default queue config.
Prometheus is deployed via prometheus-operator on kubernetes.

**Expectations vs reality**

After connectivity issues to remote - either via unstable connection (AWS to AWS China) or because Remote had issues (EC2 failure, took more than 30 minutes to heal and be available again) Prometheus gives up. 

Once remote becomes available again Prometheus does not retry.

Logs suggest that resharding might be a culprit here - as resharding means flushing data from old shards which was impossible due to connection issues.

I consider this a reliability bug - as it causes me to restart Prometheus. 
Either retry logic or default configuration issue (need advice here) or resharding logic.

My expected behaviour would be:
1. Backoff increases to some high, but reasonable value (30s - 5 minutes)
2. Retry is indefinite
3. Each WAL rotation means I lose data, but this is acceptable 
4. Resharding is either cancelled or retried if buffers could not be flushed 

My workaround was to se min_shards to 1000, so resharding would not take place. I will perform more tests later to check if this actually helps. 

**Environment**

* System information:

Prometheus 2.10.0 deployed on Kubernetes 1.11 via prometheus-operator.

```
level=info ts=2019-10-02T14:41:22.597Z caller=main.go:322 msg="Starting Prometheus" version="(version=2.10.0, branch=HEAD, revision=d20e84d0fb64aff2f62a977adc8cfb656da4e286)"
level=info ts=2019-10-02T14:41:22.597Z caller=main.go:323 build_context="(go=go1.12.5, user=root@a49185acd9b0, date=20190525-12:28:13)"
level=info ts=2019-10-02T14:41:22.597Z caller=main.go:324 host_details="(Linux 4.4.0-1079-aws #89-Ubuntu SMP Tue Mar 26 15:25:52 UTC 2019 x86_64 prometheus-prometheus-operator-prometheus-0 (none))"
level=info ts=2019-10-02T14:41:22.597Z caller=main.go:325 fd_limits="(soft=1048576, hard=1048576)"
level=info ts=2019-10-02T14:41:22.597Z caller=main.go:326 vm_limits="(soft=unlimited, hard=unlimited)"
```

* Logs:
```
ts=2019-10-02T14:41:52.619Z caller=dedupe.go:111 component=remote level=info queue=0:https://vminsert.cosmose.cloud/insert/1/prometheus msg="Remote storage resharding" from=1000 to=634
ts=2019-10-02T14:42:02.619Z caller=dedupe.go:111 component=remote level=info queue=0:https://vminsert.cosmose.cloud/insert/1/prometheus msg="Currently resharding, skipping."
ts=2019-10-02T14:42:12.619Z caller=dedupe.go:111 component=remote level=info queue=0:https://vminsert.cosmose.cloud/insert/1/prometheus msg="Currently resharding, skipping."
ts=2019-10-02T14:42:22.619Z caller=dedupe.go:111 component=remote level=info queue=0:https://vminsert.cosmose.cloud/insert/1/prometheus msg="Currently resharding, skipping."
ts=2019-10-02T14:42:32.619Z caller=dedupe.go:111 component=remote level=info queue=0:https://vminsert.cosmose.cloud/insert/1/prometheus msg="Currently resharding, skipping." 
ts=2019-10-02T14:42:52.619Z caller=dedupe.go:111 component=remote level=error queue=0:https://vminsert.cosmose.cloud/insert/1/prometheus msg="Failed to flush all samples on shutdown"
ts=2019-10-02T14:43:02.619Z caller=dedupe.go:111 component=remote level=info queue=0:https://vminsert.cosmose.cloud/insert/1/prometheus msg="Remote storage resharding" from=634 to=1000
ts=2019-10-02T14:44:02.620Z caller=dedupe.go:111 component=remote level=error queue=0:https://vminsert.cosmose.cloud/insert/1/prometheus msg="Failed to flush all samples on shutdown"
ts=2019-10-02T14:44:03.883Z caller=dedupe.go:111 component=remote level=error queue=0:https://vminsert.cosmose.cloud/insert/1/prometheus msg="non-recoverable error" count=8 err="context canceled"
```

cc @byakku

**Comment by csmarchbanks** [comment]
Hello, Prometheus v2.12.0 had some improvements around how the number of shards are calculated that may help your situation.

Are you using the default remote write configuration? If so, it can have very bad performance with high numbers of shards (defaults are improved in v2.12.0).

I have had this situation occur (remote endpoint down, came back later) and have successfully caught up, but the timing may have been different. Generally your expected behavior is what I see, with the exception of backoff, which by default only increases to 100ms.

**Comment by cstyan** [comment]
Resharding shouldn't result in remote write exiting as a whole. If it does we have a bug.

> Retry is indefinite

It is, with the exception of shard shutdown scenarios (resharding, Prometheus shutting down, etc.). In these cases we retry with backoffs for up to 1m (by default), and then force shutdown of the shards.

> Each WAL rotation means I lose data, but this is acceptable

Do you mean checkpointing? If you're remote write has fallen far enough behind, then yes it can potentially mean you lose data.

> Resharding is either cancelled or retried if buffers could not be flushed

The resharding won't take place if remote write hasn't been able to write any samples successfully recently. Or at least it shouldn't be, but it looks like that was removed at some point

**Comment by zytek** [comment]
Hey,
thanks for taking a look at this bug. 

> Are you using the default remote write configuration? If so, it can have very bad performance with high numbers of shards (defaults are improved in v2.12.0).

Yes, I was using default. There are a ton of resharding events happening every few seconds which does not sound like an optimal setup. Logs attached.

> Resharding shouldn't result in remote write exiting as a whole. If it does we have a bug.

Yep, it seems we have a bug. Logs suggest exactly that - failure to shutdown old shards during resharding resulting in unrecoverable error. 

It has happened on a second prometheus instance recently, with similar log output. I've implemented the same workaround (minShards=maxShards) and hope it helps. It did help on a second cluster.

I've attached full logs from recent event, you can notice that resharding is too aggressive (unstable connection probably) and at the end, due to failure to shutdown old shards, it stops sending metrics to remote. 

[PROM-CNNW.log](https://github.com/prometheus/prometheus/files/3701461/PROM-CNNW.log)

I can test newer prometheus version with shard count enhancements, but I believe it will only decrease probability of this event, not fix it - if there were no changes to shard shutdown logic / error recovery. Please advice if you would like me to test some other scenarios.

**Comment by glightfoot** [comment]
We got around this issue previously by setting `min_shards` equal to `max_shards` to disable the resharding operation until we upgraded to the latest version

**Comment by cstyan** [comment]
> Yes, I was using default. There are a ton of resharding events happening every few seconds which does not sound like an optimal setup. Logs attached.

Yeah the resharding calculation has had lots of improvements and the default queue configs have been updated as well. Please try 2.13.

> Yep, it seems we have a bug. Logs suggest exactly that - failure to shutdown old shards during resharding resulting in unrecoverable error.

I'm not seeing this in your logs. I see failed to flush followed immediately by more resharding events. The logs like ```ts=2019-09-27T14:32:22.347Z caller=dedupe.go:111 component=remote level=error queue=0:https://vminsert.cosmose.cloud/insert/1/prometheus msg="non-recoverable error" count=68 err="context canceled"``` are just for an individual send, and won't result in remote write exiting as a whole.
> 
> It has happened on a second prometheus instance recently, with similar log output. I've implemented the same workaround (minShards=maxShards) and hope it helps. It did help on a second cluster.
> 
> I've attached full logs from recent event, you can notice that resharding is too aggressive (unstable connection probably) and at the end, due to failure to shutdown old shards, it stops sending metrics to remote.

I still see more resharding events after the last `failed to flush` log line.

> I can test newer prometheus version with shard count enhancements, but I believe it will only decrease probability of this event, not fix it - if there were no changes to shard shutdown logic / error recovery. Please advice if you would like me to test some other scenarios.

We'd have to dig deeper to confirm there's a bug, the only fix I can make so far is to not reshard if the remote endpoint is down, which we had before but seems was unintentionally removed as part of a refactor: https://github.com/prometheus/prometheus/pull/6111

Another suggestion is to look at some of the metrics for remote write when you see this happen. Specifically rates for samples sent, the WAL watcher reading the WAL, etc. I usually use the queries in this dashboard as a starting point: https://github.com/prometheus/prometheus/blob/master/documentation/prometheus-mixin/dashboards.libsonnet#L93-L146

For example if `rate(prometheus_remote_storage_succeeded_samples_total)` is non-0 but not able to keep up with `rate(prometheus_remote_storage_samples_in_total)` you may need to scale up your remote storage or drop some series via relabelling.

**Comment by zytek** [comment]
Thanks @cstyan 

I'll wait for prometheus-operator to provide 2.13 and will deploy without my workaround. Shall this happen again I will update this issue.

Thanks for pointing out how to monitor remote write, this will be helpful.

**Comment by zytek** [comment]
We are seeing big improvements in remote_write reliability in 2.13 (even without #6111).

Works fine for >24 hours on two clusters, with one having flaky connection to remote endpoint. Makes it lag 2-5 minutes, but otherwise works ok.

**Comment by csmarchbanks** [comment]
Glad to hear 2.13 is working better for you! We have noticed the lag as well, it seems like the desired shards calculation is finding an equilibrium that has a bit of lag in some cases rather than forcing the number of pending samples to zero.
