### ISSUE TITLE
Rearrange the packages to put `CreateBlock` in  `tsdbutil` and avoid circular import

### ISSUE THREAD

**Issue by krasi-georgiev** [prometheus/prometheus#6136]

**Comment by dipack95** [comment]
`createBlock` referred to, is here: https://github.com/prometheus/prometheus/pull/5887/files#diff-deb37515bb9a472285c2cd38d5649deeR346

**Comment by droidnoob** [comment]
Is this still open. I'd like to take this up @krasi-georgiev

**Comment by codesome** [comment]
@droidnoob I see this issue is being addressed in https://github.com/prometheus/prometheus/pull/5887

**Comment by krasi-georgiev** [comment]
nope this is only a temporary solution in that linked PR as it moves is in the main tsdb package to avoid the circular import cycle.
I think we should try to organize it better

**Comment by jpmcb** [comment]
I've been looking at this issue today and I see a few paths forward:
1. Break each dependent component into it's own package. For example, where `NewHead` is called: 

```
head, err := NewHead(nil, logger, nil, chunkRange, DefaultStripeSize)
```

instead, break out the `head` files into their own packages:

```
h, err := head.NewHead(nil, logger, nil, chunkRange, DefaultStripeSize)
```

It could then be imported as `.../tsdb/head`. I played around with this a bit and it would be quite the refactor as there are several dependent private methods within the `tsdb` package that would need to become public or change how their individual APIs are accessed. 

2. Create a `tsdbutil-broker` package that would break the circular dependency between tsdb and tsdbutil. I think this could be a good solution.

Any other thoughts? Or do one of these approaches seem favorable?

**Comment by krasi-georgiev** [comment]
@codesome mentioned that he found another way to create blocks without relying on the NewHead method so maybe he can also share his idea.

**Comment by gouthamve** [comment]
@krasi-georgiev / @codesome  What is the requirement/use-case here? Where is the circular import happening?

We went through this issue in our bug scrub and we didn't fully get the context around this.

**Comment by krasi-georgiev** [comment]
was long time ago and can't remember either.
