### ISSUE TITLE
feature: Support loading file for Consul Token

### ISSUE THREAD

**Issue by damoun** [prometheus/prometheus#6140]
## Proposal

I use vault as a secret storage solution and I think it could be useful to support loading the consul token from a file like the `bearer_token_file`. For exemple, the Marathon SD already support it.

What do you think ?
If you like it, I could start working on a PR.

Thanks

**Comment by rockyluke** [comment]
I love the idea!

**Comment by roidelapluie** [comment]
The issue is that the upstream consul library never re-reads the file again. Would that still suit your need?

https://github.com/hashicorp/consul/blob/c91d0fa2c9629d74e5fe70e4acf9351f5c22858d/api/api.go#L305

**Comment by brian-brazil** [comment]
That's not in line with how we do such files elsewhere, and I can see that causing confusion.

**Comment by gouthamve** [comment]
We went through this issue in our bug scrub and this might be possible by switching to a httpTransport passed to the consul client.

@roidelapluie Could you investigate the issue further, and tag it appropriately? As you've looked at this last.

**Comment by beorn7** [comment]
Closing this as it is now superseded by #8551

**Comment by roidelapluie** [comment]
This is being worked on as part of #8924
