### ISSUE TITLE
sum_over_time(metrics) different with metric

### ISSUE THREAD

**Issue by gaopeiliang** [prometheus/prometheus#6143]
**What did you do?**
I use sum_over_time(metric) to fire alert ....
In my case , I think sum_over_time(metric) will equal with metric ,, but it not ....

Is there something else with func sum_over_time ....

![image](https://user-images.githubusercontent.com/11383058/66903276-c4aabc00-f034-11e9-9e9b-e318b62a98e7.png)

![image](https://user-images.githubusercontent.com/11383058/66903305-d12f1480-f034-11e9-9822-317899ecdc31.png)

**What did you expect to see?**
that two expr should be equal , and will not fire alert ....

**Environment**

* System information:

	Linux 3.10.0-327.el7.x86_64 x86_64

* Prometheus version:

	prometheus 2.5.0  67dc912ac8b24f94a1fc478f352d25179c94ab9b

**Comment by simonpasquier** [comment]
Thanks for your report. It looks as if this is actually a question about usage and not development.

To make your question, and all replies, easier to find, we suggest you move this over to our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search. If you prefer more interactive help, join or our [IRC channel](https://webchat.freenode.net/?randomnick=1&channels=prometheus), #prometheus on irc.freenode.net. Please be aware that our IRC channel has no logs, is not searchable, and that people might not answer quickly if they are busy or asleep. If in doubt, you should choose the mailing list.

Once your questions have been answered, please add a short line pointing to relevant replies in case anyone stumbles here via a search engine in the future.
