### ISSUE TITLE
uPlot.js time series chart

### ISSUE THREAD

**Issue by leeoniya** [prometheus/prometheus#6144]
Hey guys,

I just wanted to put [uPlot.js]( https://github.com/leeoniya/uPlot/) on your radar in case there was any interest in evaluating an alternative to rickshaw.js, which seems to be the lib used for generating time-series graphs in the Prometheus Web UI.

Its roots are also in displaying server perf logs (originally dumped into CSV by dstat). Here is a demo of it rendering 170,000 data points (spread across 3 series) in 40ms:

https://leeoniya.github.io/uPlot/bench/uPlot.html

original suggestion from @dgl: https://github.com/leeoniya/uPlot/issues/19#issue-506347811

that is all. thanks!

**Comment by juliusv** [comment]
@leeoniya Thanks. The new React UI that just got merged (in an initial, unlinked version) in https://github.com/prometheus/prometheus/pull/5694 switches from Rickshaw to Flot, which is what Grafana also uses. I (informally) evaluated a bunch of different graphing libraries for our needs in February, and most were missing either key features or weren't easy or efficient to integrate.

I don't think I was aware of uPlot.js yet. It looks interesting. However, I think we'd need a concrete motivation for moving from Flot to another library. Pure graphing performance of Flot is definitely more than good enough for us.

**Comment by juliusv** [comment]
We're pretty minimal in what we do in the built-in UI (we don't want to reimplement all of Grafana's dashboarding features). But I think we do still want to support stacked graphs (+ area fills for that), so that would be at least one missing feature.

Since it doesn't seem likely that we'd want to switch at the moment, I'm going to close this issue for now. But I'll definitely keep an eye on uPlot, thanks for bringing it to my attention!

**Comment by leeoniya** [comment]
FWIW, there's now support for high/low bands [1], area fills & hover focus [2] and a bunch more neat stuff. however, stacked series are still unlikely to ever be implemented due to their misleading nature [3].

[1] https://leeoniya.github.io/uPlot/demos/high-low-bands.html
[2] https://leeoniya.github.io/uPlot/demos/focus-cursor.html
[3] https://everydayanalytics.ca/2014/08/stacked-area-graphs-are-not-your-friend.html
