### ISSUE TITLE
React UI: Consider re-adding metric name selector

### ISSUE THREAD

**Issue by juliusv** [prometheus/prometheus#6155]
The [new React UI](https://github.com/prometheus/prometheus/pull/5694) auto-completes metric names in the expression input field just like the old UI did, but it doesn't have a metric name selector dropdown so far. I don't want to clutter the new UI unnecessarily, so I want to be careful about reintroducing this. We should consider if an explicit dropdown will still be needed, how it can be made less obtrusive, or whether (future) better in-expression autocompletion can render this feature obsolete.

**Comment by slrtbtfs** [comment]
There exists the plan to let the expression input field use the upcoming PromQL language server for things like error messages and completion. This would likely mean a complete rewrite of the input field anyway.

As an alternative to the drop down menu It might be a good idea to instead offer completions, as soon as the user clicks on the input field to focus it or starts typing.

**Comment by Nexucis** [comment]
I think it won't be usefull once #6160 is done. 
Looking about the first result in codemirror, I don't see in which use case it will be needed.
But maybe I miss something

**Comment by Nexucis** [comment]
Should fixed as well the issue #5421

**Comment by juliusv** [comment]
This issue has been fixed a while ago by adding a new metric name selector modal dialog.
