### ISSUE TITLE
React UI: Re-add query stats information

### ISSUE THREAD

**Issue by juliusv** [prometheus/prometheus#6156]
The [new React UI](https://github.com/prometheus/prometheus/pull/5694) does not yet show query stats (execution time, resolution, and number of result time series) yet. It would be good to re-add this feature somehow, but care should be taken to not clutter the new UI unnecessarily. Maybe we can find a way to only display it on request (like collapsing it first or similar).

**Comment by CSTDev** [comment]
I'll take this on if no one else is...

**Comment by CSTDev** [comment]
Initial thoughts, uses a reactstrap collapse. 
Have just thought actually that having it there will be quite jarring as it moves everything below it down and up as it's expanded/collapsed. Will re-think.

![query-stats-1](https://user-images.githubusercontent.com/3914110/67109706-07050200-f1c9-11e9-98ee-f67631f371bc.PNG)
![query-stats-1-expanded](https://user-images.githubusercontent.com/3914110/67109708-079d9880-f1c9-11e9-9653-87936bf56a5b.PNG)

**Comment by juliusv** [comment]
Yeah, another inspiration could be Grafana's explore mode. See this screenshot, where some stats appear very unobtrusively at the far right of the expression box:

![](https://grafana.com/docs/img/docs/v60/explore_prometheus.png)

That breaks down at a certain amount of stats of course, and one would have to take care that it doesn't interfere with long expression lines.

Not saying it should be like this, but it's one more idea of a possible direction.

**Comment by juliusv** [comment]
@CSTDev Here's two more mockup variants that I find relatively unobtrusive, making use of the unused space of the Graph/Table tabpane on the right:

![variant2](https://user-images.githubusercontent.com/538008/67158315-fd011180-f336-11e9-82e8-bcb7994dce11.png)

I hacked this by putting this div into the HTML:

```html
<div style="
    position: absolute;
    right: 18px;
    top: 43px;
    font-size: 9px;
    color: #999;
">Query time: 234ms<br>Time series: 1023<br>Resolution: 13s</div>
```

And:

![variant1](https://user-images.githubusercontent.com/538008/67158323-0ee2b480-f337-11e9-9875-f1dcd023851a.png)

...using:

```html
<div style="
    position: absolute;
    right: 16px;
    top: 42px;
    font-size: 9px;
    color: #999;
">Query time: 234ms - Time series: 1023 - Resolution: 13s</div>
```

What do you think? It always shows the information, but still doesn't seem too clutter-y IMO. But happy for other options too :)

**Comment by CSTDev** [comment]
@juliusv Not a big fan of having it in the box like Grafana, mainly for the problems you mention. I quite like the second example you gave. Will give that a go and see. Thanks 😄 

Do we know if people use these stats a lot? That was my only reason behind hiding them if people aren't all that interested, but I don't know.

**Comment by juliusv** [comment]
@CSTDev I think people only look at these stats occasionally, but they're at times useful enough that we should at least have an easy way of showing them. And then the question becomes: is it not better to just always display them unobtrusively (like in my examples) rather than introducing a new interactive UI element that the user has to understand and process.

So yeah, if you want to go ahead with the second example, I think that's a good enough option for now :)

**Comment by juliusv** [comment]
Done in https://github.com/prometheus/prometheus/pull/6190
