### ISSUE TITLE
React UI: Add query history to auto-complete dropdown

### ISSUE THREAD

**Issue by juliusv** [prometheus/prometheus#6157]
The [new React UI](https://github.com/prometheus/prometheus/pull/5694) does not yet support storing + searching in the user's query history yet, like the existing old Prometheus UI does.

This functionality should be added back.

**Comment by boyskila** [comment]
Can I take this one?

**Comment by juliusv** [comment]
@boyskila Sure, go ahead! I assume you're familiar with the existing functionality in the old UI?

That is, https://github.com/prometheus/prometheus/blob/7567376a2452376fcedb69ef90af1988dbfa9074/web/ui/static/js/graph/index.js#L1090-L1163 and related code.

**Comment by boyskila** [comment]
Yep, already check it. Thanks

**Comment by juliusv** [comment]
Implemented in https://github.com/prometheus/prometheus/pull/6193
