### ISSUE TITLE
Add function to convert string to float in template

### ISSUE THREAD

**Issue by pablonaranjo** [prometheus/prometheus#6158]
The humanize* functions in template only accept float64 as input. However some labels are string and is not possible to use them, so is needed some extra-function to convert string label to float and then apply the humanize function.

Example:

```
text:   "{{ strToFloat \"1435065584.128\" | humanizeTimestamp }}",
output: "2015-06-23 13:19:44.128 +0000 UTC",
```

**Comment by pablonaranjo** [comment]
Actually is not a value, the timestamp is part of the label `job_name` (I'm getting that from K8s). So I can't show or manipulate the `$labels.job_name` in Prometheus alert, to convert the timestamp in date. Maybe there is a better option, but to be honest I don't know, and I fixed it creating a new function in `template.go`. then I just do 
```
{{ strToFloat (reReplaceAll "\D+" "" $labels.job_name) | humanizeTimestamp }} 
```

Thank you for taking the time and answering me.

**Comment by gouthamve** [comment]
We went through this issue in our bug scrub and we don't think this should be a feature. Labels are strings, and shouldn't be used as/to-store numbers.

If you're looking for getting a timestamp out, try joining with `process_start_time_seconds` or join with kube-state-metrics / cAdvisor.
