### ISSUE TITLE
React UI: Ensure compliance with external URL and route prefix settings

### ISSUE THREAD

**Issue by juliusv** [prometheus/prometheus#6163]
We need to ensure that the [new React UI](https://github.com/prometheus/prometheus/pull/5694) works correctly with different values set for the `--web.external-url` and `--web.route-prefix` Prometheus command-line flags.

**Comment by juliusv** [comment]
To elaborate on the problem here: the entire React UI (using create-react-app) is built and bundled expecting a particular path to be served on, then the resulting bundle is compiled into the Prometheus Go binary. But Prometheus needs to be able to dynamically change the path that the React app is expecting to be served on.

E.g. if someone sets the `--web.route-prefix=/my/prefix` flag, then the React app (and all legacy assets/endpoints) should be served under `/my/prefix/new` instead of `/new`. I'm not sure how to dynamically inject the expected serving path into the finished + compiled-in React app bundle.

**Comment by juliusv** [comment]
One option: have Prometheus dynamically inject something like `<script>PATH_PREFIX = "/my/prefix";</script>` into the React bundle's cryptic `index.html` file and then refer to that global variable from the TypeScript files (needs a `declare var PATH_PREFIX: any;` to make TypeScript understand that this global variable exists).

**Comment by juliusv** [comment]
On this.

**Comment by roidelapluie** [comment]
@juliusv do you know if that is in 2.14.0?

**Comment by juliusv** [comment]
@roidelapluie Should be! But if you found a bug, let me know :)

**Comment by roidelapluie** [comment]
Yes that is simply not working

**Comment by roidelapluie** [comment]
It does work only when I do add a trailing slash. /new -> NOK -- /new/ -> OK

**Comment by juliusv** [comment]
Hmm, `http://localhost:9090/foo/bar/new` works totally fine for me (with `--web.external-url=http://localhost:9090/foo/bar`). Or did you also set `--web.route-prefix`?

**Comment by roidelapluie** [comment]
Yes we have both

**Comment by roidelapluie** [comment]
--web.external-url=https://XXXX/prometheus/XXXX2/ --web.route-prefix=/

**Comment by juliusv** [comment]
Yeah, can reproduce. I did:

```
./prometheus --web.external-url=http://localhost:9090/foo/bar --web.route-prefix=/
```

With an nginx config of:

```
http {
 server {
   listen 0.0.0.0:19090;
   location /foo/bar/ {
     proxy_pass http://localhost:9090/;
   }
 }
}
events {
}
```

Two separate issues, it seems:

- The "Try experimental React UI" button / "link" in the classic UI doesn't even include the path prefix and takes you to `/new` instead of `/foo/bar/new`. Ooops.
- `/foo/bar/new/` works, but `/foo/bar/new` redirects to `/new/` for some reason.

Will have to look into it, thanks!

**Comment by juliusv** [comment]
Ah, the link in the classic UI *does* do the right thing (linking to `/foo/bar/new`), but then it hits the second issue where it redirects to `/new`. So just one issue after all.

**Comment by juliusv** [comment]
So the issue is this option in the httprouter: https://godoc.org/github.com/julienschmidt/httprouter#Router.RedirectTrailingSlash

With `--web.route-prefix=/` the httprouter not only serves on `/` (which is what we want), but also makes this lack of a prefix visible to the browser in terms of a redirect that is lacking the path prefix. Now I'm not sure I'd dare to turn off that option completely (might break things), but I could add an explicit redirect for `<route-prefix>/new` -> `<route-prefix>/new/` so that the httprouter doesn't take this over:

```golang
	router.Get("/new", func(w http.ResponseWriter, r *http.Request) {
		http.Redirect(w, r, path.Join(o.ExternalURL.Path, "/new/"), http.StatusFound)
	})
```
