### ISSUE TITLE
React UI: Convert remainder of Prometheus web UI to React

### ISSUE THREAD

**Issue by juliusv** [prometheus/prometheus#6164]
The [new React UI](https://github.com/prometheus/prometheus/pull/5694) only implements the graphing/querying interface so far. It is based on [create-react-app](https://github.com/facebook/create-react-app), which only supports the full page being a React app (vs. React just being part of the page). At least if we decide to stay with vanilla create-react-app, we'll need to convert the rest of the Prometheus UI to be React-based as well.

For some of the information on the current UI (like `/rules`), we don't have fitting APIs yet to fetch (and then render) the required information. We need to decide:

- Whether to really go single-page app or move away from create-react-app
- If yes: Whether to create / modify existing APIs to get the required information, or what other possibilities exist

**Comment by boyskila** [comment]
How about to set an environment variable and if is React to send JSON response, otherwise to render the template
![image](https://user-images.githubusercontent.com/10514821/67384076-25884600-f599-11e9-9495-bbac4da919db.png)

**Comment by brian-brazil** [comment]
I thought we'd added all the APIs by now. Which are missing?

**Comment by juliusv** [comment]
At a glance, I see a couple of things missing:

- `/rules` page - `/api/v1/status/rules` API endpoint
  - missing last evaluation time
  - missing last evaluation duration
- `/status` page with general build and runtime information
  - no equivalent API endpoint seems to exist at all, except for the Alertmanager info at `/api/v1/alertmanagers`
- `/targets` page - `/api/v1/targets` API endpoint
  - AFAICS the API endpoint doesn't include any grouping info about the scrape config a target came from
  - We are probably missing the extra bit here where the `/targets` page sometimes shows a different scrape URL than it links to (when the server detects a URL containing a localhost representation, the link gets changed to be to the external IP instead)
- `/service-discovery` page - `/api/v1/targets` API endpoint
  - API is missing scrape config grouping info
- `/alerts` - `/api/v1/alerts` API endpoint
  - API is missing association of active alerts to alerting rules

**Comment by simonpasquier** [comment]
I'm all for extending the API endpoints. This would also benefit other web apps that want to integrate with Prometheus.

**Comment by juliusv** [comment]
@simonpasquier Yeah, me too. I will miss immediately-there & greppable HTML pages somewhat, but oh well (one can still grep / jq the API endpoints)...

**Comment by simonpasquier** [comment]
I won't miss the Go templates :stuck_out_tongue:

**Comment by juliusv** [comment]
@boyskila
> How about to set an environment variable and if is React to send JSON response, otherwise to render the template

To keep things simple, we'd probably just want to remove the server-side generated Go templates completely and just do everything using APIs and React... I guess if we had a Node backend, we could do SSR of the pages, but not with Go...

**Comment by boyskila** [comment]
@juliusv  If no one has started working on this though, I can give it a try.

**Comment by juliusv** [comment]
@boyskila Sounds good. It probably makes sense to just replicate the old UI bit by bit in the new UI (with navbar and all), and then at some point in the future we can just replace the old UI with it.

I guess this'll entail adding React Router functionality?

**Comment by hooten** [comment]
I'd be happy to help with a page or two on this if you'd like @boyskila. Let me know.

**Comment by boyskila** [comment]
@hooten I think only /graph and /config pages are "in progress" so far and I'm planned to take /status if you don't mind and if no one has started it yet of course, so all others are waiting :)
@juliusv

**Comment by juliusv** [comment]
@hooten As an example, here's the Config page PR: https://github.com/prometheus/prometheus/pull/6236

Keep in mind that I'm new to React / frontend / TypeScript, so not everything you see will be best practice, but I did my best :) But hopefully we can converge on a common way of how the code looks for these components.

**Comment by hooten** [comment]
Okay, great, i'll work on `/targets` @juliusv @boyskila

**Comment by csmarchbanks** [comment]
I've been wanting to refresh my very outdated react knowledge, so I will claim the `/flags` page.

**Comment by juliusv** [comment]
@hooten How far did you get on `/targets` so far? Forgot that you had claimed it here a week ago, I started on it, but not very far yet. In case you didn't get to it much yet, is it ok if I take it?

**Comment by hooten** [comment]
Hey @juliusv, I'm almost done with `targets`. I should have a PR out soon. I'd really like to finish if that's okay with you

**Comment by juliusv** [comment]
@hooten Sure, sounds good! What did you end up doing on the Go API side? Just chatting on #prometheus-dev one idea was to add options to group by target pool and filter by active/dropped on `/api/v1/targets`.

**Comment by juliusv** [comment]
@hooten E.g. `http://localhost:9090/api/v1/targets?group_by_pool=true&state=active` with an output like:

```json
{
  "status": "success",
  "data": [
    {
      "poolName": "blackbox",
      "activeTargets": [
        {
          "discoveredLabels": {
          "__address__": "http://example.com:8080",
          "__metrics_path__": "/probe",
          "__param_module": "http_2xx",
          "__scheme__": "http",
          "job": "blackbox"
        },
          "labels": {
          "instance": "http://example.com:8080",
          "job": "blackbox"
        },
          "scrapeUrl": "http://127.0.0.1:9115/probe?module=http_2xx&target=http%3A%2F%2Fexample.com%3A8080",
          "lastError": "Get http://127.0.0.1:9115/probe?module=http_2xx&target=http%3A%2F%2Fexample.com%3A8080: dial tcp 127.0.0.1:9115: connect: connection refused",
          "lastScrape": "2019-11-04T15:23:06.936858054+01:00",
          "scrapeDurationSeconds": 0.00024551,
          "health": "down"
        },
...
```

**Comment by hooten** [comment]
@juliusv That's a great idea! So far, I've only done the minimal amount of change to make the page work by adding `scrapeJob` and `lastScrapeDuration` to each of the `activeTargets` elements. My plan was to bring up more impactful API changes during the PR review.

I think there definitely needs to be some way of limiting the API response. Something like paging or field limiting or both could be good. I like the idea of limiting by `state` of `active` or `dropped` but I think the API options need to have more powerful limiting capabilities, like `api/v1/targets?fields=labels,scrapeUrl,lastError` etc.

Judging from the testing I've done, the `discoveredLabels` field is the biggest issue affecting page rendering time. When I hit `/api/v1/targets` on a prometheus monitoring a decent-sized production kubernetes cluster, the response payload was 20.4MB and took over 10 seconds to return. Kubernetes offers up a lot of labels during service discovery. Furthermore, `discoveredLabels` is only something that actually gets rendered in the "Before relabeling" tooltip. It could be interesting only to fetch that when the tooltip is triggered (e.g., `/api/v1/targets?scrapeUrl=foo&fields=discoveredLabels`).

I'm happy to try some of these things out, but I will defer to API experts on what is the best choice. Regardless, something like this will need to be done to get the `/targets` page to a performant render.

Let me know what you think or if I should ping anyone else. Thanks!

**Comment by csmarchbanks** [comment]
Hmmm... It feels unnatural to me to have a query parameter change the data structure being returned by an endpoint. To me that feels like it should just be a different endpoint if desired. I think a filter like `state` is definitely a good idea though.

In the future, I think it could be worth iterating on the design of the targets page and the corresponding api endpoints generally. For example, it could really help performance of large instances to have each group collapsed by default and an api like:
```
/api/v1/target_groups
/api/v1/target_group/:group_name
```
Where `target_groups` only pulls down a bit of metadata (counts, number up/down, etc...). And `/target_group/:group_name` isn't called until a group is expanded. This would help both render time and the amount of data being pulled back at any time.

**Comment by juliusv** [comment]
@csmarchbanks Yeah, having different formats on the same endpoint feels weird to me as well, I'm just not sure whether it feels weirder than having two target endpoints, both behaving slightly differently. Honestly I don't have a preference, both are weird :)

Pulling only some info initially is definitely a possibility, though we have to weigh it against Ctrl-F-ability (on 95% of servers I expect the performance to not be a problem). In any case I think that'd be better to discuss for a later iteration (as I think is your intention).

**Comment by juliusv** [comment]
@hooten Sorry, I saw Chris's reply but not yours above it. Let's continue the targets-page-specific debate on this issue, which I just filed: https://github.com/prometheus/prometheus/issues/6269

**Comment by juliusv** [comment]
Getting back to status pages in general: I'm calling dibs on the `/rules` page!

**Comment by sharadgaur** [comment]
@juliusv , @cmluciano and @boyskila  If it's not already taken I would like to work on `/status` page.

**Comment by juliusv** [comment]
@sharadgaur That's already done. What's still up for grabs (but bit more complicated) are the `/alerts` and `/service-discovery` pages. Maybe the latter one would be good since it is similar to `/targets` and I see you are at Splunk with @hooten, who was doing `/targets`?

**Comment by sharadgaur** [comment]
@hooten is doing `/targets`. I will take `/alerts`

**Comment by juliusv** [comment]
@sharadgaur Yeah, that's why I meant `/service-discovery` could make sense for you because it's similar. For `/alerts` one challenge will be again to see what server-side API changes we need (`/api/v1/alerts` and `/api/v1/rules` will be what you will want to look at - the latter actually has recording *and* alerting rules, but it also has active alerts for the alerting rules, which you'll need).

**Comment by csmarchbanks** [comment]
The `/status` page now needs the cardinality stats added to it as well. Here is a checklist:

- [ ] `/rules` (claimed by juliusv)
- [ ] `/targets` (claimed by hooten)
- [ ] `/status` just cardinality stats needed
- [ ] `/service-discovery`
- [ ] `/alerts`

@juliusv please feel free to edit the checklist if I missed anything/it is incorrect.

**Comment by sharadgaur** [comment]
Cool, I will take the `/status` page.  
Thank you @juliusv and @csmarchbanks.

**Comment by sharadgaur** [comment]
@juliusv created a new page `/tsdb-status` as per your suggestion.  Here is the WIP [#6281](https://github.com/prometheus/prometheus/pull/6281)

**Comment by juliusv** [comment]
Closing this meta issue in favor of more specific ones:

- /rules page: https://github.com/prometheus/prometheus/issues/6385
- /alerts page: https://github.com/prometheus/prometheus/issues/6387
- /service-discovery page: https://github.com/prometheus/prometheus/issues/6386

@hooten @boyskila @sharadgaur @csmarchbanks - in case any of you would like to build more pages :)
