### ISSUE TITLE
Be able to configure different retention periods, probably based on metric name  or some other filter

### ISSUE THREAD

**Issue by nmayakuntla** [prometheus/prometheus#6168]
We have a system where different metrics are critical for different period of time.

There are really some metrics which have very high cardinality and do not want to store such metric data for the same period as other metrics. 

Is it possible or should we introduce different retention periods instead of having 1 common configuration for entire data set.

This would really help a lot if we can configure say some data retained for 2 days where as other data could be retained for 7 or 15 days.

As this feature is lacking, we had to introduce yet another system to send data with high cardinality.

**Comment by bwplotka** [comment]
Dup of https://github.com/prometheus/prometheus/issues/1381
