### ISSUE TITLE
Allow filtering label values API with matchers

### ISSUE THREAD

**Issue by brancz** [prometheus/prometheus#6178]
## Proposal

I would like to propose allowing our label values API to be filter-able by matchers, just like we [already do with the series API](https://prometheus.io/docs/prometheus/latest/querying/api/#finding-series-by-label-matchers).

**Use case. Why is this important?**

In particular we have two use cases: 

* Autocompletion: a language server implementation (that we are actively working on) can perform requests against a live system for advanced auto-complete, this could help us create a really nice auto complete for label values, as we can cut down the possible values using the already provided selectors.
* Cutting down on cognitive overload: we have a bunch of rather large Prometheus servers that are shared by teams and the mix of concerns is causing even just metric autocompletion to be kind of a nightmare, so the ability to isolate this for teams would allow us to provide a way better experience to users.

Beyond that, it would be great if our APIs were consistent in what they offer so a third point :slightly_smiling_face: .

I brought this up on IRC and multiple people seemed to be for this idea so I felt it was worth opening an issue on.

**Comment by krasi-georgiev** [comment]
+1 this should also help for other Thanos use cases

**Comment by brancz** [comment]
This doesn’t have anything to do with Thanos per se, but whatever we end up doing here Thanos should do the same for compatibility with the Prometheus API.

**Comment by krasi-georgiev** [comment]
I think for good performance should also pass a time range.

For example in the case of auto completion when you make an instant query you are interested in labels only from the last scrape and for a range query only for the time that this range query covers.

Otherwise getting label names/values for the entire DB involves reading all index files of all current blocks including the head block. 

Or a different approach would be using some cache but again for auto completion it might make more sense to show only relevant label names/values based on the query that the user would want to run.

**Comment by brancz** [comment]
Yeah the series API allows this as well. I think that also makes sense here.

**Comment by valyala** [comment]
FYI, VictoriaMetrics supports passing `match[]`, `start` and `end` args to `/api/v1/label/.../values` since `v1.24.0` - see [the corresponding commit](https://github.com/VictoriaMetrics/VictoriaMetrics/commit/99e048c9dfae9a551bafd96855472449f8ea5c3f).
For instance, the following query would return only metric names for `{job="node_exporter"}`:
```
http://localhost:8428/api/v1/label/__name__/values -d 'match[]={job="node_exporter"}'
```

**Comment by krasi-georgiev** [comment]
@valyala any chance to contribute the same to Prometheus?

**Comment by valyala** [comment]
I think this feature can be implemented by somebody more familiar with Prometheus source code.
At high level the request to `/api/v1/label/.../values` is re-routed to `/api/v1/series` with the corresponding `match[]`, `start` and `end` args and then all the values for the selected label are collected from the response to `/api/v1/series`.

**Comment by krasi-georgiev** [comment]
In that case I would second @juliusv's [comment](https://github.com/prometheus/prometheus/issues/5706#issuecomment-564516681) that you should use different channels for such self promoting posts.

**Comment by hagen1778** [comment]
@krasi-georgiev How is this self promotion? The proposal was filed on Oct 18 and @valyala implemented this on Aug 4. His comment is just an example of how it could be implemented in Prometheus itself. Thanos was mentioned in the second comment to this proposal - why this is not treated as promotion?

**Comment by juliusv** [comment]
@hagen1778 My comment at https://github.com/prometheus/prometheus/issues/5706#issuecomment-564516681 goes into this a bit more. It can indeed be helpful to cross-link to other products/projects at times, and I don't see this individual comment as a big problem - but it fits into an overall pattern that is less ok (see details in my linked comment).

**Comment by valyala** [comment]
I think github issues isn't good place for non-technical stuff. Let's continue the discussion at https://news.ycombinator.com/item?id=21772791 .

**Comment by kdanW** [comment]
Hi, I saw this project is available under community bridge mentorship. I would like to work on this if available @krasi-georgiev

**Comment by brian-brazil** [comment]
I think Krasi is on holiday until the new year, but I'm not aware of anyone else working on this.

**Comment by bwplotka** [comment]
For the mentorship, the official process for apply is described here: https://docs.linuxfoundation.org/display/DOCS/Mentees

**Comment by krasi-georgiev** [comment]
@boyskila has the intention to apply and work on this.

**Comment by boyskila** [comment]
Yes, thanks @krasi-georgiev , I already register myself on the platform but I couldn't find where to apply for the project.

**Comment by kdanW** [comment]
yes. I also applied through the platform for Prometheus project. But there is no option to request to work on this

**Comment by bwplotka** [comment]
Nice. Let's focus on this issue for matcher selecting. Time selecting was proposed here: https://github.com/prometheus/prometheus/issues/6865

**Comment by krasi-georgiev** [comment]
I don't mind to have separate issues for matchers and time, but if the implementation doesn't make the PR too big than I would say lets keep them in a single PR.

**Comment by bwplotka** [comment]
I kind of disagree. With implementation, you just forwarding to /series API
(: So not sure if there is really point in label values with matchers if we
have series endpoint. We could even extend series endpoint to return only
certain label name ;p

**Comment by krasi-georgiev** [comment]
after a short chat on IRC we have agreed:

 - continue with the implementations for matchers for the /labels api. Although the internal implementation is similiar they return different object.
 - have one PR for matchers and one more PR for time filter. The internal implementation for time filter is much faster when not using matchers.

**Comment by bwplotka** [comment]
Good first issue as well I think, especially after @JessicaGreben work (:

**Comment by obfuscurity** [comment]
I would very much like to see this feature implemented. Although this is not necessarily a feature most of our users would need (especially since Grafana effectively provides this with their `label_values()` function), I've hit a wall with a specific project using Prometheus as the backend data store. Not being able to filter labels to specific hosts (or other attributes) means that I'm forced to reimplement this with full series queries and data munging in-app, a highly inefficient operation. :(

**Comment by eklockare** [comment]
@obfuscurity @bwplotka I've created a branch implementing the matchers part, heavily based on #6837. Quality might not be up to par, I did it as a exercise to get used to the codebase, is it ok to put up a PR?

**Comment by brian-brazil** [comment]
> This would be my first contribution so I don't want to waste anyones time

Don't put yourself down, feel free to send in an updated PR.

**Comment by eklockare** [comment]
@brian-brazil Great, I've created a new PR. Just wanted to make sure I follow proceedures :+1:

**Comment by yeya24** [comment]
As https://github.com/prometheus/prometheus/pull/8301 is merged, anything else we need to do to complete this issue?

**Comment by brian-brazil** [comment]
Nope, looks like it can be closed.
