### ISSUE TITLE
promtool rules test should report missing rule files

### ISSUE THREAD

**Issue by freznicek** [prometheus/prometheus#6182]
## Proposal
`promtool test rules ...` usability improvement to issue an error when some rule files are not found.

## Bug Report
**What did you do?**
1. I tested prometheus rule using promtool
1. I mistyped name of the rule fule specified under key `.rule_files` (alert.yml instead of alert.yaml)

**What did you expect to see?**
1. promtool warning or error that file[s] specified under key `.rule_files` does not exist

**What did you see instead? Under which circumstances?**
1. I spent some time digging into why is my alert not firing even when I confirmed in `.promql_expr_test` section it should fire
1. promtool was not showing any warnings/errors on missing files

**Environment**

* System information:
```
$ uname -srm
Linux 5.0.17-200.fc29.x86_64 x86_64
```

* Prometheus/promtool version:
```
$ promtool --version
promtool, version 2.12.0 (branch: HEAD, revision: 43acd0e2e93f9f70c49b2267efa0124f1e759e86)
  build user:       root@7a9dbdbe0cc7
  build date:       20190818-13:53:16
  go version:       go1.12.8
```
Identical with last released promtool version 2.13.0.

* Alertmanager version:
Not applicable

* Prometheus configuration file:
Not applicable

* Alertmanager configuration file:
Not applicable

* Logs (promtool):
```
$ ls ./alert*.yaml
./alert_test_corrected.yaml  ./alert_test_bad.yaml  ./alert.yaml

# valid alert rule file case
$ promtool test rules ./alert_test_corrected.yaml
Unit Testing:  ./alert_test_corrected.yaml
  SUCCESS

# invalid alert rule file case
$ promtool test rules ./alert_test_bad.yaml
Unit Testing:  ./alert_test_bad.yaml
  FAILED:
    alertname:LongTermInfoAlertBecameWarningAlert, time:72h2m0s, 
        exp:"[Labels:{alertname=\"LongTermInfoAlertBecameWarningAlert\", app=\"finan...]", 
        got:"[]"

$ diff -u ./alert_test_bad.yaml ./alert_test_corrected.yaml
--- ./alert_test_bad.yaml 2019-10-18 15:52:35.481107512 +0200
+++ ./alert_test_corrected.yaml   2019-10-18 10:17:32.537878293 +0200
@@ -1,6 +1,6 @@
 
 rule_files:
-    - alert.yml
+    - alert.yaml
 
 evaluation_interval: 1m
```

**Comment by simonpasquier** [comment]
There's https://github.com/prometheus/prometheus/pull/6075 for doing what you ask.
