### ISSUE TITLE
api/v1/targets is causing liveness probe failure

### ISSUE THREAD

**Issue by liycheng** [prometheus/prometheus#6186]
## Proposal
Running prometheus in a POD with 12 core and 75G memory, our kubernetes cluster have ~500 nodes.
In the job configuration, it has total around 4500 targets (node, pod...), up or down,
the problem is when I try to call API "api/v1/targets", it causes the prometheus hang, at least on the HTTP service port, and then liveness probe, /-/healthy, cannot go through so the POD got restarted, is this because the response of "api/v1/targets" is too huge? I can never really completely open http://hostnameapi/v1/targets in a browser, by "wget" the file downloads is ~342M.
by reading the document that, https://prometheus.io/docs/prometheus/latest/querying/api/#targets
It says: "Both the active and dropped targets are part of the response."
Ok, I guess this is something not good. 

Can the response of this call to be split into pages?
Or accept kind of "selector"?
## Bug Report
**What did you do?**
calling API "api/v1/targets"
**What did you expect to see?**
get a list of "target"
**What did you see instead? Under which circumstances?**
a huge response even caused the prometheus get restarted.
**Environment**
Running prometheus in a POD with 12 core and 75G memory, our kubernetes cluster have ~500 nodes.
d

* Prometheus version:
/etc/prometheus # /bin/prometheus --version
prometheus, version 2.6.1 (branch: HEAD, revision: b639fe140c1f71b2cbad3fc322b17efe60839e7e)
  build user:       root@4c0e286fe2b3
  build date:       20190115-19:12:04
  go version:       go1.11.4

**Comment by liycheng** [comment]
v1.7.1

**Comment by liycheng** [comment]
the prometheus version is:
/etc/prometheus # /bin/prometheus --version
prometheus, version 2.6.1 (branch: HEAD, revision: b639fe140c1f71b2cbad3fc322b17efe60839e7e)
  build user:       root@4c0e286fe2b3
  build date:       20190115-19:12:04
  go version:       go1.11.4

**Comment by brian-brazil** [comment]
Can you try the latest version?

**Comment by liycheng** [comment]
@brian-brazil 
good or bad, the latest version is able to survival through this, although still, none of my browsers can completely open the "api/v1/targets" URI, "wget" can download the file completely, the size is 1.4G, I assume the previous file was partial downloaded before the POD got restarted, so it was only 342M.
But the problem still exists, I don't have too much confidence to have my code to handle a 1.4G response from a single API call.
So, I still believe the particular API call  "api/v1/targets" requires to be split into pages or have some "filter" to narrow down the scope of return context.

**Comment by brian-brazil** [comment]
From a Prometheus standpoint, as long as it's not blocking the server isn't not a big problem.

**Comment by liycheng** [comment]
Is that possible to "dorp" the "droped" target from this call?

**Comment by brian-brazil** [comment]
No, that's important debugging information that we need to return.

**Comment by liycheng** [comment]
@brian-brazil do you mind direct me to the code in the project which handles this API call?

**Comment by liycheng** [comment]
all right, I found the code, and me dig a while and see what I can do.

**Comment by csmarchbanks** [comment]
https://github.com/prometheus/prometheus/pull/6276 will be adding an option to exclude dropped targets from the response by usng a query parameter like `/api/v1/targets?state=active`.

**Comment by gouthamve** [comment]
We went through this issue in our bug scrub and we have fixed some issues around locking in the targets path. Could you upgrade to the latest issue and see if its fixed?

If it's not, please re-open the issue and let us know?
