### ISSUE TITLE
When running on linux system Prometheus fails to resolve windows host names

### ISSUE THREAD

**Issue by zarboz** [prometheus/prometheus#6189]
ping HQ2-Webserver
PING HQ2-Webserver (10.10.10.12) 56(84) bytes of data.
64 bytes from 10.10.10.12 (10.10.10.12): icmp_seq=1 ttl=128 time=0.326 ms
^C
--- HQ2-Webserver ping statistics --- 
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.326/0.326/0.326/0.000 ms

but in prometheus target page it shows target as offline  

Get http://HQ2-WEBSERVER:9182/metrics: dial tcp: lookup HQ2-WEBSERVER on 127.0.0.53:53: server misbehaving

its odd to me that lookup is happening on localhost 127.0.0.53>>???

**Comment by brian-brazil** [comment]
Are you sure these names are in DNS, and not say netbios?

**Comment by gouthamve** [comment]
We went through this issue in our bug scrub and this looks like a question. We just use DNS to lookup targets, and please verify that the DNS entries are correct.
