### ISSUE TITLE
Make `remote.Client.Store` return the `httpResp` as well

### ISSUE THREAD

**Issue by anandsinghkunwar** [prometheus/prometheus#6202]
## Proposal
Make `github.com/prometheus/prometheus/storage/remote/client.go`: `Client.Store` return the `httpResp` as well with the error. To do this in a non breaking way, another function `StoreV2`(name is debatable of course) can be created as well. 

**Use case. Why is this important?**
This is important when someone is using the `remote.Client` and wants to know the exact response code to handle that in a way. For instance, I am using `remote.Client` for writing metrics to a M3DB remote backend and I get a `400 Bad Request` response code in the cases where the metrics are stale and can't be part of the latest block. I would have liked to handle this in a certain way, which isn't possible right now.

**Comment by brian-brazil** [comment]
This is internal code of Prometheus, and an error is an error from Prometheus's standpoint. This sounds like something to take up with M3DB as your use case sounds unusual. @robskillington

**Comment by anandsinghkunwar** [comment]
No, actually it is not related to M3DB. So, I am trying to leverage kafka as a buffer in between prometheus and m3db. So the writing to kafka part is done after writing a prometheus remote endpoint and hooking prometheus with it. The reading from kafka and pushing to M3DB involves the use of this `remote.go` `Client`, which required custom handling of response codes. @brian-brazil

**Comment by brian-brazil** [comment]
We generally don't add code to support things outside of the code base. Given how remote write works, there's no need to add kafka to the mix.

**Comment by gouthamve** [comment]
We went through this issue in our bug scrub and we've decided to close this as this is internal code.

Having said that, could you give us specific examples of the use-case? Further, we're now using the WAL for buffering metrics, hence does the same job as Kafka.

**Comment by anandsinghkunwar** [comment]
@gouthamve Although I don't need it anymore and have just copied that function with changes in my codebase, one easy problem I see with WAL "replacing" kafka I can see is that WAL storage is limited by the storage you allocate in that particular prometheus instance, kafka on the other hand, being horizontally expandable can overcome that bottleneck. Another feature is replay-ability which maybe a bit difficult to achieve in the prometheus ecosystem. Our usecase involved writing ETL pipelines on prometheus data where the kafka component really shined.
