### ISSUE TITLE
prometheus metrics data was partly lost

### ISSUE THREAD

**Issue by zhangxingdeppon** [prometheus/prometheus#6203]
## Proposal
**Use case. Why is this important?**

*“Nice to have” is not a good use case. :)*

## Bug Report
**What did you do?**
Hi,buddies,I faced a problem about prometheus,when I  get the metric "istio_requests_total" data through prometheus  ,I found that the metric’s data sometimes can be lost over a period of time,
I use this  promQL to search the metric's data:
<pre><code>
istio_requests_total{reporter="source",destination_service=~"idcardocr-xl8meey0-serving.aipaas-modelserving.svc.cluster.local"}
</code></pre>
it will return many metric data,so I just paste the key part:
![image](https://user-images.githubusercontent.com/16789841/67348158-a2ee8f00-f576-11e9-95c2-2c893f1c6b8c.png)
In this picture ,you will find the exception datas in red box,there are two problems:
firstly,the istio_requests_total number 500 straight down to 1,I thinks the number should constantly increase, the number at 1571377638.89 (2019/10/17 16:41:48 ) must large than 500  at 1571301708.89 (2019/10/18 13:47:18),but not.

secondly, between  1571377638.89 (2019/10/17 16:41:48 ) and  1571377638.89 (2019/10/17 16:41:48 ),there is no metric data to capture,so the metrics data was partly lost.
it is important for me,can you give me some ideas?I'm pleasure to provide more details if need.thanks.
**What did you expect to see?**
I hope I can found the all data through prometheus,tks
**What did you see instead? Under which circumstances?**

**Environment**

* System information:

	insert output of `uname -srm` here
<pre><code>
[aipaas@d21012u04-62-93 ~]$ uname -srm
Linux 3.10.0-693.el7.x86_64 x86_64
</code></pre>
* Prometheus version:

	insert output of `prometheus --version` here
<pre><code>
/prometheus $ prometheus --version
prometheus, version 2.8.0 (branch: HEAD, revision: 59369491cfdfe8dcb325723d6d28a837887a07b9)
  build user:       root@4c4d5c29b71f
  build date:       20190312-07:46:58
  go version:       go1.11.5
</code></pre>

* Alertmanager version:

	insert output of `alertmanager --version` here (if relevant to the issue)

* Prometheus configuration file:
```
insert configuration here
```

* Alertmanager configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by zhangxingdeppon** [comment]
> It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

@brian-brazil okay,thanks.
