### ISSUE TITLE
Schedules for scrape configs and alerts

### ISSUE THREAD

**Issue by rigtorp** [prometheus/prometheus#6209]
## Proposal

I need to monitor connectivity to a service from my servers. During weekends the service is down, but the network connectivity should be up (checked using ping). During workdays the service is up and I can check connectivity by checking that number of UDP packets received is increasing. The times the service is up changes with daylight savings and holidays. I want to run the ping check on weekends only to verify that weekend network maintenance did not break anything. During service up hours I don't want to send pings since it could be considered unwarranted messaging and against financial regulations. 

I have several other systems where the exporter has regular downtime windows and/or the alert should only be in effect during certain periods.

This is easy to do with nagios. You can specify a schedule and tell it to run checks depending on the schedule. Alerts can also be set to only trigger based on a schedule. Zabbix has similar support.

I would like to define schedules in Prometheus, for example: Monday to Friday, 03:00 to 20:00, excluding US holidays. Then I could config one scraper to run against blackbox_exporter when this schedule is not in effect and another to always scrape node_exporter. Alerts would setup to trigger on increase(node_netstat_Udp_InDatagrams[5m]) < 100 when the schedule is in effect and on probe_success == 0 when the schedule is not in effect.

Currently the workaround is to create a custom exporter or using textfile exporter to generate a bunch of boolean variables that represent the different schedules I have. For scheduling scrapers I can create a proxy exporter that returns a empty result or forwards to the target depending on a schedule. But I think this functionality should be built into Prometheus.

**Comment by brian-brazil** [comment]
Scrapes in Prometheus are continuous, so it sounds like you'll need to build something yourself on top of the config file it you want to do otherwise.

**Comment by rigtorp** [comment]
Yes I have a mess of cronjobs, shell scripts, python scripts to get some of this functionality, but it's difficult to manage. There is a reason that nagios, zabbix, icinga, cabot etc supports this. I have 6 DCs in different timezones and applications on even more different timezones and calendars. Prometheus/Alertmanager can not filter alerts by time periods and route alerts by duty roster. There even isn't any timezone aware date and time functions in PromQL. It makes it really hard to use the alerting functionality.

**Comment by simonpasquier** [comment]
There's already https://github.com/prometheus/alertmanager/issues/876 regarding the ability to dispatch notifications based on time/date.

**Comment by rigtorp** [comment]
@simonpasquier That would also be great. But in my use case the alert is not even valid and should not be checked outside some time period. It would be great if there was a new config object `time_period` in prometheus and alertmanager that could define a time period (including holidays etc). Scraping, alerting and alert routing could then be controlled by these time period objects.

**Comment by rdjogo** [comment]
> @simonpasquier That would also be great. But in my use case the alert is not even valid and should not be checked outside some time period. It would be great if there was a new config object `time_period` in prometheus and alertmanager that could define a time period (including holidays etc). Scraping, alerting and alert routing could then be controlled by these time period objects.

Exactly, e.g. if you would like to calculate "downtime" over a longer period of time, you would most likely want to exclude non-operational hours from that calculation.

**Comment by gouthamve** [comment]
We went through this issue in our bug scrub and you should try to add the extra logic / custom-exported-series to the alert itself rather than stop the scrapes.

If you'd like the scrapes stopped for a time-period, could you use file-sd and update the targets list as necessary?
