### ISSUE TITLE
No datapoints found message in prometheus dashboard

### ISSUE THREAD

**Issue by Nithya2688** [prometheus/prometheus#6216]
Hi,
I want to montior docker performance, Hence installed cadvisor+prometheus in RHEL successfully. But when try to use expression with my docker, I am getting "no datapoints found" error. Since I am new to this please help me to resolve this.
Also I want to know whether i can install grafana to get better performance result in graph.
![image](https://user-images.githubusercontent.com/56965785/67488928-467e9300-f68e-11e9-824f-53b7dffd6c07.png)

## Proposal
**Use case. Why is this important?**

*“Nice to have” is not a good use case. :)*

## Bug Report
**What did you do?**

**What did you expect to see?**

**What did you see instead? Under which circumstances?**

**Environment**

* System information:

	insert output of `uname -srm` here

* Prometheus version:

	insert output of `prometheus --version` here

* Alertmanager version:

	insert output of `alertmanager --version` here (if relevant to the issue)

* Prometheus configuration file:
```
insert configuration here
```

* Alertmanager configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```

**Comment by simonpasquier** [comment]
Thanks for your report. It looks as if this is actually a question about usage and not development.

To make your question, and all replies, easier to find, we suggest you move this over to our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search. If you prefer more interactive help, join or our [IRC channel](https://webchat.freenode.net/?randomnick=1&channels=prometheus), #prometheus on irc.freenode.net. Please be aware that our IRC channel has no logs, is not searchable, and that people might not answer quickly if they are busy or asleep. If in doubt, you should choose the mailing list.

Once your questions have been answered, please add a short line pointing to relevant replies in case anyone stumbles here via a search engine in the future.
