### ISSUE TITLE
Prometheus is not compatible with the changes in K8s v1.16

### ISSUE THREAD

**Issue by avarf** [prometheus/prometheus#6220]
## Bug Report
**What did you do?**
I installed the stable/prometheus helm chart with some minor changes proposed at https://github.com/helm/charts/pull/17268 to make it compatible with Kubernetes v1.16

After installation, none of the Kubernetes grafana dashboards show correct values.  I am using 8769 (https://grafana.com/grafana/dashboards/8769) dashboard which provides many information on cpu, memory, network, etc. This dashboard is working properly on older k8s versions but on v1.16 it shows no results. I also randomly tried some other dashboards (8588, 6879, 10551) but they either just show the requested resource for each pod and not the live usage or showing nothing.

What these dashboards do is they send a promql query to prometheus and get the results. For example this is the promql query for cpu usage from 8769 dashboard:
```
sum (rate (container_cpu_usage_seconds_total{id!="/",namespace=~"$Namespace",pod_name=~"^$Deployment.*$"}[1m])) by (pod_name)
```

I don't know if I have to change the promql or the problem is somewhere else.

**What did you expect to see?**
Correct and live resource usage like how it works with older k8s versions.

**What did you see instead? Under which circumstances?**
I described above.

**Environment**

A 5 node k8s cluster running k8s v1.16

* Prometheus version:
Based on the helm chart that I am using:2.11.1

* Alertmanager version:
v0.18.0

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
