### ISSUE TITLE
Kubernetes SD metrics do not expose cluster information

### ISSUE THREAD

**Issue by JosephSalisbury** [prometheus/prometheus#6221]
## Proposal
We are currently using the metric `prometheus_sd_kubernetes_http_request_total` to alert if a Prometheus server cannot communicate with a Kubernetes cluster.

Some of our Prometheus servers monitor multiple Kubernetes clusters, but `prometheus_sd_kubernetes_http_request_total` is the same for all these jobs, meaning we can't determine _which_ job can't discover targets in the alert.

Having a label to distinguish which job is unable to communicate with Kubernetes would be grand.

**Comment by brian-brazil** [comment]
I'd suggest using `absent()` to handle this, as there's more ways than this that things can go awry.

**Comment by JosephSalisbury** [comment]
I don't think `absent` would work in our case.

For example, if you have one Prometheus server discovering targets from two Kubernetes clusters. If one of those clusters can't be reached, `prometheus_sd_kubernetes_http_request_total{status_code="<error>"}` will start to increase, but i don't think it's possible to determine which of the two clusters Prometheus can't discover targets from.

My thinking is if we have some label on that metric (or something more generic) that identifies the job/cluster, you can determine the failing cluster. That would help us with alerting and silences and such.

**Comment by brian-brazil** [comment]
What's there is good enough for alerting, however I'd try to alert on no targets coming from a cluster rather than one specific rpc call failing.

**Comment by JosephSalisbury** [comment]
Okay yeah, I get what you mean now - alert if we don't have any expected targets from a cluster. Cool!

Thanks for the help buddy, I'll close here, there's a way around.
