### ISSUE TITLE
API documentation

### ISSUE THREAD

**Issue by atombender** [prometheus/prometheus#623]
It seems the HTTP API for querying data (from, say, a custom dashboard or monitoring solution) is completely undocumented.

One can reverse-engineer it easily enough from the official web UI and from the code, but I'd like to know if there are plans to document it properly, and I'd also like to know how stable it is considered at this point.

**Comment by fabxc** [comment]
There should definitely be documentation on this.
Until there is, there are no guarantees but you can assume that breaking changes are avoided without a good reason. Check the change logs when upgrading, to be sure.

**Comment by atombender** [comment]
Thanks!

**Comment by fabxc** [comment]
prometheus/docs#135 documents the official API that will become available with v0.15.
