### ISSUE TITLE
master branch no  npm_licenses.tar.bz2 

### ISSUE THREAD

**Issue by k8svip** [prometheus/prometheus#6251]
Dockerfile use npm_licenses.tar.bz2
...
COPY npm_licenses.tar.bz2                   /npm_licenses.tar.bz2
...

but this file 'npm_licenses.tar.bz2 '  lose

**Comment by csmarchbanks** [comment]
You will have to run `make npm_licenses` to generate the npm_licenses.tar.bz2 file. It is also included as a dependency to the `make docker` command if building that way.

**Comment by simonpasquier** [comment]
Closing since Chris has answered already. The new build requirements and process are also documented in the [README](https://github.com/prometheus/prometheus#building-from-source) file.
