### ISSUE TITLE
prometheus not parse exporter metric unit field

### ISSUE THREAD

**Issue by liuliqiang** [prometheus/prometheus#6255]
## Bug Report
**What did you do?**

I have a exporter named `random-exporter` who return random_value for metrics, and these metrics has Unit fields:

```
... more content...
# HELP random_0 value_type:int, Just a random number.
# TYPE random_0 gauge
# UNIT random_0 seconds
random_0{i="0"} 0.15651925473279124
# HELP random_1 value_type:string, Just a random number.
# TYPE random_1 gauge
# UNIT random_1 seconds
random_1{i="0"} 0.09696951891448456
# HELP random_2 value_type:counter32, Just a random number.
# TYPE random_2 gauge
# UNIT random_2 seconds
random_2{i="0"} 0.30091186058528707
# HELP random_3 value_type:counter64, Just a random number.
# TYPE random_3 gauge
# UNIT random_3 seconds
random_3{i="0"} 0.5152126285020654
... more content...
```

And i try the API to get the scrape target meta with this URL: 

`GET http://{{host}}:9090/api/v1/targets/metadata?match_target={job="randome-exporter"}&metric=random_2` 

and get the following response:

```
{
  "status": "success",
  "data": [
    {
      "target": {
        "instance": "localhost:9800",
        "job": "randome-exporter"
      },
      "type": "gauge",
      "help": "value_type:counter32, Just a random number.",
      "unit": ""
    }
  ]
```

The `unit` field is empty.

**What did you expect to see?**

As i call the api: 

`GET http://{{host}}:9090/api/v1/targets/metadata?match_target={job="randome-exporter"}&metric=random_2` 

it should response with unit there like this:

```
{
  "status": "success",
  "data": [
    {
      "target": {
        "instance": "localhost:9800",
        "job": "randome-exporter"
      },
      "type": "gauge",
      "help": "value_type:counter32, Just a random number.",
      "unit": "seconds"
    }
  ]
```

**What did you see instead? Under which circumstances?**

* Prometheus version:

```
/usr/bin/prometheus --version
prometheus, version 2.13.1 (branch: HEAD, revision: 6f92ce56053866194ae5937012c1bec40f1dd1d9)
  build user:       root@88e419aa1676
  build date:       20191017-13:15:01
  go version:       go1.13.1
```

* Prometheus configuration file:

```
alerting:
  alertmanagers:
  - path_prefix: /prometheus
    static_configs:
    - targets:
      - 192.168.57.24:9903
scrape_configs:
- job_name: randome-exporter
  scrape_interval: 30s
  static_configs:
  - targets:
    - localhost:9800
```

**Comment by brian-brazil** [comment]
Are you exposing this as openmetrics format?

**Comment by timofey-barmin** [comment]
It looks like I have the same problem. It is not clear how to make prometheus return correct units in "GET /api/v1/targets/metadata" (I always see empty unit field).
I tried specifying unit in metric name - it didn't work (for example "mymetric_seconds"). Also tried specifying it as "# UNIT mymetric_seconds seconds", it didn't work either. 
I think I read all the prometheus docs and could not find the answer. Googling gave me this issue only.
@brian-brazil Could you please point to the right doc? or maybe just explain how it works? :)

**Comment by gouthamve** [comment]
We only set units in metrics only when using Openmetrics.io (which exists in the Python client). Could you let us know if you're using OM?

Further, this is all experimental and having an empty unit is okay.

**Comment by beorn7** [comment]
To make Prometheus parse your exposition as OpenMetrics, it has to be negotiated as the corresponding content-type (`application/openmetrics-text`, see https://github.com/prometheus/common/blob/master/expfmt/expfmt.go#L26 etc. for details).

**Comment by roidelapluie** [comment]
I tried to reproduce this with latest prometheus and latest client_python:

```
$ curl --header "Accept: application/openmetrics-text; version=0.0.1,text/plain" 127.0.0.1:8000 
# HELP request_processing_seconds Time spent processing request
# TYPE request_processing_seconds summary
# UNIT request_processing_seconds seconds
request_processing_seconds_count 6.0
request_processing_seconds_sum 2.624024077995273
request_processing_seconds_created 1.5904408944816756e+09
# HELP random_seconds example
# TYPE random_seconds gauge
# UNIT random_seconds seconds
random_seconds 0.0
# EOF
```


```
$ curl -s '127.0.0.1:9090/api/v1/targets/metadata?match_target={job="prometheus"}&metric=random_seconds' -g|jq
{
  "status": "success",
  "data": [
    {
      "target": {
        "instance": "localhost:8000",
        "job": "prometheus"
      },
      "type": "gauge",
      "help": "example",
      "unit": "seconds"
    }
  ]
}
$ curl -s -g '127.0.0.1:9090/api/v1/targets/metadata?match_target={job="prometheus"}&metric=request_processing_seconds'|jq
{
  "status": "success",
  "data": [
    {
      "target": {
        "instance": "localhost:8000",
        "job": "prometheus"
      },
      "type": "summary",
      "help": "Time spent processing request",
      "unit": "seconds"
    }
  ]
}

```

So, it works for me, for gauges and summaries. Could you try updating your prometheus and client_python versions? Thanks!

**Comment by roidelapluie** [comment]
Note: The original author did not specify that they exposed the metric in the OpenMetrics format.

Prometheus text format 0.0.4 has no support for units.
