### ISSUE TITLE
DB corrupt after one day?

### ISSUE THREAD

**Issue by kwaazaar** [prometheus/prometheus#6257]
## Bug Report
**What did you do?**
I installed Prometheus using the helm chart yesterday. Everything worked fine. My deployment pipeline just tried to update the installation, using Helm. The server-pod cannot start up now.

**What did you expect to see?**
Normal startup

**What did you see instead? Under which circumstances?**
level=error ts=2019-10-31T13:41:31.933Z caller=main.go:736 err="opening storage failed: block dir: \"/data/01DRF0M1N0XDVV2CM58F264MT4\": open /data/01DRF0M1N0XDVV2CM58F264MT4/meta.json: no such file or directory"

**Environment**

* System information:

Running on Kubernetes on Azure (AKS) with a Azure File mounted data folder (sku: premiumLRS)

* Prometheus version:

2.13.1 (chart: 9.2.0)

* Prometheus configuration file:
Values-file for chart:
~~~
server:
  persistentVolume:
    storageClass: "aah-premium-lrs"
    size: 100Gi # 100Gi is minimale size voor premium LRS (anders HTTP 400 fout)
  ingress:
    ## If true, Prometheus server Ingress will be created
    ##
    enabled: true
    ## Prometheus server Ingress hostnames
    ## Must be provided if Ingress is enabled
    ##
    hosts:
      - prometheus.dev.aahg.ot
    ## Prometheus server Ingress TLS configuration
    ## Secrets must be manually created in the namespace
    ##
    tls:
      - secretName: prometheus-ssl
        hosts:
          - prometheus.dev.aahg.ot
~~~

* Logs:
~~~
level=info ts=2019-10-31T13:41:31.765Z caller=main.go:332 msg="Starting Prometheus" version="(version=2.13.1, branch=HEAD, revision=6f92ce56053866194ae5937012c1bec40f1dd1d9)"
level=info ts=2019-10-31T13:41:31.766Z caller=main.go:333 build_context="(go=go1.13.1, user=root@88e419aa1676, date=20191017-13:15:01)"
level=info ts=2019-10-31T13:41:31.766Z caller=main.go:334 host_details="(Linux 4.15.0-1061-azure #66-Ubuntu SMP Thu Oct 3 02:00:50 UTC 2019 x86_64 prometheus-server-6576dcd65c-vls7f (none))"
level=info ts=2019-10-31T13:41:31.766Z caller=main.go:335 fd_limits="(soft=1048576, hard=1048576)"
level=info ts=2019-10-31T13:41:31.766Z caller=main.go:336 vm_limits="(soft=unlimited, hard=unlimited)"
level=info ts=2019-10-31T13:41:31.853Z caller=main.go:657 msg="Starting TSDB ..."
level=info ts=2019-10-31T13:41:31.853Z caller=web.go:450 component=web msg="Start listening for connections" address=0.0.0.0:9090
level=info ts=2019-10-31T13:41:31.899Z caller=repair.go:59 component=tsdb msg="found healthy block" mint=1572440780421 maxt=1572444000000 ulid=01DREPNYVK0SX4GFD7MZ19745K
level=info ts=2019-10-31T13:41:31.929Z caller=repair.go:59 component=tsdb msg="found healthy block" mint=1572444000000 maxt=1572451200000 ulid=01DRESRAD7RPABG2KXNCEDAJ8G
level=info ts=2019-10-31T13:41:31.932Z caller=main.go:526 msg="Stopping scrape discovery manager..."
level=info ts=2019-10-31T13:41:31.932Z caller=main.go:540 msg="Stopping notify discovery manager..."
level=info ts=2019-10-31T13:41:31.932Z caller=main.go:562 msg="Stopping scrape manager..."
level=info ts=2019-10-31T13:41:31.932Z caller=main.go:536 msg="Notify discovery manager stopped"
level=info ts=2019-10-31T13:41:31.932Z caller=main.go:522 msg="Scrape discovery manager stopped"
level=info ts=2019-10-31T13:41:31.932Z caller=main.go:556 msg="Scrape manager stopped"
level=info ts=2019-10-31T13:41:31.932Z caller=manager.go:814 component="rule manager" msg="Stopping rule manager..."
level=info ts=2019-10-31T13:41:31.932Z caller=manager.go:820 component="rule manager" msg="Rule manager stopped"
level=info ts=2019-10-31T13:41:31.932Z caller=notifier.go:602 component=notifier msg="Stopping notification manager..."
level=info ts=2019-10-31T13:41:31.932Z caller=main.go:727 msg="Notifier manager stopped"
level=error ts=2019-10-31T13:41:31.933Z caller=main.go:736 err="opening storage failed: block dir: \"/data/01DRF0M1N0XDVV2CM58F264MT4\": open /data/01DRF0M1N0XDVV2CM58F264MT4/meta.json: no such file or directory"
~~~

**Comment by simonpasquier** [comment]
> Running on Kubernetes on Azure (AKS) with a Azure File mounted data folder (sku: premiumLRS)

I'm not familiar with Azure Files but I suspect that it isn't fully POSIX compliant hence the storage errors.

See https://prometheus.io/docs/prometheus/latest/storage/#operational-aspects

> If your local storage becomes corrupted for whatever reason, your best bet is to shut down Prometheus and remove the entire storage directory. Non POSIX compliant filesystems are not supported by Prometheus's local storage, corruptions may happen, without possibility to recover. NFS is only potentially POSIX, most implementations are not. You can try removing individual block directories to resolve the problem, this means losing a time window of around two hours worth of data per block directory. Again, Prometheus's local storage is not meant as durable long-term storage.

**Comment by kwaazaar** [comment]
Although I can't find an official statement on POSIX compliancy, I do think that's the problem here. Today the filesystem is corrupt again (day 4), so using Azure Blob storage for my containers in AKS seems like a bad idea when POSIX compliancy is required. This article mentions the limitations: https://docs.microsoft.com/nl-nl/azure/storage/blobs/storage-how-to-mount-container-linux
