### ISSUE TITLE
React UI: Bring back interactive legend

### ISSUE THREAD

**Issue by juliusv** [prometheus/prometheus#6268]
The graph legend in the classic UI has three modes of interaction, see e.g. http://demo.robustperception.io:9090/graph?g0.range_input=1h&g0.expr=rate(node_cpu_seconds_total%5B5m%5D)&g0.tab=0

- Hovering over legend items highlights the hovered series in the graph.
- Clicking on the series name in the legend toggles showing only that series in the graph.
- Clicking on the checkmark of a legend item turns off that series in the graph.

It would be good to bring back some, if not all, of these features in the new React UI.

**Comment by boyskila** [comment]
Anyone working on this? I would like to give it a try, just to finish with my current PR :)

**Comment by juliusv** [comment]
@boyskila Feel free!

**Comment by roidelapluie** [comment]
@juliusv Can we reopen this?

We miss the ability to select multiple lines in legend (and the unselect one of them..)

**Comment by juliusv** [comment]
@roidelapluie Yeah, I ended up telling @boyskila to omit the multi-deselect for now and see if someone really wants it :) If we do want to reintroduce it, I wonder if we can do it better somehow, since the old UI only allowed you to explicitly *de*select series that you didn't want to see, rather than the other way around. I want to avoid adding extra UI elements as much as possible...

Do you have an opinion on how this should best work?

**Comment by roidelapluie** [comment]
I do not agree with you. The old UI allow both.

- Clicking on the labels would select the one you want, then click the checkboxes to add others.
- Deselect checkbox to remove one.

Comparing some metrics is really useful, I rarely see a case where I would just see one.

**Comment by roidelapluie** [comment]
Without addind new UI elements, we could work with SHIFT and CTRL

CTRL+click = exclude
SHIFT+click = include

**Comment by boyskila** [comment]
> Comparing some metrics is really useful, I rarely see a case where I would just see one.

Yes, it's gonna be useful for the user to have the possibility to select 2 or more series.
About the series toggle, I guess just CTRL + click will be enough.

**Comment by juliusv** [comment]
> The old UI allows both.

Today I learned :rofl: The fact that I wrote the old UI and didn't know this (because it was a built-in feature of the old graphing library) is a good sign that this feature wasn't very discoverable from a UX perspective.

I generally like the idea of modifier keys to switch between behaviors. But then we have even worse discoverability features unless we write it out as instructions somewhere. Hm. I'll think about the UI bits a bit more...

And yes, totally agreed that comparing a specific subset of metrics is useful.

**Comment by roidelapluie** [comment]
Well grafana has modifiers keys too for its legend (shift and Ctrl). So it will feel natural for many users.

**Comment by juliusv** [comment]
> Well grafana has modifiers keys too for its legend (shift and Ctrl). So it will feel natural for many users.

See, another thing I didn't know :P That's good, but I hope we can do better. Maybe a hover title with instructions, like below?

![legend](https://user-images.githubusercontent.com/538008/69501744-1d108b80-0f08-11ea-906a-4c6abae28e94.png)

Or light grey non-intrusive instructions under the legend:

![legend2](https://user-images.githubusercontent.com/538008/69501791-97411000-0f08-11ea-9dff-b2976d964b2f.png)

Also open for totally different ideas, but I think we should make these instructions self-learnable somehow.

**Comment by roidelapluie** [comment]
I double checked grafana. Shift and ctrl have the same effect:  they toggle an element. Click will select only that one.

**Comment by boyskila** [comment]
> Also open for totally different ideas, but I think we should make these instructions self-learnable somehow.

Wellcome popover with instructions on the first-page load, something like http://jsfiddle.net/johannesMt/t1d1t9pp/

**Comment by juliusv** [comment]
> Wellcome popover with instructions on the first-page load, something like http://jsfiddle.net/johannesMt/t1d1t9pp/

That's a good idea, but I think in the Prometheus context it doesn't fit so well:

- A user might visit 10 different Prometheus servers after each other, so you have to always click this away everywhere (I guess you'd save in local storage for each one that it's acknowledged).
- IMO it's not worth having an interactive / distractive popup for such a minor feature that is only seldomly used. I'd rather keep it local to where the feature is (hover tooltip, small instructions, or similar, maybe there are other options, but less intrusive is better).

**Comment by juliusv** [comment]
I propose the following: implement the feature like @roidelapluie described it for now, and decide on the instructions later (or implement one of the options, we can always improve it later). At least we shouldn't see the discoverability as a blocker either.

**Comment by roidelapluie** [comment]
So: click = select ; mod+click = toggle.

Adding the text in the bottom seems a good idea, provided more than one time serie is displayed.
![image](https://user-images.githubusercontent.com/291750/69502618-7a5d0a80-0f11-11ea-93de-6785ee7e2351.png)

**Comment by juliusv** [comment]
Sounds great to me!

**Comment by boyskila** [comment]
Meanwhile, I have made some improvements and resolve some small bugs [here](https://github.com/prometheus/prometheus/pull/6367)
