### ISSUE TITLE
React UI: Build targets page

### ISSUE THREAD

**Issue by juliusv** [prometheus/prometheus#6269]
This is a more specific issue filed for the discussion started on https://github.com/prometheus/prometheus/issues/6164#issuecomment-549375737.

Let's discuss targets-page specific things here.

**Comment by juliusv** [comment]
Continuing the discussion from the more general status pages issue here:

@hooten Yeah, that 20MB targets API response is big. Does the HTML /targets page also take that long to load? It should also include all the discovered labels, but not all the data about dropped targets, which I assume to be huge.

I suggest starting simple with whatever works for smaller use cases for now and then iterating (while discussing designs with the team) on the more optimized version.

**Comment by csmarchbanks** [comment]
Some timing information (Same clusters hooten would be using).
Targets page: 10.7s, 8.95MB
`api/v1/targets`: 3.5s, 137MB

Hopefully filtering by active will help the targets page a lot...

**Comment by juliusv** [comment]
@csmarchbanks Whoa, yeah. Will be interesting to see how fast a React-based targets page loads with an API endpoint that does not include dropped targets.

**Comment by hooten** [comment]
I will use the `state=active` and `state=dropped` pattern for the api on this
