### ISSUE TITLE
promethues report  ' "INVALID" is not a valid start token '

### ISSUE THREAD

**Issue by xie905528463** [prometheus/prometheus#6280]
## Proposal
**Use case. Why is this important?**

*“Nice to have” is not a good use case. :)*

## Bug Report
**What did you do?**
 I am setting up a promethues and grafana monitoring system. Now I have encountered this problem. The network between them is open, and the configuration format of promethues is no problem. I don't know if it is a bug of promethues. Please help me to see it. Thank you very much. !
**What did you expect to see?**

**What did you see instead? Under which circumstances?**

**Environment**
 
* System information:

	insert output of `uname -srm` here

* Prometheus version:

	insert output of `prometheus --version` here

* Alertmanager version:

	insert output of `alertmanager --version` here (if relevant to the issue)
        prometheus-2.4.3.linux-amd64
        prometheus-client:LATEST

* Prometheus configuration file:
  

* Alertmanager configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:

![image](https://user-images.githubusercontent.com/47200863/68265148-326f6400-0086-11ea-9733-f6dac75d2568.png)

![image](https://user-images.githubusercontent.com/47200863/68265176-4ca94200-0086-11ea-94d0-8f80faf6bb60.png)

![image](https://user-images.githubusercontent.com/47200863/68265392-de18b400-0086-11ea-9450-e3fa66ab369d.png)

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
