### ISSUE TITLE
PromQL: Allow negative (i.e. "future") offset

### ISSUE THREAD

**Issue by dgl** [prometheus/prometheus#6282]
Currently these are parse errors:
- `metric offset -5m`
- `sum_over_time(metric[1h:1m] offset -5m)`

I propose these should allow a negative offset and therefore allow offsetting a query to the future of where the evaluation time currently is. This should be a special case as other durations don't make sense to be negative.

Use cases:
- Annotations on graphs, for example using ALERTS to annotate where alerts happened, it would be useful in some cases to join on the future `alertstate="firing"` when an alert became pending (i.e. alert that was fired actually started here).
- Manually exploring data with subqueries: in nested subqueries it can be useful to "get rid" of an offset.
- Custom uses outside the main Prometheus, for example in Thanos a custom store API could answer queries in the "future", imagine a timeseries for planned maintenance or similar.

Most of the uses I envisage would be historical queries, using this with recording rules would obviously not be useful in Prometheus alone.

**Comment by dgl** [comment]
Draft pull request in #6283 6283

**Comment by brian-brazil** [comment]
This behaviour is correct, the PromQL evaluation model doesn't allow looking into the future. If you need this adjust the query execution time.

**Comment by dgl** [comment]
The problem is it's not always possible to adjust the execution time, taking the example of annotations on a graph in Grafana, see https://grafana.com/docs/features/datasources/prometheus/#annotations.

This only supports metric queries and a very limited alert integration. In particular if I can write a query like `ALERTS{alertstate="pending"} and (ALERTS{alertstate="firing"} offset -20m)` (would be templated, so the `for:` in the alert matches the dashboard). I now have a way to indicate the point an alert that is now firing started triggering (rather than showing all pending alerts which would be noisy).

**Comment by brian-brazil** [comment]
That sounds like a feature request for Grafana then, this is possible via
our API.

**Comment by dgl** [comment]
I feel this doesn't quite mesh with what I read in [the 2018 dev summit notes](https://docs.google.com/document/d/1-C5PycocOZEVIPrmM1hn8fBelShqtqiAmFptoG4yK70/edit#heading=h.j7cqr4nr2aq) about enabling data science uses of Prometheus. Particularly with Thanos involved there are different kinds of stores possible (for example I'm working on https://github.com/G-Research/geras which is part of our strategy to migrate towards Prometheus with Thanos from an existing OpenTSDB infrastructure). With something like that then it's quite possible to have metrics written into the future -- for example a "planned maintenance timeseries". It's obviously possible to change every client of the API to support this (probably in different ways), but it loses the nice aspect that having this in PromQL allows experimentation within the Grafana explore view, etc.

I understand this has been discussed before. I feel things have moved on slightly (in particular subqueries) and while some uses of this are certainly a bad idea trying to protect users from that prevents some interesting use cases in the Prometheus ecosystem. (It'd also be very easy to lint for this in recording rules, which is almost certainly a bad idea.)

**Comment by brian-brazil** [comment]
Writing data in the future and reading beyond the execution time are
different things, and you can always alter the execution time. Grafana has
various times shifting options for example.

**Comment by valyala** [comment]
@dgl , just FYI, VictoriaMetrics just gained support for negative offsets - see [Extended PromQL docs](https://github.com/VictoriaMetrics/VictoriaMetrics/wiki/ExtendedPromQL) for more details. You can try negative offsets in action by editing graphs 
 at http://play-grafana.victoriametrics.com:3000/d/4ome8yJmz/node-exporter-on-victoriametrics-demo or by running a build [from master branch sources](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/README.md#how-to-build-from-sources). Support for negative offsets will be available in the next release.

**Comment by nasiriamini** [comment]
It would have also addressed this shortcoming as well: [https://stackoverflow.com/questions/57454274/prometheus-negative-offset
](url)

**Comment by franck102** [comment]
Looking into the future may not make sense, but looking beyond "start" in range queries most definitely does!
`avg_over_time(gauge[1h])&start=<today 00:00:00>&end=...`

currently returns uses data from yesterday for the first sample.

**Comment by beorn7** [comment]
Since some discussions happened about this elsewhere, just wanted to add here that I'd like to see negative offsets. The use case is relatively niche, but often enough to get annoyed by working around the restriction by requesting a time in the future via the HTTP API and then use positive `offset`s on everything except where otherwise the negative `offset` would end up, rendering the PromQL query much harder to understand and the dashboard settings really weird.

The one relevant drawback is that any caching layer has to pay special attention to negative `offset`s in the query as that breaks assumptions of how recent the data is that the query will touch. I daresay that caching has to take so many aspects of cachability into account that this one more thing is acceptable.

**Comment by brian-brazil** [comment]
> I daresay that caching has to take so many aspects of cachability into account that this one more thing is acceptable.

I think that's understating it a bit. Currently a cache only needs to look at the end timestamp to determine if it is "safe" to cache a result. If this were added then all caches would for the first time need to parse and understand PromQL, and any cache failing to do so would be incorrect.

**Comment by beorn7** [comment]
> Currently a cache only needs to look at the end timestamp to determine if it is "safe" to cache a result.

That's not true. A cache has to also know the retention time and determine if the cached query is touching data that is, by the time of the cache hit, already expired. To do that cleanly, it already has to parse and actually understand the PromQL query.

In the case of a negative offset, no real understanding of the query is required. The only thing to find out is the `offset` with the largest amount of negative offset.

Furthermore, a cache has to ensure that no backfilling of data has happened and that no relevant series have been deleted.

Already now, "correct" caching depends on many conditions, some of which can only be enforced outside of Prometheus. Disallowing negative offsets could happen by contract in environments that depend on "dumb" caching, same as backfilling and deletion is disallowed by contract.

I don't think that caching concerns should keep us from allowing negative offsets.




Yes, it would need to parse the query.

But a cache already depends on a number of things, like no backfilling has happened, no series got deleted,

**Comment by codesome** [comment]
With `@ <timestamp>` incoming which can look into the future, I think we can now also allow negative offsets (The implementation of `@ <timestamp>` would internally use negative offsets too for future timestamps)?

**Comment by beorn7** [comment]
I am for it, but it should also be behind that feature flag that allows `@` in the first place. Essentially, we want a feature flag to gate the behavior of accessing data that is more recent than the most recent timestamp in the HTTP query parameters.

**Comment by roidelapluie** [comment]
I agree partly.

The feature flag with "future" wording might mean that you can query the past with '@'. My understanding is that '@' would be totaly disabled.

**Comment by beorn7** [comment]
I guess we _could_ introduce a `@` that is restricted to the most recent timestamp in the HTTP query parameters, but it might be technically tricky and surprise users in subtle ways.

So I guess the feature flag would allow `@` (i.e. no `@` at all without it) and negative values for `offset`. Or we could have two separate flags for it.

**Comment by roidelapluie** [comment]
(It is not exactly "future" , it is "after end-time".)

**Comment by codesome** [comment]
#8121 is merged which adds a flag `--enable-feature`. It should be straight forward to add negative offset now behind this flag. `--enable-feature=negative-offset`?

**Comment by juliusv** [comment]
Can this issue be closed now, now that this is implemented (albeit behind a flag)?

**Comment by roidelapluie** [comment]
Let's close it when your comments are addressed here: https://github.com/prometheus/prometheus/pull/8487

**Comment by vsile** [comment]
Hi! Is it implemented at 2.25.1?
There is no information about it in [releases page](https://github.com/prometheus/prometheus/releases).
I added the flag 
--enable-feature=promql-negative-offset
to the docker-compose file with prometheus:
![изображение](https://user-images.githubusercontent.com/9244347/111117100-16cc7580-8578-11eb-9771-a6eeaee258de.png)

But no effect. I get parse error:
![изображение](https://user-images.githubusercontent.com/9244347/111117254-572bf380-8578-11eb-8643-884ea31d3076.png)

**Comment by roidelapluie** [comment]
This will be in Prometheus 2.26.0.

if you want to test, you can use `prom/prometheus:main`, our development docker image. Please be aware that this is from our development tree, therefore it is not a image recommended for production.

**Comment by dgl** [comment]
Closing this now as it is implemented in main, once 2.26.0 is released the details for enabling the feature will be at: https://prometheus.io/docs/prometheus/latest/disabled_features/
