### ISSUE TITLE
BCLOSE on normal response - not even changing to UTF-8 helps

### ISSUE THREAD

**Issue by mlem** [prometheus/prometheus#6284]
## Bug Report
**What did you do?**
Upgraded Prometheus from 2.3.1 to 2.13.0

**What did you expect to see?**
Metrics from our system.

**What did you see instead? Under which circumstances?**
Nothing (`expected label name, got \"BCLOSE\"`)

Our code looks like this:
```
    @GetMapping(value = "/prometheus")
    @ResponseBody
    public String getMetrics() {
        return registry.scrape();
    }
```
I've debugged prometheus and could see, that prometheus content-type from the request is:
```application/openmetrics-text; version=0.0.1;charset=ISO-8859-1```
and we were getting 
```
level=warn ts=2019-11-05T12:59:06.271Z caller=scrape.go:930 component="scrape manager" scrape_pool=prometheus target=http://localhost:8080/prometheus msg="append failed" err="expected label name, got \"BCLOSE\""
```
I've found the issue #5065. 
What I could understand is, that we should return `UTF-8` encoded content and shouldn't have `,}` in the response.

So I've changed the response like this:
```
    @GetMapping(value = "/prometheus")
    @ResponseBody
    public ResponseEntity<String> getMetrics() {
        HttpHeaders responseHeaders = new HttpHeaders();
        responseHeaders.add("Content-Type", "application/openmetrics-text; charset=utf-8");

        return new ResponseEntity<>(
                new String(
                        registry
                                .scrape()
                                .replaceAll("\r", "")
                                .replaceAll(",}", "}")
                                .getBytes(),
                        StandardCharsets.UTF_8
                ),
                responseHeaders,
                HttpStatus.OK);
    }
```
But then I was getting this problem:
```
level=warn ts=2019-11-05T13:17:21.291Z caller=scrape.go:930 component="scrape manager" scrape_pool=prometheus target=http://localhost:8080/prometheus msg="append failed" err="unexpected end of data, got \"EOF\""
```

I've created an example project here:

https://github.com/mlem/prometheus_spring_example

**Comment by mlem** [comment]
Please help.

**Comment by brian-brazil** [comment]
Can you share the output of /metrics?

**Comment by mlem** [comment]
[prometheus.txt](https://github.com/prometheus/prometheus/files/3819095/prometheus.txt)

**Comment by brian-brazil** [comment]
That's valid output, are you sure that's what's being sent to Prometheus? It's possible your content negotiation is getting confused.

**Comment by mlem** [comment]
I'll try to copy paste the content from the debugger directly

**Comment by mlem** [comment]
![image](https://user-images.githubusercontent.com/1065169/68382792-bbed6780-0154-11ea-8d03-ce0172ce09f9.png)
And the content of buf.buf
<details>
<summary>Details</summary>

# HELP jvm_buffer_memory_used_bytes An estimate of the memory that the Java virtual machine is using for this buffer pool
# TYPE jvm_buffer_memory_used_bytes gauge
jvm_buffer_memory_used_bytes{id="mapped",} 0.0
jvm_buffer_memory_used_bytes{id="direct",} 57344.0
# HELP jvm_gc_memory_promoted_bytes_total Count of positive increases in the size of the old generation memory pool before GC to after GC
# TYPE jvm_gc_memory_promoted_bytes_total counter
jvm_gc_memory_promoted_bytes_total 0.0
# HELP jvm_buffer_total_capacity_bytes An estimate of the total capacity of the buffers in this pool
# TYPE jvm_buffer_total_capacity_bytes gauge
jvm_buffer_total_capacity_bytes{id="mapped",} 0.0
jvm_buffer_total_capacity_bytes{id="direct",} 57344.0
# HELP jvm_memory_committed_bytes The amount of memory in bytes that is committed for the Java virtual machine to use
# TYPE jvm_memory_committed_bytes gauge
jvm_memory_committed_bytes{area="nonheap",id="CodeHeap 'profiled nmethods'",} 8978432.0
jvm_memory_committed_bytes{area="heap",id="G1 Survivor Space",} 1.048576E7
jvm_memory_committed_bytes{area="heap",id="G1 Old Gen",} 2.06569472E8
jvm_memory_committed_bytes{area="nonheap",id="Metaspace",} 3.1113216E7
jvm_memory_committed_bytes{area="nonheap",id="CodeHeap 'non-nmethods'",} 2555904.0
jvm_memory_committed_bytes{area="heap",id="G1 Eden Space",} 1.81403648E8
jvm_memory_committed_bytes{area="nonheap",id="Compressed Class Space",} 3932160.0
jvm_memory_committed_bytes{area="nonheap",id="CodeHeap 'non-profiled nmethods'",} 2555904.0
# HELP jvm_memory_max_bytes The maximum amount of memory in bytes that can be used for memory management
# TYPE jvm_memory_max_bytes gauge
jvm_memory_max_bytes{area="nonheap",id="CodeHeap 'profiled nmethods'",} 1.22908672E8
jvm_memory_max_bytes{area="heap",id="G1 Survivor Space",} -1.0
jvm_memory_max_bytes{area="heap",id="G1 Old Gen",} 6.316621824E9
jvm_memory_max_bytes{area="nonheap",id="Metaspace",} -1.0
jvm_memory_max_bytes{area="nonheap",id="CodeHeap 'non-nmethods'",} 5836800.0
jvm_memory_max_bytes{area="heap",id="G1 Eden Space",} -1.0
jvm_memory_max_bytes{area="nonheap",id="Compressed Class Space",} 1.073741824E9
jvm_memory_max_bytes{area="nonheap",id="CodeHeap 'non-profiled nmethods'",} 1.22912768E8
# HELP jvm_threads_daemon_threads The current number of live daemon threads
# TYPE jvm_threads_daemon_threads gauge
jvm_threads_daemon_threads 43.0
# HELP jvm_gc_max_data_size_bytes Max size of old generation memory pool
# TYPE jvm_gc_max_data_size_bytes gauge
jvm_gc_max_data_size_bytes 0.0
# HELP jvm_classes_loaded_classes The number of classes that are currently loaded in the Java virtual machine
# TYPE jvm_classes_loaded_classes gauge
jvm_classes_loaded_classes 5976.0
# HELP jvm_threads_live_threads The current number of live threads including both daemon and non-daemon threads
# TYPE jvm_threads_live_threads gauge
jvm_threads_live_threads 44.0
# HELP jvm_gc_live_data_size_bytes Size of old generation memory pool after a full GC
# TYPE jvm_gc_live_data_size_bytes gauge
jvm_gc_live_data_size_bytes 0.0
# HELP jvm_classes_unloaded_classes_total The total number of classes unloaded since the Java virtual machine has started execution
# TYPE jvm_classes_unloaded_classes_total counter
jvm_classes_unloaded_classes_total 0.0
# HELP jvm_gc_memory_allocated_bytes_total Incremented for an increase in the size of the young generation memory pool after one GC to before the next
# TYPE jvm_gc_memory_allocated_bytes_total counter
jvm_gc_memory_allocated_bytes_total 0.0
# HELP system_cpu_count The number of processors available to the Java virtual machine
# TYPE system_cpu_count gauge
system_cpu_count 8.0
# HELP system_cpu_usage The "recent cpu usage" for the whole system
# TYPE system_cpu_usage gauge
system_cpu_usage 0.07483031869863674
# HELP process_cpu_usage The "recent cpu usage" for the Java Virtual Machine process
# TYPE process_cpu_usage gauge
process_cpu_usage 6.44642628254118E-4
# HELP jvm_threads_states_threads The current number of threads having NEW state
# TYPE jvm_threads_states_threads gauge
jvm_threads_states_threads{state="runnable",} 15.0
jvm_threads_states_threads{state="blocked",} 0.0
jvm_threads_states_threads{state="waiting",} 20.0
jvm_threads_states_threads{state="timed-waiting",} 9.0
jvm_threads_states_threads{state="new",} 0.0
jvm_threads_states_threads{state="terminated",} 0.0
# HELP system_load_average_1m The sum of the number of runnable entities queued to available processors and the number of runnable entities running on the available processors averaged over a period of time
# TYPE system_load_average_1m gauge
system_load_average_1m 4.35
# HELP jvm_threads_peak_threads The peak live thread count since the Java virtual machine started or peak was reset
# TYPE jvm_threads_peak_threads gauge
jvm_threads_peak_threads 46.0
# HELP jvm_buffer_count_buffers An estimate of the number of buffers in the pool
# TYPE jvm_buffer_count_buffers gauge
jvm_buffer_count_buffers{id="mapped",} 0.0
jvm_buffer_count_buffers{id="direct",} 7.0
# HELP jvm_memory_used_bytes The amount of used memory
# TYPE jvm_memory_used_bytes gauge
jvm_memory_used_bytes{area="nonheap",id="CodeHeap 'profiled nmethods'",} 7607296.0
jvm_memory_used_bytes{area="heap",id="G1 Survivor Space",} 1.048576E7
jvm_memory_used_bytes{area="heap",id="G1 Old Gen",} 3518976.0
jvm_memory_used_bytes{area="nonheap",id="Metaspace",} 2.9708576E7
jvm_memory_used_bytes{area="nonheap",id="CodeHeap 'non-nmethods'",} 1294720.0
jvm_memory_used_bytes{area="heap",id="G1 Eden Space",} 8.912896E7
jvm_memory_used_bytes{area="nonheap",id="Compressed Class Space",} 3413096.0
jvm_memory_used_bytes{area="nonheap",id="CodeHeap 'non-profiled nmethods'",} 2102144.0


</details>

**Comment by mlem** [comment]
Ok, I've changed the Content-Type to UTF-8 and the string should be UTF-8 encoded too. 
```
content-type: application/openmetrics-text;charset=utf-8
```
See debug headers:
![image](https://user-images.githubusercontent.com/1065169/68466543-e868b880-0214-11ea-8231-e9cefe5fd595.png)

Buffer:
[metrics.txt](https://github.com/prometheus/prometheus/files/3823957/metrics.txt)

And yet, still I'm getting
```
msg="append failed" err="expected label name, got \"BCLOSE\""
```

**Comment by brian-brazil** [comment]
That's the OpenMetric content type, not the Prometheus format content type.

**Comment by mlem** [comment]
I've created an easy to reproduce example in https://github.com/mlem/prometheus_spring_example
You just need to install docker and docker-compose to see the error.
I'm using it to debug this problem in separation. 
If you want to use your local prometheus for debugging:
Remove 
```
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3020:3000
    networks:
      - monitoring
  prometheus:
    image: prom/prometheus:v2.13.1
    container_name: prometheus
    ports:
      - 9090:9090
    networks:
      - monitoring
    volumes:
      - .:/etc/prometheus
```
from `docker-compose.yml` and use the commited `prometheus.yml`.
You still need to run beforhand the app:
```
docker run -it --rm --name my-maven-project -v "$PWD":/usr/src/app -w /usr/src/app maven:3.6.2-jdk-11-slim mvn clean install
docker-compose build
docker-compose up
```

**Comment by mlem** [comment]
Oh, haven't seen that you responded. So I'll try to use the prometheus format content-type :+1:

**Comment by mlem** [comment]
Setting the correct Content-type helped to fix this issue.
It's `text/plain;version=0.0.4;charset=utf-8`

```
 @GetMapping(value = "/prometheus", produces = {"text/plain;version=0.0.4;charset=utf-8"})
    @ResponseBody
    @SuppressWarnings("unused")
    public String getMetrics() {
        return registry.scrape();
    }
```

You can find a working solution in https://github.com/mlem/prometheus_spring_example
