### ISSUE TITLE
eval_time does not actually support all possible <duration> values

### ISSUE THREAD

**Issue by walterdolce** [prometheus/prometheus#6285]
## Bug Report
**What did you do?**
I tried to set `eval_time` as for an alert rule test as follows, but none of them worked:
```
eval_time: 1d
eval_time: 1w
eval_time: 1y
```

**What did you expect to see?**
I expected no errors, [as per documentation](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#configuration-file):
> `<duration>`: a duration matching the regular expression `[0-9]+(ms|[smhdwy])`

**What did you see instead? Under which circumstances?**
```
yaml: unmarshal errors:
  line 27: cannot unmarshal !!str `1d` into time.Duration

# same for "1w" and "1d"
```

**Environment**

* System information:
`Darwin 19.0.0 x86_64`

* Prometheus version:
```
prometheus, version 2.13.1 (branch: non-git, revision: non-git)
  build user:       brew@Catalina.local
  build date:       20191018-01:35:32
  go version:       go1.13.1
```

```
promtool, version 2.13.1 (branch: non-git, revision: non-git)
  build user:       brew@Catalina.local
  build date:       20191018-01:35:32
  go version:       go1.13.1
```

* Alertmanager version:
N/A

* Prometheus configuration file:
N/A

* Alertmanager configuration file:
N/A

* Logs:
N/A

**Comment by roidelapluie** [comment]
Hello.

I do not think that it is sane to put durations of > 5 minutes because Prometheus will by default consider the metric stale after 5 minutes. I think instead we should fix the documentation.

**Comment by walterdolce** [comment]
I would explicitly fail with a meaningful message, in addition to fixing
the documentation, if that's the course of action that ought to be taken.

W

**Comment by brian-brazil** [comment]
I haven't tested it yet, but this sounds like a bug. You should be able to evaluate rules into the future for testing.

**Comment by brian-brazil** [comment]
The issue is we're using `time.Duration` rather than our own duration code.
