### ISSUE TITLE
Request to re-open issue #5735

### ISSUE THREAD

**Issue by chs-bnet** [prometheus/prometheus#6287]
## Proposal

We've added a couple comments to the original issue requesting that it be re-opened.

Currently, if prometheus cannot successfully complete a remote_write operation, it will log an error. However, if using a proxy via the proxy_url configuration option, prometheus will NOT log an error.

As we log separate out from metrics and have prometheus running on VM's (not containers) via systemd, it is not always practical to monitor the internal metrics for prometheus (and not always possible if it cannot complete a remote_write operation). Being able to easily trouble-shoot issues by looking at logs is basic systems administration and prometheus is completely inconsistent in how and what it logs and why.
  
We would like to see issue #5735  re-opened for these reasons. Thanks.

**Comment by csmarchbanks** [comment]
Closing this as I have reopened #5735.
