### ISSUE TITLE
custom remote write decompress with snappy failed in FAILED_TO_UNCOMPRESS(5) sometimes

### ISSUE THREAD

**Issue by reallax** [prometheus/prometheus#6296]
## Bug Report
**What did you do?**
I need a custom remote write module and implement it with java. 

**What did you expect to see?
Snappy.uncompress() works stable.

**What did you see instead? Under which circumstances?**
Snappy.uncompress() failed sometimes with error IOException: FAILED_TO_UNCOMPRESS(5)
Attention please: not always failed, lots of time it's decompressed ok.

**Environment**
* prometheus version: prometheus-2.13.1.linux-amd64
* java snappy version:
<groupId>org.xerial.snappy</groupId>
<artifactId>snappy-java</artifactId>
<version>1.1.7.3</version>
* java decompress method: org.xerial.snappy.Snappy.uncompress();
* prometheus http request header:  user-agent=Prometheus/2.13.1; content-length=1881; content-encoding=snappy; content-type=application/x-protobuf; x-prometheus-remote-write-version=0.1.0;

* System information:
Darwin xxMacBook-Pro.local 18.0.0 Darwin Kernel Version 18.0.0: Wed Aug 22 20:13:40 PDT 2018; root:xnu-4903.201.2~1/RELEASE_X86_64 x86_64

* Prometheus version:
prometheus, version 2.13.1 (branch: HEAD, revision: 6f92ce56053866194ae5937012c1bec40f1dd1d9)
  build user:       root@88e419aa1676
  build date:       20191017-13:15:01
  go version:       go1.13.1

* Prometheus configuration file:
```
# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['localhost:9090']
  - job_name: dmg_sdk_test
    static_configs:
      - targets: ['10.112.101.9:33731']

# Settings related to the remote write feature.
remote_write:
  - url: "http://10.112.101.9:8080/simple/transmit"
    write_relabel_configs:
    - source_labels: [__name__]
      target_label:  metric_name
```

* Prometheus Logs:
```
level=info ts=2019-11-09T10:14:16.556Z caller=queue_manager.go:559 component=remote queue=0:http://10.12.201.9:8080/simple/transmit msg="Remote storage resharding" from=1000 to=688
level=info ts=2019-11-09T10:14:36.556Z caller=queue_manager.go:559 component=remote queue=0:http://10.12.201.9:8080/simple/transmit msg="Remote storage resharding" from=688 to=439
level=info ts=2019-11-09T10:15:06.556Z caller=queue_manager.go:559 component=remote queue=0:http://10.12.201.9:8080/simple/transmit msg="Remote storage resharding" from=439 to=245
level=info ts=2019-11-09T10:15:36.556Z caller=queue_manager.go:559 component=remote queue=0:http://10.12.201.9:8080/simple/transmit msg="Remote storage resharding" from=245 to=132
level=info ts=2019-11-09T10:16:06.556Z caller=queue_manager.go:559 component=remote queue=0:http://10.12.201.9:8080/simple/transmit msg="Remote storage resharding" from=132 to=72
level=info ts=2019-11-09T10:16:36.556Z caller=queue_manager.go:559 component=remote queue=0:http://10.12.201.9:8080/simple/transmit msg="Remote storage resharding" from=72 to=38
level=info ts=2019-11-09T10:16:56.556Z caller=queue_manager.go:559 component=remote queue=0:http://10.12.201.9:8080/simple/transmit msg="Remote storage resharding" from=38 to=27
level=info ts=2019-11-09T10:17:26.556Z caller=queue_manager.go:559 component=remote queue=0:http://10.12.201.9:8080/simple/transmit msg="Remote storage resharding" from=27 to=14
level=info ts=2019-11-09T10:17:56.556Z caller=queue_manager.go:559 component=remote queue=0:http://10.12.201.9:8080/simple/transmit msg="Remote storage resharding" from=14 to=8
level=info ts=2019-11-09T10:18:06.556Z caller=queue_manager.go:559 component=remote queue=0:http://10.12.201.9:8080/simple/transmit msg="Remote storage resharding" from=8 to=6
level=info ts=2019-11-09T10:18:26.556Z caller=queue_manager.go:559 component=remote queue=0:http://10.12.201.9:8080/simple/transmit msg="Remote storage resharding" from=6 to=4
level=info ts=2019-11-09T10:18:46.556Z caller=queue_manager.go:559 component=remote queue=0:http://10.12.201.9:8080/simple/transmit msg="Remote storage resharding" from=4 to=3
```

* Java Logs:
```
[ERROR] 2019-11-09 18:19:44.944 [com.dmall.prom.remote.receiver.receiver.ReceiverController][http-nio-8080-exec-79] - transmitReceiver handle request error! 
java.io.IOException: FAILED_TO_UNCOMPRESS(5)
	at org.xerial.snappy.SnappyNative.throw_error(SnappyNative.java:98) ~[snappy-java-1.1.7.3.jar:na]
	at org.xerial.snappy.SnappyNative.rawUncompress(Native Method) ~[snappy-java-1.1.7.3.jar:na]
	at org.xerial.snappy.Snappy.rawUncompress(Snappy.java:474) ~[snappy-java-1.1.7.3.jar:na]
	at org.xerial.snappy.Snappy.uncompress(Snappy.java:513) ~[snappy-java-1.1.7.3.jar:na]
	at org.xerial.snappy.Snappy.uncompress(Snappy.java:488) ~[snappy-java-1.1.7.3.jar:na]
	at com.dmall.prom.remote.receiver.receiver.ReceiverController.transmitReceiver(ReceiverController.java:70) ~[classes/:na]
	at sun.reflect.GeneratedMethodAccessor37.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_144]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_144]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190) [spring-web-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138) [spring-web-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:104) [spring-webmvc-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:892) [spring-webmvc-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797) [spring-webmvc-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) [spring-webmvc-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1039) [spring-webmvc-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942) [spring-webmvc-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005) [spring-webmvc-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:908) [spring-webmvc-5.1.9.RELEASE.jar:5.1.9.RELEASE]
```

**Comment by csmarchbanks** [comment]
Just to be clear, this is an issue that is only happening in your custom java code correct?

If so, records are only snappy encoded if the compression actually makes the data smaller, so you will have to check a header bit for each record to see if it is compressed or not. Do you handle that situation in your application?

**Comment by csmarchbanks** [comment]
@reallax About how often does the uncompress failure happen, and if the request is retried does it work? Also, do you have a minimal application I could try to build to debug this?

I have never seen a failure to uncompress snappy from any of my remote receivers, but they have also all been written in go.

**Comment by reallax** [comment]
@csmarchbanks sorry for the late reply. In my opinion, the error frequency is a little high.Here is my test demo.
`import com.sun.net.httpserver.Headers;
import com.sun.net.httpserver.HttpExchange;
import com.sun.net.httpserver.HttpHandler;
import com.sun.net.httpserver.HttpServer;
import org.xerial.snappy.Snappy;

import java.io.IOException;
import java.io.InputStream;
import java.net.InetSocketAddress;
import java.util.concurrent.*;


public class SnappyDecompressErrorDemo {

    private static ExecutorService executorService;
    private static HttpServer server;
    private static int port = 8088;

    public static void main(String[] args) {
        try {
            server = HttpServer.create();
            server.bind(new InetSocketAddress(port), 3);

            executorService = new ThreadPoolExecutor(
                    5, 5, 0,
                    TimeUnit.MILLISECONDS, new LinkedBlockingQueue<Runnable>(),
                    Executors.defaultThreadFactory());

            server.createContext("/simple/transmit", new CustomHandler());
            server.start();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }


    public static class CustomHandler implements HttpHandler {

        @Override
        public void handle(HttpExchange h) throws IOException {

            int len = 0;
            try {
                Headers headers = h.getRequestHeaders();

                // result same thing
//                len = h.getRequestBody().available();
                len = getContentLength(headers);

                byte[] compressBytes = new byte[len];
                InputStream is = h.getRequestBody();
                is.read(compressBytes, 0, len);
                is.close();


                // try decompress
                byte[] clearBytes = Snappy.uncompress(compressBytes);
                System.out.println(String.format("* content length: %s, clearBytes: %s", len, clearBytes));
            } catch (Exception e) {
                System.out.println(String.format("# error! content length: %s", len));
                e.printStackTrace();
            }
        }

        private int getContentLength(Headers headers) {
            String len = headers.get("Content-length").get(0);
            return Integer.valueOf(len);
        }

        private void printHeaders(Headers headers) {
            for (String key:headers.keySet()) {
                System.out.println(key + " : " + headers.get(key));
            }
        }
    }
}`

you need jdk1.8, and maven dependecy:
`<dependency>
            <groupId>org.xerial.snappy</groupId>
            <artifactId>snappy-java</artifactId>
            <version>1.1.7.3</version>
        </dependency>`

**Comment by csmarchbanks** [comment]
@reallax I have managed to reproduce for large payloads (setting `max_samples_per_send` to 1000 reproduces it every time). I am not yet sure if it is an issue with Prometheus setting the content length, or something in the snappy library not processing large inputs.

In the meantime, by using `SnappyInputStream` rather than the content length, I have not had any failures decompressing the data. E.g.
```
        public void handle(HttpExchange h) throws IOException {

            try {
                SnappyInputStream is = new SnappyInputStream(h.getRequestBody());
                WriteRequest wr = WriteRequest.parseFrom(is);
                is.close();

                System.out.println(String.format("*  wr.count: %s", wr.getTimeseriesCount()));
                h.sendResponseHeaders(200, -1);
            } catch (Exception e) {
                System.out.println(String.format("# error!"));
                e.printStackTrace();
                h.sendResponseHeaders(503,-1);
            }
            h.close();
        }
```

Hope this helps, and I will let you know if I find out anything about why the content length method isn't working.

**Comment by reallax** [comment]
@csmarchbanks yes! It works, thanks very much.

**Comment by roidelapluie** [comment]
We have looked into this issue during our bug scrub and it looks like this issue was resolved, or was in the snappy Java library. If you think it is an issue with Prometheus please let us know.
