### ISSUE TITLE
React UI: Figure out how to "normalize" localhost URLs

### ISSUE THREAD

**Issue by juliusv** [prometheus/prometheus#6301]
The classic UI replaces the linked URL for targets that have a localhost-ish URL with the global URL, see: https://github.com/prometheus/prometheus/blob/37d666949c9475e298666cc8e0e787d76fa8fd77/web/web.go#L947-L984

We need to figure out how to do this with the new React UI as well.

**Comment by brian-brazil** [comment]
Should we consider getting rid of this behaviour?

**Comment by juliusv** [comment]
I think it depends on how ugly it would be to implement it for the new UI, since it is definitely useful, but not critical either.

**Comment by Harkishen-Singh** [comment]
I would like to take up this. Thank you.
