### ISSUE TITLE
React UI: Figure out how to handle "Xs ago" duration displays

### ISSUE THREAD

**Issue by juliusv** [prometheus/prometheus#6302]
Some of the pages in the classic UI (like /targets and /rules) show durations in the format "3.45s ago". In the new React UI, we get only absolute timestamps of events from the server, so if we wanted to compute such a relative duration, we need a relative "now" timestamp to subtract them from. The current approach is to use the browser's current timestamp, but the user's clock might be totally off with regards to the server's. We could instead think about using the `Date` header that the Prometheus server returns on every API request, and which is at least precise to the second (although not lower).

**Comment by kimuraz** [comment]
@juliusv can I work on this issue?

**Comment by juliusv** [comment]
@kimuraz Sure. First thing is to figure out what we want to do though. Via date header or some other way? I don't like any of the options, but maybe the Date header is the least bad?

**Comment by kimuraz** [comment]
@juliusv I did some research but so far I guess the Date header is the "least bad" option indeed, I guess it will guarantee that the calculation is correct since it will have the same reference. If that's the way, what is the Definition of Done for this issue? I mean, what should be delivered in this case?

**Comment by juliusv** [comment]
@kimuraz Yes, I'm thinking the same. Another option would be to replace the "Xs ago" displays with absolute timestamps, but I feel that the relative displays are much more useful for the reader.

So I would say, go for the Date header option.

> what is the Definition of Done for this issue? I mean, what should be delivered in this case?

A pull request that changes the existing React UI code to make available the `Date` header timestamp for relative time computations by the component that fetches data, and then use that on the `/new/targets` and `/new/rules` pages (the latter doesn't exist yet in the React UI). Currently the targets page uses a client-side `now()` timestamp as a reference, which would need to be replaced: https://github.com/prometheus/prometheus/blob/06b47447938a9017e7d1c2ad24df050fd61964df/web/ui/react-app/src/pages/targets/ScrapePoolPanel.tsx#L82
