### ISSUE TITLE
Data lost after restart

### ISSUE THREAD

**Issue by urupaud** [prometheus/prometheus#6311]
## Bug Report
**What did you do?**
Restarted prometheus service (task definition) which was running on AWS ECS.

**What did you expect to see?**
All the previous metrics should be there .

**What did you see instead? Under which circumstances?**
All the data was wiped out from the storage. I had data of 60 days but they were all gone. 

**Environment**

* System information:

	Linux 4.14.143-118.123.amzn2.x86_64 x86_64

* Prometheus version:

	Latest docker version prom/prometheus.   version="(version=2.13.1, branch=HEAD, revision=6f92ce56053866194ae5937012c1bec40f1dd1d9)"

* Prometheus configuration file:
These are the arguments which I was passing as you can see --storage.tsdb.retention.time was set to 60d.

"--config.file=/etc/prometheus/prometheus.yml", "--storage.tsdb.path=/prometheus", "--web.console.libraries=/usr/share/prometheus/console_libraries", "--web.console.templates=/usr/share/prometheus/consoles" ,"--storage.tsdb.retention.time=60d", "--web.external-url=https://prometheus.example.com"

**Comment by urupaud** [comment]
Note that I'm using image as prom/prometheus:latest in my docker file, so I believe this could updated my prometheus version but still the data shouldn't be wiped out I guess. And now I restarted it again but now the data is there (data of past few mins, not the 60 days data)

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
