### ISSUE TITLE
Expose the Head Cardinality Stats as metrics

### ISSUE THREAD

**Issue by csmarchbanks** [prometheus/prometheus#6317]
## Proposal

I have heard several requests from people who would like to have the new cardinality metrics exported as regular metrics such that you could see patterns and alert upon them.

The series themselves have a small possibility of adding churn to your system as cardinality of your data changes, but generally a top 10 or 20 is relatively stable and could be exported.

**Comment by brian-brazil** [comment]
I don't think this is safe at all, there's a non-trivial chance for churn particularly when there's low cardinality. This is a profiling/debugging tool, which doesn't make it good for metrics.

**Comment by sharadgaur** [comment]
A minimum of 40 metrics will be added per scrape interval if we are doing the top 10 of each cardinality stats. If we want to expose these stats as metrics, I would recommend we keep the number of metrics per cardinality stats small (like top 5 or 10).

In short, high (top `n`) number of metrics will create higher churn rate:
(higher churn) `top n >top 20 > top 10 > top 5 > top 1` (least churn)

**Comment by csmarchbanks** [comment]
I agree with Brian, naively exporting the current data is not safe. However, I think there are ways we could provide more helpful metrics for determining when cardinality issues are occurring. I am hoping that by collecting some use cases a safe solution is found.

**Comment by brian-brazil** [comment]
We should already have such metrics.

**Comment by AdamVonHorn** [comment]
Why not just expose the metrics as a Prometheus endpoint so that I don't have to create a Prometheus-Prometheus exporter?

**Comment by nicholasgibson2** [comment]
+1 for exposing these on a metrics endpoint

**Comment by roidelapluie** [comment]
I agree with @brian-brazil here.

**Comment by hagen1778** [comment]
Can we expose this info via `/api/v1/status/headinfo`?

**Comment by sharadgaur** [comment]
It will be exposed via `/api/v1/status/tsdb` in `v2.15` release

**Comment by AdamVonHorn** [comment]
@sharadgaur Dumb question, but will it be Prometheus format?

**Comment by sharadgaur** [comment]
It will be JSON format (its REST API endpoint)

**Comment by AdamVonHorn** [comment]
Great! This will work perfectly for my Prometheus-Prometheus exporter!

**Comment by roidelapluie** [comment]
We have looked into this issue during our bug scrub, and that data is exposed in the TSDB api /api/v1/status/tsdb.
