### ISSUE TITLE
metric scrape from prometheus federation is different from the origin

### ISSUE THREAD

**Issue by diemus** [prometheus/prometheus#6328]
## Proposal
**Use case. Why is this important?**

metric scrape from prometheus federation is different from the origin

*“Nice to have” is not a good use case. :)*

## Bug Report
**What did you do?**

I build a prometheus federation, one prometheus in the k8s cluster , and one out of k8s cluster.
I use the outside one to collect metrics from the inside one though federation. and I have  a metric called probe_success_detail

**What did you expect to see?**

I thought the query result would be the same from both side

**What did you see instead? Under which circumstances?**
but  the one inside k8s cluster returns 1 result, the one outside k8s cluster return 19 results, it seems federation uses some kind of cache causes this problem

the inside one's result:
	`probe_success_detail{body_match="false",cluster_id="3",duration="2.851163853",header_match="false",host="test.com",http_code="462",instance="http://test.com/",job="blackbox",name="d92d3b77-b182-49f7-961e-313520dceb1d",namespace="blackbox",path="/",schema="http"}`

the outside one has the same label values  but with different durations

<img width="1417" alt="1" src="https://user-images.githubusercontent.com/9145160/69021257-2d010a80-09f2-11ea-9f79-d0bac74606ff.png">
<img width="1384" alt="2" src="https://user-images.githubusercontent.com/9145160/69021262-34c0af00-09f2-11ea-87cb-b381e2485b4d.png">

**Environment**

* System information:

	insert output of `uname -srm` here

* Prometheus version:
	v2.13.1

* Alertmanager version:

	insert output of `alertmanager --version` here (if relevant to the issue)

* Prometheus configuration file:
```
insert configuration here
```

* Alertmanager configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
