### ISSUE TITLE
compaction: Consider merging chunks for the same series during compaction.

### ISSUE THREAD

**Issue by bwplotka** [prometheus/prometheus#6332]
## Proposal
**Use case. Why is this important?**

Compactions merge blocks. For chunks, however, it just appends chunks to the same set if they are for the same series: https://github.com/prometheus/prometheus/blob/3344bb5c332838df21f87b6473c0764315f5ca71/tsdb/compact.go#L1008

If we assume that chunks should cover 120 samples, during compaction we may end up with much smaller, inefficient chunks, especially with series with bigger scrape interval (15s -> 30m chunks; 1m -> 120m) or downsampled series (5m -> 10h; 1h -> 5d).

I would propose adding logic for chunk merging during the compaction process. I think we briefly mentioned this during the dev summit as well.

Any thoughts? (:

**Comment by brian-brazil** [comment]
Didn't someone look at this before?

**Comment by bwplotka** [comment]
Actually dig further and we have some issues in archived TSDB:
* https://github.com/prometheus/tsdb/issues/236
* https://github.com/prometheus/tsdb/pull/397

I don't know why this issue ended up investigating chunks bigger than 120 samples chunks, I think it's clear it's not worth it. 

The new information here is though downsampling, plus I think we tested only with 15s scrape interval (?). That's why it might be worth to repeat this test, but it's not a high priority. Also one of the arguments in the mentioned issue was that index size is not a big deal: For Thanos we see indexes beyond 30GB, so any improvement here is a win. As per older tests we might want to be careful to not make the compaction process taking to a lot longer.

**Comment by brian-brazil** [comment]
The number of chunks makes no difference to index size.

**Comment by bwplotka** [comment]
I think it increases it a bit https://github.com/prometheus/tsdb/blob/master/docs/format/index.md#series but the question is how significant as we are talking only about edge chunks being potentially merged during compaction.

**Comment by brian-brazil** [comment]
That's series, not chunks.

**Comment by codesome** [comment]
Each chunk has its entry in the index as far as I know (inside that series). That's the major contributor to the index size.

**Comment by bwplotka** [comment]
yes, so it can accumulate over compactions, especially for chunks that can be merged into 120 samples.

**Comment by irajdeep** [comment]
@bwplotka I can work on this if we have agreed on the idea of merging chunks : -)

**Comment by bwplotka** [comment]
Thanks! I think the agreement will be there only if we see benchmarking results that would confirm our reasoning here: chunks being partial for million of series on the edges of the block.

**Comment by codesome** [comment]
@irajdeep: As @bwplotka said the idea is still on but getting it upstream would depend on the benchmarks. Also, merging chunks is expensive. If you could implement it and benchmark, that would be great!

**Comment by roidelapluie** [comment]
@codesome Is this still on? As per our bug scrub, it looks like for prometheus it would not really be a big performance gain.

**Comment by bwplotka** [comment]
I mean we are only guessing this. I think the key is to have some data first hot often this actually happens (that we have incomplete chunks).

Also, given the ideas we have for backfilling (which might result in small chunks) I think this is still worth checking out.

However I think, given that this affects mostly Thanos with downsampling, this issue should be rather tracked on Thanos board. Let's close for now (:

**Comment by bwplotka** [comment]
Moved to https://github.com/thanos-io/thanos/issues/2769

**Comment by codesome** [comment]
With https://github.com/prometheus/prometheus/issues/7396, it might be possible to have small chunks, though not in Prometheus as it will have 0 grace period. (all this assuming it will go in)
