### ISSUE TITLE
Differentiate between conflicting rules defined in different rule files

### ISSUE THREAD

**Issue by pgier** [prometheus/prometheus#6334]
## Bug Report
**What did you do?**
Create two rules files which both contain the same recording rule name but different expressions/values.

**What did you expect to see?**
Either a notification that these rules conflict or some way to differentiate them into different time series.

**What did you see instead? Under which circumstances?**
The rules will create a single metric with alternating values as they are recorded.

* Prometheus version:

	prometheus, version 2.14.0 (branch: master, revision: 23c0299d85bfeb5d9b59e994861553a25ca578e5)

![prometheus_conflicting_recording_rules](https://user-images.githubusercontent.com/156120/69100329-900a9580-0a22-11ea-981f-7e3ccd852010.png)

Possible solution could be to add a rule filename label to each rule before they are stored to tsdb.

**Comment by pgier** [comment]
Although similar to #5529, this issue is different in that the two rules are defined in separate files and do not have any differences in labels.

**Comment by brian-brazil** [comment]
This is a valid, though broken configuration. I don't think there's anything for us to do here.

**Comment by pgier** [comment]
If it's considered a broken configuration shouldn't prometheus provide some kind of error/warning?

**Comment by brian-brazil** [comment]
We can't catch every possible way in which users can cause a label clash, though there should be at least metrics covering this already.

**Comment by pgier** [comment]
Are there potential problems with automatically adding a label which includes the filename of the source of the rule?

**Comment by brian-brazil** [comment]
Yes, that will completely break many many use cases.

**Comment by roidelapluie** [comment]
We have been looking into this into our bug scrub and we have decided that there is nothing we can reasonably do in Prometheus as there are many valid uses cases where this could happen. There is also a similar issue in #912 for verbatim rules.
