### ISSUE TITLE
Active Query logging not capturing in queries.active file

### ISSUE THREAD

**Issue by bingikarthik** [prometheus/prometheus#6341]
Prometheus config looks like as follows:
$ cat /etc/systemd/system/prometheus.service
[Unit]
Description=Prometheus
Wants=network-online.target
After=network-online.target

[Service]
User=root
Group=root
LimitNOFILE=1048576
LimitNPROC=1048576
LimitCORE=infinity
Restart=always
RestartSec=2
Type=simple
ExecStart=/opt/prometheus/prometheus \
    --config.file /opt/butler/prometheus/prometheus.yml \
    --web.listen-address ":45324" \
    --storage.tsdb.path /raid/prometheus/prometheus-data/ \
    --web.enable-lifecycle \
    --web.console.templates=/opt/prometheus/consoles \
    --web.console.libraries=/opt/prometheus/console_libraries \
    --query.max-concurrency=20 \
    --query.max-samples=50000000 \
    --query.timeout=2m

[Install]
WantedBy=multi-user.target

And we are using 2.13.1 Prometheus version 
`$ curl http://<domain_name>:45324/version`
`{"version":"2.13.1","revision":"6f92ce56053866194ae5937012c1bec40f1dd1d9","branch":"HEAD","buildUser":"root@88e419aa1676","buildDate":"20191017-13:15:01","goVersion":"go1.13.1"}`

Furthermore, It was seen that Prometheus got crashed recently
![image](https://user-images.githubusercontent.com/8635912/69150865-8c990c00-0aff-11ea-9494-441d906167bb.png)

But **we don't see any output of query logging captured in queries.active** other than [
`$ cat queries.active`
`[`

**Comment by brian-brazil** [comment]
Do you have logs from when Prometheus started up again?

**Comment by bingikarthik** [comment]
@brian-brazil 
Yes we have logs for it, please check the logs that was captured from the starting of Prometheus : https://drive.google.com/file/d/1ktPN8NtXGAn-RrSrliEFBKWX35V4JR0c/view?usp=sharing

**Comment by bingikarthik** [comment]
@brian-brazil Yes we have logs for it, please check some of the logs that was captured from the starting of Prometheus: https://drive.google.com/file/d/11h5mWi-NYivBVjW_l_Osooae3n541RMw/view?usp=sharing

**Comment by brian-brazil** [comment]
> Nov 18 14:12:51 <domain_name> prometheus[19522]: level=info ts=2019-11-18T14:12:51.218Z caller=query_logger.go:77 component=activeQueryTracker msg="These queries didn't finish in prometheus' last run:" queries="[<<<Query>>>]"

Looks like it's all working to me.

**Comment by bingikarthik** [comment]
But it should be also present in `queries.active` file right?
The output was showing like this only:
`cat /raid/prometheus/prometheus-data/queries.active`
`[`

**Comment by brian-brazil** [comment]
Only until Prometheus restarts, at which point there are no active queries.

**Comment by bingikarthik** [comment]
Oh ok got it
Thanks for the explanation @brian-brazil
