### ISSUE TITLE
container_spec_memory_limit_bytes value 0 is sent for no limit pods/containers

### ISSUE THREAD

**Issue by malli31** [prometheus/prometheus#6348]
## Proposal
**container_spec_memory_limit_bytes value is set to 0 for no limit pods or containers. Why is this important?, 

**

*“Nice to have” is not a good use case. :)*

## Bug Report
** we are calculating memory utilization using  (sum(container_spec_memory_limit_bytes{container!="POD",container!=""
      }) by ( namespace, pod) !=0 > bool 1) * 100 * (sum(container_memory_usage_bytes{container!="POD",container!=""}) by ( namespace, pod)/sum(container_spec_memory_limit_bytes{container!="POD",container!=""}) by ( namespace, pod)) this query  so for some pods/containers for which limit is not there for example prometheus-k8s-0 container_spec_memory_limit_bytes is set as 0 and the total memory utilization is more the 1000 always, **

**What did you expect to see? 

By running docker stats I can see that container_spec_memory_limit_bytes is set to remaining avilable memory of the node, so if there is no limit please set this to avilable memory of the node or something in sync with docker stats
**

**container_spec_memory_limit_bytes is set to zero 0 when limit is not there on container**

**Kubernetes latest**

* System information:

	insert output of `uname -srm` here

* Prometheus version:

	insert output of `latest` here

* Alertmanager version:

	insert output of `latest` here (if relevant to the issue)

* Prometheus configuration file:
```
insert configuration here
```

* Alertmanager configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```

**Comment by simonpasquier** [comment]
Thanks for your report. It looks as if this is actually a question about usage and not development.

To make your question, and all replies, easier to find, we suggest you move this over to our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search. If you prefer more interactive help, join or our [IRC channel](https://webchat.freenode.net/?randomnick=1&channels=prometheus), #prometheus on irc.freenode.net. Please be aware that our IRC channel has no logs, is not searchable, and that people might not answer quickly if they are busy or asleep. If in doubt, you should choose the mailing list.

Once your questions have been answered, please add a short line pointing to relevant replies in case anyone stumbles here via a search engine in the future.
