### ISSUE TITLE
Stacked graph is not displayed in enforced order

### ISSUE THREAD

**Issue by ahes** [prometheus/prometheus#6354]
## Proposal
Stacked graph is ordered randomly. The most intuitive approach would be to order stacked graphs bottom up from the biggest to the lowest values. Order direction may be enforced by using `sort()` and `sort_desc()` functions.

**Use case. Why is this important?**

Stacked graph is not fully readable because zero values can land in the middle of the chart.

## Bug Report
Stacked graph does NOT show values in order.

Query:
```
sort_desc(sum by (my_label) (increase(requests_total{my_label=~"..."}[6h])))
```

Console shows correctly ordered values.

Screenshots:
![Screenshot 2019-11-21 at 13 49 43](https://user-images.githubusercontent.com/1119356/69342116-27622980-0c6b-11ea-8066-3f521761e354.png)
![Screenshot 2019-11-21 at 13 49 53](https://user-images.githubusercontent.com/1119356/69342119-292bed00-0c6b-11ea-8a8a-6fb516321433.png)

**Environment**

* System information:

```
Linux 4.15.0-58-generic x86_64
```

* Prometheus version:

```
prometheus, version 2.13.1 (branch: HEAD, revision: 6f92ce56053866194ae5937012c1bec40f1dd1d9)
  build user:       root@88e419aa1676
  build date:       20191017-13:15:01
  go version:       go1.13.1
```

**Comment by brian-brazil** [comment]
Each timestamp is independant, so there is no correct sorting across each series as a whole. Consider for example a set of time series where each series was 0 in turn. This doesn't appear to have any possible solution.

**Comment by juliusv** [comment]
Agreed with @brian-brazil here. The ordering of series is only defined at a single timestamp (unless you want to venture into the territory of integrating over the area under the curve throughout the graph range, which wouldn't always produce great results in the face of spikyness).

On the subject of stacked graphs in general, this post from the uPlot people might be of interest: https://everydayanalytics.ca/2014/08/stacked-area-graphs-are-not-your-friend.html

**Comment by juliusv** [comment]
Closing this as I don't see a good solution here.
