### ISSUE TITLE
Starting prometheus with a very old block causes many empty wal segments.

### ISSUE THREAD

**Issue by krasi-georgiev** [prometheus/prometheus#6359]
By default each compaction processes 2h of data from the head and than reloads the db. At the reload it sets the head mint progressively advancing 2h on every compaction run. On every compaction run a new segment is created which is empty. 
So starting Prometheus with a block that is 10d old will cause around 300 compaction with a new segment for each run and a checkpoint when it accumulates 4 segments.

Need to revisit how is the head min time set when running the compaction and reloading the db.

I think the  solution should be to set the head min time to the first sample in the wal when opening the db of if the wal doesn't exist should set the head mint to the first appended sample and the right place for this should be when reloading the DB.

**Comment by cstyan** [comment]
@krasi-georgiev I added the logic to always create a new segment, so I'd like to have a go at fixing this. Do you have any logs from when you've seen this happen? The segment creation should only happen if there was an error in `db.head.Init`, in which case we call `wlog.Repair` which has the logic to always create a new segment.

**Comment by krasi-georgiev** [comment]
like I said just create a block that is a year or few months old and you will replicate it.

**Comment by codesome** [comment]
> I think the solution should be to set the head min time to the first sample in the wal when opening the db of if the wal doesn't exist should set the head mint to the first appended sample and the right place for this should be when reloading the DB.

This sounds like the right thing to do as after recovery and before any append, the `Head.MinTime()` should return the min time of the head. `initAppender` already takes care of setting it to the timestamp of the first sample if nothing is recovered from WAL.

**Comment by Transwert** [comment]
Hey guys,  is anybody working on this issue,  and if they are, can I join as well, 
And also can some put pointers as well for correct direction, ( along a little-bit briefing about issue as well ).

**Comment by codesome** [comment]
@Transwert go ahead with the fix.
Krasi mentioned 1 possible solution above which can be attempted. Reiterating it:
* Set the head min time to the first sample in the wal when opening the db
* If the wal doesn't exist should set the head mint to the first appended sample and the right place for this should be when reloading the DB.
    * For this point, if empty WAL files get created even before the first sample append, we could set it to the current time and then set it to first sample timestamp when it comes.

Pointers: `loadWAL` and sample appending logic in `tsdb/head.go`. Let me know if you need any help.

**Comment by codesome** [comment]
More information here:
It's not just an old block, it also happens if the head has very old data (a big gap between Prometheus coming down and starting again).

The fix for this particular case is not during startup but after head compaction (so, 2 different fixes). I am looking at setting mint properly after head compaction right now.

**Comment by codesome** [comment]
It was fixed in https://github.com/prometheus/prometheus/pull/8067/
