### ISSUE TITLE
hope to support environment variable for prometheus config

### ISSUE THREAD

**Issue by mojo-zd** [prometheus/prometheus#6376]
## Proposal
*i'd like to use environment fill prometheus config, but current not support.*
*Use Case*
use `pod-name` to fill the external_label

**Comment by brian-brazil** [comment]
Dupe of #2357.

**Comment by roidelapluie** [comment]
@mojo-zd   Starting Prometheus 2.27, we will be able to substitute env variables in external labels if you use `--enable-feature=expand-external-labels`

This can be tested  with the `main` docker image.
