### ISSUE TITLE
Flush Head chunks to disk

### ISSUE THREAD

**Issue by codesome** [prometheus/prometheus#6377]
The idea is to flush the head chunks to disk as soon as it is full and use it for the following purposes

1. mmap the flushed chunks in the Head instead of holding it in the memory, hence reducing the memory footprint of Head
2. Consider those chunks as checkpoints and process WAL accordingly, hence reducing the WAL replay time heavily

I had attempted checkpointing the chunks and replaying it [here](https://github.com/prometheus/prometheus/pull/6059), but the idea has evolved since then (as described above).

I will come up with a design doc to comment on in the coming weeks.

/cc @brancz @krasi-georgiev

Edit: The high-level design doc https://docs.google.com/document/d/184urkLQnM7rqLmGvS66I15jU2pyPk_qwd8v_qDlXczo/edit?usp=sharing

**Comment by brian-brazil** [comment]
The completed chunks aren't sufficient as a checkpoint, you'd also need to checkpoint all non-completed chunks. You can then replay the WAL from only that checkpoint - after loading in all the completed chunks.

**Comment by codesome** [comment]
Yes, in my previous attempt I was writing all the chunks (complete and incomplete). But in this case (initial idea), where we write out the chunks in real-time when they are complete (and not like a checkpoint exactly), writing incomplete chunks would be rather expensive to mmap (but can be done only for the replay purpose). I will keep this in mind when working on the design doc, thanks!

**Comment by brian-brazil** [comment]
And we'd still have the complete chunks via mmap hopefully, which would make them off-heap and save RAM.

**Comment by codesome** [comment]
Yes, that's the plan

**Comment by codesome** [comment]
I have jotted down some high-level ideas in this doc https://docs.google.com/document/d/184urkLQnM7rqLmGvS66I15jU2pyPk_qwd8v_qDlXczo/edit?usp=sharing

**Comment by codesome** [comment]
I was looking at the replay part of this work (work going on in this branch https://github.com/codesome/prometheus/tree/mmap-chunks) and I feel the need to change the format of samples record in Head (basically add another one).

If we are to decode the samples record and perform appends only to find out the all the samples are out of order after having the m-mapped chunks already restored, then it is going to be a lot of waste of time.

To take advantage of Head chunks on disk for replay speed, I wish to add uncompressed maxt to all samples record (max time among all the samples in that record), so that we can skip the record whose maxt is less than the smallest maxt among all the series currently loaded.

More ideas are welcome.

**Comment by codesome** [comment]
I have another idea. While we are flushing chunk to the disk whenever we complete a chunk, we can encode the segment number and the byte at which the WAL exists during flushing along with the chunk.

This way, when replaying the WAL, we can get the max WAL reference from all the series, and start replaying WAL from the min among them.

**Comment by brian-brazil** [comment]
> This way, when replaying the WAL, we can get the max WAL reference from all the series, and start replaying WAL from the min among them.

Given churn, I'd expect this to require always doing everything.

**Comment by codesome** [comment]
Good point, didn't think about churn :(
