### ISSUE TITLE
prometheus restart always

### ISSUE THREAD

**Issue by HarveyJie** [prometheus/prometheus#6383]
`Nov 27 02:03:12 prometheus-1 systemd[1]: Unit prometheus.service entered failed state.
Nov 27 02:03:12 prometheus-1 systemd[1]: prometheus.service failed.
Nov 27 02:03:18 prometheus-1 systemd[1]: prometheus.service holdoff time over, scheduling restart.
Nov 27 02:03:18 prometheus-1 systemd[1]: Stopped Prometheus Server.
Nov 27 02:03:18 prometheus-1 systemd[1]: Started Prometheus Server.`

**Comment by HarveyJie** [comment]
> runtime: out of memory

`Nov 27 12:44:24 localhost prometheus: fatal error: runtime: out of memory
Nov 27 12:44:24 localhost prometheus: runtime stack:
Nov 27 12:44:24 localhost prometheus: runtime.throw(0x2460080, 0x16)
Nov 27 12:44:24 localhost prometheus: /usr/local/go/src/runtime/panic.go:774 +0x72
Nov 27 12:44:24 localhost prometheus: runtime.sysMap(0xc2fc000000, 0x2c000000, 0x3da6878)
Nov 27 12:44:24 localhost prometheus: /usr/local/go/src/runtime/mem_linux.go:169 +0xc5
Nov 27 12:44:24 localhost prometheus: runtime.(*mheap).sysAlloc(0x3d8df00, 0x2b3d4000, 0x0, 0x0)
Nov 27 12:44:24 localhost prometheus: /usr/local/go/src/runtime/malloc.go:701 +0x1cd
Nov 27 12:44:24 localhost prometheus: runtime.(*mheap).grow(0x3d8df00, 0x159ea, 0xffffffff)
Nov 27 12:44:24 localhost prometheus: /usr/local/go/src/runtime/mheap.go:1255 +0xa3
Nov 27 12:44:24 localhost prometheus: runtime.(*mheap).allocSpanLocked(0x3d8df00, 0x159ea, 0x3da6888, 0x42cb7c)
Nov 27 12:44:24 localhost prometheus: /usr/local/go/src/runtime/mheap.go:1170 +0x266
Nov 27 12:44:24 localhost prometheus: runtime.(*mheap).alloc_m(0x3d8df00, 0x159ea, 0x101, 0xc0000fdf18)`

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by HarveyJie** [comment]
I  am chinese user, can not open the url .haha
