### ISSUE TITLE
React UI: Create /rules page

### ISSUE THREAD

**Issue by juliusv** [prometheus/prometheus#6385]
The React UI is still missing the [/rules](http://demo.robustperception.io:9090/rules) page - this still needs to be implemented (and server-side APIs extended as necessary).

**Comment by Harkishen-Singh** [comment]
@juliusv I will like to take up this.

**Comment by boyskila** [comment]
@Harkishen-Singh are you still interested in working on this?

**Comment by Harkishen-Singh** [comment]
@boyskila yes sure, I am still interested. I am in the middle of academic exams so got delayed. I will do ASAP.
Thanks.

**Comment by juliusv** [comment]
In case @boyskila would want to work on it right now, that shouldn't block you IMO if work hasn't started on it and it's still blocked on @Harkishen-Singh's side for some time.
