### ISSUE TITLE
remote write to opentsdb error

### ISSUE THREAD

**Issue by majun9129** [prometheus/prometheus#6392]
I'm using prometheus with remote storage of openTSDB, but prometheus failed to send metrics.

**Environment**
prometheus version:  prometheus-2.10.0.windows-amd64
opentsdb version: 2.4.0

**Config**
---prometheus.yaml----
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']
remote_write:
  - url: 'http://127.0.0.1:9201/write'

---adapter---
remote_storage_adapter.exe --opentsdb-url=http://172.26.94.128:4399/

---opentsdb---
tsd.network.port = 4399
tsd.http.staticroot = ./staticroot
tsd.http.cachedir = /tmp/openTSDB_temp
tsd.core.auto_create_metrics = true
tsd.core.meta.enable_realtime_ts = true
tsd.storage.hbase.zk_quorum = zk01,zk02,zk03

* *Logs:**
promehtus:  No error

adapter: 
level=warn ts=2019-11-29T06:23:11.047Z caller=main.go:330 msg="Error sending samples to remote storage" err="invalid character '<' looking for beginning of value" storage=opentsdb num_samples=100
level=warn ts=2019-11-29T06:23:11.182Z caller=main.go:330 msg="Error sending samples to remote storage" err="invalid character '<' looking for beginning of value" storage=opentsdb num_samples=100
level=warn ts=2019-11-29T06:23:11.328Z caller=main.go:330 msg="Error sending samples to remote storage" err="invalid character '<' looking for beginning of value" storage=opentsdb num_samples=100
level=warn ts=2019-11-29T06:23:11.544Z caller=main.go:330 msg="Error sending samples to remote storage" err="invalid character '<' looking for beginning of value" storage=opentsdb num_samples=100

opentsdb:
2019-11-29 14:23:11,454 WARN  [OpenTSDB I/O Worker #1] HttpQuery: [id: 0x108d2271, /172.26.0.2:58546 => /172.26.94.128:4399] Bad Request on /api/put: Chunked request not supported.
2019-11-29 14:23:11,455 INFO  [OpenTSDB I/O Worker #1] HttpQuery: [id: 0x108d2271, /172.26.0.2:58546 => /172.26.94.128:4399] HTTP /api/put done in 0ms
2019-11-29 14:23:11,455 ERROR [OpenTSDB I/O Worker #1] RpcHandler: [id: 0x108d2271, /172.26.0.2:58546 => /172.26.94.128:4399] Unexpected message type class org.jboss.netty.handler.codec.http.DefaultHttpChunk: org.jboss.netty.handler.codec.http.DefaultHttpChunk@b0bbee9
2019-11-29 14:23:11,455 ERROR [OpenTSDB I/O Worker #1] RpcHandler: [id: 0x108d2271, /172.26.0.2:58546 => /172.26.94.128:4399] Unexpected message type class org.jboss.netty.handler.codec.http.DefaultHttpChunk: org.jboss.netty.handler.codec.http.DefaultHttpChunk@33471949
2019-11-29 14:23:11,463 ERROR [OpenTSDB I/O Worker #1] RpcHandler: [id: 0x108d2271, /172.26.0.2:58546 => /172.26.94.128:4399] Unexpected message type class org.jboss.netty.handler.codec.http.DefaultHttpChunk: org.jboss.netty.handler.codec.http.DefaultHttpChunk@20bacdd9
2019-11-29 14:23:11,551 ERROR [OpenTSDB I/O Worker #1] RpcHandler: [id: 0x108d2271, /172.26.0.2:58546 => /172.26.94.128:4399] Unexpected message type class org.jboss.netty.handler.codec.http.DefaultHttpChunk: org.jboss.netty.handler.codec.http.DefaultHttpChunk@70121620
2019-11-29 14:23:11,582 ERROR [OpenTSDB I/O Worker #1] RpcHandler: [id: 0x108d2271, /172.26.0.2:58546 => /172.26.94.128:4399] Unexpected message type class org.jboss.netty.handler.codec.http.DefaultHttpChunk: org.jboss.netty.handler.codec.http.DefaultHttpChunk@2638123d
2019-11-29 14:23:11,592 ERROR [OpenTSDB I/O Worker #1] RpcHandler: [id: 0x108d2271, /172.26.0.2:58546 => /172.26.94.128:4399] Unexpected message type class org.jboss.netty.handler.codec.http.DefaultHttpChunk: org.jboss.netty.handler.codec.http.DefaultHttpChunk@2d3edae2
2019-11-29 14:23:11,592 ERROR [OpenTSDB I/O Worker #1] RpcHandler: [id: 0x108d2271, /172.26.0.2:58546 => /172.26.94.128:4399] Unexpected message type class org.jboss.netty.handler.codec.http.HttpChunk$1: org.jboss.netty.handler.codec.http.HttpChunk$1@2534823c
2019-11-29 14:23:16,275 INFO  [OpenTSDB I/O Worker #1] ConnectionManager: [id: 0x108d2271, /172.26.0.2:58546 :> /172.26.94.128:4399] DISCONNECTED

prometheus and remote-storage-adapter running in windown10, and openTSDB running in standalone server.

**Comment by liguozhong** [comment]
Environment
prometheus version: prometheus-2.10.0.windows-amd64
opentsdb version: 2.4.0


remote_storage_adapter version == ？

**Comment by liguozhong** [comment]
level=warn ts=2019-11-29T06:23:11.544Z caller=main.go:330 msg="Error sending samples to remote storage" err="invalid character '<' looking for beginning of value" storage=opentsdb num_samples=100


url error.
![image](https://user-images.githubusercontent.com/9583245/70067010-9acf4800-1628-11ea-9f12-78dff6c5fa44.png)

**Comment by liguozhong** [comment]
global:
  scrape_interval:     15s
  evaluation_interval: 30s

scrape_configs:
  job_name: 'prometheus'
      static_configs: targets: ['localhost:9090']
remote_write:
  - url: 'http://127.0.0.1:9201/write'

**Comment by liguozhong** [comment]
opentsdb 

public final class net.opentsdb.core.Tags
  /**
   * Ensures that a given string is a valid metric name or tag name/value.
   * @param what A human readable description of what's being validated.
   * @param s The string to validate.
   * @throws IllegalArgumentException if the string isn't valid.
   */
  public static void validateString(final String what, final String s) {
    if (s == null) {
      throw new IllegalArgumentException("Invalid " + what + ": null");
    } else if ("".equals(s)) {
      throw new IllegalArgumentException("Invalid " + what + ": empty string");
    }
    final int n = s.length();
    for (int i = 0; i < n; i++) {
      final char c = s.charAt(i);
      if (!(('a' <= c && c <= 'z') || ('A' <= c && c <= 'Z') 
          || ('0' <= c && c <= '9') || c == '-' || c == '_' || c == '.' 
          || c == '/' || Character.isLetter(c) || isAllowSpecialChars(c))) {
        throw new IllegalArgumentException("Invalid " + what
            + " (\"" + s + "\"): illegal character: " + c);
      }
    }
  }

**Comment by liguozhong** [comment]
opentsdb 

public final class net.opentsdb.core.TSDB

    if (config.getString("tsd.core.tag.allow_specialchars") != null) {
      Tags.setAllowSpecialChars(config.getString("tsd.core.tag.allow_specialchars"));
    }

**Comment by liguozhong** [comment]
tsd.core.tag.allow_specialchars (2.3) | String | Optional | An optional list of ASCII characters allowed in metric names, tag names and tag keys above those already allowed by TSDB. Spaces are allowed.

**Comment by liguozhong** [comment]
tsd.core.tag.allow_specialchars = "<>, ;[]:/@"

You can try to add this option in opentsdb.conf

**Comment by majun9129** [comment]
hi. @liguozhong 
Sorry, the format is not correct because of copy and paste.
remote_storage_adapter
Use https://github.com/prometheus/prometheus/tree/master/documentation/examples/remote'storage/remote'storage'adapte compiled without version number.
Then I tried to configure the parameters you provided, but it didn't seem to work. 
I'll follow your advice and read the opentsdb documentation again. Thank you.

**Comment by majun9129** [comment]
I added the following parameters：
tsd.core.tag.allow_specialchars = "<>,;[]:/@"
tsd.http.request.enable_chunked = true
tsd.http.request.max_chunk = 65535
tsd.storage.max_tags = 100
Opentsdb can already find some data.
But remote_storage_adapterstill reports the same error.

adapter:
level=warn ts=2019-11-29T06:23:11.047Z caller=main.go:330 msg="Error sending samples to remote storage" err="invalid character '<' looking for beginning of value" storage=opentsdb num_samples=100
level=warn ts=2019-11-29T06:23:11.182Z caller=main.go:330 msg="Error sending samples to remote storage" err="invalid character '<' looking for beginning of value" storage=opentsdb num_samples=100
level=warn ts=2019-11-29T06:23:11.328Z caller=main.go:330 msg="Error sending samples to remote storage" err="invalid character '<' looking for beginning of value" storage=opentsdb num_samples=100
level=warn ts=2019-11-29T06:23:11.544Z caller=main.go:330 msg="Error sending samples to remote storage" err="invalid character '<' looking for beginning of value" storage=opentsdb num_samples=10

**Comment by csmarchbanks** [comment]
The "invalid character '<' looking for beginning of value" message is due to your open tsdb instance returning what is likely an html page rather than the expected JSON response. The adapter can be updated to return a better error in this case, but it is likely not your root issue.

The log messages around chunked requests for opentsdb are more interesting, a brief search shows that enabling `tsd.http.request.enable_chunked = true` may help, or you could lower the number of samples sent per payload. Reference: https://stackoverflow.com/questions/27841071/what-is-a-chunked-request-in-opentsdb

**Comment by csmarchbanks** [comment]
Are there more log messages from opentsdb since you set the following values?
```
tsd.http.request.enable_chunked = true
tsd.http.request.max_chunk = 65535
```

**Comment by majun9129** [comment]
Hello, thank you for your reply.
I
Is there any problem with my adapter's configuration startup mode?
Opentsdb's listening port is 4399

My Prometheus has a lot of labels for each metric. In this case, is it not appropriate to store them in opentsdb?

In addition, after I added related parameters, opentsdb has no error log. However, there are warn logs, as follows:

2019-12-16 16:27:34,045 WARN [OpenTSDB I/O Worker #1] HttpQuery: [id: 0xf8e70205, /172.26.5.129:54378 => /172.26.94.128:4399] Bad Request on /api/put: No datapoints found in content
Thank you.

**Comment by csmarchbanks** [comment]
> Is there any problem with my adapter's configuration startup mode?

I do not see any obvious problems with your adapter's startup mode.

> My Prometheus has a lot of labels for each metric. In this case, is it not appropriate to store them in opentsdb?

I do not know the internals of opentsdb very well. Perhaps ask a question on their [mailing-list](https://groups.google.com/forum/#!forum/opentsdb) with some details around the amount of data you are sending?

Now that there are no errors are you still missing data you expect to see in opentsdb?

**Comment by majun9129** [comment]
Thank you for your reply.
The problem has been solved.
