### ISSUE TITLE
Proposal: Add API endpoint to retrieve metadata by metric name

### ISSUE THREAD

**Issue by beorn7** [prometheus/prometheus#6395]
_Credits and notes: The below has mostly been written by @gotjosh. He's currently on vacation. That's why I (@beorn7) am filing this now. I helped with the draft, and we also got input from @davkal (Grafana), @slrtbtfs ([LSP implementation for PromQL](https://github.com/slrtbtfs/promql-lsp)) and @jkohen and @StevenYCChou ([Stackdriver Prometheus sidecar](https://github.com/Stackdriver/stackdriver-prometheus-sidecar)). Note, however, that the below mostly caters for the Grafana and LSP use case, while the Stackdriver use case needed more invasive changes to provide metadata from targets that are not active anymore. This more or less historical data would also help Grafana, but is out of scope for this proposal. This proposal is a fairly lightweight (and hopefully uncontroversial) addition to serve as an intermediate solution until we get full metadata support, which realistically I only expect in Prometheus v3._

# Context and motivation

At the moment of writing, Prometheus users and integrations (e.g. Grafana) [make use](https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/prometheus/metric_find_query.ts#L93) of `/api/v1/label/__name__/values` as a way to expose all the metric names that Prometheus has scraped.

Prometheus currently offers a way to obtain metadata (type, help, etc) for a given metric via the `/api/v1/targets/metadata` endpoint. This metadata helps power features such as query hinting, where users are suggested to use `rate` on counters.

Often, integrations are unhappy with the current state of the API endpoint. Both Grafana and the PromQL LSP would like to obtain metadata in a situation where the target is not relevant or even unknown – in which case the endpoint has to be queried for _all_ targets, resulting in a possibly very large payload, blown up by a factor equal to the number of targets exposing the requested metric name (possibly thousands). Without the metadata, integrations have to fall back to  heuristics to determine it e.g. [detect monotonicity](https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/prometheus/query_hints.ts#L29) to infer it’s a counter.

# Challenges

## `/api/v1/targets/metadata` is per target

The current metadata API responds with the information per target. Certainly, the current API was implemented [with a lot of discussion and scrutiny applied to it](https://github.com/prometheus/prometheus/pull/4183). In fact, it can be seen used as part of [Stackdriver’s Prometheus sidecar](https://github.com/Stackdriver/stackdriver-prometheus-sidecar/blob/e9a90d80a1aea5ce7975bdb1a42f6dce4b63934a/metadata/cache.go#L47) with the target information. 

However, Grafana and the PromQL LSP tend to follow different semantics than what the endpoint was originally conceived for, by querying metadata globally (independent of the target) as opposed to per target. As described above, querying the data for all targets creates a huge blow-up of redundant data. The client then has to collapse the data between all the targets, where most of the metadata is the same, but occasionally, the metadata becomes ambiguous when clients try to collapse the information from different targets e.g. a metric having a type of “gauge” in one instance and “counter” in another, or (more commonly) the help strings differ.

The previous examples serve as an indication that there are different use cases the work proposed could serve, namely Grafana tool tips and the PromQL LSP implementation.

## `/api/v1/labels/{name}/values` responds with primitives instead of objects

A possible way to serve metadata for metric names would be to enrich the response of the label values endpoint with the metadata but the fact that it currently only returns primitives (strings) in the response would make it a breaking change of the current stable API. Also, Prometheus currently doesn’t persist metadata, so we could only serve the metadata for metrics still exposed by active targets, while the label values endpoint takes into account all data in the TSDB.

# Proposal

We propose the introduction of two new endpoints to obtain metadata by series name as opposed to targets. Safe to say, that we’re *not* proposing the introduction of any additional in-RAM data structures. The response to these endpoints can be assembled by sweeping the existing metadata cache in the scrape-pool. (Essentially, we are moving the collapsing of the redundant metadata from the client into the Prometheus server, thereby saving marshalling and unmarshalling of the blown-up data and its transfer over the wire. Even for the Prometheus server, it will probably be a net cost-saving compared to calling the existing targets/metadata endpoint for all targets.)

The output we propose is best illustrated with examples:

For the envelope, we still follow the same [Prometheus format](https://prometheus.io/docs/prometheus/latest/querying/api/#format-overview). The objects embedded within data follow this spec:

## api/v1/metadata

```bash
curl -G http://localhost:9090/api/v1/metadata --data-urlencode ‘limit=10’ | jq
{
  “status”: “success”,
  “data”: [
    {
      “promhttp_metric_handler_requests_in_flight”: [{
        “type”: ”gauge”,
        “help”: ”Current number of scrapes being served.”,
        “unit”: ”,”
      }],
    },
    {
      “go_goroutines”: [
        {
          “type”: ”gauge”,
          “help”: ”Number of bytes used for mcache structures obtained from system.”,
          “unit”: ””,
        },
        {
          “type”: ”gauge”,
          “help”: ”A great number of of bytes used for mcache structures obtained from system.”,
          “unit”: ””,
        }
      ],
    },
    {
      “go_memstats_mcache_sys_bytes”: [{
        “type”: ”gauge”,
        “help”: ”Number of bytes used for mcache structures obtained from system.”,
        “unit”: ””,
      }]
    }
  ]
}
```

## api/v1/metadata/{name} 

```bash
curl -G http://localhost:9090/api/v1/metadata/go_goroutines |  jq
{
  “status”: “success”,
  “data”: {
    “go_goroutines”: [
      {
        “type”: ”gauge”,
        “help”: ”Number of bytes used for mcache structures obtained from system.”,
        “unit”: ””,
      },
      {
        “type”: ”gauge”,
        “help”: ”A great number of of bytes used for mcache structures obtained from system.”,
        “unit”: ””,
      }
    ]
  }
}
```

We believe that this proposed format is better than the alternative of fetching metadata for _all_ targets from the existing API and let the client collapse it. 

In the response, if different targets provide different versions of metadata for the same metric name, they will be listed as additional objects inside the array of metadata. If the metadata is the same for a given metric name across all targets, the array will only have a single element.

We believe this to be sufficient for the use-case(s) described above. The exposure of the data in this format will make it feasible for integrations to consume all metrics when a target is not known (or relevant) and not have the payload linearly increase with each target added.

At this point, we would love to hear more opinions on it.

**Comment by beorn7** [comment]
The plan is that @gotjosh will work on this, but issues can only assigned to collaborators in the GH org. I'll proxy-assign this to myself.

**Comment by brian-brazil** [comment]
My general opinion is that any metadata endpoints should be designed primarily to cater to Grafana-type needs, and the current one doesn't seem fit for purpose in this regard as you note. This is an experimental API, and I'd tend towards making existing APIs better rather than spawning new ones where that makes sense.

I also believe that for the vast majority of use cases, current data is quite sufficient. It's unlikely that you'd be doing exploration on data that's no longer exported anywhere.

> Safe to say, that we’re not proposing the introduction of any additional in-RAM data structures.

We may want to consider this just on efficiency grounds, to reduce overall RAM/CPU involved. Though that's more an optimisation.

> This proposal is a fairly lightweight (and hopefully uncontroversial) addition to serve as an intermediate solution until we get full metadata support, which realistically I only expect in Prometheus v3.

As planned there'll be nothing major changing whenever v3 comes up, just a selection of minor cleanups/deprecation. So anything we're thinking on doing with metadata we should be able to talk about now.

**Comment by beorn7** [comment]
> My general opinion is that any metadata endpoints should be designed primarily to cater to Grafana-type needs, and the current one doesn't seem fit for purpose in this regard as you note. This is an experimental API, and I'd tend towards making existing APIs better rather than spawning new ones where that makes sense.

The current API makes sense if you know about the target, because it breaks ambiguity in a clean way. Plus, Stackdriver is using the current API for their Prometheus sidecar. We should not break that usage pattern in general and the Stackdriver usage pattern in particular.

Once we have proper metadata support, we can get rid of all the current API, presumably with v3.

> I also believe that for the vast majority of use cases, current data is quite sufficient. It's unlikely that you'd be doing exploration on data that's no longer exported anywhere.

I disagree. But we don't need to discuss it now. Just a point for consistency: All the other autocompletion in Grafana is based on historical data, sometimes even precisely for the time range displayed.

> As planned there'll be nothing major changing whenever v3 comes up, just a selection of minor cleanups/deprecation.

This issue is definitely not the right place to discuss v3 plans. But I have to say I wasn't aware of ony concrete plans for v3. The only thing I know is the item on the Barcelona dev summit. I haven't understood that as a comprehensive list of things to tackle in v3, more like a brainstorming of things we can clean up whenever we decide to do a v3. I'm happy to give my input for v3 if we create a doc or issue for it.

**Comment by brian-brazil** [comment]
> But we don't need to discuss it now.

Indeed. I believe we're best letting the UI stuff be figured out based on fresh in-memory data as that's easier to experiment with, and then when use cases are more concrete we can see what backend changes are practical once we've a better idea of access patterns.

> I haven't understood that as a comprehensive list of things to tackle in v3

Noone was expecting any major changes, so what we are left with is a (partial) list of things we'd like to cleanup but don't want to/can't break in v2. That's not to say that something mightn't arise, but nothing seems to be on the cards currently. Probably something for whenever the next dev summit is (Amsterdam?).

**Comment by beorn7** [comment]
I have a lot on the cards for v3. But as said, not here in this issue…

**Comment by gotjosh** [comment]
Hello everyone 👋,

For the sake of moving forward, do we agree with creating a new API?

> This is an experimental API, and I'd tend towards making existing APIs better rather than spawning new ones where that makes sense.

As @beorn7 pointed out, we have current users of the existing API (and it makes sense in their specific case) albeit as @brian-brazil states it is [marked as experimental](https://prometheus.io/docs/prometheus/latest/querying/api/#querying-target-metadata). The proposal approaches the change with caution, and _specifically_ avoids any breaking change - attempting to improve an existing one would effectively send us back to the drawing board.

**Comment by brian-brazil** [comment]
If it doesn't make sense to build off what we have, then new endpoints it is.

**Comment by beorn7** [comment]
That's done, isn't it?

**Comment by brian-brazil** [comment]
I'm not sure, we have something to dump everything but not do a lookup by metric name.

**Comment by gotjosh** [comment]
Yeah, I have one more coming up shortly.

**Comment by beorn7** [comment]
You're right. Missed that…

**Comment by beorn7** [comment]
Now it's done for real.

Note that `api/v1/metadata/{name}` has been implemented differently (as `api/v1/metadata?metric={name}`).

**Comment by gotjosh** [comment]
cc: @slrtbtfs

**Comment by slrtbtfs** [comment]
Great, thanks.
