### ISSUE TITLE
Provide default URL scheme for  promtool server addresses

### ISSUE THREAD

**Issue by grobie** [prometheus/prometheus#6397]
## Proposal
**Use case. Why is this important?**

```console
$ promtool query instant prometheus.example.org prometheus_build_info
prometheus_build_info{version="future", ...}
```

Ease of CLI usage. Similar to curl, it would be nice to handle server addresses without an explicit URL scheme gracefully. From a security perspective it would be nice to try `https` first and falling back to `http` otherwise.

*“Nice to have” is not a good use case. :)*

Alright, sorry. Gonna try regardless :upside_down_face:

**Comment by roidelapluie** [comment]
this is super weird.

when to fall back to http? when tcp says no? when certificate is not recognized? how does the user know which proto was picked?

**Comment by brian-brazil** [comment]
Yeah, http is what is expected here with no attempts to fallback.

**Comment by AdaephonBen** [comment]
I'm new to Prometheus and I would like to be assigned to this issue. Just clarifying, all that is required is to prefix http:// to the URL argument if not already present?

**Comment by brian-brazil** [comment]
Yes, add a scheme if there isn't one.

**Comment by peter-turner-hcl** [comment]
Is it free to grab this one? @AdaephonBen

**Comment by AdaephonBen** [comment]
I guess this can be closed, @roidelapluie ?

**Comment by roidelapluie** [comment]
Yes, thanks !
