### ISSUE TITLE
Pushdown aggregator group by through read hint

### ISSUE THREAD

**Issue by garrettlish** [prometheus/prometheus#6400]
## Proposal
Assume we have third-party remote storage, pull raw metrics from third-party remote storage and aggregate them in prometheus might NOT be efficient. It might worth pushdown predicate (aggregators, like min, max, avg, sum, etc.) along with group by information to third-party remote storage through read hint and reduce the data set returned from remote storage.

The proposal is add `groups` array in `ReadHints` struct, and populating it while walk through the syntax tree in promQL engine.

Let me give you a concrete example:
Assume we have one metric, it has 1,000,000 series. If there is a query like `max by (host) (sample_metric)`, third-party remote storage return 1,000,000 series and find maximum value in prometheus rule engine is inefficient. It might be better to pushdown `max` and `host` group by information to third-party remote storage and return few series (host number) to prometheus rule engine.

I had already seen one PR (https://github.com/prometheus/prometheus/pull/4265) which proposing the same thing, however, this PR doesn't handle properly (sample: it doesn't handle aggregate against binary operator result - `max by  (foo)(a - b)`).

Another proposal is passing hacked filters through promQL (like: `sum(abc{HINTS="{'by':'url|app'}"}) by (url, app)`), however, this is hacky and relies on user's promQL input and we cannot make sure it always get proper group by information.

**Comment by brian-brazil** [comment]
We're happy to add any hints that a remote storage finds useful, as long as there's a correct plausible use case for them. Note that you'll also need to indicate if it's a without or by.

**Comment by garrettlish** [comment]
Cool, thanks @brian-brazil. You are correct, we need to indicate it is without or by.

**Comment by bwplotka** [comment]
I think even Thanos project might be interested in this initiative - this allows some way of distributed querying on leafs (:

**Comment by garrettlish** [comment]
close it since https://github.com/prometheus/prometheus/pull/6401 is merged already

**Comment by sudeepknair** [comment]
nice work @garrettlish . Thanks for this feature addition 👍
