### ISSUE TITLE
Matrix selector includes both start and end time data points

### ISSUE THREAD

**Issue by garrettlish** [prometheus/prometheus#6414]
## Proposal
To denote the subsequence of a time series, four conventions are open:
a) `start_time <= t < end_time`
b) `start_time < t <= end_time`
c) `start_time <= t <= end_time`
d) `start_time < t < end_time`

The observation that conventions a) and b) have the advantage that the difference between the bounds as mentioned equals the length of the subsequence is valid.

Current prometheus matrix selector (range vector) is belong to c). It is fine for prometheus native use case. However, third-parity storage (such as SQL) we always round all timestamp to get rid of seconds (metric resolution is 1 minute), and it is belong to b) - `start_time < t <= end_time`. Then it will cause duplicated calculation. 

Sample:
Assume we have the following data points from third-parity storage:
08:00:00, 08:01:00, 08:02:00, 08:03:00

Assume we have query - `metric[3m]` with end time = 08:03:00.
Prometheus matrix selector will return 4 data points (c) rather than first 3 data points (a).

The proposal is change prometheus matrix selector behavior from c) to a), just remove https://github.com/prometheus/prometheus/blob/master/promql/engine.go#L1367-L1377 to avoid putting data point which ts=endtime into the current time range.

Any thoughts, please advise.

**Comment by brian-brazil** [comment]
I'm not seeing an actual problem this is causing here, merely a description of how things work today. What is your issue?

Ultimately if you're writing a remote read endpoint you should be making your endpoint follow the Prometheus data model, rather than attempting to change how all of the rest of the ecosystem works. Any changes here would be breaking, and thus can't happen anytime soon even if they were agreed upon.

**Comment by garrettlish** [comment]
@brian-brazil what I mean is that prometheus is using convention c) `start_time <= t <= end_time` to select subsequence of a sequence (time series), but conventions a) and b) have the following advantages:
1. The difference between the bounds equals the length of the subsequence (an element's subscript equals the number of elements preceding it in the sequence.)
2. For empty range, we don't need to make upper bound < lower bound 
Not sure I clarify it :-)

**Comment by garrettlish** [comment]
FYI: https://www.cs.utexas.edu/users/EWD/ewd08xx/EWD831.PDF

**Comment by brian-brazil** [comment]
I'm still not seeing that problem that this is causing you, this seems more philosophical than technical.

**Comment by garrettlish** [comment]
Assume we have one metric called `metric` and resolution is `1m`, one query like `sum_over_time(metric[3m])` and end time is  `08:03:00`, the result is `4` but it should be `3` from user's perspective (only sum 3 minutes data points).


```
metric 1 08:00:00
metric 1 08:01:00
metric 1 08:02:00
metric 1 08:03:00
```

**Comment by roidelapluie** [comment]
It seems that you are not correct:

instant query gives 3 values:
https://mssavbe.it-solutions.myatos.net/prometheus/mycarenet1/graph?g0.range_input=1h&g0.expr=vector(1)%5B3m%3A1m%5D&g0.tab=1

and sum_over_time returns 3 values too: http://demo.robustperception.io:9090/graph?g0.range_input=1h&g0.expr=sum_over_time(vector(1)%5B3m%3A1m%5D)&g0.tab=1

**Comment by roidelapluie** [comment]
In that regard, Prometheus is already doing b) which is what you want.

**Comment by garrettlish** [comment]
@roidelapluie your query time is incorrect, if you use rounded end time (get rid of seconds), you will get 4 data points.
Sample: http://demo.robustperception.io:9090/graph?g0.range_input=1h&g0.moment_input=2019-12-06%2011%3A59%3A00&g0.expr=vector(1)%5B3m%3A1m%5D&g0.tab=1

**Comment by brian-brazil** [comment]
Prometheus does c) currently, if you find otherwise that's a bug.

I'm still not seeing a problem description.

**Comment by garrettlish** [comment]
@brian-brazil In my previous example, `sum_over_time(metric[3m])` returns the sum of 4 minutes data points, it seems that it is a semantic problem. What do you think?

**Comment by brian-brazil** [comment]
I don't see a semantic problem, that is exactly how PromQL is meant to work.

**Comment by roidelapluie** [comment]
I guess that we can close this here or move it to the mailing list.

**Comment by garrettlish** [comment]
close it as we discussed in above
