### ISSUE TITLE
Kubernetes_sd_config scraping everything

### ISSUE THREAD

**Issue by aviadbi1** [prometheus/prometheus#6416]
## Bug Report
**What did you do?**
Put the prometheus.io scraping annotations on a service and tried to monitor it.
**What did you expect to see?**
A job in prometheus with the targeted service and nothing else.
**What did you see instead? Under which circumstances?**
The prometheus was trying to scrape all the services with or without the annotation "prometheus.io/scrape: true"
In my case some of the services do not need to be scraped, unless they got the right annotations.

**Environment**

* System information:
Running on Kubernetes 1.13

* Prometheus version:
 2.13.1

* Prometheus configuration file:
```
global:
  scrape_interval:     15s

  external_labels:
    monitor: 'example-monitor'

scrape_configs:
- job_name: 'example-metric'
  scrape_interval: 5s

  metrics_path: /metrics/
  scheme: https
  basic_auth:
    username: admin
    password: adminadmin
  tls_config:
    insecure_skip_verify: true


  kubernetes_sd_configs:
  - role: services
  relabel_configs:
  - source_labels: [__meta_kubernetes_service_label_app]
    separator: ;
    regex: config-example
    replacement: $1
    action: keep
  - source_labels: [__meta_kubernetes_endpoint_port_name]
    separator: ;
    regex: https
    replacement: $1
    action: keep
  - source_labels: [__meta_kubernetes_namespace]
    separator: ;
    regex: (.*)
    target_label: namespace
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_pod_name]
    separator: ;
    regex: (.*)
    target_label: pod
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_service_name]
    separator: ;
    regex: (.*)
    target_label: service
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_service_name]
    separator: ;
    regex: (.*)
    target_label: job
    replacement: ${1}
    action: replace
  - separator: ;
    regex: (.*)
    target_label: endpoint
    replacement: https
    action: replace
```
Really struggling to understand what i did wrong.
Thank you !
*

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
