### ISSUE TITLE
`go build` produces binary without web-interface

### ISSUE THREAD

**Issue by yorickvP** [prometheus/prometheus#6421]
## Bug Report
**What did you do?**

Instead of the recommended `make` workflow, we have been doing a `go build` based workflow to build prometheus. Until 2.14, this worked well. However, recently, a `make assets` step was added, that we weren't running.

**What did you expect to see?**

Our usual strategy for upgrading packages: 1. update the source version 2. see if they still build 3. see if they still run. Inadequate testing resulted in this making it through, but it would have been useful to have this fail at the build step. I'm sure `go build` is something anyone not reading the readme might try.

[This has since been fixed](https://github.com/NixOS/nixpkgs/pull/74987) by running `make assets`

**What did you see instead? Under which circumstances?**

A succesful build with a broken binary.

**Environment**

* System information: Linux 5.3.11 x86_64

* Prometheus version: 2.14.0

* [Logs](https://github.com/NixOS/nixpkgs/issues/74844):
```
error reading base template: open templates/_base.html: no such file or directory
```

I propose to implement [something where the code depends on the `go generate` output](https://github.com/Minnozz/go-generate-detect/blob/master/gendetect.go), so that missing `go generate` will result in a broken build with a clear error.

**Comment by roidelapluie** [comment]
Building prometheus from source should give you a fully working engine, which is the case today. 

In addition to be frustrating for the people who are not testing the API, your solution will not help the people who would have built the assets once as they would not be updated upon each go build, but they would not get a warning about it.

The last thing is that I expect to be able to run go build with only golang - no yarn or whatever library needed.

An action point we could do is to make it more clear that the web app is not built-catch the 404 and print a message like : "webapp not found-prometheus built without web app support?"
