### ISSUE TITLE
Prometheus server should have a favicon

### ISSUE THREAD

**Issue by brian-brazil** [prometheus/prometheus#643]
This'd make it easier to pick out among your other tabs

**Comment by njohns-grovo** [comment]
Could the favicon's from [prometheus.github.io](https://github.com/prometheus/prometheus.github.io/tree/master/assets/favicons) be reused here?

**Comment by fabxc** [comment]
Ideally the favicons would be different, so tab-switching is less
guess-work.

**Comment by njohns-grovo** [comment]
@fabxc i see thanks, we just hit the limits of my design capabilities :D  I'll throw this around the office and see if someone else wants to pick it up

**Comment by jimmidyson** [comment]
And if we could get svgs of logos that would be awesome for presentations, etc.

**Comment by RichiH** [comment]
See the PR.

I did the easy thing and negated all icons. As an alternative, we could also:

* have an orange torch with black circle
* have a white torch in an orange circle

On a hunch, I would lean towards giving installations the orange on black and switching http://prometheus.io/ to the secondary favicon, though.

**Comment by RichiH** [comment]
As an aside, step `make docker` on https://circleci.com/gh/prometheus/prometheus/983 does not look fully healthy.

**Comment by jimmidyson** [comment]
How about a yellow flame in the original logo for the server favicon? A lit flame indicating a running server?

**Comment by RichiH** [comment]
You mean a torch without fire for the project, a lit torch for the actual instances? I think I like that.

That would even allow playing with deployment overviews: Have the torch unlit and start lighting while provisioning in the background ;)

**Comment by jimmidyson** [comment]
Now you're getting creative! Love it!

**Comment by juliusv** [comment]
Ha! Just don't depend too much on the existing logo. IMO it's more of a placeholder until we get a "real" one, which is badly needed. Sponsor companies for a logo, anyone? ;)

**Comment by jimmidyson** [comment]
What? I love the logo personally! What's wrong with it?

**Comment by juliusv** [comment]
@jimmidyson It's hard to find the right words because I'm not a designer, but it looks "ok" to me at best, not very professionally designed. It was created as a courtesy by a friend of mine, to whom I'm thankful of course, because we needed *some* logo before launching. But I never really saw it as the logo to keep forever. Also, it looks a bit cringe-worthy at small scales if you don't have a retina display.

**Comment by mdlayher** [comment]
Mind revisiting this one?  Sure would make my bookmarks bar look nicer.  I use just favicons with no text for many of the sites that I commonly visit.

How about using the black and white logo from prometheus.io and keeping the red and white one for the official site?

**Comment by mdlayher** [comment]
This can be closed as of 1.5.0!  Woo!
