### ISSUE TITLE
sum_over_time should use semi-closed range interval

### ISSUE THREAD

**Issue by F4ncyMooN** [prometheus/prometheus#6438]
## Bug Report
**What did you do?**
It seems *_over_time query use double-closed range interval. This would cause wrong query result. 
For example, we have a counter metric with interval 10s, and the following two query produces different results.
```
sum_over_time(irate(counter_metric[20s])[10s:])
vs
irate(counter_metric[20s])
```

**What did you expect to see?**
These two query should produce same result.

**Environment**
all

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by F4ncyMooN** [comment]
This should be a BUG. I'm not asking a prometheus usage question.
subquery produces unexpected result.

```
raw -> metric
irate -> irate(metric[30s])
irate:max_over_time -> max_over_time(irate(metric[30s])[10s:])
```

Time | raw | irate | irate:max_over_time
-- | -- | -- | --
2019-12-09T07:55:50+08:00 | 560302 | 1 | 1
2019-12-09T07:56:00+08:00 | 560311 | 0.9 | 1
2019-12-09T07:56:10+08:00 | 560321 | 1 | 1
2019-12-09T07:56:20+08:00 | 560324 | 0.3 | 1
2019-12-09T07:56:30+08:00 | 560325 | 0.1 | 0.3
2019-12-09T07:56:40+08:00 | 560327 | 0.2 | 0.2
2019-12-09T07:56:50+08:00 | 560336 | 0.9 | 0.9
2019-12-09T07:57:00+08:00 | 560345 | 0.9 | 0.9
2019-12-09T07:57:10+08:00 | 560351 | 0.6 | 0.9

**Comment by brian-brazil** [comment]
I see no bug there.

**Comment by F4ncyMooN** [comment]
Let me explain. 
max_over_time(metric[10s]) means we want to calculate the maximum value **every 10 seconds**.

Suppose we have some data which was collected at exactly the start of every 10 seconds.(2019-12-09T07:55:50.000+08:00, 2019-12-09T07:56:00.000+08:00 for example)
Since the data interval is 10s and we use dual-closed range interval (2019-12-09T07:55:50+08:00 <= t <= 2019-12-09T07:56:00+08:00 for example), we will calculate the max value of two points instead of one for 10s data range.

Time | metric | max_over_time | what I want
-- | -- | -- | --
2019-12-09T07:55:50+08:00 | 1 | 1 | 1
2019-12-09T07:56:00+08:00 | 0.9 | 1 (max of (07:55:50 -> 1, 07:56:00 -> 0.9)) | 0.9
2019-12-09T07:56:10+08:00 | 1 | 1 | 1
2019-12-09T07:56:20+08:00 | 0.3 | 1 | 0.3
2019-12-09T07:56:30+08:00 | 0.1 | 0.3 | 0.1
2019-12-09T07:56:40+08:00 | 0.2 | 0.2 | 0.2
2019-12-09T07:56:50+08:00 | 0.9 | 0.9 | 0.9
2019-12-09T07:57:00+08:00 | 0.9 | 0.9 | 0.9
2019-12-09T07:57:10+08:00 | 0.6 | 0.9 | 0.6

Since prometheus will scatter the scrape time and its precision is ms, so its timestamp may look like 2019-12-09T07:56:40**.123**+08:00 (timestamp is not located in the boundary of every 10s) and will not trigger this issue.

But with subquery, after irate(metric[30s]), data timestamp will be aligned and this bug will be triggered.

**Comment by brian-brazil** [comment]
That's all working as expected. You generally should write your expressions to be resilient to jitter.

**Comment by F4ncyMooN** [comment]
So, sum_over_time will query data from [start, end] is by designed?
Could you explain why you choose this time range instead of (start, end]?

**Comment by brian-brazil** [comment]
That decision happened in the distant past before I was involved in the project, and can't be changed now as it'd be breaking.
