### ISSUE TITLE
Feature: any way with inactive metrics

### ISSUE THREAD

**Issue by Mapteg34** [prometheus/prometheus#6446]
We have gauge, and send data to it.
It works fine, but after time we can have some changes:
* gauge labels changes
* gauge on specific labels not availiable

In first case prometheus create new metric with new labels, but old metric work too, and contains constant invalid data (we dont send it, but prometheus use last catched result).

In second case too: we dont send any new values, but metric work, and contains invalid constant data (last catched result).

If we try use sum, or avg on this gauge - we got invalid results (with invalid metrics). And no way to filter only "actual" values.

Yes, we can use delete_series+clean_tombstones, yes they remove data. But metrics not be removed, and after some time prometheus fill it again with invalid value. And no way to remove it permanently, or mark "invalid"/"inactive", etc...

I attach screenshot after delete_series+clean_tombstones with this problem.

Can you add any way to work with non-actual metrics (may be function to remove it, may be function to filter it, may be any another)?

![Снимок](https://user-images.githubusercontent.com/26138251/70603802-c5b13180-1c10-11ea-87bf-d17ada14b2c6.PNG)

**Comment by simonpasquier** [comment]
Thanks for your report. It looks as if this is actually a question about usage and not development.

To make your question, and all replies, easier to find, we suggest you move this over to our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search. If you prefer more interactive help, join or our [IRC channel](https://webchat.freenode.net/?randomnick=1&channels=prometheus), #prometheus on irc.freenode.net. Please be aware that our IRC channel has no logs, is not searchable, and that people might not answer quickly if they are busy or asleep. If in doubt, you should choose the mailing list.

Once your questions have been answered, please add a short line pointing to relevant replies in case anyone stumbles here via a search engine in the future.
