### ISSUE TITLE
group_left isn't working with multiply exporters

### ISSUE THREAD

**Issue by mr-yaky** [prometheus/prometheus#6451]
Hi @brian-brazil , I saw few issues about `group_*` with a good your comments. Can you take a look on this one, please ? May be you will have some suggestions. 

## Bug Report
I'm trying to add `nodename` label  from `node_uname_info` key to use it with mongodb_mongod_replset_date. Basically I need to fix my grafana dashboard to replace ip with hostname.
So I'm doing following:
```
(up{service="node-metrics-proxy"}) + on(instance) group_left(nodename) (0 * node_uname_info)
```
and it's working properly and I always get `nodename` for `up` key.  
But when I want to get the label from different exporter it says: no data :(
As example:
```
(mongodb_connections) + on(instance) group_left(nodename) (0 * node_uname_info)
```

I guess it should be possible to use it with multiply keys from different exporters.

**Environment**
* Prometheus version:
v2.12.0
* Prometheus operator version:
v0.32.0

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by mr-yaky** [comment]
Ok, understood but it seems like a bug.
Anyway I'll ask on mailing list.
Thank you.

**Comment by mr-yaky** [comment]
If someone will get same problem you can check following post:
https://groups.google.com/forum/#!topic/prometheus-users/Z6M8x1feUuc

it's already solved.
