### ISSUE TITLE
Monitoring excessive pod restarting across the cluster

### ISSUE THREAD

**Issue by DarthVader2409** [prometheus/prometheus#6459]
Hi,
I am trying to monitor excessive pod pre-emption/reschedule across the cluster. Right now, we have a prometheous alert set up that monitors the pod crash looping as shown below.

```
 - name: KubePodCrashLooping
   message: '{{ $labels.namespace }}/{{ $labels.pod }} ({{ $labels.container }})
          is restarting {{ printf "%.2f" $value }} / second'
   severity: medium
   impact: This pod is crashing continuously
   action: Look at the pods logs to find why it is crashing consistently, if that doesn't show any service level issues check Kubelet's logs
   expression: >
          sum(rate(kube_pod_container_status_restarts_total{job="kube-state-metrics"}[15m])) by (namespace, pod)
          * on (namespace, pod) group_left(label_name)
          kube_pod_labels{label_monitoring="roger"} > 0
   for: 1h
```
But we want to monitor it in slight different way. I want to specify a value let say 55, if pods crashloops/restarts more than 55 times, lets say 63 times then I should get an alert saying pod crash looping has increased 15% than usual in specified time period. I did not find a good way to accomplish this in promql. Is this something that can be done?

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
