### ISSUE TITLE
Tests fail on Illumos/Solaris

### ISSUE THREAD

**Issue by olcai** [prometheus/prometheus#646]
I'm trying to run Prometheus under Illumos/Solaris (SmartOS, really), and while it is possible to build the project, two tests fail for me when running make test:

```
=== RUN TestTargetPoolReplaceTargets
--- FAIL: TestTargetPoolReplaceTargets (0.00s)
        targetpool_test.go:162: newTarget2 channel same as oldTarget2's
FAIL
FAIL    _/root/prometheus/retrieval     0.325s
```

```
=== RUN TestLocking
--- FAIL: TestLocking (0.00s)
        flock_test.go:37: File "/tmp/test_flock938114467/LOCK" locked twice.
FAIL
FAIL    _/root/prometheus/storage/local/flock   0.007s
```

I don't quite see why the targetpool_test one fails, but the lock test is more intriguing. I see that there is support for Solaris in `storage/local/flock/flock_solaris.go`, so I'm wondering if there is something in the build setup that makes it build the wrong version.

I'm using go version 1.4.2, with GCC 4.7.3 as the C compiler. Any pointers on why these tests fail and if I can debug them somehow?

**Comment by beorn7** [comment]
That's interesting.

I've copied the flock code from the Go leveldb implementation, but never tried it myself. So it's perfectly possible to be broken on Solaris. I think the TestTargetPoolReplaceTargets test is flaky, anyway. But for the lock it would be interesting to get more insights. No clue where to start the search, though...

**Comment by gfrey** [comment]
From what I understand `fcntl` locks files between processes, not inside a single process.

I only see one use of the `flock.New` where the error reads like "Prometheus already running?". This sounds more like locking between processes and if that is the case, the solaris implementation is working perfectly fine (tested with a simple program that locks a file, sleeps a few seconds and releases the lock, that I started twice in parallel).

**Comment by brian-brazil** [comment]
None of the Prometheus developers use Solaris and this has been sitting here for 2 years, so it's unlikely this will ever get fixed by us. If there is something remaining to be fixed here, a PR would be appreciated.
