### ISSUE TITLE
The rate value is not even accurate

### ISSUE THREAD

**Issue by jixuju** [prometheus/prometheus#6462]
By looking at grafana, we found that there was a spike problem in `sum(rate(haproxy_frontend_bytes_out_total)[1m])` occasionally, as shown in the following figure:
![image](https://user-images.githubusercontent.com/16171790/70856317-ecbf7a00-1f14-11ea-8228-a02e45b3dfcf.png)

Check the network request. The data under the timestamp is abnormal, very large, as shown in the following figure:
![image](https://user-images.githubusercontent.com/16171790/70856271-a0276f00-1f13-11ea-8031-e85125504483.png)

However, through Prometheus verification of the original metrics, the data is smooth and no sudden increase or drop is found, as shown in the following figure:
![image](https://user-images.githubusercontent.com/16171790/70856322-4de74d80-1f15-11ea-85ed-ae7682a88599.png)

The original data value is also inconsistent with the data from the above rate, as shown in the following figure:
![image](https://user-images.githubusercontent.com/16171790/70856331-a3bbf580-1f15-11ea-9c63-8fc9446c231f.png)

**Environment**

* System information:
Linux 3.10.0-862.14.4.el7.x86_64 x86_64

* Prometheus version:
prometheus, version 2.5.0 (branch: master, revision: 5fef62b83aec95dc2f82b3d77927f8534eb3e46e)
  build user:       pgier@pgier-laptop
  build date:       20181107-20:33:26
  go version:       go1.10.4

* Alertmanager version:
alertmanager, version 0.14.0 (branch: HEAD, revision: 30af4d051b37ce817ea7e35b56c57a0e2ec9dbb0)
  build user:       root@prometheus-alertmanager-binary-12-build
  build date:       20180219-15:30:56
  go version:       go1.9

**Comment by brian-brazil** [comment]
There's insufficient information here to indicate bug, this is almost certainly a counter reset. Check with resets().

**Comment by roidelapluie** [comment]
Plus, the first screenshot data probably contains the result of rate() while the second is the raw values, which explains the difference.

Additional note: Using rate[1m] is not recommended unless you have a very low scrape interval(<=15s)

**Comment by roidelapluie** [comment]
Instead of doing a query_range, you can also instant query metric[5m] to see the raw values of your metric. But that will require a more recent version of Prometheus than 2.5.0.
