### ISSUE TITLE
prometheus pod not selecting new configuration

### ISSUE THREAD

**Issue by rajputvishwas** [prometheus/prometheus#6463]
## Bug Report
**What did you do?**
   I have deployed prometheus on openshift origin OKD (3.11) and it is working fine. I have fluentbit which generates prometheus metrics. I want to send these metrics data to prometheus.
fluentbit- prometheus-metircs

http://fluent-bit-myproject.10.65.117.99.nip.io/api/v1/metrics/prometheus

fluentbit_input_records_total{name="disk.0"} 643 1576496362878
fluentbit_input_bytes_total{name="disk.0"} 25123 1576496362878
fluentbit_input_records_total{name="cpu.1"} 3223 1576496362878
fluentbit_input_bytes_total{name="cpu.1"} 3561415 1576496362878
fluentbit_input_records_total{name="mem.2"} 3223 1576496362878
fluentbit_input_bytes_total{name="mem.2"} 286847 1576496362878
fluentbit_input_records_total{name="dummy.3"} 3223 1576496362878
fluentbit_input_bytes_total{name="dummy.3"} 83798 1576496362878
fluentbit_output_proc_records_total{name="es.0"} 10306 1576496362878
fluentbit_output_proc_bytes_total{name="es.0"} 3954743 1576496362878
fluentbit_output_errors_total{name="es.0"} 0 1576496362878
fluentbit_output_retries_total{name="es.0"} 0 1576496362878
fluentbit_output_retries_failed_total{name="es.0"} 0 1576496362878

I am applying new configuration to prometheus via configmap.
 
Prometheus-configuration
===============

global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
    api_version: v1
scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - localhost:9090
- job_name: fluentbit
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /api/v1/metrics/prometheus
  scheme: http
  static_configs:
  - targets:
    - 172.30.138.92:2020
**What did you expect to see?**
   Prometheus should reflect new configuration and starts reading fluentbit metrics.
**What did you see instead? Under which circumstances?**
  Prometheus working on default configuration.
 
**Environment**
oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

* System information:

	insert output of `uname -srm` here

* Prometheus version:

Version | 2.14.0
-- | --
edeb7a44cbf745f1d8be4ea6f215e79e651bfe19
HEAD
root@df2327081015
20191111-14:27:12
go1.13.4

* Alertmanager version:

	insert output of `alertmanager --version` here (if relevant to the issue)

* Prometheus configuration file:

 global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
    api_version: v1
scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - localhost:9090
```





* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```

**Comment by codesome** [comment]
If you have changed the config, you need to hit `/-/reload` API of Prometheus asking it to reload the config (https://github.com/prometheus/prometheus/issues/1572). For more usage questions, please use user mailing list which can be found here https://prometheus.io/community/.

**Comment by rajputvishwas** [comment]
Hi Ganesh,

Thanks for your input but hitting /-/reload is not working.

[cid:image001.jpg@01D5B4C7.973F3050]

I am using OKD(Openshift origin 3.11), so was trying to use config map to overwrite existing configuration.

Thanks,
Vishwas
