### ISSUE TITLE
PromQL: Consider supporting trailing commas in grouping opts

### ISSUE THREAD

**Issue by slrtbtfs** [prometheus/prometheus#6470]
Currently PromQL allows trailing commas in label matchers, but not in the label list of grouping opts.

E.g. `a{b="c",}`,  `a{b="c"}` and `sum (a) by (b)` and are valid PromQL, while `sum (a) by (b,)` is not.

This feels somewhat inconsistent.

It might be worth considering to allow trailing commas in grouping opts, too.

**Comment by brian-brazil** [comment]
This seems reasonable to me.

@tomwilkie any thoughts from the jsonnet side of the house?

**Comment by beorn7** [comment]
Sounds reasonable to me. I can't see how Jsonnet would have a problem with this more relaxed syntax.

**Comment by brian-brazil** [comment]
I can't imagine either, but I could see them appreciating the feature.

**Comment by beorn7** [comment]
Yes, definitely. Let's do it!

**Comment by slrtbtfs** [comment]
Ok, I'll do a PR.

**Comment by slrtbtfs** [comment]
When we're already at it:

We might want to the same thing for functions, too.

**Comment by brian-brazil** [comment]
There's only a small number of functions that take a variable number of arguments, I'm not seeing the need there.

**Comment by slrtbtfs** [comment]
Doing it for functions, too, would make all comma separated lists behave the same, which has some appeal.

**Comment by brian-brazil** [comment]
Functions arguments aren't somewhere where you build up lists of an unknown number of things from disparate sources.

**Comment by slrtbtfs** [comment]
True.

I'm fine with leaving functions in their current state as well.
