### ISSUE TITLE
aggregation is not working, returning "Error executing query: Forbidden"

### ISSUE THREAD

**Issue by arnaudlemaignen** [prometheus/prometheus#6473]
## Bug Report
**What did you do?**
execute the promql formula "avg(avg_over_time(up{job="prometheus"}[2w]))" in grafana or prometheus UI

**What did you expect to see?**
the result "0.999292149292147"

**What did you see instead? Under which circumstances?**
a 403 error in grafana
![image](https://user-images.githubusercontent.com/22667740/71000137-0f02f480-20db-11ea-9290-4b161a1d0af2.png)

an "Error executing query: Forbidden" in prometheus UI
![image](https://user-images.githubusercontent.com/22667740/71000081-f561ad00-20da-11ea-877f-aadcbf5572bc.png)

this issue is happening only with avg, min, max aggregations
for instance the same formula without the avg() is working in both grafana and prom UI
![image](https://user-images.githubusercontent.com/22667740/71000253-44a7dd80-20db-11ea-82fd-dd848cb85f32.png)

even strange thing is that with doing the original query in localhost using the API we get the good result
wget 'http://localhost:9090/api/v1/query?query=avg(avg_over_time(up%7Bjob%3D%22prometheus%22%7D%5B2w%5D))&time=1576575697'

cat query?query\=avg\(avg_over_time\(up\%7Bjob\%3D\%22prometheus\%22\%7D\%5B2w\%5D\)\)\&time\=1576575697
{"status":"success","data":{"resultType":"vector","result":[{"metric":{},"value":[1576575697,"0.999292149292147"]}]}}

**Environment**
Prometheus running as a container in an Openshift Cluster with an NFS PV

* System information:
Linux 3.10.0-1062.el7.x86_64 x86_64

* Prometheus version:
prometheus, version 2.13.0 (branch: HEAD, revision: 6ea4252299f542669aca11860abc2192bdc7bede)
  build user:       root@f30bdad2c3fd
  build date:       20191004-11:25:34
  go version:       go1.13.1

* Logs:
No specific logs

level=info ts=2019-12-17T10:10:54.671Z caller=main.go:332 msg="Starting Prometheus" version="(version=2.13.0, branch=HEAD, revision=6ea4252299f542669aca11860abc2192bdc7bede)"
level=info ts=2019-12-17T10:10:54.672Z caller=main.go:333 build_context="(go=go1.13.1, user=root@f30bdad2c3fd, date=20191004-11:25:34)"
level=info ts=2019-12-17T10:10:54.672Z caller=main.go:334 host_details="(Linux 3.10.0-1062.el7.x86_64 #1 SMP Thu Jul 18 20:25:13 UTC 2019 x86_64 eaa-platform-prometheus-6-m8bhx (none))"
level=info ts=2019-12-17T10:10:54.672Z caller=main.go:335 fd_limits="(soft=1048576, hard=1048576)"
level=info ts=2019-12-17T10:10:54.672Z caller=main.go:336 vm_limits="(soft=unlimited, hard=unlimited)"
level=info ts=2019-12-17T10:10:54.777Z caller=web.go:450 component=web msg="Start listening for connections" address=0.0.0.0:9090
level=info ts=2019-12-17T10:10:54.777Z caller=main.go:657 msg="Starting TSDB ..."
level=info ts=2019-12-17T10:10:54.803Z caller=repair.go:59 component=tsdb msg="found healthy block" mint=1576108800000 maxt=1576130400000 ulid=01DVWNCQ55S2RWHB5VPWTEGVNG
level=info ts=2019-12-17T10:10:54.818Z caller=repair.go:59 component=tsdb msg="found healthy block" mint=1576130400000 maxt=1576152000000 ulid=01DVX9ZQVNSKDWGTYJEFF5BB49
level=info ts=2019-12-17T10:10:54.834Z caller=repair.go:59 component=tsdb msg="found healthy block" mint=1576152000000 maxt=1576173600000 ulid=01DVXYJYW1RV0A6CCXGB9XJS88
level=info ts=2019-12-17T10:10:54.849Z caller=repair.go:59 component=tsdb msg="found healthy block" mint=1576173600000 maxt=1576195200000 ulid=01DVYK63NDNMYT59EG9SEA5B0C
level=info ts=2019-12-17T10:10:54.865Z caller=repair.go:59 component=tsdb msg="found healthy block" mint=1576195200000 maxt=1576216800000 ulid=01DVZ7S9P7BSJW1FDHJB10Q623
level=info ts=2019-12-17T10:10:54.879Z caller=repair.go:59 component=tsdb msg="found healthy block" mint=1576216800000 maxt=1576238400000 ulid=01DVZWCHBXATA3XJQXPP4VZVTE
level=info ts=2019-12-17T10:10:54.893Z caller=repair.go:59 component=tsdb msg="found healthy block" mint=1576238400000 maxt=1576260000000 ulid=01DW0GZP0TH06BVKM3C9CNNEN8
level=info ts=2019-12-17T10:10:54.908Z caller=repair.go:59 component=tsdb msg="found healthy block" mint=1576260000000 maxt=1576281600000 ulid=01DW15JXA00JNM7Y76X1EYH981
level=info ts=2019-12-17T10:10:54.923Z caller=repair.go:59 component=tsdb msg="found healthy block" mint=1576281600000 maxt=1576303200000 ulid=01DW1T60X85EK9R7DDP2D6Z26C
level=info ts=2019-12-17T10:10:54.938Z caller=repair.go:59 component=tsdb msg="found healthy block" mint=1576303200000 maxt=1576324800000 ulid=01DW2ES6YB92T5ZECVPXPVCGHD
level=info ts=2019-12-17T10:10:54.954Z caller=repair.go:59 component=tsdb msg="found healthy block" mint=1576324800000 maxt=1576346400000 ulid=01DW33CB5WWS84C6EJRTBR457H
level=info ts=2019-12-17T10:10:54.969Z caller=repair.go:59 component=tsdb msg="found healthy block" mint=1576346400000 maxt=1576368000000 ulid=01DW3QZKTR8EA572F0Y7J3CNP2
level=info ts=2019-12-17T10:10:54.982Z caller=repair.go:59 component=tsdb msg="found healthy block" mint=1576368000000 maxt=1576389600000 ulid=01DW4CJSPTQHFHYFW1VB443QAS
level=info ts=2019-12-17T10:10:54.998Z caller=repair.go:59 component=tsdb msg="found healthy block" mint=1576389600000 maxt=1576411200000 ulid=01DW515XSBE1B78M34669E1W7E
level=info ts=2019-12-17T10:10:55.012Z caller=repair.go:59 component=tsdb msg="found healthy block" mint=1576411200000 maxt=1576432800000 ulid=01DW5NS3DKV1JHK8BGJ2DC7Y5G
level=info ts=2019-12-17T10:10:55.029Z caller=repair.go:59 component=tsdb msg="found healthy block" mint=1576432800000 maxt=1576454400000 ulid=01DW6ACAKJ6F78FKREK6FWSBD1
level=info ts=2019-12-17T10:10:55.048Z caller=repair.go:59 component=tsdb msg="found healthy block" mint=1576454400000 maxt=1576476000000 ulid=01DW6YZGEEBPS36QEH6MBFRRB7
level=info ts=2019-12-17T10:10:55.064Z caller=repair.go:59 component=tsdb msg="found healthy block" mint=1576476000000 maxt=1576497600000 ulid=01DW7KJPM40W9647RJTPS7FYZF
level=info ts=2019-12-17T10:10:55.080Z caller=repair.go:59 component=tsdb msg="found healthy block" mint=1576497600000 maxt=1576519200000 ulid=01DW885VQ745Z8VT5TRHGPS6Z7
level=info ts=2019-12-17T10:10:55.096Z caller=repair.go:59 component=tsdb msg="found healthy block" mint=1576519200000 maxt=1576540800000 ulid=01DW8WS53NHSB32BDSTMZS6BX6
level=info ts=2019-12-17T10:10:55.108Z caller=repair.go:59 component=tsdb msg="found healthy block" mint=1576562400000 maxt=1576569600000 ulid=01DW9HBTHVPERA38MBH580E59Z
level=info ts=2019-12-17T10:10:55.122Z caller=repair.go:59 component=tsdb msg="found healthy block" mint=1576540800000 maxt=1576562400000 ulid=01DW9HC7248780W2586E53Z1XD
level=info ts=2019-12-17T10:10:56.787Z caller=head.go:512 component=tsdb msg="replaying WAL, this may take awhile"
level=info ts=2019-12-17T10:10:58.667Z caller=head.go:536 component=tsdb msg="WAL checkpoint loaded"
level=info ts=2019-12-17T10:11:03.010Z caller=head.go:560 component=tsdb msg="WAL segment loaded" segment=1089 maxSegment=1100
level=info ts=2019-12-17T10:11:03.101Z caller=head.go:560 component=tsdb msg="WAL segment loaded" segment=1090 maxSegment=1100
level=info ts=2019-12-17T10:11:06.309Z caller=head.go:560 component=tsdb msg="WAL segment loaded" segment=1091 maxSegment=1100
level=info ts=2019-12-17T10:11:06.485Z caller=head.go:560 component=tsdb msg="WAL segment loaded" segment=1092 maxSegment=1100
level=info ts=2019-12-17T10:11:10.112Z caller=head.go:560 component=tsdb msg="WAL segment loaded" segment=1093 maxSegment=1100
level=info ts=2019-12-17T10:11:17.996Z caller=head.go:560 component=tsdb msg="WAL segment loaded" segment=1094 maxSegment=1100
level=info ts=2019-12-17T10:11:21.190Z caller=head.go:560 component=tsdb msg="WAL segment loaded" segment=1095 maxSegment=1100
level=info ts=2019-12-17T10:11:27.787Z caller=head.go:560 component=tsdb msg="WAL segment loaded" segment=1096 maxSegment=1100
level=info ts=2019-12-17T10:11:32.487Z caller=head.go:560 component=tsdb msg="WAL segment loaded" segment=1097 maxSegment=1100
level=info ts=2019-12-17T10:11:41.995Z caller=head.go:560 component=tsdb msg="WAL segment loaded" segment=1098 maxSegment=1100
level=info ts=2019-12-17T10:11:47.387Z caller=head.go:560 component=tsdb msg="WAL segment loaded" segment=1099 maxSegment=1100
level=info ts=2019-12-17T10:11:47.408Z caller=head.go:560 component=tsdb msg="WAL segment loaded" segment=1100 maxSegment=1100
level=info ts=2019-12-17T10:11:47.893Z caller=main.go:672 fs_type=NFS_SUPER_MAGIC
level=info ts=2019-12-17T10:11:47.893Z caller=main.go:673 msg="TSDB started"
level=info ts=2019-12-17T10:11:47.893Z caller=main.go:743 msg="Loading configuration file" filename=/etc/prometheus/prometheus-kubernetes17.yml
level=info ts=2019-12-17T10:11:47.901Z caller=kubernetes.go:192 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2019-12-17T10:11:47.905Z caller=kubernetes.go:192 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2019-12-17T10:11:47.909Z caller=main.go:771 msg="Completed loading of configuration file" filename=/etc/prometheus/prometheus-kubernetes17.yml
level=info ts=2019-12-17T10:11:47.909Z caller=main.go:626 msg="Server is ready to receive web requests."

**Comment by brian-brazil** [comment]
Prometheus can't produce 403s.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
