### ISSUE TITLE
when I use topk(5, my_metrics) to get the sort result; but last parallel data is truncated

### ISSUE THREAD

**Issue by evalizhangli** [prometheus/prometheus#6476]
when I use topk(5, my_metrics) to get the sort result; but last parallel data is truncated; Like: I have a value list(10,9,8,7,6,6,6,5), the topk result is(10,9,8,7,6), but the list(10,9,8,7,6,6,6) was expected. How to deal with this situation？

**Comment by codesome** [comment]
The result looks correct. It returns the top 5 results of the query and not the results that are `>5`. You might be looking for the query `my_metrics > 5`.

GitHub issues are for discussions on development. Please use user mailing lists or `#prometheus` channel on IRC for usage-based questions (can be found here https://prometheus.io/community/).
