### ISSUE TITLE
Proposal: Add SD implementation backed by a gRPC interface for custom providers

### ISSUE THREAD

**Issue by yskopets** [prometheus/prometheus#6484]
# Proposal

* In the context of a Service Mesh, there is always a notion of a Control Plane that coordinates telemetry among other things 
* It would be perfect for overall user experience if a Control Plane could also become a source of scrape targets (specifically, for collecting metrics out of side-car proxies)
* As a way to achieve that, we would like to propose to introduce a gRPC interface for SD that Control Planes could implement
* The choice of gRPC will enable effective server-side streaming of SD information, and it will remove the requirement on users to think upfront about refresh intervals they cannot choose reliably anyway
* There is already a well-defined, battle-tested and widely used protocol for delivering discovery information - [Envoy xDS API](https://www.envoyproxy.io/docs/envoy/latest/api-docs/xds_protocol)
* Based on all the above, we would like to ask if Prometheus community is open for such a contribution

**Comment by roidelapluie** [comment]
From our docs:

> It should not be a brand new SD mechanism, or a variant of an established mechanism. We want to integrate Prometheus with the SD that's already there in your infrastructure, not invent yet more ways to do service discovery. 

Plus, what can't you achieve with the Kubernetes service discovery? I guess what you describe is probably doable with the current kubernetes discovery.

**Comment by roidelapluie** [comment]
I propose to move this to the prometheus-dev mailing list.

**Comment by yskopets** [comment]
Service Mesh is not limited to Kubernetes.

We want to bring the same out-of-the-box experience to Service Meshes running on VMs and in hybrid environments.

**Comment by yskopets** [comment]
I created an identical post on [#prometheus-dev](https://groups.google.com/forum/#!forum/prometheus-developers)

**Comment by bboreham** [comment]
No movement in 5 years; we have [http SD](https://prometheus.io/docs/prometheus/latest/http_sd/); let's close this.
