### ISSUE TITLE
add service type metadata to kubernetes_sd_config service role

### ISSUE THREAD

**Issue by juliantaylor** [prometheus/prometheus#6496]
## Proposal
The metadata of the kubernetes_sd_config service role does not provide the service type, e.g. whether the service is a Nodeport/LoadBalancer or ClusterIP.

The service type can be relevant for the relabeling rules to for example only scrape/probe ClusterIP services with a prometheus inside the cluster, and NodePort/LoadBalancer services with a prometheus outside of the cluster.

The possible options of the type are here:
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.15/#servicespec-v1-core
Nodeport, LoadBalancer, ClusterIP and ExternalName
ExternalName is already provided in its own metadata field (__meta_kubernetes_service_external_name) but there is no metadata for the general type.

**Comment by simonpasquier** [comment]
Closed by #6684
