### ISSUE TITLE
WebUI: 'Try experimental React UI' link ignores "--web.external-url" parameter

### ISSUE THREAD

**Issue by BenediktKampmeyer** [prometheus/prometheus#6497]
## Bug Report
**What did you do?**

I've setup a Prometheus server with nginx as proxy.
Nginx is setup to proxy /prometheus/ to localhost:9090 .
Started Prometheus using parameters:
_--web.external-url https://FQDN/prometheus/ --web.route-prefix=/_. 

Everything works fine except the link _Try experimental React UI_.
This link sends me to https://FQDN/new/* instead of https://FQDN/prometheus/new/*

**Environment**

* System information:

Linux 4.19.80-0-virt x86_64 (alpine)

* Prometheus version:

version 2.14.0 (branch: HEAD, revision: edeb7a44cbf745f1d8be4ea6f215e79e651bfe19)            
  build user:       root@df2327081015                                                          |
  build date:       20191111-14:27:12                                                          |
  go version:       go1.13.4 

* Nginx config string:

location /prometheus/ {
  proxy_pass http://127.0.0.1:9090/;
}

**Comment by roidelapluie** [comment]
Fixed in 2.15.0-rc

**Comment by roidelapluie** [comment]
See #6163

**Comment by BenediktKampmeyer** [comment]
Great, thanks.
Just had a look at the still open issues before submitting this.
