### ISSUE TITLE
Getting error "expected label name, got \"BCLOSE\"" on metrics response after switching to minor version upgrade..

### ISSUE THREAD

**Issue by arun-xandr** [prometheus/prometheus#6499]
**What did you do?**
Upgraded Prometheus from 2.2.1 to 2.9.2

**What did you expect to see?**
Metrics from the system.

**What did you see instead? Under which circumstances?**
expected label name, got \"BCLOSE\"

It seems like there is a change between these two version in the way prometheus specifies
its accept header. 

https://github.com/prometheus/prometheus/blob/v2.2.1/scrape/scrape.go#L433

https://github.com/prometheus/prometheus/blob/v2.9.2/scrape/scrape.go#L525

In 2.2.1 it only recognizes "text/plain" but in 2.9.2 it recognizes both "text/plain" and "application/openmetrics-text"

In the response header the Jersey java client send the first content-type header it sees in the request header, so in the 2.2.1 version it sends back "text/plain" and all is fine but in 2.9.2 it sends content-type as "application/openmetrics-text" but with legacy content body (with extra ',') which fails parsing on prometheus side as expected.
 
I was able to fix it on the app side by explicitly setting the content-type as "text/plain" and it fixed the issue. But given the version change was MINOR I would have expected no change to be done on the client side when I migrated from 2.2.1 to 2.9.2.

One way to fix this is to rearrange the accept header in a backward compatible manner:

Instead of "application/openmetrics-text; version=0.0.1,text/plain;version=0.0.4;q=0.5,*/*;q=0.1" do this
"text/plain;version=0.0.4,application/openmetrics-text; version=0.0.1;q=0.5,*/*;q=0.1"
and I have verified that this works on my client without having to explicitly set the content-type.

This way, all existing clients doesn't have to modify their code when they migrate to newer versions.

Let me know if this sounds good and I can push a PR.

**Comment by roidelapluie** [comment]
Thank you for your report.

I am against this. We can not guarantee that broken clients will continue to work between minor releases. In this case, sending the first content-type header it sees is clearly a bug in the client -- and an obvious one, so I think that the client was broken from the start and only worked by luck.

**Comment by brian-brazil** [comment]
As @roidelapluie says this is broken HTTP content negotiation on your side, we prefer openmetrics but already do so in the standard backwards compatible way.

**Comment by arun-xandr** [comment]
Thanks @roidelapluie and @brian-brazil . I agree that the client is not sending the correct content-type to match the content after upgrade but I am more concerned about the fact that minor version change is exposing this hidden bug/behavior when it was least expected for a minor upgrade. To this effect, I was reading https://github.com/prometheus/prometheus/blob/master/docs/stability.md and it is confusing to me that "The ingestion exposition format" was considered stable but OpenMetrics support was added as "EXPERIMENTAL" (though it has an effect on the exposition format) and was considered unstable for 2.x.

The fact that openmetrics is preferred should have been a cause for major revision rather than assumed as part of the ordering of Content-Type. Just my 2 cents.

**Comment by brian-brazil** [comment]
That's not a breaking change, as existing non-OpenMetrics clients continue to work. As long as they follow the HTTP spec, which is the kind of assumption you have to make for the sake of sanity.

**Comment by arun-xandr** [comment]
I am closing this issue report. For anyone stumbling on this issue, I set the response "Content-Type" to `TextFormat.CONTENT_TYPE_004` explicitly to make it work.
