### ISSUE TITLE
prometheus k8s pod state is CrashLoopBackOff, warn"component=tsdb msg="unknown series references""

### ISSUE THREAD

**Issue by fcddk** [prometheus/prometheus#6506]
level=warn ts=2019-12-23T01:49:58.164Z caller=wal.go:116 component=tsdb msg="last page of the wal is torn, filling it with zeros" segment=/prometheus/wal/00000121

**Comment by fcddk** [comment]
The pod can't get up all the time, what is a good solution?

**Comment by brian-brazil** [comment]
We need more logs than that to work off, that message is not unusual.

**Comment by fcddk** [comment]
My image is based on version 2.10.0.  I have created three pods on three different nodes, and only one pod has this situation, and it is constantly restarting and reporting the same error.
Finally, I deleted all the wal-related log files stored locally and restarted the pod. The error disappeared. Analyze that there are problems when writing wal files that cause constant restarts.

**Comment by brian-brazil** [comment]
There'll be no debugging data then, and it was probably an OOM in any case. If it happens again and isn't OOM related please let us know.
