### ISSUE TITLE
[ANN] scollector adapter

### ISSUE THREAD

**Issue by tgulacsi** [prometheus/prometheus#652]
Hi, I've some Windows machines, and scollector (bosun.org/scollector) has a nice mature machine-metrics-collecting client. So I've made a silly little adapter, by copying&adapting graphite_exporter: https://github.com/tgulacsi/prometheus_scollector

I've made it under the same license, and willing to "donate" it to Prometheus, if that's easier.

**Comment by brian-brazil** [comment]
Thanks for writing this, we'd be happy to accept that. One question from a quick peek is do you need to add any sanitising of metric and label names to ensure they won't be rejected by prometheus?

**Comment by tgulacsi** [comment]
To answer that, I'd need better understanding what names are allowed in prometheus, and what names are produced by scollector :)
First I'll check that code in graphite_exporter, and include that. Maybe even that name mapper should be borrowed...

**Comment by brian-brazil** [comment]
https://github.com/prometheus/graphite_exporter/blob/dynamic-name/mapper.go#L27 identifierRE and validNameRE should cover you.

**Comment by juliusv** [comment]
Beware, those regexes are wrong and need updating. This doc contains the spec for what's legal in metric names, label names, and label values:

http://prometheus.io/docs/concepts/data_model/#metric-names-and-labels

See also this comment on the statsd exporter: https://github.com/prometheus/statsd_bridge/pull/10#issuecomment-92833297

**Comment by tgulacsi** [comment]
Thanks, I've done it with a simple function - I don't use regexes if they're avoidable. See "clearName" in main.go.

**Comment by oliver006** [comment]
Not to hijack this issue but is there a place where 3rd party collectors/exporters are normally announced/listed?
I wrote one for RethinkDB https://github.com/oliver006/rethinkdb_exporter and while it works well I'd appreciate feedback and obviously would like it lsited somewhere so people can find it more easily.

**Comment by brian-brazil** [comment]
We're planning on listing all the 3rd party exporters we're aware of on the website, see https://github.com/prometheus/docs/issues/68

**Comment by oliver006** [comment]
Thanks Brian, I'll add them to https://github.com/prometheus/docs/issues/68

**Comment by fabxc** [comment]
Closing as this is linked in the docs now.
