### ISSUE TITLE
Improve Prometheus Startup Times

### ISSUE THREAD

**Issue by kustodian** [prometheus/prometheus#6526]
## Proposal
Prometheus keeps 2 hours of WALs which need to be read on each Prometheus startup. Prometheus instances that ingest a lot of data need to read tens of gigabytes (or more), which means startup times can be very slow (it can last a few minutes). During this time Prometheus doesn't scrape metrics and alerting doesn't work as well.

The main goal of this issue would be to make the startup times short and the same no matter the activity of the Prometheus instances.

There are many ways to improve this, so I'm keeping this issue open for all possibilities.

**Comment by beorn7** [comment]
We have a bunch of tracking and design docs for this, from general to specific:
https://docs.google.com/document/d/11NUjmCOoMjhbs4UlJmAOPa2Bir9akytkRkvTqGSDxe0/edit#heading=h.3o4u97rijjfb
https://docs.google.com/document/d/184urkLQnM7rqLmGvS66I15jU2pyPk_qwd8v_qDlXczo/edit?usp=sharing
https://docs.google.com/document/d/1pnEsxB0CDLOxQipGw_vhkJpoDZfZPs_KjqCriumDAXQ/edit#

In general, I don't think tracking things in an issue in addition to the above is helpful.

**Comment by roidelapluie** [comment]
We have been looking at this during our bug scrub and we have decided to close it as this is discussed into other issues as mentioned by @beorn7 .
