### ISSUE TITLE
[UX] Alert filtering is hard to understand

### ISSUE THREAD

**Issue by kustodian** [prometheus/prometheus#6527]
## Proposal
There are two big UX problems with filtering alerts. The first one is that the filters on top don't look like they are toggles and it's hard to understand what happens when you click on one of the filters. They look more like tabs than checkboxes, so when I click on e.g. Firing, is it going to display only firing alerts, or exclude them. See the image below. Basically all the colleagues that used this filtering told me that every time they use it they have to discover again how it actually works, which is bad. It would be far better that these are checkboxes.
![image](https://user-images.githubusercontent.com/1949229/71514120-7c621280-289d-11ea-9c83-aacbf5b05cfc.png)

The second issue is that filters don't hide groups of alerts (files) that are not selected by the filter. Here is how the list of alerts looks like when I just select Firing. As you can see you have to scroll down to get to the firing alert, it's not visible because of the group names.
![image](https://user-images.githubusercontent.com/1949229/71513684-ac101b00-289b-11ea-97e9-be95fffd6b0b.png)

* Prometheus version:

	prometheus, version 2.15.1

**Comment by juliusv** [comment]
Totally, I always feel exactly the same when looking at the Alerts page, especially about the filters at the top. If someone can propose a better mockup (before implementing), that would be awesome.

**Comment by boyskila** [comment]
Yeah, good point! Using checkboxes is more intuitive and visually is looking way better. So something like this could be used instead.
![Screenshot 2020-01-01 23:20:15](https://user-images.githubusercontent.com/10514821/71646223-539eaa80-2ced-11ea-9c42-6bde95b93c54.png)

**Comment by juliusv** [comment]
I like it! Wondering if it makes sense to group the three new buttons even more, or prefix them with something (e.g. "Show alert types:"), but I'd say do a PR and we can play around :)

**Comment by juliusv** [comment]
Reopening this issue, because the linked fix only addressed the first issue (the checkboxes).

The question of also hiding any groups with no items remains an open one.
