### ISSUE TITLE
Signed images

### ISSUE THREAD

**Issue by MrDienns** [prometheus/prometheus#6528]
## Proposal
**Use case. Why is this important?**
Docker Content Trust allows us to verify if the images downloaded are indeed the images that Prometheus published. Security measures can be setup to only download signed images.

This goes for all Prometheus images, not just specific to this repository.

Is there any particular reason why signed images haven't been added, or is it simply a feature which hasn't been looked into yet?

https://docs.docker.com/engine/security/trust/content_trust/

**Comment by brian-brazil** [comment]
Please see https://prometheus.io/docs/operating/security/#build-process

If you need this, then you probably shouldn't trust our released binaries at all.

**Comment by MrDienns** [comment]
Thank you for the response. If releasing signed images isn't feasible then I'll build from source.
