### ISSUE TITLE
Ability to drop ports from the instance dynamic label.

### ISSUE THREAD

**Issue by AmandaCameron** [prometheus/prometheus#653]
I'd like it if it was possible to configure Prometheus to drop the port from the instance label.

My use-case:
My web-apps are exposed using a random docker port, however the tooling I have in place generates a web-app/host unique CNAME entry in our internal DNS, and since DOcker is assigning the external port "randomly" it's a bit bothersome to have it in there, as not only is it redundent, but it's going to be different beween launches of my web-apps.

I'm AmandaC in #prometheus, feel free to highlight me for further info / questions.

--
I'd be happy to come up with a simple PR for this, if there's interest. I just don't want to end up with the burden of maintaining a fork.

**Comment by fabxc** [comment]
This will be possible in the near future through relabelling. It will be part of the groundwork for more advanced service discovery than we have now. The is a [design doc](https://docs.google.com/document/d/1vEs0l0oX8npPZw06Vd8j7Ikg-x_NRGQlBuogaF3JbVw/edit#) - all comments and suggestions are welcome.
