### ISSUE TITLE
Storage Usage Way Up after 2.15.0 upgrade

### ISSUE THREAD

**Issue by timlharrison** [prometheus/prometheus#6544]
## Bug Report
**What did you do?**
Upgraded from 2.14.0 to 2.15.0 (and did not improve under 2.15.1)
**What did you expect to see?**
Storage consumption rate to remain unchanged
**What did you see instead? Under which circumstances?**
Storage consumption rate increased significantly after upgrade
**Environment**
Windows 2016
* System information:
vSphere VM
Windows 2016
16 core
32GB RAM
600GB storage drive

* Prometheus version:
2.15.1

It seems to be a LOT of *.tmp folders in the data directory taking up all the space

**Comment by roidelapluie** [comment]
Duplicate of #6513

**Comment by timlharrison** [comment]
I just noticed RAM usage is way up as well... assuming its related

**Comment by timlharrison** [comment]
This actually caused data loss for me in one of my Prom servers as the disk filled and stopped the service...

**Comment by brian-brazil** [comment]
Yip, looks like a dupe.
