### ISSUE TITLE
Error message when appending metrics does not provide enough information for troubleshouting

### ISSUE THREAD

**Issue by tionebsalocin** [prometheus/prometheus#6549]
When metrics is not formated properly the error message can be insuffisant to troubleshoot the issue easily.
Adding more information to identify the faulty metrics line would be nice 

## Bug Report
**What did you do?**
Generated a badly formated metrics such as:
`service_count{service="name",bad="{"wrong"="terrible"}"} 1`

And the error log was:
``level=warn ts=2020-01-03T17:45:37.205Z caller=scrape.go:930 component="scrape manager" scrape_pool=prometheus target=http://localhost:8080/metrics msg="append failed" err="expected equal, got \"INVALID\""`

which reflect the issue but does not give much information on where is the issue. If you have a large amount of metrics it can be tricky to identify this syntax issue

**What did you expect to see?**
I would have expected a message like:
```msg="append failed" err="expected equal, got \"INVALID\" at line 42"`

**Environment**

* System information:

	`Linux 5.3.13-arch1-1 x86_64`

* Prometheus version:

	`prometheus, version 2.11.1 (branch: HEAD, revision: e5b22494857deca4b806f74f6e3a6ee30c251763)
  build user:       root@d94406f2bb6f
  build date:       20190710-13:51:17
  go version:       go1.12.7`

* Prometheus configuration file:
```
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:8080']

```

* Logs:
```

level=info ts=2020-01-03T18:07:30.367Z caller=main.go:734 msg="Loading configuration file" filename=prometheus.yml
level=debug ts=2020-01-03T18:07:30.369Z caller=manager.go:224 component="discovery manager scrape" msg="Starting provider" provider=string/0 subs=[prometheus]
level=info ts=2020-01-03T18:07:30.369Z caller=main.go:762 msg="Completed loading of configuration file" filename=prometheus.yml
level=info ts=2020-01-03T18:07:30.369Z caller=main.go:617 msg="Server is ready to receive web requests."
level=debug ts=2020-01-03T18:07:30.369Z caller=manager.go:242 component="discovery manager scrape" msg="discoverer channel closed" provider=string/0
level=warn ts=2020-01-03T18:07:49.250Z caller=scrape.go:930 component="scrape manager" scrape_pool=prometheus target=http://localhost:8080/metrics msg="append failed" err="expected equal, got \"INVALID\""
level=warn ts=2020-01-03T18:08:04.250Z caller=scrape.go:930 component="scrape manager" scrape_pool=prometheus target=http://localhost:8080/metrics msg="append failed" err="expected equal, got \"INVALID\""
level=warn ts=2020-01-03T18:08:19.249Z caller=scrape.go:930 component="scrape manager" scrape_pool=prometheus target=http://localhost:8080/metrics msg="append failed" err="expected equal, got \"INVALID\""
level=warn ts=2020-01-03T18:08:34.248Z caller=scrape.go:930 component="scrape manager" scrape_pool=prometheus target=http://localhost:8080/metrics msg="append failed" err="expected equal, got \"INVALID\""
```

**Comment by brian-brazil** [comment]
You generally shouldn't be hand-producing the format, rather use one of the many client libraries that'll get the details right for you. The parser here is intended to be highly performant, not to be a reference parser or to make it easy to debug bad output.

I'd suggest working with the general parser that's in promtool to get more information on why a given output it bad.
