### ISSUE TITLE
wrong rate() instant vector value on metrics with exported timestamps

### ISSUE THREAD

**Issue by propertone** [prometheus/prometheus#6552]
## Bug Report
**What did you do?**
We have a custom exporter that exports timestamps with the metrics. Computing the instant vector rate() with the latest timestamp gives inconsistent values that vary between the expected rate and a value that's much lower.

Here's a simple exporter to reproduce the problem:
```
#!/usr/bin/env python
import time
from flask import Flask
app = Flask(__name__)

@app.route('/metrics')
def metrics():
    now = int(time.time())
    return "test_counter %s %s" % (now, (now-15)*1000)

if __name__ == '__main__':
    app.run(host="0.0.0.0")
```
This exports a monotonically increasing counter with a timestamp that's 15 second old.

Prometheus scrape config:
```
  - job_name: 'tstest'
    scrape_interval: 15s 
    static_configs:
        - targets:
            - localhost:5000
```

**What did you expect to see?**

Since the value of the metric is a monotonically increasing timestamp, `rate(test_counter)[1m]` should always return 1.

**What did you see instead? Under which circumstances?**
The value varies between 1 and around 0.62, depending on when you query it.
```
$ while :; do curl -d 'query=rate(test_counter[1m])' localhost:9090/api/v1/query |jq -r '.data.result[0].value|@tsv';sleep 1; done
1578090606.049	1
1578090607.062	0.8406333333333333
1578090608.076	0.8237333333333333
1578090609.089	0.8068500000000001
1578090610.102	0.7899666666666666
1578090611.116	0.7730666666666667
1578090612.129	0.7561833333333333
1578090613.142	0.7393
1578090614.155	0.7224166666666666
1578090615.169	0.7055166666666667
1578090616.182	0.6886333333333333
1578090617.195	0.67175
1578090618.208	0.6548666666666667
1578090619.221	0.6379833333333332
1578090620.235	0.6210833333333333
1578090621.247	1
...
```
This only happens under specific circumstances:
* Exported metrics have a timestamp that's less than now.
* The query time is within the last [scrape_interval].

**Environment**

* System information:

	Linux 3.10.0-1062.4.1.el7.x86_64 x86_64

* Prometheus version:

	prometheus, version 2.15.1 (branch: HEAD, revision: 8744510c6391d3ef46d8294a7e1f46e57407ab13)

In practice, this mostly visibly affects recording rules that compute rate, as the recorded value is way off (by up to 38% in our case, even with rate interval that's 4x the scrape interval).

I know that exporting timestamps on metrics is not recommended, so I've removed them in our configuration for now, but since it's technically supported and there are valid use cases for it (eg: federation, proxy to other monitoring systems), this seems like a bug.

**Comment by brian-brazil** [comment]
You have not provided sufficient information here to indicate a bug, this is almost certainly expected behaviour due to the gap you're introducing in the data.

**Comment by propertone** [comment]
I see - this happens any time there are gaps in the data, which a timestamp in the past would introduce. In practice though, it means the rate computed by recording rules is not reliable for metrics that export timestamps. Is there any work around for this?

**Comment by roidelapluie** [comment]
timestamps are meant only for federation. In this case, the federated prometheus has access to timestamp-free metrics and you can run the recording rules there. And the result of the rate() will be what you federate.

**Comment by propertone** [comment]
Ok, thanks. If the exporter already happens to export timestamps, the other workarounds I could think of are:

- Set `honor_timestamps: false` in the scrape configuration
- Add `offset [interval]` in the rate function
- Add another recording rule to copy the value of the original metric first, and compute the rate on that

This can be closed.

**Comment by brian-brazil** [comment]
A longer range may also help.
