### ISSUE TITLE
Tools to clean up / modify already collected data?

### ISSUE THREAD

**Issue by oliver006** [prometheus/prometheus#656]
Hey there,

are there tools available to selectively clean out entire (or partial) time series? Occasionally, when pushing out a test version of a new collector, I collect data in the wrong format, with the wrong label or metric names, etc and I'd like to remove it and not wipe put the entire data directory.

Suggestions?

**Comment by juliusv** [comment]
Hey @oliver006, thanks for the question! This doesn't exist yet, but we have a ticket open for it in https://github.com/prometheus/prometheus/issues/382. The use case is definitely valid and important and I'm all for it. Feel free to add ideas for it to that ticket. Closing this one.

**Comment by oliver006** [comment]
Thx!
