### ISSUE TITLE
Prometheus server crash

### ISSUE THREAD

**Issue by RohitBharatai15** [prometheus/prometheus#6561]
## Bug Report

**What did you do?**
Prometheus server was running on an Intance of 1 GB RAM, 8 GB storage having 5 endpoints .
Then after 2 or 3 days server crashed
Possible reasons :

- Storage Size

then I added more storage i.e 50GB and started the server using
`./promethues --and_some_command_line_flag`

This trick worked for 2 more days and the next error was :
![image](https://user-images.githubusercontent.com/56105210/71808705-800f4980-3094-11ea-984c-23e6b8e86c56.png)

After some work around

- Server was still running on 1 GB RAM and was crashed
- Unable to access or restart prometheus again
- http://XXX.XXX.XXX.XXX:9090 was not working on web
- And data for 2 days was lost

Then the AWS instance was shifted 32 GB Ram and 50GB storage

- Every thing was solved and server was running for 12 hrs
- Note : Prometheus was not running as a prometheus.service yet
- After 12 hrs it again Crashed

What was done next :-

- Setup prometheus as a service
- Increased storage to 100GB
- Set the retention time as 52 week
- Retention size 50 GB
- And started the server as a service

Current Scenario
Server is active
`
[root@ip prometheus-2.12.0.linux-386]# sudo systemctl status prometheus.service -l
● prometheus.service - Prometheus
   Loaded: loaded (/etc/systemd/system/prometheus.service; enabled; vendor preset: disabled)
   Active: _active_ (running) since Mon 2020-01-06 09:35:54 UTC; 42s ago
 Main PID: 25792 (prometheus)
   CGroup: /system.slice/prometheus.service
           └─25792 /usr/local/bin/prometheus --config.file=/etc/prometheus/prometheus.yml 
		--storage.tsdb.path /var/lib/prometheus/data/ --storage.tsdb.wal-compression --storage.tsdb.retention.time=52w --storage.tsdb.retention.size=50GiB

Jan 06 09:35:54 [25792]: level=info ts=2020-01-06T09:35:54.871Z caller=repair.go:59 component=tsdb msg="found healthy block" mint=1578124800000 maxt=1578132000000 ulid=O767867689HMMAME
Jan 06 09:35:54 ip: level=info ts=2020-01-06T09:35:54.871Z caller=repair.go:59 component=tsdb msg="found healthy block" mint=1578132000000 maxt=1578139200000 ulid=07656878Y9IOHJKX9X5A
Jan 06 09:35:54 ip: level=info ts=2020-01-06T09:35:54.871Z caller=repair.go:59 component=tsdb msg="found healthy block" mint=1578139200000 maxt=1578146400000 ulid=JIOYUTTYDERSR0SJ1JM9
Jan 06 09:35:54 ip: level=info ts=2020-01-06T09:35:54.994Z caller=head.go:509 component=tsdb msg="replaying WAL, this may take awhile"
Jan 06 09:35:56 ip: level=info ts=2020-01-06T09:35:56.055Z caller=head.go:533 component=tsdb msg="WAL checkpoint loaded"
Jan 06 09:35:57 ip: level=info ts=2020-01-06T09:35:57.916Z caller=head.go:557 component=tsdb msg="WAL segment loaded" segment=34 maxSegment=1404
Jan 06 09:36:03 ip: level=info ts=2020-01-06T09:36:03.174Z caller=head.go:557 component=tsdb msg="WAL segment loaded" segment=35 maxSegment=1404
Jan 06 09:36:06 ip: level=info ts=2020-01-06T09:36:06.670Z caller=head.go:557 component=tsdb msg="WAL segment loaded" segment=36 maxSegment=1404
Jan 06 09:36:16 ip: level=info ts=2020-01-06T09:36:16.766Z caller=head.go:557 component=tsdb msg="WAL segment loaded" segment=37 maxSegment=1404
Jan 06 09:36:25 ip: level=info ts=2020-01-06T09:36:25.390Z caller=head.go:557 component=tsdb msg="WAL segment loaded" segment=38 maxSegment=1404
`

But the UI says Service Unavailable
![image](https://user-images.githubusercontent.com/56105210/71810239-eb0e4f80-3097-11ea-95f2-07b66fc27145.png)

**What did you expect to see?**
We want run our prometheus server without any fail or like "0 downtime  " as we are monitoring our services.

**What did you see instead? Under which circumstances?**

**Environment**

### * System information:
   Linux `4.14.154-128.181.amzn2.x86_64`
   vm with 8cpus and 32G memory

	
### * Prometheus version:
prometheus, version 2.12.0 (branch: HEAD, revision: 43acd0e2e93f9f70c49b2267efa0124f1e759e86)
  build user:       root@7a9dbdbe0cc7
  build date:       20190818-13:56:50
  go version:       go1.12.8

### * Prometheus configuration file:
`# my global config
global:
  scrape_interval:     30s 
  evaluation_interval: 60s 
  
alerting:
  alertmanagers:
  - static_configs:
    - targets:

rule_files:
  
scrape_configs:
 
  - job_name: 'prometheus'
    
    static_configs:
     - targets: ['Target1:9090']

  - job_name: JOB one
    tls_config:
     insecure_skip_verify: true
    scrape_timeout: 15s
    scrape_interval: 30s
    honor_labels: true
    metrics_path: /metrics
    scheme: https
    basic_auth:
     username: user
     password: <secret>
    static_configs:
       - targets: ['endpoint 1']
  - job_name: JOB Two
    tls_config:
     insecure_skip_verify: true
    scrape_timeout: 15s
    scrape_interval: 30s
    honor_labels: true
    metrics_path: /metrics
    scheme: https
    basic_auth:
     username: user
     password: <secret>
    static_configs:
       - targets: ['endpoint 2']
  - job_name: JOB Three
    tls_config:
     insecure_skip_verify: true
    scrape_timeout: 15s
    scrape_interval: 30s
    honor_labels: true
    metrics_path: /metrics
    scheme: https
    basic_auth:
     username: user
     password: <secret>
    static_configs:
       - targets: ['endpoint 3']
  - job_name: JOB Four
    scrape_timeout: 15s
    scrape_interval: 30s
    honor_labels: true
    metrics_path: /metrics
    scheme: https
    basic_auth:
     username: user
     password: <secret>
    static_configs:
       - targets: ['endpoint 4']`

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by RohitBharatai15** [comment]
Hi @brian-brazil 
this problem was repetitive so I thought might be an Issue

**Comment by brian-brazil** [comment]
This is almost certainly a lack of resources on your machine, so not a bug in Prometheus.
