### ISSUE TITLE
Proposal: UI: move "No datapoints found" message to within the "Graph" tab

### ISSUE THREAD

**Issue by stephen-dexda** [prometheus/prometheus#6562]
Currently the "No datapoints found" message appears below the Execute button and above the Graph/Console tabs.

When the time range is being paged through, this causes the earlier/later buttons shift up and down from underneath the mouse cursor (depending on whether there are datapoints for that time range).

Additionally, the graph itself remains with stale values/labels/time range if the user pages earlier/later to a time range with no datapoints.

Moving "No datapoints found" to replace (or overlay) the graph area, below the graphing parameter fields, would fix both of these issues.

Additionally, it would make the graph UI consistent with the Console UI, where "no data" is shown in the Element/Value list within the Console tab.

**Comment by juliusv** [comment]
Totally agreed. This is already implemented this way in the new React UI:

https://prometheus-react.netlify.com/new/graph?g0.expr=nonexistentmetric

You should already be able to access that in recent Prometheus versions under `/new/graph`. We're unlikely to put much work into the old UI though, as it's going away soon.

**Comment by roidelapluie** [comment]
We have looked at it in our bug scrub and decided to close this as it is available in the new UI.
