### ISSUE TITLE
PromQL: Ambigousness when parsing grouping opts

### ISSUE THREAD

**Issue by slrtbtfs** [prometheus/prometheus#6563]

**Comment by slrtbtfs** [comment]
Sorry, accidentally hit enter while filing this issue. before it was complete. Content will be there in a few minutes.

**Comment by slrtbtfs** [comment]
Actual description of the issue.

The documentation for `group_left|group_right` specifies the following grammar:

```
<vector expr> <bin-op> ignoring(<label list>) group_left(<label list>) <vector expr>
<vector expr> <bin-op> ignoring(<label list>) group_right(<label list>) <vector expr>
<vector expr> <bin-op> on(<label list>) group_left(<label list>) <vector expr>
<vector expr> <bin-op> on(<label list>) group_right(<label list>) <vector expr>
```

It turns out it is also legal to use `group_left|group_right` without a label list, e.g:

```
a / ignoring(b) group_left c
```

This gets interesting when using parentheses on the right hand side of the operation, e.g:
```
 a / ignoring(b) group_left (c)
```
Since the parser only  has a small lookahead (1 token as of the old generated parser), the left parentheses gets interpreted as the start of a label list. So the above expression will trigger an error, due to a lack of a right hand side of the expression.

Another example:
```
a / ignoring(b) group_left (c + d)
```
While possibly conforming to the unclear specification, this will produce an error, since '+' isn't a legal character in a label list.

To work around this one can use
```
a / ignoring(b) group_left () (c + d)
```

---

All in all this part of PromQL turns out to be quite ambiguous, and it might make sense to consider changing the syntax or the parser behaviour to something less confusing.

**Comment by slrtbtfs** [comment]
It might be worth noting, that these problems were found by the yacc tool, so it seems using a parser generator actually helps to understand the language.

**Comment by brian-brazil** [comment]
This was already discussed, if the RHS starts with a `(` then you must have a `()` for the grouping list..

**Comment by slrtbtfs** [comment]
Is this documented anywhere?

**Comment by brian-brazil** [comment]
I'd have to see if I could dig up the discussion, but this was explicitly the way it's meant to work.

**Comment by slrtbtfs** [comment]
Closing, since IMHO there isn't anything that needs or should be done about this.

If anybody feels different about this, feel free to reopen.

**Comment by juliusv** [comment]
FWIW this just hit another user I'm helping, and it was quite confusing to them. In total I've encountered this a couple of times over the years. Not sure if this makes it worth implementing a more complex parser (looking further ahead) though, and how difficult that would be with the new YACC-based parser?

**Comment by brian-brazil** [comment]
You wouldn't need to look further ahead for this.

**Comment by slrtbtfs** [comment]
> You wouldn't need to look further ahead for this.

Why not.

Also, to reduce user confusion we could just stop recommending the `group_(left|right)` variant without parentheses in the docs.

**Comment by brian-brazil** [comment]
If I recall my compiler design classes correctly, anything you can do with a 2+ symbol lookahead you can do with a 1 symbol lookahead.

**Comment by slrtbtfs** [comment]
If the parser allows ɛ​ rules, that's true.

Look ahead isn't really that much of an issue anymore, since YACC accepts LALR(1) grammars.

The theory behind whether an LALR(k) grammar is LL(j) and vice versa, doesn't seem to produce results, that would help us here: https://en.wikipedia.org/wiki/LALR_parser#LL_parsers 

---

Putting the theory aside, I've played a bit around with the parser and wasn't able to make it parse these edge cases correctly.

In my opinion these edge cases are simply due to bad language design and instead of putting to much effort into improving their handling, I'd rather discourage users from using problematic syntaxes.

**Comment by juliusv** [comment]
Sounds like a decent compromise to me, let's just change all the documentation examples. Will send a PR for that.
