### ISSUE TITLE
[bug] Remote Storage：read fail When the label name starts with a number

### ISSUE THREAD

**Issue by liguozhong** [prometheus/prometheus#6573]
http://101.37.130.205:9090/api/v1//query?query=sum(up) by (job)
return 

{"status":"error","errorType":"execution","error":"invalid label name: 3vjia_datacenter_env"}

![image](https://user-images.githubusercontent.com/9583245/71947511-1152fd00-3208-11ea-8f1e-cda4e5d3d228.png)

![image](https://user-images.githubusercontent.com/9583245/71947526-1b74fb80-3208-11ea-8af5-b20839aa6361.png)

**Comment by liguozhong** [comment]
![image](https://user-images.githubusercontent.com/9583245/71947849-1bc1c680-3209-11ea-9dad-9cba2215c7ff.png)

At present, we solve the user's problem by adding the logic of replacing "_" prefix in the adapter of remote storage. But we think this may be a better and more general prometheus server to handle

**Comment by brian-brazil** [comment]
I'm not fully understanding what the problem is here. This sounds like your remote storage adapter is behaving correctly in not sending invalid label names.

**Comment by roidelapluie** [comment]
We have been looking into this in out bug scrub and determined this is the expected behavior; remote read should send valid labels.
