### ISSUE TITLE
PromQL: Unusual unary operator precedence

### ISSUE THREAD

**Issue by slrtbtfs** [prometheus/prometheus#6575]
Consider the expression:
```
-a^b
```
For written mathematics the convention is to interpret this as follows:
```
-(a^b)
```
However PromQL will interpret it as
```
(-a)^b
```

__To be discussed:__ Should PromQL keep the existing behaviour that might be not expected by users or change it to follow mathematical conventions, at the risk of breaking existing queries?

**Comment by brian-brazil** [comment]
This is going to be pretty rare, as exponents aren't common and usually it'd be a binary subtraction rather than a bare unary negation. I think we should make it follow the standard conventions.

**Comment by roidelapluie** [comment]
I agree. We can consider it a promql bug.
