### ISSUE TITLE
React UI: Stack graph displays null value as zero

### ISSUE THREAD

**Issue by roidelapluie** [prometheus/prometheus#6576]
## Proposal
**Use case. Why is this important?**

A value not defined is different than 0.
Old UI behaves correctly, as does grafana.

## Bug Report
**What did you do?**

Stack a graph with null values. exemple query:

label_replace(vector(time()) % 300 < 180,"x","x","","") or label_replace(vector(time()) % 300 > 140,"y","y","","") 

![est](https://user-images.githubusercontent.com/291750/71974746-8fb49c80-3212-11ea-996f-84dbb8b109dd.png)

**What did you expect to see?**

Null points are not shown

**What did you see instead? Under which circumstances?**

Null points are shown as 0

**Environment**

* Prometheus version:

	2.15.2

This is known issue in code but not tracked in a bug yet. It is a bug in a third party library we use that forces us to set 0.
cc @juliusv

**Comment by juliusv** [comment]
Thanks for opening an issue for this!

CC @boyskila who has already starting looking a bit into this on the Flot / Grafana Flot fork side.
