### ISSUE TITLE
Export metric for WAL write errors

### ISSUE THREAD

**Issue by kormat** [prometheus/prometheus#6577]
When prometheus is unable to write to the WAL, it logs a warning, but there is no metric exported to allow alerting on this condition. This means that an operator might not know there's a corrupted/truncated WAL until the next compaction cycle runs (assuming they have an alert on `prometheus_tsdb_wal_truncations_failed_total`).

Example log entries:
```
level=warn ts=2020-01-08T11:57:49.195Z caller=scrape.go:945 component="scrape manager" scrape_pool=border_routers target=<redacted>/metrics msg="appending scrape report failed" err="write to WAL: log samples: write data/wal/00000000: no space left on device"
level=warn ts=2020-01-08T11:57:49.195Z caller=manager.go:584 component="rule manager" group=alert.rules msg="rule sample appending failed" err="write to WAL: log samples: write data/wal/00000000: no space left on device"
```

**Comment by roidelapluie** [comment]
What is the value of   prometheus_tsdb_wal_corruptions_total ?

**Comment by cstyan** [comment]
In this particular case you'd probably notice via any alerts regarding disk space, but I see no harm in adding a counter for `WAL writes failed`.

**Comment by jpmcb** [comment]
Hi there! I'd like to work on this issue and get involved contributing.

Reading through the code base, I'd anticipate I'd add a test that asserts a new counter is initilized and increments when there is an error here:

https://github.com/prometheus/prometheus/blob/2ca25d1c96424c896683e8cab65ba9666e8d3b66/tsdb/head.go#L1002-L1004

Thoughts? Any other pointers?

**Comment by brian-brazil** [comment]
I'd usually not even write a unittest for a metric, you wouldn't for an application log.

**Comment by alippai** [comment]
Shouldn't `/-/healthy` and `/-/ready` reflect these failures?

**Comment by roidelapluie** [comment]
> Shouldn't `/-/healthy` and `/-/ready` reflect these failures?

This is discussed in https://github.com/prometheus/prometheus/issues/3807

**Comment by alippai** [comment]
@roidelapluie Thank you

**Comment by codesome** [comment]
Looks like this is fixed by https://github.com/prometheus/prometheus/pull/6647
