### ISSUE TITLE
label_replace doesn't work on /api/v1/query?query= endpoint

### ISSUE THREAD

**Issue by widgetpl** [prometheus/prometheus#6578]
## Bug Report
`/api/v1/query?query=` endpoint doesn't respect `label_replace` function and it returns original labels instead of replaced. I would suspect that api endpoint will return json with replaced label values.
Example query
```
label_replace(sum by (node)(kube_node_status_condition{condition="MemoryPressure",status="true"}), "node", "$1.$2.$3.$4", "node", ".*-([[:digit:]]{1,3})-([[:digit:]]{1,3})-([[:digit:]]{1,3})-([[:digit:]]{1,3}).+")
```
result in UI (http://localhost:9090/graph)

|Element|Value|
|---|---|
|{node="10.20.11.178"} | 0|
|{node="10.20.11.99"} | 0|
|{node="10.20.12.177"} | 0|
|{node="10.20.12.238"} | 0|

but in rest api (http://localhost:9090/api/v1/query?query=) I get original labels. Full request
```
http://localhost:9090/api/v1/query?query=label_replace(sum%20by%20(node)(kube_node_status_condition{condition=%22MemoryPressure%22,status=%22true%22}),%20%22node%22,%20%22$1.$2.$3.$4%22,%20%22node%22,%20%22.*-([[:digit:]]{1,3})-([[:digit:]]{1,3})-([[:digit:]]{1,3})-([[:digit:]]{1,3}).+%22)
```
output:
```
{"status":"success","data":{"resultType":"vector","result":[{"metric":{"node":"ip-10-20-12-238.eu-west-1.compute.internal"},"value":[1578486050.392,"0"]},{"metric":{"node":"ip-10-20-11-178.eu-west-1.compute.internal"},"value":[1578486050.392,"0"]},{"metric":{"node":"ip-10-20-11-99.eu-west-1.compute.internal"},"value":[1578486050.392,"0"]},{"metric":{"node":"ip-10-20-12-177.eu-west-1.compute.internal"},"value":[1578486050.392,"0"]}]}}
```
**Environment**

* Prometheus version:

Version | 2.10.0
-- | --
Revision|d20e84d0fb64aff2f62a977adc8cfb656da4e286
Branch|HEAD
BuildUser|root@a49185acd9b0
BuildDate|20190525-12:28:13
GoVersion|go1.12.5

**Comment by brian-brazil** [comment]
Those are the exact same API.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
