### ISSUE TITLE
React UI: Issue with long labels

### ISSUE THREAD

**Issue by roidelapluie** [prometheus/prometheus#6582]
## Bug Report
**What did you do?**

Run a query with long labels in react ui graph

```
label_join(label_join(label_join(label_join(label_join(label_replace(vector(1),"Lorem","Lorem_ipsum_dolor_sit_amet__consectetur","",""),"Lipsum","","Lorem"),"Xipsum","","Lorem"),"Yipsum","","Lorem"),"Zipsum","","Lorem"),"Bipsum","","Lorem")
```

**What did you expect to see?**

metrics appear in one line

**What did you see instead? Under which circumstances?**

metrics appear in multi line with line breaks in the middle.

![est](https://user-images.githubusercontent.com/291750/71985657-47ee3f00-322b-11ea-8426-51b4a70a6d8b.png)

**Comment by boyskila** [comment]
How valid is such a long set of labels?
Eventually, the container can wrap the content but this means more than one line.

![Screenshot 2020-01-09 21:36:44](https://user-images.githubusercontent.com/10514821/72098925-2de65680-3328-11ea-8722-f55fcfc93e03.png)

**Comment by brian-brazil** [comment]
There is no limit on the number or size of labels.

**Comment by roidelapluie** [comment]
More than one line is fine. While I provided a test query, I have actually seen it on prod with real metrics.
