### ISSUE TITLE
PromQL: Add position metadata to the AST

### ISSUE THREAD

**Issue by slrtbtfs** [prometheus/prometheus#6597]
## Motivation

For the PromQL language server, it is crucial to be able to map string positions to AST Nodes in PromQL queries.

## Proposal

I'd like to add the following function to the `promql.Node` interface:

```
PositionRange() PositionRange
```

where

```
type PositionRange struct {
    Start int
    End int
}
```
contains the Position of the corresponding AST Node as a byte offset in the input string.

The necessary metadata will be stored in the AST Nodes.

This would essentially be a more lightweight and less complex version of #6061.

---

Would people be ok if I go ahead with these changes as described?

cc @brian-brazil @juliusv @simonpasquier

**Comment by slrtbtfs** [comment]
This also would allow to give more precise position information for type errors. Those are quite off at the moment.

**Comment by juliusv** [comment]
Sounds good to me! :ship:

**Comment by brian-brazil** [comment]
I was confused that this was an issue and not a PR :)

**Comment by slrtbtfs** [comment]
Just wanted to make sure everybody is ok with the approach, before I spent a lot of time working on in.

PR will follow soon.
