### ISSUE TITLE
prometheus restart is very slow

### ISSUE THREAD

**Issue by du2016** [prometheus/prometheus#6608]
## Bug Report
**What did you do?**

restart my prometheus

**What did you expect to see?**

restart quickly

**What did you see instead? Under which circumstances?**

restart very slow (after 1 hour,also not ready )

**Environment**

* System information:

	Linux 3.10.0-862.el7.x86_64 x86_64

**Comment by du2016** [comment]
prometheus version is 2.9.2

**Comment by roidelapluie** [comment]
Thank you for your report, starup times are already discussed in #6526.

**Comment by du2016** [comment]
thanks
