### ISSUE TITLE
thanos open /etc/prometheus-shared/prometheus.yml: no such file or directory 

### ISSUE THREAD

**Issue by garenwen** [prometheus/prometheus#6609]
replicas: 1
  selector:
    matchLabels:
      app: prometheus-thanos
  template:
    metadata:
      labels:
        kenc.ksyun.com/app: prometheus
        kenc.ksyun.com/ns: kube-system
        app: prometheus-thanos
    spec:
      tolerations:
        - key: node.kubernetes.io/unschedulable
          effect: NoSchedule
      securityContext:
        runAsUser: 1000
        fsGroup: 2000
        runAsNonRoot: true
      schedulerName: local-storage-scheduler
      serviceAccountName: prometheus
      containers:
        - name: prometheus
          imagePullPolicy: IfNotPresent
          image: 'sss/prometheus:v2.10.0'
          args:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--config.file=/etc/prometheus-shared/prometheus.yml'
            - '--storage.tsdb.path=/var/prometheus'
            - '--web.enable-lifecycle'
            - '--storage.tsdb.retention=3d'
            - '--storage.tsdb.min-block-duration=2h'
            - '--storage.tsdb.max-block-duration=2h'
            - '--web.enable-admin-api'
          ports:
            - name: http-prometheus
              containerPort: 9090
          volumeMounts:
            - name: config-shared
              mountPath: /etc/prometheus-shared
            - name: kenc-certs
              mountPath: /etc/ssl/kenc
            - name: prometheus-thanos
              mountPath: /var/prometheus
          resources:
            limits:
              cpu: '1'
              memory: 8Gi
            requests:
              memory: 8Gi
              cpu: '0.5'
        - name: thanos
          imagePullPolicy: IfNotPresent
          image: 'ss/thanos:v0.9.0'
          args:
            - sidecar
            - '--log.level=warn'
            - '--tsdb.path=/var/prometheus'
            - '--prometheus.url=http://localhost:9090'
            - '--reloader.config-file=/etc/prometheus/prometheus.yml'
            - >-
              --reloader.config-envsubst-file=/etc/prometheus-shared/prometheus.yaml
            - '--objstore.config-file=/etc/thanos/conf/bucket.yaml'
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          ports:
            - name: http-sidecar
              containerPort: 10902
            - name: grpc
              containerPort: 10901
          volumeMounts:
            - name: thanos-config
              mountPath: /etc/thanos/conf/
            - name: prometheus-thanos
              mountPath: /var/prometheus
            - name: config-shared
              mountPath: /etc/prometheus-shared
            - name: config
              mountPath: /etc/prometheus
          resources:
            limits:
              cpu: '1'
              memory: 4Gi
            requests:
              memory: 4Gi
              cpu: '0.5'
          readinessProbe:
            httpGet:
              port: 9090
              path: /-/ready
            timeoutSeconds: 30
            periodSeconds: 10
            initialDelaySeconds: 30
            failureThreshold: 10
      volumes:
        - name: thanos-config
          configMap:
            name: edge-thanos-config
        - name: config
          configMap:
            name: prometheus-thanos-config
        - name: kenc-certs
          secret:
            secretName: prometheus-certs
        - name: config-shared
          emptyDir: {}
  volumeClaimTemplates:
    - metadata:
        labels:
          app: prometheus
        name: prometheus-thanos
      spec:
        storageClassName: local-storage
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 30Gi
-->
## Proposal
**Use case. Why is this important?**

*“Nice to have” is not a good use case. :)*

## Bug Report
**What did you do?**

**What did you expect to see?**

**What did you see instead? Under which circumstances?**

**Environment**
kuberntes 1.15

* System information:
centos 7

* Prometheus version:
v2.10

* Prometheus configuration file:
```
  prometheus.yml: |
    global:
      evaluation_interval: 30s
      external_labels:
        cluster: $(POD_NAME)
      scrape_interval: 30s
      scrape_timeout: 10s
    scrape_configs:
     - job_name: prometheus-thanos
       static_configs:
       - targets:
         - 'localhost:9090'

```

* Logs:
```
level=info ts=2020-01-13T11:29:43.299Z caller=main.go:323 build_context="(go=go1.12.5, user=root@a49185acd9b0, date=20190525-12:28:13)"
level=info ts=2020-01-13T11:29:43.299Z caller=main.go:324 host_details="(Linux 4.9.18-19080201 #1 SMP Fri Aug 2 12:15:35 CST 2019 x86_64 prometheus-thanos-0 (none))"
level=info ts=2020-01-13T11:29:43.299Z caller=main.go:325 fd_limits="(soft=65536, hard=65536)"
level=info ts=2020-01-13T11:29:43.299Z caller=main.go:326 vm_limits="(soft=unlimited, hard=unlimited)"
level=info ts=2020-01-13T11:29:43.300Z caller=main.go:645 msg="Starting TSDB ..."
level=info ts=2020-01-13T11:29:43.300Z caller=web.go:417 component=web msg="Start listening for connections" address=0.0.0.0:9090
level=info ts=2020-01-13T11:29:43.305Z caller=main.go:660 fs_type=XFS_SUPER_MAGIC
level=info ts=2020-01-13T11:29:43.305Z caller=main.go:661 msg="TSDB started"
level=info ts=2020-01-13T11:29:43.305Z caller=main.go:730 msg="Loading configuration file" filename=/etc/prometheus-shared/prometheus.yml
level=info ts=2020-01-13T11:29:43.305Z caller=main.go:514 msg="Stopping scrape discovery manager..."
level=info ts=2020-01-13T11:29:43.305Z caller=main.go:528 msg="Stopping notify discovery manager..."
level=info ts=2020-01-13T11:29:43.305Z caller=main.go:550 msg="Stopping scrape manager..."
level=info ts=2020-01-13T11:29:43.305Z caller=main.go:524 msg="Notify discovery manager stopped"
level=info ts=2020-01-13T11:29:43.305Z caller=main.go:510 msg="Scrape discovery manager stopped"
level=info ts=2020-01-13T11:29:43.305Z caller=manager.go:775 component="rule manager" msg="Stopping rule manager..."
level=info ts=2020-01-13T11:29:43.305Z caller=manager.go:781 component="rule manager" msg="Rule manager stopped"
level=info ts=2020-01-13T11:29:43.305Z caller=main.go:544 msg="Scrape manager stopped"
level=info ts=2020-01-13T11:29:43.306Z caller=notifier.go:530 component=notifier msg="Stopping notification manager..."
level=info ts=2020-01-13T11:29:43.306Z caller=main.go:714 msg="Notifier manager stopped"
level=error ts=2020-01-13T11:29:43.306Z caller=main.go:723 err="error loading config from \"/etc/prometheus-shared/prometheus.yml\": couldn't load configuration (--config.file=\"/etc/prometheus-shared/prometheus.yml\"): open /etc/prometheus-shared/prometheus.yml: no such file or directory"
```

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
