### ISSUE TITLE
PromQL: Allow engine to return strings

### ISSUE THREAD

**Issue by slrtbtfs** [prometheus/prometheus#6610]
## Problem
`promql.ParseExpr` will parse expressions of all types without syntax errors, but the engine can only evaluate expressions of type `vector` and `matrix`.

## Proposal

Add a `ParseQuery` func that will behave like `ParseExpr` but will panic if the type of the AST root has a type that can not be evaluated by the engine, i.e. is a scalar or string.

This would also solve part of the problem pointed out in https://github.com/prometheus/prometheus/issues/6598#issuecomment-573624531.

**Comment by roidelapluie** [comment]
Scalar should and strings could be fine. String is a valid promql type.

**Comment by juliusv** [comment]
For reference, the current error for a root expression like `"foo"` happens here: https://github.com/prometheus/prometheus/blob/8cb2ab6a9913d7735c729a03964bf485053aca35/promql/engine.go#L1322

Wouldn't it be better to fix the engine to support evaluating any of the four value types as the root node, rather than adding such a new function?

**Comment by slrtbtfs** [comment]
I agree now.

**Comment by slrtbtfs** [comment]
Does anyone want to work on a PR for that?

Otherwise I can do it.

**Comment by juliusv** [comment]
Either is fine, feel free to go ahead.

I hope it won't create too many complications. E.g. range evals for strings wouldn't work, I guess.

**Comment by slrtbtfs** [comment]
> E.g. range evals for strings wouldn't work, I guess.
That should already be caught by the parser.

This issue is only about the case of the root node being a string.

**Comment by juliusv** [comment]
Yes, but root nodes can be evaluated at an instant or over a range (graph), but matrix root nodes already can't be evaluated over a range, only scalars and vectors can. So I guess strings would have the same restrictions as matrix nodes.
