### ISSUE TITLE
what is different bewteen one group and multi group?

### ISSUE THREAD

**Issue by daxwang** [prometheus/prometheus#6624]
I have a question about multi record group rules, for example:
exmaple 1 (record rules in different group):
groups:
- name: group1
  rules:
  - record: metrics1
	expr: sum(__orgin_metrics)
- name: group2
  rules:
  - record: metrics2
	expr: rate(metrics1[5m])
- name: group3
  rules:
  - record: metrics3
	expr: sum(metrics2)
	

example 2 (all record rules in one group):
groups:
- name: group1
  rules:
  - record: metrics1
	expr: sum(__orgin_metrics)
  - record: metrics2
	expr: rate(metrics1[5m])
  - record: metrics3
	expr: sum(metrics2)
  
above two examples,  evaluation_interval is both 60s，one is all record rules in multi groups, and the other one  all record rules in one group, and the result of metrics2 is from metrics1,  metrics3 is from metrics2. there are several questions：
1、in example 2, all record in one group,  so i kown the prometheus execute order is metrics1=>metrics2=>metrics3. but in example1, what is the execute order in the multi groups?  is prometheus execute disorder?
2、if example1 multi group execute disorder, is it metrics3 maybe execute first? so the result of metrics3 is NAN?
3、what is different bewteen  one group and multi group？

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
