### ISSUE TITLE
Will grpc query be provided in the recent version?

### ISSUE THREAD

**Issue by zhangzheyu2simple** [prometheus/prometheus#6625]
We use prometheus internally as a database for monitoring data. When developing some applications that interact with prometheus, we find that providing a grpc interface for instant query and range query will help developers understand the structure of the returned results. To do this, we use types.proto under web/api/v2(originally used for remote storage) to provide instant queries and range queries.

Will grpc query be provided in the recent version? Also, we would be honored if we could contribute code to prometheus.

**Comment by brian-brazil** [comment]
No, there's no plans to add more APIs on top of the standard http+json API. The v2 API is abandoned, should not be used, and will be deleted at some point.
