### ISSUE TITLE
Constants in storage/local overflow int on 32-bit

### ISSUE THREAD

**Issue by chkno** [prometheus/prometheus#663]
Build (which includes "go test") fails on 32-bit systems with these constant-overflows-int messages:

storage/local/codable/codable_test.go:44: constant 422010471112345 overflows int
storage/local/storage_test.go:806: constant 4294967296 overflows int
storage/local/storage_test.go:806: constant 2147483648 overflows int
FAIL    _/home/user/prometheus/storage/local [build failed]
FAIL    _/home/user/prometheus/storage/local/codable [build failed]

**Comment by chkno** [comment]
Pull request: https://github.com/prometheus/prometheus/pull/665

**Comment by fabxc** [comment]
Fixed. Thanks again!
