### ISSUE TITLE
Compact Head eventually if ingestion stops

### ISSUE THREAD

**Issue by codesome** [prometheus/prometheus#6637]
If the ingestion of samples stop, according to the current logic, `Head` will never be [compactable](https://github.com/prometheus/prometheus/blob/949e4d12a45d3d42f9ad25d7944b6c00ddd0c403/tsdb/head.go#L1251-L1256) as the maxTime of the Head never changes.

It would be nice to compact the Head with some time guarantee instead of holding the data in Head indefinitely.

/cc @pracucci

**Comment by brian-brazil** [comment]
Is this actually a problem? This can only happen if a Prometheus has no targets, and the Prometheus will still work correctly.

**Comment by pracucci** [comment]
In Cortex we're working on a new storage based on Thanos (and thus TSDB). When a tenant stop pushing metrics to Cortex, would be ideal if TSDB could guarantee us that all series in the head are actually flushed in a block within a period of time (whatever it is, as far as reasonable).

**Comment by codesome** [comment]
This is not a problem. Rather a proposal for further enhancement.

**Comment by brian-brazil** [comment]
This could actually break users if they're trying to ingest old data, the timestamp of samples isn't necessarily now.

**Comment by gouthamve** [comment]
Hrm, can we work around this in Cortex by manually triggering a compaction? I'm asking this because time is relative (lol) and we don't want to depend on `time.Now()` in TSDB. Like you can send samples from the past or future, and it's all `int64`s inside.

**Comment by gouthamve** [comment]
Another side-effect is that people should be able to send a sample 1hr into the past (relative to the latest sample ingested). Say there is a job running that is sending data to TSDB and for some reason that job is broken and restarted after a few hours, it can no longer ingest data relatively close (but in the past) to the highestTimestamp point if we auto trigger a compaction.

Having said all this, I am open to making this is a configuration option. Though at that point it might as well be handled in Cortex itself.

**Comment by pracucci** [comment]
> This could actually break users if they're trying to ingest old data, the timestamp of samples isn't necessarily now.

I agree. I'm wondering if a solution like "no samples appended to the head since X time" may solve this problem.

> can we work around this in Cortex by manually triggering a compaction?

Sure, but how? To my understanding, as of today there's no way to trigger TSDB to "cut a new block from head" unless using `db.Snapshot()` which does more things (to my understanding).

**Comment by gouthamve** [comment]
> cut a new block from head

I think its reasonable to add a method that does that.

**Comment by brian-brazil** [comment]
> I am open to making this is a configuration option. 

Given the above discussion, I don't see how this could be configured sanely. Too much business logic, and also logic that Prometheus doesn't need.

> unless using db.Snapshot() which does more things 

It does fewer things, it will however produce a block from the head.

**Comment by brancz** [comment]
Let's set the implementation aside for a second, because I do feel there is a legitimate case to be made here for bursty environments, let's say a Prometheus server that is monitoring CI environments, are we really saying that it's fine to say the Prometheus server will continue to use whatever memory usage it had at the end of the job? I would expect that that wouldn't be the case indefinitely, and that I don't have to manually call an API to get Prometheus to not hog the memory it doesn't truly have to anymore. Just thinking out loud: maybe this is less of a problem once we offload more of the head block memory usage (I believe what @codesome is already working on)?

**Comment by brian-brazil** [comment]
> it's fine to say the Prometheus server will continue to use whatever memory usage it had at the end of the job?

You need to provision for peak memory usage one way or the other. Even in the CI case, it'd seem odd that you'd have zero targets sometimes.

**Comment by gouthamve** [comment]
Ah, this is again depending on time.Now() and I'd much rather if Prometheus
triggered the compaction rather than TSDB internally doing it.

Further as Brian said, any Prometheus also scrapes itself ;) Even in the CI
you'd most likely never hit this because of the above.

**Comment by codesome** [comment]
Closing this after some valid concerns raised above. It looks like not feasible/possible.
