### ISSUE TITLE
Compaction runs forever and WAL grows until OOM

### ISSUE THREAD

**Issue by mback2k** [prometheus/prometheus#6655]
## Bug Report
This is a similar issue as https://github.com/prometheus/prometheus/issues/6408 and https://github.com/prometheus/prometheus/issues/6595.

**What did you do?**
I am running Prometheus with default retention and TSDB settings. It is scraping ~4k metrics per second.

**What did you expect to see?**
I expected the WAL to stay small and new compact TSDB block to be created.

**What did you see instead? Under which circumstances?**
Under steady load of ~4k metrics/second, the compaction seems to run forever, leading to the WAL and RAM filling up until OOM. Due to this checkpointing also fails, Prometheus crashes unclean and the cycle repeats.

**Environment**

* System information:

Production: Linux 4.9.0-4-amd64 x86_64
Reproduced on: Darwin 18.7.0 x86_64

* Prometheus version:

Production: Docker image of 2.15.2
Reproduced with: 669592a2c4d59697ce3f654db2c1e7d5e3d42714

* Alertmanager version:

not relevant

* Prometheus configuration file:

not relevant

* Alertmanager configuration file:

not relevant

* Reproduced with code:

```go
package main

import (
	"github.com/prometheus/prometheus/tsdb"
)

func main() {
	db, err := tsdb.OpenDBReadOnly("data", nil)
	if err != nil {
		panic(err)
	}
	defer db.Close()

	err = db.FlushWAL("data")
	if err != nil {
		panic(err)
	}
}
```

* Logs:

no relevant errors or messages in log, no output is printing during compaction running forever at 100% of one CPU core.

* Probable root cause:

During my reproduction I let the FlushWAL run until the RAM usage of my little program no longer went down (starting at ~8 GB after TSDB and WAL load, down to ~500 MB). Then I paused the program with the debugger and detected the following situation:

I am running into the case of batchNames staying empty for every iteration of the top level for-loop here:
https://github.com/prometheus/prometheus/blob/669592a2c4d59697ce3f654db2c1e7d5e3d42714/tsdb/index/index.go#L815-L827

The first label position is 20814, while maxPostings is 19476 and that causes it to break on the first iteration of the inner for-loop, leaving names[] untouched and batchNames empty and that causes it to get stuck in an endless loop.

**Comment by mback2k** [comment]
Here is a screenshot showing the exact state of the relevant variables via debugger:
<img width="1206" alt="debug" src="https://user-images.githubusercontent.com/231943/72662532-afa14880-39e8-11ea-89ee-ddf5a0b22876.png">

**Comment by brian-brazil** [comment]
I can't reproduce this with the wal examples that were provided privately.

**Comment by mback2k** [comment]
Here is a pprof from the issue happening on my production system:
https://www.dropbox.com/s/2at6k1qga59bixs/pprof001.svg?dl=0

**Comment by roidelapluie** [comment]
I can reproduce with different values w.labelNames[names[0]] 22808, maxPostings, 22611

**Comment by mback2k** [comment]
So, I think I found the root cause / circumstances that lead to this WAL situation.

I am running all my exporters in ephemeral docker containers and therefore use a small proxy to add the `hostname` label to all metrics during scraping. This proxy [had a bug](https://github.com/mback2k/node_exporter_hostname/commit/ec67780173967d6509196f1e9d4f04d3aac96491) that it would also add the `hostname` label to metrics that already had it from the original exporter.

Timeline of events:
1. I am running my little proxy and a prometheus version pre 2.15 until December 2019.
2. I am upgrading prometheus to 2.15.2 at the beginning of January 2020 via `docker stack deploy`.
3. I am seeing OOM crashes shortly after and we later find out that the `hostname` label count is higher than the `__name__` count.

I would propose to add the following checks to prometheus:
1. Checking for duplicate labels per metric during scraping.
2. Handling the case of batchNames staying empty gracefully.

@brian-brazil @roidelapluie What do you think about this?

**Comment by brian-brazil** [comment]
>  am seeing OOM crashes shortly after and we later find out that the `hostname` label count is higher than the `__name__` count.

You mean instance rather than `__name__`.

> use a small proxy to add the hostname label to all metrics during scraping.

This is what service discovery and relabelling is for.

**Comment by mback2k** [comment]
> > am seeing OOM crashes shortly after and we later find out that the `hostname` label count is higher than the `__name__` count.
> 
> You mean instance rather than `__name__`.

No, I mean `__name__`, just like @roidelapluie wrote in IRC. If I understand it correctly this means there are more references to the `hostname` label than to the metric `__name__` and that shouldn't be the possible.

> > use a small proxy to add the hostname label to all metrics during scraping.
> 
> This is what service discovery and relabelling is for.

I am aware of the best practices shown in the documentation, but I am still free to add the label that way. Unless Docker Swarm service discovery is build in and is able to produce a static identifier (which it probably won't unless Docker Swarm finally provides static SRV records per node), I have to do something like that to know which host/node the metrics are coming from.

Regardless, I think the reasoning for me doing this is out of scope for the technical issue here. IMHO prometheus could check and warn about duplicate labels during scraping. And the code here should probably be updated to handle this case gracefully by checking the batchNames is not empty before breaking:
https://github.com/prometheus/prometheus/blob/669592a2c4d59697ce3f654db2c1e7d5e3d42714/tsdb/index/index.go#L815-L827

**Comment by mback2k** [comment]
I just saw that @roidelapluie already proposed https://github.com/prometheus/prometheus/pull/6660 to catch this error during scraping.

I think this is the best idea, but do you think the WAL code should also be made more tolerant by doing the `batchNames  > 0` check?

**Comment by roidelapluie** [comment]
If we can produce a test for it that could be a solution. But there are other solutions there, like fixing maxpostings.

**Comment by brian-brazil** [comment]
The problem here is that the head contains bad data, so we need to fix the bad data.

**Comment by mback2k** [comment]
@brian-brazil I totally understand, but I still think the code should at least check for `batchNames > 0` and error out if that is not the case after the inner for-loop to avoid an endless outer for-loop.

An explicit check and error is better to have than an endless loop others may run into later on again.

**Comment by brian-brazil** [comment]
That doesn't solve the problem though, you'd still end up with a broken Prometheus.

**Comment by mback2k** [comment]
Yeah, that is why I would like to see an error here, right? That is still better than an endless loop.

**Comment by brian-brazil** [comment]
It needs to be caught much earlier, as I doubt this is the only problem it causes.

**Comment by mback2k** [comment]
I get that, I personally just think that if "w.labelNames[names[0]]+c > maxPostings" and "len(batchNames) == 0" being an invalid situation, it should bail out here just in case.

**Comment by sanamana** [comment]
We ran into this recently and wanted to share a few thoughts.
We have a slightly different setup. Our TSDB is the prometheus tsdb engine fronted by handlers than expose remote write apis. We are pushing data to the instance, there is no scraping.

I agree it is bad data that causes this issue. However, I also feel that TSDB can fail fast, instead of having it spin continuously. If an invariant is not satisfied, then the TSDB should fail fast. Otherwise, the TSDB will fail much later.

tsdb project was independent of prometheus repo a few months back. It is now part of prometheus repo, but I think there will cases where it will be used separately.

**Comment by roidelapluie** [comment]
We now (2.16.0) refuse to add such bad data (assuming that labels are sorted). We will still run forever if data is corrupt. I agree we should address this, but in a way that causes the minimal impact.

Regarding the usage of tsdb: we are aware that people are using the package. Some discussion is happening on the mailing list: https://groups.google.com/d/msgid/prometheus-developers/55776f4a-b073-4bc1-a470-622d9c318344%40googlegroups.com

**Comment by roidelapluie** [comment]
Let's add an error if we enter this endless loop.
