### ISSUE TITLE
Throttle Checkpoint Activity

### ISSUE THREAD

**Issue by PeterZaitsev** [prometheus/prometheus#6665]
## Proposal
**Use case. Why is this important?**

Currently during Check-pointing Prometheus uses a lot of resources which can severely impact performance if running on smaller memory-constrained systems, severely impacting concurrent query performance and scraping performance 

It would be great instead to have an option to throttle checkpoint speed or even better have automatic adaptive checkpoints and chunk merge process. 

Instead of trying to do checkpoint or chunk merge as soon as possible  Prometheus could look at completion target time (for example 15 minutes) and throttle the process to proceed at the pace to complete in this point in time.

**Comment by brian-brazil** [comment]
Checkpointing is related to head handling, and has to happen every 2 hours. It's also limited to a core, so as long as you provision a core for it you're fine.

You do not want to throttle checkpoints, that can result in a performance spiral.

**Comment by PeterZaitsev** [comment]
Yes I understand.   And this is what I'm saying instead of having it take couple of minutes why not nave it take 15 minutes every 2 hours, or other amount which you consider safe.   If the system is designed so it can run on the slow spinning drive I assume it should also be able to be ran on the faster SSD... but just use the same amount of IOPS 

The CPU usage is not the problem. The problem is the amount of Disk IO done - specifically chunk merging tends to wash out cache slowing down performance critical stuff significantly. 

Note this is problem well understood in the conventional database space -  MySQL/Innodb uses fuzzy checkpointing,  RocksDB  (which is more similar to Prometheus) has controls on how much resources LSM  background merge will take from foreground load.

**Comment by brian-brazil** [comment]
IOPS shouldn't be an issue, it's all sequential writes.

**Comment by roidelapluie** [comment]
Increasing the length of checkpoints to 15 minutes also means that if prometheus is stopped during this time it will be required to re-do the checkpoint again.

**Comment by PeterZaitsev** [comment]
Yes, But if  Prometheus is 1.45h after previous checkpoint and it is stopped does not it mean it would have to do a lot of work already ? 

Just to be clear I'm not saying it is best solution for every case. I'm  just saying in many cases when resources are limited you want to avoid huge spikes of resource consumption when possible.  It is never really free

I mentioned cache clearing but there are other problems as well - if you use network attached storage you can easily saturate network with pushing on it with full capacity which other impacts.

**Comment by brian-brazil** [comment]
Checkpoints and compactions also can't run at the same time (among other things, so we know they only use one core). A checkpoint is also similar to the work done at startup, and I don't think it'd be wise to slow that down too - but if you want to ionice exists.

**Comment by PeterZaitsev** [comment]
The work you do at startup is completely different.  The engine is not able to serve any additional traffic until recovery is complete so you want to do it as quickly as possible.... When system IS serving the traffic you want to make sure the background activities has minimal impact of that traffic. 

The CPU core in this case is not the problem.    IOnice does not really help to the problems I described. 

We had dealt with similar problems in Percona Xtrabackup hence had to introduce limits how quickly backup will proceed - critical for some systems but not used at all for others. 

Now I totally can understand if you do not see enough of this problem in production for Prometheus in particular to have it worth fixing I can understand this point of view, just do not tell me it does not exist.

**Comment by roidelapluie** [comment]
For sure @SuperQ also sees a lot of Prometheus in the wild getting deployed with gitlab.

Ben, can we get your opinion about this?

**Comment by SuperQ** [comment]
This seems out of scope for Prometheus. Resource controls and sharing should be handled at other layers. For example, this is something easily done by [systemd resource-control options](https://www.freedesktop.org/software/systemd/man/systemd.resource-control.html).

As long as Prometheus is not blocking system resource by acquiring exclusive locks, the OS is better suited to handle scheduling.

**Comment by roidelapluie** [comment]
We have been looking at this in our bug scrub and agreed with @SuperQ that this is out of scope for Prometheus.
