### ISSUE TITLE
Gaps in result time series for _over_time functions

### ISSUE THREAD

**Issue by itsx** [prometheus/prometheus#6674]
## Bug Report
**What did you do?**
I have time series without any gaps:  ``probe_duration_seconds{datacenter="C"}`` (It is scraped with 1s interval).
When I plot it in the Expression browser I see all datapoints:

![gi-nomax](https://user-images.githubusercontent.com/15692136/72806345-4d00b480-3c55-11ea-8065-bf8f9c52c18c.png)

Than I do this query in the Expression browser:
``max_over_time(probe_duration_seconds{datacenter="C"}[15s])``

**What did you expect to see?**

I expect to see result time series without any gaps.

**What did you see instead? Under which circumstances?**

Resulting time series has two gaps.
![gi-gaps](https://user-images.githubusercontent.com/15692136/72806251-14f97180-3c55-11ea-8ee3-6b41eb2c98b7.png)
When I do the same query but with added resolution, gaps disappear:

``max_over_time(probe_duration_seconds{datacenter="C"}[15s:1s])``

![gi-res](https://user-images.githubusercontent.com/15692136/72810176-5261fd00-3c5d-11ea-8933-ec59d118a5a9.png)

I have spotted only this two gaps so far (in a cca 1w interval)
Also for all other **_over_time** functions, there are gaps on the same place.

**Environment**
Prometheus Docker image running on Ubuntu 18.04 LTS, Prometheus with 1w retention, Thanos

* System information:

Docker image:  ``prom/prometheus:v2.15.2``
```
/prometheus $ uname -srm
Linux 4.15.0-54-generic x86_64
```

Runs on Ubuntu 18.04 LTS:
```
:~$ uname -srm
Linux 4.15.0-54-generic x86_64
```

* Prometheus version:
```
/prometheus $ prometheus --version
prometheus, version 2.15.2 (branch: HEAD, revision: d9613e5c466c6e9de548c4dae1b9aabf9aaf7c57)
  build user:       root@688433cf4ff7
  build date:       20200106-14:50:51
  go version:       go1.13.5
```

* Docker run command for prometheus:

```
sudo docker run --name prometheus -d --restart=always \
--network=host \
-v prometheus-storage:/prometheus \
-v /etc/prometheus:/etc/prometheus \
prom/prometheus:v2.15.2 \
--config.file=/etc/prometheus/prometheus.yml \
--web.external-url="http://"`hostname -f`":9090" \
--storage.tsdb.max-block-duration=2h \
--storage.tsdb.min-block-duration=2h \
--web.enable-lifecycle \
--web.enable-admin-api \
--storage.tsdb.retention.time=1w
```

**Comment by roidelapluie** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by roidelapluie** [comment]
You can see that by running probe_duration_seconds{datacenter="C"}[1h] in the table view.

**Comment by roidelapluie** [comment]
Note that with added resolution it works because it will run probe_duration_seconds{datacenter="C"} every second, end therefore will have the 5 minute loopback.
