### ISSUE TITLE
Remember current query paramenters when switching to React UI

### ISSUE THREAD

**Issue by kustodian** [prometheus/prometheus#6685]
## Proposal
Our monitoring alerts have links to Prometheus queries, so when we open those Prometheus links and later press `Try experimental React UI` it doesn't remember any of the query parameters, which makes it harder to try to use it and test it out.

## Bug Report
Type some query on the Graph page and click on `Try experimental React UI`. All query parameters are lost, but they should be remembered so that you can continue the investigation in the new UI where you left of.

* Prometheus version:

	2.15.1

**Comment by boyskila** [comment]
I'll take a look

**Comment by boyskila** [comment]
@kustodian I would add that vice versa is also not working
