### ISSUE TITLE
Rule group metrics are not unregistered when the group is removed

### ISSUE THREAD

**Issue by bboreham** [prometheus/prometheus#6689]
When Prometheus sees a new rules file it will register new metrics [here](https://github.com/prometheus/prometheus/blob/fafb7940b1cdb24cada28a713fbcc01ed1e2d585/rules/manager.go#L245)

However there is no code to remove those metrics when the rule file is removed, so metrics like `prometheus_rule_group_last_evaluation_timestamp_seconds` will keep being scraped at their last value until Prometheus restarts.  This makes those metrics hard to use in dashboards, alerts, etc.

**Comment by roidelapluie** [comment]
I will work on this in the coming days.

**Comment by roidelapluie** [comment]
Closed by #6693.
