### ISSUE TITLE
allow min/max to accept multiple instant vectors or create least/greatest functions

### ISSUE THREAD

**Issue by pinkavaj** [prometheus/prometheus#6690]
## Proposal

Using patterns like `a < b or b` works, but is cumbersome and prone to errors, especialy when `b` is complex expression.

Possible solutions:
* create separate function like `greatest(v1, v2, ..)`.
* allow somethink like `max(v1, v2, ...)`.
* extending `clamp_max()` to allow instant vector as a second

Might be related to !5177

**Comment by brian-brazil** [comment]
Only binary operators can do vector matching, and considering you can already do this in PromQL I don't think we should be adding additional complexity to the language.

**Comment by pinkavaj** [comment]
Ok then, if someone feels it deserves more attention, feel free to reopen.
