### ISSUE TITLE
React UI: Implement "Consoles" link

### ISSUE THREAD

**Issue by juliusv** [prometheus/prometheus#6705]
The old UI shows a "Consoles" link in the nav at the top when [user-defined console templates](https://prometheus.io/docs/visualization/consoles/) are present. See for example the top nav at http://demo.robustperception.io:9090/graph.

The new UI does not need any changes regarding serving console templates themselves (this will still be handled by existing functionality in Prometheus that is not part of the "old" UI), but we do need to determine whether console templates are present or not, in order to know whether we should display the "Consoles" link at the top. Here is where that determination was made in the old UI:

https://github.com/prometheus/prometheus/blob/ddd49b743c1c03527064d38f4830258b4a6ccb27/web/ui/templates/_base.html#L44-L47

https://github.com/prometheus/prometheus/blob/ddd49b743c1c03527064d38f4830258b4a6ccb27/web/web.go#L963

There's two ways we could do this in the new UI:

- Add an API call that gives us this info. Drawback is that initially on page load, the "Consoles" link will not be shown, and then it appears.
- Inject a global variable into the index.html that gives us the information we need. We already do this with the global path prefix here: https://github.com/prometheus/prometheus/blob/ddd49b743c1c03527064d38f4830258b4a6ccb27/web/ui/react-app/public/index.html#L17 and here: https://github.com/prometheus/prometheus/blob/ddd49b743c1c03527064d38f4830258b4a6ccb27/web/web.go#L384

I like the second option more because we already have that ugly placeholder pattern anyway, and it immediately gives us the right nav at the top.

**Comment by drumilpatel2000** [comment]
@juliusv Can I take up this issue?

**Comment by juliusv** [comment]
Yep! And I see you already did :)
