### ISSUE TITLE
Failed to start if add wmi_exporter config (align  the config )

### ISSUE THREAD

**Issue by dhimasdjoe** [prometheus/prometheus#6715]
**My topology ex:**
I have centos vps on azure : 192.168.1.1 (ip for example, in case use ip public)
i have windows server 12 r2 on aws clouds : 192.168.2.1 (ip for example, in case use ip public)

**ket :**
on azure and on aws windows server 12 r2 , i have allow inboun and outbond port from 0-6000 with all protocol (tcp, udp etc)

**study case :** 
I install and run promotheus in centos and work 100%
this is my default configuration in prometheus
![image](https://user-images.githubusercontent.com/60417428/73329037-91600600-428e-11ea-89d2-9318bac18b94.png)
after that i want to monitor windows server, i install and run wmi_exporter and work 100%
- I can acces the metrics with ip public from anywhere
  http://prntscr.com/quc485

**case :**
- After all server it ok , now i want to integrity to prometheus server but after i add  config file in prometheus , prometheus failed to run
- this is the additional config 
![image](https://user-images.githubusercontent.com/60417428/73329299-b99c3480-428f-11ea-9bc7-f17cafb5aab2.png)
- this is failed log
![image](https://user-images.githubusercontent.com/60417428/73329474-6676b180-4290-11ea-8c4c-5d81cd6133b5.png)

i need help , thank

**Comment by roidelapluie** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by roidelapluie** [comment]
In your case you need to align job_name and static_configs vertically. Your config yaml is not valid.

**Comment by dhimasdjoe** [comment]
DONE thanks .. 
![image](https://user-images.githubusercontent.com/60417428/73332888-b8bcd000-429a-11ea-8f67-1f490616fa58.png)

**Comment by dhimasdjoe** [comment]
i will update the topic so other people understand
