### ISSUE TITLE
Have a promtool subcommand for checking targets health status

### ISSUE THREAD

**Issue by Tormenta74** [prometheus/prometheus#6723]
## Proposal

Sometimes custom exporters are unstable and under development, so regularly checking on their health status is pretty important. The only way to do this through Prometheus (that I know of) is checking the web app under Status > Targets.

I think it falls under the possible use cases of `promtool` to perform checks on these targets, whether it's the health status or the number of targets up, perhaps through a `check target` subcommand.

**Comment by brian-brazil** [comment]
Prometheus itself can already do this, it's what it's designed for.

**Comment by roidelapluie** [comment]
If you really want it in promtool..  `promtool query instant https://prometheus.demo.do.prometheus.io up`

**Comment by Tormenta74** [comment]
@roidelapluie I missed that way to do it, thanks! Feel free to close if the proposal is out of scope or uninteresting for the project.
