### ISSUE TITLE
Issue with prometheus setup with isito

### ISSUE THREAD

**Issue by HanithaKrishnaraj** [prometheus/prometheus#6731]
I am facing below issue
Target "prometheus" in docker image is always DOWN

I have updated the prometheus config yml file with  my jobname as per below link
https://dzone.com/articles/prometheus-metrics-for-microprofile-microservices

I am not able to get the metrics in prometheus dashboard but can see the stat metrics.

**Comment by codesome** [comment]
This looks like a usage/support question and not related to Prometheus development. Please use user mailing lists for such questions which you can find here https://prometheus.io/community/
