### ISSUE TITLE
Remove LookbackDelta and DefaultEvaluationInterval from the global variables of promql

### ISSUE THREAD

**Issue by roidelapluie** [prometheus/prometheus#6739]
## Proposal
**Use case. Why is this important?**

The behaviour of a PromQL engine should not depend on global variables of the PromQL package, especially when we alter those global variables at runtime.

https://github.com/prometheus/prometheus/blob/0e912faf4f52ed3f803cc18d0ebbd4eb0ba5a8bd/promql/engine.go#L55-L63

Therefore I would like to move them as EngineOpts

https://github.com/prometheus/prometheus/blob/0e912faf4f52ed3f803cc18d0ebbd4eb0ba5a8bd/promql/engine.go#L216-L223

**Comment by brian-brazil** [comment]
Do you have a particular use case in mind, or just general refactoring? The
last time this came up it was a misunderstanding of storage and PromQL
semantics.

**Comment by roidelapluie** [comment]
It is general refactoring which I would like to use later to improve testing on these features.

The context one is just general refactoring.

**Comment by roidelapluie** [comment]
LookbackDelta has been refactored in #6746.
