### ISSUE TITLE
many-to-many matching not allowed with * and GROUP_LEFT

### ISSUE THREAD

**Issue by xxxbobrxxx** [prometheus/prometheus#6743]
**What did you do?**

Using prometheus-operator metrics try with query like:

```
instance:node_cpu_utilisation:rate1m
* ON (pod, namespace) GROUP_LEFT(node) kube_pod_info
```

Where record instance:node_cpu_utilisation:rate1m has unique pod values on all inspected time range

**What did you expect to see?**

Elements of instance:node_cpu_utilisation:rate1m record with **node** label joined

**What did you see instead? Under which circumstances?**

Multiplication fails with error like:

```
Error executing query: found duplicate series for the match group {namespace="monitoring", pod="alertmanager-prometheus-operator-alertmanager-0"} on the right hand-side of the operation: [{__name__="kube_pod_info", created_by_kind="StatefulSet", created_by_name="alertmanager-prometheus-operator-alertmanager", host_ip="10.142.1.76", instance="kube-state-metrics", job="kube-state-metrics", namespace="monitoring", node="gke-bsw-api-dev-monitoring-ec273c71-7bcn", pod="alertmanager-prometheus-operator-alertmanager-0", pod_ip="10.40.41.24", uid="ac7e8fa5-469c-11ea-aa85-42010a8e0151"}, {__name__="kube_pod_info", created_by_kind="StatefulSet", created_by_name="alertmanager-prometheus-operator-alertmanager", host_ip="10.142.1.76", instance="kube-state-metrics", job="kube-state-metrics", namespace="monitoring", node="gke-bsw-api-dev-monitoring-ec273c71-7bcn", pod="alertmanager-prometheus-operator-alertmanager-0", pod_ip="10.40.41.2", uid="8bcff5ad-439e-11ea-9c90-42010a8e006a"}];many-to-many matching not allowed: matching labels must be unique on one side
```

But this rows with this **pod** label are not present in left side and should be ignored.

**Environment**

* System information:

Kubernetes 1.14.8 with prometheus-operator helm chart 8.7.0

* Prometheus version:

Verified on:

- 2.12.0
- 2.15.1
- 2.15.2

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
