### ISSUE TITLE
high CPU usage for arm system

### ISSUE THREAD

**Issue by fcddk** [prometheus/prometheus#6749]
node env:
4.15.0-55-generic #60-Ubuntu SMP Tue Jul 2 18:23:38 UTC 2019 aarch64 aarch64 aarch64 GNU/Linux
cpu info:
Architecture:        aarch64
Byte Order:          Little Endian
CPU(s):              16
On-line CPU(s) list: 0-15
Thread(s) per core:  1
Core(s) per socket:  16
Socket(s):           1
NUMA node(s):        1
Vendor ID:           0x70
Model:               2
Stepping:            0x1
BogoMIPS:            100.00
NUMA node0 CPU(s):   0-15
Flags:               fp asimd evtstrm crc32 cpuid

prometheus version: 2.10.0

high cpu uasge: 1000%

**Comment by fcddk** [comment]
go tool pprof profile
File: prometheus
Type: cpu
Time: Feb 4, 2020 at 4:19pm (CST)
Duration: 30.14s, Total samples = 53.64s (177.95%)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top
Showing nodes accounting for 49.35s, 92.00% of 53.64s total
Dropped 335 nodes (cum <= 0.27s)
Showing top 10 nodes out of 73
      flat  flat%   sum%        cum   cum%
    34.34s 64.02% 64.02%     38.90s 72.52%  runtime.scanobject
     5.48s 10.22% 74.24%      5.48s 10.22%  runtime.memclrNoHeapPointers
     3.93s  7.33% 81.56%      3.93s  7.33%  runtime.memmove
     1.17s  2.18% 83.74%      1.17s  2.18%  runtime.(*mspan).base
     1.03s  1.92% 85.66%      1.03s  1.92%  runtime.heapBits.bits
     1.03s  1.92% 87.58%      1.30s  2.42%  runtime.markrootSpans
     0.79s  1.47% 89.06%      0.79s  1.47%  runtime.spanOf
     0.76s  1.42% 90.47%      0.76s  1.42%  runtime.markBits.isMarked
     0.46s  0.86% 91.33%      0.46s  0.86%  github.com/prometheus/prometheus/pkg/textparse.(*promlexer).next
     0.36s  0.67% 92.00%      0.82s  1.53%  github.com/prometheus/prometheus/pkg/textparse.(*promlexer).Lex

**Comment by roidelapluie** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
