### ISSUE TITLE
Consider moving to https://github.com/friendsofgo/errors

### ISSUE THREAD

**Issue by bwplotka** [prometheus/prometheus#6751]
Similar to https://github.com/thanos-io/thanos/issues/1794 but for Prometheus.

I can see we are inconsistent. Sometimes we use `fmt.Errorf` sometimes `errors.Wrap`. And even if we will refactor everything to one thing, sill our dependencies can do any of those.

Why is that problem? 
* Inconsistent stype error or printed error
* Go 1.13 errors introduced `Is` and `As` methods. Those are not compatible with pkg/errors `Cause` and `Wrap`.

I would vote for using https://github.com/friendsofgo/errors for those for now as it combines both worlds. This is the key if we will start to rely on wrapped errors from libraries using Go1.13 errors (I don't think we do yet)

Some of this is was discussed [here](https://github.com/pkg/errors/issues/202). Low priority as we don't rely on that now.

**Comment by roidelapluie** [comment]
Note: circle ci is still on go1.12 for windows tests.

**Comment by bwplotka** [comment]
Not needed anymore: https://github.com/pkg/errors/commit/6d954f502eb89cd315e4baae5b0e0db516d6f787
