### ISSUE TITLE
customize metrics to be stored on local disk to save storage

### ISSUE THREAD

**Issue by codwu** [prometheus/prometheus#6757]
## Proposal
**Use case. Why is this important?**
My Prometheus scrape thousands of targets and stores the data on local disk.  The disk usage is very high now. In fact, most of the metrics are not important for me. I wonder if Prometheus can only store the metrics I care about. It will be very helpful to save storage.

**Comment by codesome** [comment]
You can use the relabeling configs to drop the metrics that you don't want.

For more usage questions, please use user mailing lists and not GitHub issues, which you can find here https://prometheus.io/community/
