### ISSUE TITLE
Support database query for list of nodes

### ISSUE THREAD

**Issue by wrouesnel** [prometheus/prometheus#677]
In cases where you don't have records in DNS SRV for a group of services (probably quite common with node_exporter use cases for example) it would be helpful to be able to specify a postgres or mysql query and server to use as the canonical source for hostnames to a particular job.

This would be useful for interfacing with things like the puppet dashboard or custom tracking solutions where altering DNS is unfeasible.

**Comment by fabxc** [comment]
The problem with unstandardized service discovery is, that we cannot support everything out of the box.
The current approach is to have a file-based fallback interface, about which you can read more in the [design doc](https://docs.google.com/document/d/1vEs0l0oX8npPZw06Vd8j7Ikg-x_NRGQlBuogaF3JbVw/edit?usp=sharing).

Is that something that would work for you?

**Comment by fabxc** [comment]
Closing as we will provide an interface for custom SD adapters and will only add native support for established SD mechanisms.
