### ISSUE TITLE
Performance of v2.16.0-rc.0

### ISSUE THREAD

**Issue by roidelapluie** [prometheus/prometheus#6771]
**What did you do?**

This issue tracks some unexpected performance differences between 2.16.0-rc.0 and 2.15.2.

![image](https://user-images.githubusercontent.com/291750/73934760-66556200-48df-11ea-9664-04d3b9e91466.png)
Allocated is pretty much the same, however RSS is higher (which is harmless)

Allocations are a lot higher
![image](https://user-images.githubusercontent.com/291750/73934908-ae748480-48df-11ea-8e9c-8ac65e9e5493.png)

Response time is higher
![image](https://user-images.githubusercontent.com/291750/73934945-c21feb00-48df-11ea-8075-949b0db10995.png)

did we break these metrics?
![image](https://user-images.githubusercontent.com/291750/73935110-1dea7400-48e0-11ea-8abc-fb813281b207.png)

**Environment**

https://github.com/prometheus/prometheus/pull/6729
http://prombench.prometheus.io/grafana/d/7gmLoNDmz/prombench?orgId=1&var-pr-number=6729

**Comment by slrtbtfs** [comment]
Some notes about the changes that PromQL underwent since the last release:

* The parser was completely rewritten. Since the parsing takes very little time compared to the rest of the engine, it is however relatively unlikely that the performance regressions come from the parser itself.
* There have been two PRs from me, that potentially have an performance impact on the engine: #6612 and #6590. I've reviewed both of them again and didn't see anything that would explain these differences.
* There seem to have been some changes regarding logging. Not sure how these affect things. I guess @roidelapluie and @brian-brazil are more knowledgeable here.

**Comment by roidelapluie** [comment]
If the logging is not enabled there should be no noticeable change.

**Comment by slrtbtfs** [comment]
I've had a look at the PromQL engine benchmarks and both the speed and memory usage seem to have slightly improved, compared to 2.15.2.

**Comment by bwplotka** [comment]
Keep in mind that benchmarks might be missing certain test cases or some
real factors, thus real results might be different. What I am saying that
it is some fact, but we should not completely rule our PromQL changes.

Kind Regards,
Bartek

**Comment by cstyan** [comment]
So after a bunch of prombench runs and bisecting, while looking only at the allocs graphs, it looks like #6591 might be causing the allocation issues. 

The strange thing is running the promql package benchmarks on that commit and 2.15.2 then using benchcmp, the allocs/bytes allocated per test look reasonable but the benchmarks take longer for 6591.

Also strange is that the prombench graphs for that PR show more allocs but that it's avg query latency is less than the query latency for 2.15.2 [here](http://prombench.prometheus.io/grafana/d/7gmLoNDmz/prombench?orgId=1&var-RuleGroup=All&var-pr-number=6591&from=1581051178610&to=1581053467352).

**Comment by beorn7** [comment]
More allocs doesn't necessarily mean lower performance. The code doing more allocs might still be the better performing one if the allocations are offset by a more efficient algorithm. We only need to make sure that the benchmark includes GC cycles. For prombench, I'd expect that to be the case.

So #6591 might cause more allocation but actually _improve_ performance, and the performance regression we see in prombench for the 2.16 RC might be somewhere else…

**Comment by slrtbtfs** [comment]
> Also strange is that the prombench graphs for that PR show more allocs but that it's avg query latency is less than the query latency for 2.15.2.

These observations actually make sense.

#6591 causes the parser to use a sync.Pool, which can be seen as kind of an alternative garbage collector, for some large data structures allocated by the parser.

This bypasses the go garbage collector, thus the parser spends less time with garbage collection which speeds things up.

The somewhat increased allocations might me management overhead, of the sync.Pool, but I'm not really sure about that.

**Comment by roidelapluie** [comment]
> More allocs doesn't necessarily mean lower performance. The code doing more allocs might still be the better performing one if the allocations are offset by a more efficient algorithm. We only need to make sure that the benchmark includes GC cycles. For prombench, I'd expect that to be the case.
> 
> So #6591 might cause more allocation but actually _improve_ performance, and the performance regression we see in prombench for the 2.16 RC might be somewhere else…

Actually, is there something wrong in the relase at all?? CPU is the same, allocated memory is the same.

And The graph with the latency seems broken and the legend format should not be seconds but requests per second.

**Comment by slrtbtfs** [comment]
Heap profiling indicates, that series expansion now allocates a lot more memory, which could mean something is weird.

In the promql engine everything seems to be alright to me.

Not sure about tsdb.

**Comment by roidelapluie** [comment]
Let's close this. Memory looks ok after deeper checks. 2.16 can be released.
