### ISSUE TITLE
solution: accurate `increase` function

### ISSUE THREAD

**Issue by brycedrennan** [prometheus/prometheus#6779]
There has been a frequent request for prometheus to implement an `increase` function that "just works" for the common situation of wanting to know the increase of a counter over time.  The current implementation misses increases at the beginning of a series and between time buckets. 

 See https://github.com/prometheus/prometheus/issues/3806 https://github.com/prometheus/prometheus/issues/1673 https://github.com/prometheus/prometheus/issues/5355 https://github.com/prometheus/prometheus/issues/5850 for further context.

I solved this in my case with the following formula:
```
clamp_min(sum(metric - (metric offset $Interval or (metric * 0))) by (x, y), 0)
```

If this satisfies others who have run into this then I suggest adding it to the documentation.

Pinging @discordianfish @tim-d-blue @Sebubu @pdambrauskas @shuz @paveltyk @remram44 @amadeuszkryze @free @JohannesRudolph for your consideration.

**Comment by brian-brazil** [comment]
This was already discussed in (at least) #3806, it can't handle resets so isn't an appropriate solution. Please keep discussions on this to the existing open issues.

**Comment by brycedrennan** [comment]
it does handle resets.

**Comment by brycedrennan** [comment]
Please re-open.

**Comment by roidelapluie** [comment]
Please keep #3806 to discuss this. That said, your solution does not handle resets properly.

**Comment by brycedrennan** [comment]
This solution doesn't handle resets comprehensively for sure, but it does handle them in a way that many might find useful.  #3806 is a different proposal.
