### ISSUE TITLE
NaN handling in aggregates

### ISSUE THREAD

**Issue by UweOhse** [prometheus/prometheus#6780]
i have a recording rule creating time series with the name:

    hist_50th_percentile:uf_backend_total_seconds:rate5m

# A: NaNs in the series:

Though none of the series of the histogram (_sum, _count, _bucket) have any NaNs in them, the series created by the recording rule above have NaNs in it. For example:

    0.17500000000000002 @1580984806.594
    NaN @1580984836.594
    0.0625 @1580984866.594

This was around 10:27.16 GMT today, and also happened yesterday (@1580894686.594 and 30 seconds later). It seems like this only happened to the time series seeing a moderately low data rate, and the two high traffic label combinations are OK.

The prometheus installation was quite old (2.9.0-rc0), so the problem leading to the NaN has likely been fixed by now anyway, but if not: i found no trace of a problem in any logfile, and the hardware seems to work fine.

# B: aggregates return NaNs, too.

When prometheus (2.9.0 and the 2.15.2 i updated to) tries to create an avg_over_time (or any other aggregate i could use) the calculation returns a NaN, too.

I know this is _mathematically_ correct. But is it the most useful answer?

I work around that by using

    avg_over_time((hist_50th_percentile:uf_backend_total_seconds:rate5m{...}!=NaN) [7d:6m]) 

This makes my rules even harder to read, and no one who hasn't been bitten by the next point will ever understand why i used '6m'.

# C: an avg_over_time(... != Nan) [7d:5m]) returns NaN, too.

The most surprising thing here is that if i change the sub query to 5 minutes, the query returns NaNs starting at 1580894686.594. This must not happen, and it only happens with 5m, not 4 or 6. Is there some kind of optimization at work which ignored the != NaN filter?

I can make that prometheus installation accessible if needed.

**Comment by lingpeng0314** [comment]
So is there any mailing thread for the issue reported here? @UweOhse
