### ISSUE TITLE
incorrect value for remote write metric pending_samples

### ISSUE THREAD

**Issue by helenxu1221** [prometheus/prometheus#6797]
**What did you do?**
send samples to remote storage.

**What did you expect to see?**
pending_samples stays around 0 most of the time when everything works fine.

**What did you see instead? Under which circumstances?**
pending_samples kept increasing even though all the samples were send to remote server successfully.

**Environment**

* Prometheus version:

prometheus, version 2.14.0 (branch: release-2.14, revision: edeb7a44cbf745f1d8be4ea6f215e79e651bfe19)

This issue happens when the total number of samples is lower than max_samples_per_send.

**Comment by csmarchbanks** [comment]
Fixed in #6798
