### ISSUE TITLE
Scrape size metric?

### ISSUE THREAD

**Issue by gsstark** [prometheus/prometheus#6803]
We currently have a metric for scrape_duration but nothing for the number of bytes in a scrape. It's hard to tell what caused a change in the scrape duration if you can't tell whether the volume of data is changing along with it. It would also be really helpful to be able to recognize bandwidth limitations or calculate network capacity requirements.

**Comment by roidelapluie** [comment]
We don't have such a number because prometheus will save the content of the scrape in its tsdb. You can use `{job="myjob"} unless {job="myjob"} offset 1h` to see which new metrics are added.
The last release candidate of prometheus has related metrics about the scrape cache that will help with this too.

**Comment by gsstark** [comment]
I don't see how to calculate the byte size of the scrape from the number of metrics. It depends heavily on the size and number of labels, the size of the HELP texts, etc. Not all the metrics in the scrape will even be added if there's a filter. The size of the tsdb is an important thing to manage but it's orthogonal to having network issues due to scrape sizes.

**Comment by brian-brazil** [comment]
scrape_samples_scraped should be enough of a proxy for that. Anything like this would be an additional sample be ingested on every single scrape by every single user, and I don't think this meets that bar.

**Comment by roidelapluie** [comment]
We have looked at this during our bug scrub and decided to close this, as adding that metric for every scrape it is pretty expensive. We also have metrics around metadata cache if that's the issue you try to address.

Thanks!
