### ISSUE TITLE
Allow set default port in scrape_config

### ISSUE THREAD

**Issue by PickingUpPieces** [prometheus/prometheus#6805]
## Proposal
At the moment, if you don't specify a port for a target, Prometheus uses port 80. It would be nice if you could set the default port for an individual job. 
 - job_name: 'infrastructure'
   static_configs:
   - port: 9100
     targets:- xyz.com

 

**Use case. Why is this important?**
If you use file-discovery, you can't monitor the same group (The same file) with different exporters, because the exporters need different ports. This feature would reduce redundancy in the config file and make it easier to update a group of hosts.

**Comment by brian-brazil** [comment]
You can already do this with relabelling, and in this case you can also specify xyz.com:9100.

**Comment by PickingUpPieces** [comment]
oh thanks @brian-brazil :D my bad...
