### ISSUE TITLE
Consider removing default port support

### ISSUE THREAD

**Issue by fabxc** [prometheus/prometheus#681]
Currently target hosts can be provided without a port name. Based on the scheme the default port is selected.

Prometheus is not a browser and usage of default ports is an exception rather than the rule. Removing this _feature_ will give developers and users one thing less to think about.

Thoughts?

**Comment by juliusv** [comment]
Not sure if this behavior should be specific to a browser - port 80 and 443 are standard well-known default ports for HTTP and HTTPS, regardless of client application (http://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml?&page=2). So it might even be less surprising to keep it.

**Comment by fabxc** [comment]
Of course it's not specific to browsers — but for Prometheus scraping from the default ports is not the normal case and a regular SD usually provides a port.
I just feel weird about interpolating the identifier for a scrape target, which should usually be a very explicit thing.

**Comment by juliusv** [comment]
Yeah, I don't feel strongly about this - do whatever feels best :)

**Comment by fabxc** [comment]
Ultimate compromise: we infer the port when we get receive the target group and thus only create targets from full `<host>:<port>`s. _(And remove a potential dead lock with that.)_

**Comment by juliusv** [comment]
Can be closed now, I guess?

**Comment by fabxc** [comment]
Yes
