### ISSUE TITLE
Query `HELP` field for a metric

### ISSUE THREAD

**Issue by JensRantil** [prometheus/prometheus#6814]
For technical (but also a bit of security) reasons we have engineers who can't access the Prometheus `/metrics` endpoint of exporters to look at the `HELP` description of metrics. I understand that there is [an API endpoint](https://prometheus.io/docs/prometheus/latest/querying/api/#querying-metric-metadata) that allows for querying for `HELP` description, however there is no GUI option for it.

Feature request: Be able to somehow query for a metric `HELP` description in the GUI.

**Comment by Harkishen-Singh** [comment]
Do we have any plans on this? Like a design doc, or anything related.

**Comment by brian-brazil** [comment]
There's no real need for a design doc for something like this, it's purely a UI feature.

**Comment by roidelapluie** [comment]
Can you please try Prometheus 2.26?

The help is present in the new experimental editor:
![help](https://user-images.githubusercontent.com/291750/113358253-bdb95b80-9345-11eb-80f3-2fc3da187b38.png)

**Comment by beorn7** [comment]
Hello from the bug scrub.

We agree with @roidelapluie that this has been implemented in 2.26. Closing, but please follow up if that's not what you wanted.
