### ISSUE TITLE
"Healthy after" option for alert rules

### ISSUE THREAD

**Issue by mitchellrj** [prometheus/prometheus#6816]
## Proposal
Alerts conditions are currently configured dually as an expression and an optional `for` duration, where the expression has to be true for the entirety of that duration. There is no way of expressing the inverse logic, that an alert is only considered resolved after the expression has been untrue for a set duration.

This is possible to achieve in some circumstance, with clever use of the query language. Construct like `min_over_time` and such are useful for simple conditions.

I propose a new option for alerting rules, `until`, expressing the inverse of the `for` logic.

This is important for circumstances such as (but not limited to):
* a process stuck in a restart loop, constantly notifying down/up/down/up - this adds noise which may distract from other alerts, and contributes to alert fatigue;
* expressions based on metrics retrieved from scrapers; in this case the scraper itself going down or restarting may resolve a valid alert, simply because the values are no-longer present; or a scrape timeout could resolve one alert and then trigger another (instead of both). For example if:
  1. I configure smtp_exporter to retrieve CPU usage from a switch,
  2. The switch exceeds the threshold set my my alert expression,
  3. The SNMP exporter fails to retrieve the next values from the switch because it does not respond in time
  4. Prometheus receives an empty result set from the exporter,
  5. The alert condition is no-longer met (though another one may be), and the alert is instantly resolved.

This will also help to simplify users' rule sets in some circumstances, where as in the above cases, large numbers of `absent` checks are required to achieve similar alert capability. Fewer rules, and less complex rules are good things for performance.

While I'm happy to attempt to contribute, I defer to your expertise for the approach and architecture of such a feature, should it meet with your approval.

**Comment by brian-brazil** [comment]
This is on purpose, and changes like these have been proposed&discussed many times before.

If you've alerts flapping like this, it indicates that your alerts may need being made more resilient, that you may want to put in silences while an issue is being investigated, or that your group/repeat interval in the alertmanager may be too low.

**Comment by mitchellrj** [comment]
Sorry for the repeated proposal, I could not find anything similar when searching Github.

A blog post or some additional documentation on working around this kind of scenario would be very much appreciated.

**Comment by roidelapluie** [comment]
https://www.robustperception.io/running-into-burning-buildings-because-the-fire-alarm-stopped

**Comment by brian-brazil** [comment]
> Sorry for the repeated proposal, I could not find anything similar when searching Github.

I couldn't either, but I know we've had a few.

> simplifying ... rule sets, and the impact on performance still stands.

I don't think that'd work out. You still need all the absent rules anyway, and the additional logic would not be free. Particularly when you get into it working across restarts.

**Comment by mitchellrj** [comment]
Much obliged, folks.
