### ISSUE TITLE
Last date of a range vector

### ISSUE THREAD

**Issue by aclowkey** [prometheus/prometheus#6825]
We have nice functions to handle the values, max_over_time, count_over_time, etc. I wanted to ask if there's a way or to propose it, so we could have functions for the **dates**, and not just the values.

## Proposal
last_over_time( <range-vector> ) - returns the last value within a range

Why is this useful? This could be helpful especially if you have alerts on metrics, and suddenly there is no data. You'd like to know when was the last time I got the data, and then see which events happened at the timestamp, etc.

What do you think?

**Comment by roidelapluie** [comment]
Thank you for your interest in prometheus.

This has been discussed in #1139 #6530.

**Comment by roidelapluie** [comment]
Sorry it is not the same.

You want max_over_time(timestamp(xxx)[24h:])

**Comment by aclowkey** [comment]
Ohhh thanks!
Seems to be what I'm looking for!

**Comment by roidelapluie** [comment]
Glad to help! Should you have more questions about this, feel free to use the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users).

**Comment by aclowkey** [comment]
I'm getting an error with the query;
'query': 1:57: parse error: range specification must be preceded by a
metric selector, but follows a *promql.Call instead

**Comment by roidelapluie** [comment]
You've forgotten the : [24h:]. This is a subquery.

Le dim. 16 févr. 2020 à 17:46, Alex Chaplianka <notifications@github.com> a
écrit :

**Comment by aclowkey** [comment]
Oh Right!
Thank you!
I was wondering about the difference. between [24h] and [24h:].
Any referenced?

**Comment by roidelapluie** [comment]
https://prometheus.io/blog/2019/01/28/subquery-support/
