### ISSUE TITLE
Comments using // no longer work

### ISSUE THREAD

**Issue by stapelberg** [prometheus/prometheus#683]
I think commit https://github.com/prometheus/prometheus/commit/3ca11bcaf58685d3994d6f643fff57075cbed595 broke comment parsing. The following example from http://prometheus.io/docs/querying/rules/ doesn’t pass a rule_checker run anymore:

```
// Saving the per-job HTTP in-progress request count as a new set of time series:
job:http_inprogress_requests:sum = sum(http_inprogress_requests) by (job)

// Drop or rewrite labels in the result time series:
new_time series{label_to_change="new_value",label_to_drop=""} = old_time series
```
```
$ rule_checker docs                      
docs: error checking rules: Parse error at line 1, char 1: no valid statement detected
```

Using # instead of // works, but I’m confused which syntax should work. Looking at the old lexer.l, it seems to have been // or /* */ for multi-line comments. Why did you switch to # if you did, breaking rules files? :(

**Comment by fabxc** [comment]
Yes, we switched to `#` intentionally. The decision was made some time ago, afaik, and this implemented it.

Breaking changes are annoying but squashing them into one release (this and the config changes) will hopefully make it less painful.
Everything required to upgrade will of course be documented with the next release.

**Comment by juliusv** [comment]
FWIW, I think we never documented comments anywhere - so they were a hidden feature up until now. Seems like hidden features are discovered anyways... The decision to change the comment format came mainly from a consensus on IRC that this is the more common comment format for config files.

**Comment by juliusv** [comment]
I have to correct myself: I just noticed we did mention comments indirectly in examples in this one page, although they were never explicitly documented otherwise: http://prometheus.io/docs/querying/rules/. Sorry about that.
