### ISSUE TITLE
Support for windows authentication

### ISSUE THREAD

**Issue by rocklan** [prometheus/prometheus#6835]
## Proposal
Currently a bunch of apps that I support use windows authentication. It would be great to be able to monitor these apps and protect the metrics URL via windows auth. Currently prometheus scraping doesn't support windows auth, only basic auth and oAuth.

Alternatively if windows auth cannot be implemented the ability to add custom HTTP headers might suffice, or even just the ability to specify the exact Authorization header.

**Comment by brian-brazil** [comment]
Thank you for your feature request. To keep things sane we only implement a limited number of standard auth methods, rather than every vendor-specific method and variation. If you really need this then I suggest using the proxy_url feature.

**Comment by rocklan** [comment]
Ok, fair enough, no problems.
