### ISSUE TITLE
HTTP API: Time range selectors for `/api/v1/labels` and `/api/v1/label/<label_name>/values`

### ISSUE THREAD

**Issue by bwplotka** [prometheus/prometheus#6865]
Hi Prometheus Family :wave: 

## What

I would like to propose extending existing HTTP v1 APIs for fetching labels and label values to accept time range selection:

```
start=<rfc3339 | unix_timestamp>: Start timestamp.
end=<rfc3339 | unix_timestamp>: End timestamp.
```

## Why

Nowadays in Prometheus (TSDB) we don't cache all values and label names anymore like we used to do. With mmap + 1/32 symbols and 1/32 posting offset block loading we have now from 2.15, each call for labels or label values will allocate extra memory (+CPU cycles) every time those APIs are invoked. This is fine for small retention, but with years of data, this might be a major bottleneck.

The main problem is that we usually don't need label names or values for EVERYTHING. The typical use case is in dashboards, where we want to know what are metric (e.g `__name__`) values available for certain e.g 1h time range we want to query for! So fetching all names and values for whole available retention is highly unnecessary. Its also both inefficient and incorrect (**this label name might not exist in the certain 1h time range we query for**). Because of that API limitation, even though e.g. Grafana, might know what time range we are interested in, it can't pass this info to Prometheus.

It is even more problematic for LTS solutions like Thanos and Cortex. In fact, Cortex already ignores correctness and returns just ~2h of labels name / values. Thanos is now correct, but with millions of series stored for years, it's super silly to fetch all label names and values for every request. Yes, we can cache things, but it would be awesome if Grafana, Prometheus UI or any client could just select the time range it is interested in.

## How

The proposed solution allows time slicing, but to be fully correct on the Prometheus side (and same will be for Thanos), we would need to perform literally `select` operation to know which labels are within desired time range. We can optimize for the case where time range fully overlaps with block though:

### /api/v1/labels?start=T1&end=T2

* Narrow down to block-level only if we time range fully overlaps with a block time range.
* Perform series call to fetch label names within block otherwise.

### /api/v1/label/<label_name>/values?start=T1&end=T2

* Narrow down to block-level only if we time range fully overlaps with a block time range.
* Perform series call to fetch label names within block otherwise.

Reference: https://github.com/thanos-io/thanos/issues/1811

Thoughts? (: 

@pracucci @brancz @brian-brazil @davkal @tomwilkie ?

**Comment by bwplotka** [comment]
This kind of implementes something similar: https://github.com/prometheus/prometheus/pull/6837/

However:
* Only for  `labelvalues`
* Without my proposed optimization. We might want to expand our `Qurier` interface properly.

**Comment by roidelapluie** [comment]
How does grafana 's label_value work behind the scenes? It seems time bound. What query do they run?

**Comment by brian-brazil** [comment]
I think we should add this, but keep it simple and allow for false positives when the time doesn't exactly align with a block.

**Comment by roidelapluie** [comment]
> How does grafana 's label_value work behind the scenes? It seems time bound. What query do they run?

they use the 'series' api.

**Comment by bwplotka** [comment]
Not always. I think it depends on function @roidelapluie 

@brian-brazil Ok so you propose to just use values/names of block without getting into details, of which of those are actually present for given time range in block?

**Comment by davkal** [comment]
> they use the 'series' api.

Grafana only uses the series API because the labels API did not have time slice support. The series API returns way more data than we need and needs some processing only to get to the label names/values. I'd be very happy to simplify this.

**Comment by krasi-georgiev** [comment]
> /api/v1/labels?start=T1&end=T2

this is already planned as part of https://github.com/prometheus/prometheus/pull/6837

I even think that when we have the matchers filters filter implemented for `/api/v1/labels` the `/api/v1/label/<label_name>/values` will get obsolete.

here is a doc with few examples with matchers and start and end args
https://docs.google.com/document/d/1sbR7WLWrh1f6ptxX3-92sNM4aP1skc5R44LxnikxGVY/edit

**Comment by bwplotka** [comment]
> I even think that when we have the matchers filters filter implemented for /api/v1/labels the /api/v1/label/<label_name>/values will get obsolete.

That's my point. With matcher, why not just use `Series`?

There is still point for those labels and values with just time IMO - we can make it way more faster and efficient.

**Comment by krasi-georgiev** [comment]
> There is still point for those labels and values with just time IMO - we can make it way more faster and efficient.

can you give an example use case for this?

**Comment by bwplotka** [comment]
Look at the current blockQuerier.LabelNames and blockQuerier.LabelValues
implementations. They just work on posting offsets, no more lookup needed.

**Comment by boyskila** [comment]
> With matcher, why not just use `Series`

This was my initial implementation https://github.com/prometheus/prometheus/pull/6837/commits/e7ed5933bd7152f174aa5b534468591d2be45cca
and we (@juliusv, @krasi-georgiev and I) agreed on that it's more cumbersome - in the end, you have to loop all the series again in order to extract needed values

**Comment by kakkoyun** [comment]
@bwplotka @JessicaGreben Do we miss anything for this issue? I suppose it's done by https://github.com/prometheus/prometheus/pull/7288. WDYT?

**Comment by JessicaGreben** [comment]
Oh yeah I think this issue should be considered done. There are a few outstanding comments on that PR #7288, but I can address those offline and we can close this. Thanks @kakkoyun
