### ISSUE TITLE
Limit targets discovered via SD

### ISSUE THREAD

**Issue by gebn** [prometheus/prometheus#6868]
## Proposal

`sample_limit` provides a way to limit the number of time series per target, however there is currently no way to limit the number of targets in the case of service discovery, so Prometheus is still vulnerable to a cardinality explosion.

We could do with a similar option, perhaps `target_limit` at the job level, which either ignores "extra" targets over this limit, or more simply stops scraping every target in the job. The intended use is to prevent a job crashing a Prometheus, so dropping every target in a job is preferable to doing nothing and losing all jobs when the instance crashes.

The limits and current number of targets per job would be exposed as metrics of Prometheus, so we could alert on their ratio and review limits in advance of them being met. Such an option would also help with budget time series per Prometheus shard.

/cc @miekg @tmhdgsn

**Comment by brian-brazil** [comment]
Arbitrarily dropping targets will result in silently lost monitoring, I don't think that's a wise thing to do.

Keep in mind that such a scrape config would likely cover all applications running on your cluster, so you'd effectively be completely blind then.

**Comment by gebn** [comment]
Thanks for the quick response @brian-brazil! I don't think I explained clearly; let me elaborate.

I'm envisaging a target limit to be settable at the job (or individual SD config) level, rather than a global limit for a given Prometheus. If we drop all targets when we hit the limit, a crashed Prometheus is as useful as one not scraping anything - hence the scoping. Meta-monitoring jobs scraping a Prometheus would not have a limit (and would likely be a `static_config` anyway, which doesn't make sense with limits, as it can be checked once when the config is built), so Prometheus would never drop itself as a target.

The use case for this is equivalent to the OOM killer - we obviously don't want to partially lose monitoring, but it's preferable to lose some or all of a job than every job on the Prometheus instance, which would happen if SD returned too many targets for that job, resulting in too much cardinality or simply too many things to scrape. It's undoubtedly a sub-optimal situation, but the lesser of two evils - equivalent to `sample_limit`, just at the target rather than sample level.

To facilitate alerting a human under these circumstances, Prometheus could expose metrics providing the current target count for each job, along with each job's limit for those where one is configured. It would then be possible to create an alerting rule of the form `count / limit > 0.N` to page a human.

**Comment by brian-brazil** [comment]
> I'm envisaging a target limit to be settable at the job (or individual SD config) level, rather than a global limit for a given Prometheus.

I presumed that, in setups where this is likely to come up I'd expect everything relevant to be in one massive scrape_config. This seems like a bit much of a foot gun, if you're that worried then multiple Prometheus servers would be a better approach to performance isolation.

**Comment by gebn** [comment]
True, isolating jobs would also work. Unfortunately we have a *lot* of jobs, some of which are tiny but still require service discovery (I'm not sure what a strategy would be for batching them together - putting important things together doesn't seem to make much sense). Plus replica instances and additional ongoing management etc. I get that we either care enough or we don't; I wonder if this would be a relatively straightforward way to put the key safeguards in place while maintaining the operational benefits of a smaller plant.

**Comment by brian-brazil** [comment]
> (I'm not sure what a strategy would be for batching them together - putting important things together doesn't seem to make much sense). 

In an ideal k8 setup, you can do all your main service/pod monitoring with a single scrape config.

There'll be a few other smaller scrape configs for e.g. the pushgateway, but that's not where the risk is.

**Comment by roidelapluie** [comment]
Duplicate of #7340, which was implemented in 2.21.
