### ISSUE TITLE
promql: Add support for .Select calls concurrency. 

### ISSUE THREAD

**Issue by bwplotka** [prometheus/prometheus#6878]
Hi (again) Prometheus family :wave: 

## Proposal

We noticed with @brancz during our investigations on query latency that `Select` calls done by PromQL are done sequentially: 

![image](https://user-images.githubusercontent.com/6950331/75368505-c9705e00-58b9-11ea-9313-9a8c126aa819.png)

It appears that those are subqueries required for the main (quite complex) instant query. Looks like they are done sequentially, where in our opinion they could be done concurrently. 
We would like to propose:

* Running independent subqueries in different goroutines.
* Controlled by some `subqueryMaxConcurrency` flag.

Would that make sense or lack of concurrency here is intended?

**Use case. Why is this important?**
* We are just waiting on one subquery to finish to start another independent subquery. We just waste time, CPU / Resources. We could do those asynchronously.  

cc @roidelapluie @slrtbtfs @brian-brazil @beorn7

**Comment by brian-brazil** [comment]
> Would that make sense or lack of concurrency here is intended?

It's more that noone brought it up yet. This is also nothing to do with subqueries, you're talking about selectors.

The one thing to watch for is needlessly spawning goroutines, we never need this for local storage for example. A traffic spike to a remote system could also cause it issues.

**Comment by bwplotka** [comment]
Yes, that's why something max concurrency flag maybe make sense?
 
And even with this, the remote system should be it's own concurrency limit logics I guess.

Anyway.. looks like it's OK to start some PR for it?

**Comment by roidelapluie** [comment]
> > Would that make sense or lack of concurrency here is intended?
> 
> The one thing to watch for is needlessly spawning goroutines, we never need this for local storage for example. A traffic spike to a remote system could also cause it issues.

Even when we run `foo and bar` ?

**Comment by brian-brazil** [comment]
A hardcoded limit is probably fine, just to avoid a potential DOS on FDs or local ports.

**Comment by krasi-georgiev** [comment]
but how can run the main query and the subquery in paralel if the main query depends on the subquery?

**Comment by brian-brazil** [comment]
This issue is about selectors, not subqueries.

**Comment by krasi-georgiev** [comment]
hm , @bwplotka can you give more details on what exactly would run in paraller?

**Comment by bwplotka** [comment]
It's not only subqueries. All `Selects`: https://github.com/prometheus/prometheus/blob/master/storage/interface.go#L63

Also @krasi-georgiev you can see what exactly we could run concurrently by looking on the image I posted (and seeing the spans in Thanos: https://github.com/thanos-io/thanos/blob/master/pkg/query/querier.go#L184

**Comment by krasi-georgiev** [comment]
yes all clear, thanks and +1 for this.

**Comment by bwplotka** [comment]
Help wanted!

**Comment by slrtbtfs** [comment]
I couldn't resist trying to implement this and have actually managed to implement this.

Do we want the cryptocurrency limits global, per query or per engine instance?

**Comment by roidelapluie** [comment]
> Do we want the cryptocurrency limits global, per query or per engine instance?

:)

**Comment by krasi-georgiev** [comment]
> Do we want the concurrency limits global, per query or per engine instance?

I hink global to for now to keep it simple, just hard code it somewhere for now.

**Comment by bwplotka** [comment]
No one works on it at the moment, so help wanted (: 

Another showcase:
![image](https://user-images.githubusercontent.com/6950331/77525704-57237700-6e81-11ea-893a-7772ffae0fe2.png)

**Comment by mkabischev** [comment]
Thanks @bwplotka for mentioning our case :) 
It's very critical issue for us: some of subqueries longs for about ~20-30 seconds and parallelization will dramatically decrease overall latency.

I'll start to work on this issue. I believe that for Prometheus there can be just small profit because it uses disk for fetching data, but Thanos the overall picture is absolutely different, so it can help a lot.

**Comment by liguozhong** [comment]
A timeout showcase in our production:
![image](https://user-images.githubusercontent.com/9583245/78469383-431a2800-7753-11ea-8ebd-774d30ae080e.png)
