### ISSUE TITLE
Histogram quantile impl has erratic behavior when distribution contains no samples

### ISSUE THREAD

**Issue by tmwilder** [prometheus/prometheus#6897]
**What did you do?**
1. Run histogram quantile on any distribution where the the total count of observations across all buckets is 0.
2. This came up for me in a use case where I am doing quantile on a bucketed throughput metric and throughput can die off for an interval. In my particular use case I'm looking at signed estimate error for an estimation system using a histogram where the le tags have a large negative to positive range (for underestimating -> overestimating).
3. Results in specifying the lowest negative bucket as the value of all quantile inputs for the interval with no observations.

**What did you expect to see?**
Open question - I think I would expect NaN if there are no samples to interpolate against in any buckets. I could be convinced 0 but without domain knowledge of the histogram this seems off. 

**What did you see instead? Under which circumstances?**
I saw in this case -8192 - my largest negative LE (I believe caused by https://github.com/prometheus/prometheus/blob/41151ca8dc069448515f48893b8631b9a3ad8df8/promql/quantile.go#L91)

The rank variable is 0 since there are no samples - then the go binary search finds the min bucket.

**Environment**

* System information:

	insert output of `uname -srm` here

* Prometheus version:
Don't have access to box - but from UI:

Version: 2.7.1
Revision: 62e591f928ddf6b3468308b7ac1de1c63aa7fcf3
Branch: HEAD
BuildDate: 20190131-11:16:59
GoVersion: go1.11.5

**Comment by brian-brazil** [comment]
I'd also expect NaN in this case, to be consistent with other outputs when there's no events.
