### ISSUE TITLE
Failing with "opening storage failed: repair corrupted WAL"

### ISSUE THREAD

**Issue by jakubgs** [prometheus/prometheus#6898]
I have a federated setup of Prometheus `2.15.2` which recently started to show gaps and throwing a lot of errors like:
```
caller=db.go:609
component=tsdb
msg="compaction failed"
err="reload blocks: head truncate failed: create checkpoint: read segments: corruption in segment /prometheus/wal/checkpoint.049194/00000000 at 96731136: unexpected non-zero byte in padded page"
```
So I removed `/prometheus/wal/checkpoint.049194` but that just gave me these:
```
caller=main.go:740
err="opening storage failed: repair corrupted WAL: cannot handle error: open WAL segment: 0: open /prometheus/wal/00000000: no such file or directory"
```
Not sure what I'm supposed to do with that. I just fails every time I try to start it.

**Comment by jakubgs** [comment]
The documentation for `1.8` recommends:
>If you suspect problems caused by corruption in the database, you can enforce a crash recovery by starting the server with the flag storage.local.dirty.
https://prometheus.io/docs/prometheus/1.8/storage/#data-corruption

But when I tried using `--storage.local.dirty` I got back:
```
Error parsing commandline arguments: unknown long flag '--storage.local.dirty'
```
So that option is no longer there, but I can't find an alternative here:
https://prometheus.io/docs/prometheus/2.16/storage/

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
