### ISSUE TITLE
Isolation followup

### ISSUE THREAD

**Issue by roidelapluie** [prometheus/prometheus#6909]
Some things I would like to clarify with isolation:

- [x] Verify across code that we always rollback or commit
- [x] Verify that appenders and queriers are as short-lived as possible
- [x] Verify that everywhere we create a head (e.g. in snapshots) it does not blow up memory

**Comment by roidelapluie** [comment]
cc @beorn7

**Comment by beorn7** [comment]
> Verify across code that we always rollback or commit

Note that there is `prometheus_tsdb_head_active_appenders`, which gets incremented on appender creation and decremented on rollback/commit. If we miss the rollback or commit, it shows up in this metrics not going back to zero (and with the new isolation code in place, it will show up as a stuck low watermark). I have seen that very occasionally in production. Those might have been Prometheus servers that were in some kind of distress anyway. But it's definitely worth a look how this can possibly happen.

> Verify that appenders and queriers are as short-lived as possible

That was desirable even before. @brian-brazil @codesome @gouthamve @krasi-georgiev as the TSDB experts, perhaps you have context for that?

> Verify that everywhere we create a head (e.g. in snapshots) it does not blow up memory

I cannot see how, but then again the experts for TSDB certainly know more than I do. Paging @brian-brazil @codesome @gouthamve @krasi-georgiev again.

**Comment by roidelapluie** [comment]
> > Verify that everywhere we create a head (e.g. in snapshots) it does not blow up memory
> 
> I cannot see how, but then again the experts for TSDB certainly know more than I do. Paging @brian-brazil @codesome @gouthamve @krasi-georgiev again.

I guess it depends what we do with the head. subtle issues like #6899 could happen.

**Comment by roidelapluie** [comment]
> * [x]  Verify across code that we always rollback or commit
 I have checked this

**Comment by beorn7** [comment]
> I guess it depends what we do with the head. subtle issues like #6899 could happen.

That wasn't exactly subtle. And it's fixed now.

**Comment by roidelapluie** [comment]
> > I guess it depends what we do with the head. subtle issues like #6899 could happen.
> 
> That wasn't exactly subtle. And it's fixed now.

I would be happy if you just take a snapshot with head of your test prometheus and confirm it's allright :)

**Comment by brian-brazil** [comment]
> as the TSDB experts, perhaps you have context for that?

Appenders I'm not worried about. For queriers it's the 2m query timeout that ultimately matters, and tweaking querier lifetimes is like at most a microoptimisation.

**Comment by beorn7** [comment]
> I would be happy if you just take a snapshot with head of your test prometheus and confirm it's allright

Done.

**Comment by roidelapluie** [comment]
Thanks!
