### ISSUE TITLE
Use TTL provided by DNS SRV results

### ISSUE THREAD

**Issue by grobie** [prometheus/prometheus#692]
The DNS refresh rate is currently a configuration option. Even better would be to use the TTL provided by the results and leave the authority at the DNS provider.

**Comment by fabxc** [comment]
As a default that would be nice. I wouldn't make it mandatory, though.
From what I understand, the TTLs of the result answer section are not that useful, as it doesn't tell us anything about joining and leaving instances. Respectively, Consul sets all TTLs to zero by default.

The SD spec requires to provide a TXT record for each SD name which's TTL specifies the TTL for the SD name. Consul, for example, does not fulfill this requirement.

I assume consul sets the same TTL for all instances and hopes the user is smart and interprets this as the TTL for service as a whole. It's unlikely to be alone in not sticking to the spec.
This has obvious implications for an implementation of ours - it would not work for many users.

**Comment by brian-brazil** [comment]
We may want to consider the refresh rate as more of a minimum ttl in this case? Would that need a different paramater name? Considering there's a caching resolver in place in many cases, is there a need to do anything on our side?

**Comment by grobie** [comment]
The default has worked fine so far. Feel free to re-open if you see a need for it.
