### ISSUE TITLE
reload blocks: head truncate failed: get segment range: segments are not sequential

### ISSUE THREAD

**Issue by zhaojiweiwin** [prometheus/prometheus#6920]
Hi：
Prometheus service is running normally，but only data in memory is available，I have tried to delete the data directory and restart the service many times, but the problem still exists.
version: Prometheus 2.12.0  storage.tsdb.path=/data/prometheus  env: Linux
error:
level=info ts=2020-03-02T15:00:02.105Z caller=compact.go:495 component=tsdb msg="write block" mint=1583150400000 maxt=1583157600000 ulid=01E2DW5MNZGYNBJKM4GHXV6742 duration=761.89417ms
level=info ts=2020-03-02T15:00:02.275Z caller=head.go:593 component=tsdb msg="head GC completed" duration=26.491921ms
level=error ts=2020-03-02T15:00:02.276Z caller=db.go:561 component=tsdb msg="compaction failed" err="reload blocks: head truncate failed: get segment range: segments are not sequential"
level=info ts=2020-03-02T17:00:02.118Z caller=compact.go:495 component=tsdb msg="write block" mint=1583157600000 maxt=1583164800000 ulid=01E2E31BXYZJC9RKE2YZ4V7WBK duration=775.559045ms
level=info ts=2020-03-02T17:00:02.273Z caller=head.go:593 component=tsdb msg="head GC completed" duration=26.859111ms
level=error ts=2020-03-02T17:00:02.273Z caller=db.go:561 component=tsdb msg="compaction failed" err="reload blocks: head truncate failed: get segment range: segments are not sequential"
level=info ts=2020-03-02T19:00:02.079Z caller=compact.go:495 component=tsdb msg="write block" mint=1583164800000 maxt=1583172000000 ulid=01E2E9X35V2H2J9KC52178AFZ0 duration=739.541862ms
level=info ts=2020-03-02T19:00:02.249Z caller=head.go:593 component=tsdb msg="head GC completed" duration=27.377685ms
level=error ts=2020-03-02T19:00:02.249Z caller=db.go:561 component=tsdb msg="compaction failed" err="reload blocks: head truncate failed: get segment range: segments are not sequential"
level=info ts=2020-03-02T21:00:02.110Z caller=compact.go:495 component=tsdb msg="write block" mint=1583172000000 maxt=1583179200000 ulid=01E2EGRTDVMC7FJST3QTXKNAG2 duration=771.598768ms
level=info ts=2020-03-02T21:00:02.278Z caller=head.go:593 component=tsdb msg="head GC completed" duration=28.40084ms
level=error ts=2020-03-02T21:00:02.278Z caller=db.go:561 component=tsdb msg="compaction failed" err="reload blocks: head truncate failed: get segment range: segments are not sequential"
level=info ts=2020-03-02T23:00:02.178Z caller=compact.go:495 component=tsdb msg="write block" mint=1583179200000 maxt=1583186400000 ulid=01E2EQMHNYKPZ4EMDYKN8H8ZFB duration=836.845331ms
level=info ts=2020-03-02T23:00:02.357Z caller=head.go:593 component=tsdb msg="head GC completed" duration=26.801089ms
level=error ts=2020-03-02T23:00:02.358Z caller=db.go:561 component=tsdb msg="compaction failed" err="reload blocks: head truncate failed: get segment range: segments are not sequential"
level=info ts=2020-03-03T01:00:02.099Z caller=compact.go:495 component=tsdb msg="write block" mint=1583186400000 maxt=1583193600000 ulid=01E2EYG8XWDBBYP11ZZXZDNJSV duration=759.538341ms
level=info ts=2020-03-03T01:00:02.270Z caller=head.go:593 component=tsdb msg="head GC completed" duration=28.02767ms
level=error ts=2020-03-03T01:00:02.271Z caller=db.go:561 component=tsdb msg="compaction failed" err="reload blocks: head truncate failed: get segment range: segments are not sequential"
level=info ts=2020-03-03T03:00:02.146Z caller=compact.go:495 component=tsdb msg="write block" mint=1583193600000 maxt=1583200800000 ulid=01E2F5C05W5CXNK80SV86A5GH1 duration=806.742351ms
level=info ts=2020-03-03T03:00:02.302Z caller=head.go:593 component=tsdb msg="head GC completed" duration=27.53216ms
level=error ts=2020-03-03T03:00:02.303Z caller=db.go:561 component=tsdb msg="compaction failed" err="reload blocks: head truncate failed: get segment range: segments are not sequential"

**Comment by liguozhong** [comment]
Try changing the order of your Prometheus operations.

The first step is to stop Prometheus, 
the second step is to delete the data directory, 
and the third step is to start Prometheus.

**Comment by zhaojiweiwin** [comment]
One of my Prometheus services has encountered this problem before. My operation mode is the same as you said. Later, the service is normal. But now my new Prometheus service has encountered the same problem. This operation has been tried several times, but the problem still occurs

**Comment by zhulongcheng** [comment]
Hey @zhaojiweiwin , could you show the files in your WAL dir?

For example: `ls path/to/your/prometheus/wal`
