### ISSUE TITLE
Add `fortytw2/leaktest` to all unit tests that involves go routines.

### ISSUE THREAD

**Issue by bwplotka** [prometheus/prometheus#6925]
Hi, :wave: 

We found this super useful in the [Thanos](https://thanos.io) project, it allows us to find memory leaks in the form of not closed go routines pretty fast. Thanks for @gotjosh who reminds me to put a request for that. :hugs:  

**Help wanted!** 

NOTE1: It does not work with `t.Parallel` until this: https://github.com/fortytw2/leaktest/issues/4
NOTE2: At some point, Uber created its own lib which does the same (without even trying to contribute to the existing https://github.com/fortytw2/leaktest) here: https://github.com/uber-go/goleak Since https://github.com/fortytw2/leaktest works well, is mature and have friendly maintainers, I would say let's stick to that. (:

**Comment by liguozhong** [comment]
go idea！
