### ISSUE TITLE
How to relabel insance names

### ISSUE THREAD

**Issue by waardd** [prometheus/prometheus#6932]
I have been reading all across the internet for a way to relabel my instance name.
Now all my dashboard have long instance names like **lsrv1.server.nl:9100**

I would like to have that reduced to **lsrv1**

My data is coming from different exporters like node_exporter and push gateway.
The last one i know you can have exported_instance and that works.
But other exporters i cant get it to work to relabel

Example (piece) of my prometheus.yml

`  - job_name: 'PreProd'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    static_configs:
      - targets: ['lsrv1.server.nl:9100'] # node_exporter
      - targets: ['lsrv1.server.nl:9091'] # pushgateway
      - targets: ['lsrv1.server.nl:9901'] # some.log
      - targets: ['lsrv1.server.nl:9902'] # some_view.log
      - targets: ['lsrv1.server.nl:9903'] # some_services.log
      - targets: ['lsrv2.server.nl:9100'] # node_exporter
      - targets: ['lsrv2.server.nl:9091'] # pushgateway
      - targets: ['lsrv2.server.nl:9901'] # some.log
      - targets: ['lsrv2.server.nl:9902'] # some_view.log
      - targets: ['lsrv2.server.nl:9903'] # some_services.log
`

Can someone assist me with this?

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
