### ISSUE TITLE
Add PositionRange for label matchers

### ISSUE THREAD

**Issue by aclowkey** [prometheus/prometheus#6942]
## Proposal
#6615  Added PositionRange to nodes in the AST. And it's great!
I was thinking, perhaps having PositionRange to LabelMatches of a vector selector is could also be useful.

The main use case I want to implement is syntax highlighting, where label matches are annotate with some information such as 'no data', etc. 

Other possibilities is PositionRange for the offset portion.

**Comment by slrtbtfs** [comment]
When you want to do syntax highlighting it might make sense to directly use the Lexer, which separates a query into single tokens, similar to what is done [here](https://github.com/prometheus-community/promql-langserver/blob/5cb2e49987617c7f3ef6abb7e86b92effb81e507/langserver/completion.go#L228).

Also there seem to be plans to support [syntax highlighting over the language server protocol](https://github.com/microsoft/vscode-languageserver-node/issues/368), so if you want to implement this it might make sense to eventually integrate it into the [PromQL language server](https://github.com/prometheus-community/promql-langserver).

It's also worth pointing out that some basic syntax highlighting for PromQL has already been implemented multiple times, e.g. in https://github.com/redhat-developer/vscode-promql and https://github.com/Nexucis/codemirror-mode-promql .

**Comment by aclowkey** [comment]
Thank you very much!
