### ISSUE TITLE
Reduce number of Alerts/Rules boilerplate code structs.

### ISSUE THREAD

**Issue by bwplotka** [prometheus/prometheus#6948]
Hello :wave: 

With @s-urbaniak we are working on `RulesAPI`, which is something like [Thanos Store API but for Rules (recording and alerts)](https://github.com/thanos-io/thanos/pull/2200). While doing this we are doing lots of conversions: JSON -> Go -> Proto -> Go -> JSON etc. That's why we plan to have single DTO for all Alerts and Rules in proto: https://github.com/thanos-io/thanos/blob/c4260bfde7973f2abb9c923b62a205e53ae6c279/pkg/store/storepb/rules.proto. Anyway, my question does not relate to Thanos. 

This should work fine, but during the work to make all compatible, we noticed that **in Prometheus the number of different RuleGroup/Rule/Recording/Alerts Go definitions is extremely large**.

**Key question: Can we simplify and reduce that number? By providing some reference DTO objects in Prometheus.**

We seem to have:

1. Go -> JSON API: https://github.com/prometheus/prometheus/blob/c530b4b456cc5f9ec249f771dff187eb7715dc9b/web/api/v1/api.go#L955
2. Internal manager struct: https://github.com/prometheus/prometheus/blob/4835bbf3763c0df7cfe1a7c2a61ad08ec0dc6075/rules/manager.go#L191
3. Go -> JSON notifier API: https://github.com/prometheus/prometheus/blob/cccd5428912c6380eef2e024f66018960d68d0d1/notifier/notifier.go#L62
4. YAML -> Go Configuration:  https://github.com/prometheus/prometheus/blob/20b1f596f6fb16107ef0c244d240b0ad6da36829/pkg/rulefmt/rulefmt.go#L105
5. model: https://github.com/prometheus/common/blob/master/model/alert.go
6. ..,7,8?? https://github.com/prometheus/alertmanager has its own... cc @simonpasquier 

Do we really need so many? 

I guess just one internal struct and one DTO (with JSON and YAML tags) would be amazing to have. Do you think it's a valid request to simplify the code and burden? @brancz @beorn7 @simonpasquier @brian-brazil 

@gouthamve @pracucci did you experience any difficulties when embedding some rules in Cortex?

**Comment by pracucci** [comment]
> @gouthamve @pracucci did you experience any difficulties when embedding some rules in Cortex?

@jtlisi May you look at this, please? You worked on that.

**Comment by bboreham** [comment]
Cortex just works with the YAML as a string.  https://github.com/cortexproject/cortex/blob/master/docs/apis.md#configs-format
I'm not clear why you care about the notifier structure, or what happens inside alertmanager.

**Comment by bwplotka** [comment]
@bboreham I care because I am a Prometheus maintainer, so I would love to have 10x less code to maintain if possible :hugs:  Plus we recreate it everywhere in Prometheus ecosystem projects, like AM and Thanos. I think we might be able to reduce those to some sane amount. (:

**Comment by brian-brazil** [comment]
Each of those has different responsibilities, so I'd be surprised if we could do too much here without creating a massive object with unclear responsibilities.

**Comment by bwplotka** [comment]
Yup, but having 8-9 of those I think is too many. We now reduced all in Thanos to just two: `proto` and `alert queue` alert struct. With some upstream Prometheus work, we could just have proto in Thanos, import rest. (:

**Comment by bwplotka** [comment]
Anyway, we are not affected, I was wondering if we can improve the maintainability of Prometheus itself.

**Comment by bwplotka** [comment]
Hello to myself from the bug scrub (: 

Let's close it,no movement on this one, which means it is good fine?
