### ISSUE TITLE
Ingestion: Use the same appender for regular samples and reporting (`up` and friends)

### ISSUE THREAD

**Issue by beorn7** [prometheus/prometheus#6950]
This is a follow-up issue to #1893.

The regular samples are appended to TSDB with an appender that is committed or rolled-back, depending on success or failure. After that, a new appender is created to append the reporting samples (`up`, `scrape_...`, etc.). The problem with this approach is that the reporting samples will become visible to the query engine a bit after the regular samples are visible.

To fix this, only one appender has to be used for both samples in the case of success. If appending the regular samples already fails for some reason, that appender has to be rolled back and a new appender has to be used for the reporting samples (which still need to be appended because `up` is now 0). If all looks successful but then the final commit for the one appender errors out, things are most likely so broken that we don't need to retry appending with just the reporting samples.

**Comment by roidelapluie** [comment]
Note to anyone who wants to implement this: the code will overlap with pending pull request #6918
