### ISSUE TITLE
request to add option or mode to save local history metrics to remote write endpoint

### ISSUE THREAD

**Issue by jenningsloy318** [prometheus/prometheus#6954]
## Proposal
**Use case. Why is this important?**
As when situations that there are already a huge amount of historical data on local storage, but as a better persistence, local storage should be migrated remote storage system. cases are  we have 3 DCs and each DC has several prometheus instances and all of them are federated together.  and all of them have generated huge data here(we have change retention period to a long period to achieve this) before remote write storage become robust. 

we already have tens of TB data on the disk, want to export/migrate these data to a third remote storage system,currently our choices are m3db. and the whole export/migration process should contains 2 steps  :
- read metrics from disk 
- write them to remote storage system

From the prometheus itself function sets, it already implemented both features, but currently prometheus can only save new data to remote write endpoint. 

we have two options here to serve this:
1. add option to the remote write configure, which can set how long the historical data can be written to remote write endpoint
2. we can also add a sub-command to prometheus (for e.g. prometheus migrate), this is only works  when migrating local historical data to remote write endpoint ; or 

*“Nice to have” is not a good use case. :)*
plus we can also make it possible for prometheus to read all data from a remote read endpoint.

**Comment by roidelapluie** [comment]
This is reasonable ; could be implemented in the tsdb tool, or in a third party tool. However that would be a lot of efforts.

**Comment by brian-brazil** [comment]
This does sound a bit niche, and sending them the block would be more efficient. I think a 3rd party tool would be the best approach here.

**Comment by roidelapluie** [comment]
Setting Pmaybe but it would better fit in an 3rd party tool. Let's think about it a few days.

**Comment by cstyan** [comment]
This would have to be a separate tool since remote write is based on the WAL, it couldn't be done with the current remote write system.

**Comment by jenningsloy318** [comment]
is there any documents that show some details about the WAL, tsdb, and how these metrics are being stored to remote endpoint ? 

currently I have a primitive code that can getting metrics from the local storage, but failed to store them to remote endport, remote storage failed to store these metrics to its database. 

my process is 
- get the MinTime and MaxTime from a block
```
tsdb connection ---->tsdbConn.Blocks() -------> each blockreader ----->blockMinT, blockMaxT 
```
- use blockMinT, blockMaxT  as parameter, to create a storage.Querier,
```
sdbConn.Querier(ctx, blockMinT, blockMaxT) ---> storage.Querier 
```
- create a labelSelectParams and labelMatcher
- pass labelSelectParams and labelMatcher to storageQuerier.Select, will get the timeSeriesSet, then get the label and sample timestamp and value
```
storageQuerier.Select(labelSelectParams, labelMatcher)  ----> timeSeriesSet  -----> lables and sample
```
- then construct []prompb.TimeSeries  with labels and sample
- create prompb.WriteRequest with []prompb.TimeSeries
- proto.Marshal and snappy.encode the prompb.WriteRequest
- use http client to send the metric to remote endpoint


and I can see all the labels and samples(timpstamp and value),  when sending metrics to remote endpoint is successfully with 200 status code, but remote endpoint failed to write the metrics to its storage, each time I only sent 1 sample to the endpoint 

I am stuck here at the final step, I tcpdumped the packet from prometheus to remote write endpoint, and the prompb.WriteRequest is same structure, only difference is that prometheus sent muliple samples but mine only one. 


here is an exmple of my prompb.WriteRequest
```
prompb.WriteRequest{Timeseries:[]prompb.TimeSeries{prompb.TimeSeries{Labels:[]prompb.Label{prompb.Label{Name:"__name__", Value:"alertmanager_alerts", XXX_NoUnkeyedLiteral:struct {}{}, XXX_unrecognized:[]uint8(nil), XXX_sizecache:0}, prompb.Label{Name:"app", Value:"alertmanager", XXX_NoUnkeyedLiteral:struct {}{}, XXX_unrecognized:[]uint8(nil), XXX_sizecache:0}, prompb.Label{Name:"env", Value:"prod", XXX_NoUnkeyedLiteral:struct {}{}, XXX_unrecognized:[]uint8(nil), XXX_sizecache:0}, prompb.Label{Name:"instance", Value:"10.36.52.155:9093", XXX_NoUnkeyedLiteral:struct {}{}, XXX_unrecognized:[]uint8(nil), XXX_sizecache:0}, prompb.Label{Name:"job", Value:"alertmanager", XXX_NoUnkeyedLiteral:struct {}{}, XXX_unrecognized:[]uint8(nil), XXX_sizecache:0}, prompb.Label{Name:"netdatatype", Value:"inb", XXX_NoUnkeyedLiteral:struct {}{}, XXX_unrecognized:[]uint8(nil), XXX_sizecache:0}, prompb.Label{Name:"state", Value:"suppressed", XXX_NoUnkeyedLiteral:struct {}{}, XXX_unrecognized:[]uint8(nil), XXX_sizecache:0}, prompb.Label{Name:"type", Value:"service", XXX_NoUnkeyedLiteral:struct {}{}, XXX_unrecognized:[]uint8(nil), XXX_sizecache:0}}, Samples:[]prompb.Sample{prompb.Sample{Value:1, Timestamp:1573594387949, XXX_NoUnkeyedLiteral:struct {}{}, XXX_unrecognized:[]uint8(nil), XXX_sizecache:0}}, XXX_NoUnkeyedLiteral:struct {}{}, XXX_unrecognized:[]uint8(nil), XXX_sizecache:0}}, XXX_NoUnkeyedLiteral:struct {}{}, XXX_unrecognized:[]uint8(nil), XXX_sizecache:0}

```

**Comment by roidelapluie** [comment]
I suggest that we close this issue here and move to the developers mailing list https://groups.google.com/forum/#!forum/prometheus-developers where more people can help.

**Comment by jenningsloy318** [comment]
I already create a mail there, but seems none intrested, so I ask help here if someone can give me some guidence.  

https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/prometheus-users/hfXB7qHVASU

**Comment by roidelapluie** [comment]
We have decided in the bug scrub to close this issue.

Remote write is better at tailing WAL. We would expect the remote write imports to work with snapshots/tsdb instead of remote write.
