### ISSUE TITLE
Limit number of consul agent connections in consul_sd

### ISSUE THREAD

**Issue by sevagh** [prometheus/prometheus#6959]
Hello,

We have a pretty large consul catalog. In one of our bigger DCs, the Prometheus poller is opening 1000+ connections to the local consul agent when doing `consul_sd`.

I can increase this value with https://www.consul.io/docs/agent/options.html#http_max_conns_per_client but I'm wondering if it makes sense to be able to limit this on Prometheus' end.

**Comment by brian-brazil** [comment]
This is a limitation of how Consul works, we need a connection per service to do watches efficiently and correctly. You'll have to adjust this on the Consul end.

**Comment by sevagh** [comment]
Thanks.
