### ISSUE TITLE
Query/Rule Time Regression

### ISSUE THREAD

**Issue by ipstatic** [prometheus/prometheus#6968]
**What did you do?**
Upgraded from Prometheus 2.8.1 to 2.16.0

**What did you expect to see?**
Better or the same query/recording rule timing.

**What did you see instead? Under which circumstances?**
Instantly saw recording rule times increase by 3-5x. Other queries taking 60-100ms longer to return results.

**Environment**

* System information:

	Linux 4.14.94+ x86_64

* Prometheus version:

	2.16.0

I have attached some images to show the differences.

This image shows a few queries on a 2.8 instance.
<img width="1535" alt="2 8" src="https://user-images.githubusercontent.com/332617/76447698-7c9f8380-639f-11ea-865d-94785b8af167.png">

These are the same queries on the same instance after upgrading to 2.16.0 (notice the load time is 60ms more). We noticed this due to the `prometheus.html` console taking ~60 seconds to load due to the increased query time (it shows a listing of all Prometheus instances plus their memory, TSDB and ingestion stats).
<img width="1538" alt="2 16" src="https://user-images.githubusercontent.com/332617/76447701-7d381a00-639f-11ea-92b2-a8917257ee27.png">

And here is the same instance showing how a recording rule group went from nearly instant to 5 seconds.
<img width="1329" alt="recording-rules" src="https://user-images.githubusercontent.com/332617/76447702-7d381a00-639f-11ea-92ac-8f032e8644cd.png">

**Comment by brian-brazil** [comment]
Can you share the full queries and how many series are touched? Did anything else change? Is the machine overloaded?

Performance can and does vary across versions.

**Comment by ipstatic** [comment]
It is basically any query. We just attempted to upgrade half our fleet to 2.16 and had to roll back due to increased rule evaluation / query times. We are seeing this across the board for everything. These instances are not overloaded, we give Prometheus a lot of memory headroom (usually Prometheus is only using 40-60% of memory to allow for large queries).

That recording rule group that jumped in the screenshot above is actually our alert rules and has very simple queries like `up{job='job'} == down`. If I can be more helpful please let me know. I know this is kind of general but we are seeing this on every instance we attempt to upgrade.

For example, this one instance is our largest instance and has some very high cardinality metrics. The total recording rule group time was ~200 seconds. After the upgrade it went up to 3,000+ seconds. It is represented by the green line below.
<img width="1534" alt="2 16-2" src="https://user-images.githubusercontent.com/332617/76513204-4f4ce700-642c-11ea-952c-e8363fe66d6d.png">

To give you some stats around that instance:
Ingested samples: 545,000/s
Head series: ~10.9 million

For the instance that I showed the screenshots in the first image:
Ingested samples: 112,000/s
Head series: 2.2 million

**Comment by brian-brazil** [comment]
We need exact queries to be able to debug. A 1000x increase in runtime that noone else has reported is likely due to overload.

**Comment by ipstatic** [comment]
I’ll have to get permission from management to do so. Most queries in those recording rules contain product names so I can’t just paste them here.

**Comment by brian-brazil** [comment]
You can anonymise the label values, but we do need to see the full structure of the query.

**Comment by ipstatic** [comment]
While waiting on permission to share other queries I have setup a test that I can replicate the issue.

On a 2.8.1 instance I setup the following recording rule:
```
groups:
- name: Github Issue 6968
  rules:
  - record: instance:prometheus_tsdb_head_samples_appended_total:rate5m
    expr: rate(prometheus_tsdb_head_samples_appended_total{job='prometheus'}[5m])
```
That expression contains 126 time series.

The average rule group evaluation time on 2.8 was .009544132
With 2.16 it is: 0.058307105

<img width="1297" alt="Screen Shot 2020-03-12 at 9 00 18 AM" src="https://user-images.githubusercontent.com/332617/76524223-1159be00-6440-11ea-8b79-5e72ad3124e9.png">

While this increase is "small" with this example, it shows that there is an order of magnitude difference between these versions.

**Comment by ipstatic** [comment]
On a hunch I downgraded to 2.15.2 and the issue goes away. So it appears a change in 2.16 has caused this issue:

<img width="1296" alt="Screen Shot 2020-03-12 at 9 16 42 AM" src="https://user-images.githubusercontent.com/332617/76525443-37805d80-6442-11ea-95bc-480605e4b7c5.png">

The first part of the graph is version 2.8.1, the middle 2.16.0, and finally the last past part 2.15.2.

**Comment by brian-brazil** [comment]
That narrows things down a lot. Does the average prometheus_engine_query_duration_seconds indicate which part of the query is slower?

**Comment by roidelapluie** [comment]
Are you using remote_read with read_recent: true?

**Comment by ipstatic** [comment]
@brian-brazil not really, seems like maybe prepare_time and inner_eval?
<img width="1306" alt="Screen Shot 2020-03-12 at 9 50 22 AM" src="https://user-images.githubusercontent.com/332617/76528661-90062980-6447-11ea-9454-f9b78c041989.png">

@roidelapluie No this is querying the local Prometheus instance which scrapes other Prometheus instances.

**Comment by brian-brazil** [comment]
>  The Prometheus instance I am running these queries on scrapes our other Prometheus instances

To be clear this is normal scraping for monitoring Prometheus itself, not federation?

Looks like it's probably prepare, which would mean indexing. That's a very simple selector though, and if anything should have gotten slightly faster with 2.16.0 - but that shouldn't be visible down at 100 series. Can you try before/after #6651?

**Comment by ipstatic** [comment]
Yes, normal scraping of /metrics and not /federate.

I just tried the commit before #6651 (61262159c43294d01ba6a87e70002d61cc6f60d1) and I am seeing near the same times I was seeing with 2.8.1. That looks to be causing the issue.

**Comment by brian-brazil** [comment]
Can you try after #6676? While #6651 does makes things faster by removing some redundant calculation, it also removed a pre-filtering of series that no longer exist which you may be seeing.

**Comment by ipstatic** [comment]
Just tried 53aa2541e5feb30f48070087716beed3531f9d88 and see the same performance I saw with 2.8.1. However if I build off master I see the same timing issues I did with 2.16.0. Do you think #6841 will give us the same issues as #6651?

**Comment by ipstatic** [comment]
Looking at `prometheus_engine_query_duration_seconds` again `prepare_time` is back up.

**Comment by roidelapluie** [comment]
Master has a new feature, isolation, which has that kind of side effects.

**Comment by brian-brazil** [comment]
It's more that #6676 happens to add back the pre-filtering that should never have made a difference in the first place. Do you have high churn for some reason?

**Comment by ipstatic** [comment]
Are you talking about the `prometheus_tsdb_head_samples_appended_total` metric? No.

**Comment by roidelapluie** [comment]
More the `scrape_series_added` metric.

**Comment by ipstatic** [comment]
We do not have high churn.
<img width="1296" alt="Screen Shot 2020-03-12 at 3 22 29 PM" src="https://user-images.githubusercontent.com/332617/76559433-914e4b00-6475-11ea-80e1-55384f4077e7.png">

**Comment by ipstatic** [comment]
Actually, I just built an image from 52630ad0c735f2dce4ce5bb851acb6c5d7df5eb1 and it is showing the same higher query timings as 16.2. I'll have to spend more time tomorrow to try and track down when it occurred again.

**Comment by ipstatic** [comment]
Sorry for the confusion. It appears #6676 is the cause and not #6651. These two commits did not show the increased query times:
540dc7df - #6651
20a94e62 - commit before #6676 was merged

However these two did:
fdbb18b4 - #6676 
91ddd67c - commit after #6676 

How else can I help?

**Comment by brian-brazil** [comment]
Would you be able to setup a Prometheus doing the same scraping but just running that rule group with a low an interval as you can, and then get a CPU profile?

**Comment by ipstatic** [comment]
Yes, if you tell me how you want me to collect the CPU profile. It should be noted this is running in a Docker container. And how low of an interval do you want?

**Comment by ipstatic** [comment]
Also what commit should I run the code from?

**Comment by brian-brazil** [comment]
Run it after 6676, as low as you can reasonably get it so it shows up nicely in the profile which are over 30s usually. https://golang.org/pkg/net/http/pprof/

**Comment by ipstatic** [comment]
I increased the rule evaluation time for that rule group to 2s and captured a 30s profile. Let me know what else I can provide.

[top.txt](https://github.com/prometheus/prometheus/files/4330766/top.txt)
![profile001](https://user-images.githubusercontent.com/332617/76645069-9ae7b980-652e-11ea-8473-9bcf570d79ed.png)

**Comment by brian-brazil** [comment]
It's odd that it's using inversePostingsForMatcher, as that selector is straight equality lookups. Are you sure that's the query in use?

I'm surprised that minTime is taking that much of it, it's a simple function. Looking at the code, that we're not pre-allocating the size of `filtered` may also be making things expensive.

**Comment by ipstatic** [comment]
Sorry, I had other recording rules still running. I now only have the one defined above running and here is the profile:

![profile002](https://user-images.githubusercontent.com/332617/76649089-5233fe80-6536-11ea-9802-5ff1bf693aca.png)
[profile002.txt](https://github.com/prometheus/prometheus/files/4331009/profile002.txt)

**Comment by brian-brazil** [comment]
Ratios are about the same, I guess it's the number of series we have to look up - but that should still be tiny. What is `count({job="prometheus"})` ?

**Comment by ipstatic** [comment]
`123712`

**Comment by brian-brazil** [comment]
So that'd work out to ~50ns per series. That seems okay in principle, and in absolute terms 50ms isn't that much. Do you have a query that is taking much longer now (e.g. seconds) in absolute terms?

**Comment by ipstatic** [comment]
While 50ms for one query isn't much, the problem is every query I have executed on these newer systems shows this. We first discovered this by trying to look at our `prometheus.html` console on our "global" Prometheus instances. It has a for loop that iterates over each Prometheus instance and does 4 queries to populate tables beside the Prometheus name. This page used to take 1-3 seconds previous to this issue, and now it takes 40-60+ seconds. I would need to reload all the recording rules on this instance to see if a single query is taking seconds longer but I am sure something is doing it. Again, we saw this across the fleet for everything, instance queries, alerting rules, recording rules. 

Here is the console and the queries it is executing. I don't think they are very expensive and they are scoped to the instance label that is being iterated over.

```
<table class="table table-condensed table-striped table-bordered" style="width: auto;">
<tr>
  <th>Prometheus</th>
  <th>Up</th>
  <th>Ingested Samples</th>
  <th>Time Series</th>
  <th>Memory</th>
  <th>Version</th>
</tr>
{{ range query "up{job='prometheus'}" | sortByLabel "instance" }}
<tr>
  <td><a href="prometheus-overview.html?instance={{ .Labels.instance }}">{{ .Labels.instance }}</a></td>
  <td {{ if eq (. | value) 1.0 }}>Yes{{ else }} class="alert-danger">No{{ end }}</td>
  <td class="text-right">{{ template "prom_query_drilldown" (args (printf "irate(prometheus_tsdb_head_samples_appended_total{job='prometheus',instance='%s'}[5m]) OR irate(prometheus_local_storage_ingested_samples_total{job='prometheus',instance='%s'}[5m])" .Labels.instance .Labels.instance) "/s" "humanizeNoSmallPrefix") }}</td>
  <td class="text-right">{{ template "prom_query_drilldown" (args (printf "prometheus_tsdb_head_series{job='prometheus',instance='%s'} OR prometheus_local_storage_memory_series{job='prometheus',instance='%s'}" .Labels.instance .Labels.instance) "" "humanize") }}</td>
  <td class="text-right">{{ template "prom_query_drilldown" (args (printf "process_resident_memory_bytes{job='prometheus',instance='%s'}" .Labels.instance) "B" "humanize1024")}}</td>
  <td class="text-right">{{ with query (printf "prometheus_build_info{job='prometheus',instance='%s'}" .Labels.instance) }}{{. | first | label "version"}}{{end}}</td>
</tr>
{{ else }}
<tr><td colspan=4>No devices found.</td></tr>
{{ end }}
```

And using the newer query logging feature, I added up all the query times to show that was the issue:
```
cat query_log.json | jq -c '[.[] | select(.httpRequest) | .stats.timings.evalTotalTime] | reduce .[] as $num (0; .+$num)'
71.16402241499995
```

**Comment by ipstatic** [comment]
Since we are upgrading to 2.15.2 as a stop gap, here is a profile of the same config with 2.15.2.

![profile003](https://user-images.githubusercontent.com/332617/76795178-f7511000-679e-11ea-8f3c-a33f780c4cb8.png)

**Comment by brian-brazil** [comment]
Hmm, that's a lot of garbage collection. Can you do a diff of two alloc_space heap profiles a few minutes apart to see where it's coming from?

**Comment by ipstatic** [comment]
I just restarted the instance when I took that profile. Here are the two you requested:

![profile004](https://user-images.githubusercontent.com/332617/76796966-edc9a700-67a2-11ea-8cd2-cc9bf4f693d3.png)
![profile005](https://user-images.githubusercontent.com/332617/76796970-edc9a700-67a2-11ea-831a-eb180a7d3fd2.png)

And I meant to say that I am seeing a 5x better performance with 2.15.2 than I am with 2.16.0.

**Comment by ipstatic** [comment]
Also, re-ran the CPU profile. Even better timings now:

![profile006](https://user-images.githubusercontent.com/332617/76802586-608c4f80-67ae-11ea-92ae-d59f5b33af9e.png)

**Comment by brian-brazil** [comment]
Those memory profiles are both inuse_space, for GC analysis we need alloc_space. pprof also has a diff feature.

**Comment by ipstatic** [comment]
I am sorry but which version did you want the heap from? The cpu profile that you see GC happening is from a 2.15.2 instance that just restarted. The last profile I posted is the same instance after running for a bit.

**Comment by ipstatic** [comment]
Here is the diff for 2.15.2 (which is what showed the GC time in the one CPU profile).

![profile009](https://user-images.githubusercontent.com/332617/76862496-95db8080-6834-11ea-8a50-220bb235727d.png)

What else should I collect/show? We really would like to upgrade to a version that has query logging as that is something we have wanted for years to help our users. However, I cannot go past 2.15.2 until this issue is resolved.

**Comment by ipstatic** [comment]
To help avoid confusion between different profiles and other debugging steps I have done the following:

1. I have setup 3 identical machines that run a different version of Prometheus:
a. 2.15.2
b. commit 20a94e6
c. commit fdbb18b
2. They each started with no TSDB history
3. They all have the same configuration and rule files. They are only monitoring the Prometheus and node metrics for our entire Prometheus fleet. We have 128 instances in varying size. They only have one rule file:
```
groups:
- name: Github Issue 6968
  interval: 2s
  rules:
  - record: instance:prometheus_tsdb_head_samples_appended_total:rate5m
    expr: rate(prometheus_tsdb_head_samples_appended_total{job='prometheus'}[5m])
```
4. I then captured a 30 second CPU profile for all three, and captured two heap profiles ~2 minutes apart and performed a diff. This was done roughly an hour after Prometheus had started.

Before I attach all the various profiles and graphs there was one thing that stood out to me. Since I started with no TSDB history, all three performed the same for the first five minutes. After five minutes, then the machine running the problem commit (fdbb18b) started showing symptoms. It is the instance with the blue line.
<img width="1302" alt="Screen Shot 2020-03-17 at 2 35 52 PM" src="https://user-images.githubusercontent.com/332617/76890836-72c5c680-685e-11ea-9883-4b2ccacec16a.png">

**Instance A (2.15.2)**
CPU profile
![profile001](https://user-images.githubusercontent.com/332617/76890942-9557df80-685e-11ea-9197-8b3fb641e2f9.png)

Mem diff
![profile004](https://user-images.githubusercontent.com/332617/76890994-a99bdc80-685e-11ea-8760-dac9b120bb22.png)

count({job="prometheus"})
`593`

**Instance B (20a94e6)**
CPU profile
![profile002](https://user-images.githubusercontent.com/332617/76891031-b5879e80-685e-11ea-9988-884662654ff1.png)

Memory diff
![profile005](https://user-images.githubusercontent.com/332617/76891048-bb7d7f80-685e-11ea-830e-b01c889e06f1.png)

count({job="prometheus"})
`576 `

**Instance C (fdbb18b)**
CPU profile
![profile003](https://user-images.githubusercontent.com/332617/76891084-c9330500-685e-11ea-81b3-a5bd7bbd9eb1.png)

Memory diff
![profile006](https://user-images.githubusercontent.com/332617/76891097-ce904f80-685e-11ea-8993-66c4683f0786.png)

count({job="prometheus"})
`576 `

At this point I believe I have proven there is a noticeable and reproducible query time regression since commit fdbb18b. If there is anything else I can provide, please let me know.

**Comment by ipstatic** [comment]
Decided to run the profile for a little longer than 30 seconds. Here is a 5 minute CPU profile and the diff:

20a94e6
![profile009](https://user-images.githubusercontent.com/332617/76895928-4febe000-6867-11ea-9f0e-45db3420632b.png)

fdbb18b
![profile008](https://user-images.githubusercontent.com/332617/76895876-38145c00-6867-11ea-9213-ce57b53525a3.png)

diff
![profile011](https://user-images.githubusercontent.com/332617/76895963-65610a00-6867-11ea-9b90-0090da6a6e86.png)

**Comment by brian-brazil** [comment]
After 5m runtime this fast path no longer applies: https://github.com/prometheus/prometheus/blob/master/tsdb/head.go#L1409-L1414

**Comment by ipstatic** [comment]
I just reverted the changes to the `Postings` function in `tsdb/head.go` from fdbb18b (https://github.com/prometheus/prometheus/commit/fdbb18b445285b69d005d88d2c1edb83f5c1b5e5#diff-6fb13507bfadf9819fea5bda61f599e6), compile and ran on my test instance that was showing the query issues. It is now performing as the others.

<img width="1573" alt="Screen Shot 2020-03-18 at 4 12 50 PM" src="https://user-images.githubusercontent.com/332617/77003339-8e4ed100-6933-11ea-9d6c-eddd79b6d1e2.png">
<img width="1575" alt="Screen Shot 2020-03-18 at 4 13 00 PM" src="https://user-images.githubusercontent.com/332617/77003340-8ee76780-6933-11ea-9a0f-03032b39291b.png">

**Comment by ipstatic** [comment]
Would it be possible for us to revert fdbb18b until a solution is found?

**Comment by ipstatic** [comment]
@brian-brazil or @roidelapluie any thoughts if I open a PR reverting fdbb18b?

**Comment by ahurtaud** [comment]
Hello,
I think I am facing the same issue after the load from 2.16.0 to 2.17.0. We were aware about CPU/query increase, but I think this is way more than expected:
- Rules eval duration (0.9 quantile) went from 15ms to ~500ms. 
- CPU went from 0.25 core to 0.6 (kubernetes pod)

<img width="1432" alt="rule-eval-duration" src="https://user-images.githubusercontent.com/25080995/77533816-d9b73100-6e97-11ea-88f9-56c5275d4f94.png">

FYI we had to fallback to 2.16.0.

**Comment by bwplotka** [comment]
I think we might have similar reports on Thanos side: https://github.com/thanos-io/thanos/issues/2213 

Will try to look closer on this as well

**Comment by bwplotka** [comment]
@ipstatic Please do. After revert you see no regression difference? 

Thanks for narrowing this down! Let's focus in PR what we can do long term :+1:

**Comment by ipstatic** [comment]
@ahurtaud I believe you are probably impacted by #6841 as that is only in 2.17.0. The issue I am seeing is present in 2.16.0 as well.

@bwplotka Yes, reverting fixes the regression I see.

**Comment by bwplotka** [comment]
Can you propose the PR?

**Comment by bwplotka** [comment]
The only problem is that without this commit still something else can be broken on master (as https://github.com/prometheus/prometheus/issues/7048) suggests. When you reverted, you reverted 2.16.0 I guess?

**Comment by roidelapluie** [comment]
I've open #7051

**Comment by ipstatic** [comment]
Ah thanks @roidelapluie I just opened #7052 :) I'll close mine in favor for yours.

**Comment by amrmahdi** [comment]
@ipstatic I think I'm missing something. You mentioned that #6676 caused your regression moving from 2.8.1 to 2.16.0, but #6676 was released in 2.17.0 Can you explain how it affected 2.16.0 ?

**Comment by bwplotka** [comment]
That's true, I did not check that. The mentioned commit was done 7 days
after 2.16 🤔

**Comment by ipstatic** [comment]
@amrmahdi 🤦‍♂ I built off master instead of the 2.16 tag by mistake and was somewhere between the 2.16 and 2.17 release. Our build process uses `git describe` to tag our built version so I was still seeing 2.16 and not actually checking the branch/commit I built off of. I can confirm #7051 does fix this issue.

**Comment by bwplotka** [comment]
Awesome! All good then. Thanks all who helped to quickly find this out!
