### ISSUE TITLE
Variance of letter case on logs

### ISSUE THREAD

**Issue by gotjosh** [prometheus/prometheus#6972]
Hello Prometheans,

Unsure whenever this is best suited as a bug report, but I've observed different letter casing in log lines and was wondering whenever this is indented.

I _think_ there might be a pattern but would like to confirm. It seems that for components starting and stopping (e.g. [scrape manager](https://github.com/prometheus/prometheus/blob/master/cmd/prometheus/main.go#L571), [remote write](https://github.com/prometheus/prometheus/blob/master/storage/remote/queue_manager.go#L398), [tsdb](https://github.com/prometheus/prometheus/blob/master/cmd/prometheus/main.go#L667), [Prometheus itself](https://github.com/prometheus/prometheus/blob/master/cmd/prometheus/main.go#L333)) log lines are capitalized. 

For everything else that appears to be operational (e.g. [scrape manager](https://github.com/prometheus/prometheus/blob/master/scrape/manager.go)), it seems to be lower case. 

However, sometimes even this pattern is broken (e.g. [remote write](https://github.com/prometheus/prometheus/blob/master/storage/remote/queue_manager.go#L538)).

Do we have any consensus on when to use which? I couldn't find any documentation that indicates that, and I'd be happy to fix/create anything that might need it.

**Comment by brian-brazil** [comment]
Log messages should be capitalised, however for go errors should not be as they'll likely be prefixed. That can sometimes result in an uncapitalised log message. If there's cases that are easy to fix, we should fix them.

**Comment by thaniri** [comment]
I can work on this.

**Comment by brian-brazil** [comment]
Create a fork on github and push it to your fork.

**Comment by gotjosh** [comment]
ping me if you need any help @thaniri, I think a first step you can do (mostly for the benefit on getting familiar with the different Prometheus areas) is to identify which are the different areas we have to look for the log lines (e.g. storage, tsdb, scrape, service discovery). 

Then, make a checklist as part of this issue so that we can keep track of which areas we have scanned already. Then, either you (or others) can each take up on the different areas and submit the PRs for them.

I think this makes it easier for everything, you can keep track of what you're doing and the reviewers only need to look at a particular area at a time.

**Comment by thaniri** [comment]
It is my personal opinion that creating a different PR for each package within the repository will result in such a trivial change taking too much time as too many people will need to get involved in this change. Really this PR could have probably been done with a sed command and some review :)

Here is the PR ready for review. I am hoping that I have followed the contributing guidelines correctly.

https://github.com/prometheus/prometheus/pull/7043

**Comment by gotjosh** [comment]
Whatever works for you, works for me 😄

**Comment by thaniri** [comment]
Tests pass now, just needed to keep pulling from master and kicking off new CI builds until it worked :)

**Comment by gotjosh** [comment]
I think we can close this now @brian-brazil, right?
