### ISSUE TITLE
WAL can't correctly handle more than 1 million segments

### ISSUE THREAD

**Issue by brian-brazil** [prometheus/prometheus#6979]
The segments are created in files with names following %08d, and checkpoints %06d. We take a  list of checkpoints/files sorted as strings, but that's not going to work once there's more than 1M segments. We should do our own sorting based on the number, and also use consistent formatting between checkpoints and segments.

We're also using ioutil.ReadDir in one place and our own fileutil.Readdir on top of Readdirnames in another, we should unify this on ioutil.Readdir rather than inventing our own thing.

**Comment by codesome** [comment]
Closed by https://github.com/prometheus/prometheus/pull/6987 and created https://github.com/prometheus/prometheus/issues/7029 for `fileutil.Readdir`
