### ISSUE TITLE
2.17.0-rc.1: err="unknown series:  not found"

### ISSUE THREAD

**Issue by roidelapluie** [prometheus/prometheus#6992]
**What did you do?**

Run Prombench

**What did you expect to see?**

2.17 can scrape the same targets as 2.16

**What did you see instead? Under which circumstances?**

2.17 sometimes fails with:
level=debug ts=2020-03-16T19:18:07.614Z caller=scrape.go:968 component="scrape manager" 
                         scrape_pool=fake-webservers-12 target=http://10.16.50.105:8081/metrics msg="append failed" err="unknown series: 
                         not found"

**Environment**

* System information:
http://prombench.prometheus.io/6991/prometheus-pr/graph?g0.range_input=2h&g0.expr=count_values(%22up%22%2Cup)&g0.tab=0
http://prombench.prometheus.io/grafana/d/7gmLoNDmz/prombench?orgId=1&var-RuleGroup=All&var-pr-number=6991&from=1584377715743&to=1584387589755
![samp](https://user-images.githubusercontent.com/291750/76797383-a573ae80-67cd-11ea-94ba-ad1e067e02cd.png)

**Comment by roidelapluie** [comment]
Happening around WAL trucate / gc

**Comment by roidelapluie** [comment]
cc @brian-brazil @beorn7 @codesome :confused:

**Comment by beorn7** [comment]
This is coming from the `AddFast` method (head.go L988). This should never bubble up to that line (because the normal `Add` is used instead if that error happens). Something weird is going on…

**Comment by roidelapluie** [comment]
And it stays il consecutive scrapes for 30 minutes

**Comment by roidelapluie** [comment]
It happened in a previous prombench too

![samp2](https://user-images.githubusercontent.com/291750/76802397-dfe24900-67d7-11ea-8025-fa7f36cf781b.png)

**Comment by beorn7** [comment]
I guess that has to happen in the `Add` method of the `headAppender`. It creates the series and then call `AddFast` for it, but perhaps it wasn't really created or got removed again or something.

That it stays that way for 30m is really curious…

I'm too tired right now to debug more.

**Comment by roidelapluie** [comment]
@beorn7 I create a PR, help is appreciated tomorrow to see how we can test that

**Comment by roidelapluie** [comment]
Bug introduced by 34426766d85423e0327dd00d09c9990ccf73deb4

**Comment by bwplotka** [comment]
Fixed by: https://github.com/prometheus/prometheus/pull/6993

Thanks @roidelapluie for finding this! :muscle:
