### ISSUE TITLE
Add functions for histogram standard deviation 

### ISSUE THREAD

**Issue by elcomtik** [prometheus/prometheus#7030]
## Proposal
**I would refer to old feature request https://github.com/prometheus/prometheus/issues/3998**

Calculating stddev for histogram would be useful for me, because I use smokeping exporter https://github.com/SuperQ/smokeping_prober, which makes huge amount of probes and returns values aggregated by histogram data type. 

My goal is to make sub second interval probing and I don't want to put such load on prometheus server directly. I consider two solutions, the first is calculate stddev by exporter and produce one more gauge metric per target, the second is to use existing histogram and calculate later on prometheus. The second one would be probably less precise, however it would provide this feature for general usage.

I think anyone who use histograms agree with some degree of precision loss. Anyone can controll it by defining bucket sizes wisely. Finally if I wanted absolute precision I wouldn't use metrics monitoring but log monitoring

**Comment by brian-brazil** [comment]
Per #3998 this is possible in a statistically sane and useful way.

**Comment by roidelapluie** [comment]
Based on https://github.com/prometheus/prometheus/issues/7030#issuecomment-602235105, we have decided in the bug scrub to close this.
