### ISSUE TITLE
Blackbox Exporter OOMing after Prometheus Upgrade (2.15.2 -> 2.16.0)

### ISSUE THREAD

**Issue by chhetripradeep** [prometheus/prometheus#7031]
**What did you do?**
We upgraded Prometheus 2.15.2 to 2.16.0

**What did you expect to see?**
Prometheus upgrade shouldn't affect the blackbox-exporter.

**What did you see instead? Under which circumstances?**
We have a setup where we have prometheus and blackbox-exporter running on same machine and this prometheus scrapes local blackbox-exporter. We have 3 of such machines for HA.

On machines where we upgrade the prometheus from 2.15.2 to 2.16.0, we started seeing blackbox-exporter OOMing out. We restrict blackbox-exporter to 128M and hence thought to bump up the memory to 256M but the OOMing issue didn't get solve.

BlackBox Exporter RSS Memory
<img width="1591" alt="Screenshot 2020-03-22 at 10 56 18 PM" src="https://user-images.githubusercontent.com/30620077/77252697-99399680-6c90-11ea-85a9-f08d58195ed1.png">

From above graphs, it looked like a memory leak of some kind. So we took a heap profile for the blackbox exporter.

```
(pprof) top
Showing nodes accounting for 15530.88kB, 100% of 15530.88kB total
Showing top 10 nodes out of 39
      flat  flat%   sum%        cum   cum%
 4357.33kB 28.06% 28.06%  4357.33kB 28.06%  github.com/prometheus/blackbox_exporter/prober.ProbeICMP
 4112.02kB 26.48% 54.53%  4112.02kB 26.48%  bufio.NewReaderSize (inline)
 3084.01kB 19.86% 74.39%  3084.01kB 19.86%  bufio.NewWriterSize
 1026.63kB  6.61% 81.00%  1026.63kB  6.61%  bytes.(*Buffer).String
  902.59kB  5.81% 86.81%   902.59kB  5.81%  compress/flate.NewWriter
  512.19kB  3.30% 90.11%   512.19kB  3.30%  runtime.malg
  512.06kB  3.30% 93.41%   512.06kB  3.30%  net.newFD
  512.02kB  3.30% 96.70%   512.02kB  3.30%  context.propagateCancel
  512.02kB  3.30%   100%   512.02kB  3.30%  net/textproto.NewReader
         0     0%   100%  4112.02kB 26.48%  bufio.NewReader
```

To compare the heap dump, we took on another machine of the HA setup where prometheus is still running 2.15.2. 

```
(pprof) top
Showing nodes accounting for 7379.42kB, 100% of 7379.42kB total
Showing top 10 nodes out of 33
      flat  flat%   sum%        cum   cum%
    3268kB 44.29% 44.29%  3780.56kB 51.23%  github.com/prometheus/blackbox_exporter/prober.ProbeICMP
 1026.63kB 13.91% 58.20%  1026.63kB 13.91%  bytes.(*Buffer).String
  520.04kB  7.05% 65.24%   520.04kB  7.05%  github.com/prometheus/client_golang/prometheus.(*Registry).Gather
     514kB  6.97% 72.21%      514kB  6.97%  bufio.NewReaderSize
     514kB  6.97% 79.18%      514kB  6.97%  bufio.NewWriterSize
  512.56kB  6.95% 86.12%   512.56kB  6.95%  bytes.makeSlice
  512.12kB  6.94% 93.06%   512.12kB  6.94%  net/http.readRequest
  512.06kB  6.94%   100%   512.06kB  6.94%  net.newFD
         0     0%   100%      514kB  6.97%  bufio.NewReader
         0     0%   100%   512.56kB  6.95%  bytes.(*Buffer).Write
```
It looked like some connections are waiting for read and write operation.

We found increase in the number of go routines on blackbox-exporter side too on the machine where we did the prometheus upgrade.

BlackBox Exporter Go Routine Count
<img width="1611" alt="Screenshot 2020-03-22 at 10 56 35 PM" src="https://user-images.githubusercontent.com/30620077/77252702-a8204900-6c90-11ea-9968-35662ddf9014.png">

Most of the checks on the blackbox exporter side are ICMPv4 and ICMPv6 checks. 

Since this happened with prometheus upgrade, we found prometheus opening lot more connections to this blackbox exporter after its upgrade and not closing the older ones..

<img width="1633" alt="Screenshot 2020-03-22 at 10 44 28 PM" src="https://user-images.githubusercontent.com/30620077/77253049-f3d3f200-6c92-11ea-8e21-a9fef243eb61.png">

**Environment**

* System information:

        Linux 4.19.88

* Prometheus version:

        2.16.0

**Comment by brian-brazil** [comment]
I don't see any indication of a bug in the blackbox exporter here. If you have more concurrent requests you'll use more resources.

**Comment by chhetripradeep** [comment]
Sorry for not phrasing it properly. I am not saying its blackbox exporter bug. I feel its a prometheus v2.16.0 bug which isn't closing the connections properly hence leaking connections on blackbox exporter side. Blackbox exporter OOMing is an symptom of it.

**Comment by brian-brazil** [comment]
Does net_conntrack_dialer_conn_established_total vs net_conntrack_dialer_conn_closed_total indicate a leak?

**Comment by chhetripradeep** [comment]
Sorry for late response, i am not sure actually but the way the timeline matches with prometheus upgrade is very suspicious.

**Comment by chhetripradeep** [comment]
I am not sure if you're looking for these graphs, attaching here for reference:

<img width="1669" alt="Screenshot 2020-03-23 at 10 15 30 PM" src="https://user-images.githubusercontent.com/30620077/77326016-1aa62d00-6d54-11ea-98f6-e36ed308f0c5.png">

<img width="1666" alt="Screenshot 2020-03-23 at 10 15 44 PM" src="https://user-images.githubusercontent.com/30620077/77326050-2bef3980-6d54-11ea-8910-9e98e1a2f023.png">

**Comment by brian-brazil** [comment]
Can you show the graph of subtracting them?

**Comment by chhetripradeep** [comment]
net_conntrack_dialer_conn_established_total - net_conntrack_dialer_conn_closed_total graph before prometheus upgrade (7th and 8th March) looks like this:

<img width="1628" alt="Screenshot 2020-03-23 at 11 41 39 PM" src="https://user-images.githubusercontent.com/30620077/77334624-0831f080-6d60-11ea-9a60-80c7f87cb42b.png">

After upgrade, it looks like this

<img width="1632" alt="Screenshot 2020-03-23 at 11 42 04 PM" src="https://user-images.githubusercontent.com/30620077/77334702-213aa180-6d60-11ea-81af-4e39dff72eb9.png">

**Comment by chhetripradeep** [comment]
I think the reason its restricting at around 1k is because of ulimit of open file set to 1024.

**Comment by brian-brazil** [comment]
If you're hitting ulimits then things will break generally, you'll want to bump that.

**Comment by chhetripradeep** [comment]
Right, another thing is to roll back prometheus to 2.15.2 and things will start working as usual. I am not familiar with prometheus codebase but do you think this fix (https://github.com/prometheus/prometheus/pull/7011)  in 2.17.0.rc4 which was a bug introduced in 2.16.0 maybe related to what i am seeing ?

**Comment by brian-brazil** [comment]
No that's unrelated, if you were hitting that your Prometheus would be crashing.

**Comment by chhetripradeep** [comment]
I see, thank you Brian for continuous help.

**Comment by chhetripradeep** [comment]
Hello @brian-brazil after some debugging we figured out that it was https://github.com/golang/go/issues/37525 golang v1.14 issue which was causing this. Our build system was using the latest golang available in our internal repository and hence using v1.14.1 which was biting us here. Thank you once again for your continuous help.
