### ISSUE TITLE
Deliver Prometheus Web GUI as a separate Go package

### ISSUE THREAD

**Issue by tejaswiniVadlamudi** [prometheus/prometheus#7036]
Existing architecture seems to be good at modularization. It would be good to package and deliver Prometheus Web GUI as a separate module. As most of the large scale systems, use other standard visualization dashboards like Grafana, we don't need to package this Web GUI as part of Prometheus delivery. If not, at least code can be refactored to support such flexibility to build without this module.

This is very much needed to not deliver more than needed and to avoid redundant features in any large scale application.

See riot conversation [here](https://matrix.to/#/!HaYTjhTxVqshXFkNfu:matrix.org/$1584628755128726adZDc:matrix.org?via=matrix.org).

**Comment by brian-brazil** [comment]
Reliability is a core goal of Prometheus, and being able to do graphing when everything else is down - including even Grafana - is important.

Is there an actual problem you're having?

> See riot conversation here.

This isn't working.

**Comment by tejaswiniVadlamudi** [comment]
Thanks for the super quick comment Brain!

No, it works perfectly fine for me. But don't want to ship it in Prometheus to my applications. I don't want them to use inbuild API but use Grafana instead which integrates with more instances.

I am curious to know if we can disable this module at Prometheus build. Don't want it to be part of the main Prometheus binary.

Happy to see Prometheus architecture with more modular components.

**Comment by tejaswiniVadlamudi** [comment]
I am not thinking about building one more reverse proxy instead build Prometheus with mandatory modules/packages.

**Comment by brian-brazil** [comment]
If you want to pick and choose you can always maintain and build a custom version, however I don't think that makes sense to be in the core.

**Comment by tejaswiniVadlamudi** [comment]
Sure, is this what other products like Thanos/Cortex is doing it today? Do they have their own custom versions or?

**Comment by bwplotka** [comment]
In Thanos, you can totally use Prometheus UI. Even if people use Grafana it's super useful to have Prometheus UI for some advanced debugging.

In the same time, all Thanos components are planned to have special UI for debugging purposes: https://github.com/thanos-io/thanos/issues/2198

I think we discussed some possibility of headless Prometheus/Thanos Querier, but we did not find enough arguments to have it? In what way those features are problematic? If you are concerned about MBs of a container image, I don't think UI contributes much here (unless with Javascript it grows majorly).

**Comment by tejaswiniVadlamudi** [comment]
1. Do we see this UI as a mandatory component in Prometheus? Tomorrow if we find a bug in Prometheus, does any corner case today recommend using this GUI?
2. As Grafana providing advanced dashboarding capabilities for multiple Prometheus instances, why do I need this GUI block in each Prometheus instance?

**Comment by roidelapluie** [comment]
Yes. To find scrape error messages, you need access to the GUI. Grafana is likely not gonna help there.

I think that you should bring this discussion to our developer mailing list and not in a github issue (you could close this issue maybe), where more people will be able to interact.

**Comment by roidelapluie** [comment]
We have discussed this in our bug scrub and decided that this is out of scope for Prometheus for the reasons mentioned in this thread, so we are closing this issue.
