### ISSUE TITLE
Instant query with [1d:1h] subquery returns 25 results instead of 24

### ISSUE THREAD

**Issue by getjack** [prometheus/prometheus#7041]
**What did you do?**
I have set up a query returning daily values. A subquery is used to help me force granularity of the result set. I use the HTTP API (GET /api/v1/query ) for the request.

> query: sum(increase(my_metrics_count{property="filterA"}[1h:1s])) by (property) [1d:1h]
> time: 1584666000 (This should be 2020-03-21 00:00:00.000 UTC)

Update: I tried another lookup by using the max timestamp 2020-03-21 23:59:59.999 UTC
The result is the same. 25 entries instead of 24. This time the frontend does not add the nanos.

**What did you expect to see?**
A result with 24 entries because a day, split into single hours should contain 24 hours. That is what i expected the subquery to do.

**What did you see instead? Under which circumstances?**
The result contains a matrix with 25 entries. The last (or first) entry is always one hour ahead of the current day so i get a result for 2020-03-21 01:00:00 UTC which i did not request at all.

When doing the same lookup via the frontend they query returns 24 entries. This is because the frontend seems to add a nanosecond to the time parameter
> query: sum(increase(my_metrics_count{property="filterA"}[1h:1s])) by (property) [1d:1h]
> time: 1584666000.421 (This should be 2020-03-21 00:00:00.421 UTC)

For some reasons creates my expected result. This is reproduceable with the HTTP API as well.

**Environment**

* System information:

	No access to shell

* Prometheus version:

	quay.io/prometheus/prometheus:v2.9.1

**Comment by brian-brazil** [comment]
This is expected behaviour, times range are inclusive. You'd see the same without subqueries if the timestamps happened to be aligned just right.

**Comment by brian-brazil** [comment]
> increase(my_metrics_count{property="filterA"}[1h:1s])

Also, this is not a sane query and there's no need to use subqueries here.

**Comment by getjack** [comment]
> This is expected behaviour, times range are inclusive. You'd see the same without subqueries if the timestamps happened to be aligned just right.
At least not what i expected. But i see that, if this ain't a bug, my questions is more of a best practices question. I have not seen any docs for that behavior.

> > increase(my_metrics_count{property="filterA"}[1h:1s])
> 
> Also, this is not a sane query and there's no need to use subqueries here.

The data i have to work with forces me to use the subqueries because it is inconsistent and prometheus would "correct" them in a faulty way. Just wanted to point out my query if that would be the faulty part.

**Comment by roidelapluie** [comment]
You maybe want my_metrics_count{property="filterA"} - my_metrics_count offset 1h

Considering your data does not have resets

**Comment by brian-brazil** [comment]
> Do you understand what i mean :) ?

To be honest I don't, there's insufficient detail in this issue to indicate what's going on as there's several different queries and results conflated.

> The data i have to work with forces me to use the subqueries because it is inconsistent and prometheus would "correct" them in a faulty way. 

That doesn't sound. If the data is bad adding subqueries to the mix won't make it better, you'll only end up with a different set of problems.

**Comment by getjack** [comment]
Ok let's close this issue then. I don't think i can write a better explanation for you.
