### ISSUE TITLE
tsdb Scan command: continue working on the PR from the legacy project

### ISSUE THREAD

**Issue by angulito** [prometheus/prometheus#7047]
## Proposal
**Use case. Why is this important?**
I would like to get this PR https://github.com/prometheus-junkyard/tsdb/pull/320 finishes if it's possible as we will have a tool to fix data corruption / missing data due to a non graceful shutdown or whatever it is the main root cause.

It would help us to deal with issues like:
```
opening storage failed: block dir: \“/prometheus/01E465JQDCJQ4VTJHHXY1DY0CJ\“: open /prometheus/01E465JQDCJQ4VTJHHXY1DY0CJ/meta.json: no such file or directory
```

or 

```
"opening storage failed: invalid block sequence: block time ranges overlap: [mint: 1584972000000, maxt: 1584979200000, range: 2h0m0s, blocks: 3]: <ulid: 01E44NBXZPE2DK62Y1DQZ924XM, mint: 1584972000000, maxt: 1584979200000, range: 2h0m0s>, <ulid: 01E44S5SCY6TF6ZT4D3GRMC9HT, mint: 1584972000000, maxt: 1584979200000, range: 2h0m0s>, <ulid: 01E457SSGHANP2MMJX5FC1A1T1, mint: 1584972000000, maxt: 1584979200000, range: 2h0m0s>"
```

I know @krasi-georgiev was already working on that PR as I've followed his comments, and I really appreciate your work! In case you need any help and I can help you, feel free to ping me and give me details about how I can help. Thanks!

**Comment by krasi-georgiev** [comment]
Are you saying that there are issues reported by people still with these errors?

both of these errors were fixed a long time ago. And will not happen in the recent Prometheus versions.

**Comment by angulito** [comment]
yes, we had that issue yesterday and it never happened to us during more than 1 year that we have prometheus running - we are running prometheus version v2.12.0 - do you think that the issue should not happen again if we upgrade it to the latest stable one? thanks!

**Comment by krasi-georgiev** [comment]
yep, just upgrade to the latest and it will be fine.

Closing this as don't think we need to invest any more time in the scan tool, but feel free to reopen if needed.

**Comment by angulito** [comment]
sounds good, and thanks for the help!!!
