### ISSUE TITLE
Query/Rule Time Regression After Upgrade To 2.17.0

### ISSUE THREAD

**Issue by hawran** [prometheus/prometheus#7048]
**What did you do?**
Upgraded from 2.16.0 -> 2.17.0.

**What did you expect to see?**
Not such a big increase of rule's evaluation time.

**What did you see instead? Under which circumstances?**
As "_a picture is worth a thousand words_" see the screenshots attached:

**prometheus_rule_group_last_duration_seconds:**
![200325-170434 prometheus_rule_group_last_duration_seconds](https://user-images.githubusercontent.com/25924718/77559167-1dbc2d00-6ebc-11ea-92da-f47334555870.png)

**engine_query_duration_seconds (the second graph uses the log10 scale for the Y-axis):**
![200325-170802 engine_query_duration_seconds](https://user-images.githubusercontent.com/25924718/77559239-3a586500-6ebc-11ea-9208-a8514a60fc61.png)

Note the increase of the `prepare_time` slice...

During the time from about 10 am to about 15 pm we were using the version 2.17.0.

**Environment**

* System information:
```
 Kernel Version:                  5.3.0-24-generic
 OS Image:                        Ubuntu 18.04.2 LTS
 Operating System:                linux
```

* Prometheus version:
	2.17.0

**Comment by bwplotka** [comment]
Looks really similar to https://github.com/prometheus/prometheus/issues/6968, but indeed it's for even newer version bumb.

**Comment by SuperQ** [comment]
We also just had to rollback to 2.16.0 due to memory and CPU overload with isolation.

https://gitlab.com/gitlab-com/gl-infra/production/-/issues/1838

We have a very large number or recording rules, some with wide (6 hour) range vectors.

**Comment by roidelapluie** [comment]
I've open #7051

**Comment by hawran** [comment]
> .. are you sure you had 2.16 before? (:

Well, I'm sure it was 2.16.

**Comment by hawran** [comment]
Just to give you more concrete examples (rule groups snippets):

```
expr: sum
  by(namespace, server) (rate(http_client_requests_total{app="watcher",container_name="watcher",status_code!="200"}[5m]))
  / sum by(namespace, server) (rate(http_client_requests_total{app="watcher",container_name="watcher"}[5m]))
  > 0.4
for: 5m
```
![200326-093053 watcher](https://user-images.githubusercontent.com/25924718/77631663-2d378680-6f4d-11ea-94ef-c57da87bef5d.png)


```
expr: sum
  by(server, namespace) (rate(http_client_requests_total{app="michacka",status_code!~"2..|3..|40[^8]|4[1-9]."}[5m]))
  / sum by(server, namespace) (rate(http_client_requests_total{app="michacka"}[5m]))
  > 0.01
for: 1m

expr: sum
  by(server, namespace) (rate(http_client_requests_total{app="michacka",status_code!~"2..|3..|40[^8]|4[1-9]."}[5m]))
  / sum by(server, namespace) (rate(http_client_requests_total{app="michacka"}[5m]))
  > 0.1
for: 1m
```
![200326-093552 michacka](https://user-images.githubusercontent.com/25924718/77631715-417b8380-6f4d-11ea-909a-2bcf6baa2a6a.png)


```
A bunch of 122 expressions...
```

**2.16.0.:**
![200326-094317 slo-iris before-2 17 0](https://user-images.githubusercontent.com/25924718/77632157-e5652f00-6f4d-11ea-9aef-d4972215fc80.png)

**2.17.0.:**
![200326-093929 slo-iris](https://user-images.githubusercontent.com/25924718/77632177-edbd6a00-6f4d-11ea-956f-d8cd29589324.png)

**2.16.0:**
![200326-094527 slo-iris after-2 17 0](https://user-images.githubusercontent.com/25924718/77632277-0c236580-6f4e-11ea-8f8d-e57e06a2ebae.png)

**Comment by hawran** [comment]
Guys, it seems that [v2.17.1](https://github.com/prometheus/prometheus/releases/tag/v2.17.1) fixes the problem.
Let's give it more time...
