### ISSUE TITLE
how about improve `sqrt()` to support N root

### ISSUE THREAD

**Issue by jkklee** [prometheus/prometheus#7054]
Hi, I need to get the `cubic root` of the instant-vector. So I think if we can improve the `sqrt()` function to add a optional arg that represent the N root(arg's default value is 2)

**Comment by brian-brazil** [comment]
There's already a `^` operator.

**Comment by jkklee** [comment]
OH, my fault, thanks a lot!

**Comment by roidelapluie** [comment]
Well it might make sense to still have sqrt I think:

27^(1/3) = 2.9999999999999996 in prometheus.

WDYT?

**Comment by brian-brazil** [comment]
`sqrt` predates `^`, if anything I'd be for removing `sqrt`. I also suspect that cube roots have only very rare uses, and you're going to see numerical analysis issues one way or the other.
