### ISSUE TITLE
remote_write stops working when remote target is a local kubernetes service and restarts

### ISSUE THREAD

**Issue by sukhong** [prometheus/prometheus#7061]
**What did you do?**
We are running a remote_write target within the same kubernetes cluster, and we are using its local service address as a remote_write url:
````
remote_write:
  - url: http://my-service.kube-system.svc.cluster.local/receive
````
This works as expected at the beginning. However, whenever some of target service pods restart, prometheus stops writing to the remote target, and seems to go into an infinite loop without processing further.

When I look at debug-level prometheus logs, I see prometheus-server pods failing with:
````
ts=2020-03-26T23:20:25.200Z caller=dedupe.go:111 component=remote level=debug remote_name=687ab3 url=http://my-service.kube-system.svc.cluster.local/receive msg="failed to send batch, retrying" err="server returned HTTP status 503 Service Unavailable:
````
And some pods failing with:
````
ts=2020-03-26T23:20:45.200Z caller=dedupe.go:111 component=remote level=debug remote_name=687ab3 url=http://my-service.kube-system.svc.cluster.local/receive msg="failed to send batch, retrying" err="Post http://my-service.kube-system.svc.cluster.local/receive: write tcp 10.240.1.227:35064->10.0.78.151:80: write: broken pipe
````
It seems like the culprit is in how prometheus is handling HttpClient. It seems to keep holding onto the stale connection even after service pods terminates, and not able to see the new ip-address for new pods within the service that is mapped by Kubernetes cluster: https://github.com/prometheus/prometheus/blob/aa61e392b23847a771541768e033c2a2c17bb853/storage/remote/client.go#L92

**What did you expect to see?**
Prometheus should continue to write to local service even when any of target service's pods restart.

**What did you see instead? Under which circumstances?**
Prometheus completely stops writing to target service

**Environment**
aks-engine provisioned kubernetes cluster in Azure.
Kubernetes 1.15.10 & 1.17.3 (reproduced in both)

* Prometheus version:
Prometheus 2.15.2 & 2.16.0 (reproducible in both)

* Prometheus configuration file:
```
prometheus.yml:
      remote_write:
        - url: "http://my-service.kube-system.svc.cluster.local/receive"
```

**Comment by roidelapluie** [comment]
cc @brancz

**Comment by csmarchbanks** [comment]
This is likely related to how go handles idle connections, see https://github.com/golang/go/issues/23427. We will need to workaround that issue somehow, closing the idle connections as suggested may work, but I don't love destroying all connections on some timer, and there could be some active connections that aren't cleaned up as we are constantly retrying.

**Comment by brian-brazil** [comment]
If the other end is dead, shouldn't the idle connections have been closed when we tried to use them?

**Comment by csmarchbanks** [comment]
Ideally yes, but the connection may or may not be directly to the deleted pod in question. @sukhong Would you be able to provide a bit more information, specifically what type of Service is being used (clusterIP, headless, etc...), and what kube proxy mode is being used? I was not able to reproduce this immediately.

**Comment by sukhong** [comment]
@csmarchbanks We are using ClusterIP (But same issue with NodePort):

````
apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: kube-system
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: my-service
  selector:
    app: my-service
````
We are also using iptables mode for kube-proxy.

I can easily reproduce this by simply deleting all pods within this service, and Prometheus will stop remote writing immediately.

**Comment by csmarchbanks** [comment]
Hmmm... I am still not able to reproduce using a local cluster. As expected, Prometheus retries a couple sends and once the new pods are up starts sending to them without a problem. 

That said, the load balancing is awful and every request is going to a single pod (the one that came up first). Is it possible that one pod is overwhelmed and causing the 503s you see?

**Comment by DavidParks8** [comment]
I work with @sukhong  on the same clusters. It may help to know that we are running in azure with linkerd.

**Comment by sukhong** [comment]
@csmarchbanks We found out that the root cause is actually Linkerd service mesh we are using. We will investigate with different Linkerd configurations. Thank you so much for a quick response and a help!
