### ISSUE TITLE
Integrate exporters into oneAgent and actively reports to Prometheus

### ISSUE THREAD

**Issue by evandeng2009** [prometheus/prometheus#7062]
## Proposal
**Use case. Why is this important?**

**Few situations that current PULL machism is not adaptive**:
1. VPC resouces can't be monitored as network is not reachable by outside Prometheus. Deploy Prometheus in VPC? No, coz we have thousands or more VPCs who have multiple VMs each, more or less. And generally VMs in VPC can reach outside world thru an universal EIP or something.
2. Firewall running in monitored OS. Many resources have firewall rules not allowing requests from any port other than their own. Monitoring should be transparent, no need for users to additionally set such kinds of rules for monitoring.
3. Exporters expose themselves on a listening port without any authentication or authorizations(Anyway, I'm using Ghostunnel/Stunnel for security enhancement). Let's suppose that exporter is a girl, Prometheus is boy A, others who can request exporters is boy B and this girl and boy A are lovers. Without Ghoustunnel or something help to identify each other, the girl right now does not have capacity of discrimination, is always serving ANYONE, not her boyfriend only, meanwhile taking workload into hosted system. What's more, boy A knows nothing about this. Think about the customized exporters which have business data maybe, a port scan then your data divulged. 
**What to do exactly? Swith to PUSH, add PUSH at least**TSL is on the way to Prometheus but it's a long way I've been waiting for like years. Even if we have TLS available in Prometheus, how about the first 2 concerns? I'm really tired of making sure my Prommetheus servers can reach to exporters, why don't let exporters go for Prometheus like Zabbix? Even without TSL, or further data encryption(yes, plain text as it is now), the girl can ALWAYS get her only boyfriend and the boy A won't worry if anyone else for instance boy B harasses the girl. As for date frenquency, the girl set it herself or boy A tells her or both, does not so matter, as well as hug or kiss.

**Too may exporters, too many ports opened and listening in a single machine**
One exporter cooperates with a specified target, like OS, Middleware. Everything has OS at least so at least 2 exporters running in each of OS. How about more applications running and port occupied by an exporter?
**What to do exactly?** I'm thinking put them together named as oneAgent like Dynatrace oneAgent. No matter what your technology and what application is, oneAgent is all you have to install, configure and run. Configure it in appropriate config block if you have corresponding things to monitor and only then that exporter model will start.

*“Nice to have” is not a good use case. :)*

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
