### ISSUE TITLE
Improve func histogram_quantile

### ISSUE THREAD

**Issue by d-ulyanov** [prometheus/prometheus#7071]
#7018  Proposal
**Use case. Why is this important?**

Hello, colleagues :)

Usually, when we're querying `histogray_quantile(xx, expr)` we do it more than one time for the same series to calculate 0.5, 0.9, 0.99 quantiles - it is a common scenario not only for us, but for many users (I noted it on many public Grafana dashboards).

It would be very useful to improve `histogram_quantile()` function to accept more than one quantile in arguments because:
1) one query instead of multiple
2) it's more efficient because we're touching exactly the same series to calculate the result

I see the two options how this feature could be implemented to keep backward compatibility:

- New function like `histogray_quantiles_list(expr, 0.5, 0.9, 0.99)`
- `histogram_quantile(0.5, 0.9, 0.99, expr)` - better from client point of view, but probably not the best choise for implementation

What do you think?

**Comment by brian-brazil** [comment]
Things like this have come up before, and this is not something that we plan on adding. You can already do this via multiple queries.

**Comment by d-ulyanov** [comment]
@brian-brazil thanks for your answer.
Could you please share your thoughts why don't you plan to add such things?

**Comment by brian-brazil** [comment]
It's unneeded complexity for something that's already possible.

**Comment by d-ulyanov** [comment]
ok, thank you, Brian!
