### ISSUE TITLE
How to survive in-memory 2 hour prometheus data during restarts/failover/upgrades

### ISSUE THREAD

**Issue by dinesh4747** [prometheus/prometheus#7072]
Hi Team,

**Current setup:**

I am using using prometheus setup running along with thanos for extended storage to accomodate 2 months of data for longer persistence

- 2 Instances of prometheus (0 replica/1 replica) and both this instances enabled with thanos-sidecar
- thanos-sidecar subsequently writes data to GCS bucket for extended long term storage
- thanos querier connected to two instances and reading data via store gateway
- Challenge/Issue in current setup:

**Despite of having long term storage we would still be losing potential data of real time/latest/current 2 hours.(storage.tsdb.max-block-duration=2h) - How do we handle the below cases?**

1. Backup/snapshot for older instance during upgrade will be an option (But it cannot be seamless and will fail to perform fault tolerance and post-facto)
2. 2 HA Instances of prometheus to handle DR scenarios but if both the instances fail then it will lose all 2 hours data with extreme case

**Question:**

Is there any efficient mechanism instilled within prometheus to save 2 hours data during restarts/crash recovery/upgrade? what measures/guidelines should we follow to minimize the data loss with less disruption

**Comment by hoffie** [comment]
I guess the mailing list is better suited for this inquiry. I see that you have already posted there:
https://groups.google.com/forum/#!msg/prometheus-users/3uBtnyeXdLo/XNyEHnZtBAAJ
