### ISSUE TITLE
Investigate remote write resharding conditions

### ISSUE THREAD

**Issue by cstyan** [prometheus/prometheus#7078]
Remote write currently will not reshard, up or down, if there hasn't been any successful sends recently. This can be problematic for a number of reasons.

1) If the remote system has been down unable to accept writes for a long time (hours, not minutes) it's possible remote write will never get out of a state where it won't be able to successfully send. For example, when cortex cuts a block for a time frame, it no longer accepts samples outside this timeframe. If remote write is far enough behind, and can't upshard to work it's way through the backlog (all of which won't be accepted by cortex), it could always be stuck in this state where the data it's trying to send it too old.

2) We could treat some other HTTP status codes as reshardable scenarios. While it's unlikely to happen, if you imagine remote write is receving 429's (rate limit) it would be a good idea to allow (or perhaps force?) downsharding.

cc @slim-bean @jtlisi

part of #6333

**Comment by brian-brazil** [comment]
> If remote write is far enough behind, and can't upshard to work it's way through the backlog (all of which won't be accepted by cortex),

That kind of sounds like a problem on Cortex's end, as this is an expected scenario.

> if you imagine remote write is receving 429's (rate limit) it would be a good idea to allow (or perhaps force?) downsharding.

I don't think we gain anything by adding complexity when the other end already can't handle the load.

**Comment by csmarchbanks** [comment]
> If remote write is far enough behind, and can't upshard to work it's way through the backlog (all of which won't be accepted by cortex), it could always be stuck in this state where the data it's trying to send it too old.

In this case the backend system should be returning a 4xx, but it looks like for the purposes of resharding we consider 4xx and 5xx classes of errors to be the same. Should we be treating non-recoverable errors as ok in the case of resharding?

**Comment by cstyan** [comment]
Yes I think it makes sense to treat some non-recoverable errors as ok for the purposes of resharding.

**Comment by slim-bean** [comment]
Mainly the situation we encountered was something like this:

```
Remote write is working fine, sending with say 100 shards.

Remote endpoint goes away for some reason, prom fails to send.

Remote endpoint comes back a long time in the future, prom resumes sending however is met with 400 errors "out of bounds" because the remote won't accept the old timestamps.

Remote won't shard up because it hasn't seen enough 200's, it's still sending with the 100 shards which was the steady state before the outage.
```

Without accelerating (sharding up) through the old data the prom will never be able to catch up as it's always behind and sending at the rate that was appropriate for when it was current, but not a rate needed to catch up.

I think treating 400 errors the same as 200 errors makes sense for the purposes of resharding with the exception of 429, where resharding would only exacerbate the problem of sending into a rate limit.

**Comment by csmarchbanks** [comment]
I crated https://github.com/prometheus/prometheus/pull/7122 for the first issue for when non-recoverable errors are encountered.

Changing the handling of 429s is a different issue. One solution would be to consider 429s as recoverable errors and go through the regular backoff/retry logic. To me backoff should be sufficient and it is unnecessary to also force downsharding. That said, the prometheus default max backoff is currently only 100ms, perhaps that should be increased?

**Comment by Harkishen-Singh** [comment]
Will like to take this up.

**Comment by Harkishen-Singh** [comment]
Sorry for the delay here.

> Changing the handling of 429s is a different issue. One solution would be to consider 429s as recoverable errors

As per the discussion, is this the only thing left as part of this issue? @csmarchbanks

**Comment by csmarchbanks** [comment]
I am closing this as the sharding conditions have already been addressed, and all that is left is handling 429s more intelligently. #8418 is a more specific issue for that work.
