### ISSUE TITLE
prometheus_web_federation metrics not available on prometheus metric endpoint

### ISSUE THREAD

**Issue by juliantaylor** [prometheus/prometheus#7080]
The prometheus web_federation error metrics are not available on the metrics endpoint where the other prometheus metrics are available
The metrics are in the source code though:
https://github.com/prometheus/prometheus/blob/master/web/federate.go#L37

Maybe some registering is missing?

**What did you do?**
on a prometheus with federations timing out
`curl -s prometheus:9090/metrics | grep federation_fai`

The log of the prometheus prints the failures, the log is printed with the metric export in the source so the metric should be there:
```
level=error ts=2020-04-02T11:31:17.906Z caller=federate.go:184 component=web msg="federation failed" err="write tcp 100.70.202.8:9090->100.68.240.115:45096: write: broken pipe"
```

**What did you expect to see?**
I expected the metrics to appear:
prometheus_web_federation_errors_total
prometheus_web_federation_warnings_total

**What did you see instead? Under which circumstances?**
nothing

* Prometheus version:

	2.16.0

**Comment by brian-brazil** [comment]
Looks like they were never registered, would you like to send a PR?

**Comment by juliantaylor** [comment]
I'll give it a try
