### ISSUE TITLE
Add offending target to error metrics like prometheus_target_scrapes_sample_duplicate_timestamp_total

### ISSUE THREAD

**Issue by omerlh** [prometheus/prometheus#7091]
## Proposal
**Use case. Why is this important?**
When having scrape issue like `prometheus_target_scrapes_sample_duplicate_timestamp_total`, it's important to know which target has the problematic metrics for monitoring purposes - in our cases, we want teams to own their services and be able to get alert/investigate issues relevant only for their services.
So instead of having a generic alert on `prometheus_target_scrapes_sample_duplicate_timestamp_total`, ideally we could have the same alert by target (job) and route it to the relevant person. Without it, those metrics are not actionable and hard to use when running a multi-tenant cluster with a single Prometheus instance.

Side note: Yes, I know we *should* run multiple Prometheus instances, but this our long term solution and will take more time to implement.

**Comment by brian-brazil** [comment]
Per-target information doesn't belong on Prometheus /metrics as that's not information about Prometheus itself, and would also pose cardinality issues. You have to work off logs in this case.

**Comment by omerlh** [comment]
How do we gat other target metrics like `scrape_samples_scraped`? maybe we can use the same mechanism?

**Comment by brian-brazil** [comment]
They're inside Prometheus' database. The challenge with the scrape_ metrics is that they are an overhead for every single scrape by every single Prometheus in existence, so there's a high bar to adding them. I don't think it would be a good tradeoff to add one purely to aid in detecting exporters incorrectly using timestamps, which you can already determine from logs.

**Comment by omerlh** [comment]
On the other hand, this metric is a bit useless - it's not actionable unless you have Prometheus per namespace...

**Comment by brian-brazil** [comment]
It tells you that you have broken targets, and you can debug from there. Metrics fundamentally can't tell you exactly what is wrong at that level of granularity, you need logs to complement them.

**Comment by roidelapluie** [comment]
targets should in general not expose timestamps except for federation.

AFAIK, you can also look at:
scrape_samples_scraped-scrape_samples_post_metric_relabeling > 0

to help you debugging that. Not perfect but a first good step.

**Comment by omerlh** [comment]
Moving the discussion to prometheus-operator, where the alert is defined.
