### ISSUE TITLE
Prometheus/Alertmanager embedded Auth/Basic Auth

### ISSUE THREAD

**Issue by fchiorascu** [prometheus/prometheus#7092]
**Use case. Why is this important?**
Because will not use nginx, haproxy, other WO to put the Auth in place which could put complexity and resource consumption IaaS (VMs)/PaaS (OpenShift Container Platform).

*“Nice to have” is not a good use case. :)*
It's perfect to have it and is not a nice to have, I think is a security best practice to have something coming with this solution and not using another app.

**Comment by roidelapluie** [comment]
Thank you for your report.

Basic authentication is on our roadmap: https://prometheus.io/docs/introduction/roadmap/
Currently work is being done to support TLS/Client-certificate authentication. We are currently working on that TLS part but can't say in which version of Prometheus this will be available. Work on basic auth hasn't started yet.

Please see our security guide if you want to learn more https://prometheus.io/docs/operating/security/ and in the time being, we have a guide to do basic auth with an external tool: https://prometheus.io/docs/guides/basic-auth/

(Note that if someone wants to help with this, make sure to get in touch before working too much on it so we can point you in the right direction.)

**Comment by fchiorascu** [comment]
@roidelapluie thank you for the details.
I've already implemented Nginx (reverse proxy) for Prometheus/alertmanager from 1y ago.
It will be great to have the security/auth in place for future releases.

**Comment by rickypai** [comment]
I started a WIP PR since we're also interested in this functionality: https://github.com/prometheus/prometheus/pull/8088

**Comment by roidelapluie** [comment]
Fixed by #8317. Alertmanager support will come soon.

**Comment by bboreham** [comment]
@roidelapluie is that number correct?

**Comment by roidelapluie** [comment]
Off by one error, #8316
