### ISSUE TITLE
support scrape loop graceful reload 

### ISSUE THREAD

**Issue by Betula-L** [prometheus/prometheus#7097]
**How to reproduce it?**

- Edit sample_limit from `10000` to `100001`
or
- Edit scrape_timeout from `30s` to `1m`

Trigger reload, then 30 of 3000 instances report `down` because of `lastError="Get http://10.69.140.12:9100/metrics: context canceled"`

**What did you expect to see?**

`Reload` will cancel involved current `scrapeLoop`, and prometheus mark this `scrapeLoop` as down. 

We can not distinguish whether instances were really down or just misreported by reload now.

**Possible solution 1:**
set `up` value as 'NAN' if `context canceled`

**Possible solution 2:**
do not record `up` if `context canceled`

**Environment**

* Prometheus version:

prometheus, version 2.16.0 (branch: HEAD, revision: b90be6f32a33c03163d700e1452b54454ddce0ec)
  build user:       root@7ea0ae865f12
  build date:       20200213-23:50:02
  go version:       go1.13.8

* Prometheus configuration file:

```
  - job_name: node_exporter
    honor_labels: true
    honor_timestamps: true
    scrape_interval: 1m
    scrape_timeout: 33s
    metrics_path: /metrics
    scheme: http
    sample_limit: 100001
```

**Comment by brian-brazil** [comment]
Reporting up as 0 is correct, as the scrape failed. I'm not sure that we should be cancelling contexts on reload though, that's for shutdown.

**Comment by Betula-L** [comment]
We can not distinguish whether instances were really down or just misreported by reload now.

**Comment by brian-brazil** [comment]
Your monitoring generally should be tolerant to a single failed scrape, as that can happen for all sorts of reasons.

**Comment by Betula-L** [comment]
Yes, you are right. 

However, in some sensitive condition, especially critical service, there should no unexpected dirty data by reload.

I think it is not expected behavior, does it?

**Comment by brian-brazil** [comment]
It needs some investigation, which is why I haven't closed the issue.

**Comment by Betula-L** [comment]
Got it, thanks.

**Comment by Betula-L** [comment]
Current scrape loop reload step:
1. create new loop
2. stop old loop immediately (cancel all current scrape)
3. run new loop
4. return reload success

However, "cancel immediately" leads to two side effects:
1. misreport "up" metric due to reload cancel
2. prometheus do not scrape for a while after reload because random scraping offset.

Thus, it's better that stop old scrape loops gracefully.

**Comment by Betula-L** [comment]
There are two approaches to implement graceful scrape reload:

Synchronous reload (option 1):
1. create new loop
2. stop old loop gracefully (wait for last scrape finished)
3. run new loop
4. return reload success

Synchronous reload may spend much time for waiting last scrape if there are some timeout scrape loops.
In the worst case scenario, the reload response just need spend max scrape timeout.

Asynchronous reload (option 2):
1. create new loop
2. return reload success
3. stop old loop gracefully (wait for last scrape finished in backgroud goroutine)
5. run new loop after stop old loop gracefully

**Comment by Betula-L** [comment]
@brian-brazil any suggestion for that plz.

Scrape do not work when reload really bothers

**Comment by brian-brazil** [comment]
We're already meant to be doing option 1, if we aren't that's a regression that needs to be fixed.

**Comment by roidelapluie** [comment]
My investigation shows that this is a valid bug.

**Comment by roidelapluie** [comment]
Done in #7752, thanks!

**Comment by Betula-L** [comment]
Thanks a lot!
