### ISSUE TITLE
Too many "too old resource version" warnings (github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:385)

### ISSUE THREAD

**Issue by hawran** [prometheus/prometheus#7102]
**What did you do?**
Looked for something into logs from Prometheus and saw a plethora of
```
level=warn ts=...Z caller=klog.go:86 component=k8s_client_runtime func=Warningf msg="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:385: watch of *v1.Pod ended with: too old resource version:  number (other number)"
```
lines.

Regarding https://github.com/prometheus/prometheus/issues/5853, why is this the `warning` level despite it ["is intended behavior"](https://github.com/prometheus/prometheus/issues/5853#issuecomment-520344645)?
Why not `debug`?

**What did you see instead? Under which circumstances?**
See above.

**Environment**

* System information:
 Kernel Version:                  5.3.0-24-generic
 OS Image:                        Ubuntu 18.04.2 LTS
 Operating System:                linux
 Architecture:                    amd64
 Kubelet Version:                 v1.14.8
 Kube-Proxy Version:              v1.14.8

* Prometheus version:
2.17.1

**Comment by roidelapluie** [comment]
Thanks for the report

@brancz can I have your opinion on this? Is this a bug or a support request? thanks

**Comment by brancz** [comment]
The problem is that this is called from within Kubernetes code that we happen to vendor, we don't control what log level this is written to.

**Comment by hawran** [comment]
> The problem is that this is called from within Kubernetes code that we happen to vendor, we don't control what log level this is written to.

I see.
Oh well, we could close the issue, I'd say.

**Comment by brancz** [comment]
Thanks for reporting! :)

**Comment by fcddk** [comment]
level=warn ts=2020-05-22T03:39:01.299Z caller=klog.go:86 component=k8s_client_runtime func=Warningf msg="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:263: watch of *v1.Pod ended with: too old resource version: 25023445 (25026262)"

**Comment by fcddk** [comment]
level=warn ts=2020-05-28T09:30:46.056Z caller=klog.go:86 component=k8s_client_runtime func=Warningf msg="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:263: watch of *v1.Pod ended with: too old resource version: 41354348 (41356716)"
level=warn ts=2020-05-28T09:31:09.546Z caller=klog.go:86 component=k8s_client_runtime func=Warningf msg="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:281: watch of *v1.Pod ended with: too old resource version: 41355663 (41356880)"
level=warn ts=2020-05-28T09:31:38.615Z caller=klog.go:86 component=k8s_client_runtime func=Warningf msg="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:263: watch of *v1.Pod ended with: too old resource version: 41356551 (41357120)"
level=warn ts=2020-05-28T09:36:20.876Z caller=klog.go:86 component=k8s_client_runtime func=Warningf msg="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:263: watch of *v1.Pod ended with: too old resource version: 41357965 (41359180)"
level=warn ts=2020-05-28T09:41:40.072Z caller=klog.go:86 component=k8s_client_runtime func=Warningf msg="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:263: watch of *v1.Pod ended with: too old resource version: 41361101 (41361611)"
level=warn ts=2020-05-28T09:42:50.941Z caller=klog.go:86 component=k8s_client_runtime func=Warningf msg="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:261: watch of *v1.Endpoints ended with: too old resource version: 41360722 (41361533)"
level=warn ts=2020-05-28T09:43:32.787Z caller=klog.go:86 component=k8s_client_runtime func=Warningf msg="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:261: watch of *v1.Endpoints ended with: too old resource version: 41359490 (41361853)"
level=warn ts=2020-05-28T09:43:44.964Z caller=klog.go:86 component=k8s_client_runtime func=Warningf msg="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:261: watch of *v1.Endpoints ended with: too old resource version: 41360036 (41361938)"
level=warn ts=2020-05-28T09:45:41.569Z caller=klog.go:86 component=k8s_client_runtime func=Warningf msg="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:281: watch of *v1.Pod ended with: too old resource version: 41361285 (41363497)"
level=warn ts=2020-05-28T09:49:46.638Z caller=klog.go:86 component=k8s_client_runtime func=Warningf msg="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:263: watch of *v1.Pod ended with: too old resource version: 41361505 (41365180)"
level=warn ts=2020-05-28T09:49:46.910Z caller=klog.go:86 component=k8s_client_runtime func=Warningf msg="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:263: watch of *v1.Pod ended with: too old resource version: 41363556 (41365180)"
level=warn ts=2020-05-28T09:53:22.092Z caller=klog.go:86 component=k8s_client_runtime func=Warningf msg="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:263: watch of *v1.Pod ended with: too old resource version: 41365924 (41366699)"
level=warn ts=2020-05-28T10:00:05.977Z caller=klog.go:86 component=k8s_client_runtime func=Warningf msg="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:261: watch of *v1.Endpoints ended with: too old resource version: 41366852 (41369181)"
level=warn ts=2020-05-28T10:00:06.801Z caller=klog.go:86 component=k8s_client_runtime func=Warningf msg="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:261: watch of *v1.Endpoints ended with: too old resource version: 41366768 (41369181)"
level=warn ts=2020-05-28T10:01:22.587Z caller=klog.go:86 component=k8s_client_runtime func=Warningf msg="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:281: watch of *v1.Pod ended with: too old resource version: 41367831 (41370206)"
level=warn ts=2020-05-28T10:01:52.959Z caller=klog.go:86 component=k8s_client_runtime func=Warningf msg="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:261: watch of *v1.Endpoints ended with: too old resource version: 41366471 (41369960)"
level=warn ts=2020-05-28T10:02:49.959Z caller=klog.go:86 component=k8s_client_runtime func=Warningf msg="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:263: watch of *v1.Pod ended with: too old resource version: 41369551 (41370812)"
level=warn ts=2020-05-28T10:03:18.657Z caller=klog.go:86 component=k8s_client_runtime func=Warningf msg="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:263: watch of *v1.Pod ended with: too old resource version: 41369551 (41371015)"
