### ISSUE TITLE
Proposal: Add a context to API dependencies interfaces

### ISSUE THREAD

**Issue by gotjosh** [prometheus/prometheus#7103]
## Proposal

At the moment, API dependencies interfaces don't support any arguments e.g.

```golang
type targetRetriever interface {
	TargetsActive() map[string][]*scrape.Target
	TargetsDropped() map[string][]*scrape.Target
}

type alertmanagerRetriever interface {
	Alertmanagers() []*url.URL
	DroppedAlertmanagers() []*url.URL
}

type rulesRetriever interface {
	RuleGroups() []*rules.Group
	AlertingRules() []*rules.AlertingRule
}
```

Given the Prometheus API package can be exported by third-parties, it is useful to pass a context to the dependant functions as they get called directly on the API endpoints. This allows for third-parties to introduce cancellation or authentication concerns on the implementations. 

**Use case. Why is this important?**

Particularly, we need it in Cortex as it handles authentication via the Context.

**Comment by bwplotka** [comment]
I think it's a good pattern, given those APIs are used directly by Prometheus HTTP API, so passing `r.Context()` would be expected. :+1:  LGTM from me.

**Comment by bwplotka** [comment]
Just curios where you use those interfaces? Do you use `api.go` or what?

**Comment by gotjosh** [comment]
You can see the [Cortex usage here](https://github.com/cortexproject/cortex/blob/1f600cb162efc4b4b42a609d406e2f0803743073/pkg/api/api.go#L239). I don't think the interfaces need to be exported to have them supported 😄. However, I see no reason why they shouldn't be public.

**Comment by bwplotka** [comment]
I mean yes, they are only useful for existing structs that require them.

Cool, looks like you are using exactly `api`  so yes, big yes from me to add context then :+1: .

**Comment by bwplotka** [comment]
Thanos cannot use api as we add more request parameters on top of Prometheus.. unless we change the `api.go` a bit (:

**Comment by brian-brazil** [comment]
Contexts only really make sense where we have a timeout/cancellation use for them, and offhand all of those are fast mutex-based calls so contexts don't help us.

**Comment by bwplotka** [comment]
Also @gotjosh how context helps you with auth? Context does not have headers :thinking:

**Comment by gotjosh** [comment]
> Contexts only really make sense where we have a timeout/cancellation use for them, and offhand all of those are fast mutex-based calls so contexts don't help us.

That makes sense. As an example, the call to `TargetsActive` and `TargetsDropped` on the `TargetRetriever` does take a lock on scrapping.

Do you think there's an alternative here @brian-brazil? I'd like to continue to import `api`. Sorry if this obvious, but since the interface implementation is left to the individual (outside of Prometheus) it can help us in our case. 

> Also @gotjosh how context helps you with auth? Context does not have headers.

We use middleware for that.

**Comment by brian-brazil** [comment]
I'd personally try to handle all auth stuff for these endpoints before it ever hit the api code.

**Comment by gotjosh** [comment]
In our case, the auth is handled in a middleware - before it even hits the API code. We rely on the context to propagate it after resolution. 

Downstream implementations, might do similar things (or cancellations) with the context too. It's more about context propagation due to the different implementation of the interface that just authentication.

I think that even if the context is unused in Prometheus, general downstream implementations can benefit from this. But for us, it means avoid us having to reinvent `api.go`. Possibly for Thanos too, as they can do something similar to what we're doing and inject the params passed in the request to the context and extract them from there.

**Comment by bwplotka** [comment]
Yup, can agree here, context would actually allow Thanos to use this API.
So LGTM from my side.

**Comment by juliusv** [comment]
Rather than making contexts spread through the entire codebase in places where Prometheus itself does not need them, could an option be to contain this to api.go and for example instead of passing in a `targetRetriever`, you pass in a factory function (e.g. `newTargetRetriever()`) that creates the retriever for each request based on the request / request context? And in the "normal" Prometheus case, it would just return a static target retriever for each request.

**Comment by gotjosh** [comment]
I'm happy with what @juliusv proposes. Does that work for you @brian-brazil?

**Comment by brian-brazil** [comment]
That seems a small enough change to be okay.
