### ISSUE TITLE
"opening storage failed: invalid block sequence: block time ranges overlap

### ISSUE THREAD

**Issue by nishant-ketu** [prometheus/prometheus#7112]
level=error ts=2020-04-10T11:30:01.011389822Z caller=main.go:625 err="opening storage failed: invalid block sequence: block time ranges overlap: [mint: 1586260800000, maxt: 1586268000000, range: 2h0m0s, blocks: 2]: <ulid: 01E5HV2H8MXNEZ7D7ER7KB4850, mint: 1586260800000, maxt: 1586268000000, range: 2h0m0s>, <ulid: 01E5HV2F6CB93FVY86TGJRVH56, mint: 1586260800000, maxt: 1586268000000, range: 2h0m0s>\n[mint: 1586246400000, maxt: 1586253600000, range: 2h0m0s, blocks: 43]: <ulid: 01E5HV213VBS2FQZVXG3NB5DWZ, mint: 1586246400000, maxt: 1586253600000, range: 2h0m0s>, <ulid: 01E5HX8DPDX4TZ5QBZAFAMAFV2, mint: 1586246400000, maxt: 1586253600000, range: 2h0m0s>, <ulid: 01E5HV2BX8QQ12908FZ2FK1TT5, mint: 1586246400000, maxt: 1586253600000, range: 2h0m0s>, <ulid: 01E5HX6E5ASWETXREER37PJ6NZ, mint: 1586246400000, maxt: 1586253600000, range: 2h0m0s>, <ulid: 01E5HX4EQ4YHMAZBX97WFPQ19Z, mint: 1586246400000, maxt: 1586253600000, range: 2h0m0s>, <ulid: 01E5HV2HW8TYP36Z9M75RN7SX2, mint: 1586246400000, maxt: 1586253600000, range: 2h0m0s>, <ulid: 01E5HV2R6VMFJ99Y6643JW218C, mint: 1586246400000, maxt: 1586253600000, range: 2h0m0s>, <ulid: 01E5HV30M7GJYDJW0E10DYFZE7, mint: 1586246400000, maxt: 1586253600000, range: 2h0m0s>, <ulid: 01E5HV3CTP7C5ZRNHVBS2J7T0N, mint: 1586246400000, maxt: 1586253600000, range: 2h0m0s>, <ulid: 01E5HV40WAKFGA6NYWVCQWMMR4, mint: 1586246400000, maxt: 1586253600000, range: 2h0m0s>, <ulid: 01E5HV54MJ0R03ZND1QPMB2P61, mint: 1586246400000, maxt: 1586253600000, range: 2h0m0s>, <ulid: 01E5HV73P2CFM3MHEPXKKH2S9F, mint: 1586246400000, maxt: 1586253600000, range: 2h0m0s>, <ulid: 01E5HV92QQE7A3HC4TETGPFGHK, mint: 1586246400000, maxt: 1586253600000, range: 2h0m0s>, <ulid: 01E5HVB1QMVCZ640H8W354CWSG, mint: 1586246400000, maxt: 1586253600000, range: 2h0m0s>, <ulid: 01E5HVD0WXVBV2ZMQ336DM5RRG, mint: 1586246400000, maxt: 1586253600000, range: 2h0m0s>, <ulid: 01E5HVF0088R0ZP1KKSHAC284W, mint: 1586246400000, maxt: 1586253600000, range: 2h0m0s>, <ulid: 01E5HVGZ3A2RW1AXKRBFC2N3V4, mint: 1586246400000, maxt: 1586253600000, range: 2h0m0s>, <ulid: 01E5HVJY6THSVWMZ4EDF56XW9W, mint: 1586246400000, maxt: 1586253600000, range: 2h0m0s>, <ulid: 01E5HVMXCPR8G7GB3B72NHDDQ6, mint: 1586246400000, maxt: 1586253600000, range: 2h0m0s>, <ulid: 01E5HVPWKACQW6AGN3WAPGC6GC, mint: 1586246400000, maxt: 1586253600000, range: 2h0m0s>, <ulid: 01E5HVRVSMW32BF4JP2P13J0KF, mint: 1586246400000, maxt: 1586253600000, range: 2h0m0s>, <ulid: 01E5HVTV38V23DP5BCWEHCVJDV, mint: 1586246400000, maxt: 1586253600000, range: 2h0m0s>, <ulid: 01E5HVWTAPDT7A406TZKZH48BK, mint: 1586246400000, maxt: 1586253600000, range: 2h0m0s>, <ulid: 01E5HVYSK9ABAV9WYNVPGC6713, mint: 1586246400000, maxt: 1586253600000, range: 2h0m0s>, <ulid: 01E5HW0RWCYNBN5Y6VYSPCA1R1, mint: 1586246400000, maxt: 1586253600000, range: 2h0m0s>, <ulid: 01E5HW2R5ZA2ASQG25MYETTW21, mint: 1586246400000, maxt: 1586253600000, range: 2h0m0s>, <ulid: 01E5HW4QMPXZAD6V2QQ355XHTF, mint: 1586246400000, maxt: 1586253600000, range: 2h0m0s>, <ulid: 01E5HW6PXQMCS4EY7MQPM2WT02, mint: 1586246400000, maxt: 1586253600000, range: 2h0m0s>, <ulid: 01E5HW8P7MA95N054ZR5FM8A3S, mint: 1586246400000, maxt: 1586253600000, range: 2h0m0s>, <ulid: 01E5HWANKHZN6E36B63YK9FFRK, mint: 1586246400000, maxt: 1586253600000, range: 2h0m0s>, <ulid: 01E5HWCMYM6EAYMJ409WN1GRPV, mint: 1586246400000, maxt: 1586253600000, range: 2h0m0s>, <ulid: 01E5HWEM9SWTHF5975DYX6JS2C, mint: 1586246400000, maxt: 1586253600000, range: 2h0m0s>, <ulid: 01E5HWGKQ3CE7NC9ZPKGGEHT0C, mint: 1586246400000, maxt: 1586253600000, range: 2h0m0s>, <ulid: 01E5HWJK7ESNGTM1TSJ1VFVP6Y, mint: 1586246400000, maxt: 1586253600000, range: 2h0m0s>, <ulid: 01E5HWMJP4YQKQY5ZFPBXKS6ZB, mint: 1586246400000, maxt: 1586253600000, range: 2h0m0s>, <ulid: 01E5HWPJ9HB5HQN8F94ZY25C7F, mint: 1586246400000, maxt: 1586253600000, range: 2h0m0s>, <ulid: 01E5HWRJ1WCPH3DNFBVNYAA85H, mint: 1586246400000, maxt: 1586253600000, range: 2h0m0s>, <ulid: 01E5HWTHE84ZRMHQ9054PKX0BK, mint: 1586246400000, maxt: 1586253600000, range: 2h0m0s>, <ulid: 01E5HWWGVVMGNKP0037CSEVJP2, mint: 1586246400000, maxt: 1586253600000, range: 2h0m0s>, <ulid: 01E5HWYG7XFYYAVMKFZ1X3AZZ7, mint: 1586246400000, maxt: 1586253600000, range: 2h0m0s>, <ulid: 01E5HX0FPQ1E71E2A7ANJG7QB1, mint: 1586246400000, maxt: 1586253600000, range: 2h0m0s>, <ulid: 01E5HX2F5KTDKFERHVM9ZEQ0N6, mint: 1586246400000, maxt: 1586253600000, range: 2h0m0s>, <ulid: 01E5HXAD5W3PMA5757X9ZR87K9, mint: 1586246400000, maxt: 1586253600000, range: 2h0m0s>"

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
