### ISSUE TITLE
Meaningless log: unsupported value type

### ISSUE THREAD

**Issue by fcddk** [prometheus/prometheus#7118]
Prometheus version: 2.15.2

log: 
level=debug ts=2020-04-14T04:42:44.779Z caller=consul.go:464 component="discovery manager scrape" discovery=consul msg="Watching service" service=stackdev-ceph tags="unsupported value type"
level=debug ts=2020-04-14T04:42:44.782Z caller=consul.go:347 component="discovery manager scrape" discovery=consul msg="Watching services" tags="unsupported value type"

prometheus config:
level=debug ts=2020-04-14T04:42:44.779Z caller=consul.go:464 component="discovery manager scrape" discovery=consul msg="Watching service" service=stackdev-ceph tags="unsupported value type"
level=debug ts=2020-04-14T04:42:44.782Z caller=consul.go:347 component="discovery manager scrape" discovery=consul msg="Watching services" tags="unsupported value type"

**Comment by fcddk** [comment]
code:
`// Watch the catalog for new services we would like to watch. This is called only
// when we don't know yet the names of the services and need to ask Consul the
// entire list of services.
func (d *Discovery) watchServices(ctx context.Context, ch chan<- []*targetgroup.Group, lastIndex *uint64, services map[string]func()) {
	catalog := d.client.Catalog()
	level.Debug(d.logger).Log("msg", "Watching services", "tags", d.watchedTags)`

**Comment by fcddk** [comment]
// Get updates for a service.
func (srv *consulService) watch(ctx context.Context, ch chan<- []*targetgroup.Group, catalog *consul.Catalog, lastIndex *uint64) {
	level.Debug(srv.logger).Log("msg", "Watching service", "service", srv.name, "tags", srv.tags)

**Comment by roidelapluie** [comment]
Fixed in prometheus 2.17 https://github.com/prometheus/prometheus/pull/6783
