### ISSUE TITLE
Memory Leak in 2.17.1

### ISSUE THREAD

**Issue by vsliouniaev** [prometheus/prometheus#7121]
**What did you do?**
We run prometheus in pairs, in hundreds of Kubernetes clusters. We started rolling out upgrades from `v2.16.0` to `v2.17.1`.

**What did you expect to see?**
No major difference in performance.

**What did you see instead? Under which circumstances?**
Prometheus will use more and more CPU and memory until it eventually is OOM-killed by docker. This does not occur in 100% of cases, but a reliable way to detect is a steady ramp of CPU usage. In about 50% of the cases where this happens, one of the pods will exhibit this behaviour while the other does not with identical configurations.

The rule evaluation duration time also keeps increasing

CPU:
![CPU](https://i.imgur.com/Eg3joxs.jpg)

Memory:
![memory](https://imgur.com/g5oRXXG.jpg)

The heap profile is the most telling in this case and suggests a memory leak is the issue:
![heap](https://imgur.com/PQvhuJb.jpg)

Other parameters like goroutines appear to be normal.

**Environment**

* System information:
`Linux 5.0.0-1032-azure x86_64`

* Prometheus version:
```
prometheus, version 2.17.1 (branch: HEAD, revision: ae041f97cfc6f43494bed65ec4ea4e3a0cf2ac69)
  build user:       root@806b02dfe114
  build date:       20200326-16:18:19
  go version:       go1.13.9
```

* Prometheus configuration file:
```
global:
  scrape_interval: 30s
  scrape_timeout: 10s
  evaluation_interval: 30s
...
```
Would rather not include the rest of the file as it is rather large and does not appear to be relevant.

* Logs:
No relevant logs

**Comment by bwplotka** [comment]
Thank for this. Very useful feedback indeed. We will investigate. :+1: 

It was already reported seconds before your issue: https://github.com/prometheus/prometheus/issues/7120 Closing one as a duplicate. Let's continue the investigation on that ticket. :hugs:
