### ISSUE TITLE
enable Clickjacking Header

### ISSUE THREAD

**Issue by fernando-domenike** [prometheus/prometheus#7126]
How can I fix the clickjacking vulnerability.

I have Prometheus in the PCI DSS environment and I need to fix this vulnerability.

Do you have any resources or procedures?

**Comment by brian-brazil** [comment]
Can you explain more about what you're asking for? If you have found a way to reproduce a security issue, the procedure for reporting it is at https://prometheus.io/docs/operating/security/

**Comment by fernando-domenike** [comment]
@brian-brazil, muito obrigado. ;)

**Comment by roidelapluie** [comment]
We have decided in the bug scrub to close this issue, and decided to close this bug as lack of info.

If you have a detailed security issue, can you use our security procedure described in https://prometheus.io/docs/operating/security/ ?

Thanks.
