### ISSUE TITLE
RuleGroups.Validate(...) needs unexported struct ruleGroups as input

### ISSUE THREAD

**Issue by sylr** [prometheus/prometheus#7128]
I'm trying to upgrade prometheus dep in thanos and I'm stuck with this:

```shell
$ make build
all modules verified
>> building binaries /Users/s.rabot/go/bin
 >   thanos
# github.com/thanos-io/thanos/cmd/thanos
cmd/thanos/check.go:88:29: not enough arguments in call to promRgs.Validate
	have ()
	want (rulefmt.ruleGroups)
```

https://github.com/prometheus/prometheus/blob/51c824543bca2f25baa6596827cf4fad8f18dc2e/pkg/rulefmt/rulefmt.go#L66

cc @bwplotka

**Comment by bwplotka** [comment]
Why you put issue on Prometheus for this? It's normal we will have build errors to fix.  We plan to upgrade deps after chunk iterator.

**Comment by sylr** [comment]
Because, unless I'm mistaken, I thought there was little that can be done in thanos if prometheus does not export `ruleGroups` or adds a `NewruleGroups() ruleGroups` func.

Am I wrong ?

**Comment by aclowkey** [comment]
I think it should be exported for non-thanos related reasons.
For example if I want to build a tool that manages alerts, and not implement my own validation logic, I can't.

**Comment by brian-brazil** [comment]
Use of our internals by 3rd parties is unsupported, but we will generally accept PRs to make things public.

**Comment by bwplotka** [comment]
Let's move forward with this then... (: 

It's blocking https://github.com/thanos-io/thanos/pull/2535

**Comment by bwplotka** [comment]
Are you still happy to continue this @sylr

**Comment by sylr** [comment]
@bwplotka I wish I could but I am pretty busy at the moment.

**Comment by roidelapluie** [comment]
Actually the way forward is to get back to yaml.v2 as there are missing features in yaml.v3

**Comment by bwplotka** [comment]
Do you have any details / related discussion @roidelapluie ?

**Comment by sylr** [comment]
https://github.com/prometheus/prometheus/pull/7142#discussion_r410899455

**Comment by roidelapluie** [comment]
Actually things are moving now.. I will see that later on.

**Comment by roidelapluie** [comment]
cmd/thanos/check.go > I do not see that file in thanos codebase?

**Comment by bwplotka** [comment]
It just changed - it is now in cmd/thanos/tools.go
