### ISSUE TITLE
Expose total number of label pairs in head

### ISSUE THREAD

**Issue by brancz** [prometheus/prometheus#7147]
## Proposal
**Use case. Why is this important?**

For scale analysis it would be great if we either exposed a metric that reflects the total number of labels (name + value combinations) in the head block. Potentially this could also be an entry in the head block cardinality section on the status page. I don't care how I just want to get the numbers out somehow and can't today.

Side note, yes top 10 cardinality labels are useful, but may be hiding a long tail of labels that still affect the head's index, but we can't be sure until we are able to validate with numbers.

Overall context: I'm researching some other indexing strategies and it's crucial to have some real world numbers for that.

@brian-brazil @roidelapluie @bwplotka @csmarchbanks @simonpasquier

**Comment by bwplotka** [comment]
Yes! 

I would go even further and have a metric of avg label value and name length. Or total. (:

**Comment by brian-brazil** [comment]
Let's keep whatever roughly in sync with what the tsdbutil analyze command does.

**Comment by brancz** [comment]
Agreed.

**Comment by csmarchbanks** [comment]
> I would go even further and have a metric of avg label value and name length. Or total. (:

Seems like a good case for a histogram, I would definitely be interested to see the distribution in size.

**Comment by khyatisoneji** [comment]
I can take this up. Is this a good first issue? Please help me with relevant packages/files that I can take a look at.
I have some context of what is included in tsdb block, please refer me to relevant files and I will revert back with my understanding.

**Comment by brian-brazil** [comment]
It should be a reasonable first issue. The code is all in https://github.com/prometheus/prometheus/blob/master/tsdb/head.go

Offhand I'd say the code would go in `getOrCreateWithID` and `gc`.

**Comment by nevill** [comment]
no updates here for a while, let me try to help.

**Comment by longngn** [comment]
Hi, I'm new contributor to Prometheus. Even though there're 2 PRs already, they're all stale. That's why I'd like to take on this issue.

**Comment by brian-brazil** [comment]
Please go ahead.

**Comment by codesome** [comment]
With #8343 it will be now available in TSDB stats page

**Comment by brancz** [comment]
Awesome! Closing since #8343 is merged.
