### ISSUE TITLE
allow to override the default PrometheusURL in alerts

### ISSUE THREAD

**Issue by gesellix** [prometheus/prometheus#716]
When running Prometheus in a Docker container and producing alerts, they contain a GeneratorURL looking like this: `http://b640ba8f91c1:9090//graph#...`. The `b640ba8f91c1` hash is a generated Docker container hostname. Obviously, such hostnames are useless in the actual alerts (or in the Alertmanager `/alerts` overview).

Would it make sense to add a configuration option  setting the desired external hostname? When empty, the current mechanism could be used.

**Comment by brian-brazil** [comment]
I think this is a good idea.

**Comment by gesellix** [comment]
@brian-brazil should I provide a PR?

**Comment by brian-brazil** [comment]
If you can that'd be great.

**Comment by juliusv** [comment]
@gesellix Add it as a flag to https://github.com/prometheus/prometheus/blob/master/web/web.go

**Comment by gesellix** [comment]
@juliusv proposed flag name: `web.hostname` ok?

**Comment by juliusv** [comment]
@gesellix Sounds good.

**Comment by gesellix** [comment]
resolved with #717
