### ISSUE TITLE
Prometheus running in a docker-compose container does not see node_exporters on other hosts.

### ISSUE THREAD

**Issue by jeffhoffman13** [prometheus/prometheus#7164]
**What did you do?**
I have Prometheus and Grafana running on localhost via docker-compose file. but can not see node_eporters running on other nodes
**What did you expect to see?**
The node_expoter nodes show up in the prometheus nodes under targets
**What did you see instead? Under which circumstances?**
No nodes
**Environment**
Centos 7.7
* System information:
Linux 3.10.0-957.27.2.el7.x86_64
	insert output of `uname -srm` here

* Prometheus version:
Current
	insert output of `prometheus --version` here
2.17.1 latest
* Alertmanager version:
Not installed
	insert output of `alertmanager --version` here (if relevant to the issue)

*Docker-compose file
# docker-compose.yml
version: '3'

volumes:
    prometheus_data: {}
    grafana_data: {}

services:
  prometheus:
    image: prom/prometheus:latest
    network_mode: "host"
    container_name: prometheus
    volumes:
#      - /local/configs/prometheus.yml:/etc/prometheus/prometheus.yml
      - /local/configs/prometheus.yml:/etc/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    ports:
        - '9090:9090'
        - '9100:9100'
    labels:
      org.label-schema.group: "monitoring"

#  alertmanager:
#    image: prom/alertmanager:v0.20.0
#    container_name: alertmanager
#    volumes:
#      - /local/configs/alertmanager:/etc/alertmanager
#    command:
#      - '--config.file=/etc/alertmanager/config.yml'
#      - '--storage.path=/alertmanager'
#    restart: unless-stopped
#    ports:
#      - '9093:9093'
#    labels:
#      org.label-schema.group: "monitoring"
#
#  node-metrics:
#    image: prom/node-exporter:latest
#    container_name: node-metrics
#    volumes:
#      - /proc:/host/proc:ro
#      - /sys:/host/sys:ro
#      - /:/rootfs:ro
#    command:
#      - '--path.procfs=/host/proc'
#      - '--path.rootfs=/rootfs'
#      - '--path.sysfs=/host/sys'
#      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
#    restart: unless-stopped
#    depends_on:
#      - prometheus
#    ports:
#        - '9200:9200'
#    labels:
#      org.label-schema.group: "monitoring"
#
#  cadvisor:
#    image: gcr.io/google-containers/cadvisor:v0.34.0
#    container_name: cadvisor
#    volumes:
#      - /:/rootfs:ro
#      - /var/run:/var/run:rw
#      - /sys:/sys:ro
#      - /var/lib/docker:/var/lib/docker:ro
#      - /cgroup:/cgroup:ro #doesn't work on MacOS only for Linux
#    restart: unless-stopped
#    ports:
#      - '8080:8080'
#    labels:
#      org.label-schema.group: "monitoring"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - /local/configs/grafana/provisioning:/etc/grafana/provisioning
    environment:
#      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
#      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-pass}
      - GF_SECURITY_ADMIN_PASSWORD=-pass
#      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    labels:
      org.label-schema.group: "monitoring"

* Prometheus configuration file:
# prometheus.yml

global:
  scrape_interval:      15s
  evaluavtion_interval: 15s
  external_labels:
      monitor: 'Orthros Cluster'

scrape_configs:
 - job_name: 'node-metrics'
   static_configs:
    - targets: ['shepherd:9100',
                'terrier:9100']

 - job_name: 'prometheus'
   static_configs:
    - targets: ['localhost:9090']
                'shepherd:9100',
                'terrier:9100']

insert configuration here
```

* Alertmanager configuration file:
```
insert configuration here (if relevant to the issue)
```


* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
