### ISSUE TITLE
promtool should support checking a single expression

### ISSUE THREAD

**Issue by epkugelmass** [prometheus/prometheus#7167]
Currently promtool support checking multiple expressions as defined in a rule file. If you want to lint a single expression, you need to arbitrarily/needlessly stick the expression in a rule file. 

I propose extending promtool with the sub-command `promtool check expressions` that takes a number of expressions from a file or stdin, with one expression per line to be checked. Notably, this proposal does not support multi-line rules. After all, we're not in the context of YAML.

This functionality is especially useful when preparing promql expressions for other systems like Grafana. In my case, I'm managing Grafana dashboards in Git so I don't have the Grafana GUI to quickly tell me that my promql is invalid. I'd like to lint my Grafana JSON, extract the promql, and run it through a checker.

**Comment by Harkishen-Singh** [comment]
Maybe, a flag like `-i` for instantaneous checking of expressions might be better after `promtool check expressions` for implementing this.

**Comment by SandeepVaman** [comment]
If we need this feature to be implemented, I would like to pick this up.

**Comment by POD666** [comment]
Looking forward to use this feature 🙂

**Comment by LeviHarrison** [comment]
Following the lead of `check metrics`, I think it makes sense to pass in any file contents over stdin:

```
cat expressions.txt | promtool check expressions
```

For single expressions (besides just `echo "expr" | ...`) we could support:

```
promtool check expression expr
```

But I'm not sure if it's necessary

**Comment by krajorama** [comment]
Hello from the bug scrub, this has been implemented via the [promtool promql format](https://prometheus.io/docs/prometheus/latest/command-line/promtool/#promtool-promql-format) command line tool.
