### ISSUE TITLE
Prometheus Tracing

### ISSUE THREAD

**Issue by MarcelHillmann** [prometheus/prometheus#7168]
Hi,

I have build a local version of prometheus, that use zipkin or jaeger for tracing the promql and the targets.

As I tried to create a PR, I found the PR-2554. 
Which include the information that "the group would't like to have the dependency in the project".

I played a time with the information, and would like to implement a plugin interface.
Then I could develop 2 single shared object, that could be loaded with the [golang plugin](https://golang.org/pkg/plugin/) functions.

Is this a vaild / interessting aproch?

Thanks
Marcel

**Comment by brian-brazil** [comment]
That's a little out of date now. The release of Prometheus which is in progress includes Jaeger, but only on an experimental stop-gap basis until a OpenTelemetry is settled.

Go plugins would not help here.

**Comment by MarcelHillmann** [comment]
Hi,

Thanks for the Info.

Marcel
