### ISSUE TITLE
Prometheus 2.17 gives EOF error for rabbitmq targets

### ISSUE THREAD

**Issue by dheerajpala** [prometheus/prometheus#7173]
**What did you do?**
We have a rabbitmq exporting metrics using prometheus rabbitmq exporter.
Added these targets in prometheus 2.17

**What did you expect to see?**
Targets being scraped

**What did you see instead? Under which circumstances?**
Got an error shown as below.

Get <URL>/rabbitmq/api/metrics/: EOF

**Environment**

These targets were being scraped perfectly fine in version 2.6, but failing in version 2.16 and 2.17.

```

**Comment by brian-brazil** [comment]
Do you have a tcpdump of what's different?

**Comment by dheerajpala** [comment]
Hi Brian, 

Sorry for the delayed response, we're actually in a restricted environment, so we'll check if the tcpdump can be shared.

Regarding the issue we've noticed that there was an extra line at the end of the metrics received from rabbitmq exporter.

****************
erlang_vm_allocators{alloc="driver_alloc",instance_no="56",kind="sbcs",usage="blocks_size"} 0
erlang_vm_allocators{alloc="driver_alloc",instance_no="56",kind="sbcs",usage="carriers"} 0
erlang_vm_allocators{alloc="driver_alloc",instance_no="56",kind="sbcs",usage="carriers_size"} 0

****************

which is not the case for metrics from other apps. Could this be causing the EOF error?

**Comment by brian-brazil** [comment]
No, that wouldn't cause it. Lacking a tcpdump I'm not sure there's much we can do here, but if you can provide one please let us know so we can reopen and look into this.
