### ISSUE TITLE
deriv() returns tiny float values for constant series

### ISSUE THREAD

**Issue by SuperQ** [prometheus/prometheus#7180]
**What did you do?**

Query `deriv(foo[5m])`

**What did you expect to see?**

All zero samples.

**What did you see instead? Under which circumstances?**

Some samples return tiny (> e-13) non-zero values.

![image](https://user-images.githubusercontent.com/1320667/80469621-19fb4a80-8941-11ea-80a3-e4a6d722646a.png)

Range vector data:

[deriv-error.json.gz](https://github.com/prometheus/prometheus/files/4544561/deriv-error.json.gz)

**Environment**

* Prometheus version:

```
prometheus, version 2.17.1 (branch: HEAD, revision: ae041f97cfc6f43494bed65ec4ea4e3a0cf2ac69)
  build user:       root@806b02dfe114
  build date:       20200326-16:18:19
  go version:       go1.13.9
```

* Prometheus configuration file:

```
- job_name: elasticsearch_logging
  scrape_interval: 30s
```

**Comment by beorn7** [comment]
Now and then, when I have a few idle cycles, I do some work on #5692. My current plan is to use a proper numerical library for the linear regression. That could/should also deal with the issue here.

**Comment by brian-brazil** [comment]
I'd thought we'd fixed this back in #2958, I'm surprised we'd have an issue with such relatively small numbers.

**Comment by beorn7** [comment]
With the improvement in #9588, `deriv(vector(123847394833945)[5m:10s])` reliably returns 0, while `deriv(vector(1238473948339456)[5m:10s])` returns a small (but constant) value.

Without it, the effect happens earlier, `deriv(vector(1238473948339)[5m:10s])` vs. `deriv(vector(12384739483394)[5m:10s])`.

That's definitely an improvement.

We could still try a "proper" numerical library. And/or we could implement an explicit shortcut for constant time series.

What do you all think?

**Comment by beorn7** [comment]
BTW: The deviations reported by the OP were due to tiny changes in the timestamp. The metric value was quite low (1057). With the timestamp clamping, it's hard to create those tiny jitters in Prometheus these days.

**Comment by beorn7** [comment]
I simulated time jitter with a weird scrape interval (99ms). Again, the Kahan summation worked better, but only slightly so in this case.

Therefore, to really "solve" this issue, we have to do even better. Not sure if the "proper" numerical libraries special-case constant input, or how reasonable it is to do. It would certainly be easy to implement…
