### ISSUE TITLE
can I build prometheus from source code by using go natively (not through promu)

### ISSUE THREAD

**Issue by ggpaue** [prometheus/prometheus#7190]
**What did you do?**
build prometheus from source code 
Or can it be built using go natively?
many thanks!
**What did you expect to see?**
it can be built using go natively
**What did you see instead? Under which circumstances?**
promu is mandatory for building prometheus
**Environment**
Linux, macOS

* System information:
Darwin 17.7.0 x86_64

* Prometheus version:

	insert output of `prometheus --version` here

* Alertmanager version:

	insert output of `alertmanager --version` here (if relevant to the issue)

* Prometheus configuration file:
```
insert configuration here
```

* Alertmanager configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```

**Comment by roidelapluie** [comment]
Promu is not mandatory. You can go to cmd/prometheus and run go build.

It is best to ask those questions in the developers mailing list rather than in a github issue.

**Comment by ggpaue** [comment]
thank you for your comment @roidelapluie !
is there anyway I can build npm_licenses.tar.bz2 by using go natively?

**Comment by roidelapluie** [comment]
It is best to ask those questions in the [developers mailing list](https://groups.google.com/forum/#!forum/prometheus-developers) rather than in a closed github issue. In the mailing list more people will be able to help you.
