### ISSUE TITLE
Regex does not work on `__name__` in an `unless` clause

### ISSUE THREAD

**Issue by nickhaskins** [prometheus/prometheus#7215]
**What did you do?**
We have an exporter that exports various metrics. It is occasionally missing data on some metrics and I wanted to create an alert on this condition, so I wrote the following query:

```
{app="au-cloudwatch-exporter", component="consolidated"} offset 1m unless {app="au-cloudwatch-exporter", component="consolidated"}
```
Which returned more data than I wanted so I tried to filter like this:

```
{app="au-cloudwatch-exporter", component="consolidated",, __name__!~".*ebs.*"} offset 1m unless {app="au-cloudwatch-exporter", component="consolidated", __name__!~".*ebs.*"}
```

**What did you expect to see?**
I expected to see a subset of the data presented with the first query. 

**What did you see instead? Under which circumstances?**
I see no data at all.  I confirmed that the following query does return data though:

```
{app="au-cloudwatch-exporter", component="consolidated",, __name__="au_cloudwatch_exporter_aws_rds_burst_balance_average"} offset 1m unless  {app="au-cloudwatch-exporter", component="consolidated", __name__="au_cloudwatch_exporter_aws_rds_burst_balance_average"}
```

**Environment**

* System information:

Linux 4.9.0-11-amd64 x86_64

* Prometheus version:

prometheus, version 2.10.0 (branch: HEAD, revision: d20e84d0fb64aff2f62a977adc8cfb656da4e286)
  build user:       root@a49185acd9b0
  build date:       20190525-12:28:13
  go version:       go1.12.5

* Alertmanager version:

N/A

* Prometheus configuration file:
can provide if relevant

* Alertmanager configuration file:
N/A

* Logs:
Nothing in the logs about this

**Comment by brian-brazil** [comment]
Selectors aren't affected by what subsequently uses them, so if there's a bug here it'd have to be with the selector itself - which seems unlikely. Can you confirm that the data you're looking for exists at the exact timestamps you're running the query at?

**Comment by roidelapluie** [comment]
I guess that this rule could produce multiple times the same labelset with different values, which would be rejected by TSDB when inserting.

I suggest you also run label_replace(selector,"__original_name","$1","__name__","(.*)") to keep the name variable.

**Comment by brian-brazil** [comment]
If it were in a recording rule it'd fail the promql query before it even got to ingestion. There's also nothing in the provided query that'd remove the metric name.

**Comment by roidelapluie** [comment]
I guess is is due to the `,,` in the selector:

`Error executing query: parse error at char 9: unexpected "," in label matching, expected identifier`

**Comment by nickhaskins** [comment]
The double comma is actually just copy pasta.  If i remove the duplicated comma I still see the issue.  I have confirmed that both parts of the query have data at the specified time, and the second part has less time series than the first.  I've even run both parts separately and paired up the results myself and gotten the expected result.  For clarity, the separate queries I ran are:
```
{app="au-cloudwatch-exporter", component="consolidated", __name__!~".*ebs.*"} offset 1m
```
and
```
{app="au-cloudwatch-exporter", component="consolidated", __name__!~".*ebs.*"}
```

Attached are screenshots of the prometheus UI confirming this:
<img width="1288" alt="Screen Shot 2020-05-07 at 9 09 32 AM" src="https://user-images.githubusercontent.com/845495/81298343-a8a75000-9042-11ea-9089-7cdc7cbe31b2.png">
<img width="1288" alt="Screen Shot 2020-05-07 at 9 09 57 AM" src="https://user-images.githubusercontent.com/845495/81298352-a9d87d00-9042-11ea-8b6c-0bf67ea3ae28.png">

**Comment by roidelapluie** [comment]
but unless does not care about __name__ and that is not a bug.

**Comment by nickhaskins** [comment]
My expectation is that `unless` doesn't treat `__name__` any differently, which is why I'm confused about why my query returns no data.  It certainly seems that there is a bug with the way this query gets interpreted that makes the `__name__` regex matter for some reason - I wouldn't think it would be on purpose though.

**Comment by roidelapluie** [comment]
Can you provide us the complete metrics of both queries?

**Comment by brian-brazil** [comment]
> My expectation is that unless doesn't treat __name__ any differently, which is why I'm confused about why my query returns no data.

Most things treat `__name__` differently as otherwise `a + b` wouldn't work as expected, if you want to match on name you need to be explicit - but that's generally something to avoid. Regexes against name are a smell.

**Comment by nickhaskins** [comment]
> Can you provide us the complete metrics of both queries?

Yeah but I'll need to scrub out some of the data so it will take a bit. I'll see what I can do in the next couple of days.

> Regexes against name are a smell.

Agreed, I'm admittedly doing something kind of weird, a sort of meta-query.

Looking over the data again, it actually seems the regex part of this may have been a red herring.  The following query only returns results that have `ebs` in them at the same timestamp:
```
{app="au-cloudwatch-exporter", component="consolidated"} offset 1m unless  {app="au-cloudwatch-exporter", component="consolidated"}
```

Specifying a `__name__` of `au_cloudwatch_exporter_aws_rds_burst_balance_average` in both parts of the query does return 55 time series though at the same timestamp.

**Comment by nickhaskins** [comment]
I have a scrubbed version of the output for each of three queries:
```
{app="au-cloudwatch-exporter', component="consolidated"}
```

```
{app="au-cloudwatch-exporter', component="consolidated"} offset 1m
```

```
{app="au-cloudwatch-exporter', component="consolidated"} offset 1m unless {app="au-cloudwatch-exporter", component="consolidated"}
```

The output of each is attached below in the zip file `sanitized_queries.zip`
[sanitized_queries.zip](https://github.com/prometheus/prometheus/files/4610655/sanitized_queries.zip)
 as, respectively, `sanitized_now.json`, `sanitized_offset.json` and `sanitized_full_query.json`.  These data sets were captured by curling to our prometheus server with query `{hostname}/api/v1/query -d query='{app="au-cloudwatch-exporter", component="consolidated"} offset 1m' -d time=2020-05-05T16:47:06Z`, with each of the different queries.  These data sets were then run through a stateful sanitizer that replaced internal label names with sanitized values consistently through all three data sets.  I have also written a little script[1] to do a set difference (which maps to my understanding of an `unless`) with this data and validated that the set difference is the output I expect from prometheus, and is different from the data I got running the full query.


[1]
```
import argparse
import json
import pprint

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('now')
    parser.add_argument('offset')
    args = parser.parse_args()
    with open(args.now, 'r') as f:
        now = json.load(f)
    with open(args.offset, 'r') as f:
        offset = json.load(f)

    offset_labels = set()
    for m in offset['data']['result']:
        labels = ';'.join(sorted(['%s:%s' % (l, m['metric'][l]) for l in m['metric']]))
        if labels in offset_labels:
            raise ValueError("duplicate label set in offset: %s" % labels)
        offset_labels.add(labels)

    now_labels = set()
    for m in now['data']['result']:
        labels = ';'.join(sorted(['%s:%s' % (l, m['metric'][l]) for l in m['metric']]))
        if labels in now_labels:
            raise ValueError("duplicate label set in now: %s" % labels)
        now_labels.add(labels)

    comp = offset_labels - now_labels
    pprint.pprint(comp)

if __name__ == "__main__":
    main()
```

**Comment by nickhaskins** [comment]
Any thoughts here? Does this issue still need more information?

**Comment by nickhaskins** [comment]
I was able to reproduce this in a promql test (in the format of `prometheus.git/promql/testdata`) FWIW:

```
load 5m
    offset_matching_a{job="api-server", group="production"}             0+10x10
    offset_matching_a{job="api-server", group="canary"}                 0+20x10
    offset_matching_a{job="app-server", group="production"}             0+30x10
    offset_matching_a{job="app-server", group="canary"}                 4
    offset_matching_b{job="api-server", group="production"}             0+50x10
    offset_matching_b{job="api-server", group="canary"}                 6
    offset_matching_b{job="app-server", group="production"}             0+70x10
    offset_matching_b{job="app-server", group="canary"}                 8

eval instant at 10m offset_matching_a{group="canary"} offset 5m unless offset_matching_a{group="canary"}
    offset_matching_a{group="canary", job="app-server"} 4

eval instant at 10m offset_matching_b{group="canary"} offset 5m unless offset_matching_b{group="canary"}
    offset_matching_b{group="canary", job="api-server"} 6
    offset_matching_b{group="canary", job="app-server"} 8

eval instant at 10m {group="canary"} offset 5m
    offset_matching_a{group="canary", job="api-server"} 20
    offset_matching_a{group="canary", job="app-server"} 4
    offset_matching_b{group="canary", job="api-server"} 6
    offset_matching_b{group="canary", job="app-server"} 8

eval instant at 10m {group="canary"}
    offset_matching_a{group="canary", job="api-server"} 40

eval instant at 10m {group="canary", job="app-server"} offset 5m unless {group="canary", job="app-server"}
    offset_matching_a{group="canary", job="app-server"} 4
    offset_matching_b{group="canary", job="app-server"} 8

eval instant at 10m {group="canary", __name__="offset_matching_b", job="api-server"} offset 5m unless {group="canary", __name__="offset_matching_b",  job="api-server"}
    offset_matching_b{group="canary", job="api-server"} 6

# Fails with an empty result set
eval instant at 10m {group="canary", job="api-server"} offset 5m unless {group="canary", job="api-server"}
    offset_matching_b{group="canary", job="api-server"} 6

# Also fails, missing the job="api-server" metric
eval instant at 10m {group="canary"} offset 5m unless {group="canary"}
    offset_matching_a{group="canary", job="app-server"} 4
    offset_matching_b{group="canary", job="api-server"} 6
    offset_matching_b{group="canary", job="app-server"} 8
```

**Comment by roidelapluie** [comment]
Your test is not valid as you load the same labelset with different values at the same timestamp.

**Comment by nickhaskins** [comment]
@roidelapluie Which labelset has two values at the same timestamp?

**Comment by roidelapluie** [comment]
Oh sorry. app/api _a/_b makes it hard to read.

**Comment by nickhaskins** [comment]
> Most things treat __name__ differently as otherwise a + b wouldn't work as expected, if you want to match on name you need to be explicit 

This turns out to be the root cause.  Unless does not in fact do matching on `__name__` unless you explicitly ask it to, which judging from the above, is probably intentional.  Compounding the confusion in this case is that there were different metrics with the exact same labelset except for `__name__`, causing the unless to cancel them out (while others, i.e. the ones with `ebs`, had only one metric with the same labelset).  Verified with my test and the real data that if I do an `on (__name__, etc)` explicitly it works as expected.  I'll close this issue, feel free to re-open, etc. as you see fit.

**Comment by roidelapluie** [comment]
Thank you. Do we have tests for on(__name__) ?

**Comment by nickhaskins** [comment]
> Thank you. Do we have tests for on(**name**) ?

No, how would I go about proposing some?

**Comment by roidelapluie** [comment]
You could add simple tests in `promql/testdata/operators.test`.
