### ISSUE TITLE
Creating a snapshot via admin API fails because it attempts to write it to the wrong directory

### ISSUE THREAD

**Issue by campee** [prometheus/prometheus#7216]
OS: CentOS release 6.9
Prometheus version: prometheus-2.18.0-1.x86_64

My system has two volumes: one for the OS (/) and one for Prometheus data (/logs). I'm starting Prometheus with the following argument: --storage.tsdb.path=/logs I've also enabled the admin API so I can create snapshots of my data. When I issue the API request to create a snapshot, it responds with an error: "invalid cross-device link". I did some digging and it's generating that error because it's trying to create a hard-link in /snapshots, which is on my OS volume (a different volume) and thus hard-links are not allowed. Why is it creating the snapshots in /snapshots though? if I look in /snapshots I can see the directory structure of my data but no actual files. Shouldn't it be creating the snapshot within the volume that I specified for my storage.tsdb.path? i.e. /logs/snapshots?

**Comment by roidelapluie** [comment]
This is a bug.

**Comment by roidelapluie** [comment]
Fixed by #7217 in the next 2.18.1

**Comment by bwplotka** [comment]
Fixed & released: https://github.com/prometheus/prometheus/releases/tag/v2.18.1

Thanks for super-quick feedback! @campee :heart:

**Comment by bwplotka** [comment]
Added task to prevent it: https://github.com/prometheus/prometheus/issues/7227
