### ISSUE TITLE
endpoint   Failure

### ISSUE THREAD

**Issue by fuguohong1024** [prometheus/prometheus#7220]
yesterday ，i add svc and endpoitn to monitor kube-scheduler. everthing is ok.
but today i find prometheus target missing,and 
` kubectl get endpoints -n kube-system`,endponit is none.
[root@node130 manifests]# kubectl get endpoints -n kube-system
NAME                      ENDPOINTS                                                                  AGE
kube-scheduler            \<none\>                                                                   140d

**Comment by fuguohong1024** [comment]
then `kubectl apply -f prometheus-kubeSchedulerServiceEnpoints.yaml` again,it`s ok ,but y?
NAME                      ENDPOINTS                                                                  AGE
kube-scheduler            192.168.1.160:10251,192.168.1.161:10251,192.168.1.162:10251                140d

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by fuguohong1024** [comment]
> It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

emmmm,you know,  some country has the great wall, in network. Actually， i can`t visit the website  like groups.google.com
