### ISSUE TITLE
math in range selector

### ISSUE THREAD

**Issue by kfox1111** [prometheus/prometheus#7233]
**Use case. Why is this important?**

I have some data caps in places. They are reset every month. I would like to alert when the current network bytes transferred is within a certain percentage of my cap within the month. The metric in question is a counter.

The only way I can see to do this with a counter, is to do a range selector with some psudocode:
increase(data_transferred[(day_of_month() * 24 * 60 * 60 + hour() * 60 * 60 + minute() * 60 + seconds())s] > xxxxxxxx

But currently its got to be hard coded to an integer. Could support for this be added?

**Comment by brian-brazil** [comment]
Ranges being variables would make things quite complicated in terms of PromQL, as the current code is highly optimised for them being constant. I'd suggest taking an approach based on daily values.

**Comment by kfox1111** [comment]
Essentially it would resolve to a constant which could then run through the query engine exactly the same it is now. Not sure why this would be a problem?

Also, not sure what you mean by daily values. How would that work? Got an example?

Thanks!

**Comment by roidelapluie** [comment]
What you want to achieve is possible with a few recording rules, let me give that a try later.

**Comment by brian-brazil** [comment]
Scalars can vary by step, and in addition scalars don't have a unit. Generally Prometheus cares about arbitrary fixed time periods, and doesn't care about things like months or time zones.

**Comment by kfox1111** [comment]
@roidelapluie Ok, Thanks for giving it a shot. I'm curious how that could work. :)

@brian-brazil varying by step could be a problem. yeah. maybe the possible queries could be limited to functions that aren't? In the example, I put the scaler in parens, while still allowing the unit to be specified. That's the most flexible but maybe it should just be in seconds always.

I get Prometheus generally doesn't care about months or timezones. But I think at least the use case is within Prometheus's wheel house? Collect metrics, alert when a query on the data shows somethings wrong or somethings about to go wrong. I'm not tied to the particular solution, more the use case, so if @roidelapluie's solution works, great. :)

**Comment by brian-brazil** [comment]
> maybe the possible queries could be limited to functions that aren't?

There are no such functions, a scalar is a scalar.

I don't think it makes sense to do this in Prometheus, there's various ways of approaching it in PromQL already.

**Comment by kfox1111** [comment]
@roidelapluie Get a chance to come up with a solution? I've tried a few times myself and not figured out a way to do it.

I'm kind of surprised that there isn't an easy way to bucket by time interval like month as I would think SLO's are a common Prometheus use case?

**Comment by roidelapluie** [comment]
I have tried but not succeeded because of the way Prometheus interpolates.

**Comment by roidelapluie** [comment]
Now that the fact it is not possible in promql does not mean it is not possible in Prometheus.

You could write a small script which uses the API and feed it back into prometheus.

**Comment by kfox1111** [comment]
Yeah. I was looking at that option too. or the option to dynamically rewrite a ServiceMonitor that hardcodes the labels. It feels really brittle though.

I looked at recording rules but while alerts seem to allow templating labels in gotl, regular rules don't seem to allow it.

Recording rules with gotl label support with time functions available would help. or gotl support during relabeling would help. or a function that can convert values to labels would work, or math in the range selector, or probably other mechanisms. But it seems very difficult to handle something as seemingly simple as "how much X have I used this Y time period".

**Comment by brian-brazil** [comment]
Prometheus is designed to handle arbitrary Y time periods - but where Y is fixed. Something that changes on a 28-31 day cycle is not fixed. This is best done with a little bit of scripting outside Prometheus.

**Comment by kfox1111** [comment]
how do you do that when you want to alert on it with an alerting rule?

It feels like it should be possible to do with Prometheus without an external script which could be brittle. Something you don't want in an alerting system.

I'd like to put in a feature request for this, but there is many different ways of solving it I think. Which way should it go? Or should I just file a request for a solution for the use case instead of an implementation?

**Comment by brian-brazil** [comment]
I'd alert on daily/hourly values. Otherwise it'd have too many false positives/negatives depending on the stage in the month. That's if I'd even alert on these at all, general latency/error alerting should generally catch it.

**Comment by kfox1111** [comment]
How do you do that, when outside forces are measuring based on things like a calendar? I don't control it. I'd like to alert not when I use more then X thingies a day, but the thing that matters, that at my current burn, I'll be in trouble at the end of the month. False positives should mostly just happen at the beginning of the month I think when the interval is sorter, and those can be suppressed by wrapping the query with "<query> and (day_of_month() > 3)" say, so that really early dates don't alert?

It really feels like you are indirectly saying this use case is not important to Prometheus. Am I tilting at a windmill here? Should I find some other alerting system for my needs?

**Comment by roidelapluie** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by kfox1111** [comment]
I did look there first. This seems to be the same issue:
https://groups.google.com/forum/#!topic/prometheus-users/wuv18Jl6TFM
And stuck at the same point. Needing to hard code things.

Should I respond to that thread, or open a new one? Thanks!

**Comment by brian-brazil** [comment]
We looked at this as part of the bug scrub, and this is out of scope.

**Comment by kfox1111** [comment]
I'm ok with not doing math, but having a solution for ranging over some interval that is based on calendar is an important use case I believe and I have not seen a good solution to it yet. Should I open a separate issue for it?

**Comment by brian-brazil** [comment]
That's probably more something to ask Grafana for. Prometheus is about math over arbitrary length time periods, not time periods whose definition changes over time.

**Comment by kfox1111** [comment]
I want to do it with Alerts. Its not a Grafana specific thing.
