### ISSUE TITLE
Unable to scrape HTTP/2-only endpoint

### ISSUE THREAD

**Issue by Daniel15** [prometheus/prometheus#7237]
**What did you do?**
Added an endpoint to my Prometheus config that only responds via HTTP/2. It's a gRPC service that I've also added a `/metrics` HTTP endpoint to, and gRPC services only speak HTTP/2 by default.

**What did you expect to see?**
Data is properly scraped.

**What did you see instead? Under which circumstances?**
Prometheus UI says:
```
Get https://xxxxxxx/metrics: EOF
```

Server says:
```
fail: Microsoft.AspNetCore.Server.Kestrel[0]
HTTP/2 over TLS was not negotiated on an HTTP/2-only endpoint.
```

**Environment**

* System information:

```
Debian "testing"
Linux 5.5.0-2-cloud-amd64 x86_64
```

* Prometheus version:

```
prometheus, version 2.15.2+ds (branch: debian/sid, revision: 2.15.2+ds-2)
  build user:       pkg-go-maintainers@lists.alioth.debian.org
  build date:       20200113-10:10:54
  go version:       go1.13.6
```

**Comment by roidelapluie** [comment]
See https://github.com/prometheus/common/pull/233

**Comment by Mario-Hofstaetter** [comment]
Has this been resolved yet?
I am getting the very same error using Prometheus `2.23.0` and ASP.NET Core Kestrel GRPC Service.

Prometheus UI: `Get "https://host.docker.internal:5011/metrics?format=prometheus": EOF`
Kestrel: `[2020-12-03 23:04:58Z ERR] Microsoft.AspNetCore.Server.Kestrel HTTP/2 over TLS was not negotiated on an HTTP/2-only endpoint.`

ARGH, I guess it's because of this: https://github.com/prometheus/common/pull/261

**Comment by roidelapluie** [comment]
More like https://github.com/prometheus/prometheus/issues/7588 and https://github.com/prometheus/prometheus/issues/8143

**Comment by Daniel15** [comment]
@Mario-Hofstaetter I don't think it's fully fixed yet. For now you'll have to enable HTTP/1.x in your service too, for example by adding this in `appsettings.json`:

```
  "Kestrel": {
    "EndpointDefaults": {
      // Temporarily enabling HTTP/1 due to https://github.com/prometheus/prometheus/issues/7237
      "Protocols": "Http1AndHttp2"
    }
  }
```

This is what I did in my service (https://github.com/Daniel15/dnstools/blob/master/src/DnsTools.Worker/appsettings.json#L9-L14) to allow Prometheus to connect.

**Comment by roidelapluie** [comment]
We are looking to see if the Golang HTTP/2 issues are fixed or not, any help is welcome.

**Comment by valdemarpavesi** [comment]
> We are looking to see if the Golang HTTP/2 issues are fixed or not, any help is welcome.

there is an update here:
https://github.com/prometheus/prometheus/issues/5938
