### ISSUE TITLE
React UI: `Use Local time` option on Alerts page

### ISSUE THREAD

**Issue by vosdev** [prometheus/prometheus#7238]
## Proposal
**Use case. Why is this important?**

`/new/graph` has a `Use local time` option.  `/new/alerts` does not (times are displayed in UTC).

It is very confusing to have dates/times displayed in different timezones on the same interface.

*“Nice to have” is not a good use case. :)*

**Comment by brian-brazil** [comment]
We looked at this as part of the bug scrub and this was decided against in #500.
