### ISSUE TITLE
react UI: clicking the same tab button you are on resets most recently queried data

### ISSUE THREAD

**Issue by GiedriusS** [prometheus/prometheus#7241]
**What did you do?**

Execute a simple query such as `process_virtual_memory_max_bytes` via the new react UI. Click on the same tab button that you are on at the moment.

**What did you expect to see?**

I expected the UI to remain the same and for the results to still be there.

**What did you see instead? Under which circumstances?**

I saw that the data had been wiped and the UI shows: "No data queried yet". Not reproducible with the old UI.

**Environment**

* System information:

	Linux 5.4.0-29-lowlatency x86_64

* Prometheus version:

	prometheus, version 2.18.1 (branch: master, revision: 5fa12ae0ef0ae23e146f02b9cbca209ab3af6188)
	build user:       gstatkevicius@gstatkevicius-desktop
	build date:       20200511-15:53:46
	go version:       go1.14.2

* Alertmanager version:

N/A

* Prometheus configuration file:

```
./documentation/examples/prometheus.yml
```

* Alertmanager configuration file:

N/A

* Logs:

N/A

**Comment by juliusv** [comment]
Thanks for reporting this, I'm taking a look!

**Comment by juliusv** [comment]
Fix in https://github.com/prometheus/prometheus/pull/7243
