### ISSUE TITLE
Potential bugs on old cores: using 64-bit functions sync/atomic

### ISSUE THREAD

**Issue by BurtonQin** [prometheus/prometheus#7248]
**What did you do?**

I noticed that there are usages of atomic.LoadInt64, atomic.AddInt64, etc.
These 64-bit functions in sync/atomic can cause errors on old cores. Please see: https://golang.org/pkg/sync/atomic/#pkg-note-BUG
I am not sure if some users are running prometheus on these old cores.

I reported this bug because I saw grpc-go developers viewed the usage of atomic64 functions as a bug and they easily fixed it in this [pull](https://github.com/grpc/grpc-go/pull/1411).
Maybe it is not a problem for prometheus if users rarely use [those old cores](https://golang.org/pkg/sync/atomic/#pkg-note-BUG) mentioned by golang. Feel free to close this issue if you want.

Usage Position: (There may be more)
https://github.com/prometheus/prometheus/blob/5fa12ae0ef0ae23e146f02b9cbca209ab3af6188/storage/remote/intern.go#L92
https://github.com/prometheus/prometheus/blob/5fa12ae0ef0ae23e146f02b9cbca209ab3af6188/storage/remote/intern.go#L99

**What did you expect to see?**

--

**What did you see instead? Under which circumstances?**

--

**Environment**

* System information:

--

* Prometheus version:

master branch,
commit: 5fa12ae0ef0ae23e146f02b9cbca209ab3af6188

* Alertmanager version:

--

* Prometheus configuration file:

--

* Alertmanager configuration file:

--

* Logs:

--

**Comment by brian-brazil** [comment]
Can you explain exactly what the bug is here? I don't think a lack of support for a 20 year old CPU which couldn't sanely run Prometheus for other reasons is a bug.

**Comment by BurtonQin** [comment]
Thanks for your reply. I will close this issue.
