### ISSUE TITLE
Cache Symbols.Lookup() and Symbols.ReverseLookup() when compacting blocks

### ISSUE THREAD

**Issue by pracucci** [prometheus/prometheus#7261]
## Proposal

We're profiling the `LeveledCompactor` while vertically compacting 60 blocks for a total of about 30M series 3x duplicated (due to some replication we have), so the input series are about 90M and the compacted block contains about 30M series.

The process is CPU bound and we're seeing that about 20-30% of CPU time is spent by `Symbols.Lookup()` and `Symbols.ReverseLookup()` summed up together. In this scenario, we would be glad to consume more memory to speed up compaction so I was thinking if you've ever thought about an (optional and configurable) in-memory LRU cache in front of `Lookup()` and `ReverseLookup()`.

![Screen Shot 2020-05-15 at 11 21 01](https://user-images.githubusercontent.com/1701904/82034319-53042080-969e-11ea-84b6-b054e7d6f0e3.png)

**Comment by brian-brazil** [comment]
We already have a cache for the labelnames as that's half the lookups, but beyond that caching label values would get us back to the situation where you basically needed to load the entire index into memory. This decision was purposefully made, and 30% increased compaction duration was seen as quite a good tradeoff for ~constant memory compactions.

In general Prometheus users are memory bound not CPU bound, and this doesn't cause any issues in practice as there's still plenty of time to do compactions.

**Comment by codesome** [comment]
We could limit the size of the cache and compaction will still be constant memory. With mmapping chunks, we might have a little more headroom to add a small cache if it gives a descent reduction in CPU.

**Comment by brian-brazil** [comment]
Would it save us anything though, or just end up trashing the cache and using more CPU? Keep in mind that the compaction code is using the same codepaths as normal queries do, and making general queries less predictable in their runtime doesn't sound like a win.

**Comment by pracucci** [comment]
In the case of Cortex and Thanos, we run the compactor as a separated component and we're experiencing (for large tenants) the compaction of overlapping 2h blocks taking more than 2h.

@brian-brazil How would you feel about an optional config to cache symbols (disabled for Prometheus) so that TSDB embedded can turn it on whenever it may sense for their use case?

**Comment by brian-brazil** [comment]
I'm against code that never runs inside Prometheus, previous such code added for Thanos/Cortex did not end well. If this makes sense it should make sense for Prometheus too.

**Comment by bwplotka** [comment]
> previous such code added for Thanos/Cortex did not end well. 

What exactly did not end well?

Any other alternative we can do to make it faster / add concurrency?

**Comment by brian-brazil** [comment]
I've had a look through the code, and the only place that a cache might realistically help is https://github.com/prometheus/prometheus/blob/4658ce60d1f21529a7ffe35ab0a30baeefbe1a04/tsdb/index/index.go#L431-L444 as series are interested sorted and thus there'll tend to be a lot of symbols shared from one series to the next. A small cache there could be of use, just remembering the symbols from the previous added series would be enough.

Everywhere else we're basically iterating over all symbols, so a cache would get ~0 hits and only slow things down.

**Comment by pracucci** [comment]
Thanks @brian-brazil for taking a deep look into it. I'm going to close this issue for the time being.

**Comment by brian-brazil** [comment]
I'm not sure why you're closing it, this is an optimisation that we should do. Based on your profile it'd knock maybe 15% off the runtime.

**Comment by bwplotka** [comment]
:+1: Awesome, let's do it.

Help wanted! :hugs:

**Comment by brian-brazil** [comment]
Also in terms of avoiding generating garbage, using swapping between two maps wouldn't be the best of ideas. I was thinking the cache would be in the form of a single slice with the symbols/ids in the same order they're in the series labels, as labelnames are always sorted.

**Comment by csmarchbanks** [comment]
Fixed in #8192
