### ISSUE TITLE
Avoid partial aggregation on restart

### ISSUE THREAD

**Issue by camathieu** [prometheus/prometheus#7265]
Hello,

When a Prometheus instance starts it can begin to evaluate recording rules before all targets have been scraped at least once, leading to artifacts in the graphs and triggering of some alerts.

Would it be possible to delay the first evaluation from a configurable amount of time (one scrape interval) to avoid that issue ?

We would be happy to provide the PR if you would accept it.

Example with a single recording rule :
```
record: dc:up:sum
expr: sum(up)
```
![aggregation](https://user-images.githubusercontent.com/6413246/82188244-e2ebd980-98ed-11ea-8990-de97a85c945e.png)

**Comment by brian-brazil** [comment]
Technically you need 2 scrape intervals, so rate has enough to work off. Not something to hard depend on, but may make sense.

**Comment by Harkishen-Singh** [comment]
@brian-brazil, I think a `bug` tag will be appropriate as well.

**Comment by brian-brazil** [comment]
I don't see any bug here, it's working as designed.

**Comment by roidelapluie** [comment]
I don't know if there is anything to do here. Targets are discovered all the time by prometheus, not only at startup.

**Comment by RichiH** [comment]
The question is if the design is good and if we should change it. More thoughts here would be good.

**Comment by roidelapluie** [comment]
We can't wait for all the targets to be scraped because prometheus does not cache the targets. It means that after starting, we have no targets because we need service discoveries to run..

Now if a service discovery hangs, it looks like it could then block recording rules.

**Comment by brian-brazil** [comment]
The idea would be to wait a certain time, not on actual SD behaviour or anything else.
