### ISSUE TITLE
PrometheusNotIngestingSamples is firing "falsely"

### ISSUE THREAD

**Issue by lilic** [prometheus/prometheus#7293]
**What did you do?**
Deploy the mixin [alerts](https://github.com/prometheus/prometheus/blob/94f577580d1786d90cd7ef167a4e6269dd99655e/documentation/prometheus-mixin/alerts.libsonnet) into a cluster.

**What did you expect to see?**
No alerts firing.

**What did you see instead? Under which circumstances?**
[PrometheusNotIngestingSamples](https://github.com/prometheus/prometheus/blob/94f577580d1786d90cd7ef167a4e6269dd99655e/documentation/prometheus-mixin/alerts.libsonnet#L128) alert firing because no scrape target has been discovered. (for example this can happen in a CI environment where for short periods of time nothing is ingested)

** Possible solution: **
Use `scrape_series_added`, but it's not the right metric in my humble opinion. We should have a metric like `scrape_targets` (could not find it, maybe it exists but I just missed it?) to be able to correlate on that, to get the correct result - which would be that Prometheus is not ingesting samples when it should be.

**Comment by simonpasquier** [comment]
Probably `rate(prometheus_tsdb_head_samples_appended_total{%(prometheusSelector)s}[5m]) <= 0 and on() count(up) > 0`

**Comment by lilic** [comment]
> Probably rate(prometheus_tsdb_head_samples_appended_total{%(prometheusSelector)s}[5m]) <= 0 and on() count(up) > 0

The problem is this does not work with metamonitoring.

**Comment by paulfantom** [comment]
prometheus should at least scrape itself, which would stop `PrometheusNotIngestingSamples` from firing.

**Comment by lilic** [comment]
@paulfantom as we discussed out of band, this is not always the case, for example if you have another instance of prometheus scraping this instance.

**Comment by simonpasquier** [comment]
After thinking more about this, I wouldn't say that the alert is buggy since it detects correctly that Prometheus isn't ingesting any samples. As a counter-measure, you can have a dummy recording rule creating a single time series. It would also validate that Prometheus can write samples to its TSDB.

**Comment by beorn7** [comment]
@simonpasquier 's idea looks good to me at first glance. I guess that could be worked into a PR.
