### ISSUE TITLE
Classic UI sometimes runs queries for instant query when in range mode

### ISSUE THREAD

**Issue by gouthamve** [prometheus/prometheus#7296]
See: https://www.youtube.com/watch?v=rjikDb0WzGM

Whats happening at the end:

If you notice carefully, it ran an instant query instead of a range-query and hence didn't update the graph. 

This doesn't happen in the react UI. Low priority bug imo.

**Comment by TAYTS** [comment]
Hi may I try on this issue?

**Comment by beorn7** [comment]
@TAYTS feel free to do so, but also note that this is in the old UI, which will be removed in the not too far future.

I'll also tag this with Hacktoberfest, just in case.
