### ISSUE TITLE
M-mapping of Head chunks taking lots of disk space on first start

### ISSUE THREAD

**Issue by codesome** [prometheus/prometheus#7305]
**What did you do?**

Ran the TSDB as part of Cortex which includes the [mmap of head chunks](https://github.com/prometheus/prometheus/pull/6679). 

**What did you expect to see?**

After/during the replay of WAL, TSDB creating the m-map chunks from the WAL where the chunks' size would be ideally less than the WAL size.

**What did you see instead? Under which circumstances?**

During replay, m-mapped chunks take a lot of space and crash after spitting "disk out of space" error. The m-mapped chunks had crossed 10x the size of WAL when it crashed. 

* Prometheus version:

Prometheus at https://github.com/prometheus/prometheus/commit/f4dd45609a05

**Comment by codesome** [comment]
I am investigating this right now, but any inputs would help too

**Comment by brian-brazil** [comment]
We've also seen a big increase in how much disk space the unittests take, as in over 10G.

**Comment by codesome** [comment]
Oh yes, nice pointer, now I know where to dig from.

**Comment by codesome** [comment]
I can see the reason why unit tests would occupy so much disk: The mmap files are allocated 512MB when they are created. So, multiple tests running in parallel can quickly take up multiple of 0.5GB files. That can potentially explain it and for tests we can try and reduce it. Still investigating the issue from the description if replay cuts a lot of files unnecessarily.

**Comment by roidelapluie** [comment]
#7284

**Comment by manutenfruits** [comment]
Does anyone know what version introduced this bug? Some people are affected and it'll be helpful to know what version to downgrade to until it's fixed.

**Comment by roidelapluie** [comment]
On 28 May 06:23, Manuel Díez wrote:
> Does anyone know what version introduced this bug? Some people are affected and it'll be helpful to know what version to downgrade to until it's fixed.
> 

It has not been released. It is only on master.

> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/prometheus/prometheus/issues/7305#issuecomment-635347226

-- 
 (o-    Julien Pivotto
 //\    Open-Source Consultant
 V_/_   Inuits - https://www.inuits.eu

**Comment by codesome** [comment]
Closed by https://github.com/prometheus/prometheus/pull/7306
