### ISSUE TITLE
Parse config before loading WAL

### ISSUE THREAD

**Issue by 0xVox** [prometheus/prometheus#7322]
## Proposal

Parse config file before loading WAL. 

Just spent a while wonderign why my prometheus pod wouldn't load - I thought perhaps it was taking too long to load the WAL, and eventually tailed the log while it went through and did just that. 

Of course, in kubernetes, these logs aren't viewable as soon as the container restarts, and it was only then that I realised that I had an extra tab in my YAML that was causing a read error - it would have been fairly obvious if it checked this before loading the WAL.

**Comment by Harkishen-Singh** [comment]
Is it a yaml syntax error or some key value. Could you provide more details, like the yaml file with the tab space?

**Comment by codesome** [comment]
A dry check of config sounds good before we start anything. Currently the config is parsed in parallel with WAL replay.

**Comment by Harkishen-Singh** [comment]
Working on this.
