### ISSUE TITLE
Couldn't load configuration (-config.file=documentation/examples/prometheus.conf

### ISSUE THREAD

**Issue by tdingus** [prometheus/prometheus#733]
uname -a
Linux new-host-2.home 3.14.17-100.fc19.x86_64 #1 SMP Thu Aug 14 17:17:26 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

steps to reproduce:

a. git clone https://github.com/prometheus/prometheus.git
b. cd prometheus
c. make build
d. ./prometheus -config.file=documentation/examples/prometheus.conf

WARN[0000] No remote storage URLs provided; not sending any samples to long-term storage  file=main.go line=126
INFO[0000] Loading configuration file documentation/examples/prometheus.conf  file=main.go line=220
ERRO[0000] Couldn't load configuration (-config.file=documentation/examples/prometheus.conf): open documentation/examples/prometheus.conf: no such file or directory  file=main.go line=224

**Comment by fabxc** [comment]
You are building from master, which contains the 0.14.0 release candidate.
See the [RC announcement](https://groups.google.com/forum/#!topic/prometheus-developers/4QXkc2NvFJ0). The switch to the YAML config format is what causes the error.

You can either try out the release candidate ([configuration docs](https://github.com/prometheus/docs/blob/master/content/docs/operating/configuration.md), [getting started docs](https://github.com/prometheus/docs/blob/master/content/docs/introduction/getting_started.md)) or build from the `0.13.4` tag for which the contents of [prometheus.io](http://prometheus.io) are valid.

**Comment by fabxc** [comment]
That said, we have to update our getting started documentation to instruct building from the latest stable release (which should have a moving tag). Sorry about the confusion.

**Comment by fabxc** [comment]
I assume this explains/resolves the issue. Otherwise feel free to comment again.

**Comment by tdingus** [comment]
yes. thanks.
