### ISSUE TITLE
Multiple alerts getting fired because alert rule expression value not getting changed to expected value after evaluation_interval

### ISSUE THREAD

**Issue by aartinagdev** [prometheus/prometheus#7336]
**What did you do?**

I have tried to implement Scaling with Prometheus Alerts by configuring a webhook receiver in AlertManager to execute my ScaleUp and ScaleDown action.
 Prometheus, AlertManager, Webhook are deployed as Kubernetes Pods.

Prometheus Configuration :
evaluation_interval: 1m
scrape_interval: 1s

Metrics Used ( these values are exposed using custom-exporter ) :
current_replica is a metric that gives instantaneous value of number of PODS running.
min_replica and max_replica are the metrics that have been set to avoid scaling replicas down and up respectively beyond that count.

Alert Rules :
1. ScaleUp:
	expr: (tps > bool 5 + current_replicas < bool max_replicas) == 2
2. ScaleDown:
	 expr: (tps < bool 5 + current_replicas > bool min_replicas) == 2

Alert Manager Configuration :
1. Grouping is disabled in AM.
2. repeat_interval: 3m

Test Case demonstration of ScaleDown action :
min_replica = 2
max_replica = 4
There is no load on the applications in the POD ( tps = 0 )
	Step 1. When 2 Pods running, scaledown rule is evaluated to false and no alerts are fired 
		current_replica = 2
		min_replica =2
	Step 2. Now I bring up one more replica 
		current_replica to 3
		Scaledown action gets evaluated to true
			because tps < 5 and current_replica > min_replica
		Alert goes into "Firing" state and it brings down one replica. 
		Here alert stays into "Firing" state for that evaluation cycle 
	Step 3. After 1m ( at the end of evaluation cycle ): 
		scaledown action still gets evaluated to true even though current_replica is 2 now, 
		hence one more replica is brought down,
		alert state changes from "Firing" to "Inactive" 

I don't understand why alert rule gets evaluated to true in Step 3, when the current number of running replicas is 2.
To confirm, after ScaleDown in Step 2, I even queried alert rule expression in Prometheus dashboard, value is not evaluated to 2, hence the expression must return false.

**What did you expect to see?**

Alert rule must have fired ScaleDown action only once after successful evaluation in Step 2.
In Step 3, alert rule must have evaluated False and prevented ScaleDown action.

**What did you see instead? Under which circumstances?**

Alert rule got evaluated to true twice and fired (not expected ) ScaleDown alert in Step 3, which resulted in dropping of replicas beyond min_replica.

**Environment**

* System information:

Linux 4.1.12-124.32.3.el7uek.x86_64 x86_64

* Prometheus version:

	image: prom/prometheus:v2.16.0

* Alertmanager version:

    image: image: prom/alertmanager

* Logs:
Webhook Logs:
Below are the webhook logs where I have extracted the Rule Evaluation Value of every cycle ( accessed from "annotations" under rules ) in which it is alerted for ScaleDown Action, you can see that metric value is 2 for both cycles.

Webhook Logs :
ScaleDown Action Metric Value is 2
[webhook] 2020/06/04 06:47:26 finished handling scaledown

 ScaleDown Action Metric Value is 2
[webhook] 2020/06/04 06:48:26 finished handling scaledown

**Comment by brian-brazil** [comment]
This sounds like a usage question, we need more timing and timestamp information to indicate if there's any actual bug here.

**Comment by aartinagdev** [comment]
I have got prometheus query.log and webhook logs ( wherein i have expression metric value of the instance when alert was fired )  with me with timestamps. I have increased replicas from 1 to 3 between two evaluation cycles : 10:20:25 - 10:21:24 
Let me know about any additional information needed.
[query.log](https://github.com/prometheus/prometheus/files/4729382/query.log)
[webhook.log](https://github.com/prometheus/prometheus/files/4729383/webhook.log)

**Comment by brian-brazil** [comment]
That's too many levels of indirection to sanely debug. If you think there's a bug in alerting rules (which is very unlikely) we need to know about when exactly the input came in, with what values and with what timestamps.

**Comment by aartinagdev** [comment]
Turns out AlertManager was invoking webhook (number of expected times + 1) because send_resolved flag is set to true by default for webhook receiver in AlertManager and there was no handling at webhook for checking alert status. Changed it to false. Working as expected.
