### ISSUE TITLE
v2 snapshots folder location

### ISSUE THREAD

**Issue by skristallidis** [prometheus/prometheus#7339]
It would be very helpful to be able to modify the output of POST /api/v1/admin/tsdb/snapshot?skip_head=<bool> to a custom location and not the <data-dir>. Using a flag maybe?

The reason for this feature suggestion is that somebody needs 2x bigger disk in order to keep a full snapshot. By providing a configurable location for the snapshot the users will be able to keep snapshots to a network share in order to reduce required Disk size.

**Comment by brian-brazil** [comment]
We use hardlinks for snapshots, so they do not need 2x the disk. If you want it on another filesystem, you could snapshot and then move it to the same effect.

**Comment by brian-brazil** [comment]
We looked at this old issue as part of the bug scrub, and don't currently see a need for this to be configurable as it'd likely cause confusion given the need for it to be on the same filesystem.
