### ISSUE TITLE
Alerts HTML

### ISSUE THREAD

**Issue by a86c6f7964** [prometheus/prometheus#735]
templates/alerts.html looks to be missing the path prefix. The links on the alerts to the graph page do not have the path prefix

**Comment by juliusv** [comment]
@a86c6f7964 Thanks yet again!

@quinox wanna give this a shot? Otherwise I can handle it.

**Comment by quinox** [comment]
In this case I'll let you handle it

**Comment by juliusv** [comment]
@a86c6f7964 Could you clarify where exactly a path prefix is missing? If I configure an alert and head to `/pathprefix/alerts`, all the links on there (like alerting expressions linking to their graph version) have the right path prefix.

Which version are you using? And if you're building from source, try doing `make clean && make` one more time.

**Comment by a86c6f7964** [comment]
```
branch	stable
date	20150522-15:12:08
go_version	1.4.2
revision	43b41c5
user	root
version	0.13.3
```

Ah... I missed 3e914a8cb1054a499a282201f3da1770211c70cf looks like once I move to .14 then it will be good. Sorry about that. I could have sworn I tried to see if things were fixed in master.

**Comment by juliusv** [comment]
@a86c6f7964 Ah cool, thanks for confirming!
