### ISSUE TITLE
flaky k8s circle test failure in  TestEndpointsDiscoveryNamespaces

### ISSUE THREAD

**Issue by roidelapluie** [prometheus/prometheus#7353]
https://app.circleci.com/pipelines/github/prometheus/prometheus/7349/workflows/b1fc2685-bfeb-44c8-a79b-e8e6ae40befe/jobs/32417/steps

@brancz Can you have a look at this? Might be related to recent k8s dependency update.

@codesome this might require a fix in release-2.19.

thanks

**Comment by roidelapluie** [comment]
I can reproduce locally.

It happens 2 times out of 1000
```
go test -run TestEndpointsDiscoveryNamespaces -count 1000 -test.v
```

**Comment by codesome** [comment]
Noted

**Comment by roidelapluie** [comment]
The test failure is already present in 2.18. No need to block the release on it.

**Comment by brancz** [comment]
Putting on my todo list. If anyone wants to grab this though feel free. :)

**Comment by brancz** [comment]
Looking into this .. haven't really found anything yet, just a first observation: failure seem to fail significantly faster (consistently ~10x).

**Comment by brancz** [comment]
It seems that the source is our early break of reading from the target groups channel. We seem to be getting the same result twice, which ultimately is a no-op, but breaks before we accept the actual "max" number of target groups.
