### ISSUE TITLE
Scrape to RAM, sync to disk option

### ISSUE THREAD

**Issue by mihaigalos** [prometheus/prometheus#7355]
## Version infos
Hardware: `Raspberry Pi Model 3`
Host OS: `Ubuntu 18.04.3 LTS (Bionic Beaver)`
Prometheus:  `2.17.1`

## Context
I am using a Raspi to run Prometheus and monitor another Raspi running Node Exporter. This question pertains to the 1st, running Prometheus.

## Proposal

In order to preserve microsd life, I would like to be able to tell Prometheus to scrape its metrics to RAM and only sync to disk every hour or day. This would prevent needless writes to the microSD, which damage it over time.

**Comment by roidelapluie** [comment]
It should work with a tmpfs filesystem.

**Comment by mihaigalos** [comment]
As a temporary workaround, I created a ramdisk and linked moved the `data` folder to it. A cronjob then syncs it back to disk every night.

```bash
# set up ramdisk
sudo mkdir -p /mnt/prometheus_logs
sudo chown $USER:$USER /mnt/prometheus_logs
sudo mount -t tmpfs -o size=100M tmpfs /mnt/prometheus_logs

# copy logs to ramdisk
sudo systemctl stop prometheus
cp -r data /mnt/prometheus_logs
rm -r data
ln -s /mnt/prometheus_logs/data .

sudo systemctl restart prometheus

# sync to disk every night at 04:00
(crontab -l ; echo "0 4 * * * mkdir -p $HOME/prometheus_logs && cp -r /mnt/prometheus_logs/data  $HOME/prometheus_logs") | crontab -

# make it permanent after reboot
grep /mnt/prometheus_logs /etc/mtab | sudo tee -a /etc/fstab
```

**Comment by roidelapluie** [comment]
Hello, thanks for your report.

At first sight and in my opinion that is a non-goal for this project. You could use Tempfs, take snapshots and sync them to disk when you need.

**Comment by brian-brazil** [comment]
We looked at this as part of the bug scrub, ramdisks seem sufficient for this rare use case.
