### ISSUE TITLE
Merger adapter causes invalid query results due to slice reuse

### ISSUE THREAD

**Issue by pracucci** [prometheus/prometheus#7359]
**What did you do?**

I'm investigating an issue in Cortex blocks storage (running Prometheus `master`) and I ended up realising that the issue is caused by `seriesMergerAdapter`'s buffer.

The problem is that `seriesMergerAdapter` reuse the same slice to cast the `Series` and then this slice is passed to `ChainedSeriesMerge` which retains the slice, so subsequent calls to `seriesMergerAdapter.Merge()` will overwrite the (unintentionally) shared slice:
https://github.com/prometheus/prometheus/blob/e5ffa8c9a08a5ee4185271c8c26051ddc1388b7a/storage/generic.go#L114-L120

_I'm still checking the impact on Prometheus, but I preferred to open the issue earlier to raise a flag._

**Comment by roidelapluie** [comment]
Can it explain #7292?

**Comment by bwplotka** [comment]
ack I am touching this part this week, so happy to investigate this.

**Comment by roidelapluie** [comment]
And https://github.com/prometheus/prometheus/issues/7349

**Comment by pracucci** [comment]
> Can it explain #7292?
> And #7349

Yes, they do.

> ack I am touching this part this week, so happy to investigate this.

I'm working on a fix right now.

**Comment by roidelapluie** [comment]
Can you fix against the release-2.19 branch?

**Comment by csmarchbanks** [comment]
Closing as #7361 has been merged.
