### ISSUE TITLE
How to run script as su  oracle -c "Script Name" in prometheus

### ISSUE THREAD

**Issue by ankurnigam** [prometheus/prometheus#7363]
As we know all command in Prometheus runs as root/nobody user. I want to run the script as oracle.

Do we know if there is any way to do this using config .yml file or any other way.

**Comment by hoffie** [comment]
> As we know all command in Prometheus runs as root/nobody user.

I don't think this is the case. Prometheus runs as the user you start it as (as any tool/daemon without explicit user switching capabilities). If it runs as root/nobody in your case, you should check the way you start Prometheus (e.g. some systemd unit, an init script, etc.).
Also, Prometheus does not invoke any other processes as far as I know.

> I want to run the script as oracle.

I would suggest running Prometheus as its own, unprivileged user. There is no need to give it any higher (root) or specific (oracle) permissions.

If you have further questions, I suggest using one of the mentioned [Community resources](https://prometheus.io/community/) as Github issues are used for bug/feature tracking purposes and not for generic usage questions. :)

**Comment by ankurnigam** [comment]
But some script need to be run as  root and some need to be run as oracle.

**Comment by hoffie** [comment]
I suggest posting to the [users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) with some more details about what scripts you are talking. Maybe you are using something in addition to Prometheus (i.e. some script execution webhook?). Such details will be needed in order to help you.

**Comment by brian-brazil** [comment]
As @hoffie says, this is a question for the users mailing list.
