### ISSUE TITLE
FileSD: Support URLs

### ISSUE THREAD

**Issue by Daniel-WWU-IT** [prometheus/prometheus#7371]
## Proposal
The file-based service discovery should support not only reading scrape configs from the local file system but also from a URL.

**Use case:**
Our Prometheus is running in Kubernetes, so its configuration is rather static. However, what is not static are the scrape targets, these can change dynamically. One solution (which we currently are using) is to read these targets using a File SD and a shared mounted volume. This works but is far from ideal.

If the File SD offered reading scrape configs from a URL and could be configured to periodically pull the config (since file watches won't work, of course), we could instead offer the configs on an HTTP endpoint and wouldn't need to use local files at all.

**Notes:**
Yes, there is support for Consul and similar, but these would introduce another unnecessary layer between Prometheus and our own service exporter. Providing scrape configs in the same format as the File SD expects is a simple yet elegant solution which might be interesting for many users.

**Comment by brian-brazil** [comment]
For kubernetes there is already kubernetes_sd_config.

This suggestion has been made several times in the past such as #4390. We already have one generic integration in the form of file_sd, and I'm against providing a 2nd mildly different type of generic integration when a simple cronjob allows converting one to the other.

**Comment by roidelapluie** [comment]
This is being implemented in #8839
