### ISSUE TITLE
Unknown symbol error when compacting Head block

### ISSUE THREAD

**Issue by codesome** [prometheus/prometheus#7373]
**What did you do?**

Ran TSDB inside Cortex

**What did you expect to see?**

No errors when compacting the Head block.

**What did you see instead? Under which circumstances?**

Compaction from Head failing with the following error
```persist head block: 2 errors: write compaction: add series: symbol entry for \"2020-06-08T07:02:36.407Z\" does not exist, unknown symbol \"2020-06-08T07:02:36.407Z\"; series not 16-byte aligned at 147394303```

And the same error repeats.

This error is not related to any disk corruption as all the data is from the memory. 

The main components involved in this compaction operations are the Head index reader and the Head block itself. It needs some investigations on how is it possible - whether some bug in the compaction code (or) some race somewhere when ingesting data which causes the symbols to be lost (or) something else.

Though this is seen inside Cortex when using TSDB, it might be very much possible while running Prometheus too.

---
Prometheus version: `v2.16.0`

**Comment by levydori** [comment]
Hey,
we are seeing the same issue on Prometheus (v2.15.2). 

`level=error ts=2020-06-17T19:04:17.039Z caller=db.go:609 component=tsdb msg="compaction failed" err="persist head block: 2 errors: write compaction: add series: symbol entry for \"bbbe9aa8-254f-44f6-b5a0-09c0ea64fd9f\" does not exist, unknown symbol \"bbbe9aa8-254f-44f6-b5a0-09c0ea64fd9f\"; series not 16-byte aligned at 22979295"` 

It's causing compaction to fail, and disk usage to slowly increase (until it reaches 100%).

**Comment by brian-brazil** [comment]
I also had a private report of this in Prometheus, not sure which version.

**Comment by bwplotka** [comment]
Hey @codesome  we just got it and we are on exact commit that was suppose to fix it ): 

```
level=error ts=2020-07-11T13:30:09.772232559Z caller=db.go:685 component=receive tenant=XXX msg="compaction failed" err="persist head block: 2 errors: write compaction: add series: symbol entry for \"olm-operator-666b97bf6d-f6mrj\" does not exist, unknown symbol \"olm-operator-666b97bf6d-f6mrj\"; series not 16-byte aligned at 112720367"
level=error ts=2020-07-11T13:31:43.428332983Z caller=db.go:685 component=receive tenant=XXX msg="compaction failed" err="persist head block: 2 errors: write compaction: add series: symbol entry for \"olm-operator-666b97bf6d-f6mrj\" does not exist, unknown symbol \"olm-operator-666b97bf6d-f6mrj\"; series not 16-byte aligned at 112723471"
```

**Comment by bwplotka** [comment]
We are exactly on https://github.com/prometheus/prometheus/pull/7526

**Comment by bwplotka** [comment]
This is from Thanos version: `master-2020-07-10-1ae66b96`

Which has clearly this fix commit: https://github.com/thanos-io/thanos/blob/1ae66b96c887485822b1b46ad2d3db2627df77f5/go.mod

**Comment by bwplotka** [comment]
BTW: We did not see this, before TSDB upgrade "with fix" :thinking:

**Comment by codesome** [comment]
We saw it in Cortex too after this PR, looks like the "fix" was not actually a fix but maybe amplifies the problem. Additionally, initial assumption was it's because of a race between adding a series and compaction. But, as the same error repeats (i.e. for the same symbol), it cannot be a race but some other underlying issue. I will take a look at it on Monday, until then maybe we should revert back the "fix".

**Comment by bwplotka** [comment]
Yes, I will revert it.

Also next time please make sure to notify here us about Cortex issue it would save us some time =D 

Enjoy the weekend!

**Comment by codesome** [comment]
> Also next time please make sure to notify here us about Cortex issue it would save us some time =D

We sure would do that, just that we noticed it today after you commented :)

**Comment by bwplotka** [comment]
Haha :heart: https://github.com/prometheus/prometheus/pull/7556

**Comment by bwplotka** [comment]
Looked a little bit, and yea in theory "fix" makes sense. Adding first symbols then postings, in theory, looks good as we are fine with one symbol more, but not fine with posting without its symbol... 

Side bug race I found by accident: https://github.com/prometheus/prometheus/pull/7557
I reproed this bug in current version without reverted "fix" in a hacky way (injected mutexes): https://github.com/prometheus/prometheus/pull/7558

With your fix I tried as well and couldn't as a quick try, so we need to look deeper.

**Comment by bwplotka** [comment]
OK I repro-ed the problem with fix as well: https://github.com/prometheus/prometheus/pull/7559

Actual fix (hopefully): https://github.com/prometheus/prometheus/pull/7560 Please feel free @codesome to commander this PR
