### ISSUE TITLE
The log shows "no space left on device" while the disk is not full 

### ISSUE THREAD

**Issue by codwu** [prometheus/prometheus#7387]
**What did you do?**
My Prometheus keeps printing logs like
```
level=warn ts=2020-06-12T02:18:03.518Z caller=scrape.go:930 component="scrape manager" scrape_pool=lambda/kubelet/1 target=https://10.240.193.83:10250/metrics/cadvisor msg="append failed" err="write to WAL: log samples: write /prometheus/wal/00008836: no space left on device"
level=warn ts=2020-06-12T02:18:03.519Z caller=scrape.go:934 component="scrape manager" scrape_pool=lambda/kubelet/1 target=https://10.240.193.83:10250/metrics/cadvisor msg="append failed" err="write to WAL: log samples: write /prometheus/wal/00008836: no space left on device"
level=warn ts=2020-06-12T02:18:03.519Z caller=scrape.go:945 component="scrape manager" scrape_pool=lambda/kubelet/1 target=https://10.240.193.83:10250/metrics/cadvisor msg="appending scrape report failed" err="write to WAL: log samples: write /prometheus/wal/00008836: no space left on device"
```
**What did you expect to see?**
The disk is full

**What did you see instead? Under which circumstances?**
My disk is not full, only 26% is used. I checked the data directory and could not find the file 00008836. The oldest file is 00108961

**Environment**

* System information:

	Linux 4.18.9-1.el7.elrepo.x86_64 x86_64

* Prometheus version:

	prometheus, version 2.13.0 (branch: HEAD, revision: 6ea4252299f542669aca11860abc2192bdc7bede)
  build user:       root@f30bdad2c3fd
  build date:       20191004-11:25:34
  go version:       go1.13.1

* Alertmanager version:

	insert output of `alertmanager --version` here (if relevant to the issue)

* Prometheus configuration file:
```
insert configuration here
```

* Alertmanager configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```

**Comment by roidelapluie** [comment]
Can you share df -h ?

**Comment by hoffie** [comment]
`df -i` and `lsof` on that file system might also be interesting.

**Comment by codwu** [comment]
I checked the data directory again and found it was 100% used. Close the issue.
