### ISSUE TITLE
Alerts propagating but not visible in prometheus /alerts URL or Alertmanager 

### ISSUE THREAD

**Issue by georgewilliamherbert** [prometheus/prometheus#7392]
Team has been using older (2.6) Prometheus/Alertmanager for some time, which I got involved in about six months ago and upgraded to then-current Prometheus 2.16.0 and Alertmanager 0.20.0

After the upgrade, we started getting reports from one user team that alerts (for example, node down) are created correctly, triggering (on for example a node added to monitoring before it's added in datacenter),  visible if you search on 'up{environment="prod",job="node}==0' in Prometheus graphing, but not visible from the prometheus /alerts URL or in Alertmanager /alerts URL.

We can confirm they flow properly through the system from generation of the alert through to PagerDuty - the alert specified in our rules and routes happens and goes out and pages.  But the admin for these cases quite reasonably wants to be able to silence alerts in Alertmanager and can't because it's not visible in that layer.  Generically, it's disturbing that we randomly can't find some of the alerts in the two intermediate layers.

Have not tried on versions between 2.6 and 2.16; this behavior wasn't there in 2.6.  We're working on a 2.18 upgrade test plan but bandwidth and priorities.  I can't see anything different about those alerts vs ones showing up properly from our rules and routes files.

**What did you do?**

Alert generated for node down.

**What did you expect to see?**

Alert visible in prometheus http://.../graph, prometheus /alerts, Alertmanager /alerts, and sent to PagerDuty

**What did you see instead? Under which circumstances?**

Alert visible in prometheus /graph, sent to PagerDuty, but not visible in prometheus /alerts or Alertmanager /alerts

**Environment**

* System information:

	iLinux 4.4.192-1.el7.elrepo.x86_64 x86_64

* Prometheus version:

prometheus, version 2.16.0 (branch: HEAD, revision: b90be6f32a33c03163d700e1452b54454ddce0ec)
  build user:       root@7ea0ae865f12
  build date:       20200213-23:50:02
  go version:       go1.13.8

* Alertmanager version:

alertmanager, version 0.20.0 (branch: HEAD, revision: f74be0400a6243d10bb53812d6fa408ad71ff32d)
  build user:       root@00c3106655f8
  build date:       20191211-14:13:14
  go version:       go1.13.5

* Prometheus configuration file:
Relevant rules file exerpt.
```
groups:
  - name: node.rules
    rules:

      - alert: NodeDown
        expr: up{job="node",environment="prod"} == 0
        for: 10m
        labels:
          severity: critical
          alert_group: generic_node
        annotations:
          title:       'Node is not responding'
          description: 'The basic node monitoring is not reporting, the node is likely down'
          value:       'Node {{ $labels.instance }} is Down'
          runbook:     troubleshooting/node_down.md
```

* Alertmanager configuration file:
```
insert configuration here (if relevant to the issue)

```

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```

**Comment by brian-brazil** [comment]
> Alert visible in prometheus /graph, sent to PagerDuty, but not visible in prometheus /alerts or Alertmanager /alerts

What do you mean that it's visible in /graph?

**Comment by georgewilliamherbert** [comment]
We can select the NodeDown status in manual search on prometheus http://prom:4100/graph url console, see the node that's down there.

up{environment="prod",job="node"}==0

(list of hosts down, including one we're referring to)

That corresponds to the alert defined for Prometheus (and presumably actually generated because PagerDuty gets it), but if you go to http://prom:4100/alerts it's not showing there.

If you go to http://alertmanager/alerts other alerts are properly shown but not this specific one.  SRE wanted to mute it in Alertmanager but can't because it's not showing as triggered.

PagerDuty gets the alert and acts on it, visible there and logged, confirming that the down node generated an alert, that it passed up the stack.

**Comment by brian-brazil** [comment]
So you didn't see the alert in graphs. Most likely either your targets aren't down for at least 10m, or they're being added and removed by service discovery. Without raw data I can't tell, but this is likely all working as expected.

**Comment by ozloozlo** [comment]
@georgewilliamherbert do you see `ALERTS{alertname="NodeDown"}` metrics in the PromQL browser while alerts are expected to trigger?

**Comment by albttx** [comment]
Hello,

i'm running the same issues:

- Alerts are present in prometheus
```
> ALERTS{}
ALERTS{alertname="HostOutOfDiskSpace70", alertstate="firing", device="/dev/md1", fstype="ext4", host="node-01", instance="localhost:9100", job="node_exporter", mountpoint="/", severity="warning"}
```
- Alert isn't silenced

- Yesterday there was the alerts showing in alertmanager...

![image](https://user-images.githubusercontent.com/8089712/169688064-f2276565-b636-4329-b6e4-a6ce6f8513e4.png)

**Comment by beorn7** [comment]
Hello from the bug scrub.

Since no information was provided in the last 3.5y, we close this.
