### ISSUE TITLE
Configurable minValidTime in the head block

### ISSUE THREAD

**Issue by codesome** [prometheus/prometheus#7396]
## Introduction 

Head block has a concept of `minValidTime` wherein it won't allow samples before 1h to be ingested (Called out of bound samples)

## Proposal

Here I propose making `minValidTime` configurable which is solely for external users of TSDB and does not affect the functioning of Prometheus.

Sometimes we want to ingest some old data because of long outages lasting >1h. In such cases, the `minValidTime` is a blocker. Making it configurable will allow ingesting old data.

Out of order samples are still discarded.

## Changes required

**To configure `minValidTime`**

There are 2 possible ways we could make it configurable.

1. Introduce a method `SetMinValidTime()` which will set it to the value passed. But this one is easy to make mistakes.

2. Pass a config, let's say `MinValidTimeGracePeriod`, which will accept samples up to `MinValidTimeGracePeriod` back in time from the current `minValidTime` that we calculate.

**To the compaction**

Allowing old samples can interfere with head compaction. So the compaction check for Head can be changed 
from `head.maxt - head.mint >= chunkRange * 3/2`
to `if len(blocks) > 0 { head.maxt - lastBlock.maxt >= chunkRange * 3/2 } else { old condition }`

Vertical compaction and vertical queries needs to be enabled to take care of overlapping data.

## Is it safe

Memory: It is proportional to the number of series. With m-mapping in place, taking in lots of old samples is not a problem.

Data: The vertical query and vertical compaction take care of everything. The user must be aware of what they are getting into.

**Comment by bwplotka** [comment]
cc @JessicaGreben

**Comment by brian-brazil** [comment]
Uhm, don't we already have this setting via the min block size?

**Comment by bwplotka** [comment]
Vertical compaction would handle those.

**Comment by codesome** [comment]
> Uhm, don't we already have this setting via the min block size?

The idea is to keep the block size same as before and allow old samples in case needed in certain scenarios.

**Comment by roidelapluie** [comment]
That sounds amazing for #535 too

**Comment by bwplotka** [comment]
Yes, this is an amazing step forward in to backfillable Remote Write :+1:

**Comment by codesome** [comment]
This might not help much for #535 as we need to align the data with existing blocks to avoid large blocks. But backfillable Remote Write, definitely.

While using configurable minValidTime, the compaction planner needs to be a little different else it is possible to create very large blocks with carefully planned samples. Hence I don't see this being exposed to users of Prometheus.

**Comment by roidelapluie** [comment]
And can't we somehow combine both usecases in one solution ? Maybe this proposal can be adapted...

**Comment by roidelapluie** [comment]
Well "backfillable Remote Write" might be the answer to #535

**Comment by bwplotka** [comment]
This PR does not solve all problems of full  https://github.com/prometheus/prometheus/issues/535 - however it's a good first step. I would focus on "short term backfill capabilities" and then we are already planning with @codesome and @pracucci to think about some compaction planner / logic to fix the large blocks problem that has to be solved for https://github.com/prometheus/prometheus/issues/535

Let's focus on this first step only for now I think :hugs:

**Comment by codesome** [comment]
I will open a PR for making `minValidTime` configurable.

**Comment by brian-brazil** [comment]
This doesn't solve #535 at all, it's more a way to do push than one-off backfilling of old data.

How would you preserve the property that Prometheus time series are append-only? Right now the only place we check for that is in the head.

**Comment by codesome** [comment]
> How would you preserve the property that Prometheus time series are append-only?

In the context of Prometheus, that would be done by setting the grace period to 0. But for external users who would set it to >0, it is difficult to assure that efficiently, it will need a lookup into the blocks. This is an issue for series which disappear in between or super long scrape intervals (like, in hours). Otherwise, there would be at least 1 sample of the series in the Head which will make old samples out of order.

**Comment by brian-brazil** [comment]
Also, if data like this is continously being ingested wouldn't it create a pile of tiny chunks due to the continuous head compactions?

If this is just a thing that affects Cortex, it may be better for Cortex to have a 2nd head for the older data.

**Comment by bwplotka** [comment]
This is same for Thanos.

Plus we can compact chunks if needed on compactor.

**Comment by codesome** [comment]
> Also, if data like this is continously being ingested wouldn't it create a pile of tiny chunks due to the continuous head compactions?

Compaction as Bartek said. Maybe we can revive https://github.com/prometheus/prometheus/issues/6332 :)

> If this is just a thing that affects Cortex, it may be better for Cortex to have a 2nd head for the older data.

This idea is also into consideration. But allowing older samples in the existing TSDB instance is a much simpler solution than handling another head. So, that idea has been kept for explicit backfilling for now and this solution mainly aims to take care of some unexpected issues that might arise lasting longer than 1h.

**Comment by brian-brazil** [comment]
Keep in mind that things have been optimised with the assumption that there's at most going to be tens of blocks. Suddenly having thousands probably won't end too well.

**Comment by codesome** [comment]
> Suddenly having hundreds probably won't end too well.

In what case is that possible right now? (except for data spanning a LOT of years)

**Comment by brian-brazil** [comment]
There are 120 minutes in a recent block, compaction is attempted every minute, thus you could have 120 tiny blocks with this change.

**Comment by codesome** [comment]
I have proposed a change in the compaction condition in the issue description which will avoid this :), it is also tested in the unit tests in the linked PR https://github.com/prometheus/prometheus/pull/7398

**Comment by brian-brazil** [comment]
Hmm, I think that logic is right but the level of intricacies this proposal is adding make me uncomfortable. I think you could get the same net effect by increasing the block size in Cortex, without having to change any logic.

**Comment by codesome** [comment]
Increased restart times is the main concern for increasing the block size.

That said, I see only 2 main additions in the logic (1) Allow a bit older samples, which includes just looking back a bit more than minValidTime (2) Look at maxt of the last block instead of mint of the head during compaction if blocks exist. These 2 seem to be simple changes (I might be biased).

**Comment by brian-brazil** [comment]
> Increased restart times is the main concern for increasing the block size.

Isn't that going to happen anyway with this change? Aren't restarts rare anyway?

> That said, I see only 2 main additions in the logic 

Ignoring the unrelated refactoring, it's also touching the WAL loading. More importantly it now requires quite a bit more thought around how compaction works.

**Comment by codesome** [comment]
> Isn't that going to happen anyway with this change?

This change is to allow samples a little older in time in case something goes wrong, and it does not necessarily increase the block size of every new block. In the majority of cases, it is still 2h blocks. So the restarts will remain same except for those cases where we end up ingesting old data.

> Aren't restarts rare anyway?

If you are talking about Cortex/Thanos - it's all during rollouts. So if you do weekly rollouts, then it's not rare, and usually, there are 10s of components using TSDB which would have 100s of TSDBs combined.

> it's also touching the WAL loading

Only for checking the min valid time, yes.

> More importantly it now requires quite a bit more thought around how compaction works.

Yes. This could be documented in the code at relevant places.

**Comment by brian-brazil** [comment]
> In the majority of cases, it is still 2h blocks

You always have to presume a worst case when it comes to provisioning, and I'd presume by default that any feature like this will be abused and/or some system in a failing state will continuously push older data. So in terms of resource usage at least, things would have to be treated the same as though you had increased the block size. Similarly given that worst case, restarts will be as slow as if you had increased the block size.

> Yes. This could be documented in the code at relevant places.

That doesn't really address my point. My point is that these implications were not immediately obvious as they're emergent properties, and compound onto the existing complexity of the system and ultimately increase the likelihood of bugs, undesired interactions, and thus make future changes harder. Documenting the additional complexity that we've found so far doesn't change that there's now more complexity (likely including some we've yet to realise).

**Comment by codesome** [comment]
> You always have to presume a worst case when it comes to provisioning

> Similarly given that worst case, restarts will be as slow as if you had increased the block size.

Provisioning, agree, need to consider the worst case. But we cannot consider only the worst case for the restarts. If it was increasing the block size, then restarts are slower 100% of the time. With this minValidTime extension, the restarts are slower in failure cases where old data is pushed back. If the system (assuming the consumers of this feature to be Cortex and Thanos) provides reliable functioning 99% of the time, then its <1% times for the slow restarts (also, the TSDB need not restart when it's taking the old data, the WAL will get truncated eventually before a restart, so the slower restarts are even less).

A Prometheus cannot abuse this as this is not planned to be configurable in Prometheus binary and will be set to 0. 

> That doesn't really address my point. My point is that these implications were not immediately obvious as they're emergent properties, and compound onto the existing complexity of the system and ultimately increase the likelihood of bugs, undesired interactions, and thus make future changes harder. Documenting the additional complexity that we've found so far doesn't change that there's now more complexity (likely including some we've yet to realise).

I am open to spending more time investigating all implications because increasing block size is not a direct replacement for this for its current use cases.

**Comment by codesome** [comment]
So, here are couple of places where complexity adds up:

1.

The compaction logic needs a small change, which is, when there is at least 1 block on disk, consider the maxt of the last block for the compactable range instead of the head mint, as mint is affected by the grace period. 

This one is a small change and easy to understand.

2.

The main complexity is on the WAL replay side. During ingestion of samples, min valid time is not fixed, rather it is 1h before the maxt of head (hence it's a variable min valid time).

Currently during WAL replay, the min valid time is fixed to the maxt of the last block. But when there is a grace period, it cannot be fixed else it will cause unnecessary samples to be loaded from WAL which is alredy in the block.

Though WAL truncation happens to remove samples from the block, it cannot be 100% assured that all samples from the block are removed from the WAL.

After giving some thought, I realized that even if we are doing dynamic min valid time (with grace period) with the WAL replay, we are anyway going to load samples from WAL which are already in the block - because with the grace period, we have to look back from the maxt of the last block. So, after a restart, the head block is always going to overlap with the last block (unless WAL has got rid of all the samples not in the head).

This needs some more thought on how we want to handle it.

**Comment by codesome** [comment]
So, point 2 above is unavoidable, i.e., possible overlapping blocks after restart even if there was no sample in the grace period. I don't see how it can be tackled without an inefficient lookup in the blocks for many samples (or) modification in the WAL record (out of scope for this). So I think this trade-off is something we have to live with if we want configurable min valid time. @brian-brazil @bwplotka

**Comment by brian-brazil** [comment]
That'd be quite inefficient and relatively complex for something Prometheus itself doesn't need, I'd suggest going with a larger block  size or having a 2nd head inside Cortex.

**Comment by brian-brazil** [comment]
Another thought I just had is that we technically should probably be doing that check on every new series - not just at WAL replay.

**Comment by codesome** [comment]
Could you elaborate a bit?

**Comment by brian-brazil** [comment]
Per above a known issue with this approach would be that it head block can contain samples which overlap with what's in the block, including out-of-order appends. The WAL issue is basically the same issue. I'm suggesting that anything done for one case should also be done for the other. This is all however quite a bit of complexity, as the head would no longer be a standalone block as it'd have to be coupled to the DB to do such checks.

**Comment by codesome** [comment]
> This is all however quite a bit of complexity, as the head would no longer be a standalone block as it'd have to be coupled to the DB to do such checks.

Yes. One of the directions could be to assure WAL never has samples from the blocks while we checkpoint, which means no unnecessary overlap on replay. But that is hard too.

**Comment by brian-brazil** [comment]
Checkpoints only contain series, not samples - and we only read samples from after the last checkpoint anyway. The issue is that whether via scrape or WAL, there's samples overlapping with blocks.

**Comment by codesome** [comment]
Checkpoints can contain samples, but I was conveying something else.

Regarding overlap with blocks, yes, that is expected with current design during appending old samples and also replay. One of the other issues that I was first looking into was - _even if you don't have old samples in Head which overlap with the blocks, you can end up having overlapping samples after restart_, which can be solved if we assure after a Head Truncation no sample from blocks is present in the WAL.

**Comment by brian-brazil** [comment]
Rewriting the entire WAL at each compaction doesn't strike me as something that'd be workable. Even then it wouldn't help. A sample could come in which overlaps with the blocks, Prometheus restarts, and there's an overlapping sample in the WAL which we shouldn't be discarding.

**Comment by codesome** [comment]
Right. No easy way to solve without re-write of many parts of TSDB. I am closing this now as there are hard to solve efficiently issues in this approach.

**Comment by bwplotka** [comment]
Thanks for this discussion. Definitely the replay is not easy. To me, we should maintain separate records for samples overlapping with the potential existing block so we know what to replay. Is this really difficult to implement?

Otherwise, yes we should compare this with starting another head block as proposed initially.

Thanks @codesome for nice investigation!

**Comment by codesome** [comment]
Discussed this offline with @bwplotka. A separate record would be too invasive change and has its own issues. So we plan to design it with having multiple TSDBs which could be simpler to implement.
