### ISSUE TITLE
Migrate legacy tests

### ISSUE THREAD

**Issue by fabxc** [prometheus/prometheus#740]
The direct port of the old tests in `promql/testdata/legacy.test` is relatively messy.
In the long run we'll want to migrate those to smaller scoped tests where testdata and queries have a better fit.

**Comment by minhlongdo** [comment]
Hi, is anyone working on this?
I would like to give it a go.

**Comment by juliusv** [comment]
@minhlongdo You're more than welcome to pick it up!

**Comment by RotBolt** [comment]
This issue seems to be inactive Can I pick it up ?

**Comment by brian-brazil** [comment]
Go ahead.

**Comment by RotBolt** [comment]
> In the long run we'll want to migrate those to smaller scoped tests where testdata and queries have a better fit.

could I get a little hint what criteria to divide tests in smaller scope test?

Like 
```
# Rates should calculate per-second rates.
eval instant at 50m rate(http_requests{group="canary", instance="1", job="app-server"}[50m])
	{group="canary", instance="1", job="app-server"} 0.26666666666666666
```
should I create different test data file for this section `Rates should calculate per-second rates.`

**Comment by brian-brazil** [comment]
> could I get a little hint what criteria to divide tests in smaller scope test?

Look at what's already elsewhere, basically don't have one big load section followed by lots of different unrelated things being tested.

> should I create different test data file for this section

Rate as a function would go in functions.test.

**Comment by RotBolt** [comment]
I am not able to find where `legacy.test` or other testData files are used ? How could I check/run test data files ?

**Comment by RotBolt** [comment]
I have been able to broadly categorize legacy tests in this way

- Rates
- Counter Resets (uses rate)
- Cut offs (uses rates function)
- Round function
- Matrix Tests
- Duplicate Label tests

I think all Rates test (including counter and cut offs) and round should go to `functions.test` 
and Matrix and Duplicate Label should have different files

**Comment by hdost** [comment]
I believe my initial commit starts down the right path. I can continue the rest in a different PR, just want to make sure I get some feedback before going much further

**Comment by hdost** [comment]
Ok decided to just go all the way :man_shrugging: let me know what you think.
