### ISSUE TITLE
`any()` aggregation operator

### ISSUE THREAD

**Issue by alice-sawatzky** [prometheus/prometheus#7400]
## `any()` aggregation operator

It would be useful if we had an aggregation operator that explicitly states "i don't care which value you pick, just pick one". This could have a marginal performance advantage over choosing an arbitrary aggregation, but the real benefit is semantic. when you put, for example, `min()` in a query, the reader assumes that this particular aggregation was chosen for a reason, but in some cases it doesn't matter, like when multiple identical or non-overlapping series are being aggregated. picking an arbitrary aggregation adds meaningless specificity and can make it harder to understand complex queries, while something like `any()` would remove any false meaning from the expression.

**Comment by roidelapluie** [comment]
This seems really niche. If values don't matter, you could use `count` or `0*count`.

**Comment by beorn7** [comment]
I like the semantic dimension here. I remember discussions about recording-rule naming, where the aggregation should be part of the name, but then you might propagate something like `min` even if it has no meaning. Having an explicit aggregator for that would defuse the discussion.

**Comment by roidelapluie** [comment]
I have used count many time for this ; I think it is close enough to the original need, and it reads fine too within promql complex queries.

**Comment by brian-brazil** [comment]
If you want an arbitrary series there's already `topk(1, expr)`. I think anything added here would have to behave like count, but always return the value 1.

**Comment by roidelapluie** [comment]
Thanks @alice-sawatzky . We have added a group() aggregator. We did not name it `any` because we do not return any value from the aggregation, but instead a value of 1.

**Comment by alice-sawatzky** [comment]
Oh, i'm glad my request inspired a feature, although that's not actually what I was looking for!

I was specifically looking for something that _does_ return a value. My intended use case is for situations where there's multiple values being aggregated and they're either non-overlapping temporally or always expected to be the same.

**Comment by roidelapluie** [comment]
Unfortunately so far promql is fully deterministic (except IIRC the order of the values which depends on how storage sends data), and adding a any() function would be somehow break that promise.

**Comment by brian-brazil** [comment]
If you're using the value you should care about how you're calculating it in case they are different. One of min, max, or avg is usually what you want.

**Comment by alice-sawatzky** [comment]
@roidelapluie ah, that's a good point. since the only point of `any()` is semantic, it would be perfectly fine to implement it deterministically. for example it could be an alias for `min()`, or whatever aggregation operator is determined to be cheapest.
