### ISSUE TITLE
histogram_quantile aggregation by more than one label plots incorrectly

### ISSUE THREAD

**Issue by albertyfwu** [prometheus/prometheus#7402]
**What did you do?**
Graph using `histogram_quantile` with `sum` on two labels, i.e.
```histogram_quantile(0.9, sum(rate(grpc_request_duration_seconds_bucket{service="$service"}[$interval])) by (le, grpc_method))```

**What did you expect to see?**
One time series per `grpc_method` label value plotted correctly.

**What did you see instead? Under which circumstances?**
The result of 
```histogram_quantile(0.9, sum(rate(grpc_request_duration_seconds_bucket{service="$service"}[$interval])) by (le, grpc_method))```
was not the same as plotting `histogram_quantile` separately for each value of `grpc_method`:
```histogram_quantile(0.9, sum(rate(grpc_request_duration_seconds_bucket{service="$service",grpc_method="GetGridFile"}[$interval])) by (le, grpc_method))```
and
```histogram_quantile(0.9, sum(rate(grpc_request_duration_seconds_bucket{service="$service",grpc_method="PostAgvState"}[$interval])) by (le, grpc_method))```

![image](https://user-images.githubusercontent.com/1498227/84727765-9a532a80-af44-11ea-9c21-b8e0a5385727.png)

**Environment**

* System information:

	`Linux 4.14.177-139.254.amzn2.x86_64 x86_64`

* Prometheus version:

	`prometheus, version 2.17.2 (branch: HEAD, revision: 18254838fbe25dcc732c950ae05f78ed4db1292c)`

* Alertmanager version:

	insert output of `alertmanager --version` here (if relevant to the issue)

* Prometheus configuration file:
```
insert configuration here
```

* Alertmanager configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```

**Comment by brian-brazil** [comment]
That's weird. Can you  reproduce this for a single timestamp in the Prometheus UI? If so, can you share the source data for that?

**Comment by albertyfwu** [comment]
When I run this in the Prometheus, I can't reproduce this issue for a single timestamp. Does this mean it's a Grafana issue?

Note that I'm in the UTC-7 timezone.

![image](https://user-images.githubusercontent.com/1498227/84841403-1443ec00-aff7-11ea-976b-3d6ec00fbbd5.png)

![image](https://user-images.githubusercontent.com/1498227/84841443-2b82d980-aff7-11ea-877c-d62df3286145.png)

![image](https://user-images.githubusercontent.com/1498227/84841522-64bb4980-aff7-11ea-9e2f-87419cba6556.png)

**Comment by albertyfwu** [comment]
Here's another graph showing how drastically different the plots are:

![image](https://user-images.githubusercontent.com/1498227/84841778-2e31fe80-aff8-11ea-9754-b608552633a7.png)

**Comment by brian-brazil** [comment]
That would seem like a Grafana issue then, though I'm not sure how that could happen.

**Comment by albertyfwu** [comment]
Thanks for looking into this. I filed this bug in the grafana project: https://github.com/grafana/grafana/issues/25643

**Comment by albertyfwu** [comment]
I was using an incorrect setting in Grafana. Sorry for the trouble.
