### ISSUE TITLE
expected equal, got "INVALID"

### ISSUE THREAD

**Issue by iru-dev** [prometheus/prometheus#7403]
Hey.
I got an error, maybe filter it or fix it

curl --header 'Host: "exemple.com' 10.10.10.8

`curl -s http://**********:9927/metrics |  promtool check metrics
  2 error while linting: text format parsing error in line 177: unexpected end of label value ""
`

Build Information
Version	2.15.2
Revision	d9613e5c466c6e9de548c4dae1b9aabf9aaf7c57
Branch	HEAD
BuildUser	root@688433cf4ff7
BuildDate	20200106-14:50:51
GoVersion	go1.13.5

``
177 nginx_vts_server_bytes_total{host=""exemple.com",direction="in"} 76
 178 nginx_vts_server_bytes_total{host=""exemple.com",direction="out"} 396
 179 nginx_vts_server_requests_total{host=""exemple.com",code="1xx"} 0
 180 nginx_vts_server_requests_total{host=""exemple.com",code="2xx"} 0
 181 nginx_vts_server_requests_total{host=""exemple.com",code="3xx"} 1
 182 nginx_vts_server_requests_total{host=""exemple.com",code="4xx"} 0
 183 nginx_vts_server_requests_total{host=""exemple.com",code="5xx"} 0
 184 nginx_vts_server_requests_total{host=""exemple.com",code="total"} 1
 185 nginx_vts_server_request_seconds_total{host=""exemple.com"} 0.000
 186 nginx_vts_server_request_seconds{host=""exemple.com"} 0.000
 187 nginx_vts_server_cache_total{host=""exemple.com",status="miss"} 0
 188 nginx_vts_server_cache_total{host=""exemple.com",status="bypass"} 0
 189 nginx_vts_server_cache_total{host=""exemple.com",status="expired"} 0
 190 nginx_vts_server_cache_total{host=""exemple.com",status="stale"} 0
 191 nginx_vts_server_cache_total{host=""exemple.com",status="updating"} 0
 192 nginx_vts_server_cache_total{host=""exemple.com",status="revalidated"} 0
``

is it possible to implement a filter?

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
