### ISSUE TITLE
unexpected first record, dropping buffer

### ISSUE THREAD

**Issue by fcddk** [prometheus/prometheus#7409]
prometheus version: 2.15.2
storage: Local storage， size:2T ，local disk storage

log :
level=error ts=2020-06-05T17:01:06.947Z caller=db.go:609 component=tsdb msg="compaction failed" err="reload blocks: head truncate failed: create checkpoint: read segments: corruption in segment /prometheus/wal/00000136 at 32768: unexpected first record, dropping buffer"

Serious consequences：
The wal stored 20 days, 100G old data, cannot be cleared normally, and prometheus cannot be started at last

**Comment by fcddk** [comment]
level=warn ts=2020-06-11T05:47:16.216Z caller=main.go:514 msg="Received SIGTERM, exiting gracefully..."

**Comment by fcddk** [comment]
level=error ts=2020-06-17T06:52:14.015Z caller=main.go:747 err="opening storage failed: get segment range: segments are not sequential"

**Comment by codesome** [comment]
> The wal stored 20 days, 100G old data, cannot be cleared normally, and prometheus cannot be started at last

That's a lot of data in WAL and not normal for Prometheus. Has the corruption message being going on for very long without a restart? The error that you mentioned is mainly due to disk corruption and the solution is to delete the WAL (all the files after the corrupt file).

> level=error ts=2020-06-17T06:52:14.015Z caller=main.go:747 err="opening storage failed: get segment range: segments are not sequential"

Did you delete some files manually?

**Comment by fcddk** [comment]
I delete the file  '/prometheus/wal/00000136'  manually.

**Comment by fcddk** [comment]
As can be seen from the log, once the segment file is damaged, the old wal data cannot be cleaned up normally. The files in the wal directory continue to increase, and eventually prometheus will be directly down.

**Comment by fcddk** [comment]
level=error ts=2020-06-01T15:01:07.454Z caller=db.go:609 component=tsdb msg="compaction failed" err="reload blocks: head truncate failed: create checkpoint: read segments: corruption in segment /prometheus/wal/00000136 at 32768: unexpected first record, dropping buffer" 


level=error ts=2020-06-11T05:01:05.828Z caller=db.go:609 component=tsdb msg="compaction failed" err="reload blocks: head truncate failed: create checkpoint: read segments: corruption in segment /prometheus/wal/00000136 at 32768: unexpected first record, dropping buffer"

**Comment by fcddk** [comment]
I think this is a fatal bug, there should be a forced deletion strategy or compensation mechanism, wal has a lot of accumulated old data does not make any sense.

**Comment by codesome** [comment]
> I delete the file '/prometheus/wal/00000136' manually.

You should be deleting all the files after that index and not just that file. On the other hand, if you restart the Prometheus, it will clean up the corrupt files itself (delete all the WAL starting from the corruption point).

**Comment by roidelapluie** [comment]
> > I delete the file '/prometheus/wal/00000136' manually.
> 
> You should be deleting all the files after that index and not just that file. On the other hand, if you restart the Prometheus, it will clean up the corrupt files itself (delete all the WAL starting from the corruption point).

Is  that new ? Can you verify that assertion? thanks :)

**Comment by codesome** [comment]
What is new?

**Comment by fcddk** [comment]
Yes, after deleting the data, restart the pod, the program can work normally.

**Comment by fcddk** [comment]
Prometheus should consider handling such exceptions, because prometheus should not work properly because of the existence of wal's bad files. Reliable prometheus should not cause a crash after a period of time due to this hidden danger.

**Comment by codesome** [comment]
> Prometheus should consider handling such exceptions

That is a reasonable request, but I am not sure if it is good to silently delete data.

There are metrics to track failed checkpointing. Additionally, we can increment `prometheus_tsdb_wal_corruptions_total` when we face corruption during runtime (we only increment in the beginning right now), and alerts could be set for those metrics.

**Comment by fcddk** [comment]
prometheus_tsdb_wal_truncations_total==0
prometheus_tsdb_wal_corruptions_total no data

**Comment by codesome** [comment]
> prometheus_tsdb_wal_corruptions_total no data

Cause the old data is deleted.

**Comment by fcddk** [comment]
Yes, we can see the shortcomings of promethes: when such an exception occurs, the normal function of the wal module cannot be guaranteed, which is very undesirable and dangerous, prometheus should heal itself, remove the files before the bad files, and keep them forever Its snapshot function for the latest data.

**Comment by Alexbyy** [comment]
> > The wal stored 20 days, 100G old data, cannot be cleared normally, and prometheus cannot be started at last
> 
> That's a lot of data in WAL and not normal for Prometheus. Has the corruption message being going on for very long without a restart? The error that you mentioned is mainly due to disk corruption and the solution is to delete the WAL (all the files after the corrupt file).
> 
> > level=error ts=2020-06-17T06:52:14.015Z caller=main.go:747 err="opening storage failed: get segment range: segments are not sequential"
> 
> Did you delete some files manually?

There are comments in the code which  says "When we hit any corruption during checkpointing,repairing is not an option"。But it doesn't mention any way to solve this problem,Does the way that deleting the wal manually is the only way we can do in this case? and I am wondering why prometheus doesn't take any approach after  we hit some corruption. such as deleting the corruption's segment with force. Thanks!

**Comment by fcddk** [comment]
The only solution now is to delete the damaged files so that prometheus can work normally. Without any wal backup data for repair, after all, I think that the stable collection and monitoring function is the original intention and goal of prometheus. Now the only thing to consider is how to delete, and the impact on the monitoring data after deletion.

**Comment by fcddk** [comment]
Now there is a difficulty: Is there any good way to reproduce this exception, so that it is convenient to do optimization testing for the problem.

**Comment by beorn7** [comment]
Hello from the bug scrub.

A lot has happened in this area over the last 4y. There is probably little value in keeping this particular issue open. We'll close it and would encourage people running into WAL replay issues to open new issues.
