### ISSUE TITLE
Load rule files from directory or glob.

### ISSUE THREAD

**Issue by beorn7** [prometheus/prometheus#741]
In the config, rules files have to be specified explicitly at the moment. It should be possible to either specify a glob or a directory. Upon startup and upon a SIGHUP, all files matching the specified glob or all files matching `*.rules` in the specified directory, respectively, will be loaded.

Note that the latter corresponds to the way the textfile module of the node exporter works.

Both ways allows applying atomic renaming to avoid parsing of incomplete files (i.e. we do not want an implementation that simply loads _all_ files in a specified directory).

**Comment by beorn7** [comment]
BTW: I prefer the `<directory>/*.rules` way over the glob way.

**Comment by fabxc** [comment]
Me too – it's also more consistent with the `file_sd_configs`.

**Comment by beorn7** [comment]
You actually mean the opposite. ;)

**Comment by fabxc** [comment]
See my comment in the PR. Glob is simply used to expand the files in the directory (plus allowing prefixes and suffixes on file level). Globing directories is not possible through the config.

**Comment by beorn7** [comment]
Yes.

But my idea was, like in the textfile exporter, to not allow globs at all, but only either a complete file name or a directory. In the former case, everything stays as it is (so no breaking change). In the latter case, only files with a hardcoded suffix (e.g. `.rules`) are loaded from that directory.

I like my idea best (hear hear...), but I prefer consistency within the same binary. So we should go with exactly the same approach as the file-based SD.

**Comment by fabxc** [comment]
I think the current solution is closer to your idea than to full-fledged globing – at least I hope so :)

We could of course enforce `.rules` ending as well if no one feels strong about potentially breaking people who chose another extension for some reason.

**Comment by beorn7** [comment]
> I think the current solution is closer to your idea than to full-fledged globing – at least I hope so :)

But perhaps globbing is not desirable _per se_.

Also, we don't need to enforce `.rules` as a prefix in general. According to my idea, that would only required for files in configured directories.

But as said, unless we now want to change file-based SD, too, we should just stay with the approach you have chosen.

**Comment by matthiasr** [comment]
FWIW, taking everything from a directory is not incompatible with atomic renames either – as long as it's on the same filesystem, whether the `mv` is within a directory or not doesn't matter.

**Comment by fabxc** [comment]
Yes, if you have a set of fixed file extensions that are considered only,
this is not an issue.

**Comment by beorn7** [comment]
On Thu, May 28, 2015 at 12:56 PM, Matthias Rampke
<notifications@github.com> wrote:
>
> FWIW, taking everything from a directory is not incompatible with atomic renames either – as long as it's on the same filesystem, whether the mv is within a directory or not doesn't matter.

Sure. Technically, it's not a problem, but we are expecting human
beings to do it the right way...


-- 
Björn Rabenstein, Engineer
http://soundcloud.com/brabenstein

SoundCloud Ltd. | Rheinsberger Str. 76/77, 10115 Berlin, Germany
Managing Director: Alexander Ljung | Incorporated in England & Wales
with Company No. 6343600 | Local Branch Office | AG Charlottenburg  |
HRB 110657B

**Comment by fabxc** [comment]
Renaming being atomic is not a general assumption we can make anyway,
unfortunately.

**Comment by davidkarlsen** [comment]
The issue is closed - but was this ever implemented?

**Comment by beorn7** [comment]
Yes, it's globbing. https://github.com/prometheus/prometheus/blob/42c05dd3a2e847b5329470a6a0d380b09cf3ca13/rules/manager.go#L389

We should document the behavior.

**Comment by beorn7** [comment]
See https://github.com/prometheus/docs/pull/586
