### ISSUE TITLE
can we have  the API  "get historic alert"

### ISSUE THREAD

**Issue by garysdevil** [prometheus/prometheus#7416]
Reason：
1. Safety review
2. We can count differnt alert, after that we can do some app truning

**Comment by gouthamve** [comment]
Hi, you could use the `ALERTS` time-series for this. This is more of a usage request than a bug, so we're closing this as part of a bug-scrub.

To make your question, and all replies, easier to find, we suggest you move this over to our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search. If you prefer more interactive help, join or our [IRC channel](https://webchat.freenode.net/?randomnick=1&channels=prometheus), #prometheus on irc.freenode.net. Please be aware that our IRC channel has no logs, is not searchable, and that people might not answer quickly if they are busy or asleep. If in doubt, you should choose the mailing list.

Once your questions have been answered, please add a short line pointing to relevant replies in case anyone stumbles here via a search engine in the future.
