### ISSUE TITLE
Documentation rendering is faulty

### ISSUE THREAD

**Issue by datamuc** [prometheus/prometheus#7418]
The rendering of the documentation is doing something wrong:

https://prometheus.io/docs/prometheus/latest/configuration/configuration/#container

After "See below for the configuration options for Triton discovery" there is a lot of mess.

https://github.com/prometheus/prometheus/blob/release-2.19/docs/configuration/configuration.md
and
https://github.com/prometheus/prometheus/blob/master/docs/configuration/configuration.md
are looking ok though.

**Comment by roidelapluie** [comment]
@codesome what about we backport 

https://github.com/prometheus/prometheus/commit/3c753aba5f3ac334e87c1203ddc6c27cd0005bf3#diff-e3e2a9bfd88566b05001b02a3f51d286

to release-2.19?

**Comment by roidelapluie** [comment]
Thank you, this is fixed #7419
