### ISSUE TITLE
Cache that DNS UDP query led to TC

### ISSUE THREAD

**Issue by miekg** [prometheus/prometheus#742]
Currently the code in `retrieval/discovery/dns.go` always does a UDP lookup first. When this returns a truncated packet, a TCP query is tried instead. So far so good.

I think it makes sense to implement some kind of caching here, so once a TC bit is seen for a name, only TCP queries are done for the next X minutes (or whatever).

**Comment by fabxc** [comment]
That's certainly an optimization we should consider.
I don't think it's urgent for now, though, as the number of DNS requests is
completely shadowed by the number of target scrapes.

It might take a while until we get to it – PRs are always welcome, of
course :)

**Comment by gouthamve** [comment]
This is out of scope in Prometheus itself, we shouldn't be doing DNS resolver logic in Prometheus itself, but rather offload it to a third party library if one is available. Also closing this as nobody has asked for it in a while.
