### ISSUE TITLE
REACT UI: Alert value not showed correctly in alert tab

### ISSUE THREAD

**Issue by nunokisc** [prometheus/prometheus#7424]
**What did you do?**
When I tried the new user interface I went to the alerts tab and opened an alert that had been triggered when the value was over 95 and the value it had was 9.503297183067829e+01. I went to the old interface and the value is really 95.0330846897198.
Perhaps a problem with unit conversion in the new interface.

**What did you expect to see?**
The same value as the old interface i think.
Alert value in old interface 95.0330846897198.

**What did you see instead? Under which circumstances?**
Alert value in new interface 9.503297183067829e+01.

**Environment**

* System information:

Linux 3.10.0-1062.12.1.el7.x86_64 x86_64

* Prometheus version:

prometheus, version 2.19.1 (branch: HEAD, revision: eba3fdcbf0d378b66600281903e3aab515732b39)
  build user:       root@62700b3d0ef9
  build date:       20200618-16:35:26
  go version:       go1.14.4

![OLD UI](https://user-images.githubusercontent.com/26737722/85165676-16f44a80-b25e-11ea-817c-c5bfcf13e727.png)
![NEW UI](https://user-images.githubusercontent.com/26737722/85165679-178ce100-b25e-11ea-9ffa-ed8f23953a09.png)

#7426

**Comment by roidelapluie** [comment]
Thanks for your report.

The new UI is using scientific notation, 9.5e+01 = 95.

cc @juliusv what should we do with this?

**Comment by nunokisc** [comment]
The old ui also uses scientific notation but in larger numbers, if i'm not wrong.

**Comment by nunokisc** [comment]
solved in #7426
