### ISSUE TITLE
Identify re-used service discovery configs

### ISSUE THREAD

**Issue by roidelapluie** [prometheus/prometheus#7427]
## Proposal
**Use case. Why is this important?**

It is currently difficult to identify if a service discovery is effectively reused. We could either add a metric of a sign in the UI if that's the case. When we have support requests or even when debugging, that would be useful.

**Comment by beorn7** [comment]
Hello from the bug scrub.

After almost 4y of radio silence on this, we assume this isn't relevant enough to keep it open. @roidelapluie please re-open if you disagree.
