### ISSUE TITLE
Error indexing label name to label values batch: write data/labelname_to_labelvalues/000411.log: no space left on device

### ISSUE THREAD

**Issue by jeeyshe** [prometheus/prometheus#7432]
The porblem is like the title, but when I check the host, I found space is enough.

* Logs:
```
Error indexing label name to label values batch: write data/labelname_to_labelvalues/000411.log: no space left on device
```
* works
While I restart prometheus, it works. We had filled the disk with data the day before error occurred,  So, when disk has no free space, error occurred, while disk space recovered ans had enough space, prometheus has no perception about it. So error last for days until I restart prometheus.

**Comment by codesome** [comment]
Thanks for the report. This doesn't look like a problem in Prometheus itself rather the disk space running out as you mentioned. Prometheus needs free disk space to run.
