### ISSUE TITLE
Security issue on JQuery with version < 3.5

### ISSUE THREAD

**Issue by sasadangelo** [prometheus/prometheus#7446]
Hi all,

I use Prometheus in a monitoring project for my Company. The security team opened a vulnerability issue because on 9090 port they see a JQuery version below 3.5. They reported the following security report:
https://www.tenable.com/plugins/nessus/136929
that suggests upgrading to 3.5

If you follow the link inside you arrive here:
https://blog.jquery.com/2020/04/10/jquery-3-5-0-released/

If I well understand the problem, it is related to the use of a special HTML tag. It's clear that to fix the security issue you need to upgrade to 3.5 or just report that you don't use that tag.

Now looking at the commit history there is this commit, where it seems the fix is present.
https://github.com/prometheus/prometheus/commit/c7d9516695c51cdb2185166e34c8190feca0fdf8

the commit was included 26 days ago. I tried the Prometheus 2.19.1 (built 6 days ago) and I verified it includes JQuery 3.3.1. 

To verify this I did:
1. install Prometheus 2.19.1
2. start the server
3. Access to localhost:9090 with Chrome
4. Right-click->Inspect and click on Console tab
5. Enter this command: console.log(jQuery.fn.jquery);

it reports 3.3.1. My question is: why I do not have evidence that Prometheus 2.19.1 uses JQuery 3.5? If JQuery 3.5 is not included in 2.19.1, can you tell me whether the security exposure affects Prometheus or not? If so, when do you think it will be solved?
Thank you in advance for help.

**Comment by simonpasquier** [comment]
jQuery is used both by the "legacy" UI and the React-based UI. https://github.com/prometheus/prometheus/commit/c7d9516695c51cdb2185166e34c8190feca0fdf8 only fixed the React part as far as I can tell.

I've submitted #7447 to upgrade the jQuery version in the legacy UI.

**Comment by sasadangelo** [comment]
Ok, it seems that:

```
Even though our code doesn't seem to be
vulnerable to the issue, lets upgrade to the latest jQuery release so we
don't have to bother.
```

this confirm that legacy UI is not affect by the problem. Right?
When do you think PR will be included?

**Comment by sasadangelo** [comment]
@juliusv why you closed this issue?
I only need a confirmation that this problem doesn't affect 2.19.1 so I can answer to my security team. Then I asked when it will be included because if it will happen in a few days I can wait and upgrade my project.

**Comment by sasadangelo** [comment]
@juliusv I am sorry, I just noticed you merged the PR.
Thank you. Excuse me, I am not well inside the Prometheus projects. How long does it take to have a new build release?

**Comment by simonpasquier** [comment]
The next release candidate is planned for July 15th (see [RELEASE.md](https://github.com/prometheus/prometheus/blob/master/RELEASE.md)).

**Comment by sasadangelo** [comment]
Hi, thank you for your reply.
The release schedule seems for a major release. What about a minor release (i.e. 2.19.1)? 
I noticed you merged the PR and automatically started a build and test process. This time I noticed there is a failure, however, suppose it completes successful, does this mean a minor release will be created (i.e. 2.19.2) that I can install?

I think we can wait until July 15th because this problem seems a false positive (detected by Nessus a vulnerability scan tool), however, if there is a chance I can close it earlier with a minor release it would be great.

**Comment by sasadangelo** [comment]
@simonpasquier @juliusv I noticed a new driver 2.19.2 has been released. I installed it but fix is not included. As said above I think something went wrong with acceptance tests for the PR. Please can you give a look? I would like to avoid that PR will not be included in the 15th July release due to integration problems.

**Comment by simonpasquier** [comment]
#7447 will be included in v2.20.0 for sure. v2.19.2 was a patch release so it only included a critical fix that would prevent a potential crash in v2.19.0 and v2.19.1.

**Comment by sasadangelo** [comment]
Ok thank you

**Comment by simonpasquier** [comment]
@sasadangelo  v2.20.0 is out :)
