### ISSUE TITLE
Make labels.Matcher an interface

### ISSUE THREAD

**Issue by codesome** [prometheus/prometheus#7449]
## Proposal
**Use case. Why is this important?**

While changing the matcher to an interface does not affect Prometheus in any way except maybe code changes at a lot of places, this would allow custom matchers to be implemented and experimented easily for projects like Cortex/Thanos and hence also backport them to Prometheus.

**Comment by brian-brazil** [comment]
Should we really be making our code more complicated for the sake of making it easy for downstream projects to produce incompatible versions of PromQL?

**Comment by codesome** [comment]
> for the sake of making it easy for downstream projects to produce incompatible versions of PromQL

Cortex plans to experiment with regex optimization which is sometimes the bottleneck when it comes to query touching lots of series. I don't think projects like Cortex and Thanos have any plans to get incompatible with PromQL but actually tries to be 100% compatible (including the web APIs). I cannot speak for other projects, but you have some projects here which will use it for good and backport optimizations to Prometheus :)

**Comment by codesome** [comment]
Example _experiments_ https://github.com/cortexproject/cortex/compare/master...pracucci:fast-regex-matching which if proves to be good, we could backport it into Prometheus

**Comment by codesome** [comment]
@pracucci mentioned that the indirection from the interface has a performance impact as the `Matches()` method would be called a lot of times. I am closing this for now in favor of https://github.com/prometheus/prometheus/pull/7453/ as an interface won't be required if we are able to add optimizations directly upstream.
