### ISSUE TITLE
Prometheus working for none-clusteradmin accounts

### ISSUE THREAD

**Issue by KlavsKlavsen** [prometheus/prometheus#7458]
## Proposal
**Use case. Why is this important?**
We are several departments, who run on a common openshift cluster, and we are not cluster-admins, which means we cannot query for Pods at ClusterScope f.ex. - and Prometheus does this - even if you direct it to only look at a few namespaces.

I would like for each department to be able to manage their own monitoring - as they are responsible for those services and handling ops for them - and prometheus + mtail would be very nice for that.

Currently Prometheus does not seem to able to work at all - when run in such a context.
I keep getting errors about it trying to access v1.Pods at ClusterScope: https://groups.google.com/forum/#!topic/prometheus-users/tsDEYeshn7k

I have tried disabling scraping of pods - as I'm okay with having to define pods to monitor manually if necessary (but it should be able to just list pods in the given namespaces - to discover.

I tried with just removing the rules from prometheus helm chart that I did not have access to - and improve helm chart to allow for RoleBindings in all namespaces instead of using ClusterRoleBindings - and then I got the admin to insert a common Role - that I could point at. This seems to work fine, and I'll gladly submit a PR for the improved chart to support it - once prometheus can actually work in this context.

**Comment by roidelapluie** [comment]
cc @brancz

**Comment by KlavsKlavsen** [comment]
I opened #7470 about the error log - so this can be about making Prometheus support none-clusteradmin usage.. I don't know if thats not right or not.. but IMHO its a bug that it logs that error constantly - and its a missing feature that it does not have options to support none-clusteradmin usage (for openshift users who wants to run their own monitoring :)

Together with container-resource-exporter and this fix in openshift https://bugzilla.redhat.com/show_bug.cgi?id=1756123 - I seem to have solved how to get all the metrics I need - so its actually doable to run my own prometheus and get usage metrics as well.. Kube-state-metrics works in "namespaced" none-cluteradmin mode - so I get request and limit numbers for all my containers.. so it seems its just Prometheus thats hardcoded to expecting being cluster admin and having access to the v1.Pods at clusterscope.

**Comment by brancz** [comment]
Which version of Prometheus are you using? Because we are actively discovering Endpoints on individual namespaces and that only requires list/watch for those namespaces.

**Comment by KlavsKlavsen** [comment]
Using v2.18.1

**Comment by brancz** [comment]
Could you share your entire configuration instead of the snippet?

**Comment by KlavsKlavsen** [comment]
full configmap

```
apiVersion: v1
data:
  alerting_rules.yml: |
    {}
  alerts: |
    {}
  prometheus.yml: |
    global:
      evaluation_interval: 1m
      scrape_interval: 1m
      scrape_timeout: 10s
    rule_files:
    - /etc/config/recording_rules.yml
    - /etc/config/alerting_rules.yml
    scrape_configs:
    - job_name: prometheus
      static_configs:
      - targets:
        - localhost:9090
    - job_name: kube
      static_configs:
      - targets:
        - api-klavs2-prometheus-kube-state-metrics:8080
    - job_name: kubernetes-pods
      kubernetes_sd_configs:
      - namespaces:
          names:
          - api-klavs2-gateway-bank-d1
          - api-klavs2-gateway-web-d1
          - api-klavs2-manager-d1
          - api-klavs2-portal-d1
          - api-klavs2-tiller-d1
        role: pod
      relabel_configs:
      - action: keep
        regex: true
        source_labels:
        - __meta_kubernetes_pod_annotation_prometheus_io_scrape
      - action: replace
        regex: (.+)
        source_labels:
        - __meta_kubernetes_pod_annotation_prometheus_io_path
        target_label: __metrics_path__
      - action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        source_labels:
        - __address__
        - __meta_kubernetes_pod_annotation_prometheus_io_port
        target_label: __address__
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - action: replace
        source_labels:
        - __meta_kubernetes_namespace
        target_label: kubernetes_namespace
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_name
        target_label: kubernetes_pod_name
    alerting:
      alertmanagers:
      - kubernetes_sd_configs:
          - role: pod
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        relabel_configs:
        - source_labels: [__meta_kubernetes_namespace]
          regex: api-klavs2-monitoring-d1
          action: keep
        - source_labels: [__meta_kubernetes_pod_label_app]
          regex: prometheus
          action: keep
        - source_labels: [__meta_kubernetes_pod_label_component]
          regex: alertmanager
          action: keep
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_probe]
          regex: .*
          action: keep
        - source_labels: [__meta_kubernetes_pod_container_port_number]
          regex:
          action: drop
  recording_rules.yml: |
    {}
  rules: |
    {}
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: api-klavs2-prometheus
    meta.helm.sh/release-namespace: api-klavs2-monitoring-d1
  creationTimestamp: 2020-06-26T10:24:33Z
  labels:
    app: prometheus
    app.kubernetes.io/managed-by: Helm
    chart: prometheus-11.5.0
    component: server
    heritage: Helm
    release: api-klavs2-prometheus
  name: api-klavs2-prometheus-server
  namespace: api-klavs2-monitoring-d1
  resourceVersion: "339235079"
```

**Comment by brancz** [comment]
The discovery config under the `alerting` section is the culprit. You are not scoping the namespace to discover from there, which is why it tries to discover the Alertmanager pods from all namespaces.

**Comment by KlavsKlavsen** [comment]
why aren't those logs in alertmanager pod then?.. I'll test it out :)

**Comment by brancz** [comment]
It's Prometheus discovering Alertmanager being the problem.

**Comment by KlavsKlavsen** [comment]
Thank you for the clarity. The default in chart Values.yaml - is:
alertmanagers: []

That threw me off :)

I'll see how to get my PR to the prometheus helm chart posted (fighting getting access to github push here unfortunately) - which enables support for using "common" clusterrole, with RoleBinding per-namespace instead - for those of us running on openshift cluster as none-cluster admins :)
