### ISSUE TITLE
Deep Dive into TSDB Internal Structures

### ISSUE THREAD

**Issue by yashrsharma44** [prometheus/prometheus#7459]
## Documentation Request

Hey Everyone, I have been going through the tsdb of **Prometheus**, and it is a pretty powerful database that powers it.

I wanted to dig more about the internal structure of `tsdb` and know about the structure of `chunks`, `index`, `head chunks`, `tombstones` and `wal`, but the [current documentation](https://github.com/prometheus/prometheus/tree/master/tsdb/docs/format) was _too abstract_ for me.

Honestly, this might be simple for _experienced authors and contributors_, but since I am quite new to the Prometheus and Databases in general, I would love some **visualizations and deep dive into the tsdb internal structures**.

I have went through **Fabian's** talk, it was quite promising, but at the same time he skimmed through the internals, which don't cover the depth.

I also went through **Goutham's** talk, which was quite interactive and hilarious, so kudos to him(https://www.youtube.com/watch?v=AYnXeMGAZes&t=1026s), but in his talk he covered the apsect of using tsdb as a library and not the internal constructs

Similarly, I also watched **Björn's** talk (https://www.youtube.com/watch?v=HbnGSNEjhUc) and it discussed the algorithm used in tsdb.

I was suggested this [doc](https://docs.google.com/document/d/1t5eSLlH36oK1Ex3PWwuc4R58kx4PC7Ago90TRR_7nmo/edit#heading=h.9fse7yo9k0j6) by @gouthamve , and it was somewhat helpful, because the internal structure of tsdb was rewritten soon after this doc was written.

So what I think is missing is an explanation of the internals of tsdb, particularly how - 
• Visual representation of chunk/index/tombstones/etc
• What are postings
• Series/Chunks
• Visual representation of the documentation of tsdb

The documentation of tsdb is still **comprehensive** and covers lots of topics, but it is **too abstract** for a newbie developer like me, and some **explanation / visual diagrams** would go a long way in decrypting the internals of tsdb :stuck_out_tongue: .

**Comment by bwplotka** [comment]
Amazing, thanks for this write-up. I think this might very useful for potential talks that Ian plans! :muscle:

**Comment by juliusv** [comment]
I had the same thoughts recently when trying to understand the TSDB code, especially since so much has happened in the TSDB recently, and it would be great to get specific explanations of how everything fits together these days, maybe with pointers to code like I once did for the overall Prometheus architecture in https://github.com/prometheus/prometheus/blob/master/documentation/internal_architecture.md :)

**Comment by codesome** [comment]
I can attempt to draw some diagrams for the overall picture of how different components (inside TSDB) fit in as the first step (without going into details of each component for now).

**Comment by ianbillett** [comment]
@juliusv that [internal architecture overview](https://github.com/prometheus/prometheus/blob/master/documentation/internal_architecture.md) is awesome!  Can't believe I have never seen it before - it doesn't appear to be present on the docs page 🤔  

I would be happy to make a first attempt of flesh out that document with some findings from my PromCon talk `TSDB WTF` :)

**Comment by juliusv** [comment]
@ianbillett Awesome, thanks, glad you like it :) For TSDB-specific stuff it would be great to put it into a separate document, but then link to that from the main one.

**Comment by ianbillett** [comment]
FYI the branch is in-progress [here](https://github.com/ianbillett/prometheus/tree/internal-tsdb-architecture-docs) - PR should be ready this weekend 🤗

**Comment by yashrsharma44** [comment]
Some more resources -
* https://ganeshvernekar.com/blog/prometheus-tsdb-the-head-block
* https://ganeshvernekar.com/blog/prometheus-tsdb-wal-and-checkpoint

Thanks @codesome for the writeup! :tada:

**Comment by codesome** [comment]
I expect at least 5 more blog posts covering other parts :)

**Comment by beorn7** [comment]
Hello from the bug scrub.

With @codesome's blog posts published a long time ago, we'll close this. https://ganeshvernekar.com/blog/prometheus-tsdb-the-head-block/
