### ISSUE TITLE
Getting mmap: invalid argument error for 2.19.0 version

### ISSUE THREAD

**Issue by rajanikantpatel** [prometheus/prometheus#7469]
getting following error with prometheus 2.19.0 version.

level=error ts=2020-06-26T09:51:32.496Z caller=main.go:758 err="opening storage failed: mmap files, file: /prometheus/data/chunks_head/000108: mmap: invalid argument

following is the arguments 
- >-
              --web.external-url=https://prometheus-dev-kc1-iad.saase2e.pitneycloud.com
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--storage.tsdb.path=/prometheus/data'
            - '--storage.tsdb.retention.time=30d'
            - '--web.enable-lifecycle'
            - '--storage.tsdb.no-lockfile'
            - '--log.level=warn'

**Comment by brian-brazil** [comment]
What operating system and filesystem are you using? What does strace say is happening?

> --storage.tsdb.no-lockfile

This is a dangerous flag that you should not use.

**Comment by DandyDeveloper** [comment]
@brian-brazil @rajanikantpatel I experienced a similar problem today in 2.19.1.

Issue was very similar to this: https://github.com/prometheus/prometheus/issues/7412

I think the bugfix isn't working as we had an empty chunk file that basically needed to be removed and my understanding is the fix in the above issue removes those loose chunk files.

After removing the file in question that the error is complaining about, things started up as normal.

**Comment by roidelapluie** [comment]
> @brian-brazil @rajanikantpatel I experienced a similar problem today in 2.19.1.
> 
> Issue was very similar to this: #7412
> 
> I think the bugfix isn't working as we had an empty chunk file that basically needed to be removed and my understanding is the fix in the above issue removes those loose chunk files.
> 
> After removing the file in question that the error is complaining about, things started up as normal.

Thanks, sounds like a different issue. Can you please open a new bug please?

**Comment by codesome** [comment]
> we had an empty chunk file

0 bytes? There can be 0 chunks, but 0 bytes in a file seems unlikely as we write headers as soon as we create a file.

But checking the `mmap: invalid argument` error from this issue description, that (also) comes when we try to m-map a completely empty file, so I think _somewhere_ we are ending up creating empty files (even without headers). I will check that.

**Comment by codesome** [comment]
@rajanikantpatel did the Prometheus shutdown gracefully when you restarted?

**Comment by DandyDeveloper** [comment]
@codesome @roidelapluie I'll wait until it's been confirmed before opening this. As the error is the exact same. 

In my case, I just needed to remove the chunks_head file being references and it was completely empty. 

In our case, it's plausible we have an ungraceful shutdown (It was a k8s pod, so I couldn't get the logs from the original crash)

**Comment by gouthamve** [comment]
When we cut a new file, we open a new file and then write the headers to it. Which means if Prometheus crashes right after we create the file, we could end up with an empty file. We should either ignore the empty files, or write the header to `tmp` file and then `mv`.

**Comment by bibarrav** [comment]
Hi, I'm having the same issue with Prometheus v2.20.1... and try v2.20.0, v2.21.0-rc.0, master tag, and the issue still appearing

Here my logs:
level=info ts=2020-09-04T17:14:32.024Z caller=main.go:343 msg="Starting Prometheus" version="(version=2.20.1, branch=HEAD, revision=983ebb4a513302315a8117932ab832815f85e3d2)"
level=info ts=2020-09-04T17:14:32.024Z caller=main.go:344 build_context="(go=go1.14.6, user=root@7cbd4d1c15e0, date=20200805-17:26:58)"
level=info ts=2020-09-04T17:14:32.024Z caller=main.go:345 host_details="(Linux 4.15.0-115-generic #116-Ubuntu SMP Wed Aug 26 14:04:49 UTC 2020 x86_64 prometheus-server-79cc5df447-hrlkg (none))"
level=info ts=2020-09-04T17:14:32.024Z caller=main.go:346 fd_limits="(soft=1048576, hard=1048576)"
level=info ts=2020-09-04T17:14:32.024Z caller=main.go:347 vm_limits="(soft=unlimited, hard=unlimited)"
level=info ts=2020-09-04T17:14:32.118Z caller=web.go:524 component=web msg="Start listening for connections" address=0.0.0.0:9090
level=info ts=2020-09-04T17:14:32.118Z caller=main.go:684 msg="Starting TSDB ..."
level=info ts=2020-09-04T17:14:32.220Z caller=repair.go:59 component=tsdb msg="Found healthy block" mint=1597903200000 maxt=1597910400000 ulid=01EG5TV6K79QZ8AHQDM0DX3H85
level=info ts=2020-09-04T17:14:32.221Z caller=repair.go:59 component=tsdb msg="Found healthy block" mint=1597917600000 maxt=1597924800000 ulid=01EG5Z96T86NZNR124D42YRHCZ
level=info ts=2020-09-04T17:14:32.222Z caller=repair.go:59 component=tsdb msg="Found healthy block" mint=1597893487370 maxt=1597903200000 ulid=01EG5Z9PAQ2TSZ7A7Y11BP29A9
level=info ts=2020-09-04T17:14:32.222Z caller=repair.go:59 component=tsdb msg="Found healthy block" mint=1597924800000 maxt=1597946400000 ulid=01EG6TR61T3Q89F8ZZ79S5ND0N
level=info ts=2020-09-04T17:14:32.222Z caller=repair.go:59 component=tsdb msg="Found healthy block" mint=1597946400000 maxt=1597968000000 ulid=01EG7FBHK11XXTFCHMK3R0ZCXX
level=info ts=2020-09-04T17:14:32.223Z caller=repair.go:59 component=tsdb msg="Found healthy block" mint=1597968000000 maxt=1598032800000 ulid=01EG9D5GAP7KN3JD51MES3W6MH
level=info ts=2020-09-04T17:14:32.224Z caller=repair.go:59 component=tsdb msg="Found healthy block" mint=1598032800000 maxt=1598097600000 ulid=01EGBAZYVFPHB6B4TK2WXVDQ2W
level=info ts=2020-09-04T17:14:32.225Z caller=repair.go:59 component=tsdb msg="Found healthy block" mint=1598119200000 maxt=1598126400000 ulid=01EGBZH4GYBKQTD3MB43NY07D9
level=info ts=2020-09-04T17:14:32.226Z caller=repair.go:59 component=tsdb msg="Found healthy block" mint=1598097600000 maxt=1598119200000 ulid=01EGBZHJA864MSN5K41VRBC32T
level=info ts=2020-09-04T17:14:32.226Z caller=repair.go:59 component=tsdb msg="Found healthy block" mint=1598126400000 maxt=1598133600000 ulid=01EGC6CVPVF0KYBT9ZTFFV5X4G
level=info ts=2020-09-04T17:14:32.227Z caller=repair.go:59 component=tsdb msg="Found healthy block" mint=1598133600000 maxt=1598140800000 ulid=01EGCD8K3W39SCKJ15RT1ACHTY
level=info ts=2020-09-04T17:14:32.227Z caller=repair.go:59 component=tsdb msg="Found healthy block" mint=1598140800000 maxt=1598155200000 ulid=01EGEHYD79ZBBTFXRYMARP10ZT
level=info ts=2020-09-04T17:14:32.228Z caller=repair.go:59 component=tsdb msg="Found healthy block" mint=1598198400000 maxt=1598227200000 ulid=01EGFDDE40A11MTQY06Y4CAKVY
level=info ts=2020-09-04T17:14:32.228Z caller=repair.go:59 component=tsdb msg="Found healthy block" mint=1598227200000 maxt=1598292000000 ulid=01EGH4BJW8R4XME72G78383NEF
level=info ts=2020-09-04T17:14:32.229Z caller=repair.go:59 component=tsdb msg="Found healthy block" mint=1598292000000 maxt=1598356800000 ulid=01EGK262ZA8S469PYBFYCZRD55
level=info ts=2020-09-04T17:14:32.231Z caller=repair.go:59 component=tsdb msg="Found healthy block" mint=1598356800000 maxt=1598421600000 ulid=01EGMZYXFGM0SPAF2SPGVHPFZ4
level=info ts=2020-09-04T17:14:32.231Z caller=repair.go:59 component=tsdb msg="Found healthy block" mint=1598421600000 maxt=1598486400000 ulid=01EGPXW2EBPTGEY2JYXTH7BTXP
level=info ts=2020-09-04T17:14:32.232Z caller=repair.go:59 component=tsdb msg="Found healthy block" mint=1598551200000 maxt=1598558400000 ulid=01EGRVGRX354V7DSKE4H2K5VEG
level=info ts=2020-09-04T17:14:32.233Z caller=repair.go:59 component=tsdb msg="Found healthy block" mint=1598486400000 maxt=1598551200000 ulid=01EGRVJ6Q05FZ2G6BHWX0F7XPE
level=info ts=2020-09-04T17:14:32.234Z caller=repair.go:59 component=tsdb msg="Found healthy block" mint=1598558400000 maxt=1598565600000 ulid=01EGS2CG50X0TSDCC0VDGT9KBF
level=info ts=2020-09-04T17:14:32.235Z caller=repair.go:59 component=tsdb msg="Found healthy block" mint=1598565600000 maxt=1598572800000 ulid=01EGS987CX7QRTYPSEF907RZQ2
level=info ts=2020-09-04T17:14:32.236Z caller=repair.go:59 component=tsdb msg="Found healthy block" mint=1598572800000 maxt=1598580000000 ulid=01EGTW69JXJKX9ZTSJ4VSF7VAQ
level=info ts=2020-09-04T17:14:32.249Z caller=main.go:553 msg="Stopping scrape discovery manager..."
level=info ts=2020-09-04T17:14:32.249Z caller=main.go:567 msg="Stopping notify discovery manager..."
level=info ts=2020-09-04T17:14:32.249Z caller=main.go:589 msg="Stopping scrape manager..."
level=info ts=2020-09-04T17:14:32.249Z caller=main.go:563 msg="Notify discovery manager stopped"
level=info ts=2020-09-04T17:14:32.249Z caller=main.go:549 msg="Scrape discovery manager stopped"
level=info ts=2020-09-04T17:14:32.249Z caller=manager.go:888 component="rule manager" msg="Stopping rule manager..."
level=info ts=2020-09-04T17:14:32.249Z caller=manager.go:898 component="rule manager" msg="Rule manager stopped"
level=info ts=2020-09-04T17:14:32.249Z caller=main.go:583 msg="Scrape manager stopped"
level=info ts=2020-09-04T17:14:32.249Z caller=notifier.go:601 component=notifier msg="Stopping notification manager..."
level=info ts=2020-09-04T17:14:32.275Z caller=main.go:755 msg="Notifier manager stopped"
level=error ts=2020-09-04T17:14:32.366Z caller=main.go:764 err="opening storage failed: mmap files, file: /data/chunks_head/000051: mmap: invalid argument"

**Comment by roidelapluie** [comment]
Is /data/chunks_head/000051 empty? If yes, can you delete it and use 2.19.3 or 2.20.1?

**Comment by bibarrav** [comment]
Ok, It was empty, so I deleted it and started Prometheus normally... But, this problem is not resolved?, I understand that was introduced an improvement (#7573) to use .tmp file to prevent this?

**Comment by roidelapluie** [comment]
2.19.3 and 2.20.0 will no longer *create* those files, but if they are present we do not delete them, to make sure we catch any other bug that might happen after those releases.

**Comment by zetaab** [comment]
we still see this issue all the time and using 2.22.0. Also datas are cleaned like 100x times but still its driving me crazy all the time.

**Comment by roidelapluie** [comment]
Can you please raise a new issue with your details ? (logs, system, filesystem, etc)

**Comment by ngrilly** [comment]
Has been fixed with https://github.com/prometheus/prometheus/pull/8061.
