### ISSUE TITLE
Prometheus keeps logging error - when run as not clusteradmin

### ISSUE THREAD

**Issue by KlavsKlavsen** [prometheus/prometheus#7470]
With prometheus setup with no scraping configuration (except for itself) - with a user that is not clusteradmin - it logs constantly:
level=error ts=2020-06-26T12:26:02.836Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:385: Failed to list *v1.Pod: pods is forbidden: User \"system:serviceaccount:api-klavs2-monitoring-d1:prom-server-api-klavs2\" cannot list pods at the cluster scope: no RBAC policy matched"

This is an annoyance - when using Prometheus in a kubernetes cluster, to only manage my teams namespaces (which actually still works fine - it just logs the above all the time).

If I it wanted to discover pods - it should be configurable wether to query at clusterscope - or in namespace scope - and it seems discovery is hardcoded somewhere even with almost empty config?

**Comment by roidelapluie** [comment]
Can you paste the config.

**Comment by KlavsKlavsen** [comment]
Solved in #7458
