### ISSUE TITLE
React UI: Anchored links on /targets don't scroll to the selected pool on page load

### ISSUE THREAD

**Issue by juliusv** [prometheus/prometheus#7473]
Links like https://prometheus-react.netlify.app/new/targets#pool-caddy don't scroll to the selected target pool upon page load, so sharing links to specific target pools doesn't work properly. The scrolling works while using the page though, when clicking on one of the target pool headers. We probably need to explicitly read the hash fragment after loading the targets info and manually jump to the right spot.

**Comment by gouthamve** [comment]
@juliusv does #7456 fix this or is this still a bug to be fixed?

**Comment by juliusv** [comment]
This bug is still alive.

**Comment by beorn7** [comment]
Hello from the bug scrub.

We assume this has become irrelevant with the ongoing effort to redo the UI completely. @Nexucis please re-open if this assumption is wrong.
