### ISSUE TITLE
tsdb, index reader: Rename SortedLabelValue back to LabelValues and add UnsortedLabelValues.

### ISSUE THREAD

**Issue by bwplotka** [prometheus/prometheus#7478]
Hi, 

We just spent 30m figuring out the differences and the fact that `index.Reader.LabelValues` is unsorted and `querier.LabelValues`  is always sorted, creates real confusion. 

What do you think for quick readability improvement and changing things back and adding `UnsortedLabelValues` or `LabelValues(sorted)` as `Select` has? (: 

cc @gouthamve @brian-brazil @brancz

**Comment by bwplotka** [comment]
Related to https://github.com/prometheus/prometheus/pull/7448

**Comment by codesome** [comment]
Sounds good. I would prefer `UnsortedLabelValues` instead of passing a bool to avoid a lot of code changes (as `UnsortedLabelValues` would not be used very often)

**Comment by eklockare** [comment]
Made an attempt, I hope I interpreted correctly

**Comment by ngetahun** [comment]
Is this issue up for grabs? I'd like to submit a PR.

**Comment by bwplotka** [comment]
Looks like this was blocked on our review, reviewed now. So depends if @eklockare has time (:

**Comment by ngetahun** [comment]
I have a WIP [PR](https://github.com/prometheus/prometheus/pull/8098)

**Comment by bwplotka** [comment]
@ngetahun Can you base your changes on https://github.com/prometheus/prometheus/pull/7511 PR, because it super close to be done, just small nits. WDYT?

**Comment by yashrsharma44** [comment]
Can I work on this issue, if it's not resolved?

**Comment by palash25** [comment]
hi is this still up for grabs? i see 3 different open PRs for this

**Comment by codesome** [comment]
Pinged on #8624 to bring it back alive. I would wait for a week for any response.

**Comment by roidelapluie** [comment]
We have looked at this pull request during our bug scrub.

By now, we aren't even sure if it is worth changing the names. People are really used to the semantics now, so better leave it as is.

Thank you for your contribution.
