### ISSUE TITLE
Version 2.19.2 not in Image registry (quay.io)

### ISSUE THREAD

**Issue by Robert-Stam** [prometheus/prometheus#7481]
On quay.io version 2.19.2 is missing

https://quay.io/repository/prometheus/prometheus?tab=tags

Note that it’s available on the Docker hub.

Are you stopped with quay, if so, it would be good to add to the (version 2.19.2) release notes.

**Comment by roidelapluie** [comment]
cc @codesome @SuperQ @simonpasquier  should we release a .3? the .2 release job failed apparently.

**Comment by roidelapluie** [comment]
Thanks @Robert-Stam for your report.

**Comment by roidelapluie** [comment]
https://circleci.com/workflow-run/5116ac97-04bc-4894-acee-2ec52ae9f41e

**Comment by roidelapluie** [comment]
Note: the reason NOT to re-run the workflow is that it would change the checksum of the tarballs.

**Comment by Robert-Stam** [comment]
Somebody with push rights could pull from Docker hub and push to quay.io to fix manually.

**Comment by codesome** [comment]
> the .2 release job failed apparently.

:(

**Comment by SuperQ** [comment]
I'll see if I can re-publish everything.

**Comment by SuperQ** [comment]
Ok, I downloaded and extracted the build tarballs into my local .build. I then re-ran the various `make docker` commands.

**Comment by codesome** [comment]
Thanks @SuperQ for doing it! I see it in quay now
