### ISSUE TITLE
Compaction running out of memory

### ISSUE THREAD

**Issue by clambin** [prometheus/prometheus#7483]
**What did you do?**

Since upgrading to 2.19.2, I frequently see Prometheus running out of memory when compacting:

```
level=error ts=2020-06-29T21:00:03.803Z caller=db.go:675 component=tsdb msg="compaction failed" err="reload blocks: head truncate failed: truncate chunks.HeadReadWriter: mmap: cannot allocate memory"

panic: write /prometheus/chunks_head/000292: file already closed
```

However, when I check system resources, there is plenty of memory available.  E.g. in the case above, RSS was only 256MB (and has been higher than that without issue).

I suspect this has something to do with #6679 , which talks about this specific panic.

**What did you expect to see?**

Compaction should complete successfully.

**What did you see instead? Under which circumstances?**

Been tracking this issue for a couple of days now, but no discernible pattern:  compactions with more memory and more head chunks have been successful.

**Environment**

* System information:

	Linux 4.19.118-v7l+ armv7l
        running in docker (swarm) Docker version 19.03.12, build 48a6621 on raspbian buster.

* Prometheus version:

	prometheus, version 2.19.2 (branch: HEAD, revision: c448ada63d83002e9c1d2c9f84e09f55a61f0ff7)
	build user:       root@dd72efe1549d
	build date:       20200626-10:09:28
	go version:       go1.14.4

* Alertmanager version:

	N/A

* Prometheus configuration file:
```
services:
  prometheus:
    image: prom/prometheus:v2.19.2
    networks:
      - net
    volumes:
      - /mnt/media/prometheus_data:/prometheus
      - ./prometheus:/etc/prometheus
      - /etc/timezone:/etc/timezone
    ports:
      - 9090:9090
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=90d'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
```

(retention was 90d. I've since reduced it to 45d but problem remains the same)

* Alertmanager configuration file:

N/A

* Logs:

```
prometheus_prometheus.1.fpx4uxg188z4@raspberrypi    | level=info ts=2020-06-29T19:30:41.556Z caller=compact.go:495 component=tsdb msg="write block" mint=1593446400000 maxt=1593453600000 ulid=01EC0RYPXHNFMT3A82H0V00MM6 duration=2.40340887s
prometheus_prometheus.1.fpx4uxg188z4@raspberrypi    | level=info ts=2020-06-29T19:30:41.670Z caller=head.go:792 component=tsdb msg="Head GC completed" duration=39.301408ms
prometheus_prometheus.1.fpx4uxg188z4@raspberrypi    | level=info ts=2020-06-29T19:30:45.034Z caller=head.go:869 component=tsdb msg="WAL checkpoint complete" first=1996 last=1997 duration=3.151814496s
prometheus_prometheus.1.fpx4uxg188z4@raspberrypi    | level=info ts=2020-06-29T21:00:03.306Z caller=compact.go:495 component=tsdb msg="write block" mint=1593453600000 maxt=1593460800000 ulid=01EC0Y2AZD0HP9HBQ4VPDY9CAP duration=2.429068649s
prometheus_prometheus.1.fpx4uxg188z4@raspberrypi    | level=info ts=2020-06-29T21:00:03.490Z caller=head.go:792 component=tsdb msg="Head GC completed" duration=40.064588ms
prometheus_prometheus.1.fpx4uxg188z4@raspberrypi    | level=error ts=2020-06-29T21:00:03.803Z caller=db.go:675 component=tsdb msg="compaction failed" err="reload blocks: head truncate failed: truncate chunks.HeadReadWriter: mmap: cannot allocate memory"
prometheus_prometheus.1.fpx4uxg188z4@raspberrypi    | panic: write /prometheus/chunks_head/000292: file already closed
prometheus_prometheus.1.fpx4uxg188z4@raspberrypi    |
prometheus_prometheus.1.fpx4uxg188z4@raspberrypi    | goroutine 371 [running]:
prometheus_prometheus.1.fpx4uxg188z4@raspberrypi    | github.com/prometheus/prometheus/tsdb.(*memSeries).mmapCurrentHeadChunk(0xc22aa50, 0x5811290)
prometheus_prometheus.1.fpx4uxg188z4@raspberrypi    | 	/app/tsdb/head.go:1991 +0x22c
prometheus_prometheus.1.fpx4uxg188z4@raspberrypi    | github.com/prometheus/prometheus/tsdb.(*memSeries).cutNewHeadChunk(0xc22aa50, 0x1fcd273, 0x173, 0x5811290, 0x818b4)
prometheus_prometheus.1.fpx4uxg188z4@raspberrypi    | 	/app/tsdb/head.go:1962 +0x24
prometheus_prometheus.1.fpx4uxg188z4@raspberrypi    | github.com/prometheus/prometheus/tsdb.(*memSeries).append(0xc22aa50, 0x1fcd273, 0x173, 0x0, 0x0, 0x3275, 0x0, 0x5811290, 0x101)
prometheus_prometheus.1.fpx4uxg188z4@raspberrypi    | 	/app/tsdb/head.go:2118 +0x3a4
prometheus_prometheus.1.fpx4uxg188z4@raspberrypi    | github.com/prometheus/prometheus/tsdb.(*headAppender).Commit(0x9dd3c20, 0x0, 0x0)
prometheus_prometheus.1.fpx4uxg188z4@raspberrypi    | 	/app/tsdb/head.go:1197 +0x1ec
prometheus_prometheus.1.fpx4uxg188z4@raspberrypi    | github.com/prometheus/prometheus/tsdb.dbAppender.Commit(0x2406c58, 0x9dd3c20, 0x54d2f00, 0x1634e64, 0x1953c01)
prometheus_prometheus.1.fpx4uxg188z4@raspberrypi    | 	/app/tsdb/db.go:703 +0x24
prometheus_prometheus.1.fpx4uxg188z4@raspberrypi    | github.com/prometheus/prometheus/storage.(*fanoutAppender).Commit(0xa6b0000, 0x0, 0x0)
prometheus_prometheus.1.fpx4uxg188z4@raspberrypi    | 	/app/storage/fanout.go:162 +0x28
prometheus_prometheus.1.fpx4uxg188z4@raspberrypi    | github.com/prometheus/prometheus/scrape.(*scrapeLoop).append.func1(0x64dbdd4, 0x24069d8, 0xa6ae330, 0x85adc20, 0xe7c4000, 0x108cd8, 0x215ef8)
prometheus_prometheus.1.fpx4uxg188z4@raspberrypi    | 	/app/scrape/scrape.go:1091 +0x34
prometheus_prometheus.1.fpx4uxg188z4@raspberrypi    | github.com/prometheus/prometheus/scrape.(*scrapeLoop).append(0x85adc20, 0xe7c4000, 0x108cd8, 0x215ef8, 0xa699020, 0x19, 0x537c4e8a, 0xbfb6b539, 0x5eb4c5d9, 0x689, ...)
prometheus_prometheus.1.fpx4uxg188z4@raspberrypi    | 	/app/scrape/scrape.go:1224 +0xa04
prometheus_prometheus.1.fpx4uxg188z4@raspberrypi    | github.com/prometheus/prometheus/scrape.(*scrapeLoop).run(0x85adc20, 0x7e11d600, 0x3, 0x540be400, 0x2, 0x0)
prometheus_prometheus.1.fpx4uxg188z4@raspberrypi    | 	/app/scrape/scrape.go:970 +0x47c
prometheus_prometheus.1.fpx4uxg188z4@raspberrypi    | created by github.com/prometheus/prometheus/scrape.(*scrapePool).sync
prometheus_prometheus.1.fpx4uxg188z4@raspberrypi    | 	/app/scrape/scrape.go:422 +0x3c4
prometheus_prometheus.1.m32xuhbfthy0@raspberrypi    | level=info ts=2020-06-30T06:00:12.507Z caller=main.go:337 msg="Starting Prometheus" version="(version=2.19.2, branch=HEAD, revision=c448ada63d83002e9c1d2c9f84e09f55a61f0ff7)"
prometheus_prometheus.1.m32xuhbfthy0@raspberrypi    | level=info ts=2020-06-30T06:00:12.507Z caller=main.go:338 build_context="(go=go1.14.4, user=root@dd72efe1549d, date=20200626-10:09:28)"
prometheus_prometheus.1.m32xuhbfthy0@raspberrypi    | level=info ts=2020-06-30T06:00:12.508Z caller=main.go:339 host_details="(Linux 4.19.118-v7l+ #1311 SMP Mon Apr 27 14:26:42 BST 2020 armv7l e3696539f46b (none))"
prometheus_prometheus.1.m32xuhbfthy0@raspberrypi    | level=info ts=2020-06-30T06:00:12.508Z caller=main.go:340 fd_limits="(soft=1048576, hard=1048576)"
prometheus_prometheus.1.m32xuhbfthy0@raspberrypi    | level=info ts=2020-06-30T06:00:12.508Z caller=main.go:341 vm_limits="(soft=unlimited, hard=unlimited)"
prometheus_prometheus.1.m32xuhbfthy0@raspberrypi    | level=info ts=2020-06-30T06:00:12.515Z caller=main.go:678 msg="Starting TSDB ..."
```
<img width="578" alt="head chunks" src="https://user-images.githubusercontent.com/59534649/86102030-53744180-babb-11ea-9167-c506be4cc51e.png">
<img width="575" alt="memory usage" src="https://user-images.githubusercontent.com/59534649/86102035-553e0500-babb-11ea-9cd1-77b28b8465ae.png">

**Comment by brian-brazil** [comment]
That's a 32bit machine, on which running Prometheus is thus going to be extremely challenging. You need a machine with more (presumably virtual) memory.

**Comment by clambin** [comment]
I've been running it fine for over 6 months.  It's only since upgrading to 2.19 that problems started happening.

**Comment by brian-brazil** [comment]
2.19 requires more virtual memory than previous versions, you need a 64bit machine. 32bit system are generally not supported as we use mmap a lot, if you want to try to get it to work you can but we don't promise anything there as trying to support 32bit systems would cripple things for the vast majority of our users on 64bit systems. I can only suggest looking at Prometheus 1.x, which did not use mmap.

**Comment by gouthamve** [comment]
Hi, we've discussed this in the bug scrub, but this is a limitation of Prometheus on `32bit` systems. We'll update the docs to reflect this and we'll log the warning on startup.


As Brian suggested, it's best to run Prometheus 1.x on 32bit systems.

**Comment by beorn7** [comment]
> I've been running it fine for over 6 months. It's only since upgrading to 2.19 that problems started happening.

2.19 mmap's even more files than 2.18. Which might explain what you see here. But the difference doesn't really make a dent. I'd expect that even your 2.18 setup will run into memory problems once your load increases just a bit.

What the others said here is true, for any reasonably load, you probably want a 64bit architecture. Or try https://github.com/prometheus/prometheus/releases/tag/v1.7.2 indeed. It's quite mature for what it does… (o:

**Comment by clambin** [comment]
Thanks for the advice.   I managed to get prometheus 2.19 stable again by a) reducing the scrape interval for the most often scraped metrics and b) lowering the retention to 7d and using remote storage for the data that I do want to keep longer than that.

For my info: which of these would be responsible for running out of memory? Scrape interval or retention time?  Since the crash occurred during WAL processing, I'm guess it's the scrape interval?

**Comment by brian-brazil** [comment]
I'd expect both to contribute roughly linearly to virtual memory use.

**Comment by mitchellrj** [comment]
I think it would be helpful if the error message also stated how much memory it was trying to allocate. This would help administrators re-scale systems where possible.

**Comment by brian-brazil** [comment]
I don't think that'd be useful. Virtual memory is basically infinite on a 64-bit system so there's nothing to provision, and can't really be extended on a 32-bit system.

**Comment by jarfil** [comment]
Had the same problem. Fixed it by adding a size limit for the storage with `--storage.tsdb.retention.size=500MB`.

Maybe on 32bit systems there could be a default/maximum value for `storage.tsdb.retention.size`, along with the warning.

**Comment by shay-berman** [comment]
@clambin any update on this ticket?

**Comment by clambin** [comment]
@shay-berman haven't had any more issues since I lowered scrape rate & retention period.
