### ISSUE TITLE
ci: make sure promql/parser/generated_parser.y.go is reproducible

### ISSUE THREAD

**Issue by roidelapluie** [prometheus/prometheus#7488]
We should run goyacc in CI to make sure the file promql/parser/generated_parser.y.go matches promql/parser/generated_parser.y.

**Comment by Harkishen-Singh** [comment]
@roidelapluie could you tell why do we need this?

**Comment by roidelapluie** [comment]
To make sure that PR's like #7480 are correct.

**Comment by Harkishen-Singh** [comment]
Will take up this!

**Comment by beorn7** [comment]
Hello from the bug scrub.

This seems still relevant. Unfortunately, the work on #7516 was abandoned. @krajorama committed to have a look if he can quickly revive it.

**Comment by krajorama** [comment]
I see the comment `# Prometheus has switched to GitHub action.` in [.cirleci/config.yml](https://github.com/prometheus/prometheus/blob/main/.circleci/config.yml), so porting the code from #7516 to Github actions. Probably simpler actually.
