### ISSUE TITLE
truncated tcp messages

### ISSUE THREAD

**Issue by miekg** [prometheus/prometheus#749]
Do to a small fubar of mine SkyDNS set the TC bit on  TCP messages. Prometheus does not like/use those for resolving purposes. I think it makes sense to have an extra check to see if the message size is 64K bytes and if the message is smaller, just ignore the TC bit, and use the data inside the message.

Logging such messages still makes sense.

**Comment by miekg** [comment]
This might (also) be an issue in Go DNS, I'll check that too.

**Comment by brian-brazil** [comment]
Is there an update here? Is this something we as a user of the library should have to care about?

**Comment by grobie** [comment]
This doesn't make sense. It should not be Prometheus' task to second-guess whether a DNS server should not have set the truncation bit and ignore it. The DNS spec is pretty clear about the interface.
