### ISSUE TITLE
PromQL  resets()  counting wrong changes

### ISSUE THREAD

**Issue by akshayvijapur** [prometheus/prometheus#7500]
**What did you do?** I tried to find number of times a counter has went down using resets

**What did you expect to see?** I expect that it should return number of times counter has went down

**What did you see instead? Under which circumstances?** It is wrongly counting.

Example :

188 -> 248  = From 188 to 248, The value has increased, But not decreased, But still it is counting as one change.

**Environment**: Linux

* System information:

	insert output of `uname -srm` here 

* Prometheus version:

	insert output of `prometheus --version` here 2.19.2

* Alertmanager version:

	insert output of `alertmanager --version` here (if relevant to the issue)

* Prometheus configuration file:
```
insert configuration here
```

* Alertmanager configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```

**Comment by brian-brazil** [comment]
Can you share the exact input that is going into resets?

**Comment by dennybritz** [comment]
I'm running into this problem as well. For the `some_query`, this is my resets graph that causes `rate` queries to return invalid results.

```
resets(some_query[5m])
```

![image](https://user-images.githubusercontent.com/403133/92269470-833d2c80-eee4-11ea-87ed-5c1bb2cfc2bc.png)

Looking at only `some_query` I see the following increasing values, no decreases:

![image](https://user-images.githubusercontent.com/403133/92269601-cbf4e580-eee4-11ea-97f3-657b6adf571a.png)

The following is the raw data. As you can see, there is nothing decreasing:

```
{"status":"success","data":{"resultType":"matrix","result":[{"metric":{ "secret": "stuff" },"values":[[1599239976.031,"72371"],[1599239976.032,"72371"],[1599240006.031,"78369"],[1599240006.032,"78369"],[1599240036.031,"85360"],[1599240066.031,"90303"],[1599240066.032,"90303"],[1599240096.031,"95269"],[1599240096.032,"95269"],[1599240126.031,"103291"],[1599240126.032,"103291"],[1599240156.031,"109188"],[1599240156.032,"109188"],[1599240186.031,"115143"],[1599240186.032,"115143"],[1599240216.031,"120988"],[1599240216.032,"120988"],[1599240246.032,"123920"]]}]}}
```

Build info:

```

Version | 2.19.2
-- | --
c448ada63d83002e9c1d2c9f84e09f55a61f0ff7
HEAD
root@dd72efe1549d
20200626-09:02:20
go1.14.4

```

**Comment by Harkishen-Singh** [comment]
@akshayvijapur any updates? Maybe, you can send a range query for that particular query via HTTP request and mention the response for better understanding.

**Comment by roidelapluie** [comment]
I am closing this due to lack of feedback.
