### ISSUE TITLE
Image built from Dockerfile is missing frontend assets

### ISSUE THREAD

**Issue by ggpaue** [prometheus/prometheus#7509]
**What did you do?**
Build Prometheus docker image from Dockerfile
**What did you expect to see?**
Normal Prometheus image can be deployed on cluster
**What did you see instead? Under which circumstances?**
`error reading base template: open web/ui/templates/_base.html: no such file or directory`
Looks like assests under `web/ui/templates` are not copied into docker image
I have checked the Dockerfile, seems this path are not copied
**Environment**
kubernetes cluster
* System information:

	insert output of `uname -srm` here

* Prometheus version:

	2.17.1

* Alertmanager version:

	insert output of `alertmanager --version` here (if relevant to the issue)

* Prometheus configuration file:
```
insert configuration here
```

* Alertmanager configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```

**Comment by roidelapluie** [comment]
Related to https://groups.google.com/g/prometheus-developers/c/3XBC6t3BqW0 I guess.

**Comment by roidelapluie** [comment]
Our docker file is not engineered to build Prometheus from the ground up. It requires pre-built frontends and assets.

**Comment by gouthamve** [comment]
I think the info to compile the frontend should be added to `CONTRIBUTING.md` as well. Right now it seems to exist only in the -developers thread above.

**Comment by ggpaue** [comment]
@roidelapluie thanks for the reply, can you share the step to build the frontend?
thanks!

**Comment by sylr** [comment]
You can use this dockerfile to build everything at once https://github.com/sylr/prometheus/blob/v2.19.2%2Bsylr.1/Dockerfile.multi-stage

**Comment by azimjohn** [comment]
#hacktoberfest brought me here, I will be taking care of the issue

**Comment by Clash-ion** [comment]
So a possible fix for this issue is to make a 2-stage dockerfile which copies the assets after it has been created in stage 1. Will this be sufficient? If yes then I am willing to take this issue.

**Comment by Krunal2017** [comment]
I would like to work on this, if it's not taken.

**Comment by Krunal2017** [comment]
As others mentioned, it seems the issue here is that the current Dockerfile expects prebuilt binaries of prometheus & promtool. A multi-stage dockerfile with a stage for building the UI assets, seems the way to solve this. I'll try building the assets with a few docker images, and see what works here.

**Comment by Krunal2017** [comment]
I tried a 3-stage dockerfile to build the nodejs assets & golang assets separately in the first two stages. But it seems to run into this error:
```
web/ui/embed.go:21:3470: pattern static/react/asset-manifest.json.gz: no matching files found
!! command failed: build -o /prometheus/prometheus -ldflags -X github.com/prometheus/common/version.Version=2.47.1 -X github.com/prometheus/common/version.Revision=fe90dcccffec8596ff3901b943aef5e1982172d6 -X github.com/prometheus/common/version.Branch=hackfest-docker -X github.com/prometheus/common/version.BuildUser=root@94d1eb083108 -X github.com/prometheus/common/version.BuildDate=20231015-08:56:55  -extldflags '-static' -a -tags netgo,builtinassets,stringlabels github.com/prometheus/prometheus/cmd/prometheus: exit status 1
make: *** [Makefile.common:200: common-build] Error 1
The command '/bin/sh -c cd /prometheus &&     make common-build' returned a non-zero code: 2
```
Maybe building both the assets in one stage would help get past this.

**Comment by krajorama** [comment]
Hello from the bug scrub: @krajorama  to double check the documented Docker build instructions from the README and close this issue if asserts are there in that procedure.

**Comment by krajorama** [comment]
Following the documented procedure [README.md](https://github.com/prometheus/prometheus/blob/main/README.md#building-the-docker-image)

Check out a new clean copy of prometheus from git, then:

Clean promu from my go path
```
rm ~/go/bin/promu
```

Then the procedure:
```
make promu
promu crossbuild -p linux/amd64
make npm_licenses
make common-docker-amd64
```

Then run 
```
docker run -p 9090:9090 -v path-to-my-stuff/prometheus.yml:/etc/prometheus/prometheus.yml docker.io/prom/prometheus-linux-amd64:main
```

According to [install doc](https://prometheus.io/docs/prometheus/latest/installation/#volumes-bind-mount)

Navigating to localhost:9090 in browser worked and no errors.

As the documented instructions work on main branch, closing this issue.
