### ISSUE TITLE
go build generated prometheus binary doesn't include frontend assets

### ISSUE THREAD

**Issue by ggpaue** [prometheus/prometheus#7517]
**What did you do?**
go build from cmd/prometheus to generate prometheus binary
**What did you expect to see?**
fully worked prometheus binary
**What did you see instead? Under which circumstances?**
the binary is different from the binary built directly from "make build"
it doesn't include frontend assets
error message: error reading base template: open web/ui/templates/_base.html: no such file or directory
**Environment**
kubernetes cluster
* System information:

	insert output of `uname -srm` here

* Prometheus version:

	2.18.1

* Alertmanager version:

	insert output of `alertmanager --version` here (if relevant to the issue)

* Prometheus configuration file:
```
insert configuration here
```

* Alertmanager configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```

**Comment by roidelapluie** [comment]
Answered here: https://groups.google.com/g/prometheus-developers/c/3XBC6t3BqW0
