### ISSUE TITLE
Protected Prometheus (OpenID Auth enaled) can be use as target in federation Prometheus scrape config ??

### ISSUE THREAD

**Issue by chandankashyap19** [prometheus/prometheus#7519]
Hello Guys,

I am stuck at point by doing integration of openid auth enabled prometheus to federation. Let me explain in detail about the configuration and blocker.

My slave Prometheus is openid auth enabled. Whenever, We try to access the prometheus it ask for login authentication and get us IN if authorization get success. Post successful login, prometheus dashboard and its graph can be see.

Federation prometheus is running at different place. Federation prometheus scrape_configs looks like below

scrape_configs:
  - job_name: 'federate'
    scrape_interval: 15s

    honor_labels: true
    metrics_path: '/federate'

    params:
      'match[]':
        - '{job="prometheus"}'
        - '{__name__=~"job:.*"}'

    static_configs:
      - targets:
        - 'prometheus-slave.xyz.com:443'  (my slave prometheus endpoint)

**Issue :**  The target status is DOWN and Status is "server returned HTTP status 403 Forbidden".

I know the error is coming because of federation Prometheus has not getting credential to access slave Prometheus. But, I am not getting anything at federation prometheus where credentials related configuration will be done which allow federation Prometheus to access auth protected slave prometheus.

Suggestion & help need !!!!!!
#FederationPrometheus

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
