### ISSUE TITLE
Continuous delivery to Chocolatey

### ISSUE THREAD

**Issue by eloekset** [prometheus/prometheus#7521]
## Proposal
**Use case. Why is this important?**
Prometheus for Windows is published on Chocolatey, but unfortunately a [very old release is out there](https://chocolatey.org/packages/prometheus).

I can hardly see your build pipeline on CircleCI, but you probably have some release pipeline that pushes docker images based on tags on GitHub? If so, it shouldn't take much effort to push to Chocolatey from the same pipeline?

I can only see build pipelines for the last few master and PR builds.
![image](https://user-images.githubusercontent.com/791721/86601746-ff2cfe00-bfa1-11ea-8584-32f4dfb28fcc.png)

I've done a bit research on how the current Chocolatey package is released, and they use some kind of [automatic update (AU packages)](https://github.com/Tervis-Tumbler/au-packages), but it obviously stopped working a while ago.

**Comment by gouthamve** [comment]
@SuperQ @simonpasquier Do we want to support this? What would it take and how much effort is this?

**Comment by eloekset** [comment]
BTW, Microsoft has a preview out of a new package manager called [winget](https://docs.microsoft.com/en-us/windows/package-manager/). It utilizes GitHub as package source, so it's very easy to add and update packages. 

For instance Notepad++ uses the GitHub releases as source for its binaries. [This is the manifest for one package version](https://github.com/microsoft/winget-pkgs/tree/master/manifests/Notepad%2B%2B/Notepad%2B%2B).

**Comment by krajorama** [comment]
Hello from the bug scrub:  closing as nobody worked on this for 4 years, might not be relevant anymore. Please follow up if you have concrete plans to work on this.

**Comment by SuperQ** [comment]
Agreed, I don't think we have any interest in the community to support Chocolatey. If someone volunteered to add it, we could open this again.
