### ISSUE TITLE
The time required for alert resolve should be customizable

### ISSUE THREAD

**Issue by liuyk0109** [prometheus/prometheus#7527]
**Maybe we should provide a parameter that can be used to set how long the alarm is considered to be recovered?**

We now have a parameter `for`, to set how long the alert will be firing. I think parameters like this are also necessary for resolve.

In my use, i often see some alert between firing->resolved->firing. I think that alerts should be resolved when they were evaluated as **ok** multiple times during a customizable period.

**Comment by logosty** [comment]
i agree

**Comment by brian-brazil** [comment]
This has been proposed and discussed many times before, such as in #4681, and this is not a feature that is planned to be added. Closing as a dupe of #4681.
