### ISSUE TITLE
Out-of-order series during head compaction

### ISSUE THREAD

**Issue by codesome** [prometheus/prometheus#7531]
When there are concurrent appends of new series and head compaction, we could face an error like this
`unexpected error: persist head block: write compaction: add series: out-of-order series added with label set "{n414=\"v414\"}"`

This indicates that there is some race that needs to be fixed. 

It can be reproduced by running this test (Remove the `t.Skip()` before running. Run it multiple times if it doesn't fail in the first attempt.)
https://github.com/prometheus/prometheus/blob/30505a202a4c33ceeb10bfb3ba01e371a2a10906/tsdb/head_test.go#L1879

The root cause is yet to be identified.

(I remember seeing this reported but could not find an issue for that, hence opened a new one)

**Comment by roidelapluie** [comment]
Is that #5617?

**Comment by codesome** [comment]
Looks like it, although I am not sure about the `{}` being out of order. Closing this in favour of that.

**Comment by roidelapluie** [comment]
> Looks like it, although I am not sure about the `{}` being out of order. Closing this in favour of that.

Since then I have added a check and we disallow empty label sets like {}. I guess it was just an occurrence of this bug, with an empty label set
