### ISSUE TITLE
Inconsistency in which keywords are allowed as metric names

### ISSUE THREAD

**Issue by juliusv** [prometheus/prometheus#7532]
The following all result in an error when trying to use them as a top-level expression / metric name:

* `bool`
* `group_right`
* `group_left`
* `on`
* `ignoring`
* `without`
* `on`
* `offset`

However, `by` evaluates just fine as a metric name. It seems to me it should be treated like the other keywords as well? Especially it should be treated the same as `without`, since they are both the same type of aggregation modifier.

Just looking briefly at [`lexKeywordOrIdentifier()`](https://github.com/prometheus/prometheus/blob/30505a202a4c33ceeb10bfb3ba01e371a2a10906/promql/parser/lex.go#L750-L776), the lexer seems fine, but https://github.com/prometheus/prometheus/blob/master/promql/parser/generated_parser.y#L539 explicitly allows some keywords also as metric identifiers, but not others. What behavior do we want?

**Comment by juliusv** [comment]
cc @slrtbtfs

**Comment by slrtbtfs** [comment]
This was introduced in  https://github.com/prometheus/prometheus/pull/6933 .

Allowing more keywords in that position would create conflicts in the yacc grammar.

IIRC the reason it was handled this way, is that PromQL doesn't really have the concept of reserved keywords. For example in this expression, `<placeholder>` could be replaced  by any keyword:

```
sum by (<placeholder>) (foo)
```

**Comment by juliusv** [comment]
I see, thanks! The docs introduced in the linked PR do not mention `without`, and it's used grammatically the same as `by`, so probably at least making those two behave the same would be possible?

**Comment by slrtbtfs** [comment]
I've just checked that. Adding without wouldn't create new conflicts.

**Comment by slrtbtfs** [comment]
@juliusv  Can this issue be closed or are there still things to be clarified?

**Comment by juliusv** [comment]
I think it can be closed.
