### ISSUE TITLE
Support Alibaba's Nacos service discovery

### ISSUE THREAD

**Issue by javaDer** [prometheus/prometheus#7539]
## Proposal
**Use case. Why is this important?**

*“Nice to have” is not a good use case. :)*

**Comment by javaDer** [comment]
I got the answer
 TKS

**Comment by roidelapluie** [comment]
This is the first time this service discovery is requested. Let's keep this open for a few time to  see if there is a community interest in it. Then, it would need a sponsor from someone from the prometheus team and a pull request, as described in our procedures.

**Comment by TsingLiang** [comment]
I have the interest to support Nacos. Can I commit a pull request?

**Comment by roidelapluie** [comment]
Nacos raises many questions, in particular:

- How redundant is it with the Kubernetes SD?
- What added values is there over DNS SD?
- Is there a go client? If yes, does it have kubernetes as dependency? (I am not willing to have 2 SD depending on kubernetes)

I could sponsor that SD, but not now as we have multiple SD in running-in period. Once the new SD's become more mature are we have conclusive answers from above, that _could_ be an option.

**Comment by roidelapluie** [comment]
We could now explore this. Could you look at the questions previously posted?

**Comment by mark4z** [comment]
Here is the go client for nacos

**Comment by birkh8792** [comment]
simple implementation，please see [nacos](https://github.com/birkh8792/prometheus/commits/feature-nacos-lic)

**Comment by xmuyoucai** [comment]
i need

**Comment by yuzhichang** [comment]
I think it's better that Nacos provides [http sd](https://prometheus.io/docs/prometheus/latest/http_sd/), Promtheus needs change nothing.

**Comment by hujun-w-2** [comment]
a good idea

**Comment by vividfish** [comment]
did http SD support any authorization? i tryed set bearer_token or basic_auth,but did not work

**Comment by LeviHarrison** [comment]
Looks like HTTP SD support was added in version 2.2.0 of Nacos: https://nacos.io/zh-cn/blog/2.2.0-release.html, so I think this issue is resolved.
