### ISSUE TITLE
Support Kubernetes EndpointSlice

### ISSUE THREAD

**Issue by howardjohn** [prometheus/prometheus#7572]
# Proposal
**Use case. Why is this important?**

Kubernetes has added a new beta API, [EndpointSlice](https://kubernetes.io/docs/concepts/services-networking/endpoint-slices/). The intent here is to be a replacement for Endpoint, with some scalability and other concerns addressed. It should be a drop in replacement for Endpoints, and will likely GA soon (I am not on the team, so not sure the exact timeline).

For some period of time (potentially very long time), clusters are likely to have both endpoints and endpointslice present on the cluster, so things will not be too bad for Prometheus use case. However:

* There is a possibility that at some point in the future Endpoints will be truncated to X number of endpoints, meaning some pods will be missing scraping
* There may be clusters that disable Endpoints and use only EndpointSlice
* Users, or other controllers, may create EndpointSlices but not Endpoints
* In some distant future, Endpoint may be fully deprecated. However, deprecated a GA API has no precedence so its pretty murky territory.

The request here would be to add an option to the Kubernetes service discovery to support reading endpoint slices instead of Endpoints.

cc @robscott @douglas-reid

**Comment by roidelapluie** [comment]
Work is in progress at #6838

**Comment by roidelapluie** [comment]
You have a lot of claims in your issue, like `There is a possibility that at some point in the future Endpoints will be truncated to X number of endpoints, meaning some pods will be missing scraping`, do you have sources for that? Thanks.

**Comment by roidelapluie** [comment]
Note that our tests show that because of the different RBAC rules it is not a drop-in replacement, as it is not transparent for users.

**Comment by howardjohn** [comment]
Thanks for the link, I missed that one. Most of the comments are from @robscott who is an owner for EndpointSlice in k8s - I am just a user. I'll let him add any sources if they are available

**Comment by robscott** [comment]
Hey @roidelapluie, the current plan (which may get pushed back) would involve adding a warning to Endpoints that exceeded a threshold (1000 IPs) in 1.20 and then truncating those Endpoints in 1.21. Here's the relevant part of the KEP: https://github.com/kubernetes/enhancements/blob/master/keps/sig-network/20190603-endpointslices/README.md#roll-out-plan.

**Comment by roidelapluie** [comment]
Thank you! I guess we will also use `endpoints.kubernetes.io/over-capacity` to issue warnings to our users.

**Comment by howardjohn** [comment]
I think this is done now since https://github.com/prometheus/prometheus/pull/6838 is merged or is there other work to track?

**Comment by roidelapluie** [comment]
We need to add the warnings for the users when overcapacity labels are
present.

Le jeu. 10 sept. 2020 à 05:01, John Howard <notifications@github.com> a
écrit :

**Comment by beorn7** [comment]
@brancz Is this perhaps a good issue for Hacktoberfest to add this one remaining feature?

**Comment by brancz** [comment]
@beorn7 yes!

**Comment by beorn7** [comment]
OK, added label. Hacktoberfest hackers (and hacksen, if you allow this weird Germanicism), note that here is just one piece of the puzzle missing. Might be easy points… (o:

**Comment by katsadim** [comment]
Hello thinking of grabbing thisone (hacktoberfest ftw). 

Is it as easy as detecting the presence of `endpoints.kubernetes.io/over-capacity` label and then `level.Warn().log`ging it? Or something more elaborate that i am missing?

**Comment by brancz** [comment]
Looks like the feature, documentation, and overcapacity warning are all implemented. So I'm closing this! :tada:
