### ISSUE TITLE
Generalise an interface for retention in TSDB

### ISSUE THREAD

**Issue by codesome** [prometheus/prometheus#7576]
The idea is to make the retention decisions via an interface that also allows looking at each block. With this, the time based and size based retention logic would be a single interface for Prometheus and allow external users to inject different interfaces as retention filters.

This is particularly helpful for Cortex and Thanos who don't want some blocks to be deleted based on some conditions.

/cc @pracucci @pstibrany @bwplotka @brancz

**Comment by bwplotka** [comment]
Either generalization or API for deleting blocks I guess.

**Comment by pracucci** [comment]
> API for deleting blocks I guess

Interesting approach, but how would that work? If a block is not "ready to be deleted" (because not shipped to the long-term storage yet) how should it work? The API fails and TSDB continuously retry? I would love to hear more thoughts on this 🙏

**Comment by codesome** [comment]
Even with an API, you would need some control over the retention policy to _not delete_ blocks.

**Comment by brancz** [comment]
I tend to agree that an pluggable interface would be best here. Refactoring shouldn't be too invasive to make this possible I think.
