### ISSUE TITLE
Support dropping metrics after recording; or aggregating during scraping

### ISSUE THREAD

**Issue by franck102** [prometheus/prometheus#7582]
## Proposal
Support either 
- aggregating while scraping: preferred
- or dropping metrics after recording (short-term cost of ingesting in tsdb, but save on long-term cost)

I understand that a full-fledged recording rule while scraping probably goes against the design. What about a poor man's solution: aggregate metrics that are duplicate after relabeling, using hardcoded predefined semantics (e.g. sum for counters, avg for gauges, not supported for histograms...)

**Use case. Why is this important?**
Many metrics originate from sources over which Prometheus users have no control (kubelet, node-exporter, kube-state-metrics, metrics-server, istio system); plus the high cardinality of many of those metrics may be justified for a small system, but become unmanageable in a larger system.

Commonly aggregates over those metrics would still be extremely useful for alerting - e.g. response times across all endpoints/channels, cpu_usage over a few select cpu states...

The only option today to keep prometheus costs in check is to completely drop those metrics.

**Comment by brian-brazil** [comment]
Thanks for your suggestion, this was previously covered in #6352. The short version is that in order to use the data you have to pay the costs of ingesting it, and once it's ingested there's no real performance benefit to dropping it.

> I understand that a full-fledged recording rule while scraping probably goes against the design

This is #394, though slightly different.

**Comment by franck102** [comment]
The suggestion to aggregates metrics that conflict after relabeling is not covered in the previous issue, where you stated instead:
"This doesn't work out, we need the data in the tsdb to be usable in rules at which point the cost is already paid. Recording rules are also independent of scrapes."

Aggregating at scrape time would not involve rules.

**Comment by brian-brazil** [comment]
You need some form of math to do aggregation, and practically speaking that means PromQL. If you want to e.g. aggregate counters that means first using rate(), which requires history for correctness and thus ingestion.

If a target is exposing data with too high cardinality and you wish to drop a label, the best approach is to get the target to not have that label. So I'd suggest filing issues against the relevant projects.

**Comment by franck102** [comment]
That is a useless suggestion, the obviously efficient approach is to have the scraping side - Prometheus - pick, aggregate and choose amongst the metrics exposed by sources; rather than expecting every source on the planet to provide fine-grained configurability as to what they expose; and every sysadmin to go configure 20 sources... that they often don't even control.

Anyway... this and similar answers just comforts me in the fact that we need to find an alternative to Prometheus.
