### ISSUE TITLE
Stop processing rule group after a rule is failing

### ISSUE THREAD

**Issue by roidelapluie** [prometheus/prometheus#7591]
**What did you do?**

Have 2 rules in a group. The first one fails.

**What did you expect to see?**

The group stops executing after the failing rule.

**What did you see instead? Under which circumstances?**

All the queries are running, even after the failing one.

![rg](https://user-images.githubusercontent.com/291750/87725912-6c206f00-c7be-11ea-9539-fab110015bd5.png)

This is probably breaking for users, so it would be a prometheus 3.x thing. Or maybe it could be overridable by a rule group option: on_error: continue

**Comment by roidelapluie** [comment]
Thinking a bit more:

- Not sure if it makes sense if we do not roll back the rules executed before
- we can not commit the rules all together or use a single appender because the rules need to be able to read the result from previous iterations

**Comment by brian-brazil** [comment]
I think the current behaviour is fine, and should not even configurable otherwise. Consider that single rule with no dependencies on it started running into the sample or time limits for queries, we shouldn't break all subsequent alerts/rules due to this.

**Comment by roidelapluie** [comment]
Yes I guess we have lots of people not caring about those dependencies. Thanks.
