### ISSUE TITLE
cannot load github.com/go-sql-driver/mysql: open /home/gopath/src/github.com/prometheus/prometheus/vendor/github.com/go-sql-driver/mysql: no such file or directory

### ISSUE THREAD

**Issue by baiyunsong** [prometheus/prometheus#7597]
I added a package _ "github.com/go-sql-driver/mysql", make build will show that it cannot be obtained, what is the reason?

**Comment by roidelapluie** [comment]
What are you trying to achieve?

**Comment by baiyunsong** [comment]
I need prometheus to read the data in the database，the rules are stored in the database
