### ISSUE TITLE
level=error ts=2020-07-15T19:52:49.331Z caller=compact.go:538 component=tsdb msg="removed tmp folder after failed compaction" err="unlinkat /prometheus/data/01EDA0JSP250R6RYATTC0939FX.tmp: directory not empty"

### ISSUE THREAD

**Issue by prashantnitt07** [prometheus/prometheus#7601]
### **I am getting  Prometheus pods log and getting disk space  in /promethous 

****Prom Version : 2.18** 

**NAS mount point : /promethous****** 

r: sync dir: sync /prometheus/data/01EDA0GYRVWMZBMDSNYG4YKWKC.tmp: invalid argument"

level=error ts=2020-07-15T19:52:49.331Z caller=compact.go:538 component=tsdb msg="removed tmp folder after failed compaction" err="unlinkat /prometheus/data/01EDA0JSP250R6RYATTC0939FX.tmp: directory not empty"

level=error ts=2020-07-15T19:52:49.331Z caller=db.go:667 component=tsdb msg="compaction failed" err="persist head block: open index writer: sync dir: sync /prometheus/data/01EDA0JSP250R6RYATTC0939FX.tmp: invalid argument"

level=error ts=2020-07-15T19:53:49.559Z caller=compact.go:538 component=tsdb msg="removed tmp folder after failed compaction" err="unlinkat /prometheus/data/01EDA0MMGK3413B3DKQ0AB0V8C.tmp: directory not empty"

level=error ts=2020-07-15T19:53:49.559Z caller=db.go:667 component=tsdb msg="compaction failed" err="persist head block: open index writer: sync dir: sync /prometheus/data/01EDA0MMGK3413B3DKQ0AB0V8C.tmp: invalid argument"

level=error ts=2020-07-15T19:54:49.847Z caller=compact.go:538 component=tsdb msg="removed tmp folder after failed compaction" err="unlinkat /prometheus/data/01EDA0PFAQ4SK430JMPG3XKP0M.tmp: directory not empty"

level=error ts=2020-07-15T19:54:49.847Z caller=db.go:667 component=tsdb msg="compaction failed" err="persist head block: open index writer: sync dir: sync /prometheus/data/01EDA0PFAQ4SK430JMPG3XKP0M.tmp: invalid argument"

level=error ts=2020-07-15T19:55:50.084Z caller=compact.go:538 component=tsdb msg="removed tmp folder after failed compaction" err="unlinkat /prometheus/data/01EDA0RA6Q67SKFYGH4JCHVRQ2.tmp: directory not empty"

level=error ts=2020-07-15T19:55:50.084Z caller=db.go:667 component=tsdb msg="compaction failed" err="persist head block: open index writer: sync dir: sync /prometheus/data/01EDA0RA6Q67SKFYGH4JCHVRQ2.tmp: invalid argument"

level=error ts=2020-07-15T19:56:50.357Z caller=compact.go:538 component=tsdb msg="removed tmp folder after failed compaction" err="unlinkat /prometheus/data/01EDA0T514XZY8BSXE5QYH75YX.tmp: directory not empty"

level=error ts=2020-07-15T19:56:50.357Z caller=db.go:667 component=tsdb msg="compaction failed" err="persist head block: open index writer: sync dir: sync /prometheus/data/01EDA0T514XZY8BSXE5QYH75YX.tmp: invalid argument"

level=error ts=2020-07-15T19:57:50.580Z caller=compact.go:538 component=tsdb msg="removed tmp folder after failed compaction" err="unlinkat /prometheus/data/01EDA0VZWN0PEBW4YK832G6KAF.tmp: directory not empty"

level=error ts=2020-07-15T19:57:50.580Z caller=db.go:667 component=tsdb msg="compaction failed" err="persist head block: open index writer: sync dir: sync /prometheus/data/01EDA0VZWN0PEBW4YK832G6KAF.tmp: invalid argument"

level=error ts=2020-07-15T19:58:50.800Z caller=compact.go:538 component=tsdb msg="removed tmp folder after failed compaction" err="unlinkat /prometheus/data/01EDA0XTPMVVYD93XARQXYESWC.tmp: directory not empty"

level=error ts=2020-07-15T19:58:50.800Z caller=db.go:667 component=tsdb msg="compaction failed" err="persist head block: open index writer: sync dir: sync /prometheus/data/01EDA0XTPMVVYD93XARQXYESWC.tmp: invalid argument"

level=error ts=2020-07-15T19:59:51.102Z caller=compact.go:538 component=tsdb msg="removed tmp folder after failed compaction" err="unlinkat /prometheus/data/01EDA0ZNGGVP09HNQZZ341PF34.tmp: directory not empty"

level=error ts=2020-07-15T19:59:51.102Z caller=db.go:667 component=tsdb msg="compaction failed" err="persist head block: open index writer: sync dir: sync /prometheus/data/01EDA0ZNGGVP09HNQZZ341PF34.tmp: invalid argument"

level=error ts=2020-07-15T20:00:51.316Z caller=compact.go:538 component=tsdb msg="removed tmp folder after failed compaction" err="unlinkat /prometheus/data/01EDA11GCYAGHESG5Y3NQTKV3P.tmp: directory not empty"
level=error ts=2020-07-15T20:00:51.316Z caller=db.go:667 component=tsdb msg="compaction failed" err="persist head block: open index writer: sync dir: sync /prometheus/data/01EDA11GCYAGHESG5Y3NQTKV3P.tmp: invalid argumen

**Comment by brian-brazil** [comment]
> NAS mount point : /promethous

Are you using NFS?

**Comment by prashantnitt07** [comment]
Azure windows storage NAS and mounted with Linux server
please confirm Azure storage is support Prometheus TSDB

**Comment by prashantnitt07** [comment]
### Thanks for support @brian-brazil 

I have used local storage instead Azure NAS storage and not getting any error for version 2.19.3.

promethous pod deployment is working fine with local storage
