### ISSUE TITLE
2.20 release notes should contain an explicit note about compression

### ISSUE THREAD

**Issue by roidelapluie** [prometheus/prometheus#7612]
We should have an explicit note about the wal compression on top of the release notes. That is because users who will upgrade to 2.20 will not be able to downgrade below 2.11 without cleaning their wal.

Also,
- Is it possible to downgrade to 2.19 again without the wal.compressed option?
- What happens with mixed wals : compressed / uncompressed?

cc @beorn7

**Comment by beorn7** [comment]
I was planning to explain that in the announcement mail, assuming that we don't give that detailed level of explanation in CHANGELOG.md. However, I just checked, and we have done that now and then, so I'm happy to add a one-sentence explanation about the change.

In my understanding, every Prometheus release 2.11+ will be able to read a compressed WAL. I don't know if Prometheus will then continue what it has found on disk, or if it will do what the command line flag says, possible creating a mixed WAL. @codesome should know.

**Comment by roidelapluie** [comment]
Note: The announcement mailing list has only a few hundreds subscribers, where I expect many more people to read the changelog.

**Comment by codesome** [comment]
The WAL record header has the information if the record is compressed. So, as WAL compression was introduced in 2.11, if you upgrade to 2.20, you can safely downgrade up to 2.11 and there is _no need to set the compressed flag_ to decode the compressed record. But yes, it would be good to mention you cannot downgrade below 2.11 without data loss if you upgrade to 2.20.

**Comment by codesome** [comment]
> possible creating a mixed WAL

There can be mixed WAL when you switch between compressed and non-compressed WAL, which is fine, everything is taken care of by the record header.

**Comment by beorn7** [comment]
Thanks @codesome . I'll add a note to the upcoming 2.20.0-rc.1 CHANGELOG entry accordingly.
