### ISSUE TITLE
promql: Fix select hints when subqueries are used.

### ISSUE THREAD

**Issue by bwplotka** [prometheus/prometheus#7630]
We can do much better in terms of hinting e.g step that will be used when subqueries are used. Especially for other users of PromQL we can detect what resolution to fetch based on this.

See TODO: https://github.com/prometheus/prometheus/blob/ce1db029095e3246591fd157b3ccddce01313019/promql/engine.go#L656

**Comment by roidelapluie** [comment]
This is not exactly clear to me.

**Comment by brancz** [comment]
The implementation makes it a lot more clear https://github.com/prometheus/prometheus/pull/7636

**Comment by gastonqiu** [comment]
I am interested in this issue but I am not so familiar with this project. Could you give me more information about this issue so that I can help on it?

**Comment by Harkishen-Singh** [comment]
Not sure, but I think this involves updating querier from the tsdb as well, not just promql. 
@bwplotka

**Comment by anukul** [comment]
Hi, I would like to try this!

I'm looking in [`populateSeries`](https://github.com/prometheus/prometheus/blob/release-2.21/promql/engine.go#L620) to understand how hints are derived at the moment, and will start by finding / adding cases in [`TestSelectHintsSetCorrectly`](https://github.com/prometheus/prometheus/blob/release-2.21/promql/engine_test.go#L246) where they can be improved further for subqueries.

**Comment by GiedriusS** [comment]
https://github.com/prometheus/prometheus/pull/11163 I think we can close this now with this merged? @bwplotka :thinking:
