### ISSUE TITLE
Staleness markers not added when series are deleted

### ISSUE THREAD

**Issue by sandeepsukhani** [prometheus/prometheus#7648]
**What did you do?**
Deleted metric `x` from time `t1` to `t2`.

**What did you expect to see?**
No samples for the whole interval of deleted series being returned for query response.
While this is due to look back period feature of promql engine, this could be solved by adding staleness markers at the beginning of deleted time range.

**What did you see instead? Under which circumstances?**
Samples were being returned for time interval `t1` to `t1`+<5mins> when instant queries without range selector and range queries were done. This was not happening when doing instant queries with range selector.

**Environment**

* System information:
	Linux 5.4.0-40-generic x86_64

* Prometheus version:
	Latest master branch.

* Prometheus configuration file:
	Default config.

cc @tomwilkie @gouthamve

**Comment by brian-brazil** [comment]
This behaviour is correct. It would be very unexpected that deleting data would also add data (which'd in itself present a non-trivial technical challenge), and that'd also prevent it removing the entries from the index.

**Comment by roidelapluie** [comment]
I agree with Brian, when deleting data from tsdb, I would not expect stale markers to be added, because we would need to keep them forever. If I delete 2M timeseries from an app , I don't want 2M stale markers.

**Comment by codesome** [comment]
In the bug scrub we decided that the current behavior is fine for the reasons above. Another reason is, TSDB does not know about the staleness, hence it's not easy to keep track in Prometheus and it's inefficent. Hence closing it for now.
