### ISSUE TITLE
PromQL: provide more efficient way to "join" metric in query

### ISSUE THREAD

**Issue by Betula-L** [prometheus/prometheus#7649]
### Proposal
**Use case. Why is this important?**

Currently, PromQL provide keyword `group_left` to join two metrics, for example 
```
job:memory_usage_percent{instance_name=~".*"} * on(instance_name) group_right(app) instance_app_relation{app="test.db.db"}
```
This queries for select all memory usage of app test.db.db.

Assume that 
1.`job:memory_usage_percent{instance_name=~".*"}` has 10k samples
2.`instance_app_relation{app="test.db.db"}` has no data,

the result of this "join" should be no data.

However, prometheus need **prefetch both all data** of
1. `job:memory_usage_percent{instance_name=~".*"}` (10k samples)
2. `instance_app_relation{app="test.db.db"}` (0 samples)

before "join" metric now even though `instance_app_relation{app="test.db.db"}` has no data now.

https://github.com/prometheus/prometheus/blob/610b622520b7350cef6ad874f5f4154101771278/promql/engine.go#L1264

That is not such efficient anyway.

**Maybe solution**

support "Nested Loop Join" like other sql-like system.

**Comment by roidelapluie** [comment]
That would require a really really huge refactoring.

**Comment by brian-brazil** [comment]
> support "Nested Loop Join" like other sql-like system.

This won't work, we have no idea what a selector might return from remote read and we also want to batch up those calls for both semantic and performance reasons. The data sizes here are also small, and this wouldn't make much of a difference I expect.

**Comment by Betula-L** [comment]
> The data sizes here are also small, and this wouldn't make much of a difference I expect.

10k is just an example. 

It impacts so much when we use this sql as alert rule (about 100K rules). For each evaluation, we need go though all samples of job:memory_usage_percent.

99 percent of `innerEval` time increased from 4~5ms to 60ms.

**Comment by roidelapluie** [comment]
Thanks for the example.

It probably means something about your alert.

I would not like an alerting rule to take 2ms, but when there is an incent, it takes 5 seconds and all the CPU that goes with it.

**Comment by brian-brazil** [comment]
Yeah, this looks like something to optimise at the PromQL and metric level rather than trying to micro-optimise the implementation in a way that can blow up on you.

**Comment by Betula-L** [comment]
> Yeah, this looks like something to optimise at the PromQL and metric level rather than trying to micro-optimise the implementation in a way that can blow up on you.

Thanks for your suggestion. I would consider other way to fix it.

The background is that, we manages 50k+ machine and thousands of micro-apps.
For different apps, we need provider a way to adjust threshold of alert rule. For example, app A is sensitive for memory usage, but the others is not.

The old version of alert rules are like that 
`
job:memory_usage_percent{instance_name=~"^instance_A$|^instance_B$...."}  > 90 (for app X)
job:memory_usage_percent{instance_name=~"^instance_C$...."}  > 80 (for app Y)
`
those PromQL spends over 30s if the number of containers for one app is larger than 10000.

The join PromQL performs much better than `the old version` PromQL for app with huge instances/
```
job:memory_usage_percent{instance_name=~".*"} * on(instance_name) group_right(app) instance_app_relation{app="test.db.db"}
```

**Comment by roidelapluie** [comment]
instance_name=~"^instance_A$|^instance_B$...."

I think that adding ^ and $ **prevents** some optimization on our side. Regexes are anchored by default.

**Comment by roidelapluie** [comment]
https://github.com/prometheus/prometheus/issues/2651 for context.

**Comment by brian-brazil** [comment]
> The old version of alert rules are like that

That's inefficient, you want to do things in as few rules as possible generally. See https://www.robustperception.io/using-time-series-as-alert-thresholds for how to better approach this.

I'd also note that filtering a job-level metric on instance label is weird. A metric with a job: prefix should not have an instance label.

**Comment by Betula-L** [comment]
> That's inefficient, you want to do things in as few rules as possible generally. See https://www.robustperception.io/using-time-series-as-alert-thresholds for how to better approach this.

Amazing!!! I'm sure it's the exact approach fo me. Thank you!

**Comment by brian-brazil** [comment]
Great!
