### ISSUE TITLE
Concurrent sorting

### ISSUE THREAD

**Issue by jfcg** [prometheus/prometheus#7665]
__Proposal:__
Replacing standard library's sort with a concurrent sorting library like [sorty](https://github.com/jfcg/sorty).
Note: I am the author of sorty.

__Current behavior:__
standard sort is not concurrent and runs in a single goroutine. This is very slow.
Also `sort.Interface` is slower than sorty's `lesswap()` as a way to access generic collections.

__Desired behavior:__
As a time series database, Prometheus can benefit a lot from concurrent sorting (with sorty or one of alternative libraries.)

__Alternatives considered:__
See the benchmarks in sorty readme.

__Use case:__
I have inspected Prometheus code: standard sort is heavily used. sorty can cover all of it except calls to Stable().

**Comment by roidelapluie** [comment]
Thank you. My first remark is that that third party component is not by default approved to be used in CNCF, because it is MPL: https://github.com/cncf/foundation/blob/master/allowed-third-party-license-policy.md

**Comment by jfcg** [comment]
Hi,
Is there a spesific reason that [MPL](https://www.mozilla.org/en-US/MPL/2.0/FAQ/) is out of the [Allowlist](https://github.com/cncf/foundation/blob/master/allowed-third-party-license-policy.md)?
Afaik it is an [OSI](https://opensource.org/licenses) approved license from Mozilla, and it is open source/closed source/commercial etc. friendly.

opened an [issue](https://github.com/cncf/foundation/issues/104) at cncf just in case.
Thanks..

**Comment by roidelapluie** [comment]
I have no idea.

Note that there are MPL-Software in the exception list: https://github.com/cncf/foundation/blob/master/license-exceptions/cncf-exceptions-2019-11-01.json ; but that would require extra work.

I also have no strong opinion about your proposal, I will let our tsdb experts reply.

**Comment by brian-brazil** [comment]
PromQL using more than one core per query is undesirable, as it makes resource usage of the server unpredictable and will cause CPU spikes. We also only use sorting with relatively small data sizes and it's only a small part of evaluation, so any benefits are likely minimal.

**Comment by jfcg** [comment]
biggest advantage realizes with big data sets, and limitation of one core per query makes it unfeasible, so closing.
