### ISSUE TITLE
CI: Go routine leak in TSDB test

### ISSUE THREAD

**Issue by roidelapluie** [prometheus/prometheus#7672]
```
goleak: Errors on successful test run: found unexpected goroutines:
[Goroutine 15500 in state chan send, with github.com/prometheus/prometheus/tsdb.(*SegmentWAL).cut.func2 on top of the stack:
goroutine 15500 [chan send]:
github.com/prometheus/prometheus/tsdb.(*SegmentWAL).cut.func2(0xc0000be630)
	/home/circleci/project/tsdb/wal.go:599 +0xc0
created by github.com/prometheus/prometheus/tsdb.(*SegmentWAL).cut
	/home/circleci/project/tsdb/wal.go:598 +0x160
]
FAIL	github.com/prometheus/prometheus/tsdb	172.643s
```

This error happens sometimes in CI

**Comment by Mic92** [comment]
Also happens on our hydra aarch64 builder where we test with high concurrency: https://hydra.nixos.org/build/134536536/nixlog/3

**Comment by delroth** [comment]
I hit this today when building Prometheus, so as of 2.27.1 this is still randomly occurring.

**Comment by juliusv** [comment]
I just got this as well. I'm going to change the priority of this from P3 to at least P2, because broken tests cause grief for PR authors + reviewers.

**Comment by roidelapluie** [comment]
We could ignore this in CI for now (add an exception) while keeping this issue open.

**Comment by codesome** [comment]
I think https://github.com/prometheus/prometheus/pull/10056 closes this issue. We can re-open if we face it again.
