### ISSUE TITLE
time="2020-07-20T06:26:36Z" level=error msg="Error opening memory series storage: sync /prometheus/labelpair_to_fingerprints: invalid argument" source="main.go:192"

### ISSUE THREAD

**Issue by prashantnitt07** [prometheus/prometheus#7677]
Promethus version : 1.8.2

Linux machine

using Azure NAS file and mounted in linux  . can support azure NAS

**Comment by codesome** [comment]
`/prometheus/labelpair_to_fingerprints` does not seem familiar. Are you actually using v1.8.2 or did you mistype it for v2.8.2? (but I don't see a v2.8.2)

**Comment by roidelapluie** [comment]
We have looked at this during our bug scrub. NFS is not a supported filesystem for Prometheus, which would explain your error. We also recommend you to upgrade to Prometheus 2.x: https://prometheus.io/docs/prometheus/latest/migration/
