### ISSUE TITLE
Send notification using prometheus and Alertmanager

### ISSUE THREAD

**Issue by deepak2312** [prometheus/prometheus#7682]
I have setting up Prometheus to generate alerts and alert manager  to send notification of the alerts through gmail.

prometheus, version 2.16.0 (branch: non-git, revision: non-git)
  build user:       builder@8e285083fec8
  build date:       20200225-12:29:27
  go version:       go1.13.7

alertmanager, version 0.20.0 (branch: non-git, revision: non-git)
  build user:       builder@ffa94ca89d60
  build date:       20200414-16:38:10
  go version:       go1.13.8

**prometheus.yml :**

global:
  scrape_interval: 1m
  scrape_timeout: 10s
  evaluation_interval: 1m
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - 127.0.0.1:9093
    scheme: http
    path_prefix: /alertmanager/
    api_version: v2
  - static_configs:
    - targets:
      - 10.168.3.51
    scheme: http
    path_prefix: /alertmanager/
    api_version: v2
rule_files:
- /srv/prometheus/rules/*.yml

**alertmanager.yml**

global:
 resolve_timeout: 1m

route:
 receiver: 'gmail-notifications'

receivers:
- name: 'gmail-notifications'
 email_configs:
 - to: demo@gmail.com
   from: monitor@gmail.com
   smarthost: smtp.gmail.com:587
   auth_username: monitor@gmail.com
   auth_identity: monitor@gmail.com
   auth_password: **********
   send_resolved: true

Alerts is being fired by Prometheus and alert manager dashboard shown active alert. But alert notification is not being sent on email.

I receive following  error in prometheus.log

level=info ts=2020-07-28T10:15:27.136Z caller=main.go:677 msg="TSDB started"
level=info ts=2020-07-28T10:15:27.136Z caller=main.go:747 msg="Loading configuration file" filename=/etc/prometheus.yml
level=info ts=2020-07-28T10:15:27.138Z caller=main.go:775 msg="Completed loading of configuration file" filename=/etc/prometheus.yml
level=info ts=2020-07-28T10:15:27.138Z caller=main.go:630 msg="Server is ready to receive web requests."
level=error ts=2020-07-28T10:17:19.257Z caller=notifier.go:524 component=notifier alertmanager=http://10.168.3.51/alertmanager/api/v2/alerts count=2 msg="Error sending alert" err="bad response status 401 Unauthorized"

I don't seem to get where we should add credential and in which file

**Comment by roidelapluie** [comment]
Thanks for your report. It looks as if this is actually a question about usage and not development.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
