### ISSUE TITLE
Format chunks number on 8 characters instead of 6 (or more?)

### ISSUE THREAD

**Issue by roidelapluie** [prometheus/prometheus#7694]
Should we encode chunks segments file names on 8 characters instead of 6, now that we will ever ever-increasing chunks numbers with the head_chunks?

We already have 8 characters for the checkpoints.

**Comment by roidelapluie** [comment]
$ tree data/chunks_head/
data/chunks_head/
└── **000002**

**Comment by brian-brazil** [comment]
As long as we're handling increased numbers of digits correctly, it doesn't matter too much.

**Comment by roidelapluie** [comment]
We need to check if we don't do a simple sort() then.

**Comment by codesome** [comment]
Number of characters is not a problem as the printing won't limit it to 6 if it goes beyond, the sorting needs to be fixed it if is not taking the actual number. But from what I see, the sorting is fine https://github.com/prometheus/prometheus/blob/3c5ff27959fa7a0361b955d52b228f6c7b073246/tsdb/wal/wal.go#L767-L789

**Comment by roidelapluie** [comment]
Thanks!
