### ISSUE TITLE
Use the actually used disk space for retention.size calculation.

### ISSUE THREAD

**Issue by sezuan** [prometheus/prometheus#7698]
As far as I understand the code correctly, the size stored in the header of the on disk data files is used to calculate the storage size of the database. This leads to an issue when using a compressed filesystem like ZFS.
I enabled size-based retention with a limit that was greater than the required disk space, but lower than the true data size and Prometheus started to drop blocks.

In my opinion,  it would be better to use the disk space actually used, as this corresponds to the users' expectations.

**Comment by johncming** [comment]
Another option could be that save block size into the block meta file.  The value of block size still uses bytes in memory.

**Comment by roidelapluie** [comment]
We have looked at this during our bug scrub and this is something out of TSDB scope. We can't support filesystem specific file sizes and compression / deduplication mechanisms. We just use the standard filesystem sizes.
