### ISSUE TITLE
Metric for Prometheus startup time

### ISSUE THREAD

**Issue by ali-sattari** [prometheus/prometheus#7703]
## Proposal
When running large instances of Prometheus, startup time becomes a concern, even with many improvements done in recent versions instances can take 10m or more to load WAL and become ready/start scraping. Yet there is no metric to record this. Having it as a metric can help to see the effect of changes, optimizations, or environment growth and act on it.
I tried to calculate it somehow out of container_creation_time and container_ready metrics in K8S but wasn't successful.

**Comment by max-neverov** [comment]
hi, i'd like to work on this
