### ISSUE TITLE
Different file permission in code

### ISSUE THREAD

**Issue by johncming** [prometheus/prometheus#7717]
**What did you do?**

Review code, I saw different file permission in the repository, mostly is `0644` or `0666`

**What did you expect to see?**

File permission should mostly be consistent for some reason . `0644` is a common choice, for example safety .

The circumstance of using `0666` looks like rarely.

**What did you see instead? Under which circumstances?**

There are at least two values for file permission.

1. `0644`
```
cmd/promtool/archive.go
24:const filePerm = 0644

tsdb/fileutil/flock_solaris.go
48:	f, err := os.OpenFile(fileName, os.O_RDWR|os.O_CREATE, 0644)
```

2. `0666`

```
tsdb/wal.go
507:	f, err := os.OpenFile(name, os.O_RDWR, 0666)

promql/query_logger.go
85:	file, err := os.OpenFile(filename, os.O_CREATE|os.O_RDWR|os.O_TRUNC, 0666)
```

* Prometheus version:

	master branch

Note:

The `kind/bug` label may be no accurate for the issue, but different file permission may lead to some maintain problem .

**Comment by roidelapluie** [comment]
It should be 666 and the umask set by the user would determine the actual value.
