### ISSUE TITLE
index: Preallocate slices when decoding series.

### ISSUE THREAD

**Issue by bwplotka** [prometheus/prometheus#7732]
During profiling of tip of TSDB we found that `index.(*Decoder).Series` takes a significant amount of time on growing slice:

![image](https://user-images.githubusercontent.com/6950331/89182185-2ec52b00-d58d-11ea-83a2-13600f3f7caa.png)

Might be log hanging fruit to improve it by some preallocations.

**Comment by brancz** [comment]
It appears to me that it's this variable that we initialize from scratch on every `.Next` call. https://github.com/prometheus/prometheus/blob/28c5cfaf0d417d9bc2378f1e9838a15ebc76e6b8/tsdb/querier.go#L382

Either a pool of `labels.Labels` or pre-allocating ~10 items would make sense here.

**Comment by knweiss** [comment]
Side note: The Go static analyzer [prealloc](https://github.com/alexkohler/prealloc) finds slice declarations that could potentially be preallocated. It is also integrated into the metalinter [golangci-lint](https://github.com/golangci/golangci-lint/) and can be called like this:
```
golangci-lint run --disable-all --enable=prealloc --tests=false ./tsdb/...
```
It finds 13 cases in tsdb of today's HEAD (however not the line in querier.go).

**Comment by brancz** [comment]
Yeah this is not a typical pre-alloc case, it's more of an array re-use case
