### ISSUE TITLE
exec format error

### ISSUE THREAD

**Issue by gupf0719** [prometheus/prometheus#7755]
step1 git clone https://github.com/prometheus/prometheus.git (master branch) 

step2 cd prometheus, make build

step3 docker build -t prometheus:2.20 .

step4 docker run \         
        -p 9090:9090 \
        -v /Users/gupengfei/programming/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml \
        --name prometheus1 \
        prometheus:2.20 bash

standard_init_linux.go:211: exec user process caused "exec format error"

error :
standard_init_linux.go:211: exec user process caused "exec format error"

**Comment by roidelapluie** [comment]
I think you build it for Mac with make build but docker wants an Linux executable.
Can you try:
GOOS=linux make build

**Comment by gupf0719** [comment]
> I think you build it for Mac with make build but docker wants an Linux executable.
> Can you try:
> GOOS=linux make build

it's ok , thanks very much
