### ISSUE TITLE
Please allow including configuration snippets

### ISSUE THREAD

**Issue by NightTsarina** [prometheus/prometheus#7760]
Hi,

Related to #1648, I would like to be able to import configuration snippets from other files. In particular, if I am managing the configuration files with ansible or a similar system, I need to split responsibilities (I have an ansible role for each exporter), and also I need a way to include manual configuration that won't be overwritten by the config management system.

Currently, not having this feature makes it very awkward to manage prometheus.yml with ansible..

**Comment by brian-brazil** [comment]
This sort of topic has been discussed before. Prometheus is not a configuration management system, and this is the responsibility of systems like ansible. In this particular case I'd suggest using its `assemble` module, which is designed for exactly this.

**Comment by NightTsarina** [comment]
Brian, I understand that argument, and I have seen the discussions in the past. But this is not about making it a cfg mgmt system, just adding a very common and very useful functionality... And it is something that would make integration at the system (debian) package level much easier (by having exporter packages dropping sample configurations for localhost scraping in the right place).

Plus, your suggestion is not really useful, as it requires running that ansible module every time something changes any part of the configuration, manual or not. It is almost like the sendmail scripts that ran M4 every time you changed configuration.. It can be done, but it is an ugly hack.

**Comment by roidelapluie** [comment]
Why can't file_sd cover?

**Comment by NightTsarina** [comment]
> Why can't file_sd cover?

Because for that I need to have defined all the scrape configurations in advance in the main template. Instead, I would like to separate the general configuration from the scrape configuration, and drop a file that contains -say- all the configuration to scrape node-exporters. Right now, I have a simple ansible configuration for node/blackbox/selfmonitoring and alertmanager. But if I want to add one instance of one exporter, even to test it out, I need to create new ansible configuration and modify the main template to add it.

These are common problems for sysadmins for a long time, and that is why most important packages in debian use this mechanism, which works great for integration with other packages, while giving lots of freedom to the sysadmin and guaranteeing that manually added snippets are never touched by the packaging system.

I think this is so useful that I would probably add it to the Debian package myself when I get the time, but I really like to avoid deviating from upstream. Or maybe do it with a pre-processor hooked into the init script/service file, but that is a hack.

**Comment by beorn7** [comment]
Closing for now as a dupe #5519 (which also links to previous requests).

However, given that this topic comes up now and then again, we'll put it on the agenda of the Prometheus dev summit to discuss it in more detail.
