### ISSUE TITLE
Disallow invalid label names on targets

### ISSUE THREAD

**Issue by benley** [prometheus/prometheus#777]
It looks like Prometheus will let you apply invalid labels to targets that come from file_sd targets at the very least; probably other types as well.

e.g.
```json
[{
  "targets": ["1.2.3.4:9100"],
  "labels": {
    "some_valid_label": "asdfasdfasdf",
    "oops:this-label-is-invalid": "asdfasdfasdf"
  }
}]
```

The "oops:this-label-is-invalid" label will show up on the status page under base labels, but there doesn't seem to be any way to query for it.  The client_golang library restricts labels to `[A-Za-z0-9_]`, but I don't see the same happening inside prometheus.

**Comment by fabxc** [comment]
Thanks for reporting this.

Validation of label names goes via the `client_golang` library. The `UnmarshalYAML` method of the `LabelName` type checks the regex during unmarshaling. The respective `UnmarshalJSON` method that does the same was missing, thus you were able to provide wrong labelnames via JSON target groups.

So basically it's a bug in `client_golang`. 
See #778
