### ISSUE TITLE
ChunkQuerier: Accessing returned chunk.Bytes() causes SegFault

### ISSUE THREAD

**Issue by bwplotka** [prometheus/prometheus#7776]
Looks like we are sharing some memory that gets deallocated, causing https://github.com/thanos-io/thanos/issues/3013

This looks like it's happening on querying during `compactHead` is finished processing. Probably mmaped chunks are the reason - those bytes has to be copied in the iterator.

**Comment by pracucci** [comment]
Thanks for reporting it. Could this issue affect Prometheus as well?

**Comment by bwplotka** [comment]
Yes, using remote-read.

Investigating compaction process WITH delete API coming in same moment (:

**Comment by bwplotka** [comment]
Fix: https://github.com/prometheus/prometheus/pull/7795

**Comment by bwplotka** [comment]
Looks like from all conversations: It works an intended. 

I described this behavior better and added tests against it here: https://github.com/prometheus/prometheus/pull/7795 but overall this ready is good to be closed (:
