### ISSUE TITLE
Strict checking of API query params

### ISSUE THREAD

**Issue by roidelapluie** [prometheus/prometheus#7780]
# Proposal
**Use case. Why is this important?**

We should check that only valid parameters are passed to /api/v1/query and query_range (timeout, step, query, stats) and that they have only one value, and return 400 if extra or duplicate parameters are passed.

This is a preparation of the future limit/sorting post-processing options which will be added, to prevent silent mistakes in the API queries.

**Comment by brian-brazil** [comment]
This has the potential to break existing users, some frameworks will add additional url parameters for tracking etc.

**Comment by roidelapluie** [comment]
Do you have exemples? I'd think they would add Headers.

**Comment by brian-brazil** [comment]
Not offhand, but things like Google Analytics are often added to URLs.

**Comment by roidelapluie** [comment]
like utm_source=news4&utm_medium=e-mail&utm_campaign=printemps-ete .. mmh

**Comment by roidelapluie** [comment]
What would you think about leveraging our warning field?

**Comment by brian-brazil** [comment]
I think that'd be watering it down a bit, the user likely has little control over it and would be more likely to ignore actual warnings.

**Comment by roidelapluie** [comment]
Indeed.
