### ISSUE TITLE
Prometheus OOM crash with 1TB of free memory remaining

### ISSUE THREAD

**Issue by amckinley** [prometheus/prometheus#7781]
Running a very large Prometheus install (1,952GB memory, 128vCPUs), we observed Prometheus crash with a "runtime out of memory" error, despite having almost 1TB of available memory. You can see we actually had two machines crash at about the same time, one of which was legitimately out of memory, but the other one was totally healthy:
![Screen Shot 2020-08-11 at 12 32 33 PM](https://user-images.githubusercontent.com/54160/89940666-bbe03380-dbce-11ea-895c-1b719ee54ee1.png)

Stack trace:
```
level=error ts=2020-08-11T13:08:40.215Z caller=consul.go:487 component="discovery manager scrape" discovery=consul msg="Error refreshing service" service=cloudwatch_exporter tags= err="Get \"http://127.0.0.1:8500/v1/health/service/cloudwatch_exporter?index=1650985810&stale=&wait=30000ms\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x26d56d3, 0x16)
	/usr/local/go/src/runtime/panic.go:1116 +0x72
runtime.sysMap(0x193f8000000, 0x8000000, 0x4254c78)
	/usr/local/go/src/runtime/mem_linux.go:169 +0xc5
runtime.(*mheap).sysAlloc(0x423fdc0, 0x7c00000, 0x423fdc8, 0x3da0)
	/usr/local/go/src/runtime/malloc.go:715 +0x1cd
runtime.(*mheap).grow(0x423fdc0, 0x3da0, 0x0)
	/usr/local/go/src/runtime/mheap.go:1286 +0x11c
runtime.(*mheap).allocSpan(0x423fdc0, 0x3da0, 0x0, 0x4254c88, 0x415b46)
	/usr/local/go/src/runtime/mheap.go:1124 +0x6a0
runtime.(*mheap).alloc.func1()
	/usr/local/go/src/runtime/mheap.go:871 +0x64
runtime.(*mheap).alloc(0x423fdc0, 0x3da0, 0xc00bd00100, 0x427910)
	/usr/local/go/src/runtime/mheap.go:865 +0x81
runtime.largeAlloc(0x7b40000, 0x460001, 0x193f523e000)
	/usr/local/go/src/runtime/malloc.go:1152 +0x92
runtime.mallocgc.func1()
	/usr/local/go/src/runtime/malloc.go:1047 +0x46
runtime.systemstack(0x0)
	/usr/local/go/src/runtime/asm_amd64.s:370 +0x66
runtime.mstart()
	/usr/local/go/src/runtime/proc.go:1041

<snip 200MB of goroutine traces>
```

**Environment**

* System information:
```
$ uname -srm
Linux 4.15.0-1035-aws x86_64

$ ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 7869925
max locked memory       (kbytes, -l) 16384
max memory size         (kbytes, -m) unlimited
open files                      (-n) 65536
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 7869925
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```

* Prometheus version:
```
$ prometheus --version
prometheus, version 2.18.1 (branch: HEAD, revision: ecee9c8abfd118f139014cb1b174b08db3f342cf)
  build user:       root@2117a9e64a7e
  build date:       20200507-16:51:47
  go version:       go1.14.2
```

* Prometheus configuration file:
https://pastebin.com/BTy1haNB

**Comment by jpdstan** [comment]
![image](https://user-images.githubusercontent.com/5893781/89943395-fd72dd80-dbd2-11ea-9ee7-e3c66ebdcf0c.png)

![image](https://user-images.githubusercontent.com/5893781/89943411-02d02800-dbd3-11ea-8c42-dcb8ceadab41.png)

![image](https://user-images.githubusercontent.com/5893781/89943425-06fc4580-dbd3-11ea-8180-146b0faf7c7c.png)

![image](https://user-images.githubusercontent.com/5893781/89943444-0d8abd00-dbd3-11ea-8cb8-e69ba0434c37.png)

![image](https://user-images.githubusercontent.com/5893781/89943457-124f7100-dbd3-11ea-9a60-88434207f55f.png)

**Comment by jpdstan** [comment]
For a little context - the ~4:30 mark is when the WAL replay finished, which, according to the graph below, took about 1**4 hours** :O 

![image](https://user-images.githubusercontent.com/5893781/89944250-55f6aa80-dbd4-11ea-9837-1802f6fc7d5b.png)

**Comment by roidelapluie** [comment]
When you see the isolation watermark raising I'd like to see what a gorouting dump gives.

**Comment by roidelapluie** [comment]
Also, maybe you should consider sharding at this stage.

**Comment by jpdstan** [comment]
Also during this 4:30 - 6:15 window is seems like we were unable to hit a WAL checkpoint (didn't receive any `prometheus_tsdb_wal_truncate_duration_seconds_count` metrics in this timeframe and didn't see `WAL checkpoint complete` log messages)

**Comment by amckinley** [comment]
> Also, maybe you should consider sharding at this stage.

Yes, we're currently migrating away from this configuration to use Cortex instead.

**Comment by beorn7** [comment]
The Go runtime has clearly claimed "out of memory". If that's a false claim (as the title of this issue suggests), it's not a Prometheus bug but a bug in the Go runtime or even in the OS.

Another possibility is that something in Prometheus requested memory very fast so that the metric for "free memory" wasn't updated in time before Prometheus killed itself.

**Comment by amckinley** [comment]
> Another possibility is that something in Prometheus requested memory very fast so that the metric for "free memory" wasn't updated in time before Prometheus killed itself.

That seems at least conceivable, but as the issue suggests, there was at least a terabyte of free memory on that host.

**Comment by roidelapluie** [comment]
"Memory" is everything and nothing at the same time. What does the first graph show? cached+buffer+inuse?

**Comment by amckinley** [comment]
> "Memory" is everything and nothing at the same time. What does the first graph show? cached+buffer+inuse?

`node_memory_MemAvailable_bytes`

**Comment by amckinley** [comment]
I'm not an expert, but from the stack trace, it looks like the attempted allocation was for `0x8000000` bytes (or ~134MB if my math is right), so I don't think it was an attempt to allocate all the free memory in the universe. This is also "reproducible" in the sense that we've observed these machines crash with the same "OOM" condition several times in the last few days.

I found this thread, which makes absolutely zero sense to me: https://github.com/golang/go/issues/39400 But I guess I can try changing `vm/overcommit_memory` and see what happens.

**Comment by hoffie** [comment]
@amckinley Can you confirm that there are no cgroup-level limits, e.g. from some a container runtime or from systemd? (I think I have mostly seen such limits manifest in the form of kernel OOM messages, but maybe there are still ways to handle this more gracefully and Golang might do that?)

**Comment by amckinley** [comment]
> @amckinley Can you confirm that there are no cgroup-level limits, e.g. from some a container runtime or from systemd? (I think I have mostly seen such limits manifest in the form of kernel OOM messages, but maybe there are still ways to handle this more gracefully and Golang might do that?)

It's running on a bare EC2 instance, so there's no cgroup shenanigans at play.

**Comment by beorn7** [comment]
This is an interesting discussion, but we are really discussing topics outside Prometheus. This could be in the Go runtime, in the Linux kernel, or a special property of the VMs Amazon uses. 

Since we use GH issues to track actionable issues in Prometheus, we (in our weekly bug scrub) decided to close this. Feel free to continue discussing (on a forum of your choice, or if need be on this closed issue), but please understand that we need to take this off our plate.

**Comment by amckinley** [comment]
For future archeologists: we figured this out. It turns out we were running into the kernel limit `vm.max_map_count`, which controls how many memory map areas a process can request. The default limit of 65536 was too low, so doing `sysctl -w vm.max_map_count=262144` fixed our issue and allowed Prometheus to continue consuming memory. There's probably nothing you can do about this on the Prometheus side since the golang allocator manages this, but FWIW 65536 is a *lot* of memory maps and I'm kinda surprised that Prometheus keeps allocating them long after startup.

**Comment by beorn7** [comment]
Yeah, Prometheus maps the TSDB block files into memory, and while it compacts multiple smaller blocks into bigger ones spanning longer timeframes, the total number of blocks is growing until the retention limit is reached. (Prometheus might also only map some older files for real once they are accessed, but I'm not sure about that one.)

In any case, congrats to the awesome troubleshooting. We should definitely keep this in mind and once we write some guidelines about running very large Prometheus servers, we should include `vm.max_map_count` and not only the obvious ones like the limit for open files.

**Comment by brian-brazil** [comment]
> Prometheus might also only map some older files for real once they are accessed, but I'm not sure about that one

Everything needed is mmapped in when we load the block, so it's basically proportional to the number of blocks you have.

**Comment by amckinley** [comment]
> We should definitely keep this in mind and once we write some guidelines about running very large Prometheus servers

Let us know when you get around to that; we could help you write a book on the subject ;)

**Comment by juliusv** [comment]
@amckinley See also https://twitter.com/RealRockaut/status/1300425495008481281 - there's definitely interest in learning more about such a huge setup, maybe a PromCon talk next year, or something on your own earlier than that? :)

**Comment by rockaut** [comment]
I know this is closed already - and my comment is off-topic, sorry - but as a user and community-member I would love to see and hear more about this setup, the purpose and the challanges around it if its possible ;-)

**Comment by RichiH** [comment]
https://twitter.com/TwitchiH/status/1300373916951744512 is the root comment for the new-found publicity. A few thoughts that don't go out of my head:

1. Are you able to spin up a sacrificial instance which ingests the data twice to see if and how it explodes?
2. Would you be willing to write a use case report, case study, similar?
3. Can you share a pprof of a longer-running instance with us?

**Comment by amckinley** [comment]
> @amckinley See also https://twitter.com/RealRockaut/status/1300425495008481281 - there's definitely interest in learning more about such a huge setup, maybe a PromCon talk next year, or something on your own earlier than that? :)

Those are great ideas! Our team is really bandwidth-constrained right now, but especially once the dust is settled migrating _away_ from our giant Prometheus, we'd definitely be interested in sharing more details with the community about how we got here.

> A few thoughts that don't go out of my head:
> 
> 1. Are you able to spin up a sacrificial instance which ingests the data twice to see if and how it explodes?

We could try that, but FWIW we've seen our current 2TB instances still OOM when something like this slips by us:
![image](https://user-images.githubusercontent.com/54160/91759778-15f96680-eb87-11ea-8980-e594316b104c.png)

Once we're in a slightly more stable place, I can probably spin up an extra instance and halve the sample rate just to see what happens.

> 2. Would you be willing to write a use case report, case study, similar?

Absolutely, time permitting. Ask me again in a month :)

> 3. Can you share a pprof of a longer-running instance with us?

Sure, how do you want it? SVG?

**Comment by RichiH** [comment]
SVG sounds good, yes.

**Comment by amckinley** [comment]
GitHub won't let me embed SVGs, so here you go: https://pastebin.com/4RBu9HQ6

That server's been running for about 24hrs.
