### ISSUE TITLE
Add the Prometheus logo to the react ui

### ISSUE THREAD

**Issue by roidelapluie** [prometheus/prometheus#7783]
## Proposal
**Use case. Why is this important?**

I think that except in the favicon, the prometheus logo is nowhere to be seen in the UI.

I'd like to see it in the navbar:

![temp](https://user-images.githubusercontent.com/291750/89949785-b6173c00-dc28-11ea-8f49-068213070256.png)

Here is my test code:

<details>
```
<a class="pt-0 navbar-brand" href="/new/graph" aria-current="page"><img src="https://prometheus.io/assets/prometheus_logo_grey.svg" style="vertical-align: text-top;height: 1.4em;padding-right:.2em"> Prometheus</a>
```
</details>

**Comment by roidelapluie** [comment]
In a small screen:
![temp2](https://user-images.githubusercontent.com/291750/89950246-83217800-dc29-11ea-8896-3a897425e8ac.png)

**Comment by indavarapuaneesh** [comment]
can I look into this?

**Comment by anuraagbarde** [comment]
Can I work on this?

**Comment by BrandonDalton** [comment]
Hi am I able to work on this?
