### ISSUE TITLE
Duplicated results from /api/v1/series

### ISSUE THREAD

**Issue by pracucci** [prometheus/prometheus#7801]
When multiple matchers are passed to `/api/v1/series`, this API doesn't guarantee deduplicated results.

To my understanding this is caused by fetch series using `.Select(false, ...)`:
https://github.com/prometheus/prometheus/blob/b521612042ec87103088b45b7b5dfee3bb8dc732/web/api/v1/api.go#L604-L608

But then we use `NewMergeSeriesSet()` which expects sorted series sets in order to correctly deduplicate series:
https://github.com/prometheus/prometheus/blob/b521612042ec87103088b45b7b5dfee3bb8dc732/web/api/v1/api.go#L610

Two questions:
1. Am I missing anything?
2. What's the expected behaviour of `/api/v1/series`? We would like to do the "right thing" in Cortex, but I'm not sure what's that 😄

**Comment by gouthamve** [comment]
I think the API should return deduplicated results.

**Comment by brian-brazil** [comment]
Yes, if there's duplicates that's a bug.

**Comment by roidelapluie** [comment]
@pracucci Thanks for raising this! as you have found out the cause, do you want to send a PR?

**Comment by showuon** [comment]
@pracucci , if you don't have time to handle this issue, I can help! Thanks.

**Comment by pracucci** [comment]
_Sorry for the late reply._

> @pracucci , if you don't have time to handle this issue, I can help! Please let me know. Thanks.

Yes, please!

> as you have found out the cause, do you want to send a PR?

Fixing it is trivial, but I've found difficulties adding a test, because the fix is in the API logic.

**Comment by roidelapluie** [comment]
Closed by #7852
