### ISSUE TITLE
feature: support time range parameters in snapshot API

### ISSUE THREAD

**Issue by yeya24** [prometheus/prometheus#7802]
## Proposal
**Use case. Why is this important?**

Current snapshot API only supports snapshotting all TSDB blocks in the disk and head. But sometimes I just want to backup the blocks within a certain time range. 

Maybe we can support start and end params in the snapshot API.

*“Nice to have” is not a good use case. :)*

**Comment by brian-brazil** [comment]
Snapshots are really cheap as they are hardlinks, the expensive part is the head which you can already ask not to have. Is this really needed?

**Comment by yeya24** [comment]
I don't see a reason why we don't want to support this. The point is that it is not always necessary to snapshot all the blocks. I just need to snapshot some blocks

The code change is trivial I think. Does it break something?

**Comment by roidelapluie** [comment]
I think this is not needed. If we do so, our users will expect to only and exactly have from the start to the end, which we can't do with snapshots.

**Comment by beorn7** [comment]
During the bug scrub, we felt that this would gain us very little but adds some complications prone to be misunderstood.

If anyone feels this would be useful, please speak up. Otherwise, we'll close this.
