### ISSUE TITLE
Text is cropped in react ui tooltips

### ISSUE THREAD

**Issue by roidelapluie** [prometheus/prometheus#7803]
**What did you do?**

Look the tooltips in the new UI

**What did you expect to see?**

Like in the old UI:

![tt2](https://user-images.githubusercontent.com/291750/90293962-9a5ca180-de85-11ea-9efd-18f4024c7c2e.png)

**What did you see instead? Under which circumstances?**

Text is cropped:

![tt1](https://user-images.githubusercontent.com/291750/90293972-a21c4600-de85-11ea-8bb5-998315fe2c07.png)

* Prometheus version:

	2.20.1

**Comment by roidelapluie** [comment]
cc @juliusv

**Comment by juliusv** [comment]
Interesting, it doesn't happen on the PromLabs one, and I've never seen it do that before: https://demo.promlabs.com/new/graph?g0.expr=up&g0.tab=0&g0.stacked=0&g0.range_input=1h

Wondering if it's a recent regression or something specific triggering that issue, checking...

**Comment by juliusv** [comment]
According to `git bisect`, the commit that introduces this bug is this jquery version bump: https://github.com/prometheus/prometheus/commit/c7d9516695c51cdb2185166e34c8190feca0fdf8
