### ISSUE TITLE
PromQL: Inconsistent / wrong behavior of boolean operator

### ISSUE THREAD

**Issue by trallnag** [prometheus/prometheus#7816]
**What did you do?**

Boolean comparison of a histogram quantile against a gauge. I think it is best explained with the following queries / screenshits.

The following query works perfectly fine and just as I expected:

```
(
  rate(discoverer__round_duration_seconds_sum{instance="discovery:8080", job="discovery"}[1m])
  /
  rate(discoverer__round_duration_seconds_count{instance="discovery:8080", job="discovery"}[1m])
)
> bool
(
  discoverer__info_interval_seconds{instance="discovery:8080", job="discovery"} * 0.02
)
```

![image](https://user-images.githubusercontent.com/24834206/90413033-37018800-e0ae-11ea-883f-0bc4e5593464.png)

Now I want to do exactly the same but use a quantile instead of the avg rate:

```
(
  histogram_quantile(1.0,
    sum by (le) (
      rate(discoverer__round_duration_seconds_bucket{instance="discovery:8080", job="discovery"}[1m])
    )
  )
)
>= bool
(
  discoverer__info_interval_seconds{instance="discovery:8080", job="discovery"} * 0.0001
)
```

Please notice that I multiple the gauge with a very small number. This is just to make clear that it will be always <= than the quantile.
The query returns "No datapoints found":

![image](https://user-images.githubusercontent.com/24834206/90413336-9cee0f80-e0ae-11ea-808c-c8e872bd8024.png)

The two queries by themselves work fine and return datapoints.

**What did you expect to see?**

I expected to see something according to the first screenshot.

**Environment**

* System information:

	Official Prometheus Docker container.

* Prometheus version:

	2.20.1 983ebb4a513302315a8117932ab832815f85e3d2

**Comment by roidelapluie** [comment]
Thanks for your report. It looks as if this is actually a question about usage and not development.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
