### ISSUE TITLE
Unchecked lines should remain unchecked when zooming out

### ISSUE THREAD

**Issue by jsoref** [prometheus/prometheus#7818]
**What did you do?**
1. Visit /graph
1. Enter a query of the form `100 * (count by(job, namespace, service) (up == 0) / count by(job, namespace, service) (up)) > 10`
1. See a couple of lines that correspond to that query (?)
1. In the "legend rickshaw_legend", click the action (✔) for all but one of them
1. See that only one line remains
1. Click the "glyphicon glyphicon-plus" to change the zoom

**What did you expect to see?**

* Any line that I'd unchecked should remain unchecked.
* The line I didn't uncheck should remain checked.
* Lines that were not in the limited scope could appear checked since they had no reason not to.
* If I had zoomed in and lost a line and then later zoomed out and regained a line, I'd expect it to remain hidden.

**What did you see instead? Under which circumstances?**

All of the lines were visible

**Environment**

* System information:

```
Linux 4.19.112+ x86_64
```

* Prometheus version:

```
prometheus, version 2.18.1 (branch: HEAD, revision: ecee9c8abfd118f139014cb1b174b08db3f342cf)
  build user:       root@2117a9e64a7e
  build date:       20200507-16:51:47
  go version:       go1.14.2
```

* Alertmanager version:

* Prometheus configuration file:

* Alertmanager configuration file:

* Logs:

**Comment by roidelapluie** [comment]
Changing the zoom changes the query, so possibly alter query results, so that would be difficult to put in place. Grafana does this (retain selected legend when time changes) and I quite do not like it.

Note that you can deselect just one in one click by clicking directly on the 'V'.

cc @juliusv WDYT?

**Comment by jsoref** [comment]
The problem is that I need to de-select all but one. Having to do that repeatedly is painful.

**Comment by roidelapluie** [comment]
Then you can click on the text of that one.

**Comment by bwplotka** [comment]
Hello from the Bug Scrub!

Sounds like this issue is for the old UI, so let's close it. New UI(s) might still have this UX, so if anyone feels strong about it, feel free to add another issue and tag @juliusv for the decision making. Thanks!
