### ISSUE TITLE
Cloudwatch- Exporter cannot get data in rul.yml in a timely manner to generate alarms

### ISSUE THREAD

**Issue by yeyudetiankon1** [prometheus/prometheus#7828]
Hello, I am having an issue with some of the metrics having about a 7-8 minute delay.

For instance, I am looking to test CPU Usage over a certain amount, this will, of course, be raised, but as its down low (at about 1%) I have to set my equation to be very low for testing.

 - aws_namespace: AWS/ElastiCache
       aws_metric_name: CPUUtilization
       aws_dimensions: [CacheClusterId]
       aws_dimension_select_regex:
         CacheClusterId: [my-cluster.*]
       aws_statistics: [Average]
I then set the alert for this

 - alert: Redis CPU% over 0.1%
       annotations:
         description: '{{ $labels.cache_cluster_id }} is currently over 0.1% CPU Usage'
         message: '{{ $labels.instance }} is currently over 0.1% CPU Usage'
       expr: aws_elasticache_cpuutilization_average{} >= 0.1
       for: 15m
       labels:
         severity: critical
This should take the last 15 minutes and throw an alert as the % is always above 0.1%
However, it never fires, and we suspect that its due to the fact there is never any "moment" or current data being collected from AWS.

Is there a way to fix this? even if it is delayed stats? By this I mean it uses 10-minute old data as the current data so that there is always up to date information?

I have been able to successfully create alerts for other metrics on standalone servers which provide up to date info, so my structure for the alert seems to work fine. And when I click the expression in the Alerts, it shows me a graph with the last 7 or 8 minutes missing.

**Comment by roidelapluie** [comment]
Thanks for your report. It looks as if this is actually a question about usage and not development.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
