### ISSUE TITLE
Add flags to control logrus output destinations

### ISSUE THREAD

**Issue by wrouesnel** [prometheus/prometheus#785]
The change to logrus has left prometheus without any easy way to be run on systems still using SysV init. This means at the moment Prometheus can only log to the console, which requires some hacky workarounds to get it playing nicely with init scripts.

Ideally there'd be a command line flag for something like `-log.hook` to allow seeing the syslog, journald, file hooks logrus supports.

**Comment by juliusv** [comment]
This should be an issue in https://github.com/prometheus/log. Closing this one and opened a new one there: https://github.com/prometheus/log/issues/4
