### ISSUE TITLE
Go 1.15 will break a test case about ssl SANs.

### ISSUE THREAD

**Issue by johncming** [prometheus/prometheus#7861]
**What did you do?**

Commit PRs and found that `TestNewHTTPWithServerName ` failed in the windows environment in CI.

**What did you expect to see?**

No error for `TestNewHTTPWithServerName`.

**What did you see instead? Under which circumstances?**

I looked the last PR results, and there were some successes and some failures with this use case.

**Environment**

windows in ci

* System information:

	windows in ci

* Prometheus version:

	master branch

* Logs:
```
=== RUN   TestNewHTTPWithServerName
2020/08/28 01:41:49 http: TLS handshake error from 127.0.0.1:50034: remote error: tls: bad certificate
    target_test.go:306: Get "https://127.0.0.1:50033": x509: certificate relies on legacy Common Name field, use SANs or temporarily enable Common Name matching with GODEBUG=x509ignoreCN=0
--- FAIL: TestNewHTTPWithServerName (0.01s)
```

* CI failed results 

https://app.circleci.com/pipelines/github/prometheus/prometheus/8873/workflows/1265f98d-c3de-49bd-a286-21b61402e093/jobs/38710

https://app.circleci.com/pipelines/github/prometheus/prometheus/8638/workflows/01992340-66b4-4992-9dac-fbaf2e631e6b/jobs/37696

* Further information

[crypto/x509: Go 1.15 will break default connections to AWS RDS](https://github.com/golang/go/issues/39568)

**Comment by roidelapluie** [comment]
Thanks. This has been fixed on master a few weeks ago.
