### ISSUE TITLE
Hetzner service discovery does not check the status code of the robot api

### ISSUE THREAD

**Issue by roidelapluie** [prometheus/prometheus#7870]
**What did you do?**

Try  HZ robot against a local endpoint, which returns a 404

**What did you expect to see?**

Service discovery tries to unmarshal the response.

**What did you see instead? Under which circumstances?**

Only unmarshal if the answer is 200. it means that it will also do that for 403 (unauthorized).

cc @LKaemmerling

**Comment by LKaemmerling** [comment]
I will fix this tomorrow directly 👍🏻

**Comment by roidelapluie** [comment]
> I will fix this tomorrow directly 👍🏻

Can you fix it against the release-2.21 branch? Thanks!

**Comment by gouthamve** [comment]
Closed by #7872
