### ISSUE TITLE
example_write_adapter out of date?

### ISSUE THREAD

**Issue by amckinley** [prometheus/prometheus#7874]
I think the `example_write_adapter` might be missing some `remote_write` protocol changes from the last few years? In particular, I think maybe it needs to report back to the sender the number of successfully-received samples (just a guess since I've noticed Prometheus report on the number of failed samples when there was a problem with the `remote_write`).

**What did you do?**
Compiled and ran `example_write_adapter` from https://github.com/prometheus/prometheus/tree/master/documentation/examples/remote_storage/example_write_adapter and pointed our large Prometheus instance at it (which should be generating ~40MB/sec of `remote_write` traffic.

**What did you expect to see?**
Printed metrics from the adapter and increases in `prometheus_remote_storage_succeeded_samples_total`, as well as the other `remote_write`-related metrics.

**What did you see instead? Under which circumstances?**
Some metrics printed from the adapter process, then the receiving process stopped responding. All remote_write-related metrics stayed flat, indicating that no samples were marked as successfully written.

**Environment**

* System information:

```
$ uname -srm
Linux 4.15.0-1035-aws x86_64
```

* Prometheus version:

```
$ prometheus --version
prometheus, version 2.18.1 (branch: HEAD, revision: ecee9c8abfd118f139014cb1b174b08db3f342cf)
  build user:       root@2117a9e64a7e
  build date:       20200507-16:51:47
  go version:       go1.14.2
```

* Prometheus configuration file:
https://pastebin.com/BTy1haNB

**Comment by roidelapluie** [comment]
Thanks for your report. cc @cstyan @csmarchbanks

**Comment by csmarchbanks** [comment]
Hello, the `example_write_adapter` is only an example, and not built for efficiency or scale, for example each request would generate a large amount of garbage to be collected due to decoding the snappy buffers and objects without any reuse. Is it possible you were overwhelming the example_write_adapter?

The metrics for number of sent samples and other similar metrics are entirely based on the http response code Prometheus receives from a remote write target, not any sort of message that the target needs to respond with.

**Comment by amckinley** [comment]
To provide more context, we're currently load testing Cortex as a replacement for Prometheus in our environment. When we enable the `remote_write` from Prometheus to our Cortex cluster, we're observing that Prometheus maxes out at around 30MB/sec of `remote_write` traffic despite low load on the Cortex side. The `remote_write` WAL follower on our Prometheus server rapidly falls behind, and then we run into this issue: https://github.com/prometheus/prometheus/issues/5803

After extensive tuning of our `remote_write` settings, it's clear that we're hitting some kind of limit that we don't understand. To try and determine if this is a bottleneck somewhere in Cortex or elsewhere in our stack, I was trying to basically run a service that accepts `remote_write` traffic and drops it on the floor, which is how I found this example code.

I've also been looking around for any kind of documentation on the `remote_write` protocol so I could write my own dummy server, without a lot of success. Could you suggest a path forward for creating a "dumb" `remote_write` receiver?

**Comment by csmarchbanks** [comment]
Interesting, thank you for the context. The "dumbest" remote write receiver you could write is a simple http server that redirects all input to /dev/null and returns a 200. E.g.
```
package main

import (
	"io"
	"io/ioutil"
	"log"
	"net/http"
)

func main() {
	http.HandleFunc("/receive", func(w http.ResponseWriter, r *http.Request) {
		io.Copy(ioutil.Discard, r.Body)
	})
	log.Fatal(http.ListenAndServe(":1234", nil))
}
```
The protocol sends the snappy compressed protobuf over http that you see in the `example_write_adapter`, but only checks the http response code upon return. You can find the logic in [client.go](https://github.com/prometheus/prometheus/blob/master/storage/remote/client.go#L149).

Would you be willing to share your `remote_write` configuration? I don't see it in the config link above. I am definitely interested in learning what the bottleneck is.

**Comment by amckinley** [comment]
Thanks very much for the example implementation! We'll test that and report back when we have more information.

> Would you be willing to share your remote_write configuration? I don't see it in the config link above. I am definitely interested in learning what the bottleneck is.

We've tried quite a few variations on our remote_write config, but this is what we're using currently:
```
            queue_config:
              capacity: 10000
              max_samples_per_send: 2000
```

We would love some guidance on how to tune this for extremely high-throughput Prometheus installs communicating over 10GE links to a Cortex cluster. You may remember us from such GH issues as https://github.com/prometheus/prometheus/issues/7781 :)

**Comment by roidelapluie** [comment]
@csmarchbanks @amckinley

Is the exemple remote write actually broken or can we close this issue?

Thanks!

**Comment by amckinley** [comment]
@roidelapluie depends on what you mean by "broken". It definitely stops responding pretty quickly after you begin to throw a non-trivial amount of traffic at it.

**Comment by cstyan** [comment]
If someone wants to extend the existing example implementation they're free to open a PR, but the example isn't broken.

**Comment by bwplotka** [comment]
Hello from the Bug Scrub!

Sounds like what this issue is about, is to have some benchmarking/testing receiver for remote write. While this would be nice, we likely should do it in another repo. I even started some work around it, but help wanted. Ideally some endpoint that scales and dumps the samples with some statistics. 

However, as it was said current example is not broken in this sense.
