### ISSUE TITLE
Document remote_read protocol

### ISSUE THREAD

**Issue by BertHartm** [prometheus/prometheus#7885]
**What did you do?**

ran a query_range of `sum(increase(metric_name{label!="true"}[1m] offset 1w))` on a prometheus that remote reads for data

full path `/api/v1/query_range?query=sum(increase(metric_name%7Blabel!%3D%27true%27%7D%5B1m%5D%20offset%207d))&start=1599095850&end=1599097800&step=150`
(32.5 minutes between start and end)

**What did you expect to see?**

remote read would fetch 33.5m worth of data, but from a week ago

**What did you see instead? Under which circumstances?**

remote read fetches 607050s worth of data (1w, 37.5 minutes)

**Environment**

* System information:

	it's the quay.io/prometheus/prometheus:v2.18.2 docker image

* Prometheus version:

	v2.18.2

* Alertmanager version:

	n/a

* Prometheus configuration file:
n/a

* Alertmanager configuration file:
n/a

* Logs:
n/a

**Comment by bwplotka** [comment]
That's an interesting one, worth investigating.

**Comment by BertHartm** [comment]
traced a little last night, and it seems like the engine doesn't even try to compute the right time, and just takes the query end time: https://github.com/prometheus/prometheus/blob/master/promql/engine.go#L479-L481

I'm assuming this needs a `findMaxTime` method, which will probably easier with the subquery improvements in the latest rc

**Comment by brian-brazil** [comment]
This behaviour is correct, and changing it would both be breaking and prevent more complex use cases. This values are the total time over which the query is looking.

The actual time it's asking for in particular is in the hints, if your remote storage doesn't take this in to account that's something to being up with them.

**Comment by roidelapluie** [comment]
We have discussed this at the bug scrub, and it looks like we lack proper documentation for remote_read. We should have in the future better documentation around it, that includes best practices as well.

**Comment by PKhivasra** [comment]
Looks like this issue has been fixed in:  https://github.com/prometheus/prometheus/releases/tag/v2.25.0

```
Query:
sum(rate(metric_name{label=~"true"}[1m] offset 1w))
Duration on graph: 30mins
```
Request: /query_range, Prometheus version: **2.25.0**

```
StartTime = 1701299408588 = Wednesday, November 29, 2023 3:10:08.588 PM GMT-08:00 = 7 days 31 (30+1) mins ago from current time
Endtime = 1701301268588 = Wednesday, November 29, 2023 3:41:08.588 PM GMT-08:00 = 7 days ago from current time
Total data fetched for = 31 mins
```

Request: /query_range, Prometheus version: **2.24.1**

```
startTime: 1701214447387 = Tue Nov 28 2023 15:34:07 GMT-0800 (7 days, 35 (30 + 5) mins ago from currentTime)
endTime:1701821347387 = Tue Dec 05 2023 16:09:07 GMT-0800
Total Data fetched: 1 week 35mins (This is too much of data fetched)
```

**Comment by bwplotka** [comment]
Hello from the Bug Scrub!

Looks like it's fixed indeed. Thanks! Closing for now, we can always reopen.
