### ISSUE TITLE
Unexpected behavior when using _ in alert unit test to generate a missing value

### ISSUE THREAD

**Issue by colltoaction** [prometheus/prometheus#7887]
**What did you do?**

I used `_` in an alert unit test to generate a missing value

**What did you expect to see?**

An alert being triggered

**What did you see instead? Under which circumstances?**

The alert was not triggered. However, I found a workaround that shows this is unexpected behavior.

**Environment**

I have a repro that I based off `master` a few minutes ago: https://github.com/colltoaction/prometheus/commit/0d22fb1d7c550fad9bdc8552b67c92c42e098415. The files `cmd/promtool/testdata/unittest_missing_bad.yml` and `cmd/promtool/testdata/unittest_missing_good.yml` are almost identical, but one passes and the other one doesn't.

You can see that I only changed

```yaml
values: "0 _"
```

for

```yaml
values: "_ 0"
```

-----

I debugged the code as far as I could, but when I reached https://github.com/prometheus/prometheus/blob/267dd17fe7c847fecb5255dc88278f5f1f8ee92b/promql/parser/parse.go#L200 I was basically lost. It reached the point where the code was using a yacc generated parser and I didn't want to dig further before posting here.

**Comment by brian-brazil** [comment]
Thanks for your report, this is as expected. This is due to staleness handling, we look back for the last non-stale value. The issue here is that your test data is not quite realistic, try `stale` as the value instead - or evaluate it 5m later.

**Comment by colltoaction** [comment]
Thanks, I'll try that! Is there any resource I can use to learn more about these options for handling staleness? I haven't had a chance to watch [your talk](https://www.youtube.com/watch?v=GcTzd2CLH7I), but are there any written docs I can look into?

**Comment by brian-brazil** [comment]
It looks like we haven't actually documented `_` and `stale`, so we should fix that. We're not even using `_` anywhere in our own unittests that I can see.

**Comment by colltoaction** [comment]
I found this comment https://github.com/prometheus/prometheus/issues/4689#issuecomment-426655275 pointing to these tests https://github.com/prometheus/prometheus/blob/9bca041285e226410809b64ce2d178bc4ccabbcf/promql/parse_test.go#L1734.

**Comment by colltoaction** [comment]
`stale` worked as expected. Thank you!

**Comment by keremgocen** [comment]
this one still needs a PR? I'm looking for something to work on..

**Comment by colltoaction** [comment]
From what I understand, unit tests and documentation would make a great
contribution.

**Comment by MacroPower** [comment]
Having this in the documentation would be great as it took me a little while to land on this issue.
