### ISSUE TITLE
Jaeger tracing broken in 2.20.1

### ISSUE THREAD

**Issue by BertHartm** [prometheus/prometheus#7888]
**What did you do?**

upgraded from prometheus 2.19.3 to 2.20.1

**What did you expect to see?**

parent / child trace relationships to continue working for remote read sources

**What did you see instead? Under which circumstances?**

the remote read sources were behaving as if no parent trace existed
also, sometimes seeing spans showing no context in the jaeger ui, but can't consistently reproduce that

**Environment**

* System information:

	quai.io/prometheus/prometheus:v2.20.1

* Prometheus version:

	v2.20.1

* Alertmanager version:

	n/a

* Prometheus configuration file:
n/a

* Alertmanager configuration file:
n/a

* Logs:
n/a

**Comment by roidelapluie** [comment]
@csmarchbanks @bwplotka 

Can you please triage this issue? Thanks!

**Comment by csmarchbanks** [comment]
I reproduced this issue locally. The remote read client appears to not have a span on the context it receives, but I have not had time to trace through the code to find out where the span is dropped yet.
