### ISSUE TITLE
minor fix for docker dependency to fix illumos build

### ISSUE THREAD

**Issue by jclulow** [prometheus/prometheus#7890]
I deploy and use Prometheus on some illumos-based systems.  The build process has been working out of the box for a while, at least as of earlier this year.

Trying to build master now, though, and I hit this error:

```
>> building binaries
GO111MODULE=on /var/tmp/PROMDAP/gopath/bin/promu build --prefix /var/tmp/PROMDAP/gopath/src/github.com/prometheus/prometheus
 >   prometheus
# github.com/docker/docker/client
vendor/github.com/docker/docker/client/client.go:120:35: undefined: DefaultDockerHost
vendor/github.com/docker/docker/client/client.go:125:12: undefined: DefaultDockerHost
vendor/github.com/docker/docker/client/client.go:128:12: undefined: defaultProto
vendor/github.com/docker/docker/client/client.go:129:12: undefined: defaultAddr
!! command failed: build -o /var/tmp/PROMDAP/gopath/src/github.com/prometheus/prometheus/prometheus -ldflags -X github.com/prometheus/common/version.Version=2.20.1 -X github.com/prometheus/common/version.Revision=252265fa81989f4cef2fd9e875bb77fb318c9314 -X github.com/prometheus/common/version.Branch=master -X github.com/prometheus/common/version.BuildUser=@sigma -X github.com/prometheus/common/version.BuildDate=20200831-21:11:26  -extldflags '-static' -mod=vendor -a -tags netgo,builtinassets github.com/prometheus/prometheus/cmd/prometheus: exit status 2
gmake: *** [Makefile.common:227: common-build] Error 1
```

This turns out to be because the `illumos` build tag is missing from `vendor/github.com/docker/docker/client/client_unix.go`.  Adding it in manually allows the build to complete and the resultant binary functions correctly:

```diff
diff --git a/vendor/github.com/docker/docker/client/client_unix.go b/vendor/github.com/docker/docker/client/client_unix.go
index 178ff6740..69fb1b48f 100644
--- a/vendor/github.com/docker/docker/client/client_unix.go
+++ b/vendor/github.com/docker/docker/client/client_unix.go
@@ -1,4 +1,4 @@
-// +build linux freebsd openbsd netbsd darwin dragonfly
+// +build linux freebsd openbsd netbsd darwin dragonfly illumos

 package client // import "github.com/docker/docker/client"
```

Is it alright to make a patch against the vendored copy of the module?  The upstream copy has been patched already, though perhaps not in the 19.03 stable branch: https://github.com/moby/moby/blob/ae0ef82b90356ac613f329a8ef5ee42ca923417d/client/client_unix.go#L1

The resultant built binary identifies it as:

```
$ ./prometheus --version
prometheus, version 2.20.1 (branch: master, revision: 252265fa81989f4cef2fd9e875bb77fb318c9314)
  build user:       @sigma
  build date:       20200831-21:14:29
  go version:       go1.14.6
```

I thought I would check in to see what the best plan was before just filing a PR!  Thanks.

**Comment by roidelapluie** [comment]
It is not right to patch vendor, I recommend you to:

request moby to build for illumos in the 19.03 branch
add a issue there to see if we are willing to officially support illumos


alternatively you can:
clone the release-2.21 branch and comment dockerswarm in github.com/prometheus/prometheus/discovery/dockerswarm

**Comment by roidelapluie** [comment]
We have looked at this in the bug scrub and decided to keep this issue until the new docker release is out with official illumos support.

**Comment by roidelapluie** [comment]
hello @jclulow 

Are you able to build prometheus 2.24.1 for illumos ? It should work out of the box.

**Comment by jclulow** [comment]
Indeed I am!  Thanks so much!

```
$ cache/gopath/src/github.com/prometheus/prometheus/prometheus --version
prometheus, version 2.24.1 (branch: non-git, revision: non-git)
  build user:       jclulow@newcastle
  build date:       20210202-00:48:49
  go version:       go1.15.3
  platform:         illumos/amd64
```

While I have you, it'd be great if I could get someone to point me in the right direction on prometheus/promu#191 and then I think we would be all set across the board.

Thanks again!

**Comment by roidelapluie** [comment]
Thanks, I have answered on the other issue and pinged the maintainers.
