### ISSUE TITLE
HTTP API | DELETE |  all with time range not working 

### ISSUE THREAD

**Issue by NarendranathPanda** [prometheus/prometheus#7894]
**What did you do?**
I was trying to clean up all metrics  1599141970(GMT: Thursday, September 3, 2020 2:06:10 PM) time 1599142090(GMT: Thursday, September 3, 2020 2:08:10 PM)
# v1
`curl -X POST   -g 'http://localhost:9090/api/v1/admin/tsdb/delete_series?match[]={__name__=~".%2B"}&start=1599141970&end=1599142090'`

# v2
`
curl post -g 'http://localhost:9090/api/v2/admin/tsdb/delete_series' -d {"matchers": [{"name": "__name__", "type": 2, "value": ".+"} ], "start": "1599141970","end": "1599142090"}`

**What did you expect to see?**

All the metrics will be cleaned up falling under the time range 1599141970 - 1599142090

**What did you see instead? Under which circumstances?**
It won't work , No deletion at all
**Environment**
local | windows

* System information:

	insert output of `uname -srm` here

* Prometheus version:

	insert output of `prometheus --version` here
prometheus, version 2.12.0 (branch: HEAD, revision: 43acd0e2e93f9f70c49b2267efa0124f1e759e86)
  build user:       root@7a9dbdbe0cc7
  build date:       20190818-14:07:44
  go version:       go1.12.8

* Alertmanager version:

	insert output of `alertmanager --version` here (if relevant to the issue)

* Prometheus configuration file:
```
insert configuration here
```

* Alertmanager configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
