### ISSUE TITLE
global.external_labels configuation

### ISSUE THREAD

**Issue by Antiarchitect** [prometheus/prometheus#7895]
## Proposal
**Use case. Why is this important?**
Kubernetes + Helm case.
When tried to make Prometheus + Thanos (thanos.io) integration inside the Kubernetes I've faced the fundamental configuration problem of Prometheus - there is no way to set unique global.external_labels per StatefulSet's pod - it is a requirement of Thanos (https://thanos.io/tip/operating/troubleshooting.md/#possible-solution-1) at the moment and the only true way to distinct metrics from different Prometheus servers on the logical level. Is it possible to provide another way to set (additional?) external_labels like environment variable or Prometheus server flag?

P.S. It could be possibly achieved by unnatural and hacky manner like making n configuration files distinct only by external_labels set and try to mount it for all pods at once, and then, based on specific construct choose which one to apply per each pod:

```
env:
  - name: CONFIG_PREFIX
    valueFrom:
      fieldRef:
        fieldPath: metadata.name
```

But it is a very hacky way and will definitely break the config reload feature most Prometheus Helm charts have at the moment.
Currently, bitnami chart seems to manage this problem somehow but only by integrating with bitnami Prometheus operator and that's too heavy as the regular charts can deploy Prometheus into Kubernetes without an operator and a bunch of additional CRDs.
Mirror issue on Thanos side: https://github.com/thanos-io/thanos/issues/3123

**Comment by brian-brazil** [comment]
This isn't possible, it's up to whatever is invoking Prometheus to provide the config file with the values you want. It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by beorn7** [comment]
Just in case others arrive here with a similar problem:

https://github.com/grafana/jsonnet-libs/blob/master/prometheus-ksonnet/lib/prometheus-ha-mixin.libsonnet demonstrates the Jsonnet mixin way of configuring different external labels for the different pods in a stateful set (our need comes from Cortex, not Thanos, but that's just a detail). It is essentially using the same idea that @Antiarchitect described above (as "unnatural and hacky" :o), i.e. create a different config map for each replica, mount them all, and then pick according to an env variable.

This is indeed quite a contraption, and one of the reasons why I'd prefer env variable substitution in the config file (or external labels on the command line, if nothing else works).

**Comment by Antiarchitect** [comment]
@beorn7 Fat chance: #2357 - cloud-native, you know.

**Comment by roidelapluie** [comment]
@Antiarchitect Starting Prometheus 2.27, we will be able to substitute env variables in external labels if you use `--enable-feature=expand-external-labels`

This can be tested  with the `main` docker image.

**Comment by Antiarchitect** [comment]
@roidelapluie Great news. I have fought this problem by turning off autorefresh of prometheus configs and some bash + sed magic. Will try as soon as I update the chart.

**Comment by roidelapluie** [comment]
2.27 is scheduled in 5 weeks, the doc is here if you want to test with the main docker image : https://github.com/prometheus/prometheus/blob/main/docs/disabled_features.md
