### ISSUE TITLE
No "for" in new rules UI

### ISSUE THREAD

**Issue by sergey-onanchenko** [prometheus/prometheus#7897]
Dear Colleagues,

**What did you do?**
Open Rules via new UI

**What did you expect to see?**
Same details (presence of "for") as in old UI

**What did you see instead? Under which circumstances?**

Alert configurations are cut

* Prometheus version:

	2.20.1

![изображение](https://user-images.githubusercontent.com/38660869/92203175-35470b00-ee89-11ea-8346-a8ccf846a2d0.png)

**Comment by roidelapluie** [comment]
This will be fixed in 2.21. Thanks.

**Comment by roidelapluie** [comment]
Fixed in #7605 #7606
