### ISSUE TITLE
topk/bottomk X over time, X = [avg, sum, min, max, etc...]

### ISSUE THREAD

**Issue by codesome** [prometheus/prometheus#7903]
## Proposal
**Use case. Why is this important?**

Quoting [this comment](https://github.com/prometheus/prometheus/issues/7878#issuecomment-686373735) here

> Another thing we cannot do natively in PromQL is graphing top N time series. All the details [are in this blog post](https://www.robustperception.io/graph-top-n-time-series-in-grafana).
> TL;DR is, if you use topk in query_range, you can get much more than k time series. We cannot graph just k metrics based on some condition (say sum, avg, etc is the highest for past x hours).
> While it can be done in Grafana, it would be nice to be able to do it natively in PromQL to write ad-hoc queries.

Implementing this would not be as simple as adding a new method because of the `query_range` semantics (it run's an instant query at all the timestamps in the range and is just a syntactic sugar over instant queries), as we need fixed set of metrics to be plotted for entire range.

I plan to work on a proposal to fix/implement this without breaking the `query_range` semantics and without needing invasive changes in PromQL. Please raise your concerns if any :)

Update: A clarification. The aim of this is to be able to do `topk X over time` where `X` can be average, sum, min, max, median, etc.

Update:
Developers mailing list: https://groups.google.com/g/prometheus-developers/c/K8HUmH7t6hk
Design doc: https://docs.google.com/document/d/1uSbD3T2beM-iX4-Hp7V074bzBRiRNlqUdcWP6JTDQSs/edit?usp=sharing

**Comment by roidelapluie** [comment]
Well this sounds like sort + limit in the output modifiers that were accepted in the dev summit?

**Comment by brian-brazil** [comment]
Not quite, this use case was explicitly out of scope as it's trickier than it looks. For example when you're talking about a series rather than a sample, what does "top" mean?

**Comment by codesome** [comment]
> For example when you're talking about a series rather than a sample, what does "top" mean?

Yeah, so, we need to be able to tell what to look for. For example: sum over time, min over time, max over time, etc is highest (or lowest for bottomk).

**Comment by bwplotka** [comment]
Wonder what's the behaviour for worst edge cases for other systems like DataDog? :thinking:

**Comment by bwplotka** [comment]
We talked offline with @codesome  and TBH we feel like the best is to use post-processing/modifiers for that.

This can work as a sorting modifier + limit k. Obviously sorting has to have some aggregation (sometimes called rank method).  

Since this fits into modifier/postprocessing work, we are referring this issue on our Community Bridge mentorship: https://github.com/cncf/mentoring/blob/master/communitybridge/2020/q3-q4/project_ideas.md#prometheus

**Comment by codesome** [comment]
> we might have better ideas soon.

I am still collecting and evaluating ideas to eliminate any edge cases and check it against use cases beyond topk itself. I should have something to show in a few weeks time.

**Comment by codesome** [comment]
Developers mailing list: https://groups.google.com/g/prometheus-developers/c/K8HUmH7t6hk
Design doc: https://docs.google.com/document/d/1uSbD3T2beM-iX4-Hp7V074bzBRiRNlqUdcWP6JTDQSs/edit?usp=sharing

**Comment by bboreham** [comment]
Just want to link the blog post here too: https://prometheus.io/blog/2021/02/18/introducing-the-@-modifier/
