### ISSUE TITLE
= is considered as EQL in lexer when used within braces

### ISSUE THREAD

**Issue by Harkishen-Singh** [prometheus/prometheus#7904]
**What did you do?**
I was working on developing [Prettier](https://github.com/prometheus/prometheus/pull/7779) for PromQL. While writing extensive unit tests, I came across this issue which was responsible for breaking the formatting at some places.

### Issue
`=` should be considered as ASSIGN item by the lexer. This happens as expected until it is used inside label_matchers. When in label_matchers, it is treated as `EQL`. This leads to [issues](https://github.com/prometheus/prometheus/pull/7779#discussion_r484217251) while formatting a PromQL expression.

Note: `EQL` should be `==`.

Related code: 
1. https://github.com/prometheus/prometheus/blob/f8c8adfd67b48709a4e57341c7cb6d7ebbdff061/promql/parser/lex_test.go#L231
2. https://github.com/prometheus/prometheus/blob/f8c8adfd67b48709a4e57341c7cb6d7ebbdff061/promql/parser/lex_test.go#L591

**What did you expect to see?**
Consider `=` as ASSIGN even when used inside label_matchers.

**What did you see instead? Under which circumstances?**
`=` is considered as `EQL` when used within label_matchers.

**Comment by brian-brazil** [comment]
This sounds vestigial, from before recording rules were in YAML.

**Comment by Harkishen-Singh** [comment]
Will take up this.

**Comment by roidelapluie** [comment]
Mmh this is not really correct, I think it is equal and not assign ?

**Comment by Harkishen-Singh** [comment]
You mean, in vector selectors, you use `metric_name{label==value}`? As far as I know, I don't think there's any such vector selector comparison. But yes, in terminology, we call that as equality.

**Comment by Harkishen-Singh** [comment]
I think this is a bug not a cleanup.

**Comment by roidelapluie** [comment]
It is cleanup as there is no user impact.

**Comment by brian-brazil** [comment]
Yeah, nothing is actually broken here. It's just something vestigial from Prometheus 1.x days that's still lying around.
