### ISSUE TITLE
Federation TODO

### ISSUE THREAD

**Issue by fabxc** [prometheus/prometheus#791]
#786 piled up a few TODOs for federation:

- `honor_labels` sufficient as final configuration option? Are there other things then label handling that should differentiate a federation target from a regular scrape target?
- Sorting relevant except for debugging via text protocol?
- Versioning of federation endpoint? As part of the regular API?

**Comment by fabxc** [comment]
@juliusv If we can agree on the last point I'd close this one.
You suggested to include it into the API, I was for keeping it separated from the API. Do you have a stronger tendency so far?

For reference, my reasoning was that version bumps for the API endpoints and federation are unlikely to line up or be related at all. Plus the fundamentally different output format. I don't think an API client package should be required to interact with `/federate` to be complete.

**Comment by brian-brazil** [comment]
I think some versioning would be wise, but not tied to the regular API. On the other hand it's only the arguments that should change over time, and that can probably be done in a backwards-compatible way.

**Comment by juliusv** [comment]
I don't feel strongly... if we start with it outside of the API, we can still decide to move it into the API later (whereas the opposite would be more breaking).

**Comment by brian-brazil** [comment]
I don't think there's anything more to be done here?
