### ISSUE TITLE
Add function: Ratio between two (label,value) sets on the same metric

### ISSUE THREAD

**Issue by MeenaAlfons** [prometheus/prometheus#7922]
## Proposal
**Use case. Why is this important?**

Getting the ratio of two sets of (label,value) pairs for the same metric is common use case which can be implemented efficiently if it is natively supported by a function in prometheus.

**Example:**
We have a `requests_counter` metrics with one label `result` which takes one of two values `error` and `ok`. For the sake of finding out the percentage (ratio) of errors over a specific period of time, we currently need to use the following query:
```
sum(rate(requests_counter{result="error"}[28d])) / sum(rate(requests_counter[28d]))
```
OR
```
sum(increase(requests_counter{result="error"}[28d])) / sum(increase(requests_counter[28d]))
```
Both would give the same result.

The problem is that any of those queries would take longer to execute and with huge number of events the query will timeout. The reason is that the execution of such queries need to traverse the data points twice; Once for the numerator and another time for the denominator.

The intended calculation can been done by traversing the data points once with two accumulating counters in hand. This will reduce. the execution time by 50%.

Therefore, the proposal is to have a function in prometheus called `ratio(...)` which takes three parameters:
- The metric name
- A set of (label, value) pairs
- Another set of (label, value) pairs

And the result of `ratio(...)` will be the ratio of the number of events happened with the **first** set of (label,value) pairs to the number of events happened with the **second** Set of (label,value) pairs.

```
ratio(metric, LabelValueSet1, LabelValueSet2) =

number of events matching LabelValueSet1
-------------------------------------------
number of events matching LabelValueSet2
```

**Comment by roidelapluie** [comment]
That is a good idea to reduce the amount of select we do.

How do you cover http_requests{code=~"5.."} type of selects?

**Comment by roidelapluie** [comment]
Note that we could optimize this use case in TSDB selcts out of the box but not in remote reads calls.

**Comment by brian-brazil** [comment]
Functions don't do arbitrary label matching which is essential for this to be useful (that's what operators are for), and I don't think we should be making PromQL more complex for the sake of micro-optimising performance. If there's a performance optimisation that's possible here let's do it under the covers and not push that burden on to the user.

More generally, your examples and what your proposed function would enable can be an anti-pattern as it encourages undoing the benefits of labels; plus it's simpler, safer, and faster to do ok/error as two separate total/failed counters. 

For the more general case for more than 2 label values I think https://www.robustperception.io/using-group_left-to-calculate-label-proportions is what you actually want, and also more efficient than what you're proposing as it'll only require one PromQL expression.

**Comment by roidelapluie** [comment]
@brian-brazil 

Do we do 2 selects in the local tsdb for:

```
  sum without (cpu)(rate(node_cpu[1m]))  
/ ignoring(mode) group_left 
  sum without (mode, cpu)(rate(node_cpu[1m])) 
```


?

**Comment by brian-brazil** [comment]
Yes, that's two selects. I'd suggest however that if doing common subexpression elimination here (the technical name for this optimisation) makes the difference in terms of a timeout, that the real problem is the amount of data being processed. A 28d rate is going to be slow generally, and at most a 2X improvement will in face of growth at most buy you a little time until you run into limits again.

The more appropriate solution here is aggregation and rates over a short time period, such as 5m, in recording rules and then taking it from there when running large 28d reporting queries.

**Comment by Harkishen-Singh** [comment]
As per the discussion, I guess we do not want to implement(atleast what Brian said). So, is this still a kind/feature in terms of Pmaybe?

**Comment by roidelapluie** [comment]
I am waiting for input of the OP or the next bug scrub to close this.

**Comment by roidelapluie** [comment]
We have looked at it during our bug scrub and decided to close this as per above comments. Thanks!
