### ISSUE TITLE
remote_read : support hardcoding an extra label selector to add to each remote query

### ISSUE THREAD

**Issue by primeroz** [prometheus/prometheus#7927]
## Proposal
**Use case. Why is this important?**
In my use case i have multiple k8s clusters running prometheus, all og them writing to a Cortex cluster. 
All prometheus in the same environment ( dev for example ) will write to Cortex as the same tennant

When metrics are sent to Cortex the `external_labels` are added to every series to help identify which cluster the metrics belong to ( `env: dev` `cluster: k8s1` for example)

When i enable remote_read on the client prometheus though , unless i add the `cluster: k8s1` label selector to every query cortex will return series for all clusters in that environment say `cluster: k8s1`, `cluster: k8s2` and so on

While this is manageable on Grafana / prometheus UI it becomes a bit of an issue when rules are evaluated for recording and alerting on prometheus

Do you think it would be possible / sensible to add either the `external_labels selector` to every remote_read query or allow specifying `extra label selector` in the remote_read section so to make it optional ?

**Comment by roidelapluie** [comment]
are you looking for `required_matchers` ?

**Comment by brian-brazil** [comment]
> When i enable remote_read on the client prometheus though , unless i add the cluster: k8s1 label selector to every query cortex will return series for all clusters in that environment say cluster: k8s1, cluster: k8s2 and so on

That doesn't sound right, this is meant to work out of the box. The external labels should be applied automatically to the remote read requests - unless you already have a matcher for the label name. Can you share the exact query you're using? Can you also share your config file?

**Comment by primeroz** [comment]
> are you looking for required_matchers ?

I guess I do ... and i can't really understand how i missed it in the configuration docs. 

> That doesn't sound right, this is meant to work out of the box. The external labels should be applied automatically to the remote read requests - unless you already have a matcher for the label name. Can you share the exact query you're using? Can you also share your config file?

Interesting ... i have no remote_read anymore but i will re-enable and get some info for you. 
The real pain was about `rules evaluation` ... is that supposed to automatically use the external labels as well ? 

I will get the info by the end of they hopefully ... if you want i can close this ( since it seems like not only i missed the `required_matchers` but also this should work out of the box and in case reopen a new case if i still have the issue ?

BTW i am on a bit old version of prometheus : v2.16.0 ... could that be the reason ? 

Thanks btw

**Comment by brian-brazil** [comment]
> The real pain was about rules evaluation ... is that supposed to automatically use the external labels as well ?

Yes, query evaluation is the same everywhere.

> BTW i am on a bit old version of prometheus : v2.16.0 ... could that be the reason ?

This shouldn't have changed since 2.0 days.

**Comment by primeroz** [comment]
Ok , i will get more info for you ... it might just turn out i was doing something wrong! 

thanks for the speedy feedback

**Comment by primeroz** [comment]
> required matchers

Reading again I read this to mean "only query the remote endpoint if the query has these matchers" not "always apply these labels when querying remote endpoint"

But the `external_labels` is actually what i needed so will get back on that

**Comment by primeroz** [comment]
Ok finally i have an update for this and i Think there was an issue with 2.16 the same query to a local cluster with remote_read to cortex 

**2.16**
![aW1hZ2UucG5n](https://user-images.githubusercontent.com/2085772/93210828-9d86ce00-f760-11ea-98f4-0461508341a8.png)


**2.17**
![aW1hZ2UucG5n 2 17](https://user-images.githubusercontent.com/2085772/93210872-b1323480-f760-11ea-8051-ba5e0d442d2d.png)


found in the release notes for 2.17
`[BUGFIX] Remote read: Fix duplication of metrics read from remote storage with external labels #6967 #7018`
