### ISSUE TITLE
Proposal: Completely remove series after deleting and cleaning (delete in-mem metadata)

### ISSUE THREAD

**Issue by trallnag** [prometheus/prometheus#7932]
## Proposal

Completely remove time series including information about respective labels, label values etc. after using `/api/v1/admin/tsdb/delete_series` and `/api/v1/admin/tsdb/clean_tombstones` instead of still returning information about removed time series for example in calls to `/api/v1/label`.

**Use case. Why is this important?**

Currently deleted time series still show up (indefinitely) in various web UIs that show all available metrics. Even after cleaning the tombstones. This is for example the case in Grafana and the Prometheus web UI, since they all use the `/api/v1/label` to retrieve all `__name__` values. And the responses of this endpoint contain names of metrics that have been deleted.

![image](https://user-images.githubusercontent.com/24834206/93003817-2f64c000-f542-11ea-8dd7-31c507c50d0e.png)

This can get a bit annoying especially if someone has made a mistake in the naming of a metric or simply wants to get rid off old metrics that are not used anymore. But this is not possible and so these non-existant metrics continue to pollute the namespace and might irritate users that work with Prometheus and are left wondering why certain metrics are shown but contain no data points.

**Comment by roidelapluie** [comment]
Thank you for your issue. I think it is a duplicate, I will try to find the original issue and link it here.

**Comment by roidelapluie** [comment]
We have looked at this during our bug scrub, can you please verify that you are no longer ingesting those labels?

Also, if the data is still in head (ingested in the last 2-3 hours), you will still see the labels. Can you please confirm that it's not the case?

**Comment by trallnag** [comment]
I will try it out in a reproducible setup once I get to it in the next few days and than come back to you / this issue

**Comment by estahn** [comment]
@roidelapluie We're seeing the same behaviour. I deleted the series but it still pops up in the suggestion box.

**Comment by juliusv** [comment]
I was just on a consulting call with a customer who got the same issue - no samples anymore for deleted series, but `/api/v1/series` still returned the deleted series.

**Comment by roidelapluie** [comment]
Same question as in september. Were those samples ingested very recently?

**Comment by juliusv** [comment]
This is a good point, since it wasn't *that* many series (IIRC) it may well have been just ones from the most recent hours, not sure.

**Comment by roidelapluie** [comment]
If the data delete was only on blocks, that is a bug. In the head, this is a known behaviour. Not to say it is not a bug but there might be technical reasons behind it.

**Comment by brian-brazil** [comment]
> Not to say it is not a bug but there might be technical reasons behind it.

This is something that has changed over time, and may change back and forward again. It boils down to performance, and deleted series being returned is not a priority when considering ingestion/querying speed. So sometime the implementation happens to be synchronous, sometimes it isn't.

**Comment by juliusv** [comment]
Yeah, I'm starting to recall past discussions about this. Then we should mention this at https://prometheus.io/docs/prometheus/latest/querying/api/#delete-series because while this behavior may be a reasonable tradeoff, it's definitely not what someone would expect when reading the API docs.

**Comment by kvz** [comment]
In our case we were trying to remove metrics from machines we no longer care about, which happens a lot since we encode video on behalf of our customers with unpredictable loads. So we scale up & down many machines. We care about the active ones, but do not about the ones that have been scaled down. When removing metrics for these machines, it seemed to have no effect as the next runs of the script that handles comparing EC2 state against Prometheus metric instances, the metrics for the same machines where targeted for deletion over and over. This puzzled me because the Prometheus API did report it successfully deleted them (`✅ Success. body='', ok='true', status='204', statusText='No Content'`).

I think your explanation makes sense Brian, I just double checked to confirm that the machines that keep being targeted are machines that were fairly recently scaled down. Just with my lack of familiarity with the Prometheus internals I don't think I could have figured this out without Julius pointing me to this thread. Googling mostly lead me to users suggesting that I needed to properly escape the `instance` name, or have Prometheus `clean_tombstones` after I deleted them.

**Comment by brian-brazil** [comment]
The deletion is of the samples, not of the series. And clean tombstones is only guaranteed to affect blocks, not the head.

>  it seemed to have no effect as the next runs of the script that handles comparing EC2 state against Prometheus metric instances

It sounds like you're using the wrong APIs. You should be using the query APIs, not the label ones, to determine state at a given time. The label APIs can return false positives for a number of reasons, and that will always be the case.

**Comment by juliusv** [comment]
@brian-brazil Regarding "You're using the wrong APIs" - When nothing in our documentation makes that clear (and rather suggests the opposite), that's on us. I'll send a PR to clarify the docs.

**Comment by juliusv** [comment]
https://github.com/prometheus/prometheus/pull/8376

**Comment by Ultimator14** [comment]
FWIW I was facing the same issue (with old job names showing up) but after deleting all time series belonging to a certain job and cleaning the tombstones afterwards, the job label was removed automatically after a few hours (Prometheus version 2.38.0).

**Comment by bwplotka** [comment]
Hello from the Bug Scrub!

Sounds like after the documentation change, this behaviour should be explicit (and is intended for now) -- essentially Metadata stored in head (in-memory) stays and will be eventually forgotten (few hours).

Sounds like for autocompletion, the consensus is that this behaviour is good enough. Might be not trivial to implement and the benefit is small. We are open for suggestions around different issues around this behaviour with metadata -- we can reopen or you can created a new issue 🤗
