### ISSUE TITLE
rule_checker does not indicate if a rule is keeping_extra

### ISSUE THREAD

**Issue by jaqx0r** [prometheus/prometheus#794]
The following rules:

    job:errors:rate10s_nokeep = sum(task:errors:rate10s{job="s"}) by (code)
    job:errors:rate10s = sum(task:errors:rate10s{job="s"}) by (code) keeping_extra

are printed as

    job:errors:rate10s_nokeep = sum(task:errors:rate10s{job="s"}) BY (code)
    job:errors:rate10s = sum(task:errors:rate10s{job="s"}) BY (code)

by rule_checker.

I'd expect the keeping_extra clause to remain as it's part of the rule.

**Comment by fabxc** [comment]
Thanks, will be fixed in master soon.
