### ISSUE TITLE
WAL replay remote storage tailing error message after lagging behind

### ISSUE THREAD

**Issue by Harkishen-Singh** [prometheus/prometheus#7940]
Not sure if its a bug, but definitely some errors in log during wal replay when prometheus is started with remote storage (TimescaleDB).

**What did you do?**

Start Prometheus with remote-storage enabled.

**What did you expect to see?**
No errors while wal replay.

**What did you see instead? Under which circumstances?**
Errors during wal replay, but then says `wal replay done`. Seems like a missing segment due to inconsistency in truncation and wal.Watcher (or possible race).

* Logs:
```
level=info ts=2020-09-14T05:56:16.839Z caller=head.go:806 component=tsdb msg="Head GC completed" duration=2.366574ms
level=info ts=2020-09-14T05:56:16.839Z caller=checkpoint.go:96 component=tsdb msg="Creating checkpoint" from_segment=5695 to_segment=5696 mint=1600012800000
level=info ts=2020-09-14T05:56:16.881Z caller=head.go:886 component=tsdb msg="WAL checkpoint complete" first=5695 last=5696 duration=42.542668ms
level=info ts=2020-09-14T05:56:16.905Z caller=head.go:806 component=tsdb msg="Head GC completed" duration=1.129637ms
level=info ts=2020-09-14T05:56:16.945Z caller=head.go:806 component=tsdb msg="Head GC completed" duration=2.814506ms
level=info ts=2020-09-14T05:56:16.945Z caller=checkpoint.go:96 component=tsdb msg="Creating checkpoint" from_segment=5697 to_segment=5698 mint=1600027200000
level=info ts=2020-09-14T05:56:16.993Z caller=head.go:886 component=tsdb msg="WAL checkpoint complete" first=5697 last=5698 duration=47.674518ms
level=info ts=2020-09-14T05:56:17.013Z caller=head.go:806 component=tsdb msg="Head GC completed" duration=1.926415ms
level=info ts=2020-09-14T05:56:17.041Z caller=head.go:806 component=tsdb msg="Head GC completed" duration=2.009196ms
level=info ts=2020-09-14T05:56:17.041Z caller=checkpoint.go:96 component=tsdb msg="Creating checkpoint" from_segment=5699 to_segment=5700 mint=1600041600000
level=info ts=2020-09-14T05:56:17.082Z caller=head.go:886 component=tsdb msg="WAL checkpoint complete" first=5699 last=5700 duration=40.615538ms
level=info ts=2020-09-14T05:56:17.109Z caller=head.go:806 component=tsdb msg="Head GC completed" duration=2.02106ms
level=info ts=2020-09-14T05:56:17.134Z caller=head.go:806 component=tsdb msg="Head GC completed" duration=1.007374ms
level=info ts=2020-09-14T05:56:17.134Z caller=checkpoint.go:96 component=tsdb msg="Creating checkpoint" from_segment=5701 to_segment=5702 mint=1600056000000
level=info ts=2020-09-14T05:56:17.172Z caller=head.go:886 component=tsdb msg="WAL checkpoint complete" first=5701 last=5702 duration=38.221026ms
ts=2020-09-14T05:56:17.198Z caller=dedupe.go:112 component=remote level=error remote_name=3ed20f url=http://localhost:9201/write msg="error tailing WAL" err="open data/wal/00005702: no such file or directory"
ts=2020-09-14T05:56:23.267Z caller=dedupe.go:112 component=remote level=info remote_name=3ed20f url=http://localhost:9201/write msg="Done replaying WAL" duration=1.068800422s

```

**Comment by codesome** [comment]
cc @cstyan

**Comment by cstyan** [comment]
Well something strange is going on, there's 4 checkpoints created in the span of 2 seconds. Looks to me like the WAL watcher was replaying 5701 when the last checkpoint was happening, and when it finished 5702 no longer existed, so it moved on to 5703 and found sample with a timestamp > prometheus' start time, hence the `done replaying WAL` message.

This could have caused more problems if there was series records in that segment file, we wouldn't have those labels when we see the series reference ID later, until the next time we check for and read the checkpoint file.

@codesome is it possible to delay any checkpointing until after the WAL watcher has replayed the WAL? Or should we delay remote storage starting until after the regular replay and initial checkpointing?

**Comment by codesome** [comment]
> Well something strange is going on, there's 4 checkpoints created in the span of 2 seconds.

@Harkishen-Singh did you restart the Prometheus after a few hours gap since it was down?

> @codesome is it possible to delay any checkpointing until after the WAL watcher has replayed the WAL? Or should we delay remote storage starting until after the regular replay and initial checkpointing?

The initial checkpointing is not in yet (unless Head is getting compacted when TSDB opens), but after https://github.com/prometheus/prometheus/pull/7939, I would say let's checkpoint once and then start the remote storage because I would not prefer TSDB operations depend on remote-write. Does remote write WAL replay block the statup? Also, if we checkpoint before remote write replay, is there a possibility of losing data because remote-write has not sent the samples from the earlier WAL segments?

**Comment by Harkishen-Singh** [comment]
> @Harkishen-Singh did you restart the Prometheus after a few hours gap since it was down?

Yes, in fact, anytime I start it with remote storage enabled, this happens. (Checked out just now and same thing)

> Does remote write WAL replay block the startup?

I don't think so.

**Comment by cstyan** [comment]
> The initial checkpointing is not in yet (unless Head is getting compacted when TSDB opens), but after #7939, I would say let's checkpoint once and then start the remote storage because I would not prefer TSDB operations depend on remote-write. Does remote write WAL replay block the statup? Also, if we checkpoint before remote write replay, is there a possibility of losing data because remote-write has not sent the samples from the earlier WAL segments?

@codesome I also would prefer if TSDB did not depend on remote write, but yes there is the possibility of losing data because remote-write has not sent the samples from earlier WAL segments once we have the remote write checkpointing from #7710. Remote write WAL replay doesn't block startup, that replay is explicitly not started until after TSDB has started (in main.go).

**Comment by Harkishen-Singh** [comment]
>  but after #7939, I would say let's checkpoint once and then start the remote storage because I would not prefer TSDB operations depend on remote-write.

Better if we have an issue for that.

**Comment by roidelapluie** [comment]
We have looked at this during our bug scrub and decided to close this based on above comments. Thanks!

**Comment by Harkishen-Singh** [comment]
I think this requires work than closing it. @roidelapluie

**Comment by codesome** [comment]
Yeah lets keep this open until we are sure we cannot fix it.

@cstyan: is this error possible even when running normally but remote write lagging a lot? Hence rw lagging behind a few files and WAL truncation happens.

**Comment by cstyan** [comment]
In theory if remote write was very far behind you could see this error yes. But if it's just a few files behind during normal operation, successfully sending data still but just not able to keep up, it's not likely that checkpointing would delete a segment file that remote write hasn't already read. 

Not sure what we can do in either case, as we don't want remote write to have a say in whether a segment file is truncated as part of checkpointing.

**Comment by codesome** [comment]
If Prometheus is down for some time, then after a restart the data in the WAL could be technically considered as lagging behind. Nothing much we can do there when TSDB should not know about remote write and there would be loss of data in remote write anyway. So I propose wont-fix for this particular issue as it's a side affect of longer downtime of Prometheus.

**Comment by cstyan** [comment]
I agree. There's not much we can do in that case. 

We can do the "TSDB doesn't say it's 'started' until it's checked if it should, and executed, checkpointing. And then remote write can start" for the particular case in this issue.

**Comment by ElkRom** [comment]
Hi guys,
Any updates?

**Comment by bwplotka** [comment]
Hello from the Bug Scrub!

Seems as @codesome and @cstyan says, there is still no good idea (after 4y) on how to do it better at the moment. It seems it's an edge case around Prometheus replaying very old data and remote write trying to tail that. Let's close for now, we can always reopen. Thanks!
