### ISSUE TITLE
Output modifiers for query/query_range API

### ISSUE THREAD

**Issue by codesome** [prometheus/prometheus#7947]
## Proposal
**Use case. Why is this important?**

As decided in the dev summit, we want to have sorting of instant query and range query results based on label-values and query result.

Additionally we could have more post processors than just sorting.

This is currently part of community bridge.

**Comment by roidelapluie** [comment]
Do we want to have the UI part of this included in the scope?

**Comment by codesome** [comment]
For the entire work, yes. And as this is the first thing to be done in the community bridge and should be a small addition, it might be in the scope of community bridge too.

**Comment by GayathriVenkatesh** [comment]
Proposal: https://docs.google.com/document/d/1x84e_AhMgwdk_7B5cFj_exOD4BY9ryVRU9JUXJTmFOA/edit#heading=h.bupciudrwmna

**Comment by beorn7** [comment]
Hello from the bug scrub.

As discussed in #8434, by now we have PromQL functions for various sorting options, and we have decided to not do post-processing for now.
