### ISSUE TITLE
Ouput modifiers for query_range API

### ISSUE THREAD

**Issue by codesome** [prometheus/prometheus#7948]
## Proposal
**Use case. Why is this important?**

As decided in the dev summit, we want to have output modifiers for query_range. We still need to explore how the modifiers would like for query_range.

Some initial ideas are sorting based on some ranking (avg, sum, etc) and maybe limit on results after sorting on rank.

This is currently part of community bridge.

**Comment by roidelapluie** [comment]
Do we want to have the UI part of this included in the scope?

**Comment by codesome** [comment]
For the entire work, yes, for community bridge, maybe not, because the duration of program is short.

**Comment by sannimichaelse** [comment]
Hi @codesome, I would love to work on this task as part of the community bridge project.

How do I get started?

**Comment by codesome** [comment]
Hi @sannimichaelse, please apply on the community bridge platform and we will reach out in the next week.

**Comment by sannimichaelse** [comment]
Thanks for the prompt response @codesome. Will submit my application

**Comment by codesome** [comment]
Merging this with #7947. Since an instant query API can return a matrix, the solution for both query and query_range APIs would look similar/same.
