### ISSUE TITLE
why prometheus_tsdb_storage_blocks_bytes is greater than prometheus_tsdb_retention_limit_bytes?

### ISSUE THREAD

**Issue by mdh67899** [prometheus/prometheus#7952]
**What did you do?**

prometheus storage data is greater than storage.tsdb.retention.size，why prometheus don't clean the old data? thanks

```
prometheus_tsdb_storage_blocks_bytes: 779490342263 (725.95GB)
prometheus_tsdb_retention_limit_bytes: 751619276800 (700GB)

```
**What did you expect to see?**

prometheus delete old data and prometheus_tsdb_storage_blocks_bytes less than prometheus_tsdb_retention_limit_bytes

**What did you see instead? Under which circumstances?**

**Environment**

* System information:

	Linux 3.10.0-957.21.3.el7.x86_64 x86_64

* Prometheus version:

```
prometheus, version 2.19.3 (branch: HEAD, revision: 657ba532e42f1db8d7c77bf802378643da0d3118)
  build user:       root@b99e50bced7c
  build date:       20200724-12:20:53
  go version:       go1.14.6

```

* Alertmanager version:

	insert output of `alertmanager --version` here (if relevant to the issue)

* Prometheus configuration file:
```
insert configuration here
```

* Alertmanager configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```

**Comment by codesome** [comment]
The `prometheus_tsdb_storage_blocks_bytes` will go above `prometheus_tsdb_retention_limit_bytes` for a small while before the old data is deleted. The retention bytes is merely an indication of when to start deleting old data and not a strict boundary. Did it go down after some time?

This brings my attention to the checkpoints - we are not taking that into consideration when checking for retention.

**Comment by codesome** [comment]
Opened https://github.com/prometheus/prometheus/issues/7954 for checkpoints in retention checks

**Comment by mdh67899** [comment]
it's not go down after some time. I restart prometheus, prometheus_tsdb_storage_blocks_bytes go down immediately.

I think it may be the reason for this line of code, commenting it may solve the problem

https://github.com/prometheus/prometheus/blob/7aa5fb01bf4c71f0a29490f75f45e39356f4bb2c/tsdb/db.go#L1119

**Comment by codesome** [comment]
That line is actually not the problem because we collect all deletable blocks before breaking (else why would it work after a restart?)

Do you have the logs before the restart? I suspect either we are not updating prometheus_tsdb_storage_blocks_bytes properly or Prometheus faced issues deleting the blocks.

(Also, if you are seeing this again, can you check the actual size on disk?)

**Comment by mdh67899** [comment]
sorry, the log level is not debug level when I restart prometheus, there is no special logs

I understand this way:  when writing a new block, the reload method will always be executed. The reload method will execute the BeyondSizeRetention method to get the blocks that needs to be deleted because the storage size exceeds the limit. If the block exceeds the size of prometheus_tsdb_retention_limit_bytes, **if there are there block**, because of the break statement, it will jump out of the current loop and only **return one block**. In fact, **three of them need to be returned**. Is my understanding correct?

sorry for my poor english.

**Comment by mdh67899** [comment]
I am not particularly familiar with the source code of prometheus, and it may be my misunderstanding

**Comment by roidelapluie** [comment]
Hello,

https://github.com/prometheus/prometheus/blob/7aa5fb01bf4c71f0a29490f75f45e39356f4bb2c/tsdb/db.go#L1115-L1117

This means that we will return all the remaining blocks.

**Comment by codesome** [comment]
> the log level is not debug level when I restart prometheus, there is no special logs

Any errors in compaction/checkpointing/etc will be an error and does not require debug logs. Do you have logs before you restarted?

+ What @roidelapluie said about the code above

**Comment by codesome** [comment]
https://github.com/prometheus/prometheus/issues/8005#issuecomment-719499374
