### ISSUE TITLE
Consider checkpoints for size based retention

### ISSUE THREAD

**Issue by codesome** [prometheus/prometheus#7954]
**Use case. Why is this important?**

Currently we are not considering checkpoints in the size based retention which could be significant at times (especially now that we are truncating a larger portion of WAL).

We need to consider it's size for the retention.

**Comment by Harkishen-Singh** [comment]
I will like to take this up.

**Comment by codesome** [comment]
Go ahead!

**Comment by codesome** [comment]
My bad. While talking to @Harkishen-Singh offline on unit tests in #7969, we realised it late that we are already counting the checkpoint. See: https://github.com/prometheus/prometheus/blob/19c190b406c992278aaade63be92ecc7bb6a4921/tsdb/wal/wal.go#L898

It takes the entire directory which includes even the checkpoint.
