### ISSUE TITLE
Clean tombstones should not require more disk space than a normal compaction

### ISSUE THREAD

**Issue by brian-brazil** [prometheus/prometheus#7957]
See #7545, it looks like if we're cleaning multiple blocks we only delete the old blocks when we reload at the very end. We should be smarter about that.

**Comment by ArthurSens** [comment]
Hi, I think I can try this one.
From what I've read, the idea is to change when the clean up happens... Instead of doing it once at the end, we need to cleanup after every compaction, correct?

**Comment by brian-brazil** [comment]
Basically yes, do the reload after each block compaction.
