### ISSUE TITLE
Prometheus version should include the GOOS / GOARCH

### ISSUE THREAD

**Issue by roidelapluie** [prometheus/prometheus#7962]
Prometheus version currently prints:

prometheus, version 2.9.2 (branch: HEAD, revision: d3245f15022551c6fc8281766ea62db4d71e2747)
  build user:       root@1d43b6951e8f
  build date:       20190424-15:32:31
  go version:       go1.12.4

Having the OS/Arch in addition would be nice, as we already have the go version. Especially, detecting armv7 vs arm64, amd64 and i386.

**Comment by dstdfx** [comment]
Hi there, could I pick this one?

**Comment by dstdfx** [comment]
Hi there, I'll pick this one

**Comment by dstdfx** [comment]
Am I right that it requires some changes in https://github.com/prometheus/common at first?

**Comment by roidelapluie** [comment]
Fixed by #7968

Thanks!
