### ISSUE TITLE
Improve promtool tsdb ls

### ISSUE THREAD

**Issue by roidelapluie** [prometheus/prometheus#7972]
## Proposal
**Use case. Why is this important?**

When I run prometheus ls, I get the following information

```
tsdb ls /prometheus/v2/
BLOCK ULID                  MIN TIME       MAX TIME       NUM SAMPLES  NUM CHUNKS  NUM SERIES
01EBB26SGYHGQG5EMA0N2EWDV8  1592136000000  1592719200000  36310548102  306542295   1922060
01EBWED1AGMFWFX1GM32HQXWPP  1592719200000  1593302400000  35359036968  298620915   2106370
01ECDTKKXP0HP396C1ZKEYR26Q  1593302400000  1593885600000  35683567873  301286366   1959606
01ECZ6PZ1JN84XKEJVV43XXQNP  1593885600000  1594468800000  33992603115  287134995   1973368
```

It think it would be valuable and relevant to:
- have a size column
- dapth the CLI flag ``--human`` to have the size human-readable

**Comment by brian-brazil** [comment]
> have a CLI flag --human to have the date and the sized human-readable

Keep in mind that the TSDB has no knowledge of what the units of the timestamps are, it's just arbitrary numbers to the TSDB.

**Comment by roidelapluie** [comment]
> > have a CLI flag --human to have the date and the sized human-readable
> 
> Keep in mind that the TSDB has no knowledge of what the units of the timestamps are, it's just arbitrary numbers to the TSDB.

I would limit that in the cmd/promtool/ package and not in the tsdb/ package, and not default to it.

That would be a good compromise to me.

**Comment by roidelapluie** [comment]
Oooh there is a human readable flag already.

I guess the scope if this issue is just the size then.

**Comment by brian-brazil** [comment]
The tsdb subcommand is for tsdb stuff, so should work with any use of the tsdb and thus the same design principles apply.

**Comment by roidelapluie** [comment]
> The tsdb subcommand is for tsdb stuff, so should work with any use of the tsdb and thus the same design principles apply.

It seems like the human readable date already exists.

**Comment by brian-brazil** [comment]
That's a bug then, as it can produce incorrect values. At the least we should be documenting that it's assuming milliseconds in the flag help.

**Comment by Harkishen-Singh** [comment]
Should there be `K` or `M` if `--human` flag is used?

**Comment by brian-brazil** [comment]
That seems reasonable to me.

**Comment by roidelapluie** [comment]
I think we us this already: https://github.com/alecthomas/units

**Comment by ArthurSens** [comment]
Hi :wave: 

I'd like to work on this issue, that will be my first code contribution :slightly_smiling_face:

**Comment by ArthurSens** [comment]
Hello @codesome @bwplotka @krasi-georgiev 

While trying to solve this issue, I noticed that the [Block struct](https://github.com/prometheus/prometheus/blob/master/tsdb/block.go#L246) has the [Size()](https://github.com/prometheus/prometheus/blob/master/tsdb/block.go#L358) function, making it easy to retrieve a block's size(duh :stuck_out_tongue:)

But at promtool [listBlock](https://github.com/prometheus/prometheus/blob/master/cmd/promtool/tsdb.go#L344) function, I can only retrieve a [BlockReader interface](https://github.com/prometheus/prometheus/blob/master/tsdb/block.go#L115), which does not have that Size() function.

Am I missing something? Is it possible to print block size with what we have today?

If not, should I add the Size() function to BlockReader interface? That would require me to implement that function with the [Head](https://github.com/prometheus/prometheus/blob/master/tsdb/head.go#L54) and [RangeHead](https://github.com/prometheus/prometheus/blob/master/tsdb/head.go#L928) structs, and I would need some extra guidance with that :grimacing:

**Comment by codesome** [comment]
Adding Size() method to BlockReader sounds fine
