### ISSUE TITLE
Add a mechanism to handle duplicate queries at metric relabeling / ingestion time

### ISSUE THREAD

**Issue by mewa** [prometheus/prometheus#7978]
## Proposal
**Use case. Why is this important?**
When ingesting metrics we're not always interested in keeping all the labels exported, however, dropping certain labels can cause the scrape to contain duplicate series.

Currently the workaround is to edit the metrics format of whatever is spitting them out - either by editing the application itself or by writing a metrics exporter that would aggregate these duplicates in a meaningful way. I feel it shouldn't be that hard to do such transformations.

It would be really helpful if we could define an action to apply to such duplicates in a relabel config, i.e. to aggregate them an ingestion time. I think it's generic and common enough to warrant including it in Prometheus' core.

#### Example
This becomes especially important as the number of monitored namespaces increases. Suddenly a fairly high-cardinality, aggregate query becomes extremely heavy.

One of the metrics available from the [Nginx Ingress Controller](https://github.com/kubernetes/ingress-nginx/) is `nginx_ingress_controller_request_duration_seconds_bucket` (example below). In our example, we're interested in lowering the cardinality of this metric, so we'd like to drop the `method`, `path`, and `status` labels. However, currently doing so would result in having duplicate time series, since there's no way to tell Prometheus to aggregate these series in some meaningful way.

As I have mentioned, currently, this would require forking the Nginx Ingress Controller or writing a metrics exporter that would wrap such aggregations.

```
nginx_ingress_controller_request_duration_seconds_bucket{
        controller_class="nginx",
        controller_namespace="ingress",
        controller_pod="nginx-ingress-controller-64777788dc-ccccj",
        endpoint="metrics",
        exported_namespace="test",
        exported_service="web",
        host="example.com",
        ingress="test",
        instance="1.1.1.1:10254",
        job="ingress-metrics",
        le="+Inf",
        method="DELETE",
        namespace="app",
        path="/",
        pod="nginx-ingress-controller-64777788dc-ccccj",
        service="ingress-metrics",
        status="204"
}
```

#### Possible implementation

I imagine it could be achieved in a relabel config either by supplying an `aggregation` action such and `aggregation_type` of `sum`, `avg`, `min`, `max`, etc.

To take it further, I'm also wondering if this could be a good entry point to allow manipulating the expression using promQL at ingestion-time.

I'll be happy to work on a solution once we come to agreement on how we would define this in the configuration.

**Comment by brian-brazil** [comment]
Thanks for your suggestion.This has come up numerous times before such as in #6352, and isn't workable. Reducing the cardinality in the target is the appropriate way to handle this.
