### ISSUE TITLE
Increase value for `maxErrMsgLen` for remote write API

### ISSUE THREAD

**Issue by alvinlin123** [prometheus/prometheus#7982]
## Proposal

Currently only 256 bytes is read upon non HTTP 200 from remote write server:https://github.com/prometheus/prometheus/blob/072b9649a30e06c71ddd1c64d25f71c4936e56ba/storage/remote/client.go#L41

256 bytes is quite short, and leads to error message being truncated, which may make operator's life hard. 

As an example, I was remote writing to Cortex and saw the error message gets truncated like in [this Cortex issue](https://github.com/cortexproject/cortex/issues/3247). 

I am thinking if we can increase the value of `maxErrMsgLen` to 512 or even bigger like 10KB?

**Comment by roidelapluie** [comment]
cc @bwplotka WDYT about this proposal?

**Comment by cstyan** [comment]
I don't have an issue with increasing the size slightly, would also impact remote read so Bartek would need to be on board as well.

**Comment by pracucci** [comment]
> I don't have an issue with increasing the size slightly

@cstyan What's the downside of significantly increasing it?

**Comment by brian-brazil** [comment]
It could lead to severe logspam, 10k is multiple screens worth of text.

**Comment by pracucci** [comment]
Agree about 10k, but I'm wondering if we could find a compromise. Does 1KB looks reasonable to you?

**Comment by cstyan** [comment]
512 or 1024 is reasonable IMO.

**Comment by siddhant94** [comment]
hey @brian-brazil , if this is unassigned, can I raise the PR? And 512 or 1024, what would be the preference? maybe 1024?

**Comment by brian-brazil** [comment]
Feel free to raise a PR, let's go with say 512 for now.

**Comment by siddhant94** [comment]
> Feel free to raise a PR, let's go with say 512 for now.

Here's the linked PR - #8017
