### ISSUE TITLE
Allow alerts discovery

### ISSUE THREAD

**Issue by CRASH-Tech** [prometheus/prometheus#7986]
I would like to be able to automatically add alert rules.
Something like endpoint /alerts
From where prometheus will pick up a list of alert rules for a specific service.

**Comment by roidelapluie** [comment]
Thank you for your proposal.

Personally, I think that this is against the principles of Prometheus labels, as it would prevent prometheus to reuse the same alert for multiple label sets, or potentially create duplicate or conflicting alerts. It also raises many questions, like, how often would we refresh them, how would we treat that API being down (even before first fetch), and many other issues.

Alerts are better centralized, taking advantage of the labels like instance or job. There are many configuration management tools to enable you to do this.

If you have device specific thresolds, you can also use https://www.robustperception.io/using-time-series-as-alert-thresholds

**Comment by brian-brazil** [comment]
We look at this in the bug scrub, and are closing per the above.
