### ISSUE TITLE
Histogram bucket value is greater than count

### ISSUE THREAD

**Issue by rybbchao** [prometheus/prometheus#7990]
**What did you do?**

Use fluentd to collect logs and export histogram metrics.

**What did you expect to see?**

Each value in buckets should be less than or equal to `count`.

**What did you see instead? Under which circumstances?**

Some values in buckets were greater than `count`.

![image](https://user-images.githubusercontent.com/17705238/94666300-e41f1f80-033f-11eb-8772-088bb0cfb11c.png)
![image](https://user-images.githubusercontent.com/17705238/94666362-f5682c00-033f-11eb-8df9-4ced0f6aa405.png)

  | Bucket | Count
-- | -- | --
2020-09-25 03:21:03 | 544688 | 544703
2020-09-25 03:21:04 | 547495 | 548359
2020-09-25 03:21:33 | 547495 | 548359
2020-09-25 03:21:34 | 549010 | 549025

From `03:21:33` to `03:21:34`, the increments are as below:

* Bucket: 549010 - 547495 = 1515
* Count: 549025 - 548359 = 666

I tried to reproduce it but I failed. However, it happened several times.

**Environment**

* Prometheus version: v2.21.0
* Fluentd version: v1.11.2
* fluent-plugin-prometheus: v1.8.4 (prometheus/client_ruby: v0.9.0)

**Comment by brian-brazil** [comment]
This is an issue with your data source, and not Prometheus itself. You should file this against fluent-plugin-prometheus most likely.

**Comment by brian-brazil** [comment]
We looked at this in the bug scrub, and per the above this is not an issue in Prometheus so we're closing it.
