### ISSUE TITLE
Go mod file is invalid in v2

### ISSUE THREAD

**Issue by Skarlso** [prometheus/prometheus#7991]
https://github.com/prometheus/prometheus/blob/v2.21.0/go.mod

Is wrongly declaring the module. It's missing a `v2` from its end. Which makes the build fail:

```
github.com/prometheus/prometheus@v2.9.2+incompatible: invalid version: +incompatible suffix not allowed: module contains a go.mod file, so semantic import versioning is required
```

**Comment by bwplotka** [comment]
Hi :wave: 

Yes, and there is lot's of reasons why this is this way. You read all here: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/prometheus-developers/F1Vp0rLk3TQ/F412gRw0CAAJ

TL;DR: It's as easy as putting `GIT-SHA` or `v2.21.0` as version of module, run for Prometheus `go mod tidy` and it will work. The reason why it's confusing is that we introduced Go modules while the project was in v2 version already.

At the end, it will look something like `github.com/prometheus/prometheus v1.8.2-0.20200819132913-cb830b0a9c78`

And this is fine, it's not `v1.8.2` it's might actually higher version - you can see the date and actually commit hash `cb830b0a9c78`. This is how Go module works right now and we are looking for good solution here.

Hope that helps :hugs:

**Comment by Skarlso** [comment]
@bwplotka 
This would help if I would directly require Prometheus. But it's coming in as a dependency from something.

**Comment by bwplotka** [comment]
Hm. I would contact the dependency author and put desired Prometheus version in "replace" section of go mod file. See https://github.com/thanos-io/thanos/blob/830ac35a57602ae890dc195095bf58b831854bb7/go.mod#L80

**Comment by Skarlso** [comment]
Now to find, who the heck is the dependency which brings it in.... :))

**Comment by Skarlso** [comment]
Thanks, this worked btw->
```
replace github.com/prometheus/prometheus => github.com/prometheus/prometheus v1.8.2-0.20190424153033-d3245f150225
```

Should be the right version...

**Comment by roidelapluie** [comment]
You can use `go mod why github.com/prometheus/prometheus`

**Comment by Skarlso** [comment]
```
go: finding module for package github.com/prometheus/prometheus
# github.com/prometheus/prometheus
(main module does not need package github.com/prometheus/prometheus)
```

:D
