### ISSUE TITLE
Allow remote read to not add external labels

### ISSUE THREAD

**Issue by dgl** [prometheus/prometheus#7992]
**What did you do?**

Upgrading to Prometheus 2.20.0 our setup that makes use of [thanos-remote-read](https://github.com/g-research/thanos-remote-read) stopped working.

This is because now external labels are included in the request sent to remote read endpoints. It seems like this is a behaviour change over 2.16.0 which we were previously running.

c4eefd1b3aef4d2f557f67ffc7c192ba1a63937d appears to have fixed what may be considered a bug, external labels weren't included in the remote read query.

This is because:

```
type externalLabelsQuerier struct {
  storage.Querier
```

Embedding the `Querier` embedded SelectSorted as well as Select, but externalLabelsQuerier only overrode Select, so the `next` is called directly when SelectSorted is called on externalLabelsQuerier.

**What did you expect to see?**

It seems like this behaviour is as intended(?), but we accidentally relied on a behaviour that was possibly a bug.

We would like to add an option to remote_read to skip adding the external labels (e.g. `add_external_labels: false`, with a default of true). Combined with `required_matchers` this allows bringing data into a Prometheus that has been aggregated outside of it in a Thanos setup.

**Comment by bwplotka** [comment]
I think that is a fair point :+1: 

cc @brian-brazil @roidelapluie WDYT?

**Comment by roidelapluie** [comment]
Yes, I like this.

Should it be a simple on/off flag or something more complex, along the lines of `relabel_configs`?

**Comment by brian-brazil** [comment]
What's the use case for this?

It has always been the intended since 2.0 that external labels are included in remote read requests (unless there's a matcher for one of them), it was indeed a bug if that was not happening.

Otherwise you'd pull in data from other Prometheus servers that wrote to the same remote storage system.

If you want data from a different Prometheus (i.e. one that hasn't the same external labels) a user has to explicitly request this in their selectors.

> Combined with required_matchers this allows bringing data into a Prometheus that has been aggregated outside of it in a Thanos setup.

This is not the intended use for required_matchers. It's meant for non-storage data along the lines of  https://www.robustperception.io/promql-queries-against-sql-databases-using-a-read-adapter
, which would simply ignore extraneous labels.

> along the lines of relabel_configs?

Relabeling works on labels, not selectors.

**Comment by roidelapluie** [comment]
> Relabeling works on labels, not selectors.

External labels are labels.

**Comment by dgl** [comment]
> What's the use case for this?

https://github.com/G-Research/thanos-remote-read/blob/master/docs/ruler.md explains it, essentially bringing some data into a Prometheus setup, that comes from elsewhere in a Thanos setup.

(Once Thanos has offline duplication of Prometheus replica data -- very close! -- it could also be useful to query that data, as pure remote read wouldn't work anymore. Although that would likely need something more akin to relabelling.)

> This is not the intended use for required_matchers [...] which would simply ignore extraneous labels

I suppose we could just pass labels to ignore to thanos-remote-read. I probably would have done that to start with if I'd realised this was actually a bug rather than a feature...

**Comment by brian-brazil** [comment]
> essentially bringing some data into a Prometheus setup, that comes from elsewhere in a Thanos setup.

That example isn't quite enough for me to figure out what's going on. What sort of data is it that is being pulled in?

It sounds to me like this this is all working exactly as intended, and its the PromQL query that needs altering if it wants to explicitly pull in data that was "meant for" a different Prometheus.


Also the recording rule there isn't following best practices, as `thanos` is (presumably) not its sole relevant label name and it's missing an operation.

**Comment by dgl** [comment]
> That example isn't quite enough for me to figure out what's going on. What sort of data is it that is being pulled in?

Sorry, I can't really talk about specifics, but two more concrete use cases are:

- Calculating a total of something across sharded Prometheus instances, where we would like the alerts to not have a hard dependency on Thanos, but if we can add some annotations based on querying that data it is very helpful.

Imagine in a thanos-ruler a rule like:

```yaml
- record: somelabel:things:sum
  expr: sum by (somelabel) (things_total)
```

Where `things_total` comes from several Prometheus instances. In particular that ends up with some external labels like `ruler_cluster`, but not `prometheus`. If a Prometheus instance doesn't have external labels configured this works fine.

- With [Geras](https://github.com/G-Research/geras), our frontend to OpenTSDB, we are slowly migrating data from OpenTSDB, but being able to query still it is very useful (particularly to sanity check new instrumentation). This is kind of close to the database example, but having to explain to people they need to put `{source="geras",prometheus="",prometheus_replica=""}` in a query is rather confusing as there isn't another Prometheus involved, if we see the required_matcher, then having an option to not require those labels makes sense to me.

(If you consider that remote read is offered as an API to another team, it's a bit of an API violation that this depends on how another team chooses to configure their external labels. Maybe another approach could be to actually put a list in the remote read request of the names of the external labels.)

**Comment by brian-brazil** [comment]
> two more concrete use cases are:

That's enough to work from.

> Where things_total comes from several Prometheus instances. In particular that ends up with some external labels like ruler_cluster, but not prometheus.

Okay, so in that case it's the query that needs adjusting. The required matchers is superfluous from a semantics standpoint (it's only an optimisation) this is normal reading global data back from remote storage.

> If you consider that remote read is offered as an API to another team, it's a bit of an API violation that this depends on how another team chooses to configure their external labels. 

It's not, it's primarily a way to read back the data that you have previously written via remote write. With an opt-in way to read data that other Prometheus servers have written - which is basically what we have here.

**Comment by brian-brazil** [comment]
We look at this in the bug scrub, and this does seem to be the correct and desired behaviour - if a user wants data that originates from another Prometheus via remote read they must explicitly request this to avoid confusion. To me it also sounds like you may wish to reconsider the layout of your external labels.

**Comment by dgl** [comment]
We'll workaround this elsewhere.
