### ISSUE TITLE
promql case insensitive regexp do not work anymore

### ISSUE THREAD

**Issue by sylr** [prometheus/prometheus#7994]
**What did you do?**

Upgraded from 2.19.2 to 2.21.0

**What did you expect to see?**

```
kube_node_status_condition{condition="Ready",node=~"(?i:.+-master-.+)"}
```

I expected this condition to still work.

**What did you see instead? Under which circumstances?**

No data.

**Environment**

* System information:

	Docker

* Prometheus version:

	v2.21.0

**Comment by sylr** [comment]
As noted by @kormat on IRC this does work however:

`kube_node_status_condition{condition="Ready",node=~"((?i).+-master-.+)"}`

**Comment by dgl** [comment]
Potentially due to https://github.com/prometheus/prometheus/pull/7503 -- https://github.com/prometheus/prometheus/pull/7503/files#diff-386e83803db9aa684313923bb1c147daR100 does not take Flags into account anywhere that I can see.

**Comment by brian-brazil** [comment]
That sounds like it alright. We should add some unittests for the various flags RE2 supports anyway.

@pracucci
