### ISSUE TITLE
Add labels to Selector by clicking on labels in result set [React UI]

### ISSUE THREAD

**Issue by Hixon10** [prometheus/prometheus#7995]
1. I open the Web UI - http://localhost:9090/new/graph
2. I enter a selector (for example, **go_memstats_alloc_bytes**)
3. I receive some results in table. For example:
```
go_memstats_alloc_bytes{instance="localhost:9090", job="prometheus"} | 20346216
```
4. I want to automatically change my selector to **go_memstats_alloc_bytes{instance="localhost:9090"}**, by click clicking on `instance="localhost:9090"` in result table.

![prom](https://user-images.githubusercontent.com/2648802/94741636-1733d400-037d-11eb-8efb-d8a8ccf1320d.png)
![prom2](https://user-images.githubusercontent.com/2648802/94741787-55c98e80-037d-11eb-9f97-19631b4102f1.png)

This feature dramatically improve my UX, because right now I need to copy labels, and it is really hard task (I need to select label without unnecessary symbols and so on).

**Comment by hagen1778** [comment]
It might be not trivial to add filter automatically to the query, because the query itself could be very complex.
I'd be fine if label-value pair will be just copied to the buffer when I click on it, so I can decide myself where to paste it.

**Comment by roidelapluie** [comment]
This makes sense, I have added the help wanted label.

**Comment by beorn7** [comment]
Hello from the bug scrub.

#11229 fixed this issue (more or less).
