### ISSUE TITLE
scraping doesn't respect HTTP 429 (StatusTooManyRequests) status code from server

### ISSUE THREAD

**Issue by p0lyn0mial** [prometheus/prometheus#7996]
**What did you do?**  Recently I run into a situation in which the API server was overloaded and responded with HTTP 429 status code but the Prometheus kept sending the request at the defined interval. Unfortunately, I can't share any data so you would have to inspect the source code to confirm that.

**What did you expect to see?** I would like to see the Prometheus slowing down ideally at an exponential rate. Sending request to an overloaded server certainly doesn't help. Some servers like Kubernetes API provide hints to clients by setting `Retry-After` header indicating for how long clients should wait.

**What did you see instead? Under which circumstances?** The Prometheus didn't "follow" HTTP 429 and kept sending the request at the defined interval.

**Environment**

* System information:

	insert output of `uname -srm` here

* Prometheus version:

	insert output of `prometheus --version` here

* Alertmanager version:

	insert output of `alertmanager --version` here (if relevant to the issue)

* Prometheus configuration file:
```
insert configuration here
```

* Alertmanager configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```

**Comment by simonpasquier** [comment]
I don't think that Prometheus should stop scraping the target because it replied with `429`. Scrapes are expected to happen at fixed intervals and a `429` response translates to the `up` metric being `0` which is the right thing to do.
Also https://tools.ietf.org/html/rfc6585#section-4 doesn't say anything about what the clients SHOULD/MAY do.

**Comment by brian-brazil** [comment]
As @simonpasquier says, we're already doing the right thing here. If you want scrapes to happen less frequently then change your scrape interval. Breaking your monitoring during an overload seems unwise however and I'd suggest ensuring that Prometheus is exempted from such limits.

**Comment by brian-brazil** [comment]
We looked at this in the bug scrub, and are closing per the above.
