### ISSUE TITLE
no indication when scraping fails

### ISSUE THREAD

**Issue by p0lyn0mial** [prometheus/prometheus#7997]
**What did you do?** Recently I run into a situation in which the API server was overloaded and didn't respond to scraping requests. As a result, some alerts failed to indicate that there we no metrics. It took me some time to figure out why the Prometheus wasn't able to get the metrics from the target server.

**What did you expect to see?** It would be nice if the Prometheus could expose some metric indicating why scraping failed. The metric could contain HTTP status code or even some message so that troubleshooting is easier and faster.

**What did you see instead? Under which circumstances?** I didn't find anything in the logs and I didn't find a metric that could help me tell why scraping failed.

**Environment**

* System information:

	insert output of `uname -srm` here

* Prometheus version:

	insert output of `prometheus --version` here

* Alertmanager version:

	insert output of `alertmanager --version` here (if relevant to the issue)

* Prometheus configuration file:
```
insert configuration here
```

* Alertmanager configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```

**Comment by brian-brazil** [comment]
Scraping failing is indicated by up being 0, and  you can get more information from the UI. A metric with information has previously been disclosed and rejected as it would have unbounded cardinality, plus per-scrape metrics are really expensive. #7797 is the direction we're going with here.

**Comment by brian-brazil** [comment]
We looked at this in the bug scrub, and are closing per the above.
