### ISSUE TITLE
Eureka SD: Add a Prometheus User-agent on HTTP requests

### ISSUE THREAD

**Issue by roidelapluie** [prometheus/prometheus#8002]
## Proposal
**Use case. Why is this important?**

In the service discoveries, we add a User-Agent to identify the prometheus server and its version to the HTTP requests.

We should do the same for the newly added Eureka SD.

Here is an exemple of user agent we use: https://github.com/prometheus/prometheus/blob/50ae4e298bbb7f8628b0ac01cdd5f7d328b46051/discovery/dockerswarm/dockerswarm.go#L38

**Comment by meetme2meat** [comment]
@roidelapluie If this is open I can take this up and https://github.com/prometheus/prometheus/issues/8003 . Also, the test seems to be failing on local master copy

**Comment by roidelapluie** [comment]
Can you reach out to our community: https://prometheus.io/community/ so we can see why that fails for you.

**Comment by meetme2meat** [comment]
So can I take these 2 issues? 

If yes what I understand from the above description is we need to add a User-Agent Header for Eureka SD and Hetzner Robot SD, right?

**Comment by roidelapluie** [comment]
Yes, please comment on the other issue too

**Comment by meetme2meat** [comment]
@roidelapluie  Thanks
