### ISSUE TITLE
Hetzner Robot SD: Use the Prometheus User Agent in HTTP requests

### ISSUE THREAD

**Issue by roidelapluie** [prometheus/prometheus#8003]
## Proposal
**Use case. Why is this important?**

In the service discoveries, we add a User-Agent to identify the prometheus server and its version to the HTTP requests.

We should do the same for the newly added Hetzner SD. **Note: only the Hetzner Robot calls role should have the user agent, as the hcloud already has a custom user agent set.**

Here is an exemple of user agent we use: https://github.com/prometheus/prometheus/blob/50ae4e298bbb7f8628b0ac01cdd5f7d328b46051/discovery/dockerswarm/dockerswarm.go#L38

**Comment by meetme2meat** [comment]
Will take this up once https://github.com/prometheus/prometheus/issues/8002 get accepted.
