### ISSUE TITLE
Prometheus 2.19 retention not working

### ISSUE THREAD

**Issue by davidxianggao** [prometheus/prometheus#8005]
**What did you do?**
Our Prometheus is running in a pod on a Kubernetes cluster

The current setting of Prometheus is

$ ps auxwww | grep prometheus
    1 nobody   40:40 /bin/prometheus --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus --storage.tsdb.retention.size=40GB --log.level=info

Each time I just either extend with more disk space or recreate the brand new volume

**What did you expect to see?**
the WAL and chunk head space should stop growing when the disk space reaches the retention limit, like 40GB.

**What did you see instead? Under which circumstances?**
I see the tsdb keeps growing in size. now it's 99% again on a 60GB of FS.
And each I restart Prometheus, sometimes the disk space usage jumps by a few GB suddenly after it completing scanning WAL files. Not sure it recovers from some corruption or something.
Also the WAL scanning takes quite long; for example, I see it scanned 394 WAL segments in the most-recent of Prometheus restart. Each segment scanning took about 2-3 seconds, which cost 10+ mins to start Prometheus and get tsdb ready.

/prometheus $ df -h /prometheus
Filesystem                Size      Used Available Use% Mounted on
10.33.39.211:vol_6fc192fa0b17853d8fdac6eecf8ab53c
                         60.0G     59.6G    349.5M  99% /prometheus
/prometheus $ du -hs *
2.1M    01EGKWFED4J1GKWZ6173B0R9QG.tmp
4.0K    01EKMVV6503HMZKH1V8A40BV92.tmp
20.4M   01EKMZ00BMPHS4JG5S06NB5Y4D
9.2G    chunks_head
0       lock
4.0K    queries.active
48.2G   wal

**Environment**
Production

* System information:

$ uname -srm
Linux 3.10.0-1127.19.1.el7.x86_64 x86_64

* Prometheus version:

$ prometheus --version
prometheus, version 2.19.1 (branch: HEAD, revision: eba3fdcbf0d378b66600281903e3aab515732b39)
  build user:       root@62700b3d0ef9
  build date:       20200618-16:35:26
  go version:       go1.14.4

* Alertmanager version:

$ alertmanager --version
alertmanager, version 0.20.0 (branch: HEAD, revision: f74be0400a6243d10bb53812d6fa408ad71ff32d)
  build user:       root@00c3106655f8
  build date:       20191211-14:13:14
  go version:       go1.13.5

* Prometheus configuration file:
/etc/prometheus $ cat prometheus.yml
global:
  scrape_interval:     15s
  evaluation_interval: 15s

  external_labels:
    monitor: 'promswarm'

rule_files:
  - "swarm_node.rules.yml"
  - "swarm_task.rules.yml"
  - "demo_node.rules.yml"

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    dns_sd_configs:
    - names:
      - 'node-exporter'
      type: 'A'
      port: 9100

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - http://grafana:3000 # Target to probe with Grafana
        - http://prometheus:9090 # Target to probe with Grafana
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115  # The blackbox exporter's real hostname:port

* Alertmanager configuration file:
It's kind of irrelevant to this issue because alertmanager is running in a separte pod in Kubernetes and the problem happens when alertmanager stops.

* Logs:

level=info ts=2020-10-02T14:15:10.621Z caller=main.go:337 msg="Starting Prometheus" version="(version=2.19.1, branch=HEAD, revision=eba3fdcbf0d378b66600281903e3aab515732b39)"
level=info ts=2020-10-02T14:15:10.621Z caller=main.go:338 build_context="(go=go1.14.4, user=root@62700b3d0ef9, date=20200618-16:35:26)"
level=info ts=2020-10-02T14:15:10.621Z caller=main.go:339 host_details="(Linux 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 11 19:12:04 EDT 2020 x86_64 prometheus-6475dc8c7b-js2kt (none))"
level=info ts=2020-10-02T14:15:10.621Z caller=main.go:340 fd_limits="(soft=1048576, hard=1048576)"
level=info ts=2020-10-02T14:15:10.621Z caller=main.go:341 vm_limits="(soft=unlimited, hard=unlimited)"
level=info ts=2020-10-02T14:15:10.642Z caller=main.go:678 msg="Starting TSDB ..."
level=info ts=2020-10-02T14:15:10.642Z caller=web.go:524 component=web msg="Start listening for connections" address=0.0.0.0:9090
level=info ts=2020-10-02T14:15:11.353Z caller=head.go:645 component=tsdb msg="Replaying WAL and on-disk memory mappable chunks if any, this may take a while"
level=info ts=2020-10-02T14:17:12.939Z caller=head.go:706 component=tsdb msg="WAL segment loaded" segment=0 maxSegment=374
level=info ts=2020-10-02T14:17:15.065Z caller=head.go:706 component=tsdb msg="WAL segment loaded" segment=1 maxSegment=374
level=info ts=2020-10-02T14:17:17.432Z caller=head.go:706 component=tsdb msg="WAL segment loaded" segment=2 maxSegment=374
level=info ts=2020-10-02T14:17:19.632Z caller=head.go:706 component=tsdb msg="WAL segment loaded" segment=3 maxSegment=374
level=info ts=2020-10-02T14:17:22.136Z caller=head.go:706 component=tsdb msg="WAL segment loaded" segment=4 maxSegment=374
level=info ts=2020-10-02T14:17:24.352Z caller=head.go:706 component=tsdb msg="WAL segment loaded" segment=5 maxSegment=374
level=info ts=2020-10-02T14:17:26.532Z caller=head.go:706 component=tsdb msg="WAL segment loaded" segment=6 maxSegment=374
...
...
level=info ts=2020-10-02T14:31:06.330Z caller=head.go:706 component=tsdb msg="WAL segment loaded" segment=369 maxSegment=374
level=info ts=2020-10-02T14:31:08.983Z caller=head.go:706 component=tsdb msg="WAL segment loaded" segment=370 maxSegment=374
level=info ts=2020-10-02T14:31:11.307Z caller=head.go:706 component=tsdb msg="WAL segment loaded" segment=371 maxSegment=374
level=info ts=2020-10-02T14:31:13.885Z caller=head.go:706 component=tsdb msg="WAL segment loaded" segment=372 maxSegment=374
level=info ts=2020-10-02T14:31:15.387Z caller=head.go:706 component=tsdb msg="WAL segment loaded" segment=373 maxSegment=374
level=info ts=2020-10-02T14:31:15.415Z caller=head.go:706 component=tsdb msg="WAL segment loaded" segment=374 maxSegment=374
level=info ts=2020-10-02T14:31:15.419Z caller=head.go:709 component=tsdb msg="WAL replay completed" duration=16m4.061215372s
level=info ts=2020-10-02T14:31:17.053Z caller=main.go:694 fs_type=65735546
level=info ts=2020-10-02T14:31:17.053Z caller=main.go:695 msg="TSDB started"
level=info ts=2020-10-02T14:31:17.053Z caller=main.go:799 msg="Loading configuration file" filename=/etc/prometheus/prometheus.yml
level=info ts=2020-10-02T14:31:17.068Z caller=main.go:827 msg="Completed loading of configuration file" filename=/etc/prometheus/prometheus.yml
level=info ts=2020-10-02T14:31:17.068Z caller=main.go:646 msg="Server is ready to receive web requests."
level=info ts=2020-10-02T14:31:26.401Z caller=compact.go:495 component=tsdb msg="write block" mint=1598384434664 maxt=1598385600000 ulid=01EKMVK1SW65N0ADF3HBZM6QJA duration=2.18090327s
level=info ts=2020-10-02T14:31:29.815Z caller=head.go:792 component=tsdb msg="Head GC completed" duration=153.227589ms
level=error ts=2020-10-02T14:33:34.699Z caller=db.go:675 component=tsdb msg="compaction failed" err="reload blocks: head truncate failed: create checkpoint: flush records: write /prometheus/wal/checkpoint.00000248.tmp/00000030: no space left on device"
level=info ts=2020-10-02T14:33:37.991Z caller=compact.go:495 component=tsdb msg="write block" mint=1598385600000 maxt=1598392800000 ulid=01EKMVQ26MDQ71SKEW4TC9TSV3 duration=2.291033222s
level=info ts=2020-10-02T14:33:46.420Z caller=compact.go:495 component=tsdb msg="write block" mint=1598385600000 maxt=1598392800000 ulid=01EKMVQAVQ0YZF182CXW3PEKQA duration=1.853869665s
level=info ts=2020-10-02T14:33:48.984Z caller=head.go:792 component=tsdb msg="Head GC completed" duration=104.36129ms
...
...
level=info ts=2020-10-02T14:57:35.843Z caller=head.go:792 component=tsdb msg="Head GC completed" duration=95.921353ms
level=error ts=2020-10-02T14:59:32.755Z caller=db.go:675 component=tsdb msg="compaction failed" err="reload blocks: head truncate failed: create checkpoint: flush records: write /prometheus/wal/checkpoint.00000255.tmp/00000029: no space left on device"
level=info ts=2020-10-02T15:00:35.479Z caller=compact.go:495 component=tsdb msg="write block" mint=1598457600000 maxt=1598464800000 ulid=01EKMX8DBK6BJ5F511YSGYJMCM duration=2.723784021s
level=info ts=2020-10-02T15:00:42.354Z caller=compact.go:495 component=tsdb msg="write block" mint=1598457600000 maxt=1598464800000 ulid=01EKMX8MBBGPHB020JEH76ECKE duration=2.439220412s
level=info ts=2020-10-02T15:00:44.820Z caller=head.go:792 component=tsdb msg="Head GC completed" duration=89.237455ms
level=error ts=2020-10-02T15:02:23.059Z caller=db.go:675 component=tsdb msg="compaction failed" err="reload blocks: head truncate failed: create checkpoint: flush records: write /prometheus/wal/checkpoint.00000256.tmp/00000027: no space left on device"
level=info ts=2020-10-02T15:03:25.547Z caller=compact.go:495 component=tsdb msg="write block" mint=1598464800000 maxt=1598472000000 ulid=01EKMXDKNKJNZ0D52T7PFXCZ5W duration=2.488213148s
level=info ts=2020-10-02T15:03:31.453Z caller=compact.go:495 component=tsdb msg="write block" mint=1598464800000 maxt=1598472000000 ulid=01EKMXDT3H98F3WQVP3W4ZK1N0 duration=1.803627297s
level=info ts=2020-10-02T15:03:33.829Z caller=head.go:792 component=tsdb msg="Head GC completed" duration=103.364827ms
level=error ts=2020-10-02T15:05:19.442Z caller=db.go:675 component=tsdb msg="compaction failed" err="reload blocks: head truncate failed: create checkpoint: flush records: write /prometheus/wal/checkpoint.00000256.tmp/00000026: no space left on device"
level=info ts=2020-10-02T15:06:22.139Z caller=compact.go:495 component=tsdb msg="write block" mint=1598472000000 maxt=1598479200000 ulid=01EKMXJZXJHWY6CARXYQJ492B2 duration=2.696147591s
level=info ts=2020-10-02T15:06:29.350Z caller=compact.go:495 component=tsdb msg="write block" mint=1598472000000 maxt=1598479200000 ulid=01EKMXK7RE7RDD3X7HH69QTF8R duration=1.879378639s
level=info ts=2020-10-02T15:06:32.188Z caller=head.go:792 component=tsdb msg="Head GC completed" duration=117.686065ms
level=error ts=2020-10-02T15:08:12.894Z caller=db.go:675 component=tsdb msg="compaction failed" err="reload blocks: head truncate failed: create checkpoint: flush records: write /prometheus/wal/checkpoint.00000257.tmp/00000025: no space left on device"
level=info ts=2020-10-02T15:09:15.942Z caller=compact.go:495 component=tsdb msg="write block" mint=1598479200000 maxt=1598486400000 ulid=01EKMXR99Y3DP1QSE5HFSSP2B3 duration=3.047522436s
level=info ts=2020-10-02T15:09:24.526Z caller=compact.go:495 component=tsdb msg="write block" mint=1598479200000 maxt=1598486400000 ulid=01EKMXRJEAABBM4SD16BVV3TBE duration=2.275857153s
level=info ts=2020-10-02T15:09:27.105Z caller=head.go:792 component=tsdb msg="Head GC completed" duration=97.779093ms
level=error ts=2020-10-02T15:11:02.704Z caller=db.go:675 component=tsdb msg="compaction failed" err="reload blocks: head truncate failed: create checkpoint: flush records: write /prometheus/wal/checkpoint.00000258.tmp/00000026: no space left on device"
level=info ts=2020-10-02T15:12:05.150Z caller=compact.go:495 component=tsdb msg="write block" mint=1598486400000 maxt=1598493600000 ulid=01EKMXXF4GQHHA3WCJF2NY4FXH duration=2.44524409s
level=info ts=2020-10-02T15:12:11.292Z caller=compact.go:495 component=tsdb msg="write block" mint=1598486400000 maxt=1598493600000 ulid=01EKMXXNHP7N6JJYD8S3BPHEBC duration=2.021990675s
level=info ts=2020-10-02T15:12:13.941Z caller=head.go:792 component=tsdb msg="Head GC completed" duration=87.655014ms
level=error ts=2020-10-02T15:13:47.998Z caller=db.go:675 component=tsdb msg="compaction failed" err="reload blocks: head truncate failed: create checkpoint: flush records: write /prometheus/wal/checkpoint.00000258.tmp/00000024: no space left on device"
level=info ts=2020-10-02T15:14:49.866Z caller=compact.go:495 component=tsdb msg="write block" mint=1598493600000 maxt=1598500800000 ulid=01EKMY2GHZQMX3VXBHPY27VYW0 duration=1.867483987s
level=info ts=2020-10-02T15:14:56.183Z caller=compact.go:495 component=tsdb msg="write block" mint=1598493600000 maxt=1598500800000 ulid=01EKMY2PGR1K8SHDWXKMGVQYTE duration=2.079231733s
level=info ts=2020-10-02T15:14:58.419Z caller=head.go:792 component=tsdb msg="Head GC completed" duration=92.539269ms

**Comment by Harkishen-Singh** [comment]
Maybe there is some link with this issue as well. https://github.com/prometheus/prometheus/issues/7952

**Comment by brian-brazil** [comment]
@codesome Do you see a potential issue here, or is this just fallout from a disk filling up?

**Comment by davidxianggao** [comment]
My case sounds a bit different situation that the tsdb size never goes down, even after a few times of Prometheus restart. 

Last week when tsdb size reached close to 50GB of FS size, the retention setting was "--storage.tsdb.retention=336h". I changed it to "--storage.tsdb.retention.time=14d" but the size kept growing after a few restarts.

Then I added "--storage.tsdb.retention.size=45GB" with "--storage.tsdb.retention.time=14d" and but still no help.

In the end, I kept "--storage.tsdb.retention.time=40GB" after extending the FS to new size of 60GB. But it quickly filled up the additional new 10GB disk space just 5 days after. 

When I created this ticket, I've blown away the persistent volume and create a brand new 50GB for Prometheus.

**Comment by bradwood** [comment]
I'm seeing this exact issue with 2.20.0 also. It seems as if retention is just completely ignored.

**Comment by michielvangendt** [comment]
We're also having this issue after upgrading from v2.18.2 to v2.21.0 yesterday. Let me know if you would like to see our configuration/logs.
![image](https://user-images.githubusercontent.com/29581995/96186080-2f8a1e00-0f3b-11eb-8671-9c21c0b78247.png)

**Comment by roidelapluie** [comment]
Yes, I would like the logs please. The original logs in this post happen after the out if space,would be nice to see them earlier.

**Comment by roidelapluie** [comment]
Also if you can run `./promtool tsdb list /data` that would be nice.

**Comment by michielvangendt** [comment]
I've attached the logs of 2 instances that were showing this behaviour. I've also included the output of the `./promtool tsdb list /data` command, but this was executed after I've already manually deleted some blocks and restarted the container.
[logs.zip](https://github.com/prometheus/prometheus/files/5387974/logs.zip)

**Comment by roidelapluie** [comment]
What is the command line options of your prometheus server and which instance is in the graph? Is it instance 1 or 2? Thanks.

**Comment by roidelapluie** [comment]
What do the metrics  prometheus_tsdb_time_retentions_total prometheus_tsdb_size_retentions_total and prometheus_tsdb_blocks_loaded look like in those periods?

**Comment by roidelapluie** [comment]
2.19.0 implemented **chunks_head**. That is a new directory in the wal. I am wondering if because of that extra disk space, you would not have run out of disk, making next compactions fail.

**Comment by michielvangendt** [comment]
Instance 2 was shown on the graph above, but I've included a grafana dashboard below to make it more clear. The command-line options that were used:
```
      --web.console.templates=/etc/prometheus/consoles
      --web.console.libraries=/etc/prometheus/console_libraries
      --storage.tsdb.retention.size=8GiB
      --config.file=/etc/prometheus/config_out/prometheus.env.yaml
      --storage.tsdb.path=/prometheus
      --storage.tsdb.retention.time=14d
      --web.enable-lifecycle
      --storage.tsdb.no-lockfile
      --web.external-url=https://prometheus.our.domain
      --web.route-prefix=/
      --storage.tsdb.max-block-duration=2h
```

Here are the metrics you asked for. You'll see that I manually cleaned up older chunks.

**Instance1:**
![Instance1](https://user-images.githubusercontent.com/29581995/96237371-86c0da80-0f9d-11eb-84b6-10c9a954627a.png)

**Instance2:**
![Instance2](https://user-images.githubusercontent.com/29581995/96237411-92140600-0f9d-11eb-9ee8-fe2e7d20a435.png)

**Comment by Subhasis180689** [comment]
We are also facing the same issue. We see exponential growth in chunks_head folder. We don't see data for some days and suddenly it starts working and only shows some period data. We see compaction failed error in the logs.

**Comment by bismarck** [comment]
I'm also running into this issue.  I'm currently running v2.20.1. In my logs I noticed: 
```
panic: write header: write /prometheus/chunks_head/004616.tmp: no space left on device
```
I have retention size set to 325GB and my volume is 500Gi

**Comment by roidelapluie** [comment]
What is the size of prometheus/chunks_head ?

**Comment by bismarck** [comment]
@roidelapluie I had to wipe the disk on the instance that ran out of space, but the other instance is currently at `44.7G`.

**Comment by roidelapluie** [comment]
Where do the logs come from? Did the other instance run out of space?

**Comment by bismarck** [comment]
The logs were from the instance that ran out of space. The other instance with prometheus/chunks_head @ 44.7G is getting close to being out of space (the prometheus dir is currently 464.1G and we have retention size set to 325G)

**Comment by roidelapluie** [comment]
Can we see the logs of that second instance? And also, what are the files in the chunks_head?

**Comment by bismarck** [comment]
[chunks_head.txt](https://github.com/prometheus/prometheus/files/5442545/chunks_head.txt)
I attached the list of files in the chunks_head directory.  Working on getting the logs from Splunk.

**Comment by TimSimmons** [comment]
I'm having similar issues on 2.20.1 with setting only `--storage.tsdb.retention.size`. There are some nodes that are still running size retentions, according to `prometheus_tsdb_size_retentions_total`, but they aren't deleting enough data.

running
```
sort(label_replace(prometheus_tsdb_retention_limit_bytes, "instance", "$1:9100", "instance", "(.*):.*") - on (instance) (node_filesystem_size{mountpoint="/"} - node_filesystem_avail{mountpoint="/"}) < 0)
```
I can see the nodes that are using more disk than their retention limit increasing over the last few weeks
![graph](https://i.imgur.com/paVDm5J.png)

Interestingly it appears that _some_ hosts are trying to do the retention operations but are not deleting enough data, while some are not even trying, despite both groups being over their limit.

I don't see any logs that are not what I'd consider normal `WAL checkpoint complete, Creating checkpoint, Head GC completed, compact blocks`. On hosts that are doing the retentions vs some that are not. on the few hosts I spot checked, the `chunks_head` dir was less than 1GB, same with the WAL.

**Comment by Shadi** [comment]
We are facing similar problems with our pods, we have both `storage.tsdb.retention.size` and `storage.tsdb.retention.time` set, but prometheus is constantly above the limit of size retention, even when it deletes older blocks it does not delete enough, this started to happen after we switch to 2.19 version, and we are seeing it on multiple pods with different configuration, some of them run out of disk space and we have to delete chunks_head content and sometimes wal folder contents manually for it to be able to start.

We are currently seeing it with the following pod, it didn't run out of space but it is using more disk that specified by size retention.

Prometheus options:

```
...
prometheus:
/prometheus@sha256:e7d566a59b2882364b946ba2b3791bfbf60d86ecf5ecb73d81d836a3a0ae5240
    Port:          9090/TCP
    Host Port:     0/TCP
    Args:
      --web.console.templates=/etc/prometheus/consoles
      --web.console.libraries=/etc/prometheus/console_libraries
      --storage.tsdb.retention.size=7152MB
      --config.file=/etc/prometheus/config_out/prometheus.env.yaml
      --storage.tsdb.path=/prometheus
      --storage.tsdb.retention.time=31d
      --web.enable-lifecycle
      --storage.tsdb.no-lockfile
      --storage.tsdb.max-block-duration=2h
...
```

Disk usage by running `du -h` in the prometheus container:
```
...
/dev/sda                  9.1G      8.1G      1.0G  89% /prometheus
...
```

Size of directories inside of /prometheus path:
```
....
214.5M	./wal
18.9M	./chunks_head
....
```
All content:
[du.txt](https://github.com/prometheus/prometheus/files/5464599/du.txt)


![Screenshot 2020-10-30 at 11 44 09](https://user-images.githubusercontent.com/10242258/97696293-aa0f7d80-1aa5-11eb-81f2-1d7d04171d24.png)
![Screenshot 2020-10-30 at 11 44 59](https://user-images.githubusercontent.com/10242258/97696305-ad0a6e00-1aa5-11eb-99a5-e46c3ed1a63a.png)
![Screenshot 2020-10-30 at 11 45 32](https://user-images.githubusercontent.com/10242258/97696312-b0055e80-1aa5-11eb-84be-2ce566388360.png)
![Screenshot 2020-10-30 at 11 46 13](https://user-images.githubusercontent.com/10242258/97696320-b267b880-1aa5-11eb-97ea-34b9efb61ae0.png)
![Screenshot 2020-10-30 at 11 46 47](https://user-images.githubusercontent.com/10242258/97696332-b4ca1280-1aa5-11eb-844a-e1a7a2fbd86a.png)

**Comment by Shadi** [comment]
Another issue we noticed is that sometimes the chunk_heads folder would grow significantly that it would be using more than 20% of the volume size and be even larger than wal/:

```

12.4G   /prometheus/01EKNJ5DXP17BQPQPWRGH1YJ2J
--
14.4G   /prometheus/01EKVBJFJGX8W04WC1BSE4D996
15.9G   /prometheus/01EM14ZBPKZ40GAAZCYHXJY4K8
16.7G   /prometheus/01EM6YD9PBB17WM644N25PNAE2
16.9G   /prometheus/01EMCQSRKJXTH9HP8Z0Z9YT0VE
17.1G   /prometheus/01EMJH8MYK1QGPWA90PT3N8NJG
6.3G    /prometheus/01EMMEVE120P5GWWYTWQZQXHCR
2.3G    /prometheus/01EMN3AQHYZZNSD3S11KBEHMRB
914.9M  /prometheus/01EMNQSK79JWZY4YGCDBDGEYSQ
2.3G    /prometheus/01EMNQXKTJ44P5S17G7A41P3B5
936.1M  /prometheus/01EMNYNAF2RYM934TZ4FGB9H0D
895.4M  /prometheus/01EMP5H1Q3FZ80PWSNNS57KJWW
63.2G   /prometheus/chunks_head
4.0K    /prometheus/queries.active
8.0K    /prometheus/thanos
4.0K    /prometheus/thanos.shipper.json
54.5G   /prometheus/wal

```

**Comment by codesome** [comment]
I think I might know what is happening. We check for retention only when a compaction happens, which is when Head is compacted into a block and when blocks are merged to form bigger blocks - both of them happen in intervals of hours. What were are missing is regular check for retention. So a fix for this would be check for retention (time and size) in the compaction loop even when we don't compact anything.

**Comment by brian-brazil** [comment]
> So a fix for this would be check for retention (time and size) in the compaction loop even when we don't compact anything.

I don't think this is the full solution, as that loop can't happen while a compaction is going on and those can take a whole.

**Comment by Shadi** [comment]
> I think I might know what is happening. We check for retention only when a compaction happens, which is when Head is compacted into a block and when blocks are merged to form bigger blocks - both of them happen in intervals of hours. What were are missing is regular check for retention. So a fix for this would be check for retention (time and size) in the compaction loop even when we don't compact anything.

Looking at the code I can see that the deletion of old blocks happen as part of the reload call:
https://github.com/prometheus/prometheus/blob/master/tsdb/db.go#L1034

and I can see the counter `prometheus_tsdb_reloads_total`  still increasing even when the disk usage is above the retention size.

**Comment by ArthurSens** [comment]
Hey, so I've been experimenting with this bug yesterday, adding a lot of debug messages on master branch and seeing what the logs tell me.

You can see the log lines I've added here:
https://github.com/prometheus/prometheus/compare/master...ArthurSens:debug_retention_fix

After building it, I've started prometheus with this config:
```
./prometheus --log.level=debug --storage.tsdb.retention.size=50MB
```
I've left it there during the night, logs after running for 8 hours can be seen here:
https://gist.github.com/ArthurSens/695e23898c6db5843e9e33cb60d80ab5


One thing that looked really strange for me was the size of head chunks disk mapper at the `BeyondSizeRetention` function. Where it is positive in the first interactions:
```
level=debug ts=2020-10-31T06:56:00.899Z caller=db.go:1155 component=tsdb msg="Looking for beyond size retention deletable blocks" numBlocks=0
level=debug ts=2020-10-31T06:56:00.899Z caller=db.go:1167 component=tsdb msg="Initializing size counter with WAL size and Head chunks written to disk" blocksSizeSum=16165203 headChunksSize=2811608 walSize=13353595 retentionLimit=52428800
.
.
.
level=debug ts=2020-10-31T07:00:00.915Z caller=db.go:1155 component=tsdb msg="Looking for beyond size retention deletable blocks" numBlocks=1
level=debug ts=2020-10-31T07:00:00.915Z caller=db.go:1167 component=tsdb msg="Initializing size counter with WAL size and Head chunks written to disk" blocksSizeSum=16735284 headChunksSize=3070611 walSize=13664673 retentionLimit=52428800
```

But then it becomes a negative number:
```
level=debug ts=2020-10-31T09:00:00.910Z caller=db.go:1155 component=tsdb msg="Looking for beyond size retention deletable blocks" numBlocks=2
level=debug ts=2020-10-31T09:00:00.910Z caller=db.go:1167 component=tsdb msg="Initializing size counter with WAL size and Head chunks written to disk" blocksSizeSum=-106145329 headChunksSize=-128706817 walSize=22561488 retentionLimit=52428800
.
.
.
level=debug ts=2020-10-31T11:00:00.911Z caller=db.go:1155 component=tsdb msg="Looking for beyond size retention deletable blocks" numBlocks=3
level=debug ts=2020-10-31T11:00:00.911Z caller=db.go:1167 component=tsdb msg="Initializing size counter with WAL size and Head chunks written to disk" blocksSizeSum=-229042224 headChunksSize=-260491364 walSize=31449140 retentionLimit=52428800
.
.
.
level=debug ts=2020-10-31T11:00:01.162Z caller=db.go:1155 component=tsdb msg="Looking for beyond size retention deletable blocks" numBlocks=4
level=debug ts=2020-10-31T11:00:01.162Z caller=db.go:1167 component=tsdb msg="Initializing size counter with WAL size and Head chunks written to disk" blocksSizeSum=-376850524 headChunksSize=-394709084 walSize=17858560 retentionLimit=52428800
```

I don't think I'll have the time to investigate this further today, maybe tomorrow I'll have another look and hopefully fix it

**Comment by roidelapluie** [comment]
I think I have found the issue and a bugfix is proposed in #8005. Thanks all.

**Comment by mehyedes** [comment]
@roidelapluie thanks for the fix !

I was just wondering if there was a workaround for this though, until the fix is released.

**Comment by codesome** [comment]
v2.22.1 would include the fix [which will be cut soon](https://github.com/prometheus/prometheus/pull/8146). Note that the disk usage can still go beyond the configured size, but it should go down soon with the next block reload.

**Comment by roidelapluie** [comment]
2.22.1 is out with the fix.
