### ISSUE TITLE
PromQL regexp takes forever

### ISSUE THREAD

**Issue by chicknsoup** [prometheus/prometheus#8010]
**What did you do?**

Upgraded from v2.19 to v2.21

**What did you expect to see?**

```
sd_process_cpu_system{cmd=~".*?(redis|sentinel).*",instance="10.0.0.2:20100"}
```

Expected to see some results

**What did you see instead? Under which circumstances?**

Error executing query: Gateway Time-out

**Others**

This query works as expected
```
sd_process_cpu_system{cmd=~".*?redis.*",instance="10.0.0.2:20100"}
```

It is possibly related to this https://github.com/prometheus/prometheus/pull/7453 ?

Rolling back to 2.19 resolves the issue

**Comment by brian-brazil** [comment]
How long does the working query take, what sort of and how many values does `cmd` have?

@pracucci

**Comment by chicknsoup** [comment]
> 
> 
> How long does the working query take, what sort of and how many values does `cmd` have?
> 
> @pracucci

* The working query takes only around `600ms` and on v2.19 the query returns almost instantly even without `instance label`
* cmd is linux process' cmdline
* count(sd_process_cpu_system{instance="10.0.0.2:20100"} returns 50

**Comment by brian-brazil** [comment]
I can't reproduce easily, what is the cardinality of `cmd`? `count (group by (cmd)(sd_process_cpu_system))`

**Comment by chicknsoup** [comment]
> 
> 
> I can't reproduce easily, what is the cardinality of `cmd`? `count (group by (cmd)(sd_process_cpu_system))`

`count (group by (cmd)(sd_process_cpu_system))` returns 8701, is it too high?

Btw, after some new targets added, the same issue appears on the node with version 2.19. So this is not related to https://github.com/prometheus/prometheus/pull/7453. It seems that some generated `cmd` labels are causing bad regexp performance. Could be the size of the label?

**Comment by brian-brazil** [comment]
9k isn't high, however given the name of the label I guess that you have really long label values. The limit on the commandline is 2MB on my machine, but I still can't see going through 18GB of text taking 2 minutes.

**Comment by chicknsoup** [comment]
> 
> 
> 9k isn't high, however given the name of the label I guess that you have really long label values. The limit on the commandline is 2MB on my machine, but I still can't see going through 18GB of text taking 2 minutes.

You're right, I can see values with over 15k characters. Is there any way to improve the perf or I have to limit the length of label values to below 1k?

**Comment by roidelapluie** [comment]
It seems an issue within the exporter, which should crop those labels, or not expose them. We know that behind the scenes fuzzing Prometheus with long regexes is really slow.

**Comment by chicknsoup** [comment]
Okay, I guess I have to trim down the length of the label values. We can close this issue.
