### ISSUE TITLE
Tracking backfill/bulk-import feature progress

### ISSUE THREAD

**Issue by piroux** [prometheus/prometheus#8016]
## Proposal

As a Prometheus user ardently waiting for the backfilling / bulk-importing feature to be available, I try to keep track of the related Issues and PRs. :rocket: 

But I think it would be easier to have something to track the different iterations to achieve this feature, in the upstream Github repo. For instance, it could be under a Project, or even a simple Milestone, or even with a single main Issue tracking a list of other Issues and PRs (but someone would have to edit it).

Personally, I think a Project would be a better fit, but just anything would be great.

It would allow the Prometheus user community to have a better overview of what has been achieved, what is currently being worked on, what are the futures steps, regarding the progress of the backfilling / bulk-importing feature, which has been quite a debated idea those past few years here, and has seen many hops, to finally lead to an [increase in support and proposals in 2020](https://docs.google.com/document/d/15wKdeFntgUmEnV8kqQ_5iQEIhXnwU8HNm0NKlkR0xk4/edit#).

---

A non-exhaustive list of related Issues and PRs, that could benefit from being under _something_: :umbrella: 

- #11
- #535
- #7119
- #6282

- #5887
- #7950
- #7586
- #7675
- #7999

**Comment by cstyan** [comment]
cc @bwplotka @JessicaGreben @aSquare14

**Comment by codesome** [comment]
I don't think #6282 is related

**Comment by roidelapluie** [comment]
Is this correct? https://github.com/prometheus/prometheus/projects/1

**Comment by piroux** [comment]
Awesome ! :smiley:
