### ISSUE TITLE
Promtool query should print error messages from upstream server

### ISSUE THREAD

**Issue by roidelapluie** [prometheus/prometheus#8018]
## Proposal
**Use case. Why is this important?**

I was running `promtool query instant https://admin:$pw@cortex.inuits.eu/prometheus up` and got an error:

`query error: client_error: client error: 401`

It would have helped me if I would have got the error:

```no org id``` (which in this case is sent by cortex)

```
$ curl https://admin:$pw@cortex.inuits.be/prometheus/api/v1/query
no org id
```

printed in the console too.

**Comment by Harkishen-Singh** [comment]
Will take this up.

**Comment by Harkishen-Singh** [comment]
@roidelapluie do you have any endpoint which I can use? My test environment is not giving errors according to whats required here.

**Comment by roidelapluie** [comment]
Just do the query against https://prometheus.io

**Comment by Harkishen-Singh** [comment]
@roidelapluie could you give an example? That would be helpful.

**Comment by Harkishen-Singh** [comment]
> Just do the query against https://prometheus.io

Unable to reproduce this. BTW, the process is unclear as well.

**Comment by Harkishen-Singh** [comment]
Should this issue be closed?

**Comment by beorn7** [comment]
Hello from the bug scrub.

> Should this issue be closed?

We guess the answer is yes.  :)
