### ISSUE TITLE
Promtool promql unittests get slower the more there are of them

### ISSUE THREAD

**Issue by ivannpaz** [prometheus/prometheus#8019]
## Proposal: Parallel test execution

**Total tests in suite increase testing time almost exponentially**

We are sitting at around 130 tests right now, and tests take 21 mins on our CI/CD pipeline (10 mins on my 8 core local machine)..

By adding a `--workers` or similar setting to `promtool test rules file.json` this could be reduced by a big margin.

Would this be suitable/possible to incorporate into promtool test execution?

**Comment by brian-brazil** [comment]
Unittest execution time should be measured in seconds, not minutes. For example the fairly exhaustive tests for PromQL itself take less than 10s.

It sounds like you've created some very expensive tests with far more data than is needed to test that your rules are working correctly, I'd suggest trimming them down.

**Comment by ivannpaz** [comment]
@brian-brazil Your comment sent me on the right direction for further research. However (and please excuse if this is not the place to ask) I'd like to understand why the following occurs:

**Some context:**

We have rules and tests grouped by "domains", written in jsonnet, which we compile together first:
```
jsonnet rules.jsonnet > rules.json
jsonnet tests.jsonnet > tests.json
```
And then we run the tests:
```
promtool test rules tests.json
```
We found one specific test set, that if we remove from the equation, tests take around 130s to finish, which is great for us, so I did some more combinations and found the following:

**Set 1: Everything**
```
domain1/domain1_tests.jsonnet
domain2/domain2_tests.jsonnet
domain3/domain3_tests.jsonnet
domain4/domain4_tests.jsonnet
```
Tests take 600s

**Set 2: We leave "expensive" tests out**
```
domain1/domain1_tests.jsonnet
// domain2/domain2_tests.jsonnet
domain3/domain3_tests.jsonnet
domain4/domain4_tests.jsonnet
```
Tests take 120s

**Set 3: Only the expensive one**
```
//domain1/domain1_tests.jsonnet
domain2/domain2_tests.jsonnet
//domain3/domain3_tests.jsonnet
//domain4/domain4_tests.jsonnet
```
Tests take 54s

So, is there any gotcha here while mixing tests together? Only difference I can see right now is that we have "eval_time" in most of the tests set to 10m, 120m, 5m, etc, while the "expensive" domain2_tests have "eval_time" of 24h, 25h.

On their own, they are fast... but mixed with the rest, and the whole test suite suffers.

**Comment by brian-brazil** [comment]
I'd have to see the actual tests, but I'm guessing that you're loading in all the data only once and then doing the testing. Each test suit should have its own input data.

For the rare case of a test that needs a day of data, make sure it's only got exactly the data it needs as those tend to be more expensive.

Splitting out your rule groups and thus tests as they're actually split in production will also help.

**Comment by ivannpaz** [comment]
For reference, one of the particular slow tests looks like this:
```jsonnet
{
    "interval": "1h",
    "input_series": [
        {
            "series": "orders_stuck_in_error{instance=\"i1\",env=\"prd\",client_id=\"CLIENT_ID\"}",
            "values": "44-1x25"
            // values: 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19
            // alert:   0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1
            // timing:  0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
        }
    ],
    "alert_rule_test": [
        {
            "eval_time": "24h",
            "alertname": "Number of orders in error above threshold",
            "exp_alerts": [
                {
                    "exp_labels": {
                        "alertname": "Number of orders in error above threshold",
                        "instance": "i1",
                        "env": "prd",
                        "client_id": "CLIENT_ID",
                        "severity": "critical",
                        "service": "processing",
                    },
                    "exp_annotations": {
                        "title": "Number of orders in error for client CLIENT_ID are above threshold",
                        "description": |||
                                    Environment: prd / Host: i1 / Client: CLIENT_ID
                                    Troubleshooting: See the runbook.
                                |||,
                        "runbook": "https://runbook.url/",
                    }
                }
            ]
        },
        {
            "eval_time": "25h",
            "alertname": "Number of orders in error above threshold",
            "exp_alerts": []
        }
    ]
}
```
While the rule itself looks like:
```jsonnet
{
    "alert": "Number of orders in error above threshold",
    "expr": "max by (instance,client_id,env) (min_over_time(orders_stuck_in_error[1d])) >= 20",
    "labels": {
        "severity": "critical",
        "service": "processing"
    },
    "annotations": {
        "title": "Number of orders in error for client  {{ $labels.client_id }} are above threshold",
        "description": |||
                    Environment: {{ $labels.env }} / Host: {{ $labels.instance }} / Client: {{ $labels.client_id }}
                    Troubleshooting: See the runbook.
                |||,
        "runbook": "https://runbook.url/"
    }
}
```
On a side note, I will try spliting tests as you suggest as well.

**Comment by brian-brazil** [comment]
> For reference, one of the particular slow tests looks like this:

That only has 25 samples, it should be really fast to test. How long does it take to run on its own?

> Which leads us to believe that the input series of each test would be loaded for each specific alert_rule_set?

That's how it works. If you've tests using the same inputs it's fine to put them in the same set however, re-ingesting lots of data isn't free.

**Comment by ivannpaz** [comment]
> That only has 25 samples, it should be really fast to test. How long does it take to run on its own?

That one alone on its own, 18s. The problem is when we have them all together...

> That's how it works. If you've tests using the same inputs it's fine to put them in the same set however, re-ingesting lots of data isn't free.

I don't think we share input data from one alert_rule_set to the other, but perhaps that reingestion is killing us anyhow.

I will try spliting all test groups and run them on their own...

**Comment by brian-brazil** [comment]
> That one alone on its own, 18s.

That doesn't sound right at all, it should be measured in milliseconds.

**Comment by ivannpaz** [comment]
> That doesn't sound right at all, it should be measured in milliseconds.

You are totally right. I ran that sole test, but again the full `rules.json` file. I now deactivated everything but that alert rule and that specific test and timing is `0.54s`

**Comment by brian-brazil** [comment]
That sounds more reasonable

**Comment by ivannpaz** [comment]
We have around 112 alerts, distributed in 20 groups. Dind't think that'd be too much.

What still throws me off, is that a certain group, if used in isolation, doesn't take much. 
If the rest of the groups are tested at once, without the specific "expensive" one, it doesn't take much time either... 
But when the specific one, and the rest, are tested at once... boom... 😢

**Comment by brian-brazil** [comment]
Hmm, sounds like we might not be cleaning up between tests properly.

**Comment by ivannpaz** [comment]
![image](https://user-images.githubusercontent.com/16879/95356084-9322a480-08c6-11eb-8cf7-25342eaca3a9.png)

Well, managed to bring tests to a total run time of  ~118s. Changed the pipeline to run `promtool test rules tests.json`, where `tests.json` is a rendered version of each `jsonnet` collector we have for each domain's tests. It's not pretty, but at least is 6X faster.

What should I do with this issue now? While having the feature of parallel tests would be nice (if possible), the actual issue we faced overhere was not directly related to that. Perhaps there's even something off in `promtool` running tests as you suggested 🤷‍♂️ 

In any case, thanks for your invaluable assitance Brian!

**Comment by brian-brazil** [comment]
Yeah, splitting up tests ascross different promtool invocations should only ever be (slightly) slower due to the overheads of starting up new processes so something is wrong here. This will need further investigation.

**Comment by dgl** [comment]
> What still throws me off, is that a certain group, if used in isolation, doesn't take much.
If the rest of the groups are tested at once, without the specific "expensive" one, it doesn't take much time either...
But when the specific one, and the rest, are tested at once... boom... 😢

@ivannpaz: What I think is happening here is a single test with an eval_time of 1d or such is making all the other tests need to calculate all rules from 0 up to that time, I think due to an incorrect assumption in promtool. (PR coming...)

**Comment by ivannpaz** [comment]
@dgl Sure! I can test the PR. Do you have a process for me which I can follow to build this version? I already updated my prometheus local repo copy and checkedout your PR, but I'm not 100% certain on how to build this specific version of promtool :( 

```
Ξ GoLang/prometheus git:(fix-intervals) ▶ gl -3
* 234a25880 - (HEAD -> fix-intervals) promtool: Calculate mint and maxt per test (14 hours ago) <David Leadbeater>
* c5a832b39 - Close resources after failing to startup TSDB (#8031) (20 hours ago) <Arthur Silva Sens>
* fdf1c2922 - Fix metric description of prometheus_tsdb_symbol_table_size_bytes. (#8080) (22 hours ago) <Brian Brazil>
```

**Comment by dgl** [comment]
> If I attempt the naive way of running it from here I get some errors, so I'm certain I'm missing something for the whole build process to work:
> 
> ```
> GoLang/prometheus git:(fix-intervals) ▶ go run cmd/promtool/main.go 

Simply do:

```
go build ./cmd/promtool
./promtool
```

(The issue with doing `go run` like that is there's multiple files, and your run command is only picking up one.)

**Comment by ivannpaz** [comment]
Hi again @dgl , just had a chance to run the whole test suite with the build from your PR and it does seem to improve it:

We have the following:
- 112 alerts distributed in 20 groups
- 460 test cases in 112 alert rule tests

With "current" `promtool` running a `promtool test rules tests.json` takes roughly 20 minutes.

with your fix:
```
$ time ../../GoLang/prometheus/promtool test rules tests.json
Unit Testing:  tests.json
  SUCCESS

../../GoLang/prometheus/promtool test rules tests.json  79.98s user 5.70s system 147% cpu 58.135 total
```
