### ISSUE TITLE
Proposal: Force the alignment of the scrape timestamps

### ISSUE THREAD

**Issue by roidelapluie** [prometheus/prometheus#8032]
## Proposal

Prometheus' TSDB relies on timestamps to b equally distant for double delta compression.

We have introduced in Prometheus 2.22 a mechanism to align the timestamps due to a regression in golang that made the alignment unreliable.

Now, as this appears to be a big win in the block size with unaligned timestamps; +50% size was noticed in my production environment.

Now, we need to decide where we bring this in the future.

Possible directions are:

- Keep the setting as is (2 ms (for scrape intervals > 400ms), on/off switch)
- Keep as is with other defaults
- Allow the user to configure the tolerance
- Disable the feature

## It is a difficult exercise to quote people, so I have extracted a few comments that are not-related to the workaround and the implementation details, but #7976 has the whole context. Thanks for your understanding.

Extract from #7976:

@beorn7 

> There is one possible line of argument that says that the adjustment we are doing here will only cause trouble in bizarre edge cases so it's safe to enable it by default. But then we should enable it permanently because jittery timers can also happen on heavily loaded servers (which incidentally benefit most from better compression). I could be convinced that the premise is true here and we should go down that path.
> 
> The next option is that the TS adjustment is enough of a potential problem that we should just see it as a temporary work around (to mitigate the Go bug or our own sub-optimal bit bucketing for timestamps). Then we are in the situation I described above: Let's not enforce the work around on people that don't need it.
> 
> The final option is that this is a real trade-off between accuracy and better compression, even after the Go bug is fixed or we have improved TS compression. In this case, the conclusion is again that this should be a flag.
> 
> I wholeheartedly agree that we should avoid useless flags. But as discussed above, the flag is only useless if this adjustment could as well be done permanently.
> 
> My proposal is the following: Have a flag that defaults to the adjustment in this PR. Mark this flag as preliminary. If nobody ever complains about the new behavior, we can make it permanent and remove the flag. If people do complain, we can later discuss if we want to remove the adjustment altogether or if we want to keep it as an option (with the default the one way or the other).

@brian-brazil 

> > There is one possible line of argument that says that the adjustment we are doing here will only cause trouble in bizarre edge cases so it's safe to enable it by default. 
> 
> Basically yes. It's safe, but not ideal.
> 
> > But then we should enable it permanently because jittery timers can also happen on heavily loaded servers
> 
> I disagree with this line of argument. The problems this currently causes are sufficiently severe that I think it's tolerable to have a temporary workaround in which we purposefully produce lower quality data, and that's only because the preferable workaround of rolling back our Go version doesn't appear viable.
> 
> That's very different from in the long term purposefully ingesting less accurate data as a performance microoptimisation, and once either the Go issue is resolved or our compression is improved sufficiently I think this should be rolled back.

**Comment by beorn7** [comment]
To provide more context and thoughts (outside of the context of the Go bug and of the huge amount of text we collectively had to produce to decide if there should be an off-switch for a work-around to mitigate a Go regression):

I have seen identically configured servers with identical workload (in HA pairs) that produced significantly different TSDB sizes. My assumption was that one of the servers had to compete for CPU cycles with more (ore greedier) pods on the same Kubelet, thus creating more jitter in the timestamp. This was even before the Go bug, but the Go bug supports my hypothesis.

The effect of timestamp jitter is amplified by the bit bucketing we use for double-delta encoding of the timestamps. In Prometheus 2.x, a timestamp with the perfect double-delta of zero consumes 1bit. Any other double-delta, even if it is just 1ms, will consume at least 16bits. Details see [this issue comment](https://github.com/prometheus/prometheus/issues/5865#issuecomment-616641709). We should obviously fix that.

But even then, timestamps will still need at least 1bit, and they have to be decoded. The impact of the Go regression demonstrates that a lightly loaded server prior to the Go regression (or a server with the work-around in #7976) is using 1bit for a timestamp in the vast majority of cases.

Prometheus already used a run-length encoding for those cases, encoding (IIRC) up to 127 subsequent zeros into 8bit. However, if the case of a zero double-delta is happening almost always, we could leverage this even more. For example, if a chunk has completely regular timestamps, we can just store the starting timestamp and the interval.

Of course, everything we can gain here is merely that one last bit we store per timestamp right now in the best case. With 10 to 12 bits per sample right now on average, that's not much percentage-wise. However, we are already thinking about improving the value compression, too, see #5865. The better we compress samples, the more relevant better TS compression becomes (to state the obvious). But there is another aspect: With the current schema, we still have to _decode_ timestamps, scanning through the bit stream. With completely regular timestamps throughout a chunk, we can reduce decoding to values only, which is an added performance gain.

**Comment by brian-brazil** [comment]
>  thus creating more jitter in the timestamp. This was even before the Go bug, but the Go bug supports my hypothesis.

I've too noticed this, and that was also my hypothesis - though also that the values mightn't compress as well either. For example a perfectly linearly increasing counter wouldn't have an identical increase from scrape to scrape anymore.

> We should obviously fix that.

I agree, that's far from optimal.

> The better we compress samples, the more relevant better TS compression becomes

That's true, however I wonder what the overall impact would be across an entire target. Not everything will be constant or constantly increasing, so the impact will be less than the theoretical best case.

> With completely regular timestamps throughout a chunk, we can reduce decoding to values only, which is an added performance gain.

Do we have an idea of what that costs us, versus the value decoding? I'd expect timestamps to be cheaper, as we don't have to mess with floats. Completely regular timestamps aren't a thing we can rely on for scrapes, though they're already a thing with recording rules.

**Comment by beorn7** [comment]
> Completely regular timestamps aren't a thing we can rely on for scrapes

Not rely on, of course, but with the adjustment feature in place, it is likely enough to happen that we can treat it as a special case during encoding (i.e. if there are irregularities, encode the timestamps as we do it now; if not, compress them into (almost) nothingness).

> Do we have an idea of what that costs us, versus the value decoding?

I guess (but it's only a guess at this point) that we spend quite a bit of time in the whole picking the right bits from the stream. IIRC, we interleave timestamps and values. Even just iterating to a certain value in the middle of a chunk means to inspect and analyze the bitstream up to that sample (and then only fully decode the value at which we arrive).

**Comment by roidelapluie** [comment]
I think it is worth getting downstream involved too, especially the downstreams who compact vertically HA pairs of prometheus:
They have then 2 lines of equally distanced timestamps, which when merged are not compressed anymore.

Prom1 : T=1 T=31 T=61
Prom2 : T=5 T=35 T=65

Vertical compaction: T=1 T=5 T=31 T=35 T=61 T=65

Do those downstreams work like that?

**Comment by brian-brazil** [comment]
They shouldn't, as that's quite unsafe. For example counters could be seen to go backwards due to races.

**Comment by beorn7** [comment]
Yeah, definitely don't merge the timeseries from HA pairs together. You either keep them separate by a label, or you pick one (Cortex has a setup to pick one server from an HA pair and switch to the other, should the picked one die).

**Comment by Windrow14** [comment]
Excuse me.

With Prometheus 2.31.1 (on ubuntu 20.04), I have a problem that "resolved" message is always sent one minute later than "endsAt" time.

I didn't have such problem on 2.29.1 (on ubuntu 18.04).

Is this caused by the timestamp tolerance (2ms by default, which my setup does not meet)?

---

Thu Dec  9 13:17:54 CST 2021
   34  7117 ACCEPT     tcp  --  *      *       192.168.0.130        0.0.0.0/0            tcp dpt:9093
Callback triggered.
json_str: {"receiver":"web\\.hook","status":"resolved","alerts":[{"status":"resolved","labels":{"alertname":"srtsink_packets_sent_losing","instance":"192.168.0.157:9923","job":"srt","monitor":"example","process_identity":"mqtt/opo_client_80e4e7f5-eaa4-46c1-936a-a29d6d3360f5","severity":"warning","srt_socket":"1063990645"},"annotations":{"description":"packets sent from srtsink have been losing for 3 seconds","summary":"packets sent from srtsink have kept losing for 3 seconds"},"startsAt":"2021-12-09T05:16:33.238Z","endsAt":"2021-12-09T05:16:55.238Z","generatorURL":"http://zhao-QiTianM420-N000-C:9090/graph?g0.expr=irate%28packets_sent_lost%7Bjob%3D%22srt%22%7D%5B5s%5D%29+%3E+0\u0026g0.tab=1","fingerprint":"26130f5ce8c1550a"}],"groupLabels":{"alertname":"srtsink_packets_sent_losing"},"commonLabels":{"alertname":"srtsink_packets_sent_losing","instance":"192.168.0.157:9923","job":"srt","monitor":"example","process_identity":"mqtt/opo_client_80e4e7f5-eaa4-46c1-936a-a29d6d3360f5","severity":"warning","srt_socket":"1063990645"},"commonAnnotations":{"description":"packets sent from srtsink have been losing for 3 seconds","summary":"packets sent from srtsink have kept losing for 3 seconds"},"externalURL":"http://k8s-node:9093","version":"4","groupKey":"{}/{severity=\"warning\"}:{alertname=\"srtsink_packets_sent_losing\"}","truncatedAlerts":0}

**Comment by roidelapluie** [comment]
On 08 Dec 21:45, Windrow14 wrote:
> Excuse me.
> 
> With Prometheus 2.31.1 (on ubuntu 20.04), I have a problem that "resolved" message is always sent one minute later than "endsAt" time.
> 
> I didn't have such problem on 2.29.1 (on ubuntu 18.04).
> 
> Is this caused by the timestamp tolerance (2ms by default, which my setup does not meet)?

This is probably not related. I suggest you to ask for help in our community
channels: https://prometheus.io/community

**Comment by roidelapluie** [comment]
This is implemented.
