### ISSUE TITLE
Log when Head compaction results in an empty block

### ISSUE THREAD

**Issue by codesome** [prometheus/prometheus#8034]
We already do it when compacting multiple blocks
https://github.com/prometheus/prometheus/blob/3240cf83f08e448e0b96a4a1f96c0e8b2d51cf61/tsdb/compact.go#L433-L438

Compaction of Head block resulting in an empty blocks goes unnoticed currently. We should log that too.

For contributors, the log should go just before this return
https://github.com/prometheus/prometheus/blob/3240cf83f08e448e0b96a4a1f96c0e8b2d51cf61/tsdb/compact.go#L491

And the log should include the `mint` and `maxt` of the compaction attempted.

**Comment by brian-brazil** [comment]
Might this result in even more logspam when a Prometheus that hasn't run in a while is started back up?

**Comment by frbimo** [comment]
can i take this?

**Comment by codesome** [comment]
> Might this result in even more logspam when a Prometheus that hasn't run in a while is started back up?

Yes, but it is better than no logs. Faced this first hand, without the logs we were not able to figure out what was happening and why was checkpointing happening so often with no indication of any compaction.
