### ISSUE TITLE
character class regex behaviour changed

### ISSUE THREAD

**Issue by sergey-onanchenko** [prometheus/prometheus#8040]
Dear Colleagues,

**What did you do?**

Found changed behavious of character class ( [xyz] ) in new versions.

prometheus 2.16.0:
node_load15{Type=~"[Cc]ouchbase.*"} - works fine

prometheus 2.20.1:
node_load15{Type=~"[Cc]ouchbase.*"} - doesn't work
but found that another syntax works: node_load15{Type=~"[C,c]ouchbase.*"}
 
**What did you expect to see?**
Expect same behaviour as should be according to RE2 https://github.com/google/re2/wiki/Syntax 

**Environment**
prometheus 2.20.1

Am I missing something or this is some regression ?

**Comment by brian-brazil** [comment]
Thanks for the report, this was fixed in https://github.com/prometheus/prometheus/pull/8013 which will be in the next release. It looks like that character class was being converted to a case insensitive match under the covers.
