### ISSUE TITLE
Support json marshalling for structs

### ISSUE THREAD

**Issue by omegas27** [prometheus/prometheus#8043]
## Proposal
**Use case. Why is this important?**

Multiple Yaml marshalling library started to use json tags as the main source for marshalling to yaml which means we need to use specific yaml marshalling libraries as the main marshalling format for prometheus structs.

For more context, see http://web.archive.org/web/20190603050330/http://ghodss.com/2014/the-right-way-to-handle-yaml-in-golang/

**Comment by brian-brazil** [comment]
Can you explain more what the feature is that you wish to add to the Prometheus binary?

The code in this repo is internal, and as far as I'm aware we already have appropriate json tags where we are using JSON.

**Comment by omegas27** [comment]
I am in need of serializing the structs in https://github.com/prometheus/prometheus/tree/master/discovery and those do not really seem internal as they are in use in multiple projects like prometheus-operator or promxy.

My use case is that I need to be able to marshal and unmarshal kubernetes_sd_configs as I need to generate scrape configs whenever we create a new cluster in my operator but our yaml library is using what is outlined in the link I posted previously so this is not getting marshalled properly.

The change would be minimal and I can do it but I wanted to propose my idea first

**Comment by brian-brazil** [comment]
That's all internal code for internal data structures, and others import them entirely at their own risk.

If you need this I'd suggest maintaining your own structs, as none of the marshalling libraries we use have this issue.

**Comment by omegas27** [comment]
In that case, should it clearly not be marked as internal then (e.g. moved into an internal directory) to avoid confusion for users?

**Comment by brian-brazil** [comment]
That'd involve moving ~everything into an internal directory, which we're not willing to do. We're generally willing to let others import our code at their own risk, but that's very different from taking on code and features which we ourselves do not need which would bloat the codebase, set incorrect expectations, and make maintenance more difficult.

**Comment by omegas27** [comment]
Sure, I understand your reasoning
