### ISSUE TITLE
Properly log unknown refs during WAL replay

### ISSUE THREAD

**Issue by codesome** [prometheus/prometheus#8045]
In the below line, `unknownRefs` is an atomic variable, so we should be using `unknownRefs.Load()` to log, else it leads to `count="unsupported value type"`
https://github.com/prometheus/prometheus/blob/dee6ac274e7723cc96774384809e0e8add62955a/tsdb/head.go#L629

**Comment by GayathriVenkatesh** [comment]
@codesome I would like to work on this :)

**Comment by codesome** [comment]
@GayathriVenkatesh sure, go ahead!

**Comment by JinLingChristopher** [comment]
@codesome PTAL https://github.com/prometheus/prometheus/pull/8048
