### ISSUE TITLE
Customize URL prefix on alerts

### ISSUE THREAD

**Issue by bluecmd** [prometheus/prometheus#805]
While -web.hostname allows to set the hostname part of http://$host:$port, the scheme and $port is not settable per se.

The problem I'm having is that for the operator the Prometheus frontend is behind a proxy and needs to be accessed through this proxy. Currently the url is http://host:9090/prefix while I need it to be https://my.longer.hostname/prefix/

**Comment by juliusv** [comment]
This is how parts of the externally exposed URL are configured right now:

- the hostname is a flag
- the path prefix is a flag
- the port is derived from the listening address, but the externally 
  reachable port could actually be different (load-balancer or port forwarding)
- the scheme is hardcoded to `http`

The last two points are problematic and need to be configurable. Now I started a PR to be able to configure the scheme, but then noticed the thing about the port as well. I thought it might be better to just allow setting the entire Prometheus URL externally as one string. We would still need the hostname and path prefix flags though, as the former is used to substitute `localhost` in target links on the status page, and the latter is used for self-links throughout the web UI. Adding a separate flag for the entire URL would introduce partial redundancy (path prefix and hostname information would be repeated and possibly inconsistent). Maybe add *two* new flags, for scheme and external port (if external port flag is empty, it would default to the listening port)?

/cc @fabxc

**Comment by brian-brazil** [comment]
For me the hostname I'd display is different (and a lot shorter) than the full hostname that you need to get to the prometheus server. If anything I'd like to be able to determine links automagically from the labels for all targets (in my case it's a simple concatenation), maybe we need a `__display` target label?

**Comment by juliusv** [comment]
For that, you'd still need to be able to configure what the default externally visible hostname is, so this sounds like an orthogonal issue. Granted, just configuring the hostname might not be enough, as the external scheme, port, and endpoint of targets (if they are reachable through an LB at all) could be all different as well. That would then have to be configurable via some display relabeling options, but I see that as an orthogonal issue (and maybe too much feature bloat to put it into Prometheus TBH).
