### ISSUE TITLE
tests: Move from `t.Errorf(` `t.Fail` usages on comparison to `testutil.Ok` / `Assert` / `Equals` 

### ISSUE THREAD

**Issue by bwplotka** [prometheus/prometheus#8063]
Example (https://github.com/prometheus/prometheus/blob/a282d2509971174301408c5a5f96946c478dfb0f/tsdb/querier_test.go#L1526):

```
                       if len(matches) != len(c.exp) {
				t.Errorf("Evaluating %s, length of result not equal to exp", c.pattern)
			} else {
				for i := 0; i < len(c.exp); i++ {
					if c.exp[i] != matches[i] {
						t.Errorf("Evaluating %s, unexpected result %s", c.pattern, matches[i])
					}
				}
			}
```
Should be  just:
```
testutil.Equals(t, exp, matches)
```

Potential good first issue for @GayathriVenkatesh

**Comment by bwplotka** [comment]
The best way to tackle this is to search for `t.Error`, `t.Errorf` and `t.Fail` within Prometheus code.

**Comment by codesome** [comment]
And `t.Fatal`, `t.Fatalf`

**Comment by wawa0210** [comment]
Is anyone following this issue, if not, I am willing to try to fix it

**Comment by ArthurSens** [comment]
Hi @wawa0210, I think @GayathriVenkatesh is working on it already :slightly_smiling_face:.

**Comment by wawa0210** [comment]
Got it, I didn’t see that @GayathriVenkatesh is already working on this

**Comment by Creatone** [comment]
I guess that fixing this was abandoned, so that's why I made PR.
