### ISSUE TITLE
TSDB: cold and hot data separation

### ISSUE THREAD

**Issue by storyicon** [prometheus/prometheus#8070]
## Proposal
**Use case. Why is this important?**
I'm considering hot and cold data separation for TSDB, which works like this:
```
Data written to SSD within 7 days, older data moved to HDD, does not affect query.
```
This is expected to reduce the cost of disk usage and the impact on performance.

I have some questions that I'm not sure about:
1. existence of existing solutions. (I tried to find but nothing was found)
2. community attitudes towards it (e.g. whether it should be integrated into TSDB or not)
3. any potential problems(For example, similar attempts and discussions were made and then abandoned.)

**Comment by storyicon** [comment]
If the community thinks that this feature should be integrated into TSDB, I think it can start from letting TSDB support multiple directories and discovering Blocks dynamically.

**Comment by brian-brazil** [comment]
It is recommended that all data be on SSD, mixing in slower storage with mmap can cause problems. You can always do this yourself under the covers, as symlinking the blocks should work.

**Comment by codesome** [comment]
We use hard links for snapshots where it has to be on the same file system. And what Brian said above. Supporting multiple filesystems is not something we plan to do, hence closing this.

**Comment by storyicon** [comment]
I'm sorry I'm late. Thank you for your attitude.
``` mixing in slower storage with mmap can cause problems.```
 @brian-brazil  I'm interested in knowing exactly what problems it would pose, I tried searching for information about it but didn't find anything, can you briefly talk about it or give me a link?

@codesome Thanks for the heads-up, I'll see if there's a compromise solution.
