### ISSUE TITLE
Swarm Service Discovery: Smarter, more efficient retrieval of data.

### ISSUE THREAD

**Issue by darkl0rd** [prometheus/prometheus#8073]
As it stands, all objects [tasks,nodes,networks,..] are pulled from the swarm API on interval N for each service discovery block.
In a relatively small swarm (10 nodes), I have ~400 containers with 9 service discovery blocks. For each iteration, currently 120+ MB is pulled over the line.

Rather than GET'ting all objects from the API each time and filtering the output on the Prometheus side through relabeling, we could be a lot smarter and more efficient by not pulling the (majority) of irrelevant data in the first place. The Swarm API has built-in support for (basic) filtering operations.

I actually noticed this, due to load spikes on one of the manager nodes. In my case, I run a "Caddy" container on a manager node which exposes the Swarm API, through mounting the socket and in turn exposing it to the Prometheus backend.

**Comment by roidelapluie** [comment]
Thanks, for those numbers, indeed it makes sense, I will implement it.

**Comment by roidelapluie** [comment]
https://github.com/prometheus/prometheus/pull/8074

**Comment by roidelapluie** [comment]
400 containers producing 120MB, could you look at the dump and tell us what's there exactly? That seems like a lot.

**Comment by darkl0rd** [comment]
GET /v1.40/tasks returns around 11Mb 
GET /v1.40/services returns around 2Mb

That together accounts for around 117 Mb (each called 9 times, once for each discovery block)
The rest is the calls to /nodes etc.

**Comment by brian-brazil** [comment]
> GET /v1.40/tasks returns around 11Mb

I presume you mean MB not Mb.

> That together accounts for around 117 Mb (each called 9 times, once for each discovery block)

It's only called once if the discovery configs are identical.

That's still 27kB per task, which feels high.

**Comment by darkl0rd** [comment]
> > GET /v1.40/tasks returns around 11Mb
> 
> I presume you mean MB not Mb.

Yes, MegaByte.

> > That together accounts for around 117 Mb (each called 9 times, once for each discovery block)
> 
> It's only called once if the discovery configs are identical.

The configs are not identical, they all have a different relabel block to filter on “prometheus-job”. The reason I raised this issue, to perform the filtering before pulling in the data.

> That's still 27kB per task, which feels high.
Have a look at a swarm task definition, they’re pretty large.

**Comment by brian-brazil** [comment]
> The configs are not identical, they all have a different relabel block to filter on “prometheus-job”.

The specific discovery needs to be identical, other aspects of the scrape config such as the relabelling don't matter.

**Comment by roidelapluie** [comment]
Could we get your caddy logs to better understand how prometheus fetches the data (e.g. if we fetch it 9 times).

**Comment by darkl0rd** [comment]
Sure, seeing is believing right - attached 5m of logs.
[prometheus_caddy-swarm-api.log](https://github.com/prometheus/prometheus/files/5423479/prometheus_caddy-swarm-api.log)

**Comment by brian-brazil** [comment]
Can you share your config? You can use relabelling to specify the port.

**Comment by roidelapluie** [comment]
https://github.com/prometheus/prometheus/blob/4e5b1722b342948a55b3d7753f6539040db0e5f0/documentation/examples/prometheus-dockerswarm.yml#L20-L24 is how you can do. This is for the nodes but can be adapted for the tasks too.

**Comment by darkl0rd** [comment]
I am using the 'port' attribute as advertised here: https://prometheus.io/docs/prometheus/latest/configuration/configuration/#nodes
```
# Role of the targets to retrieve. Must be `services`, `tasks`, or `nodes`.
role: <string>

# The port to scrape metrics from, when `role` is nodes, and for discovered
# tasks and services that don't have published ports.
[ port: <int> | default = 80 ]
```

See also [https://github.com/prometheus/prometheus/issues/7684](url)

**Comment by darkl0rd** [comment]
Anything else I can provide to help analysis & resolve this?

**Comment by roidelapluie** [comment]
Could you test by seeing the port with relabeling?

**Comment by darkl0rd** [comment]
> Could you test by seeing the port with relabeling?

Sure, however I am not sure how that is supposed to work. Most of the services I monitor are on Overlay networks and do not expose any ports. For this you implemented 7684, the explicit definition of a port on the discovery configuration. Without setting it, nothing is discovered and there will be nothing to relabel.

**Comment by roidelapluie** [comment]
```
  - job_name: 'service2'
    scheme: http
    metrics_path: "/metrics"
    dockerswarm_sd_configs:
      - host: http://my-swarm-api:9090
        role: tasks
        port: 80
    metrics_relabel_configs:
      - source_labels: [__address__]
        regex: '(.*):80'
        target_label: __address__
        replacement: "$1:4321"
```

**Comment by darkl0rd** [comment]
> ```
>   - job_name: 'service2'
>     scheme: http
>     metrics_path: "/metrics"
>     dockerswarm_sd_configs:
>       - host: http://my-swarm-api:9090
>         role: tasks
>         port: 80
>     relabel_configs:
>       - source_labels: [__address__]
>         regex: '(.*):80'
>         target_label: __address__
>         replacement: "${1}:4321"
> ```

I'll give this a go - seems very hacky to me. Using a "fake" static port to ensure discovery of internal services.
Also, even if this works, that would reduce the discovery with a factor 9 (Discovery will only take place once, because all the blocks are identical). However - we will still be pulling in a lot of data on each 'refresh', which was the reason for reporting this issue, allowing filtering to take place prior to pulling in the data for processing.

**Comment by roidelapluie** [comment]
Can you run a /tasks?filter= query and tell us what would be the difference?

**Comment by darkl0rd** [comment]
140 KB filtered on label (e.g. prometheus-job="cadvisor" => 10 tasks; one per node)
11.5 MB unfiltered

Implementing the suggested port relabel "hack" above we gain a factor N, N being the amount of discovery blocks
9 Discovery Blocks * 11.5 MB =~ 103.5MB versus just 11.5MB of data to be processed by Prometheus.

Implementing the filtering of tasks on the Swarm API level results in a 84x smaller dataset (11.5 * 1024 / 140) - this is by filtering on a label "prometheus-job=cadvisor" (10 tasks) as mentioned above.

Below an overview of data processed per minute, based on the 9 discovery blocks present in my configuration:

Results without filter and without relabel "hack": 103.5MB
Results without filter but with relabel "hack": 11.5MB 

Results with filter:  140KB * 9 = 1.26MB 
Results with filter and relabel "hack": 140KB

**Comment by roidelapluie** [comment]
Thanks. #8074 makes sense then.
