### ISSUE TITLE
Add TLSClientConfig to Promtool query subcmds

### ISSUE THREAD

**Issue by mrueg** [prometheus/prometheus#8081]
## Proposal
**Use case. Why is this important?**
Prometheus can be secured by server and client cert auth. Currently promtool only supports to send HTTP client requests. It would be great if promtool had options to execute queries by providing a cert and keyfile for client cert auth as well as supporting TLS from server side.

**Comment by beorn7** [comment]
Hello from the bug scrub.

We believe this was fixed by #11487.
