### ISSUE TITLE
Opening TSDB ReadOnly can corrupt TSDB (non-sequential files)

### ISSUE THREAD

**Issue by roidelapluie** [prometheus/prometheus#8086]
When we Open TSDB in read only, programmatically, we should still take the lock. Not doing so often leads to "un-sequential" mmap files errors, if Prometheus is still running. I think that this behavior is not correct and that we should take the lock to prevent that kind of issues.

**Comment by brian-brazil** [comment]
The whole point of ReadOnly is that we can use it when Prometheus is running.

**Comment by roidelapluie** [comment]
Then we should take the necessary action to prevent it to corrupt tsdb

**Comment by bwplotka** [comment]
Agree, help wanted to ensure this :upside_down_face:

**Comment by codesome** [comment]
Now with the read-repair of m-map chunks we have a issue that the "read only" DB is not read only anymore.

**Comment by codesome** [comment]
But I am curious how opening in read only mode can corrupt the DB, we don't write anything that can corrupt it (minus the repair now), it would only read the file. Any steps to reproduce?

**Comment by Wiewiogr** [comment]
Do we know if this is still the case? If I use tsdb.OpenReadOnly(), will it corrupt the database that it's reading?

**Comment by codesome** [comment]
@roidelapluie have you faced any issues lately? Maybe it is time to close this issue.

**Comment by machine424** [comment]
The RO Head can alter the mmap chunks in `repairLastChunkFile` and also in `removeCorruptedMmappedChunks`
But it can also cut new chunks while playing the WAL `processWALSamples->mmapChunks` as we see here https://github.com/prometheus/prometheus/issues/11618.

I'm working on a patch here https://github.com/prometheus/prometheus/pull/13218

**Comment by beorn7** [comment]
Fixed by #13218.
