### ISSUE TITLE
Add Filters by Tag for Azure VM's to azure_sd_config

### ISSUE THREAD

**Issue by infa-kparida** [prometheus/prometheus#8092]
## Proposal
Add filters to azure_sd_config so that each job can be defined to discover only those instances that are specific to the job instead of scanning through all the VM's in the subscription 

We have different teams sharing same Prometheus where requirements are defined in jobs specific to the team.For example we have node exporter but team A need metrics to be scraped every 10s but teamB need to scrape every 30s.Without filter its very difficult to manage the jobs effectively.

We are using 3 SD mechanism.
ec2_sd_config
azure_sd_config
gce_sd_config

It looks like except azure_sd_config the other 2 are supporting the filter mechanism.

**Comment by brian-brazil** [comment]
Is the information you need for this not already via relabelling?

We only add this when it's a performance issue, not for filtering as that's what relabelling is for.

**Comment by infa-kparida** [comment]
Agree. Yes Relabelling can be used to write specific filtered metrics into the disk.However before writing Prometheus discovers all the targets and scrapes them and then use compute power to relabel them.So that will affect the performance.

If we are dropping the targets before prometheus scrapes itself that will enhance the  performance.

**Comment by brian-brazil** [comment]
> However before writing Prometheus discovers all the targets and scrapes them and then use additional compute power to relabel them.

That's not how it works. It's presumed that the cost of target relabelling is so small that it doesn't matter, and we only scrape what's left at the end of relabelling.

> If we are dropping the targets before prometheus scrapes itself that will enhance the performance.

Relabelling already allows for this.

**Comment by infa-kparida** [comment]
Ohh thats good to know.Thank you for those clarifications.In that case we can go ahead with relabelling.Thanks a ton @brian-brazil
