### ISSUE TITLE
error reading base template: open templates\_base.html: The system cannot find the path specified.

### ISSUE THREAD

**Issue by luoMonkeyKing** [prometheus/prometheus#8097]
with prometheus 2.19 on windows10, the default web page, http://localhost:9090/graph, fails with:

error reading base template: open /\templates\_base.html: file does not exist

**Comment by brian-brazil** [comment]
Where did you get the binary from?

**Comment by luoMonkeyKing** [comment]
from https://github.com/prometheus/prometheus/tree/release-2.19

**Comment by luoMonkeyKing** [comment]
level=info ts=2020-10-22T08:21:59.263Z caller=main.go:341 msg="No time or size retention was set so using the default time retention" duration=15d
level=info ts=2020-10-22T08:21:59.263Z caller=main.go:376 msg="Starting Prometheus" version="(version=, branch=, revision=)"
level=info ts=2020-10-22T08:21:59.263Z caller=main.go:377 build_context="(go=go1.15.1, user=, date=)"
level=info ts=2020-10-22T08:21:59.263Z caller=main.go:378 host_details=(windows)
level=info ts=2020-10-22T08:21:59.263Z caller=main.go:379 fd_limits=N/A
level=info ts=2020-10-22T08:21:59.263Z caller=main.go:380 vm_limits=N/A
level=info ts=2020-10-22T08:21:59.265Z caller=web.go:538 component=web msg="Start listening for connections" address=0.0.0.0:9090
level=info ts=2020-10-22T08:21:59.265Z caller=main.go:737 msg="Starting TSDB ..."
level=info ts=2020-10-22T08:21:59.272Z caller=head.go:645 component=tsdb msg="Replaying WAL and on-disk memory mappable chunks if any, this may take a while"
level=info ts=2020-10-22T08:21:59.272Z caller=head.go:706 component=tsdb msg="WAL segment loaded" segment=0 maxSegment=5
level=info ts=2020-10-22T08:21:59.273Z caller=head.go:706 component=tsdb msg="WAL segment loaded" segment=1 maxSegment=5
level=info ts=2020-10-22T08:21:59.274Z caller=head.go:706 component=tsdb msg="WAL segment loaded" segment=2 maxSegment=5
level=info ts=2020-10-22T08:21:59.274Z caller=head.go:706 component=tsdb msg="WAL segment loaded" segment=3 maxSegment=5
level=info ts=2020-10-22T08:21:59.277Z caller=head.go:706 component=tsdb msg="WAL segment loaded" segment=4 maxSegment=5
level=info ts=2020-10-22T08:21:59.277Z caller=head.go:706 component=tsdb msg="WAL segment loaded" segment=5 maxSegment=5
level=info ts=2020-10-22T08:21:59.277Z caller=head.go:709 component=tsdb msg="WAL replay completed" duration=4.9866ms
level=info ts=2020-10-22T08:21:59.278Z caller=main.go:753 fs_type=unknown
level=info ts=2020-10-22T08:21:59.278Z caller=main.go:754 msg="TSDB started"
level=info ts=2020-10-22T08:21:59.278Z caller=main.go:904 msg="Loading configuration file" filename=C:\prometheus\src\prometheus\documentation\examplesaa\prometheus.yml
level=info ts=2020-10-22T08:21:59.292Z caller=main.go:932 msg="Completed loading of configuration file" filename=C:\prometheus\src\prometheus\documentation\examples\prometheus.yml
level=info ts=2020-10-22T08:21:59.293Z caller=main.go:705 msg="Server is ready to receive web requests."

**Comment by brian-brazil** [comment]
Hmm, does this also happen with the latest version?

**Comment by luoMonkeyKing** [comment]
Well, I did not try the latest version? But the 2.19.3 version is ok on Linux, I don’t know if I am missing any configuration

**Comment by brian-brazil** [comment]
Your report is about Windows, and this is not something that requires any configuration.

**Comment by luoMonkeyKing** [comment]
Yes, but I can't find the cause of the problem now, so that I can't debug the code now. Can you help find the reason? Thanks

**Comment by luoMonkeyKing** [comment]
By the way, my go version is 1.15

**Comment by brian-brazil** [comment]
This would be a build time problem, if it happens with a given binary it'll continue happening.

**Comment by luoMonkeyKing** [comment]
Is there any solution? When I used version 2.3.2 before, it was normal on windows10

**Comment by brian-brazil** [comment]
Can you tell us if this happens with the latest version?

**Comment by luoMonkeyKing** [comment]
Ok, I will download a new version to try, and I will reply to you if there is a result

**Comment by roidelapluie** [comment]
The issue is that you have built Prometheus with go build.

**Comment by roidelapluie** [comment]
Please run `make assets` before go build.

**Comment by roidelapluie** [comment]
or simply try: `cd web/ui && go generate`, which could also work.

**Comment by luoMonkeyKing** [comment]
I tried cd web/ui && go generate, and after starting it with IDEA Goland development tool, the same error was reported

**Comment by brian-brazil** [comment]
It looks like this is a question about building Prometheus from source, it makes more sense to ask questions like this on the [prometheus-developers mailing list](https://groups.google.com/forum/#!forum/prometheus-developers) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
