### ISSUE TITLE
Error parsing commandline arguments: unexpected false

### ISSUE THREAD

**Issue by fcddk** [prometheus/prometheus#8099]
Error parsing commandline arguments: unexpected false
prometheus: error: unexpected false

**Comment by fcddk** [comment]
./prometheus --storage.tsdb.wal-compression=false

**Comment by brian-brazil** [comment]
See https://github.com/alecthomas/kingpin#boolean-values

This would have to be changed upstream.

**Comment by fcddk** [comment]
thanks!

**Comment by brian-brazil** [comment]
We looked at this in the bug scrub. This makes sense to support, however this would have to be done upstream rather than in Prometheus.
