### ISSUE TITLE
Removing old data it not happening if "no space left on device" regardless retention params

### ISSUE THREAD

**Issue by VShox** [prometheus/prometheus#8100]
**What did you do?**
Having Prometheus running with retention.time =15d we are experience catch22, when "no space left on device" in attempt to scrape new data & write them to /wal AND memory not been freed more than 15days as it looks like removing old data happens only after compaction which means depends on it.

**What did you expect to see?**
I do expect to see that retention.time will be respected regardless ability to write and do not depend on it.

**What did you see instead? Under which circumstances?**
Instead of that the memory was not freed even after 15 days

**Environment**
prometheus:v2.13.1 inside of k8s

* System information:

Linux 4.14.165-133.209.amzn2.x86_64 x86_64

* Prometheus version:

prometheus, version 2.13.1 (branch: HEAD, revision: 6f92ce56053866194ae5937012c1bec40f1dd1d9)
  build user:       root@88e419aa1676
  build date:       20191017-13:15:01
  go version:       go1.13.1

**Comment by roidelapluie** [comment]
Hello,

It seems that recent prometheus version should not have this issue anymore. Can you update to 2.22 and check this? Thanks.

**Comment by brian-brazil** [comment]
We looked at this in the bug scrub, and there's not enough information to go on here to indicate an issue. In general, once you run of of disk space all bets are off.
