### ISSUE TITLE
Add Organizations API to EC2 Service Discovery

### ISSUE THREAD

**Issue by MartinLeedotOrg** [prometheus/prometheus#8101]
## Proposal
AWS has an Organizations API that allows you to discover accounts within an organizational unit (ou).

Prometheus EC2 Service Discovery requires each account to be specified individually. This could be achieved more reliably by specifying an ou to traverse and to add each account found to the list of accounts to be checked by EC2 SD.

If this is a sensible feature to add I'm happy to help put together a PR for it.

**Comment by brian-brazil** [comment]
How would that work with authentication, and the multitude of different ways that auth can work with AWS?

**Comment by MartinLeedotOrg** [comment]
In the same way that EC2 SD requires a role to assume in the target account, Org SD would require a role to assume in the management account that has organizations:Describe* and organizations:List*.

**Comment by brian-brazil** [comment]
My question is more once you have a list of accounts, how do you authenticate to those accounts?

**Comment by brian-brazil** [comment]
Also, how would you gain access at the network level to the accounts to be able to talk to their targets?

**Comment by MartinLeedotOrg** [comment]
Currently the SDConfig takes a role_arn which looks like:
arn:aws:iam::1234567890:role/MonitoringService

It then, if that role is set, assumes that role and does the ec2.DescribeInstances dance.

My suggestion is to also provide an optional:
ou_default_role
ou
ou_management_arn

And then to create a role_arn list by getting the account number from the ou and appending the ou_default_role

The config would look like:
```
scrape_configs:
  - job_name: 'foo'
    ec2_sd_configs:
      - ou: ou-abcdef
        ou_management_arn: awn:aws:iam:managementaccount:role/Discovery
        ou_default_role: Monitoring
```

The network level is the same approach as in the current discovery - i.e. just done through assumed roles.

**Comment by brian-brazil** [comment]
> Currently the SDConfig takes a role_arn which looks like:

That is only 1 way of the 10+ ways that auth can work with AWS. How does this work with the others?

I'm wary of adding complexity like this for something that only covers one tiny corner of the potential use cases, and requires yet more options that'll then go on to interact weirdly with all the other auth mechanisms which is something we've had issues with for AWS several times in the past.

This feels like adding discovery discovery, which would require a whole new DSL, secret handling etc. to work.

> The network level is the same approach as in the current discovery - i.e. just done through assumed roles.

Scrapes have no knowledge of AWS, as discovery is an independent process. They're simple HTTP requests.

**Comment by MartinLeedotOrg** [comment]
> That is only 1 way of the 10+ ways that auth can work with AWS. How does this work with the others?

This proposal doesn't touch authentication.

Service Discovery currently exclusively uses roleARN for cross account authorization for describing instances in other accounts. This proposal doesn't add anything new in terms of auth and only uses what is already supported.

AWS strongly recommends against running infrastructure in the management account, so assumed roles is practically the only way people will ever want to talk to the organizations API anyway.

> This feels like adding discovery discovery, which would require a whole new DSL, secret handling etc. to work.

That's exactly what it is, but there's no additional secret handling to work on as far as I can see. The simplest approach I can see is that instead of returning a target_group per account we return a target_group per ou and add the account as a __meta_ec2_account label

> Scrapes have no knowledge of AWS, as discovery is an independent process. They're simple HTTP requests.

This proposal doesn't change this at all. We would still get a target group back from service discovery exactly how we do now. The only difference is instead of the targets all belonging to a single account they'd belong to a single OU.

**Comment by brian-brazil** [comment]
> This proposal doesn't touch authentication.

That would be the problem I'm seeing. Once you have a list of accounts, how do you authenticate to each of them to find their targets? Does that work with all the different auth methods? Based on experiences with other SDs I'd also expect to see requests to need to filter that list, or have special handling for some of them. So we'd probably be talking about a new form of relabelling on top of that, on top of two levels of AWS auth.

Discovery discovery is a whole new set of problems on top of discovery, and discovery is enough of a problem on its own (with AWS being notable for the complexity its myriad of ever growing auth methods bring). The proposed optional fields also smell like business logic, as I see none of those fields in the API docs. Business logic like that does not belong hardcoded in SD code, we can't make any presumptions about how users have laid out their organisations and accounts.

I have a suspicion that this would be quite complex to do in a proper generic fashion, and that for the level of flexibility you seem to be asking for you might be better off regenerating the config file when there's a new account.

**Comment by MartinLeedotOrg** [comment]
> you might be better off regenerating the config file when there's a new account.

We already do regenerate the configuration ourselves with a sidecar process, and that works fine for our purposes.

I really do think this a problem that other people will have in the future, which is why I think it would be a useful addition to service discovery.

> Once you have a list of accounts, how do you authenticate to each of them to find their targets? Does that work with all the different auth methods?

The mechanism for authenticating to each account is no different to how it is now, just the method of discovering accounts changes from manually populating them in the config file to discovering them based on the OU they belong to.

>The proposed optional fields also smell like business logic, as I see none of those fields in the API docs. Business logic like that does not belong hardcoded in SD code, we can't make any presumptions about how users have laid out their organisations and accounts.

OUs, if used, contain zero or more accounts. They can always be queried from the Management Account. The only assumption made here is that each account within an OU is set up similarly with regards to cross account access and roles being available. As that's pretty much the point of Organizations I think that it's rather safe.

**Comment by brian-brazil** [comment]
> The only assumption made here is that each account within an OU is set up similarly with regards to cross account access and roles being available.

That is an assumption, but the broader assumption is that a) you care about all OUs within the organisation and b) all those OUs are set up in this fashion. That seems like a pretty shaky assumption, particularly as one incorrectly setup account should break discovery for all the rest.

**Comment by MartinLeedotOrg** [comment]
I'm not suggesting scraping the entire organisation - just the OUs of interest.  For example, a common pattern is to have separate OUs for dev, prod and staging. Each of those would be targetted individually. To clarify, an Organization contains one or more OUs. An OU contains other OUs and accounts. Using this proposal the user could start anywhere in this tree that they wanted.

An incorrectly set up account would cuase an error when attempting to assume the role in it to list instances. That could just be logged out as a warning rather than breaking discovery.

**Comment by brian-brazil** [comment]
> I'm not suggesting scraping the entire organisation - just the OUs of interest.

That is the question, how do you know which are of interest. Does a user have to list them all? A regex? What if they want to exclude a particular subtree or account? What about other information a OU might contain? What are the defaults?

> That could just be logged out as a warning rather than breaking discovery.

Silently ignoring targets is unwise, on error a SD should continue to use the last good state and it is considered a bug for a SD to do otherwise.

**Comment by MartinLeedotOrg** [comment]
I feel like something is being lost in communication here.

Let's say I have an OU for all my dev accounts called ou-123456. I might be adding a new dev account every time we bring a new dev on board, or want to try a new experiment.  I'd like to be able to run EC2 Service Discovery in all of those accounts.

I would like to simply add something like 
```
aws_ous:
  - ou-123456
```

to my scrape config, and have EC2 SD run in all accounts within that OU.

The OU changes very, very rarely. Accounts which are in this OU change potentially many times a day.

There is no default, this is a feature for AWS users who are managing multiple accounts, almost always with some sort of tooling.

**Comment by brian-brazil** [comment]
I understand that, I also understand from experience that that would not be sufficient for many users who want to do more complex operations based on membership of several OUs and any other metadata that AWS currently has or in future adds in relation to these. I have not just to think about the happy simple case, but every other case that users are likely going to ask for if we start going down the path of discovery discovery.

**Comment by roidelapluie** [comment]
The less API calls we need to do for one service discovery, the best it is. I do not believe in `discover discover`, because Prometheus itself is not multi-tenant. Error behaviour is also questionable.

**Comment by MartinLeedotOrg** [comment]
Happy to adjust error behaviour, I'm more interested in agreeing on functionality first.

Prometheus currently doesn't do any complex operations based on accounts other than at the label/relabel stage as I understand it. As all I'm interested in doing is providing a list of accounts to discovery with perhaps an additional account label, I believe everything that currently works will still work.

**Comment by brian-brazil** [comment]
> Prometheus currently doesn't do any complex operations based on accounts other than at the label/relabel stage

Prometheus doesn't do any operations on accounts at all, it knows nothing of them. We work in terms of targets which happen to be within an account but that's all hidden from us by the libraries we use.

**Comment by MartinLeedotOrg** [comment]
Service Discovery works by using a role to get a list of all targets within
an account.

Account discovery would use an OU to get a list of all accounts to then get
a list of all targets.

I don’t see that the two concepts are all that different.

**Comment by brian-brazil** [comment]
We looked at this in the bug scrub, and this is an unusual use case that is also quite complex in the general case. Accordingly we're going to close this off. You could also consider something like Consul.
