### ISSUE TITLE
React-only frontend feature flag

### ISSUE THREAD

**Issue by jzelinskie** [prometheus/prometheus#8123]
## Proposal

I propose to add a CLI-flag to the Prometheus binary that forces only the react frontend to be served.
This could be a boolean switch (e.g. `--react-only=True`) or an enumeration (e.g. `--frontend=default`, `--frontend=react`).

**Use case. Why is this important?**

I'd like to restrict my instance so that users do not have the choice between frontends, but are forced to use the react one.
This is partially to avoid confusion, but also allows us to depend on functionality that always/never present in a particular frontend. It has the nice side effect of encouraging us to surface any bugs/issues upstream rather than just clicking the button to switch back to the old frontend code and never following up.

**Comment by roidelapluie** [comment]
I think it is an awesome idea, as we want to switch to the new UI soon.

cc @juliusv

**Comment by brian-brazil** [comment]
If we're going to get rid of the old UI, let's get rid of it rather than complicating things with flags.

**Comment by roidelapluie** [comment]
> If we're going to get rid of the old UI, let's get rid of it rather than complicating things with flags.

I think that the new UI is fine. But clearly I can't test it as well as our userbase.

Could we, for a release, switch to the new UI and keep the "classic UI" link ? e.g. / would redirect to /new instead of /graph. Then we remove the classic UI.

**Comment by juliusv** [comment]
I think we should at least default to the new UI, but we probably still need to keep the old one around until we find a solution for https://github.com/prometheus/prometheus/issues/6881 (which is bad in both versions, but much worse in the new UI). I have tried to play a bit with react-virtualized and react-window, but haven't had much success yet.

**Comment by brian-brazil** [comment]
We looked at this in the bug scrub, and per above the plan is to possibly switch what the default is before removing the old UI but without any configurability.
