### ISSUE TITLE
meta.json file is not generating 

### ISSUE THREAD

**Issue by mohanagandlla** [prometheus/prometheus#8126]
**What did you do?**
I have attached the mapr to the Prometheus on two instances at one instance it is working good coming to second one its not creating the meta.json file finally throwing an error 
This is the status of mount
posix                  1.0T     71.1G    952.9G   7% /prometheus
**What did you expect to see?**
wal corruption need to resolve
**What did you see instead? Under which circumstances?**

**Environment**

* Prometheus version:

	insert output of `prometheus --version` 2.22.0

* Logs:
```
level=error ts=2020-10-29T03:29:33.202Z caller=main.go:764 err="opening storage failed: block dir: \"/prometheus/01ENRA5TM45DGMR9PG0NF5R3M6\": open /prometheus/01ENRA5TM45DGMR9PG0NF5R3M6/meta.json: no such file or directory"
```
I have checked on all compacts there is no JSON file

**Comment by roidelapluie** [comment]
You can't run to Prometheus instances on the same directory, is that what is happening here? Which filesystem are you using?

**Comment by mohanagandlla** [comment]
NO I have deployed the application on Kubernetes it is inside the pod and the instance is from an operator, I just added the PV to the Prometheus instance I didn't change anything there and I am using mapr-fs system

**Comment by brian-brazil** [comment]
We look at this in the bug scrub and networked filesystems such as mapr-fs are not supported, as they often do not provide full POSIX semantics. If you can reproduce this on a local filesystem please let us know, otherwise we shall presume the issue is with your filesystem.
