### ISSUE TITLE
replace ioutils.ReadAll with io.Copy in TSDB/fileutile.go/copyfile

### ISSUE THREAD

**Issue by zdyj3170101136** [prometheus/prometheus#8127]
**Use case. Why is this important?**
in TSDB/fileutile.go/copyfile, which use ioutils.Readall read data from disk to user space and then use ioutils.WriteAll write data from user space to disk.
I think it is not efficient.

And in linux copyFileRange in go, which `performs an in-kernel copy between
       two file descriptors without the additional cost of transferring data
       from the kernel to user space and then back into the kernel.`.

And in go, io.Copy implement copyFileRange.
*“Nice to have” is not a good use case. :)*

**Comment by nrchakradhar** [comment]
Can I submit a PR for this?

**Comment by brian-brazil** [comment]
Sure, some benchmarks would also be good so we know how much it helps.

**Comment by nrchakradhar** [comment]
I created a gist with the code in the link below:
https://gist.github.com/nrchakradhar/78df3373b28a4ff5383df70e0b84b9ac

My observations (as a newbie I may be wrong)
io.copy seems to be using consistent memory(as expected per golang documentation) with lesser time.

Please let me know if my observations are fine.

**Comment by ArthurSens** [comment]
Memory usage reduction looks pretty nice, but it came with the cost of some extra processing time. I wonder if this could be a problem at a large scale :thinking: 

Hey @nrchakradhar, maybe a PR changing our codebase directly could be useful too. Maintainers can trigger a benchmark from your PR and see how your changes affect Prometheus.

I think this is where you want to work on :slightly_smiling_face: 
https://github.com/prometheus/prometheus/blob/ebe0da7a726e169f9612358159f7afce04cb6802/tsdb/fileutil/fileutil.go#L62-L73

**Comment by nrchakradhar** [comment]
@brian-brazil I was initially planning to make the change in the codebase itself, but thought that I cannot put/create test files in the repo for checking. I will modify the code base and create a PR soon.

**Comment by nrchakradhar** [comment]
The function is used only in tests and hence changes are not needed as of now.
https://github.com/prometheus/prometheus/pull/8188#issuecomment-729962324
https://github.com/prometheus/prometheus/pull/8188#issuecomment-730301389
