### ISSUE TITLE
Snapshot foldername has different length if hash starts from zero

### ISSUE THREAD

**Issue by Anikei** [prometheus/prometheus#8135]
**What did you do?**
Use the batch script to backup snapshots which created with API call.

**What did you expect to see?**
Foldernames which are easy to parse from output
20201030T075849Z-57e9d1860d1d68d8
20201030T164421Z-0866cb397916001e

**What did you see instead? Under which circumstances?**
20201030T075849Z-57e9d1860d1d68d8
20201030T164421Z-866cb397916001e
For the second folder zero char is omitted, so it is a foot shot for somebody who expected the stable value length

**Environment**
Windows 10 64

* Prometheus version:
prometheus-2.22.0-rc.0.windows-amd64

**Comment by roidelapluie** [comment]
Thanks. I have created #8138.
