### ISSUE TITLE
regex drop not working for all characters wildcard

### ISSUE THREAD

**Issue by schmirgo** [prometheus/prometheus#8136]
[data_from_database.txt](https://github.com/prometheus/prometheus/files/5468556/data_from_database.txt)
[log.txt](https://github.com/prometheus/prometheus/files/5468557/log.txt)
[prometheus-config.txt](https://github.com/prometheus/prometheus/files/5468558/prometheus-config.txt)

**What did you do?**
Regex is not working, dropping all metrics with regex .* is not working within metrics_relabel_config.
i tried various combinations like (.*) and more complicated variations with alphanumerical regex like [a-z]*.
the log file corresponds to the output of the regex .*
Regex with various combinations of 'scrape_.*' or similar regex does not work. Regex is verified to full match within Go.
i am using blackbox-exporter to scrape metrics. i use timescaledb postgresql adapter for data storage.

**What did you expect to see?**
not seeing any scrape metrics or any metrics at all because of drop relabel config

**What did you see instead? Under which circumstances?**
metrics being stored, database dump contains following (database was cleared before every prometheus start, prometheus was restarted after every regex change):
"sample","time","name","value","labels"
"up{job=""http"",instance=""http://docker1:9000"",metric_name=""up""} 1.000000 1604120315143","2020-10-31 05:58:35.143+01","up","1","{""job"": ""http"", ""instance"": ""http://docker1:9000"", ""metric_name"": ""up""}"
"scrape_duration_seconds{job=""http"",instance=""http://docker1:9000"",metric_name=""scrape_duration_seconds""} 0.008670 1604120315143","2020-10-31 05:58:35.143+01","scrape_duration_seconds","0.008670115","{""job"": ""http"", ""instance"": ""http://docker1:9000"", ""metric_name"": ""scrape_duration_seconds""}"
...

**Environment**
blackbox-exporter
postgresql-timscaledb adapter
official docker image from dockerhub: prom/prometheus:latest

* System information:
Linux 5.4.34-0-lts x86_64

* Prometheus version:
dockerhub: prom/prometheus:latest
prometheus, version 2.22.0 (branch: HEAD, revision: 0a7fdd3b76960808c3a91d92267c3d815c1bc354)
  build user:       root@6321101b2c50
  build date:       20201015-12:29:59
  go version:       go1.15.3
  platform:         linux/amd64

* Prometheus configuration file:
snippet here, full config attached:
[...]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: docker1:9115  # The blackbox exporter's real hostname:port.
    metric_relabel_configs:
      - source_labels: [ __name__ ]
        regex: .*
        action: drop
      - source_labels: [ __name__ ]
        regex: 'scrape_samples_scraped'
        action: drop
[...]

* Logs:
level=info ts=2020-10-31T05:00:04.283Z caller=head.go:889 component=tsdb msg="WAL checkpoint complete" first=1440 last=1448 duration=120.553311ms,
level=info ts=2020-10-31T04:44:32.338Z caller=main.go:732 fs_type=EXT4_SUPER_MAGIC,
ts=2020-10-31T04:44:32.341Z caller=dedupe.go:112 component=remote level=info remote_name=46ed0b url=http://docker1:9201/write msg="Starting WAL watcher" queue=46ed0b,
level=info ts=2020-10-31T04:44:32.338Z caller=main.go:735 msg="TSDB started",
level=info ts=2020-10-31T04:44:32.338Z caller=main.go:861 msg="Loading configuration file" filename=/etc/prometheus/prometheus.yml,
ts=2020-10-31T04:44:32.342Z caller=dedupe.go:112 component=remote level=info remote_name=46ed0b url=http://docker1:9201/write msg="Replaying WAL" queue=46ed0b,
level=info ts=2020-10-31T04:44:32.342Z caller=main.go:684 msg="Server is ready to receive web requests.",
level=info ts=2020-10-31T04:44:32.342Z caller=main.go:892 msg="Completed loading of configuration file" filename=/etc/prometheus/prometheus.yml totalDuration=3.865657ms remote_storage=880.927µs web_handler=1.077µs query_engine=1.369µs scrape=661.982µs scrape_sd=108.848µs notify=47.008µs notify_sd=33.66µs rules=2.636µs,
ts=2020-10-31T04:44:53.680Z caller=dedupe.go:112 component=remote level=info remote_name=46ed0b url=http://docker1:9201/write msg="Done replaying WAL" duration=21.339157407s,
level=info ts=2020-10-31T05:00:04.146Z caller=compact.go:494 component=tsdb msg="write block" mint=1604109600000 maxt=1604116800000 ulid=01ENYGDQPSB59VEMK6YEB599R6 duration=472.600253ms,
level=info ts=2020-10-31T05:00:04.162Z caller=head.go:809 component=tsdb msg="Head GC completed" duration=1.962639ms,
level=info ts=2020-10-31T05:00:04.163Z caller=checkpoint.go:96 component=tsdb msg="Creating checkpoint" from_segment=1440 to_segment=1448 mint=1604116800000,
level=info ts=2020-10-31T04:44:32.248Z caller=main.go:353 msg="Starting Prometheus" version="(version=2.22.0, branch=HEAD, revision=0a7fdd3b76960808c3a91d92267c3d815c1bc354)",
level=info ts=2020-10-31T04:44:32.248Z caller=main.go:358 build_context="(go=go1.15.3, user=root@6321101b2c50, date=20201015-12:29:59)",
level=info ts=2020-10-31T04:44:32.248Z caller=main.go:359 host_details="(Linux 5.4.34-0-lts #1-Alpine SMP Wed, 22 Apr 2020 19:26:07 UTC x86_64 02bc9be015c0 (none))",
level=info ts=2020-10-31T04:44:32.248Z caller=main.go:360 fd_limits="(soft=1048576, hard=1048576)",
level=info ts=2020-10-31T04:44:32.248Z caller=main.go:361 vm_limits="(soft=unlimited, hard=unlimited)",
level=info ts=2020-10-31T04:44:32.254Z caller=main.go:712 msg="Starting TSDB ...",
level=info ts=2020-10-31T04:44:32.254Z caller=web.go:516 component=web msg="Start listening for connections" address=0.0.0.0:9090,
level=info ts=2020-10-31T04:44:32.255Z caller=repair.go:56 component=tsdb msg="Found healthy block" mint=1602763200000 maxt=1602828000000 ulid=01EMRA6D540H2PSYA6ADPYF111

**Comment by brian-brazil** [comment]
> Regex with various combinations of 'scrape_.*' or similar regex does not work. 

That's correct, metric_relabel_configs only applies to scraped metrics. up and the 3 scrape_ metrics are not scraped.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by schmirgo** [comment]
Hi, thansk fpr clarification. I was assuming it was a bug because it was not stated within the documentation that there are "special" metrics lile values which are reported the same ways as metrics but treated differently (not filtered).

The problem with those scrape_.* is that anyone not wanting those metrics has to delete them somehow. for example delete with a batch job, which is riduculous regarding the fact that prometheus is a monitoring tool. in my case i have to write an (ugly) "on insert" trigger in the database which discards those datasets. i can not waste 200%-300% of space to values i don't need in the future.

**Comment by hoffie** [comment]
If you don't want to scrape specific targets at all, the solution might be `relabel_configs` which filters what targets are scraped. As Brian said, if you want to further discuss this issue, the mailing list will be the better place. :)

**Comment by brian-brazil** [comment]
> it was not stated within the documentation that there are "special" metrics lile values which are reported the same ways as metrics but treated differently

That is clearly stated in the docs: https://prometheus.io/docs/prometheus/latest/configuration/configuration/#metric_relabel_configs

**Comment by schmirgo** [comment]
> 
> 
> > it was not stated within the documentation that there are "special" metrics lile values which are reported the same ways as metrics but treated differently
> 
> That is clearly stated in the docs: https://prometheus.io/docs/prometheus/latest/configuration/configuration/#metric_relabel_configs

I can only find the wording "such as UP" therefore i did not try to filter "UP" because i have read the docs before. Maybe there is a complete list of generated timeseries somewhere?

Thanks for the hint though, in my case it is not necessary to clarify this topic anymore, i found out which ones are generated by adding .* as regex anyway. i would place something into the docs like "scraped_*" as well as "UP"

**Comment by roidelapluie** [comment]
Are you using remote write?
