### ISSUE TITLE
Prometheus Normal environment collapse

### ISSUE THREAD

**Issue by huangchengwu** [prometheus/prometheus#8145]
2020/10/20 10:17:15 bad connection
level=error ts=2020-10-20T02:17:15.645978145Z caller=consul.go:356 component="discovery manager scrape" discovery=consul msg="Error refreshing service list" err="Get http://172.16.0.115:8500/v1/catalog/services?index=1662869&stale=&wait=30000ms: context canceled"
2020/10/20 10:17:15 invalid character 's' looking for beginning of value
2020/10/20 10:17:15 invalid character 's' looking for beginning of value
fatal error: concurrent map writes

goroutine 15962561 [running]:
runtime.throw(0x1fcff9f, 0x15)
        /usr/lib/golang/src/runtime/panic.go:774 +0x72 fp=0xc05f19f470 sp=0xc05f19f440 pc=0x42f332
runtime.mapassign_fast64(0x1c34ae0, 0xc0e80146c0, 0xa83d514c7c92eacc, 0x12)
        /usr/lib/golang/src/runtime/map_fast64.go:101 +0x350 fp=0xc05f19f4b0 sp=0xc05f19f470 pc=0x411a80
github.com/prometheus/prometheus/rules.(*Group).CopyState(0xc047e95380, 0xc049570600)
        /data/prometheus/prometheus/rules/manager.go:441 +0x52a fp=0xc05f19f788 sp=0xc05f19f4b0 pc=0x187efda
github.com/prometheus/prometheus/rules.(*Manager).Update.func1(0xc01c461a01, 0xc049570600, 0xc0008048c0, 0xc0106bcc60, 0xc047e95380)
        /data/prometheus/prometheus/rules/manager.go:775 +0xc4 fp=0xc05f19f7b8 sp=0xc05f19f788 pc=0x1887384
runtime.goexit()
        /usr/lib/golang/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc05f19f7c0 sp=0xc05f19f7b8 pc=0x45edf1
created by github.com/prometheus/prometheus/rules.(*Manager).Update
        /data/prometheus/prometheus/rules/manager.go:772 +0x4fa

goroutine 1 [chan receive, 40052 minutes]:
github.com/oklog/oklog/pkg/group.(*Group).Run(0xc000c9de90, 0xc0001211f0, 0x8)
        /data/prometheus/prometheus/vendor/github.com/oklog/oklog/pkg/group/group.go:43 +0xed
main.main()
        /data/prometheus/prometheus/cmd/prometheus/main.go:717 +0x6778

goroutine 19 [syscall, 40052 minutes]:
os/signal.signal_recv(0x0)
        /usr/lib/golang/src/runtime/sigqueue.go:147 +0x9c
os/signal.loop()
        /usr/lib/golang/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
        /usr/lib/golang/src/os/signal/signal_unix.go:29 +0x41

What's wrong with this report

**Comment by roidelapluie** [comment]
Thanks for this report. Can you please provide us more context, as the operating system, and the version of Prometheus you are running?

**Comment by roidelapluie** [comment]
Also an idea about the number of targets/service discoveries would help.

**Comment by roidelapluie** [comment]
Here is the form we usually ask our users to file: https://github.com/prometheus/prometheus/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by beorn7** [comment]
Hello from the bug scrub.

No info provided in 3.5y. We have to close this.
