### ISSUE TITLE
Permission Denied when requesting a snapshot via the admin API

### ISSUE THREAD

**Issue by JessedeJonge** [prometheus/prometheus#8150]
**What did you do?**
Called `curl -XPOST http://localhost:9090/api/v2/admin/tsdb/snapshot`
**What did you expect to see?**
Snapshot being created
**What did you see instead? Under which circumstances?**
`{"error":"created snapshot directory: mkdir snapshots: permission denied","code":13,"message":"created snapshot directory: mkdir snapshots: permission denied"}`
**Environment**
`--storage.tsdb.path /data/prometheus/` That directory is owned by prometheus with cmod 777. Making the directory `/data/prometheus/snapshots` with 777 manually also does not work.

* Prometheus version:

```
prometheus, version 2.18.0 (branch: HEAD, revision: a12e96299dcd159ea09b260f1a21e7e4b86e011d)
  build user:       root@7fbcff55abdb
  build date:       20200505-14:26:04
  go version:       go1.14.2

```
* Relevant code:

`	var (
		snapdir = filepath.Join(api.dbDir, "snapshots")
		name    = fmt.Sprintf("%s-%016x",
			time.Now().UTC().Format("20060102T150405Z0700"),
			rand.Int63())
		dir = filepath.Join(snapdir, name)
	)
	if err := os.MkdirAll(dir, 0777); err != nil {
		return apiFuncResult{nil, &apiError{errorInternal, errors.Wrap(err, "create snapshot directory")}, nil, nil}
	}`

api.dbDir should be the path from --storage.tsdb.path?

**Comment by roidelapluie** [comment]
This is a bug in 2.18.0 which was fixed in 2.18.1. please upgrade.
