### ISSUE TITLE
startup fails with invalid config, missing the log message

### ISSUE THREAD

**Issue by TomL-dev** [prometheus/prometheus#8156]
**What did you do?**

i made a mistake in my prometheus configuration file. i wrote `metric_path` instead of `metrics_path`. After restarting prometheus, it kept crashing with no error logging and exit code 2. I was stuck on this longer than i would like to admit. When reverting my config (removed newly added entry) it did start. However when i readded the error and did a `curl -X POST localhost:9090/-/reload` i did get a nice error message stating what my error was:

```
failed to reload config: couldn't load configuration (--config.file="/config/prometheus.yml"): parsing YAML file /config/prometheus.yml: yaml: unmarshal errors:
  line 53: field metric_path not found in type config.ScrapeConfig
```

**What did you expect to see?**

i expect prometheus to log the same issue (cannot validate configuration) on startup

**What did you see instead? Under which circumstances?**

no error logging, just exit code 2 in my docker container

**Environment**

* System information:

	insert output of `uname -srm` here

      Linux 3.10.0-1160.2.1.el7.x86_64 x86_64

* Prometheus version:

	insert output of `prometheus --version` here

        prometheus, version 2.22.1 (branch: HEAD, revision: 00f16d1ac3a4c94561e5133b821d8e4d9ef78ec2)
        build user:       root@516b109b1732
        build date:       20201105-14:02:25
        go version:       go1.15.3
        platform:         linux/amd64

**Comment by brian-brazil** [comment]
I cannot reproduce this, I get an error on stderr as expected.

**Comment by TomL-dev** [comment]
Thanks for your fast reply.

thats good to know, than it might me my setup (docker stack within docker swarm) that doesn't properly sends out the error log on startup

Only seeing the exit code 2 when docker inspect-ing the container

**Comment by brian-brazil** [comment]
That sounds like an issue with your setup rather than Prometheus. Can you reproduce outside of Docker?

**Comment by TomL-dev** [comment]
i'll try, if this still is an issue, i'll reopen the ticket
