### ISSUE TITLE
Inconsistent CPU usage reported when compared to real system usage on some systems

### ISSUE THREAD

**Issue by nanoandrew4** [prometheus/prometheus#8157]
**What did you do?**

I installed two helm charts, stable/wordpress and stable/prometheus-operator. The wordpress chart was configured to have a CPU limit of 1 CPU, and deploys two containers inside the wordpress pod, one for wordpress and one for metrics. The wordpress container was then stressed to force it to reach its CPU limit.

**What did you expect to see?**

We expected to see Prometheus indicate that 1 thread was being used by the pod when it was under load, since that is what the limit is configured as, and kubernetes won't let it pass that limit.

**What did you see instead? Under which circumstances?**

![pod_limit_issue](https://user-images.githubusercontent.com/14365320/98378205-02b2bd80-2046-11eb-88aa-0daa21c4f5f5.PNG)

In the image above we can see that I ran two processes that just consume CPU, in order to generate load inside the container, which each consume ~50% of a thread each, which is correct, since the limit for the container is at 100%, or 1 thread, and it seems each process gets about half of the CPU time. The command `kubectl top pods -A` also shows that the pod is consuming 1000 millicores, which is correct. However, when I go to Prometheus and run the following query: `node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate` I see the following:
![pod_limit_issue_2](https://user-images.githubusercontent.com/14365320/98379711-e1eb6780-2047-11eb-8207-3102815d9420.PNG)

The pod is reported as using 2 threads, which is inconsistent with what htop and kubectl report in the first image. There are so many variables in this puzzle that I am not sure where to begin, but I lean more towards Prometheus reporting incorrect data given that both htop and kubernetes are reporting the numbers I expect to see, given my setup. What is odd is it only happens on two of our systems, all the others report data correctly.

**Environment**

* System information:

On a machine where correct data is reported: Linux 4.15.0-121-generic x86_64 and Linux 3.10.0-1127.19.1.el7.x86_64 x86_64
On a machine where incorrect data is reported: Linux 3.10.0-1062.el7.x86_64 x86_64

* Prometheus version:
2.18.2 (which is the version used by the helm chart stable/prometheus-operator)

**Comment by brian-brazil** [comment]
I see no indication of any Prometheus bugs here, this sounds like more of a cAdvisor question.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
