### ISSUE TITLE
https static_target scraper returns 503 for public internet URL that is accessible to curl/etc.

### ISSUE THREAD

**Issue by fche** [prometheus/prometheus#8171]
**What did you do?**

configure prometheus to monitor public debuginfod services

**What did you expect to see?**

prometheus to scrape the metrics off of `https://debuginfod.opensuse.org/metrics`
cc: @marxin 

**What did you see instead? Under which circumstances?**

prometheus indicates a 503 error code and target down.
curl of the same URL works fine from the same machine.
prometheus scraping of similar servers works fine, e.g. of `https://debuginfod.elfutils.org/metrics`.

**Environment**

* Data exporter information:

There is some reverse proxy between this version of `elfutils debuginfod` and the public internet.  It appears to be injecting extra HTTP response headers.  We wonder if it may be some golang http security at play.

<pre>
% curl -i https://debuginfod.opensuse.org/metrics
HTTP/2 200 
content-length: 2372
content-type: text/plain
date: Wed, 11 Nov 2020 11:32:27 GMT
x-frame-options: SAMEORIGIN
x-xss-protection: 1; mode=block
x-content-type-options: nosniff
referrer-policy: no-referrer-when-downgrade
strict-transport-security: max-age=31536000;includeSubDomains;preload
</pre>

* System information:

Fedora 32: Linux 5.7.15-200.fc32.x86_64 x86_64 but others observed, including opensuse.

* Prometheus version:

	insert output of `prometheus --version` here
    % prometheus --version
    prometheus, version  (branch: , revision: )
       build user:       
       build date:       
       go version:       go1.15rc1

that looks weird, but Fedora's `golang-github-prometheus-2.20.0-2.fc33.x86_64` is my build.

* Prometheus configuration file:
```
insert configuration here
```
      - job_name: 'debuginfod-https'
       scheme: https
       static_configs:
        - targets: ['debuginfod.opensuse.org']

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```

Nothing relevant (no mention of this target in the logs, no errors).

**Comment by brian-brazil** [comment]
If the server is returning a 503, that's a problem with the server not Prometheus.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by fche** [comment]
Brian, I believe the point is that the server is not returning 503.
It appears to be prometheus' libraries rejecting the 200 result.

**Comment by brian-brazil** [comment]
I had checked this locally, and the error states that the server returned a 503. There is no logic in Prometheus that could affect that.

**Comment by marxin** [comment]
All right, is there a way one can get the complete the HTTP request (including all headers) that is sent a server?

**Comment by brian-brazil** [comment]
It doesn't offer that, the data volumes would be too high for data which is basically constant.

**Comment by fche** [comment]
OK, too bad ... it makes errors a bit of a mystery.
