### ISSUE TITLE
Add Hetzner Cloud project name label

### ISSUE THREAD

**Issue by xoxys** [prometheus/prometheus#8175]
## Proposal

It would be helpful to have the Hetzner Cloud project name available as a label in the Hetzner SD. This is useful if you have a lot of projects and need to group hosts.

**Comment by roidelapluie** [comment]
This information is not available in the API right now, AFAIK.

cc @LKaemmerling

**Comment by LKaemmerling** [comment]
Yep this information is not available ATM. But you (as a user) have it, because you have the API token that is bound to a single project.

**Comment by xoxys** [comment]
Can a parameter from the sd configbe passed to a label as workaround?

```
- bearer_token: '12345'
  role: hcloud
  name: project_1
```

that results in something like `__meta_hetzner_name=project_1` as a workaround?

**Comment by roidelapluie** [comment]
you can use:

```
    relabel_configs:
      - target_label: project
        replacement: project_1
```

**Comment by roidelapluie** [comment]
> Yep this information is not available ATM. But you (as a user) have it, because you have the API token that is bound to a single project.

In the case of Prometheus, you can use multiple Hetzner SD's per job. Is it planned on Hetzner side to add this information to the API, or should we close this request?

**Comment by roidelapluie** [comment]
Maybe can can somehow set the project with an api call when initialising the provider, I assume it does not change for each api key.

**Comment by LKaemmerling** [comment]
> In the case of Prometheus, you can use multiple Hetzner SD's per job. Is it planned on Hetzner side to add this information to the API, or should we close this request?

@roidelapluie when we add it to the API i will prepare the change within the Service Discovery. ATM i don't see it for the foreseeable future.

**Comment by xoxys** [comment]
Ok I'll keep using a custom Hcloud SD. The suggested way is IMO only possible with a lot of duplications.

**Comment by roidelapluie** [comment]
This does not seem actionable for us, so I will close this.
