### ISSUE TITLE
full disk because of many left .tmp directories 

### ISSUE THREAD

**Issue by universam1** [prometheus/prometheus#8180]
We face TSDB storage filling up because of .tmp directories that are left. We understand that these tmp directories result from failed compaction or retention, but even though the Prometheus pods are healthy the left tmp dirs are not rotated / removed at any time later.

**What did you do?**

cleaning up the tmp dirs manually - but that is not acceptable for a fleet of clusters

**What did you expect to see?**

eventually Prometheus removes / rotates these tmp directories, but they keep on lingering forever

**What did you see instead? Under which circumstances?**

The tmp directories are never cleaned up

**Environment**
kube-prometheus running quay.io/prometheus/prometheus:v2.22.1
* System information:

	Linux 4.14.198-152.320.amzn2.x86_64 x86_64

* Prometheus version:

	prometheus, version 2.22.1 (branch: HEAD, revision: 00f16d1ac3a4c94561e5133b821d8e4d9ef78ec2)
        build user:       root@516b109b1732
        build date:       20201105-14:02:25
        go version:       go1.15.3
        platform:         linux/amd64

* Prometheus configuration file:
```
prometheus --log.level=debug --web.console.templates=/etc/prometheus/consoles --web.console.libraries=/etc/prometheus/console_libraries --storage.tsdb.retention.si
ze=90GB --config.file=/etc/prometheus/config_out/prometheus.env.yaml --storage.tsdb.path=/prometheus --storage.tsdb.retention.time=1y --web.enable-lifecycle --storage.tsdb.no-lockfile --web
.external-url=/prometheus --web.route-prefix=/prometheus --storage.tsdb.min-block-duration=2h --storage.tsdb.max-block-duration=2h
```

**Comment by dhohengassner** [comment]
@universam1 thanks - fighting with that as well

**Comment by roidelapluie** [comment]
Can you please tell us what those files are excactly? And provide us with the Prometheus logs? Thanks!

**Comment by universam1** [comment]
> Can you please tell us what those files are excactly? And provide us with the Prometheus logs? Thanks!

tmp directories like `/prometheus/01EQ0DZ14E04F7P51Q3NA1562G.tmp`

**Comment by roidelapluie** [comment]
Do you see the same under previous versions of Prometheus?

**Comment by roidelapluie** [comment]
cc @bwplotka I think you could poke around the code :)

**Comment by roidelapluie** [comment]
> > Can you please tell us what those files are excactly? And provide us with the Prometheus logs? Thanks!
> 
> tmp directories like `/prometheus/01EQ0DZ14E04F7P51Q3NA1562G.tmp`
> 
> Which logs would you like to see? No errors logged in this regard, just missing function we believe

logs around when that file was created

**Comment by universam1** [comment]
> Do you see the same under previous versions of Prometheus?

Yes, we hoped the latest version would be different but it does not

**Comment by universam1** [comment]
> logs around when that file was created

We saw OOMKilled (which is a different thing), but these .tmp dirs are left untouched. They are already way older than the retention

**Comment by roidelapluie** [comment]
Looking at your last comment, we think that the issue is the oomkilled, in such cases it can happen that there are leftovers .tmp files. The actual issue is that Prometheus did not have enough memory.

**Comment by universam1** [comment]
> Looking at your last comment, we think that the issue is the oomkilled, in such cases it can happen that there are leftovers .tmp files. The actual issue is that Prometheus did not have enough memory.

Right, and that is what I stated as a fact at the TO. However that is not the concern of this issue. It is the mere fact that Prometheus will never clean up such artifacts at any time later, and by mere probability every storage will eventually fill up. 

Hence a function is missing that automatically purges or processes such artifacts

**Comment by roidelapluie** [comment]
Mmmh which version created thos tmp files?

#7772 should have covered this.

**Comment by universam1** [comment]
> Mmmh which version created those tmp files?
> 
> #7772 should have covered this.

Interesting! We were running 2.15.2 at that time

**Comment by roidelapluie** [comment]
@bwplotka do you think we should delete pre-2.21 `.tmp` blocks as well? I'd say yes..

**Comment by AdaephonBen** [comment]
I'd like to pick this up. @roidelapluie

**Comment by codesome** [comment]
> do you think we should delete pre-2.21 .tmp blocks as well? I'd say yes..

I would say yes too since deleting old .tmp dirs manually would be tedious if you have lots of Prometheus running.

@AdaephonBen sure go ahead!

**Comment by longngn** [comment]
I'd like to pick this up

**Comment by universam1** [comment]
Awesome thanks 😊
