### ISSUE TITLE
promtool: check only exp_labels/exp_annotations

### ISSUE THREAD

**Issue by StupidScience** [prometheus/prometheus#8182]
## Proposal
Currently tests check that all of labels/annotations match in alert and test descriptions and use `reflect.DeepEqual` for .
It makes tests inconvenient to work with dynamic labels/annotations.

Would be great if `exp_labels`/`exp_annotations` will be checked and other will be just ignored.

For example:
We have annotations set like this:
```
"summary": "Azure MySQL storage warning",
"description": "Azure MySQL free storage < 20%. You have to increase the storage size or clean it up",
"value": "{{ $value }}"
```

So we don't wanna test real `value` annotation value.
So we'll declare test annotations like this:
```
"exp_annotations": {
  "summary": "Azure MySQL storage warning",
  "description": "Azure MySQL free storage < 20%. You have to increase the storage size or clean it up"
},
```

What do you think?

**Comment by brian-brazil** [comment]
That wouldn't be correct, as in the case of labels the full label set are the identity of the alert so you'd miss unwanted labels being let through. Also, how would you test that a label/annotation was missing or empty? Missing and empty labels are the same thing semantically.

For a given test the output of these will always be identical, so it shouldn't be hard to copy&paste to keep things in sync.

**Comment by StupidScience** [comment]
I don't understand the problem with missing or empty label. From my pov there is no problem. Can you give some context here?

However I'm not sure about unwanted labels/annotations. May be some kind of strictness flag can help with this.

**Comment by brian-brazil** [comment]
> I don't understand the problem with missing or empty label. From my pov there is no problem. Can you give some context here?

How would you assert that a given label should not be present?

> However I'm not sure about unwanted labels/annotations. May be some kind of strictness flag can help with this.

I personally don't see the need, it's not particularly difficult to provide the full set of labels that are generated. The goal of the unittests is to test what the alert is up to after all.

**Comment by roidelapluie** [comment]
We have looked at this during our bug scrub and decided to close this. We think that the current behaviour is correct and that there are sufficient workarounds (like copy and paste) to deal with this.

Thanks!

**Comment by pSub** [comment]
@dgl as you are the appointed unit test expert, please reconsider this feature request. I cannot emphanize the points made by @alexanderabramov  enough. We are currently adopting prometheus and have a lot of annotations that do not need to be covered by all test. Copy & pasting is error prone and creates visual noise, which hinders test adoption.

**Comment by dgl** [comment]
#11033 is implementing a basic regexp matching on annotations.
