### ISSUE TITLE
can't see some old metrics after restoring snapshot

### ISSUE THREAD

**Issue by inkdude** [prometheus/prometheus#8184]
**What did you do?**
I have prometheus version 2.18
I enable  **--web_api_admin**
launch creating snapshot from prometheus
receive folder in which i have many directories with names like a "01E10T8EV6ZSK04N6299ZWQX45"
Update prometheus to the last version (2.22) and start
then stop prometheus
go to /var/lib/prometheus
delete all files from this directory
copy all directories from snapshot to the /var/lib/prometheus
start prometheus

**What did you expect to see?**

In node_exporter i expect to see continue my time series, but i see only old data (new data don't write into the snapshot directories)

I have trouble only with node_exporter dashboard

From other exporters such as mikrotik_exporter or APC UPS exporter i see all data (old and new) time series continue writing in the same files

If i create a new dashboard node_exporter i see a new data, but i don't see old data

**What did you see instead? Under which circumstances?**
This is old dashboard node_exporter
![image](https://user-images.githubusercontent.com/17637953/99141725-318ced00-265f-11eb-9798-699eeb858cd5.png)

This is a new dashboard node_exporter
![image](https://user-images.githubusercontent.com/17637953/99141878-85e49c80-2660-11eb-883e-2ecc3240365f.png)

**Environment**

* Prometheus version:

prometheus, version 2.22.1 (branch: HEAD, revision: 00f16d1ac3a4c94561e5133b821d8e4d9ef78ec2)
  build user:       root@516b109b1732
  build date:       20201105-14:02:25
  go version:       go1.15.3
  platform:         linux/amd64

How i can concatenate old and new time series in my new dashboard node_exporter (new dashboard is better)?

**Comment by roidelapluie** [comment]
We have looked at in in our bug scrub, can you please help us by providing more steps to reproduce this behaviour?

**Comment by inkdude** [comment]
Solved!
Do not change name of job on a new config prometheus)))
Before restoring
![image](https://user-images.githubusercontent.com/17637953/100232766-d8b03500-2f39-11eb-9f5f-bb539e1f0788.png)

After restoring (used new config prometheus.yml with old backup metrics)
![image](https://user-images.githubusercontent.com/17637953/100232837-f2ea1300-2f39-11eb-86f4-9df53bf7d021.png)


In first picture job = "Hardware", on second job = "node"

Grafana can't understand what's going with job naming

After that i change name of job and all alright!
![image](https://user-images.githubusercontent.com/17637953/100232990-2c228300-2f3a-11eb-8dd2-cddc741bee0f.png)

Thank you @roidelapluie )))
