### ISSUE TITLE
Wal Compaction fail in repeated times

### ISSUE THREAD

**Issue by mohanagandlla** [prometheus/prometheus#8195]
Hi I was facing the WAL compaction fail and in logs I have seen this

level=error ts=2020-11-14T17:02:36.468Z caller=db.go:685 component=tsdb msg="compaction failed" err="delete persisted head block after failed db reload:01EQ3V61MKYGSW91GP411WRBTQ: unlinkat /prometheus/01EQ3V61MKYGSW91GP411WRBTQ/chunks: directory not empty"

This issue is geting a lots of time I am not sure there the mistake is...!
I am using the posix type mapr to store the data(PV and PVC).

I am using the mapr system POSIX type and static way of memory
Inside the chunks directory the content is

/prometheus/01EQ3V61MKYGSW91GP411WRBTQ/chunks $ ls -lart
total 795398
-rw-r--r-- 1 xxxxxxxxx xxxxx 536870843 Nov 14 17:01 .fuse.fuse000001
-rw-r--r-- 1 xxxxxxxxx xxxxx 277615125 Nov 14 17:01 .fuse.fuse000002
drwxr-xr-x 3 xxxxxxxxx xxxxx 2 Nov 17 08:23 ..
drwxr-xr-x 2 xxxxxxxxx xxxxx 2 Nov 17 08:23 .

/prometheus $ rm -rvf 01EQ3V61MKYGSW91GP411WRBTQ
removed '01EQ3V61MKYGSW91GP411WRBTQ/.fuse.fuseindex'
removed '01EQ3V61MKYGSW91GP411WRBTQ/chunks/.fuse.fuse000002'
removed '01EQ3V61MKYGSW91GP411WRBTQ/chunks/.fuse.fuse000001'
**rm: can't remove '01EQ3V61MKYGSW91GP411WRBTQ/chunks': Directory not empty**
removed directory: '01EQ3V61MKYGSW91GP411WRBTQ

**Comment by roidelapluie** [comment]
It sounds like your filesystem is not suppoted by Prometheus as it creates extra files in the data directories.

**Comment by mohanagandlla** [comment]
O but I am using mapr FS inside that I am following POSIX system that will support for prometheus mentioned at prometheus official web site I think so.

**Comment by roidelapluie** [comment]
Please use a local filesystem, as the issues you are facing more than probably come from mapr.

If you can reproduce this on a local filesystem, please reopen this bug.
