### ISSUE TITLE
React UI: Add something like 'insert metric at cursor' button

### ISSUE THREAD

**Issue by trallnag** [prometheus/prometheus#8211]
## Proposal

The classic UI features the button `insert metric at cursor` that allows users to to - well - insert metric at cursor and see a list of all available metrics. Neither is possible with the experimental React UI.

![image](https://user-images.githubusercontent.com/24834206/99911351-0d32af80-2cf4-11eb-851d-de9562ca9670.png)

It would be nice to have something similar for the React UI. Maybe turn the search symbol box into a button?

![image](https://user-images.githubusercontent.com/24834206/99911370-2c314180-2cf4-11eb-84ca-472ebcad4009.png)

## Use case. Why is this important?

Once the classic UI is removed there will be no option to see all available metrics from the UI. Navigating to Status > Targets and then open the `/metrics` endpoint directly is not an option because it is very uncommon to have your targets reachable from the same place the user is visiting the web UI. In addition this is not viable when you have a lot of different targets.

Also, if a user is fairly new to Prometheus and opens the web React UI, the user has no easy way to see all available metrics. He either has to type random chars to get a suggestions that never include all metrics, know at least a part of the metric name he is interested in or

**Comment by roidelapluie** [comment]
cc @juliusv

**Comment by juliusv** [comment]
For sure we need a better way to list all metrics. But that old dropdown is also not great in terms of usability / searchability. In PromLens I approached this problem like this, maybe we can do something similar in Prometheus:

![metrics-explorer](https://user-images.githubusercontent.com/538008/99916954-a7532180-2d0d-11eb-937b-d95b24c2b7c6.gif)

**Comment by Lanseuo** [comment]
If no one minds, I will have a look into this and create a pull request for this issue
