### ISSUE TITLE
File discovery targets continue to be scraped after job is removed

### ISSUE THREAD

**Issue by XNorith** [prometheus/prometheus#8214]
**What did you do?**
Started prometheus with a file-discovery job defined with 1 target.
Removed the file-discovery job from prometheus.yml and sent a HUP signal to prometheus.

**What did you expect to see?**
I expected metric collection from the target defined in the now removed job to cease

**What did you see instead? Under which circumstances?**
Prometheus continued to scrape the targets; this is confirmed by querying for metrics from the removed targets for query ranges well after the HUP was sent.

**Environment**

* System information:

	Linux 5.4.39-linuxkit x86_64

* Prometheus version:

	prometheus --version
prometheus, version 2.22.2 (branch: HEAD, revision: de1c1243f4dd66fbac3e8213e9a7bd8dbc9f38b2)
  build user:       root@f7d7e91063f0
  build date:       20201116-12:43:43
  go version:       go1.15.5
  platform:         linux/amd64

* Prometheus configuration file:
```
-----
At service start:
-----
scrape_configs:
- job_name: "test"
  file_sd_configs:
  - files:
    - "/etc/prometheus/test.json"
-----
Just prior to HUP being sent:
-----
scrape_configs:
-----
test.json:
-----
[
  {
    "labels": {
      "job": "test"
    },
    "targets": [ "127.0.0.1:9090" ]
  }
]
```

* Logs:
```
$ pkill -HUP prometheus
level=info ts=2020-11-23T17:08:45.413Z caller=main.go:861 msg="Loading configuration file" filename=prometheus.yml
/etc/prometheus $ level=info ts=2020-11-23T17:08:45.419Z caller=main.go:892 msg="Completed loading of configuration file" filename=prometheus.yml totalDuration=5.9966ms remote_storage=11.8µs web_handler=12µs query_engine=57.9µs scrape=1.5326ms scrape_sd=14.7µs notify=7.4µs notify_sd=8.8µs rules=6.8µs
```

Issue has been seen in production, and reproduced using the prom/prometheus:latest docker image (sha256:f7ffebdd428ba005e2c65ec1c7debdffdd39c43eb6bd0ddfa64ea7aba2a3fd14)

**Comment by roidelapluie** [comment]
What do you mea by 'well after' ? Do you see it removed from the configuration shown in the web interface?

**Comment by XNorith** [comment]
Apologies; I got hit with a bit of confirmation bias in trying to identify the source of my bug; this report isn't valid.
Will open a separate issue once I do a bit more due-diligence reproducing what I'm seeing in production.
