### ISSUE TITLE
Remote read duplicates first sample in range vector results

### ISSUE THREAD

**Issue by juliusv** [prometheus/prometheus#8215]
Range vector selectors sometimes return the first sample twice when joining local data with data from remote_read.

![duplicate-samples](https://user-images.githubusercontent.com/538008/99995958-6285c400-2dbb-11eb-96d6-293fc69d48dc.png)

Steps to reproduce:

1) Start a Prometheus with remote write + remote read config, scraping some data at 5-second intervals.
2) Run `foo[15s]`
3) See 4 (instead of 3) samples being returned, the first one being a duplicated one.

I used `git bisect` to track down the commit that introduced this problem and it was: 088fcc9e4814cfdd48b3393d46c6edc16f39e7a8

/cc @bwplotka and @codesome you both authored that PR

**Comment by roidelapluie** [comment]
Is that promql/ or storage/ ?

**Comment by juliusv** [comment]
I mean it affects both, but judging by the commit that introduced it, it is likely to be a storage bug.

**Comment by Harkishen-Singh** [comment]
Either this is resolved or it is hard to reproduce (like a rare issue).

**Comment by juliusv** [comment]
Indeed I couldn't reproduce this anymore at the current master, but still at an older revision from last year. I used `git bisect` again (now with the meaning of `good` and `bad` reversed) to find the commit at which this problem was fixed, and it seems like 9199fcb8d100afba384bf566779712a2b8094b6c by @codesome was the one that fixed it.

@codesome can you see what could accidentally have fixed this issue in your commit?

**Comment by codesome** [comment]
@juliusv  The `findMinMaxTime` in PromQL engine was updated in that commit which now calculates the min max properly. I guess that is used by the remote read for hints? That might have fixed it, but not 100% sure.

**Comment by juliusv** [comment]
@codesome Interesting. I still would have assumed that if there were overlapping / duplicate samples between the data from remote + local storage, that they would be deduplicated in the merge process.

**Comment by roidelapluie** [comment]
While you are still here, we have this to investigate and it could be related to this issue: https://github.com/prometheus/prometheus/issues/8558

**Comment by beorn7** [comment]
Hello from the bug scrub.

With #8591 in and some other assumptions expressed above that this is fixed, we just assume this is indeed fixed and close this. Also, no updates in more than 3y.

Having said that, if anyone has evidence this is still a problem, please follow up here in the issue.
