### ISSUE TITLE
Add elasticsearch(es) remote storage supported

### ISSUE THREAD

**Issue by llhhbc** [prometheus/prometheus#8220]
## Proposal
**Use case. Why is this important?**
The data of tsdb will borken after disk error.

*“Nice to have” is not a good use case. :)*

**Comment by csmarchbanks** [comment]
There is already a remote write integration for Elasticsearch listed on our website: https://prometheus.io/docs/operating/integrations/#remote-endpoints-and-storage. Does that cover the use case you are looking for?

**Comment by llhhbc** [comment]
Is only for write, not for read. I need read and write on es.

**Comment by roidelapluie** [comment]
This seems an issue for Elasticsearch instead of Prometheus.

**Comment by brian-brazil** [comment]
We looked at this in the bug scrub. If Elastic themselves add it we accept a PR to list it on the website. However creating such a thing is out of scope for the Prometheus project, so we're going to close this. If you're looking for others to help develop this I'd suggest reaching out either to Elastic or on the prometheus-developers mailing list.
