### ISSUE TITLE
cannot populate chunk N: not found

### ISSUE THREAD

**Issue by tarko** [prometheus/prometheus#8221]
After upgrading from 2.15.2 to 2.21 (and then 2.22 and 2.22 which do not fix this) we periodically see different heavier alerting rules (the ones that run for multiple seconds, evaluation_interval is 120s) fail with following error:

`
Nov 25 13:01:45 moonrise prometheus[12298]: level=warn ts=2020-11-25T13:01:45.589Z caller=manager.go:598 component="rule manager" group=hardware msg="Evaluating rule failed" rule="alert: DdmPredictedLaneBiasHigh\nexpr: round(predict_linear(ddm_lane_bias[2h], 24 * 3600) > ignoring(lane) group_left() ddm_bias_hi_thresh) and ignoring(job, lane) ifOperStatus == 1\nfor: 4h\nlabels:\n  dumbs: \"true\"\nannotations:\n  description: '{{ $labels.instance }} interface {{ $labels.ifName }} lane {{ $labels.lane }} predicted bias will be {{ $value }}mA in 24h'\n  summary: '{{ $labels.instance }} interface {{ $labels.ifName }} lane {{ $labels.lane }} predicted bias high. Optical pluggable will fail soon'\n" err="cannot populate chunk 1552662134784010: not found"
`

This happens just for single evaluation, next evaluation will run correctly.

![graph](https://user-images.githubusercontent.com/1047849/100233289-36408380-2f32-11eb-8186-8c6d51b7960b.png)

**Environment**

* System information:

`Linux 4.9.0-11-amd64 x86_64`

* Prometheus version:

```
prometheus, version 2.22.2 (branch: HEAD, revision: de1c1243f4dd66fbac3e8213e9a7bd8dbc9f38b2)
  build user:       root@f7d7e91063f0
  build date:       20201116-12:43:43
  go version:       go1.15.5
  platform:         linux/amd64
```

**Comment by brian-brazil** [comment]
Can you share the logs around this? This smells like something to do with head compaction.

**Comment by tarko** [comment]
Sure, line breaks for readability:

```
Nov 25 11:01:35 moonrise prometheus[12298]: level=info ts=2020-11-25T11:01:35.980Z caller=compact.go:494 component=tsdb msg="write block" mint=1606291200000 maxt=1606298400000 ulid=01EQZGYRXZSZAWPJN3RV9ZRTDN duration=1m35.917296757s
Nov 25 11:01:45 moonrise prometheus[12298]: level=info ts=2020-11-25T11:01:45.443Z caller=head.go:809 component=tsdb msg="Head GC completed" duration=6.011735963s
Nov 25 11:01:45 moonrise prometheus[12298]: level=info ts=2020-11-25T11:01:45.524Z caller=checkpoint.go:96 component=tsdb msg="Creating checkpoint" from_segment=52918 to_segment=52927 mint=1606298400000
Nov 25 11:02:02 moonrise prometheus[12298]: level=info ts=2020-11-25T11:02:02.304Z caller=head.go:889 component=tsdb msg="WAL checkpoint complete" first=52918 last=52927 duration=16.780324829s

Nov 25 13:01:40 moonrise prometheus[12298]: level=info ts=2020-11-25T13:01:40.467Z caller=compact.go:494 component=tsdb msg="write block" mint=1606298400000 maxt=1606305600000 ulid=01EQZQTG60K8C586B8Z5XHYD51 duration=1m40.403461554s

Nov 25 13:01:45 moonrise prometheus[12298]: level=warn ts=2020-11-25T13:01:45.589Z caller=manager.go:598 component="rule manager" group=hardware msg="Evaluating rule failed" rule="alert: DdmPredictedLaneBiasHigh...

Nov 25 13:01:50 moonrise prometheus[12298]: level=info ts=2020-11-25T13:01:50.329Z caller=head.go:809 component=tsdb msg="Head GC completed" duration=5.901566168s
Nov 25 13:01:50 moonrise prometheus[12298]: level=info ts=2020-11-25T13:01:50.415Z caller=checkpoint.go:96 component=tsdb msg="Creating checkpoint" from_segment=52928 to_segment=52937 mint=1606305600000
Nov 25 13:02:07 moonrise prometheus[12298]: level=info ts=2020-11-25T13:02:07.285Z caller=head.go:889 component=tsdb msg="WAL checkpoint complete" first=52928 last=52937 duration=16.870492769s
```

Looking at historical logs it's always the same pattern - error is always preceded by `caller=compact.go:494 component=tsdb msg="write block"`

**Comment by brian-brazil** [comment]
That's a relatively long head GC, how many series do you have in the head and what sort of churn?

**Comment by tarko** [comment]
3975817 of series in the head currently, 2020-11-25 14:00:00 +0000 UTC to 2020-11-25 15:27:18 +0000 UTC

There is definetly some churn but shouldn't be too bad as 99.9% of the data is gathered from SNMP and is pretty stable.

**Comment by brian-brazil** [comment]
Hmm, ddm_lane_bias and ddm_bias_hi_thresh don't sound like SNMP metrics. Are those also fully stable over time?

**Comment by tarko** [comment]
These go through custom exporter indeed but originate from SNMP. Either way they are pretty stable but devices/interfaces are ofc coming and going over time (but longer periods mostly, not in minutes).

**Comment by brian-brazil** [comment]
Given it's happening around head compaction/GC, I'd expect it's a series appearing/disappearing either around that time or at the edge of the data being requested. Blocks are 2h, so that you've a 2h range is suspicious here.

**Comment by tarko** [comment]
Sounds plausible. From error it looked like an write issue (to a chunk that has been GCd) but the "cannot populate chunk" can probably be read as "cannot read from TSDB to memory" instead.

**Comment by raqqun** [comment]
Hi there we also encountered the same errors after upgrading from 2.16 to 2.22. Logs are here :

```text
level=info ts=2020-11-26T21:06:37.723Z caller=compact.go:494 component=tsdb msg="write block" mint=1606413600000 maxt=1606420800000 ulid=01ER35P451XJPANNZGC4VFSBQB duration=6m37.689854082s
level=info ts=2020-11-26T21:07:08.634Z caller=db.go:1152 component=tsdb msg="Deleting obsolete block" block=01EQGY1BWRX576R94MTN6ARP38
level=warn ts=2020-11-26T21:07:08.652Z caller=manager.go:598 component="rule manager" group=kube-apiserver.rules msg="Evaluating rule failed" rule="record: apiserver_request:burnrate1d\nexpr: ((sum(rate(apiserver_request_duration_seconds_count{job=\"apiserver\",verb=~\"LIST|GET\"}[1d])) - ((sum(rate(apiserver_request_duration_seconds_bucket{job=\"apiserver\",le=\"0.1\",scope=~\"resource|\",verb=~\"LIST|GET\"}[1d])) or vector(0)) + sum(rate(apiserver_request_duration_seconds_bucket{job=\"apiserver\",le=\"0.5\",scope=\"namespace\",verb=~\"LIST|GET\"}[1d])) + sum(rate(apiserver_request_duration_seconds_bucket{job=\"apiserver\",le=\"5\",scope=\"cluster\",verb=~\"LIST|GET\"}[1d])))) + sum(rate(apiserver_request_total{code=~\"5..\",job=\"apiserver\",verb=~\"LIST|GET\"}[1d]))) / sum(rate(apiserver_request_total{job=\"apiserver\",verb=~\"LIST|GET\"}[1d]))\nlabels:\n  verb: read\n" err="cannot populate chunk 557072240345092: not found"
level=warn ts=2020-11-26T21:07:09.831Z caller=manager.go:598 component="rule manager" group=kube-apiserver-availability.rules msg="Evaluating rule failed" rule="record: apiserver_request:availability30d\nexpr: 1 - ((sum(increase(apiserver_request_duration_seconds_count{verb=~\"POST|PUT|PATCH|DELETE\"}[30d])) - sum(increase(apiserver_request_duration_seconds_bucket{le=\"1\",verb=~\"POST|PUT|PATCH|DELETE\"}[30d]))) + sum(code:apiserver_request_total:increase30d{code=~\"5..\",verb=\"write\"} or vector(0))) / sum(code:apiserver_request_total:increase30d{verb=\"write\"})\nlabels:\n  verb: write\n" err="cannot populate chunk 727852655837187: not found"
level=info ts=2020-11-26T21:07:14.945Z caller=head.go:809 component=tsdb msg="Head GC completed" duration=6.311463791s
level=info ts=2020-11-26T21:07:15.435Z caller=checkpoint.go:96 component=tsdb msg="Creating checkpoint" from_segment=89051 to_segment=89060 mint=1606420800000
level=info ts=2020-11-26T21:09:46.128Z caller=head.go:889 component=tsdb msg="WAL checkpoint complete" first=89051 last=89060 duration=2m30.69380133s
```

**Comment by ipstatic** [comment]
We are seeing this too on some recording/alerting rules that have different ranges that go past the compaction boundary. @brian-brazil what other information can we provide to help troubleshoot the issue?

**Comment by roidelapluie** [comment]
I have the same issue: #8397

**Comment by roidelapluie** [comment]
Is this a part of https://github.com/prometheus/prometheus/issues/5877 ?

**Comment by brian-brazil** [comment]
That seems likely.

**Comment by shinebayar-g** [comment]
Just noticed same issue on fresh [kube-prometheus-stack](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack) Helm chart deployment. It was one of the `kube-apiserver.rules` Unfortunately I couldn't grab the full rule details, it was gone after refresh.

**Comment by progvp** [comment]
Same issue on the latest `kube-prometheus-stack` helm chart. Here's the log entries:
```
level=info ts=2021-06-22T17:00:05.121Z caller=compact.go:513 component=tsdb msg="write block" mint=1624370400293 maxt=1624377600000 ulid=01F8TAM6T5FT8FDJ5H1CPB6A16 duration=3.899195223s
level=warn ts=2021-06-22T17:00:05.144Z caller=manager.go:603 component="rule manager" group=kube-apiserver.rules msg="Evaluating rule failed" rule="record: apiserver_request:burnrate3d\nexpr: ((sum by(cluster) (rate(apiserver_request_duration_seconds_count{job=\"apiserver\",verb=~\"POST|PUT|PATCH|DELETE\"}[3d]))\n  - sum by(cluster) (rate(apiserver_request_duration_seconds_bucket{job=\"apiserver\",le=\"1\",verb=~\"POST|PUT|PATCH|DELETE\"}[3d])))\n  + sum by(cluster) (rate(apiserver_request_total{code=~\"5..\",job=\"apiserver\",verb=~\"POST|PUT|PATCH|DELETE\"}[3d])))\n  / sum by(cluster) (rate(apiserver_request_total{job=\"apiserver\",verb=~\"POST|PUT|PATCH|DELETE\"}[3d]))\nlabels:\n  verb: write\n" err="cannot populate chunk 1001734012946: not found"
level=info ts=2021-06-22T17:00:05.254Z caller=head.go:925 component=tsdb msg="Head GC completed" duration=127.366434ms
```

Error has gone after around 5 minutes

**Comment by codesome** [comment]
From the error message and the log times of when Head GC and the error occured, I conclude that it is the Head GC vs open queries interactions. Similar to blocks, we need a query tracker for Head and delay truncation of Head (with a timeout) if there are open queriers spanning the truncation time.

**Comment by codesome** [comment]
I have reproduced this in https://github.com/prometheus/prometheus/pull/9077

**Comment by codesome** [comment]
Closed by https://github.com/prometheus/prometheus/pull/9081/
