### ISSUE TITLE
promtool tsdb backfil does not check for # EOF

### ISSUE THREAD

**Issue by roidelapluie** [prometheus/prometheus#8228]
If I create a file without a newline, we still ingest the metrics.

```
echo -n a 1 $(date +%s) > test
```

```
./promtool tsdb create-blocks-from openmetrics test data4
BLOCK ULID                  MIN TIME                       MAX TIME                       DURATION  NUM SAMPLES  NUM CHUNKS  NUM SERIES  SIZE
01ER321F9RE4P1QVSC8KD1KJZE  2020-11-26 19:56:14 +0000 UTC  2020-11-26 19:56:14 +0000 UTC  1ms       1            1           1           514B
```

I do think that we should enfore the files to end with \n, to backfilling corruption (e.g a truncated timestamp). I do not especially think we should enforce the # EOF.

**Comment by brian-brazil** [comment]
> I do think that we should enfore the files to end with \n, to backfilling corruption (e.g a truncated timestamp). I do not especially think we should enforce the # EOF.

OpenMetrics requires the # EOF, if that's not causing a failure then that's a bug  - as that's there to catch things like file truncation.

**Comment by roidelapluie** [comment]
We do not require it at the moment.

**Comment by roidelapluie** [comment]
Given that we parse one line at the time, we can also ingest:

```
a 1 1
# EOF
b 1 1
```

Which is also not valid.

**Comment by brian-brazil** [comment]
The parser is meant to be catching all of that already. It looks like the backfill code is creating a parser per line, rather than a parser per file.

**Comment by roidelapluie** [comment]
Yes, that is what I see too.

**Comment by roidelapluie** [comment]
This is probably because the current parser can't stream and we would need to put all the file in memory prior to scan it.

**Comment by brian-brazil** [comment]
Thinking on it, the simple thing would be to mmap.

**Comment by beorn7** [comment]
I don't think that mmap'ing is ever simple.

Having a first-class streaming capability in the parser would be great, though.

Stopping at the first `# EOF` would be easy to add to the current backfill implementation, even with the line-based parsing.

As we go through the whole file first to detect the max and min timestamp, it's also easy to bail out at that time if there is no `# EOF` at the end before even starting the actual backfill work.

**Comment by brian-brazil** [comment]
> I don't think that mmap'ing is ever simple.

In this case I think it might be, as it's a one-shot CLI tool that already requires a real file. There's no complex memory management or concurrency to worry about.
