### ISSUE TITLE
compaction failed, err="reload blocks: head truncate failed: create checkpoint: read segments: corruption in segment data/wal/00003343 at 13025513: unexpected checksum 8cab5432, expected afc8abd0"

### ISSUE THREAD

**Issue by NilChow** [prometheus/prometheus#8236]
This error occurs from 18th of this month, now the data only until to 18th, and the last few hours.
Before that, due to out of disk space, it failed when  “write to WAL”. Is this cause the this error? But after that, the compaction was still suceessed once, then continued failed, until now.
Looking forward to your reply！

![image](https://user-images.githubusercontent.com/57666663/100497991-03002d80-319a-11eb-86e9-4c7ba441245a.png)

**Comment by NilChow** [comment]
I checked the wal directory, there are datas from the 18th to today, how can I slove this error, and compact these datas.
![image](https://user-images.githubusercontent.com/57666663/100498252-df3de700-319b-11eb-8f3d-894f888ed265.png)

**Comment by roidelapluie** [comment]
Please fill in the template so we can determine if it is a known bug:

https://github.com/prometheus/prometheus/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by brian-brazil** [comment]
We looked at this in the bugscrub and without the information requested above we can't proceed further, so are closing this pending that information.
