### ISSUE TITLE
group aggregator can't be parsed in a recording rule

### ISSUE THREAD

**Issue by Shadi** [prometheus/prometheus#8253]
**What did you do?**

I tried to create a recording rule that is using the recently introduced group() aggregator but I got the following error:
```
The  "prometheusrules" is invalid: : 1:2366: group "public-alerts", rule 4, "node_pod_pids_limit": could not parse expression: 1:7: parse error: unexpected <by>
```

The same expression works directly on Prometheus:

```
    - node_pod_pids_limit
      expr: |
        6144 * max by (node)(kube_node_role{role=~"ingress.*"})
          or
        1024 * max by (node)(kube_node_info)
```

I looked at the parsing code a bit and I think its being matched as a function in generated_parser.y instead of an aggregator, but I have no idea why it works directly on prometheus, as far as I can see the parsing code path in engine.go is the same as rulefmt.go

**What did you expect to see?**

a valid query expression should be also valid as a recording rule expression

**Environment**

* System information:

	`Linux 4.15.0-124-generic x86_64`

* Prometheus version:

```
prometheus, version 2.22.1 (branch: HEAD, revision: 00f16d1ac3a4c94561e5133b821d8e4d9ef78ec2)
  build user:       root@516b109b1732
  build date:       20201105-14:02:25
  go version:       go1.15.3
  platform:         linux/amd64
```

rule:
```
    - record: node_pod_pids_limit
      expr: |
        6144 * max by (node)(kube_node_role{role=~"ingress.*"})
          or
        1024 * max by (node)(kube_node_info)
```

**Comment by Shadi** [comment]
Argh sorry not a bug, we are using an older version of prometheus-operator which is using a pre v2.20.0 prometheus package.

**Comment by roidelapluie** [comment]
your exemple shows max instead of group

**Comment by Shadi** [comment]
I switch to max until the issue is fixed and forgot to revert it before copying it, I will update the description.
