### ISSUE TITLE
Add <aggregation>_over_time function that always returns 1

### ISSUE THREAD

**Issue by jutley** [prometheus/prometheus#8255]
## Proposal

**Use case. Why is this important?**

In order to alert when we stop seeing a metric, I often use a query pattern like this:

```
sum by (foo, bar) (max_over_time(my_metric[1w]))
unless
sum by (foo, bar) (my_metric) 
```

The idea is that there is a result in the past week that no longer exists, we can be notified.

What I don't like is `max_over_time`. We do not need the max value for the series over that range, or even any particular value. We just need *some* value. Using `max_over_time` carries unnecessary semantics that can confuse people down the road, and also adds additional computation.

Similar to how the `group by` operation was introduced to group labels without a meaningful value, I think it makes sense to do something similar for the `<aggregation>_over_time` functions. For every time series that exists in the provided range vector, the function would return `1`.

I'm not sure what this would be called. Perhaps `present_over_time`, in contrast to `absent_over_time`?

**Comment by roidelapluie** [comment]
```
group by (foo, bar) (count_over_time(my_metric[1w]))
```

Would already be better I think for your usecase, but I am not opposed to a present_over_time function.
