### ISSUE TITLE
Backfill: Fully utilize OM parser rather than parsing the input line by line.

### ISSUE THREAD

**Issue by beorn7** [prometheus/prometheus#8266]
To avoid reading the whole OM input file into memory first, we are currently using a fairly ad-hoc wrapper around the OM parser that allows parsing from a `Reader` interface by parsing every line of the input separately. This requires explicit treatment of an `# EOF` line and prevents multi-line operations that the parser might perform in the future.

Option 1: `mmap` the input file so that it can be fed to the parser as a byte slice without the requirement to load it completely into the user space. Pro: No changes to the parser required. Conceptually simple approach. Con: mmap'ing is not natively supported by Go. Logically, we are still just linearly reading a file, for which mmap'ing is not a good fit.

Option 2: Add 1st-class support for parsing from a `Reader` to the OM parser. Pro: Clean approach, makes the parser more generally usable. Con: Can be tricky to code. Current parser code liberally makes use of the data being available as a byte slice.

**Comment by roidelapluie** [comment]
mmap implemented in #8232
