### ISSUE TITLE
[API] api/v1/series with only non-empty matcher killing the memory

### ISSUE THREAD

**Issue by ahurtaud** [prometheus/prometheus#8286]
**What did you do?**

Calling the api Series with only an empty matcher increases by A LOT the memory (and cpu) usage.
One of my user basically OOM Killed my prometheus with a label_values on grafana on a label which does not exist.

`curl -g 'http://<prometheus>/api/v1/series?match[]={foo=%22%22}'`

![Screen Shot 2020-12-14 at 17 36 39](https://user-images.githubusercontent.com/25080995/102108381-23cfb080-3e33-11eb-8e7c-d39f0222575a.png)

**What did you expect to see?**

I would like prometheus to reject the matcher like it is with the query UI with the following query:

`{foo=""}`

![Screen Shot 2020-12-14 at 17 39 56](https://user-images.githubusercontent.com/25080995/102108601-6a250f80-3e33-11eb-846e-e0b93a4a286c.png)

* Prometheus version:
	v2.23.0 (happen on most releases)

**Something else to add**

Weirdly this API call answer instantly an empty success:

`curl -g 'http://<prometheus>/api/v1/series?match[]={}'`

**Comment by roidelapluie** [comment]
I have opened #8288 but there is probably room for improvement here ; e.g. maybe a flag with a limit of series that it returns before erroring?
