### ISSUE TITLE
REGRESSION: A test now fails on machines set to a timezone other than CEST

### ISSUE THREAD

**Issue by swsnider** [prometheus/prometheus#829]
In commit d868264bb883835cbbf7f4c3c17c0442e1d6f576, a test of the humanizeTimestamp template function is hard-coded to assume CEST, and therefore fails on both my mac, and a Dockerfile I just wrote to build the software in my CI pipeline.

**Comment by juliusv** [comment]
@swsnider Ah ZOMG, of course. Sorry about that. Will fix.

**Comment by beorn7** [comment]
CEST is the timezone of the SoundCloud HQ, so obviously the perfect timezone for everybody... ;->
