### ISSUE TITLE
Add more scrape limits

### ISSUE THREAD

**Issue by roidelapluie** [prometheus/prometheus#8291]
As per the last dev summit:

We want to implement the easy, configurable defenses, like label name/value length and number of scraped labels. We will fail the scrape when hit. We will provide counters to make this easy for users.

The above will be configurable during runtime.

cc @lilic

**Comment by lilic** [comment]
Looking forward to this feature! Would be interesting in tackling this, but most likely cannot get to it until next year, is that still okay? Thanks!

**Comment by roidelapluie** [comment]
Yes, totally okay, I will assign to you. End of the year is always a quiet period.

**Comment by lilic** [comment]
So @roidelapluie before I start the work, to understand correctly we want to add the following config fields:
- limit for the number of scraped labels -> `LabelLimit`
- limit for the length of label name -> `LabelNameLenghtLimit`
- limit for the length of value name -> `LabelValueLenghtLimit`

Let me know if I missed any here, and if you have any better naming suggestions for the fields to be more self-descriptive, thanks!

**Comment by nrchakradhar** [comment]
>The above will be configurable during runtime.
Does this mean that, the values can be increased, decreased at runtime. Would there be any side effects especially when values are decreased?

**Comment by roidelapluie** [comment]
That sounds right @lilic

**Comment by roidelapluie** [comment]
> > The above will be configurable during runtime.
> 
> Does this mean that, the values can be increased, decreased at runtime. Would there be any side effects especially when values are decreased?

When values are changed we would invalidate scrape cache. That should not be visible to users.

**Comment by lilic** [comment]
Sadly I never got the time to work on this, due to other higher priority tasks. Now since leaving the team, I have handed the task over to @dgrisonnet. 

But thank you @roidelapluie for pinging me on it! 🙇‍♀️

**Comment by dgrisonnet** [comment]
Happy to take over @lilic's work on this feature :slightly_smiling_face:

**Comment by bwplotka** [comment]
Nice, some follow up question regarding:

> limit for the number of scraped labels -> LabelLimit

Do we mean per single metrics or per job or overall in Prometheus?

**Comment by roidelapluie** [comment]
this is a scrape job setting that applies to any metric post relabelling
