### ISSUE TITLE
Proposal: Allow humanizeDuration to work on stringified numbers

### ISSUE THREAD

**Issue by asherholder** [prometheus/prometheus#8303]
When you have a stringified number as a label, it would be nice to be able to use the same humanizeDuration logic on it.
Example: label_name: "interval": "5400" => "1h 30m"

**Comment by brian-brazil** [comment]
You can't apply a Go function that takes in a float type to a string instead, so there's no way to make that work.

Given that labels are opaque strings I would either suggest changing the label value, or having a time series which has this as both a value and label value and working from there.

**Comment by roidelapluie** [comment]
What are you trying to achieve?

**Comment by roidelapluie** [comment]
Hello

We have looked at this during our bug scrub and decided to close this issue.

This is not feasible with go templating, so it is out of scope for prometheus. Please consider the above workaround. Thanks!

**Comment by beorn7** [comment]
That's not quite true. I have created #8339. This is not to say we _have_ to provide the feature. But technically, it's possible. So we need a "real" decision here.

**Comment by roidelapluie** [comment]
Thanks @beorn7 , I did forget that this was indeed custom functions. I am in favour of this, and to extend to other functions. Especially useful alerting on histograms.

**Comment by brian-brazil** [comment]
I'm not sure it's a good idea to be doing this sort of type magic, it's not very Go and could get weird when you look at the various functions we have and all the potential type conversions. I think any type conversions should be explicit, not implicit magic.

I'd also like to hear more about the original use case, we currently only have one sentence.

**Comment by roidelapluie** [comment]
So by explicit, you mean we could have a type conversion function?

**Comment by brian-brazil** [comment]
Yeah, though it'd be parsing rather than type conversion as we're not exactly casting here.

**Comment by ties** [comment]
> I'd also like to hear more about the original use case, we currently only have one sentence.

I am alerting when newly encountered objects have a time to live that is too short (e.g. `increase(metric_expiration_seconds_bucket{le="54611.0"}[15m] > 0`). When alerting for this, it is useful that the alert contains a readable amount of time such as by `humanizeDuration`: 56411.0s is not readable, 15h10m is.

**Comment by jebeaudet** [comment]
Would you be open into supporting `int` as well? We have threshold that we'd like to show in the alerts that might be float or int : 
```    - alert: ${config.db_instance_identifier}-DbRamMaxLow
      expr: avg_over_time(aws_rds_freeable_memory_average{dbinstance_identifier=~"${config.db_instance_identifier}.*"}[1d]) < ${config.db_ram_minimum_freeable_memory_bytes_low}
      for: 5m
      annotations:
        description: ${config.db_instance_identifier} is approaching the minimum acceptable threshold for freeable memory. Current freeable memory = {{ $value | humanize}}, threshold = {{ ${config.db_ram_minimum_freeable_memory_bytes_low} | humanize}}.
        summary: Database freeable memory is approaching minimum
```
Here we have some template coming from terraform but basically `${config.db_ram_minimum_freeable_memory_bytes_low}` is sometimes a float, sometimes an int depending on the result of the computation : 
```
db_ram_minimum_freeable_memory_bytes_low = 0.075 * var.instance_max_ram
```
I could convert everything into a string I guess but if we support float, I can't see why we shouldn't support int as well.
Thanks

**Comment by beorn7** [comment]
Prometheus only knows floats. Even if it is an integral number, it is still represented as a float.

**Comment by jebeaudet** [comment]
Not sure who's seeing int then but given the error message I got, it's not only floats : 
```
<error expanding template: error executing template __alert_xxx-redacted: template: __alert_xxx-redacted:1:242: executing "__alert_xxx-redacted" at <humanize>: wrong type for value; expected float64; got int>
```
For others that might end up here, I've solved it by using terraform `format` function `{{ ${format("%.2f, config.your_variable_here)} | humanize}}`, that will make any number a float in the yaml.

**Comment by beorn7** [comment]
I see. That number is not coming from Prometheus, but it's inserted into your YAML by terraform. And apparently, a plain integer number in Go templating is parsed as an `int`, which then collides with `humanize` only expecting a string ar a float64.

This is probably very niche, but I don't see any reason to not let `humanize` and `humanizeDuration` cover that case, too.

**Comment by jebeaudet** [comment]
Great news thanks, I'll submit a proper issue + PR in the next days, unless you want to do it yourself. In that case, let me know. 

Thanks

**Comment by beorn7** [comment]
PRs are always welcome! (@roidelapluie please shout if you don't agree with my assessment here).

**Comment by roidelapluie** [comment]
It's fine for me :)
