### ISSUE TITLE
Prometheus Agent

### ISSUE THREAD

**Issue by RichiH** [prometheus/prometheus#8305]
As per the dev summit: https://docs.google.com/document/d/1iO1QHRyABaIpc6xXB1oqu91jYL1QQibEpvQqXfQF-WA

This is the design document: https://docs.google.com/document/d/1wWrTMWn8UgxgSeao8n1TABPm6pnKIGJmEDdbbWV7lRQ

**Comment by rfratto** [comment]
Can this be closed with #8785 being merged?
