### ISSUE TITLE
Prometheus ecosystem benchmarking

### ISSUE THREAD

**Issue by RichiH** [prometheus/prometheus#8306]
Just to cross-track https://docs.google.com/document/d/12DcuwrHnR-gVbWQq2Qq5UI2ZIq5CqS7W3OYALU6Bke8

It does not really fit in prometheus/prometheus, but this location is least bad for now.

**Comment by kaffarell** [comment]
Have we already implemented this with the prombot and `/prombench main` command or am I missing something?

**Comment by bboreham** [comment]
Hello from the bug-scrub!
Looks like this didn't go anywhere, so closing.  @RichiH if you disagree we can re-open.
@kaffarell prombench is ok for (a subset of) Prometheus specifically, but I think the "ecosystem" part of the title refers to benchmarking other things which are compatible with Prometheus.
