### ISSUE TITLE
Prometheus remote-write receiver

### ISSUE THREAD

**Issue by RichiH** [prometheus/prometheus#8307]
As per the dev summit: https://docs.google.com/document/d/1iO1QHRyABaIpc6xXB1oqu91jYL1QQibEpvQqXfQF-WA

CONSENSUS:  We want to explore remote write in Prometheus as an EXPERIMENTAL feature behind a feature flag. We will explore this without restricting possible approaches. We will do this in a design doc at first.

This is the design document: https://docs.google.com/document/d/1PpTDtVaKAnhMRxBJ0k7_rCQ3Z3uJVcALgdPo0QpObSk

Also see https://github.com/prometheus/prometheus/issues/4769

**Comment by hpcre** [comment]
I'm not a Prometheus expert, but may i suggest a brief description of what is proposed for the remote write feature? So that all comments are sure to be relevant and on track

**Comment by inancgumus** [comment]
https://github.com/loadimpact/k6/issues/1761

**Comment by RichiH** [comment]
@hpcre this would allow Prometheus to ingest bulk data, not through pulling and scraping, but through a push model.

**Comment by brancz** [comment]
I don't think bulk importing was the intended use case, remote-write would be rather unsuitable for this, as bulk inserts need something much more efficient (I believe there was a separate consensus on a rough design for a bulk inserts). It's so you can have effectively the reverse model of today's federation model, so you could have multiple Prometheus servers in many sites, push their data into a central Prometheus.

**Comment by beorn7** [comment]
FYI: The first stage of a bulk import feature has been implemented as part of the `promtool` command line tool. It will be released with v2.24 in two days. You can then import from OpenMetrics files with a command line like `promtool tsdb create-blocks-from openmetrics`.

**Comment by valdemarpavesi** [comment]
will be "remove DUP" implemented for HA-Prometheus ?

![image](https://user-images.githubusercontent.com/10376101/107418274-13a71b00-6adc-11eb-829f-e967afbb9c1b.png)

**Comment by brancz** [comment]
I think that probably needs more discussion. I would personally prefer the de-duplication method Thanos implements, which happens at query time.

**Comment by tomwilkie** [comment]
This was implemented in #8424 and released in 2.25.0.

@valdemarpavesi this change is unrelated to HA setup, and you're still expect to run a pair of Prometheus.  @brancz I suggest we have a separate discussion about HA pair handling and deduplication - there are pros and cons to both approaches.

I'd like to close this ticket and not piggy back that discussion here, if that okay?

**Comment by brancz** [comment]
> I suggest we have a separate discussion about HA pair handling and deduplication - there are pros and cons to both approaches.

I agree there are pros and cons of either, I could even see us allowing either as they essentially just choose different trade-offs.

> I'd like to close this ticket and not piggy back that discussion here, if that okay?

Agreed! Feel free to close.
