### ISSUE TITLE
Higher memory usage after upgrade from 2.18.3 -> 2.23.0

### ISSUE THREAD

**Issue by kustodian** [prometheus/prometheus#8310]
**What did you do?**
Upgraded Prometheus from 2.18.3 to 2.23.0.

**What did you expect to see?**
Smaller memory footprint because I read the release notes for all releases in between and I saw a few improvements for the memory footprint.

**What did you see instead? Under which circumstances?**
We see higher memory usage. We especially see bigger memory spikes every 2 hours, compared to 2.18.3. Check the image below. The big memory spike is in the middle is the Prometheus restart.

![image](https://user-images.githubusercontent.com/1949229/102878034-f2b13a80-4447-11eb-97ea-aaec5afff958.png)

Note that Apps memory is basically `Total - (free + all other types of memory)`.

**Environment**
```
CentOS 7.x
```
* System information:
```
Linux 3.10.0-957.21.2.el7.x86_64 x86_64
```
* Prometheus version:

```
prometheus, version 2.23.0 (branch: HEAD, revision: 26d89b4b0776fe4cd5a3656dfa520f119a375273)
  build user:       root@37609b3a0a21
  build date:       20201126-10:56:17
  go version:       go1.15.5
  platform:         linux/amd64
```

**Comment by codesome** [comment]
> Total - (free + all other types of memory)

Can you share the query you used for that?

**Comment by kustodian** [comment]
I knew that you will ask me that :D Here it is:
```
sum(node_memory_MemTotal_bytes{instance=~"$node:$port"} - node_memory_MemFree_bytes{instance=~"$node:$port"} - node_memory_Buffers_bytes{instance=~"$node:$port"} - node_memory_Cached_bytes{instance=~"$node:$port"} - node_memory_Slab_bytes{instance=~"$node:$port"} - node_memory_PageTables_bytes{instance=~"$node:$port"} - node_memory_SwapCached_bytes{instance=~"$node:$port"}) by (instance)
```

**Comment by codesome** [comment]
The node memory is not very useful here. Could you check the memory used only by Prometheus?

**Comment by codesome** [comment]
You could use `process_resident_memory_bytes` for that

**Comment by kustodian** [comment]
Since Prometheus is the only thing on this VM which is doing something, the trend of that metric will be the same, but here it is:
![image](https://user-images.githubusercontent.com/1949229/102975340-32d3f400-4500-11eb-8945-7aeb48da7944.png)

**Comment by roidelapluie** [comment]
Hello,

Can we please have screenshots of the Prometheus benchmark dashboard? https://grafana.com/grafana/dashboards/12054

Thanks

**Comment by kustodian** [comment]
Is something like this ok?
![image](https://user-images.githubusercontent.com/1949229/104917369-9af8e700-5993-11eb-8d14-4ab203849358.png)

**Comment by MCPDanilovich** [comment]
I have the same problem:
![image](https://user-images.githubusercontent.com/25364749/107030004-febb4680-67c0-11eb-8434-fb0d4b6c33af.png)

But after update to 2.24.1 situation is better.
2.23 version:
![image](https://user-images.githubusercontent.com/25364749/107029673-750b7900-67c0-11eb-9cc3-ad27e2645c0d.png)
2.24.1 version:
![image](https://user-images.githubusercontent.com/25364749/107029712-88b6df80-67c0-11eb-88c0-21b1c7ff0e2a.png)

Memory usage rate is slower in 2.24.1 version

**Comment by MCPDanilovich** [comment]
But I see growth of rss (process_resident_memory_bytes{job="prometheus",instance="$Prometheus:9090"})

**Comment by srinivasev** [comment]
Hi @codesome, is there any update on this issue. We observed similar behavior when adopted 2.23.0 Prometheus.

**Comment by SuperQ** [comment]
`process_resident_memory_bytes` is not the correct metric to look at for these versions. This is due to the way Go marks memory free for the OS to use.

https://tip.golang.org/doc/go1.16#runtime

Upgrading to Prometheus >= 2.26.0 will change this behavior to make RSS more closely follow the real (`go_memstats_alloc_bytes`) memory usage of the process.
