### ISSUE TITLE
Check upon config load whether alerting rule template fields can be parsed

### ISSUE THREAD

**Issue by juliusv** [prometheus/prometheus#835]
A user got `error parsing template __alert_GlimpseDNSHighLatency: template: __alert_GlimpseDNSHighLatency:1: unexpected "*" in operand; missing space?` in the Alertmanager email message because they had `{{$labels.quantile * 100}}` in their alerting message template, which isn't valid in Go templates. Can we detect this sort of thing at configuration load time by test-parsing the SUMMARY and DESCRIPTION fields?

**Comment by fabxc** [comment]
We can add a parse+execute cycle to the `promtool`. Parsing alone doesn't guarantee that much for templates.
I'll look into that later today.

**Comment by codesome** [comment]
I have done some similar checks in https://github.com/prometheus/prometheus/pull/4277. Only catch is that it wont detect `$labels.something_wrong`, but would detect `$something_wrong`, and the one mentioned in the issue description.

I will open a PR for this.
