### ISSUE TITLE
React UI version of Status -> Targets shows spurious ': address <host>: missing port in address' for localhost targets when behind an Apache reverse proxy

### ISSUE THREAD

**Issue by siebenmann** [prometheus/prometheus#8358]
**What did you do?**

We have our Prometheus instance behind a HTTPS Apache reverse proxy. Since the switch to the new React UI in 2.23.0, the /targets URL (from Status -> Targets) will show an error for all targets of ': address <our-host>: missing port in address' for most targets it reports. It appears that this warning shows up only for targets where the endpoint is 'localhost' or '127.0.0.1', except for the scrape of Prometheus itself on 'http://localhost:9090/metrics'.

I am running 2.24.0 (and before it 2.23.0) in setups that aren't behind an Apache reverse proxy and those instances don't show this problem.

**Environment**

* System information:

	Linux 4.15.0-117-generic x86_64

* Prometheus version:

	prometheus, version 2.24.0 (branch: HEAD, revision: 02e92236a8bad3503ff5eec3e04ac205a3b8e4fe)
  build user:       root@d9f90f0b1f76
  build date:       20210106-13:48:37
  go version:       go1.15.6
  platform:         linux/amd64

Our Prometheus configuration is relatively large and I expect it to not be relevant. However, some of our command line flags are probably relevant here, so:

    prometheus --config.file=/etc/prometheus/prometheus.yml [tsdb settings etc] --web.external-url=https://csmetrics.cs.toronto.edu/prometheus/ --web.route-prefix=/ --web.listen-address=127.0.0.1:9090

**Comment by roidelapluie** [comment]
Thanks for this report!

cc @juliusv

**Comment by roidelapluie** [comment]
Thank you. This bug is harmless and should not have any impact besides wrongly showing an error in the UI. I am working on a patch.

**Comment by roidelapluie** [comment]
![Uploading host.png…]()

**Comment by roidelapluie** [comment]
A fix is in #8359
