### ISSUE TITLE
Expose Query Stats via Headers

### ISSUE THREAD

**Issue by gotjosh** [prometheus/prometheus#8366]
## Proposal
**Use case. Why is this important?**

Exposing query stats on queries is available by using the `stats=true` query parameter. The stats are then exposed via the response body. It would be useful if we could expose these stats via a header to avoid having to parse the whole body while keeping track of these for statistics.

Extracting these stats from top-level proxies would result in more intensive computation by having the proxy parse the response.

I think we can have the same JSON blob be embedded as part of a header when we use a query parameter like `stats=header`.

**Comment by brian-brazil** [comment]
That seems a bit weird to me, the HTTP header is the frame not the packet and starting to extract arbitrary data into HTTP headers doesn't seem like it'd end well in terms of complexity. If you want to track stats, there's already metrics from Prometheus itself.

**Comment by gotjosh** [comment]
That's fair, I can see the angle.

**Comment by roidelapluie** [comment]
> ## Proposal
> **Use case. Why is this important?**
> 
> Exposing query stats on queries is available by using the `stats=true` query parameter. The stats are then exposed via the response body. It would be useful if we could expose these stats via a header to avoid having to parse the whole body while keeping track of these for statistics.
> 
> Extracting these stats from top-level proxies would result in more intensive computation by having the proxy parse the response.
> 
> I think we can have the same JSON blob be embedded as part of a header when we use a query parameter like `stats=header`.

You can also use the query log file.
