### ISSUE TITLE
Add a "AllowList" for label values

### ISSUE THREAD

**Issue by wederbrand** [prometheus/prometheus#8375]
## Introduce a "AllowList" for label values
**Keeping number of time series under control**
Some values for labels might come directly from a client, such as a "client_name" or "segment" or similar. 
Instead of letting all services/targets keep this filter up to date it would be nice if Prometheus could do it.

So for each metric, or by a regexp filter, allow some values and block all other, or possibly merge them as "other".

**Comment by roidelapluie** [comment]
You are looking for a two-step metrics_relabel_config with
- labelmap
- labelkeep
This is already possible.
