### ISSUE TITLE
PromQL template variables for start and end

### ISSUE THREAD

**Issue by codesome** [prometheus/prometheus#8377]
## Proposal

Pulling out the discussion from https://github.com/prometheus/prometheus/pull/8121, we would like to have some handy variables to denote start, end, and range of a query in PromQL. These are template variables which are evaluated before giving the query to the PromQL engine. The main pain point here is coming up with a syntax that does not conflict with many other template formats.

Grafana uses `$var` `${var}` and `[[var]]`. Go uses `{{$var}}` `{{do something}}`. Since Prometheus is used with these often, we cannot use them. **Edit:** we can use the Grafana variables because it ignores the variables that it does not know and passes it through as it is.

Here are some random possible examples for the template variable syntax that does not conflict with PromQL and hopefully not many other template formats that are widely used with Prometheus
1. `<<var>>`
2. `$<var>`
3. `$[var]`
4. `$:var:`
5. `start()` `end()` `range()`

Suggestions are welcome. It would be nice to have some variable in place before the next release to use with the `@` modifier.

cc @beorn7 @brian-brazil @roidelapluie

**Comment by beorn7** [comment]
I'm sure you discussed this already, but could you perhaps summarize here why those cannot be treated syntactically like functions, i.e. `start()`, `end()`, `range()`? We already have `time()`, which has some similarities. I get that the latter interacts with the query engine in a different way (rather than just a preprocessing step). But couldn't we see that as an implementation detail? Do we have to create a new syntax, just because it is handled differently internally? Or in other words: Is it important from the user's perspective that these are not "real" PromQL functions?

**Comment by beorn7** [comment]
What's the planned behavior for instant queries? I assume start and end will both return the same as `time()` and range will be zero.

**Comment by codesome** [comment]
The only subtle difference is that currently PromQL functions are meant to work with the evaluation time that it is being executed and does not have any other metadata, so the time() makes sense. start() end() range() need additional metadata about the query. A different syntax for these would make it explicit to user regarding its behaviour. Maybe templating will help extend it further for future use cases too?

That said, I am not against start() end() range() (adding it to the issue description now).

> What's the planned behavior for instant queries? I assume start and end will both return the same as time() and range will be zero.

That is my understanding too.

**Comment by brian-brazil** [comment]
> Grafana uses $var ${var} and [[var]].

I had thought these were in principle viable, as Grafana passes through anything it doesn't recognise?

> why those cannot be treated syntactically like functions, i.e. start(), end(), range()?

Using the same syntax for things with different semantics is unwise as that leads to confusion and unintuitive behaviours down the road. Consider for example what happens to a potential future step() used inside a subquery, or you use start() inside a expression that's using `@`.

> We already have time(), which has some similarities.

Time() is independent of the outermost range query evaluation, whereas these are not. Time() is a completely normal PromQL function semantically, like every other function it has no knowledge of range queries.

> Or in other words: Is it important from the user's perspective that these are not "real" PromQL functions?

Yes, as these values can go in places where arbitrary PromQL expressions can't such as in `@`, and potentially also the range of a range vector selector in future. That would cause confusion, as you could put things that are syntactically functions in some places but not others.

Range also seems a bit redundant, you can do subtraction if you want it.

**Comment by codesome** [comment]
> you can do subtraction if you want it

Number to duration conversion is not supported yet I guess? For a start, simpler is better (from implementation perspective)

**Comment by codesome** [comment]
> I had thought these were in principle viable, as Grafana passes through anything it doesn't recognise?

Then I don't see a problem with ${start}

**Comment by codesome** [comment]
Or maybe even go templating with {{$start}}, which will make it much easier to work with.

**Comment by roidelapluie** [comment]
We would need to double check what grafana does.

**Comment by codesome** [comment]
> We would need to double check what grafana does.

Tried in Grafana explore, it ignores what it does not know and gives to Prometheus

**Comment by codesome** [comment]
> Tried in Grafana explore, it ignores what it does not know and gives to Prometheus

But it does not pass the original thing. This is the error message

Query `rate(prometheus_tsdb_head_chunks_created_total[$grafanadoesnotknow])`
`"invalid parameter \"query\": 1:48: parse error: missing unit character in duration"`

Query `rate(prometheus_tsdb_head_chunks_created_total[{{$grafanadoesnotknow}}])`
`"1:48: parse error: missing unit character in duration"`

So I don't think we can reliably use them in Grafana

**Comment by beorn7** [comment]
Thanks for the arguments against the function syntax. Those are good points, but I don't see them as sufficient for a decision.

Of course, those functions (or pseudo-functions) need a clearly defined behavior, but I don't see a problem to define them as returning the parameters of the range query always. (Inside a sub-query, you know the step already, as you have provided it. Inside an expression pinned with `@`, you alsa know it. So there is no real need to provide a function for those.)

The confusion of what we allow as a `@` parameter (and later in ranges of range selectors) is certainly a concern, but how far do we want to carry that? It would be nice to allow simple arithmetic like subtraction or multiplication for those, but do we really want to come up with a new syntax for subtraction and multiplication just for the sake of making the user aware that it's not an arbitrary PromQL expression? (Ultimately, I would like to explore actually allowing arbitrary PromQL expressions there. I get why we don't want to open this version of Pandora's box now, but I wouldn't exclude it for eternity.)

**Comment by roidelapluie** [comment]
As we would only allow that after @, maybe @ start or @ end might just work fine.

**Comment by codesome** [comment]
Why just for `@`? I would see this to be used anywhere rather than just for `@`.

**Comment by roidelapluie** [comment]
> Why just for `@`? I would see this to be used anywhere rather than just for `@`.

What would be the usecase?

**Comment by codesome** [comment]
> What would be the usecase?

https://docs.google.com/document/d/1jMeDsLvDfO92Qnry_JLAXalvMRzMSB1sBr9V7LolpYM/edit

Depending on how this goes, we will have use cases

**Comment by roidelapluie** [comment]
First time I see that doc :) will browse it.

**Comment by codesome** [comment]
> First time I see that doc

It was linked in the @ timestamp design doc :)

**Comment by ArthurSens** [comment]
> > Why just for `@`? I would see this to be used anywhere rather than just for `@`.
> 
> What would be the usecase?

What I'm most looking forward to is using this if range selectors, something like:

```
sum(
  rate(apiserver_request_total{code=~"5.."}[start_of_month()]) @ <some_time_based_grafana_variable>
)
/
sum(
  rate(apiserver_request_total[start_of_month()]) @ <some_time_based_grafana_variable>
)
```
instead of:
```
sum(
  rate(apiserver_request_total{code=~"5.."}[30d])
)
/
sum(
  rate(apiserver_request_total[30d])
)
```

With that, It would be possible to "reset" my SLOs at the start of every month, very useful for monthly reports about our services reliability.

**Comment by beorn7** [comment]
Yeah, that's what I'm looking for, too, but I think it needs a more thorough treatment of calendars and timezones, see that document that @codesome just linked above. Start of month in Berlin or in New York? And maybe you are using the Chinese calendar for billing purposes…

@roidelapluie gave this talk at PromCon: https://promcon.io/2019-munich/talks/improved-alerting-with-prometheus-and-alertmanager/
It has some mind blowing examples, including calculating the time of Easter in PromQL. Which leads is back to allowing arithmetic or even arbitrary PromQL expressions…

But as said, this is a quite big version of Pandora's box. One step after another.

**Comment by brian-brazil** [comment]
> Or maybe even go templating with {{$start}}, which will make it much easier to work with.

That is not viable, as it'd directly conflict with notification/console templating in Prometheus.

> do we really want to come up with a new syntax for subtraction and multiplication just for the sake of making the user aware that it's not an arbitrary PromQL expression? (Ultimately, I would like to explore actually allowing arbitrary PromQL expressions there. I get why we don't want to open this version of Pandora's box now, but I wouldn't exclude it for eternity.)

I'd presume we'd end up with PromQL, but with semantic restrictions. There's practical and performance limits on what you can put in an `@` or range vector range, basically they must be a constant across all steps for a given query and not touch the TSDB.

I had proposed limiting the scope of the initial `@` to avoid that particular can of worms derailing things, but it all needs to be kept in mind.

> As we would only allow that after @, maybe @ start or @ end might just work fine.

The problem is that is valid PromQL, in particular an instant vector selector. If you use that, then you have to come up with a new distinct expression language if you want to allow arithmetic in future.

Having the same string mean two different things and more importantly have a different type depending on the context in which it is used is a recipe for confusion. Context-dependant types are to be avoided and have ended poorly any time I've seen them attempted, let's keep it so that any given sub-expression in isolation has exactly one potential type.

**Comment by brian-brazil** [comment]
> The problem is that is valid PromQL, in particular an instant vector selector. If you use that, then you have to come up with a new distinct expression language if you want to allow arithmetic in future.

Or more succinctly, what would the following PromQL expression do? `start - time()`

**Comment by roidelapluie** [comment]
Can we imagine having another kind of functions, "static functions" who would get the context of the query? This would be an implementation details in promql, for users it would just be functions `start()` , `end()`, `range()`

**Comment by brian-brazil** [comment]
Those would be functions only because "function" is in the name, they're not like other functions and still leaves you the problem that some things that look like functions work in one place but not another. The set of data that a function has access to is purposefully limited and having things called "functions" with access to data well outside that scope seems unwise to me. The less constrained a definition is, the less useful it is.

**Comment by roidelapluie** [comment]
So, what about:

`.start` `.end` `.range`

`!start` `!end` `!range`

**Comment by brian-brazil** [comment]
`!` looks like a not operator, which is confusing. Dots are also weird, that kinda looks like a metric name but not quite.

**Comment by codesome** [comment]
Few more characters :P

`&start` `&end` `&range`

`?start` `?end` `?range`

**Comment by roidelapluie** [comment]
Those would mess up with urls and API's :)

**Comment by brian-brazil** [comment]
Why aren't you considering $start?

**Comment by codesome** [comment]
Because of https://github.com/prometheus/prometheus/issues/8377#issuecomment-762240400. But turns out I was wrong, checked again. I think $start is totally viable and can be used.

**Comment by roidelapluie** [comment]
Okay. Is there a way in grafana to escape $start in case you have it as a dashboard variable?

**Comment by roidelapluie** [comment]
> Okay. Is there a way in grafana to escape $start in case you have it as a dashboard variable?

Note that we should not block on that.

**Comment by codesome** [comment]
> Note that we should not block on that.

Right. Users can always modify their variables.

**Comment by codesome** [comment]
How do we decide on a syntax now? I would like to propose `$start $end $range` here since that looks very familiar and has no conflicts with Grafana or Go templates. Raise your voices if you have any concerns about that.

**Comment by roidelapluie** [comment]
:+1:

**Comment by roidelapluie** [comment]
Maybe $step, too

**Comment by codesome** [comment]
I would like to start with start, end and range for now. I think $step will be more useful when we are able to do arithmetic on them while preserving the semantics (the doc in https://github.com/prometheus/prometheus/issues/8377#issuecomment-762257087)

**Comment by beorn7** [comment]
Do we really need `range` if that's just the delta between `start` and `end`?

Even if this is will be behind a feature flag initially, it seems we are touching a few pivotal questions here about future directions of PromQL. I suggested this topic for the dev-summit later this week and I would prefer to see what the room thinks there. If we don't get to it, we can still try to make a call here in this issue (or consider other ways of nailing down a decision).

**Comment by roidelapluie** [comment]
As things stands we need range as it would be considered a duration for now (?)

The use case I'd like to solve is `topk_over_time(metric[$range] @ $end)`

**Comment by brian-brazil** [comment]
I think the way to handle that is to make is to durations are just syntactic sugar for scalar literals, where values ultimately are in seconds. Then $start/$end/$range are all scalar literals and would work everywhere you would want them to. As a bonus you could pass 1h into predict_linear etc.

**Comment by codesome** [comment]
In the dev summit that happened yesterday ([notes](https://docs.google.com/document/d/10o4gkjgK46MdUHTowpUG_pyeON3Z5k0CbPBqQ211KOE/edit)), keeping the long term view of what we eventually would like to do (allow PromQL with `@`, arithmetic on timestamps, durations, etc), we decided to go with `start()` syntax instead of introducing a new syntax. Additionally, this goes behind `--enable-feature=promql-at-modifier`.

I will open a PR for this and I would like to add `start()` `end()` and `range()` (range since we don't have support for semantic preserving arithmetic on timestamps, and also the shorthand for range is going to be very handy).

I will defer `step()` for later, or do we have any use cases right now without the need of semantic preserving airthemtic operations on them?

**Comment by beorn7** [comment]
I would have loved to have `step()` a couple of times in the past, but that was mostly related to using it as parameter for `offset` or in range selectors. To make a (pseudo) function that just returns the number of seconds of the specified step useful in those cases, we _also_ need to change range selectors and `offset` to accept bare numbers (with the implication they are seconds).

Similarly, `range()` isn't really usable as a parameter for `@` without arithmetic (and once we have arithmetic, it's just a bit of syntactic sugar). `range()` could be useful in range selectors (how fitting…), but then again we needed it to accept bare numbers rather than just a duration literal.

So my question: Do you plan to tackle the "bare numbers as duration literals" (essentially: append a `s` if there is none)? (That's what @brian-brazil just said [above](https://github.com/prometheus/prometheus/issues/8377#issuecomment-766905594).) If you do, I'd definitely include `step()` right now.

**Comment by roidelapluie** [comment]
As said, I'd love if we can make an exception and make range() return a duration when used as `topk_over_time(metric[range()] @ end())`

**Comment by codesome** [comment]
I am with @roidelapluie here to add `end()`. And eventually, allow bare numbers for durations.

**Comment by beorn7** [comment]
> I'd love if we can make an exception and make range() return a duration …

My gut feeling is that we are all fine with allowing bare numbers for durations (implying "seconds"). So I'd say before going down the rabbit hole of what kind of exceptions and special cases we want to define, let's just do the "bare numbers for duration" first.

**Comment by codesome** [comment]
I will open a PR for start() and end() for now since those are biggest blockers for using @ sanely.

**Comment by roidelapluie** [comment]
> > I'd love if we can make an exception and make range() return a duration …
> 
> My gut feeling is that we are all fine with allowing bare numbers for durations (implying "seconds"). So I'd say before going down the rabbit hole of what kind of exceptions and special cases we want to define, let's just do the "bare numbers for duration" first.

I am fine with that.
