### ISSUE TITLE
I want to where are Prometheus Htlm, Js, cs pages.?

### ISSUE THREAD

**Issue by Mehmoodulhassan104** [prometheus/prometheus#8381]
Hi there,
I want to add some functionality in Prometheus UI, Please tell me where are the Prometheus html, cs and js pages. Thanks in advance.

**Comment by roidelapluie** [comment]
Hello,

You will find all the information on this page: https://github.com/prometheus/prometheus/tree/master/web/ui/react-app

Regards,

**Comment by roidelapluie** [comment]
Also, please note that we have a [prometheus-developers mailing list](https://groups.google.com/forum/#!forum/prometheus-developers). On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
