### ISSUE TITLE
error when run "yarn start"

### ISSUE THREAD

**Issue by huangwei2013** [prometheus/prometheus#8385]
**What did you do?**

compile/run ui by yarn

**What did you expect to see?**

it runs

**What did you see instead? Under which circumstances?**

[root@k8s-master react-app]# yarn 
yarn install v1.22.5
[1/4] Resolving packages...
  success Already up-to-date.
Done in 1.14s.

info There appears to be trouble with your network connection. Retrying...
[root@k8s-master react-app]# 
[root@k8s-master react-app]# yarn start
yarn run v1.22.5
$ react-scripts start
/go/src/github.com/prometheus/prometheus/web/ui/react-app/node_modules/react-dev-utils/WebpackDevServerUtils.js:167
  compiler.hooks.done.tap('done', async stats => {
                                  ^^^^^

SyntaxError: missing ) after argument list
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/go/src/github.com/prometheus/prometheus/web/ui/react-app/node_modules/react-scripts/scripts/start.js:45:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Environment**

centos7.6 (aliyun cloud)
promethues-master (downloaded about 2021/01/18)

* System information:

	insert output of `uname -srm` here

* Prometheus version:

	insert output of `prometheus --version` here

* Alertmanager version:

	insert output of `alertmanager --version` here (if relevant to the issue)

* Prometheus configuration file:
```
insert configuration here
```

* Alertmanager configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```

**Comment by roidelapluie** [comment]
It seems that your nodejs version is too old. Can you tell us the output of `$ node --version` ?

**Comment by huangwei2013** [comment]
@roidelapluie  em.... yes, I found my nodejs is toooo old. It's fine now~

thx
