### ISSUE TITLE
Backfill: Add --simple-output

### ISSUE THREAD

**Issue by roidelapluie** [prometheus/prometheus#8389]
When you try to import a year of data, using the tsdb backfill command, I suspect that the print of the blocks, which forces to re-read the database medata again and again, slows the command by a lot. I would like to have a --quiet or -- simple-output option which would speed that print, and instead just output the blocks ULID.

**Comment by roidelapluie** [comment]
cc @aSquare14 FYI

**Comment by codesome** [comment]
> I suspect that the print of the blocks, which forces to re-read the database medata again and again, slows the command by a lot.

Biggest slowdown I think is the re-iteration of entire file for every block. There is some room for improvement by indexing the file location ranges for each block on first iteration.

**Comment by aSquare14** [comment]
Yep, I think there is room for improvement using indexing but I think @roidelapluie's suggestion about print also makes sense. Sending a PR for that in a while.
