### ISSUE TITLE
panic during Appender.Commit()

### ISSUE THREAD

**Issue by asp24** [prometheus/prometheus#8396]
Sometimes panic happened during Appender.Commit() call

**What did you expect to see?**
No panics

**What did you see instead? Under which circumstances?**
```
panic: runtime error: index out of range [2767] with length 2767

goroutine 8739 [running]:
github.com/prometheus/prometheus/tsdb.(*headAppender).Commit(0xc0b6350f80, 0x0, 0x0)
	/go/pkg/mod/github.com/prometheus/prometheus@v1.8.2-0.20210119214810-e4487274853c/tsdb/head.go:1263 +0x5ad
github.com/prometheus/prometheus/tsdb.dbAppender.Commit(0xdb6520, 0xc0b6350f80, 0xc000324000, 0xdb7ea0, 0xc0c68a0080)
	/go/pkg/mod/github.com/prometheus/prometheus@v1.8.2-0.20210119214810-e4487274853c/tsdb/db.go:773 +0x35
```

**Environment**

* System information:

	Linux 4.19.112+ x86_64

* Prometheus version:

	Prometheus v2.24.1 TSDB storage used as dependency

**Comment by brian-brazil** [comment]
Can you share your config, and if you're doing anything unusual? Is this repeatable? Do you have the rest of the stack trace?

The only way I can see this happening is due to an appender being used concurrently, which isn't something we do as far as I'm aware.

**Comment by roidelapluie** [comment]
Can you please share prometheus --version as well.

**Comment by asp24** [comment]
@brian-brazil Thx for advise, it was parallel append in some corner case
