### ISSUE TITLE
Error with go1.16 in TestChunkDiskMapper_WriteChunk_Chunk_IterateChunks

### ISSUE THREAD

**Issue by roidelapluie** [prometheus/prometheus#8403]
@eclipseo reported

> I've got another error following:

```
github.com/prometheus/prometheus/tsdb/chunks
--- FAIL: TestChunkDiskMapper_WriteChunk_Chunk_IterateChunks (0.01s)
panic: runtime error: slice bounds out of range [:104326] with capacity 104293 [recovered]
	panic: runtime error: slice bounds out of range [:104326] with capacity 104293

goroutine 20 [running]:
testing.tRunner.func1.2(0x555db3ac0a40, 0xc0000d20d8)
	/usr/lib/golang/src/testing/testing.go:1144 +0x332
testing.tRunner.func1(0xc000086900)
	/usr/lib/golang/src/testing/testing.go:1147 +0x4b6
panic(0x555db3ac0a40, 0xc0000d20d8)
	/usr/lib/golang/src/runtime/panic.go:965 +0x1b9
github.com/prometheus/prometheus/tsdb/chunks.TestChunkDiskMapper_WriteChunk_Chunk_IterateChunks(0xc000086900)
	/builddir/build/BUILD/prometheus-2.24.1/_build/src/github.com/prometheus/prometheus/tsdb/chunks/head_chunks_test.go:122 +0xc9c
testing.tRunner(0xc000086900, 0x555db3ad7188)
	/usr/lib/golang/src/testing/testing.go:1194 +0xef
created by testing.(*T).Run
	/usr/lib/golang/src/testing/testing.go:1239 +0x2b3
exit status 2
FAIL	github.com/prometheus/prometheus/tsdb/chunks	0.015s
```

_Originally posted by @eclipseo in https://github.com/prometheus/prometheus/issues/8393#issuecomment-764948396_

**Comment by roidelapluie** [comment]
@codesome I can reproduce this locallhy with go1.16beta1. We need to triage that ASAP to know if it is a bug on our end or a regression in go that we have to report before the final release.

**Comment by roidelapluie** [comment]
Still present with the final go1.16, @bwplotka @codesome can you have a look here? Thanks!

**Comment by johejo** [comment]
Since go1.16
The byte slice returned by `ioutil.ReadFile` no longer has an extra 512 bytes capacity.
https://github.com/golang/go/commit/3d913a926675d8d6fcdc3cfaefd3136dfeba06e1

The crashed test expects that the 34 bytes extra capacity to be 0 padded.

https://github.com/prometheus/prometheus/pull/6830

**Comment by roidelapluie** [comment]
> Since go1.16
> The byte slice returned by `ioutil.ReadFile` no longer has an extra 512 bytes capacity.
> [golang/go@3d913a9](https://github.com/golang/go/commit/3d913a926675d8d6fcdc3cfaefd3136dfeba06e1)
> 
> The crashed test expects that the 34 bytes extra capacity to be 0 padded.
> 
> #6830

Awesome finding! Are you willing to propose a fix?

**Comment by johejo** [comment]
I'm not familiar deep inside the tsdb.

Why do we need to check that the capacity is 0 padded?
https://github.com/prometheus/prometheus/blob/1fac1c783bf6bc19d6883e7cb413fbf0f6f1381a/tsdb/chunks/head_chunks_test.go#L121-L124

**Comment by codesome** [comment]
> Why do we need to check that the capacities are 0 padded?

The files are preallocated in Windows but the file might not be full. So all 0 header marks the end of the file.

**Comment by roidelapluie** [comment]
> > Why do we need to check that the capacities are 0 padded?
> 
> The files are preallocated in Windows but the file might not be full. So all 0 header marks the end of the file.

This is not the same files. Those specific files are also preallocated on linux.

**Comment by bwplotka** [comment]
Ack, I can take a look

**Comment by bwplotka** [comment]
Fixed https://github.com/prometheus/prometheus/pull/8538

Rest of tsdb tests passed for me on Go1.6
