### ISSUE TITLE
--alertmanager.timeout has no effect

### ISSUE THREAD

**Issue by brian-brazil** [prometheus/prometheus#8405]
The value for --alertmanager.timeout isn't hooked up to anything, which is misleading at best. It looks like it has had no effect since around 2.0.0, and and this is configured in the config file these days. We should make it clear that this flag is deprecated, has no effect, and then remove it with Prometheus 3 whenever that is.

**Comment by roidelapluie** [comment]
Should we make it work instead?

**Comment by brian-brazil** [comment]
That'd be kinda weird, we don't take config file defaults from flags anywhere else.

**Comment by roidelapluie** [comment]
Oh indeed I missed that sentence in your initial statement.
