### ISSUE TITLE
tmpfs errors and failures

### ISSUE THREAD

**Issue by adsbxchange** [prometheus/prometheus#8406]
**What did you do?**
Prometheus + node_exporter on Buster
saving prometheus in TMPFS to save SD writes

**What did you expect to see?**
It working

**What did you see instead? Under which circumstances?**
faliures:

Jan 25 03:12:23 raspberrypi prometheus[6999]: level=error ts=2021-01-25T03:12:23.027Z caller=db.go:745 component=tsdb msg="compaction failed" err="compact head: persist head block: populate block: write chunks: preallocate: no space left on device"
Jan 25 03:13:23 raspberrypi prometheus[6999]: level=error ts=2021-01-25T03:13:23.069Z caller=db.go:745 component=tsdb msg="compaction failed" err="compact head: persist head block: populate block: write chunks: preallocate: no space left on device"
Jan 25 03:14:23 raspberrypi prometheus[6999]: level=error ts=2021-01-25T03:14:23.150Z caller=db.go:745 component=tsdb msg="compaction failed" err="compact head: persist head block: populate block: write chunks: preallocate: no space left on device"
Jan 25 03:15:23 raspberrypi prometheus[6999]: level=error ts=2021-01-25T03:15:23.186Z caller=db.go:745 component=tsdb msg="compaction failed" err="compact head: persist head block: populate block: write chunks: preallocate: no space left on device"
Jan 25 03:16:23 raspberrypi prometheus[6999]: level=error ts=2021-01-25T03:16:23.217Z caller=db.go:745 component=tsdb msg="compaction failed" err="compact head: persist head block: populate block: write chunks: preallocate: no space left on device"
Jan 25 03:17:23 raspberrypi prometheus[6999]: level=error ts=2021-01-25T03:17:23.254Z caller=db.go:745 component=tsdb msg="compaction failed" err="compact head: persist head block: populate block: write chunks: preallocate: no space left on device"
Jan 25 03:18:23 raspberrypi prometheus[6999]: level=error ts=2021-01-25T03:18:23.316Z caller=db.go:745 component=tsdb msg="compaction failed" err="compact head: persist head block: populate block: write chunks: preallocate: no space left on device"
Jan 25 03:19:23 raspberrypi prometheus[6999]: level=error ts=2021-01-25T03:19:23.391Z caller=db.go:745 component=tsdb msg="compaction failed" err="compact head: persist head block: populate block: write chunks: preallocate: no space left on device"
Jan 25 03:20:23 raspberrypi prometheus[6999]: level=error ts=2021-01-25T03:20:23.414Z caller=db.go:745 component=tsdb msg="compaction failed" err="compact head: persist head block: populate block: write chunks: preallocate: no space left on device"
Jan 25 03:21:23 raspberrypi prometheus[6999]: level=error ts=2021-01-25T03:21:23.430Z caller=db.go:745 component=tsdb msg="compaction failed" err="compact head: persist head block: populate block: write chunks: preallocate: no space left on device"

**Environment**
Raspbian Buster
* System information:

Linux 5.4.83-v7l+ armv7l

* Prometheus version:

prometheus, version 2.24.1 (branch: HEAD, revision: e4487274853c587717006eeda8804e597d120340)
  build user:       root@0b5231a0de0f
  build date:       20210120-01:04:17
  go version:       go1.15.6
  platform:         linux/arm

* Prometheus configuration file:
```
  - job_name: 'node'
    scrape_interval: 60s
    scrape_timeout: 10s
    static_configs:
      - targets: ['localhost:9100']

  - job_name: 'dump1090'
    scrape_interval: 60s
    scrape_timeout: 10s
    static_configs:
      - targets: ['localhost:9105']


```

```
=/usr/bin/prometheus --config.file=/etc/prometheus/prometheus.yml  \
        --storage.tsdb.path="/prometheus-tmpfs/prometheus" \
        --storage.tsdb.min-block-duration=30m --storage.tsdb.max-block-duration=1h \
       --storage.tsdb.wal-compression \
        --storage.tsdb.retention.time=1d --storage.tsdb.retention.size=50MB \
        --storage.tsdb.no-lockfile \
        --web.enable-admin-api


```
![Screenshot_2021-01-24_20-23-07](https://user-images.githubusercontent.com/34561158/105657634-18d05d00-5e82-11eb-9c8c-bf262d372cd8.png)
![Screenshot_2021-01-24_20-22-42](https://user-images.githubusercontent.com/34561158/105657639-18d05d00-5e82-11eb-98ba-e0003749a759.png)

**Comment by adsbxchange** [comment]
Plenty of space.  Fails first attempt.  Has been this way since 2.x .... was this intended?

**Comment by brian-brazil** [comment]
Looks like you've nowhere near enough disk space to me. It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by adsbxchange** [comment]
There's 200MB of TMFS with 20M in use and 181M available.   Can you not read the output of  df -h?

**Comment by roidelapluie** [comment]
Hello, Prometheus is using preallocation and files that can take multiple hundreds of MB.

**Comment by adsbxchange** [comment]
Is there a way to shut that off? Or has prometheus become useless for ramdisk operations?  This worked without issue in the 1.5.x releases.

**Comment by RichiH** [comment]
While I do understand that using software can be stressful, in particular when it's not acting as you want it to, and that it's human to have strong emotions sometimes, those emotions should not swap over onto GitHub or mailing lists. There are humans on the other side as well.

Please be aware that Prometheus is part of the CNCF and we do follow the CNCF CoC.

**Comment by adsbxchange** [comment]
This is either a bug or a lack of foresight with regard to tmpfs.   I'll give it a 1000MB of tmpfs just to prove the assumption wrong, instead of disregarding it, it can be addressed.  This seems to be a common issue, all you have to do is look at reported issues.

**Comment by RichiH** [comment]
1. You did receive a reply in https://groups.google.com/g/prometheus-users/c/3Qy1zGEnZWc -- where this kind of question belongs
2. "lack of foresight" is also not neutral language and you were asked to moderate yourself already. You can transmit the same meaning with neutral wording and we consider this a pre-requisite of taking part in our community.


I will lock this thread now.
