### ISSUE TITLE
Remote write should retry on 429

### ISSUE THREAD

**Issue by bboreham** [prometheus/prometheus#8418]
## Proposal

http code 429, meaning "too many requests", should be handled as a retryable condition by Prometheus remote write.

One scenario which has been observed using Cortex: if the backend goes down for ten minutes, all sending Prometheus will build up ten minutes of data in their WALs. Once service is restored they will send as fast as possible, even increasing the number of shards to go even faster.  Since the backend does not have resources to accept all sends in parallel, it has to choose between rejecting sends with a 5xx error so that they are retried, or dropping the data.  (Currently Cortex is coded to drop)

Currently, all 4xx errors cause the send to be dropped by Prometheus with an error report in the log, while all 5xx errors are retried.  429 could be changed to retry, with a limit on build-up of data if the overload is not temporary.

429 also allows a "retry-after" header so the back-end can indicate how much slower it would like Prometheus to go.

**Comment by csmarchbanks** [comment]
Hello!

There is an open PR to fix this, including setting the Retry-After header here: https://github.com/prometheus/prometheus/pull/8237. A few review comments need to be addressed, but hopefully it will be out soon.

**Comment by roidelapluie** [comment]
https://github.com/prometheus/prometheus/pull/8237 https://github.com/prometheus/prometheus/pull/7078

**Comment by bboreham** [comment]
I did search for existing issues; it seemed that changing _sharding_ behaviour on 429 was ruled out in #7078, and retrying was not the subject.
I did not think to search for PRs, sorry.

**Comment by roidelapluie** [comment]
> I did not think to search for PRs, sorry.

No problem, your input on the PR is welcome.

**Comment by csmarchbanks** [comment]
Reopening as this is not complete yet/first PR will be reverted.

**Comment by Harkishen-Singh** [comment]
@csmarchbanks I think this can be closed now?

**Comment by roidelapluie** [comment]
I would still want to discuss some points.

- Should we retry whithout retry-after or when retry-after is in the past?
- should we have a higher limit on retry-after?

**Comment by bboreham** [comment]
> Should we retry without retry-after 

Yes, it could be a server that hasn't been updated to send this info yet.

> or when retry-after is in the past?

Yes, that can be caused by network delay on the return path.  If it is a long way in the past, perhaps more interesting, but I can't see it as worth adding complexity for.

> should we have a higher limit on retry-after?

Like if the retry-after is ten years into the future?  Yes, I think it would be worth capping it at the max block duration, which is when the WAL will get dropped if I understand things.

**Comment by jgehrcke** [comment]
> Should we retry whithout retry-after or when retry-after is in the past?

Yes. An invalid `retry-after` value should be treated as non-existing.

A non-existing `retry-after` should result in the "standard retry strategy" to apply, which should _eventually_ come to an end (defined by [`batch_send_deadline`](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#remote_write)?).

(I have never contributed to Prometheus before, so take my input with a grain of salt.)

**Comment by csmarchbanks** [comment]
I generally agree with the above couple of replies. If retry-after is missing or in the past I think we should just use the default backoff.

One note, `batch_send_deadline` is not actually how long we allow a batch to be sent, it is how long we wait to put together a batch of samples (500 by default). That way low traffic Prometheus instances will still send their samples relatively quickly rather than wait for the entire batch to fill. There will need to be a new way of deciding when to stop retrying for 429s, easiest is probably a static number of tries, other options I have heard are to drop them if more than `x` minutes behind, or calculating derivatives and dropping 429s if Prometheus is backing up, and keep retrying if Prometheus is catching up.

**Comment by bboreham** [comment]
We had our staging Cortex system down for several hours, and I believe what I observed is that Prometheus will drop data from the WAL after two hours, so that data is never sent over remote-write.

Maybe we don't need any limit on retries beyond that?

**Comment by Harkishen-Singh** [comment]
> If retry-after is missing or in the past I think we should just use the default backoff.

I think the current code handles that?

> There will need to be a new way of deciding when to stop retrying for 429s, easiest is probably a static number of tries, other options I have heard are to drop them if more than x minutes behind, or calculating derivatives and dropping 429s if Prometheus is backing up, and keep retrying if Prometheus is catching up.

That looks like work for #8549 

Do we have anything else left in this issue?

**Comment by csmarchbanks** [comment]
Depending on the implementation #8549 can likely close this if it is agreed as a path forward. If not then some other work specific to 429s may need to be done.
