### ISSUE TITLE
Apply for "Official" status for our Docker images

### ISSUE THREAD

**Issue by SuperQ** [prometheus/prometheus#8426]
## Proposal

We can apply to make our images marked as "Official" on Docker hub.

See: https://docs.docker.com/docker-hub/official_images/

**Comment by beorn7** [comment]
@roidelapluie and I thought we should do this when we looked at this during bug scrub. @SuperQ do you want to own this?

**Comment by SuperQ** [comment]
Sure, I'll see if I have time this week to look into it.

**Comment by beorn7** [comment]
Hello from the bug scrub.

@SuperQ did this fall through the cracks? Are you still planning to work on this?

We believe this is still valid and useful. We could try to find someone else to work on this (maybe @LeviHarrison , see above ;), but we don't want to take it away from @SuperQ if he still wants it…

**Comment by LeviHarrison** [comment]
Happy to pick this up if @SuperQ doesn't want to.

**Comment by SuperQ** [comment]
Yes, I haven't had time to work on this.

**Comment by LeviHarrison** [comment]
Looking into this more, it's a far bigger effort than I expected.

Mainly, we'd need to create a new Docker image. A requirement of the official images program is that an "official" image can only be derived from another "official" image. So we can't just use our existing busybox image as a base, we'd have to move all the steps to the main Prometheus Dockerfile, so then it can be based off an official image (debian). Futhermore, Docker's CI system is going to be building these images from scratch, so we can't rely on our current process of building binaries using promu and then copying them in. We'd have to download them from the published release in the Dockerfile.

To do all of this, it seems like the general convention is to have a separate repository dedicated to just Dockerfiles (ex:  https://github.com/influxdata/influxdata-docker/tree/master). Once a new version is released from the main Prometheus repository (I think they allow us to include release candidates in the official image too), prometheus-docker would automatically be updated, and then a PR would have to be merged in https://github.com/docker-library/official-images before the new version could be officially published. That would be a new delay to deal with.

As far as the existing Dockerfile in this repository, I would probably keep it there so we can still push `main` tags to our own Docker repo. But everything else would have to go to the official image I think.

Let me know how all this sounds and if we should move forward.

**Comment by SuperQ** [comment]
Thanks for looking into this more closely. I don't think those required changes are things we want to do. Let's just stick with the current images/process.

**Comment by beorn7** [comment]
Yeah, it sounds like a lot of hoops to jump through. I'd say we have more pressing things to do…

**Comment by beorn7** [comment]
I'll close this for now, but if anyone feels strongly enough about it to invest the required work, feel free to re-open.

**Comment by LeviHarrison** [comment]
Agreed
