### ISSUE TITLE
Proposal: hrate() for graphing rates

### ISSUE THREAD

**Issue by candlerb** [prometheus/prometheus#8429]
### Part 1: `hrate()`

I would like to propose a new range vector rate function, `hrate`.  What it does is:

* Calculate the midpoint time of the given range interval
* Find the *last* data point in the *first half* of the time interval
* Find the *last* data point in the *second half* of the time interval
* Calculate the rate between these two

Example: the sampling interval is 1 minute, and A to J are stored data points:

```
    <------------- 10 minute range window ------------->

    [..A....B....C....D....E....F....G....H....I....J..]
                              |
                          half-way
                           point
```

`hrate(foo[10m])` would calculate the rate between points E and J.  This is roughly equivalent to:

```
(foo - foo offset 5m) / (timestamp(foo) - timestamp(foo offset 5m))
```

except that it also takes into account any counter resets in E-F-G-H-I-J.

The proposed name `hrate` is because it calculates the rate over about _half_ the given time window[^1].

### Part 2: range query step size available as range vector parameter

I propose some syntax - arbitrarily shown as `[*]` and `[+]` here - to use the current step size in a range.

When processing a [range query](https://prometheus.io/docs/prometheus/latest/querying/api/#range-queries), e.g. `/api/v1/query_range?start=START&end=END&step=STEP`:

* `foo[*]` is treated as `foo[STEP]`
* `foo[+]` is treated as `foo[2 * STEP]`

Outside of the context of a range query, some sensible default values are chosen[^2], e.g.

* `foo[*]` is treated as `foo[5m]`
* `foo[+]` is treated as `foo[10m]`

## Use case. Why is this important?

There is a long-standing issue around drawing graphs of rates in Prometheus.  The problem is that sudden counter changes which ought to be visible as spikes, are missed entirely if the step interval (the time interval between points on the X axis) is larger than the range interval being queried.

Although it's more obvious with `irate()` than `rate()`, it happens with `rate()` as well: consider the following where the query is `rate(foo[5m])` but the step is 10 minutes.

```
                       X..X..X..X..X..X..X..X..
                      .
..X..X..X..X..X..X..X..
 [             ]               [             ]
 <----range---->               <----range---->
               <------------STEP------------->
```

For each point the rate is calculated over a 5 minute window, but misses the jump in the metric.

What you actually want is for the rate to be calculated over the entire STEP interval.  If the step is 10 minutes, and the data is sampled at 1 minute intervals, you need `rate(...[11m])` to calculate the rate between two points 10 minutes apart.

The current workarounds for this are ugly.

* For a long time Grafana has had a variable `$__interval` equal to the step, but that was wrong[^3].  Grafana 7.2 introduced a new variable [`$__rate_interval`](https://grafana.com/docs/grafana/latest/datasources/prometheus/#using-__rate_interval-variable), which is set to be the sum of the graph step and the sampling interval (which is configured as an attribute of the data source and/or as `min_step`).   This works, but it involves hard-coding the sampling interval in the dashboard.  Prometheus timeseries don't necessarily have a fixed sampling interval anyway - you can crank it up and down in your scrape job - and different jobs can have different scrape intervals.  And of course, this only works in grafana -  nowhere else, including Prometheus' own web UI.
* VictoriaMetrics' flavour of PromQL redefined its `rate()` function to include the data point prior to the window start.  That gives the right answer (although you still need to choose a range vector window equal to the step), but makes it [incompatible with prometheus](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/165).  It also is inconsistent with other prometheus functions; e.g. you'd expect `count(...[5m])` and `sum(...[5m])` to use only the data points within the window, not one extra point outside of the window.

With the above proposal, you will be able to do `hrate(foo[+])` and always get the correct rate, and with any front-end (including prometheus' own web UI)

A range vector still only contains data points *within* the range, retaining the consistency of the Prometheus data model.

`hrate(foo[10m])` is roughly the same as VictoriaMetrics' `rate(foo[5m])`, in that they both look at the data point before the 5 minute point - but `hrate` does this without extending the query outside the defined range.  Effectively, the first half of the time window is the extension period.

## Downsides?

At first glance, it seems like it would be less efficient: e.g. with a step of 5 minutes, then `hrate(...[10m])` will read nearly twice as much data from the TSDB as `rate(...[6m])`, and those extra data points will be ignored when calculating the rate for that time.  This gets worse when you are zoomed a long way out, for say `hrate(...[120m])` vs `rate(...[61m])`.

However, if you've calculated a rate for the previous point in time, those points will already be in memory.  Hence the  efficiency depends on how well prometheus deals with overlapping range vector periods.

```
 A B C D E F G H I J K L M N O P Q R S T
[. . . . . . . . . .]                         foo[10m] @ t0
          [. . . . . . . . . .]               foo[10m] @ t5
                    [. . . . . . . . . .]     foo[10m] @ t10
```

-----

[^1]: Edge case: what if only one half of the time window contains any data points? There are two options: it could either return nothing, or it could fallback to the behaviour of `rate()` and return the rate between the first and last points available.  I would prefer the former, because otherwise you can get erratic rates when a timeseries is just starting, but could be persuaded the other way.

[^2]: Maybe better to use the global evaluation interval and twice the global evaluation interval.  That would be consistent with the default resolution in a [subquery](https://prometheus.io/docs/prometheus/latest/querying/basics/#subquery).

[^3]: Consider `rate(foo[$__interval])`.  If you are sampling data at 1 minute intervals, and your X-axis timestep is also 1 minute, then the range vector contains only 1 data point and no rate can be calculated.  Even if your X-axis timestep is 5 minutes, then you're calculating a rate over a 4 minute interval, which can introduce inaccuracies because one in 5 data points is ignored.

**Comment by candlerb** [comment]
Optional part 3, for bonus ease-of-use:

When parsing PromQL, if a `hrate(...)` function is parsed but the content is an instant vector rather than a range vector, automatically convert it to a range vector.  For simple expressions this will be adding `[+]`, and for complex expressions this will involve writing a subquery `[+:*]`

If this is done, you'll be able to write simple queries like `hrate(foo)` which "do the right thing".

**Comment by beorn7** [comment]
Thanks for your thoughts.

You are presenting yet another variation of the rich topic of rate calculation and range selectors. This has been intensely discussed for many years. Even if some individuals claim they have clearly found the best solution, I remain sceptic.
I could start now to list concerns I have with your approach, but with the limited about of time I have right now, it would inevitably be a less thoughtful and complete answer than you deserve. 

The good news is that the Prometheus team has decided to reconsider the whole topic thoroughly, gathering all the proposals made over the years, including the experience with actual implementations. See [this comment](https://github.com/prometheus/prometheus/issues/3806#issuecomment-748522887). The team has also decided to embrace feature flags (K8s style), so that it will become easier to add experimental new implementations without committing to supporting them forever or confusing mainstream users.

I would like to use #3806 as the umbrella issue for "improving `rate`" to not have a bunch of open issues sprinkled around. I will therefore close this issue, but mention it over in #3806. This will all be taken into account when we do our research. And even if the outcome is that we won't change or add anything, the effort will create a comprehensive explanation of the trade-offs made, which is much better then just saying “This is way more complicated than you think, trust me, I'm an engineer…”

Finally a bit of consolation for the waiting time: We will introduce arithmetic for durations and a `step()` (pseudo) function so that you can actually write `foo_total[step()]` or `foo_total[2*step()+10]`. See #8377.

**Comment by candlerb** [comment]
Thank you for your thoughtful and considered reply.  #8377 is pretty recent and I hadn't come across it yet.  Cheers!
