### ISSUE TITLE
@ timestamp can return a single result

### ISSUE THREAD

**Issue by roidelapluie** [prometheus/prometheus#8433]
When I run the query:

`timestamp(up @ 1612215335)`

curl 'http://127.0.0.1:9090/api/v1/query_range?query=timestamp%28up+%40+1612215335%29&start=1612129171.047&end=1612215571.047&step=345'

I have the result:

{"status":"success","data":{"resultType":"matrix","result":[{"metric":{"instance":"127.0.0.1:9090","job":"blackbox_exporter"},"values":[[1612129171.047,"1612215330.793"]]}]}}

I think that this should return "1612215330.793" for **each step**, not just a single data point.

Tested on d6402bcd820cced2d07e399bd9ffc357510ee0f8

**Comment by codesome** [comment]
After some brief investigation, looks like a bug specific to `timestamp()`.

https://github.com/prometheus/prometheus/blob/41247b69507342b8d26110207af988ad5a1310e5/promql/engine.go#L1128

Here it does not consider the offset of the vector selector while it should.
