### ISSUE TITLE
Test group in unit tests should allow a name property

### ISSUE THREAD

**Issue by mishamo** [prometheus/prometheus#8439]
## Proposal
A unit test file could have multiple test groups defined for different edge cases, all testing the same alert. 

The current output only informs the user of the `alertname`, `exp` and `got` for failing tests, with no indication of which of the actual test groups failed.

The proposal is to add an optional `name` property to a test group that would be output if there are failing tests.

**Comment by roidelapluie** [comment]
Thank you for this! I will dig into this and look at the PR soon.

**Comment by roidelapluie** [comment]
Fixed in #8440. Thanks!
