### ISSUE TITLE
Alerting with Prometheus using Flapjack

### ISSUE THREAD

**Issue by jeanfrancis** [prometheus/prometheus#844]
Anyone has  tried alerting in Prometheus using Flapjack ?

**Comment by juliusv** [comment]
Pretty sure nobody in the core team of developers has tried anything with Flapjack, but for general questions like this, I'd recommend asking on the mailing list or IRC channel (http://prometheus.io/community/).

Fine to close this issue here?

**Comment by jeanfrancis** [comment]
Thanks for the quick feedback
