### ISSUE TITLE
Combine NewHead() arguments into a HeadOptions struct in tsdb/head.go

### ISSUE THREAD

**Issue by codesome** [prometheus/prometheus#8447]
With more and more tumables coming for the Head blocks, the list of arguments in `NewHead` is getting very big and any change to them requires a change in lot of other places which uses NewHead (example: a new option is incoming with exemplars for the queue size).

Similar to DB Options, it would be nice to club relevant `NewHead` arguments into a `HeadOptions`.

**Comment by ankurkumarz** [comment]
I will start working on this
