### ISSUE TITLE
Convert CircleCI (windows) testing config to PS

### ISSUE THREAD

**Issue by mikeee** [prometheus/prometheus#8454]
https://github.com/mikeee/ChocoPackages/issues/10

Initially raised above I believe it may be more suitable as an issue raised here and also I'm proposing a fix that stops using bash as part of your windows test workflow and moves towards PowerShell. The CircleCI configuration should be modified to do the above.

The Go windows installer recently implemented a change in the location where the binaries are installed to (from the root of C:\ to Program Files) and labelled this as a security issue.
Given the testing script uses Choco to upgrade Go to the latest version, it seems it has been caught out by this change. I believe it is not an issue with the package and maybe worth upgrading this repo rather than changing the installation location globally for all users as the change makes a lot of sense.

What needs to be recreated in PS:

- General syntax
- Refresh the environment post-install (not entirely necessary but this should provide reassurance)
- Convert the regex (excludes) list to PS
- Run the tests

**Comment by roidelapluie** [comment]
Thanks a lot for your analysis and the deep dive. TSDB testing under windows is important to us, as with a new release this week, I am really happy about this.
