### ISSUE TITLE
feature: add collapse/expand all button to ui target page for react ui

### ISSUE THREAD

**Issue by juliantaylor** [prometheus/prometheus#8461]
This was added for the old UI but not the react UI, but now that the react ui is default this is relevant again, see following issue:
https://github.com/prometheus/prometheus/issues/6127

> The ui target page can contain a lot of different scrape jobs which can be collapsed to give a good overview.
What is missing is a collapse and expand all targets button to help navigate to targets on is interested in quickly.
In our case we have prometheus configurations with many jobs, some of them have thousands of scrape targets. The default on first visit is to have all targets are expanded and one has to scroll many pages to get to a target one wants to check. After the first visit the collapsed jobs are stored in the browser which makes it ok, but if you have many different prometheus instances you have to do a of clicks each time you visit a new one.

**Comment by hooten** [comment]
I can work on this.
