### ISSUE TITLE
Remote write: Make HTTP 429 errors recoverable only when the user opts-in

### ISSUE THREAD

**Issue by roidelapluie** [prometheus/prometheus#8474]
We have to make the 429-retry mechanism in remote-write opt-in, I'd prefer as a remote write configuration flag (per remote-write url).

> This is indeed a breaking change. From what I can we see, we _never_ drop data here? This means Prometheus will just keep falling behind if it is being constantly rate-limited? This assumes that Prometheus doesn't send data to a remote system that basically limits it constantly.
>
> This is not true, we limit people in GrafanaCloud pretty regularly and they're completely fine with it. Further, in Cortex, we return 429 not just on a samples per second limit and do it for other cases too. For example, we have a limit for _active series_ and if a user sends more than their active series limit, we return a 429. In this case, Prometheus would _never_ be able to proceed because it would constantly try to send the sample that creates a new series and it would fail forever.
>
> Now I am not sure if Cortex has the right behavior with 429 for other limits, it seemed pretty right when we built it ;) I still think it has the right behavior, but given Cortex has a major chunk of remote-write use-cases, we shouldn't roll out this change in Prometheus until we fix it in Cortex. WDYT @roidelapluie @csmarchbanks?

_Originally posted by @gouthamve in https://github.com/prometheus/prometheus/issues/8237#issuecomment-777369196_

**Comment by roidelapluie** [comment]
@gouthamve 429 is not the right behaviour, it should be 400

```
The HTTP 429 Too Many Requests response status code indicates the user has sent too many requests in a given amount of time ("rate limiting").
```

It should in general not be about the content of the requests being wrong, but just too many request being sent.

**Comment by pracucci** [comment]
> 429 is not the right behaviour for cortex IMO

I agree Cortex shouldn't use 429 for the max series/metadata limits and we should (will) change it. However, having the new behaviour not the default would allow Cortex to gain some time to let Cortex operators to upgrade.

**Comment by Harkishen-Singh** [comment]
I will take up this and submit a fix.

**Comment by csmarchbanks** [comment]
I am happy with a configuration flag (probably defaulted to off for now). 

Another future solution would be to limit the number of retries for 429s, e.g. only retry once or twice then drop them to avoid backing up too much

**Comment by pracucci** [comment]
> Another future solution would be to limit the number of retries for 429s, e.g. only retry once or twice then drop them to avoid backing up too much

May be non trivial, but an alternative approach could be retrying 429 until Prometheus is not lagging behind a threshold. After that drops 429 and move forward with the remote write.

**Comment by csmarchbanks** [comment]
https://github.com/prometheus/prometheus/issues/7912 is an issue to do that for anything retryable.

**Comment by Harkishen-Singh** [comment]
> Another future solution would be to limit the number of retries for 429s, e.g. only retry once or twice then drop them to avoid backing up too much

That's what I meant with `Max-Retries` header in the PR.
