### ISSUE TITLE
Error when trying to install promtool

### ISSUE THREAD

**Issue by JarnoRFB** [prometheus/prometheus#8480]
**What did you do?**
`go get -v github.com/prometheus/prometheus/cmd/promtool`

**What did you expect to see?**
promtool being installed.

**What did you see instead? Under which circumstances?**
```
# github.com/prometheus/prometheus/cmd/promtool
../go/src/github.com/prometheus/prometheus/cmd/promtool/main.go:645:35: not enough arguments in call to api.LabelValues
	have (context.Context, string, time.Time, time.Time)
	want (context.Context, string, []string, time.Time, time.Time)
```

**Environment**
* Go version
`go version go1.15.8 linux/amd64`

* System information:
Ubuntu 20.04.2 LTS
`Linux 5.4.0-65-generic x86_64`

**Comment by skorpy2009** [comment]
https://github.com/prometheus/client_golang/commit/babeb356a51b1277535260e0122ad8c46240ab96#diff-9a3a8e3f0424115273d9a05e9b087ad13a7872995a962822be6975c287d3857cR234 introduced the bug

**Comment by roidelapluie** [comment]
Thank you. Promtool builds fine within out CI, so I think it might be in your local setup.

Can you try with a released binary? You can get them at https://prometheus.io/download/ ; it is shipped with Prometheus.

Alternatively, could you try to run:

```
git clone https://github.com/prometheus/prometheus
cd prometheus
make build
```

which is the "official" way to build Prometheus.

**Comment by ZyanKLee** [comment]
I got the same issue when building in docker with Dockerfile:

```
FROM golang:1.15.8-buster as prom

RUN go get github.com/prometheus/alertmanager/cmd/amtool ;\
    go get github.com/prometheus/prometheus/cmd/promtool ;\
    /go/bin/amtool --version ;\
    /go/bin/promtool --version
```

`amtool` installs fine, but `promtool` fails with the message mentioned above.

**Comment by beorn7** [comment]
You have to make sure to be in Go-module mode. If you just build from the lastest state of all the dependencies, you'll run into the breaking change that was merged in prometheus/client_golang recently.

For example, you could run
```
GO111MODULE=on go get -v github.com/prometheus/prometheus/cmd/promtool@master
```

In general, it's recommended to use the released binaries published [here](https://prometheus.io/download/). If you want to build things yourself, be prepared to run into some Go shenanigans.

**Comment by JarnoRFB** [comment]
Using `GO111MODULE=on go get -v github.com/prometheus/prometheus/cmd/promtool@master` works indeed, thanks!

It should be mentioned that building  `promtool` from source is explicitly mentioned in the docs https://prometheus.io/docs/prometheus/latest/configuration/recording_rules/ . I believe it would make sense then to instead recommended to use the released binaries. I can provide a PR if that makes sense.

**Comment by beorn7** [comment]
Good catch. I created #8491 to address that.
