### ISSUE TITLE
promtool LabelValues call doesn't have enough arguments

### ISSUE THREAD

**Issue by shaheinm** [prometheus/prometheus#8494]
I'm working on a Prometheus based tool called [Pelorus](https://github.com/konveyor/pelorus), and we're noticing a bug where the `LabelValues` function from the [Prometheus Go client](https://github.com/prometheus/client_golang) requires one more argument than is passed in the call from promtool.

Here is the function signature in the go client:

```
func (h *httpAPI) LabelValues(ctx context.Context, label string, matches []string, startTime time.Time, endTime time.Time) (model.LabelValues, Warnings, error)
```

And here is where promtool calls out to it:

```
val, warn, err := api.LabelValues(ctx, name, stime, etime)
```

I hacked a quick test on my fork of prometheus, sending a nil slice through the call and our tests succeeded. You can view the tests for yourself here:

**[Failure](https://github.com/konveyor/pelorus/runs/1905714744?check_suite_focus=true)**
**[Passing](https://github.com/konveyor/pelorus/runs/1906694425?check_suite_focus=true)** (using my [fork](https://github.com/shaheinm/prometheus/commit/a08be17262b9797ac162507d72a36825ae8b058e))

**What did you do?**

Ran promtool rules test with labels

**What did you expect to see?**

The tests should run

**What did you see instead? Under which circumstances?**

The tests failed to run. GitHub Actions showed an error message:

```
not enough arguments in call to api.LabelValues
````

**Comment by roidelapluie** [comment]
Hello, we have removed our vendor directory recently. Can you please try with the environment variable GO111MODULE=on ? Thanks!

**Comment by shaheinm** [comment]
@roidelapluie It does result in a different error message, so progress :)

There still seem to be some dependency issues, though https://github.com/konveyor/pelorus/pull/250/checks?check_run_id=1920077661

**Comment by roidelapluie** [comment]
I have commented in the pull request.

**Comment by shaheinm** [comment]
much appreciated, this can be closed out
