### ISSUE TITLE
Add computer name as meta label in azure_sd_config

### ISSUE THREAD

**Issue by DaveOHenry** [prometheus/prometheus#8499]
## Expose ```osProfile.computerName``` as meta label in [azure_sd_config](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#azure_sd_config)
**Computer name is the name that is used by Azure DNS. If this info was available from Prometheus SD we could easily build some relabel configs on top of it and reliably monitor the status / availability of all DNS registrations.**

**Background**
We have a service that runs on Azure Virtual Machine Scale Sets and relies on internal DNS resolution, therefore we need to check if all the computer names can be resolved.

**Comment by roidelapluie** [comment]
There is a rate-limiting issue with the azure SD. I am afraid we can't add more RPC calls here.

Do you know if that info would be available with our current RPC calls?

**Comment by DaveOHenry** [comment]
Unfortunately I'm not familiar with Go, but I'm pretty sure that the information is already available in the object(s) that are retrieved via the Azure SDK calls.

________________________________
Von: Julien Pivotto <notifications@github.com>
Gesendet: Dienstag, 16. Februar 2021, 20:17
An: prometheus/prometheus
Cc: DaveOHenry; Author
Betreff: Re: [prometheus/prometheus] Add computer name as meta label in azure_sd_config (#8499)


There is a rate-limiting issue with the azure SD. I am afraid we can't add more RPC calls here.

Do you know if that info would be available with our current RPC calls?

**Comment by roidelapluie** [comment]
We don't have that info but we expose the machine name. What is the difference?

**Comment by DaveOHenry** [comment]
Please see ```properties.osProfile.computerName``` at https://docs.microsoft.com/en-us/rest/api/compute/virtualmachinescalesetvms/list#virtualmachinescalesetvm for example.

> Specifies the host OS name of the virtual machine.
> 
> This name cannot be updated after the VM is created.
> 
> Max-length (Windows): 15 characters
> 
> Max-length (Linux): 64 characters.

The computerName therefore defines which name the host OS will use to register at the DNS server while the "machine name" has nothing to do with DNS at all.

**Comment by roidelapluie** [comment]
We have looked at this during our bug scrub. I think we don't have the info with the current way the SD is written but I would encourage azure users to try this and see if we can get that information without extra RPC calls.

**Comment by deesejohn** [comment]
I believe this value is exposed as `vm.VirtualMachineProperties.OsProfile.ComputerName` in:

https://github.com/prometheus/prometheus/blob/ea6f6bba74dec06dd7a439304d6187f3b193e112/discovery/azure/azure.go#L448-L473

If that is correct, then would the meta tag `__meta_azure_machine_properties_os_profile_computer_name` be appropriate or too verbose?

**Comment by darshanime** [comment]
@deesejohn I've raised a quick PR for this. Let me know if you were already working on this, happy to close fwiw 🙂
