### ISSUE TITLE
Implement custom headers in remote-read

### ISSUE THREAD

**Issue by Harkishen-Singh** [prometheus/prometheus#8503]
PR #8416 implements the ability to send custom headers in remote-write. This is very useful and helps implement a bunch of features on the remote-write storage side.

However, if we implement the headers support, it should be on the read side as well. This can have many use-cases and may help users to avoid using a proxy, which at times, complicates the arch.

**Comment by roidelapluie** [comment]
Let's do it, moving this away from the send to a new roundtripper.

**Comment by Harkishen-Singh** [comment]
I will take up this.

**Comment by Harkishen-Singh** [comment]
> to a new roundtripper.

Can you please clarify this? Do you mean to make changes in the prometheus/common repo and not here?
