### ISSUE TITLE
not cleaning up checkpoint tmp files 

### ISSUE THREAD

**Issue by fcddk** [prometheus/prometheus#8514]
**What did you do?**
When restarting prometheus, there are many useless tmp files that have been ignored and always exist.

**What did you expect to see?**
Prometheus automatically cleans up junk files 

**What did you see instead? Under which circumstances?**
     many tmp files
     `rw-r--r-- 1 nobody nogroup 121M Feb 18 14:46 00106268
-rw-r--r-- 1 nobody nogroup 123M Feb 18 14:49 00106269
-rw-r--r-- 1 nobody nogroup 121M Feb 18 14:51 00106270
-rw-r--r-- 1 nobody nogroup 110M Feb 18 14:53 00106271
drwxr-xr-x 2 nobody nogroup 4.0K Aug 14  2020 checkpoint.024541.tmp
drwxr-xr-x 2 nobody nogroup 4.0K Aug 15  2020 checkpoint.025061.tmp
drwxr-xr-x 2 nobody nogroup 4.0K Aug 15  2020 checkpoint.025450.tmp
drwxr-xr-x 2 nobody nogroup 4.0K Aug 16  2020 checkpoint.025567.tmp
drwxr-xr-x 2 nobody nogroup 4.0K Aug 17  2020 checkpoint.026366.tmp
drwxr-xr-x 2 nobody nogroup 4.0K Aug 18  2020 checkpoint.026978.tmp
drwxr-xr-x 2 nobody nogroup 4.0K Aug 18  2020 checkpoint.027046.tmp
drwxr-xr-x 2 nobody nogroup 4.0K Aug 19  2020 checkpoint.027500.tmp
drwxr-xr-x 2 nobody nogroup 4.0K Aug 20 13:03 checkpoint.027936.tmp
drwxr-xr-x 2 nobody nogroup 4.0K Aug 21 01:03 checkpoint.028196.tmp
drwxr-xr-x 2 nobody nogroup 4.0K Aug 21 07:03 checkpoint.028316.tmp
drwxr-xr-x 2 nobody nogroup 4.0K Aug 22 01:02 checkpoint.028723.tmp
drwxr-xr-x 2 nobody nogroup 4.0K Aug 22 03:10 checkpoint.028738.tmp
drwxr-xr-x 2 nobody nogroup 4.0K Aug 24 01:03 checkpoint.029770.tmp
drwxr-xr-x 2 nobody nogroup 4.0K Aug 24 07:03 checkpoint.029887.tmp
drwxr-xr-x 2 nobody nogroup 4.0K Aug 25 01:03 checkpoint.030288.tmp
drwxr-xr-x 2 nobody nogroup 4.0K Aug 26 13:03 checkpoint.031073.tmp
drwxr-xr-x 2 nobody nogroup 4.0K Aug 27 01:02 checkpoint.031331.tmp
drwxr-xr-x 2 nobody nogroup 4.0K Aug 28 03:03 checkpoint.031901.tmp
drwxr-xr-x 2 nobody nogroup 4.0K Aug 28 05:03 checkpoint.031916.tmp
drwxr-xr-x 2 nobody nogroup 4.0K Aug 28 11:09 checkpoint.032047.tmp
drwxr-xr-x 2 nobody nogroup 4.0K Aug 28 13:03 checkpoint.032060.tmp
drwxr-xr-x 2 nobody nogroup 4.0K Aug 28 15:03 checkpoint.032073.tmp
drwxr-xr-x 2 nobody nogroup 4.0K Aug 28 17:11 checkpoint.032087.tmp
drwxr-xr-x 2 nobody nogroup 4.0K Aug 28 19:11 checkpoint.032097.tmp
drwxr-xr-x 2 nobody nogroup 4.0K Aug 28 21:03 checkpoint.032109.tmp
drwxr-xr-x 2 nobody nogroup 4.0K Aug 28 23:04 checkpoint.032119.tmp
drwxr-xr-x 2 nobody nogroup 4.0K Aug 29 01:06 checkpoint.032131.tmp
drwxr-xr-x 2 nobody nogroup 4.0K Aug 29 03:06 checkpoint.032139.tmp
drwxr-xr-x 2 nobody nogroup 4.0K Aug 29 05:03 checkpoint.032151.tmp
drwxr-xr-x 2 nobody nogroup 4.0K Aug 29 07:03 checkpoint.032164.tmp
drwxr-xr-x 2 nobody nogroup 4.0K Aug 29 09:21 checkpoint.032177.tmp
drwxr-xr-x 2 nobody nogroup 4.0K Feb 18 13:04 checkpoint.106132
root@mgt07:/monitor/prometheus/wal# date
Thu Feb 18 14:55:10 CST 2021`

**Environment**

* System information:

	Linux 5.0.0-29-generic x86_64

* Prometheus version:

  prometheus, version 2.15.2 (branch: master, revision: e7e1a937a55f009e6fe9224c2ee5064abe85e769)
  build user:       root@master01
  build date:       20200415-01:14:21
  go version:       go1.13.8

* Logs:
```
  nothing
```

**Comment by fcddk** [comment]
tmp file:

-rw-r--r-- 1 nobody nogroup 121M Feb 18 14:46 00106268
-rw-r--r-- 1 nobody nogroup 123M Feb 18 14:49 00106269
-rw-r--r-- 1 nobody nogroup 121M Feb 18 14:51 00106270
-rw-r--r-- 1 nobody nogroup 110M Feb 18 14:53 00106271
drwxr-xr-x 2 nobody nogroup 4.0K Aug 14  2020 checkpoint.024541.tmp
drwxr-xr-x 2 nobody nogroup 4.0K Aug 15  2020 checkpoint.025061.tmp
drwxr-xr-x 2 nobody nogroup 4.0K Aug 15  2020 checkpoint.025450.tmp
drwxr-xr-x 2 nobody nogroup 4.0K Aug 16  2020 checkpoint.025567.tmp
drwxr-xr-x 2 nobody nogroup 4.0K Aug 17  2020 checkpoint.026366.tmp
drwxr-xr-x 2 nobody nogroup 4.0K Aug 18  2020 checkpoint.026978.tmp
drwxr-xr-x 2 nobody nogroup 4.0K Aug 18  2020 checkpoint.027046.tmp
drwxr-xr-x 2 nobody nogroup 4.0K Aug 19  2020 checkpoint.027500.tmp
drwxr-xr-x 2 nobody nogroup 4.0K Aug 20 13:03 checkpoint.027936.tmp
drwxr-xr-x 2 nobody nogroup 4.0K Aug 21 01:03 checkpoint.028196.tmp
drwxr-xr-x 2 nobody nogroup 4.0K Aug 21 07:03 checkpoint.028316.tmp
drwxr-xr-x 2 nobody nogroup 4.0K Aug 22 01:02 checkpoint.028723.tmp
drwxr-xr-x 2 nobody nogroup 4.0K Aug 22 03:10 checkpoint.028738.tmp
drwxr-xr-x 2 nobody nogroup 4.0K Aug 24 01:03 checkpoint.029770.tmp
drwxr-xr-x 2 nobody nogroup 4.0K Aug 24 07:03 checkpoint.029887.tmp
drwxr-xr-x 2 nobody nogroup 4.0K Aug 25 01:03 checkpoint.030288.tmp
drwxr-xr-x 2 nobody nogroup 4.0K Aug 26 13:03 checkpoint.031073.tmp
drwxr-xr-x 2 nobody nogroup 4.0K Aug 27 01:02 checkpoint.031331.tmp
drwxr-xr-x 2 nobody nogroup 4.0K Aug 28 03:03 checkpoint.031901.tmp
drwxr-xr-x 2 nobody nogroup 4.0K Aug 28 05:03 checkpoint.031916.tmp
drwxr-xr-x 2 nobody nogroup 4.0K Aug 28 11:09 checkpoint.032047.tmp
drwxr-xr-x 2 nobody nogroup 4.0K Aug 28 13:03 checkpoint.032060.tmp
drwxr-xr-x 2 nobody nogroup 4.0K Aug 28 15:03 checkpoint.032073.tmp
drwxr-xr-x 2 nobody nogroup 4.0K Aug 28 17:11 checkpoint.032087.tmp
drwxr-xr-x 2 nobody nogroup 4.0K Aug 28 19:11 checkpoint.032097.tmp
drwxr-xr-x 2 nobody nogroup 4.0K Aug 28 21:03 checkpoint.032109.tmp
drwxr-xr-x 2 nobody nogroup 4.0K Aug 28 23:04 checkpoint.032119.tmp
drwxr-xr-x 2 nobody nogroup 4.0K Aug 29 01:06 checkpoint.032131.tmp
drwxr-xr-x 2 nobody nogroup 4.0K Aug 29 03:06 checkpoint.032139.tmp
drwxr-xr-x 2 nobody nogroup 4.0K Aug 29 05:03 checkpoint.032151.tmp
drwxr-xr-x 2 nobody nogroup 4.0K Aug 29 07:03 checkpoint.032164.tmp
drwxr-xr-x 2 nobody nogroup 4.0K Aug 29 09:21 checkpoint.032177.tmp
drwxr-xr-x 2 nobody nogroup 4.0K Feb 18 13:04 checkpoint.106132
root@mgt07:/monitor/prometheus/wal# date
Thu Feb 18 14:55:10 CST 2021

**Comment by roidelapluie** [comment]
Thank you for this.a lot of bugs around this have been fixed lately. Could you try Prometheus 2.25.0 and see if the error appears again?

**Comment by roidelapluie** [comment]
We have looked at this during the bug scrub. Did you have any chance to upgrade?

Also, which filesystem are you using?
You can see that by the log line `fs_type=`, e.g. `level=info ts=2021-03-01T15:44:47.192Z caller=main.go:799 fs_type=EXT4_SUPER_MAGIC`.

**Comment by fcddk** [comment]
level=info ts=2021-03-05T08:31:38.866Z caller=main.go:684 fs_type=EXT4_SUPER_MAGIC

**Comment by roidelapluie** [comment]
Upgrading should get rid of those files, which were created in August.

**Comment by beorn7** [comment]
Hello from the bug scrub.

We are closing this, assuming that this particular issue has been fixed by the many releases we had in the meantime. If you still see similar problems, please file a new issue.
