### ISSUE TITLE
Client_golang update breaks `go get` for latest promtool

### ISSUE THREAD

**Issue by abangser** [prometheus/prometheus#8521]
**What did you do?**
I am trying to go get prom tool:
```
go get github.com/prometheus/prometheus/cmd/promtool
```

**What did you expect to see?**
I expected to see the package installed

**What did you see instead? Under which circumstances?**
```
/go/src/github.com/prometheus/prometheus/cmd/promtool/main.go:642:35: not enough arguments in call to api.LabelValues
	have (context.Context, string, time.Time, time.Time)
	want (context.Context, string, []string, time.Time, time.Time)

Exited with code exit status 2
```

I believe this is due to a change in the [client_golang package](https://github.com/prometheus/client_golang/commit/75d7516f2a100997f739a5bc520bf08bb44a2600#diff-9a3a8e3f0424115273d9a05e9b087ad13a7872995a962822be6975c287d3857c)

Work around if helpful for anyone:
```
GO111MODULE=on go get github.com/prometheus/prometheus/cmd/promtool@c2c5aeb16b9b3c7e2b6ce4a0ef03a213b8bcce21
```

**Environment**

* System information:

	insert output of `uname -srm` here: `Linux 4.19.121-linuxkit x86_64`

     (I am running `docker run --rm -it golang /bin/bash`)

* Prometheus version:

	insert output of `prometheus --version` here: `bash: prometheus: command not found`

* Alertmanager version:

	insert output of `alertmanager --version` here: `bash: alertmanager: command not found`

* Prometheus configuration file:
n/a

* Alertmanager configuration file:
n/a

* Logs:
n/a

**Comment by roidelapluie** [comment]
Hello, this is due to the fact that we have removed the vendor directory from prometheus,

The `workaround` you have found is not a workaround, it is the recommended way to compile promtool.

**Comment by abangser** [comment]
Thanks for the update. This is slightly confusing for me as I now need to pin releases but actually just want to follow along head. This will require more work to make sure I continue to pull in latest but of course is doable and automatable. Based on your response though it sounds like I should close this since it is working as intended?

**Comment by roidelapluie** [comment]
GO111MODULE=on go get github.com/prometheus/prometheus/cmd/promtool@master


will work too.

**Comment by abangser** [comment]
Ah fantastic. Thanks for that update. I definitely understand the risks of master and am happier dealing with those. Thank you for being so responsive!
