### ISSUE TITLE
Prometheus has renamed its default branch to main

### ISSUE THREAD

**Issue by roidelapluie** [prometheus/prometheus#8527]
Dear community,

In the coming days, we will rename the default branch of this repository from `master` to `main`.

At this point, it will be required to run, in your local prometheus repository:

```
$ git branch -m master main
$ git fetch origin
$ git branch -u origin/main main
```

Read more in the mailing list: https://groups.google.com/g/prometheus-developers/c/lsObDkitEoQ/m/TLMEMkV1AAAJ

**Comment by bwplotka** [comment]
Let's do it 👍🏽

**Comment by roidelapluie** [comment]
https://github.com/prometheus/circleci/pull/14

**Comment by roidelapluie** [comment]
The switch has been done.
