### ISSUE TITLE
Grafana losing all connectivity to Prometheus.

### ISSUE THREAD

**Issue by Choogster1** [prometheus/prometheus#8530]
**What did you do?**

Running a 4 node docker swarm cluster with prometheus/grafana installation for monitoring of the containers

**What did you expect to see?**

After logging into grafana after a week and checking my docker dashboard, I expected to see the dashboard working correctly

**What did you see instead? Under which circumstances?**

Grafana gave error messages for every variable saying  'Template variables could not be initialized: undefined'

**Environment**

Redhat 8

* System information:

Linux 4.18.0-240.10.1.el8_3.x86_64 x86_64

* Prometheus version:

v2.19.1

* Alertmanager version:

v0.21.0

The problem appears to be a whole load of .TMP folders appearing in the prometheus_data folder - I checked my other 4 node cluster running the same configuration, which is still working correctly and there are no .TMP folders.

If I shut down the cluster, delete all the files and folders in prometheus_data and then start the cluster again, I can import the JSON dashboard and it runs correctly for an unknown amount of time before the same happens again.

**Comment by roidelapluie** [comment]
We have fixed a few .tmp directories issues recently. Can you please confirm that you still see this bug if you update to the latest release?

Also, please tell us which filesystem/operating system you are using.

Thank you.

**Comment by Choogster1** [comment]
operating system was Redhat Enterprise 7. The other 4 node swarm cluster I've been running is Redhat Enterprise 7 which seems to be more stable. I was running exactly the same versions of Prometheus on both clusters but I'll try updating the containers to the newest version.

**Comment by roidelapluie** [comment]
What filesystem are you using? Can you paste us the logs of the Prometheus server start?

**Comment by Choogster1** [comment]
After running v2.25.0 I'm running into the same problem. It seems that prometheus is quitting for no particular reason. 

prom/prometheus:v2.25.0                       "/bin/prometheus --c…"   3 seconds ago   Created 
prom/prometheus:v2.25.0                       "/bin/prometheus --c…"   3 minutes ago   Exited (137) 4 seconds ago
prom/prometheus:v2.25.0                       "/bin/prometheus --c…"   5 minutes ago   Exited (137) 3 minutes ago
prom/prometheus:v2.25.0                       "/bin/prometheus --c…"   8 minutes ago   Exited (137) 5 minutes ago

Before it quits, the logs show with no further messages:

level=info ts=2021-02-26T06:05:03.795Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=51 maxSegment=1332
level=info ts=2021-02-26T06:05:03.872Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=52 maxSegment=1332
level=info ts=2021-02-26T06:05:03.898Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=53 maxSegment=1332
level=info ts=2021-02-26T06:05:03.968Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=54 maxSegment=1332
level=info ts=2021-02-26T06:05:04.269Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=55 maxSegment=1332

The .TMP folder problem has been solved however, but the errors appearing in Grafana haven't thus far.

**Comment by roidelapluie** [comment]
Thanks for the logs. It seems that at some point your wal got corrupted/checkpoints were not created.  Having 1000 segments in the wal is not normal. Do you have any clue about what happened?

The way forward is to delete (or move) your data/wal directory.

**Comment by roidelapluie** [comment]
Cc @codesome

**Comment by Choogster1** [comment]
> Thanks for the logs. It seems that at some point your wal got corrupted/checkpoints were not created. Having 1000 segments in the wal is not normal. Do you have any clue about what happened?
> 
> The way forward is to delete (or move) your data/wal directory.

I have absolutely no idea what happened. The error even appeared once when I was watching the grafana screen, one minute the dashboard was fine, the next minute it was full of red error messages.

**Comment by roidelapluie** [comment]
Which kind of filesystem are you using? You can see that in the `fs_type` log line, e.g. `level=info ts=2021-03-01T16:06:30.639Z caller=main.go:799 fs_type=EXT4_SUPER_MAGIC`.
This is not a known bug with Prometheus 2.25 so far.

Can you please also provide the full logs, with the reason of the exit ? Is it killed by the OOM-Killer (you can see that by running `dmesg`)?

Thanks again!

**Comment by Choogster1** [comment]
I refreshed the deployment again yesterday and today grafana is giving a screenfull of errors again, and I noticed Prometheus has quit multiple times.  There is nothing in the log mentioning fs_type. Only OS type  host_details="(Linux 4.18.0-240.15.1.el8_3.x86_64 #1 SMP Wed Feb 3 03:12:15 EST 2021 x86_64 e7633e4dd973 (none))

The log only shows the following, there is no reason for the exit included. The last line of this section is the last line of the log.

level=info ts=2021-03-02T04:46:59.000Z caller=head.go:668 component=tsdb msg="Replaying on-disk memory mappable chunks if any"
level=info ts=2021-03-02T04:47:00.089Z caller=head.go:682 component=tsdb msg="On-disk memory mappable chunks replay completed" duration=1.088803849s
level=info ts=2021-03-02T04:47:00.089Z caller=head.go:688 component=tsdb msg="Replaying WAL, this may take a while"
level=info ts=2021-03-02T04:47:37.466Z caller=head.go:714 component=tsdb msg="WAL checkpoint loaded"
level=info ts=2021-03-02T04:48:10.969Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=2 maxSegment=299
level=info ts=2021-03-02T04:48:11.464Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=3 maxSegment=299
level=info ts=2021-03-02T04:48:12.764Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=4 maxSegment=299
level=info ts=2021-03-02T04:48:14.071Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=5 maxSegment=299
level=info ts=2021-03-02T04:48:15.973Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=6 maxSegment=299
level=info ts=2021-03-02T04:48:17.266Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=7 maxSegment=299
level=info ts=2021-03-02T04:49:20.963Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=8 maxSegment=299
level=info ts=2021-03-02T04:49:21.466Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=9 maxSegment=299
level=info ts=2021-03-02T04:49:21.968Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=10 maxSegment=299
level=info ts=2021-03-02T04:49:22.561Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=11 maxSegment=299
level=info ts=2021-03-02T04:49:24.263Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=12 maxSegment=299
level=info ts=2021-03-02T04:49:24.690Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=13 maxSegment=299
level=info ts=2021-03-02T04:49:25.274Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=14 maxSegment=299
level=info ts=2021-03-02T04:49:25.275Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=15 maxSegment=299
level=info ts=2021-03-02T04:49:25.589Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=16 maxSegment=299
level=info ts=2021-03-02T04:49:25.978Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=17 maxSegment=299
level=info ts=2021-03-02T04:49:26.364Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=18 maxSegment=299
level=info ts=2021-03-02T04:49:26.574Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=19 maxSegment=299
level=info ts=2021-03-02T04:49:26.969Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=20 maxSegment=299
level=info ts=2021-03-02T04:49:26.971Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=21 maxSegment=299
level=info ts=2021-03-02T04:49:27.065Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=22 maxSegment=299
level=info ts=2021-03-02T04:49:27.068Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=23 maxSegment=299
level=info ts=2021-03-02T04:49:28.272Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=24 maxSegment=299
level=info ts=2021-03-02T04:49:28.474Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=25 maxSegment=299
level=info ts=2021-03-02T04:49:28.673Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=26 maxSegment=299
level=info ts=2021-03-02T04:49:28.762Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=27 maxSegment=299
level=info ts=2021-03-02T04:49:28.969Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=28 maxSegment=299
level=info ts=2021-03-02T04:49:29.362Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=29 maxSegment=299
level=info ts=2021-03-02T04:49:29.674Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=30 maxSegment=299
level=info ts=2021-03-02T04:49:30.095Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=31 maxSegment=299
level=info ts=2021-03-02T04:49:30.099Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=32 maxSegment=299
level=info ts=2021-03-02T04:49:33.786Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=33 maxSegment=299
level=info ts=2021-03-02T04:49:36.488Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=34 maxSegment=299
level=info ts=2021-03-02T04:49:39.795Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=35 maxSegment=299
level=info ts=2021-03-02T04:49:39.985Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=36 maxSegment=299
level=info ts=2021-03-02T04:49:40.866Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=37 maxSegment=299
level=info ts=2021-03-02T04:49:41.663Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=38 maxSegment=299
level=info ts=2021-03-02T04:49:41.786Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=39 maxSegment=299
level=info ts=2021-03-02T04:49:41.969Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=40 maxSegment=299
level=info ts=2021-03-02T04:49:42.782Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=41 maxSegment=299
level=info ts=2021-03-02T04:49:42.881Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=42 maxSegment=299
level=info ts=2021-03-02T04:49:43.884Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=43 maxSegment=299
level=info ts=2021-03-02T04:49:44.172Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=44 maxSegment=299
level=info ts=2021-03-02T04:49:44.468Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=45 maxSegment=299
level=info ts=2021-03-02T04:49:44.688Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=46 maxSegment=299
level=info ts=2021-03-02T04:49:45.385Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=47 maxSegment=299
level=info ts=2021-03-02T04:49:45.587Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=48 maxSegment=299
level=info ts=2021-03-02T04:49:46.361Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=49 maxSegment=299
level=info ts=2021-03-02T04:49:46.493Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=50 maxSegment=299
level=info ts=2021-03-02T04:49:46.798Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=51 maxSegment=299
level=info ts=2021-03-02T04:49:47.097Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=52 maxSegment=299
level=info ts=2021-03-02T04:49:48.688Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=53 maxSegment=299
level=info ts=2021-03-02T04:49:48.870Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=54 maxSegment=299
level=info ts=2021-03-02T04:49:48.982Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=55 maxSegment=299
level=info ts=2021-03-02T04:49:49.261Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=56 maxSegment=299
level=info ts=2021-03-02T04:49:49.665Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=57 maxSegment=299
level=info ts=2021-03-02T04:49:50.783Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=58 maxSegment=299
level=info ts=2021-03-02T04:49:51.090Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=59 maxSegment=299
level=info ts=2021-03-02T04:49:51.281Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=60 maxSegment=299
level=info ts=2021-03-02T04:49:51.392Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=61 maxSegment=299
level=info ts=2021-03-02T04:49:51.572Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=62 maxSegment=299
level=info ts=2021-03-02T04:49:51.681Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=63 maxSegment=299
level=info ts=2021-03-02T04:49:51.891Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=64 maxSegment=299
level=info ts=2021-03-02T04:49:52.071Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=65 maxSegment=299
level=info ts=2021-03-02T04:49:52.193Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=66 maxSegment=299
level=info ts=2021-03-02T04:49:52.565Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=67 maxSegment=299
level=info ts=2021-03-02T04:49:52.685Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=68 maxSegment=299
level=info ts=2021-03-02T04:49:52.889Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=69 maxSegment=299
level=info ts=2021-03-02T04:49:52.999Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=70 maxSegment=299
level=info ts=2021-03-02T04:49:53.279Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=71 maxSegment=299
level=info ts=2021-03-02T04:49:53.571Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=72 maxSegment=299
level=info ts=2021-03-02T04:49:53.679Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=73 maxSegment=299
level=info ts=2021-03-02T04:49:53.893Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=74 maxSegment=299
level=info ts=2021-03-02T04:49:54.180Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=75 maxSegment=299
level=info ts=2021-03-02T04:49:54.295Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=76 maxSegment=299
level=info ts=2021-03-02T04:49:54.391Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=77 maxSegment=299
level=info ts=2021-03-02T04:49:54.508Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=78 maxSegment=299
level=info ts=2021-03-02T04:49:54.683Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=79 maxSegment=299
level=info ts=2021-03-02T04:49:54.788Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=80 maxSegment=299
level=info ts=2021-03-02T04:49:54.969Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=81 maxSegment=299
level=info ts=2021-03-02T04:49:55.076Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=82 maxSegment=299
level=info ts=2021-03-02T04:49:55.208Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=83 maxSegment=299
level=info ts=2021-03-02T04:49:55.371Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=84 maxSegment=299
level=info ts=2021-03-02T04:49:55.579Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=85 maxSegment=299
level=info ts=2021-03-02T04:49:55.684Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=86 maxSegment=299
level=info ts=2021-03-02T04:49:55.872Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=87 maxSegment=299
level=info ts=2021-03-02T04:49:56.686Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=88 maxSegment=299
level=info ts=2021-03-02T04:49:56.794Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=89 maxSegment=299
level=info ts=2021-03-02T04:49:56.897Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=90 maxSegment=299
level=info ts=2021-03-02T04:49:57.064Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=91 maxSegment=299
level=info ts=2021-03-02T04:49:57.198Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=92 maxSegment=299
level=info ts=2021-03-02T04:49:57.485Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=93 maxSegment=299
level=info ts=2021-03-02T04:49:57.592Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=94 maxSegment=299
level=info ts=2021-03-02T04:49:57.776Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=95 maxSegment=299
level=info ts=2021-03-02T04:49:57.894Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=96 maxSegment=299
level=info ts=2021-03-02T04:50:00.578Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=97 maxSegment=299
level=info ts=2021-03-02T04:50:00.769Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=98 maxSegment=299
level=info ts=2021-03-02T04:50:00.979Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=99 maxSegment=299
level=info ts=2021-03-02T04:50:01.109Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=100 maxSegment=299
level=info ts=2021-03-02T04:50:01.271Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=101 maxSegment=299
level=info ts=2021-03-02T04:50:01.393Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=102 maxSegment=299
level=info ts=2021-03-02T04:50:01.510Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=103 maxSegment=299
level=info ts=2021-03-02T04:50:01.597Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=104 maxSegment=299

**Comment by roidelapluie** [comment]
Do you have the looks of the previous run?

**Comment by Choogster1** [comment]
> Do you have the looks of the previous run?

They're the same as this. It ends on a maxSegment= line, no termination message

**Comment by roidelapluie** [comment]
Something prevents prometheus to checkpoints and it is unclear what. Maybe the logs of the first run after the cleanup would help.

**Comment by Choogster1** [comment]
Ah. I found this after refresh in the log, which could have a bearing on it. 

fs_type=NFS_SUPER_MAGIC msg="This filesystem is not supported and may lead to data corruption and data loss. Please carefully read https://prometheus.io/docs/prometheus/latest/storage/ to learn more about supported filesystems.

**Comment by roidelapluie** [comment]
Okay, as stated in the error message, we do not support NFS. The kind of errors you are seeing are common with NFS.

I'd recommend to use a local posix-compliant filesystem instead.

**Comment by roidelapluie** [comment]
Based on my last reply, I am going to close this issue.

If you have more questions about this, please reach the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users).

Thanks!!
