### ISSUE TITLE
[tsdb] Support ingesting data out of order

### ISSUE THREAD

**Issue by gouthamve** [prometheus/prometheus#8534]
## Proposal

Prometheus now supports remote-write and I can see people using Prometheus for some push based use-cases. I am not yet sure we want to make Prometheus a full push based system. Having said that, there are other downstream projects like Thanos and Cortex which use TSDB and want to support out of order ingest for various use-cases. 

We are working on adding more protocols in front of Cortex (for ex, https://github.com/grafana/influx2cortex) to enable more usecases and also to help people migrate from other TSDBs to Prometheus based systems. But for these use-cases we need to have out of order ingests.

We should have support for that in TSDB core rather than Thanos and Cortex hacking a layer on top of TSDB. We could enable it in Prometheus too if needed. I briefly raised this in the storage working group, and there is broad consensus. We should find a good way to do this without blowing up the resource requirements.

**Comment by codesome** [comment]
Closing in favour of https://github.com/prometheus/prometheus/issues/8535
