### ISSUE TITLE
Can't clean database

### ISSUE THREAD

**Issue by UAnton** [prometheus/prometheus#8541]
**What did you do?**

curl -X POST -g 'http://localhost:9090/api/v1/admin/tsdb/delete_series?match[]={__name__=~".+"}'
curl -X POST -g 'http://localhost:9090/api/v1/admin/tsdb/clean_tombstones'

**What did you expect to see?**

Clean database

**What did you see instead? Under which circumstances?**

Nothing happens

**Environment**

* System information:

	Linux 5.4.0-65-generic x86_64

* Prometheus version:

  prometheus, version 2.25.0 (branch: HEAD, revision: a6be548dbc17780d562a39c0e4bd0bd4c00ad6e2)
  build user:       root@615f028225c9
  build date:       20210217-14:17:24
  go version:       go1.15.8
  platform:         linux/amd64
* Alertmanager version:

  alertmanager, version 0.21.0 (branch: HEAD, revision: 4c6c03ebfe21009c546e4d1e9b92c371d67c021d)
  build user:       root@dee35927357f
  build date:       20200617-08:54:02
  go version:       go1.14.4

* Logs:
```
Nothing in logs
```

**Comment by roidelapluie** [comment]
Can you please provide more details? What does curl respond? Do you still see old metrics?

**Comment by UAnton** [comment]
> Can you please provide more details? What does curl respond? Do you still see old metrics?

Curl response is empty. All old metrics are present.

**Comment by roidelapluie** [comment]
curl response should not be empty. can you paste the output of the `curl -v` commands?

**Comment by UAnton** [comment]
> curl response should not be empty. can you paste the output of the `curl -v` commands?

```
root@prometheus-w:/home/az# curl -v -X POST -g 'http://localhost:9090/api/v1/admin/tsdb/delete_series?match[]={__name__=~".+"}'
*   Trying 127.0.0.1:9090...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 9090 (#0)
> POST /api/v1/admin/tsdb/delete_series?match[]={__name__=~".+"} HTTP/1.1
> Host: localhost:9090
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 204 No Content
< Date: Thu, 25 Feb 2021 22:18:20 GMT
< 
* Connection #0 to host localhost left intact
```
Maybe the curl query is wrong?

**Comment by roidelapluie** [comment]
Do you still see metrics values? What makes you think the database is not empty?

**Comment by UAnton** [comment]
Because I see all metrics for the last 30 days

**Comment by roidelapluie** [comment]
Thanks, I can reproduce this.

**Comment by roidelapluie** [comment]
Workaround: curl -X POST -g 'http://localhost:9090/api/v1/admin/tsdb/delete_series?match[]={nonexistent=""}'

**Comment by roidelapluie** [comment]
I see 2 issues here:

1. Maybe it's a bug we should address
2. Maybe it is a safeguard we have, in which case we probably should return 400 to the caller.

**Comment by UAnton** [comment]
Metrics still present
```
root@prometheus-w:/home/az# curl -v -X POST -g 'http://localhost:9090/api/v1/admin/tsdb/delete_series?match[]={nonexistent=""}'
*   Trying 127.0.0.1:9090...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 9090 (#0)
> POST /api/v1/admin/tsdb/delete_series?match[]={nonexistent=""} HTTP/1.1
> Host: localhost:9090
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 204 No Content
< Date: Thu, 25 Feb 2021 22:39:11 GMT
< 
* Connection #0 to host localhost left intact
```

**Comment by roidelapluie** [comment]
The {nonexistent=""} trick definitevely works in my test env..

**Comment by UAnton** [comment]
Works after a service restart. Thanks!
