### ISSUE TITLE
react ui: gracefully handle restarts

### ISSUE THREAD

**Issue by roidelapluie** [prometheus/prometheus#8550]
When we restart Prometheus, we have this during the WAL replay:

![unr](https://user-images.githubusercontent.com/291750/109498251-8419da00-7a93-11eb-8066-f43de737d1b3.png)

Previous UI was just showing '503 not available' message.

I think we could have something better, a nice "landing page" like what Jenkins has, which would refresh when Prometheus is ready:

<img width="404" alt="exportjenkins" src="https://user-images.githubusercontent.com/291750/109498524-d824be80-7a93-11eb-8cd8-927f91ed9158.png">

cc @juliusv  WDYT?

**Comment by juliusv** [comment]
Yep, definitely makes sense. I might get to this at some point, but happy to take contributions as well.

**Comment by roidelapluie** [comment]
The idea would be to use the /-/ready endpoint.

**Comment by anubhav21sharma** [comment]
Would it make sense to also show the progress of WAL replay or mmap chunks replay in the UI while it's happening?

**Comment by juliusv** [comment]
> Would it make sense to also show the progress of WAL replay or mmap chunks replay in the UI while it's happening?

That would be cool. It would require more work of course. You would have to add code to the TSDB to expose that initial loading state, and then make it available via the HTTP API to the web app somehow. But generally, I'm for such features from a user's POV.

**Comment by LeviHarrison** [comment]
I think we could just write messages like this to an array, and hook it up to an endpoint like `/api/v1/walreplay` (or maybe even `/-/walreplay`, not sure if this would constitute as a management endpoint). Then fetch that endpoint every 1-2 seconds on the startup screen until `/-/ready` is true.

https://github.com/prometheus/prometheus/blob/b3feb2c2aed8cd27f69613985ad7ddcab2cb1e6c/tsdb/head.go#L768

**Comment by roidelapluie** [comment]
This is pretty structured data, I would prefer to return the numbers so that we can have a progressbar or so.

**Comment by LeviHarrison** [comment]
How about having something like this:

```go
type Response struct {
  Read    int // i
  Total   int // last - startFrom
}
```

https://github.com/prometheus/prometheus/blob/b3feb2c2aed8cd27f69613985ad7ddcab2cb1e6c/tsdb/head.go#L754

**Comment by roidelapluie** [comment]
We probably also want the startFrom exposed as First, and the total should probably be called Last.

**Comment by LeviHarrison** [comment]
Ok, will do! And should this be a management endpoint or just a regular API one?

**Comment by roidelapluie** [comment]
This is a regular API endpoint. Note that there might be some time before we even start replaying the wal that we would need t handle as well.

**Comment by LeviHarrison** [comment]
So you're saying that we should add other indications of activity?

**Comment by roidelapluie** [comment]
> So you're saying that we should add other indications of activity?

Somehow I just want to make sure that you know we can spend up to a few seconds before we actually replay the wal. I think  we can zero all the wall replay info during that moment.

**Comment by LeviHarrison** [comment]
This can be closed

**Comment by juliusv** [comment]
Thanks!
