### ISSUE TITLE
Issue found by Svace static analyzer 

### ISSUE THREAD

**Issue by vvdvortsova** [prometheus/prometheus#8554]
Hello
This warning found with the Svace. 

It may cause unforeseen problems.
https://github.com/prometheus/prometheus/blob/77e648534e2f716cc3cf090eadf009d4c37d0dbf/scrape/scrape.go#L508
Usage of variable l is found in goroutine while its value may be changed by one of outer loops before this goroutine's execution (race condition).
https://github.com/prometheus/prometheus/blob/77e648534e2f716cc3cf090eadf009d4c37d0dbf/scrape/scrape.go#L510

**Comment by roidelapluie** [comment]
I don't think this is an issue in practice because that variable is local and we don't have other pull requests which could change it.

We could rewrite it as `go func(sl scrapeLoop) { sl.run(interval, timeout, nil)  }(l)` but i don't know if that brings any benefit.

**Comment by vvdvortsova** [comment]
By adding **l** as a parameter to the closure, **l** is evaluated at each iteration and placed on the stack for the goroutine, so each **uniqueLoops** element is available to the goroutine when it is eventually executed.

```bash
for _, l := range uniqueLoops {
		if l != nil {
			go func(lp loop) {
				lp.run(interval, timeout, nil)
			} (l)
		}
	}
```
May I contribute to fix this issue with a pull request?

**Comment by roidelapluie** [comment]
yes

**Comment by roidelapluie** [comment]
Before we can put the function to the go routine stack, we must know l, so I am not sure that this is an actual bug ? we would not go to the next iteration of the loop before getting the function in the stack?

**Comment by roidelapluie** [comment]
https://play.golang.org/p/yz_ifHC-Hut -> does not seem to cause issues

**Comment by vvdvortsova** [comment]
The for loop might not do what you expect because their **l** variable is actually a single variable that takes on the value of each **uniqueLoops** element. Because the closures are all only bound to that one variable, there is a very good chance that when you run this code you will see the last element printed for every iteration instead of each value in sequence, because the goroutines will probably not begin executing until after the loop.

**Comment by roidelapluie** [comment]
I have asked this question in golang-nuts and got a reply: https://groups.google.com/g/golang-nuts/c/2vZ0IBm3Q18

The provider answer, which I invite you to read, points at https://golang.org/ref/spec#Go_statements

> The function value and parameters are evaluated as usual in the calling goroutine, but unlike with a regular call, program execution does not wait for the invoked function to complete. 

As the function value is evaluated in the calling go routing, I expect this to just work as expected, and to be a false positive of your static analyzer.

**Comment by beorn7** [comment]
I agree with @roidelapluie here. What your static analyzer should flag is something like this:

```Go
	for _, l := range uniqueLoops {
		if l != nil {
			go func(){
				l.run(interval, timeout, nil)
			}()
		}
	}
```

However, we never access `l` from the goroutine that is started here. On the contrary, we are retrieving the method to call from `l` and _then_ start it as a goroutine.

**Comment by vvdvortsova** [comment]
> I have asked this question in golang-nuts and got a reply: https://groups.google.com/g/golang-nuts/c/2vZ0IBm3Q18
> 
> The provider answer, which I invite you to read, points at https://golang.org/ref/spec#Go_statements
> 
> > The **function value** and parameters **are evaluated as usual in the calling goroutine**, but unlike with a regular call, program execution does not wait for the invoked function to complete.
> 
> As the function value is evaluated in the calling go routine, I expect this to just work as expected, and to be a false positive of your static analyzer.

You are right. I agree with you. I misunderstood. Sorry. It's FP. On your case we'll fix it.
