### ISSUE TITLE
A bug which may cause series data points duplicate 

### ISSUE THREAD

**Issue by wangzhao765** [prometheus/prometheus#8558]
We found that series returned by API /api/v1/query may sometimes have duplicate data points. 

After carefully reading the code, we think that https://github.com/prometheus/prometheus/blob/main/storage/merge.go#L469  should be the root cause.

In the function func (c *chainSampleIterator) Seek(t int64) bool, after poping the current point from the heap, the last timestamp don't refresh. So if the seek timestamp is duplicate and then we run the function next(), the iterator will return the duplicate data point with the same timestamp as the seek timestamp.

Please help to confirm this issue, thanks a lot.

**Comment by roidelapluie** [comment]
cc @bwplotka can you have a look at this one?

**Comment by roidelapluie** [comment]
Let's bring more storage people to the discussion: @codesome did you see this ?

**Comment by juliusv** [comment]
I am not a specialist in that piece of code anymore, but it seems like a plausible explanation, and I just managed to reproduce the problem in a new test case. Turns out, nobody actually wrote a test to test this prominent feature of that iterator (skipping over duplicate samples) yet :)

**Comment by juliusv** [comment]
Will send a PR.

**Comment by juliusv** [comment]
https://github.com/prometheus/prometheus/pull/8591

**Comment by wangzhao765** [comment]
Really thank you for your works. @roidelapluie @juliusv
