### ISSUE TITLE
Support additional formats for offset and time range

### ISSUE THREAD

**Issue by pbasetty** [prometheus/prometheus#8562]
Currently offset values can only be specified in single units (2h, 75m, 10s, etc). Would like to request support for multi unit values such as 1h15m, etc.

The same applies for time-range values, for example, would like support for increase(up[1h15m])

**Background**
When a user query is pre-processed using Prometheus query parsing library, these fields are parsed into "time.Duration" and printed back in the multi-unit format. So 75m becomes 1h15m.

**Comment by roidelapluie** [comment]
This is supported as of Prometheus 2.21.
