### ISSUE TITLE
Using the HTTP query_range API, the start,end parameters are changed when passed to remote storage

### ISSUE THREAD

**Issue by iwctwbai** [prometheus/prometheus#8578]
**What did you do?**
I use post to request /api/v1/query_range the start / end parameter passed to the remote storage in range will be changed

For the start parameter, the time becomes start-300 seconds

For the end parameter, it changes over time

I think the problem may have been before Prometheus was delivered to remote storage（/promql/engine.go，func (ng *Engine) execEvalStmt(ctx context.Context, query *query, s *parser.EvalStmt)）

**What did you expect to see?**
Same time as delivery in remote storage adapter

**What did you see instead? Under which circumstances?**

**Environment**

* System information:

Darwin 19.6.0 x86_64

* Prometheus version:

	insert output of `prometheus --version` here
v2.25.0

* Alertmanager version:

	insert output of `alertmanager --version` here (if relevant to the issue)

* Prometheus configuration file:
```
insert configuration here
```

* Alertmanager configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```

**Comment by roidelapluie** [comment]
Thank you for raising this issue.

This works as expected, the -300 seconds are the lookback delta. Prometheus will look for sample up to "loopback delta" in the past to look for the samples. Once that toopback delta is over, a metric is marked as "stale" and no longer taken into consideration for the current query.

**Comment by iwctwbai** [comment]
> 对于结束参数，您可以更明确些吗？您是否为查询指定了实际的结束时间参数？

 @roidelapluie Yes, I have specified the actual start and end time
If I specify a specific time, will the result also be affected by loopback Delta?
My request is like this
```
curl --location --request POST 'http://localhost:9081/api/v1/query_range' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'query=ifHCOutOctets' \
--data-urlencode 'start=2021-03-10T00:00:00+08:00' \
--data-urlencode 'end=2021-03-10T23:59:59+08:00' \
--data-urlencode 'step=5m' \
--data-urlencode 'timeout=5m'
```

**Comment by iwctwbai** [comment]
@roidelapluie 
It's an incredible question

My exporter has been working all day. At the same time yesterday, I specified start = the first minute of the day and end = the last minute of the day. Prometheus would deliver the query request to the remote storage adapter. But at the moment I query today's (query yesterday's data request can be delivered at the moment) request will not be delivered to the remote storage adapter

Do I need to provide more information? Please let me know if you need to.
Thank you!

**Comment by iwctwbai** [comment]
@roidelapluie 
Everything works fine after I set "read_recent: true".
I think there might be some bugs here.
Also, how can the start parameter of the remote storage adapter be consistent with the start parameter passed by the HTTP API? (The end parameter is now the same as the HTTP API after setting "read_recent: true ").
Do I need to provide more information? Please let me know if you need to.

**Comment by roidelapluie** [comment]
It can not be consistent, this works as designed. We need to have access to the samples 300s before the query.

**Comment by iwctwbai** [comment]
@roidelapluie 
I understand
If you do not set the "read_recent: true" parameter, the problem that will change dynamically is a bug. Do you need any information to help you troubleshoot this problem

**Comment by roidelapluie** [comment]
It is not a bug, we not not want to read the recent data by default. As I said, remote read is meant to read data that was previously sent by prometheus to a remote. Because we have still the data in the local prometheus server, we do not ask for this data twice.

It seems that overall you are trying to use remote read in a way that we do not support. It is fine, but calling our behaviour a bug is not correct :)

**Comment by iwctwbai** [comment]
No offense

According to your saying, "remote read is mean to read data that was previously sent by Prometheus to a remote", but for example, if I query the data of 0-24 hours today, there is no problem not through remote storage, but the HTTP API does not return any data. Does this mean that the local database of Prometheus does not work properly? Because only through the local database, we should also query the data

**Comment by roidelapluie** [comment]
I think that you are confused about the Prometheus data model.

To  get data into its local database, Prometheus is scraping targets. It means it will get metrics from HTTP apis, which are exposing metrics. We fetch the data at regular intervals. This is configured under `scrape_configs`.
e.g. if you go to https://prometheus.demo.do.prometheus.io/metrics you will see the metrics of a prometheus server.


Remote read is not used for ingesting data. It is used when Prometheus is sending the data it has ingested via the /metrics endpoints of the targets to an external storage, like cortex, or thanos. The process of sending the data to a LTS storage is called `remote_write`.
Those services are specialized into storing the data long term. Then, you can use remote read to get the data out of those storage. But those storage should not be your primary source of metrics, the metrics should come from the scrapes.

**Comment by iwctwbai** [comment]
@roidelapluie 
Thank you very much. Could you please kindly tell me the principle of changing the parameter of end time

**Comment by roidelapluie** [comment]
I'd encourage you to join the [prometheus-developers mailing list](https://groups.google.com/forum/#!forum/prometheus-developers) if you have further questions. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
