### ISSUE TITLE
Web UI: TSDB Configuration - Blank Page

### ISSUE THREAD

**Issue by Sebi2020** [prometheus/prometheus#8596]
**What did you do?**
I tried to open the TSDB Status in the status menu (New UI)

**What did you expect to see?**
Status information about TSDB

**What did you see instead? Under which circumstances?**

A blank white page.

**Environment**
- Docker (prom/prometheus image)
- Traefik (with SSL Termination)
- Chrome Browser (latest)
- Windows 10 (Browser environment)

**System information**
    - prom/prometheus Docker image on x64

**Prometheus version**
```
prometheus, version 2.25.0 (branch: HEAD, revision: a6be548dbc17780d562a39c0e4bd0bd4c00ad6e2)
  build user:       root@615f028225c9
  build date:       20210217-14:17:24
  go version:       go1.15.8
  platform:         linux/amd64
````

* Prometheus configuration file:
```
empty
```

**Comment by roidelapluie** [comment]
Can you please share your requests/responses (from the developers tools)? And look for errors in the javascript console? Thanks!

cc @juliusv FYI

**Comment by Sebi2020** [comment]
This only happens with new Prometheus instances that have not created any time series yet

**Comment by roidelapluie** [comment]
Oh, so it is not really a bug, is it ? If we have no time series, we have to tsdb, we have no stats.

**Comment by Sebi2020** [comment]
I think it's a bug because if there is nothing the web ui should display something like "No TSDB stats available yet" or something equal. But you get a blank page (not even a navigation bar is shown).

**Comment by roidelapluie** [comment]
Thanks, I will mark as a bug (must have nav page, should have a message)
