### ISSUE TITLE
promtool: Support some kind of “lint” for rules

### ISSUE THREAD

**Issue by dgl** [prometheus/prometheus#8613]
`promtool check rules` currently is [documented](https://prometheus.io/docs/prometheus/latest/configuration/recording_rules/#syntax-checking-rules) as a way to syntax check rules. However it also checks for duplicate rules, which is closer to a lint check.

There are some features in PromQL that are potentially problematic to use in recording rules now:
- Negative offset is likely incorrect in recording rules (I mentioned some kind of lint [then](https://github.com/prometheus/prometheus/issues/6282#issuecomment-550308545))
- Subqueries are often not a good idea (noted on the [blog post](https://prometheus.io/blog/2019/01/28/subquery-support/))

I propose something like a `--lint` flag where the default is “duplicate-rules” to match current behaviour, but could also accept `--lint=all`, etc. 

(Some overlap with #8607)

**Comment by Harkishen-Singh** [comment]
This was planned was part of #7779 but that's inactive at the moment for the reviewing process. If we can resume work there, then I can extend the pretty process as described here.

**Comment by roidelapluie** [comment]
This sounds like a good idea.
