### ISSUE TITLE
Per rule evaluation duration metric

### ISSUE THREAD

**Issue by gouthamve** [prometheus/prometheus#8618]
## Proposal

Currently we provide metrics (duration and success) at a rule-group level. But a group can have 10s of rules inside it. If a rule_group is skipping iterations, then its likely caused by a few rules inside the group. Today, we can easily find the culprit rules by looking at the UI.

Having said that, we are seeing some groups slowly creeping up in evaluation duration and knowing the historical evaluation duration for each rule would be quite helpful. This would basically be adding `prometheus_rule_group_rule_last_duration_seconds` which has an index of the rule being evaluated as a label.

A workaround to this is to write an exporter which queries the API and exposes the metrics, but I'd like to avoid that if possible.

**Comment by roidelapluie** [comment]
This seems like something for the query_log > loki.

A label with the rule ID would just be too much cardinality here. As you say, you can have 10s of rules inside a group.

Note that you would probably not need to write an exporter, you could simply use the json_exporter.

**Comment by roidelapluie** [comment]
This seems really expansive in terms of metrics we are exposing. It sounds like events. This looks like something that can be extracted from the query log or the traces we have in PromQL.

**Comment by skpenpen** [comment]
Interrested for keep track of rules duration evalution and alert on it

**Comment by beorn7** [comment]
Hello from the bug scrub.

Nothing has happened here in almost 3y. We are closing it, but if anyone has concrete plans of working on this (and an idea how to make it efficient enough), please follow up so that we can reopen.
