### ISSUE TITLE
Improve handling of Basic Credentials in the web UI

### ISSUE THREAD

**Issue by bluecmd** [prometheus/prometheus#862]
For targets using basic credentials:
1) 0.14 used to construct and display a URL with embedded credentials in it. This disappeared in 0.15rc0.
Expected behavior: The link should be generated with something like <a href="https://username:password@host:1234/metrics">https://host:1234/metrics</a>. Note the suggestion to not display the credentials but only embed them.

2) It would be nice if the credentials were masked in the configuration dump in the UI.

**Comment by bluecmd** [comment]
Ping @fabxc

**Comment by fabxc** [comment]
1) Is already/still how it works. Chrome doesn't show the credentials in the bottom-left corner on hovering but they are in the actual `href` tag.

2) Is solved in #876

**Comment by bluecmd** [comment]
1) Ah, so it is. My bad.

2) Neat!

**Comment by juliusv** [comment]
Looks like this is solved now, closing. Reopen please if you're still missing something :)
