### ISSUE TITLE
prometheus.io is down

### ISSUE THREAD

**Issue by appleciderjack** [prometheus/prometheus#8647]
Checked with downfor.io

Hope it comes back online soon!
Thanks

<img width="1440" alt="Screen Shot 2021-03-25 at 9 45 19 AM" src="https://user-images.githubusercontent.com/66964580/112511129-5735ab80-8d4f-11eb-9604-1304e08c03cf.png">
<img width="1367" alt="Screen Shot 2021-03-25 at 9 48 00 AM" src="https://user-images.githubusercontent.com/66964580/112511145-5ac93280-8d4f-11eb-942b-24c658cd5cd1.png">

**Comment by metalmatze** [comment]
Netlify is having problems and it should resolve itself once they are back to normal operation:
https://www.netlifystatus.com/

**Comment by roidelapluie** [comment]
This is hosted by netlify. You can check their status at https://www.netlifystatus.com/

I will close this issue as it does not seem to be on us.
