### ISSUE TITLE
Document exemplars

### ISSUE THREAD

**Issue by roidelapluie** [prometheus/prometheus#8648]
The exemplars feature is under-documented.
I would appreciate documentation in the release-2.26 branch, notably how to enable them (add to the `disable feature page`).

cc @cstyan

**Comment by cstyan** [comment]
It's documented in the `enable-feature` flag but I can add it to that docs page as well.

**Comment by roidelapluie** [comment]
We made the feature flag a lot shorter unfortunately because it was unreadable, and it points to the disabled features page.Sorry about that, I did not realize it was not documented on the page.
