### ISSUE TITLE
Wrong CHANGELOG link in release notifications

### ISSUE THREAD

**Issue by liguozhong** [prometheus/prometheus#8650]
![image](https://user-images.githubusercontent.com/9583245/112572725-bcf46700-8e25-11eb-8f95-4cfe33e0a0f1.png)

**Comment by liguozhong** [comment]
@bwplotka 

[FEATURE] Scaleway Discovery: Add Scaleway Service Discovery. #8555
[FEATURE] PromQL: Allow negative offsets. Behind --enable-feature=promql-negative-offset flag. #8555

**Comment by roidelapluie** [comment]
Thank you, I have fixed the issue in README and in the release page.
