### ISSUE TITLE
React UI: graph does from 8w to 1y

### ISSUE THREAD

**Issue by roidelapluie** [prometheus/prometheus#8652]
When we click on "+" here: https://prometheus.demo.do.prometheus.io/graph?g0.expr=&g0.tab=0&g0.stacked=0&g0.range_input=8w

The duration jumps from 8 weeks to 1 year.

It looks like we could have more jumps in-between, e.g 16 weeks.

**Comment by LeviHarrison** [comment]
Maybe `8w => 26w => 1y` or even `8w => 16y => 26w => 1y`?

**Comment by roidelapluie** [comment]
I don't know which logic to follow but I oomed by prometheus over this :)

**Comment by LeviHarrison** [comment]
Not exactly sure what "oomed" means 🤣, but I'll go ahead and open a PR :)

**Comment by ArthurSens** [comment]
OOM kill = Out Of Memory kill.

Maybe because querying 1y was too much 🙂
