### ISSUE TITLE
Experimental editor does not wrap

### ISSUE THREAD

**Issue by roidelapluie** [prometheus/prometheus#8663]
I opened a rule in the graph expression and started expanding it for debugging.

It turns out the input became wider and wider, to the point where the page itself expanded.

I think the behavior should be to wrap the queries.

![wrap](https://user-images.githubusercontent.com/291750/112820282-c24fec80-9085-11eb-95d6-54174112a7b2.png)

cc @Nexucis @juliusv @bwplotka

**Comment by roidelapluie** [comment]
This is the classic editor:
![wrap2](https://user-images.githubusercontent.com/291750/112820650-19ee5800-9086-11eb-9fe0-8815900b50e8.png)

**Comment by roidelapluie** [comment]
Note: this is not the actual query I used to test 🤣

**Comment by juliusv** [comment]
Haha! Luckily we already know how to add wrapping (I didn't want it in PromLens though (maybe I should?)) :) Will send a PR.

**Comment by Nexucis** [comment]
oh you definitely should @juliusv :D. try PromLens on a small laptop (like 11") you will be annoyed quite quickly

**Comment by Nexucis** [comment]
but if you don't want to wrap it @juliusv, the other way to do it is to force the editor to have a fixed width, so it can pop up an horizontal scroll bar.

**Comment by roidelapluie** [comment]
My preference is to wrap.

**Comment by Nexucis** [comment]
oh yeah me too. horizontal scroll bar is annoying as well after using it multiple time. But well when you are talking about responsive issue, you don't have so many way to solve it. Or use an horizontal bar, or wrap the text.

Wondering if you can use a combination of both actually.

Note that I was more talking for PromLens.

**Comment by juliusv** [comment]
Yeah, I'll look into wrapping. It won't be possible for the tree view though :) Anyway, not Prometheus-specific.

**Comment by roidelapluie** [comment]
fixed by #8665
