### ISSUE TITLE
Maintaining free range markers on the the default port allocations page

### ISSUE THREAD

**Issue by tsibley** [prometheus/prometheus#8668]
:wave: I noticed the [default port allocations](https://github.com/prometheus/prometheus/wiki/Default-port-allocations) wiki page was missing some markers for free ranges, so I [wrote a little program](https://gist.github.com/tsibley/8a705ba15fef4bc03d833f424419237b) to keep them up-to-date (mostly so I could myself easily see what ranges were free :-). I don't know if there's any interest in making this an automated part of the maintenance of that page (e.g. with GH Actions). I can't submit a PR to the wiki repo, so I'm creating this issue FWIW. Thanks for Prometheus!

**Comment by roidelapluie** [comment]
Thank you for this. The default port allocation page is mainly community maintained, and the format is quite fragile. I am unsure we should "automate" it in its current form.

I have added this topic to the discussion topic we have at our montly public developers summits: https://prometheus.io/community to see if we need have a better solution than a wiki page.

**Comment by SuperQ** [comment]
Yes, we didn't imagine needing thousands of individual port allocations when we first created the page. :joy_cat:

**Comment by beorn7** [comment]
Hello from the bug scrub.

On 2021-12-16, the dev summit discussed the ports wiki page. Result was the following consensus: "We will keep it as is, and re-assess the situation in roughly three months."

This is now 2.5y ago. We believe no re-assessment has happened. Maybe the current state is in some way "good enough". It certainly seems we shouldn't create automation on top of this somewhat fragile and grassroots approach, see comment above.
