### ISSUE TITLE
Storage becomes inconsistent

### ISSUE THREAD

**Issue by beorn7** [prometheus/prometheus#867]
Occasionally, the Prometheus server logs "Dropped more chunks from persistence than 
from memory for fingerprint 7202cb21fd049080 [...]".
Storage is then inconsistent, a restart with crash recovery is required.

In the crash recovery, the affected fingerprint often doesn't require a recovery, so the file actually is consistent.

The problem happens often enough to rule out an actual data corruption. It's likely some kind of programming bug.

**Comment by beorn7** [comment]
Looks I have nailed it in https://github.com/prometheus/prometheus/pull/880 .

**Comment by juliusv** [comment]
Awesome!
