### ISSUE TITLE
remote_write discovery functionality.

### ISSUE THREAD

**Issue by hdost** [prometheus/prometheus#8673]
## Proposal
**Use case. Why is this important?**
Similar to https://prometheus.io/docs/prometheus/latest/configuration/configuration/#alertmanager_config
the use of remote_write resources being available via consul has (to me obvious advantages)

**Comment by roidelapluie** [comment]
We would need to discuss between this and #8402

**Comment by hdost** [comment]
Indeed this seems a duplicate, will close and have conversation there.
