### ISSUE TITLE
Customize through the flags the configuration of the new PromQL editor

### ISSUE THREAD

**Issue by Nexucis** [prometheus/prometheus#8685]
the lib `codemirror-promql` has different parameters that defines:
*  the amount of time to consider when retrieving the metric. By default the interval is 12h. So currently when the new PromQL editor is autocompleting the metric, it is retrieving the metric existing since 12h.
* the maximum number of metrics in Prometheus for which metadata is fetched. If the number of metrics exceeds this limit, no metric metadata is fetched at all.
By default the limite is 10k.

## Proposal
It would be interesting to customize these default values using some flags like `--web.editor.lookbackInterval=12h` and `--web.editor.maxMetricsMetadata=10000`

Like that we can decrease or increase these limits depending of the size of the Prometheus we are running

**Comment by Nexucis** [comment]
and I forgot also there is a LRU cache embedded into the lib where there is a maxAge which is the maximum amount of time that a cached completion item is valid before it needs to be refreshed. By default it's 5min

Maybe for this one, it's not really important, but I guess it won't hurt if it's possible to change as well it's default value.

**Comment by Nexucis** [comment]
aaand if Thanos is going to integrate the new PromQL editor, maybe it would be interesting to have these flags as well in Thanos.

**Comment by roidelapluie** [comment]
I don't have an opinion here.

cc @juliusv

**Comment by roidelapluie** [comment]
@juliusv ping, do you think it is worth the overhead?

**Comment by juliusv** [comment]
No opinion either, really. Happy to let someone add configurability when they actually require it, I would say. Another option could be to add those options into the web UI, but then hide the increasingly large number of UI settings behind a settings menu, instead of having them all at the top.

**Comment by Nexucis** [comment]
It will be interesting behind this issue to create a new package in `web/ui/module` that contains the code of [CMExpressionInput](https://github.com/prometheus/prometheus/blob/e5b1b15dc3ad11c18de97e600fd5fb84ca69076b/web/ui/react-app/src/pages/graph/CMExpressionInput.tsx).

Like that it can be used by PromLens, Perses, Thanos ...etc. That will help to provide a common way to enter the PromQL query + the configuration of codemirror-promql

**Comment by Nexucis** [comment]
WDYT @juliusv ?

**Comment by juliusv** [comment]
@Nexucis The input in PromLens is already totally different than in Prometheus in the way it executes things (since it doesn't actually evaluate the query but tries to parse it into a tree via the backend), so at least for that use case it wouldn't help me much. Maybe it's helpful for others though. IMO it should be motivated by a concrete use case. For the case of Thanos/Cortex, I guess the reusability would be more interesting on a higher level (showing the entire expression browser, maybe more).

**Comment by Nexucis** [comment]
I was proposing to do that because on Thanos side they would like to add more configuration around codemirror-promql. See https://github.com/thanos-io/thanos/issues/4685

So to avoid to do the work twice, I was thinking to export the CMExpression. But perhaps yeah it would be more interesting to export it on a higher level.

I was also thinking about Perses with a potential metric explorer. I think having a react component around codemirror-promql would help to commonize the way to use it across Prometheus/Thanos/Perses. Cortex I don't know if they are using it anyway.

**Comment by beorn7** [comment]
Hello from the bug scrub.

@Nexucis this hasn't seen updates in a while. Is it still relevant?

**Comment by Nexucis** [comment]
Hello,

I think we can close this issue, the configuration of the PromQL editor is enough like that in Prometheus at least. For other project that depends on it, then if they want to configure it, it's always possible but it will depend on their decisions.
