### ISSUE TITLE
rate() function giving spurious peak

### ISSUE THREAD

**Issue by apeksharma** [prometheus/prometheus#8687]
**What did you do?**
Plotting graph of a metric (say M) and the rate of that metric.

**What did you expect to see?**
No deviation in normal graph of rate(M)

**What did you see instead? Under which circumstances?**
Unexpected spike in the graph

![image](https://user-images.githubusercontent.com/4148936/113478185-e015bb00-94a4-11eb-9b2a-43321e1e0b2e.png)

Data points for that duration
![image](https://user-images.githubusercontent.com/4148936/113478250-53b7c800-94a5-11eb-8ed0-4a95fa804c5e.png)

**Environment**

* System information:

Don't have access to the system. Can get it if needed.

* Prometheus version:

	2.18.1
	
![image](https://user-images.githubusercontent.com/4148936/113478265-8235a300-94a5-11eb-827d-0002d94f8c4c.png)

* Alertmanager version:

NA

* Prometheus configuration file:
Don't have access to the system. Can get it if needed.

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```

**Comment by roidelapluie** [comment]
You probably have resets.

Can you please provide the raw metrics?

to do that, run `mymetric{label="a"}[3h]` in the "console" tabs.

**Comment by apeksharma** [comment]
Thanks Julien for responding.

PFA raw metrics. 
Also, adding graphs from the exact same duration for easy correlation.
![image](https://user-images.githubusercontent.com/4148936/113503133-7bfb0180-954d-11eb-8f31-8ea8e58dd900.png)
[raw_metrics.txt](https://github.com/prometheus/prometheus/files/6254176/raw_metrics.txt)

**Comment by roidelapluie** [comment]
You have a counter reset:

439 @1617442554.304
439 @1617442554.315
440 @1617442564.304
439 @1617442564.315
440 @1617442574.33
440 @1617442584.297

**Comment by roidelapluie** [comment]
It might be a bug in prometheus. Why is that scraped twice at the same time?

Can you are more about your configuration?

**Comment by apeksharma** [comment]
cc: @sanjeevpandey19: Sanjeev, would you be able to help with above questions?

**Comment by vsliouniaev** [comment]
Reminds me a bit of this issue: https://github.com/prometheus/prometheus/issues/6894

**Comment by roidelapluie** [comment]
I totally agree and I digged multiple times in the codebase without finding the bug yet...

**Comment by apeksharma** [comment]
I see. Can close this in favor of earlier one then.
Thanks Julien and Vasily

**Comment by roidelapluie** [comment]
Can you still provide the requested info please?

**Comment by sanjeevpandey19** [comment]
> Can you still provide the requested info please?

@roidelapluie what sort of specific information you need here.

Do you want to know if we have setup using operator or vanila Prometheus or you would need Prometheus.yaml itself  ?

**Comment by roidelapluie** [comment]
I'd like the prometheus.yml to see the relabeling rules and the jobs, if possible.

**Comment by dhruvp-8** [comment]
@roidelapluie any update on this issue we are also facing the issue in Prometheus 2.25.0 where in the rate() function has unexpected spikes in the data

**Comment by amey24kulkarni** [comment]
Team, Is there any update on this issue.. We're also facing similar issue. But with increase() function
