### ISSUE TITLE
CHANGELOG: hyperlink PRs

### ISSUE THREAD

**Issue by conorevans** [prometheus/prometheus#8689]
## Proposal

I find the Prometheus CHANGELOG to be quite unfriendly - hyperlinking the PRs would make things a lot nicer, imo.

Happy to do this once given the go-ahead, so assign to me if you're happy for me to do this. Thanks

**Comment by roidelapluie** [comment]
Sounds like a good idea to me. Thanks!

**Comment by beorn7** [comment]
As said in the PR, I think this is a bad idea. It also affects all repos and should be decided collectively.
