### ISSUE TITLE
Path for rule files is not relative to configuration

### ISSUE THREAD

**Issue by TheTincho** [prometheus/prometheus#869]
Hi,

Just a small detail: if one uses a relative path to include rules, it is not resolved from the directory where the main configuration is, which would seem to me like the most obvious.

THanks.

**Comment by juliusv** [comment]
:+1: makes sense to change this.

**Comment by fabxc** [comment]
Yes, breaking though.

**Comment by juliusv** [comment]
Yup.

**Comment by fabxc** [comment]
Was fixed in #874

**Comment by TheTincho** [comment]
Thanks!
