### ISSUE TITLE
As a third party, I can't validate the Rule using the package rulefmt

### ISSUE THREAD

**Issue by Nexucis** [prometheus/prometheus#8694]
Hello,

Through the PR #6533, the package `rulefmt` doesn't expose anymore a way to validate a single rule when using the struct `Rule`.

Before it was possible and useful. Because when you are wrapping the `Rule` in a third component that would like to expose this struct before deploying it into Prometheus, then it was possible to ensure that the `Rule` is valid in the Prometheus terme.

I know it's been a while the API changed for this package, but well PromQL didn't change so much before v2.25 and v2.26, so I didn't have to update the Prometheus dependencies :D.

I understand why the changes were performed, and I don't have so good idea so far, to provide the method `Validate` for the struct `Rule` that follows more or less the same code than the method Validate for the struct `RuleNode` (Same applies for the struct `RuleGroup` of course)

Anyway, is it something possible on your side to provide back the same API ?

**Comment by roidelapluie** [comment]
cc @cyriltovena I think loki uses this code. Is @Nexucis missing something, or do you need this too?

**Comment by Nexucis** [comment]
on my side I ended up by created the yaml struct expected in a `[]byte` and then use `rulefmt.Parse`

Like that for example: https://github.com/perses/perses/blob/20b812ac88d7436d415a728be746f8efe8908d31/internal/api/impl/v1/prometheusrule/service.go#L30-L41

**Comment by Nexucis** [comment]
so if there is a more elegant solution, that would be so cool !

**Comment by cyriltovena** [comment]
@roidelapluie Loki uses its own group rule loader. We have also validation done here https://github.com/grafana/cortex-tools/blob/main/pkg/rules/parser.go#L35 but I don't think we uses `rulefmt`.

**Comment by skpenpen** [comment]
`
go.mod 
github.com/prometheus/prometheus v1.8.2-0.20200724121523-657ba532e42f

rule.go
import "github.com/prometheus/prometheus/pkg/rulefmt"

**some for
                                        var a rulefmt.RuleNode

					err = yaml.Unmarshal(ajson, &a)
					if err != nil {
						log.Errorln(rule.Rule, ":", err)
					}

					errs := a.Validate()
					if errs != nil || len(errs) > 0 {
						for _, err := range errs {
							log.Errorln("Error in rule", group, rule.Rule, ":", err)
						}
						continue
					}
`

**Comment by beorn7** [comment]
Hello from the bug scrub.

@Nexucis this hasn't seen updates in a while. Is it still relevant?

**Comment by Nexucis** [comment]
from my side we can close this issue. The workaround I shared is fine
