### ISSUE TITLE
msg="Error sending alert" err="bad response status 404 Not Found"

### ISSUE THREAD

**Issue by luigisainini** [prometheus/prometheus#8696]
Deploying a monitoring stack with prom\prometheus:latest and prom/alertmanager:v0.12.0 i received the error:

`prometheus_1         | level=error ts=2021-04-06T14:58:25.808Z caller=notifier.go:527 component=notifier alertmanager=http://alertmanager:9093/api/v2/alerts count=1 msg="Error sending alert" err="bad response status 404 Not Found"`

I expected to have no problem with the latest version. I tried some problem solving curl command retrieving:
`curl http://alertmanager:9093/`   -------- > WAS OK

`curl http://alertmanager:9093/api/v2/alerts`  ------ > 404 status

even if everything was up and responding on 9093 and path_prefix was correctly configured.

So i used prom/prometheus:v2.25.1 instead latest and everything was fixed.

**Environment**
Linux 5.4.0-1037-aws x86_64

* Prometheus version:
latest

* Alertmanager version:
prom/alertmanager:v0.12.0

* Logs:
```
prometheus_1         | level=error ts=2021-04-06T14:58:25.808Z caller=notifier.go:527 component=notifier alertmanager=http://alertmanager:9093/api/v2/alerts count=1 msg="Error sending alert" err="bad response status 404 Not Found"
prometheus_1         | level=error ts=2021-04-06T14:58:40.807Z caller=notifier.go:527 component=notifier alertmanager=http://alertmanager:9093/api/v2/alerts count=1 msg="Error sending alert" err="bad response status 404 Not Found"

```

**Comment by roidelapluie** [comment]
Hello,

Prometheus 2.26 has switched to alertmanager API v2 as announced in the release notes of 2.25 and 2.26. That API was release 2 years ago.

You version of Alertmanager is very old. You could update alertmanager or set `api_version` to `v1` in your prometheus configuration:
https://prometheus.io/docs/prometheus/latest/configuration/configuration/#alertmanager_config
