### ISSUE TITLE
Metric "up" may miss when error in scrape

### ISSUE THREAD

**Issue by wangzhao765** [prometheus/prometheus#8702]
Prometheus version: 2.19.2
We found that if the scrape returns an error "upstream connect error or disconnect/reset before headers. reset reason: connection termination", the metric "up" will miss the data point (instead of a value of 0 or 1). However, scrape_duration_seconds and scrape_samples_scraped keep normal.

**Comment by roidelapluie** [comment]
Thank you for your issue. The logic for this has changed in Prometheus 2.20. Can you please try to reproduce with a higher version and provide us more data to better understand what is going on?

**Comment by psvmcc** [comment]
Hi, I see similar issue with version 2.26.0 with dns-sd discovery, one of targets in down state on targets page, with error:
```
Get "http://1.2.3.4:9100/metrics": dial tcp 1.2.3.4:9100: connect: connection refused
```

And on same time query `up` returns 1 for this target, when it should return 0.

**Comment by roidelapluie** [comment]
@wangzhao765 Can you please try with a higher version and report back? Thank you!

**Comment by beorn7** [comment]
Hello from the bug scrub.

Closing for lack of follow up in 3y.
