### ISSUE TITLE
Instrument Exemplar Storage and Scraping

### ISSUE THREAD

**Issue by bwplotka** [prometheus/prometheus#8707]
It would be amazing to know more about what is happening with exemplars in Promethus based on metrics.

AC:
* Prometheus exposes metrics on:
   *  how many exemplars were scraped
   * how many we hold in queue
   *  the oldest exemplar in queue etc 
   
   
cc @cstyan   (Unless I missed something and we have those already - could not find though)

**Comment by bwplotka** [comment]
Fixing attempt: https://github.com/prometheus/prometheus/pull/8712

**Comment by clux** [comment]
Just spotted this issue. Does this mean that scraping of exemplars currently does not work?

**Comment by roidelapluie** [comment]
It means that we could have more metrics to get more insights, but yes examplars do work in Prometheus 2.26.
