### ISSUE TITLE
Possible duplicate out of order exemplars metrics

### ISSUE THREAD

**Issue by yeya24** [prometheus/prometheus#8708]
**What did you do?**
I am looking at the existing exemplar metrics.

```
➜  prometheus git:(main) ✗ promlinter list . --add-help | grep exemplar
COUNTER             prometheus_target_scrapes_exemplar_out_of_order_total        Total number of exemplar rejected due to not being out of the expected order.
COUNTER             prometheus_tsdb_exemplar_out_of_order_exemplars_total        Total number of out of order exemplar ingestion failed attempts
COUNTER             prometheus_tsdb_out_of_order_exemplars_total                 Total number of out of order exemplars ingestion failed attempts.
```

I found that [prometheus_tsdb_exemplar_out_of_order_exemplars_total](https://github.com/prometheus/prometheus/blob/289ba11b79a4ddc02a5566f6344dd33533dfeb2f/tsdb/exemplar.go#L61) and [prometheus_tsdb_out_of_order_exemplars_total](https://github.com/prometheus/prometheus/blob/c7a62b95cea098b677a958bf4e20084bc427aad5/tsdb/head.go#L226) are almost the same. It is not very clear what's the difference between the two. 

If they are duplicates, it would be good to only keep one. If they are not, it would be good to update the help text or metric name to make it more clear.

* Prometheus version:

	latest main

**Comment by roidelapluie** [comment]
Thank you for your report.

cc @cstyan

**Comment by bwplotka** [comment]
Found confusing too, fixing attempt: https://github.com/prometheus/prometheus/pull/8712
