### ISSUE TITLE
VMWare Discovery

### ISSUE THREAD

**Issue by RyanW8** [prometheus/prometheus#8717]
## Proposal
**Use case. Why is this important?**

We would like to monitor all ESXI hosts and also all virtual machines in a VMWare vCenter environment; however since VMs and ESXI hosts are so dynamic (they come and go super often) it seems silly to define them statically. 

We could use `dns_sd_configs` however that doesn't seem right as there would be no distinction between ESXI hosts for example and VMs.

If prometheus had VMWare discovery built in that scraped a vCenter for targets then that woiuld be awesome

**Comment by SuperQ** [comment]
There are a vmware file_sd config generator that could be used as a basis for implementing this.

https://github.com/AppliedTrust/vmware-filesd

**Comment by LeviHarrison** [comment]
https://github.com/vmware/govmomi/blob/master/examples/virtualmachines/main.go is be the Go equivalent of this, and adding in https://pkg.go.dev/github.com/vmware/govmomi@v0.25.0/vapi/tags#Manager.ListAttachedTags would allow you to get the tags.

**Comment by mohag** [comment]
> There are a vmware file_sd config generator that could be used as a basis for implementing this.
> 
> https://github.com/AppliedTrust/vmware-filesd

That one is gone now, any idea where it can easily be found again?

(Implementing custom SD stuff as "web" servers that can be scraped by http_sd might make sense)
