### ISSUE TITLE
Proposal: Move `storage.tsdb.retention.size` out of experimental mode.

### ISSUE THREAD

**Issue by bwplotka** [prometheus/prometheus#8728]
Hi All, 

I would propose to move our retention by size flag out of the experimental stage. Do we know any major issues that we have seen so far with this feature?

I know the issue of users trying to limit the size of WAL itself, which I don't think works now. Anything else that could block adding stability guarantees to this?

Ref: https://github.com/prometheus/prometheus/blob/main/cmd/prometheus/main.go#L261

**Comment by roidelapluie** [comment]
LGTM.

**Comment by roidelapluie** [comment]
It seems we have passed the lazy consensus timeout.

**Comment by PhilipGough** [comment]
What is the process for moving something out of experimental? Is it essentially just a docs update?

**Comment by goelankitt** [comment]
Can I pick this up as a first contribution?

**Comment by roidelapluie** [comment]
Yes. It is a doc update, which also touches code. We also need to review the docs since I think now WAL size is properly computed.
