### ISSUE TITLE
Include apk tools in Prometheus docker container so I can install update-ca-certificates

### ISSUE THREAD

**Issue by ncook-hxgn** [prometheus/prometheus#8735]
## Proposal
I need to be able to add self-signed certificates to prom/prometheus so that I can get metrics from a server behind https with a self signed certificate.

This is currently difficult because
1) apk is not installed, which doesn't help with 2)
2) update-ca-certificates is not installed

Generally I would add certificates to the /usr/share/ca-certificates/extra/ directory and then run update-ca-certificates, but I can't do this. (for reference: https://hackernoon.com/alpine-docker-image-with-secured-communication-ssl-tls-go-restful-api-128eb6b54f1f)

Please either include apk in your prom/prometheus image (so that I can install certificate mgmt software), or provide the image with update-ca-certificates preinstalled.

Thanks

**Comment by roidelapluie** [comment]
We plan to *remove things* from the docker image, not adding things. In your case, it seems like you could just add the ca somewhere and point to the single ca with the ca_file parameter.

**Comment by ncook-hxgn** [comment]
I did not know there was a ca_file parameter.. I assume I can set that in the container startup somewhere, would you be so kind as to link me to some docs on ca_file parameter? I've been using Prometheus only a day or so, I don't know where anything is..

**Comment by ncook-hxgn** [comment]
I mean, having docs doesn't help with using prom/prometheus as a base image as described in the prometheus docs 2nd page, [here](https://prometheus.io/docs/prometheus/latest/installation/#custom-image), where it is hard to customise without package management.

**Comment by ncook-hxgn** [comment]
> I did not know there was a ca_file parameter.. I assume I can set that in the container startup somewhere, would you be so kind as to link me to some docs on ca_file parameter? I've been using Prometheus only a day or so, I don't know where anything is..

I found the tls_config -docs- snippet [here].

OK. 

Awesome. I just made it insecure_skip_verify - even easier. Nice!
