### ISSUE TITLE
Feedback on kubectl plugin to dump data blocks

### ISSUE THREAD

**Issue by ihcsim** [prometheus/prometheus#8753]
I am hoping to get a sense of whether the community will be interested in a
kubectl plugin that I wrote, that can be used to dump the Prometheus TSDB 
head and persistent blocks, where the persistent blocks can be filtered by time
range. If there is enough interest, I have some specific questions about the
correctness of my implementation.

Link to repo: https://github.com/ihcsim/promdump

(Apologies if this isn't the right forum. After looking through the [community
page](https://prometheus.io/community/), it feels like GH might be the place for this.)

## Use case - Why is this important?

Often when debugging Kubernetes clusters with restrictive access, I find it
helpful to get access to the in-cluster Prometheus metrics. To reduce the
amount of back-and-forth with the users (due to missing metrics, incorrect
labels etc.), it makes sense for me to ask the users to "get me everything
around the time of the incident".

The most common way to achieve this is to use commands like `kubectl exec` 
and `kubectl cp` to compress and dump Prometheus' entire data directory. On
non-trivial clusters, the resulting compressed file can be very large. To import 
the data into a local test instance, I will need at least the same amount of disk 
space.

promdump is a tool that can be used to dump Prometheus data blocks. It is
different from the `promtool tsdb dump` command in such a way that its output
can be re-used in another Prometheus instance. See #8281  for a discussion on
the limitation on the output of `promtool tsdb dump`. And unlike the Promethues
TSDB `snapshot` API, promdump doesn't require Prometheus to be started with the
`--web.enable-admin-api` option. Instead of dumping the entire TSDB, promdump
offers the flexibility to filter persistent blocks by time range.

## How it works

The promdump CLI is implemented as a kubectl plugin. It downloads the
`promdump-$(VERSION).tar.gz` file from a public storage bucket to your local
`/tmp` folder. It then uploads the decompressed `promdump` binary to the
targeted Prometheus container, via the pod's `exec` subresource.

Within the Prometheus container, promdump queries the Prometheus TSDB using 
the [`tsdb`](https://pkg.go.dev/github.com/prometheus/prometheus/tsdb) package.  It reads and streams the WAL files, head block and persistent 
blocks to stdout, which can be redirected to a file on your local file system. To regulate 
the size of the dump, persistent blocks can be filtered by time range.

When the data dump is completed, the promdump binary will be automatically
deleted from your Prometheus container.

The `restore` subcommand can then be used to copy this dump file to another
Prometheus container. When this container is restarted, it will reconstruct its
in-memory index and chunks using the restored on-disk memory-mapped chunks 
and WAL.

## What it looks like

```sh
# check the tsdb metadata
$ kubectl promdump meta --context=$CONTEXT -p $POD_NAME
Head Block Metadata
------------------------
Minimum time (UTC): | 2021-04-18 18:00:03
Maximum time (UTC): | 2021-04-18 20:34:48
Number of series    | 18453

Persistent Blocks Metadata
----------------------------
Minimum time (UTC):     | 2021-04-15 03:19:10
Maximum time (UTC):     | 2021-04-18 18:00:00
Total number of blocks  | 9
Total number of samples | 92561234
Total number of series  | 181304
Total size              | 139272005

# capture the data dump
$ TARFILE="dump-`date +%s`.tar.gz"
$ kubectl promdump \
  --context "${CONTEXT}" \
  -p "${POD_NAME}" \
  --min-time "2021-04-15 03:19:10" \
  --max-time "2021-04-18 20:34:48"  > "${TARFILE}"

# restore the data dump found at ${TARFILE}
$ kubectl promdump restore \
  --context="${CONTEXT}" \
  -p "${POD_NAME}" \
  -t "${TARFILE}"
```

## Existing issues

AFAICT, there are any existing issues for this. The two that come close are
#8280 and #8281.

**Comment by roidelapluie** [comment]
Thank you for this.

cc @brancz @bwplotka @simonpasquier

**Comment by Harkishen-Singh** [comment]
This looks cool. Thank you for this.

**Comment by ihcsim** [comment]
Thanks for the interest so far! @bwplotka mentioned that the only part that is
tricky is dumping the WAL files, but the current approach should still work -
even with Thanos! So far, I have been testing with data directory of up to
about 5GB. If anyone else would like to try it out, I am more than happy to
help set you up.

Meanwhile, I have submitted https://github.com/kubernetes-sigs/krew-index/pull/1259 to make this an
official kubectl plugin.

My final question is whether it will benefit the community if the source is moved
to github.com/prometheus-community, and if this is something that can be added
to `promtool`.

**Comment by ihcsim** [comment]
I am closing this issue. The tool has been added to the kubectl krew repo. Feel free
to raise any issues, feedback etc. in the repo. If the community wants to help improve
and maintain it, I will be willing to transfer the source to 
github.com/prometheus-community. Thanks!

**Comment by roidelapluie** [comment]
We would be happy to list it on the website too: https://github.com/prometheus/docs

**Comment by ihcsim** [comment]
@roidelapluie Love the idea! Any suggestion on which section? Is there a particular spot for community tools?

**Comment by roidelapluie** [comment]
https://prometheus.io/docs/operating/integrations/

Probably under "Other"
