### ISSUE TITLE
support aliyun ecs scrape

### ISSUE THREAD

**Issue by xibei316** [prometheus/prometheus#8758]
we have many aliyun_ecs instance and hope they are monitored.

https://www.alibabacloud.com/product/ecs?spm=a3c0i.267727.6791778070.dnavproductelastic1.376a5258DZMQe1

**Comment by KeyOfSpectator** [comment]
@roidelapluie 
Hi~ We are alibaba aliyun team, we have a aliyun ecs discovery implement.
https://github.com/AliyunContainerService/prometheus/tree/master/discovery/ecs
Can we take a merge-request of our commit to master branch?

- pressure test: this implement support pressure test with 1K+ ECS, and every ECS have 20 tags, support frequency ECS scale scenario. 
- support filter with ECS label.
- use scrolling API to discovery ecs to support frequency ECS scale change scenario.

**Comment by beorn7** [comment]
Hello from the bug scrub.

Sorry for the delay here. It looks like #11931 is an overarching issue including this one. We'll close this and continue the discussion over there in #11931.
