### ISSUE TITLE
Prometheus v2.26.0 go panic frequently

### ISSUE THREAD

**Issue by haowells** [prometheus/prometheus#8762]
**What did you do?**
I use version v2.26.0 to start up a prometheus pod in k8s cluster

**What did you expect to see?**
I expect prometheus pod can keep running and generate blocks in path specified in storage.tsdb.path

**What did you see instead? Under which circumstances?**
pod keep crash due to same golang panic,  paste logs below

**Environment**

* System information:
```
-bash-4.2# uname -srm
Linux 5.4.0-59.generic.x86_64 x86_64
```
* Prometheus version:
```
/prometheus # /bin/prometheus --version
prometheus, version 2.26.0 (branch: HEAD, revision: 3cafc58827d1ebd1a67749f88be4218f0bab3d8d)
  build user:       root@a67cafebe6d0
  build date:       20210331-11:56:23
  go version:       go1.16.2
  platform:         linux/amd64
```
* Alertmanager version:

* Prometheus configuration file:

* Alertmanager configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:

```
level=info ts=2021-04-26T23:19:42.966Z caller=main.go:767 msg="Server is ready to receive web requests."
panic: snappy: decoded block is too large

goroutine 145955 [running]:
github.com/golang/snappy.Encode(0xc590980000, 0x5e2c9b, 0x5e2c9b, 0x10383c34000, 0xdd77491e, 0xe0728000, 0xb38ebffd, 0xe0728000, 0x18)
	/go/pkg/mod/github.com/golang/snappy@v0.0.3/encode.go:22 +0x2d7
github.com/prometheus/prometheus/tsdb/wal.(*WAL).log(0xc0002ce2d0, 0x10383c34000, 0xdd77491e, 0xe0728000, 0x6aa201, 0xe1daa76b08, 0xfb1e619de0)
	/app/tsdb/wal/wal.go:624 +0x52d
github.com/prometheus/prometheus/tsdb/wal.(*WAL).Log(0xc0002ce2d0, 0xddb4723618, 0x1, 0x1, 0x0, 0x0)
	/app/tsdb/wal/wal.go:596 +0xed
github.com/prometheus/prometheus/tsdb.(*headAppender).log(0xe0778280b0, 0x0, 0x0)
	/app/tsdb/head.go:1368 +0x34a
github.com/prometheus/prometheus/tsdb.(*headAppender).Commit(0xe0778280b0, 0x0, 0x0)
	/app/tsdb/head.go:1388 +0x9e
github.com/prometheus/prometheus/tsdb.dbAppender.Commit(0x32d7258, 0xe0778280b0, 0xc000b5c000, 0x5efc59531429db5e, 0x13)
	/app/tsdb/db.go:808 +0x35
github.com/prometheus/prometheus/storage.(*fanoutAppender).Commit(0xdf13284140, 0x1747e22, 0xed819422e)
	/app/storage/fanout.go:176 +0x49
github.com/prometheus/prometheus/scrape.(*scrapeLoop).scrapeAndReport.func1(0xddb4723ce8, 0xddb4723cf8, 0xe4c896cb00)
	/app/scrape/scrape.go:1096 +0x49
github.com/prometheus/prometheus/scrape.(*scrapeLoop).scrapeAndReport(0xe4c896cb00, 0x1bf08eb000, 0x1bf08eb000, 0x0, 0x0, 0x0, 0x1747e22, 0xed819422e, 0x4421000, 0x0, ...)
	/app/scrape/scrape.go:1163 +0xb4d
github.com/prometheus/prometheus/scrape.(*scrapeLoop).run(0xe4c896cb00, 0x1bf08eb000, 0x1bf08eb000, 0x0)
	/app/scrape/scrape.go:1049 +0x365
created by github.com/prometheus/prometheus/scrape.(*scrapePool).sync
	/app/scrape/scrape.go:518 +0x9ce
```

**Comment by roidelapluie** [comment]
Can we know more about the targets you scrape? Are you scraping targets with a very very huge number of labels/metrics or very long label value?

**Comment by haowells** [comment]
@roidelapluie  I think targets indeed huge. I don't have exactly number, but this problem instance scraping around 3000+ k8s nodes + pods on them.
I do a testing today, if I disable WAL compress feature. use option --no-storage.tsdb.wal-compression.  this golang panic never appear again.
but I do want to take advantage WAL compress feature. How can I let pod running without crash ? thanks

**Comment by roidelapluie** [comment]
Now I am wondering if you had some kind of disk corruption. Checkpointing from 0 to 348 does not feel right.

cc @codesome @bwplotka do you have any idea what is going on here?

**Comment by haowells** [comment]
@roidelapluie  could you explain more what make you feel not right for checkpoint from 0 to 348 ?
attach again all the logs 
```
level=info ts=2021-04-27T07:52:05.640Z caller=main.go:767 msg="Server is ready to receive web requests."
level=info ts=2021-04-27T11:28:27.328Z caller=compact.go:507 component=tsdb msg="write block" mint=1619509904854 maxt=1619510400000 ulid=01F49F9MAWFF938VV9FREAGPED duration=36m42.467500165s
level=info ts=2021-04-27T11:30:00.616Z caller=head.go:880 component=tsdb msg="Head GC completed" duration=1m32.640342858s
level=info ts=2021-04-27T12:06:47.363Z caller=compact.go:507 component=tsdb msg="write block" mint=1619510400000 maxt=1619517600000 ulid=01F49HFPDHH7FJFCS0TP6XRSAY duration=36m46.609972479s
level=info ts=2021-04-27T12:09:00.176Z caller=head.go:880 component=tsdb msg="Head GC completed" duration=2m12.216364926s
level=info ts=2021-04-27T12:09:00.655Z caller=checkpoint.go:95 component=tsdb msg="Creating checkpoint" from_segment=0 to_segment=348 mint=1619517600000
level=info ts=2021-04-27T12:16:41.994Z caller=head.go:977 component=tsdb msg="WAL checkpoint complete" first=0 last=348 duration=7m41.341673673s
level=info ts=2021-04-27T13:36:41.502Z caller=compact.go:507 component=tsdb msg="write block" mint=1619517600000 maxt=1619524800000 ulid=01F49PMF448G1XH02YCH6SK5QN duration=36m41.498440914s
level=info ts=2021-04-27T13:38:43.692Z caller=head.go:880 component=tsdb msg="Head GC completed" duration=1m55.508774268s
level=info ts=2021-04-27T13:38:44.174Z caller=checkpoint.go:95 component=tsdb msg="Creating checkpoint" from_segment=349 to_segment=556 mint=1619524800000
level=info ts=2021-04-27T13:47:29.303Z caller=head.go:977 component=tsdb msg="WAL checkpoint complete" first=349 last=556 duration=8m45.130321141s
level=info ts=2021-04-27T15:37:00.013Z caller=compact.go:507 component=tsdb msg="write block" mint=1619524800000 maxt=1619532000000 ulid=01F49XG6C4061PBF03MFVJPT4A duration=37m0.008912518s
level=info ts=2021-04-27T15:38:47.966Z caller=head.go:880 component=tsdb msg="Head GC completed" duration=1m47.298515803s
level=info ts=2021-04-27T15:38:48.665Z caller=checkpoint.go:95 component=tsdb msg="Creating checkpoint" from_segment=557 to_segment=749 mint=1619532000000
level=info ts=2021-04-27T15:47:45.689Z caller=head.go:977 component=tsdb msg="WAL checkpoint complete" first=557 last=749 duration=8m57.025049251s
level=info ts=2021-04-27T17:36:38.097Z caller=compact.go:507 component=tsdb msg="write block" mint=1619532000000 maxt=1619539200000 ulid=01F4A4BXM7V0TWJJVJRTFYYAT3 duration=36m38.090380378s
level=info ts=2021-04-27T17:38:21.237Z caller=head.go:880 component=tsdb msg="Head GC completed" duration=1m40.538897505s
level=info ts=2021-04-27T17:38:22.071Z caller=checkpoint.go:95 component=tsdb msg="Creating checkpoint" from_segment=750 to_segment=936 mint=1619539200000
level=info ts=2021-04-27T17:47:39.786Z caller=head.go:977 component=tsdb msg="WAL checkpoint complete" first=750 last=936 duration=9m17.716054753s
level=info ts=2021-04-27T18:47:33.565Z caller=compact.go:448 component=tsdb msg="compact blocks" count=3 mint=1619509904854 maxt=1619524800000 ulid=01F4A736CASX0CVC3B7KZY0TJ3 sources="[01F49F9MAWFF938VV9FREAGPED 01F49HFPDHH7FJFCS0TP6XRSAY 01F49PMF448G1XH02YCH6SK5QN]" duration=59m53.778656598s
level=info ts=2021-04-27T18:47:34.982Z caller=db.go:1230 component=tsdb msg="Deleting obsolete block" block=01F49F9MAWFF938VV9FREAGPED
level=info ts=2021-04-27T18:47:37.429Z caller=db.go:1230 component=tsdb msg="Deleting obsolete block" block=01F49HFPDHH7FJFCS0TP6XRSAY
level=info ts=2021-04-27T18:47:40.104Z caller=db.go:1230 component=tsdb msg="Deleting obsolete block" block=01F49PMF448G1XH02YCH6SK5QN
level=info ts=2021-04-27T19:36:24.032Z caller=compact.go:507 component=tsdb msg="write block" mint=1619539200000 maxt=1619546400000 ulid=01F4AB7MW7111FPKC1DY03AXXE duration=36m24.025671604s
level=info ts=2021-04-27T19:38:08.398Z caller=head.go:880 component=tsdb msg="Head GC completed" duration=1m43.721638942s
level=info ts=2021-04-27T19:38:09.031Z caller=checkpoint.go:95 component=tsdb msg="Creating checkpoint" from_segment=937 to_segment=1121 mint=1619546400000
level=info ts=2021-04-27T19:47:03.926Z caller=head.go:977 component=tsdb msg="WAL checkpoint complete" first=937 last=1121 duration=8m54.89583294s
level=info ts=2021-04-27T21:36:25.666Z caller=compact.go:507 component=tsdb msg="write block" mint=1619546400000 maxt=1619553600000 ulid=01F4AJ3C47EBBT88MN8KV5N9XW duration=36m25.658731721s
level=info ts=2021-04-27T21:38:21.942Z caller=head.go:880 component=tsdb msg="Head GC completed" duration=1m52.759446732s
level=info ts=2021-04-27T21:38:23.718Z caller=checkpoint.go:95 component=tsdb msg="Creating checkpoint" from_segment=1122 to_segment=1306 mint=1619553600000
level=info ts=2021-04-27T21:47:20.475Z caller=head.go:977 component=tsdb msg="WAL checkpoint complete" first=1122 last=1306 duration=8m56.760785804s
level=info ts=2021-04-27T22:46:20.046Z caller=compact.go:448 component=tsdb msg="compact blocks" count=3 mint=1619524800000 maxt=1619546400000 ulid=01F4AMT20WV9W07B9XWQ7SR6VZ sources="[01F49XG6C4061PBF03MFVJPT4A 01F4A4BXM7V0TWJJVJRTFYYAT3 01F4AB7MW7111FPKC1DY03AXXE]" duration=58m59.570757341s
level=info ts=2021-04-27T22:46:22.047Z caller=db.go:1230 component=tsdb msg="Deleting obsolete block" block=01F4A4BXM7V0TWJJVJRTFYYAT3
level=info ts=2021-04-27T22:46:23.362Z caller=db.go:1230 component=tsdb msg="Deleting obsolete block" block=01F4AB7MW7111FPKC1DY03AXXE
level=info ts=2021-04-27T22:46:24.680Z caller=db.go:1230 component=tsdb msg="Deleting obsolete block" block=01F49XG6C4061PBF03MFVJPT4A
level=info ts=2021-04-27T23:36:36.456Z caller=compact.go:507 component=tsdb msg="write block" mint=1619553600000 maxt=1619560800000 ulid=01F4ARZ3C42BZK6SXMJE7RS2YE duration=36m36.451314007s
level=info ts=2021-04-27T23:38:26.518Z caller=head.go:880 component=tsdb msg="Head GC completed" duration=1m49.405664918s
level=info ts=2021-04-27T23:38:27.148Z caller=checkpoint.go:95 component=tsdb msg="Creating checkpoint" from_segment=1307 to_segment=1491 mint=1619560800000
level=info ts=2021-04-27T23:47:18.897Z caller=head.go:977 component=tsdb msg="WAL checkpoint complete" first=1307 last=1491 duration=8m51.750104682s
level=info ts=2021-04-28T00:40:00.326Z caller=compact.go:448 component=tsdb msg="compact blocks" count=2 mint=1619509904854 maxt=1619546400000 ulid=01F4AVNQQJTJCFBSNRSAWSYJFZ sources="[01F4A736CASX0CVC3B7KZY0TJ3 01F4AMT20WV9W07B9XWQ7SR6VZ]" duration=52m41.428061694s
level=info ts=2021-04-28T00:40:09.488Z caller=db.go:1230 component=tsdb msg="Deleting obsolete block" block=01F4A736CASX0CVC3B7KZY0TJ3
level=info ts=2021-04-28T00:40:12.088Z caller=db.go:1230 component=tsdb msg="Deleting obsolete block" block=01F4AMT20WV9W07B9XWQ7SR6VZ
level=info ts=2021-04-28T01:36:33.152Z caller=compact.go:507 component=tsdb msg="write block" mint=1619560800000 maxt=1619568000000 ulid=01F4AZTTM4QTZK7NG4N27CT9DG duration=36m33.147862528s
level=info ts=2021-04-28T01:38:12.675Z caller=head.go:880 component=tsdb msg="Head GC completed" duration=1m38.654621383s
level=info ts=2021-04-28T01:38:13.221Z caller=checkpoint.go:95 component=tsdb msg="Creating checkpoint" from_segment=1492 to_segment=1675 mint=1619568000000
level=info ts=2021-04-28T01:47:13.480Z caller=head.go:977 component=tsdb msg="WAL checkpoint complete" first=1492 last=1675 duration=9m0.260522869s
level=info ts=2021-04-28T03:36:09.614Z caller=compact.go:507 component=tsdb msg="write block" mint=1619568000000 maxt=1619575200000 ulid=01F4B6PHW4RA48PZC0Y3NZV9XK duration=36m9.609761176s
level=info ts=2021-04-28T03:37:23.254Z caller=head.go:880 component=tsdb msg="Head GC completed" duration=1m13.006260675s
level=info ts=2021-04-28T03:37:24.057Z caller=checkpoint.go:95 component=tsdb msg="Creating checkpoint" from_segment=1676 to_segment=1859 mint=1619575200000
level=info ts=2021-04-28T03:46:18.420Z caller=head.go:977 component=tsdb msg="WAL checkpoint complete" first=1676 last=1859 duration=8m54.364573924s
level=info ts=2021-04-28T04:46:18.057Z caller=compact.go:448 component=tsdb msg="compact blocks" count=3 mint=1619546400000 maxt=1619568000000 ulid=01F4B9BB5MV2PTNBB15X4H1AM4 sources="[01F4AJ3C47EBBT88MN8KV5N9XW 01F4ARZ3C42BZK6SXMJE7RS2YE 01F4AZTTM4QTZK7NG4N27CT9DG]" duration=59m59.637244338s
level=info ts=2021-04-28T04:46:20.320Z caller=db.go:1230 component=tsdb msg="Deleting obsolete block" block=01F4AJ3C47EBBT88MN8KV5N9XW
level=info ts=2021-04-28T04:46:21.611Z caller=db.go:1230 component=tsdb msg="Deleting obsolete block" block=01F4ARZ3C42BZK6SXMJE7RS2YE
level=info ts=2021-04-28T04:46:22.965Z caller=db.go:1230 component=tsdb msg="Deleting obsolete block" block=01F4AZTTM4QTZK7NG4N27CT9DG
level=info ts=2021-04-28T05:36:55.325Z caller=compact.go:507 component=tsdb msg="write block" mint=1619575200000 maxt=1619582400000 ulid=01F4BDJ944C7VT12VKMAPRAMD3 duration=36m55.320899387s
level=info ts=2021-04-28T05:38:41.699Z caller=head.go:880 component=tsdb msg="Head GC completed" duration=1m45.493954625s
level=info ts=2021-04-28T05:38:42.399Z caller=checkpoint.go:95 component=tsdb msg="Creating checkpoint" from_segment=1860 to_segment=2046 mint=1619582400000
level=info ts=2021-04-28T05:47:45.186Z caller=head.go:977 component=tsdb msg="WAL checkpoint complete" first=1860 last=2046 duration=9m2.787650087s
level=info ts=2021-04-28T07:37:14.595Z caller=compact.go:507 component=tsdb msg="write block" mint=1619582400000 maxt=1619589600000 ulid=01F4BME0C40NKGSW5KFFY26KY3 duration=37m14.590739737s
level=info ts=2021-04-28T07:38:56.797Z caller=head.go:880 component=tsdb msg="Head GC completed" duration=1m41.354627576s
level=info ts=2021-04-28T07:38:57.623Z caller=checkpoint.go:95 component=tsdb msg="Creating checkpoint" from_segment=2047 to_segment=2234 mint=1619589600000
level=info ts=2021-04-28T07:48:00.781Z caller=head.go:977 component=tsdb msg="WAL checkpoint complete" first=2047 last=2234 duration=9m3.159665417s```

**Comment by codesome** [comment]
> Checkpointing from 0 to 348 does not feel right.

It just looks like a big environment from the logs. I don't think the panic implies a disk corruption.

> panic: snappy: decoded block is too large
> if I disable WAL compress feature. use option --no-storage.tsdb.wal-compression. this golang panic never appear again.

Seems like some limitation in snappy? I will be able to look at it only after a few weeks.

**Comment by codesome** [comment]
Looking at https://github.com/golang/snappy/blob/674baa8c7fc30da5df3074a459494a7e6b427dff/decode.go#L30-L43 and I think we _cannot_ rule out disk corruption yet :)

**Comment by codesome** [comment]
Ignore my previous comment, I was looking at the wrong thing. It is checked even before we touch the disk https://github.com/golang/snappy/blob/674baa8c7fc30da5df3074a459494a7e6b427dff/encode.go#L21, so it is not a disk corruption.

It might be a matter of very large record. A very big scrape target. <disappearing for now>

**Comment by roidelapluie** [comment]
Thanks for checking this @codesome :) Indeed it seems a limitation in snappy.

Are you by any chance using prometheus federation with a lot of metrics? Or do you have an idea of the bigger scrape target?

**Comment by haowells** [comment]
@roidelapluie @codesome  any idea about this,  can we identify what's cause this problem? because of some big metrics or limitation of snappy?

**Comment by codesome** [comment]
> because of some big metrics or limitation of snappy?

Both, a big target which is hitting the snappy limit

Could you please tell us about [this](https://github.com/prometheus/prometheus/issues/8762#issuecomment-828279636):
> Are you by any chance using prometheus federation with a lot of metrics? Or do you have an idea of the bigger scrape target?

**Comment by haowells** [comment]
@codesome  I can provide some data about my scrape target from /tsdb-status endpoint 

<h2 style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0.5rem; font-weight: 500; line-height: 1.2; font-size: 2rem; color: rgb(33, 37, 41); font-family: -apple-system, system-ui, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, Arial, &quot;Noto Sans&quot;, &quot;Liberation Sans&quot;, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">TSDB Status</h2><h3 class="p-2" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0.5rem; font-weight: 500; line-height: 1.2; font-size: 1.75rem; padding: 0.5rem !important; color: rgb(33, 37, 41); font-family: -apple-system, system-ui, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, Arial, &quot;Noto Sans&quot;, &quot;Liberation Sans&quot;, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Head Stats</h3><div class="p-2" style="box-sizing: border-box; padding: 0.5rem !important; color: rgb(33, 37, 41); font-family: -apple-system, system-ui, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, Arial, &quot;Noto Sans&quot;, &quot;Liberation Sans&quot;, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

Number of Series | Number of Chunks | Number of Label Pairs | Current Min Time | Current Max Time
-- | -- | -- | -- | --
30032627 | 59765210 | 1618607 | 2021-05-06T08:00:00.000Z (1620288000000) | 2021-05-06T11:29:23.285Z (1620300563285)

</div>

**Comment by csmarchbanks** [comment]
Thank you for all the information so far! Since this is likely caused by a single scrape, could you provide us with what the largest scrapes your server does? Feel free to anonymize the information, I suspect kube-state-metrics will be at the top.
```
topk(10, scrape_samples_post_metric_relabeling)
```

**Comment by haowells** [comment]
@csmarchbanks.  what the scrape_samples_post_metric_relabeling means ?

Yes. you are right. kube-state-metrics is the top1

scrape_samples_post_metric_relabeling{application_xxx_name="kubesystem", applicationinstance_xxx_name="kube-state-metrics-deployments", environment_xxx_name="production", firewall_network_tess_io_type="none", instance="xxx:8080", job="kubernetes_pod", k8s_app="kube-state-metrics", kubernetes_namespace="kube-system", lifecycle_state_tess_io_name="production", pod_template_hash="5bcccc45f9", zone_network_tess_io="mpt-prod"}
7132570

**Comment by csmarchbanks** [comment]
Thank you for the information. scrape_samples_post_metric_relabeling is the number of samples scraped from a target that actually make it into the database. It is the same as scrape_samples_scraped minus any metrics dropped via metric relabeling rules.

Judging from your information, you have ~400 characters per metric for labels on the job + probably 100-200 characters for additional labels such as pod, container, etc that are exposed by kube state metrics. Multiply that estimate by more than 7 million series being returned by kube state metrics means that the record could be as large as 3.3 to 4 GB in size, and the maximum snappy encoding size is 3.7 GB. The panic will be fixed for this size of scrape in Prometheus 2.27.0 (release candidate to be created shortly). The large records wouldn't be compressed to avoid this panic, in the future we hope to compress them as well, see https://github.com/prometheus/prometheus/issues/8791.

**Comment by bwplotka** [comment]
The great investigation, thanks, everyone. I think we should also give this feedback to kube-state-metrics too.

**Comment by bwplotka** [comment]
https://github.com/kubernetes/kube-state-metrics/issues/1475
