### ISSUE TITLE
Add Generic HTTP-based SD

### ISSUE THREAD

**Issue by vgratian** [prometheus/prometheus#8771]
## Proposal
**Use case. Why is this important?**

This SD should look exactly the same as the file-based SD, except that it is fetched from an HTTP endpoint rather than the local fs. 

I work on a large project for storage monitoring and I think many face the same issue that we do. We don't want to open a SD request for our own Project, but a generic HTTP-based would satisfy everyone.

I am also coding in Go, so if the community thinks this is a good idea, I could prepare a pull request.

**Comment by vgratian** [comment]
I am also coding in Go, so if the community thinks this is a good idea, I could prepare a pull request!

**Comment by roidelapluie** [comment]
This is discussed here: https://docs.google.com/document/d/1tVeuzjpU4-TiYPNWJXKmcyIuZF6A2tUq270RbBT5zho/edit

**Comment by vgratian** [comment]
awesome, thanks for sharing the link

**Comment by vgratian** [comment]
is someone already working on this? should I go ahead and try to implement it myself?

**Comment by roidelapluie** [comment]
There are still disagreements over the design doc.

**Comment by roidelapluie** [comment]
This is being implemented in #8839

**Comment by juliusv** [comment]
Can this issue be closed now?

**Comment by roidelapluie** [comment]
Yes 🥳
