### ISSUE TITLE
Prometheus negative cpu utilization with rate

### ISSUE THREAD

**Issue by sksingh20** [prometheus/prometheus#8772]
Prometheus reporting negative value of cpu utilization as taken with rate function.

Here is link of snapshots of error condition.
100 - (avg by (instance) (rate(node_cpu_seconds_total{mode="idle",instance=~"$host"}[1m])) * 100)
Response: attached snapshot link.

[http://skras.ddns.net/TI/Promcpu](http://skras.ddns.net/TI/Promcpu)

Troubleshooting Query: node_cpu_seconds_total{mode="idle",instance=~"$host"}
Troubleshooting Query Response:

Object
request:Object
url:"api/datasources/proxy/1/api/v1/query_range?query=node_cpu_seconds_total%7Bmode%3D%22idle%22%2Cinstance%3D~%22sermon%22%7D&start=1619717745&end=1619717880&step=15"
method:"GET"
hideFromInspector:false
response:Object
status:"success"
data:Object
resultType:"matrix"
result:Array[4]
0:Object
metric:Object
values:Array[10]
0:Array[1619717745,322555.9]
1:Array[1619717760,322570.32]
2:Array[1619717775,322580]
3:Array[1619717790,322580]
4:Array[1619717805,322580]
5:Array[1619717820,322627.9]
6:Array[1619717835,322642.11]
7:Array[1619717850,322656.44]
8:Array[1619717865,322670.74]
9:Array[1619717880,322685.1]
1:Object
2:Object
3:Object

**Comment by sksingh20** [comment]
Not able to fix this issue even after putting so much hours. This is understood that this is causing due to missed scrap. But not sure how rate function actually normalizing values which end up having negative values for cpu utilization.

**Comment by roidelapluie** [comment]
Thanks for your report. It looks as if this is actually a question about usage and not development.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) or our [forums](https://discuss.prometheus.io) rather than in a GitHub issue. In our [community channels](https://prometheus.io/community), more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by sksingh20** [comment]
@roidelapluie Can you help to understand how to use correctly if this is usage issue. This appears to me as development issue which some how did not handled data properly or Prometheus is Prometheus return negative utilization report.

**Comment by sksingh20** [comment]
@roidelapluie can you hep to address this issue. This is making complete graph in question. Please also confirm If this is limitation of product due to its approximation behaviour.

**Comment by darshanime** [comment]
It's recommended to have the range selector interval to be > 4*scrape interval. Can you try that?

**Comment by sksingh20** [comment]
> It's recommended to have the range selector interval to be > 4*scrape interval. Can you try that?

Already tries with 1m, 2m where scrap interval is 15sec... but same issue
