### ISSUE TITLE
Way to stop scrape stats being sent to remote write endpoints

### ISSUE THREAD

**Issue by loganmc10** [prometheus/prometheus#8784]
## Proposal
**Use case. Why is this important?**

I'm talking about metrics like ```scrape_samples_scraped```. We use Grafana Cloud and we pay per series. It would be nice to be able to disable sending these kinds of metrics to Grafana Cloud.

It would save us quite a bit of money.

**Comment by loganmc10** [comment]
I haven't tried dropping them using a metric relabel config, however the fact that ```scrape_samples_post_metric_relabeling``` is one of the samples makes me believe they are added after that stage anyway

**Comment by loganmc10** [comment]
Sorry I just realized that ```write_relabel_configs``` exists, this is what I'm looking for

**Comment by roidelapluie** [comment]
https://grafana.com/docs/grafana-cloud/billing-and-usage/prometheus/usage-reduction/
