### ISSUE TITLE
investigate per shard buffering improvements for remote write

### ISSUE THREAD

**Issue by cstyan** [prometheus/prometheus#8788]
Currently a shard allocates a buffer of `prompb.TimeSeries`, which is extended to be slightly longer than `maxSamplesPerSend` if sending of exemplars is enabled. We also allocate buffers of `prompb.Sample` and `prompb.Exemplar`, which are used to actually store the data of a sample or exemplar. The `prompb.TimeSeries` buffer then just references elements in the other two buffers before generating the actual `WriteRequest`. This saves us some allocations.

However, even though the the `prompb.TimeSeries` buffer can hold `maxSamplesPerSend*1.1` `promob.TimeSeries`, we only check if we have `maxSamplesPerSend` OR `maxExemplars` before building a write request. The `maxSamplesPerSend` defaults to `100` and `maxExemplars` is set to `int(math.Max(1, float64(maxSamplesPerSend/10)))`, or 10 in the case of default config. This means the worst case scenario is that we could end up sending write requests that only have 10 samples and 10 exemplars, potentially impacting throughput. 

We should investigate a way to buffer a reasonable amount of data points, regardless of type, and not having a max of one kind lead to reduced throughput.

**Comment by LeviHarrison** [comment]
We could just remove the limit for specific data types altogether, and set a limit for data points in total. The only fault I can see with this approach is over-allocating the `maxExamplars` buffer, given that use is expected to be low. That being said, I'm not really understanding why this buffer is even needed in the first place. It seems that it's only being used to hold the exemplar until it can be assigned to `pendingData[nPending].Exemplars`.

https://github.com/prometheus/prometheus/blob/e313ffa8abf61b5e2df3e917e2f31a899c91b66c/storage/remote/queue_manager.go#L1095-L1098

**Comment by cstyan** [comment]
>That being said, I'm not really understanding why this buffer is even needed in the first place. It seems that it's only being used to hold the exemplar until it can be assigned to `pendingData[nPending].Exemplars`.

This is to save on memory/allocations, we allocate the buffers `sampleBuffer` and `exemplarBuffer`, and then just refence their elements in `pendingData`. This means that there isn't an exemplar slice and sample slice allocated for each element in `pendingData`.

**Comment by cstyan** [comment]
`Ok, that makes sense. Then maybe we allocate a buffer of dataPoint or something like that, which could hold either a sample or an exemplar.` At that point we we could just allocate the `pendingData` buffer to be the max size. We might end up with slightly higher memory usage, but if the potential impact to throughput is reduced then I think it's a win.

**Comment by LeviHarrison** [comment]
Can I open a PR for this?

**Comment by roidelapluie** [comment]
> Great! Can I open a PR for this?

Sure, it would make the discussion progress. I am sure that this is the kind of things that need to be experimented to decide.
