### ISSUE TITLE
support traversing an AST concurrently

### ISSUE THREAD

**Issue by chunshao90** [prometheus/prometheus#8789]
## Proposal
pql: A +B
Current implementation in [promql/parser/ast.go](https://github.com/prometheus/prometheus/blob/main/promql/parser/ast.go#L302) implement is not concurrent.
When A & B costs a lot of time, traversing an AST concurrently can be greatly improved.
A concurrent version has been implemented in our company, and works great. If interested, I can contribute to the community.

**Comment by roidelapluie** [comment]
Currently the promql engine is designed to run in one thread. This is a feature, we have limit on concurrent queries etc to protect the server. In general this works fine.

Are you using the parser outside of the promql code?

**Comment by worcsrcsgg** [comment]
We fork the prometheus, extend and modifiy a few modules of prometheus, and push down some operations to the underlying storage.
The concurrent version has achieved a great performance improvement in our company.
Can we reduce the granularity of concurrency to a [Selector](https://github.com/prometheus/prometheus/blob/main/promql/parser/ast.go#L185)?
[query.max-concurrency](https://github.com/prometheus/prometheus/blob/v2.25.2/cmd/prometheus/main.go#L290) may need to be modified to ensure that the concurrency limit is effective.

```
	a.Flag("query.max-concurrency", "Maximum number of queries executed concurrently.").
		Default("20").IntVar(&cfg.queryConcurrency)
```

**Comment by roidelapluie** [comment]
Not really since it would mean that a complex query would 'block' other prometheus queries. Currently the complex queries are a bit "penalized" by the current system. If you have really complex queries you run often and they take a lot of time it is preferable to use recording rules.

**Comment by beorn7** [comment]
Hello from the bug scrub.

Nothing has moved here in the last 3y.

Note that sister projects implementing distributed versions of Prometheus (Cortex, Thanos, Mimir, …) are more interested in concurrent query evaluation and have already done work on it. E.g. https://github.com/thanos-io/promql-engine 

We'll close this issue, as it didn't go beyond initial ideas. This should not imply that we don't want any of these optimizations in Prometheus ever, but we'll open an issue if somebody comes up with a concrete plan.
