### ISSUE TITLE
Compress very large records in the WAL

### ISSUE THREAD

**Issue by csmarchbanks** [prometheus/prometheus#8791]
Right now, if a record is larger than the maximum size snappy can compress (~3.7 GB) we do not compress it at all, see https://github.com/prometheus/prometheus/pull/8790. A user would probably like these large datasets compressed as chances are a scrape of that size has a fair amount of repeated label names/values that could be compressed away.

**Comment by LeviHarrison** [comment]
Can the record be arbitrarily split into smaller chunks (which are then compressed by themselves) or are there only certain places in the data where it can happen?

**Comment by LeviHarrison** [comment]
What I meant was splitting a record into multiple chunks, compressing those, and them putting them back together as one record, although there are probably issues with that.

**Comment by csmarchbanks** [comment]
Yep, that is kind of what the framed version of snappy does. Upon decoding time we would have to know where the multiple chunks start/end to snappy decompress them appropriately. I think that information would have to be stored at write time which would involve a new record type, but if there is a clever way to do it that would be awesome.

**Comment by roidelapluie** [comment]
When we work on this, we need to take into account our will to have transactionnal remote write and not do something that would go against that goal.

**Comment by LeviHarrison** [comment]
I've managed to combine chunks of encoded data into one, without any additional records needed, and get it to decode. But the decoder seems to cap out at 4.39 GB, which is likely the highest we can push it with one input chunk. Better, but not by much.

**Comment by LeviHarrison** [comment]
Actually, I believe I found the reason for the cap. 4.39 GB -> bytes is curiously close to the limit of `uint32`, Golang's default `uint` type. Encoding `4294967295` bytes (the exact maximum) split into three chunks and then decoding it yields a success. But, `4294967298` bytes is a failure.

This seems to check out when taking a peek into the decoding function in snappy (although the amd and arm versions are in assembly, I assume it's the same).

https://github.com/golang/snappy/blob/33fc3d5d8d990c6bccaf4da1d7bb661e0cc53cb6/decode_other.go#L25-L27

**Comment by bwplotka** [comment]
I am not sure if this is worth a try. 7 million series scrape is extreme, and I wonder if we should focus on teaching others and ensuring:

* Scrape targets never are so large (especially by [default](https://github.com/kubernetes/kube-state-metrics/issues/1475)), or users select what they need.
* It's easy to shard scrape by target within single process as well as multiple Prometheus-es or Agent modes.

**Comment by beorn7** [comment]
Hello from the bug scrub.

Nothing has happened here in the last 3y. There are some doubts how relevant this optimization is in practice. We'll close this for now, but if anyone believes we should still work on it, please follow up with some evidence, and we'll re-open.
