### ISSUE TITLE
Audit logging feature in Prometheus and alertmanager

### ISSUE THREAD

**Issue by rajiamarnath** [prometheus/prometheus#8794]
Hi, 

Please let us know if there are plans to support Audit logging feature for Prometheus and Alertmanager.

Use Case:
Audit logs are intended for system-related events that are significant.  Some examples:
-          Functional problems caused by application users, application errors, configuration problems and possible applications bugs
In case of errors, there should be a hint given about the error, i.e. component owner should provide enough information to the system administrator should check the services for debugging this.
-          start and stop of a service
-          events that change the state of critical objects in the system (Managed Objects, Alarm states etc)

**Comment by roidelapluie** [comment]
Thank you for your interest in Prometheus.

This issue does not seem actionnable, so I will close it. Please open specific issues if we miss some logs. Prometheus should provide you with the logs needed to operate it.

You can also contact the community at https://prometheus.io/community if you have more general cross-projects questions like this one.
