### ISSUE TITLE
Render Exemplars in Prometheus UI

### ISSUE THREAD

**Issue by bwplotka** [prometheus/prometheus#8797]
Just sharing idea and feedback we have. We talk about better multi-signal correlation techniques, so we should probably start with our own UI too! (: 

## Acceptance Criteria:

* Graph page can render exemplars on top of time series line, like Grafana does.
* Add Instant exemplars query view?

**Comment by roidelapluie** [comment]
This looks great! I would however make them a checkbox.

**Comment by LeviHarrison** [comment]
I'm working on this. The entire PromQL query can be passed to `/query_exemplars` to get the exemplars, correct?

**Comment by LeviHarrison** [comment]
> Add Instant exemplars query view?

@bwplotka I'd be interested to know more about your idea for this. #8832 will add support to the graph, but won't touch anywhere else.

**Comment by bwplotka** [comment]
So looks like the first AC `Graph page can render exemplars on top of time series line, like Grafana does.` was done and I don't remember what I meant by instant query view exemplars, so let's close it 🙃

**Comment by roidelapluie** [comment]
"instant query view exemplars" => examplars in the console tab ?

**Comment by LeviHarrison** [comment]
Yeah that's what I was thinking, but how would that work? I don't believe we even have an instant exemplar query API. Also there's the question of how to display them.

**Comment by beorn7** [comment]
Hello from the bug scrub.

3y later, nothing has moved here. We assume that exemplars in the table view aren't that useful. We'll close this, but if somebody has concrete plans to work on exemplars in the table view, please follow up.
