### ISSUE TITLE
Add exemplar support to clickhouse remote_storage_adapter

### ISSUE THREAD

**Issue by weetime** [prometheus/prometheus#8803]
## Proposal
**Use case. Why is this important?**

*“Nice to have” is not a good use case. :)*
When I use prometheus remote_storage_adapter with clickhouse, I can't found a good example. An old project prom2click can't work , so I refactor this project.

**Comment by weetime** [comment]
https://github.com/weetime/remote_storage_adapter

**Comment by roidelapluie** [comment]
Thank you, you should add the Apache 2 license to your repository.

**Comment by weetime** [comment]
> Thank you, you should add the Apache 2 license to your repository.

Thank you, I have done.
