### ISSUE TITLE
reevaluate remote write queue config defaults

### ISSUE THREAD

**Issue by cstyan** [prometheus/prometheus#8808]
We'll want to be able to maintain the same max samples/s output with the new defaults, but bumping the max samples per send would lower the shard requirements, and upsharding can lead to DDOS like issues since we have no back pressure mechanism (related issues: https://github.com/prometheus/prometheus/issues/5166)

**Comment by DurveshKumarPal** [comment]
[Uploading Transactional based remote-write _ Design doc.docx…]()

**Comment by bboreham** [comment]
The main thing I would change is to lower max-shards from 1,000 - maybe 100.  Even that is too big for most installations.

**Comment by cstyan** [comment]
The defaults have been changed: https://github.com/prometheus/prometheus/blob/main/config/config.go#L155-L172

**Comment by bboreham** [comment]
And it was me that changed them 🤦‍♂️ 
Current `MaxShards: 200` is still too high, but not quite as bad.

**Comment by krajorama** [comment]
Hello from the bug scrub:  seeing that there has been no PR opened in the last 3 years, this seems to be low priority or went away. Please reopen if there is new information, work to be done.
