### ISSUE TITLE
Direct support for configuration in Kubernetes

### ISSUE THREAD

**Issue by carroarmato0** [prometheus/prometheus#8813]
## Proposal

The current way to pass configuration such as extra alerts or rules in Prometheus on Kubernetes is to use a ConfigMap, have it mounted inside the Prometheus/AlertManager Pods and to use a sidecar container to perform the reloading.

This works through inotify, however, the sync between the ConfigMap and the Volume depends on the configuration of Kubelet which is in charge of the sync.

By default, this can take a minute.  While this can be changed to something lower, depending on the infrastructure you might not have control over this.

Ideally, Prometheus and Alertmanager would be able to directly talk to the Kubernetes API and watch for changes, allowing modifications of rules to be near instant.

**Comment by roidelapluie** [comment]
I am not sure we want to interact direcltly with config maps but I recall @brancz to express the will to not have "reloaders" sidecar and therefore Prometheus would gain the ability to reload the configuration from disk as it changes by itself.

**Comment by carroarmato0** [comment]
@roidelapluie that would still have the issue of you being at the mercy of the kubelet configuration which you may or may not have control over depending on the cloud vendor, and have inconsistencies to take care of.

**Comment by brancz** [comment]
I get the appeal of this, though I do wonder whether this is a step too far in regards to integrating. There are various projects out there allowing this, and the difficulty I have is that if we add Kubernetes integration then people will want consul/etcd/...

I'm not saying this is not a good idea, but I'm not sure the maintenance burden given the potential scope is justified.

**Comment by carroarmato0** [comment]
@brancz would perhaps some kind of HTTP endpoint be possible from which to fetch dynamic configuration from via polling be an option? (not sure if it's already possible today).
In kube everything is an API object, so theoretically speaking, if Prometheus could be given a URL to an HTTP endpoint containing the configuration, and having a configurable polling, might work?  That would it should be more compatible I guess with consolue and etcd? Although you might still have to deal with proper parsing options depending on how the other things implement or display the data....

**Comment by carroarmato0** [comment]
The ideal scenario would be that a change in configuration would be near instant. That will not always be possible, but the biggest pain right now is that you are at the mercy of however the kubelet has been configured to sync the contents of the configmap with the mounted volume in the pods.

The specific use-case here which I'm busy with,  users can configure alert rules in a GUI, the GUI app translates the configuration in Alert Rules for Prometheus in a ConfigMap, the ConfigMap contents are mounted inside the Prometheus Pod(s), and there's a config-reload sidecar which takes it from there. From a user's perspective, having to wait minutes for something to visibly happen can make them doubt if the rules have been applied or not. Unless they are informed that it can take some time.

**Comment by fpetkovski** [comment]
In order to keep Prometheus less specific to Kubernetes, this can be implemented through a dedicated config reloader which is going to have a watch on a single Secret or ConfigMap and update the Prometheus config file whenever the configuration changes. Then this reloader can be run as a sidecar only for the Kubernetes use case.

**Comment by krajorama** [comment]
Hello from the bug scrub: thank you for the good discussion, however there hasn't been movement on this issue for a few years. We're closing the issue with the understanding that it can be reopened if someone wants to work on this and also that there's an alternative proposal to achieve the same result by an external component, as suggested here: https://github.com/prometheus/prometheus/issues/8813#issuecomment-926466555
