### ISSUE TITLE
Not sure of your release numbering/versioning practices, but prometheus 2.27.0 executable reports 2.26.0 version

### ISSUE THREAD

**Issue by rgoerwit** [prometheus/prometheus#8820]
I may just not understand numbering/versioning practices in your case, but the prometheus 2.27.0 executable reports 2.26.0 version.

Replicate the issue:

 ./prometheus --version
prometheus, version 2.26.0 (branch: main, revision: 277bac622ac74240bbe6b75cbe96fe3472a7dc48)
  build user:       buildtmpuser@ubuntu
  build date:       20210513-01:21:26 # NOTE DATE
  go version:       go1.16.3
  platform:         linux/arm64

 git log | head -3
commit 277bac622ac74240bbe6b75cbe96fe3472a7dc48
Author: ide-rea <30512600+ide-rea@users.noreply.github.com>
Date:   Wed May 12 22:47:05 2021 +0800

**Comment by roidelapluie** [comment]
Did you build the branch release-2.27 ?

**Comment by csmarchbanks** [comment]
I downloaded the latest linux 2.27.0 binary and it is reporting 2.27.0 for me:
```
➜  prometheus-2.27.0.linux-amd64 ./prometheus --version
prometheus, version 2.27.0 (branch: HEAD, revision: 24c9b61221f7006e87cd62b9fe2901d43e19ed53)
  build user:       root@f27daa3b3fec
  build date:       20210512-18:04:51
  go version:       go1.16.4
  platform:         linux/amd64
```

Which version/build are you using? Or from source?

**Comment by rgoerwit** [comment]
Here's what I get:

 **cd /tmp**
 **git clone https://github.com/prometheus/prometheus**
Cloning into 'prometheus'...
remote: Enumerating objects: 74849, done.
remote: Counting objects: 100% (160/160), done.
remote: Compressing objects: 100% (125/125), done.
remote: Total 74849 (delta 56), reused 95 (delta 31), pack-reused 74689
Receiving objects: 100% (74849/74849), 125.93 MiB | 7.97 MiB/s, done.
Resolving deltas: 100% (39781/39781), done.
**cd prometheus/**
**git log | head -3**
commit 277bac622ac74240bbe6b75cbe96fe3472a7dc48
Author: ide-rea <30512600+ide-rea@users.noreply.github.com>
Date:   Wed May 12 22:47:05 2021 +0800

**Comment by csmarchbanks** [comment]
Ahh yes, you are on the `main` branch not `release-2.27`. Once https://github.com/prometheus/prometheus/pull/8819 is merged the main branch will be updated to report a version of 2.27.0 as well. We do releases in a branch, and once everything is OK merge it back into main.

**Comment by rgoerwit** [comment]
So you can close this.  No, you're correct:  I didn't until now understand how the branching and tags were being done...

**Comment by rgoerwit** [comment]
git checkout "tags/v2.27.0"
git fetch
