### ISSUE TITLE
readCheckpoint wasn't able to read all data from the checkpoint  xxx

### ISSUE THREAD

**Issue by fcddk** [prometheus/prometheus#8825]
**Environment**

* System information:

	Linux slave07  5.4.61-050461-generic #202008260931 SMP Wed Aug 26 09:34:29 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

* Prometheus version:

	2.22.0

* Logs:
```
ts=2021-05-14T00:30:44.168Z caller=dedupe.go:112 component=remote level=error remote_name=prometheus-center-adapter url=http://localhost:9201/write msg="error tailing WAL" err="readCheckpoint: readCheckpoint wasn't able to read all data from the checkpoint /prometheus/wal/checkpoint.00000366/00000000, size: 13697024, totalRead: 2335785"
```

**Comment by fcddk** [comment]
remote_write:
- url: http://localhost:9201/write
  remote_timeout: 30s
  name: prometheus-center-adapter
  queue_config:
    capacity: 2500
    max_shards: 200
    min_shards: 1
    max_samples_per_send: 500
    batch_send_deadline: 5s
    min_backoff: 30ms
    max_backoff: 100ms

**Comment by roidelapluie** [comment]
cc @cstyan @csmarchbanks @codesome

**Comment by cstyan** [comment]
@fcddk can you please send us more of the logs from that Prometheus instance? I can't really debug or make any suggestions based on that one log line alone.

**Comment by fcddk** [comment]
@cstyan   I only get this exception log, other logs did not appear.

**Comment by roidelapluie** [comment]
Can we get prometheus --version, and the filesystem you are using?

**Comment by fcddk** [comment]
df -hT |grep monitor: 
/dev/monitor           ext4      930G  3.5G  879G   1% /monitor

**Comment by fcddk** [comment]
prometheus, version 2.22.0 (branch: non-git, revision: non-git)
  build user:       root@5jje19a
  build date:       20210503-03:12:53
  go version:       go1.15.1
  platform:         linux/amd64

**Comment by roidelapluie** [comment]
cc  @cstyan do you have an idea about what is going on here?

**Comment by cstyan** [comment]
Not with the information given, no.

IIRC even if TSDB creates a new checkpoint while remote write is reading the current checkpoint, which results in deletion of the current checkpoint, remote write having the file pointer open means the file isn't actually deleted/cleaned up until remote write closes that pointer. So without more information, off the top of my head I don't have any ideas.

**Comment by krajorama** [comment]
Hello from the bug scrub: there hasn't been new information to go on since three years, please test the scenario with the latest Prometheus version and open a new issue if it comes up.
