### ISSUE TITLE
Prevent scrape OOM by scrape stage limitation when target expose too many metrics 

### ISSUE THREAD

**Issue by hanjm** [prometheus/prometheus#8827]
## Problem

some bad service expose too many cardinary metrics, the prometheus server will OOM even if we config `sample_limit` .

currently, The Prometheus server will read the total body when scrape, then do limit operation when append to db.

https://github.com/prometheus/prometheus/blob/main/scrape/scrape.go#L738
```go
func (s *targetScraper) scrape(ctx context.Context, w io.Writer) (string, error)  
// ...
_, err = io.Copy(w, s.gzipr)
// ...
```

## Proposal
Prometheus server use a limit reader, not read all the body.
or 
prometheus client sdk set the `sample_count` in http response header.  Prometheus server read header `sample_count` first, then read body. not copy all the body.

**Comment by roidelapluie** [comment]
Thank you. Relying on a client header is fragile but we could use an io.LimitReader.

Note that the default limit should be pretty high (we have users scraping 4 GB per scrape).
