### ISSUE TITLE
Azure/azure-sdk-for-go does not contain arm/compute.

### ISSUE THREAD

**Issue by logston** [prometheus/prometheus#8829]
I've tried the following with an number of different `@SHAs` including `@main` and get the same error:

```
GO111MODULE=on go get github.com/prometheus/prometheus@main

go mod vendor
go: downloading google.golang.org/grpc v1.37.0
go: downloading github.com/aws/aws-sdk-go v1.38.35
go: downloading golang.org/x/net v0.0.0-20210505214959-0714010a04ed
go: downloading golang.org/x/oauth2 v0.0.0-20210427180440-81ed05c6b58c
go: downloading google.golang.org/genproto v0.0.0-20210429181445-86c259c2b4ab
go: downloading github.com/prometheus/common v0.23.0
go: downloading golang.org/x/sys v0.0.0-20210503173754-0981d6026fa6
go: downloading google.golang.org/api v0.46.0
go: downloading cloud.google.com/go v0.81.0
go: downloading golang.org/x/text v0.3.6
go: finding module for package github.com/prometheus/prometheus/discovery/config
go: downloading github.com/uber/jaeger-client-go v2.28.0+incompatible
go: finding module for package k8s.io/api/discovery/v1beta1
go: downloading github.com/google/pprof v0.0.0-20210504235042-3a04a4d88a10
go: downloading github.com/docker/docker v20.10.6+incompatible
go: downloading github.com/json-iterator/go v1.1.11
go: downloading github.com/uber/jaeger-lib v2.4.1+incompatible
go: found github.com/prometheus/prometheus/discovery/config in github.com/prometheus/prometheus v2.5.0+incompatible
go: downloading github.com/gophercloud/gophercloud v0.17.0
go: downloading github.com/Azure/azure-sdk-for-go v54.0.0+incompatible
go: finding module for package github.com/Azure/azure-sdk-for-go/arm/network
go: finding module for package github.com/Azure/azure-sdk-for-go/arm/compute
github.com/.... imports
        github.com/prometheus/prometheus/discovery/config imports
        github.com/prometheus/prometheus/discovery/azure imports
        github.com/Azure/azure-sdk-for-go/arm/compute: module github.com/Azure/azure-sdk-for-go@latest found (v54.2.0+incompatible), but does not contain package github.com/Azure/azure-sdk-for-go/arm/compute
github.com/.... imports
        github.com/prometheus/prometheus/discovery/config imports
        github.com/prometheus/prometheus/discovery/azure imports
        github.com/Azure/azure-sdk-for-go/arm/network: module github.com/Azure/azure-sdk-for-go@latest found (v54.2.0+incompatible), but does not contain package github.com/Azure/azure-sdk-for-go/arm/network 
```

**Comment by logston** [comment]
For reference, I've read through:
- https://github.com/prometheus/prometheus/issues/4468
- https://github.com/prometheus/prometheus/issues/8586
- https://github.com/prometheus/prometheus/issues/5590

I'm curious why `prometheus/discovery/azure` depends on `github.com/Azure/azure-sdk-for-go/arm/compute` when is no where to be found in the project.

**Comment by roidelapluie** [comment]
To build Prometheus, please clone the repository or run make build. go get does not fully respect the go.mod file (e.g. does not respect the `replace`). `go get` also does not build the UI.
Which version of go are you using?

**Comment by logston** [comment]
Thanks @roidelapluie. I'm not trying to run make or build Prometheus. Instead, we depend on it in our own repo. Eg.

```
import (
...
prom_config "github.com/prometheus/prometheus/config"
...
)
```
We are trying to use 2.26.0. We are upgrading from 2.13.0.

**Comment by roidelapluie** [comment]
In 2.26 github.com/prometheus/prometheus/config does not depend on azure (except for the tests).

**Comment by roidelapluie** [comment]
Which version of go are you using?

**Comment by logston** [comment]
Hmm, odd. Very curious why `go mod vendor` is finding a version of `github.com/prometheus/prometheus/discovery/config` that imports `github.com/prometheus/prometheus/discovery/azure`. 

We are running Go 1.15. 

I see a line like the following above:

```
go: found github.com/prometheus/prometheus/discovery/config in github.com/prometheus/prometheus v2.5.0+incompatible
```

Any reason why go would fetch `v2.5.0` if I've explicitly listed the SHA of 2.26.0 in our go.mod file? 

Thanks for all your help @roidelapluie.

**Comment by logston** [comment]
Ah, I see now. `go mod vendor` searches for and installs a version of promethues that has the directory path `github.com/prometheus/prometheus/discovery/config`, thus causing 2.5.0 to be installed. I thought that by pinning the version in my `go.mod` file, the correct version would be installed. After which I would be able to refactor my code. Instead, I must remove that import before running `go mod...`. My mistake. Thanks @roidelapluie.
