### ISSUE TITLE
Add a prod() or product() function

### ISSUE THREAD

**Issue by robinmarechal** [prometheus/prometheus#8830]
Currently working on a fully Prometheus/Grafana based monitoring infrastructure, we want/need to create high-level "health" metrics, based on lower level health metrics, themselves bases on more lower level health metrics, etc...

These "health" metrics should be between 0 and 1. A higher value meaning that the component is healthy, and a lower value that the component is unhealthy.

A simple average is not a good solution since a critical value would be masked by other values, especially if combining more than 3 or 4 values. For example, `avg(0.1, 0.8, 1.0, 0.9) = 0.7` => the value `0.1` has not enough impact on the result.

The best solution we found to combine these metrics is to use the Geometric Mean concept, which is basically the **_n_'th root of a product of _n_ elements**. A `geom_avg()` is probably not a good idea since the need is really specific. However, a `prod()` function might be more useful and would be enough to achieve our goal, combined with the power of a fraction (`^(1/n)`).

Moreover, I believe its implementation would be really simple, and could be useful to other users in their specific use-cases.

Any thought or remark will be appreciated!
Thanks.

**Comment by roidelapluie** [comment]
> The best solution we found to combine these metrics is to use the Geometric Mean concept.

Based on https://github.com/prometheus/prometheus/issues/438#issuecomment-81853784

@beorn7 :
> #599 will add `ln` and `exp`. So once that is in, you can write `exp(avg(ln(metric)))` for geometric mean and `exp(avg_over_time(ln(metric[10m])))` for geometric mean over time.

**Comment by beorn7** [comment]
@robinmarechal I hope that addresses your need.

Having said that, I have been thinking for a while how we could introduce custom PromQL functions and operators without polluting the common use cases and without encouraging too much obfuscation. This case here was easy as there is already a very reasonable work-around. However, we regularly get requests for many different interesting statistical techniques, and neither can we just add all those requested functions and operators, nor is it great to reject all those requests and just tell users to import the data into R or something via the HTTP API. But that's a bigger point to discuss at a future dev summit.

**Comment by robinmarechal** [comment]
@roidelapluie Oops, I didn't think of that solution. My maths skills are defintely getting rusted. Thanks!

@beorn7 Yep this totally addresses my needs. 

Actually I was thinking of custom PromQL functions and operators as well when I wrote my issue. But that was of course way too complex for my simple needs. 
If you ever find a way to implement that kind of feature, while keeping a high performant system, it would be dope. That would definitely be a killer feature.

Thanks to both of you!
