### ISSUE TITLE
When does Prometheus actually execute the storage.tsdb.retention.time or storage.tsdb.retention.size and remove old data?

### ISSUE THREAD

**Issue by brosev** [prometheus/prometheus#8835]
We currently have storage.tsdb.retention.time set to 26d but have data about that's 27-28 days old. It looks like eventually something is executed that removes the old data but I can't find what this is or how to configure it to happen more often. As it is the data grows for a couple of days before the task to remove data is actually executed, allowing data to grow well past the 26d retention time.

Also, we experimented with the retention size setting. We have about 8.8TB capacity and we set retention size to 8TB. But within hours of setting this our disk was full. I understand that we need to account for wal size and about 10% of our retention time (I believe that since we didnt set retention time, it should default to 15d?) but that should not have equaled 8TB of data. Why was older data not removed to account for retention size?

How can we make the task that removes old data happen more frequently?

We are on version 2.21.

Thanks!

**Comment by roidelapluie** [comment]
Size-based retention does not work in 2.21 due to a bug. It works in 2.22.1 onwards. Can you please update?

Regarding the retention time, this is the minimum that Prometheus will guaratee you, not the maximum. The maximum will depend on the blocks size.

**Comment by brosev** [comment]
@roidelapluie could you please elaborate on what you mean by "this is the minimum that Prometheus will guaratee you, not the maximum."

Just Curious, What is the best way to avoid filling up disk on 2.21? Considering there was a bug with the retention size setting.

Thanks!

**Comment by roidelapluie** [comment]
Avoid filling up the disk on 2.21 can be done by setting a time duration.

The minimum that Prometheus guarantees means that we will you might have access to a little more data that what you have in your retention config, because the data is per blocks that can span over multiple days.

I am closing this issue as it is for a fixed bug.

**Comment by brosev** [comment]
@roidelapluie Weve updated the version to:

prometheus, version 2.27.1 (branch: HEAD, revision: db7f0bcec27bd8aeebad6b08ac849516efa9ae02)
  build user:       root@fd804fbd4f25
  build date:       20210518-14:17:54
  go version:       go1.16.4
  platform:         linux/amd64

And still cannot get the the retention size setting working. We've set the retention size to 7500GB and as soon as we start up prometheus the data continues to climb without going down. We eventually need to revert the setting to use time rather than size. Is there something we're missing. We don't see related errors in the logs. Can you advise?

Thanks.
