### ISSUE TITLE
Linode Service Discovery Support

### ISSUE THREAD

**Issue by tjhop** [prometheus/prometheus#8843]
## Proposal
**Use case. Why is this important?**

At [Linode](https://www.linode.com/), we internally use a few custom adapters based around our configuration management system (SaltStack) to write out some basic scrape target configs for use with the file based service discovery. This has served us well for a few years, but we're starting to outgrow this internal system. We started reconsidering what a new service discovery system could look like for us internally, and realized there's no reason to keep it to ourselves, so we might as well contribute it upstream!

With that said, I have a commit with functional Linode APIv4 based service discovery and tests here:
https://github.com/tjhop/prometheus/commit/490f27b6ce6a36d421053b58fd7ee2db1a59f421

Reading through contributor docs indicates I should work based on issues, so figured I'd open one up to start that conversation. I'd be happy to PR if maintainers are willing to accept it.

**Comment by roidelapluie** [comment]
Yes, this seems reasonnable, I would maintain it. Is there a free tier we can use to play around the API's?

**Comment by roidelapluie** [comment]
Closed by #8846
