### ISSUE TITLE
Run CI jobs based on modified language

### ISSUE THREAD

**Issue by LeviHarrison** [prometheus/prometheus#8849]
## Proposal
**Use case. Why is this important?**

I've found myself working on UI changes, and although some do involve touching the backend, most end up being TS only. Each time I push a commit, the full suite of Go tests are run, and a bunch of builds on multiple platforms are generated, even though no Go code was actually touched. Take for example #8832, a purely TS-related PR. After pushing a series of mostly small refactoring changes this morning, a plethora of Go tests were run, and 66 executables of Prometheus and Promtool were generated. Out of all of this, only the few UI tests (in comparison to the Go tests) and a single build of the UI were actually needed. I propose we change the CI config to more selectively run jobs based on language to save resources and speed up checks.

**Comment by roidelapluie** [comment]
We still want to run the full tests but we would be interested into splitting the go tests and the ui tests in circleci.
