### ISSUE TITLE
Add custom labels to automatically generated series.

### ISSUE THREAD

**Issue by MarcSolde** [prometheus/prometheus#8865]
## Proposal
Let's assume a situation where we have N prometheus scrapping differents endpoints (there is no overlap), and said prometheus send the data to a single influxDB database, including the automatically generated series, such as scrape_samples_scrapped or scrape_duration_seconds. As far as I know, there is no way to add custom labels on those metrics to identify which prometheus send which time series(correct me if I'm wrong), so it would be pretty interesting to be able to do so, since we can already do so on scraped metrics by setting so on the config file (under job -> metric_relabel_config and adding a custom label there).

Thanks.

PS: Excuse my English, my level is not native.

**Comment by beorn7** [comment]
If you set `external_labels` in the `global` section of the config file, it should cover your use case. See https://prometheus.io/docs/prometheus/latest/configuration/configuration/#configuration-file

**Comment by MarcSolde** [comment]
It does, thanks!

Since this is already implemented, I'm closing the issue.
