### ISSUE TITLE
promtool does not accept names with dots for backfill

### ISSUE THREAD

**Issue by amnonh** [prometheus/prometheus#8866]
Using dot in a parameter name should be valid
**What did you do?**
I've used the following file (this is simplified version):
```
$ cat of.1.txt
# HELP disk.used disk used
# TYPE disk.used gauge
disk.used{instance="10.0.0.11",job="node_exporter",mountpoint="/var/lib/scylla" ,serverId="279"} 0.17906300289943433 1619542224.527
disk.used{instance="10.0.0.11",job="node_exporter",mountpoint="/var/lib/scylla" ,serverId="279"} 0.17906300289943433 1619542284.527
disk.used{instance="10.0.0.11",job="node_exporter",mountpoint="/var/lib/scylla" ,serverId="279"} 0.17906300289943433 1619542344.527
# EOF
```
and uploaded it with 
```
promtool tsdb create-blocks-from openmetrics /prometheus/data/of.1.txt /prometheus/data/
```
**What did you expect to see?**
it should have been loaded
**What did you see instead? Under which circumstances?**
getting min and max timestamp: next: expected text in HELP, got "INVALID"
**Environment**

* System information:

	insert output of `uname -srm` here

* Prometheus version:
```
prometheus, version 2.27.1 (branch: HEAD, revision: db7f0bcec27bd8aeebad6b08ac849516efa9ae02)
  build user:       root@fd804fbd4f25
  build date:       20210518-14:17:54
  go version:       go1.16.4
  platform:         linux/amd64
```

**Comment by roidelapluie** [comment]
https://prometheus.io/docs/concepts/data_model/

Dots are not allowed in metric names: the metric name may contain ASCII letters and digits, as well as underscores and colons. It must match the regex `[a-zA-Z_:][a-zA-Z0-9_:]*`

**Comment by roidelapluie** [comment]
Note: it is frequent to use `_` instead of `.`. It is also recommended to have the unit in the metric name (e.g. `disk_used_bytes`).
