### ISSUE TITLE
Timezone Support in promQL

### ISSUE THREAD

**Issue by roidelapluie** [prometheus/prometheus#8872]
Prometheus has multiple calendar functions.

I propose the addition of an optional var arg "timezone", which would look like:

`day_of_week(time(), "Europe/Brussels")`.

This would then return the day of the week for that unix timestamp in the Europe/Brussels timezone.

For windows compatibility, we should have a new flag in Prometheus that loads a timezone zip file.

The embedded timezone in go can not be used because it is outdated, and can not be updated easily by users. I would not offer it as an option, and I would not ship a current one. Instead, we should document properly how to fetch it.

**Comment by roidelapluie** [comment]
cc @fionera would you be interested by working on this?

**Comment by roidelapluie** [comment]
Let's also gather @juliusv input. The tricky point is that those calendar functions already have an optional parameter. Either we try to cast the first parameter as a string to see if it is a timezone, so we would allow time("Europe/Brussels"), or we force the first parameter (if even possible in promql parser?).

**Comment by juliusv** [comment]
I think @beorn7 has thought about this 100x more deeply in https://github.com/prometheus/prometheus/pull/8871#issuecomment-850584432 and his doc than I ever have or ever will do :) But generally timezones are "here be dragons" territory for me. From purely a language standpoint (assuming timezones were simple and that would work without problems), I would prefer a single offset function that can be composed with the others time functions. But @beorn7 raised the good point that functions that directly take a timezone can cover more cases correctly (though still not all).

In any case, *iff* we do anything in this direction, it definitely should be behind a feature flag. On a tangent I think that we should rename the `--enable-feature` flag to `--enable-experimental-feature` flag to make it 100% obvious to anyone using it that things not only may break / be removed, but are expected to.

**Comment by beorn7** [comment]
I'm not sure if the friction caused by changing `--enable-feature` to `--enable-experimental-feature` is worth the benefit, if there is benefit at all. We got the inspiration from K8s, and that's how it is done over there: https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/
Note that features go through well defined stages, but they don't have separate flags for those. That seems to have worked well so far.

**Comment by roidelapluie** [comment]
This is clearly a typo in my design doc

Le sam. 29 mai 2021 à 17:44, Björn Rabenstein ***@***.***> a
écrit :
