### ISSUE TITLE
max number of records returnable from prometheus

### ISSUE THREAD

**Issue by sksingh20** [prometheus/prometheus#8873]
**What did you do?**
Team, I have major issue on grafana dashboard which is increasing step size by itself resulting in substantial loss of data.
https://github.com/grafana/grafana/issues/34775

As per https://github.com/grafana/grafana/issues/34775 this is defect due to limitation of Prometheus where prometheus is making limit of 11K records.

Whereas I see no limitation of records in Prometheus documentation.
**What did you expect to see?**
No limitation of records. It should be limit of infrastructure or a configuration parameter configurable by adminsitartors.

**What did you see instead? Under which circumstances?**
https://github.com/grafana/grafana/issues/34775

**Environment**

* System information:

	insert output of `uname -srm` here

* Prometheus version:

	insert output of `prometheus --version` here

* Alertmanager version:

	insert output of `alertmanager --version` here (if relevant to the issue)

* Prometheus configuration file:
```
insert configuration here
```

* Alertmanager configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```

**Comment by roidelapluie** [comment]
Thanks for your interest in Prometheus and Grafana. This was extensively discussed in the linked grafana issue. I am going to close this on the Prometheus side.
