### ISSUE TITLE
Remove limitation of 11,000 points per timeseries

### ISSUE THREAD

**Issue by sksingh20** [prometheus/prometheus#8887]
**What did you do?** This related to Gauge data type. This is issue generated out of with closure of issue reported to Grafana. Grafana Team stated that issue is due to Prometheus.
Grafana Issue link:
Remove automatically increasing step value in Grafana dashboard for Gauge on more than 12 Hrs duration
https://github.com/grafana/grafana/issues/35065

Grafana team asked to raise issue with Prometheus team with following comment:
"Please raise this with the prometheus project: https://github.com/prometheus/prometheus/blob/39d79c3cfb86c47d6bc06a9e9317af582f1833bb/web/api/v1/api.go#L424"

**What did you expect to see?** There should not be limit enforced at product level (limitation of 11K records) which is causing substantial loss of data yielding wrong business decision. usages of Prometheus and Grafana becomes challange for CXO which is endup giving false data points because actual data is not returned. While data collected at 15 Sec scrap, data returned to dashboard with hours of interval. 

**What did you see instead? Under which circumstances?**
This is observed that crucial gauage data points lost when Grafana dashboard duration increased for more than 12 Hours.

Objective of dashboard is not only to show beautiful graphs but to show clear data pointers for status of servers and applications. Grafana team closed issue saying this is issue due to limitation at Prometheus. Due to limitation of records returned by Prometehus(11K records), grafana dashboard increasing step value causing substantial loss of data.

for six hour duration query is as follows:
url:"api/datasources/proxy/2/api/v1/query_range?query=IOT_Wstation%7Bparam%3D%22Power-Calc%22%2Cexported_instance%3D%2212%22%7D&start=1622040435&end=1622062035&step=15"

For 12Hour duration Grafa query is as follows:
url:"api/datasources/proxy/2/api/v1/query_range?query=IOT_Wstation%7Bparam%3D%22Power-Calc%22%2Cexported_instance%3D%2212%22%7D&start=1622018980&end=1622062180&step=20"

for 7 days duration Grafana query is as follows:
url:"api/datasources/proxy/2/api/v1/query_range?query=IOT_Wstation%7Bparam%3D%22Power-Calc%22%2Cexported_instance%3D%2212%22%7D&start=1621457100&end=1622061900&step=300"

for 30 days duration Grafana query is as follows:
url:"api/datasources/proxy/2/api/v1/query_range?query=IOT_Wstation%7Bparam%3D%22Power-Calc%22%2Cexported_instance%3D%2212%22%7D&start=1621457100&end=1622061900&step=3600"

Step Value increased to 3600 sec = 1 Hr.

**Environment** Grafana 7.3.4 Over Ubuntu

* System information:
	insert output of `uname -srm` here

* Prometheus version:

	insert output of `prometheus --version` here
Not Applicable. Repeatable issue upfront on all latest release.

* Alertmanager version:
	insert output of `alertmanager --version` here (if relevant to the issue)

* Prometheus configuration file:
```
insert configuration here
```
Not Applicable. Repeatable issue upfront.

* Alertmanager configuration file:
```
insert configuration here (if relevant to the issue)
```
Not Applicable. Repeatable issue upfront.

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```
Not Applicable. Repeatable issue upfront.

**Comment by roidelapluie** [comment]
That limit is there to protect Prometheus, and I do not really think it is realistic or useful to have more than this.

I do not think that a browser could generate a dashboard which is more than 11k metrics wide. Unless your browser has 11k pixels large (which I think is 3x 4k displays), you would be missing points anyway.

Am I missing something?

**Comment by roidelapluie** [comment]
Note that if you really want all the value, without functions, you can use: `my_metric[${__range_s}s]` as query in grafana and check the "instant" checkbox.

**Comment by sksingh20** [comment]
Please see how normal business use case look like. Which is also shown in default dashboard of Zabbix.

![image](https://user-images.githubusercontent.com/35199465/120593587-5ad76400-c45d-11eb-81bb-cbf7270747bf.png)

Business use case is to see status of server and application in duration to understand its status. Including month end loads, quarterly, half yearly and yearly statistics.

**Comment by sksingh20** [comment]
> That limit is there to protect Prometheus, and I do not really think it is realistic or useful to have more than this.
> 
> I do not think that a browser could generate a dashboard which is more than 11k metrics wide. Unless your browser has 11k pixels large (which I think is 3x 4k displays), you would be missing points anyway.
> 
> Am I missing something?

Objective is show clear view of data. This will be expertise and efficiency of visualization tool on how tool deal with high volume of data. We need to present clear view of data and dropping data at Prometheus level makes question on usefulness of tool itself.

**Comment by roidelapluie** [comment]
As far as I see, zabbix returns less than 900 points i your examples. The 11000 samples limit is not your issue I guess, as it is 10 times more than what you have provided as an example.

**Comment by sksingh20** [comment]
> As far as I see, zabbix returns less than 900 points i your examples. The 11000 samples limit is not your issue I guess, as it is 10 times more than what you have provided as an example.

Yes. I have given this feedback to grafana team that they are evn not utilizing 11K records, which whold atlest able to draw graph for about 45Hours at 15 sec scrap value.

But when it comes to weekly, monthly views data itself is not there which is blocked at Prometheus level. I do not see a restriction to apply at Prometheus level as use case of data will depend on business requirement and administrators to pick and choose to meet their individual business case.

**Comment by SuperQ** [comment]
Yes, there is a reason to limit API output. Unlimited API output leads to bad user experience. You are trying to do something that doesn't produce useful results. This is an [XY Problem](https://en.wikipedia.org/wiki/XY_problem).

You need to use PromQL to format the data in a way that is useful to display in Grafana. The Grafana team has provided extremely helpful functionality to make this work well.

For example, your query should probably be `avg_over_time(IOT_Wstation{param="Power-Calc",exported_instance="12"}[$__interval])`. This will make Grafana and Prometheus automatically scale the data to match the time width (step) of each pixel on the graph to the underlying data.

**Comment by SuperQ** [comment]
For questions/help/support please use our [community](https://prometheus.io/community/) channels. There are more people available to potentially respond to your request and the whole community can benefit from the answers provided.

**Comment by sksingh20** [comment]
@SuperQ What you mean by "Unlimited API output leads to bad user experience"? 
How that leads bad user experience?
Are you owning infrastructure deployed?
If there is limitation of the way Prometheus manage data?

This only gives view that prometheus is not ready for enterprise deployment and serious business cases.
You want to drive business and you are expecting business to change their thought and should not expect actual data. 

This point will be communicated to CXO community.

You are giving reason where Prometheus will be bottleneck and business need to seriously think on alternative solution.
Thank you for your looking on this request.

**Comment by sksingh20** [comment]
@SuperQ This is how graph is destroyed based on your suggestion of avg_over_time

![image](https://user-images.githubusercontent.com/35199465/120707103-8bf47a80-c4d7-11eb-94d9-b4f1b900fa72.png)
This ended with junk data

**Comment by SuperQ** [comment]
Prometheus is not your bottleneck. Your understanding of time-series data is the bottleneck.

Systems like Zabbix make naive decisions for you, which leads to incorrect data. Prometheus provides raw data calculations. You have to have a greater understanding of your data in order to use it correctly.

To use an analogy. Zabbix is a spreadsheet, Prometheus is an SQL database. You have to take more care in understanding in order to get the results you expect.
