### ISSUE TITLE
Configurabe scrape interval / scrape timeout via relabeling

### ISSUE THREAD

**Issue by roidelapluie** [prometheus/prometheus#8895]
As per dev summit:

```
CONSENSUS: We want to be able to configure scrape intervals via relabelling.
```

It means that each target can have its own scrape interval.

My proposal is:

- Enable dynamic scrape interval / timeout via relabeling.
- Scrape interval should be shown in the UI, maybe as a tooltip in the last scrape column.

Note: I have already implemented scrape_interval and scrape_timeout labels in https://github.com/prometheus/common/commit/3a13497dea8f64585868e4c4ad710735653d6344 to ease contributions.

**Comment by LeviHarrison** [comment]
I'm working on this.
