### ISSUE TITLE
Issue with running prometheus image with non-root user other than nobody 

### ISSUE THREAD

**Issue by avanichy25** [prometheus/prometheus#8901]
**What did you do?**
 I tried to create a docker file and added new user but i am getting error with prometheus 

```
msg="Error opening query log file" file=/prometheus/queries.active err="open /prometheus/queries.active: permission denied"
````

**What did you expect to see?**
Prometheus working with non-root user other than nobody when customizing the dockerfile.

**What did you see instead? Under which circumstances?**
Prometheus with customized image not working with user added in the dockerfile.

**Environment**

* System information:
`centos 8`
* Prometheus version:
`v2.22.2`
* Alertmanager version:
`v0.18.0`

* Prometheus configuration file:
Dockerfile
````FROM        quay.io/prometheus/busybox:latest
MAINTAINER  The Prometheus Authors <prometheus-developers@googlegroups.com>

COPY prometheus                             /bin/prometheus
COPY promtool                               /bin/promtool
COPY documentation/examples/prometheus.yml  /etc/prometheus/prometheus.yml
COPY console_libraries/                     /etc/prometheus/
COPY consoles/                              /etc/prometheus/
COPY LICENSE                                /LICENSE
COPY NOTICE                                 /NOTICE

RUN ln -s /usr/share/prometheus/console_libraries /usr/share/prometheus/consoles/ /etc/prometheus/
RUN mkdir -p /prometheus
RUN adduser -S xxxx -G root -D && chown -R xxxx:root /prometheus

USER       xxx
EXPOSE     9090
VOLUME     [ "/prometheus" ]
WORKDIR    /prometheus
ENTRYPOINT [ "/bin/prometheus" ]
CMD        [ "-config.file=/etc/prometheus/prometheus.yml", \
             "-storage.local.path=/prometheus", \
             "-web.console.libraries=/etc/prometheus/console_libraries", \
             "-web.console.templates=/etc/prometheus/consoles" ]
````
configuration:
image: prometheus:v2.22.2
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    restart: unless-stopped

**Comment by roidelapluie** [comment]
Thanks for your report. It looks as if this is actually a question about usage and not development.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) or our [forums](https://discuss.prometheus.io) rather than in a GitHub issue. In our [community channels](https://prometheus.io/community), more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
