### ISSUE TITLE
Should PromQL return answers when datapoints are far away from the boundaries?

### ISSUE THREAD

**Issue by roidelapluie** [prometheus/prometheus#8906]
This is a followup on #8905 to see if there is a need to change something in PromQL.

The issue is that when you run delta(foo[1d]), even you have only samples covering 30s, we would return an answer. This can be quite confusing.

The options would be:

- Make a minimal relative coverage required (e.g. datapoints should cover 75% of the range)?
- Make a minimal absolute coverage required?
- ....

I think if someone wants to pick this up, a design doc analyzing multiple possibilities and cases (e.g. very short/very long ranges, edge cases, no data in the middle etc) would be very welcome.

**Comment by ide-rea** [comment]
I think **delta[1d]** should return 0, if datapoints after extrapolating not equal to the boundaries. delta function is properly used for gauge metric, As the gauge metric can up and down, the very limited datapoints can't reflect the delta trend in the whole boundaries and  also cause some misunderstanding about the datapoints. This only my thoughts Thanks!

**Comment by beorn7** [comment]
The current behavior is deliberate, and it's actually very important if you aggregate the result of delta/increase/rate across many instances that come and go. A lot of thought was given to exactly the case where the data only covers a small fraction of the range.

Maybe there is need for another handling, but that needed a different syntax. Or we have to rethink the whole concept. This is what makes the whole topic so hard and interconnected. I guess this should be part of what was "decided" at the dev-summit: “We want to rethink this from first principles.” (But nothing has happened so far.)

**Comment by beorn7** [comment]
Hello from the bug scrub!

As said above, a solution to this should be part of an overarching concept how to address the various problems people have with delta/rate/increase. There are various design proposals floating around in various stages of maturity. This needs a deeper discussion, as alluded to at the dev summit, and keeping this individual issue open for a single aspect of that discussion is somewhat confusing. We'll close this, but keep it in mind for the solution to come.
