### ISSUE TITLE
Add Ingress Class to Ingress SD Config Meta Labels

### ISSUE THREAD

**Issue by Evesy** [prometheus/prometheus#8914]
## Proposal
The annotation `kubernetes.io/ingress.class` was adopted by many ingress controllers to assign ingresses to the desired controller. Using the Ingress prometheus discovery this can be used to filter scrapes to certain ingress classes using the annotation meta labels such as `__meta_kubernetes_ingress_annotation_kubernetes_io_ingress_class` which is very useful.

In our case we use it to perform blackbox monitoring against ingresses belonging to a certain class only (those that are public facing ingresses).

In Kubernets 1.18 that annotation has been [deprecated](https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/) in favour of a first class field in the ingress spec (`ingressClassName`). Migrating from using the annotation in ingresses to using the native field will result in users being unable to determine the ingresses class in the scrape config (unless additional custom annotations/labels are used)

It'd be incredibly useful to add an additional meta label like `__meta_kubernetes_ingress_class_name` if `ingessClassName` is present in the spec, similar to the existing ones for scheme and path

**Comment by brancz** [comment]
This makes a lot of sense. Would you like to contribute this addition?

**Comment by Evesy** [comment]
I'm making an attempt alongside raising this issue but Go is new to me so I'm not sure how far I'll get 😅

**Comment by roidelapluie** [comment]
That sounds awesome! We have weekly contributor hours where we can unblock you if needed: https://prometheus.io/community

**Comment by gouthamve** [comment]
Can this be closed given #8916?

**Comment by Evesy** [comment]
Closed via #8916
