### ISSUE TITLE
[FR] Dynamically registered scrapers via REST API

### ISSUE THREAD

**Issue by Diniboy1123** [prometheus/prometheus#8920]
## Proposal
**Use case. Why is this important?**
It has probably been asked before, though I couldn't find the thread. However I would find an opportunity such as adding scraper tasks via the already existing admin REST API extremely useful. For example I have a software that launches a ton of subprocesses and each would expose a metrics endpoint for Prometheus to scrape. Right now without a middleware like pushgateway or Consul it's really hard to add dynamically scalable metrics sources from applications. However with a rest api endpoint we could very easily tell Prometheus to query the specific host from now on for metrics.

Would there be any technical difficulty by implementing a system like that?

*“Nice to have” is not a good use case. :)*

**Comment by LeviHarrison** [comment]
The new generic HTTP SD (#8839) may help with this. It allows you to provide Prometheus with an endpoint containing any targets you want to be scraped, and you can dynamically update the list.

**Comment by Diniboy1123** [comment]
Looks great, yes. Thank you so much for this change to the contributors.

May I know when will this be pushed as a release?

**Comment by LeviHarrison** [comment]
v2.28.0 seems to be aimed for Wednesday of next week (6/16), although I can't guarantee it will happen exactly then.

https://github.com/prometheus/prometheus/blob/main/RELEASE.md
