### ISSUE TITLE
update the css but not working

### ISSUE THREAD

**Issue by CptJason** [prometheus/prometheus#893]
I have changed the css in file of  ./web/blob/static/css/prom_console.css, and then refreshed on the browser, but it did not work.
![image](https://cloud.githubusercontent.com/assets/397285/8665785/9578ed7e-2a1a-11e5-8575-63683b8ab03d.png)

**Comment by brian-brazil** [comment]
Run `make web` to rebuild the blobs, and then restart prometheus. You can also use `-web.use-local-assets` to read off the filesystem rather than the files embedded in prometheus.

**Comment by beorn7** [comment]
I assume this fixes the the issue. Please re-open if that's not the case...

**Comment by Christmas-shl** [comment]
I am sorry to tell this, I have done that,but it doesn`t work 
when i type "make web" it shows like:
make -C web
make[1]: Entering directory `/home/wowotuan/mydocker/gitrepository/prometheus/web'
TMPDIR=/tmp GOROOT=/home/wowotuan/mydocker/gitrepository/prometheus/.build/root/go GOPATH=/home/wowotuan/mydocker/gitrepository/prometheus/.build/root/gopath /home/wowotuan/mydocker/gitrepository/prometheus/.build/root/go/bin/go get github.com/jteeuwen/go-bindata/...
TMPDIR=/tmp GOROOT=/home/wowotuan/mydocker/gitrepository/prometheus/.build/root/go GOPATH=/home/wowotuan/mydocker/gitrepository/prometheus/.build/root/gopath /home/wowotuan/mydocker/gitrepository/prometheus/.build/root/go/bin/go generate ./blob
/home/wowotuan/mydocker/gitrepository/prometheus/.build/root/go/bin/gofmt -w -s=true blob/files.go
make[1]: Leaving directory `/home/wowotuan/mydocker/gitrepository/prometheus/web'

when i type "make -C web" ,it shows :

make: Entering directory `/home/wowotuan/mydocker/gitrepository/prometheus/web'
TMPDIR=/tmp GOROOT=/home/wowotuan/mydocker/gitrepository/prometheus/.build/root/go GOPATH=/home/wowotuan/mydocker/gitrepository/prometheus/.build/root/gopath /home/wowotuan/mydocker/gitrepository/prometheus/.build/root/go/bin/go get github.com/jteeuwen/go-bindata/...
TMPDIR=/tmp GOROOT=/home/wowotuan/mydocker/gitrepository/prometheus/.build/root/go GOPATH=/home/wowotuan/mydocker/gitrepository/prometheus/.build/root/gopath /home/wowotuan/mydocker/gitrepository/prometheus/.build/root/go/bin/go generate ./blob
/home/wowotuan/mydocker/gitrepository/prometheus/.build/root/go/bin/gofmt -w -s=true blob/files.go
make: Leaving directory `/home/wowotuan/mydocker/gitrepository/prometheus/web'
[3]+  Done                    nohup ./prometheus -config.file=./config/prometheus.yml

**Comment by brian-brazil** [comment]
In what way doesn't it work? That looks correct to me

**Comment by juliusv** [comment]
Yeah, the make output looks good. Or do the CSS changes still not take effect afterwards?
