### ISSUE TITLE
exemplar text parsing fails

### ISSUE THREAD

**Issue by clux** [prometheus/prometheus#8930]
**What did you do?**
- Modified the rust prometheus client library to export exemplars on histograms - https://github.com/tikv/rust-prometheus/pull/395
- Made sure it conforms to the  [openmetric spec on exemplars](https://github.com/OpenObservability/OpenMetrics/blob/main/specification/OpenMetrics.md#exemplars)
- Modified a rust program to use it, and add exemplars to its `/metrics` text output - https://github.com/clux/controller-rs/pull/12
- Configured prometheus 2.26 and 2.27 (tried both) to scrape the app
- Dumped metrics output from `curl 0.0.0.0:8080/metrics` to verify format:

```
# HELP foo_controller_handled_events handled events
# TYPE foo_controller_handled_events counter
foo_controller_handled_events 1
# HELP foo_controller_reconcile_duration_seconds The duration of reconcile to complete in seconds
# TYPE foo_controller_reconcile_duration_seconds histogram
foo_controller_reconcile_duration_seconds_bucket{le="0.01"} 1 # {trace_id="6c1011d34f17c4ca1177b40ddfb5184b"} 0.006
foo_controller_reconcile_duration_seconds_bucket{le="0.1"} 1
foo_controller_reconcile_duration_seconds_bucket{le="0.25"} 1
foo_controller_reconcile_duration_seconds_bucket{le="0.5"} 1
foo_controller_reconcile_duration_seconds_bucket{le="1"} 1
foo_controller_reconcile_duration_seconds_bucket{le="5"} 1
foo_controller_reconcile_duration_seconds_bucket{le="15"} 1
foo_controller_reconcile_duration_seconds_bucket{le="60"} 1
foo_controller_reconcile_duration_seconds_bucket{le="+Inf"} 1
foo_controller_reconcile_duration_seconds_sum 0.006
foo_controller_reconcile_duration_seconds_count 1
```

**What did you expect to see?**
Was expecting the exported metrics be parsed and appearing on prometheus.

**What did you see instead? Under which circumstances?**

Parse error from prometheus without a lot of context:
![Screenshot from 2021-06-12 20-44-17](https://user-images.githubusercontent.com/134092/121787632-0fd8f180-cbbf-11eb-9957-7a917a217517.png)
The same happens with or without an exemplar timestamp. Also tried varying the number of decimals in the exemplar value to no avail. It works when removing the exemplar part in the output.

**Environment**

`k3d` running `kube-prometheus-stack` (defaults config, but plus  `enableFeatures: [ "exemplar-storage"]` in `prometheusSpec`)

* System information:

Linux 5.12.7-arch1-1 x86_64

* Prometheus version:

```
$ kubectl exec prometheus-promstack-kube-prometheus-prometheus-0 -n monitoring -- prometheus --version
Defaulting container name to prometheus.
Use 'kubectl describe pod/prometheus-promstack-kube-prometheus-prometheus-0 -n monitoring' to see all of the containers in this pod.
prometheus, version 2.27.1 (branch: HEAD, revision: db7f0bcec27bd8aeebad6b08ac849516efa9ae02)
  build user:       root@fd804fbd4f25
  build date:       20210518-14:17:54
  go version:       go1.16.4
  platform:         linux/amd64
```

**Comment by clux** [comment]
Tried the newer version of `promtool` with `curl 0.0.0.0:8080/metrics | promtool check metrics` and getting:

```
error while linting: text format parsing error in line 6: expected integer as timestamp, got "#"
```

which is coming from this line:

```
foo_controller_reconcile_duration_seconds_bucket{le="0.01"} 1 # {trace_id="b5685aeb05d642a850078b0d798056a0"} 0.005
```

**Comment by clux** [comment]
same error also from example lines in the [openmetrics exemplar spec](https://github.com/OpenObservability/OpenMetrics/blob/main/specification/OpenMetrics.md#exemplars-1):

```sh
$ echo 'foo_bucket{le="1"} 11 # {trace_id="KOO5S4vxi0o"} 0.67' | promtool check metrics
error while linting: text format parsing error in line 1: expected integer as timestamp, got "#"
 $ promtool --version
promtool, version 2.27.1 (branch: HEAD, revision: db7f0bcec27bd8aeebad6b08ac849516efa9ae02)
  build user:       root@fd804fbd4f25
  build date:       20210518-14:17:54
  go version:       go1.16.4
  platform:         linux/amd64
```

**Comment by roidelapluie** [comment]
I think you try to add examplars to Prometheus Text Format.

Are you setting the correct content-type for OpenMetrics?

**Comment by clux** [comment]
...Ah. No. Sorry. :-(

I tried a bit now after setting `application/openmetrics-text; version=1.0.0; charset=utf-8`, plus some other minor changes like (`# EOF/n` ending), and it's now accepted by prometheus \o/

Is the the Prometheus Text Format not meant to support exemplars? Or is that reserved for OpenMetrics?
Would be great if the OpenMetrics format was parseable by `promtool` if this is the case.

At any rate, feel free to close as invalid. Thank you very much.

**Comment by roidelapluie** [comment]
We are not evolving the text format anymore, we want to promote OpenMetrics. If you plan for adding full openmetrics support for Rust, do not hesitate to reach for help. There are a few differences between both formats, and the library ideally would handle both (via negotiation in the headers).
