### ISSUE TITLE
Promtool should validate service discovery files

### ISSUE THREAD

**Issue by Khez** [prometheus/prometheus#8935]
## Proposal
Offer a way to validate [`json` and `yml` files loaded by `file_sd_configs`](https://github.com/prometheus/prometheus/blob/main/discovery/file/file.go#L391), either by:
- updating `promtool check config`
- adding a dedicated command `promtool check file_sd_configs`

A dedicated command would be better suited because [changing the targets list dynamically](https://prometheus.io/docs/guides/file-sd/#changing-the-targets-list-dynamically) does not require a prometheus restart/reload, meaning the files themselves are not required @ prometheus start.

## Situation
[promtool check config](https://github.com/prometheus/prometheus/blob/main/cmd/promtool/main.go#L332) validates that one or more files exist for a specific [file-sd](https://prometheus.io/docs/guides/file-sd/#installing-configuring-and-running-prometheus) configuration, but their contents are not checked.

There is no way to validate the files before publishing them.

The only way to detect the issues without checking the logs is adding an alert on `prometheus_sd_file_read_errors_total`.

## Example bad config that passes check config
`prometheus.yml`

```
scrape_configs:
  - job_name: 'node'
    file_sd_configs:
    - files: ['./service_discovery/node.yml']
```

`./service_discovery/node.yml`

```
- targets:
  - 127.0.0.1:9100
  labels: { example: nocomma between:labels }
```

## Current behaviour
Output of `promtool check config`
```
Checking prometheus.yml
  SUCCESS: 0 rule files found
```

If the file is missing, a warning is issues:
```
Checking prometheus.yml
  WARNING: file "service_discovery/node.yml" for file_sd in scrape job "node" does not exist
  SUCCESS: 0 rule files found
```

**Both scenarios currently have an exit code of 0.**

**Comment by LeviHarrison** [comment]
Something like this could also be extended to the new HTTP SD, and both could also be made available as a standalone command for those developing SD mechanisms.

**Comment by roidelapluie** [comment]
I would not go HTTP calls during check config, however checking the format of file_sd seems a good idea.

cc @dgl

**Comment by LeviHarrison** [comment]
I can work on this.

**Comment by Khez** [comment]
@roidelapluie @LeviHarrison can I help with the PR in any way ?

**Comment by LeviHarrison** [comment]
If you could test it out that'd be great! It's always good to get feedback.
