### ISSUE TITLE
No version v1.0.0 for linodego, getting error when trying to build

### ISSUE THREAD

**Issue by bogdandrutu** [prometheus/prometheus#8939]
github.com/linode/linodego@v1.0.0: reading github.com/linode/linodego/go.mod at revision v1.0.0: unknown revision v1.0.0

https://github.com/linode/linodego/tags

**Comment by roidelapluie** [comment]
Thanks, I have open https://github.com/prometheus/prometheus/pull/8941

**Comment by roidelapluie** [comment]
You can pull main again. I have also raised an issue upstream.
