### ISSUE TITLE
Promtool: Check service discovery command

### ISSUE THREAD

**Issue by LeviHarrison** [prometheus/prometheus#8968]
## Proposal

Add a `check sd` command, which takes `--config.file`, the Prometheus configuration file, `--job`, the service discovery job, and `--wait-time`, the time we allow to discover the targets.

```
promtool check sd --config.file=prometheus --job=prometheus --wait-time=5s
```

Discovery would then be performed as normal, relabeling would then be run, and the output would be printed.

(credit to @roidelapluie for the command syntax and the idea to use the existing discovery mechanisms)

**Use case. Why is this important?**

It could be useful for a user to quickly see what any SD is giving them, but especially with the introduction of the HTTP SD they'll be a lot more developers working on SD integrations, and this could make the development process easier.

**Comment by roidelapluie** [comment]
cc @dgl

**Comment by dgl** [comment]
@roidelapluie in your original proposal for this (https://github.com/prometheus/prometheus/pull/8950#discussion_r654402270) you kind of imply machine readable? The current PR from @darshanime has a human readable output, which I think is actually useful... but maybe we should add a `--yaml` flag or such?
