### ISSUE TITLE
HTTP SD: allow charset in content type

### ISSUE THREAD

**Issue by roidelapluie** [prometheus/prometheus#8971]
Currently the HTTP SD only allows application/json, exactly.

Since content type can also contain the charset : application/json;charset=utf8,
we could support it as well.

Note: only utf-8 is allowed.

Questions:

Which kind of spaces are allowed? Do we need regexes? Which other options could be set? Is there a way to decode that header in the std lib?

**Comment by roidelapluie** [comment]
According to RFC, the following are equivalent:

     text/html;charset=utf-8
     text/html;charset=UTF-8
     Text/HTML;Charset="utf-8"
     text/html; charset="utf-8"


I guess that will be a lot of fun to parse.

**Comment by LeviHarrison** [comment]
So we'll need to support:

```
 application/json;charset=utf-8
 application/json;charset=UTF-8
 Application/JSON;Charset="utf-8"
 application/jsonl; charset="utf-8"
```

and so on.

Is any random combination of capital and lowercase letters allowed?

**Comment by roidelapluie** [comment]
why jsonl;? typo?

Yes it is case insensitive as I understand it. just call .ToLower i guess.

**Comment by LeviHarrison** [comment]
Whoops typo. I can work on this.

Maybe just a regex idk

**Comment by roidelapluie** [comment]
`^(?i:application/json(;\s*charset=("utf-8"|utf-8))?)$` would do it.
