### ISSUE TITLE
backport: weird data suffix after backporting

### ISSUE THREAD

**Issue by stevekuznetsov** [prometheus/prometheus#8982]
I'm using the `promtool tsdb create-blocks-from openmetrics` command and generating data for this using Go and the model libraries. I generate series with 125 data points, aligned on the minute. I'm noticing when I backfill, start Prometheus and query for the data, there are always four extra data points appended to those that I've generated in code. Any ideas what might be causing this?

![Screenshot from 2021-06-22 20-06-51](https://user-images.githubusercontent.com/7328370/123029601-3b659400-d396-11eb-9143-b47234bf2c49.png)

In this screenshot you can see my random values generated at the minute, then at the end of the series, it "flat-lines" at the last value for four more data points.

cc @roidelapluie

**Comment by roidelapluie** [comment]
We do not insert "staleness markers" after the inserted data. There is no extra data, this is just due to the "lookback delta".

Learn more here: https://www.robustperception.io/staleness-and-promql
