### ISSUE TITLE
Rules silently ignored if one can't be found.

### ISSUE THREAD

**Issue by miekg** [prometheus/prometheus#899]
If you have a rule_files listing:
```
rule_files:
  - "/prometheus_config/bla.rules"
  - "/prometheus_config/bliep.rules
```
And ff the file `bla.rules` can't be found all rules are (silently ignored).

**Comment by fabxc** [comment]
What version are you running? In 0.14.0 you should get an error logged at least (reproduced it this way).

```
ERRO[0000] Error loading rules, previous rule set restored: open test/test.rules: no such file or directory
```

Do you not see this error?

Previous rule set is the empty one on startup.
 
In 0.15.0 it should error on reading bad rule files and exit if that happens on startup. Missing files are not errored on (to be a bit liberal as one might add them later and adding whole directories like `a/*.rules` is possible). Other files are still read.

The new `promtool` is actually errors during config checking if there is a non-glob file that does not exist. Having more strictness in this direction seems fine.

Is that more like the behavior you would expect?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [prometheus] Rules silently ign..." ]
>What version are you running? In 0.14.0 you should get an error logged at least (reproduced it this way).
>
>```
>ERRO[0000] Error loading rules, previous rule set restored: open test/test.rules: no such file or directory
>```
>
>Do you not see this error?

Yep, I see it.

>Previous rule set is the empty one on startup.

Hmmm, yes. Dropping all rules makes it easier to spot a bit one.

>In 0.15.0 it should error on reading bad rule files and exit if that happens on startup. Missing files are not errored on (to be a bit liberal as one might add them later and adding whole directories like `a/*.rules` is possible). Other files are still read.
>
>The new `promtool` is actually errors during config checking if there is a non-glob file that does not exist. Having more strictness in this direction seems fine.
>
>Is that more like the behavior you would expect?

Jep, what you describe for 0.15.0 is exactly what I am looking for.

Thanks!

/Miek

--
Miek Gieben
