### ISSUE TITLE
"Heisenberg" data gaps disappearing at different time ranges with the same step

### ISSUE THREAD

**Issue by arcivanov** [prometheus/prometheus#9001]
This is done via Grafana over the same data series. The same query, with same step over different time ranges produces either gaps or no gaps. The smaller range makes the gap disappear.

Graphs and queries are attached.

![gaps](https://user-images.githubusercontent.com/5355666/123552096-999dc880-d742-11eb-9548-5d68d603c566.png)

![no_gaps](https://user-images.githubusercontent.com/5355666/123552107-a15d6d00-d742-11eb-8d9e-cb4404c53ff2.png)

[gaps.txt](https://github.com/prometheus/prometheus/files/6721911/gaps.txt)

[no_gaps.txt](https://github.com/prometheus/prometheus/files/6721912/no_gaps.txt)

Federated Prometheus with Thanos is used. 

Prometheus Helm Chart 13.6.0

**Comment by roidelapluie** [comment]
Thanks for your report. It looks as if this is actually a question about usage and not development.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) or our [forums](https://discuss.prometheus.io) rather than in a GitHub issue. In our [community channels](https://prometheus.io/community), more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by arcivanov** [comment]
@roidelapluie How's it a "question" or about "usage"?? I'm reporting data inconsistencies in queries over the same period of data with the same step, which is clearly a bug. Please reopen.

**Comment by arcivanov** [comment]
The identical queries with identical steps respond with MISSING DATA depending on start/stop dates.

**Comment by roidelapluie** [comment]
If I look at the value:

            [
              1624747800,
              "0.009732573432704955"
            ],

            [
              1624747800,
              "0.011268470206515543"
            ],

You are more than probably not querying the same prometheus data. It makes me think that your datasource is not Prometheus, but thanos.

**Comment by arcivanov** [comment]
Specific gaps are:

```
            [
              1624742505,
              "0.02040816326530612"
            ],
            [
              1624742520,
              "0.02040816326530612"
            ],
            [
              1624742595,
              "0"
            ],
            [
              1624742610,
              "0"
            ],
```

**Comment by arcivanov** [comment]
@roidelapluie We are, you can compare the queries. But furthermore there are actual gaps and this behavior is ALWAYS reproducible. 

Once you find the gap at certain start/stop it never goes away at that time range. Once the gap disappears in a narrower window it also disappears for good.

**Comment by arcivanov** [comment]
>  It makes me think that your datasource is not Prometheus, but thanos.

We do use Prometheus with Thanos side-cars but the DSes are actually query frontends.

**Comment by roidelapluie** [comment]
Thank you.

I invite you to reach out to the thanos community: https://thanos.io/tip/contributing/community.md/
The query frontend is outsite of the Prometheus server scope.

**Comment by arcivanov** [comment]
Thanks, now it's clear.
