### ISSUE TITLE
Promtool: support rule evaluation command

### ISSUE THREAD

**Issue by yeya24** [prometheus/prometheus#9024]
## Proposal
**Use case. Why is this important?**

As a Prometheus user/SRE, I want to add some new alerting rules. But right now, there is not a good way to test these new rules against a running Prometheus. Compare to `promtool test rules` command, the rule evaluation command can specify the server address and evaluates the rules against that server. This is more like an E2E test rather than a unit test.

## Example usage

`promtool  rules <server> <rule-files-to-evaluate>`

## Possible implementation

Similar to `promtool tsdb create-blocks-from rules` command, this command can iterate through all rules in the rule files and perform instant queries against the server based on the given query expression. This goes through the `api/v1/query` API so `ALERTS` and `ALERTS_FOR_STATE` won't be written to TSDB.

**Comment by dgl** [comment]
It's an interesting idea and something I've thought about too, but really this direction leads to re-implementing Prometheus itself in promtool (rules that depend on each other need to be written to an underlying TSDB... how do you view the results? do you want a graph UI? etc...)

A way you can do this right now is write a minimal Prometheus config that points at another Prometheus through remote read, literally just this:
```yaml
remote_read:
  - url: http://prometheus.demo.do.prometheus.io/api/v1/read
    read_recent: true
rule_files:
  - the-extra-rules-you-want-test.yaml
```

Another idea that I quite like is making it easier to write rule tests, maybe a way to point at some data and generate the `input_series` based on that data (this gets into needing to understand relationships of rules and so on, e.g. https://github.com/vatine/promgraph type thing); that could be a tool that sits outside of prometheus itself and help with this kind of thing though.

**Comment by yeya24** [comment]
> It's an interesting idea and something I've thought about too, but really this direction leads to re-implementing Prometheus itself in promtool (rules that depend on each other need to be written to an underlying TSDB... how do you view the results? do you want a graph UI? etc...)

We can do it in a simple way and I think it is okay to not handle recording rules and these dependencies. Instant query for rules expr would be good enough.

**Comment by roidelapluie** [comment]
... which we already support in promtool

**Comment by roidelapluie** [comment]
and in the prometheus UI

**Comment by roidelapluie** [comment]
This seems like

https://github.com/prometheus/prometheus/pull/4277
https://github.com/prometheus/prometheus/issues/1220
https://github.com/prometheus/prometheus/issues/1154

WDYT?

**Comment by yeya24** [comment]
@roidelapluie Thanks, I see. Yeah, there is some overlapping here

**Comment by beorn7** [comment]
Hello from the bug scrub!

3y later… Since nothing has happened here to further flesh out what to do here concretely, we'll close this now. Please refer to the other issues for related topics that are probably more concrete feature requests to implement.

Feel free to follow up with contrary evidence.
