### ISSUE TITLE
Invalid ClientAuth: RequireAnyClientCert

### ISSUE THREAD

**Issue by toymachiner62** [prometheus/prometheus#9066]
**What did you do?**
Added a `web-config.yml` with these contents:

```
tls_server_config:
  cert_file: /prometheus/my.crt
  key_file: /prometheus/my.key
  client_auth_type: RequireAnyClientCert
```

**What did you expect to see?**

Prometheus server start

**What did you see instead? Under which circumstances?**

The error 
```
msg="Unable to validate web configuration file" err="Invalid ClientAuth: RequireAnyClientCert"
```

**Environment**
Docker

* Prometheus version:

2.28.1

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```
```
docker run -e STAGE=test prometheus  
level=info ts=2021-07-08T01:42:15.304Z caller=main.go:389 msg="No time or size retention was set so using the default time retention" duration=15d
level=info ts=2021-07-08T01:42:15.305Z caller=main.go:443 msg="Starting Prometheus" version="(version=2.28.1, branch=HEAD, revision=b0944590a1c9a6b35dc5a696869f75f422b107a1)"
level=info ts=2021-07-08T01:42:15.305Z caller=main.go:448 build_context="(go=go1.16.5, user=root@2915dd495090, date=20210701-15:20:10)"
level=info ts=2021-07-08T01:42:15.305Z caller=main.go:449 host_details="(Linux 5.10.25-linuxkit #1 SMP Tue Mar 23 09:27:39 UTC 2021 x86_64 d48d45e2a1ef (none))"
level=info ts=2021-07-08T01:42:15.305Z caller=main.go:450 fd_limits="(soft=1048576, hard=1048576)"
level=info ts=2021-07-08T01:42:15.305Z caller=main.go:451 vm_limits="(soft=unlimited, hard=unlimited)"
level=info ts=2021-07-08T01:42:15.307Z caller=web.go:541 component=web msg="Start listening for connections" address=0.0.0.0:9090
level=error ts=2021-07-08T01:42:15.308Z caller=main.go:659 msg="Unable to validate web configuration file" err="Invalid ClientAuth: RequireAnyClientCert"
```

**Comment by toymachiner62** [comment]
The documentation https://prometheus.io/docs/prometheus/latest/configuration/https/ says

```
# Server policy for client authentication. Maps to ClientAuth Policies.
# For more detail on clientAuth options:
# https://golang.org/pkg/crypto/tls/#ClientAuthType
[ client_auth_type: <string> | default = "NoClientCert" ]
```
and when I go to https://golang.org/pkg/crypto/tls/#ClientAuthType `RequireAnyClientCert` is one of the options.

**Comment by LeviHarrison** [comment]
I can confirm this issue, although I have no idea why it happens. All the other types work fine except this particular one, and it's been around for a decade so I don't think it's versioning.

**Comment by roidelapluie** [comment]
Because: https://github.com/prometheus/exporter-toolkit/blob/e283c808ff59be37bfa81cdab57c67e8993d365a/web/tls_config.go#L154

We should add the method but make it clear in the documentation that only RequireAndVerifyClientCert provides security.

**Comment by toymachiner62** [comment]
In my case i'm trying to only allow traffic over TLS but am fine with self signed certs.

**Comment by roidelapluie** [comment]
RequireAndVerifyClientCert works with self signed certs; you just need to add the cert as CA

**Comment by LeviHarrison** [comment]
Still needs an upgrade and docs fix, I can handle that
