### ISSUE TITLE
remote-write: don't stall on garbageCollectSeries()

### ISSUE THREAD

**Issue by bboreham** [prometheus/prometheus#9082]
I observed periodic peaks in send lag (`prometheus_remote_storage_highest_timestamp_in_seconds - prometheus_remote_storage_queue_highest_sent_timestamp_seconds`:

![image](https://user-images.githubusercontent.com/8125524/123937391-048f0f80-d98e-11eb-9ce0-c2804ab194bb.png)

The timing coincides with creating a checkpoint.

After studing many goroutine dumps, I formed the opinion that `Watcher.readCheckpoint()` can hold the `QueueManager.seriesMtx` lock for extended periods:

```
1 @ 0x250f27a 0x2515e16 0x2515810 0x23d2984 0x23d337f 0x23d2025 0x23d42e5 0x472101
#	0x250f279	github.com/prometheus/prometheus/storage/remote.(*pool).intern+0x339			/app/storage/remote/intern.go:57
#	0x2515e15	github.com/prometheus/prometheus/storage/remote.(*QueueManager).internLabels+0xf5	/app/storage/remote/queue_manager.go:696
#	0x251580f	github.com/prometheus/prometheus/storage/remote.(*QueueManager).StoreSeries+0x26f	/app/storage/remote/queue_manager.go:649
#	0x23d2983	github.com/prometheus/prometheus/tsdb/wal.(*Watcher).readSegment+0x743			/app/tsdb/wal/watcher.go:485
#	0x23d337e	github.com/prometheus/prometheus/tsdb/wal.(*Watcher).readCheckpoint+0x41e		/app/tsdb/wal/watcher.go:585
#	0x23d2024	github.com/prometheus/prometheus/tsdb/wal.(*Watcher).garbageCollectSeries+0x5a4		/app/tsdb/wal/watcher.go:457
#	0x23d42e4	github.com/prometheus/prometheus/tsdb/wal.(*Watcher).watch.func1+0x84			/app/tsdb/wal/watcher.go:375
```

Holding the lock prevents `QueueManager.Append()` from running so no new data is added to outgoing queues.

```
1 @ 0x43af05 0x44cbe5 0x44cbce 0x46e0e7 0x47d165 0x251485a 0x2514389 0x23d2577 0x23d130e 0x23cffd2 0x23cf61a 0x472101
#	0x46e0e6	sync.runtime_SemacquireMutex+0x46						/usr/local/go/src/runtime/sema.go:71
#	0x47d164	sync.(*Mutex).lockSlow+0x104							/usr/local/go/src/sync/mutex.go:138
#	0x2514859	sync.(*Mutex).Lock+0x579							/usr/local/go/src/sync/mutex.go:81
#	0x2514388	github.com/prometheus/prometheus/storage/remote.(*QueueManager).Append+0xa8	/app/storage/remote/queue_manager.go:503
#	0x23d2576	github.com/prometheus/prometheus/tsdb/wal.(*Watcher).readSegment+0x336		/app/tsdb/wal/watcher.go:510
#	0x23d130d	github.com/prometheus/prometheus/tsdb/wal.(*Watcher).watch+0xaad		/app/tsdb/wal/watcher.go:414
#	0x23cffd1	github.com/prometheus/prometheus/tsdb/wal.(*Watcher).Run+0x711			/app/tsdb/wal/watcher.go:255
#	0x23cf619	github.com/prometheus/prometheus/tsdb/wal.(*Watcher).loop+0x139			/app/tsdb/wal/watcher.go:204
```

(these are from `version=2.28.1, branch=HEAD, revision=b0944590a1c9a6b35dc5a696869f75f422b107a1`)

As I understand it, `StoreSeries()` will be called with all series from one target, so potentially hundreds of thousands.  Perhaps it should yield the lock every 100 series, something like that?

While I'm here, I would like to question this comment
https://github.com/prometheus/prometheus/blob/14b24d15b0977772c6343fa569c38fd2a078fa16/storage/remote/queue_manager.go#L657-L659
Won't the garbage-collection process result in _every_ active series being replaced?
And if I'm right about that, why bother re-interning and releasing all the labels?

**Comment by cstyan** [comment]
`Perhaps it should yield the lock every 100 series, something like that?` 

This sounds like it's worth trying, if we can prove doing so still results in all the correct data being sent over remote write (see my comment on your PR regarding series reference IDs)

**Comment by rfratto** [comment]
> Perhaps it should yield the lock every 100 series, something like that?
> Won't the garbage-collection process result in every active series being replaced?
> And if I'm right about that, why bother re-interning and releasing all the labels?

From what I can tell, there's no reason to reprocess the labels at all if `StoreSeries` is being called from reading a checkpoint, and is the only reason the lock needs to be held.

Maybe there could be a third method, `UpdateSeriesSegment`, that is called only when reading checkpoints and doesn't need to grab the lock?

**Comment by bboreham** [comment]
I think at the moment `seriesMtx` is also protecting `seriesSegmentIndexes`, but I don't see an obstacle to adding another lock, then `SeriesReset()` could take both.

**Comment by rfratto** [comment]
Hmm, I'm not 100% sure about that, it looks like it's only referenced from StoreSeries and SeriesReset which can't be called concurrently. Might be better to have a second mutex for it regardless, though.

**Comment by bboreham** [comment]
At this point I'm tempted to say that `seriesSegmentIndexes` should move out of `QueueManager` up to `Watcher`.
It seems an uneasy relationship that `StoreSeries()` and `SeriesReset()` rely on being called in a particular way to maintain it.

**Comment by cstyan** [comment]
> Based on that, maybe there could be a third method, UpdateSeriesSegment, that is called only when reading checkpoints and doesn't need to grab the lock? (Perhaps it could also fall back to StoreSeries if for some reason the series really doesn't exist.)

This is what I was going to suggest.

**Comment by bboreham** [comment]
Given a separate method to read segments and call `UpdateSeriesSegment`, do you think it should still increment `prometheus_wal_watcher_records_read_total` ? The current behaviour strikes me as a little confusing.

**Comment by bboreham** [comment]
> StoreSeries and SeriesReset which can't be called concurrently

I think they can - `garbageCollectSeries()` is set off on its own goroutine, calling both, while `Watcher.watch()` carries on calling `StoreSeries()` on a ticker.

I implemented `UpdateSeriesSegment` with a separate lock - see #9109.
