### ISSUE TITLE
[Feature] alertmanager received alerts can be configured 

### ISSUE THREAD

**Issue by clyang82** [prometheus/prometheus#9090]
## Proposal
**Use case. Why is this important?**

Follow this [document](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#alertmanager_config), I can be able to specify the alertmanager the prometheus server sends alerts to. But I cannot configure some filters or matchers that just send the desired alerts. for example: I have 2 alertmanagers configured to receive the alerts from prometheus server. one is in-cluster alertmanager instance. the other is external alertmanager instance. I want to filter out some alerts in the external alertmanager. e.g.: `watchdog` etc. w/o this feature, it will have many alerts considered that 1000+ prometheus instances send alerts to a central external alertmanager. Thanks.

*“Nice to have” is not a good use case. :)*

**Comment by clyang82** [comment]
we can use `drop` action of https://prometheus.io/docs/prometheus/latest/configuration/configuration/#alert_relabel_configs to filter out alerts.

**Comment by roidelapluie** [comment]
it seems that you have found the solution. Indeed, you should use alert_relabel_configs `drop` for this use case, or `keep`.
