### ISSUE TITLE
Unable to query some metrics

### ISSUE THREAD

**Issue by Spiroman** [prometheus/prometheus#9099]
**What did you do?**
Queried a metric we have like so `autoPostFlow{error!~".+"}` and got over 500 results
**What did you expect to see?**
I expected to get **nothing**, this metric (autoPostFlow) always has an error label filled
**What did you see instead? Under which circumstances?**
I got over 500 entries which is unusual since I'm matching all metrics in which the error label is empty

<img width="809" alt="Screen Shot 2021-07-18 at 18 51 58" src="https://user-images.githubusercontent.com/6946401/126073749-a8976b7d-9ee1-4d36-8a03-e4f890f1ddfb.png">

The weirdest part is that I am unable to query any of the results I get, be it with some regex, or directly. 
Below are two images, one showing result (partial) of `autoPostFlow{error!~".+"}`, the other a query with the exact fields from the result above.

![Screen Shot 2021-07-18 at 18 59 39](https://user-images.githubusercontent.com/6946401/126074060-6daa0e17-2375-4ddc-bb75-77d9d4b3eb25.png)

An example of not being able to query field directly:

![Screen Shot 2021-07-18 at 19 00 04](https://user-images.githubusercontent.com/6946401/126074066-f3314c00-fc22-425d-baa9-4d79fd3b5e0a.png)

I have tried the playing with the regex, querying only parts of the error label, but to no avail, there are just those 500 something entries which I'm unable to query.

I also made sure that they are not part of the result I'm querying already (I'm using this query elsewhere `sum(autoPostFlowError{error=~".+"})`)  by running this simple calculation/query:
`sum(autoPostFlowError) - sum(autoPostFlowError{error=~".+"}) - sum(autoPostFlowError{error!~".+"})` and seeing the results is 0. (the result for `sum(autoPostFlowError{error!~".+"})` != 0)

**Environment**

* Prometheus version:

	We're using the following prometheus image: quay.io/prometheus/prometheus:v2.13.1

* Prometheus configuration file:
[link to prom confing](https://gist.github.com/Spiroman/d3a397332df5622edfefb9390a81e6ab)

**Comment by codesome** [comment]
Do those errors contain newlines? `!=".+"` seems to be working fine. Note that `.` does not match newline in regex.

That said, it is not a good idea to have such descriptive errors as label values since they seems to have a lot of dynamic values (and is too big of a value).

**Comment by Spiroman** [comment]
At least two types of the repeating error (~450 time series) do not contain the newline character.

`!~".+"` Shouldn't this return nothing, since all of the time series have a non empty error label?
Also, regardless of the regex matching, shouldn't searching for a result element directly at least return said element?
Would it help you if I pasted some of those errors?

Thanks for pointing out the descriptive labels issue, we'll avoid this in future metrics.

**Comment by codesome** [comment]
@Spiroman what does `count(autoPostFlow{error=~".*\n(.|\n)*"}))` give you?

**Comment by Spiroman** [comment]
@codesome no data
![Screen Shot 2021-07-20 at 10 34 24](https://user-images.githubusercontent.com/6946401/126280656-4ea75680-8613-4b26-9768-228520bcf8da.png)

**Comment by roidelapluie** [comment]
Can you please try `autoPostFlow{error=~"^(?s:.+)$"}`?

I have already noticed that the UI does not render newlines in labels but there is no real good solution for this.

**Comment by Spiroman** [comment]
@roidelapluie No data
<img width="1274" alt="Screen Shot 2021-07-28 at 13 20 00" src="https://user-images.githubusercontent.com/6946401/127390223-d0dbc0bc-0e85-4f45-aa0c-cb246145729b.png">

**Comment by roidelapluie** [comment]
Could you send us an example http result with the examples? That could show us which chars cause issues.

**Comment by Spiroman** [comment]
@roidelapluie Sorry, but I'm not sure I understand what you want me to send you. 
Could you be more specific?

**Comment by roidelapluie** [comment]
The HTTP requests/responses (like tyou get with F12  - developers tools in the browser)
