### ISSUE TITLE
documentation improvement: document start/stop being inclusive

### ISSUE THREAD

**Issue by gabor** [prometheus/prometheus#9100]
when looking at the http api documentation for range queries https://prometheus.io/docs/prometheus/latest/querying/api/#range-queries the documentation does not say if the `start` and `end` timestamps are included in the range or not. my understanding is that they are included (meaning `start <= x <= end`), it would be nice to mention this in the documentation.

**Comment by roidelapluie** [comment]
Thanks for your report.

cc @RichiH WDYT?

**Comment by RichiH** [comment]
Makes sense, see PR. Thanks @gabor !
