### ISSUE TITLE
Memory leak in samples deletion procedure

### ISSUE THREAD

**Issue by timofey-barmin** [prometheus/prometheus#9108]
Edits by @codesome:
Actions to be taken
1. [low hanging fruit] Call Delete() on Head only if delete time ranges overlap with it ([code reference](https://github.com/prometheus/prometheus/blob/24165adadc889131dbd0143b5c16cd3a079e46cd/tsdb/db.go#L1662-L1664))
2. [low hanging fruit] Head GC to also GC tombstones ([code reference](https://github.com/prometheus/prometheus/blob/24165adadc889131dbd0143b5c16cd3a079e46cd/tsdb/head.go#L1740))
3. [not really a low hanging fruit] Clean tombstones API to also clean tombstones from the Head (TBD if it is worth it, need to look for any historical reasons or if it is a regression. Not a requirement to fix this leak.)

---

**What did you do?**

Context:
Basically we are trying to downsample the data. In order to reduce disk space consumption (we have pretty strict disk space limits for stats), we are "decimating" samples. In other words we are removing samples as they got older, but not all of them but we leave some samples there to have a longer history.

We implemented the described above thing by calling the /delete_series endpoint every minute with a specific `start` and `end` for all the metrics.

**What did you expect to see?**

We expected to see lower disk space usage with longer stats history and stable (flat) memory consumption. 

**What did you see instead? Under which circumstances?**

Prometheus instance consumes more and more memory and eventually gets killed due to OOM after a few days of work. If I disable the "decimation" procedure (stop calling the /delete_series basically), the problem disappears and memory consumption plateaus.

On the staging instance in the aws we see it consumes roughly 3-4G per day and crashes at 25G. Number of time series there: 30819. 
<img width="1707" alt="Screen Shot 2021-07-21 at 11 07 46 AM" src="https://user-images.githubusercontent.com/3727395/126539187-8bbd8878-c04f-4309-8dbc-1b19ff53c1e9.png">

I reproduced it locally on mac by the following simple script:
```
$ cat ~/test/mem_issue.sh
#!/bin/bash
set -e

while true; do
  timestamp=`date +"%s"`
  startts="$((timestamp - 60))"
  endts="$((timestamp - 52))"
  url="http://localhost:9090/api/v1/admin/tsdb/delete_series?match[]={instance=\"localhost:9090\"}&start=$startts&end=$endts"
  echo "$url"
  curl -X POST -g "$url"
  sleep 10
done
```

After one day of this script running the difference in mem consumption can be seen clearly:

With periodic deletions:
<img width="798" alt="Screen Shot 2021-07-21 at 11 21 23 AM" src="https://user-images.githubusercontent.com/3727395/126539982-48c5c3e8-a580-41b5-aa21-7d2cab67e42e.png">

Without deletions:
<img width="820" alt="Screen Shot 2021-07-21 at 11 20 45 AM" src="https://user-images.githubusercontent.com/3727395/126540019-6d6aa1ee-a00e-41c2-8674-0a5bbfb62a6a.png">

**Environment**

It reproduced on aws linux and on darwin. It seems like it does not depend on the env much.

* System information:

```
$ uname -srm
Darwin 19.6.0 x86_64

```

* Prometheus version:

```
prometheus, version 2.27.1 (branch: HEAD, revision: db7f0bcec27bd8aeebad6b08ac849516efa9ae02)
  build user:       root@bb2fc99061d0
  build date:       20210518-14:07:30
  go version:       go1.16.4
  platform:         darwin/amd64

```
	
* Prometheus configuration file:

Our staging instance has more complicated config but it can be reproduced on the simplest config like this (but it takes longer time as the number of metrics is lower):

```
$ cat prometheus.yml
global:
  scrape_interval:     1s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']

```

* Logs:

On staging where it crashed because of OOM the last logs were:
```
57255 level=info ts=2021-07-15T10:16:44.792Z caller=compact.go:494 component=tsdb msg="write block" mint=1626220800000 maxt=1626285600000 ulid=01FAMTP8Y0X5RGTYZ5DAT4K5Y6 duration=1.59143539s
57256 level=info ts=2021-07-15T10:16:45.625Z caller=compact.go:494 component=tsdb msg="write block" mint=1626307200000 maxt=1626328800000 ulid=01FAMTPAFRPRE5QDBG2DAW9QQH duration=833.052171ms
57257 level=info ts=2021-07-15T10:16:46.246Z caller=compact.go:494 component=tsdb msg="write block" mint=1626328800000 maxt=1626336000000 ulid=01FAMTPB9SJ22GRQBDGR9VVD5K duration=620.793956ms
57258 level=info ts=2021-07-15T10:16:46.253Z caller=db.go:1152 component=tsdb msg="Deleting obsolete block" block=01FAMTMGQ540BPX3TDP3Q9HBV5
57259 level=info ts=2021-07-15T10:16:46.270Z caller=db.go:1152 component=tsdb msg="Deleting obsolete block" block=01FAMTMEB34YNCG5XZ2VKYBK8Z
57260 level=info ts=2021-07-15T10:16:46.277Z caller=db.go:1152 component=tsdb msg="Deleting obsolete block" block=01FAMTMFWT0WHKWWN76BR0GVEK
57261 level=info ts=2021-07-15T10:17:44.757Z caller=compact.go:494 component=tsdb msg="write block" mint=1626220800000 maxt=1626285600000 ulid=01FAMTR3GW7WWJGKNF37FDXK60 duration=1.560656142s
57262 level=info ts=2021-07-15T10:17:45.579Z caller=compact.go:494 component=tsdb msg="write block" mint=1626307200000 maxt=1626328800000 ulid=01FAMTR51NKY7WPP56W2201MMV duration=821.192934ms
57263 level=info ts=2021-07-15T10:17:46.160Z caller=compact.go:494 component=tsdb msg="write block" mint=1626328800000 maxt=1626336000000 ulid=01FAMTR5VBSYVN4G5XEWFRXZPZ duration=581.230981ms
57264 level=info ts=2021-07-15T10:17:46.166Z caller=db.go:1152 component=tsdb msg="Deleting obsolete block" block=01FAMTPB9SJ22GRQBDGR9VVD5K
57265 level=info ts=2021-07-15T10:17:46.173Z caller=db.go:1152 component=tsdb msg="Deleting obsolete block" block=01FAMTPAFRPRE5QDBG2DAW9QQH
57266 level=info ts=2021-07-15T10:17:46.190Z caller=db.go:1152 component=tsdb msg="Deleting obsolete block" block=01FAMTP8Y0X5RGTYZ5DAT4K5Y6
57267 level=info ts=2021-07-15T10:18:46.004Z caller=compact.go:494 component=tsdb msg="write block" mint=1626220800000 maxt=1626285600000 ulid=01FAMTSZAK06BNTRBMA8XSGHXH duration=1.569405117s
57268 level=info ts=2021-07-15T10:18:46.826Z caller=compact.go:494 component=tsdb msg="write block" mint=1626307200000 maxt=1626328800000 ulid=01FAMTT0VNVMV2149RSNW0M4GW duration=821.47751ms
57269 level=info ts=2021-07-15T10:18:47.407Z caller=compact.go:494 component=tsdb msg="write block" mint=1626328800000 maxt=1626336000000 ulid=01FAMTT1NAT3G7FPGE729R1PBR duration=580.965225ms
57270 level=info ts=2021-07-15T10:18:47.416Z caller=db.go:1152 component=tsdb msg="Deleting obsolete block" block=01FAMTR51NKY7WPP56W2201MMV
57271 level=info ts=2021-07-15T10:18:47.420Z caller=db.go:1152 component=tsdb msg="Deleting obsolete block" block=01FAMTR5VBSYVN4G5XEWFRXZPZ
57272 level=info ts=2021-07-15T10:18:47.436Z caller=db.go:1152 component=tsdb msg="Deleting obsolete block" block=01FAMTR3GW7WWJGKNF37FDXK60
57273 fatal error: runtime: out of memory
```
Let me know we you need stacktraces that are printed right after the `out of memory` error.

Locally (I didn't wait long enough for it to crash) but logs look pretty ok to me:
```

level=info ts=2021-07-21T01:56:06.249Z caller=main.go:426 msg="Starting Prometheus" version="(version=2.27.1, branch=HEAD, revision=db7f0bcec27bd8aeebad6b08ac849516efa9ae02)"
level=info ts=2021-07-21T01:56:06.249Z caller=main.go:431 build_context="(go=go1.16.4, user=root@bb2fc99061d0, date=20210518-14:07:30)"
level=info ts=2021-07-21T01:56:06.249Z caller=main.go:432 host_details=(darwin)
level=info ts=2021-07-21T01:56:06.249Z caller=main.go:433 fd_limits="(soft=256, hard=unlimited)"
level=info ts=2021-07-21T01:56:06.249Z caller=main.go:434 vm_limits="(soft=unlimited, hard=unlimited)"
level=info ts=2021-07-21T01:56:06.253Z caller=web.go:540 component=web msg="Start listening for connections" address=127.0.0.1:9090
level=info ts=2021-07-21T01:56:06.254Z caller=main.go:803 msg="Starting TSDB ..."
level=info ts=2021-07-21T01:56:06.254Z caller=tls_config.go:191 component=web msg="TLS is disabled." http2=false
level=info ts=2021-07-21T01:56:06.259Z caller=head.go:741 component=tsdb msg="Replaying on-disk memory mappable chunks if any"
level=info ts=2021-07-21T01:56:06.297Z caller=head.go:755 component=tsdb msg="On-disk memory mappable chunks replay completed" duration=38.613571ms
level=info ts=2021-07-21T01:56:06.298Z caller=head.go:761 component=tsdb msg="Replaying WAL, this may take a while"
level=info ts=2021-07-21T01:56:06.503Z caller=head.go:813 component=tsdb msg="WAL segment loaded" segment=0 maxSegment=1
level=info ts=2021-07-21T01:56:06.503Z caller=head.go:813 component=tsdb msg="WAL segment loaded" segment=1 maxSegment=1
level=info ts=2021-07-21T01:56:06.503Z caller=head.go:818 component=tsdb msg="WAL replay completed" checkpoint_replay_duration=114.193µs wal_replay_duration=205.739985ms total_replay_duration=244.517237ms
level=info ts=2021-07-21T01:56:06.505Z caller=main.go:828 fs_type=19
level=info ts=2021-07-21T01:56:06.505Z caller=main.go:831 msg="TSDB started"
level=debug ts=2021-07-21T01:56:06.505Z caller=main.go:832 msg="TSDB options" MinBlockDuration=2h MaxBlockDuration=31d MaxBytes=1GiB NoLockfile=false RetentionDuration=1y WALSegmentSize=0B AllowOverlappingBlocks=false WALCompression=true
level=info ts=2021-07-21T01:56:06.505Z caller=main.go:957 msg="Loading configuration file" filename=./prometheus.yml
level=debug ts=2021-07-21T01:56:06.534Z caller=manager.go:195 component="discovery manager scrape" msg="Starting provider" provider=static/0 subs=[prometheus]
level=info ts=2021-07-21T01:56:06.534Z caller=main.go:988 msg="Completed loading of configuration file" filename=./prometheus.yml totalDuration=29.024755ms remote_storage=5.122µs web_handler=307ns query_engine=2.197µs scrape=28.645242ms scrape_sd=97.764µs notify=919ns notify_sd=1.947µs rules=3.782µs
level=info ts=2021-07-21T01:56:06.534Z caller=main.go:775 msg="Server is ready to receive web requests."
level=debug ts=2021-07-21T01:56:06.534Z caller=manager.go:213 component="discovery manager scrape" msg="Discoverer channel closed" provider=static/0
level=info ts=2021-07-21T02:03:16.139Z caller=compact.go:513 component=tsdb msg="write block" mint=1626822195592 maxt=1626825600000 ulid=01FB3CV18QVNQKCBA72YMH59H9 duration=531.926557ms
level=info ts=2021-07-21T02:03:16.141Z caller=head.go:925 component=tsdb msg="Head GC completed" duration=1.362425ms
level=info ts=2021-07-21T03:00:01.570Z caller=compact.go:513 component=tsdb msg="write block" mint=1626825600634 maxt=1626832800000 ulid=01FB3G2YG8FSF19F42ZXZPP04H duration=921.485765ms
level=info ts=2021-07-21T03:00:01.571Z caller=head.go:925 component=tsdb msg="Head GC completed" duration=1.230755ms
level=info ts=2021-07-21T05:00:01.394Z caller=compact.go:513 component=tsdb msg="write block" mint=1626832800602 maxt=1626840000000 ulid=01FB3PYNT89V6G68FEZQC3ZCHZ duration=682.470478ms
level=info ts=2021-07-21T05:00:01.396Z caller=head.go:925 component=tsdb msg="Head GC completed" duration=1.214479ms
level=info ts=2021-07-21T05:00:01.416Z caller=checkpoint.go:97 component=tsdb msg="Creating checkpoint" from_segment=0 to_segment=1 mint=1626840000000
level=info ts=2021-07-21T05:00:01.621Z caller=head.go:1022 component=tsdb msg="WAL checkpoint complete" first=0 last=1 duration=205.179238ms
level=info ts=2021-07-21T07:00:01.541Z caller=compact.go:513 component=tsdb msg="write block" mint=1626840000673 maxt=1626847200000 ulid=01FB3XTD4DMMNEEQZGP5XX8XTP duration=759.6467ms
level=info ts=2021-07-21T07:00:01.543Z caller=head.go:925 component=tsdb msg="Head GC completed" duration=1.11078ms
level=info ts=2021-07-21T09:00:01.623Z caller=compact.go:513 component=tsdb msg="write block" mint=1626847200743 maxt=1626854400000 ulid=01FB44P4EWAFHMPNYNXA98NHQN duration=763.291727ms
level=info ts=2021-07-21T09:00:01.625Z caller=head.go:925 component=tsdb msg="Head GC completed" duration=1.134786ms
level=info ts=2021-07-21T09:00:01.646Z caller=checkpoint.go:97 component=tsdb msg="Creating checkpoint" from_segment=2 to_segment=3 mint=1626854400000
level=info ts=2021-07-21T09:00:01.840Z caller=head.go:1022 component=tsdb msg="WAL checkpoint complete" first=2 last=3 duration=193.251952ms
level=info ts=2021-07-21T11:00:01.820Z caller=compact.go:513 component=tsdb msg="write block" mint=1626854400814 maxt=1626861600000 ulid=01FB4BHVS52B8QVQPDDK29SGK1 duration=887.303356ms
level=info ts=2021-07-21T11:00:01.822Z caller=head.go:925 component=tsdb msg="Head GC completed" duration=1.172295ms
level=info ts=2021-07-21T11:00:02.343Z caller=compact.go:454 component=tsdb msg="compact blocks" count=3 mint=1626825600634 maxt=1626847200000 ulid=01FB4BHWP4QSXTZ3GVV8MKQ12S sources="[01FB3G2YG8FSF19F42ZXZPP04H 01FB3PYNT89V6G68FEZQC3ZCHZ 01FB3XTD4DMMNEEQZGP5XX8XTP]" duration=483.185294ms
level=info ts=2021-07-21T11:00:02.348Z caller=db.go:1239 component=tsdb msg="Deleting obsolete block" block=01FB3G2YG8FSF19F42ZXZPP04H
level=info ts=2021-07-21T11:00:02.352Z caller=db.go:1239 component=tsdb msg="Deleting obsolete block" block=01FB3PYNT89V6G68FEZQC3ZCHZ
level=info ts=2021-07-21T11:00:02.360Z caller=db.go:1239 component=tsdb msg="Deleting obsolete block" block=01FB3XTD4DMMNEEQZGP5XX8XTP
level=info ts=2021-07-21T13:00:01.786Z caller=compact.go:513 component=tsdb msg="write block" mint=1626861600898 maxt=1626868800000 ulid=01FB4JDK3DMM2XHNQ2BDFE6FJE duration=780.957959ms
level=info ts=2021-07-21T13:00:01.788Z caller=head.go:925 component=tsdb msg="Head GC completed" duration=1.152235ms
level=info ts=2021-07-21T13:00:01.810Z caller=checkpoint.go:97 component=tsdb msg="Creating checkpoint" from_segment=4 to_segment=5 mint=1626868800000
level=info ts=2021-07-21T13:00:02.080Z caller=head.go:1022 component=tsdb msg="WAL checkpoint complete" first=4 last=5 duration=270.499468ms
level=info ts=2021-07-21T15:00:01.855Z caller=compact.go:513 component=tsdb msg="write block" mint=1626868800967 maxt=1626876000000 ulid=01FB4S9ADE7QFYQ10FSTM6ATK9 duration=784.542986ms
level=info ts=2021-07-21T15:00:01.857Z caller=head.go:925 component=tsdb msg="Head GC completed" duration=1.169772ms
level=info ts=2021-07-21T17:00:01.132Z caller=compact.go:513 component=tsdb msg="write block" mint=1626876000038 maxt=1626883200000 ulid=01FB5050RA8WA05N1CZ85C3816 duration=994.400081ms
level=info ts=2021-07-21T17:00:01.134Z caller=head.go:925 component=tsdb msg="Head GC completed" duration=1.377731ms
level=info ts=2021-07-21T17:00:01.209Z caller=checkpoint.go:97 component=tsdb msg="Creating checkpoint" from_segment=6 to_segment=7 mint=1626883200000
level=info ts=2021-07-21T17:00:01.482Z caller=head.go:1022 component=tsdb msg="WAL checkpoint complete" first=6 last=7 duration=273.022182ms
level=info ts=2021-07-21T17:00:02.380Z caller=compact.go:454 component=tsdb msg="compact blocks" count=3 mint=1626847200743 maxt=1626868800000 ulid=01FB50522B13G7WSRP6TC214W8 sources="[01FB44P4EWAFHMPNYNXA98NHQN 01FB4BHVS52B8QVQPDDK29SGK1 01FB4JDK3DMM2XHNQ2BDFE6FJE]" duration=897.574439ms
level=info ts=2021-07-21T17:00:02.386Z caller=db.go:1239 component=tsdb msg="Deleting obsolete block" block=01FB44P4EWAFHMPNYNXA98NHQN
level=info ts=2021-07-21T17:00:02.393Z caller=db.go:1239 component=tsdb msg="Deleting obsolete block" block=01FB4BHVS52B8QVQPDDK29SGK1
level=info ts=2021-07-21T17:00:02.404Z caller=db.go:1239 component=tsdb msg="Deleting obsolete block" block=01FB4JDK3DMM2XHNQ2BDFE6FJE
level=info ts=2021-07-21T17:00:03.307Z caller=compact.go:454 component=tsdb msg="compact blocks" count=3 mint=1626822195592 maxt=1626868800000 ulid=01FB5052Z4D34GFGDB9JZPE39W sources="[01FB3CV18QVNQKCBA72YMH59H9 01FB4BHWP4QSXTZ3GVV8MKQ12S 01FB50522B13G7WSRP6TC214W8]" duration=902.759909ms
level=info ts=2021-07-21T17:00:03.313Z caller=db.go:1239 component=tsdb msg="Deleting obsolete block" block=01FB50522B13G7WSRP6TC214W8
level=info ts=2021-07-21T17:00:03.325Z caller=db.go:1239 component=tsdb msg="Deleting obsolete block" block=01FB3CV18QVNQKCBA72YMH59H9
level=info ts=2021-07-21T17:00:03.336Z caller=db.go:1239 component=tsdb msg="Deleting obsolete block" block=01FB4BHWP4QSXTZ3GVV8MKQ12S
```

**Comment by codesome** [comment]
Before even looking at the leak, I can say that calling delete for all series every minute is going to be very expensive. Since it touches all series, every delete call will lead to a compaction of the block (which is a total re-write of the data block). This is going to reduce the life of your disk pretty significantly.

**Comment by AdamSLevy** [comment]
It would be interesting to test if the memory goes back down if you pause calling delete for some time. That would be a good indication that it's not a leak but simply compounding effects of re-compaction due to the regular delete_series calls

**Comment by timofey-barmin** [comment]
@codesome
We can do it less frequently then, I think.

@AdamSLevy 
I'll try that, but I have to say that your words about it not being a leak don't sound convincing :)

**Comment by timofey-barmin** [comment]
@AdamSLevy 
I stopped the script with deletions yesterday. Memory didn't go back as you see, but it's not growing anymore. So it still looks like a memory leak. I'm pretty sure if unpause the script it will start leaking again (will do that).

<img width="822" alt="Screen Shot 2021-07-27 at 3 50 09 PM" src="https://user-images.githubusercontent.com/3727395/127238515-97e97e85-ee9b-45dc-ba15-4c7e8adf36b0.png">

For comparison, here is the same graph from identical Prometheus with identical load, but where there were no deletions done:

<img width="820" alt="Screen Shot 2021-07-27 at 4 00 39 PM" src="https://user-images.githubusercontent.com/3727395/127238583-91986304-7c36-4aba-b579-4ce1cb61b983.png">

Since it's easy to reproduce should be easy for you to fix, I guess.    

It also looks like when it crashes due to OOM it doesn't always can load all the blocks after restart. But I don't have much info about it now. I will create a separate issue for it if I can confirm it.

**Comment by codesome** [comment]
@timofey-barmin thanks for checking it out. Would it be possible to share the heap and alloc profiles of the Prometheus server where delete script is running (maybe restart the Prometheus server and start script again to not OOM)? They are available at 
`<prometheus-url>/debug/pprof/heap` and `<prometheus-url>/debug/pprof/allocs`

**Comment by timofey-barmin** [comment]
@codesome 
sure, here they are:
[memory_issue.zip](https://github.com/prometheus/prometheus/files/6894212/memory_issue.zip)

**Comment by codesome** [comment]
@timofey-barmin thanks! I will take a look at them next week :)

**Comment by codesome** [comment]
Took a quick look and one thing stands out immediately
```
Showing top 10 nodes out of 50
      flat  flat%   sum%        cum   cum%
  271.45MB 93.91% 93.91%   271.45MB 93.91%  github.com/prometheus/prometheus/tsdb/tombstones.Intervals.Add
       4MB  1.38% 95.30%        4MB  1.38%  bufio.NewWriterSize (inline)
    2.64MB  0.91% 96.21%     2.64MB  0.91%  compress/flate.NewWriter
    2.27MB  0.78% 97.00%     2.27MB  0.78%  github.com/prometheus/prometheus/web/ui.glob..func1
       2MB  0.69% 97.69%        6MB  2.08%  github.com/prometheus/prometheus/tsdb.(*memSeries).mmapCurrentHeadChunk
    1.66MB  0.57% 98.26%     1.66MB  0.57%  github.com/prometheus/prometheus/tsdb.newStripeSeries
```

Without much investigation into code further, I am guessing it's just way too many tombstones because for each delete call, 1 tombstones is created _per series_. So if you have 1000 series, every delete call will add 16000 bytes with at least 8000 bytes fixed overhead. Your test script was delete every 10s, so for 2hrs tombstones will take roughly 11MB of memory. For 30819 series, ~340 MB. And I see that we are not deleting those tombstones from Head block ever, which means 10G of memory will fill in 2.5 days (which aligns with the graph in the issue description).

So the fix to this should be to also garbage collect tombstones when we are garbage collecting the Head block.

In the meantime, until this is fixed, you should consider reducing the frequency of delete calls and restart Prometheus after you hit some fixed memory limit (old tombstones are not loaded back into memory on restart).

**Comment by menih** [comment]
Just in case there are other options - the goals for performing the pruning
on older stats is to reduce both disk space and especially resident memory.
Is there other ways to achieve the same without going through deletion and
tombstones?

**Comment by menih** [comment]
And is there a way, short of process restart, to manually solicit tombstone
GC?

**Comment by codesome** [comment]
There is no other way yet other than deleting or using smaller retention. And deletion won't necessarily reduce the memory upfront, rather take more memory for tombstones but that should be within limit once we do GC on Head tombstones.

There is an API endpoint to clean the tombstones (hence delete the actual data too), but that does not delete the data from Head but only persistent blocks. But I guess in your case all the deletes are in the head block so it is not useful. So there is 1 improvement we can do - clean tombstones API to also clean from the Head block.

In the mean time, if you are aggressively deleting data by calling the script every minute, would it also be the case that you could increase the scrape interval so that you don't need the deletion script at all?

**Comment by timofey-barmin** [comment]
@codesome 
Thanks a lot for this info. Just to be clear: primary goal for us is to reduce disk space consumption with fixed history length. Memory becomes an issue at this point only when it starts leaking.

So, if I understand correctly, if I try removing a sample that is in the head block, the tombstone will be in memory forever (until restart). If I try to remove the sample that is in persistent block, there should be no tombstone in memory at all. Is this correct?

If so, how could we make sure we never remove samples that are in the head block? Currently I see that if I wait 4 hours before removing the samples the problem is still present. I can try to guess: If I set min-block-size = 2h, will this guarantee that 4 hours samples are not in the head block anymore?

Regarding your question about increasing the scrape interval:
It's an option, but it doesn't help as much as downsampling. The worst granularity we can afford is probably ~20 sec (this granularity requirement is for relatively fresh samples only). Which is 2 times worse than we have now (10 sec). So it will give us 2 times longer stats history. Currently we have 2 days of stats (with 1GB limit), so we will have 4 day history if we increase the scrape interval. Unfortunately, 4 day history is also too short for us. So we have no other option but downsampling if we want to have good granularity for "young" samples and long stats history at the same time.

**Comment by codesome** [comment]
> If I try to remove the sample that is in persistent block, there should be no tombstone in memory at all. Is this correct?

You found another issue! I just checked the code and looks like we are not skipping the Head block if the delete call does not overlap with it (while we take care of it properly for persistent blocks). So looks like tombstones will grow in memory for any delete call. I have updated the issue description with possible fixes to do.

> Currently I see that if I wait 4 hours before removing the samples the problem is still present.

If we fix the above (i.e. not touching Head if it does not overlap), then 4 hour is good enough to not touch Head block at all. By default min block size should be 2h.

**Comment by codesome** [comment]
@darshanime thanks! Please see the issue description for the 3 different action items. You can ignore the 3rd one for now.

**Comment by menih** [comment]
We have tried this fix and it seems memory is behaving properly. But what we are noticing is very high CPU consumption during processing (%100) of sample removal. The more samples we need to remove, the longer the duration of high CPU we're seeing. This basically take over all compute available on the host which may not be acceptable.

1) Can understand what is consuming this high CPU? Is there a way to work around it?
2) Are there any plans to address this in the future?

**Comment by codesome** [comment]
Glad to know that the fix is working. Answer to your questions:

1. [Compactions](https://ganeshvernekar.com/blog/prometheus-tsdb-compaction-and-retention#compaction). I believe you are calling delete on old data too? In that case, the compaction process will rewrite the block to remove the deleted series soon after you call the delete API, because the delete call touches a big % of the series. You can try to call the delete API less frequently to reduce the overall CPU usage over time, but there is no way to totally remove the high CPU consumption.
2. This is the intended behaviour for deletes spanning all time series. Calling delete API for all time series at such regular intervals is not a use case that Prometheus recommends or would plan to support. What Prometheus could eventually support is downsampling.

**Comment by menih** [comment]
I am wondering how Prometheus' own compaction based on disk space size, or
timestamp retention works. It requires sample removal as well, right?
Would it be more efficient thus not requiring heavy computation resources?

Downsampling would be great to have and probably achieve exactly what
we are looking for. Which release is this planned for?

**Comment by menih** [comment]
Also forgot to ask - is there a way to batch delete multiple samples and
control when compaction will take place?
