### ISSUE TITLE
Change the definition of ready or create a new endpoint with a different definition

### ISSUE THREAD

**Issue by wiardvanrij** [prometheus/prometheus#9122]
At the moment we use a readiness probe on `http-get http://:web/-/ready` which makes sense. This is actually from the Prometheus Operator but I assume this is the de facto standard to use it. 

Now regarding 0 downtime deployments, we face an issue. Even though using a stateful set with 2 replica's, we experience hiccups/downtime. This is caused by two factors:
- The LB/svc but also other components that do discovery (such as Thanos) might just not be as quick to spot the new pod.
- The newly made replica has not scraped all the targets yet, causing missing data.

I thought to be clever and create an issue at the Prometheus Operator here: https://github.com/prometheus-operator/prometheus-operator/issues/3711 to implement .spec.minReadySeconds. However this is actually not a k8s thing yet. See: https://github.com/kubernetes/kubernetes/issues/65098 - that should come in k8s 1.22 (?)

So to solve this I'm thinking about a combination:
1: We need to allow Prometheus to be 'not ready' and start scraping. I.e. make sure to have done 3 rounds of scrapes (or whatever)
2: We need to allow an extra period of 'ready state' to allow other components (such as Thanos) to discover it. This IMO only can be done at k8s 1.22 when we actually have such a feature.

This would (I think) solve any issues with deploying and allows us to only run 2 replica's to have 0 downtime deployments.

For point number 1, it would mean a new 'ready endpoint' by either changing the definition of `ready` or create a new endpoint with a different definition of `ready` 

One definition can be: It's healthy and started
The other one can be:  It's healthy, started and has done a few scrape rounds so there is actually data present

**Comment by roidelapluie** [comment]
Hello, thanks for your pull request.

I think this complexity would belong to kubernetes and not in Prometheus, as in the issue linked. I do not think we need additional endpoints in Prometheus for this. An alternative would be to have a custom readinessprobe that does a curl /-/ready && sleep 30s

**Comment by wiardvanrij** [comment]
> I think this complexity would belong to kubernetes and not in Prometheus, as in the issue linked. 

For the best outcome, it would consist of effort in Kubernetes and in Prometheus. I see features in Prometheus complementary to other techniques. Like the health/ready endpoints. 

> An alternative would be to have a custom readinessprobe that does a curl /-/ready && sleep 30s

I mean, that could work. However I strongly feel that this is not a robust solution. More a workaround. 

The point is that there is only one place which knows the exact state. That is Prometheus. It does however also need the feature from k8s. Yet I think it's so important to know if Prometheus has actual "data ready", rather than "being ready" itself. Personally, I would favour 'data ready' over anything. Perhaps I'm the odd one here though :D

**Comment by roidelapluie** [comment]
The data is queryable when /-/ready is OK.

Data ready is a big word and it is out of scope here: what if Prometheus can not scrape targets? What if you have a scrape interval of 5m? This would add a 20 min delay on startup.

I think that `minReadySeconds` of 5m should fix your specific needs.

**Comment by wiardvanrij** [comment]
Wow sorry for the super late response here. Totally missed this one :)

> The data is queryable when /-/ready is OK.

Prometheus is ready and technically you can run queries but there won't be any data for the period Prometheus was not online.
When running in HA, that's exactly the moment the only Prometheus that _has_ that data, will go offline due to the rolling update (since there is now a Prom online). 

> Data ready is a big word and it is out of scope here: what if Prometheus can not scrape targets? What if you have a scrape interval of 5m? This would add a 20 min delay on startup.

I agree on all parts, just with a different outcome. A part of the HA setup makes it absolutely fine to have a rollover which adds a delay of 20 minutes if for some reason needs that to be actually useful for the use-case. IMO 20 min delay seems quite unrealistic though but regardless; yes I would actually prefer this.

> I think that `minReadySeconds` of 5m should fix your specific needs.

It certainly helps and it should be an easy implementation that gets us a lot further. However, it's just an estimate and a lucky guess on how long Prometheus should take to be ready and consists of data. 

To answer your question regarding the 
> what if Prometheus can not scrape targets? 
Alright, I think it should be more about 'have I done scrapes' - I.e. if Prometheus has iterated over all the scrape targets (maybe for n-amount of times) -> than we consider it "data ready". If Prometheus cannot get to your targets, than that's your data.

I guess the tl;dr part here is: Prometheus is the source of truth on it's state. Using any other method is just hoping for the best.

**Comment by bboreham** [comment]
Hello from the bug-scrub!

Seems the work-around of using minReadySeconds is workable.  Beyond that, an external tool could implement a readiness probe which queried scrape metrics to give the answer you wanted.
We'll close this for now, but if there is some reason to integrate that tool into Prometheus please follow-up.
