### ISSUE TITLE
Paths to CSS and JS for /classic/config path result in 404s

### ISSUE THREAD

**Issue by aiyengar2** [prometheus/prometheus#9130]
**What did you do?**

Deployed Prometheus behind a proxy. Opened up the Networking tab on DevTools. Went to `/classic/config`.

**What did you expect to see?**

No errors / 404s.

**What did you see instead? Under which circumstances?**

Observed that the network calls to get the CSS and JS for that page result in 404s.

![Screen Shot 2021-07-28 at 10 41 02 AM](https://user-images.githubusercontent.com/13127443/127370561-3e60834b-dae9-473d-90e3-5b4102da8618.png)

---

I omitted the remaining information about the environment since the fix seems to be relatively straightforward.

I believe the fix for this is just a quick followup to @juliusv's PR in https://github.com/prometheus/prometheus/pull/8142 to update the paths below to add `/classic`:

https://github.com/prometheus/prometheus/blob/39d79c3cfb86c47d6bc06a9e9317af582f1833bb/web/ui/templates/config.html#L2-L3

**Comment by juliusv** [comment]
@aiyengar2 Thanks for reporting this, you're totally right, and it's broken also without a proxy! Fix PR: https://github.com/prometheus/prometheus/pull/9202
