### ISSUE TITLE
ipv6 addresses for targets throws error

### ISSUE THREAD

**Issue by jimmidyson** [prometheus/prometheus#914]
```
Get http://fe80::f816:3eff:fee5:a2eb:10255/metrics: dial tcp: too many colons in address fe80::f816:3eff:fee5:a2eb:10255
```

Are ipv6 addresses supported?

**Comment by matthiasr** [comment]
They should be … and that URL should be `http://[fe80::f816:3eff:fee5:a2eb]:10255/metrics`. How is this address configured? SD (which kind)?

**Comment by jimmidyson** [comment]
A new kind ;) Kubernetes discovery in PR - so need to wrap ipv6 addresses in `[...]`. OK let me add that in - thanks.

**Comment by juliusv** [comment]
Yup, see also https://en.wikipedia.org/wiki/IPv6_address#Literal_IPv6_addresses_in_network_resource_identifiers

**Comment by jimmidyson** [comment]
@juliusv Thanks!

**Comment by w0mbat** [comment]
We are running Kubernetes and Prometheus on Rackspace and for some reason, they sometimes assign ipv4, sometimes ipv6 addresses.

The example prometheus configuration for kubernetes suggests to use the `kubernetes-service-endpoints` job which does autodiscovery on services that should be scraped. At this point it is not possible to add any bracket for the ipv6 address and we also don´t know in advance which address will actually be used by prometheus.

From my perspective it would be good if prometheus would be smart enough to detect if an ip is ipv4 or ipv6.

Thoughts?

**Comment by jimmidyson** [comment]
Are you seeing ipv6 addresses not wrapped in `[..]` properly? That is a bug if so - could you open a separate issue for that please?

**Comment by w0mbat** [comment]
@jimmidyson No, they are not wrapped at all - will open an issue for that
