### ISSUE TITLE
Proposal: add generic (EDS) based XDS SD mechanism

### ISSUE THREAD

**Issue by howardjohn** [prometheus/prometheus#9144]
## Proposal
**Use case. Why is this important?** [Envoy](https://envoyproxy.io/) is CNCF graduated project, and has more or less become a de-facto standard proxy implementation for service meshes and cloud-native Ingresses.

Aside from acting as a proxy implementation, Envoy also contains a vendor-neutral [XDS API](https://www.envoyproxy.io/docs/envoy/latest/api-docs/xds_protocol#xds-rest-and-grpc-protocol). This API is implemented not only by Envoy itself, but also [gRPC](https://grpc.github.io/grpc/cpp/md_doc_grpc_xds_features.html) and a few other proxies ([MOSN](https://github.com/mosn/mosn), [Quilin](https://github.com/googleforgames/quilkin/blob/main/docs/xds.md) and a lot of proprietary proxies).

Support was recently added for Kuma SD (https://github.com/prometheus/prometheus/issues/7919). However, there are a few issues with this approach:
* The SD only has support for a Kuma-specific API, `MonitoringAssignment`. This locks out the vast ecosystem mentioned above.
* The implementation uses an uncommon variant of the API (`REST-JSON polling`), rather than the much more common gRPC streaming. This is far less supported and much less efficient.

It would be great to add support for a more vendor-neutral API, [`ClusterLoadAssignment`](https://github.com/envoyproxy/envoy/blob/0d2418e9f19d50197ed237dfe5497c715d3c99f0/api/envoy/config/endpoint/v3/endpoint.proto#L32), which is part of the core XDS APIs and implemented by all(?) users of XDS. Additionally, support for gRPC streaming would allow existing control planes to be used in place, and avoid high performance costs.

Similar request in the past: https://github.com/prometheus/prometheus/issues/6484

cc @austince @mandarjog @roidelapluie

**Comment by austince** [comment]
Thanks for the ping @howardjohn + the interest! 

I think adding support for `ClusterLoadAssignment` sounds like a good idea – do you have a specific proposal for mapping those to Prometheus targets? The current xDS SD implementation is only vendor-specific in terms of the API. It is built to be extended to new APIs easily. 

For gRPC, we had a similar conversation (perhaps see [this ML thread](https://groups.google.com/g/prometheus-developers/c/w2F6gxYW8U8/m/hRrKWRu4BAAJ) for context), but ultimately went with HTTP since it simplified both the mechanics and the dependencies of the SD. @roidelapluie would have the golden insights there.

**Comment by austince** [comment]
We looked quite a bit for a standard API that fully expressed something like a Prometheus Target, but did not find anything w/in Envoy or elsewhere. Would be happy to have more support to define a standard there. Here are some threads in OpenTelemetry around that:
* https://github.com/open-telemetry/opentelemetry-proto/issues/263
* https://github.com/open-telemetry/opentelemetry-specification/issues/1078#issuecomment-776334709

**Comment by howardjohn** [comment]
I would envision the mapping to be like this:
```json
{
    "@type": "type.googleapis.com/envoy.config.endpoint.v3.ClusterLoadAssignment",
    "cluster_name": "some-backend",
    "endpoints": [
        {
            "lb_endpoints": [
                {
                    "endpoint": {
                        "address": {
                            "socket_address": {
                                "address": "10.36.3.86",
                                "port_value": 8080
                            }
                        }
                    },
                    "metadata": {
                        "__meta_prometheus_job": "something",
                        "__meta_prometheus_foobar": "else"
                    }
                }
            ]
        }
    ]
}
```

The thread suggest `metadata` is not intended to be used for this purpose, but I am not sure I agree - it seems well suited? I think the docs are just a bit misleading (`The endpoint metadata specifies values that may be used by the load balancer to select endpoints in a cluster for a given request. The filter name should be specified as envoy.lb.`), because it is documenting how Envoy the proxy uses them. There is a common detail/terminology confusion between Envoy-the-proxy, XDS transport protocol (ie sending Discovery{Request,Response}), and the XDS apis (ie `ClusterLoadAssignment`) - I think in this case they are discussing Envoy-the-proxy's usage of `metadata` - it seems perfectly valid to use `metadata` for other usages as well (we do this in Istio at least, and have never had issues).

> ultimately went with HTTP since it simplified both the mechanics and the dependencies of the SD

My reading of the thread is there is this primary concern:

> hould we have a generic SD, I would not like that much GRPC as would
> bring many dependencies, that we already had issues with. Additionally,
> we have more chances to use a more-established standard like HTTP (with
> long poll). Especially since the communications only need to be one-way.

gRPC is currently a transitive dependency (from the XDS import for one, among others like k8s). I don't know how to exactly quantify the impact of moving it from an indirect -> direct dependency, but from importing it explicitly it seems there are no real changes to `go.sum` (and go.mod just has the new grpc line). So its plausible its not a huge new dependency in terms of go imports - it is of course a new runtime dependency. I think a lot of the complexity is already a sunk cost with the go-control-plane import for kuma_sd.

Regarding the one-way part - one of the biggest benefits of the gRPC streaming is that the control plane can push updates. So instead of polling every Xs, and getting the full state-of-the-world (which may be very large!! like O(megabytes)), we can connect once and then just get incremental updates as endpoints change.

gRPC is less standard than HTTP, but its not horribly bespoke - it is mostly just "protobuf over HTTP/2" if you squint your eyes :slightly_smiling_face: .

**Comment by austince** [comment]
@howardjohn Yeah :/ the xDS API / envoy-proxy line is not the most straightforward. It seems like using metadata for this would work, though would be tougher to implement/validate as it relies on arbitrary keys in metadata being present.
Do you envision this being pulled from the main xDS API? How does one distinguish a request for  `ClusterLoadAssignment` the load balancer spec vs. `ClusterLoadAssignment` the metric scrape target spec? 

For gRPC, I agree with you completely that incremental updates would be great! Here are a couple more threads on the gRPC/Prometheus relationship that you might be interested in:
* https://github.com/prometheus/prometheus/issues/7836
* https://github.com/prometheus/prometheus/issues/8414

In the context of the HTTP polling in the current kuma_sd, it is important to note that it uses HTTP long-polling (thanks @roidelapluie  :)) to reduce the polling requests, and ofc uses the version of the current resources to only send back the state of the world when that changes. This can be O(megabytes) like you mentioned, but with those two features, it is much more efficient than the same over the http_sd.

**Comment by howardjohn** [comment]
> How does one distinguish a request for ClusterLoadAssignment the load balancer spec vs. ClusterLoadAssignment the metric scrape target spec?

Its _possible_ a control plane would not care, and just always set all the labels. For scalability reasons, that seems like it would always work - certainly for us that would cause scalability concerns to add all the prom labels for every client.

The XDS requests contain metadata about the client in the `node` - there is arbitrary `struct` config as well as user agent, etc. So somewhere in there could specify prometheus and a control plane could choose to respond differently in that case

**Comment by roidelapluie** [comment]
Hello,

This is indeed kuma-sd, within a package that can do XDS REST-JSON polling. Adding different types should be possible within the same go package -- if it supports the REST-JSON polling.

We went for HTTP polling for now because we are thinking about what we will do with our protobuf stacks, and I did not want a service discovery to interfere with this until we have a proper solution for the protobuf we use in the rest of Prometheus. I also did not want to take the kuma PR in hostage pending this proto work.

**Comment by mandarjog** [comment]
I think we may also need to tweak the api for simplicity.
EDS does not allow wildcard resource request. If not, the controlplane can choose to still implement a wildcard eds and specifically deltaEds.

**Comment by bboreham** [comment]
Hello from the bug-scrub!

Prometheus has [http SD](https://prometheus.io/docs/prometheus/latest/http_sd/), which would allow any source of service information to be integrated.
Since no further comments were made on this issue, we will conclude it was not of high interest and close it.
