### ISSUE TITLE
scrape_duration_seconds and scrape_samples_scraped are empty for some nodes

### ISSUE THREAD

**Issue by fisdev6** [prometheus/prometheus#9149]
Hello,

We have prometheus setup to scrape data from various wildfly instances,
For some of them, the up command give 0 ( node down ) information.

But some metrics are being extracted from those nodes !

When we look at the scrape_duration for those we also have values, and the scrape_sample_scraped is also giving 0

Is this something known ?

You can find attached, screenshots of the different commands
![scrape_duration_seconds](https://user-images.githubusercontent.com/88373321/127986550-f09091aa-a12f-444b-9cfa-127c383096a3.JPG)
![scrape_sample_scraped](https://user-images.githubusercontent.com/88373321/127986553-344bae4a-7764-45d6-8baa-825d333082a1.JPG)
![up](https://user-images.githubusercontent.com/88373321/127986556-c68377c0-3147-40e9-a080-bc1ed4d44580.JPG)

**Comment by LeviHarrison** [comment]
The scrape duration is always reported, whether the target is up or not. I believe the reason why you're seeing some downed targets have a non-zero `scrape_samples_scraped` is that the target might have been up at some point, and is now down, while others may have always been down, and therefore have never had any samples scraped.

**Comment by fisdev6** [comment]
Thanks for your reply,

When looking at the dashboard we have built using grafana, we do have metrics being fetched from those host wich have a 0 in the scrape_sample_scraped

**Comment by roidelapluie** [comment]
Can you please provide us relevant parts of your configuration, and a screenshot of the nodes in the targets page? Your Prometheus version would be useful too.

**Comment by bboreham** [comment]
At the bug-scrub meeting we decided to close this as no further information was supplied.
