### ISSUE TITLE
Calculating standardized cpu metrics requested by pods for an hour

### ISSUE THREAD

**Issue by sathyendrasaran** [prometheus/prometheus#9156]
I am trying to find the  cpu requested by kubernetes pods rolled up to an hour
lets say we have an average cluster cpu allocatable as 10 cpu cores
pod 1 requests 5 cpu for 20 mins
pod 2 requests 5 cpu for 30 mins
pod 3 requests 5 cpu for  1 hr

now i have to find for an hour 
how much cpu is occupied by pod 1 for that hour and likewise for pod 2 and 3
since pod 3 is occupies 5 cpu thoroughout that hour - we can say pod 3 cpu occupied = 5 
How to calculate the cpu requested by pod 1 and 2 normalized for that hour

my initial thought for normalizing was
For pod 1 => 5*(20/60) = 1.666667 (requests normalized for an hour)
But when i use it for the metrics

i see sum(pod1+pod2+....+podn) > total cluster cpu -- like way higher( 340 > 80)
Any thoughts on logic here?

Does Kubernetes always allocate the pod requests ?

**Comment by codesome** [comment]
Hi @sathyendrasaran, we use GitHub issues for development discussions. Please use our community channels for such questions which you can find here https://prometheus.io/community/
