### ISSUE TITLE
who can give me advise。

### ISSUE THREAD

**Issue by CloudWise-Lukemiao** [prometheus/prometheus#9173]
![image](https://user-images.githubusercontent.com/76942485/128625101-6017481e-ab34-427a-8b57-febf6725c269.png)
I am developing a third-party open source database, which is responsible for remote writing and reading of Prometheus. At present, the two files in the pictures I use are temporarily downloaded and copied to my project. My question is how to reference these two files in MVN, or is there another better way?

**Comment by codesome** [comment]
Hi @CloudWise-Lukemiao, we use GitHub issues to tracks bugs/features of Prometheus project. Please use our community channels for such questions https://prometheus.io/community. (PS: your question is more about proto handling in MVN, so Prometheus community might not be the best place for this question)
