### ISSUE TITLE
React UI: Pre-relabel labels extend offscreen and can't be seen

### ISSUE THREAD

**Issue by LeviHarrison** [prometheus/prometheus#9175]
**What did you do?**

I hovered over one of my targets with a particularly long list of labels.

**What did you expect to see?**

All the labels, or the ability to scroll down to see the rest of them.

**What did you see instead? Under which circumstances?**

The box of labels had extended offscreen. Conveniently, a scroll bar appeared, but as I scrolled down my pointer left the hover area, and the box was hidden again.

**Environment**

* Prometheus version: 2.28.1

**Comment by LeviHarrison** [comment]
We also might want to consider changing how we display labels.

**Comment by roidelapluie** [comment]
cc @juliusv what's your take here?

**Comment by juliusv** [comment]
@LeviHarrison You are talking about the tooltip that shows the pre-relabeling target labels, right? Are the "normal" target labels in the table displayed fine otherwise (I couldn't see a problem with those)?

**Comment by LeviHarrison** [comment]
Yes. Sorry, I should have clarified that.

**Comment by juliusv** [comment]
Yeah, we could have little exander button in that table cell to show the pre-relabel labels? That would also help in general for folks who want to copy-and-paste something from them.

**Comment by LeviHarrison** [comment]
That would be awesome.

**Comment by juliusv** [comment]
The only thing I don't like about that is the space that kind of button would use: if we put it on the same line, the text "show pre-relabeling labels" would use a lot of horizontal space, whereas if the button was under or over the normal target labels, it would make most target rows (where all labels fit on one line) twice as tall or so. Maybe we could put it on the same line as the labels, but use some "details" icon with "show pre-relabeling labels" as hover text only?

**Comment by LeviHarrison** [comment]
Maybe something like this:

![image](https://user-images.githubusercontent.com/54278938/128926861-1c8e7700-f185-4dd8-841a-197eaece6c58.png)

**Comment by juliusv** [comment]
That would suggest that some of the normal target labels are hidden and need to be expanded... whatever icon (or other means) we use should make it clear that the action shows a different set of labels, not just completing the existing ones.

**Comment by roidelapluie** [comment]
Let's find a solution that does not make #6881 worse.

**Comment by Nexucis** [comment]
@LeviHarrison could you post a screen shot showing your issue ? I'm currently working around the target page, maybe there is a quick fix to do for this one.

**Comment by LeviHarrison** [comment]
Sorry, I think I didn't take a screenshot for this issue originally because it was kind of tricky to do so. It was on an instance running in a k8s cluster, and the k8s discovery mechanism attaches a lot of labels to targets leading to this issue. I might be able to spin up one later and get a screenshot, but I don't have one running right now.

**Comment by jheddings** [comment]
I ran across this issue when troubleshooting the same problem as @LeviHarrison , also from a Kubernetes cluster.  I managed to capture the screenshot by holding down the mouse press, which seemed to keep the "Before relabeling" pane up a bit longer.

![Screenshot 2023-09-10 at 20 39 12](https://github.com/prometheus/prometheus/assets/5632561/e31ebac6-7451-4a1e-80d6-f832e9d2baf8)
![Screenshot 2023-09-10 at 20 38 06](https://github.com/prometheus/prometheus/assets/5632561/f82ba8dc-dc16-47d7-86a3-89090d1c9654)

**Comment by juliusv** [comment]
Here's a fix proposal: https://github.com/prometheus/prometheus/pull/12824
