### ISSUE TITLE
Remote-write should clear backlog much faster than 100 seconds

### ISSUE THREAD

**Issue by bboreham** [prometheus/prometheus#9178]
## Proposal
Remote-write should try to make up time faster, by putting more weight on the backlog of un-sent samples.

Here, we first compute a coefficient of 0.1 divided by the sharding tick, which is 10 seconds, or 1/100, then apply this to the number of pending samples:
https://github.com/prometheus/prometheus/blob/e8663a4eacd310f403ebf5ce492494652dd69379/storage/remote/queue_manager.go#L830-L834
Effectively we target 100 seconds to clear the backlog.

The point seems to be aluded to here: https://github.com/prometheus/prometheus/issues/6333#issuecomment-555360746
> I believe the weight of the samples pending within the calculation isn't enough, but again this is just my theory.

however the source of this quote is not given.

Personally I find 100 seconds to be very long.  There are a couple of suggestions in #6333 that it should be "a few scrapes" or "`batch_send_deadline` + 1m" (65 seconds by default).

I think I would be ok with 30 seconds. I don't really want to make it configurable since hardly anyone will configure it, but I guess that might be the easiest way to find the "right" value.

**Comment by cstyan** [comment]
Open to any way you or @csmarchbanks think is a reasonable improvement, the sharding calculation has always been a bit over my head.

Maybe either the integral calculation or the overall sharding calculation should weight the delay value more heavily, more like an exponential increase with delay rather than just linear?

```
// When behind we will try to catch up on a proporation of samples per tick.
// This works similarly to an integral accumulator in that pending samples
// is the result of the error integral.
const integralGain = 0.1 / float64(shardUpdateDuration/time.Second)
```
Include delay somewhere in here :point_up:  or here :point_down: ?
```
desiredShards = timePerSample * (dataInRate*dataKeptRatio + integralGain*dataPending)
```

**Comment by csmarchbanks** [comment]
Changing the integral gain will change the 100s deadline proportionally, and is one way we could approach this. It does also mean that we could end up resharding more often, potentially in an oscillating manner. If we add to much gain we could get something that looks like k=1.6 in https://en.wikipedia.org/wiki/PID_controller#/media/File:PID_varyingP.jpg. Happy to see some experiments run for this, and it could be that as long as we are using a few cycles and the moving averages everything will be great.

I also still think just having some extra headroom in our shard calculations such that temporary spikes in latency do not cause resharding at all would provide value and quicker response at a very small cost of increased memory in the stable case. When oscillating as we can right now we would end up using all that memory anyway.
