### ISSUE TITLE
Support bearer token & client cert auth to targets

### ISSUE THREAD

**Issue by jimmidyson** [prometheus/prometheus#918]
Currently only supports basic auth to auth to targets AFAIK - would like to see other options for authentication, especially bearer token & client certs.

**Comment by matthiasr** [comment]
:+1:

**Comment by jimmidyson** [comment]
As background, this is pretty much a necessity to integrate with Kubernetes / OpenShift 3 in a secure environment. Currently there are configurations to Kubernetes to open up the metrics endpoint without auth, but can probably expect this to be deprecated or removed soon-ish.
