### ISSUE TITLE
React UI: Update Flot license headers

### ISSUE THREAD

**Issue by LeviHarrison** [prometheus/prometheus#9181]
Now that Grafana's Flot fork is licensed under MIT (https://github.com/grafana/grafana/pull/36442), we should update the license headers in the vendored code to reflect that.

Currently, the header is the following:

```js
/**
 *
 * THIS FILE WAS COPIED INTO PROMETHEUS FROM GRAFANA'S VENDORED FORK OF FLOT
 * (LIVING AT https://github.com/grafana/grafana/tree/master/public/vendor/flot),
 * WHICH CONTAINS FIXES FOR DISPLAYING NULL VALUES IN STACKED GRAPHS. THE ORIGINAL
 * FLOT CODE WAS LICENSED UNDER THE MIT LICENSE AS STATED BELOW. ADDITIONAL
 * CHANGES HAVE BEEN CONTRIBUTED TO THE GRAFANA FORK UNDER AN APACHE 2 LICENSE, SEE
 * https://github.com/grafana/grafana/blob/master/license.
 *
 */
```

In https://github.com/prometheus/prometheus/pull/8977, multiple solutions were discussed, which at the time were to improve the Apache header because the MIT relicensing hadn't happened yet. There was a split between whether we should include just a short `SPDX-License-Identifier` or the full Apache 2.0 header, but given that MIT has no header, I think we can agree on the short version:

```js
/*
SPDX-License-Identifier: MIT
Source: https://github.com/grafana/grafana/tree/main/public/vendor/flot/jquery.flot.js
*/
```

To complicate things, it's worth mentioning that there are some very small changes we made to the fork. For example, in adding the selection plugin I had to modify the following lines:

https://github.com/prometheus/prometheus/blob/c3a54d1328f3b4dde9c796ecfebc16247ddeb455/web/ui/react-app/src/vendor/flot/jquery.flot.selection.js#L199

https://github.com/prometheus/prometheus/blob/c3a54d1328f3b4dde9c796ecfebc16247ddeb455/web/ui/react-app/src/vendor/flot/jquery.flot.selection.js#L412 (this one appears in the other files too)

I'm sure these aren't the only examples of changes, and although minuscule, I wonder if that should affect the header.

cc @RichiH @roidelapluie @juliusv

**Comment by roidelapluie** [comment]
We would need @boyskila's approval to re-license their changes under MIT.

**Comment by LeviHarrison** [comment]
@boyskila friendly ping :)

**Comment by boyskila** [comment]
Hey @juliusv, yeah I'm ok with that :) Sorry again for the late response.

**Comment by juliusv** [comment]
Great! No worries, and thanks :)

**Comment by LeviHarrison** [comment]
Finally got around to opening #11603 for this
