### ISSUE TITLE
remote write filesystem data disorder

### ISSUE THREAD

**Issue by hs02041102** [prometheus/prometheus#9182]
**What did you do?**
we use remote write and nodeexporter to forward data to other system。but we find that filesystem  is error.
the value and mountain of one host is others.
![BEF7DC17-7C9E-4b17-A8C9-AC41ED481607](https://user-images.githubusercontent.com/88703291/128817630-06e1f017-de67-4a5f-a66c-128b3ba2c005.png)
![23B5C07C-A3F2-4944-8B3E-09CC54449D67](https://user-images.githubusercontent.com/88703291/128817633-2f2608b4-ff3e-4f5c-9401-e22a2729cdff.png)
/gitlab is not exist in this host， it belong to other host remotewrite by the same Prometheus. 
we cant find '/backup/gitlab' in this host's metrics.
**Environment**
docker  k8s  linux

* Prometheus version:
2.28.1

**Comment by codesome** [comment]
We use GitHub issues to track Prometheus development. Please use our community channels for usage questions which you can find here https://prometheus.io/community/.
