### ISSUE TITLE
Promtool could support reading PrometheusRule input

### ISSUE THREAD

**Issue by clux** [prometheus/prometheus#9195]
**Use case. Why is this important?**

Currently, to use `promtool` on a gitops style repo, people have to extract the `.spec` from `PrometheusRule` files to create temporary files to then check.

It's not super hard to work around, but requires something like [`yq`](https://github.com/kislyuk/yq), and temporary file usage:

```sh
for PROMFILE in $(grep -lR "kind: PrometheusRule" yamlfolder/); do
  yq ".spec" -y < "${PROMFILE}" > "${PROMFILE}.promtool.yaml"
done
promtool check rules $(find "yamlfolder/" -iname "*.promtool.yaml")
find "yamlfolder/" -iname "*.promtool.yaml" -exec rm {} \;
```

Would you be open to a PR that speculatively reads the file as yaml, checks if it has a `kind: PrometheusRule`, and if so, enters into the `.spec` key first?

I realise this is a a `prometheus-operator` thing, but it feels like it could be a quick thing to support - if you think it sounds reasonable.

**Comment by roidelapluie** [comment]
Also, I would expect that in a "gitops" repo, you use a templating system that enables you to deduplicate the rules yaml from the pure kube "enveloppe".

**Comment by clux** [comment]
Yeah, there are workarounds here, they just all require some fiddling everywhere (sometimes all you have is the pure kube yaml, sometimes you want to test your generated output before merging prs).

Anyway, not essential, and I guess this is more in `prometheus-operator`'s purview anyway. Closing.
