### ISSUE TITLE
Does prometheus support   okta OAuth2   this authentication login method

### ISSUE THREAD

**Issue by zhucanhong** [prometheus/prometheus#9206]
Does prometheus support   okta OAuth2   this authentication login method ?

**Comment by bboreham** [comment]
Please go back to the "New issue" page and follow the link at "If you need help or support, please request help [here](https://prometheus.io/community/)."

**Comment by roidelapluie** [comment]
This was answered in the mailing lisT: https://groups.google.com/g/prometheus-users/c/GSBOovRpCRg/m/a2hmoDcCAwAJ
