### ISSUE TITLE
Stop remote-write flapping between two shard counts

### ISSUE THREAD

**Issue by bboreham** [prometheus/prometheus#9207]
I took this screen grab to illustrate: shards is flapping from 2 to 3 and back again, as the lag between queued data and sent data grows and falls.  Round-trip latency is broadly flat over the period.

![image](https://user-images.githubusercontent.com/8125524/129541393-fd6f0899-d937-43d4-a722-a68334bd2445.png)

I see that when desired-shards moves from 2.01 to 1.99 this triggers an instant shard-down from 3 to 2, only to see lag increase and shard back up to 3 again.

The algorithm avoids shifts of less than 30%, however 3->2 is 33% (and 2->1 is 50%).
One simple modification would be to also prohibit a downshard of 1.

I considered adding more dampening to the algorithm, but in my picture it's happening over 20-40 minutes; it's hard to imagine dampening that works a bit better at that scale but doesn't still oscillate over hours.

**Comment by cstyan** [comment]
The only problem could be when users have set queue configs that will result in them only ever needing a small amount of shards, and where sharding up or down by one shard changes throughput a lot.

**Comment by bboreham** [comment]
Going _up_ by one would be allowed.

**Comment by krajorama** [comment]
Hello from the bug scrub: no new development in 3 years, closing. Please reopen if there's new information or volunteering with a PR.
