### ISSUE TITLE
Provide metric of (useless) alert rule count

### ISSUE THREAD

**Issue by chenlujjj** [prometheus/prometheus#9215]
## Proposal
**Use case. Why is this important?**
1. We want to monitor the total count of alert rules and ,
2. monitor the count of stale or useless alert rules and then delete them to reduce the computation activity of prometheus. In our use case, the alert rules which have been always evaluated as “nodata” are considered as useless.

**Comment by roidelapluie** [comment]
You can use `max_over_time(prometheus_rule_group_last_evaluation_samples[7d])`.

**Comment by chenlujjj** [comment]
Thank you !
