### ISSUE TITLE
When I remove the job, the data still lasts for about 5 minutes

### ISSUE THREAD

**Issue by BegoniaGit** [prometheus/prometheus#9221]
prometheus version:  2.21.0

After I removed the job from `prometheus.yml`, and verified that the job was removed on the prometheus Web UI, the dashboard data still lasted about 5 minutes.

I wonder if this is a bug or a special design and if it has anything to do with the TSDB.
thanks.

![image](https://user-images.githubusercontent.com/34222824/129940095-58d7db86-d5e2-4c2e-b8e6-b67f0dccbde5.png)

**Comment by LeviHarrison** [comment]
I believe that is expected behavior.

From https://prometheus.io/docs/prometheus/latest/querying/basics/#staleness:

> If no sample is found (by default) 5 minutes before a sampling timestamp, no value is returned for that time series at this point in time. This effectively means that time series "disappear" from graphs at times where their latest collected sample is older than 5 minutes or after they are marked stale.

This is being tracked in #4966.

**Comment by roidelapluie** [comment]
This should not happen if you just query a metric, unless the metric was exposed with a timestamp. Can you please provide us more details? (Scrape config, does the metric expose a timestamp, which query did you run?)

**Comment by BegoniaGit** [comment]
> I believe that is expected behavior.
> 
> From https://prometheus.io/docs/prometheus/latest/querying/basics/#staleness:
> 
> > If no sample is found (by default) 5 minutes before a sampling timestamp, no value is returned for that time series at this point in time. This effectively means that time series "disappear" from graphs at times where their latest collected sample is older than 5 minutes or after they are marked stale.
> 
> This is being tracked in #4966.

thank you very much, the `https://prometheus.io/docs/prometheus/latest/querying/basics/#staleness:` is very useful.

**Comment by BegoniaGit** [comment]
> This should not happen if you just query a metric, unless the metric was exposed with a timestamp. Can you please provide us more details? (Scrape config, does the metric expose a timestamp, which query did you run?)

thank you for your reply,my problem has resolved.
