### ISSUE TITLE
Limits on the number of alerts generated by a rule

### ISSUE THREAD

**Issue by gouthamve** [prometheus/prometheus#9225]
We have a customer with a faulty rule that generated 30K alerts from a single rule. Now this makes the `/api/v1/rules` API nearly impossible to use with 15MB+ of data. We have scrape time limits on the samples we scrape, but I think we should also have limits on the number of samples each rule evaluation generates.

**Comment by bboreham** [comment]
Ref https://github.com/cortexproject/cortex/issues/1396

**Comment by LeviHarrison** [comment]
This would just be a separate query engine `MaxSamples` limit for alerting rules, right?

**Comment by gouthamve** [comment]
`MaxSamples` is on the input data and I am thinking of a new limit for the output of the alerting rules.

**Comment by LeviHarrison** [comment]
Yes, I suppose enforcing a limit on `active` alerts (which I believe is the correct output slice) makes more sense. Would we log a warning and send the alerts up to the limit, or error and send none at all? It seems unexpected to completely ignore all alerts if there are too many, but I don't think log line is noticeable enough. Maybe a new alert state, something like `exceeded`?

**Comment by gouthamve** [comment]
I think we should send the alerts up to the limit. But also, this would mean a "failed evaluation" and the error would show up in the UI and alert would be triggered by the mixin.

**Comment by LeviHarrison** [comment]
Should we set the `state` to `HealthBad` or leave it at `HealthGood`? I'm inclined to say `HealthBad` because something is not right.

In order to trigger an alert in the mixin we have expose a new metric, like `rule_evaluation_alerts_exceeded_total`.

**Comment by gouthamve** [comment]
We will set it to Bad. I think we can get away with incrementing `prometheus_rule_evaluation_failures_total`

**Comment by LeviHarrison** [comment]
Sounds good! I can work on this.

**Comment by beorn7** [comment]
Shouldn't we do this for rules in general (not just alerting rules, but also recording rules)?

A recording rule producing an exploding amount of output series is a problem, too.

**Comment by LeviHarrison** [comment]
Sure

**Comment by roidelapluie** [comment]
HealthBad since we would not Commit() to tsdb, but Rollback instead, similar to scrape, where we set up = 0 even if the scrape-over-network part works.

**Comment by roidelapluie** [comment]
I think we should fail completely and not store alerts if we break the limit. The default would still be no limit so we would not break our users.

**Comment by LeviHarrison** [comment]
I agree with failing completely now. If a user received some alerts, they might falsely believe they're getting the full picture.
