### ISSUE TITLE
Include exemplars in snapshot

### ISSUE THREAD

**Issue by codesome** [prometheus/prometheus#9228]
Else if snapshots are enabled, you might lose all the exemplars on a restart. This should be fixed before the next release.

**Comment by LeviHarrison** [comment]
I think we'd have to find another way to store exemplars on disk, given that we can't put them on a WAL because they'd be invalidated by the `minValidTime` from the blocks.

**Comment by codesome** [comment]
@LeviHarrison we already put them in the WAL. And invalidating them beyond the `minValidTime` is the desired behaviour right now I believe because it is only planned to be a in-memory store right now hence should follow the Head's valid time range.

**Comment by roidelapluie** [comment]
Is that really our priority? I'd rather work on having proper on-disk retention for examplars rather than using snapshots for this purpose.

**Comment by codesome** [comment]
Update: We discussed this in the Prometheus storage working group call and we want to add exemplars in snapshots since we already write them in WAL and restore on restart.

**Comment by LeviHarrison** [comment]
> And invalidating them beyond the minValidTime is the desired behaviour right now I believe because it is only planned to be a in-memory store right now hence should follow the Head's valid time range

My point was when snapshotting we convert the head chunk to a block, and in the head chunk, there is almost certainly a sample with a higher timestamp than the most recent exemplar, or at least most of them. When the samples become a block, the blocks `maxValidTime` becomes the timestamp of that most recent sample as does the `minValidTime` when loading the WAL, and therefore would invalidate most, if not all, of the exemplars left in the WAL. That's why I don't think we can store exemplars on the WAL in a snapshot, we'll have to come up with a new way.

**Comment by codesome** [comment]
> when snapshotting we convert the head chunk to a block

We don't create a block, a snapshot is [an entirely new format on disk](https://github.com/prometheus/prometheus/blob/main/tsdb/docs/format/memory_snapshot.md). I guess that is the root of confusion here.

**Comment by LeviHarrison** [comment]
Ahhhhhh that makes more sense. Thanks!

**Comment by codesome** [comment]
The main challenge in this snapshot record is maintaining the order of exemplars in the circular buffer since that will decide which exemplars will be deleted first on overflow. If we keep exemplars of a series together after a replay, we will delete 1 series at a time, which will not be the desired behaviour.

The exemplar storage does not store the series reference that we have in TSDB, rather stores the series labels and its own index entries. So I have these 3 ways in mind to write this snapshot:

1. Store the series labels together at the start with the index of them appearing in the record becoming their reference, and use that reference for the exemplars. Cons: We will need to store the map of these labels during replay and is a memory overhead. Also, these labels will take more space (unnecessary when we already store the series).

2. Store the series labels together with exemplars (for every exemplar). Pro: Efficient on memory during replay. Cons: can take a whole lot of space. Even if the exemplars were for a single series, the labels will be duplicated a lot of times.

3. (My choice) Get the series reference from TSDB when for the series labels when writing the snapshot and write that reference instead in the snapshot. When we replay back, we would have already replayed back the series and we can get labels from the ref. Con: additional computation to find reference of series from labels. But that will be a small overhead and better than using more memory/disk space in this case.

cc @cstyan 

I am starting off with the 3rd one right now, but will be easy to modify with any comments or concerns.

**Comment by roidelapluie** [comment]
I agree with 3 too.
