### ISSUE TITLE
Allow reloading via webhandler

### ISSUE THREAD

**Issue by swsnider** [prometheus/prometheus#923]
Right now, config can only be reloaded by sending SIGHUP to prometheus's process. It would be significantly easier for the automation that I'm writing to distribute our configuration to our prometheus instances if we were able to do the equivalent from a POST to the prometheus http server.

Is this something that you've already decided was a bad idea? I notice that in #108, you decided against file watches for different reasons than would seem to apply here.

**Comment by juliusv** [comment]
We already have a feature to quit Prometheus remotely (optionally enablable by setting the `-web.enable-remote-shutdown` command-line flag): https://github.com/prometheus/prometheus/blob/master/web/web.go#L170-L172

So unless we want to also remove that (I don't think anyone actually uses it), it could make sense to also add a reload endpoint. You'd probably just need to pass this channel to the web handler and make the handler send signals over it when called: https://github.com/prometheus/prometheus/blob/276dbf8a5d2444337263e70373f46cfde7fe5ffe/cmd/prometheus/main.go#L104

**Comment by swsnider** [comment]
I have actually used the quithandler because sometimes we get phantom jobs, but maybe that just means I'm the only one.

Your suggested solution is more elegant than mine was -- I just had the web handler send SIGHUP to itself. The channel is a better idea :)

**Comment by juliusv** [comment]
This was implemented in https://github.com/prometheus/prometheus/pull/976
