### ISSUE TITLE
Trig Functions

### ISSUE THREAD

**Issue by leonerd** [prometheus/prometheus#9233]
It would be useful to have some trig functions (at least, `sin`, `cos` and `atan2`), as these are essential when working with data that arrives in polar (r, theta) form.

When presented with raw data in (r, theta) form (i.e. expressed in terms of magnitude and direction), one of the first things you nearly always want to do is convert it to cartesian form, so things like longterm averages are actually meaningful:

```
data_x = data_r * sin(data_theta)
data_y = data_r * cos(data_theta)
```

Having done that, your longerterm averages over data_x and data_y now make sense, and you can then extract an "average" magnitude and direction out of these again:

```
data_r:avg1d = sqrt(data_x:avg1d ^ 2 + data_y:avg1d ^ 2)
data_theta:avg1d = atan2(data_y:avg1d, data_x:avg1d)
```

---

Background: I've been using Prometheus to store weather data, trying to represent wind speed + direction

**Comment by roidelapluie** [comment]
yes, this is something we would accept a pull request for.

**Comment by LeviHarrison** [comment]
I'm working on this.

**Comment by LeviHarrison** [comment]
It might be useful to also add functions to convert degrees to radians and vice versa. Or just add a π constant and let users do the operation in a few more steps.

**Comment by leonerd** [comment]
@LeviHarrison Yes I was thinking exactly that - either a pi constant or some conversion functions. I have no firm feeling for which is best - either would be fine with me.

Let me know if you need a hand with testing it out, or docs-writing, or some of those other bits.

**Comment by mattxwang** [comment]
Also would love to see this! I'm curious, @LeviHarrison, any plans on adding `arcsin`/`arccos` (with the intention of transforming cyclical data to linear data)? More than happy to help out however possible!

**Comment by LeviHarrison** [comment]
As long as there's a use case, which you've provided, I don't see why not.

My current list is `sin`, `cos`, `tan`, `atan2`, `deg`, `rad`, and now `asin` and `acos`.

Thanks for your suggestion!

**Comment by mattxwang** [comment]
Great, thank you so much! Let me know if there's anything I can do to help, and excited to see this come together!

**Comment by roidelapluie** [comment]
I'd like all the trig functions should be documented in a short list like this: https://prometheus.io/docs/prometheus/latest/querying/functions/#aggregation_over_time

We could provide a pi() => scalar function.

**Comment by LeviHarrison** [comment]
I still think `deg` and `rad` might be a nice idea to simplify things, but I guess we could rely on only `pi`.

**Comment by LeviHarrison** [comment]
I just opened #9239, if anyone would like to test it out that would be great!

**Comment by roidelapluie** [comment]
marking not-as-easy-as it looks because of atan2

**Comment by LeviHarrison** [comment]
I've opened #9248 to explore the possibility of an `atan2` binary operator.

**Comment by LeviHarrison** [comment]
With the merge of #9248, as well as #9239 previously, I think this issue can be closed.

**Comment by leonerd** [comment]
Yup, I'm, happy :)

**Comment by LeviHarrison** [comment]
Thanks for all your help!

**Comment by mattxwang** [comment]
Thanks everyone 😊
