### ISSUE TITLE
Prometheus UI throws warning intermittently

### ISSUE THREAD

**Issue by nandakumar-sre** [prometheus/prometheus#9238]
I am running Prometheus (version 2.29.1) in Docker image in Kubernetes environment.
```
~ $ prometheus --version
prometheus, version 2.29.1 (branch: HEAD, revision: dcb07e8eac34b5ea37cd229545000b857f1c1637)
  build user:       root@364730518a4e
  build date:       20210811-14:48:27
  go version:       go1.16.7
  platform:         linux/amd64
```

The Prometheus UI occasionally shows warning of kind "Warning: Unexpected response status when fetching server time: Failed to fetch". Uploading the image below for reference. This errors doesn't show up always but only a few times. I tried turning ON the debug option on log.level for Prometheus pod but no related errors are observed in logs. The resource availability on the node looks good. Anyone else experiencing similar issues or any possible fixes we know of? 

![image](https://user-images.githubusercontent.com/84132955/130457199-8777b6ad-0fd1-4cf0-ae7d-65bdc77304ae.png)

**Comment by LeviHarrison** [comment]
I don't really think it could be an issue with UI, failing to fetch indicates a problem with establishing a connection to the server.

Could you please provide logs from the Network tab in Devtools?

**Comment by nandakumar-sre** [comment]
@LeviHarrison Attached the network logs from Chrome Dev tools for reference.
[prometheus UI error network logs.zip](https://github.com/prometheus/prometheus/files/7033035/prometheus.UI.error.network.logs.zip)

**Comment by LeviHarrison** [comment]
The server time request seems to return what I think is no status code (indicated as `Finished`). I'm not sure what this means, but my guess is still something with the network.

There might be an error message in the Devtools console, could you please check there?

**Comment by nandakumar-sre** [comment]
@LeviHarrison : I see an error stating ` net::ERR_NETWORK_CHANGED ` . I am trying to figure out more about this.  
Any thoughts on the possible causes of this issue? 
![image](https://user-images.githubusercontent.com/84132955/130482091-cf40959d-e438-47db-83eb-fb17f54e5bd5.png)

**Comment by LeviHarrison** [comment]
I believe that `ERR_NETWORK_CHANGED` is an issue with your browser or computer, not Prometheus. There seem to be many different causes so I can't pinpoint one for you.

**Comment by SuperQ** [comment]
It would be useful if the React UI would surface the underlying error here.

**Comment by LeviHarrison** [comment]
@juliusv WDYT? I'm not totally sure we should be surfacing these errors.

**Comment by juliusv** [comment]
To my knowledge we already surface the full error that JavaScript / the browser makes available to us. When the connection fails, "Failed to fetch" is usually the only error message we get from the browser about the request, unfortunately.

Given that we cannot show more information in this case and given that the underlying problem with the connections seems to be not related to Prometheus itself (but `ERR_NETWORK_CHANGED`), I'll close this issue. Feel free to reopen if there are aspects to this that could be handled better on the Prometheus side.
