### ISSUE TITLE
Querying labels that return no results when mixing regex and equality label matches returns results from other series

### ISSUE THREAD

**Issue by pdf** [prometheus/prometheus#924]
The following queries all return the expected results, when there are results to return, and no results when not all label queries match:
```
ALERTS{monitor=~"^validmonitor$"}
ALERTS{instance=~"^validinstance$", monitor=~"^validmonitor$"}
ALERTS{monitor="validmonitor"}
ALERTS{instance="validinstance", monitor="validmonitor"}
ALERTS{monitor=~"^invalidmonitor$"}
ALERTS{instance=~"^invalidinstance$", monitor=~"^invalidmonitor$"}
ALERTS{monitor="invalidmonitor"}
ALERTS{instance="invalidinstance", monitor="invalidmonitor"}
ALERTS{monitor=~"^invalidmonitor$"}
ALERTS{instance=~"^invalidinstance$", monitor=~"^validmonitor$"}
ALERTS{instance="invalidinstance", monitor="validmonitor"}
ALERTS{instance="validinstance" invalidlabel="blah"}
ALERTS{instance=~"validinstance" invalidlabel=~"blah"}
ALERTS{instance="invalidinstance" invalidlabel="blah"}
ALERTS{instance=~"invalidinstance" invalidlabel=~"blah"}
```
Where `validinstance`/`validmonitor` are values that return results, and `invalidinstance`/`invalidmonitor` are values that should not return results, and `invalidlabel` is a label that doesn't exist.  The regex anchors are options, they have no bearing on the issue.

However, mixing regex and equality label matches as in the following queries returns results from completely different series when one of the labels would return results, but the other would not:
```
ALERTS{instance="invalidinstance", monitor=~"^validmonitor$"}
ALERTS{instance=~"^invalidinstance$", monitor="validmonitor"}
ALERTS{instance=~"validinstance" invalidlabel="blah"}
```

I may have missed some permutations above, but I think the scenario should be clear?  I don't have test results with data right now, because I blew away my storage to make sure it was a query language problem rather than some sort of data storage corruption.  This scenario does apply to querying any series though, so if you like I can provide some arbitrary results that illustrate the problem.

This was all tested on v0.15.0rc3

**Comment by juliusv** [comment]
Wow! I can definitely reproduce it with a Prometheus that just scrapes itself and this query:

```
up{job="invalidjob",instance=~"localhost"}
```

...it returns all kinds of time series. Will investigate ASAP, although I might not get to it today because we're on an offsite until Friday.

Thanks for reporting!

**Comment by juliusv** [comment]
Issue identified. Fix PR is out: https://github.com/prometheus/prometheus/pull/927

**Comment by fabxc** [comment]
Thanks for reporting and fixing!

**Comment by pdf** [comment]
Thanks for sneaking in a look at this @juliusv
