### ISSUE TITLE
Automate all steps of the release process

### ISSUE THREAD

**Issue by juliusv** [prometheus/prometheus#926]
So that things like https://github.com/prometheus/prometheus/issues/925 don't happen (forgot to update stable branch). Ideally, this will be automated at some point.

**Comment by jimmidyson** [comment]
I'd like to see docker tags for each each version as they're released. So in addition to what you said on the other thread, I'd like to see a 0.15.0 docker tag, etc as each release happens. Latest would still point to stable & master to master. This would let me stick on a particular version & choose to upgrade when I'm ready after testing in my env etc by changing to the appropriate docker tag. If latest is the only available release tag that makes users vulnerable to breaking changes between releases with no option to pick an actual release version.

**Comment by juliusv** [comment]
@jimmidyson That sounds like a great idea. @discordianfish Is that easy to automate with the Docker Hub? Must be, right? :)

**Comment by jimmidyson** [comment]
Yeah if you're using docker hub automated builds you just add another build pointing to your git tag.

**Comment by discordianfish** [comment]
No, there is no easy way to automate this. You still need to manually create a new tag in the hub for every release. But this in general sounds good and should be put into the release docs. On the long run I would stop using automated builds and just build the images locally and push it. This way we can automate setting the right tags etc.

**Comment by zrml** [comment]
@jimmidyson + 1 on the requested feature.
Thanks

**Comment by jimmidyson** [comment]
@discordianfish We (fabric8) switched to our own builds for exactly that reason. We use circleci.com & works great.

**Comment by TheTincho** [comment]
As I said in IRC, don't forget to update the dependency on client_golang (and possibly make a release there too).

**Comment by fabxc** [comment]
Adjusted the title to our actual goal.

**Comment by discordianfish** [comment]
+1 - I'm happy to take care of the Docker specific parts, but first we need to decide for a CI and build process for the binaries. Once that's done, I can add the docker stuff.

**Comment by brian-brazil** [comment]
I think we can say this is done by now.

**Comment by matthiasr** [comment]
Massive shout-out to @sdurrheimer for that!
