### ISSUE TITLE
Reduce CPU consumption at low cardinality

### ISSUE THREAD

**Issue by whh32** [prometheus/prometheus#9261]
## Proposal
**Use case. Why is this important?**

When we have a large number of low cardinality queries, such as idc and machine survival, uncompressed postinglist will consume a large amount of computing resources in crc32. Should we consider compressing postinglist like lucene or caching frequently used term?
*“Nice to have” is not a good use case. :)*

**Comment by roidelapluie** [comment]
cc @codesome @bboreham do you have any opinion here?

**Comment by codesome** [comment]
We eventually do want to compress the postings list while also increasing the postings to 64bit from the current 32bit. There will likely be reduction in the size with 64bit+compression compared to 32bit+no compression from our earlier experiments, but it wont be a big reduction depending on trade-off with reading performance.

A cache looks like a good idea to try out and benchmark. The cache that I have mind is for `single matcher -> postings list` per block, and if feasible with not so complex code, we could store the postings list compressed in memory to fit more stuff in the cache.

**Comment by bboreham** [comment]
Can you show in a profile where the CPU is being used?

**Comment by whh32** [comment]
> Can you show in a profile where the CPU is being used?

![image](https://user-images.githubusercontent.com/8488141/135408836-68c342b8-e18f-4b4d-a479-77a1c672572a.png)

**Comment by bboreham** [comment]
Are you saying by caching the lookup from matchers->series we can save CRC calculations?
How would you invalidate the cache?

**Comment by npordash** [comment]
The CRC calculations are only done when reading from persisted blocks which are immutable.

I can confirm that I have also observed cpu time being dominated by CRC calculations on setups where you have a lot of alert or recording rules running that touch data beyond the head block.

**Comment by krajorama** [comment]
Hello from the bug scrub: no movement on this for 3 years, will close now. Please follow up if you'd like to work on this issue.
