### ISSUE TITLE
Allow TSDB isolation to be disabled on append

### ISSUE THREAD

**Issue by bboreham** [prometheus/prometheus#9265]
## Proposal
We re-use Prometheus TSDB in Cortex, where I observe sometimes that many ingester goroutines are blocked on `isolation.newAppendID` and `isolation.closeAppend`.  In Cortex, samples are sent over remote write so isolation does not achieve much: parts of the scrape will be sharded to different sends, then sharded again to different ingesters. We do not have distributed transactions over these writes so reads will have partial data anyway.

I would like to add an option to TSDB such that Appenders will stop calling `newAppendID` and `closeAppend` and use 0 as the ID - 0 is already accepted as meaning "no isolation".

**Comment by roidelapluie** [comment]
The plan is to make remote write transactional (sending commits together to remote write): https://docs.google.com/document/d/1UgSNnQYB1TJKVHkrUybEZPDsDl6MYCSiABm71v73Uvs/edit

I would really avoid doing this in cortex as you would need to re-introduce it later.

**Comment by roidelapluie** [comment]
cc @beorn7

**Comment by bboreham** [comment]
We would need to introduce distributed transaction tracking in Cortex too. 

While this is a valid pursuit, I still think it’s ok to have the option to turn it (both) off.

**Comment by darshanime** [comment]
I can work on this (happy to throw away pr if it's decided to not have the flag...)

**Comment by roidelapluie** [comment]
> We would need to introduce distributed transaction tracking in Cortex too.
> 
> While this is a valid pursuit, I still think it’s ok to have the option to turn it (both) off.

Yeah, I am just raising my concern. @codesome and @bwplotka are TSDB maintainers, and @beorn7 has implemented the isolation. I will let them decide.

**Comment by beorn7** [comment]
I have no concerns with offering it as an option on the TSDB level.

**Comment by codesome** [comment]
No concerns as well with this. Cortex (or any distributed remote store) will require more complex isolation mechanism on top of TSDB anyway, so it may or may not need isolation at TSDB level.
