### ISSUE TITLE
Api documentation about how to inegrate any C project with Prometheus

### ISSUE THREAD

**Issue by Rohit2387** [prometheus/prometheus#9266]
Hi,

Is there any documentation present for inegration c programs with promethus,  both sample code and C documentation will be helpful for writing and integrating C Programs.

Br
Rohit

**Comment by LeviHarrison** [comment]
The Prometheus-recognized (but unofficial) C client library is https://github.com/digitalocean/prometheus-client-c, and an example can be found [here](https://github.com/digitalocean/prometheus-client-c/tree/master/example).

**Comment by Rohit2387** [comment]
Hi,

Actually if i undestood the promethus first need to integrate with C program through and then C promethus library expose URL that can be acess by promethus server to collect diffent metrix.


Now for example i Have a c server program that get request and then ack the response with sucess
int main()
{
 socket();
bind();
listen();
while(1)
{
accept();
read();
write("sucess");// now here suppose i want to write metrics w.r.t no of request,no of bytes read...etc ,which API to call...should be helpful
}
}

**Comment by Rohit2387** [comment]
hi @LeviHarrison any comments?
If I want to integrate it ,my module should be divided into 3 part
   Application code which is the service that i want to monitor
   library that expose interface(API/Callback) towards application and Rest interface for accessing metrix 
   UI for preomethus.

Basically how to start this 2 steps:
App.c  
     set_url_for_promethus_acess();
     call_api_to_set_no_of_request_metrics();

**Comment by Rohit2387** [comment]
Hi,

above mention git repo can be used as official c library for promethus.

Br
Rohit

**Comment by cstyan** [comment]
The client libraries provide functionality for exposing metrics over HTTP and generating those metrics in your applications code. Prometheus itself just needs to know about the endpoint your application is exposing metrics on, and scrapes them over HTTP. 

Levi's comment seems to provide all the necessary links at the moment. If you still have additional questions please try one of the community locations or the C client libraries issues.
