### ISSUE TITLE
Missing documentation for `role: endpointslice` in kubernetes_sd_config

### ISSUE THREAD

**Issue by valyala** [prometheus/prometheus#9269]
The https://github.com/prometheus/prometheus/pull/6838 added `role: endpointslice` for `kubernetes_sd_config` in [Prometheus v2.21.0](https://github.com/prometheus/prometheus/blob/main/CHANGELOG.md#2210--2020-09-11) a year ago. It would be great if this new role would be documented at https://prometheus.io/docs/prometheus/latest/configuration/configuration/#kubernetes_sd_config similar to other Prometheus service discovery roles.

The related issue - https://github.com/prometheus/prometheus/issues/7572

**Comment by roidelapluie** [comment]
thanks!
cc @brancz

**Comment by la3mmchen** [comment]
I tried to write documentation to this as referenced in https://github.com/prometheus/prometheus/pull/9436

**Comment by brancz** [comment]
Closed by #9436
