### ISSUE TITLE
Getting started documentation doesn't work

### ISSUE THREAD

**Issue by drawks** [prometheus/prometheus#928]
I just tried to follow the "Getting Started" steps from prometheus.io and was greeted with the following when trying to start prometheus the first time:

```
$ ./prometheus -config.file=prometheus.yml
prometheus, version 0.15.0 (branch: HEAD, revision: a59b7ac)
  build user:       julius@desktop
  build date:       20150722-19:27:55
  go version:       1.4.2
INFO[0000] Loading configuration file prometheus.yml     file=main.go line=173
ERRO[0000] Couldn't load configuration (-config.file=prometheus.yml): open prometheus.yml: no such file or directory  file=main.go line=177
ERRO[0000] Note: The configuration format has changed with version 0.14. Please see the documentation (http://prometheus.io/docs/operating/configuration/) and the provided configuration migration tool (https://github.com/prometheus/migrate).  file=main.go line=178
```

While the error does give some advice on how to proceed it seems sub-optimal for the example configuration to not work with the current released version of the software, especially when the step previous was instructions on cloning github and building the master from source.

**Comment by drawks** [comment]
doh! my own mistake

**Comment by abhiwat** [comment]
I found same error. Could you share you mistake,please???
I think I mistake same thing...

**Comment by juliusv** [comment]
@abhiwat I'm not @drawks, but from his error message, the error looks quite clear: `open prometheus.yml: no such file or directory`. It just sounds like there was no `prometheus.yml` file at all in his working directory :)

**Comment by drawks** [comment]
Yeah, I typoed the filename, then didn't notice the error immediately because I was target fixated on:
```
ERRO[0000] Note: The configuration format has changed with version 0.14. Please see the documentation (http://prometheus.io/docs/operating/configuration/) and the provided configuration migration tool (https://github.com/prometheus/migrate).  file=main.go line=178
```
