### ISSUE TITLE
Checksum for prometheus-2.29.2.darwin-amd64.tar does not match the checksum provided in the sha256sum file

### ISSUE THREAD

**Issue by dark-shade** [prometheus/prometheus#9297]
**What did you do?**
Got the checksum for prometheus-2.29.2.darwin-amd64.tar, it does not match the checksum provided in the sha256sum file. Verified for other tars, they matched. Please see the attached screenshot.

**What did you expect to see?**
Checksum should have matched. Not sure if someone forgot to update it for darwin-amd64 in the sha256sum file or if there is some other underlying issue.

<img width="1537" alt="Screen Shot 2021-09-03 at 10 43 56 AM" src="https://user-images.githubusercontent.com/3988800/132033073-ccd5107e-4eca-47cc-a96c-9557f0ed2039.png">

**Comment by roidelapluie** [comment]
Where did you get your release? It works as expected for me:

```
$ sha256sum prometheus-2.29.2.darwin-amd64.tar.gz 

810a94974be44f92d6c3ba1b7604513ef0a2c1a159bd10afc50da25370813302  prometheus-2.29.2.darwin-amd64.tar.gz
```

**Comment by roidelapluie** [comment]
ooh your issue is that you have already run *gunzip*. You are comparing the checksum of the *.tar* with the *.tar.gz*.
