### ISSUE TITLE
Missing MetricMetaData in Golang Package

### ISSUE THREAD

**Issue by TomL-dev** [prometheus/prometheus#9302]
**What did you do?**

I'm trying to convert Prometheus RemoteWrite requests to OpenTelemetry format. In the protoformat from the WriteRequest: https://github.com/prometheus/prometheus/blob/main/prompb/remote.proto
i see there is a MetricMetaData field. however if i check the golang package: https://pkg.go.dev/github.com/prometheus/prometheus/prompb#WriteRequest
i don't see the MetricMetaData in there. 

I'm wondering where the metadata is in the golang package

**Comment by LeviHarrison** [comment]
The pkg.go.dev documentation is unfortunately far out of date because we last tagged a Go module release in 2018.

Here's a version generated today: https://gowalker.org/github.com/prometheus/prometheus/prompb#WriteRequest

**Comment by LeviHarrison** [comment]
If you `go get github.com/prometheus/prometheus@v1.8.2-0.20210720123808-b1ed4a0a663d` (see https://github.com/thanos-io/thanos/blob/1205a222cb1e1be4862ef39b4c3a9c538056cf83/go.mod#L63) it should be up to date.

**Comment by roidelapluie** [comment]
You can use go get github.com/prometheus/prometheus@release-2.30 to get a specific release.
