### ISSUE TITLE
Test failure in armel

### ISSUE THREAD

**Issue by TheTincho** [prometheus/prometheus#931]
Hi,

It seems I can get this test to fail all the time, with or without Debian patches, both in 0.14.0 and 0.15.0.

```
~/prometheus$ GOPATH=/home/tincho/prometheus/.build/root/gopath go test -v github.com/prometheus/prometheus/retrieval -run TestTargetScrapeWithFullChannel
=== RUN TestTargetScrapeWithFullChannel
--- FAIL: TestTargetScrapeWithFullChannel (0.03s)
	target_test.go:163: Expected target error "ingestion channel full", actual: "read tcp 127.0.0.1:36487: i/o timeout"
FAIL
exit status 1
FAIL	github.com/prometheus/prometheus/retrieval	0.059s
```

The strace is pretty difficult to read, with the goroutines seemingly switching threads many times.. But I see the server replying with a bunch of metrics, in 6 chunks. Then I see the client (same thread, no less), reading 3 of these chunks and then doing nothing, until a bit later it closes the socket without finishing the read. Maybe this is related to chunking issues?

You can see the interesting part of the strace here: http://paste.debian.net/286505/

**Comment by brian-brazil** [comment]
This is flaky for me on amd64, so likely a race that's always lost on ARM.

**Comment by fabxc** [comment]
This one will be gone in its current form in #1064

**Comment by beorn7** [comment]
OK, closing here then. If it shows up in similar form again, we'll notice...
