### ISSUE TITLE
Add exemplars support on the remote write receiver endpoint

### ISSUE THREAD

**Issue by secat** [prometheus/prometheus#9317]
## Proposal
The Prometheus remote write receiver endpoint currently does not append exemplars. This issue proposes to add exemplars support on the remote write receiver.

According to @csmarchbanks, it should be fairly easy to add a loop for exemplars like the one done for samples here: https://github.com/prometheus/prometheus/blob/0111aa987e600c861dff34e4d24e891ed63d0535/storage/remote/write_handler.go#L77

It should also take into consideration that the `exemplar-storage` feature is enabled.

**Comment by yeya24** [comment]
I'd like to work on this issue if no one is working on it.

**Comment by codesome** [comment]
@yeya24 #9319 was opened shortly after. Feel free to pick some other issue :) thanks

**Comment by LeviHarrison** [comment]
Implemented in #9319
