### ISSUE TITLE
Support for transactional remote write

### ISSUE THREAD

**Issue by Harkishen-Singh** [prometheus/prometheus#9327]
## Proposal
**Use case. Why is this important?**
Atomic writes for Prometheus scraped data to remote storage.

[Here](https://tsdb.co/txn-rw-design) is the design doc, that contains the plan and discussions around the topic.

**Status: Review** phase

**Comment by beorn7** [comment]
Perhaps link the doc under https://prometheus.io/docs/introduction/design-doc/ ?

**Comment by Harkishen-Singh** [comment]
That will be a good place. How do we add to that list?

**Comment by beorn7** [comment]
Just update https://github.com/prometheus/docs/blob/master/content/docs/introduction/design-doc.md and open a PR for that repo.

**Comment by bboreham** [comment]
Reviewed at bug-scrub:
There's not much detail here, and the point is captured under #6333, so closing this issue.
