### ISSUE TITLE
Go mod version

### ISSUE THREAD

**Issue by tjq857** [prometheus/prometheus#9336]
When I want to obtain dependencies through go mod, I am prompted that the dependent version does not exist. The reason is that although the version number is greater than or equal to 2, the v2 suffix is ​​not added to the go mod

**Comment by LeviHarrison** [comment]
Maybe https://github.com/prometheus/prometheus/issues/9302#issuecomment-914367303 can help?

**Comment by roidelapluie** [comment]
Yes, please see above comment. you can do `go get github.com/prometheus/prometheus@release-2.30`.
