### ISSUE TITLE
promtool: too many files open when backfilling a long time range

### ISSUE THREAD

**Issue by kokes** [prometheus/prometheus#9337]
**What did you do?**

I wanted to backfill a larger dataset using `promtool tsdb create-blocks-from openmetrics`

**What did you expect to see?**

All blocks created without issue.

**What did you see instead? Under which circumstances?**

```
01FFJ65SW4MQV0Z9TB7QDYW91E  1631455224000  1631462364001  1h59m0.001s  120          1            1            783
block creation: process blocks: get blocks: 2 errors: corrupted block 01FFJ65SW4MQV0Z9TB7QDYW91E: fcntl data/01FFJ65SW4MQV0Z9TB7QDYW91E/chunks: too many open files; corrupted block 01FFJ65TX4J9MD71X0AWJE2C2F: fcntl data/01FFJ65TX4J9MD71X0AWJE2C2F/chunks: too many open files
```

**Environment**

macOS, Alpine Linux

* System information:

Darwin 19.6.0 x86_64

* Prometheus version:

```
$ promtool --version
promtool, version 2.29.2 (branch: non-git, revision: non-git)
  build user:       brew@iMac-Pro
  build date:       20210827-15:14:42
  go version:       go1.17
  platform:         darwin/amd64
 ```

(2.30.0 was released at the time of writing - tried it with that as well later on and encountered the same issue)

* Logs:

See above.

---

**Reproducer**

Generate some sample data that span a large number of 2-hour blocks:

```python
import random
import datetime as dt

FILENAME = "metrics.prom"
METRIC = "some_random_metric_total"
N = 10000

if __name__ == "__main__":
    ts = dt.datetime.utcnow() - dt.timedelta(minutes=N)
    with open(FILENAME, "wt", encoding="utf-8") as fw:
        for _ in range(N):
            value = random.randint(1000, 2000)
            fw.write(f"{METRIC} {value} {int(ts.timestamp())}\n")
            ts += dt.timedelta(minutes=1)
        fw.write("# EOF")
```

Then with a low ulimit (which happens to be the default on my Mac)

```
$ ulimit -n
256
```

promtool will err having too many files open, can be seen live via `lsof -p $(pgrep promtool)`. Works just fine on a system with a higher ulimit (e.g. stock Alpine).

---

I tried introspecting the code to understand where the file handlers get opened and if/when they get closed, but I got nowhere :( If the handlers need to be open (e.g. if incoming data are not time-ordered?), I'd expect promtool to be either ulimit-aware or have a fixed size pool of handlers (or a combination of both). But I don't really understand the storage mechanics to give an appropriate piece of advice.

**Comment by roidelapluie** [comment]
Yes, I guess we could evaluate how many FD's can be needed and issue a warning if we hit this.

**Comment by roidelapluie** [comment]
We have looked at this again in the bug triage meeting.

Part of the solution would be #8518. Another workaround would be to use `./promtool tsdb create-blocks-from  --max-block-duration 16h` so you have less blocks, therefore less fd's needed.

**Comment by codesome** [comment]
Since Prometheus uses block ranges `2h, 6h, 18h, ...` (multiple of 3), maybe `18h` would be a better choice to align well.

**Comment by bboreham** [comment]
Reviewed again at the bug-scrub:
No further comments in nearly 3 years, and it seems we have an improvement and a workaround, so closing.
If it is still a problem please add the details and we can re-open.
