### ISSUE TITLE
Russian support in prometheus export 

### ISSUE THREAD

**Issue by masterwishx** [prometheus/prometheus#9346]
using Prometheus docker in unraid (linux x64) + Prometheus MSI Afterburner Exporter
when using **MSI Afterburner in Russian** in main comp + msI Afterburner Remote Server

then having error in prometheus ( 500 internal server error) (was collected befor with same name and value)
[
![1550778889_01111 jpg cd34d7f61cfe11c4de366a837f90c02f](https://user-images.githubusercontent.com/28630321/133460465-04f57333-3456-40e4-8880-6d5956796943.jpg)
![2075479502_011 jpg 97814ed8f973478631260d8222ae69ca](https://user-images.githubusercontent.com/28630321/133460481-d46d2072-1f00-4b70-aca7-7a5f6749f90a.jpg)
](url)

when changed MSI Afterburner to English the errors is gone .
but having  same vulues of afterburner and some of (go values)
![Буфер обмена0111](https://user-images.githubusercontent.com/28630321/133461457-8fac1910-b8e1-4876-ac32-40b8813ab857.jpg)

1. How to fix go_gc values ?
2. Will be possible **to add Russian langue support for Prometheus export**?
3. 
Thanks

**Comment by roidelapluie** [comment]
MSI Afterburner is not something we manage, please contact their developers.

**Comment by masterwishx** [comment]
Msi aftererburner it's for example only. 
But in prometheus document it can export only
(a-zA-Z)metrics, so it's only English metrics that can be handled for export Right?
That why I asked for Russian metrics for export.

**Comment by beorn7** [comment]
Label _values_ can be any UTF-8 string. Metric and label _names_ have to match the regexp `[a-zA-Z_:][a-zA-Z0-9_:]*`. That's very deeply baked into Prometheus and even PromQL and not going to change any time soon.

If you really cannot avoid characters outside of that regexp, you could put them into a label value as a work around.
