### ISSUE TITLE
linux tarball is not namespaced

### ISSUE THREAD

**Issue by robey** [prometheus/prometheus#935]
If you `tar xvf` the distribution tarball, at least as of 0.15.1, it will dump a bunch of files in the current folder, not a distribution folder. Normally, a distribution tarball should contain all the files inside a folder with the same name (so `prometheus-0.15.1.linux-amd64.tar.gz` would unpack into a new folder called `prometheus-0.15.1.linux-amd64`.

**Comment by beorn7** [comment]
Yeah, historical reasons for that. Originally, the "bunch of files" was just one, the `prometheus` binary. Now we have `promtool`, too, and the console templates... I guess we have to rethink the packaging.

**Comment by juliusv** [comment]
Other historical reason: we didn't want any versioning in the contained files because we just want to unpack them into the same place always and use the same run script, etc. That would get more annoying when unpacking to a versioned directory. @matthiasr opinion?

**Comment by beorn7** [comment]
@juliusv That's essentially a SoundCloudism... As @robey said, it's very weird to publicly distribute tar balls that don't create a directory for their content when unpacked...

**Comment by robey** [comment]
For other services, we have deploy scripts do something like this:

```sh
ETCD_FOLDER=$(echo "$ETCD_TARBALL" | sed -e 's/.tar.gz//')
[ -x "$ETCD_FOLDER" ] || tar xf "$ETCD_TARBALL"
rm -f etcd && ln -s "$ETCD_FOLDER" etcd
```

Then "etcd" is always a symlink to the currently-installed version, which has the advantage of telling us at a glance which version is running, and lets us keep old versions around for rollback. I think this is really common (we certainly didn't invent it). So far, prometheus is the only service I've deployed that doesn't make unix-style tarball folders like this.

**Comment by juliusv** [comment]
Ok, sounds good to me then. But then we should do this for all our projects for consistency, including those that have only one binary file. @robey wanna give it a try?

**Comment by matthiasr** [comment]
This should go into the next minor release then, it _is_ a breaking change.

**Comment by matthiasr** [comment]
PS: with proper packages everything will be ok :)

**Comment by robey** [comment]
Unless your build is more complicated than it looks, I think that will do it.

**Comment by juliusv** [comment]
Yep, should be super straightforward.
