### ISSUE TITLE
Link all Docker images to base image on docker hub (and trigger builds once manually)

### ISSUE THREAD

**Issue by juliusv** [prometheus/prometheus#937]
...to resolve issues fixed in https://github.com/prometheus/prometheus_cli/issues/8.

@discordianfish

**Comment by discordianfish** [comment]
@juliusv I've change the title; That's what I actually meant

**Comment by brian-brazil** [comment]
@sdurrheimer Is this still relevant?

**Comment by grobie** [comment]
Not relevant anymore with promu.
