### ISSUE TITLE
Report a coding issue that uses reference to loop iterator variable

### ISSUE THREAD

**Issue by guodongli-google** [prometheus/prometheus#9432]
**What did you do?**

Run a static analyzer DeepGo, which reports a finding on the related code.

**What did you see instead? Under which circumstances?**

At https://github.com/prometheus/prometheus/blob/main/pkg/rulefmt/rulefmt.go#L85-86,
https://github.com/prometheus/prometheus/blob/a7d499e19a932f4f7cf14e8b8c935dd43d2a9830/pkg/rulefmt/rulefmt.go#L85-L86

Within the loop `for i, r := range g.Rules`, variable `r` is shared by all the loop iterations, as described in the Go specification (https://golang.org/ref/spec).
All instances of `&r` and its field addresses such as `&r.Record` within the loop may refer to the last rule updated by the loop. 
```
		for i, r := range g.Rules {
			for _, node := range r.Validate() {
```
Within `r.Validate()`, the return value `nodes` includes multiple instances of the same `&r.Record`:
https://github.com/prometheus/prometheus/blob/a7d499e19a932f4f7cf14e8b8c935dd43d2a9830/pkg/rulefmt/rulefmt.go#L135-L140

Next, all the nodes returned by `r.Validate()` are appended into the `errs` slice, which escapes the loop:
https://github.com/prometheus/prometheus/blob/a7d499e19a932f4f7cf14e8b8c935dd43d2a9830/pkg/rulefmt/rulefmt.go#L93-L97

As a consequence, `errs` may hold multiple instances of the same rule's fields.

For example, supposed `g.Rules = [r1, r2]`,  code
```
		for i, r := range g.Rules {
			for _, node := range r.Validate() {
				...
				errs = append(errs, &Error{
					Group:    g.Name,
					Rule:     i + 1,
					RuleName: ruleName.Value,
					Err:      node,
				})
			}
		}
```
produces
```
errs = [
  &Error{..., Err: WrappedError{ ..., node:  &r2.Record} },
  &Error{..., Err: WrappedError{ ..., node:  &r2.Record} },
]
```
That is, it contains two instances of `&r2.Record`, while the correct result should be:
```
errs = [
  &Error{..., Err: WrappedError{ ..., node:  &r1.Record} },
  &Error{..., Err: WrappedError{ ..., node:  &r2.Record} },
]
```

**What did you expect to see?**

A fix is to avoid reusing the shared variable item:
```
		for i, r := range g.Rules {
			for _, node := range g.Rules[i].Validate() {
				...
```

**Found by #deepgo.**

**Comment by codesome** [comment]
Thanks for the report, nice catch!

**Comment by Howie59** [comment]
i can do this @codesome

**Comment by Howie59** [comment]
assign

**Comment by codesome** [comment]
@Howie59 please go ahead!

**Comment by LeviHarrison** [comment]
Fixed in https://github.com/prometheus/prometheus/pull/9483.
