### ISSUE TITLE
PromQL is not deterministic

### ISSUE THREAD

**Issue by free** [prometheus/prometheus#9450]
Was trying to debug why a Grafana Heatmap panel for a histogram that clearly only had recorded observations in the 1M-2M and 2M-5M ranges looked like this:

![Screenshot from 2021-10-05 12-53-51](https://user-images.githubusercontent.com/32070098/136010304-9e6ee95b-b8f8-45bd-a09e-fddf7c1103df.png)

You'll notice that the 2 buckets above had on the order of 30K observations each, whereas the other non-zero ones all show up as `0.0` (rounded). I also noticed that on refresh the `0.0` buckets shift around randomly. The underlying query is nothing fancy:

```
sum by (le) (
  avg by(le, some_label) (
    increase(metric[1m])
  )
)
```

Long story short, I looked at a specific timestamp and played around with the query and what seems to happen is that aggregations (such as `sum` and `avg`) produce randomly ordered results. If those results are in turn aggregated again, the result of that aggregation may be different depending on the order of the inputs.

Take for example the following query:

```
sum(
  avg by(foo) (
      label_replace(up{job="prometheus"}, "foo", "1", "job", "prometheus") * 0.99999999999998
    or
      label_replace(up{job="prometheus"}, "foo", "2", "job", "prometheus") * 100
    or
      label_replace(up{job="prometheus"}, "foo", "3", "job", "prometheus") * 100
  )
)
```

On any single-Prometheus deployment, this will sometimes yield `200.99999999999997`, sometimes `201`. The reason for that can be seen in [this playground example](https://play.golang.org/p/yZAGWt5OfiQ): `0.99999999999998 + 100.0 + 100.0 != 100.0 + 100.0 + 0.99999999999998`.

AFAICT the fix is to simply sort the output of `evaluator.aggregation()` by labels. Then in the example above `avg` will always produce the same output at a given timestamp. Not only that, but in the case of aggregating histogram buckets, the labels other than `le` will be sorted consistently across buckets, so the result of the aggregation will be exactly the same for buckets that have the same number of observations.

**Comment by free** [comment]
As a side-note, while adding a bit of overhead to aggregations, this would fix the annoyance of Prometheus sometimes producing nicely sorted, sometimes randomly shuffled results.

**Comment by free** [comment]
Alternately, in order to avoid unnecessary overhead, one could simply sort the inputs to aggregations instead. If already sorted (such as when read from the TSDB) that would take linear time. If not, O(N * log(N)).

**Comment by roidelapluie** [comment]
https://github.com/prometheus/prometheus/pull/9459
