### ISSUE TITLE
Unary negation of range vectors (rate and resets of decreasing metrics)

### ISSUE THREAD

**Issue by ruuda** [prometheus/prometheus#9453]
## Proposal

Allow computing `rate()`, `resets()`, and `increase()` for metrics that count down rather than up.

One way to achieve this, would be to allow unary negation on range vectors. Currently `rate(-decreasing_metric[5m])` and `rate(0 - decreasing_metric[5m])` cause a parse error, but if this were allowed, it would enable computing the rates of decreasing metrics. Note, `-rate(decreasing_metric[5m])` is not at all the same thing!

Negating a range vector would negate all of its values.

**Use case. Why is this important?**

I have an exporter that monitors the balance of an account. The balance is decreasing continuously, as a system is spending from the account. Periodically, the account gets topped up. I want to compute its spending rate, and _only_ spending, regardless of when the account gets topped up. If I compute this using `delta` or `deriv`, then if the account was topped up inside the time window selected for the range vector, then the spending rate is no longer accurate, and may even go negative.

**Comment by roidelapluie** [comment]
Unfortunately, a bank account is fundamentally a gauge, which is incompatible with rate(). I have read your message and you are aware of that, but I fundamentally think that even if we would allow unary negation of vectors, you would stumble accross other issues.

As a workaround, you could try:

`clamp_min(decreasing_metric - decreasing_metric offset 5m, 0)` but it would not take into account "counter resets".
Another possibility would be to use subqueries:
`rate((-decreasing_metric)[5m:])`, with other tradeoffs.

**Comment by ruuda** [comment]
Aah, a subquery is a nice workaround, thanks!
