### ISSUE TITLE
web/ui: 77 vulnerabilities (16 moderate, 37 high, 24 critical)

### ISSUE THREAD

**Issue by Dentrax** [prometheus/prometheus#9472]
**What did you do?**

`make build` on commit b4175f72316db74dcd26f3a33770e63f2e57081b

* Logs:
```
make build
cd web/ui && npm install

up to date, audited 2418 packages in 13s

173 packages are looking for funding
  run `npm fund` for details

77 vulnerabilities (16 moderate, 37 high, 24 critical)
```

Are there any ongoing discussion or PR related to `npm` vulnerabilities? Should we concern about this?

**Comment by LeviHarrison** [comment]
Thanks for the report. cc @juliusv @Nexucis, but from what I've heard these aren't the biggest deal. We also upgrade our dependencies every release anyway.
