### ISSUE TITLE
`atan2` is currently not allowed between scalar values

### ISSUE THREAD

**Issue by roidelapluie** [prometheus/prometheus#9485]
In PromQL testing I noticed that `atan2` is currently not allowed between scalar values like `1 atan2 2` (`operator "atan2" not allowed for Scalar operations`). Is there a good reason for this? I would just treat it like any of the other arithmetic operators, which also work between scalars.

_Originally posted by @juliusv in https://github.com/prometheus/prometheus/issues/9248#issuecomment-939952244_

**Comment by ziollek** [comment]
@LeviHarrison I've added PR according to your suggestion: https://github.com/prometheus/prometheus/pull/9515
