### ISSUE TITLE
Increase produces different results for different range

### ISSUE THREAD

**Issue by krasi-georgiev** [prometheus/prometheus#9486]
<details>
<summary>Raw output from <b>telliot_trader_eth_converted{reporter="0xDD6D1C35518fc955BBBeb52C5c1f5Fb4E16D7EAF"}</b>
</summary>

{
    "state": "Done",
    "series": [
      {
        "meta": {
          "preferredVisualisationType": "table"
        },
        "refId": "B",
        "length": 1,
        "fields": [
          {
            "name": "Time",
            "type": "time",
            "config": {},
            "values": [
              1633927683000
            ],
            "state": null
          },
          {
            "name": "__name__",
            "config": {
              "filterable": true
            },
            "type": "string",
            "values": [
              "telliot_trader_eth_converted"
            ],
            "state": {
              "displayName": "__name__"
            }
          },
          {
            "name": "instance",
            "config": {
              "filterable": true
            },
            "type": "string",
            "values": [
              "10.244.0.57:9090"
            ],
            "state": {
              "displayName": "instance"
            }
          },
          {
            "name": "job",
            "config": {
              "filterable": true
            },
            "type": "string",
            "values": [
              "report-master"
            ],
            "state": {
              "displayName": "job"
            }
          },
          {
            "name": "reporter",
            "config": {
              "filterable": true
            },
            "type": "string",
            "values": [
              "0xDD6D1C35518fc955BBBeb52C5c1f5Fb4E16D7EAF"
            ],
            "state": {
              "displayName": "reporter"
            }
          },
          {
            "name": "Value #B",
            "type": "number",
            "config": {},
            "values": [
              4.1986
            ],
            "state": {
              "displayName": "Value #B"
            }
          }
        ]
      },
      {
        "meta": {
          "preferredVisualisationType": "graph"
        },
        "refId": "B",
        "length": 56,
        "fields": [
          {
            "name": "Time",
            "type": "time",
            "config": {},
            "values": [
              1633926855000,
              1633926870000,
              1633926885000,
              1633926900000,
              1633926915000,
              1633926930000,
              1633926945000,
              1633926960000,
              1633926975000,
              1633926990000,
              1633927005000,
              1633927020000,
              1633927035000,
              1633927050000,
              1633927065000,
              1633927080000,
              1633927095000,
              1633927110000,
              1633927125000,
              1633927140000,
              1633927155000,
              1633927170000,
              1633927185000,
              1633927200000,
              1633927215000,
              1633927230000,
              1633927245000,
              1633927260000,
              1633927275000,
              1633927290000,
              1633927305000,
              1633927320000,
              1633927335000,
              1633927350000,
              1633927365000,
              1633927380000,
              1633927395000,
              1633927410000,
              1633927425000,
              1633927440000,
              1633927455000,
              1633927470000,
              1633927485000,
              1633927500000,
              1633927515000,
              1633927530000,
              1633927545000,
              1633927560000,
              1633927575000,
              1633927590000,
              1633927605000,
              1633927620000,
              1633927635000,
              1633927650000,
              1633927665000,
              1633927680000
            ],
            "state": null
          },
          {
            "name": "Value",
            "type": "number",
            "config": {
              "displayNameFromDS": "telliot_trader_eth_converted{instance=\"10.244.0.57:9090\", job=\"report-master\", reporter=\"0xDD6D1C35518fc955BBBeb52C5c1f5Fb4E16D7EAF\"}"
            },
            "labels": {
              "instance": "10.244.0.57:9090",
              "job": "report-master",
              "reporter": "0xDD6D1C35518fc955BBBeb52C5c1f5Fb4E16D7EAF"
            },
            "values": [
              4.0241,
              4.0241,
              4.0241,
              4.0241,
              4.0241,
              4.0241,
              4.0241,
              4.0241,
              4.0241,
              4.0241,
              4.0241,
              4.0241,
              4.0241,
              4.0241,
              4.0241,
              4.0241,
              4.0241,
              4.0241,
              4.0241,
              4.0241,
              4.0241,
              4.0241,
              4.0241,
              4.1986,
              4.1986,
              4.1986,
              4.1986,
              4.1986,
              4.1986,
              4.1986,
              4.1986,
              4.1986,
              4.1986,
              4.1986,
              4.1986,
              4.1986,
              4.1986,
              4.1986,
              4.1986,
              4.1986,
              4.1986,
              4.1986,
              4.1986,
              4.1986,
              4.1986,
              4.1986,
              4.1986,
              4.1986,
              4.1986,
              4.1986,
              4.1986,
              4.1986,
              4.1986,
              4.1986,
              4.1986,
              4.1986
            ],
            "state": {
              "calcs": {
                "sum": 231.10809999999998,
                "max": 4.1986,
                "min": 4.0241,
                "logmin": 4.0241,
                "mean": 4.126930357142856,
                "last": 4.1986,
                "first": 4.0241,
                "lastNotNull": 4.1986,
                "firstNotNull": 4.0241,
                "count": 56,
                "nonNullCount": 56,
                "allIsNull": false,
                "allIsZero": false,
                "range": 0.1745000000000001,
                "diff": 0.1745000000000001,
                "delta": 0.1745000000000001,
                "step": 0,
                "diffperc": 0.04336373350562862,
                "previousDeltaUp": true
              },
              "displayName": "telliot_trader_eth_converted{instance=\"10.244.0.57:9090\", job=\"report-master\", reporter=\"0xDD6D1C35518fc955BBBeb52C5c1f5Fb4E16D7EAF\"}"
            }
          }
        ],
        "name": "telliot_trader_eth_converted{instance=\"10.244.0.57:9090\", job=\"report-master\", reporter=\"0xDD6D1C35518fc955BBBeb52C5c1f5Fb4E16D7EAF\"}"
      }
    ],
    "annotations": [],
    "request": {
      "app": "explore",
      "dashboardId": 0,
      "timezone": "utc",
      "startTime": 1633952908797,
      "interval": "15s",
      "intervalMs": 15000,
      "panelId": "Q-cd81dace-291d-407b-9dcc-1f1b2783fe38-0Q-b0bb7a99-e20a-4548-bd68-beac321c0a0e-1Q-2f5d8626-b814-4328-baad-7d27c8c0f46f-2Q-7f89b16e-1772-4f07-8e33-533f08659cae-3Q-c7017f11-7c17-42a4-bfb5-e80ed4ad13c1-4Q-bbff9114-1bb2-4bf1-9ad0-18867a4e0e28-5",
      "targets": [
        {
          "refId": "A",
          "key": "Q-cd81dace-291d-407b-9dcc-1f1b2783fe38-0",
          "exemplar": true,
          "expr": "increase (  last_over_time(telliot_trader_eth_converted{reporter=\"0xDD6D1C35518fc955BBBeb52C5c1f5Fb4E16D7EAF\"}[5m:])  - on(reporter)  last_over_time(telliot_trackerTellor_submit_cost[5m:])[5m:]) ",
          "hide": true
        },
        {
          "refId": "B",
          "key": "Q-b0bb7a99-e20a-4548-bd68-beac321c0a0e-1",
          "exemplar": true,
          "expr": "telliot_trader_eth_converted{reporter=\"0xDD6D1C35518fc955BBBeb52C5c1f5Fb4E16D7EAF\"}",
          "hide": false
        },
        {
          "refId": "C",
          "key": "Q-2f5d8626-b814-4328-baad-7d27c8c0f46f-2",
          "exemplar": true,
          "expr": "telliot_trackerTellor_submit_cost{reporter=\"0xDD6D1C35518fc955BBBeb52C5c1f5Fb4E16D7EAF\"}",
          "hide": true
        },
        {
          "refId": "D",
          "key": "Q-7f89b16e-1772-4f07-8e33-533f08659cae-3",
          "exemplar": true,
          "expr": "(increase(telliot_trader_eth_converted{reporter=\"0xDD6D1C35518fc955BBBeb52C5c1f5Fb4E16D7EAF\"}[5m])>0)  - on(reporter) (increase(telliot_trackerTellor_submit_cost{reporter=\"0xDD6D1C35518fc955BBBeb52C5c1f5Fb4E16D7EAF\"}[5m])>0)",
          "hide": true
        },
        {
          "refId": "E",
          "key": "Q-c7017f11-7c17-42a4-bfb5-e80ed4ad13c1-4",
          "exemplar": true,
          "expr": "increase(telliot_trader_eth_converted{reporter=\"0xDD6D1C35518fc955BBBeb52C5c1f5Fb4E16D7EAF\"}[5m])",
          "hide": true
        },
        {
          "refId": "F",
          "key": "Q-bbff9114-1bb2-4bf1-9ad0-18867a4e0e28-5",
          "exemplar": true,
          "expr": "increase(telliot_trackerTellor_submit_cost{reporter=\"0xDD6D1C35518fc955BBBeb52C5c1f5Fb4E16D7EAF\"}[5m])",
          "hide": true
        }
      ],
      "range": {
        "from": "2021-10-11T04:34:26.070Z",
        "to": "2021-10-11T04:48:02.098Z",
        "raw": {
          "from": "2021-10-11T04:34:26.070Z",
          "to": "2021-10-11T04:48:02.098Z"
        }
      },
      "requestId": "explore_left",
      "rangeRaw": {
        "from": "2021-10-11T04:34:26.070Z",
        "to": "2021-10-11T04:48:02.098Z"
      },
      "scopedVars": {
        "__interval": {
          "text": "15s",
          "value": "15s"
        },
        "__interval_ms": {
          "text": 15000,
          "value": 15000
        }
      },
      "maxDataPoints": 1860,
      "liveStreaming": false,
      "endTime": 1633952909208
    },
    "timeRange": {
      "from": "2021-10-11T04:34:26.070Z",
      "to": "2021-10-11T04:48:02.098Z",
      "raw": {
        "from": "2021-10-11T04:34:26.070Z",
        "to": "2021-10-11T04:48:02.098Z"
      }
    },
    "timings": {
      "dataProcessingTime": 0.04500001668930054
    },
    "graphFrames": [
      {
        "meta": {
          "preferredVisualisationType": "graph"
        },
        "refId": "B",
        "length": 56,
        "fields": [
          {
            "name": "Time",
            "type": "time",
            "config": {},
            "values": [
              1633926855000,
              1633926870000,
              1633926885000,
              1633926900000,
              1633926915000,
              1633926930000,
              1633926945000,
              1633926960000,
              1633926975000,
              1633926990000,
              1633927005000,
              1633927020000,
              1633927035000,
              1633927050000,
              1633927065000,
              1633927080000,
              1633927095000,
              1633927110000,
              1633927125000,
              1633927140000,
              1633927155000,
              1633927170000,
              1633927185000,
              1633927200000,
              1633927215000,
              1633927230000,
              1633927245000,
              1633927260000,
              1633927275000,
              1633927290000,
              1633927305000,
              1633927320000,
              1633927335000,
              1633927350000,
              1633927365000,
              1633927380000,
              1633927395000,
              1633927410000,
              1633927425000,
              1633927440000,
              1633927455000,
              1633927470000,
              1633927485000,
              1633927500000,
              1633927515000,
              1633927530000,
              1633927545000,
              1633927560000,
              1633927575000,
              1633927590000,
              1633927605000,
              1633927620000,
              1633927635000,
              1633927650000,
              1633927665000,
              1633927680000
            ],
            "state": null
          },
          {
            "name": "Value",
            "type": "number",
            "config": {
              "displayNameFromDS": "telliot_trader_eth_converted{instance=\"10.244.0.57:9090\", job=\"report-master\", reporter=\"0xDD6D1C35518fc955BBBeb52C5c1f5Fb4E16D7EAF\"}"
            },
            "labels": {
              "instance": "10.244.0.57:9090",
              "job": "report-master",
              "reporter": "0xDD6D1C35518fc955BBBeb52C5c1f5Fb4E16D7EAF"
            },
            "values": [
              4.0241,
              4.0241,
              4.0241,
              4.0241,
              4.0241,
              4.0241,
              4.0241,
              4.0241,
              4.0241,
              4.0241,
              4.0241,
              4.0241,
              4.0241,
              4.0241,
              4.0241,
              4.0241,
              4.0241,
              4.0241,
              4.0241,
              4.0241,
              4.0241,
              4.0241,
              4.0241,
              4.1986,
              4.1986,
              4.1986,
              4.1986,
              4.1986,
              4.1986,
              4.1986,
              4.1986,
              4.1986,
              4.1986,
              4.1986,
              4.1986,
              4.1986,
              4.1986,
              4.1986,
              4.1986,
              4.1986,
              4.1986,
              4.1986,
              4.1986,
              4.1986,
              4.1986,
              4.1986,
              4.1986,
              4.1986,
              4.1986,
              4.1986,
              4.1986,
              4.1986,
              4.1986,
              4.1986,
              4.1986,
              4.1986
            ],
            "state": {
              "calcs": {
                "sum": 231.10809999999998,
                "max": 4.1986,
                "min": 4.0241,
                "logmin": 4.0241,
                "mean": 4.126930357142856,
                "last": 4.1986,
                "first": 4.0241,
                "lastNotNull": 4.1986,
                "firstNotNull": 4.0241,
                "count": 56,
                "nonNullCount": 56,
                "allIsNull": false,
                "allIsZero": false,
                "range": 0.1745000000000001,
                "diff": 0.1745000000000001,
                "delta": 0.1745000000000001,
                "step": 0,
                "diffperc": 0.04336373350562862,
                "previousDeltaUp": true
              },
              "displayName": "telliot_trader_eth_converted{instance=\"10.244.0.57:9090\", job=\"report-master\", reporter=\"0xDD6D1C35518fc955BBBeb52C5c1f5Fb4E16D7EAF\"}"
            }
          }
        ],
        "name": "telliot_trader_eth_converted{instance=\"10.244.0.57:9090\", job=\"report-master\", reporter=\"0xDD6D1C35518fc955BBBeb52C5c1f5Fb4E16D7EAF\"}"
      }
    ],
    "tableFrames": [
      {
        "meta": {
          "preferredVisualisationType": "table"
        },
        "refId": "B",
        "length": 1,
        "fields": [
          {
            "name": "Time",
            "type": "time",
            "config": {},
            "values": [
              1633927683000
            ],
            "state": null
          },
          {
            "name": "__name__",
            "config": {
              "filterable": true
            },
            "type": "string",
            "values": [
              "telliot_trader_eth_converted"
            ],
            "state": {
              "displayName": "__name__"
            }
          },
          {
            "name": "instance",
            "config": {
              "filterable": true
            },
            "type": "string",
            "values": [
              "10.244.0.57:9090"
            ],
            "state": {
              "displayName": "instance"
            }
          },
          {
            "name": "job",
            "config": {
              "filterable": true
            },
            "type": "string",
            "values": [
              "report-master"
            ],
            "state": {
              "displayName": "job"
            }
          },
          {
            "name": "reporter",
            "config": {
              "filterable": true
            },
            "type": "string",
            "values": [
              "0xDD6D1C35518fc955BBBeb52C5c1f5Fb4E16D7EAF"
            ],
            "state": {
              "displayName": "reporter"
            }
          },
          {
            "name": "Value #B",
            "type": "number",
            "config": {},
            "values": [
              4.1986
            ],
            "state": {
              "displayName": "Value #B"
            }
          }
        ]
      }
    ],
    "logsFrames": [],
    "traceFrames": [],
    "nodeGraphFrames": [],
    "graphResult": [
      {
        "meta": {
          "preferredVisualisationType": "graph"
        },
        "refId": "B",
        "length": 56,
        "fields": [
          {
            "name": "Time",
            "type": "time",
            "config": {},
            "values": [
              1633926855000,
              1633926870000,
              1633926885000,
              1633926900000,
              1633926915000,
              1633926930000,
              1633926945000,
              1633926960000,
              1633926975000,
              1633926990000,
              1633927005000,
              1633927020000,
              1633927035000,
              1633927050000,
              1633927065000,
              1633927080000,
              1633927095000,
              1633927110000,
              1633927125000,
              1633927140000,
              1633927155000,
              1633927170000,
              1633927185000,
              1633927200000,
              1633927215000,
              1633927230000,
              1633927245000,
              1633927260000,
              1633927275000,
              1633927290000,
              1633927305000,
              1633927320000,
              1633927335000,
              1633927350000,
              1633927365000,
              1633927380000,
              1633927395000,
              1633927410000,
              1633927425000,
              1633927440000,
              1633927455000,
              1633927470000,
              1633927485000,
              1633927500000,
              1633927515000,
              1633927530000,
              1633927545000,
              1633927560000,
              1633927575000,
              1633927590000,
              1633927605000,
              1633927620000,
              1633927635000,
              1633927650000,
              1633927665000,
              1633927680000
            ],
            "state": null
          },
          {
            "name": "Value",
            "type": "number",
            "config": {
              "displayNameFromDS": "telliot_trader_eth_converted{instance=\"10.244.0.57:9090\", job=\"report-master\", reporter=\"0xDD6D1C35518fc955BBBeb52C5c1f5Fb4E16D7EAF\"}"
            },
            "labels": {
              "instance": "10.244.0.57:9090",
              "job": "report-master",
              "reporter": "0xDD6D1C35518fc955BBBeb52C5c1f5Fb4E16D7EAF"
            },
            "values": [
              4.0241,
              4.0241,
              4.0241,
              4.0241,
              4.0241,
              4.0241,
              4.0241,
              4.0241,
              4.0241,
              4.0241,
              4.0241,
              4.0241,
              4.0241,
              4.0241,
              4.0241,
              4.0241,
              4.0241,
              4.0241,
              4.0241,
              4.0241,
              4.0241,
              4.0241,
              4.0241,
              4.1986,
              4.1986,
              4.1986,
              4.1986,
              4.1986,
              4.1986,
              4.1986,
              4.1986,
              4.1986,
              4.1986,
              4.1986,
              4.1986,
              4.1986,
              4.1986,
              4.1986,
              4.1986,
              4.1986,
              4.1986,
              4.1986,
              4.1986,
              4.1986,
              4.1986,
              4.1986,
              4.1986,
              4.1986,
              4.1986,
              4.1986,
              4.1986,
              4.1986,
              4.1986,
              4.1986,
              4.1986,
              4.1986
            ],
            "state": {
              "calcs": {
                "sum": 231.10809999999998,
                "max": 4.1986,
                "min": 4.0241,
                "logmin": 4.0241,
                "mean": 4.126930357142856,
                "last": 4.1986,
                "first": 4.0241,
                "lastNotNull": 4.1986,
                "firstNotNull": 4.0241,
                "count": 56,
                "nonNullCount": 56,
                "allIsNull": false,
                "allIsZero": false,
                "range": 0.1745000000000001,
                "diff": 0.1745000000000001,
                "delta": 0.1745000000000001,
                "step": 0,
                "diffperc": 0.04336373350562862,
                "previousDeltaUp": true
              },
              "displayName": "telliot_trader_eth_converted{instance=\"10.244.0.57:9090\", job=\"report-master\", reporter=\"0xDD6D1C35518fc955BBBeb52C5c1f5Fb4E16D7EAF\"}"
            }
          }
        ],
        "name": "telliot_trader_eth_converted{instance=\"10.244.0.57:9090\", job=\"report-master\", reporter=\"0xDD6D1C35518fc955BBBeb52C5c1f5Fb4E16D7EAF\"}"
      }
    ],
    "tableResult": {
      "meta": {
        "preferredVisualisationType": "table"
      },
      "refId": "B",
      "length": 1,
      "fields": [
        {
          "name": "Time",
          "type": "time",
          "config": {},
          "values": [
            1633927683000
          ],
          "state": null
        },
        {
          "name": "__name__",
          "config": {
            "filterable": true
          },
          "type": "string",
          "values": [
            "telliot_trader_eth_converted"
          ],
          "state": {
            "displayName": "__name__"
          }
        },
        {
          "name": "instance",
          "config": {
            "filterable": true
          },
          "type": "string",
          "values": [
            "10.244.0.57:9090"
          ],
          "state": {
            "displayName": "instance"
          }
        },
        {
          "name": "job",
          "config": {
            "filterable": true
          },
          "type": "string",
          "values": [
            "report-master"
          ],
          "state": {
            "displayName": "job"
          }
        },
        {
          "name": "reporter",
          "config": {
            "filterable": true
          },
          "type": "string",
          "values": [
            "0xDD6D1C35518fc955BBBeb52C5c1f5Fb4E16D7EAF"
          ],
          "state": {
            "displayName": "reporter"
          }
        },
        {
          "name": "Value #B",
          "type": "number",
          "config": {},
          "values": [
            4.1986
          ],
          "state": {
            "displayName": "Value #B"
          }
        }
      ]
    },
    "logsResult": null
  }

</details>

```
increase(telliot_trader_eth_converted{reporter="0xDD6D1C35518fc955BBBeb52C5c1f5Fb4E16D7EAF"}[20m])
```
produces the correct result of 0.175

```
increase(telliot_trader_eth_converted{reporter="0xDD6D1C35518fc955BBBeb52C5c1f5Fb4E16D7EAF"}[10m])
```
produces the incorrect result of 0.176

```
increase(telliot_trader_eth_converted{reporter="0xDD6D1C35518fc955BBBeb52C5c1f5Fb4E16D7EAF"}[5m])
```
produces the incorrect result of 0.177

* Prometheus version:

	v2.28.1

* Alertmanager version:

	insert output of `alertmanager --version` here (if relevant to the issue)

* Prometheus configuration file:
```
scrape_interval: 5s
```

Happy to give access to the prometheus server if needed. Ping me on slack

**Comment by roidelapluie** [comment]
mmh I wonder if we do something wrong here. We shoud try to write your metrics into actual tests in promql/testdata to better see what's going on.

**Comment by roidelapluie** [comment]
It would help if you can provide us with some testing data, e.g. using `promtool test rules`.

**Comment by krasi-georgiev** [comment]
it is in the first comment

**Comment by krasi-georgiev** [comment]
@roidelapluie you now have all the info that is needed right?

**Comment by roidelapluie** [comment]
In the first comment it is not the actual data from Prometheus, but some extract from Grafana.

Could you run telliot_trader_eth_converted{reporter="0xDD6D1C35518fc955BBBeb52C5c1f5Fb4E16D7EAF"}[30m] in the `Prometheus console` and provide me the result, so I have the exact values with the timestamps?

So far it looks like this is probably just prometheus extrapolation at work.

**Comment by krasi-georgiev** [comment]
With this query the results like this
Begining is 0.9645 
End is 1.2262
so increase should be: 0.2617

This is what increase returns:
increase(telliot_trader_eth_converted{reporter="0xDD6D1C35518fc955BBBeb52C5c1f5Fb4E16D7EAF"}[20m])
0.26279497907949784
increase(telliot_trader_eth_converted{reporter="0xDD6D1C35518fc955BBBeb52C5c1f5Fb4E16D7EAF"}[30m])
0.2624289693593314


<details>
<summary>Data</summary>

{"status":"success","data":{"resultType":"matrix","result":[{"metric":{"__name__":"telliot_trader_eth_converted","instance":"10.244.0.111:9090","job":"report-master","reporter":"0xDD6D1C35518fc955BBBeb52C5c1f5Fb4E16D7EAF"},"values":[[1637784878.542,"0.9645"],[1637784883.542,"0.9645"],[1637784888.542,"0.9645"],[1637784893.542,"0.9645"],[1637784898.542,"0.9645"],[1637784903.542,"0.9645"],[1637784908.542,"0.9645"],[1637784913.542,"0.9645"],[1637784918.542,"0.9645"],[1637784923.542,"0.9645"],[1637784928.542,"0.9645"],[1637784933.542,"0.9645"],[1637784938.542,"0.9645"],[1637784943.542,"0.9645"],[1637784948.542,"0.9645"],[1637784953.542,"0.9645"],[1637784958.542,"0.9645"],[1637784963.542,"0.9645"],[1637784968.542,"0.9645"],[1637784973.542,"0.9645"],[1637784978.542,"0.9645"],[1637784983.542,"0.9645"],[1637784988.542,"0.9645"],[1637784993.542,"0.9645"],[1637784998.542,"0.9645"],[1637785003.542,"0.9645"],[1637785008.542,"0.9645"],[1637785013.542,"0.9645"],[1637785018.542,"0.9645"],[1637785023.542,"0.9645"],[1637785028.542,"0.9645"],[1637785033.542,"0.9645"],[1637785038.542,"0.9645"],[1637785043.542,"0.9645"],[1637785048.542,"0.9645"],[1637785053.542,"0.9645"],[1637785058.542,"0.9645"],[1637785063.542,"0.9645"],[1637785068.542,"0.9645"],[1637785073.542,"0.9645"],[1637785078.542,"0.9645"],[1637785083.542,"0.9645"],[1637785088.542,"0.9645"],[1637785093.542,"0.9645"],[1637785098.542,"0.9645"],[1637785103.542,"0.9645"],[1637785108.542,"0.9645"],[1637785113.542,"0.9645"],[1637785118.542,"0.9645"],[1637785123.542,"0.9645"],[1637785128.542,"0.9645"],[1637785133.542,"0.9645"],[1637785138.542,"0.9645"],[1637785143.542,"0.9645"],[1637785148.542,"0.9645"],[1637785153.542,"0.9645"],[1637785158.542,"0.9645"],[1637785163.542,"0.9645"],[1637785168.542,"0.9645"],[1637785173.542,"0.9645"],[1637785178.542,"0.9645"],[1637785183.542,"0.9645"],[1637785188.542,"0.9645"],[1637785193.542,"0.9645"],[1637785198.542,"0.9645"],[1637785203.542,"0.9645"],[1637785208.542,"0.9645"],[1637785213.542,"0.9645"],[1637785218.542,"0.9645"],[1637785223.542,"0.9645"],[1637785228.542,"0.9645"],[1637785233.542,"0.9645"],[1637785238.542,"0.9645"],[1637785243.542,"0.9645"],[1637785248.542,"0.9645"],[1637785253.542,"0.9645"],[1637785258.542,"0.9645"],[1637785263.542,"0.9645"],[1637785268.542,"0.9645"],[1637785273.542,"0.9645"],[1637785278.542,"0.9645"],[1637785283.542,"0.9645"],[1637785288.542,"0.9645"],[1637785293.542,"0.9645"],[1637785298.542,"0.9645"],[1637785303.542,"0.9645"],[1637785308.542,"0.9645"],[1637785313.542,"0.9645"],[1637785318.542,"0.9645"],[1637785323.542,"0.9645"],[1637785328.542,"0.9645"],[1637785333.542,"0.9645"],[1637785338.542,"0.9645"],[1637785343.542,"0.9645"],[1637785348.542,"0.9645"],[1637785353.542,"0.9645"],[1637785358.542,"0.9645"],[1637785363.542,"0.9645"],[1637785368.542,"0.9645"],[1637785373.542,"0.9645"],[1637785378.542,"0.9645"],[1637785383.542,"0.9645"],[1637785388.542,"0.9645"],[1637785393.542,"0.9645"],[1637785398.542,"0.9645"],[1637785403.542,"0.9645"],[1637785408.542,"0.9645"],[1637785413.542,"0.9645"],[1637785418.542,"0.9645"],[1637785423.542,"0.9645"],[1637785428.542,"0.9645"],[1637785433.542,"0.9645"],[1637785438.542,"0.9645"],[1637785443.542,"0.9645"],[1637785448.542,"0.9645"],[1637785453.542,"0.9645"],[1637785458.542,"0.9645"],[1637785463.542,"0.9645"],[1637785468.542,"0.9645"],[1637785473.542,"0.9645"],[1637785478.542,"0.9645"],[1637785483.542,"0.9645"],[1637785488.542,"0.9645"],[1637785493.542,"0.9645"],[1637785498.542,"0.9645"],[1637785503.542,"0.9645"],[1637785508.542,"0.9645"],[1637785513.542,"0.9645"],[1637785518.542,"0.9645"],[1637785523.542,"0.9645"],[1637785528.542,"0.9645"],[1637785533.542,"0.9645"],[1637785538.542,"0.9645"],[1637785543.542,"0.9645"],[1637785548.542,"0.9645"],[1637785553.542,"0.9645"],[1637785558.542,"0.9645"],[1637785563.542,"0.9645"],[1637785568.542,"0.9645"],[1637785573.542,"0.9645"],[1637785578.542,"0.9645"],[1637785583.542,"0.9645"],[1637785588.542,"0.9645"],[1637785593.542,"0.9645"],[1637785598.542,"0.9645"],[1637785603.542,"0.9645"],[1637785608.542,"0.9645"],[1637785613.542,"0.9645"],[1637785618.542,"0.9645"],[1637785623.542,"0.9645"],[1637785628.542,"0.9645"],[1637785633.542,"0.9645"],[1637785638.542,"0.9645"],[1637785643.542,"0.9645"],[1637785648.542,"0.9645"],[1637785653.542,"0.9645"],[1637785658.542,"0.9645"],[1637785663.542,"0.9645"],[1637785668.542,"0.9645"],[1637785673.542,"0.9645"],[1637785678.542,"0.9645"],[1637785683.542,"0.9645"],[1637785688.542,"0.9645"],[1637785693.542,"0.9645"],[1637785698.542,"0.9645"],[1637785703.542,"0.9645"],[1637785708.542,"0.9645"],[1637785713.542,"0.9645"],[1637785718.542,"0.9645"],[1637785723.542,"0.9645"],[1637785728.542,"0.9645"],[1637785733.542,"0.9645"],[1637785738.542,"0.9645"],[1637785743.542,"0.9645"],[1637785748.542,"0.9645"],[1637785753.542,"0.9645"],[1637785758.542,"0.9645"],[1637785763.542,"0.9645"],[1637785768.542,"0.9645"],[1637785773.542,"0.9645"],[1637785778.542,"0.9645"],[1637785783.542,"0.9645"],[1637785788.542,"0.9645"],[1637785793.542,"0.9645"],[1637785798.542,"0.9645"],[1637785803.542,"0.9645"],[1637785808.542,"0.9645"],[1637785813.542,"0.9645"],[1637785818.542,"0.9645"],[1637785823.542,"0.9645"],[1637785828.542,"0.9645"],[1637785833.542,"0.9645"],[1637785838.542,"0.9645"],[1637785843.542,"0.9645"],[1637785848.542,"0.9645"],[1637785853.542,"0.9645"],[1637785858.542,"0.9645"],[1637785863.542,"0.9645"],[1637785868.542,"0.9645"],[1637785873.542,"0.9645"],[1637785878.542,"0.9645"],[1637785883.542,"0.9645"],[1637785888.542,"0.9645"],[1637785893.542,"0.9645"],[1637785898.542,"0.9645"],[1637785903.542,"0.9645"],[1637785908.542,"0.9645"],[1637785913.542,"0.9645"],[1637785918.542,"0.9645"],[1637785923.542,"0.9645"],[1637785928.542,"0.9645"],[1637785933.542,"0.9645"],[1637785938.542,"0.9645"],[1637785943.542,"0.9645"],[1637785948.542,"0.9645"],[1637785953.542,"0.9645"],[1637785958.542,"0.9645"],[1637785963.542,"0.9645"],[1637785968.542,"0.9645"],[1637785973.542,"0.9645"],[1637785978.542,"0.9645"],[1637785983.542,"0.9645"],[1637785988.542,"0.9645"],[1637785993.542,"0.9645"],[1637785998.542,"0.9645"],[1637786003.542,"0.9645"],[1637786008.542,"0.9645"],[1637786013.542,"0.9645"],[1637786018.542,"0.9645"],[1637786023.542,"0.9645"],[1637786028.542,"0.9645"],[1637786033.542,"0.9645"],[1637786038.542,"0.9645"],[1637786043.542,"0.9645"],[1637786048.542,"0.9645"],[1637786053.542,"0.9645"],[1637786058.542,"0.9645"],[1637786063.542,"0.9645"],[1637786068.542,"0.9645"],[1637786073.542,"0.9645"],[1637786078.542,"0.9645"],[1637786083.542,"0.9645"],[1637786088.542,"0.9645"],[1637786093.542,"0.9645"],[1637786098.542,"0.9645"],[1637786103.542,"0.9645"],[1637786108.542,"0.9645"],[1637786113.542,"0.9645"],[1637786118.542,"0.9645"],[1637786123.542,"0.9645"],[1637786128.542,"0.9645"],[1637786133.542,"0.9645"],[1637786138.542,"0.9645"],[1637786143.542,"0.9645"],[1637786148.542,"0.9645"],[1637786153.542,"0.9645"],[1637786158.542,"0.9645"],[1637786163.542,"0.9645"],[1637786168.542,"0.9645"],[1637786173.542,"0.9645"],[1637786178.542,"0.9645"],[1637786183.542,"0.9645"],[1637786188.542,"0.9645"],[1637786193.542,"0.9645"],[1637786198.542,"0.9645"],[1637786203.542,"0.9645"],[1637786208.542,"0.9645"],[1637786213.542,"0.9645"],[1637786218.542,"0.9645"],[1637786223.542,"0.9645"],[1637786228.542,"0.9645"],[1637786233.542,"0.9645"],[1637786238.542,"0.9645"],[1637786243.542,"0.9645"],[1637786248.542,"0.9645"],[1637786253.542,"0.9645"],[1637786258.542,"0.9645"],[1637786263.542,"0.9645"],[1637786268.542,"0.9645"],[1637786273.542,"0.9645"],[1637786278.542,"0.9645"],[1637786283.542,"0.9645"],[1637786288.542,"0.9645"],[1637786293.542,"0.9645"],[1637786298.542,"0.9645"],[1637786303.542,"0.9645"],[1637786308.542,"0.9645"],[1637786313.542,"0.9645"],[1637786318.542,"0.9645"],[1637786323.542,"0.9645"],[1637786328.542,"1.2262"],[1637786333.542,"1.2262"],[1637786338.542,"1.2262"],[1637786343.542,"1.2262"],[1637786348.542,"1.2262"],[1637786353.542,"1.2262"],[1637786358.542,"1.2262"],[1637786363.542,"1.2262"],[1637786368.542,"1.2262"],[1637786373.542,"1.2262"],[1637786378.542,"1.2262"],[1637786383.542,"1.2262"],[1637786388.542,"1.2262"],[1637786393.542,"1.2262"],[1637786398.542,"1.2262"],[1637786403.542,"1.2262"],[1637786408.542,"1.2262"],[1637786413.542,"1.2262"],[1637786418.542,"1.2262"],[1637786423.542,"1.2262"],[1637786428.542,"1.2262"],[1637786433.542,"1.2262"],[1637786438.542,"1.2262"],[1637786443.542,"1.2262"],[1637786448.542,"1.2262"],[1637786453.542,"1.2262"],[1637786458.542,"1.2262"],[1637786463.542,"1.2262"],[1637786468.542,"1.2262"],[1637786473.542,"1.2262"],[1637786478.542,"1.2262"],[1637786483.542,"1.2262"],[1637786488.542,"1.2262"],[1637786493.542,"1.2262"],[1637786498.542,"1.2262"],[1637786503.542,"1.2262"],[1637786508.544,"1.2262"],[1637786513.542,"1.2262"],[1637786518.542,"1.2262"],[1637786523.542,"1.2262"],[1637786528.542,"1.2262"],[1637786533.542,"1.2262"],[1637786538.542,"1.2262"],[1637786543.542,"1.2262"],[1637786548.542,"1.2262"],[1637786553.542,"1.2262"],[1637786558.542,"1.2262"],[1637786563.542,"1.2262"],[1637786568.542,"1.2262"],[1637786573.542,"1.2262"],[1637786578.542,"1.2262"],[1637786583.542,"1.2262"],[1637786588.542,"1.2262"],[1637786593.542,"1.2262"],[1637786598.542,"1.2262"],[1637786603.542,"1.2262"],[1637786608.542,"1.2262"],[1637786613.542,"1.2262"],[1637786618.542,"1.2262"],[1637786623.542,"1.2262"],[1637786628.542,"1.2262"],[1637786633.542,"1.2262"],[1637786638.542,"1.2262"],[1637786643.542,"1.2262"],[1637786648.542,"1.2262"],[1637786653.542,"1.2262"],[1637786658.542,"1.2262"],[1637786663.542,"1.2262"],[1637786668.542,"1.2262"],[1637786673.542,"1.2262"]]}]}}

</details>

**Comment by krasi-georgiev** [comment]
ping @roidelapluie
