### ISSUE TITLE
React UI: Starting Screen flashes before going to requested page

### ISSUE THREAD

**Issue by LeviHarrison** [prometheus/prometheus#9522]
**What did you do?**

I opened the Prometheus web UI on a version that has the starting screen (for example https://prometheus-react.netlify.app).

**What did you expect to see?**

I expected to be taken right to the graph page.

**What did you see instead? Under which circumstances?**

The starting screen flashed for a second before forwarding me to the graph page.

* Prometheus version:

	main (1270b87)

This happens because the UI starts out on the starting screen and only moves off it once a request to `/ready` responds with a `200` status. I wonder if we could have the request happen in the background instead and just delay all requests on other pages until it responds (and if the server isn't ready _then_ go to the starting screen).

**Comment by kitarp29** [comment]
Can you assign this issue to me?
I have some experience in ReactJS, I think I can help.
@LeviHarrison

**Comment by LeviHarrison** [comment]
Feel free to work on it. Thanks!

**Comment by kitarp29** [comment]
Thanks.
