### ISSUE TITLE
dynamic  labels support

### ISSUE THREAD

**Issue by taotao365s** [prometheus/prometheus#9542]
## Proposal
**Use case. Why is this important?**

we want to use the same metric, but use different tag in some case, for user or developer, because we have a lot of metric in our application, we cannot list them , after all,  the metric is still growing in the feature and now.

*“Nice to have” is not a good use case. :)*

**Comment by roidelapluie** [comment]
Could you please clarify your need, your programming language, and whether you are looking for a solution in the Prometheus server (that would be relabeling) or in client libraries (that would be declaring variables with labeled gauges/counters I think). In this case, can you also share some code that you find "very very terrible"? Thank you!

**Comment by bboreham** [comment]
Reviewed at the bug-scrub meeting; the issue was never clarified so closing.
