### ISSUE TITLE
external_labels not being ignored on clash

### ISSUE THREAD

**Issue by jamessewell** [prometheus/prometheus#9544]
When I have a scrape target which sets a label which clashes with an external_label it seems the external_label is always presented.

This is contrary to the documentation:

```
# Note that any globally configured "external_labels" are unaffected by this
# setting. In communication with external systems, they are always applied only
# when a time series does not have a given label yet and are ignored otherwise.
```

Seems to be an issue on all versions

**Comment by LeviHarrison** [comment]
https://github.com/prometheus/prometheus/pull/9479, which has been recently merged to fix https://github.com/prometheus/prometheus/issues/5861, might resolve this.

**Comment by roidelapluie** [comment]
It's not related.
