### ISSUE TITLE
Unary expressions like `+++++++---------++++++1` shouldn't be valid

### ISSUE THREAD

**Issue by juliusv** [prometheus/prometheus#955]
E.g. `+++++++---------++++++1` returns `-1`. Guess it should be a parse error?

**Comment by juliusv** [comment]
@fabxc

**Comment by juliusv** [comment]
Reason is the recursion here: https://github.com/prometheus/prometheus/blob/5279d50d92c7259b1a20e6978f871827bbdfcbe1/promql/parse.go#L554

**Comment by fabxc** [comment]
Yes. This is very much intended. Why would this be a parsing error?

**Comment by brian-brazil** [comment]
In that case, why is `-If` a parse error? It's not currently documented that we have unary operators.

**Comment by fabxc** [comment]
`-If` is a runtime panic based on an unrelated bug. It's fixed in #954.
Unary expressions exist for number literals. Applying it to a vector or matrix errors "expected type scalar in unary expression, got vector". This is no new behavior.

**Comment by juliusv** [comment]
Ok yeah, though Go, JS, and some other languages don't allow this notation, Python seemingly does. And you can make a case for that it makes sense. So fine to close this from my side then.

**Comment by juliusv** [comment]
(but yeah, it might be cool do allow `-foo` as well)

**Comment by fabxc** [comment]
Yes, I'll open a separate issue for that.
