### ISSUE TITLE
Consider using more strict formatters like gci and gofumpt

### ISSUE THREAD

**Issue by invidian** [prometheus/prometheus#9557]
To bring more uniformity to the codebase and to make it easier for developers already using more strict formatters, I'd like to propose enabling `gofumpt` and `gci` linters in golangci-lint configuration and to format all Go source files in this repository using those programs.

Those formatters are compatible with more popular `gofmt`, meaning after applying `gofumpt` formatting, `gofmt` won't try to revert it.

If one has automatic formatting configured in their IDE, working with not formatted files becomes annoying if one wants to produce clear commits (without formatting fixes on the side).

Here you can see applied formatting: https://github.com/prometheus/prometheus/commit/282990880615ab698fe9583b21ae52e19c333f46

I'm happy to open PR configuring linter and fixing current formatting.

**Comment by roidelapluie** [comment]
This sounds reasonable to me, but we share the config with all the projects. An email to the prometheus-developers mailing list is appropriate.

**Comment by invidian** [comment]
Make sense. I'll post it to the mailing list.

**Comment by roidelapluie** [comment]
Now, it is a good time to finalize this and merge it.

**Comment by invidian** [comment]
>Now, it is a good time to finalize this and merge it.


Resolved conflicts on the PR then.

>If you agree on changes from 2688951, I'll also enable an extra rule to enforce that and merge the formatting commits.

What to do with https://github.com/prometheus/prometheus/pull/9563/commits/72672c9e47882bce75dc4b83f98cee62cdd6b741 commit then?

**Comment by roidelapluie** [comment]
We take -s
