### ISSUE TITLE
Template language for rules files

### ISSUE THREAD

**Issue by mwitkow-io** [prometheus/prometheus#958]
I know this smells of template hell, but for our use case of federation (where we only federate precomputed metrics) we end up writing a lot of boiler plate.

Are you guys planning on providing a canonical rules file template language or should we bake something specific just for us? :)

**Comment by fabxc** [comment]
To be honest, I think building something for yourselves is the most realistic option.
Introducing a template system for rule files that then mixes up with other template languages of people's config management etc. might do more harm then good.

**Comment by brian-brazil** [comment]
I don't think we'll ever add a template language, as I'm sure you've experienced it's easy for well intentioned factoring to gradually get out of control and land in template hell. If you feel the need to automatically generate rules, you can to do so with your configuration management language.

If you're ending up with a lot of boiler plate, it's possible you aren't taking full advantage of labels.

**Comment by beorn7** [comment]
Perhaps we should have a "non-roadmap" section on prometheus.io containing all the non-goals?

There are a number of features that are obvious to ask for but which we do not intend to implement for not so obvious reasons...

**Comment by brian-brazil** [comment]
That sounds like a good idea.

**Comment by mwitkow-io** [comment]
The problem we're trying to solve is generating the pre-aggregations on our scrape-level proms that later on get sucked in by our master proms.

We end up with a much of similar rules that just end with `:min`, `:max`, `:sum` and `:avg`. Aggregating sums of histogram buckets (and `_sum` and `_count`) as well leads to tons of copy-pasting and "missing comma"-liek typos.

If you guys explicitly state a template language for prometheus as a non-goal, we'll roll our own :) I just wanted to make sure we wouldn't duplicate efforts :)

**Comment by beorn7** [comment]
Filed https://github.com/prometheus/docs/issues/149 for the offroad-map. :)
