### ISSUE TITLE
Add label manipulation functions

### ISSUE THREAD

**Issue by brian-brazil** [prometheus/prometheus#959]
We need functions in promql to allow playing around with labels, to allow for more advanced use cases such as dealing with mismatched label names.

I propose the following functions:
- `label_set(vector, labelname, labelvalue)`
- `label_copy(vector, dest_labelname, src_labelname)`
- `label_join(vector, dest_labelname, separator, src_labelname...)`
- `label_replace(vector, dest_labelname, replacement, src_labelame, regex)`

Combining `label_join` and `label_replace` you can do any merging and mixing you want of labels. The alternative to having two functions would be to offer a way to use go templates, which I don't think is wise for performance reasons.

**Comment by brian-brazil** [comment]
Set and copy can be done with replace, so we could have just join and replace.

**Comment by juliusv** [comment]
I'm going to implement `label_replace` now as a first thing. `label_join` having an arbitrary number of source labels is IIUC the only reason why we want the `dest_...`, `src_...` arguments in that order, right?

**Comment by fabxc** [comment]
dest first is also the order of Go's builtin `copy()`. I find it easier to read in this context, too.

**Comment by juliusv** [comment]
Yeah, that order is common in some contexts. Ok, will keep it like that then.

**Comment by brian-brazil** [comment]
> label_join having an arbitrary number of source labels is IIUC the only reason why we want the dest_..., src_... arguments in that order, right?

Yes

**Comment by varunpatro** [comment]
Hi what's the status of this PR? Only `label_replace` has been completed am I right?
I am keen on working on this PR for Hacktoberfest.

**Comment by brian-brazil** [comment]
That's correct. `label_join` is what's needed to complete this PR, as it allows all possible functionality. At some vague future date we may add the other two as syntactic sugar around label_replace.

**Comment by varunpatro** [comment]
Alright thanks. I'll work on `label_join` then. Should I work on `master` or some other branch?

**Comment by fabxc** [comment]
Awesome, you can file that PR straight to master.

**Comment by brian-brazil** [comment]
To answer your answer on IRC: https://github.com/prometheus/prometheus/blob/master/promql/functions.go#L819

Allow for up to say 8 labels to be specified, that should be more than enough.

**Comment by hryamzik** [comment]
How about ```label_remove```? I'm playing around labels and miss this function indeed.

**Comment by brian-brazil** [comment]
That's not something that should be handled at the PromQL level. You should either exclude `instance` from your grouping labels in the alertmanager, or use aggregation to remove the label in the alert.

**Comment by hryamzik** [comment]
I can't do this as other metrics are instance-related. But I've found a way to do this:

```
label_replace(certificate_expiration_date,"instance", "", "instance", ".*")
```

**Comment by brian-brazil** [comment]
May I suggest using the blackbox exporter for this? It exports SSL cert expiry dates, and the labels should be nicer to work with.

**Comment by hryamzik** [comment]
@brian-brazil good point, I didn't mention this exporter, thank you!

But I can't see a way to check domain expiration and ssl certificates on multiple hosts.

**Comment by brian-brazil** [comment]
It does support multiple hosts, but doesn't do domain expiration currently. Would need to be careful on that one, don't want to overwhelm Whois.

**Comment by hryamzik** [comment]
I simply run cron scripts once an hour. Whois is a nightmare with it's format so I had to implement failing on parse error. 

```bash
#!/bin/bash
# Scipt checks domain expiration dates.
# Checked with reg.ru and GoDaddy.com
# whois is required

scriptname=${0##*/}
metricname=${scriptname%.*}


function get_date_from_string {
    if exp_date=$(date -d $2 +%s)
    then
        printf 'domain_check_expiration_date{name="%s"} %s\ndomain_check_success{name="%s"} 1\n' $1 $exp_date $1
    else
        echo "invalid date '$2'" > /dev/stderr
        printf 'domain_check_expiration_date{name="%s"} 0\ndomain_check_success{name="%s"} 0\n' $1 $1
    fi
}

function check_expiration {
    whois=$(whois $1)
    if exp_date_raw=$(echo "$whois"|egrep -i 'Registry Expiry Date|Registrar Registration Expiration Date')
    then
        # generic & godaddy
        # echo "godaddy or generic" > /dev/stderr
        get_date_from_string $1 $(echo $exp_date_raw|awk -F ': ' {'print $2'})
    elif exp_date_raw=$(echo "$whois"|egrep -i 'free-date')
    then
        # reg.ru
        # echo "reg.ru" > /dev/stderr
        get_date_from_string $1 $(echo $exp_date_raw|awk -F ': ' {'print $2'}|tr '.' '-')
    else
        echo "Unsupported whois format for $1" > /dev/stderr
        printf 'domain_check_expiration_date{name="\s"} 0\ndomain_check_success{name="\s"} 0\n' $1 $1
    fi
}


echo -n '' > /tmp/${metricname}.prom.$$
{% for domain in check_domains %}
check_expiration {{ domain }} >> /tmp/${metricname}.prom.$$
{% endfor %}

cat <<EOF>> /tmp/${metricname}.prom.$$
${metricname}_completion_time $(date +%s)
EOF
mv -v /tmp/${metricname}.prom.$$ /var/lib/node_exporter/${metricname}.prom
```

**Comment by leonerd** [comment]
Would there be any mileage in allowing multiple destination labels somehow too? E.g. if you wanted to split an "address" label into separate host + port fields. Or to specifically remove a label by setting its value to the empty string.

Also another thing is I quite often I end up doing a simple match of `(.*)` and a replacement of `$1`, effectively just renaming a label. Maybe a convenient shortcut of

    label_rename(vector, dest_labelname, src_labelname)

**Comment by brian-brazil** [comment]
We have join and replace now which are the minimal set of functions.

**Comment by bric3** [comment]
Adding a label don't work if there is no label. I'm trying to integrate a metric into a table of existing values. However the `label_replace` don't activate when there's no label.

```
label_replace(
  sum(http_requests_total{service="$service",handler=~".*"}),
  "handler", "all", "", ".+"
  )
```

-------
Prom 1.8

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
