### ISSUE TITLE
Retention time of 2 hours not working as intended

### ISSUE THREAD

**Issue by twix14** [prometheus/prometheus#9595]
**What did you do?**
Run prometheus server, in k8s, with 2 hours of retention and a block duration of 2h (recommended by Thanos). Thanos is taking care of long term retention, 30 days. 

**What did you expect to see?**
You should only be able to see data until 2 hours ago. 

**What did you see instead? Under which circumstances?**
Data from 5h30 ago was available to query. This will cause Prometheus to consume more resources, for metrics which already have been store by Thanos.

![Screenshot 2021-10-26 at 12 34 08](https://user-images.githubusercontent.com/25937180/138869685-6a96be11-8b08-4009-b4eb-fb89d181f71e.png)

Here you can see two blocks (01FJXX7WWQ3XTYBD91YB0PRYNB and 01FJY43KWNY079Y2F45P2YKTAS) and the current chunks. I expected to see one closed block but not two of them. Logs show that only the oldest block is being deleted every 2 hours.

<img width="589" alt="Screenshot 2021-10-26 at 12 38 42" src="https://user-images.githubusercontent.com/25937180/138870314-4c21d7e4-7040-4fa3-9fe6-c1dcdd9c92fa.png">

Output of meta.json of the oldest block (01FJXX7WWQ3XTYBD91YB0PRYNB):

```
{
	"ulid": "01FJXX7WWQ3XTYBD91YB0PRYNB",
	"minTime": 1635228002003, -> Tuesday, 26 October 2021 06:00:02.003
	"maxTime": 1635235200000,
	"stats": {
		"numSamples": 127266331,
		"numSeries": 271257,
		"numChunks": 1057748
	},
	"compaction": {
		"level": 1,
		"sources": [
			"01FJXX7WWQ3XTYBD91YB0PRYNB"
		]
	},
	"version": 1
}
```

Output of meta.json of the latter block:

```
{
	"ulid": "01FJY43KWNY079Y2F45P2YKTAS",
	"minTime": 1635235200708,
	"maxTime": 1635242400000,
	"stats": {
		"numSamples": 133698907,
		"numSeries": 282855,
		"numChunks": 1112227
	},
	"compaction": {
		"level": 1,
		"sources": [
			"01FJY43KWNY079Y2F45P2YKTAS"
		]
	},
	"version": 1
}
```

**Environment**

* Prometheus version: 2.29.1

* Prometheus configuration file:
```
prometheus
  --config.file=/prometheus/prometheus.yaml
  --storage.tsdb.path=/prometheus
  --storage.tsdb.retention.time=2h
  --web.enable-lifecycle
  --storage.tsdb.no-lockfile
  --web.enable-admin-api
  --web.external-url=http://prometheus.observability.svc.cluster.local:9090
  --web.route-prefix=/
  --log.format=json
  --storage.tsdb.min-block-duration=2h
  --storage.tsdb.max-block-duration=2h
```

* Logs: 
```
{"block":"01FJXFGEC65C7K699DC86GNPMB","caller":"db.go:1289","component":"tsdb","level":"info","msg":"Deleting obsolete block","ts":"2021-10-26T09:00:46.007Z"}
{"caller":"head.go:1018","component":"tsdb","duration":"7.898423844s","level":"info","msg":"Head GC completed","ts":"2021-10-26T09:00:53.906Z"}
{"caller":"checkpoint.go:97","component":"tsdb","from_segment":309,"level":"info","mint":1635235200000,"msg":"Creating checkpoint","to_segment":316,"ts":"2021-10-26T09:00:54.612Z"}
{"caller":"head.go:1184","component":"tsdb","duration":"38.014823837s","first":309,"last":316,"level":"info","msg":"WAL checkpoint complete","ts":"2021-10-26T09:01:32.627Z"}
{"caller":"compact.go:518","component":"tsdb","duration":"45.549377787s","level":"info","maxt":1635242400000,"mint":1635235200708,"msg":"write block","ts":"2021-10-26T11:00:47.618Z","ulid":"01FJY43KWNY079Y2F45P2YKTAS"}
{"block":"01FJXPC5M7TZB2NWYB7A63D12K","caller":"db.go:1289","component":"tsdb","level":"info","msg":"Deleting obsolete block","ts":"2021-10-26T11:00:47.631Z"}
{"caller":"head.go:1018","component":"tsdb","duration":"8.178396694s","level":"info","msg":"Head GC completed","ts":"2021-10-26T11:00:55.809Z"}
{"caller":"checkpoint.go:97","component":"tsdb","from_segment":317,"level":"info","mint":1635242400000,"msg":"Creating checkpoint","to_segment":324,"ts":"2021-10-26T11:00:56.605Z"}
{"caller":"head.go:1184","component":"tsdb","duration":"40.618016938s","first":317,"last":324,"level":"info","msg":"WAL checkpoint complete","ts":"2021-10-26T11:01:37.223Z"}
```

**Comment by codesome** [comment]
`>=`  looks fine. Note that it will will still leave you with of `5h` of data at peak for any retention `<5h`. This is because the retention is calculated w.r.t. the last block, so there will be at least 1 block of 2h plus upto 3h of data in the head block. (Currently with `>` instead of `>=` you will have 2 blocks and 3h of head, hence peack data range being `7h`).

**Comment by twix14** [comment]
@codesome 2h 1 block + 2h of the head block, at most, is what totally makes sense and I'm fine with it. Thanks guys!
