### ISSUE TITLE
Please add the ability to scape remote endpoints without a VPN

### ISSUE THREAD

**Issue by hookenz** [prometheus/prometheus#960]
I'd like to place my prometheus monitoring server in a different physical location to the machines I'm monitoring.

The only way I can see to do this securely is with a VPN.  Are there any alternatives like a proxy with a http auth or similar?

**Comment by beorn7** [comment]
This is pretty much one of our non-goals, which we plan to document more clearly, see https://github.com/prometheus/docs/issues/149 .

Short answer: You need to set up some way independent from Prometheus to allow the scrapes. There are just too many possible setups to support this within Prometheus.

Sorry for that...

**Comment by juliusv** [comment]
@hookenz While we won't be adding a proxy itself, what might be helpful in this scenario are existing support for basic auth (http://prometheus.io/docs/operating/configuration/#scrape-configurations-scrape_config), pending support for proxy support for scrapes (https://github.com/prometheus/prometheus/pull/943), or pending support for bearer tokens (https://github.com/prometheus/prometheus/pull/921).
