### ISSUE TITLE
Remote Write: non-recoverable errors influence desired shards

### ISSUE THREAD

**Issue by rfratto** [prometheus/prometheus#9604]
https://github.com/prometheus/prometheus/blob/f29caccc42557f6a8ec30ea9b3c8c089391bd5df/storage/remote/queue_manager.go#L819

The number of desired shards accounts for how much read WAL data is still attempting to be delivered. This is done by looking at the difference from the newest timestamp sent to remote_write (`prometheus_remote_storage_queue_highest_sent_timestamp_seconds`) and the newest timestamp read from the WAL. 

`prometheus_remote_storage_queue_highest_sent_timestamp_seconds` is not updated when a batch is dropped from a non-recoverable error. This makes sense, and is useful for tracking the delay of data appearing into remote_write. However, it does not make sense for use in the desired shards caclulation. If a client is _only_ receiving 400s, the metric will never increase, and will cause the desired shards to unnecessarily balloon up. 

Instead of `prometheus_remote_storage_queue_highest_sent_timestamp_seconds`, the desired shards calculation should use the highest timestamp of a sample that left the queue, either from a successful delivery or a non-recoverable error.

**Comment by bboreham** [comment]
Reviewed at the bug-scrub: believed to be fixed by #10102.
