### ISSUE TITLE
Improve Prometheus's internal metrics

### ISSUE THREAD

**Issue by fabxc** [prometheus/prometheus#961]
Many parts of Prometheus itself are not instrumented as well they should be.

**Comment by brian-brazil** [comment]
I maintain that the correct way to measure memory usage is in terms of how much of it you can read in a second!

**Comment by juliusv** [comment]
@brian-brazil Haha, :+1: :100: Let's make it so!

**Comment by brian-brazil** [comment]
On a more serious note, I'll be doing up consoles templates for prometheus itself in the next few days so I should have some concrete suggestions from that.

**Comment by fabxc** [comment]
There are also parts which are not instrumented at all – namely the
different SD mechanisms and the query engine.
The more generic the SD instrumentation the better. But there may be some
reasonable specific metrics.

**Comment by mwitkow-io** [comment]
Can I drop a feature request here?

 - number of targets per `job`
 - number of metrics collected and retained last scrape  per `job`

:)

**Comment by brian-brazil** [comment]
Per-instance/job metrics are something that should come from the scrape, and don't belong on the /metrics for prometheus as they're not about prometheus at a systems level.

> number of targets per job

`count by(job)(up{job="job"}`

> number of metrics collected and retained last scrape per job

`count by (job)({job="job"})`

Be careful with that one, it's going to be slow.

**Comment by mwitkow-io** [comment]
Yea, the last one is precisely the reason why we'd like a counter :)

**Comment by brian-brazil** [comment]
The way to do that would be as `scrape_samples_collected` similar to `scrape_duration_seconds`.

**Comment by brian-brazil** [comment]
scrape_samples_scraped has been added. The rest of this ticket is rather generic, so if there's specific metrics you're looking for please open issues for then.

**Comment by beorn7** [comment]
I guess @fabxc original intention was to keep this as a reminder to eventually rewrite the instrumentation from scratch. I don't know if anybody ever will have the time and nerves to do so. We could just keep improving instrumentation iteratively as we see fit.
