### ISSUE TITLE
Agent: Add validation that fails agent if no remote write is configured.

### ISSUE THREAD

**Issue by bwplotka** [prometheus/prometheus#9611]
cc @rfratto

**Comment by roidelapluie** [comment]
That's interesting. Should we error or should we warn? What should we do if remote write is removed while the agent is running?

**Comment by rfratto** [comment]
> That's interesting. Should we error or should we warn? What should we do if remote write is removed while the agent is running?

It should probably fail validation and not make any runtime changes to remote_write unless there's at least one in the file.

I can see it being a warning too, though: in the worst case you have a WAL that keeps stale series in it up to the max WAL time before new GCs will clean them up.

**Comment by ArthurSens** [comment]
Is there any use-case for an agent without a remote-write?

If there isn't then I think the most reasonable approach would be a hard-fail for the agent 🤔

Letting it run may misguide users that everything is working as expected

**Comment by rfratto** [comment]
The only use case I've really been able to identify is doing cardinality analysis on the WAL without having to persist metrics. But there's still reasonable workarounds to give you similar things: temporary Prometheus server that you spin down later, or a fake remote_write endpoint, etc. 

Bringing up the lack of a use case is a really good point, and I'm on the side of having the validation hard-reject configs without any remote_writes. That restriction can always be lifted if a nice use case shows up.
