### ISSUE TITLE
Agent is not behind a feature flag

### ISSUE THREAD

**Issue by roidelapluie** [prometheus/prometheus#9617]
The Prometheus agent is certainly a feature that might change in the future, including its flags, and behavior.

I think we should gate it behind an experimental feature flag.

**Comment by rfratto** [comment]
Just to make sure I understand, that means we'd need to pass two flags to active it, right?

```
--enable-feature=agent --agent
```

**Comment by roidelapluie** [comment]
According to the last dev summit, I think we should only have `--enable-feature=agent` and then "graduate" it to a real flag.
