### ISSUE TITLE
Rules API: support label-based matcher. [Feature Request]

### ISSUE THREAD

**Issue by hanjm** [prometheus/prometheus#9627]
## Proposal
**Use case. Why is this important?**
In thanos-sidecar mode, fanout prometheus rules api may response lots of rules. Could we support label based matcher in prometheus rules api, like series api `match[]` parameters . https://github.com/prometheus/prometheus/blob/main/docs/querying/api.md#finding-series-by-label-matchers . 😃 
relevant issue in thanos https://github.com/thanos-io/thanos/issues/4812

**Comment by roidelapluie** [comment]
I think we could get the group name and the file as parameters. It is very difficult to gave the match[] because the labels in the rules are templates and not values.

**Comment by hanjm** [comment]
> I think we could get the group name and the file as parameters. It is very difficult to have the match[] because the labels in the rules are templates and not values.

Templates will rendered on active alert,  so what about match rules on origin label and match active alert on rendered label?

**Comment by hanjm** [comment]
Hi, If this proposal reasonabl, I could start implement it (:

**Comment by saswatamcode** [comment]
Hello 👋, I wanted to move forward with this issue, regarding matcher support in Prometheus Rules API. A major use case for this is multi-tenant setups, where the only way to achieve tenancy seems to be modifying the API response, which is what [prom-label-proxy does](https://github.com/prometheus-community/prom-label-proxy/blob/1eac0933d51263ca7856fb8e4528f03039afa44f/injectproxy/rules.go#L166). Maybe I can raise a PR and get some feedback on the approach and implementation details? 🙂

**Comment by roidelapluie** [comment]
it is fine to filter on active alerts, but filtering on definitions would require an alternative approach (filter by name, group ...)

**Comment by bwplotka** [comment]
Why not a simple approach for Rules API to filter on non rendered labels? (Let's keep the Alerts API from the discussion for now).

Commented on the [PR](https://github.com/prometheus/prometheus/pull/10194#pullrequestreview-863455107)
