### ISSUE TITLE
Keywords should be valid metric names

### ISSUE THREAD

**Issue by brian-brazil** [prometheus/prometheus#963]
Currently an expression such as `if` is invalid due to it being a keyword. As we won't limit metric not to clash with keywords, we should allow any valid metric name to be used in promql.

**Comment by fabxc** [comment]
I don't see the practical necessity of this considering the implementation complexity it ships with. This will be absolutely nasty to parse for alerting rules.

**Comment by fabxc** [comment]
I don't think this will ever happen and nor do I consider it necessary.
I would like to close issues that are not going to be tackled. Our keywords are mostly single-worded while metrics are generally multi-worded, so the conflict-potential is minimal. There is always the workaround through `__name__` should there actually ever be a conflict.

Thoughts?

**Comment by juliusv** [comment]
:+1: for closing for now and potentially reopening in the distant future if the need really ever becomes apparent.
