### ISSUE TITLE
Proposal: machine-level target filtering

### ISSUE THREAD

**Issue by rfratto** [prometheus/prometheus#9637]
## Proposal
Grafana Agent allows users to easily run one agent per machine, all configured with the same set of scrape jobs. The list of targets actively scraped from is filtered down to the set of targets that are colocated on the same node as the agent. 

This was initially implemented via a feature called [host filtering](https://grafana.com/docs/agent/latest/operation-guide/#host-filtering), where Grafana Agent tries to detect if a target is running on the same machine, and filters it out if it isn't. I've not been very happy with this implementation, and I think upstreaming the use case (but not the implementation), is the perfect time to work out the issues with it. 

This is what host filtering does:

* If the target address is localhost/127.0.0.1, always scrape. 
* Otherwise, only scrape targets if the target has a hostname label that matches the hostname of the machine the agent is running on (i.e., check for `__meta_kubernetes_node_name`.)

I think relabel rules would be the best place to move this logic. I propose that Prometheus automatically inject a machine-level `__prometheus_agent_hostname` label based on the result of `os.Hostname()`. While this would allow for writing relabel rules that make use of Prometheus' hostname, I can't currently identify a minimal set of new/existing rules that would provide equivalent functionality to what Grafana Agent's host filtering does. You would need (at least) some new way of keeping/dropping targets based on if a set of labels match, but I can't think of a way to encode the localhost bypass at all.

**Comment by rfratto** [comment]
> You would need at least some new way of keeping/dropping targets based on if a set of labels match,

Something like:

```yaml
- source_labels: [__meta_kubernetes_node_name, __prometheus_agent_hostname]
  action: match # or match_ne for the inverse, or something similarly named 
```

**Comment by rfratto** [comment]
> If the target address is localhost/127.0.0.1, always scrape

Maybe this is an edge case we could initially ignore anyway? I don't think you'd use the host name filtering inside of an SD that might produce localhost targets.

**Comment by roidelapluie** [comment]
How would you know your own "node" hostname?

**Comment by rfratto** [comment]
Ah, sorry, during a rewrite I missed the primary part of the proposal. I think that a `__prometheus_agent_hostname` label should be injected by Prometheus, set to the result of `os.Hostname()`, that can be used during relabeling. I'll edit the issue description to add this.

**Comment by roidelapluie** [comment]
When does os.Hostname match the actual hostname? not in kubernetes AFAIK.

**Comment by rfratto** [comment]
Not by default, no. It's been common for this snippet to be added to Promtail for similar Kubernetes host filtering and Grafana Agent when host filtering is used: 

```yaml
        env:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
```

**Comment by roidelapluie** [comment]
This is a quite involved trick indeed. I am wondering if it is possible to do this on all the platforms (e.g. nomad) or if we should explicitly allow for `--node.name` CLI argument to be more generic. Then you can use --node.name=$HOSTNAME in your k8s yaml.

**Comment by rfratto** [comment]
Putting it as a flag name makes sense. I'm still thinking of simpler ways to pull off machine-level filtering, since I agree that there'd be a lot that would need to happen to make this a possibility in relabel rules. 

I'm starting to rethink if the host filtering code in grafana/agent isn't all that bad after all, but I still think it's worthwhile exploring what alternatives could look like.

**Comment by gintrator** [comment]
This is possible with existing relabelling functionality, with the caveat that you must run a config-generation step before Prometheus starts. We happen to use ERB to do this, but any templating language would do. Something along these lines...

```
...
relabel_configs:
  - action: keep
    source_labels: [__meta_kubernetes_pod_node_name]
    regex: (<%=Regexp.escape(ENV["NODE_NAME"])%>)
...
```
... where `NODE_NAME` is set using the k8s downward API as posted above.

**Comment by roidelapluie** [comment]
```
relabel_configs:
  - action: keep
    source_labels: [__meta_kubernetes_pod_node_name]
    regex_env: $NODE_NAME
```

We could introduce a new field in the relabeling: regex_env that would substitute regexes.

**Comment by gintrator** [comment]
Note that there is a difference between `regex: (<%=Regexp.escape(ENV["NODE_NAME"])%>)` and `regex_env: $NODE_NAME`, if `$NODE_NAME` is interpreted directly.

As an example, if `$NODE_NAME` is `host.internal`, The 1st evaluates to `regex: (host\.internal)`, which is a group matching the string `host.internal` exactly, but the 2nd evaluates to `regex: host.internal`. In this case, it'll probably have the intended effect, since the regex `.` does match the character `.` (since regex `.` matches anything), but it's not actually doing an exact string match, it also matches `host-internal`, `hostXinternal`, etc..

I suppose this depends on the semantics of `regex_env`. Does it treat the var as a regex expression or as an exact string match that it should escape?

**Comment by roidelapluie** [comment]
This is interesting. Making it templatable is an option, with a regex_escape and an env() function.

Instead of regex_env, we could have a `value` field that would need to exactly match.

**Comment by roidelapluie** [comment]
So.

What about we introduce an extra flag:

--enable-feature=template-regex [enabled by default with the agent mode], in which regex becomes a templated field that can use templates. We add 2 functions:

regexp_quotemeta which calls regexp.QuoteMeta
and getenv which calls os.getenv.

Then it becomes:

```
relabel_configs:
  - action: keep
    source_labels: [__meta_kubernetes_pod_node_name]
    regex: '{{regexp_quotemeta(getenv("NODE_NAME"))}}'
```

**Comment by rfratto** [comment]
The idea of using text/template is really interesting here, and I think it's possible to take it further to cover both behaviors of host filtering: 

> This is what host filtering does:
>
> * If the target address is localhost/127.0.0.1, always scrape.
> * Otherwise, only scrape targets if the target has a hostname label that matches the hostname of the machine the agent is running on (i.e., check for __meta_kubernetes_node_name.)

What if there support for `action: template`, where the `replacement` field would be treated as a text/template? Alongside functions like GetEnv, you could have the current context be set to the active metric/target being relabeled. Here's an example spread across multiple lines to give an idea of what you might be able to do:

```yaml
relabel_configs:
- action: template 
  target_label: _keep 
  target_label: |
   {{ $nodeName := GetEnv "NODE_NAME" }}
   {{ if .Labels.__meta_kubernetes_pod_node_name == $nodeName }}
   true 
   {{ else if or (.Labels.__address__ == "localhost") (.Labels.__address__ == "127.0.0.1") }}
   true 
   {{ else }}
   false  
   {{ end }}
- action: keep 
  source_labels: _keep 
  regex: true
```
  
While I don't think everyone would take advantage of specific snippet, I think the idea of using templates for relabeling could open the door to some interesting capabilities that you can't express otherwise.  

For example, in the past I've wished I could express a rule that checked if label A was equal to label B, but Go's regex doesn't allow those kinds of checks. That kind of check would be arbitrary with templates.

**Comment by rfratto** [comment]
The minimal example of a template action, ignoring all the extra logic, would be: 

```yaml
relabel_configs:
- action: template 
  target_label: _keep 
  target_label: {{ eq .Labels.__meta_kubernetes_pod_node_name (GetEnv "NODE_NAME") }}
- action: keep 
  source_labels: _keep 
  regex: true
```

**Comment by rfratto** [comment]
> the `replacement` field would be treated as a text/template

This is a bit in the weeds, but hypothetically in this case you'd probably want a separate `template:` field so you could compile the template once and cache the result.

**Comment by roidelapluie** [comment]
> > the `replacement` field would be treated as a text/template
> 
> This is a bit in the weeds, but hypothetically in this case you'd probably want a separate `template:` field so you could compile the template once and cache the result.

mmh? I'd expect that we compile the regex once, don't we?

**Comment by rfratto** [comment]
> mmh? I'd expect that we compile the regex once, don't we?

We do, but I don't think you could do that for a text/template if it was a part of the `replacement` field.

**Comment by roidelapluie** [comment]
> > mmh? I'd expect that we compile the regex once, don't we?
> 
> We do, but I don't think you could do that for a text/template if it was a part of the `replacement` field.

If you give it access to the labels, yes. otherwise no. I think the `action: template` with access to labels can be a good idea. I'll poke around.

**Comment by juliusv** [comment]
So far, I like the idea of introducing an `action: template` best. Although it could have performance impacts when also allowed outside of target relabeling, I think we shouldn't forbid it in the other relabeling places (metrics, alerts, remote write) if someone really wants to use it. I expect it to be such a niche use case anyway that not many users should run into issues with it.

**Comment by rfratto** [comment]
> If you give it access to the labels, yes. otherwise no. I think the action: template with access to labels can be a good idea. I'll poke around.

Did you have time to poke around yet? If not, do you mind if I take a crack at an `action: template` PR? It looks like I might have some free time tomorrow to put an initial PR together.

**Comment by rfratto** [comment]
> If you give it access to the labels, yes. otherwise no. I think the action: template with access to labels can be a good idea. I'll poke around.

@roidelapluie Did you have time to poke around yet? If not, do you mind if I take a crack at an `action: template` PR? It looks like I might have some free time tomorrow to put an initial PR together.

**Comment by bboreham** [comment]
This proposal relates to filtering targets after they have been received from the Kubernetes API-server.
I think it would be even better if we filtered the 'watch' call into the API-server so it would restrict the pods it tells us about.

**Comment by rfratto** [comment]
> This proposal relates to filtering targets after they have been received from the Kubernetes API-server.
> I think it would be even better if we filtered the 'watch' call into the API-server so it would restrict the pods it tells us about.

I used Kubernetes as an example, but people have used Grafana Agent's host filtering for SD's beyond Kubernetes (i.e., Consul). A generic way to filter targets based on environment would still be useful IMO.

**Comment by chenjpu** [comment]
```
logs:loki
sd:consul

consulagent_sd_configs
```
This way can directly discover local services

**Comment by rfratto** [comment]
I no longer have a need for this, so I'm going to close.
