### ISSUE TITLE
Move to opentelemetry tracing

### ISSUE THREAD

**Issue by roidelapluie** [prometheus/prometheus#9644]
Jaeger clients are sunsetting. we should move out tracing implementation to opentelemetry.

- https://github.com/jaegertracing/jaeger/issues/3362

**Comment by roidelapluie** [comment]
https://github.com/jaegertracing/jaeger/issues/3362

**Comment by roidelapluie** [comment]
Note to implementers: we do not have to offer any backwards compatibility. Jaeger was never documented and since the beginning was meant to be replaced by opentelemetry.

**Comment by matej-g** [comment]
Hey @roidelapluie I'm currently in process of doing the same for Thanos, happy to contribute here as well!

**Comment by roidelapluie** [comment]
Thanks, I have assigned the issue to you. Ping us back if you need help: https://prometheus.io/community
