### ISSUE TITLE
Implement alert silence link on the rules status page

### ISSUE THREAD

**Issue by pdf** [prometheus/prometheus#966]
Judging by the placeholder links, I'm going to assume that the plan is to move silencing into prometheus-proper at some point (as opposed to alertmanager, for example).  This would indeed be beneficial, because then the silenced state could appear in the time-series data, and be used for reporting (eg - I don't want my wall-board to light up if an alert has been silenced).

This issue is just to track implementation so that we can have a notification when the feature is committed.

**Comment by brian-brazil** [comment]
Silences are already implemented in the alertmanager, and there's no plans to move them to prometheus as multiple prometheus servers (some of which may be identical) talk to an alertmanager and you don't want to have to create silences multiple times.

The silence link is meant to be a link to the alertmanager to save you a little bit of time. As-is we should either remove it due to the confusion it causes, or make it actually work.

**Comment by matthiasr** [comment]
I just spoke with @fabxc about these links yesterday; I would expect them to take me to Alertmanager.

Having the silences live in Prometheus would make it impossible to silence across multiple Prometheus or interact with all of them. It would also be a problem with Prometheus' high availability model (have two). Alertmanager doesn't have one yet, but in general I expect syncing alert state to have very different expectations from the time series pieces, and be better contained in AM.

As for metrics showing the alert state, AM could just expose these (maybe it already does?) and if you want them in Prometheus just scrape it.

**Comment by fabxc** [comment]
We plan to make the redirection to alertmanager work. It just came up
yesterday with @matthiasr.

We certainly don't want to have two places to do silencing. Aside from
implementation, this would be a major source of confusion and errors during
operation.

**Comment by pdf** [comment]
Indeed I hadn't considered the scaling issue.

So, with alertmanager remaining the authoritative source for silences I guess we need alertmanager to re-export received alerts, after appending the silenced state as a new label, so prometheus can scrape them back into a new series.  I'll open an issue over there, though I know it's due for a rewrite.

**Comment by brian-brazil** [comment]
This may be a bit complicated due to us now supporting multiple alertmanagers.

**Comment by roidelapluie** [comment]
> This may be a bit complicated due to us now supporting multiple alertmanagers.

There is more into that:

- We would need to know to which AM the alert has been sent; alerts relabeling must be taken into consideration (including alerts dropped directly in prometheus)
- Alertmanagers can have external URL's, we should use those (how?)
- The fact that alertmanager are dynamically configurable makes it even more complex. Alertmanagers can come and go.

**Comment by matthiasr** [comment]
I would lean on the exteranal-URL / clustering as the semantics for this: Generate silence links using the external URL, and rely on Alertmanager itself to handle propagation of silences.

**Comment by renzsickle** [comment]
Is there still interest in this?

We'd like to use the Alert Manager for centralised alert configuration and dissemination, but we'd also like to create an "alerts" dashboard in Grafana. Adding "silenced" information to the ALERTS timeseries would seem to enable this (unless there's a better way?).

**Comment by Henac** [comment]
I am also interested @renzsickle, I am after the same functionality as you. The AlertManager Grafana data source has essentially been abandoned, so being able to access this information from Prometheus seems like the best way forward. 
I would be interested in thoughts from main Prometheus contributors...

**Comment by brian-brazil** [comment]
Prometheus itslef doesn't know about or work with about silences, as that's the Alertmanager's concern and also silences are not time series. The most it might do (and this is what this issue is about) is providing a URL that'd allow you to create a silence in the browser.

**Comment by roidelapluie** [comment]
> Prometheus itslef doesn't know about or work with about silences, as that's the Alertmanager's concern and also silences are not time series. The most it might do (and this is what this issue is about) is providing a URL that you could click which would take you to the Alertmanager and allow you to create a silence in the browser.

Even that seems problematic as alert managers use service discovery, come and go, and Prometheus would need to know the public address of the alertmanagers.

**Comment by brian-brazil** [comment]
We already know a public address of the alertmanagers, as that's what we're sending alerts to.

**Comment by matthiasr** [comment]
That's usually not the same address as where humans can reach it:
Prometheus uses service discovery; browsers typically don't.

**Comment by roidelapluie** [comment]
Yes, we would usually send the alerts to pods IP, not to alertmanager's `--web.external-url=`

**Comment by brian-brazil** [comment]
We do have a working IP and any prefix needed on the HTTP path. That should be sufficient in any standard routable network setup - and we can't do much about unroutable setups.

**Comment by matthiasr** [comment]
And yet, they are the norm, and an assumption of our security model.

I don't know if AM does already off the top of my head, but a component
knowing its own external URL and prefix is already a common pattern. What
prevents Alertmanager from generating the silence URL as part of the
templating?

**Comment by brian-brazil** [comment]
> What prevents Alertmanager from generating the silence URL as part of the templating?

Nothing - that's possible and done today by at least some users. However that's not what this issue is about, this issue is about having a silence link on the rule status page of Prometheus.

**Comment by xkilian** [comment]
Having a silence link on the Prometheus page is nice to have and makes it easier to silence new rules that are being tested. But this is by no means the actual answer to the business need to put devices in various "states" and be able to reflect them n dashboard, not just in AlertManager/Karma and notifications.

Alerts need to take into account this state, same as dashboards and finally alertManager/Karma manages the silence/acknowledgement portion of the alerts.

We have resorted to implementating an administrative state metric for each physical device so that it can be reflected in dashboards and flowcharts. 

> admin_state{host="blah", state="active"} 0
> admin_state{host="bleh", state="maintenance"} 1
> admin_state{host="bleh", state="planned"} 1
etc.

As noted in the thread, silences live in the alertmanager and their state is independant from Prometheus alerts and displays. Hence the need to have an actual metric that represents the state of a device. (active, planned, maintenance, longterm maintenance, out-of-service-to-be-removed).
The state is managed through an API driven web frontend and a custom grafana control that talks to the API.
Just my two cents.

**Comment by bboreham** [comment]
Discussed at bug-scrub.  Closing as probably never going to be implemented; see discussion above for why it's not as easy as it might seem. Still open to PRs if you can solve it.
