### ISSUE TITLE
High Availability Support 

### ISSUE THREAD

**Issue by zqwlai** [prometheus/prometheus#9670]
@LeviHarrison hi, i submitted a pr about  [high availability](https://github.com/prometheus/prometheus/pull/9658) .

The common practice of high availability is to deploy two nodes and monitor one exporter at the same time. In this way, there will be the problem of repeated collection. Therefore, I think how to ensure that only one node works at the same time is a point that can be optimized.

My idea is to use the gossip protocol to implement this mechanism, just like the implementation method in alertmanger. The specific method is to set the name of the gossip protocol of the local node as the local timestamp when each peer node is started. The node compares its own name and obtains the name list of all members. If its own name is the smallest, then it starts to work.

This method needs to ensure that the system clock of each peer is consistent.

**Comment by roidelapluie** [comment]
I personally consider high availability like described in your proposal out of scope for Prometheus. You are proposing an Active/Passive model. It can be implemented out of the project itself by using kubernetes, nomad, or Linux-HA (pacemaker/corosync). Pretty much all the environments already have solved this problem for a long time.

The current recommended model for HA in Prometheus is to have an Active Active model, where the instances work all the time. In this model, clustering happens at Alertmanager level, as every Prometheus server sends alerts to every Alertmanager.

Active / passive model has a number of issues in Prometheus: time series could jump for one host to the other, making querying difficult ( the PromQL query engine is not designed for it). It is not easy to know if the passive node has the ability to scrape nodes (firewall?) until it becomes active. The FOR duration and status of nodes should be shared between nodes.
