### ISSUE TITLE
make assets failure on v2.31.1 tag (and master)

### ISSUE THREAD

**Issue by mikhailkoliada** [prometheus/prometheus#9685]
As per title, the logs are:

cd web/ui && npm install
up to date in 0.651s
found 0 vulnerabilities

cd web/ui && npm run build

> prometheus@ build /tmp/prometheus/web/ui
> bash build_ui.sh --all

build module/codemirror-promql

> codemirror-promql@0.18.0 build /tmp/prometheus/web/ui/module/codemirror-promql
> npm run build:grammar && npm run build:lib

> codemirror-promql@0.18.0 build:grammar /tmp/prometheus/web/ui/module/codemirror-promql
> lezer-generator src/grammar/promql.grammar -o src/grammar/parser

sh: line 1: lezer-generator: command not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! codemirror-promql@0.18.0 build:grammar: `lezer-generator src/grammar/promql.grammar -o src/grammar/parser`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the codemirror-promql@0.18.0 build:grammar script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/zlogene/.npm/_logs/2021-11-07T11_50_39_949Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! codemirror-promql@0.18.0 build: `npm run build:grammar && npm run build:lib`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the codemirror-promql@0.18.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/zlogene/.npm/_logs/2021-11-07T11_50_39_964Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! prometheus@ build: `bash build_ui.sh --all`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the prometheus@ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/zlogene/.npm/_logs/2021-11-07T11_50_39_993Z-debug.log
make: *** [Makefile:38: ui-build] Error 1

**Comment by roidelapluie** [comment]
What is your version of node and mom? We require pretty recent versions

**Comment by mikhailkoliada** [comment]
ugh, I have updated nodejs to the latest 16.x and it went fine! Thanks for the hint.
