### ISSUE TITLE
should consider weather the len(el.Points) is 0

### ISSUE THREAD

**Issue by RayYe586** [prometheus/prometheus#9692]
https://github.com/prometheus/prometheus/blob/c28b9a05741d499fcbcca56165d96fd2d39a8f0e/promql/functions.go#L413

**Comment by codesome** [comment]
Those validations would be already done before reaching this point. Have you found any way to make this line fail?

**Comment by RayYe586** [comment]
Yes,i have found the code,thanks

**Comment by codesome** [comment]
Closing this issue since the check is not required - should be validated already before reaching this line.
