### ISSUE TITLE
Proposal: ability for importers to scrape targets without network

### ISSUE THREAD

**Issue by rfratto** [prometheus/prometheus#9706]
## Proposal
Grafana Agent embeds common Prometheus exporters as "integrations." These integrations work by exposing a unique metrics endpoint per integration and automatically configuring scrape managers to collect metrics from these endpoints. This requires Grafana Agent to have an HTTP server for integrations to work. We would like the ability to disable the HTTP server without breaking the ability to use integrations. If the Grafana Agent could scrape targets without using the network, the capability to use integrations without an HTTP server would be retained. 

I propose a way to inject a custom target scrapers into the scrape manager:

1. Make the [`scrape.scraper`](https://github.com/prometheus/prometheus/blob/f4650c27e7b3cfe55b9fd22aa7410a499f46ba6f/scrape/scrape.go#L728-L733) interface and its methods public.
2. Pass a function scrape manager that specifies how to create a scraper: `func(target *scrape.Target, client *http.Client, timeout time.Duration, bodySizeLimit int64) scraper`
3. Loosen the [restriction on targets](https://github.com/prometheus/prometheus/blob/f4650c27e7b3cfe55b9fd22aa7410a499f46ba6f/scrape/target.go#L406-L413) to use a http/https scheme so custom scrapers can use the protocol scheme for hooking in custom logic. 

This proposal isn't as clean as it could be: the implementation of the scraper that the Grafana Agent would use would ignore the http client for integrations. I'm not sure it's worthwhile to create a more minimal design, and the proposal above seems to be the way to add this functionality into Grafana Agent with minimally disruptive changes to Prometheus.

**Comment by roidelapluie** [comment]
I do not think we should allow this, as there is a lot of logic in scraping that is outside of HTTP. I kinda would like the users of scrape manager to use all of the code rather than copy/pasting it.

Instead, I think you could use dedicated DialContext to make HTTP requests without going to the network.

**Comment by roidelapluie** [comment]
If my idea does not work, we should still scrape using HTTP (maybe allow unix socket on linux) because changing this would change a lot of the semantics around scraping.

**Comment by rfratto** [comment]
> I do not think we should allow this, as there is a lot of logic in scraping that is outside of HTTP. I kinda would like the users of scrape manager to use all of the code rather than copy/pasting it.

I'm not sure I'm understanding what the concern is yet. My proposal is to allow callers to override this block of logic, leaving everything else the same: https://github.com/prometheus/prometheus/blob/9fae120f2a6daa420530e44559c67ce27cb6e7eb/scrape/scrape.go#L755-L820

> Instead, I think you could use dedicated DialContext to make HTTP requests without going to the network.

I'd be happy with this workaround; we should be able to get it work for us. Unix sockets would be less desirable since we want this functionality to be also available for Windows users who are using Grafana Agent for its embedded windows_exporter.

**Comment by rfratto** [comment]
> 3. Loosen the restriction on targets to use a http/https scheme so custom scrapers can use the protocol scheme for hooking in custom logic.

Are you ok with this part of the suggestion? I think even with having DialContext we'd still want to be able to use something like `integration://` to be able to use an in-memory net.Conn instead of a "real" net.Conn.

**Comment by roidelapluie** [comment]
If it's in memory, it should not be an issue to keep http. It remains http queries, with http headers, etc.

This code block you highlight contains useful things: e.g. the Blackbox exporter uses the scrape timeout to determine its own timeouts. I don't really want to have an abstraction layer in every exporter.

**Comment by rfratto** [comment]
> If it's in memory, it should not be an issue to keep http. It remains http queries, with http headers, etc.

Sure, but it wouldn't be clear to our dialer when the caller wants to use the network vs an in-memory connection, since the scrape manager would still be handling both kinds of targets.

**Comment by roidelapluie** [comment]
> > If it's in memory, it should not be an issue to keep http. It remains http queries, with http headers, etc.
> 
> Sure, but it wouldn't be clear to our dialer when the caller wants to use the network vs an in-memory connection, since the scrape manager would still be handling both kinds of targets.

it's probably better to use a custom hostname like agent.internal.

**Comment by rfratto** [comment]
> it's probably better to use a custom hostname like agent.internal.

👍 My immediate concern is colliding with something on a corporate DNS, but we can make this configurable and come back to propose an alternative if it's a problem for us. Thanks!

**Comment by bwplotka** [comment]
Thanks Robert, let's to find some solution that satisfies all. Can you elaborate more on feature you are missing in Prometheus that you want are working on? Is it some form of target assignment based on Cortex sharding or something? 🤔 

I wonder if this should be a different scrape manager then and we should name our scrapeManager a `httpScrapeManager`? (:

**Comment by rfratto** [comment]
> Can you elaborate more on feature you are missing in Prometheus that you want are working on?

It’s pretty much exactly like I said in the description: some of our users have security constraints where the Agent can’t be listening for HTTP traffic at all, but we’re currently unable to disable its HTTP server because integrations require it. 

If a user starts the Grafana Agent with this configuration: 

```yaml
server:
  http_listen_port: 8080 

integrations: 
  node_exporter: 
    enabled: true
```

It internally translates into (essentially) this: 

```yaml 
scrape_configs: 
- job_name: integrations/node_exporter 
  metrics_path: /integrations/node_exporter/metrics 
  static_configs: 
  - targets: [localhost]
```

We’ve also had to do some pretty gross hacks to work around a user having an HTTPS server defined, so being able to make an in-memory connection for scraping integrations would make a fair amount of our code a lot cleaner.

**Comment by roidelapluie** [comment]
Feel free to come back to us if the proposed solution does not work for you. Thanks!

**Comment by rfratto** [comment]
I won't start working on this for a few weeks, but I'm pretty confident what you proposed would be fine. I'll let y'all know if for some reason it has problems though. Thanks for the help!
