### ISSUE TITLE
Make the size of all the `len` field in block's index 8 bytes

### ISSUE THREAD

**Issue by codesome** [prometheus/prometheus#9709]
Persistent block's [index has multiple sections](https://github.com/prometheus/prometheus/blob/main/tsdb/docs/format/index.md) (symbol table, labels offsets, label offset table, postings lists, postings offset table). All of these sections have first 4 bytes describing the size (the `len`) of the section, which limits the size of the section to 4GiB.

We have already seen issues being reported where users hit the symbol table size limit. Similarly we have seen postings offset table hitting the 4GiB limit silently without error during compaction while giving error when reading the block.

I propose we make the length field 8 bytes. This will require index version bump.

@Harkishen-Singh has shown interest to work on making postings 64 bits, which will also require index version bump. So I plan to club this with that to result in a single version bump (but if required, 2 version bumps, if the 64 bit postings work is going to take some time).

**Comment by bboreham** [comment]
Reviewed at the bug-scrub meeting.

A lot of discussion in other issues leads to the conclusion that we will not make Prometheus blocks 64-bit, and so we do not need the change proposed here. 
* https://github.com/prometheus/prometheus/issues/9078#issuecomment-1572752630
* #5868
* #9078

Open to discussing further if you would like.
