### ISSUE TITLE
allow regex matcher on label names

### ISSUE THREAD

**Issue by darshanime** [prometheus/prometheus#9727]
## Proposal
Currently, we allow regex selectors (equal, not equal) on label values. How about allowing them on label names too?

We already have the `labelName -> <some postings>` in memory, we can implemement the label name regex efficiently without having to touch the disk

https://github.com/prometheus/prometheus/blob/422e7839d4e0524fe78f7e12a6d9adba2bc73639/tsdb/index/index.go#L1068-L1070

**Comment by roidelapluie** [comment]
What would be the usecase?

At first glance I'd say that label names should be known in advance in the prometheus model, and this is simply not needed and not practical.

We already have cardinality explosions with label values, let's avoid that by encouraging the same pattern with the label names.

**Comment by darshanime** [comment]
makes sense, agree.

> What would be the usecase?

I had no usecase, just thought it might be interesting!

closing...
