### ISSUE TITLE
Support for exemplar of other types of metrics, not just those containing the "_total"  or "_bucket" suffixes

### ISSUE THREAD

**Issue by zmapleshine** [prometheus/prometheus#9738]
https://github.com/prometheus/prometheus/blob/411021ada9ab41095923b8d2df9365b632fd40c3/pkg/textparse/openmetricsparse.go#L365

I am using other sdk (opentelemetry-sdk-metrics) based on Prometheus SDK, and the type of Gauge metrics also has exemplars data, but Prometheus does not support such data collection. 
The data looks like:

```shell
gateway_active_requests{endpoint="[GET]/api/v1/test",flow_type="",http_method="GET",route_uri="lb://apm-test-service"} 803.0 # {span_id="ae9ed7bb0d532e5f",trace_id="b4a5ffd744ff22c9d01439b0a1cb3203"} -1.0 1636979238.664
```

**Comment by brian-brazil** [comment]
They are not, as there's no events associated with a gauge given they're snapshots of state.

**Comment by zmapleshine** [comment]
Thanks ,I think I should give this information back to the SDK provider.I'll reopen the issue if something new happens.
