### ISSUE TITLE
Targets UI page fails to render IPv6 link-local addresses with a Zone ID specified

### ISSUE THREAD

**Issue by ben-wallis** [prometheus/prometheus#9760]
**What did you do?**
Specified a target via file_sd with address `[fe80::f1ee:adeb:371d:983%eth1]:9100`

**What did you expect to see?**

The target listed correctly on the `/targets` status page

**What did you see instead? Under which circumstances?**

The target was scraped correctly and data is available but the target page shows `Error: Failed to construct 'URL': Invalid URL`

![image](https://user-images.githubusercontent.com/11904214/141996715-a9ddb0ea-2cd9-4b06-9f3f-40488342716b.png)

**Environment**

* System information:

Linux 4.19.0-17-amd64 x86_64

* Prometheus version:

```
prometheus, version 2.30.3 (branch: HEAD, revision: f29caccc42557f6a8ec30ea9b3c8c089391bd5df)                                                                  │# HELP promhttp_metric_handler_errors_total Total number of internal errors encountered by the promhttp metric handler.
  build user:       root@5cff4265f0e3                                                                                                                          │# TYPE promhttp_metric_handler_errors_total counter
  build date:       20211005-16:10:52                                                                                                                          │promhttp_metric_handler_errors_total{cause="encoding"} 0
  go version:       go1.17.1                                                                                                                                   │promhttp_metric_handler_errors_total{cause="gathering"} 0
  platform:         linux/amd64  
```

* Prometheus configuration file:

Contents of `file_sd/test_job.yml`:

```
[
  {
    "labels": {
      "job": "test_job"
    },
    "targets": [
      "[fe80::f1ee:adeb:371d:983%eth1]:9100"
    ]
  }
]
```

* Logs:

No relevant logs as this appears to be a frontend issue, there are no errors in the Chrome dev tools console.

**Comment by LeviHarrison** [comment]
This happens because the native Javascript `URL` class doesn't seem to support IPv6.

https://github.com/prometheus/prometheus/blob/8b25e35a3edbce8eb23c8c855973dfe81171bee7/web/ui/react-app/src/pages/targets/EndpointLink.tsx#L12

**Comment by ben-wallis** [comment]
I think it's specific to IPv6 with zone IDs - it does render correctly with an IPv6 address without a zone ID (the `%eth1` part in my example). This is required for link-local addresses, but isn't actually supported in URLs in most browsers. So even if it was rendered correctly it would result in a URL that most browsers would refuse to navigate to. Not sure if that really matters though since that's not exactly Prometheus' fault.

**Comment by LeviHarrison** [comment]
> I think it's specific to IPv6 with zone IDs - it does render correctly with an IPv6 address without a zone ID (the %eth1 part in my example).

Ah OK.

> So even if it was rendered correctly it would result in a URL that most browsers would refuse to navigate to. Not sure if that really matters though since that's not exactly Prometheus' fault.

If Prometheus can scrape a target using the URL, we should be able to display it. There are lots of instances where URLs might not be accessible from the browser, like if the targets are on a different network or require authentication.

**Comment by roidelapluie** [comment]
We have looked at this during the bug scrub. We should indeed display it if we can scrape it, even if this sounds like a niche use case. if the fix is not too complex, let's fix it.

**Comment by mtfoley** [comment]
I'd love to try to help out with a PR for this one. Based on looking through the section of code linked to previously, would it be worthwhile to use a synthetic URL to salvage the query parameters for the badges? e.g.
```js
const EndpointLink: FC<EndpointLinkProps> = ({ endpoint, globalUrl }) => {
  let url: URL;
  let search: string = '';
  let invalidURL: boolean = false;
  try {
    url = new URL(endpoint);
  } catch (err: unknown) {
    invalidURL = true;
    if(endpoint.indexOf('?') > -1) search = endpoint.substring(endpoint.indexOf('?'));
    url = new URL('http://0.0.0.0'+search); 
  }
  const { host, pathname, protocol, searchParams }: URL = url;
  const params = Array.from(searchParams.entries());
  return (
    <>
      invalidURL && <a href={globalUrl}>{globalUrl.replace(search,'')}</a>
      !invalidURL && <a href={globalUrl}>{`${protocol}//${host}${pathname}`}</a>
      {params.length > 0 ? <br /> : null}
      {params.map(([labelName, labelValue]: [string, string]) => {
        return (
          <Badge color="primary" className="mr-1" key={`${labelName}/${labelValue}`}>
            {`${labelName}="${labelValue}"`}
          </Badge>
        );
      })}
    </>
  );
}
```

**Comment by LeviHarrison** [comment]
Thanks for taking the time to propose a solution!

I'm not sure that solely URL parameters would be of much use. And, given that they're provided as a configuration option for an entire job, you wouldn't be able to distinguish individual targets.
