### ISSUE TITLE
Unsual lag when running HA pair

### ISSUE THREAD

**Issue by wilfriedroset** [prometheus/prometheus#9807]
**What did you do?**
I'm facing a issue with my HA pairs of Prometheus. All HA pairs are remote writing to Cortex where ha tracker is enabled but both replica start lagging with a significant amount a context-switch.

On the attached screenshot we can see the result of this query:
`prometheus_remote_storage_highest_timestamp_in_seconds{instance=~"$instance"} - on (job, instance) prometheus_remote_storage_queue_highest_sent_timestamp_seconds{instance=~"$instance"}`
Cortex on its end is quite happy with only HTTP 200 on both the write path.

<img width="1352" alt="time difference" src="https://user-images.githubusercontent.com/12611310/142430531-74c61977-6b0a-43ea-b1e7-f9511c088560.png">

On the screenshots above, At ~15:30, I’ve completely stop all prometheus, reboot all instances and start everything up again. I’ve 5 HA pair of prometheus writing to the same cortex. They are scraping 5000 targets/~10M series per HA pair.

One interesting point is the regularity of the pattern. Lag stable for 4h, then increasing lag for 4h, and so on.
We can also see that prometheus instances show a very high context-switching.

![time difference and shards](https://user-images.githubusercontent.com/12611310/142430739-661a385d-7a47-48b7-9bd6-ee52a85c77e9.png)
![contex switch and interupt](https://user-images.githubusercontent.com/12611310/142430754-4af27bfb-7364-4d1c-82d0-0820fcdbdbc2.png)
![tsdb status](https://user-images.githubusercontent.com/12611310/142430764-2424a1e2-0bf2-4f32-a77c-1b804f5eb4b6.png)
![ha tracking](https://user-images.githubusercontent.com/12611310/142430765-b3e31784-f3d5-4529-8bc6-6c02c7cfd6b6.png)

From the remote storage point of view, everything is working as expected
![cortex distributor](https://user-images.githubusercontent.com/12611310/142430758-80241312-562f-4e4f-a451-9cfb46590228.png)
![cortex ingester](https://user-images.githubusercontent.com/12611310/142430762-a882961f-1f2c-4e58-8eb1-f403b48f4583.png)

**What did you expect to see?**
No lag in my prometheus as long as my remote storage can keep up (which is the case)

**What did you see instead? Under which circumstances?**

**Environment**

* System information:
  * debian 10 Linux 4.19.0-18-cloud-amd64 x86_64
  * 400 GB storage SSD ext-4
  * 4 Gbit/s private network

* Remote storage information:
  * Cortex 1.10.0 on baremetal
    * 6 distributors
      * 60 GB RAM / 16 vcpus
    * 12 ingesters
      * 120 GB RAM / 32 vcpus

* Prometheus version:

* 5 HA pairs of Prometheus 2.30.2 on baremetal
  * 120 GB RAM / 32 vcpus

* Alertmanager version:
Not used

* Prometheus configuration file:
```
global:
  evaluation_interval: 15s
  scrape_interval: 15s
  scrape_timeout: 10s

  external_labels:
    __replica__: prometheus-4
    cluster: '2'


remote_write:
  - name: cortex
    queue_config:
      max_samples_per_send: 1000
      retry_on_http_429: true
    send_exemplars: true
    url: http://rw.cortex.service.dc1.consul:9009/api/v1/push


rule_files:
  - /etc/prometheus/rules/*.rules


scrape_configs:
  - file_sd_configs:
    - files:
      - /etc/prometheus/file_sd/*.yml
    job_name: node-exporter-bench
    metrics_path: /metrics
```

* Alertmanager configuration file:
Not used

* Logs:
Over the time range prometheus logs (in debug) are not reporting unusual message. I've a lot of `"Flushing data to remote storage..."` and `"Remote storage resharding"`.

**Comment by bboreham** [comment]
Personally in this repo I would focus less on the remote-write lag, which might be blamed on the back end, and more on the 500,000 context-switches per second which has to originate somewhere in the Prometheus (or Go runtime) code.

We had similar things happen at Grafana Labs, tried bigger and bigger machines but they just can't context-switch any faster.

**Comment by wilfriedroset** [comment]
Here's what we can see at the system level

```
timeout 120 strace -c -f -p $(pidof prometheus)
strace: Process 6041 attached with 40 threads
strace: [ Process PID=6089 runs in x32 mode. ]
strace: [ Process PID=6088 runs in x32 mode. ]
strace: [ Process PID=6086 runs in x32 mode. ]
strace: [ Process PID=6088 runs in 64 bit mode. ]
strace: [ Process PID=6086 runs in 64 bit mode. ]
strace: [ Process PID=6084 runs in x32 mode. ]
strace: [ Process PID=6078 runs in x32 mode. ]
strace: [ Process PID=6078 runs in 64 bit mode. ]
strace: [ Process PID=6089 runs in 64 bit mode. ]
strace: [ Process PID=6071 runs in x32 mode. ]
strace: [ Process PID=6071 runs in 64 bit mode. ]
strace: [ Process PID=6062 runs in x32 mode. ]
strace: [ Process PID=6060 runs in x32 mode. ]
strace: [ Process PID=6062 runs in 64 bit mode. ]
strace: [ Process PID=6084 runs in 64 bit mode. ]
strace: [ Process PID=6060 runs in 64 bit mode. ]
strace: [ Process PID=6058 runs in x32 mode. ]
strace: [ Process PID=6058 runs in 64 bit mode. ]
strace: Process 6041 detached
strace: Process 6053 detached
strace: Process 6054 detached
strace: Process 6055 detached
strace: Process 6056 detached
strace: Process 6057 detached
strace: Process 6058 detached
strace: Process 6059 detached
strace: Process 6060 detached
strace: Process 6061 detached
strace: Process 6062 detached
strace: Process 6063 detached
strace: Process 6064 detached
strace: Process 6065 detached
strace: Process 6066 detached
strace: Process 6067 detached
strace: Process 6068 detached
strace: Process 6069 detached
strace: Process 6070 detached
strace: Process 6071 detached
strace: Process 6072 detached
strace: Process 6073 detached
strace: Process 6074 detached
strace: Process 6075 detached
strace: Process 6076 detached
strace: Process 6077 detached
strace: Process 6078 detached
strace: Process 6079 detached
strace: Process 6080 detached
strace: Process 6081 detached
strace: Process 6082 detached
strace: Process 6083 detached
strace: Process 6084 detached
strace: Process 6085 detached
strace: Process 6086 detached
strace: Process 6087 detached
strace: Process 6088 detached
strace: Process 6089 detached
strace: Process 6385 detached
strace: Process 6386 detached
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
 61.69  587.276796         769    763388     78890 futex
 17.26  164.269921          24   6657426           sched_yield
  8.02   76.355985         183    415936         5 epoll_pwait
  3.44   32.764893         238    137401        21 nanosleep
  2.76   26.272747       15694      1674        33 rt_sigreturn
  2.65   25.216044          75    334005           write
  1.29   12.325953        7276      1694           tgkill
  1.29   12.297858        7255      1695           getpid
  1.19   11.297593          71    157523     42521 read
  0.34    3.223940       46723        69        67 connect
  0.04    0.397067        2796       142        16 epoll_ctl
  0.01    0.075521         260       290           setsockopt
  0.00    0.042777         619        69           socket
  0.00    0.026639       26639         1           fsync
  0.00    0.020013         312        64           close
  0.00    0.013397         181        74           getsockname
  0.00    0.011324         166        68           getpeername
  0.00    0.007572         114        66           getsockopt
  0.00    0.004524          15       296           newfstatat
  0.00    0.004095         273        15           getdents64
  0.00    0.001212         101        12         6 accept4
  0.00    0.000772         154         5           fstat
  0.00    0.000156           8        19           openat
  0.00    0.000011          11         1           restart_syscall
  0.00    0.000000           0         6           fcntl
------ ----------- ----------- --------- --------- ----------------
100.00  951.906810               8471939    121559 total
```

With perf it's a bit clearer
```
# timeout 120 perf record -e context-switches -a -g
WARNING: Kernel address maps (/proc/{kallsyms,modules}) are restricted,
check /proc/sys/kernel/kptr_restrict.

Samples in kernel functions may not be resolved if a suitable vmlinux
file is not found in the buildid cache or in the vmlinux path.

Samples in kernel modules won't be resolved at all.

If some relocation was applied (e.g. kexec) symbols may be misresolved
even with a suitable vmlinux or kallsyms file.

Couldn't record kernel reference relocation symbol
Symbol resolution may be skewed if relocation was used (e.g. kexec).
Check /proc/kallsyms permission or run as root.
[ perf record: Woken up 1354 times to write data ]
[kernel.kallsyms] with build id f73bed50bd33647e7f740c49321c569daa6eb04a not found, continuing without symbols
[ perf record: Captured and wrote 341.815 MB perf.data (3253193 samples) ]
```
```
+   50.35%    50.35%  swapper          [unknown]                 [k] 0xffffffffae45583e
-   49.45%    49.45%  prometheus       [unknown]                 [k] 0xffffffffae455598
   - 49.38% runtime.goexit.abi0
      - 46.88% github.com/prometheus/prometheus/storage/remote.(*shards).start.dwrap.28
         - 46.88% github.com/prometheus/prometheus/storage/remote.(*shards).runShard
            - 46.75% runtime.selectgo
               - 35.10% runtime.sellock
                  - 34.62% runtime.lock2
                     - 34.61% runtime.futex.abi0
                          34.61% 0xffffffffae455598
               + 11.64% runtime.mcall
      + 2.25% github.com/prometheus/prometheus/tsdb/wal.(*Watcher).Start.dwrap.9
+   49.38%     0.00%  prometheus       prometheus                [.] runtime.goexit.abi0
+   49.24%     0.00%  prometheus       prometheus                [.] runtime.selectgo
-   46.88%     0.00%  prometheus       prometheus                [.] github.com/prometheus/prometheus/storage/remote.(*shards).start.dwrap.28
   - github.com/prometheus/prometheus/storage/remote.(*shards).start.dwrap.28
      - 46.88% github.com/prometheus/prometheus/storage/remote.(*shards).runShard
         - 46.75% runtime.selectgo
            + 35.10% runtime.sellock
            + 11.64% runtime.mcall
-   46.88%     0.00%  prometheus       prometheus                [.] github.com/prometheus/prometheus/storage/remote.(*shards).runShard
   - github.com/prometheus/prometheus/storage/remote.(*shards).runShard
      - 46.75% runtime.selectgo
         - 35.10% runtime.sellock
            + 34.62% runtime.lock2
         + 11.64% runtime.mcall
+   41.27%     0.00%  prometheus       prometheus                [.] runtime.futex.abi0
+   37.35%     0.00%  prometheus       prometheus                [.] runtime.sellock
+   36.87%     0.00%  prometheus       prometheus                [.] runtime.lock2
+   12.04%     0.00%  prometheus       prometheus                [.] runtime.mcall
+   12.04%     0.00%  prometheus       prometheus                [.] runtime.schedule
+   12.03%     0.00%  prometheus       prometheus                [.] runtime.findrunnable
+   11.94%     0.00%  prometheus       prometheus                [.] runtime.park_m
+    7.24%     0.00%  swapper          [unknown]                 [k] 0xffffffffade9826a
+    7.11%     0.00%  prometheus       prometheus                [.] runtime.usleep.abi0
+    7.07%     0.00%  prometheus       prometheus                [.] runtime.stealWork
+    7.07%     0.00%  prometheus       prometheus                [.] runtime.runqsteal
+    7.07%     0.00%  prometheus       prometheus                [.] runtime.runqgrab
+    4.40%     0.00%  prometheus       prometheus                [.] runtime.stopm
+    4.40%     0.00%  prometheus       prometheus                [.] runtime.mPark
+    4.40%     0.00%  prometheus       prometheus                [.] runtime.notesleep
+    2.25%     0.00%  prometheus       prometheus                [.] github.com/prometheus/prometheus/tsdb/wal.(*Watcher).Start.dwrap.9
+    2.25%     0.00%  prometheus       prometheus                [.] github.com/prometheus/prometheus/tsdb/wal.(*Watcher).loop
+    2.25%     0.00%  prometheus       prometheus                [.] github.com/prometheus/prometheus/tsdb/wal.(*Watcher).Run
+    2.25%     0.00%  prometheus       prometheus                [.] github.com/prometheus/prometheus/tsdb/wal.(*Watcher).watch
+    2.25%     0.00%  prometheus       prometheus                [.] github.com/prometheus/prometheus/tsdb/wal.(*Watcher).readSegment
+    2.25%     0.00%  prometheus       prometheus                [.] github.com/prometheus/prometheus/storage/remote.(*QueueManager).Append
+    2.25%     0.00%  prometheus       prometheus                [.] github.com/prometheus/prometheus/storage/remote.(*shards).enqueue
+    0.55%     0.00%  prometheus       prometheus                [.] runtime.epollwait.abi0
+    0.51%     0.00%  prometheus       prometheus                [.] runtime.osyield.abi0
+    0.51%     0.00%  prometheus       [unknown]                 [.] 0xffffffffadea354f
```

Here  is what we can see with pprof
![profile001](https://user-images.githubusercontent.com/12611310/142653392-48545e3c-1dc0-40c8-9b45-0567d8186341.png)

You can find the pprof file and perf file here:
[perf.data.gz](https://github.com/prometheus/prometheus/files/7571438/perf.data.gz)
[prometheus.pprof.gz](https://github.com/prometheus/prometheus/files/7571440/prometheus.pprof.gz)

**Comment by roidelapluie** [comment]
Could you show us what is your number of shards? It seems that it is changing a lot in your case, some tuning might be needed (increase the minimal number of shards).

I know we have remote write in the *prometheus* mixin, seeing what that looks like might help.

**Comment by csmarchbanks** [comment]
Thank you for all of the data, I am exploring this issue right now. If you are resharding a lot that can cause a slowdown for sure and having a set number of minimum shards is helpful. 

Looking at your profiles the slowdown I think comes the slowdown comes from reading each sample from a channel, I am looking into batching those instead to reduce the select hotspot you see.

**Comment by wilfriedroset** [comment]
I've tried with the default values `min_shard: 1`, `max_shard: 200`.
Now I'm running with `min_shard: 4` and `max_shard: 100`.
In the comment we can see that the shard desired are going like crazy.
Here is what they look like today on one prometheus after apply the new min_shard/max_shard (green line at 100):
<img width="1345" alt="prom4-shard" src="https://user-images.githubusercontent.com/12611310/142681319-587fa069-3d87-447a-9c37-db592ac1319b.png">

As suggested by @bboreham I've splitted my workload, I've 20 HA pairs responsible for 2500 targets each. All of them are showing the same pattern.
<img width="1347" alt="20-prom-shard" src="https://user-images.githubusercontent.com/12611310/142681836-11078bb9-4117-457c-8c66-b4fb09274200.png">

Apart from the shard pattern shown above I don't see something specific in the remote write dashboard from prometheus mixin.

**Comment by csmarchbanks** [comment]
@wilfriedroset Any chance you would be willing and able to test out the change in https://github.com/prometheus/prometheus/pull/9830 in a safe manner? I am also planning to test it out in some of our clusters, but the more eyes/validation the better.

**Comment by wilfriedroset** [comment]
I will have a look at it.
In the meantime I've remove the single loadbalancer between my many prometheus and cortex.
For ~24h I've been using consul for it  dns loadbalancing which is not that great to even the load on cortex's distributor. But it was not better from prometheus.
![Capture d’écran 2021-11-25 à 10 20 17](https://user-images.githubusercontent.com/12611310/143414228-eeb2410a-38e5-4517-abd6-f3075cb64d9d.png)
![Capture d’écran 2021-11-25 à 10 20 24](https://user-images.githubusercontent.com/12611310/143414240-2c0dcbfe-701f-4652-8991-feb90b48f09f.png)
Then I've deployed a loadbalancer on each prometheus instance and configure them to use their own loadbalancer (hence the significant improvement at 2PM on the  screenshot above).

Here is the configuration of the haproxy (same all over the place apart from the private ip)
```
root@cortex-lb-1:~# cat /opt/consul-template/templates/haproxy.ctmpl
global
    daemon
    master-worker
    log-send-hostname

    chroot              /var/lib/haproxy
    log                 127.0.0.1 local2

    pidfile             /var/run/haproxy.pid
    server-state-base   /var/lib/haproxy/state

    user                haproxy
    group               haproxy

    maxconn             40000

    stats socket /var/run/haproxy.sock mode 666 level admin
    stats timeout 30s

    # utilize system-wide crypto-policies
    ssl-default-bind-ciphers    PROFILE=SYSTEM
    ssl-default-server-ciphers  PROFILE=SYSTEM

defaults
    log                             global
    load-server-state-from-file     local
    retries                         6

    option                          dontlognull
    option                          log-separate-errors

    timeout  check                  5s
    timeout  client                 1m
    timeout  client-fin             10s
    timeout  connect                3s
    timeout  http-request           10s
    timeout  queue                  1m
    timeout  server                 5m
    timeout  tunnel                 30m
    timeout  http-keep-alive        10s

    default-server fall 3 inter 1000 rise 2 downinter 1000 weight 10 maxconn 2000

listen distributor
    bind                            [redacted]:9009

    mode                            http
    option                          httplog
    option                          http-server-close
    option forwardfor except        127.0.0.0/8
    option                          redispatch
    balance                         roundrobin
    log-format                      "%ci:%cp [%tr] %ft %b/%s %TR/%Tw/%Tc/%Tr/%Ta %ST %B %CC %CS %tsc %ac/%fc/%bc/%sc/%rc %sq/%bq %hr %hs %{+Q}r"
    maxconn             40000
    fullconn            40000

    option  httpchk GET /ready{{ range service "distributor.cortex|any" }}
    server {{ .Node }} {{ .Address }}:{{ .Port }} check{{ end }}
```
And the new configuration of the remote write, basically using the loadbalancer on the same instance
```
remote_write:
  - name: cortex
    queue_config:
      max_samples_per_send: 1000
      max_shards: 100
      min_shards: 4
      retry_on_http_429: true
    send_exemplars: true
    url: http://localhost:9009/api/v1/push
```

So I guess the not optimal haproxy configuration 😅  is triggering the behavior explained in the first post.

**Comment by wilfriedroset** [comment]
@csmarchbanks I've been testing your branch for ~24h on half of my prometheus HA pairs.
I can confirm that context switches are a lot better.
We can see on the screenshot below that we have 3 lines representing:
* blue line, `sum(irate(node_context_switches_total[10m]))`
* green line, ` sum(irate(node_context_switches_total{instance=~"prometheus-(3|5|11|14|17|4|6|12|13|18)"}[10m]))` running prometheus built from #9830
* yellow line, `sum(irate(node_context_switches_total{instance!~"prometheus-(3|5|11|14|17|4|6|12|13|18)"}[10m]))` running prometheus 2.30.2
<img width="1362" alt="patched-prometheus" src="https://user-images.githubusercontent.com/12611310/143771679-244e99e2-0216-455a-a5de-a41e8e78f0aa.png">

I will continue the test by deploying the patched version everywhere.

**Comment by wilfriedroset** [comment]
Test was successful all over the place and I witness the expected behavior (less context switching)
<img width="1362" alt="patched-prometheus-2" src="https://user-images.githubusercontent.com/12611310/143872374-589d62bb-e080-47e7-95fb-b8ab2521a203.png">
<img width="1362" alt="patched-prometheus-3" src="https://user-images.githubusercontent.com/12611310/143872392-8935b55a-2796-4d97-9b1b-d3f1467c0708.png">

**Comment by roidelapluie** [comment]
@wilfriedroset Prometheus will never question DNS again once the requests are open, HAProxy would work best. We do not have client side load balancing.

**Comment by csmarchbanks** [comment]
@wilfriedroset Thanks for testing out the PR! Glad to see that context switches are significantly lower as I hoped. Does it make a difference on general load on the Prometheus instances as well?

For client side load balancing https://github.com/prometheus/prometheus/issues/8402 exists, but I don't think there is agreement much less work being done yet. Your HAProxy solution is probably the way to go for now.

**Comment by wilfriedroset** [comment]
I did not witness any difference on the load or on the overall performance.
I'm comfortable with a load balancing server side.

**Comment by csmarchbanks** [comment]
I have merged #9830, though it will not be in a release until v2.33.0. The rest of this issue seems to be covered by #8402/using a proxy to achieve client side load balancing so I am going to close it. Let me know if you think there is remaining work not covered.

**Comment by rajatvig** [comment]
Did this make it to 2.33.0? Not seeing in the changelog

**Comment by bboreham** [comment]
Yes, #9830 was part of 2.33.0.  You can see it in the code here, for instance: https://github.com/prometheus/prometheus/blame/v2.33.0/storage/remote/queue_manager.go#L912

@beorn7 I think you did the release; should it be in the CHANGELOG?

**Comment by beorn7** [comment]
Ooh yeah, that slipped… Probably because the original commits were so old that I didn't look back far enough.

Feel free to send me a PR against CHANGELOG.md.
