### ISSUE TITLE
hashmod uses fnv

### ISSUE THREAD

**Issue by miekg** [prometheus/prometheus#981]
Hi,

We see a huge discrepancy in the load hitting our scraping prometheus-ussss. We use hashmod to spread the load. hashmod used fnv which is a "non-cryptographic hash function". I think it makes sense to just use a crypto hash for hashmod, like md5 or sha1 which should result in a more even load distribution.

**Comment by brian-brazil** [comment]
What sort of skew are you seeing, and what sort of cardinality does the label you're hashing have?

**Comment by miekg** [comment]
eyeballing some graphs: the skew is 100%. The load of prometheus1 is twice the load of prometheus0. The string we hash is (ultimately) defined by the user and frequently starts with the some prefix, we could  do some transformations here, but "just" using a crypto hash function would solve this.

**Comment by brian-brazil** [comment]
That sounds like a misconfiguration rather than a skew issue. Can you share your configuration?

It's recommended to hash on something like `__address__` or `instance`.

**Comment by miekg** [comment]
No, we can't split this on `__address__` or the like, we want to keep stuff that is related in a job on the same prometheus.

**Comment by brian-brazil** [comment]
The sharding functions are intended for use when a single job has gotten so big that it won't fit on a single prometheus server. Up to that point we recommend splitting off Prometheus servers based on functionality/team/level of stack.

Given this you're best off running separate Prometheus servers and managing the split yourself, which also avoids all the complexity of a master/slave setup.

**Comment by miekg** [comment]
But why being so hesitant of changing the hash function? Is that because of performance reasons?

I don't think how we structured our setup is particularly strange and it would work perfectly (out-of-the-box) is hashmod was just doing a crypto hash.

**Comment by brian-brazil** [comment]
I've no problem changing the hash function if there's significant skew. There's no performance concerns here as it's only calculated when a target is created or updated. How many jobs do you have?

It doesn't sound like this is a good way to do your setup though. It's a very advanced feature meant for a  specific use case, It's not meant to split things out on something as coarse as `job`, `rack` is about the limit. If you want to use this you need to shard based on address, and then manage the master/slave setup that requires. That's a lot of work so we recommend manually choosing which jobs go where, until you get to a stage that you have jobs that won't fit on one prometheus and you're forced to use sharding.

**Comment by miekg** [comment]
It already does not fit on one prometheus instance :) That's why we are using a federated setup and use hashmod to shared on the job level.

Thanks for considering this request!

**Comment by brian-brazil** [comment]
> It already does not fit on one prometheus instance :) 

The problem comes when a single job doesn't fit. All your jobs not fitting is much easier to deal with..

Can you give examples of the job names that all got put on the same shard, and how many shards you're using?

**Comment by juliusv** [comment]
Totally agree, this shouldn't be using FNV. That hash is notorious for only changing the output a little if the input changes only a little. If you have two places that change only a little in the input, you can often even get the same output again, which is what might be biting you here (still would be interesting to get some colliding examples though to confirm). Let's switch this to a better hash. I'm on vacation for the rest of the week, but :+1: in general.

**Comment by fabxc** [comment]
:+1: there are no downsides in switching the hash function. Especially if
it allows for another use-case.

**Comment by brian-brazil** [comment]
#982 is merged now. It's not clear this allows for another use case, as job sizes are generally going to be too variable to shard based on.
