### ISSUE TITLE
Add `source_tenants` to rule definitions

### ISSUE THREAD

**Issue by dimitarvdimitrov** [prometheus/prometheus#9814]
## Proposal
To add a new field `source_tenants` to alerting and recording rules. 

**Use case. Why is this important?**
This field will be useful when there are multiple prometheus instances we want to aggregate the rules over. Currently it is not possible to store this data as first-class citizen. It has to be cramped up in the annotations.

https://github.com/prometheus/prometheus/issues/9815 shows the proposed change

**Comment by roidelapluie** [comment]
This seems very specific. How are you aggregating rules? Which API endpoints are you using?

At first glace, adding the external labels to the API *might* be a better solution.

**Comment by roidelapluie** [comment]
Note that this seems to also be what the "labels" field is made for.

**Comment by dimitarvdimitrov** [comment]
The use case is when the expression in a single rule needs to be ran against multiple prometheis.

> How are you aggregating rules? Which API endpoints are you using?

We're essentially querying multiple prometheis and then merging the results. So the endpoint equivalent will be `GET /api/v1/query`.

> Note that this seems to also be what the "labels" field is made for.

The resulting labels need not necessarily be changed, so the `labels` field doesn't work that well. We only need to know which prometheis to query (i.e. which `tenants` to get the `source` metrics from)

**Comment by roidelapluie** [comment]
It looks like this problem is outside of the Prometheus scope, you can add labels to identify your tenants if that is needed, or use an external classifier or convention in filenames to know for which "tenant" a rule applies. I have to admit that I do not fully grasp the usecase, but adding arbitrary fields into the API does not seem an appropriate solution to me. cc @juliusv for a second opinion.

**Comment by juliusv** [comment]
I'm also a bit confused about the use case and the exact monitoring and querying setup you are describing. Looking at https://github.com/prometheus/prometheus/pull/9815, I see the new `source_tenants` field being added everywhere, but I don't see it actually being used for anything?

**Comment by hanjm** [comment]
I think add label-based matcher to rules api is more reasonable and generic 😄 look at this issue: https://github.com/prometheus/prometheus/issues/9627

**Comment by dimitarvdimitrov** [comment]
@juliusv @roidelapluie This gives a better overview of the use case https://github.com/cortexproject/cortex/pull/4477. We're essentially going to use the API models to store the rules and read the `source_tenants` when evaluating each rule.

@roidelapluie you mentioned 
> At first glace, adding the external labels to the API _might_ be a better solution.

What do you refer to as "external labels?"

@hanjm If I'm understanding your proposal correctly, you propose to add a query search parameter to the API. The parameter will be used to limit the rules that the API returns. I don't think this is going to work for us. We need the "tenants" on the API responses, so that we know what to do with each rule.

**Comment by juliusv** [comment]
@dimitarvdimitrov That leaves a bit more confused. Tenants are a Cortex concept and don't exist in Prometheus. What exactly would the behavior be that you are looking for? E.g. when you add your new rule fields and someone sets them, what happens exactly? Is the data queried differently (and in what way), or is it just stored differently (and in what way)?

**Comment by dimitarvdimitrov** [comment]
@juliusv The expression in the rule will be evaluated differently. Instead of querying the data from a single backing TSDB, it will query multiple TSDBs (of the different tenants). The rule eval result will be written in the same way.

**Comment by juliusv** [comment]
@dimitarvdimitrov But in Prometheus, there is only one TSDB, or were you planning on using this new code in Cortex only? I don't think we should add a specific tenants field to rule code in Prometheus that isn't used by Prometheus itself...

**Comment by dimitarvdimitrov** [comment]
That makes sense. I think at this point it's logical to close this. Thanks for considering it.
