### ISSUE TITLE
promql function to sum distinct for gauge value

### ISSUE THREAD

**Issue by alileza** [prometheus/prometheus#9822]
## Background

I have some issue with trying to build promql query from metrics that are being scraped from telegraf. For example
```
query: my_metrics{app="telegraf"}[5m]

result: {app="telegraf"} 336 @1637319417.799
                         336 @1637319427.803
                         336 @1637319437.799
                         510 @1637319497.799
                         317 @1637319507.799
                         317 @1637319517.799
                         317 @1637319527.799
                         317 @1637319537.799
                         317 @1637319547.799
                         317 @1637319557.799
```

So I'm trying to get the sum_over_time from that gauge, but since Prometheus keeps pulling the same value until telegraf flushes the gauge from memory.
It kinda messed up the query result, from that 5m interval, I'm expecting to get 336+510+317 instead of all.

## Proposal

Would be nice to have a function to distinct gauge value over time, so we can get the right amount of sum, or maybe I'm missing a way to get the right value.

**Comment by juliusv** [comment]
Hi! From what I understand, you are trying to track values from individual events, to then sum those up. Indeed with the scraping / metrics model of Prometheus, that is not possible, as the scrape is decoupled from the event and Prometheus fundamentally tracks metrics and not individual events. So the way you'd usually approach this is to expose a counter metric instead, which would already be the cumulative total over all tracked events.

**Comment by roidelapluie** [comment]
Another big issue with this approach is that it would rely on every measurement to contain a different value. This would be a confusing function for most PromQL users, and I fear it could even not fulfil your usecase because of this requirement.

**Comment by juliusv** [comment]
Yes, forgot to mention that explicitly!

**Comment by alileza** [comment]
@juliusv yes you got it right, in my case, I don't own the service, I'm just trying to translate influxql to promql, in a hope that I don't need on influxdb anymore 🤞

@roidelapluie I kinda share the same feeling, initially, I was trying to create a different function like `distinct`, which should return distinct value in a vector, I think that one shares a more common understanding among users. But this is my first time touching promql folder, and  I was a bit stuck trying to do that func earlier, and ended up having this proposal. Do you think distinct is more acceptable?

**Comment by roidelapluie** [comment]
Which prometheus integration are you using with teleraph? Maybe switching to remote write could help: https://github.com/influxdata/telegraf/blob/master/plugins/serializers/prometheusremotewrite/README.md (you need --enable-feature=remote-write-receiver and push to https://prometheus:9090/api/v1/write)

**Comment by alileza** [comment]
the setup that we have is bunchs of telegraf  prometheus scrape telegraf

**Comment by alileza** [comment]
our setup is like bunch of telegraf daemonset that expose http output with prometheus format and the metrics flushes every 2mins or something like that

**Comment by alileza** [comment]
ok I changes the architecture to use telegraf push to prometheus api/v1/write, rather than prometheus scraping telegraf and it looks promising, thank you @roidelapluie 🙏 

in this case I don't think I need distinct function since metrics stored exactly one time. So I guess unless there's other needs for this function, this issue can be closed I guess?

I'm not an expert on promql but having such a function might be beneficial for some cases

**Comment by alileza** [comment]
if you folks think a distinct function is worthy to add, I can try to find some time wrapping up the function @juliusv @roidelapluie otherwise I guess we can pause or drop it :)

**Comment by juliusv** [comment]
> in this case I don't think I need distinct function since metrics stored exactly one time.

Note that even with push, you are still treating time series samples as individual *events* with a special identity, whereas the whole Prometheus computational assumes a relatively arbitrary sampling of *state* (meaning the current value of something that is ongoing and that could be sampled as frequently as you want). It can always happen that either some pushes / scrapes fail (in which case some events would be lost), or that time series are downsampled at some later point in time, and the query language is also not really geared around an event-based use case. So I still don't think it fits well into the Prometheus model...

**Comment by peterbourgon** [comment]
@alileza 

> I'm expecting to get 336+510+317 instead of all

Prometheus may scrape its targets on discrete intervals, but metrics are actually continuous, so the concept of unique values of a gauge isn't really sensical. When you "push" a value of 336, you're not sending a single event, you're setting the gauge to a value, and it will retain that value indefinitely.

**Comment by beorn7** [comment]
Hello from the bug scrub!

We decided to close this for now as nothing has been moving here in the last 2.5y. The general considerations above about this function not really fitting the Prometheus data model well are legitimate, but we also acknowledge that we have derived from that pure view in the past (cf. `changes` function). If anyone plans to invest work into this, please follow up and we can discuss further.
