### ISSUE TITLE
"Unknown series references" caused by samples written to WAL before series

### ISSUE THREAD

**Issue by pracucci** [prometheus/prometheus#9841]
In case we have 2+ concurrent appenders writing a series which doesn't exist yet, the 1st call to `appender.Append()` will create the series while other appends will just append the sample.

When a series is created, it's appended to the list of new series created within the `headAppender`:
https://github.com/prometheus/prometheus/blob/f08c89e569b2421bcc8ef7caf585fd8d3c2ccaba/tsdb/head_append.go#L260-L265

During the `headAppender.Commit()` we call `headAppender.log()` which writes any new series to the WAL before samples:
https://github.com/prometheus/prometheus/blob/f08c89e569b2421bcc8ef7caf585fd8d3c2ccaba/tsdb/head_append.go#L376-L383

However, in case there are multiple concurrent appenders appending (different) samples for the same series, the first appender will create the series and subsequent ones will just append samples. There's no guarantee that the `Commit()` is executed on the appender which created the series before others, so there's no guarantee that the series is written to the WAL before other appenders write its samples to the WAL, thus leading to "Unknown series references" while replaying the WAL.

A unit test reproducing the issue is here:
https://github.com/prometheus/prometheus/pull/9842

**Comment by codesome** [comment]
The case of samples record coming before series record is possible only in case of miconfiguration where 2 scrape jobs are scraping same metrics with no unique labels attached. Or, relabelling during remote write is stripping the unique labels. Trying to fix this in TSDB (i.e. either syncing appenders to write write all series record before samples record, or reorder replay of WAL records) will get very complex, so I suggest fixing the config to avoid clashing series in different appends, and we fix #9846 so that Prometheus can start gracefully in such situations.

**Comment by pracucci** [comment]
> The case of samples record coming before series record is possible only in case of miconfiguration where 2 scrape jobs are scraping same metrics with no unique labels attached.

Not true for the case of Cortex where, due to quorum, we may still have inflight requests in ingesters after we send the response back to the client (Prometheus) but I agree that this is an edge case and I think we should just fix the panic for now.

**Comment by pracucci** [comment]
> Trying to fix this in TSDB (i.e. either syncing appenders to write write all series record before samples record, or reorder replay of WAL records) will get very complex

An option could be logging the series creation to WAL as soon as the series is created instead of waiting for `appender.Commit()`, considering the log series creation to WAL even in case of `appender.Rollback()` (because series creation is not rolled back).

**Comment by codesome** [comment]
> An option could be logging the series creation to WAL as soon as the series is created instead of waiting for appender.Commit(),

That would create too many series records. We batch them up in Commit() currently. We could see how that trade-off works out, it would be non-ideal in terms of disk write calls.

But that still will not solve this issue. After creating series and before logging the series record into the WAL, some other competing appender can log a sample in between.

**Comment by pracucci** [comment]
Agree Ganesh. In any case I still think it's not worth to fix, as far as we get the WAL reply working correctly if this case happens (hopefully #9856 fixes it).

**Comment by pracucci** [comment]
Fixed by #9856.
