### ISSUE TITLE
ipv6 target url Error: Failed to construct 'URL': Invalid URL

### ISSUE THREAD

**Issue by chris-fengtian-guo** [prometheus/prometheus#9872]
Describe the issue.  when prometheus configure with ipv6 target , for example http://192.168.113.25:9090/targets
Failed to construct 'URL': Invalid URL -> the root cause is for ipv6 web url 2000::24:9290 it should add [] for ipv6 address 
http://[2000::24]:9100/

This is screen shot of the fail of 9090 targets
![prometheus_ipv6_target_url_bug_20211126185549](https://user-images.githubusercontent.com/88421048/143570371-04cbdbb7-74ed-4fba-868b-9396c422e044.png)

I'm just beginer to the go language and I used C language to programe
I have make a drift patch to fix the bug but I didn't find where to upload the patch

1) following is my configure for 100% reproduce this bug

For examples http://192.168.113.25:9090/targets show the invalid URL

[root@hs25 ~]# ps auxw|grep prometheus
prometh+   33286  0.6  0.2 1260308 146196 ?      Ssl  Nov24  20:06 /usr/bin/prometheus --web.console.libraries=/usr/share/prometheus/console_libraries --web.console.templates=/usr/share/prometheus/consoles --config.file=/etc/prometheus/prometheu.yml --storage.tsdb.path=/data/prome_db --storage.tsdb.retention.size=15GB --web.enable-lifecycle --log.level=debug
root      190583  0.0  0.0 221928  1148 pts/0    S+   18:53   0:00 grep --color=auto prometheus
[root@hs25 ~]# cat /etc/prometheus/host_target.yml 
- targets:
  - 2000::24:9290
  - 2000::24:9000
  labels:
   group: '1

[fengtian@hyper1 ~]$ cat /etc/prometheus/prometheus.yml 
global:
  scrape_interval:     5s
  evaluation_interval: 5s

rule_files:
  - "vm.rules"
  - "host.rules"
  - "cluster.rules"

scrape_configs:

  - job_name: host
    scrape_interval: 5s
    scrape_timeout: 5s
    file_sd_configs:
    - files:
      - host_target.yml
      refresh_interval: 5s
    relabel_configs:
    - source_labels: ['__address__']
      separator:     ':'
      regex:         '(.*):.*'
      target_label:  'instance'
      replacement:   '${1}'

**Comment by chris-fengtian-guo** [comment]
I make a drift patch to fix this issue 

[fengtian@hyper1 prometheus_src_build]$ cat 0001-fix-web-target-with-ipv6-address-url.patch 
From fc62eb20897c3bc251adb0e958a38ea3d7f2dc10 Mon Sep 17 00:00:00 2001
From: Guo fengtian <guoft09@chinatelecom.cn>
Date: Fri, 26 Nov 2021 16:44:28 +0800
Subject: [PATCH] fix web target with ipv6 address url

Signed-off-by: Guo fengtian <guoft09@chinatelecom.cn>
---
 web/api/v1/api.go | 75 +++++++++++++++++++++++++++++++++++++++++++++--
 1 file changed, 73 insertions(+), 2 deletions(-)

diff --git a/web/api/v1/api.go b/web/api/v1/api.go
index dc9c01d9a..f79d5c08c 100644
--- a/web/api/v1/api.go
+++ b/web/api/v1/api.go
@@ -854,6 +854,66 @@ func getGlobalURL(u *url.URL, opts GlobalURLOptions) (*url.URL, error) {
 	return u, nil
 }
 
+func convert_ipv6(str2 string) string {
+	/*
+	str := "http://192.168.113.24:9000/metrics"
+	str2 := "http://2000::25:9100/metrics"
+	*/
+	fmt_hdr := "://"
+	fmt_tail := "/"
+	hdr_idx := strings.Index(str2, fmt_hdr)
+	if hdr_idx == -1 {
+		return str2
+	}
+	ip_addr := str2[hdr_idx + len(fmt_hdr):]
+	hdr_tail := strings.Index(ip_addr, fmt_tail)
+	if hdr_tail == -1 {
+		return str2
+	}
+	ip_addr = ip_addr[0:hdr_tail]
+	if strings.Contains(ip_addr, ".") {
+		fmt.Println("str2 is ipv4", ip_addr)
+		return str2
+	}
+	//fmt.Println("ip_addr after index strip =", ip_addr)
+	newstr := strings.Split(str2, "/")
+	fmt.Println(newstr)
+	slen := len(newstr)
+	//fmt.Println("split str len=", slen)
+	if slen > 2 {
+		//fmt.Println("str[1] len=", len(str[1]))
+		find_idx := strings.Index(newstr[2], ":")
+		/*
+		fmt.Println("str[0]=", newstr[0])
+		fmt.Println("str[1]=", newstr[1])
+		fmt.Println("str[2]=", newstr[2])
+		fmt.Println("split > 2. find_idx=", find_idx)
+		*/
+		var url_ipv6 string
+		if find_idx != -1 {
+			//fmt.Println("find ipv6 with :")
+			ipv6_addr := newstr[2]
+			var last_idx int = -1
+			for idx := 0; idx < len(ipv6_addr); idx ++ {
+				if ipv6_addr[idx] == ':' {
+					last_idx = idx
+					fmt.Println("find : idx=", idx)
+				}
+			}
+			ipv6_new := ipv6_addr[0:last_idx]
+			//fmt.Println("ipv6 new=", ipv6_new)
+			url_ipv6 = newstr[0] + "//[" + ipv6_new + "]" + ipv6_addr[last_idx:] + "/"
+			//fmt.Println("ipv6 url after modify=", url_ipv6)
+			for idx := 3; idx < slen; idx ++ {
+				url_ipv6 += newstr[idx]
+			}
+			fmt.Println("ipv6 url after modify=", url_ipv6)
+			return url_ipv6
+		}
+	}
+	return str2
+}
+
 func (api *API) targets(r *http.Request) apiFuncResult {
 	sortKeys := func(targets map[string][]*scrape.Target) ([]string, int) {
 		var n int
@@ -890,17 +950,28 @@ func (api *API) targets(r *http.Request) apiFuncResult {
 				lastErrStr := ""
 				lastErr := target.LastError()
 				if lastErr != nil {
+					level.Error(api.logger).Log("msg", "fguo=", lastErr.Error)
 					lastErrStr = lastErr.Error()
 				}
 
 				globalURL, err := getGlobalURL(target.URL(), api.globalURLOptions)
+				level.Error(api.logger).Log("msg", "fguo=target.URL", target.URL())
+				level.Error(api.logger).Log("msg", "fguo=globalURL", globalURL.String())
+				level.Error(api.logger).Log("msg", "fguo key=", key)
+				str_orig := target.URL().String()
+				str2 := convert_ipv6(str_orig)
+				/*
+				if strings.Contains(str2, "::") {
+					str2 = "http://[2000::25]:9100/metrics"
+				}
+				*/
 
 				res.ActiveTargets = append(res.ActiveTargets, &Target{
 					DiscoveredLabels: target.DiscoveredLabels().Map(),
 					Labels:           target.Labels().Map(),
 					ScrapePool:       key,
-					ScrapeURL:        target.URL().String(),
-					GlobalURL:        globalURL.String(),
+					ScrapeURL:        str2,
+					GlobalURL:        str2,
 					LastError: func() string {
 						if err == nil && lastErrStr == "" {
 							return ""
-- 
2.27.0

**Comment by LeviHarrison** [comment]
I believe https://github.com/prometheus/prometheus/issues/8623 already covers this issue, and https://github.com/prometheus/prometheus/pull/9853 should offer an interim fix.

**Comment by roidelapluie** [comment]
http://2000::24:9290 ?? What is prometheus doing with that? Scraping 2000:0:0:0:24:9290 on port 0 or 2000:0:0:0:0:24 on port 9290? You should fix your scrape configuration and we could reject this URL I think.

**Comment by chris-fengtian-guo** [comment]
1) the 2000::24 is compressed ipv6 address of 2000::24:9290  and 9290 is port of ipmi-exporter
the prometheus can scrape data from 2000::24:9290 success but just the generated url is invalid because lack of []
2) Thanks for LeviHarrison
I should report the issue more early, I found this bug more than 1 weeds before and make a drift patch to make it help

**Comment by chris-fengtian-guo** [comment]
this issue is fixed by 
https://github.com/prometheus/prometheus/issues/9760
