### ISSUE TITLE
Potential Race condition when compacting head and receiving samples at the same time

### ISSUE THREAD

**Issue by alanprot** [prometheus/prometheus#9879]
We run cortex and we are seeing some blocks with samples out of order or duplicated samples. Looking into the issue seems that tsdb is accepting those samples due some race condition.

https://github.com/cortexproject/cortex/issues/4573 has a detailed explanation what we see on our side but basically seems we have a race condition when receiving samples for a series that is being GC'ed after head compaction.

Ex Timeline:
* SeriesA had samples from 22:00 to 23:50
* At 1:30 u  compact a new block (with data up to 00:00)
* We receive a new sample (t1, v1) for SeriesA and the push go routineA is on [this](https://github.com/prometheus/prometheus/blob/e63b85be4fd7a6425dc697adc8244065028dfae2/tsdb/head_append.go#L243) line
* At the same point the SeriesA is gced [here](https://github.com/prometheus/prometheus/blob/e63b85be4fd7a6425dc697adc8244065028dfae2/tsdb/db.go#L969) and [here](https://github.com/prometheus/prometheus/blob/e63b85be4fd7a6425dc697adc8244065028dfae2/tsdb/head.go#L1377)
*  routineA resume and (t1, v1)  is pushed to the store (even though the series was gc'ed already)
* We receive another sample  (t1, v2), we create the SeriesA in memory and allow this push. 

**What did you do?**

Run Cortex and send very sparse data with duplicated samples. It will eventually happen.

Repro case (Unit test): https://github.com/alanprot/prometheus/commit/e30d8710b1e7ad2fbc6b2d3e0d59f76a58ba6807

Maybe a potential fix could be something like: https://github.com/alanprot/prometheus/commit/fbc420637e52c83cd074bf5d77c4b643f681bf83

**What did you expect to see?**

Duplicates samples should not be ingested and shipped to the block.

**What did you see instead? Under which circumstances?**

Duplicated samples are ingested.

**Environment**
Cortex but it seems that the problem can happen in prometheus as well.

**Comment by roidelapluie** [comment]
cc @codesome

**Comment by codesome** [comment]
@alanprot was there any forced compaction called on TSDB? (like /shutdown or /flush calls on the Cortex ingesters?) This race sample should have resulted in "out of bounds" error ideally (i.e. overlaps the compaction).

But I think some other concurrent append can move the out of bound time while allowing this race sample to be appended. The right fix for this would be to re-check the out of bound property (i.e. not overlapping with compaction) for the GCed series for the head block's latest maxTime in Commit() instead of discarding the sample altogether.

**Comment by alanprot** [comment]
Hi, thanks for looking into this.

We may have restarted the ingesters but we never called the force compaction ( /shutdown or /flush).

**Comment by alanprot** [comment]
Hi @codesome I think i see what you mean but this still can happen right?

From the timeline:

1. SeriesA had samples from 22:00 to 23:50
1. At 1:30 u  compact a new block (with data up to 00:00)
1. We receive a new sample (t1, v1) for SeriesA and the push go routineA is on [this](https://github.com/prometheus/prometheus/blob/e63b85be4fd7a6425dc697adc8244065028dfae2/tsdb/head_append.go#L243) line 
1. At the same point the SeriesA is gced [here](https://github.com/prometheus/prometheus/blob/e63b85be4fd7a6425dc697adc8244065028dfae2/tsdb/db.go#L969) and [here](https://github.com/prometheus/prometheus/blob/e63b85be4fd7a6425dc697adc8244065028dfae2/tsdb/head.go#L1377)
1.  routineA resume and (t1, v1)  is pushed to the store (even though the series was gc'ed already)
1. We receive another sample  (t1, v2), we create the SeriesA in memory and allow this push. 

So i think what you are saying is that step 3 should throw an "out of bounds" error, but this condition is checked at line [L237](https://github.com/prometheus/prometheus/blob/e63b85be4fd7a6425dc697adc8244065028dfae2/tsdb/head_append.go#L237), so if this go routine has already passed that line, and we trigger a compactHead (truncateMemory + gc), the truncateMemory function will indeed update the `minValidTime ` field but is already too late.

**Comment by alanprot** [comment]
> The right fix for this would be to re-check the out of bound property (i.e. not overlapping with compaction) for the GCed series for the head block's latest maxTime in Commit() instead of discarding the sample altogether.

So any samples that are appended but not committed should be discarded if `truncateMemory` is called? This seems a more drastic change as on my change we are only discarding if `truncateMemory` AND the series got gc'ed.

**Comment by codesome** [comment]
Let's replace 1:30 with 1:00, which is the actual thing that will happen.

So I am assuming `t1` is before 00:00, hence the issue happens.

In that case yes, we need to consider such samples as out of bound immediately after `truncateMemory`, because at that point a block has been cut, and if we allow this sample to go in, it can overlap with a block on disk.

We already do something like that for out of order samples. So it might be as simple as checking for out of bound in [this loop](https://github.com/prometheus/prometheus/blob/e63b85be4fd7a6425dc697adc8244065028dfae2/tsdb/head_append.go#L448-L464).

Would you like to open a PR? It should be a simple one, checking for out of bound only requires [this](https://github.com/prometheus/prometheus/blob/e63b85be4fd7a6425dc697adc8244065028dfae2/tsdb/head_append.go#L237).

**Comment by alanprot** [comment]
> Let's replace 1:30 with 1:00, which is the actual thing that will happen.
Yes... correct. 

I would love to create a PR but i still a little confused. Seems that when we call `truncateMemory` we don't update the `headAppender#minValidTime` right? So this would not have any effect.

Seems that in this case we would need to check the `headAppender#head.minValidTime`?

Doing this change I still get the error:

```
        	Error:      	Received unexpected error:
        	            	
        	            	metric output does not match expectation; want:
        	            	
        	            	# HELP prometheus_tsdb_head_samples_appended_total Total number of appended samples.
        	            	# TYPE prometheus_tsdb_head_samples_appended_total counter
        	            	prometheus_tsdb_head_samples_appended_total 2508
        	            	
        	            	got:
        	            	
        	            	# HELP prometheus_tsdb_head_samples_appended_total Total number of appended samples.
        	            	# TYPE prometheus_tsdb_head_samples_appended_total counter
        	            	prometheus_tsdb_head_samples_appended_total 2509
```

**Comment by codesome** [comment]
> I would love to create a PR but i still a little confused. Seems that when we call truncateMemory we don't update the headAppender#minValidTime right? So this would not have any effect.

Oh right, we need to check from the Head as well.

> Doing this change I still get the error:

Not sure I understand what change is it

**Comment by codesome** [comment]
> Why you don't like the Abort flag?

It will discard the sample even if it was a valid sample and did not overlap with the compaction. We should not be discarding any sample without a reason. In this case, we should discard the sample only if we know if it went out of bounds, else we are falsely counting any sample that comes under these conditions as an out of order sample.

**Comment by codesome** [comment]
> I just have one concern about that. the head minValidTime is an atomic.Int64 so checking this on the commit maybe can have a perf impact?

That is true. Maybe we want a version of your abort flag idea - have the flag, but only discard the sample if it goes out of bound. Hence we call the minValidTime() function only if the flag was set to true.

**Comment by alanprot** [comment]
Seems that this fix also does not fix the race condition: :(

```
		abort := series.abortCommit && s.T < a.head.minValidTime.Load()
		ok, chunkCreated := false, false
		if !abort {
			ok, chunkCreated = series.append(s.T, s.V, a.appendID, a.head.chunkDiskMapper)
		}
```

And the reason for that is that the series are removed from the map on the GC method https://github.com/prometheus/prometheus/blob/cd739214ddfe5ce5efd57e7a4c65d727d0b1227c/tsdb/head.go#L1409 and the minTime is only updated after in the `truncateMemory` method with no locking https://github.com/prometheus/prometheus/blob/cd739214ddfe5ce5efd57e7a4c65d727d0b1227c/tsdb/head.go#L842

When i have some time i will run the fix with just abort for a long time in our test env and see if fiz the issue and everything works fine.

**Comment by alanprot** [comment]
Hi @codesome 

https://github.com/alanprot/prometheus/commit/4b8e99d1e89f3f51f4669bf8e3c3ba4f8a213bed

This change also fix the problem (and also another datapoint to prove we have a race condition on that code). What do you think?

**Comment by alanprot** [comment]
Hi @codesome 

I created a PR to try to address this.... I changed the repro case to use a real TSDB to make sure that this problem really exists.

Thanks

**Comment by beorn7** [comment]
Hello from the bug scrub!

#10624 got closed with the assumption that the problem has been addressed implicitly by other changes. While we cannot be sure, of course, no recurrence of this problem was reported in a while. We'll close this, but please follow up or open a new issue if you see anything like this.
