### ISSUE TITLE
Possible copyright violation in unquote function

### ISSUE THREAD

**Issue by cugu** [prometheus/prometheus#9884]
The prometheus [`unquote` function](https://github.com/prometheus/prometheus/blob/46c52607611992aeee631a1e19f053d886ca34d4/util/strutil/quote.go#L24) looks like it is largely inspired by the (former) [`unquote` function in Go's strconv package](https://github.com/golang/go/blob/015423a15bcfae148d5121bcf4ba5b50d0847cd0/src/strconv/quote.go#L362).

Neither the file itself nor the [NOTICE](https://github.com/prometheus/prometheus/blob/main/NOTICE) file list the Go copyright.

I am not proficient in software law, but shouldn't the copyright notice be added somewhere?

**Comment by JessicaGreben** [comment]
Looked at this in the bug scrub meeting, this claim seems valid. @juliusv are you able to fix it as you are the author?

**Comment by juliusv** [comment]
Thanks for pointing this out, totally true that the appropriate notices are missing here, sorry about that!

Here's a PR to address it: https://github.com/prometheus/prometheus/pull/9942
