### ISSUE TITLE
An error occurred Error: Failed to construct'URL': Invalid URL but the status is up

### ISSUE THREAD

**Issue by shixinghong** [prometheus/prometheus#9885]
![image](https://user-images.githubusercontent.com/56341144/143832092-681cf384-8cb0-4fcf-b708-d32ce09cdea5.png)

![image](https://user-images.githubusercontent.com/56341144/143832190-bd8d0865-8ec2-4302-a6c4-c21206cd843b.png)

As shown in the figure above, I deliberately modified the configuration to: 9000,
Is this state the most reasonable for down?
If the status is up, the target was wrong.

Is this a bug
Or does anyone have any solution?

**Comment by weixing-dev** [comment]
typo: port 9090

**Comment by mtfoley** [comment]
May be related to #9760 and #9872 , and a PR was merged today that may fix this issue, #9853

**Comment by JessicaGreben** [comment]
This issue should be fixed with #9853, but @shixinghong we recommend you to change your config from `:9090` to `localhost:9090`.
