### ISSUE TITLE
Make global labels useful

### ISSUE THREAD

**Issue by brian-brazil** [prometheus/prometheus#991]
Global labels aren't currently very useful as they tend to get aggregated away. I propose that we add in global labels if the given label isn't already present for alerting, federation and long term storage.

**Comment by fabxc** [comment]
We should do the same for recording or don't attach them on regular ingestion either.

**Comment by brian-brazil** [comment]
I'm thinking removing the attachment on regular ingestion.

**Comment by fabxc** [comment]
Closed via #1051
