### ISSUE TITLE
promql: `histogram_quantile` implicitly sums together metrics with the same labelset

### ISSUE THREAD

**Issue by beorn7** [prometheus/prometheus#9910]
**What did you do?**

I ran the following query with multiple histograms with a name matching the regexp:

```PromQL
histogram_quantile(0.99, {__name__=~"rpc_durations_histogram_.*seconds_bucket"})
```

**What did you expect to see?**

I expected to see the following error:

_Error executing query: vector cannot contain metrics with the same labelset_

This error happens if I run queries like the following:

```PromQL
sqrt({__name__=~"rpc_durations_histogram_.*seconds_bucket"})
rate({__name__=~"rpc_durations_histogram_.*seconds_bucket"}[5m])
```

**What did you see instead? Under which circumstances?**

A result is calculated:

```
{instance="localhost:8080", job="example"}      0.0004940000000000007
```

What `histogram_quantile` implicitly does is a `sum` aggregation on all histograms that have the same label set and differ only by name. You could write the query above as follows:

```PromQL
histogram_quantile(0.99, sum without()({__name__=~"rpc_durations_histogram_.*seconds_bucket"}))
```

This is surprising, both from a semantic point of view as well as for the simple reason that it is entirely undocumented. No other PromQL function behaves in that way. All other functions process the vector normally element by element. If that results in a collisions of label sets (due to the removal of the name label that some functions do), the above error message is issued.

**Environment**

This is relevant for all Prometheus versions to date with the `histogram_quantile` function.

**Discussion**

The question is of course if this is a bug or a feature. I'm fairly certain the behavior wasn't intended when implementing `histogram_quantile` but is an unfortunate byproduct.

I think of it as a fundamental breach of PromQL semantics, as already explained above.

I assume that nobody so far has run into it because two rare usage pattern must coincide:
 1. Call `histogram_quantile` on a bare histogram without `rate` (which is very rarely useful).
 2. Call `histogram_quantile` on a vector of differently named elements with otherwise the same labels.

If you tried to `rate` the above query, i.e. `histogram_quantile(0.99, rate({__name__=~"rpc_durations_histogram_.*seconds_bucket"}[5m]))`, you obviously get the usual error message, i.e. _Error executing query: vector cannot contain metrics with the same labelset_.

**Summary**

I think this should be considered a bug, and we should fix the behavior to yield the same error message as all other functions in that case.

This is in contrast to considering it a feature (albeit an unintended one), which would turn a bug fix into a breaking change.

I think the fix (or breaking change) will effect only very few users, if any at all. In the cases where it does, it will result in an error, i.e. it won't be a silent breakage. Furthermore, if someone really has created queries affected by the fix, it is highly likely that it has happened by accident and not to deliberately utilize this surprising undocumented behavior.

**Comment by David-N-Perkins** [comment]
@beorn7 I've got a [PR](https://github.com/prometheus/prometheus/pull/10140) up for this. Can you take a look at it?
