### ISSUE TITLE
document how derivatives are calculated

### ISSUE THREAD

**Issue by sed-i** [prometheus/prometheus#9929]
It would be handy if the docs specified how derivatives are calculated under different scenarios, for example:

- forward differences / central differences / etc.
- first order / second order / etc.
- first resample the data and then differentiate, or first differentiate and then resample?

For example, maybe to calculate the derivative at the left-most point (boundary) you take a second-order forward difference, and at the right-most point (boundary) you take second order backward difference.

https://github.com/prometheus/prometheus/blob/54e2efcda0142b05eece9bd567a3b1702a26a593/docs/querying/functions.md#L335-L340

**Comment by mtfoley** [comment]
I had some experience with some of these calcs in a recent PR, I can take a crack at this one in a new PR.

I believe the TL;DR is that a least-squares linear regression is performed and the slope of the resulting trend line is used in the output. There are caveats to account for time series values (i.e. large x values) and to deal with float64 numeric types in summation.

cc: @beorn7

**Comment by beorn7** [comment]
Note that `rate` and friends are working very differently from `deriv`. I'm not sure which one the OP is referring to.

For the former, see https://promlabs.com/blog/2021/01/29/how-exactly-does-promql-calculate-rates as an excellent starter.

For `deriv`, we are indeed doing a least-squares linear regression (IIRC), but it should be noted that I would prefer to replace our DIY implementation by a proper numerical library, see also #7180 and #5692.

**Comment by mtfoley** [comment]
based on the `rate()` having a pretty substantial docs section compared to others, i guessed that the OP was talking about a need in the docs about the `deriv()` function. I don't see it as exhibiting especially different behavior at "boundaries" of the range vector. I linked a PR and cc'd you @sed-i.
