### ISSUE TITLE
Figure out approach to regex anchoring

### ISSUE THREAD

**Issue by brian-brazil** [prometheus/prometheus#996]
We've got regexes in a few places, we should ensure we're happy they're all anchored in a way that's consistent and doesn't cause surprises. I believe they're all currently unanchored, which I'm not sure makes sense for selectors at least.

**Comment by juliusv** [comment]
Agreed. Full string matches would be more useful than substring matches in most cases, and people are already using it wrong. I'm even considering breaking that for selectors, although it will be painful :-/

**Comment by brian-brazil** [comment]
:+1: on full anchoring

**Comment by juliusv** [comment]
We have the following unanchored regex usages in the Prometheus server:

- `reReplaceAll` template function
- `match` template function
- `label_replace` function
- regex label selectors
- relabeling (including `labelmap` matching)

@brian-brazil Do any of them make sense to stay unanchored, like the `reReplaceAll` function?

/cc @fabxc

**Comment by brian-brazil** [comment]
The template functions should remain as-is, as they're straight calls to the relevant Go functions. `reReplaceAll` must be unanchored to be useful.

**Comment by juliusv** [comment]
@brian-brazil That's what I suspected. Ok, so I'll anchor all but the template functions then.

**Comment by juliusv** [comment]
All points addressed by the referenced PRs. Closing.
