### ISSUE TITLE
SelectHints should contain function parameters in addition to the function name

### ISSUE THREAD

**Issue by fpetkovski** [prometheus/prometheus#9979]
## Proposal
**Use case. Why is this important?**

We would like to optimize the retrieval of SeriesSets by pre-computing the result for certain aggregations. 
This is currently possible to do for aggregations like `max` and `min`, but not for `topk` and `bottomk` because the latter two aggregations have an additional parameter which is not provided in the SelectHints: https://github.com/prometheus/prometheus/blob/655e2d28795ff5b1532778d7ce2f014e4a76da6f/promql/engine.go#L777-L783

I am more than happy to make the contribution myself, I just wanted to know whether there are any objections to having the parameters in addition to the function name.

**Comment by roidelapluie** [comment]
As per previous dev summit, I'd prefer to have a design doc about how we would shard promql queries in the future, instead of changing the protocol right away. I do not know when/who would work on that design doc.

If we do not foresee this in a relativaly close future, we could add this.

**Comment by bwplotka** [comment]
Ack, we can try combining all we need to add to hints into one proposal to make sure Thanos can use the same APIs, PromQL engine and Prometheus engine can responds to those hints results.

**Comment by beorn7** [comment]
Hello from the bug scrub!

@bwplotka @fpetkovski is this still relevant? If so, do you know anyone who has capacity to work on it?

**Comment by fpetkovski** [comment]
I don't think this is very relevant for Thanos anymore since we have a better way to distribute queries today. I would be fine with closing this issue.

**Comment by beorn7** [comment]
OK, closing this for now. Of course, it's always easy to re-open. :)
